### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by rudijs** [firehol/netdata#10]
Hi,

Before I go ahead and create my own, do you know if this app has already been "dockerized"?

If not, I'll go ahead and create a public image.

I'd like to use netdata on multiple Ubuntu machines, so it makes sense to containerize it.

Thanks.

**Comment by ktsaou** [comment]
Hi,

I am not aware of anyone having done that.
If you do and you would like to share your work, I would be glad to include it in the official repo.

**Comment by rudijs** [comment]
Hi,

Ok cool, for sure I'd like to contribute.

Leave it with me and I'll follow up.

Cheers

**Comment by rudijs** [comment]
Hi,

I've been looking into this a little in my free time, but am stuck on one thing.

I could be confusing myself, so I'll elaborate a little.

I'm not sure how to containerize the application code that reads from /proc.

Ex:

    fp = fopen("/proc/net/dev", "r");

That code would read from the container's /proc not from the host OS (which is what we want?).

I've used containers that read from the hosts /var/log directory, but to do that I mount the host /var/log into /host/var/log in the container. Then the application code reads from /host/var/log.

I can see how netdata could be used in both the host OS and the container, but my initial goal is to see if I can get a container to read from the host.

If that works out, the one image could be deployed across many hosts via many containers (from the one source image).

So I've asked on the Docker forum, but no responses - I might take the same question to stackoverflow.

One option I thought of earlier, but kind of wrote it off as it's a hassle, would be if the source code has constants for the path to resources.

Ex:

const procNetDev = '/proc/net/dev'

and then have a flag that would in some way allow these resource constants to be prepended with '/host/

The container would then mount the host OS /proc into /host/proc.

To be honest though I'm not sure if this is the correct approach.

So this is currently where I'm at with this.

**Comment by ktsaou** [comment]
ok.

I have added config file options to set all /proc and /sys files used by netdata.

To see the config lines you need to change just point your browser to:

```
http://your-linux-host:19999/netdata.conf
```

This will give you the default config for all options supported.
Then search for `filename to monitor`.

You can also get the list, by running this on the same host as netdata:

```bash
curl 2>/dev/null "http://localhost:19999/netdata.conf" | less -p  "filename to monitor"
```

**Comment by rudijs** [comment]
OK cool - that's was quick!

So I've taken a look at it and this is what I gather so far.

From a fresh git clone, or gzip download, run ./netdata.start which creates the netdata.conf file.

Looking into netdata.conf the first 'filename to monitor' so get to is `# filename to monitor = /proc/net/dev`

So in the context of a Docker container if we mount the host's or another container's `/proc` into `/host/proc` we need it to be `# filename to monitor = /host/proc/net/dev`

As the netdata.conf file is created at start time and defaults to /proc/net/dev we'd need to edit the netdata.conf file then restart the container.

It's gets a bit awkward if the container is ephemeral as those files are not persisted to the host's filesystem.

We'd perhaps need to do something like "sudo docker exec netdata-container sed -e /^\/proc/\/host\/proc/g" then kill and restart netdata.

All that is doable, but a better option might be to alter the netdata.start so that is can do something like "netdata.start --plugin_path /host"

Something like that so the netdata.conf file is initially created to work from /host, then no need to fiddle with path and restart.

With something like this in place netdata could be used three ways:

1) As it is now deployed on host reading from host
2) Deployed as a Docker container reading from host
3) Deployed as a Docker container reading from another container

A valid use can I can think of is something like I'm doing now:

1) Netdata container to read from host
2) Netdata container to read from NGINX container
3) Netdata container to read from NodeJS application container

In all 3 containers they'd be using "netdata.start --plugin_path /host" (or soemthing like that.)

These containers would all be deployed from the same docker source image that could easily be hosted at hub.docker.com.

What do you think?

I think what I'm suggesting requires a bit code refactoring and might be a hassle, I could also be on the wrong track.

My thoughts on this are based on something I'm already doing with logstash-forwarder.

It's a simialar application to how I'm suggesting here .. it reads from /host/var/log and can read from host OS or other containers.

It's difference with this approach here is no command line flags, it reads from a config file you provide to the docker container.

https://hub.docker.com/r/rudijs/docker-logstash-forwarder/~/dockerfile/

**Comment by ktsaou** [comment]
You are right.
It needs some refactoring though.
Give me some time to do it.

**Comment by ktsaou** [comment]
ok, here it is.

Added command line option `-ch /path/to/use/as/prefix` which will prefix all `/proc/` and `/sys/` paths accessed by netdata.

Keep in mind though that this option will only affect the core of netdata. Supporting this prefix in plugins.d and charts.d modules needs more work...

**Comment by rudijs** [comment]
I've forked the repo and started a docker branch and had some good success.

There's one issue though, we need the process to be able to run in the foreground.

As it is now the web server runs as a background process so when you start a docker container in daemon mode the netdata app starts, then the container closes.

Running the container in non daemon mode and it works sweet.

This foreground process step is the exact same this done with NGINX.

The official NGINX docker image has this build command:

    CMD ["nginx", "-g", "daemon off;"]

Is this foreground option something already available in the netdata binary? Or is it easy to rig up?

We'd need another start up config option along with the '-ch' flag.

You can see the Dockerfile and bottom of the README.md here:

https://github.com/rudijs/netdata/tree/docker

**Comment by ktsaou** [comment]
ok, here it is this one too.

Let me know how it goes...

**Comment by ktsaou** [comment]
Rudi I saw you are passing parameters to netdata.start.

I just updated it to actually pass the parameters it gets to netdata.

So, please fork it again before trying the new patches.

**Comment by rudijs** [comment]
Hi,

I've created a fresh repo from the latest netdata source https://github.com/rudijs/netdata/tree/docker

Just working with non-daemon mode currently, so it's:

1. Build the image
2. Launch a netdata container
3. Start the netdata service manually.

Once that's working fine, next steps are to launch the container in daemon mode.

I'm seeing an error at the moment, looks like it's coming out of the compiled code not the shell start script.

Here's the steps and truncated error output:

- Build
- `sudo docker build -t netdata:0.1.0 .`
- Launch
- `sudo docker run -it --rm --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p 19999:19999 netdata:0.1.0 bash`
- Start netdata manually from inside the running container
- `./netdata.start -ch host`

Here's the truncated output.

```
    COMPILING WITH OPTIONS: -Wall -Wextra -O3 -DBIN_DIR='/opt/netdata' -DCONFIG_DIR='/opt/netdata/conf.d' -DLOG_DIR='/opt/netdata/log' -[15/1628]
DIR='/opt/netdata/plugins.d' -fomit-frame-pointer

    INSTALLING apps.plugin to /opt/netdata/plugins.d

 >>> apps.plugin requires root access to access files in /proc
 >>> Please authorize it!


make[2]: Leaving directory `/opt/netdata/src/plugins.d'

    INSTALLING netdata to /opt/netdata

make[1]: Leaving directory `/opt/netdata/src'
Fixing directory permissions for user nobody...
Stopping a (possibly) running netdata...
Starting netdata...
15-10-18 03:43:17: ERROR: netdata: Cannot open file '/opt/netdata/conf.d/netdata.conf' (errno 2, No such file or directory)
rm: cannot remove 'conf.d/netdata.conf.new': No such file or directory

OK. NetData started! Hit http://localhost:19999/ from your browser.

Enjoy...
```

It's not happy creating /opt/netdata/conf.d/netdata.conf, however after the command is run and I ls:

```
root@168f57fb86a9:/opt/netdata# ll
total 312
drwxr-xr-x 14 root   root   4096 Oct 18 03:43 ./
drwxr-xr-x  4 root   root   4096 Oct 18 03:43 ../
drwxr-xr-x  8 root   root   4096 Oct 18 03:32 .git/
-rw-r--r--  1 root   root     53 Oct 18 03:32 .gitignore
-rwxr-xr-x  1 root   root    882 Oct 18 03:32 Makefile*
-rwxr-xr-x  1 root   root   8666 Oct 18 03:32 README.md*
drwxrwxr-x 24 nobody root   4096 Oct 18 03:43 cache/
drwxr-xr-x  2 root   root   4096 Oct 18 03:32 charts.d/
drwxrwxr-x  2 nobody root   4096 Oct 18 03:43 conf.d/
drwxrwxr-x  2 nobody root   4096 Oct 18 03:43 log/
-rwxr-xr-x  1 root   root 252580 Oct 18 03:43 netdata*
-rwxr-xr-x  1 root   root   3380 Oct 18 03:32 netdata.start*
drwxr-xr-x  2 root   root   4096 Oct 18 03:43 plugins.d/
drwxr-xr-x  5 root   root   4096 Oct 18 03:43 src/
drwxrwxr-x  2 nobody root   4096 Oct 18 03:43 web/
```

conf.d should be writeable by both root and nobody.

```
root@168f57fb86a9:/opt/netdata# ls conf.d/
apps_groups.conf
```

Hrmmm... what might be the issue?

**Comment by ktsaou** [comment]
probably my fault.
Could you please try the new netdata.start?

**Comment by ktsaou** [comment]
One issue that will exist if you use the `-nd` option, is that the config file will never be created. `netdata.start` relies on netdata being forked for it to download the config file for the first time.

So, if you use `-nd` you will have to download the initial config file yourself.

**Comment by rudijs** [comment]
I've update my fork to the lasted commit:

```
commit af154f5018ad4e874d972d065271771d4c2b40fe
Author: Costa Tsaousis (ktsaou) <costa@tsaousis.gr>
Date:   Sun Oct 18 13:19:25 2015 +0300

    prevent a false error message while downloading config file; #10
```

and then rebased my **docker** branch from this latest commit.

Built a new docker image and launched a container:

`sudo docker run -it --rm --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p 19999:19999 netdata:0.1.2 bash`

This drops me into the running container at /opt/netdata:

`root@e6f4cf4e6c77:/opt/netdata#`

From here (inside the running container) I start netdata:

`root@82dcfdb996aa:/opt/netdata# ./netdata.start -ch /host`

I still get the same error as before but things do start up OK:

```
make[2]: Entering directory `/opt/netdata/src/plugins.d'
    COMPILING WITH OPTIONS: -Wall -Wextra -O3 -DBIN_DIR='/opt/netdata' -DCONFIG_DIR='/opt/netdata/conf.d' -DLOG_DIR='/opt/netdata/log' -DPLUGINS_DIR='/opt/netdata/plugins.d' -fomit-frame-pointer

    INSTALLING apps.plugin to /opt/netdata/plugins.d

 >>> apps.plugin requires root access to access files in /proc
 >>> Please authorize it!


make[2]: Leaving directory `/opt/netdata/src/plugins.d'

    INSTALLING netdata to /opt/netdata

make[1]: Leaving directory `/opt/netdata/src'
Fixing directory permissions for user nobody...
Stopping a (possibly) running netdata...
Starting netdata...
15-10-18 12:55:59: ERROR: netdata: Cannot open file '/opt/netdata/conf.d/netdata.conf' (errno 2, No such file or directory)
rm: cannot remove 'conf.d/netdata.conf.new': No such file or directory

OK. NetData started! Hit http://localhost:19999/ from your browser.

Enjoy...

root@82dcfdb996aa:/opt/netdata#
```

Processes:

```
root@82dcfdb996aa:/opt/netdata# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18168  2036 ?        Ss   12:54   0:00 bash
nobody     165  0.3  0.0 468436  6808 ?        SNl  12:55   0:00 /opt/netdata/netdata -ch /host
nobody     170  0.2  0.0   4440   732 ?        SN   12:55   0:00 /bin/sh /opt/netdata/plugins.d/tc-qos-helper.sh 1
root       174  0.2  0.0   4780  1060 ?        SN   12:55   0:00 /opt/netdata/plugins.d/apps.plugin 1
nobody     615  0.0  0.0   4340   356 ?        SN   12:56   0:00 sleep 0.995
root       616  0.0  0.0  15564  1156 ?        R+   12:56   0:00 ps aux
```

Firing up a browser and all charts look OK and render out.

There is no config in conf.d though. Running in this mode there should be yeah?

The process is running in the background, only the -ch flag has been used no -nd as yet (that's next steps).

I've really only *used* netdata not dug into the source code.

Inside the container I installed lsof and ran it, here some truncated output:

```
root@82dcfdb996aa:/opt/netdata# lsof | grep netdata
netdata    165     nobody  cwd   unknown                         /proc/165/cwd (readlink: Permission denied)
netdata    165     nobody  rtd   unknown                         /proc/165/root (readlink: Permission denied)
netdata    165     nobody  txt   unknown                         /proc/165/exe (readlink: Permission denied)
netdata    165     nobody    0   unknown                         /proc/165/fd/0 (readlink: Permission denied)
netdata    165     nobody    1   unknown                         /proc/165/fd/1 (readlink: Permission denied)
netdata    165     nobody    2   unknown                         /proc/165/fd/2 (readlink: Permission denied)
netdata    165     nobody    3   unknown                         /proc/165/fd/3 (readlink: Permission denied)
netdata    165     nobody    4   unknown                         /proc/165/fd/4 (readlink: Permission denied)
netdata    165     nobody    5   unknown                         /proc/165/fd/5 (readlink: Permission denied)
netdata    165     nobody    6   unknown                         /proc/165/fd/6 (readlink: Permission denied)
netdata    165     nobody    7   unknown                         /proc/165/fd/7 (readlink: Permission denied)
...
truncated output
...
netdata    165 173 nobody  cwd   unknown                         /proc/165/task/173/cwd (readlink: Permission denied)
netdata    165 173 nobody  rtd   unknown                         /proc/165/task/173/root (readlink: Permission denied)
netdata    165 173 nobody  txt   unknown                         /proc/165/task/173/exe (readlink: Permission denied)
netdata    165 173 nobody    0   unknown                         /proc/165/task/173/fd/0 (readlink: Permission denied)
netdata    165 173 nobody    1   unknown                         /proc/165/task/173/fd/1 (readlink: Permission denied)
netdata    165 173 nobody    2   unknown                         /proc/165/task/173/fd/2 (readlink: Permission denied)
netdata    165 173 nobody    3   unknown                         /proc/165/task/173/fd/3 (readlink: Permission denied)
netdata    165 173 nobody    4   unknown                         /proc/165/task/173/fd/4 (readlink: Permission denied)
netdata    165 173 nobody    5   unknown                         /proc/165/task/173/fd/5 (readlink: Permission denied)
netdata    165 173 nobody    6   unknown                         /proc/165/task/173/fd/6 (readlink: Permission denied)
netdata    165 173 nobody    7   unknown                         /proc/165/task/173/fd/7 (readlink: Permission denied)
netdata    165 173 nobody    8   unknown                         /proc/165/task/173/fd/8 (readlink: Permission denied)
netdata    165 173 nobody    9   unknown                         /proc/165/task/173/fd/9 (readlink: Permission denied)
netdata    165 173 nobody   10   unknown                         /proc/165/task/173/fd/10 (readlink: Permission denied)
netdata    165 173 nobody   11   unknown                         /proc/165/task/173/fd/11 (readlink: Permission denied)
netdata    165 173 nobody   12   unknown                         /proc/165/task/173/fd/12 (readlink: Permission denied)
netdata    165 173 nobody   13   unknown                         /proc/165/task/173/fd/13 (readlink: Permission denied)
netdata    165 173 nobody   14   unknown                         /proc/165/task/173/fd/14 (readlink: Permission denied)
netdata    165 173 nobody   15   unknown                         /proc/165/task/173/fd/15 (readlink: Permission denied)
lsof      4162       root  cwd       DIR   0,48     4096      12 /opt/netdata
root@82dcfdb996aa:/opt/netdata#
```

I thought it should be readingfrom /host/proc/* ?

**Comment by ktsaou** [comment]
Its the apps.plugin you are seeing... As I said above, these require some more work.

Could you please check that there are lines in lsof with /host/proc ?

Regarding the error, you are not using the latest version of netdata.start.
The latest version throws a line with `OK. NetData started!` and another one with `Hit http://localhost:19999/ from your browser.`. The older versions did both on the same line.

**Comment by rudijs** [comment]
> Its the apps.plugin you are seeing... As I said above, these require some more work.

Ah OK, no probs.

> Could you please check that there are lines in lsof with /host/proc ?

Sure, here ps aux and lsof output just now:

```
root@82dcfdb996aa:/opt/netdata# ps aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18168  1960 ?        Ss   12:54   0:00 bash
nobody     165  0.2  0.0 542168  7112 ?        SNl  12:55   0:04 /opt/netdata/netdata -ch /host
nobody     170  0.0  0.0   4440   732 ?        SN   12:55   0:01 /bin/sh /opt/netdata/plugins.d/tc-qos-helper.sh 1
root       174  0.0  0.0   4780  1060 ?        SN   12:55   0:00 /opt/netdata/plugins.d/apps.plugin 1
nobody   16192  0.0  0.0   4340   360 ?        SN   13:24   0:00 sleep 0.994
root     16193  0.0  0.0  15564  1156 ?        R+   13:24   0:00 ps aux
root@82dcfdb996aa:/opt/netdata# lsof | grep host
root@82dcfdb996aa:/opt/netdata# 
```

> Regarding the error, you are not using the latest version of netdata.start.

Oh .. ok my bad. I was pretty sure I rebased from an upstream/master that I configured.

I'll go that again and try it out, better to rebase than refork again if I can.

Cheers.

**Comment by rudijs** [comment]
> Regarding the error, you are not using the latest version of netdata.start.

Oh .. I rebased OK, but used a cached docker layer for the netdata source code.

Let me report back here before you do anything else, looking into this now.

**Comment by rudijs** [comment]
Yikes! The first docker build steps are failing on me right now, which stops the docker image build entirely.

Looks like an upstream ubuntu packaging issue

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update -y &&    apt-get install git-core lsof curl build-essential zlib1g-dev -y &&     apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Annoying .. it's almost 10pm Sunday night here, think I'll pick this up again on Monday - hopefully overnight this upstream error will get sorted out.

**Comment by rudijs** [comment]
Hi,

OK the apt-get issue has resolved itself, everything is building OK now.

The build is successful and the browser fires up with the graphs/reports all good.

Here's a review of the process (note this is the background mode, foreground will come next)

Step 1 Build

    sudo docker build -t netdata:0.1.0 .

Step 2 start a new container and enter it manually

    sudo docker run -it --rm --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p 19999:19999 netdata:0.1.0 bash

Step 3 start netdata from command line within the container (reading from /host)

    root@22ff851d7179:/opt/netdata# ./netdata.start -ch /host

Here's some of that output (truncated)


```
make[2]: Leaving directory `/opt/netdata/src/plugins.d'

    INSTALLING netdata to /opt/netdata

make[1]: Leaving directory `/opt/netdata/src'
Fixing directory permissions for user nobody...
Stopping a (possibly) running netdata...
Starting netdata...
OK. NetData Started!
Downloading default configuration from netdata...
New configuration saved for you to edit at conf.d/netdata.conf

Hit http://localhost:19999/ from your browser.

Enjoy...

root@22ff851d7179:/opt/netdata# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18164  2000 ?        Ss   04:13   0:00 bash
nobody     164  0.3  0.0 542168 11036 ?        SNl  04:13   0:00 /opt/netdata/netdata -ch /host
nobody     169  0.3  0.0   4440   732 ?        SN   04:13   0:00 /bin/sh /opt/netdata/plugins.d/tc-qos-helper.sh 1
root       173  0.2  0.0   4748  1208 ?        SN   04:13   0:00 /opt/netdata/plugins.d/apps.plugin 1
nobody     338  0.0  0.0   4340   356 ?        SN   04:13   0:00 sleep 0.996
root       339  0.0  0.0  15564  1152 ?        R+   04:13   0:00 ps aux
```

So we can see it's started up OK.

conf.d also has config data, grep for 'host' in it:

```
root@22ff851d7179:/opt/netdata# grep host conf.d/netdata.conf
        # host access prefix = /host
        # hostname = 22ff851d7179
        # filename to monitor = /host/proc/net/dev
        # filename to monitor = /host/proc/interrupts
        # filename to monitor = /host/proc/sys/kernel/random/entropy_avail
        # filename to monitor = /host/proc/diskstats
        # path to get h/w sector size = /host/sys/block/%s/queue/hw_sector_size
        # filename to monitor = /host/proc/net/snmp
        # filename to monitor = /host/proc/net/netstat
        # filename to monitor = /host/proc/net/stat/nf_conntrack
        # filename to monitor = /host/proc/net/ip_vs_stats
        # filename to monitor = /host/proc/stat
        # filename to monitor = /host/proc/meminfo
        # filename to monitor = /host/proc/vmstat
        # filename to monitor = /host/proc/net/rpc/nfsd
```

Looks good. Now lsof and grep for 'host'

```
root@22ff851d7179:/opt/netdata# lsof | grep host
root@22ff851d7179:/opt/netdata#
```

Should we see '/host' in the lsof output?

Without grepping for 'host' here's some truncated output:

```
...
...
netdata    164 166 nobody  cwd   unknown                       /proc/164/task/166/cwd (readlink: Permission denied)
netdata    164 166 nobody  rtd   unknown                       /proc/164/task/166/root (readlink: Permission denied)
netdata    164 166 nobody  txt   unknown                       /proc/164/task/166/exe (readlink: Permission denied)
netdata    164 166 nobody    0   unknown                       /proc/164/task/166/fd/0 (readlink: Permission denied)
netdata    164 166 nobody    1   unknown                       /proc/164/task/166/fd/1 (readlink: Permission denied)
netdata    164 166 nobody    2   unknown                       /proc/164/task/166/fd/2 (readlink: Permission denied)
netdata    164 166 nobody    3   unknown                       /proc/164/task/166/fd/3 (readlink: Permission denied)
netdata    164 166 nobody    4   unknown                       /proc/164/task/166/fd/4 (readlink: Permission denied)
netdata    164 166 nobody    5   unknown                       /proc/164/task/166/fd/5 (readlink: Permission denied)
...
...
```

**Comment by rudijs** [comment]
Costa,

```
One issue that will exist if you use the -nd option, is that the config file will never be created. netdata.start
relies on netdata being forked for it to download the config file for the first time.

So, if you use -nd you will have to download the initial config file yourself.
```

I think the *-nd* option is going to be used pretty much in all use cases of the netdata in Docker.

Just like with NGINX, all daemonized use cases run NGINX in the foreground (so the Docker container will not exit).

What are some options for setting up the config file manually?

Is there a set of defaults we could configure, then copy that file into the docker image or container at build or run time?

Again simialar to NGINX where you can load in your own NGINX config files (vhosts etc) at container run time.

For example in my custom NGINX containers I copy in the SSL configuratin files when the image is made, so containers launched have that installed and ready to go.

**Comment by titpetric** [comment]
The docker image is available: https://hub.docker.com/r/titpetric/netdata/ - tested as a local build, and as a build installed from the docker hub.

Apps metrics are not correct, I'm opening a separate issue for it, suggesting to close this thread.
