### ISSUE TITLE
Bind socket to specific address rather than *

### ISSUE THREAD

**Issue by squash** [firehol/netdata#100]
Currently to restrict access to the tool, the process is to create an iptables rule to block access on your external interface, and set up mod_proxy or similar to proxy connections to the localhost interface. Being able to specify the interface or address to bind to would simplify this process in a way that you won't forget after a reboot. :)

**Comment by jstn** [comment]
Seconded!

**Comment by cbricart** [comment]
actually - I would prefer the idea to just bind to 127.0.0.1:<someport> (or even just a unix-socket) and reverse-proxy that using any other webserver - like `nginx`, `pound`, `apache` or whatever YMMV ..

**Comment by ElectronicWar** [comment]
I think this is really important and a must-have for any software running on an internet-facing system. All my interfaces are reverse-proxied through my local nginx instance and get their forced HTTPS this way as well.

**Comment by zquestz** [comment]
Yeah this is essential. Lots of users will want this merely on localhost, or a specific nic.

**Comment by zquestz** [comment]
This does work, but is based on ip not interface. Just set your `/etc/netdata/netdata.conf` to:

```
[global]
bind socket to IP = 127.0.0.1
```

**Comment by ktsaou** [comment]
It has been implemented last week. Sorry! I forgot to mention it here (I did somewhere else, but I lost this).

Keep in mind that if you bind it to `::1` it will bind to both IPv4 and IPv6, while `127.0.0.1` binds only to IPv4 (the kernel does this, not netdata).

**Comment by ktsaou** [comment]
Cleaning up. If something remains open it again.
