### ISSUE TITLE
netdata-updater.sh line 15: pidof: command not found

### ISSUE THREAD

**Issue by AckRiteris** [firehol/netdata#1000]
Got this when executing the script via cron. Should I ignore this?
Script works when launched from command line, pidof exists.

Relevant crontab (ran as root):
0 5 * * * /netdata/netdata-updater.sh

**Comment by ktsaou** [comment]
It will not harm if missing.
However this command is pretty standard on all linux systems.
Which distribution do you use?

**Comment by AckRiteris** [comment]
CentOS 6.7 . That's the weird part - command exists and runs, just not in the script.

**Comment by ktsaou** [comment]
hm... is it in `/sbin` or `/usr/sbin`?

**Comment by ktsaou** [comment]
I made a change to inherits the PATH from the installer. If it is PATH related, this will fix it.
