### ISSUE TITLE
Service copied to wrong location

### ISSUE THREAD

**Issue by solitaryr** [firehol/netdata#1004]
Hello,

I'll be the first to say that I am not an expert in this area since I'm still coming up to speed on systemd.  However, I believe the better way to add a service on RHEL, CentOS 7 would be to change a couple of the steps in "starting netdata at boot" instructions to

# copy netdata.service to systemd
cp system/netdata.service /usr/lib/systemd/system/

# start netdata
systemctl start netdata

**Comment by ktsaou** [comment]
hi,

I think the directory `/usr/lib/systemd/system` is for distribution supplied files. User supplied files should go to `/etc/systemd/system`.

**Comment by paulfantom** [comment]
Systemd service files should be located in `/usr/lib/systemd/system` when installing from binary package so they can be updated while updating package. Also they can be overridden by user-defined service files in `/etc/systemd/system`. This way when updating package, installer doesn't have to check if file changed, while user-defined configuration will be intact.
Basically this is how *nix file system should be used, `/usr` is for packages and configuration files shipped with them, `/etc` is for user-defined configurations. Somehow somewhere in linux programs development this was abandoned. However there is a [movement to get back to this schema](http://0pointer.net/blog/projects/stateless.html).

**Comment by ktsaou** [comment]
I am closing this. If you need help, just post.
