### ISSUE TITLE
nginx_log crashes and doesn't restart

### ISSUE THREAD

**Issue by shadycuz** [firehol/netdata#1007]
After Setting up nginx_log I noticed it works for about 30 mins or so and then it stops reporting. In the logs I found this 

`16-09-21 11:34:57: python.d ERROR: nginx_log_Reverse_Proxy Something wrong:  'No                                                neType' object has no attribute 'group'`

Stopping netdata and restarting fixes the problem for a bit.

**Comment by shadycuz** [comment]
@paulfantom If you need me to turn on tracing to get you more info just let me know. I don't have NGINX locally on the machine I'm running Netdata. 

I'm using rsyslog and RELP to transfer them from my NGINX container to my netdata Host.

**Comment by paulfantom** [comment]
@shadycuz could you test if this [commit](https://github.com/paulfantom/netdata/commit/69c18f4e1ac736e4a3c98c4008d8ec548381fb21) resolves this issue?

**Comment by shadycuz** [comment]
Is it is the latest update? I'm about to go to bed, I'll manually update
when I'm awake again and see what it does

**Comment by paulfantom** [comment]
I created pull request with changes containing fix. It is here:
https://github.com/firehol/netdata/pull/1021

**Comment by shadycuz** [comment]
@paulfantom I might have not installed the fixes right. I copy pasted the changes to my gitclone on my server, Paying attention to remove the one line and added in the new try this, except this statement. I then started netdata. It ran for 5 mins crashed with same error in log, then I restarted it and it ran for about 20 some mins and crashed with the same error. It does crash on the actual webpage and then spits the error to log about 3 mins after.

```
16-09-25 23:45:44: python.d ERROR: nginx_log_Reverse_Proxy Something wrong:  'NoneType' object has no attribute 'group'
16-09-26 00:08:55: python.d ERROR: nginx_log_Reverse_Proxy Something wrong:  'NoneType' object has no attribute 'group'
```

**Comment by paulfantom** [comment]
Could you change `AttributeError` to `Exception` and run it again?

**Comment by shadycuz** [comment]
@paulfantom So far so good, it will need to run for another hour or so to know this issue is fixed and for a while longer to see if anything else crops up but I'm confident so far.

**Comment by shadycuz** [comment]
@paulfantom It ran for 4 1/2 hours.

**Comment by ktsaou** [comment]
does this still happen?

**Comment by shadycuz** [comment]
Yes, let me update just to confirm. And I'll post the logs of it crashes
again

**Comment by shadycuz** [comment]
Still up, I'll let you know in 12 hours

**Comment by ktsaou** [comment]
thanks!

**Comment by shadycuz** [comment]
Still ticking away =) It's up to you if your ready to mark this as closed. I know before it would die with in 15 mins. 

I'm very happy. I run a Nginx reverse proxy in front of my little cloud empire. It's hosted on a LXC container. I monitor my LXC (host) and my Web(host) with netdata and you can imagine that when looking at my web host I want to see the Nginx information with it, not on the LXC page. 

@paulfantom Thank you
@ktsaou  and You Mr.

**Comment by ktsaou** [comment]
ok. I am closing this.
Most probably there is something in the log that makes the module crash. If it happens again, please re-open it. If it happens again, it is important to have it fixed.
