### ISSUE TITLE
Any way to add a http basic auth? Or password protect the page?

### ISSUE THREAD

**Issue by CodeBrauer** [firehol/netdata#101]
Are there any built in features for that?
Some charts maybe leaks information that shouldn't be readable for anyone.

**Comment by hauleth** [comment]
You could use Nginx frontend with HTTP Basic Auth to achieve that.

**Comment by CodeBrauer** [comment]
@hauleth But using a webserver would only work as a proxy - on the port netdata was started, the data is still visible to anyone, isn't it?

**Comment by hauleth** [comment]
If you block it in `iptables

**Comment by CodeBrauer** [comment]
Okay, this should work, thanks!

**Comment by CodeBrauer** [comment]
This works with Apache 2.4 and `mod_proxy`&`mod_proxy_http` enabled

```apache
<VirtualHost *:80>
    ServerName netdata.example.com
    ServerAdmin webmaster@localhost
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia Off
    ProxyPass / http://127.0.0.1:19999/
    ProxyPassReverse / http://127.0.0.1:19999/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

Add htaccess and htpasswd, and done.

**Comment by MarjanSadat** [comment]
hi and thanks for netdata,
is it possible to have an authentication like this before seeing netdata??

![77777777](https://user-images.githubusercontent.com/31684355/48693050-6fc8b080-ebed-11e8-9123-4ed71ccd6241.png)
