### ISSUE TITLE
Zero-based Y axis in charts

### ISSUE THREAD

**Issue by kachkaev** [firehol/netdata#1010]
Hi guys,

I'm pretty new here so sorry in advance if I haven't found something obvious before submitting this issue. I tried my best!

I enjoy netdata a lot – it has already helped me to make an upgrade decision I would not think of otherwise. There is one minor visual trap I'd like to report though. Have a look at this swap chart that I have in front of me pretty much all the time now:

![screen shot 2016-09-22 at 20 27 21](https://cloud.githubusercontent.com/assets/608862/18763100/c123a3ec-8103-11e6-9a1e-69174ba980b4.png)

It feels like all is great, but a closer look reveals that it is not – the swap is being used quite substantially (by about 20%)!

![screen shot 2016-09-22 at 20 28 05](https://cloud.githubusercontent.com/assets/608862/18763112/c8abba3c-8103-11e6-917b-12bceb6d3633.png)

The truth is not easy to spot because of a dynamic range on the Y axis. It starts from about 500 MB at the moment, thus hiding a very important red object!

If the chart always started at zero, the real resource profile could be decoded instantly by the user's brain as colour is a pre-attentive visual variable (unlike the glyphs, which represent the numbers). Not sure that making the base value of Y fixed is a good idea in all situations, but it might be worth considering, at least as an option.

What do you think?

**Comment by ktsaou** [comment]
interesting finding... I can't reproduce it though... On my browsers stacked charts always show zero.
Which OS and browser version you use?

**Comment by kachkaev** [comment]
OSX + latest FF and Chrome

**Comment by kachkaev** [comment]
If there is a way to extract the exact dataset by running something in the browser's console, I'll be happy to share the dump.

**Comment by ktsaou** [comment]
you are so right. I just checked it at browserstack and yes, zero is not shown on mac browsers (don't ask me why - it is inside dygraphs codes).

I just added an option to dygraphs on stacked charts to always include zero. I verified this works on browserstack.

If you want to test it before I merge it, clone my repo (http://github.com/ktsaou/netdata) and install it.

**Comment by kachkaev** [comment]
Amazing! Zero is now in place in both FF and Chrome on OSX!

![screen shot 2016-09-22 at 23 33 55](https://cloud.githubusercontent.com/assets/608862/18768448/15df29f6-811d-11e6-90f9-78303b87734f.png)
(that little gap is me updating netdata)

Many thanks @ktsaou – this is truly a remarkable project!

**Comment by ktsaou** [comment]
ok, thanks!
the change is now merged.

**Comment by kachkaev** [comment]
I just came across the same possible issue in two other charts on Linux Firefox:
![screenshot from 2016-10-18 10-53-48](https://cloud.githubusercontent.com/assets/608862/19473004/96bd5eae-9521-11e6-8307-0fc5ff170247.png)
![screenshot from 2016-10-18 10-54-32](https://cloud.githubusercontent.com/assets/608862/19473002/947dbbf2-9521-11e6-8220-68f556595c5b.png)

Is this intentional or is it a bug?

The version of netdata is recent (I installed it this Sunday).

**Comment by ktsaou** [comment]
Zero is only shown on `stacked` charts. On `line` and `area` charts, the y-axis focuses automatically to include only the visible range. Without this feature it would be impossible to visualize small variations in the y-axis (i.e. if a dimensions is ranging between 8000 and 9000, it would appear as a straight line - with this feature you can get visual feedback even on this variation).

**Comment by kachkaev** [comment]
Thanks for your reply @ktsaou – I agree with your arguments.

As far as I understand, distinguishing between 8000 and 9000 and knowing how far you are from 0 (which may be a sign of a problem in a case of the entropy, for instance) are two distinct questions, which imply two different cognitive tasks. In the second case it may be helpful to see the chart with a fixed zero to avoid extra cognitive load (i.e. reading the numbers after assessing the shape). This suggests that having "fixed" zeros in all chats can be a useful option. Maybe a new button next to +, - , etc.? I don't think it's urgent or has a priority, but I still see a value in being able to toggle between two mode. Not a bug for sure, but maybe a tiny bit to think about.

**Comment by kachkaev** [comment]
One more quick thought: if such a concept as "fixed 0" is ever introduced, it may be widen to "fixed range" concept for some charts. In case of the entropy, one may want to quickly know how far they are from 0, but if it comes to CPU or a few other resources, it may be important to know how much is left until the physical cap (100% in case of CPU).

When a range is always dynamic, those who see the CPU chart, first spot the highest peak and then move their sight to the left in order to read a corresponding number. Thus, the situation becomes clear after the value is read (which is slow and not cognitively trivial).

On the other hand, the whole notion of a range as a chart view mode introduces another level of cognitive complexity – a user either needs to check if some small icon is glowing or there should be a clear pre-attentive way to perceive what mode the chart is in.

**Comment by ktsaou** [comment]
Nice! There is another task link charts so that the y-range is the same to them. This will allow to compare them visually #593

I will try to implement something like that with that change.
