### ISSUE TITLE
Cloudflare's Rocket Loader conflicting with dashboard.js

### ISSUE THREAD

**Issue by rayonaboat** [firehol/netdata#1018]
I've discovered that [Rocket Loader](https://blog.cloudflare.com/56590463/) is conflicting with dashboard.js, causing the page to look like [this](https://i.gyazo.com/aac3748ccce4ded35faaf6eec5e93c40.png), essentially not loading the dashboard script. It seems like the solution is to create a [page rule](https://i.gyazo.com/dfc5b928a0f91f7ae082120535d81360.png) or to disable Rocket Loader. Cloudflare does provide an [HTML attribute](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-), but in my testing it didn't work. 

I've submitted a ticket to Cloudflare, but I just wanted to help if someone else faces a similar issue.

**Comment by ktsaou** [comment]
Thanks! Interesting info.

If they something there is something the app should do, let me know.
Keep in mind though that most javascript files are dynamically loaded via javascript, so I don't know if they have a solution (the page say the `data-cfasync="false"` works only in HTML).

**Comment by ktsaou** [comment]
Cleaning up.
