### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [firehol/netdata#102]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/firehol/netdata/blob/0fffe00ce88d4af2dd1a4c781250d635211b4663/src/main.c#L462)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [tc_device_create](https://github.com/firehol/netdata/blob/54d9ad67e4ab8f47f30871dd015c65ac2dd18ec5/src/plugin_tc.c#L331)

**Comment by ktsaou** [comment]
Thanks for reporting it!
Fixed them.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
There are [some update candidates left over]( "Update candidates: tc_device_set_…()"). Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

**Comment by ktsaou** [comment]
I totally agree and usually I handle all return values.
In a few cases however, like the `strdup` case you pinpoint, this is not the problem. If `name` is null, the dimension will not change name. It is ok.

Regarding the static source code analysis, I'll have a look. Thank you for pointing this out!

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by ktsaou** [comment]
> Are you interested to apply aspect-oriented software development?
> How do you think about to encapsulate error detection and corresponding exception handling as a reusable aspect in your software?

I know it took me too long, but this was closed and on the panic of the first days I lost it.
I need to read about these.
Thanks!

**Comment by ktsaou** [comment]
Just a note to let you know I followed your suggestion: netdata is now analysed by coverity.com
