### ISSUE TITLE
Uptodate Netdata no longer has clickable alerts or alarms.

### ISSUE THREAD

**Issue by shadycuz** [firehol/netdata#1026]
My Version 6c031eca1acba79dcc2b37b0536ee8311be20bba on one server has jump to chart and clickable notifications.

My two other servers 269bf704615be3e315df341d76e02d9fc6939bef do not.

**Comment by ktsaou** [comment]
The file `dashboard.js` is cached at your browser.
Could you please press Control-F5 on your browser? If it persists, hit with your browser `http://your.netdata.ip:19999/dashboard.js` and once it is there, press `Control-F5` to force a refresh.

Accidentally I pushed a version netdata that gives 14 days of caching on all static files. I fixed it, it is 1 day now.

**Comment by ktsaou** [comment]
I also submitted a few changes that will force uncaching dashboard.js
Just install the latest version, and press `control-F5` on your browser. It should be done.

**Comment by shadycuz** [comment]
Aww gotcha, the manual refresh did it. You push way to many updates at the
moment for that amount of caching lol
