### ISSUE TITLE
ubuntu init.d installation

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1029]
@peterpacz1 thank you for editing the wiki.

This command you added is wrong:

```
cp /usr/sbin/netdata /etc/init.d/netdata
```

The user should not copy the netdata binary to `/etc/init.d/netdata`.

Please fix it...

**Comment by ktsaou** [comment]
i fixed it. Thanks!

**Comment by ShenZhouHong** [comment]
Thanks for fixing it. Apologies for the error.
