### ISSUE TITLE
Uninstall netdata?

### ISSUE THREAD

**Issue by cpunix** [firehol/netdata#103]
Installed on Ubuntu server, but how can I uninstall in scratch?

**Comment by cpunix** [comment]
Never mind. Figured it out by: 

> apt-get **remove** zlib1g-dev gcc make git autoconf autogen automake pig-config

Let me know if I missed anything.

**Comment by Tmplt** [comment]
That command removes dependencies for building netdata. The program itself is still somewhere on your system. I don't know of any other way than to `rm` the installed binaries -- I'm not in custom with Ubuntu.

**Comment by cpunix** [comment]
@Tmplt 

That's what I suspected. I'll keep looking.

**Comment by Tmplt** [comment]
From what I gather from the documentation, only the `netdata` binary and it's configuration directory is created when installing. You can find the former's location with `which netdata` (if its directory is in your `PATH`). 

Then you can remove the configs by removing the `/etc/netdata/` directory.

I'm not sure if there is a more proper way of doing this on Ubuntu, though.

**Comment by cpunix** [comment]
I removed the /etc/netdata/, /root/netdata/ and var/log/netdata/. I'm looking for a installed log something like that. Thank you for your time on the documentation, you beat me to it!

**Comment by cpunix** [comment]
Looks like everything's clean up with netdata. Is there any fast way with a single command for look in each log file that match the word "netdata" so I could still remove them off?

**Comment by nvtkaszpir** [comment]
https://github.com/firehol/netdata/blob/master/netdata-installer.sh#L94

well described in the installer.

**Comment by cpunix** [comment]
Thanks @nvtkaszpr! That's even more details!

**Comment by tsumaru720** [comment]
I just removed it from some of my stuff (for now!) - Below paths are based on the defaults used to install, obviously change if you used a custom install path

Was basically:

```
killall netdata
apt-get remove zlib1g-dev gcc make git autoconf autogen automake pkg-config
rm -Rf /usr/sbin/netdata
rm -Rf /etc/netdata
rm -Rf /usr/share/netdata
rm -Rf /usr/libexec/netdata
rm -Rf /var/cache/netdata
rm -Rf /var/log/netdata
rm -Rf /opt/netdata
userdel netdata
```

**Comment by cpunix** [comment]
Thanks for the additional tips, tsumaru720!

**Comment by ktsaou** [comment]
and

```sh
groupdel netdata
```

**Comment by cbricart** [comment]
actually, if it has been installed by a package manager (i.e `apt`, `emerge`, `dnf|yum|rpm`, ..) from a **binary package**,  the package manger knows best what to uninstall..
if it was installed »by hand« (i.e. `git clone.. && ./configure .. &% make && make install`) it should have been installed w/i it's own prefix path (`./configure --install /opt/netdata ...`) - then uninstalling would simply be `rm -rf /opt/netdata` (and removing the user & group, of course)

**Comment by jrgp** [comment]
You could also install to a specific prefix, and then rm -rf the prefix if you no longer need it.

For instance I put mine under /opt/netdata

    ./netdata-installer.sh --install /opt/netdata

And if I decided I didn't want it anymore

    rm -rf /opt/netdata

**Comment by cpunix** [comment]
They're all cleaned out of the system. Thank you guys!

**Comment by slrslr** [comment]
@tsumaru720

Yours mentioned commands will not remove netdata completely, it caused [this issue](https://github.com/netdata/netdata/issues/5570). Consider updating your post.
