### ISSUE TITLE
High CPU usage when viewing netdata in browser

### ISSUE THREAD

**Issue by TheSpawnMan** [firehol/netdata#1030]
i recently updated my ubuntu server host from 14.04lts to 16.04lts and netdata on the host is causing big draws on the cpu when it used to not even be noticeable.

when viewing other netdata statistic pages in my VMs on the host. it is still little to no draw. its only when im viewing the cpu stats on the host computer
![troncap](https://cloud.githubusercontent.com/assets/11219590/18886446/c2e94c5a-84a4-11e6-95d8-f96be987b344.PNG)

ive removed all the default locations and then reinstalled but it didnt fix the issue..

**Comment by ktsaou** [comment]
Can you post the applications chart? It should have metrics for these:

![image](https://cloud.githubusercontent.com/assets/2662304/18888994/7e66e97a-8503-11e6-95b1-e20eff7de065.png)

**Comment by TheSpawnMan** [comment]
i think this is what your asking for.

![cpuapps](https://cloud.githubusercontent.com/assets/11219590/18889322/5076f99e-84b1-11e6-96c3-b51558eda90e.PNG)

**Comment by ktsaou** [comment]
The CPU utilization does not from netdata. It is your X server. Click on the `netdata` label and then on the `X` label to verify it.

If this did not happen before you upgrade to 16.04lts, it is probably a graphics driver problem. Your CPU is doing things, the GPU should do.

**Comment by TheSpawnMan** [comment]
opps... thanks... no idea how to fix that issue but at least i know what to look at now.
