### ISSUE TITLE
Help required to match data to of system.ram to free -m.

### ISSUE THREAD

**Issue by abhishekdgeek** [firehol/netdata#1034]
Hi Team,

I was working on a project where in I installed this tool to monitor the services. My free -m shows 1 Gig is being used where in the monitors by net data show 3Gigs being consumed.

Based on my analysis I came to figure it out that netdata is showing RAM available vs RAM free and not RAM used vs total RAM. Please confirm the same.

```
Mem:
total: 7984
used: 1162
free: 3207
shared: 24
buff/cache: 3613
available: 6485
```

Also as a developer point, what shall be a key factor in understanding memory consumption. Is it RAM used or RAM free or any other factor?

Many thanks,
Abhishek Jain

**Comment by ktsaou** [comment]
Hi, netdata parses `/proc/meminfo`. This is mine:

```
$ cat /proc/meminfo
MemTotal:        8072624 kB
MemFree:          206636 kB
MemAvailable:    4395536 kB
Buffers:           31264 kB
Cached:          4475232 kB
SwapCached:         5852 kB
Active:          3953000 kB
Inactive:        3255416 kB
Active(anon):    1829776 kB
Inactive(anon):  1057380 kB
Active(file):    2123224 kB
Inactive(file):  2198036 kB
Unevictable:       16864 kB
Mlocked:           16864 kB
SwapTotal:      25165804 kB
SwapFree:       24961116 kB
Dirty:               952 kB
Writeback:             0 kB
AnonPages:       2715416 kB
Mapped:            90768 kB
Shmem:            178556 kB
Slab:             335296 kB
SReclaimable:     247232 kB
SUnreclaim:        88064 kB
KernelStack:       11408 kB
PageTables:        32536 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    29202116 kB
Committed_AS:    5314012 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    571392 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     3112440 kB
DirectMap2M:     5169152 kB
```

This is `free -m` at the same time:

```
              total        used        free      shared  buff/cache   available
Mem:           7883        2953         201         174        4728        4292
Swap:         24575         199       24376
```

This is the netdata chart (almost at the same time):

![image](https://cloud.githubusercontent.com/assets/2662304/18926738/b43c9022-85c1-11e6-974d-a50762b9da88.png)

This is the code that does this: https://github.com/firehol/netdata/blob/7e4d6904404b6777a83046de3edca8a7a5df10c4/src/proc_meminfo.c#L52-L119 More precisely, netdata shows:

```c
        rrddim_set(st, "free", MemFree);
        rrddim_set(st, "used", MemUsed);
        rrddim_set(st, "cached", Cached);
        rrddim_set(st, "buffers", Buffers);
```

As read by `/proc/meminfo` divided by 1024 to make them MB.

**Comment by ktsaou** [comment]
Probably this is the line you are interested: https://github.com/firehol/netdata/blob/7e4d6904404b6777a83046de3edca8a7a5df10c4/src/proc_meminfo.c#L101

```c
unsigned long long MemUsed = MemTotal - MemFree - Cached - Buffers;
```

**Comment by ktsaou** [comment]
And this has been done in such a way that summing up all the dimensions of the chart, you will get the total memory of the system.

In the code of `free`, I see that: https://github.com/mmalecki/procps/blob/fe4c4a7314f32907b9f558ad0d8b8d0ff1cc76be/proc/sysinfo.c#L622 

```c
kb_main_used = kb_main_total - kb_main_free;
```

So, free is reporting cached and buffers as used too.

**Comment by ktsaou** [comment]
> Also as a developer point, what shall be a key factor in understanding memory consumption. Is it RAM used or RAM free or any other factor?

Generally, memory cache is some sort of free memory. Linux uses memory to speed up the disks, so it uses all the available memory to cache disk blocks. Also, Linux can also squeeze its buffers when it starves for resources.

On the other hand, Linux over commits its memory. You can have 4GB of RAM, 4 GB of swap  and allocate 15GB of RAM without a failure at the application. Linux reserves memory only when it is accessed.

Check the memory section of the charts: http://london.my-netdata.io/#menu_mem_submenu_system It has 2 charts: [page faults](https://en.wikipedia.org/wiki/Page_fault) (read that page understand how this works) and **committed**. This one is the more interesting. It is the amount of memory the running applications have allocated.

On my system (the one I posted the data above), I have 3.2 GB used RAM, 0.2GB used swap,, but 5.2GB committed. This means the running apps have allocated 2GB or RAM which have never been accessed.

**Comment by ktsaou** [comment]
I am closing this. If you need help, just post.
