### ISSUE TITLE
Plugin Installation (How?)

### ISSUE THREAD

**Issue by emresaracoglu** [firehol/netdata#1039]
Hello

Software works thank you but how can I add a plugin?

**Comment by ktsaou** [comment]
Well, there are several plugins:

1. plugins using the [netdata plugin API](https://github.com/firehol/netdata/wiki/External-Plugins), go to `/usr/libexec/netdata/plugins.d/*.plugin`. These can be written in any computer language (i.e. go, lua, java, ruby, whatever...).

  Examples: https://github.com/firehol/netdata/tree/master/plugins.d

2. modules of the default `bash` plugin ([charts.d.plugin](https://github.com/firehol/netdata/blob/master/plugins.d/charts.d.plugin)), go to `/usr/libexec/netdata/charts.d/*.chart.sh`.

  Examples: https://github.com/firehol/netdata/tree/master/charts.d

3. modules of the default `python` plugin ([python.d.plugin](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin)), go to `/usr/libexec/netdata/python.d/*.chart.py`.

  Examples: https://github.com/firehol/netdata/tree/master/python.d

4. modules of the default `node.js` plugin ([node.d.plugin(https://github.com/firehol/netdata/blob/master/plugins.d/node.d.plugin)), go to `/usr/libexec/netdata/python.d/*.chart.js`.

  Examples: https://github.com/firehol/netdata/tree/master/node.d

**Comment by ktsaou** [comment]
updated the wiki with this information: https://github.com/firehol/netdata/wiki/External-Plugins

**Comment by ktsaou** [comment]
I am closing this. If you need help, post here.

**Comment by emresaracoglu** [comment]
Hello again Tsaousis,

NetData is an extraordinary project and I thank you for your help but I could not add Redis to NetData..
I do not know where to upload or update any of the files. Again thanks

**Comment by ktsaou** [comment]
Could you please explain a bit what you are trying to do.
Which files you plan to upload or update?
