### ISSUE TITLE
 ERROR: netdata: Cannot read /proc/stat cpu line. Expected 10 params, read 9.

### ISSUE THREAD

**Issue by justincm** [firehol/netdata#104]
Exactly as above

 ERROR: netdata: Cannot read /proc/stat cpu line. Expected 10 params, read 9.

more /proc/stat
cpu  63107623 469739856 16332464 4158916418 707099622 2516676 5260527 0
cpu0 63107623 469739856 16332464 4158916418 707099622 2516676 5260527 0
intr 6977815166 2698368508 13 0 3 3 0 17 0 1 0 0 0 124 0 0 496231868 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1250267077 0 0 0 0 0 0 0 2532947552 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 9967786557
btime 1404226219
processes 73168102
procs_running 4
procs_blocked 0

**Comment by justincm** [comment]
I think this may be down to centos 5 and RHEL 5 both had the issue

changed the proc_stat.c to reflect the number of params reran the neddata_installer and Viola cpu graph and no errors

**Comment by ktsaou** [comment]
thanks for reporting it.
