### ISSUE TITLE
A little suggestion for cgroups and libvirtd

### ISSUE THREAD

**Issue by fumok** [firehol/netdata#1045]
I've modified this line code:

https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L73

like:
`[ -z "${NAME}" ] && NAME="$(echo ${CGROUP} | sed 's/machine.slice_machine.*-qemu//; s/\/x2d//; s/\/x2d/\-/g; s/\.scope//g')"`

There is no more need to edit cgroups-names.conf, to obtain short meaningful guest names.

I must yet investigate different scopes (like scope, scope_vcpu0, scope_emulator), because they can return very different cpu %.

**Comment by ktsaou** [comment]
Thanks! I haven't responded so far, because I am trying to figure out how to do this better...

**Comment by saivert** [comment]
Also have to add that netdata does not clean up stale cgroup names because once they are cached in /var/cache/netdata they stay put even though they refer to a VM that is no longer running. Also restarting VMs using libvirt seems to create a new cgroup name every time instead of reusing the old one.

**Comment by ktsaou** [comment]
Hi.

Cleanup is controlled by these settings:

```
[global]
	cleanup obsolete charts after seconds = 3600
	cleanup orphan hosts after seconds = 3600
	delete obsolete charts files = yes
	delete orphan hosts files = yes
```

netdata by default cleanups charts 1 hour after the charts were last used by any way (collected, updated, viewed). This cleanup takes place only when new charts are added.

So, 1 hour after a cgroup has been updated or viewed and once a new chart is added, netdata will cleanup the old ones.

I think netdata should not delete charts immediately. We may need them. So, I chose to cleanup them only when there is some benefit in doing so (memory will increase when a new chart is added, so this is the right place to cleanup the old ones).

@fumok I am very sorry I forgot your suggestion.
I added it in PR #1935 - could you please verify it works?

**Comment by fumok** [comment]
Grouping method in PR #1935 seems ok. 

Now I've lost memory details of virtual machines, but I must investigate the cause.

**Comment by ktsaou** [comment]
I merged it, so the issue closed automatically.
If you find it it does not work, please post and I'll reopen it.
