### ISSUE TITLE
can't install in SLES 11.1

### ISSUE THREAD

**Issue by mcando** [firehol/netdata#105]
While running installer it fails with this:
Makefile.am:4: option `dist-xz' not recognized
autoreconf: automake failed with exit status: 1
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sorry! NetData failed to build...
You many need to check these:
1. The package zlib1g-dev has to be installed.
2. You need basic build tools installed, like:
   gcc make autoconf automake pkg-config
3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

I couldn't find zlib1g-dev for SLES, has anybody tried this?
Thanks

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/issues/67

**Comment by ktsaou** [comment]
I re-open it, since you also have a problem with zlib1g-dev.

Can you search for `zlib`?
It might be `zlib-devel`.

**Comment by mcando** [comment]
yes, I've already installed zlib-devel
I've also tried with  '--zlib-is-really-here' option but didn't work
autoconf is 2.63-1.160.2
zlib-devel is 1.2.7-0.12-3

**Comment by mcando** [comment]
I did what's on #67 and could finish the install. It's working now, can't see if I'm missing something though.
Thank you!
