### ISSUE TITLE
Access to file is not permitted

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#1051]
When I try to access Netdata, all that shows up is the error message:
```
Access to file '/usr/share/netdata/web/' is not permitted.
```
It was working this morning, and it is not working as of an hour or so ago. I did not restart or update Netdata in that time.

**Comment by ktsaou** [comment]
Something changed the permissions of this directory. It should be owned by user `netdata` and group `netdata`.

Since netdata is a web server, it uses this technique as a protection. It refuses to serve files with wrong permissions, even if it has access to do it. The user and group required is controlled by `/etc/netdata/netdata.conf` options `web files owner` and `web files group`. You can get your running config (to check these settings) using http://your.netdata.ip:19999/netdata.conf

**Comment by ktsaou** [comment]
If fix it, run:

```sh
chown -R netdata:netdata /usr/share/netdata/web/
```

but, you should find how these permissions got changed...

**Comment by kmlucy** [comment]
I am using titpetric docker container. Could it be related to https://github.com/titpetric/netdata/issues/18?

**Comment by ktsaou** [comment]
It might be if you updated the container without re-installing netdata... (I don't know if this can be done, but since the files in  titpetric/netdata#18 are now `root:netdata` it might be the case).

**Comment by kmlucy** [comment]
I ran 
```
chown -R netdata:netdata /usr/share/netdata/web/
``` 
with no change, but when I ran
```
chown -R root:root /usr/share/netdata/web/
```
That fixed it. I'm not sure what happened, but it must be related somehow.

**Comment by ktsaou** [comment]
This probably means your netdata runs as root now.
@titpetric is this related to  titpetric/netdata#18 ?

**Comment by Data-Monkey** [comment]
I have the same issue and there are a lot of people in the unRAID community that use the same docker.
Yes, the docker is running as root.
The above chown fixed it.

**Comment by ktsaou** [comment]
@titpetric I think you should have this `chown` in your `build.sh` script or somewhere.

**Comment by titpetric** [comment]
Thanks for the heads up. It would be preferential for netdata to acknowledge the read flags for the respective user-group under which netdata runs (root in this case). I added the chown to titpetric/netdata but it seems unreasonable given all files are world-readable?

**Comment by ktsaou** [comment]
> I'd suggest to chown them to root.netdata, and only check that they are not world-writable (0664 or 0644 for root only). Ownership checks don't make sense to me.

These checks add an additional layer of protection. For example, to prevent netdata from serving `/etc/passwd` or `/etc/shadow`. Currently netdata has 2 layers of protection for such a case:

1. It does not allow `..` in URLs.
2. It serves only files matching the exact user and group.

You know... it is a web server... I had to protect the system somehow... Of course I am open to better ideas.

**Comment by titpetric** [comment]
For docker containers there's no point, as they have no usable passwd/shadow files. I chowned the files to root:root to solve the permissions issue in titpetric/netdata.

Options would be:

1. always look for netdata owned (user or group), even if netdata runs as root (would fix the issue),
2. have an option to turn off these user/group checks completely and just rely on read flags,
3. actually translate whatever url with realpath, and check that it's in a given web root when it's resolved.

The third option is the "sane" one, but it's beyond me how simple/hard it would be to do it in C.

**Comment by ktsaou** [comment]
> actually translate whatever url with realpath, and check that it's in a given web root when it's resolved.

Yes I tried that, but it is slow. It requires recursion on the directory hierarchy. Thinks are a bit more complicated in Linux due to hard links (a file might not have just one location).

**Comment by titpetric** [comment]
Pretty, fast, secure: pick two :)

**Comment by titpetric** [comment]
I suggest closing, or moving into long-term improvement for next major release. I suppose there's no issue with using realpath with a caching layer on top of it, Either way, work-arounds were made and it's not a critical issue.

**Comment by ktsaou** [comment]
ok. thanks.
