### ISSUE TITLE
packages installer should have a `--noninteractive` mode

### ISSUE THREAD

**Issue by benwtr** [firehol/netdata#1054]
It would be nice if the `https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh` script had a `--noninteractive` flag that executes commands like `yum` and `apt-get` with their `-y` flag or equivalent so that the script can be run non-interactively.

I worked around this in a chef recipe yesterday but it would have been better if I didn't have to do this:
```ruby
# install-required-packages.sh script assumes a human is present to hit Y and
# tell apt it's okay to install packages
ruby_block 'tweak apt command line for noninteractive execution' do
  script_file = "#{Chef::Config[:file_cache_path]}/netdata-demo-site/install-required-packages.sh"
  search_regex = /\s+run \$\{sudo\} apt-get install \"\$\{\@\}\"/
  block do
    sed = Chef::Util::FileEdit.new(script_file)
    sed.search_file_replace search_regex, 'run ${sudo} apt-get -y install "${@}"'
    sed.write_file
  end
  only_if { ::File.readlines(script_file).grep(search_regex).any? }
end
```

**Comment by ktsaou** [comment]
did it.
Can you check?

**Comment by benwtr** [comment]
@ktsaou works for me! (tested on ubuntu-14.04, so should likely be fine on any debian family OS)
