### ISSUE TITLE
[documentation] jq and nodejs packages not available on centos (6.8)

### ISSUE THREAD

**Issue by benwtr** [firehol/netdata#1057]
These packages are not available in the default centos repos, I assume they're in EPEL but the Installer documentation does not mention that.

So, the following bit that's currently on the wiki will fail:
```
# CentOS / Red Hat Enterprise Linux
yum install jq nodejs
```

**Comment by ktsaou** [comment]
The packages installer should say EPEL is needed: https://github.com/firehol/netdata-demo-site/blob/f47f780ac42ad5d4066b313bee9df6859ace045a/install-required-packages.sh#L343-L344

Have you tried installing it with EPEL enabled and failed?

We have the means to node that a package is missing, but node.js on centos is not one there: https://github.com/firehol/netdata-demo-site/blob/f47f780ac42ad5d4066b313bee9df6859ace045a/install-required-packages.sh#L598-L599

So, if you cannot install it with EPEL enabled, we should mention it.

**Comment by benwtr** [comment]
Ah, okay, cool. The _Installation_ page in the wiki doesn't mention EPEL though. 

This is a documentation issue not a code issue.

**Comment by ktsaou** [comment]
> This is a documentation issue not a code issue.

Added it.
Thanks!
