### ISSUE TITLE
SNMP Plugin

### ISSUE THREAD

**Issue by SlodeSoft** [firehol/netdata#1068]
Hi all,

When i test my plugin SNMP i get this message :

 (CEST): node.d.plugin: ERROR: Cannot read configuration file /etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/etc/netdata/node.d.conf', using internal defaults.

I didn't find this file on my server :(

**Comment by l2isbad** [comment]
The only file you need to create yourself to make snmp work is snmp.conf. Put it to netdata/node.d/ folder and thats all.

**Comment by ktsaou** [comment]
I updated the wiki that was incorrectly pointing to `/etc/netdata/snmp.conf`. The right one is `/etc/netdata/node.d/snmp.conf`: https://github.com/firehol/netdata/wiki/snmp.node.js

Though, both should work (the code searches for both): https://github.com/firehol/netdata/blob/cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff/plugins.d/node.d.plugin#L43-L55

**Comment by ktsaou** [comment]
Did you solved it?
