### ISSUE TITLE
per chart configuration not working (snmp module)

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1069]
I need different history values for each graph but per chart configuration didnt work. The only history value which affects my snmp graphs is global.

**Comment by ktsaou** [comment]
How did you set it, when it didn't work?

**Comment by l2isbad** [comment]
[chartname]
 history=x

[snmp_test-core-101.bandwidth_upl]
 history=5

cat charts | grep snmp_test-core-101.bandwidth_upl
               "snmp_test-core-101.bandwidth_upl":             {
                        "id": "snmp_test-core-101.bandwidth_upl",
                        "type": "snmp_cta-core-cta101",
                        "context": "snmp_test-core-101.bandwidth_upl",

**Comment by ktsaou** [comment]
I just confirmed it works.

I think you have not set it right. If you download `http://your.netdata.ip:19999/netdata.conf` it should have a comment that the option you set is unused.

It is best to download the latest version of netdata.conf, and edit it:

```sh
curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
```

**Comment by l2isbad** [comment]
Yeah. i was wrong/. Sorry
