### ISSUE TITLE
Content decoding issue | Lighttpd

### ISSUE THREAD

**Issue by Darlelet** [firehol/netdata#107]
While using Netdata with Lighttpd, i'm facing this error when I try to access netdata from a custom subdomain:
ERR_CONTENT_DECODING_FAILED (Using Chrome and Firefox)
I have zlib.output_compression/zlib.output_handler enabled (php.ini) as well as mod_compress.

Here's my lighttpd config rule:
```
$HTTP["host"] =~ "(monit.domain.com)" {
        proxy.server = ("" => ((
        "host" => "127.0.0.1",
        "port" => 19999,
        )))
}
```

Netdata's working perfectly using host:19999 though...

Any ideas?

Thanks in advance!

**Comment by ktsaou** [comment]
I think lighttpd re-compresses the response of netdata, without decompressing it first.

Open `/etc/netdata/netdata.conf` and set in `[global]`:

```
enable web responses gzip compression = no
```

**Comment by ktsaou** [comment]
I have updated the wiki page too: https://github.com/firehol/netdata/wiki/Running-behind-lighttpd

**Comment by Darlelet** [comment]
Working like a charm, thanks :)
