### ISSUE TITLE
Running as user not working

### ISSUE THREAD

**Issue by necrophcodr** [firehol/netdata#1071]
Hi, I've installed netdata 1.4.0 using the installer into /opt/netdata.

Running `/opt/netdata/sbin/netdata -D -k -u nobody` yields:

16-10-05 14:25:51: ERROR: netdata: Cannot open file '/opt/netdata/etc/netdata/netdata.conf' (errno 2, No such file or directory)
16-10-05 14:25:51: INFO: netdata: System has 4 processors.
16-10-05 14:25:51: INFO: netdata: System supports 32768 pids.
16-10-05 14:25:51: ERROR: netdata: User 'nobody' is not present. Ignoring option.
16-10-05 14:25:51: ERROR: netdata: Group 'nobody' is not present. Ignoring option.
16-10-05 14:25:51: INFO: netdata: Adjusted my Out-Of-Memory score to 1000.
16-10-05 14:25:51: INFO: netdata: Adjusted my scheduling priority to IDLE.
16-10-05 14:25:51: ERROR: netdata: User nobody is not present.
16-10-05 14:25:51: ERROR: netdata: Cannot become user 'nobody'. Continuing as we are.
16-10-05 14:25:51: INFO: netdata: NetData started on pid 24447

**Comment by necrophcodr** [comment]
`getent passwd | grep -E '^nobody:x'`
nobody:x:...

**Comment by necrophcodr** [comment]
Additional information:

`lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by ktsaou** [comment]
Well, I just installed ubuntu 14.04 to test it:

```sh
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

# /opt/netdata/usr/sbin/netdata -D -k -u nobody
16-10-05 19:07:59: INFO: netdata: System has 4 processors.
16-10-05 19:07:59: INFO: netdata: System supports 32768 pids.
16-10-05 19:07:59: ERROR: netdata: Group 'nobody' is not present. Ignoring option.
16-10-05 19:07:59: INFO: netdata: Adjusted my Out-Of-Memory score to 1000.
16-10-05 19:07:59: INFO: netdata: Adjusted my scheduling priority to IDLE.
16-10-05 19:07:59: INFO: netdata: Successfully became user 'nobody'.
16-10-05 19:07:59: INFO: netdata: NetData started on pid 9735
```

It complains only for for the group `nobody`:

```sh
# getent passwd nobody
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin

# getent group nobody
<nothing printed>
```

So, I can't reproduce it.
Do you have any exotic PAM configuration?

**Comment by necrophcodr** [comment]
No exotic PAM configuration. In fact, this is just a standard install with Virtualmin installed using the GPL virtualmin installer and then netdata on top. I'll dig around some more and see if something has changed regarding the user, but not as far as I can tell:

    root@webserver:~# getent passwd nobody
    nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
    root@webserver:~# getent group nobody
    <nothing>

**Comment by necrophcodr** [comment]
FYI

    root@webserver:~# /opt/netdata/sbin/netdata -k -D -u root
    16-10-06 09:45:51: ERROR: netdata: Cannot open file '/opt/netdata/etc/netdata/netdata.conf' (errno 2,     No such file or directory)
    16-10-06 09:45:51: INFO: netdata: System has 4 processors.
    16-10-06 09:45:51: INFO: netdata: System supports 32768 pids.
    16-10-06 09:45:51: ERROR: netdata: User 'root' is not present. Ignoring option.
    16-10-06 09:45:51: ERROR: netdata: Group 'root' is not present. Ignoring option.
    16-10-06 09:45:51: INFO: netdata: Adjusted my Out-Of-Memory score to 1000.
    16-10-06 09:45:51: INFO: netdata: Adjusted my scheduling priority to IDLE.
    16-10-06 09:45:51: ERROR: netdata: User root is not present.
    16-10-06 09:45:51: ERROR: netdata: Cannot become user 'root'. Continuing as we are.
    16-10-06 09:45:51: INFO: netdata: NetData started on pid 30035

**Comment by ktsaou** [comment]
Do you have selinux, grsecurity, apparmor or some other exotic security framework installed?

**Comment by necrophcodr** [comment]
I should've mentioned: 1.3.0 worked fine. Didn't have this issue. Still don't on our other identical servers. But for 1.4.0 it didn't work.

**Comment by necrophcodr** [comment]
And no frameworks of any kind like that, except what comes with Ubuntu 14.04.5.

**Comment by ktsaou** [comment]
Well, I am not sure how to help you.
netdata uses standard system calls to get the users and groups: https://github.com/firehol/netdata/blob/b8097b6640d611c4684052e9c824869c34a20414/src/web_client.c#L249

Also, this functionality has not changed since v1.3

**Comment by necrophcodr** [comment]
I decided to rebuild it, and somehow this made it work. I'm not sure how this is possible, but I guess the problem was solved by simply rebuilding it again and reinstalling it.

**Comment by ktsaou** [comment]
nice you solved it. I am not sure either how this is possible.
