### ISSUE TITLE
Send hostname in Telegram Notification

### ISSUE THREAD

**Issue by TheClonker** [firehol/netdata#1072]
Hi, im using netdata for my Servers and loving it, I recently enabled the [Telegram Notifications](https://github.com/firehol/netdata/wiki/health-monitoring#telegramorg-messages).
Now have the Problem that i can't tell what Server is sending the alert. It looks like this http://puu.sh/ryxHt/99c1419af6.png

I would propose to change the Message Text to the following:
`telegram_message="<b>${host} - ${severity}"`
https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh#L654

Maybe even make it configurable if necessary.

**Comment by ktsaou** [comment]
oops! yes of course.
There is a pending PR to add pushbullet notifications. Once this is merged, I'll fix this one too.

**Comment by ktsaou** [comment]
I just realised I forgot this.
I'll do it later today...

**Comment by ktsaou** [comment]
could you please clone https://github.com/ktsaou/netdata and check it?

**Comment by TheClonker** [comment]
Works as intended, thank you very much @ktsaou :)

**Comment by ktsaou** [comment]
merged it.
thanks!

**Comment by Hossein124** [comment]
Hi guys
Thank you for reading the settings of the telegram file, I did not get it right
