### ISSUE TITLE
What happened to the netdata-updater.sh script?

### ISSUE THREAD

**Issue by spacerodent** [firehol/netdata#1073]
I spun up a new server and noticed the netdata-update.sh script is now missing.  I actually used that script can you explain why it was removed (or was that a mistake)?

Thanks for your work on this excellent project.

**Comment by ktsaou** [comment]
You have to install it once.
It is generated by the installer, since it needs to know how to re-install it.

**Comment by spacerodent** [comment]
I am running cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff (Post release 1.4.0) and installing via ansible with the following lines:

- name: clone the netdata repository
  git: repo=https://github.com/firehol/netdata.git dest=/root/netdata clone=yes
  when: install_netdata
  tags:
    - netdata

- name: build and install netdata
  shell: cd /root/netdata && ./netdata-installer.sh --install /opt --dont-wait --dont-start-it creates=/opt/netdata
  when: install_netdata
  tags:
    - netdata

I did a rm -rf on my netdata checkout AND installation.  It builds and installs but afterwards there is not netdata-updater.sh in /root/netdata.  I have search my / partition on the off chance it was written to some other location but it is not found.

This is the output if the installer log:

# Thu Oct  6 01:15:24 UTC 2016
CFLAGS="-O3" ./netdata-installer.sh --install /opt --dont-wait --dont-start-it
# ./autogen.sh  ... OK
# ./configure --prefix=/opt/netdata/usr --sysconfdir=/opt/netdata/etc --localstatedir=/opt/netdata/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3  ... OK
# make  ... OK
# make install  ... OK
# chown -R netdata:netdata /opt/netdata/usr/share/netdata/web  ... OK
# chmod 0755 /opt/netdata/usr/share/netdata/web  ... OK
# chown -R netdata:netdata /opt/netdata/etc/netdata  ... OK
# chmod 0755 /opt/netdata/etc/netdata  ... OK
# chown -R netdata:netdata /opt/netdata/var/cache/netdata  ... OK
# chmod 0755 /opt/netdata/var/cache/netdata  ... OK
# chown -R netdata:netdata /opt/netdata/var/log/netdata  ... OK
# chmod 0755 /opt/netdata/var/log/netdata  ... OK
# chown -R netdata:netdata /opt/netdata/var/lib/netdata  ... OK
# chmod 0755 /opt/netdata/var/lib/netdata  ... OK
# chown -R netdata:netdata /opt/netdata/etc/netdata/python.d  ... OK
# chmod 0755 /opt/netdata/etc/netdata/python.d  ... OK
# mkdir -p /opt/netdata/etc/netdata/charts.d  ... OK
# chown -R netdata:netdata /opt/netdata/etc/netdata/charts.d  ... OK
# chmod 0755 /opt/netdata/etc/netdata/charts.d  ... OK
# mkdir -p /opt/netdata/etc/netdata/node.d  ... OK
# chown -R netdata:netdata /opt/netdata/etc/netdata/node.d  ... OK
# chmod 0755 /opt/netdata/etc/netdata/node.d  ... OK
# chown root /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin  ... OK
# chmod 0755 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin  ... OK
# setcap cap_dac_read_search\,cap_sys_ptrace+ep /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin  ... OK

**Comment by spacerodent** [comment]
I figured out the issue.  If you use the installer option --dont-start-it the script exits before the updater or uninstaller scripts are written.
