### ISSUE TITLE
Netdata with https

### ISSUE THREAD

**Issue by AlbertoOS** [firehol/netdata#1074]
Is it possible to use netdata with https? I haven't found any tutorial or config about this.
If it is not possible now, will it be in the future?

**Comment by LukasMa** [comment]
It is possible, I'm using it myself. But netdata can't do that itself. Why should it? SSL/TLS isn't that easy and why implement it if there is software designed to do that?
The simple solution: Proxy netdata behind a webserver like apache, nginx or caddy. There are example config files in the wiki. I use nginx, it's fairly simple.

**Comment by AlbertoOS** [comment]
I wasn't aware of how hard it could be to implement. Putting the difficulty aside, they have a lot of things to implement already. Valid points.

I just tested setting it up behind apache and nginx after, it worked fine. Thanks for the insight!
