### ISSUE TITLE
MYSQL Plugin

### ISSUE THREAD

**Issue by YoYo71** [firehol/netdata#1075]
Hi all,

Problem after update latest release. no recognize mysql server.
If make manual mysql.conf and restart netdata, plugin apache and memcache disappears.
Force plugin in "charts.d.conf", it's ok for apache and mysql, but errors arrive in logs

Thanks for help

**Comment by ktsaou** [comment]
The latest netdata uses `python` (`python.d`) plugins. The old shell plugins (`charts.d`) should be disabled for all plugins that already exist in python.

To fix the issue, please remove the `force` option you added in `charts.d.conf` and post the output of this:

```sh
# /usr/libexec/netdata/plugins.d/python.d.plugin 1 mysql
```

It should print a few error lines (it tries to detect various configurations of mysql) and then start working, like this:

```sh
# /usr/libexec/netdata/plugins.d/python.d.plugin 1 mysql
16-10-05 23:21:02:  INFO: Using python v3
16-10-05 23:21:02: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
16-10-05 23:21:02: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
16-10-05 23:21:02: python.d INFO: using MySQLdb
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'socket1'
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket1
16-10-05 23:21:02: python.d ERROR: mysql_socket3_root Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_socket3_root check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket3_root
16-10-05 23:21:02: python.d ERROR: mysql_tcpipv6 Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_tcpipv6 check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcpipv6
16-10-05 23:21:02: python.d ERROR: mysql_socket2 Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_socket2 check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket2
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'mycnf2_root'
16-10-05 23:21:02: python.d INFO: Disabled mysql/mycnf2_root
16-10-05 23:21:02: python.d ERROR: mysql_socket2_root Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_socket2_root check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket2_root
16-10-05 23:21:02: python.d ERROR: mysql_socket3 Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_socket3 check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket3
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'socket1_root'
16-10-05 23:21:02: python.d INFO: Disabled mysql/socket1_root
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'mycnf1'
16-10-05 23:21:02: python.d INFO: Disabled mysql/mycnf1
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'tcp'
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcp
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'tcpipv4'
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcpipv4
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'mycnf1_root'
16-10-05 23:21:02: python.d INFO: Disabled mysql/mycnf1_root
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'tcp_root'
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcp_root
16-10-05 23:21:02: python.d ERROR: mysql_tcpipv6_root Cannot establish connection to MySQL.
16-10-05 23:21:02: python.d ERROR: mysql_tcpipv6_root check function failed.
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcpipv6_root
16-10-05 23:21:02: python.d ERROR: local already exists. Stopping 'tcpipv4_root'
16-10-05 23:21:02: python.d INFO: Disabled mysql/tcpipv4_root

# here is where it starts generating charts

CHART mysql_local.net '' 'mysql Bandwidth' kilobits/s bandwidth mysql.net area 90000 1
DIMENSION Bytes_received in incremental 8 1024
DIMENSION Bytes_sent out incremental -8 1024
CHART mysql_local.queries '' 'mysql Queries' queries/s queries mysql.queries line 90001 1
DIMENSION Queries queries incremental 1 1
DIMENSION Questions questions incremental 1 1
```

**Comment by YoYo71** [comment]
Thanks for reply;

Result for this shell

#/var/log/netdata$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 mysql
16-10-08 17:04:55:  INFO: Using python v2
16-10-08 17:04:55: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
16-10-08 17:04:55: python.d INFO: MODULES_DIR='/usr/libexec/netdatapython.d/',            CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
16-10-08 17:04:55: python.d INFO: using MySQLdb
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv6_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv6_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcpipv6_root
16-10-08 17:04:56: python.d ERROR: mysql_tcp Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcp check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcp
16-10-08 17:04:56: python.d ERROR: mysql_mycnf1_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_mycnf1_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/mycnf1_root
16-10-08 17:04:56: python.d ERROR: mysql_tcp_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcp_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcp_root
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv6 Cannot establish connection to  MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv6 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcpipv6
16-10-08 17:04:56: python.d ERROR: mysql_mycnf2 Cannot establish connection to M ySQL.
16-10-08 17:04:56: python.d ERROR: mysql_mycnf2 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/mycnf2
16-10-08 17:04:56: python.d ERROR: mysql_socket2 Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket2 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket2
16-10-08 17:04:56: python.d ERROR: mysql_socket3 Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket3 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket3
16-10-08 17:04:56: python.d ERROR: mysql_socket1 Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket1 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket1
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv4 Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv4 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcpipv4
16-10-08 17:04:56: python.d ERROR: mysql_socket1_root Cannot establish connectio n to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket1_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket1_root
16-10-08 17:04:56: python.d ERROR: mysql_mycnf1 Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_mycnf1 check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/mycnf1
16-10-08 17:04:56: python.d ERROR: mysql_mycnf2_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_mycnf2_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/mycnf2_root
16-10-08 17:04:56: python.d ERROR: mysql_socket2_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket2_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket2_root
16-10-08 17:04:56: python.d ERROR: mysql_socket3_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_socket3_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/socket3_root
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv4_root Cannot establish connection to MySQL.
16-10-08 17:04:56: python.d ERROR: mysql_tcpipv4_root check function failed.
16-10-08 17:04:56: python.d INFO: Disabled mysql/tcpipv4_root
16-10-08 17:04:56: python.d FATAL: no more jobs
DISABLE


#/var/log/netdata/error.log
16-10-08 17:16:05: INFO: netdata: Adjusted my Out-Of-Memory score to 1000.
16-10-08 17:16:05: INFO: netdata: Adjusted my scheduling priority to IDLE.
16-10-08 17:16:05: INFO: netdata: Successfully became user 'netdata'.
16-10-08 17:16:05: INFO: netdata: NetData started on pid 19520
16-10-08 17:16:05: INFO: netdata: Starting thread tc.
16-10-08 17:16:05: INFO: netdata: Starting thread idlejitter.
16-10-08 17:16:05: INFO: netdata: TC thread created with task id 19521
16-10-08 17:16:05: INFO: netdata: Starting thread proc.
16-10-08 17:16:05: INFO: netdata: CPU Idle Jitter thread created with task id 19522
16-10-08 17:16:05: INFO: netdata: Starting thread cgroups.
16-10-08 17:16:05: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1' on pid 19523.
16-10-08 17:16:05: INFO: netdata: PROC Plugin thread created with task id 19524
16-10-08 17:16:05: INFO: netdata: CGROUP Plugin thread created with task id 19525
16-10-08 17:16:05: INFO: netdata: Not starting thread check.
16-10-08 17:16:05: INFO: netdata: Starting thread health.
16-10-08 17:16:05: INFO: netdata: Starting thread plugins.d.
16-10-08 17:16:05: INFO: netdata: HEALTH thread created with task id 19526
16-10-08 17:16:05: INFO: netdata: Starting thread web.
16-10-08 17:16:05: INFO: netdata: PLUGINS.D thread created with task id 19527
16-10-08 17:16:05: INFO: netdata: Not starting thread web-single-threaded.
16-10-08 17:16:05: INFO: netdata: Multi-threaded WEB SERVER thread created with task id 19528
16-10-08 17:16:05: INFO: netdata: Listening on '[0.0.0.0]:19999'
16-10-08 17:16:05: INFO: netdata: Listening on '[::]:19999'
16-10-08 17:16:05: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 19530
16-10-08 17:16:05: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/python.d.plugin 1 ' on pid 19530.
16-10-08 17:16:05: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/node.d.plugin 1 ' on pid 19532.
16-10-08 17:16:05: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 19532
16-10-08 17:16:05: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 19534
@


same result, is disactivate

**Comment by ktsaou** [comment]
It seems that it cannot connect to your mysql server.
Can you try to give the `netdata` user CONNECT access to your mysql? CONNECT is useless, it cannot do anything except get statistics.

**Comment by ktsaou** [comment]
Did you solve it?

**Comment by YoYo71** [comment]
sorry, no resolve.

result :

# mysql -u netdata
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 904317
Server version: 5.6.30-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

test : 
mysql> show global status;
+-----------------------------------------------+-------------+
| Variable_name                                 | Value       |
+-----------------------------------------------+-------------+
| Aborted_clients                               | 5           |
| Aborted_connects                              | 108         |
| Binlog_cache_disk_use                         | 0           |
| Binlog_cache_use                              | 0           |
| Binlog_stmt_cache_disk_use                    | 0           |
| Binlog_stmt_cache_use                         | 0           |
| Bytes_received                                | 28063152054 |
| Bytes_sent                                    | 82743896297 |
| Com_admin_commands                            | 9           |
| Com_assign_to_keycache                        | 0           |
| Com_alter_db                                  | 0           |
| Com_alter_db_upgrade                          | 0           |
| Com_alter_event                               | 0           |
| Com_alter_function                            | 0           |
| Com_alter_procedure                           | 0           |
| Com_alter_server                              | 0           |
| Com_alter_table                               | 0           |
| Com_alter_tablespace                          | 0           |
| Com_alter_user                                | 0           |
| Com_analyze                                   | 0           |
| Com_begin                                     | 29679       |
| Threads_cached                                | 14          |
| Threads_connected                             | 1           |
| Threads_created                               | 15          |
| Threads_running                               | 1           |
| Uptime                                        | 685861      |
| Uptime_since_flush_status                     | 685861      |
+-----------------------------------------------+-------------+
341 rows in set (0,01 sec)

an idea ?

**Comment by ktsaou** [comment]
I think this is not the same.
Can you try this:

```sh
# become user netdata
su -s /bin/bash netdata

# connect to mysql on localhost
mysql --no-defaults --host 127.0.0.1 --port 3306 -e 'show global status;'
```

Also, while user `netdata`, post the output of this:

```sh
mysql --print-defaults
```

**Comment by ktsaou** [comment]
Did you solve it? Can we close this?

**Comment by hameno** [comment]
I've also had problems with the mysql plugin. I tried to follow the instructions in the conf file and added the netdata user like this:
```
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost' with grant option;
# > flush privileges;
```
But it does not connect and I think know why: there is no job with this data in the conf file - if I add one it works.
My job definition:

```
tcpipv4_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  host     : '127.0.0.1'
  port     : '3306'
```

The other jobs don't work because they have no access to the sockets (as netdata user)

(All on ubuntu 14.04)

**Comment by ktsaou** [comment]
Thanks! Added them: https://github.com/firehol/netdata/pull/1385/commits/4412ae87b6caeabdbea5d80ae79e5b3bde59500d

**Comment by ktsaou** [comment]
Is there any other pending issue? Can we close this?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if there is something pending, please post and I'll re-open it.
