### ISSUE TITLE
chart colors on custom dashboard dont change with data-colors=""

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1084]
After prev upgrade (cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff- > ed548ad47eca461a164ed89bb1263b84e3bea751) all my sexy color graphs turned into red/green (something wrong in dashboard.js)

**Comment by ktsaou** [comment]
oh! yes. I think I know what did this. I'll fix it later today.

**Comment by l2isbad** [comment]
Thanks for the quick response. You rock! Keep it up.

**Comment by ktsaou** [comment]
fixed it.
Thanks for reporting this.
