### ISSUE TITLE
Dashboard for TV

### ISSUE THREAD

**Issue by mokrea** [firehol/netdata#109]
Great idea.. it could have a layout option for TVs.

**Comment by ktsaou** [comment]
You can write one in plain HTML and it could have charts from many netdata servers.

Only a `div` per chart is needed (no javascript). I'll write a wiki page for it. It is very simple.

**Comment by mokrea** [comment]
like this http://<ip or domain name>:<port>/api/v1/chart?chart=system.cpu

**Comment by ktsaou** [comment]
ok, pull it again.

Then goto to your netdata server `http://my.server:19999/tv.html`.

You its source to get the idea.

**Comment by mokrea** [comment]
Great... works fine. thank you.
