### ISSUE TITLE
chart failed to be created as easypiechart

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1091]
I got this after **data-easypiechart-barcolor** option. Before prev update it shows no bar with data-easypiechart-barcolor and now no chart at all.

Also i dont get it sorry.  I m litterally just add 
`data-easypiechart-barcolor="function (percent) { return (percent < 50 ? '#5cb85c' : percent < 85 ? '#f0ad4e' : '#cb3935');}`
to my charts (and i understand it should not work as is).
how does it should work? based on percentage it returns color but percentage of what value?

**Comment by ktsaou** [comment]
You have to enclose the value in parentheses:

```
<div ... data-easypiechart-barcolor="(function (percent) { return (percent < 50 ? '#5cb85c' : percent < 85 ? '#f0ad4e' : '#cb3935');})" ...>
```

> how does it should work? based on percentage it returns color but percentage of what value?

Unfortunately this is how these chart libraries work. The max value is dynamically calculated. You can set the max yourself though, based on which the percentage will be calculated. Check this all possible options: https://github.com/firehol/netdata/blob/ccf5173e9511da7e4a266121226f73459e165de0/web/dashboard.js#L4944

**Comment by ktsaou** [comment]
duplicate of #1089 #958

**Comment by l2isbad** [comment]
Oh..parentheses. My bad.  Thanks for clarification
