### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [firehol/netdata#110]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [buffer_free](https://github.com/firehol/netdata/blob/253dbf6a5a8bf3f8fa74f676af41b68cd39d05d6/src/web_buffer.c#L300)
* [tc_device_set_class_name](https://github.com/firehol/netdata/blob/7e086a7ecced30619a975669ebc006b4afecd7d2/src/plugin_tc.c#L296)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by ktsaou** [comment]
Nice! Let me read a bit about it.

**Comment by mcnewton** [comment]
Agreed. free() does nothing if the pointer is NULL.

**Comment by ktsaou** [comment]
merged the fix.

**Comment by elfring** [comment]
Thanks for [your small](https://github.com/firehol/netdata/commit/e5080111671c910836a7a6cc2aaf4704398825fc#diff-cd15d0ee1730ba613fed066882e8c07bL432 "Code cleanup") [source code improvement](https://github.com/firehol/netdata/commit/3601202dc6b9b7102df746ae600baf8bf20b4da3#diff-40ae359a0f60215e7e9aa2d2716841f8L317 "Bug fixes detected by static code analysis").
