### ISSUE TITLE
dovecot_local.sessions option to show only sessions

### ISSUE THREAD

**Issue by justohall** [firehol/netdata#1100]
Hello. Love netdata - awesome job. Just wondering if there is an option to show only the sessions and not the logins for dovecot. As it is Logins is on a different scale than sessions. I realise I can turn the display off - but be nice to just be able to show the graph without the logins.

Thank you

Justin

**Comment by ktsaou** [comment]
Thanks!

You could split them in two charts and a submit a PR. The source is here: https://github.com/firehol/netdata/blob/master/python.d/dovecot.chart.py

**Comment by justohall** [comment]
Thank you ktsaou. I am a bit new to github. But I think I have done it right.
For some reason it ended up being two PRs.
https://github.com/firehol/netdata/pull/1102
https://github.com/firehol/netdata/pull/1103

**Comment by ktsaou** [comment]
you made 2 branches.
Can you make it one?

1. `git checkout patch-2`
2. `cp python.d/README.md /tmp/`
3. `git checkout patch-1`
4. `cp /tmp/README.md python.d/README.md`
5. `git commit python.d/README.md -m 'updated readme'`
6. `git branch -D patch-2`
7. `git push`

**Comment by justohall** [comment]
Thank you ktsaou. I think I have done that now. But might be too late as @paulfantom has already merged patch-1?

**Comment by ktsaou** [comment]
push it normally, and then make another PR from your repo `patch-1` branch.

**Comment by ktsaou** [comment]
or, leave `patch-2`. It is the same.

**Comment by ktsaou** [comment]
check the comment I made or the PR of patch-1 too.

**Comment by ktsaou** [comment]
this is done, so I close it.
