### ISSUE TITLE
There is no FireQOS

### ISSUE THREAD

**Issue by MatejKovacic** [firehol/netdata#1106]
Hi,
I have successfully installed netdata on RaspberryPi 3 (I am using Raspbian). The I tried to install FireQOS as described here: https://github.com/firehol/netdata/wiki/Real-time-application-bandwidth-monitoring).

"sudo apt-get install firehol" works fine, but there is no application fireqos:

```
fireqos start
-bash: fireqos: command not found
```

Any idea what to do?

**Comment by ktsaou** [comment]
interesting... it is probably a very old version of firehol.

You can use this little script to install everything:

https://github.com/firehol/netdata-demo-site/blob/master/install-all-firehol.sh

It installs firehol+fireqos + iprange (required by newest firehol) + netdata

You can ommit the netdata part if you already have it installed.

**Comment by ktsaou** [comment]
Did you installed it? Can we close this?

**Comment by MatejKovacic** [comment]
Sorry. I did not installed it. Actually I have found that I need to get info only about total bandwith use on a specific ethernet device. Which is already implemented.

**Comment by ktsaou** [comment]
ok then. I am closing this.
thanks!
