### ISSUE TITLE
snmp does not work

### ISSUE THREAD

**Issue by archonnn** [firehol/netdata#1108]
So, after I installed netdata and node.js, I created my snmp.conf file. when I try to execute it with this command:
 "/usr/libexec/netdata/plugins.d/node.d.plugin 2c snmp" 

it pops the message:

 "node.d.plugin: ERROR: Cannot read configuration file /etc/netdata/node.d.conf: ENOENT, no such file or directory '/etc/netdata/node.d.conf', using internal defaults.
DISABLE"

First time I did this though, it worked perfectly, then i did killall netdata and /usr/sbin/netdata and the information I asked on the snmp.conf appeared normally on "myip:19999". After a while it stopped working with this error without me doing anything. How can I fix this? Any help would be appreciated. 

This is my snmp file:

``` json
{
    "enable_autodetect": false,
    "update_every": 1,
    "servers": [
                        {
                                "hostname": "myip",
                                "community": "public",
                                "update_every": 1,
                                "options": { "timeout": 5000 },
                                "cpuusage": {
                                        "cpuusage.test": {
                                                "title": "snmptest",
                                                "units": "MB",
                                                "priority":1,
                                                "type": "area",
                                                "enabled": true,
                                                "port": "161",
                                                "dimensions": {
                                                        "in": {
                                                                "oid": ".1.3.6.1.4.1.2021.11.9.0",
                                                                "divisor": 1024
                                                        }
                                                }
                                        }
                                }
                        }
                ]

}
```

**Comment by ktsaou** [comment]
> node.d.plugin: ERROR: Cannot read configuration file /etc/netdata/node.d.conf: ENOENT, no such file or directory '/etc/netdata/node.d.conf', using internal defaults.

this configuration file used to set defaults for the plugin. It is ok to be missing.

> How can I fix this? Any help would be appreciated.

please run:

```sh
/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp debug
```

and post the whole output you will receive. Use pastebin or something else if it is too big.

**Comment by ktsaou** [comment]
Did you solve it? Can we close this issue?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, please post and I'll re-open it.
