### ISSUE TITLE
"always update the charts, even if focus is lost" option is not working

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1113]
Just noticed.

Charts are not updating when focus is lost on current version.

My main dashboard is on cd0a3e602e22b7b7d9e6d8d2b025b514e08e2bff and "
NETDATA.options.current.stop_updates_when_focus_is_lost = false;" is working as intended.

**Comment by ktsaou** [comment]
I tested this earlier today and found it working. Are you sure it is not working?

**Comment by l2isbad** [comment]
I am 100% sure because i tested it 5 minute ago.

grep false --after-context=1 --before-context=2 index.html 
        <script>
        var netdataTheme = 'slate';
        NETDATA.options.current.stop_updates_when_focus_is_lost = false;
        </script>

Same config works ok for me before

**Comment by ktsaou** [comment]
hm... `netdataTheme` has to be given before loading dashboard.js, but `NETDATA.options.current.stop_updates_when_focus_is_lost` after loading it.

Where did you put it?

**Comment by ktsaou** [comment]
Just tested again in `tv.html`. Edit this file, this option is commented. Uncomment it and load it on your browser. The option works...

**Comment by l2isbad** [comment]
<head>

    <title>Health Dashboard</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

        <script>
        var netdataTheme = 'slate'; // this is dark
        NETDATA.options.current.stop_updates_when_focus_is_lost = false;
        </script>

         <script type="text/javascript" src="http://10.4.0.185:19999/dashboard.js"></script>
