### ISSUE TITLE
Add labels/timeline support

### ISSUE THREAD

**Issue by thinrope** [firehol/netdata#1114]
I recently started using netdata and I think it has quite some future!

One IMHO great enhancement will be adding arbitrary labels/annotations and timelines to be displayed along the graphs. 

The simplest example is being able to add label "2016-10-12T12:34:56 HDD crash", representing a point in time.
Slightly more complicated version is "2016-10-12T12:34:56_2016-10-12T13:12:11 power outage, UPS power" representing an interval.

A hakich way to implement that with current RRD back-end is to create RRD named after the label, then add 1 at the point in time (and fill with 1s, if interval). Even without any additional processing it will make sense. Heck, I can write a script that produces such data right now and have it displayed!

A proper way will be to have a separate data type (JSON/CSV/WHATEVER), stored in a static file which is processed for a graph (and available as static resource over some (new) API)...

I understand this will require quite substantial coding time, but hey let's have it here for discussion.

**Comment by ktsaou** [comment]
I agree,

Actually, the old version of netdata (`http://your.netdata.ip:19999/old/`) supported annotations (although somewhat limited). We should do this properly now.

**Comment by thinrope** [comment]
O! I haven't discovered that old dashboard yet, THANKS!
I actually like it a lot. WOW, quite some functionality in there! Is there some write up why the design was switched? Will the "old" be supported for some time? It feels a bit slower, performance?
I guess reimplementing most of the functionality/UI and replace GoogleChartsAPI shouldn't that hard?

**Comment by ktsaou** [comment]
The old one is based on google charts. They have horrible performance.
Actually, when you press this button:

![image](https://cloud.githubusercontent.com/assets/2662304/19396778/65513858-924d-11e6-86d5-9194f5285835.png)

You get a dashboard that looks very close to the new one:

![image](https://cloud.githubusercontent.com/assets/2662304/19396810/8964bc6a-924d-11e6-8663-f3b82a334947.png)

I realized that most of the time I working on this view, so I decided that this should be the default.

There is also a single chart view:

![image](https://cloud.githubusercontent.com/assets/2662304/19396855/b366f636-924d-11e6-91c8-a12ebabc4a18.png)

which is not needed on the current netdata. You can just resize the charts from their lower right corner.

**Comment by ktsaou** [comment]
Also, the new version of netdata supports many chart libraries.

Check: `http://your.netdata.ip:19999/dashboard.html`. This is a showcase of the different chart libraries supported.

**Comment by thinrope** [comment]
Yup, that dashboard.html and the rest in that dir I discovered (yesterday). I love the idea of being able to change the view dynamically, as well as gong between list and single graph, also some presets for time intervals. Being able to see one graph full screen means a simple way to show 2 (or few) in different browser windows. Helps if one uses a tiling manger ;-)
I often work with lots of data, so having 4K/40" monitor helps, but I still need to zoom/focus on a single graph or two and switch between them.

I still haven't found annotations though... I guess (using Google API), something along https://developers.google.com/chart/interactive/docs/roles?hl=en is possible.
I see also http://dygraphs.com/gallery/#g/annotations so it is a matter of storing those files in the backend.

My first test will be plotting .bash_history along with CPU :-) Too sad bash does not store command end by default, but there are some workarounds.

**Comment by ktsaou** [comment]
Cleaning up.
I am closing this. Annotation is in my todo list.
