### ISSUE TITLE
split collection, visualization, alerting and API, provide ON/OFF control

### ISSUE THREAD

**Issue by thinrope** [firehol/netdata#1115]
I understand netdata is focused on realtime data, yet humans hardly process in realtime.
So currently netdata (usually) shows just an hour or so of data. Hopefully soon we'll have snapshots #309 and I guess people we'll be using the WebUI to analyse historic data, may be from another machine (copied locally?).

AFAIU, currently there are three basic functionalities from the user's perspective (with API as glue in between):
- data collection
- ---API---
- visualisation (WebUI)
- alerting

It will make sense to be able to control separately their function. I suggest the following terms
- data collection: record/stop
- ---API---: allow/deny
- visualization: play/pause
- alerting: enable/disable

Adding those as independent buttons on the WebUI will be great. (yes auto-starting the recording when alerting is enabled ot visualization is play may be tempting, but we'll figure that out).

While currently all graphs can be paused by pan/zoom, having a toggle play/pause button on the graphs will be enough for WebUI.
Being able to stop/start recording (the collector) from the WebUI will be great.
I think I saw a pause for alerting already, but cannot find it now :-| 

Finally being able to switch to "headless mode", or "API deny"==(pause+disable) if you prefer, while still collecting data will be useful in some instances with security implications.

**Comment by thinrope** [comment]
BTW, as a first workaround, what is the "right way" to disable all alarms in config file? I mean, don't bother with alarms, don't calculate them, but keep them around for later to be enabled.

Is the only way deleting (i.e. moving) conf files out of /etc/netdata/health.d ?

**Comment by ktsaou** [comment]
> Is the only way deleting (i.e. moving) conf files out of /etc/netdata/health.d ?

edit /etc/netdata/netdata.conf and set `[health].enabled = false`.

**Comment by ktsaou** [comment]
Cleaning up
