### ISSUE TITLE
debian package fails installing inside unprivileged LXC containers

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1116]
Trying to install a .deb built from the `contrib/debian` instructions fails inside an LXD container with the following errors:

```
Setting up netdata (1.4.1~master) ...
Failed to set capabilities on file `/usr/lib/x86_64-linux-gnu/netdata/plugins.d/apps.plugin' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
dpkg: error processing package netdata (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu11) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 netdata
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The issue has to do with the `setcap` command that the `netdata.postinst` script tries to run. It works fine on privileged containers and native hosts.

**Comment by ktsaou** [comment]
@lhw @FedericoCeratto could you please help?

**Comment by lhw** [comment]
Well the whole point of an unprivileged container is that you can't run root commands. setcap being an example with a lot of destructive power.

**Comment by haasn** [comment]
It's worth noting that I can install netdata “by hand” (via the install shell script) on an unprivileged container with no apparent issues.

(Unless the functionality would be reduced? If so, what should I look for?)

**Comment by lhw** [comment]
That installation will be missing the permissions to read certain files and not draw some graphs i assume.

**Comment by ktsaou** [comment]
Sorry, I don't know. @titpetric can you help?

**Comment by titpetric** [comment]
I think @lhw has the response down pat. Setcap is "overreaching" what is available in non-priv mode

**Comment by ktsaou** [comment]
Is this done? Can we close it?

**Comment by lhw** [comment]
This is intentionally not working. So I don't think there will be a fix for this.

**Comment by ktsaou** [comment]
ok. The make files and the installer will fallback to root `setuid` when capabilities are not there.
@haasn did this work for you?

**Comment by haasn** [comment]
@ktsaou I haven't had a chance to test it yet. I'll update the issue when I can.

**Comment by haasn** [comment]
Using a fresh .deb built from master:

```
% dpkg -i netdata_1.4.1\~master_amd64.deb 
Selecting previously unselected package netdata.
(Reading database ... 41346 files and directories currently installed.)
Preparing to unpack netdata_1.4.1~master_amd64.deb ...
Unpacking netdata (1.4.1~master) ...
Setting up netdata (1.4.1~master) ...
/var/lib/dpkg/info/netdata.postinst: 30: /var/lib/dpkg/info/netdata.postinst: Syntax error: "fi" unexpected (expecting ";;")
dpkg: error processing package netdata (--install):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for systemd (229-4ubuntu11) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 netdata
```

Seems like an unrelated issue to this one, though

**Comment by ktsaou** [comment]
thanks! fixed that in pr #1205

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if there is still a fault, please post and I'll re-open it.

**Comment by haasn** [comment]
Tested it again, the original issue persists as of g360b362.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  netdata
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,805 kB of archives.
After this operation, 6,731 kB of additional disk space will be used.
Get:1 http://devel01.informatik.uni-ulm.de/repo xenial/main amd64 netdata amd64 1.5.0-485-g360b362~rolling [1,805 kB]
Fetched 1,805 kB in 0s (39.7 MB/s)
Selecting previously unselected package netdata.
(Reading database ... 41639 files and directories currently installed.)
Preparing to unpack .../netdata_1.5.0-485-g360b362~rolling_amd64.deb ...
Unpacking netdata (1.5.0-485-g360b362~rolling) ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up netdata (1.5.0-485-g360b362~rolling) ...
Failed to set capabilities on file `/usr/lib/x86_64-linux-gnu/netdata/plugins.d/apps.plugin' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
dpkg: error processing package netdata (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 netdata
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by FedericoCeratto** [comment]
@haasn I can add a setcap fallback in the official Debian package. Falling back to setuid is not ideal for security but acceptable.

**Comment by haasn** [comment]
@FedericoCeratto Will setuid work in unprivileged containers?

**Comment by ktsaou** [comment]
> Will setuid work in unprivileged containers?

setuid works everywhere. setcap does not work in containers and nfs (i.e. nfs root). `netdata-installer.sh` already fallbacks to setuid. I think packages will should fallback too.

**Comment by haasn** [comment]
Oh, right, because unprivileged containers work off ID mapping. Makes sense.
