### ISSUE TITLE
debian package fails to run out-of-the-box: wrong permissions on /var/lib/netdata/registry

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1117]
After installing a plain .deb package built from the `contrib/debian` scripts out-of-the-box, I get an error due to missing write permissions to `/var/lib/netdata/registry`.

Adding a `chown root:netdata /var/lib/netdata/registry && chmod g+w /var/lib/netdata/registry` to the `postinst` script solves the issue.

**Comment by ktsaou** [comment]
@lhw @FedericoCeratto could you please help?

**Comment by lhw** [comment]
We can probably port some of the fixes we made to the actual package back into the contrib/debian directory. But we did change quite a bit. I'll look into it tomorrow.

**Comment by haasn** [comment]
@lhw What are you referring to when you say “the actual package”? Is this a debian package or an ubuntu package? A quick search found me no existing easily-available ubuntu package for netdata (apart from a more-or-less broken PPA). If there was something already readily available, I would not have to go to the trouble of packaging it myself.

**Comment by lhw** [comment]
The official debian package is here: https://anonscm.debian.org/gitweb/?p=collab-maint/netdata.git its still in the debian new queue. Meaning it has to be approved by debian ftp masters first. As soon as its in it will be in debian unstable and later testing and ubuntu.

**Comment by ktsaou** [comment]
What is the process to update it to v1.4?

**Comment by ktsaou** [comment]
Also, can you give me the commands I need to run to build a dep package from it? (excuse me for my ignorance)

**Comment by thinrope** [comment]
I had same issue in Gentoo,  /var/lib/netdata was root:root (and forgot to file a bug :-|

**Comment by ktsaou** [comment]
> I had same issue in Gentoo, /var/lib/netdata was root:root (and forgot to file a bug :-|

In ticket #651 you can find the list of netdata maintainers per distribution. I suggest to open a new bug for it and invite the gentoo maintainer to fix it.

**Comment by thinrope** [comment]
Yes I just did: https://bugs.gentoo.org/show_bug.cgi?id=597382

**Comment by lhw** [comment]
>  What is the process to update it to v1.4?
The debian ftp-masters have a bit of a backlog right now and netdata is still circling the new queue. I'll get on that as soon as it gets into unstable.
> Also, can you give me the commands I need to run to build a dep package from it? (excuse me for my ignorance)
dpkg-buildpackage should do fine.

**Comment by ktsaou** [comment]
> dpkg-buildpackage should do fine.

So, just copy `/contrib/debian` to `/debian` and run `dpkg-buildpackage`?

**Comment by haasn** [comment]
> So, just copy /contrib/debian to /debian and run dpkg-buildpackage?

You also have to `make debian/changelog` (from inside the contrib folder), which requires running `./autogen.sh` in the main dir first as well.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.

I know @FedericoCeratto will update the debian files at the netdata repo soon, so everything will be aligned.
