### ISSUE TITLE
Contrib Structure?

### ISSUE THREAD

**Issue by LeeNX** [firehol/netdata#1119]
Looking for input on how to contrib back to the awesome netdata project, of course would be scratching my own itch too ...  

I have some snmp configs, that might help other people, which I think might be an idea to have them in the wiki with the snmp configs, but in a structured why?  

I am also making/hacking up some web scrappers, that pull data from some ADSL routers that I have, that don't propagate the ADSL info into the snmp tree, where or how would one suggest I put this in my own netdata install and how can I give these back?  

I can't think of a general way to build these 3rd-party applets that can both easy to update and not conflict with my current netdata install?

**Comment by ktsaou** [comment]
This is nice. Thank you for your willingless to share back.

The problem with node.js plugins is that JSON does not allow comments. So the only option is the wiki at the moment.

I have recently moved the SNMP wiki page in the repo: https://github.com/firehol/netdata/blob/master/conf.d/node.d/snmp.conf.md

So, you can fork the repo and add example configurations to it. Once we have a few, we could add a menu at the top of this page. If we manage to get really a lot, I will alter the code to load them dynamically from multiple configuration files.

**Comment by ktsaou** [comment]
Cleaning up.
