### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by swizzley** [firehol/netdata#112]
Please offer documentation for FreeBSD

**Comment by ktsaou** [comment]
I am very sorry, I don't use FreeBSD (also, I think new data collectors have to written for it).
So, don't expect this from me.
Of course, if anyone is willing to bring netdata to the BSD world, please do so...

**Comment by syepes** [comment]
This would be Great!

**Comment by m-wynn** [comment]
The procfs has been deprecated in FreeBSD (and other BSDs as well) for quite a while now.  I believe this would require quite a rewrite.

**Comment by ktsaou** [comment]
There is a PR to compile it on FreeBSD #187

**Comment by joancatala** [comment]
I also would love to have it on FreeBSD. I did some tries but there is no uuid-dev or libuuid-devel, and some other dependencies :-(  (On Debian works perfectly).

**Comment by ktsaou** [comment]
> there is no uuid-dev or libuuid-devel

If someone handles the rest, I can take care of libuuid.

**Comment by backstube** [comment]
Oh yes, a FreeBSD port would be great. I'm very much looking forward to it. Thanks for the Linux build, it looks als works simply great!!

**Comment by vlvkobal** [comment]
Initial FreeBSD support was introduced with #1321

`e2fsprogs-libuuid`, `gcc` and `autotools` are mandatory for installing `netdata` on FreeBSD at present time.

**Comment by ktsaou** [comment]
Thanks!
Added a note on the installation wiki page: https://github.com/firehol/netdata/wiki/Installation#freebsd
Please feel free to edit that page, to add any information required.

**Comment by ktsaou** [comment]
Cleaning up day. Since netdata is now FreeBSD friendly, I think we can close this.

Thank you @vlvkobal !
