### ISSUE TITLE
Also remember the “when to refresh charts?” option

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1120]
From the settings page:

> Settings take effect immediately and are saved permanently to browser local storage (except the refresh on focus / always option). 

I want `netdata` to remember this setting as well. Or alternatively, I want it to default to “always” rather than “on focus”. I don't understand why this setting is not remembered by default. It seems like a design choice, but I don't understand the design choice.

**Comment by ktsaou** [comment]
Check #423 

I will try to add a button on the dashboard, so it will be just a click away to enable it.

**Comment by haasn** [comment]
Seems like this is a duplicate of #423. Discussion seems more appropriate there.
