### ISSUE TITLE
Add semaphore count and other ipcs limits to health monitoring

### ISSUE THREAD

**Issue by k1-hedayati** [firehol/netdata#1128]
Sometimes systems run out of available semaphores and applications can't run, having an alarm on that would be nice

**Comment by ktsaou** [comment]
How do you count the active semaphores and how do you know which is the max?

**Comment by k1-hedayati** [comment]
There is an `ipcs` command for this, it has there sections "Shared Memory Segments", "Semaphore Arrays", "Message Queues".
You can get active semaphores with `ipcs -us` and max with `ipcs -ls`, `ipcs -h` reveals more options.

I'm not that familiar with low level stuff and not sure how useful this can be but sometimes I've saw my app doesn't run because of semaphores issue.

**Comment by ktsaou** [comment]
ok. These commands give the active ones, but to have an alarm we need a threshold. So, do you find the max semaphores supported.

**Comment by k1-hedayati** [comment]
Max semaphores is fourth number in output of `cat /proc/sys/kernel/sem` and "max number of arrays" in output of `ipcs -ls`

More info:
[Setting Semaphores](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Tuning_and_Optimizing_Red_Hat_Enterprise_Linux_for_Oracle_9i_and_10g_Databases/chap-Oracle_9i_and_10g_Tuning_Guide-Setting_Semaphores.html)
[Linux - Kernel Semaphore parameters](http://gerardnico.com/wiki/linux/semaphore)

**Comment by ktsaou** [comment]
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html-single/Tuning_and_Optimizing_Red_Hat_Enterprise_Linux_for_Oracle_9i_and_10g_Databases/#chap-Oracle_9i_and_10g_Tuning_Guide-Setting_Shared_Memory

it says:

⁠8.1. The **SEMMSL** Parameter
This parameter defines the maximum number of semaphores per semaphore set.

⁠8.2. The **SEMMNI** Parameter
This parameter defines the maximum number of semaphore sets for the entire Linux system.

8.3. The **SEMMNS** Parameter
This parameter defines the total number of semaphores (not semaphore sets) for the entire Linux system. 

8.4. The **SEMOPM** Parameter
This parameter defines the maximum number of semaphore operations that can be performed per semop(2) system call (semaphore call). 

and

```
# cat /proc/sys/kernel/sem
250     32000   32      128
```

These values represent **SEMMSL**, **SEMMNS**, **SEMOPM**, and **SEMMNI**.

So, the 4th parameter is **SEMMNI**, which is the max number of **semaphore sets**.

The 2nd: **SEMMNS** which defines the max **semaphores** a system can have.

This is my output:

```sh
# cat /proc/sys/kernel/sem 
32000	1024000000	500	         32000
#SEMMSL SEMMNS      SEMOPM       SEMMNI
```

As I see it: `SEMMNS = SEMMSL * SEMMNI`

So, you want an alarm on the number of the **semaphone sets**.

On my system, this gives the list of semaphores:

```sh
# cat /proc/sysvipc/sem 
       key      semid perms      nsems   uid   gid  cuid  cgid      otime      ctime
  35913747     196608   600          1  1000  1000  1000  1000 1476644419 1476565522
   3121959      65537   600          2     0     0     0     0 1476565201 1476565201
```

The nsems parameter is the single semaphores or semaphore sets?

Using the output of `ipcs`:

```sh
# ipcs -s 

------ Semaphore Arrays --------
key        semid      owner      perms      nsems     
0x02240013 196608     costa      600        1         
0x002fa327 65537      root       600        2         

# ipcs -s -u

------ Semaphore Status --------
used arrays = 2
allocated semaphores = 3
```

each line in `/proc/sysvipc/sem` is a semaphore set (or array), and `nsems` is the semaphores allocated within this array.

So, the alarm should be triggered only when the number of lines in ` /proc/sysvipc/sem` is close to **SEMMNI**.

Now, this is problematic. I don't want to open `/proc/sysvipc/sem` and count the lines it has, every single second. It might have thousands of lines and this will take previous CPU resources.

We need to find a counter of the currently used semaphore sets, exposed by the kernel.

**Comment by k1-hedayati** [comment]
Why every single second? I think something like every 30 seconds is fine.
Why thousands of lines? default limit is 128 and it seems oracle recommends it to be 256 which far from 1k, I don't think having thousands of active semaphores is that much common to make us worry.

`ipcs -s -u` gives correct number of active semaphores, we can just use that and don't use `/proc/sysvipc/sem` at all.

**Comment by ktsaou** [comment]
I read the ipcs source and adapted a bit to come with the following. The kernel provides such counters already.

I will try to add more IPC information to merge it into netdata. This can do per second data collection.

```c
#include <stdio.h>
#include <inttypes.h>

#include <sys/sem.h>
#include <sys/msg.h>
#include <sys/shm.h>

#ifndef SEMVMX
# define SEMVMX  32767  /* <= 32767 semaphore maximum value */
#endif

/* Some versions of libc only define IPC_INFO when __USE_GNU is defined. */
#ifndef IPC_INFO
# define IPC_INFO   3
#endif

struct ipc_limits {
    uint64_t        shmmni;     /* max number of segments */
    uint64_t        shmmax;     /* max segment size */
    uint64_t        shmall;     /* max total shared memory */
    uint64_t        shmmin;     /* min segment size */

    int             semmni;     /* max number of arrays */
    int             semmsl;     /* max semaphores per array */
    int             semmns;     /* max semaphores system wide */
    int             semopm;     /* max ops per semop call */
    unsigned int    semvmx;     /* semaphore max value (constant) */

    int             msgmni;     /* max queues system wide */
    size_t          msgmax;     /* max size of message */
    int             msgmnb;     /* default max size of queue */
};

struct ipc_status {
    int             semusz;     /* current number of arrays */
    int             semaem;     /* current semaphores system wide */
};

/* according to X/OPEN we have to define it ourselves */
union semun {
    int val;
    struct semid_ds *buf;
    unsigned short int *array;
    struct seminfo *__buf;
};

int ipc_sem_get_limits(struct ipc_limits *lim) {
    FILE *f;
    int rc = 0;

    lim->semvmx = SEMVMX;

    f = fopen("/proc/sys/kernel/sem", "r");
    if (f) {
        rc = fscanf(f, "%d\t%d\t%d\t%d",
               &lim->semmsl, &lim->semmns, &lim->semopm, &lim->semmni);
        fclose(f);

    }

    if (rc != 4) {
        struct seminfo seminfo = { .semmni = 0 };
        union semun arg = { .array = (ushort *) &seminfo };

        if (semctl(0, 0, IPC_INFO, arg) < 0) {
            lim->semmni = 0;
            lim->semmsl = 0;
            lim->semmns = 0;
            lim->semopm = 0;
            return 1;
        }
        lim->semmni = seminfo.semmni;
        lim->semmsl = seminfo.semmsl;
        lim->semmns = seminfo.semmns;
        lim->semopm = seminfo.semopm;
    }

    return 0;
}

int ipc_sem_get_status(struct ipc_status *st) {
    struct seminfo seminfo;
    union semun arg;
    arg.array = (ushort *)  (void *) &seminfo;
    if (semctl (0, 0, SEM_INFO, arg) < 0) {
        /* kernel not configured for semaphores */
        st->semusz = 0;
        st->semaem = 0;
        return 1;
    }

    st->semusz = seminfo.semusz;
    st->semaem = seminfo.semaem;

    return 0;
}

int main(int argc, char **argv) {
    struct ipc_limits lim;
    struct ipc_status st;

    if(ipc_sem_get_limits(&lim)) {
        printf("unable to fetch semaphore limits\n");
        return 1;
    }

    if(ipc_sem_get_status(&st)) {
        printf("unable to fetch semaphore statistics\n");
        return 1;
    }

    printf ("------ Semaphore Limits --------\n");
    printf ("max number of arrays = %d\n", lim.semmni);
    printf ("max semaphores per array = %d\n", lim.semmsl);
    printf ("max semaphores system wide = %d\n", lim.semmns);
    printf ("max ops per semop call = %d\n", lim.semopm);
    printf ("semaphore max value = %u\n", lim.semvmx);

    printf ("------ Semaphore Status --------\n");
    printf ("used arrays = %d\n", st.semusz);
    printf ("allocated semaphores = %d\n", st.semaem);
}
```

**Comment by k1-hedayati** [comment]
Great! I'm looking forward to it

**Comment by ktsaou** [comment]
I have implemented this. Only semaphores for the moment.

Before merging it, please test it. Clone https://github.com/ktsaou/netdata.git then checkout branch `ipc`, install it and report back success or failure.

Thanks!

**Comment by ktsaou** [comment]
I forgot: in the system overview section there will be 2 charts: semaphores and semaphore arrays. I have also added 2 alarms for each of these. The alarms read the system configuration and will complain at 80% utilization (warning) and 90% utilization (critical) for both semaphores and semaphore arrays.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you have missed something, please post and I'll re-open it.

**Comment by mailinglists35** [comment]
I have this output:
```
[root@linux bin]# ipcs -q

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages
0x00001bbc 0          root       666        0            0
0x00001c20 32769      root       666        0            0
0x00001c84 65538      root       666        0            0
0x00001ce8 98307      root       666        0            0
0x00001d4c 131076     root       666        0            0
0x00001db0 163845     root       666        0            0
0x000003e8 196614     root       666        0            0
0x000007d0 229383     root       666        0            0
0x00000bb8 262152     root       666        0            0
0x00000fa0 294921     root       666        0            0
0x00001388 327690     root       666        0            0
```

How do I see a graph for "messages" column for each message queue id?

Currently it shows only this graph:

![image](https://cloud.githubusercontent.com/assets/2054302/23544680/fccdad3c-0008-11e7-8304-31d4a8a5ab39.png)

**Comment by ktsaou** [comment]
Unfortunately only semaphores are currently collected.
Please open another issue for IPC queues and I'll try to check what an effort that could be to be added.

**Comment by mailinglists35** [comment]
thank you, filed https://github.com/firehol/netdata/issues/1890
