### ISSUE TITLE
OBO design bug in API

### ISSUE THREAD

**Issue by thinrope** [firehol/netdata#1135]
API returns one less than the requested number of points  (since header is not a point).
````
2016-10-18 10:21 kalin@sky ~ $ curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&points=1"
time,guest_nice,guest,steal,softirq,irq,user,system,nice,iowait

2016-10-18 10:22 kalin@sky ~ $ curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&points=2"
time,guest_nice,guest,steal,softirq,irq,user,system,nice,iowait
2016-10-17 21:23:09,0,0,0,0.00355,0,30.64095,3.93994,0.01198,0.04144

2016-10-18 10:22 kalin@sky ~ $ curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&points=5"
time,guest_nice,guest,steal,softirq,irq,user,system,nice,iowait
2016-10-18 01:43:56,0,0,0,0.00032,0,1.24274,0.23708,0.0259,0.08163
2016-10-17 12:58:48,0,0,0,0.00334,0,41.69262,4.76455,0.0139,0.01369
2016-10-17 00:13:40,0,0,0,0.00625,0,39.78393,6.41141,0.01159,0.01827
2016-10-16 11:28:32,0,0,0,0.0002,0,9.27833,0.79829,0.00772,0.0085
````
Same is with `format=json`, it is just harder to see.
I guess that was implemented to cater for special case `points=0` that seems to return all data, although that is not logical. IMHO `points=0` should only return the header (and zero points). And `(points == NULL)` should return all data (NOTE: this is currently implemented)
In addition that should be documented.

**Comment by ktsaou** [comment]
There is no bug. You are ignoring an important parameter/feature: **alignment**. This guarantees the charts are consistent when panning them.

Checked: https://github.com/firehol/netdata/pull/253

To do what you want, you should add the `&options=unaligned`.

**Comment by thinrope** [comment]
Well... I spend a good 30 minutes between looking at the API in Swagger Editor and the CLI making queries and I am more confused than before I started... :-| And another 30 writing this, hope it doesn't sound like a rant ;-)

BTW, Swagger UI link from https://github.com/firehol/netdata/wiki/REST-API-v1 is not working (returning File '/usr/share/netdata/web/swagger/' does not exist, or is not accessible.).

I suspect that the main issues I have with the above are:

1. unexpected defaults (may be optimised for default short-term storage only)
2. non-strict API, does not NOT return error for bad query (e.g. missing required parameter)
3. and/or not-current API docs (shown in swagger)
4. no way to get (latest) raw data

## unexpected defaults
Yes, I am really expecting to get N points if I use `points=N`. May be except in the case that I request too many (response size limit) or there is no data (which should probably be error). The special case `points=1` really throws my logic to /dev/null and I think for this sole purpose `options=unaligned` should be default. Since we don't have options with value (`options=alined:false` or similar), I think changing it to `options=aligned` and off by default will be the reasonable fix. Yes, I am aware that will break a few things, but I expect it to be a major hurdle when we think about log-term storage, snapshots, etc.

## non-strict API?
````
2016-10-18 18:00 kalin@sky ~ $ curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&dimension=user&points=3"
time,user
2016-10-18 13:09:00,1.51913
2016-10-17 13:20:56,40.64071
````
Not providing required parameter `after` in the 1st case, should have returned 400: Bad Request.

## outdated docs?
````
2016-10-18 18:01 kalin@sky ~ $ curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&dimension=user&points=3&after=-600"
time,user
2016-10-18 18:00:00,2.50497
2016-10-18 17:56:40,9.12903
2016-10-18 17:53:20,1.39919
````
Providing a default value to `after` (=-600) per docs, should have NOT changed the output.

## no way to get the raw data?
*(disclaimer: I work in digital forensics, we LOVE raw)*
While I agree that metrics are just numbers and can easily loose meaning depending on the sampling, I still find it valuable to be able to provide simple interface to GET what you PUT and it should not be changed. I was unsuccessfully trying to "GET the last 10 values". Or may be I am missing `grouping=none` and it being a default?

## I need more caffeine?
At least the above is my definition of REQUIRED and DEFAULT, please correct me if I am wrong. I'll give it some more thought in a day or two.

Given how complex a dashboard can be and all the parameters and options that are needed anyway, my hope was that defaults are set so that a request like this will return the last reading only, no thrills, nothing automagic, and I would be able to query few servers easily:
````
curl -s -o - "http://localhost:19999/api/v1/data?format=csv&chart=system.cpu&dimension=user&points=1"
````
I ended up with 0 points (just header) :-(
Turning a default off (by `options=unaligned`)  and it worked :-)
So I braced up and requested 5 points, but old data was returned :-(
Trying to get 5 points 1h ago, `points=5&options=unaligned&after=-3600` I got 5 points, but averaged for the last hour/5 intervals :-| (API being helpful and doing work not told to - averaging).
Hmm fiddling with `before` being 60,-60,-3600-60, -3600+60 all produced unexplainable results :-G
Finally I "nailed" it with:
````bash
(
API="http://localhost:19999/api/v1/data?format=tsv&chart=system.cpu&dimension=user"
NOW=$(date +%s);
DURATION=10;
AGO=3600;
curl -s -o - "${API}&after=$((${NOW} - ${AGO}))&before=$((${NOW} - ${AGO} + ${DURATION}))"
)
````
but I abused the fact that this data uses 1s resolution, so I still cannot get easily:
* `last` (=current) reading
* `N points, S seconds ago`
* `instant value at time T`
:-|

**Comment by ktsaou** [comment]
> BTW, Swagger UI link from https://github.com/firehol/netdata/wiki/REST-API-v1 is not working (returning File '/usr/share/netdata/web/swagger/' does not exist, or is not accessible.).

fixed that. thanks!

Regarding the other comments you make... ok, it is a matter of context. For sure, better documentation would help and possibly changing a few defaults or names might also improve the situation.

Let's see the context:

## before and after

these define the time-frame, the duration of the data to be returned. The default is **all the data**. Of course, we could change that, but before deciding, we need to see what the rest parameters do.

In PR #1146 I adapted a bit their description to make it clear that the defaults return the whole duration of the round robin database.

## points

the `points` parameter is used only to alter the number of points returned for the requested duration. If it is not given, all the points in the database for the requested duration will be returned.

This is its description at swagger (I haven't touched now):

> The number of points to be returned. If not given, or it is <= 0, or it is bigger than the points stored in the round robin database for this chart for the given duration, all the available collected values for the given duration will be returned.

What you suggest, is to change this meaning / context. You suggest to make it define the time-frame, the duration of the data to be returned.

Let's assume we do this.

So, we pass `points=2` and we expect to get back the last 2 seconds of data. So, `points` defines the time-frame, the duration.

Then we add `after=-20&before=-5`. What now? Suddenly `points=2` should no longer define the duration, but switch to aggregation / reduction.

I think this suggestion is not right. Parameters should not switch context.

Of course, we could rename `points` to `reduce` or something that could provide a better understanding of what it does, at first sight.

## unaligned

`unaligned` should not be there. I don't like it at all. If you search for it at the repo, you will see that I had to add it to satisfy situations like yours, where alignment is confusing.

Why alignment is needed, I think is obvious. Without alignment, there cannot be visualization. The returned data will always change based on the time the request is made and charts will constantly change shape, on every update.

This is why the default is with alignment enabled. To prevent all these.

So, the whole idea is that:

- `before` and `after` are the only parameters that control the time-frame
- `points` is only needed if the returned points need to be reduced
- `unaligned` should never be used, unless you know what you are doing

Is it more clear now?
