### ISSUE TITLE
openSUSE LEAP 42.1 lm_sensor prerequisite failed

### ISSUE THREAD

**Issue by victisomega** [firehol/netdata#1137]
I noticed running curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all

It ran until it hiccuped at "No candidate for lm_sensor"

I'm currently running this on openSUSE LEAP 42.1

I can install it manually, after which rerunning that script will finish successfully but I believe the fault lies in the fact that it's searching for "lm_sensor" when the SUSE derivative is known simply as "sensors"

Not a big deal as it installs and runs fine, just wanted to bring it to your attention. Happy Coding and thank you for the fantastic program!

**Comment by ktsaou** [comment]
I don't have access to this distro.
Can you find the right package for installing lm-sensors?

**Comment by ktsaou** [comment]
Check this: https://forums.opensuse.org/showthread.php/391229-Can-t-find-lm-sensors

It suggests that this works:

```sh
zypper in sensors
```

Does it?

**Comment by victisomega** [comment]
Yes it does. sensors provides lm_sensors

**Comment by ktsaou** [comment]
Fixed it. Can you check it now?

**Comment by victisomega** [comment]
Good to go! thanks!

**Comment by ktsaou** [comment]
I see that for all package managers, I have already a check in the code to avoid re-installing the package. But I don't know how to do this check with zypper. Can you help me?

What I need is a command that will return 0 if it is installed, and non-0 if it is not.

Reading around I see that these commands can be candidates. Can you run them for me and give the output?

```sh

# checking installed packages with zypper
echo "TEST1"; zypper se -i sensors; echo $?

# checking not installed packages with zypper
echo "TEST2"; zypper se -i invalidpackagename; echo $?

# checking installed packages with rpm
echo "TEST3"; rpm -q sensors; echo $?

# checking not installed packages with rpm
echo "TEST4"; rpm -q invalidpackagename; echo $?
```

**Comment by victisomega** [comment]
zypper will eventually print 0 if it is installed, but it will print every package installed in a table grid first Example below.

TEST2
Loading repository data...
Reading installed packages...

S | Name        | Summary                              | Type
--+-------------+--------------------------------------+--------
i | libsensors4 | Hardware health monitoring library   | package
i | sensors     | Hardware health monitoring for Linux | package
0

**Comment by victisomega** [comment]
This should work.

zypper se -i invalidpackagename &>/dev/null; echo $?
# Returns 104 Not installed

zypper se -i sensors &>/dev/null; echo $?
# Returns 0 because it is installed

**Comment by ktsaou** [comment]
hm... will it return 0 (installed) for something that partially matches?

```sh
zypper se -i senso &>/dev/null; echo $?
```

**Comment by ktsaou** [comment]
or even:

```sh
zypper se -i sensors4 &>/dev/null; echo $?
```

**Comment by victisomega** [comment]
Looks like zypper's search function may not be precise enough for that. Fortunately SUSE uses RPMs for their packages so rpm -q sensors will work.

**Comment by ktsaou** [comment]
fixed that too.

I would appreciate a final test that everything is working as expected.

You are very helpful. Thank you!

**Comment by victisomega** [comment]
Everything runs smoothly now. Kudos for supporting SUSE and her derivatives!
