### ISSUE TITLE
To enable it, you need a kernel built with CONFIG_KSM=y

### ISSUE THREAD

**Issue by ghprod** [firehol/netdata#114]
Hi, after finish installing I get that message, how to have kernel with `CONFIG_KSM=y'?

Thanks

**Comment by ktsaou** [comment]
This message is about enabling the kernel memory deduper.
You don't need it, but it could lower the memory requirements of netdata if you had it.

This is a kernel configuration options. The fact that you don't have it, means that you need a new kernel that has it (or you can build your own - this is an advanced task though).

So, I suggest to just ignore it.

**Comment by ghprod** [comment]
Thanks @ktsaou for your reply :)
