### ISSUE TITLE
Problems choosing theme

### ISSUE THREAD

**Issue by jos3k4** [firehol/netdata#1141]
I just updated my netdata server with the latest version available (1.4.0) and I have my own dashboard using some chart components. In order to have the dark theme on my **index.html** I have the following line of code:

```
<script>var netdataTheme = 'slate';</script>
```

(More information about this [here](http://lists.firehol.org/pipermail/firehol-devs/2016-March/000921.html))

However for some reason, the web UI still appear in white. Maybe something changed related with setup your theme on the last release?

Thanks

**Comment by l2isbad** [comment]
netdataTheme has to be given before loading dashboard.js
it can be the problem

<script>  var netdataTheme = 'slate'; // this is dark  </script>
<script type="text/javascript" src="http://1.2.3.4:19999/dashboard.js"></script>

**Comment by ktsaou** [comment]
Yes, before loading dashboard.js, since it needs to know which css files to load.

**Comment by ktsaou** [comment]
I am closing this. If you need help, just post.
