### ISSUE TITLE
Include runtime dependencies in RPM spec file

### ISSUE THREAD

**Issue by acjohnson** [firehol/netdata#1145]
According to your Installation documentation, the following two packages are required to be installed in order for netdata to run, however the spec file does not include these packages as Requirements to install netdata from RPM:

package|description
:-----:|-----------
`libuuid`|part of `util-linux` for GUIDs management
`zlib`|gzip compression for the internal netdata web server

**Comment by ktsaou** [comment]
hm... thanks for reporting this.

So, shall I add the following?

```
Requires:	zlib
Requires:	util-linux
```

@philwhineray @alonbl @paulfantom can you help?

**Comment by alonbl** [comment]
Hi,

Everything in BuildRequires you have and is required in runtime as well should be in Requires statement (without the -devel suffix if was specified).

Notice that although I did not approve you worked with a guy who introduced a lot of issues in your spec, see 3fea7af57 which is relevant to this discussion. As you can see the requires statements were removed.

Alon

**Comment by ktsaou** [comment]
merged it.
If you have any other issues, let me know.
