### ISSUE TITLE
Disk space health monitoring false criticals

### ISSUE THREAD

**Issue by LiquidityC** [firehol/netdata#1148]
I have a mounted usb disk on my Raspberry Pi, it's a 2TB disk as shown from this 'df -h' line:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       1.8T  268G  1.5T  16% /mnt/external

I think it's the TB size that is messing with netdata because netdata seems to think that the disk is 85% full which it clearly isn't. When I write large files to the drive I get critical alarms from netdata that the disk will be full within the hour and sometimes that the drive is 95% full.

I got the alarms last night and this is all the data I saved from when it happened. I'm happy to add more data to this issue. Just request what you need and I will try to comply.

On a sidenote. Netdata is a fantastic application, you guys have done great work with it!

**Comment by ktsaou** [comment]
I think I have fixed (on my pi it works properly).
Let me know if the problem remains.

**Comment by LiquidityC** [comment]
Sounds great. I'll get back if I find anything else.
