### ISSUE TITLE
How to Monitor Virtual interfaces?

### ISSUE THREAD

**Issue by itmanet** [firehol/netdata#1149]
Hi,
As a beginner i'm looking to figure out if:
Is there any way with current plugins to monitor virtual interfaces like eth0.0, eth0.1, eth0.2, etc.  (for bandwithd and packets/s) ?
If not, is there any guide showing how could I make a new plugin for this task? 

Thanxs.

Example:
# The primary network interface

```
auto eth0.3
iface eth0.3 inet static
   address 192.168.1.6
   netmask 255.255.255.192
   gateway 192.168.1.1
   dns-nameservers 8.8.8.8
   up   ip addr add 192.168.1.7/24 dev eth0 label eth0:0
   down ip addr del 192.168.1.7/24 dev eth0 label eth0:0
   up   ip addr add 192.168.1.8/24 dev eth0 label eth0:1
   down ip addr del 192.168.1.8/24 dev eth0 label eth0:1

   up   ip addr add 192.168.1.9/24 dev eth0 label eth0:2
   down ip addr del 192.168.1.9/24 dev eth0 label eth0:2
   up   ip addr add 192.168.1.10/24 dev eth0 label eth0:3
   down ip addr del 192.168.1.10/24 dev eth0 label eth0:3

   up   ip addr add 192.168.1.11/24 dev eth0 label eth0:4
   down ip addr del 192.168.1.11/24 dev eth0 label eth0:4
   up   ip addr add 192.168.1.12/24 dev eth0 label eth0:5
   down ip addr del 192.168.1.12/24 dev eth0 label eth0:5
```

**Comment by ktsaou** [comment]
The kernel does not keep track these metrics for such kind of interfaces. These are actually aliases to the same interface.

You can use FireQoS to classify such traffic into different classes to monitor it (and probably shape it too), or you can create VLANs, which are independent interfaces inside the linux kernel (this requires a compatible switch).

The simpler solution is fireqos - once you have qos classes configured, netdata will automatically render its classes.

**Comment by cihankom** [comment]
Hi ktsaou,

I am working with itmanet together and I have tried your solution about fireQos.
FireQos looks like support only one network interface at the same time. Am I right?
is it possible to classify all network interface on machines ?

Thanks

**Comment by ktsaou** [comment]
> FireQos looks like support only one network interface at the same time. Am I right?

No, you are not right. FireQoS supports any number of interfaces and up to 5000 classes per interface.

But you have to understand how Linux interfaces work. I suggest to forget `ifconfig` and use `ip link show`. The later reports interfaces that QoS can be applied to.

> is it possible to classify all network interface on machines ?

QoS is applied at a network interface (link) level. There is no point to apply a single QoS policy on multiple interfaces - you will not get anything useful out of it.

What are you trying to do?

**Comment by ktsaou** [comment]
If I have understood your case right, you have eth0 with multiple subnets. These appear as network interface **aliases** in `ifconfig`, but in reality they are just multiple IPs on a single interface: `eth0`. Check `ip link show` and `ip addr show` to verify this.

So, in this case, you can apply a single QoS policy on `eth0`. This QoS policy could use sub-classes. Check these:

- https://github.com/firehol/firehol/wiki/FireQOS-Use-Scenarios
- https://github.com/firehol/firehol/issues/154

**Comment by cihankom** [comment]
Ok I will check it. thanks

**Comment by ktsaou** [comment]
I am closing this. If you need help, just post.
