### ISSUE TITLE
Arduino examples

### ISSUE THREAD

**Issue by vlachosv** [firehol/netdata#1154]
Can i have a sample code on how to monitoring the values from a templature sensor connected local on a raspberry pi and what format must have a remote sensor values to monitoring in netdata?

I have 3 esp8266 with a templature sensor and try to send values to a netdata server.

**Comment by ktsaou** [comment]
how do you read these values from the console?

**Comment by vlachosv** [comment]
In first case ( sensor directly connected to the raspberry pi via gpio ) with shell:

1.) http://elinux.org/RPi_GPIO_Code_Samples#Shell
2.) http://www.cl.cam.ac.uk/projects/raspberrypi/tutorials/temperature/#step-three-a


In second case ( sensor connected to the esp8266 ) convert sensor data to json, xml, url string etc, and send via web wherever I want (api, php app, etc) or i can programming esp8266 to response sensor data in a http reauest from netdata server.

Example post in php: index.php?date=25112016&time=130548&temp=25


What is the best way to input values in netdata via web? api?
Can i have a sample of code or some base instructions?

I try to play with this logic /etc/netdata/node.d/sma_webbox.conf but dont read any value.

**Comment by ktsaou** [comment]
If you know BASH: https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh
If you know python: https://github.com/firehol/netdata/blob/master/python.d/example.chart.py

In both cases, copy them, search/replace `example` with `whatever` and adapt according to your needs.

Of course, you can use any language you like: documentation of the Plugins API is here: https://github.com/firehol/netdata/wiki/External-Plugins

**Comment by vlachosv** [comment]
Ok thank you for the reply.
