### ISSUE TITLE
Question about TCP Reset alarms

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1156]
On our hosts with HaProxy as a gateway we regularly see TCP reset alarms every now and then. They are not triggered because of port scans but because of our filtering in the proxy. Those filters actively drop connections depending on IP addresses and URLs that they request. This is a nice and effective way to get rid of spammers, robots and other culprits.

Using `http-request deny` in HaProxy does this according to their documentation:

```
  - "deny" : this stops the evaluation of the rules and immediately rejects
    the response and emits an HTTP 502 error. No further "http-response"
    rules are evaluated.
```

Am I correct that this could trigger TCP reset alarms? And if so, how could I get NetData still monitoring TCP resets but not being impacted by those intentional ones?

**Comment by ktsaou** [comment]
Based on the description, these should not trigger TCP reset. I see that haproxy responds with HTTP code 502, so as far as the client is concerned, it got a response from the server, i.e. it manage to connect.

When TCP reset is sent to the clients, they will be reporting `connection refused`. It is the one you get if you run `curl http://localhost:12345` and nothing is listening on port `12345`.

The netdata alarm, works like this:

1. it calculates the average TCP resets for the last minute. If this less than 5, it assumes it is 5.

2. it calculates the average TCP reset for the last 10 seconds.

3. If the later (10 sec average) is 4 times bigger than the first (1 min average), the alarm is triggered.

So, it needs a 10 second average above 20 and 4 times the average of the last minute.

For the average of the last 10 second to be 20, **200 TCP resets in 10 seconds are needed**. So, the threshold is already high enough.

I have to admit that this alarm bothers me too. I occasionally have such alarms, which unfortunately I haven't found a way to trace (you need to run tcpdump on the machine while they happen).

When I created this alarm, my goal was to have something that will notify us if a busy service on the machine dies.

Probably, we will have either silent this alarm or disable it. I don't know.

What do you think?

**Comment by jurgenhaas** [comment]
It's interesting as I got these TCP reset alarms pretty everywhere originally and that improved with later versions of NetData to those hosts that run HaProxy. So, if it's not the deny responses, then I wonder what else that could be.

If NetData is able to identify the number of TCP resets, isn't there a way to debug and log which ports had been requested? That would help to understand what's going on and we wouldn't have to go through tcpdump.

Other than that I'd rather prefer to silent these alarms. Testing services by means of knocking at the door is probably not too reliable in the first place and should be done by uptime test from remote locations anyway.

**Comment by ktsaou** [comment]
> If NetData is able to identify the number of TCP resets

unfortunately what the kernel exposes is just a number: the number of outbound TCP resets (i.e. the TCP resets this host sent on all its network interfaces). So, I guess `tcpdump` is the only way to find out why.

I have switched the alarm to `silent`.
