### ISSUE TITLE
Imposible install on Suse Enterprise 12

### ISSUE THREAD

**Issue by Nitrosito** [firehol/netdata#1162]
Hi, i Have:

SUSE Linux Enterprise Server 12 SP1, Linux 3.12.62-60.64.8-default

when i execute "curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-package

```
Loading /etc/os-release ...
Unknown distribution ID: sles
Cannot find valid distribution in: sles 
Cannot find valid distribution with lsb-release

I NEED YOUR HELP
It seems I cannot detect your system automatically.
And it seems I cannot find a known package manager in this system.
Please open a github issue to help us support your system too.s.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata"
```

I install all dependencies manually, but when i execute netdata_instaler.sh

```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-suse-linux-gnu
checking host system type... x86_64-suse-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for accept4... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for mallopt... yes
checking for mallinfo... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking for _Generic... no
checking for __atomic... yes
checking size of void *... 8
checking for sin in -lm... yes
checking for UUID... no
configure: error: Package requirements (uuid) were not met:

No package 'uuid' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables UUID_CFLAGS
and UUID_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues
```

if i use --libs-are-really-here:

```
make[2]: Entering directory '/root/netdata/src'
gcc -DHAVE_CONFIG_H -I. -I..  -DVARLIB_DIR="\"/var/lib/netdata\"" -DCACHE_DIR="\"/var/cache/netdata\"" -DCONFIG_DIR="\"/etc/netdata\"" -DLOG_DIR="\"/var/log/netdata\"" -DPLUGINS_DIR="\"/usr/libexec/netdata/plugins.d\"" -DRUN_DIR="\"/var/run/netdata\"" -DWEB_DIR="\"/usr/share/netdata/web\""        -O3 -pthread -MT apps_plugin.o -MD -MP -MF .deps/apps_plugin.Tpo -c -o apps_plugin.o apps_plugin.c
In file included from apps_plugin.c:1:0:
common.h:66:23: fatal error: uuid/uuid.h: No existe el fichero o el directorio
 #include <uuid/uuid.h>
```

BUT!
uuid.h exist! , they are in /usr/include/linux/uuid.h

¿How to resolve this?

A lot of thanks

**Comment by ktsaou** [comment]
Is it safe to assume that sles has the same packages as opensuse?

Which package manager do you use? `zypper`?

**Comment by Nitrosito** [comment]
No, I think that Suse Enterprise Server dont use same package as  opensuse.
I use Zypper.

I link manually uuid.h to netdata/src/uuid/uuid.h , but fail to compile.

(Unkown size storage uuid , or similar error)

¿Netdata can be installed on Suse enterprise? or i dimiss?

Thanx and regards

**Comment by ktsaou** [comment]
libuuid-devel is needed to compile netdata. Unfortunately I don't know the exact package name for sles.

This library is pretty standard for all linux systems. It is developed by the linux kernel developers and should exist in all distributions. It might be called `libuuid-devel`, `libuuid1-devel`, `util-linux`, etc.

As I don't have access to SLES 12, I suggest to search a bit for it. You might be able to get a solution at the suse forums.

If you find a solution, please let us know, so that others can benefit too.

**Comment by BerndHelber** [comment]
To solve this Issue:
In the first Step, add the SDK and SLE-SDK12-SP1-Updates Repos to your System.
`zypper info libuuid-devel
---------------------------------------
Repository: SLE-SDK12-SP1-Updates
Name: libuuid-devel
Version: 2.25-32.4
Architektur: x86_64
Hersteller:SUSE LLC <https://www.suse.com/>
Supportstufe: Unbekannt
Installiert: Ja
Status: aktuell
Installationsgröße: 16,6 KiB
Zusammenfassung:Development files for libuuid1
Beschreibung: 
  Files to develop applications using the library to generate universally
  unique IDs (UUIDs).`

You also have to add the SLES12-SP1-Updates to your System.


`zypper info  util-linux `  
Informationen zu package util-linux:
------------------------------------
Repository: SLES12-SP1-Updates
Name: util-linux
Version: 2.25-32.4
Architektur: x86_64`

Keep in mind, if you make use of an evaluation Version you have 60 Days for testing, and you're able to activate the Online Repositories. If you're System is already registered and not already done activate the following Online Repositories  in Yast and you should be golden.
----------------------------------------------
SLE-Module-Legacy12-Debuginfo-Pool
SLE-Module-Legacy12-Debuginfo-Updates
SLE-Module-Legacy12-Pool
SLE-Module-Legacy12-Source-Pool
SLE-Module-Legacy12-Updates
SLES12-SP1-Debuginfo-Pool
SLES12-SP1-Debuginfo-Updates
SLES12-SP1-Pool
SLES12-SP1-Source-Pool
SLES12-SP1-Updates
SLE-SDK12-SP1-Debuginfo-Pool
SLE-SDK12-SP1-Debuginfo-Updates
SLE-SDK12-SP1-Pool
SLE-SDK12-SP1-Source-Pool
SLE-SDK12-SP1-Updates
SLE-Module-Toolchain12-Debuginfo-Pool
SLE-Module-Toolchain12-Debuginfo-Updates
SLE-Module-Toolchain12-Pool
SLE-Module-Toolchain12-Updates
-------------------------------------------

Kind regards

**Comment by ktsaou** [comment]
@BerndHelber thanks!

Can you give me the exact commands to add SDK and SLE-SDK12-SP1-Updates to a sles system? I would like to give them to users of our installer.

**Comment by BerndHelber** [comment]
Firstly register your System at Suse Customer Center.

https://scc.suse.com/

Or, if you have an SMT Server add the System to your SMT Server, or SuSE Manager System.
Suse will provide a registration code for your System.
Add the Registration Code to your System.
This Step  has to be accomplished with Yast2.
If the System is registered and the Registration Code is valid, you will be able to to activate the necessary Repositories with Yast2.

Keep in mind that SuSE auto generates unique Repository URL's for your System.
All you need is a valid Evaluation Subscription.

Kind regards

**Comment by ktsaou** [comment]
thanks!

**Comment by shadycuz** [comment]
@ktsaou I will look up all the SUSE related commands for adding these repositories with Yast and add this to the documentation tonight.

**Comment by shadycuz** [comment]
SLES12 and instructions for repositories are confusing, I think I added the correct relevant information to the wiki, but it doesn't explain how to install the above repositories, just what is needed (Registered System or the DVD). 

I'm going to go ahead and add a link from the installation wiki back to hear, but this can be closed now.

**Comment by ktsaou** [comment]
ok thanks!

**Comment by FedericoCeratto** [comment]
Wiki link: https://github.com/firehol/netdata/wiki/Installation
