### ISSUE TITLE
Docker containers, networks interfaces, alarms

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1163]
Not sure how this one should be handled. I'm bringing it up so that we can probably collect ideas on what we want and how that could be achieved.

My problem is that when working with Docker containers, we are getting new network interfaces every time we fire up a new container. The great thing is that NetData immediately starts monitoring those network interfaces as well, which is a bonus that I had not thought about before. But it's great.

Now, when shutting down one of the containers, its interface(s) are being killed on purpose. The problem is, NetData is still monitoring them and soon after will trigger an alarm that it couldn't read from the interface anymore.

Now, the catch 22 is that when I shut down a container deliberately, I want NetData to stop monitoring it as well and don't alert me about dead interfaces. On the other hand, if a container crashed, it is probably important to get exactly those alerts.

Any ideas on how that could be resolved?

**Comment by l2isbad** [comment]
Same with all interfaces
https://github.com/firehol/netdata/issues/1142

**Comment by ktsaou** [comment]
I am copying my response here. This thread seems a better place to discuss this. Here it is:

---

hm... what is a container crash? Does such a thing exist?

If it does not exist, then you simply don't need alarms for network interfaces attached to containers. You can disable the template, and add alarms only for the physical interfaces of the system.

On the other hand, if you need alarms to exist only under certain conditions (e.g. when a container is running), we could invent a solution where something external to netdata (a script may be), might be called to take this decision and inform netdata. Would this be something useful?

**Comment by jurgenhaas** [comment]
A container is a process like e.g. Apache or MySQL and such a process could of course crash and then it's not available any more. Nor are its interfaces. But a container can be shut down deliberately and then the interfaces are disappearing as well, but that's not perceived an alert.

**Comment by ktsaou** [comment]
ok, I got that. The issues are:

1. how can we build a dependency tree of all the metrics, i.e. how netdata could know that this apache is part of a container and if that container is stopped it is obvious to expect the apache to be stopped too. This might seem simple at first sight, but it is not. Containers may use bridges, NAT, or even sub-containers with more processes and more networking options. It is virtually impossible to build such a dependency tree, unless you are the docker itself (and I can think several cases under which this is impossible even for docker).

2. how can we know that a docker is administratively down or crashed? The result of both is that the container is not running, but how can netdata know why it is not running?

What I find useful here, is to have in netdata a mechanism to disable alarms on demand. This will provide the means for automation systems that perform maintenance, migration, setup and destruction of containers, to inform netdata about what they believe netdata should do.

Of course I am open to other ideas too...

**Comment by jurgenhaas** [comment]
I'm with you on that, it is like you're saying.

With regard to network interfaces though, maybe the difference is this: from the nature of the alert it sounds to me that NetData continues trying to read from the network interface which doesn't exist anymore, when the Docker container stopped. But the message is saying that it can't read from that interface anymore.

The difference is: failed reading from an existing interface should trigger an alarm, but reading from an interface that doesn't exist anymore should just get NetData to stop reading from that interface,

I've cross checked that: if the docker container is up and running, `ifconfig` shows an interface like `veth89bea67` and as soon as the container gets closed (crashed or manually), that interface disappears from the list. At that point, NetData should just remove that interface from its list of monitored devices, shouldn't it?

Or, if that's not a reasonable proposal, maybe we should make that 2 different alerts: one that triggers when we can't read from an existing interface anymore and another one for interfaces that once existed but don't anymore.

**Comment by ktsaou** [comment]
hm... it is not like that. Netdata reads `/proc/net/dev`. When a container is stopped or crashed, the interface disappears from this list.

But netdata has a chart for it with an alarm attached to it, that checks when was the last time we collected data for this chart. The alarm does not poll the interface. It just checks the netdata database.

What you propose can be done, by examining the bytes transferred through the interface in the last minute. So, if during the last minute, we did collect data, but the data was zero, then the alarm should be fired.

The problem however, is that this alarm will be triggered even for interfaces just sitting idle for a minute...

**Comment by jurgenhaas** [comment]
Let me come back to this one as I still get hit by it every now and then. I understand your previous comment and yes, that sounds like a catch 22.

> So, if during the last minute, we did collect data, but the data was zero, then the alarm should be fired.

However, my problem just seems to be the opposite. The device does disappear from the list and there is no data collected anymore from that device. The charts are behind in time and the alert gets fired.

Even worse, this will never recover until I restart NetData on that host. Pretty inconvenient.

**Comment by ktsaou** [comment]
> Even worse, this will never recover until I restart NetData on that host. Pretty inconvenient.

yes, I totally understand this. This veth world makes it a bit complicated.

I need to find an elegant way to handle it. What you experience is exactly the same with a USB network card disconnected, or a high-end hot-swappable PCI network card malfunctioning.

So, this is our situation:

1. netdata cannot ignore a disappearing network interface.

2. to ignore the alarm, some user action should be required, but currently we don't have authentication. One way to do it without authentication, could be to add a special button/URL to the email sent (with a random UUID in it), which once clicked will instruct netdata to switch the alarm to `CLEAR`. It is not 100% safe though (since email is not safe).

   A similar setup, could be to set an admin password/pin for netdata and the dashboard to allow you switch alarms off, if you know the password/pin. This could also be useful after authentication is implemented (admin actions would require another pin to be accepted).

3. another way, could be to somehow detect all this container setup and find a way to link all the related charts and alarms to it, and remove them once the container is removed. I don't have a clue how this can done though. It needs quite some research and a quite some code in netdata.

The problem with ephemeral containers is a little bit worst. netdata maintains some memory for all the charts of the containers. So, if containers are starting and stopping all the time, the memory netdata uses is increasing constantly.

Let me think a bit. Probably adding a special flag to container related charts, could solve all these issues at once...

**Comment by jurgenhaas** [comment]
Not an easy one, that's for sure. Maybe I'm naive, but let me still ask this question: if a new container gets fired up, NetData gets notified about a new interface obviously. Is there an event that you're listeing to or are you referring to /proc/net/dev regularly?

For the other way round, if a container gets closed, isn't there system events around that tell others what's going on? I would have thought that termination of containers should report if that termination was regular or critical and depending on that the alerting may be different too. For regular termination of containers (maybe same for bluetooth and other temporary devices) there shouldn't be any alerts, but for critical termination (like unexpected shutdown or a crash) your scenario described above should apply.

Does that make any sense?

**Comment by ktsaou** [comment]
What you say makes sense 100%, but unfortunately there are no events at all. Netdata finds out what is happening the hard way: it reads proc files and finds new interfaces introduced or old interfaces removed. The same is true for everything, including containers. There is nothing that tells why these happened.

**Comment by nodekra** [comment]
As a workaround you can use [Docker API ](https://docs.docker.com/engine/api/v1.26/) to monitor docker network changes, I use it with simple console script to reload `CSF firewall `and  added `netdata reload `as well right now, since I faced this issue too. I believe netdata can listen Docker events by itself. Here is `curl` example to parse Action of Network events:

> curl  --unix-socket /var/run/docker.sock http:/events | jq -r 'select( .Type == "network")|.Action'

Networks report these events: `create, connect, disconnect, destroy`

**Comment by jurgenhaas** [comment]
Sounds great, would be excellent if NetData could do that automatically.

**Comment by ktsaou** [comment]
This is really nice indeed! Let me play a bit with it...

**Comment by mailinglists35** [comment]
I am experiencing this with lxc too, not only docker

**Comment by mailinglists35** [comment]
>  I'm bringing it up so that we can probably collect ideas on what we want and how that could be achieved.

For me, this would be ideal solution:

- monitor newly created interfaces with name pattern vethXXXXXX (it's nice to see traffic for each)
- if interface named vethXXXXXX dissapears from system, forget about it, do not show it in the list, act like it never existed (I don't want to receive alerts, I don't want to edit configuration files, I like how everything happens automatically, I don't want to see it listed)

I frequently start and stop containers so this has become quite frustrating.
![image](https://cloud.githubusercontent.com/assets/2054302/23402923/be04debe-fdbe-11e6-8ba0-46d6683ef343.png)

**Comment by ktsaou** [comment]
@mailinglists35 you can do what you describe already, at least for alarms. Edit this file: https://github.com/firehol/netdata/blob/master/conf.d/health.d/net.conf

And set

```
families: vethIMPORTANT !veth* *
```

- `vethIMPORTANT` name all the `veth` interfaces you want to have this alarm
- `!veth*` ignores all other `veth*` interfaces
- `*` enabled this alarm for all other interfaces

You can add as many patterns as you like, both positive and negative. The first that matches an interface will be used.

You can test your patterns on the command line:

```
# netdata -W simple-pattern 'vethIMPORTANT !veth* *' vethIMPORTANT
RESULT: MATCHED - pattern 'vethIMPORTANT !veth* *' matches 'vethIMPORTANT'

# netdata -W simple-pattern 'vethIMPORTANT !veth* *' veth1234
RESULT: NOT MATCHED - pattern 'vethIMPORTANT !veth* *' does not match 'veth1234'
```

Of course the permanent solution is for netdata to use the docker API mentioned above.

**Comment by ktsaou** [comment]
I have given a solution on PR #1875 for self-cleaning stopped network interfaces and containers.
Any testers available?

**Comment by mailinglists35** [comment]
thank you, works fine for me!

**Comment by jurgenhaas** [comment]
Yeah, works fine here too.

**Comment by ktsaou** [comment]
merged it. I have kept a note to check docker events in case it can help even more.
