### ISSUE TITLE
"ERROR 410: Netdata registry ACCESS failed: http://foo.example.org:19999"

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1170]
My configuration:

foo.example.org:

```
[registry]
    enabled = yes
    registry to announce = http://foo.example.org:19999
```

bar.example.org:

```
[registry]
    enabled = no
    registry to announce = http://foo.example.org:19999
```

The `my-netdata` menu item works fine on `foo.example.org:19999` but it fails on `bar.example.org:19999`. I get the following errors in my console after doing so:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://foo.example.org:19999/api/v1/registry?action=access&machine=f25d604a-9726-11e6-94fc-00224d522f9a&name=wsl51&url=http%3A%2F%2Fwsl51%3A19999%2F&_=1477659094761. (Reason: missing token ‘cache-control’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).(unknown)
"ERROR 410: Netdata registry ACCESS failed: http://foo.example.org:19999"
```

foo.example.org is using version 1.4.0; bar.example.org is using git master as of about a month ago. Both hosts can reach each other fine on port 19999.

Using the default (global) registry also works fine.

**Comment by ktsaou** [comment]
Your netdata on `foo` (the registry) is older than the netdata on `bar`.
Could you please update it too?

**Comment by haasn** [comment]
I could try that. The reason for the version difference is that `foo` is rpm-based whereas `bar` is dpkg-based and I had trouble building the rpm package for git master, so I built `foo` from the stable release ver instead.

**Comment by ktsaou** [comment]
I think I fixed rpm building on master. Can you retry? If it works, please close this issue.
