### ISSUE TITLE
Restarting netdata

### ISSUE THREAD

**Issue by kachkaev** [firehol/netdata#1174]
I've been playing with the configs a bit and this required me to restart netdata a few times. I could not find any instructions on how to do this (e.g. on [a corresponding wiki page](https://github.com/firehol/netdata/wiki/Configuration)), so empirically came up with this solution:

```
killall netdata; sleep 5; sudo netdata
```

The reason for `sleep 5` is because the time gap saves me from this racing condition:

```
sudo killall netdata; sleep 2; sudo netdata
2016-10-28 17:27:05: netdata: ERROR: IPv4 bind() on ip '0.0.0.0' port 19999 failed. (errno 98, Address already in use)
2016-10-28 17:27:05: netdata: ERROR: Cannot bind to ip '0.0.0.0', port 19999
2016-10-28 17:27:05: netdata: ERROR: IPv6 bind() on ip '::' port 19999 failed. (errno 98, Address already in use)
2016-10-28 17:27:05: netdata: ERROR: Cannot bind to ip '::', port 19999
2016-10-28 17:27:05: netdata: FATAL: Cannot listen on any socket. Exiting... # : Success

2016-10-28 17:27:05: netdata: INFO: Saving database...
2016-10-28 17:27:05: netdata: INFO: NetData exiting. Bye bye...
```

Before I got to config editing and thought a bit about means to restart netdata, the solution was even worse:

``` bash
cd /path/to/netdata
./netdata-installer.sh -f
```

Both options seem quite clumsy and I'm not sure I'm restarting netdata / reloading config the best possible way. It would be good if the wiki contained some advice on this. Or maybe there should be `netdata restart` / `netdata stop` options?

Sorry if the question is stupid.

**UPD**: Just faced a situation when 5 secs was not enough :–)

**Comment by ktsaou** [comment]
Which distribution you use?

If it is systemd based, you can run `systemctl restart netdata` and it will do it.

**Comment by kachkaev** [comment]
Thanks for the advice @ktsaou – I did not realise that netdata registered itself as a proper service when installing.

Both `systemctl restart netdata` and `service restart netdata` work, but not on all machines. Those with older kernels seems to not have netdata registered as a service. 

I guess that this is because the installer assumes that `servicectl` exist in the system ([see line 821 in `netdata-installer.sh`](https://github.com/firehol/netdata/blob/b45af457ec84ecdfaebb23565072d8eb51ad2afa/netdata-installer.sh#L821)), which is not the case for all my machines:

```bash
uname -a
#Linux ip-10-123-123-123 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

which systemctl
# [no output]

service netdata restart
# netdata: unrecognized service
```

```bash
uname -a
Linux ip-10-123-123-124 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

which systemctl
# /bin/systemctl

sudo service netdata restart
# [no output]
```

__PS:__ Might be related to #1004

**Comment by kachkaev** [comment]
I added a small new section in [Configuation page on wiki](https://github.com/firehol/netdata/wiki/Configuration#applying-changes). Feel free to correct me if I'm wrong in anything. Hope this can help a few newcomers like me!

**Comment by ktsaou** [comment]
ok, thanks.

In the `system` directory of netdata you can find various system services for netdata for different operating system (openrc, lsb, init.d, etc).  These are documented at the installation wiki page: https://github.com/firehol/netdata/wiki/Installation#starting-netdata-at-boot
