### ISSUE TITLE
[question] The use of " circular indicators" from the plugins

### ISSUE THREAD

**Issue by vpashka** [firehol/netdata#1176]
The System overview you have a  "circular indicators" (CPU, Disk Read/Write, etc).
Is it possible to use them (create) from the plugins?

P.S. Sorry for my english. I used translate.google...

**Comment by ktsaou** [comment]
I am not sure I understand the question.
Can you explain what you are trying to do?

**Comment by vpashka** [comment]
I would like in my plugin display information the pie chart. Is it possible?
Similarly, as the CPU, Disk Read/Write etc.

**Comment by ktsaou** [comment]
Yes, using a custom dashboard.

View the source of `http://your.netdata:19999/tv.html` to get the idea. No javascript necessary - only  HTML.

**Comment by vpashka** [comment]
Good. Thanks for the idea. I will try..
