### ISSUE TITLE
Alarm not triggered

### ISSUE THREAD

**Issue by MelkorLord** [firehol/netdata#1179]
Hi,

I want to monitor the fans through lm_sensors which netdata already charts nicely. I have 4 fans on my test host. 2 of them running around 1300 rpm and 2 running around 800 rpm.

I've tried to setup an alarm and set the values so that it would trigger the alarm but nothing's happening, I don't net mail alarms like I get for my nearly full harddrives.

```
template: fans_rotation
      on: sensors.fan
   units: Rotations/min
   every: 10s
    warn: $this < 1100
    crit: $this < 900
    info: Fan rotations per minute
      to: sysadmin
```

sending `killall -USR2 netdata` or restarting netdata does change anything, they're never triggered!

If it helps, here is the section extracted from `netdata.conf`

```
[sensors.nct6776-isa-0290_fan]
    # history = 3600
    # enabled = yes
    # cache directory = /var/cache/netdata/sensors.nct6776_isa_0290_fan
    # chart type = line
    # type = sensors
    # family = fans
    # units = Rotations/min
    # context = sensors.fan
    # priority = 90003
    # gap when lost iterations above = 1
    # name = sensors.nct6776_isa_0290_fan
    # title = nct6776-isa-0290 fans speed (sensors.nct6776_isa_0290_fan)
    # dim nct6776-isa-0290_fan1 name = fan1
    # dim nct6776-isa-0290_fan1 algorithm = absolute
    # dim nct6776-isa-0290_fan1 multiplier = 1
    # dim nct6776-isa-0290_fan1 divisor = 1000
    # dim nct6776-isa-0290_fan2 name = fan2
    # dim nct6776-isa-0290_fan2 algorithm = absolute
    # dim nct6776-isa-0290_fan2 multiplier = 1
    # dim nct6776-isa-0290_fan2 divisor = 1000
    # dim nct6776-isa-0290_fan4 name = fan4
    # dim nct6776-isa-0290_fan4 algorithm = absolute
    # dim nct6776-isa-0290_fan4 multiplier = 1
    # dim nct6776-isa-0290_fan4 divisor = 1000
    # dim nct6776-isa-0290_fan5 name = fan5
    # dim nct6776-isa-0290_fan5 algorithm = absolute
    # dim nct6776-isa-0290_fan5 multiplier = 1
    # dim nct6776-isa-0290_fan5 divisor = 1000
```

Is there something I'm doing wrong?

**Comment by l2isbad** [comment]
**$this** is the result of **lookup/calc** action
Look into your alarm log just after `killall -USR2 netdata` and you will see a lot of NaN

**Comment by ktsaou** [comment]
Right. `$this` is the result of `lookup` and `calc`.
You can use in `warn` and `crit` the dimensions directly though. So, instead of `$this` use `$dimension` (as shown on the dashboard). So, assuming the fans are named `fan1`, `fan2`, `fan4`, `fan5` you can either add 4 alarms one for each dimension, or a combined alarm, like this:

```
warn: $fan1 < 1100 OR $fan2 < 1100 OR $fan4 < 1100 OR $fan5 < 1100
crit: $fan1 < 800 OR $fan2 < 800 OR $fan4 < 800 OR $fan5 < 800
```

**Comment by ktsaou** [comment]
I am closing this.
If you need more help, just post.
