### ISSUE TITLE
Install on Ubiquity Edgerouter?

### ISSUE THREAD

**Issue by ne0shell** [firehol/netdata#118]
Would it be possible to get this working on my edgerouter?

**Comment by jbehrends** [comment]
The Edgerouter's OS is based on Debian, so looking at the install guide (https://github.com/firehol/netdata/wiki/Installation) it appears that it would be possible.  You'd have to setup repo's on the Edgerouter first (https://help.ubnt.com/hc/en-us/articles/205202560-EdgeMAX-Add-other-Debian-packages-to-EdgeOS), then you should be able to install the prerequisites.

**Comment by Sachiru** [comment]
Initial tests on the Edgerouter reveal the following:

App installs successfully, however, upon restart the /var/log/netdata folder disappears, thus preventing netdata from being relaunched. Manually recreating the folder works and the netdata binary launches again. 

This appears to be an EdgeMax issue.

Also, the netdata binary appears to consume a large chunk of CPU power.

**Comment by Sachiru** [comment]
Further research reveals this thread:

https://community.ubnt.com/t5/EdgeMAX/Edgerouter-Pro-all-logs-are-deleted-after-reboot/td-p/1000371

As a workaround, either recreating the logging directory or turning off debug logging fixes this issue.

**Comment by ktsaou** [comment]
To lower the CPU requirements, just increase `update every` in netdata config. If you change it from `1` to `2`, you will half the CPU requirements of netdata and you will have every 2 seconds data collection.

Also, disable external plugins (again in the netdata config). `charts.d.plugin` is BASH (slow) and `apps.plugin` is heavy (heavier than netdata itself). If you need them, set their `update every` to `5` or `10`.

**Comment by Sachiru** [comment]
Thanks for the suggestions. Setting update to 2 seconds and setting plugins to 4 second halved the load.

Only thing not showing up now is QoS metrics.

**Comment by ktsaou** [comment]
are there any qos (`tc` rules), active?

There is a script that handles this (https://github.com/firehol/netdata/blob/master/plugins.d/tc-qos-helper.sh).

Practically this is what it does for each device:

 ```sh
tc -s class show dev $device
```

And to get the devices, it does this:

```sh
cat /proc/net/dev | grep ":" | cut -d ':' -f 1
```

**Comment by ktsaou** [comment]
Is this settled. May we close it?

**Comment by jbehrends** [comment]
Feels like the original question was answered to me.
I say close it.

**Comment by ktsaou** [comment]
I see on this post:

https://community.ubnt.com/t5/EdgeMAX/FEATURE-REQUEST-Netdata-support-for-Edgerouter-Edgemax/m-p/1528174/highlight/true#M105512

They get high CPU usage.

If you can post on this forum, please let them know they can edit `netdata.conf` to set `update every = 2` (update every 2 seconds - or even more if it still gets a lot of CPU) and at the plugins section disable `charts.d` and `apps.plugin` (they are both CPU hungry).
With these settings, netdata should work well on these devices.

**Comment by stickbird** [comment]
Hy!

 

I tried to install netdata in my EdgeMAXPOE, but isn't running.

 

First I tried with:

ubnt@Router# sudo apt-get install netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netdata
[edit]
 

 

 

And then I tried:

 

ubnt@Router# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : mips64
BASH major version: 4
 --- Downloading script to detect required packages... --- 
[/home/ubnt]$ /usr/bin/curl https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41978  100 41978    0     0   109k      0 --:--:-- --:--:-- --:--:--  136k
 OK   

 --- Running downloaded script to detect required packages... --- 
[/home/ubnt]$ sudo /bin/bash /tmp/netdata-kickstart-lsrygX netdata 
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 7 (wheezy)
ID              : debian
ID_LIKE         : 
VERSION_ID      : 7

We detected these:
Distribution    : debian
Version         : 7
Codename        : 7 (wheezy)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib1g-dev' is installed...
dpkg-query: no packages found matching zlib1g-dev
 > Checking if package 'uuid-dev' is installed...
dpkg-query: no packages found matching uuid-dev
 > Checking if package 'libmnl-dev' is installed...
dpkg-query: no packages found matching libmnl-dev
 > Checking if package 'python-yaml' is installed...
dpkg-query: no packages found matching python-yaml
 > Checking if package 'python-pymongo' is installed...
dpkg-query: no packages found matching python-pymongo

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   apt-get update  

apt-get install libmnl-dev python-pymongo python-yaml uuid-dev zlib1g-dev 


Press ENTER to run it > 
apt-get install libmnl-dev python-pymongo python-yaml uuid-dev zlib1g-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmnl-dev : Depends: libmnl0 (= 1.0.3-3) but 1.0.3-5 is to be installed
 uuid-dev : Depends: libc6-dev but it is not going to be installed or
                     libc-dev
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues


 FAILED   

It failed to install all the required packages, but I can try to install netdata.
Press ENTER to continue to netdata installation > 
 --- OK, let's give it a try... --- 
 --- Updating netdata source code... --- 
[/usr/src/netdata.git]$ sudo /usr/bin/git fetch --all 
Fetching origin
 OK   

[/usr/src/netdata.git]$ sudo /usr/bin/git reset --hard origin/master 
Checking out files: 100% (737/737), done.
HEAD is now at 5b10604 Merge pull request #4139 from paulfantom/patch-1
 OK   

 --- Installing netdata... --- 
[/usr/src/netdata.git]$ sudo ./netdata-installer.sh -u 

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

 --- Run autotools to configure the build environment --- 
[/usr/src/netdata.git]# autoreconf -ivf 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
 OK   

[/usr/src/netdata.git]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O2 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... none
checking build system type... mips64-unknown-linux-gnu
checking host system type... mips64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/src/netdata.git':
configure: error: C compiler cannot create executables
See `config.log' for more details
 FAILED   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues


 FAILED   

 ABORTED  netdata-installer.sh exited with error 

[edit]

You can see the errors you give ...
I have installed the packages: gcc make autoconf automake pkg-config, but it still does the same.
But the compiler don't work!
 

Can anyone post step by step how to install it correctly?


Thanks!

**Comment by Ferroin** [comment]
Possible causes for that configure error include:

* You don't actually have a compiler installed.
* The configure script found some executable other than the C compiler (which obviously won't work for compiling things).
* The configure script tried to pass an option to the C compiler that it does not recognize (for example, trying a `-fstackprotector` option on a 3.x series GCC).
* The compilation failed for some other reason (disk is out of space, ran into a memory error, etc).

**Comment by ktsaou** [comment]
@stickbird could you please post your `config.log`?

**Comment by stickbird** [comment]
@ktsaou  what you need?!?
There are'nt a config.log in the Logs on /var/log.

**Comment by ktsaou** [comment]
No, I meant that when you run the installer it says:

```
configure: error: in `/usr/src/netdata.git':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

So, you should have `config.log` in `/usr/src/netdata.git`. This is the one that will tell us why your compiler fails.

**Comment by paulfantom** [comment]
> See `config.log' for more details

Is this customizable? If yes, maybe it would be better to show full path to file?

**Comment by ktsaou** [comment]
I am afraid it is not. This error is printed by `autoconf`.
