### ISSUE TITLE
New installation on Debian, nothing visible except background image

### ISSUE THREAD

**Issue by creativelies** [firehol/netdata#1188]
Install goes smoothly on Debian 8 Jessie following the instructions, no error messages but when I access the URL I get the background image and nothing else. The /var/log/netdata/error.log shows most recently:

```
2016-10-31 11:50:02: apps.plugin: ERROR: Cannot process /proc/7807/io (command 'cron') (errno 3, No such process)
2016-10-31 12:27:02: apps.plugin: ERROR: Cannot process /proc/9226/io (command 'cron.sh') (errno 3, No such process)
```

...but that error is not consistent with when I try to access the page.

The error.log entries could be unrelated - what am I missing here with the install? It's behind an nginx reverse proxy with upstream:

```
upstream netdata {
            server 127.0.0.1:19999;
            keepalive 64;
}
```

 and location block config:

```
location ~ /net/(?<ndpath>.*) {
    auth_basic "Restricted";
    auth_basic_user_file /opt/pw/.htpasswd;
    proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;
    }
```

This same nginx config appeared to be working on a previous server without issue.

**Comment by ktsaou** [comment]
Press F12 on you browser to check the console errors and examine nginx errors.
There is something wrong in the nginx configuration and things fail to be transferred.

**Comment by creativelies** [comment]
Nothing is turning up in /var/log/nginx/error.log and /var/log/nginx/access.log shows 200 responses for this:

"GET /net/api/v1/alarms?active&_=1478040929101 HTTP/1.1" 200 129

The console shows only this upon page load:

> window.controllers is deprecated. Do not use it for UA detection.

Any ideas where I should start looking for solutions regarding what to change in the nginx config?

**Comment by ktsaou** [comment]
In most of the cases, this means `/` is missing in a path.

Please do this: While you have a `tail -f /var/log/netdata/*.log /var/log/nginx/*.log` running on a terminal, press F5 on your browser.

Could you please post the log?

**Comment by creativelies** [comment]
Well that sounds promising! Log output:

Nginx logs:

```
1.158.178.2 - user [02/Nov/2016:10:11:14 +1100] "GET /net/api/v1/alarms?active&_=1478041841497 HTTP/1.1" 200 129 "https://url.org/net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"
1.158.178.2 - user [02/Nov/2016:10:11:15 +1100] "GET /net/api/v1/alarms?active&_=1478041873551 HTTP/1.1" 200 129 "https://url.org/net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
1.158.178.2 - user [02/Nov/2016:10:11:15 +1100] "GET /net/api/v1/registry?action=hello&_=1478041873552 HTTP/1.1" 200 157 "https://url.org/net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
1.158.178.2 - user [02/Nov/2016:10:11:16 +1100] "GET /net/api/v1/alarm_log?after=0&_=1478041873553 HTTP/1.1" 200 8948 "https://url.org/net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
```



Netdata log:

```
2016-11-02 10:11:12: 5: (sent/all = 33842/156148 bytes -78%, prep/sent/total = 0.05/3.49/3.54 ms) filecopy: 200 '/'
2016-11-02 10:11:14: 5: (sent/all = 118/122 bytes -3%, prep/sent/total = 0.05/0.84/0.89 ms) data: 200 '/api/v1/alarms?active&_=1478041841497'
2016-11-02 10:11:14: 5: (sent/all = 118/122 bytes -3%, prep/sent/total = 0.04/0.73/0.78 ms) data: 200 '/api/v1/alarms?active&_=1478041873551'
2016-11-02 10:11:15: 5: (sent/all = 146/165 bytes -12%, prep/sent/total = 0.04/0.54/0.57 ms) data: 200 '/api/v1/registry?action=hello&_=1478041873552'
2016-11-02 10:11:16: 5: (sent/all = 8935/142392 bytes -94%, prep/sent/total = 0.83/1.67/2.51 ms) data: 200 '/api/v1/alarm_log?after=0&_=1478041873553'
2016-11-02 10:11:25: 5: (sent/all = 117/122 bytes -4%, prep/sent/total = 0.05/0.82/0.87 ms) data: 200 '/api/v1/alarms?active&_=1478041873555'
2016-11-02 10:11:26: 5: (sent/all = 118/122 bytes -3%, prep/sent/total = 0.04/0.58/0.62 ms) data: 200 '/api/v1/alarms?active&_=1478041841498'
2016-11-02 10:11:36: 5: (sent/all = 118/122 bytes -3%, prep/sent/total = 0.05/0.64/0.69 ms) data: 200 '/api/v1/alarms?active&_=1478041873556'
```

**Comment by ktsaou** [comment]
Something is missing...

I see requests in netdata access log that do not appear in nginx log... probably you didn't copied everything.

Do you get errors on your browser console? Press F12 to your browser and switch to console and network. Then press F5 to reload the page. Do you see errors?

**Comment by creativelies** [comment]
No errors other than:

`window.controllers is deprecated. Do not use it for UA detection.
`

**Comment by ktsaou** [comment]
hm... is there a control-F5 in safari to force reloading the page?

I am sorry, but I don't really know how to help you with that. It seems that the requests are not going to your nginx. Safari must have responses cached so, you have to find a way to force reloading the page to get the logs from nginx.

Clearing the browser cache may help.
Can you give it a try?

**Comment by creativelies** [comment]
Oh, I get the same result using Firefox or Chrome - Safari isn't my primary browser, it's what I usually use when the others aren't working to check something!

I cleared the cache in Firefox (should have done that earlier... sorry) and got the following error in nginx:

`2016/11/03 09:30:21 [error] 23030#23030: *25999 open() "/var/www/url.org/net/dashboard.js" failed (2: No such file or directory), client: 108.162.222.123, server: url.org, request: "GET /net/dashboard.js?v20161030-30 HTTP/1.1", host: "url.org", referrer: "https://url.org/net/"
`

**Comment by ktsaou** [comment]
ok, that is better.

So, your nginx is not sending `/net/dashboard.js?v20161030-30` to netdata, but tries to serve it from disk.

I just installed your configuration on my nginx and everything works perfectly, even authentication.
Is it possible that you have other rules that may interfere?

**Comment by creativelies** [comment]
Something else in my config is clearly interfering with it - I moved the netdata-related stanza up to the top of the nginx config file and all is working perfectly now.

Thanks very much for the help there. I'm not sure what was causing it - other things in the file are:


 ```
 location / 	{
				try_files $uri $uri/ =404; 

index index.php;

}

	location ~ \.php$ {
	try_files $uri =404;
#	fastcgi_index index.php;	
	fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;	
#	fastcgi_pass unix:/var/run/php5-fpm.sock;
	include /etc/nginx/fastcgi_params;
	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			}

        location ~*  \.(svg|jpg|jpeg|png|gif|ico)$ {
                        expires 7d;
                        }

        location ~*  \.(css|js)$ {
                        expires 60m;
                        }
```

**Comment by ktsaou** [comment]
nice! I am closing this.
