### ISSUE TITLE
Nvme0n1 labelled drives

### ISSUE THREAD

**Issue by jrens** [firehol/netdata#119]
Trying to get netdata to monitor a nvme drive in ubuntu. I naively duplicated the config for one of my other drives however this doesn't show up. Also localhost:19999/netdata.conf doesn't seem to have updated either. Any help?
[netdatadiff.txt](https://github.com/firehol/netdata/files/199029/netdatadiff.txt)

**Comment by ktsaou** [comment]
Nice drive you have!

I need to know its major and minor device numbers.
So, if your drive is `/dev/nvme`, so this:

```sh
ls -l /dev/nvme*
```

And post the output.

**Comment by karel1980** [comment]
I don't have one, but here is some information for nvme devices: http://en.community.dell.com/techcenter/os-applications/w/wiki/7581.nvme-on-rhel7

This document contains a bit more information: https://www.kernel.org/doc/Documentation/devices.txt
The nvme disks have major 253 (which is marked as local/experimental, so not sure if that's permanent)
The partitions have major 259.

**Comment by ktsaou** [comment]
major 253 has been added with this PR: #96 .
It is already merged.
So, just pull it again and install it.

**Comment by jrens** [comment]
It is indeed. #96 didn't catch it. Here is the output
```
crw------- 1 root root 248, 0 Apr  4 09:42 /dev/nvme0
brw-rw---- 1 root disk 259, 0 Apr  4 09:42 /dev/nvme0n1
brw-rw---- 1 root disk 259, 1 Apr  4 09:42 /dev/nvme0n1p1
brw-rw---- 1 root disk 259, 2 Apr  4 09:42 /dev/nvme0n1p2
brw-rw---- 1 root disk 259, 3 Apr  4 09:42 /dev/nvme0n1p3
brw-rw---- 1 root disk 259, 4 Apr  4 09:42 /dev/nvme0n1p4
brw-rw---- 1 root disk 259, 5 Apr  4 09:42 /dev/nvme0n1p5
brw-rw---- 1 root disk 259, 6 Apr  4 09:42 /dev/nvme0n1p6
```

**Comment by ktsaou** [comment]
ok added.
I assumed up to 16 partitions are supported. If it is otherwise, please let me know to adapt it.

**Comment by jrens** [comment]
Perfect. Thanks for your help. Very nice product.
