### ISSUE TITLE
Desktop notifications from custom dashboard charts

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1190]
To get desktop notifications i should log into default dashboard (:19999) and set "refresh chart" option to always.
It would be very handy if netdata could  push alarms notifications for charts/dimensions which are located on custom dashboard.

**Comment by ktsaou** [comment]
> To get desktop notifications i should log into default dashboard (:19999) and set "refresh chart" option to always.

there is no need to set chart refresh to always. Notifications work **always** (every 10 seconds), even if the dashboard is paused and focus has been lost.

> It would be very handy if netdata could push alarms notifications for charts/dimensions which are located on custom dashboard.

On your custom dashboards, just set:

```html
<script>var netdataShowAlarms = true;</script>
```

**before** loading `dashboard.js`. You will have notifications on your dashboard too.

There are many options that control the dashboard.

### options to set before loading dashboard.js

https://github.com/firehol/netdata/blob/d7531dc0c44294e3aae6b52655c2ab7795138453/web/dashboard.js#L1-L30

### options to set after loading dashboard.js

https://github.com/firehol/netdata/blob/d7531dc0c44294e3aae6b52655c2ab7795138453/web/dashboard.js#L258-L333

You can use, `NETDATA.setOption(key, value);` to set these. `key` should be string (i.e. enclosed in quotes).

**Comment by l2isbad** [comment]
many thx!
