### ISSUE TITLE
sms support

### ISSUE THREAD

**Issue by wioxjk** [firehol/netdata#1198]
Stumbled upon this sms api:
http://api.ip1sms.com

Having tried it myself and am very satisfied, is it possible to integrate it in netdata?
You have to sign up and pay to use the service thou,

**Comment by shadycuz** [comment]
I already have some working code for twillio API. Twillio allows any one to register and use 1 free number. I thought about working this into netdata because I don't use push notifications because of the hit on battery life.

I did have questions though, like how to access the health alarms, so that for every new alarm a new sms is sent. I only really know Python and I didn't think this would make sense as a plugin because most of the plugins are based around displaying a chart.

**Comment by ktsaou** [comment]
It is just a bash script guys: https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh

You can duplicate `pushbullet` or `pushover` to adapt it to any API. If you do, please make a PR.

**Comment by shadycuz** [comment]
I'll take a look at it tonight, im looking at the alarm bash script now. I
didn't know you could do so much in bash. Makes all the nifty little
scripts I wrote look like html compared to Django lol

**Comment by shadycuz** [comment]
@ktsaou I worked on it all night, all the code should be duplicated, but It's not working and I'm not seeing any relevant error msgs in the debug log. Just random alarm info. Could you please give a look over while I'm alseep? I'm thinking it is something simple?? It's either failing at the curl or before, I'm not seeing any thing in my twilio API logs.

[The branch I made](https://github.com/shadycuz/netdata/tree/sms_feature)

**Comment by ktsaou** [comment]
Thanks! Will do later today.

**Comment by ktsaou** [comment]
I think this is the command needed:

```sh
            httpcode=$(${curl} -X POST --write-out %{http_code} --silent --output /dev/null \
                --form-string "From=${twilionumber}" \
                --form-string "To=${user}" \
                --form-string "Body=${message}" \
                -u "${accountsid}:${accounttoken}" \
                "https://api.twilio.com/2010-04-01/Accounts/${accountsid}/Messages.json")
```

Can you test it?

Keep in mind phone numbers have to be given in international notation (i.e. `+ COUNTRYCODE PHONENUMBER`).

**Comment by ktsaou** [comment]
I updated the code. Take it from github.

**Comment by ktsaou** [comment]
btw, they have a `curl` example at their site:

![image](https://cloud.githubusercontent.com/assets/2662304/19979753/417dd096-a204-11e6-8c8c-2bfb6c77b676.png)

**Comment by shadycuz** [comment]
@ktsaou I have implemented the changes to curl, and I'm not seeing much change. Twilio is still not getting the curl. The only change I see is that killall -USR2 netdata is actually refreshing the alarm notification in the browser, where it didn't seem to be before. I have poured through the Logs and I'm not seeing anything related to alarm-notify.sh or twilio, I'm going to attempt to run it by hand and see if I see anything.

**Comment by shadycuz** [comment]
@ktsaou What I did was test the curl manually and it was able to send a txt msg to my phone. I then tried to run ./alarm-notify.sh test and it pointed out all the typos I had made like several missing $ in front of variables and I put a space in front of a variable name once. So I fixed all the ${varname}. I then ran ./alarm-notify.sh test +1myphonenumber and the errors are gone but I'm not seeing the info output from the send_twilio.

 Only 
`2016-11-03 20:08:49: alarm-notify.sh: INFO: sent email notification for: Webhost test.chart.test_alarm is CRITICAL to 'root'`

Does the test routine test all notification types? Do I need to still supply my SID,TOKEN,TWILIONUMBER manually when I run alarm-notify.sh? or will it still grab that out of health_alarm_something.conf?

**Comment by shadycuz** [comment]
@ktsaou I will keep working on it but I know it's not executing the send_twilio part. I'm not sure why it fails to get that far. I also don't think I'm using the alarm-notify.sh test routine right. I have a feeling if I go in and hardcode the api,token and number into the code it will work.

**Comment by ktsaou** [comment]
make a PR and I guide you to fix it.

**Comment by shadycuz** [comment]
@ktsaou Here #1211, could the + in the phone number interfere with building the recipients? That is the only thing I can think of. I should have done some basic debugging like printing some of my variables to stdout just to make sure they were being loaded properly from health_notify.conf

**Comment by ktsaou** [comment]
> I'm not sure how to fix it now that I submitted the PR. I still think before send_twilio(), SEND_TWILIO is being set to = "NO"

Just commit it as usual and push it. It will automatically appear in the PR.

**Comment by shadycuz** [comment]
So I checked, and SEND_TWILIO stays "YES" all the way through the script. I'm not sure why in my logs all scripts are set to disabled.

**Comment by shadycuz** [comment]
@ktsaou  I'm still investigating, but just in case your looking at it as well, This IF inside of send_twilio() is being eval as False.

if [ "${SEND_TWILIO}" = "YES" -a ! -z "${accountsid}" -a ! -z "${accounttoken}" -a ! -z "${twilionumber}" -a ! -z "${recipients}" -a ! -z "${message}" -a ! -z "${title}" ]

I checked SEND_TWILIO and it's "YES" and accountsid , accounttoken and twilionumber all have the appropriate values from the config file. I'm going to echo the last 3 values and see what they come out to be.

**Comment by ktsaou** [comment]
Why don't you just print all these variables? A variable is empty...

**Comment by ktsaou** [comment]
This requires 6 parameters:

```
local accountsid="${1}" accounttoken="${2}" twilionumber="${3}" recipients="${4}"  title="${5}" message="${6}"
```

but this, passes only 4:

```
send_twilio "${TWILIO_ACCOUNT_SID}" "${TWILIO_ACCOUNT_TOKEN}" "${TWILIO_NUMBER}" "${host} ${status_message} - ${name//_/ } - ${chart}" "${alarm}\n 
 +Severity: ${severity}\n
 +Chart: ${chart}\n
 +Family: ${family}\n
 +To View Netdata go to: ${goto_url}\n
 +The source of this alarm is line ${src}"
```

**Comment by ktsaou** [comment]
it passes 5, so one is missing...

**Comment by shadycuz** [comment]
@ktsaou I see what I did wrong, I passed in the to_twilio recipients and it now fails at the else part with a syntax error. Not sure if bash is picky about white space or not? I'm thinking when I pasted in your code above, I didn't align it up properly.

```
/usr/libexec/netdata/plugins.d/alarm-notify.sh: line 661: syntax error near unexpected token `else'
/usr/libexec/netdata/plugins.d/alarm-notify.sh: line 661: `            else'
# FAILED

```

I'll be back in an hour to investigate it, I'm going to go get some food.

**Comment by shadycuz** [comment]
@ktsaou @wioxjk Alarms are up and working. This is mostly a double post of what I posed in the PR #1211 . When should I add the Twilio Documentation to the wiki? What do you think about including the host the alarm is coming from in all the alerts? I have 3 hosts running Netdata and already I'm sick of looking in the URL included in the alarm notification for the name of the host. It's kinda silly if you only have 1 install though, but maybe we can find a decent solution when the multi-server dashboard is built? 

![image](https://cloud.githubusercontent.com/assets/17090999/20028069/c3b75542-a2fd-11e6-85d0-cc6ccbe36e8e.png)

**Comment by ktsaou** [comment]
bravo!

> When should I add the Twilio Documentation to the wiki?

now.

> What do you think about including the host the alarm is coming from in all the alerts?

for all notification methods, the host is the first word. Actually, your alarms should say `Plex needs attention ...`

**Comment by ktsaou** [comment]
@wioxjk twilio is now merged, so you can use it.
If you still need ip1sms.com support, please try to adapt `alarm-notify.sh`, much like @shadycuz did. It is a simple shell script, so it is relatively easy to do it (yes, I know @shadycuz lost his sleep to do it... but still bash is the simplest computer language).

**Comment by wioxjk** [comment]
Thank you

**Comment by ktsaou** [comment]
ok, I consider this fixed then.
If you adapt it, make a PR.

thank you @shadycuz !
