### ISSUE TITLE
Is there no password protection?

### ISSUE THREAD

**Issue by sankalpsingha** [firehol/netdata#120]
I want to use this to keep a monitor on my server. Is there no way of password protecting the interface?

Currently anyone with the knowledge of my `server-ip:19999` can access the interface. 

Or am I missing something? :open_mouth:

**Comment by Kubuxu** [comment]
See https://github.com/firehol/netdata/issues/101 and https://github.com/firehol/netdata/wiki/Running-behind-nginx#enable-authentication

**Comment by sankalpsingha** [comment]
Yup I see that now. But I think that not every one would want to keep it behind an nginx upstream and a small authentication can be made in the application itself. Just as a basic security feature. Just my two cents..

**Comment by ktsaou** [comment]
You are right. However authentication without SSL is not that much of a security.
So, SSL is needed first, but it is not my first priority.
If you really need this now, I suggest to pass netdata through another web server.

**Comment by mcnewton** [comment]
We have over 150 servers and having found this project it would be nice to run it on them all. But we can't do that without any sort of protection, and we wouldn't install nginx or apache on everything. By default we'd use iptables anyway, but if that's accidentally disabled this becomes wide open. So some sort of added access control would be nice at some point.

**Comment by ktsaou** [comment]
If your servers are not directly on the internet (i.e. they are in a DMZ), you can:

1. disable port 19999 at your DMZ firewall.
2. have just one nginx to proxy all netdata installations. I added info at the wiki: https://github.com/firehol/netdata/wiki/Running-behind-nginx#access-multiple-netdata-servers-via-one-nginx

I really understand this is feature is needed. Please work around it, until it is coded in netdata.

**Comment by mcnewton** [comment]
We have all servers directly on the Internet (behind firewall, but there is internal access from a large number of untrusted machines, so essentially "on the Internet") :-).

But thanks for the link, it's a useful nginx config! Absolutely no pressure from me to get the feature. But something would be useful one day.

**Comment by gueff** [comment]
You may be interested in this little howto, explaining how to install netdata and run it behind an apache with Basic Auth: 
https://blog.ueffing.net/post/2016/04/03/how-to-install-firehol-netdata-on-a-linux-ubuntu-14-04-box-and-run-it-behind-an-apache2-proxy-with-basic-auth-protection/

**Comment by tx7** [comment]
Hi,
First, I want to say thanks to the creator of this plugin; it's awesome.
I'm currently running behind Nginx.

My question is that I've setup with SSL and password protected when I go my site:
https://abc.xyz.com:7443

The 'registry' in the  /etc/netdata/netdata.conf , for 'registry to announce',  do I enter https://abc.xyz.com:7443 or https://abc.xyz.com:19999 ?

My registry domain = abc.xyz.com

**Comment by ktsaou** [comment]
The registry is using the same settings as with the rest of netdata.
It cannot be working with `https://abc.xyz.com:19999`. Netdata does not have HTTPS support. Unless you also proxy port 19999.

**Comment by tx7** [comment]
This my Nginx: 

`auth_basic "Protected";
auth_basic_user_file /etc/nginx/.htpasswd;
location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:19999;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_store off;
    }`

**Comment by ktsaou** [comment]
Your nginx should be listening to port 7443 for requests which will forward to netdata at 19999. This happens for registry requests too.

**Comment by tx7** [comment]
I'm new to this Nginx setup stuff.
I has Nginx listening on port 7443, and the proxy pass is on port 19999, is that correct?

**Comment by ktsaou** [comment]
Cleaning up. Let's continue the discussion about authentication support in netdata at #70 .
Thanks!
