### ISSUE TITLE
Creating alarm

### ISSUE THREAD

**Issue by mo0nsniper** [firehol/netdata#1202]
Hello,

I want to create an alarm for when there are many network packets received on an interface (ex. 10000).
I want to use it to detect when my server is under a DoS/DDoS.

The problem is that I can't find the chart information for packets received or packets transmitted for the net chart.

Where could I find that information for the net chart, or a general way for any other chart?

Thanks

**Comment by shadycuz** [comment]
@mo0nsniper Have a look at this wiki page [DDOS SYNPROXY](https://github.com/firehol/netdata/wiki/Monitoring-SYNPROXY)

**Comment by ktsaou** [comment]
You don't have these charts?

http://registry.my-netdata.io/#menu_net

So, the packet charts are called something like `net_packets.eth0`

**Comment by mo0nsniper** [comment]
Yes, I have the net charts, but it's not clear to me from the documentation what should be in the alarm on the "on:" line.
The two questions that I have are:
- What should I put just for sent packets?
- And if I want to make the alarm for all network interfaces?

**Comment by mo0nsniper** [comment]
@shadycuz Thanks, I've tried to setup SYNPROXY but got an error. Opened issue [here](https://github.com/firehol/firehol/issues/156)

Also I would need the alarm on number of packets for the UDP DoS

**Comment by l2isbad** [comment]
template: ddos_check
        on: net.packets
        lookup: average -5m of sent
        every: 1s
        crit: $sent > 9999
        to: sysadmin

**or better check spikes**  (current value gt then 500% from avg for last 5 min)

template: ddos_check
        on: net.packets
        lookup: average -5m of sent
        every: 1s
        calc: ($sent - $this)/($this/100)
        crit: $this >= 500
        to: sysadmin

**Comment by ktsaou** [comment]
nice! However, the `received` dimension should be used.

I had them already written when @l2isbad posted, so here there are alternative versions:

```
   alarm: eth0_packets
      on: net_packets.eth0
   units: packets
   every: 10s
    warn: $received > 5000
    crit: $received > 10000
   delay: down 10m multiplier 1.5 max 1h
    info: number of packets received on the interface
      to: sysadmin
```

The above will check once every 10s if the current rate of received packets is above 5000 (warning) or 10000 (critical). It will send an alarm immediately when the alarm arms, but it will wait 10m before sending a disarm notification.

The following is the same, but it does not check the last  value, but the average of the last 10 seconds

```
   alarm: eth0_packets
      on: net_packets.eth0
  lookup: average -10s of received
   units: packets
   every: 10s
    warn: $this > 5000
    crit: $this > 10000
   delay: down 10m multiplier 1.5 max 1h
    info: number of packets received on the interface
      to: sysadmin
```

The following will also protect you in case you have spikes:

```
   alarm: eth0_packets
      on: net_packets.eth0
  lookup: average -10s of received
   units: packets
   every: 10s
    warn: $this > ($status >= $WARNING)?(3000):(5000))
    crit: $this > ($status == $CRITICAL)?(8000):(10000))
   delay: down 10m multiplier 1.5 max 1h
    info: number of packets received on the interface
      to: sysadmin
```

**Comment by ktsaou** [comment]
@l2isbad created templates, using the context of the charts. Unfortunately the context is found at the `http://your.netdata/api/v1/charts` response and `/etc/netdata/netdata.conf`.

So, his versions apply the alarms on all network interfaces.

**Comment by l2isbad** [comment]
in the last message he wrote about sent dimension

> The two questions that I have are:
> 
> What should I put just for sent packets?
> And if I want to make the alarm for all network interfaces?

**Comment by ktsaou** [comment]
oh... I see... I lost that...
So, **you are the best**!
Thanks for answering it!

**Comment by mo0nsniper** [comment]
You are both right :) I wrote sent but meant received packets.
Also thanks for explaining me how to create the alarm, I think I understant it now.

I'll make a template for generating alarms on all interfaces.
Do you think this could be usefull to be included in netdata?

**Comment by l2isbad** [comment]
It very depends. Personally i dont think it is a good idea to have this types of alarms on by default.
But it makes sense if such alarms will be only included but not activated.

**Comment by ktsaou** [comment]
Well, I could add a `silent` alarm (it will only be shown when you view the dashboard) and have something to detect spikes:

```
template: 1m_received_packets_rate
      on: net.packets
  lookup: average -1m of received
   units: packets
   every: 1m
    info: the average number of packets received during the last minute

template: 10s_received_packets_spike
      on: net.packets
  lookup: average -10s of received
    calc: $this * 100 / (($1m_received_packets_rate < 100)?(100):($1m_received_packets_rate))
   every: 10s
   units: %
   warn: $this > (($status >= $WARNING)?(200):(1000))
   crit: $this > (($status >= $WARNING)?(1000):(2000))
   info: the % of the rate of received packets in the last 10 seconds, compared to the rate of the last minute
   role: silent
```

### in detail

the following is just a calculation. It will allow other alarms of the same interface to use `$1m_received_packets_rate`, which resolves to the average rate packets are received in the last minute.

```
template: 1m_received_packets_rate
      on: net.packets
  lookup: average -1m of received
   units: packets
   every: 1m
    info: the average number of packets received during the last minute
```

the following is the alarm. It first lookups the average of the received packets rate during the last 10s. Then this calculates the percentage compared to `$1m_received_packets_rate`. To avoid alarms when an interface is just idle, if `$1m_received_packets_rate < 100` it assumes it is `100`.

Them the alarm, is triggered if the 10s average is 1000% compared to 1m average (warning at 10x), or 2000% (critical at 20x).

It is silent, so no notifications will be sent. It will be just shown when the dashboard is open at a browser window and will be logged at the alarm log.

```
template: 10s_received_packets_spike
      on: net.packets
  lookup: average -10s of received
    calc: $this * 100 / (($1m_received_packets_rate < 100)?(100):($1m_received_packets_rate))
   every: 10s
   units: %
   warn: $this > (($status >= $WARNING)?(200):(1000))
   crit: $this > (($status >= $WARNING)?(1000):(2000))
   info: the % of the rate of received packets in the last 10 seconds, compared to the rate of the last minute
   role: silent
```

What do you think?
Can you test it?

**Comment by mo0nsniper** [comment]
Sounds good to me.
I've installed the alarm on the server and until now with normal traffic got no alarm.

**Comment by ktsaou** [comment]
added it, although I increased the minimum packets from 100 to 1000.
