### ISSUE TITLE
netdata should create /var/cache/netdata at startup

### ISSUE THREAD

**Issue by candrews** [firehol/netdata#1204]
Netdata should create /var/cache/netdata when it starts if that directory doesn't already exist.

Currently the [open-rc script does this](https://github.com/firehol/netdata/blob/4d456e3740ad6bdab3f183b104f4d8e3a982b74f/system/netdata-openrc.in#L37) but rather than having each init script handle this responsibility, it would be better if netdata did it.

**Comment by ktsaou** [comment]
Will it be able to?

I mean, in systemd systems, netdata is started as user `netdata`. Will user `netdata` be able to create `/var/cache/netdata`?

**Comment by ktsaou** [comment]
I did, but I don't know if this will help (it will help if netdata is started as root though).

**Comment by ktsaou** [comment]
Check #1205. Are you ok?
