### ISSUE TITLE
Disks: exclude/ignore nfs mounts

### ISSUE THREAD

**Issue by patschbo** [firehol/netdata#1206]
is it possible to add something like an ignorelist/excludes to the netdata.conf [plugin:proc:/proc/diskstats]  to ignore for example nfs mounts?

**Comment by ktsaou** [comment]
There are sections like this:

```
[plugin:proc:/proc/diskstats:/]
	# enable space metrics = auto
	# space usage = auto
	# inodes usage = auto
```

Uncommenting them and setting them to `no` will disable them.

**Comment by patschbo** [comment]
but we use the automounter (with nfs) for example to mount dynamic the homeshares of our users, so how could i handle this? i dont wont see this ones...

I have now tried following:

```
[plugin:proc:/proc/diskstats]
	space metrics for mounted filesystems = no
	space usage for all disks = no
	inodes usage for all disks = no
```

but it still create this graphs!? Do i something wrong or i misunderstand this options....

thanks for your help

**Comment by ktsaou** [comment]
You are so right! My bad.
I fixed these options in PR #1210

In the same PR, I added option `exclude space metrics on paths` which allows you to set path prefixes (a space separated list of them), which will be excluded from disk space statistics. So, if your automounter mounts the users' homes at `/home/<USER>`, `/users/<USER>` and `/automounted/<USERS>`, you can set `exclude space metrics on paths = /home/ /users/ /automounted/`.

Keep in mind you have to download the latest version of `netdata.conf` from your server, once you install the latest,

**Comment by rda0** [comment]
@ktsaou is it possible that `exclude space metrics on paths` no longer works?

We are using the latest netdata version from github and are unable to exclude nfs mounts with:

```
[plugin:proc:diskspace]
    exclude space metrics on paths = /home/ /net/ /backup/ /public/
```

Excluding by type (`nfs`, `autofs`) with `exclude space metrics on filesystems` has no effect as well:

```
[plugin:proc:diskspace]
    exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs nfs
```

**Comment by ktsaou** [comment]
Just tested excluding `nfs`. It works.

The filesystem is extracted from `/proc/self/mountinfo` (the third parameter before the end of each line).

**Comment by rda0** [comment]
Thank you @ktsaou for your reply.

I think I was confused, because I did not understand how netdata needs to be configured in a master-slave setup (with all ephemeral slaves). With the following lines in the **master `netdata.conf`**:

```
[plugin:proc:diskspace]
	exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs nfs
	exclude space metrics on paths = /home/ /net/ /backup/ /public/ /home/* /net/* /backup/* /public/*
```

I can do the following on the master:

```
# curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[plugin:proc:diskspace\]/,/^$/p'
[plugin:proc:diskspace]
	exclude space metrics on paths = /home/ /net/ /backup/ /public/ /home/* /net/* /backup/* /public/*
	exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs nfs
...

# curl -Ss 'http://localhost:19999/host/slave/netdata.conf' | sed -n -e '/\[plugin:proc:diskspace\]/,/^$/p'
[plugin:proc:diskspace]
	exclude space metrics on paths = /home/ /net/ /backup/ /public/ /home/* /net/* /backup/* /public/*
	exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs nfs
...
```

Which led me to the assumption, that the configuration from the master is inherited somehow by the slave. But this is not the case, as the excludes do not have any affect on the slave.

Then adding the following as stated in [your comment](https://github.com/netdata/netdata/issues/1206#issuecomment-258583386) to the slave config has no effect:

```
[plugin:proc:diskspace]
    exclude space metrics on paths = /home/ /net/ /backup/ /public/
```

But this works as expected to exclude all automounted directories:

```
[plugin:proc:diskspace]
    exclude space metrics on paths = /home/* /net/* /backup/* /public/*
```
