### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#1207]
The experimental packages installer failed.

This is what it says:

[root@melete.kr:/home]curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
Cannot find /etc/os-release
Loading /etc/lsb-release ...
Cannot find distribution with /etc/lsb-release
Running command: lsb_release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

We detected these:
Distribution    : CentOS
Version         : 6.6
Codename        : Final
Package Manager : install_yum
Packages Tree   : centos
Detection Method: lsb_release
Default Python v: 2 

ERROR/I don't know how to install autoconf-archive.

**ERROR/I don't know how to install autogen.**

 > Checking if package 'zlib-devel' is installed...
 > Checking if package 'libuuid-devel' is installed...
 > Checking if package 'libmnl-devel' is installed...

ERROR/I don't know how to install nodejs. Check: https://nodejs.org/en/download/package-manager/

 > Checking if package 'PyYAML' is installed...
 > Checking if package 'MySQL-python' is installed...
 > Checking if package 'python-psycopg2' is installed...

```

**Comment by shadycuz** [comment]
@sohwaje Did you install EPEL? http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

**Comment by ktsaou** [comment]
I think you will be able to install netdata, even with these errors.
Actually I updated the installer to report these errors are warnings.
Could you please retry?

**Comment by sohwaje** [comment]
[root@melete.kr:/root]curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
Cannot find /etc/os-release
Loading /etc/lsb-release ...
Cannot find distribution with /etc/lsb-release
Running command: lsb_release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

We detected these:
Distribution    : CentOS
Version         : 6.6
Codename        : Final
Package Manager : install_yum
Packages Tree   : centos
Detection Method: lsb_release
Default Python v: 2 

WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

WARNING
package autogen is not available in this system.
You may try to install without it.

 > Checking if package 'zlib-devel' is installed...
 > Checking if package 'libuuid-devel' is installed...
 > Checking if package 'libmnl-devel' is installed...
 > Checking if package 'PyYAML' is installed...
 > Checking if package 'MySQL-python' is installed...
 > Checking if package 'python-psycopg2' is installed...

All required packages are already installed. Now proceed to the next step.



Is this all right?

**Comment by ktsaou** [comment]
yes, you can proceed to the next step...

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if still need help, please post and I'll re-open it.
