### ISSUE TITLE
starting from unit file or in after.local gives error

### ISSUE THREAD

**Issue by roelandjansen** [firehol/netdata#121]
if I try to start netdata automatically via systemd or via /etc/init.d/after.local,
the web page gives and error

"File '' does not exist, or is not accessible." 
(from webclient.c in the mysendfile function)

If I kill off netdata and manually start, all goes fine.

What I see is that if it fails, ps aux|grep netdata only shows:

/opt/netdata/usr/sbin/netdata   running

but if I manually start, ps aux|grep netdata shows

/opt/netdatausr/sbin/netdata running
/bin/bash /opt/netdata/usr/lib/netdata/plugins/d/tc-qos-helper.sh 1
/bin/bash /opt/netdata/usr/lib/netdata/plugins.d/apps.plugin 1
sleep x
sleep x

so it seems that some subprocesses are not started.
(copy/paste did not work, hopefully not typos here)

Any ideas?

**Comment by ktsaou** [comment]
Wild guess: different permissions?

Currently you have to start netdata as `root`. It will switch to the `netdata` user by itself.

**Comment by roelandjansen** [comment]
wild answer ;-)

* after.local is started at the  boot process and is id root.
 
* the unit file also is not changed at that point, except for the 
path of the executable. (both User and Group entries in the unit file are root)

recap:

 
If I systemctl enable.. and boot up it does not it does not work
if I start by using after.local entry /path/to/binary it does not work

if I systemctl start it works
if I start by /path/to/binary it works

**Comment by roelandjansen** [comment]
add info... 

after some time. the started instance via systemctl died.

Status still showed OK:


roeland-vm:/home/roeland # systemctl status  netdata
netdata.service - netdata
   Loaded: loaded (/etc/systemd/system/netdata.service; disabled)
   Active: active (running) since Mon 2016-04-04 08:42:06 CEST; 1h 13min ago
  Process: 3633 ExecStart=/opt/netdata/usr/sbin/netdata (code=exited, status=0/SUCCESS)
 Main PID: 3635 (netdata)
   CGroup: /system.slice/netdata.service
           └─3635 /opt/netdata/usr/sbin/netdata

Apr 04 08:42:06 roeland-vm systemd[1]: netdata.service: Supervising process 3635 which is not our child. We'll most likely not notice when it exits.

(process 3635 is spawned from the main process and is from user netdata)

roeland-vm:/home/roeland # systemctl stop netdata
roeland-vm:/home/roeland # systemctl start netdata

no reply from systemctl but it does not work. same error as in the first post.

roeland-vm:/home/roeland # systemctl stop netdata
roeland-vm:/home/roeland # ps aux|grep netdata
root       9203  0.0  0.0   9248  1584 pts/1    S+   09:56   0:00 grep --color=auto netdata
roeland-vm:/home/roeland # systemctl start netdata
roeland-vm:/home/roeland # ps aux|grep netdata
netdata    9208  1.7  0.2 391108  6620 ?        SNl  09:56   0:00 /opt/netdata/usr/sbin/netdata
root       9217  0.0  0.0   9248  1584 pts/1    S+   09:56   0:00 grep --color=auto netdata
roeland-vm:/home/roeland # systemctl stop netdata
roeland-vm:/home/roeland # /opt/netdata/usr/sbin/netdata


now it works again (generally the whole day)

**Comment by ktsaou** [comment]
may we close this? Is there something pending?

**Comment by roelandjansen** [comment]
I haven't see a solution yet --  If automatically started -- it fails.

**Comment by ktsaou** [comment]
which distro and version are you using?

**Comment by roelandjansen** [comment]
openSUSE LEAP 42.1 and SLES11/SLES12

**Comment by ktsaou** [comment]
Hm... you are first here I saw with these.
So, I don't know how to help you. The problem you face seems system related...

**Comment by roelandjansen** [comment]
possible. If I coul d get a grip on why the error is thrown, we could go on from that point.

**Comment by ktsaou** [comment]
If you update your netdata, the filename will be shown.
I guess it is `/usr/share/netdata/web/index.html`.

So, it say this file does not exist, or is not accessible. Somehow it cannot access this file. So probably netdata runs as a user that is not allowed to access it.

You can download http://your.netdata.server:19999/netdata.conf to see the `run as user` setting and the `web files owner` setting. These are what netdata thinks should be happening.

Check also `/var/log/netdata/error.log` for errors.

**Comment by roelandjansen** [comment]
I just updated to the latest version (git clone..)

I'll first see if this keeps working. I also opted to have it default installed instead of running from /opt.
I would assume that the netdata.conf should not make any difference because:

o) manual start is by root (and drops privs)
o) started from /etc/init.d/after.local is by root (and drops privs)
o) systemctl start is by root (and drops privs)


Anyways. first let's see if the auto start works with the latest version.

**Comment by roelandjansen** [comment]
ok. restarted the vm and started from within systemd (yeah I know..)

File '/usr/share/netdata/web/' does not exist, or is not accessible.

netdata.service - netdata
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled)
   Active: active (running) since Mon 2016-04-11 10:30:47 CEST; 1min 31s ago
  Process: 2073 ExecStart=/usr/sbin/netdata -pidfile /var/run/netdata.pid (code=exited, status=0/SUCCESS)
 Main PID: 2077 (netdata)
   CGroup: /system.slice/netdata.service
           └─2077 /usr/sbin/netdata -pidfile /var/run/netdata.pid

Apr 11 10:30:47 roeland-vm netdata[2073]: 16-04-11 10:30:47: INFO: netdata: Listening on all IPs (IPv6 and IPv4)

a  service restart does not change.

roeland-vm:/home/roeland # ls -ld /usr/share/netdata/web/
drwxrwxr-x 7 netdata netdata 4096 Apr 11 10:16 /usr/share/netdata/web
roeland-vm:/home/roeland # ls -l /usr/share/netdata/web/
total 436
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 css
-rw-r--r-- 1 netdata netdata   9779 Apr 11 10:16 dashboard.css
-rw-r--r-- 1 netdata netdata  18655 Apr 11 10:16 dashboard.html
-rw-r--r-- 1 netdata netdata 176530 Apr 11 10:16 dashboard.js
-rw-r--r-- 1 netdata netdata  10073 Apr 11 10:16 dashboard.slate.css
-rw-r--r-- 1 netdata netdata   1195 Apr 11 10:16 demo.html
-rw-r--r-- 1 netdata netdata   4987 Apr 11 10:16 demo2.html
-rw-r--r-- 1 netdata netdata  56875 Apr 11 10:16 favicon.ico
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 fonts
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 images
-rw-r--r-- 1 netdata netdata  77810 Apr 11 10:16 index.html
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 lib
-rw-r--r-- 1 netdata netdata  20103 Apr 11 10:16 netdata-swagger.json
-rw-r--r-- 1 netdata netdata  12587 Apr 11 10:16 netdata-swagger.yaml
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 old
-rw-r--r-- 1 netdata netdata     26 Apr 11 10:16 robots.txt
-rw-r--r-- 1 netdata netdata   7628 Apr 11 10:16 tv.html
-rw-r--r-- 1 netdata netdata     41 Apr 11 10:16 version.txt

nd if I now...

roeland-vm:/home/roeland # /usr/sbin/netdata
16-04-11 10:34:18: INFO: netdata: Listening on all IPs (IPv6 and IPv4)

it is working just fine.

and a check on the directories:

roeland-vm:/home/roeland # ls -ld /usr/share/netdata/web/
drwxrwxr-x 7 netdata netdata 4096 Apr 11 10:16 /usr/share/netdata/web/
roeland-vm:/home/roeland # ls -l /usr/share/netdata/web/
total 436
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 css
-rw-r--r-- 1 netdata netdata   9779 Apr 11 10:16 dashboard.css
-rw-r--r-- 1 netdata netdata  18655 Apr 11 10:16 dashboard.html
-rw-r--r-- 1 netdata netdata 176530 Apr 11 10:16 dashboard.js
-rw-r--r-- 1 netdata netdata  10073 Apr 11 10:16 dashboard.slate.css
-rw-r--r-- 1 netdata netdata   1195 Apr 11 10:16 demo.html
-rw-r--r-- 1 netdata netdata   4987 Apr 11 10:16 demo2.html
-rw-r--r-- 1 netdata netdata  56875 Apr 11 10:16 favicon.ico
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 fonts
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 images
-rw-r--r-- 1 netdata netdata  77810 Apr 11 10:16 index.html
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 lib
-rw-r--r-- 1 netdata netdata  20103 Apr 11 10:16 netdata-swagger.json
-rw-r--r-- 1 netdata netdata  12587 Apr 11 10:16 netdata-swagger.yaml
drwxr-x--- 2 netdata netdata   4096 Apr 11 10:16 old
-rw-r--r-- 1 netdata netdata     26 Apr 11 10:16 robots.txt
-rw-r--r-- 1 netdata netdata   7628 Apr 11 10:16 tv.html
-rw-r--r-- 1 netdata netdata     41 Apr 11 10:16 version.txt


looks the same.

**Comment by ktsaou** [comment]
@alonbl @philwhineray any ideas?

**Comment by philwhineray** [comment]
Not really.

Permissions on /usr/share/netdata or (less likely /usr/share) rather than
the web folder?

Otherwise some AppArmor interference?

https://www.suse.com/documentation/sled11/singlehtml/apparmor_quickstart/apparmor_quickstart.html#sec.aaquick.audit

**Comment by roelandjansen** [comment]
no. no apparmor. Unlike selinux, it does not automagically interfere/f* up systems. 
(I did disable it though)

I completely threw out all the snippets and redid a git clone of the release as of today.  20160429.
the installer fails:

chown root /usr/libexec/netdata/plugins.d/apps.plugin
cannot access <above path> No such file or directory.

created the directory by hand, installer runs fine

Now. when the installer starts netdata, the error is the same. So it's even getting worse.

**Comment by ktsaou** [comment]
Can we make a test?

Run the installer like this:

```sh
sudo ./netdata-installer.sh --install /tmp
```

This will install netdata in `/tmp/netdata`. Does it run now?

**Comment by roelandjansen** [comment]
obviously it won't as there are no exec permissions on /tmp.

But hey, I want to help too ;-) so I have remounted it suid,exec,dev

I uninstalled again, removed the snippets left over

It does report the same error at install /tmp/netdata/usr/libexec/plugins.d/apps.plugin no such file or directory. 

Luckily it does not work. Looking at the history above and ps aux|grep netdatea, I do not see 
things like:

/.....path...../netdata/plugins/d/tc-qos-helper.sh 1
/.....path...../netdata/plugins.d/apps.plugin 1

have you tried a clean install?

**Comment by trieuvutrung** [comment]
@roelandjansen:
look same me. 
`[root@localhost netdata]# ls -la /usr/share | grep netdata
drwx------    3 root root  4096 14:24  9 Th05 netdata
`
`chmod 755 /usr/share/netdata/`
it work for me.

**Comment by ktsaou** [comment]
The installer leaves `/usr/share/netdata/` with permissions 700 on your systems?

**Comment by trieuvutrung** [comment]
yes. after i install, /usr/share/netdata/ permission is 700.

**Comment by roelandjansen** [comment]
I'll check that when back home. The work-laptop is not at hand where I do the VM pretesting..

**Comment by ktsaou** [comment]
The installer prints the commands it runs on the console. Mine prints these:

```
:-----------------------------------------------------------------------------
Running command:

chown -R netdata:netdata /usr/share/netdata/web


:-----------------------------------------------------------------------------
Running command:

chmod 0755 /usr/share/netdata/web

```

What your installer prints?

**Comment by ktsaou** [comment]
ok, it fixes the directory `/web` but not the parent.

**Comment by ktsaou** [comment]
I merged #396 to prevent this from happening in the future. However, all of you that have already installed it you will have to run this by hand:

```sh
chmod 755 /usr/share/netdata
```

**Comment by roelandjansen** [comment]
after uninstalling and a git pull it seems to work, manually.

Next is to see if it can be brought up automatically.

**Comment by roelandjansen** [comment]
the systemd service file now seems to be able to start it as well
