### ISSUE TITLE
zero-based fping latency chart

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1213]
Non zero based old style much better imo
![old](https://cloud.githubusercontent.com/assets/22274335/20031074/6373928c-a3b5-11e6-9850-2def2fc36cda.png)
vs
![new](https://cloud.githubusercontent.com/assets/22274335/20031075/678ac386-a3b5-11e6-82ef-cb7d4cf6fa4e.png)

**Comment by ktsaou** [comment]
you are right, I found that too. I'll revert it back.

**Comment by l2isbad** [comment]
ok thx!
