### ISSUE TITLE
Integration for home assistant

### ISSUE THREAD

**Issue by ezar** [firehol/netdata#1215]
I want to start a home assistant integration for netdata, but I don't know, how can access to current value for a tag? Can you help me?

**Comment by ktsaou** [comment]
So, you just need to get the latest value of a metric/dimension of a chart?

This is how:

`http://your.netdata/api/v1/data?chart=CHARTID&before=0&after=-1&format=csv&options=seconds`

Check the [API](https://github.com/firehol/netdata/wiki/REST-API-v1). netdata can produce aggregated data, in different formats. The one above responds with a CSV.

**Comment by shadycuz** [comment]
@ezar Is this so you can use the google or amazon home devices to check on Netdata by asking it? Like "Okay google, does Netdata have any alarms?"

**Comment by ezar** [comment]
Can we access to alarms from api?

**Comment by ktsaou** [comment]
Here is what we have:

- `http://box:19999/api/v1/alarms?all` returns all the running alarms.
- `http://box:19999/api/v1/alarms` returns all the raised alarms.
- `http://box:19999/api/v1/alarm_log` returns all the events of the alarm log.
- `http://box:19999/api/v1/alarm_log?after=UNIQUEID` returns all the events of the alarm log, that occurred after UNIQUEID (so you can poll it, and remember the last UNIQUEID of what is returned, which you give it back to get incrementally the events, etc).
- `http://box:19999/api/v1/badge.svg?alarm=NAME` returns an SVG (XML) if the given alarm NAME.

**Comment by ezar** [comment]
Wow!!!

**Comment by ktsaou** [comment]
ok, I am closing this. Post if you have any other questions.
