### ISSUE TITLE
SCTP Information

### ISSUE THREAD

**Issue by RiseEarly** [firehol/netdata#1218]
I would like to know if it is possible to get sctp connectivity details in netdata, just like TCP.
The number of SCTP Associations that are active,
SCTP Read/Write Queues
SCTP Errors
SCTP Handshake details, etc.

**Comment by ktsaou** [comment]
Is it any of them: https://github.com/firehol/netdata/blob/3a3ab4b5ebdab08aad08c24f53f50894702749cb/src/proc_net_netstat.c#L225-L352

If not, can you find the source of this information?

**Comment by RiseEarly** [comment]
No, SCTP is a protocol similar to TCP. So we would like to show stats, just like TCP.
IS it possible to write a plugin for the same, using nodejs snmp module [as there is a SNMP MIB for the same : SCTP-MIB.txt] and then transferring the output to netdata for visualisations ?? Is there any documentation that you can point to, if this is a feasible solution.

**Comment by ktsaou** [comment]
I guess you mean this:

```sh
# cat /proc/net/sctp/snmp 
SctpCurrEstab                   	0
SctpActiveEstabs                	0
SctpPassiveEstabs               	0
SctpAborteds                    	0
SctpShutdowns                   	0
SctpOutOfBlues                  	0
SctpChecksumErrors              	0
SctpOutCtrlChunks               	0
SctpOutOrderChunks              	0
SctpOutUnorderChunks            	0
SctpInCtrlChunks                	0
SctpInOrderChunks               	0
SctpInUnorderChunks             	0
SctpFragUsrMsgs                 	0
SctpReasmUsrMsgs                	0
SctpOutSCTPPacks                	0
SctpInSCTPPacks                 	0
SctpT1InitExpireds              	0
SctpT1CookieExpireds            	0
SctpT2ShutdownExpireds          	0
SctpT3RtxExpireds               	0
SctpT4RtoExpireds               	0
SctpT5ShutdownGuardExpireds     	0
SctpDelaySackExpireds           	0
SctpAutocloseExpireds           	0
SctpT3Retransmits               	0
SctpPmtudRetransmits            	0
SctpFastRetransmits             	0
SctpInPktSoftirq                	0
SctpInPktBacklog                	0
SctpInPktDiscards               	0
SctpInDataChunkDiscards         	0
```

I can write a plugin for these, but I need you to answer these:

1. Can you group them to charts? Give a chart name and put any of the above as dimensions to it.
2. How can I use sctp? Is there an application that uses such sockets, so that I can test the reported values?

**Comment by RiseEarly** [comment]
yes, this is exactly what we need. Thanks for your help.

1. Charts similar in nature to TCP like : Number of SCTP Connections [SctpCurrEstab], SCTP Errors [SctpChecksumErrors], Number of times SCTP Connectivity is aborted [sctpAborteds], etc.
2. SCTP is primarily used in Telecom for transmitting signaling information, so there are no applications that is out there like HTTP/telnet for TCP. So testing can be done only with sample client server programming.

**Comment by ktsaou** [comment]
Done in #3705 
I cannot test it. Could you please give it a run?
