### ISSUE TITLE
monitoring everything

### ISSUE THREAD

**Issue by sirajkrm** [firehol/netdata#1220]
hi
i'm a network and system administrator
i saw this project " netdata "
to be honest best monitoring tool ever
great design
great performance
great capabilities 
& great work !
i would like to suggest.. if is it possible
to make this software monitor everything in infrastructure
systems, servers, switchs, routers, hosts etc...
that would be the greatest monitoring software ever
i hope that would be in considération  :)
P.S. 
if this work would be done as the suggestion - Entreprise Edition
i, personnaly will pay for it !
but please.. keep it open source
big thank's

**Comment by sirajkrm** [comment]
hi thank you so very much for your response.. :)
ok i'll take a look at the link you gave me, appreciate it.
but i really encourage you to do so about writing data collection for windows (it widely used by users) and other Linux Dists.. for one simple reason : it would make the software improved more open to systems and other devices.. think of that ^^

it's true.. netdata is at its very early stages but what i'm giving you is suggestion that system, security & network administrator love to find.
i ain't an expert in programming language or design etc...
but i can support you as i mentioned  in the first comment.

best of luck :)
thank's.

**Comment by ktsaou** [comment]
Thanks! You are right. This is why I have left all such requests hanging at the issue tracker.
Time will come...

**Comment by sirajkrm** [comment]
hi Mr. Costa
can we talk over chat ?!
facebook, twitter, linkedin...
something i need to tell you :)

**Comment by ktsaou** [comment]
btw, netdata runs on FreeBSDs and MacOS X now (although with limited charts yet).

I am cleaning up the issue tracker, so I'll close this.
Nice you like my work! Sure, I am considering alternatives to have netdata grow faster...
