### ISSUE TITLE
 registry hostname not reflecting in the registry web browser

### ISSUE THREAD

**Issue by divgwd** [firehol/netdata#1224]
Hi,
I have set up a registry for three servers ,one of the servers connecting to registry server has the below config   
registry hostname = PROCServer_1 in my /etc/netdata/netdata.conf file but when i check under the my-netdata menu in the registry's web browser it takes the hostname of the server and not the registry hostname mentioned in the /etc/netdata/netdata.conf.Is there something I am  doing wrong ??
Thanks in advance.

**Comment by ktsaou** [comment]
Well, I just did it and it works.
After you do this change, you have to visit this server once. After that point the server will appear with its new name.

Can you try it?

**Comment by divgwd** [comment]
I did and it worked.
 Thank you :)

**Comment by ktsaou** [comment]
nice!
