### ISSUE TITLE
netdata fails to detect the system going into sleep/hibernate

### ISSUE THREAD

**Issue by haasn** [firehol/netdata#1225]
On a desktop system, sleep and hibernate are very normal activities and shouldn't be considered error states by netdata. However, netdata seems to consider it as the system being unresponsive:

```
Nov 08 18:13:00 foo-desktop systemd[1]: Reached target Sleep.
Nov 08 18:13:00 foo-desktop systemd[1]: Starting Suspend...
Nov 08 18:13:00 foo-desktop systemd-sleep[14158]: Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory
Nov 08 18:13:00 foo-desktop systemd-sleep[14160]: /lib/systemd/system-sleep/wpasupplicant failed with error code 255.
Nov 08 18:13:00 foo-desktop systemd-sleep[14158]: Suspending system...
....
Nov 08 20:04:41 foo-desktop kernel: ACPI: Low-level resume complete
Nov 08 20:04:41 foo-desktop kernel: ACPI: Waking up from system sleep state S3
Nov 08 20:04:41 foo-desktop kernel: PM: Finishing wakeup.
Nov 08 20:04:41 foo-desktop systemd[1]: Time has been changed
...
Nov 08 20:04:51 foo-desktop msmtp[14378]: host=mail.example.org tls=on auth=off from=netdata@example.org recipients=root mailsize=8035 smtpstatus=250 smtpmsg='250 2.0.0 Ok: queued 
```
(Omitted are about 10 more emails sent by netdata)

The emails it sends are of the form
```
   foo-desktop is critical

   disk_space.dm-1 Chart
   disk space last collected secs = 6701 seconds ago
   number of seconds since the last successful data collection of the
   mount point Alarm
   / Family
   CRITICAL Severity
   Di 8. Nov 20:04:41 CET 2016 Time
   [1]View Netdata
   The source of this alarm is line 5@/etc/netdata/health.d/disks.conf
       	Sent by [2]netdata, the real-time performance monitoring.
```

The 6701 seconds it thinks the disk was unresponsive for approximately matches the ~2 hours the system was actually suspended for.

**Comment by haasn** [comment]
Note that this can be avoided by using `clock_gettime` instead of `gettimeofday` to measure time and using a clock other than `CLOCK_REALTIME`.

For example, netdata could use `CLOCK_MONOTONIC`, which does not count time the system spent suspended.

**Comment by ktsaou** [comment]
hm... it is not that simple... if we ignore sleep time, the time at the charts will be wrong after resume.
I think we need to find a way to detect the system came up from sleep and suspend the alarms for a few seconds...

**Comment by haasn** [comment]
You could probably compare the `MONOTONIC` time delta against the `REALTIME` delta to detect a hibernation event.

Also, it might ultimately be a better idea to use `MONOTONIC` time internally (inside the rdd database), together with an extra log of monotonic time vs realtime (so the monotonic time can be mapped to a real time for visual display).

**Comment by ktsaou** [comment]
netdata was incorrectly using BOOTTIME to detect hibernation. With PR #2577 it uses MONOTONIC, so that wake up from hibernation is properly detected and no false alarms are sent.

**Comment by ktsaou** [comment]
merged the fix
