### ISSUE TITLE
Separate web UI template

### ISSUE THREAD

**Issue by hryamzik** [firehol/netdata#123]
Is it possible to use web ui with a different data source? In fact I would like to connect this brilliant interface to [prometheus templates](https://prometheus.io/docs/visualization/template_examples/).

**Comment by ktsaou** [comment]
Haha...

I am afraid it is not that easy. The netdata server has a special API to drive the dashboard.
Also, the netdata server responds in 1-2 milliseconds for most chart refreshes to give you this snappy feeling.

So, if you just get the same dashboard and try to pull data from another server (even if it was compatible), I am afraid it will not be the same...

**Comment by ktsaou** [comment]
I am closing this. Of course PRs are welcome if someone is willing to make the dashboard compatible with another backend.
