### ISSUE TITLE
Swap alerts probably misleading

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1235]
Currently one of the swap alerts is defined like this by default:

```
   alarm: used_swap_space
      on: system.swap
    calc: $used * 100 / ( $system.ram.used + $system.ram.cached + $system.ram.free )
   units: % of RAM
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (15) : (20))
    crit: $this > (($status == $CRITICAL) ? (40) : (50))
   delay: up 0 down 15m multiplier 1.5 max 1h
    info: the swap memory used, as a percentage of the system RAM
      to: sysadmin
```

So, this is going to be critical only when used swap is above 40% of the system RAM. Well, that may never trigger if you had a scenario like this:

System RAM: 2GB
SWAP size: 512MB

So, as soon as SWAP is going to be full utilized we are about to use 25% of the system RAM which just about triggers a warning. But the fact that the available swap is used 100% can potentially cause a big problem.

Conclusion: I'm not sure if the above alert is really required, maybe it is. But I think we should also have an alert that triggers, when x% of the available SWAP is going to be used for a period longer than y.

**Comment by ktsaou** [comment]
hm... you are right. I thought that the rule of thumb is that swap should be twice the ram.
I'll fix it to take into account both.

**Comment by ktsaou** [comment]
added it

**Comment by ktsaou** [comment]
merged it
