### ISSUE TITLE
Enhancement to the MySQL plugin to monitor replication status

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1240]
If we also collected

- Slave_SQL_Running
- Slave_IO_Running
- Seconds_Behind_Master

from either `GLOBAL STATUS` or explicitly from `SLAVE STATUS` we could then monitor

- if replcation is still running
- how far behind the master the replication actually is

Rather than proposing a new plugin I wonder if that could be added to the existing one.

**Comment by l2isbad** [comment]
How this should work?
Slave_SQL_Running, Slave_IO_Running  - strings.
Seconds_Behind_Master - integer.
What new charts are we need to monitor
```
if replcation is still running
how far behind the master the replication actually is
```
Seconds_Behind_Master is easy one since value is int
What about Slave_SQL_Running, Slave_IO_Running?

**Comment by jurgenhaas** [comment]
Slave_SQL_Running and Slave_IO_Running are either "Yes" or "No" and if one of them is "No" while `SHOW SLAVE STATUS` is returning something and Master_Host has a value, that should trigger an alert. And the charts should just be a flag indicating if it's running or not.

With regard to the seconds behind master, I don't have enough experience to answer that question. In my own fairly small configuration the slaves are usually behind only for a few seconds but I can't tell what would be acceptable for larger environments.

**Comment by l2isbad** [comment]
Ok so if node is slave we need to more charts (family Slave)
1. Seconds_Behind_Maste
2. Slave_SQL_Running, Slave_IO_Running. If "Yes" value should be 1, if not 'Yes' value should be -1
Am i right? 
What else?

**Comment by jurgenhaas** [comment]
Sounds good to me.

**Comment by l2isbad** [comment]
I did it.
Can you test? 
https://github.com/l2isbad/netdata/blob/mysql_chart_add_slave_stats/python.d/mysql.chart.py

if its ok i will make a pr

**Comment by jurgenhaas** [comment]
This is great! Thanks you @l2isbad 

Your link above isn't working though, but I've used the patch from https://github.com/l2isbad/netdata/commit/697d5608ef4f1171abf3a5503db9640386775556.patch and that does exactly what I'm looking for.

I guess there is no alarm configured by that, right?

**Comment by l2isbad** [comment]
My bad, i replace the old branch with new.

**Comment by l2isbad** [comment]
To be honest i dont know what alarms we need.

**Comment by jurgenhaas** [comment]
Well, at least an alarm that gets triggered when the chart "Slave Status" is zero.

**Comment by l2isbad** [comment]
Also 
https://github.com/firehol/netdata/issues/1454

Slave Status only values   1/-1
1 = Yes
2 != Yes

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1470

**Comment by l2isbad** [comment]
> Well, at least an alarm that gets triggered when the chart "Slave Status" is zero or -1.

post to https://github.com/firehol/netdata/issues/1454 pls

**Comment by ktsaou** [comment]
merged! thank you @l2isbad !
