### ISSUE TITLE
API no data

### ISSUE THREAD

**Issue by ezar** [firehol/netdata#1241]
No data when I ask: api/v1/data?chart=system.load&before=0&after=-1
What is the problem?

**Comment by ktsaou** [comment]
system.load is updated every 5 seconds - the linux kernel calculates like that.
Use this: http://registry.my-netdata.io/api/v1/data?chart=system.load&before=0&after=-5

**Comment by ktsaou** [comment]
Keep in mind you can find the `update every` of each chart, by examining it: http://registry.my-netdata.io/api/v1/chart?chart=system.load

**Comment by ezar** [comment]
Thanks! It works!
Why can you add a new API to access to current value? Will be wonderful.

**Comment by ktsaou** [comment]
ok, fixed that.
Giving `after=-1` will return a point even if the chart's update frequency is above 1.
Thanks for asking for it!

**Comment by ezar** [comment]
Works perfect. You're the best!
Regards,
