### ISSUE TITLE
Invalid JSON from /api/v1/charts

### ISSUE THREAD

**Issue by soruly** [firehol/netdata#1244]
I've got an alert error `Error 405: Cannot download charts index from server`

When I parse the raw JSON I found that "title" contains an escape `\` that makes the JSON failed to parse
```
		"disk_inodes._mnt_snowy_music_lossless": {
			"id": "disk_inodes._mnt_snowy_music_lossless",
			"name": "disk_inodes._mnt_snowy_music_lossless",
			"type": "disk_inodes",
			"family": "/mnt/snowy/Music Lossless",
			"context": "disk.inodes",
			"title": "Disk Files (inodes) Usage for /mnt/snowy/Music Lossless [//192.168.1.100/Music\040Lossless] (disk_inodes._mnt_snowy_music_lossless)",
			"priority": 2024,
			"enabled": true,
			"units": "Inodes",
			"data_url": "/api/v1/data?chart=disk_inodes._mnt_snowy_music_lossless",
			"chart_type": "stacked",
			"duration": 3600,
			"first_entry": 1479094710,
			"last_entry": 1479095174,
			"update_every": 1,
			"dimensions": {
				"avail": {
					"name": "avail"
				},
				"used": {
					"name": "used"
				},
				"reserved_for_root": {
					"name": "reserved for root"
				}
			},
			"green": null,
			"red": null
		},
```
After correcting the path in my `/etc/fstab`, it's working again.
The problem is this line in my fstab:
`/mnt/snowy/Music\040Lossless /home/public/Music\040Lossless none bind`
The `\040` is for making a space when mounting drives. (as suggested in http://stackoverflow.com/questions/15316017/how-do-i-specify-a-label-path-with-spaces-in-etc-fstab)

I wonder if you'd like to handle this character escape?

**Comment by ktsaou** [comment]
> I wonder if you'd like to handle this character escape?

yes I do. I marked this as bug, to fix it asap.

**Comment by ktsaou** [comment]
hm... I see the fix is already in place.

Could you please post your `/proc/self/mountinfo`? I think this octal number appears also in another field, apart the mount point.

**Comment by soruly** [comment]
```

**Comment by ktsaou** [comment]
fixed it. will merge once travis completes.
Thanks for reporting it.

**Comment by ktsaou** [comment]
merged it.
