### ISSUE TITLE
Digital Ocean droplet

### ISSUE THREAD

**Issue by bitbreakr** [firehol/netdata#125]
Hi,

I does not work on created vps from digital ocean...
It gets installed successfuly but when I want to run it:

/usr/sbin/netdata: No such file or directory

Thanks

**Comment by ktsaou** [comment]
can you re-install it and post the output of the installer?

**Comment by akalajzi** [comment]
Tried it on DigitalOcean Ubuntu14.04, and definitely works.

**Comment by Jacob-SAE** [comment]
I installed this Saturday night on DigitalOcean with Ubuntu14.04 without issue.

@bitbreakr: Could you provide more information regarding the OS you were using at the time?

**Comment by ktsaou** [comment]
Hi the demo sites also run on digital ocean (the have donated VMs).
I close this. If you have any issues, please open it again.
