### ISSUE TITLE
Possible to hide / show certain tabs in Netdata dashboard?

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#1250]
is its possible to make netdata not show an certain section of stats, for example i want to hide the Users tab so people seeing live stats will not see who is using the server. iam using netdata as an stat / specs publicly to give customers an preview. 

thanks

**Comment by ktsaou** [comment]
I just added 2 options to apps.plugin to allow you disable users and/or groups charts.
To set them, edit `/etc/netdata/netdata.conf` and set:

```
[plugin:apps]
	update every = 1
	command options = no-users no-groups
```

If this section is not found on your netdata.conf, download a fresh copy of this file from `http://your.netdata.ip:19999/netdata.conf`.

- `no-users` disables the users charts
- `no-groups` disables the user groups charts

It is now in PR #1251
Will be merged in a while...

**Comment by Dedsec1** [comment]
Thanks for the fast reply, also where could i find the html code for the my-netdata.io website?

**Comment by ktsaou** [comment]
> where could i find the html code for the my-netdata.io website?

http://your.netdata.ip:19999/demosites.html

**Comment by ktsaou** [comment]
merged it.
