### ISSUE TITLE
setting up System Overview chart on custom demosites.html page?

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#1253]
so i got an custom demosites.html page setup on my server but wanted to see if i could get the system overview chart to be replaced with the default one found in the demosites.html file, i didnt see an plugin for it but i did find the html code in the default.html file but iam not sure if it would work well with my custom demo sites page.

**Comment by ktsaou** [comment]
this is the code that generates the system overview: https://github.com/firehol/netdata/blob/2ba7db38468400e1b1e8365e30ee8f3b776b9215/web/index.html#L1115-L1227

**Comment by Dedsec1** [comment]
cool thanks, so if  i wanted to put in the system overview info on the demosites html file i would just use the same info for each chart or would it just work with copying.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, please post and I'll re-open it.
