### ISSUE TITLE
Diskspace Usage full while it is not

### ISSUE THREAD

**Issue by sevaho** [firehol/netdata#1255]
hello,

So I'm guessing this is a bug, 'df -h' shows that device .mmcblk0p2 is not full while netdata says its completely full. How can I fix this?

fdisk -l output:

/dev/mmcblk0p2      137216 61415423 61278208 29.2G 83 Linux

mount output:

/dev/mmcblk0p2 on / type ext4 (rw,noatime,data=ordered)

fstab output:

/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1

Greetings

![screenshot from 2016-11-16 13-56-28](https://cloud.githubusercontent.com/assets/10941956/20348568/652e0478-ac06-11e6-9516-7873c4ffaac5.png)

![screenshot from 2016-11-16 13-56-46](https://cloud.githubusercontent.com/assets/10941956/20348576/6e4f8c70-ac06-11e6-9eb1-34a970862b11.png)

![screenshot from 2016-11-16 13-57-03](https://cloud.githubusercontent.com/assets/10941956/20348580/7184317a-ac06-11e6-88a2-c89b5dfc3a0c.png)

**Comment by ktsaou** [comment]
This is very strange. I checked the code again - it is actually a variation of the code found in `coreutils`.
I can't spot the cause of this...

Could you please run this for me?

1. create this file as `statvfs.c`:

  ```c
#include <stdio.h>
#include <sys/statvfs.h>

int main(int argc, char **argv) {
    const char *mount_point = "/", *disk = "undefined";

    struct statvfs buff_statvfs;
    if (statvfs(mount_point, &buff_statvfs) < 0) {
        fprintf(stderr, "Failed statvfs() for '%s' (disk '%s')", mount_point, disk);
        return 1;
    }

    printf("'%s': STATVFS: "
    	"f_frsize=%llu "
    	"f_bsize=%llu "
    	"f_bavail=%llu "
    	"f_blocks=%llu "
    	"f_bfree=%llu "
    	"\n"
    	, mount_point
    	, (unsigned long long)buff_statvfs.f_frsize
    	, (unsigned long long)buff_statvfs.f_bsize
    	, (unsigned long long)buff_statvfs.f_bavail
    	, (unsigned long long)buff_statvfs.f_blocks
    	, (unsigned long long)buff_statvfs.f_bfree
    	);

    // taken from get_fs_usage() found in coreutils
    unsigned long bsize = (buff_statvfs.f_frsize) ? buff_statvfs.f_frsize : buff_statvfs.f_bsize;

    fsblkcnt_t bavail         = buff_statvfs.f_bavail;
    fsblkcnt_t btotal         = buff_statvfs.f_blocks;
    fsblkcnt_t bavail_root    = buff_statvfs.f_bfree;
    fsblkcnt_t breserved_root = bavail_root - bavail;
    fsblkcnt_t bused;
    if(btotal >= bavail_root)
        bused = btotal - bavail_root;
    else
        bused = bavail_root - btotal;

    printf("'%s': BYTES  avail=%llu, used=%llu, reserved_for_root=%llu\n", mount_point, (unsigned long long)bavail, (unsigned long long)bused, (unsigned long long)breserved_root);

    return 0;
}
```

2. compile it with: `gcc -o statvfs statvfs.c`

3. run it and post the output please

Thanks!

**Comment by sevaho** [comment]
Thank you for your reply, here is the output:

`
'/': STATVFS: f_frsize=4096 f_bsize=4096 f_bavail=3974489 f_blocks=7525189 f_bfree=4293851
'/': BYTES  avail=3974489, used=3231338, reserved_for_root=319362
`

**Comment by ktsaou** [comment]
ok thanks. Let's see:

netdata puts `bsize` (i.e. `f_frsize` in your case) as the multiplier of the chart and `1024 * 1024 * 1024` as the divider (https://github.com/ktsaou/netdata/blob/a19ead105eeedcf7b01ec14a892d2e799e4dcba6/src/proc_diskstats.c#L243-L245) :

So,

avail = 3974489 * 4096 / (1024 * 1024 * 1024) = 15.16GB
used = 3231338 * 4096 / (1024 * 1024 * 1024) = 12.33GB
reserved_for_root = 319362 * 4096 / (1024 * 1024 * 1024) = 1.22GB

hm... the charts do not match...

Are you sure you are using the latest version of netdata? 

Let me check. The latest version of netdata should reports such charts as:

![screenshot from 2016-11-21 15-50-53](https://cloud.githubusercontent.com/assets/2662304/20485005/692b4112-b002-11e6-8750-8411648d1ca2.png)

check the chart name. It is `disk_space._` (`_` is escaped from `/`). So, I think you are not using the latest version of netdata.

**Comment by sevaho** [comment]
Thank you very much for your help, you were right I just needed to update.
