### ISSUE TITLE
Can't use after installation: Received request is too big.

### ISSUE THREAD

**Issue by jeanpaulrh** [firehol/netdata#126]
I installed Netdata and launched it.
If I try to connect to port 19999 I get this error:

`Received request is too big.`

I enabled debug and in access log I get this:

`16-04-01 19:41:49: 1: 10.8.0.18 port 47651 connected on thread task id 1134

16-04-01 19:41:49: 1: 10.8.0.18 port 47651 disconnected from thread task id 1134

16-04-01 19:41:49: 1: (sent/all = 30/30 bytes -0%, prep/sent/total = 1459532563742.72/0.11/1459532563742.72 ms) data: 400 'too big request'`

**Comment by ktsaou** [comment]
Hi,

I just increased the request size from 8K to 16K. Also, the error message will also log the request size it received.

Please `git pull` and install it again.

If the problem remains, please post:

1. Your browser
2. The URL you are accessing your netdata (I am trying to figure out of you are using a domain that may have a significant size of cookies)
3. If you can navigate to http://netdata.firehol.org, without problems

In either case, please report success or failure.

**Comment by jeanpaulrh** [comment]
It works for me now. Thanks!
