### ISSUE TITLE
Proxmox install failure

### ISSUE THREAD

**Issue by denningsrogue** [firehol/netdata#1261]
I've just tried to install netdata to my new Proxmox 4.3 host based on Debian 8 Jessie.  The install fails with this error:

make -j8
./netdata-installer.sh: line 389: make: command not found

What dependency am I missing?  Not a programmer and new to linux.  I'm guessing this is Java related.

Any help appreciated.

**Comment by ktsaou** [comment]
run `apt-get install make` and run the installer again.
Did you use the script that installs all dependencies?

**Comment by denningsrogue** [comment]
Thanks.  That worked.  I did use the script that installs all the dependencies.  What exactly is “make”.  I assumed wrongly that “make” was a command for the compiler so I checked to see if gcc was installed and it was. 

Thanks again for your help.

-- 
Richard Peters
richardpeters@me.com
