### ISSUE TITLE
Python - Float to Int

### ISSUE THREAD

**Issue by MajorTom6** [firehol/netdata#1262]
Hi,

I am having a problem returning floating point numbers using python.d/example.chart.py.
This is shown specifically at line 30:  
```
def update(self, interval):
        self.begin("example.python_random", interval)
        data = getFloat()
        self.set("dimension", data)
        self.end()
        self.commit()
        return True
```
I was monitoring this value using /plugins.d/python.d.plugin and noticed it was changing the values from the SimpleService class; so I edited line 303 of /python.d/python_modules/base.py

from 
`value = str(int(value))`
to
`value = str(float(value))`

Which corrected the error at that level, but at the dashboard level I am still only getting integers!

Thanks for any input you can give.

\- Tom

**Comment by ktsaou** [comment]
You are right. The current netdata API supports only integers, so multiply your float number by 100 or 1000 and set the divider of the dimension to the same number.

This is how to set multiplier and dividers in python: https://github.com/firehol/netdata/blob/4b5f021453cd3220c4d4c2507d4cee1a8c88804b/python.d/mysql.chart.py#L65 the first number (-8) is the multiplier, and the second (1024) is the divider.

**Comment by MajorTom6** [comment]
Would it not give the same result when multiplying and dividing by the same number?
I tried this and I believe it does (but maybe with correct rounding), is this expected?
I apologize if the question seems ignorant.

Thanks for the help and great software.
-Tom

**Comment by ktsaou** [comment]
ok nice!
