### ISSUE TITLE
create a web app including netdata

### ISSUE THREAD

**Issue by buweilv** [firehol/netdata#1265]
today, I found netdata in github, its scalability attracts me. So I want to integrate netdata in my web app. However my app only has small part of function is monitoring the servers performance. So How to use the netdata's daemon to collect some info such as CPU, Network, I/O ... and the web charts in my own app?

**Comment by ktsaou** [comment]
Hi,

1. If you need to add data to netdata (i.e. send your app metrics to it), you need to write a netdata plugin. The plugin will be responsible for collecting the raw data that will be used later to build charts. Netdata supports all programing languages (bash, python, node.js, - anything can be a netdata plugin). Check: https://github.com/firehol/netdata/wiki/External-Plugins

2. If you need to embed netdata charts on your app (i.e. show data collected by netdata on interactive charts on your web app), you need to include a javascript file and setup a `<div>` for each chart. Netdata will automatically refresh it and make it interactive. Check `http://your.netdata.ip:19999/tv.html` for a demo. There are also a few more `.html` files in the web directory. Check these too - they are static HTML files that netdata turns them to interactive dashboards.

**Comment by ktsaou** [comment]
I am closing this.
If you need help, just post.
