### ISSUE TITLE
about to tidy up a bit..

### ISSUE THREAD

**Issue by cbricart** [firehol/netdata#127]
I'm currently looking at the various scripts in (mostly but not limited to) `charts.d/`, and I think we could spare a few CPU cycles and context switches there - especially, when those contained parts called in some loop.. Additionally, I would reduce the external toolset needed.

Before I'll send a pull request with my changes, I wanted to clarify a few things:
* There are Shell-Scripts that simply have `#!/bin/sh` but are (heavily) using »BASHisms«..
* ..others explicitly calling for `#!/bin/bash` while actually they don't really need it..
* `curl` **is** listed as a dependency - but `wget` is also used
* there seems to be a many implicit assumptions for a variety of tools to be _that is installed everywhere, isn't it..?_, like `sed`, `grep`, `tr`, `awk`, `bc`, `head`, `tail` .. 

So **is** there a _basic-must-have-toolset_ you have in mind..? Or even like: »Yes, we expect the system has actually to have BASH installed, and every tool we call by it's name we surely assume it's the GNU-implementation..

**EDIT:** Ok - I think I've found the »wanted basic set« within the check in `plugins.d/charts.d.plugin`..
(maybe the wiki should be also updated .. i.e. there are some occasions where something like »proud to have no external dependencies at all« is written ..

**Comment by ktsaou** [comment]
Initially, I wrote most shell plugins to work with plain `sh`. Then I found that some systems had different shells, under which even the most basic things could not be done.

I decided then to force `bash` and started using bashism. This force is only needed in `charts.d.plugin`. All others are sourced into it, so it does not matter what shebang they have.

Generally I try not to assume anything. This is why `require_cmd()` is there.

Regarding `wget`, it is only needed in 2 charts.d.plugin that can only work as an example for building your own. They are both for private apps, not available to anyone else, but me. Anyway a graceful check for `wget` was missing in one of them and I just added it.

Regarding the "zero dependencies", let's do a test: delete all plugin dirs and start netdata.
What you get?
A fully functional monitoring for your system.

Of course, if you need to monitor mysql, you need to have mysql. In other cases, netdata issues a few "abnormal" dependencies: if you need to monitor SNMP or `named` you need node.js.

I consider all these add-ons, plugins and these plugins do have dependencies. I never implied netdata is able to monitor everything imaginable without any dependency. I only said it can work without dependencies. And this is true (please test it).

**Comment by ktsaou** [comment]
I see there is a PR that fixes `/bin/bash`: https://github.com/firehol/netdata/pull/132/commits/f1440fe19584a3a9d5e329fcbee5ba4af4fe1c64

**Comment by ktsaou** [comment]
Is there something pending on this?

**Comment by paulfantom** [comment]
Close?

**Comment by ktsaou** [comment]
I have already converted all shell shebangs to `/usr/bin/env bash`.

**Comment by paulfantom** [comment]
Closing.
