### ISSUE TITLE
"server mysql accept src 198.x.x.x." not working, host/network not found

### ISSUE THREAD

**Issue by Eloque** [firehol/netdata#1270]
As it says, if I have the `server mysql accept src 198.x.x.x `statement in my configuration, Firehol will report an error.

I believe my syntax is in order, and the error says host/network not found. I can only guess at the cause, do I need an interface for this specific IP? I don't want to rely on MySQL to allow/disallow IP's but do it at the firewall level.

I am on Git master, 
```
FireHOL 3.0.2_master
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
iptables v1.6.0
```

The error says this, InetZiggo is the internet facing interface with a public IP; 

```
--------------------------------------------------------------------------------
ERROR   : # 1.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : 163@/etc/firehol/firehol.conf: server:
COMMAND : /sbin/ip6tables -t filter -A in_InetZiggo -p tcp -s 192.x.x.x --sport 1024:65535 --dport 3306 -m conntrack --ctstate NEW\,ESTABLISHED -j ACCEPT
OUTPUT  :

ip6tables v1.6.0: host/network '192.x.x.x ' not found
Try 'ip6tables -h' or 'ip6tables --help' for more information.

--------------------------------------------------------------------------------
ERROR   : # 2.
WHAT    : A runtime command failed to execute (returned error 2).
SOURCE  : 163@/etc/firehol/firehol.conf: server:
COMMAND : /sbin/ip6tables -t filter -A out_InetZiggo -p tcp --sport 3306 -d 192.x.x.x --dport 1024:65535 -m conntrack --ctstate ESTABLISHED -j ACCEPT
OUTPUT  :

ip6tables v1.6.0: host/network '192.x.x.x' not found
Try 'ip6tables -h' or 'ip6tables --help' for more information.
```

**Comment by ktsaou** [comment]
Hi.

ok. Wrong repo though. You should use the firehol/firehol repo.

The issue is that you are trying to use IPv4 address on IPv6.

So, either use `server4` or `interface4` or disable IPv6 completely  at you firehol.conf.

**Comment by Eloque** [comment]
I am sorry. Didn't notice that I wasn't in the right repo. Thank you, server4 did the trick.

**Comment by ktsaou** [comment]
nice.
