### ISSUE TITLE
Monitor open files descriptors

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#1272]
Hi,

A useful graph to monitor is the open files descriptors in a OS.

This can be monitor through the /proc/ filesystem using `/proc/sys/fs/file-nr` variable that have the following info:

> 1440    0       65535

Being, 1440 the number of currently used file handles, 0 the number of currently unused file handles and 65535 the maximum file handles that can be allocated.

It is really easy to parse those values just splitting the spaces:

> cat /proc/sys/fs/file-nr | awk -F ' ' '{ printf "%d %d %d",$1,$2,$3 }'

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Tuning_and_Optimizing_Red_Hat_Enterprise_Linux_for_Oracle_9i_and_10g_Databases/chap-Oracle_9i_and_10g_Tuning_Guide-Setting_File_Handles.html

Another second part of this plugin (or a different one) can be to monitor the open files descriptors of a specific program because is a different limit. This is really useful to detect when a program is doing something wrong (not releasing FD properly, etc...).

In this case, the current open FD a program is using can be known with the following command:

> ls -f1 /proc/pid_of_program/fd | wc- l

Using `-f1` is to avoid `ls` to order de results; just printing them. It is really fast; for example, having 100000 FDs in a folder it just takes 0.046s to get the result:

> time ls -f1 fd/ | wc -l
100003
real	0m0.046s
user	0m0.020s
sys	0m0.028s

So I don't think it can affect the performance.

To get the max FD for the program, it can be reach in the `/proc/pid_of_program/limits` variable:

> Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             15057                15057                processes 
**Max open files            65535                65535                files**     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       15057                15057                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by ktsaou** [comment]
It is already there.

Check:

![image](https://cloud.githubusercontent.com/assets/2662304/20491724/f0aba056-b01a-11e6-9620-9d6db8b3a0cd.png)

We count open files at the applications section, at the users section and user groups section.
We also report sockets in the same sections, at the network subsection.

**Comment by ktsaou** [comment]
What would be interesting though, is to process the limits file and find a way to have alarms them.

The problem for the moment is that alarms are static. We can't have an alarm template applied on every dimension of a chart, without knowing the dimensions upfront.

hm... nice case... let me think how this can solved...

**Comment by dseira** [comment]
You're right, I forgot to add the application to apps_group.conf.

But it is strange because I added the new app to the apps_group.conf:

> dns: dnsdist

> ps -e | grep dnsdist
42674 ?        15:26:39 dnsdist

> ls -f1 /proc/42674/fd | wc -l
89

And netdata is only showing 5 open files:

![seleccion_038](https://cloud.githubusercontent.com/assets/378158/20495241/8986a94c-b020-11e6-8926-68e5ffe0cdab.png)

**Comment by ktsaou** [comment]
They might be sockets. Did you check them?

**Comment by ktsaou** [comment]
A few charts below

**Comment by dseira** [comment]
ah, ok. They are splitted in types. If I count all of them, is the expected value.
