### ISSUE TITLE
configure error while compile

### ISSUE THREAD

**Issue by meagon** [firehol/netdata#1275]
```
checking for sin in -lm... yes
./configure: line 5929: syntax error near unexpected token `newline'
./configure: line 5929: `PKG_CHECK_MODULES('

```

**Comment by LiveChief** [comment]
can u provide a little more info

What OS?
How are you getting this?
Have you installed all the required packages?

**Comment by PabOu-be** [comment]
Hi,

Came across the same issue.

Error is with the script netdata-installer.sh during the following command 
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3

OS is debian wheezy with proxmox 3.4.15. Everything is up-to-date and I ran the kickstart.sh script before the netdata-installer.sh. I even tried running apt-get install build-essential.

Regards

**Comment by PabOu-be** [comment]
Another error message, earlier in the command :
./configure: line 4091: PKG_PROG_PKG_CONFIG: command not found

Problem solved with apt-get install pkg-config

**Comment by LiveChief** [comment]
Hello PabOu-be,
The package "pkg-config" is part of the required packages, next time install all the required packages before you come here and complain something isnt working.
https://github.com/firehol/netdata/wiki/Installation

**Comment by ktsaou** [comment]
nice! I like your edits. Your are gentlemen...

Guys, to help you with configure errors, we really need the full output of your console. In most of the cases, either a required package is missing, or is messed on your system and needs to be re-installed.

So, run the kickstart script and post everything on your screen (including the command line you run). Even if this succeeds, it will give us information about your system and the packages.

Next, run the installer script and again post everything on your screen (include the command line you run).

Thannks

**Comment by PabOu-be** [comment]
Hello LiveChief,

As I mentionned, I ran the kickstart script, so the required packages should have been installed. There might be a bug there.

Unfortunately, I do not have output history anymore.

Regards,

**Comment by PabOu-be** [comment]
Yeah, there seems to be a bug with the kickstart script:

```
root@mybox /opt/netdata-setup/netdata $ apt-get remove pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  pkg-config
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 172 kB disk space will be freed.
Do you want to continue [Y/n]? 
(Reading database ... 54103 files and directories currently installed.)
Removing pkg-config ...
Processing triggers for man-db ...



root@mybox /opt/netdata-setup/netdata $ bash /tmp/kickstart.sh netdata-all
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 7 (wheezy)
ID              : debian
ID_LIKE         : 
VERSION_ID      : 7

We detected these:
Distribution    : debian
Version         : 7
Codename        : 7 (wheezy)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 

WARNING
package nodejs is not available in this system.
To install nodejs check: https://nodejs.org/en/download/package-manager/


All required packages are already installed. Now proceed to the next step.
```

**Comment by LiveChief** [comment]
Herro PabOu-be,
Like it says on the wiki "Try our experimental automatic requirements installer (no need to be root)." the key word is "experimental" its still needs improvements / bug fixes, anyway thank you for reporting the bug.


Try this: 
`apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`

AND 

`curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata`

**Comment by ktsaou** [comment]
Could you please try:

```
bash /tmp/kickstart.sh netdata-all -i
```

`-i` will re-install the required packages.

**Comment by PabOu-be** [comment]
ktsaou, there seems to be a few packages missing:

```
root@mybox /opt/netdata-setup/netdata $ bash /tmp/kickstart.sh netdata-all -i
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 7 (wheezy)
ID              : debian
ID_LIKE         : 
VERSION_ID      : 7

We detected these:
Distribution    : debian
Version         : 7
Codename        : 7 (wheezy)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 

WARNING
package nodejs is not available in this system.
To install nodejs check: https://nodejs.org/en/download/package-manager/


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   apt-get update  

apt-get install autoconf autoconf-archive autogen automake curl gcc git libmnl-dev lm-sensors make netcat pkg-config python python-mysqldb python-psycopg2 python-yaml uuid-dev zlib1g-dev 


Press ENTER to run it > 
apt-get install autoconf autoconf-archive autogen automake curl gcc git libmnl-dev lm-sensors make netcat pkg-config python python-mysqldb python-psycopg2 python-yaml uuid-dev zlib1g-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version.
autoconf set to manually installed.
autoconf-archive is already the newest version.
automake is already the newest version.
gcc is already the newest version.
gcc set to manually installed.
git is already the newest version.
libmnl-dev is already the newest version.
make is already the newest version.
make set to manually installed.
python-psycopg2 is already the newest version.
python is already the newest version.
python-mysqldb is already the newest version.
python-yaml is already the newest version.
uuid-dev is already the newest version.
zlib1g-dev is already the newest version.
curl is already the newest version.
The following extra packages will be installed:
  guile-1.8-libs libltdl7 libopts25-dev
Suggested packages:
  fancontrol sensord read-edid i2c-tools
The following NEW packages will be installed:
  autogen guile-1.8-libs libltdl7 libopts25-dev lm-sensors netcat pkg-config
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,443 kB/2,502 kB of archives.
After this operation, 7,026 kB of additional disk space will be used.
Do you want to continue [Y/n]?
```

**Comment by ktsaou** [comment]
Could you please install them?
Also, there was an issue at the netdata installer, so please before installing netdata, run `git pull` into the directory you have downloaded it.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.

**Comment by PabOu-be** [comment]
Hi.
Reopening as today's install-required-packages.sh script still does not pull pkg-config as required on ubuntu 16.04.
Regards,

**Comment by ktsaou** [comment]
Hi, could you please post the output of `install-required-packages.sh`, including the command line you run?

**Comment by PabOu-be** [comment]
Here it is...
`$ curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 16.04.1 LTS (Xenial Xerus)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 16.04

We detected these:
Distribution    : ubuntu
Version         : 16.04
Codename        : 16.04.1 LTS (Xenial Xerus)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   apt-get update  

apt-get install autoconf-archive autogen libmnl-dev python-yaml 


Press ENTER to run it > 
apt-get install autoconf-archive autogen libmnl-dev python-yaml 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  autoconf autogen-doc automake guile-2.0-libs libgc1c2 libopts25 libopts25-dev m4
Suggested packages:
  gnu-standards autoconf-doc libtool
The following NEW packages will be installed:
  autoconf autoconf-archive autogen autogen-doc automake guile-2.0-libs libgc1c2 libmnl-dev libopts25
  libopts25-dev m4 python-yaml
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,812 kB of archives.
After this operation, 27.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://be.archive.ubuntu.com/ubuntu xenial/universe amd64 autoconf-archive all 20150925-1 [637 kB]
Get:2 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 m4 amd64 1.4.17-5 [195 kB]
Get:3 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 autoconf all 2.69-9 [321 kB]
Get:4 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 libgc1c2 amd64 1:7.4.2-7.3 [81.2 kB]
Get:5 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 guile-2.0-libs amd64 2.0.11+1-10 [2,239 kB]
Get:6 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 libopts25 amd64 1:5.18.7-3 [57.8 kB]
Get:7 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 libopts25-dev amd64 1:5.18.7-3 [93.0 kB]
Get:8 http://be.archive.ubuntu.com/ubuntu xenial/universe amd64 autogen amd64 1:5.18.7-3 [550 kB]
Get:9 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 autogen-doc all 1:5.18.7-3 [1,013 kB]
Get:10 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 automake all 1:1.15-4ubuntu1 [510 kB]
Get:11 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 python-yaml amd64 3.11-3build1 [105 kB]
Get:12 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 libmnl-dev amd64 1.0.3-5 [11.0 kB]
Fetched 5,812 kB in 0s (11.9 MB/s)
Selecting previously unselected package autoconf-archive.
(Reading database ... 111984 files and directories currently installed.)
Preparing to unpack .../autoconf-archive_20150925-1_all.deb ...
Unpacking autoconf-archive (20150925-1) ...
Selecting previously unselected package m4.
Preparing to unpack .../archives/m4_1.4.17-5_amd64.deb ...
Unpacking m4 (1.4.17-5) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../autoconf_2.69-9_all.deb ...
Unpacking autoconf (2.69-9) ...
Selecting previously unselected package libgc1c2:amd64.
Preparing to unpack .../libgc1c2_1%3a7.4.2-7.3_amd64.deb ...
Unpacking libgc1c2:amd64 (1:7.4.2-7.3) ...
Selecting previously unselected package guile-2.0-libs:amd64.
Preparing to unpack .../guile-2.0-libs_2.0.11+1-10_amd64.deb ...
Unpacking guile-2.0-libs:amd64 (2.0.11+1-10) ...
Selecting previously unselected package libopts25:amd64.
Preparing to unpack .../libopts25_1%3a5.18.7-3_amd64.deb ...
Unpacking libopts25:amd64 (1:5.18.7-3) ...
Selecting previously unselected package libopts25-dev:amd64.
Preparing to unpack .../libopts25-dev_1%3a5.18.7-3_amd64.deb ...
Unpacking libopts25-dev:amd64 (1:5.18.7-3) ...
Selecting previously unselected package autogen.
Preparing to unpack .../autogen_1%3a5.18.7-3_amd64.deb ...
Unpacking autogen (1:5.18.7-3) ...
Replaced by files in installed package libopts25-dev:amd64 (1:5.18.7-3) ...
Selecting previously unselected package autogen-doc.
Preparing to unpack .../autogen-doc_1%3a5.18.7-3_all.deb ...
Unpacking autogen-doc (1:5.18.7-3) ...
Selecting previously unselected package automake.
Preparing to unpack .../automake_1%3a1.15-4ubuntu1_all.deb ...
Unpacking automake (1:1.15-4ubuntu1) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../python-yaml_3.11-3build1_amd64.deb ...
Unpacking python-yaml (3.11-3build1) ...
Selecting previously unselected package libmnl-dev.
Preparing to unpack .../libmnl-dev_1.0.3-5_amd64.deb ...
Unpacking libmnl-dev (1.0.3-5) ...
Processing triggers for install-info (6.1.0.dfsg.1-5) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Setting up autoconf-archive (20150925-1) ...
Setting up m4 (1.4.17-5) ...
Setting up autoconf (2.69-9) ...
Setting up libgc1c2:amd64 (1:7.4.2-7.3) ...
Setting up guile-2.0-libs:amd64 (2.0.11+1-10) ...
Setting up libopts25:amd64 (1:5.18.7-3) ...
Setting up libopts25-dev:amd64 (1:5.18.7-3) ...
Setting up autogen (1:5.18.7-3) ...
Setting up autogen-doc (1:5.18.7-3) ...
Setting up automake (1:1.15-4ubuntu1) ...
update-alternatives: using /usr/bin/automake-1.15 to provide /usr/bin/automake (automake) in auto mode
Setting up python-yaml (3.11-3build1) ...
Setting up libmnl-dev (1.0.3-5) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...

All Done! - Now proceed to the next step.





$ curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 16.04.1 LTS (Xenial Xerus)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 16.04

We detected these:
Distribution    : ubuntu
Version         : 16.04
Codename        : 16.04.1 LTS (Xenial Xerus)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   apt-get update  

apt-get install lm-sensors nodejs python-psycopg2 


Press ENTER to run it > 
apt-get install lm-sensors nodejs python-psycopg2 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpq5 libsensors4 libuv1 python-egenix-mxdatetime python-egenix-mxtools
Suggested packages:
  fancontrol sensord read-edid i2c-tools python-egenix-mxdatetime-dbg python-egenix-mxdatetime-doc
  python-egenix-mxtools-dbg python-egenix-mxtools-doc python-psycopg2-doc
The following NEW packages will be installed:
  libpq5 libsensors4 libuv1 lm-sensors nodejs python-egenix-mxdatetime python-egenix-mxtools python-psycopg2
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,685 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://be.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpq5 amd64 9.5.5-0ubuntu0.16.04 [78.1 kB]
Get:2 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 libsensors4 amd64 1:3.4.0-2 [28.4 kB]
Get:3 http://be.archive.ubuntu.com/ubuntu xenial/universe amd64 libuv1 amd64 1.8.0-1 [57.4 kB]
Get:4 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 python-egenix-mxtools amd64 3.2.9-1 [75.3 kB]
Get:5 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 python-egenix-mxdatetime amd64 3.2.9-1 [68.3 kB]
Get:6 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 python-psycopg2 amd64 2.6.1-1build2 [131 kB]
Get:7 http://be.archive.ubuntu.com/ubuntu xenial/universe amd64 lm-sensors amd64 1:3.4.0-2 [85.3 kB]
Get:8 http://be.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 nodejs amd64 4.2.6~dfsg-1ubuntu4.1 [3,161 kB]
Fetched 3,685 kB in 0s (33.4 MB/s)
Selecting previously unselected package libpq5:amd64.
(Reading database ... 114609 files and directories currently installed.)
Preparing to unpack .../libpq5_9.5.5-0ubuntu0.16.04_amd64.deb ...
Unpacking libpq5:amd64 (9.5.5-0ubuntu0.16.04) ...
Selecting previously unselected package libsensors4:amd64.
Preparing to unpack .../libsensors4_1%3a3.4.0-2_amd64.deb ...
Unpacking libsensors4:amd64 (1:3.4.0-2) ...
Selecting previously unselected package libuv1:amd64.
Preparing to unpack .../libuv1_1.8.0-1_amd64.deb ...
Unpacking libuv1:amd64 (1.8.0-1) ...
Selecting previously unselected package python-egenix-mxtools.
Preparing to unpack .../python-egenix-mxtools_3.2.9-1_amd64.deb ...
Unpacking python-egenix-mxtools (3.2.9-1) ...
Selecting previously unselected package python-egenix-mxdatetime.
Preparing to unpack .../python-egenix-mxdatetime_3.2.9-1_amd64.deb ...
Unpacking python-egenix-mxdatetime (3.2.9-1) ...
Selecting previously unselected package python-psycopg2.
Preparing to unpack .../python-psycopg2_2.6.1-1build2_amd64.deb ...
Unpacking python-psycopg2 (2.6.1-1build2) ...
Selecting previously unselected package lm-sensors.
Preparing to unpack .../lm-sensors_1%3a3.4.0-2_amd64.deb ...
Unpacking lm-sensors (1:3.4.0-2) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_4.2.6~dfsg-1ubuntu4.1_amd64.deb ...
Unpacking nodejs (4.2.6~dfsg-1ubuntu4.1) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu13) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up libpq5:amd64 (9.5.5-0ubuntu0.16.04) ...
Setting up libsensors4:amd64 (1:3.4.0-2) ...
Setting up libuv1:amd64 (1.8.0-1) ...
Setting up python-egenix-mxtools (3.2.9-1) ...
Setting up python-egenix-mxdatetime (3.2.9-1) ...
Setting up python-psycopg2 (2.6.1-1build2) ...
Setting up lm-sensors (1:3.4.0-2) ...
Setting up nodejs (4.2.6~dfsg-1ubuntu4.1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for systemd (229-4ubuntu13) ...
Processing triggers for ureadahead (0.100.0-19) ...

All Done! - Now proceed to the next step.`

**Comment by ktsaou** [comment]
I think you have missed a ` -i ` to `/tmp/kickstart.sh`.

Copy from the installation page:

```sh
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
```

It is: `bash /tmp/kickstart.sh -i netdata`

**Comment by PabOu-be** [comment]
Yes, but that's just a workaround around the bug: it should work without --ignore-installed

**Comment by ktsaou** [comment]
ok.

the script runs this: https://github.com/firehol/netdata-demo-site/blob/1bd250394fc70318f299b70cf8dd64f03dff48a0/install-required-packages.sh#L864

The above checks if the command `pkg-config` is present. It does it by running these: https://github.com/firehol/netdata-demo-site/blob/1bd250394fc70318f299b70cf8dd64f03dff48a0/install-required-packages.sh#L489-L490

So, either of the following 2 command returns 0 on your system, without `pkg-config` installed:

```
which "pkg-config" && echo "which found it - EXISTS"
command -v "pkg-config" && echo "command found it - EXISTS"
```

Could you please check it?

**Comment by jreitmayer** [comment]
I am trying the install in step 2 and having the same problem. 

[root@netdata tmp]# bash /tmp/kickstart.sh netdata-all -i
Cannot find /etc/os-release
Loading /etc/lsb-release ...
Cannot find distribution with /etc/lsb-release
Running command: lsb_release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

We detected these:
Distribution    : CentOS
Version         : 6.8
Codename        : Final
Package Manager : install_yum
Packages Tree   : centos
Detection Method: lsb_release
Default Python v: 2

WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

WARNING
package autogen is not available in this system.
You may try to install without it.

WARNING
package nodejs is not available in this system.
To install nodejs check: https://nodejs.org/en/download/package-manager/


The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   yum update

yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel


Press ENTER to run it > 

[root@netdata tmp]# which "pkg-config" && echo "which found it - EXISTS"
/usr/bin/pkg-config
which found it - EXISTS
[root@netdata tmp]# command -v "pkg-config" && echo "command found it - EXISTS"
/usr/bin/pkg-config
command found it - EXISTS
[root@netdata tmp]#

ktsaou do you have any other suggestions?

**Comment by ktsaou** [comment]
Why don't you run the command?

```sh
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel
```

If you omit ` -i ` will not re-install anything. I have decided to instruct users to use ` -i ` because a few systems report certain commands as present, although they are not (I haven't trace it though).

**Comment by jreitmayer** [comment]
Ran that and got this... 

```
[root@netdata tmp]# yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.host-engine.com
 * epel: pubmirror2.math.uh.edu
 * extras: dist1.800hosting.com
 * updates: ftp.osuosl.org
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package curl-7.19.7-52.el6.x86_64 already installed and latest version
Package gcc-4.4.7-17.el6.x86_64 already installed and latest version
Package git-1.7.1-4.el6_7.1.x86_64 already installed and latest version
Package libmnl-devel-1.0.2-3.el6.x86_64 already installed and latest version
Package libuuid-devel-2.17.2-12.24.el6_8.1.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package MySQL-python-1.2.3-0.3.c1.1.el6.x86_64 already installed and latest version
Package nc-1.84-24.el6.x86_64 already installed and latest version
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Package python-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-psycopg2-2.0.14-2.el6.x86_64 already installed and latest version
Package PyYAML-3.10-3.1.el6.x86_64 already installed and latest version
Package zlib-devel-1.2.3-29.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package lm_sensors.x86_64 0:3.1.1-17.el6 will be installed
--> Processing Dependency: lm_sensors-libs(x86-64) = 3.1.1-17.el6 for package: lm_sensors-3.1.1-17.el6.x86_64
--> Processing Dependency: libsensors.so.4()(64bit) for package: lm_sensors-3.1.1-17.el6.x86_64
--> Running transaction check
---> Package lm_sensors-libs.x86_64 0:3.1.1-17.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================================================================================
 Package                             Arch                       Version                            Repository                Size
==================================================================================================================================
Installing:
 lm_sensors                          x86_64                     3.1.1-17.el6                       base                     123 k
Installing for dependencies:
 lm_sensors-libs                     x86_64                     3.1.1-17.el6                       base                      38 k

Transaction Summary
==================================================================================================================================
Install       2 Package(s)

Total download size: 161 k
Installed size: 414 k
Is this ok [y/N]: y
Downloading Packages:
(1/2): lm_sensors-3.1.1-17.el6.x86_64.rpm                                                                  | 123 kB     00:00
(2/2): lm_sensors-libs-3.1.1-17.el6.x86_64.rpm                                                             |  38 kB     00:00
----------------------------------------------------------------------------------------------------------------------------------
Total                                                                                             842 kB/s | 161 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : lm_sensors-libs-3.1.1-17.el6.x86_64                                                                            1/2
  Installing : lm_sensors-3.1.1-17.el6.x86_64                                                                                 2/2
  Verifying  : lm_sensors-libs-3.1.1-17.el6.x86_64                                                                            1/2
  Verifying  : lm_sensors-3.1.1-17.el6.x86_64                                                                                 2/2

Installed:
  lm_sensors.x86_64 0:3.1.1-17.el6

Dependency Installed:
  lm_sensors-libs.x86_64 0:3.1.1-17.el6

Complete!

```
Then i rerun the step 2 from your install page and i get 

```
[root@netdata tmp]# curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
Cannot find /etc/os-release
Loading /etc/lsb-release ...
Cannot find distribution with /etc/lsb-release
Running command: lsb_release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

We detected these:
Distribution    : CentOS
Version         : 6.8
Codename        : Final
Package Manager : install_yum
Packages Tree   : centos
Detection Method: lsb_release
Default Python v: 2

WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

WARNING
package autogen is not available in this system.
You may try to install without it.

WARNING
package nodejs is not available in this system.
To install nodejs check: https://nodejs.org/en/download/package-manager/


The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   yum update

yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel
```

**Comment by ktsaou** [comment]
This is step 1.
Step 1 is `git checkout ...`

**Comment by ktsaou** [comment]
sorry step 2 is `git checkout ... `

**Comment by ktsaou** [comment]
this one: https://github.com/firehol/netdata/wiki/Installation#2-install-netdata

**Comment by jreitmayer** [comment]
my apologies i meant step 1, second curl command

**Comment by ktsaou** [comment]
> my apologies i meant step 1, second curl command

It is not required. You have to pick one of the 2: the first is basic netdata (system monitoring), the second is full netdata (including application plugins).

**Comment by jreitmayer** [comment]
oh thats confusing. I can try moving forward but i was hoping to use some of the application plugins.

**Comment by ktsaou** [comment]
> oh thats confusing.

I am sorry for that. If you believe you can make that page less confusing, just edit it.

> I can try moving forward but i was hoping to use some of the application plugins.

Yes please do so. There is no harm to run both the commands of step one.

**Comment by jreitmayer** [comment]
did i miss something on my install of Centos that the application plugin might need?

**Comment by ktsaou** [comment]
Plugins in netdata are used to monitor applications you have installed. For example, you need the python mysql plugin to monitor your mysql server.

Which application you need to monitor?

**Comment by jreitmayer** [comment]
elasticsearch to start. mysql would be nice. apache. wordpress.

**Comment by ktsaou** [comment]
ok. install netdata and then check `/etc/netdata/python.d`. You will find all the config files to edit to make it connect to all your apps. There are a few instructions on each file.

**Comment by jreitmayer** [comment]
i'll take a look at that. thanks
