### ISSUE TITLE
Netdata on Windows using Ubuntu integrated bash on windows 10

### ISSUE THREAD

**Issue by gkathir15** [firehol/netdata#1276]
Since the new _**developer preview**_ **of windows 10,**
they have **# 
ubuntu bash shell in windows

** [https://msdn.microsoft.com/en-us/commandline/wsl/about](url)
Everything was okay with the compilation and installation,
but it could not start when the **Init** file started.
It threw a lot of errors.even with all python modules installed.
Hope I could  have feedback on it.
I even changed all the ports to 8090,which was not used and accessible in my PC
If this could be accomplished we can Run it on Windows,

**Comment by LiveChief** [comment]
i don't know maybe cause its build for linux and your trying to run it on windows.
:|
./Close

**Comment by ktsaou** [comment]
@gkathir15 can you post here the errors?
have you run the dependencies kickstart script?

**Comment by ktsaou** [comment]
@LiveChief windows 10 runs ubuntu. netdata should run on it. The whole idea with these issues is to make netdata better. So, please don't instruct people to close the issues without first investigating what is wrong.

**Comment by gkathir15** [comment]
@ktsaou  Sure I will be posting the errors soon.
and let me run the yes I ran the kick start script
is this the kickstart script?
`curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata`
I threw error like cannot use port 19999,
so I manually changed the port to 8090 in all codes and made a repo:[https://github.com/gkathir15/netdata](url)
and by changing the Repo address to my repo `git clone https://github.com/gkathir15/netdata.git --depth=1,
this didn't work.
Please correct me if am wrong.
Thanks.

**Comment by ktsaou** [comment]
please follow the procedure are described at the installation page and copy-paste the errors here. The kickstart script should not do anything about port 19999.

**Comment by gkathir15** [comment]
@ktsaou  sure I will do it,
Between mean time if anyone can install netdata IN Windows it would be helpful.
@LiveChief -if u could plz try working on windows.

**Comment by ktsaou** [comment]
I just installed it on Ubuntu/BASH for Windows 10.

http://pastebin.com/9mp4gikx

It installed without issues, although it seems that the init scripts have some issue:

```
/usr/sbin/service netdata stop
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  3554 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
```

and netdata cannot use IPv6, only IPv4:

```
2016-11-28 12:11:58: netdata: ERROR: IPv6 bind() on ip '::' port 19999 failed. (errno 98, Address already in use)
2016-11-28 12:11:58: netdata: ERROR: Cannot bind to ip '::', port 19999 (errno 95, Operation not supported)
2016-11-28 12:11:58: netdata: INFO: Listen socket [0.0.0.0]:19999 opened.
```

Both of the above, are outside the responsibility of netdata.
Check at the end: netdata runs.

**Comment by gkathir15** [comment]
@ktsaou So finally you can see netdata on your local windows browser on the above port 19999,
are you getting the charts on browser?
even i got the same error.
we could not Start the Init file right?

**Comment by ktsaou** [comment]
Yes, I saw the charts.
There was a bug in the netdata installer (#1292) which is now fixed.
Could you please `git pull` into the directory you downloaded netdata source and re-install it?

**Comment by gmorain** [comment]
Hi @gkathir15 (and @ktsaou)

I confirm that on my side, after the install script fix (which also caused issues on my Debian Jessie server), I successfully installed netdata under WSL in my W10 virtual machine (my main machine is a Mac) and accessed the graphs immediately after.

Gilles

**Comment by gkathir15** [comment]
@gmorain  and @ktsaou  thanks,
@ktsaou I will reinstall it.
let me close this issue.

**Comment by Droyk** [comment]
Hey guys I am new to this will you be able to give me any instruction on how to install netdata on windows 10 thanx @ktsaou

**Comment by ktsaou** [comment]
Well, you need to enable "Bash for Windows" (or "Ubuntu for Windows" - I don't know the official name).

Once you do this, you will have a Bash application in your programs. If you start this, you will get a Linux prompt.

On this prompt, follow the installation wiki page of netdata: https://github.com/firehol/netdata/wiki/Installation - the procedure is the same with **Debian / Ubuntu**.

**Comment by hbcbh1999** [comment]
![image](https://user-images.githubusercontent.com/1378193/42980372-f58c0ea0-8ba4-11e8-9df5-e5c0ff11ba66.png)

I recently installed netdata on Windows Subsystem (Ubuntu 18.04). Installation was complete with all dependencies.  But I cannot use it whatsoever. Attached is screenshot from my terminal window.

**Comment by ktsaou** [comment]
You have a permissions issue. Something is wrong with this installation.
Could you please do `ls -l /var/lib/netdata/registry` and post it here?

**Comment by hbcbh1999** [comment]
![image](https://user-images.githubusercontent.com/1378193/43046066-aaea4eb8-8d91-11e8-9459-9a06ce187640.png)

I don't have netdata.service

**Comment by ktsaou** [comment]
ok, could you please run `find /etc/systemd -name netdata.service` and locate it?

**Comment by hbcbh1999** [comment]
I ran the command but no result was returned. I installed netdata with bash script.

**Comment by ktsaou** [comment]
Could you please re-install it and post the whole installation output here?

**Comment by hbcbh1999** [comment]
If you don't mind, I would like to do this later. I have been trying to get the uninstall script but I haven't succeeded yet.
