### ISSUE TITLE
Convert system.ipv4 in and out to megabytes

### ISSUE THREAD

**Issue by brando56894** [firehol/netdata#1278]
What do I have to change to get system.ipv4 inbound and outbound to show MB/sec instead of Kbps? I know how to change it from Kbps to Mbps, but can't figure out exactly how to change it from Mbps to MB/sec.

I've enabled **dim inOctet multiplier = 8** and **dim outOctet multiplier = -8** hoping they would change them by a factor of 8, but it didn't seem to do anything.

**Comment by ktsaou** [comment]
```
[system.ipv4]
	# history = 28800
	# enabled = yes
	# cache directory = /opt/netdata/var/cache/netdata/system.ipv4
	# chart type = area
	# type = system
	# family = network
	units = MB/s
	# context = system.ipv4
	# priority = 500
	# gap when lost iterations above = 1
	# name = system.ipv4
	# title = IPv4 Bandwidth (system.ipv4)
	# dim InOctets name = received
	# dim InOctets algorithm = incremental
	dim InOctets multiplier = 1
	dim InOctets divisor = 1048576
	# dim OutOctets name = sent
	# dim OutOctets algorithm = incremental
	dim OutOctets multiplier = -1
	dim OutOctets divisor = 1048576
```

So multiplier should by 1 (or -1 for out) and divisor 1024*1024 = 1048576 for both.

**Comment by ktsaou** [comment]
The source is bytes, so MB is `source * 1 / (1024 * 1024)`

**Comment by brando56894** [comment]
Thanks!

**Comment by kevincaradant** [comment]
Hi 

I'm looking the file before to compile the project in the aim to have all setup as I want after to start your script to install netdata but no way to find this file. In `netdata.conf ` before to compile, the file is almost empty. So, I tried at the hand and after with Atom to search the text of this file. I get always 0 answer :/. Do you know where I can edit the file in your github project to have Mb/s directly ? 

Thank you  very much ;)

**Comment by ktsaou** [comment]
netdata generates `netdata.conf`. Just download it with:

```sh
curl http://localhost:19999/netdata.conf >/tmp/netdata.conf
```

Then edit `/tmp/netdata.conf`, move it to `/etc/netdata/netdata.conf` and restart netdata.

**Comment by DonZheng** [comment]
Hi @ktsaou sorry for bringing this topic up again, but I'm trying to figure out how to change openvpn.total_traffic to Mb/s.

I searched in netdata.conf and go.d/openvpn.conf but cannot find where to edit the `units`, `multiplier `and `divisor `options. Can you please advise where I should look at?

P.S. At the moment, my netdata cloud console displays openvpn.total_traffic in kilobits, which is not very easy to read.
![image](https://user-images.githubusercontent.com/40833875/95667514-ee001880-0bb2-11eb-8f87-c9066172d3a1.png)

**Comment by thiagoftsm** [comment]
Hello @DonZheng ,

Are you having this problem on cloud dasboard or Netdata agent dashboard?
Which version are you running?  I remember we bring few versions ago a fix to convert traffic for ebpf that also affects openvpn.

Best regards!

**Comment by DonZheng** [comment]
@thiagoftsm , thank you for your reply.

Sorry that I didn't make the case clear enough. I'm having this problem on cloud dashboard.

Running environment: netdata v1.25.0-151-nightly on Ubuntu 20.04.1 LTS.

After netdata installation, then manually update conf files for openvpn, I can see charts as illustrated in my previous post. Trying to figure out how to change the metrics to Mb/s, so asking for guidance here.

Any help will be greatly appreciated.

**Comment by thiagoftsm** [comment]
Thank you for the additional information @DonZheng.

I will ask you to create a new issue, because this original issue was related to the agent. 

I think with a separated issue, it will be more clear what we need to fix.

Best regards!

**Comment by DonZheng** [comment]
@thiagoftsm , roger that. I will create a new issue shortly.

Cheers.

**Comment by thiagoftsm** [comment]
Thank you @DonZheng !

I assigned the issue for the cloud team.

Best regards!

**Comment by DonZheng** [comment]
@thiagoftsm Absolutely my pleasure to contribute my 2 cents worth to this great tool.

I was thinking the netdata.cloud, as a closed source product, will not respond to user feedback on github. It they do, I would LOVE to raise a few more feedbacks. 

I manage quite a number of servers and can see many simple but missing features on cloud (i.e. displaying server ip address,  sorting, alias/node_name change....)

Shall I raise cloud related feedback as issues here on github, @thiagoftsm ?

Best Wishes!

**Comment by thiagoftsm** [comment]
Hello @DonZheng ,

The cloud is a project that we started this year and we would love to hear feedback from it. :) Please, be free to join our community  https://community.netdata.cloud and post a question! You can also send me an email (thiago@netdata.cloud) and we will try to schedule a meeting to hear you.

Best regards!
