### ISSUE TITLE
Aggregate data from a cluster

### ISSUE THREAD

**Issue by izdi** [firehol/netdata#128]
Can't seem to find info regarding aggregation across multiple servers, is there any approach or planned feature ?

**Comment by cbricart** [comment]
aggregation is/may be done within your browser.
The idea for you is to create dashboards (i.e. HTML skeletons) which pulls the data via the API from multiple servers.
see: https://github.com/firehol/netdata/wiki/Custom-Dashboards

**Comment by ktsaou** [comment]
try this:

1. git pull (I pushed `tv.html` today)
2. install it again
3. go to http://your.server:19999/tv.html

There is your aggregation...

**Comment by izdi** [comment]
@ktsaou alright this seems like it, are there any triggers/alerts available ?

**Comment by cbricart** [comment]
@izdi see #88

**Comment by ktsaou** [comment]
I think no issue left here. I close it. We will discuss alerts in #88

**Comment by damageboy** [comment]
@ktsaou From reading tv.html I understand that by aggregation you mean aggregating multiple charts into one html page. Not agregating total CPU usage from N machines... is this correct?

**Comment by ktsaou** [comment]
> @ktsaou From reading tv.html I understand that by aggregation you mean aggregating multiple charts into one html page. Not agregating total CPU usage from N machines... is this correct?

yes
