### ISSUE TITLE
failed to send email

### ISSUE THREAD

**Issue by BecomeBamboo** [firehol/netdata#1280]
thx for the software,I read the health wiki to configurate,but I cannot receive alarm via email.My system is centos 6,I can use command to sendmail ,like this:
`mail -s 'test mail' xxxtest@gmail.com </usr/local/test.txt 
`

this is the error log:
```
/usr/local/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh: line 471: /usr/sbin: is a directory
2016-11-24 15:46:06: alarm-notify.sh: ERROR: failed to send email notification for: centos1 disk_space._home.disk_space_usage is WARNING to 'xxxtest@gmail.com' with error code 126.
```

my send mail path is:/usr/sbin,and service start,here is my conf:
sendmail path
![image](https://cloud.githubusercontent.com/assets/3755288/20591547/06541f8c-b264-11e6-959e-3ffede3a4afe.png)

recipient address:
![image](https://cloud.githubusercontent.com/assets/3755288/20591570/1cc1f3b6-b264-11e6-8c74-6959ff673713.png)

what's the problem?and is there any conf demo I can refer to?

**Comment by ktsaou** [comment]
It needs the full path to the sendmail command, i.e. `sendmail="/usr/sbin/sendmail"`. Or leave it empty. It will find it in `/usr/sbin`. This is used in cases where multiple MTAs are installed in a system, to allow the admin route the email to the proper MTA.

**Comment by BecomeBamboo** [comment]
thx for the reply,really do me a favor,now it works ,thx

**Comment by ktsaou** [comment]
ok. nice.
