### ISSUE TITLE
IPv6: Address family not supported by protocol appears in log if "ip version = ipv4" is set

### ISSUE THREAD

**Issue by infectormp** [firehol/netdata#1282]
Hello,

I use kernel with disabled ipv6
If i run netdata with `ip version = ipv4` and `bind to = localhost ` i get 
`ERROR: netdata: IPv6 socket() on ip '::1' port 19999 failed. (errno 97, Address family not supported by protocol)
`

To solve this problem i need comment out `::1             localhost` in `/etc/hosts` or set  `bind to = 127.0.0.1 ` in `netdata.conf`

here is my `/etc/hosts`
```
# IPv4 and IPv6 localhost aliases
127.0.0.1       localhost
::1             localhost
```

**Comment by wioxjk** [comment]
Well, if you have IPv6 disable there is no reason to keep ::1 localhost in your hostfile at all.
I think this a non-issue, because it works as expected.

**Comment by infectormp** [comment]
even if i set `ip version = ipv4`?

**Comment by ktsaou** [comment]
@wioxjk is right, but @infectormp is also right. It seems like a bug. netdata knows that IPv6 is disabled in its config and knows also that `::1` is IPv6. It should not even try it.

@infectormp I guess netdata starts normally even when this line is printed. So the only problem is this log line (and the attempt to connect to it). Right?

**Comment by infectormp** [comment]
@ktsaou you right, i can connect to localhost:19999. So problem only in logs.

**Comment by ktsaou** [comment]
ok, found the fault.

`ip version` does not exist any more. Your `netdata.conf` is very old.

So the problem is that since you see an error message, you cannot tell if netdata is running or not.
If netdata cannot bind to any IP, port given, it will print `Cannot listen to any socket. Exiting...`. But you don't know that.

So, I changed netdata to print all the addresses it managed to bind to, if any of its attempts to bind to a port failed, like this:

```
2016-11-26 16:38:38: netdata: ERROR: IPv4 bind() on ip '1.2.3.4' port 19999 failed. (errno 99, Cannot assign requested address)
2016-11-26 16:38:38: netdata: ERROR: Cannot bind to ip '1.2.3.4', port 19999
2016-11-26 16:38:38: netdata: INFO: Listen socket [0.0.0.0]:19999 opened.
2016-11-26 16:38:38: netdata: INFO: Listen socket [::]:19999 opened.
```

Thanks for reporting it.

**Comment by infectormp** [comment]
@ktsaou Thank you for fixing it. I use netdata 1.4 and found information about `ip version` option in wiki https://github.com/firehol/netdata/wiki/Configuration.

**Comment by ktsaou** [comment]
thanks for pointing that wiki page to me. I fixed there too.

**Comment by ktsaou** [comment]
merged the fix...

**Comment by Scoutinglegion** [comment]
I can understand it
