### ISSUE TITLE
Question - Netdata memory modes and footprint

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#1285]
I tried running Netdata in all the three modes, to compare the memory utilization in each scenario and for some reason couldn't see any benefits in using map mode except the fact that the data is synced periodically. In all the cases the memory footprint of Netdata hovered around the 350MB mark.

My configuration is as follows

[global]
	#hostname = NETDATA_HOSTNAME
	history = 86400
	access log = none
	disconnect idle web clients after seconds = 3600
	config directory = /etc/netdata
	cache directory = /var/cache/netdata
	log directory = /var/log/netdata
	memory deduplication (ksm) = yes
	error log = /var/log/netdata/error.log
	update every = 5
	# ram, save (the default, save on exit, load on start), map (swap like)
    memory mode = map
    # the directory where data are saved
    cache directory = /var/cache/netdata
	
[registry]
    enabled = yes
    registry to announce = http://NETDATA_REGISTRY_URL
    registry hostname = NETDATA_REGISTRY_NAME

I do have ksm enabled as well on my CentOs instance. Is the "map" mode supposed to save on memory footprint?

**Comment by ktsaou** [comment]
The memory mode does not change the memory footprint.

In all modes the memory footprint is exactly the same, but in `map`, the kernel is allowed to swap out netdata to its data files (not to swap memory). For this to happen, the system must be under memory pressure. Otherwise the kernel does not have any reason not to give to netdata all the RAM it requested.

Can you check it?

**Comment by ktsaou** [comment]
What can change the memory footprint is KSM. The kernel memory deduper. You can expect 50% less memory used by netdata.

**Comment by gamefundas** [comment]
I tested this and the behavior is as expected. Was able to confirm that when squeezed out for memory Netdata starts swapping to disk. Also KSM benefits to about 60%. 

We should be able to close this issue.

**Comment by ktsaou** [comment]
nice! thanks!
