### ISSUE TITLE
Question - Postgres remote instance or RDS support

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#1286]
I have seen some posts that talks about support for Postgres running locally, the demo shows few charts as well but couldn't find any good documentation that explains how to setup one. I am more interested in monitoring a remote DB instance which is running on Amazon RDS.

Does the developed plugin support monitoring remote Postgres instances?

**Comment by ktsaou** [comment]
Yes, it does.

Check the configuration file: https://github.com/firehol/netdata/blob/master/conf.d/python.d/postgres.conf

You can give host, port, user and password.

**Comment by gamefundas** [comment]
I added my DB configuration in postgres.conf and also modified python.d.conf to enable postgres but dont see any change to the effect. My thinking was this will create a "Postgres" menu item in the dashboard with additional DB charts. Am I missing something?

Please pardon me if I missed reading the configuration steps for plugins.

**Comment by ktsaou** [comment]
Run it by hand:

```
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 postgres
```

Keep in mind there is an issue (https://github.com/firehol/netdata/pull/1183#issuecomment-258716151): the python module will just report failure to connect without any descriptive reason for back it up. I hope @facetoe will fix that in the python modules for postgres.

**Comment by facetoe** [comment]
Hi @gamefundas, on the DB server you need to ensure that [pg_hba.conf](https://www.postgresql.org/docs/9.1/static/auth-pg-hba-conf.html) is configured to allow connections from the netdata server. 

You should be able to connect using `psql` from the netdata server, if this fails then the plugin will also fail. 

I'll try to fix the terrible error message tonight @ktsaou !

**Comment by ktsaou** [comment]
> I'll try to fix the terrible error message tonight

thank you!

**Comment by ktsaou** [comment]
The latest version has better logging in case of connection failure.
Thank you @facetoe  !

**Comment by facetoe** [comment]
No worries!

**Comment by gamefundas** [comment]
Fantastic this worked. Had some library dependency on CentOs but I managed to get all the charts running. Thanks @facetoe and @ktsaou

**Comment by gamefundas** [comment]
Closing this one.

**Comment by lastko** [comment]
Hello, 

I have created a docker image from titpetric/netdata:1.6, I have installed python-psycopg2 in order to use postgres plugin. I'm running the container using flags: 
--privileged 
--net=host
-v $PWD/etc/netdata/python.d/postgres.conf:/etc/netdata/python.d/postgres.conf:ro 
-v /proc:/host/proc:ro 
-v /sys:/host/sys:ro 
-v /var/run/docker.sock:/var/run/docker.sock

, with configurations files mounted.

I have configured postgres.conf to monitorize RDS instances but I can't see any graphs in the dashboard because I'm getting this error:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 postgres
2017-04-23 09:49:40:  INFO: Using python v2
2017-04-23 09:49:40:  INFO: YAML output is ordered
2017-04-23 09:49:40: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-04-23 09:49:40: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['postgres']
2017-04-23 09:49:40: python.d DEBUG: postgres: loading module configuration: '/etc/netdata/python.d/postgres.conf'
2017-04-23 09:49:40: python.d DEBUG: postgres: reading configuration
2017-04-23 09:49:40: python.d DEBUG: postgres/production: job added
2017-04-23 09:49:40: python.d DEBUG: all job objects [<Service(production, initial daemon)>]
2017-04-23 09:49:40: python.d INFO: CHECKED OK: postgres_production
2017-04-23 09:49:40: python.d INFO: RENAMED: postgres_Production , from postgres_production
2017-04-23 09:49:40: python.d DEBUG: overridden job names: ['postgres_Production']
2017-04-23 09:49:40: python.d DEBUG: all remaining job objects: [<Service(Production, initial daemon)>]
2017-04-23 09:49:40: python.d ERROR: postgres_Production must be superuser to get directory listings

2017-04-23 09:49:40: python.d ERROR: DISABLED: postgres/Production
2017-04-23 09:49:40: python.d FATAL: no more jobs
DISABLE
```

I took a look to the file ```python.d/postgres.chart.py``` and the only check related with the superuser is related with the database to show certain graphs but nothing related with "directory listings".

Please, could you let me know how to disable this behavior or fix the issue?

Thanks you very much in advance.

**Comment by facetoe** [comment]
Hmm, I've never tested the plugin against RDS but I know RDS instances run with reduced privliges. Looking at the SQL I'd guess https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L65 is the culprit as it runs `pg_catalog.pg_ls_dir('pg_xlog/archive_status')`. I'd say a patch is needed to add an option to disable this metric in order for it to work with RDS. 

I'll set up and RDS instance and see if I can get it working.

**Comment by lastko** [comment]
Yep, the IF_SUPERUSER query returns FALSE
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L123
in RDS instance.

Maybe we can remove from default QUERY_STATS:
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L146
QUERIES['ARCHIVE']: METRICS['ARCHIVE'],

and add it in method add_additional_queries_ :
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L301
if is_superuser is true.

**Comment by facetoe** [comment]
Yep, looks like an easy fix.

**Comment by l2isbad** [comment]
@lastko @facetoe 
PR?

**Comment by facetoe** [comment]
Yea I'm testing now, just having a few RDS related issues.

**Comment by lastko** [comment]
I'm testing right if it works right now. You should exclude 'rdsadmin' database because your RDS user don't have permission to use this database. For any reason I'm getting a ```Error: invalid connection option "database_poll"``` when I try to define database and avoid quering "rdsadmin" database.

**Comment by facetoe** [comment]
yea it looks like some of the queries don't respect the `database_poll` option.

**Comment by lastko** [comment]
I think we have two different things here. Maybe we should PR the fix for 'is_superuser' and 'QUERY_STATS' that is working for me, and create another one for the problem with the 'database_poll'.

**Comment by facetoe** [comment]
Yep sounds good.

**Comment by l2isbad** [comment]
> Error: invalid connection option "database_poll"

hm, how it happens? `database_poll` option pop'ed from the configuration on `init`

**Comment by facetoe** [comment]
Looks like the problem is this query - https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L87. It filters on `WHERE NOT datname ~* '^template\d+'` but doesn't exclude any other databases. I think we need to change it to explicitly include only those databases we are interested instead of excluding those we are not interested in. Shouldn't be had to do with paramatarized queries.

**Comment by facetoe** [comment]
Cool got it working, PR incoming.

**Comment by facetoe** [comment]
I created  #2120 to fix these issues, any chance you guys could test?

**Comment by lastko** [comment]
It works pretty good for me. I'm getting metrics from 2 different instances in RDS and another one from compose. So good job and thanks you very much!

**Comment by facetoe** [comment]
No worries!
