### ISSUE TITLE
error in date-time strings created by logdate() function

### ISSUE THREAD

**Issue by mutsys** [firehol/netdata#1287]
Just noticed this in `node.d/node_modules/netstat.js`

```javascript
logdate: function(d) {
        if(typeof d === 'undefined') d = new Date();
        return this.zeropad2(d.getFullYear()) + '-' + this.zeropad2(d.getMonth()) + '-' + this.zeropad2(d.getDay())
            + ' ' + this.zeropad2(d.getHours()) + ':' + this.zeropad2(d.getMinutes()) + ':' + this.zeropad2(d.getSeconds());
    }
```

`Date.getDay()` returns a numeric value for the day of the week (Sunday -> Saturday : 0 -> 7). I think you meant to use `Date.getDate()`, which returns a numeric value for the day of the month (1 -> 31).

**Comment by ktsaou** [comment]
You are right.
I am fixing it now.
