### ISSUE TITLE
most CPU graphs empty for Ubuntu 16.10

### ISSUE THREAD

**Issue by icebal** [firehol/netdata#1289]
idle jitter and cpufreq are the only graphs showing. same hardware running centos 7 is showing these just fine. /proc/loadavg is pulling the same info as centos counterpart as well.

**Comment by ktsaou** [comment]
can you check your `/var/log/netdata/error.log`?
The only reason for this to happen is for netdata to be unable to read `/proc`. So, you must have installed `grsecurity`, `apparmor`, or something exotic that prevents it from reading the information it needs.

**Comment by icebal** [comment]
Its a default install of xenial, looks like apparmor is installed and on by
default. Only things i could find relating to anything cpu is this:
2016-11-27 23:14:00: charts.d: INFO: cpu_apps: is disabled. Add a line with
cpu_apps=force in /
etc/netdata/charts.d.conf to enable it (or remove the line that disables
it).                  2016-11-27 23:14:00: charts.d: INFO: cpufreq: is
disabled. Add a line with cpufreq=force in /et
c/netdata/charts.d.conf to enable it (or remove the line that disables it).
2016-11-28 00:23:59: apps.plugin: ERROR: Cannot stat file
'/proc/19378/stat' (errno 2, No such file or
directory)
2016-11-28 01:27:40: apps.plugin: ERROR: Cannot stat file
'/proc/11015/stat' (errno 2, No such file or
directory)
2016-11-28 01:33:55: apps.plugin: ERROR: Cannot stat file
'/proc/13147/stat' (errno 2, No such file or
directory)
2016-11-28 02:35:16: apps.plugin: ERROR: Cannot stat file
'/proc/11669/stat' (errno 2, No such file or directory)

**Comment by ktsaou** [comment]
hm... these are not related to the issue you face.

Do this:

```sh
# ls -ld /proc/stat
-r--r--r-- 1 root root 0 Nov 28 10:47 /proc/stat
```

**Comment by icebal** [comment]
-r--r--r-- 1 root root 0 Nov 27 23:02 /proc/stat

**Comment by ktsaou** [comment]
hm...

stop netdata and do this by hand:

```
# netdata -D
```

does it work now?

Did you install it with `netdata-installer.sh` ?

**Comment by icebal** [comment]
Same thing with -D (ran as root and as user) after stopping the systemd
service, and used the installer.sh, yes. -D option stopped most graphs from
showing anything, but wasn't giving the "empty" icon either. Its running on
the system via systemd unit that was installed with it.

**Comment by icebal** [comment]
through up a opensuse leap server and it too has the same issue, and it also has apparmor on by default. going to continue to TS.

**Comment by icebal** [comment]
completely stopping apparmor on both opensuse (tumbleweed, not leap, i was mistaken) and ubuntu caused no change.

**Comment by ktsaou** [comment]
Could you please run `git pull` into the directory you downloaded netdata source and run the installer again? There was a bug at the installer (#1292) which might be the cause of this.

**Comment by icebal** [comment]
git pulled, force reinstall, and restarted with systemctl for good measure. the charts are there now, not just saying empty, just no data at all shown.

**Comment by icebal** [comment]
going to uninstall and redo everything.

**Comment by icebal** [comment]
complete uninstall, reinstall also did nothing. if it helps, the app.plugin for CPU works just fine, its just the /proc info that wont show up.

**Comment by ktsaou** [comment]
well, you are facing quite an odd situation...
Could you please run netdata as root? Edit `/etc/netdata/netdata.conf` and set `run as user = root` and restart netdata. Does it work now?

**Comment by icebal** [comment]
Running as root still has the same issue, and now the Network Interface
graphs are showing the empty icon. I also had to chown all the files in
/usr/share/netdata/web to root:root or it would show a "unable to access
/usr/share/netdata/web" error.

**Comment by ktsaou** [comment]
@icebal this is totally strange...

Let me check something else. This is going to create a lot of output, so I would suggest to start it for some time and stop it.

Stop netdata and run it with this:

```
./src/netdata -W debug_flags="0x00000020" -D
```

This will create `/var/log/netdata/debug.log`. It should log lines like this: https://github.com/ktsaou/netdata/blob/6cd8b76b0a1ce22f82c4fb23c19f351ee8cfe56d/src/plugin_proc.c#L79-L79

If you see lines like this, data collection in netdata works (tries to collect data). It should continue logging such lines forever. If it stops, we have an issue.

If you are really adventurous, you could try `0xFFFFFFFF` - this is all the debugging info there is. The full list is here: https://github.com/ktsaou/netdata/blob/6cd8b76b0a1ce22f82c4fb23c19f351ee8cfe56d/src/log.h#L4-L28
But don't enable all of them. If `0x00000020` continues forever, without any charts, we will enable `0x00000040` to check what is being written to the internal database.

(I am very sorry for this, but I have several ubuntu 16.10 installations without any issues - we have to trace it on your system to understand what is happening).

**Comment by icebal** [comment]
It be clear, its happening on both openSuse tumbleweed, and ubuntu 16.10
like I said above. I'll start the debug on both in about 1-2 hours as I'm
at work right now.

**Comment by ktsaou** [comment]
Have you checked another browser? It might be a plugin you have...

**Comment by icebal** [comment]
both firefox and chrome do this, and it wouldnt explain why centos7 and debian 8 work fine :(

**Comment by icebal** [comment]
0x20 didnt fix the issue, and only logged ~1 page with vi in the last 8 hours. running 0x40 now.

**Comment by icebal** [comment]
redid 0x20 to grab the logs, all it spit put in the last 8 hours is the same as below:
2016-11-30 00:10:06: netdata: DEBUG (1460@sys_fs_cgr:cgroups_main   ): PROCNETDEV: calling do_sys_fs_cgroup().
2016-11-30 00:10:07: netdata: DEBUG (0079@plugin_pro:proc_main      ): PROCNETDEV: calling do_sys_kernel_mm_ksm().
2016-11-30 00:10:07: netdata: DEBUG (0088@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_loadavg().
2016-11-30 00:10:07: netdata: DEBUG (0096@plugin_pro:proc_main      ): PROCNETDEV: calling do_ipc().
2016-11-30 00:10:07: netdata: DEBUG (0104@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_interrupts().
2016-11-30 00:10:07: netdata: DEBUG (0112@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_softirqs().
2016-11-30 00:10:07: netdata: DEBUG (0120@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_net_softnet_stat().
2016-11-30 00:10:07: netdata: DEBUG (0128@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_sys_kernel_random_entropy_avail().
2016-11-30 00:10:07: netdata: DEBUG (0136@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_net_dev().
2016-11-30 00:10:07: netdata: DEBUG (0144@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_diskstats().

**Comment by icebal** [comment]
went ahead and did the 0xff debug as well, 0x40 was not putting anything out to the logs, or to stdin. they are attached, let me know if you need screenshots as well.

[opensuse-tumbleweed-logs.zip](https://github.com/firehol/netdata/files/621134/opensuse-tumbleweed-logs.zip)
[ubuntu16.10-logs.tar.zip](https://github.com/firehol/netdata/files/621135/ubuntu16.10-logs.tar.zip)

**Comment by icebal** [comment]
here is a screenshot for ubuntu, the same issue is with opensuse as well:
![image](https://cloud.githubusercontent.com/assets/946581/20742918/ee87b52e-b698-11e6-979d-b1389e55f092.png)

**Comment by icebal** [comment]
reinstalling and rebooting both machines fixed all the known issues. why did this happen on these two, but debian and centos7 worked from the start? all 4 were done through the "automated" procedure in the wiki.

**Comment by ktsaou** [comment]
This is very strange. I can't see any reason for this happening, apart from something preventing netdata from reading the `/proc` files properly.

Nice you got it working now.
