### ISSUE TITLE
Dovecot socket unexpectedly disconnected

### ISSUE THREAD

**Issue by nicolasbadia** [firehol/netdata#1295]
I can't get dovecot to work correctly with netdata.
Netdata give me this error when it start:

```
2016-11-28 21:16:23: cgroup-name.sh: INFO: cgroup 'system.slice_dovecot.service' is called 'system.slice_dovecot.service'
2016-11-28 21:16:24: python.d ERROR: dovecot_localsocket unix socket '/var/run/dovecot/stats': unexpectedly disconnected
2016-11-28 21:16:24: python.d ERROR: dovecot_localsocket list index out of range
2016-11-28 21:16:24: python.d ERROR: DISABLED: dovecot/localsocket
```

And dovecot give that at the same time:
    
    Nov 28 21:16:24 server101 dovecot: stats: Error: Stats client input error: Invalid level

Since the error come when netdata start, I suspect an issue there. I couldn't find much information about this kind of error on the web. Can someone tell what is going wrong?

I'm using latest netdata and dovecot 2.2.13.

**Comment by ktsaou** [comment]
I see that netdata sends just this `EXPORT\tglobal\r\n`:  https://github.com/firehol/netdata/blob/322d10a2252d1652b3137c1abacc8a355697e1f9/python.d/dovecot.chart.py#L95

Here is what I see:

```sh
# doveadm stats dump global
reset_timestamp	last_update	num_logins	num_cmds	num_connected_sessions	user_cpu	sys_cpu	clock_time	min_faults	maj_faults	vol_cs	invol_cs	disk_input	disk_output	read_count	read_bytes	write_count	write_bytes	mail_lookup_path	mail_lookup_attr	mail_read_count	mail_read_bytes	mail_cache_hits
1480366201	0.000000	0	0	0	0.0	0.0	0.0	0	0	0	0	0	0	0	0	0	00	0	0	0	0
```

but if instead of `global` I give something dovecot does not understand:

```sh
# doveadm stats dump test
Fatal: read(/var/run/dovecot/stats) unexpectedly disconnected
```

and syslog writes:

```
Nov 28 22:51:12 box dovecot: stats: Error: Stats client input error: Invalid level
```

So, I think your dovecot does not support `global` statistics.

I am running 2.2.19 and it does.

**Comment by nicolasbadia** [comment]
Ok, I will wait for Debian to update dovecot then...
Thanks a lot for looking into it so quickly!
