### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by ricyoung** [firehol/netdata#1299]
The experimental packages installer failed.

sudo curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >  /tmp/kickstart.sh &&  bash /tmp/kickstart.sh -i netdata-all

or here

:sudo bash /tmp/kickstart.sh -i netdata-all
\

This is what it says:

-i netdata
Loading /etc/os-release ...
command 'yum' or 'dnf' is required to install packages on a 'rhel 7.3' system.

please paste your screen here

![screen shot 2016-11-29 at 11 39 21 pm](https://cloud.githubusercontent.com/assets/753937/20743814/32450e58-b68d-11e6-9542-92eed70fc16b.png)

**Comment by ktsaou** [comment]
hm... do you have `yum` or `dnf` installed?

The installer searches for it everywhere: https://github.com/firehol/netdata-demo-site/blob/8ec6fb4ae8df9d2d4efea954838343f3771cd607/install-required-packages.sh#L3

**Comment by J3K** [comment]
Temporary edit : 

EDIT THIS LINE : https://github.com/firehol/netdata-demo-site/blob/8ec6fb4ae8df9d2d4efea954838343f3771cd607/install-required-packages.sh#L376

replace it with**package_installer="install_dnf"** or _package_installer="install_yum"_ depends on what you have.

and comment out Line 378 and Line 379

**Comment by ktsaou** [comment]
@J3K this means lines 34 and 35 do not detect `yum` or `dnf`. How is that possible?
@ricyoung could you please run:

```sh
which yum
command -v yum
which dnf
command -v dfn
```

and post the output here?

**Comment by ktsaou** [comment]
found the bug and fixed it.
Please retry - it should work now.
