### ISSUE TITLE
What is "goofy roentgen"?

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1301]
With the latest master release I see the following *goofy roentgen* as a chart on some of my hosts but I have no idea what that could be. I haven't even found anything in the netdata source code, which is even more surprising.

![2016-11-30 12 22 05 screen](https://cloud.githubusercontent.com/assets/1475675/20750582/ed0d63ba-b6f7-11e6-8c45-9244ef87cbab.jpg)

Any idea?

**Comment by jurgenhaas** [comment]
Never mind, this is the name of a docker container running.

**Comment by ktsaou** [comment]
:) docker is very funny in this aspect...
