### ISSUE TITLE
Cache problems after reboot

### ISSUE THREAD

**Issue by Feeliiix** [firehol/netdata#1303]
Hello,

I have a problem with netdata. When I restart my server, netdata stops displaying the data after 40 seconds. A normal `service netdata restart` does not work. I thought it might be a cache problem and it is.
Then I remove all files from `/var/cache/netdata` and then run `service netdata restart` everything works fine again.

System info: `Linux ***.***.com 4.8.0-27-generic #29-Ubuntu SMP Thu Oct 20 21:03:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Thanks for your help,
Feeliiix

**Comment by ktsaou** [comment]
I guess latest git version of netdata and default configuration. Right?
When you say "netdata stops displaying the data after 40 seconds", what exactly do you mean? Your web browser is making requests to fetch data, but netdata responds with the same data again and again?
Have you tried any other browser? It might be a plugin interfering somehow...

If you access `http://your.netdata.ip:19999/api/v1/data?chart=system.cpu` and refresh it every a few seconds, does it respond with new data?

**Comment by Feeliiix** [comment]
Yeah, I'm using the latest git version with the default configuration.
The first 40 seconds after the reboot netdata responds with new data, but after 40 seconds this stops.
Netdata is sending the same data again and again.

**Comment by ktsaou** [comment]
So, you say that this happens only if `/var/cache/netdata` is not empty after reboot and just 40 seconds after it is started?

These seem unrelated, since the files in that directory are just read once and saved when netdata exits.

hm... I am trying to figure what could be wrong... Since netdata responds to queries when this happens, it means there is no deadlock somewhere.

Can you reproduce the problem and while it happens (i.e. charts do not refresh), run the following and post the output:

```sh
pid=$(pidof netdata); for x in /proc/$pid/task/*; do cat "${x}/status" | grep "^State:" ; done
```

**Comment by Feeliiix** [comment]
That is the output:

```
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
State:  S (sleeping)
```

**Comment by ktsaou** [comment]
hm... so it is not a deadlock...

Could you please set `debug flags = 0x00000020` in `/etc/netdata/netdata.conf` and restart netdata?

This will create `/var/log/netdata/debug.log`. It should log lines like this: https://github.com/ktsaou/netdata/blob/6cd8b76b0a1ce22f82c4fb23c19f351ee8cfe56d/src/plugin_proc.c#L79-L79

If you see lines like this, data collection in netdata works (tries to collect data). It should continue logging such lines forever. If it stops, we have an issue.

**Comment by Feeliiix** [comment]
It stops. Here is the log: https://gist.github.com/Feeliiix/358b7200303146134dfcafd109a9611f

Startup started at top of the log: 2016-11-30 21:26:05
Logging stops at the end of the file: 2016-11-30 21:26:31
Now I'm at: 2016-11-30 21:33:05

**Comment by ktsaou** [comment]
interesting.
I see that it stops at `vmstat`. Can you check that netdata has not logged `PROC thread exiting` at the `error.log`?

It should either log `PROC thread exiting` in error log, or `PROCNETDEV: calling do_proc_net_rpc_nfsd().`.

Do you mind if I add some more debug statements and give a version of netdata to run?

**Comment by Feeliiix** [comment]
Everything I can find about `thread exiting` in `error.log`:

```
2016-11-30 22:52:13: netdata: INFO: (0602@backends.c:backends_main  ):BACKEND thread exiting
2016-11-30 22:52:13: netdata: INFO: (0428@plugins_d.:pluginsd_worker):PLUGINSD: '/usr/libexec/netdata/plugins.d/fping.plugin' thread exiting
2016-11-30 22:52:14: netdata: INFO: (0428@plugins_d.:pluginsd_worker):PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' thread exiting
```

And about `calling do_proc_net_rpc_nfsd()` in the `debug.log`:
```
2016-11-30 21:50:54: netdata: DEBUG (0224@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_net_rpc_nfsd().
2016-11-30 22:52:17: netdata: DEBUG (0224@plugin_pro:proc_main      ): PROCNETDEV: calling do_proc_net_rpc_nfsd().
```

If you need more, give me more debug statements and a version of netdata to run.

**Comment by ktsaou** [comment]
Well, I just need this line: https://github.com/ktsaou/netdata/blob/a19ead105eeedcf7b01ec14a892d2e799e4dcba6/src/proc_vmstat.c#L208-L208

to become:

```c
debug(D_PROCNETDEV_LOOP, "PROCNETDEV: vdo_proc_vmstat() reading file.");
ff = procfile_readall(ff);
debug(D_PROCNETDEV_LOOP, "PROCNETDEV: vdo_proc_vmstat() reading file done.");
```

and run the test again. I suspect that something is changed in kernel 4.8 that might be blocking netdata. This line reads the file from proc. So, if it stops inside this call, the kernel pauses netdata...

**Comment by ktsaou** [comment]
If you want me to prepare a version of netdata with this, let me know.

**Comment by Feeliiix** [comment]
Hmm think all it didn't stop in this call. Log: https://gist.github.com/Feeliiix/88d45659d77f031afef092d38ad86319

But look here: https://gist.github.com/Feeliiix/88d45659d77f031afef092d38ad86319#file-debug-2-log-L166
The time jumped for 1 hour after the restart and I don't know why.

**Comment by ktsaou** [comment]
oops! how can the time jump one hour?
Did you hibernate the machine?

**Comment by ktsaou** [comment]
For sure netdata relies on timing. If the clock jumps, it might be that it calculates a wrong time to sleep between iterations...

**Comment by Feeliiix** [comment]
Ok, I will try to fix this on my server. I figured out that on startup for some seconds the time set to UTC and after some seconds the time is set to the configured timezone. In this time section netdata is started.

**Comment by Feeliiix** [comment]
Ok it works!! 

The problem was that the time who was set by `tzdata` was different to the `hwclock` time.
I now synchronized the `hwclock` time with `hwclock --systohc` and everything works.

Sorry @ktsaou... It was my fault... But thanks for your great help...

**Comment by ktsaou** [comment]
ok. no problem.
Nice it now works for you too!
