### ISSUE TITLE
new home page: http://my-netdata.io/

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1305]
Check it. It is nice.

http://my-netdata.io/

**Comment by l2isbad** [comment]
Well i think the сurrent site/design is not cool enough for such an amazing thing netdata is :)

**Comment by ktsaou** [comment]
@philwhineray @alonbl @titpetric @paulfantom @simonnagl @FedericoCeratto I am honoured to have your name at the netdata home page. I hope you allow me to do this. If you don't like it, please let me know.

Thank you guys!
