### ISSUE TITLE
Plugin for Dell Servers

### ISSUE THREAD

**Issue by alexmrhv** [firehol/netdata#1309]
A 'nice to have' feature would be to have a plugin for Dell hardware.

As was requested here is an example of ipmitool usage regarding relevant things to pull from a dell server (any of these commands without "delloem" will work on most other brands aswell):

The SEL will show any errors written to the lifecycle (in this case its just intrusion).
> [root@localhost ~]# ipmitool sel list
   1 | 11/03/2016 | 16:35:59 | Event Logging Disabled #0x72 | Log area reset/cleared | Asserted
   2 | 11/07/2016 | 06:48:19 | Physical Security #0x73 | General Chassis intrusion () | Asserted
   3 | 11/07/2016 | 06:48:24 | Physical Security #0x73 | General Chassis intrusion () | Deasserted
   4 | 11/07/2016 | 09:10:48 | Physical Security #0x73 | General Chassis intrusion () | Asserted
   5 | 11/07/2016 | 09:10:53 | Physical Security #0x73 | General Chassis intrusion () | Deasserted
   6 | 11/07/2016 | 13:48:14 | Physical Security #0x73 | General Chassis intrusion () | Asserted
   7 | 11/07/2016 | 13:48:19 | Physical Security #0x73 | General Chassis intrusion () | Deasserted
   8 | 11/08/2016 | 08:39:30 | Physical Security #0x73 | General Chassis intrusion () | Asserted
   9 | 11/08/2016 | 08:39:35 | Physical Security #0x73 | General Chassis intrusion () | Deasserted
   a | 11/30/2016 | 20:38:45 | Physical Security #0x73 | General Chassis intrusion () | Asserted
   b | 11/30/2016 | 20:38:50 | Physical Security #0x73 | General Chassis intrusion () | Deasserted

Power consumption history, updated per minute and not second.
Power consumption at the moment can be pulled using a newer version of ipmitool (i'm running 1.8.15 under CentOS7) using the command `ipmitool delloem powermonitor powerconsumption` , as the older versions return a sensor read error.

>[root@localhost ~]# ipmitool delloem powermonitor powerconsumptionhistory
Power Consumption History

>Statistic                   Last Minute     Last Hour     Last Day     Last Week

>Average Power Consumption   296 W           296 W         298 W        298 W
Max Power Consumption       306 W           306 W         720 W        720 W
Min Power Consumption       292 W           292 W          26 W         26 W

>Max Power Time
Last Minute     : Thu Dec  1 15:07:00 2016
Last Hour       : Thu Dec  1 15:07:00 2016
Last Day        : Wed Nov 30 21:40:56 2016
Last Week       : Wed Nov 30 21:40:56 2016
Min Power Time
Last Minute     : Thu Dec  1 14:13:04 2016
Last Hour       : Thu Dec  1 14:13:04 2016
Last Day        : Wed Nov 30 21:43:48 2016
Last Week       : Wed Nov 30 21:43:48 2016

Also anything else that i may have missed (like sensor data) and seems useful to you, you can find in the [ipmitool man page](https://linux.die.net/man/1/ipmitool) specifically things under the "delloem" command and generally anything else.
One thing to note is that constant access to the lifecycle may results in a possible freeze of the lifecycle controller so data pulling should be done occasionally.

**Comment by ktsaou** [comment]
ok, let's see what we can do.

Put the following as `/usr/libexec/netdata/charts.d/delloem.chart.sh`:

```sh

# update every minute
delloem_update_every=60

# order of chart at the dashboard
delloem_priority=60000

delloem_get_watt() {
    # collect data
    ipmitool delloem powermonitor powerconsumptionhistory |\
        sed -n -e "s/^\(Average\|Min\|Max\)[[:space:]]\+Power[[:space:]]\+Consumption[[:space:]]\+\([0-9]\+\).*$/SET \1 = \2/p"
}

delloem_check() {
    # return 0 if we can collect data
    # return 1 if we can't

    require_cmd ipmitool || return 1
    delloem_get_watt >/dev/null || return 1
    return 0
}

delloem_create() {
    # create the chart
    cat <<EOF
CHART sensors.dellwatt '' "Dell IPMI Power Consumption" "Watts" dell dell area $((delloem_priority)) $delloem_update_every
DIMENSION Min min absolute 1 1
DIMENSION Max max absolute 1 1
DIMENSION Average average absolute 1 1
EOF
}

delloem_update() {
    echo "BEGIN sensors.dellwatt $1"
    delloem_get_watt
    echo "END"
}
```

Then execute by hand:

```
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 delloem
```

and post here the output please.

**Comment by ktsaou** [comment]
freeipmi plugin written in C is in PR #1881

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
I have merged several changes to freeipmi plugin for netdata. It is now more compatible and it also has alarms in case IPMI reports critical sensors.

If you have high cpu on `kipmi0` process (a kernel thread), please check the [netdata wiki page](https://github.com/firehol/netdata/wiki/monitoring-IPMI#kipmi0-cpu-usage) for the fix (you need to pass a kernel parameter to lower the frequency the kernel polls the IPMI processor).
