### ISSUE TITLE
The source release should include a pre-built configure script

### ISSUE THREAD

**Issue by VinDuv** [firehol/netdata#131]
The `netdata` releases are missing the `configure` script. It should be pre-built and distributed in the source releases, for the following reasons:
 - It allows building `netdata` without installing autoconf
 - It produces better error messages if something is missing. On a system without pkg-config, `autogen.sh` doesn’t produce errors, but `configure` fails with
```
./configure: line 5030: syntax error near unexpected token `newline'
./configure: line 5030: `	PKG_CHECK_MODULES('
```
 on the other hand, a correctly pre-built `configure` will produce:
```
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full path to pkg-config.
```

Note that you can use `./autogen.sh && ./configure && make dist` to generate a source release archive  which includes the configure script.

**Comment by ktsaou** [comment]
@philwhineray can you review this suggestion please?

**Comment by mcnewton** [comment]
As a comment on this, I just did https://github.com/firehol/netdata/pull/132 to add Debian packaging, and added the configure script, but was told to remove it. In projects I work on they are always in git as well - same reasons as noted above.

If it's useful, the commit I removed is at https://github.com/mcnewton/netdata/commits/configure-scripts

Cheers!
Matthew

**Comment by mcnewton** [comment]
I forgot to note here the comments on the PR that there are two different locations to download the released version from, which I personally found confusing. Only one includes the configure script. Not enough coffee for me maybe :-)

**Comment by philwhineray** [comment]
I think the releases do contain a configure script. If you obtain the raw
package from version control (I.e github) it does/should not.

For source builds with configure go to https://firehol.org/download/netdata/
where unsigned/master gets built every git checkin. The others contain
official versioned releases which should be where the github releases page
points to.

**Comment by philwhineray** [comment]
So I have updated the README.md to make things clearer what is going on but I see that the installer script assumes it will run autogen and the [install wiki page](/firehol/netdata/wiki/Installation) assumes it is needed too, so some extra work is really required to make it seamless.

**Comment by mcnewton** [comment]
@philwhineray that update to README.md is very useful, thank you.

**Comment by philwhineray** [comment]
Think this can be closed. The installer will point you to the right place if you don't have autotools or too low a version now.
