### ISSUE TITLE
Donations Page

### ISSUE THREAD

**Issue by dikaio** [firehol/netdata#1310]
First off I'm soooo, soooo appreciative in knowing there are so many devs out there that are so much smarter than myself 😊. I would love to contribute but I'm guessing my pull requests may end up pushing the project goals back 😏. I haven't been able to find a donations page is there not one up? I'd like to contribute there if possible.

**Comment by ktsaou** [comment]
Thanks!

Have you seen this: https://github.com/firehol/netdata/wiki#can-i-help ?
We don't need money. We need help.

Documentation is behind code. We need to strengthen the community (can you setup/maintain a facebook page?). If you can code, we need more plugins, a mobile app maybe, etc.

**Comment by dikaio** [comment]
@ktsaou will dig into the code!
