### ISSUE TITLE
netdata on ephemeral nodes

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#1311]
I was wondering how the registry works in case of a multi-node application running in a autoscaling group. Mynetdata as described below does some grouping based on the registry name but its unclear how this works 
https://github.com/firehol/netdata/wiki/mynetdata-menu-item

For instance I have the following configurations for the Server and Application

Netdata Server
[global]
	hostname = ip-xxx-xxx-xxx-xxx

[registry]
    enabled = yes
    registry to announce = http://netdata.mydomain.com
    registry hostname = Netdata Server

In case of the application, for all the nodes
[global]
	hostname = ip-xxx-xxx-xxx-xxx

[registry]
    enabled = no
    registry to announce = http://netdata.mydomain.com
    registry hostname = My App

3 nodes of "My App" is running with 3 ephemeral IP's and a load balancer url. The Mynetdata menu show two links, viz. "Netdata Server" & "My App". Accessing "My App" using the load balancer URL takes me to one of the nodes.

Is there any way for me to see or access each node?

**Comment by ktsaou** [comment]
You should set hostnames like this `My App Node 1`, `My App Node 2`, etc.
The problem is the ephemeral IPs. You should somehow, inject these ephemeral IPs to a DNS server (give a hostname like `my-app-node-1` when an ephemeral IP is assigned), or let the registry know (i.e. have a script at boot/assignement of the ephemeral IP, call the registry).

Something similar has been requested in #1041.

**Comment by gamefundas** [comment]
This makes it a little difficult as we don't have a way to numerically index a auto-scaling group. And AWS doesn't provide one. So essentially the only thing that makes our nodes appear different is the IP or Hostname. If I give my nodes a meaningful name such as "Service Name - ip-xxx-xxx-xxx-xxx) then they would appear on the registry list as separate menu items but then this will end up as a very long list and at the same time we would have trouble de-registering nodes that get terminated and AWS spins off a new instance or in case of downscaling.

Looks like we will have to manually manage the menu items.

In my view this registry can be managed better using service-discovery. If Netdata supports something like Consul then the registry responsibility can be offloaded to a different module. And nodes (services tagged as "netdata") can be read by Netdata in real time to build the Menu. Any sort of ephemeral ip's, nodes unhealthy or out of service etc will be managed by Consul. A registry type configuration can help choose "Netdata" or "Consul".

This is my thought but there could be other better ways to implement this.

**Comment by ktsaou** [comment]
ok. Excuse my ignorance, but I don't have any experience with AWS or Consul.

What you say is that when AWS spawns new nodes, these are based on an image you have provided, but there is no way for you to have some kind of persistent storage for it. Everything will be created, run for some time and then shutdown. When later a new node is needed, a fresh one is started to join. There is no persistent storage at all, not even for storing a simple id.

If there is some kind of persistent storage, the solution is simple.
If there is no persistent storage at all, you are right, we need something.

**Comment by ktsaou** [comment]
I think we should do something about this.
I just don't know yet what needs to be done... I need your help to figure it out.

**Comment by gamefundas** [comment]
Have been a little busy and couldnt reply to this thread. So basically in AWS autoscaling instances, the nodes keep getting swapped often depending on changes to underlying infrastructure and application deployments. There is persistence in the form of EBS volumes which get mapped when the new instances spawn up. But thats not the problem, as we do get the netdata saved snapshots back.

What will be helpful is if Netdata can read from service-discovery the underlying nodes for each service and build the tree. Consul cli can provide this information, of all the services and their nodes/ephemeral ip's. The only problem that I still see with this is that Netdata UI probably pulls the metrics directly from the target servers. The nodes have private IP's and typically they cannot be access from outside. So DNS entries for each nodes will have to be created regardless I guess. Unless Netdata has a server that serves the metrics after talking to nodes.

Short of it is, we still need to find a better way to support this kind of architecture.

**Comment by ktsaou** [comment]
Well, the file `/var/lib/netdata/registry/netdata.public.unique.id` contains a GUID that uniquely identifies a netdata.

The whole idea, is to give a netdata a consistent GUID. So, if you have up to 10 netdata, you will need 10 GUIDs. These GUIDs are random. If your setup suddenly needs 11 netdata, you can start netdata without a file at `/var/lib/netdata/registry/netdata.public.unique.id` - the 11th netdata will generate a new one.

Then, you need to let the registry know about the IP this netdata can be found at. You can do this with a `curl` command. After you run this `curl` command, all your users that have accessed a netdata with this GUID in the past, will be able to find it at its new IP via the `my-netdata` menu.

All of the above could be executed by a script that runs at boot and shutdown on each of your nodes and could use Consul CLI, a persistent storage, or whatever.

Will this do?

**Comment by gamefundas** [comment]
And I imagine using the same server name will update or point it to the new IP. If that is the case then this might work. Will try this out.

**Comment by ktsaou** [comment]
ok, try that. The `curl` command will be tricky, so test it with 2 users (one user accesses the a netdata that changed IP, with the new IP - and the other user is able to detect this change via the `my-netdata` menu).

Once this works for you, I'll help you prepare this `curl` command.

**Comment by gamefundas** [comment]
I realized this wouldn't work in our clustered environment as access to all service nodes via IP's/Hostnames are restricted and the only way to access is through the load balancers. However the load balancer hits one of the service nodes and hence there is no means for us to view the dashboard of all operating nodes.

Creating DNS routes for each service node is lot more work and requires extra book keeping when these ephemeral nodes gets replaced by new ones.

**Comment by ktsaou** [comment]
strange setup.

So, you are saying there is no way to access a node directly even when you know its IP? How is that possible? What restricts you? Is there a firewall?

If you can access a node when you know its IP, then it is just a matter of knowing somehow that IP. I can think of a few ways to overcome this.

Can the nodes talk to each other? If yes, then one or more of them could run an nginx to proxy all the netdata for all the nodes. That nginx could be load balanced by your balancer.

Could you please explain a bit your setup?  I would really like to make this work...

**Comment by gamefundas** [comment]
I can explain to clarify the setup. All our business services are hosted in Amazon in respective vpc's and some of these services could be running as a autoscaling cluster where in service A can be configured to run on X servers where X is dynamic and varies by load throughout the day. X min is 5 and Max is 10 let's say for Service A. Now service A is exposed via a Route53 DNS which maps to a ELB (load balancer) and this load balancer keeps track of all the healthy X servers that are available to process the user request. Based on load factor the auto scaling policy in AWS will increase/decrease the underlying serves but the load balancer is smart enough to add/remove accordingly. So basically the users are only aware of Service A through the route 53 DNS entry. IP's are abstracted as they can be anything and could change in the course of time. 

We could find out the IP's by querying AWS at that moment using their API's and also see in AWS Dashboard but then the boxes still cannot be accessed for 2 reasons. 

1. Firewall policy - only the load balancers are allowed to access the servers. 

2. These IP's cannot be directly resolved in the data center the users are accessing the service. Only the route-53 DNS can be used to resolve.  This is the way the network has been configured. 

The other thing to know is that these servers in a auto scaling configuration are essentially cloned from a template. So they are exactly the same besides the IP. AWS currently doesn't provide an instance index as part of its metadata so I can't name these servers with some meaningful host names such as servicenode-1,2,3 etc. 

Nginx I thought about it but then I will end up running on every server as they are clones. If I manage to setup independently as a separate instance I won't be able to manage the dynamic Serve list. 

To me it seems like for a clustered environment like this we may need a metrics server that collects all of this centrally. And the dashboard running off that central data. We have similar setup with Stage monitor that uses Elasticsearch as backend and the Grafana Dashboard aggregates Service A data for JVM metrics. It also has details of the host name where a particular metric was logged from. 

Hope I was able to explain the setup. Feel free to probe me further on this. I would love to get this working.

**Comment by gamefundas** [comment]
Also one more thing to add, in terms of interaction with services, users are allowed to access through Route53 DNS while applications or let's say Service B running in the same or different VPC uses service discovery (consul) to talk to Service A. Both Service A and B will be registered in consul server via the consul agent so when someone asks for Service A only the healthy nodes or IP/port will serve the request. This is the level of abstraction for a service to service http communication. This is achieved by using a loadbalanced/discovery enabled consul http client. Again the other service knows nothing about the IP/server node that's processing its http request. 

We use Spring Cloud in our Microservice architecture and this setup is more of a standard these days.

**Comment by ktsaou** [comment]
thanks for taking the time to help me with this.

You can always send the metrics from all your netdata servers to one of the supported backends: https://github.com/firehol/netdata/wiki/netdata-backends and visualize them with grafana.

However, I would love to have this purely solved with netdata, without sending the metrics to a central server.

I think the load balancer cannot help us. I am not sure that DNS will either.

Is it possible to allow connections towards port 19999 on all nodes, from a **single static IP**?

If this can happen, then you could setup a server with a static IP (e.g. the grafana one?) as a proxy that could be used to access netdata on the available nodes, directly (i.e. without passing through the balancer). I mean something like this:

![image](https://cloud.githubusercontent.com/assets/2662304/21592116/4efda8de-d113-11e6-8ab5-b21e1da48900.png)

If this can be done, then it is just a matter of properly configuring that proxy when nodes start and stop.

**Comment by gamefundas** [comment]
I am not quite familiar with proxies but my understanding is they merely redirect based on rules, the client browser will see node 1,2,3 serving the request which will be blocked by the firewall. Also we don't have the means to alter the user's browser proxy settings, this is controlled by the info security teams on the organization level.

The workaround we have had so far is run a windows node (support desktop) in the same VPC and have our devops team gain temporary access to it using a support workflow and then from that machine access the nodes via a browser. Since this desktop runs within the same VPC its allowed to access the other nodes using IP addresses.

Just that this is an inconvenient method for the devops team to support and monitor production. If I misunderstood your proxy approach please pardon me.

**Comment by ktsaou** [comment]
Oh... when I said "proxy" I didn't mean `squid`. I meant a web server that when it gets a request for `http://proxy.ip/node1/` will know the current IP of `node1` and access it directly, ie.:

1. you -> proxy: `http://proxy.ip/node1/`
2. proxy -> node1: `http://node1.ip:19999/`
3. the replies back the same way: node1 -> proxy -> you

So, as far as the nodes are concerned, only the "proxy" will be accessing them. The "proxy" could also have username/password protection, so only you will be able the see the nodes.

**Comment by gamefundas** [comment]
Aha! I see what you are referring to. Some kind of Http relay server that simply translates the URL and delegates the call to the respective server, then returns the response. 

Hmmm, will have to see if there is something available around the same lines, else will need to write one. Netdata UI and the chart data, will they be able to run off  http://proxy.ip/node1/. I wonder how the node1 context will be applied to all the calls from the dashboard UI.

Also assuming these are going to be HTTP GET calls only from the UI.

**Comment by ktsaou** [comment]
This setup is pretty easy. You don't need a dedicated server for that. You can use any server that can spare running an nginx (the same nginx could also run other things - but I would suggest to be admin stuff since we are going to reload nginx when nodes start or stop).

So, here is what will happen:

1. The "proxy" server will run a shell script. We will bind this script to a port using `inetd` or `xinetd`.

2. Each node will hit the script on boot and shutdown, with something like:

   - `http://proxy.ip:port/on?key=XXXXXXXXXXXXXXXXX` (on boot)
   - `http://proxy.ip:port/off?key=XXXXXXXXXXXXXXXXX` (shutdown)

   The `key` is just something you choose, to trust the request.

   The script on the "proxy" will:

   - decide a slot (`node1`, `node2`, etc)
   - execute a `curl` command to let netdata registry know of the new URL for this node (so that your `my-netdata` menu on the netdata dashboards will work)
   - reconfigure and reload the proxy nginx to hit the node at the right IP
   - return the GUID to be used by the netdata running on the node made the request

3. On each node now, after the above `curl` command is run (on boot and shutdown), the GUID received from the proxy will be saved to `/var/lib/netdata/registry/netdata.unique.id` (and only on boot., netdata will be started).

Of course, the script run on the proxy could use consul if it can be used to fetch the node IP.

**Comment by ktsaou** [comment]
I have added to netdata functionality to allow remote databases (actually it allows a lot more, check PR #1817 ).

Under this scenario, you work like this:

1. You need a central netdata - a netdata that will not be ephemeral.
2. On each ephemeral node you configure netdata ([`/etc/netdata/stream.conf`](https://github.com/firehol/netdata/blob/master/conf.d/stream.conf)) to send all metrics to the central netdata. This is magical (you set the same API key on the central netdata and all ephemeral nodes and you are done - check PR #1817 ).
3. All your ephemeral nodes will appear at `http://central.netdata.ip:19999/host/nodeX/` where `nodeX` is their hostname.
4. You don't need to keep track of them. They will appear at the `my-netdata` menu of the central netdata automatically. Check PR #1858 .
5. The central netdata will also handle all alarms for them. It is smart enough to run alarms only when the ephemeral node is connected, streaming metrics (this is configurable at `stream.conf`).
6. The central netdata auto-cleans itself, removing all metrics of disconnected hosts after some time (also configurable at `stream.conf`).

It has a lot more features, supporting headless collectors, proxies, routing, etc. I made all these to solve monitoring for auto-scaling cloud setups, exactly like yours.

So, use it. You will love it!

(PS: This is new - I am testing it extensively for several days now, without any issues so far - please report back your experiences with it).

**Comment by ktsaou** [comment]
And I didn't mention that the ephemeral nodes are connecting to the central netdata, streaming, pushing metrics. So, you will just add a fixed configuration at the ephemeral nodes template. The ephemeral nodes will initiate all connections to the central one.

**Comment by ktsaou** [comment]
btw, PR #1875 adds support for monitoring ephemeral containers too!

**Comment by gamefundas** [comment]
@ktsaou this is fantastic, dream come true feature for me. Will try over the weekend on our lab vpc and report back the experience with this. 

Thx
Andy

**Comment by ktsaou** [comment]
nice, thanks! looking forward for your report...

**Comment by gamefundas** [comment]
@ktsaou I am having trouble with slaves ->master communication due to our AWS web proxy blocking the calls. Is there a way for me to use the Netdata master FQDN instead of the IP address as there a Route53 DNS which I could use to bypass the proxy. The DNSndirectly points to the Netdata Master node. 

The other option is for netdata to pick the no_proxy settings from the environment, which again makes it tricky as I will have to script the "no_proxy" configuration in all the slaves to make it work. Change in Netdata master IP address would then require change to all slave configurations.

**Comment by ktsaou** [comment]
slave->master communication is not HTTP, so it cannot be proxied. netdata opens a socket directly to the host and port given without using any proxy configuration.

At the `destination` you can give hostnames too. You can put multiple space separated entries too, and the first found working will be used.

If the system has multiple interfaces, you can specify the interface too, like this:

```
destination = [PROTOCOL:]HOST[%INTERFACE][:PORT] ...
```

Full example:

```
destination = tcp:master-hostname%eth0:19999 tcp:[ipv6:ip:address]%eth1:19999
```

If you use ipv6 IPs, use `[ipv6:ip:address]` (with brackets).

**Comment by gamefundas** [comment]
I think the problem is that the server is rejecting the API key. How do I configure the server to receive all requests from a key?

My steam conf for master is as follows

[xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx]
     enabled = yes
     default history = 3600
     default memory mode = save
     health enabled by default = auto

when it said [API_KEY], I imagined replacing that with the shared GUID. Am I doing this right.

**Comment by ktsaou** [comment]
Check the netdata error.log on the master.

On both master and slave do this:

```
tail -f /var/log/netdata/error.log | grep STREAM
```

If the slave manages to connect to the master you will see something like:

```
2017-03-09 09:38:52: netdata: INFO : STREAM [receive from [10.11.12.86]:38564]: new client connection.
2017-03-09 09:38:52: netdata: INFO : xxx [10.11.12.86]:38564: receive thread created (task id 27721)
2017-03-09 09:38:52: netdata: INFO : STREAM xxx [receive from [10.11.12.86]:38564]: client willing to stream metrics for host 'xxx' with machine_guid '1234567-1976-11e6-ae19-7cdd9077342a': update every = 1, history = 3600, memory mode = ram, health auto
2017-03-09 09:38:52: netdata: INFO : STREAM xxx [receive from [10.11.12.86]:38564]: initializing communication...
2017-03-09 09:38:52: netdata: INFO : STREAM xxx [receive from [10.11.12.86]:38564]: receiving metrics...
```

**Comment by ktsaou** [comment]
The possible errors on the master, rejecting communication: https://github.com/firehol/netdata/blob/master/src/rrdpush.c#L686-L733 (the lines starting with `error(`  - these will be logged to the error.log of the master).

**Comment by gamefundas** [comment]
I am unable to understand what is the difference between API_KEY and MACHINE_GUID. If I remove the [MACHINE_GUID] section it works.

**Comment by ktsaou** [comment]
ok. The API key is just used to authorise the communication between 2 netdata. If they are configured with the same API key, they can talk. Otherwise they cannot.

Machine Guids: each netdata has a unique ID. This is a random guid generated the first time a netdata starts and is saved in `/var/lib/netdata/registry/netdata.unique.id`. This is how the registry finds out that 2 URLs refer to the same netdata.

You can **optionally** create sections with machine guids in `stream.conf`, to provide default settings for each remote netdata. This is to be used in extreme cases. Let's see an example:

1. You have 3 nodes: A, B, C 
2. You have a master, D
3. You stream all metrics from A, B, C to D.
4. You decide one day, to stream all metrics to another netdata, from D to E.
5. On E you want to have a different history size of node A.

To achieve this, on E, you define the same API key with D, but you add the machine guid of A to change the history size.

It is extreme, and you probably don't have to use it for your setup.

**Comment by ktsaou** [comment]
> If I remove the [MACHINE_GUID] section it works.

You had `[MACHINE_GUID].enable = no`, so you didn't want to receive metrics for this machine.

**Comment by ktsaou** [comment]
So, it works?

**Comment by gamefundas** [comment]
Ok makes sense now. In my case I don't have to define the [MACHINE_GUID] as my requirement is to accept all with same configuration. But I see the flexibility to customize this, if needed later.

Is there a way for the Netdata nodes to appear with a Custom name other than the default host name. For example, currently all our ephemeral nodes have hostnames as ip-xxx-xxx-xxx-xxx. We cant name these differently. However if there is a way for us to tag or name our Netdata with another meaningful name such as "Service A - Host name" it will be easy to recognize in that list. Perhaps a configuration "server_name" something that the master can use from the slave to register.

**Comment by ktsaou** [comment]
You can name them on the slaves. Before starting netdata on the slaves, create a `netdata.conf` with this:

```
[global]
    hostname = XYZ
```

It will be propagated to the master. But make sure all the hosts will have unique names (e.g. `A-ip-xxx-xxx-xxx-xxx` - also I haven't tested if anything breaks with hostnames with spaces).

You can do this with a script like this (save it as `/usr/sbin/netdata-start.sh`):

```sh
#!/usr/bin/env bash
cat >/etc/netdata/netdata.conf <<EOF
# DO NOT EDIT - automatically generated by /usr/sbin/netdata-start.sh
[global]
    hostname = A-$(hostname)
EOF
exec /usr/bin/netdata "${@}"
```

Of course, add any other netdata options you need.

Then edit `/etc/systemd/system/netdata.service` and change `/usr/sbin/netdata` to `/usr/sbin/netdata-start.sh` (keep any parameters - they will passed to netdata by the script).

**Comment by gamefundas** [comment]
Pardon me. Our AWS script was incorrect, the one that populates the hostname in netdata.conf. It was defaulting to the AWS hostname when it couldn't find our service name. Fixed that everything looks good now. 

Thanks :)

**Comment by ktsaou** [comment]
ok. I would really love to know if you are happy with this solution.
It took us quite a redesign to achieve this architecture, and I would really like to know if we did right or not.

So, please use it for some time and let us know of your thoughts.

Thanks!

**Comment by gamefundas** [comment]
@ktsaou this is working great so far. Great effort in pulling this together as a solution. 
I will start upgrading many of our other servers in the cluster to send data to this central netdata and see what sort of network utilization we see. Also want to see if the central netdata gets intense with data coming from all directions. Will closely monitor the CPU, memory etc on this instance.

Given that the central Netadata will contain all the data from other instances. I am thinking this server would need a lot of memory and in order to scale we will have to use other configuration methods like proxy netdata?

**Comment by ktsaou** [comment]
If the central netdata has SSD disks, I suggest to user `memory mode = map`. This will constantly write data on disks (I measured that for each host it needs a few KB/s), but it will immediately make the RAM size irrelevant. `map` works like swap. If you have enough disk space, use it all for netdata...

I have already figured out how to lower the amount of data written with memory mode = ram to 1/3 of what is today, but this will require another refactoring.

I have [atlanta demo](http://atlanta.my-netdata.io/) running with `memory mode = map` to test it, and so far it seems good.

Keep in mind netdata with `memory mode = map` will restart instantly, since it does not need to load/save the data. It just maps the files. Also, if the server crashes, the files are there, updated.

Also, there are 2 settings that should delete the files:

```
[global]
	delete obsolete charts files = yes
	delete orphan hosts files = yes
```

So, it should auto-cleanup too.

If you are on Azure, they give on each VPS a `/dev/sdb` disk that is local SSD (very fast), but it is ephemeral (if they migrate the VPS on another physical server, the data on this drive are lost). You can use that for the cache.

**Comment by ktsaou** [comment]
I forgot: make sure you enable KSM too. This is a true memory saver.

**Comment by ktsaou** [comment]
I have setup a server on Azure that has 21 containers (one for each operating system of interest).

These 21 containers are running netdata in streaming mode (headless), and the host is running a netdata with `memory mode = map` and 48 hours of data retention for all nodes.

Check it to get an idea of the I/O (the cache directory is set on the special azure ssd drive):

http://build.my-netdata.io/

![image](https://cloud.githubusercontent.com/assets/2662304/23833216/3ffe928a-074b-11e7-936d-b2730ed2a7ca.png)

**Comment by ktsaou** [comment]
btw, hide the `iowait` dimension on the system.cpu to get the how of how much CPU netdata needs for 22 total nodes collecting data, 21 streaming them and 1 receiving them:

![image](https://cloud.githubusercontent.com/assets/2662304/23833270/ccb14a38-074b-11e7-8e06-6bdba4daf861.png)

It is ignorable. The host is actually sleeping...

**Comment by ktsaou** [comment]
I did some research on how `iowait` can be controlled.
My findings are here: https://github.com/firehol/netdata/wiki/Memory-Requirements#memory-mode--map

**Comment by ktsaou** [comment]
@gamefundas while I was testing all the above, I found a few issues which I fixed. So, I suggest to use the latest version of netdata, at least on the master node (there was a bug related to the number of hosts connected to it - I found it while restarting netdata with more than 5 slaves - it is fixed).

**Comment by gamefundas** [comment]
@ktsaou  will do.
Few more questions, forgive me if I missed it in the docs.

1. If the master goes down for some reason and comes back up, do the slaves transfer all the data on reconnect or we lose metrics for the outage period.

2. If central netdata is configured with a backend such as influxdb, will it record data for all the slaves that are sending data to it.

3. I only have 30 odd servers in my VPC so quite limited in terms of scale to test this out. At what point do we say that a single netdata server wont be enough. Any scaling options you have in mind for the future, perhaps a message broker or Redis to buffer the streams.

**Comment by ktsaou** [comment]
> If the master goes down for some reason and comes back up, do the slaves transfer all the data on reconnect or we lose metrics for the outage period.

The metrics will be lost. But, you can have multiple masters. Just space separate many of them at the `destination` config. The first responsive will be used.

> If central netdata is configured with a backend such as influxdb, will it record data for all the slaves that are sending data to it.

yes. Actually, you can't select which hosts not to send... so all or nothing...

> I only have 30 odd servers in my VPC so quite limited in terms of scale to test this out. At what point do we say that a single netdata server wont be enough.

netdata does not have any limitation and as you see it is pretty efficient in terms of CPU. With an SSD drive, I think it can easily be scaled to hundreds of servers.

netdata also supports proxies, so complex setups can be achieved.

I guess the most efficient would be to have "farms", with their master, which could also proxy all data to a larger host for archiving or probably bigger retention...

> Any scaling options you have in mind for the future, perhaps a message broker or Redis to buffer the streams.

I don't think there is need for this. The collecting netdata can maintain a small database. netdata proxies can also be "store and forward proxies" (they can have a local database too). So, there is already enough functionality in it...

The problem is that I haven't implemented anything to push old metrics (only the fresh ones are pushed). I don't see why it can't be done though if the sending netdata (collector or proxy) has a local database... It will require some work (I tried to sync clocks on connect, so this is explicitly prevented now, but it sounds doable...)

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you have any issues, just post.

**Comment by dspaceproject** [comment]
Hi @ktsaou I am having a similar architecture as above issue #1311 could you please assist me with the bootstrapping script for ephemeral nodes.

**Comment by ktsaou** [comment]
@dspaceproject it is all documented here: https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes

**Comment by dspaceproject** [comment]
@ktsaou I have done all that and it is working fine, I will be using auto-scaling to scale my ephemeral nodes up and down automatically thus my quiz.

**Comment by ktsaou** [comment]
hm... then I haven't understood the question. Could you please describe the problem a bit more?

**Comment by gamefundas** [comment]
Streaming configuration using Netdata server is the best solution for a AWS autoscaling architecture. This has helped us get around the registry problem and also stats aren’t lost in the event of nodes getting recycled. Let me know if I didn’t answer your real problem.

**Comment by dspaceproject** [comment]
@gamefundas is there a script you run so that you can monitor any autoscalled instances?

**Comment by dspaceproject** [comment]
I am using cloud formation which is an aws service, where I want to add a shell script that will install netdata automatically on instances that I will launch using the cloud formation template so that I can be able to monitor them The instances or the nodes can easily be spawned up and down depending on the load and they are behind a load balancer. pretty similar with https://cloud.githubusercontent.com/assets/2662304/23627468/96daf7ba-02b9-11e7-95ac-1f767dd8dab8.png architecture. Hope now you get it.

**Comment by gamefundas** [comment]
Netdata

**Comment by dspaceproject** [comment]
and how did you implement it?

**Comment by gamefundas** [comment]
Installation steps are documented for respective OS and physical architecture in https://github.com/firehol/netdata/wiki/Installation

For Netdata Master and Slaves configurations, you can follow
https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes

As for cloud formation you may need to reach out to AWS support. On a high level I can say that these need to be scripted in userdata section of CF template.

**Comment by dspaceproject** [comment]
Wow thanks for the info @gamefundas I am grateful.

**Comment by ktsaou** [comment]
@gamefundas thanks!
