### ISSUE TITLE
"disk_space" not working anymore

### ISSUE THREAD

**Issue by bluepuma77** [firehol/netdata#1312]
I just upgraded to the latest version of netdata and suddenly the disk space is not shown anymore. It worked fine with the version from 8 weeks ago.

Web
`disk_space.md2: chart not found on url "/api/v1/chart?chart=disk_space.md2"
`
Logs
`2016-11-30 15:38:31: 1: (sent/all = 57/37 bytes -49856065064079867904%, prep/sent/total = 0.07/0.07/0.14 ms) data: 404 '/api/v1/data?chart=disk_space.md2&format=json&points=42&group=average&options=ms|flip|jsonwrap|nonzero&after=-300&_=1480520247624'`

Has the parameter changed?

**Comment by ktsaou** [comment]
Unfortunately the space charts have changed name.
Check the dashboard. Now they follow the mount point, not the underlying device.

**Comment by ktsaou** [comment]
I am closing this.

Sorry for the inconvenience. This change was required to avoid having a few disk space charts reported with the underlying disks and other reported with their mount point (for example network filesystems do not have an underlying disk).
