### ISSUE TITLE
Run behind nginx, with URI path

### ISSUE THREAD

**Issue by TechKat** [firehol/netdata#1317]
I found out about netdata through DigitalOcean and it is an amazing app.

However, I'd like to restrict access to it through a specific URL path.

Say I have an admin panel: https://example.com/admin

If I were to go to https://example.com/admin/netdata, it'll display the dashboard, however the nginx example that I have found in the Wiki is not loading the app, rather throwing a 404 error (which I believe to be my Laravel app doing that)

Ideally, I'd like to load https://example.com/admin/netdata through Laravel to display a page, and have:
https://example.com/admin/netdata/app load the actual dashboard which I can include as an iframe.

```
upstream backend {
        server 127.0.0.1:19999;
        keepalive 64;
}
location = /admin/netdata/app {
        return 301 /admin/netdata/app/;
}
location ~ /admin/netdata/app/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://backend/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;

        return 200 'test';
}
```

The first location block appears to work fine, it is redirecting from /app to /app/, but the second location block appears to be ignored, I even don't get the 200 OK response to say 'test', it still throws a 404 Not Found.

Any ideas?

**Comment by TechKat** [comment]
Closing this as I have now found an easier solution using the following location blocks:

```
location = /admin/netdata/app {
                return 301 /admin/netdata/app/;
        }

        location ^~ /admin/netdata/app/ {
                proxy_pass http://127.0.0.1:19999/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

**Comment by sogeniusio** [comment]
Did you create a route for this?
