### ISSUE TITLE
Alarm Clear action

### ISSUE THREAD

**Issue by mo0nsniper** [firehol/netdata#1319]
Hello,

It would be good to have also a line in alarm configuration for executing a script when the alarm is Cleared.
This way we can execute a script when the alarm is triggered and have another script when the alarm is Cleared.

Thank you.

**Comment by ktsaou** [comment]
hm... this is pretty simple.
So, let's say that you want your script called `my-alarm.sh`, to be executed on the CLEAR condition of an alarm.

1. set the `exec` line of the alarm to your script. Of course, this script will be executed on all states of the alarm.
2. In this script do the following:

```sh
#!/bin/bash

# call the alarm notification script of netdata
# to take care of the notification
"${NETDATA_PLUGINS_DIR}/alarm-notify.sh" "${@}"

# remember its return value to give it back to netdata
ret=$?

if [ "${10}" = "CLEAR" ]
then
   # do whatever you need for the clear status of the alarm
fi

# let netdata know if we send an alarm notification
return $ret
```

**Comment by mo0nsniper** [comment]
Great, I think this is better than two scripts. 
Thank you.

**Comment by ktsaou** [comment]
nice!
