### ISSUE TITLE
Application stats inside docker container

### ISSUE THREAD

**Issue by ibnesayeed** [firehol/netdata#1324]
Suppose, netdata is running inside a container with `/sys`, `/proc`, and `/var/run/docker.sock` mounted inside. Another container with some application (for example MySQL) is running on the same host. How to configure/link things so that the application (in this case MySQL) stats are available in netdata?

**Comment by ktsaou** [comment]
You can configure your netdata to connect to it, via the docker network.

**Comment by ibnesayeed** [comment]
Which means (just thinking out loud):

If the connection uses Unix socket then i will have to make that socket as a volume and link the containers to use the volume-from instruction in the netdata; alternatively, the socket file can be made a volume and mounted on the hots (perhaps under /tmp), then mounted inside netdata container.

If the connection requires TCP, we will have to link the containers or run them under the same virtual network.

**Comment by ktsaou** [comment]
Unfortunately, something like that is needed.

Other options:

1. run netdata on the mysql container too.
2. run netdata on the host and give it the socket file of the containerized mysql.


BTW, I have in my todo list to allow netdata plugins enter containers to collect data, when netdata runs on the host: #474

**Comment by ibnesayeed** [comment]
Well, people who are obsessed with containerization will not like either of these two approaches because:

1. run netdata inside app container:
    * it pollutes the application (mysql in this case) container with more packages (netdata) and goes against the philosophy of one process per container
    * in some cases it might not even be feasible to amend every application container with netdata
    * it means each container will have one netdata instance and the dashboard would be collecting from as many netdata instances as there are application containers
2. run netdata on the host
    * no issues, except now the host machine is being polluted with a non-dockerized application.

The discussion on the #474 is fantastic. Here I can think of another approach that can be used by each plugin to penetrate in corresponding containers to collect data from:

Assume that we are running three containers, mysql, redis, and netdata. Assume that we have mounted the docker.sock from the host inside netdata container. This way netdata can have access to all the containers. Now mysql and redis plugins can use docker's exec interface to run desired commands inside the corresponding containers (which can be configured to match certain patterns in the container names or by feature detection as if a container can run a specif application command or not). Thought?

**Comment by ktsaou** [comment]
Something similar has been seen in the past for lxc: #167 

It is not elegant though... and it would also require a completely different solution for docker, lxc, kubernetes, etc. Each and every containers manager will be a journey to support...

**Comment by ibnesayeed** [comment]
> It is not elegant though... and it would also require a completely different solution for docker, lxc, kubernetes, etc. Each and every containers manager will be a journey to support...

Agree!

**Comment by ktsaou** [comment]
Cleaning up. I am closing this in favour of #474
