### ISSUE TITLE
ipv4.tcpsock, data-show-value-of-connections-at not working

### ISSUE THREAD

**Issue by Retrospector** [firehol/netdata#1325]
I am currently working on a Custom Dashboard which should display the current tcp connections to a couple of Servers running. Since the numbers In the legend are a bit too small when displayed on a distant screen, I wanted to extract the number of connections ans show them enlarged next to the graphs. 
As the title suggests I tried that with `data-show-value-of-connections-at="id_of_span"` but it appears not to be working in this case. I tried it with other data (CPU, Swap etc.) and there it works. 
my graph div:
```
<div
	data-netdata="ipv4.tcpsock"
	data-host="http://IP:19999/"
	data-title=" "
	data-chart-library="dygraph"
	data-width="400px"
	data-height="200px"
	data-colors="#6c71c4"
	data-after="-300"
	data-legend="no"
	data-show-value-of-connections-at="sys1-conns"
></div>
```
the span: `<span id="sys1-conns"></span>`

I'm not sure if it's a bug or if I'm just doing something wrong. I appreciate your help!
We are still in awe about netdata, superb work. It makes monitoring systems so much nicer, thanks for your work!

**Comment by ktsaou** [comment]
hm... it seems that `data-show-value-of-X-at` works only with dimension IDs. You can find the dimension ID using `http://your.netdata.ip:19999/api/v1/chart?chart=ipv4.tcpsock`. `connections` is the name of dimension `CurrEstab`.

**Comment by Retrospector** [comment]
I tried both `data-show-value-of-connections-at="sys1-conns"` and `data-show-value-of-CurrEstab-at="sys1-conns"` but the data never showed up in the span. I'll try again tomorrow and report back.

**Comment by ktsaou** [comment]
ok. try lower case too. I think javascript is always converting keys to lowercase.

**Comment by Retrospector** [comment]
I tried lowercase dimension IDs, sadly it still does not work. I attached the site I made for testing below, maybe you can test it if you have the time. (changed .html to .txt since github doesn't let me upload .html) 
[ipv4-demo.txt](https://github.com/firehol/netdata/files/639108/ipv4-demo.txt)
Thanks for your help.

**Comment by ktsaou** [comment]
hm...

ok, I have added the ability to use either `id` or `name` and I converted them to lowercase to allow javascript find them properly.

**Comment by Retrospector** [comment]
It woks now, thanks for your help and the great work with netdata!
