### ISSUE TITLE
Monitor App not based on Process Name

### ISSUE THREAD

**Issue by depraved22** [firehol/netdata#1327]
I was trying to figure out if there is an out of the box way to do this. I have a few 'mono' things installed and they don't create a proper process name output so the Name in /proc doesn't work.

It looks like this:

```
root@plex: ~# ps -ef | grep -i drone
felix 4044 1 7 09:51 ? 00:00:02 /usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser
root 4168 3911 0 09:51 pts/1 00:00:00 grep -i drone
root@plex: proc# cd 4044
root@plex: 4044# cat status
Name:	Main
State:	S (sleeping)
Tgid:	4044
Ngid:	0
Pid:	4044
```

For my other python stuff, I was able to get the process name changed, but can't seem to figure out a way in mono to get this done.

Thanks.

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf#L28

You can use something like `*/opt/NzbDrone/NzbDrone.exe*`.

**Comment by depraved22** [comment]
*chaching*

That worked as I was reading through and missed that.

Thanks for the quick reply!
