### ISSUE TITLE
config directory is not handed to plugins?

### ISSUE THREAD

**Issue by dynek** [firehol/netdata#133]
Hello,

Trying to run the netdata app in a directory which is different from the prefix I supplied when building it.
Everything works fine as I can specify the different locations in netdata.conf, however the app.plugin keeps looking for apps_groups.conf in PREFIX/netdata/etc/netdata/.

```bash
16-04-01 23:06:34: ERROR: apps.plugin: Cannot open file '//home/dynek/build/qnap/netdata/opt/netdata/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
16-04-01 23:06:34: ERROR: apps.plugin: Cannot read process groups groups
```

This path is hardcoded in src/apps_plugin.c:

```c
snprintf(filename, FILENAME_MAX, "%s/apps_%s.conf", CONFIG_DIR, name);
```

Wouldn't it make sense to also give possibility to specify the config dir location from netdata.conf?

I'll see if I can do a little something.

**Comment by ktsaou** [comment]
The environment variable `NETDATA_CONFIG_DIR` is passed to all plugins, but it seems it is ignored. If you can fix it, please make a PR, otherwise wait a bit for me to do it...

**Comment by ktsaou** [comment]
ok, I fixed it.
Thanks for reporting it.
Please close the issue, if done.
