### ISSUE TITLE
Can Not Cross-Compile ?

### ISSUE THREAD

**Issue by bradennapier** [firehol/netdata#1330]
It is complaining that files dont exist - tried all the installers, they dont appear to be there.  I also dont want python in general although i cant see anything to disable that.  Trying to compile for arm gnueabi 

make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/workspace/repos/netdata-1.4.0/plugins.d'
Making all in python.d
make[2]: Entering directory `/home/ubuntu/workspace/repos/netdata-1.4.0/python.d'
make[2]: *** No rule to make target `python-modules-installer.sh', needed by `all-am'.  Stop.
make[2]: Leaving directory `/home/ubuntu/workspace/repos/netdata-1.4.0/python.d'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/workspace/repos/netdata-1.4.0'
make: *** [all] Error 2

**Comment by bradennapier** [comment]
Is there any information aywhere on how someone may cross-compile this properly?

**Comment by bradennapier** [comment]
It would appear that a few things are wrong here

1. The source .tar.gz didnt include the files above - downloading the masster zip gave them to me 
2. The options to set the linker flags is not working.  I am epxorting UUID_LIBS yet the make file is

`UUID_LIBS = -L/lib`

So this basically wasnt meant to be cross-compiled from what I can see although I am a fairly big noob in this arena

**Comment by ktsaou** [comment]
unfortunately, me too... so if anyone knows, please help...

**Comment by bradennapier** [comment]
I figured it out actually although I havent tested it yet

**Comment by bradennapier** [comment]
So this is an ABSOLUTE mess because I was jsut adding stuff trying to fix all the various errors but it built and completed with the following.  I need to clean it up as I am sure its going to be looking at the wrong paths when run on the actual system.  It shouldn't have needed all this so I think the key was manually adding the -lz and -luuid as those were not added automatically if you need to change the flags

```
name="nd"
chain="arm-none-linux-gnueabi"
toolchain="/home/ubuntu/workspace/build/dashkit/toolchains/${chain}"
chainusr="${toolchain}/${chain}/libc/usr"
chainlib="${chainusr}/lib"
prefix="${toolchain}/bin/${chain}"

SHARED="1"
CC="${prefix}-gcc"; 
CXX="${prefix}-g++";
LD="${prefix}-ld";
AS="${prefix}-as";
AR="${prefix}-ar";
STRIP="${prefix}-strip";
RANLIB="${prefix}-ranlib";
export DESTDIR="${chainlib}/${name}"
STATIC_ZLIB_PATH="${chainlib}/zlib/lib/libz.a"
export CC CXX AR STRIP RANLIB SHARED; 
# The location of lib files on the local machine.
os_dir=/remote/Store/Common/Dash/.os
export LIBS="-L${os_dir}/lib -L/opt/arm-linux/lib -L${chainlib} -L${chainlib}/zlib -L${chainlib}/uuid"
export CPPFLAGS="-I${chainlib}/libressl/include -I${chainlib} -I${chainlib}/libressl/lib -I${chainlib}/zlib"
export LDFLAGS="-L${chainlib} -L${os_dir}/lib "
# make distclean
#autoconf

ZLIB_CFLAGS="-I${chainlib}/zlib"
ZLIB_LIBS="-L${chainlib}/zlib -lz"
UUID_CFLAGS="-I${chainlib}"
UUID_LIBS="-L${chainlib}/uuid -L${chainlib} -luuid"

export ZLIB_CFLAGS ZLIB_LIBS UUID_CFLAGS UUID_LIBS
#export PKG_CONFIG_LIBDIR="${chainlib}"

make distclean
./autogen.sh
sudo chown ubuntu:ubuntu -R *

./configure \
  --with-webdir=/remote/Store/Common/Dash/.os/www \
  --prefix="${chainlib}" \
  --with-zlib  \
  --host=arm-none-linux-gnueabi \
  --bindir=/usr/bin \
  --sbindir=/usr/sbin \
  --libexecdir=/usr/libexec \
  --libdir=/remote/Store/Common/Dash/.os/lib
make PLATFORM=arm-linux-gnueabi
make install
```

**Comment by diizzyy** [comment]
It works fine crosscompiling using OpenWRT/LEDE's toolchain / package repo.

**Comment by ktsaou** [comment]
thanks for letting us know!

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
