### ISSUE TITLE
setcap in netdata-install.sh, problem with docker image

### ISSUE THREAD

**Issue by titpetric** [firehol/netdata#1331]
The command setcap on [line 714](https://github.com/firehol/netdata/blob/master/netdata-installer.sh#L714) might be incorrect in some measure. It works, but the apps.plugin is not executable when in effect. I currently worked around by running the chown/chmod commands, which should be only done if the setcap command fails (it doesn't).

I am not familiar with it in terms of:

1. I already use SYS_PTRACE as --cap-add with netdata docker as recommended,
2. apps.plugin seems to work with chown/chmod without any additional caps

Which leaves me with the question why setcap is used if chmod/chown is a reliable way to perform the same, and if setcap is used, 1) are we missing some --cap-adds on the container, or 2) is the actual setcap missing some caps to make apps.plugin executable ("Operation not permitted" when running by hand, or when run from within netdata was not exactly what was needed here).

Please advise.

**Comment by ktsaou** [comment]
Well I see it already falls back to chown/chmod: https://github.com/firehol/netdata/blob/bf91af27976cfb634d27a1a7faa1f20067170db5/netdata-installer.sh#L714-L720

Are you sure it fails? I think it does not report a failure. It does it, but it does not work.
What I can do, is add an option to the installer, to always try chown/chmod.
Will this do?

**Comment by titpetric** [comment]
I'm sorry for not being clear.

1. setcap executes correctly (exit code 0),
2. getcap reports the same set of caps on the file,
3. when trying to execute the file as root, "operation not permitted" is the result

as soon as chown root:root is run against the file, whatever was set with 'setcap' was lost.

If anything, I'd just like some information what was intended with setcap call here. I already issued the chmod/chown commands in the Dockerfile as a fix to the issue, so the issue is more of a request for additional info.

**Comment by ktsaou** [comment]
Oh... that is easy: #157 
In short: users were complaining that setuid is a security issue and packagers were complaining that setuid is deprecated and capabilities should be used instead. So, I switched apps.plugin to use capabilities first.

**Comment by titpetric** [comment]
Ok, from what I read about it, it's a tricky kernel flags / aufs / security options on the container territory, which I will not be able to resolve faster than just by leaving the chmod/chown lines in the docker file. I suppose setcap is reasonable for manual installs as you have set it up. Thank you.

**Comment by ktsaou** [comment]
well, after some research I added to the `netdata-installer.sh` the following function:

```
iscontainer() {
    # man systemd-detect-virt
    local cmd=$(which systemd-detect-virt 2>/dev/null || command -v systemd-detect-virt 2>/dev/null)
    if [ ! -z "${cmd}" -a -x "${cmd}" ]
        then
        "${cmd}" --container >/dev/null 2>&1 && return 0
    fi

    # /proc/1/sched exposes the host's pid of our init !
    # http://stackoverflow.com/a/37016302
    local pid=$( cat /proc/1/sched | head -n 1 | { IFS='(),#:' read name pid th threads; echo $pid; } )
    local p=$(( pid + 0 ))
    [ ${pid} -ne 1 ] && return 0

    # lxc sets environment variable 'container'
    [ ! -z "${container}" ] && return 0

    # docker creates /.dockerenv
    # http://stackoverflow.com/a/25518345
    [ -f "/.dockerenv" ] && return 0

    # ubuntu and debian supply /bin/running-in-container
    # https://www.apt-browse.org/browse/ubuntu/trusty/main/i386/upstart/1.12.1-0ubuntu4/file/bin/running-in-container
    if [ -x "/bin/running-in-container" ]
        then
        "/bin/running-in-container" >/dev/null 2>&1 && return 0
    fi

    return 1
}
```

I am testing it now.
It seems to be working.

There are few very interesting findings:

1. `systemd-detect-virt` is awesome. Not only it detects containers, but it also detects VMs !
2. `/proc/1/sched` exposes the host's pid of our init ! unbelievable !

I have made PR #1477 with this.

**Comment by ktsaou** [comment]
and there was an even simpler method:

1. I added to apps.plugin arg `-v` that makes it print its version and exit with 0.
2. after `setcap`, the installer checks if apps.plugin returns with 0 if instructed to print its version and exit.

So, with this change, we 100% sure that the installer will either use a working `setcap`, or fallback to setuid to root.

@titpetric I think, you can remove your work-around.

**Comment by titpetric** [comment]
Thank you, commenting it out now
