### ISSUE TITLE
Nginx Php-FPM Configuration

### ISSUE THREAD

**Issue by apurva577** [firehol/netdata#1332]
Hello

Anyone can help me to configure netdata with Nginx and php-fpm ?

If possible then please avail nginx and php-fpm configuration for it

**Comment by ktsaou** [comment]
I think these configurations are distribution specific.

What netdata needs is the following to work:

1. for nginx, `curl 'http://localhost/stub_status'`
2. for php-fpm, `curl 'http://localhost/status?full&json'`

If you make these 2 commands return data, netdata will render its charts.

You can probably search for solutions for your distribution.

**Comment by apurva577** [comment]
Hello

I am getting the return data of mentioned 2 commands.

Can you please have look once on http://host.autotrends.in/ 

its not showing graphs. dont know why

**Comment by ktsaou** [comment]
Can you post the output you get?

**Comment by apurva577** [comment]
[root@host php.d]# curl 'http://host.autotrends.in/status?full&json'

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /status</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://host.autotrends.in/status?full&amp;json</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>
      Using the URLconf defined in <code>adengineM1.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
                ^campaign/submit/lead
                
            
          </li>
        
          <li>
            
                ^campaign/
                
            
          </li>
        
          <li>
            
                ^frizza/
                
            
          </li>
        
          <li>
            
                ^admin/
                
            
          </li>
        
          <li>
            
                ^$
                
            
          </li>
        
      </ol>
      <p>The current URL, <code>status</code>, didn't match any of these.</p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>

**Comment by apurva577** [comment]
[root@host php.d]# curl 'http://host.autotrends.in/stub_status'

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /stub_status</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>GET</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://host.autotrends.in/stub_status</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>
      Using the URLconf defined in <code>adengineM1.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
                ^campaign/submit/lead
                
            
          </li>
        
          <li>
            
                ^campaign/
                
            
          </li>
        
          <li>
            
                ^frizza/
                
            
          </li>
        
          <li>
            
                ^admin/
                
            
          </li>
        
          <li>
            
                ^$
                
            
          </li>
        
      </ol>
      <p>The current URL, <code>stub_status</code>, didn't match any of these.</p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>

**Comment by ktsaou** [comment]
No this is not the output you need. These are error pages. They both say `page not found`. This means nginx and php-fpm are not configured to serve the URLs requested.

**Comment by apurva577** [comment]
This is my nginx configuration but its without php-fpm configuration.

upstream backend {
    # the netdata server
    server 127.0.0.1:19999;
    keepalive 300;
}

server {
    # nginx listens to this
    listen 80;

    # the virtual host name of this
    server_name host.autotrends.in;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}

I did not found nginx php-fpm configuration on net. Googled alot sir.

**Comment by ktsaou** [comment]
I normally have `/etc/nginx/conf.d/status.conf` with these contents:

```
server {
    listen 127.0.0.1:80;

    location /stub_status {
        stub_status on;
    }
}
```

This should enable the nginx one, but only for `localhost`. You will not be able to fetch it from any other host (netdata will be able to get it).

For php-fpm, I am sorry, I don't know.

**Comment by alibo** [comment]
@apurva577 For php-fpm:
1. Uncomment `;pm.status_path = /status` in `/etc/php/7.0/fpm/pool.d/www.conf` (check your running php version before)

2. Add this to you nginx config file (ex: `/etc/nginx/sites-enabled/default`)
```conf
    location ~ ^/status$ {
       access_log off;
       allow 127.0.0.1;

       # - maybe you need this! (it didn't work for me without this!)
       # allow <you-server-ip>; 

       deny all;

       include fastcgi_params;
       fastcgi_pass 127.0.0.1:9000;

       # - or you can use unix socket:
       # fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
    }
```

3. Change `/etc/netdata/python.d/phpfpm.conf` if needed.

4. You can now verify it works:
```bash
curl http://127.0.0.1/status
```

More details:
https://easyengine.io/tutorials/php/fpm-status-page/

**Comment by ktsaou** [comment]
@alibo you are the best! Thanks!

**Comment by alibo** [comment]
@ktsaou You're welcome. :)

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now, but you need more help, just post.
