### ISSUE TITLE
Adding a gunicorn plugin

### ISSUE THREAD

**Issue by deltaskelta** [firehol/netdata#1334]
I want to add a gunicorn plugin. I think i can see how the plugins work but I cannot tell the best way to get any stats on the gunicorn process itself...

A few ideas i have are:

    Systemctl status gunicorn

But that doesn't give much info...I was also thinking to just get the pid and search for the process to give basic info...

Any advice?

Also. It looks like there are no tests anywhere. Should I bother writing tests?

**Comment by ktsaou** [comment]
You can add the gunicorn process name to `apps_groups.conf` https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf By doing that, netdata will provide many metrics related to the gunicorn process in the `Applications` section on the dashboard.

To get metrics specific to the operation of gunicorn, you can adapt `nginx_log` plugin to tail the gunicorn log file in real-time and provide insights for the requests served per response code: https://github.com/firehol/netdata/blob/master/python.d/nginx_log.chart.py

Both of the above, require no-cooperation from gunicorn.

I see gunicorn provides a few metrics (http://docs.gunicorn.org/en/stable/instrumentation.html) but I don't know how you can get them...

**Comment by deltaskelta** [comment]
ok thanks for the reply. 

Should I add a plugin/module for this or is it completely unnecessary? Why are there modules for some other programs instead of just adding their process names to `app_groups.conf`?

**Comment by ktsaou** [comment]
they provide somehow their own metrics, much like gunicorn does for statsd. If gunicorn has an API or a method to get these metrics (instead of just statsd) we could have a netdata plugin connect to it to fetch them and chart them.

**Comment by deltaskelta** [comment]
I see thanks for the clarification. 

I will write something for the gunicorn-logs but I ran into an issue with even seeing what is specified in the `nginx_log.charts.py` in the dashboard anywhere....

I added `netdata` user to the `adm` group so it could have read access to the logs, but I cannot see where else to go from there? Any ideas?

**Comment by deltaskelta** [comment]
nvm, it popped up eventually...after restarting the service it didnt come up, but then it magically showed up later

**Comment by deltaskelta** [comment]
I modified the plugin to fit gunicorn, but when it tried to read the conf file at python.d/gunicorn_log.conf` I get this error in the netdata logs

`2016-12-09 15:50:08: python.d ERROR: /etc/netdata/python.d/gunicorn_log.conf is not a valid configuration file`

The permissions should be correct so I cannot see why it is not reading the conf

**Comment by ktsaou** [comment]
The configuration file should be a valid YAML file.
Check it with a validator, like this: http://www.yamllint.com/

**Comment by deltaskelta** [comment]
ok it was a permissions issue, those things are always getting me....

I added the necessary conf and chart.py files in PR #1337

**Comment by ktsaou** [comment]
merged it! thanks!
