### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by C0rn3j** [firehol/netdata#1339]
There's a small typo on the project website - http://my-netdata.io/

>★ In real-time

>netdata collects thousands of metrics per server per second, with just 1% CPU utilization of a single core, **a few MB or RAM** and no disk I/O at all. View everything on stunning real-time interactive web dashboards, even when netdata is running on low-end hardware. 

should be **a few MB of RAM**

**Comment by ktsaou** [comment]
fixed. thanks!
