### ISSUE TITLE
nginx proxy with many other sites,

### ISSUE THREAD

**Issue by Night1** [firehol/netdata#1346]
Hey, I'm running a reverse proxy in my nginx setup I'm having issues getting netdata to work,
When I go to domain/netstat I do get the splash screen from netdata, but nothing more loads 

current config is:

server {
     listen 443 ssl http2;
     server_name apps.niklas.pw;
     ssl_certificate /etc/letsencrypt/live/apps/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/apps/privkey.pem;
     ssl_protocols TLSv1.2;
     ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;
     ssl_prefer_server_ciphers on;
     ssl_dhparam /etc/ssl/certs/dhparam.pem;
     ssl_stapling on;
     ssl_stapling_verify on;
     resolver 8.8.8.8 8.8.4.4 valid=300s;
     resolver_timeout 5s;
     add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

     root /var/www/apps;

     ## Service -1 ##
     location /service-1{
          rewrite /service-1/(.*) /$1 break;
          proxy_pass http://127.0.0.1:8096;
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }

     ## service-2##

          location /web {
          proxy_pass http://192.168.1.43:32400/web/;
          proxy_redirect http://192.168.1.43:32400/web/ /;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

     ## Service -2  ##
     location /service-3{
          proxy_pass http://192.168.1.43:891;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          auth_basic "Restricted";
          auth_basic_user_file /etc/nginx/.htpasswd;
     }

     location /netdata {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://127.0.0.1:19999/;

        gzip on;
        gzip_proxied any;
        gzip_types *;

     }
}

Any suggestions?

**Comment by l2isbad** [comment]
Try this https://github.com/firehol/netdata/issues/1006

**Comment by Night1** [comment]
Thank you for respone l2isbad, 

I have looked at that one and that either gives me a 404, or "File '/usr/share/netdata/web/netdata/' does not exist, or is not accessible."

**Comment by l2isbad** [comment]
Ok, does /usr/share/netdata/web/netdata/ exist? whats ur web files directory

**Comment by Night1** [comment]
/usr/share/netdata/web/netdata/  is emby netdata is in /usr/share/netdata/web/

and 

 location /netdata/ {
 rewrite ^/netdata(/.*)$ $1 break;
 proxy_pass http://localhost:19999;
   } 

that worked, no need to make it more complicated, thank you. I noticed it has been along time since i messed around in nginx.

It is a pitty that every app handles proxy differently, so that need to make own config per app :(
