### ISSUE TITLE
data parameters list?

### ISSUE THREAD

**Issue by jvantslot** [firehol/netdata#1348]
Is there a comprehensive list somewhere for the parameters available for the different data charts?

For example the 
`data-netdata="system.ipv4"` and `data-netdata="system.ram"`

as well the related parameters such as `data-dimensions` that are used in the` <div>` tags on some of the demo pages?
If not, where would they be in the code that I might start putting together a list for the wiki?

Thanks!

**Comment by ktsaou** [comment]
Documentation: https://github.com/firehol/netdata/wiki/Custom-Dashboards#adding-charts

Code: https://github.com/firehol/netdata/blob/master/web/dashboard.js
Search for `.data(` and you will find them all.

Keep in mind most of them are chart library specific.

If you would like to contribute some documentation, we would appreciate if you edit the wiki pages to add it.

Thanks!

**Comment by l2isbad** [comment]
To see description of the library specific configuration parameters you can use library documentation. Ex [daygraph library](http://dygraphs.com/options.html), [easypiechart library](https://rendro.github.io/easy-pie-chart/)

**Comment by ktsaou** [comment]
I am closing this now. If we can help somehow, just post.
