### ISSUE TITLE
Ignore/disable disk space usage for mounted iso images

### ISSUE THREAD

**Issue by hameno** [firehol/netdata#1350]
I have a PXE server which has a few different iso files mounted to access their contents via tftp. 
They are mounted using the following settings:

    /media/ISOs/ubuntu-14.04.4-desktop-amd64.iso /media/netboot/ubuntu/14.04/amd64/desktop iso9660 ro,user,loop 0 0

Netdata now warns about the usage of those mounts. Maybe that could be automatically disabled for iso9660 mounts?

**Comment by ktsaou** [comment]
Hi, you can add the paths you mount these images (e.g. `/media/netboot`) to `/etc/netdata/netdata.conf` at `exclude space metrics on paths`. Append any paths to be excluded.

**Comment by hameno** [comment]
Good to know, will use that for now. Would it also make sense to ignore iso9660 mounts by default?

**Comment by ktsaou** [comment]
yeap, I am fixing it already.
Thanks for reporting it.

**Comment by ktsaou** [comment]
Well, I did it, but I think netdata should exclude all read-only mount points from space monitoring. I am doing this now.

**Comment by ktsaou** [comment]
merged it.
