### ISSUE TITLE
trying to write a gunicorn plugin, getting error from executing command in config

### ISSUE THREAD

**Issue by deltaskelta** [firehol/netdata#1357]
I am trying to get some separate charts for different gunicorn instances so I decided to write a module for it but I am getting an error from the `Popen` command and I cannot see why this is any different from other `ExecutableService` modules...

in my conf file I have this... (I will read from PID file in the real version, just trying to get something that works first)

```
local:
  command: '/bin/ps --forest -o pid -o pmem -o pcpu -g 10763'
```

and then in the netdata error logs I see this. 

```
2016-12-12 16:48:57: python.d ERROR: gunicorn_local Executing command /bin/ps --forest -o pid -o pmem -o pcpu -g 10763 resulted in error: [Errno 2] No such file or directory
```

I can recreate the Popen error in my system python by giving it a string argument as well. Popen needs to take a list of strings...

```
1. Popen(['ls', '-l']m stdout=PIPE, stderr=PIPE) # will succeed
2. Popen('ls -l, stdout=PIPE, stderr=PIPE) # will give same error
```

I looked through the code and I do not see anything that splits the args. Is there something I am missing here? `exim` and `postfix` service seem to have the same flaw but I do not run those on my system so I cannot verify if those fail as well

**Comment by deltaskelta** [comment]
I see my initial post has an error and netdata is splitting the command into a list to pass to Popen....I still cannot see why I am getting an error when I try to run `/bin/ps` or `/bin/ls` (just running `ls` as a test to see what would happen...

Is there a reason why these commands should be failing?

**Comment by l2isbad** [comment]
i am not a programmer but it looks like a bug for me

Command goes to _get_raw_data() in **# test command and search for it in /usr/sbin or /sbin when failed** of check() funcions as as string for the first time.
And then trying to change /bin/ part to /sbin/ or /usr/sbin/ and if in both cases os.path.isfile is False it leaves base part of command with /usr/sbin

**Comment by deltaskelta** [comment]
I'm not sure why you say you are not a programmer, that was a pretty hard bug to track down... Anyway You were right, I'll look into reforming the code in the basy.py module and making a PR. Thanks for the help

**Comment by ktsaou** [comment]
hm... I am not sure why @paulfantom added this code there. netdata already sets a proper `PATH` variable of all its plugins, so this treatment should not be needed.

Anyway, since my python skills are not the best, I would really appreciate a PR...

**Comment by deltaskelta** [comment]
I changed the order of where the command is split, which makes it work...

PR 1362

I didn't feel comfortable removing the part that searches the `sbin`s because I am not that familiar with netdata code and I didn't want to break anything.

**Comment by ktsaou** [comment]
I think this is fixed now. Can we close it?
