### ISSUE TITLE
Slowness cpu iowait observed in Map mode

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#1360]
I was using the following netdata configuration on Amazon Linux RHEL CentOs based instance and for some reason CPU spikes every once in while would hit 60-80%. Some times even higher. Looking at the graphs indicated most of it had to do with iowait. This cause Nagios/Consul to take the nodes out of service. The constant flapping was becoming an issue and I had to switch to 5 sec resolution + Save mode. This solved the problem significantly. Now the only time I see a spike ~20-30% is when Netdata is starting and then things fall flat. Thought I will bring this to you attention.

Also noticed AWS reports CPU utilization differently than Netdata. The AWS charts are 30-40% lower than Netdata. Not sure if they are excluding something in their calculations.

[global]
        #hostname = NETDATA_HOSTNAME
        history = 86400
        access log = none
        disconnect idle web clients after seconds = 3600
        config directory = /etc/netdata
        cache directory = /var/cache/netdata
        log directory = /var/log/netdata
        memory deduplication (ksm) = yes
        error log = /var/log/netdata/error.log
        update every = 2
        # ram, save (the default, save on exit, load on start), map (swap like)
        memory mode = map
        # the directory where data are saved
        cache directory = /var/cache/netdata

**Comment by ktsaou** [comment]
Well, in `memory mode = map`  the kernel controls how frequently the netdata memory is saved to disk. If you don't have very fast disks (like SSDs) I wouldn't suggest to use this mode.

In `memory mode = save` there should not be any such issue. If you still see this issue in `save` mode, I suggest to examine the `disk` and `swaps` charts at the Applications section of the netdata dashboard. Something else is causing them.

**Comment by gamefundas** [comment]
Thanks @ktsaou I was trying to look deeper on this but for some reason my disk & swap charts in Applications show empty. Not sure if anything is preventing them to load.

**Comment by ktsaou** [comment]
> I was trying to look deeper on this but for some reason my disk & swap charts in Applications show empty. Not sure if anything is preventing them to load.

hm... what do you mean by "empty"? Can you post a screenshot? If there are dimensions in these charts, but all the values are zero, this could be normal.

If you run `ls -lR /usr` on this server, does it show a spike on the disk chart of the Applications?

> Also wondering if there is a breakdown of iowaits, application/user wise.

Unfortunately no. The linux kernel does not provide this info. But you can find physical disk reads/writes:

![image](https://cloud.githubusercontent.com/assets/2662304/21157372/beb02a22-c181-11e6-8998-100ef543c670.png)

and swap reads (major page faults):

![image](https://cloud.githubusercontent.com/assets/2662304/21157417/e3e75860-c181-11e6-9457-bb6c5d3b95c6.png)

**Comment by gamefundas** [comment]
Yes I did mean the values were zero. 

Its probably me getting too anxious about this one. I do see some activity later in the day today which indicates the charts are looking good. Sorry false alarm.
