### ISSUE TITLE
Systemd daemon not shown on Netdata's dashboard

### ISSUE THREAD

**Issue by yhafri** [firehol/netdata#1361]
Hi

I've a perfectly working systemd daemon.
I can start/stop it using:

```
# systemctl start my-program
# systemctl stop my-program
```

But it doesn't appear on any Netdata section.

What should i do to be able to see it on Netdata's [Memory](http://127.0.0.1:19999/#menu_users_submenu_mem;theme=slate;help=true;update_always=true) section for example?

On the same machine, the _netdata daemon_ is started as a service with _systemd_ too, and i can see it on Netdata dashboard.

My configuration:

```
$ uname -a  (ubuntu 16.10)
Linux ns352638.ip-91-121-84.eu 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

$ # netdata -v
netdata 1.4.1_master

```

**Comment by ktsaou** [comment]
Hi, you have to add your program to this file: https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf

**Comment by yhafri** [comment]
Hi Costa

I just did it, but no luck even after restarting netdata multiple times.

Here's my entry at the very bottom of _/etc/netdata/apps_groups.conf_:
`my-program: my-program`

And to double check:
```
$ ps -e | grep my-program
32357 ?        00:00:00 my-program

$  cat /proc/32357/stat
32357 (my-program) S 1 32357 32357 0 -1 4219136 20417 9714 0 0 59 10 0 0 20 0 20 0 283222128 184795136 16116 18446744073709551615 4194304 6908692 132616816232928 0 0 0 65536 528518 65536 0 0 0 17 2 0 0 0 0 0 9006528 9349345 56768464 132616816233872 132616816234282 132616816234282 132616816234800 0
```

**Comment by yhafri** [comment]
I tried again by moving the entry to the top, just after the Netdata section.
Same result :-(

**Comment by ktsaou** [comment]
Does `my-program` has a space in it?

Try:

```
myprogram: 'my-program' '*my-program*'
```

**Comment by yhafri** [comment]
Nope, there're no space in it. I've tried with:
`myprogram: 'my-program' '*my-program*'`

same result.

Is that normal that I'm only seeing two groups and nothing else? These ones:
```
root
netdata
```

See [screenshot](https://postimg.org/image/gf3gux49z/).

**Comment by yhafri** [comment]
I also tried with a process already running on my system [RabbitMQ](https://www.rabbitmq.com/):
`rabbitmq: beam.smp`

nothing shows up on the dashboard.

**Comment by l2isbad** [comment]
You should look into **Applications** (not **Users**) charts if I understand correctly what you need

**Comment by yhafri** [comment]
I checked everywhere of course.
Here's my [Application](https://postimg.org/image/bemq6wtjh/) section.

**Comment by l2isbad** [comment]
Hm, It works for me

- root@xxx[/opt/netdata/etc/netdata]grep test apps_groups.conf

`my_test_app: seq`

- root@xxx[~]nice -n 19 seq 1 1000000000

![test_app](https://cloud.githubusercontent.com/assets/22274335/21128366/c0ae1508-c13d-11e6-823b-1b7ccc02a66c.jpeg)

**Comment by yhafri** [comment]
@l2isbad which version are you using?
I've compiled the latest from source.

**Comment by l2isbad** [comment]
Latest. 
System is 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) i686 GNU/Linux

Do as in my example - do you see <your test app>  in **Applications** (when seq is running) ?

**Comment by yhafri** [comment]
Did exactly as you:

```
# grep test /etc/netdata/apps_groups.conf
my_test_app: seq

# nice -n 19 seq 1 1000000000
1
2
3
[...]
34209
34210
34211
34212
34213
34214
34215
[...]
```

My [Application](https://postimg.org/image/c8wdfd9fj/) section still the same.

**Comment by l2isbad** [comment]
> Question should i have to restart netdata every time i update /etc/netdata/apps_groups.conf?
Yes.

**Comment by yhafri** [comment]
Using netdata v1.3.1_master on a RedHat 7.2, I don't even have to touch **apps_groups.conf**. 

My systemd service shows up dynamically on the dashboard. Why?

**Comment by ktsaou** [comment]
`apps_groups.conf` has been re-worked.
You can copy your RedHat 7.2 version to the new installation.

btw, which program are you interested in?

**Comment by yhafri** [comment]
Ok I'll copy the old config to the new one and keep you informed. 
I'm interested in RabbitMQ (https://www.rabbitmq.com).
It's open source.

**Comment by yhafri** [comment]
Overwriting v1.4.1 `apps_groups.conf` with Redhat 7.2 (v1.3.1) one didn't help much.
I'm still not seeing any change on teh Dashboard.

**Question**: can this be related to `netdata-installer.sh` script?
I've used that script to install v1.4.1. But I've manually compiled the v1.3.1.
Is it possible to install the v1.4.1 without `netdata-installer.sh`? If yes, advice how to do it please.

**Comment by ktsaou** [comment]
Can you give me the line of rabbitmq when you run `ps fax`?

**Comment by yhafri** [comment]
Sorry for the delay @ktsaou.

Here are the full steps which will help you reproduce it locally:

```
$ wget https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_6/rabbitmq-server-generic-unix-3.6.6.tar.xz
$ tar xf rabbitmq-server-generic-unix-3.6.6.tar.xz
$ cd rabbitmq_server-3.6.6/
$ sbin/rabbitmq-server

              RabbitMQ 3.6.6. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /home/dummy/rabbitmq_server-3.6.6/var/log/rabbitmq/rabbit@ns343587.log
  ######  ##        /home/dummy/rabbitmq_server-3.6.6/var/log/rabbitmq/rabbit@ns343587-sasl.log
  ##########
              Starting broker...
 completed with 0 plugins.

Then:
$ ps fax
27158 pts/22   Ss     0:00  \_ -bash
expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/home/dummy/rabbitmq_server-3.6.6/var/lib/rabbitmq/mnesia/rabbit@ns343587" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
27852 ?        Ss     0:00              \_ inet_gethost 4
27853 ?        S      0:00                  \_ inet_gethost 4

$ ps auxwww | grep rabbitmq
dummy   27571  0.0  0.0  13712  1888 pts/22   S+   17:10   0:00 /bin/sh -e sbin/rabbitmq-server
dummy   27669  1.4  0.5 4398228 86616 pts/22  Sl+  17:10   0:04 /opt/erlang/R16B03-tachyon/erts-5.10.4/bin/beam.smp -W w -A 128 -P 1048576 -t 5000000 -stbt db -zdbbl 32000 -K true -B i -- -root /opt/erlang/R16B03-tachyon -progname erl -- -home /home/dummy -- -pa /home/dummy/rabbitmq_server-3.6.6/ebin -noshell -noinput -s rabbit boot -sname rabbit@ns343587 -boot start_sasl -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/home/dummy/rabbitmq_server-3.6.6/var/log/rabbitmq/rabbit@ns343587.log"} -rabbit sasl_error_logger {file,"/home/dummy/rabbitmq_server-3.6.6/var/log/rabbitmq/rabbit@ns343587-sasl.log"} -rabbit enabled_plugins_file "/home/dummy/rabbitmq_server-3.6.6/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/home/dummy/rabbitmq_server-3.6.6/plugins" -rabbit plugins_expand_dir "/home/dummy/rabbitmq_server-3.6.6/var/lib/rabbitmq/mnesia/rabbit@ns343587-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/home/dummy/rabbitmq_server-3.6.6/var/lib/rabbitmq/mnesia/rabbit@ns343587" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```

I'm suspecting that the _net-installer.sh_ has something to do with my issue. As showed in my screenshot (see above), i'm only seeing root and netdata users and nothing else in the dashboard.

**Comment by ktsaou** [comment]
The latest version of netdata supports rendering systemd services (check: http://london.my-netdata.io/#menu_services;theme=slate;help=false)  and also has a nasty bug fixed in apps.plugin that prevented a few applications from being shown under certain conditions.

Please try the latest version of netdata.

I am closing this now. If you still have an issue, please post to help us find the issue and fix it.

Thanks!

**Comment by yhafri** [comment]
Hi @ktsaou 
Did a fresh install on Ubuntu 16.04 with the latest netdata from trunk. Same issue: only 02 processes are displayed as you can see.
<img width="1127" alt="netdata-ubuntu16_04" src="https://cloud.githubusercontent.com/assets/23661134/22654874/7e9774c6-ec8e-11e6-936b-71b29ebdf5ba.png">

**Comment by ktsaou** [comment]
Do you have errors in `/var/log/netdata/error.log`?

**Comment by yhafri** [comment]
[error.log.txt](https://github.com/firehol/netdata/files/755795/error.log.txt)

**Comment by ktsaou** [comment]
To is totally strange.

1. become user netdata

```sh
su -s /bin/bash netdata
```

2. check the /proc filesystem

```sh
# show everything under /proc
ls -l /proc

# check pin 1
ls -l /proc/1/
```

Could you please post the output?

**Comment by yhafri** [comment]
```
$ whoami
netdata

$ ls -l /proc
total 0
dr-xr-x---  7 netdata root     0 Feb  7 21:21 515
dr-xr-x---  7 netdata root     0 Feb  7 21:21 572
dr-xr-xr-x  2 root    root     0 Feb  7 21:21 acpi
-r--r--r--  1 root    root     0 Feb  7 21:21 buddyinfo
dr-xr-xr-x  4 root    root     0 Feb  7 21:21 bus
-r--r--r--  1 root    root     0 Feb  7 21:21 cgroups
-r--r--r--  1 root    root     0 Feb  7 21:21 cmdline
-r--------  1 root    root 22624 Feb  7 21:21 config.gz
-r--r--r--  1 root    root     0 Feb  7 21:21 consoles
-r--r--r--  1 root    root     0 Feb  7 21:21 cpuinfo
-r--r--r--  1 root    root     0 Feb  7 21:21 crypto
-r--r--r--  1 root    root     0 Feb  7 21:21 devices
-r--r--r--  1 root    root     0 Feb  7 21:21 diskstats
-r--r--r--  1 root    root     0 Feb  7 21:21 dma
-r--r--r--  1 root    root     0 Feb  7 21:21 drbd
dr-xr-xr-x  2 root    root     0 Feb  7 21:21 driver
-r--r--r--  1 root    root     0 Feb  7 21:21 execdomains
-r--r--r--  1 root    root     0 Feb  7 21:21 fb
-r--r--r--  1 root    root     0 Feb  7 21:21 filesystems
dr-xr-xr-x 12 root    root     0 Feb  7 21:21 fs
dr-xr-xr-x  4 root    root     0 Feb  7 21:21 ide
-r--r--r--  1 root    root     0 Feb  7 21:21 interrupts
-r--r--r--  1 root    root     0 Feb  7 21:21 iomem
-r--r--r--  1 root    root     0 Feb  7 21:21 ioports
dr-xr-xr-x  2 root    root     0 Feb  7 21:21 ipmi
dr-xr-xr-x 36 root    root     0 Feb  7 21:21 irq
-r--r--r--  1 root    root     0 Feb  7 21:21 kallsyms
-r--r--r--  1 root    root     0 Feb  7 21:21 key-users
-r--------  1 root    root     0 Jan  8 11:22 kmsg
-r--r--r--  1 root    root     0 Feb  7 21:21 loadavg
-r--r--r--  1 root    root     0 Feb  7 21:21 locks
-r--r--r--  1 root    root     0 Jan  8 11:22 mdstat
-r--r--r--  1 root    root     0 Feb  7 21:21 meminfo
-r--r--r--  1 root    root     0 Feb  7 21:21 misc
lrwxrwxrwx  1 root    root    11 Feb  7 21:21 mounts -> self/mounts
dr-xr-xr-x  2 root    root     0 Feb  7 21:21 mpt
-r--r--r--  1 root    root     0 Feb  7 21:21 mtd
-rw-r--r--  1 root    root     0 Feb  7 21:21 mtrr
lrwxrwxrwx  1 root    root     8 Feb  7 21:21 net -> self/net
-r--r--r--  1 root    root     0 Feb  7 21:21 pagetypeinfo
-r--r--r--  1 root    root     0 Feb  7 21:21 partitions
dr-xr-xr-x  3 root    root     0 Feb  7 21:21 scsi
lrwxrwxrwx  1 root    root     0 Jan  8 11:22 self -> 572
-r--------  1 root    root     0 Feb  7 21:21 slabinfo
-r--r--r--  1 root    root     0 Feb  7 21:21 softirqs
-r--r--r--  1 root    root     0 Feb  7 21:21 stat
-r--r--r--  1 root    root     0 Jan  8 11:22 swaps
dr-xr-xr-x  1 root    root     0 Jan  8 11:22 sys
--w-------  1 root    root     0 Feb  7 21:21 sysrq-trigger
dr-xr-xr-x  2 root    root     0 Feb  7 21:21 sysvipc
-r--r--r--  1 root    root     0 Feb  7 21:21 timer_list
dr-xr-xr-x  4 root    root     0 Feb  7 21:21 tty
-r--r--r--  1 root    root     0 Feb  7 21:21 uptime
-r--r--r--  1 root    root     0 Feb  7 21:21 version
-r--------  1 root    root     0 Feb  7 21:21 vmallocinfo
-r--r--r--  1 root    root     0 Feb  7 21:21 vmstat
-r--r--r--  1 root    root     0 Feb  7 21:21 zoneinfo

$ ls -l /proc/1/
ls: cannot access '/proc/1': No such file or directory
```

**Comment by ktsaou** [comment]
hm... you are running something that prevents netdata from reading `/proc`. Are you using grsecurity or something exotic?

**Comment by yhafri** [comment]
@ktsaou maybe I've missed something, but you think the netdata user can't access /proc.

From the above, all good to me. 

/proc/1 simply doesn't exist.

Also, I'm not using grsecurity or anything like that. 

Can you clarify please?

**Comment by ktsaou** [comment]
ok.

1. Your proc filesystem has only PIDs 515 and 572 (which are owned by user `netdata`). This is not normal. There should be dozens (if not hundreds) of PIDs running.
2. If you check the contents of `/proc/515/status` you will see that PPID is 1 (it is not shown above, but I am sure it will, since `apps.plugin` complains about it). This means that PID 1 exists, but it is not accessible by netdata.

So, your `/proc` filesystem is somehow hidden from user `netdata`.

I have seen in this past with `grsecurity`. If `uname -a` has `grs` in it, this is the case (your kernel has `grsecurity` enabled). If this is the case, check these:

https://github.com/firehol/netdata/issues/1110#issuecomment-254076604

https://github.com/firehol/netdata/issues/502#issuecomment-225652598

https://github.com/firehol/netdata/issues/434#issuecomment-220832359 (I don't recomment this)

If your kernel does not have `grsecurity`, then something else is preventing user `netdata` from reading `/proc`.

In general `ls -l /proc` run as `root` and user `netdata` should be the same.

**Comment by ktsaou** [comment]
> Linux ns352638.ip-91-121-84.eu 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

and I just saw your kernel has `grs` in it. So you run `grsecurity`.

**Comment by yhafri** [comment]
I'll try to fix that. Thank you
