### ISSUE TITLE
No network information with grsecurity

### ISSUE THREAD

**Issue by smithygotlost** [firehol/netdata#1366]
Using centos 7.2.1511 and the latest netdata im unable to get half the ammount of information any of your servers are showing..

Is there anything im missing ?

**Comment by rlefevre** [comment]
Maybe it could be useful if you detail some statistics you expect to be there and are not, in regard to your system details?

**Comment by smithygotlost** [comment]
Network usage mainly

**Comment by rlefevre** [comment]
I'm just trying to help there. Network base stats are from `/proc/net/dev`, maybe copy/paste what you have there, it could help.

**Comment by ktsaou** [comment]
Is there anything special about your kernel? Can you post:

```sh
uname -a
```

In many cases, a special kernel with enabled `grsecurity` or other exotic security mechanism prevents netdata from collecting all the information it needs.

A quick check is to stop netdata and run it as root, by hand:

```sh
# stop netdata
service netdata stop || systemctl stop netdata || killall netdata

# make sure web files are owned by root
chown -R root:root /usr/share/netdata/web

# run it as root
/path/to/netdata -D -u root
```

Does it work better now?

To revert the changes back, press `Control-C` and run: 

```sh
# make sure web files are owned by netdata
chown -R netdata:netdata /usr/share/netdata/web /var/lib/netdata

# start netdata
service netdata start || systemctl start netdata || /usr/sbin/netdata
```

**Comment by smithygotlost** [comment]
Thank you Ktsaou, Yes running as root solved that issue and now displays everything

How can i fix this as a perm thing ?

**Comment by ktsaou** [comment]
`uname -a` ?

**Comment by smithygotlost** [comment]
Linux 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ktsaou** [comment]
This is what I thought: `grs` stands for `grsecurity`.

Here are some leads:

https://github.com/firehol/netdata/issues/1110#issuecomment-254076604

https://github.com/firehol/netdata/issues/502#issuecomment-225652598

https://github.com/firehol/netdata/issues/434#issuecomment-220832359 (I don't recomment this)

**Comment by smithygotlost** [comment]
Thank you again Ktsaou, i'm really greatful for your help. If this is a GRSecurity issue is there any cause for concern by bypassing this security just for Netdata ??

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
