### ISSUE TITLE
Disk stats (usage, etc.) not reported if /proc/diskstats doesn't exist

### ISSUE THREAD

**Issue by Matoking** [firehol/netdata#1369]
I have a VPS running CentOS 7 as a guest under an OpenVZ virtualizer. Since netdata relies on /proc/diskstats for various disk statistics, my netdata instance running under this VPS can't report anything about disk besides Total Disk I/O. No block devices exist under a OpenVZ guest, and as such /proc/diskstats doesn't exist.

df command still reports file system usage as normal. For example:
```
$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/simfs     120586240 24654356  95931884  21% /
devtmpfs         1572864        0   1572864   0% /dev
tmpfs            1572864        0   1572864   0% /dev/shm
tmpfs            1572864      900   1571964   1% /run
tmpfs            1572864        0   1572864   0% /sys/fs/cgroup
tmpfs             314576        0    314576   0% /run/user/1000
tmpfs             314576        0    314576   0% /run/user/0
```

Other than that, I haven't found anything under /proc that could be used to get the same details as what /proc/diskstats provides. /proc/user_beancounters exists and so does /proc/vz, but /proc/bc doesn't exist, which seems to be OpenVZ's newer interface for various OpenVZ guest related statistics. Furthermore, I've read there could also be a /proc/vz/vzaquota file with disk usage statistics, but on my VPS it's empty (could be a configuration error on my VPS provider's part).

**Comment by ktsaou** [comment]
Interesting... this is the first time I see OpenVZ and Virtuozzo.

Do you have `/proc/self/mountinfo`?
If yes, you should at least have disk space monitoring.

**Comment by ktsaou** [comment]
I found that if `/proc/diskstat` is not there, disk space charts are not shown either.
I just updated netdata to show disk space charts in this case.
Will merge in a while (the issue will be closed automatically when this is merged).

**Comment by Matoking** [comment]
The disk usage charts show up ( /, /dev, /dev/shm, /run ), but no actual data is generated.

**Comment by ktsaou** [comment]
> The disk usage charts show up ( /, /dev, /dev/shm, /run ), but no actual data is generated; the charts remain empty.

hm... The fact that the charts are shown, means it managed to read `/proc/self/mountinfo`. Then netdata does a `statvfs()` for each disk to find its space usage: https://github.com/ktsaou/netdata/blob/302ea6ecbb032b0b782dfa4415d8aaf32b8f797a/src/proc_diskstats.c#L177-L180

If `statvfs()` fails it should log `Failed statvfs() for ...` at `/var/log/netdata/error.log`.

Do you have any such logs?

**Comment by Matoking** [comment]
/var/log/netdata/error.log is filled with different errors, but nothing related to statvfs

**Comment by ktsaou** [comment]
Could you please post it here?

**Comment by Matoking** [comment]
[netdata_error.txt](https://github.com/firehol/netdata/files/650217/netdata_error.txt)

**Comment by ktsaou** [comment]
hm... I don't see anything about disks either.
Keep in mind that you have to setuid to root `apps.plugin`. It seems that virtuozzo does not support linux capabilities, so it cannot read `/proc/<pid>/io`. You can run:

```sh
chmod 4755 /usr/libexec/netdata/plugins.d/apps.plugin
```

the installer already does this if `setcap` fails, but it seems that under virtuozzo `setcap` does not fail, but it does not work either: https://github.com/firehol/netdata/blob/892a8114054404dab69a8094f879fe2c715d289a/netdata-installer.sh#L714-L720

Regarding the disk space charts, could you please post a screenshot of one such chart? There are 2-3 different cases for "empty" and their image will help me understand which one it is.

**Comment by ktsaou** [comment]
updated the commands to be run (a `chown` is needed too).

**Comment by Matoking** [comment]
A screenshot of the empty disk usage chart

![netdata_empty_chart](https://cloud.githubusercontent.com/assets/959667/21161007/a9d09bba-c18f-11e6-843f-e71e1d529ddf.png)

**Comment by ktsaou** [comment]
and the URL on your browser is?

**Comment by ktsaou** [comment]
oh... I just want the path, not the host/domain

**Comment by ktsaou** [comment]
or, let us do this: Could you please keep only the URL up to the port, like `http://your.netdata.ip:19999/` and see if it refreshes now?

**Comment by ktsaou** [comment]
I see that `simfs` and it looks strange... What is `simfs`?

http://anonexp.blogspot.gr/2013/01/simfs-openvz-container-filesystem.html

hm... I am not sure it supports `statvfs()`... let me check something...

**Comment by ktsaou** [comment]
Can you do this: https://github.com/firehol/netdata/issues/1255#issuecomment-261668100
and give me the output?

This little program tests that `statvfs()` works on your system.

**Comment by Matoking** [comment]
I'm accessing the netdata instance over HTTP on a different port other than 19999. I checked the incoming responses, and I'm getting them for both disk_inodes and disk_space. All of the value tuples are (null, null, null), however.

I've read a bit and I've only read about df and stat being used to read the disk usage. It should also be noted that there isn't a file called /dev/simfs.

**Comment by Matoking** [comment]
I ran the provided test program and got the following output:

```
'/': STATVFS: f_frsize=4096 f_bsize=4096 f_bavail=23914297 f_blocks=30146560 f_bfree=23914297 
'/': BYTES  avail=23914297, used=6232263, reserved_for_root=0
```

**Comment by ktsaou** [comment]
I found it. It is netdata fault. Since `/proc/diskstat` does not exist, netdata does a single iteration and then gives up on disk stats.
I am preparing a fix now.

**Comment by Matoking** [comment]
Thanks for the help, I'll check back on this issue tomorrow.

**Comment by ktsaou** [comment]
Fixed it: https://github.com/firehol/netdata/pull/1371
Merged it already.
