### ISSUE TITLE
Missing capabilities to monitor other processes

### ISSUE THREAD

**Issue by remram44** [firehol/netdata#1374]
netdata doesn't seem to be able to report some data about other processes (such as network and disk usage, though global usage is available).

I had to give more capabilities to `apps.plugin` for this to work (you can see when):

<img src="https://cloud.githubusercontent.com/assets/426784/21169128/79a7dc94-c187-11e6-8a13-3b58438a9c48.png">

I'd like to know what the precise required capabilities are, so I can set it up in the most secure way. It is probably worth adding some `setcap` calls to the installer as well.

**Comment by remram44** [comment]
Currently nothing short of `cap_dac_read_search,cap_sys_ptrace+ep` seems to do the trick... that's quite a lot of capabilities 😿

**Comment by ktsaou** [comment]
Hi, 

here they are: https://github.com/firehol/netdata/issues/157#issuecomment-205080520
and the installer sets them, and fallbacks to setuid to root: https://github.com/firehol/netdata/blob/322d10a2252d1652b3137c1abacc8a355697e1f9/netdata-installer.sh#L714-L720

How did you install it?
If you didn't install it as root, it could not do it.

**Comment by remram44** [comment]
> If you didn't install it as root, it could not do it.

Oh this is definitely what happened. Are those really necessary? `cap_sys_ptrace` allows netdata to take over any process, and from there the whole system.

**Comment by ktsaou** [comment]
Well, this `setcap` is not applied to netdata. It is applied to `apps.plugin` only. This plugin performs a hard-coded function of reading most files in `/proc`. netdata never instructs it what to do. It is a one-way communication from `apps.plugin` to netdata. So, I think it is pretty safe to do it.

Check https://github.com/firehol/netdata/issues/157#issuecomment-205080520 . You will see why without this, `apps.plugin` is limited.

**Comment by remram44** [comment]
This looks good! Perhaps it could be added to the FAQ? "My netdata doesn't report per application net/disk usage?" I'm sure other people install without root and don't know about the missing capabilities 😉

**Comment by ktsaou** [comment]
Done: https://github.com/firehol/netdata/wiki/Apps-Plugin#apps-plugin-is-missing-information

Thanks!
