### ISSUE TITLE
How long does netdata store metrics data? Does it collect those even when nobody is looking at the page

### ISSUE THREAD

**Issue by manuelgu** [firehol/netdata#1376]
Hey!

1. How long back in time does netdata store its metric values?
2. Does it collect the data even when nobody is watching the monitoring page?

**Comment by ktsaou** [comment]
Hi,

1. Check this: https://github.com/firehol/netdata/wiki/Memory-Requirements
2. Yes, of course

It can also archive its metrics for long-term storage to `graphite` or `opentsdb`: https://github.com/firehol/netdata/wiki/netdata-backends

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
