### ISSUE TITLE
select data partition/directory shown in apps.preads

### ISSUE THREAD

**Issue by baoboa** [firehol/netdata#1377]
from what i guess apps.preads and apps.pwrites are only monitoring /dev/sda , i didn't find any config file for it, i want to monitor apps accessing /dev/sd* , is it possible via config or is it an enhancement ?

thanks for this project anyway.

**Comment by ktsaou** [comment]
`apps.preads` and `apps.pwrites` are the reads and writes made by processes on any disk.
This is reported by the kernel using `/proc/<pid>/io`. Values in these files are not restricted to a specific disk.

- lines `rchar` and `wchar` on these files are logical reads and writes.
- lines `read_bytes` and `write_bytes` are physical reads and writes.

all the above, specific to this process id, on all disks combined.

**Comment by baoboa** [comment]
i was confused  because i don't see much activity in app.pread compare to disk /dev/sdb which host the raid, i will check my configuration. 

thanks
