### ISSUE TITLE
Forward Netdata's data to KAfka

### ISSUE THREAD

**Issue by RiseEarly** [firehol/netdata#1380]
I would first like to thank and appreciate you for the immediate responses and support you have been providing us. We have taken Netdata into our product now, and started using this for monitoring all the devices.

Question:
Today, we see it is possible to push alarms from netdata to Kafka.
But is there a similar option for pushing Netdata's data, at frequent intervals to a kafka topic.

If this is already there, can you please point us out there ??

**Comment by ktsaou** [comment]
There is graphite and opentsdb support: https://github.com/firehol/netdata/wiki/netdata-backends

It is relatively easy to add more backends: https://github.com/firehol/netdata/wiki/netdata-backends#adding-more-backends

So, if you know basic C, you can format the messages to send them to kafka.

I would appreciate a PR if you do...

**Comment by RiseEarly** [comment]
Yep thanks for the info, we will do this!!

**Comment by divgwd** [comment]
Hi,
I wanted to know where to edit the Makefile to add the linking libraries needed by the kafka client .

**Comment by ktsaou** [comment]
Normally, these go to autoconf `configure.ac`: https://github.com/firehol/netdata/blob/master/configure.ac

You could add a switch to enable kafka, like this: https://github.com/firehol/netdata/blob/4d27d2b3a94ce17e454e6e38c9b9e8e9dd368e58/configure.ac#L56-L60

and once this is enabled by the user, check that kafka libraries are available, like this: https://github.com/firehol/netdata/blob/4d27d2b3a94ce17e454e6e38c9b9e8e9dd368e58/configure.ac#L158-L172

So, you have modified the backends code in netdata to use a kafka SDK? Which one?
This is quite some change in `backends.c`. Would you like me to review it?

**Comment by divgwd** [comment]
Hi ,
yes, I'd want you to review it :).
I am using librdkafka as my client driver ( https://github.com/edenhill/librdkafka )
but for now I am unable to compile the code.I have added the switches and also the libraries needed by kafka.
changes in the configure.ac
````
AC_ARG_ENABLE(
        [plugin-kafka],
        [AS_HELP_STRING([--enable-plugin-kafka], [enable kafka plugin])],
        ,
        [enable_plugin_kafka="no"]
)

if test -z "${RT_LIBS}"; then
        AC_CHECK_LIB(
                [rt],
                [clock_gettime],
                [RT_LIBS="-lrt"],
                [echo "Error! You need to have librt around."]
        )
fi

test -z "${RT_LIBS}" && AC_MSG_ERROR([rtlib required but not found])
        AC_DEFINE([RT_LIB_DEFINE], [1], [rtlib settings])
        OPTIONAL_RT_CLFAGS="${RT_CFLAGS}"
        OPTIONAL_RT_LIBS="${RT_LIBS}"

if test "${enable_plugin_kafka}" = "yes"; then
        PKG_CHECK_MODULES(
                [KAFKA],
                [lrdkafka],
                [lz],
                [LIBS="-lpthread"],
        )       
        test -z "${KAFKA_LIBS} -L/usr/local/lib" && AC_MSG_ERROR([lrdkafka lz lpthread lrt required but not found])
        AC_DEFINE([INTERNAL_PLUGIN_KAFKA], [1], [kafka plugin settings])
        OPTIONAL_KAFKA_CLFAGS="${KAFKA_CFLAGS} -I/usr/local/include/"
        OPTIONAL_KAFKA_LIBS="${KAFKA_LIBS} -L/usr/local/lib/"
fi


AC_SUBST([OPTIONAL_RT_CLFAGS])
AC_SUBST([OPTIONAL_RT_LIBS])
AC_SUBST([OPTIONAL_KAFKA_CLFAGS])
AC_SUBST([OPTIONAL_KAFKA_LIBS])

```

in the src/Makefile
```
KAFKA_CFLAGS=
KAFKA_LIBS=
OPTIONAL_KAFKA_CLFAGS= -I/usr/local/include/
OPTIONAL_KAFKA_LIBS= -L/usr/local/lib/

```
when I run netdata-installer.sh
I see
```checking for clock_gettime in -lrt... yes
checking for UUID... yes
checking for KAFKA... no
checking for ZLIB... yes
```
can you tell me where am going wrong ??

**Comment by ktsaou** [comment]
Hm... I am not such an expert on autoconf to find it like that.
If you make a PR, I could check it out and try to fix it (it is a try and fail loop for me)...

**Comment by divgwd** [comment]
Hi,
Thank you  for your inputs :) , did a basic testing to push netdata's data into kafka , it's working .I wanted to know if it's possible to disable certain metrics while pushing the data ?? and also if it's possible to change the format of the data??

**Comment by zeleznikm** [comment]
> I wanted to know if it's possible to disable certain metrics while pushing the data ??

This would be another great enhancement for me...

**Comment by ktsaou** [comment]
> if it's possible to disable certain metrics while pushing the data

The main problem with that is not the filtering itself, but the management of it (i.e. the configuration that has to be parsed and maintained to allow it). I think these databases already provide such functionality. Check: https://github.com/firehol/netdata/issues/1247#issuecomment-263241870

> if it's possible to change the format of the data

change the format? such as?

**Comment by RiseEarly** [comment]
Changing the format to JSON ???

Regards,
~Ramya

________________________________

**Comment by ktsaou** [comment]
ah! ok. Sending JSON is pretty easy. I guess however that this might also require HTTPS and parsing JSON responses back. These need some work... (linking against libcurl and have a JSON parser for C).

**Comment by divgwd** [comment]
Hi,
We are actually managing many data centres and taking only needed metrics to our local data store for proactive monitoring of the managed data centres . We are trying to push the data from netdata into kafka directly , for this we have added a backend (like graphite and opentsdb), now the data pushed is a string but we needed a json object as the output data format which goes into kafka,is this possible ? Also, if there is  filtering mechanism based on the netdata config file which could only send data for specified metrics only? where should we be adding that?
Thank You in advance :)

**Comment by ktsaou** [comment]
Check this: https://github.com/ktsaou/netdata/blob/e0acd981b994f8eddd1f6260f5596273b5419541/src/backends.c#L330-L333

This loop walks through all the charts and calls the `formatter` function for each chart/dimension to append them to `BUFFER b`. Filtering can be done there.

If your JSON is a simple `name:value` object, you can also filter the metrics at the formatter function. So, you can add a formatter like this: https://github.com/ktsaou/netdata/blob/e0acd981b994f8eddd1f6260f5596273b5419541/src/backends.c#L59-L66

The formatter can be selected from netdata settings like that: https://github.com/ktsaou/netdata/blob/e0acd981b994f8eddd1f6260f5596273b5419541/src/backends.c#L186-L207

And the response send by kafka can be parsed like that: https://github.com/ktsaou/netdata/blob/e0acd981b994f8eddd1f6260f5596273b5419541/src/backends.c#L97-L112

As you can see, the backends logic is already modular. Adding more backends is not that hard.

**Comment by divgwd** [comment]
Hi,
Is it possible to add all metrics data at a shot into the buffer??

**Comment by ktsaou** [comment]
> Is it possible to add all metrics data at a shot into the buffer??

hm... I don't really get the question... Can you provide a few more details?

**Comment by divgwd** [comment]
https://github.com/ktsaou/netdata/blob/e0acd981b994f8eddd1f6260f5596273b5419541/src/backends.c#L330-L333

This loop walks through all the charts and calls the formatter function for each chart/dimension to append them to BUFFER b. 
so can we append all the metrics to the buffer b at one single shot??
instead of the loop?

**Comment by ktsaou** [comment]
no. this is the only way in `C`: loop through all of them and call the formatter to append them.
They will be send in one shot to the backend server, but you have to loop through them in `C` to create the buffer to be send.

Why this loop bothers you?

**Comment by ktsaou** [comment]
I am closing this now, but if there is something pending, please post and I'll re-open it.

**Comment by divgwd** [comment]
Hi,
I am trying to compile the latest netdata with kafka backend using librdkafka as the driver ,but it fails as the library fails to link to a non standard path .
below is the older compilation output:
`gcc     -I/usr/local/include    -O3 -pthread   -o netdata appconfig.o avl.o backends.o clocks.o common.o daemon.o dictionary.o eval.o global_statistics.o health.o log.o main.o plugin_checks.o plugin_idlejitter.o plugin_nfacct.o plugin_tc.o plugins_d.o popen.o sys_fs_cgroup.o procfile.o proc_self_mountinfo.o registry.o rrd.o rrd2json.o storage_number.o unit_test.o url.o web_buffer.o web_buffer_svg.o web_client.o web_server.o  plugin_proc.o proc_diskstats.o proc_interrupts.o proc_softirqs.o proc_loadavg.o proc_meminfo.o proc_net_dev.o proc_net_ip_vs_stats.o proc_net_netstat.o proc_net_rpc_nfs.o proc_net_rpc_nfsd.o proc_net_snmp.o proc_net_snmp6.o proc_net_softnet_stat.o proc_net_stat_conntrack.o proc_net_stat_synproxy.o proc_stat.o proc_sys_kernel_random_entropy_avail.o proc_vmstat.o ipc.o sys_kernel_mm_ksm.o -lm  -lz   -luuid   -L/usr/local/lib -lrdkafka`


but the newer compilation output is  as below:
`gcc        -O2 -pthread   -o netdata appconfig.o adaptive_resortable_list.o avl.o backends.o clocks.o common.o daemon.o dictionary.o eval.o global_statistics.o health.o health_log.o health_config.o health_json.o log.o main.o plugin_checks.o plugin_idlejitter.o plugin_nfacct.o plugin_tc.o plugins_d.o popen.o socket.o simple_pattern.o sys_fs_cgroup.o sys_devices_system_edac_mc.o sys_devices_system_node.o procfile.o proc_self_mountinfo.o registry.o registry_internals.o registry_url.o registry_person.o registry_machine.o registry_init.o registry_db.o registry_log.o rrd.o rrddim.o rrdfamily.o rrdhost.o rrdset.o rrdcalc.o rrdcalctemplate.o rrdvar.o rrddimvar.o rrdsetvar.o rrd2json.o rrd2json_api_old.o rrdpush.o storage_number.o unit_test.o url.o web_api_old.o web_api_v1.o web_buffer.o web_buffer_svg.o web_client.o web_server.o   ipc.o plugin_proc.o plugin_proc_diskspace.o proc_diskstats.o proc_interrupts.o proc_softirqs.o proc_loadavg.o proc_meminfo.o proc_net_dev.o proc_net_ip_vs_stats.o proc_net_netstat.o proc_net_rpc_nfs.o proc_net_rpc_nfsd.o proc_net_snmp.o proc_net_snmp6.o proc_net_softnet_stat.o proc_net_stat_conntrack.o proc_net_stat_synproxy.o proc_stat.o proc_sys_kernel_random_entropy_avail.o proc_vmstat.o proc_uptime.o sys_kernel_mm_ksm.o -lm  -lz   -luuid    -lpthread`


Is there anything I am doing wrong ?
Thanks in advance!

**Comment by divgwd** [comment]
Hi,
We finished adding kafka as the backend, we would like you to review it .
I'll submit  a PR by tomorrow noon IST.

**Comment by ktsaou** [comment]
nice!

**Comment by divgwd** [comment]
Hi,
While trying to install the netdata with kafka plugin on one of our servers I get the below error :+1: 
`[netdata]# /usr/sbin/netdata -P /var/run/netdata.pid
./installer/functions.sh: line 140: /usr/sbin/netdata: No such file or directory`

but it while compiling and installing it installs to /usr/local path
`make[2]: Entering directory /opt/Netdata-Kafka_ver_1.1/netdata/src
test -z "/usr/local/sbin" || /bin/mkdir -p "/usr/local/sbin"
  /usr/bin/install -c netdata '/usr/local/sbin'
test -z "/var/cache/netdata" || /bin/mkdir -p "/var/cache/netdata"
 /usr/bin/install -c -m 644 .keep '/var/cache/netdata'
test -z "/var/log/netdata" || /bin/mkdir -p "/var/log/netdata"
 /usr/bin/install -c -m 644 .keep '/var/log/netdata'
test -z "/var/lib/netdata/registry" || /bin/mkdir -p "/var/lib/netdata/registry"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata/registry'
test -z "/var/lib/netdata" || /bin/mkdir -p "/var/lib/netdata"
 /usr/bin/install -c -m 644 .keep '/var/lib/netdata'
test -z "/usr/local/libexec/netdata/plugins.d" || /bin/mkdir -p "/usr/local/libexec/netdata/plugins.d"
  /usr/bin/install -c apps.plugin '/usr/local/libexec/netdata/plugins.d'
`
I have encountered this with just one server .I want to know why does the binary install in a different path and the code to run it searches in another path?? 
where should I be editing of checking for the mismatch in the path setting??
