### ISSUE TITLE
sysvinit scripts are not checking status before start/stop execution

### ISSUE THREAD

**Issue by variia** [firehol/netdata#1381]
Hi,

I am building saltstack formula to install netdata and found an issue with both sysvinit sctipts. In nutshell, they don't check status before running stop or start functions and it breaks init when start is executed on top of a running netdata since it deletes the pid file after throwing the errors:

```
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata start
Starting netdata...
                                                           [  OK  ]
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata status
netdata (pid  11531) is running...
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata stop
Stopping netdata...                                        [  OK  ]
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata stop
Stopping netdata...                                        [FAILED]
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata start
Starting netdata...
                                                           [  OK  ]
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata status
netdata (pid  11792) is running...
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata start
Starting netdata...
2016-12-15 12:06:40: netdata: ERROR: IPv4 bind() on ip '0.0.0.0' port 19999 failed. (errno 98, Address already in use)
2016-12-15 12:06:40: netdata: ERROR: Cannot bind to ip '0.0.0.0', port 19999
2016-12-15 12:06:40: netdata: ERROR: IPv6 bind() on ip '::1' port 19999 failed. (errno 98, Address already in use)
2016-12-15 12:06:40: netdata: ERROR: Cannot bind to ip '::1', port 19999
2016-12-15 12:06:40: netdata: FATAL: Cannot listen on any socket. Exiting... # : Success

2016-12-15 12:06:40: netdata: INFO: Saving database...
2016-12-15 12:06:40: netdata: INFO: NetData exiting. Bye bye...
                                                           [FAILED]
[root@formula-pillar-centos-6 ~]# /etc/init.d/netdata status
netdata is stopped
[root@formula-pillar-centos-6 ~]# netstat -tlnp | grep netdata
tcp        0      0 0.0.0.0:19999               0.0.0.0:*                   LISTEN      11792/netdata
tcp        0      0 ::1:19999                   :::*                        LISTEN      11792/netdata
```
The only way to fix this is to kill the netdata process. To run status check before function is best practice on most distros and the fix is easy:
```
--- /usr/share/netdata/system/netdata-init-d	2016-12-15 10:31:35.544777001 +0000
+++ /etc/init.d/netdata	2016-12-15 12:12:50.792304686 +0000
@@ -56,9 +56,11 @@

 case "$1" in
 start)
+        service_status && exit 0
 	service_start
 ;;
 stop)
+        service_status || exit 0
 	service_stop
 ;;
 restart)
```
I am happy to fix this in both `netdata-init-d` and `netdata-lsb` scripts and create a pull request.

**Comment by ktsaou** [comment]
Yes, please do so. Check also this: https://github.com/firehol/netdata/pull/403

**Comment by ktsaou** [comment]
Check also the cases where the installer installs each version: https://github.com/firehol/netdata/blob/9e48033fbcf2f83c8359b181fbe4cf6dab757616/netdata-installer.sh#L866-L890

**Comment by variia** [comment]
I did check those but I find not much relation, could you pls clarify? I also tested the lsb script for debian variants and that is fine.

**Comment by ktsaou** [comment]
oh... sorry. I didn't imply there is any relation. I thought that since you are going to touch those files, you should know where they are used and what other people thought about them. I didn't try to imply anything...

**Comment by variia** [comment]
ahh okay, thanks.
Regarding #403, I personally don't see much point feature upgrading the init ecosystem of this app (like installer, scripts, etc). But if such a thing is considered, the person reporting or working on the feature (like runas user) needs to reflect this feature in all the other init scripts as well as systemd unit files, not just Centos-6. But generally, I find that contrib script solving non existing problems so I would leave the `runas` user management to the config file and keep the current scripts.
