### ISSUE TITLE
Graphite Question

### ISSUE THREAD

**Issue by animosity22** [firehol/netdata#1382]
I've been trying to tweak my config such that I don't destroy my disk that has my graphite database on it. 

My backend config is pretty much based on the documentation:

```
[backend]
         enabled = yes
         data source = average
         type = graphite
         destination = localhost
         prefix = netdata
         hostname = hostname
         update every = 10
         buffer on failures = 10
         timeout ms = 20000
```

I've toyed around with a bunch of settings in the carbon cache, but almost no matter what I do, I have the disk that is my graphite disk 100% utilized almost the entire time.

My storage is setup:

```
[netdata]
pattern = ^netdata.*
retentions = 10s:1h,1m:1d,10m:1y
```

I have plenty of CPU/Memory, but my disk is a sata 7200 rpm disk that only has this on it so I can't do much in terms of making that faster.

I've tried tweaking many of the carbon settings:

```

MAX_CACHE_SIZE = inf
MAX_UPDATES_PER_SECOND = 50
```

If I move it too low for updates, it seems to not feed it into Grafana enough and I get no data triggered alerts. If I move it much higher, I get 100% disk utilization the whole time and the disk is constantly busy.

Any other thoughts or suggestions as when I was using collectd, I didn't get this behavior and I really do not want to change back. 

I did peek at the other opentsb backend, but that seems like a bit too much work on the setup and config for that.

**Comment by ktsaou** [comment]
hm... I don't use graphite myself, apart from testing, so I don't know how to help you.

I would check if netdata is sending too many metrics for some reason. netdata adds a few charts for that: https://github.com/firehol/netdata/wiki/netdata-backends#monitoring-operation

I would ask for help from users that have reported using graphite successfully. So, @thecityofguanyu, @bkmeneguello, @busyninja if you can help here, please do. Thanks!

**Comment by animosity22** [comment]
Appreciate the feedback. I can't imagine ~2k metrics being sent is that much based on the reports. 

If anyone else that has plugged into graphite, I'd be curious to see what your performance is.

**Comment by thecityofguanyu** [comment]
My graphite database host is on a hosted OpenVZ container VPS, so I can't give the best insight into real HDD impact. Sorry.

With that said, here's the netdata `system.io` graph on the host from the past day. netdata takes it from `/proc/vmstat`. Take from that what you will.

![graphite-system.io](http://i.imgur.com/LXLnhu4.png)

My netdata backend settings are default apart from the destination. I'm also using Carbon's default storage schema retention for netdata.

**Comment by animosity22** [comment]
@thecityofguanyu - do you happen to have the IOPS? It's writing very little data but generating a lot of IOPS for me.

**Comment by animosity22** [comment]
I think I figured it out. 

I was writing my graphite data to a XFS file system that doesn't do well with small files and writes. I moved it back over to an ext4 file system and everything really started working properly again and it handles the small IO a ton better.

Thanks!
