### ISSUE TITLE
Echarts.js and Netdata

### ISSUE THREAD

**Issue by tevez15** [firehol/netdata#1383]
Hi, 

I'm using net data, and I have a lot of charts using echarts.js, but, if is in the same page I have both, netdata give me errors like: 

> netdata.server_cpu: chart failed to be created as dygraph

This is the files and the order.
```
<!-- CHART SCRIPTS -->
<script src="/public/js/dashboard/echarts.js"></script>
<script src="/public/js/dashboard/echarts-all.js"></script>

<script src="/public/js/dashboard/jquery.dashcharts.js"></script>

<!-- netdata -->
<script type="text/javascript" src="http://<?php echo Ip::getServerAddress(); ?>:19999/dashboard.js"></script>
<!-- netdata -->
```

**Comment by josealgardataborges** [comment]
Same here.... cant get netdata to work together with echarts [https://github.com/ecomfe/echarts](url)

**Comment by ktsaou** [comment]
Could you please set this line to `true` and reload the page: https://github.com/firehol/netdata/blob/f4827e695a2a67b3c37e316a61e28705f6972dd0/web/dashboard.js#L344

This will make the error thrown by dygraphs visible at the browser console.

**Comment by tevez15** [comment]
Hi.. now on console he says:

> ReferenceError: Gauge is not defined

**Comment by ktsaou** [comment]
hm... it seems it is conflicting with gauge.js, no dygraphs.
Can you switch chart library to verify this is the case?

**Comment by tevez15** [comment]
Hi,

I change to kendo, and work, but the problem now is, I have all the data generated with echarts, can you explain how I can use both (netdata and echarts) without conflit?

**Comment by ktsaou** [comment]
One simple solution is to put either of the 2 in `iframe`.
Unfortunately, from the posts above, I can trace why this is happening. If you can provide a sample HTML that can reproduce the problem, it might help to figure out how that can be fixed.

**Comment by tevez15** [comment]
You just need your own netdata dashboard.js, everything is working.

https://drive.google.com/file/d/0B1g4CkAMVHPFMDFWNVZEa0sxN28/view?usp=sharing

**Comment by ktsaou** [comment]
Well... something really weird is happening here. Once `echarts.js` is loaded, netdata is not able to load any other jquery modules. I am seeking for help too...

**Comment by tevez15** [comment]
echarts.js use a required to load files, including gauge. Probably the conflict come from that required.

For example, I tested with kendo ui charts and work without problems.

**Comment by josealgardataborges** [comment]
Im guessing that there's some sort of autoload of files on echarts, that blows netdata.

**Comment by ktsaou** [comment]
I think there is something wrong with `jquery`. Once `echarts.js` is loaded jquery goes crazy. I have asked for help too, so give me a day or two to come with something...

**Comment by josealgardataborges** [comment]
@ktsaou please take your time. In the meantime i settled for KendoUI Charts/Gauges which do not conflict with netdata. But would love to use echarts.js for same results. I'll wait for your findings. Regards.

**Comment by ktsaou** [comment]
I have made a few changes to netdata for compatibility. They are already merged.

However, with your version of echarts, it still does not work.
I downloaded the latest version of echarts, and it works fine (although your sample page does not work - it seems they have changed the API of echarts).

So, here is a sample html:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    <!-- including ECharts file -->
    <script src="echarts.js"></script>
	<script type="text/javascript" src="http://localhost:19999/dashboard.js"></script>
</head>
<body>
    <!-- prepare a DOM container with width and height -->
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // based on prepared DOM, initialize echarts instance
        var myChart = echarts.init(document.getElementById('main'));

        // specify chart configuration item and data
        var option = {
            title: {
                text: 'ECharts entry example'
            },
            tooltip: {},
            legend: {
                data:['Sales']
            },
            xAxis: {
                data: ["shirt","cardign","chiffon shirt","pants","heels","socks"]
            },
            yAxis: {},
            series: [{
                name: 'Sales',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // use configuration item and data specified to show chart
        myChart.setOption(option);
    </script>

	<div data-netdata="system.cpu" data-chart-library="gauge" data-gauge-adjust="width" data-title="Received" data-width="12%" data-before="0" data-after="-300" data-colors="" role="application" class="netdata-container">
	</div>
	<div data-netdata="system.cpu" data-chart-library="easypiechart" data-gauge-adjust="width" data-title="Sent" data-width="12%" data-before="0" data-after="-300" data-colors="" role="application" class="netdata-container">
	</div>
</body>
</html>
```

and this is the screenshot:

![image](https://cloud.githubusercontent.com/assets/2662304/21510241/d296e63e-cc99-11e6-949a-816980efd28c.png)

The version of echarts I used has been downloaded from this page: http://echarts.baidu.com/download.html - I tried this one: http://echarts.baidu.com/dist/echarts.js

In the version of echarts you sent me, they had done something that really destroyed jquery. In the latest version of echarts though, everything seems good.

**Comment by ktsaou** [comment]
I am closing this now. If we can help somehow, just post.
