### ISSUE TITLE
Monitor GPU Usage on Netdata

### ISSUE THREAD

**Issue by aj-fernando** [firehol/netdata#1389]
Hello, 

I'm trying to monitor gpu usage on a nvidia tegra k1 board in which I use netdata to monitor system. I have to say its a great tool but I'm having some problems of writing a custom plugin. At the moment I'm involved with writing a custom plugin to monitor the usage on NVIDIA gpu on the board and also another to monitor outputs from an executable of a software code i wrote that's running always in background.

I wonder how I can start writing a plugin which suits best for my requirements. There are some examples of how to use an existing skeleton plugin (python and bash etc.) but not sample code of how to write one just a [pseudo code](https://github.com/firehol/netdata/wiki/External-Plugins#writing-plugins-properly) I would like to add a c plugin since I'm coding with c++ but the sample code itself here [apps.plugin.c](https://github.com/firehol/netdata/blob/master/src/apps_plugin.c) is going close to 3000 lines and not easy to understand for someone who just started with netdata. Or using another plugin is a better idea? And if there are some other sample codes, please share! 

Thanks alot!!

**Comment by l2isbad** [comment]
> but not sample code of how to write one

> Or using another plugin is a better idea? And if there are some other sample codes

I think a good idea is to use python :

- To begin with  a good idea is to look at the [existing python plugins](https://github.com/firehol/netdata/tree/master/python.d)

- And [instructions/guide](https://github.com/firehol/netdata/wiki/How-to-write-new-module) how to create custom python plugins.

**Comment by ktsaou** [comment]
In all cases, the idea is very simple:

1. Collect data any way you like
2. Output `CHART`, `DIMENSION`, `BEGIN`, `SET`, `END` lines to send these data to netdata

It is just a few `printf()` statements.

So, in `C`:

1. This is the main loop: https://github.com/firehol/netdata/blob/08bb468b96aa02486acb50bce316a1915aa0509d/src/apps_plugin.c#L2846-L2853
2. This generates charts: https://github.com/firehol/netdata/blob/08bb468b96aa02486acb50bce316a1915aa0509d/src/apps_plugin.c#L2516-L2644
3. This sends charts to netdata:
https://github.com/firehol/netdata/blob/08bb468b96aa02486acb50bce316a1915aa0509d/src/apps_plugin.c#L2385-L2510

Another, simpler example is fping:

1. The main loop is controlled by fping code, so no loop just for netdata
2. This code prints both the charts and updates the values: https://github.com/ktsaou/fping/blob/develop/src/fping.c#L1299-L1374

The full documentation of lines you can `printf()` for netdata is here: https://github.com/firehol/netdata/wiki/External-Plugins

It is ridiculously simple. You will not have any problems if you experiment a bit with it.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you need help just post and I'll re-open it.
