### ISSUE TITLE
File ' ' does not exist, or is not accessible.

### ISSUE THREAD

**Issue by amsierra** [firehol/netdata#139]
Installed netdata on Ubuntu 12.04.05 without a hitch, however when trying to access the web UI, all I see is the line above in the browser. I tried finding the web server configuration, or enabling some of the debug logs, but I'm not sure what to look for. 

There is also a few other services running on this machine, MySQL, nginx, rails, so I'm not sure if there is a conflict somewhere. Apologize for the sparse details, if someone could point me in the right direction I can do some more digging.

**Comment by ktsaou** [comment]
The directory with the web files does not exist.
How did you install it?

**Comment by amsierra** [comment]
Using the installer script, I checked /usr/share/netdata/web, all the files appear to be there and owned by netdata

**Comment by ktsaou** [comment]
ok, I just pushed a change that will reveal the filename in question.
Could you please pull it and install it again?

**Comment by amsierra** [comment]
Awesome, got it. /usr/share/netdata was owned by root after the installation procedure. I had to chown to netdata:netdata and add 755 perms.
