### ISSUE TITLE
Error 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by supervazi** [firehol/netdata#1390]
Hi,

Today a made an update and after that I get this error when accessing the dashboard.

Error 405: Cannot download charts index from server http://.../api/v1/charts

However, if I access it directly a can see the charts list. As you suggested in another thread, I paste the result in http://jsonlint.com/ and get this:

```
"disk_inodes._mnt_wdmycloud": {
	"id": "disk_inodes._mnt_wdmycloud",
	"name": "disk_inodes._mnt_wdmycloud",
	"type": "disk_inodes",
	"family": "/mnt/wdmycloud",
	"context": "disk.inodes",
	"title": "Disk Files (inodes) Usage for /mnt/wdmycloud [\\192.168.64.5\Backup] (disk_inodes._mnt_wdmycloud)",
	"priority": 2024,
	"enabled": true,
	"units": "Inodes",
	"data_url": "/api/v1/data?chart=disk_inodes._mnt_wdmycloud",
	"chart_type": "stacked",
	"duration": 3600,
	"first_entry": 1481890004,
	"last_entry": 1481890872,
	"update_every": 1,
	"dimensions": {
		"avail": {
			"name": "avail"
		},
		"used": {
			"name": "used"
		},
		"reserved_for_root": {
			"name": "reserved for root"
		}
	},
	"green": null,
	"red": null
},



Error: Parse error on line 7731:
...nodes",
			"title": "Disk Files (inodes)
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

Only the default dashboard not working, my custom dashboards are working without problem. I made a clean install too, but with the same result.
Same update on other server - without the wdmycloud mount - worked without problem.

It is a great tool! Thank you!

**Comment by ktsaou** [comment]
Thanks for reporting it.
Found the error. It needs the `\` escaped.
I am way of a computer right now. I will submit a fix later today.

**Comment by supervazi** [comment]
Thank you for the quick reply, I will report the result as I install it.

**Comment by ktsaou** [comment]
Could you please check?

**Comment by supervazi** [comment]
Updated. It is working without problem now.
Thank you for the quick fix!
