### ISSUE TITLE
Question - Http endpoint performance

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#1396]
We are using netdata on all our spring boot servers that hosts REST Web services. And I was thinking it would great if Netdata could capture the Http endpoint performance on our server that's running on a specific port. But I assume this will require some plugin that runs along with the application server and wire tapping may not be possible. Not sure if Linux has something that provides this information in any way.

Thought its worth a shot to ask.

**Comment by ktsaou** [comment]
Without the cooperation of the application, the best bet is to have the web server log in its access log timing information (most web servers can do this), and have a netdata plugin monitor the log in real-time to parse it. There are a few plugins in python that parse web server logs already, so a small change will be required.

In general, I suggest to use a web server as a web application firewall (WAF), to have your real application protected and isolated. This man-in-the-middle web server could also provide quite a few more functions (like load-balancer, URL filtering, etc). A netdata monitoring this man-in-the-middle web server could provide this information for all your web servers. The only problem that might require some cooperation from your application is to somehow parse the client the IP from an HTTP header.

On the other hand, if you can alter the application, what is required is rather simple - just a few variables:

1. count of requests received so far (each request just adds one)
2. sum of the duration in milliseconds all requests took so far (each response adds the time it took to be computed)

Just the above 2 variables, can be used to calculate:

1. requests per seconds
2. average time to respond to requests

Ideally, you should also want the max response time too, but this is a bit more tricky.

**Comment by gamefundas** [comment]
We decided to go with Stagemonitor for closely monitoring the spring boot application as most of our requirements are easily met. Trying to do this with Netdata would have made this a long trip.
