### ISSUE TITLE
/proc/net/sockstat

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#14]
Support:

`/proc/net/sockstat` and `/proc/net/sockstat6`

**Comment by andyshinn** [comment]
When this is implemented, I would love if it supported the `mem` and `orphan` numbers from `/proc/net/sockstat`. This would be very helpful in tracking `TCP: out of memory -- consider tuning tcp_mem` errors for tuning `/proc/sys/net/ipv4/tcp_mem`.

**Comment by ktsaou** [comment]
These files are pretty simple to parse. I am not sure I know how to use this information though.

Can you find any reliable sources for each of the numbers in these files?

```sh
# cat /proc/net/sockstat
sockets: used 2152
TCP: inuse 66 orphan 0 tw 9 alloc 77 mem 6
UDP: inuse 17 mem 17
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

[This post](https://serverfault.com/questions/628635/what-is-the-unit-of-mem-and-memory-in-proc-net-sockstat) says `mem` in `TCP` and `UDP` are in pages, while `memory` in `FRAG` is in bytes.

[This post](https://www.linuxquestions.org/questions/linux-networking-3/what-is-tcp-orphan-in-in-proc-net-sockstat-850000/) discusses about `orphan`, but I am not sure I understand. [This one](https://community.hpe.com/t5/Networking/Regarding-meaning-for-quot-cat-proc-net-sockstat-quot-results/td-p/3922867) says that orphan sockets, are connections that are not attached to any user file handle.

[This post](http://blog.tsunanet.net/2011/03/out-of-socket-memory.html) describes out of memory errors and orphans, much better.

This is indeed very useful info!

**Comment by andyshinn** [comment]
I agree, it is a little hazy. I was using http://blog.tsunanet.net/2011/03/out-of-socket-memory.html as a reference which is helpful.

The TCP mem is in pages and directly correlates to `/proc/sys/net/ipv4/tcp_mem` (which is also in pages). I'll see if i can dig up information on FRAG, orphan, tw, and alloc as well.

**Comment by ktsaou** [comment]
here is the `/proc/net/sockstat` plugin.
Next is `/proc/net/sockstat6`.
I'll also try to implement the alarm.

**Comment by ktsaou** [comment]
![screenshot from 2017-11-07 01-44-05](https://user-images.githubusercontent.com/2662304/32469842-2d1fa6ee-c35d-11e7-8201-69a29769f507.png)

**Comment by marcelmfs** [comment]
By the way my netdata aggregator server is showing the `TCP: out of memory -- consider tuning tcp_mem` in dmesg. RAM usage and the number of used sockets (not a huge sudden increase) during these error messages seem normal, maybe there's something else leaking TCP memory?
