### ISSUE TITLE
100 % cpu spikes with Gcloud machines

### ISSUE THREAD

**Issue by aniketdeo** [firehol/netdata#1401]
Hi,
I found one anamoly while using Netdata with Gcloud instance.
The CPU usage goes to 100 % in every 1 min for some milliseconds/microseconds(attaching the screen)
Wanted to know if anyone is facing the same issue or what is the solution for this issue?
Any help wud be appreciated. TIA
![netdata_forum](https://cloud.githubusercontent.com/assets/16444376/21305135/bfb2fd24-c5ef-11e6-9a12-397facd7f7b3.png)

**Comment by ktsaou** [comment]
Could you please post a screenshot of the "Applications" cpu chart, with all its dimensions shown?

like this one:

![image](https://cloud.githubusercontent.com/assets/2662304/21308140/4894cde8-c5e1-11e6-9772-88768a1ba753.png)

**Comment by ktsaou** [comment]
Did you find the source of the spikes?

**Comment by ktsaou** [comment]
@aniketdeo  did you solve it?

I am closing this now, but if we can help somehow, just post.
