### ISSUE TITLE
system.ipv4: data download failed for url...

### ISSUE THREAD

**Issue by egyptianbman** [firehol/netdata#1402]
The charts at the top of `System Overview` don't seem to be able to recover from an api failure.

When I go to the url: https://{host}/api/v1/data?chart=system.ipv4&format=array&points=300&group=average&options=absolute|jsonwrap|nonzero&after=-300&dimensions=received

It works. It's snappy and I have no issues but at some point, the api isn't responding which is causing the UI to choke and the chart never gets restored. I have to reload the page to restore the charts.

**Comment by ktsaou** [comment]
This seems like a networking or a proxy issue.
When this happens, could you please check the web browser console?
Is it a timeout or what?

**Comment by egyptianbman** [comment]
From what I'm seeing the request is cancelled:
![image](https://cloud.githubusercontent.com/assets/323600/21328383/4b732952-c5f9-11e6-8c64-672a5ac6eb33.png)

**Comment by ktsaou** [comment]
interesting! I don't think this is cancelled by netdata...

If you are using chrome, please open this url: `chrome://net-internals/#events`, switch back to netdata, reload the page and wait for it to happen again.

Then switch back on the tab with the URL I gave you. Can you find the cancelled request on the list? Click on it and it will give you more details. Can you post them here?

**Comment by ktsaou** [comment]
I have added the code to make retries in PR #1403 
I always wanted to do this, to allow the dashboard survive netdata restarts.
Keep in mind though, these cancelled requests of yours are not normal. They should not be there. So, it would be good to find the cause (probably a web browser plugin or something - btw, do they happen on any other browser?).
