### ISSUE TITLE
missing sys/sysmacros.h includes

### ISSUE THREAD

**Issue by candrews** [firehol/netdata#1408]
glibc 2.25 is deprecating the namespace pollution of <sys/types.h> injecting major(), minor(), and makedev() into the compilation environment, with a warning that insists that users include <sys/sysmacros.h>
See https://bugzilla.redhat.com/show_bug.cgi?id=130601#c6

netdata should add appropriate `#include <sys/sysmacros.h>` to eliminate the issue.

(Issue originally reported at https://bugs.gentoo.org/show_bug.cgi?id=603182 )

**Comment by ktsaou** [comment]
fixed it!
