### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR after successful install

### ISSUE THREAD

**Issue by mpdehnel** [firehol/netdata#1409]
I installed netdata on our Ubuntu 16.04 server on 9th December, with all the pre-requisites. It worked absolutely fine, and was a dream to get going. Really useful data!

Now, as of today, whenever I visit `https://url-of-our.server:19999` (which used to work perfectly), I just get `ERR_SSL_PROTOCOL_ERROR`. I have completely uninstalled and re-installed netdata and still get the same thing. There were no errors in the original or subsequent install.

Nothing related to this seems to show in `error.log` and the only things showing in `access.log` are of the following type:

`2016-12-20 15:52:54: 5: <ip-address> port 56392 connected on thread task id 84040`
`2016-12-20 15:52:54: 5: <ip-address> port 56392 disconnected from thread task id 84040`

Oddly enough, accessing it via the `<ip-address>:19999` works just fine. 
Its normal URL is a fully qualified domain name.

Other colleagues have had the same issue on different browsers / operating systems / in incognito mode.

Any thoughts or suggestions gratefully received!

Edit: One of my colleagues has now managed to produce:

![pasted image at 2016_12_20 04_04 pm](https://cloud.githubusercontent.com/assets/237223/21358076/78f8e9a8-c6cf-11e6-85ad-04a952dd6fcb.png)

**Comment by ktsaou** [comment]
hm... for sure this is not netdata related.
Searching around I found this: http://stackoverflow.com/a/4762977 which gives a few possible reasons...

**Comment by ktsaou** [comment]
Check this one too: http://serverfault.com/a/497433

**Comment by mpdehnel** [comment]
Well, it kind of is netdata _related_ if it's from a clean install, and netdata is calling a certain SSL library with a certain (wrong?) configuration. :-)

I assume this would require some sort of change in the `# GitLab Nginx #` section of the configuration file found in `/etc/gitlab/gitlab.rb` ? What would that change be?

I have `nginx['redirect_http_to_https'] = true` and 
`nginx['redirect_http_to_https_port'] = 80` in this file already. (I've tried replacing 80 with 443 to no success)

Any suggestions very welcome! Is there anywhere else I should look for errors in logs?

**Comment by ktsaou** [comment]
hm... I really don't know how to help you.

netdata does not know anything about SSL, so there is nothing I can do to influence how your nginx is communicating with SSL. And I am not an nginx expert either.

If anyone knows how to help, please do so...

**Comment by mpdehnel** [comment]
Netdata kind of does know _something_ about SSL, because it has a whole section on nginx and its use of SSL in the `gitlab.rb` file. My guess is that the interaction between nginx, OpenSSL, and netdata is causing this somewhere, I just can't find where!

Have you successfully set up a LetsEncrypt cert (or any other TLS/SSL cert for that matter) with netdata?

**Comment by mpdehnel** [comment]
Also, [this file](https://gitlab.com/gitlab-org/gitlab-recipes/blob/638d829be36fd904f2ba4300c8cc925d0ca9b289/web-server/nginx/gitlab-ssl) and the commit message associated with it
> Prevent error: ssl_error_rx_record_too_long in Firefox

seem to indicate this is an issue which has previously been fixed.

**Comment by mpdehnel** [comment]
Sorry, deleted previous comments as I was getting confused between configs, and my comments were wrong. The initial post still stands though!

**Comment by vblogio** [comment]
It seems that github embedded web server push a redirect order to Chrome and Safari browsers :( . It works like a charm with Firefox but strictly impossible to connect via simple http from others...

**Comment by ktsaou** [comment]
> It seems that netdata embedded web server push a redirect order to Chrome and Safari browsers :(

hm... the SSL/TLS connection is established before any other traffic is passed through it. So, the error you see is purely between your web browser and the HTTPS server. netdata has not received/sent anything yet.

To verify it, you could serve some static content from your web server using the same URL. Does it work if you take netdata out of the equation?

The links I gave you above say that the SSL/TLS configuration of the web server is probably wrong and if you try to use port 443 instead of 19999 for the SSL/TLS connection, it will work.

I am sorry that I cannot help more, but I truly don't know how to help you and I really don't see how netdata can influence the SSL communication of your web server.

**Comment by ktsaou** [comment]
@mpdehnel did you solve it?

I am closing this now, but we can help somehow, just post.

**Comment by mpdehnel** [comment]
Hi,

So I worked out it was due to an HSTS error! Will post a write up soon...

Thanks,

Martin 

Martin Dehnel-Wild

**Comment by Nextr0n** [comment]
> 
> Hi, So I worked out it was due to an HSTS error! Will post a write up soon... Thanks, Martin Martin Dehnel-Wild
> […](#)
> On 4 Feb 2017, at 21:21, Costa Tsaousis ***@***.***> wrote: Closed #1409. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hey, how did you manage to solve the problem? I cannot connect to the url:19999 either (getting the same error message on Firefox), but it works in a private window, leading me to believe it is a HSTS problem. Would you mind sharing a solution?

**Comment by thiagoftsm** [comment]
Hi @Nextr0n ,

In normal situation the error `SSL_ERROR_RX_RECORD_TOO_LONG` is due miss configuration on server side or HSTS, please, try one of the following actions:

1 - Case your Netdata has a TLS certificate, please, verify whether Netdata has permission to access the certificate.
2 - Case it does not have, it can be at least 6 different possibilities related to Firefox configuration, for more details you can see https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/ .

best regards!
