### ISSUE TITLE
daemon does not start after offical package installation on Debian

### ISSUE THREAD

**Issue by daveloyall** [firehol/netdata#1410]
Hi, I'm using Debian (sid, aka unstable) and I just did apt-get install netdata.  (Thanks to everyone who made that possible!)

Here is the shell output.  Notice the double space before the `is missing...` text.

    [...]
    The following extra packages will be installed:
      fonts-font-awesome libjs-bootstrap libjs-d3 libjs-jquery libjs-raphael netdata-data
    Recommended packages:
      javascript-common
    The following NEW packages will be installed:
      fonts-font-awesome libjs-bootstrap libjs-d3 libjs-raphael netdata netdata-data
    The following packages will be upgraded:
      libjs-jquery
    1 upgraded, 6 newly installed, 0 to remove and 1307 not upgraded.
    Need to get 2,016 kB of archives.
    After this operation, 6,522 kB of additional disk space will be used.
    Do you want to continue? [Y/n] 
    Get:1 http://debian.cites.illinois.edu/pub/debian/ sid/main fonts-font-awesome all 4.7.0~dfsg-1 [514 kB]
    Get:2 http://debian.cites.illinois.edu/pub/debian/ sid/main libjs-bootstrap all 3.3.7+dfsg-2 [274 kB]
    Get:3 http://debian.cites.illinois.edu/pub/debian/ sid/main libjs-d3 all 3.5.17-1 [131 kB]
    Get:4 http://debian.cites.illinois.edu/pub/debian/ sid/main libjs-jquery all 3.1.1-2 [154 kB]
    Get:5 http://debian.cites.illinois.edu/pub/debian/ sid/main libjs-raphael all 2.1.0-1 [34.0 kB]
    Get:6 http://debian.cites.illinois.edu/pub/debian/ sid/main netdata-data all 1.4.0+dfsg-1 [611 kB]
    Get:7 http://debian.cites.illinois.edu/pub/debian/ sid/main netdata amd64 1.4.0+dfsg-1 [298 kB]
    Fetched 2,016 kB in 1s (1,063 kB/s)
    Reading changelogs... Done
    Selecting previously unselected package fonts-font-awesome.
    (Reading database ... 198997 files and directories currently installed.)
    Preparing to unpack .../fonts-font-awesome_4.7.0~dfsg-1_all.deb ...
    Unpacking fonts-font-awesome (4.7.0~dfsg-1) ...
    Selecting previously unselected package libjs-bootstrap.
    Preparing to unpack .../libjs-bootstrap_3.3.7+dfsg-2_all.deb ...
    Unpacking libjs-bootstrap (3.3.7+dfsg-2) ...
    Selecting previously unselected package libjs-d3.
    Preparing to unpack .../libjs-d3_3.5.17-1_all.deb ...
    Unpacking libjs-d3 (3.5.17-1) ...
    Preparing to unpack .../libjs-jquery_3.1.1-2_all.deb ...
    Unpacking libjs-jquery (3.1.1-2) over (1.12.3-1) ...
    Selecting previously unselected package libjs-raphael.
    Preparing to unpack .../libjs-raphael_2.1.0-1_all.deb ...
    Unpacking libjs-raphael (2.1.0-1) ...
    Selecting previously unselected package netdata-data.
    Preparing to unpack .../netdata-data_1.4.0+dfsg-1_all.deb ...
    Unpacking netdata-data (1.4.0+dfsg-1) ...
    Selecting previously unselected package netdata.
    Preparing to unpack .../netdata_1.4.0+dfsg-1_amd64.deb ...
    Unpacking netdata (1.4.0+dfsg-1) ...
    Processing triggers for fontconfig (2.11.0-6.4) ...
    Processing triggers for man-db (2.7.5-1) ...
    Setting up fonts-font-awesome (4.7.0~dfsg-1) ...
    Setting up libjs-bootstrap (3.3.7+dfsg-2) ...
    Setting up libjs-d3 (3.5.17-1) ...
    Setting up libjs-jquery (3.1.1-2) ...
    Setting up libjs-raphael (2.1.0-1) ...
    Setting up netdata-data (1.4.0+dfsg-1) ...
    Setting up netdata (1.4.0+dfsg-1) ...
    [info] Not starting the netdata daemon:  is missing..
    hobbes@metalbaby:~$

**Comment by ktsaou** [comment]
@lhw @FedericoCeratto any ideas? This info message is not in the source code of netdata...

**Comment by FedericoCeratto** [comment]
@daveloyall can you try adding the following line to your /etc/init.d/netdata after "DEFAULTSFILE=/etc/default/$NAME" around line 36?
```
CONF_FNAME=/etc/netdata/netdata.conf
```
I'll update the package soon.

**Comment by daveloyall** [comment]
@FedericoCeratto, before making the changes you recommended, I tried `sudo service netdata stop` followed by `sudo service netdata start`.  Okay, I got the same error that I got during installation.

I made the edit you recommended, then tried again.  It worked!  Great job.

**Comment by FedericoCeratto** [comment]
I've uploaded version 1.4.0+dfsg-2 with a fix
