### ISSUE TITLE
How to fix the Y axis unit between 2 constant values

### ISSUE THREAD

**Issue by aj-fernando** [firehol/netdata#1411]
Hello, 

I have written a sample bash plugin code thanks to input from some chaps here. But in my case I want to set the Y axis of the chart forever fixed on between 1-100. Because the data value I'm collecting as a percentage. But I can see that netdata is keep changing the focus of y-axis automatically to include only the visible range of X axis data. I understand that it's doing it to magnify the data for a better observation but in my case I want the overall view. 

Can i do it by parsing some code to "CHART ..." after unit name or something? 

Thanks! Appreciate your support!

**Comment by ktsaou** [comment]
Unfortunately, you have to edit this file and add your chart to it, like the one shown: https://github.com/firehol/netdata/blob/ae06bb7d8631baa6064d4ccd11bcd346267880be/web/dashboard_info.js#L302

Keep in mind, your changes will be overwritten the next time you update your netdata...
(yes, I know, I have to find a better way to support this).

**Comment by ktsaou** [comment]
I forgot to mention that you can set y-range on custom dashboards. It is just the default dashboard that supports this the way I mentioned above.

I am closing this. If we can help somehow, just post.

**Comment by Bezod** [comment]
Any news on this?

**Comment by l2isbad** [comment]
no
https://github.com/firehol/netdata/issues/1884

**Comment by ninoz** [comment]
Just out of interest you mention its possible to fix the y-range on a custom dashboard, how would you go about doing this?

Many Thanks

**Comment by l2isbad** [comment]
data-dygraph-valuerange="[0, null]"

**Comment by ninoz** [comment]
thanks for the swift replay, that's exactly what I needed for my ping graphs!

Thanks
