### ISSUE TITLE
Having More than two threshold for alarms

### ISSUE THREAD

**Issue by divgwd** [firehol/netdata#1415]
Hi,
I wanted to know if it's possible to have more than one threshold ie like we have WARNING and CRITICAL is it possible to have  MINOR,WARNING and CRITICAL??

**Comment by ktsaou** [comment]
Unfortunately no. You can of course, have 2 different alarms with different thresholds each...

**Comment by divgwd** [comment]
Thank you :)

**Comment by ktsaou** [comment]
Cleaning up....
