### ISSUE TITLE
finer grained process groups

### ISSUE THREAD

**Issue by 0xpr03** [firehol/netdata#142]
Hello,
I'm currently having problems trying to differentiate between processes with the same name.
For example JVM processes can be running totally different applications while obviously having the same process name.
I could imagine adding a process ID file specifier for such cases ( which can be checked all X minutes if at all ).

I hope this wasn't asked before, I've tried to find similar cases.

![unbenannt](https://cloud.githubusercontent.com/assets/1280209/14228323/deab80b2-f911-11e5-8655-f1b25fb0c69f.png)
(Yes it was me erasing the other names)

**Comment by ktsaou** [comment]
Well, it seems we can read `/proc/X/cmdline` which also includes the command line arguments.
This would require a new configuration file, probably with patterns to match substrings of it.

**Comment by 0xpr03** [comment]
As you just mentioned in #146 : I would be totally fine with groups already. I'm afraid that pattern matching could kill the biggest reason why I'm using this software after years of sticking to htop & co:
Performance.

**Comment by ktsaou** [comment]
yes I now.
I am not go to kill the performance of netdata.

Actually `apps.plugin` is already too heavy (heavier than the netdata daemon). If you look at the code, I have done the most to speed it up, but too much work to be done. I'll see what I can do...

**Comment by ktsaou** [comment]
this has been implemented (without killing performance). Read the top of `apps_groups.conf`.
Thanks!

**Comment by ktsaou** [comment]
Cleaning up. If something remains open it again.
