### ISSUE TITLE
netdata-updater fails

### ISSUE THREAD

**Issue by kariboe** [firehol/netdata#1422]
I followed this tutorial to install the latest git version of netdata: https://github.com/firehol/netdata/wiki/Installation#2-install-netdata

All works perfect and uninstaller en updater files are created. But when I try to run the updater.sh
script I get this error:

 ```
./netdata-updater.sh -f
do dec 22 13:51:45 CET 2016 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

do dec 22 13:51:45 CET 2016 : INFO:  Updating netdata source from github...
Updating df3bc4a..e8ba513
error: Your local changes to the following files would be overwritten by merge:
	conf.d/Makefile.am
	conf.d/python.d.conf
	configure.ac
	plugins.d/loopsleepms.sh.inc
	python.d/Makefile.am
	python.d/README.md
	src/common.c
	src/common.h
	src/daemon.c
	src/freebsd_sysctl.c
	src/main.c
	src/plugin_freebsd.h
	src/registry.c
	src/rrd.c
	src/web_client.c
Please, commit your changes or stash them before you can merge.
Aborting
do dec 22 13:51:46 CET 2016 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)
```

What I am doing wrong? Seems like the installer creates several files that must be commited before I can get the latest git code. 

I am writing Puppet code to install Netdata on all my servers, so i need an automated update method that works.  Any help is appreciated.

**Comment by ktsaou** [comment]
These files have been altered after being checked out. This is a plain `git` operation.
If this happened automatically via your puppet scripts, then something is wrong with your scripts. It should not happen if you don't edit the files.

**Comment by kariboe** [comment]
Thanks for the pointer! While transferring the files from puppet server to node the permissions of the files changed. I rewrote my code to do a git clone immediately from github. Now all works fine.
