### ISSUE TITLE
Can you monitor multiple switches?

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#1425]
Can you monitor multiple switches? For instance SWitch1, SWitch2...
Tell me How I edit the /etc/netdata/node.d/snmp.conf.

------------------my snmp.conf--------------------------
{
    "enable_autodetect": false,
    "update_every": 3,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "10.0.0.1",
            "community": "public",
            "update_every": 3,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "snmp_switch.bandwidth_port1": {
                    "title": "Gi1/0/1",
                    "units": "megabits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "IS3DBMaster",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.10101",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1048576
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.10101",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1048576
                        }
                    }
                }
"hostname": "10.0.0.2",
            "community": "public",
            "update_every": 3,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "IS3WEB01port1": {
                    "title": "Gi1/0/1",
                    "units": "megabits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "IS3WEB01",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.10101",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1048576
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.10101",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1048576
                        }
                    }
                 }
              }
           }
        ]
----------------------------------------------------------------------------------------------------
This is worng.

**Comment by l2isbad** [comment]
Here you go

```
{
	"enable_autodetect": false,
	"update_every": 3,
	"max_request_size": 100,
	"servers": [{
		"hostname": "10.0.0.1",
		"community": "public",
		"update_every": 3,
		"max_request_size": 50,
		"options": {
			"timeout": 10000
		},
		"charts": {
			"snmp_switch.bandwidth_port1": {
				"title": "Gi1/0/1",
				"units": "megabits/s",
				"type": "area",
				"priority": 1,
				"family": "IS3DBMaster",
				"dimensions": {
					"in": {
						"oid": "1.3.6.1.2.1.2.2.1.10.10101",
						"algorithm": "incremental",
						"multiplier": 8,
						"divisor": 1048576
					},
					"out": {
						"oid": "1.3.6.1.2.1.2.2.1.16.10101",
						"algorithm": "incremental",
						"multiplier": -8,
						"divisor": 1048576
					}
				}
			}
		}
	}, {
		"hostname": "10.0.0.2",
		"community": "public",
		"update_every": 3,
		"max_request_size": 50,
		"options": {
			"timeout": 10000
		},
		"charts": {
			"IS3WEB01port1": {
				"title": "Gi1/0/1",
				"units": "megabits/s",
				"type": "area",
				"priority": 1,
				"family": "IS3WEB01",
				"dimensions": {
					"in": {
						"oid": "1.3.6.1.2.1.2.2.1.10.10101",
						"algorithm": "incremental",
						"multiplier": 8,
						"divisor": 1048576
					},
					"out": {
						"oid": "1.3.6.1.2.1.2.2.1.16.10101",
						"algorithm": "incremental",
						"multiplier": -8,
						"divisor": 1048576
					}
				}
			}
		}
	}]
}
```

**Comment by sohwaje** [comment]
Thank you.
I  succeeded in solving that problem.

But I have one question.
-"divisor": 1048576
+"divisor": 1000000 <=====correct?

**Comment by l2isbad** [comment]
[Correct](https://en.wikipedia.org/wiki/Kilobit)

**Comment by sohwaje** [comment]
Both "in" and "out" is "1000000"?

**Comment by l2isbad** [comment]
If "units": "megabits/s", - yes.

**Comment by sohwaje** [comment]
Thank you.

**Comment by ktsaou** [comment]
I am closing this.
If you need further help, please post.

(thank you @l2isbad )
