### ISSUE TITLE
Nginx Proxy Cache Hit / Miss

### ISSUE THREAD

**Issue by leonorpw** [firehol/netdata#1426]
Hello, 
i am looking for a way to track Cache hits / miss from Nginx.
Is there any way to track this? 

Thanks! For creating Netdata =) <3

**Comment by l2isbad** [comment]
I google it and answer is [yes](https://easyengine.io/tutorials/nginx/upstream-cache-status-in-access-log/)!

**Comment by leonorpw** [comment]
Oh damn, I have unfortunately found nothing in my search. Maybe i should improve my google skill oO

Thanks for your help =)
