### ISSUE TITLE
How to customize the default dashboard?

### ISSUE THREAD

**Issue by cobrafast** [firehol/netdata#143]
There are a few dashboard like gauges (free swap, disk r/w, ...) at the very top of a default netdata installtion.
How would I go about to customize these?

I'm particularly interested in replacing the IPv4 Rx/Tx with a NIC Rx/Tx and inverting the swap and RAM gauges.

**Comment by ktsaou** [comment]
If you know HTML/javascript this is easy (just edit `/usr/share/netdata/web/index.html`).

If you installed it today, you can go to `/tv.html` to find a dashboard you can customize using plain HTML. You can host this dashboard anywhere (i.e. your web server).

**Comment by cobrafast** [comment]
The custom dashboard thing doesn't work since netdata only seems to support HTTP but not HTTPS, and my custom dashboard would be hosted on a HTTPS-site. Firefox by default forbids to load scripts (`dashboard.js`) from HTTP sources on a HTTPS-site.

But thank you anyways, I will try to get it done by editing the file you named.

**Comment by cobrafast** [comment]
I did it! Thanks for your help!

![](https://x.ezl.re/20160402_214154.png)

**Comment by I12crash** [comment]
cobrafast, would you be willing to share your html that you used to make that dashboard? I like the layout of it. I created on, but I'm having issues figuring out the RAM especially. I can get it to display the Ram used, but my gauge just shows 100% all the time.

**Comment by cobrafast** [comment]
I'm afraid I don't have the code anymore. Some previous update had a merge conflict and I couldn't be bothered to manually merge my code, so I opted for the original dashboard.

If I'm not mistaken some newer git version switched those two gauges to used instead of free.

**Comment by I12crash** [comment]
Alright, thanks for the reply. I'll keep plugging along in my free time to figure it out.

**Comment by ktsaou** [comment]
The cockpit at the top? It is here: https://github.com/firehol/netdata/blob/70417d058f73384caee1224c9c729c394834170b/web/index.html#L1153-L1260

As you can see it is a few `DIV`s wrapped in javascript (to provide a dynamic chart history for hover to work). You can unwrap it and set a fixed timeframe in your custom dashboard.

**Comment by I12crash** [comment]
Yep, I'm an idiot. Thank you! I've got a sweet dashboard setup now.

**Comment by pixelcookie11** [comment]
> The cockpit at the top? It is here: https://github.com/firehol/netdata/blob/70417d058f73384caee1224c9c729c394834170b/web/index.html#L1153-L1260
> 
> As you can see it is a few `DIV`s wrapped in javascript (to provide a dynamic chart history for hover to work). You can unwrap it and set a fixed timeframe in your custom dashboard.

How can I just get the top part of the dashboard in a separate page kinda like this https://the-eye.eu/traffic/

Sorry if this is a stupid question, I am a noob.

**Comment by thiagoftsm** [comment]
Hi @pixelcookie11 ,

Firstly there is not stupid question, be free to ask us what you need. ;)
Netdata gives for the user the possibility to create their own dashboards as you can see in this link https://docs.netdata.cloud/web/gui/custom/ , inside this link you will also have an example called `tv.html` that has part of the code that you need.

best regards!

**Comment by pixelcookie11** [comment]
How did I miss that? Thanks!

**Comment by thiagoftsm** [comment]
> How did I miss that? Thanks!

You are welcome! :) 

> Is there a list of all the "modules" that I can use?

I understood modules as charts, families, case my interpretation is correct, you can request to Netdata using the URL `http://localhost:19999/api/v1/charts`, you can also enable or disable more charts using the section `[plugins]` and the stock files inside `/usr/lib/netdata/conf.d/`, for more details, please, see these links inside our documentation  https://docs.netdata.cloud/docs/add-more-charts-to-netdata/#configuring-plugins.

Best regards!
