### ISSUE TITLE
Changing from C to F and others...

### ISSUE THREAD

**Issue by rjsears** [firehol/netdata#1433]
I was looking around and was wondering how I change some of the settings for outputting (like temp C to F), etc...

**Comment by LeeNX** [comment]
Real measurements are done in ```C``` ... <Just joking> ;-)  
  
Might be a locale setting as suggested in - https://ubuntuforums.org/showthread.php?t=1616285
  
But I am guessing and there might be something to change in netdata to display ```F```, like calling ```sensors``` with the ```-f``` parameter as suggested in - http://superuser.com/questions/1025519/how-can-i-use-lm-sensors-in-celsius/1025526  
  
Can one change the measurement unit per chart? Would someone want too?

**Comment by ktsaou** [comment]
If the data source cannot change, it can be done by adding an option to the module that collects these values to send to netdata the `collected value * 9 / 5 + 32` and change the units of the chart to F.


It would be required for the following modules:

### python
1. https://github.com/firehol/netdata/blob/master/python.d/hddtemp.chart.py
2. https://github.com/firehol/netdata/blob/master/python.d/sensors.chart.py

### bash
1. https://github.com/firehol/netdata/blob/master/charts.d/apcupsd.chart.sh
1. https://github.com/firehol/netdata/blob/master/charts.d/hddtemp.chart.sh
1. https://github.com/firehol/netdata/blob/master/charts.d/sensors.chart.sh

I guess the python ones are more important (only `apcupsd` has not been ported to python).

Anyone willing to make a PR?

**Comment by l2isbad** [comment]
sounds interesting i will try.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1438 @rjsears

**Comment by ktsaou** [comment]
Is this done? Can we close it?

**Comment by l2isbad** [comment]
It is not done for bash plugins.

**Comment by ktsaou** [comment]
I have moved all the unit conversion requests to #2745 
So, let's continue this discussion there.
