### ISSUE TITLE
Firejailed processes appear as "system" application

### ISSUE THREAD

**Issue by jody-frankowski** [firehol/netdata#1442]
[Firejailed](https://github.com/netblue30/firejail/) processes appear as "system" applications.

Steps to reproduce:
`firejail firefox`

Expected behavior:
The processes are listed as "firejailed_process_name (firejail)".

**Comment by ktsaou** [comment]
Please post a screenshot and the output of `ps fax` (that shows the process tree) and `ps -e` (that shown the process names as seen by netdata).

**Comment by jody-frankowski** [comment]
```sh
ps fax
[...]
 1055 tty1     S      0:00                  \_ firejail firefox
 1066 tty1     S      0:00                  |   \_ firejail firefox
 1091 tty1     Sl   355:54                  |       \_ firefox
 1803 tty1     Sl     0:00                  |           \_ /usr/lib/firefox/plugin-container /home/me/.mozilla/firefox/73i2bdki.default/extensions/webpg-fi
refox@curetheitch.com/plugins/npwebpg-extonly-v0.6.3-Linux_x86_64-gcc3.so -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appd
ir /usr/lib/firefox/browser 2 plugin
[...]
```

```sh
ps -e
[...]
 1055 tty1     00:00:00 firejail
[...]
 1066 tty1     00:00:00 firejail
 1091 tty1     05:56:16 firefox
[...]
```

![image](https://cloud.githubusercontent.com/assets/3500332/21470923/56c6abfa-ca9d-11e6-8681-398bd7ae2d46.png)

**Comment by ktsaou** [comment]
I think your firefox is under X, not under system.
You haven't posted the whole of `ps fax` output, but I think it would appear under X. I see X is properly detected on your system (3rd chart shows X, on the first 2 it must be on the dimensions below the visible).

So, how did you concluded that your firefox is shown as `system`?

**Comment by jody-frankowski** [comment]
I concluded it was under `system` because of the memory graph.
I even did a memory reduction into `about:memory` to confirm, and there indeed was a reduction for the `system` graph.

On the following screenshot you can see my tests:
- I opened a firejailed chromium, and it appears as `other`.
- I closed it, and memory from `other` drops.
- I closed firefox, and memory from `system` drops.
- I opened a firejailed firefox, and it appears as `other`.

![image](https://cloud.githubusercontent.com/assets/3500332/21472471/258331a0-cadc-11e6-8e73-6ff8a5bd068a.png)

I can't explain why it appears in `other` after a restart, but I can only guess that it's because of how they are started:
- In the first instance, firefox was started from my `.xinitrc`.
- In the second instance, firefox was started from dmenu.

Here is the process tree of the first firefox:

```sh
root       580  0.0  0.0  94844  4576 ?        Ss   16:54   0:00 login -- me
me         800  0.0  0.0  45396  6008 tty1     Ss   16:54   0:00  \_ -zsh
me         924  0.0  0.0  13696  3116 tty1     S+   16:54   0:00      \_ /bin/sh /usr/bin/startx
me         952  0.0  0.0  15920   916 tty1     S+   16:54   0:00          \_ xinit /home/me/.xinitrc -- /etc/X11/xinit/xserverrc :0 vt1 -auth /tmp/serveraut
me         953  3.3  1.0 451832 167828 tty1    Rl   16:54   5:57              \_ /usr/lib/xorg-server/Xorg -nolisten tcp :0 vt1 -auth /tmp/serverauth.hwhm05
me        1027  0.0  0.0  13696  3220 tty1     S    16:54   0:00              \_ sh /home/me/.xinitrc
me        1048  0.0  0.0  12788  1832 tty1     S    16:54   0:00                  \_ sxhkd -m 1
me        1049  0.0  0.0 343612 14612 tty1     Sl   16:54   0:00                  \_ lxpolkit
me        1050  0.0  0.0  13968  2052 tty1     S    16:54   0:00                  \_ firejail firefox
me        1062  0.0  0.0  26060  2800 tty1     S    16:54   0:00                  |   \_ firejail firefox
me        1090 49.0 16.3 4131692 2673796 tty1  Sl   16:54  87:26                  |       \_ firefox
me        1798  0.0  0.2 394084 43180 tty1     Sl   16:54   0:00                  |           \_ /usr/lib/firefox/plugin-container /home/me/.mozilla/firefox
```

Here is the one of the second:
```sh
me       22871  0.0  0.0  24936  3608 ?        S    19:53   0:00 /usr/bin/zsh
me       22874  0.0  0.0  13968  2072 ?        S    19:53   0:00  \_ firejail firefox
me       22875  0.0  0.0  26060  2860 ?        S    19:53   0:00      \_ firejail firefox
me       22877  103 12.6 3303724 2070672 ?     Sl   19:53  12:59          \_ firefox
me       22967  0.0  0.2 394080 43024 ?        Sl   19:53   0:00              \_ /usr/lib/firefox/plugin-container 
```

Hope this helps.

**Comment by ktsaou** [comment]
ok, thanks.

The whole idea with the process grouping made by netdata is to limit the number of dimensions shown at the charts (it does not have much meaning to have 1k dimensions there - not to mention that your browser will be very slow on such a chart).

This grouping is controlled by `/etc/netdata/apps_groups.conf`.
I added a few more applications to that file, to match your case.
So you can just update netdata to get the latest.

Of course you can edit this file to match your needs.

Thanks for reporting this!

**Comment by jody-frankowski** [comment]
Thank you very much.
