### ISSUE TITLE
Links to different sections doesn't work.

### ISSUE THREAD

**Issue by Kezxo** [firehol/netdata#1449]
On the main page right under CPU there is this text: _"You can get per core usage at the **CPUs** section and per application usage at the **Applications Monitoring** section."_
It has two links to the different sections but they are broken, they lead to ``#cpu`` and ``#apps`` but it should be ``#menu_cpu`` and ``#menu_apps`` I'm guessing?
There are more of these, I'm not sure any of the internal links in the sections themselves work.

**Comment by ktsaou** [comment]
thanks! Fixed them.
