### ISSUE TITLE
apps.plugin's debug_malloc performs misaligned 32-bit reads/writes

### ISSUE THREAD

**Issue by gbritton** [firehol/netdata#145]
The debug malloc wraps allocations as so: (32-bit sentinel)(32-bit size)(allocation...)(32-bit sentinel).  The trailing sentinel is immediately following the allocation and is accessed via a pointer to 32-bit value.  In the case in which an allocation of N bytes where N is not divisible by 4, this pointer will not be properly 32-bit aligned and the accesses will cause Alignment Faults on architectures (such as ARM) which cannot do unaligned data accesses.  This should either be fixed by not accessing it as 32-bits (instead, doing bytewise access, which of course could be done only if the pointer is misaligned; or, padding between the allocation and the sentinel could be added (which does effectively grow the sentinel if the point of the debugging is to validate the data -immediately- surrounding the allocation.

**Comment by ktsaou** [comment]
Thanks for bringing this up.
I will update apps.plugin to use debug_malloc only in debug mode.

**Comment by ktsaou** [comment]
ok. fixed it.
Thanks again!
