### ISSUE TITLE
Alarms setting

### ISSUE THREAD

**Issue by ck196** [firehol/netdata#1452]
I configured heath notify for CPU like below.
![netdata](https://cloud.githubusercontent.com/assets/1131215/21489905/98acc220-cc32-11e6-922d-85945a277723.png)

Why is colour is GREEN when CPU over 60%?

**Comment by ktsaou** [comment]
Check the warning condition. It says: set warning state, when the previous status is warning+ and the value is above 60, or the previous state is not warning+ and the value is above 85.

So, if the alarm is clear, it needs to be 85+ to enter warning state.
But to return to clear, it needs to be 60-.

**Comment by ck196** [comment]
@ktsaou thank you very much, it is very clear explain. Now I understand it.
I also want to count 5xx, 4xx on nginx_log and create alarms for it.
For now, does netdata support it?

**Comment by ktsaou** [comment]
yes, you can do it.
prepare it and post it and I'll review it. If you do it right, I'll add it to be available to everyone.

**Comment by ktsaou** [comment]
Did you build the alarm?
I am closing this ticket due to inactivity. But please post if you need help.
