### ISSUE TITLE
define redis alarms in netdata

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1453]
If you use **redis** in a production environment, please help me identify the alarms netdata should have to ensure you have a healthy redis installation.

Just post here your needs - I'll try to build alarms to satisfy them. I only expect from you to help me figure them out and test them once we have them.

**Comment by l2isbad** [comment]
What about alarms on plugins exec time?

**Comment by ktsaou** [comment]
sure, open it up as a separate issue please.

**Comment by alibo** [comment]
I think this URL can help :)
https://www.datadoghq.com/blog/how-to-monitor-redis-performance-metrics/

**Comment by ktsaou** [comment]
we have added health checks about the background save operation of redis.
I am closing this. I guess people using redis in production will request a few alarms eventually...
