### ISSUE TITLE
YOUR HELP NEEDED: define mysql/mariadb alarms in netdata

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1454]
If you use **mysql** or **mariadb** in a production environment, please help me identify the alarms netdata should have to ensure you have a healthy database installation.

Just post here your needs - I'll try to build alarms to satisfy them. I only expect from you to help me figure them out and test them once we have them.

**Comment by jurgenhaas** [comment]
When https://github.com/firehol/netdata/pull/1470 git implemented I would hope to have an alarm if the slave wasn't running anymore, value -1 for the "Slave Status" chart.

Other than that I've been working happily with a set of defaults over at ServerDensity:

- Slow Queries > 10
- Lock Wait > 20
- Threads Connected > 50

**Comment by ktsaou** [comment]
ok, let me check:

## slow queries

![image](https://cloud.githubusercontent.com/assets/2662304/21546723/83dfd37e-cde9-11e6-9218-fcd000eeab04.png)

You suggest ` > 10`.

Would that be:

1. warning when `sum of slow queries over the last 10 seconds > 10`
2. critical when `sum of slow queries over the last 10 seconds > 20`

## lock wait

![image](https://cloud.githubusercontent.com/assets/2662304/21546785/3540e82e-cdea-11e6-9053-96db0aade6cd.png)

I see on my machine this reaches up to 100:

![image](https://cloud.githubusercontent.com/assets/2662304/21546747/d6d1f328-cde9-11e6-942d-4ab2b72a8c79.png)

Would it be better to check for a ratio, like `abs(waited) * 100 / (immediate + abs(waited)) > 20` as an average over the last 10 seconds?

I would suggest `warn > 20%`, `critical > 50%`.

## threads connected

![image](https://cloud.githubusercontent.com/assets/2662304/21546882/12311dc6-cdeb-11e6-9bee-564a8aa0164f.png)

hm... I have 3 times the threshold of ServerDensity on my server.
How that can be a static number?

**Comment by ktsaou** [comment]
Also, I see the following:

## read random next

![image](https://cloud.githubusercontent.com/assets/2662304/21546990/d07edd22-cdeb-11e6-940e-2a28eeb4200d.png)

I know that when this purple line is not spiking, but is staying constantly too high, we've got problems... I need a rule of thumb though to make an alarm...

**Comment by ktsaou** [comment]
implemented a few alarms, making a PR now...

**Comment by jurgenhaas** [comment]
Looking good, I've deployed that to all my hosts and we'll see how those behave when traffic picks up early next week.

**Comment by ktsaou** [comment]
Shall we add alarms for replication? Any ideas?

**Comment by pgporada** [comment]
A replication lag alarm couldn't hurt.

**Comment by ktsaou** [comment]
> A replication lag alarm couldn't hurt.

I see this:

![image](https://cloud.githubusercontent.com/assets/2662304/21549549/86a45370-cdfb-11e6-88b1-39e79f7cf078.png)

What should we check?

**Comment by ktsaou** [comment]
@jurgenhaas do you know if the seconds behind chart will keep growing if the replication breaks? I mean, if the value will stop being collected when the replication breaks, there is no meaning to check for ` > 30`. We should check for ` = nan`.

**Comment by jurgenhaas** [comment]
The chart "Slave Status" will be either `1` or `-1` according to https://github.com/firehol/netdata/issues/1240 so the first alert should be if either sql_running or io_running is `-1`. In either of those cases the slave will start being behind the master and that period will then grow all the time until the replication starts working again.

If the current instance is not configured for replication, then this chart won't even show up as far as I understand.

**Comment by ktsaou** [comment]
Thanks!

So, 2 alarms:

1. `(sql_running == -1) OR (io_running == -1)`, checked every 10 seconds, without taking into account any history (the latest collected values).

2. `slave behind seconds > 10` (warn) and `slave behind seconds > 30` (crit).

I am preparing them now.

**Comment by jurgenhaas** [comment]
Perfect

**Comment by ktsaou** [comment]
added them to PR #1471 

Here they are:

```

template: mysql_replication
      on: mysql.slave_status
    calc: ($sql_running == -1 OR $io_running == -1)?0:1
   units: status
   every: 10s
    crit: $this == 0
   delay: down 5m multiplier 1.5 max 1h
    info: checks if mysql replication has stopped
      to: dba

template: mysql_replication_lag
      on: mysql.slave_behind
    calc: $seconds
   units: seconds
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (5)  : (10))
    crit: $this > (($status == $CRITICAL) ? (10) : (30))
   delay: down 5m multiplier 1.5 max 1h
    info: the number of seconds mysql replication is behind this master
      to: dba
```

![image](https://cloud.githubusercontent.com/assets/2662304/21550522/4419c028-ce03-11e6-9450-9859ea2d3c5d.png)

**Comment by ktsaou** [comment]
hm... `1 status`, `0 status`... what does that mean?

Would that be: `1 ok`, `0 ok`, or `1 active`, `0 active`? (unfortunately it have to be a number and a units string). What do you think?

**Comment by l2isbad** [comment]
> If the current instance is not configured for replication, then this chart won't even show up as far as I understand

Yes, if 
```
mysql> show slave status;
Empty set (0.00 sec)
```
chart won't show up

[This is a good article](https://www.percona.com/blog/2014/05/02/how-to-identify-and-cure-mysql-replication-slave-lag/) @pgporada 

Reason of replication delay either O_THREAD (netowrk?) either SQL_THREAD (queries execute time)
> MySQL replication works with two threads, IO_THREAD & SQL_THREAD

> You can calculate slave SQL_THREAD lag from Read_Master_Log_Pos – Exec_Master_Log_Pos in general as long as Master_Log_File parameter output from show slave status and Relay_Master_Log_File parameter from show slave status output are the same.

IO_THREAD  - this one we cant calculate
SQL_THREAD - can! we can see on charts if sql_thread the reason of delay or not
1. diff between Master_Log_File and Relay_Master_Log_File
2. diff between Read_Master_Log_Pos and Exec_Master_Log_Pos

**Comment by ktsaou** [comment]
@l2isbad I see on that post:

> Also, the Seconds_Behind_Master parameter shows a huge delay in seconds. However, this can be misleading, because it only measures the difference between the timestamps of the relay log most recently executed, versus the relay log entry most recently downloaded by the IO_THREAD. If there are more binlogs on the master, the slave doesn’t figure them into the calculation of Seconds_behind_master. 

Do we have a means to calculate the lag on the server? I see they have created a heartbeat: https://www.percona.com/doc/percona-toolkit/2.2/pt-heartbeat.html to monitor replication delay reliably...

**Comment by l2isbad** [comment]
well 
```
pacman --sync --search percona-toolkit
community/percona-toolkit 2.2.19-1
    Collection of advanced command-line tools to perform a variety of MySQL and system tasks.
```
```
apt-file search pt-heartbeat
percona-toolkit: /etc/percona-toolkit/pt-heartbeat.conf
percona-toolkit: /usr/bin/pt-heartbeat
percona-toolkit: /usr/share/man/man1/pt-heartbeat.1p.gz
```
We can use pt-heartbeat to calculate the replication delay - the only requirement is to install it on the master node if  i understand it right

**Comment by ktsaou** [comment]
> but is sounds the same as 'seconds behind server'

Well, the whole idea is that a slave cannot know how much time behind the master is, if it cannot communicate with the master. As I understood it, the slave calculates `seconds behind master` based only on the data it has seen.

This heartbeat is constantly writing a timestamp, so even if the slave cannot communicate with the server, it can detect the time is left behind...

**Comment by ktsaou** [comment]
Additional alarms that could be useful:

Check this: http://www.tecmint.com/mysql-mariadb-performance-tuning-and-optimization/2/

## concurrent connections limit

- `show variables` reports `max_connections`
- `show global status` reports `Max_used_connections`

So, we could calculate a percentage and add an alarm for it.

## thread_cache_size

Another interesting calculation, based on `show global status` values:

```
100 - ((Threads_created / Connections) * 100)
```

The article says:

> If you get a low number, it means that most of the new mysql connections are starting new thread instead of loading from cache. You will surely want to increase the thread_cache_size in such cases.

Does anyone have some experience with these?

**Comment by ktsaou** [comment]
merged the mysql alarms we have so far.
