### ISSUE TITLE
Help on Install - Raspberry PI - Debian (jessie)

### ISSUE THREAD

**Issue by Firemanjoe** [firehol/netdata#1461]
Hey! This looks great! I'm running what I mentioned above and I'm trying to replace my existing monitoring system to this awesome one. How can I go about getting this installed, keeping in mind that I'm rather code dumb, although I'm learning. 

Cheers!

**Comment by ktsaou** [comment]
For Raspbian, OSMC, ArchLinux, just follow the installation procedure. It works nicely.

If you have a modern RPi (v2 or v3), the default settings are good. For RPi v1 (the single core), after you install netdata edit `/etc/netdata/netdata.conf` and set `update every = 5` and restart netdata. With this setting netdata will collect data once every 5 seconds (it lowers the CPU utilization of netdata below 1%).

If you face any issues, just post here.

**Comment by jareis** [comment]
Hello,

I just tried to install in a raspberry pi debian, and in the **step 2**:

> $ bash netdata-installer.sh 
netdata-installer.sh: line 2: $'\r': command not found
: No such file or directory4: /etc/profile
netdata-installer.sh: line 5: $'\r': command not found
netdata-installer.sh: line 7: $'\r': command not found
netdata-installer.sh: line 37: syntax error near unexpected token `$'{\r''
'etdata-installer.sh: line 37: `banner() {

so I run ` $dos2unix netdata-installer.sh` before executing the netdata-installer.sh . After i discovered that autogen.sh had a similar problem so: `$dos2unix autogen.sh `

And breaked the install in:
> ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3  ... FAILED!

Any ideas?

**Comment by jareis** [comment]
Running `$ sudo ./netdata-installer.sh ` has the same behaviour...

**Comment by ktsaou** [comment]
Please do these:

```
# before root
sudo su

# install all the packages needed to build and run netdata
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
# press ENTER or Y as instructed

# download netdata
cd /usr/src
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
./netdata-installer.sh
```

Please copy and paste each line, without altering anything. They should work.

If something fails, please copy and paste here the output of the command, including the command you run (all the session of failed command).

**Comment by ktsaou** [comment]
I updated it. So, please read it on github.

**Comment by jareis** [comment]
Thanks @ktsaou, it worked.

**Comment by ktsaou** [comment]
ok. nice!
I am closing this now.

**Comment by Firemanjoe** [comment]
Thanks Everything works great on my machine as well!

**Comment by slimshizn** [comment]
This works fine, thank you. How do we go about updating this with a new release?

**Comment by seetendra** [comment]
Do these steps to update
1. cd /usr/src
2. cd netdata
3. ./netdata-installer.sh
