### ISSUE TITLE
spaces in python job names cause gaps on the charts

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1464]
In issue #1443 the root cause for the gaps has been traced down to a space being present at the job nane of module nginx_log of python.d.plugin.

**Comment by l2isbad** [comment]
```
local:
 name: 'test test'

2016-12-29 09:27:07: python.d INFO: RENAMED: fail2ban_test test , from fail2ban_local
2016-12-29 09:27:09: netdata: ERROR: PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' is requesting 
a BEGIN on chart 'fail2ban_test', which does not exist. Disabling it.
```

i did not dig into it but quick fix is to replace all spaces with '_' when renaming the job

https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L343
to
`new_name = job.__module__ + '_' + sub(r'\s', '_', job.override_name)`

Then everything works fine
`2016-12-29 09:30:54: python.d INFO: RENAMED: fail2ban_test_test , from fail2ban_local`

**Comment by ktsaou** [comment]
nice! you would like to make a PR?

**Comment by l2isbad** [comment]
done
https://github.com/firehol/netdata/pull/1467

**Comment by ktsaou** [comment]
merged! Thanks!
