### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by hrassel** [firehol/netdata#1469]
The experimental packages installer failed.

I first tried to do a update, as that did not pan out, I uninstalled it all then removed netdata folder, and tried to do a full install again. Then it came with the error below.

This is what it says:

netdata-installer.sh: 31: printf: %q: invalid directive
netdata-installer.sh: 35: printf: %q: invalid directive

  ^
netdata-installer.sh: 54: netdata-installer.sh: Bad substitution

```txt

please paste your screen here

```

**Comment by ktsaou** [comment]
Which distro? This should not happen if you have bash installed.

---
Sent from my iphone.

29 Δεκ 2016, 14:03, ο/η hrassel <notifications@github.com> έγραψε:

**Comment by hrassel** [comment]
This happens on Ubuntu 16.04, but I have a other server with the same distro where it dosent happen. 

Sendt fra min iPhone

**Comment by ktsaou** [comment]
Well, can you post the exact command you run?

**Comment by hrassel** [comment]
Sure. That would be sudo sh netdata-installer.sh

Sendt fra min iPhone

**Comment by ktsaou** [comment]
probably `sh` is not `bash`. Could you please run it directly: `sudo ./netdata-installer.sh` ?

**Comment by hrassel** [comment]
That did the trick. And the script ran fine this time. Thank you for the help. 👍🏻

Sendt fra min iPhone
