### ISSUE TITLE
MySQL charts missing

### ISSUE THREAD

**Issue by hameno** [firehol/netdata#1472]
I've just updated to rev 5326c64b22f2a9e734f9f1836cf2334c61d0ca5b and now all mysql charts disappeared - I think it is related to #1454.

Running ```/usr/libexec/netdata/plugins.d/python.d.plugin mysql``` as root works correctly, running it as netdata user shows the following error:

    2016-12-29 20:10:31: python.d ERROR: mysql_local (1227, 'Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation')

I think the netdata user needs more permissions - this should probably be documented in python.d/mysql.conf

EDIT: Running

    grant REPLICATION CLIENT on *.* to 'netdata'@'localhost';

fixes this.

**Comment by ktsaou** [comment]
Thanks for reporting this!

@l2isbad could you please check? I think it should be logging an error but not failing if it cannot get replication status information in `check()`.

**Comment by ktsaou** [comment]
This issue is a side effect of PR #1470 (added slave status monitoring).

**Comment by ktsaou** [comment]
it has been fixed!
thanks for reporting it!
