### ISSUE TITLE
what our users say about netdata?

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#148]
In this thread we collect interesting (or funny, or just plain) posts, blogs, reviews, articles, etc - about netdata.
1. don't start discussions on this post
2. if you want to post, **post the link to the original post and a screenshot!**

**Comment by ktsaou** [comment]
https://twitter.com/Simpe_li/status/715334781135929344

![image](https://cloud.githubusercontent.com/assets/2662304/14229401/ae9f8182-f93b-11e5-9378-00a614639302.png)

**Comment by ktsaou** [comment]
https://twitter.com/ZooC0d3/status/715635420583878656

![image](https://cloud.githubusercontent.com/assets/2662304/14229407/d77ee962-f93b-11e5-94e1-8660d2441db2.png)

**Comment by ktsaou** [comment]
https://blog.gillesliard.net/2016/03/31/superviser-un-serveur-avec-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14229413/113d31ae-f93c-11e5-88c3-3e54bbee3911.png)

**Comment by ktsaou** [comment]
https://twitter.com/_cirrus_minor_/status/715619555150798849

![image](https://cloud.githubusercontent.com/assets/2662304/14229417/345fc296-f93c-11e5-8238-bbfe7250e107.png)

**Comment by ktsaou** [comment]
https://twitter.com/sarmadjari/status/715459946599616512

![image](https://cloud.githubusercontent.com/assets/2662304/14229425/72ceecbe-f93c-11e5-8c4e-f73172bb1f17.png)

**Comment by ktsaou** [comment]
https://twitter.com/RootMoose/status/715340198901641216

![image](https://cloud.githubusercontent.com/assets/2662304/14229437/a5d930b0-f93c-11e5-89bb-ea646cf18454.png)

**Comment by ktsaou** [comment]
https://hackerb.it/2016/03/31/system-monitoring-netdata/

The translation of the first sentence, is the nice one:

> I have already seen some system monitoring programs, or applications, but NetData kills everything

![image](https://cloud.githubusercontent.com/assets/2662304/14229446/dc3c6622-f93c-11e5-9714-bed0be4ee912.png)

**Comment by ktsaou** [comment]
http://www.redeszone.net/2016/03/31/monitoriza-rendimiento-equipo-linux-tiempo-real-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14229481/a071e4e0-f93d-11e5-8110-35bac3fd6cd3.png)

**Comment by ktsaou** [comment]
https://www.reddit.com/r/linux/comments/4ce83u/netdata_linux_performance_monitoring_done_right/

![image](https://cloud.githubusercontent.com/assets/2662304/14229540/617bffea-f93e-11e5-802e-f5eb3a90bd26.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229542/780ebb76-f93e-11e5-8087-b8c0abd0a7ff.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229547/920f5ab2-f93e-11e5-843e-e4c7903bf4f0.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229551/b2940828-f93e-11e5-8f21-c270f24adc5f.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229556/d0d3fcc6-f93e-11e5-9318-e1e99e99ef4d.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229558/ea08bba0-f93e-11e5-8ebd-fadd194acd28.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229560/0e36901a-f93f-11e5-8970-783264d068dd.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229565/31315c80-f93f-11e5-9ffb-083bd673e57a.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229572/4ba17fa0-f93f-11e5-92ec-d2f927bacd72.png)

**Comment by ktsaou** [comment]
https://news.ycombinator.com/item?id=11388196

Hacker News folks are tough in their comments !
However, this site contributes by far the most unique visitors:

![image](https://cloud.githubusercontent.com/assets/2662304/14229588/d47cf106-f93f-11e5-91b7-1466bf0b6683.png)

**Comment by ktsaou** [comment]
https://www.techsuii.com/2016/03/31/monitoring-linux-status-with-netdata/

The title in English:

> The status of the beautiful netdata.

![image](https://cloud.githubusercontent.com/assets/2662304/14229607/46069e08-f940-11e5-8deb-5c79d8afd6b2.png)

**Comment by ktsaou** [comment]
http://www.tecmint.com/netdata-real-time-linux-performance-network-monitoring-tool/

![image](https://cloud.githubusercontent.com/assets/2662304/14229636/d40c71f0-f940-11e5-97d9-ff1d5ac6d421.png)

**Comment by ktsaou** [comment]
https://blog.ouvrard.it/2016/04/01/netdata-le-dashboard-serveur-par-excellence/

![image](https://cloud.githubusercontent.com/assets/2662304/14229642/0320ed5e-f941-11e5-983a-eb84441af21c.png)

**Comment by ktsaou** [comment]
http://www.bluebert.info/?p=442

![image](https://cloud.githubusercontent.com/assets/2662304/14229654/446b38e6-f941-11e5-8ff8-e15bc143101e.png)

**Comment by ktsaou** [comment]
https://mondedie.fr/viewtopic.php?id=8009

![image](https://cloud.githubusercontent.com/assets/2662304/14229657/766f7be0-f941-11e5-8a3b-4d77239b6686.png)

**Comment by ktsaou** [comment]
https://twitter.com/jpmens/status/715169739614588928

![image](https://cloud.githubusercontent.com/assets/2662304/14229660/afdde16e-f941-11e5-9cad-cce8a33b69bf.png)

**Comment by ktsaou** [comment]
https://korben.info/outil-surveiller-temps-reel-performances-de-machine-linux.html

![image](https://cloud.githubusercontent.com/assets/2662304/14229665/dae48a34-f941-11e5-8ade-7eddaf8f4100.png)

**Comment by ktsaou** [comment]
https://plus.google.com/+CybercitiBiz/posts/jY9UEzAwrWv

![image](https://cloud.githubusercontent.com/assets/2662304/14229671/1138dc8e-f942-11e5-995c-108e93c74e6a.png)

![image](https://cloud.githubusercontent.com/assets/2662304/14229673/28419e7a-f942-11e5-9cef-0a7bb6953cb7.png)

**Comment by ktsaou** [comment]
https://www.youtube.com/watch?v=na6x6oWYW9s

![image](https://cloud.githubusercontent.com/assets/2662304/14229682/69f23dac-f942-11e5-86e6-75bdee95a139.png)

**Comment by ktsaou** [comment]
http://mangolassi.it/topic/8715/netdata/2

![image](https://cloud.githubusercontent.com/assets/2662304/14232202/834b177a-f9aa-11e5-9e2f-83868fbf69ad.png)

**Comment by ktsaou** [comment]
http://cerebrux.net/2016/04/03/netdata-realtime-server-performance-monitoring/

![image](https://cloud.githubusercontent.com/assets/2662304/14235470/f9eed026-fa07-11e5-9dcd-f6f44a96973f.png)

**Comment by ktsaou** [comment]
http://www.monitoring-fr.org/2016/04/netdata-real-time-performance-monitoring/
https://www.youtube.com/watch?v=gMB3RSeCalk

![image](https://cloud.githubusercontent.com/assets/2662304/14242077/02660990-fa58-11e5-9ba1-d96502895d17.png)


![image](https://cloud.githubusercontent.com/assets/2662304/14242052/ccb2d7c4-fa57-11e5-933c-67af3ad0b7c7.png)

**Comment by ktsaou** [comment]
https://www.facebook.com/engintron/posts/1674960902778203

![image](https://cloud.githubusercontent.com/assets/2662304/14244675/0f72820a-fa65-11e5-8fe8-2121fe304129.png)

of course netdata is not built on node.js...

**Comment by ktsaou** [comment]
https://www.shellandco.net/live-monitor-linux-server-style/

![image](https://cloud.githubusercontent.com/assets/2662304/14254771/de63f84e-fa99-11e5-8f5b-d7b5cf9ee432.png)

**Comment by ktsaou** [comment]
http://forum.qnap.com/viewtopic.php?f=320&t=121518&sid=5dd54f41d857edd9b0fb6d1b89412480

![image](https://cloud.githubusercontent.com/assets/2662304/14274111/1477a722-fb18-11e5-9615-c4715643ebc3.png)

**Comment by ktsaou** [comment]
https://twitter.com/DanielMiessler/status/715193882003132416

![image](https://cloud.githubusercontent.com/assets/2662304/14274137/312306d2-fb18-11e5-8edd-8ea0b66df3fc.png)

**Comment by ktsaou** [comment]
https://twitter.com/GhFargo/status/717725903124619265

![image](https://cloud.githubusercontent.com/assets/2662304/14322023/1aea8d38-fc24-11e5-8624-3fa030d026bc.png)

**Comment by ktsaou** [comment]
https://twitter.com/MBombeck/status/717400058992451584

![image](https://cloud.githubusercontent.com/assets/2662304/14322064/3977fc0e-fc24-11e5-9a1a-a10da97fece6.png)

**Comment by ktsaou** [comment]
https://twitter.com/HermanHarperink/status/715588592744153088

![image](https://cloud.githubusercontent.com/assets/2662304/14322756/a64378c0-fc26-11e5-9459-352da0637137.png)

**Comment by ktsaou** [comment]
http://sebw.info/article14/netdata-real-time-performance-monitoring

![image](https://cloud.githubusercontent.com/assets/2662304/14322894/1dc08dd4-fc27-11e5-84cc-337fe2007a45.png)

**Comment by ktsaou** [comment]
http://www.osside.net/?p=15920#more-15920

![image](https://cloud.githubusercontent.com/assets/2662304/14323485/732d708c-fc29-11e5-9a31-fab207fa6354.png)

**Comment by ktsaou** [comment]
http://lignux.com/monitorea-tu-sistema-en-tiempo-real/

![image](https://cloud.githubusercontent.com/assets/2662304/14323637/f488c334-fc29-11e5-86e7-e65e5189da7e.png)

**Comment by ktsaou** [comment]
Statistics on netdata github repo:

![image](https://cloud.githubusercontent.com/assets/2662304/14323932/6855b3fc-fc2b-11e5-81ad-aaa06f01899a.png)

**Comment by ktsaou** [comment]
http://www.speed09.com/netdata-surveiller-serveur-classe/

![image](https://cloud.githubusercontent.com/assets/2662304/14349488/2271b236-fccc-11e5-82cf-d1f0a95791ea.png)

**Comment by ktsaou** [comment]
http://sysnews.net/netdata-a-real-time-performance-monitoring-tool-for-linux-systems.html

![image](https://cloud.githubusercontent.com/assets/2662304/14349548/808b92e2-fccc-11e5-840c-539d02b8fc27.png)

**Comment by ktsaou** [comment]
http://www.somosbinarios.es/monitoriza-web-tiempo-real-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14349579/afa2eabc-fccc-11e5-97a3-da6716c0448a.png)

**Comment by ktsaou** [comment]
https://lempstacker.com/tw/Try-to-use-netdata-on-CentOS-7/

![image](https://cloud.githubusercontent.com/assets/2662304/14349636/f841b398-fccc-11e5-857f-b062e85317e8.png)

**Comment by ktsaou** [comment]
https://poinsot.info/articles/linux/monitoring-sous-debian-8-avec-netdata

![image](https://cloud.githubusercontent.com/assets/2662304/14349689/59305088-fccd-11e5-92cd-9a420bc7c901.png)

**Comment by ktsaou** [comment]
More statistics:

![image](https://cloud.githubusercontent.com/assets/2662304/14375696/e54518f8-fd6b-11e5-8c3e-127d5bd784b9.png)

**Comment by ktsaou** [comment]
https://twitter.com/dagnu46/status/718155952084664320

![image](https://cloud.githubusercontent.com/assets/2662304/14402715/7b7377a4-fe46-11e5-9935-5ca6e69c57e2.png)

**Comment by ktsaou** [comment]
More github statistics:

![image](https://cloud.githubusercontent.com/assets/2662304/14402730/a94d8390-fe46-11e5-9205-400361f64501.png)


![image](https://cloud.githubusercontent.com/assets/2662304/14402725/9d7ece16-fe46-11e5-9840-ce788a4c9566.png)

**Comment by ktsaou** [comment]
https://twitter.com/francoisz/status/715512245032247297

![image](https://cloud.githubusercontent.com/assets/2662304/14402931/c769cfd2-fe4b-11e5-99e8-537924d64fef.png)

**Comment by ktsaou** [comment]
https://www.facebook.com/worldofgnome/posts/1158977147467643

![image](https://cloud.githubusercontent.com/assets/2662304/14402945/733e396a-fe4c-11e5-9dd3-897347e6d1f5.png)

**Comment by ktsaou** [comment]
http://www.linuxstyle.org/aplication/article/35

![image](https://cloud.githubusercontent.com/assets/2662304/14402957/eb925518-fe4c-11e5-8f4c-45e18d6f45b5.png)

**Comment by ktsaou** [comment]
https://twitter.com/LinuxUndIch/status/719232599802122241

![image](https://cloud.githubusercontent.com/assets/2662304/14412201/d5fc9ea6-ff65-11e5-84d1-be9f75e56143.png)

**Comment by ktsaou** [comment]
https://twitter.com/drupalero/status/718495445836820480

![image](https://cloud.githubusercontent.com/assets/2662304/14412209/15810a94-ff66-11e5-99f8-bd3a941528fd.png)

**Comment by ktsaou** [comment]
https://twitter.com/mistofvongola/status/718287350116270080

![image](https://cloud.githubusercontent.com/assets/2662304/14412218/37e00fe0-ff66-11e5-8dfb-acc34237c152.png)

**Comment by ktsaou** [comment]
https://twitter.com/igrigorik/status/718276962540609537

![image](https://cloud.githubusercontent.com/assets/2662304/14412222/59c31454-ff66-11e5-9fe0-b4f475f8822b.png)

**Comment by ktsaou** [comment]
https://twitter.com/ifraixedes/status/717382125570433024

![image](https://cloud.githubusercontent.com/assets/2662304/14412231/724dba56-ff66-11e5-84f6-60ee4810ae63.png)

**Comment by ktsaou** [comment]
https://linuxundich.de/gnu-linux/echtzeit-system-monitoring-mit-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14412286/d0e5c1ac-ff67-11e5-9940-75550b85635d.png)

**Comment by ktsaou** [comment]
More statistics:

We are reaching 9.000 stars and 500 forks!

![image](https://cloud.githubusercontent.com/assets/2662304/14444153/957c56d6-004c-11e6-84c9-443b3b312b35.png)

We still have about 2.500 unique visitors and more than 500 git clones **per day**!

![image](https://cloud.githubusercontent.com/assets/2662304/14444144/88e4f3b0-004c-11e6-888e-e45116753eb9.png)

We are still in github's trending daily (around the middle), 2nd in weekly and 2nd in monthly, in all categories. Never left these lists, since Mar 31st!

Weekly:
![image](https://cloud.githubusercontent.com/assets/2662304/14444265/26f2ab74-004d-11e6-99bf-7a7a12c45e45.png)


Monthly:
![image](https://cloud.githubusercontent.com/assets/2662304/14444256/0f8ab45e-004d-11e6-9878-99a16031afb1.png)

**Comment by ktsaou** [comment]
https://twitter.com/DatabaseLabs/status/719647702712250368

![image](https://cloud.githubusercontent.com/assets/2662304/14445157/8a1492fc-0053-11e6-9fb7-b197fba4d879.png)

**Comment by ktsaou** [comment]
https://twitter.com/sdouche/status/719636647046983680

![image](https://cloud.githubusercontent.com/assets/2662304/14475038/a4159ec0-0108-11e6-8b64-e33523566c87.png)

**Comment by ktsaou** [comment]
https://twitter.com/Liebensmittel/status/719913009775251456

![image](https://cloud.githubusercontent.com/assets/2662304/14475077/cf94493e-0108-11e6-86ab-b6df7086d443.png)

**Comment by ktsaou** [comment]
https://twitter.com/andreapernici/status/718810978977193984

![image](https://cloud.githubusercontent.com/assets/2662304/14475191/65dc036e-0109-11e6-9c41-e21c5682ed48.png)

**Comment by ktsaou** [comment]
https://twitter.com/RemzJay/status/718793398132613120

![image](https://cloud.githubusercontent.com/assets/2662304/14475225/a21b4204-0109-11e6-8d5e-6f1362d6891a.png)

**Comment by ktsaou** [comment]
https://twitter.com/c0defella/status/717417197115727872

![image](https://cloud.githubusercontent.com/assets/2662304/14475306/06597178-010a-11e6-97c0-6d1ccef11984.png)

**Comment by ktsaou** [comment]
https://twitter.com/takhirata/status/717138038590058497

![image](https://cloud.githubusercontent.com/assets/2662304/14475367/4cfd6616-010a-11e6-89c1-98ae838ba5d5.png)

**Comment by ktsaou** [comment]
https://twitter.com/yxjxx/status/716915492238331905

![image](https://cloud.githubusercontent.com/assets/2662304/14475399/7ee2a952-010a-11e6-8796-006a769f9698.png)

**Comment by centminmod** [comment]
@ktsaou just came across netdata and love it - so easy to install so it's a right candidate for integration as an official addon for my [centminmod.com](http://centminmod.com) LEMP auto installer project :)

https://twitter.com/centminmod/status/719998561904103424

**Comment by ktsaou** [comment]
Thanks! Nice!

**Comment by ktsaou** [comment]
https://twitter.com/Nept__/status/720020341582651392

![image](https://cloud.githubusercontent.com/assets/2662304/14478300/317b6754-011d-11e6-8b93-2aa97f5956ec.png)

**Comment by ktsaou** [comment]
More statistics:

![image](https://cloud.githubusercontent.com/assets/2662304/14478335/83082648-011d-11e6-82fd-62a10e0a38eb.png)

This is nice: **18.000 git clones**, around 3.000 unique visitors and 800 git clones today!

![image](https://cloud.githubusercontent.com/assets/2662304/14478342/8eecad58-011d-11e6-98ab-bdba51aa3a03.png)

No 8 on Today's Github Trending, No 4 on the Weekly, No 2 on the Monthly.

**Comment by ktsaou** [comment]
https://twitter.com/GuidoRugo/status/720081816925970433

![image](https://cloud.githubusercontent.com/assets/2662304/14486744/39a66b0a-0167-11e6-9306-517990a08a14.png)

**Comment by ktsaou** [comment]
https://n0where.net/real-time-performance-monitoring-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14505193/c6185b30-01c0-11e6-84d6-c9aacc9bbe80.png)

**Comment by ktsaou** [comment]
https://twitter.com/cryptocointalk/status/720479571112538112

![image](https://cloud.githubusercontent.com/assets/2662304/14548556/8212db9e-02c0-11e6-88ff-18c26afa4ee8.png)

**Comment by ktsaou** [comment]
https://twitter.com/xrd0/status/720658077285019648

![image](https://cloud.githubusercontent.com/assets/2662304/14548574/a83c910c-02c0-11e6-8934-cf8778affda1.png)

**Comment by ktsaou** [comment]
https://twitter.com/dazabani/status/720537652198567936

![image](https://cloud.githubusercontent.com/assets/2662304/14548586/ca6f37de-02c0-11e6-916e-e740193ce8ed.png)

**Comment by glensc** [comment]
package got added to [PLD-Linux](https://www.pld-linux.org/): https://github.com/pld-linux/netdata

**Comment by ktsaou** [comment]
> package got added to PLD-Linux: https://github.com/pld-linux/netdata

perfect!

**Comment by ktsaou** [comment]
https://twitter.com/Javisandom/status/722195595440558081

![image](https://cloud.githubusercontent.com/assets/2662304/14623935/e3007062-05de-11e6-9861-26cc1b612fd5.png)

**Comment by ktsaou** [comment]
https://twitter.com/ZooC0d3/status/722178776801652737

![image](https://cloud.githubusercontent.com/assets/2662304/14623956/fb9af28c-05de-11e6-9675-7a4a81d5d509.png)

**Comment by ktsaou** [comment]
https://twitter.com/eldracote/status/721792911860449280

![image](https://cloud.githubusercontent.com/assets/2662304/14623983/25226496-05df-11e6-8db5-7729f7348a89.png)

**Comment by ktsaou** [comment]
https://twitter.com/rasurc/status/721672060657905666

![image](https://cloud.githubusercontent.com/assets/2662304/14624006/44801bf8-05df-11e6-9859-22614da1136f.png)

**Comment by ktsaou** [comment]
https://twitter.com/ChtefiD/status/721451570337071104

![image](https://cloud.githubusercontent.com/assets/2662304/14624025/6a80adb8-05df-11e6-9040-b7be2639d88f.png)

**Comment by ktsaou** [comment]
https://twitter.com/olshek_/status/722834958306267136

![image](https://cloud.githubusercontent.com/assets/2662304/14691068/e339a754-0757-11e6-8f5a-7f9b65dad95f.png)

**Comment by ktsaou** [comment]
https://twitter.com/DietPi_/status/722819863119396864

![image](https://cloud.githubusercontent.com/assets/2662304/14691095/fdc37f5a-0757-11e6-96c0-392ffac21181.png)

**Comment by ktsaou** [comment]
https://twitter.com/ofalvai/status/722794375223193600

![image](https://cloud.githubusercontent.com/assets/2662304/14691117/19a95d84-0758-11e6-95be-d519f3cfb883.png)

**Comment by ktsaou** [comment]
https://twitter.com/pablotrianda/status/722573326380634114

![image](https://cloud.githubusercontent.com/assets/2662304/14691135/361bc024-0758-11e6-9fae-fca1ce954f62.png)

**Comment by ktsaou** [comment]
https://twitter.com/npravdin/status/722501907516891136

![image](https://cloud.githubusercontent.com/assets/2662304/14691149/4ae9ecec-0758-11e6-92a1-f1b87f54ac0f.png)

**Comment by ktsaou** [comment]
http://lamiradadelreplicante.com/2016/04/18/monitorizando-linux-en-tiempo-real-con-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14691252/e04337da-0758-11e6-84e4-16342fa6e6ff.png)

**Comment by ktsaou** [comment]
http://www.itzgeek.com/how-tos/linux/centos-how-tos/netdata-real-time-performance-monitoring-tool-for-linux.html

![image](https://cloud.githubusercontent.com/assets/2662304/14691278/0bc0312e-0759-11e6-8fdf-aac30e3f1df0.png)

**Comment by ktsaou** [comment]
http://pinoyprogrammer.co/real-time-performance-monitoring-netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14691317/373f7b16-0759-11e6-81ea-eec5197ab4c1.png)

**Comment by ktsaou** [comment]
http://notasinformaticas.com/netdata-herramienta-de-monitorizacion-para-linux/

![image](https://cloud.githubusercontent.com/assets/2662304/14691356/76446786-0759-11e6-8afb-bf33d213400e.png)

**Comment by ktsaou** [comment]
http://www.giantoaktesting.com/go/index.php?do=article&id=439

![image](https://cloud.githubusercontent.com/assets/2662304/14691365/886ef7d2-0759-11e6-818a-85f649f3f240.png)

**Comment by ktsaou** [comment]
http://www.codexiu.cn/linux/blog/8182/

![image](https://cloud.githubusercontent.com/assets/2662304/14691404/bc091136-0759-11e6-8d3b-5cb235415399.png)

**Comment by ktsaou** [comment]
https://cuongquach.com/2016/04/netdata-hostbased-monitor-tainguyen-linux/

![image](https://cloud.githubusercontent.com/assets/2662304/14691421/d70b85ae-0759-11e6-9b9e-09a7e72728a9.png)

**Comment by ktsaou** [comment]
http://forumubuntusoftware.info/viewtopic.php?f=23&t=10189&p=83041

![image](https://cloud.githubusercontent.com/assets/2662304/14694848/422c795e-0775-11e6-9fe6-834659856fd1.png)

**Comment by ktsaou** [comment]
Compiled statistics here: https://docs.google.com/spreadsheets/d/1bRTz8D8HKmjWqqNuYcOgXBTpxW4A_cCjhcdBOmDltpk/edit#gid=0

We have:

- 278.951 views,
- 79.556 unique visitors,
- 22.525 git clones,
- 17.832 unique cloners,
- 494 watchers,
- 10.465 stars,
- 622 forks

and after 22 days netdata is still on the top trending projects for:

- daily (15th),
- weekly (22nd) and
- monthly (2nd)

Wow! Thanks!

**Comment by ktsaou** [comment]
https://twitter.com/GeorgiBotzev/status/726392925656068097

![image](https://cloud.githubusercontent.com/assets/2662304/14976321/3c9a8542-1113-11e6-8ac7-a4489f496f6b.png)

**Comment by ktsaou** [comment]
https://twitter.com/amir_mehler/status/725770732416946176

![image](https://cloud.githubusercontent.com/assets/2662304/14976346/80722bee-1113-11e6-87a9-7404d5620e6e.png)

**Comment by ktsaou** [comment]
https://twitter.com/mr_timp/status/725598739256070145

![image](https://cloud.githubusercontent.com/assets/2662304/14976361/9f41838a-1113-11e6-979b-f79cf7e8510c.png)

**Comment by ktsaou** [comment]
https://twitter.com/deveth0/status/725593897527836672

![image](https://cloud.githubusercontent.com/assets/2662304/14976372/c653742e-1113-11e6-818f-973880bc2a3b.png)

**Comment by ktsaou** [comment]
https://twitter.com/juncotic/status/725317184180756480

![image](https://cloud.githubusercontent.com/assets/2662304/14976387/e85331cc-1113-11e6-9832-2e898f6bb925.png)

**Comment by ktsaou** [comment]
https://twitter.com/peerside/status/725239584657821696

![image](https://cloud.githubusercontent.com/assets/2662304/14976394/03f6d014-1114-11e6-9681-b6f1168ccc76.png)

**Comment by ktsaou** [comment]
https://twitter.com/IT_Supertramp/status/724874221873168385

![image](https://cloud.githubusercontent.com/assets/2662304/14976411/2d85d13c-1114-11e6-9132-88a0c391bd8a.png)

**Comment by ktsaou** [comment]
https://twitter.com/rajeeshknambiar/status/723920436438941696

![image](https://cloud.githubusercontent.com/assets/2662304/14976430/59cfe7dc-1114-11e6-8a8a-ac88f840d9c8.png)

**Comment by ktsaou** [comment]
https://hiob.fr/netdata/

![image](https://cloud.githubusercontent.com/assets/2662304/14981559/9d610b56-1138-11e6-8c68-e1a4e2c49ff8.png)

**Comment by ktsaou** [comment]
https://twitter.com/thewonderfall/status/727596053428572164

![image](https://cloud.githubusercontent.com/assets/2662304/14999117/dd7f545c-118f-11e6-9c10-0932ecb1d6d0.png)

**Comment by ktsaou** [comment]
https://twitter.com/GeorgiBotzev/status/726392925656068097

![image](https://cloud.githubusercontent.com/assets/2662304/15009040/d4a93b42-11ec-11e6-82c9-470629acca9a.png)

**Comment by ktsaou** [comment]
https://twitter.com/DatabaseLabs/status/719647702712250368

![image](https://cloud.githubusercontent.com/assets/2662304/15095093/d7ff02aa-14c0-11e6-9736-c34925c3b0eb.png)

**Comment by ktsaou** [comment]
https://twitter.com/milosgajdos/status/728514165879537664

![image](https://cloud.githubusercontent.com/assets/2662304/15095113/8581a5fe-14c1-11e6-8d9f-b0c7ac666d1f.png)

**Comment by ktsaou** [comment]
https://twitter.com/johefernan/status/730960714408415232

![image](https://cloud.githubusercontent.com/assets/2662304/15244136/722326ea-1908-11e6-93c9-1d8c6df60a30.png)

**Comment by ktsaou** [comment]
http://eko.one.pl/forum/viewtopic.php?id=13657

A very long screenshot of netdata running in OpenWrt.

![image](https://cloud.githubusercontent.com/assets/2662304/15244218/b5356b6e-1908-11e6-905d-1a26d31dc39e.png)

**Comment by ktsaou** [comment]
https://twitter.com/AnandNande/status/733947214154899456

![image](https://cloud.githubusercontent.com/assets/2662304/15447647/1c1fee22-1f52-11e6-9aa0-a1eba7ed0ca8.png)

**Comment by ktsaou** [comment]
https://twitter.com/devnullKen/status/734869770915479557

![image](https://cloud.githubusercontent.com/assets/2662304/15486266/1cfb8f16-214d-11e6-80ee-c3f8492fcabe.png)

**Comment by ktsaou** [comment]
https://twitter.com/Deex_Gnome/status/734511680487587840

![image](https://cloud.githubusercontent.com/assets/2662304/15486313/55819fba-214d-11e6-8bbb-8fc9d0ee2987.png)

**Comment by paulfantom** [comment]
Maybe not exactly about netdata, but there are many netdata charts in this article, and we are mentioned:
http://arstechnica.com/gadgets/2016/09/the-router-rumble-ars-diy-build-faces-better-tests-tougher-competition/

**Comment by ktsaou** [comment]
nice! Here is another one:

https://twitter.com/sk4ndix/status/775634380240871424

![image](https://cloud.githubusercontent.com/assets/2662304/18617543/a57bc4ca-7dda-11e6-8dda-542707b237af.png)

**Comment by ktsaou** [comment]
Review of netdata 1.3 in spanish:

http://www.redeszone.net/2016/09/06/ya-esta-disponible-netdata-1-3-0-conoce-las-nuevas-funciones-este-monitor-servidores-tiempo-real/

![image](https://cloud.githubusercontent.com/assets/2662304/18617556/ec8f0714-7dda-11e6-8748-9306eb40008f.png)

**Comment by ktsaou** [comment]
Enthusiastic:

https://twitter.com/kcnickerson/status/773700526890426368

![image](https://cloud.githubusercontent.com/assets/2662304/18617559/0d5ad54a-7ddb-11e6-979f-045cf9618861.png)

**Comment by ktsaou** [comment]
Another review:

https://thatservernerd.com/2016/09/05/installing-netdata-to-monitor-your-linux-environment/

![image](https://cloud.githubusercontent.com/assets/2662304/18617578/56c005de-7ddb-11e6-91e9-ef18ac001fc7.png)

**Comment by ktsaou** [comment]
https://www.linuxbabe.com/monitoring/linux-server-performance-monitoring-with-netdata

![image](https://cloud.githubusercontent.com/assets/2662304/18617584/7a39ffce-7ddb-11e6-9c18-16a0542c8290.png)

**Comment by ktsaou** [comment]
From @agross - this is how I found him:

Thanks Alexander!

![image](https://cloud.githubusercontent.com/assets/2662304/18617589/a2b0b6be-7ddb-11e6-9ceb-7397d1ebfd0a.png)

**Comment by ktsaou** [comment]
https://twitter.com/FGRibreau/status/770554988250750980

![image](https://cloud.githubusercontent.com/assets/2662304/18617596/d45b1b8c-7ddb-11e6-8785-c1ed1f6234fb.png)

**Comment by ktsaou** [comment]
https://blog.robseder.com/2016/09/19/netdata-web-based-performance-monitoring-for-linux/

**...has a ridiculously powerful and beautiful dashboard...**

![image](https://cloud.githubusercontent.com/assets/2662304/18623400/477157ee-7e45-11e6-9dcc-b3a55769fdd0.png)

**Comment by shadycuz** [comment]
One of my favorite sources of Linux how-to...
<https://twitter.com/nixcraft/status/715283444830314496>

![image](https://cloud.githubusercontent.com/assets/17090999/19956974/6117cbf6-a168-11e6-8d8c-057afa6c7c34.png)
