### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by vlvkobal** [firehol/netdata#1485]
HAPPINESS FOR EVERYBODY!

I know. Christmass and other holydays for non christians are more prominent. None the less New Year is in between the two Christmass celebrations. At least for me it's the midst of winter festival. I wish the best for all who are under the God's love!

**Comment by ktsaou** [comment]
Happy New Year guys!

Thank you for adopting and contributing to netdata!
It really makes me proud!
