### ISSUE TITLE
Visual improvement, remove loop devices from disk statistics (Disks)

### ISSUE THREAD

**Issue by cryptofuture** [firehol/netdata#1486]
Seems like zero stats shown for any loop devices.  
I know I can disable stats in config, but in my case new device created time after time. And yes I'm not sure if it really worth to collect disk stats for any loop devices at all.
In my case thats ubuntu-core snaps and canonical-livepatch(new every time with every kernel patch) snaps.   
Devices mounted to /snap/ubuntu-core/number and to /snap/canonical-livepatch/*, where `*` has new number with every kernel patch.  
Not sure what is the best solution here disable `/snap/canonical-livepatch/*` and `/snap/ubuntu-core/*`namespaces or disable stats for any loop devices. Possibly every new snap application could be installed in /snap/application/ so it might be useful in future to have disk stats per application. Thoughts?

**Comment by ktsaou** [comment]
Happy new year!

The stats you want to disable are disk performance metrics (i.e. bandwidth, operations, etc) or disk space metrics (i.e. free/used space, inodes, etc)?

**Comment by cryptofuture** [comment]
Happy New Year indeed! 
Basically all I see in disks with this devices. Not sure are we need loop devices at all, however that could be useful in some use cases, as I said above. Like if snap will become common and all applications will be mounted in separate mount point under /snap Performance disabled as for individual mount. As for now I use snap only since thats the way canonical-livepatch works. Every update as new loop device mounted under `/snap/canonical-livepatch/*` and /snap/ubuntu-core is something like system base in Debian.
Thats:
```
disk
disk_ops
disk_qops
disk_backlog
disk_util
disk_await
disk_avgsz
disk_svctm
disk_iotime
```

**Comment by l2isbad** [comment]
> remove loop devices from disk statistics

if i understand correctly it as not a good idea because mount a file as a loop device is a quick way to limit the size of the samba share (as example). 
```
# dd if=/dev/zero of=test.img bs=1M count=1024
# sudo mkfs.ext4 test.img
# sudo mount -o loop test.img /mnt/
```
And you want to collect statistics from such loops

**Comment by cryptofuture** [comment]
@l2isbad Yes, that makes sense. But in your example loop device will be static, so you can add it manually. For now I'm not sure that any charts are works for loop devices at all, since in my case devices listed with disk charts above, but all charts with zero values (empty).

**Comment by l2isbad** [comment]
works ok for me
![screenshot_20170101_144457](https://cloud.githubusercontent.com/assets/22274335/21580332/fa3ca6ac-d030-11e6-9e21-209557015a59.png)

**Comment by cryptofuture** [comment]
This is how devices looks like in config, but as already said, only ubuntu-core is static but canonical-livepatch increments by one with every patch, while previous device still represented in system.
So, another solution could exclude devices by family recursively or if family contains some world in device name config. But I' not totally sure that proper a way to do things (since thats the way to regexp at etc...)
```
[disk.loop0]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk.loop0
	# chart type = area
	# type = disk
	# family = /snap/canonical-livepatch/15
	# units = kilobytes/s
	# context = disk.io
	# priority = 2000
	# gap when lost iterations above = 1
	# name = disk.loop0
	# title = Disk I/O Bandwidth (disk.loop0)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 512
	# dim reads divisor = 1024
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -512
	# dim writes divisor = 1024

[disk_ops.loop0]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_ops.loop0
	# chart type = line
	# type = disk_ops
	# family = /snap/canonical-livepatch/15
	# units = operations/s
	# context = disk.ops
	# priority = 2001
	# gap when lost iterations above = 1
	# name = disk_ops.loop0
	# title = Disk Completed I/O Operations (disk_ops.loop0)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1

[disk_backlog.loop0]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_backlog.loop0
	# chart type = area
	# type = disk_backlog
	# family = /snap/canonical-livepatch/15
	# units = backlog (ms)
	# context = disk.backlog
	# priority = 2003
	# gap when lost iterations above = 1
	# name = disk_backlog.loop0
	# title = Disk Backlog (disk_backlog.loop0)
	# dim backlog name = backlog
	# dim backlog algorithm = incremental
	# dim backlog multiplier = 1
	# dim backlog divisor = 10

[disk_util.loop0]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_util.loop0
	# chart type = area
	# type = disk_util
	# family = /snap/canonical-livepatch/15
	# units = % of time working
	# context = disk.util
	# priority = 2004
	# gap when lost iterations above = 1
	# name = disk_util.loop0
	# title = Disk Utilization Time (disk_util.loop0)
	# dim utilization name = utilization
	# dim utilization algorithm = incremental
	# dim utilization multiplier = 1
	# dim utilization divisor = 10

[disk_iotime.loop0]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_iotime.loop0
	# chart type = line
	# type = disk_iotime
	# family = /snap/canonical-livepatch/15
	# units = milliseconds/s
	# context = disk.iotime
	# priority = 2022
	# gap when lost iterations above = 1
	# name = disk_iotime.loop0
	# title = Disk Total I/O Time (disk_iotime.loop0)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1

[disk.loop1]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk.loop1
	# chart type = area
	# type = disk
	# family = /snap/ubuntu-core/423
	# units = kilobytes/s
	# context = disk.io
	# priority = 2000
	# gap when lost iterations above = 1
	# name = disk.loop1
	# title = Disk I/O Bandwidth (disk.loop1)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 512
	# dim reads divisor = 1024
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -512
	# dim writes divisor = 1024

[disk_ops.loop1]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_ops.loop1
	# chart type = line
	# type = disk_ops
	# family = /snap/ubuntu-core/423
	# units = operations/s
	# context = disk.ops
	# priority = 2001
	# gap when lost iterations above = 1
	# name = disk_ops.loop1
	# title = Disk Completed I/O Operations (disk_ops.loop1)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1

[disk_backlog.loop1]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_backlog.loop1
	# chart type = area
	# type = disk_backlog
	# family = /snap/ubuntu-core/423
	# units = backlog (ms)
	# context = disk.backlog
	# priority = 2003
	# gap when lost iterations above = 1
	# name = disk_backlog.loop1
	# title = Disk Backlog (disk_backlog.loop1)
	# dim backlog name = backlog
	# dim backlog algorithm = incremental
	# dim backlog multiplier = 1
	# dim backlog divisor = 10

[disk_util.loop1]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_util.loop1
	# chart type = area
	# type = disk_util
	# family = /snap/ubuntu-core/423
	# units = % of time working
	# context = disk.util
	# priority = 2004
	# gap when lost iterations above = 1
	# name = disk_util.loop1
	# title = Disk Utilization Time (disk_util.loop1)
	# dim utilization name = utilization
	# dim utilization algorithm = incremental
	# dim utilization multiplier = 1
	# dim utilization divisor = 10

[disk_iotime.loop1]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_iotime.loop1
	# chart type = line
	# type = disk_iotime
	# family = /snap/ubuntu-core/423
	# units = milliseconds/s
	# context = disk.iotime
	# priority = 2022
	# gap when lost iterations above = 1
	# name = disk_iotime.loop1
	# title = Disk Total I/O Time (disk_iotime.loop1)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1

[disk.loop2]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk.loop2
	# chart type = area
	# type = disk
	# family = /snap/canonical-livepatch/17
	# units = kilobytes/s
	# context = disk.io
	# priority = 2000
	# gap when lost iterations above = 1
	# name = disk.loop2
	# title = Disk I/O Bandwidth (disk.loop2)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 512
	# dim reads divisor = 1024
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -512
	# dim writes divisor = 1024

[disk_ops.loop2]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_ops.loop2
	# chart type = line
	# type = disk_ops
	# family = /snap/canonical-livepatch/17
	# units = operations/s
	# context = disk.ops
	# priority = 2001
	# gap when lost iterations above = 1
	# name = disk_ops.loop2
	# title = Disk Completed I/O Operations (disk_ops.loop2)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1

[disk_backlog.loop2]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_backlog.loop2
	# chart type = area
	# type = disk_backlog
	# family = /snap/canonical-livepatch/17
	# units = backlog (ms)
	# context = disk.backlog
	# priority = 2003
	# gap when lost iterations above = 1
	# name = disk_backlog.loop2
	# title = Disk Backlog (disk_backlog.loop2)
	# dim backlog name = backlog
	# dim backlog algorithm = incremental
	# dim backlog multiplier = 1
	# dim backlog divisor = 10

[disk_util.loop2]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_util.loop2
	# chart type = area
	# type = disk_util
	# family = /snap/canonical-livepatch/17
	# units = % of time working
	# context = disk.util
	# priority = 2004
	# gap when lost iterations above = 1
	# name = disk_util.loop2
	# title = Disk Utilization Time (disk_util.loop2)
	# dim utilization name = utilization
	# dim utilization algorithm = incremental
	# dim utilization multiplier = 1
	# dim utilization divisor = 10

[disk_iotime.loop2]
	# history = 3600
	# enabled = yes
	# cache directory = /var/cache/netdata/disk_iotime.loop2
	# chart type = line
	# type = disk_iotime
	# family = /snap/canonical-livepatch/17
	# units = milliseconds/s
	# context = disk.iotime
	# priority = 2022
	# gap when lost iterations above = 1
	# name = disk_iotime.loop2
	# title = Disk Total I/O Time (disk_iotime.loop2)
	# dim reads name = reads
	# dim reads algorithm = incremental
	# dim reads multiplier = 1
	# dim reads divisor = 1
	# dim writes name = writes
	# dim writes algorithm = incremental
	# dim writes multiplier = -1
	# dim writes divisor = 1
```

**Comment by ktsaou** [comment]
There are several settings for you to tweak:

Check the diskstats plugin configuration:

```
[plugin:proc:/proc/diskstats]
	# enable new disks detected at runtime = yes
	# performance metrics for physical disks = auto
	# performance metrics for virtual disks = no
	# performance metrics for partitions = no
	# performance metrics for mounted filesystems = no
	# performance metrics for mounted virtual disks = auto
	# bandwidth for all disks = auto
	# operations for all disks = auto
	# merged operations for all disks = auto
	# i/o time for all disks = auto
	# queued operations for all disks = auto
	# utilization percentage for all disks = auto
	# backlog for all disks = auto
	# space usage for all disks = auto
	# inodes usage for all disks = auto
	# exclude space metrics on paths = /proc/ /sys/ /var/run/user/ /run/user/
	# filename to monitor = /proc/diskstats
	# path to get block device infos = /sys/dev/block/%lu:%lu/%s
	# path to get h/w sector size = /sys/block/%s/queue/hw_sector_size
	# path to get h/w sector size for partitions = /sys/dev/block/%lu:%lu/subsystem/%s/../queue/hw_sector_size
```

You can easily disable space charts by adding paths to `exclude space metrics on paths`. If the `/snap/` path is standards for this kind of mount points, I could add it by default to the existing list.

For performance metrics, I see in the code that netdata considers as **virtual disk**, a disk that has slaves: https://github.com/firehol/netdata/blob/93d730ebb0cff74ef68dcd3a4273ce525214fab5/src/proc_diskstats.c#L317-L327

I not sure though if we should by default disable loop devices. Possibly we could add a setting to disable certain types of disks.

Could you please post your `/proc/diskstats`?

**Comment by cryptofuture** [comment]
`exclude space metrics on paths = /proc/ /sys/ /var/run/user/ /run/user/ /snap/canonical-livepatch/ /snap/ubuntu-core/` not works so its not recursive after all.   
Btw, didn't had this string in config, mine could be old  (but I don't copypaste without reason from http://webaddress/netdata.config mine config is over 300k lines long with all that commented lines and containers with custom disabled enabled stats)
```
   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 34 0 218 36 0 0 0 0 0 36 36
   7       1 loop1 234539 0 471092 315728 0 0 0 0 0 16492 315672
   7       2 loop2 5564428 0 11129006 38853548 0 0 0 0 0 1124788 38852916
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 95517714 3870986 12136244048 2086615400 10163586 9962355 587988440 61173720 0 94271128 2166792736
   8       1 sda1 6439523 2397409 70718480 37508204 289702 8218747 68068248 6317580 0 19879780 43816812
   8       2 sda2 89075836 1473558 12065399704 2049099588 9873586 1743608 519919000 54855968 0 91612764 2122823020
 251       0 zram0 13836583 0 110692664 287096 11179625 0 89437000 630048 0 869520 912740
 251       1 zram1 13888835 0 111110680 287792 11237250 0 89898000 627052 0 876836 911312
```
Thinking about it will be cool to remove zram from disks stats also (but i didn't even know path for swap partition)
```
zram0  251:0    0 213.6M  0 disk [SWAP]
zram1  251:1    0 213.6M  0 disk [SWAP]
```
sda1 is a swap also, but its excluded from diskstats as expected.

**Comment by ktsaou** [comment]
There are 2 families of metrics collected for disks:

1. disk performance metrics (i.e. bandwidth, operations/s, etc)
2. disk space metrics (used/free space, used/free inodes)

These are independent. For example, you can have space metrics for a disk but disable performance metrics for it.

The option `exclude space metrics on paths` is used only for space metrics. Actually this is the only option you have to massively disable space metrics monitoring (after that, there are individual settings for each mount point).

For **performance metrics**, there are many options. In PR #1493 I added another one: `performance metrics for disks with major X`, where `X` is the first column on `/proc/diskstats`.

So:

- if you want to disable performance metrics for `loop` devices, add: `performance metrics for disks with major 7 = no`
- similarly to disable performance monitoring for `zram`, add `performance metrics for disks with major 251 = no`

**Comment by ktsaou** [comment]
closed automatically by github after the merge of PR #1493.
Please check it. If you still have issues, host here and I'll reopen this.

**Comment by cryptofuture** [comment]
Just tested, works as intended. It was genius idea to make exclusion by diskstats number.

**Comment by krisavi** [comment]
Sorry for bringing it up again, but for me it seems even setting the major 7 to no and manually disabling each graph of the snap drives doesn't make them disappear. The alarms and graphs are still there. Tried rebooting, restarting service. Downloading new config and modifying it. I am also getting the events for all of those drives because they show as "full".

**Comment by ktsaou** [comment]
I think you refer to **disk space** monitoring. The original issue is about **disk performance** monitoring.
Unfortunately the 2 are completely different:

- **disk space** monitoring is linked to mount points
- **disk performance** monitoring is linked to block device metrics (I/O bandwidth, operations, etc)

I think netdata has contributed to this confusion, since it attempts to "merge" the 2, when possible.

So, here is how configuration works:

## disk performance monitoring

This is the configuration that configures it:

```
[plugin:proc:/proc/diskstats]
	# enable new disks detected at runtime = yes
	# performance metrics for physical disks = auto
	# performance metrics for virtual disks = auto
	# performance metrics for partitions = no
	# bandwidth for all disks = auto
	# operations for all disks = auto
	# merged operations for all disks = auto
	# i/o time for all disks = auto
	# queued operations for all disks = auto
	# utilization percentage for all disks = auto
	# backlog for all disks = auto
	# filename to monitor = /proc/diskstats
	# path to get block device infos = /sys/dev/block/%lu:%lu/%s
	# path to get h/w sector size = /sys/block/%s/queue/hw_sector_size
	# path to get h/w sector size for partitions = /sys/dev/block/%lu:%lu/subsystem/%s/../queue/hw_sector_size
	# exclude disks = loop* ram*
	# performance metrics for disks with major 259 = yes
	# performance metrics for disks with major 253 = yes
```

The later 2 options shown are dynamic. If your system has more major numbers, they will appear here too.

The above, control the default options. For each block device you will also have this:

```
[plugin:proc:/proc/diskstats:nvme0n1]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto
```

So, you can disable all by default and enable a few, or enable all by default and disable a few.

## disk space monitoring

This is the section that configures it:

```
[plugin:proc:diskspace]
	# update every = 1
	# check for new mount points every = 15
	# exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
	# exclude space metrics on filesystems = 
	# space usage for all disks = auto
	# inodes usage for all disks = auto
```

You can exclude metrics, by adding the mount points you want to exclude to the `exclude space metrics on paths` setting.

You can also exclude one or more filesystems (i.e. `ext4`, `btrfs`, etc) to the `exclude space metrics on filesystems`.

You can also turn the "by default enabled" logic the other way around by setting `space usage for all disks` and `inodes usage for all disks` to `no`. If you do this, all disk space monitoring will be disabled by default. You can enable only the disks you want by setting the following for every disk:

```
[plugin:proc:diskspace:/]
	# space usage = auto
	# inodes usage = auto
```

You will have one section like the above, for all your mount points.

I am very sorry it was so confusing for you. I have tried to support all possible combinations... but the result is that there are way too many options to tweak...

**Comment by krisavi** [comment]
Ok,

Logically thinking ususally # means comments, so I made my config like that:

`
[plugin:proc:/proc/diskstats]
        # enable new disks detected at runtime = yes
        # performance metrics for physical disks = auto
        # performance metrics for virtual disks = no
        # performance metrics for partitions = no
        # performance metrics for mounted filesystems = no
        # performance metrics for mounted virtual disks = auto
        performance metrics for diskd with major 7 = no
        space metrics for disks with major 7 = no
        space usage for disks with major 7 = no
        bandwidth for disks with major 7 = no
        inodes usage for disks with major 7 = no
        # space metrics for mounted filesystems = auto
        # bandwidth for all disks = auto
        # operations for all disks = auto
        # merged operations for all disks = auto
        # i/o time for all disks = auto
        # queued operations for all disks = auto
        # utilization percentage for all disks = auto
        # backlog for all disks = auto
        # space usage for all disks = auto
        # inodes usage for all disks = auto
        # filename to monitor = /proc/diskstats
        # path to get block device infos = /sys/dev/block/%lu:%lu/%s
        # path to get h/w sector size = /sys/block/%s/queue/hw_sector_size
        # path to get h/w sector size for partitions = /sys/dev/block/%lu:%lu/subsystem/%s/../queue/hw_sector_size
        exclude space metrics on paths = /proc/ /sys/ /var/run/user/ /run/user/ /snap/
`
For the loop drives I made it like that

`
[plugin:proc:/proc/diskstats:loop0]
        enable = no
        # enable performance metrics = auto
        # bandwidth = auto
        # operations = auto
        # merged operations = auto
        # i/o time = auto
        # queued operations = auto
        # utilization percentage = auto
        # backlog = auto
        # enable space metrics = auto
        # space usage = auto
        # inodes usage = auto
`

**Comment by ktsaou** [comment]
So, did you fix it?

btw, a few of entries you added are not used. fetch `http://your.netdata.ip:19999/netdata.conf` and there should comments for all unused options you added.

**Comment by krisavi** [comment]
That though did not fix it. I still get alerts and graphs are still there

**Comment by ktsaou** [comment]
ok,

Could you please upload http://your.netdata.ip:19999/netdata.conf to paste-it or similar?

**Comment by krisavi** [comment]
Ok,

I think I figured it out. My netdata config dir is /opt/netdata/etc/netdata and I was changing /etc/netdata/netdata.conf 

Weird it made /etc/netdata if it is not using it nor has not used it.

**Comment by ktsaou** [comment]
One solution is to install it again in / and immediatelly uninstall it. This will remove all folders and directories.
Then re-install it in /opt since this is the final location you want.
