### ISSUE TITLE
install script shebang portability

### ISSUE THREAD

**Issue by bakman2** [firehol/netdata#150]
I am trying to install this on a synology, the bash paths are not in default directories.
Could you change the scripts to using more portable shebangs ie.
```#!/usr/bin/env bash```

**Comment by ktsaou** [comment]
I don't know if this the most portable way.
@alonbl @philwhineray any ideas?

**Comment by alonbl** [comment]
As this is not a standard shell, but bash, for these that are bash specific I would be flexible.
The other method of doing that would be to generate a stub /usr/libexec/xxx/run which will be symlinked by all our scripts /usr/libexec/xxx/firehol->run, this will in turn execute @BASH@ $0.sh "$@", the advantage is that the main script files can be written without being a template.

**Comment by bakman2** [comment]
I figured that there is no quick/dirty way to install it on Synology, as there is no zlib-dev available. 
In the end, it was easier to install chroot and install from there (i have updated the wiki with this info)

**Comment by bakman2** [comment]
I'll close this one.

**Comment by ktsaou** [comment]
> I figured that there is no quick/dirty way to install it on Synology, as there is no zlib-dev available. 
> In the end, it was easier to install chroot and install from there (i have updated the wiki with this info)

If the zlib dependency is a problem, I think the zlib folks have a way of adding it to embeddable applications (without re-distributing their entire source package). If you need this, open a github issue and I'll give it a try at some point.
