### ISSUE TITLE
Uptime badge?

### ISSUE THREAD

**Issue by jvantslot** [firehol/netdata#1507]
Really loving the badges!
Is there a system.uptime for badges?

**Comment by l2isbad** [comment]
Not yet!
But yes. I think we need uptime information under System Overview

**Comment by l2isbad** [comment]
@ktsaou do you plan to do this as internal one or i can do it on python?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1546

**Comment by ktsaou** [comment]
implemented in #1547
