### ISSUE TITLE
Missing ${PREFIX}/var/run/netdata directory on first run...

### ISSUE THREAD

**Issue by GreenDragon** [firehol/netdata#151]
**Installed with:**

`$ sudo ./netdata-installer.sh --install /opt`

**Observed:**

Running command:

/opt/netdata/usr/sbin/netdata

16-04-02 21:34:48: ERROR: netdata: Cannot create directory '/opt/netdata/var/run/netdata'. (errno 2, No such file or directory)

OK. NetData Started!

**To fix:**

```
$ sudo killall netdata
$ sudo mkdir -p /opt/netdata/var/run/netdata
$ sudo chown -R netdata:netdata /opt/netdata/var/run/netdata
$ sudo /opt/netdata/usr/sbin/netdata
```

**Comment by ktsaou** [comment]
@alonbl I think this was introduced with https://github.com/firehol/netdata/commit/458de8ae0d3c3da5626a30a2077a5116e09254cb

There is #156 to settle the pidfile once and for all.

**Comment by alonbl** [comment]
@ktsaou: the configuration is incorrect, you should use localstate to refer to /var/run if you wish to explicit use it. installing to /opt will require we create the run and clean it properly.

**Comment by ktsaou** [comment]
> the configuration is incorrect, you should use localstate to refer to /var/run if you wish to explicit use it. installing to /opt will require we create the run and clean it properly.

So, you see to pass `--localstate` at `./configure` at the installer?

**Comment by alonbl** [comment]
On 3 April 2016 at 14:03, Costa Tsaousis <notifications@github.com> wrote:

> So, you see to pass --localstate at ./configure at the installer?
>

Yes, we can add --with-rundir  to override only rundir if you like.

**Comment by ktsaou** [comment]
Well, the installer already does this:

```sh
./configure \
	--prefix="${NETDATA_PREFIX}/usr" \
	--sysconfdir="${NETDATA_PREFIX}/etc" \
	--localstatedir="${NETDATA_PREFIX}/var" \
	--with-zlib --with-math --with-user=netdata \
	CFLAGS="${CFLAGS}" || exit 1
```

**Comment by ktsaou** [comment]
I think we need `--with-rundir`, otherwise the cache files will be moved too.

**Comment by alonbl** [comment]
On 3 April 2016 at 14:22, Costa Tsaousis <notifications@github.com> wrote:

> I think we need --with-rundir, otherwise the cache files will be moved
> too.
>
Started to write this, however, once we have --pidfile= the rundir becomes
obsolete, so I suggest to resolve this within the --pidfile= change.

**Comment by ktsaou** [comment]
This has been solved with the addition of the option `-pidfile`.
I close it. If a problem remains, please open it again.
