### ISSUE TITLE
Change default System overview metrics

### ISSUE THREAD

**Issue by tijmenvn** [firehol/netdata#1511]
I would like to change the default meters for ipv4 inbound and outbound to the activity of my main network connection activity (eth0). Is it possible to change the default system overview metrics?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1253

**Comment by tijmenvn** [comment]
Okay, I tried changing the title of one chart to see if it had any effect, but starting the service again, doesn't reload the index.html it seems

**Comment by l2isbad** [comment]
You don't need to restart netdata

![screenshot_20170105_002113](https://cloud.githubusercontent.com/assets/22274335/21647265/e43f17fa-d2dc-11e6-8ba1-e61e79e9593b.png)

**Comment by tijmenvn** [comment]
![capture](https://cloud.githubusercontent.com/assets/9320891/21647541/0d00694c-d29b-11e6-88de-44057eff9065.JPG)
Great success!
