### ISSUE TITLE
/etc/netdata empty when host-binding with docker

### ISSUE THREAD

**Issue by Gmentsik** [firehol/netdata#1513]
When i run netdata with docker-compose and bind mount the 

> /etc/netdata

folder on the host via

`    volumes:
    - /srv/docker/mon/netdata:/etc/netdata
`
the folder stays empty.

Why is that?

Shouldn't the netdata image write the config files to the directory?
Netdata runs as root in the container, the folder is also owned by root.

**Comment by ktsaou** [comment]
hm... I don't know.
@titpetric could you please check this?

**Comment by Gmentsik** [comment]
I guess it has something to do how netdata docker image is built.

When I copy the contents of /etc/netdata to the volume on the host, it works of course.

I think the 'problem' is that the files are not copied during the startup of the image to the folder and if I understand docker right, the volume is assigned after all layers of the image has been downloaded and the container is starting up.

**Comment by titpetric** [comment]
@Gmentsik /etc/netdata folder is built on the container build process ofcourse, you can only provide your own contents which you then pass from your srv/docker/mon/netdata - the way docker works however, it will not copy anything out of the container in this case, neither will it keep some files which you might provide via the volume. If you need the contents of etc/netdata first, try running it without a volume mount first, and issuing something like `docker cp container:/etc/netdata /srv/docker/mon/netdata` and it should copy the files for you. Does this information resolve your issue?

Best,
Tit

**Comment by Gmentsik** [comment]
Yes this resolves the issue as already stated above.

Thanks,
GM

**Comment by muhahacz** [comment]
@titpetric 

For example:
https://github.com/muhahacz/docker-sickrage/blob/master/Dockerfile

The Sickrage creates datadir with config at start, you can mount it like -v /docker/sickrage:/config/sickrage and .. voila,
Default persistent config at a first run.
