### ISSUE TITLE
Custom chart with option nonzero and data-dimensions set

### ISSUE THREAD

**Issue by t-h-e** [firehol/netdata#1514]
The option nonzero or "NETDATA.options.current.eliminate_zero_dimensions = true;" should remove dimensions that contain only zeros, which works fine if no dimensions are specified.

If data-dimensions is set, then this flag is ignored. https://github.com/firehol/netdata/blob/master/src/rrd2json.c#L630-L636

Doesn't that seem counter-intuitive? If the user wants to show only certain dimensions, but automatically remove nonzero dimensions, that is not possible. But this could actually be done by adding or removing the nonzero flag.

**Comment by ktsaou** [comment]
You are right.
I'll remove that code to allow it work in that case too.

**Comment by ktsaou** [comment]
done!
thanks!

**Comment by t-h-e** [comment]
Sorry for not checking this earlier, but this change on its own, hasn't done the trick for me. The method `rrdr_disable_not_selected_dimensions` sets all dimensions that are specified by the user to `RRDR_NONZERO`, regardless of the option `nonzero`.

The following change fixes that: https://github.com/t-h-e/netdata/commit/cf14df5f6dc587b89f8360291d5244e7f84af618

PS: It seems kind of confusing that in the REST api the option `nonzero` removes dimensions that are all zeros and internally `RRDR_NONZERO` marks dimensions with values other than zero. Maybe renaming the `nonzero` option to `eliminate_zero_dimensions` like in the javascript case would be more expressive.

**Comment by ktsaou** [comment]
ok. I don't see any issues.
Can you make a PR?

**Comment by t-h-e** [comment]
PR https://github.com/firehol/netdata/pull/1658

**Comment by ktsaou** [comment]
well, I found an issue.

if all dimensions are zero and the nonzero option is set, then the charts are shown as empty.

If am adding code, to detect this, and enable all the zero dimensions if none is nonzero (the way it should work).

**Comment by t-h-e** [comment]
You are right. I never had that case. Thanks.
