### ISSUE TITLE
Add labels to prometheus integration

### ISSUE THREAD

**Issue by ralberto** [firehol/netdata#1519]
Hi.
I've just started playing with netdata and I really like what I've seen! :) Thank you.

Netdata integration with prometheus is a really nice feature, however I think metric names should be more generic and the usage of labels should be used to differentiate metric instances.

It's difficult to perform some analytics or create dashboards on grafana having to know all the metric names upfront when most of the metric names are generated dynamically. Let me give an example (omitted "comments") of what I think it would be more useful:

```
 apps_cpu_user{instance="inst1", "app"="netdata", ...} 8241 1483717288033
 apps_cpu_user{instance="inst1", "app"="apps_plugin", ...} 0 1483717288033
```

Using the previous format allows us to rank applications p/ cpu usage, display cpu usage p/ application in a single chart, etc... using current format we have to anticipate the metric name (apps_cpu_user_netdata; apps_cpu_user_apps_plugin), which I think is impractical. Same happens in other metrics like disk space p/ partition, etc...

I'm not so sure in scenarios like (ex. net_packets) if received / sent should be part of the metric name or a label. Ex:

```
 net_packets{instance="inst1", "interface"="eth0", "dir"="received", } 8241 1483717288033
 net_packets{instance="inst1", "interface"="eth0", "dir"="sent", } 8241 1483717288033

 # Alternative option
 net_packets_received{instance="inst1", "interface"="eth0"} 8241 1483717288033
 net_packets_sent{instance="inst1", "interface"="eth0"} 8241 1483717288033
```

I believe the first option is more flexible and makes sense, however...

What do you think? Does it make any sense? It's doable?

Thanks.

**Comment by ktsaou** [comment]
Yes, I did that and deleted, since the prometheus dev @brian-brazil thought that this is not better.

Check this conversation and examples: https://github.com/firehol/netdata/issues/1497#issuecomment-270485717

**Comment by ktsaou** [comment]
So, in the second example (http://pastebin.com/9geNGH8m), the ethernet would be:

```
net_net_received{family="enp4s0",instance="costa_pc"} 130170475 1483563048000
net_net_sent{family="enp4s0",instance="costa_pc"} 16829337 1483563048000

net_packets_received{family="enp4s0",instance="costa_pc"} 155969 1483563048000
net_packets_sent{family="enp4s0",instance="costa_pc"} 115536 1483563048000
net_packets_multicast{family="enp4s0",instance="costa_pc"} 7437 1483563048000
```

which I can turn to:

```
net_net{family="enp4s0",dimension="received",instance="costa_pc"} 130170475 1483563048000
net_net{family="enp4s0",dimension="sent",instance="costa_pc"} 16829337 1483563048000

net_packets{family="enp4s0",dimension="received,instance="costa_pc"} 155969 1483563048000
net_packets{family="enp4s0",dimension="sent",instance="costa_pc"} 115536 1483563048000
net_packets{family="enp4s0",dimension="multicast",instance="costa_pc"} 7437 1483563048000
```

**Comment by brian-brazil** [comment]
The dimension label there isn't a good label in Prometheus terms as it's not a partition on the space. You usually also want sent and received as separate metrics.

**Comment by ktsaou** [comment]
ok.

today netdata sends:

```
chartid_dimensionid{instance} value timestamp
```

should then be:

```
context_dimensionid{family,instance} value timestamp
```

?

PS: The variables netdata has are shown at: https://github.com/firehol/netdata/issues/1497#issuecomment-270485717

**Comment by ktsaou** [comment]
I added this to v1.5.0 milestone - I don't want to ship a version with the wrong support for prometheus.
So, please let me know how would you like to work, to fix it before the next release.
Thanks!

**Comment by ralberto** [comment]
Using current netdata variables and having to make a generalization, I think that the most useful line format is:
```
context_unit{instance, family, dimension, chart}
```

I know that there might be label values combinations that are not extremely useful (ex. Using label “dimension” to add sent bytes with received bytes). However, in many scenarios these labels contain values that change according to the monitored instance. It’s practical to maintain queries depending on the monitored host (i.e. number of CPUs, partitions, network interfaces, etc…), and having to enumerate all of them. From what I understand: 
* **family** - contains network interface names, partition names, etc… Ex. decomposes inodes per partition.
* **dimension** - decomposes a set of metrics per user. Ex. cpu usage, num. Threads, disk reads, page faults, etc… We need to add those values, without having to enumerate each user.
* **chart** - decomposes a set of metrics per cpu / core. Ex. cpu iowait, system, user, etc...

Maybe not an optimal solution, just a proposal using current netdata variables. 

@brian-brazil , can you help here?

**Comment by brian-brazil** [comment]
The problem is that what you say only appears to be true for a handful of metrics, most of them would combine time series into metrics that don't belong together.

While the data model has the potential to allow for automatic labels, they way it is used is far from clean enough to do so.

**Comment by ktsaou** [comment]
So, guys shall we leave it as-is or a change is required?

**Comment by brian-brazil** [comment]
I think as-is is as good as you're going to get, unless you want to do major amounts of work.

**Comment by ralberto** [comment]
Current prometheus support presents several issues. Not being able to anticipate metric names, presents a major challenge when trying to make any use of the centralized data. There are also data being centralized that can/should be deduced, causing explosion of metrics and adding confusion.

In order to be useful, I think this requires more work :-/

**Comment by ktsaou** [comment]
Guys, I need some guidelines though. I don't really understand what needs to be done. If you can provide the requirements, I could at least estimate the amount of work needed.

**Comment by brian-brazil** [comment]
You'd need to work through all of the existing metrics and figure out which of the families/dimensions are labels in the Prometheus sense and which are not.

**Comment by ktsaou** [comment]
hm... what is the problem if metrics are given to prometheus with a family that is not that useful? I mean, if we just put all the families there, then there will be a few metrics with meaningful families and a few with meaningless families. What is the problem with that?

**Comment by brian-brazil** [comment]
> What is the problem with that?

The problem is that many of them will be meaningless, as many of the families should actually be in the metric name. In addition them all having the label name "family" is likely to cause some user error when they match metrics that shouldn't be matched.

**Comment by ktsaou** [comment]
ok, got it. I think that the main feature missing is "application instance".

In this example, the redis instance monitored is `local`, which is lost:

```
redis_net_total_net_input_bytes{family="network",instance="costa_pc"} 41988 1483563048003
redis_net_total_net_output_bytes{family="network",instance="costa_pc"} 14957316 1483563048003
```

The problem is that netdata does not maintain this "application instance" in a separate field. It is part of `chartid` and there different rules depending on the plugin that generated it.

I think this has to be revisited when #807 is implemented. This would provide finer control over the names to be passed to prometheus.

**Comment by ktsaou** [comment]
There is PR #2436 that is in this direction.
Have a look.
