### ISSUE TITLE
I have 2 netadapter but it shows only one

### ISSUE THREAD

**Issue by ipcpu** [firehol/netdata#152]
I think it is better to gather network stats from /proc/net/dev.

**Comment by ktsaou** [comment]
this is where it gets the stats.

Check it: https://github.com/firehol/netdata/blob/master/src/proc_net_dev.c

Can you post your `/proc/net/dev`?

**Comment by ktsaou** [comment]
netdata will show the charts only if the interface counters (bytes, packets, etc) are not zero.
Is the interface we are talking operational?

**Comment by ipcpu** [comment]
Oh,sorry.It's my fault.
I find them in "network interfaces".
