### ISSUE TITLE
Overlays of Graphs

### ISSUE THREAD

**Issue by samof76** [firehol/netdata#1523]
Is there a way to overlays graphs from the multiple hosts? Say I crank up my own dashboard template like tv.html, is there possibility to overlays the graphs, rather than seeing them seperately?

**Comment by l2isbad** [comment]
You can add to custom dashboard [whatever you want from any server](https://github.com/firehol/netdata/wiki/Custom-Dashboards#netdata-server)
But you [cant create an aggregate charts](https://github.com/firehol/netdata/issues/1140)

**Comment by ktsaou** [comment]
I am closing this in favour of #1140
This is a feature we need, and will be implemented.
But, let's continue the discussion there.
