### ISSUE TITLE
netdata failed to install in centos 6.5 

### ISSUE THREAD

**Issue by sravanireddyk** [firehol/netdata#1537]
./configure: line 8087: syntax error near unexpected token `newline'
./configure: line 8087: `PKG_CHECK_MODULES('

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

**Comment by ktsaou** [comment]
Hi, I think you have not installed all the required packages to build it.
Could you please run:

```sh
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
```

**Comment by sravanireddyk** [comment]
Thanks for response , I still got same issue .Package which are listed are installed in my box 
 rpm -qa |grep zlib-devel
zlib-devel-1.2.3-29.el6.x86_64
libuuid-devel-2.17.2-12.24.el6_8.1.x86_64

**Comment by ktsaou** [comment]
which version of autoconf is installed?

**Comment by ktsaou** [comment]
Also, could you please post the entire log of netdata-installer.sh ?

**Comment by sravanireddyk** [comment]
./netdata-installer.sh 

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon    at /usr/sbin/netdata
   - config files  at /etc/netdata
   - web files     at /usr/share/netdata
   - plugins       at /usr/libexec/netdata
   - cache files   at /var/cache/netdata
   - db files      at /var/lib/netdata
   - log files     at /var/log/netdata
   - pid file      at /var/run

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

:-----------------------------------------------------------------------------
Running command:

./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'

:-----------------------------------------------------------------------------
Running command:

./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for a BSD-compatible install... /usr/bin/install -c
./configure: line 3766: PKG_PROG_PKG_CONFIG: command not found
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for accept4... yes
checking for struct timespec... yes
checking for clockid_t... yes
checking for library containing clock_gettime... -lrt
checking for clock_gettime... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for mallopt... yes
checking for mallinfo... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking for _Generic... no
checking for __atomic... no
checking size of void *... 8
checking host system type... (cached) x86_64-unknown-linux-gnu
checking whether sys/types.h defines makedev... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for sin in -lm... yes
./configure: line 8087: syntax error near unexpected token `newline'
./configure: line 8087: `PKG_CHECK_MODULES('

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

autoconf version -- autoconf-2.63-5.1.el6.noarch

**Comment by ktsaou** [comment]
I think your system has broken `pkg-config`. You should run the installer with option ` --libs-are-really-here`.

Can you try it?

**Comment by sravanireddyk** [comment]
actually that is the first thing i tried , then also same thing happened . I even tried  updating ,below is the package running in my box 
mingw64-pkg-config-0.28-2.el6.x86_64

**Comment by ktsaou** [comment]
@philwhineray any ideas?

**Comment by philwhineray** [comment]
Is ` mingw64-pkg-config-0.28-2.el6.x86_64` the right package? It sounds like that is to do with Windows compatibility or something, should it not be something like `pkgconfig-0.23-9.1.el6.i686.rpm`?

The configure error [PKG_PROG_PKG_CONFIG: command not found](http://stackoverflow.com/questions/17089858/pkg-config-pkg-prog-pkg-config-command-not-found) seems to also suggest the correct package to have the `pkg-config` program is not installed.

**Comment by philwhineray** [comment]
Sorry, good link but I did a bad job of interpreting it. It is the `pkg.m4` file that is not being found.

Chances are it should still be in the same package though, so that needs checking first.

**Comment by ktsaou** [comment]
@sravanireddyk  did you solve it?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. If you need help, just post.
