### ISSUE TITLE
Single dashboard for all the systems

### ISSUE THREAD

**Issue by leylmordor** [firehol/netdata#1538]
Hi, 

Is there any way to monitor all the systems which already have netdata installed in single dashboard ?

**Comment by l2isbad** [comment]
[More likely no than yes](https://github.com/firehol/netdata/wiki/Custom-Dashboards)

**Comment by ktsaou** [comment]
Unfortunately no, currently. The my-netdata menu on the top left of each dashboard, has a list of all the host, but that is all.

Could you please describe what a multi-server dashboard could show? You want just CPU, Disk I/O and RAM for each host, or you are interested for something specific?

**Comment by leylmordor** [comment]
yeah, just CPU, Disk I/O, RAM for each host on a single dashboard.

**Comment by leylmordor** [comment]
@l2isbad I can view my dashboard from those sample ones, but the other system I'm using, It does not show, it throws an error when I change the URL to the 2nd system!

**Comment by ktsaou** [comment]
> yeah, just CPU, Disk I/O, RAM for each host on a single dashboard.

thanks! that was I had in mind too. I think we will have this pretty soon.

I am closing it as a duplicate of #115
