### ISSUE TITLE
Let netdata run + monitor Nagios / Sensu Plugins 

### ISSUE THREAD

**Issue by bascht** [firehol/netdata#1540]
Hi @ktsaou! This continues the Reddit thread – I'll try to explain my idea a bit further:
At the moment netdata will only monitor, display and alert for metrics (numbers, that is). It'd be great if it could also run simple Nagios / Sensu Plugins and evaluate the output (`OK`, `WARN`, `CRIT`). Those plugins come packaged for most distributions, are independent from Nagios / Sensu and are pretty easy to run e.g.

```
$ /usr/lib/nagios/plugins/check_procs -C nginx -w 3:5
PROCS OK: 5 processes with command name 'nginx'

$ /usr/lib/nagios/plugins/check_procs -C nginx -w 3:4
PROCS WARNING: 5 processes with command name 'nginx'
```

That way Netdata could be the _only_ monitoring system one needed for a host. At the moment you'd have to use Netdata + X to monitor all aspects of one host. Netdata already has a great visualisation + alerting system, so it'd be great to have it cover this aspect as well.

Just a quick mock up of what I mean:

![screenshot from 2017-01-10 09-45-47](https://cloud.githubusercontent.com/assets/51264/21799648/704020c8-d71a-11e6-9bde-b153e7cae34b.png)

Could be way more than what you want netdata to be, but I'm interested in your thoughts. 😄

**Comment by ktsaou** [comment]
hm... I think netdata can already do what you need without need for nagios.

For example this is the number of web server processes run (examples come from https://london.my-netdata.io):

![image](https://cloud.githubusercontent.com/assets/2662304/21825848/0769b248-d78e-11e6-9ce6-0fca404f58bd.png)

You can have an alarm in netdata for them like this:

```
 alarm: nginx_processes_wrong
    on: apps.processes
  warn: $httpd < 3 OR $httpd > 5
  crit: $httpd = NaN OR $httpd = 0
    to: webmaster
```

The processes matched in `httpd` are defined in [`/etc/netdata/apps_groups.conf`](https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf). You can define your app groups to match anything you like from the process tree. This is what matches `httpd`: https://github.com/firehol/netdata/blob/392042e6cb0b3f9b366436ecef01d6e93613b67a/conf.d/apps_groups.conf#L90

and netdata can even check in alarms, the processes used memory:

![image](https://cloud.githubusercontent.com/assets/2662304/21826085/e493f57a-d78e-11e6-913d-0a35be7b0a22.png)

the processes CPU utilization:

![image](https://cloud.githubusercontent.com/assets/2662304/21826127/0310dba8-d78f-11e6-85c1-fe16fc7ef943.png)

if they are swapping:

![image](https://cloud.githubusercontent.com/assets/2662304/21826164/25140e32-d78f-11e6-80c2-f0476582ebb4.png)

the number of sockets they have open:

![image](https://cloud.githubusercontent.com/assets/2662304/21826193/3b779f22-d78f-11e6-9570-66d312552adc.png)

etc.

hm... you didn't know all these were there... hm... I need to blog more...

**Comment by ktsaou** [comment]
I updated the alarm definition to be complete...

**Comment by ktsaou** [comment]
oh I forgot.

netdata also has `fping` support: 

![image](https://cloud.githubusercontent.com/assets/2662304/21826484/57e70412-d790-11e6-83ca-c2b20f08c0f3.png)

monitors entropy:

![image](https://cloud.githubusercontent.com/assets/2662304/21826505/6e50f62c-d790-11e6-89d9-bdbae089fbdf.png)

and I am sure we can write a simple plugin to make DNS checks... (you can do it too in bash - I can show you how if you need this).

**Comment by ktsaou** [comment]
... and netdata processes the log files of your nginx web servers:

![image](https://cloud.githubusercontent.com/assets/2662304/21826695/2a61fbd6-d791-11e6-9317-52a2d3e8403f.png)

So, you can have an alarm if (for example) the ratio of 2xx responses is less than 99% of the total web requests (if you need help to write this, I can help).

**Comment by bascht** [comment]
Hey @ktsaou! Thank you soooo much for that extensive answer! I think your approach with `alarm: web_processes_running / on: apps.processes` would indeed cover my use case. I'm gonna give it a try and will report back! 😃

**Comment by bascht** [comment]
@ktsaou Update: checking and alerting with `apps.processes` works great, thanks! 
I stumbled upon another small check, that's probably a bit harder to fit into the netdata ecosystem:

```
 /usr/lib/nagios/plugins/check_ssl_cert -H example.com
SSL_CERT OK - X.509 certificate for 'example.com' from 'StartCom Class 2 IV Server CA' valid until Aug 30 09:41:20 2018 GMT (expires in 596 days)|days=596;;;;
```

I could create netdata plugin that pulls the `days_until_expired` as a metric and alerts if it goes under a certain threshold. Do you see an easier way to do that? :)

**Comment by ktsaou** [comment]
> I could create netdata plugin that pulls the days_until_expired as a metric and alerts if it goes under a certain threshold. Do you see an easier way to do that? :)

This can be a bash plugin that checks it once every 10mins or so and pushes to netdata the number of days remaining.

Ideally, this plugin could receive a configuration for multiple servers to be checked and produce a chart that has one dimension for each server checked.

**Comment by l2isbad** [comment]
@bascht @ktsaou 
I may be wrong but threre is a` sh` module for python.
So..
```
cat check_check 
#!/bin/bash
echo 'Hello world 999!' | grep -o 'world.*'

```
```
>>> import sh
>>> my_command = sh.Command('/home/lgz/check_check')
>>> data = my_command()
>>> to_netdata = {data.rstrip().split(' ')[0]: data.rstrip().split(' ')[1]}
>>> to_netdata
{u'world': u'999!'}

```

We can make `ShService` that uses custom script.
_get_raw_data()
    return  result of script

Then you only need to parse data...

**Comment by ktsaou** [comment]
yeap, that works too!

**Comment by bascht** [comment]
@ktsaou @l2isbad Thank you both for your input and support! 

Should I close this ticket until I have further questions?

**Comment by ktsaou** [comment]
perfect!
