### ISSUE TITLE
Timezone setting

### ISSUE THREAD

**Issue by ericlakich** [firehol/netdata#1544]
I would like to config netdata to display metrics in UTC instead of browser time. Is there a way to do this with the current build?

**Comment by ktsaou** [comment]
Hi. netdata displays everything at the local time of your web browser by calling javascript functions that do this automatically.

Unfortunately there is no option to change that.

The code that does this is here:

1. at the chart legends: https://github.com/firehol/netdata/blob/e98a1f05abf52168d5a13dea5234f992f295c815/web/dashboard.js#L2307

2. at the chart x-axis: https://github.com/firehol/netdata/blob/e98a1f05abf52168d5a13dea5234f992f295c815/web/dashboard.js#L4303

In theory, you can turn everything to UTC by:

- replacing `.getHours()` with `.getUTCHours()`
- replacing `.getMinutes()` with `.getUTCMinutes()`
- replacing `.getSeconds()` with `.getUTCSeconds()`
- replacing `.toLocaleDateString()` with `.toLocaleDateString(window.navigator.userLanguage, {timeZone: 'UTC'})`
- replacing `.toLocaleTimeString()` with `.toLocaleTimeString(window.navigator.userLanguage, {timeZone: 'UTC'})`

**Comment by ktsaou** [comment]
I am trying to figure if this feature is a need more people have.
So far, no one joined this discussion, so it might be pretty niche.

Before closing the issue, could you please explain why you need this feature? If this is something that more people would need, we could support it.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.

**Comment by glatapoui** [comment]
Hi !

I'm pitching in a bit late, but this issue is making my life a bit more difficult when debugging an issue: when I want to correlate activity with a suspect log message (which is in UTC), I must always do the conversion and risk looking at the wrong place in the graph.

I would love seeing that as an option, like padding or smoothing lines..

**Comment by ktsaou** [comment]
@glatapoui so you suggest to add an option to switch timezone at the browser, as a feature for easily correlating netdata view with others sources (e.g. log files).

This is a nice one. Could you please open an new github issue for this?

**Comment by Ferroin** [comment]
And make sure to reference this one so that people looking here know where to look for that discussion.

**Comment by ktsaou** [comment]
I opened it.
