### ISSUE TITLE
haproxy optimizations

### ISSUE THREAD

**Issue by hameno** [firehol/netdata#1551]
Just saw the new haproxy plugin. Great work!

I noticed some things which could probably be optimized:

1. health check currently considers backends which are in "MAINT" status as failed. I would argue that those should not count as failed as they have been intentionally disabled.

2. the default config has commented out jobs. is this intentionally?

3. chart legends are too small for the backend names. currently only 9 characters are displayed, which is rather short - maybe the whole legend part could be made wider? our backends are named like this:
```<env>-<app>-<app-module>```, e.g. ```staging-web-upload```

**Comment by hameno** [comment]
Also, it would be great if the health check could do something like this: 
warn if: one or more servers in a backend are down (but not MAINT)
crit if: all servers of a backend are down (including MAINT)

**Comment by l2isbad** [comment]
@hameno glad you like it!

1. So only alert if status is DOWN? 

2. Yes.

3. Well, this question is for @ktsaou 
 
Any other suggestion?

**Comment by hameno** [comment]
1. Yes. All other failure cases are like I described in my other comment.

**Comment by ktsaou** [comment]
> chart legends are too small for the backend names. currently only 9 characters are displayed, which is rather short - maybe the whole legend part could be made wider? our backends are named like this:
> <env>-<app>-<app-module>, e.g. staging-web-upload

Well, this is not that easy. I have tried to have variable width legend depending on the screen size, but the css is just too complex.

Currently you have 2 options:

1. hover on the legends should show the value
2. set a shorter name for each backend dimension on netdata.conf

I have on my todo to provide an alternative legend, below the charts, much like Azure does:

![image](https://cloud.githubusercontent.com/assets/2662304/21881196/ade91f6e-d8ab-11e6-9feb-a639478f6bb6.png)

**Comment by l2isbad** [comment]
This one is easy.
> warn if: one or more servers in a backend are down (but not MAINT)
Seems we need another chart for this

`{backend_name: number of servers in DOWN state for backend}`
alarm is up `if number of servers in DOWN state for backend > 0 `

Seems we need another chart for this
> crit if: all servers of a backend are down (including MAINT)

`{backend_name: total number of servers - number of servers in DOWN or MAINT}`
alarm is up `if total number of servers - number of servers in DOWN or MAINT = 0`

**Comment by hameno** [comment]
Yes, looks correct

**Comment by hameno** [comment]
Just noticed a new failure case: I forgot to apply my permission change in my puppet conf and the sockets owner/group got changed back to another user, netdata could not access the socket anymore and all charts got stuck. Maybe a "last collected" warning is also useful.

**Comment by l2isbad** [comment]
> Maybe a "last collected" warning is also useful.

sure!

One more question. [There is a status for backend](http://demo.haproxy.org) (not for server).
If 

> crit if: all servers of a backend are down (including MAINT)

Can we use backend status in such case?

**Comment by hameno** [comment]
Looks like that could work, yes.

**Comment by l2isbad** [comment]
Yeah
![screenshot_20170112_174508](https://cloud.githubusercontent.com/assets/22274335/21882677/eb0f8188-d8ee-11e6-973f-f9e4e944e5fa.png)

Then
1. Add "last collected"  alarm
2. Add new chart to chart family - backend status
3, Add 'if backend is DOWN' alarm
.
.profit!
