### ISSUE TITLE
Export graphs and statistics

### ISSUE THREAD

**Issue by Eark** [firehol/netdata#1553]
Is there some way to export graphs and other useful statistics as a file?
I'm looking at the log file but still need additional information.

**Comment by ktsaou** [comment]
There are many options, but could please describe a bit more what you need, so that I direct you to the right solution?

**Comment by Eark** [comment]
Thank you for the reply. I'm totally new to firehol/netdata and the whole Linux server. Following are the some form information we need to gather and display as a graph/table in time period. 
For example: CPU usage statistic from Jan 1 2016 - Jan 7 2016 in graph and raw data form.
Briefly, what we see in netdata save them as a log for later use.

CPU
Total CPU utilization (system.cpu)

LOAD
System Load Average (system.load)

DISK 
Disk I/O (system.io)
Disk I/O Bandwidth (disk.dm_0)
Disk Completed I/O Operations (disk_ops.dm_0)

RAM
System RAM (system.ram)

MEMORY
Committed (Allocated) Memory (mem.committed)
Committed (Allocated) Memory (mem.committed)

SWAP
System Swap (system.swap)

NETWORK
IPv4 Bandwidth (system.ipv4)
IPv4 TCP Connections (ipv4.tcpsock)
IPv4 TCP Packets (ipv4.tcppackets)
IPv4 TCP Errors (ipv4.tcperrors)
IPv4 TCP Handshake Issues (ipv4.tcphandshake)
TCP Connection Aborts (ipv4.tcpconnaborts)

PROCESSES
System Processes (system.processes)
Started Processes (system.forks) 
System Active Processes (system.active_processes)

INTERRUPTS
CPU Interrupts (system.intr)

SOFTIRQS
System softirqs (system.softirqs)

SOFTNET
System softnet_stat (system.softnet_stat)

**Comment by ktsaou** [comment]
ok. Check the API: https://github.com/firehol/netdata/wiki/REST-API-v1

netdata can export metrics in many formats: JSON, CSV, TSV, HTML, etc... it is even a google charts data  provider. You can also specify datetime ranges, data aggregation/reduction methods and points you need to get.

But, netdata does not have such a long history inside it. By default it has just 1 hour of data (you can increase this but it will use a lot of memory).

You can ask netdata to push all its metrics to a back-end time-series database, using one of the supported back-ends: https://github.com/firehol/netdata/wiki/netdata-backends - there is also support for prometheus which is not documented yet (search github, you will find the related information).

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need more help, just post.

**Comment by Eark** [comment]
Thank you for the support. I've used API methods to accomplish my task.
Cheers!
