### ISSUE TITLE
Blacklist network interfaces using wildcard

### ISSUE THREAD

**Issue by elisiariocouto** [firehol/netdata#1556]
First of all, excellent job on netdata. We are on the verge of dumping Zabbix.

We are using netdata in docker with a very minimal configuration to monitor CPU, Memory, Disk and Network from approximately 50 servers.

The problem is that docker creates virtual network interfaces (`veth<short_container_hash`) that I want to ignore. I've already set the `enable new interfaces detected at runtime` option to `no` but if the netdata container starts with an already present virtual network interface and if the interface is deleted I will get unnecessary alerts.

A way of doing this would be:
```
[plugin:proc:/proc/net/dev:veth*]
    enabled: no
```

Do you support these wildcard selectors?

**Comment by ktsaou** [comment]
> First of all, excellent job on netdata.

thank you!

> I've already set the `enable new interfaces detected at runtime option` to no but if the netdata container starts with an already present virtual network interface and if the interface is deleted I will get unnecessary alerts.

Are you sure? `enable new interfaces detected at runtime option = no` turns the default for all interfaces to `no`, so that only interfaces you explicitly set to `yes` are enabled.

I am adding an option to disable `veth` interfaces.

**Comment by ktsaou** [comment]
merged it.
There is now a veth setting too:

```
[plugin:proc:/proc/net/dev]
	# enable new interfaces detected at runtime = auto
	# enable ifb interfaces = no
	# enable veth interfaces = auto
```

**Comment by elisiariocouto** [comment]
Thank you! The only feature that is lacking to be a complete and modern replacement for classic monitoring tools is a central node whose purpose is to relay alerts and monitor connectivity to all the other `netdata` instances. OAuth2 support is also important. I've read in some issues that you're already working on these features.

Once again, good job.

**Comment by ktsaou** [comment]
Well there were more requests for excluding interfaces (#1567), so I did this:

I just added the code to allow:

```
[plugin:proc:/proc/net/dev]
	disable devices matching = lo fireqos* *-ifb
```

It accepts a space separated list of network interfaces, each of them:

- without any asterisks = exact match
- starting with asterisk = matches the suffix of the network interface name
- ending with asterisk = matches the prefix of the network interface name
- starting and ending with asterisk = matches a substring of the network interface name

If a network interface matches, it is by default disabled.
Interfaces that are by default disabled, can be enabled explicitly at their configuration section (so, you can disable all `veth*` interfaces, but keep one specific enabled.

Will merge it in a while.

**Comment by ktsaou** [comment]
merged it!

**Comment by adamancini** [comment]
The 
```
[plugin:proc:/proc/net/dev]
enable veth interfaces = no
disable devices matching = lo veth* ov*
```

options are not taking effect in my netdata dashboard - I ensured my netdata install is up to date with git and have the relevant settings in my netdata.conf - I see other settings taking effect when I restart my daemon, so the config file is being read.  When I pull my config file from localhost:19999/config, I see
```
# option 'enable veth interfaces' is not used.
        enable veth interfaces = no
 # option 'disable devices matching' is not used.
        disable devices matching = lo veth* ov*
```

Is this feature live yet?

**Comment by ktsaou** [comment]
It has been renamed/refactored with a PR later, to allow both disabling and enabling by default (each interface, even the disabled ones, will have a section where they can be individually enabled/disabled).

So it was renamed to state the fact that this setting controls the "by default" status of interfaces:

```
[plugin:proc:/proc/net/dev]
	disable by default interfaces matching = lo fireqos* *-ifb veth*
```

There is no need to copy settings from github. Just download the latest `netdata.conf` from the server and edit it:

```sh
cd /etc/netdata
mv netdata.conf netdata.conf.old
curl 'http://localhost:19999/netdata.conf' >netdata.conf.new && mv netdata.conf.new netdata.conf
```

**Comment by adamancini** [comment]
Thanks for the clarification
