### ISSUE TITLE
IPTables Rules

### ISSUE THREAD

**Issue by strk1204** [firehol/netdata#1559]
Was looking to block all trafic on interface eth0 (besides some white listed stuff including netdata) but after I did this, netdata would have on the splashscreen followed by an error being unable to load an api. Are there any other ports besides 19999 that need to be opened for netdata to work.
Thanks.

**Comment by ktsaou** [comment]
No. just 19999.

I think the splashscreen is cached on your browser. Even if this page will not be loaded if you press F5.
You can press F12 on your browser, switch to the network tab and check the failed requests.

**Comment by ktsaou** [comment]
did you solve the issue?

**Comment by strk1204** [comment]
No. Just reverted the IPTables rules.

**Comment by ktsaou** [comment]
ok. If we can do anything to help, just post.
