### ISSUE TITLE
pidfile management

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#156]
Suggested by @alonbl : https://github.com/firehol/netdata/pull/140#issuecomment-204922493

I see that pid file is created unconditionally, you should add a parameter for a service --pidfile or similar with a location of pidfile to create, if not given, do not create one. Then modify the systemd/openrc to run the service with no forking and no pidfile.

**Comment by ktsaou** [comment]
@alonbl I will add the pidfile option now, but I have a few questions:

1. currently the netdata server creates a `netdata` directory in rundir. Do we need this directory creation?

2. pidfile will only be created when the command line option `-pidfile` is given, or always? (even if this parameter is not give)

3. shall I add the pidfile option to the configuration file too, or just the command line?

4. When started as non-root, where is the proper place for the pidfile? `~/netdata.pid` ?

**Comment by alonbl** [comment]
On 3 April 2016 at 14:59, Costa Tsaousis <notifications@github.com> wrote:

> @alonbl <https://github.com/alonbl> I will add the pidfile option now,
> but I have a few questions:
>
>    1.
>
>    currently the netdata server creates a netdata directory in rundir. Do
>    we need this directory creation?
>
> I tried to remove this directory, then saw that you create it and perform
some non-standard usage.
No, you do not need to do this logic, packager/service will do that if
required.
Please notice that both openrc and systemd do not need this pidfile, this
applies only to old sysvinit scripts.


>
>    1.
>
>    pidfile will only be created when the command line option -pidfile is
>    given, or always? (even if this parameter is not give)
>
> Only when parameter is provided.


>
>    1.
>
>    shall I add the pidfile option to the configuration file too, or just
>    the command line?
>
> Only command-line, service wrapper will use it or not per its decision.


>
>    1.
>
>    When started as non-root, where is the proper place for the pidfile?
>    ~/netdata.pid ?
>
> Where --pidfile is referring... you should not guess.

Please also apply these best practices:
1. cleanup pidfile using unlink.
2. if (1) fails, truncate file.

**Comment by ktsaou** [comment]
this is done.
I close it.

**Comment by broughmilan** [comment]
I will get divorced ... so nothing else can make ... eight years marries
finally destroyed ... thanks for your help .
