### ISSUE TITLE
Authentication and registry

### ISSUE THREAD

**Issue by richardweiu** [firehol/netdata#1563]
I set authentication by nginx ,and the same time  enable the registry.

I get this problem,in our config file we can't send username and password,so we will get 401 (Unauthorized) error at the registry page.

```
[registry]
    enabled = no
    registry to announce = http://your.registry:19999
```

did I forget setting someting to save the problem?or registry and authentication can't show up together.

**Comment by ktsaou** [comment]
I think you have to pass all your netdata through the same nginx for this to work.
So, once you are authenticated to one netdata, you will be authenticated to all of them.

**Comment by richardweiu** [comment]
Thank you very much,It's a good idea.but I get a new problem lik [#731](https://github.com/firehol/netdata/issues/731)

```

jquery-2.2.4.min.js:4 GET http://xxxxx:1999/registry%20to%20announce%20=%20http://120.…nlou.com&url=http%3A%2F%2F120.26.205.4%3A1999%2Fdocker2%2F&_=1484372589613 400 (Bad Request)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
access @ dashboard.js?v20170107-5:6475
(anonymous) @ dashboard.js?v20170107-5:6428
(anonymous) @ dashboard.js?v20170107-5:6459
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
dashboard.js?v20170107-5:655 ERROR 410: Netdata registry ACCESS failed: registry to announce = http://xxx:1999/
(index):588 failed to contact the registry - loaded registry data from browser local storage
```

**Comment by richardweiu** [comment]
so I soved by adding proxy_cookie_path.

**Comment by ktsaou** [comment]
ok. I am closing this.
If you need help, just post.
