### ISSUE TITLE
Blacklist network interfaces

### ISSUE THREAD

**Issue by el-psycho** [firehol/netdata#1567]
Hi, how can I blacklist network interfaces from being monitored by netdata? I want to use netdata with ovirt hosts. The problem is that when a vm guest is created in ovirt, the hosts will have a virtual network interface for that vm with a name like vnet1. When the vm guest is destroyed and the vnet1 interface is removed, netdata starts sending alerts about not being able to reach the vnet1 network interface.

I only want to monitor the network interfaces for the host. If I could ignore/blacklist the virtual ones using a pattern like vnet* that would be great. Something along the lines of the following would be perfect:
```
[plugin:proc:/proc/net/dev:vnet*]
        enabled = no
```
Thanks.

**Comment by ktsaou** [comment]
I just added the code to allow:

```
[plugin:proc:/proc/net/dev]
	disable devices matching = lo fireqos* *-ifb
```

It accepts a space separated list of network interfaces, each of them:

- without any asterisks = exact match
- starting with asterisk = matches the suffix of the network interface name
- ending with asterisk = matches the prefix of the network interface name
- starting and ending with asterisk = matching a substring of the network interface name

If a network interface matches, it is by default disabled.
Interfaces that are by default disabled, can be enabled explicitly at their configuration section (so, you can disable all `vnet*` interfaces, but keep one specific enabled.

Will merge it in a while.

**Comment by ktsaou** [comment]
merged it!

**Comment by el-psycho** [comment]
Thank you for the quick fix! Great project.
