### ISSUE TITLE
drop root privileges from apps.plugin

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#157]
Moved from: https://github.com/firehol/netdata/issues/149#issuecomment-204838428

netdata is not running as root. Even if started as root, it switches to another user.

Only apps.plugin is running as root because it cannot do otherwise. It needs to read the entire `/proc` filesystem (mainly the files /proc/X/io are the problem).  These files state the I/O of each process. Let's see one:

```sh
# cat /proc/29983/io
rchar: 321648498
wchar: 96160
syscr: 589846
syscw: 2199
read_bytes: 98852864
write_bytes: 9093120
cancelled_write_bytes: 0
```

They are harmless. But let's see their persmissions:

```sh
# ls -l /proc/29983/io
-r-------- 1 root squid 0 Apr  2 13:43 /proc/21398/io
```

If you know of a way to read these files, other than being root, we will be glad to do it.

CC: @alonbl

**Comment by alonbl** [comment]
> This is what netdata already does. Only apps.plugin runs as root.

it should run as a separate /service/ not as a plugin, the plugin should run as netdata and communicate with the separate service.

**Comment by ktsaou** [comment]
> it should run as a separate /service/ not as a plugin, the plugin should run as netdata and communicate with the separate service.

ok, apps.plugin will still have to run as root? If so, what is the gain?

**Comment by alonbl** [comment]
> ok, apps.plugin will still have to run as root? If so, what is the gain?

well, the apps.plugin will run as netdata, there will be a separate service that runs as root, you can claim that the separate service is the same logic, that's true, however the least privilege model instructs that only the minimum code will run as privilege... The concept of drop privileges is obsoleted.

in both openrc and systemd you can have dependency, so a service will be started before the main service, provide various of features, in your case, read /proc artifacts.

**Comment by ktsaou** [comment]
Sorry @alonbl. I still don't get it.

apps.plugin is the minimum isolated part that has to run as root. It is already isolated and it is already the minimum required.

To achieve this today, it is setuid to root. Netdata starts it as non-privileged user but because it is setuid to root, it works.

If I get it right, you propose to have it as a different service, meaning that it will not be setuid to root any more, but systemd or openrc will start it as root.

So, at the end of the day, apps.plugin will still run as root. We cannot avoid this.

Let's say we did it. Why this would be better than a simple setuid to root? Actually I find it a lot more complex (two init scripts, two services that will depend on each other and will probably will have to be synchronized, started in the proper sequence at boot, etc).

So, what is the gain?

**Comment by alonbl** [comment]
@ktsaou: as long as suid works for you - you are ok. please keep in mind that the suid feature is slowly depreciated in containers and selinux.

**Comment by ktsaou** [comment]
Is it possible to remove the `root` requirement from apps.plugin using, for example, capabilities?

**Comment by alonbl** [comment]
well, you can try to use CAP_DAC_OVERRIDE or CAP_FOWNER, but in these as well you will need a new process, easiest to achieve this in a new service as service manager will be able to assign these capabilities to your process.

**Comment by Kubuxu** [comment]
You could use:
```
CAP_DAC_OVERRIDE
              Bypass file read, write, and execute permission checks.  (DAC
              is an abbreviation of "discretionary access control".)
```
http://man7.org/linux/man-pages/man7/capabilities.7.html

**Comment by philwhineray** [comment]
Another possibility to lose setuid would be to invoke via sudo and require that the administrator grant passwordless invocation of the script for the netdata user. This is closer to the separate service model but without all the overhead and effort that would go into securing a separate root service.

In either case, I think best practice would be for the plugin to open or call what it needs to as early as possible with as little logic as possible, before dropping rights for any other processing.

**Comment by alonbl** [comment]
@philwhineray: sudo is also a problematic tool for containers and selinux environments, it designed as interactive tool and has same issues of suid. same goes for dropping rights.

**Comment by Kubuxu** [comment]
Even better:
```
       CAP_DAC_READ_SEARCH
              * Bypass file read permission checks and directory read and
                execute permission checks;
```

So you can just open and read all files.

**Comment by mcnewton** [comment]
Even if it stays suid, there are probably some extra checks that can be made. For example checking that the user calling the apps.plugin binary is the netdata user configured in the config script.

Currently any user can run it and get all the stats, which may not be desirable. Installing it as root/netdata 4750 is probably a good idea, which works for me.

root/netdata 0750 combined with appropriate capabilities is probably the best option.

**Comment by mcnewton** [comment]
Not looking too promising :(

Works:
> chown root:root apps.plugin
> chmod 4755 apps.plugin

and

> chown root:netdata apps.plugin
> chmod 4750 apps.plugin

Doesn't work:
> chown root:root apps.plugin 
> chmod 755 apps.plugin 
> setcap cap_dac_read_search+ep apps.plugin

or

> chown root:root apps.plugin 
> chmod 755 apps.plugin 
> setcap cap_dac_override+ep apps.plugin

or

> chown root:root apps.plugin
> chmod 755 apps.plugin 
> setcap cap_fowner+ep apps.plugin

Maybe there are other ideas?

Shipping an apparmor profile would definitely be a good idea (and possibly whatever selinux does, but I've never used that) to lock down the binary. At least for those that have the sense to use it, anyway!

**Comment by mcnewton** [comment]
OK, there must be a capability of some sort that works, because:

> chmod 755 apps.plugin 
> chown root:root apps.plugin 
> setcap all=eip apps.plugin

works fine (easiest way to test is to do `$ ./apps.plugin | grep Per`).

Just to find the required capability....

**Comment by mcnewton** [comment]
Phew... took some searching. Got it! Good job you can pass numeric capability values to setcap, so a sort of binary chop on the numbers made it much easier:

> chown root:netdata apps.plugin
> chmod 0750 apps.plugin
> setcap cap_dac_read_search,cap_sys_ptrace+ep apps.plugin

This starts up (as non-root) with no Permissions errors, and seems to work fine, no suid required.

Not sure if it's possible for the netdata daemon to set these capabilities and then run the plugin, to save them having to be set on the filesystem? Maybe a new config options so it's extensible to other plugins as well? I think this should be possible with libcap. But the netdata daemon would then need to retain more capabilities itself to be able to do that. e.g.

> [plugin capabilities]
> apps.plugin = cap_dac_read_search,cap_sys_ptrace+ep

Cheers,
Matthew

**Comment by alonbl** [comment]
guys, this is exactly the reason why the privilege escalation should be in different service and communicate via ipc. the new service should be started as root or netdata with a specific capability set.

**Comment by Kubuxu** [comment]
netdata can't set capabilities, it would either need to run as root, or have capability for that which is almost equal running as root.

In my opinion, capabilities should be set during installation of the modules. Modules should check if they have required capabilities and report them missing if that is the case.

This way there is no need for separate processes, root access is required only during installation. Also it allows unprivileged user to run netdata if capabilities are already set on modules files and those modules can be executed by this user (shared group?)

**Comment by alonbl** [comment]
Having multiple least privileged model is preferable in term of security. I
do not like starting as root and dropping privileges nor adding extra
capabilities to the main process.

**Comment by ktsaou** [comment]
I guess this is the way to go:

> chown root:netdata apps.plugin
> chmod 0750 apps.plugin
> setcap cap_dac_read_search,cap_sys_ptrace+ep apps.plugin

thanks @mcnewton for tracing this down !

I will check the docs to adapt apps.plugin to check it has these capabilities.

**Comment by ktsaou** [comment]
> I will check the docs to adapt apps.plugin to check it has these capabilities and show a meaningful error message otherwise.

Well, it seems that checking the process capabilities from C, requires linking with libcap. I don't like to add this dependency now. So, I have switched the make files and the installer to set the right capabilities (thanks @mcnewton !), but I will not add the few lines that will print a nice error message.

I think, at some point netdata will have to have capabilities itself, and probably manage the capabilities of its plugins. When we reach that point, I will add the right message.

The PR is #405 (together with the registry #310 ).

**Comment by ktsaou** [comment]
I mark this as fixed and clone it.
Thank you all!

**Comment by ktsaou** [comment]
Hm... it seems that setcap does not work on NFS shares.
I adapted the makefiles to fallback to setuid...

**Comment by mcnewton** [comment]
Hmm, bummer on NFS. Don't really ever think of anyone running anything on NFS these days (systems I mean - data yes, reluctantly).

Falling back to suid is probably the only option available in that case. Though maybe it would be safer to leave it broken and to report to the person installing it that they need to do it, rather than doing it automatically? I can't imagine that installing on NFS is that common, and anyone doing it will have set it up deliberately so should understand the risks of adding an suid binary.

**Comment by ktsaou** [comment]
> Hmm, bummer on NFS. Don't really ever think of anyone running anything on NFS these days (systems I mean - data yes, reluctantly).

well... NFS is common for diskless machines. nfsroot is great especially for IoT. For example, I have all my RPis boot from nfs - this is really the best solution, since NFS is a lot faster/bigger/more reliable than SD cards, it allows updating a lot of devices centrally, backing up centrally, etc.

Think home automation, industrial monitoring machines, etc. netdata is a killer app for these devices, since it is very small, it call collect custom sensor values and they can control the CPU and memory resources allocated to it. I see a few vendors are already adding it to their solutions: https://market.jeedom.fr/index.php?v=d&p=market&type=plugin&plugin_id=2369&utm_source=dlvr.it&utm_medium=twitter

**Comment by ktsaou** [comment]
In PR #1676 I updated apps.plugin to check its capabilities and give instructions to the user, as suggested by @Kubuxu here:

> Modules should check if they have required capabilities and report them missing if that is the case.

So, this is done!
Thanks!
