### ISSUE TITLE
How do I exclude certain NICs from interface_last_collected_secs alarm?

### ISSUE THREAD

**Issue by Bilge** [firehol/netdata#1571]
I keep getting alarms emailed to me about `net.vethXXXXXXX` interfaces (Docker pseudo-devices) being critical.

> interface last collected secs = 66 seconds ago

I think this is coming from the interface_last_collected_secs template, but it is unclear from the `health.d/net.conf` config or the documentation how to disable this alarm for certain interfaces, since neither seem to mention exclusions.

I would like to be able to specify an exclusion pattern that can match `net.veth*` or similar.

**Comment by ktsaou** [comment]
in PR #1570 I added the capability to match chart families in alarm templates.

This is done like this:

```
template: NAME
      on: CONTEXT
families: SIMPLE PATTERN TO MATCH FAMILIES
...
```

`SIMPLE PATTERN` is like this:

1. a space separated list of `words`
2. each `word` may have one or more asterisks
3. `words` starting with `!`, give a negative match
4. processing of `words` is left-to-right

Examples:

1. match everything:

```
families: *
```

2. match nothing:

```
families: !*
```

3. match only veth interfaces:

```
families: veth*
```

4. match everything except veth interfaces:

```
families: !veth* *
```

5. match all veth interfaces except veth2:

```
families: !veth2 veth*
```

6. match tun, br, veth interfaces, except tun3, br4 and veth12:

```
families: !tun3 !br4 !veth12 tun* br* veth*
```

You get the idea...

This is not extensively tested, so I would appreciate your help.
Until this is merged, checkout `https://github.com/ktsaou/netdata.git` and install it, like the main repo.

**Comment by ktsaou** [comment]
PR #1570 is merged.
So, just update your netdata.

**Comment by Bilge** [comment]
Thanks Costa, I will try it soon!

On 16 Jan 2017 10:31, "Costa Tsaousis" <notifications@github.com> wrote:

PR #1570 <https://github.com/firehol/netdata/pull/1570> is merged.
So, just update your netdata.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/firehol/netdata/issues/1571#issuecomment-272825556>,
or mute
the thread
