### ISSUE TITLE
Alarm Badges

### ISSUE THREAD

**Issue by jvantslot** [firehol/netdata#1573]
I seem to be having an issue with creating a badge for an alarm status.

Following the instructions in the [Health monitoring](hhttps://github.com/firehol/netdata/wiki/health-monitoring#api-calls) section of Wiki, I've been trying to 'use the following URL: `http://your.netdata.ip:19999/api/v1/badge.svg?alarm=NAME`, obviously replacing the host my my netdata server's hostname and port.

I've used the URL: `http://your.netdata.ip:19999/api/v1/alarms?all`

To determine what I *think* is the proper value for NAME for the alarm that I want the badge to display. but no matter what value I pass to the api, it returns `No chart id is given at the request.`.

Do I need to pass additional parameters?  What would the proper NAME value to pass if not the "name" parameter of the JSON results for an alarm?

Thanks for any hints!

FYI: Using version `d88d8db37528ede0ce986feff2f8c59d14fc909a`

**Comment by ktsaou** [comment]
At the alarms API call you get something like this:

```json
{
	"hostname": "costa-pc",
	"latest_alarm_log_unique_id": 1480441719,
	"status": true,
	"now": 1484526098,
	"alarms": {
		"system.softnet_stat.1hour_netdev_backlog_exceeded": {
			"id": 1480363647,
			"name": "1hour_netdev_backlog_exceeded",
			"chart": "system.softnet_stat",
			"family": "softnet_stat",
			"active": true,
			"exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "sysadmin",
			"source": "3@/etc/netdata/health.d/softnet.conf",
			"units": "packets",
			"info": "number of packets dropped because sysctl net.core.netdev_max_backlog was exceeded (this can be a cause for dropped packets)",
			"status": "CLEAR",
			"last_status_change": 1484525934,
			"last_updated": 1484526054,
			"next_update": 1484526114,
			"update_every": 60,
			"delay_up_duration": 0,
			"delay_down_duration": 1800,
			"delay_max_duration": 3600,
			"delay_multiplier": 1.500000,
			"delay": 0,
			"delay_up_to_timestamp": 1484525934,
			"lookup_dimensions":"dropped",
			"db_after": 1484522455,
			"db_before": 1484526054,
			"lookup_method": "sum",
			"lookup_after": -3600,
			"lookup_before": 0,
			"lookup_options": "absolute unaligned",
			"warn":"$this > 0",
			"warn_parsed":"($this > 0)",
			"green":null,
			"red":null,
			"value":0
		},
```

You need to pass `http://your.netdata.ip:19999/api/v1/badge.svg?chart=CHART&alarm=NAME`

where `CHART` is the `chart:` line shown above and `NAME` is the `name:` line shown above.

The wiki says that for badges, the `chart=` parameter is the only one required.

I updated the wiki page with this: For alarm badges, **both `chart` and `alarm` parameters are required**.

I am very sorry this was confusing...

**Comment by jvantslot** [comment]
Perfect!  `chart=CHART` was what I was missing. 

Works like a charm now!

Thanks!
