### ISSUE TITLE
Use docker container name instead of container id

### ISSUE THREAD

**Issue by felixoi** [firehol/netdata#1576]
I think we should use the docker `container name` instead of the docker `container id`. At the moment a docker container in netdata looks like this:
![Current Look of Docker Containers](https://i.gyazo.com/869d85d05693d9182477354c329dbbf1.png)
Because the `container name` is also unique, I think we should use the `container name` for better recognizability.

The example docker container I have:
![Docker Container Information](https://i.gyazo.com/636b60399767e4ef321262c5df4de18f.png)

**Comment by ktsaou** [comment]
it should work if user netdata is in the docker group (the installer does this already).
did you fix it?

**Comment by felixoi** [comment]
Yes, something gone wrong. After an reinstall everything was working.
