### ISSUE TITLE
QOS class names not showing in netdata

### ISSUE THREAD

**Issue by teeby** [firehol/netdata#1577]
I have downloaded the latest version of netdata  and firehol on a Centos 6.5 server.  Both worked out of the box after installing the prerequisites. 

I am using fireqos and have created some classes based on the tutorial examples and this has worked ok with the tc rules being created. However when I look at the QOS section of netdata rather than seeing my classs names I am seeing 1:11, 1:12 etc. Also the interface is still called eth4 and eth4-ifb rather than using the name I put in the interface statement.

 I went though it twice to make sure I had followed everything correctly but still get the same issue. 

I found that the helper script /usr/libexec/netdata/plugins.d/tc-qos-helper.sh had this line
fireqos_run_dir="var/run/fireqos"
but the install had actually created the directory as /usr/local/var/run/fireqos.  So I updated that and restarted netdata but still no luck.

So I am now looking for suggestions on what else to check.

**Comment by ktsaou** [comment]
strange.

keep in mind you can override this variable in `/etc/netdata/tc-qos-helper.conf`: https://github.com/firehol/netdata/blob/c2d103df701b1c1feae020f44eb3a942845b3aeb/plugins.d/tc-qos-helper.sh#L75

Could you please run `ls -l /usr/local/var/run/fireqos/` ?

**Comment by teeby** [comment]
[root@sam fireqos]# ls -l /usr/local/var/run/fireqos/
total 32
drwxr-xr-x 2 root root 4096 Jan 13 17:45 ifaces
drwxr-xr-x 2 root root 4096 Jan 13 17:45 ifbs
-rw-r--r-- 1 root root 8680 Jan 18 09:33 isp_gw-in.conf
-rw-r--r-- 1 root root 8598 Jan 18 09:33 isp_gw-out.conf


my fireqos config is pretty much one from the examples to test it before I modify it, but just changed the interface to reflect my device.

 configure the netdata ports
    server_netdata_ports="tcp/19999"

    interface eth4 isp_gw bidirectional ethernet balanced rate 20Mbit
       class arp
          match arp

       class icmp
          match icmp

       class dns commit 1Mbit
          server dns
          client dns

       class ntp
          server ntp
          client ntp

       class ssh commit 2Mbit
          server ssh
          client ssh

       class rsync commit 2Mbit max 10Mbit
          server rsync
          client rsync

       class web_server commit 10Mbit
          server http
          server netdata

       class client
          client surfing

       class nms commit 1Mbit
          match input src 10.2.3.5



I don't see the interface name or the class names and the result looks (if this paste works) like this.

 
![image](https://cloud.githubusercontent.com/assets/25155646/22058640/90f07618-dd61-11e6-95e4-1ce6a71a0e6e.png)

**Comment by ktsaou** [comment]
If you run the plugin by hand you will get something like this:

```sh
$ /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
BEGIN eth2-ifb
class htb 1:8000 parent 1:1 leaf 20: prio 1 rate 12Kbit ceil 100Mbit burst 1599b cburst 1600b
 Sent 93236131 bytes 970143 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 970143 borrowed: 0 giants: 0
 tokens: 16041656 ctokens: 1925

class htb 1:11 parent 1:1 leaf 11: prio 0 rate 6500Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 189328071757 bytes 197350751 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 194699945 borrowed: 0 giants: 0
 tokens: 28726 ctokens: 28726

class htb 1:1 root rate 100Mbit ceil 100Mbit burst 1600b cburst 1600b
 Sent 189421307888 bytes 198320894 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 1867 ctokens: 1867

class htb 11:11 parent 11:1 leaf 12: prio 0 rate 110Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 70066000 bytes 136364 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 136327 borrowed: 37 giants: 0
 tokens: 1276125 ctokens: 21591

class htb 11:1 root rate 6500Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 189328065291 bytes 197350717 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 120758747 borrowed: 0 giants: 0
 tokens: 28726 ctokens: 28726

class htb 11:13 parent 11:1 leaf 14: prio 2 rate 1300Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 2688513616 bytes 10558609 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 10493718 borrowed: 64889 giants: 0
 tokens: 133458 ctokens: 26688

class htb 11:12 parent 11:1 leaf 13: prio 1 rate 1300Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 4401581365 bytes 18604209 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 17070060 borrowed: 1517529 giants: 0
 tokens: 143650 ctokens: 28726

class htb 11:15 parent 11:1 leaf 16: prio 4 rate 325Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 23615501871 bytes 19959196 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 7362151 borrowed: 12597045 giants: 0
 tokens: 574605 ctokens: 28726

class htb 11:14 parent 11:1 leaf 15: prio 3 rate 325Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 615375 ctokens: 30765

class htb 11:16 parent 11:1 leaf 17: prio 5 rate 1950Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 96609456078 bytes 61864757 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 28985374 borrowed: 32641891 giants: 0
 tokens: 7433 ctokens: 2226

class htb 11:18 parent 11:1 leaf 19: prio 7 rate 12Kbit ceil 6500Kbit burst 1599b cburst 1599b
 Sent 56601826152 bytes 81044001 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 7178413 borrowed: 71483237 giants: 0
 tokens: -184483 ctokens: 27707

SETDEVICENAME world-in
SETCLASSNAME 11:11 dsl/voip
SETCLASSNAME 11:12 dsl/interactive
SETCLASSNAME 11:13 dsl/vpns
SETCLASSNAME 11:14 dsl/servers
SETCLASSNAME 11:15 dsl/synacks
SETCLASSNAME 11:16 dsl/surfing
SETCLASSNAME 11:8001 dsl/default
SETCLASSNAME 11:18 dsl/background
SETCLASSNAME 1:8000 default
SETDEVICEGROUP eth2
END eth2-ifb
```

The SETDEVICENAME / SETCLASSNAME lines are the ones generating this information.
Could you please verify they are generated?

**Comment by teeby** [comment]
No when I run it I don't get the SETDEVICENAME or SETCLASSNAME generated.

BEGIN eth4-ifb
class htb 1:11 parent 1:1 leaf 11: prio 4 rate 200000bit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 56040 bytes 934 pkt (dropped 0, overlimits 0 requeues 0)
 rate 48bit 0pps backlog 0b 0p requeues 0
 lended: 934 borrowed: 0 giants: 0
 tokens: 960000 ctokens: 9610

class htb 1:1 root rate 20000Kbit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 114004217 bytes 224012 pkt (dropped 0, overlimits 0 requeues 0)
 rate 19656bit 12pps backlog 0b 0p requeues 0
 lended: 87373 borrowed: 0 giants: 0
 tokens: 3313 ctokens: 3313

class htb 1:13 parent 1:1 leaf 13: prio 4 rate 1000Kbit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 200000 ctokens: 10000

class htb 1:12 parent 1:1 leaf 12: prio 4 rate 200000bit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 247340 bytes 432 pkt (dropped 0, overlimits 0 requeues 0)
 rate 8bit 0pps backlog 0b 0p requeues 0
 lended: 432 borrowed: 0 giants: 0
 tokens: 960000 ctokens: 9610

class htb 1:15 parent 1:1 leaf 15: prio 4 rate 2000Kbit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 941892 bytes 12732 pkt (dropped 0, overlimits 0 requeues 0)
 rate 1008bit 2pps backlog 0b 0p requeues 0
 lended: 12732 borrowed: 0 giants: 0
 tokens: 95000 ctokens: 9500

class htb 1:14 parent 1:1 leaf 14: prio 4 rate 200000bit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 6450 bytes 72 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 72 borrowed: 0 giants: 0
 tokens: 940000 ctokens: 9407

class htb 1:17 parent 1:1 leaf 17: prio 4 rate 10000Kbit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 51120 bytes 544 pkt (dropped 0, overlimits 0 requeues 0)
 rate 104bit 0pps backlog 0b 0p requeues 0
 lended: 544 borrowed: 0 giants: 0
 tokens: 19204 ctokens: 9610

class htb 1:16 parent 1:1 leaf 16: prio 4 rate 2000Kbit ceil 10000Kbit burst 1600b cburst 1600b
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 100000 ctokens: 20000

class htb 1:8000 parent 1:1 leaf 20: prio 4 rate 200000bit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 91041411 bytes 175597 pkt (dropped 0, overlimits 0 requeues 0)
 rate 9360bit 8pps backlog 0b 0p requeues 0
 lended: 103903 borrowed: 71694 giants: 0
 tokens: 65430 ctokens: 3313

class htb 1:19 parent 1:1 leaf 19: prio 4 rate 1000Kbit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 rate 0bit 0pps backlog 0b 0p requeues 0
 lended: 0 borrowed: 0 giants: 0
 tokens: 200000 ctokens: 10000

class htb 1:18 parent 1:1 leaf 18: prio 4 rate 200000bit ceil 20000Kbit burst 1600b cburst 1600b
 Sent 21659964 bytes 33701 pkt (dropped 0, overlimits 0 requeues 0)
 rate 9128bit 2pps backlog 0b 0p requeues 0
 lended: 18022 borrowed: 15679 giants: 0
 tokens: 955000 ctokens: 9563

END eth4-ifb
WORKTIME 17

**Comment by teeby** [comment]
So looking through the script for the setclassname function I can see the stuff about /etc/iproute2/tc_cls.
When i check the directory I don't have a tc_cls file.

**Comment by teeby** [comment]
I ran a yum update iproute
ran netdata-updater.sh 
re-edited the helper plug back to the /usr/local/var/run/fireqos directory 

and now it is showing the class names.  I am not sure exactly what it was that "fixed" this but I will assume it was to do with the iproute.

**Comment by ktsaou** [comment]
> looking through the script for the setclassname function I can see the stuff about /etc/iproute2/tc_cls

this is an alternative method, for non-fireqos rules.

> re-edited the helper plug back to the /usr/local/var/run/fireqos directory

any change to the script will be overwritten when you re-install/update netdata.
I suggest to set this variable in `/etc/netdata/tc-qos-helper.conf`. This file persists updates.

**Comment by ktsaou** [comment]
I guess we can close this. Yes?

**Comment by teeby** [comment]
I don't have a /etc/netdata/tc-qos-helper.conf file. I don't have a tc-qos-helper.conf anywhere on the filesystem.  Do you have to create one if you want one? Not sure otherwise how I'm missing this.  Other than that, as I now have the class names  this issue is resolved and therefore can be closed.

**Comment by ktsaou** [comment]
> Do you have to create one if you want one

yes, create it.
