### ISSUE TITLE
Unclear navigation with many docker containers

### ISSUE THREAD

**Issue by felixoi** [firehol/netdata#1583]
This is only my opinion I'm curious about yours:

When having many docker containers the navigation looks like this at the moment:

- Overview
- ...
- Docker Container 1
- Docker Container 2
- ... More Docker Containers ...
- ...

I think this makes the navigation very unclear and fully stuffed. My suggestion is to create a collapsable point "Docker Containers":

- Overview
- CPU
- Docker Containers
    * Docker Container 1
    * Docker Container 2
    * ... More Docker Containers ...
- ...

I think that makes the navigation cleaner.

**Comment by ktsaou** [comment]
I agree. This is why I opened #345 some time ago.

The whole idea with containers is that containers may also contain containers which may also contain containers, etc. So, the whole idea with a menu like that is pretty limited. Yes, I know this is not the case for most containers today, but I see it coming...

Another issue with containers is that processing them is quite CPU intensive. I think I have done a very nice improving it (netdata is 4 times faster in monitoring containers as of yesterday), which made it possible to monitor **systemd services using cgroups**, but still... there are way too many metrics.

Hopefully, we will adapt the UI at some point to become more functional.

**Comment by ktsaou** [comment]
I am closing this. Let's continue this discussion on #345
