### ISSUE TITLE
Disks locked every 3 minutes because of netdata

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#1585]
Just found after several hours that python processes are causing disks locked every 3 minutes for 1-2 seconds, i have proofs with my custom IO scripts which record any IOwait at the second level 👍 

```
01/17/2017 10:48:06 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          16.88    0.00    4.94   50.81    0.00   27.38

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   190.00    0.00  525.00     0.00     7.14    27.87    47.92  152.98    0.00  152.98   1.90 100.00
sdb               0.00   426.00    1.00 1436.00     0.07     8.99    12.91   155.00   61.46 1887.00   60.19   0.70 100.00
```

I have disabled netdata which uses python a lot, my ioscript does not record anymore locked disks

If confirmed, netdata can be good to be enabled punctually for investigations... or python is interfering with something else on server (centos 6 + cpanel + cloudlinux progs using python for some + https://github.com/AnoopAlias/XtendWeb)

**Comment by ktsaou** [comment]
is this a physical or a virtual server?
If this is physical, do you monitor the temperatures of the disks with netdata?

**Comment by ktsaou** [comment]
Keep in mind you can disable the python plugin in netdata and still view what exactly is happening.
Also, I would appreciate your description of "locked disks".

**Comment by yoorshop** [comment]
Hello,

I mean 100% disk utilization on all disks...

This morning, nothing anymore abnormal.

I noted same processes of cpanel and lvestats also

weird !

**Comment by yoorshop** [comment]
I must mentioned thqt disks app is displaying limited things from now, and i did not change any settings in python.d.conf, not collecting anymore details of sda and sdb, but remain dev/shm and /var only

**Comment by ktsaou** [comment]
well, do this:

1. start netdata
2. wait for it to happen
3. check the Application section
4. check the disk subsection
5. check these charts:

![image](https://cloud.githubusercontent.com/assets/2662304/22054913/fc547766-dd60-11e6-91f1-118b6b5f26ca.png)

netdata does not read anything from disks (some plugins may do, but nothing significant).
netdata does not write to disks, except its access log (only when you view the dashboard).

Can you post a screenshot?

**Comment by yoorshop** [comment]
Yes i have this from beginning, but this is not sda and and sdb like i had, they disappeared, in top dashboard, and also in disk section, see screenshots
![netd-dash](https://cloud.githubusercontent.com/assets/10398236/22055300/d1397ee2-dd5a-11e6-9f84-5e631dba97d7.PNG)
![netd-dash1](https://cloud.githubusercontent.com/assets/10398236/22055302/d346f9b2-dd5a-11e6-875d-faf85b517e9b.PNG)

**Comment by yoorshop** [comment]
look screenshot, even with group we see nothing else then netdat user
all was working yesterday

netdata was stopped over night, only thing i did, and now 2 hours 
![netd-dash2](https://cloud.githubusercontent.com/assets/10398236/22055513/c7d1b2ec-dd5b-11e6-96ae-65dcc7fcfdd7.PNG)
that i restarted it

**Comment by ktsaou** [comment]
You are probably having `grsecurity` enabled and netdata cannot read from `/proc` filesystem. So these charts are empty.

**Comment by yoorshop** [comment]
no, i use orignal kernel, there has never been any grs on this server, all was working yesterday

I'm ano going to upgrade install

**Comment by yoorshop** [comment]
no change after upgrade...

**Comment by yoorshop** [comment]
My observium uses snmp, and still continue to show me all as
![snmp-observium](https://cloud.githubusercontent.com/assets/10398236/22056380/29c3589e-dd60-11e6-9fc9-157bb6937046.PNG)

usual, issue is with your app

**Comment by yoorshop** [comment]
content of /proc/diskstats

   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 72575341 1398354 2245743342 39179769 253005057 140444459 5827107616 274345389 1 34232230 313370036
   8       1 sda1 1898525 755019 110497084 1518540 3845019 8222352 247361496 23979024 1 6716679 25496946
   8       2 sda2 176 34 1680 19 0 0 0 0 0 19 19
   8       3 sda3 70676366 640392 2135219114 37661138 222081677 132222107 5579746120 250154930 0 31181300 287701818
   8      16 sdb 85542649 21438501 1942218538 373585775 43870109 77951650 2162823832 607335878 0 214827773 980897255
   8      17 sdb1 85542360 21435503 1942192242 373584869 43869204 77951650 2162823832 607335822 0 214827253 980896291

**Comment by ktsaou** [comment]
ok, but what about `ls -l /proc/diskstats` ?

**Comment by yoorshop** [comment]
[root@web1 ~]# ls -l /proc/diskstats
-r--r--r-- 1 root root 0 Jan 18 09:46 /proc/diskstats
[root@web1 ~]#

**Comment by yoorshop** [comment]
Ah, all is back, after doing the 2 things you told me
![netd-dash3](https://cloud.githubusercontent.com/assets/10398236/22057056/5b5c2996-dd63-11e6-876e-0738faf65320.PNG)

all this is a little weird

**Comment by yoorshop** [comment]
partial, still no sda and sdb details

**Comment by ktsaou** [comment]
please update this issue too.

Keep in mind netdata drops all privileges while running. This is the right way to do this job and it explains the reason other solutions can work on your system but netdata faces issues.

If you still face problems allowing netdata to read the information it needs, you can run it as root. I don't suggest this though. The right way is to fix your system.

**Comment by yoorshop** [comment]
these sda and sdb appears interminttently in fact, don't knwo how to make it stable

**Comment by yoorshop** [comment]
Our server is holding 1250 websites with cpanel cloudlinux, you can imagine that server has no issue, there is 2 sysadmin managing it and me

**Comment by ktsaou** [comment]
Run netdata as root:

edit /opt/netdata/etc/netdata/netdata.conf and set:

```
[global]
    run as user = root
    web files owner = netdata
    web files group = netdata
```

and restart netdata.

Now check who is using your disk in the applications section of the dashboard.

**Comment by yoorshop** [comment]
done, no change

**Comment by ktsaou** [comment]
hm... can you post the charts of your disks?

**Comment by ktsaou** [comment]
@yoorshop have you solved the issue?

I am closing this. If you need help, please start netdata and post the disk utilization charts, like the following.

## per app

http://london.my-netdata.io/#menu_apps_submenu_disk

![image](https://cloud.githubusercontent.com/assets/2662304/22621469/4b3071d0-eb2d-11e6-9edc-a46935cdd026.png)

## per user

http://london.my-netdata.io/#menu_users_submenu_disk

![image](https://cloud.githubusercontent.com/assets/2662304/22621473/65749efe-eb2d-11e6-86e5-7f37d9d8fca4.png)

## per user group

http://london.my-netdata.io/#menu_groups_submenu_disk

![image](https://cloud.githubusercontent.com/assets/2662304/22621479/84e6a458-eb2d-11e6-80ae-37b9e3c0313a.png)


## per systemd service (if you run systemd)

http://london.my-netdata.io/#menu_services_submenu_disk

![image](https://cloud.githubusercontent.com/assets/2662304/22621488/a539e9cc-eb2d-11e6-97d7-cb029059429f.png)
