### ISSUE TITLE
Display process running

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#1587]
Hi,

It would be nice to have processes from top and pidstat in some way, and be able to cross with IO + iostat graphs to find issues/culprits causes

**Comment by ktsaou** [comment]
netdata breaks down all system usage:

1. per Application
2. per User
3. per User Group
4. per Systemd Services

So, it already there.

**Comment by yoorshop** [comment]
netdata stop, and start change nothing, and double check any python.d activation

**Comment by ktsaou** [comment]
Which distro is this?

**Comment by yoorshop** [comment]
centos 6

**Comment by ktsaou** [comment]
A container or virtual machine?

The distro is missing `/proc/diskstat`, or netdata cannot read it. If the Applications section is showing only netdata, then netdata cannot read files from /proc.

Are you using grsecurity?
Please post `uname -a`.

**Comment by yoorshop** [comment]
no grs, and this is a dedicated server

**Comment by ktsaou** [comment]
`uname -a` please.
Check your netdata error.log It must be complaining...

**Comment by yoorshop** [comment]
[root@web1 netdata]# uname -a
Linux web1.hosting1976.fr 2.6.32-673.26.1.lve1.4.20.el6.x86_64 #1 SMP Tue Dec 27 17:42:53 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@web1 netdata]#

I have no error.log in folder netdata

**Comment by yoorshop** [comment]
My observium uses snmp, and still continue to show me all as 
![snmp-observium](https://cloud.githubusercontent.com/assets/10398236/22056361/153aa5e4-dd60-11e6-9afd-51823df32355.PNG)
usual, issue is with your app

**Comment by ktsaou** [comment]
check `/var/log/netdata/error.log`.

**Comment by yoorshop** [comment]
It did not exist, i created it with file

no change

**Comment by ktsaou** [comment]
Did you use the `--install` option at the `netdata-installer.sh`?

**Comment by yoorshop** [comment]
yes, i have things in /opt/netdata

**Comment by ktsaou** [comment]
Then `/opt/netdata/var/log/netdata/error.log`.

**Comment by yoorshop** [comment]
I just did a service netdata restart

graph in top dashboard disappeared again

**Comment by yoorshop** [comment]
2017-01-18 09:55:58: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-01-18 09:55:59: apps.plugin: ERROR: pid 481212 netdata states parent 1, but the later does not exist.
2017-01-18 09:55:59: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-01-18 09:56:00: apps.plugin: ERROR: pid 481212 netdata states parent 1, but the later does not exist.
2017-01-18 09:56:00: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-01-18 09:56:01: apps.plugin: ERROR: pid 481212 netdata states parent 1, but the later does not exist.
2017-01-18 09:56:01: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-01-18 09:56:02: apps.plugin: ERROR: pid 481212 netdata states parent 1, but the later does not exist.
2017-01-18 09:56:02: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-01-18 09:56:03: apps.plugin: ERROR: pid 481212 netdata states parent 1, but the later does not exist.
2017-01-18 09:56:03: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)

**Comment by yoorshop** [comment]
2017-01-18 09:57:09: netdata: Too many logs (201 logs in 139 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1061 seconds.

**Comment by yoorshop** [comment]
after 

[root@web1 ~]# service netdata stop
Stopping netdata...                                        [  OK  ]
[root@web1 ~]# service netdata start
Starting netdata...                                        [  OK  ]
[root@web1 ~]#

graph in top dashboard show up again

but still no sda and sdb device
2017-01-18 09:59:42: apps.plugin: ERROR: pid 487867 netdata states parent 1, but the later does not exist.
2017-01-18 09:59:42: netdata: ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)

all was working yesterday, and of course no one played with file diskstats

**Comment by ktsaou** [comment]
ok, do these:

```sh
# become user netdata
su -s /bin/bash netdata

# check /proc/diskstats
cat /proc/diskstats
```

Does it work?

**Comment by yoorshop** [comment]
[root@web1 ~]# su -s /bin/bash netdata
bash-4.1$ cat /proc/diskstats
cat: /proc/diskstats: No such file or directory
bash-4.1$

**Comment by ktsaou** [comment]
as you can see, you do have something there...

**Comment by yoorshop** [comment]
file exist of course, but netdata does not see it anymore whereas yesterday was the case, and my observium continue with no issue

**Comment by ktsaou** [comment]
did you solve it? can we close this issue?

**Comment by yoorshop** [comment]
This was a feature request about detailed process like top can give

**Comment by ktsaou** [comment]
> This was a feature request about detailed process like top can give

yes, and it already exists. What is missing?

**Comment by yoorshop** [comment]
I think we don't understand from beginning on this

Show me a screenshot of process running as root, nobody as an example, 
not tagged as system i mean

**Comment by ktsaou** [comment]
I think I forgot to answer this.

> Show me a screenshot of process running as root, nobody as an example

ok, here we are:

## systemd services

http://london.my-netdata.io/#menu_services_submenu_cpu

![image](https://cloud.githubusercontent.com/assets/2662304/22621402/bceab850-eb2b-11e6-9156-134472cc0ac0.png)

## applications (grouped via /etc/netdata/apps_groups.conf)

http://london.my-netdata.io/#menu_apps

![image](https://cloud.githubusercontent.com/assets/2662304/22621410/f56f4fa6-eb2b-11e6-8159-2cee8213a2a4.png)

## users

http://london.my-netdata.io/#menu_users

![image](https://cloud.githubusercontent.com/assets/2662304/22621416/0dac54ba-eb2c-11e6-91d6-e1f808fa77a7.png)


## user groups

http://london.my-netdata.io/#menu_groups

![image](https://cloud.githubusercontent.com/assets/2662304/22621419/22247d3c-eb2c-11e6-88d9-e9a826000866.png)

## alarms on all the above

You can write alarms for anything that interests you. Check the discussion at https://github.com/firehol/netdata/issues/1540#issuecomment-271709101

---

So, I would love to understand what you need that is missing.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.

**Comment by bigrana** [comment]
I have solve the same problem on CentOS Linux release 7.3.1611 (Core), to solve the problem i had must use this command chmod +s /usr/libexec/netdata/plugins.d/apps.plugin instead of chmod 4755 /usr/libexec/netdata/plugins.d/apps.plugin that use the installer

**Comment by ktsaou** [comment]
oops! are you sure? Could you please help me identify the issue?

```sh
# chmod 4755 /usr/libexec/netdata/plugins.d/apps.plugin 
# ls -l /usr/libexec/netdata/plugins.d/apps.plugin 
-rwsr-xr-x. 1 root root 259936 Jul  8 01:49 /usr/libexec/netdata/plugins.d/apps.plugin
```

```sh
# chmod +s /usr/libexec/netdata/plugins.d/apps.plugin 
# ls -l /usr/libexec/netdata/plugins.d/apps.plugin 
-rwsr-sr-x. 1 root root 259936 Jul  8 01:49 /usr/libexec/netdata/plugins.d/apps.plugin
```

So, the only diff I see is that `+s` forces the group id too.

If you have not installed netdata in a docker container, the installer would have [set capabilities](https://github.com/firehol/netdata/blob/de0ef9d43fae22052222a2a8ab49c04d61e694e7/netdata-installer.sh#L758).
