### ISSUE TITLE
Dial-graphs misaligned in Safari/OS X

### ISSUE THREAD

**Issue by bakman2** [firehol/netdata#159]
As subject, the "dial"-graphs show up misaligned, when hovering over the graph below, the graphs "jump" and align properly. Suspect a css/float issue ? 
![dial](https://cloud.githubusercontent.com/assets/333960/14232117/c0b9101a-f99d-11e5-9c20-0642827273a2.jpg)

**Comment by ktsaou** [comment]
I don't have Safari/OS X, so anyone with such a setup, please make a PR.

**Comment by bakman2** [comment]
in the source code after the h2's
```<div style="width: 100%;height:107px; text-align: center;">```
to force the 107px height, probably not the most elegant solution, but appears to be working.

**Comment by Geng-G-Razor** [comment]
@bakman2 May I ask that , how could you install this on a mac? I tried to do this ,but failed.

**Comment by ktsaou** [comment]
You cannot install it on a mac. You can install it on a Linux and use it from a mac.

**Comment by Geng-G-Razor** [comment]
@bakman2 @ktsaou Oh, I see, thank you.
