### ISSUE TITLE
netdata user in haproxy group after netdata update

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#1591]
Having a previous version of netdata in a server that has haproxy running, after using netdata-updater.sh script to update the program, I have to manually add the netdata user to haproxy group to start monitoring it. I don't know if this is the expected behaviour or is a mistake.

I've done the same process in a varnish server (to test the varnish plugin) and works perfectly; the user netdata is added to the varnish group.

**Comment by ktsaou** [comment]
thanks!
@l2isbad we should add it at the installer.

**Comment by ktsaou** [comment]
It is now added.
Thanks!
