### ISSUE TITLE
varnish plugin not showing graphs

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#1592]
I'm testing the varnish plugin in server with the following versions:

```
OS: ubuntu 14.04 
varnish: 3.0.5-2
```

The netdata is updated using the netdata-updater.sh script. I've also checked that the netdata user is in the varnish group.

The problem is that the graphs are not working, only the memory usage that I can assume it uses another command than `varnishstat`:

![seleccion_073](https://cloud.githubusercontent.com/assets/378158/22113146/9df89e1c-de65-11e6-84b4-93e6e30d3fb8.png)

I've also tested manually that the netdata user can execute the `varnishstat` command and works perfectly:

`sudo -u netdata varnishstat`

I've also checked the netdata logs an the plugin seems to be running:

> 2017-01-19 16:24:29: python.d INFO: varnish Plugin was started successfully
> 2017-01-19 16:24:29: python.d INFO: CHECKED OK: varnish

Any idea of which can be the problem?

**Comment by LeeNX** [comment]
I suspect this is because netdata currently only expected to support Varnish v4+, not Varnish V3, seeing that Varnish 4.0 and below EOL  
  
Varnish v3 - https://www.varnish-cache.org/lists/pipermail/varnish-announce/2015-April/000702.html  
Varnish V4.0 - https://lists.gt.net/varnish/announce/39909?page=last  
  
I still run some Varnish V3.0 systems, so this is a bit of a pity, but reason to upgrade.

**Comment by l2isbad** [comment]
Varnish 3. is super old. I think a good idea is to modify check function to fail if it is not 4+. The output in error log is OK which is confusing.
Or another way is to add varnish 3 support )
I see all information wee need is present in `varnishstat` output.
[varnishstat-not-root-but-varnishlog_group-V3.txt](https://github.com/firehol/netdata/files/704060/varnishstat-not-root-but-varnishlog_group-V3.txt)

**Comment by l2isbad** [comment]
@dseira 
Looks like it as a 'one character fix'
Can you change
https://github.com/firehol/netdata/blob/master/python.d/varnish.chart.py#L91

`self.rgx_all = compile(r'([A-Z]+\.)?([\d\w_.]+)\s+(\d+)')`

and restart netdate service

?

**Comment by l2isbad** [comment]
Other changes
1. sess_conn and sess_drop in v4 = client_conn and client_drop in v3
.
.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1596
