### ISSUE TITLE
Mysql crash...

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#1593]
We had enabled mysql plugin only from yesterday

After consulting cloudlinux about what could be the cause, their answer is clear 👍 :

Developers were able to identify that the issue caused by function ut_error in some srv_error_monitor mysql service. Quite similar bugreport http://bugs.mysql.com/bug.php?id=70430

**Comment by ktsaou** [comment]
Hi,

Do you imply that netdata is causing mysql to crash?

Well, netdata is executing only 2 mysql commands: `show global status;` and `show slave status;`: https://github.com/firehol/netdata/blob/d46acae54b160f2114c0c6d873437d1188fecf56/python.d/mysql.chart.py#L42-L43

Other than that, it is a perfectly normal and valid mysql client, like any other application.

**Comment by yoorshop** [comment]
I agree, but coincidence is strange...

I updated mysql, let see if happens an issue in next days.

Alqo, disabling mysql does not work, it still continues to monitor mysql whatever i do

**Comment by l2isbad** [comment]
@yoorshop 
[/opt/netdata/etc/netdata]grep mysql **python.d.conf**
`mysql: no`

**Comment by yoorshop** [comment]
still not

This is confusing to hav folders in /etc/ /opt/, and /root/, 3 folders for same app

**Comment by ktsaou** [comment]
> This is confusing to hav folders in /etc/ /opt/, and /root/, 3 folders for same app

Put source code in `/usr/src`.
Since you installed it in `/opt`, everything for its runtime is in `/opt`.

**Comment by yoorshop** [comment]
Can you be more specific about 
Put source code in /usr/src
?

I merge /etc/netdata, and /root/netdata, to a single folder in /usr/src/netdata ?

**Comment by l2isbad** [comment]
`/root/netdata` is source code (if you did `git clone` as a root)

**Comment by yoorshop** [comment]
I performed cleaning etc.... mysql plugin still not diabled

**Comment by l2isbad** [comment]
Pls show output
`ps aux | grep netdata`
`sudo grep mysql /opt/netdata/etc/netdata/python.d.conf`

also clear error.log
restart netdata service
and 
`grep mysql /opt/netdata/var/log/netdata/error.log `

**Comment by ktsaou** [comment]
@yoorshop did you solve it?
I am closing this, but please post if you need more help.
