### ISSUE TITLE
Default alarm ram_in_swap on macOS not correct

### ISSUE THREAD

**Issue by simonnagl** [firehol/netdata#1598]
Because the legend of system.ram differ this alarm is to hight on macOS.

For a local fix I changed the alarm to this:
``` 
From 2f5de7bdf745059bb9c257caaa412f9eae14edc1 Mon Sep 17 00:00:00 2001
From: Simon Nagl <sin6332@thi.de>
Date: Fri, 20 Jan 2017 14:42:14 +0100
Subject: [PATCH] Fix alarm ram_in_swap on macOS

---
 conf.d/health.d/swap.conf | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/conf.d/health.d/swap.conf b/conf.d/health.d/swap.conf
index 7f57560..6cc68a5 100644
--- a/conf.d/health.d/swap.conf
+++ b/conf.d/health.d/swap.conf
@@ -14,7 +14,7 @@
 
    alarm: ram_in_swap
       on: system.swap
-    calc: $used * 100 / ( $system.ram.used + $system.ram.cached + $system.ram.free )
+    calc: $used * 100 / ( $system.ram.active + $system.ram.wired + $system.ram.compressor + $system.ram.purgeable + $system.ram.speculative )
    units: % of RAM
    every: 10s
     warn: $this > (($status >= $WARNING)  ? (15) : (20))
-- 
2.10.1 (Apple Git-78)

```

CC: @vlvkobal

**Comment by simonnagl** [comment]
The other to alarms in `swap.conf` need a fix too.

**Comment by ktsaou** [comment]
This could a choice of the installer or what?

**Comment by simonnagl** [comment]
This should not be a choice of the server.

I can think about these solutions:
1. Let a precompile build the difference. This has the positive aspect we would not have duplicated code. I am not quite sure if this is to much overhead.
2. Maintain one folder for each OS. I think this suits more. First of all I see many differences in alarms. System have other values they collect and may differ even more in the future. Also this makes it easier to maintain changes in one OS. For example if you need to fix an alarm for Linux you do not have to think about if you need precompile tags not to touch in on another system.

What do you think? If you are happy with one solution I can help you out!

**Comment by ktsaou** [comment]
I don't really understand how 1 will work. Can you elaborate a bit?

I guess in 2, netdata will have a common health alarms folder and a system specific alarms folder. So it will load the common one and the system specific one when it starts. How is it going to know which system specific folder to use?

**Comment by simonnagl** [comment]
# How 1 works

1. we rename all files in health.d to conf.c
We change the syntax a bit. Here is an example
```{c}
#define _COMMENT #

   alarm: 30min_ram_swapped_out
      on: system.swapio
  lookup: sum -30m unaligned absolute of out
          _COMMENT we have to convert KB to MB by dividing $this (i.e. the result of the lookup) with 1024
#ifdef __APPLE__
    calc: $used * 100 / ( $system.ram.active + $system.ram.wired + $system.ram.compressor + $system.ram.purgeable + $system.ram.speculative )
#else
    calc: $this / 1024 * 100 / ( $system.ram.used + $system.ram.cached + $system.ram.free )
#endif
   units: % of RAM
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (10) : (20))
    crit: $this > (($status == $CRITICAL) ? (20) : (30))
   delay: up 0 down 15m multiplier 1.5 max 1h
    info: the amount of memory swapped in the last 30 minutes, as a percentage of the system RAM
      to: sysadmin
```
2. We precompile this file `gcc -E file.conf.c > file.conf`
```
# 1 "swap.conf.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 330 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "swap.conf.c" 2


   alarm: 30min_ram_swapped_out
      on: system.swapio
  lookup: sum -30m unaligned absolute of out
          # we have to convert KB to MB by dividing $this (i.e. the result of the lookup) with 1024

    calc: $used * 100 / ( $system.ram.active + $system.ram.wired + $system.ram.compressor + $system.ram.purgeable + $system.ram.speculative )



   units: % of RAM
   every: 1m
    warn: $this > (($status >= $WARNING) ? (10) : (20))
    crit: $this > (($status == $CRITICAL) ? (20) : (30))
   delay: up 0 down 15m multiplier 1.5 max 1h
    info: the amount of memory swapped in the last 30 minutes, as a percentage of the system RAM
      to: sysadmin
```

# Process of 2
1. I guess in 2 the repository will have one common health alarm folder and one for each system.
2. The package maintainer / netdata-installer should copy the required two folders to /etc/netdata/health.d. netdata-installer may check $OSTYPE

Personally I like 2 more because it is easier to have files which are only in one system. 1 will lead to files with just comments in.

**Comment by ktsaou** [comment]
check #1705 for the fix I plan to give.

**Comment by ktsaou** [comment]
This has been fixed.
If something remains, just post.
