### ISSUE TITLE
Update Directly from webpage [Request]

### ISSUE THREAD

**Issue by tx7** [firehol/netdata#1599]
Hello guys,

I like Netdata, and using it daily on my system.
It would be easier if we, admins, can upgrade it directly from the web page instead run the script or schedule a cron job.

Is this possible?

Thanks.

**Comment by ktsaou** [comment]
It could, but we would need to implement authentication first.

In the mean time, you can use the `netdata-updater.sh` script via cron. The installation wiki page has instructions.

**Comment by tx7** [comment]
Ok, I know.
Thanks.

**Comment by simonnagl** [comment]
Seems to be the same as #419

**Comment by ktsaou** [comment]
> Seems to be the same as #419

it is... let's discuss this there...
