### ISSUE TITLE
apache2 virtual host not working 

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#1601]
iam trying to setup an virtual host on my scaleway vps for netdata but when i try to access it at http://server ip/netdata apache2 just gives me an 404. i did follow https://github.com/firehol/netdata/wiki/Running-behind-apache but for some reason its acting up. 

here is my config for netdata.conf 

<VirtualHost *:80>
    RewriteEngine On
    ProxyRequests Off

    # Local netdata server accessed with '/netdata', at 127.0.0.1:19999
    ProxyPass "/netdata" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30
    ProxyPassReverse "/netdata" "http://127.0.0.1:19999/"
    RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]

    ErrorLog ${APACHE_LOG_DIR}/netdata-error.log
    CustomLog ${APACHE_LOG_DIR}/netdata-access.log combined
</VirtualHost>

**Comment by l2isbad** [comment]
@Dedsec1 
You can put Proxy/Rewrite stuff to default conf 
or remove default conf
or create netdata.conf without <VirtualHost *:80>
or create netdata.conf with <VirtualHost **ip.address**:80>

i am not an active apache user but it looks like vhost matching order problem

**Comment by ktsaou** [comment]
@Dedsec1 did you solve it?
I am closing this, but if you need help, please post.

**Comment by Dedsec1** [comment]
yes somewhat but apache is still being an pain in the ass

**Comment by ktsaou** [comment]
That's why most people prefer nginx... Somehow apache has become too complex...

**Comment by Dedsec1** [comment]
agreed, i think iam going to switch over to nginx and hopefully things will work better.
