### ISSUE TITLE
Regular warnings/criticals of disk backlog

### ISSUE THREAD

**Issue by cosmicdan** [firehol/netdata#1602]
I maintain a remote dedicated debian server that hosts a netdata install along with Proxmox VE. Proxmox only has one active LXC.

On the guest LXC, basically anything I do of any significant disk activity/volume (a hundred MB or so), such as copying a directory tree or pulling some file updates through a git repo, will trigger at least a warning of a disk backlog, sometimes critical.

I have tried to research the issue, but I'm not sure if this is expected behavior. I understand I can increase the green/red values in disk.conf, but I'm wondering if I should do that. Is this actually a problem that I need to fix or should I bump those thresholds? I'm not an expert in Linux server administration so would appreciate any advice - I did try and research this but came up with nothing. My initial idea was that it could be a false positive due to write-back caching or something, but surely you would have accommodated for that kind of thing...

Note that the server does run on an SSD - not sure if that's any different.

**Comment by ktsaou** [comment]
hi, you can change the threshold to whatever suits you best.

I have never seen this warning on SSDs. It very hard to have any backlog on them.

This alarm usually means: the disk is expected to do more than it does. If you have something critical on these disks, expect delays...

So, adjust it to whatever you believe is appropriate for you, or even comment it out.

**Comment by ktsaou** [comment]
btw, I try to supply more alarms that is usually needed. It is easier to disable the alarms you don't need than create new alarms for the things you need.

So, I just try to create alarms for everything I believe can be useful. It is up to you to decide what you need on each system.

**Comment by cosmicdan** [comment]
Thanks for the response.

Fair enough - the included alarms serve more as an example or templates than anything, understood. Now I am concerned that the SSD is building a backlog of these sizes, but that's not an issue with netdata.

I'll investigate the cause and increase the thresholds if necessary. Thanks!
