### ISSUE TITLE
Remounting an NFS4 mount point as read-only immediately triggers an alarm (disk_space._n.disk_space_last_collected_secs)

### ISSUE THREAD

**Issue by luisgmuniz** [firehol/netdata#1606]
...and when it is again remounted read-write, the alarm is cleared.

I'm using netdata 1.4.1_master running on top of CentOS 6.8.

I've discovered [issue 1605](https://github.com/firehol/netdata/issues/1605) while investigating this one, so both might, or might not, be related.

JFTR, the mount options are:

     ftpback-rbx-XX.ovh.net:/export/ftpbackup/nsXXXXX.ovh.net on /n type nfs4 (ro,nosuid,nodev,noexec,relatime,vers=4.0,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=XXX.YYY.ZZZ.TTT,local_lock=none,addr=XXX.YYY.ZZZ.TTT)

**Comment by ktsaou** [comment]
hm... this one happens because netdata excludes read-only mount points from data collection (to save memory).

It is a bug... let me find out a way to fix it...

**Comment by ktsaou** [comment]
I believe I have fixed it with #1607 . Testing it. Will be merged in a while.

**Comment by ktsaou** [comment]
merged! thanks for reporting this!
If you still have an issue with it, please post and I'll re-open this.
