### ISSUE TITLE
Average computation

### ISSUE THREAD

**Issue by koraa** [firehol/netdata#1611]
Hi,

so I was looking the network statistics of my server (images attached). There is a relatively regular load every minute, because I am pinging it using a cronjob.

As you can see from the images, the averages for greater time spans are…weird.

If avrages start working well it might also be nice to be able to tell the UI to generate averages over certain time spans. For instance when checking for load on the network in my scenario, I don't care about the spikes, I just want to know how much bandwidth is taken by the regular pings.

I am also wondering about the values themselves, they seem a little high. I could imagine netdata querying the avrage at a peak time and thereby creating values that are too high? (For instance if I had an idling network card, and then a burst at 1Gbit/s, would it report 1Gbit for the entire five second window I am sampling at?)

If that is a problem, it could help to record absolute values (bytes written/sent/…) and leaving average computation to netdata/the frontend. This could also help when computing averages (For instance, taking a 1m avrate at a 1s sample rate would be as simple as computing `(samples[t]-samples[t-60])/60` and then smoothing the curve I imagine).

This could also make it easier to write scripts for data gathering, since it wouldn't have to compute the averages in cases where no differential data is available.

![screenshot1](https://cloud.githubusercontent.com/assets/1451261/22186549/cba89382-e0f7-11e6-8386-6eb0280c83ea.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/1451261/22186545/cba0f5b4-e0f7-11e6-884e-5303580ffe09.jpg)
![screenshot3](https://cloud.githubusercontent.com/assets/1451261/22186548/cba7fb34-e0f7-11e6-87ef-77dd53a4e0b3.jpg)
![screenshot4](https://cloud.githubusercontent.com/assets/1451261/22186546/cba62fe8-e0f7-11e6-9008-34819d16cf82.jpg)
![screenshot5](https://cloud.githubusercontent.com/assets/1451261/22186547/cba7dfe6-e0f7-11e6-9b13-d56d801ac6e6.jpg)
![screenshot6](https://cloud.githubusercontent.com/assets/1451261/22186550/cba9cb6c-e0f7-11e6-9888-446cd5ce8b04.jpg)
![screenshot7](https://cloud.githubusercontent.com/assets/1451261/22186551/cbb6132c-e0f7-11e6-98cf-b581ce48e01b.jpg)

**Comment by ktsaou** [comment]
hm... I didn't really get the problem.

netdata works by reading `/proc/net/dev` every single second. All the numbers in this file are incremental, meaning that every time they are read, their incremental different to the previous reading is calculated. This is the value used.

netdata can calculate averages when you zoom out.

If you want to calculate averages in arbitrary durations, you can use the API to ask netdata give you the values you need.

For example:

```
http://box:19999/api/v1/data?chart=net.eth0&after=-3600&points=1&options=unaligned&format=csv
```

returns 1 point, the average of the last hour.

**Comment by koraa** [comment]
Yup, I red about that when I finally found the api yesterday :)

The problem that's left then is the weird graph renderingt documented in the pictures.
And that it would be nice to be able graph the avrages in the UI. It may even be nice to switch graphs in the GUI between absolute and differential mode, considering that you already have the absolute data.

**Comment by ktsaou** [comment]
> And that it would be nice to be able graph the avrages in the UI. It may even be nice to switch graphs in the GUI between absolute and differential mode, considering that you already have the absolute data.

hm... I still don't get it. Your graphs are weird, but I guess these are the values your kernel exposes. The switch between absolute and differential is confusing for me. netdata collects incremental counters which it interpolates to find the absolute value of each second. So, once we have the absolute value of each second, what would be the differential mode? Could you please explain it a bit?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If we can help somehow, post here.
