### ISSUE TITLE
External intervals for providing samples

### ISSUE THREAD

**Issue by koraa** [firehol/netdata#1612]
Hi,

I tried to write a script for gathering io bandwidth and ops/s for ZFS pools.
ZFS provides a tool called `zpool iostat` which prints exactly that information.

Unfortunately, when I call it, it will usually just give me the current values; this is probably the average over *some* time but I am pretty sure the window is much smaller than 1 second, so I can't use it for netdata.

Luckily, the tool has a mode for regular reports, so I can just tell it to produce the average of the last second every second or so. Then again, getting this integrated with netdata is rather difficult, because nedata wants me to provide a value at a specific point in time. The best thing I could come up with is this: I could fork the `zpool iostat` into a new process and write some awk script to convert the differential values to absolute ones (by simply summing the one second averages) and then writing the result to a temporary file.

In the bash _update function call I could read this absolute value, and generate another average with the value from one second ago.

Just using the values from the iostat command as they are, would not be to nice because due to clock drift there could be race conditions where values are skipped or where we start lagging behind or ahead.

Unfortunately, getting this all right in bash is rather cumbersome. It would be much nicer to just be able to send data to netdata whenever we have some; netdata could do the correction internally in a similar manner as described above (but without temp file) and even better; e.g. it could interpolate two data points that suffer from clock drift to arrive at a more precise value for the sample.

**Comment by ktsaou** [comment]
> Then again, getting this integrated with netdata is rather difficult

Not it is not:

1. Write a shell script called `zfs.plugin`
2. Create the charts in bash (`CHART` and `DIMENSION` lines)
3. Call `zpool` in loop mode to print statistics every second and pipe this to an awk that transforms it to `BEGIN`, `SET`, `END` lines.

The biggest challenge would be to detect in `awk` the iteration. If zpool prints something between the iterations, everything would be super easy...

**Comment by ktsaou** [comment]
have also a loop at [fping.plugin](https://github.com/firehol/netdata/blob/master/plugins.d/fping.plugin). This one required no `awk` because the nice folks at fping [accepted by PR](https://github.com/schweikert/fping/pull/105) so that fping can generate netdata friendly output.

**Comment by ktsaou** [comment]
a "look", not a "loop" - fixed it :)

**Comment by koraa** [comment]
OK, didn't find that API. Thank you!
