### ISSUE TITLE
`cgroup-name.sh` does not respect plugin dir

### ISSUE THREAD

**Issue by kvz** [firehol/netdata#1619]
Hi

I'm getting the error

```bash
  sh: 1: exec: /srv/current/stack/usr/libexec/netdata/plugins.d/cgroup-name.sh: Permission denied
```

And I think it's because the plugin dir is evaluated at compile time here:

```c
static char *cgroups_rename_script = PLUGINS_DIR "/cgroup-name.sh";
```

Instead of being read from the configuration. I'm running into this as I compile ahead of time so I can distribute binaries during deploying, vs slowing down the launch process by adding compiling on the spot. 

I might be wrong with my analysis of the problem though, I know nothing about c 🤔

**Comment by ktsaou** [comment]
You can set:

```
[plugin:cgroups]
	script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh
```

**Comment by kvz** [comment]
That fixed it!

```bash
2017-01-24 07:45:47: cgroup-name.sh: INFO: cgroup 'user' is called 'user'
```

😄 👍 

Thank you so much for assisting!
