### ISSUE TITLE
Dashboard Accessability

### ISSUE THREAD

**Issue by wankbank** [firehol/netdata#162]
I've got `netdata` successfully installed and running, although I'm not really a 'web' guy, or maybe just a slightly clueless — but how to I access the dashboard remotely (eg. https://myhostname:19999)? 

My server is localhost, but that's two continents away... so typing `https://localhost:19999` in my browser here isn't going to make anything on it appear on my screen, unless I'm missing something. 

I've uncommented the hostname in:
```
 /etc/netdata/netdata.conf
```
Restarted, then tried to access the dashboard, but it seems to be unreachable. Thanks!

**Comment by ktsaou** [comment]
Hi, there is no HTTPS interface to netdata. Only HTTP.
Currently, if you need HTTPS you will need to pass netdata through another web server (check the wiki for info).

**Comment by wankbank** [comment]
Thank you for the quick response! If it hasn't already been suggested it would be nice to have HTTPS ability built in hopefully in a future version. In the meantime I'll check the wiki, and once again thank you.
