### ISSUE TITLE
Non-standard Node location

### ISSUE THREAD

**Issue by kvz** [firehol/netdata#1620]
Hi,

My Node.js is in a non-standard location and I depend on `PATH` to find it. Currently when restarting Netdata I'm getting

```bash
/srv/shared/netdata/plugins/node.d.plugin: line 2: exec: ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM: not found
```

How would I be able to pass my PATH to Netdata? It's correctly set in the shell from which I'm restarting Netdata by the way:

```bash
$ command -v node
/srv/current/stack/bin/node
```

**Comment by ktsaou** [comment]
You can pass the `PATH` you need with this:

```
[plugins]
	PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/sbin
```

**Comment by kvz** [comment]
Thanks a lot for the quick response, appreciated!

I now have:

```bash
$ egrep '^\[plugins' etc/netdata.conf -A2
[plugins]
	PATH environment variable = /srv/current/api2/bin:/srv/current/core/bin:/srv/current/stack/lib/ruby/gems/2.1.0/gems/bin:/srv/current/stack/lib/ruby/gems/2.1.0/gems/ruby/2.1.0/bin:/srv/current/stack/bin:/srv/current/stack/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

which contains the important bits: `/srv/current/stack/bin`, which is where my node lives:

```bash
$ which node
/srv/current/stack/bin/node
```

After a restart, it still cannot find it however:

```bash
/srv/shared/netdata/plugins/node.d.plugin: line 2: exec: ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM: not found
```

As a sidenote, `fping`, which lives here:

```bash
$ which fping
/srv/current/stack/sbin/fping
```

Also cannot be found:

```bash
2017-01-24 07:44:01: fping.plugin: FATAL: command '' is not found or is not executable - cannot proceed.
```

**Comment by ktsaou** [comment]
ok.

1. create a new file
2. write in it:

```sh
#!/usr/bin/env bash

# show the current PATH
echo "PATH=${PATH}" >/tmp/netdata.path

# show the current node
echo "$(command -v nodejs || command -v node || command -v js || echo "ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM")" >>/tmp/netdata.path

exit 1
```

3. chmod 755 it
4. move it to the netdata plugins directory (don't create it in there, create it somewhere else and move it there).
5. wait up to 10 seconds (netdata checks for new plugins every 10 seconds)
6. cat /tmp/netdata.path

   What does it say?

7. delete it

**Comment by ktsaou** [comment]
I forgot: The fping binary can be set in /etc/netdata/fping.conf

**Comment by kvz** [comment]
Thanks for the instructions, also about `fping`, I was able to resolve that by what you said! 👍 

Here's my output:

```bash
$ cp ndebug.plugin /srv/shared/netdata/plugins/ && sleep 10 && sudo cat /tmp/netdata.path
PATH=/srv/current/api2/bin:/srv/current/core/bin:/srv/current/stack/lib/ruby/gems/2.1.0/gems/bin:/srv/current/stack/lib/ruby/gems/2.1.0/gems/ruby/2.1.0/bin:/srv/current/stack/bin:/srv/current/stack/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM
vagrant at vbox@local-vagrantisp in /srv/current on api2/vbox#00000
$ which node
/srv/current/stack/bin/node
```

Here's some additional output, proving that command does look at my PATH inside the shell:

```bash
$ command -v nodejs; echo $?
1
$ command -v node; echo $?
/srv/current/stack/bin/node
0
$ command -v js; echo $?
1
```

The subshell also does not cause the trouble:

```bash
$ echo "$(command -v node)"; echo $?
/srv/current/stack/bin/node
0
```

I traced it down further, via your proposed way of debugging, and finally found that it's a permission issue where the `netdata`user does not have access to the `node` bin:

```bash
$ sudo -HEu netdata env PATH=${PATH} 'ls -al /srv/current/stack/bin/node'
env: ls -al /srv/current/stack/bin/node: Permission denied
```

I can take it from here - sorry to have driven this back to an environmental issue on my side, hence wasting your time. I very much appreciate the handholding here, and FWIW, I'll be able to debug plugins myself now in the future 👌
