### ISSUE TITLE
Netdata not finding non-standard Python modules location

### ISSUE THREAD

**Issue by kvz** [firehol/netdata#1621]
Hi,

I'm trying to get MySQL monitoring to work, and I'm currently getting 

```bash
2017-01-23 14:49:08: python.d ERROR: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
```

So I installed the first dependency via `pip install mysqlclient` as instructed, and I verified it was correctly installed:

```bash
$ ls -al /srv/current/stack/lib/python2.7/site-packages/MySQLdb |tail -3
-rw-r--r-- 1 vagrant vagrant   331 Jan 23 14:18 release.pyc
-rw-rw-r-- 1 vagrant vagrant  4017 Jul 26 08:12 times.py
-rw-r--r-- 1 vagrant vagrant  5390 Jan 23 14:18 times.pyc
```

However the message keeps saying it cannot find it. Could this be because my Python modules are in a non-standard location? I'm passing Netdata the correct environment variables that should be able to tell it where my modules live:

```
$ env |grep PYTHON
PYTHON_LIBRARIES=/srv/current/stack/lib/python2.7/site-packages
PYTHONPATH=/srv/current/stack/lib/python2.7/site-packages
PYTHON_INCLUDE_DIRS=/srv/current/stack/include/python2.7
```

**Comment by ktsaou** [comment]
hm... I don't have any idea how to fix that.
@l2isbad can you help?

**Comment by l2isbad** [comment]
Can you check in python interpreter

`import MySQLdb`
or
`import pymysql`

**Comment by kvz** [comment]
Thank you for your quick responses.

> Can you check in python interpreter

When I try that, it works without error:

```bash
$ python
Python 2.7.10 (default, Aug 26 2016, 16:23:09)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>>
```

I suspect that somehow, the python that is run by Netdata, does not look at the environment.

So I added these settings to my config:

```bash
[plugins]
PYTHON_LIBRARIES environment variable = ${PYTHON_LIBRARIES}
PYTHONPATH environment variable = ${PYTHONPATH}
PYTHON_INCLUDE_DIRS environment variable = ${PYTHON_INCLUDE_DIRS}
```

But that did not resolve it unfortunately, it still cannot find the mysql module:

```bash
2017-01-24 07:54:11: python.d INFO: MODULES_DIR='/srv/shared/netdata/python.d/', CONFIG_DIR='/srv/shared/netdata/etc/', UPDATE_EVERY=1, ONLY_MODULES=[]
2017-01-24 07:54:12: python.d ERROR: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-01-24 07:54:12: python.d ERROR: Problem loading mysql
2017-01-24 07:54:12: python.d ERROR: Problem loading postgres No module named psycopg2
```

**Comment by kvz** [comment]
After regenerating the config it also reports that:


```bash
[plugins]
	plugins directory = /srv/shared/netdata/plugins

	# option 'PYTHON_LIBRARIES environment variable' is not used.
	PYTHON_LIBRARIES environment variable = /srv/current/stack/lib/python2.7/site-packages

	# option 'PYTHONPATH environment variable' is not used.
	PYTHONPATH environment variable = /srv/current/stack/lib/python2.7/site-packages

	# option 'PYTHON_INCLUDE_DIRS environment variable' is not used.
	PYTHON_INCLUDE_DIRS environment variable = /srv/current/stack/include/python2.7
```

**Comment by l2isbad** [comment]
You are right @kvz 
python plugin append to sys.path only the netdata's python mudules dir

**Comment by l2isbad** [comment]
Are there any variables we can set in plugin section of conf file to append them to python sys.path later ? @ktsaou

**Comment by l2isbad** [comment]
btw @kvz as a warkaround you can modify sys.path in `/usr/lib/python2.7/site.py
`

sys.path (without PYTHONPATH)
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7', '**/etc/network/**']

**Comment by kvz** [comment]
Great, thanks @l2isbad! I changed this line in `/usr/lib/python2.7/site.py` (original commented out):

```bash
#PREFIXES = [sys.prefix, sys.exec_prefix]
PREFIXES = [sys.prefix, sys.exec_prefix, "/srv/current/stack/lib/python2.7/site-packages"]
```

And now Netdata can find `MySQLdb` 🎉 

```bash
2017-01-25 09:59:53: python.d INFO: using MySQLdb
```

I won't close this issue rightaway as you might want to keep track of this in case you somehow want to add support for respecting the PYTHON env vars that allow to modify this path, but I'll leave that up to you - afaic: feel free to close as I'll be on my way 😄 👍

**Comment by ktsaou** [comment]
@l2isbad your call...

**Comment by l2isbad** [comment]
I think the good idea is to use PYTHONPATH as netdatas user configurable environment variable.

**Comment by ktsaou** [comment]
> I think the good idea is to use PYTHONPATH as netdatas user configurable environment variable.

You mean to add it to `netdata.conf`?

**Comment by l2isbad** [comment]
Yes!

**Comment by ktsaou** [comment]
done

**Comment by ktsaou** [comment]
merged it.

**Comment by kvz** [comment]
Confirmed working ❤️

**Comment by kvz** [comment]
It seems I celebrated too early, old machines still had my hack in place. On newly launched machines, it cannot find `msg` now, which seems to be a lib from netdata

**Comment by l2isbad** [comment]
`msg` in `'/opt/netdata/usr/libexec/netdata/python.d/python_modules'`
python plugin append it at to `sys.path` start
