### ISSUE TITLE
Force recreating the graph

### ISSUE THREAD

**Issue by mrmodolo** [firehol/netdata#1622]
I created a new speedtest based graph to measure the speed of the providers I own. In case, they are two providers and I alternate between them according to speed and stability.

When I switch from one provider to another, I would like to recreate the entire graph since speeds are different between providers.

How can I do to re-create the chart dynamically when I change my network?

![image](https://cloud.githubusercontent.com/assets/1923174/22211438/23c30f12-e174-11e6-875f-0780936f83ed.png)

Thanks,
Marcelo Módolo

**Comment by ktsaou** [comment]
You can't currently. But you could have 2 charts, one for each provider and update only the active one.

I plan to visually differentiate charts that have stopped collecting data.

I also plan to add annotations #312, so that even on the same chart, there could be a flag to document the switch.

**Comment by mrmodolo** [comment]
I'll continue with a chart only. Who knows how to change the title of the chart might be an interesting idea!

Thanks,
Marcelo Módolo

**Comment by ktsaou** [comment]
ok. I am closing this now.
If you need help, just post.
