### ISSUE TITLE
Display node.js chart

### ISSUE THREAD

**Issue by carlystaub** [firehol/netdata#1625]
Registered and enabled my plugin with node.d.conf, wrote the logic to process, configure, and update the data, and executed /usr/libexec/netdata/plugins.d/node.d.plugin debug my_plugin (and it apparently sends the chart without problem), but I cannot get the chart to display on my netdata server. I tried to update netdata.conf with my plugin, but it doesn't seem to be doing anything. What am I missing?

**Comment by ktsaou** [comment]
netdata should be complaining about something in /var/log/netdata/error.log.

Could you please post a whole iteration of your plugin here? I might be able to spot the error.

**Comment by ktsaou** [comment]
btw, there is no need to add your plugin to netdata.conf - it will do by itself.

**Comment by ktsaou** [comment]
@carlystaub did you solve it?
I am closing this now, but if you need more help, just post.
