### ISSUE TITLE
possible to load custom dashboard behind vhost?

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#1626]
HI, 

so i have an virtualhost setup thats running netdata behind apache2 with an custom domain that i own, the issue iam running into is that i have an custom stats page that links to other servers that i run. my current server is setup as this. what i would like to do is have netdata load up the custom stats page from my domain.org/stats instead of http://custom domain.org:19999/stats.html.

http://custom domain.org:19999/stats.html main page with links to other netdata servers.

here is my virtual host config, 

<IfModule mod_ssl.c>
<VirtualHost *:443>
    RewriteEngine On
    ProxyRequests Off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>

    # Local 127.0.0.1:19999/ netdata server accessed with '/netdata'
    ProxyPass "/netdata" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=3                                                                                                                     0
    ProxyPassReverse "/netdata" "http://127.0.0.1:19999/"
    RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]

            ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile /etc/letsencrypt/live/domain/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
ServerName domain
</VirtualHost>
</IfModule>

**Comment by ktsaou** [comment]
What do apache access and error logs say when you access netdata via apache?

**Comment by Dedsec1** [comment]
the apache logs list the following,  but when i try to access https://domain.org/netdata/stats i get File does not exist, or is not accessible: &#x2F;usr&#x2F;share&#x2F;netdata&#x2F;web&#x2F;stats

[Tue Jan 24 06:25:02.535575 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 06:25:02.535616 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:49:32.476498 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:49:32.495414 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:49:32.495436 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:50:41.628411 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:50:41.646751 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:50:41.646774 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:50:53.299455 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:50:53.317733 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:50:53.317756 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:53:33.526869 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:53:33.545254 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:53:33.545275 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:54:21.138426 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:54:21.157107 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:54:21.157130 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:55:20.414990 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00493: SIGUSR1 received.  Doing graceful restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 24 17:55:20.434385 2017] [mpm_event:notice] [pid 28741:tid 139668613764992] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jan 24 17:55:20.434407 2017] [core:notice] [pid 28741:tid 139668613764992] AH00094: Command line: '/usr/sbin/apache2'

**Comment by l2isbad** [comment]
Hello @Dedsec1 
Looks like '[apache virtual host](https://github.com/firehol/netdata/issues/1601)' is working now! Am i right?

To be honest i not fully understand your description..

I use custom dashboard 'behind vhost' (nginx in my case).

- first vhost is custom dashboard (where you have script type="text/javascript" src=... and other links to netdatas servers)

- other files is proxy vhosts for all these netdata servers.

works like a charm

**Comment by Dedsec1** [comment]
yes somewhat, the vhost is working but for some reason, the vhost will only work if i use the main netdata page and apache does not seem to find domain:19999/stats.html. but if i use my server's ip and netdata port then it works just fine.

**Comment by l2isbad** [comment]
Why  `domain:19999/stats.html` ?

Create new domain for custom dashboard. 

```
<VirtualHost *:80>
ServerName  custom.mydomain.lan
ServerAlias www.custom.mydomain.lan
DocumentRoot /var/www/html/CUSTOMDASHBOARDDIR (here your index.html)
</VirtualHost>
```

Other vhost with PROXY/REWRITE etc
```
<VirtualHost *:80>
ServerName  netdata.mydomain.lan
ServerAlias www.netdata.mydomain.lan
RewriteEngine On
ProxyRequests Off
ProxyPass "/netdata" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=3  (or not 127.0.0.1 if you want to proxy to remote machine)                                                                                                                   
ProxyPassReverse "/netdata" "http://127.0.0.1:19999/"
RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]
</VirtualHost>
```

Another N vhosts for others netdata servers

**And...that is all!**
Replace another.netdata.server:19999 in custom dashboard with your ServerName and Port.

```
<div data-netdata="unique.id"
     data-host="http://another.netdata.server:19999/"
     ></div>
```

**Comment by ktsaou** [comment]
@Dedsec1 did you solve it?

I am closing this now, but if you need help, please post and I'll re-open it.
