### ISSUE TITLE
cpufreq doesn't appear in the dashboard 

### ISSUE THREAD

**Issue by abpostelnicu** [firehol/netdata#1629]
Hello,

I have installed on two district machines netdata and on one of them i can't be able to have the graph for cpufreq shown in dashboard.

1. raspberry pi 3 with raspbian 8 - everything works fine and the graph is displayed
2. debian 8 - on HP Microserver Gen8 with an Intel Xeon E3-1240V2 - the graph does now show and looking through the logs it seems that i have the following error:

```
2017-01-24 11:25:14: python.d ERROR: cpufreq couldn't find a method to read cpufreq statistics
2017-01-24 11:25:14: python.d ERROR: cpufreq check() failed - disabling job
```

I use the default config for the cpufreq from /etc/netdata/python.d/cpufreq.conf

**Comment by l2isbad** [comment]
Script looks into
1. /sys/devices/system/cpu/cpu*/cpufreq/stats/time_in_state
2. /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq

If there is nothing there

> 2017-01-24 11:25:14: python.d ERROR: cpufreq couldn't find a method to read cpufreq statistics

**Comment by ktsaou** [comment]
@abpostelnicu your kernel should be exposing this information for netdata to use. If there is no such information exposed, we cannot do much to collect it.

I am closing this now. If you believe your system exposes this information but netdata does not use it, please post here the information you have, so that we can fix it.

**Comment by skibbipl** [comment]
Hello,
Again I'm hijacking another thread. On my debian servers I don't see cpufreq charts. Kernel is configured to expose this data:
```
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq
1603048
1599770

uname -a
Linux server01 4.13.0-1-amd64 #1 SMP Debian 4.13.4-1 (2017-10-01) x86_64 GNU/Linux
```
Netdata error log contains only errors regarding the old cpufreq module:
```
2017-10-20 15:14:59: charts.d: INFO: cpufreq: is disabled. Add a line with cpufreq=force in /opt/netdata/etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2017-10-20 15:15:02: python.d INFO: CHECKED OK: cpufreq
```

**Comment by l2isbad** [comment]
Are you sure?
It's under `CPUs` 
![screenshot_20171020_230501](https://user-images.githubusercontent.com/22274335/31824940-8f72dc8c-b5eb-11e7-84f1-fde9cf8174f0.png)

**Comment by skibbipl** [comment]
Damn, it seems that debian packaged netdata is totally broken. I've reinstalled netdata from binary package and cpufreq is displayed correctly.

**Comment by ktsaou** [comment]
> it seems that debian packaged netdata is totally broken. I've reinstalled netdata from binary package and cpufreq is displayed correctly.

@lhw @FedericoCeratto please check this.
