### ISSUE TITLE
Overlapping Digits

### ISSUE THREAD

**Issue by drgnomage** [firehol/netdata#1631]
I am receiving an issue with the Arch Linux community edition of netdata (netdata 1.4.0). The percentages etc are overlapping/retaining old values. Please see image below:
![2017-01-24-132938_3200x900_scrot](https://cloud.githubusercontent.com/assets/6968974/22249577/7c16aeb8-e23b-11e6-9234-c4dcfc292a0d.png)

If I adjust the zoom level of the page, the error is temporarily cleared.

Please let me know if I need to provide any more information.

**Comment by l2isbad** [comment]
> netdata 1.4.0
Flagged out-of-date on 2017-01-23

**Comment by drgnomage** [comment]
I'm not experiencing the same issue from the AUR (netdata 1.5.1_master)

I will close the case.

**Comment by ktsaou** [comment]
In most of these cases (overlapping digits on the dashboard) restarting the web browser helps. It seems to be an issue of the browsers. I can't really make anything to fix it.

**Comment by drgnomage** [comment]
@ktsaou It does but it soon comes back, this morning was particularly bad.

![2017-01-27-083644_3200x900_scrot](https://cloud.githubusercontent.com/assets/6968974/22364824/f60dbfe0-e46b-11e6-895d-77e6d0b07411.png)

I'm fairly certain it is just retaining old values and putting new ones on top, I'm guessing that would be a cache on the local machine?

**Comment by ktsaou** [comment]
ok. When this happens, could you please check if there are multiple DOM elements with multiple values? You can do this by pressing the right menu button and selecting `Inspect`, like this:

![image](https://cloud.githubusercontent.com/assets/2662304/22380951/2d5c78a4-e4c8-11e6-92ed-3187070faa15.png)

Then you should get something like this:

![image](https://cloud.githubusercontent.com/assets/2662304/22380969/40ffe1ca-e4c8-11e6-85f1-353ff36572f5.png)

The highlighted line will flash as values are updated.

I am sure there will be just one DOM element with the latest value. If this is the case, I cannot do much. It is your browser / graphics card that does this.

If there are multiple DOM elements, one for each value shown, then I should fix it. It should not happen.

**Comment by drgnomage** [comment]
When I used the inspect element function, the old values went away. 

I will leave the page open with the inspect element panel open and let you know if more DOM elements pop up by tomorrow.

**Comment by drgnomage** [comment]
It generates an entire new canvas by the look of it.

![2017-01-30-151934_3200x900_scrot](https://cloud.githubusercontent.com/assets/6968974/22428623/b317bcfe-e6ff-11e6-827e-e3b0de86a88a.png)

**Comment by ktsaou** [comment]
I think I forgot this.
So, it is a bug. Let me find out what is happening....

**Comment by ktsaou** [comment]
Well, I am trying to figure out how this is possible, but I can't find a way to reproduce it.
Can you give me a few directions?

1. which browser?
2. when does this happen?

**Comment by drgnomage** [comment]
Sure.

1. Firefox 50.

2. The error usually occurs after a large period of time has elapsed. At least 2 hours in my observations. I don't know if there are any interactive causes as it usually appears when I haven't checked the page for a while.

**Comment by ktsaou** [comment]
found it.

I had some logic to re-create all charts after 5000 refreshes (just in case a chart library uses more and more memory as time passes), but I didn't initialize everything properly, so for gauge charts this leaded to duplicate charts creation (i.e. exactly the opposite of what my intention was).

I fixed it.
