### ISSUE TITLE
FreeBSD - incorrect /proc

### ISSUE THREAD

**Issue by DubhAd** [firehol/netdata#1632]
It looks like netdata is expecting the linprocfs version of procfs on /proc, however the linprocfs version is more correctly mounted at /compat/linux/proc.

**Comment by ktsaou** [comment]
I don't see it used in freebsd code: https://github.com/firehol/netdata/blob/master/src/freebsd_sysctl.c

Where did you find it?

**Comment by RobBelics** [comment]
I don't know if this answers the question but FreeBSD doesn't use /proc for itself. Linux programs running under compatibility mode are normally placed in /compat/linux/proc and that's where such programs look for these things since, as I said, FreeBSD, as the OS, has no use for /proc.

**Comment by ktsaou** [comment]
ah ok!

I think @vlvkobal does not use `/proc` anywhere on freebsd and macos.

Let's give him some time to respond.

**Comment by vlvkobal** [comment]
`procfs` is used neither in FreeBSD nor in macOS plugins. It can be used in other parts of `netdata` (for example, in apps.plugin). But these parts are automatically disabled at `netdata` start. Nevertheless I haven't verified yet if `netdata` demands `procfs` for running. In the future all `procfs` dependencies should be excluded for FreeBSD and macOS.

**Comment by RobBelics** [comment]
But on reddit, one user shows it fails on his machine trying to access(?) /proc.

**Comment by vlvkobal** [comment]
If there are any issues with `procfs` on FreeBSD you can add this to `/etc/fstab`:
`proc /proc procfs rw 0 0`
and reboot your machine.
Alternatively you can invoke the `mount -t procfs proc /proc` command.

**Comment by ktsaou** [comment]
@vlvkobal it is probably a leftover...  let me check...

1. I see cgroups is enabled in freebsd/macos - I am moving it to linux only - making a PR now.

2. apps.plugin is already disabled, but it attempts to access files in /proc - it fails to read them and exits.

3. I see in `common.c` in `get_system_cpus()` there is an override for MacOS, but not for FreeBSD. Is this intentional?

4. I see the following settings which are probably leftovers. The current configuration uses `SIMPLE_PATTERN` to enable/disable network interfaces.

```
plugin_freebsd.c:    config_get_boolean("plugin:proc:/proc/net/dev:lo", "enabled", 0);
plugin_freebsd.c:    config_get_boolean("plugin:proc:/proc/net/dev:fireqos_monitor", "enabled", 0);
plugin_macos.c:    config_get_boolean("plugin:proc:/proc/net/dev:lo", "enabled", 0);
plugin_macos.c:    config_get_boolean("plugin:proc:/proc/net/dev:fireqos_monitor", "enabled", 0);
```

So, 3 and 4 are yours to decide how you want to handle them on FreeBSD and MacOS.

**Comment by ktsaou** [comment]
Merged the fix for 1.

**Comment by simonnagl** [comment]
@3. This may not be intentional. Since I have no access to FreeBSD this may be true.

**Comment by ktsaou** [comment]
ok. I am marking this as bug and I assign it to @vlvkobal to find a work around.
@vlvkobal if you want it the way it is, just comment.

**Comment by vlvkobal** [comment]
3 and 4 were fixed with #1691.

**Comment by ktsaou** [comment]
So, this is done. No more `/proc` in FreeBSD!
apps.plugin is not ported yet (which will attempt to access `/proc`, fail and exit).

**Comment by ktsaou** [comment]
I am closing this now.
Thank you all!
