### ISSUE TITLE
Being able to set divisor and precision from dashboard.js

### ISSUE THREAD

**Issue by kvz** [firehol/netdata#1634]
Hi!

My Netdata integration is coming along nicely! 

<img width="218" alt="screenshot 2017-01-24 23 19 20" src="https://cloud.githubusercontent.com/assets/26752/22269463/beab0f26-e28b-11e6-8724-daf1b945e84e.png">

I would now like to set all these graphs to display Mbit/s with a range of [0, 500] and a precision of 2. I believe this will make it easier to spot in this view when machines are starting to go overboard.

I noticed this is possible via the API, but I wonder how I would type this in HTML? I tried via `data-divisor`, `data-division` and a number of other variants. I also tried to run it through the `append-options` attribute somewhat desperately :) But to no avail.

I also checked https://github.com/firehol/netdata/wiki/Custom-Dashboards but it didn't say.

Any chance I can configure this without changing the server config? I'd love to have settings in other places.

**Comment by ktsaou** [comment]
nice!

Unfortunately, I haven't supported changing the divisors on the dashboard. This would require from the javascript code to go through all points and divide them.

There is support for changing them at `netdata.conf`.

You can though set precision and you can also ask all these charts to have the same y-range. Check `/demosites.html` - it does both of them.

**Comment by kvz** [comment]
Understood! Thanks!
