### ISSUE TITLE
Netdata on PFsense

### ISSUE THREAD

**Issue by karsyboy** [firehol/netdata#1640]
I know that netdata states nowhere that its supported for pfsense so this may be the wrong area to post this as this is only kind of an issue, but since there is now FreeBSD support for netdata would this be possible. I have spent the night tinkering to get netdata working on PFsense (for the reason that I could see this being a popular tool to have) but keep getting stuck at the C compiler when trying to compile and install netdata. If someone with more knowledge could help me build a PFsense package or get it working that would be amazing (I would also love you forever).

**Comment by ktsaou** [comment]
hi.

@vlvkobal please check this one too. Supporting `pfSense` would be nice.

**Comment by vlvkobal** [comment]
Umm... Is it possible to get access to installed `pfSence`? If it is, I'd better verify `netdata` installation remotely instead of installing a new virtual machine.

**Comment by karsyboy** [comment]
I was not able to actually get netdata running it would fail at the C compiler I dont have a lot of programming skill so I was not sure what it would take to get netdata running on pfsense.

**Comment by vlvkobal** [comment]
If you can give me access (login and password) to your machine it would be much easier for me to resolve issues with compiling `netdata`.

**Comment by l2isbad** [comment]
@karsyboy If you are not comfortable withlogin/pass request from a random internet guy (sounds scary to me) you can set up new pfsense vm and provide access to it for @vlvkobal 
Not for your existing pfsense instance.

**Comment by ktsaou** [comment]
I tried to create a pfsense vm on azure, but it fails.

@vlvkobal one way could be to setup pfsense with virtualbox on your development machine. I could do this and give you access, but my upstream speed is very bad and it will not be very helpful for you.

**Comment by l2isbad** [comment]
I think a good idea is to setup [OPNsense](https://opnsense.org) (which is more "open" then pfsenes) vm too

**Comment by vlvkobal** [comment]
I'll try to install it on my machine next week.

**Comment by vlvkobal** [comment]
I've installed pfSense virtual machine and I've successfully run `netdata` on it.

@karsyboy you can install `netdata` with
`pkg add http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/netdata-1.5.0.txz` or
`pkg add http://pkg.freebsd.org/FreeBSD:10:i386/latest/All/netdata-1.5.0.txz` (choose appropriate one for your platform). You can find more information in https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages and https://doc.pfsense.org/index.php/Versions_of_pfSense_and_FreeBSD

You can't compile `netdata` on pfSense. Take a look at https://doc.pfsense.org/index.php/Can_I_compile_software_on_pfSense

**Comment by ktsaou** [comment]
nice!

**Comment by brando56894** [comment]
This doesn't work on pfSense 2.3 since it doesn't use the FreeBSD package repository anymore, it fails at e2fsprogs-libuuid.

**Comment by ktsaou** [comment]
So, there is no libuuid on pfSense 2.3 or is it named otherwise?

**Comment by vlvkobal** [comment]
I forgot to verify package dependencies. As long as psSense does not have `e2fsprogs-libuuid` included in the native packages collection, I think you should install it manually with `pkg add http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/e2fsprogs-libuuid-1.43.4.txz` before installing netdata. @brando56894 could you check this.

**Comment by ktsaou** [comment]
@karsyboy did you tried it? Can we close this issue?

**Comment by karsyboy** [comment]
I have been out of town for the past couple of week so i just finally got around to doing this it did install. When i try to start it i cant bind it to any IP's
[
![capture](https://cloud.githubusercontent.com/assets/25337712/23245003/43563c0a-f957-11e6-9708-daf12168e058.PNG)
](url)

**Comment by vlvkobal** [comment]
@karsyboy try to bind netdata to specific address using option `bind to =` in `netdata.conf`
Check your firewall rules for 192.168.11.131 if you need netdata to be binded to this address exactly.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.

**Comment by bitratio** [comment]
It seems there is no installation available for 2.3.3?

**Comment by bitratio** [comment]
[2.3.3-RELEASE][root@pf]/root: pkg add http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/netdata-1.5.0.txz
pkg: http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/netdata-1.5.0.txz: Not Found

**Comment by pando85** [comment]
I installed it successfully; try this http://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/netdata-1.6.0.txz
You will need some dependencies too.

**Comment by bitratio** [comment]
Thanks Pando, works!

**Comment by brando56894** [comment]
Any chance this will be supported on the official Netgate hardware, such as the SG-1000? I only see ARM v6 packages.

CPU: ARM Cortex-A8 r3p2 (ECO: 0x00000000)	
Thumb2, Security, VMSAv7	
Texas Instruments AM335x Processor, Revision ES1.2
am335x built-in CPU Crypto (inactive)

http://www.ti.com/lsds/ti/processors/sitara/arm_cortex-a8/am335x/overview.page
tps://www.netgate.com//products/sg-1000.html
