### ISSUE TITLE
Monitor external hosts?

### ISSUE THREAD

**Issue by lukasp2** [firehol/netdata#1643]
Hi,

I want to run netdata on my RPi 2 and monitor my Ubuntu VM and my QNAP. IS that possible?

Br,
Lukas

**Comment by rickatnight11** [comment]
`netdata` is intended to be a local live metric analysis tool.  The intended use-case is to be an alternative to traditional CLI tools, like top/atop/htop.  All of its plugins source data from local sources that in general aren't remotely accessible.

It's intended for you to install on each of your "monitored" machines, and if you want to do historical or cross-machine analysis, you can forward the metrics to central service like OpenTSDB or Graphite.

**Comment by ktsaou** [comment]
@rickatnight11 thanks!

The only change I would make is that netdata python and node plugins are usually capable of collecting metrics remotely. System metrics though can only be collected from the localhost.

So, @lukasp2 you will have to install netdata on all your devices.
