### ISSUE TITLE
Alarms for fping

### ISSUE THREAD

**Issue by tuwxyz** [firehol/netdata#1645]
Hi

How to write an alarm for fping module?

**Comment by simonnagl** [comment]
Just referring to the wiki: https://github.com/firehol/netdata/wiki/health-monitoring#examples

If you need more information just ask

**Comment by ktsaou** [comment]
The idea is that fping:

1. reports NaN (null) values if the connection is lost
2. reports high average latency
3. reports packet loss

So, we could have alarms checking all these conditions.

You can give it a try.
I will be able to help later today.

**Comment by tuwxyz** [comment]
I will give it a try this weekend (I hope). Thanks.

**Comment by ktsaou** [comment]
I added 2 of the 3 checks in PR #1652

**Comment by ktsaou** [comment]
added them all. merged it too.
