### ISSUE TITLE
FTP upload to server crashes

### ISSUE THREAD

**Issue by mario-coin** [firehol/netdata#1647]
I have this server Netdata is monitoring, and it is also used with Filezilla for specific large FTP traffic sometimes.
After trying to upload some package of files, all applications lose connection to web server and mysql, which seems to sleep for a brief time before returning to normal. **Uploading works if Netdata process is down**.

So, is it a important topic to talk a workaround, or should I not have Netdata installed, on this case?
If it's important, is there a config I should look or try? It seems all services are shut down because server reaches the limit in some criterias.

Suggestion: would be valid cron to low the update frequency on Netdata, so that crash does not occur again?

**Comment by l2isbad** [comment]
Well. i am just messing around but I think it would be great if you give more information!
Was it once or repeats in the same circumstances ("large FTP")?
Can you ssh to server and do a troubleshoot when "all applications lose connection to web server and mysql"? (run top, check services etc)

Also pls look into
https://github.com/firehol/netdata/issues/1630

> Keep in mind though that netdata is running with the IDLE process scheduling priority (lower than nice 19) and adjusts its OOM score to 1000 (so that it will be the first process to be killed if the server runs out of memory). So, it is pretty safe to run...

If netdata is running you can post some charts - at least 'Applications' (while problem exist).

**Comment by ktsaou** [comment]
@mario-coin your conclusion is probably wrong. The presence of netdata cannot trigger this. As @l2isbad suggested, you can use netdata itself to examine what is happening on your system while this happens.

**Comment by mario-coin** [comment]
Sorry for the delayed reply.

I could repeat the issue, with Netdata down this time. As it is not related to the tool, there's no point to continue this trace.

Thanks anyway for the fast reply :-)
