### ISSUE TITLE
No strings to translate on Crowdin

### ISSUE THREAD

**Issue by Atalanttore** [firehol/netdata#1649]
Hi,

there are no strings to translate for NetData on Crowdin.

See: https://crowdin.com/project/netdata

Regards,
Ettore

**Comment by ktsaou** [comment]
There aren't much to translate yet. Only the strings between the charts... which are not that many.

**Comment by ktsaou** [comment]
There are a few issues asking for help in enriching this information, like #279

**Comment by ktsaou** [comment]
And I think this is duplicate of #219

**Comment by ktsaou** [comment]
I am closing this in favour of #219.
Let's discuss everything about translations there.
