### ISSUE TITLE
please update documentation to include python-requests for elasticsearch plugin

### ISSUE THREAD

**Issue by haghabozorgi** [firehol/netdata#1650]
elasticsearch plugin requires the requests python module.
Test on minimal install of centos 6 and 7, installation of python-requests rpm is needed, otherwise you will see in error.log:
`python.d ERROR: Problem loading elasticsearch No module named requests`

**Comment by ktsaou** [comment]
thanks for reporting this.
@l2isbad please check this.

**Comment by l2isbad** [comment]
Yeah, i forgot  sorry

**Comment by ktsaou** [comment]
@l2isbad we might also have to adapt the kickstart.sh script to install the package on various distros.
It will need some work though to find the exact package name everywhere...

**Comment by l2isbad** [comment]
To be honest i am not a big fan of 'lets install all automatically, lets listen on all interfaces etc'. I am prefer documentation/error log approach.
If it is not core functionality (like ES) then only we need is to provide good documentations how to setup plugin (install additional modules/packages) properly.

**Comment by haghabozorgi** [comment]
Agreed. I think a simple update to wiki installation section should
suffice. Perhaps update the apt,dnf, and yum lines and add a new entry into
table mentioning python-requests package is needed for elasticsearch, and
call it a day.

**Comment by ktsaou** [comment]
@l2isbad the [kickstart script](https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh) has the option `netdata-all` which should install all packages required for all plugins of netdata. Several people use it to identify quickly which packages they should install.

I added this to it.
I am going to add it to the wiki page now.

@haghabozorgi thanks for reporting it.
