### ISSUE TITLE
Node.JS SNMP Module - Returned OID value offsets

### ISSUE THREAD

**Issue by nzurku** [firehol/netdata#1654]
This isn't so much an issue but rather a clarification of how the module works. The SNMP values have a multiplier and divisor, but is there any supported way to do an offset (add/subtract)?

We're trying to monitor two giant CAT generators for our datacenter, and we'd like to read the generated kW that is reported over Modbus. Our Modbus->SNMP converter works great, but CAT's generators monitor the power starting at -2000000000 watts, which then you do the math with the current value to see how many watts you're producing. I don't know the reason for starting with this negative number, but I believe Modbus counters will wrap pretty quickly with how many watts these things could produce. This can be fixed within the GUI of our modbus converter, but it doesn't send these "fixed" and offset values over to SNMP... Oh well.

We were able to easily fix with with Nagios because the generator scripts are just easy to code in the -2000000000 offset.

If there any solution for doing this within netdata? I would assume in most cases the offset needs to be done before any multiplier or divisor is applied.

I'm sure running a datacenter NOC with netdata wasn't the original intent, but so far using netdata has turned out AWESOME.

Thanks!

**Comment by ktsaou** [comment]
ok, nice. I could add this. Let me check...

**Comment by ktsaou** [comment]
ok added it and tested. It works.

Just add another member, below the `multiplier` and the `divisor`, named `offset` with the positive or negative value you need.

It is in PR #1652

**Comment by nzurku** [comment]
Wow, thanks for the quick addition.

That works for our use case - the offset is modifying the SNMP value properly. Our generator is now properly reading 0KW when not powering the load.

Thanks again!

**Comment by ktsaou** [comment]
merged it.
