### ISSUE TITLE
netdata on suse 10

### ISSUE THREAD

**Issue by kgorgolewski** [firehol/netdata#1656]
hi,
i got netdata compiled on one of our old suse 10 sp2 servers, after updating some necessary libraries. but after accessing the UI i can see only a short "system overview" and some "netdata monitoring" infos. i also checked the error.log file and have seen that cpu, block io, devices, etc are tried to accessed from /sys/fs/cgroup/..., like:
**2017-01-26 14:36:58: netdata: ERROR: Cannot find cgroup cpuacct mountinfo. Assuming default: /sys/fs/cgroup/cpuacct
2017-01-26 14:36:58: netdata: ERROR: Cannot find cgroup blkio mountinfo. Assuming default: /sys/fs/cgroup/blkio
2017-01-26 14:36:58: netdata: ERROR: Cannot find cgroup memory mountinfo. Assuming default: /sys/fs/cgroup/memory
2017-01-26 14:36:58: netdata: ERROR: Cannot find cgroup devices mountinfo. Assuming default: /sys/fs/cgroup/devices**
but under /sys/fs everything is empty. i tried to search for this topic, but could find any results for suse 11 and newer.
so do i understand it correctly that these data, which would be mount under /sys/fs is kernel version specific? it looks our used kernel is very old (2.6.16.60) and therefore no data is available? or do i miss something?
regards

**Comment by ktsaou** [comment]
Yes, cgroups is containers. netdata reads `/proc/self/mountinfo` to find the exact mount points. But your system seems not to have them (too old kernel).

**Comment by kgorgolewski** [comment]
thanks ktsaou. let me see if i can find a newer kernel for our system ;)

**Comment by ktsaou** [comment]
if you don't use systemd or containers, it will not be any useful...

**Comment by kgorgolewski** [comment]
but as far as i could see is /proc/self/mountinfo introduced with kernel 2.6.26... and we are currently far away from this version. i will try it at least :)

**Comment by kgorgolewski** [comment]
i think we should close this question... i will come back in case i got further questions :)

**Comment by dthielking** [comment]
I get the same error:

**ERROR: Cannot find cgroup memory mountinfo. Assuming default: /sys/fs/cgroup/memory**
But there is no memory directory.

I am using Debian 8 Stable

**Comment by ktsaou** [comment]
> I am using Debian 8 Stable

You need to pass `cgroup_enable=memory swapaccount=1` to the kernel command line. It is by default disabled in debian.

**Comment by ktsaou** [comment]
> to the kernel command line

at grub, of course...

**Comment by dthielking** [comment]
Perfect! Thank you for your advise.
