### ISSUE TITLE
update netdata

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#1668]
Hi,

When I update netdata, it shows 8/10 that there is again new updates available

thanks

**Comment by ktsaou** [comment]
This is good. It means we work on it, adding features and making it better.

A lot of people add `netdata-updater.sh` to a daily cron job. This has been designed not to print anything if the update is successful. So you will receive an email from cron only when the update fails.

**Comment by yoorshop** [comment]
I'm using cron

**Comment by ktsaou** [comment]
Everything is good then...

**Comment by ktsaou** [comment]
I am closing this. If you need help or you have a suggestion to make, please post.
