### ISSUE TITLE
multiple charts.d instances - mysql_cmds issue running mysql via lxc-attach

### ISSUE THREAD

**Issue by ticklemynausea** [firehol/netdata#167]
Hi. This issue has nothing to do with lxc, only with the way mysql.chart.sh invokes mysql. I could not think of a better title for this issue, sorry.

It  is possible to run a command inside a linux container like the following:

`
lxc-attach -n mycontainer -- mysql
`

I have tried to take advantage of this to monitor mysql servers running inside LXC with the following configuration in `mysql.conf`:

```
mysql_cmds[myhost]="mysql"
mysql_cmds[mycontainer ]="lxc-attach -n mycontainer -- mysql"

mysql_opts[myhost]="-hlocalhost -uroot -pmypassword"
mysql_opts[mycontainer ]="-hlocalhost -uroot -pmypassword"
```

This will not work for reasons I could not yet determine (I'm looking inside `mysql.chart.sh`). Reading the docs one could expect this to work:

> keep in mind that local user netdata should be able to access your mysql to execute this:
> `$mysql $OPTIONS -s -e "show global status;"`

Running the command:

`lxc-attach -n mycontainer -- mysql -hlocalhost -uroot -pmypassword -s -e "show global status;" `

is valid and works exactly as expected.

I'm thinking there's maybe an issue with spaces in the commands in `$mysql_cmds`? I'm trying to see if I can fix this myself, but any help would be greatly appreciated.

**Comment by ticklemynausea** [comment]
I realized there may be other impediments, such as the user netdata runs under not being able to use lxc-attach.

**Comment by ticklemynausea** [comment]
Yay! I was able to get this working!

My issue above caused this to show up in the error log:

`/usr/libexec/netdata/plugins.d/../charts.d/mysql.chart.sh: line 18: lxc-attach -n mycontainer -- mysql: command not found`

So I did the following change to `mysql.chart.sh` (just removed a pair of double quotes):

```
index 2839052..7a31db2
--- a/mysql.chart.sh
+++ b/mysql.chart.sh
@@ -14,8 +14,8 @@ declare -A mysql_cmds=() mysql_opts=() mysql_ids=()

 mysql_exec() {
        local ret
-
-       "${@}" -s -e "show global status;"
+
+       ${@} -s -e "show global status;"
        ret=$?

        [ $ret -ne 0 ] && echo "plugin_command_failure $ret"

```

This fixed the `command not found` error, but now there was a complaint from lxc-attach in the error log that happened because the netdata user can't attach that container (root is needed). I needed to allow the `netdata` user to use lxc-attach, so I gave the user permission to sudo and run only that specific command. In `/etc/sudoers`:

`netdata ALL=(ALL:ALL) NOPASSWD: /usr/bin/lxc-attach -n mycontainer -- mysql *`

And finally in `/etc/netdata/mysql.conf`:
mysql_cmds[mycontainer]="sudo lxc-attach -n mycontainer -- mysql"
``

This seems to be working great, as now I can monitor several mysql instances on my server (we depend a lot on lxc) from a single netdata installation.

**Comment by ktsaou** [comment]
I think you could also run, on host:

```
mysql -h lxc-container1-ip ...
```

So, you could just configure the host mysql to connect to the mysql running in the container, as if it was on a separate machine.

Using the above, you could configure `/etc/netdata/mysql.conf`, like this:

```sh
mysql_opts[server1]="-h server1"
mysql_opts[server2]="-h server2"
```

where `server1` and `server2` are the IPs of the containers.

**Comment by ticklemynausea** [comment]
That was always a possibility, but I prefered to keep the mysql instances listening only on localhost.

**Comment by ktsaou** [comment]
ok nice.
The `lxc-attach` that runs so frequently, isn't a problem? How frequent do you collect data?

**Comment by ktsaou** [comment]
You know there is another, probably more efficient way:

You go to `/usr/libexec/netdata/plugins` and you create a file per container, named `container1.plugin`, like this:

```sh
#!/bin/bash

export NETDATA_CONFIG_DIR="/path/to/configs/for/this/container"
exec lxc-attach /usr/libexec/netdata/plugins/charts.d.plugin ${@}
```

This is a plugin. It runs the `charts.d.plugin` inside the container, using its own configuration directory.
This way, lxc-attach is run just once and more than one plugins could be run inside each container.

Of course, the container needs access to `/usr/libexec/netdata/`.

**Comment by ticklemynausea** [comment]
> The lxc-attach that runs so frequently, isn't a problem? How frequent do you collect data?

lxc-attach by itself is not a problem at all. It runs very fast. But right now I'm annoyed with the amount of logging that PAM does to auth.log because of my sudo. Since this collection is performed very frequently my auth.log is getting filled up with sudo success and session close messages.

I'll make use of your suggestion so I don't have to use a modified version of mysql.chart.sh.

**Comment by ktsaou** [comment]
For each container, install only the charts.d plugins you need, or duplicate data collection might happen for other plugins (there are also a few performance charts for charts.d itself that might be affected). Try it. If you find a problem post here and I'll see what I can do.

**Comment by ticklemynausea** [comment]
I was able to get this working properly with your pointers! So excited!

Here's what I did:

Firstly, I needed to copy some parts of netdata into the containers. Just the bare minimum needed for this to work. So in `container_1` and `container_2` I copied parts of netdata so that I have the following executable scripts under their root filesystem:

```
/usr/libexec/netdata/
├── charts.d
│   └── mysql.chart.sh
└── plugin.d
    └── charts.d.plugin
```

Both `container_1` and `container_2` need to have the following config files under their root filesystem:
```
/etc/netdata
├── charts.d.conf
└── mysql.conf
```
I specified a normal connection to a mysql instance in `mysql.conf`. This is from an inside the container point of view. Like this:

```
mysql_cmds[container_1]="mysql"
mysql_opts[container_1]="-hlocalhost -uroot -ptherootpassword"
```

As for `charts.d.conf`, I disabled every chart except mysql. Like this:
```
enable_all_charts="no"
mysql="yes"
```

Now, as @ktsaou suggested, I created two new plugins in the host system, called `charts-container_1.plugin` and `charts-container_2.plugin`. They are pretty much like one another:

```
#!/bin/bash                                                                                 
# NETDATA_CONFIG_DIR is from an inside-the-container point of view                                                                                   
export NETDATA_CONFIG_DIR="/etc/netdata"                                                    
exec sudo lxc-attach -n container_1-- /usr/libexec/netdata/plugin.d/charts.d.plugin ${@}
```

Then, just allow the netdata user to run this particular command as root in `/etc/sudoers`:

```
Cmnd_Alias LXC_ATTACH_NETDATA_CHARTS_PLUGIN = /usr/bin/lxc-attach -n container_1 -- /usr/libexec/netdata/plugin.d/charts.d.plugin *, /usr/bin/lxc-attach -n container_2 -- /usr/libexec/netdata/plugin.d/charts.d.plugin *

netdata ALL=(ALL:ALL) NOPASSWD: LXC_ATTACH_NETDATA_CHARTS_PLUGIN
```

And this is it! I'm really happy with this solution because this will easily allow getting more charts from services running inside the containers like apache2! Thanks a lot @ktsaou!

**Comment by ktsaou** [comment]
ok nice!

The apache plugin does not support multiple servers so the charts will overlap. You will probably have to edit each apache.chart.sh and find the CHART and BEGIN to change their names.

Also, there may be an issue with the charts in "Netdata Monitoring / charts.d" section with the execution times of charts.d plugins. Most probably netdata receives multiple values for the same charts (mysql in your case). If this is the case, the charts.d chart for mysql in the "Netdata Monitoring" section will be going "fast" (time will progress in these charts faster). To fix this, the proper way is to search/replace in the scripts the names of the functions and global variables, so that instead of `mysql_` your will have `mysql_contrainer1_`, etc. The filenames will have to be named like this too.

**Comment by ticklemynausea** [comment]
@ktsaou Yes, I can confirm that this is happening.

I'll go ahead and try to fix it with your suggestion.

**Comment by ticklemynausea** [comment]
I did it as you recommended, doing a `s/mysql_/mysql_container_X_/g` inside each `mysql.chart.sh`. I also renamed `mysql.chart.sh` to `mysql_container_1.chart.sh`

Then following the errors I found in the logs, I:
- changed the `mysql="yes"` setting in `charts.d.conf` to read `mysql_container_X="yes"`.
- renamed `mysql.conf` to `mysql_container_X.conf` and then inside this file renamed `mysql_cmds` and `mysql_opts` to `mysql_container_X_cmds` and `mysql_container_X_opts`

These steps make perfect sense if one thinks we just created a new plugin called `mysql_container_X` which needs its own settings.

**Comment by ktsaou** [comment]
nicely done.
I will have a look to find a easier way of doing it.

**Comment by ticklemynausea** [comment]
Thanks for looking into easier ways of doing this! This method is not a bad way to extend netdata though, and in the meantime I've use it to successfully monitor mysql and apache, even creating my own charts.d plugin for monitoring the player count on a game server that runs on a container! But there's a weird issue I found with this method of doing things. So, to recap:

I have a netdata plugin running on the host called `charts-minecraft.plugin`:
```
#!/bin/bash

export NETDATA_CONFIG_DIR="/etc/netdata"
exec sudo lxc-attach -n minecraft -- /usr/libexec/netdata/plugins.d/charts.d.plugin ${@}
```

And then inside the container I have a modified version of `apache.chart.sh`. I only modified the CHART and BEGIN commands, doing both `s/BEGIN apache/BEGIN apache_minecraft/g` and `s/CHART apache/CHART apache_minecraft/g`. (https://gist.github.com/ticklemynausea/094b94ccbb986e2589180c80e0756bce).

Further, I have the apache probing interval set in `/etc/netdata/apache.conf` with `apache_update_every=5`
Netdata seems to run perfectly fine! But looking into my webserver logs I can see that the probing is being done twice per probing interval:

```
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:00 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:01 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:05 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:06 +0100] "GET /server-status?auto HTTP/1.1" 200 510 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:10 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:11 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:15 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:16 +0100] "GET /server-status?auto HTTP/1.1" 200 512 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:20 +0100] "GET /server-status?auto HTTP/1.1" 200 509 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:21 +0100] "GET /server-status?auto HTTP/1.1" 200 511 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:25 +0100] "GET /server-status?auto HTTP/1.1" 200 510 "-" "curl/7.35.0"
localhost:80 127.0.0.1 - - [04/Apr/2016:22:14:26 +0100] "GET /server-status?auto HTTP/1.1" 200 511 "-" "curl/7.35.0"
```

I think it's important to add that when `apache_update_every` is set to `1` this issue does not happen.

First I tought that this would be an issue with this hackish apache chart.d plugin, but then I made another chart.d plugin to monitor a game server and I can see from the game console that the same issue is happening. This time the probing interval is set inside the script itself:

(https://gist.github.com/ticklemynausea/8af7e052b2eba1273b830aca7139e273)

```
[22:35:00] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:35:01] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:35:30] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:35:31] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:36:00] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:36:01] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:36:30] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:36:31] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:37:01] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:37:30] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[22:37:31] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
```

Looking close at the timestamps you can see that it does not always happen, which makes this issue even weirder. As always, I would appreciate any help that's possible.

**Comment by ktsaou** [comment]
I think that the environment variables (NETDATA_CONFIG_DIR and the others set by netdata, namely NETDATA_PLUGINS_DIR, etc - check **[External Plugins](https://github.com/firehol/netdata/wiki/External-Plugins#environment-variables)** for a list) may not pass to charts.d.plugin inside the container.

This may not affect the timings, but please make a check.

Then, to figure out what is happening, I suggest to run the commands by hand.
Run this:

```sh
export NETDATA_CONFIG_DIR="/etc/netdata"
lxc-attach -n minecraft -- /usr/libexec/netdata/plugins.d/charts.d.plugin 1
```

This would collect values once per second. You can also run it with parameters `debug 1` to also show what it is doing.

I understand this is weird, so probably something else is happening...

**Comment by ticklemynausea** [comment]
For now I can for now confirm that environment variables are passed into the container. At least this test seems valid to me:

```
# TESTING=testing_env_vars lxc-attach -n minecraft -- env
TESTING=testing_env_vars
SHELL=/bin/bash
(...)
```

**Comment by ticklemynausea** [comment]
Yay I got it! I should've looked harder in the logs before I posted.

Running the commands by hand I could see this error:

```
/usr/libexec/netdata/plugins.d/charts.d.plugin: line 225: /usr/libexec/netdata/plugins.d/loopsleepms.sh.inc: No such file or directory
```

Copying `/usr/libexec/netdata/plugins.d/loopsleepms.sh.inc` inside the container solved the issue. Success!

**Comment by paulfantom** [comment]
Closing since I believe it is resolved and also outdated.
