### ISSUE TITLE
Unnecessary error-level log messages

### ISSUE THREAD

**Issue by FedericoCeratto** [firehol/netdata#1670]
Netdata is generating log messages with ERROR level at start time that should probably use INFO instead:

ERROR: Cannot read ECC memory errors directory '/sys/devices/system/edac/mc' (errno 2, No such file or directory)
ERROR: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
ERROR: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfsd' (errno 2, No such file or directory)
ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfs' (errno 2, No such file or directory)

Many similar messages are generated by the Python plugins when trying to detect various daemons that are not installed.

This makes troubleshooting more difficult. May I suggest using ERROR only for events that are "breaking" netdata? Thank you.

**Comment by ktsaou** [comment]
Currently, these are used in netdata error.log, for all netdata programs (including plugins in all languages):

1. `INFO` = something you should know
2. `ERROR` = something that might disable a section of netdata - the log line includes errno
3. `FATAL` = something that prevents netdata from running - the log line includes errno and netdata exits

So, when netdata autodetection of something fails, we log `ERROR`, the relevant module is disabled but the program continues to run. When the program cannot run at all, we log `FATAL`.

**Comment by ktsaou** [comment]
updated the wiki to reflect the above: https://github.com/firehol/netdata/wiki/Log-Files

I am closing this. If you have a suggestion, let's discuss it.
