### ISSUE TITLE
NetData doesnt work on some places

### ISSUE THREAD

**Issue by andre-paulo98** [firehol/netdata#1681]
Installed netdata yesterday. Worked fine at my house.
Then today when i went back to school it didn't worked there getting the error 405: Cannot download charts index from server http://server:19999/api/v1/charts
Tested on my phone with mobile data and it worked just fine.

**Comment by l2isbad** [comment]
Hi @andre-paulo98 
> doesnt work on some places

What places do you mean? Your school?

**Comment by andre-paulo98** [comment]
That was the only place i found for now.

**Comment by simonnagl** [comment]
Maybe your school blocks inconvenient ports like 19999.

If you need access to it you can use `default port = 80`. This might work.
Anyways if you do not want anybody to see the page (what I think because you did not post the real URL) You should put your page behind a web server and use authentication. For more information check the wiki.

If you know all these things please do not blame me and ignore this.

**Comment by ktsaou** [comment]
Error 405 on the dashboard means that some API call failed to reach netdata.
You can check the console of your web browser (press F12, switch to the network tab and refresh the page).

There can be a few reasons for this:

1. Your place is using proxy that does not allow ports other than 80 or 443.
2. Your place have a transparent proxy for ports 80 and 443, so 19999 does not go through it (if you configure the proxy by hand it might work).
3. You have a content filtering plugin on the browser.

In most of the cases, checking the web browser console helps determine the problem.

**Comment by andre-paulo98** [comment]
> Maybe your school blocks inconvenient ports like 19999.
I'm gonna check if thats the case in couple days, will let you know if it worked.

I have other question about the web server, let me know if i should create a new issue.
On the wiki (running apache) how can i access netdata on a subdomain: netdata.mydomain.com
Tried the basic pointing the domain with virtual hosts to /netdata/web and didn't worked
should i use that method and instead of `ProxyPass "/netdata"` use `ProxyPass "/"` ?

**Comment by l2isbad** [comment]
@andre-paulo98 
https://github.com/firehol/netdata/issues/1601
https://github.com/firehol/netdata/issues/1626

A lot of apache/nginx issues (just look)!

> Edit: And then how can i disable the myserver.com:19999 access?

 
[/opt/netdata/etc/netdata]sudo grep bind netdata.conf
        # bind to = *
        bind to = 127.0.0.1

**Comment by andre-paulo98** [comment]
> @andre-paulo98
#1601
#1626

But that is all for mywebsite.com/netdata.
I wanted something like netdata.mywebsite.com
Just like http://toronto.my-netdata.io/

**Comment by l2isbad** [comment]
@andre-paulo98 

Here you go

```
<VirtualHost *:80>
ServerName  netdata.mywebsite.com
ServerAlias netdata.mywebsite.com
RewriteEngine On
ProxyRequests Off
ProxyPass "/" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=3                                        
ProxyPassReverse "/" "http://127.0.0.1:19999/"
</VirtualHost>
```

**Comment by andre-paulo98** [comment]
Thank you very much
