### ISSUE TITLE
Empty Config

### ISSUE THREAD

**Issue by DildoShwagginz** [firehol/netdata#1683]
Is there a way to create netdata page without any charts?
If I go through the netdata.config and disable all charts, I end up with still having a chart about Ipv4 ICMPmsg. Im not sure if this is the right way to disable the charts.
My plan is to implement my own chart via python.d.plugin but the config is so confusing and long to me

**Comment by ktsaou** [comment]
The `[plugins]` section has everything:

```
[plugins]
	# tc = yes
	# idlejitter = yes
	# proc = yes
	# diskspace = yes
	# cgroups = yes
	# checks = no
	# plugins directory = /usr/libexec/netdata/plugins.d
	# enable running new plugins = yes
	# check for new plugins every = 60
	# httpd-mod-cache-log = yes
	# fping2 = yes
	# charts.d = yes
	# fping = yes
	# node.d = yes
	# python.d = yes
	# apps = yes
```

If you need an external plugin enabled, but you need to enable/disable individual modules of it, there should be a `.conf` file in `/etc/netdata`. So for `python.d.plugin` you should edit [`/etc/netdata/python.d.conf`](https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf).

**Comment by DildoShwagginz** [comment]
Thank you very much, this worked out for me!

But now Im facing another problem, I took the example.chart.py (which I can enable and the Graph shows up) as a template and made this:
`class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        super(self.__class__,self).__init__(configuration=configuration, name=name)
        self.ser = serial.Serial(
            port='/dev/ttyUSB0',
            baudrate=9600,
            parity=serial.PARITY_NONE,
            stopbits=serial.STOPBITS_ONE,
            bytesize=serial.EIGHTBITS,
            timeout = 3
        )
    def getstatus(self):
        self.ser.write('ka 04 ff\r')
        response = self.ser.read(100)
        if response = 'a 00 OK01x':
            return 1
        else:
            return 0
    def check(self):
        return True
    
    def create(self):
        self.chart("Display.python_random", '', 'Display Status', 'Status On/Off',
                   'status', 'status', 'line', self.priority, self.update_every)
        self.dimension('status1')
        self.commit()
        return True
    
    def update(self, interval):
        self.begin("Display.python_random", interval)
        self.set("status1", getstatus(self))
        self.end()
        self.commit()
        return True` 

I try to do simple serial communication with a device, but it seems like if I initialize the "self.ser=" the graph wont show up anymore, even if i dont call the getstatus() function at all.

**Comment by ktsaou** [comment]
@l2isbad could you please help?

**Comment by l2isbad** [comment]
def getstatus(self):
        self.ser.write('ka 04 ff\r')
        response = self.ser.read(100)
        **if response = 'a 00 OK01x':**
            return 1
        else:
            return 0
    def check(self):
        return True


>>> if 1 = 2: print(3)
  File "<stdin>", line 1
    if 1 = 2: print(3)
         ^
SyntaxError: invalid syntax

**Comment by l2isbad** [comment]
And @DildoShwagginz 
Don't stick to example.chart.py!

There is more then 30 different python plugins. Read them to understand how it works.

**Comment by l2isbad** [comment]
```python
class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        super(self.__class__,self).__init__(configuration=configuration, name=name)

    def check(self):
        return True
    
    def get_status(self):
        return 33
    
    def create(self):
        self.chart("example.python_random", '', 'A random number', 'random number',
                   'random', 'random', 'line', self.priority, self.update_every)
        self.dimension('random1')
        self.commit()
        return True
    
    def update(self, interval):
        self.begin("example.python_random", interval)
        self.set("random1", self.get_status())
        self.end()
        self.commit()
        return True
```

**Comment by ktsaou** [comment]
Is this done? Shall we close it?

**Comment by DildoShwagginz** [comment]
Yes it is, please close it.
Thank you very much, I appreciate that. :+1:
