### ISSUE TITLE
Is it possible to compile/install netdata on RHEL/Centos 5?

### ISSUE THREAD

**Issue by orgito** [firehol/netdata#1685]
Is it possible to compile/install netdata on RHEL/Centos 5?

**Comment by ktsaou** [comment]
If it has autotools 2.6 I think you should be able to do it.
Have you tried it?

**Comment by orgito** [comment]
RHEL5 has autools 2.58. I'm trying using the released source, which should not need autotools.

**Comment by ktsaou** [comment]
well... the whole problem is to get autoconf detect the build settings for your system. This process creates `config.h` in the root directory of the source tree, which is used by the netdata source files to understand how they should be compiled.

So, if you manage to run autoconf, everything should be very easy.

**Comment by ktsaou** [comment]
I mean if you run `./configure` and it works, it will be compiled.

**Comment by orgito** [comment]
Thanks, I'll try that.

**Comment by ktsaou** [comment]
ok, I did something unorthodox.

This file is a statically linked netdata against `musl-libc`. It is static (meaning it does not read any libraries from the system it runs). It should run on any 64bit Intel/AMD processor, with any Linux kernel. I am not sure though. This is the first time I do this. On all systems I tried it, it works though.

So, if you are adventurous enough, give it a try.

[netdata-1.5.1_master.tar.gz](https://github.com/firehol/netdata/files/740544/netdata-1.5.1_master.tar.gz)

It installs to `/opt/netdata`.

To install it, do this:

```sh
# do everything in /opt
cd /opt

# download it
wget "https://github.com/firehol/netdata/files/740544/netdata-1.5.1_master.tar.gz"

# untar it (in /opt) - directory netdata will be created
tar -zxvpf netdata-1.5.1_master.tar.gz

# add user and group netdata to system and fix permissions
bash /opt/netdata/post-install.sh

# start netdata
/opt/netdata/usr/sbin/netdata
```

Please report if it works or not.

**Comment by orgito** [comment]
I was using uuid-devel to meet netdata dependency of libuuid-devel. The installar did not work with it. 

So I installed libuuid from source for my RHEL5 servers configuring it with:
`./configure --prefix=/usr --libdir=/usr/lib64`

That made netdata-installer.sh happy and it worked.

**Comment by ktsaou** [comment]
ok. nice!

**Comment by ktsaou** [comment]
@roschacker where did you find this netdata package?
Check the installation page. You can install it from source. It is pretty simple.

**Comment by roschacker** [comment]
> where did you find this netdata package?
i googled it

> Check the installation page. You can install it from source. It is pretty simple.
script written for  specific version of bash:

`[root@system ~]# curl -Ss 'https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
Sorry! This script needs BASH version 4+, but you have BASH version 3.2.25(1)-release`

**Comment by ktsaou** [comment]
Have you tried to do it by hand?

https://github.com/netdata/netdata/wiki/Installation#1-prepare-your-system

**Comment by roschacker** [comment]
> 
> 
> Have you tried to do it by hand?
> 
> https://github.com/netdata/netdata/wiki/Installation#linux-by-hand

my openssl version is incompatible (0.9X instead of 1.X)
i do not know the short way to update it without breaking a lot of other staff

**Comment by ktsaou** [comment]
netdata does not need openssl.
Give it a try. You only need libuuid and zlib.

**Comment by roschacker** [comment]
> 
> 
> netdata does not need openssl.
> Give it a try. You only need libuuid and zlib.

yes, but look at your shell script - 
it uses `curl` at least
curl  does NOT work even with github
because support of TLS versions (not sure exactly)
that used by openssl 0.9.8.X
for connections was switched off
https://githubengineering.com/crypto-removal-notice/

**Comment by ktsaou** [comment]
You have a few options:

1. Use git with `ssh` to clone the repo using `ssh` as transport. Then run the installer. This needs some configuration on your side.

2. Download a zip file from github, copy it to your server, unzip it to `/usr/src/netdata.git` and run the installer.

3. If your servers are 64bit, you can download the static 64 bit version of netdata. These also include a statically build `curl` compiled with the right openssl version. If you have a broken package management that does not have the required packages for compilation, this is the way to go.
