### ISSUE TITLE
INNODB files

### ISSUE THREAD

**Issue by MarkPartlett** [firehol/netdata#1688]
Is there any way to find the DiskIO per single file for InnoDB files, so you can work out what is the busiest file/table.

**Comment by ktsaou** [comment]
I don't know. Is such a metric exposed by mysql?

**Comment by MarkPartlett** [comment]
I don’t believe so… how about at the OS level?

**Comment by MarkPartlett** [comment]
https://github.com/draios/sysdig does it via a sysdig -c topfiles_bytes command

**Comment by MarkPartlett** [comment]
you can close this. thanks!

 I love the graphs, I would like to make a JDBC based website tool similar to netdata!
