### ISSUE TITLE
Fail to build on RHEL 6

### ISSUE THREAD

**Issue by ilanbe** [firehol/netdata#1689]
Installation and build are failing due to : 
........
apps_plugin.o: In function `main':
apps_plugin.c:(.text+0x7b44): undefined reference to `CAP_IS_SUPPORTED'
apps_plugin.c:(.text+0x7b68): undefined reference to `CAP_IS_SUPPORTED'
collect2: ld returned 1 exit status
make[2]: *** [apps.plugin] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/sys_kernel_mm_ksm.Tpo .deps/sys_kernel_mm_ksm.Po
make[2]: Leaving directory `/home/user/netdata/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/netdata'
make: *** [all] Error 2

**Comment by ktsaou** [comment]
fixed it. Could you please update and retry?

**Comment by ilanbe** [comment]
updated. fix confirmed.

Thanks
