### ISSUE TITLE
virtio statistics: monitoring plan9 FS bandwidth.

### ISSUE THREAD

**Issue by brando56894** [firehol/netdata#1692]
I finally convinced the guys over at FreeNAS to integrate NetData into the OS, but one thing I had noticed in both FreeBSD and Linux is that when I was transferring files over 9P NetData showed very little activity (in the range of  few hundred KB a sec when I was moving a few GB file). I asked Jordan (their CTO) why this was and he said "That's probably because neither one [iotop and NetData] is plumbed into VIRTIO-VSOCK traffic.  Both of those tools would have to adapt to that, as well as probably adding a telemetry point to the virtio code itself."

Plan 9 is the main protocol we use for internal storage between the host and VMs/Docker Containers.

Would it be possible to make this happen some how?

**Comment by ktsaou** [comment]
@vlvkobal could you please check this?

**Comment by vlvkobal** [comment]
@brando56894 what charts were you inspecting when you was tranferring files?

**Comment by brando56894** [comment]
System Overview is what I usually look at, specifically for this Disk Read and Disk Write.

**Comment by brando56894** [comment]
Just to make sure that I'm not crazy I DD'd a file in a VM to a dataset that is connected via 9P and the terminal shows 76 MB/sec, while NetData shows 57 KB.

![capture](https://cloud.githubusercontent.com/assets/572116/22532925/bb01c85a-e8b8-11e6-9906-2f9013b062ef.PNG)

**Comment by brando56894** [comment]
According to one of FreeNAS' devs 9P uses virtualized PCI devices to communicate between the Host and the VM. IDK if that info helps at all, I know next to nothing regarding it.

**Comment by vlvkobal** [comment]
Could you provide `iostat -dx 1` output during the transfer?

**Comment by brando56894** [comment]
```
 [root@pirate ~]# iostat -dx 1
Linux 4.9.6-1-ARCH (pirate.brandongolway.us)    02/03/17        _x86_64_        (2 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.04     1.79    0.38    1.24     6.82    15.44    27.57     0.00    2.72    2.29    2.85   1.75   0.28

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   121.00    0.00  122.00     0.00  1976.00    32.39     0.60    4.73    0.00    4.73   1.39  17.00
```

**Comment by ktsaou** [comment]
@vlvkobal is this a bug or an enhancement?

**Comment by vlvkobal** [comment]
It looks like a `virtio` driver bug. As I can see, both Linux and FreeBSD system utilities can't display virtio traffic stats correctly. Thus, from `netdata`'s point of view if we could find where to get `virtio` statistics from and integrate it into `netdata`, it would be an enhancement.

**Comment by brando56894** [comment]
I'm gonna close this considering Jordan Hubbard quit iX Systems on 4/7/2017, and shortly after the FreeNAS Corral team was disbanded. Once that happened the original team sh*t canned FreeNAS Corral, and they will be basing the newest version off of FreeNAS 9.10, which will be using NFS instead of 9PFS.
