### ISSUE TITLE
insserv warning script 'netdata' missing lsb tags and overrides debian

### ISSUE THREAD

**Issue by dirzhov** [firehol/netdata#1696]
I got the next error when call dpkg-reconfigure in Ubuntu:
`insserv warning script 'netdata' missing lsb tags and overrides debian`

File /etc/ini.d/netdata does not include info in the begginig of the file like this:
```
### BEGIN INIT INFO
# Provides:          netdata
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      1 0 6
# Short-Description: simple description.
### END INIT INFO
```

Maybe make sense to inlude such lines?

OS: Ubuntu 16.01
Netdata version: 1.5.0

**Comment by ktsaou** [comment]
I see this information in the file: https://github.com/firehol/netdata/blob/master/system/netdata-lsb.in
Can you help me figure out what is wrong?

**Comment by dirzhov** [comment]
I'm so sorry.. It was my fault. I build from sources and copied wrong file
- name: Move the systemd file in place
      copy:
        remote_src: true
        src: /tmp/netdata-1.5.0/system/netdata-init-d
        dest: /etc/init.d/netdata 
        mode: 0770
I found in sources lsb version. Thank you!

**Comment by ktsaou** [comment]
ok. nice.
