### ISSUE TITLE
Option to only watch process for cpu usage (and not its tree)

### ISSUE THREAD

**Issue by kvz** [firehol/netdata#1698]
Hi 😊 

Reading [this](https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf), it says:

> For each process given, its whole process tree will be grouped, not just  the process matched. The plugin will include both parents and childs.

It would help us a lot of we could have an option to just monitor the process itself. Our usecase is we have a `node` process that spawns maybe 20 `ffmpeg` processes, and in the cpu graphs we'd like to be able to see `node` consumption without the `ffmpeg` processes being factored into that.

I was thinking the config could look like this:

```yaml
encoding: ffmpeg* convert identify mogrify
transfer: curl aws s3cmd
brain: node coffee
```

But my current ffmpeg is that `brain` would always be saturated as `encoding` and `transfer` processes belong to the `node` process tree as they're spawned by it.

Is there any workaround so that we can make this happen already perhaps?

Thanks in advance for your advice, loving netdata so far.

**Comment by ktsaou** [comment]
So, you are saying that with the config you have, `ffmpeg` gets accumulated into `brain`?

hm... I think this is a bug. Let me check...

ok, I think I found it. When `node` executes `ffmpeg` it:

1. forks itself (a new PID is created, as `node`)
2. calls a version of `exec()` to execute `ffmpeg`. This does not change the PID of the process.

`apps.plugin` has a caching mechanism, to allow it work faster. It does not compare the name of the process against the the configuration file on every iteration. It does it once, and then caches it forever.

It seems that `node` is somewhat slow to call `ffmpeg` after it calls `fork()`. This makes `apps.plugin` think that the process executing is still `node`.

hm... looking for solution...

**Comment by ktsaou** [comment]
I think I fixed it.
Now, when the processes change, apps.plugin is able to detect it.
Could you please check it?

**Comment by kvz** [comment]
Hey, I think you fixed it too! 😄 👍 

<img width="1021" alt="screen shot 2017-02-02 at 10 00 53" src="https://cloud.githubusercontent.com/assets/26752/22542940/8d23f3ba-e92e-11e6-810d-468cd996b68d.png">

💯 

It seems to be picking mostly red & green in the default interface. I'll fix it in my own dashboard, but is there a reason for this, or just by change (indexes of the different groups?) or did I misconfigure my apps?

**Comment by ktsaou** [comment]
> It seems to be picking mostly red & green

hm... can you enable all dimensions from the dashboard settings?
It is either a bug or it just rotated the whole color palette and picked the same colors again.

**Comment by kvz** [comment]
I had made no changes to the dashboard settings. I had not included the original netdata config, and was only using my own apps. After appending all the original groups to `apps_groups.conf` also, I saw more diverse colors.

**Comment by ktsaou** [comment]
I meant this one:

![image](https://cloud.githubusercontent.com/assets/2662304/22570552/8aea7b02-e9a4-11e6-8d0d-f2bcfc91916e.png)

If you set it to `All`, then even the dimensions that are just zero will be shown (i.e. all of them), which could help us identify if there are more than 20 of them. If more than 20 are present, the colors are reused.
