### ISSUE TITLE
Fail to connect to postgresql via socket

### ISSUE THREAD

**Issue by Yamakaky** [firehol/netdata#1701]
```
socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'
```
```
2017-02-01 16:54:12: python.d ERROR: postgres_socket fe_sendauth: no password supplied
2017-02-01 16:54:12: python.d ERROR: postgres_socket check() failed - disabling job
```
I don't have a password on the local postgres user and `pg_hba.conf` is set to trust.

**Comment by ktsaou** [comment]
@l2isbad check this one too...

(We probably need a guide on how to setup postgres - many users are facing issues with it)

**Comment by l2isbad** [comment]
@Yamakaky @harpo
It works for me w/o
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L206

![screenshot_20170202_072519](https://cloud.githubusercontent.com/assets/22274335/22528955/c9d75a4c-e918-11e6-846f-42f2f9b3b2d1.png)

**postgres.conf**
```yaml
socket:
    name     : 'socket'
    user     : 'postgres'
    database : 'postgres'

tcp:
    name     : 'tcp'
    database : 'postgres'
    user     : 'postgres'
    password : '321'
    host     : 'localhost'
    port     : 5432
```

```
# Database administrative login by Unix domain socket
#local   all             postgres                                peer

# Database administrative login by Unix domain socket
#local   all             postgres                                trust

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             postgres                                trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5

```

` grep postgres error.log `
2017-02-02 07:33:25: python.d INFO: **CHECKED OK: postgres_socket**
2017-02-02 07:33:25: python.d INFO: RENAMED: postgres_socket , from postgres_socket
2017-02-02 07:33:25: python.d INFO: **CHECKED OK: postgres_tcp**
2017-02-02 07:33:25: python.d INFO: RENAMED: postgres_tcp , from postgres_tcp

**Comment by l2isbad** [comment]
The porblem is 

**>>> help(psycopg2.connect)**

The basic connection parameters are:
    
    - *dbname*: the database name (only in dsn string)
    - *database*: the database name (only as keyword argument)
    - *user*: user name used to authenticate
    - *password*: password used to authenticate
    **- *host*: database host address (defaults to UNIX socket if not provided)**

We need to remove [**host**](https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L206) to connect to socket.

**Comment by l2isbad** [comment]
Also plugin doesn't reconnect to socket after postgres restart.
I fix it later

**Comment by ktsaou** [comment]
can we close this? It is fixed, yes?

**Comment by Yamakaky** [comment]
Yes!
