### ISSUE TITLE
Add loging to systemd-journald for all the netdata logs

### ISSUE THREAD

**Issue by Yamakaky** [firehol/netdata#1702]
I prefer it to text files.

**Comment by ktsaou** [comment]
So, you want netdata to log to its stderr?

You can set this in `netdata.conf`:

```
[global]
	error log = stderr
```

I see in the code you can use `system`, `stdout`, `stderr`, `/dev/null` (to disable it), `none` (to disable it) and `syslog` (to send error.log to syslog).

I think either `system`, `stdout` or `stderr` will send the error.log of netdata to the systemd journal. Can you test it?

**Comment by l2isbad** [comment]
I can test it @ktsaou 
`error log = stderr`

works

**Comment by ktsaou** [comment]
nice!

**Comment by Yamakaky** [comment]
Oh, didn't see `stderr` in the doc.

**Comment by Yamakaky** [comment]
In fact it's not really solved, since it would mean duplication of the timestamp, and it would not have features like filter by severity.

**Comment by l2isbad** [comment]
```bash
journalctl -u netdata.service -p err
-- Logs begin at Sun 2017-01-01 13:21:09 +09, end at Thu 2017-02-02 10:28:35 +09. --
Feb 02 10:28:25 ttk-work netdata[5376]: INTERNAL ERROR: indexing of config 'netdata server resources' in section 'plugin:proc': already exists.
Feb 02 10:28:25 ttk-work netdata[5376]: child pid 5389 exited with code 127.
Feb 02 10:28:25 ttk-work netdata[5376]: PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' exited with error code 127. Disabling it.
Feb 02 10:28:25 ttk-work netdata[5376]: child pid 5400 exited with code 1.
Feb 02 10:28:25 ttk-work netdata[5376]: PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' exited with error code 1. Disabling it.
Feb 02 10:28:25 ttk-work netdata[5376]: child pid 5396 killed by signal 15.
Feb 02 10:28:25 ttk-work netdata[5376]: PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' exited with error code -1. Disabling it.
Feb 02 10:28:26 ttk-work netdata[5376]: Cannot read ECC memory errors directory '/sys/devi
```

**Comment by Yamakaky** [comment]
hum, cool, I'll try!

**Comment by l2isbad** [comment]
no logs from python in case of error log = syslog

**Comment by Yamakaky** [comment]
Do you plan to fix it?

**Comment by ktsaou** [comment]
> no logs from python plugin in case of error log = syslog
> Do you plan to fix it?

Yes, #805

**Comment by ktsaou** [comment]
I am closing this in favour of #805 
If you need help, just post.
