### ISSUE TITLE
API

### ISSUE THREAD

**Issue by anasri** [firehol/netdata#171]
Does this script have API ? 
I'm interested to use it in WHMCS  for each customer virtual/dedicated server

**Comment by ktsaou** [comment]
https://github.com/firehol/netdata/wiki/REST-API-v1

It very simple though, it serves the dashboards. No user authentication / authorization or limit on the charts users may have access to.

**Comment by ktsaou** [comment]
Did it worked for you?

**Comment by ktsaou** [comment]
There was a typo in the API documentation and the swagger editor was not showing it. It is fixed.

**Comment by ktsaou** [comment]
ok, I close this.
If you need something more, open it again.
