### ISSUE TITLE
Feature Request: Elasticsearch/Logstash Backend

### ISSUE THREAD

**Issue by orgito** [firehol/netdata#1710]
Are there plans for Elasticsearch or Logstash backends?

**Comment by ktsaou** [comment]
Well, any PRs are welcome. It should be relatively easy to do it.

**Comment by orgito** [comment]
I'll simply use the graphite logstash codec for now. I'll see if I can submit a PR for elasticsearch.

**Comment by simonnagl** [comment]
Please leave this open until this is implemented.

**Comment by orgito** [comment]
All right. But it should be noted that it is currently possible to send data to Elasticsearch using logstash tcp input with the graphite codec.

**Comment by ktsaou** [comment]
ok, updated the wiki.

There is a request to support more backends via their native API #1642 
I am closing this in favour of #1642
