### ISSUE TITLE
Random Data gaps!

### ISSUE THREAD

**Issue by ogulcanozugenc** [firehol/netdata#1712]
Hello all. I have random data gaps of 1-2 seconds mostly. Can you help me with this? Thanks.
![ekran alintisi](https://cloud.githubusercontent.com/assets/22659319/22606655/479f3b58-ea5d-11e6-8b04-4ac0b3019ccb.PNG)

**Comment by ktsaou** [comment]
netdata runs with the IDLE process scheduling priority.

Abstract from `man sched`:

```
   SCHED_IDLE: Scheduling very low priority jobs

       This policy is intended for running jobs at extremely low priority
       (lower even than a +19 nice value with the SCHED_OTHER or SCHED_BATCH policies).
```

So, when your system is under extreme CPU pressure, netdata is runs in "slow motion", to allow your applications run faster. This shows gaps on the charts.

**Comment by ogulcanozugenc** [comment]
Oh, I got it. Can we turn this off? I want to see the data without having these gaps. Thanks for the fast response.

**Comment by ktsaou** [comment]
hm... I see in the code it is hardcoded.
I'll add a `netdata.conf` option to let you pick the scheduling priority you like.
Will do this, within this weekend.

**Comment by ogulcanozugenc** [comment]
Wow. I will wait for your response. Thanks.

**Comment by ktsaou** [comment]
added it.
check PR #1713 for documentation.

Will be merged in a while...

**Comment by ogulcanozugenc** [comment]
I will try in two minutes. Thanks for your help.
