### ISSUE TITLE
mongo with netdata

### ISSUE THREAD

**Issue by harshaldavda** [firehol/netdata#1717]
Hii,
I am using mongodb and recently installed netdata. netdata is working fine with apache mysql nginx. but I want graphs of mongo too..

**/etc/netdata/conf.d/apps_groups.conf** contains
--------------------------------------------------------------------
sql: mysqld* mariad* postgres* oracle_* ora_*
nosql: mongod redis* memcached
--------------------------------------------------------------------

mongodb service isalso running but I am not able to see in charts in netdata dashboard.

So, how do I add graphs for it.

Thank you.

**Comment by l2isbad** [comment]
Netdata has no plugin for a `mongodb` yet.
I google a bit and it looks simple - you can get all status from url (/_status) in json format.

https://docs.mongodb.com/manual/reference/command/serverStatus/#output

**Comment by harshaldavda** [comment]
Okay Thank you

**Comment by l2isbad** [comment]
@harshaldavda 
Keep the issue open pls.

**Comment by bonesoul** [comment]
should we expect a plugin any soon?

**Comment by l2isbad** [comment]
Yes. My plan is to collect all [important](https://www.datadoghq.com/blog/monitoring-mongodb-performance-metrics-wiredtiger/) metrics i can get with the 'http://x.x.x.x:y/_status'. (ServerStatus).
Another way is to use `'pymongo'` (ServerStatus, dbstats, ...) - more metrics but you need to install additional software..
Any suggestion?
Is it enough to use 'ServerStatus' data or not?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1822

**Comment by jappre** [comment]
looking forward!

**Comment by l2isbad** [comment]
@jappre i am not a mongodb user. And mongodb has 9k metrics...
Which ones are important? The result in [PR](https://github.com/firehol/netdata/pull/1822)
Any help from a mongodb user will be appreciated.
You can use script from my PR and suggest what i need remove/add/change/etc

**Comment by todojs** [comment]
The more important metrics are in MongoStat native tool

https://docs.mongodb.com/manual/reference/program/mongostat/

**Comment by l2isbad** [comment]
@harshaldavda 
@bonesoul 
@jappre 
@todojs 
Initial version merged

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you something is missing, let us know.
