### ISSUE TITLE
How to graph Proliant ipmitool values with Netdata

### ISSUE THREAD

**Issue by thomasfrivold** [firehol/netdata#1729]
Hi

I have a few HP Proliant servers, and by using impitool, I can see the fanspeed, power usage in watts and temperatures from sensors inside the machine.

Here is the output from ipmitool:
root@moneymaker:~# ipmitool sdr
UID Light        | 0x00              | ok
Int. Health LED  | 0x00              | ok
Ext. Health LED  | 0x00              | ok
Power Supply 1   | 125 Watts         | ok
Power Supply 2   | disabled          | ns
Power Supplies   | 0x00              | ok
Fan 1            | 25.48 percent     | ok
Fan 2            | 25.48 percent     | ok
Fan 3            | 25.87 percent     | ok
Fan 4            | disabled          | ns
Fans             | 0 percent         | ok
Temp 1           | 24 degrees C      | ok
Temp 2           | 40 degrees C      | ok
Temp 3           | 64 degrees C      | ok
Temp 4           | 35 degrees C      | ok
Temp 5           | 28 degrees C      | ok
Temp 6           | 28 degrees C      | ok
Temp 7           | 28 degrees C      | ok
Temp 8           | 33 degrees C      | ok
Temp 9           | 30 degrees C      | ok
Temp 10          | 32 degrees C      | ok
Temp 11          | 36 degrees C      | ok
Temp 12          | 38 degrees C      | ok
Temp 13          | 37 degrees C      | ok
Temp 14          | 36 degrees C      | ok
Temp 15          | 35 degrees C      | ok
Temp 16          | 33 degrees C      | ok
Temp 17          | 31 degrees C      | ok
Temp 18          | 31 degrees C      | ok
Temp 19          | 31 degrees C      | ok
Temp 20          | 32 degrees C      | ok
Temp 21          | 29 degrees C      | ok
Temp 22          | 57 degrees C      | ok
Temp 23          | 41 degrees C      | ok
Temp 24          | 40 degrees C      | ok
Power Meter      | 142 Watts         | ok
Memory           | 0x00              | ok

Could you help me devise a script to read this into netdata?
I saw in a reddit thread where it was suggested to open an issue here on Github, in order to ask this...

**Comment by l2isbad** [comment]
Yo @thomasfrivold

[lm_sensors](https://github.com/firehol/netdata/tree/master/python.d#sensors) is not working for you?

```
extra/lm_sensors 3.4.0-2 [installed]
    Collection of user space tools for general SMBus access and hardware monitoring
```

**Comment by thomasfrivold** [comment]
Great points, so you had me dive a little deeper.
Mmkay, I ran sensors-detect, and it tried to help me add lm-sensor/kernel modules.
Here's the output - which I guess describes the issue which I didn't see until now ... Drivers have not been written yet!

> Now follows a summary of the probes I have just done.
> Just press ENTER to continue: 
> 
> Driver `coretemp':
>   * Chip `Intel digital thermal sensor' (confidence: 9)
> 
> Driver `to-be-written':
>   * ISA bus, address 0x300
>     Chip `SMSC SCH4307 Super IO Fan Sensors' (confidence: 9)
>   * ISA bus, address 0xca2
>     Chip `IPMI BMC KCS' (confidence: 8)
> 
> Note: there is no driver for SMSC SCH4307 Super IO Fan Sensors yet.
> Check http://www.lm-sensors.org/wiki/Devices for updates.
> 
> To load everything that is needed, add this to /etc/modules:
> #----cut here----
> # Chip drivers
> coretemp
> #----cut here----
> If you have some drivers built into your kernel, the list above will
> contain too many modules. Skip the appropriate ones!
> 
> 

Therefore, I think my only way of reading these data is by parsing the data from "ipmitool sdr" with the Proliant output (different from Supermicro | Dell)

**Comment by l2isbad** [comment]
Ok. Pls do

```bash
time ipmitool sdr
```

**Comment by thomasfrivold** [comment]
Okay :)

> root@moneymaker:~# time ipmitool sdr
> UID Light        | 0x00              | ok
> Int. Health LED  | 0x00              | ok
> Ext. Health LED  | 0x00              | ok
> Power Supply 1   | 100 Watts         | ok
> Power Supply 2   | disabled          | ns
> Power Supplies   | 0x00              | ok
> Fan 1            | 25.48 percent     | ok
> Fan 2            | 25.48 percent     | ok
> Fan 3            | 25.48 percent     | ok
> Fan 4            | disabled          | ns
> Fans             | 0 percent         | ok
> Temp 1           | 22 degrees C      | ok
> Temp 2           | 40 degrees C      | ok
> Temp 3           | 59 degrees C      | ok
> Temp 4           | 34 degrees C      | ok
> Temp 5           | 26 degrees C      | ok
> Temp 6           | 26 degrees C      | ok
> Temp 7           | 26 degrees C      | ok
> Temp 8           | 31 degrees C      | ok
> Temp 9           | 29 degrees C      | ok
> Temp 10          | 31 degrees C      | ok
> Temp 11          | 34 degrees C      | ok
> Temp 12          | 36 degrees C      | ok
> Temp 13          | 36 degrees C      | ok
> Temp 14          | 35 degrees C      | ok
> Temp 15          | 34 degrees C      | ok
> Temp 16          | 32 degrees C      | ok
> Temp 17          | 30 degrees C      | ok
> Temp 18          | 29 degrees C      | ok
> Temp 19          | 29 degrees C      | ok
> Temp 20          | 30 degrees C      | ok
> Temp 21          | 29 degrees C      | ok
> Temp 22          | 54 degrees C      | ok
> Temp 23          | 39 degrees C      | ok
> Temp 24          | 38 degrees C      | ok
> Power Meter      | 142 Watts         | ok
> Memory           | 0x00              | ok
> 
> real	0m0.241s
> user	0m0.004s
> sys	0m0.000s

Cheers!

**Comment by l2isbad** [comment]
real	0m0.241s
Heavy.
You don't want to call it every second... 

Anyway. 
What charts do you need?
Can you create charts yourself from `ipmitool sdr` and paste it here?

**Comment by thomasfrivold** [comment]
I installed the HP non-free Proliant diag tools from their repositories. Polling using this alternative tool, hp-health is blazing fast. Maybe that is the best way to go.

> root@moneymaker:~# time hplog -t && time hplog -f
> ID     TYPE        LOCATION      STATUS    CURRENT  THRESHOLD 
>  1  Basic Sensor Ambient         Normal    71F/ 22C 107F/ 42C 
>  2  Basic Sensor Processor Zone  Normal   104F/ 40C 179F/ 82C 
>  3  Basic Sensor Processor Zone  Normal   143F/ 62C 179F/ 82C 
>  4  Basic Sensor Memory Board    Normal    91F/ 33C 188F/ 87C 
>  5  Basic Sensor Memory Board    Normal    78F/ 26C 188F/ 87C 
>  6  Basic Sensor Memory Board    Normal    78F/ 26C 188F/ 87C 
>  7  Basic Sensor Memory Board    Normal    77F/ 25C 188F/ 87C 
>  8  Basic Sensor Memory Board    Normal    87F/ 31C 188F/ 87C 
>  9  Basic Sensor Memory Board    Normal    82F/ 28C 188F/ 87C 
> 10  Basic Sensor Memory Board    Normal    86F/ 30C 188F/ 87C 
> 11  Basic Sensor Memory Board    Normal    93F/ 34C 188F/ 87C 
> 12  Basic Sensor I/O Zone        Normal    96F/ 36C 154F/ 68C 
> 13  Basic Sensor I/O Zone        Normal    95F/ 35C 154F/ 68C 
> 14  Basic Sensor I/O Zone        Normal    95F/ 35C 154F/ 68C 
> 15  Basic Sensor I/O Zone        Normal    91F/ 33C 154F/ 68C 
> 16  Basic Sensor I/O Zone        Normal    87F/ 31C 154F/ 68C 
> 17  Basic Sensor I/O Zone        Normal    86F/ 30C 154F/ 68C 
> 18  Basic Sensor I/O Zone        Normal    84F/ 29C 154F/ 68C 
> 19  Basic Sensor Processor Zone  Normal    82F/ 28C 188F/ 87C 
> 20  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
> 21  Basic Sensor SCSI Backplane  Normal    82F/ 28C 140F/ 60C 
> 22  Basic Sensor System Board    Normal   127F/ 53C 230F/110C 
> 23  Basic Sensor System Board    Normal   100F/ 38C 188F/ 87C 
> 24  Basic Sensor System Board    Normal    98F/ 37C 188F/ 87C 
> 
> 
> real	0m0.002s
> user	0m0.000s
> sys	0m0.000s
> ID     TYPE        LOCATION      STATUS  REDUNDANT FAN SPEED 
>  1  Var. Speed   System Board    Normal     N/A     Normal   ( 25)
>  2  Var. Speed   System Board    Normal     N/A     Normal   ( 25)
>  3  Var. Speed   System Board    Normal     N/A     Normal   ( 25)
>  4  Basic Fan    System Board    Absent     N/A     Unknown 
> 
> 
> real	0m0.002s
> user	0m0.000s
> sys	0m0.000s
> 
> 

Graphs? I think a time series chart with power usage, time series chart with fan speeds could be cool!

**Comment by l2isbad** [comment]
@thomasfrivold 
**root**@moneymaker:~# time hplog -t && time hplog -f

Can you execute command as non root user?

**Comment by l2isbad** [comment]
And pls check in python interpreter (if you need root privileges to execute `hplog` use `sudo python` or execute `python` as root)

```python
from subprocess import Popen, PIPE
import re
reply = Popen(['hplog', '-t'], stdout = PIPE)
reply = reply.communicate()[0]
reply = reply.decode()
reply = ' '.join(reply.splitlines())
re.findall(r'Basic Sensor ([\w\/]+) \w+(?: \w+)? (\d+)F/ (\d+)C (\d+)F/ (\d+)C', reply)
```

If output looks like
```
[('Ambient', '71', '22', '107', '42'),
 ('Processor', '104', '40', '179', '82'),
 ('Processor', '143', '62', '179', '82'),
 ('Memory', '91', '33', '188', '87'),
 ('Memory', '78', '26', '188', '87'),
 ('Memory', '78', '26', '188', '87'),
 ('Memory', '77', '25', '188', '87'),
...
...
...
```

**Comment by ktsaou** [comment]
Guys can we close this? Is there anything pending?

**Comment by l2isbad** [comment]
> Is there anything pending?

No. @thomasfrivold guy was gone. He can reopen later if he needs to.

**Comment by thomasfrivold** [comment]
Hi, sorry I went away. My girlfriend visited and I had to turn off my noisy server :)

@l2isbad :+1: 
Here is what you requested:

time hplog -t && time hplog -f

root@moneymaker:/infrastructure/ipmi.datafeed# time hplog -t && time hplog -f
ID     TYPE        LOCATION      STATUS    CURRENT  THRESHOLD 
 1  Basic Sensor Ambient         Normal    77F/ 25C 107F/ 42C 
 2  Basic Sensor Processor Zone  Normal   104F/ 40C 179F/ 82C 
 3  Basic Sensor Processor Zone  Normal   104F/ 40C 179F/ 82C 
 4  Basic Sensor Memory Board    Normal   102F/ 39C 188F/ 87C 
 5  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 6  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 7  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 8  Basic Sensor Memory Board    Normal    95F/ 35C 188F/ 87C 
 9  Basic Sensor Memory Board    Normal    87F/ 31C 188F/ 87C 
10  Basic Sensor Memory Board    Normal    91F/ 33C 188F/ 87C 
11  Basic Sensor Memory Board    Normal   100F/ 38C 188F/ 87C 
12  Basic Sensor I/O Zone        Normal   107F/ 42C 154F/ 68C 
13  Basic Sensor I/O Zone        Normal   105F/ 41C 154F/ 68C 
14  Basic Sensor I/O Zone        Normal   105F/ 41C 154F/ 68C 
15  Basic Sensor I/O Zone        Normal   102F/ 39C 154F/ 68C 
16  Basic Sensor I/O Zone        Normal    98F/ 37C 154F/ 68C 
17  Basic Sensor I/O Zone        Normal    95F/ 35C 154F/ 68C 
18  Basic Sensor I/O Zone        Normal    93F/ 34C 154F/ 68C 
19  Basic Sensor Processor Zone  Normal    84F/ 29C 188F/ 87C 
20  Basic Sensor Memory Board    Normal    91F/ 33C 188F/ 87C 
21  Basic Sensor SCSI Backplane  Normal    93F/ 34C 140F/ 60C 
22  Basic Sensor System Board    Normal   140F/ 60C 230F/110C 
23  Basic Sensor System Board    Normal   109F/ 43C 188F/ 87C 
24  Basic Sensor System Board    Normal   109F/ 43C 188F/ 87C 


real	0m0.002s
user	0m0.000s
sys	0m0.000s
ID     TYPE        LOCATION      STATUS  REDUNDANT FAN SPEED 
 1  Var. Speed   System Board    Normal     N/A     Normal   ( 25)
 2  Var. Speed   System Board    Normal     N/A     Normal   ( 25)
 3  Var. Speed   System Board    Normal     N/A     Normal   ( 29)
 4  Basic Fan    System Board    Absent     N/A     Unknown 


real	0m0.002s
user	0m0.000s
sys	0m0.000s

>And pls check in python interpreter (if you need root privileges to execute hplog use sudo python or execute python as root)
Yes, I always operate as root. Old-skool.

Your suggested python script runs correctly.
Pardon my ignorance, now what?
Two questions: 
1. How do I make the parsed data available to Net-data?
2. Should I run it as a script like this?
$root@moneymaker:/infrastructure# `while` true ; do sleep 1s && ./python3.4  pythonscript.netdata.from.github.friend.l2isbad.py ; done`

**Comment by l2isbad** [comment]
@thomasfrivold 

> Yes, I always operate as root. Old-skool.

You can't execute  `hpolg` as non root user, right? If so you need to run netdata as root (not recommended but it's up to you).

> Should I run it as a script like this?

You need to make a script_name.chart.py script and move it to the `usr/libexec/netdata/python.d/` directory.

Lets start from `hplog -t`
```
ID     TYPE        LOCATION      STATUS    CURRENT  THRESHOLD 
 1  Basic Sensor Ambient         Normal    77F/ 25C 107F/ 42C 
 2  Basic Sensor Processor Zone  Normal   104F/ 40C 179F/ 82C 
 3  Basic Sensor Processor Zone  Normal   104F/ 40C 179F/ 82C 
 4  Basic Sensor Memory Board    Normal   102F/ 39C 188F/ 87C 
 5  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 6  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 7  Basic Sensor Memory Board    Normal    84F/ 29C 188F/ 87C 
 8  Basic Sensor Memory Board    Normal    95F/ 35C 188F/ 87C 
 9  Basic Sensor Memory Board    Normal    87F/ 31C 188F/ 87C 
10  Basic Sensor Memory Board    Normal    91F/ 33C 188F/ 87C 
11  Basic Sensor Memory Board    Normal   100F/ 38C 188F/ 87C 
12  Basic Sensor I/O Zone        Normal   107F/ 42C 154F/ 68C 
13  Basic Sensor I/O Zone        Normal   105F/ 41C 154F/ 68C 
14  Basic Sensor I/O Zone        Normal   105F/ 41C 154F/ 68C 
15  Basic Sensor I/O Zone        Normal   102F/ 39C 154F/ 68C 
16  Basic Sensor I/O Zone        Normal    98F/ 37C 154F/ 68C 
17  Basic Sensor I/O Zone        Normal    95F/ 35C 154F/ 68C 
18  Basic Sensor I/O Zone        Normal    93F/ 34C 154F/ 68C 
19  Basic Sensor Processor Zone  Normal    84F/ 29C 188F/ 87C 
20  Basic Sensor Memory Board    Normal    91F/ 33C 188F/ 87C 
21  Basic Sensor SCSI Backplane  Normal    93F/ 34C 140F/ 60C 
22  Basic Sensor System Board    Normal   140F/ 60C 230F/110C 
23  Basic Sensor System Board    Normal   109F/ 43C 188F/ 87C 
24  Basic Sensor System Board    Normal   109F/ 43C 188F/ 87C 
```

What chart/charts do you need?

**Comment by ktsaou** [comment]
freeipmi plugin written in C is in PR #1881

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
I have merged several changes to freeipmi plugin for netdata. It is now more compatible and it also has alarms in case IPMI reports critical sensors.

If you have high cpu on `kipmi0` process (a kernel thread), please check the [netdata wiki page](https://github.com/firehol/netdata/wiki/monitoring-IPMI#kipmi0-cpu-usage) for the fix (you need to pass a kernel parameter to lower the frequency the kernel polls the IPMI processor).
