### ISSUE TITLE
Keep loading when losing focus

### ISSUE THREAD

**Issue by mcharron** [firehol/netdata#173]
Hello,

I don't know if I'm doing something wrong, or if it's already answered (I searched but nothing fits to my needs).

I want to know if there's a way to let netdata loading informations, even when you're not in the window ? I keep a chrome window open on my screen but I have to focus it to get netdata parsing informations.

I'm working on ubuntu 15.04.

Thanks

**Comment by ktsaou** [comment]
on you netdata dashboard, there is a "settings" button on the top right.

**Comment by mcharron** [comment]
Ahah, I've seen it but I've not seen the "On focus" switch... My bad. Thanks !
