### ISSUE TITLE
python.d.plugin crashes with RHEL 5

### ISSUE THREAD

**Issue by orgito** [firehol/netdata#1731]
Because RHEL  uses phython 2.4, python.d.plugin does not work.

It is possible to install python26 in RHEL 5, but it is not trivial to make it default. 

So, to workaround the problem I installed **python26**, **python26-requests** and **python26-mysqldb.** 

And changed the second line of **python.d.plugin** 

```bash
'''':; exec "$(command -v python || command -v python3 || command -v python2 || echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
```
to 
```bash
'''':; exec "$(command -v python26 || command -v python3 || command -v python2 || echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
```

Just leaving this here as it could be useful to someone else

**Comment by l2isbad** [comment]
>  but it is not trivial to make it default.

Dirty workaround is (not recommended)

```bash
cd /usr/bin
ls -l python
lrwxrwxrwx 1 root root 7 Dec 24 17:04 python -> python2.7
rm python
ln -s python2.6 python
```

**Comment by orgito** [comment]
Really note recommended. RHEL 5 various system commands (yum, etc) require pytho 2.4 as default. Many things will break if you do that. No easy or supported way tho change the default system python.

Better workaround:
```bash
sed -i 's/command -v python /command -v python26 /' /usr/libexec/netdata/plugins.d/python.d.plugin
```

Adjust the path to python.d.plugin for your installation

**Comment by ktsaou** [comment]
To avoid having this change broken every time you update netdata, I suggest to do this:

1. Create somewhere a directory to hold the right python link. e.g. `/usr/local/netdata/bin`.
2. Create a link in this directory for `python` -> `/usr/bin/python26`
3. Edit `/etc/netdata/netdata.conf` and set `PATH environment variable = /usr/local/netdata/bin:...rest of $PATH...`
4. Restart netdata

It should work...

**Comment by ktsaou** [comment]
This is the point in `/etc/netdata/netdata.conf` to do it:

```
[plugins]
	# PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
	# PYTHONPATH environment variable = 
	# tc = yes
	# idlejitter = yes
	# proc = yes
	# diskspace = yes
	# cgroups = yes
	# checks = no
	# plugins directory = /usr/libexec/netdata/plugins.d
	# enable running new plugins = yes
	# check for new plugins every = 60
	# apps = yes
	# fping = yes
	# python.d = yes
	# charts.d = yes
	# node.d = yes
```

Just uncomment the `PATH` line and prepend the directory you created to it, with a colon `:`.

**Comment by orgito** [comment]
Thank you. Way better solution!
