### ISSUE TITLE
Enable iframe by using X-Frame-Options 

### ISSUE THREAD

**Issue by billibit** [firehol/netdata#1735]
I would like to use iframe to show netdata dashboard inside a monitor app. 
How to enable iframe in the netdata web server?

if I know which web app Netdata is using, I can probably figure out which to enable the X-Frame-Options ...

**Comment by ktsaou** [comment]
You need to create a custom dashboard, like this: http://london.my-netdata.io/demo.html

example:

```html
<html lang="en">
<script type="text/javascript" src="dashboard.js?v20170105-7"></script>
<script>
NETDATA.options.current.stop_updates_when_focus_is_lost = false;
</script>
<body>

<div style="width: 100%; text-align: center;">
    <div data-netdata="netdata.server_cpu"
            data-dimensions="user"
            data-chart-library="gauge"
            data-width="150px"
            data-after="-60"
            data-points="60"
            data-title="Yes! Realtime!"
            data-units="I am alive!"
            data-colors="#FF5555"
            ></div>
    <br/>
    <div data-netdata="netdata.server_cpu"
            data-dimensions="user"
            data-chart-library="dygraph"
            data-dygraph-theme="sparkline"
            data-width="200px"
            data-height="30px"
            data-after="-60"
            data-points="60"
            data-colors="#FF5555"
            ></div>
</div>
</body>
</html>
```

Then you can embed it anywhere you like.

Keep in mind I have set `NETDATA.options.current.stop_updates_when_focus_is_lost = false` to make it auto-refresh the charts even when focus is lost (focus will always be lost when running in an iframe, unless you click inside the iframe).

**Comment by ktsaou** [comment]
btw, you can also embed netdata charts in your web application directly: just load `dashboard.js` from the netdata server and add one or more divs to render the charts.

**Comment by billibit** [comment]
I like the index.html and don't want to spend time to build my own page. Why we can't modify the index.html or the web server to enable the iframe?
I understand it is a custom web server in C, is there a way to enable the iframe option support in the response?

**Comment by ktsaou** [comment]
I am sorry, I don't really follow. `iframe` has nothing to do with HTTP. It is an HTML property. So, the web server has nothing to do with it.

netdata charts can be perfectly embedded with `iframe`. The problem though, is that charts will auto-refresh only when you click in the `iframe`. You can enable the always refresh option with a javascript line, but this way, the charts will always be refreshing, even if you have the charts in a minimized window or an out of focus tab.

Am I missing something?

**Comment by ktsaou** [comment]
I mean, `iframes` are handled entirely by web browsers, not web servers. Web servers know nothing about them.

**Comment by billibit** [comment]
The X-Frame-Options must be set on the web server in the response header, it is not a web page side option. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Note: Setting the meta tag is useless! For instance, <meta http-equiv="X-Frame-Options" content="deny"> has no effect. Do not use it! Only by setting through the HTTP header like the examples below, X-Frame-Options will work.

Configuring Apache

To configure Apache to send the X-Frame-Options header for all pages, add this to your site's configuration:
Configuring Apache

To configure Apache to send the X-Frame-Options header for all pages, add this to your site's configuration:
Header always append X-Frame-Options SAMEORIGIN

**Comment by ktsaou** [comment]
ok. I didn't know that.
I'll add a configuration options to allow you set it.

**Comment by ktsaou** [comment]
Added it in PR #1797

In `/etc/netdata/netdata.conf` a new option will appear like this:

```
[global]
    web x-frame-options header = 
```

You can set this to whatever the protocol accepts: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Keep in mind the protocol says:

> The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a <frame>, <iframe> or <object> . Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.
> 
> The added security is only provided if the user accessing the document is using a browser supporting X-Frame-Options.

So, this header will only **restrict** you from embedding netdata.
