### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by syswombat** [firehol/netdata#1738]
The experimental packages installer failed.

This is what it says:
i have installed it on a new VM with Debian 8
and also done a 
`apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`
without probelm

please paste your screen here

# curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
 curl: (7) Failed to connect to raw.githubusercontent.com port 443: No route to host
```

**Comment by l2isbad** [comment]
@syswombat 
curl: (7) Failed to connect to raw.githubusercontent.com port 443: **No route to host**

**Comment by syswombat** [comment]
yes how to fix it for curl, for the apt-get packet the Routing will work. Also doing update and upgrade works

**Comment by l2isbad** [comment]
I mean it's not routing issue. I may be wrong but...
You need to check firewall/access-lists etc. Something is blocking your request. If it's not local iptables rules the good idea is to use `tcpdump`.
```bash
tcpdump -n -i IFNAME icmp
```

You need to look for  `ICMP type unreachable/prohibited`. They are from host that blocks your requests.

**Comment by syswombat** [comment]
ok, i will do it tonight, i would not have set up a Firewall or access-list but maybe this was build automatic

**Comment by syswombat** [comment]
```
> ~# tcpdump -n -i IFNAME icmp
> tcpdump: IFNAME: No such device exists
> (SIOCGIFHWADDR: No such device)
```

**Comment by l2isbad** [comment]
You need to replace IFNAME (interface name). 
Or do without  `-i`  option (listen on all interfaces)

```bash
  tcpdump -n icmp
```

**Comment by syswombat** [comment]
found the problem, DHCP gave as Gateway 255.255.255.0 
after I fix it and gave a fix ip it worked nicely
why it gave a wrong gateway ;-( I don't know other Computer are getting all correct.
in this situation my Problem is solved.
thanks a lot, and have a nice day
