### ISSUE TITLE
question about netdata / conf.d / node.d / snmp.conf.md  

### ISSUE THREAD

**Issue by syswombat** [firehol/netdata#1739]
Hello
i have 3 Switch, UPS and NAS which would give Information.
do i have to write all in one File or do i have to crate for each device a file? 
i yes how to Name it exactly?
have a nice day
vinc

**Comment by l2isbad** [comment]
@syswombat 
1 file :pensive:
https://github.com/firehol/netdata/issues/1126

**Comment by ktsaou** [comment]
I am closing this now. If you need help, just post.
