### ISSUE TITLE
how to config Dynamic apps in applications (1:1)?

### ISSUE THREAD

**Issue by zhangxin0112** [firehol/netdata#1742]
hi  tanks your project. i got  some questions.
-bash-4.1$ jps
9554 NodeManager
32499 YarnChild
32387 YarnChild
32490 YarnChild
30970 MRAppMaster
32507 YarnChild
32619 YarnChild
32620 YarnChild
32621 YarnChild
32893 Jps
now i conf my apps_groups.conf 
   YarnChild: *org.apache.hadoop.mapred.YarnChild*
now i could got the charts on web ,,but my real want like this on my web
one cmdname : one cmdname 
 org.apache.hadoop.mapred.YarnChild 192.168.33.204 37588 attempt_1480322685319_0211_m_000002_0 3 :  org.apache.hadoop.mapred.YarnChild 192.168.33.204 37588 attempt_1480322685319_0211_m_000002_0 3
not group: process1 process2 process3 ..
 in that way .i can got the more detail about my apps(the apps is Dynamic)
 what is your suggest?

**Comment by ktsaou** [comment]
I am not sure I understand the question. You want to monitor application `YarnChild`, but you want to have multiple chart dimensions for different instances of it?

**Comment by zhangxin0112** [comment]
yes . in the fact . `jps ` show the apps's named "YarnChild",but use `ps -ef|grep YarnChild`  it's cmdline w
looks like " yarn org.apache.hadoop.mapred.YarnChild 192.168.33.204 34708 attempt_1480322685319_0218_m_000017_0 28"  
"yarn  org.apache.hadoop.mapred.YarnChild 192.168.33.204 34708 attempt_1480322685319_0218_m_000019_0 29 "
"yarn  org.apache.hadoop.mapred.YarnChild 192.168.33.204 34708 attempt_1480322685319_0218_m_000015_0 27"
.......

Summary：
the same process name but not the same process
likes web tomcat named "Bootstrap" , i could start any number web tomcat process ,they all the same name,but not the same process,maybe the diff just the ports.

want:
one process name : one process 
thanks.

**Comment by ktsaou** [comment]
When you start the same process multiple times, does anything change in its process tree? Use `ps fax` to see it.

If you start it with a script or a command line argument, and this still remains in `ps fax` having the `yarn` processes as children, you could match the parent one that is different among instances.

If this is not possible for you, how would you suggest to match them? I mean you would need to know they are `yarn1`, `yarn2`, `yarn3`. How would you like to configure them, so that `yarn1` will be a specific one (i.e. not a random one)?

**Comment by zhangxin0112** [comment]
thanks for your reply.
in my consider. the command `top` shows the results:
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND 
28010 tools     20   0 6676m 1.3g  13m S  0.0  1.4  32:36.40 /usr/java/jdk1.8.0_66/jre/bin/java -Djava.util.logging.config.file=/opt/app/eis-tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLo
29430 tools     20   0 6410m 1.2g  17m S  0.3  1.3   3:11.58 /usr/java/jdk1.8.0_66/jre/bin/java -Djava.util.logging.config.file=/opt/app/edm-tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLo
 2165 tools     20   0 30.0g 1.2g  15m S  1.0  1.3 137:16.06 /usr/java/jdk1.8.0_66/jre/bin/java -Djava.util.logging.config.file=/opt/app/api-tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLo

the command `jps` shows the results:
24484 Jps
2165 Bootstrap
29430 Bootstrap
28010 Bootstrap

use the `top` 's  COMMAND as process's name ,then it will became dynamic and it monitors every process ,not groups.

**Comment by ktsaou** [comment]
Yes I understand these commands shown PIDs. However, showing PIDs at the netdata dashboard is not possible.

Could you please post `ps fax`?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
