### ISSUE TITLE
where is the app debug log fiel ?

### ISSUE THREAD

**Issue by zhangxin0112** [firehol/netdata#1743]
i set my apps_groups.conf : 
DataNode: a + *org.apache.hadoop.hdfs.server.datanode.DataNode*
but where is the log file? 
total 3372
drwxr-xr-x 2 netdata root       4096 Feb  8 03:49 ./
drwxrwxr-x 3 root    root       4096 Feb  6 14:24 ../
-rw-rw-r-- 1 netdata netdata  692210 Feb  8 11:20 access.log
-rw-rw-r-- 1 netdata netdata   62608 Feb  7 16:54 access.log-20170208
-rw-rw-r-- 1 netdata netdata       0 Feb  6 14:24 debug.log
-rw-rw-r-- 1 netdata netdata  758153 Feb  8 11:21 error.log
-rw-rw-r-- 1 netdata netdata 1908445 Feb  7 16:54 error.log-20170208
-rw-r--r-- 1 netdata netdata       0 Feb  6 14:24 .keep
 is am i forget any place to set for open the  debug model?

**Comment by zhangxin0112** [comment]
now i got it .forget it .
https://github.com/firehol/netdata/wiki/troubleshooting-alarms

**Comment by zhangxin0112** [comment]
i  edit my netdata.conf and set debug flags = 0x00800000
now i got some debug message in debug.log but i still can not find any message about my app set.
what should i do ?

**Comment by ktsaou** [comment]
Can you post the alarm configuration for your app?

**Comment by zhangxin0112** [comment]
yes .now .i think the netdata.conf  set the key debug flags = 0xffffff   ,that is point the netdata's log level..not the a process's debug message. yes that right?  
my app_groups.conf looks like:
# -----------------------------------------------------------------------------
# SW applications
YarnChild: a + *Dyarn.app.container.log*
DataNode: a + *org.apache.hadoop.hdfs.server.datanode.DataNode*
JournalNode: a+*org.apache.hadoop.hdfs.qjournal.server.JournalNode*
DFSZKFailoverController: a+ *org.apache.hadoop.hdfs.tools.DFSZKFailoverController*
Kafka: a+*/opt/kafka/kafka_2.11-0.9.0.0/config/server2.properties*
Bootstrap: a +*org.apache.catalina.startup.Bootstrap*

i want: got the process's detail info. 

-----------------------------------------------------------------
btw could u repaly  it ? 
[https://github.com/firehol/netdata/issues/1742](url)

thanks u.

**Comment by zhangxin0112** [comment]
i think:
i want to implementation one process : one process 
and the process is dynamic
if i get the detail info about a process ,

**Comment by ktsaou** [comment]
`apps.plugin` does not have a debug log file.

To get the debug output (it is very cryptic), you have to run:

```sh
# become user netdata
sudo -s /bin/bash netdata

# run apps.plugin
/usr/libexec/netdata/plugins.d/apps.plugin debug 1
```

I am closing this in favour of #1742

**Comment by zhangxin0112** [comment]
got it . thanks u .!!
for now , the apps.plugin's debug output does not contain the process's detail info . 
any way .thanks .
