### ISSUE TITLE
nut plugin: chart for number of clients

### ISSUE THREAD

**Issue by csamsel** [firehol/netdata#1745]
Hi,
i'd like to check the number of clients connected to my upsd to see if everything is in order. The number of clients can easily be checked by running eg:

```
oxygen-system-vm nut # upsc -c eaton | wc -l
2
```

the output format of `upsc -c name`  is just one client per line. I started editing the plugin file but i did not understand how the `awk` part works. I guess a chart definition could look like this:

```
CHART nut_$x.clients '' "UPS Clients" "number" ups nut.clients line $((nut_priority + 8)) $nut_update_every
DIMENSION clients clients absolute 1 
```

personally i'd give a bit higher priority but that's debateable.

**Comment by ktsaou** [comment]
added it to PR #1753.

Once merged, update your netdata and edit `/etc/netdata/charts.d.conf` and set:

```sh
nut_clients_chart=1
```

The above will enable the chart you need.

**Comment by ktsaou** [comment]
(btw, keep in mind macos support in travis is problematic - macos builds never start since yesterday)

**Comment by ktsaou** [comment]
I deleted my last comment (wrong issue)
