### ISSUE TITLE
Can't install on a scaleway.com ARM dediserver with ubuntu 14.04 

### ISSUE THREAD

**Issue by anwar666** [firehol/netdata#1748]
The following packages have unmet dependencies:
 uuid-dev : Depends: libuuid1 (= 2.20.1-5.1ubuntu20) but 2.20.1-5.1ubuntu20.7 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ktsaou** [comment]
hm... I don't know how to help you. This seems distro specific.
@philwhineray any ideas?

**Comment by philwhineray** [comment]
Just pulling suggestions from google here...

Is the package actually held? Try this to find out:

~~~~
dpkg --get-selections | grep hold
~~~~

If not, did you use `apt-get`? Using `aptitude` might give more information as to what is wrong. For that matter, what did you run to get that error, and was there any other output?

**Comment by anwar666** [comment]
root@fra-dedi:~# apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version.
automake is already the newest version.
automake set to manually installed.
gcc is already the newest version.
make is already the newest version.
pkg-config is already the newest version.
pkg-config set to manually installed.
zlib1g-dev is already the newest version.
curl is already the newest version.
git is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 uuid-dev : Depends: libuuid1 (= 2.20.1-5.1ubuntu20) but 2.20.1-5.1ubuntu20.7 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by philwhineray** [comment]
So @ktsaou is definitely correct. You have a problem with ubuntu, not with netdata.

It looks like your packages are somehow out of sync but I don't know how to resolve that. I would try this one last time:

~~~~
aptitude update
aptitude install uuid-dev
~~~~

In case it is just the package list or the problem has been resolved upstream.

If that does not work, my advice is to ask in Ubuntu-specific forums giving those commands and the output.

**Comment by anwar666** [comment]
Thanks a lot.I have already installed netdata successfully.

**Comment by philwhineray** [comment]
Great news. Thanks for letting us know!
