### ISSUE TITLE
using github API to let the users know of new versions

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#175]
The quick adoption of netdata (currently we run with more than 1.000 git clones per day) I think introduces a few issues we have to settle.

One, is how do we communicate with all these users to let them know about bugs we fixed or new features we added.

I don't like to idea of adding anything related to the above at the netdata server.

However, we can add such checks at the **dashboard's javascript**. The web dashboard (i.e. the user's browser) could make a call to github to find out if the installed version of netdata is up to date.

Github provides these APIs:

https://api.github.com/repos/firehol/netdata/commits

or

https://api.github.com/repos/firehol/netdata/releases

Using these the web browser (not the netdata server), could find out if the installed version of netdata is the latest version, possibly show a notification on the web page and probably a link to the commits since the installed version (it is easy to do it using this url: `https://github.com/firehol/netdata/compare/SHA1...SHA2`).

**This will not affect the netdata server.** It can be done using pure javascript at the **user's web browser** and checked just once per day or per week (the check could be cached at browser's local storage), or on user's request (a button somewhere on the dashboard).

To accomplish it, we just need a file inside the web directory with the SHA of the installed version of netdata. This file can easily be created/updated with git hooks, so that every time we push a commit, this file is updated too. The web browser of the user could then fetch this file, query github and decide if there are updates the user should know.

What do you think?
Will this be helpful or desired?

**Comment by ticklemynausea** [comment]
I would welcome such a change.

**Comment by ktsaou** [comment]
@philwhineray can you help setting up this in git?

I have tried do in the following, and it seems to work:

1. Create .gitattributes with these content:

  ```
web/version.txt filter=version_file
```

2. Set the following filters:

  ```
git config --global filter.version_file.smudge 'git log -n 1 | grep ^commit\ | cut -d \  -f 2'
git config --global filter.version_file.clean 'cat >/dev/null'
```

3. touched `web/version.txt` and committed

4. on checkout, `web/version.txt` has the SHA of the last commit

What I miss is that a `git pull` does not re-create `web/version.txt`. It remains the first checked out.
You have to run `rm web/version.txt; git checkout web/version.txt` to update it.

Any ideas?

**Comment by philwhineray** [comment]
I think unfortunately smudge/clean does not do quite what you want. The problem is that if the comitted file does not change (in this case `web/version.txt`) then it is not checked out and the filter not applied.

Have I understood that you are trying to obtain a commit id to embed in the package users will get in order to later compare that to what github reports? It might be more effective just to make your `git log` command part of the `Makefile.am` so it runs as part of the packaging/installation process. Then it will apply the correct version whether it is something we ship or that the user clones and later pulls, provided they install with the tools.

**Comment by ktsaou** [comment]
perfect! You are the best! (so easy and straightforward! - what was I thinking?)

**Comment by philwhineray** [comment]
Actually it may not be perfect - I guess really it should check for `.git` directory before running the command (there won't be one in packaged version) but the two-step process should save the file from corruption.

**Comment by philwhineray** [comment]
No, it doesn't. I will push a fix direct.

**Comment by philwhineray** [comment]
Also, the build system was not using a repo but a tar extracted from git, so it failed trying to get a version. That is now fixed too.

**Comment by ktsaou** [comment]
I have it ready. Check this screenshot:

![image](https://cloud.githubusercontent.com/assets/2662304/14298974/86416c80-fb90-11e5-8c34-f0775f8c1f82.png)

**Comment by ktsaou** [comment]
I did the commit, but the github UI seems to have an issue showing it.

**Comment by ticklemynausea** [comment]
GitHub is having some issues: https://status.github.com/messages

**Comment by ktsaou** [comment]
ok, it showed up...

**Comment by ktsaou** [comment]
well, it showed up on github, but cloning does not include the changes for a few machines...

**Comment by ktsaou** [comment]
oh! I found it. `git pull` over ssh shows everything. `git pull` over https is left behind...

**Comment by ktsaou** [comment]
ok, it is the demo http://netdata.firehol.org/

**Comment by ktsaou** [comment]
Done.
I close it.
