### ISSUE TITLE
hi errors	 help fix  

### ISSUE THREAD

**Issue by genrihx2** [firehol/netdata#1754]
1m ipv4 udp receive buffer errors	
Screenshots http://prntscr.com/e6x5pj

**Comment by ktsaou** [comment]
Yes, your machine is receiving UDP traffic in a rate bigger than the rate it can consume, or at ports no daemon is listening.

Do you believe this is falsely reported by netdata? Why?

**Comment by ktsaou** [comment]
Generally you can use `sysctl` to increase the UDP buffers for all daemons running the system. The application you use, may have its own setting for UDP buffers too.

**Comment by genrihx2** [comment]
yes

**Comment by ktsaou** [comment]
I don't follow. "yes" on what?

**Comment by genrihx2** [comment]
Thank you   ktsaou    Good luck
