### ISSUE TITLE
Can't Install On FreeBSD 12

### ISSUE THREAD

**Issue by brando56894** [firehol/netdata#1762]
I'm trying to build NetData from the Git repo on FreeBSD 12 but it fails because it says it can't find libuuid-devel and/or zlib-devel. I can't seem to find them either. I installed all the packages listed in the installation section. I'm relatively new to FreeBSD, I'm a Linux guy.

I had this same issue when I tried a few weeks ago, but I was able to install NetData from the ports collection.

```
Running command (in /root/netdata):

./configure --prefix=/opt/netdata/usr --sysconfdir=/opt/netdata/etc --localstatedir=/opt/netdata/var --with-zlib --with-math --with-user=netdata CFLAGS=-O2
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/root/netdata':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.
```

**Comment by ktsaou** [comment]
The problem you face is different.

The log above says:

```
configure: error: cannot run C compiled programs.
```

So, I guess you compiler/linker/toolchain is broken.

cc: @vlvkobal

**Comment by vlvkobal** [comment]
I've installed netdata on `FreeBSD-12.0-CURRENT-amd64-20170210-r313561` without any issues.

@ktsaou it was enough to install packages `git bash autoconf automake pkgconf e2fsprogs-libuuid gcc` for building netdata. Are `wget curl autogen autoconf-archive libtool pidof` packages needed for anything?

**Comment by ktsaou** [comment]
1. `curl` is needed for alarm notifications, except email.
2. `pidof` is needed for the installer to restart netdata properly.
3. the others, I am not sure either - if they are not needed for building netdata, we can remove them for the wiki.

**Comment by brando56894** [comment]
I have been using the "canned" templates on FreeNAS, I'll give it a try on FreeBSD 11 that I have running in VMware.

**Comment by brando56894** [comment]
This is an issue with the FreeNAS FreeBSD 12 template as I was able to compile NetData successfully in a stock FreeBSD VM. Sorry about that guys.
