### ISSUE TITLE
Configure apps_groups. Conf

### ISSUE THREAD

**Issue by sonic4002** [firehol/netdata#1765]
1.i would like to monitor several python scripts with different names and different proc-id
but they all apear as "python" in ps fax
i couldnt find a proper apps_groups.conf configuration
to monitor several process using the proc-name

i would appreciate if you help me create a proper config file

What are the titles i can use in the configuration file? Beside the name displayed in the charts
Things like time to measure the script running etc.. 

2.how do i create my own designed dashboard for the scripts i mentioned earlier? 
Is there is a step by step guide or an example i can use to study from? 

Thank you

**Comment by ktsaou** [comment]
1. Use this format: https://github.com/firehol/netdata/blob/3675d1209f10eff1712cc4876910e6cf80a98798/conf.d/apps_groups.conf#L37-L38

   That format, searches for a substring in the whole command line, including all its parameters. So if your command is `python /path/to/my/super/script parameter1 parameter2` you can use `*super/script*` or `*parameter1*`, or any substring.

2. There are many dashboards you can view to understand the idea: [`tv.html`](https://github.com/firehol/netdata/blob/master/web/tv.html), [`demo.html`](https://github.com/firehol/netdata/blob/master/web/demo.html), etc. These are installed at your server: http://your.netdata.ip:19999/demo.html

   The documentation is here: https://github.com/firehol/netdata/wiki/Custom-Dashboards

   There are many undocumented options for each chart library, like here: https://github.com/firehol/netdata/blob/3675d1209f10eff1712cc4876910e6cf80a98798/web/dashboard.js#L4283-L4449 - but to use them, you have to understand how the chart library works. You can experiment of course.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
