### ISSUE TITLE
web_log timings

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1766]
@l2isbad I see at the registry a lot of spikes up to 300ms http://registry.my-netdata.io/#menu_web_log_nginx_netdata_submenu_timings

I am trying to find them in the log, but I cannot.

Any ideas how to test the regex against the log file?

**Comment by ktsaou** [comment]
false alarm. I found the logs. Sorry.

**Comment by l2isbad** [comment]
grep -o ' [0-9]\.[3-9][0-9]* ' access.log
all reponse time 0.300 +
