### ISSUE TITLE
fail to build cloudlinux 6

### ISSUE THREAD

**Issue by LeAnhlinux** [firehol/netdata#1767]
Hello,

When ibuild in cloudlinux 6 i have error belows:

configure.ac:15: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Someone help me !

Best Regard

**Comment by ktsaou** [comment]
@simonnagl have a look at this please.

**Comment by netblues** [comment]
Also same error on centos 6.8. on updating. 
Previous version runs fine
Just Installed on centos 7.3 with no issues too

**Comment by simonnagl** [comment]
This seems an issue with older autogen versions. I'll check it it detail later.

**Comment by netblues** [comment]
./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:15: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

rpm -qa | grep autoconf
autoconf-2.63-5.1.el6.noarch
uname -a
Linux .gr 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by netblues** [comment]
confirm fixed :)

**Comment by ktsaou** [comment]
thanks!

**Comment by simonnagl** [comment]
It seems m4_esyscmd_s is not supported by older autoconf versions. I did could not find an official page with the information since when it is supported.

#1772 tries uses m4_esyscmd instead.

@netblues, @LeAnhlinux Can you check if this is supported by your versions?
