### ISSUE TITLE
Observing strange behavior with netdata and iowait

### ISSUE THREAD

**Issue by BurningSmile** [firehol/netdata#1768]
So recently I have been having problems with iowait. After monitoring disk io with iotop -o I am constantly seeing the journaling service (jbd2) eating io.

Once I turn off netdata [systemctl stop netdata.service] The issue goes away.

It appears to be a bug with the past few releases of netdata. Is there something I am supposed to tweak in the config to stop this from happening? I have it set to retain 1 hour of graphs.

OS is Ubuntu server 16.04.1

I forgot to mention that this is a vps so it is a virtualized env.

Thanks

**Comment by ktsaou** [comment]
Can you start netdata and post these charts:

![image](https://cloud.githubusercontent.com/assets/2662304/22860923/16c3d95e-f114-11e6-922c-dec54b77c374.png)

These charts state which application use disk (physical reads/writes).

Just below these there is another set that provides logical reads/writes (these do not necessarily result in physical disk access).

**Comment by ktsaou** [comment]
Also, if you run systemd, you may have these charts too, that state the systemd services that use disk.

![image](https://cloud.githubusercontent.com/assets/2662304/22860941/daa42de2-f114-11e6-9f79-55e745ddd026.png)

**Comment by BurningSmile** [comment]
The graphs you wanted.
https://i.imgur.com/2hWFxRx.png
https://i.imgur.com/TugmZnb.png

iotop -ao after a few min of running.
https://i.imgur.com/gIwEe9j.png

I should also mention that it doesn't do this on any of the other systems I manage with the same exact configuration and services running. 
I also wiped and reinstalled ubuntu server 16.04.1 LTS on the vps today to completely isolate any old config that might be causing an issue. white it is highly unlikely I wanted to be sure. 
Fortunately there isn't anything on this that is production critical that can't just be backed up.

**Comment by ktsaou** [comment]
ok, I see it writes 4kb/s.

I suggest to do these:

1. Make sure `memory mode` in `netdata.conf` is set to `save`. If you have enabled `memory mode = map`, the kernel will be syncing the netdata memory to disk all the time.
2. Disable the netdata access.log, by setting `access log = none` in `netdata.conf`.
3. Check that netdata error.log is not flooded with logs, while netdata runs (netdata has a flood protection, so this should not happen, but have a look).
4. Make sure `debug.log` is empty, if not please comment out `debug flags` in `netdata.conf`.

Once you do the above, netdata will not write to disk anything.

Keep in mind however, that the disk activity shown is very light and does not justify the waitio you experience. This system has a problem with its disks... they are extremely slow...

**Comment by BurningSmile** [comment]
Thanks for the info. I have contacted our VPS host with seeing if they can do anything about the disks causing this issue. 

tail -n30 netdataerror.log 

https://hastebin.com/eqedenevag.vbs

debug.log is empty

**Comment by ktsaou** [comment]
Have you solved it? Can we close this issue?

**Comment by BurningSmile** [comment]
Yes, I am taking up the issue with the vps host. Thanks for your time.
