### ISSUE TITLE
Netdata reports too many redirects (apache vhost) when looking at Netdata page

### ISSUE THREAD

**Issue by dvdmuckle** [firehol/netdata#1777]
I have Netdata served through an apache reverse proxy, and whenever I look at the page long enough, It reports an alarm of too many redirects.

![](http://i.imgur.com/zBYaZtT.png)

This started happening a couple days ago, I don't know if there was a recent update that broke things or not. FWIW, I haven't tweaked my apache configs in that time either.

**Comment by ktsaou** [comment]
Hi,

Well I need you to verify if this is a bug.

From your twitter post, I understood that you can trigger this alarm. If this is the case, please tail you apache log and then trigger it. Could you please post here your apache log that triggers the alarm?

**Comment by ktsaou** [comment]
This is very interesting, because the alarm https://github.com/firehol/netdata/blob/4578337079b223e94c4a4b2442015786de136ec2/conf.d/health.d/web_log.conf#L57-L68 should be triggered only when there are more than 120 requests/min. So, since you have 40% redirects, it means there are at least 48 redirects.

**Comment by dvdmuckle** [comment]
http://paste.ubuntu.com/23984712/
This is the entire access.log. A lot of stuff relating to Python and by extension netdata. Most of it just looks like the paste bellow though.
http://paste.ubuntu.com/23984697/
This is also the whole of the other_vhosts_access.log, which I think might be important for this alarm. There are also a lot of 300 requests in it, but I'm not sure if that's normal.
https://paste.ubuntu.com/23984753/

**Comment by dvdmuckle** [comment]
It may also be worth mentioning I have a firewall up (UFW) that allows traffic from anywhere to ports 80 and 443, but not 19999. I'm also redirecting all traffic to port 80 on my vhost to port 443. I noticed one of the logs has a lot of requests to port 80, not sure if that has anything to do with it.

**Comment by ktsaou** [comment]
ok, this is the problem (at the last file):

```
dvdmuckle.xyz:80 127.0.0.1 - - [12/Feb/2017:06:25:03 -0500] "GET /server-status?auto HTTP/1.1" 301 563 "-" "Python-urllib/2.7"
```

In the other files it responds properly.

I see other logs like this:

```
49.56.141.35 - - [12/Feb/2017:16:56:50 -0500] "GET /server-status?auto HTTP/1.1" 200 4603 "-" "Python-urllib/2.7"
dvdmuckle.xyz:80 127.0.0.1 - - [12/Feb/2017:06:25:18 -0500] "GET /server-status?auto HTTP/1.1" 301 563 "-" "Python-urllib/2.7"
```

hm... I don't know why your web server sends 301 for this request. This accounts for half the limit (60reqs/sec). I guess that when you access netdata, you trigger a large set of such redirects, which in turn triggers the alarm.

You can disable the netdata alarm (edit the file given at the alarm and comment it out), but if I were you I would try to understand why these redirects happen.

**Comment by ktsaou** [comment]
> It may also be worth mentioning I have a firewall up (UFW) that allows traffic from anywhere to ports 80 and 443, but not 19999. I'm also redirecting all traffic to port 80 on my vhost to port 443. I noticed one of the logs has a lot of requests to port 80, not sure if that has anything to do with it.

I think the redirects are purely domain/hostname based. There is nothing at the firewall level that can influence them.

I am not an apache expert, but I think redirects are handled entirely by the web server .

**Comment by ktsaou** [comment]
So... I think the alarm is real. There is no back. You do have that many redirects.

You have the following options:

1. comment out the alarm.
2. increase the limit of the alarm from 120 to 500.
3. edit `/etc/netdata/python.d/web_log.conf` and ignore the problematic log file (this will also disable the charts for it, but it might be a good solution if that log file does not have any useful info).
4. find the reason you have so many redirects and fix it.

To be clear: I am not implying that it can be fixed. Sometimes web server configuration is a spaghetti. But unfortunately I don't know how to help you fix it (apache configuration is too complicated for me).

**Comment by dvdmuckle** [comment]
Hrm, interesting. I'll investigate it some more. Any reason this would show up only a couple days ago?

**Comment by dvdmuckle** [comment]
I looked into it more. If I turn off redirecting all http trafic on port 80 to https on port 443, the alarm stops. Turning it back on raises the alarm again. That lines up with these lines in the vhosts log.
```
149.56.141.35 - - [12/Feb/2017:16:56:50 -0500] "GET /server-status?auto HTTP/1.1" 200 4603 "-" "Python-urllib/2.7"
dvdmuckle.xyz:80 127.0.0.1 - - [12/Feb/2017:06:25:18 -0500] "GET /server-status?auto HTTP/1.1" 301 563 "-" "Python-urllib/2.7"
```
I do have a redirect line for my port 80 vhost, so I guess if netdata is the one requesting traffic to that port, I think it's fine to ignore the alarm.

**Comment by dvdmuckle** [comment]
However, I'm still confused as to why the alarm only pops up if I have the netdata window in focus. If I'm doing anything else in my browser it's fine.

**Comment by ktsaou** [comment]
> Any reason this would show up only a couple days ago?

I added it to netdata a couple of days ago, part of the new `web_log` plugin.

> However, I'm still confused as to why the alarm only pops up if I have the netdata window in focus. If I'm doing anything else in my browser it's fine.

I think you are redirecting netdata charts too somehow.

Have you added all your apache logs to netdata `web_log` plugin?

**Comment by romanstingler** [comment]
we got 

1m successful = 26.8%
the ratio of successful HTTP responses (2xx) over the last minute

It's a nice idea to implement such things, but there are more variables to consider.
The "problem" we have is, that we get a lot of 304 status codes. 
So I have fixed it for our purpose but in future there should be more discussions prior the implementation.

**Comment by LeeNX** [comment]
Not been following this issue very closely, but I see at the begin, there is no mention of HTTP status code 304, but now you suggestion 304 are bad, which I would like to disagree. 304 are good, less traffic and other resource usage, if it's working correctly.   
  
304 is a cache hit by the client browser - https://httpstatuses.com/304  
    
Something I am hoping to find the time to discuss, but might not really be part of this issue?

**Comment by ktsaou** [comment]
> So I have fixed it for our purpose but in future there should be more discussions prior the implementation.

I am very sorry for the inconvenience. Of course I am open to any ideas on how to do these discussions. I admit I thought this is the way to do it: we add features, you use them and give feedback.

> 304 is a cache hit by the client browser

Sure, it is a good thing and should be accounted to successful responses.

@l2isbad I suggest to add another chart counting:

1. successful requests: 1xx, 2xx, 304
2. redirects: 301, 303, 307, 308
3. bad requests: 4xx
4. server errors: 5xx

Once we have this, I'll adapt all alarms to use this chart.

@LeeNX @romanstingler do you see any issues with this?

**Comment by romanstingler** [comment]
@ktsaou yeah this would be great. 👍

**Comment by ktsaou** [comment]
I am reading about the response codes here: https://httpstatuses.com/
I added all 3xx except 304 to `redirects`. I think all the others are redirects.

**Comment by l2isbad** [comment]
@ktsaou chart name/chart description/chart family?

**Comment by LeeNX** [comment]
As a lowly SysAdmin, 304 as ```successful ``` is good 👍

**Comment by ktsaou** [comment]
I suggest `web_log.response_statuses`, it should be the first in order, family `responses` (together with other 2).

I updated my response above, for the dimension names.

**Comment by ktsaou** [comment]
chart title 'Response Statuses'.

**Comment by romanstingler** [comment]
works for me

**Comment by ktsaou** [comment]
ok, fixed it. Check #1783 for what we did.
Of course, suggestions are welcome.

If you have edited your `/etc/netdata/health.d/web_log.conf`, please delete it so that the new one will be installed (if you haven't edited it, it will be replaced with the new).

**Comment by ktsaou** [comment]
Published blog "The spectacles of a web server log file".

Read it at:
- medium: https://medium.com/@ktsaou/the-spectacles-of-a-web-server-log-file-90c995e9e986#.ab7wdadz0
- github wiki: https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file

Posted on:
- twitter: https://twitter.com/linuxnetdata/status/831431634167660544
- facebook: https://www.facebook.com/linuxnetdata/
- hacker news: https://news.ycombinator.com/item?id=13642330
- reddit /r/linux: https://www.reddit.com/r/linux/comments/5tz8tk/the_spectacles_of_a_web_server_log_file_monitor/
- reddit /r/sysadmin: https://www.reddit.com/r/sysadmin/comments/5tz99h/the_spectacles_of_a_web_server_log_file_monitor/

**Upvote it** and **share it**. Help us spread the word.

**Comment by darioseidl** [comment]
After installing netdata (which is great btw. - it immediately it helped us diagnose a problem, and it's is so pretty to look at), I had the exact same problem as dvdmuckle. We also redirect http requests on port 80 to https on 443, and netdata reported too many redirects coming from netdata itself on /server-status?auto.

I found an easy fix: In `/etc/netdata/python.d/apache.conf` are the URLs defined for collecting data from apache. Changing them from http to https avoids the redirects.

```localhost:
  name : 'local'
#  url  : 'http://localhost/server-status?auto'
  url  : 'https://localhost/server-status?auto'

localipv4:
  name : 'local'
#  url  : 'http://127.0.0.1/server-status?auto'
  url  : 'https://127.0.0.1/server-status?auto'

localipv6:
  name : 'local'
#  url  : 'http://::1/server-status?auto'
  url  : 'https://::1/server-status?auto'
```
