### ISSUE TITLE
central netdata?

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#178]
Go to your installation of netdata at the URL `/tv.html`.

You will find this:

![tv](https://cloud.githubusercontent.com/assets/2662304/14262483/6d8500f8-fabe-11e5-84e1-c510b3bd6ebd.gif)

In this page, charts are coming for 2 netdata servers:
1. The demo site
2. Your local netdata server

Play a bit with it. You cannot tell the difference. Probably the demo site has a bigger network latency. Any other differences? **None**! You cannot tell that one of the 2 netdata servers is the master and the other is the slave (**because both are masters**).

Given that I work on a longer DB, which will allow each netdata manage a longer history, why do we need a central netdata?

I understand a central netdata would solve the following problems:
## Unified dashboard

I.e. compare data from multiple servers. The demo above shows we are already very close to this without a central netdata (and probably better than any other solution).

If you think of it, putting 20 charts on a page that come from 20 different netdata servers, is giving you a tremendous amount of power! You have the horsepower of 20 servers on a single page! Its efficiency is so high that any central DB will not dare to compete with.

As you can see, the hard work has already been done. I am just trying to figure out a flexible UI to manage this power...
## Longer history

Longer history can serve 2 purposes:
- **detailed performance log about the recent past** (e.g. "what did exactly happen last weekend"?)
  
  I hope that with the updates I am planning, netdata will solve this (i.e. up to a few weeks of history). My understanding is that the I/O required for updating this DB, or reading from it to render the charts will be totally ignorable. I think I can prove this. So, please be patient and give me try...
- **general performance statistics** (e.g. "how many queries/s were we serving last year?").
  
  I am not sure this is a job for netdata. You can install influxdb, opentsdb, grafana or an NMS to have this kind of information, probably with data extracted from netdata at regular intervals in lower resolution.
## Alarms

Again, I am not sure this is a job for netdata.

There are plenty of tools out there that do a very good job in this area and netdata will not offer anything more. Of course collecting the data twice is a waste and I hope that either "we" (the netdata community) will push these data to other tools, or "they" (the other communities) will pull these data from netdata.

---

So, do we need a central netdata and why?

(I know, the easy answer is "let's wait to see how you are going to achieve a longer history without a noticeable impact on the server monitored" :)

**Comment by ktsaou** [comment]
I have to admit, since I wrote the above, I spend quite some time thinking of it.

Also, a lot of users ask for something like this.

To my understanding copying the chart data to a central server is the last thing we should do.

Why? 

Well, the default netdata installation on a raspberry pi monitors more than 700 metrics. On most server systems netdata monitors 1500-2000 metrics. I have a server with 5000 metrics. I like this. Actually I would like it to be a lot higher.

Since we have so many metrics, pushing all of them to a central place cannot scale well.

For the moment I am trying to figure out how we could satisfy the needs we have without copying the data:

## Unified dashboard

Check #310 . Having a central registry will allow us to link the dashboards. I have experimented a bit with the demo sites. The demo sites have a little menu at the top left:

![image](https://cloud.githubusercontent.com/assets/2662304/14770177/a6a0a1fc-0a73-11e6-89d0-118c02056869.png)

Of course this is childish currently, but if we could have a registry of all the netdata servers we have installed, the dashboards could have more functionality to make them act as one (like mix and match charts from separate netdata servers).

## Past performance data

Check #309 : Snapshots are a bit different, but I find the idea more powerful that just performance history.

Snapshots could be manual or programmatically triggered and they could include all performance data, in full detail! So, when you have an issue to trace, you just press a button to have all chart data saved for you. Then on the dashboards, you could have a menu to navigate through the snapshots and load them back.

## Alarms / Health Checks

Health checks, could be:

    - are my servers running?

    This can be implemented with a simple "I am here" operation of each netdata server with s central point.

    - notify me when the value A goes above X for 10 seconds.

    This can be implemented on each netdata server, without copying the data.

    - notify me when value A on server1 is above X and value B on server2 is above Y, for 15 seconds

    Notifications like the above can only be implemented centrally. I resist to the idea of copying data to a central place, but I do like the idea of adding simple single chart alerts into each netdata and then have a central server collect all these alarms (that will be generated by each netdata server) and do a simple correlation on them and possibly handle notifications, escalation, etc.

I am still considering all the options...

**Comment by leemalmac** [comment]
What if a server was restarted? As I understand all the data is stored in memory, or not?
For example, if someone use a virtual servers provider like Linode, Digital Ocean, etc a server (hardware) can be restarted by the provider. Digital Ocean does this (I primarily use DO) sometimes to resolve their issues. In this case the data will be lost.

Otherwise, I love the idea to keep things simple and fast as much as possible. Pushing even 100 metrics every second to remote server will affect in 26M database records per day... not bad I must say=)

**Comment by ktsaou** [comment]
> Pushing even 100 metrics every second to remote server will affect in 26M database records per day...

The average for a netdata server is above 1.000 (750 on an RPi, 1015 on the demo sites, 2.200 on my home linux router). If you also have a few applications monitored, multiple interfaces, multiple disks, a few containers, QoS, etc it will easily get above 3.000. And we all should want (at least I want) this to be 10.000 metrics per server. Netdata can do it. We add charts to it and we optimize it all the time. It will do it.

> What if a server has been restarted?

If the server is not crashed, netdata saves its db to disk and loads it back when it starts.

If you really want an archive of past data, check #309. I think snapshots is the way to do it. Snapshots can reduce the data (all the netdata servers can aggregate data - it is needed for the dashboard so it is there since day zero) and at the snapshots you could also select which chart you need saved.

Of course, having just an hour of data on each server is limited. On most of my servers I give it a day, or half, or if memory is limited 1/3 of a day. I will improve this too, by using deduplication, compression and some disk I/O. If we manage to have a week of data on each server, it would be just great!

**Comment by davidak** [comment]
yesterday i had an idea how monitoring should work, i wrote it down:

https://github.com/davidak/davidak.de/blob/59414456e8a3dc2aa440657d6a39ca5dcc692e56/pages/ideen.md#distributed-zero-effort-system-monitoring

netdata is very close to that.

performance data can be locally on each node.

nodes should discover their systemd services (or other init systems), report them to x another nodes and tell that node if they are OK. also tell one other nodes that it is UP. so we can have a distributed network of self-monitoring nodes, that report to other nodes. the other nodes send alerts if the nodes don't report everything is OK. so may give them my e-mail.

the registry is central right now. maybe that can also be distributed? my netdata nodes find other nodes and connect to 512 (?) of them. maybe you can use [libp2p](https://github.com/ipfs/go-libp2p) from IPFS. i can configure my node to report to 2 other nodes, therefor it checks 2 other nodes. one should be on the same (local) network, the other a little bit away (on another datacenter). so if the datacenter explodes where my servers are i get notified from a foreign node of someone else.

what do you think?

**Comment by ktsaou** [comment]
> nodes should discover their systemd services (or other init systems), report them to x another nodes and tell that node if they are OK. also tell one other nodes that it is UP. so we can have a distributed network of self-monitoring nodes, that report to other nodes. the other nodes send alerts if the nodes don't report everything is OK. so may give them my e-mail.

Check #318

> the registry is central right now. maybe that can also be distributed? my netdata nodes find other nodes and connect to 512 (?) of them. maybe you can use libp2p from IPFS. i can configure my node to report to 2 other nodes, therefor it checks 2 other nodes. one should be on the same (local) network, the other a little bit away (on another datacenter). so if the datacenter explodes where my servers are i get notified from a foreign node of someone else.

I try to resist to the idea of self-discovering hosts. I think we should target bigger, more cloud friendly. So, we could host something on AWS, something else on Azure, or DigitalOcean and all these be one. 

Take the registry as an example: if the registry could pass settings, or UI data between nodes, the possibilities are endless, even across data centers, hosting providers, etc.

I plan the same for health monitoring.

I agree that a single node for registry and health monitoring is limited. "at-least-one" or "one-or-more" would be nice, with "more" being any other netdata servers you like. For health monitoring we are going to need nodes that are configured to handle health notifications. At some point we may have a mobile app supporting push notifications, or a chatbot, or a SMS gateway, or a SIP agent to call your mobile phone. These require some special handling that should be implemented at specific hosts only. It is not practical to configure all these features on every host.

I am also thrilled by the idea that the central hosts could be shared, globally. For example, the netdata demo servers could form a global network for netdata registries and health monitoring hosts that all netdata installations could use, out of the box. At these hosts we could integrate SMS gateways, SIP, chatbots, so that we can enjoy the full functionality even if we have just one server, or if the servers we have are scattered all over the internet.

So, yes I agree we need more than one central host (not for the chart data), but I would prefer something more loose, more flexible, more "internet" and less "data center".

Configuration could remain simple and straight forward. For example, all nodes could talk to one of the central monitoring servers (any of them) to get back all the configuration they need, including fallback hosts. So the default configuration could say `health host = http://health.my-netdata-io` and once a netdata talks to this host, it will receive all the configuration it needs, including all the other nodes it can talk for health events.

Of course, I am still researching and evaluating ideas...

**Comment by pierreozoux** [comment]
About this specific topic, I think the main game changer in recent years was the change to a new pattern.

At the time of configuration management, like chef, you had a central database, and whenever you needed a new host, you added it to your central database (like chef server) and chef was aware, and then, it triggered the reconfiguration of your nagios server for instance.
The trend now is to aim at discovery/registration pattern. There is a good article about the idea here:
http://nerds.airbnb.com/smartstack-service-discovery-cloud/

The idea is to have a distributed key-value store (like etcd). Then every new host will register there. And then, some specific process will watch this to discover some hosts.

So I think this is a classic problem, and we shouldn't reinvent the wheel.

We could have a simple configuration to push everything to a master, or a more advanced thing where the master will discover new hosts. It actually depends if it is a push or pull I guess.

In my specific use case, I'll use docker swarm. All the nodes are already registered to the swarm masters. So I'd just need to discover all the hosts and bake a new configuration for netdata.

my 2 cents

**Comment by ktsaou** [comment]
@pierreozoux keep in mind that "discovery" may be applied in many areas for netdata:

1. discover the metrics to be monitored
2. discover the containers running (2a) and their applications (2b)
3. discover the registry to advertise 
4. discover the health hosts to send health events to
5. discover other netdata servers

I strongly believe each netdata should focus on just one host. This is a key design principle. Of course it could connect to a remote server to collect data, but I strongly believe this should be limited if it cannot be avoided. It should only be used when a netdata cannot be installed at the remote host.

netdata already has great auto-discovery features for the metrics to be monitored and the applications running on each system (1). It also discovers the containers (2a) and I would love to work on auto-discovery of apps running within containers (2b - so a netdata running at the host, discovers the apps running inside containers). Keep in mind netdata should not run in a container. It should run at the host to monitor everything inside all containers. It already does this for the resource utilization of all containers, and we need to make it happen for containerized apps too.

(3) and (4) are very simple. Yes, we could use etcd for that, but I wouldn't hardcode it in netdata. DevOps should be able to kickstart netdata with settings taken from etcd or whatever.

What I don't like is (5). I cannot see how this will help in any direction.

**Comment by davidak** [comment]
How would you check if a host is alive? I want to get notified if one fails.

**Comment by ktsaou** [comment]
> How would you check if a host is alive? I want to get notified if one fails.

Each netdata will have to report once every (e.g) 1 minute to the health monitoring hosts (any of them). This will also allow some basic charts to come from the health monitoring hosts (i.e. this periodic report from all hosts will include a few basic metrics - or the metrics you want reported).

I also plan to detect system reboots and application restarts using their uptime. If the new uptime is smaller that the last, then we have a restart.

**Comment by ktsaou** [comment]
PR #775 adds alarms to netdata.
I am looking for beta testers. If you are interested join the discussion there.

**Comment by ktsaou** [comment]
implemented netdata backends: **graphite** and **opentsdb** in PR #1264 .
testers needed, so if you use any, please join comment on the PR.

**Comment by ktsaou** [comment]
merged it. so just update netdata and configure it.
wiki page: https://github.com/firehol/netdata/wiki/netdata-backends

**Comment by mailinglists35** [comment]
I have an use case where the operator has to monitor metrics of a system to which he does not have tcp/ip connectivity to (it's a database behind a firewall), but has access to the front end application host on where a netdata is running.

In this case I cannot use the tv.html example dashboard as there is no direct ip connectivity between the browser and the monitored system.

Will registry allow this scenario?

**Comment by l2isbad** [comment]
@mailinglists35 you can use nginx/apache to proxy requests from the operator

**Comment by mailinglists35** [comment]
yes, but that means additional work as bandaid around netdata.
My question was about netdata being able to remotely collect metrics from another netdata.

**Comment by l2isbad** [comment]
> My question was about netdata being able to remotely collect metrics from another netdata.

Implemented in https://github.com/firehol/netdata/pull/1817

Push model

**Comment by mailinglists35** [comment]
Whoa, that looks exactly like what I needed. Thank you! :)

**Comment by l2isbad** [comment]
Yeah. PR is **super amazing**.

**Comment by ktsaou** [comment]
I think we can close this now. netdata can be centralized...
