### ISSUE TITLE
Question about weblog alerts

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1781]
The alert "the ratio of successful HTTP responses (2xx) over the last minute" raises pretty often on one of my webservers where we occasionally have over 10% responses in the 3xx area. This is not necessarily an error, in fact with caching the 304 (not modified) can be quite common.

From that host I'm now getting pretty regular alerts, not only warnings but even critical alerts although operations are just running normal.

My suggestion for alert configuration would be like this:

- Response codes 5xx are always important and should be a critical alert
- Response codes 4xx are noteworthy but should probably only raise silent alerts
- All other response codes are OK

What do you think?

**Comment by ktsaou** [comment]
Yeah, I didn't though about 304... We are fixing it as part of #1777 - check the discussion there.

I think 4xx should not be silent. We may have to increase the thresholds, but if there are too many of them, you should get a notification. What do you think?

I you agree, do you want to suggest 4xx thresholds?

**Comment by jurgenhaas** [comment]
Sorry I missed the other issue and created this one which is clearly a duplicate.

Regarding a 4xx threshold I think that's hard to tell and depends heavily on circumstances (overall traffic, nature of site(s), etc.). E.g. if you have a website with a paywall it would be expected to get 401, 402 and 403 which will trigger a call to action to the visitor the either login or make some payments.

404 on the other hand can happen quite often if one changed platform and hasn't properly defined redirects for the new site structure.

And unfortunately there are some web applications that are poorly developed and they caus 4xx warnings quite regularly so I'm not sure if everyone would be happy to get alerted about them all the time. On the other hand, from a performance monitoring point of view, it is important to create awareness and get people to fix that stuff.

**Comment by ktsaou** [comment]
ok, fixed it. Check #1783 for what we did.
Of course, suggestions are welcome.

If you have edited your `/etc/netdata/health.d/web_log.conf`, please delete it so that the new one will be installed (if you haven't edited it, it will be replaced with the new).

**Comment by jurgenhaas** [comment]
Perfect, this looks great.

**Comment by ktsaou** [comment]
I increased the thresholds a lot to avoid false positives. The PR has more information.

**Comment by ktsaou** [comment]
@jurgenhaas I would love to know your experiences with the `5m_requests`. This alarm breaks the database in 5 minute intervals and compares the adjacent ones. If they differ a lot, it triggers the alarm.

**Comment by ktsaou** [comment]
This is an attempt to find sudden increases or decreases in web requests.

**Comment by jurgenhaas** [comment]
@ktsaou so far my experience is great with your new alarm settings. With regard to the `5m_requests` I haven't had any issue for the last 24 hours. When ever I looked, I only seem to be having successful responses with quite a few of 304s and only a little 302s but everything else is in the 200s.

The settings in the alarm config file though seems to make sense and I guess we have to monitor that for a while to see what's the long term experience. But so far, this is excellent. Thanks a lot.

**Comment by ktsaou** [comment]
ok thanks! keep in mind you can also enable a timing alarm if you log timing information. `/etc/netdata/python.d/web_log.conf` has information about `nginx` and `apache` config

**Comment by ktsaou** [comment]
Published blog "The spectacles of a web server log file".

Read it at:
- medium: https://medium.com/@ktsaou/the-spectacles-of-a-web-server-log-file-90c995e9e986#.ab7wdadz0
- github wiki: https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file

Posted on:
- twitter: https://twitter.com/linuxnetdata/status/831431634167660544
- facebook: https://www.facebook.com/linuxnetdata/
- hacker news: https://news.ycombinator.com/item?id=13642330
- reddit /r/linux: https://www.reddit.com/r/linux/comments/5tz8tk/the_spectacles_of_a_web_server_log_file_monitor/
- reddit /r/sysadmin: https://www.reddit.com/r/sysadmin/comments/5tz99h/the_spectacles_of_a_web_server_log_file_monitor/

**Upvote it** and **share it**. Help us spread the word.

**Comment by jurgenhaas** [comment]
Great article, I've upvoted and shared via Twitter.
