### ISSUE TITLE
Running behind nginx - No images

### ISSUE THREAD

**Issue by azzaka** [firehol/netdata#179]
when pulling a remote SERVER, Nginx calls the page fine however it does not appear to pull/parse the images/css properly.

My server file is below:

upstream host-apps {
    server host.apps:19999;
    keepalive 64;
}

upstream host-plex {
    server host.plex:19999;
    keepalive 64;
}

upstream host-gate {
    server host.ssh-gate:19999;
    keepalive 64;
}

server {
   listen       80;
   server_name domain.com;

location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Scheme   $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://host-$behost/$ndpath$is_args$args;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}

I do actually use Proxy_pass for other software instances and these appear to be fine. I'm wondering if I need to tell netdata what the base url is. 

Any help appreciated.

**Comment by ktsaou** [comment]
Your config is not right.
This is the corrent way: https://github.com/firehol/netdata/wiki/Running-behind-nginx#access-multiple-netdata-servers-via-one-nginx

**Comment by azzaka** [comment]
Hi ktsaou,

I amended the config as suggested in the original installation guide and still no joy. I amended the domain with the server IP as above and still no change.

eg: http://bloodyc.at/netdata/server1/

**Comment by ktsaou** [comment]
Check your nginx logs. It should be complaining...

**Comment by azzaka** [comment]
I amended the domain to the external IP and it does work. So no errors in the log files, and when the FQDN is used, the page does not find the css/images, yet with the external IP it works fine.

any idea's?

**Comment by ktsaou** [comment]
In your config you say:

```
location ~ /netdata/(?.)/(?.) {
```

But the right one is:

```
location ~ /netdata/(?<behost>.*)/(?<ndpath>.*)
```

because you need the variables `behost` and `ndpath` defined later:

```
proxy_pass http://host-$behost/$ndpath$is_args$args;
```

**Comment by azzaka** [comment]
I amended the config to be exactly as you suggested. See below:

upstream backend-server1 {
    server 192.168.2.14:19999;
    keepalive 64;
}
upstream backend-server2 {
    server 192.168.2.15:19999;
    keepalive 64;
}
upstream backend-server3 {
    server 192.168.2.13:19999;
    keepalive 64;
}

server {
   listen      80;
   server_name 212.23.5.58 192.168.2.14;

# Location block for calling the Netdata backend streams
location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend-$behost/$ndpath$is_args$args;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }

}

**Comment by ktsaou** [comment]
So, you mean that when the url is `http://name/netdata/server1/` does not work, but when it is `http://ip/netdata/server1/` it work?

This seems a problem of nginx. I don't know how to help you. Does nginx have alias names or something? 

I see mine has:

```
    listen 1.2.3.4:80;
    server_name netdata.firehol.org;
```

Probably you need to set the names too?

**Comment by azzaka** [comment]
I don't have the issue when using any other app. Only this one. It is strange. I'll amend the config to include the ip address on the listen, however will this be set to the internal or external?

**Comment by ktsaou** [comment]
I am sorry, I don't know. I am not an nginx expert...

**Comment by azzaka** [comment]
No problem. I appreciate you trying to help. I set the IP as above and then amended the domain name, however again there was no joy. No matter, the multi server works via the external IP and that's certainly good enough for me.

**Comment by ktsaou** [comment]
shall we close this?

**Comment by azzaka** [comment]
Technically it is still an issue since netdata cannot use dns when behind the proxy. I'm ok with the way it works, I would suggest adding a note to the nginx proxy page so there are no repeat queries about the issue.

**Comment by ktsaou** [comment]
I am not sure. I use it with dns normally in debian, ubuntu, gentoo, using the configurations from the wiki (my production configs are there). Something else is happening, but I am not sure what. We need an nginx expert...

**Comment by DriverXX** [comment]
In your nginx config you put only ip in 'server_name':

server_name 212.23.5.58 192.168.2.14;

You also need to put your domain name, otherwise nginx handle request only form the ip but not the domain.
Example:

server_name 212.23.5.58 192.168.2.14 yourdomain.com;

**Comment by ktsaou** [comment]
Did you make it?
Can we close this?

**Comment by rgiyf** [comment]
@azzaka as i understand you want handle netdata like http(s)://yourdomain.com/netdata ?
you can add something like this to your server directive:
```
location @netd {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;

        rewrite ^/netdata(.*) /$1 break;
        proxy_pass http://127.0.0.1:19999;
    }
location /netdata {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        root /var/www;
        index index.html;
        
        try_files $uri $uri/ @netd;
        
   }
```
I think you can delete ```proxy_set_header X-Forwarded-Proto https;``` if not using https. In my case nginx handling static files from ```/var/www/netdata``` and redirects anything else to netdata daemon. That the whole point :) Found this approach when tried to config nginx with tomcat.

**Comment by azzaka** [comment]
Thanks for this. 

I have amended it as suggested, however this is suggesting that I have static pages to server, which in the case of Netdata is incorrect.

I use the multi-server method, which creates the url as http://ip-address/netdata/server1/ etc. What I essentially want is the same, but by using the hostname or fqdn. ie: http://host.apps/netdata/server1/

**Comment by lokiiiii** [comment]
Hello there,
I've been searching for a way to access netdata through URI with nginx as reverse proxy, and I found the solution of @rgiyf which kind of work:
With this nginx configuration, I can access my netdata through https://myserver.com/netdata/ but if I go to https://myserver.com/netdata (without the ending "/" ), css seems to not load and I got a weird page without infos or graphs or css.
Do you have any idea ? 
Thanks a lot!

**Comment by rgiyf** [comment]
@lokiiiii do you use my example like this `location /netdata` or like this `location /netdata/`(with the ending "/")?

**Comment by lokiiiii** [comment]
Without the ending / , that's why I can't understand... :D 

Here is my conf:

`location @netd {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                rewrite ^/netdata(.*) /$1 break;
                proxy_pass http://127.0.0.1:19999;
        }

        location /netdata {
                root /var/www;
                index index.html;
                try_files $uri $uri/ @netd;
        }`

**Comment by rgiyf** [comment]
@lokiiiii strange 🤔 my instance just add "/" every time if I'm not specifying it.

**Comment by lokiiiii** [comment]
Pretty strange indeed, I've check over google and couldn't find some answers...
Some are reporting issue with trailing slash but it couldn't help...
If anyone could help... ? :D 
Thanks anyway !

**Comment by rgiyf** [comment]
@lokiiiii I guess you need to go to dev console of your browser and debug. And recheck nginx configs 😃

**Comment by lokiiiii** [comment]
Awkward, after playing with my conf, I went back with your config, and now, going to https://mydomain/netdata automatically redirect me to https://mydomain.com...
I really am lost here... :D

**Comment by ktsaou** [comment]
I solved it in my multi-netdata nginx passthrough by sending to the browser a 301 (moved) to the URL with the trailing slash.

Check it here: https://github.com/firehol/netdata/wiki/Running-behind-nginx#access-multiple-netdata-servers-via-one-nginx

**Comment by lokiiiii** [comment]
Thanks @ktsaou but as I don't use multi netdata config, I'm not using $behost, etc...
So I don't really know how to adapt your return 301 into @rgiyf config...
My competences are pretty limited here... :(
Thanks anyway to both of you :)

**Comment by azzaka** [comment]
Sorry my servers been offline for a spell. (Lost drives.) I'll be back up and running shortly and then I'll test the DNS config again. 

DriverXX, the issue with adding the DNS is that it wont work with DNS. Hence my questions.

**Comment by ktsaou** [comment]
ok. Let me close this for now. If you need help just help.

**Comment by ktsaou** [comment]
Just post.

**Comment by peelos** [comment]
hi, thanks for the attention to this great application, I have tried the wiki settings for Nginx reverse proxy yet haven't manage to integrate into my SSL domain

my working Nginx.conf currently with some example location configurations:


```
server {
        listen 443;
        ssl on;
        server_name  sub.domain.com;
        ssl_certificate  /share/CACHEDEV1_DATA/.qpkg/QNginx/cert_chain.crt;
        ssl_certificate_key /share/CACHEDEV1_DATA/.qpkg/QNginx/sub_domain_com.key;

        location / {
            root   html;
            index  index.php index.html index.htm;
        }

location ^~ /location1 {
        proxy_pass http://127.0.0.1:1111; 
        proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location ^~ /location2 {
        proxy_pass http://127.0.0.1:2222;
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_set_header    X-Forwarded-Ssl     on;
        proxy_set_header    X-Forwarded-Host    $server_name;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;

        }

        location ^~ /location3 {
        proxy_pass https://127.0.0.1:8443/location3; 
                proxy_read_timeout 1800s;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }
```

could you please explain where the code on your wiki for NGinx would fit in this configuration?

**Comment by ktsaou** [comment]
I am not an nginx expert, but I think you should create a new `location` for netdata and add the back-end server configs needed for nginx to reach netdata.
