### ISSUE TITLE
web_log_nginx_access decode() takes no keyword arguments

### ISSUE THREAD

**Issue by adude00** [firehol/netdata#1792]
Hi, we installed netdata on our log aggregator, a Centos 6.6 with Python 2.6.6.

we're having this error while decoding nginx logs:
```
2017-02-14 17:36:04: python.d ERROR: web_log_nginx_access decode() takes no keyword arguments
2017-02-14 17:36:04: python.d ERROR: DISABLED: web_log/nginx_access
```

It was configured as such:
```
nginx_access:
  name: 'externalproxy'
  path: '/var/log/rsyslog/nginx.log'   # readable log file from netdata
```
This is how nginx has logging configured:
```
    log_format combined '[$time_local] $request_time $server_name $remote_addr '
                         '$status $body_bytes_sent "$request" '
                         '"$http_referer" "$http_user_agent"';
```

Furthermore rsyslog add something in the beginning of the line. The result is this:
```
<190>Feb 15 09:31:24 name-of-proxy.fqdn.tld nginx: [15/Feb/2017:09:31:24 +0100] 57.445 domain.accessed.fqdn.tld 192.168.10.1 200 148 "POST /http-bind/ HTTP/1.1" "-" "Pidgin 2.10.6 (libpurple 2.10.6)"
<190>Feb 15 09:31:24 name-of-proxy.fqdn.tld nginx: [15/Feb/2017:09:31:24 +0100] 0.020 domain.accessed.fqdn.tld 192.168.10.1 200 280 "POST /http-bind/ HTTP/1.1" "-" "Pidgin 2.10.12 (libpurple 2.10.12)"
<190>Feb 15 09:31:24 name-of-proxy.fqdn.tld nginx: [15/Feb/2017:09:31:24 +0100] 0.019 domain.accessed.fqdn.tld 192.168.10.1 200 284 "POST /http-bind/ HTTP/1.1" "-" "Pidgin 2.10.12 (libpurple 2.10.12)"
```

If the error we're experiencing is related to our log format, would it be possible to have a custom log format in the web_log plugin?

**Comment by l2isbad** [comment]
@adude00 
https://github.com/firehol/netdata/pull/1788

But yes, your log format is not supported. Can you change the format to one that is supported? 

> If the error we're experiencing is related to our log format, would it be possible to have a custom log format in the web_log plugin?

Well..
For custom log format you need to set your own parameters

- regex

- plugin expect from regex result

  * basic values: address method url code bytes_sent (all charts except timings and received dimension of bandwidth chart)
  * extended: address method url code bytes_sent resp_length resp_time (all charts)

so you need to specify values order in your regex

- time (request_time) should be passed in microseconds to netdata so you need to specify a multiplier (1 000 000 in case of nginx)

All this looks too complicated and can be broken after adding any new features to the plugin in near future.

**Comment by adude00** [comment]
> your log format is not supported. Can you change the format to one that is supported?

We can, but it requires changing all of our production proxies log format and our log aggregator rsyslog format. Those logs are already parsed by grok in an ELK stack, so it's a bit of work to redo everything. We could add a new stream of log in a different format to avoid rewriting all the grok filters, but I need to asses the performance impact of a double log stream.

Obviously it would be nicer if we could just "drop" netdata in our environment, but I understand that changing the log parser takes even more work. Maybe take this into consideration as a feature request for the future?

**Comment by l2isbad** [comment]
Personally i like the "custom_log format" idea.

**Comment by ktsaou** [comment]
I agree. The `custom_log_format` you propose @l2isbad is our solution. I understand it will complicate things, but this was expected... a lot of people may have adapted the format to their needs and enforcing our own will just limit netdata adoption.

**Comment by l2isbad** [comment]
Got it!
To get rid of 'order' stuff i will use `groupdict` regex method.

```python
re.search(r'(?P<resp_time>[\d.]+) [a-z.]+ (?P<address>[\d.]+) (?P<code>\d+) (?P<bytes_sent>\d+) "(?P<method>[A-Z]+) (?P<url>.*?)" ', l).groupdict()

{'address': '192.168.10.1',
 'bytes_sent': '284',
 'code': '200',
 'method': 'POST',
 'resp_time': '0.019',
 'url': '/http-bind/ HTTP/1.1'}
```

```yaml
custom_log_format:
     regex: '(?P<resp_time>[\d.]+) [a-z.]+ (?P<address>[\d.]+) (?P<code>\d+) (?P<bytes_sent>\d+) "(?P<method>[A-Z]+) (?P<url>.*?)" '
     time_multiplier: 1000000
```

**Comment by ktsaou** [comment]
nice!
Is this slower? I mean, can it be compiled?

**Comment by l2isbad** [comment]
> can it be compiled?

yes.

**Comment by l2isbad** [comment]
Yo @adude00 
https://github.com/firehol/netdata/pull/1793

Please test it.

You need to add to the configuration file (to the job config)

```yaml
custom_log_format:
     regex_pattern: '(?P<resp_time>[\d.]+) [a-z.]+ (?P<address>[\d.]+) (?P<code>\d+) (?P<bytes_sent>\d+) "(?P<method>[A-Z]+) (?P<url>.*?)" '
```

Not sure about **[a-z.]+** part. This pattern must match **domain.accessed.fqdn.tld** thing in your logs.

**Comment by ktsaou** [comment]
merged it

**Comment by adude00** [comment]
It works! There was a small issue in the regexp ( the character `"` was not escaped) but it works!

Thanks!

Here are some screenshots: [1](https://i.imgur.com/hLOKyqC.png), [2](https://i.imgur.com/ufsmecU.png), [3](https://i.imgur.com/aPGCEIS.png).

I also tried the categories and they work. Do I understand correctly that categories only filter the **URL** part and not the address, right?

If yes, I might suggest to evaluate the possibility to for address as well. For people using it to parse reverse proxies log it would be a nice feature to be able to split traffic depending on the website visited (say that on the same reverse proxy there are multiple websites).

**Comment by l2isbad** [comment]
@adude00 
Hm, `"` is not a metacharacter why do we need to escape it?

> Do I understand correctly that categories only filter the URL 

It's requests per url. Url is (?P<url>...).

**Comment by l2isbad** [comment]
> If yes, I might suggest to evaluate the possibility to filter for address as well

Well, Can you describe this in more detail. Charts/dimensions.

**Comment by adude00** [comment]
>  Hm, `"` is not a metacharacter why do we need to escape it?

Sorry, my bad. Just tried it now without the escape and it worked. Probably it was a typo somewhere in the conf.

**Comment by l2isbad** [comment]
I see "unmatched" on your screenshot. `pattern` fails sometimes. Better to find these lines. "unmatched" is bad 😄

**Comment by adude00** [comment]
> Well, Can you describe this in more detail. Charts/dimensions.

I see that you filter by URL, which is nice if you are using netdata on a single web server which exposes a single app. You [filter by /api1 and /api2](https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file#url-patterns) and it shows which function is used the most. On the other hand, If you, like me, wish to install it on a reverse proxy that serves multiple websites, it would be nice to have a graph showing which websites are accessed instead. 

So... exactly the same filter as _categories_ does for _url_, but for address instead. Then I can have a nice graph with the most visited websites.

By the way, thanks :)

**Comment by l2isbad** [comment]
Post here some logs and mark `address` part please.

**Comment by adude00** [comment]
I'm not sure how to mark it. I put the address between `**`

```
<190>Feb 17 07:56:27 reverseproxy2.domain.tld nginx: [17/Feb/2017:07:56:27 +0100] 0.246 **cloud.domain.tld** 192.168.15.1 207 385 "PROPFIND /remote.php/webdav/ HTTP/1.1" "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<190>Feb 17 07:56:34 reverseproxy2.domain.tld nginx: [17/Feb/2017:07:56:34 +0100] 0.000 **www.domain2.net** 93.62.180.50 301 185 "GET / HTTP/1.1" "-" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"
<190>Feb 17 13:51:36 reverseproxy1.domain.tld nginx: [17/Feb/2017:13:51:36 +0100] 2.004 **customer.domain.tld** 37.186.133.42 200 416 "POST /poller/receive HTTP/1.1" "https://customer.domain.tld/urlualblabla" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
<190>Feb 17 03:42:00 reverseproxy2.domain.tld nginx: [17/Feb/2017:03:42:00 +0100] 0.057 **something.domain3.tld** 93.62.180.50 200 33517 "GET / HTTP/1.1" "-" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"
```

Just to be clear, there are not `**` in the logs. It's just to mark the address.

**Comment by l2isbad** [comment]
Oh, it's $server_name.
How many different addresses do you have? It could be a huge chart (a lot of  dimensions).

**Comment by adude00** [comment]
In total, hundreds. But I was thinking of manually choosing the most used ones the others can go into the "others" category. If it's possible to have the field auto-populated with the 10-20 most used $server_name it would be great, but I'd be ok also with having to put into the conf the most used ones by hand.

**Comment by l2isbad** [comment]
@adude00 
What is `auto-populated` + `most used `. How is this supposed to work? I'm not sure this can be implemented. @ktsaou Any thoughts?

> k also with having to put into the conf the most used ones by hand. + others

easy

**Comment by l2isbad** [comment]
And @adude00 i think you need to open another issue. We are done here 😄

> web_log_nginx_access decode() takes no keyword arguments

**Comment by adude00** [comment]
I agree, it was another request for another feature.

I am closing this issue.
