### ISSUE TITLE
python 2.6: freeradius - invalid syntax

### ISSUE THREAD

**Issue by Maheine** [firehol/netdata#1800]
I have an issue starting freeradius.chart.py with rhel6 / python 2.6.6:

/var/log/netdata/error.log
```
2017-02-16 14:31:44: python.d ERROR: Problem loading freeradius invalid syntax (freeradius.chart.py, line 75)
```

[root@server]# python freeradius.chart.py:
```
  File "freeradius.chart.py", line 75
    self.definitions = {k:v for k, v in CHARTS.items() if k in self.order}
                              ^
SyntaxError: invalid syntax
```

**Comment by l2isbad** [comment]
Yeah. Python 2.6. Dict comprehensions issue :anguished:
To be honest it not only in freeradius

**Comment by l2isbad** [comment]
Yo @Maheine 
Can you change this line
https://github.com/firehol/netdata/blob/master/python.d/freeradius.chart.py#L75

to

```python
self.definitions = dict([elem for elem in CHARTS.items() if elem[0] in self.order])
```

And restart the plugin?

**Comment by l2isbad** [comment]
fixed in https://github.com/firehol/netdata/pull/1801

**Comment by ktsaou** [comment]
merged

**Comment by Maheine** [comment]
Thank you
