### ISSUE TITLE
python 2.6: freeradius - zero length field name

### ISSUE THREAD

**Issue by Maheine** [firehol/netdata#1802]
And I found another problem with Python 2.6:
2017-02-16 17:24:10: python.d ERROR: freeradius_local zero length field name in format
2017-02-16 17:24:10: python.d ERROR: DISABLED: freeradius/local

I changed the host in freeradius.conf from localhost to an IP address.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1803

`Request returned no data. Is server alive? Used options: host {0}, port {1}, secret {2}'.format(self.host, self.port, self.secret`

>  from localhost to an IP address

If it's not 127.0.0.1 you need to change `listen` `ipaddr` conf in `freeradius/sites-enabled/status` (default 127.0.0.1)

**Comment by ktsaou** [comment]
merged
