### ISSUE TITLE
Fail2ban plugin with modular jail configs in jail.d directory

### ISSUE THREAD

**Issue by l00v3** [firehol/netdata#1808]
Hello!
First let me say - very good monitoring software!

I'm trying to setup fail2ban plugin but I have a problem. I have jails separated modularly into jail.d directory. Fail2ban supports this officially, but NetData is not reading this directory, only jail.conf.
It would be very good if NetData supported modular jail.d directory, because it's easier to maintain. Does anybody have any thoughts on this?
Thank you very much!
Tom

**Comment by l2isbad** [comment]
Yo @l00v3 

Can you check in python interpreter this

```python
l = list()
import re
for conf in glob('/etc/fail2ban/jail.d/*'):              
    with open(conf) as conf:
        enabled = re.findall(r'([A-Za-z-]+\]) enabled = (true)', ' '.join(conf.read().split()))
        if enabled:
            l.append(enabled)
print(l)
            
[[('ssh]', 'true'), ('dropbear]', 'true')], [('ssh]', 'true'), ('dropbear]', 'true'), ('xinetd-fail]', 'true')]
```

Does this work and all your enabled jail in list?

**Comment by l00v3** [comment]
Hello @l2isbad, thank you for your quick answer :)
Tried and in one situation, all are listed:
`[[('sshd]', 'true')], [('sshd-ddos]', 'true')], [('sshd]', 'true')], [('nginx-http-auth]', 'true')], [('postfix-sasl]', 'true')]]`

But when there is commented lines between [name] and enabled = true, it will not list it, like this one:

```
[haproxy-http-auth]
#...
############
# NOTE
#
#...
enabled = true
filter  = haproxy-http-auth
...
```
If i put "enabled = true" right after [name], then it is listed.
Is it possible to search the whole file for "enabled = true", or should we have to put it second to [name]?

Thank you very much!

**Comment by l2isbad** [comment]
@l00v3 it's super easy if user defined jails is always in lower case. I see [DEFAULT] and [SECTION_NAME] in jail.local..

**Comment by l2isbad** [comment]
@l00v3 
https://github.com/firehol/netdata/pull/1810

You need to add `conf_dir` to the job configuration. 

```yaml
local:
 log_path: '/var/log/fail2ban.log'
 conf_path: '/etc/fail2ban/jail.local'
 conf_dir: 'path/to/jail.d/'
```

**Comment by iredmail** [comment]
Confirmed, it works as expected. Thank you, @l2isbad

**Comment by ktsaou** [comment]
Cleaning up.
