### ISSUE TITLE
centos 6 make install Permission denied

### ISSUE THREAD

**Issue by evely211** [firehol/netdata#181]
hi
When I use the default path when installation
error:

when i use ./netdata-installer.sh --install /opt successfuly!!

My version of the system
Linux xny 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Installing netdata ...
:-----------------------------------------------------------------------------
Running command:

make install 

Making install in charts.d
make[1]: Entering directory `/root/netdata/charts.d'
make[2]: Entering directory `/root/netdata/charts.d'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/libexec/netdata/charts.d" || /bin/mkdir -p "/usr/libexec/netdata/charts.d"
 /usr/bin/install -c -m 644 README.md '/usr/libexec/netdata/charts.d'
/usr/bin/install: cannot change permissions of `/usr/libexec/netdata/charts.d/README.md': Permission denied
make[2]: *** [install-dist_chartsDATA] Error 1
make[2]: Leaving directory `/root/netdata/charts.d'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/root/netdata/charts.d'
make: *** [install-recursive] Error 1

**Comment by ktsaou** [comment]
I think the error is caused by SELinux, but I am not an expert in this area.

**Comment by ktsaou** [comment]
have you solved it?
May we close this issue?

**Comment by evely211** [comment]
Sorry, just to see, it has been resolved,
Did not open SELinux installed on another VMware is no problem
