### ISSUE TITLE
[netdata.spec] Only set "Recommends:" tag for RPMs >= 4.12.0

### ISSUE THREAD

**Issue by Saruspete** [firehol/netdata#1812]
Hello,

It seems commit 7ffe27a8236171c8fe49d58cae4bce00fa9d1dc1 broke RHEL/CentOS specfile. 
It added "Recommends:" tag on the netdata.spec.in template, without check on the RPM version. 

The recommends tag was added on RPM 4.12.0 (http://rpm.org/wiki/Releases/4.12.0) (currently only used by Fedora >= 24 https://fedoraproject.org/wiki/Packaging:WeakDependencies) and is not backward compatible. 
So it should be only added if the output of "rpm --version" or "rpmbuild --version" is >= 4.12.0

Sample output of "rpmbuild --version" (same for rpm) on : 
RHEL 6.8 : `RPM version 4.8.0`
RHEL 7.3 : `RPM version 4.11.3`
Fedora 23 : `RPM version 4.13.0-rc1`

Unfortunalty, I don't know autoconf to do the proper code and submit a PR, but will definitely provide any samples to help. 

Best regards,
Adrien.

**Comment by ktsaou** [comment]
> Unfortunalty, I don't know autoconf to do the proper code and submit a PR, but will definitely provide any samples to help.

Unfortunately neither do I.

@philwhineray @breed808 could you please help?

**Comment by ktsaou** [comment]
I guess you mean some like this: https://github.com/firehol/netdata/blob/master/netdata.spec.in#L24-L27

@Saruspete can you check?

**Comment by breed808** [comment]
It's easy enough to wrap it with:
```
%if 0%{?fedora}
Recommends: curl
...
%else
...
%endif
```
However @alonbl has previously mentioned that we should be keeping `%if`/`%else` statements to a minimum, using `%define` entries at the top of the file instead. I'm not sure how to create a multiline `%define` entry that we could use in this situation.

**Comment by alonbl** [comment]
Hi,
Please see  #1819, I've tried to apply the logic of distro specific outside of package body to reduce conflicts when changed and while doing so fix all sort of stuff.
Please review carefully.
Thanks!

**Comment by ktsaou** [comment]
I think this is fixed ( thank you @alonbl ), so we can close it.
If you believe there is something missing, just post.
