### ISSUE TITLE
rabbit mq monitoring

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1813]
It would be nice if we could collect metrics for rabbit mq.

**Comment by ktsaou** [comment]
```sh
curl -s -u user:pass 'http://172.17.0.2:15672/api/aliveness-test/%2F' | jq
```

```json
{
  "status": "ok"
}
```

---
```sh
curl -s -u user:pass 'http://172.17.0.2:15672/api/exchanges' | jq
```

```json
[
  {
    "message_stats": {
      "publish": 0,
      "publish_details": {
        "rate": 0
      },
      "publish_in": 2,
      "publish_in_details": {
        "rate": 0
      },
      "publish_out": 2,
      "publish_out_details": {
        "rate": 0
      },
      "ack": 0,
      "ack_details": {
        "rate": 0
      },
      "deliver_get": 0,
      "deliver_get_details": {
        "rate": 0
      },
      "confirm": 0,
      "confirm_details": {
        "rate": 0
      },
      "return_unroutable": 0,
      "return_unroutable_details": {
        "rate": 0
      },
      "redeliver": 0,
      "redeliver_details": {
        "rate": 0
      }
    },
    "name": "",
    "vhost": "/",
    "type": "direct",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  },
  {
    "name": "amq.direct",
    "vhost": "/",
    "type": "direct",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  },
  {
    "name": "amq.fanout",
    "vhost": "/",
    "type": "fanout",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  },
  {
    "name": "amq.headers",
    "vhost": "/",
    "type": "headers",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  },
  {
    "name": "amq.match",
    "vhost": "/",
    "type": "headers",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  },
  {
    "name": "amq.rabbitmq.log",
    "vhost": "/",
    "type": "topic",
    "durable": true,
    "auto_delete": false,
    "internal": true,
    "arguments": {}
  },
  {
    "name": "amq.rabbitmq.trace",
    "vhost": "/",
    "type": "topic",
    "durable": true,
    "auto_delete": false,
    "internal": true,
    "arguments": {}
  },
  {
    "name": "amq.topic",
    "vhost": "/",
    "type": "topic",
    "durable": true,
    "auto_delete": false,
    "internal": false,
    "arguments": {}
  }
]
```

---

```sh
curl -s -u user:pass 'http://172.17.0.2:15672/api/queues' | jq
```

```json
[
  {
    "memory": 9096,
    "message_stats": {
      "deliver": 0,
      "deliver_details": {
        "rate": 0
      },
      "deliver_no_ack": 0,
      "deliver_no_ack_details": {
        "rate": 0
      },
      "get": 0,
      "get_details": {
        "rate": 0
      },
      "get_no_ack": 2,
      "get_no_ack_details": {
        "rate": 0
      },
      "publish": 2,
      "publish_details": {
        "rate": 0
      },
      "publish_in": 0,
      "publish_in_details": {
        "rate": 0
      },
      "publish_out": 0,
      "publish_out_details": {
        "rate": 0
      },
      "ack": 0,
      "ack_details": {
        "rate": 0
      },
      "deliver_get": 2,
      "deliver_get_details": {
        "rate": 0
      },
      "confirm": 0,
      "confirm_details": {
        "rate": 0
      },
      "return_unroutable": 0,
      "return_unroutable_details": {
        "rate": 0
      },
      "redeliver": 0,
      "redeliver_details": {
        "rate": 0
      }
    },
    "reductions": 3599,
    "reductions_details": {
      "rate": 0
    },
    "messages": 0,
    "messages_details": {
      "rate": 0
    },
    "messages_ready": 0,
    "messages_ready_details": {
      "rate": 0
    },
    "messages_unacknowledged": 0,
    "messages_unacknowledged_details": {
      "rate": 0
    },
    "idle_since": "2017-02-17 22:56:26",
    "consumer_utilisation": null,
    "policy": null,
    "exclusive_consumer_tag": null,
    "consumers": 0,
    "recoverable_slaves": null,
    "state": "running",
    "garbage_collection": {
      "max_heap_size": 0,
      "min_bin_vheap_size": 46422,
      "min_heap_size": 233,
      "fullsweep_after": 65535,
      "minor_gcs": 8
    },
    "messages_ram": 0,
    "messages_ready_ram": 0,
    "messages_unacknowledged_ram": 0,
    "messages_persistent": 0,
    "message_bytes": 0,
    "message_bytes_ready": 0,
    "message_bytes_unacknowledged": 0,
    "message_bytes_ram": 0,
    "message_bytes_persistent": 0,
    "head_message_timestamp": null,
    "disk_reads": 0,
    "disk_writes": 0,
    "backing_queue_status": {
      "mode": "default",
      "q1": 0,
      "q2": 0,
      "delta": [
        "delta",
        "undefined",
        0,
        "undefined"
      ],
      "q3": 0,
      "q4": 0,
      "len": 0,
      "target_ram_count": "infinity",
      "next_seq_id": 2,
      "avg_ingress_rate": 0.12943762153322996,
      "avg_egress_rate": 0.12943762153322996,
      "avg_ack_ingress_rate": 0,
      "avg_ack_egress_rate": 0
    },
    "node": "rabbit@my-rabbit",
    "arguments": {},
    "exclusive": false,
    "auto_delete": false,
    "durable": false,
    "vhost": "/",
    "name": "aliveness-test"
  },
  {
    "memory": 14040,
    "reductions": 2107,
    "reductions_details": {
      "rate": 0
    },
    "messages": 0,
    "messages_details": {
      "rate": 0
    },
    "messages_ready": 0,
    "messages_ready_details": {
      "rate": 0
    },
    "messages_unacknowledged": 0,
    "messages_unacknowledged_details": {
      "rate": 0
    },
    "idle_since": "2017-02-17 22:46:56",
    "consumer_utilisation": null,
    "policy": null,
    "exclusive_consumer_tag": null,
    "consumers": 0,
    "recoverable_slaves": null,
    "state": "running",
    "garbage_collection": {
      "max_heap_size": 0,
      "min_bin_vheap_size": 46422,
      "min_heap_size": 233,
      "fullsweep_after": 65535,
      "minor_gcs": 3
    },
    "messages_ram": 0,
    "messages_ready_ram": 0,
    "messages_unacknowledged_ram": 0,
    "messages_persistent": 0,
    "message_bytes": 0,
    "message_bytes_ready": 0,
    "message_bytes_unacknowledged": 0,
    "message_bytes_ram": 0,
    "message_bytes_persistent": 0,
    "head_message_timestamp": null,
    "disk_reads": 0,
    "disk_writes": 0,
    "backing_queue_status": {
      "mode": "default",
      "q1": 0,
      "q2": 0,
      "delta": [
        "delta",
        "undefined",
        0,
        "undefined"
      ],
      "q3": 0,
      "q4": 0,
      "len": 0,
      "target_ram_count": "infinity",
      "next_seq_id": 0,
      "avg_ingress_rate": 0,
      "avg_egress_rate": 0,
      "avg_ack_ingress_rate": 0,
      "avg_ack_egress_rate": 0
    },
    "node": "rabbit@my-rabbit",
    "arguments": {},
    "exclusive": false,
    "auto_delete": true,
    "durable": true,
    "vhost": "/",
    "name": "test1"
  },
  {
    "memory": 9080,
    "reductions": 2033,
    "reductions_details": {
      "rate": 0
    },
    "messages": 0,
    "messages_details": {
      "rate": 0
    },
    "messages_ready": 0,
    "messages_ready_details": {
      "rate": 0
    },
    "messages_unacknowledged": 0,
    "messages_unacknowledged_details": {
      "rate": 0
    },
    "idle_since": "2017-02-17 22:48:14",
    "consumer_utilisation": null,
    "policy": null,
    "exclusive_consumer_tag": null,
    "consumers": 0,
    "recoverable_slaves": null,
    "state": "running",
    "garbage_collection": {
      "max_heap_size": 0,
      "min_bin_vheap_size": 46422,
      "min_heap_size": 233,
      "fullsweep_after": 65535,
      "minor_gcs": 4
    },
    "messages_ram": 0,
    "messages_ready_ram": 0,
    "messages_unacknowledged_ram": 0,
    "messages_persistent": 0,
    "message_bytes": 0,
    "message_bytes_ready": 0,
    "message_bytes_unacknowledged": 0,
    "message_bytes_ram": 0,
    "message_bytes_persistent": 0,
    "head_message_timestamp": null,
    "disk_reads": 0,
    "disk_writes": 0,
    "backing_queue_status": {
      "mode": "default",
      "q1": 0,
      "q2": 0,
      "delta": [
        "delta",
        "undefined",
        0,
        "undefined"
      ],
      "q3": 0,
      "q4": 0,
      "len": 0,
      "target_ram_count": "infinity",
      "next_seq_id": 0,
      "avg_ingress_rate": 0,
      "avg_egress_rate": 0,
      "avg_ack_ingress_rate": 0,
      "avg_ack_egress_rate": 0
    },
    "node": "rabbit@my-rabbit",
    "arguments": {},
    "exclusive": false,
    "auto_delete": false,
    "durable": false,
    "vhost": "/",
    "name": "test2"
  }
]
```

```sh
curl -s -u user:pass 'http://172.17.0.2:15672/api/nodes' | jq
```

```json
[
  {
    "cluster_links": [],
    "mem_used": 64813624,
    "mem_used_details": {
      "rate": 22844.8
    },
    "fd_used": 24,
    "fd_used_details": {
      "rate": 0
    },
    "sockets_used": 0,
    "sockets_used_details": {
      "rate": 0
    },
    "proc_used": 235,
    "proc_used_details": {
      "rate": 0
    },
    "disk_free": 3675176960,
    "disk_free_details": {
      "rate": -4915.2
    },
    "io_read_count": 1,
    "io_read_count_details": {
      "rate": 0
    },
    "io_read_bytes": 1,
    "io_read_bytes_details": {
      "rate": 0
    },
    "io_read_avg_time": 0.293,
    "io_read_avg_time_details": {
      "rate": 0
    },
    "io_write_count": 0,
    "io_write_count_details": {
      "rate": 0
    },
    "io_write_bytes": 0,
    "io_write_bytes_details": {
      "rate": 0
    },
    "io_write_avg_time": 0,
    "io_write_avg_time_details": {
      "rate": 0
    },
    "io_sync_count": 0,
    "io_sync_count_details": {
      "rate": 0
    },
    "io_sync_avg_time": 0,
    "io_sync_avg_time_details": {
      "rate": 0
    },
    "io_seek_count": 0,
    "io_seek_count_details": {
      "rate": 0
    },
    "io_seek_avg_time": 0,
    "io_seek_avg_time_details": {
      "rate": 0
    },
    "io_reopen_count": 0,
    "io_reopen_count_details": {
      "rate": 0
    },
    "mnesia_ram_tx_count": 39,
    "mnesia_ram_tx_count_details": {
      "rate": 0
    },
    "mnesia_disk_tx_count": 14,
    "mnesia_disk_tx_count_details": {
      "rate": 0
    },
    "msg_store_read_count": 0,
    "msg_store_read_count_details": {
      "rate": 0
    },
    "msg_store_write_count": 0,
    "msg_store_write_count_details": {
      "rate": 0
    },
    "queue_index_journal_write_count": 0,
    "queue_index_journal_write_count_details": {
      "rate": 0
    },
    "queue_index_write_count": 0,
    "queue_index_write_count_details": {
      "rate": 0
    },
    "queue_index_read_count": 0,
    "queue_index_read_count_details": {
      "rate": 0
    },
    "gc_num": 34929,
    "gc_num_details": {
      "rate": 21.2
    },
    "gc_bytes_reclaimed": 595274792,
    "gc_bytes_reclaimed_details": {
      "rate": 316852.8
    },
    "context_switches": 175845,
    "context_switches_details": {
      "rate": 61.6
    },
    "io_file_handle_open_attempt_count": 10,
    "io_file_handle_open_attempt_count_details": {
      "rate": 0
    },
    "io_file_handle_open_attempt_avg_time": 0.0536,
    "io_file_handle_open_attempt_avg_time_details": {
      "rate": 0
    },
    "partitions": [],
    "os_pid": "254",
    "fd_total": 1048576,
    "sockets_total": 943626,
    "mem_limit": 3350223257,
    "mem_alarm": false,
    "disk_free_limit": 50000000,
    "disk_free_alarm": false,
    "proc_total": 1048576,
    "rates_mode": "basic",
    "uptime": 1623270,
    "run_queue": 0,
    "processors": 4,
    "exchange_types": [
      {
        "name": "topic",
        "description": "AMQP topic exchange, as per the AMQP specification",
        "enabled": true
      },
      {
        "name": "direct",
        "description": "AMQP direct exchange, as per the AMQP specification",
        "enabled": true
      },
      {
        "name": "headers",
        "description": "AMQP headers exchange, as per the AMQP specification",
        "enabled": true
      },
      {
        "name": "fanout",
        "description": "AMQP fanout exchange, as per the AMQP specification",
        "enabled": true
      }
    ],
    "auth_mechanisms": [
      {
        "name": "AMQPLAIN",
        "description": "QPid AMQPLAIN mechanism",
        "enabled": true
      },
      {
        "name": "RABBIT-CR-DEMO",
        "description": "RabbitMQ Demo challenge-response authentication mechanism",
        "enabled": false
      },
      {
        "name": "PLAIN",
        "description": "SASL PLAIN authentication mechanism",
        "enabled": true
      }
    ],
    "applications": [
      {
        "name": "amqp_client",
        "description": "RabbitMQ AMQP Client",
        "version": "3.6.6"
      },
      {
        "name": "asn1",
        "description": "The Erlang ASN1 compiler version 4.0.4",
        "version": "4.0.4"
      },
      {
        "name": "compiler",
        "description": "ERTS  CXC 138 10",
        "version": "7.0.3"
      },
      {
        "name": "crypto",
        "description": "CRYPTO",
        "version": "3.7.2"
      },
      {
        "name": "inets",
        "description": "INETS  CXC 138 49",
        "version": "6.3.4"
      },
      {
        "name": "kernel",
        "description": "ERTS  CXC 138 10",
        "version": "5.1.1"
      },
      {
        "name": "mnesia",
        "description": "MNESIA  CXC 138 12",
        "version": "4.14.2"
      },
      {
        "name": "mochiweb",
        "description": "MochiMedia Web Server",
        "version": "2.13.1"
      },
      {
        "name": "os_mon",
        "description": "CPO  CXC 138 46",
        "version": "2.4.1"
      },
      {
        "name": "public_key",
        "description": "Public key infrastructure",
        "version": "1.3"
      },
      {
        "name": "rabbit",
        "description": "RabbitMQ",
        "version": "3.6.6"
      },
      {
        "name": "rabbit_common",
        "description": "",
        "version": "3.6.6"
      },
      {
        "name": "rabbitmq_management",
        "description": "RabbitMQ Management Console",
        "version": "3.6.6"
      },
      {
        "name": "rabbitmq_management_agent",
        "description": "RabbitMQ Management Agent",
        "version": "3.6.6"
      },
      {
        "name": "rabbitmq_web_dispatch",
        "description": "RabbitMQ Web Dispatcher",
        "version": "3.6.6"
      },
      {
        "name": "ranch",
        "description": "Socket acceptor pool for TCP protocols.",
        "version": "1.2.1"
      },
      {
        "name": "sasl",
        "description": "SASL  CXC 138 11",
        "version": "3.0.2"
      },
      {
        "name": "ssl",
        "description": "Erlang/OTP SSL application",
        "version": "8.1"
      },
      {
        "name": "stdlib",
        "description": "ERTS  CXC 138 10",
        "version": "3.2"
      },
      {
        "name": "syntax_tools",
        "description": "Syntax tools",
        "version": "2.1.1"
      },
      {
        "name": "webmachine",
        "description": "webmachine",
        "version": "1.10.3"
      },
      {
        "name": "xmerl",
        "description": "XML parser",
        "version": "1.3.12"
      }
    ],
    "contexts": [
      {
        "description": "RabbitMQ Management",
        "path": "/",
        "port": "15672",
        "ssl": "false"
      }
    ],
    "log_file": "tty",
    "sasl_log_file": "tty",
    "db_dir": "/var/lib/rabbitmq/mnesia/rabbit@my-rabbit",
    "config_files": [
      "/etc/rabbitmq/rabbitmq.config"
    ],
    "net_ticktime": 60,
    "enabled_plugins": [
      "rabbitmq_management"
    ],
    "name": "rabbit@my-rabbit",
    "type": "disc",
    "running": true
  }
]
```

more to come

**Comment by brizzbane** [comment]
Just started using netdata.  Googled 'rabbitmq' + 'netdata'.  Surprised this isn't already implemented, and that this issue is only 15 hours old :p.

I would also appreciate RabbitMQ monitoring.

**Comment by ktsaou** [comment]
rabbitmq manager presents this:

![image](https://cloud.githubusercontent.com/assets/2662304/23091304/b8356bf8-f5bb-11e6-93c7-bc56a96d13b6.png)

Can you help us identify:

1. what charts should we show?
2. where do we find the information for each metric on the charts?

There is nagios plugin that could help us identify this information: https://github.com/nagios-plugins-rabbitmq/nagios-plugins-rabbitmq

**Comment by julianseeger** [comment]
The Management Plugin shows a lot of useful graphs, but for the most important (imho), I would like to suggest a baseline for further discussion:

### Node
* I/O average time per operation
  * **show**: read/write/seek/sync/file handle open attempt (like the management plugin shows)
  * **alarms**: like above 50ms? for any of them (any value above 50ms probably means the disk is under too much pressure or rabbitMQ is swapping)
  * **where to find**: everything with "avg_time" as suffix
![image](https://cloud.githubusercontent.com/assets/3258762/23336416/fd2dca38-fbcf-11e6-92d7-ed6f875cea74.png)
(the image shows a node that needed to swap a non-lazy queue before and now needs to read that swapped information from time to time)

* Cluster Links
  * **show**: outgoing traffic to each node in the cluster (stacked)
  * **alarms**: none, just info
  * **where to find**: `/api/queues` in the `cluster_links` entry (empty in your example)
```JSON
{
    "cluster_links": [
        {
            "name": "***",
            "peer_addr": "***.***.***.***",
            "peer_port": *****,
            "sock_addr": "***.***.***.***",
            "sock_port": *****,
            "stats": {
                "send_bytes": 10084625,
                "send_bytes_details": {
                    "avg": 10051166.438016528,
                    "avg_rate": 108.27,
                    "rate": 106.0,
                    "samples": [
                        {
                            "sample": 10084625,
                            "timestamp": 1488075000000
                        }, ...
                    ],
                }
            }
        }
    ]
}
```
![image](https://cloud.githubusercontent.com/assets/3258762/23336437/d4ffad1e-fbd0-11e6-9a17-642104b0b0b7.png)


### Queues
* Queued messages
  * **show**: total messages per queue as a stacked chart (one chart with all queues)
  * **alarms**: 
    * increasing backlog: when totals are constantly increasing for .. 1min? (each queue)
    * total backlog: default: none, user-defined: number of total messages in one-queue or overall
  * **where to find**: I think it's the `messages` value on the `/api/vhosts` endpoint

* Message Rates
  * **show**: message rates overall (publish, confirm, ... like the management plugin shows in overview)
  * **alarms** (per queue): 
    * 1.) if unacknowledged messages are piling up (deliver > ack) for *too long* (1min?)
    * 2.) if *too many* messages are redelivered (>5%?)
  * **where to find**: should be in the queues endpoint

* Message Space *(maybe 2 charts: persistent and in-memory)*
  * **show**: size of messages as a stacked chart (one chart with all queues)
  * **alarms**: none. should be covered by disk alerts, total message alerts and the rabbitmq disk operation times
  * **where to find**: `message_bytes` in the `/api/queues` endpoint (or `message_bytes_ram` and `message_bytes_persistent` if split to two charts) 

* **Reductions** can probably indicate when bad things are happening, but I'm lacking knowledge there. Maybe a good point for some nifty explanation text 
![image](https://cloud.githubusercontent.com/assets/3258762/23336522/f114b966-fbd2-11e6-8ca2-ab22f93a3747.png)

**Comment by l2isbad** [comment]
The main problem is always what metrics to collect and how to group them into charts. If you guys know all metrics we need (@julianseeger gj man!) it's very easy to create the plugin since all returned data in json.

That is how it works in elasticsearch plugin or mongodb:

1. [Stats list](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L23-L59)

format is
**[(x, y, z), ...]**

**x** - path to value we are need in json data dictionary

ex.
`indices.search.fetch_current` means `data['indices']['search']['fetch_current']`

**y**  - dimenstion id. If None dimension id will be last part from `x`, if `value` dimension id will be `value`.

**z** - function. If we need any calculation/manipulation with value before pass it to netdata. If calculation is not needed function is None.

2. [Charts](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L96-L288)

3. [URLs](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L318-L320) from where to fetch data.

That is all! All other logic is one [small function](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L467-L480)

And get_data method (parse data from _get_raw_data) will be few strings.

```python
to_netdata = fetch_data_(raw_data=raw_data, metrics_list=STATS_LIST)
return to_netdata
```

So the 99, 9% (no python and even no programming at all!) of the work is to create STATS_LIST and CHARTS which is easy if you know what metrics do we need.

**Comment by ktsaou** [comment]
ok, here is what I think (context / dimensions):

---

## rabbit exchanges

The following come from the `exchanges` call. There should be one such set for each queue.

I suggest to define chart ids like this: `rabbit_JOBNAME_exchange_VHOSTNAME.type`.

All the charts of the same exchange should have the same `family` (` = exchange_VHOSTNAME`) so that they will appear as a submenu, and alarms willing to use cross chart variables will be able to use the ones within the same family.

Also, pay attention to the context (to allow templated alarms).

Only exchanges with `message_stats` should be sent to netdata.

- `rabbit.exchange_messages`
   - `publish`
   - `ack`
   - `deliver_get`
   - `confirm`
   - `return_unroutable` (negative)
   - `redeliver`

- `rabbit.exchange_messages_publish`
   - `in`
   - `out` (negative)

## rabbit queues

The following come from the `queues` call. There should be one such set for each queue.

I suggest to define chart ids like this: `rabbit_JOBNAME_queue_QUEUENAME.type`. All the charts of the same queue should have the same `family` (` = queue_QUEUENAME`) so that they will appear as a submenu, and alarms willing to use cross chart variables will be able to use the ones within the same family.

- `rabbit.queue_state`
  - `running` (should be 1 when `"state": "running"`)
  - `other` (should be 1 when "state" is not "running") - The idea is to add other useful states in the future.

- `rabbit.queue_memory`
   - `used`

- `rabbit.queue_messages_state` (all come from `messages_*`)
   - `ram`
   - `ready`
   - `unacknowledged`
   - `persistent`

- `rabbit.queue_messages_size` (all come from `message_bytes_*`)
   - `all` (this comes from `message_bytes` - is it really all?)
   - `ram`
   - `ready`
   - `unacknowledged`
   - `persistent`

- `rabbit.queue_disk_iops`
   - `reads` (from `disk_reads`)
   - `writes` (from `disk_writes`)

- `rabbit.queue_messages`
   - `all`
   - `ready`
   - `unacknowledged`

- `rabbit.queue_messages_detailed` (all come from `message_stats`, when available - I don't know if this includes master/detail relationships - if it does, we have to break it into multiple charts)
   - `deliver`
   - `deliver_no_ack`
   - `get`
   - `get_no_ack`
   - `publish`
   - `publish_in`
   - `publish_out`
   - `ack`
   - `deliver_get`
   - `confirm`
   - `return_unroutable`
   - `redeliver`

- `rabbit.queue_consumers`
   - `consumers`

- `rabbit.queue_garbage_collector`
   - all the `*_size` metrics

---

## rabbit nodes

Similarly to the queues, one set of charts for each node.

- file descriptors
- socket descriptors
- erlang processes
- total memory
- total disk space used

---

## rabbit overview

Then, from all the above, we will need a few charts to show the global counts:

- `rabbit.aliveness` (from the `aliveness` call)
   - `alive`, with possible values 0, 1

- number of exchanges
- number of queues
- number of consumers
- number of connections
- number of channels

---

I think there is an entity called `channels`. If there is, we would need another set of charts for each of them.

( @l2isbad I have not completed the above - you can start writing something if you like - I need to read myself to understand what else is needed).

**Comment by ktsaou** [comment]
And I forgot `reductions`, mentioned by @julianseeger

**Comment by ktsaou** [comment]
@l2isbad do you need more info for this? Can we start with something simple and build on it?

**Comment by l2isbad** [comment]
Well, the main problem is lack of rabbitmq stats on a simple install. I have to setup a working rabbitmq instance or something.

**Comment by ktsaou** [comment]
I guess docker is your friend...
Up and running with stats in 2 minutes...

**Comment by l2isbad** [comment]
Up and running but not sure about all stats we need - they are not the same then yours after install. Looks like rabbitmq instance should do some work before i can get all the stats. If you have server with working rabbitmq i suggest to allow access to port 15672 from my ip to it.

**Comment by ktsaou** [comment]
You could try this:

```
curl -s -u user:pass 'http://172.17.0.2:15672/api/aliveness-test/%2F' | jq
```

This dispatches a message. I'll try to find an example app we can use to test this.

**Comment by ktsaou** [comment]
@l2isbad I have been trying to find a test app to produce some load on rabbit without success.
But on work I do have a rabbit installation with load. Unfortunatelly, I can't give you access, but I can dump all the calls with data on them.

Will this do to prepare this plugin?

**Comment by l2isbad** [comment]
Maybe next week I will succeed to get access  to working rabbit mq instance. If not, then let's try 

> dump all the calls

**Comment by hijklmno** [comment]
any updates? this would be awesome to have. we have a rabbit cluster, and the rabbit management console has a memory leak that we wish to migrate away from :/

**Comment by l2isbad** [comment]
Well, i have access to the rabbit mq on a zenoss instance.
`api/overview` + `api/nodes` = all stats from the dashboard overview section
`api/queues` and `api/exchanges` returns nothing meaningful  in my case.

`api/connections` ...chart rate?
![screenshot_20170512_104101](https://cloud.githubusercontent.com/assets/22274335/25978793/84a337fe-36ff-11e7-910c-a28eb06252a4.png)

I think we can start from `overview + nodes` and chart all information from the overview section 

- queues messages
- message rates
- global counts
- nodes (file descriptors, socket descriptors, erlang processes, memory, disk space)

**Comment by gerhard** [comment]
This can be closed now, thanks @l2isbad for the contribution 👍
