### ISSUE TITLE
integrate two install scripts further, into oneliner

### ISSUE THREAD

**Issue by Anton-Latukha** [firehol/netdata#1818]
* Looking at documentation
* While knowing internals of Linux
* and I see your scripting skills
* @ktsaou #1169

I see how far you got in this scripts.
I don't see why don't combine preparation script with installation one, in truly oneliner.
They are separated by just `git clone`.

Keys, explanation, can be combined.

```shell
git clone --depth 1 "$url" "$repo_path" # can be done in temp folder even as root or user
# if be dirty, can do right away `chmod -R 0300 "$repo_path"` if we being paranoid, if installer caw work in that
"$repo_path"/netdata-installer.sh
rm -rf "$repo_path" # does user really need a code repository after installation?
```

Thank you.

P.S. - You got a really ultimate product. Just look back several years ago...

**Comment by ktsaou** [comment]
Hi,

thanks! We are working on a static netdata build that will be installed with https://github.com/megastep/makeself Check this: https://github.com/firehol/packages/issues/1

Usually, the right way to do it:

1. Run the kickstart script once
2. `git clone` the source into `/usr/src/netdata.git`
3. install it from there with the installer
4. link `netdata-updater.sh` from the source directory to your `/etc/cron.daily/` to make it update netdata automatically - the installer suggests this when it finishes.

The installer fully supports non-root setups. Check #149 . You will need of course to either `setcap` or setuid to root `apps.plugin`. So, the change you made at the installation wiki page is not exactly accurate. When you run the installer as a normal user is does not allows installing at system paths, but on any other folder it will be installed and run if you do not have root access.

For non-root users though, I suggest to keep the source in `$HOME/src`.

**Comment by Anton-Latukha** [comment]
Jesus, I saw https://github.com/megastep/makeself

Things like that are needed.


P.S.
<sub>\<small talk\>
I am myself thinking how to properly #! cross-platform installation script for Leksah including MSYS2 and Mac OS envs (Leksah is IDE for Haskell written in Haskell). Complexity to install it properly, was his main weaknesses that downed it's usage completely now. So I like to see shell standardization in universal functions/snippets/solutions.</sub>

**Comment by ktsaou** [comment]
Binary packages with `makeself` are here: https://github.com/firehol/binary-packages

Also, your kickstart suggestion is here:

```sh
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by ktsaou** [comment]
This is done. I am closing it.
