### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by UVV-gh** [firehol/netdata#182]
Hi guys,
I've just downloaded the 1.0.0 released package and trying to get it built in yocto linux environment. The problem is there's not COPYING file with GPL license attached, that is required by both, yocto and GPL itself as it's stated in [GPL FAQ](http://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude).
Could you please include this file in release?

Thanks,
Vyacheslav

**Comment by ktsaou** [comment]
So, the COPYING file should be this?

http://www.gnu.org/licenses/gpl.txt

**Comment by UVV-gh** [comment]
Yep, I believe that's the one.

**Comment by UVV-gh** [comment]
Sorry, I accidentally pushed a wrong button.

**Comment by UVV-gh** [comment]
Just a small note (and I don't want to create a pull request). There is a type in configuration parser:
src/appconfig.c:219:                    error("Ignoring line %d ('%s'), it is **outsize** all sections.", line, s);

**Comment by ktsaou** [comment]
> error("Ignoring line %d ('%s'), it is outsize all sections.", line, s);

what is wrong with it?

**Comment by UVV-gh** [comment]
Isn't that supposed to be **outside**?

**Comment by ktsaou** [comment]
yes, of course! I'll fix it. Thanks!

**Comment by ktsaou** [comment]
Done. Thanks for reporting!
