### ISSUE TITLE
Badges with graphs

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#1820]
Hi,

I don't understand from your doc :
https://github.com/firehol/netdata/wiki/Generating-Badges

how we can embed real graphs moving into a website page where there is already some contents, exactly as you show on your demo page 👍 http://my-netdata.io/
see "netdata live demo sites"

**Comment by ktsaou** [comment]
These are badges:

> [![User Base](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=persons&label=user%20base&units=null&value_color=blue&precision=0&v42)](https://registry.my-netdata.io/#netdata_registry) [![Monitored Servers](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=machines&label=servers%20monitored&units=null&value_color=orange&precision=0&v42)](https://registry.my-netdata.io/#netdata_registry) [![Sessions Served](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_sessions&label=sessions%20served&units=null&value_color=yellowgreen&precision=0&v42)](https://registry.my-netdata.io/#netdata_registry)<br/>_(the figures come from **[netdata registry](https://github.com/firehol/netdata/wiki/mynetdata-menu-item)** data, showing only installations that use the public global registry, counting since May 16th 2016)_
>
> [![New Users Today](http://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=persons&after=-86400&options=unaligned&group=incremental-sum&label=new%20users%20today&units=null&value_color=blue&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![New Machines Today](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=machines&group=incremental-sum&after=-86400&options=unaligned&label=servers%20added%20today&units=null&value_color=orange&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![Sessions Today](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_sessions&after=-86400&group=incremental-sum&options=unaligned&label=sessions%20served%20today&units=null&value_color=yellowgreen&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry)<br/>_Check **[[Generating Badges]]** for more information._

They come from netdata and can be embedded like images.

https://my-netdata.io is a custom dashboard. You have it on your netdata too at http://your.netdata.ip:19999/demosites.html.

View its source. The documentation is : https://github.com/firehol/netdata/wiki/Custom-Dashboards

**Comment by yoorshop** [comment]
Ok.

We use htacess protection on our netdata page, first issue, and we can't let it opened.
Second issue, we get error 101 ! can't load local library from our server : ourdomain.com/lib/jqueryfile....

**Comment by yoorshop** [comment]
Now removed htaccess for test purpose, and test is done on http domain

We will have also issue that our site is https 100%

**Comment by yoorshop** [comment]
Our page is now working, but we can't secure anything either with htaccess pasword, or nginx IP restriction (it collected local IP when connecting instead of target IP allowed)... 👍 
Precisely this is causing the issue :
"GET /netdata/api/v1/chart?chart=netdata.server_cpu&_=1487573607550 HTTP/1.1

**Comment by yoorshop** [comment]
you have to load the chart in the target server and somehow serve from there .

This is to be done in the html/ app code - server side it is all set correctly . The target server does load up netdata url as i confirmed from lynx/curl. 

But dynamic end user ip's are blocked by our config and they cannot directly access the netdata url on the server unless we keep it all open.

**Comment by yoorshop** [comment]
I now have a custom dashboard on another website.
I observe that initial netdat stops itself suddenly, and the custom dashboard  still works, crazy !

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
I see there are unanswered questions, but I am not sure if they are still valid.
If you still need help, just post.
