### ISSUE TITLE
python 2.6 - varnish - invalid syntax

### ISSUE THREAD

**Issue by reneski** [firehol/netdata#1824]
error.log message:
<code>python.d ERROR: Problem loading varnish invalid syntax (varnish.chart.py, line 155)</code>

System:
CentOS release 6.8
Python 2.6.6
netdata Version: 1.5.0-321-gb00e654_rolling

python varnish.chart.py
```
  File "varnish.chart.py", line 155
    to_netdata = {k: int(v) for t, k, v in data_all}
                              ^
SyntaxError: invalid syntax
```

**Comment by l2isbad** [comment]
Yo @reneski 

check this fix https://github.com/firehol/netdata/pull/1825
does it work now?

**Comment by reneski** [comment]
yep, now it works.
thanks alot.

**Comment by reneski** [comment]
I just saw that I get the same error for the following 3 charts, should be the same kind of problem:
```
python bind_rndc.chart.py
  File "bind_rndc.chart.py", line 121
    for topic, body in findall(regex, raw_data)})
      ^
SyntaxError: invalid syntax
```
```
python smartd_log.chart.py
  File "smartd_log.chart.py", line 188
    self.previous_data = {k: v for k, v in self.previous_data.items() if basename(disk.name) not in k}
                                 ^
SyntaxError: invalid syntax
```
```
python isc_dhcpd.chart.py
  File "isc_dhcpd.chart.py", line 117
    all_leases = {k[6:len(k)-3]:v[7:len(v)-2] for k, v in raw_leases[0].items()}
                                                ^
SyntaxError: invalid syntax
```

**Comment by l2isbad** [comment]
Yes. I know 😄 @reneski 
I will fix it soon

**Comment by ktsaou** [comment]
merged it

**Comment by wmandra** [comment]
I'm getting this same error on CentOS 6.8 with python 2.7:

python bind_rndc.chart.py
  File "bind_rndc.chart.py", line 121
    for topic, body in findall(regex, raw_data)})
      ^
SyntaxError: invalid syntax

**Comment by l2isbad** [comment]
fixed in https://github.com/firehol/netdata/pull/1872

**Comment by ktsaou** [comment]
Cleaning up. Post if something is missing.
