### ISSUE TITLE
yum wants to update vzkernel during installation

### ISSUE THREAD

**Issue by slrslr** [firehol/netdata#1826]
Hello,
on CentOS release 6.6 (Final) 64bit i tried to install netdata required packages using command mentioned in the README:

> yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel

and it wants to update vzkernel:
https://s20.postimg.org/g09v4gxjh/62684654516141618994848946535.gif

Please can i somehow skip it? I prefer staying at current kernel version and prefer no system restart on this server.

**Comment by ktsaou** [comment]
hm... I don't know. `yum` must somehow support blacklisting versions of packages, but I don't know how. I suggest to search it.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
