### ISSUE TITLE
Netdata doesn't start

### ISSUE THREAD

**Issue by shamangit** [firehol/netdata#1830]
Hello all,

I installed netdata on a RedHat Linux server. When I start the service, I see the following message.
2017-02-22 10:41:38: netdata: ERROR: IPv6 socket() on ip ‘::’ port 19999 failed. (errno 97, Address family not supported by protocol)
2017-02-22 10:41:38: netdata: ERROR: Cannot bind to ip ‘::’, port 19999
2017-02-22 10:41:38: netdata: INFO: Listen socket [0.0.0.0]:19999 opened.

Trying to access htt://linux-hostname:19999 from a browser on a Windows machine didn't work.
Can someone please help me?

Thanks

**Comment by ktsaou** [comment]
I understand netdata started. It couldn't open an IPv6 port, but it managed to open an IPv4.

My guess is that you have a firewall installed that prevents you from accessing it.

To verify it runs, do this:

```sh
netstat -nat | grep LISTEN | grep 19999
```

Does it show a line?

Here is mine:

```sh
# netstat -nat | grep LISTEN | grep 19999
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN     
```

**Comment by shamangit** [comment]
Hi Costa,

It shows this without the LISTEN:

# netstat -nat | grep LISTEN | grep
tcp        0      0 0.0.0.0:19999               0.0.0.0:*

Thanks,
Shashi

**Comment by ktsaou** [comment]
The above means that netdata runs.
So, you must have a firewall running that blocks port 19999.

**Comment by shamangit** [comment]
Can you suggest where I can change the port from default value of 19999?
I guess it's netdata.conf but I thought I saw it more than in one place.

**Comment by l2isbad** [comment]
@shamangit 
```
sudo grep '= 19999' netdata.conf
        # default port = 19999
```

**Comment by ktsaou** [comment]
netdata can listen to multiple ports/IPs:

```
[global]
   bind to = IP1:19999 IP2:19998 IP3:19997 [ipv6:ip1]:19996 [ipv6:ip2]:19995
```

The `default port` is used when `bind to` does not specify a port.

**Comment by ktsaou** [comment]
> # netstat -nat | grep LISTEN | grep
> tcp        0      0 0.0.0.0:19999               0.0.0.0:*

Something is wrong with this. You grepped `LISTEN` but it is not shown?

**Comment by shamangit** [comment]
On the terminal, it seems working; so I guess it's stopped by firewall rules to be connected from a different machine.
wget http://hostname.domain.com:19999
--2017-02-24 08:43:54--  http://hostname.domain.com:19999/
Resolving hostname.domain.com... <ipaddress>
Connecting to hostname.domain.com|<ipaddress>|:19999... connected.
HTTP request sent, awaiting response... 200 OK
Length: 174190 (170K) [text/html]
Saving to: “index.html”

100%[==========================>] 174,190     --.-K/s   in 0s

2017-02-24 08:43:54 (428 MB/s) - “index.html” saved [174190/174190]

Is there a way I can find:
1) an open port that’s not blocked by the firewall and
2) change the default 19999 port to a different one?

Thanks.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.

It seems I missed your last question. You can change the netdata port by editing `/etc/netdata/netdata.conf` at the `[web]` section.
Sorry for the long delay to get this info.

If you still need help, post here.
