### ISSUE TITLE
Feedback on weblog monitoring

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#1832]
Now that I've used this for a few days I can provide some feedback. What's happening on low traffic sites is that we often get alerts about the ration of good/bad requests which are quite normal and shouldn't raise an issue.

Here is an example:

![2017-02-23 10 23 58 screen](https://cloud.githubusercontent.com/assets/1475675/23253395/a2943d9a-f9b4-11e6-8175-f1be1603a251.jpg)

Only for a couple of seconds there are some 40x responses which is almost always the fact when a bot scans the site where they have outdated links in their repository that they re-check.

I'm not entirely sure but I guess what would be much better is to increase the time period or to set the period somehow in relation to the overall traffic.

**Comment by ktsaou** [comment]
hm... yeap I found that too.

Possible solutions:

1. increase the number of **total** requests required to evaluate the alarm. The calculation is `bad * 100 / total`. Now `total` is 120/5min for the `5min_*` alarms and 120/min for the `1min_*` alarms. I am not sure if this is right though.

2. give an up-hysteresis to the alarm. So, the alarm will trigger, you will see the HTML5 notification on the dashboard, but it will send all other kinds of notifications (including email) only when the alarm is raised for e.g. 1 minute. If the alarms disarms within 1 minute, there will be no notification. How does that sound?

**Comment by jurgenhaas** [comment]
The first one doesn't sound good for some reason. It's more like ignoring this health parameter for smaller sites which isn't really what we want.

The second one sounds better but I would tailor that a bit: if you measure data of the last minute and only alert if the situation stays the same for at least a minute, the likelihood that this still raises the alert is pretty high. As an example look at the chart posted in my original post, the problem is there for only a few seconds but those seconds have an impact for as long as a minute as you always measure the last minute in that case.

So, if we measure the last minute, we should raise an alert if the problem persists for at least 2 minutes.

The following list indicates that this might be correct:

![2017-02-24 08 01 25 screen](https://cloud.githubusercontent.com/assets/1475675/23293735/18fa9778-fa68-11e6-9c46-0a552cbb09c8.jpg)

But that also shows that we get double alerts because we measure the percentage of good requests with an alert if that goes below the threshold. And we also get an alert if the percentage of base requests goes below the threshold. And both alerts will fire almost always at the same time.

**Comment by ktsaou** [comment]
ok. I added 2 minute delay to trigger notifications at #1840
Can you test it, before merging it?

**Comment by jurgenhaas** [comment]
I have updated the web_log alerts accordingly and they don't fire alerts anymore but they still show in the dashboard. Is that intended?

**Comment by ktsaou** [comment]
yes, exactly.

So, they don't bother you with notifications, but if watch the dashboard you will know something is happening.
