### ISSUE TITLE
Suggestion: exclude "nice" from default CPU utilization health config

### ISSUE THREAD

**Issue by literal** [firehol/netdata#1833]
IMO Netdata's greatest advantage is how it works out of the box with very little need to understand and tweak all the config files. So I guess it's an important objective to make the default config as universally useful as possible.

After installing Netdata we initially had lots of false CPU utilization alarms due to media encoding batch jobs. These jobs are meant to fully utilize the CPU and are "niced" to prevent the servers from becoming unresponsive. I guess that's not such an uncommon a scenario.

We fixed the false alarms by removing "nice" from the "10min_cpu_usage" query in /etc/netdata/health.d/cpu.conf. But I guess it would be sensible to make that the default, because high "nice" CPU load is usually intentional and hardly an operational problem.

**Comment by ktsaou** [comment]
Nice suggestion! Let me think of it a bit. At first glance, I think you are right.

**Comment by ktsaou** [comment]
ok. did it. I will merge it in a while (the ticket will close automatically when merged).
Thanks!
