### ISSUE TITLE
New Mountpoint search of  [plugin:proc:diskspace] causes cifs/kerberos mount to fail every 15seconds

### ISSUE THREAD

**Issue by mind-code** [firehol/netdata#1834]
I have 2 Mountpoints via fstab that mount via this line:

` SOURCE  MNTPOINT    cifs    noauto,x-systemd.automount,user=USER$,sec=krb5,multiuser,noserverino  0       0`

This mountpoint gets mounted on first access and requires the user to have a valid Kerberos ticket. It works great.

When I start netdata, it tries to mount these mounts as the netdata user and it fails since the local netdata user obviously has no Kerberos Ticket. This generates 2 errors every 15 seconds. Is there any way to disable this behaviour and get netdata to ignore these mountpoints?

The mountpoints appear to have no own section in the netdata.conf.

When I play with the options under [plugin:proc:diskspace] it does seem to have an effect. The 
 **check for new mount points every** parameter works in changing the times between the errors. So it seems that this functionality is the culprit. The option **exclude space metrics on paths** seemed like a good option to get around my problem. Unfortunately it doesnt work. 

There should be a way to permanently exclude Mountpoints from being scanned.

**Comment by mind-code** [comment]
In the same vein, I also have NFS4 mounts that mount with noauto,x-systemd.automount as well. These dont generate errors, but this behaviour by netdata causes all these mountpoints, that are delayed on purpose until the first (real) user accesses them to mount immediatly on netdata start at boot time.

**Comment by ktsaou** [comment]
hm... interesting!

Could you please make a test?

Change this line: https://github.com/firehol/netdata/blob/27ef89eccffa5d3aef8b8cdba30fb8b39d059a3c/src/proc_self_mountinfo.c#L285

To:

```c
if(do_statvfs && !(mi->flags & MOUNTINFO_IS_DUMMY)) {
```

There is another such line here: https://github.com/firehol/netdata/blob/27ef89eccffa5d3aef8b8cdba30fb8b39d059a3c/src/proc_self_mountinfo.c#L322

Change that too. But can you find out which of the 2 causes the issue? It might be both, but I would prefer not to disable both if any of them is not problematic.

The above will disable calls to `stat()` and `statvfs()` on dummy filesystems. Dummy filesystems are defined at: https://github.com/firehol/netdata/blob/27ef89eccffa5d3aef8b8cdba30fb8b39d059a3c/src/proc_self_mountinfo.c#L19-L35

`autofs` is in them.

**Comment by mind-code** [comment]
Thank you for your response.

I did the tests:

| Line285 | Line322 | fixed? |
| --------- | --------- | -------- |
| x | x | yes |
| x | - | no |
| - | x | yes |

So this change fixes the automount triggering on boot! Great!

But it appears, we have 2 issues here. This fix above, fixes the automount triggering, but once the CIFS mount gets mounted at any point the access error messages reappear every 15 seconds. The Filesystem is now mounted and appears as normal cifs type FS in /proc/self/mountinfo. Back to the original Problem, netdata then tries to access these mountpoints constantly and generates a lot of errors over time. 

I tried to find a fix/workaround for me by adding the Fs_type cifs to: https://github.com/firehol/netdata/blob/27ef89eccffa5d3aef8b8cdba30fb8b39d059a3c/src/proc_self_mountinfo.c#L19-L35

This works, but only if I change both, Line 285 and 322. This is probably not a good solution to put into your actual code :), but it fixes my issue for now. I have no other cifs mounts on these systems that I would have a need for netdata to look at. Do I have to expect some negative behaviour from changing both these lines?

Maybe you have an idea how to handle this special cifs case better?

**Comment by ktsaou** [comment]
you are right.

I think that additionally to line 322, you can change the `1` to `0` in this line: https://github.com/firehol/netdata/blob/27ef89eccffa5d3aef8b8cdba30fb8b39d059a3c/src/plugin_proc_diskspace.c#L17

Once you do this, `statvfs()` (the problematic call), will be executed only when it is not excluded from disk space charts. So you will be able to add:

```
[plugin:proc:diskspace]
    exclude space metrics on paths = /path/to/problematic/mountpoint ...whatever the line already has...
```

So, just prepend the CIFS mount point.

Can you confirm this fixes the problem?

**Comment by ktsaou** [comment]
I made the above in PR #1817 

I also added an option to exclude filesystems:

```
[plugin:proc:diskspace]
	# update every = 1
	# check for new mount points every = 15
	# exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/*
	# exclude space metrics on filesystems = 
	# space usage for all disks = auto
	# inodes usage for all disks = auto
```

This PR however is huge - we will need a few days to merge it.

**Comment by mind-code** [comment]
I will verify as soon as possible, but this is work related for me and the earliest opportunity for me to test will be Monday morning CET.

**Comment by ktsaou** [comment]
No problem! I'll wait for you.

**Comment by mind-code** [comment]
I verified the suggestes fix and the commit, even though u didnt wait :smile: 

The manual fix 1->0 and add Mountpoints to excluded list: **works / fixed**
New Patch/Commit - add Mountpoints to excluded list: **works / fixed**
New Patch/Commit - add FS to excluded list: **works / fixed**

Thank you very much for this speedy fix. This has been a very pleasent experience :+1:

**Comment by l2isbad** [comment]
@mind-code I think it happened automatically after merge 😄

**Comment by ktsaou** [comment]
oh... sorry. github closes issues related to PRs that are merged.
I didn't want to be rude.
Sorry!

**Comment by mind-code** [comment]
No worries, thats why I put a smilie there.

Anyway thank you for your work and quick help, its much appreciated!
