### ISSUE TITLE
Question : nginx virtual host

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/netdata#1835]
Netdata is pretty good for monitoring your machine. But I was thinking of monitoring my virtual host to netdata. How can I do that ?

**Comment by l2isbad** [comment]
What is `monitoring my virtual host`? What do you mean?

**Comment by netchild** [comment]
Hi,

guessing what you mean:
 - let each nginx virtual host write it's own logfile
 - have in each nginx virtual host a nginx stub status url (example below)
 - use the python.d/nginx_log.conf to monitor each logfile
 - use python.d/nginx.conf to monitor the stub status for each virtual host

Example nginx config for the stub status:
     location /my_stub_status_url_for_the_vhost {
                        access_log off;
                        stub_status on;
                        allow <IP of netdata host/interface>;
                        deny all;
                }

**Comment by l2isbad** [comment]
Well, there is no technical reason not to do so.

**Comment by sLuvpreet33** [comment]
Can you elaborate the python.d/nginx_log.conf part ?

**Comment by l2isbad** [comment]
`python.d/nginx_log.conf` is the configuration file for `nginx_log` python plugin which is no longer used

https://github.com/firehol/netdata/issues/1847

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
