### ISSUE TITLE
Error with fail2ban plugin, maybe others

### ISSUE THREAD

**Issue by nublaii** [firehol/netdata#1837]
I have a couple of custom made jails for fail2ban, and their names are (the file name matches the jail name)

```
/etc/fail2ban/jail.d/testing
/etc/fail2ban/jail.d/testing_someothername
```

They are both properly configured inside /etc/fail2ban/jail.d/ and enabled.

I added `conf_dir: '/etc/fail2ban/jail.d/'` to python.d/fail2ban.conf and after restarting netdata **only the first one appears**, the one named _testing_ in this case.

If I rename the jail to something else it works as expected.

**Comment by l2isbad** [comment]
Current for conf_dir is:
1. find all *.conf files in conf_dir
2. find all *.local files in conf_dir
3. add to list all *.local and all *.conf if name.conf not in *.local 
4. find all jails in all these files in list
5. regex for jails
```
r'\[([A-Za-z-]+)][^\[\]]*? enabled = true'
```

[A-Za-z-]+ not matches [testing_someothername]

**Comment by nublaii** [comment]
that was fast ;)

It works, but I found an extra quirk: it finds everything inside and enabled in `/etc/fail2ban/jail.d/*` but it doesn't find the ones defined and enabled inside `/etc/fail2ban/jail.conf`.

Apparently when you define **conf.dir** it doesn't parse **jail.conf**?

**Comment by l2isbad** [comment]
@nublaii 
Yes. But I think you are right. Plugin must parse conf file AND files in conf_dir.

**Comment by l2isbad** [comment]
@nublaii 
I think i fix it. Can you test it please?

**Comment by nublaii** [comment]
Humm... nope, still happening, any way I can start this up that could give you more info?

**Comment by l2isbad** [comment]
@nublaii 
It works for me 100%.
Are you sure you are using modified script from my PR?

**Comment by l2isbad** [comment]
```
grep --before-context=2 "^enabled.*= true" jail.local 
[ssh]

enabled  = true

grep --before-context=2 "^enabled.*= true" jail.d/jail.local 
[apache]

enabled  = true

grep fail2b error.log
2017-02-25 10:38:13: python.d INFO: fail2ban_local Plugin successfully started. Jails: ['apache', 'ssh']
2017-02-25 10:38:13: python.d INFO: CHECKED OK: fail2ban_local
```

**Comment by nublaii** [comment]
I see what the problem is... I'm not using **/etc/fail2ban/jail.local**. I'm using the default **/etc/fail2ban/jail.conf** for 'ssh', and that one is not showing up...

**Comment by l2isbad** [comment]
Plugin uses the one defined in configuration file (`conf_path`). If `conf_path` is not defined default is '/etc/fail2ban/jail.local'

**Comment by nublaii** [comment]
Ok, I changed the config to point to **/etc/fail2ban/jail.conf** and now it works perfectly.

Wouldn't it make more sense to make the default for the plugin the same as the default for fail2ban?

**Comment by l2isbad** [comment]
Default is `/etc/fail2ban/jail.local`

from `jail.conf`

> To avoid merges during upgrades DO NOT MODIFY THIS FILE
> and rather provide your changes in /etc/fail2ban/jail.local

**Comment by nublaii** [comment]
Makes sense, the only problem is the default installation on Ubuntu server (at least on 14.04 and 16.04) has the ssh jail enabled on the main jail.conf.

**Comment by l2isbad** [comment]
I think it's always only the `conf` file.
Lack of .local in debian repository:
```
apt-file show fail2ban | grep -E 'jail\.(conf|local)$'
fail2ban: /etc/fail2ban/jail.conf
```

If plugin didn't find any jails in configuration files it will use `ssh` as the default jail.
https://github.com/l2isbad/netdata/blob/fail2ban_plugin_improvements/python.d/fail2ban.chart.py#L83

```python
self.jails_list = list(set(jails_list) - set(self.exclude)) or ['ssh']
```

**Comment by nublaii** [comment]
Going for edge-cases:

 I leave the ssh jail on the default jail.conf, create a jail.local file to add some extra jails and then put some inside jail.d/extraone.conf

**Comment by l2isbad** [comment]
> The current config will force you to pick either jail.conf or jail.local right?

Yes. You don't need both. No customization - jail.conf. Any customization - jail.local and/or jail.d/ 

I understand there is cases when you need all - jail.conf, jail.local and jail.d/*.conf|local. But it's strongly not recommended.

**Comment by l2isbad** [comment]
The first thing a user should do after fail2ban installation (and after reading information in jail.conf!) is to copy jail.conf to jail.local.

**Comment by pschiffe** [comment]
No, there is no need for copying. From official documentation [1]:
> Every .conf file can be overridden with a file named .local. The .conf file is read first, then .local, with later settings overriding earlier ones. Thus, a .local file doesn't have to include everything in the corresponding .conf file, only those settings that you wish to override.
> Modifications should take place in the .local and not in the .conf. This avoids merging problem when upgrading. These files are well documented and detailed information should be available there.

So, from [2], this is how the configuration is read:
> Files are applied in the following order:
>    /etc/fail2ban/jail.conf
>    /etc/fail2ban/jail.d/*.conf, alphabetically
>    /etc/fail2ban/jail.local
>    /etc/fail2ban/jail.d/*.local, alphabetically

`/etc/fail2ban/jail.conf` is for fail2ban upstream, should not be modified by distro or user. `/etc/fail2ban/jail.d/*.conf` is for distro and packages from distro repositories, `/etc/fail2ban/jail.local` and `/etc/fail2ban/jail.d/*.local` are for users. I personally just use something like `/etc/fail2ban/jail.d/99-my-config.local` and I put there only what differs from defaults.

But I guess this can differ in various distros. What I've just described applies to CentOS and Fedora.

[1] https://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Configuration
[2] https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-centos-7

**Comment by l2isbad** [comment]
@pschiffe 
I know. I mean it is easier to copy jail.conf to jail.local and modify it than create a new file and put configuration to it.

**Comment by ktsaou** [comment]
Is this a bug that needs to be fixed?

**Comment by l2isbad** [comment]
> Is this a bug that needs to be fixed?

no

fail2ban plugin reads from `conf_path` file and all `.conf` and `.local` files in `conf_dir`. If `conf_path` is not defined default is `/etc/fail2ban/jail.local`.

The logic is simple, works well and i see no reason to complicate it.

**Comment by ktsaou** [comment]
ok. I am closing this.

**Comment by l2isbad** [comment]
About labels - for the sake of trues,  it was a bug. Fixed in https://github.com/firehol/netdata/pull/1839
😄

**Comment by pschiffe** [comment]
Hi @l2isbad , I've just updated netdata to 1.6 and checked the fail2ban plugin. I have a suggestion - couldn't be the line:
```
# conf_dir: '/etc/fail2ban/jail.d/'
```
uncommented by default? It would be easier for users. Or is there a specific reason behind the comment?

Also, I have an idea for additional graph - number of currently blocked ips. This can be read from the output of `fail2ban-client status <jail>` command:
```
# time fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	10
|  `- Journal matches:	_SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned:	10
   |- Total banned:	10
   `- Banned IP list:	110.77... list of ips ...166.77

real	0m0.057s
user	0m0.041s
sys	0m0.015s
```

**Comment by pschiffe** [comment]
@l2isbad hm, now I see. If the configuration of fail2ban is in both, `jail.local` and `jail.d/`, the plugin doesn't work correctly. It seems that it reads only the `jail.local` file. But in some cases, I have jail enabled in `jail.local` and then disabled in `jail.d/` (because the `jail.local` is managed by some other sw). Maybe reading only the output of `fail2ban-client status` would make it easier and more robust..

**Comment by l2isbad** [comment]
> reading only the output of fail2ban-client status

do not want 😄 

> Also, I have an idea for additional graph - number of currently blocked ips. This can be read from the output of fail2ban-client status <jail> command

Actually i think i can do the same without `fail2ban-client status`. The only i need is `bantime` (this thing is global, isn't it?). Then i can add to the list banned ip, remove it after `bantime` and chart length of the list. 
What do you think?

> uncommented by default?

agree

> But in some cases

There is always some cases 😄 

> It seems that it reads only the jail.local file

It reads both - all .local and .conf files in `conf_dir` and file in `conf_path`

**Comment by pschiffe** [comment]
> It reads both - all .local and .conf files in `conf_dir` and file in `conf_path`

so it ignores redefines or something:
```
# cat /etc/fail2ban/jail.local 
[ssh-iptables]
enabled  = true

[vsftpd-iptables]
enabled  = false

[exim-iptables]
enabled = true

[vesta-iptables]
enabled = true
```
```
# cat /etc/fail2ban/jail.d/my.local 
[vsftpd-iptables]
enabled = true

[exim-iptables]
enabled = false
```
```
# fail2ban-client status
Status
|- Number of jail:	3
`- Jail list:	ssh-iptables, vesta-iptables, vsftpd-iptables
```
```
# cat /etc/netdata/python.d/fail2ban.conf
...
local:
 log_path: '/var/log/fail2ban.log'
 conf_path: '/etc/fail2ban/jail.local'
 conf_dir: '/etc/fail2ban/jail.d/'
```
```
# cat /var/log/netdata/error.log
...
2017-03-23 13:56:26: python.d INFO: fail2ban Plugin succefully started. Jails: ['ssh-iptables', 'exim-iptables', 'vesta-iptables']
```

`bantime` can be configured differently for every jail. See, I can understand you don't like parsing the output of the `fail2ban-client status`, but reimplementing the config parser of fail2ban isn't too much win either. You also need to watch the log file for unbans, as ip might be removed before the `bantime` expires.

**Comment by l2isbad** [comment]
Ye, i know. Regex matches only `true` jails
https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L18

You can remove any jails from chart by adding them to the ```exclude``` in the module configuration file
https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L83

I agree we should change jail-auto-detect part logic (but i still think all problems because of poor jails management)
