### ISSUE TITLE
possibility to prepopulate registry?

### ISSUE THREAD

**Issue by daku69** [firehol/netdata#1838]
Hi,

it woudl be nice if there's a possibility to prepopulate the (local) registry with a list of hosts.

use case: we have a bunch of servers, whenever someone "new" connects to one of the netdata instances, or when you purge the browsers cache/config, one has to start from scratch. it would be nice if we could have a static list of certain hosts as a default "inventory", rather than an empty list.

Regards,
David

**Comment by ktsaou** [comment]
Yes, I know. Check this: #505

I am closing this, as duplicate, in favour of #505.
Let's continue the discussion there.

Thanks!
