### ISSUE TITLE
Blockers preventing netdata integration with FreeNAS

### ISSUE THREAD

**Issue by jordanhubbard** [firehol/netdata#1841]
Hi folks,

Well, for now we've unfortunately had to give up.  FreeNAS, being a software appliance rather than a generalized OS, has certain requirements it imposes on all of its services just to keep things under some modicum of control (since the boot environment is more restricted, requires that services do more controlled I/O to what might be a USB flash device with limited write wear-leveling, etc).

For 1.5.0 we're going to put this on hold but will absolutely consider requests from our users to integrate subsequent releases of netdata that eliminate or mitigate at least some of the issues in https://bugs.freenas.org/issues/20521, which I will simply summarize here:

1. Overhead is still too high - I see this getting much better in unreleased github versions, so perhaps with 1.6 or some later version, once the FreeBSD port gets refreshed, we can revisit this.

2. netdata needs an option to log to syslog and **only** syslog.  Some appliances like FreeNAS don't even encourage local log file generation (see above about flash memory, or keeping disks spun down to reduce power consumption when system dataset is on primary ZFS pool) and will therefore configure a remote syslog server and send all of their log data elsewhere.

3. netdata needs, for same reason above, the ability to turn the registry off completely (and not even attempt to create it, if disabled).

4. For sanity's sake, it would be much more desirable for netdata to not attempt to read and write to so many different filesystem locations at all - /var/log/netdata, /var/lib/netdata, /var/cache/netdata, /usr/local/share/netdata, all of which require certain permissions, all add to the burden of migration and upgrades of the system overall.  As per above, we would much prefer to have netdata to follow the standard unix application template:  binary in /usr/local/sbin, data files (not owned by any particular user - root:wheel should be permissable) in /usr/local/share and persistent data in /usr/local/var/db or nowhere at all, if disabled (/usr/local/var in order to keep everything under common prefix and not cause "prefix pollution").

Thanks.

**Comment by ktsaou** [comment]
Hi. Thanks for the feedback.

1. I understand the current github version does not have this issue to the degree experienced in 1.5.0 ( @vlvkobal what changed? ). However, keep in mind that you can lower the data collection frequency. Going from "per second" to "once every 2 seconds" will cut the CPU requirements in half.

2. It is already there. Set `error log = syslog` and `access log` and `debug log` to `none`. You can send `access log` to `syslog` too, if you like.

3. The registry server is disabled on all netdata servers by default. I guess you mean the `my-netdata` menu of the dashboard, which is purely a dashboard feature (i.e. implemented at the web browser).  Check this for more information: https://github.com/firehol/netdata/wiki/mynetdata-menu-item

   What bothers you?

4. All these are configurable, both at compile time and run time.

   You can pass to `./configure` the paths you would like netdata to use.

   You can also change all paths and web files permissions at `netdata.conf`.

Keep in mind you can easily come up with a setup where netdata never writes to disks:

i. disable logs (set them to `none` or `syslog`)
ii. set `memory mode = ram`
ii. disable `health` (it maintains a log of alarm events on disk).

Do you need help? I can help to settle all issues that bother you...

**Comment by ktsaou** [comment]
btw, If the current github version of netdata is so much more efficient than 1.5.0, I can release 1.6.0 immediately.

**Comment by ktsaou** [comment]
I see at the ticket you mentioned that the issues are:

> Okay, this is not going to happen. netdata has too many problems:
>
>1) it needs /var/log/netdata directory even though I configured it to log to syslog only - why?
>2) it needs /var/lib/netdata and /var/cache/netdata directories even though I configured it to not use any persistent storage
>3) it needs special permissions in /usr/local/share/netdata
>4) it uses more CPU time than whole FreeNAS 10 middleware in background operation

1. set `log directory = /tmp` - netdata will not write anything there, since all logs are set to `syslog`.

2. set  `cache directory = /tmp` - netdata will not read / write anything there, if the `memory mode = ram`.
   You should keep `lib directory` somewhere though. This is needed for the alarm log and for storing the netdata unique id.

3. set `web files owner` and `web files group` to whatever you like for these files.

4. increase `update every` to `2` or more. This will lower the update frequency and divide a CPU consumption. I would love to have some more insights on the CPU consumption of netdata on FreeNAS. Is the increased CPU observed on PCs/servers or embedded devices?

**Comment by jordanhubbard** [comment]
I think some important details from the ticket may have been misinterpreted.  It's not that we didn't try to set those configuration options, it's that the netdata service simply falls over at startup time without those directories present (try it!) even with those configuration options set.  We're trying to essentially create a "minimum footprint" netdata for inclusion with FreeNAS and we simply don't create any more directories, with permissions any more customized than we have to, and the end result is that netdata simply fails to start when we do this.

**Comment by vlvkobal** [comment]
> I understand the current github version does not have this issue to the degree experienced in 1.5.0 ( @vlvkobal what changed? ).

#1691, #1709,  #1711, #1724

**Comment by ktsaou** [comment]
hm... ok. I think #1724 lowered the CPU significantly. On systems with many cores it was multiplying the number of `sysctl`s made.
Thanks!

**Comment by ktsaou** [comment]
> I think some important details from the ticket may have been misinterpreted. It's not that we didn't try to set those configuration options, it's that the netdata service simply falls over at startup time without those directories present (try it!) even with those configuration options set. We're trying to essentially create a "minimum footprint" netdata for inclusion with FreeNAS and we simply don't create any more directories, with permissions any more customized than we have to, and the end result is that netdata simply fails to start when we do this.

Probably. Let me check. This what I did:

1. on a fresh machine, without netdata ever installed
2. git clone the repo in my home
3. `./autogen.sh`
4. `./configure` (without any options - the defaults)
5. `make -j4`
6. **I did not install it**
7. edited `/tmp/netdata.conf` with these:

```
[global]
        config directory = /home/costa/src/netdata-ktsaou.git/conf.d
        plugins directory = /home/costa/src/netdata-ktsaou.git/plugins.d
        web files directory = /home/costa/src/netdata-ktsaou.git/web
        log directory = /tmp
        cache directory = /tmp
        lib directory = /tmp
        home directory = /tmp
        memory mode = ram
        access log = none
        debug log = none
        error log = syslog
        run as user = costa

[web]
        web files owner = costa
        web files group = costa
```

(if you use v1.5 the `[web]` section does not exist - put the settings in `[global]`).

You can see the paths pointing directly to my home. I also asked netdata to run as me (user `costa`), and check the web files with my user and group.

Then I run this **directly from the compiled git repo, without installing it**:

```
./src/netdata -D -c /tmp/netdata.conf
```

It runs perfectly.

Since I pointed `lib directory` to `/tmp` it created a few files there. You should keep lib dir somewhere persistent.

Could you please help me reproduce the problem?

**Comment by brando56894** [comment]
They have moved Netdata integration into the SU1 (10.1) milestone since they're really trying to get RELEASE (10.0) out ASAP, so this probably won't be attended to for another few weeks at least. Just to keep you updated.

Here is the new ticket for reference sake: https://bugs.freenas.org/issues/21493

**Comment by ktsaou** [comment]
ok. thank you for letting me know.
I am also trying to release netdata 1.6, so most probably this will be out before they give it another try.

**Comment by jordanhubbard** [comment]
Please let me know when 1.6 is released and the FreeBSD port maintainer does a pull-up (I think mohki?) and we'll try again in a FreeNAS Corral software update!

**Comment by ktsaou** [comment]
> Please let me know when 1.6 is released and the FreeBSD port maintainer does a pull-up (I think mohki?) and we'll try again in a FreeNAS Corral software update!

of course!

cc: #1947

**Comment by jordanhubbard** [comment]
Thanks, we have this screened into https://bugs.freenas.org/issues/21493 and will release it in a Software Update sometime after you guys get done and we have a chance to integrate, test and also create a proper services UI entry for it.

**Comment by ktsaou** [comment]
ok thanks.
@vlvkobal has done a refactoring on the freebsd code to make it more modular and manageable.
Also, `apps.plugin` has been ported for freebsd, providing a few new sets of charts, breaking down the system process tree into application groups, users and user groups. The application groups are controlled by `/etc/netdata/apps_groups.conf`.

We have also added a freeipmi plugin that could be useful for use, if freenas is installed on server hardware.

Would you like to test these a bit on freenas before our release?

Our target is to release v1.6 this weekend. If we find a breaking point, we will postpone the release for another week. So, your feedback will greatly help us.

**Comment by jordanhubbard** [comment]
I have asked the engineering manager for FreeNAS 9.10 to also look into integration since his release schedule is a bit more relaxed than ours for 9.10.3; he is looking into this now.  We are doing a rapid-response release to FreeNAS Corral (aka "10") tonight but after that we can look at #21493 (our ticket) again and see what milestone to aim for.  Thanks!

**Comment by ktsaou** [comment]
nice! thank you!

**Comment by ktsaou** [comment]
Just released netdata v1.6.0
I think you can give netdata another try...

**Comment by jordanhubbard** [comment]
It's going into FreeNAS Corral 10.0.3 which will be released tonight!   JFYI.  It's specifically called out in the ReleaseNotes which are here (in addition to being in the download directory and posted to the FreeNAS Forums, once the release is pushed later tonight):  https://github.com/freenas/corral-build/blob/master/build/profiles/corral/release/FreeNAS/Corral/10.0.3/ReleaseNotes.md

Thanks for all your help!!

**Comment by ktsaou** [comment]
Wow!
Thank you!

**Comment by ktsaou** [comment]
FYI, netdata now supports zfs monitoring. Check it live at http://freebsd.my-netdata.io/#menu_zfs
