### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by netchild** [firehol/netdata#1842]
Hi,

the following I noticed on FreeBSD (going down top to bottom) (with netdata 1.5.0) -- update after ktsaou asked to look at the online demo which runs a more recent snapshot (= shortened my list of suggestions):
1. cpu - "nice" is red and "user" is green. Is this on purpose? red and green are signal colors, red being the "dangerous/attention" and green the "all ok" one. I suggest to use other colors than red/green as there is not really a warning/OK condition on the utilisation (except maybe 100% = you applications want a faster CPU). IF you want to stay with red/green, I suggest to change the colors for user/nice, as (assuming the usual case of nice values which give lower priority) the user part is the interesting part when it comes to bottlenecks.

2. disk - the values displayed are in/out. I suggest to change this to read/write.

3. swap - I suggest to change in/out to read/write

4. processes - "All system processes" - If I understand it rights it's the number of processes in the system, no matter if runnning on CPU or stopped, or zombie (maybe you eant to also graph zombies?). The text there says "active" processes (in the text and in the label of the legend), which suggest "running". I suggest to stick with one way of description (suggestion for the label "processes").

5. interrupts - I have a lot of interrupts which are always 0, and a lot which are fixed rate. A way to have the legend sorted in a different way would be nice (hide "0", sorted by int/s, manual order, ...).

6. uptime - I suggest to display in more easily human understandable units automatically, e.g. after 180 seconds switch to display in minutes, after 120 minutes switch to display in hours, after 48 hours switch to days, after 120 days switch to months.

7. IPv4 TCP errors - the graph is plotting into the negative range only, bug in the calculation of values on FreeBSD?

Bye,
Alexander.

**Comment by l2isbad** [comment]
Looks like [related](https://github.com/firehol/netdata/issues/1480)

**Comment by ktsaou** [comment]
@netchild I guess you are referring to v1.5.0.

Could you please update this for the current version (live at http://freebsd.my-netdata.io)

**Comment by netchild** [comment]
@ktsaou Done = less suggestions. 👍

**Comment by ktsaou** [comment]
ok, nice!

1. `cpu` chart colors, fixed. @vlvkobal FYI the colors are in pairs: good, bad, good, bad, good, bad, etc. (so put the good ones on odd positions and the bad ones on even positions). Of course: good = bright colors such as green, yellow, blue, ... and bad = dark colors such as red, orange, brown, ...

   I tried to change the Linux colors too. It seems there are a few deviations from the above, so I postponed it until I find some time to re-arrange the colors on the dashboard.

2. you are right - it will break a lot of things if we do it now. I guess at the next major release.

3. same as above.

4. hm... a process is of course a program currently loaded and able to execute. But then we also have the `running` processes, meaning that they are executing, they are at the CPU, right now. I needed to find a way to distinguish the two. So, I decided to call `active process` a program that is loaded and is able to execute code and `running process` a program that is running some code at the CPU right now.

5. legends sorting is discussed at https://github.com/firehol/netdata/issues/1566#issuecomment-272555453

   Constantly zero dimensions should be hidden, unless all the dimensions are zero, or the dashboard setting explicitly wants zero dimensions to be shown:

   ![image](https://cloud.githubusercontent.com/assets/2662304/23339886/4e991eea-fc34-11e6-8038-9f06adb775ce.png)


6. It is human in a badge, like this: ![](http://registry.my-netdata.io/api/v1/badge.svg?chart=system.uptime) (this is live, refresh the page to get a new one). Unfortunately at the chart it is way too complex to do this. It would require dynamic divisors depending on the value.

7. positive and negative number are artificial in netdata. We intentionally make numbers negative to improve visualization (i.e. in/inbound/read = positive, out/outbound/write = negative).

**Comment by ktsaou** [comment]
I did a few edits, so please read it on github.

**Comment by ktsaou** [comment]
I have moved all the unit conversion requests to #2745 
The request to convert uptime to something human readable will be handled there.

I think the only pending request is rename the disk I/O dimensions to `read` and `write`. I have created #2746 to track all dimensions naming issues.

So, I am closing this.
If there is something more pending that I missed, just post here to let me know.
