### ISSUE TITLE
smartd_log plugin doesn't work on RHEL/CentOS 7

### ISSUE THREAD

**Issue by pschiffe** [firehol/netdata#1846]
It's because the smartd service logs to journald, not to /var/log/smard directory. Systemd has python bindings, so it's should be easy to parse logs from journald in python, ie. see https://www.g-loaded.eu/2016/11/26/how-to-tail-log-entries-through-the-systemd-journal-using-python/

**Comment by l2isbad** [comment]
It work for me on manjaro.

`man smartd`

> OPTIONS
>        -A PREFIX, --attributelog=PREFIX
>               Writes   smartd   attribute   information   (normalized   and   raw   attribute   values)  to  files  'PRE‐FIX''MODEL-SERIAL.ata.csv' or 'PREFIX''VENDOR-MODEL-SERIAL.scsi.csv'.

```
cat /etc/default/smartmontools
SMARTD_ARGS="-i 3600 -A /var/log/smartd/"
```

**Comment by pschiffe** [comment]
Well yeah, as a workaround, I can configure `smartd` to log to the directory; but in general, I don't want to do that as then I have to configure `logrotate` and it takes disk space and utilization. Better workaround is just to configure `smartd` to send notification email if there is something wrong with disks (if metrics are not that important). BTW, does netdata send alerts if there is some smart error by default? I didn't find it in `health.d/disks.conf` file.

**Comment by l2isbad** [comment]
@pschiffe

I don't agree that it's a workaround. Plugin is mega light. It reads from log file only if there is new data (1 time per --interval).

> logrotate and it takes disk space and utilization

Disk space and utilization? Literally zero utilization. It's up to you what interval you want to configure. Super super super tiny even without logrotate.  

> if there is some smart error by default? 

No. What is error?
 
Raw values are vendor specific and meaningless (to set up default alarms). Normalized...Can you suggest anything?

**Comment by pschiffe** [comment]
@l2isbad I didn't mean plugin, but the csv files in `/var/log/smartd/`, they will grow indefinitely w/o logrotate..
**BUT** I double checked your first comment in this issue and the data in csv files in `/var/log/smartd/` are **not** available in `journald`. The `smartd` daemon won't log those data unless configured with the `-A` option, so there is no need for supporting `journald` in this plugin. I'm sorry for the noise.

WRT the smart error, it's useful to monitor:
```
# smartctl --health /dev/sda
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-3.10.0-514.6.2.el7.x86_64] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
```

If result is not `PASSED` alert should be raised.

**Comment by l2isbad** [comment]
@pschiffe 

> they will grow indefinitely w/o logrotate

[Of course. It's in configuration file.](https://github.com/firehol/netdata/blob/master/conf.d/python.d/smartd_log.conf#L71-L72)

It's a very bad idea to use `smartctl` in plugin. Super heavy, [Check this].(https://github.com/firehol/netdata/pull/1679)

I can add a chart with *csv file size (line in bind_rndc and isc_dncpd plugins) and warn the user if size > ..10mb?

**Comment by pschiffe** [comment]
@l2isbad no need for the chart with *csv file size, this problem should be handled in advance by logrotate if someone choose to use it. However, I'm wondering, are you able to assess disk health from the values in *csv files? I understand that calling `smartctl` is heavy, but it provides nice green/red indication of disk health. Maybe it's possible to get it some other way.

Anyway, for now I'm going to configure the smartd daemon to send me an email in case there's any problem with smart attributes of my disks.

Thanks for the support and keep up the great work!

**Comment by l2isbad** [comment]
> are you able to assess disk health from the values in *csv files?

Sure you can. But it depends on vendor/disk type.
We can add to monitor different smart attributes for different disks..
If someone will dig into it and suggest universal alarms if there are any. It will be cool.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
