### ISSUE TITLE
Override nginx_log pattern in config

### ISSUE THREAD

**Issue by netchild** [firehol/netdata#1847]
Hi,

seems my nginx log is in a format the normal regex doesn't like (I have additional info there for "nginx amplify" to measure backend response, see below). A crude test was to change the pattern in nginx_log.chart.py to:
    pattern = r'" ([0-9]{3}).*'
This gives me now some values. The best solution may be to be able to override the pattern in the config.

Here is what I have as logformat in nginx:
        log_format  main_ext '$remote_addr - $remote_user [$time_local] "$request" '
                ' $status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for" '
                'rt=$request_time ua="$upstream_addr" '
                'us="$upstream_status" ut="$upstream_response_time" '
                'ul="$upstream_response_length" '
                'cs=$upstream_cache_status' ;

A typical log line looks like this:
192.168.1.117 - - [25/Feb/2017:18:23:20 +0100] "GET /nginx_status HTTP/1.1"  200 106 "-" "Python-urllib/2.7" "-" rt=0.000 ua="-" us="-" ut="-" ul="-" cs=-
192.168.1.117 - - [25/Feb/2017:18:23:20 +0100] "GET /fpmstatus?full&json HTTP/1.1"  200 922 "-" "Python-urllib/2.7" "-" rt=0.001 ua="unix:/var/run/php.fcgi" us="200" ut="0.001" ul="927" cs=-

Maybe you want to add some graphs for those items too? May also be interesting to match "HTTP/x.y" and graph how many come via HTTP 1.0 / 1.1 / 2.0 or whatever.

Bye,
Alexander.

**Comment by l2isbad** [comment]
@netchild 
nginx_log plugin not used anymore and was removed.

New plugin for web log parsing is [web_log](https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py) ([configuration](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf))

[Wiki page](https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file) for web_log and [live demo](https://london.my-netdata.io/default.html#menu_web_log_nginx_netdata)

**Comment by ktsaou** [comment]
Sounds good. On my web servers I see only HTTP/1.1, but I guess this is because the application does not support anything else.

If you do it, replace the `.` with `_` at the dimension id and give it with a dot as the name.

**Comment by l2isbad** [comment]
$request" is always ends with `HTTP/x.y`, right?

**Comment by l2isbad** [comment]
added https://github.com/firehol/netdata/pull/1852

**Comment by ktsaou** [comment]
I think this is done.
