### ISSUE TITLE
Questions on installing Netdata in Centos 7 with Webmin/Virtualmin.

### ISSUE THREAD

**Issue by joejac** [firehol/netdata#1857]
Hello,
I saw Netdata demos and it is impressive. I have a small VPS with Webmin/Virtualmin control panel, my questions are:
1.- Can I install and run Netdata without having conflicts or disrupting Webmin/Virtualmin control panel?,
if I can install it without issues,
2.- Is there a tutorial on installing Netdata in Centos 7 with Webmin/Virtualmin?

Thanks in advance
Best regards
Jose

**Comment by ktsaou** [comment]
Hi, to install netdata you need ssh access. If you have it (even if not root), netdata will run. The installation wiki page has information how to do this.

In general, netdata does not interfere with anything else, although there are exotic kernels out there that disable certain kernel features (such as access to `/proc`) and may limit netdata significantly.

Unfortunately I am not familiar with webmin/virtualmin...

**Comment by joejac** [comment]
Thanks a lot ktsaou for your fast reply.
Yes I have access via ssh and I will use a normal user, not root, just in case.
Best regards
Jose

**Comment by pschiffe** [comment]
@joejac check this copr yum repo, it contains the latest rpm of netdata for CentOS and Fedora. With this repo, installation of netdata is as easy as:
```
curl -o /etc/yum.repos.d/tartare-netdata-epel-7.repo https://copr.fedorainfracloud.org/coprs/tartare/netdata/repo/epel-7/tartare-netdata-epel-7.repo
yum install netdata
systemctl enable --now netdata
```

**Comment by LeeNX** [comment]
I can confirm, that the above repo works on ClearOS v7.x.  
  
Two things come to mind, first, will this repo be kept up to date and second, where is the Ubuntu PPA with the latest release?  
  
Yes, I am a lazy Admin ... ;-)

**Comment by joejac** [comment]
Thanks a lot to all
Regards
Jose

**Comment by joejac** [comment]
Hello,
I followed these instructions:
https://github.com/firehol/netdata/wiki/Installation
And this tutorial:
https://www.youtube.com/watch?v=613FZMOp0A8
It works fine with Webmin/Virtualmin, I do not use it much, because Webmin already have some simple monitoring, that now that the VPS is running fine, is enough for me.

Anyway NetData was very useful at that time that I was debugging the server, and I consider NedData very impressive and outstanding. Thanks for maintaining and sharing NetData
Regards
Jose.

________________________________
