### ISSUE TITLE
[feature request] please register with IANA for an official tcp port - 19999/tcp is registered to another org

### ISSUE THREAD

**Issue by mailinglists35** [firehol/netdata#1862]
```
[root@el7 netdata]# grep 19999 /etc/services
dnp-sec         19999/tcp               # Distributed Network Protocol - Secure
dnp-sec         19999/udp               # Distributed Network Protocol - Secure
```

IANA port description for tcp/19999: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=19999

Wikipedia entry for protocol used for tcp port 19999: https://en.wikipedia.org/wiki/DNP3

How to register for a IANA tcp port: http://www.iana.org/form/ports-services

**Comment by mailinglists35** [comment]
yes, I know that chances of someone accidentally breaking a SCADA system by installing netdata on it are small... but, for the sake of correctness, netdata should have it's own registered tcp port.

**Comment by ktsaou** [comment]
Hi,

I applied to IANA for a port. However, I believe they will decline the request. The IANA port registry attempts to assign ports to different network protocols. netdata does not introduce a new protocol (the protocol is plain HTTP).

Let's see what they will respond...

**Comment by ktsaou** [comment]
Well, I had a few interactions with them.
Their final response is this:

> The observation that this protocol's interaction pattern is adequately served using standard protocols within the Web application stack which do not require a port assignment, and that in any case the details of communication after an initial HTTP(S) connection can be negotiated over HTTP(S), there is no need for a port assignment.

To my understanding IANA assigns ports to **protocols**, not applications. So, since netdata is using protocols that have already port assignments by IANA, there is no need (as IANA sees it) to assign a port to it.

**Comment by ktsaou** [comment]
The funny part, is that if we develop a new (and largely unecessary) protocol for netdata, IANA will probably assign a port to it :smile:

**Comment by mailinglists35** [comment]
> IANA assigns ports to protocols, not applications
hah, I didn't realise that. I always assumed the later. very good to know!
