### ISSUE TITLE
Help customizing a heath check for bursty network behavior on hosts with multiple interfaces.

### ISSUE THREAD

**Issue by pol** [firehol/netdata#1866]
I am trying to update the "packet storm" health check for a machine that is a master node of a cluster that also is connected to large parallel storage.  So, 1) the cluster will periodically send bursts of traffic back to the master, and B) users will periodically send/receive 10Gbps data to the parallel filesystem.  These both look like packet storms, but they are actually the system working as intended.

Before I disable the health checks entirely, could anyone give advice on what good functional alerts should look like on a system like this.  I think that error behavior would be:

1. default test on eth0 (the 1Gbps access interface)
  * solve with current test.
2. Unusually high bursts of packets on eth1 (the 1gbps management interface)
  * solve by adding a test to check for the maximum packet bursts over the last 30 minutes, and alert if you get more than 100% over the last 10s.  I wrote this one and it works ok, but it is applied to all interfaces (including eth0).
3. Very high sustained traffic on eth2 (the 10Gbps data interface).  I want to get alerts when someone is transferring giant data that uses up the 10Gbps interface for more than 15 minutes.  
  * Not sure how to write this one.  Normal traffic is bursty and huge. I think I would want something like "average bandwidth over the last 15 minutes that is greater than 200MB/s", but this isn't really a packet-storm type test.  Should I just disable the packet storm test for this interface?  Is it possible for a packet storm test to be relevant for this interface?

And finally: how do you target tests to interfaces?  Do I just make multiples of the tests and replace `families: *` with `families: eth0` or something like that? 

Thanks in advance!

**Comment by ktsaou** [comment]
Hi.

## how the `families` line works

`families` for interfaces are the interface names.

You can put positive and negative matches. For example:

### apply only to eth0

```
families: eth0
```

### apply to all veth*

```
families: veth*
```

### apply to all veth* except veth4

```
families: !veth4 veth*
```

### apply to all, except eth0 and veth*, but allow veth12

```
families: veth12 !veth* !eth0 *
```

You can add as any number of matches both positive and negative. They are evaluated left to right. The first that matches (positive or negative) is used.

---

> And finally: how do you target tests to interfaces? Do I just make multiples of the tests and replace families: * with families: eth0 or something like that?

Yes exactly.

Keep in mind the alarms can use cross chart metrics. For example we calculate average packet size, or consult IPv4 and IPv6 metrics to make a decision.

Anyway, if you have come up with an alarm and you need help to write it, I'll be glad to help...

**Comment by ktsaou** [comment]
regarding patterns: I forgot to mention you can put an asterisk anywhere, any number of times, like:

```
families: *e*n*p*1*s*4*
```

**Comment by pol** [comment]
Thanks, I will update my tests to target them to appropriate interfaces.

**Comment by ktsaou** [comment]
and you can test your patterns on the command line:

```sh
netdata -W simple-pattern '!eth0 eth*' eth2
RESULT: MATCHED - pattern '!eth0 eth*' matches 'eth2'

# netdata -W simple-pattern '!eth0 eth*' eth0
RESULT: NOT MATCHED - pattern '!eth0 eth*' does not match 'eth0'
```

(ok the message is probably misleading: `NOT MATCHED` = negative match, i.e. don't apply the alarm to it)

**Comment by pol** [comment]
Does a packet-storm test seem sensible on a 10Gbps storage interface? I think it will just alarm whenever someone copies data of an appreciable size.  

I don't need an alarm when someone copies 10s of GB of data, but when a user has a program that is reading/writing 100s of GB (sustained) I would like an alert.  Where is the appropriate category for this alert?  Is it a net.conf, ipv4.conf, or something else? 

Also, I was looking for another data source to alert from (instead use eth2.bandwidth or packets), and the UI appears to be broken for multiple interfaces.  It creates a chart for eth1, but none of the other interfaces has a chart.  Also, mousing over the chart data for eth1 updates the dashboard indicator for *all* of the interfaces. Should I create a separate ticket for this?

**Comment by ktsaou** [comment]
> Where is the appropriate category for this alert? Is it a net.conf, ipv4.conf, or something else?

anywhere you like, even your file. netdata reads all `.conf` files in `/etc/netdata/health.d`.

> I don't need an alarm when someone copies 10s of GB of data, but when a user has a program that is reading/writing 100s of GB (sustained) I would like an alert.

You can change the alarms in place too.

I see it compares the last 10secs with the last 1minute and issues a warning at 1000% and critical at 2000%: https://github.com/firehol/netdata/blob/b2b3ef2d2b3b8f04556c6cb9316eb0f44f6883d9/conf.d/health.d/net.conf#L102-L121

You can change the durations at the `lookup` lines. If you change the name of `1m_received_packets_rate` you will have to search/replace it too.

**Comment by ktsaou** [comment]
> Also, I was looking for another data source to alert from (instead use eth2.bandwidth or packets), and the UI appears to be broken for multiple interfaces. It creates a chart for eth0, but none of the other interfaces has a chart. Also, mousing over the chart data for eth0 updates the dashboard indicator for all of the interfaces. Should I create a separate ticket for this?

Yes please, and add screenshots.

**Comment by pol** [comment]
I just refreshed my UI after updating my interface alerts, and the UI bug went away, though the UI doesn't appear to capture virtual interfaces (eth0:1).  I will make another ticket for that it if it persists.  

Thanks for your help, I think you have resolved my issue.  I will try my hand at creating a new alert based on sustained bandwidth instead of packets for my 10Gbps interface.
