### ISSUE TITLE
cpufreq plugin doesn't work in RHEL/CentOS 7

### ISSUE THREAD

**Issue by pschiffe** [firehol/netdata#1867]
```
2017-02-27 20:07:14: python.d ERROR: cpufreq couldn't find a method to read cpufreq statistics
2017-02-27 20:07:14: python.d ERROR: cpufreq check() failed - disabling job
2017-02-27 20:07:14: python.d ERROR: DISABLED: cpufreq/None
```

I'm not sure if this is a distro or CPU specific, but I don't see any `time_in_state` or `scaling_cur_freq` file. On my machine, current freq is in the `cpuinfo_cur_freq` file:
```
# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
# uname -srv
Linux 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
# ll /sys/devices/system/cpu/cpu0/cpufreq
total 0
-r--r--r--. 1 root root 4096 Feb 27 20:16 affected_cpus
-r--------. 1 root root 4096 Feb 27 20:16 cpuinfo_cur_freq
-r--r--r--. 1 root root 4096 Feb 27 20:16 cpuinfo_max_freq
-r--r--r--. 1 root root 4096 Feb 27 20:16 cpuinfo_min_freq
-r--r--r--. 1 root root 4096 Feb 27 20:16 cpuinfo_transition_latency
-r--r--r--. 1 root root 4096 Feb 27 20:16 related_cpus
-r--r--r--. 1 root root 4096 Feb 26 00:55 scaling_available_governors
-r--r--r--. 1 root root 4096 Feb 27 20:16 scaling_driver
-rw-r--r--. 1 root root 4096 Feb 26 12:28 scaling_governor
-rw-r--r--. 1 root root 4096 Feb 27 20:16 scaling_max_freq
-rw-r--r--. 1 root root 4096 Feb 27 20:16 scaling_min_freq
-rw-r--r--. 1 root root 4096 Feb 27 20:16 scaling_setspeed
# cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq 
2325257
```

**Comment by l2isbad** [comment]
> time_in_state or scaling_cur_freq

Yes. This is the way it works now
https://github.com/firehol/netdata/issues/1629

@tycho is the guy who wrote the plugin.
Can you help?

**Comment by tycho** [comment]
@pschiffe What do `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver` and `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor` say?

**Comment by tycho** [comment]
Also, does your kernel have `CONFIG_CPU_FREQ_STAT` and `CONFIG_CPU_FREQ_STAT_DETAILS`?

**Comment by pschiffe** [comment]
```
# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
intel_pstate
# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
performance
# grep -e CONFIG_CPU_FREQ_STAT -e CONFIG_CPU_FREQ_STAT_DETAILS /boot/config-3.10.0-514.6.2.el7.x86_64
CONFIG_CPU_FREQ_STAT=m
CONFIG_CPU_FREQ_STAT_DETAILS=y
```

**Comment by tycho** [comment]
In my experience, the `intel_pstate` scaling driver has a mind of its own and doesn't seem to pay attention to `scaling_governor` It also makes some nonsensical choices. If you were to plot `cpuinfo_cur_freq` your graph would be all over the place and not provide you with any meaningful data.

You can add `intel_pstate=disable` on your kernel command line (add it to `GRUB_CMDLINE_LINUX` in `/etc/default/grub` and regenerate /boot/grub/grub.cfg with `grub-mkconfig -o /boot/grub/grub.cfg`) and it will fall back to `acpi-cpufreq` which is better behaved.

**Comment by pschiffe** [comment]
All right, but the cpufreq plugin should be able to graph the frequency no matter what scaling driver is used, shouldn't it? If the graph is all over the place, user will be at least able to act on it.

**Comment by tycho** [comment]
I don't think the graph going crazy will tell the user anything. `scaling_cur_freq` is already horribly inaccurate (since it's an instantaneous metric rather than bucketized residency data).

I guess we could do something like this:

```diff
diff --git a/python.d/cpufreq.chart.py b/python.d/cpufreq.chart.py
index c761aae8..6fe2efaa 100644
--- a/python.d/cpufreq.chart.py
+++ b/python.d/cpufreq.chart.py
@@ -96,6 +96,15 @@ class Service(SimpleService):
             self.assignment[cpu]['inaccurate'] = path
 
         if len(self.assignment) == 0:
+            # fall back to cpuinfo_cur_freq if scaling_cur_freq is missing (intel_pstate driver?)
+            for path in glob.glob(self.sys_dir + '/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq'):
+                path_elem = path.split('/')
+                cpu = path_elem[-3]
+                if cpu not in self.assignment:
+                    self.assignment[cpu] = {}
+                self.assignment[cpu]['inaccurate'] = path
+
+        if len(self.assignment) == 0:                                                                                                                                                                             
             self.error("couldn't find a method to read cpufreq statistics")                                                                                                                                       
             return False                                                                                                                                                                                          
              
```

I wonder if there's a nice way to express to netdata users that the graph data is horked because of the `intel_pstate` driver or `schedutil` governor. Right now we just show the data as-is, and the user may be left scratching their head as to why the cpufreq graph is all over the place.

**Comment by pschiffe** [comment]
I've tried your patch, but it somehow doesn't work, only thing I can get is this in `error.log`:
```
2017-03-01 22:56:03: charts.d: ERROR: cpufreq: module's 'cpufreq' check() function reports failure.
```

I meant that graph going crazy tells the user that he might want to investigate and learn about why it is that way.

**Comment by tycho** [comment]
Hmm. I'll give it a try on a machine with `intel_pstate` enabled and see what happens.

> I meant that graph going crazy tells the user that he might want to investigate and learn about why it is that way.
I know what you meant, I just don't think that's a lot for the user to go on. The only way they'd figure it out is by digging into the code. I'd prefer the problem be documented right in front of them.

**Comment by l2isbad** [comment]
@pschiffe 
2017-03-01 22:56:03: **charts.d:** ERROR: cpufreq: module's 'cpufreq' check() function reports failure.

**Comment by ktsaou** [comment]
Guys I am lost with this. Is there an issue to be solved?

**Comment by pschiffe** [comment]
@ktsaou the `cpufreq.chart.py` plugin should be probably updated to handle also the `intel_pstate` driver.

**Comment by l2isbad** [comment]
scaling_cur_freq is 400 root:root on all systems i checked

**Comment by ktsaou** [comment]
hm... this means it can only be done with a C binary that has the capabilities or is setuid to root...

**Comment by tycho** [comment]
Which is not worth the risk, IMO

**Comment by pschiffe** [comment]
I'm fine with closing this issue as wontfix, it's not that important to me.

**Comment by ktsaou** [comment]
ok, I am closing this.
