### ISSUE TITLE
Cpu's not sorted in correct order

### ISSUE THREAD

**Issue by wmandra** [firehol/netdata#1871]
On high CPU count servers, the individual cpu stats are sorted alphanumerically which lists:

cpu0, cpu1, cpu10, cpu11, ... cpu2, cpu20, cpu21

ideally these would sort in numeric order.

**Comment by yoursvivek** [comment]
This is also mentioned in #2263. I believe this is fixed now with PR #2281. Can be closed now.

**Comment by ktsaou** [comment]
yes, you are right.
thanks!
