### ISSUE TITLE
Nginx with user+pass auth

### ISSUE THREAD

**Issue by andreipietrosu** [firehol/netdata#1874]
Hello,

I'm trying to export some graphs in an unified dashboard but considering I'm using Nginx with user+pass in from I'm not able to access the data. Can you please advise how I can fix this?

P.S. the html unified dashboard is on the registry netdata server.

Sample gauge:

`<div data-netdata="system.active_processes"
                    data-host="https://netdata.example.com"
                    data-title="Active Processes"
                    data-chart-library="easypiechart"
                    data-width="100"
                    data-height="100"
                    data-after="-300"
                    data-points="150"
                    data-easypiechart-max-value="1000"
                    data-easypiechart-generate-gradient="[0, 300, 400]"
                    data-easypiechart-gradient-percent-color-0="#FFFFFF"
                    data-easypiechart-gradient-percent-color-10="#999900"
                    data-easypiechart-gradient-percent-color-100="#000000"
                    ></div>
`

The error:

system.active_processes: data download failed for url: https://netdata.example.com/api/v1/data?chart=system.active_processes&format=array&points=150&group=average&options=absolute|jsonwrap|nonzero&after=-300

**Comment by ktsaou** [comment]
Hi. To support nginx authentication, all your netdata servers should be behind the same authonticating nginx. You cannot have a custom dashboard with charts from multiple servers, where a few of them are authenticated and others are not.

Is that the question?

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
