### ISSUE TITLE
HTTP to HTTPS redirect behind Apache without rewrite, /netdata, alongside existing virtual hosts

### ISSUE THREAD

**Issue by ninjamonkey198206** [firehol/netdata#1879]
I've spent 12+ hours figuring out how to get netdata to use it's own fqdn, as I run a wildcard domain to my router using no-ip, with Apache as the webserver on Ubuntu 16.04. It's set to have *.example.com go to my router, with all web traffic ports forwarded to my server.  I've got ownCloud, phpvirtualbox, Plex, and netdata playing together nicely now.

I'll be adding Netdata as an option in a server installation, customization, and management script that I've been working on, now that I've got this worked out.

This configuration allows me to use netdata.example.com with http forwarding to https, which is proxied to netdata, without any need to adjust the firewall due to my default drop all firewall allowing localhost traffic, and no need to use /netdata in addition to a custom domain. (It's a pet peeve of mine)
It also seems to eliminate the need for the Rewrite entirely.

I've really only been working with Linux in general for about a year or so, so please let me know if I've got something poorly done or if there is a specific reason why this is a bad idea.

It assumes that users have used at least most of the instructions for properly hardening a server, and ensures http traffic and https traffic using netdata's fqdn is secured through SSL and properly forwarded.

For single public IP hosting multiple sites or systems, your default instructions are fine, with these possible exceptions:
(I use letsencrypt for my server certs, so I had to renew them and update them with the new fqdn after restarting apache, then reload apache again with the new certs before this worked properly)

Apache seems to select the default virtual host by the name of the conf file, using x-netdata-ssl.conf will ensure that netdata won't interfere with other site resolution.
```
sudo nano /etc/apache2/sites-available/x-netdata-ssl.conf
```

```
<VirtualHost *:80>

        ServerName netdata.example.com
        ServerAdmin somecallmetim@gmail.com

        DocumentRoot /usr/share/netdata/web/netdata

        Redirect permanent "/" "https://netdata.example.com/"

        ErrorLog ${APACHE_LOG_DIR}/netdata-error.log
        CustomLog ${APACHE_LOG_DIR}/netdata-access.log combined

</VirtualHost>

<VirtualHost *:443>

	ServerName netdata.example.com
	ServerAdmin somecallmetim@gmail.com

	DocumentRoot /usr/share/netdata/web/netdata

	SSLEngine On
	SSLCertificateFile              /etc/ssl/certs/example.pem
	SSLCertificateKeyFile           /etc/ssl/private/example.pem

	ProxyRequests Off
	ProxyPreserveHost On

	<Proxy *>
		Order deny,allow
		Allow from all
	</Proxy>

	# Local 127.0.0.1:19999 netdata server accessed with '/'
	ProxyPass "/" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30
	ProxyPassReverse "/" "http://127.0.0.1:19999/"

	<Location />
		AuthType Basic
		AuthName "Protected site"
		AuthUserFile /etc/apache2/.htpasswd
		Require valid-user
		Order deny,allow
		Allow from all
	</Location>

	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>

	<Directory /usr/lib/cgi-bin>
		SSLOptions +StdEnvVars
	</Directory>

	BrowserMatch "MSIE [2-6]" \
	nokeepalive ssl-unclean-shutdown \
	downgrade-1.0 force-response-1.0

	ErrorLog ${APACHE_LOG_DIR}/netdata-error.log
	CustomLog ${APACHE_LOG_DIR}/netdata-access.log combined

</VirtualHost>
```

To resolve properly without any issues:
```
sudo nano /etc/hosts
```
add
```
127.0.1.1       netdata.example.com netdata
```

That's it. This should work as long as 80 and 443 are listening for apache, and the DocumentRoot is set to the correct directory for the installation. Everything else I did was right from your instructions.

Again, I'm still somewhat of a noob, so if any of this is a really bad idea, please let me know.

**Comment by ktsaou** [comment]
Hi. I am sorry it needed such an effort...

Well, I am not an expert on this. I don't see any issues though...

**Comment by ninjamonkey198206** [comment]
No worries.

I've worked on electronics and Windows systems for years, and just started getting into programming, web work of any kind, and Linux fairly recently.

I'm teaching myself as I go, and I've learned that I'm not quite a Google-Fu Master yet. I've crammed more info into my head in the last year than I did in four years of college.

I just thought this would be helpful if I had gotten it right.

I'll have this built into the script I've been working on by the end of the week. I use it all the time for spinning up Ubuntu Server testing and dev VMs quickly. You're welcome to try it out for testing purposes. I'd just wait until I get 1.1.3 out with this and a few fixes in there.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you need help, post here.

**Comment by sundarraj-M** [comment]
Hi Ktsaou,
   I am running netdata on my dev server where i am having multiple domains running in the same server,Now my netdata dashboard is open to all whoc access the domain with port 19999 .How do i restrict it .Using .htpasswd should not affect the other domains .Trying to change the port but its not loading .Could you please suggest.

Thanks
Sundar

**Comment by ktsaou** [comment]
@sundarraj-M are your proxying netdata via apache? If yes, you should check what apache can do to restrict access to certain URL paths. Generally, you should be able to allow/deny access based on IP, or ask for user authentication on the netdata path.
