### ISSUE TITLE
Cannot understand option '-pidfile'.

### ISSUE THREAD

**Issue by nmaggioni** [firehol/netdata#188]
As of today, updating a week-old version to the latest brings up the the error in the title.
Strangely enough, it only seems to appear when using systemd: manually calling the executable in _/usr/sbin/netdata_ works fine (given the same options as the systemd service file and run under the same - root - user).

**Comment by ktsaou** [comment]
Check this: #156 and #163 

I guess it was required for making it more system friendly (each package maintainer can set the proper filename for their distribution).

Unfortunately, I changed (without thinking too much) the default used by the installer (it was `/var/run/netdata/netdata.pid` and now it is `/var/run/netdata.pid`).

Sorry... we are still learning...

**Comment by nmaggioni** [comment]
It looks more like there is an outdated file somewhere, the output of `journalctl` follows:

```
apr 05 23:24:38 netdata[15816]: Cannot understand option '-pidfile'.
apr 05 23:24:38 netdata[15816]: USAGE: /usr/sbin/netdata [-d] [-l LINES_TO_SAVE] [-u UPDATE_TIMER] [-p LISTEN_PORT] [-df debug flags].
apr 05 23:24:38 netdata[15816]: -c CONFIG FILE the configuration file to load. Default: /etc/netdata/netdata.conf.
apr 05 23:24:38 netdata[15816]: -l LINES_TO_SAVE can be from 5 to 864000 lines in JSON data. Default: 3600.
apr 05 23:24:38 netdata[15816]: -t UPDATE_TIMER can be from 1 to 3600 seconds. Default: 1.
apr 05 23:24:38 netdata[15816]: -p LISTEN_PORT can be from 1 to 65535. Default: 19999.
apr 05 23:24:38 netdata[15816]: -u USERNAME can be any system username to run as. Default: none.
apr 05 23:24:38 netdata[15816]: -ch path to access host /proc and /sys when running in a container. Default: empty.
apr 05 23:24:38 netdata[15816]: -nd or -nodeamon to disable forking in the background. Default: unset.
apr 05 23:24:38 netdata[15816]: -df FLAGS debug options. Default: 0x00000000.
apr 05 23:24:38 netdata[15816]: -stacksize BYTES to overwrite the pthread stack size.
apr 05 23:24:38 netdata[15816]: -pidfile FILENAME to save a pid while running.
```

The `-pidfile` option is not accepted, but it's listed in the available ones.
And if I manually run `sudo -u netdata /usr/sbin/netdata -pidfile /var/run/netdata/netdata.pid` everything is fine, just the systemd unit isn't cooperating.

No worries at all, keep up the good work :)
