### ISSUE TITLE
per-cpu graph Y axis does not go from 0 to 100, instead it spreads from 0 to maximum cpu % usage recorded

### ISSUE THREAD

**Issue by mailinglists35** [firehol/netdata#1884]
instead I expect per cpu graph to go from 0 to 100 like in system overview - cpu

![image](https://cloud.githubusercontent.com/assets/2054302/23551996/acf483fe-002a-11e7-9efa-7281fb63dbc1.png)

**Comment by l2isbad** [comment]
Ratio is much cleaner with auto scale. Why it's the problem for you?

**Comment by mailinglists35** [comment]
> Why it's the problem for you?

I don't expect to see Y axis from zero to currently max.
I expect Y axis to be from zero to maximum theoretical.

**Comment by mailinglists35** [comment]
> Ratio is much cleaner

maybe for you, but not for me too :(

**Comment by drMspamy** [comment]
Autoscale works fine if you only look at a single core. If you want to spot imbalances with load distribution across many cores the autoscale function could become misleading by by letting you compare things based on different scaling.

Maybe add a little slider to enable/disable autoscaling for this graph?

**Comment by archuserr** [comment]
this please! for the CPU and RAM, please have an option to show the full scale. i don't care if my CPU is bouncing between 3-5%, but the graph looks the same as if it was bouncing between 30%-100%.

**Comment by Bezod** [comment]
This would be very handy. The way it is now requires you to check the number assigned since the actual graph can look the same during 3% CPU usage and 90% CP usage. It defetes the purpose of using a graph.

**Comment by ktsaou** [comment]
I have switched the per core cpu charts to fixed range 0% to 100%.
It will be merged with #2121

**Comment by ktsaou** [comment]
merged it.
