### ISSUE TITLE
lxc containers only have cpu and mem metrics/graphs

### ISSUE THREAD

**Issue by mailinglists35** [firehol/netdata#1885]
I have latest git netdata on centos 7.3 host with centos 7.3 lxc containers 

For two containers I can see cpu and ram.
![image](https://cloud.githubusercontent.com/assets/2054302/23553484/fbf8549c-0031-11e7-92a1-415e6bd43635.png)

For a third container I see also disk:
![image](https://cloud.githubusercontent.com/assets/2054302/23553468/ecbed00a-0031-11e7-9e34-7f8174d3f5d9.png)

I don't understand why the third container also has disk (the second was cloned from first; first and third were deployed using `lxc-create -n name -t centos`). This makes me wondering if I'm missing other metrics that should be present for lxc containers. Is it because of not yet implemented issue #474 ?

```
rpm -aq|grep lxc
libvirt-daemon-lxc-2.0.0-10.el7_3.4.x86_64
lxc-1.0.9-1.el7.x86_64
lxc-extra-1.0.9-1.el7.x86_64
libvirt-daemon-driver-lxc-2.0.0-10.el7_3.4.x86_64
lxc-libs-1.0.9-1.el7.x86_64
python34-lxc-1.0.9-1.el7.x86_64
lxc-templates-1.0.9-1.el7.x86_64
lua-lxc-1.0.9-1.el7.x86_64
```

**Comment by ktsaou** [comment]
They are probably just zero. netdata tries not to create charts when all the collected information is just zero.
This is controlled by the `auto` setting in `netdata.conf`:

```
[plugin:cgroups]
	# enable cpuacct stat (total CPU) = auto
	# enable cpuacct usage (per core CPU) = auto
	# enable memory (used mem including cache) = auto
	# enable detailed memory = auto
	# enable memory limits fail count = auto
	# enable swap memory = auto
	# enable blkio bandwidth = auto
	# enable blkio operations = auto
	# enable blkio throttle bandwidth = auto
	# enable blkio throttle operations = auto
	# enable blkio queued operations = auto
	# enable blkio merged operations = auto
```

In all the above `auto` means `yes, except if the collected values are zero`.

So, step into the container and do something with its disk. Then hit F5 on the dashboard. It should show up.

**Comment by ktsaou** [comment]
btw, this is memory reduction feature for all plugins in netdata.
Without it, netdata would show up quite a few more charts.

**Comment by mailinglists35** [comment]
> netdata tries not to create charts when all the collected information is just zero

Whoa, that is a precious detail I must have missed. Thank you for the clarification!

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
