### ISSUE TITLE
Issue sending 'As Counted' to InfluxDB

### ISSUE THREAD

**Issue by masterapropos** [firehol/netdata#1886]
First of all, thank you for all that you do with this project. It helps our schools substantially.

When I send data to InfluxDB with the 'as counted' data source. It shows in Influx as wildly different than when it sends the averaged together metrics.

This is mainly for the metrics, prefix.system.ipv4.Out/In Octet

When its set to average, I get a sane value; however, when its set to send as counted, it is a number in the billions.

The data I've collected with netcat would suggest the data is always sending as follows.

Averaged: (put prefix.system.ipv4.OutOctets 1488553569 23641679777 host=hostname)
AsCounted: (put prefix.system.ipv4.OutOctets 1488550550 23617440784 host=hostname)

If you have any insight into this issue, it would be greatly appreciated.

**Comment by ktsaou** [comment]
In `as collected` mode, netdata collects the metrics and sends to the backend database whatever the source reports. The metrics are not normalized, interpolated, or in any way altered by netdata.

`Octets` reports `bytes`, as a counter value (`incremental` in netdata lingo, i.e. a value that is constantly incrementing). netdata, first finds the incremental difference to the last collected value and then converts this to kilobits/s by multiplying with 8 and dividing by 1024.

So, you have to use it as a `counter`, not a `gauge`. If you use `average`, then the metrics sent by netdata will always be `gauges` (netdata will do the conversion).

**Comment by masterapropos** [comment]
Is there a way to send these values as a gauge in the netdata configuration?

I can send this as an average for every 1 second; however, it seems like that would significantly increase the work the server being monitored is doing.

If there is already documentation on this, I apologize for the silly questions. If not and you're alright with it, I'd be happy to contribute updates to documentation with all that I've learned.

**Comment by ktsaou** [comment]
well, instead of `as collected` use `average` and set `update every` to the frequency you want metrics to be sent:

```
[backend]
    enabled = yes
    # type = graphite
    # destination = localhost
    data source = average
    # prefix = netdata
    # hostname = my-name
    update every = 10
    # buffer on failures = 10
    # timeout ms = 20000
```

**Comment by masterapropos** [comment]
I'd just like to update this with the resolution I found to my issue.

You can resolve counter graphing issues on Grafana by using a derivative graph. Just input the number of seconds you set 'as counted' to create an accurate graph.

It was silly I didn't realize this sooner. Thanks again!
