### ISSUE TITLE
php-fpm: gaps on certain charts

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1888]
https://horizon.scotthelme.co.uk/reporturi-shared-02/#menu_phpfpm_local_submenu_request_CPU

![image](https://cloud.githubusercontent.com/assets/2662304/23574197/b91e0970-0084-11e7-848d-1c203fce9cf9.png)

@l2isbad check the "request CPU" and "request memory" charts. They have gaps. But other charts of the PHP-FPM do not have gaps.

Something is happening...

**Comment by ktsaou** [comment]
It happens on all their servers I checked: https://horizon.scotthelme.co.uk/

**Comment by l2isbad** [comment]
Ok, i will try to fix it today
