### ISSUE TITLE
Amavisd-new SNMP 

### ISSUE THREAD

**Issue by l00v3** [firehol/netdata#1894]
Hello guys!
I try to gather statistical data from Amavisd-new through SNMP. I followed this post for enabling SNMP support in Amavisd-new:
http://bl0gg.ruberg.no/2017/01/enabling-snmp-support-in-amavisd-new/

I get normal output with all the statistical data when running snmpwalk command.

Then I configured `node.d/snmp.conf` from the wiki example so the right OID was in there (tried various combinations). But when I run `/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp` I get the following error:
```
2017-03-05 21:46:10: node.d.plugin: ERROR: snmp: 127.0.0.1: Received error = { [RequestFailedError: NoSuchName: 1.3.6.1.4.1.15312.2.1.1]
  name: 'RequestFailedError',
  message: 'NoSuchName: 1.3.6.1.4.1.15312.2.1.1',
  status: 2 } varbinds = undefined
DISABLE
```

Like stated above I tried various OID combinations and all gave error. There are logs that just confirm netdata accessing SNMP agent, but no other error.

Does somebody have any other idea what to try or what could be the problem with this?
Thank you very much!

**Comment by l2isbad** [comment]
> I get normal output with all the statistical data when running snmpwalk command

Can you post here snmpwalk output?

> right OID

Can you get information for that OID with `snmpget` (not snmpwalk)?

**Comment by l00v3** [comment]
So for start amavisd-snmp-subagent gives this output:
```
registering root OID 1.3.6.1.4.1.15312.2.1.1 for am.snmp
registering root OID 1.3.6.1.4.1.15312.2.1.2 for am.nanny
registering root OID 1.3.6.1.4.1.15312.2.1.3.1.1 for pf.maildrop
registering root OID 1.3.6.1.4.1.15312.2.1.3.1.2 for pf.incoming
registering root OID 1.3.6.1.4.1.15312.2.1.3.1.3 for pf.active
registering root OID 1.3.6.1.4.1.15312.2.1.3.1.4 for pf.deferred
```

If I use first OID from above output and run `snmpwalk`:
`snmpwalk -m +AMAVIS-MIB -c public -v2c 127.0.0.1 1.3.6.1.4.1.15312.2.1.1`

Output:
http://pastebin.com/MkRN9pVT


If i run `snmpget`:
`snmpget -v2c -m +AMAVIS-MIB -c public 127.0.0.1 1.3.6.1.4.1.15312.2.1.1`

Output:
```
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: AMAVIS-MIB::amavisStats
```


If i try  to use other OID with `snmpwalk`:

`snmpwalk -m +AMAVIS-MIB -c public -v2c 127.0.0.1 1.3.6.1.4.1.15312.2.1.3.1.1`

Output:

```
AMAVIS-MIB::mtaQueueEntriesMaildrop.0 = Gauge32: 0
```


If i run `snmpget`:
`snmpget -v2c -m +AMAVIS-MIB -c public 127.0.0.1 1.3.6.1.4.1.15312.2.1.3.1.1`

Output:
```
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: AMAVIS-MIB::mtaQueueEntriesMaildrop
```

Does this help? If you need more info I can dig further.

**Comment by l2isbad** [comment]
> snmpwalk - retrieve a subtree of management values using SNMP GETNEXT requests

You need to find appropriate OID. That is all.

Example:
1.3.6.1.2.1.31.1.1.1.6	ifHCInOctets


snmpwalk -v 2c <community> <host> 1.3.6.1.2.1.31.1.1.1.6 gives me a lot of output

iso.3.6.1.2.1.31.1.1.1.6.**1** = Counter64: 17011399394731603                                                                                                                                    
iso.3.6.1.2.1.31.1.1.1.6.**2** = Counter64: 3364836228931762                                                                                                                                     
iso.3.6.1.2.1.31.1.1.1.6.**3** = Counter64: 23004056367859139                                                                                                                                    
iso.3.6.1.2.1.31.1.1.1.6.**4** = Counter64: 0    
 

If i want to chart interface bandwidth i need to find exact OID (last number in my example - interface)

```
snmpget -v 2c <community> <host> 1.3.6.1.2.1.31.1.1.1.6 
iso.3.6.1.2.1.31.1.1.1.6 = No Such Instance currently exists at this OID
```

```
snmpget -v 2c <community> <host> 1.3.6.1.2.1.31.1.1.1.6.13
iso.3.6.1.2.1.31.1.1.1.6.13 = Counter64: 317211772080638
```

**Comment by l00v3** [comment]
Thank you for your answer.

Ok I think I did it right but still I don't get specific counters with snmpget, for example:

Firstly I run `snmpwalk -m +AMAVIS-MIB -c public -v2c 127.0.0.1 1.3.6.1.4.1.15312.2.1.1.2` and get:
```
AMAVIS-MIB::inMsgs.0 = Counter32: 3
AMAVIS-MIB::inMsgsInbound.0 = Counter32: 3
AMAVIS-MIB::inMsgsOutbound.0 = Counter32: 0
...
```

Then I run this first OID with `snmpwalk -m +AMAVIS-MIB -c public -v2c 127.0.0.1 1.3.6.1.4.1.15312.2.1.1.2.1` and get:
```
AMAVIS-MIB::inMsgs.0 = Counter32: 3
```
So far so good. 
But if I try to get this counter with `snmpget -v2c -m +AMAVIS-MIB -c public 127.0.0.1 1.3.6.1.4.1.15312.2.1.1.2.1` I get:
```
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: AMAVIS-MIB::inMsgs
```
What am I doing wrong here?
Did anybody got Amavis statistics through SNMP into NetData?

Any help would be very much appreciated.

Thank you very much!

**Comment by l2isbad** [comment]
> But if I try to get this counter with snmpget -v2c -m +AMAVIS-MIB -c public 127.0.0.1 1.3.6.1.4.1.15312.2.1.1.2.1 I get:

1.3.6.1.4.1.15312.2.1.1.2.1.**0**?

**Comment by l00v3** [comment]
`snmpget -v2c -m +AMAVIS-MIB -c public 127.0.0.1 1.3.6.1.4.1.15312.2.1.1.2.1.0`

Output:
```
AMAVIS-MIB::inMsgs.0 = Counter32: 4
```

Jup, it works, didn't know that I had to add 0. Thank you very much! 
I will try to configure it now with NetData. Will report back how it goes :)

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
