### ISSUE TITLE
awk: cmd. line:48: fatal: division by zero attempted

### ISSUE THREAD

**Issue by t-h-e** [firehol/netdata#1897]
I tried the newest git version as well as version 1.5.0 from the Arch Linux repo. I completely removed the previous installation, before installing from the repo.

I get a lot of these errors in the error.log: `awk: cmd. line:48: fatal: division by zero attempted`
And after a while the cpu gets stuck.
from journalctl:
`Feb 27 21:41:27 thanatos kernel: NMI watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [apps.plugin:29409]`

I'm not sure if it is related to this error, but the log also shows:

> 2017-03-06 09:52:44: apps.plugin: ERROR: Cannot process /proc/1/io (command 'systemd') (errno 13, Permission denied)
> 2017-03-06 09:52:44: apps.plugin: ERROR: Cannot process entries in /proc/1/fd (command 'systemd') (errno 13, Permission denied)

netdata is run as root. Permission on `/proc/1/io` are `400`

error log: https://justpaste.it/146vn

**Comment by ktsaou** [comment]
Hi.

1. Kernel CPU soft lockups cannot be triggered by applications. This is a hardware/driver issue. I suggest to google for it.

2. `awk` making a division by zero, is probably a `charts.d` module. Can you help us find which one? Execute `/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 MODULE`, where `MODULE` is one of `ap`, `apcupsd`, `hddtemp`, `nut`. Only these call `awk`.

3. `apps.plugin` runs with capabilities or setuid to root. Run `getcap /usr/libexec/netdata/plugins.d/apps.plugin` and `ls -l` the same file to verify this. Since you get permission denied errors on `/proc`, either neither of these are used, or your kernel has an exotic feature preventing `apps.plugin` from reading `/proc`. Could you please post `uname -a`?

**Comment by t-h-e** [comment]
1. Thanks for the info

2. Seems to be the `ap` module: https://jpst.it/USeA
The others just stop with the message `2017-03-06 11:14:42: charts.d: FATAL: main: No charts to collect data from.`, which seems fine.

3. 

> [pi@thanatos ~]$ getcap /usr/libexec/netdata/plugins.d/apps.plugin
> /usr/libexec/netdata/plugins.d/apps.plugin = cap_dac_read_search,cap_sys_ptrace+ep
> [pi@thanatos ~]$ ls -l /proc/1/io
> -r-------- 1 root root 0 Mar  5 11:45 /proc/1/io

uname -a: `Linux thanatos 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux`

**Comment by ktsaou** [comment]
ok. I will look into fixing `ap`.

Regarding `apps.plugin`, could you please run it by hand as root? does it still complain?
If it does not, could you please run it as user netdata? (`su -s /bin/sh netdata` to become user netdata).

**Comment by t-h-e** [comment]
No problems running `apps.plugin` by hand. Neither as root, nor as netdata.

Thanks for your help.

**Comment by ktsaou** [comment]
So, you run apps.plugin by hand and there are no issues, but when you run it with netdata you get errors about permission denied on certain proc files?

hm... this sounds like your systemd is removed the ability from the netdata process tree to use capabilities... Have you changed the default `netdata.service` file?

**Comment by t-h-e** [comment]
Ok, I tested it again.
The current github version works without problems, but if I install netdata from the Arch Linux repository (version 1.5.0), then I get the permission errors when running as netdata. It works fine when run as root.

**Comment by ktsaou** [comment]
> The current github version works without problems, but if I install netdata from the Arch Linux repository (version 1.5.0), then I get the permission errors when running as netdata. It works fine when run as root.

ok. Thanks. @@svenstaro have a look at this. It seems v1.5.0 has a permissions issue in ArchLinux.

@t-h-e I fixed the `ap` module division by zero. I'll merge it in a while (the ticket will close automatically).
