### ISSUE TITLE
Ubuntu Servre how to view http://127.0.0.1:19999/ ?

### ISSUE THREAD

**Issue by boromeke** [firehol/netdata#190]
Thanks！

**Comment by ktsaou** [comment]
Sorry, I don't understand the question.

**Comment by boromeke** [comment]
Hi, @ktsaou ！

My "Ubuntu Server" is not installed desktop environment。
So, I can not get through the monitoring data http://127.0.0.1:19999/.

Could the "domain.com:19999" to browse this form of monitoring data?

**Comment by svenstaro** [comment]
Yes.

**Comment by JaviSabalete** [comment]
Use proxy, or another pc on local network

http://192.168.X.X:19999

**Comment by 0xpr03** [comment]
ssh connection: putty: port forwarding of 19999.
Then you're good without external access.

**Comment by ktsaou** [comment]
Let's close this. @boromeke if you need help, just post.
