### ISSUE TITLE
How does netdata collect data?

### ISSUE THREAD

**Issue by talkyy** [firehol/netdata#1907]
Hello everybody,
Please help me.

**Comment by ktsaou** [comment]
A lot of different methods. It depends. Which data?

**Comment by talkyy** [comment]
Hi,
I want to know netdata's architecture and the way that netdata collects mectrics to show on webpage.
Please help me.
Thanks in advance.

**Comment by ktsaou** [comment]
My friend you are asking for a lot of documentation.

The general idea is:

1. netdata spawns threads and processes for data collection.
2. these threads collect information from files in `/proc`, by connecting to other processes APIs, by executing third party commands, sending queries to databases, application servers, etc. There is no limit on what netdata can do to collect data. We support whatever is needed. There are several APIs involved in this process (including a few netdata specific).
3. the collected metrics are processed (normalized, interpolated, etc) and stored in a round-robin time-series database with a fixed step.
4. web dashboards, query this database to retrieve data, which then are passed to javascript visualization libraries to render them on screen.

Why do you need all these? Are you writing a paper or something?

**Comment by talkyy** [comment]
Dear ktsaou,
Thanks a lot for your answers. I need all those because i'm a student, i have a  school project about monitoring a network system in real-time. So i need more documentation. I drew a picture about netdata's architecture as you say. Is it correct?
Again, thanks for your help.
![netdata_arch](https://cloud.githubusercontent.com/assets/26269505/23824476/321db994-06aa-11e7-82d5-a618789c6c8b.PNG)

**Comment by ktsaou** [comment]
yes, nice.

above and below the database there are 2 APIs:

1. above, is the web API. This gets requests, examines the database and responds in various formats. It also capable for reducing the data (calculating sums, averages, etc)

2. below, is the data collection API. There is a low-level `C` API (the internal netdata plugins use this) and a high level external plugins API (this is text based and uses internally the low-level `C` API).

You can link multiple netdata together by streaming data between them. On the sender side the low level `C` API spawns threads to stream data to another netdata. One the receiver side, the web API spawns threads connecting the sockets from the remote netdata to the external plugins API. Using this, netdata are able to mirror their data to remote netdata.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
