### ISSUE TITLE
Display value only in custom dashboard

### ISSUE THREAD

**Issue by DildoShwagginz** [firehol/netdata#1908]
Hi everyone,
I see that you can use different types of charts to fit your data, and you can even customize these charts with javascript.
Im not really into js and I have no idea how to solve this:
Trying to display the value of a chart in realtime, like the value inside an easypiechart but without the stuff around.
Is this possible?

**Comment by l2isbad** [comment]
Possible in [custom dashboard](https://github.com/firehol/netdata/wiki/Custom-Dashboards#extracting-dimension-values)

(query time numbers are dynamic)
![screenshot_20170308_210928](https://cloud.githubusercontent.com/assets/22274335/23703491/8c46b11e-0443-11e7-95e9-da7a701c948b.png)

**Comment by DildoShwagginz** [comment]
Thanks got it! Im using this:

<div data-netdata="netdata.server_cpu"
     data-show-value-of-user-at="cpu_user"
     ></div>
<span id="cpu_user"></span>

I have the real time value, but also the graph. 
Can I disable the it somehow or make it invisible?

**Comment by ktsaou** [comment]
Well... if the solution above is not right for you, possible other solutions are:

1. query netdata directly. The value you need is just an ajax call away.

2. you can create a custom chart type that will just display the latest value. Doing so may also allow hover on other charts, to refresh the right value on your chart too. `dashboard.js` has many chart types defined. You can attach yours, using javascript, without altering dashboard.js.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
