### ISSUE TITLE
Incorrect 'host' while sending data to kafka via logstash tcp input and the json codec

### ISSUE THREAD

**Issue by mushenrs** [firehol/netdata#1917]
I use https://github.com/firehol/netdata/pull/1815 New JSON Format, but 'host' field is not correct. How can I config it? Thank you very much.

Here is my config:
**netdata.conf**
[backend]
    enabled = yes
    data source = average
    type = json
    destination = localhost:6888
    prefix = netdata
    hostname = koumakan
    update every = 10
    buffer on failures = 10
    timeout ms = 20000

**logstash.conf**
input {
    tcp {
        port => 6888
        codec => "json"
    }
}

output {
    kafka {
        topic_id => "MonitorData"
        bootstrap_servers => "192.168.5.158:9092,192.168.5.159:9092"
    }
}

Message in Kafka is like this:
{
    "prefix": "netdata",
    "hostname": "koumakan",
    "chart_id": "system.swap",
    "chart_name": "system.swap",
    "family": "swap",
    "context": "system.swap",
    "type": "system",
    "units": "MB",
    "id": "free",
    "name": "free",
    "value": 0,
    "timestamp": 1489042150,
    "@version": "1",
    "@timestamp": "2017-03-09T06:49:10.009Z",
    **"host": "0:0:0:0:0:0:0:1"**,
    "port": 65011
}

**Comment by ktsaou** [comment]
Hi,

I guess you mean the bold entries. These are not netdata output. netdata submits all information up to `timestamp`. The rest is generated by kafka.

Check the code: https://github.com/firehol/netdata/blob/cab47afab39dd529fd06040111d314c2100e5183/src/backends.c#L283-L314

The hostname is submitted properly by netdata at the field `hostname`, not `host`.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
