### ISSUE TITLE
dashboard chart colors appear fixed when dimensions are added

### ISSUE THREAD

**Issue by MartijnBraam** [firehol/netdata#1920]
The module works great but the colors used for the dimentions in `web_log_apache.http_method` and `web_log_apache.http_version` are not great.

Both GET and POST are the same green color and in the http version chart the http1.1 and http2.0 traffic is also both green. This makes it impossible to differentiate the amount visually in the charts.

![screenshot from 2017-03-09 13-58-41](https://cloud.githubusercontent.com/assets/6928199/23751204/87a9acfa-04d0-11e7-902c-7a1b9f71ac50.png)

**Comment by l2isbad** [comment]
F5 ?

**Comment by MartijnBraam** [comment]
Okay that fixed it :) (also http 1.4?)

**Comment by ktsaou** [comment]
Yeah, this is a bug I haven't found the time to fix yet...

**Comment by slavikvin** [comment]
Hello, is there any progress on that issue? In our case we can`t easily press F5, so that kind of fix would be great for us.

**Comment by ktsaou** [comment]
I have made a few changed in color management these days. I haven't tested this case yet, but it may be fixed.

Can anyone test it?
Is it still there?

**Comment by l2isbad** [comment]
still here

**Comment by ktsaou** [comment]
hm... ok... I'll give it another try...
Do you have an easy way of reproducing it?

**Comment by l2isbad** [comment]
Yes.

```bash
/var/log/nginx]cat test2
100.100.0.1 - - [14/Feb/2017:08:11:17 +0900] "GOT /stub_status HTTP/1.5" 555 114 125 0.002 "-" "Python-urllib/2.7"
100.100.0.1 - - [14/Feb/2017:08:11:17 +0900] "GOT /stub_status HTTP/1.5" 555 114 125 0.002 "-" "Python-urllib/2.7"

[/var/log/nginx]cat test2 >> access.log
```

**Comment by ktsaou** [comment]
fixed it.
It is in #2121

**Comment by ktsaou** [comment]
merged it
