### ISSUE TITLE
apps.pwrite and apps.preads doesn't match what's seen in /proc/<pid>/io

### ISSUE THREAD

**Issue by nomius** [firehol/netdata#1926]
Hi,
  First of all, thanks for netdata, the tool is incredible!
  I'm monitoring a process IO performance and I might be interpreting apps.pwrites and apps.preads incorrectly or there might be a bug in netdata: https://gist.github.com/nomius/cf0dd764e3687661c8e67b910c6f5374

What should I sum up or which calculation should be done with the preads and/or pwrites to match what I see in /proc/<pid>/io? Because at first sight they are kinda hard to match or doesn't match.
Is netdata showing on every seconds the amount of bytes per second or how should be understand these numbers to match what we see in proc/<pid>/io?

Many thanks in advance and best regards,

**Comment by ktsaou** [comment]
Hi,

there are 2 levels of processing:

1. `apps.*` may aggregate many processes to each chart dimension. `apps.plugin` builds a process tree similar to `ps fax`. A few of the processes are matched by `apps_groups.conf` and others are not. The ones that are not matched directly are accounted first to their parents, and if they still cannot be accounted to any target, they are added to their children. `apps.plugin` tries hard not to throw away anything - so all processes must somehow be reported to the dimensions defined.

2. The values of `/proc/PID/io` are incremental. This means they always grow (every time the process reads or writes data, the numbers are incremented by the amount of data read or written). For `incremental` values, netdata finds their **rate**, by subtracting the previous reading from the current one and dividing the result with the duration between the 2 readings. It does this using microsecond calculations using `long double` variables (very precise). This **rate** is then interpolated to find the exact rate at second boundaries (so rate 0.5 at 00:00:00.5 and rate 1.5 at 00:00:01.5 are interpolated as 1.0 at 00:00:01). This is the final value shown at the charts.

A simple way to check netdata is right, is to do a large file transfer, see what is reported by netdata and verify the total amount transferred matches.

**Comment by ktsaou** [comment]
I forgot:

> the tool is incredible!

thank you!

**Comment by nomius** [comment]
Hi,
  Thanks for replying back!
  Should then the sum up of the values in `apps.*` higher than `/proc/PID/io`? Because in my case it isn't, in fact `/proc/PID/io` is waaaay higher than `apps.*`, in the first one I had close to 8MB but the sum of the values in `apps.*` is 10k:

```
root@localhost:~# cat /proc/13912/io
rchar: 5181600
wchar: 48997597
syscr: 6850
syscw: 98021
read_bytes: 8290304
write_bytes: 22040576
cancelled_write_bytes: 2707456
root@localhost:~#
```

vs.

```
root@localhost:~# curl 'http://localhost:19999/api/v1/data?chart=apps.preads' 2>/dev/null | grep '\(2017,2,10\|2017,2,9\)' | awk '/^[0-9]*/ {print $6}' | grep -v '^\(0\|null\),' | sed -e 's/,//g' | tr '\n' '+' | awk '{print $0"0"}' | bc -lq
10638.47848
```

Unless that . (dot) is not a decimal point...

**Comment by ktsaou** [comment]
The units of the apps.preads chart is `kilobytes/s`. So, netdata reports 10MB.

**Comment by ktsaou** [comment]
btw, this will be the same:

```
http://localhost:19999/api/v1/data?chart=apps.preads&format=ssv&options=unaligned&points=1&group=sum
```

i.e. sum all the dimensions and all the values of the whole apps.preads database and report just 1 value.

**Comment by nomius** [comment]
Awesome! I thought those were `bytes/s`. Now it's more clear :-)

Thanks a lot!

**Comment by ktsaou** [comment]
ok. nice!
