### ISSUE TITLE
feature request: Add -V or --version 

### ISSUE THREAD

**Issue by dtouzeau** [firehol/netdata#1927]
Difficult to enable to cron task if we cannot display the version by command line.
This to ensure that the task have correctly installed the new version.
This to maintain versioning on several systems...

**Comment by ktsaou** [comment]
hm... let me check:

1. `netdata`, exists as `-v`, added now `-V`.
2. `apps.plugin`, exists as `-v` and `version`, added now `-V`.
3. `freeipmi.plugin` didn't have anything, added the same with `apps.plugin`.

Thanks!

**Comment by ktsaou** [comment]
Keep in mind that git version use `git describe` to generate the version string.

These strings are:

```
program LAST_RELEASE-COMMITS_SINCE_LAST_RELASE-gHASH_rolling
```

So, you might get something like:

```
netdata 1.5.0-569-g45b53c3f_rolling
```

So, it is 569 commits after 1.5.0, the git commit hash is `45b53c3f`.

If you have mirrored git with `--depth=1`, you may get:

```
netdata 1.0.0-3823-g45b53c3f_rolling
```

So, it is 3823 commits after 1.0.0 - unfortunately, this is a side effect that cannot be avoided - it is the way `git` works.

**Comment by dtouzeau** [comment]
thanks !
