### ISSUE TITLE
NaN when using titleoids

### ISSUE THREAD

**Issue by gbarford** [firehol/netdata#1929]
Hi,

I found that when I used titleoids in the snmp module, I got NaN rather than port names.  The cause of the problem seems to be attempting to multiple a Strings returned from netsnmp.   I'm not sure the intent of the original code, however this modification fixes the issue with titleoids not working for me.

Giles

---  old-snmp.node.js	2017-03-11 09:21:07.347129394 +0000
+++ snmp.node.js	2017-03-11 11:45:01.903283373 +0000
@@ -272,7 +272,7 @@
                         if(__DEBUG === true)
                             netdata.debug(service.module.name + ': ' + service.name + ': found ' + service.module.name + ' value of OIDs ' + varbinds[i].oid + " = " + varbinds[i].value);
 
-                        if(varbinds[i].type === net_snmp.ObjectType.OctetString)
+                        if(varbinds[i].type === net_snmp.ObjectType.OctetString && service.snmp_oids_index[varbinds[i].oid].type !== 'title')
                             value = parseFloat(varbinds[i].value) * 1000;
                         else
                             value = varbinds[i].value;

**Comment by ktsaou** [comment]
Thanks for reporting this!

I was introduced with PR #1271 while attempting to fix #1236 

I added the fix you suggested.
