### ISSUE TITLE
Change wiki permissions

### ISSUE THREAD

**Issue by JaviSabalete** [firehol/netdata#193]
https://help.github.com/articles/changing-access-permissions-for-wikis/

I edited https://github.com/firehol/netdata/wiki/Running-behind-apache without restrictions

**Comment by ktsaou** [comment]
Thanks for doing this!

Well, I intentionally let everyone contribute to documentation. While this is not abused, I like it, actually I depend on it (this is also the reason I left several pages on the wiki empty)!

@philwhineray, github does not send notification when this happens.
Can we have something to monitor the changes?

**Comment by philwhineray** [comment]
According to [StackOverflow](http://stackoverflow.com/questions/8407917/how-can-you-track-or-be-notified-of-changes-to-github-wikis) we can either publish an rss feed or process notifications.

Notifications are what start off the builds, so I am comfortable adding this if you want, but we need to decide what to do when there is a notification (email firehol-devs, like the builds?)

If you already have an RSS reader that is possibly easier to manage.

**Comment by ktsaou** [comment]
RSS is good.

**Comment by philwhineray** [comment]
This is what you need:

https://github.com/firehol/netdata/wiki.atom

Shall we close for now?

**Comment by ktsaou** [comment]
ok. I have it.
I have seen a few commits on the wiki with spam. I have a backup of the entire wiki now, so I am going to leave it unrestricted.
Yes, we can close this.

**Comment by ktsaou** [comment]
It seems user @sxynblond2 emptied the wiki.

Restored from backup and restricted access to it.
