### ISSUE TITLE
Custom JS in index.html to support custom plugins

### ISSUE THREAD

**Issue by NMcCloud** [firehol/netdata#1936]
Is it possible to add a custom JS to index.html to support custom plugins.  I basically want to do simple customizing of the dashboard by adding descriptions to my various custom plugins to help administrators.  This should not be overwritten if netdata is upgraded.  If there is another method of doing this that survives upgrades, please let me know.
Thanks

**Comment by ktsaou** [comment]
Charts information is stored at [dashboard_info.js](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js).

You add to this file whatever you like, but unfortunately, there is no way currently to merge your custom information into it. So, it will be overwritten on the next update.

The right solution would be to add another file `custom_info.js` which would be shipped without any significant content. You could overwrite this file.

@alonbl I need your help on this: I need a file in the `web` directory, which should be installed with `make install` but should never be overwritten by it, allowing the users to overwrite it. Is there an official way to do this?

**Comment by alonbl** [comment]
> @alonbl <https://github.com/alonbl> I need your help on this: I need a
file in the web directory, which should be installed with make install but
should never be overwritten by it, allowing the users to overwrite it. Is
there an official way to do this?

Options:
1. install a different file and fallback to this file if file is missing -
this is the best.
2. create a complex install-data-hook that will avoid installing if exists
- bad approach.
3. define as config in downstream package (%config in rpm or config-protect
in gentoo, etc...)
4. probably you want to define it as symlink to /etc as people should put
configuration files in /etc.
5. have an environment to select what file to load, user can control
environment.
6. have configuration file that specify what to read.

**Comment by ktsaou** [comment]
hm... many options....

1. there will a 404 error on the web server. not good.
2. sounds complex too.
3. will depend on downstream to do it right - not always the case.
4. symlinks are not supported by the netdata web server (security reasons)
5. environment is not really used by netdata
6. **aha! this is nice**, a configuration option in `netdata.conf` to set the custom filename to read.

thank you @alonbl !

Let me try this now...

**Comment by ktsaou** [comment]
ok, here it is #1939 
Could you please test it?
To learn how to use it, read `web/dashboard_info_custom_example.js`

**Comment by NMcCloud** [comment]
Works like a charm.  Thank you :)
