### ISSUE TITLE
Is it possible to execute netdata remotely

### ISSUE THREAD

**Issue by ashyjaggs** [firehol/netdata#1938]
Is it possible to install netdata on one server and then monitor all servers connected to it like a hadoop clusters.

**Comment by ktsaou** [comment]
Hi. What does "all servers connected to it" mean? All serves are connected to all other servers - that's what the internet does :)

Generally, you need to collect metrics from each server. netdata is a data collector, so you need to install it everywhere.

Then, you can choose if you want each node to be autonomous, or you want to transfer the metrics to a central one. I suggest to use the autonomous mode (it is the default) when you can. It is simpler, there is nothing to configure and you will have the list of your servers at the `my-netdata` menu on the top left of every dashboard.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
