### ISSUE TITLE
Install failed,something wrong with the netdata-installer.sh

### ISSUE THREAD

**Issue by jay5571871** [firehol/netdata#194]
When I run the command 'sudo ./netdata-installer.sh --install /usr/local',it occured some errors. The error infomation is as below:
/usr/bin/install: cannot stat `./version.txt': No such file or directory

Can you help me solve the problem?

**Comment by philwhineray** [comment]
How did you get the source?

If you downloaded it as a tar from github that will happen. You need to either pull down a proper source package from https://firehol.org/download/netdata/ (the unsigned/master directory always comes in line with the latest git master) or do a `git clone`. Or, if you have done the latter, do a `git pull` to come up to date.

**Comment by philwhineray** [comment]
@ktsaou I can imagine this happening again in future.

I guess there are 3 options:

1. Update the `netdata-installer.sh` to detect the situation (no `web/version.txt` and no `.git` dir) and give the same advice as above before running.
2. Update the Makefile.am to do the same
3. Change the mechanism by which we get commit ids
4. Update the Makefile.am to generate an empty version.txt in this case

I can't think of any better way of doing (3). Git just doesn't seem set up to do that sort of processing.

I actually quite like (4). It would mean that the version check would need to be disabled but I can imagine some people/distros might want a way to do that anyway.

**Comment by ktsaou** [comment]
If version.txt was existing with the gitattribute ident, would this allow us to a version?

**Comment by ktsaou** [comment]
No it wouldn't. We would have the wrong version.

**Comment by ktsaou** [comment]
check this: https://github.com/MartinSeeler/auto-changelog-hook#how-it-works
It amends an updated changelog on every commit. Can we use the same procedure to amend version.txt?

(regarding automatic change log generation - I think this is better: https://github.com/skywinder/github-changelog-generator - but no automation is given)

**Comment by ktsaou** [comment]
Until we find a solution, if we do this:

```sh
version.txt:
        if test -d "$(top_srcdir)/.git"; then \
                if git --git-dir="$(top_srcdir)/.git" log -n 1 > v.tmp; then \
                        grep ^commit\  v.tmp | cut -d" " -f2 > version.txt; \
                        rm -f v.tmp; \
                else \
                        rm -f v.tmp; \
                        touch version.txt \
                fi; \
        else \
                touch version.txt \
        fi
```

so that an empty version.txt is created, will it suffice to bypass the installation problem?

**Comment by jay5571871** [comment]
@philwhineray @ktsaou Thank you all! I just do a git pull to update the source and install completed successfully.

**Comment by ktsaou** [comment]
ok, I also added these changes, to prevent this error in the future.

**Comment by ktsaou** [comment]
and I verified that downloading a zip file and using the installer, works.

**Comment by philwhineray** [comment]
Thanks Costa.

**Comment by Negasus** [comment]
Installation stopped at:
`make[2]: Leaving directory '/home/user/netdata/system'
Making all in web
make[2]: Entering directory '/home/user/netdata/web'
if test -d "../.git"; then \
	if git --git-dir="../.git" log -n 1 > v.tmp; then \
		grep ^commit\ v.tmp | cut -d" " -f2 > version.txt; \
		rm -f v.tmp; \
	else \
		rm -f v.tmp; \
		echo "0" > version.txt; \
	fi; \
else \
	echo "0" > version.txt; \
fi
`

**Comment by manei** [comment]
Same here, @Negasus. Same problem.

**Comment by ktsaou** [comment]
can you post the exact error you are receiving?

**Comment by Negasus** [comment]
After print this text in console, install process stopped.
Helps only Ctrl+C 

Also see this https://github.com/firehol/netdata/issues/232

**Comment by ktsaou** [comment]
fixed it.
Sorry!
