### ISSUE TITLE
Line Graph representation 

### ISSUE THREAD

**Issue by arulvelu21** [firehol/netdata#1941]
Hi I have created a custom dashboard , which posses only two information such as CPU and RAM . I need to use Line graph to represent both the data in same graph. Where x axis represents time and Y axis represents percentage used. Does netdata supports this multiple data in single chart ?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1140

**Comment by ktsaou** [comment]
Hi, unfortunately currently no.
I am closing this as duplicate of #1140. Let's continue the discussion there.
