### ISSUE TITLE
Merge multiple dimensions from different servers/charts into one graph

### ISSUE THREAD

**Issue by oernii** [firehol/netdata#1942]
Hi, is it possible to merge multiple dimensions into one chart somehow? For example creating a simple dashboard with one graph , which would contain for example 3 lines for 3 cpu-iowait for 3 different servers, each running a separate instance of netdata?

The dimensions use the same units and represend the same measurement on 3 servers.

**Comment by oernii** [comment]
Ugh, I just found:
#1941
#1140
#1523

**Comment by ktsaou** [comment]
Hi, yes this is a feature we need, but it is not there yet.
I am closing this in favour of #1140. Let's continue the discussion there.
