### ISSUE TITLE
netdata.service starts BEFORE mysql.service =  mysql charts are not showing

### ISSUE THREAD

**Issue by eLPy17** [firehol/netdata#1945]
Hi everyone!

I have this issue on my Ubuntu 16.04 with netdata + mysql python.d plugin after rebooting the system. Mysql charts are not showing because mysql python.d plugin tries DB connection before mysqld.sock is created.

To fix this issue, i've changed Mysql service name in **/etc/systemd/system/netdata.service** from:

> After=network.target httpd.service squid.service nfs-server.service mysql**d**.service named.service postfix.service

to:

> After=network.target httpd.service squid.service nfs-server.service mysql.service named.service postfix.service

Hope this helps someone.

**Comment by ktsaou** [comment]
merged the fix
