### ISSUE TITLE
netdata v1.6

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#1947]
I would like to release netdata v1.6 this weekend.

@vlvkobal @l2isbad do you have any reason to postpone this?

@l2isbad remember the "add new charts" page is a little bit behind (web_log, nginx_log, etc).

**Comment by l2isbad** [comment]
> do you have any reason to postpone this?

no

> "add new charts" page is a little bit behind

Yes. Not only the "add new charts" page. Python readme too.  Will do it before the weekend

**Comment by vlvkobal** [comment]
@ktsaou What do you think of merging #1912 before releasing v1.6? The PR is working and it's almost ready. It can be merged right now or after I rewrite 3 residual modules.

**Comment by ktsaou** [comment]
> @ktsaou What do you think of merging #1912 before releasing v1.6? The PR is working and it's almost ready. It can be merged right now or after I rewrite 3 residual modules.

That would be very nice. We just need to test it well before release. If you believe it will be well tested, let's do it. We can postpone the release for another week (which btw, is at the netdata birthday - March 31, 2016).

So, your call: do you want me to merge it now and decide for the release on Friday? Or you want to merge it after you have the new modules in place?

**Comment by vlvkobal** [comment]
One module left. I hope I'll finish it tomorrow.

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
This is up to now the changelog for v1.6.

There was an issue in freebsd support that holds me back from releasing 1.6 at #1972 
I think I have fixed the issue, but @vlvkobal should have a look.

---

### New to netdata? Check its demo: [http://my-netdata.io](http://my-netdata.io)

> [![User Base](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=persons&label=user%20base&units=null&value_color=blue&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![Monitored Servers](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=machines&label=servers%20monitored&units=null&value_color=orange&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![Sessions Served](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_sessions&label=sessions%20served&units=null&value_color=yellowgreen&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry)
> 
> [![New Users Today](http://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=persons&after=-86400&options=unaligned&group=incremental-sum&label=new%20users%20today&units=null&value_color=blue&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![New Machines Today](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_entries&dimensions=machines&group=incremental-sum&after=-86400&options=unaligned&label=servers%20added%20today&units=null&value_color=orange&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry) [![Sessions Today](https://registry.my-netdata.io/api/v1/badge.svg?chart=netdata.registry_sessions&after=-86400&group=incremental-sum&options=unaligned&label=sessions%20served%20today&units=null&value_color=yellowgreen&precision=0&v42)](https://registry.my-netdata.io/#menu_netdata_submenu_registry)
> 
> Release announced on [twitter](), [hacker news](), [reddit r/linux](),  [reddit r/sysadmin](), [reddit r/linuxadmin](), [reddit r/freebsd]()

## Central netdata is here!

This is the first release that supports real-time streaming of metrics between netdata servers.

netdata can now be:

- **autonomous host monitoring** (like it always has been)
- **headless data collector** (collect and stream metrics in real-time to another netdata)
- **headless proxy** (collect metrics from multiple netdata and stream them to another netdata)
- **store and forward proxy** (like **headless proxy**, but with a local database)
- **central database** (where metrics from multiple hosts are aggregated)

metrics databases can be configured on all nodes and each node maintaining a database may have a **different retention** policy and possibly run (even different) **alarms** on them.

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/2662304/23629551/bb1fd9c2-02c0-11e7-90f5-cab5a3ed4c53.png"/>
</p>

There are 4 settings that control what netdata can be:

1. `[global].memory mode` in `netdata.conf`, controls if a netdata will maintain a **local database** and the type of it. For more information check [Running a dedicated central netdata server](https://github.com/firehol/netdata/wiki/Memory-Requirements#running-a-dedicated-central-netdata-server).

2. `[web].mode` in `netdata.conf`, controls if netdata will **expose its API**, and the type of web server to enable (single or multi-threaded). Check [netdata.conf configuration for streaming](https://github.com/firehol/netdata/wiki/Replication-Overview#netdataconf-configuration).

3. `[stream].enabled` in `stream.conf`, controls if netdata will **stream its metrics to another netdata**. Check [stream.conf for sending metrics](https://github.com/firehol/netdata/wiki/Replication-Overview#streaming-configuration).

4. `[API KEY].enabled` in `stream.conf`, controls if netdata will **accept metrics from other netdata**. Check [stream.conf for receiving metrics](https://github.com/firehol/netdata/wiki/Replication-Overview#options-for-the-receiving-node).

Using the above, we support a lot of different configurations, like these:

target | memory<br/>mode | web<br/>mode | stream<br/>enabled | send to<br/>backend | local<br/>alarms | local<br/>dashboard
-------|:-----------:|:---:|:------:|:-------:|:---------:|:----:
**headless collector**|`none`|`none`|`yes`|not possible|not possible|no
**headless proxy**|`none`|not `none`|`yes`|not possible|not possible|no
**proxy with db**|not `none`|not `none`|`yes`|possible|possible|yes
**central netdata**|not `none`|not `none`|`no`|possible|possible|yes


### monitoring ephemeral nodes

netdata now supports monitoring autoscaled ephemeral nodes, that are started and stopped on demand (their IP is not known). 

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/2662304/23627295/e3569adc-02b8-11e7-9d55-4014bf98c1b3.png"/>
</p>

When the ephemeral nodes start streaming metrics to the central netdata, the central netdata will show register them at `my-netdata` menu on the dashboard, like this:

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/2662304/24080824/24cd2d3c-0caf-11e7-909d-a8dd1dbb95d7.png"/>
</p>

You can see this live at [https://build.my-netdata.io](https://build.my-netdata.io) (this server may not always be available for demo).

For more information check: [monitoring ephemeral nodes](https://github.com/firehol/netdata/wiki/monitoring-ephemeral-nodes).

### monitoring ephemeral containers and VM guests

netdata now cleans up container, guest VM, network interfaces and mounted disk metrics, disabling automatically their alarms too.

For more information check [monitoring ephemeral containers](https://github.com/firehol/netdata/wiki/monitoring-ephemeral-containers).

## apps.plugin ported for FreeBSD

**[Vladimir Kobal](https://github.com/vlvkobal)** has ported `apps.plugin` to FreeBSD.

netdata can now provide `Applications`, `Users` and `User Groups` under FreeBSD too:

Also, the CPU utilization of netdata under FreeBSD, is now a lot less compared to netdata v1.5.

See it live at our **[FreeBSD demo server](http://freebsd.my-netdata.io/#menu_apps)**.

## web_log plugin

[Ilya Mashchenko](https://github.com/l2isbad) has done a wonderful job creating a **unified web log parsing plugin** for all kinds of web server logs. With it, netdata provides real-time performance information and health monitoring alarms for web applications and web sites!

Requests by http status:
![image](https://cloud.githubusercontent.com/assets/2662304/22902194/ea0affc6-f23c-11e6-85f1-a4951dd4bb40.png)

Requests by http status code family:
![image](https://cloud.githubusercontent.com/assets/2662304/22901883/dea7d33a-f23b-11e6-960d-00a913b58936.png)

Requests by http status code:
![image](https://cloud.githubusercontent.com/assets/2662304/22901965/1a5d84ba-f23c-11e6-9d38-3deebcc8b879.png)

Requests bandwidth:
![image](https://cloud.githubusercontent.com/assets/2662304/22902266/245141d6-f23d-11e6-90f9-98729733e0da.png)

Requests timings:
![image](https://cloud.githubusercontent.com/assets/2662304/22902283/369e3f92-f23d-11e6-9359-53e5d4ecb18e.png)

URL patterns of interest (you configure the patterns):
![image](https://cloud.githubusercontent.com/assets/2662304/22902302/4d25bf06-f23d-11e6-844d-18c0876bdc3d.png)

Requests by http method:
![image](https://cloud.githubusercontent.com/assets/2662304/22902323/5ee376d4-f23d-11e6-8457-157d3f438843.png)

Requests by IP version:
![image](https://cloud.githubusercontent.com/assets/2662304/22902370/7091a770-f23d-11e6-8cd2-74e9a67b1397.png)

Number of unique clients:
![image](https://cloud.githubusercontent.com/assets/2662304/22902384/835aa168-f23d-11e6-914f-cfc3f06eaff8.png)

and a lot more, including **alarms**:


alarm|description|minimum<br/>requests|warning|critical
:-------|-------|:------:|:-----:|:------:
`1m_redirects`|The ratio of HTTP redirects (3xx except 304) over all the requests, during the last minute.<br/>&nbsp;<br/>*Detects if the site or the web API is suffering from too many or circular redirects.*<br/>&nbsp;<br/>(i.e. **oops!** *this should not redirect clients to itself*)|120/min|&gt; 20%|&gt; 30%
`1m_bad_requests`|The ratio of HTTP bad requests (4xx) over all the requests, during the last minute.<br/>&nbsp;<br/>*Detects if the site or the web API is receiving too many bad requests, including `404`, not found.*<br/>&nbsp;<br/>(i.e. **oops!** *a few files were not uploaded*)|120/min|&gt; 30%|&gt; 50%
`1m_internal_errors`|The ratio of HTTP internal server errors (5xx), over all the requests, during the last minute.<br/>&nbsp;<br/>*Detects if the site is facing difficulties to serve requests.*<br/>&nbsp;<br/>(i.e. **oops!** *this release crashes too much*)|120/min|&gt; 2%|&gt; 5%
`5m_requests_ratio`|The percentage of successful web requests of the last 5 minutes, compared with the previous 5 minutes.<br/>&nbsp;<br/>*Detects if the site or the web API is suddenly getting too many or too few requests.*<br/>&nbsp;<br/>(i.e. too many = **oops!** *we are under attack*)<br/>(i.e. too few = **oops!** *call the network guys*)|120/5min|&gt; double or &lt; half|&gt; 4x or &lt; 1/4x
`web_slow`|The average time to respond to requests, over the last 1 minute, compared to the average of last 10 minutes.<br/>&nbsp;<br/>*Detects if the site or the web API is suddenly a lot slower.*<br/>&nbsp;<br/>(i.e. **oops!** *the database is slow again*)|120/min|&gt; 2x|&gt; 4x
`1m_successful`|The ratio of successful HTTP responses (1xx, 2xx, 304) over all the requests, during the last minute.<br/>&nbsp;<br/>*Detects if the site or the web API is performing within limits.*<br/>&nbsp;<br/>(i.e. **oops!** *help us God!*)|120/min|&lt; 85%|&lt; 75%

For more information check: **[the spectacles of a web server log file](https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file)**.

## backends

netdata can now archive metrics to `JSON` backends (both push, by @lfdominguez, and pull modes).

## IPMI monitoring

netdata now has an IPMI plugin (based on [freeipmi](https://www.gnu.org/software/freeipmi/)) for monitoring **server hardware**.

The plugin creates (up to) 8 charts, based on the information collected from IPMI:

1. number of sensors by state
2. number of events in SEL
3. Temperatures CELCIUS
4. Temperatures FAHRENHEIT
5. Voltages
6. Currents
7. Power
8. Fans

It also supports alarms (including the number of sensors in **critical** state):

![image](https://cloud.githubusercontent.com/assets/2662304/23674138/88926a20-037d-11e7-89c0-20e74ee10cd1.png)

For more information, check [monitoring IPMI](https://github.com/firehol/netdata/wiki/monitoring-IPMI).

## New Plugins

**[Ilya Mashchenko](https://github.com/l2isbad)** continues to build python data collection plugins for netdata! **He rocks!**

- **web_log** for monitoring in real-time all kinds of web server log files @l2isbad
- **freeipmi** for monitoring IPMI (server hardware)
- **nsd** (the [name server daemon](https://www.nlnetlabs.nl/projects/nsd/)) @383c57
- **mongodb** @l2isbad
- **varnish** @l2isbad


## Improved Plugins

- **nfacct** reworked and now collects connection tracker information using netlink.
- **ElasticSearch** re-worked @l2isbad
- **mysql** re-worked to allow faster development of custom mysql based plugins (MySQLService) @l2isbad
- **SNMP**
- **tomcat** @NMcCloud
- **ap** (monitoring hostapd access points)
- **php_fpm** @l2isbad
- **postgres** @l2isbad
- **isc_dhcpd** @l2isbad
- **bind_rndc** @l2isbad
- **numa**
- **apps.plugin** improvements and freebsd support @vlvkobal
- **fail2ban** @l2isbad
- **smartd** (monitoring disk S.M.A.R.T. values) @l2isbad
- **freeradius** @l2isbad
- **nut** (monitoring UPSes)
- **tc** (Linux QoS) now works on qdiscs instead of classes for the same result (a lot faster) @t-h-e

## New and Improved Alarms
- **web_log**, many alarms to detect common web site/API issues
- **fping**, alarms to detect packet loss, disconnects and unusually high latency
- **cpu**, cpu utilization alarm now ignores `nice`

## New and improved alarm notification methods
- **HipChat** to allow hosted HipChat @frei-style
- **discordapp** @lowfive

## Dashboard Improvements
- dashboard now works on HiDPi screens
- dashboard now shows version of netdata
- dashboard now resets charts properly
- dashboard updated to use latest gauge.js release

## Other Improvements
- thanks to @rlefevre netdata now uses a lot of different high resolution system clocks.

netdata has received a lot more improvements from many more  contributors! (it was really a lot of work to dig into git log to collect all the above, so forgive me if I forgot to mention a few contributions and contributors).

Thank you all!

**Comment by ktsaou** [comment]
Also, releases are published in blogs, posted everywhere, etc.

So, if you believe something should be explained more or differently, or if you believe I have forgot something, please post you suggestions here.

**Comment by l2isbad** [comment]
`varnish` is not new. `smartd_log` is new. `web_log` + request per http version chart

**Comment by ktsaou** [comment]
thanks. updated it.

**Comment by ktsaou** [comment]
@l2isbad I think it might be better to keep a wiki page for the current changelog, to update at the time we merge something. That way we could keep links to related PRs, wiki pages we added, etc.

What do you think?

**Comment by l2isbad** [comment]
> What do you think?
If you think that will make things easier why not

**Comment by ktsaou** [comment]
just released it!

thank you all!

**Comment by ktsaou** [comment]
Issues found during 1.6.0 release:

1. Travis fails on macos for releases: https://travis-ci.org/firehol/netdata/jobs/213109374

2. @titpetric requested to also tag git releases with `v1.6` (without the minor version - required for docker hub to pick it up), but I don't know how to do it. @philwhineray could you please help?

3. release emails sent by github are empty and are also sent from @philwhineray . @philwhineray could you please help me fix these 2 issues? Ideally I would like release emails to have some release text I will prepare and sent from me.

**Comment by titpetric** [comment]
Disregard the tag about 1.6.0 - I'm pretty sure there should be an automated way to do this. 1.6 should keep in line with whatever 1.6.X tag is the latest, and I don't see why you'd have to create two tags for it (but I suspect you could?).

I added 1.6.0 to the titpetric/netdata image. I'm going to set up a `firehol/netdata` image that will take this repository directly - it should solve a number of problems, mainly that currently `titpetric/netdata` is the most popular image (and unofficial as well).

**Comment by ktsaou** [comment]
@titpetric thanks!

**Comment by philwhineray** [comment]
It will be possible to create an extra v1.6 tag if necessary but it could be a bit painful. If it is a full tag, then github and travis will want to create a separate release for it. A simple tag may or may not be sufficient for what you need. Let me know if any action is needed but for now I'm happy if a solution can be found with the three-digit versions.

**Comment by philwhineray** [comment]
For the other two, I have pushed a pair of commits.

The sed command is now fixed to work with non-GNU sed, so the OSX should build.

I have added "draft: true" to the release in the .travis.yml - hopefully that will solve the release issue. If not, we will either have to wait for a [travis fix](https://github.com/travis-ci/travis-ci/issues/6132) or think up some kind of workaround.

**Comment by ktsaou** [comment]
@philwhineray thanks!
