### ISSUE TITLE
TCP Monitoring : Getting Client Details

### ISSUE THREAD

**Issue by RiseEarly** [firehol/netdata#1954]
Hi,
       We are trying to monitor our TCP Sockets, We are able to make use of the TCP Aborts chart for the fluctuations on the connection. But unable to identify the client, which is causing this problem.

Just wanted to know if there is a way to achieve this in Netdata. IF this is already present, request to point me to the same. This would be a very useful feature, in proactively identifying clients causing the fluctuations.

Thanks.

**Comment by ktsaou** [comment]
Hi. Unfortunately netdata cannot identify the offending process. Currently netdata is only aware of the total.

**Comment by RiseEarly** [comment]
Ohh ok, is this something which is planned to take up ??

I can see that the file : /proc/net/nf_conntrack gives a detailed information about the TCP Handshake status.
[root@localhost net]# cat nf_conntrack
ipv4     2 tcp      6 299 ESTABLISHED src=172.16.3.77 dst=172.16.23.16 sport=49319 dport=22 src=172.16.23.16 dst=172.16.3.77 sport=22 dport=49319 [ASSURED] mark=0 secmark=0 use=3

[root@localhost net]# netstat -anp|grep ESTA
tcp        0     36 172.16.23.16:22             172.16.3.77:49319           ESTABLISHED 20270/sshd

So since it was from /proc/net, was wondering if this can be done through netdata itself.  Is this possible ??

**Comment by ktsaou** [comment]
I think that identifying the process for a specific TCP abort is more complex. We are not interested just about the currently open sockets. We are interested about the process that generated a specific TCP abort. I am not sure this can be identified with information from `/proc`.

It is more of a tracing issue for tools like https://github.com/iovisor/bcc and even for bcc, I am not sure it can be done...

**Comment by RiseEarly** [comment]
OK. Can there be a way of monitoring selected Clients ?? In addition to what we are seeing now, can we configure a IP:Port pair, which has to be monitored, so that we are looking at only specific endpoints.

**Comment by ktsaou** [comment]
Unfortunately not with netdata.

I have to admit that I don't know how to find the application related to a socket error, even by hand... Such errors are tracked inside the kernel and are exposed as system-wide counters. netdata collects and visualizes these kernel counters.

If I had a server with such errors, I would do this:

1. Look at bcc. This tool hooks itself to receive a log of all the kernel methods an application directly or indirectly calls. To correlate a socket error with a specific application, one should understand which kernel call handles this situation and then subscribe to receive events for it. So, if this correlation can be done in Linux, I think bcc would be the one to do it. But it requires quite some understanding of the kernel and the underlying layers, so I consider it: hard.

2. tcpdump enough traffic until it happens. Once it happens, I would attempt to find the offending socket with wireshark and based on the ports I would attempt to figure out the application.

I am not aware of any other way to trace socket errors.

If anyone has a better alternative, please post.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
