### ISSUE TITLE
To change the parameters of system.ram

### ISSUE THREAD

**Issue by arulvelu21** [firehol/netdata#1955]
Hi i am using netdata in my system. I could see the chart provided represents x axis as time and Y axis as MB used. Now i have used google chart to plot system.ram . I need to convert Y axis MB to percentage. Can this be done ? Please help

**Comment by ktsaou** [comment]
Here it is: https://jsfiddle.net/ktsaou/scf8rtoh/

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
