### ISSUE TITLE
SWAP alert weird ? 

### ISSUE THREAD

**Issue by kevincaradant** [firehol/netdata#1957]
Hi 

I noticed on my raspberry pi a bug / or a misunderstood about the SWAP used,  only since few days. 

I saw the same in the London test netdata server. 

![image](https://cloud.githubusercontent.com/assets/6093175/24011955/94abee2a-0a7c-11e7-85a6-be4ba2462ec6.png)

Why the % of SWAP is not the same ? 

Thank you in advance

**Comment by ktsaou** [comment]
Hi,

There are 3 alarms. Each has a different scope.

1. ![](https://london.my-netdata.io/api/v1/badge.svg?chart=system.swapio&alarm=30min_ram_swapped_out&refresh=auto)

   This alarm tries to find out if the system is actively swapping out. It will be triggered if the total swapped out size is about 20% of the system RAM.

2. ![](https://london.my-netdata.io/api/v1/badge.svg?chart=system.swap&alarm=used_swap&refresh=auto)

   This alarm will be triggered if the swap has critically low free space. It will be triggered when 90% of swap is used.

3. ![](https://london.my-netdata.io/api/v1/badge.svg?chart=system.swap&alarm=ram_in_swap&refresh=auto)

   This alarm tries to find if the system does not have enough RAM for what it has to do. It does this by comparing the amount the swap used, to the system RAM size. So, it says that the swap space used, is X% of the system RAM. It is triggered when the amount of swap used is 20% or more, of the system RAM (50%+ gives critical).

   This alarm is good for detecting performance issues in server environments. If is also effective for detecting memory leaks in applications.

**Comment by kevincaradant** [comment]
Explaination always very detailed, thank you :)

OK so in my case I will get always this alert because I installed ZRAM which compress the RAM to increase it in SWAPpart  ^^. SO I have 400MB of SWAP and 800MB of RAM via ZRAM. BTW Very useful for a Raspberry pi limited to 512mo / 1Go of RAM :).
