### ISSUE TITLE
[DOC] fping plugin

### ISSUE THREAD

**Issue by kevincaradant** [firehol/netdata#1958]
This doc: https://github.com/firehol/netdata/wiki/fping-Plugin

Have some little mistake on this part:
```
# time in milliseconds (1 sec = 1000 ms) to ping the hosts
# 200 = 5 pings per second
update_every=200
```

should be 

```
# time in milliseconds (1 sec = 1000 ms) to ping the hosts
# 200 = 5 pings per second
ping_every=200
```

`Then you need to edit /etc/netdata/netdata.conf like this:`

should be 

`Then you need to edit /etc/netdata/fping.conf like this:`

Let me know if I wrong.

Regards

**Comment by ktsaou** [comment]
thanks for reporting this!

For the first I think you are wrong. The whole config is this: https://github.com/firehol/netdata/blob/master/conf.d/fping.conf This file has both `update_every` and `ping_every`:

- `update_every` is the update frequency of the fping charts at the dashboard. Each host will be pinged 
- `ping_every` controls how many pings each host will receive for each data collection. So, if `update_every = 1` (sec) and `ping_every = 200` (ms), each host will be pinged 5 times for each data collection point.

For the second you are right. I fixed it.

**Comment by kevincaradant** [comment]
I copy/paste the content of the second `update_every` which should be `fping_every`.

**Comment by ktsaou** [comment]
You are right. Thanks!

**Comment by ktsaou** [comment]
I fixed it.

**Comment by kevincaradant** [comment]
Alright thank you, I close this issue :)
