### ISSUE TITLE
Question: Mysql replication lag and http error codes  monitoring 

### ISSUE THREAD

**Issue by divgwd** [firehol/netdata#1961]
Hi,
I wanted to know if it's possible to monitor mysql replication lag ?
Is there any config options to enable monitoring the http error codes in apache conf file??
Thanks in advance :)

**Comment by l2isbad** [comment]
discussion about mysql replication lag https://github.com/firehol/netdata/issues/1454

> monitoring the http error codes


http://london.my-netdata.io/default.html#menu_web_log_nginx_netdata_submenu_responses;theme=slate;help=true

**Comment by l2isbad** [comment]
'seconds behind master' = NOW() minus the TIMESTAMP set in Relay_Master_Log_File position Exec_Master_Log_Pos

**Comment by divgwd** [comment]
Thank you :)

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
