### ISSUE TITLE
new JSON backend uses an Elasticsearch keyword..

### ISSUE THREAD

**Issue by ThomasADavis** [firehol/netdata#1962]
The new JSON backend uses the word 'type', which is a special item in elasticsearch.

The 'type' field is used to select which properties in the index templates are used.  Having it be several dozen different values, but yet the same style for the rest of the fields causes a huge burden in elasticsearch.  You have to create an index template for each 'type' to be effective (especially  in v5x, where. where the 'text' vs. 'keyword' makes a huge performance difference.

We also use 'type' to generate indexes, which then proceeded to create many indexes.

Our current solution is to use logstash mutate plugin to move the 'type' field to 'plugin', and set the type field to 'netdata'.

Can this be changed or removed?

**Comment by ktsaou** [comment]
hi. it has been renamed in #1964
