### ISSUE TITLE
Self-cleaning obsolete charts

### ISSUE THREAD

**Issue by vlvkobal** [firehol/netdata#1967]
@ktsaou Doesn't `netdev_added` in `netdata/src/proc_net_dev.c` have to be decreased in `netdev_free()`?

Why did you stop using dictionaries for storing per chart data for network interfaces disks and file systems?

**Comment by ktsaou** [comment]
> Doesn't netdev_added in netdata/src/proc_net_dev.c have to be decreased in netdev_free()?

Thanks! fixed that.

> Why did you stop using dictionaries for storing per chart data for network interfaces disks and file systems?

The dictionaries are there, and are of extensive use by external plugins and web clients.

I am trying to have all internal plugins maintain pointers to charts and dimensions. Using dictionaries puts a constant CPU overhead on the system (each dictionary lookup is at least a few comparisons and an `strcmp()`, doing that for 1k dimensions means 1k strcmp/s).

Also, looking up the dictionary uses a read lock.

My main concern is embedded devices: I would like netdata to be perfect for IoT, so every extra bit in the iteration loop counts.

**Comment by ktsaou** [comment]
@vlvkobal I am preparing the release (for tomorrow). Do you have any reason to postpone it?

**Comment by vlvkobal** [comment]
> @vlvkobal I am preparing the release (for tomorrow). Do you have any reason to postpone it?

No.
