### ISSUE TITLE
plugin install

### ISSUE THREAD

**Issue by Vartkat** [firehol/netdata#1979]
Hello,

Seems weird but I don't find any website explaining in details how to install or activate a plugin. 
I'm trying to monitor a local postgres database on Ubuntu 16. 
Netdata is installed and running fine.
On demo sites I see the Postgres local icon and charts but it seems impossible to find a step by step tutorial on how to do this.

If someone had a few minutes to write a few lines saying which files to edit, where are these files and what parameter to write that would be great.

Seems to me everything, I mean every file is in the directories, I suppose there's a few line to uncomment and a few parameters to write but no clue to where I have to start. 

Every word in the wiki seems to me made for developers which I'm not.

Tanks in advance
Regards

**Comment by ktsaou** [comment]
Hi.

I am very sorry, this is so confusing. The wiki is editable by everyone, so if you can help us put the following information to the place you would expect it, please do.

You can check a plugin by running it on console.

To run the python plugin the same way netdata runs it, do this:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# execute python plugin in debug mode, for postgres only
/usr/libexec/netdata/plugins.d/python.plugin debug 1 postgres
```

Valid output should print lines starting with `CHART`, `DIMENSION`, `BEGIN`, `END`, `SET`. All other is debug output.

All netdata configuration is at `/etc/netdata`. Python modules (like the postgres one), use `/etc/netdata/python.d`. There is a file named `postgres.conf` in there.

**Comment by ktsaou** [comment]
I had a typo in the command. Get it again from my comment above.

**Comment by ktsaou** [comment]
I added this information to the [add more charts to netdata](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins) wiki page (the one that is linked below the menu of charts at the dashboard).

**Comment by l2isbad** [comment]
@Vartkat 

> Every word in the wiki

> made for developers

What about [postgres readme from the wiki page](https://github.com/firehol/netdata/tree/master/python.d#postgres) (check requirements!) and [postgres configuration file](https://github.com/firehol/netdata/blob/master/conf.d/python.d/postgres.conf)?
Have you read them? They are written in a simple manner and provides all information you need to run the plugin

**Comment by Vartkat** [comment]
Thanks for the advices. 

I've used your commands and modified my files according to the errors that was raised.
Finally here is the output 
_______
2017-03-21 10:52:32:  INFO: Using python v2
2017-03-21 10:52:32: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-21 10:52:32: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['postgres']
2017-03-21 10:52:32: python.d DEBUG: postgres: loading module configuration: '/etc/netdata/python.d/postgres.conf'
2017-03-21 10:52:32: python.d DEBUG: postgres: reading configuration
2017-03-21 10:52:32: python.d DEBUG: postgres/tcpipv6: job added
2017-03-21 10:52:32: python.d DEBUG: postgres/tcpipv4: job added
2017-03-21 10:52:32: python.d DEBUG: postgres/postgres: job added
2017-03-21 10:52:32: python.d DEBUG: postgres/tcp: job added
2017-03-21 10:52:32: python.d DEBUG: postgres/socket: job added
2017-03-21 10:52:32: python.d DEBUG: all job objects [<Service(tcpipv6, initial daemon)>, <Service(tcpipv4, initial daemon)>, <Service(postgres, initial daemon)>, <Service(tcp, initial daemon)>, <Service(socket, initial daemon)>]
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv6 'bool' object has no attribute 'cursor'
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv6 check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/tcpipv6
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv4 'bool' object has no attribute 'cursor'
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv4 check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/tcpipv4
2017-03-21 10:52:32: python.d ERROR: postgres_postgres 'bool' object has no attribute 'cursor'
2017-03-21 10:52:32: python.d ERROR: postgres_postgres check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/postgres
2017-03-21 10:52:32: python.d ERROR: postgres_tcp 'bool' object has no attribute 'cursor'
2017-03-21 10:52:32: python.d ERROR: postgres_tcp check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/tcp
2017-03-21 10:52:32: python.d ERROR: postgres_socket 'bool' object has no attribute 'cursor'
2017-03-21 10:52:32: python.d ERROR: postgres_socket check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/socket
2017-03-21 10:52:32: python.d DEBUG: overridden job names: []
2017-03-21 10:52:32: python.d DEBUG: all remaining job objects: []
2017-03-21 10:52:32: python.d FATAL: no more jobs
DISABLE
_______
Why  FATAL: no more jobs, if there's no more jobs why it doesn't deal with the found jobs ?

Costa, I would be honored to add some lines to the wiki if ever I was successful. 
As you see the level of precision I need is far from the explanations I found in the wiki. For example, at first, I was editing files in the github local copy and (at first) didn't understand that the files were installed in /etc. So when I mean "step by step explanations" it's a kind of "for dummies" and more I would like to understand what's going on. I'm dreaming of explanations saying "If you want to add a chart, the chart needs data, the collecting data is X, to activate the collection of data you have to edit the /etc/xyr/zzz.conf file and uncomment lines adding your own settings. You can verify the collection is well setup by looking at xxx. Then you can add the chart, to add the chart edit the file..., etc...".
Perhaps everything seems obvious for a lot of people but let me tell you I dealt with a lot of setup with things much more complicated like OpenVPN bridges. I'm not saying that the OpenVPN files are perfect but when you read the wiki and the comments in the files, it's easier to find your way.
For example, the content of the .conf files because of the indentation, and the lines that are not commented, makes it not clear about what to do. Do I have to uncomment some lines ? which ones, why the uncommented lines are there and do I need to let them as they are ? I don't know. Nothing tells me.

If I understood what to do I would be glad to write a few lines in the wiki to help others, or even suggest comment inside files, but for now I'm lost. The chart doesn't appear, I don't know if the collection of data is working, I don't even know if this is the right way of thinking about how Netdata is working.

Thanks for your help

Vart

**Comment by l2isbad** [comment]
@Vartkat 
1. sudo grep '[ ]trust' --before-context=1 /etc/postgresql/9.4/main/pg_hba.conf 
```
# Database administrative login by Unix domain socket
local   all             postgres                                trust
```
2. Restart postgres.service
3. Update netdata to the latest version
4. Restart netdata

**Comment by l2isbad** [comment]
> Why FATAL: no more jobs

All jobs fails..

```
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv6 'bool' object has no attribute 'cursor' # -< FAIL
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv6 check() failed - disabling job 
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/tcpipv6
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv4 'bool' object has no attribute 'cursor' # -< FAIL
2017-03-21 10:52:32: python.d ERROR: postgres_tcpipv4 check() failed - disabling job
2017-03-21 10:52:32: python.d ERROR: DISABLED: postgres/tcpipv4
```

I agree that he error description looks strange, but it's because of old version of the plugin

**Comment by Vartkat** [comment]
Whaof ! I succeeded and I think I understood a few things. 
Here are a few line to help others in case you want to add these to the Wiki.

After standard installation a few defaults plugins are running. For some additional plugins like postgres, there's no need to download and install any file. All files are already there, the only thing to do is to edit the .conf file to give some details about the chart you want.

In my case, to get the postgres chart. The only file to edit is 
/etc/netdata/python.d/postgres.conf
either
$ vi /etc/netdata/python.d/postgres.conf
or 
$ nano /etc/netdata/python.d/postgres.conf

As in many linux configuration files the lines with a # are comments.
For postgres you have to pick an access method, either socket, tcp4 or tcp6.
If your postgres server is on the same machine you can use socket acces (that's what I did).
The lines to add or to uncomment are :

socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'
    
These lines are telling Netdata to access your local postgres server as user postgres on the database postgres (seams obvious). As the user postgres is the master user, the Netdata chart will have access to all databases and you'll see the list on the right column of Netdata interface.

After editing the /etc/netdata/python.d/postgres.conf file, restart netdata :
$ sudo service netdata restart
and reload your Netdata webpage to see changes.

If ever the postgres chart is not there it could be that your postgres server is not allowing access. 
To check if so :
1) become user netdata
sudo su -s /bin/bash netdata

2) execute python plugin in debug mode, for postgres only
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 postgres

If the result is ending after a few lines, it means it's not working and the lines are telling you why. 
If it's working you'll never ending lines like :
__________
BEGIN postgres_TEST.xxx_db_stat_tuple_write 999863
SET xxx_tup_inserted = 69
SET xxx_tup_updated = 65
SET xxx_tup_deleted = 72
SET xxx_conflicts = 0
END
________

If the error is postgres server not allowing access, you have to tweak the /etc/postgresql/9.4/main/pg_hba.conf file.
If you're running an older version of postgresql server change the 9.4 version to 9.3 or 9.2.
Edit the file and find the line saying
local   all             postgres                                peer
and change it to :
local   all             postgres                                trust

Save your changes and restart the postgres server.
$ sudo service postgresql restart
then restart Netdata
$ sudo service netdata restart

and finally reload your netdata webpage in your browser.


As socket is not the only access method to the postgres server, if you choose tcp, you can specify and IP and doing so monitor a remote server, simply specifying its ip address.

________________

I tried with another user than postgres to not have all the databases listed but only one. Perhaps the access rights of the user I specified are too wide, but I'm still getting all databases including postgres.
What would be the method to have only one database ? 
Do I have to add a special user with only access to the specific database ? 
What rights do I have to give this user, do Netdata need to be able to write ?
Perhaps Netdata needs the master access (user postgres) to be able to gather infos ?

Thanks again

V.

**Comment by l2isbad** [comment]
> all the databases listed but only one

I can add an option to poll the only specified databases (this will exclude other databases from `database size` chart too).
Is this what you want? @Vartkat

**Comment by Vartkat** [comment]
I thought it would a matter of postgres user, I thought that if I add a postgres user with access to only one database and in Netdata con I specify this user and database, I would only have the one specified.

Couldn't it be this way ? Seems logical to me and I hope doesn't make you more work. Isn't it ?

**Comment by l2isbad** [comment]
> Couldn't it be this way ? 

Not sure how it should be. Not a postgres user.

This is all queries the plugin uses
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L23-L125

**Comment by Vartkat** [comment]
I'm no expert but I assume most of these requests are only available to master user i.e. postgres.
In this case, we'll have to precise in the .conf comments that user must be postgres and no other, and the database parameter would be the one you'll use to exclude other databases. 
This also means that if I want two databases I have to make another set of lines in the .conf file with another name.

How does it sound to you ?

**Comment by l2isbad** [comment]
?
```yaml
socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'
    database_poll: 'name1 name2 name3'
```

**Comment by Vartkat** [comment]
If I'm right about the obligation to be postgres user...

> socket:
>     name     : 'local'
>     user     : 'postgres'              #this must be postgres master user
>     database : 'postgres'          #this must be postgres master database
>     database_poll: 'name1 name2 name3'  # not implemented yet

Or any sentence clearer :-)

**Comment by l2isbad** [comment]
I mean i can add  `database_poll` option. This will exclude from charts **all**  databases except the ones are in `database_poll` (if '`database_poll` is not empty/not exist). 
Are you ok with that?

**Comment by Vartkat** [comment]
Deal !
Yes, it makes sense to me. I was just saying to add many, many, comments, to help dummies like me :-)

**Comment by l2isbad** [comment]
@Vartkat 
https://github.com/firehol/netdata/pull/2006

**Comment by ktsaou** [comment]
merged it

**Comment by ktsaou** [comment]
I think this can be closed now.

**Comment by brizzbane** [comment]
just wanna add, I found this via Google trying to get my initial postgresql charts going, this did it for me:

If the error is postgres server not allowing access, you have to tweak the /etc/postgresql/9.4/main/pg_hba.conf file.
If you're running an older version of postgresql server change the 9.4 version to 9.3 or 9.2.
Edit the file and find the line saying
local all postgres peer
and change it to :
local all postgres trust

Save your changes and restart the postgres server.
$ sudo service postgresql restart
then restart Netdata
$ sudo service netdata restart

Thans @Vartkat
