### ISSUE TITLE
 netdata: ERROR: IPv6 socket() on ip '::' port 19999 failed

### ISSUE THREAD

**Issue by wh211212** [firehol/netdata#1992]
Starting netdata...2017-03-22 09:02:49: netdata: ERROR: IPv6 socket() on ip '::' port 19999 failed. (errno 97, Address family not supported by protocol)
2017-03-22 09:02:49: netdata: ERROR: Cannot bind to ip '::', port 19999

**Comment by ktsaou** [comment]
Your system does not support ipv6.
netdata should be started though, using ipv4.
did it start?

**Comment by wh211212** [comment]
yes,my os off ipv6, netdata can start normal,and use normal ,I just want to ignore this errors, but in netdata.conf,I can't find which how to config netdata start using only ipv4.

**Comment by ktsaou** [comment]
oh, I see.

Change `bind to = 0.0.0.0:19999`. This will bind to ipv4 only.

**Comment by wh211212** [comment]
thank you, I'm config follow you said it's work. ...

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
