### ISSUE TITLE
can't use prometheus disk metrics about space & read writes

### ISSUE THREAD

**Issue by inattendu** [firehol/netdata#1993]
Hello !

Fisrt, thanks for this awesome work.

I'm actually building a grafana dashboard to get disk metrics persistent :

i actually want to monitor 
- sda Read & Write
- space used , reserved & free on /

For the read / Write metrics ; I have tried to use : 
- disk_sda_reads & disk_sda_writes 
but it seems to be an incremental counter, how to get kb/s value ?

And for used space I have tried :
- disk_space___avail & disk_space___used
but i don't understand the returned value, how can I convert it to human readable format ?

Maybe have I missed another important value in : /api/v1/allmetrics?format=prometheus

I will be happy to share the final dashboard that already display (RAM / CPU / SWAP & LOAD)

**Comment by ktsaou** [comment]
prometheus is getting the values "as-collected". This means these values are whatever the source reports. Are not normalized, interpolated, or in any way altered by netdata.

disk space metrics are not gauges in prometheus terminology. The source reports bytes, so just divide them with the unit you want.

disk performance metrics are counters in prometheus terminology, ie values that are constantly incrementing. The source reports bytes, so to have kb/s you have find the difference between 2 data collections, divide it with the number of seconds between them, and convert them to the units you are interested.

Unfortunately, I don't use prometheus myself, so I don't know prometheus specifics.

@ldelossa I guess these are pretty common questions. Do you have a document that describes how this is done?

**Comment by ktsaou** [comment]
fixed a typo. read it on gihub...

**Comment by ldelossa** [comment]
@inattendu I will be performing this same task in a few days so I can report back here. However what you'd want to do (at a high level) is find out what the counter's default metric is in (bytes/kb/mb/ etc..) and then you're going to have to perform the math yourself along with using a prometheus function for rate ( take a sample of the current counter, wait a defined period of time, take another sample, and compute the rate over time). Once you do this you'd want to multiple or divide by the correct value to transition from the base size metric (bytes/kb) to the target. 

I can provide an example using prometheus's default node exporter, the query would look like this:

```
irate(node_disk_bytes_written[60s]) / 1024
```

**Comment by inattendu** [comment]
Thanks a lot, it seems to be exactly what I needed.
I will share the result soon with a link to this thread.
 
Keep up the good work :1st_place_medal:
