### ISSUE TITLE
Wrong SENSOR DIR in centOS 7 fresh install.

### ISSUE THREAD

**Issue by Tangoes** [firehol/netdata#1995]
Well, I am having some issues trying to setup sensor chart... 

On centOS 7, as "strace sensors" says, sensor dir is "/sys/class/hwmon/..." (and not /sys/devices as netdata thinks).

Tryied with sensors.conf:
sensors_sys_dir="/sys/class/hwmon"
sensors_sys_depth=10

but still no luck:
charts.d: ERROR: sensors: no sensors found in '/sys/class/hwmon/'

Maybe permissions issue?
Maybe a fix with a symbolic link?

Paste of my "starce sensors":
http://pastebin.com/4P5drBJE

**Comment by l2isbad** [comment]
@Tangoes 
Did you install `lm-sensors/lm_sensors`? (debian/arch)
If no please install it and restart `netdata.service`

**Comment by Tangoes** [comment]
Yes, it was installed with netdata prerequisites, but didnt run sensors-detect:

[root@server ~]# sensors
i350bb-pci-0300
Adapter: PCI adapter
loc1:         +61.0°C  (high = +120.0°C, crit = +110.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +43.0°C  (high = +81.0°C, crit = +91.0°C)
Core 0:         +43.0°C  (high = +81.0°C, crit = +91.0°C)
Core 1:         +40.0°C  (high = +81.0°C, crit = +91.0°C)
Core 2:         +37.0°C  (high = +81.0°C, crit = +91.0°C)
Core 3:         +37.0°C  (high = +81.0°C, crit = +91.0°C)
Core 4:         +42.0°C  (high = +81.0°C, crit = +91.0°C)
Core 5:         +40.0°C  (high = +81.0°C, crit = +91.0°C)

nct6776-isa-0a30
Adapter: ISA adapter
Vcore:         +1.07 V  (min =  +0.54 V, max =  +1.49 V)
in1:           +1.81 V  (min =  +1.62 V, max =  +1.99 V)
AVCC:          +3.28 V  (min =  +2.96 V, max =  +3.63 V)
+3.3V:         +3.28 V  (min =  +2.96 V, max =  +3.63 V)
in4:           +1.52 V  (min =  +1.35 V, max =  +1.65 V)
in5:           +1.25 V  (min =  +1.13 V, max =  +1.38 V)
3VSB:          +3.31 V  (min =  +2.96 V, max =  +3.63 V)
Vbat:          +3.22 V  (min =  +2.96 V, max =  +3.63 V)
fan1:            0 RPM  (min =  700 RPM)  ALARM
fan2:            0 RPM  (min =  700 RPM)  ALARM
fan3:            0 RPM  (min =  700 RPM)  ALARM
fan4:            0 RPM  (min =  700 RPM)  ALARM
fan5:            0 RPM  (min =  700 RPM)  ALARM
SYSTIN:        +46.0°C  (high = +75.0°C, hyst = +70.0°C)  sensor = thermistor
CPUTIN:        +53.0°C  (high = +95.0°C, hyst = +92.0°C)  ALARM  sensor = thermistor
AUXTIN:        +22.5°C    sensor = thermistor
PECI Agent 0:   +0.0°C  (high = +95.0°C, hyst = +92.0°C)
cpu0_vid:     +0.000 V
intrusion0:   ALARM
intrusion1:   ALARM

[root@server ~]#

**Comment by Tangoes** [comment]
After run sensors-detect, I have the same sensors.

```
[root@server ~]# ls /sys/devices/
breakpoint  ide1         pci0000:ff  rbd       uncore_cbox_0  uncore_cbox_3  uncore_ha     uncore_imc_2  uncore_qpi_0   uncore_r3qpi_0  virtual
cpu         LNXSYSTM:00  platform    software  uncore_cbox_1  uncore_cbox_4  uncore_imc_0  uncore_imc_3  uncore_qpi_1   uncore_r3qpi_1
ide0        pci0000:00   pnp0        system    uncore_cbox_2  uncore_cbox_5  uncore_imc_1  uncore_pcu    uncore_r2pcie  uncore_ubox
[root@server ~]# 
```

**Comment by l2isbad** [comment]
Please do (change path if needed)
```bash
[/opt/netdata/usr/libexec/netdata/plugins.d]./python.d.plugin debug 1 sensors  
```

**Comment by Tangoes** [comment]
Is it supposed to end?

`BEGIN sensors.i350bb-pci-0300_temperature 999932
SET i350bb-pci-0300_temp1 = 60000
END 
BEGIN sensors.coretemp-isa-0000_temperature 999932
SET coretemp-isa-0000_temp1 = 38000
SET coretemp-isa-0000_temp2 = 38000
SET coretemp-isa-0000_temp3 = 35000
SET coretemp-isa-0000_temp4 = 32000
SET coretemp-isa-0000_temp5 = 34000
SET coretemp-isa-0000_temp6 = 38000
SET coretemp-isa-0000_temp7 = 35000
END 
BEGIN sensors.nct6776-isa-0a30_temperature 999932
SET nct6776-isa-0a30_temp1 = 45000
SET nct6776-isa-0a30_temp2 = 52000
SET nct6776-isa-0a30_temp3 = 22500
END 
BEGIN sensors.nct6776-isa-0a30_voltage 999932
SET nct6776-isa-0a30_in0 = 1056
SET nct6776-isa-0a30_in1 = 1816
SET nct6776-isa-0a30_in2 = 3312
SET nct6776-isa-0a30_in3 = 3296
SET nct6776-isa-0a30_in4 = 1512
SET nct6776-isa-0a30_in5 = 1248
SET nct6776-isa-0a30_in7 = 3312
SET nct6776-isa-0a30_in8 = 3216
END 

BEGIN netdata.plugin_pythond_sensors 999932
SET run_time = 2
END

2017-03-22 12:48:32: python.d DEBUG: sensors sensors updated in 2 ms
2017-03-22 12:48:32: python.d DEBUG: sensors sleeping for 0.996377944946 secs to reach frequency of 1.0 secs, now: 1490183313.0  next: 1490183314.0  penalty: 0
BEGIN sensors.i350bb-pci-0300_temperature 1000001
SET i350bb-pci-0300_temp1 = 60000
END 
BEGIN sensors.coretemp-isa-0000_temperature 1000001
SET coretemp-isa-0000_temp1 = 38000
SET coretemp-isa-0000_temp2 = 38000
SET coretemp-isa-0000_temp3 = 35000
SET coretemp-isa-0000_temp4 = 32000
SET coretemp-isa-0000_temp5 = 34000
SET coretemp-isa-0000_temp6 = 38000
SET coretemp-isa-0000_temp7 = 35000
END 
BEGIN sensors.nct6776-isa-0a30_temperature 1000001
SET nct6776-isa-0a30_temp1 = 45000
SET nct6776-isa-0a30_temp2 = 52000
SET nct6776-isa-0a30_temp3 = 22500
END 
BEGIN sensors.nct6776-isa-0a30_voltage 1000001
SET nct6776-isa-0a30_in0 = 1056
SET nct6776-isa-0a30_in1 = 1816
SET nct6776-isa-0a30_in2 = 3312
SET nct6776-isa-0a30_in3 = 3296
SET nct6776-isa-0a30_in4 = 1512
SET nct6776-isa-0a30_in5 = 1248
SET nct6776-isa-0a30_in7 = 3312
SET nct6776-isa-0a30_in8 = 3216
END 

BEGIN netdata.plugin_pythond_sensors 1000001
SET run_time = 1
END

2017-03-22 12:48:33: python.d DEBUG: sensors sensors updated in 1 ms
2017-03-22 12:48:33: python.d DEBUG: sensors sleeping for 0.997454881668 secs to reach frequency of 1.0 secs, now: 1490183314.0  next: 1490183315.0  penalty: 0
`

**Comment by l2isbad** [comment]
No. It's for debugging purpose. You can run any python plugin by hand and see the output from it.

The output in your case means that the data is collected. 

Are you sure there is no "sensors" thing at the dashboard?

![screenshot_20170322_205334](https://cloud.githubusercontent.com/assets/22274335/24196590/a8377d78-0f41-11e7-9a94-57fc61747eb2.png)

**Comment by Tangoes** [comment]
Nope.

![seleccion_129](https://cloud.githubusercontent.com/assets/19514845/24196889/bc019f88-0eff-11e7-8083-39ed2263f875.png)

```
cat /var/log/netdata/error.log | grep sensor

2017-03-22 10:29:42: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2017-03-22 13:00:37: charts.d: ERROR: sensors: no sensors found in '/sys/class/hwmon/hwmon1'.
2017-03-22 13:00:37: charts.d: ERROR: sensors: module's 'sensors' check() function reports failure.
```
Also removed comment in line with sensors=force, still not working.

**Comment by l2isbad** [comment]
`charts.d` is bash plugins not python. 

```bash
grep sensors error.log
2017-03-22 20:15:13: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in /opt/netdata/etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2017-03-22 20:15:13: python.d INFO: CHECKED OK: sensors
```

**Comment by Tangoes** [comment]
Yes, all bash is disabled by default... but I enabled it, to give it a try... not working.

**Comment by l2isbad** [comment]
Well. Here is the code, you can execute it from python interpreter.

1. cd [/opt/netdata/usr/libexec/netdata/python.d/python_modules] ()
[/opt/netdata/usr/libexec/netdata/python.d/python_modules]ls lm_sensors.py 
lm_sensors.py

2. run from shell ```python'''

3.
```python
import lm_sensors as sensors

LIMITS = {
    'temperature': [-127, 1000],
    'voltage': [-127, 127],
    'current': [-127, 127],
    'fan': [0, 65535]
}

TYPE_MAP = {
    0: 'voltage',
    1: 'fan',
    2: 'temperature',
    3: 'power',
    4: 'energy',
    5: 'current',
    6: 'humidity',
    7: 'max_main',
    16: 'vid',
    17: 'intrusion',
    18: 'max_other',
    24: 'beep_enable'
}
sensors.init()
data =dict()
for chip in sensors.ChipIterator():
    prefix = sensors.chip_snprintf_name(chip)
    for feature in sensors.FeatureIterator(chip):
        sfi = sensors.SubFeatureIterator(chip, feature)
        for sf in sfi:
            val = sensors.get_value(chip, sf.number)
            break
        typeName = TYPE_MAP[feature.type]
        if typeName in LIMITS:
            limit = LIMITS[typeName]
            if val < limit[0] or val > limit[1]:
                continue
            data[prefix + "_" + str(feature.name.decode())] = int(val * 1000)
```

4. data - collected data
```python
>>> from pprint import pprint
>>> pprint(data)
{'acpitz-virtual-0_temp1': 27800,
 'acpitz-virtual-0_temp2': 29800,
 'asus-isa-0000_fan1': 0,
 'coretemp-isa-0000_temp1': 51000,
 'coretemp-isa-0000_temp2': 51000,
 'coretemp-isa-0000_temp3': 49000,
 'coretemp-isa-0000_temp4': 46000,
 'coretemp-isa-0000_temp5': 44000,
 'nct6791-isa-0290_fan1': 0,
 'nct6791-isa-0290_fan2': 2299000,
 'nct6791-isa-0290_fan3': 0,
 'nct6791-isa-0290_fan4': 0,
 'nct6791-isa-0290_fan5': 0,
 'nct6791-isa-0290_in0': 872,
 'nct6791-isa-0290_in1': 1016,
 'nct6791-isa-0290_in10': 224,
 'nct6791-isa-0290_in11': 192,
 'nct6791-isa-0290_in12': 1008,
 'nct6791-isa-0290_in13': 1016,
 'nct6791-isa-0290_in14': 232,
 'nct6791-isa-0290_in2': 3312,
 'nct6791-isa-0290_in3': 3312,
 'nct6791-isa-0290_in4': 1008,
 'nct6791-isa-0290_in5': 2024,
 'nct6791-isa-0290_in6': 816,
 'nct6791-isa-0290_in7': 3408,
 'nct6791-isa-0290_in8': 3344,
 'nct6791-isa-0290_in9': 1008,
 'nct6791-isa-0290_temp1': 5000,
 'nct6791-isa-0290_temp10': 0,
 'nct6791-isa-0290_temp2': 45000,
 'nct6791-isa-0290_temp3': 36500,
 'nct6791-isa-0290_temp4': 98000,
 'nct6791-isa-0290_temp5': 96000,
 'nct6791-isa-0290_temp6': 98000,
 'nct6791-isa-0290_temp7': 51000,
 'nct6791-isa-0290_temp8': 0,
 'nct6791-isa-0290_temp9': 0}

```

**Comment by l2isbad** [comment]
@Tangoes 
there is no such thing like a `DIR`

**Comment by Tangoes** [comment]
Ok, so I´ll keep trying how to get sensor charts working.

**Comment by l2isbad** [comment]
Actually if `./python.d.plugin debug 1 sensors` not fails the charts should be at the dashboard

**Comment by Tangoes** [comment]
I understand what you say, but as I said before: debug works, but not in dashboard... Do not worry, I´ll keep trying, if I find the issue, I´ll report.
