### ISSUE TITLE
Possible variable-data source mismatch

### ISSUE THREAD

**Issue by SamBosch** [firehol/netdata#2000]
I suspect that the variables are in the wrong order in: 
src/proc_net_snmp6.c

        rrddim_set(st, "sent", Ip6OutRequests);
        rrddim_set(st, "received", Ip6InReceives);
        rrddim_set(st, "forwarded", Ip6InDelivers);
        rrddim_set(st, "delivers", Ip6OutForwDatagrams);

Netdata returns positive results for IPv6 forwarding, yet the Ip6OutForwDatagrams returns zero...

Should Ip6InDelivers and Ip6OutForwDatagrams swap positions?

**Comment by ktsaou** [comment]
It seems you are right.

**Comment by ktsaou** [comment]
merged the fix.
