### ISSUE TITLE
Monitoring of individual VMs

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2004]
(Fresh install of netdata 1c421f8e under ubuntu 16.04)

Right now, if I have a bunch of KVM VMs running, they are rolled up together under applications as "VMs".

~~~
# apps_groups.conf
VMs: vbox* VBox* qemu*
~~~

It would be great if they could be split out, for example by looking at the `-name` or `-uuid` argument to qemu.  This would then identify which VM is generating the most CPU load and the most disk activity.

This would imply being able to split an application group down into subgroups, e.g. by parsing the name/args against some sort of regexp or in a plugin.  Then the VMs would be stacked as different applications.  Alternatively, each VM could have its own set of graphs, like containers do.

It looks like #1045 implemented something like this if the kvm process is inside its own cgroup.  Unfortunately, the virtualisation software I'm using (ganeti) doesn't start each VM inside its own cgroup hierarchy. Under the "systemd Services" heading, all the resources are booked to a single "ganeti" service.

**Comment by ktsaou** [comment]
libvirtd registers each VM in their own cgroup when running with systemd.
To see if it does, run `systemd-cgtop`. Does it show the VMs? If yes, update your netdata and they should up (I changed the default settings yesterday to enable them by default).

Keep in mind you may also need to enable certain systemd features: https://github.com/firehol/netdata/wiki/monitoring-systemd-services (on a few systems, systemd has cgroup accouninting for memory and disk disabled).

If you don't have cgroups for your VMs, then you can do something like this in `apps_groups.conf`:

```
myVM1: *XXXXXXX*
myVM2: *YYYYYYY*
```

etc. When you add 2 asterisks (begin and end), apps.plugin searches the whole command line, not just the process name. So, match whatever you like from the command line (I would use the UUID).

**Comment by candlerb** [comment]
> libvirtd registers each VM in their own cgroup when running with systemd.

Unfortunately ganeti doesn't use libvirtd.

> myVM1: *XXXXXXX*

Thanks, I think that'll work (albeit manual maintenance required)
