### ISSUE TITLE
system.interrupts

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#2005]
Hello,

We want to setup a ccomplementary monitoring script that wil record same data as : system.interrupts cumulated with cpature of top processes, and soem more so that to identify easily which users can cause troubles on server....

What is exact command line to get the data value given in system.interrupts of netdata ?

Thanks

**Comment by ktsaou** [comment]
1. You can query the API: https://github.com/firehol/netdata/wiki/REST-API-v1 this provides a lot of functionality, including looking up past data, calculating averages or sums, etc.

2. You can get the latest snapshot of all metrics with shell scripting: `http://netdata.ip:19999/api/v1/allmetrics`. You can also append `?format=json` to get all the metrics in json.

Generally, the API is quite rich. This is what the dashboards use.

**Comment by ktsaou** [comment]
You can also find what calls the dashboard makes, by pressing F12 on your browser and switching to the network tab. This will reveal all the calls.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
