### ISSUE TITLE
Doesn't play well with mod_evasive

### ISSUE THREAD

**Issue by nigelhorne** [firehol/netdata#2011]
Using a proxy through Apache all works fine unless I enable mod_evasive in which case I get 403 errors after a bit of time and widgets fail to load.  Mod_evasive e-mails me that it's blocked a DDOS.

**Comment by ktsaou** [comment]
well, each chart refresh is a request, so a lot of requests on a dashboard.

I read about evasive here: https://www.digitalocean.com/community/tutorials/how-to-protect-against-dos-and-ddos-with-mod_evasive-for-apache-on-centos-7

it says:

> `DOSPageCount` is the limit for the number of requests for the same page per page interval (usually set to one second) by an IP address. Once the threshold for that interval has been exceeded, the IP address of the client will be added to the blocked list. **The default value is set quite low at 2**.

well, netdata would normally do up to 20-30 requests/s per client...

> `DOSSiteCount` is the limit for the total number of requests for the same website by an IP address per site interval (defaults to 1 second).

same as above.

I think the defaults of mod evasive are wrong.

**Comment by nigelhorne** [comment]
I've upped the DOSPageCount to 30.  I'll let you know how I get on.  Thanks for the prompt reply.

**Comment by ValkiryXDA** [comment]
Anyone figured out a decent config for this yet? Sorry to revive a dead issue.

**Comment by ktsaou** [comment]
Have you tried to increase the thresholds to 20?
