### ISSUE TITLE
data-title - how do I change the text size?

### ISSUE THREAD

**Issue by nigelhorne** [firehol/netdata#2015]
I would like to increase the point size for data-title.  But all the doc says is:

"Chart title
You can overwrite the title of the chart using this:
...."

See http://bandsman.mooo.com/netdata/demosites3.html for my example - the label on the 3 dygraphs is very small.

**Comment by ktsaou** [comment]
Hi,

I suggest to add a `div` above each chart with a bigger title.

Unfortunately, changing the embedded chart title needs quite some work. Yes, I know we should support this kind of customizations...

**Comment by nigelhorne** [comment]
I guessed it may be that, but I couldn't figure out the magic div command to put in.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
