### ISSUE TITLE
Fails to build on FreeBSD12

### ISSUE THREAD

**Issue by nigelhorne** [firehol/netdata#2016]
> Sorry! netdata failed to build...
> 
> You many need to check these:
> 
> 1. The package uuid-dev (or libuuid-devel) has to be installed.
> 
>    If your system cannot find libuuid, although it is installed
>    run me with the option:  --libs-are-really-here
> 
> 2. The package zlib1g-dev (or zlib-devel) has to be installed.
> 
>    If your system cannot find zlib, although it is installed
>    run me with the option:  --libs-are-really-here
> 
> 3. You need basic build tools installed, like:
> 
>    gcc make autoconf automake pkg-config
> 
>    Autoconf version 2.60 or higher is required.
> 
> If you still cannot get it to build, ask for help at github:
> 
>    https://github.com/firehol/netdata/issues

Yet I have them:

> root@pi2b:/home/njh/src/netdata # which gcc
> /usr/local/bin/gcc
> root@pi2b:/home/njh/src/netdata # which automake
> /usr/local/bin/automake
> root@pi2b:/home/njh/src/netdata # which autoconf
> /usr/local/bin/autoconf
> root@pi2b:/home/njh/src/netdata # which pkg-config
> /usr/local/bin/pkg-config
> root@pi2b:/home/njh/src/netdata # 
> root@pi2b:/home/njh/src/netdata # autoconf --version
> autoconf (GNU Autoconf) 2.69
> Copyright (C) 2012 Free Software Foundation, Inc.
> License GPLv3+/Autoconf: GNU GPL version 3 or later
> <http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by David J. MacKenzie and Akim Demaille.

**Comment by nigelhorne** [comment]
And in case you're wondering, I did run this:

pkg install bash e2fsprogs-libuuid git curl autoconf automake gcc pkgconf pidof

**Comment by ktsaou** [comment]
@nigelhorne sorry for the delay... It seems I missed this issues somehow...

@vlvkobal could you please check this?

**Comment by vlvkobal** [comment]
I've tried to install `netdata` on `FreeBSD-12.0-CURRENT-amd64-20170210-r313561` and `FreeBSD-12.0-CURRENT-amd64-20170323-r315864` snapshoots. I can't replicate the error. Everything is working fine.

@nigelhorne try to use `--libs-are-really-here` option.

**Comment by nigelhorne** [comment]
Doesn't help.

This is on "FreeBSD pi2b.bandsman.co.uk 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r305028: Tue Aug 30 05:53:50 UTC 2016     root@releng3.nyi.freebsd.org:/usr/obj/arm.armv6/usr/src/sys/RPI2  arm"

**Comment by ktsaou** [comment]
@nigelhorne could you please post the whole build log? If we see the error code, we may be able to identify the issue.

**Comment by nigelhorne** [comment]
Here you go.  I hope there's something in here which helps point it out!

./netdata-installer.sh

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

 --- Run autotools to configure the build environment --- 
[netdata]# ./autogen.sh 
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
autoreconf-2.69: running: /usr/local/bin/autoheader-2.69 --force
autoreconf-2.69: running: automake --add-missing --copy --force-missing
autoreconf-2.69: Leaving directory `.'
 OK   

[netdata]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O2\ -W\ -Wformat=2\ -Wswitch\ -Wshadow\ -Wwrite-strings\ -Wuninitialized\ -Wall\ -pipe 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... armv6-unknown-freebsd12.0
checking host system type... armv6-unknown-freebsd12.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/njh/src/netdata':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
 FAILED   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

# cat config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by netdata configure 1.6.0-44-gd67bc79c_rolling, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe

## --------- ##
## Platform. ##
## --------- ##

hostname = pi2b.bandsman.co.uk
uname -m = arm
uname -r = 12.0-CURRENT
uname -s = FreeBSD
uname -v = FreeBSD 12.0-CURRENT #0 r305028: Tue Aug 30 05:53:50 UTC 2016     root@releng3.nyi.freebsd.org:/usr/obj/arm.armv6/usr/src/sys/RPI2 

/usr/bin/uname -p = armv6
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /root/bin
PATH: /sbin
PATH: /usr/sbin
PATH: /usr/local/bin
PATH: /usr/local/sbin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2716: checking whether to enable maintainer-specific portions of Makefiles
configure:2725: result: no
configure:2801: checking for a BSD-compatible install
configure:2869: result: /usr/bin/install -c
configure:2880: checking whether build environment is sane
configure:2935: result: yes
configure:3086: checking for a thread-safe mkdir -p
configure:3125: result: ./install-sh -c -d
configure:3132: checking for gawk
configure:3162: result: no
configure:3132: checking for mawk
configure:3162: result: no
configure:3132: checking for nawk
configure:3148: found /usr/bin/nawk
configure:3159: result: nawk
configure:3170: checking whether make sets $(MAKE)
configure:3192: result: yes
configure:3221: checking whether make supports nested variables
configure:3238: result: yes
configure:3368: checking build system type
configure:3382: result: armv6-unknown-freebsd12.0
configure:3402: checking host system type
configure:3415: result: armv6-unknown-freebsd12.0
configure:3483: checking for gcc
configure:3499: found /usr/local/bin/gcc
configure:3510: result: gcc
configure:3739: checking for C compiler version
configure:3748: gcc --version >&5
gcc (FreeBSD Ports Collection) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3759: $? = 0
configure:3748: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/lto-wrapper
Target: armv6-portbld-freebsd12.0
Configured with: /wrkdirs/usr/ports/lang/gcc/work/gcc-4.9.4/configure --disable-multilib --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc49 --libexecdir=/usr/local/libexec/gcc49 --program-suffix=49 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc49/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --disable-libgcj --enable-languages=c,c++,objc,fortran --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc49 --build=armv6-portbld-freebsd12.0
Thread model: posix
gcc version 4.9.4 (FreeBSD Ports Collection) 
configure:3759: $? = 0
configure:3748: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3759: $? = 1
configure:3748: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3759: $? = 1
configure:3779: checking whether the C compiler works
configure:3801: gcc -O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe   conftest.c  >&5
configure:3805: $? = 0
configure:3853: result: yes
configure:3856: checking for C compiler default output file name
configure:3858: result: a.out
configure:3864: checking for suffix of executables
configure:3871: gcc -o conftest -O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe   conftest.c  >&5
configure:3875: $? = 0
configure:3897: result: 
configure:3919: checking whether we are cross compiling
configure:3927: gcc -o conftest -O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe   conftest.c  >&5
In file included from conftest.c:11:0:
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:59:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'typedef'
 typedef __off_t  fpos_t;
 ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:142:19: error: expected ')' before '_close'
  int (* _Nullable _close)(void *);
                   ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:143:19: error: expected ')' before '_read'
  int (* _Nullable _read)(void *, char *, int);
                   ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:144:2: error: expected ';' before 'fpos_t'
  fpos_t (* _Nullable _seek)(void *, fpos_t, int);
  ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:264:33: error: unknown type name 'fpos_t'
 int  fgetpos(FILE * __restrict, fpos_t * __restrict);
                                 ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:274:28: error: unknown type name 'fpos_t'
 int  fsetpos(FILE *, const fpos_t *);
                            ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:410:13: error: conflicting types for '_Nullable'
      int (* _Nullable)(void *, const char *, int),
             ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:409:13: note: previous definition of '_Nullable' was here
      int (* _Nullable)(void *, char *, int),
             ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:411:6: error: unknown type name 'fpos_t'
      fpos_t (* _Nullable)(void *, fpos_t, int),
      ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:412:13: error: conflicting types for '_Nullable'
      int (* _Nullable)(void *));
             ^
/usr/local/lib/gcc49/gcc/armv6-portbld-freebsd12.0/4.9.4/include-fixed/stdio.h:410:13: note: previous definition of '_Nullable' was here
      int (* _Nullable)(void *, const char *, int),
             ^
conftest.c:12:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'int'
 int
 ^
configure:3931: $? = 1
configure:3938: ./conftest
eval: ./conftest: not found
configure:3942: $? = 127
configure:3949: error: in `/home/njh/src/netdata':
configure:3953: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=armv6-unknown-freebsd12.0
ac_cv_env_CC_set=''
ac_cv_env_CC_value=''
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe'
ac_cv_env_CPPFLAGS_set=''
ac_cv_env_CPPFLAGS_value=''
ac_cv_env_CPP_set=''
ac_cv_env_CPP_value=''
ac_cv_env_IPMIMONITORING_CFLAGS_set=''
ac_cv_env_IPMIMONITORING_CFLAGS_value=''
ac_cv_env_IPMIMONITORING_LIBS_set=''
ac_cv_env_IPMIMONITORING_LIBS_value=''
ac_cv_env_LDFLAGS_set=''
ac_cv_env_LDFLAGS_value=''
ac_cv_env_LIBCAP_CFLAGS_set=''
ac_cv_env_LIBCAP_CFLAGS_value=''
ac_cv_env_LIBCAP_LIBS_set=''
ac_cv_env_LIBCAP_LIBS_value=''
ac_cv_env_LIBMNL_CFLAGS_set=''
ac_cv_env_LIBMNL_CFLAGS_value=''
ac_cv_env_LIBMNL_LIBS_set=''
ac_cv_env_LIBMNL_LIBS_value=''
ac_cv_env_LIBS_set=''
ac_cv_env_LIBS_value=''
ac_cv_env_MATH_CFLAGS_set=''
ac_cv_env_MATH_CFLAGS_value=''
ac_cv_env_MATH_LIBS_set=''
ac_cv_env_MATH_LIBS_value=''
ac_cv_env_NFACCT_CFLAGS_set=''
ac_cv_env_NFACCT_CFLAGS_value=''
ac_cv_env_NFACCT_LIBS_set=''
ac_cv_env_NFACCT_LIBS_value=''
ac_cv_env_PKG_CONFIG_LIBDIR_set=''
ac_cv_env_PKG_CONFIG_LIBDIR_value=''
ac_cv_env_PKG_CONFIG_PATH_set=''
ac_cv_env_PKG_CONFIG_PATH_value=''
ac_cv_env_PKG_CONFIG_set=''
ac_cv_env_PKG_CONFIG_value=''
ac_cv_env_SSE_CANDIDATE_set=''
ac_cv_env_SSE_CANDIDATE_value=''
ac_cv_env_UUID_CFLAGS_set=''
ac_cv_env_UUID_CFLAGS_value=''
ac_cv_env_UUID_LIBS_set=''
ac_cv_env_UUID_LIBS_value=''
ac_cv_env_ZLIB_CFLAGS_set=''
ac_cv_env_ZLIB_CFLAGS_value=''
ac_cv_env_ZLIB_LIBS_set=''
ac_cv_env_ZLIB_LIBS_value=''
ac_cv_env_build_alias_set=''
ac_cv_env_build_alias_value=''
ac_cv_env_host_alias_set=''
ac_cv_env_host_alias_value=''
ac_cv_env_target_alias_set=''
ac_cv_env_target_alias_value=''
ac_cv_host=armv6-unknown-freebsd12.0
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AWK=nawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/njh/src/netdata/missing aclocal-1.15'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /home/njh/src/netdata/missing autoconf'
AUTOHEADER='${SHELL} /home/njh/src/netdata/missing autoheader'
AUTOMAKE='${SHELL} /home/njh/src/netdata/missing automake-1.15'
AWK='nawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-O2 -W -Wformat=2 -Wswitch -Wshadow -Wwrite-strings -Wuninitialized -Wall -pipe'
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENABLE_CAPABILITY_FALSE=''
ENABLE_CAPABILITY_TRUE=''
ENABLE_PLUGIN_APPS_FALSE=''
ENABLE_PLUGIN_APPS_TRUE=''
ENABLE_PLUGIN_FREEIPMI_FALSE=''
ENABLE_PLUGIN_FREEIPMI_TRUE=''
ENABLE_PLUGIN_NFACCT_FALSE=''
ENABLE_PLUGIN_NFACCT_TRUE=''
EXEEXT=''
FREEBSD_FALSE=''
FREEBSD_TRUE=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
IPMIMONITORING_CFLAGS=''
IPMIMONITORING_LIBS=''
LDFLAGS=''
LIBCAP_CFLAGS=''
LIBCAP_LIBS=''
LIBMNL_CFLAGS=''
LIBMNL_LIBS=''
LIBOBJS=''
LIBS=''
LINUX_FALSE=''
LINUX_TRUE=''
LTLIBOBJS=''
MACOS_FALSE=''
MACOS_TRUE=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /home/njh/src/netdata/missing makeinfo'
MATH_CFLAGS=''
MATH_LIBS=''
MKDIR_P='./install-sh -c -d'
NFACCT_CFLAGS=''
NFACCT_LIBS=''
OBJEXT=''
OPTIONAL_IPMIMONITORING_CFLAGS=''
OPTIONAL_IPMIMONITORING_LIBS=''
OPTIONAL_LIBCAP_CFLAGS=''
OPTIONAL_LIBCAP_LIBS=''
OPTIONAL_MATH_CLFAGS=''
OPTIONAL_MATH_LIBS=''
OPTIONAL_NFACCT_CLFAGS=''
OPTIONAL_NFACCT_LIBS=''
OPTIONAL_UUID_CLFAGS=''
OPTIONAL_UUID_LIBS=''
OPTIONAL_ZLIB_CLFAGS=''
OPTIONAL_ZLIB_LIBS=''
PACKAGE='netdata'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='netdata'
PACKAGE_RPM_RELEASE=''
PACKAGE_RPM_VERSION='1.6.1'
PACKAGE_STRING='netdata 1.6.0-44-gd67bc79c_rolling'
PACKAGE_TARNAME='netdata'
PACKAGE_URL=''
PACKAGE_VERSION='1.6.0-44-gd67bc79c_rolling'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
SET_MAKE=''
SHELL='/bin/sh'
SSE_CANDIDATE=''
STRIP=''
UUID_CFLAGS=''
UUID_LIBS=''
VERSION='1.6.0-44-gd67bc79c_rolling'
ZLIB_CFLAGS=''
ZLIB_LIBS=''
ac_ct_CC='gcc'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build='armv6-unknown-freebsd12.0'
build_alias=''
build_cpu='armv6'
build_os='freebsd12.0'
build_vendor='unknown'
cachedir=''
chartsdir=''
configdir=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
has_jemalloc=''
has_tcmalloc=''
host='armv6-unknown-freebsd12.0'
host_alias=''
host_cpu='armv6'
host_os='freebsd12.0'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/njh/src/netdata/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='/var'
logdir=''
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
nodedir=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
pluginsdir=''
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
pythondir=''
registrydir=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='/etc'
target_alias=''
varlibdir=''
webdir=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "netdata"
#define PACKAGE_TARNAME "netdata"
#define PACKAGE_VERSION "1.6.0-44-gd67bc79c_rolling"
#define PACKAGE_STRING "netdata 1.6.0-44-gd67bc79c_rolling"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "netdata"
#define VERSION "1.6.0-44-gd67bc79c_rolling"

configure: exit 1

**Comment by csamsel** [comment]
I dont really know FreeBSD but quiet sure it's ARM related. Also the errors in the gcc test point more towards a FreeBSD problem than to an error in netdata.

**Comment by vlvkobal** [comment]
@nigelhorne you can try to compile `netdata` with clang. Delete gcc package and set
`setenv CFLAGS "-I/usr/local/include"` before compiling `netdata`.

**Comment by ktsaou** [comment]
I am closing this.
@nigelhorne did you solve it?
if you still need help, just post and I'll be notified.
