### ISSUE TITLE
Question: Backend logging from netdata master writes all data to db under his own hostname

### ISSUE THREAD

**Issue by vbonline** [firehol/netdata#2017]
I have a bunch of ephemeral nodes sending their data to a netdata master

The master archives the data to a opentsdb backend (influxdb). But all data arriving in influxdb has the hostname tag from the master. So how do I determine which data belongs to which node?

My backend configuration:

[backend]
   enabled = yes
   type = opentsdb
   destination = localhost
   prefix = sirius

Example measurement in the opentsdb database:

sirius.apps.cpu.cron

But from which host is this?

**Comment by ktsaou** [comment]
Are you sure?

I see [at the code](https://github.com/ktsaou/netdata/blob/25ab875c31533a003f6f6f38592361fc1c8e8f06/src/backends.c#L588-L588) that netdata passes the hostname of each host, to the backend.

Could you please verify it?

You can dump to error.log the whole buffer netdata sends to the backend, by uncommenting [this line](https://github.com/ktsaou/netdata/blob/25ab875c31533a003f6f6f38592361fc1c8e8f06/src/backends.c#L617-L617). Remember to comment it again, since you will get a lot of data in error.log.

**Comment by vbonline** [comment]
Uncommented the line, recompiled, installed and restarted... 

Result: Lots of lines like:

put sirius.netdata.plugin_tc_time.run_time 1490400754 11.0000000 host=sirius
put sirius.netdata.plugin_tc_cpu.user 1490400754 0.0000000 host=sirius
put sirius.netdata.plugin_tc_cpu.system 1490400754 0.0000000 host=sirius
put sirius.system.idlejitter.jitter 1490400754 89.7777778 host=sirius

BACKEND END

But:

sirius:/var/log/netdata # grep 'host=sirius' error.log | wc -l
95362
sirius:/var/log/netdata # grep 'host=' error.log | grep -v sirius | wc -l
0

So 95k backend data logged with host=sirius, but one with one of my ephemeral nodes (3 more), which I can see on my netdata website...

**Comment by vbonline** [comment]
Found the problem:

Somehow reinstalling with "./netdata-updater.sh -f" had overwritten stream.conf so my nodes couldn't send data, so the master couldn't send data from them to the archive. Since netdata.conf is NOT overwritten I didn't notice that stream.conf was reset.

I recreated stream.conf on the master and now it is writing all data to the archive...

Thanks for the effort!

**Comment by ktsaou** [comment]
I have added some debugging output to backends.
Could you please get the latest version, install it and set the following in `netdata.conf`:

```
[global]
    debug flags = 0x0000000008000000
```

restart netdata and in `debug.log` you will have a few lines per iteration stating the number of hosts, charts and dimensions sent, but also the reasons hosts, charts and dimensions are not sent (if any).

**Comment by vbonline** [comment]
Thank you! Very helpful.

**Comment by ktsaou** [comment]
hm... `netdata-updater.sh` overwrote `stream.conf`? This is a problem. Could you please check this is really what happened?

**Comment by vbonline** [comment]
No "make install" does. Which I executed after I uncommented the line you requested. And it still does (tested it right now). So maybe a handling error on my side?

Since it left netdata.conf intact the master still worked,  but couldn't receive data from the nodes, so I didn't notice it at first...

**Comment by ktsaou** [comment]
ok. yes `make install` does overwrite the files. This is why you have to use the updater/installer. They both protect your configuration.

**Comment by vbonline** [comment]
To repay a bit for the effort:

Here is a Grafana dashboard which templates all hosts where data is sent by the master:

[https://grafana.com/dashboards/1775](url)

Principle:

All netdata Nodes are sending to the netdata-master
The netdata master archives all data to influxdb
The grafana dashboard let you select which netdata host (nodes or master) you want to see data from

I don't think you can make it easier than that.

Thank you for the node/master configuration. That makes life sooo much easier with a lot of servers.

**Comment by ktsaou** [comment]
nice! 👍
