### ISSUE TITLE
question on bootstrap netdata

### ISSUE THREAD

**Issue by abdulirfan3** [firehol/netdata#202]
Hello,

We are so impressed by this tool that our team has decided to move forward and install this on all the new server that we are going to build going forward and from security standpoint most of our servers do NOT run in DMZ and also we are going to install it and only bring up netdata when we need to, in that way the netdata web server will be down and port 19999 will not be used until and unless bring up netdata.  

Now to my main question.  As we want to bootstrap the install(we run in AWS and use cloudformation to build our servers), we have 2 options....
1. As part of user data init script, git clone the repo and install for every server
2. install it once on our current image and create a new image out of this and use that image for all servers going forward.

If we were to use option number #2, what are the things we need to do to make this work.  Reason why I ask is, lets say we bring up a new server using our current image and that host/hostname is called "imagehost"... now i install netdata and make sure i can get to http://imagehost:199999 and everything is fine, next I stop this "imagehost" server and create an image out this... once the image is created, i launch a new server from this image and lets call that new host/hostname is "webserver1".... As the new image has a netdata conf and hostname of "imagehost"... or would netdata automatically detect new hostname and we are good to go ??

Also is there a way to do a unattended install or does below works as we have to HIT ENTER key ?
echo | <PATH_TO_NETDATA_INSTALL>/netdata-installer.sh

**Comment by ktsaou** [comment]
Nice you like netdata!

netdata auto-detects everything at runtime, including the hostname. If you haven't edited the configuration file, everything is automatic. Try it. Get `http://your.server:19999/netdata.conf` to see it. The hostname should be commented, so it is autodetected.

The installer supports several options. Run `./netdata-installer.sh -h` to see them. One is `--dont-wait`, which does exactly what you ask for.

I have one question for you: Since you don't have a DMZ, how do you control administrative access to your servers? You run firewalls on all your servers, you have a VPN where you connect to get admin access, something else?

**Comment by abdulirfan3** [comment]
Thank you for the explanation with regards to bootstrap...

With regards to your questions, I should have stated it better.  We do have DMZ, but we dont plan to use this image to bring up servers there, we use a different image which is hardened when we deploy servers in DMZ.... but for any hosts (either in DMZ or not) we control inbound access thru AWS Security group (acts like instance level firewall) and for admin access we have a bastion host that we first SSH to from our internal network  and then SSH from bastion host to all other host (again inbound access to this bastion host in protected by a special security group that only allow port 22 from specific IP address, everything is denied).  We also do use SSH agent forward to protect all server further, as only way to login to them is using key-pair that sits on our laptop.... bastion host never keeps the key-pair....we just use that as a proxy ...

**Comment by ktsaou** [comment]
ok. You could therefore install an nginx to the bastion host, allowing connections from the same host it allows ssh. This nginx will allow you to access all your netdata servers. I use the nginx config found here: https://github.com/firehol/netdata/wiki/Running-behind-nginx#access-multiple-netdata-servers-via-one-nginx

This config allows you to access netdata with URLs like:

- `http://bastion.host/netdata/server1/` to reach server1
- `http://bastion.host/netdata/server2/` to reach server2
- `http://bastion.host/netdata/server3/` to reach server3

nginx could also require authentication to access any of the netdata servers, using the config found here: https://github.com/firehol/netdata/wiki/Running-behind-nginx#enable-authentication

So, all netdata servers will be blocked with AWS Security. At AWS Security only nginx will be listening for requests from the same IP it accepts SSH. nginx will further require authentication from the users, to proxy them to any netdata (and only to netdata - you define the back-end netdata servers one by one in nginx config).

This way, you could leave netdata running all the time. If your hosts have enough RAM, you could configure netdata with `history = 86400` to have a day of data, and enable KSM (the installer says how) to deduplicate its memory (it save about half of it).

**Comment by ktsaou** [comment]
Can we close this?

**Comment by ktsaou** [comment]
I close this.
If something is missing, open it again.
