### ISSUE TITLE
Web notifications

### ISSUE THREAD

**Issue by RyanGuyCode** [firehol/netdata#2024]
I notice that web notifications are persistent. If something is addressed, it goes away. Is there a way to have them age out. The moment I close a notification, it pops up again.

**Comment by ktsaou** [comment]
hm... this shouldn't be happening.

When you say "it pops up again", you mean "immediately", "on next dashboard refresh", "after some time"?

This is how netdata works:

1. each alarm has a unique id
2. every time an alarm changes state, an `alarm event` is generated.
3. each `alarm event` gets also a unique id (incremental)
4. web notifications show the latest `alarm event` of an alarm, only if it is not older (smaller) than the last shown - the dashboard saves the latest `alarm event` id shown, to browser local storage.

So:

1. if alarms pop up "immediately", we may have a bug.
2. if alarms pop up "on next dashboard refresh", your browser local storage may be disabled.
3. if alarms pop up "after some time", you may be having an alarm that flip-flops. You will have to check the alarm log to find out if this is the case (on the dashboard).

**Comment by RyanGuyCode** [comment]
Hi, I meant immediately.

**Comment by ktsaou** [comment]
ok, please press F12 on your web browser and switch to the console tab. Are there any messages logged?

**Comment by ktsaou** [comment]
ok, please press F12 on your web browser and switch to the console tab. Are there any messages logged?

**Comment by RyanGuyCode** [comment]
Sorry about this, but I don’t have F12 on my MacOS.

Warm Regards,
Ryan Milton
Network Engineer CCNA, CCNP, JNCIA, JNCIS-ENT, JNCIS-SEC

**Comment by ktsaou** [comment]
well, the web browser console should have something to open it...

google says:

> To access the developer console in Safari, use the Develop > Show Error Console menu item (Option-Cmd-C): If you don't see the Develop menu, you'll need to turn it on using Safari Preferences. Open Safari > Preferences, and click on the Advanced Tab.

**Comment by RyanGuyCode** [comment]
Gotcha!

So, what I see is this:

(index):1 Error in event handler for (unknown): TypeError: Cannot read property 'verdict' of undefined
    at chrome-extension://cfnpidifppmenkapgihekkeednfoenal/aph.js:240:17


However, it looks to be with Bitdefender:


      chrome.extension.sendMessage
                  (
                        {
                              type: BitDefenderTrafficLight.consts.BD_TLL_COMMAND_APH_REQUEST,
                              url: location.href,
                              body: document.getElementsByTagName("html")[0].innerHTML.replace(/\s+/g," "),
                              title: document.title,
                              meta: meta,
                              scripts: scripts,
                              domain: domainExtracted
                        }, function(response)
                        {

                              if(response.verdict == "PHISHING") <--------error points here.
                              {
                                    pageInfo.status = "Phishing";
                              }
                              else if(response.verdict == "MALWARE")
                              {
                                    pageInfo.status = "Malware";
                              }
                              else if(response.verdict == "UNTRUSTED")
                              {
                                    pageInfo.status = "Untrusted";
                                    if(response.white != 'true')
                                    {
                                          var url = response.url;
                                          BitDefenderTrafficLight["'"+url+"'"] = 1;
                                    }



Warm Regards,
Ryan Milton
Network Engineer CCNA, CCNP, JNCIA, JNCIS-ENT, JNCIS-SEC

**Comment by bvierra** [comment]
This is an error from TrafficLight not properly returning a response from a call sent to it, they have had the issue for awhile now (https://forum.bitdefender.com/index.php?/topic/73657-traffic-light-gives-javascript-error/). Try disabling the plugin and see if it resolves the issue.

**Comment by RyanGuyCode** [comment]
That seems to clean things up actually.

Thank you!

Warm Regards,
Ryan

**Comment by ktsaou** [comment]
ok. nice!
Thank you @bvierra  !
