### ISSUE TITLE
Settings cutom dashboard

### ISSUE THREAD

**Issue by yoorshop** [firehol/netdata#2027]
Hello,

I have setup a custom dashboard which works fine.

Default refresh setting is 'onfocus', adn I would like 'always', how we do that ?

thanks

**Comment by l2isbad** [comment]
```html
<script>   
 // always update the charts, even if focus is lost
    NETDATA.options.current.stop_updates_when_focus_is_lost = true;
</script>
```

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
