### ISSUE TITLE
MUTEX_LOCK failed to get lock on macOS 10.11

### ISSUE THREAD

**Issue by octomike** [firehol/netdata#2028]
I just built 1.6.0 and netdata won't start:

```
$ sudo /usr/local/sbin/netdata -D
2017-03-28 16:31:03: netdata: ERROR: MUTEX_LOCK: failed to get lock (code 22) (errno 9, Bad file descriptor)
2017-03-28 16:31:03: netdata: ERROR: MUTEX_LOCK: failed to unlock (code 22).
[...]
```

Let me know how to provide debug output  and I will gladly deliver.

**Comment by octomike** [comment]
Okay, it seems those issues are unrelated. The mutex_lock error is spamming me a lot, but netdata will start once netdata.conf is in place and user/group permissions are set correctly. `/usr/local/var/log/netdata/debug.log` is what needs to be checked.

**Comment by ktsaou** [comment]
@vlvkobal could you please check this?

**Comment by linickx** [comment]
> I just built 1.6.0 and netdata won't start:

I've had similar issues installing on OSX but found this error message was miss-direction.

Assuming you're following [the guide](https://github.com/firehol/netdata/wiki/Installation#macos)

My fix was. 

1. Copy `~/opt/netdata/etc/netdata/netdata.conf` to desktop - `cp ~/opt/netdata/etc/netdata/netdata.conf ~/Desktop`
2. Delete install directory - `rm -fr ~/opt/netdata/`
3. Create a new netdata etc directory - `mkdir -p ~/opt/netdata/etc/netdata/`
4. Move the file - `mv ~/Desktop/netdata.conf ~/opt/netdata/etc/netdata/`
5. Fix the `run as user` to be "nobody", excerpt below... take note of the OSX-funny, no space after the `=`

```
# global netdata configuration

[global]
	# run as user = netdata
    run as user =nobody
```

Now re-install `./netdata-installer.sh --install ~/opt` and it should start ok.

HTH!

... I have v1.6.1_rolling running on 2x OSX 10.11.6 machines, but I still need to figure out what all these errors are as they fill up the screen when netdata starts, does anyone has any suggestions?

**Comment by ktsaou** [comment]
well, we surely need the help of @vlvkobal here....

**Comment by tncyysl** [comment]
same error after `./netdata-updater.sh` 🤔

**Comment by ktsaou** [comment]
http://stackoverflow.com/questions/30511046/pthread-mutex-lock-returns-22-in-c

it seems that error 22 means that the mutex is unitialized. Let me try find it...

**Comment by ktsaou** [comment]
Strange. There are only 4 mutexes in netdata and all of them are initialized properly.
Still searching...

**Comment by ktsaou** [comment]
Could you please help me find it?

I need the following from you:

1. Re-install netdata, but this time I need you to run netdata-installer.sh like this:

```sh
CFLAGS="-DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh     <... options ...>
```

So, just define `CFLAGS="-DNETDATA_INTERNAL_CHECKS=1"` before running it.

2. edit /etc/netdata/netdata.conf (if you have in `/opt/netdata`, prepend that to the path) and set:

```
[global]
    debug flags = 0x0000000004000000
```

Now, restart netdata. The file `/var/log/netdata/debug.log` (or the same under `/opt/netdata`), will be created. Let it run until you see the above errors in `error.log` and please post `debug.log` here.

Of course, undo both changes after that.

 `debug.log` will include the points that call the offending mutex functions and the result of the mutex, so I might be able to spot the issue.

**Comment by octomike** [comment]
> Could you please help me find it?
I'll gladly provide some debug logs.

Output of running and immediately interrupting `netdata -D`: [console-out.txt](https://github.com/firehol/netdata/files/944164/console-out.txt)

The rather large debug.log (no `ERROR` lines though and timestamps are not specific enough): [debug.log.txt](https://github.com/firehol/netdata/files/944163/debug.log.txt)

Let me know if you need more!

**Comment by ktsaou** [comment]
Found it! Your trace was critical to pinpoint it!
Submitting a PR now.

**Comment by ktsaou** [comment]
merged it.
Could you please confirm it works now?

**Comment by octomike** [comment]
Can confirm. No more mutex spam.

Thanks for the clear debug instructions!
