### ISSUE TITLE
Dashboard doesnt show nginx plugin

### ISSUE THREAD

**Issue by lxprost** [firehol/netdata#2029]
Ubuntu 16.04 LTS

tryed:

/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug nginx
= all okey, working 

> 
> RemoteNginx:
>   name : 'abhttp'
>   url     : 'http://172.16.0.4/stats'
>   retries : 10
>   update_every : 1
>   priority     : 90100
> 

in /etc/netdata/python.d/nginx.conf

cat /var/log/nedata/error.log | grep nginx

> 2017-03-28 16:34:13: charts.d: INFO: nginx: is disabled. Add a line with nginx=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
> 2017-03-28 16:35:44: charts.d: INFO: nginx: is disabled. Add a line with nginx=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
> 2017-03-28 16:39:59: python.d INFO: CHECKED OK: nginx_RemoteNginx
> 2017-03-28 16:39:59: python.d INFO: RENAMED: nginx_abhttp , from nginx_RemoteNginx
>

**Comment by ktsaou** [comment]
I can think of 2 possible problems:

1. you have 2 nginx servers with the same name, so only one of them manages to go through.
Could you please set `name: 'abhttp2'` and retry?

    python.d.plugin uses names for mutually exclusion between configuration sections. So, for any given name, only one configuration section will be active at any given time.

2. For some reason the plugin stops collecting data. Could you please check your nginx logs for requests from netdata?

@l2isbad any other ideas?

**Comment by lxprost** [comment]
After 10 minutes logs:

> 2017-03-28 17:07:40: python.d ERROR: nginx_log_nginx_log Cannot access file: '/var/log/nginx/access.log'
> 2017-03-28 17:07:40: python.d ERROR: nginx_log_nginx_log check() failed - disabling job
> 2017-03-28 17:07:40: python.d ERROR: DISABLED: nginx_log
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connections/main.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connections/active.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.requests/main.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.requests/requests.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connection_status/main.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connection_status/reading.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connection_status/writing.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connection_status/waiting.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connect_rate/main.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connect_rate/accepts.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/nginx_abhttp.connect_rate/handled.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/netdata.plugin_pythond_nginx_abhttp/main.db.
> 2017-03-28 17:12:13: netdata: INFO: Initializing file /var/cache/netdata/netdata.plugin_pythond_nginx_abhttp/run_time.db.

Now, all work fine
