### ISSUE TITLE
Documentation for `data-show-value-of`

### ISSUE THREAD

**Issue by samof76** [firehol/netdata#2038]
Hi i am trying to build a customized dashboard, something of this sort...

![StackExchange](http://blog.serverfault.com/files/2012/01/StackExchangeStatusPage.jpg)

I am looking for the documentation, `data-show-`, to get CPU utilization, is it possible?

                <div data-netdata="system.cpu" data-height="20px" data-chart-library="sparkline" data-width="60%" data-show-value-system-cpu-at="system-cpu" data-host="http://localhost:19999/" class="netdata-container"></div>
                <span id="system-cpu"></span>%

In which case how?

**Comment by ktsaou** [comment]
hm... it seems I missed this question. I am sorry...

I suggest to use the dygraph sparkline.
You can find all `data-` options for dygraph here: https://github.com/firehol/netdata/blob/99d44b7d0c4e006b11318a28ba4a7e7d3f9b3bae/web/dashboard.js#L4270-L4453

At `http://your.netdata.ip/registry.html` I have an incomplete attempt of mine to create a `my-netdata` menu with such charts. You could probably check it.

A dashboard like the one you have above, would be ideal to be registry based. So, if you move towards this, I would love to add it to netdata.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
