### ISSUE TITLE
systemd fails to start netdata.service

### ISSUE THREAD

**Issue by nickptrvc** [firehol/netdata#204]
When you try to start netdata with systemd, it just hangs and eventually will time out. I found that the path `/opt/netdata/var/run/` didn't exist as stated in the netdata.service file for the `-pidfile` path. Once I create the `run` directory, I was able to start netdata using systemd. I used the default `netdata-installer.sh` script to build and install netdata.

Using CentOS 7.2 and the latest master commit `2f9429c`.

```
ExecStart=/opt/netdata/usr/sbin/netdata -pidfile /opt/netdata/var/run/netdata.pid
                                                                   ^ this guy
```

**Comment by Kubuxu** [comment]
I think it was resolved here: https://github.com/firehol/netdata/pull/200/

Can you check it?

**Comment by ktsaou** [comment]
It seems we all (me and the package maintainers) have different opinions as to where to save the pid file.
Anyway, thanks for reporting it. The installer now creates this directory.

**Comment by nickptrvc** [comment]
@ktsaou fix confirmed. thanks for the speedy resolution.
