### ISSUE TITLE
Host FQDN is not properly determined for the alert email

### ISSUE THREAD

**Issue by pol** [firehol/netdata#2042]
Even though `hostname -f` prints out the correct fqdn, that isn't used in the email that is sent out. As a result, anti-spam filters will bounce the emails because the domain is invalid.   The expectation is that the email would use the full fqdn for the email domain.

Host: 
```
[root@naemon netdata]# hostname
naemon
[root@naemon netdata]# hostname -f
naemon.rci.montana.edu
```

Send test email:
```
/usr/libexec/netdata/plugins.d/alarm-notify.sh test

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2017-03-31 13:23:50: alarm-notify.sh: INFO: sent email notification for: naemon test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2017-03-31 13:23:50: alarm-notify.sh: INFO: sent email notification for: naemon test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2017-03-31 13:23:50: alarm-notify.sh: INFO: sent email notification for: naemon test.chart.test_alarm is CLEAR to 'root'
# OK
```

Email that arrives has a bad fqdn and is rejected by our mail listserv:

```
Mar 31 11:49:05 acnssympa postfix/smtpd[24191]: NOQUEUE: reject: RCPT from
naemon.rci.montana.edu[153.90.203.171]: 450 4.1.8
<root@naemon.localdomain>: Sender address rejected: Domain not found;
from=<root@naemon.localdomain> to=<REDACTED>
proto=ESMTP helo=<naemon.localdomain>
```

**Comment by ktsaou** [comment]
Hi,

email is dispatched like this: https://github.com/firehol/netdata/blob/b1b47cabfcb9485dc3b1f346a26192d26e857dfe/plugins.d/alarm-notify.sh#L1301-L1304

`send_email` is function: https://github.com/firehol/netdata/blob/b1b47cabfcb9485dc3b1f346a26192d26e857dfe/plugins.d/alarm-notify.sh#L639

So this is what netdata does:

```sh
sendmail -t <<EOF
To: ${to_email}
Subject: ${host} ${status_message} - ${name//_/ } - ${chart}
Content-Type: text/html

...
EOF
```

This means that the `sendmail` command of your MTA controls the `From:` line of the emails sent. netdata does not set it (and I believe setting the `From:` line is only allowed for `root`, so netdata will not be able to set it anyway).

My understanding is that you have to configure your MTA to send emails properly. Your MTA appended `.localdomain`, so I guess this is its default configuration.

If you use postfix, you will have to set `mydomain = your.domain` to `/etc/postfix/main.cf` (or equivalent, depending on your distro).

**Comment by pol** [comment]
My only success so far has been to set my hostname as the fqdn.  This is not going to work for some of my hosts who have complicated networking.

I did try just setting it manually, and it worked.  The snippet below was a test from the shell, and it properly set the "FROM" to `whoami`@`hostname -f`.

```
[root@naemon ~]# sendmail -t <<EOF
> To: ${to_email}
> From: $(whoami)@$(hostname -f)
> Subject: ${host} ${status_message} - ${name//_/ } - ${chart}
> Content-Type: text/html
>
> This is a test.
> EOF
```

I may try modifying netdata to do what I want, but I am afraid to do that since updates will break the behavior.  And this is probably not the *right* way to do it, but I don't really want to install postfix either.

**Comment by ktsaou** [comment]
Does this work is the user running this command is not root?

Which MTA do you use?

**Comment by pol** [comment]
Wow, I fail the sysadmin test.  I am using postfix (I didn't think I was), I assumed I was using some very-basic GNU sendmail binary (or something like it).  

I will try updating postfix/main.cf and report back the results.

However, I did try using sendmail -t with the "From: " header as an unprivileged user, and it worked fine (It showed up in my inbox with the right data in the right fields).  I don't know if it would work with the netdata user, but it did work for my non-root shell account.

**Comment by pol** [comment]
Reporting back

Setting `myhostname = naemon.rci.montana.edu` in `/etc/postfix/main.cf` worked great.

I am now testing what you recommended (setting `mydomain = rci.montana.edu`) to see if that also works.  I expect that it will, and I can change that setting system-wide (for those servers that use postfix).

thanks for your help, I hope that this issue thread is of some use to people like me who assume that "FROM:" in an email from a service is set by the service and nowhere else.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.

**Comment by Hariprasanth03SN** [comment]
/usr/libexec/netdata/plugins.d/alarm-notify.sh: line 1017: backtrackr713@blask. command not found

2018-07-31 18:21:55: alarm-notify.sh: ERROR: failed to send email notification for: kali test.chart.test_alarm is CLEAR to 'root' with error code 127.
# FAILED 
 
help me with this error
