### ISSUE TITLE
firehol - Can't install

### ISSUE THREAD

**Issue by xspbrx** [firehol/netdata#2044]
When I run the below commands:
`curl 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-all-firehol.sh' >install-all-firehol.sh
bash ./install-all-firehol.sh`
I keep getting this
`Downloading (git pull) iprange...
Already up-to-date.
Downloading (git pull) firehol...
Already up-to-date.
Downloading (git pull) netdata...
Already up-to-date.

Building iprange...
./autogen.sh: 2: ./autogen.sh: autoreconf: not found`

Any Suggestions

**Comment by ktsaou** [comment]
Run this:

```
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata firehol
```

Your system is missing a few packages. The above command will find which ones.

**Comment by xspbrx** [comment]
@ktsaou Cheers

**Comment by xspbrx** [comment]
@ktsaou One more question, when I run

`sudo fireqos status`

I keep getting

`There is no interface named '' to show`

**Comment by ktsaou** [comment]
the status command needs another parameter: the interface to show status for...
