### ISSUE TITLE
netdata: basic embedded build 

### ISSUE THREAD

**Issue by matthew-l-weber** [firehol/netdata#2052]
I'm working on adding the netdata software as a package in buildroot and I'm at a stage where I'd welcome feedback on approaches to disabling pieces of the software to create a minimal build.  Basically I'd like the most minimal configuration I can get with the C code standalone without node.js or python pieces, etc.  Any guidance is definitely welcomed and I'll propose back  my changes in a pull as I work through them.

Thanks!

**Comment by matthew-l-weber** [comment]
label:question

**Comment by ktsaou** [comment]
Hi, edit netdata.conf and at the `[plugins]` section disable the ones you don't need.

**Comment by matthew-l-weber** [comment]
Agree, I was also thinking of taking it one step further to limit
installation to minimize file system size.  I.e. to enable/install python
plugins/hooks when the file system has it, etc

**Comment by ktsaou** [comment]
well... you are going to save just a few KB:

```sh
# du -s -h /tmp/netdata/usr/libexec/netdata/*
152K	/tmp/netdata/usr/libexec/netdata/charts.d
184K	/tmp/netdata/usr/libexec/netdata/node.d
248K	/tmp/netdata/usr/libexec/netdata/plugins.d
888K	/tmp/netdata/usr/libexec/netdata/python.d
```

If this is important for you, just delete the relative directories.

**Comment by ktsaou** [comment]
In `/usr/libexec/netdata/plugins.d` keep `alarm_notify.sh` is you need alarms.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
