### ISSUE TITLE
How to set alarm notfification on multiple mount points

### ISSUE THREAD

**Issue by mohammedadil123** [firehol/netdata#2055]
Hi 

I am unable to  set alarm notification for different  mount point .

Please help me out

**Comment by ktsaou** [comment]
The default alarm for disk space is this: https://github.com/firehol/netdata/blob/543f65452d55a0d30b22214c6e1ee299c160b87b/conf.d/health.d/disks.conf#L8-L18

You have 2 options:

1. If you need a different notification script for just a chart, copy this definition and change `template` to `alarm` and set the `on` parameter to the exact chart you want it to be applied. This solution is good of you want to overwrite the notification for just one chart.

2. You can have multiple templates for different mount points. So, you copy the alarm template again, the new one will still be a `template` and you will use the `families` option to filter the mount points each one will be applied to.

The `families` option accepts any number of space separated mount poinits. You can also use ` * ` as wildcard and the ` ! ` for negative matches.

So, you will have 2 templates with different families (mount points).

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
