### ISSUE TITLE
HTML keeps getting dumped to console

### ISSUE THREAD

**Issue by palanjam** [firehol/netdata#2057]
I'm on netdata 1.6.1_rolling. CentOS 7. I keep getting the HTML from the webpage dumped to my console and as a result keep getting the message that I have new mail in /var/spool/mail/root

**Comment by ktsaou** [comment]
Hi. What do you mean? Could you please explain it a bit more and include screenshot?

**Comment by palanjam** [comment]
Yep. From my /var/spool/mail/root file. It posts quite often. 

Maybe an error that isn't going to a log or trying to email me but I don't have email setup on my server.

![netdata error](https://cloud.githubusercontent.com/assets/1247820/24731021/b3abe78c-1a24-11e7-9e20-25bcac395777.png)

**Comment by l2isbad** [comment]
`health_alarm_notify.conf`

```bash
# enable/disable sending emails
SEND_EMAIL="YES"
```

**Comment by palanjam** [comment]
Ahh ok so then it technically isn't an issue then. But maybe by default netdata out of the box should have that disabled?

**Comment by ktsaou** [comment]
This is still strange for me. My understanding is that you have some kind of mail client running on the console or dumping email messages when you ssh.
Have you configured this? Which distro do you use?

This a bad default, but I don't think netdata should disable emails by default. emails should not be dumped on the console, and this dump is not performed by netdata...

**Comment by l2isbad** [comment]
They are not dumped to the console.
Netdata send message to the root user (default). That is all.

**Comment by palanjam** [comment]
Correct what @l2isbad said. Typically when you don't specify an output destination for errors/stdout, it will send it to the "mailbox" of the user that is running the program.

**Comment by ktsaou** [comment]
> Typically when you don't specify an output destination for errors/stdout, it will send it to the "mailbox" of the user that is running the program.

This is true for cron jobs. Which other programs do this?

**Comment by palanjam** [comment]
Hmm yea that's true. It's usually only cron. I have installed postfix but haven't configured it. Maybe netdata tries to email if it detects it? The odd thing is this just started happening when I upgraded netdata a few days ago from v1.3

**Comment by l2isbad** [comment]
> few days

> from v1.3

wow 😄

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
