### ISSUE TITLE
Question: Netdata master backend configuration - hostname property?

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#2059]
I have the following Netdata master configuration

[global]
        hostname = netdata-server
        history = 86400
        access log = none
        disconnect idle web clients after seconds = 3600
        config directory = /etc/netdata
        cache directory = /var/cache/netdata
        log directory = /var/log/netdata
        memory deduplication (ksm) = yes
        error log = /var/log/netdata/error.log
        update every = 3
        memory mode = map
        web compression level = 1
        enable web responses gzip compression = yes
        multi threaded web server = yes
        delete obsolete charts files = yes
        delete orphan hosts files = yes

[registry]
        enabled = yes
        registry to announce = NETDATA_REGISTRY_URL

[backend]
        enabled = yes
        # data source = average
        type = opentsdb
        destination = localhost
        prefix = netdata
        hostname = ?
        # update every = 10
        # buffer on failures = 10
        # timeout ms = 20000

What does [backend].hostname refer to?

**Comment by ktsaou** [comment]
I am not sure I understand. You want to define custom hostnames for the slaves at the master?

**Comment by gamefundas** [comment]
Pardon me. My question was a little confusing. Edited now with an example.

**Comment by ktsaou** [comment]
oh, I see.

This is a left-over. It was implemented before replication. It allows us to set a different hostname at the backend, for the local host only.

For remote hosts, it is not used.
I decided not to remove it, to avoid breaking setups that make use of it.

**Comment by gamefundas** [comment]
That's explains. Thx.
