### ISSUE TITLE
Netdata roadmap and vision - Beyond 1.6

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#2060]
Netdata 1.6 release was a significant milestone to make it faster, easy to setup, pluggable, and operate on a cluster/distributed infrastructure. Love the way netdata hs evolved in a short span of time. 

Is there a roadmap as to what to expect in the coming months, year etc? Support for more plugins, any plan to expand Netdata in to the APM space. Just curious and excited to know. :)

**Comment by finid** [comment]
Did want to start a separate thread on this, so I'll tack it on here. 

Would love to see ability to feed logs to a central dashboard.

**Comment by ktsaou** [comment]
Hi,

@gamefundas I haven't replied yet, because there are so much to write. My primary focus for the moment is to expand the netdata userbase by solving the most basic needs we all have. There is still plenty of area for improvement towards this. So, I try to pick features that would have the maximum impact.

@finid "logs feeding" is already there. But netdata is not logstash, elastic search, splunk and the likes. It parses the log files in real-time and produces charts. There are already many plugins in netdata that work like that. Which logs you want it to chart?

**Comment by finid** [comment]
@ktsaou, I have to explore the log feeding a bit more. I was thinking that sending [osquery](https://osquery.io/) logs to a cool dashboard like Netdata would be nice.

**Comment by ktsaou** [comment]
FYI, netdata now has a statsd server embedded. So, APM is here too. 

https://github.com/firehol/netdata/wiki/statsd

**Comment by finid** [comment]
Statsd in Netdata is nice, very nice!

Thanks @ktsaou

**Comment by gamefundas** [comment]
This is fantastic, this now gives me an option to send my Spring boot metrics to Netdata through statsd. Not a preferred way but it should work. 

Also the fact that the charts will be dynamically created it has an advantage over Grafana where one has to create and manage the dashboards. 

Would like to know if the statsd metrics would also end up in the backend for historical analysis?

**Comment by ktsaou** [comment]
> Would like to know if the statsd metrics would also end up in the backend for historical analysis?

yes, but read this: https://github.com/firehol/netdata/wiki/statsd#private-metric-charts

**Comment by gamefundas** [comment]
The limit on the #of charts and performance, should netdata UI spread out to tabbed pages for statsd charts.

**Comment by ktsaou** [comment]
The only problem that exists is that on page scroll, the dashboard needs to re-evaluate the visibility of all charts. For thousands of charts this takes some time (1-2 seconds). So, for every scroll the page freezes for a second or two.

Even if they are on different tabs, the dashboard will still need to do this.

The solution is to find a way, not to re-evaluate all the charts, but only the ones that are likely to be visible depending on the type of change applied to the page (scrolled above/below, switched a tab, etc).

This means the dashboard will need to build a dependency tree of some kind, or maintain different lists depending on the parent element.

Anyway, I need some time to figure this out...

**Comment by gamefundas** [comment]
Love the statsd server in Netdata 1.7
#2466 this is something to look forward to in 1.8.

**Comment by MACscr** [comment]
So does this mean we can push metrics to the statd server included to netdata and chart those metrics within netdata?

**Comment by ktsaou** [comment]
> So does this mean we can push metrics to the statd server included to netdata and chart those metrics within netdata?

yes, exactly. Actually netdata is the only statsd server with automatic visualization. You can also create custom netdata charts correlating different statsd metrics.

**Comment by gamefundas** [comment]
@ktsaou any new features being planned for a release. Its been a while since 1.10 was rolled out.
There was a lot of discussion around Prometheus, Consul and Spring boot integrations/support. Just curious what's coming soon.

**Comment by ktsaou** [comment]
I think we will release an official roadmap soon. We are working on it! We are planning significant improvements in all aspects of netdata.

I am closing this issue, since it is pretty old. We will discuss the new roadmap soon.
