### ISSUE TITLE
Changing default port doesn't work

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [firehol/netdata#2065]
I've modified the config to change the port from :19999 but no matter what port I choose, and even though the config is changed, it still boots back up under :19999

Platform: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

**Comment by ktsaou** [comment]
Could you post your config please?

**Comment by BrickerBrickerOneNine** [comment]
[web]
        # web files owner = netdata
        # web files group = netdata
        # listen backlog = 100
        # default port = 19998
        # bind to = *
        # mode = multi-threaded
        # disconnect idle clients after seconds = 60
        # respect do not track policy = no
        # x-frame-options response header =
        # enable gzip compression = yes
        # gzip compression strategy = default
        # gzip compression level = 3

**Comment by ktsaou** [comment]
The line is commented.
Please remove the '#'.

**Comment by BrickerBrickerOneNine** [comment]
of course. thanks!
