### ISSUE TITLE
netdata-updater.sh is not working

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [firehol/netdata#2066]
meeeeeeee@mycomp:~/netdata$ sudo ./netdata-updater.sh
[sudo] password for meeeeeeee:
Fri Apr  7 14:44:33 EDT 2017 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Fri Apr  7 14:44:33 EDT 2017 : INFO:  Updating netdata source from github...
./netdata-updater.sh: line 67: git: command not found
Fri Apr  7 14:44:33 EDT 2017 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT GET LAST COMMIT ID (use -f for force re-install)

trying -f does nothing

**Comment by ktsaou** [comment]
hm... did you install it from git?

**Comment by BrickerBrickerOneNine** [comment]
Yes, I followed:

https://github.com/firehol/netdata/wiki/Installation#2-install-netdata

**Comment by ktsaou** [comment]
hm...

but it says:

```
./netdata-updater.sh: line 67: git: command not found
```

So, how did you get it without `git`?

**Comment by BrickerBrickerOneNine** [comment]
Yeah, now that I do git -version it says git not installed, but whats freaking odd is neither is zip, and i know i installed that because i zip'd stuff up! SOMETHING IS GOING NUTS OMG!!!! 
sorry for overlooking "command not found" im such an igit...i have bigger problems apparently.

**Comment by BrickerBrickerOneNine** [comment]
Ok, after reinstalling git, and running command, works 100%...odd. It wouldnt have done that if i didnt install via git in the first place, right?

**Comment by ktsaou** [comment]
ok, nice...
