### ISSUE TITLE
Monitoring route table?

### ISSUE THREAD

**Issue by tyrken** [firehol/netdata#2069]
I'm looking to monitor the presence of entries in a route table - i.e. output of `netstat -r`.  I can't see anything for this so presume I'd have to write my own - probably Python is easiest via ExecutableService running netstat as reading /proc/net/route is very Linux specific.

Just confirming my suspicions before starting to work really - please close (with any advice) before I start off in the wrong direction...

**Comment by ktsaou** [comment]
Yes, there is no routing monitoring plugin.
You can use python, or bash. Check this example for bash: https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh

**Comment by ktsaou** [comment]
btw, what do you plan to monitor for the routing table?

**Comment by tyrken** [comment]
See https://github.com/firehol/netdata/pull/2073 for my initial attempt - to count the number of routes and signal the presence of particular CIDRs so they can be alerted on when missing/present.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
