### ISSUE TITLE
Running data collector on another machine/alerts

### ISSUE THREAD

**Issue by deadbird99** [firehol/netdata#207]
First, thanks a lot for netdata. Seriously, it's the monitoring tool I've been searching for for months.

My question is: is there a way to run netdata UI and data collector on two separates machines?
Another question: is it possible to watch a particular value and trigger alerts? Even at a lower level using python script if necessary ;)

Thanks a lot

**Comment by ktsaou** [comment]
Hi, thanks!

A few data collectors support connecting to remote servers to receive their metrics: nxing, apache, mysql, named, snmp, etc.

A few even support multiple remote servers: mysql, named, snmp. (so one netdata installation can monitor many servers).

I have a task to re-write all the application data collectors to support multiple remote application, but this is not ready yet.

Regarding alerts, there are a few open tasks for them #183 #88 etc. However they are not ready yet. Of course you can use the netdata API (check the wiki) to write alarms in any language you know. The API exposes collected data in many formats.

**Comment by deadbird99** [comment]
Thanks a lot for your fast answer. I'll definitely check the API and create my own alerting scripts.

About the data collector, I see the thing from another point of view. I have a machine A that runs the netdata WebUI, and a machine B that runs the data collector. What I'd like to do is configure the data collector to send datas to machine A rather than localhost. Is this feasible?

**Comment by ktsaou** [comment]
Well, netdata is mainly a data collector with an API, like collectd, statsd, etc. All these do have an API, much like netdata.

The difference with netdata is that is written to be real-time and very efficient, so a static web site (yes the site is plain javascript+html+css - nothing runs server side for the site) can directly talk to the data collector itself. The netdata daemon (i.e. the data collector) is not aware of the web UI.

So, even if we were to do what you propose, the result would be that you will have to install 2 netdata daemons that will talk to each other to exchange data.

Check also #178 .

**Comment by awestvik** [comment]
So at some point in the future it's possible to monitor my snmp enabled switch? Hopefully adding info of said switch from the website.

**Comment by ktsaou** [comment]
You can add your snmp switch to monitor its performance already.
Check this: https://github.com/firehol/netdata/wiki/snmp.node.js

Alerts and auto-configuration of SNMP are not yet implemented.

**Comment by awestvik** [comment]
Thanks for the reply, I'm going to hold off until the auto-part is in place 👍 😇

**Comment by ktsaou** [comment]
ok. which switch do you have?

**Comment by ktsaou** [comment]
I close this.
If you need something more, open it again.
