### ISSUE TITLE
[web].mode = none

### ISSUE THREAD

**Issue by archuserr** [firehol/netdata#2070]
I'm a new user. I'm running netdata on a Raspberry Pi 3 with 32bit Arch (ArchLinuxARM-2017.04-rpi-2-rootfs.tar.gz).

The wiki says "[web].mode = none disables the API (netdata will not listen to any ports)" but that doesn't work for me. The web server is still running. It doesn't display the graphs, but it shows the gray background with "netdata" in the center.

http://127.0.0.1:19999/netdata.conf also still works, and it doesn't reflect the mode=none. It still has the default "# mode = multi-threaded".

/var/log/netdata/error.log is about 1200 lines long after running for an hour. I searched for "web" and "mode" but didn't see anything relevant.

Let me know if you need more information from me.

**Comment by ktsaou** [comment]
Could you please post the `[web]` section of your netdata.conf?

**Comment by archuserr** [comment]
after more testing, i think firefox is loading it from its cache. here's what i see even after restarting firefox:

[screenshot](http://imgur.com/a/SXVXe)

if i switch to chrome, i don't get anything. i've never seen another web site do this, so it confused me.
