### ISSUE TITLE
What is the datasource for netdata?

### ISSUE THREAD

**Issue by amankumarjain** [firehol/netdata#2071]

**Comment by ktsaou** [comment]
Hi, I am not sure I understand the question. Could you please describe what you need?

**Comment by amankumarjain** [comment]
where netdata store al data, for metric visualization

**Comment by ktsaou** [comment]
I see. In memory. It has its own fast memory database (or on disk, check `memory mode = map`). Metrics can be archived to time-series databases (graphite, opentsdb, etc), but netdata never reads from them.

**Comment by amankumarjain** [comment]
In my conf # memory mode = save, what this mean?

**Comment by amankumarjain** [comment]
what will be best tsd for metric visualization, which will work best with netdata.
influxdb, graphite, opentsdb, prometheus? (please suggest which will more best with big data and can be done horizontal clustering also if required)

**Comment by ktsaou** [comment]
> In my conf # memory mode = save, what this mean?

memory modes: https://github.com/firehol/netdata/wiki/Memory-Requirements#memory-modes

> what will be best tsd for metric visualization, which will work best with netdata.

netdata **writes metrics to time-series dbs**, but *never reads metrics from them*.
So, it is up to you to use whatever you need, for the purpose you need it. netdata does not need it. Most probably you are going to use grafana or another visualization tool on them.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, just post.
