### ISSUE TITLE
couchdb: dynamic graph creation after netdata has been started

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#2072]
Hello, 
First of all, want to say thank you for so nice monitoring service like Netdata, its really awesome!

I`m trying to write python plugin to monitoring CouchDB. 
Getting general CouchDB stats is simply (curl http://127.0.0.1:5984/_stats/ which returns json-stats data). 
Currently I have troubles with http://127.0.0.1:5984/_active_tasks, especially with replication tasks.

When Netdata starts, you cant know  when replication tasks will take place, you cant know local dbs will be replica tasks, also you cant know remote dbs. All this info will be present only when replication task will appear.
When it happens Netdata needs to create new graph with those info (source_host.source_db:target_host.target_db, replication percentage per source_db, etc.).

For now, using modified check() I create dynamic charts when python plugin inits (other words when restart Netdata) and modified update() to track new active tasks (at this step I create new order and charts -- but you still need manually refresh Netdata dashboard to show new graphs).

If you wish, you can review those plugin here: https://github.com/shellshock1953/share/blob/master/couchdb_dbstat.chart.py
config file here: https://github.com/shellshock1953/share/blob/master/couchdb_dbstat.conf

The main question - how to do this correctly?
How can I create dynamic graphs after Netdata has been started?

Thanks)

**Comment by ktsaou** [comment]
Hi, thanks!

Well, the netdata daemon will accept new charts any time. But, I haven't followed how this is done in python.

@l2isbad could you please help?

**Comment by ktsaou** [comment]
I mark this an enhancement and new plugin request. I hope you will make a PR once the couchdb plugin is ready :)

**Comment by l2isbad** [comment]
@shellshock1953 
[web_log](https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py) plugin creates dynamic dimensions/charts (dynamic charts when `detailed_response_aggregate`: no)

**Comment by shellshock1953** [comment]
@l2isbad thk, i`ll check those plugins.

**Comment by MarjanSadat** [comment]
hi and thanks for netdata again,
i have one text file which data is like this
```
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
......
```
is it possible to make a chart according this text file and show it in dashboard, thanks so much.
