### ISSUE TITLE
openvpn graphs not working 

### ISSUE THREAD

**Issue by csamsel** [firehol/netdata#2075]
Hello,
I have the following in my openvpn server configuration:
`status /var/log/openvpn-status.log 10`
which produces the following openvpn-status.log file:
```
OpenVPN STATISTICS
Updated,Tue Apr 11 11:24:07 2017
TUN/TAP read bytes,124932050
TUN/TAP write bytes,2889152473
TCP/UDP read bytes,2976046224
TCP/UDP write bytes,171779592
Auth read bytes,2889152699
pre-compress bytes,25983398
post-compress bytes,19061018
pre-decompress bytes,3453624
post-decompress bytes,3990548
END
```

i'm using the following netdata config (`ovpn_status_log.conf`):
```
default:
 log_path: '/var/log/openvpn-status.log'
 update_every: 10
```

netdata can successfully read the file:
```
oxygen-system-vm netdata # grep  ovpn /var/log/netdata/error.log 
2017-03-27 14:41:59: python.d INFO: ovpn_status_log_default Plugin was started succesfully
2017-03-27 14:41:59: python.d INFO: CHECKED OK: ovpn_status_log_default
```
But as output it shows the graphs `ovpn_status_log_default.users ` and `ovpn_status_log_default.traffic` always as 0.

I also wonder how netdata is suppose to display the number of users? It's not in status log file.

for reference:
```
oxygen-system-vm ~ # netdata -v
netdata 1.6.0

oxygen-system-vm ~ # openvpn --version
OpenVPN 2.4.1 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr  5 2017
library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
```

**Comment by ktsaou** [comment]
@l2isbad could you please check this?

**Comment by l2isbad** [comment]
> I also wonder how netdata is suppose to display the number of users? It's not in status log file.
```bash
openvpn --version
OpenVPN 2.3.4 i586-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 19 2015
```

```bash
cat /var/log/openvpn-status.log 

OpenVPN CLIENT LIST
Updated,Wed Apr 12 09:05:41 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
lgzvbox,10.4.23.197:59028,8328891,18562634,Tue Apr 11 07:14:12 2017
lgzwork,10.4.23.199:33334,1223653,849788,Tue Apr 11 07:13:23 2017
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
10.9.0.9,lgzvbox,10.4.23.197:59028,Wed Apr 12 09:05:32 2017
10.9.0.1,lgzwork,10.4.23.199:33334,Tue Apr 11 23:08:19 2017
GLOBAL STATS
Max bcast/mcast queue length,0
END
```

**Comment by csamsel** [comment]
Mh. Well you log file clearily looks different. I didnt know about `status-version`. Setting it to 3 results in the following file (not really different from the previous): 
```
OpenVPN STATISTICS
Updated,Wed Apr 12 08:03:16 2017
TUN/TAP read bytes,0
TUN/TAP write bytes,0
TCP/UDP read bytes,0
TCP/UDP write bytes,0
Auth read bytes,0
pre-compress bytes,0
post-compress bytes,0
pre-decompress bytes,0
post-decompress bytes,0
END
```
I suppose the available variables are dependent on the mode OpenVPN is running in. I'm using tap with preshared key (thats enough for a single client).

**Comment by l2isbad** [comment]
I'm not sure what calculation should we do with all that stuff but the output looks easy to parse.

Any suggestion?

```
TUN/TAP read bytes,124932050
TUN/TAP write bytes,2889152473
TCP/UDP read bytes,2976046224
TCP/UDP write bytes,171779592
Auth read bytes,2889152699
pre-compress bytes,25983398
post-compress bytes,19061018
pre-decompress bytes,3453624
post-decompress bytes,3990548
```

**Comment by csamsel** [comment]
I looked at graph because i was wondering about amount of traffic the VPN produced on the internect connecting, that would be (i think):
TCP/UDP read bytes <- Thats the inbound traffic
TCP/UDP write bytes <- outbound traffic

i assume TUN/TAP traffic is the traffic which was send over VPN (so without overhead and not factoring compression). Might be interesting as well, but not for me. The difference between TCP/UDP and TUN/TAP is probably the produced overhead (or saved traffic in case compression kicks in hard). 
No idea whats Auth read. The pre/post (de)compression is kinda self explaintory but i'm not interested in that.

I dont think fancy calculations are required here, just human readable format for bytes.

**Comment by Zolotkey** [comment]
I am having the same issue with the number of users connected. It updates the Traffic fine but not the amount of users. 

Freebsd-11.0-RELEASE
OpenVPN 2.4.0

This is my status file:
`OpenVPN CLIENT LIST
Updated,Fri Apr 14 11:37:42 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
2516-comlink,xxx.xxx.xxx.xxx,2696,3959,Fri Apr 14 11:37:11 2017
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
xxx.xxx.xxx.xxx,2516-comlink,xxx.xxx.xxx.xxx,Fri Apr 14 11:37:12 2017
GLOBAL STATS
Max bcast/mcast queue length,0
END`

**Comment by l2isbad** [comment]
That's how it works:

```python
raw_data = '''OpenVPN CLIENT LIST
Updated,Wed Apr 12 09:05:41 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
lgzvbox,10.4.23.197:59028,8328891,18562634,Tue Apr 11 07:14:12 2017
lgzwork,10.4.23.199:33334,1223653,849788,Tue Apr 11 07:13:23 2017
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
10.9.0.9,lgzvbox,10.4.23.197:59028,Wed Apr 12 09:05:32 2017
10.9.0.1,lgzwork,10.4.23.199:33334,Tue Apr 11 23:08:19 2017
GLOBAL STATS
Max bcast/mcast queue length,0
END'''

data_inter = re.search(r'(?<=Since ).*?(?=.ROUTING)', ' '.join(s.splitlines())).group()
data_inter # (all stuff between Since and ROUTING)
'lgzvbox,10.4.23.197:59028,8328891,18562634,Tue Apr 11 07:14:12 2017 lgzwork,10.4.23.199:33334,1223653,849788,Tue Apr 11 07:13:23 2017'

data_final = ' '.join(re.findall(r'\d{1,3}(?:\.\d{1,3}){3}[:0-9,. ]*', data_inter))
data_final # (ip_adress:port + bytes in, bytes out). 
# After this step we have all the information we need
'10.4.23.197:59028,8328891,18562634, 10.4.23.199:33334,1223653,849788,'

users = re.subn(r'\d{1,3}(?:\.\d{1,3}){3}:\d+', '',  data_final)[1]
users (number of ip.addresses)
2

traffic = re.findall(r'(?<=(?:,| ))\d+(?=(?:,| ))', data_final)
traffic # (list of bytes in, bytes out)
['8328891', '18562634', '1223653', '849788']

bytes_in = sum(int(x) for x in traffic[::2]) 
bytes_out = sum(int(x) for x in traffic[1::2])
```
It works with the output you provide (i replaced `xxx.xxx.xxx.xxx` with 1.2.3.4:1234)

**Comment by l2isbad** [comment]
@Zolotkey 
If ip address in your case is xxx.xxx.xxx.xxx (not xxx.xxx.xxx.xxx:yyyy) please change
https://github.com/firehol/netdata/blob/master/python.d/ovpn_status_log.chart.py#L35
to
```python
self.regex_users = r_compile(r'\d{1,3}(?:\.\d{1,3}){3}')
```

**Comment by ktsaou** [comment]
Is there anything pending on this?

**Comment by Zolotkey** [comment]
Nope, this was fixed for me.

**Comment by ktsaou** [comment]
perfect!

**Comment by ktsaou** [comment]
oops! I should wait @csamsel ...
@csamsel should I re-open it?

**Comment by csamsel** [comment]
nono, as i commented on the merge - it works for me.

**Comment by ktsaou** [comment]
ok, perfect!
