### ISSUE TITLE
Exposing headless slave data to Prometheus centrally

### ISSUE THREAD

**Issue by tyrken** [firehol/netdata#2076]
Following the wiki on integrating with Prometheus, and it's mainly working (with v1.5.2 - v2.0.0 Alpha isn't getting all metrics - see https://github.com/prometheus/prometheus/issues/2611).

However I'm using many headless slaves reporting data to a pair of central netdata servers with web gui/db/etc. & was hoping to just configure Prometheus to scrape from the central servers.  The URL http://localhost:19999/api/v1/allmetrics?format=prometheus reports **only the central servers own metrics (with instance label), omitting data from the slaves**.

I can use a sub-url to scrape slave data at the central node, http://localhost:19999/host/slave-host1/api/v1/allmetrics?format=prometheus, but that means a lot of configuration management in Prometheus...

Any chance of changing this?

**Comment by ktsaou** [comment]
Hi,

added it to PR #2077 
This is untested. Please install the https://github.com/ktsaou/netdata repo and report sucess or failure.

The format parameter to the `allmetrics` method, is called `prometheus_all_hosts`.

I would appreciate it, if you also update the wiki page at https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus to reflect this change.

**Comment by tyrken** [comment]
Cool - will try this tomorrow, thanks!

**Comment by tyrken** [comment]
Unfortunately it doesn't quite work, reporting the error:

```
text format parsing error in line 2422: second TYPE line for metric name "netdata_plugin_pythond_routes_default_run_time", or TYPE reported after samples
```

I'm guessing it doesn't like the repeated **TYPE** lines in :

```
...
# TYPE netdata_plugin_pythond_routes_default_run_time gauge
netdata_plugin_pythond_routes_default_run_time{instance="nlog1"} 2 1492011115003
....
# TYPE netdata_plugin_pythond_routes_default_run_time gauge
netdata_plugin_pythond_routes_default_run_time{instance="nlog2"} 3 1492011114757
...
```

**Comment by ktsaou** [comment]
hm... this will require a dictionary to be maintained and a lookup to be made for every metric. It will be quite an intensive operation... many thousands of dictionary lookups and searches (per server mirrored) for each call...

@brian-brazil we need your help with this. @tyrken requested to receive metrics for many netdata, in one go. So, just one call to netdata from prometheus returns metrics for N netdata hosts (in case you missed it, netdata 1.6 is able to stream its metrics in real-time to other netdata servers, so a central netdata is now feasible).

However, when metrics for different hosts is returned by netdata, prometheus issues this error:

```
text format parsing error in line 2422: second TYPE line for metric name "netdata_plugin_pythond_routes_default_run_time", or TYPE reported after samples
```

So, although the `TYPE` is the same, prometheus does not accept the response.

Is there anything we can do about this at the prometheus side?

As I said at the beginning, I can do it in netdata, but since netdata hosts are not homogeneous (certain hosts may have metrics that other hosts do not), a dictionary should be consulted to find out if each metric is already included in the response, or not. This is will be quite intensive...

**Comment by brian-brazil** [comment]
You could remove the HELP/TYPE lines. I'd benchmark it first though.

**Comment by ktsaou** [comment]
Are these lines only cosmetic/informative? Do they change anything inside prometheus?
If they are just info, I can comment them out. I see the `HELP` lines are already commented in netdata. I can't recall why...

**Comment by brian-brazil** [comment]
At the moment they are unused.

**Comment by ktsaou** [comment]
ok, thanks!

I have added 2 `allmetrics` options: `help=yes|no` and `types=yes|no`. The default for both is `no`.
So, by default netdata will not send `HELP` and `TYPE` lines to prometheus.

Example URL:

```
http://localhost:19999/api/v1/allmetrics?format=prometheus&help=yes&types=yes
```

The above gives lines like this:

```sh
# HELP netdata chart services.throttle_io_ops_write, dimension system.slice_gdm.service, value * 1 / 1 delta gives operations/s (counter)
# TYPE services_throttle_io_ops_write_system_slice_gdm_service counter
services_throttle_io_ops_write_system_slice_gdm_service{instance="ktsaou_laptop"} 0 1492035506382
# HELP netdata chart services.throttle_io_ops_write, dimension system.slice_systemd-machined.service, value * 1 / 1 delta gives operations/s (counter)
# TYPE services_throttle_io_ops_write_system_slice_systemd_machined_service counter
services_throttle_io_ops_write_system_slice_systemd_machined_service{instance="ktsaou_laptop"} 0 1492035506382
```

So, in `HELP` lines I also tried to provide some meaningful information on how netdata calculates the values it presents at the charts (of course netdata is more complicated than that - it also interpolates values to second boundaries).

**Comment by ktsaou** [comment]
@tyrken please give it another shot...

**Comment by tyrken** [comment]
This is working without error now - (assuming I leave TYPES off), and adding honor_labels to use the upstream hostnames as instance names makes it nicer.

It seems (from https://prometheus.io/docs/concepts/metric_types/) that Prometheus doesn't currently use the metric TYPE info yet (would have thought the counter types could be converted to a rate in the UI automatically, but..).

IMHO I would take the hit (maybe via parameter request) to make a temporary hash table to de-dupe the metric TYPEs on every scrape, possibly only allowing/de-duping those that are non-guages if that is the default assumption.  But as that's not needed now I'm happy for this to proceed as currently working.  I'll update the Wiki & close this later.

**Comment by ktsaou** [comment]
merged it.
