### ISSUE TITLE
Prometheus API - What are the metic units?

### ISSUE THREAD

**Issue by linickx** [firehol/netdata#2079]
Hi, Are the metric units for the Prometheus API documented somewhere?

For example, this is a comparison of RAM values, I'm fairly sure I've pasted like for like here but it's not obvious to me how `1912049` translates to ~`7473MB` 

1. `/api/v1/allmetrics?format=prometheus`
```
# TYPE system_ram_active gauge
system_ram_active{instance="iMAC"} 1912049 1492012806010
# TYPE system_ram_wired gauge
system_ram_wired{instance="iMAC"} 506852 1492012806010
# TYPE system_ram_throttled gauge
system_ram_throttled{instance="iMAC"} 0 1492012806010
# TYPE system_ram_compressor gauge
system_ram_compressor{instance="iMAC"} 60 1492012806010
# TYPE system_ram_inactive gauge
system_ram_inactive{instance="iMAC"} 1242750 1492012806010
# TYPE system_ram_purgeable gauge
system_ram_purgeable{instance="iMAC"} 4967 1492012806010
# TYPE system_ram_speculative gauge
system_ram_speculative{instance="iMAC"} 137305 1492012806010
# TYPE system_ram_free gauge
system_ram_free{instance="iMAC"} 394644 1492012806010
```

2. `/api/v1/allmetrics?format=shell`
```
# chart: system.ram (name: system.ram)
NETDATA_SYSTEM_RAM_ACTIVE="7473"      # MB
NETDATA_SYSTEM_RAM_WIRED="1980"      # MB
NETDATA_SYSTEM_RAM_THROTTLED="0"      # MB
NETDATA_SYSTEM_RAM_COMPRESSOR="0"      # MB
NETDATA_SYSTEM_RAM_INACTIVE="4854"      # MB
NETDATA_SYSTEM_RAM_PURGEABLE="24"      # MB
NETDATA_SYSTEM_RAM_SPECULATIVE="536"      # MB
NETDATA_SYSTEM_RAM_FREE="1537"      # MB
NETDATA_SYSTEM_RAM_VISIBLETOTAL="16404"      # MB
```

The counters, such as interface sent/received is also confusing. Through a little bit of trial and error I think `net_en1_received{instance="iMAC"} 2591036022 1492012997008` is a counter of bytes, not bits ... but I'm not 100% sure 😕 

Thanks in advance!

**Comment by ktsaou** [comment]
Hi, prometheus developers requested to receive metrics "as-collected", meaning that netdata does not alter them in any way.

The memory metrics collected from the system, are in pages (4KB/page on Linux).

The shell metrics exposed are the ones visualized by netdata.

**Comment by ktsaou** [comment]
And yes, the network metrics collected are bytes, as a counter.

**Comment by ktsaou** [comment]
Check this comment: https://github.com/firehol/netdata/issues/2076#issuecomment-293724534
I added some optional information on the data sent to prometheus, including the information you need.

**Comment by linickx** [comment]
Hi, Thanks for responding.

> The memory metrics collected from the system, are in pages (4KB/page on Linux).
> And yes, the network metrics collected are bytes, as a counter.

And thank you for clarifying these two specifics, however, I'm sure you don't want to answer for every single metric. I'd appreciate it if you can point me in the direction on how to find the "as-collected" metric units (I've not had much luck when trying to use github's repo search.)

**Comment by ktsaou** [comment]
merged the change
