### ISSUE TITLE
/data API with points=X returns (X-1) points

### ISSUE THREAD

**Issue by deadbird99** [firehol/netdata#208]
For example:

http://netdata.firehol.org/api/v1/data?chart=cpu.cpu0&points=2

returns 1 point, not 2.

**Comment by ktsaou** [comment]
you are so right!
thanks! I'll have a look (most probably I lost the equal sign in a comparison).

**Comment by caipeichao** [comment]
I debug the source code. Maybe this bug is caused by the function in `rrd2rrdr` from the file `rrd2json.c`.

See https://github.com/firehol/netdata/pull/253 for more detail.

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/pull/253#issuecomment-214519674

This behaviour is by design.
