### ISSUE TITLE
Customize email notifications recipient e-mail address

### ISSUE THREAD

**Issue by slrslr** [firehol/netdata#2081]
Hello,

i would like Netdata send e-mail notifications to different e-mail address, not to the server local mailbox.
How can i do it please? I found no setting in netdata.conf

https://github.com/firehol/netdata/wiki/email-notifications

Thank You

**Comment by ktsaou** [comment]
You case the global default in this file and line: https://github.com/firehol/netdata/blob/99d44b7d0c4e006b11318a28ba4a7e7d3f9b3bae/conf.d/health_alarm_notify.conf#L101

It should be in `/etc/netdata/`.

**Comment by ktsaou** [comment]
I updated the wiki with this info too.

**Comment by olegsidokhmetov** [comment]
Hello!

Change for what? For any email?

**Comment by cakrit** [comment]
> Hello!
> 
> Change for what? For any email?
> 
> I can uderstand, how setting *.conf file for sending alert to mine email o_0

Apologies, but I don't understand your question at all. Please create a new issue and tell us exactly what you need help with.

**Comment by ilyam8** [comment]
i think the problem is resolved
https://github.com/netdata/netdata/issues/2343#issuecomment-513848095
