### ISSUE TITLE
Seconds to hours conversion is imprecise

### ISSUE THREAD

**Issue by Komic** [firehol/netdata#2082]
If netdata's `history` parameter is set to 43200, the web interface will somehow display "_for 12 hours, 12 minutes and 12 seconds of real-time history._"

**Comment by ktsaou** [comment]
Hi,

netdata tries not to waste memory. It calls `mmap()` to get database memory. This call returns memory rounded in pages (each page is 4KB under Linux). So, since the system has reserved this memory for netdata, it uses it all, which results to this little difference.

**Comment by Komic** [comment]
I see, thanks. :)
