### ISSUE TITLE
[Bash Chart Plugin Issue] Dynamic chart dimensions?

### ISSUE THREAD

**Issue by grctest** [firehol/netdata#2083]
Hey,

This isn't directly a netdata issue, but more of an issue I've encountered whilst creating chart plugins.

I've been trying to create charts for the Gridcoin cryptocurrency client, and have been trying to display all client versions and their quantity on the network.

The chart and its dimensions are declared via a bash script within create_chart, this only runs once within the current [getpeerinfo.chart.sh](https://github.com/grctest/GRC-Netdata/blob/master/getpeerinfo/getpeerinfo.chart.sh) file and the chart is updated continuously via update_chart, if a new version come online in the network its version dimension won't be shown until the netdata instance was reset.

How does netdata handle adding and removing dimensions from a chart without resetting the netdata instance? Can I call create_chart from within update_chart when a new dimension is required? Is this a limitation of bash chart plugins?

Any advice?

Related issue: https://github.com/grctest/GRC-Netdata/issues/7

Cheers 👍 

Edit: Quick second question whilst I'm here: How do you show values less than 1 on the charts? I'm trying to show 0.01 and it's showing 0.

**Comment by ktsaou** [comment]
Hi,

You can add dimensions any time, by sending the CHART/DIMENSION lines again to netdata. Actually, only the CHART and new DIMENSIONs are required, but it is ok to send the whole chart again.

Unfortunatelly, you cannot dynamically delete dimensions (yet).

The netdata plugin API supports only integers, but you can specify multipliers and dividers for each DIMENSION. So, to get 0.01 resolution, multiply all values sent to netdata by 100 and specify a divider of 100 at the DIMENSION lines.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.
