### ISSUE TITLE
How to create a menu category in the custome DashBoard ?

### ISSUE THREAD

**Issue by phaothu** [firehol/netdata#2084]
Base on tv.html I have created my custom dashboard . Its work perfect . But now the list monitor of many server are too long . I need to category them into a menu sit on the right like the default netdata page. How can I do that ?

**Comment by ktsaou** [comment]
You can use bootstrap tabs for them:

http://getbootstrap.com/components/#nav-tabs

The idea is that you add sets of charts in different `<div>` (these will be the "screens") and link the tabs to each `<div>`.

Here is an example: http://jsfiddle.net/ktsaou/vcov0ypr/3/

**Comment by phaothu** [comment]
That's what i need thanks you so much.
