### ISSUE TITLE
Add ability to get disk utilization via Prometheus

### ISSUE THREAD

**Issue by ldelossa** [firehol/netdata#2087]
I've begging to build out dashboards based off Prometheus scraping Netdata. So far so good, however I don't quite see how I can use the metrics to get disk percentage utilization. I see the following:

```
disk_space___avail{instance="fresnel_fl4l"} 2176099 1492170957960
disk_space___used{instance="fresnel_fl4l"} 442525 1492170957960
disk_space___reserved_for_root{instance="fresnel_fl4l"} 0 1492170957960
```

From the allmetrics endpoint with a prometheus format, however this isn't a direct representation of Total OR per disk usage. I also see references to a "plugin" which may be what's representing disk utilization. 

Am I incorrect with these assumptions?

**Comment by ktsaou** [comment]
Yeah, I know this is confusing:

The original chart should be called `disk_space./`.

- But `/` is illegal for chart names, so netdata makes it `disk_space._`.
- Then prometheus considers [all non-alphanumeric characters except `_` as illegal](https://github.com/firehol/netdata/blob/0f37283905ebd01095e438165405ec590119887b/src/rrd2json.c#L179), which results to `disk_space__`.
- We should then add `.dimension` for each dimension, so the additional `.` is also converted to `_`, which results to `disk_space___dimension`.

[netdata pushes to prometheus all the information it has](https://github.com/firehol/netdata/blob/0f37283905ebd01095e438165405ec590119887b/src/rrd2json.c#L207-L232), so anything viewable on netdata dashboards, should be available to prometheus too.

**Comment by ktsaou** [comment]
In simpler words, the source for each prometheus metric is `disk_space./.avail`, but `.` and `/` are converted to `_`.

**Comment by ldelossa** [comment]
Okay let me explore this, I was under the impression that, that metric did not show accurate disk utilization. Also while I have you here - what is apps.Iread (or write) signifying here? Are these process read/writes which hit the page buffer and don't equate to direct disk activity? Do writes to socket FD's count within this metric? Also I don't see apps.Iread being exported in the prometheus stats.

**Comment by ktsaou** [comment]
lreads/lwrites are logical reads and writes. I think they include all I/O made by the processes matches. preads/pwrites are the physical reads and writes, i.e. the ones that were actually made to the physical medium.

**Comment by ktsaou** [comment]
And I see it is there:

```
apps_lreads_netdata{instance="boxe"} 930092541 1492182599594
apps_lreads_apps_plugin{instance="boxe"} 686325756 1492182599594
apps_lreads_charts_d_plugin{instance="boxe"} 0 1492182599594
apps_lreads_node_d_plugin{instance="boxe"} 137435168 1492182599594
apps_lreads_python_d_plugin{instance="boxe"} 13859246 1492182599594
apps_lreads_tc_qos_helper{instance="boxe"} 159150214 1492182599594
apps_lreads_httpd{instance="boxe"} 1566391 1492182599594
apps_lreads_proxy{instance="boxe"} 1847633 1492182599594
apps_lreads_ftpd{instance="boxe"} 0 1492182599594
apps_lreads_email{instance="boxe"} 0 1492182599594
apps_lreads_ppp{instance="boxe"} 0 1492182599594
apps_lreads_logs{instance="boxe"} 0 1492182599594
apps_lreads_samba{instance="boxe"} 0 1492182599594
apps_lreads_nfs{instance="boxe"} 0 1492182599594
apps_lreads_ssh{instance="boxe"} 0 1492182599594
apps_lreads_print{instance="boxe"} 0 1492182599594
apps_lreads_time{instance="boxe"} 0 1492182599594
apps_lreads_dhcp{instance="boxe"} 0 1492182599594
apps_lreads_named{instance="boxe"} 79952 1492182599594
apps_lreads_torrents{instance="boxe"} 0 1492182599594
apps_lreads_cron{instance="boxe"} 0 1492182599594
apps_lreads_media{instance="boxe"} 36444755 1492182599594
apps_lreads_X{instance="boxe"} 0 1492182599594
apps_lreads_ksmd{instance="boxe"} 0 1492182599594
apps_lreads_system{instance="boxe"} 0 1492182599594
apps_lreads_kernel{instance="boxe"} 0 1492182599594
apps_lreads_other{instance="boxe"} 0 1492182599594
apps_lreads_build{instance="boxe"} 0 1492182599594
```

netdata does not filter any charts. Each and every one is sent. The only ones not sent, are those that are marked for deletion (i.e. the ones that would not be presented on netdata dashboards either).

**Comment by ldelossa** [comment]
I'm sorry this is totally my mistake, I was looking for "I" not "L". my apologies.

**Comment by ldelossa** [comment]
So I do not believe the counters for my data drive are expressing the right values:

allmetrics endpoint, prometheus format output
```
# TYPE disk_space__data_avail gauge
disk_space__data_avail{instance="moosive_datanode_01"} 578420640 1492230919544
# TYPE disk_space__data_used gauge
disk_space__data_used{instance="moosive_datanode_01"} 48542922 1492230919544
# TYPE disk_space__data_reserved_for_root gauge
disk_space__data_reserved_for_root{instance="moosive_datanode_01"} 33558528 1492230919544
```

And netdata's graph:

![image](https://cloud.githubusercontent.com/assets/5642902/25060831/9a47fe3c-2174-11e7-89b5-a20334980e02.png)

**Comment by ktsaou** [comment]
If you update your netdata to the latest version and call the allmetrics URL like this:

```
http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus&help=yes&types=yes
```

it will show you the calculation:

```sh
# HELP netdata chart disk_space._, dimension avail, value * 4096 / 1073741824 gives GB (gauge)
# TYPE disk_space___avail gauge
disk_space___avail{instance="boxe"} 34298432 1492239474571
# HELP netdata chart disk_space._, dimension used, value * 4096 / 1073741824 gives GB (gauge)
# TYPE disk_space___used gauge
disk_space___used{instance="boxe"} 188043556 1492239474571
# HELP netdata chart disk_space._, dimension reserved_for_root, value * 4096 / 1073741824 gives GB (gauge)
# TYPE disk_space___reserved_for_root gauge
disk_space___reserved_for_root{instance="boxe"} 11904814 1492239474571
```

**Comment by ktsaou** [comment]
Linking #2079, #1876, #1993 (all these are about prometheus and dimension units)

**Comment by ldelossa** [comment]
Very cool, out of curiosity what is the base unit the disk metrics are in? 

Also since I want to update now, will running the "netdata-updater.sh" script remove my custom app groups files from /etc/netdata ?

**Comment by ktsaou** [comment]
> what is the base unit the disk metrics are in?

It seems to be pages...

> Also since I want to update now, will running the "netdata-updater.sh" script remove my custom app groups files from /etc/netdata ?

`netdata-installer.sh` (which is called by `netdata-updater.sh`) does not overwrite config files that have been edited. It calculates md5 sums of all files, and it overwrites them with newer versions only if their hash is known as a version shipped with netdata. In all cases, you will have a `.old` and a `.orig` version of the config.

**Comment by ldelossa** [comment]
Great!

This can be closed out.
