### ISSUE TITLE
Netdata client nodes in agent-only mode

### ISSUE THREAD

**Issue by jakedahn** [firehol/netdata#2088]
I am working on setting up a netdata in a master/slave configuration. All of the slave/client nodes ship their metrics to the master node, and the master node dumps those metrics to influxdb which can be used for grafana.

Basically I'm trying to follow the diagram that was outlined in this wiki page: https://github.com/firehol/netdata/wiki/monitoring-ephemeral-nodes#archiving-to-a-time-series-database

![e3569adc-02b8-11e7-9d55-4014bf98c1b3](https://cloud.githubusercontent.com/assets/8596/25057236/376aac22-212b-11e7-96f0-9f8bd632623e.png)

The one thing that I'm struggling to figure out is how to disable the web dashboard on all of the slave/client nodes. In the wiki page documentation it mentions `do not serve dashboards` which made me believe that there was an option to disable the web interface entirely, but I haven't been able to find the config flag or documentation for it. For example if I have 10 servers shipping their metrics upstream I won't be looking at server1:19999, server2:19999..., I would just at things downstream in grafana or the netdata master node dashboard.

Is it possible to disable the web interface and run netdata in agent-only mode?

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/wiki/Replication-Overview#netdataconf-configuration

You can:

1. disable the database on slave nodes, with `[global].memory mode = none`
2. disable the API on slave nodes, with `[web].mode = none`

With the above options, alarms will be checked only at the master node and the slaves will run with about 5MB or RAM each. Alarm will be run by the master for all nodes.

For optimizing the memory footprint of the master node and possibly support very long history for all nodes, check this: https://github.com/firehol/netdata/wiki/Memory-Requirements#running-a-dedicated-central-netdata-server

**Comment by jakedahn** [comment]
Awesome, thank you @ktsaou! I will give that a shot and report back later today.

**Comment by jakedahn** [comment]
It turns out that when you set `[web].mode = none` the server still binds to the `19999` port even though the API is not running.

I confirmed this via `netstat` on the host itself, and an nmap check from a remote machine.

```bash
netstat -plnt | grep netdata
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      28264/netdata
tcp6       0      0 :::19999                :::*                    LISTEN      28264/netdata
```

This is fine, but a little unexpected (i.e. if it's disabled, why is it binding to a port?). Since my goal is to also minimize network surface area for all of the servers running netdata as an agent, I also had to change the default bind ip to `127.0.0.1` to not accept remote connections on the default port `19999`.

For other folks going down this same path, here are the configuration options I used:

```ini
# File: /etc/netdata/netdata.conf
[general]
    memory mode = none

[web]
    mode = none
    bind to = 127.0.0.1
```

@ktsaou Thanks again for the pointers!

**Comment by ktsaou** [comment]
hm... this looks like a bug... let me trace it down...

**Comment by ktsaou** [comment]
ok, fixed it.
