### ISSUE TITLE
Seperate netdata master metrics listener from web server port

### ISSUE THREAD

**Issue by tjones136** [firehol/netdata#2089]
I've got netdata set up on two test machines, one a headless collector, the other a master.  It works as advertised.

I've got the master working behind apache, so I know I can do all of my happy fun web security there.

What I want to do is have the web server portion of netdata listen only on 127.0.0.1:19999, while still having the metrics stream in from the headless collector(s) on *:19999.  This way data can flow in, but users must go through apache to get any charts.

Is there a way to accomplish this configuration with a single netdata instance?  Or do I need to figure out how to run a proxy netdata instance on the same hardware as the master?

**Comment by ktsaou** [comment]
Hi,

netdata can bind to multiple IPs. For example you can use this:

```
[web]
    bind to = 127.0.0.1:19999 10.0.0.1:19998
```

You can use `127.0.0.1:19999` to be proxied via the apache, and `10.0.0.1:19998` to be used for streaming (protect this port with your firewall to allow access only via your netdata slaves).

The streaming protocol is not HTTP, so it cannot go through apache. Also, streaming requires the API key to be known, so your streaming functionality will be protected enough.

**Comment by tjones136** [comment]
Thanks for the quick reply.  So, more or less, I'll need to go with plan B.  AKA the hard way.

Which is what I expected, but I had to try just in case it was possible for my plan A to work.

BTW, thanks for creating and sharing netdata.  It really is a great piece of software who's impact is only beginning to be felt.

**Comment by tjones136** [comment]
For the record, I did figure out how to do what I was after.  I have a second netdata instance acting as a headless proxy between the "external" network and the internal loopback, and the primary netdata installation listening only to the loopback.  The proxying instance is set up so that if a collector can be disabled, it is.

Anyone hitting port 19999 on the master server gets the initial netdata background page and nothing else, but streamed data still traverses the proxy just fine.  Users logging in via the web server on port 80 of the master server get all the graphs I can give them.
