### ISSUE TITLE
Update process wipes apps_groups.conf

### ISSUE THREAD

**Issue by looterz** [firehol/netdata#209]
When I go through the netdata update process `/etc/netdata/apps_groups.conf` config is reset. 

Is there a way to only merge in changes, but keep my custom groups?

**Comment by ktsaou** [comment]
Ooops! This should not happen. Let me have a look.

**Comment by ktsaou** [comment]
@alonbl @philwhineray I am not sure how to do this with autoconf.
The file `apps_groups.conf` should not be overwritten.

**Comment by alonbl** [comment]
It is packager's mission to avoid overwrite of file.
rpm use %config, ebuild use config protect, etc...
additional complexity can be introduced in automake, however, based on
assumption that packaging is used there is no benefit of doing so.

**Comment by ktsaou** [comment]
Hm... what if I renamed it to `apps_groups.conf.default` and have the installer put in the right place if another one is not already there?

**Comment by alonbl** [comment]
this is not standard behavior.
you can have /usr/share/xx/conf/* as a set of defaults if you like, remove
the /etc content from package, defaults should be set in application and
override only if there is actual user config.

**Comment by ktsaou** [comment]
This has been fixed.
Please close it.
