### ISSUE TITLE
Negative Values in Graphs?

### ISSUE THREAD

**Issue by archuserr** [firehol/netdata#2090]
I'm seeing negative values in some of the graphs. Is this normal? Negative network packets transferred and negative bytes written to disk don't make sense to me. They're mostly (but not all) on the network and disk related graphs. The system processes graph says -2.

[Image](http://imgur.com/ITtnaDO)

I'm running Arch on a Raspberry Pi 3.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1842

> positive and negative numbers are artificial in netdata. We intentionally make numbers negative to improve visualization (i.e. in/inbound/read = positive, out/outbound/write = negative).

**Comment by archuserr** [comment]
thanks for the answer and quick response!
