### ISSUE TITLE
Arch IPv6

### ISSUE THREAD

**Issue by archuserr** [firehol/netdata#2091]
i'm having this same problem as issue #1843 i'm runing netdata 1.6.0

/proc/net/snmp6 is reporting invalid numbers and making a mess of the IPv6 graphs and filling up /var/log/netdata/error.log. i reported this to the arch arm people. (i assume it's specifically arch because raspbian doesn't have this problem.)

how do i disable the IPv6 graphs? it looks like i can disable proc, but i don't want to do that. i tried:
`#[plugin:proc:/proc/net/snmp6]` but that didn't work.

**Comment by ktsaou** [comment]
Hi,

You should have this section in `netdata.conf`:

```
[plugin:proc]
	# netdata server resources = yes
	# /proc/stat = yes
	# /proc/uptime = yes
	# /proc/loadavg = yes
	# /proc/sys/kernel/random/entropy_avail = yes
	# /proc/interrupts = yes
	# /proc/softirqs = yes
	# /proc/vmstat = yes
	# /proc/meminfo = yes
	# /sys/kernel/mm/ksm = yes
	# /sys/devices/system/edac/mc = yes
	# /sys/devices/system/node = yes
	# /proc/net/dev = yes
	# /proc/net/netstat = yes
	# /proc/net/snmp = yes
	# /proc/net/snmp6 = yes
	# /proc/net/softnet_stat = yes
	# /proc/net/ip_vs/stats = yes
	# /proc/net/stat/conntrack = yes
	# /proc/net/stat/synproxy = yes
	# /proc/diskstats = yes
	# /proc/net/rpc/nfsd = yes
	# /proc/net/rpc/nfs = yes
	# /proc/spl/kstat/zfs/arcstats = yes
	# ipc = yes
```

**Comment by ktsaou** [comment]
Linking #1510 that seems similar to this.

**Comment by archuserr** [comment]
that worked. thanks!

to help clueless people like me, would it make sense to have a section at the top of netconf.conf to enable/disable the major sections (System Overview, Memory, CPUs, Disks, ...)?

most users probably don't use IPv6.

many users probably install netdata on a single-user machine. 'User Groups', and 'Users' aren't much benefit to them, but you have to set `enabled = no` 32 times to disable them.

**Comment by ktsaou** [comment]
Nice it worked.

Well... all machines run deamons and should be running under different system users. So, Users and Groups is there for monitoring these deamons, not the humans using the systems (although this can be done too).

I could add an option to apps.plugin to stop reporting them, but I think most people should not disable them.

**Comment by archuserr** [comment]
i understand. thank you!
