### ISSUE TITLE
AWS RDS (for MySQL)

### ISSUE THREAD

**Issue by xtheonexuk** [firehol/netdata#2098]
Hi

Is it possible to monitor AWS RDS MySQL instances with netdata?

I've checked the FAQs but I couldn't see anything obvious though I'm sure I'm not the only one with this question in mind.

Thanks,
Dave

**Comment by ktsaou** [comment]
For mysql, netdata needs only the ability to connect. This exposes server performance metrics.
I don't know AWS has removed this functionality from their servers. If they haven't, it should work.
Have you tried it?

**Comment by xtheonexuk** [comment]
Thanks for the reply @ktsaou 
I haven't yet tried it as we aren't currently using RDS - we're planning moving our whole infrastructure to AWS in the next 6-8 weeks so I wondered if anyone else has RDS this and if it works.

**Comment by ktsaou** [comment]
I don't. If no one else responds, I would appreciate it if you update this ticket when you test it.

**Comment by xtheonexuk** [comment]
Of course @ktsaou - I shall update once I've tried it if no one else replies in the mean time.

**Comment by ktsaou** [comment]
Did you test it?

**Comment by ktsaou** [comment]
Cleaning up.
If you need help, just post.

**Comment by chudamanisanju** [comment]
I also want to try this,

**Comment by cakrit** [comment]
@chudamanisanju it should be a matter of configuring a job and any firewalls needed, so that the netdata running wherever you have it can access the mysql server in AWS. Is there something specific we need to know about AWS RDS that makes this difficult?

**Comment by chudamanisanju** [comment]
@cakrit you are right, we have to allow netdata IP in RDS. I will let you know once I have done this
