### ISSUE TITLE
dashboard with multiple hosts: handle properly unreachable hosts

### ISSUE THREAD

**Issue by azafred** [firehol/netdata#210]
I wrote myself a little flask 'script' that loops over all the hosts I have setup netdata on and displays a couple of charts from every host. 
While it sometimes works, it often ends up timing out on a few hosts, and it is generally very slow at loading all the charts. (loading them independently is very fast however). My forte is not in web design, and I was wondering if there were any tricks on speeding up the load time. 

Cheers,
Fred.

**Comment by ktsaou** [comment]
Nice!

Put all the charts on a page, one below the other. The charts from the same host should be inside one `div`, let's call this the host container. So, you are going to have several host containers, one for each host, and each container should include all the charts from the host you need to show.

Initially, the first host container should have `style.display = 'block'` and all the others `style.display = 'none'`. So, only the first is shown.

Then, use `setTimeout()` to switch the visibility of host containers. To switch hosts, set `style.display = 'none'` to the visible one and `style.display = 'block' to the host container you want to show. You may need to also call `NETDATA.onscroll()` just after you switch their visibility, to let the my dashboard code know you changed something (this will re-check which charts are visible).

Once every few few total loops, do a `location.reload()`. This will resolve the issue that the dashboard will permanently show as failed, charts that failed just once.

If you do it and you are happy with it, please share it. Others will need it too.

**Comment by ktsaou** [comment]
I edited my answer, so please read it on github.

**Comment by azafred** [comment]
Thanks @ktsaou, I will definitely give it a shot. Appreciate the help! I understand the first part, going to need to look into the second part :)

**Comment by azafred** [comment]
Funny, I was mostly doing things right, but had a couple hosts in the list that were not reachable due to firewall rules. Those unreachable hosts were causing everything to appear slow. Once I fixed that issue, everything is working very well!  
Very very nice job!

**Comment by ktsaou** [comment]
> but had a couple hosts in the list that were not reachable

You are right. I have to solve this issue.

**Comment by ktsaou** [comment]
The issue of properly reporting failed hosts has been solved with #271 (sorry, I forgot to update this).
I close this. If you need something more, open it again.

**Comment by ktsaou** [comment]
Hi,

PR #303 allows dashboards that collect data from multiple servers, to have independent refresh rate per chart. This means that if one netdata is slow for some reason (most probably network latency), the other charts will still be refreshed at full speed. So, the charts are de-coupled.

**Comment by ktsaou** [comment]
Also, CORS if fixed, so the other servers will not actually have any overhead. Before this update, in multi-server dashboards, all servers except the one servicing `dashboard.js` were getting twice as many requests (one OPTIONS and one GET) for each chart refresh.

**Comment by mdbootstrap** [comment]
Could you share some samples? tips to create a dashboard for multiples hosts on a single page?

**Comment by ktsaou** [comment]
> Could you share some samples? tips to create a dashboard for multiples hosts on a single page?

http://your.netdata.ip:19999/tv.html

Check also: 

- https://github.com/firehol/netdata/wiki/Custom-Dashboards
- https://github.com/firehol/netdata/wiki/Custom-Dashboard-with-Confluence
