### ISSUE TITLE
Ignore UPD Buffer Errors for Certain Ports

### ISSUE THREAD

**Issue by Monstar316** [firehol/netdata#2102]
I was just wondering if there is a way to add exceptions to netdata to allow it to ignore udp buffer errors for certain ports.

I'm getting notified almost every day about udp buffer errors but when I investigate on my system, it's always related to the same application that uses a particular port. In this case, it's Kodi that is generating the udp errors.

Also, just to say, netdata is awesome. It covers everything I need in terms of system monitoring. Good job 👍

**Comment by ktsaou** [comment]
Hi,

thanks!

Unfortunately, the kernel exposes just one metric for the whole system. So we cannot filter it by application or port.

**Comment by ktsaou** [comment]
You can of  course disable the whole alarm on this system. Just edit the file pointed by the alarm and comment out the alarm. Your change will not be overwritten when netdata is updated.

**Comment by Monstar316** [comment]
I thought that might be the case. I'll probably just do it that :-)
