### ISSUE TITLE
apache.chart.py and self signed ssl certs

### ISSUE THREAD

**Issue by Bluesnarf** [firehol/netdata#2105]
Is there a way to provide the option to have the new python Apache chart ignore self signed certificates? I noticed there aren't curl options like the deprecated bash version. If so can this option be added?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1845

**Comment by Bluesnarf** [comment]
After replacing base.py and adding the config parameter in #1845 the issue has been resolved with Python 2.7.13. Thanks for the fast response! I will close this issue.

**Comment by l2isbad** [comment]
@Bluesnarf 

> After replacing base.py 

Replacing? It's already in the base.py

https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L478-L490

**Comment by Bluesnarf** [comment]
You're correct, I replaced it needlessly. Thanks again for the fast
response. I tried replacing it after I noticed the chart wasn't showing up
and the error went away in the logs. It just took a moment to render so it
wasn't needed to be replaced.
