### ISSUE TITLE
hostname can't write correctly 

### ISSUE THREAD

**Issue by fooltux** [firehol/netdata#2106]
I configure  backend type is  graphite. and my servers's hostname format is XX-25-22-1.h.china.com.cn 。but when it write to database   , the XX-25-22-1 part is lost .
the metric should be  netata.XX-25-22-1.h.china.com.cn.chart.dimension , but now it's netdata.h.china.com.cn.chart.dimension

**Comment by ktsaou** [comment]
Check your `netdata.conf`. There should a `hostname` under `[global]` (which is also shown at the dashboard) and another one under `[backend]` (which overwrittes the first, for the backend functionality only).

Are these properly set?

**Comment by fooltux** [comment]
the hostname under  [global] and [backend]  are comment  both master and all  slaver .

**Comment by fooltux** [comment]
sorry   . I found the reason .It's the kairosdb plugin problem

**Comment by ktsaou** [comment]
ok. no problem.
