### ISSUE TITLE
charts.d.plugin won't start: parse scientific numbers from apache

### ISSUE THREAD

**Issue by Steto82** [firehol/netdata#211]
charts.d.plugin did not start 

after checking the Logs with: 

grep charts.d /var/log/netdata/error.log

>charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: 1
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
/usr/libexec/netdata/plugins.d/charts.d.plugin: Zeile 276: 10#13114e: Der Wert ist für die aktuelle Basis zu groß. (Fehlerverursachendes Zeichen ist »10#13114e«).
charts.d: No charts to collect data from.
16-04-12 10:49:29: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' called DISABLE. Disabling it.
16-04-12 10:49:29: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' on pid 17162 stopped.

and ps fax
>17147 ?        SNl    0:03 /usr/sbin/netdata -pidfile /var/run/netdata.pid
17150 ?        SN     0:00  \_ /bin/bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
20863 ?        SN     0:00  |   \_ sleep 0.998
17167 ?        SN     0:05  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1

i think there will be a problem at /usr/libexec/netdata/plugins.d/charts.d.plugin on line 276 but i do not know how to resolve this.

**Comment by ktsaou** [comment]
Hi,

can you run it by hand and post the output?

```sh
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1
```

**Comment by Steto82** [comment]
Hi,

here is teh output:

> charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 1
charts.d: 'airsearches' is enabled.
charts.d: 'apache' is enabled.
charts.d: 'ap' is enabled.
charts.d: 'cpu_apps' is enabled.
charts.d: 'cpufreq' is enabled.
charts.d: 'crsproxy' is enabled.
charts.d: 'example' is enabled.
charts.d: 'load_average' is enabled.
charts.d: 'mem_apps' is enabled.
charts.d: 'mysql' is enabled.
charts.d: 'nginx' is enabled.
charts.d: 'nut' is enabled.
charts.d: 'opensips' is enabled.
charts.d: 'postfix' is enabled.
charts.d: 'sensors' is enabled.
charts.d: 'squid' is enabled.
charts.d: enabled charts:  airsearches apache ap cpu_apps cpufreq crsproxy example load_average mem_apps mysql nginx nut opensips postfix sensors squid
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/airsearches.chart.sh'
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/apache.chart.sh'
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
/usr/libexec/netdata/plugins.d/charts.d.plugin: Zeile 276: 10#27274e: Der Wert ist für die aktuelle Basis zu groß. (Fehlerverursachendes Zeichen ist »10#27274e«).
charts.d: activated charts:
charts.d: activated charts:
charts.d: run_charts=''
charts.d: No charts to collect data from.
DISABLE
charts.d: cleaning up temporary directory /tmp/.netdata-charts.d-eQQCjVQKnh ...

**Comment by ktsaou** [comment]
Hm... The is a comment in line 247. https://github.com/firehol/netdata/blob/master/plugins.d/charts.d.plugin#L247 .

Can you remove the `#` character and retry?

**Comment by Steto82** [comment]
Here is the new outpu:

> charts.d:

 started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 1
charts.d: 'airsearches' is enabled.
charts.d: 'apache' is enabled.
charts.d: 'ap' is enabled.
charts.d: 'cpu_apps' is enabled.
charts.d: 'cpufreq' is enabled.
charts.d: 'crsproxy' is enabled.
charts.d: 'example' is enabled.
charts.d: 'load_average' is enabled.
charts.d: 'mem_apps' is enabled.
charts.d: 'mysql' is enabled.
charts.d: 'nginx' is enabled.
charts.d: 'nut' is enabled.
charts.d: 'opensips' is enabled.
charts.d: 'postfix' is enabled.
charts.d: 'sensors' is enabled.
charts.d: 'squid' is enabled.
charts.d: enabled charts:  airsearches apache ap cpu_apps cpufreq crsproxy example load_average mem_apps mysql nginx nut opensips postfix sensors squid
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/airsearches.chart.sh'
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/apache.chart.sh'
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
value=' 4.47003e-5' f='4.47003e-5', m='1000000'
/usr/libexec/netdata/plugins.d/charts.d.plugin: Zeile 276: 10#47003e: Der Wert ist für die aktuelle Basis zu groß. (Fehlerverursachendes Zeichen ist »10#47003e«).
charts.d: activated charts:
charts.d: activated charts:
charts.d: run_charts=''
charts.d: No charts to collect data from.
DISABLE
charts.d: cleaning up temporary directory /tmp/.netdata-charts.d-DHcnZPFrfR ...

**Comment by ktsaou** [comment]
ok. I found a solution. I will fix it tonight.

**Comment by Steto82** [comment]
great, thank you!

**Comment by ktsaou** [comment]
ok. here it is. You apache is reporting its metrics in scientific notation numbers.
Could you please test it?

**Comment by Steto82** [comment]
Hi,

here is the new output.

> 16-04-13

 08:38:56: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/charts.d.plugin 1 ' on pid 25302.
16-04-13 08:38:56: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' running on pid 25302
charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: 1
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: ap: configuration file '/etc/netdata/ap.conf' not found. Using defaults.
/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh: line 36: iw: command not found
charts.d: chart 'ap' check() function reports failure.
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
/usr/libexec/netdata/plugins.d/charts.d.plugin: line 288: 10#62061e: value too great for base (error token is "10#62061e")
charts.d: No charts to collect data from.
16-04-13 08:38:57: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' called DISABLE. Disabling it.
16-04-13 08:38:57: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' on pid 25302 stopped.


Still the same error:
/plugins.d/charts.d.plugin: line 288: 10#62061e: value too great for base (error token is "10#62061e")

**Comment by ktsaou** [comment]
Could you please uncomment the same line the post again the output?

**Comment by Steto82** [comment]
Sure, here is the Output from /usr/libexec/netdata/plugins.d/charts.d.plugin debug 1


> charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 1
charts.d: 'airsearches' is enabled.
charts.d: 'ap' is enabled.
charts.d: 'apache' is enabled.
charts.d: 'cpu_apps' is enabled.
charts.d: 'cpufreq' is enabled.
charts.d: 'crsproxy' is enabled.
charts.d: 'example' is enabled.
charts.d: 'load_average' is enabled.
charts.d: 'mem_apps' is enabled.
charts.d: 'mysql' is enabled.
charts.d: 'nginx' is enabled.
charts.d: 'nut' is enabled.
charts.d: 'opensips' is enabled.
charts.d: 'postfix' is enabled.
charts.d: 'sensors' is enabled.
charts.d: 'squid' is enabled.
charts.d: enabled charts:  airsearches ap apache cpu_apps cpufreq crsproxy example load_average mem_apps mysql nginx nut opensips postfix sensors squid
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/airsearches.chart.sh'
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh'
charts.d: ap: configuration file '/etc/netdata/ap.conf' not found. Using defaults.
/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh: line 36: iw: command not found
charts.d: chart 'ap' check() function reports failure.
charts.d: loading chart: '/usr/libexec/netdata/plugins.d/../charts.d/apache.chart.sh'
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
value=' 5.48297e-5' f='5.48297e-5', m='1000000'
/usr/libexec/netdata/plugins.d/charts.d.plugin: line 288: 10#48297e: value too great for base (error token is "10#48297e")
charts.d: activated charts:
charts.d: activated charts:
charts.d: run_charts=''
charts.d: No charts to collect data from.
DISABLE
charts.d: cleaning up temporary directory /tmp/.netdata-charts.d-YaLCr8E69G ...

**Comment by ktsaou** [comment]
Something is not right:

```sh
printf "%f\n" 5.48297e-5
-bash: printf: 5.48297e-5: invalid number
0,000000
```

Could you please give me the output of this:

```sh
 $ curl -s "http://127.0.0.1:80/server-status?auto"
```

Mine, gives this:

```
Total Accesses: 1410254
Total kBytes: 1658884
CPULoad: .000339104
Uptime: 1468575
ReqPerSec: .960287
BytesPerSec: 1156.7
BytesPerReq: 1204.53
BusyWorkers: 1
IdleWorkers: 49
Scoreboard: _________________________.......................................________W________________.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by Steto82** [comment]
Here it is:


> Total Accesses: 32
Total kBytes: 16
Uptime: 566642
ReqPerSec: 5.6473e-5
BytesPerSec: .0289142
BytesPerReq: 512
BusyWorkers: 1
IdleWorkers: 4
Scoreboard: ___W_.................................................................................................................................................

**Comment by ktsaou** [comment]
ok. I tested it now with your apache data and it works.
Please update again.

**Comment by Steto82** [comment]
Ok I tested it and it works fine!
Thx!
