### ISSUE TITLE
add chart mongodb to web netdata

### ISSUE THREAD

**Issue by samerkalil** [firehol/netdata#2111]
hi
i want add chart of mongodb database on website netdata
please help me

**Comment by samerkalil** [comment]
fadi@fadi-hw-srv1:/etc/netdata$ sudo su -s /bin/bash netdata
netdata@fadi-hw-srv1:/etc/netdata$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb
2017-04-21 12:28:27:  INFO: Using python v2
2017-04-21 12:28:28:  INFO: YAML output is ordered
2017-04-21 12:28:28: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-04-21 12:28:28: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mongodb']
2017-04-21 12:28:28: python.d DEBUG: mongodb: loading module configuration: '/etc/netdata/python.d/mongodb.conf'
2017-04-21 12:28:28: python.d DEBUG: mongodb: reading configuration
2017-04-21 12:28:28: python.d DEBUG: mongodb/local: job added
2017-04-21 12:28:28: python.d DEBUG: all job objects [<Service(local, initial daemon)>]
2017-04-21 12:28:28: python.d ERROR: mongodb_local Pymongo module is needed to use mongodb.chart.py
2017-04-21 12:28:28: python.d ERROR: mongodb_local check() failed - disabling job
2017-04-21 12:28:28: python.d ERROR: DISABLED: mongodb/local
2017-04-21 12:28:28: python.d DEBUG: overridden job names: []
2017-04-21 12:28:28: python.d DEBUG: all remaining job objects: []
2017-04-21 12:28:28: python.d FATAL: no more jobs
DISABLE

**Comment by samerkalil** [comment]
# netdata python.d.plugin configuration
#
# This file is in YaML format.
# Generally the format is:
#
# name: value
#

# Enable / disable the whole python.d.plugin (all its modules)
enabled: yes

# Prevent log flood
# Define how many log messages can be written to log file in one log_interval
logs_per_interval: 200

# Define how long is one logging interval (in seconds)
log_interval: 3600

# ----------------------------------------------------------------------
# Enable / Disable python.d.plugin modules
#default_run: no
#
# If "default_run" = "yes" the default for all modules is enabled (yes).
# Setting any of these to "no" will disable it.
# 
# If "default_run" = "no" the default for all modules is disabled (no).
# Setting any of these to "yes" will enable it.

# apache_cache: yes
# apache: yes
# bind_rndc: yes
# cpufreq: yes
# cpuidle: yes
# dns_query_time: yes
# dovecot: yes
# elasticsearch: yes

# this is just an example
example: no

# exim: yes
# fail2ban: yes
# freeradius: yes

# gunicorn_log has been replaced by web_log
gunicorn_log: no
# mongodb: true
# haproxy: yes
# hddtemp: yes
# ipfs: yes
# isc_dhcpd: yes
# mdstat: yes
# memcached: yes
# mysql: yes
# nginx: yes
# nsd: yes

# nginx_log has been replaced by web_log
nginx_log: no

# ovpn_status_log: yes
# phpfpm: yes
# postfix: yes
# postgres: yes
# redis: yes
# retroshare: yes
# sensors: yes
# smartd_log: yes
# squid: yes
# tomcat: yes
# varnish: yes
# web_log: yes
fadi@fadi-hw-srv1:/etc/netdata$ sudo cat python.d.conf
# netdata python.d.plugin configuration
#
# This file is in YaML format.
# Generally the format is:
#
# name: value
#

# Enable / disable the whole python.d.plugin (all its modules)
enabled: yes

# Prevent log flood
# Define how many log messages can be written to log file in one log_interval
logs_per_interval: 200

# Define how long is one logging interval (in seconds)
log_interval: 3600

# ----------------------------------------------------------------------
# Enable / Disable python.d.plugin modules
#default_run: no
#
# If "default_run" = "yes" the default for all modules is enabled (yes).
# Setting any of these to "no" will disable it.
# 
# If "default_run" = "no" the default for all modules is disabled (no).
# Setting any of these to "yes" will enable it.

# apache_cache: yes
# apache: yes
# bind_rndc: yes
# cpufreq: yes
# cpuidle: yes
# dns_query_time: yes
# dovecot: yes
# elasticsearch: yes

# this is just an example
example: no

# exim: yes
# fail2ban: yes
# freeradius: yes

# gunicorn_log has been replaced by web_log
gunicorn_log: no
# mongodb: true
# haproxy: yes
# hddtemp: yes
# ipfs: yes
# isc_dhcpd: yes
# mdstat: yes
# memcached: yes
# mysql: yes
# nginx: yes
# nsd: yes

# nginx_log has been replaced by web_log
nginx_log: no

# ovpn_status_log: yes
# phpfpm: yes
# postfix: yes
# postgres: yes
# redis: yes
# retroshare: yes
# sensors: yes
# smartd_log: yes
# squid: yes
# tomcat: yes
# varnish: yes
# web_log: yes

**Comment by l2isbad** [comment]
Yo @samerkalil 

> 2017-04-21 12:28:28: python.d ERROR: mongodb_local Pymongo module is needed to use mongodb.chart.py

You have to install `python-pymongo` package

**Comment by samerkalil** [comment]
okay i install the package and view the log on terminal, But I want and it to web(http://127.0.0.1:19999) .
How ??

**Comment by l2isbad** [comment]
> I want and it to web

it should be there if credential in the module configuration file are correct (host, port, user, password)

To find the problem please do one more time
```bash
sudo su -s /bin/bash netdata
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb
```

**Comment by samerkalil** [comment]
thanks :) :+1: :100:

**Comment by ne0c0de** [comment]
Hi,

Sorry for this dummy question but how can i install `python-pymongo` package? I searched it but couldn't find any solution

**Comment by ne0c0de** [comment]
ok, i installed first pip then installed that python package. nevermind my question :)
