### ISSUE TITLE
Prometheus CPU question

### ISSUE THREAD

**Issue by matejkramny** [firehol/netdata#2113]
Netdata outputs an arbitrary value. I want to display that as a % in grafana.

To display accurate metrics, you would need to grab `sum(irate(system_cpu_iowait[$interval]))`.

This works well, however the server has 16 cores. The value therefore needs to be divided by 16 to get an accurate % (0-100).

Is there any recommended way of showing metrics like this in grafana? There is no exported metric for number of cores, and I see no other way of showing this accurately.

**Comment by ktsaou** [comment]
netdata exposes CPU per core and as a system total.

- per code is `cpu.cpuN`, where `N` is the core number (zero-based)
- system total is `system.cpu`

The calculation netdata does is this:

1. These are `counters` meaning they always get incremented and their incremental difference over a period, gives the value we should use for that period.
2. Then, to find the percentage of each dimension, you need to divide its incremental difference, to the incremental difference of the sum of all dimensions. You will notice there is also an `idle` dimension (which is not visible on the dashboard). So, the sum of all dimensions is the total CPU consumed.

I know it is tricky, but this is how the Linux kernel works.

**Comment by matejkramny** [comment]
Thanks. So far I've managed to get an accurate display (0-100%) with the following.

It's basically `iowait / (sum of all system_cpu_* metrics)`. As far as I know, you can't do something like `irate(system_cpu_*{exported_instance=~"$server"}[$interval])` which would make the query easier.

(newlines and indentation just so it's easier to read)

```
sum(
    irate(system_cpu_iowait{exported_instance=~"$server"}[$interval]) /
    (
        irate(system_cpu_guest_nice{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_guest{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_steal{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_softirq{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_irq{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_user{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_system{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_nice{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_iowait{exported_instance=~"$server"}[$interval]) + 
        irate(system_cpu_idle{exported_instance=~"$server"}[$interval])
    )
)
```

Very hairy, but works. Any suggestions for improvement?

**Comment by ktsaou** [comment]
Well, I don't know.
@brian-brazil could you check if this prometheus query is appropriate for the calculating CPU utilization?

**Comment by matejkramny** [comment]
Would be great if there was a grafana dashboard specifically for netdata! :)

**Comment by ktsaou** [comment]
Yes, it would. Would you like to maintain one for netdata?

**Comment by matejkramny** [comment]
I can do.

Found one that uses the InfluxDB source ([grafana.com/dashboards/1295](https://grafana.com/dashboards/1295)). Is this maintained by netdata?

**Comment by ktsaou** [comment]
No, it is not maintained by netdata.
I have seen another reference to such a dashboard, here: https://github.com/firehol/netdata/issues/2017#issuecomment-289567700

If you want to maintain the "official" one, let me know. I'll add you to the netdata maintainers: https://github.com/firehol/netdata/issues/651

**Comment by matejkramny** [comment]
Yeah why not. I am currently writing a dashboard for netdata metrics

**Comment by ktsaou** [comment]
ok, nice.
When you have a link to it, let me know to add references to it. I'll also add a wiki page for you to add information on how to use it.

**Comment by brian-brazil** [comment]
That query looks about right.

**Comment by vincus** [comment]
I am also trying to achieve this, additionally for multiple hosts, but a little bit confused that I suppose the task is to get the total percentage, so for example an irate result 200 means 40% on 8 cores, therefore I do not understand how you get a good result just because you divide the iowait with the sum of others.

Could you explain a little bit ? Thank you

**Comment by matejkramny** [comment]
@vincus there is no exported metric with "total" cpu time.

If you want to find the percentage of CPU time (0 - 100%) you must first:

1. Find the total - do this by combining all CPU metrics
2. Divide by the metric you're interested in. Eg: `iowait / total = 0.2`
3. Times 100 to get a human-readable value out. `0.2 * 100 = 20%`

Attached screenshot of my dashboard setup for the `$server` variable.

<img width="647" alt="screen shot 2017-05-12 at 00 06 01" src="https://cloud.githubusercontent.com/assets/797608/25975558/de5d8398-36a6-11e7-8a41-56db71fb3a00.png">

**Comment by vincus** [comment]
Thanks, I understand the method now, only left some small problems:
First:
This query in prometheus (as well as in Grafanas of course)
`irate(system_cpu_idle[2m])`
gives result
`Element	Value
{exported_instance="sin_xx2",instance="192.168.xxx.xxx:19999",job="netdata-scrape"}	744.8
{exported_instance="sin_xx3",instance="192.168.xxx.xxx:19999",job="netdata-scrape"}	779.6
`
This one
`irate(system_cpu_idle{exported_instance=~"sin-xx2"}[2m])`
drops no data.

Any idea why ?

Also trying to find out to use wildcard labels in Grafana+Prometheus.
The goal is to automatically get an average CPU usage for hosts matching a specific pattern.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. Thank you guys...
