### ISSUE TITLE
Using the UrlService framework.

### ISSUE THREAD

**Issue by shadycuz** [firehol/netdata#2115]
I would like to work on a new Python module this weekend but I was unsure of how to run the code interactively? For example, if I want to run the code from nginx.chart.py how can I do so interactively in a python shell so I can dump the value of raw and see what my url is returning?

```
raw = self._get_raw_data().split(" ")
```

Thanks,
Levi

**Comment by l2isbad** [comment]
> python shell so I can dump the value of raw and see what my url is returning

Well, you can use the code from the UrlService `_get_raw_data` method:

```python
try:
    import urllib.request as urllib2
except ImportError:
    import urllib2
reply = opener.open('http://www.google.ru')
raw_data = reply.read().decode('utf-8', 'ignore')
raw_data
```

**Comment by shadycuz** [comment]
Awww I see. 

I actually was thinking I can't do what I want with the framework you guys have put in place.

What I am wanting is a single chart. With each "line" on the chart being data from a different url.

So something like this in the config section.

```
mychartsname:
  update_every:
  retries:
  priority:
  lines:
    line1name:
     url: http://myurl.com/mymetric
   line2name:
    url: http://mysecondurl.com/another metric
```

Can I still write my own plugin without a framework? What I'm wanting to do is really simple but has more advanced use cases down the road. I want to have a plugin that allows you to see see the metrics of other netdata servers. So say I have 5 servers I was to use the Netdata API URL for CPU to show the other 4 servers CPU metrics all on 1 chart on the 5th server. That way I can get an alert should a server go down. That is v1 simple version. For v2 I would like to mashup different charts on different servers to create something similar to the google charts example https://jsfiddle.net/ktsaou/L5y2eqp2/ . But I want to be more like Perfstack.  http://www.solarwinds.com/perfstack

**Comment by l2isbad** [comment]
>  With each "line" on the chart being data from a different url.

[ElasticSearch](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py) plugin uses UrlService to get data from 3 URLs

**Comment by shadycuz** [comment]
@l2isbad Yes I think I can do it with UrlService after looking at what you wrote for the elastic search plugin. However, I am still struggling. I see you def this function in the plugin.

```
def check(self):
```
and some of the important code resides in it but I don't see where you invoke it at? I think looking at this code I will be able to create my plugin but with a bit simpler approach.

**Comment by l2isbad** [comment]
`check() `executed for every job on start (every framework has it's own `check` and you can override it if you need; **return !True = stop job**)
https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L368-L374

**Comment by shadycuz** [comment]
Can I access the Overall Cpu gauge data? The one at the top in System Overview?. To start off simple I just want to be able to curl a single URL and get back a simple to use CPU value. I noticed when trying /api/v1/data?chart=system.cpu I get all the history for that chart. 

Thanks for your patience.

**Comment by shadycuz** [comment]
Also I think I know now why I have been struggling with the API calls. Your link in the wiki http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/firehol/netdata/master/web/netdata-swagger.yaml is not working correctly. It does not import your yaml. I'm using Chrome and all it talks about is a swagger pet store example and I was really confused as to why you would link to that.

**Comment by l2isbad** [comment]
http://my-netdata.io/swagger/#!/default/get_data
```bash
curl -s 'http://localhost:19999/api/v1/data?chart=system.cpu&after=-5&format=csv'
time,guest_nice,guest,steal,softirq,irq,user,system,nice,iowait
2017-04-26 22:12:23,0,0,0,0,0,15.25,2.75,0,0
2017-04-26 22:12:22,0,0,0,0.49383,0,17.03704,2.46914,0,0
2017-04-26 22:12:21,0,0,0,0,0,16.66667,1.99005,0,0
2017-04-26 22:12:20,0,0,0,0.24691,0,16.04938,1.7284,0,0
2017-04-26 22:12:19,0,0,0,0,0,15.25,2.25,0,1.5
```

**Comment by shadycuz** [comment]
@l2isbad 

So with this config
```
mychartsname:
  lines:
       line1name: 'http://myurl.com/mymetric'
       line2name: 'http://mysecondurl.com/another metric'
```
when I run ``` self.lines = self.configuration.get('lines')``` will that work? Will I get a list or dict or string? 

The problem Im trying to figure out is how to read in the number of lines from the config file to build the chart dictionary. The user might supply 1 url or N+ urls.

**Comment by shadycuz** [comment]
Must be a dict, code from web_log.
```
self.url_pattern = self.configuration.get('categories')  # dict
```

config 
```
nginx_log:
  name  : 'nginx_log'
  path  : '/var/log/nginx/access.log'

apache_log:
  name  : 'apache_log'
  path  : '/var/log/apache/other_vhosts_access.log'
  categories:
      cacti : 'cacti.*'
      observium : 'observium'
```

**Comment by l2isbad** [comment]
Ordered dict

**Comment by shadycuz** [comment]
@l2isbad I wanted to try a simple version of the plugin but had some troubles.

```
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug simple_dash
2017-04-29 19:19:29:  INFO: Using python v2
2017-04-29 19:19:29:  INFO: YAML output is ordered
2017-04-29 19:19:29: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-04-29 19:19:29: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['simple_dash']
2017-04-29 19:19:30: python.d DEBUG: simple_dash: loading module configuration: '/etc/netdata/python.d/simple_dash.conf'
2017-04-29 19:19:30: python.d DEBUG: simple_dash: reading configuration
2017-04-29 19:19:30: python.d DEBUG: simple_dash/testconfig: job added
2017-04-29 19:19:30: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-04-29 19:19:30: python.d ERROR: simple_dash_testconfig too many values to unpack
2017-04-29 19:19:30: python.d ERROR: DISABLED: simple_dash/None
2017-04-29 19:19:30: python.d DEBUG: overridden job names: []
2017-04-29 19:19:30: python.d DEBUG: all remaining job objects: []
2017-04-29 19:19:30: python.d FATAL: no more jobs
DISABLE
```

code is ...

```
from base import UrlService

try:
    import urllib.request as urllib
except ImportError:
    import urllib

ORDER = list()

CHARTS = dict()


class Service(UrlService):
    def __init__(self, configuration=None, name=None):
        UrlService.__init__(self, configuration=configuration, name=name)
        self.name = self.configuration.get('name')
        self.servers = self.configuration.get('servers')

    def check(self):

        if not all([self.servers,self.name]):
            return False

        self.order = [self.name]

        CHARTS[self.name] = {'options': [None, self.name,'Online', 'Health Check', 'simple_d$
                            'lines': []}

        for name, url in self.servers:
            CHARTS[self.name]['lines'].append([name,name,'absolute'])

        self.definitions = CHARTS

        return True

 def _get_data(self):
        """
        Format data received from http request
        :return: dict
        """

        try:
            results = {}
            for name, url in self.servers:
                request = urllib.request.urlopen(url)
                try:
                    if 200 <= request.getcode() <= 300:
                        results[name] = 1
                    else:
                        results[name] = 1
                except:
                    results[name] = 0

            return results
        except (ValueError, AttributeError):
            return None
```

config is...

```
testconfig:
  name : 'Random'
  servers  :
    google : 'www.google.com'
    facebook : 'www.facebook.com'
```

**Comment by l2isbad** [comment]
@shadycuz 

2017-04-29 19:19:30: python.d ERROR: simple_dash_testconfig too many values to unpack

```python
for name, url in self.servers

for name, url in self.servers.items()
```

**Comment by shadycuz** [comment]
@l2isbad I know I didn't use get_raw_data() like I should have. I wanted to keep it simple by only checking for a valid response. Should I try and rewrite my code to use get_raw_data() so It's easy to implement basic auth or will it be easy to implement basic auth as is? 

Thanks so much for your help!

**Comment by l2isbad** [comment]
@shadycuz 

> Should I try and rewrite my code to use get_raw_data() so It's easy to implement basic auth

yes

**Comment by l2isbad** [comment]
@shadycuz 

>  So say I have 5 servers I was to use the Netdata API URL for CPU to show the other 4 servers CPU metrics all on 1 chart on the 5th server
> Should I try and rewrite my code to use get_raw_data() so It's easy to implement basic auth

Here is the code. it's not optimized but should work (after https://github.com/firehol/netdata/pull/2140 will be merged). At least you can start from it 😄 
Keep in mind that the local server will always fail

```yaml
cpu:
  chart: 'system.cpu' # <- netdata chart
  # algo: 'incremental' # 'absolute' by default
  server_group:
    server1: # <- dimension name
      host: '127.0.0.1:19999'
    server2:
      host: '10.4.23.200:19999'
      # user = 'user' if needed
      # pass = 'pass' if needed
    server3:
      host: '127.0.0.1:19998'
```

```python
# -*- coding: utf-8 -*-

from base import UrlService
try:
        from queue import Queue
except ImportError:
        from Queue import Queue
from threading import Thread
from collections import namedtuple, defaultdict
from json import loads

# default module values (can be overridden per job in `config`)
# update_every = 2
update_every = 1
priority = 60000
retries = 60

SERVERS = namedtuple('SERVERS', ['url', 'opener'])

# charts order (can be overridden if you want less charts, or different order)
ORDER = list()
CHARTS = defaultdict(lambda: defaultdict(lambda: list()))


class Service(UrlService):
    def __init__(self, configuration=None, name=None):
        UrlService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.server_group = self.configuration.get('server_group')
        self.servers_to_poll = list()

    def check(self):
        chart = self.configuration.get('chart')
        if not chart:
            self.error('chart_name not specified')
            return False
        if not (self.server_group and isinstance(self.server_group, dict)):
            self.error('server_group not specified')
            return False

        self.servers_to_poll = build_servers_to_poll(self.server_group,
                                                     chart, self._build_opener)

        result = self._get_data()
        if not result:
            return False

        to_check = dict(self.servers_to_poll)
        for srv in to_check:
            if srv not in result:
                self.error('"%s" server removed due to non response' % srv)
                self.servers_to_poll.pop(srv)
            else:
                self._data_from_check[srv] = result[srv]
        self.create_chart_(chart)
        return self.servers_to_poll or False

    def _get_data(self):
        threads = list()
        queue = Queue()
        result = dict()

        for server in self.servers_to_poll:
            srv = self.servers_to_poll[server]
            th = Thread(target=self._get_data_from_server_, args=(queue, srv.url,
                                                                  srv.opener, server))
            th.start()
            threads.append(th)

        for thread in threads:
            thread.join()
            result.update(queue.get())
        return result or None

    def _get_data_from_server_(self, queue, url, opener, server):
        """
        Format data received from http request
        :return: dict
        """
        raw_data = self._get_raw_data(url, opener)

        if not raw_data:
            return queue.put(dict())
        try:
            data = loads(raw_data)
            data = round(sum(data['data'][0][1:]) * 1000)
        except (ValueError, TypeError, KeyError, IndexError):
            return queue.put(dict())
        else:
            return queue.put({server: data})

    def create_chart_(self, chart_name):
        algo = 'absolute' if self.configuration.get('algo', 'absolute') == 'absolute'\
            else 'incremental'
        chart = 'server_group_' + chart_name
        self.order = [chart]
        self.definitions[chart]['options'] = [None, '%s aggregate chart' % chart_name, 'units',
                                              chart_name, 'server_group.%s' % chart_name, 'stacked']
        for server in self.servers_to_poll:
            self.definitions[chart]['lines'].append([server, None, algo, '1', '1000'])


def build_servers_to_poll(server_group, chart, build_opener):
    def build_url_(host, chart_name):
        return 'http://%s/api/v1/data?chart=%s&after=-1' % (host, chart_name)

    def find_opener_options_(options, full_url):
        opener_options = dict(url=full_url)
        for option in ['user', 'pass', 'ss_cert', 'proxy']:
            if option in options:
                opener_options.update({option: options[option]})
        return opener_options

    result = dict()
    for server in server_group:
        srv = server_group[server]
        if 'host' not in srv:
            continue
        url = build_url_(srv['host'], chart)
        opener = build_opener(**find_opener_options_(srv, url))
        result.update({server: SERVERS(url=url, opener=opener)})
    return result

```

**Comment by ktsaou** [comment]
Is anything pending on this? Can we close it?

**Comment by shadycuz** [comment]
Yes, I think I got what I needed if I ever want to make this plugin a reality. 

Thanks,
Levi

**Comment by OdysLam** [comment]
> > With each "line" on the chart being data from a different url.
> 
> [ElasticSearch](https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py) plugin uses UrlService to get data from 3 URLs
> 
> > Can I still write my own plugin without a framework?
> 
> I think if `UrlService `is not suitable for some reason better to update `UrlService`. But yes, you can - if so `SimpleService` is your choice.
> 
> Looks more clear
> 
> ```yaml
> mychartsname:
>   lines:
>        line1name: 'http://myurl.com/mymetric'
>        line2name: 'http://mysecondurl.com/another metric'
> ```

Hey @ilyam8,

Do you think that it would be a good idea to mention in the docs that multiple urls are indeed supported and point to the elasticsearch module?

cheers :)

**Comment by ilyam8** [comment]
I see there is optional `url` param in the `get_raw_data` UrlService method


https://github.com/netdata/netdata/blob/c3b201b2b5e745e2bf736f77ed771933d3eb0024/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py#L116-L131

So, yes, it is possible to use different URLs. Probably rabbitmq is a better example becuase it is simple (no threads) and it fetches data from 3 different URLs.

> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py

**Comment by OdysLam** [comment]
Yes! It's way simpler,  should I PR a change in the docs where these 2 plugins are mentioned in the urlservice part of the python.d doc as examples of multiple urls?

Because it is not mentioned explicitly and if you hadn't tell me, I would never have discovered rabitmq.

**Comment by ilyam8** [comment]
Please do, why not 👍
