### ISSUE TITLE
netdata slaves do not update the master for newly added dimensions

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2117]
@l2isbad in one system, I have errors about this specific dimension:

```
netdata: ERROR: Cannot find dimension with id '1_0' on stats 'web_log_nginx_netdata.http_version' (web_log_nginx_netdata.http_version).
```

Somehow the plugin did not add the dimension but sent metrics for it to netdata. It flooded the logs with it (triggering of course the log flood protection).

**Comment by l2isbad** [comment]
Does this repeat after the restart?
It's strange because "add dimension" code is the same for `http version/http method/detailed response` charts.

**Comment by ktsaou** [comment]
No, it does not.

Pretty strange. This happened on the build server http://build.my-netdata.io/ in which I aggregate several other hosts. This is why I added the host to the log lines, to understand which host did that.

If it was on localhost (the native collector) this is a bug in the python code.
If it was a slave, this is a bug in the streaming functionality of the slaves.

Let's wait for it to happen again...

**Comment by ktsaou** [comment]
At #2123 this appeared on the numa metrics. So, this is a bug of the netdata slaves.

**Comment by ktsaou** [comment]
found it.

The problem occurred after restarting the slave. This is why it appeared:

1. The dimensions have an `exposed` flag, that tracks if they have been sent to the master.
2. When a slave with a local database restarts, the dimensions are saved to disk. The saved data include this `exposed` flag.
3. netdata was not resetting the flag when loading the dimensions from disk, resulting in these errors.

I am making a PR now.
