### ISSUE TITLE
Fail2ban Plugin - Jails with numbers in name

### ISSUE THREAD

**Issue by Cyb0rk** [firehol/netdata#2118]
Hi,

If I use jails with numbers in the jail name they aren't recognized by netdata.

For example:

`[dovecot-pop3imap]` isn't recognized by netdata but `[viper-dovecot-pop-imap]` is. Fail2ban accepts these jails without any problem.

Is there a way to implement numbers in jailnames in netdata?

**Comment by l2isbad** [comment]
@Cyb0rk 

> Is there a way to implement numbers in jailnames in netdata?

done

**Comment by ktsaou** [comment]
merged it.
