### ISSUE TITLE
iOS app suggestion: auto-detect mobile browser and set sequential refresh mode

### ISSUE THREAD

**Issue by edwardd06** [firehol/netdata#212]
Would it be possible to create an iOS app to monitor your netdata installation as the web browser only works for a few seconds (chrome for iOS)then it stops refreshing even with always set to when to reload the charts. It doesn't even load all the charts. It would be lovely and worth paying for a iOS app

**Comment by ktsaou** [comment]
Strange. I just tested on my iphone with chrome and everything works.

Are you trying on your netdata or the demo site?
The demo site has a cut off threshold and asks for captcha after a number of requests (I had to do this - many abuse it).

Can you post a screenshot of the problem?

For sure, the mobile version does not have a menu system, so you have to scroll down. But all charts are shown and all work.

**Comment by edwardd06** [comment]
I managed to get or working by changing the synchronisation to sequential as parallel seems to effect the iPhone's performance.

**Comment by ktsaou** [comment]
I see. I can probably detect this and switch it to sequential automatically.
I'll leave this open to fix it.

**Comment by simonnagl** [comment]
```javascript
var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
```

(http://stackoverflow.com/questions/9038625/detect-if-device-is-ios#9039885)

**Comment by ktsaou** [comment]
Check PR #1726 
Will be merged in a while...
