### ISSUE TITLE
/etc/netdata/health_alarm_notify.conf overwritten during update

### ISSUE THREAD

**Issue by ShaunPCcom** [firehol/netdata#2122]
Every time netdata gets updated through the system package manager, /etc/netdata/health_alarm_notify.conf gets overwritten. This behavior happens on Arch Linux. As a result, I have to turn off email notifications and reset my pushover.net settings each update.

**Comment by ktsaou** [comment]
hm... the package manager should provide some means to protect the configuration.
@svenstaro any ideas?

**Comment by ShaunPCcom** [comment]
Some additional information:
In Arch Linux, a new config file is usually placed in the correct folder appended with .pacnew. Then the Admin has to merge the original config file and the new one manually. I'm not sure how this accomplished, but I hope that helps point in the right direction.

**Comment by svenstaro** [comment]
I fixed this in netdata-1.6.0-3. Please just report an Arch Linux bug next time.

**Comment by ShaunPCcom** [comment]
I have updated and confirmed this is functioning correctly. Thank you.
