### ISSUE TITLE
Values rounding??

### ISSUE THREAD

**Issue by Foggyx420** [firehol/netdata#2127]
when the market percent changes for 1hour or 24 hour are low they seem to round off. for example if the value being pushed to chart is 0.9 it says 0 on chart. when I try to add to another chart cents for what the market value is and the output is 1.2433 cents it displays 1.00 on chart.

market charts for percent change

        onehourVal=$(jq '.[].percent_change_1h' $GRCCMC)
        twentyfourVal=$(jq '.[].percent_change_24h' $GRCCMC)
        sevendaysVal=$(jq '.[].percent_change_7d' $GRCCMC)

market chart for usd to cryptocurrency

        usdVal0=$(jq -r '.[].price_usd' $GRCCMC | tr -d '\n')
        usdVal1=$(echo $usdVal0 \* 100 | bc | tr -d '\n') #don't use multiplier in chart the \n causes issues and results in 0

now ive tested these values in a personal .sh script and they show up properly and correct. but when passed to chart it appears netdata is rounding the small number.

BEGIN market.usdprice
SET usd = $usdVal
END

BEGIN market.percent_change
SET onehour = $onehourVal
SET twentyfour = $twentyfourVal
SET sevendays = $sevendaysVal
END

everything passes fine but netdata not displaying it as it receives it (rounds down).

any idas?

**Comment by ktsaou** [comment]
oh... I see.

The plugins API support only integers. But you can set a divider at the `DIMENSION` line. So, set the divider to 1000 and multiply all values by 1000.

Let me check if this info is missing from the wiki...

**Comment by ktsaou** [comment]
yeap, it was missing. I added it: https://github.com/firehol/netdata/wiki/External-Plugins#data-collection

Thanks!

**Comment by Foggyx420** [comment]
thank you sir!
