### ISSUE TITLE
Netdata registry issues ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by colomb001** [firehol/netdata#2129]
I can't get the registry to work for the my-netdata menu. 
netdata 1.6.1_rolling
CentOS 7.3.1611 ( all updates applied )

![image](https://cloud.githubusercontent.com/assets/12431065/25390888/6fcbf0d6-299a-11e7-8f2d-10e12aa0fd7c.png)

when navigating to the url in the error in Firefox:
![image](https://cloud.githubusercontent.com/assets/12431065/25390756/0b93a9e2-299a-11e7-895b-c2c73861fdf5.png)

**Comment by ktsaou** [comment]
Hi, netdata does not support SSL directly. You have to pass it through nginx or apache and setup SSL on that server. The wiki has several guides for all web servers.

**Comment by colomb001** [comment]
Could we make note of that in https://github.com/firehol/netdata/wiki/mynetdata-menu-item ?

The instructions in "Every netadata can be a registry" section make it sound like all that is needed are the configuration changes to the netdata.conf and it should work.

Thank you.

**Comment by colomb001** [comment]
Because netdata.conf has https for the default registry server, I was under the impression it was necessary to have ssl if I wanted to use my own registry server despite the fact that https://github.com/firehol/netdata/wiki/mynetdata-menu-item clearly shows a registry server without https. My mistake.
