### ISSUE TITLE
Unable to start netdata ("Cannot cd to directory")

### ISSUE THREAD

**Issue by falzm** [firehol/netdata#2130]
Hi, I'm trying to give netdata a test run: I've built the binary in a Docker container, but when I try to run it on the host (not in a Docker container) it complains about not being able to access a directory:

```
marc@carbon:~/netdata/netdata% ~/netdata/netdata/usr/sbin/netdata -D -c ~/netdata/netdata/etc/netdata/netdata.conf -i 127.0.0.1 -u marc
2017-04-25 19:26:24: netdata: FATAL: Cannot cd to directory '/netdata/netdata/etc/netdata' # : No such file or directory

2017-04-25 19:26:24: netdata: INFO : Saving database [0 hosts(s)]...
2017-04-25 19:26:24: netdata: INFO : netdata exiting. Bye bye...
```

It looks like it "remembers" the `/netdata/netdata/etc/netdata` directory from compile time (using `./netdata-installer.sh --install /netdata --dont-start-it` command), but as far as I've looked in the command line options there's nothing to override this path (hardcoded in the binary from compilation). Did I miss something?

Thank you in advance.

**Comment by ktsaou** [comment]
Hi, the file `~/netdata/netdata/etc/netdata/netdata.conf` can override all directories decided at compile time.

Check this for an example: https://github.com/firehol/netdata/issues/1841#issuecomment-282609090

**Comment by falzm** [comment]
That did the trick. Thanks!
