### ISSUE TITLE
Nginx proxy

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#2131]
Was trying to run netdata-master behind Nginx using reverse proxy using the instructions below
https://github.com/firehol/netdata/wiki/Running-behind-nginx

But ended up with the following error
"File does not exist, or is not accessible: /usr/share/netdata/web/netdata"

#778 refers to this and indicates that it works but I don't see this happening in my case.
The Nginx configuration is as follows

server {
        listen       80;
        server_name  localhost;
        location /netdata {
             return 301 /netdata/;
        }

        location ~ /netdata/(?<ndpath>.*) {
           proxy_redirect off;
           proxy_set_header Host $host;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Server $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_http_version 1.1;
           proxy_pass_request_headers on;
           proxy_set_header Connection "keep-alive";
           proxy_store off;
           proxy_pass http://netdata/$ndpath$is_args$args;
           gzip on;
           gzip_proxied any;
           gzip_types *;
    }
}

when accessed using http://monitoring-server/netdata I get the error.

**Comment by l2isbad** [comment]
same error here (File '/usr/share/netdata/web/netdata/' does not exist, or is not accessible)
https://github.com/firehol/netdata/issues/1346

**Comment by gamefundas** [comment]
@ktsaou I suppose we don't have a solution to this at this point.

**Comment by ktsaou** [comment]
This is purely a path re-writing problem at nginx. It calls netdata like this `http://172.0.0.1:19999/netdata/`, which results to `file /usr/share/netdata/web/netdata not found`. Note that there is a `/netdata` at the end. This should not be there.

**Comment by gamefundas** [comment]
I remember doing this but ended up with the netdata grey background. The page failed to load any chart or widget. Chrome developer indicated that it couldn't load the charts. I will reproduce this and get back with the exact error.

**Comment by ktsaou** [comment]
perfect!

**Comment by ktsaou** [comment]
Did you manage to reproduce it?

**Comment by gamefundas** [comment]
I may not use this afterall as all my Netdata clients are streaming stats to master. We can close this for now.

**Comment by sas5437** [comment]
May not be the most helpful post, but I ran into a similar problem.
My nginx sites-available (part that matters)
```
    location /netdata {
        proxy_pass http://127.0.0.1:19999/;
    }
```
Then I noticed a 404 on the request to download `dashboard.js` like gamefundas mentioned.
![image](https://user-images.githubusercontent.com/167059/30443114-7916a48e-994c-11e7-9c03-a7b593b1306e.png)
I resolved this by modifying the `/usr/share/netdata/web/index.html:3600`
```
<script type="text/javascript" src="dashboard.js?v20170815-14"></script>
```
To
```
<script type="text/javascript" src="netdata/dashboard.js?v20170815-14"></script>
```
Now my dashboard loads up great!

**Comment by ktsaou** [comment]
@sas5437 you should not edit `index.html`. This will fix part of the problem. The right way to use `proxy_pass` to rewrite the URL sent to the upstream server. It is described here: https://github.com/firehol/netdata/wiki/Running-behind-nginx#as-a-subfolder-to-an-existing-virtual-host
