### ISSUE TITLE
Option for fixed value on y-axis

### ISSUE THREAD

**Issue by Bezod** [firehol/netdata#2132]
There should be an option to set a fixed value on the y-axis. As it is now, netdata is magnifying the graph which is good for seeing how values are currently changing but requires the user to look at the asigned values. Having fixed y values makes it easier to monitor the system from a distance.

**Comment by ktsaou** [comment]
Hi, the problem with this is that netdata does not know the value of "the whole". It cannot know, for example, the cap for interrupts, sql queries/s, etc.

So, this is only possible for things we know upfront they have a cap, like the CPU chart that is always 0% - 100%.

**Comment by ktsaou** [comment]
What we could do though, is have all the charts with the same context, under the same family (i.e. cpu interrupt charts, for all cores), have the same scale. Now, they are independent.

**Comment by Bezod** [comment]
Thanks for the quick response! That would work. In this case I was thinking about a fixed percentage although I forgot to mention it, glad to hear something like that would be possible.

**Comment by ktsaou** [comment]
ok, I did the following:

1. per core cpu utilization charts are now fixed to 0 - 100%
2. all charts under the same family (submenu on the dashboard), with the same context and the same units, have aligned y-range.

Both will be merged with #2121 .

**Comment by Bezod** [comment]
Thanks! Look forward to the next release

**Comment by ktsaou** [comment]
merged it.
