### ISSUE TITLE
Refresh dashboard when new charts appears

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#2134]
Hello,

I`m creating new Netdata plugin (Python) to monitor [CouchDB stats](https://github.com/shellshock1953/share/blob/master/plugin/couchdb_AT_dbstat.chart.py).
After checking and creating charts, i add new data into self.order and self.definitions. But to actually see those data i need to refresh dashboard. 
General question: How can I say to Netdata to refresh dashboard when whole new charts appears?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1920

**Comment by shellshock1953** [comment]
issue in #1920 is related, but not the same. 
To get new chart appear, I have to refresh all dashboard, but I can`t do it manually by pressing F5. So is there a way that Netdata do it automatically?

**Comment by ktsaou** [comment]
Unfortunately this functionality does not exist on the default dashboard. You can do it with just 3 lines of javascript on custom dashboards and probably a web browser plugin (autorefresh with timeout).

Could you please describe your use case? I might be able to help some other way...

**Comment by shellshock1953** [comment]
I`m trying to create monitoring plugin (using python) for CouchDB #2072

One of the subjects -- be able to monitor active replication tasks (sequence). The problem is: you can`t know what host (and remote dbs) will be in those replication tasks.
So, when whole new task appear, whole new chart needed to present data.

My plugin is watching for a new replication tasks, creates new charts but can`t show them without refreshing dashboard.

**Comment by ktsaou** [comment]
hm... what if you create dimensions on a fixed number of charts? So, you will have a few charts for monitoring replication and tasks will add dimensions to them.

Are the tasks finite or unlimited? If they are unlimited, you have a problem. netdata will create files for these charts and dimensions. They will fill your disks.

**Comment by shellshock1953** [comment]
Do you mean create fake-dimension with some static data (for example with 0), just to keep replication chart present? If so -- it is possible, but its more dirty hack than real solution.
Tasks is finite.

Maybe, I really need to use custom board. But -- what refresh handler I need to use, to refresh whole dashboard, because using of time counter is not desirable.

**Comment by ktsaou** [comment]
> Do you mean create fake-dimension with some static data (for example with 0), just to keep replication chart present? If so -- it is possible, but its more dirty hack than real solution.

No, I don't mean that.

If the tasks are finite, you could use the same logic many plugins of netdata already use (apps.plugin, systemd services, etc).

This logic says that:

1. A fixed set of charts are created
2. Dimensions are added dynamically - to add a dimension to an existing chart, just re-send the chart definition to netdata
3. Dimensions not collected do not need to be sent to netdata - just don't send them at all - send only the ones you collect data for - the not collected dimensions will show gaps on the charts

**Comment by shellshock1953** [comment]
Ok, thank you.

**Comment by l2isbad** [comment]
Looks like we need to add `add_new_dimension` method to the [SimpleService](https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L57).

**Comment by ktsaou** [comment]
please do so...  (nice new avatar)...
