### ISSUE TITLE
`service netdata restart` fails due to missing pidfile

### ISSUE THREAD

**Issue by Techwolfy** [firehol/netdata#2135]
When I attempt to restart netdata via the `service` command, I get the following error:

```
[ ok ] Stopping the netdata daemon...done (not running - there is no /var/run/netdata/netdata.pid).
[....] Starting the netdata daemon...2017-04-27 13:49:50: netdata: ERROR: IPv4 bind() on ip '127.0.0.1' port 19999 failed. (errno 98, Address already in use)
2017-04-27 13:49:50: netdata: ERROR: Cannot bind to ip '127.0.0.1', port 19999
2017-04-27 13:49:50: netdata: FATAL: Cannot listen on any socket. Exiting... # : Success

2017-04-27 13:49:50: netdata: INFO: Saving database...
2017-04-27 13:49:50: netdata: INFO: netdata exiting. Bye bye...
failed.
```

This appears to be due to 53262d9f6e00dca3ac1f761a5b7f459e347ef6f0 (issue #773), which removes the daemon PID file in favor of the systemd service interface. However, my system still uses sysvinit, which does need the PID file. This is the default configuration for systems upgraded from Debian wheezy or earlier.

EDIT: I'm using version 1.5.0 of netdata from the [Debian unstable repository](https://packages.debian.org/unstable/netdata), which seems to have [Debian-specific patches applied](http://metadata.ftp-master.debian.org/changelogs/main/n/netdata/netdata_1.5.0+dfsg-4_changelog).

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.
