### ISSUE TITLE
What is the source of CPU usage per user ?

### ISSUE THREAD

**Issue by luvpreetsingh** [firehol/netdata#2136]
How does netdata collect the CPU, RAM usage per user, application and group ? 
Which file is the source for this in ubuntu 16.04 ?
 
Like in the picture below ?

![screenshot from 2017-04-28 02-58-52](https://cloud.githubusercontent.com/assets/23127804/25516650/657ba2b8-2c09-11e7-94f6-08f2891d762a.png)

**Comment by ktsaou** [comment]
This is done by `apps.plugin`. Apps.plugin walks through the entire process tree (using `/proc` under linux) and aggregates per user utilization based on the process found running.

To find the user and group of each process, it just examines its PID directory under /proc:

```
dr-xr-xr-x.  9 costa   costa                 0 Apr 29 19:05 2171
dr-xr-xr-x.  9 root    root                  0 Apr 29 01:33 22
dr-xr-xr-x.  9 postfix postfix               0 Apr 29 18:18 22187
dr-xr-xr-x.  9 costa   costa                 0 Apr 29 19:05 2235
dr-xr-xr-x.  9 costa   costa                 0 Apr 29 19:05 2251
dr-xr-xr-x.  9 root    root                  0 Apr 29 01:33 23
dr-xr-xr-x.  9 costa   costa                 0 Apr 29 19:05 2330
dr-xr-xr-x.  9 costa   costa                 0 Apr 29 19:05 2353
dr-xr-xr-x.  9 root    root                  0 Apr 29 16:11 23672
```

To get its CPU utilization it uses `/proc/PID/stat`.
