### ISSUE TITLE
Can Netdata execute Linux command when certain Alarm is triggered?

### ISSUE THREAD

**Issue by slrslr** [firehol/netdata#2137]
Hello, can Netdata execute certain Linux command when certain Alarm is triggered?

example when it reports critical disk utilization, i would like Netdata to execute command i define, example:
commandhere | mail -s "command" me@mail.com

There is /etc/netdata/health.d/disks.conf but does not seem to support any command.

**Comment by ktsaou** [comment]
Yes, of course you can. All alarms accept an `exec` line. Write a script to be executed and append:

```
exec: /path/to/your/script.sh
```

More info: https://github.com/firehol/netdata/wiki/health-configuration-reference#alarm-actions

keep in mind your script will be executed for all statuses, even CLEAR or UNDEFINED ones.
netdata will pass 20 parameters to your script. Check them here: https://github.com/firehol/netdata/blob/eb551d2c19c2fbbc5d702fd8d01f4c1e78b4f990/plugins.d/alarm-notify.sh#L124-L143

**Comment by ktsaou** [comment]
oh, I forgot. You can also add your own commands to `/etc/netdata/health_alarm_notify.conf`. But in this case, you will have to filter by chart and status (this file is executed for every alarm and status). The parameters are already parsed into variables when this file is sourced.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.

**Comment by slrslr** [comment]
in /etc/netdata/health.d/net.conf i aded into "check for packet storms" section "exec" line:

to: sysadmin
exec: /root/scripts/log_server_resources_usage.sh

and when i do:
stat /root/scripts/log_server_resources_usage.sh

>   File: `/root/scripts/log_server_resources_usage.sh'
  Size: 380             Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 2361589     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (  496/ netdata)   Gid: (  495/ netdata)
Access: 2017-05-27 16:31:05.746166226 +0000
Modify: 2017-05-27 16:31:05.746166226 +0000
Change: 2017-05-28 09:39:33.874241488 +0000

THat script contains line: cat /tmp/nodewatch_stats >> /tmp/server_resources_snapshot

and stat shows that this logfile was last accessed/modified 2017-05-27, so it seems that netdata is not executing this bash script? I already received netdata e-mail regarding packet storm, so the alarm was triggered.

**Comment by ktsaou** [comment]
Fetch this from your browser:

```
http://netdata.ip:19999/api/v1/alarms?all
```

And search for the alarm. What exec line does it say?

**Comment by slrslr** [comment]
it shows these exec lines: "/usr/libexec/netdata/plugins.d/alarm-notify.sh"

>   File: `/usr/libexec/netdata/plugins.d/alarm-notify.sh'
  Size: 51471           Blocks: 104        IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 6047703     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)

**Comment by ktsaou** [comment]
Could you please post your alarm configuration?

**Comment by slrslr** [comment]
here it is: https://pastebin.com/JgEq928f
I believe i just added exec line.

**Comment by ktsaou** [comment]
ok, did you restart netdata after adding the `exec` line? You can also `killall -USR2 netdata` to have it reload health configuration.

For you exec line to be respected, the `http://your.netdata.ip:19999/api/v1/alarms?all` has to show it.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by MarjanSadat** [comment]
Hi and Thanks For Netdata:)
i added exec: /usr/libexec/netdata/plugins.d/test.sh to net_drops.eth1.inbound_packets_dropped
and in my script i wrote
#!/usr/bin/env bash
systemctl start mysql
but it didn't execute, could you please help me?
one thing more, in http://localhost:19999/api/v1/alarms?all for this template it also added my script.
thanks

**Comment by ktsaou** [comment]
Could you please change it to this:

```sh
#!/usr/bin/env bash

name="${7}"
status="${10}"

echo >&2 "$(date): MYALARM '${name}' WITH STATUS '${status}', ATTEMPTING TO START MYSQL"
systemctl start mysql
```

You can find all the parameters that may be useful for you, here: https://github.com/netdata/netdata/blob/521136c74cd1e3a7aff45099155335ac51fc9a41/health/notifications/alarm-notify.sh.in#L170-L189

The next time it triggers, please check `/var/log/netdata/error.log` with this:

```sh
grep MYALARM /var/log/netdata/error.log
```

If it has logged the line, it run. You just need to handle it in a better way.

**Comment by ktsaou** [comment]
netdata runs as user `netdata`.

Probably you should run these commands with `sudo` and give netdata the ability to run sudo without a password.

For best protection, I would allow user `netdata` to only run your script with sudo and change the script to this:

```
#!/usr/bin/env bash

name="${7}"
status="${10}"

if [ "${UID}" != "0" ]
then
    # we don't run as root
    # let's sudo ourself
    echo >&2 "$(date): MYALARM '${name}' WITH STATUS '${status}', UID '${UID}', ATTEMPTING TO RUN MYSELF WITH sudo"
    sudo "${0}" "${@}"
    ret=$?
    # hm... sudo failed
    [ $ret -ne 0 ] && echo >&2 "$(date): MYALARM '${name}' WITH STATUS '${status}', UID '${UID}', FAILED TO RUN MYSELF WITH sudo"
    exit $ret
fi

echo >&2 "$(date): MYALARM '${name}' WITH STATUS '${status}', UID '${UID}' ATTEMPTING TO START MYSQL"
systemctl start mysql
```


To allow user `netdata` run the specific script with `sudo`, create the file `/etc/sudoers.d/netdata` with these contents:

```
netdata ALL=(ALL) NOPASSWD: /usr/libexec/netdata/plugins.d/test.sh
```

Make sure the path to your script is ok.

**Comment by MarjanSadat** [comment]
thanks ktsaou,
my main os is centOS but i did it in ubuntu too, and i did what exactly you said and this is out put

centOs output:
```
Sat Nov 10 15:21:04 IRST 2018: MYALARM 'inbound_packets_dropped_ratio' WITH STATUS 'CRITICAL', UID '997', ATTEMPTING TO RUN MYSELF WITH sudo
Sat Nov 10 15:21:04 IRST 2018: MYALARM 'inbound_packets_dropped_ratio' WITH STATUS 'CRITICAL', UID '997', FAILED TO RUN MYSELF WITH sudo
```
ubuntu output is as same but mysql.service not start.
could you please tell me what should i do in centos?

**Comment by MarjanSadat** [comment]
it worked finally, thank you so much Mr.ktsaou

**Comment by MarjanSadat** [comment]
it worked finally, thank you so much Mr.ktsaou
