### ISSUE TITLE
Caddy reverse proxy not working 

### ISSUE THREAD

**Issue by Dedsec1** [firehol/netdata#2138]
Hi, 

i recently reinstalled my OVH server with Debian 8.7 and wanted to install netdata to monitor it.  to make it short on my old server i was running Ubuntu 16.10 with caddy running as for my reverse proxys. but for some reason when i tried to setup netdata running on localhost:19999 with an reverse proxy such as this: 

domain.com/netdata/ {
	proxy / 127.0.0.1:19999 {
	transparent
	}

*as you can see Caddy follows the same layout as nginx almost but more easier to use.

netdata says the following File does not exist, or is not accessible: /usr/share/netdata/web/netdata/

i have setup netdata before many times on different servers so iam not sure if its an bug or mabey an typo somewhere in the code.

**Comment by ktsaou** [comment]
As I see it, caddy is sending the path of the url to the backend server.

So, since your url is `http://domain.com/netdata/`, caddy extracts `/netdata/` and sends it to the backend server, so netdata is accessed with `http://127.0.0.1:19999/netdata/`, which of course does not exist, thus the error.

This is a caddy configuration problem. Unfortunately, I don't know how to help you fix it.

**Comment by Dedsec1** [comment]
Gotcha, most of the time Caddy works on Ubuntu so it could be something with Debian

**Comment by Dedsec1** [comment]
@ktsaou heres the funny thing, just tested on my ipad and netdata loads up just fine. it must be something with an user agent or something within netdata.

**Comment by ktsaou** [comment]
netdata logs the url it receives at `/var/log/netdata/access.log`. Could you please check it?

**Comment by ktsaou** [comment]
Did you solve it?
I am closing this now. If you need help, just post.

**Comment by cwmp** [comment]
works find for me. I am using the current caddyserver version 0.10.3. please retry

https://<domain.tld>/netdata/ {
	proxy /	http://127.0.0.1:19999 {
		transparent
		}
	push
}
