### ISSUE TITLE
Create Debian backport

### ISSUE THREAD

**Issue by Techwolfy** [firehol/netdata#2139]
The only dependency of `netdata` and `netdata-data` not already in Debian Stable is `fonts-font-awesome`, which already has a working backport. I was able to install the package from unstable without any issues (aside from #2135, which is unrelated), but it would be nice to have an official backport.

**Comment by FedericoCeratto** [comment]
@Techwolfy you might want to open a bug on the Debian BTS for this.

**Comment by Techwolfy** [comment]
I created [bug #861638](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861638) on the Debian BTS requesting the backport.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.
