### ISSUE TITLE
centminmod

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#214]
@centminmod

following your https://github.com/firehol/netdata/issues/148#issuecomment-209107981

I saw your project. Very interesting.

These may be interesting for you:

1. You can use FireHOL, which has SYNPROXY support (SYN floods protection): https://github.com/firehol/netdata/wiki/Monitoring-SYNPROXY and basic IDS (anti-port scan): https://github.com/firehol/firehol/wiki/Working-with-traps

2. If you use FireHOL, you can also use FireQoS which will provide extra protection: https://github.com/firehol/netdata/wiki/You-should-install-QoS-on-all-your-servers

3. I see a few very interesting apps you use. Probably we could write a few data collectors for netdata for them.

**Comment by centminmod** [comment]
@ktsaou sweet great timing on this created issue and thanks for the heads up info :+1: 

not sure if it's the place, but i did reply/ask a question on reddit post of yours https://www.reddit.com/r/linux/comments/4ce83u/netdata_linux_performance_monitoring_done_right/d1ib3tz and my question https://www.reddit.com/r/linux/comments/4ce83u/netdata_linux_performance_monitoring_done_right/d20dsxf

it was regarding your comment on raising the `update every` value for systems with a single processor on raspberry pi v1 

> does this recommendation apply to number of cpu core/threads in general ? i am planning to integrate netdata into my lemp stack installer and users can install on various vps specs including 1, 2 or 4+ cpu core/thread based vpses. So I should be adding to my integration script auto detection and auto tuning of the update every number based on detected cpu cores ?

i'm thinking of along the lines of
```
CPUS=$(grep -c "processor" /proc/cpuinfo)

# adjust update frequency based on cpu core/thread count
if [ "$CPU" -eq '1' ]; then
    sed -i "s|# update every = 1|update every = 2|g" /etc/netdata/netdata.conf
fi
```

> I see a few very interesting apps you use. Probably we could write a few data collectors for netdata for them.

indeed a few would include

* php-fpm pools
* memcached server
* redis server
* elasticsearch
* zend opcache

example of some of the stats I track via munin with my forum integrated display https://community.centminmod.com/pages/mstats/

**Comment by ktsaou** [comment]
> does this recommendation apply to number of cpu core/threads in general ? i am planning to integrate netdata into my lemp stack installer and users can install on various vps specs including 1, 2 or 4+ cpu core/thread based vpses. So I should be adding to my integration script auto detection and auto tuning of the update every number based on detected cpu cores ?

No, it does not. The only reason to increase `update_every` is if the CPU is too slow. Most server systems today are pretty fast.

As a precaution, you could provide a default `/etc/netdata/netdata.conf` that keeps the netdata `update_every = 1`, but sets `apps.plugin`, `charts.d.plugin` and `node.d.plugin` to ` 2 `. Especially `charts.d.plugin` and `apps.plugin` are very CPU intensive (more than the netdata daemon).

Regarding the script you mention, you can just provide a default `/etc/netdata/netdata.conf`. The installer will not overwrite it.

I am thinking of something like this:

```
[global]
	history = 7200
	update every = 1

[plugins]
	tc = no

[plugin:charts.d]
	update every = 2

[plugin:apps]
	update every = 2

[plugin:node.d]
	update every = 2
```

The `tc = no` line is needed only if you don't setup QoS (I suggest to setup QoS though - it saved me on a few DDoS attacks).

Last, I'll have a look at the apps you use for collecting data.

**Comment by centminmod** [comment]
@ktsaou thanks for the clarification especially for the CPU intensive chart and apps plugin settings as some Centmin Mod LEMP installs are on Low end systems with 128-256MB ram, and 1 cpu systems. Usually, i script it so to detect system environments memory and cpu resource availability and auto optimize settings for nginx, php-fpm, mariadb mysql based on number of cpu cores and memory available for base defaults. So will do the same for charts and apps plugin settings :)

**Comment by ktsaou** [comment]
perfect!

**Comment by ktsaou** [comment]
Closing this too.
