### ISSUE TITLE
Zero-based graph for system.active_processes

### ISSUE THREAD

**Issue by h2suzuki** [firehol/netdata#2141]
Thank you for this great project.
We are using netdata like a visual replacement of the aggregated system commands like top, vmstat, iostat, ...,etc., because our target machine is head-less configuration (no keyborad, no screen, no mouse).

I have one query.  Is it possible for me to draw system.active_processes zero-based?  (any configuration parameter available?)

The sudden increase in the number of processes can be observed by system.forks graph, so we want to see the gradual increases of the total number of processes using system.active_processes.  For that regard, zero-based graph is preferred.

![2017-05-01_00h39_32](https://cloud.githubusercontent.com/assets/4984414/25565707/671edf54-2e07-11e7-99bb-407fb59bd25f.png)

**Comment by ktsaou** [comment]
Hi.

On custom dashboards you can do it. On the default dashboard though, no you cannot.

I think however the request is probably wrong. If you get zero based active processes, what you will get is just a straight line. There are not enough pixels for it to show 1/192 detail. Are you sure this is what you want?

**Comment by h2suzuki** [comment]
Thank you for the reply.
I will try custom dashboards.   Should I edit share/netdata/web/dashboard.html?

Yes, I'm pretty sure that this is what I want, because we have many cron job tasks, and the graph will not be static.  The change by a few number of processes do not matter for me either, so flat graph is appropriate for that case for me.  The change will be shown by forks graph anyway.  :-)

**Comment by ktsaou** [comment]
Start with `tv.html`.

The option you need to pass to any chart to make it zero based is `data-dygraph-valuerange="[min, max]"`. If you set `min` to zero and `max` to `null`, the chart will be zero based.

**Comment by h2suzuki** [comment]
Hi,
How could this issue be closed?  Any page on Wiki should I check?  (or can I close it by myself?)

**Comment by ktsaou** [comment]
It is ok. I am closing it.
