### ISSUE TITLE
ping to the default gateway and the name server

### ISSUE THREAD

**Issue by h2suzuki** [firehol/netdata#2142]
One more query.  Thanks in advance!

Is it possible to ping to the default gateway and the name server, by automatically finding the addresses under DHCP environment?

The RTT to the default gateway tends to reflect the local Wifi congestion of our IoT device.  Also the RTT to the name server tends to reflect the congestion of the uplink network beyond the local subnet (beyond the gateway) in cases like that a shopping mall with lots of people overwhelm ISP uplink bandwidth.  Because of DHCP, no fixed addresses are available.  If fping can figure out the address by itself using routing table or dig command output, that would be a great help for us.

**Comment by ktsaou** [comment]
hm... I think the default gateway and the name server IPs will never change. So your IoT device will have a dynamic IP due to DHCP, but the default gateway and the name server should have fixed IPs.

Am I missing something?

I see there is a `dns_query_time.chart.py` plugin in netdata. This resolves hostnames to IPs and measures the time it took. I have never used it though.

**Comment by h2suzuki** [comment]
The default gateway will change depending on the subnet given by the dhcp server.  When we bring our IoT device from one place to another, the network configuration will completely change, e.g. one place gives 192.168.10.1 for the gateway, while another place can give 192.168.111.1.  When we connect through VPN network, the address will change to 192.168.30.1, too, for example.
We can find the address by something like `ip route show | awk '$1=="default"{print $3;exit}'`

Thanks for the information about dns_query_time.chart.py.
I was using v1.6.0, but updated to master HEAD to use the plugin.
Then, when I run it, it causes error.  It seems like passing --prefix=/opt/scorer (i.e. our project name) to ./configure causes the failure.

```
sudo -u netdata /opt/scorer/libexec/netdata/plugins.d/python.d.plugin 1 debug dns_query_time
2017-05-01 02:46:32:  INFO: Using python v2
2017-05-01 02:46:32:  INFO: YAML output is ordered
2017-05-01 02:46:32: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-05-01 02:46:32: python.d ERROR: /etc/netdata/python.d.conf reading error: [Errno 2] No such file or directory: '/etc/netdata/python.d.conf'
2017-05-01 02:46:32: python.d INFO: MODULES_DIR='/opt/scorer/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['dns_query_time']
2017-05-01 02:46:32: python.d ERROR: dns_query_time: configuration file '/etc/netdata/python.d/dns_query_time.conf' not found. Using defaults.
2017-05-01 02:46:32: python.d DEBUG: dns_query_time: setting configuration for only one job
2017-05-01 02:46:32: python.d DEBUG: dns_query_time: job added
2017-05-01 02:46:32: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-05-01 02:46:32: python.d ERROR: dns_query_time 'python-dnspython' package is needed to use dns_query_time.chart.py
2017-05-01 02:46:32: python.d ERROR: dns_query_time check() failed - disabling job
2017-05-01 02:46:32: python.d ERROR: DISABLED: dns_query_time/None
2017-05-01 02:46:32: python.d DEBUG: overridden job names: []
2017-05-01 02:46:32: python.d DEBUG: all remaining job objects: []
2017-05-01 02:46:32: python.d FATAL: no more jobs
DISABLE
```

Where should I touch to resolve the error?

**Comment by ktsaou** [comment]
ok.

The file [/etc/netdata/fping.conf](https://github.com/firehol/netdata/blob/master/conf.d/fping.conf) is a shell script. So, you can include that little command to figure out the default gateway. If you add the gateway IP to the [hosts](https://github.com/firehol/netdata/blob/eb551d2c19c2fbbc5d702fd8d01f4c1e78b4f990/conf.d/fping.conf#L22) variable, it will be pinged by fping and visualized by netdata.

Regarding the second question, before running the plugin by hand, do this:

```
export NETDATA_CONFIG_DIR="/opt/scorer/etc/netdata"
```

Of course, make sure the path exists.
Then the plugin will run.

**Comment by h2suzuki** [comment]
After exporting `NETDATA_CONFIG_DIR`, dns_query_time worked for me.
Thank you very much!

I hope that the attached patch could be applied for convenience of others.
```
diff --git a/build/subst.inc b/build/subst.inc
index 9682cf8..bac7e73 100644
--- a/build/subst.inc
+++ b/build/subst.inc
@@ -2,6 +2,7 @@
 	if sed \
 		-e 's#[@]localstatedir_POST@#$(localstatedir)#g' \
 		-e 's#[@]sbindir_POST@#$(sbindir)#g' \
+		-e 's#[@]configdir_POST@#$(configdir)#g' \
 		-e 's#[@]sysconfdir_POST@#$(sysconfdir)#g' \
 		-e 's#[@]pythondir_POST@#$(pythondir)#g' \
 		$< > $@.tmp; then \
diff --git a/system/netdata.service.in b/system/netdata.service.in
index 6bbb84e..614fd48 100644
--- a/system/netdata.service.in
+++ b/system/netdata.service.in
@@ -6,6 +6,7 @@ After=network.target httpd.service squid.service nfs-server.service mysqld.servi
 Type=simple
 User=netdata
 Group=netdata
+Environment=NETDATA_CONFIG_DIR=@configdir_POST@
 ExecStart=@sbindir_POST@/netdata -D
 
 # saving a big db on slow disks may need some time
```

For fping, Ubuntu 16.04 has older version of fping 3.13 (netdata requires 3.15).
Since we have a specific `--prefix` rule by us, we build fping v4.0 and install it by ourselves.

After turning fping's setuid on by `chmod 4755 $INSTALL_PREFIX/sbin/fping` and editing etc/netdata/fping.conf as the below, it works.

```
fping="/opt/scorer/sbin/fping"

hosts="`/sbin/ip route show | awk '
BEGIN           {GW="127.0.0.1"}
$1=="default"   {GW=$3;exit}
END             {print GW}'`"
```

Thank you for providing a help. :-)

**Comment by l2isbad** [comment]
2017-05-01 02:46:32: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-05-01 02:46:32: python.d ERROR: **dns_query_time 'python-dnspython' package is needed to use dns_query_time.chart.py**
2017-05-01 02:46:32: python.d ERROR: dns_query_time check() failed - disabling job
2017-05-01 02:46:32: python.d ERROR: DISABLED: dns_query_time/None

> After exporting NETDATA_CONFIG_DIR, dns_query_time worked for me.

**Comment by h2suzuki** [comment]
Oh, I forgot to mention that I also installed dnspython.  Otherwise, the plugin didn't run.
Either of the following worked on Ubuntu 16.04.

    apt-get install python-dnspython
          or
    pip install dnspython


So the remaining point is only this.  I hoped to give a name like "default_gateway" to the non-fixed IP address to ping.

> Oh, one more query. Is it possible to give a user friendly name to the graph?
> The graph name becomes something like "fping.172_31_0_1_latency" by this method.

**Comment by h2suzuki** [comment]
I have yet another issue by this method.

When NetData is started after boot, the network interface might not get ready yet.
Then, I don't know how to ask fping plugin to auto-detect the new default gateway, after the network is up.

The same is true when the interface is changed from eth0 to wlan0.

Even worse, when the gateway address changed, the old graph fping.172_31_0_1_latency disappears.  Then new graph comes up with the new name like fping.172_32_0_1_latency.
We have many discontinuous graphs, even though we only want to measure the RTT of the default gateway...

Now I suspect that putting a gateway-finding script in fping.conf is a wrong way to go (insane).

I wish to have a virtual target "default gateway" in fping.conf, and fping plugin would follow the default gateway even when it's changing.  What do you think?

**Comment by ktsaou** [comment]
Well... I guess the easiest to do for your case would be to create a simple bash plugin that will do exactly what you need. There are many bash plugins already in netdata (charts.d directory), so pick one and alter it.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.
