### ISSUE TITLE
Issues after new install of netdata

### ISSUE THREAD

**Issue by arjove** [firehol/netdata#2143]
Hello,

I have just installed netdata on 2 systems. Both systems are running centos 7 and are fully uptodate. 
One is a webserver and one is a clean install. 

I cannot acces :19999, it just times out. 

The log files in /var/log/netdata/ do not show anything out of the ordinary, any suggestions as to what check next? 

Kind regards,

**Comment by kmonsoor** [comment]
possibly, your port `19999` is not open to access from public internet.  In that case, Netdata will listen to `19999`, but no external host isn't being able to reach that port.
For example, on an AWS EC2 instances, you have to enable it from the AWS console. 

You can check if Netdata itself serving on the port or not, by trying this command on the SSH-ed console to that machine.
```
$ wget 127.0.0.1:19999
```
If Netdata is working properly, it will download a `index.html` file. If not, something like "connecting ..." will come up until it times out.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this now. If you need help, just post.
