### ISSUE TITLE
Netdata on Synology DSM 6.x (question / innstallation help)

### ISSUE THREAD

**Issue by HactarofDoom** [firehol/netdata#2147]
I ran into an issue with the netdata install on my Synology RS3617xs running DSM 6.1.1-15101

I installed CHROOT (and the required Python), SSH into the Synology as root and run the usual apt-get update/upgrade and set the locales. Installed the packages as mentioned in the wiki, cloned the GIT and run the install script. Now i get the following errors:

`[/root/netdata]# chmod a+rX /usr/share/netdata`
`OK`   

 `--- Install netdata at system init ---`
`I don't know what init file to install on system 'debian-8'. Open a github issue to help us fix it.`
`FAILED  Cannot install netdata init service.` 

`--- Start netdata --- `
`[/root/netdata]# /usr/sbin/service netdata stop`
`netdata: unrecognized service`
`FAILED  ` 

`[/root/netdata]# /usr/sbin/service netdata restart`
`netdata: unrecognized service`
`FAILED` 

`[/root/netdata]# /usr/sbin/service netdata start` 
`netdata: unrecognized service`
`FAILED`   

`[/root/netdata]# stop_all_netdata`
`OK`

`[/root/netdata]# /usr/sbin/netdata` 
`2017-05-02 11:13:11: netdata: ERROR: PROCFILE: Cannot open file '/proc/stat' (errno 2, No such file or directory)`
`2017-05-02 11:13:11: netdata: ERROR: Cannot open file '/proc/stat'. Assuming system has 1 processors.`
`2017-05-02 11:13:11: netdata: ERROR: Cannot open file '/proc/sys/kernel/pid_max'. Assuming system supports 32768 pids. (errno 2, No such file or directory)`
`OK`   

`OK. NetData Started!`

Manually trying to start results in

`root@xxxxxx:~/netdate# /usr/sbin/netdata` 
`2017-05-02 11:15:38: netdata: ERROR: PROCFILE: Cannot open file '/proc/stat' (errno 2, No such file or directory)`
`2017-05-02 11:15:38: netdata: ERROR: Cannot open file '/proc/stat'. Assuming system has 1 processors.`
`2017-05-02 11:15:38: netdata: ERROR: Cannot open file '/proc/sys/kernel/pid_max'. Assuming system supports 32768 pids. (errno 2, No such file or directory)`

So CHROOT on DSM 6.x does not create the needed files in /proc and also has some issue with the system init. So far all search attempts only lead to DSM 5.x Users where it ran soomthly apparently and noone seems to have said issue.

Anyone got a hint for me or has this running on DSM 6.x and can share experience on the matter?

**Comment by ktsaou** [comment]
Hi. I really don't know how to help you. netdata really needs access to `/proc`. Is it possible to run netdata outside the chroot?

**Comment by HactarofDoom** [comment]
Ok, a new day a new outlook on things. After a minor DSM Version update today morning netdata is now up and running (started manualy with /usr/sbin/netdata) however neither  a "killall netdata" is working not was i so far able to register netdata with either systemd or /etc/init.d/

So should anyone run into the same problem update to the latest DSM version or, if none is available, try jet another restart and start the service by hand.

Let's see if i can get it to register the rest of the commands also but since it is now running priorities have shifted to another fire to be extinguished. Will update here if and when i find a way around.

**Comment by ktsaou** [comment]
Did you find a way to work around this?

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by jlgoolsbee** [comment]
I ran into this exact set of problems on a DS212 running DSM 6.1.5-15254, and can confirm that for some reason, /proc inside the chroot environment was empty until I rebooted.
