### ISSUE TITLE
the values from gauges overlap

### ISSUE THREAD

**Issue by colomboipl** [firehol/netdata#215]
Hello there. 
I have running the netdata on a docker container titpetric and after minutes the values inside the gauge overlap. In both situation sequential refresh or best effort.

How do i fix this?

**Comment by ktsaou** [comment]
I don't really get the problem. Is it visual (paste a screenshot) or data related?

**Comment by colomboipl** [comment]
Yes it is. Now i not near the server, but it like 2 values are overlao on the same gauge. To solve i need to refresh the main page.

**Comment by ktsaou** [comment]
ok. Please post a screenshot when you can.

**Comment by colomboipl** [comment]
Hello,
Finally i have some screenshot from this issue.
Best Regards,
Arnaldo Monteiro
![netdata_overlap1](https://cloud.githubusercontent.com/assets/12485946/14568399/390acc6e-0328-11e6-9443-d67efc84dc47.jpg)
![netdata_overlap2](https://cloud.githubusercontent.com/assets/12485946/14568403/3b6abfbe-0328-11e6-895d-fab8b4c2d7f2.jpg)

**Comment by ktsaou** [comment]
Strange.

Which browser and version you use?

Does the same happen on http://netdata.firehol.org ?

**Comment by colomboipl** [comment]
I have a Centos 6.4 server where the netdata is installed and running inside the doker container titpetric/netdata.
The browser I used is firefox 45.0.1 and Chromium 49.0.2623 and have the ubuntu 14-04 distro

**Comment by colomboipl** [comment]
Ohh I don´t no and cannot tested because our machine is not connected to the internet.

**Comment by ktsaou** [comment]
I am not sure I can do something about this.

Could you please press Control-F5 on your browser to clear its cache?
Do you have any extensions installed on your browser? Is it possible to disable them all and refresh the site with Control-F5?

**Comment by colomboipl** [comment]
Hello,

i tried with different machines, diferent browser and the same issue. Maybe the problem is that i´m running the netdata from docker.

Best regards,
Arnaldo Monteiro

**Comment by ktsaou** [comment]
No, where the server is running is irrelevant.

To be sure, try the demo site: http://netdata.firehol.org.
Does it happen there?

**Comment by ktsaou** [comment]
Did you manage to find what is happening?

**Comment by colomboipl** [comment]
Miraculous nevermore appeared.

I dindn´t change the docker version or the docker image.

Can close!
