### ISSUE TITLE
Netdata master with memory mode = map, causing io waits in CPU utilization charts

### ISSUE THREAD

**Issue by gamefundas** [firehol/netdata#2150]
I am noticing 40% CPU(mostly iowaits) swamping the Netdata master server. Currently I have a Netdata master with about 5 slaves pushing metrics in to it. Following are the set of configurations for master and slaves.

The server specs are as follows:
AWS - r4.xlarge with 4 CPU 30 GB Ram, 10 Gigabit Network bandwidth & EBS optimized SSD storage

Netdata master netdata.conf:
```
[global]
        #hostname = NETDATA_HOSTNAME
        history = 86400
        access log = none
        disconnect idle web clients after seconds = 3600
        config directory = /etc/netdata
        cache directory = /var/cache/netdata
        log directory = /var/log/netdata
        memory deduplication (ksm) = yes
        error log = /var/log/netdata/error.log
        update every = 3
        memory mode = map
        web compression level = 1
        enable web responses gzip compression = yes
        multi threaded web server = yes
        delete obsolete charts files = yes
        delete orphan hosts files = yes

[registry]
        enabled = yes
        registry to announce = NETDATA_REGISTRY_URL

[backend]
        enabled = yes
        type = opentsdb
        destination = localhost
        prefix = netdata
```

Netdata master stream.conf:
```
[stream]
        enabled = no

[11111111-2222-3333-4444-555555555555]
    enabled = yes
    default history = 86400
    default memory mode = map
    health enabled by default = auto
	default postpone alarms on connect seconds = 60
```

Netdata slaves - netdata.conf
```
[global]
	#hostname = NETDATA_HOSTNAME
	history = 86400
	access log = none
	disconnect idle web clients after seconds = 3600
	config directory = /etc/netdata
	cache directory = /var/cache/netdata
	log directory = /var/log/netdata
	memory deduplication (ksm) = yes
	error log = /var/log/netdata/error.log
	update every = 3
	memory mode = none
	web compression level = 1
	enable web responses gzip compression = yes
	delete obsolete charts files = yes
	delete orphan hosts files = yes

[health]
    enabled = no
```

Netdata slaves - stream.conf
```
[stream]
    enabled = yes
	destination = tcp:AWS_NETDATA_HOST:80
	api key = 11111111-2222-3333-4444-555555555555
	buffer size bytes = 5048576
	reconnect delay seconds = 5
```

Few charts the explain what I see. Please let me know if you need any other views to nail down this problem.	

These are the registered slave nodes, that are sending data to the netdata master. Just 5 of them to begin with.
![image](https://cloud.githubusercontent.com/assets/5448799/25661987/c5679b7a-2fe0-11e7-88da-426e3f4d2b0e.png)

Approx 40% CPU utilization across. Restarting clears up but soon it gets back to the 40% state.
![image](https://cloud.githubusercontent.com/assets/5448799/25661956/aa69bf38-2fe0-11e7-9fb3-56c3472f89a8.png)

See these alerts come up few different times indicating there was a lot of disk activity
![image](https://cloud.githubusercontent.com/assets/5448799/25661928/8d54d068-2fe0-11e7-98eb-cca8d2f91d4c.png)

For some reason only one of the CPU cores is swamped, close to 95% iowait's
![image](https://cloud.githubusercontent.com/assets/5448799/25662169/7ffe6b6c-2fe1-11e7-89e6-f9ece1758ed0.png)

Please let me know if you need any other data points. Will be happy to share.

**Comment by ktsaou** [comment]
Also, you can check an azure system I have that aggregates 23 netdata servers at http://build.my-netdata.io.

**Comment by gamefundas** [comment]
The problem was with the Nginx process. Bringing it down resolved the iowait. Will figure out to see if Netdata and Nginx had anything to do with this or its an independent issue.

![image](https://cloud.githubusercontent.com/assets/5448799/25706428/6f40950c-30ae-11e7-9b1c-5fad069c9187.png)

Will close this one out after verifying.

**Comment by gamefundas** [comment]
I am rebuilding our entire cluster in the next few days or week. Will get to know more on this. We also originally had Influx running on the same host. Trying to get rid of it so that Netdata is the only process on this machine.

**Comment by ktsaou** [comment]
ok perfect. I am closing this. If you need help, just post.
