### ISSUE TITLE
ERROR 101: Cannot load jQuery: http://my_ip_addr:19999/lib/jQuery-2.2.4.min.js

### ISSUE THREAD

**Issue by captainwong** [firehol/netdata#2155]
My netdata runs on Ubuntu 16.04.2 LTS, I use my colorfy Android Pad visit http://my_ip_addr:19999, it show the error on title. Help?

**Comment by captainwong** [comment]
FYI, I restart netdata by running:
netdata stop
netdata start

and now it works fine......

**Comment by captainwong** [comment]
Should I close this issue? I a newbie here, please let me know what should I do.

**Comment by ktsaou** [comment]
Hi, ok I'll close it.
Keep in mind that for all such errors, the right way to find what is happening is to tail `/var/log/netdata/error.log` and `/var/log/netdata/access.log`.

It should tell you what the error is.

**Comment by captainwong** [comment]
Thank you, next time I find this bug I'll try what you said.
