### ISSUE TITLE
*** SECURITY information for domain.com ***

### ISSUE THREAD

**Issue by qtwrk** [firehol/netdata#2158]
Hi guys 
  This morning I received this email 

> domain.com : May  6 06:00:38 : netdata : user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/bin/smbstatus -P

I am not sure what is it about ?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/2094

You are right @qtwrk we must perform a check (sudo -v) before executing the command

**Comment by l2isbad** [comment]
> we need to opt-in the samba plugin too

what is "opt-in"? :simple_smile:

**Comment by ktsaou** [comment]
disabled by default... no auto-detection.
So, the users will have to edit pythond.conf to enable it.

**Comment by l2isbad** [comment]
It always fails now by default
```bash
[/opt/netdata/var/log/netdata]grep samba error.log
2017-05-06 23:30:39: python.d ERROR: samba Sorry, user netdata may not run sudo on lgz-homepc.
2017-05-06 23:30:39: python.d ERROR: samba check() failed - disabling job
2017-05-06 23:30:39: python.d ERROR: DISABLED: samba/None
```

**Comment by ktsaou** [comment]
I think it is ok to close this now.
@qtwrk if you still have an issue with it, please post.
