### ISSUE TITLE
Invalid API Key GUID.... 

### ISSUE THREAD

**Issue by efaden** [firehol/netdata#2159]
Does anyone have an example configuration with an API key?  I have tried about 100 different ways and on the server side I always get

 GUID 'MyAPIKey' is not a valid GUID.

I added 

[MyAPIKey]
    enabled = yes
    default history = 3600
    default memory mode = save
    health enabled by default = auto

And enabled it on the clients....
   and set api key = MyAPIKey

Any advice?

**Comment by efaden** [comment]
Nevermind.  It wasn't clear that the API KEY also needed to be a GUID

**Comment by ktsaou** [comment]
hm... I see it says how to do it: https://github.com/firehol/netdata/blob/63c96aa96f96f3aea10bdcd2ecd92c889f26b3af/conf.d/stream.conf#L7

Probably you missed that...

**Comment by efaden** [comment]
I didn't catch that part, but it also doesn't really say anywhere that the API key HAS to be a GUID.   Also may make sense to just add a line or two to the WIKI page on it.  Got it to work though.  Works perfectly now.
