### ISSUE TITLE
node.js post initial netdata install ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#216]
I only came across the note about node.js at https://github.com/firehol/netdata/wiki/Installation#nodejs

If I install node.js after the initial netdata install, is there anything I need to do for netdata to detect and use node.js ?

**Comment by ktsaou** [comment]
The best is to install it before.

node.js is currently needed only for `named` (`bind`) and SNMP. If you don't install `named` or you are not going to configure SNMP, you don't need it.

Keep in mind though, I plan to re-write several BASH plugins to node.js.

**Comment by centminmod** [comment]
@ktsaou cheers

programming wise bash I can follow, not much for node.js heh

**Comment by ktsaou** [comment]
cleaning up. I close this one too.
If something remains, please let me know.
