### ISSUE TITLE
Latest commit bind new port on host

### ISSUE THREAD

**Issue by t3chn0m4g3** [firehol/netdata#2166]
First of all, thank you very much for netdata 😃 

The latest commit on `master` seems to introduce new ports `[tcp,udp]/8125` which in my case need to be accessible through iptables rules, without the netdata service is unreachable.
```
tcp        0      0 127.0.0.1:19999         0.0.0.0:*               LISTEN      1584/netdata    
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      1584/netdata    
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           1584/netdata
```
Reverting back to v1.6.0 restores the expected behaviour:
```
tcp        0      0 127.0.0.1:64301         0.0.0.0:*               LISTEN      19483/netdata 
```
I experienced this using a docker container with `net=host` mode enabled and iptables rules not allowing access to [tcp,udp]/8125 - dtag-dev-sec/tpotce#100

Thanks in advance for your insight.

**Comment by ktsaou** [comment]
Hi,

the latest version has an embedded statsd server that listens by default on udp and tcp port 8125. Check this for more information: https://github.com/firehol/netdata/wiki/statsd

As a security measure for installations that get updated, [we bind port 8125 only on localhost](https://github.com/firehol/netdata/blob/855aa2680dd26670af125978179d1d3db9211557/src/statsd.c#L294). This allows statsd to be used from the localhost only, so no firewall rules are needed.

So, you say that due to this netdata failed to start or affected port 19999 in any way?

**Comment by t3chn0m4g3** [comment]
@ktsaou Thanks for you swift response :bowtie: 

Yes, while netdata was starting without any problems I had to unload my iptables NFQUEUE chain for netdata to work again. After adding `[tcp,udp]/8125` to the exclude list and reloading iptables it was working fine again.

From what you are describing I should not have experienced such strange behaviour, do you have any ideas on that?

Thanks again!

**Comment by ktsaou** [comment]
hm... this is really strange. As you can see:

```
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      1584/netdata    
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           1584/netdata
```

Both are binded to 127.0.0.1.
Also, netdata statsd is isolated code (even different threads), so I am not sure this has anything to do with the problem you faced (it shouldn't).

Can you post of describe the firewall rule that was affected by this?

**Comment by t3chn0m4g3** [comment]
This is the one (`tcp/64301`=`tcp/19999`):
```
/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW -m multiport ! --dports 64295,64296,64297,64298,64299,64300,64301 -j NFQUEUE
```

**Comment by ktsaou** [comment]
What is this mapping? (`tcp/64301`=`tcp/19999`)
Is it possible the mapping was influenced with the appearance of a new port?

(excuse my ignorance - I understand this is some kind of a honeypot, but I cannot really tell what can affect it).

**Comment by t3chn0m4g3** [comment]
This was just to indicate, that I am running netdata on `tcp/64301` 😅 
The rule itself sets exclusions which should not be forwarded to the honeypot (honeytrap binds to all open ports unless excluded) which expects its packets on a NFQUEUE chain.
However, as you described, I have no idea why the reachability of `statsd` should influence `netdata` reachability at all.
Hmm 🤔 , unless `netdata` tries to bind permamently to `tcp/8125` since the honeypot will of course answer the request with a bogus reply!?
Is such a situation handled with the new `statsd` feature?

**Comment by ktsaou** [comment]
> This was just to indicate, that I am running netdata on tcp/64301 😅

nice! you got me :)

> bind permamently to tcp/8125

I am not sure I follow. What does "bind **permanently**" mean?

**Comment by t3chn0m4g3** [comment]
😄 

Ok, you got me there 😉 

As you pointed out `statsd` is running on `tcp/8125`. With the iptables chain in place (without the exclusion) `statsd` will not be accessible since `honeytrap` will answer any request to that service with a bogus reply. If for some reason `netdata` itself needs to establish an active connection to `statsd` it would try to connect to `honeytrap` instead of `statsd`.
What happens if `netdata` can not successfully establish a connection to `statsd`? Will it be accessible or does it need a `statsd` connection fully working before handling web-requests?

**Comment by ktsaou** [comment]
netdata does not talk to statsd over the socket. netdata is statsd, so there is no need to talk over a socket.
I am still confused. The web port has no dependency on statsd. Actually netdata API and netdata statsd are totaly independent.

Is it possible to restore your previous config to test it? I think statsd has nothing to do with your problem.

**Comment by t3chn0m4g3** [comment]
When using the latest netdata `master` (without changing anything around the honeypot) netdata is not accessible via web.

When using release `v1.6.0` (also without changing anything around the honeypot) netdata can be accessed without any problems.

I am happy to dig deeper into the strange behaviour. What type of (debug) logs / infos do you need?

**Comment by ktsaou** [comment]
Well, the first thing to verify is if netdata got the request.

You can do this by examining `/var/log/netdata/access.log` and `netstat -nat | grep 19999` (or your netdata port).

So, is the client connected to netdata?

**Comment by t3chn0m4g3** [comment]
Thank you for the suggestion and please excuse my late feedback 😰 

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
NFQUEUE    tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN state NEW multiport dports  !ftp,ssh,telnet,nameserver,69,http,loc-srv,https,microsoft-ds,ms-sql-s,1723,1883,1900 NFQUEUE num 0
NFQUEUE    tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN state NEW multiport dports  !mysql,sip,sip-tls,5601,11211 NFQUEUE num 0
NFQUEUE    tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN state NEW multiport dports  !64295:64303 NFQUEUE num 0
NFQUEUE    tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN state NEW multiport dports  1025,50100,http-alt,tproxy,9200 NFQUEUE num 0
```
What I found out...
- Even the excludes I mentioned earlier did not work, phenomenon persisted after reboot.
- Checked for the requests in `access.log`, `1.6.0` is receiving the requests, `rolling build` is not, unless I flush the INPUT chain with `iptables -F INPUT` (have to flush, deleting rules does not help) which then results in immediate response (docker images and configs are completely identical except for the different `netdata branches`).
- Only when removing `network_mode: "host"` option (and then setting `networks` and `ports` in the `docker-compose.yml`) the client can connect when using the `rolling build`.
```
# Netdata service
  netdata:
    container_name: netdata
    restart: always
#    network_mode: "host"
    networks:
     - netdata_local
    ports:
     - "127.0.0.1:64301:19999"    
    cap_add:
     - SYS_PTRACE
    security_opt:
     - apparmor=unconfined
    image: "dtagdevsec/netdata:1706"
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /var/run/docker.sock:/var/run/docker.sock
``` 
I am not sure if I remember correctly, but if not using `network_mode: "host"` there were some constraints with the network statistics. Is that (fully) solved by mapping `/proc` and `/sys` into the container? If yes I had a solution 😄

**Comment by ktsaou** [comment]
hm... could you please check that disabling statsd server in netdata.conf solves the issue?

This is totally strange... The new port should not influence your setup at all, except if docker somehow refuses to run it for some reason.

@titpetric any ideas? This docker container is going crazy for some reason I can't really understand...

**Comment by t3chn0m4g3** [comment]
Thanks for the swift response!

What is the option to do that? `/etc/netdata/netdata.conf` just tells me it self provides the .conf from 127.0.0.1:19999. Just one line :)

**Comment by ktsaou** [comment]
Using the latest version (with statsd), download netdata.conf with this:

```sh
curl 'http://localhost:19999/netdata.conf' >/tmp/netdata.conf
sudo cp /tmp/netdata.conf /etc/netdata/netdata.conf
```

Then you will have a `[statsd]` section with `enabled = yes`. Uncomment it and set it to `no`.

**Comment by titpetric** [comment]
It seems this would be a specific firewall issue related to this setup. Netdata in host mode may be disrupted by firewall policies and honeypots on the host. What exactly changed between 1.6.0 and master netdata I don't know. There might be some indication in "docker logs [container]" if netdata refuses to bind to some port for some reason. Attaching the container logs might help (use pastebin or https://filedrop.si for example).

@t3chn0m4g3, can you somehow reproduce the issue on a clean machine? Scaleway or Digital ocean let you spin up a machine cheaply, you could use this [referral link for DigitalOcean](https://m.do.co/c/f6a67e30a1f4) so you can get $10 in credits to try to replicate the issue at no cost (but time). If/when you do, keep in mind that you should attach steps to reproduce, so I can try to figure out what is going on in more detail.

In regards to /proc and /net, you could run netdata without `--net=host`, but you wouldn't get all metrics. Currently the only way is faking this filesystem for the container. I explain it in more depth in [Bypassing Docker Network Isolation post on my blog](https://scene-si.org/2016/11/22/bypassing-docker-network-isolation-hack/).

**Comment by t3chn0m4g3** [comment]
@ktsaou I think we can eliminate `statsd`as root cause, disabling does not change the behaviour.  
@titpetric Disabled all honeypots, result is the same. Thank you for the links, will try that out as well.

Also I worked my way back through the commits:
b689036d47ee0004f1ac11e888073d0557e28ca9 is the one introducing the problem
c93f4240e3a65e3f63b3f82ed651e4caae106b9d is the last version that works for me

Hope that helps to identify the problem, thanks for your kind support 😃

**Comment by titpetric** [comment]
Could you paste the log output from both versions into pastebin/somewhere,
please?

To get the log, run something like `docker logs container > works.log` and
`docker logs container > broken.log` after the netdata instance(s) have
started and serve traffic.

Best

**Comment by t3chn0m4g3** [comment]
@titpetric thx and here you go :)
[broken.txt](https://github.com/firehol/netdata/files/1007844/broken.txt)
[works.txt](https://github.com/firehol/netdata/files/1007843/works.txt)

**Comment by t3chn0m4g3** [comment]
Thanks guys, I just solved it. @ktsaou and @titpetric it was an iptables issue which did not handle the NFQ forwarding as expected.

After updating to the following iptables logic everything works again as expected.

```
# Set iptables accept rules to avoid forwarding to honeytrap / NFQUEUE
ExecStartPre=/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW,ESTABLISHED -m multiport --dports 64295:64303,7634 -j ACCEPT
ExecStartPre=/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW,ESTABLISHED -m multiport --dports 21,22,23,42,69,80,135,443,445,1433,1723,1883,1900 -j ACCEPT
ExecStartPre=/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW,ESTABLISHED -m multiport --dports 3306,5060,5061,5601,11211 -j ACCEPT
ExecStartPre=/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW,ESTABLISHED -m multiport --dports 1025,50100,8080,8081,9200 -j ACCEPT

# Forward all other connections to honeytrap / NFQUEUE
ExecStartPre=/sbin/iptables -w -A INPUT -p tcp --syn -m state --state NEW -j NFQUEUE
```

Thanks again for your kind support :bowtie:  the discussion helped me very much to solve it!

**Comment by ktsaou** [comment]
nice you solved it. It was a really strange case...
