### ISSUE TITLE
A question about how the nodejs snmp plugin get the ports metrics

### ISSUE THREAD

**Issue by lfdominguez** [firehol/netdata#2167]
Hello, this is an informative question. I have a router that i want check with netdata and configure the snmp plugin to take the bandwith of the ports of it, all works great, but when i test the results vs another tools i can see a difference of some kbps.
Well, the question is that how you calculate the bandwith of the router using the Octets information from it.
I code a Ruby program to test where i request the information to router and the time that i get is that the router send me and that is same to the zabbix (that are currently used to get the information), but is not the same to netdata nodejs plugin.

This use the ruby-snmp gem

```ruby
require 'snmp'

last_in = 0
last_sec = 0
diff_in = 0
diff_sec = 0

time_OID = SNMP::ObjectId.new('1.3.6.1.2.1.1.3.0');
while true
  SNMP::Manager.open(host: '190.6.71.161') do |manager|
    response = manager.get(['IF-MIB::ifInOctets.1158'])
    response.each_varbind do |vb|
      inValue = vb.value.to_i
      diff_in = inValue - last_in
      last_in = inValue
      # puts "#{vb.name.to_s} #{vb.value} #{vb.value.asn1_type}"
    end

    response = manager.get([time_OID])
    response.each_varbind do |vb|
      secs = vb.value.to_i / 100
      diff_sec = secs - last_sec
      last_sec = secs
      # puts "#{vb.name.to_s} #{vb.value.to_i / 100} #{vb.value.asn1_type}"
    end

    puts "Consumed #{diff_in} in #{diff_sec} for #{diff_in / diff_sec * 8 / 1000} kbps"

    sleep 10
  end
end
```

**Comment by ktsaou** [comment]
Could you please describe the difference you see?

The examples we provide suggest that `kbps = octets * 8 / 1024`. Your example says `kbps = octets * 8 / 1000`. You control this with the `divisor` of the snmp configuration.

Then, netdata interpolates the values at the exact second boundaries. So, a value of 100 bytes collected in 1.2 seconds is:

```
100 * 8 / 1024 / 1.2 = 0.65 kbps
```

(interpolation is more complicated than this, but anyway, you will get the idea)

While yours will show:

```
100 * 8 / 1000 = 0.80 kbps
```

Your code seems to ignore the time the SNMP device needed to answer (my Linksys SRW2024P switch needs 7 seconds!).

**Comment by lfdominguez** [comment]
I don't ignore the device time because i get the time that device send me with

```ruby
time_OID = SNMP::ObjectId.new('1.3.6.1.2.1.1.3.0');
```
to calculate the bandwith i use that time, because in that time the routers take the information, so if the router has a lag of 7 seconds dont care, because i use that information from the router, not from my timer...

**Comment by lfdominguez** [comment]
and searching in google...
```
1 kbps = 1000 bps
```
so that's is one of the main differences..... (https://www.wikiwand.com/es/Kilobit_por_segundo) i known that wikipedia is not a scientific source ;) but in many place i found that:
```
1 Kibit = 1024 bit
```

**Comment by lfdominguez** [comment]
oh sorry for the link to Wikipedia in Spanish (is my main language), this is the English article https://www.wikiwand.com/en/Data_rate_units#/Kilobit_per_second

**Comment by ktsaou** [comment]
ok, so what is the discrepancy you see? Is it justified by the different divisor?

**Comment by lfdominguez** [comment]
maybe, I want to know if when you get the information from the router, the time that you use for the calculation is from the router (timeOID) or the got from the PC. thanks..

**Comment by ktsaou** [comment]
The current implementation of SNMP with node.js, uses relative times with millisecond resolution, taken from the time a successful response from SNMP is received, on the netdata host, not the snmp device.

In general, netdata tries not to "loose" time. There is a beat all netdata programs follow, and the netdata daemon has some logic to prevent its plugins going far behind time, or step into the future. So, no matter what the plugin reports, the netdata server may apply adjustments... If you compile your netdata with flag `-DNETDATA_INTERNAL_CHECKS=1` you will have logs of these adjustments in error.log.

It seems a nice enhancement to use the SNMP time though...

**Comment by lfdominguez** [comment]
i will try create a snmp plugin with ruby that use the snmp device plugin and the use cubic interporlation to get the others values, what do you think about that?

**Comment by ktsaou** [comment]
nice! If you can also support SNMP v3 you will also satisfy #1363 .

Do not bother with interpolation. netdata does that. You only need to provide the right values and the right duration in nanoseconds to netdata (of course if you use timeOID you will have centiseconds, so just multiply them by 10000 and pass them to netdata).

**Comment by lfdominguez** [comment]
ok, I will code wen I have a little time...

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
