### ISSUE TITLE
TCP Current State Monitoring

### ISSUE THREAD

**Issue by polynomial** [firehol/netdata#2169]
* Problem Statement:

 For certain complex distributed systems there exist failure modes which manifest as TCP connections in specific states on the client host(s). An example is the upstream servers behind a proxy experiencing some sort of resource constraints or availability issue. These connections will not be accepted[1] connections and the client host will see these connections in the SYN-SENT[2] state. This can expose configuration issues like the listen[3] backlog[4], number of works, or intermittent network problems like latency or path failures.

* Solution:

 To diagnose, the operations staff can use histograms of TCP connection counts according to the State they are in. Investigating this on the system can be done with the `ss` command:

    $ ss -ant
    State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
    SYN-SENT   0      1      172.27.233.198:46460              10.1.1.1:8080               
    SYN-SENT   0      1      172.27.233.198:46462              10.1.1.1:8080               
    SYN-SENT   0      1      172.27.233.198:46464              10.1.1.1:8080               
    SYN-SENT   0      1      172.27.233.198:46466              10.1.1.1:8080    

This data is provided by the `st` column in `/proc/net/tcp`:

    $ cat /proc/net/tcp
      sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
      16: C6E91BAC:B582 0101010A:1F90 02 00000001:00000000 01:0000028E 00000005  1000        0 784852 2 0000000000000000 3200 0 0 1 5                    
      17: C6E91BAC:B580 0101010A:1F90 02 00000001:00000000 01:0000025B 00000005  1000        0 783290 2 0000000000000000 3200 0 0 1 5                    
      24: C6E91BAC:B586 0101010A:1F90 02 00000001:00000000 01:000002C1 00000005  1000        0 783314 2 0000000000000000 3200 0 0 1 5                    
      26: C6E91BAC:B57E 0101010A:1F90 02 00000001:00000000 01:00000228 00000005  1000        0 790621 2 0000000000000000 3200 0 0 1 5                    
      34: C6E91BAC:B588 0101010A:1F90 02 00000001:00000000 01:000002C1 00000005  1000        0 783327 2 0000000000000000 3200 0 0 1 5                    

It would be awesome to have netdata capture the number of connections in each state[5].

1: https://linux.die.net/man/3/accept
2: https://tools.ietf.org/html/rfc793#section-3.2
3: https://linux.die.net/man/2/listen
4: https://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
5: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/tcp_states.h?id=HEAD#n16

**Comment by ktsaou** [comment]
Hi,
nice request!

Are you sure this information is not already exposed by netdata IPv4/TCP charts?

Background: so far I have avoided parsing all the connections handled by the system. The reason is simple: There are systems that handle dozens of thousands of connections. Parsing all these connections all the time, is a resource intensive operation. Also, in several cases (e.g. conntrack), even the kernel "freezes" while this parsing takes place.

So, I have used the aggregated metrics already exposed by the kernel. For TCP, these are `/proc/net/snmp` and `/proc/net/netstat`.

I see there is also `/proc/net/sockstat` which I have not used.

Especially `/proc/net/netstat` has too much information, from which I used just a small part:

```sh
# cat /proc/net/netstat
TcpExt: SyncookiesSent SyncookiesRecv SyncookiesFailed EmbryonicRsts PruneCalled RcvPruned OfoPruned OutOfWindowIcmps LockDroppedIcmps ArpFilter TW TWRecycled TWKilled PAWSPassive PAWSActive PAWSEstab DelayedACKs DelayedACKLocked DelayedACKLost ListenOverflows ListenDrops TCPPrequeued TCPDirectCopyFromBacklog TCPDirectCopyFromPrequeue TCPPrequeueDropped TCPHPHits TCPHPHitsToUser TCPPureAcks TCPHPAcks TCPRenoRecovery TCPSackRecovery TCPSACKReneging TCPFACKReorder TCPSACKReorder TCPRenoReorder TCPTSReorder TCPFullUndo TCPPartialUndo TCPDSACKUndo TCPLossUndo TCPLostRetransmit TCPRenoFailures TCPSackFailures TCPLossFailures TCPFastRetrans TCPForwardRetrans TCPSlowStartRetrans TCPTimeouts TCPLossProbes TCPLossProbeRecovery TCPRenoRecoveryFail TCPSackRecoveryFail TCPSchedulerFailed TCPRcvCollapsed TCPDSACKOldSent TCPDSACKOfoSent TCPDSACKRecv TCPDSACKOfoRecv TCPAbortOnData TCPAbortOnClose TCPAbortOnMemory TCPAbortOnTimeout TCPAbortOnLinger TCPAbortFailed TCPMemoryPressures TCPSACKDiscard TCPDSACKIgnoredOld TCPDSACKIgnoredNoUndo TCPSpuriousRTOs TCPMD5NotFound TCPMD5Unexpected TCPSackShifted TCPSackMerged TCPSackShiftFallback TCPBacklogDrop TCPMinTTLDrop TCPDeferAcceptDrop IPReversePathFilter TCPTimeWaitOverflow TCPReqQFullDoCookies TCPReqQFullDrop TCPRetransFail TCPRcvCoalesce TCPOFOQueue TCPOFODrop TCPOFOMerge TCPChallengeACK TCPSYNChallenge TCPFastOpenActive TCPFastOpenActiveFail TCPFastOpenPassive TCPFastOpenPassiveFail TCPFastOpenListenOverflow TCPFastOpenCookieReqd TCPSpuriousRtxHostQueues BusyPollRxPackets TCPAutoCorking TCPFromZeroWindowAdv TCPToZeroWindowAdv TCPWantZeroWindowAdv TCPSynRetrans TCPOrigDataSent TCPHystartTrainDetect TCPHystartTrainCwnd TCPHystartDelayDetect TCPHystartDelayCwnd TCPACKSkippedSynRecv TCPACKSkippedPAWS TCPACKSkippedSeq TCPACKSkippedFinWait2 TCPACKSkippedTimeWait TCPACKSkippedChallenge TCPWinProbe TCPKeepAlive TCPMTUPFail TCPMTUPSuccess
TcpExt: 11 5 6 1180 8 0 0 1240 0 0 9605961 6 0 0 0 95783 6262482 58454 795530 0 19 203424956 1027688511 138157480834 0 1155791134 206998190 2762280440 5487445301 356 157379281 0 29 60 3 239 359 223 12606 41674 4675995 55 265430 13026 214419380 468591 198600 211567 1269324 464896 191 155521 0 345 806351 44007 116733 4432 2598161 3530 0 10100 0 0 0 1921 639 38812 10822 0 0 129 726 1781795688 0 0 1479845 62643 0 11 0 860 120802033 48493940 0 40170 1191771 6332 0 0 0 0 0 0 149290 0 225305073 3282 3294 64348 130263 18367484546 0 0 0 0 86 77105 38102 0 130 6 15902 5753393 25 164
IpExt: InNoRoutes InTruncatedPkts InMcastPkts OutMcastPkts InBcastPkts OutBcastPkts InOctets OutOctets InMcastOctets OutMcastOctets InBcastOctets OutBcastOctets InCsumErrors InNoECTPkts InECT1Pkts InECT0Pkts InCEPkts
IpExt: 203 0 5884749 163748 511679 45369 2865344384519 28922933333837 1182462740 26085751 61072054 10779773 0 11977444136 10968 717592 3318782
```

Could you please check if aggregated metrics for what you need are not already exposed as totals by the kernel? If the kernel exposes aggregated metrics for SYN_SENT, of course the optimal would be to use these.

**Comment by polynomial** [comment]
Thanks for the reply. I absolutely agree with the cost/overhead concern. I dug through the files mentioned and came up with some that would be great to capture and provide insight here:
/proc/net/netstat TCPSynRetrans[1]
/proc/net/sockstat  ActiveOpens, AttemptFails, RetransSegs[2]

1: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f19c29e3e391a66a273e9afebaf01917245148cd
2: https://github.com/BrightcoveOS/Diamond/wiki/collectors-TCPCollector

**Comment by ktsaou** [comment]
ok.

ActiveOpens, AttemptFails and RetransSegs are available in `/proc/net/snmp` and netdata already collects them:

![image](https://cloud.githubusercontent.com/assets/2662304/25885852/7c883b0c-3563-11e7-8935-a71742ad1e9f.png)

TCPSynRetrans from `/proc/net/netstat` is missing. Shall I add it to the same chart? I think yes...

**Comment by ktsaou** [comment]
I see `/proc/net/netstat` provides these:

- `TCPSynRetrans`
- `TCPSYNChallenge`
- `TCPACKSkippedSynRecv`
- `TCPChallengeACK`

What do you think? A new chart about TCP SYN, with the above?

netdata parses and groups the following from `/proc/net/netstat`: https://github.com/ktsaou/netdata/blob/e660d3e15b274066157947ab0f4f8f3686dcaecd/src/proc_net_netstat.c#L64-L96

Ideally, we should create charts with some meaning. So, I would like your help to figure out how to create a new chart for monitoring TCP SYN operations.

**Comment by ktsaou** [comment]
Another solution could be to create a chart for TCP retransmits:

```sh
# nstat --zero | grep -i retrans
TcpRetransSegs                  15                 0.0
TcpExtTCPLostRetransmit         0                  0.0
TcpExtTCPFastRetrans            1                  0.0
TcpExtTCPForwardRetrans         0                  0.0
TcpExtTCPSlowStartRetrans       0                  0.0
TcpExtTCPRetransFail            0                  0.0
TcpExtTCPSynRetrans             0                  0.0
```

**Comment by polynomial** [comment]
I love the idea of adding `TCPSynRetrans` to the existing `tcphandshake` graph. For the blurb below perhaps: `TCPSynRetrans shows retries for outbound TCP connections, which can point indicate general connectivity issues or backlog on the remote host, more info can be found: https://tools.ietf.org/html/rfc793#section-3.2 https://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html`.

I will research the other metrics available and open another issue regarding the other metrics here and how it would make sense to present them.

Let me also mention how amazing netdata has been in resolving issues and providing a low cost, minimal configuration, comprehensive, metric collection tool. Thanks!

**Comment by ktsaou** [comment]
ok, I'll try to add it to the same chart (it would be the first metric with this complexity, since this metric will span 2 collectors...).

> Let me also mention how amazing netdata has been in resolving issues and providing a low cost, minimal configuration, comprehensive, metric collection tool. Thanks!

Thanks! Actually your love (stars, comments, installations, shares, blogs, etc) gave me strength to keep extending it!

**Comment by ktsaou** [comment]
and more importantly: you will help significantly if you can map `/proc/net/netstat` metrics to meaningful charts! This mapping is a lot more time consuming compared to the time needed to code data collection for these metrics... and the same is true for most plugins. As @l2isbad (who develops and maintains python plugins) has repeatedly noted, if you know what to collect and how to map it to charts, the code to do it is trivial...

**Comment by ktsaou** [comment]
Added it:

![image](https://cloud.githubusercontent.com/assets/2662304/25919154/7041799e-35d6-11e7-8ae1-fe40732f4e43.png)

Will be merged with #2175

**Comment by ktsaou** [comment]
closed automatically by github. If you have any issue with it, just post.

**Comment by ktsaou** [comment]
I am moving `ActiveOpens` and `PassiveOpens` to a separate chart. On busy servers, these two metrics "hide" the handshake issues (you cannot easily see them - you have to intentionally select the other dimensions to visualize the issue).

So, I am moving these 2 dimensions to a separate chart.

**Comment by ktsaou** [comment]
In PR #3238

**Comment by lucasRolff** [comment]
Sorry to comment on this rather old post, however, I'm currently in the process of moving the last few servers to netdata - on these servers I've been monitoring connection states for years using collectd and shipped them to influxdb to have historical state.

I'm well aware, that netdata wants to avoid doing things that consume too much CPU, however I wonder if it could be implemented anyway as an "opt in" graph, and possible with a default config of only collecting the information every let's say 10 seconds.

During the time with collectd (even on servers with well over 100k connections), I've never had issues with collections of the tcp state from /proc/net/tcp - it does only fetch it on a 10 second interval I believe, and it wouldn't make sense (imo) to pull such data more often than that, because it's already a "summary", so per second stats would just be a waste in that case.
