### ISSUE TITLE
generate snapshot statistics to html file ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#217]
I do a lot of stress load testing of my servers for [comparison benchmarks](http://centminmod.com/benchmarks.html) with different web server configurations i.e. nginx vs apache vs openlitespeed/litespeed vs caddy for http/1.1 and http/2 etc. Part of that process is gathering system level stats for cpu, memory and disk usage etc.

Was wondering if netdata has any planned or existing feature which would allow us to generate a moment in time snapshot of all server statistics and save them to a html file or their own `/snapshot/timestamp/*` directory for viewing or posting along with my benchmark results ?

**Comment by ktsaou** [comment]
ok, we already have this.

You can generate snapshots in JSON, CSV, HTML.
Check the API documentation.

Examples (all these dump the last 600 seconds of data):

JSON
```
http://netdata.firehol.org/api/v1/data?chart=system.cpu&before=0&after=-600&options=seconds
```

CSV
```
http://netdata.firehol.org/api/v1/data?chart=system.cpu&before=0&after=-600&options=seconds&format=csv
```

CSV with TABs
```
http://netdata.firehol.org/api/v1/data?chart=system.cpu&before=0&after=-600&options=seconds&format=tsv
```

HTML
```
http://netdata.firehol.org/api/v1/data?chart=system.cpu&before=0&after=-600&options=seconds&format=html
```

You can also save them in a format that can directly be loaded to google charts.
```
http://netdata.firehol.org/api/v1/data?chart=system.cpu&before=0&after=-600&format=datatable
```

In this case, you can also append `tqx=` with options supported by google charts.
https://developers.google.com/chart/interactive/docs/dev/implementing_data_source#request-format

**Comment by centminmod** [comment]
@ktsaou marvelous indeed just what I need thanks

**Comment by ktsaou** [comment]
> where's the latest API documentation https://github.com/firehol/netdata/wiki/REST-API-v1 ?

Follow the Swagger Editor link. Here: http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/firehol/netdata/master/web/netdata-swagger.yaml

(there was a duplicate key and it was not presented - I fixed it)

**Comment by centminmod** [comment]
ah i see the correct API info now.. thanks @ktsaou

**Comment by ktsaou** [comment]
Can we close this?

**Comment by ktsaou** [comment]
ok. I close it.
Open it again if something is missing.
