### ISSUE TITLE
Install problem Raspberry Pi3

### ISSUE THREAD

**Issue by Jacopx** [firehol/netdata#2170]
I have already install NetData in my FreeBSD server or in my macOS. If I'm trying to install it in my Raspberry Pi3 it show me these:

`
Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues`

Of course everything that it say that is miss is installed. I have already run update and upgrade...

**Comment by ktsaou** [comment]
Hi, before that message block, there was an error shown. Could you please post 20 lines above this message?

**Comment by rmarchant** [comment]
Hi - I had the same problem. Here is the actual error message.

`configure: error: libuuid required but not found. Try installing 'uuid-dev' or 'libuuid-devel'. FAILED `

The uuid-dev package isn't in the default raspbian repository, so I manually downloaded the armhf package :

https://packages.debian.org/jessie/armhf/uuid-dev/download

Installed with dpkg, then re-ran the netdata installer.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. If you believe there is something we can do, just post.
