### ISSUE TITLE
Disabling a Python Module?

### ISSUE THREAD

**Issue by dugajean** [firehol/netdata#2171]
I want to prevent netdata from trying to fetch data from Postfix. I want ahead and renamed the module file in the `python.d` folder, but I'm not sure if that fixes it.

I'd greatly appreciate your help on this and maybe it'd be good to add this piece of info somewhere in your wiki - I couldn't find it there.

**Comment by ktsaou** [comment]
Hi, edit `/etc/netdata/python.d.conf` and set `postfix` to `no`.

**Comment by ktsaou** [comment]
If you renamed it, you have to use the new name. Or rename it back to what it was.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
