### ISSUE TITLE
Set algorithm in configuration chart for statsd metrics

### ISSUE THREAD

**Issue by VDigitall** [firehol/netdata#2172]
Hi, statsd implementation in netdata is cool solution. I can't configure algorithm in synthetic statsd charts, because dimension take only 4 params, how can I set algorithm?

**Comment by ktsaou** [comment]
Hi, yes it is cool!

The algorithm is determined by the type of metric. So, `counter` and `meter` are always `incremental` and all others are `absolute`.

Now, that I think of it, we should probably allow this to be overwritten, to allow settings the other types netdata supports...

**Comment by VDigitall** [comment]
How about extended counters, when I used statsite I can get for my counter max, min, avg and other values via *my_counter.lower*, *my_counter.upper* etc. Can I there use it?

**Comment by ktsaou** [comment]
hm... I need your help to understand. A counter for statsd is a values that always gets incremented. So, it counts something. What is `lower` and `upper`? This functionality exists for histograms, not counters.

Am I missing something?

**Comment by VDigitall** [comment]
https://github.com/statsite/statsite

> extended_counters : If enabled, the counter output is extended to include all the computed summary values. Otherwise, the counter is emitted as just the sum value. Summary values include count, mean, stdev, sum, sum_sq, lower, upper, and rate. Defaults to false.

**Comment by ktsaou** [comment]
hm... How this should be calculated?

I quickly walked through statsite code. If I understand it correctly, when you say you want extended counters, it actually turns the counters to histograms, so that they are not incremental values any more.

Then the question rises: what is a histogram for statsite? It turns out it is an alias for a timer.

hm... @VDigitall could you please give me an example of 5 samples you will send to statsd within the same flush period, and the values you expect to get back?

(ps: it seems that all statsd servers have abused the etsy/statsd protocol - all servers I have seen so far have little unique differences here and there...)

**Comment by VDigitall** [comment]
Yes. 
I send:
```
echo "upload_size:1024|c" | nc -u -w 1 127.0.0.1 8125
echo "upload_size:124|c" | nc -u -w 1 127.0.0.1 8125
echo "upload_size:10|c" | nc -u -w 1 127.0.0.1 8125
echo "upload_size:54|c" | nc -u -w 1 127.0.0.1 8125
echo "upload_size:984|c" | nc -u -w 1 127.0.0.1 8125
```
After flushing I recieve in stdin:
```
\ncounts.upload_size.count 5 1355563265\n
\ncounts.upload_size.lower 10 1355563265\n
\ncounts.upload_size.upper 1024 1355563265\n
\ncounts.upload_size.sum  2196 1355563265\n
...
```

**Comment by ktsaou** [comment]
yes, this this what I thought. This is a histogram.
You can change `|c` to `|h` to get the same with netdata.
Only `sum` is missing, I am adding it now...

PS: I think what statsite did with extended counters is totally wrong. It completely messed the protocol. A counter is about counting the number of events of something (i.e. number of uploads in your case). To measure the average upload size, the right way to do it is a histogram.

Also, counters are integers while histograms and gauges are floating point.

Additionaly, for your use case, the right way to do it is:

```sh
printf "app_name.uploads:1|c\napp_name.upload_size:XXX|h\n" | nc -u -w 1 127.0.0.1 8125
```

So, 2 metrics: one counts the number of uploads, the second provides the upload size histogram.

**Comment by ktsaou** [comment]
closed automatically by github. If you have any issue with it, just post.

**Comment by VDigitall** [comment]
Hi, how can I get access to min, max, avg etc. values of histogram in synthetic statsd chart. I create statsd.d directory and put myapp.conf file with entry:
```
[app]
        name = my_apps
        metrics = my_apps.*
        private charts = yes
        gaps when not collected = no
        memory mode = ram
        history = 60000

[upload_size]
        name = Upload size
        title = Upload size
        family = Upload_size
        context = my_app.upload_size
        units = MB
        type = line
        dimension = my_app.upload_size.min
        dimension = my_app.upload_size
```
when I create chart only with first dimension chart don't appear, with second i recieve wrong value like some sum
