### ISSUE TITLE
netdata prevents autofs automatic unmounts

### ISSUE THREAD

**Issue by dmongan1** [firehol/netdata#2173]
Configured autofs to unmount after 1 minute of inactivity on a Red Hat 7.3 system.  It only works when I stop the netdata process.   I have tried disabling anything in the netdata.conf file that pertains to nfs and the /home directory where the mount takes place.  Any idea what is accessing /home that prevents autofs from unmounting after a user has logged off?

**Comment by ktsaou** [comment]
Hi.

interesting! netdata does at `statvfs()` call for all mount points it collects space metrics for. It seems that this call prevents auto-unmounting.

You can disable disk space metrics for this path, with this (in netdata.conf):

```
[plugin:proc:diskspace]
    exclude space metrics on paths = !/path/to/exclude ... whatever else already exists...
```

So, prefix that setting with a ` ! ` + the path to exclude  + a space + all the other values already present in this setting.

You can verify you did this right, if after it is mounted, you hit F5 on your browser. Disk space metrics for this mount point should not exist.

**Comment by ktsaou** [comment]
Also, if the path is dynamic, you can use `*` as a pattern, e.g.: ` !/path/to/exclude/* `

**Comment by ktsaou** [comment]
I updated my comments. The `!` character is not needed. Whatever this pattern matches is excluded, so no need for negative match.
Please read the correct values on github...

(sorry)

**Comment by dmongan1** [comment]
Thank you....   It works!
________________________________

**Comment by ktsaou** [comment]
nice!
