### ISSUE TITLE
python.d/redis.chart.py - bug when redis restarts

### ISSUE THREAD

**Issue by eLPy17** [firehol/netdata#2177]
python.d/redis.chart.py stops to collect data when redis-server.service is restarted.

I'm sure there is more elegant solution, but this one works for me)
I commented one line in the code bellow and added **self.request = "INFO\r\n"** to fix this bug

```
if self.passwd:
	info_request = self.request
	self.request = "AUTH " + self.passwd + "\r\n"
	raw = self._get_raw_data().strip()

	if raw != "+OK":
		return None
	#self.request = info_request
	self.request = "INFO\r\n"

response = self._get_raw_data()
```

**Comment by l2isbad** [comment]
>  commented one line in the code bellow and added self.request = "INFO\r\n" to fix this bug

This is enough elegant for current redis plugin implementation. I suggest to make a PR @eLPy17

**Comment by l2isbad** [comment]
fixed in https://github.com/firehol/netdata/pull/2182
