### ISSUE TITLE
error message " nginx: [emerg] unknown "ndpath" variable"

### ISSUE THREAD

**Issue by Homer-Sim** [firehol/netdata#2178]
Hello 
my netdata container running behin nginx reverse proxy with your settings for a subfolder

nginx: [emerg] unknown "ndpath" variable
this is the error message displayed all the time and blocking other apps.
do you have an idea how to fix it, without the ndpath entries it is not working.

Thanks

**Comment by ktsaou** [comment]
Hi,

this line defines `nfpath`:

```
location ~ /netdata/(?<ndpath>.*) {
```

and this line uses it:

```
proxy_pass http://netdata/$ndpath$is_args$args;
```

You need to define it before use it.

**Comment by Homer-Sim** [comment]
I did. I copied the lines in the tutorial but the error message stays alive

nginx part:
    location ^~ /netdata/(?<ndpath>.*) {

        auth_basic "dashboard restricted"; # Ausgabe-Meldung bei Zugriff
        auth_basic_user_file /config/nginx/.htpasswd; # Pfad zur .htpasswd-Datei
        proxy_pass http://192.168.100.10:19999/$ndpath$is_args$args;
        gzip on;
        gzip_proxied any;
        gzip_types *;
        include /config/nginx/proxy.conf;
    }

**Comment by ktsaou** [comment]
Well... I am not that strong in nginx configuration.
If anyone can help, please do so...

**Comment by Homer-Sim** [comment]
I found the mistake 

wrong: location ^~ /netdata/(?.*) {
working: location ~ /netdata/(?.*) {

**Comment by ktsaou** [comment]
perfect!
