### ISSUE TITLE
Only run upgrade script if version is newer

### ISSUE THREAD

**Issue by metasikander** [firehol/netdata#2179]
Would it be possible to set up the script to only run if there actually is new software to be built?

I have set up saltstack to run the script as one of its states, but that means that every time i run the state the script is run in it's entirety. That is a bit too resource hungry for my liking, so it would be great if the script could check the version of the installed software before it builds it again.

**Comment by ktsaou** [comment]
hm... `netdata-updater.sh` does exactly that. Have you tried it?

**Comment by metasikander** [comment]
hmm. i see. i havent actually tried that. it would make my setup much more complicated though.
would it be possible to combine them? like run a test at the beginning to se if it's already installed, and do an upgrade or a install depending on the result?
if not i will have to install it manually the first time, and then run the update script through saltstack, in stead of doing everything in saltstack (which is what i prefer)

**Comment by ktsaou** [comment]
I think this will do the job:

```sh
#!/bin/bash
set -e
cd /usr/src/netdata.git
if [ -x netdata-updater.sh ]
then
    ./netdata-updater.sh
else
    ./netdata-installer.sh
fi
```

The above will run the updater if it exists (it is created by the installer), or run the installer if it is the first time it is installed on this machine.

**Comment by metasikander** [comment]
Wow. Thank you so much for your help. That really means a lot!
