### ISSUE TITLE
Is there any way to aggregate data of many servers in a dashboard?

### ISSUE THREAD

**Issue by wanghm** [firehol/netdata#218]
Very great tool!
Is there any way to aggregate data of many servers in one dashboard?

**Comment by Steto82** [comment]
Hi,

just take a look in the Wiki. Our company have already 7 different Servers in one 1 dashboard compared.

https://github.com/firehol/netdata/wiki/Custom-Dashboards

**Comment by ktsaou** [comment]
Did you find it? Do you need help?
If not, please close this.

**Comment by myroslav** [comment]
@ktsaou How one can aggregate dataseries from several servers on single graph? I.e. stack CPU usage of servers that cluster consist of. Or some Nginx request stats across cluster.

I do understand that I can display multiple graphs from different servers side by side, but sometimes this can be quite complex task (for instance displaying 10 servers). Stacking / Overlaying data in single graph is the only option.

What are the options in the cases described above?

**Comment by ktsaou** [comment]
Unfortunately I don't have this ready.

It can be done by querying all the servers and merging their responses, in javascript. It is not very hard, but it is not too easy either.

If you don't want to write this js code, you could use sparklines. If you render (using the existing dashboard) a sparkline for each server, one below the other, you will get almost the same stacked result you seek. It is very easy to build such custom dashboards. You can build a very complex dashboard with just basic HTML knowledge, horizontal or vertical or even with tabs and modals to provide different views for whatever you need. No javascript is required from you for this. Only basic HTML.

**Comment by wanghm** [comment]
thanks a lot

**Comment by rockatos** [comment]
Hello,
I am a beginner and I am a little be lost. @ktsaou you said above "It can be done by querying all the servers and merging their responses, in javascript.", could you please tell me in which files or file there are the queries for the data?
Thank you very much in advance!

**Comment by ktsaou** [comment]
Check the API: https://github.com/firehol/netdata/wiki/REST-API-v1

Extending the netdata dashboard would be much more complicated. If you want to do it though, it is here: https://github.com/firehol/netdata/blob/cb326dff0245688d19a07999d318067bace47ef8/web/dashboard.js#L3617

**Comment by rockatos** [comment]
Thank you very much for your guidance!
