### ISSUE TITLE
Can't create synthetic statsd chart with some params of histogram

### ISSUE THREAD

**Issue by VDigitall** [firehol/netdata#2181]
Hi, how can I get access to min, max, avg etc. values of histogram in synthetic statsd chart. I create statsd.d directory and put myapp.conf file with entry:
```
[app]
        name = my_apps
        metrics = my_apps.*
        private charts = yes
        gaps when not collected = no
        memory mode = ram
        history = 60000

[upload_size]
        name = Upload size
        title = Upload size
        family = Upload_size
        context = my_app.upload_size
        units = MB
        type = line
        dimension = my_app.upload_size.min
        dimension = my_app.upload_size min 1 1000
```
I send to statsd
```
echo "my_app.upload_size:3|h" | nc -u -w 1 127.0.0.1 8125
echo "my_app.upload_size:8|h" | nc -u -w 1 127.0.0.1 8125
echo "my_app.upload_size:19|h" | nc -u -w 1 127.0.0.1 8125

```
when I create chart only with first dimension chart don't appear, with second i recieve min value but when I try use min and max in the same chart appear only latest dimension like tihis:
```
        dimension = my_app.upload_size min 1 1000
        dimension = my_app.upload_size max 1 1000
```
On chart appear only max, but on private chart per metrics I see all params (max, min, average etc.)
#2172

**Comment by ktsaou** [comment]
ok, this is missing. I am adding it now.

**Comment by ktsaou** [comment]
It is in #2183

I changed the `dimension` specs a bit:

```
dimension = METRIC NAME TYPE MULTIPLE DIVIDER
```

`TYPE` can be:

- `events` to get the number of events received by statsd
- `last` to get the last value, as calculated at the flush interval of the metric (the default)

Then for histograms and timers you can use:

- `min`
- `max`
- `sum`
- `average` (same as `last`)
- `percentile`
- `median`
- `stddev`

So, you can now select the calculation you need.

Keep in mind the first value that is sent to netdata creates the chart, but does not show any points. netdata does interpolation at second boundaries, and this interpolation needs 2 values in 2 different seconds to show the first point on the chart.

**Comment by ktsaou** [comment]
Testing it. Will merge it in a while...

**Comment by ktsaou** [comment]
tested and merged!
If you have any issue with it, please post.
