### ISSUE TITLE
Where do I need to install netdata?

### ISSUE THREAD

**Issue by mims92** [firehol/netdata#2188]
Hello,

Let me explain myself:

I installed netdata on my laptop to test. It looks very great, user-friendly, displays a lot of stats.
Now what I want to do is to install it on a linux server to monitor it (PHP, etc).

Do I need to install netdata directly on the server or it can be somewhere else? Because I don't want users to have access to it of course. Maybe with IP restriction, VPS...

I'm a newbie in server monitoring tool.

Thank you for your understanding.

**Comment by ktsaou** [comment]
Hi,

install netdata on all your systems.

Once netdata is installed everywhere, you have more options regarding the location of its database and its dashboards. But that is a bit advanced.

So, for the most basic setup, just install it on all your systems.

**Comment by mims92** [comment]
Thank you :)

So here I have installed netdata on a server but it is accessible for everybody on port 19999.
I've setup apache on port 80 but it doesn't work. The server is still accessible on port 19999 but not on 80.

I'm a bit lost here.

What I want to acheive is to use netdata from the server as part of a node with a central monitoring web UI.

**Comment by l2isbad** [comment]
> still accessible on port 19999

```bash
[/opt/netdata/etc/netdata]grep -E "global|bind" netdata.conf
# global netdata configuration
[global]
        # bind to = *
        bind to = 127.0.0.1
```

> setup apache on port 80

https://github.com/firehol/netdata/wiki/Running-behind-nginx           (<-- prefered option)
https://github.com/firehol/netdata/wiki/Running-behind-apache

**Comment by mims92** [comment]
Hi @l2isbad ,

Thank you.

With Apache it blows up (error: client denied by server configuration: /var/www/html/)
```
<VirtualHost *:80>
	RewriteEngine On
	ProxyRequests Off
	<Proxy *>
		Order deny,allow
		Allow from all
	</Proxy>

	# Local 127.0.0.1:19999 netdata server accessed with '/netdata'
	ProxyPass "/netdata" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30
	ProxyPassReverse "/netdata" "http://127.0.0.1:19999/"
	RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]

	<Location /netdata>
		AuthType Basic
		AuthName "Protected site"
		AuthUserFile /etc/apache2/.htpasswd
		Require valid-user
		Order deny,allow
		Allow from all
	</Location>

	ErrorLog ${APACHE_LOG_DIR}/netdata-error.log
	CustomLog ${APACHE_LOG_DIR}/netdata-access.log combined

</VirtualHost>
```

The `netdata.conf` file was empty so I used the default one and added `bind to` .
I stopped Apache and netdata is no more available at IP:19999

**Comment by l2isbad** [comment]
To be honest I do not really understand what the problem is based on the information provided. 
And i am not an apache user.

I did some test and this works for me:

1. `apt-get install libapache2-mod-proxy-html`
2. `a2enmod proxy`
    `a2enmod proxy_http`
3. create `netdata.conf` in `/etc/apache2/sites-available/`

```bash
<VirtualHost IP.ADDRESS.TO.LISTEN.ON:PORT>
# change servername to whatever you want to
ServerName  netdata.lan
ProxyRequests Off
ProxyPass "/" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=3                                        
ProxyPassReverse "/" "http://127.0.0.1:19999/"
</VirtualHost>
```

4. `a2ensite netdata.conf`
5. `systemctl restart apache.service`
6. Go to `netdata.lan`. Profit!

**Comment by mims92** [comment]
Thank you very much for your time!

I installed NGINX in the end. It's working out of the box ;)

Can be closed.
