### ISSUE TITLE
HAProxy plugin improvement - idle time

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#2189]
It would be useful to add another graph to the haproxy plugin to monitor the idle time of the haproxy process to see which is the internal state of the haproxy process itself.

The description is:

https://www.haproxy.org/download/1.7/doc/management.txt

```
Since HAProxy runs around an event loop, it waits for new events using poll()
(or any alternative) and processes all these events as fast as possible before
going back to poll() waiting for new events. It measures the time spent waiting
in poll() compared to the time spent doing processing events. The ratio of
polling time vs total time is called the "idle" time, it's the amount of time
spent waiting for something to happen. This ratio is reported in the stats page
on the "idle" line, or "Idle_pct" on the CLI. When it's close to 100%, it means
the load is extremely low. When it's close to 0%, it means that there is
constantly some activity. While it cannot be very accurate on an overloaded
system due to other processes possibly preempting the CPU from the haproxy
process, it still provides a good estimate about how HAProxy considers it is
working : if the load is low and the idle ratio is low as well, it may indicate
that HAProxy has a lot of work to do, possibly due to very expensive rules that
have to be processed. Conversely, if HAProxy indicates the idle is close to
100% while things are slow, it means that it cannot do anything to speed things
up because it is already waiting for incoming data to process. In the example
below, haproxy is completely idle :

  $ echo "show info" | socat - /var/run/haproxy.sock | grep ^Idle
  Idle_pct: 100
```
Is possible to get this value either through the socket or the url.

**Comment by l2isbad** [comment]
> possible to get this value either through the socket or the url

I don't see any "Idle_pct" in the output from `http://ip.address:port/haproxy_stats;csv` (the one that plugin uses) request

**Comment by dseira** [comment]
You're right. I throught that through url (csv) could be possible; but it's not possible.

Thanks!

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by ashish1099** [comment]
@ktsaou I think this is an issue

when setting up the haproxy config to use `via_url`, it tries to hit the haproxy twice.

1. stats
2. info

but in case of info there is no info in the haproxy stats page, not sure why we are doing this.
it's resulting in 503 all the time.

```
2020-12-03T03:18:02+01:00 localhost haproxy[19080]: 127.0.0.1:28490 [03/Dec/2020:03:18:02.642] netdata-monitoring netdata-monitoring/<NOSRV> 0/-1/-1/-1/0 503 237 - - SC-- 182/1/0/0/0 0/0 "GET /haproxy HTTP/1.1"
2020-12-03T03:18:12+01:00 localhost haproxy[19080]: 127.0.0.1:28824 [03/Dec/2020:03:18:12.631] netdata-monitoring netdata-monitoring/<STATS> 0/0/0/0/1 200 21725 - - LR-- 180/1/0/0/0 0/0 "GET /haproxy?stats;csv;norefresh HTTP/1.1"
```

I think we should even try to hit the haproxy for info when its based on `via_url`, let me know if you are, I can raise a PR for it

**Comment by OdysLam** [comment]
Hey @ashish1099,

This is an extremely old issue! @ilyam8 is the appropriate person to respond and guide you for a PR (or not). Welcome to our community and thank you for wanting to contribute. It means a lot to us.

cheers 🙇‍♂️
