### ISSUE TITLE
Nginx weblog

### ISSUE THREAD

**Issue by vincus** [firehol/netdata#2192]
**Hello,**

  I am trying to filter for specific vhost in nginx (used as a reverse proxy) using weblog. This is needed for distinguish confirmed faulty requests and real faulty.
--------
This is our logformat:
```
    log_format myformat '$remote_addr -> $host -> $upstream_addr (auth: $remote_user) [$time_local] '
    '[micro: $msec] "$request" $status out: $body_bytes_sent '
    '"$http_referer" "$http_user_agent" '
    'in: $request_length t: $request_time r: $upstream_response_time "$http_soapaction" ssl: "$ssl_cipher" "$ssl_protocol" gzip: "$gzip_ratio"';
```
---------
This is our netdata weblog config:

`nginx_log:`
`  name: 'darlinghost_nginx_log'`
`  path: '/path/log_nginx/access_v2.log'`
`  update_every: 5`
`  custom_log_format:`
`    pattern: '(?P<address>[\da-f.:]+) -.*?"(?P<method>[A-Z]+) (?P<url>.*?)" (?P<code>[1-9]\d{2}) out: (?P<bytes_sent>\d+).* in: (?P<resp_length>\d+) t: (?P<resp_time>\d\.\d+)'`

This one works fine
----------
This is the intention:

`nginx_log:`
`  name: 'darlinghost2_nginx_log'`
`  path: '/path/log_nginx/access_v2.log'`
`  update_every: 5`
`  custom_log_format:`
`    pattern: '(?P<address>[\da-f.:]+) -.*myfavouriteclient.*?"(?P<method>[A-Z]+) (?P<url>.*?)" (?P<code>[1-9]\d{2}) out: (?P<bytes_sent>\d+).* in: (?P<resp_length>\d+) t: (?P<resp_time>\d\.\d+)'
`
The problem is when I am trying to use the filter, as not all rows contain the "favouriteclient" string, netdata will not match when starting, so it disables the plugin.

The category is not good for this, as it does not do a status code breakdown.
Any ideas how to achieve this ?

Thank you

**Comment by l2isbad** [comment]
> netdata will not match when starting, so it disables the plugin
Yep. That's how current version works.

> to filter for specific vhost in nginx
You can redirect logs for specific host to another file.

**Comment by l2isbad** [comment]
@vincus 
https://github.com/firehol/netdata/pull/2279

**Comment by vincus** [comment]
@l2isbad time for a donation :) Thank you

**Comment by ktsaou** [comment]
merged it.
