### ISSUE TITLE
mdstat missing a array

### ISSUE THREAD

**Issue by 0x3333** [firehol/netdata#2193]
I have a RAID 1+0 in mdstat, using nested RAIDs, here is my /proc/mdstat

```
Personalities : [raid1] [raid0] [linear] [multipath] [raid6] [raid5] [raid4] [raid10]
md2 : active raid0 md0[0] md1[1]
      3906502656 blocks super 1.2 512k chunks

md0 : active raid1 sda1[0] sdb1[1]
      1953382400 blocks super 1.2 [2/2] [UU]
      bitmap: 1/15 pages [4KB], 65536KB chunk

md1 : active raid1 sdd1[1] sdc1[0]
      1953382400 blocks super 1.2 [2/2] [UU]
      bitmap: 0/15 pages [0KB], 65536KB chunk

unused devices: <none>
```

In my netdata I can only see `md1` and `md2`, which is odd, as my RAID 1 is `md0` and `md1`.

![screen shot 2017-05-16 at 11 23 45](https://cloud.githubusercontent.com/assets/289289/26110967/34001dd4-3a2a-11e7-93c8-4c54a3f3f27a.png)

Is there anything I need to configure?

**Comment by l2isbad** [comment]
Well, it's a bug (wrong regex). Actually md2 is md0 😄
