### ISSUE TITLE
nginx web_log separate subdomains

### ISSUE THREAD

**Issue by Avamander** [firehol/netdata#2196]
Is there a way to make netdata display requests per subdomain in one graph and connections per subdomain in another graph? So that one could see how many connections (or requests) are being made to specific subdomain instead of one blue (or green) graph that shows all connections (or requests) to all (sub)domains.

**Comment by l2isbad** [comment]
Hi @Avamander 
Sorry if i don't understand you correctly.
1. You can redirect logs for different vhosts to different files
2. You can use 
https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L66-L69
to match specific domain
https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file#url-patterns

**Comment by Avamander** [comment]
What exactly would I need to do to use option 1?

**Comment by l2isbad** [comment]
Separate access_log directive for vhost you are interested in (access_log context: http, server, location, if in location, limit_except).
And another job in the web_log module configuration file ofc.

**Comment by Avamander** [comment]
Okay. For option two I just have to log $host somewhere and the pattern will be matched?

**Comment by l2isbad** [comment]
No, i was wrong. "Category"  is only for matches in $request.

> log $host somewhere and matches will be looked for trough the entire log

I think i can add such feature. @ktsaou what do you think? Is this a good idea? Or should this be implemented in another way?

**Comment by Avamander** [comment]
Okay, so option one is the only choice. When specifying two jobs in the web_log module conf, I'll get twice the amount of graphs I had before? What about a summary?

**Comment by l2isbad** [comment]
>  I'll get twice the amount of graphs

Yes. It's two different jobs. No summary (summary is N vhosts logs to 1 file).

> Okay, so option one is the only choice. 

Well, no. You can replace `$request` with `$host `in the `nginx log_format `. Then "category" should work.

**Comment by l2isbad** [comment]
@ktsaou I think we need to add "category" feature for user defined field.
something like
```yaml
user_defined:
    dim_name1: 'regex1'
    dim_name1: 'regex2'
    dim_name1: 'regex3'

custom_log_format:
    pattern: '"(?P<user_defined>[^"])" (?P<address>[\da-f.:]+) -.*?"(?P<method>[A-Z]+) (?P<url>.*?)" (?P<code>[1-9]\d{2}) (?P<bytes_sent>\d+) (?P<resp_length>\d+) (?P<resp_time>\d\.\d+) '

**Comment by ktsaou** [comment]
hm... this seems nice, but how would it affect the charts?

**Comment by l2isbad** [comment]
The chart will appear only if "user_defined" is in job configuration and "user_defined" field in the custom_log_format.

**Comment by ktsaou** [comment]
so just one additional chart will be created, with the count of all requests matching each dimension?

**Comment by l2isbad** [comment]
Yes, same chart as for url patterns but it will be matches not in $request but in any user defined field

**Comment by l2isbad** [comment]
@Avamander 
https://github.com/firehol/netdata/pull/2200

**Comment by Avamander** [comment]
I guess I'll just update it then.
