### ISSUE TITLE
 I can't install the last netdata on SuSe 11

### ISSUE THREAD

**Issue by amvilardo** [firehol/netdata#220]
Running ./autogen.sh ...
:-----------------------------------------------------------------------------
Running command:

./autogen.sh 

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
Makefile.am:4: option`dist-xz' not recognized
autoreconf: automake failed with exit status: 1

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:
1. The package zlib1g-dev has to be installed.
2. You need basic build tools installed, like:
   
   gcc make autoconf automake pkg-config
   
   Autoconf version 2.60 or higher is required
3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

**Comment by philwhineray** [comment]
See #67 and #105 

Basically, you need a more recent automake or to remove the dist-xz from the top of `Makefile.am`.

@ktsaou we should probably update the `Makefile.am` to specify 1.11, which was when dist-xz support was added. 

Or, as suggested elsewhere we drop dist-xz support from the Makefile.am and not produce such a package. But 1.11 was pre January 2012 so support should be pretty widespread.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
