### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by ale-rinaldi** [firehol/netdata#2201]
web_log plugin reports unmatched lines.

This is my log:

```txt

37.159.226.69 - - [18/May/2017:12:52:15 +0200] "-" 408 0 "-" "-"

```

**Comment by ktsaou** [comment]
hm... this is line is missing information...
Could you please post another line that is matched?

**Comment by ktsaou** [comment]
This is duplicate of #2675 (or the other way around).
Anyway, there is PR #2693 that attempts to fix this. So, if you can test it, please do so and comment on #2693
