### ISSUE TITLE
Email notifications are not received

### ISSUE THREAD

**Issue by mvandeplassche** [firehol/netdata#2203]
Hi, 

First netdata install on a Debian 8 VPS. Trying to configure email notifications. 

I can send emails as **netdata** using _sendmail_ or _mail_ commands and I receive them. With _sendmail_ I have to specify the full path otherwise I get a "bash: sendmail: command not found" message. So, from the command line mail is working as **netdata**. 

Commands used as **netdata** : 
`echo test | mail -s "subject" email@email.com`
`echo "test" | /usr/sbin/sendmail -v email@email.com`

Now when using the test command : 
`/usr/libexec/netdata/plugins.d/alarm-notify.sh test`
I get 3 "OK" messages (see this [pastebin](https://pastebin.com/raw/jsquzM5p) for the full output) BUT I don't receive the emails. The output in /var/log/mail.log is OK : see this [pastebin](https://pastebin.com/raw/juT30YHz).

In /etc/netdata/health_alarm_notify.conf : 
```
sendmail="/usr/sbin/sendmail"
SEND_EMAIL="YES"
DEFAULT_RECIPIENT_EMAIL="email@email.com"
```

I don't know what else I can do since it works from the command line... been scratching my head with this for a few hours. Please, help me :)

Hope there is enough details. 

EDIT : formatting and details

**Comment by ktsaou** [comment]
Hi, netdata does this:

```sh
# become user netdata
su -s /bin/bash netdata

# send an email
/usr/sbin/sendmai -t <<EOF
To: email@email.com
Subject: my subject
Content-Type: text/html

hello world
EOF
```

Does this work?

**Comment by mvandeplassche** [comment]
Hi, 

It worked ! I received the email.

What am I doing wrong ?

**Comment by ktsaou** [comment]
ok, then do this:

```sh
# become user netdata
su -s /bin/bash netdata

# send a few test alarms
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```

**Comment by mvandeplassche** [comment]
Unfortunately this is the command that led to the ouput in the pastebins in my first message. The output is positive, yet I receive no mail.

**Comment by ktsaou** [comment]
hm... I don't know how to help you. Based on the logs, netdata has successfully given the emails to your MTA and your MTA says it dispatched them...

I am not sure either, why when you do it by hand it works, but when you do it with the script it fails.

Since your MTA logs that it received them and dispatched them, I guess it must be something related to anti-spamming, or a kind of filtering performed by your mail server. The emails netdata sends are HTML and contain external links - this may be triggering a rule somewhere.

**Comment by mvandeplassche** [comment]
Weird, since as you said it works when I do it by hand. Could it be a header-related bug ?

Anyway I'm not going to waste your time with this, thanks for replying ;)

I'll let you know if I fix this.

**Comment by ktsaou** [comment]
I don't think is a header. The sendmail command I gave you has [exactly the same headers netdata uses](https://github.com/firehol/netdata/blob/4172f7fdd14d574e365d9a7005f20a35c294926e/plugins.d/alarm-notify.sh#L1304-L1308).

Also the [sendmail command is the same](https://github.com/firehol/netdata/blob/4172f7fdd14d574e365d9a7005f20a35c294926e/plugins.d/alarm-notify.sh#L635).

So, we are left with just the content.

If you want to verify it, copy the script and [replace this](https://github.com/firehol/netdata/blob/4172f7fdd14d574e365d9a7005f20a35c294926e/plugins.d/alarm-notify.sh#L1309-L1391), with just "hello world" (make sure there is an empty line above it) and call the script again. It should work.

**Comment by mvandeplassche** [comment]
Yep, I confirm, it worked. 

(Received 2 mails out of 3 atm but I guess the third is on its way)

**Comment by ktsaou** [comment]
Are you sure the emails are not in the spam folder?

**Comment by mvandeplassche** [comment]
I checked the spam folder after every test.

**Comment by ktsaou** [comment]
hm... I have never seen gmail losing an email. Are you sure the emails are sent to it? Is there anything on your setup that could filter out emails?

**Comment by mvandeplassche** [comment]
I have a very simple setup. I used ssmtp to send available upgrade notifications (and fail2ban alerts but I stopped them). It is also used by a wordpress plugin (contact form 7). 

I even checked the "from" mailbox. No mail. 

According to /var/log/mail.log emails were sent.

**Comment by mvandeplassche** [comment]
I completely disabled iptables : 

- Manual sending still works
- Script sending still no results

**Comment by mvandeplassche** [comment]
So... I replaced [this](https://github.com/firehol/netdata/blob/4172f7fdd14d574e365d9a7005f20a35c294926e/plugins.d/alarm-notify.sh#L1309-L1391) with this : 

`${host} ${status_message}<br /><br />

Chart : ${chart}<br /><br />

Alarm : ${alarm}${info_html}<br /><br />

Family : ${family}<br /><br />

Severity : ${severity}<br /><br />

Time : ${date}${raised_for_html}<br /><br />

The source of this alarm is line ${src}<br /><br />`

It's working.

**Comment by ktsaou** [comment]
I made the notification MIME encoded multipart, containing both text and html versions.
Could you please check now?

**Comment by mvandeplassche** [comment]
Thank you for working to fix this. Still the same result, but I noticed something...

It seems to be a problem from my server or my ssmtp configuration. I just noticed my other email notifications are sent but not received (apticron) in /var/log/mail.log. 

I don't get why some emails are received and some are not, but this is not a problem relative to netdata. Sorry about that.

**Comment by ktsaou** [comment]
ok, no problem...

**Comment by makutamatey** [comment]
> Hi, netdata does this:
> 
> ```shell
> # become user netdata
> su -s /bin/bash netdata
> 
> # send an email
> /usr/sbin/sendmai -t <<EOF
> To: email@email.com
> Subject: my subject
> Content-Type: text/html
> 
> hello world
> EOF
> ```
> 
> Does this work?

Please you mean the above should be added to /etc/netdata/edit-config health_alarm_notify.conf or just run it in the terminal?

**Comment by cakrit** [comment]
If you need email notifications, you should just ensure you can send and receive an email from your server, using the sendmail command. That takes a bit of configuring to set up, that depends on your system. Once you do that, you don't need to configure anything in netdata, you will be receiving alarms as email notifications. If you prefer a different notification method, you'll need to follow the general instructions [here](https://docs.netdata.cloud/health/notifications/) and  the method-specific instructions that are shown under "Supported notifications". You'll see those on the left side menu when you click on the link.
