### ISSUE TITLE
Disable web access but not API

### ISSUE THREAD

**Issue by mims92** [firehol/netdata#2207]
Hi,

I've installed Netdata on two servers. I streamed on to the other (but both of them have access to each other, weird).

My question is: how can I disable web on the slave and have a web access only on the master?

Netdata runs under Nginx.

Thank you

**Comment by ktsaou** [comment]
Hi, check this: https://github.com/firehol/netdata/wiki/Replication-Overview#netdataconf-configuration

**Comment by mims92** [comment]
Oh, thank you! I missed this little part :)

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
