### ISSUE TITLE
ERROR: failed to set SO_REUSEPORT on socket 3 when starting netdata

### ISSUE THREAD

**Issue by mims92** [firehol/netdata#2208]
Hello (again),

Each time I kill `killall netdata` and start `netdata`, I have an error:
```
ERROR: failed to set SO_REUSEPORT on socket 3
```
Netdata can be access on port 19999 though.
To remove this error, I need to reinstall netdata.

I don't know if this issue can cause `server is not replying properly.` from a streaming server.

**Comment by ktsaou** [comment]
Distro and kernel version?

**Comment by mims92** [comment]
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Comment by ktsaou** [comment]
hm.... I just checked all the netdata installations I have on debian. This error does not appear on any of them.
Does this happen if you do `systemctl restart netdata`?

**Comment by mims92** [comment]
`systemctl: command no found` :)

I don't get it neither. It works on other servers.

**Comment by ktsaou** [comment]
wait a moment, debian 8 is a systemd system. Could you please run `cat /etc/os-release`?

**Comment by mims92** [comment]
Oops... wrong server. It's Debian 7 `Linux  3.2.0-4-amd64 #1 SMP Debian 3.2.81-1 x86_64 GNU/Linux`

**Comment by ktsaou** [comment]
ok, could you please try `service netdata restart`? Does it log this error?

**Comment by mims92** [comment]
```
$ service netdata restart
[ ok ] Stopping real-time performance monitoring: netdata.
[....] Starting real-time performance monitoring: netdata2017-05-22 12:19:14: netdata ERROR: failed to set SO_REUSEPORT on socket 3
. ok 
$
```

**Comment by ktsaou** [comment]
ok, I found it.

Your kernel does not have support for `SO_REUSEPORT` and netdata just prints the error: https://github.com/ktsaou/netdata/blob/b689036d47ee0004f1ac11e888073d0557e28ca9/src/socket.c#L49-L51

I will make this silent if there is no support for it.

**Comment by mims92** [comment]
Thank you 👍 

Does that make my streaming server (slave) complain about server is not replying properly?

**Comment by ktsaou** [comment]
No, for your system this was a useless error. Just ignore it.

**Comment by ktsaou** [comment]
merged it!
thank you for reporting it.

**Comment by mikeweilgart** [comment]
I get this same error on RHEL 6.2 with kernel 2.6.32-220.el6.x86_64, but I see that I've got netdata version 1.6.0.  So I assume it's just a noise error here, also (and fixed in 1.7)?

**Comment by ktsaou** [comment]
> I get this same error on RHEL 6.2 with kernel 2.6.32-220.el6.x86_64, but I see that I've got netdata version 1.6.0. So I assume it's just a noise error here, also (and fixed in 1.7)?

yeap. But it is not "fixed". v1.7+ just doesn't print the error. You can ignore it too.
btw, yes update to 1.7, it is a lot better. The best netdata is in the git though...

**Comment by mikeweilgart** [comment]
@ktsaou I still see it in 1.7:

```
[root@servername ~]# service netdata status
netdata (pid  19826) is running...
[root@servername ~]# service netdata restart
Stopping netdata...                                        [  OK  ]
Starting netdata...2017-09-07 03:12:36: netdata ERROR: failed to set SO_REUSEPORT on socket 3 (errno 92, Protocol not available)
2017-09-07 03:12:36: netdata ERROR: failed to set SO_REUSEPORT on socket 5 (errno 92, Protocol not available)
                                                           [  OK  ]
[root@servername ~]# /opt/netdata/bin/netdata -version
netdata 1.7.0-211-gaebbd496_rolling
[root@servername ~]# uname -a
Linux servername.domainname 2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011 x86_64 x86_64 x86_64 GNU/Linux
[root@servername ~]# cat /etc/*release
Red Hat Enterprise Linux Server release 6.2 (Santiago)
Red Hat Enterprise Linux Server release 6.2 (Santiago)
[root@servername ~]#
```

This is FYI since I'm ignoring it as a "noise" error as advised.  But I thought you would want to know.

**Comment by ktsaou** [comment]
@mikeweilgart thanks!
The binary package is built on a newer kernel / libc that has this option available at compile time. So, at runtime it fails and netdata logs this.

So, yes you can ignore it. The fix I provided above simply does not execute this part of the code at all, if the kernel / libc netdata is compiled with, does not support this option.

I will provide a fix that will silence it based on `errno`.

**Comment by ktsaou** [comment]
ok, here it is. 
thank you for reporting it.

**Comment by ktsaou** [comment]
merged it.

**Comment by atsaloli** [comment]
I just updated from 1.7 to 1.10 and it's nice not to have the noise from this error anymore. Thank you!
