### ISSUE TITLE
Is it safe to run netdata without password on your webserver?

### ISSUE THREAD

**Issue by mt247** [firehol/netdata#2209]
So is it safe to run it on my webserver for example in example.com/netdata so everyone could look at it? Or can they get some sort of information out of netdata which is bad?

**Comment by mt247** [comment]
And is there a way to hide all the sensitive data from example.com/netdata directory?

**Comment by ktsaou** [comment]
Hi, you have many alternatives to restrict access to netdata.
Check this: https://github.com/firehol/netdata/issues/2168#issuecomment-300475906

**Comment by mt247** [comment]
"Management applications must never be directly exposed to the internet, with or without authentication."

Is netdata this kind of application? I would like not to restrict netdata using anyway and provide stats like load in server to users, I was just asking is it safe to do it this way or can I hide some sensitive information or is there any?

**Comment by ktsaou** [comment]
Well, if you are under attack and the attackers have access to netdata, they will know if they are doing right or wrong. They will also be able to see what other apps you run which they may attack.
So, yes netdata is a management application. If you don't care about the risk, you can expose it to the internet. For most uses though, netdata should be restricted.

**Comment by mt247** [comment]
Ok, thanks. I'm just running small home server which have only few users running teamspeak and nextcloud.

**Comment by Altiano** [comment]
Wouldn't it be nice if we can configure username and password?
I'm just running on one machine, not so complex application yet.
Just quote from the docs:

> I concluded then that configuring software like that is a waste for time and effort.

**Comment by ktsaou** [comment]
> Wouldn't it be nice if we can configure username and password?

It would, but for most of us this would be useless. netdata is a distributed app. I run hundreds of them. Even at my home I have 20. Configuring authentication on all of them is not practical. If you really need authentication, just install nginx in front of netdata. It is just 5 mins to do it.

**Comment by ktsaou** [comment]
I have added a wiki page regarding netdata security: https://github.com/firehol/netdata/wiki/netdata-security

Cleaning up. If you need further help, just post here.
