### ISSUE TITLE
history = 3600 changes & effects ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#221]
Seems /etc/netdata/netdata.conf has `history = 3600` and that is time range in seconds for what's displayed in the charts so the last 60 minutes / 1hr of stats ?

* What can I expect server resource usage wise - cpu, memory consumption for raising the history value beyond 3600 ? Is there a rule of thumb ? or internal benchmark results of observed resource consumption increases that you can share ?
* there seems to be a lot of entries for history = 3600 in /etc/netdata/netdata.conf do i just change the global one ?
* is there a way to roughly estimate the memory usage required ?

cheers

George

**Comment by ktsaou** [comment]
> so the last 60 minutes / 1hr of stats?

yes

> What can I expect server resource usage wise - cpu, memory consumption for raising the history value beyond 3600 ? Is there a rule of thumb ? or internal benchmark results of observed resource consumption increases that you can share

At 3600 expect 10-15MB or RAM. Read the memory requirements page at the wiki for more information: https://github.com/firehol/netdata/wiki/Memory-Requirements

If you can enable the kernel memory deduper, please do so: https://github.com/firehol/netdata/wiki/Memory-Deduplication---Kernel-Same-Page-Merging---KSM

The history size will only affect CPU when you zoom out the charts. But in general, for just a user accessing the charts, this is ignorable.

> there seems to be a lot of entries for history = 3600 in /etc/netdata/netdata.conf do i just change the global one ?

It is an hierarchy. The global will change all of them. The plugin ones will affect only the charts generated by these plugins. Of course you can override this inheritance by setting it per chart.

> is there a way to roughly estimate the memory usage required

Check the memory requirements page. Also, netdata itself reports its memory at the charts (applications section).

**Comment by centminmod** [comment]
cheers @ktsaou from the memory requirements page, the definition of dimensions = the chart types ? i.e. system.cpu is 1 dimension ?

if so the formula would be count the chart types in play

```
cat /etc/netdata/netdata.conf | grep "^\[" | cut -d '[' -f 2 | cut -d ']' -f 1 | grep -v ^global$ | grep -v "^plugin" | sort -u | wc -l
199
```

then using the formula would be ~65.588 MB for 24hr history ?
```
86,400 seconds * 4 bytes * 199 = 65.588
```

**Comment by ktsaou** [comment]
system.cpu has 9 dimensions (from the settings menu, select "Which dimensions to show? = All" to show them all at the charts.

You can find the number of dimensions using this:

```sh
curl "http://localhost:19999/netdata.conf" 2>/dev/null | egrep "[[:space:]]dim[[:space:]].*[[:space:]]algorithm[[:space:]]*=" | wc -l
```

Also, the current API to get all charts and dimensions is this: http://netdata.firehol.org/api/v1/charts

There is a deprecated (old) API which provides the current memory information: http://netdata.firehol.org/all.json This one have the current memory used by netdata per chart and its bottom for the whole of netdata.

**Comment by centminmod** [comment]
sweet awesome info to have.. thanks @ktsaou  :)

**Comment by centminmod** [comment]
interestingly netdata app mem profile reports ~465.8MB memory so roughly around that, that is committed memory or memory in use ?

![image](https://cloud.githubusercontent.com/assets/5899584/14507785/b7595bca-0207-11e6-8b65-f85efc6a7ae0.png)

**Comment by ktsaou** [comment]
This is the memory used by all netdata programs, the whole process tree (charts.d, apps.plugin. node.d, tc-helper), including their heaps (pre-garbage collectors, etc) The actual database is probably 1-2MB more than your calculation. If you have KSM enabled you can see the exact database size at the `offered` dimension.

To find the actual memory savings for KSM, you will have to wait up to `history` seconds (initially, it is all zeros, so 95% deduplication will be reported, but it will decline as memory fills up).

**Comment by ktsaou** [comment]
updated my answer.

**Comment by centminmod** [comment]
sweet thanks for clarification as i was just about to mention the differences with smem reported PSS vs RSS sizes
```
smem -tuk
User     Count     Swap      USS      PSS      RSS 
nobody       1        0   656.0K   719.0K     1.2M 
dbus         1        0   880.0K   957.0K     1.8M 
ntp          1        0  1004.0K     1.1M     2.3M 
polkitd      1        0     4.9M     5.7M     8.2M 
postfix      4        0     5.5M     6.7M    16.8M 
redis        6        0    14.9M    15.4M    21.4M 
netdata      3        0    73.6M    75.1M   469.5M 
mysql        1        0    75.4M    75.7M    78.0M 
root        25        0   100.2M   128.5M   214.9M 
nginx       14        0   242.8M   277.8M   472.1M 
---------------------------------------------------
            57        0   519.8M   587.7M     1.3G
```

**Comment by ktsaou** [comment]
ok. I have now a task to compress this memory on netdata restart. It stresses the disks now a lot when restarting netdata with such a big db.

**Comment by centminmod** [comment]
would be nice.. looking forward to testing compression on my test server :)

**Comment by ktsaou** [comment]
I am closing this. netdata will change its memory management entirely soon, so this will not be an issue.
