### ISSUE TITLE
Installation issues with Centos 7

### ISSUE THREAD

**Issue by suedeyoung** [firehol/netdata#2215]
Hey guys! I randomly found this while going through hours of googling for a good monitoring system and stumbled across your guys. I was trying out the installation but it doesn't seem to be working on my end here so I wanted to see if there was anything that we can do for that. 

Copy of what I tried to do on the installation but it was failing:

[root@147418 /]# git clone https://github.com/firehol/netdata.git --depth=1
Cloning into 'netdata'...
remote: Counting objects: 601, done.
remote: Compressing objects: 100% (553/553), done.
remote: Total 601 (delta 89), reused 211 (delta 33), pack-reused 0
Receiving objects: 100% (601/601), 2.99 MiB | 0 bytes/s, done.
Resolving deltas: 100% (89/89), done.
[root@147418 /]# cd netdata/
[root@147418 netdata]# ./netdata-installer.sh 

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

 --- Run autotools to configure the build environment --- 
[/netdata]# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: -: no such file or directory
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
 FAILED   

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

I tried the --libs-are-really-here command as well while following your installation guide but still got the same output as the above but the two things that it wasn't liking was installed as well. 

From Yum when I tired to install the packages as well and update them: 

Package libuuid-devel-2.23.2-33.el7_3.2.x86_64 already installed and latest version
Package zlib-devel-1.2.7-17.el7.x86_64 already installed and latest version

Do you have any other ideas on how to proceed?

**Comment by suedeyoung** [comment]
Just to post a bit more about it to try to help, I also tried the basic build tools that it talked about and got this back: 

Package gcc-4.8.5-11.el7.x86_64 already installed and latest version
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
No package pkg-config available.
Nothing to do

**Comment by ktsaou** [comment]
Have you run the pre-installation script that detects the packages required on your system?

Check this: https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system

**Comment by suedeyoung** [comment]
Yeah I had run that first since I was following the guide that you linked but I just did it again just to make sure. 

[root@147418 /]# curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
Loading /etc/os-release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

/etc/os-release information:
NAME            : CentOS Linux
VERSION         : 7 (Core)
ID              : centos
ID_LIKE         : rhel fedora
VERSION_ID      : 7

We detected these:
Distribution    : centos
Version         : 7
Codename        : 7 (Core)
Package Manager : install_yum
Packages Tree   : centos
Detection Method: /etc/os-release
Default Python v: 2 


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  

yum install MySQL-python PyYAML autoconf autoconf-archive autogen automake curl gcc git libmnl-devel libuuid-devel lm_sensors make nmap-ncat nodejs pkgconfig python python-psycopg2 python-requests zlib-devel 


Press ENTER to run it > 
yum install MySQL-python PyYAML autoconf autoconf-archive autogen automake curl gcc git libmnl-devel libuuid-devel lm_sensors make nmap-ncat nodejs pkgconfig python python-psycopg2 python-requests zlib-devel 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.steadfast.net
 * epel: fedora-epel.mirror.lstn.net
 * extras: mirror.steadfast.net
 * updates: mirror.steadfast.net
Package MySQL-python-1.2.5-1.el7.x86_64 already installed and latest version
Package PyYAML-3.10-11.el7.x86_64 already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package autoconf-archive-2016.09.16-1.el7.noarch already installed and latest version
Package autogen-5.18-5.el7.x86_64 already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package curl-7.29.0-35.el7.centos.x86_64 already installed and latest version
Package gcc-4.8.5-11.el7.x86_64 already installed and latest version
Package git-1.8.3.1-6.el7_2.1.x86_64 already installed and latest version
Package libmnl-devel-1.0.3-7.el7.x86_64 already installed and latest version
Package libuuid-devel-2.23.2-33.el7_3.2.x86_64 already installed and latest version
Package lm_sensors-3.4.0-4.20160601gitf9185e5.el7.x86_64 already installed and latest version
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
Package 2:nmap-ncat-6.40-7.el7.x86_64 already installed and latest version
Package 1:nodejs-6.10.2-1.el7.x86_64 already installed and latest version
Package 1:pkgconfig-0.27.1-4.el7.x86_64 already installed and latest version
Package python-2.7.5-48.el7.x86_64 already installed and latest version
Package python-psycopg2-2.5.1-3.el7.x86_64 already installed and latest version
Package python-requests-2.6.0-1.el7_1.noarch already installed and latest version
Package zlib-devel-1.2.7-17.el7.x86_64 already installed and latest version
Nothing to do

All Done! - Now proceed to the next step.

**Comment by ktsaou** [comment]
On my centos 7, I see the command `autom4te` is available.
This command is part of package `autoconf`.

```
[root@centos7 /]# command -v autom4te
/usr/bin/autom4te

[root@centos7 /]# yum whatprovides /usr/bin/autom4te
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.dataone.nl
 * extras: centos.mirror.triple-it.nl
 * updates: centos.mirror.transip.nl
autoconf-2.69-11.el7.noarch : A GNU tool for automatically configuring source code
Repo        : base
Matched from:
Filename    : /usr/bin/autom4te

autoconf-2.69-11.el7.noarch : A GNU tool for automatically configuring source code
Repo        : @base
Matched from:
Filename    : /usr/bin/autom4te

```

**Comment by suedeyoung** [comment]
It looks like mine is in another location for some reason when I did command -v autom4te. Would this cause any issues? 

[root@147418 /]# command -V autom4te
autom4te is /usr/local/bin/autom4te

**Comment by ktsaou** [comment]
It should not be a problem if it is in the system path. But as you can see, it cannot find it:

```
[/netdata]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: -: no such file or directory
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
FAILED
```

This command is run by `autoreconf`, not the netdata installer.  So, it seems a problem with the toolchain you have installed.

**Comment by suedeyoung** [comment]
What would you recommend to try to get that to work? I'm still getting started with things other then cPanel since I want to learn but never poked at autoreconf before. 

Do you think that removing it with yum and then installing it again would help?

**Comment by suedeyoung** [comment]
Alright so I reinstalled the server since it was just a testing server and it's working now. I guess when the other admin installed nagios to the server to test it out it was messing up the install for some weird reason.

**Comment by ktsaou** [comment]
ok, nice you solved it.
