### ISSUE TITLE
Opentsdb multiple keys

### ISSUE THREAD

**Issue by tschibelfeldt** [firehol/netdata#2217]
Hi 

Is it possible to add multiple keys to the backend part for opentsdb right now the only key shipped to influxdb is the host need keys like
Environment
Location
Group
and so on

**Comment by ktsaou** [comment]
An example? I am not sure I understand the question... (sorry)

**Comment by tschibelfeldt** [comment]
Hi
this is what I have in influxdb(opentsdb) from netdata
netdata.users.vmem.root,host=is-udvrhel6

host is a key I would like something like
netdata.users.vmem.root,host=is-udvrhel6,location=anywhere,environment=production,group=app-servers

so that netdata will add more keys to the records

**Comment by ktsaou** [comment]
ok. If I understand this right, you just need netdata to append something on all metrics sent to opentsdb. One string, for all metrics of a specific host.

So, if we add a `netdata.conf` option which you can use to give all these settings per host, you will be satisfied.

Right?

**Comment by tschibelfeldt** [comment]
Hi 
That is exactly what I need. Makes grouping and query so much better in grafana

**Comment by ktsaou** [comment]
ok. I understand this should also be a configuration option for mirrored hosts too (i.e. netdata master-slave replication `stream.conf`). To support this for slaves requires some work.

If you don't plan to use netdata replication, I can add this now to netdata.conf to be applied globaly. What do you think?

**Comment by tschibelfeldt** [comment]
Hi 
I dont need it for for replication I am using opentsdb and don't plan on replication anytime soon

Thanks for swift and fantastic service

**Comment by ktsaou** [comment]
added it - it is untested.
Please checkout my repo and test it. I would appreciate it if you could test it both with and without this setting (to verify we didn't break anything).

**Comment by ktsaou** [comment]
clone `https://github.com/ktsaou/netdata` (my repo).

**Comment by tschibelfeldt** [comment]
Hi 
Have tested both and it works perfectly. Thanks alot

**Comment by ktsaou** [comment]
merged it!
thanks!
