### ISSUE TITLE
QOS class names not showing in netdata

### ISSUE THREAD

**Issue by johnnyb2good** [firehol/netdata#2218]
Hello, I'm experiencing a similar issue to #1577 (also titled QOS class names not showing in netdata).  After initial installation of FireQOS, Netdata was showing class names properly.  Then at some point, perhaps after testing the fireqos dump and fireqos status commands, Netdata started showing class numbers and OS based interface names rather than the "world-in" and "world-out" assigned names.

Netdata is showing eth0-ifb (inbound) and eth0 (outbound) with class numbers 11 through 20 rather than the class names.  Screen shot follows:

![image](https://cloud.githubusercontent.com/assets/20143009/26286354/81b11b9a-3e31-11e7-8333-ef1a81ceb312.png)

Similar to #1577, my path for fireqos_run_dir="/usr/local/var/run/fireqos", and I've tried adding this variable assignment to file /etc/netdata/tc-qos-helper.conf, restarting fireqos and netdata services, but the result is the same.

Running /usr/libexec/netdata/plugins.d/tc-qos-helper.sh I get ongoing output near the start of which does contain:

SETDEVICENAME world-in
SETCLASSNAME 11: tcpsyn
SETCLASSNAME 12: tcpack
SETCLASSNAME 13: ssh
SETCLASSNAME 14: https
SETCLASSNAME 15: http
SETCLASSNAME 16: icmp
SETCLASSNAME 17: smtp
SETCLASSNAME 18: dns
SETCLASSNAME 19: ntp
SETCLASSNAME 20: default
SETDEVICEGROUP eth0
END eth0-ifb

and

SETDEVICENAME world-out
SETCLASSNAME 11: tcpsyn
SETCLASSNAME 12: tcpack
SETCLASSNAME 13: ssh
SETCLASSNAME 14: https
SETCLASSNAME 15: http
SETCLASSNAME 16: icmp
SETCLASSNAME 17: smtp
SETCLASSNAME 18: dns
SETCLASSNAME 19: ntp
SETCLASSNAME 20: default
SETDEVICEGROUP eth0
END eth0

This was just a testing fireqos.conf configuration to get started.  It is:

DEVICE=eth0

INPUT_SPEED=40Gbit
OUTPUT_SPEED=1Gbit
LINKTYPE="ethernet"

interface $DEVICE world-in input rate $INPUT_SPEED balanced
    class tcpsyn commit 2%
        match tcp syn
    class tcpack commit 2%
        match tcp ack
    class ssh commit 2%
        match tcp port 22
    class https commit 50%
        match tcp port 443
    class http commit 20%
        match tcp port 80
    class icmp commit 2%
        match icmp
    class smtp commit 2%
        match tcp port 25,110,143,465,587,993,2525,2526
    class dns
        match tcp port 53
    class ntp
        match tcp port 123
    class default

interface $DEVICE world-out output rate $OUTPUT_SPEED balanced
    class tcpsyn commit 2%
        match tcp syn
    class tcpack commit 2%
        match tcp ack
    class ssh commit 2%
        match tcp port 22
    class https commit 50%
        match tcp port 443
    class http commit 20%
        match tcp port 80
    class icmp commit 2%
        match icmp
    class smtp commit 2%
        match tcp port 25,110,143,465,587,993,2525,2526
    class dns
        match tcp port 53
    class ntp
        match tcp port 123
    class default

Changing to a simpler config file with just one or two classes does not resolve the issue.

ls -l $(which fireqos) reports:

lrwxrwxrwx 1 root root 32 May 20 23:11 /usr/local/sbin/fireqos -> ../libexec/firehol/3.1.3/fireqos

ls -l /usr/local/var/run/fireqos/ reports:

total 32
drwxr-xr-x 2 root root 4096 May 21 14:35 ifaces
drwxr-xr-x 2 root root 4096 May 21 14:35 ifbs
-rw-r--r-- 1 root root 8384 May 21 14:35 world-in.conf
-rw-r--r-- 1 root root 8269 May 21 14:35 world-out.conf

Fireqos and Firehol version: 3.1.3
Netdata version: 1.6.0-362-g2e3beb3_rolling, commit 2e3beb3
OS is Ubuntu 16.04 LTS.
Kernel is 4.9.28 custom compiled to allow for IFB support.

Any help is appreciated.  Thanks!

Johnny

**Comment by ktsaou** [comment]
Could you please run the `tc-qos-helper.sh` us user netdata? I guess there is a permissions issue somewhere...

```sh
# become user netdata
su -s /bin/bash netdata

# run tc-qos-helper.sh
/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

Does it output the class names now?

**Comment by johnnyb2good** [comment]
No it does not.  Only:

BEGIN eth0-ifb
<snip>
END eth0-ifb
BEGIN eth0
<snip>
END eth0

Good find!  I'll try to dig into it more shortly to see why.

**Comment by johnnyb2good** [comment]
Default permissions for the /usr/local/ directory structure were:

root@hydrogen:~# ls -la /usr/local
total 52
drwxr-xr-x 13 root       root       4096 May 20 22:55 .
drwxr-xr-x 11 root       root       4096 Dec 14 00:05 ..
(...snip...)
drwxr-xr-x  2 root       root       4096 May 20 23:11 sbin
drwxr-xr-x 10 root       root       4096 May 20 22:52 share
drwxr-xr-x  2 root       root       4096 Jul 22  2016 src
drwx------  6 root       root       4096 May 21 17:20 var

root@hydrogen:~# ls -la /usr/local/var
total 24
drwx------  6 root root 4096 May 21 17:20 .
drwxr-xr-x 13 root root 4096 May 20 22:55 ..
drwx------  3 root root 4096 May 21 17:20 cache
drwx------  3 root root 4096 May 21 17:20 lib
drwx------  5 root root 4096 May 21 17:20 run
drwx------  3 root root 4096 May 20 23:13 spool

root@hydrogen:~# ls -la /usr/local/var/run
total 20
drwx------ 5 root root 4096 May 21 17:20 .
drwx------ 6 root root 4096 May 21 17:20 ..
drwx------ 2 root root 4096 May 21 19:51 firehol
drwxr-xr-x 4 root root 4096 May 21 14:36 fireqos
drwx------ 2 root root 4096 May 21 09:19 link-balancer
-rw------- 1 root root    0 May 21 18:43 update-ipsets.lock

root@hydrogen:~# ls -la /usr/local/var/run/fireqos/
total 40
drwxr-xr-x 4 root root 4096 May 21 14:36 .
drwx------ 5 root root 4096 May 21 17:20 ..
drwxr-xr-x 2 root root 4096 May 21 14:35 ifaces
drwxr-xr-x 2 root root 4096 May 21 14:35 ifbs
-rw-r--r-- 1 root root 8384 May 21 14:35 world-in.conf
-rw-r--r-- 1 root root 8269 May 21 14:35 world-out.conf

I modified /usr/local/var and /usr/local/var/run directories to 755 permissions.

This resolved the problem.  Now executing this:

# become user netdata
su -s /bin/bash netdata

# run tc-qos-helper.sh
/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

yields the expected output and the Netdata graphs have corrected themselves after a service restart.

If you see any other potential permissions issues here, please let me know.  I'm not sure how the issue was introduced or if there should be a different set of default permissions (ex: 755 instead of 700) across the whole /usr/local/var tree to avoid further permissions issues like this.

Thanks,

Johnny

**Comment by ktsaou** [comment]
I guess the program that first created these directories on your system gave wrong permissions to them (wrong umask?).
`/usr/local/var/run` should have the same permissions with `/var/run`, which is world readable.

**Comment by johnnyb2good** [comment]
umask seems good -- it defaults to 022.  The timestamps of most of the sub-directories in /usr/local/var (including /usr/local/var) with 700 permissions were timestamped 2017-05-21 @ 17:20.  The only files or directories sharing the same timestamp on all the disk filesystems are some update-ipsets related directories.  Example: Directory /usr/local/var/cache/update-ipsets has the same timestamp.  Maybe this implies those permissions were somehow set by the install of update-ipsets?

**Comment by ktsaou** [comment]
I see update-ipsets sets its umask to 077.
But, this could only happen if update-ipsets created these directories. It creates them if they are not there. So, it might be the problem.

I am fixing it.
However the same problem exists for firehol too.

**Comment by ktsaou** [comment]
merged the fix.
thank you for reporting it.

**Comment by johnnyb2good** [comment]
Hi Costa.  I installed firehol 3.1.3 and iprange last Friday on a Centos 7 system without update-ipsets.  I checked it today and it does have the same issue -- 700 dir permissions including and throughout /usr/local/var.  Thanks for fixing and thank you for all the amazing software!

Johnny

**Comment by johnnyb2good** [comment]
(scratch the '...without update-ipsets' part of my last comment.  I forgot firehol 3.1.3 comes with update-ipsets.  Thanks again!)
