### ISSUE TITLE
chart viewing - panning & dragging options ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#222]
To view individual chart data you can use the left and right arrows to pan or drag the chart left and right. But is there a shortcut of some kind to quickly up to the very beginning or end of the chart's plotted data ?

cheers

George

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/14497947/50441e4a-01a1-11e6-9f7f-d340167d6694.png)

The "Play" button.

**Comment by centminmod** [comment]
the play button would jump to most recent time frame, but there's no shortcut to jump to beginning of the time frame i.e. 3600 seconds ago ?

**Comment by ktsaou** [comment]
sorry... not currently.

**Comment by centminmod** [comment]
ok thanks for clarification

just wondering as if i set history to expand to 24+ hours, it would take a lot more drags to get to beginning of the time frame :)

**Comment by ktsaou** [comment]
zoom out first.
But you are right, it is needed.

**Comment by centminmod** [comment]
ah thanks for the zoom out tip :)

**Comment by rahulpathakgit** [comment]
Is there a configuration option to enable the play and pause button, currently I don't see them on the charts

**Comment by ktsaou** [comment]
just update netdata (git pull) and once running press control-F5 on your browser.
I added it 2 days ago.

**Comment by rahulpathakgit** [comment]
great, got them now, thanks.
And BIG thanks for creating such wonderful tool

**Comment by ktsaou** [comment]
shall we close this? Is something remaining?

**Comment by centminmod** [comment]
sweet thanks @ktsaou

**Comment by pikomen** [comment]
3 years after and still no option to move in time quickly...

**Comment by cakrit** [comment]
> 3 years after and still no option to move in time quickly...

See issue #6061. Can you help us with a PR?
