### ISSUE TITLE
netdata upstreams are not cleaning up slave deleted charts

### ISSUE THREAD

**Issue by runecalico** [firehol/netdata#2222]
I have setup a few os level netdata installations on hosts with docker installed, if I view the gui on the physical host the container charts are current (so old containers drop off and new ones show up), however the charts on the central netdata do NOT update. New containers don't show up, and old containers stick around.

How can I determine if this is a bug or configuration error?

The streaming clients are setup using api key which all of them share,  memory mode = save in [global] and mode=multi-threaded in [web].

The central netdata is running in a docker container.

stream.conf with single api key, default memory mode = ram,  most plugins disabled in netdata.conf, memory mode = save in [global], and saving stats to an opentsdb backend (influx). Any help would be appreciated. Thanks.

**Comment by runecalico** [comment]
ah probably would help if I said what release I was running (on all of them)
Release -  1.6.0-343-gba8cb51_rolling, netdata commit: ba8cb51

**Comment by ktsaou** [comment]
I tried to reproduce this without success.

These are the steps I used:

1. setup master-slave between 2 hosts
2. on the slave, start docker container A
3. hit F5 on the dashboard of the slave at the master - the chart was shown
4. stopped container A - hit F5 on the slave dashboard at master - the chart stopped updating
5. started container B (on the slave)
6. hit F5 on the slave dashboard at master - the new container showed up
etc

Could you please help me find a path to reproduce it?

Keep in mind netdata cleans up obsolete charts after some time (by default 1 hour). So, don't expect them to vanish immediately.

**Comment by runecalico** [comment]
Hmm.. Okay, then I'll poke around and try rebuilding my setup piece by piece and see if I can isolate when it stops, as well as reproduce. If I can't then that's fine too as that means it's working :)

**Comment by runecalico** [comment]
hmm... Something is seriously off... I think I will definitely have to rebuild from scratch and see when it starts going wrong (assuming it does again).  Just to add proof that I'm not imaging things.. on Slave A we see that the disks only go up to dm-49
![image](https://cloud.githubusercontent.com/assets/18315837/26403665/9e0ffed0-4054-11e7-83f5-0b2f4bcc1479.png)
But on the master... it's got disks up to dm-52! and that dm-52's chart is still updating! uh.. what?
![image](https://cloud.githubusercontent.com/assets/18315837/26403719/d169f38a-4054-11e7-8fab-3f2b5e335ebe.png)
 
so I'll rebuild, it might take a few days before I have something to post again as an FYI.

**Comment by runecalico** [comment]
Even with using a new master, still having issues. So.. I'll keep the sending host using the current rpm binary, but switch the master to a binary install using the kickstart-static64.sh installed binary. I'm wondering if it's due to how I created the netdata rpm. We sit behind a auth proxy, which tends to greatly discourage the "recommended" installation method....

**Comment by ktsaou** [comment]
I think I know what is happening.

Streaming metrics is not sending a flag that instructs netdata to cleanup obsolete charts. So, at the master, once a chart is created is it is never cleaned up, even if the slave has removed it.

**Comment by runecalico** [comment]
Thanks for continuing to have looked into this, is there any debug output or something I can do or provide that would help?

**Comment by ktsaou** [comment]
No. I just need to add a new flag to the protocol. I will try to do it asap (usually a weekend work).

**Comment by ktsaou** [comment]
implemented in PR #2411 
Can you test it?

**Comment by ktsaou** [comment]
merged it.

**Comment by runecalico** [comment]
Thanks, I'll see about testing it (it will take a bit, as I'll see about doing it next week)

**Comment by ktsaou** [comment]
ok, take your time.
