### ISSUE TITLE
Dropwizard metrics compatibility

### ISSUE THREAD

**Issue by fabMrc** [firehol/netdata#2224]
Hi

Do you have request for dropwizard metrics support ? 
this librairy allow developpers to declare metrics directly in the code and push them to a backend or expose it to a REST endpoint.
Netdata plugin need to know statically all scraped metrics so it may be parametrizeable
http://metrics.dropwizard.io

**Comment by ktsaou** [comment]
Hi,

I see that their metric types are very close to statsd metrics (`meters`, `counters`, `gauges`, `timers`, `histograms` - statsd also define `sets`). The also provide a `healthcheck` metric.

From what I read, I understand they have actually embedded a statsd implementation inside their library. They tried to avoid the overheads of running a separate statsd server. This is a nice comment about [their comparison with statsd](https://github.com/dropwizard/metrics/issues/1130#issuecomment-301445991).

There is a statsd reporter for it: https://github.com/ReadyTalk/metrics-statsd
So, I guess you can use just that to send the metrics to netdata.

**Comment by fabMrc** [comment]
OK nice ! I will try it tomorrow 😀

**Comment by fabMrc** [comment]
Ok https://github.com/ReadyTalk/metrics-statsd/issues/20
It works but all is reported as Gauge. It is an implementation choice of metrics-statsd developpers. I can filter in netdata metrics but Is it possible to display on the same charts many metrics with statsd plugin ?

**Comment by ktsaou** [comment]
nice! let us know of your findings...

**Comment by fabMrc** [comment]
It works nice with synthetic charts: 

Example of configuration

```ini
# start a new app - you can add many apps in the same file
[app]
    # give a name for this app
    # this controls the main menu on the dashboard
    # and will be the prefix for all charts of the app
        name = springboot_application

        # match all the metrics of the app
        metrics = jvm.* counter.*

        # shall private charts of these metrics be created?
        private charts = no

        # shall gaps be shown when metrics are not collected?
        gaps when not collected = no

        # the memory mode for the charts of this app: none|map|save
        memory mode = ram

        # the history size for the charts of this app, in seconds
        history = 60



# create a chart
# this is its id - the chart will be named myapp.mychart
[heap]
    # a name for the chart, similar to the id (2 names for each chart)
        name = heap

        # the chart title
        title = Jvm heap

        # the submenu of the dashboard
        family = Application 1

        # the context for alarm templates
        context = chart.context

        # the units of the chart
        units = MB

        # the sorting priority of the chart on the dashboard
        priority = 91000
        # the type of chart to create: line | area | stacked
        type = line

        # one or more dimensions for the chart
        # type = events | last | min | max | sum | average | percentile | median | stddev
        #        events = the number of events for this metric
        #        last = the last value collected
        #        all the others are only valid for histograms and timers

        dimension = jvm.mem.heap.used used last 1 1000000
        dimension = jvm.mem.heap.max max last 1 1000000
        dimension = jvm.mem.heap.committed committed last 1 1000000
        dimension = jvm.mem.heap.init init last 1 1000000

```

Now if I want to replicate data to a ES backend It becomes more complicated because I read I must use graphite output with TCP and logstash with graphite input plugin. (I did not find logstash conf example)
Do you have plan to offer a dedicated solution for exporting data to ES (for example via HTTP API) ?

**Comment by ktsaou** [comment]
nice!

Increase the history. 60 seconds is too little. (bad default from my side - I updated it).

I am not aware with ES backend. netdata can push metrics as JSON to a backend but I don't know if ES requires something special.

**Comment by ktsaou** [comment]
Could you please post a screenshot of the synthetic charts generated? I want to add your case as an example.

**Comment by fabMrc** [comment]
![screen](https://cloud.githubusercontent.com/assets/11136019/26405721/7be488c0-4096-11e7-8c02-7f54317ad937.jpg)

**Comment by fabMrc** [comment]
![screen](https://cloud.githubusercontent.com/assets/11136019/26406126/a7119938-4097-11e7-8063-b4ed7dbf221c.jpg)

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
