### ISSUE TITLE
monitoring epehemeral nodes, no alarm send when triggered

### ISSUE THREAD

**Issue by Jugulaire** [firehol/netdata#2226]
Hi,

I've configured Netdata to get one master with alarm + graph and slave getting data from all of my server.
When i trigger the alarm on the master email are sended but when i do the same on slave, it does not work. 

I've followed the step in the documentation.
Anybody have already fix this issue ?

**Comment by ktsaou** [comment]
How do you trigger the alarm on the master or the slave?

**Comment by Jugulaire** [comment]
I use sysbench to create high CPU usage

**Comment by ktsaou** [comment]
ok,

On the **slave dashboard at the master**:

1. does the CPU graph show the load?
2. If you open the alarms dialog and find the alarm, there is a badge. What does it show?

**Comment by Jugulaire** [comment]
Thank you for your help. i get the solution. 
It is pretty bizarre but it was a bug in **SSMTP** configuration.
You need to edit  ``/etc/ssmtp/revaliases`` for Netdata user to have sending option working.
