### ISSUE TITLE
Large number of Network Interfaces

### ISSUE THREAD

**Issue by chosenken** [firehol/netdata#223]
We have a box that builds applications using docker.  We end of creating and destroying close to 100 containers a day, or even more.  The problem I am seeing is the `veth` device that gets created for the container, which lives no longer then 5 min on average, is still present on the UI.  This causes an issue with the webpage when it tries to load over 100 interfaces.

Is there a way we could set an exclude list, such that netdata will not monitor devices that start with `veth`?  Or is is possible to turn of `Network Interfaces` completely?

**Comment by ktsaou** [comment]
You have several options (set in `/etc/netdata/netdata.conf`):

1. Turn off network interfaces completely by setting this:

 ```
[plugin:proc]
	/proc/net/dev = no
```

2. Turn off all network interfaces except the ones you have enabled in the configuration:

 ```
[plugin:proc:/proc/net/dev]
	enable new interfaces detected at runtime = no
```

 To enable a few interfaces, use this (for each interface, in this example `eth0`):
 ```
[plugin:proc:/proc/net/dev:eth0]
	enabled = yes
```

**Comment by chosenken** [comment]
@ktsaou , that worked perfectly!  Thanks for the info!  There are sooo many things in the conf file, going to take a while to get it all.

**Comment by ktsaou** [comment]
> There are sooo many things in the conf file, going to take a while to get it all.

That was the idea. To have many options to tweak when you need to, but nothing to configure when the default are just right...
