### ISSUE TITLE
"Behind Lighttpd" / proxy pass failed 

### ISSUE THREAD

**Issue by meepmeep** [firehol/netdata#2230]
Hello

I try to use netdata behind my lighttpd, following the [wiki documentation
](https://github.com/firehol/netdata/wiki/Running-behind-lighttpd) but it fails.

First error : **File does not exist, or is not accessible: /usr/share/netdata/web/netdata/**

So I create a symbolic link (I haven't found a configuration value to specify the fully called URL)
``ln -s /usr/share/netdata/web /usr/share/netdata/web/netdata
``

And then, second error, I get a popup error message : 
`Error 405: Cannot download charts index from server : http://10.7.0.200/netdata/api/v1/charts
`

Does anyone know why ?

**Comment by ktsaou** [comment]
There is something wrong with your URL rewrite configuration at lighttpd. It passes `/netdata/` to netdata on all URLs, which of course does not exist.

So, the URL of your browser might be `http://myhost/netdata/` but on netdata the `/netdata/` part should not be propagated.

**Comment by meepmeep** [comment]
Found the issue.
mod_rewrite was disabled on my configuration ;)
