### ISSUE TITLE
Dashboard graph operation

### ISSUE THREAD

**Issue by oernii** [firehol/netdata#2232]
Hi, is it possible to:
- flip the graph upside down?
- add divider ? - using bytes and the numbers are displayed as 3.00e+, would like to use kB or MB
- fill the graph with color (like net.eth0, currenly my custom graphs are lines only)

thx

**Comment by ktsaou** [comment]
Hi,

1. flip the chart: use css

2. divider: if you have a custom plugin set the divider to the `DIMENSION` line. If you want to change the divider of any other chart, edit `netdata.conf`, find the chart and alter its divider.

3. fill the graph: if you have custom plugin, set the proper parameter to the `CHART` line to `area` or `stacked`. For any other chart, edit `netdata.conf` like before.

**Comment by duecedriver** [comment]
I will pile on here op if you dont mind..

first off... love netdata...

question.. how can I make the meters.. not the graphs.. have a fixed scale.. or better.. remain at the highest level maintained...

as a pilot when I look at a gauge.. not a chart.. its a realime glance at performance not necessarily looking for the exact datapoint... IE when you glance at a speedomiter .. do you really read it.. or are you looking for the need to be in a relative place?

same with netdata.. I would like to glance the guages to see that the needles are in the expected place.. but with changing scale factor.. that is impossible ... making the gauge less readible ..

THANKS!

**Comment by ktsaou** [comment]
Hi,

netdata does not know the scale of metrics - it is not aware of the maximum value a dimension may get. To visualize charts, it uses the visible values to scale the charts to the value-range found in the visible timespan. 

All charts have a "visible timespan", even gauges. This "visible timespan" allows gauges to update their values when you hover your mouse over another chart (this is why this update is so fast).

Dynamic scaling provides better visibility for most cases. There are a few cases however (like the ones you are interested), that this scaling is misleading.

So, if you know the scale of charts, you can set them:

1. For custom dashboards, you can define them at the chart  - the setting inherits the naming convensions of the charting library (for dygraphs use `data-dygraph-valuerange="[min, max]"`, for gauge.js use `data-gauge-min="MIN"` and `data-gauge-max="MAX").

2. For the default dashboard, you can supply your visualization settings, by editing `netdata.conf` and setting in the `[web]` section the setting `custom dashboard_info.js = FILENAME.js`. Unfortunately, this functionality is undocumented. So, here a few directions:

   This file must be under `/usr/share/netdata/web` (owned by `netdata:netdata`). There is already an example file shipped with netdata: https://github.com/firehol/netdata/blob/master/web/dashboard_info_custom_example.js

   You will need to edit the section `customDashboard.context` (context is the template of charts, i.e. all bandwidth chart of network interfaces have the same context). To find the context of a chart, you need to fetch `http://your.netdata.ip:19999/api/v1/charts`, search for your chart and you will find a line with its context.

   Once you have the context, add to FILENAME.js this:

```js
customDashboard.context = {
    "context_of_chart_as_found": {
        valuerange: [min, max]
    } 
};
```

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
