### ISSUE TITLE
how to save netdata in local file

### ISSUE THREAD

**Issue by danfengcao** [firehol/netdata#2233]
I want to foward netdata to kafka, but the kafka api in my company only support get data from log file, so I need to save netdata to local file.

Do you have any ideas to meet that demand?

I can modify C code if needed.

**Comment by ktsaou** [comment]
hm...

Before modifying source code, I would attempt to use `netcat` to listen to a port and save the data to a file, and instruct netdata to connect to that port as a backend and push its metrics.

Have you tried that?

**Comment by danfengcao** [comment]
really interesting, you are a  genius. I will test this method in large-scale clusters.

**Comment by zhangxin0112** [comment]
hi here is the shell how to send netdata to kafka .
1.conf the etc/netdata/netdata.conf to node4:1234
[backend]
         enabled = yes
         data source = average
         type = graphite
         destination = node4:1234
         prefix = netdata
         hostname = dw-dev206
         update every = 10
         buffer on failures = 10
         timeout ms = 20000

2.nc listen node4:1234 and use | to send data to node4:4321
[root@node4 kafka-bin]# nc -l 1234 |nc -l 4321

3.nc get data from node4:4321 and use | to send data to standin with kafka-console-producer.sh
[root@node3 kafka-bin]# nc node4 4321  | kafka-console-producer.sh --broker-list node4:9092,node3:9092 --topic test1

4.comsumer the topic .
[root@node3 bin]# kafka-console-consumer.sh --bootstrap-server node4:9092,node3:9092 --topic test1 --from-beginning

now . u get it .

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
