### ISSUE TITLE
availabe disk space? name a container 

### ISSUE THREAD

**Issue by Homer-Sim** [firehol/netdata#2238]
Hello 

I love to use netdata. After some days of use I have two questions.

Is it possible to name the containers in different names as the cryptic number/letter combination?

And my second question, I am not sure but I can not find any information about the available disk space. Is this supported?

Thanks #

**Comment by ktsaou** [comment]
Hi,

yes to both. But I need your help to figure out why netdata did not detect them by default.

Answer these please:

1. post your `/etc/os-release`
2. post the output of `grep cgroup-name.sh /var/log/netdata/error.log`
3. post the output of `cat /proc/self/mountinfo`

You can configure them by hand, but let's find first why this happened to you...

**Comment by ktsaou** [comment]
And:

4. Do you run netdata in a container or directly at the host?

**Comment by Homer-Sim** [comment]
in a container

**Comment by ktsaou** [comment]
hm... in a container things are not easy. It can be done, but you will need to:

1. pass docker.sock to the container netdata runs
2. expose all mount points of the host to the container netdata runs

So, both of the above are container configuration you need to do.

The whole thing will be a lot easier if you run netdata at the host (actually, just install it at the host - everything will work).

**Comment by Homer-Sim** [comment]
I added now the socked setting but containers are not displayed anymore

This is my docker command

docker run -d --cap-add SYS_PTRACE \
  --name=netdata \
  --restart=always \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 19999:19999 titpetric/netdata

**Comment by ktsaou** [comment]
hm... I don't know.
@titpetric could you please help?

**Comment by ktsaou** [comment]
@Homer-Sim keep in mind you can install a binary package at the host. This installs in /opt/netdata and does not require anything on the host: https://github.com/firehol/binary-packages

**Comment by Homer-Sim** [comment]
I followed your hint and installed it directly on the machine, it is now working but I can not see disk usage ??
If I am looking at sda no disk usage/available space si displayed ??

**Comment by ktsaou** [comment]
hm... are you sure? There should be a `/` submenu under disks.

`sda` is a disk. Normally your `/` is `sda1` (a partition of the disk). Netdata reports performance for the whole disk under `sda` and disk space usage for the mount points with their mount path, i.e.: `/`.

**Comment by Homer-Sim** [comment]
Now I identified what I am missing. On my server is a USB HDD attached and mounted in /docker/data/video. But this is not shown in netdata.

**Comment by ktsaou** [comment]
fetch `http://your.netdata.io:19999/netdata.conf` and search for `plugin:proc:diskspace`. Do you see `/docker/data/video`?

If yes, is it enabled or disabled?
(netdata will disable it if the mount point is read-only when it checks it - but you can enable it in the config to overwrite this decision).

**Comment by Homer-Sim** [comment]
This is the entry:

[plugin:proc:diskspace:/docker/data/video]
	# space usage = auto
	# inodes usage = auto

**Comment by ktsaou** [comment]
`auto` means: decide at run time.
uncomment it and set to `yes`.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
