### ISSUE TITLE
multiple network interface support

### ISSUE THREAD

**Issue by raedah** [firehol/netdata#224]
Question
1) Does this support the ability to control multiple network interfaces?
2) Does it support the ability to direct connections to a specified interface based on how that connection is classified? (wanted)

**Comment by ktsaou** [comment]
I guess you are talking about FireQOS.
If yes, the proper issues tracker is this: https://github.com/firehol/firehol/issues

The answers though are:

1. yes, any number you like
2. yes, of course

Check the FireQOS tutorial. It will give you a step by step guide on how to set it up: https://github.com/firehol/firehol/wiki/FireQOS-Tutorial

**Comment by raedah** [comment]
Thanks! Ill give it a try.
