### ISSUE TITLE
IPv4 System Overview

### ISSUE THREAD

**Issue by Defiance82** [firehol/netdata#2246]
I installed NetData on 3 servers. 2 of them show IPv4 data usage under the System Overview. However for some reason 1 server does not show it at all. If I click on Network Interfaces I can see the usage with no issues. It's just not added it to the System Overview.

**Comment by ktsaou** [comment]
Hi,

the system overview chart is provided by the kernel for both ipv4 and ipv6. It seems that your kernel does not expose it.

netdata reads [total ipv4](https://github.com/ktsaou/netdata/blob/718c8dacdf092e8fe081c5768b635c11fbf28252/src/proc_net_netstat.c#L239-L254) from `/proc/net/netstat`, row `IpExt`, columns `InOctets` and `OutOctets` and [total ipv6](https://github.com/ktsaou/netdata/blob/5b832c25c6a1ab29037b65d94f7c8865e2e653c3/src/proc_net_snmp6.c#L279-L294) from `/proc/net/snmp6`, rows `Ip6InOctets` and `Ip6OutOctets`.

If this information does not exists, or it is just zero, the charts are not created.

Which distro and kernel version you use?

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
