### ISSUE TITLE
`nv` plugin stuck at top

### ISSUE THREAD

**Issue by skwerlman** [firehol/netdata#2249]
I used to use the [nv](https://github.com/coraxx/netdata_nv_plugin) plugin on my personal box, and it worked great. After re-imaging a few months back and not reinstalling the plugin, I tried it today, but I can't get it to appear anywhere but at the very top of the UI (in place of the System Overview section), regardless of the priority I set for it (both in the plugin itself and it's conf).
![2017-05-28-102010_1802x865_scrot](https://cloud.githubusercontent.com/assets/6954107/26529520/44eae002-438f-11e7-938e-870cc084a7b4.png)

**Comment by ktsaou** [comment]
hm... if you fetch `http://your.netdata.ip:19999/api/v1/charts` what priority does it have?

**Comment by skwerlman** [comment]
The plugin itself has priority 145000, and each of its charts has priority 0

**Comment by ktsaou** [comment]
well, plugins do not have a priority. The priority you set at their source code, should be set to their charts.
If you set all the charts to the right priority, they will be moved down...

**Comment by skwerlman** [comment]
The "plugin priority" bit was me misreading the data. The 145000 is for the python.d timing stats. My bad.

The problem I'm having is that the priority I'm assigning in `nv.conf` is not being respected.

nv.conf:
```
update_every: 1
retries: 10
priority: 60000

legacy: False
nvMemFactor: 1
```

debug log:
https://gist.github.com/skwerlman/64e62267702a4acbc6676907e0525c68

Looking at the debug log, you can see priority being set to 60000 at line 47, but the charts being drawn with priority 0 starting at line 83.

**Comment by skwerlman** [comment]
The debug log shows the priority being set correctly (line 47), but the charts still have priority 0 in the api...
https://gist.github.com/skwerlman/64e62267702a4acbc6676907e0525c68

**Comment by ktsaou** [comment]
hm... @l2isbad any ideas?

**Comment by l2isbad** [comment]
@skwerlman 
try this:

https://github.com/coraxx/netdata_nv_plugin/blob/master/nv.chart.py#L249

to

```python
name = pynvml.nvmlDeviceGetName(handle).decode()
```

**Comment by l2isbad** [comment]
@coraxx
^

**Comment by skwerlman** [comment]
That fixed it! Thanks
