### ISSUE TITLE
Log messages from "apps.plugin"

### ISSUE THREAD

**Issue by FedericoCeratto** [firehol/netdata#225]
The apps plugin logs to syslog as "apps.plugin". It should log using a name that makes it clear that it belong to netdata, e.g. "netdata.apps.plugin"

**Comment by ktsaou** [comment]
thanks for reporting this!

apps.plugin should not log to syslog. I'll fix it.

**Comment by ktsaou** [comment]
this has been fixed.
Thanks!

**Comment by ktsaou** [comment]
I close it.
If something is missing let me know.
