### ISSUE TITLE
Unable to establish web Interface 

### ISSUE THREAD

**Issue by shkart** [firehol/netdata#2256]
Hi,
     I have netdata installed in arm target, i can see both netdata and apps.plugin processes are running. But we are unable to establish web interface. We are getting pagenot found error in chrome browser.

Arm target plaform IP is set to 128.0.0.x and loopback is 127.0.0.1 same as x86. Do we need modifcations to netdata source code to establish web interface, please suggest.

I am typing “128.0.0.x:19999” in browser URL field.

Test Setup: Arm target connected to laptop via ethernet cable, opening chrome browser in laptop with URL  “128.0.0.x:19999”, unable to see below screen in arm target. This URL link perfectly works with x86-linux.

**Comment by ktsaou** [comment]
ok,

Verify that netdata gets the request: check `/var/log/netdata/access.log` on your arm box.

If netdata does not log anything there, the request is not routed to it. From the arm box, run this `curl 'http://localhost:19999/'`. It should respond with an HTML file and access.log should log it.

So, first try to route the request to it. Then we will check if there are more issues.

**Comment by shkart** [comment]
I have redirected the log to /var/log/netdata/access.log, I have disconnected the wifi now (earlier it was connected). Now I tried to access in chrome browser with 'http://localhost:19999/', chrome throws "Access to file '' is not permitted." I have given the permission (chmod 777 ) in my arm box still unable to access.

**Comment by ktsaou** [comment]
ok, but did `/var/log/netdata/access.log` show the atempt to access netdata?

**Comment by ktsaou** [comment]
let's do this:

Can you ssh from your laptop to the arm box? Using which IP?

**Comment by shkart** [comment]
Hi,
    Yes i could see some data in the access.log(have attached in mail), Yes
i can ssh to arm box, using 128.0.0.107.

Thanks,
Karthik

**Comment by shkart** [comment]
I have attached both error.txt (error.log) and access.txt  (access.log).

[error.txt](https://github.com/firehol/netdata/files/1044548/error.txt)
[access.txt](https://github.com/firehol/netdata/files/1044549/access.txt)

netdata is running as user "nobody" on target. In x86 "netdata" run as user "netdata". It should netdata user in the target as well.

**Comment by ktsaou** [comment]
ok, you have several problems:

1. netdata on your system runs as user `nobody`. If this is not what you want, you need to add user and group `netdata` to your system. netdata logs the user it runs, as the first line of the log:

```
17-05-22 18:35:32: INFO (0312@../../git/:become_daemon  ): netdata: Successfully became user 'nobody'.
```

2. netdata has a security mechanism inside it, checking the user and group web files should be owned. By default these are the user netdata is running as. You have to chown all files at `/usr/share/netdata/web` to this user and group. If you want the files to be owned by another user, edit netdata.conf at the `[web]` section.

This is shown by the response code `403` in `access.log`.

3. The user netdata runs as needs to have write access to `/var/cache/netdata` and `/var/lib/netdata`. If this embedded system does not have a disk (or you don't want netdata to use files for the metrics) set `memory mode = ram` in `netdata.conf`.

4. The user netdata runs as needs to have read access to `/etc/netdata.

5. Your netdata is veeeeeeeeeeeeeeeeeeeeery old. Please use a more recent copy of it.

**Comment by shkart** [comment]
Hi,
    I modified fields as "run as user = root" & "web files owner = root" in netdata.conf file it worked. I was able to access web interface of the netdata from arm target. Now i could see the netdata is running as user root. Thank you very much for the help.

**Comment by ktsaou** [comment]
ok, nice!
