### ISSUE TITLE
Choose which metrics are sent to backend

### ISSUE THREAD

**Issue by colomb001** [firehol/netdata#2257]
We've got netdata setup on a couple of servers streaming data to influxdb for historical purposes. We are only interested in a handful of metrics historically and are concerned that as we add more netdata servers, the influxdb size will increase too quickly. Is there a way to specify what metrics are sent to the backend?

**Comment by ktsaou** [comment]
Hi,

I certainly can add this feature to netdata. But I thought it would be better to push all metrics to the backend database at lower rate, e.g. once every 10, 30 or 60 seconds and control the retention policy at the backends.

So, as we are today:

- netdata controls the rate metrics are pushed to backends.
- backends control the retention policy required for each metric.

Are you sure you want to filter metrics sent to backends?
You will be first requesting this feature...

**Comment by colomb001** [comment]
Hmmm, that all makes sense.

To put this somewhat into perspective, I'm using grafana as a front end. When creating a dashboard and adding graphs, the sheer number of datasources to choose from is overwhelming.

This is my first exposure to influxdb and time series databases in general. I'll spend some more time working with it to see if maybe I can set rules to ignore incoming data series or use retention policies to  drop them as they come in.

Table the request for now. Thanks for the speedy response!

**Comment by ktsaou** [comment]
ok. I am closing this for now.
If you need help, or you finally need it, just post here.

**Comment by jpriebe** [comment]
I can see the value of this request.  I'm experimenting with an InfluxDB backend.  I'm sending just one host's data to InfluxDB, and that's over 850 metrics!  If I spent some time looking through them, I'm sure I really only need about 50 of them for long-term analysis.  Filtering the metrics sent to InfluxDB would help me in a lot of ways:

- reduce the data handling of InfluxDB (currently at 140KB every 10s for 1 host; if I had 50 hosts, that is 700KB per second, which seems like a pretty big deal on a modest cloud computing instance)
- reduce the complexity of the retention policies I would need to define; right now, I'm able to use just 5 policies and corresponding continuous queries to downsample my data by using wildcards; if I were to retain each metric (or group of metrics) separately, it might take me 100 or more policies.   This, of course, is somewhat of an InfluxDB-specific problem.

**Comment by ktsaou** [comment]
ok, added it.
Check PR #2294

**Comment by ktsaou** [comment]
A new setting has been added under the `[backends]` section: `send charts matching = *`. One or more space separated patterns can be given, using `*` as wildcard (any number of times within each pattern). A pattern starting with `!` gives a negative match. So to match all charts named `apps.*` except charts ending in `*reads`, use `send charts matching = !*reads apps.*`.

Can you test it?

**Comment by ktsaou** [comment]
You have to install `https://github.com/ktsaou/netdata.git`. Just like the official one.

**Comment by ktsaou** [comment]
I verified it works.

**Comment by ktsaou** [comment]
merged it.

**Comment by jpriebe** [comment]
I tested earlier, and PR #2294 hadn't gone through yet.  I just re-rean the test, and it worked for me with some simple tests like

```
send charts matching = system.forks
```

and

```
send charts matching = system.*
```

**Comment by zhangxin0112** [comment]
I have 200+hosts . I am looking for this feature . It is very useful.
