### ISSUE TITLE
First dimension of synthetic statsd chart get divider 1000

### ISSUE THREAD

**Issue by VDigitall** [firehol/netdata#2260]
Hi,
I have new problem with synthetic statsd chart.
If create synthetic chart with dimensions gauge metrics, and send to netdata metrics one by one, then first dimension receive divider 1000 and other all receive divider 1 but on private charts all metrics displays fine.
my `/etc/netdata/statsd.d/metric.conf`
```
[app]
        name = metric
        metrics = *
        private charts = yes
        gaps when not collected = no
        memory mode = ram
        history = 6000

[my_metric]
        name = Test metric
        title = Test metric
        family = Test metric
        context = metric.my_metric
        units = items
        priority = 91000
        type = line
        dimension = metric1 m1 last 1 1
        dimension = metric2 m2 last 1 1
        dimension = metric3 m3 last 1 1
        dimension = metric4 m4 last 1 1
```
my `http://localhost:1999/netdata.conf`
```
[metric.my_metric]
	# history = 6000
	# enabled = yes
	# cache directory = /var/cache/netdata/metric.my_metric
	# chart type = line
	# type = metric
	# family = Test metric
	# units = items
	# context = metric.my_metric
	# priority = 91000
	# gap when lost iterations above = 1
	# name = metric.Test_metric
	# title = Test metric (metric.Test_metric)
	# dim m1 name = m1
	# dim m1 algorithm = absolute
	# dim m1 multiplier = 1
	# dim m1 divisor = 1
	# dim m2 name = m2
	# dim m2 algorithm = absolute
	# dim m2 multiplier = 1
	# dim m2 divisor = 1
	# dim m3 name = m3
	# dim m3 algorithm = absolute
	# dim m3 multiplier = 1
	# dim m3 divisor = 1
	# dim m4 name = m4
	# dim m4 algorithm = absolute
	# dim m4 multiplier = 1
	# dim m4 divisor = 1000
```
![private_charts_metric](https://cloud.githubusercontent.com/assets/6977678/26622519/5da12d16-45f3-11e7-81e5-13f4ee772872.png)
![synthetic_chart_metric](https://cloud.githubusercontent.com/assets/6977678/26622526/632c41c6-45f3-11e7-9c2b-ef54b90764ab.png)
For reproduction I put my `metric.conf` to `/etc/netdata/statsd.d/` and restart `netdata` then use four shell tabs and start one by one next commands:
`watch --interval=1 "echo \"metric4:19.023|g\" | nc localhost 8125"`
`watch --interval=1 "echo \"metric3:16.023|g\" | nc localhost 8125"`
`watch --interval=1 "echo \"metric1:12.023|g\" | nc localhost 8125"`
`watch --interval=1 "echo \"metric2:11.023|g\" | nc localhost 8125"`

**Comment by ktsaou** [comment]
yes, you are right. This is a bug.
The reason is exactly the same with #2253 . Actually I had added the fix there and later removed (what was I thinking?)

Fixed in #2261 

Thank you for reporting it.

**Comment by ktsaou** [comment]
merged it.

**Comment by VDigitall** [comment]
Hi, in last build again apper this issue, but this time first dimension get divider 100 and display valid value and other dimesion get divider 1 and multiplier 1 but display wrong value like has multiplier 1000000. 
For reproduction I put my `metric.conf `to `/etc/netdata/statsd.d/` and restart netdata then use four shell tabs and start one by one next commands:

```
watch --interval=1 "echo \"metric4:19.023|g\" | nc localhost 8125"
watch --interval=1 "echo \"metric3:16.023|g\" | nc localhost 8125"
watch --interval=1 "echo \"metric1:12.023|g\" | nc localhost 8125"
watch --interval=1 "echo \"metric2:11.023|g\" | nc localhost 8125"
```

**Comment by ktsaou** [comment]
You are right.
A typo - wrong copy-paste.
Fixed it. Will merge in a while.

**Comment by ktsaou** [comment]
merged it!
Thank you for reporting this (and sorry for the back and forths)...
