### ISSUE TITLE
Disk sorting is ASCII instead of human-numeric order.

### ISSUE THREAD

**Issue by gdevenyi** [firehol/netdata#2263]
If I have a collection of dm-* disks like dm-1 to dm-12, currently there are sorted in the web interface with
dm-1
dm-10
dm-11
dm-12
dm-2

These should be sorted in human-numeric order.

**Comment by Ferroin** [comment]
Same goes for CPU utilization (cpu0, cpu1, cpu10, cpu11, etc), as well as some other stuff too (I don't remember what off the top of my head).

**Comment by ktsaou** [comment]
You are right. I need to find a way to do the right sorting in javascript...

**Comment by Ferroin** [comment]
Well, the simple method is to first group strings by length, sort each group normally, then order the groups by increasing length.  That's how most stuff I know of ends up implementing this type of thing internally.

The odd thing is that there are some things that _are_ sorted correctly (for example, the per-CPU interrupt charts).

**Comment by gdevenyi** [comment]
https://stackoverflow.com/questions/2802341/javascript-natural-sort-of-alphanumerical-strings

**Comment by ktsaou** [comment]
fix is in PR #2281 
I will merge it tomorrow. If you can test it, please do so...

**Comment by Ferroin** [comment]
#2281 appears to be working correctly here.

**Comment by ktsaou** [comment]
nice! thanks!
I just pushed a few more changes (not related this issue - performance optimizations). If you can update it and test it again it would be great...

**Comment by Ferroin** [comment]
Everything still looks good, although I unfortunately don't have the tooling required to properly test that the performance improved.

**Comment by ktsaou** [comment]
ok thanks! Chrome can monitor the performance (hit F12, switch to performance tab, reload the page).

The improvement is clearly visible when you switch 2 netdata servers from the the `my-netdata` menu. Switch between 2 servers with the PR installed and do the same without the PR. Hit Control-F5 first on each server to fetch the latest files. From 2+ seconds to start rendering charts, we are now below 1 second. This is even more visible if your personal computer is not that powerful.

The whole idea for this improvement is to allow netdata load pages with thousands of charts (now it loads a few hundreds - but loading dashboard performance was terrible above 1k charts). Now it is a lot better.

**Comment by Ferroin** [comment]
Huh, I actually never knew there was a page profiler in Chrome...

Checking between the current version in the PR and the version I had installed (1.6.0 via the Gentoo ebuild), I do in fact see a small performance improvement, although I wouldn't expect it to be much considering that none of the systems I'm using netdata on have more than about 200 charts.

**Comment by ktsaou** [comment]
merged it...
