### ISSUE TITLE
Custom plugin to create graph from multiple commands

### ISSUE THREAD

**Issue by adamckay** [firehol/netdata#2265]
Hi,

Really loving netdata and I'm writing a custom Python plugin to query the number of items in a [celery](http://www.celeryproject.org/) queue  that's using Redis as a broker. Celery has a built in way to query the number of tasks currently active and I've created a plugin successfully, however the celery command is quite slow (~ 3 seconds during usage) so I'm going to modify it so it queries the length of a redis key (`redis-cli llen queue_name`).

I've hit a problem because I can only get the length of a single key at once and I'm not able to use `&` to chain commands together - I've currently set a variable containing the list of queue names and am iterating over it to set the command and get raw data, however when running in debug mode it complains that the command is unsuccessful and returns `None`. Switching to the netdata user (`su -s /bin/bash netdata`) can run the redis-cli command successfully so I'm a bit stuck.

I just want to check if I'm approaching this from the right angle or if you could offer any better advice to achieve this?

Thanks

**Comment by l2isbad** [comment]
```python
# -*- coding: utf-8 -*-
# Description: exim netdata python.d module
# Author: Pawel Krupa (paulfantom)

from base import ExecutableService
from random import randint

# default module values (can be overridden per job in `config`)
# update_every = 2
priority = 60000
retries = 60

# charts order (can be overridden if you want less charts, or different order)
ORDER = ['commands']

CHARTS = {
    'commands': {
        'options': [None, "Commands", "commands", 'commands', 'commands.commands', 'stacked'],
        'lines': [
        ]}
}

COMMAND_OPTS = [5] * 5


class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS

    def check(self):
        data = self._get_data()
        if not data:
            return False
        for key in data:
            self.definitions['commands']['lines'].append([key, key, 'absolute'])
        return True

    def _get_data(self):
        """
        Format data received from shell command
        :return: dict
        """
        self.data = dict()
        for opts in enumerate(COMMAND_OPTS, 1):
            num, opt = opts[0], opts[1]
            self.command = ['echo', str(opt)]
            raw_data = self._get_raw_data()
            if raw_data:
                self.data['data_%s' % num] = mapper(raw_data)
        return self.data or None


def mapper(data):
    return int(data[0].strip()) * randint(3, 8)

```
![screenshot_20170601_155046](https://cloud.githubusercontent.com/assets/22274335/26667844/18ee8d04-46e2-11e7-8e5f-1944bab71391.png)

**Comment by adamckay** [comment]
Perfect, thank you! 😃
