### ISSUE TITLE
when running the netdata-updater.sh

### ISSUE THREAD

**Issue by samueletacchini** [firehol/netdata#2267]
as ia run the updater it tells me that i have to run it as a user with $UID == 0 even if i am  as root ($UID == 0) 
(fixed by bypassing the check in the sh: if [ "${INSTALL_UID}" != "${UID}" ] => if [ "${INSTALL_UID}" == "${UID}" ]

(after the successful update the sh fixed himself)

**Comment by ktsaou** [comment]
hm... Can you reproduce it?
If you can, please post the generated `netdata-updater.sh` here.

**Comment by samueletacchini** [comment]
[netdata-updater.zip](https://github.com/firehol/netdata/files/1044234/netdata-updater.zip)
 here is the code
after updating in the web page a lot of graphs (that were shown before) are not..

**Comment by ktsaou** [comment]
wait a moment... a problem at a time.

I don't see any issue at the script you sent. I understand the script you sent is the one that was overwritten and is now correct. So, if you run it now it says "no updated available".

The script I need is the one that reports `This script should be run as user with uid 0 but it now runs with uid ???`.

So, can you reproduce the problem somehow?

regarding the missing graphs, can you identify one chart missing?

**Comment by samueletacchini** [comment]
(just rebooted and the graphs are now showing)
and yes sorry 
![bug](https://cloud.githubusercontent.com/assets/24253468/26673824/8981f5ca-46be-11e7-943b-d7261d7e396c.PNG)
 it's showing this..

**Comment by ktsaou** [comment]
This is interesting.

Is your `sh` bash or something else?

If you run it directly `./netdata-updater.sh` does it run?

If you run  `echo "${UID}"` like the script does, does it still print ` 0 `?

**Comment by ktsaou** [comment]
For the missing charts, I need you to identify 1 chart missing.

**Comment by samueletacchini** [comment]
now every single chart is showing, but before the reboot it was only showing the "load" one and the system runtime one.

**Comment by samueletacchini** [comment]
I honestly don't think it's my bash i never changed anything and just updated the system
![bug2](https://cloud.githubusercontent.com/assets/24253468/26674385/97c30866-46c0-11e7-8d54-0d9fc2f262be.PNG)
 this is showing running those commands..

**Comment by venkatesh6114** [comment]
@ktsaou The above issue is thrown when we run as "sh netdata-updater.sh", that's what @samueletacchini mentioning.

**Comment by ktsaou** [comment]
Yes, but what should we do if it is null. It should never be null, or if it is null should somehow find a way to get the current uid...

**Comment by ktsaou** [comment]
I see there is `$EUID` too. Can we check if this is not null when `$UID` is null?

**Comment by ktsaou** [comment]
We change it to:

```sh
if [ "${INSTALL_UID}" != "${UID}" -o "${INSTALL_UID}" != "${EUID}" ]
then
```

Can you test if it works in this case?

**Comment by ktsaou** [comment]
updated it (get it from github)

**Comment by samueletacchini** [comment]
echo $EUID is printing 0..
Found out that echo $uid is printing nothing (null)

**Comment by samueletacchini** [comment]
updated it and still printing the same
![bug 3](https://cloud.githubusercontent.com/assets/24253468/26676705/2d739b02-46c9-11e7-880c-130d0e276013.PNG)

**Comment by venkatesh6114** [comment]
@ktsaou , When $UID is NULL, $EUID is also NULL. So it won't work it seems.

**Comment by samueletacchini** [comment]
maybe there is a case sensitive/insensitive problem so it is actually checking for $uid >(that is null) and not for $UID that is 0

**Comment by ktsaou** [comment]
Is there a command to call to find the UID?

**Comment by venkatesh6114** [comment]
Just give a look at this https://stackoverflow.com/questions/39445968/bash-getting-uid-on-shell-script-does-not-work

**Comment by samueletacchini** [comment]
i think it's a system variable so just print it (echo) should be fine right?

**Comment by ktsaou** [comment]
@venkatesh6114 can you check `$(id -u)` ?

**Comment by samueletacchini** [comment]
still 0

**Comment by ktsaou** [comment]
> i think it's a system variable so just print it (echo) should be fine right?

yes, but when it runs with `sh` is prints nothing...

**Comment by venkatesh6114** [comment]
@ktsaou $(id -u) is working. It outputs **0**. So no issues.

**Comment by ktsaou** [comment]
ok, thanks!
fix in PR #2270 . Will merge in a while.

**Comment by samueletacchini** [comment]
:) thank you!!

**Comment by ktsaou** [comment]
merged it.
