### ISSUE TITLE
Default install does not show systemd services charts

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2269]
I have 2 installs of netdata on 2 ARM Debian Jessie systems which are largely similar. When viewing the default dashboard, I noticed that one of the installs shows `systemd services` metrics. Specific commit hash:

* 2591ab7: shows `systemd services`
* 7771771: (latest as of today) doesn't show `systemd services`.

[Difference in terms of commits](https://github.com/firehol/netdata/compare/2591ab72c4ec291d7c3a1eb7766a5acc25408e3e...77717713335be9882883066b4b7b8425c6d41320).

In both cases, `netdata.conf` is set to  `# enable systemd services = yes`.

Would be grateful if anyone can help debug this

Update: these are default installs of netdata

**Comment by ktsaou** [comment]
Hi, it is a systemd issue. You can enable it by changing a few systemd settings.
Check this: https://github.com/firehol/netdata/wiki/monitoring-systemd-services

**Comment by elfgoh** [comment]
@ktsaou For additional clarity, these are default netdata installs. I am happy to try the recommendations in the wiki page at the next opportunity. But I wanted to understand the differences in behaviour. Did I somehow get lucky with one of the installs?

**Comment by ktsaou** [comment]
Well... check the contents of `/etc/systemd/system.conf`.

If they are the same on both systems, then the 2 systems should be running different versions of `systemd`, or something else has triggered systemd to change its default behaviour.

If they are not the same, someone (or something - not netdata), has changed one of the files. Probably another application you installed on one of the two systems.

**Comment by elfgoh** [comment]
Ok got it. Thanks! Will feedback here

**Comment by elfgoh** [comment]
I have verified that the the following were not the cause:

* `/etc/systemd/system.conf`
* systemd versions

Seems that something else is causing the change. Nevertheless the wiki instructions were sufficient to get the systemd metrics being loaded. It did however require a reboot to take effect. Is this expected?

**Comment by ktsaou** [comment]
> It did however require a reboot to take effect. Is this expected?

No restart is needed, but you need to (as the wiki says):

1. run `systemctl daemon-reexec`
2. if it doesn't show at `systemd-cgtop`, restart a service - any service - to wake it up

**Comment by elfgoh** [comment]
I confirm that the documentation is correct and I had misunderstood it

**Comment by WeebHiroyuki** [comment]
Hello. I can reproduce this issue but I can't seem to fix it. https://github.com/firehol/netdata/wiki/monitoring-systemd-services redirects me to the main wiki page. Can someone help please?

**Comment by vlvkobal** [comment]
Please look at https://learn.netdata.cloud/docs/agent/collectors/cgroups.plugin#monitoring-systemd-services
