### ISSUE TITLE
RAM usage warnings should consider ZFS ARC size

### ISSUE THREAD

**Issue by gdevenyi** [firehol/netdata#2271]
For storage systems based on ZFS, the ARC is typically fixed sized of RAM such that total RAM usage can be very close to 100%

This results in the RAM usage warning triggering constantly.

It would be beneficial if the RAM check could account for ZFS ARC usage.

**Comment by ktsaou** [comment]
I see the `ram.conf` alarm is this:

```
   alarm: ram_in_use
      on: system.ram
    calc: $used * 100 / ($used + $cached + $free)
   units: %
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: down 15m multiplier 1.5 max 1h
    info: system RAM usage
      to: sysadmin
```

I guess we should make it like this:

```
    calc: ($used - $zfs.arc_size.arcsz) * 100 / ($used + $cached + $free)
```

Then the problem is that on non-zfs systems, `$zfs.arc_size.arcsz` will be `nan`.

I think we can use this:

```
    calc: ($used - (($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz))) * 100 / ($used + $cached + $free)
```

Can you make this change to verify it works? If it works, I'll merge it...

**Comment by gdevenyi** [comment]
Looks like this change worked, memory alarm is no longer trigger on my storage arrays.

**Comment by ktsaou** [comment]
ok nice. Could you please verify the badge at the alarms modal on the dashboard, shows the right percentage used?

Also, is this alarm useful now? I mean, will the alarm ever trigger? Is there a minimum arc size that we should never consider "free memory"?

In other words, you as a sysadmin of a ZFS system, when would you like to be alarmed regarding memory issues? Does the change satisfy you?

**Comment by gdevenyi** [comment]
I think this is close, but instead the ARC should be ignored on both ends:
```
 calc: ($used - (($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz))) * 100 / ($used + $cached + $free -  (($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz)))
```

**Comment by ktsaou** [comment]
hm... try it, but I think it will be triggered again for no reason, since arc can use all the available memory...

**Comment by gdevenyi** [comment]
This works fine. The math above treats "available" memory as memory not used by the ARC.

So if my ARC is 75% of my system memory, netdata only shows the usage of the remaining 30%

**Comment by ktsaou** [comment]
PR #2375 
I chose to create a separate alarm to measure the memory to be excluded from the alarm. This allows possible other similar cases to be added to the exclusion list and also provides a nice badge about the amount of memory excluded.

**Comment by gdevenyi** [comment]
That looks fine with me. Thanks.

**Comment by xfakt-pj** [comment]
I am still getting 'low ram' warnings even though I have this config file (the default config)

```
  alarm: used_ram_to_ignore
      on: system.ram
    calc: ($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz)
   every: 10s
    info: the amount of memory that is reported as used, but it is actually capable for resizing itself based on the system needs (eg. ZFS ARC)

   alarm: ram_in_use
      on: system.ram
#   calc: $used * 100 / ($used + $cached + $free)
    calc: ($used - $used_ram_to_ignore) * 100 / ($used - $used_ram_to_ignore + $cached + $free)
   units: %
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: down 15m multiplier 1.5 max 1h
    info: system RAM usage
      to: sysadmin
```

Am I doing something wrong? My ARC is about 10GB large, I have 24GB RAM, yet netdata reports 93% in use.

**Comment by ktsaou** [comment]
Could you please post this:

![screenshot from 2017-07-05 23-14-36](https://user-images.githubusercontent.com/2662304/27883032-c5c27ff8-61d7-11e7-9553-e2d33a166169.png)

It shows if it matches the 10GB ARC.

Then please also post this:

![screenshot from 2017-07-05 23-16-25](https://user-images.githubusercontent.com/2662304/27883096-ff64e656-61d7-11e7-8823-7b4851c3f13a.png)

It shows the amount of RAM used on your system.

**Comment by xfakt-pj** [comment]
![A](https://user-images.githubusercontent.com/24892191/27905331-edcbb074-623f-11e7-81c1-bb2116fc70ba.png)

![B](https://user-images.githubusercontent.com/24892191/27905336-f0cf222e-623f-11e7-83d8-093d50481827.png)

To me this looks like it recognizes the ARC, but fails to respect it in the graph and the alarms.

**Comment by ktsaou** [comment]
Could you please post the legend of the last chart. We need to make the calculation by hand to understand if it really failed to respect it in the alarms.

**Comment by xfakt-pj** [comment]
My bad!

![B2](https://user-images.githubusercontent.com/24892191/27906256-16c24710-6243-11e7-8c25-e9ce7918471a.png)

**Comment by xfakt-pj** [comment]
This might also be relevant:

![C](https://user-images.githubusercontent.com/24892191/27910021-924ce40c-6253-11e7-85a4-c36eb601845c.png)

**Comment by ktsaou** [comment]
no problem. So:

24000 MB `total`
22949 MB `used`
10670 MB ARC `used_ram_to_ignore`
53 `cached`
1089 `free`

The equation is `(used - used_ram_to_ignore) * 100 / (used - used_ram_to_ignore + cached + free)`

So : `(22949 - 10670) * 100 / (22949 - 10670 + 53 + 1089) = 91.49 %`

It works as expected, but still there is a problem: **ARC is supposed to automatically scale down**, so it should be considered `free`.

So the right equation should be: `(used - used_ram_to_ignore) * 100 / (used + cached + free)`, which resolves to `(22949 - 10670) * 100 / (22949 + 53 + 1089) = 50.97 %`

@gdevenyi this was your suggestion. My understanding is that we should not subtract `used_ram_to_ignore` from both ends. What do you think?

**Comment by xfakt-pj** [comment]
50% corresponds with the amount ram being used on my host by everything except ARC. So the equation seems right to me. A second opinion would be wise though ;)

**Comment by gdevenyi** [comment]
@ktsaou ZFS arc is pretty awful at "automatically scaling down", on top of that, ZFS systems typically fix the ARC size to dedicate a fix block of ram to the ARC, making it unavailable to the rest of the system.

**Comment by xfakt-pj** [comment]
Somewhat related: I am using zfsonlinux on a Proxmox host, and proxmox limits the ARC size to 50% of ram by default: https://pve.proxmox.com/wiki/ZFS_on_Linux

**Comment by ktsaou** [comment]
So, leave it as is or change it?

If ARC does not scale down automatically, we should not change the equation. The alarm you get @xfakt-pj is valid.

If however ARC does scale down automatically, we should remove it from the divider.

**Comment by xfakt-pj** [comment]
Personally: I am really not sure, I entered this conversation assuming that ARC always scales down when requested but this seems indeed not to be the case in every situation. 

I don't have a solid answer, maybe @gdevenyi does.

**Comment by gdevenyi** [comment]
So, ZFS on linux has the "ability" to scale the ARC, however its not well tested and in general doesn't work well. As a result, most ZFS installs fix the ARC size so that it has bounded properties (either the OS sets defaults or the administrator does)

**Comment by ktsaou** [comment]
> So, ZFS on linux has the "ability" to scale the ARC, however its not well tested and in general doesn't work well. As a result, most ZFS installs fix the ARC size so that it has bounded properties (either the OS sets defaults or the administrator does)

So, the alarm is good as it is today.

**Comment by xfakt-pj** [comment]
It seems so, this discussion also triggered me to rethink my zfs strategy ;)

Met vriendelijke groet,

Peter-Jan Pinxteren


[image: Xfakt-logo]

Peter-Jan Pinxteren
E-mail: peterjan@xfakt.nl
Website: www.xfakt.nl

Telefoon: 030-8200256

*Postadres*
Postbus 1500
4700 BM Roosendaal
Nederland
*Bezoekadres*
Gastelseweg 142
4705 RB Roosendaal
Nederland
