### ISSUE TITLE
web_log: allow filtering with regex

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2278]
@l2isbad first I want to say "THANK YOU" for the marvelous work you have done with the web_log plugin. This is wonderful, awesome! It is ubelievably helpful to have this visibility in real-time.

I have installed in on several apache, nginx and squid acting as perimeter application firewalls and it really helps to pinpoint all kinds of issues.

I have 1 more request:

web/proxy logs often have different kinds/groups of requests in them. I need to somehow have "virtual logs". That is to provide the whole set of charts but for requests matching a regex.

An easy way to do it, is to add a `filter` regex configuration option. So, we could add the same log file many times, with different filters. 

The above will waste a few resources, since the log parsing will be done multiple times. Although this is not ideal, it is an acceptable solution. Of course if you can find another more efficient solution, please use that.

In other cases, we need the whole log except a few of the requests. a single regex can do this, but I guess that if someone needs 10 positive and 3 negative matches, the regex will be quite complex. Possibly an `exclude` regex can make thinkgs simpler for the admin (so, first match `filter` and then make sure `exclude` does not match).

Your call. You know better...

**Comment by l2isbad** [comment]
@ktsaou 

```yaml
filter:
  include: 'regex'  # optional
  exclude: 'regex'  # optional
```

?
