### ISSUE TITLE
Openstack with NetData

### ISSUE THREAD

**Issue by kholisrag** [firehol/netdata#2289]
I want to install netdata with openstack in one node,
the netdata installation is success,
but when I access the netdata with the port, it's cannot connect
I think it's because the iptables, so I configure the iptables like this:

```
iptables -A INPUT -p tcp --dports 19999 -m multiports  -j ACCEPT
iptables -A INPUT -p udp --dports 19999 -m multiports -j ACCEPT
iptables -A OUTPUT -p tcp --sports 19999 -m multiports -j ACCEPT
iptables -A OUTPUT -p udp --sports 19999 -m multiports -j ACCEPT
```
I try to restart iptables service, it's didn't work
I try to restart the PC but it's also didn't work

anyone can help?

**Comment by ktsaou** [comment]
I suggest to use these commands:

```sh
iptables -I INPUT -p tcp --dport 19999 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -I OUTPUT -p tcp --sport 19999 -m conntrack --ctstate ESTABLISHED -j ACCEPT
```

You can use the same with IPv6 if you replace `iptables` with `ip6tables`.

**Comment by ktsaou** [comment]
The key difference with your rules is that:

1. the rules you tried are appended to the firewall. If however the firewall explicitly drops all traffic at its end, the appended rules will never match anything.

2. the rules I suggested use the connection tracker of the kernel to make sure that port 19999 can only be used for a server running on the localhost (somewhat more secure).

**Comment by kholisrag** [comment]
Thanks... it's worked...

**Comment by bravechou2009** [comment]
**

- [ ] 

**
