### ISSUE TITLE
backend authentication

### ISSUE THREAD

**Issue by luca-moser** [firehol/netdata#2303]
I am reading https://github.com/firehol/netdata/wiki/netdata-backends but im not finding any way to let netdata authenticate against an influxdb instance. Is this feature even implemented?

**Comment by ktsaou** [comment]
Hi,

netdata implements the graphite and opentsdb plaintext protocols. Both of these protocols do not support authentication.

So, unfortunately no, netdata cannot authenticate to its backends.

**Comment by luca-moser** [comment]
Ok, thanks for the quick response :)
