### ISSUE TITLE
centralized netdata and unique opentsdb tags per host

### ISSUE THREAD

**Issue by jpriebe** [firehol/netdata#2304]
I'm trying to build a centralized netdata server that is receiving updates from 30-40 headless collector netdata instances.  I want it to write out to InfluxDB via the opentsdb interface, and I want it to add tags to that data.  The tags would reflect tags we use in our AWS environment, like "InstanceClass" or "Name".

Since the tags are defined in [backend] in netdata.conf, I don't see how the data from different hosts could be tagged differently.  I suspect that this is not possible (since the netdata child nodes probably aren't passing tags to the master).

Maybe the answer is to go straight to InfluxDB from the child nodes.  But I would really like to have a live netdata dashboard with all my nodes.  And I'd like to take advantage of netdata's handling of ephemeral nodes, which would be a huge benefit.

**Comment by ktsaou** [comment]
hm... yes you are right.

Are you sending the metrics `as collected`? If yes, the headless collectors can push these metrics to opentsdb themselves, bypassing the central netdata. This allows you to set opentsdb host tags at the collectors.

If you are sending the metrics `average`, `sum`, or `volume`, netdata has to be extended to support per host opentsdb host tags at the master.

**Comment by ktsaou** [comment]
hm... you answered it already. You want to use the master for handling ephemeral nodes.
ok. This needs some work...

**Comment by ktsaou** [comment]
What I can do, is to allow us set opentsdb host tags at `stream.conf`.
You will be able to do it per `[API_KEY]` and `[MACHINE_ID]`.

Another way, would be the slave to send it to the master. This will allow the setting to be propagated to all upstream netdata servers, but you will not be able to override it at a master.

Which one do you prefer?

1. set it at the master sending the metrics to opentsdb?, or 
2. set it at each slave and automatically inherited by the masters?

Generally, since this is opentsdb specific, I would prefer to only configure it at the hosts directly communicating with opentsdb (option 1 above). This means: cleaner netdata streaming protocol, one point to control all the opentsdb interaction, more flexibility, since multiple netdata masters sending metrics to multiple opentsdb servers, could have different host tags for each netdata host.

What do you think?

**Comment by jpriebe** [comment]
IIUC, option 1 would require that the centralized server have a priori knowledge of the hosts it will be collecting, so that it could have the tags pre-configured.

I think option 2 fits better for ephemeral hosts, where they come and go, and as long as the individual hosts are configured properly, they will have the appropriate tags on their metrics.

Tagged metrics seems to be an important category of time series dbs, so it may be worth making a change to the netdata protocol to accommodate it.  

Perhaps you could make the changes very minimal, like the client sends a single message with all the tags that should be appended to every metric originating from that client.  The master could then just keep a lookup table of host-to-tags and append the tags as the metrics come in.  Of course, it would have to deal with hosts coming and going in the case of ephemeral hosts.  Just an idea...

**Comment by ktsaou** [comment]
hm... ok. 

So you say that ephemeral hosts are able to know their uniqueness? I thought all of them were just replicas, without anything unique on them - even their IP is dynamic.

Out of curiosity, how is this done on AWS?

**Comment by jpriebe** [comment]
Yes, the ephemeral hosts do have some information about their uniqueness (as well as what "type" of host they are).  Some of this is intrinsic to AWS, and some of it is in the way you make use of the instance tagging facility.

Each instance has an instance ID, like "i-07083a1e4897366c9".  Instances also have tags that you can use for any key/value data you like.

When the instance is started, you can run a "userdata" script, where you can perform some configuration.  So we use a script to write that ID into the netdata configuration for tagging purposes.

We also like to specify an "instance class" (this is our convention, not necessarily part of AWS).  So if we have an auto-scaling group of web servers, we'll define a launch configuration for the instances in that group.  That launch configuration includes the userdata script, which we can use to set a tag of "InstanceClass=Web Server".  And again, we'll put that into the netdata config.

So all the new data from these ephemeral hosts has an instance class that lets us do things like query InfluxDB for metrics from all web servers, and then we can use the instance IDs to distinguish them.

**Comment by ktsaou** [comment]
ok, nice! thank you!
I will follow your suggestion and implement No 2.

**Comment by ktsaou** [comment]
Initial support for mirroring host tags added.
Not tested yet.
PR #2354

**Comment by ktsaou** [comment]
tested it - it works

**Comment by ktsaou** [comment]
merged it.
