### ISSUE TITLE
kickstart.sh script without prompts

### ISSUE THREAD

**Issue by alex-phillips** [firehol/netdata#2305]
Is there a way to run the kickstart.sh scripts without prompts? i.e., confirmation, auto-add `-y` to apt-get install commands, etc. I'd like to automate this where simply running the bash/curl "one-liner" is all that is required.

**Comment by ktsaou** [comment]
hm... the underlying scripts can do it, so I need to add an option to kickstart.sh to pass it through the others.

**Comment by ktsaou** [comment]
ok, here it is. Can you test it?

```
bash <(curl -Ss https://raw.githubusercontent.com/ktsaou/netdata/master/kickstart.sh) --dont-wait
```

Keep in mind the non-interactive mode of the packages installer depends on the package manager.
If your package manager still requires user input, please give me the exact command that enables non-interactive mode and it and I'll add it.

**Comment by fabMrc** [comment]
Not available on kickstart-static64.sh

**Comment by ktsaou** [comment]
ok, here it is.

I also made a PR to makeself ( megastep/makeself#100 ) with the changes required to it, to support this feature. This PR, with the updated makeself is now included in netdata.

**Comment by fabMrc** [comment]
thanks it works
