### ISSUE TITLE
Monitor processes in host from container

### ISSUE THREAD

**Issue by ghost** [firehol/netdata#2307]
Hi,

I'm working on a Ubuntu 14.04 with CUDA 8.0 in a nvidia-docker. I've successfully installed netdata and a nv monitor plugin:
[https://github.com/coraxx/netdata_nv_plugin](url)

Right now, I'd like to add some feature by myself. I would like to specifically monitor a processes running in host, from my docker where netdata installed. I've tried to map /proc from host to container but it return this error:
```
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/proc\\\" to rootfs \\\"/var/lib/docker/overlay/e8688bcc3689e07590c2cbec14c2e7d6a417e06dfc2f30fb516580e30d14127a/merged\\\" at \\\"/proc\\\" caused \\\"\\\\\\\"/var/lib/docker/overlay/e8688bcc3689e07590c2cbec14c2e7d6a417e06dfc2f30fb516580e30d14127a/merged/proc\\\\\\\" cannot be mounted because it is located inside \\\\\\\"/proc\\\\\\\"\\\"\""
Error: failed to start containers: 5b24c45c4f23
```
with this command:
```
sudo NV_GPU=0 nvidia-docker run --privileged --net=host -d --name netdata_test_map_2 -v /proc:/proc -p 8081:8081 -it d189f42bc63e
```

Is there any suggestion on how to deal with this problem? Or any other practical solution?

Thank you very much!

**Comment by ktsaou** [comment]
I am not a docker expert, but I think you have to mount host's `/proc` to a new directory inside the container.

I suggest to use `/host` and inside that mount the host's `/proc` and `/sys`, as `/host/proc` and `/host/sys`.

Then you need to edit `netdata.conf` (in the container) and set:

```
[global]
    host access prefix = /host
```

**Comment by dcharbonnier** [comment]
This works for me :
```
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE
```

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
