### ISSUE TITLE
Disable some Alarms?

### ISSUE THREAD

**Issue by jpedrot** [firehol/netdata#2315]
I tried searching and got no hits on this.

A crude way of disabling some alarms is to rename/remove the corresponding .conf file for that alarm.
But when you upgrade netdata, the file comes back and you have to rename/remove the .conf file again.

Is there a better way, or should I just make a cron that removes the file if they exist?

**Comment by Ferroin** [comment]
I'm not 100% certain about the upstream kickstart.sh script, but for versions installed through your package manager, you should be able to just comment out the alarm itself in the appropriate config file.

**Comment by l2isbad** [comment]
Or change `health configuration directory` (netdata.conf) and make links of interested alarms to the new directory. All other alarms will be disabled.

**Comment by jpedrot** [comment]
Thanks for the tips, I will look into this suggestions.
