### ISSUE TITLE
How to make netdata re-check all plugins?

### ISSUE THREAD

**Issue by Wing924** [firehol/netdata#2318]
Hello! I want to know how you make netdata re-check all plugins.

For example, in this scenario:

1. Install and start netdata.
2. Install and start apache.
3. Because netdata don't know apache has been started, it don't show apache graph.

How to make netdata auto-detect apache without restart it manually?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1918

**Comment by Wing924** [comment]
@l2isbad 
I know there are so many jobs that loop forever is a bad idea.
But I think it is good to add a option to re-check all plugins every day.

**Comment by dcharbonnier** [comment]
or at least a signal to reload

**Comment by ktsaou** [comment]
You can just kill `python.d.plugin`. Netdata will restart it.
But probably a `systemctl restart netdata` is probably equally fast if you haven't increased the history too much.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by l2isbad** [comment]
@Wing924 
implemented
https://github.com/firehol/netdata/issues/2757
