### ISSUE TITLE
Can we use netdata as a centralize monitoring tool 

### ISSUE THREAD

**Issue by sahubharat25** [firehol/netdata#2319]
Hi,

We are planing to implement netdata in our prod environment but we didn't find any doc to make it centralize  tool.

Can you Please let us know how we can do that.

**Comment by dcharbonnier** [comment]
Read :
- https://github.com/firehol/netdata/wiki/netdata-backends
- https://github.com/firehol/netdata/wiki/Replication-Overview
- https://github.com/firehol/netdata/releases/tag/v1.6.0

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
