### ISSUE TITLE
Failing to build - ubuntu

### ISSUE THREAD

**Issue by swiftugandan** [firehol/netdata#232]
The latest build is hanging at:
{{{
make[2]: Entering directory `/tmp/netdata/web'
if test -d "../.git"; then \
		if git --git-dir="../.git" log -n 1 > v.tmp; then \
			grep ^commit\ v.tmp | cut -d" " -f2 > version.txt; \
			rm -f v.tmp; \
		else \
			rm -f v.tmp; \
			echo "0" > version.txt; \
		fi; \
	else \
		echo "0" > version.txt; \
	fi
}}}

Please advise

**Comment by swiftugandan** [comment]
commit: ce9629df3960686ada4d00677ccb3896ced844be

**Comment by R0GGER** [comment]
Same problem here...
![2016-04-15 11_48_35](https://cloud.githubusercontent.com/assets/8298741/14558034/7bc11220-0300-11e6-8c59-1edb749c4284.png)

**Comment by samuba** [comment]
Also got the same Problem on CentOS 7.1

**Comment by kvasilov48** [comment]
I too...

Making all in system
make[2]: вход в каталог «/home/netdata/system»
if sed \
	-e 's#[@]localstatedir_POST@#/var#g' \
	-e 's#[@]sbindir_POST@#/usr/sbin#g' \
	-e 's#[@]sysconfdir_POST@#/etc#g' \
	netdata-openrc.in > netdata-openrc.tmp; then \
	mv "netdata-openrc.tmp" "netdata-openrc"; \
else \
	rm -f "netdata-openrc.tmp"; \
	false; \
fi
if sed \
	-e 's#[@]localstatedir_POST@#/var#g' \
	-e 's#[@]sbindir_POST@#/usr/sbin#g' \
	-e 's#[@]sysconfdir_POST@#/etc#g' \
	netdata.service.in > netdata.service.tmp; then \
	mv "netdata.service.tmp" "netdata.service"; \
else \
	rm -f "netdata.service.tmp"; \
	false; \
fi
if sed \
	-e 's#[@]localstatedir_POST@#/var#g' \
	-e 's#[@]sbindir_POST@#/usr/sbin#g' \
	-e 's#[@]sysconfdir_POST@#/etc#g' \
	netdata-init-d.in > netdata-init-d.tmp; then \
	mv "netdata-init-d.tmp" "netdata-init-d"; \
else \
	rm -f "netdata-init-d.tmp"; \
	false; \
fi
make[2]: выход из каталога «/home/netdata/system»
Making all in web
make[2]: вход в каталог «/home/netdata/web»
if test -d "../.git"; then \
	if git --git-dir="../.git" log -n 1 > v.tmp; then \
		grep ^commit\ v.tmp | cut -d" " -f2 > version.txt; \
		rm -f v.tmp; \
	else \
		rm -f v.tmp; \
		echo "0" > version.txt; \
	fi; \
else \
	echo "0" > version.txt; \
fi

**Comment by ktsaou** [comment]
fixed it.
Sorry!

**Comment by samuba** [comment]
works for me. Thank's for the fast fix! : )
Issue can probably be closed.

**Comment by swiftugandan** [comment]
thanx for the fast fix
