### ISSUE TITLE
Only need to monitor only certain metrics in netdata

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2324]
I only need to monitor certain metrics like cpu, ram, uptime and a few others. Is it better to turn off the charts in `netdata.conf`, or to construct a custom html file to render my desired metrics. What are the pros/cons/considerations of both methods? Thanks!

**Comment by ktsaou** [comment]
This is quite easy. Edit `netdata.conf` and disable everything at the `[plugins]` section, except `proc`. If you need to disable features of `proc`, there is another section `[plugin:proc]`.

Disabling plugins like that lowers also the resources consumed by netdata.
However, the whole idea of netdata is to let you know what is happening on your systems. If you disable all the data collection like that, you will not have all this information when you will need it.

My personal strategy is: collect everything, create custom dashboards to have a quick view and access the full dashboards when problems arise to see what is happening and why.

**Comment by sarlalian** [comment]
Is there a way to have netdata collect the normal set of metrics but only send a small subset on to opentsdb / influxdb?  Its nice to see the metrics when viewing the host, but our long term trending doesn't need the full set of metrics, and certain types (cgroups) in specific, are actually detrimental to our long term metrics storage.

**Comment by ktsaou** [comment]
Of course.
Use this:

```
[backend]
	send charts matching = !not*this*one* *this*one !*one *
```

This is a netdata simple pattern: a space separated list of patterns. Each pattern can have any number of ` * ` as wildcard. Patterns starting with ` ! ` give a negative match (will not be sent). Matches are evaluated left to right, the first pattern matching a chart (positive or negative) is used.

So, to send all cgroups, use `cgroup*`, to send all cgroups expect `lxc` cgroups use: `!*lxc* cgroup*`.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by fti-cneve** [comment]
@ktsaou @ilyam8 
I have multiple docker containers in my system. And I want to disable following charts from netdata for all docker containers:
- cgroup_system_services_config_ctr.cpu_limit
- cgroup_system_services_config_ctr.cpu_per_core
- cgroup_system_services_config_ctr.mem_utilization
- net_duplex.eth0

I tried to disable it from netdata.conf as follows:

[cgroup_system_services_config_ctr.cpu_limit]
        enabled = no
[cgroup_system_services_config_ctr.cpu_per_core]
        enabled = no
[cgroup_system_services_config_ctr.mem_utilization]
        enabled = no

(system_services_config_ctr is docker container name)

Would you please tell me how to disable these charts? I don't want to disable all cgroup charts. only few of them listed above needs to be disabled.

**Comment by ilyam8** [comment]
Hey @fti-cneve, have you checked the `[plugin:cgroups]` section (`netdata.conf`)? It is not possible to disable specific charts but check `enable ...` options.

**Comment by thiagoftsm** [comment]
Hello @igolemanski ,

You can select the charts that you want to send for netdata parent using the option [send charts matching](https://learn.netdata.cloud/docs/metrics-storage-management/reference-streaming#send-charts-matching) inside the configuration file `stream.conf`.

Best regards!

**Comment by igolemanski** [comment]
Thank you for the advice! I have done it and it works when I am directly logged in to the child I can see the limited metrics. Still when I move from the parent to the child I still see all of the running processes as usual. 

My goal is to completely stop the unnecessary metrics and to leave only the systemd, so that way It won't use additional server resources.

**Comment by thiagoftsm** [comment]
Hello @igolemanski ,

I misunderstood your initial goal, I am sorry for this.
Well, when you want to collect only specific metrics, this means that collectors need to be disabled as you can see in [this](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#configuration) link. For your current necessity you will need to keep `cgroup.plugin` enabled.

Best regards!
