### ISSUE TITLE
Netdata Update not working ?

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/netdata#2332]
Hi, I am using netdata on ubuntu 14.04 and 16.04.

I installed netdata on 14.04 some 3 months ago, and on 16.04 I installed it last week. 

On 16.04, I saw a section a **systemd Services**, but I did not see it on 14.04. So, I updated it(after 3 months), the update was successful, but even then I am not seeing any section namely **systemd services**. 

Why is it so ?

**Comment by ktsaou** [comment]
ubuntu 14.04 is not a systemd system.

**Comment by sLuvpreet33** [comment]
Oh !! I don't know how I missed that !! 

Sorry for this !

**Comment by sLuvpreet33** [comment]
Hey @ktsaou  I see netdata has opened some port,  but I cant figure out why it has opened that, 

    monitoring-server@monitoring-server:~$ sudo netstat -ntlp | grep netdata
    tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      26001/netdata   
    tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      26001/netdata   
    tcp6       0      0 :::19999                :::*                    LISTEN      26001/netdata   

I don't think I have made any change in netdata config, then what is this port for ?

**Comment by l2isbad** [comment]
> what is this port 8125 for ?

https://github.com/firehol/netdata/wiki/statsd
