### ISSUE TITLE
How to draw charts from data whose elements already have timestamp with it?

### ISSUE THREAD

**Issue by jerome-wang** [firehol/netdata#2333]
I have a data stream from redis, I need to keep getting fresh data from it and draw it to charts. And the data sequence looks like this:

{1497445992, 52}
{1497445994, 54}
{1497445998, 32}
{1497445991, 44}
....

All the data above already has a UNIX timestamp in it. 
I checked examples in python.d/, and didn't find any information about committing data along with timestamp. So I am here for help, did I missed some thing, or currently netdata not support this?

**Comment by ktsaou** [comment]
Hi,

To do this with netdata you have to write a data collector to collect these metrics as they happen (i.e. every second).

why this happens: netdata is not a generic time-series database, like graphite, opentsdb, etc. It is real-time performance monitoring tool, with an ephemeral internal time-series database.

So, I suggest either push your metrics to a time-series database in batch mode, like you ask, or write a small data collector to push metrics to netdata as they happen (i.e. without a timestamp).

**Comment by ktsaou** [comment]
Keep in mind netdata is a statsd server. It is very easy to add statsd to any custom application.
Check https://github.com/firehol/netdata/wiki/statsd

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
