### ISSUE TITLE
Can netdata collect text(non-metrics) data?

### ISSUE THREAD

**Issue by danfengcao** [firehol/netdata#2336]
I want to collect information(processlist) of mysql, but the type of information is text, not metrics. 
Is it possible for netdata to collect non-metric data? I think it's a general problem which would be met with other people.
Do you have any ideas of that puzzle? I can write source code if needed. In fact, I have added some codes of netdata in my personal environment.

**Comment by ktsaou** [comment]
Hi, netdata is strictly metrics. So you can have the number of processes, the number of unique processes, the time these processes are connected, etc. You can even map the processes into groups and keep a dimension / metric for each group (like apps.plugin does for the process tree), but still everything netdata does is based on numbers.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
