### ISSUE TITLE
How do I configure app groups where process names include spaces?

### ISSUE THREAD

**Issue by raffomania** [firehol/netdata#234]
I'm trying to add the plex media server process to an app group. The process is named `Plex Media Serv`:

    $ cat /proc/360/status 
    Name:	Plex Media Serv
    ...

How do I specify this in `/etc/netdata/apps_groups.conf`?

**Comment by ktsaou** [comment]
As: `Plex\ Media\ Serv`

**Comment by raffomania** [comment]
Thanks! Unfortunately, this doesn't work for me :(
I added the line `plex: Plex\ Media\ Serv` to `apps_groups.conf` and restarted netdata, but the plex group is not showing up in the charts.

**Comment by ktsaou** [comment]
apps.plugin read `/proc/360/stat`.
Can you post this file?

It is still does not work, please post the output of this:

```sh
/usr/libexec/netdata/plugins.d/apps.plugin debug 10 2>&1 | grep -i plex
```

**Comment by raffomania** [comment]
Contents of `/proc/360/stat`:

    360 (Plex Media Serv) S 1 360 360 0 -1 1077936384 3727314 81462639 1163 5255 204442 92214 2269664 67494 20 0 17 0 1309 697630720 36944 18446744073709551615 1 1 0 0 0 0 0 4097 17646 0 0 0 17 3 0 0 1707 0 0 0 0 0 0 0 0 0 0

When running

    /usr/libexec/netdata/plugins.d/apps.plugin debug 10 2>&1 | grep -i plex

it returns, among other data,

    apps.plugin: 	Agregating PlexMediaServ pid 360 on other utime=204449, stime=92215, cutime=2269664, cstime=67494, minflt=3727345, majflt=1163, cminflt=81462639, cmajflt=5255

seems like the spaces get munched somewhere along the process. Adding `plex: PlexMediaServ` to the group config fixed the problem.

Thanks!

**Comment by ktsaou** [comment]
This is not its proper behaviour. I'll have to check it.

**Comment by ktsaou** [comment]
Could you please post the whole log?
I guess it parsed `apps_groups.conf` properly, but it removed the spaces when evaluating the process tree.

**Comment by ktsaou** [comment]
this has been fixed. Read the top of `apps_groups.conf`.
keep in mind the old method of escaping spaces with backslash does not work any more. Now you can just enclose the process name in quotes. It also supports simple patterns.
Thanks!

**Comment by Night1** [comment]
Sorry to bring this back from the dead, 
however I'm unable to get plex listed on netdata, ive added Plex: Plex*  to apps_groups.conf and it does not show up.

also tried with Plex: 'Plex Media Serv'

**Comment by ktsaou** [comment]
Have you updated your netdata?

Give me the output of this:

```sh
/usr/libexec/netdata/plugins.d/apps.plugin debug 1 2>&1 | grep Plex
```

**Comment by Elrique64** [comment]
This is one of the lines I entered into the apps_group.conf and it works for me:  

Plex: "Plex Media Serv"

This is on an Asustor NAS, and works very well reporting Plex usage.  the only problem I see is Plex New Transcoder is considered a child process and when it's analyzing a file it shows Plex Media Server as using the CPU instead of Plex New Transcoder.  I tried to set:

PlexTranscode: "Plex New Transcoder"

But that didn't work.  (Because it's spawned from PMS, I suppose.)

**Comment by ktsaou** [comment]
> PlexTranscode: "Plex New Transcoder"
> 
> But that didn't work.

Can you find it in `ps -e` ? How is it shown there?

**Comment by Elrique64** [comment]
Well, I had to make a new library, but this is the results of ps -e for just this one instance.  

27156 root       5:23 /volume1/.@plugins/AppCentral/plexmediaserver/plexmediaserver/Resources/Plex New Transcoder -i -------------------------.mp4-threads 0 -nostats -q 3 -loglevel quiet -progressurl http://127.0.0.1:32400/video/:/transcode/session/bif/progress -filter_complex [0:v:0] scale=w=320:h=240:force_original_aspec

There is more to the line, but I don't have enough screen to show it all.  I blocked out the file name, too....  No need to have that in there.  

I tried 
_PlexTranscode:*"Plex New Transcoder"*_ 

and there was no joy with that either.

**Comment by ktsaou** [comment]
Try this:

```
PlexTranscode:"*Plex New Transcoder*"
```

**Comment by Elrique64** [comment]
Ok, tried that new string you suggested and it appears to be working correctly.  Transcoding seems to be showing as it's own process, now, so I can get some statistics on this as people stream media from me!  Many thanks!

**Comment by ktsaou** [comment]
ok. I close this. If there is any issue pending please open it again.
