### ISSUE TITLE
email notifications 

### ISSUE THREAD

**Issue by steveharder** [firehol/netdata#2343]
Hi,
I got it all wrong and can't send mail notifications to my gmail or office 365 account.
I don't have a lot of experience with sendmail.
can you please explain the steps for configuring the sendmail in Ubuntu server with Netdata?

Thanks,

**Comment by ktsaou** [comment]
Well, I think you should search for a guide for your mail server to do this. I think there are plenty of how-tos out there for postfix (google it as `postfix to gmail` or `postfix to office365`).

Once your system is able to send emails, netdata will be able too.

**Comment by steveharder** [comment]
Dear Costa I was able to configure postfix with my office 365 account but seems to have an issue with netdata email configuration, see the error below I see when I try to sent a test email  - 

# SENDING TEST CRITICAL ALARM TO ROLE: [ROLE]
/etc/netdata/health_alarm_notify.conf: line 95: myemail@domain.com: command not found
2017-06-15 16:13:48: alarm-notify.sh: INFO: sent email notification for: netdata-master test.chart.test_alarm is CRITICAL to 'myemail@domain.com'
# OK

**Comment by ktsaou** [comment]
What is at your `/etc/netdata/health_alarm_notify.conf` at line 95?
The default file has this there: https://github.com/firehol/netdata/blob/6dd6a777f4687ede8e5a6b50af40dd3e9cce8694/conf.d/health_alarm_notify.conf#L95

**Comment by steveharder** [comment]
I added my email address to line 95 and now moved it to line 93 but I get the same error.

# email global notification options
"my@domain.com"
# multiple recipients can be given like this:
              ""

**Comment by ktsaou** [comment]
You email address should be at this line: https://github.com/firehol/netdata/blob/6dd6a777f4687ede8e5a6b50af40dd3e9cce8694/conf.d/health_alarm_notify.conf#L101

like this:

```
DEFAULT_RECIPIENT_EMAIL="user@example.com"
```

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by makutamatey** [comment]
Please can you throw more light on the sendmail command?  how can i configure it?
I understand it is in /usr/sbin/sendmail ,but no sendmail exist in my usr/sbin

**Comment by paulkatsoulakis** [comment]
Hello @makutamatey, thanks for contacting!
You must have sendmail configured on your system, for netdata to be able to utilise it and send mails.

Depending the distribution you are running, you may already have something available, otherwise you need to get the distro specific instructions and follow them. I could point to some instructions if you provide more details about your distro, though still the best way to go is to try instructions on your machine directly

**Comment by olegsidokhmetov** [comment]
Hello!

A installed sendmail and configured  /etc/netdata/health_alarm_notify.conf

`# enable/disable sending emails
SEND_EMAIL=**"YES"**

# if a role recipient is not configured, an email will be send to:
DEFAULT_RECIPIENT_EMAIL=**"name@domain.com"**
# to receive only critical alarms, set it to "root|critical"
`

But command /usr/libexec/netdata/plugins.d/alarm-notify.sh test does not work.
What I need to do for etting email to my email?

**Comment by cakrit** [comment]
> Hello!
> 
> A installed sendmail and configured /etc/netdata/health_alarm_notify.conf
> 
> #enable/disable sending emails
> SEND_EMAIL="YES"
> 
> #if a role recipient is not configured, an email will be send to:
> DEFAULT_RECIPIENT_EMAIL="[oleg.sidokhmetov@domain.com](mailto:oleg.sidokhmetov@domain.com)"
> #to receive only critical alarms, set it to "root|critical"
> 
> But command /usr/libexec/netdata/plugins.d/alarm-notify.sh test does not work.
> What I need to do for getting emails to my email?

First ensure your server can actually send emails, by running the `sendmail` command yourself, directly from the shell. If that works, `alarm-notify.sh will also work.

**Comment by olegsidokhmetov** [comment]
I used command echo "Subject: sendmail test" | sendmail -v oleg.sidokhmetov@domain.com

After this command i recieved email
[https://savepice.ru/full/2019/7/22/f36e96a05fd4a31c0b97bf34a287fe44-full.png.html](url)

When i try to use command /usr/libexec/netdata/plugins.d/alarm-notify.sh test i did not get email from netdata

**Comment by cakrit** [comment]
Ah ok. Good to know you figured it out! :)
