### ISSUE TITLE
Discord Notifications

### ISSUE THREAD

**Issue by spitefultowel** [firehol/netdata#2344]
I installed the latest version of netdata with the kicstart script on EL7. When attempting to run _/usr/libexec/netdata/plugins.d/alarm-notify.sh test_ we receive the following.

```
# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2017-06-15 17:07:12: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is CRITICAL to 'tech-only', with HTTP error code 400.
# FAILED

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2017-06-15 17:07:12: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is WARNING to 'tech-only', with HTTP error code 400.
# FAILED

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2017-06-15 17:07:13: alarm-notify.sh: ERROR: failed to send discord notification for: local.localdomain test.chart.test_alarm is CLEAR to 'tech-only', with HTTP error code 400.
# FAILED
```

The same webhook runs for older versions that were setup and upgraded.

**Comment by ktsaou** [comment]
@lowfive can you help us on this? Does it work for you?

@spitefultowel which was the last version that worked?

**Comment by spitefultowel** [comment]
@ktsaou on the systems that I've updated netdata to latest it works with no issues. It's only when I installed from latest release that it throws Discord API error 400. I've verified the settings are correct (using existing as well as manually entering the info). But to answer your question I know it works on ```Your netdata version: 1.6.1_rolling
Your netdata commit: d6f1054 ```

**Comment by ktsaou** [comment]
Well, I am checking the changes to discord with this: https://github.com/firehol/netdata/blame/master/plugins.d/alarm-notify.sh

Everything discord related is 5 months old. So, I think there is something in the content that discord does not like.

I suggest to add the following line [just above the highlighted one](https://github.com/firehol/netdata/blame/master/plugins.d/alarm-notify.sh#L1118):

```
printf >/tmp/discord-debug-$$.txt "%q " ${curl} --write-out %{http_code} --silent --output /dev/null -X POST --data-urlencode "payload=${payload}" "${webhook}"
```

When this line is added, the script will print in /tmp/discord-debug-XXXX.txt (where XXXX is a number), the curl command that posts the notification to discord.

Can you post a few of them? (please mask your API keys)

**Comment by spitefultowel** [comment]
@ktsaou 
```/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on localhost.localdomain",\n            "text": "localhost.localdomain is critical, `test.chart` (_test.family_), *test alarm = new value*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "danger",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=localhost.localdomain&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-red.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "localhost.localdomain",\n                    "ts": 1497654675\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/ID/Key/slack ```

```/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on localhost.localdomain",\n            "text": "localhost.localdomain needs attention, `test.chart` (_test.family_), *test alarm = new value*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "warning",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=localhost.localdomain&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-orange.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "localhost.localdomain",\n                    "ts": 1497654676\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/ID/Key/slack```

```/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on localhost.localdomain",\n            "text": "localhost.localdomain recovered, `test.chart` (_test.family_), *test alarm (alarm was raised for 3 seconds)*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "good",\n                    "title": "test alarm (alarm was raised for 3 seconds)",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=localhost.localdomain&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/check-mark-2-128-green.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "localhost.localdomain",\n                    "ts": 1497654676\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/ID/Key/slack```

**Comment by ktsaou** [comment]
I don't see anything strange.

To help us find the issue, please do also these:

1. Run one of them (leave your API keys in it) and post the output. Discord may be returning the reason of failure.
2. Make the same change on another host that works and post the same files. Probably by comparing the 2 versions we can figure out the problem.

**Comment by spitefultowel** [comment]
So I just noticed that on the older version alarm-notify.sh is significantly different than the newer version. For instance line 1118 in the newer version is ```httpcode=$(${curl} --write-out %{http_code} --silent --output /dev/null -X POST --data-urlencode "payload=${payload}" "${webhook}")``` while in the older it's ```# the key status message```. In fact, the send_discord starts on 1042 in the older (with netdata-updater.sh runs) and the newer has it on 1076. I personally prefer to mask the key, but I will confirm that the URL's are the same and the key does have _ and -.

```
/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on localhost",\n            "text": "localhost is critical, `test.chart` (_test.family_), *test alarm = new value*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "danger",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=localhost&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-red.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "localhost",\n                    "ts": 1497669639\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/ID/Key/slack
```

```
/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on localhost",\n            "text": "localhost needs attention, `test.chart` (_test.family_), *test alarm = new value*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "warning",\n                    "title": "test alarm = new value",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=localhost&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/alert-128-orange.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "localhost",\n                    "ts": 1497669639\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/ID/Key/slack
```

```
/usr/bin/curl --write-out %\{http_code\} --silent --output /dev/null -X POST --data-urlencode $'payload=        {\n            "channel": "#tech-only",\n            "username": "netdata on coredb01",\n            "text": "coredb01 recovered, `test.chart` (_test.family_), *test alarm (alarm was raised for 3 seconds)*",\n            "icon_url": "https://registry.my-netdata.io/images/seo-performance-128.png",\n            "attachments": [\n                {\n                    "color": "good",\n                    "title": "test alarm (alarm was raised for 3 seconds)",\n                    "title_link": "https://registry.my-netdata.io/goto-host-from-alarm.html?host=coredb01&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "value": "test.family"\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/check-mark-2-128-green.png",\n                    "footer_icon": "https://registry.my-netdata.io/images/seo-performance-128.png",\n                    "footer": "coredb01",\n                    "ts": 1497669640\n                }\n            ]\n        }' https://discordapp.com/api/webhooks/295971292962619393/7_yyTECyQ7UxeJdic8hDZCU2n-Zt9TXcyW1tOKsaWU97dzbYu1_RR-qF0YzRSKJ4LUXC/slack
```

**Comment by spitefultowel** [comment]
I also copied over the alarm-notify from the working system (which is missing all of the custom notifications), but that resulted in no changes.

**Comment by ktsaou** [comment]
> I also copied over the alarm-notify from the working system (which is missing all of the custom notifications), but that resulted in no changes.

I guess this also means that the new `alarm-notify.sh` will work on the other systems. So, there is something on this system.

In general http code 400 means "bad request". Did you try to run one such curl command by hand? Did it respond with anything more descriptive?

For example, if I run one of them (please remove `--output /dev/null` from it before running it), it prints:

```
{"webhook_id": ["Value \"ID\" is not snowflake."]}400
```

What does it say in your case?

**Comment by spitefultowel** [comment]
The output returned from the failed curl command is
```
{"webhook": ["username"]}400
```
Running the successful curl command on the failing system results in ```ok200```.

I've discovered the issue. The "username" in the failing system is > 32 characters. I tested this by adjusting the username to 30 characters and it worked successfully. Once it hit 33 characters it started to fail. I'm guessing a truncation to the variable prior to dumping for output might be the way to go. I recommend updating line 1093 to be as follows as it will limit the username to 32 characters with 21 for host and 11 for the netdata message.
```
            "username": "netdata on ${host:0:21}",
```

**Comment by ktsaou** [comment]
nice finding!
I made a change so that when the username field is above 32 characters, it will be truncated to 28 and `...` will be appended.
Can you test it?

**Comment by spitefultowel** [comment]
Successfully works.

**Comment by ktsaou** [comment]
Thank you for tracing it and identifying the fix!

**Comment by ktsaou** [comment]
merged the fix.
