### ISSUE TITLE
[Question] What does data-common-max affect?

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2345]
Saw `data-common-max` but couldnt figure out what it is for. Please advise. eg

```
               <div data-netdata="netdata.net"
                        data-dimensions="out"
                        data-common-max="netdata-net-out"
                        data-decimal-digits="0"
                        data-title="Chart Data Traffic"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>

```

**Comment by ktsaou** [comment]
If you give the same `data-common-max` to 2+ charts, then all of them will share the same max value of their y-range. If one spikes, all of them will be aligned to have the same scale. This is done for the cpu interrupts and and cpu softnet charts at the dashboard and also for the gauge and easypiecharts of the netdata home page. This is why all these charts have the same scale.

The same functionality exists for `data-common-min`.

**Comment by elfgoh** [comment]
I see. Is this documented anywhere? I did a [search](https://github.com/firehol/netdata/search?q=data-common-max&type=Wikis&utf8=✓) and did find anything

**Comment by ktsaou** [comment]
documentation is behind, especially the custom dashboards one.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
