### ISSUE TITLE
Can I Monitor application bandwidth with Linux QoS without using FireQOS?

### ISSUE THREAD

**Issue by llunaCreixent** [firehol/netdata#2348]
Can I Monitor application bandwidth with Linux QoS without using FireQOS?

I made my QoS configuration with tc and iptables without using FireQOS.
I installed netdata but I can not see my clsses in my network interface. 
Do I have to make extra configuration? 
I want to see the traffic like here: https://github.com/firehol/netdata/wiki/Monitor-application-bandwidth-with-Linux-QoS

thank you for you time (:

**Comment by ktsaou** [comment]
It should work out of the box.

The script that does the job is this: https://github.com/firehol/netdata/blob/master/plugins.d/tc-qos-helper.sh

Can you run it by hand?

**Comment by llunaCreixent** [comment]
I should restart (systemctl restart netdata) after changing the tc objects. And 'Quality os Service' item appears in the menu.

Everithing is ok. (:
