### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2361]
Hello i'm using a mac and i can't install netdata. I've tried many times following closely the instructions but I have always a error message when it comes to build the program. Here's the display of my terminal when it goes wrong : 

"autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory"

How can I fix the problem ?

**Comment by ktsaou** [comment]
The problem is this:

```
Can't exec "aclocal": 
autoreconf: failed to run aclocal: No such file or directory
```

hm... I am not using a mac, so I don't know how to fix this.
@vlvkobal could you please help?

**Comment by cgoze** [comment]
Hi ! I solved the problem, I didn't do "brew link" for automake and autoconf, also zlib was not installed. I did it with "brew install zlib", then "brew link zlib".
Hope it can help someone with the same problem :)

**Comment by aizaimenghuangu** [comment]
I did it with "brew install zlib", then "brew link zlib". real solve this problem!
