### ISSUE TITLE
multiple senders sending metrics for the same host

### ISSUE THREAD

**Issue by GitStoph** [firehol/netdata#2364]
I have a master netdata server that has several clients streaming back to it. Whenever I attempt to use an SNMP.conf on this server however, iowait begins to spike, the CPU's work their way up to 100% and it eventually causes the netdata process to completely crash. 

My conf:
```
{
    "enable_autodetect": false,
    "update_every": 10,
    "servers": [{
        "hostname": "10.1.2.15",
        "community": "MyCoolCommunity",
        "update_every": 10,
        "max_request_size": 50,
        "titleoid": ".1.3.6.1.2.1.1.5.0",
        "options": { "timeout": 10000, "version": 1 },
        "charts": {
                "snmp_switch.myswitchname.bandwidth_port": {
                "title": "Switch Stats Per Port ",
                "titleoid": ".1.3.6.1.2.1.31.1.1.1.18.",
                "units": "kbps",
                "type": "area",
                "priority": 100,
                "family": "MySwitchName Ports",
                "multiply_range": [ 1, 41 ],
                "dimensions": {
                    "in": {
                        "oid": ".1.3.6.1.2.1.2.2.1.10.",
                        "algorithm": "incremental",
                        "multiplier": 8,
                        "divisor": 1024,
                        "offset": 0
                    }, "out": {
                        "oid": ".1.3.6.1.2.1.2.2.1.16.",
                        "algorithm": "incremental",
                        "multiplier": -8,
                        "divisor": 1024,
                        "offset": 0
                }
            }
        }
    }]
}
```
https://pastebin.com/U5yk3qpV - here's the error.log from her last moments 

I'm not sure if it matters, but I do have memory dedupe running currently on the master (KSM). 

Let me know what other outputs you'd require? everything seemed to work fine when i would `sudo su -s /bin/bash netdata` followed by `/usr/libexec/netdata/plugins/node.d.plugin debug snmp` ..

**Comment by ktsaou** [comment]
Hi, interesting... plugins should not have this effect to netdata.
Could you please run the snmp plugin by hand like this and post here the output:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the SNMP plugin by hand
/usr/libexec/netdata/plugins.d/node.d.plugin debug 1 snmp
```

**Comment by GitStoph** [comment]
Apologies, just getting back to this today. Uninstalled and reinstalled netdata before you replied. Now my netdata master is refusing to create dbs for any of the other servers attempting to stream to it (probably a separate issue i'm sure). The error log is claiming they're using different API keys than what's currently listed in the stream.conf, even though their configs never changed. I backed up and reused the stream.conf that I originally had for the server before reinstalling, but it's still failing. I'll have to come back to this once I get the streaming working again.

**Comment by GitStoph** [comment]
Looks like it runs the plugin without issue. It returns the switch, ports, and current traffic counter. It then continues to keep running in a continuous loop. would you like all of that in a pastebin? or will a snippet suffice?
```
2017-06-20 13:05:30: node.d.plugin: DEBUG: sent chart snmp_switch.mycoolswitch.bandwidth_port39
2017-06-20 13:05:30: node.d.plugin: DEBUG: setting current chart to snmp_switch.mycoolswitch.bandwidth_port40
BEGIN snmp_switch.mycoolswitch.bandwidth_port40 9875000
END

2017-06-20 13:05:30: node.d.plugin: DEBUG: sent chart snmp_switch.mycoolswitch.bandwidth_port40
2017-06-20 13:05:30: node.d.plugin: DEBUG: setting current chart to snmp_switch.mycoolswitch.bandwidth_port41
BEGIN snmp_switch.mycoolswitch.bandwidth_port41 9875000
SET in = 0
SET out = 0
END

2017-06-20 13:05:30: node.d.plugin: DEBUG: sent chart snmp_switch.mycoolswitch.bandwidth_port41
2017-06-20 13:05:30: node.d.plugin: DEBUG: snmp: 10.1.2.15: data collection ended in 87 ms.
2017-06-20 13:05:30: node.d.plugin: DEBUG: runAllServices()
2017-06-20 13:05:30: node.d.plugin: DEBUG: runAllServices()
2017-06-20 13:05:30: node.d.plugin: DEBUG: runAllServices()
```

**Comment by GitStoph** [comment]
After the debug appears to work, I run `sudo systemctl restart netdata`, and I'm able to see my SNMP switch for a few moments. Shortly thereafter netdata kills itself as a process completely. I was able to pick this out of the error.log before it throttled logging responses however:
```
2017-06-20 13:12:10: node.d.plugin: ERROR: snmp: 10.1.2.15: Received error = [TypeError: snmp.varbindError is not a function] varbinds = undefined
2017-06-20 13:12:20: node.d.plugin: ERROR: snmp: 10.1.2.15: Received error = [TypeError: snmp.varbindError is not a function] varbinds = undefined
2017-06-20 13:12:30: node.d.plugin: ERROR: snmp: 10.1.2.15: Received error = [TypeError: snmp.varbindError is not a function] varbinds = undefined
```
It appears it was able to do about three collections before it died. After it dies, I do a `sudo mv snmp.conf snmp.conf.bak` to attempt to "deactivate" the snmp plugin. When I restart netdata, `sudo systemctl start netdata`, the netdata user is using huge amounts of CPU.

**Comment by GitStoph** [comment]
![image](https://user-images.githubusercontent.com/20820226/27348872-1d8a2ed0-55bb-11e7-97f2-9aa6eadc721c.png)

**Comment by GitStoph** [comment]
At this point netdata becomes unusable. I can't refresh the webpage, etc. the entire server comes crashing to a halt virtually. It begins to spawn a ton of processes. see picture:
![image](https://user-images.githubusercontent.com/20820226/27348941-5434885e-55bb-11e7-8538-162f7f63ce3d.png)

**Comment by GitStoph** [comment]
After the second `sudo systemctl restart netdata`, the server seems to be sitting on a large amount of iowait. As you can see from before I even attempted the snmp plugin, the cpu rarely went above 10% CPU usage. here is where it sits now:
![image](https://user-images.githubusercontent.com/20820226/27349171-0bd7313c-55bc-11e7-93b8-84a6d827e7e3.png)
So I wonder, does this have anything to do with how it works with the KSM? Or the memory mode = map? Where can I go from here to assist with troubleshooting?

**Comment by GitStoph** [comment]
Tried a couple different settings.
Memory mode = Map + No KSM = Crashing.
Mem mode = Save + No KSM = ran out of RAM (unsurprisingly) quickly. No go. 
Mem mode = save + KSM = currently acceptable, but CPU is pretty consistently around 50% with 4 cores to work with.. I'd prefer to not run that hot consistently forever if possible. Please note that this is also with my SNMP switch config enabled. No crashing, everything working. 

This SNMP monitor is not required, but we'd like to have a few of them running rather than constantly referring back to LibreNMS. Before with mem mode map and KSM, the server ran cold and flawlessly with the same workload..  Since netdata wasn't compatible with Windows Server, SNMP was the next best option to use. I hope my info helps?

**Comment by ktsaou** [comment]
You face a very strange issue for sure!

So, I see 2 problems:

1. The SNMP problem
2. The high CPU usage problem
3. Memory modes

## SNMP Problem

Could you please run the plugin by hand to record 2 minutes of data and post them (using pastebin or something)?

We need to figure out what is causing this strange behaviour. Normally netdata is very strict with its plugins, and automatically disables any that misbehaves. So, a plugin should never cause such an issue to netdata.

I hope the output of the plugin will help us trace it.

## High CPU Usage

There is only one point that could cause something like this in netdata: When netdata adds data to the time-series database, it has to show a gap if this collection point is not adjacent to the last collection point. So, if a chart was last collected 10 minutes ago and is now collected, netdata will have to loop through 10 minutes (600 seconds) for all dimensions of the chart, to fill in zeros.

Normally this is very very fast. But if this happens for a slave that is streaming metrics to netdata, this work has to be done for every metric of the host. If you have 20 hosts that got connected at once, which were last collected 30 minutes ago, this could lead to the duration we see on the chart you posted.

I understand this is a central netdata that other hosts are streaming data to it. Right?
Do the above match the conditions these high CPU appeared?
Let me also check if I can optimize this part of the code... (will post here later about this)

## Memory modes

If the amount of memory to be used by netdata is above the available system ram, the only way to go is `memory mode = map`. KSM does not play a role here. In this mode, KSM cannot be enabled.

So, you say it is crashing with `memory mode = map`? We need to fix that. Are you comfortable to install `valgrind` on this machine to find the issue?

**Comment by ktsaou** [comment]
I have merged a few fixes that should prevent any startup crashes with `memory mode = map`. Also I optimized a bit the gaps filling code (it can be made a lot faster though).
I also updated net-snmp to the latest version.

Could you please test it now?

**Comment by GitStoph** [comment]
Yes sir. Admittedly I made the mistake of allowing graphite to be running on the same server. Although it's CPU usage is negligible, it's complicating the troubleshooting process unnecessarily. Currently I'm spinning up a dedicated graphite server to move that task over to. When that's done, I'll completely reinstall Ubuntu Server on the netdatamaster, configure it with memory mode = map and leave KSM off as requested. I'll skip the SNMP problem for now as I believe the functionality of the rest of netdata is more important. I'll keep you posted with my results. 

I'm unfamiliar with `valgrind` and its proper usage. I may need further instruction at that point to obtain the information you're intending?

**Comment by ktsaou** [comment]
ok, nice!

> I'm unfamiliar with valgrind and its proper usage. I may need further instruction at that point to obtain the information you're intending?

I have applied a few fixes that could cause such a crash on netdata startup, with memory mode `map`. If you find a case that it crashes (I can't), before solving the issue post here and I'll give instructions on how to run it (very simple, it just requires netdata to be recompiled with debugging enabled - also quite simple).

**Comment by GitStoph** [comment]
Here's where I'm currently at:
**Server config/stats:**
4 CPUs
8GB RAM
150GB HDD
Distributor ID: Ubuntu **Clean/new install from scratch**
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
Installed: netdata, fireqos, iptraf-ng, htop
Zero changes made to `/sys/kernel/mm/ksm/run` or `/sys/kernel/mm/ksm/sleep_millisecs`
zero changes made to `/etc/sysctl.d/netdata-memory.conf`
**Netdata.conf changes**
```
	• [global]
		 Hostname = NetdataMaster
		 History = 43200
		 Memory mode = map
	• [web]
		 Mode = multi-threaded
	• [registry]
		 Enabled = yes
		 Registry to announce = http://10.1.4.14:19999
		 Registry hostname = NetdataMaster
	• [backend]
		 Enabled = yes
                 Update every = 3
```
**Stream.conf changes**
```
[API_KEY]
[my-sweet-api-key]
  Enabled = yes
  Default history = 43200
  Default memory mode = map
```
After running `sudo systemctl restart netdata` after configuring the conf files, cpu was hovering right around 27%. Not too shabby. 

Then I attempted to add a new streaming server to netdata (my new graphite server). As soon as I restarted netdata on it after configuring `netdata.conf` and `stream.conf`, the CPU's went crazy. 3 of the 4 CPUs were constantly pegging at 100%. I'm assuming this is to extrapolate the previously missing data as you mentioned before? A side effect of this is, when I reload http://mynetdatamaster.domain.net:19999, i get the following error in my browser:
Cannot open file: /usr/share/netdata/web/index.html.

It's been approximately 10-15minutes now that I've sat back and let the netdata processes on the master do their work, but I still can't access the web URL. I'm unsure how it'd normally take to finish calculating this backlog? I wish I could still access the dash to see the stats while it's performing this work?

**Comment by ktsaou** [comment]
How did you installed netdata?

Does `/usr/share/netdata/web/index.html` exist? Is it owned by user `netdata` and group `netdata`?

Why the settings you posted above are capitalized? They won't work like that.

Can you post `/etc/sysctl.d/netdata-memory.conf`?

How many servers will be sending metrics to this machine?

Let's do it step by step:

1. Stop netdata
2. Disable streaming and disable backends
3. Delete everything in `/var/cache/netdata` (these are the metrics stored so far)
4. Start netdata and make sure it is pretty idle, with `memory mode = map` and `history = 43200` (are you sure you want that little history? This is just 12 hours).

Once you have this working and stable, enable streaming to start accepting metrics from other netdata servers. Depending on the number of hosts streaming metrics you may see increased I/O wait. If you have the right sysctl settings, it should settle after a minute or so (it creates all the files for the metrics). **This step is successful only if you have an idle system with ignorable I/O wait.** If it is not almost idle do not continue. Fix this first.

Once you are there, ping me to continue the setup.

**Comment by GitStoph** [comment]
> How did you installed netdata?
```
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
sudo ./netdata-installer.sh
```

> Does/usr/share/netdata/web/index.html exist? Is it owned by user netdata and group netdata?

Yes to both questions.

>Why the settings you posted above are capitalized? They won't work like that.

Sorry, formatted like that when I copied them from my OneNote.

>Can you post /etc/sysctl.d/netdata-memory.conf?

It doesn't exist, I never created it. 

>How many servers will be sending metrics to this machine?

15 currently.

So I think I may have found the solution to the problem. Before I saw you replied back, what I did was:
- `sudo systemctl stop netdata` on every single server.
- `sudo systemctl start netdata` on just the netdata master.
   - I noticed from FireQOS that I was still getting some netdata traffic on my master.. this is odd.. I go on to discover that another network admin had started the netdata process as a different user!
- I go back through every server and instead run `sudo killall netdata`
Things are calm on the master at this point. Great. Things are working.
- I go back to each server, one at a time, and run the `netdata-updater.sh`
   - This not only ensures each are on the latest version, but starts the process as well.

Now I have all 15 servers up and running, and the NetdataMaster's CPU is sitting just around 2-4%. Yay!

>Start netdata and make sure it is pretty idle, with memory mode = map and history = 43200 (are you sure you want that little history? This is just 12 hours).

I may go back to 86400. This is currently acceptable however since I am using prometheus/grafana to scrape the NetdataMaster from a separate server. This is again now working nicely with the config:
```
  - job_name: 'netdata'
    metrics_path: "/api/v1/allmetrics?format=prometheus_all_hosts&types=no"
    static_configs:
      - targets: ['netdatamaster'sIP:19999']
```
Quick question - Do i have to change the metric to 86400 in the `netdata.conf` AND `stream.conf`? or can I just change it in the `stream.conf`? 

**Proposed Solution** Is there a way when restarting the netdata service (`sudo systemctl restart netdata`) to verify that it is not currently running by another user? I think this is what was potentially hosing up everything? If there's a way to inject the change on your end so everyone's is fixed with the next update, that may potentially save future headaches? That, or possibly a less desirable possibility would be to ignore the metric time gaps when the netdata service is restarted on a NetdataMaster? I personally would consider the slight gap negligible, but my opinion is a drop in the netdata ocean.

**Comment by ktsaou** [comment]
> Quick question - Do i have to change the metric to 86400 in the netdata.conf AND stream.conf? or can I just change it in the stream.conf?

The netdata.conf setting is the default for all others. So comment out all others if you want to control it from netdata.conf.

> Proposed Solution- Is there a way when restarting the netdata service (sudo systemctl restart netdata) to verify that it is not currently running by another user? I think this is what was potentially hosing up everything? If there's a way to inject the change on your end so everyone's is fixed with the next update, that may potentially save future headaches?

netdata is designed to run concurrently for different purposes, even by the same user. But each instance should have its own config, directories and ports.

With the default settings, if you attempt to start netdata twice, the second one fails, because the port 19999 is already taken. So, I guess in your case you had the port on one of the 2 changed.

> That, or possibly a less desirable possibility would be to ignore the metric time gaps when the netdata service is restarted on a NetdataMaster? I personally would consider the slight gap negligible, but my opinion is a drop in the netdata ocean.

When it is a round-robin database. "ignore the metric time gaps" means "zero the database for this time-series". If we don't zero it, you will see the values of the previous round (i.e. if it is 86400, the values of the same time, yesterday). But, I will solve this issue. I can make this faster. It just requires some refactoring of the code.

> Is there a way potentially to send an update command to all upstream servers? And/or send a systemctl restart netdata (or equivalent) to upstream servers? Or is that too much of a security risk/coding headache?

You are right. The current status of netdata is that it is entirely "read only". You cannot actually do anything from the outside of each host, except view metrics.

**Comment by ktsaou** [comment]
I think we should treat the duplicate streaming of metrics from the same host in a special way. This duplicate streaming produces unexpected results, so we could either deny the second, or stop the first stream and accept the second stream.

**Comment by ktsaou** [comment]
I added a log line when this happens (multiple senders streaming metrics for the same host).
I will think a bit of it to decide how it should be treated.

**Comment by GitStoph** [comment]
Hmm. The problems have come back with a fury this morning it appears.. `journalctl -xe` tells me:
```
Jun 23 09:17:01 netdata CRON[12469]: pam_unix(cron:session): session closed for user root
Jun 23 10:08:51 netdata kernel: show_signal_msg: 15 callbacks suppressed
Jun 23 10:08:51 netdata kernel: netdata[694]: segfault at 1260 ip 000000000043b76e sp 00007fa6f9feb9b0 err
Jun 23 10:09:26 netdata systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Jun 23 10:09:26 netdata systemd[1]: netdata.service: Unit entered failed state.
Jun 23 10:09:26 netdata systemd[1]: netdata.service: Failed with result 'signal'.
Jun 23 10:11:18 netdata systemd[1]: Starting Daily apt activities...
```
**Note - netdata happens to be the server's name.**

Going to go through all the servers and disable the backends again.. Restarting the service just resulted in pegging the CPU's completely.

**Comment by ktsaou** [comment]
The crash is bad. We have to find it. Are you sure all your servers are unique? If the same machine GUID (`/var/lib/netdata/registry/netdata.public.unique.id`) is streamed by more than one host, things are unpredictable (I haven't even tested this case, so it might lead to a crash).

The latest version of netdata [logs a line when it detects this](https://github.com/firehol/netdata/blob/04811fb233e42c619308b7ae1c8fa3e740711e9a/src/rrdpush.c#L628): `multiple streaming connections for the same host detected`. Could you please check you don't have this line logged?

Regarding memory management, netdata does not do anything. This is entirely managed by the kernel. It works like virtual memory (the kernel decides which parts of the files to load into main memory, how long to keep them there, when to remove them from memory to free memory for other purposes, etc).

For example, on this server: http://build.my-netdata.io/ I have 23 hosts streaming metrics. Total 12GB. The machine has 8 GB RAM. The current memory utilization is 28%.

**Comment by ktsaou** [comment]
I have updated this wiki page with directions to run netdata under valgrind or to get a stack trace from core dumps: https://github.com/firehol/netdata/wiki/Tracing-Options

It would be very helpful if you could compile netdata with debugging and enable core dumps on this system, to allow us find the exact point of the issue.

**Comment by GitStoph** [comment]
So it was completely stable over the weekend, and is still running strong currently. I'm unsure as to what bug was still caught up in things, but it appears to have worked itself out for now? Last time the RAM had filled up over the course of two days.. It's been three since the correction and RAM utilization is down at 11.7% currently.. If I see the issue appears to be coming back, I'll gladly assist with tracing.

**Comment by ktsaou** [comment]
I think there is an issue in netdata when multiple senders are pushing metrics for the same host. I setup a lab to test it, but I couldn't reproduce it.

So, there is something for sure that triggers this, the solution most probably will be simple, but until we understand what it is and how to reproduce it, I can't do much...

**Comment by ktsaou** [comment]
And I don't think this is some random fault in netdata. Something very specific triggers this. So, I don't think it will happen again for you if you don't change the configuration of the senders or the receiver.

**Comment by GitStoph** [comment]
I haven't had the issue come back yet. I'll keep you updated if it does. Apologies for the lack in communication.

**Comment by ktsaou** [comment]
It is ok. If it happens again post here.
I am closing this for the moment, but just post and I'll reopen it immediately (it helps me clean my todo list).
