### ISSUE TITLE
Is there a way to manipulate values from SNMP 

### ISSUE THREAD

**Issue by ilanbe** [firehol/netdata#2369]
Hi, 
My specific  case is a "Process Start Time"  returned  in  epoch via SNMP, while I need to display "Seconds from startup) in seconds. 
any throughout on how i can manipulate the value for the chart/alarm?

 Thanks

**Comment by ktsaou** [comment]
Unfortunately you can't with just configuration.

But you can copy [snmp.node.js](https://github.com/firehol/netdata/blob/master/node.d/snmp.node.js) to `snmp2.node.js` and do whatever you like with it...

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
