### ISSUE TITLE
Shebang line #!/bin/sh in chart.d scripts failing on Ubuntu

### ISSUE THREAD

**Issue by zegerk** [firehol/netdata#237]
Dash is failing on declare statement - replacing with bash resolves the problem

`netdata/charts.d$ ./mysql.chart.sh 
./mysql.chart.sh: 13: ./mysql.chart.sh: Syntax error: "(" unexpected
`

**Comment by ktsaou** [comment]
Hi, these scripts are not runnable on their own.
They are sourced by `plugins.d/charts.d.plugin` which has the right shebang.

There is also a pull request in progress, that among other things, fixes them too #132 , but in any case their shebang is not used.
