### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2371]
Hi,

I want to suppress some charts that are displayed by default on the result page (http://ip-adress:19999), how can I configure netdata to keep only the charts I'm interested in ?

Thank you for your responses :)

**Comment by Ferroin** [comment]
If you don't care about the data itself (that is, you not only don't want to see the charts, but also don't care about collecting the data to send elsewhere), you can disable particular plugins or parts of plugins through netdata.conf.

**Comment by cgoze** [comment]
Ok, but I didn't really understood how we could do that

**Comment by l2isbad** [comment]
Head of netdata.conf file

```
# netdata configuration
#
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
```

**Comment by Ferroin** [comment]
To give a more specific example, I disable the uptime chart in all my netdata instances (I only care about current value for it 99% of the time, so keeping a chart for it is pointless for me).  To do so, I add the following to my `netdata.conf` file:
```
[plugin:proc]
        /proc/uptime = no
```

The proc plugin is admittedly one of the easy cases, but you can find info in the documentation for most plugins on how to disable specific instances.

**Comment by cgoze** [comment]
Ok thank you for your help :)

**Comment by l2isbad** [comment]
Well, wiki is the great source to start 😄 
[internal plugins](https://github.com/firehol/netdata/wiki/Internal-Plugins)
[external plugins](https://github.com/firehol/netdata/wiki/External-Plugins)

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
