### ISSUE TITLE
Odd CPU ordering in cpufreq chart.

### ISSUE THREAD

**Issue by Ferroin** [firehol/netdata#2374]
I hadn't looked much at the cpufreq charts on any of my systems before, and just noticed something really odd about them.  In the legend (and in terms of the color selection), the CPU ordering is really wierd, listing cores in pairs that are out of order relative to each other.  On my 4-core 8-thread laptop which has an Intel processor, I have:
```
cpu6
cpu7
cpu4
cpu5
cpu2
cpu3
cpu0
cpu1
```

While on my 8-core 16-thread home server (running a new Ryzen 7) I get:
```
cpu8
cpu9
cpu6
cpu7
cpu4
cpu5
cpu2
cpu3
cpu0
cpu1
cpu14
cpu15
cpu10
cpu11
cpu12
cpu13
```

For some reason, things are getting grouped by physical core (cpu0 and cpu1 on both systems are the first and second thread of the first physical core, cpu2 and cpu3 are on the second physical core, etc).  The ordering is consistent however (if I shutdown netdata and nuke the database file, I get the same ordering each time on a given system), so I think there's just a sorting function somewhere that's off.

**Comment by l2isbad** [comment]
@Ferroin 
Please change
https://github.com/firehol/netdata/blob/master/python.d/cpufreq.chart.py#L103
to
```python
for name in sorted(self.assignment, key=lambda v: int(v[3:])):
```
was it fixed?

**Comment by Ferroin** [comment]
Yep, that fixes it.  I can't believe I didn't think to check if netdata was trying to sort the list.

**Comment by ktsaou** [comment]
merged it!
