### ISSUE TITLE
How to config a netdata proxy mode ?

### ISSUE THREAD

**Issue by fooltux** [firehol/netdata#2377]
I'm config two node transfer data to master by a proxy ,but I confused about the configuration and ther manual is no finished . could you plese give  me a example  about how to config a proxy ? thanks a lot

**Comment by ktsaou** [comment]
Did you solved it?

**Comment by fooltux** [comment]
yes   I solved it .thank you very musch .

2017-06-23 5:05 GMT+08:00 Costa Tsaousis <notifications@github.com>:
