### ISSUE TITLE
MySQL charts are empty

### ISSUE THREAD

**Issue by axper** [firehol/netdata#2383]
Hi I have installed latest netdata 1.6.0-612-g04811fb_rolling on my host server.
I am running my databases in Kubernetes containers.

I have configured mysql plugin to connect to mysql via username/password, however the charts on netdata dashboard display all empty.
Running `sudo /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug` proves that netdata can connect to mysql and fetch data just fine: https://gist.github.com/axper/b3cb999ab571fe314fcfc3d93d46702e
Here's my `/etc/netdata/python.d/mysql.conf` : https://gist.github.com/axper/580f1c3164874dfab1dea28d28998372

Netdata charts display fine for elasticsearch and mongodb, I connected to them via TCP as well.

Please help me debug this issue.

**Comment by ktsaou** [comment]
Could you please run the plugin as user `netdata`:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the plugin
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug
```

netdata runs as user `netdata`, and probably is not able to fetch any data from the database.

**Comment by axper** [comment]
Ok this is weird, after about half an hour refreshing the page fixed it.
Can close this issue.
