### ISSUE TITLE
Getting started with development of a new chart

### ISSUE THREAD

**Issue by BrainDoctor** [firehol/netdata#2388]
Netdata is cool! So cool that I got the idea to collect the energy measurements of the photovoltaic installation at home. The installation comes with a device that provides a JSON API to collect the values. The JSON from a remote URL looks like this:
```
{
	"Head" : {
		"RequestArguments" : {},
		"Status" : {
			"Code" : 0,
			"Reason" : "",
			"UserMessage" : ""
		},
		"Timestamp" : "2017-06-25T16:54:57+02:00"
	},
	"Body" : {
		"Data" : {
			"Site" : {
				"Mode" : "meter",
				"P_Grid" : -718.499984,
				"P_Load" : -1106.500016,
				"P_Akku" : null,
				"P_PV" : 1825,
				"rel_SelfConsumption" : 60.630138,
				"rel_Autonomy" : 100,
				"E_Day" : 26837,
				"E_Year" : 5354118,
				"E_Total" : 14316920,
				"Meter_Location" : "grid"
			},
			"Inverters" : {
				"1" : {
					"DT" : 123,
					"P" : 1825,
					"E_Day" : 26837,
					"E_Year" : 5354118,
					"E_Total" : 14316920
				}
			}
		}
	}
}
```

I am thinking of writing a Python module that parses these values and displays them in a custom dashboard. It would neat to display the dashboard on a Raspberry Pi with Touchscreen in the kitchen.

Where do I begin with developing such a module? I have PyCharm installed on Windows, but then I got some reference not found issues for "base" and the UrlService and the like. What is the recommended way for this and debugging?

**Comment by ktsaou** [comment]
Nice! I already do this for my installation (the solar installation has an SMA WebBox attached) with a node.js plugin: https://github.com/firehol/netdata/blob/master/node.d/sma_webbox.node.js

Mine gives this output:

```json
{
  "format": "JSON",
  "result": {
    "overview": [
      {
        "unit": "W",
        "meta": "GriPwr",
        "name": "GriPwr",
        "value": "50"
      },
      {
        "unit": "kWh",
        "meta": "GriEgyTdy",
        "name": "GriEgyTdy",
        "value": "65.056"
      },
      {
        "unit": "kWh",
        "meta": "GriEgyTot",
        "name": "GriEgyTot",
        "value": "79747.249"
      },
      {
        "unit": "",
        "meta": "OpStt",
        "name": "OpStt",
        "value": ""
      },
      {
        "unit": "",
        "meta": "Msg",
        "name": "Msg",
        "value": ""
      }
    ]
  },
  "proc": "GetPlantOverview",
  "version": "1.0",
  "id": "1"
}
```

and the plugin produces 3 charts:

![image](https://user-images.githubusercontent.com/2662304/27518357-c836ca4e-59e6-11e7-947b-33f0b6d08004.png)

I collect values every 5 seconds (the maximum detail supported by SMA WebBox).

If you want to use python, I think @l2isbad can suggest a plugin that would be close to what you need.

**Comment by BrainDoctor** [comment]
Thank you this is indeed close to what I need, however I don't know any Node.js, only Java, Python and C# :( I should be able to adapt your code though.
What IDE on what platform are you using? Are plugins "unit" testable or is it better to code within Netdata directly (try & error with any texteditor) ? So far I haven't found any manuals for this.

**Comment by ktsaou** [comment]
Unfortunately unit testing has only be implemented for the core of netdata (the database operations).
You can test plugins by running them on a command line. For example to test sma webbox, you do this:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the plugin
/usr/libexec/netdata/plugins.d/node.d.plugin debug 1 sma_webbox
```

It should produce output compatible with netdata external plugins: https://github.com/firehol/netdata/wiki/External-Plugins

If you run it under netdata (i.e. restart netdata when your plugin is configured), netdata checks all the output from your plugin and will log any discrepancies in `/var/log/netdata/error.log`. It also disables plugins that misbehave.

**Comment by ktsaou** [comment]
btw, I use clion from jetbrains (netdata is mainly in C, jetbrains has donated 4 licenses to netdata).

**Comment by BrainDoctor** [comment]
Alright, this should get me somewhere. I'll setup an ubuntu VM and try with WebStorm or VS with my student license.
Should I share my plugin for netdata? It's for Fronius installations (https://www.solarweb.com/), specifically Fronius Symo. Right now I forked this repo for my own development.
Also I have a plugin for the heat pump installation in mind, but this one is easier to get started ;)

**Comment by ktsaou** [comment]
> Should I share my plugin for netdata

why not to? others may benefit too...

**Comment by l2isbad** [comment]
@BrainDoctor 
> The JSON from a remote URL looks like

[Then UrlService framework is your choice](https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L501-L599)

https://github.com/firehol/netdata/wiki/How-to-write-new-module#urlservice


>  I think @l2isbad can suggest a plugin that would be close to what you need

actually any that uses UrlService

**Comment by BrainDoctor** [comment]
Thank you. I was aware of the UrlService, however I did not know how to develop and test the new plugin.
Closing the issue now.
