### ISSUE TITLE
Add monitoring for NTP

### ISSUE THREAD

**Issue by Strykar** [firehol/netdata#2390]
I just started using netdata, I took a look at https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata
What's the right way to monitor NTP traffic over IPv4 and v6?

**Comment by l2isbad** [comment]
> NTP traffic over IPv4 and v6

ntp traffic?

https://github.com/firehol/netdata/wiki/Monitor-application-bandwidth-with-Linux-QoS

**Comment by Strykar** [comment]
I'll try that now. How do I monitor NTP's CPU/memory consumption?

**Comment by l2isbad** [comment]
> I'll try that now. How do I monitor NTP's CPU/memory consumption?

https://github.com/firehol/netdata/wiki/Apps-Plugin

**Comment by ktsaou** [comment]
apps.plugin and if your system is systemd based, you can also enable this: https://github.com/firehol/netdata/wiki/monitoring-systemd-services

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
