### ISSUE TITLE
chart types

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2392]
Hello, I'm writing a new python module. I read the help page https://github.com/firehol/netdata/wiki/How-to-write-new-module on how to write a module from the skeleton module given. I want to display my data in a piechart. Is the chart type 'area' is correct or is there another chart type that matches the pie chart ?

**Comment by ktsaou** [comment]
Hi, you need to set it to `stacked`. netdata does not support piecharts, but stacked charts are actually piecharts with a time dimension.

**Comment by cgoze** [comment]
Ok, for the 'lines', what are the different algorithm and how they are changing the data is displayed ?

**Comment by ktsaou** [comment]
They are explained here: https://github.com/firehol/netdata/wiki/External-Plugins#dimension
