### ISSUE TITLE
When is the release date for v1.7.0?

### ISSUE THREAD

**Issue by Wing924** [firehol/netdata#2395]
Hello!
Could you share me the future plan about release cycle?
Since v1.6.0 released in Mar 20th, 2017 and v1.5.0 released in Jan 22nd, 2017,
I think v1.7.0 will be released soon.

**Comment by ktsaou** [comment]
I plan to release it the first or the second weekend of July.

**Comment by gamefundas** [comment]
Any new features being introduced or this will be more of a enhancement release?

**Comment by candrews** [comment]
1.7.0 has been released: https://github.com/firehol/netdata/releases/tag/v1.7.0

**Comment by ktsaou** [comment]
I think we can close this now.
