### ISSUE TITLE
Allowing access to netdata only on one domain

### ISSUE THREAD

**Issue by bumbalaga** [firehol/netdata#2396]
Hello, I've read through the wiki, but i cannot find the answer i am looking for.

Currently i have a couple of websites under my nginx configuration and all of them allow access to the netdata dash via the port. Is there any way i can block access to netdata from all of the domains except one?

Also, on another server i am running VestaCP, which uses Apache2 and Nginx for proxy purposes. How would you configure this system to allow access to netdata on particular domain?

Thanks for your helps in advance.
Regards.

**Comment by ktsaou** [comment]
Hi,

if you proxy netdata through apache or nginx, you can use all the means provided by these web servers to limit access to netdata.

For apache check this: https://github.com/firehol/netdata/wiki/Running-behind-apache
For nginx this: https://github.com/firehol/netdata/wiki/Running-behind-nginx

You can use one web server to proxy all your netdata servers and apply all the filtering you need.

**Comment by bumbalaga** [comment]
To be completely honest with you, i don't really understand how can i manage access to port 19999 via nginx.

Are you suggesting that i should only allow access to port 19999 to localhost (iptables) and then use nginx as a proxy to access this port?

**Comment by ktsaou** [comment]
yes exactly. No need for iptables if your web server is running on the same host. You can bind netdata to 127.0.0.1 by editing netdata.conf.

If you run netdata on multiple hosts, you can proxy all your netdata via just one apache or nginx. In this case, use iptables to allow access to port 19999 from your web server only, and configure your web server to apply any access control you like for any or all of your netdata.

**Comment by bumbalaga** [comment]
I'll try it and let you know how it went.

**Comment by bumbalaga** [comment]
I did what you have said and proxy works fine, however when i try to access it using the port, i get this error message:
https://ss.bumbalaga.net/2017-06-27_20-17-24.png

Any chance of makind it disappear?

**Comment by ktsaou** [comment]
I guess you mean "when I try to access it using the **proxy**".
The URL rewrite you made at the proxy is wrong. Please check netdata access.log and the web server logs for the rewrite it makes.

**Comment by bumbalaga** [comment]
No, i meant what i wrote.

Let me explain what i want to achieve in more detail:

I want netdata to be accessible from one domain on the server, with password authentication. (The proxy is working)
I want http://Server_Ip:19999 to return completely nothing, as if there is no service running on this port

Is this achievable?

**Comment by ktsaou** [comment]
ok,

is the web server / proxy running on the same host with netdata? If yes, bind netdata to localhost. If no, you need iptables to block port 19999 from everywhere except the web server/proxy.

Password authentication can be setup at the web server / proxy. The wiki pages have info about this, but you can also use the documentation of your web server / proxy to set this up.

If you get errors while accessing netdata through the proxy, your proxy is not working properly. Please check the netdata access.log and the web server logs to find what is wrong (the proxy needs to rewrite the URL to fetch it properly from netdata - this is a bit tricky and the main reason for errors when accessing netdata through a proxy).

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by HostChefs** [comment]
Hello,

I am having a similar problem here... I have binded netdata on default port, but listening only to localhost.
What I want to do, is to make it accessible, ONLY through example.com/netdata/

Now, my problems are two. It is accessible through all the domains in the server and also, the dashboard.js is not loading, as it gets 404 error.

Any hints please?

**Comment by ktsaou** [comment]
@HostChefs we would need more info to help you. Are you using nginx? In general you should define a `backend` and then add a `location` to the virtual host you want netdata exposed.

The problem you have with error 404, means that your web server does not re-write the URL properly for sending it to netdata. For example if you access netdata via `http://your.domain/netdata/`, the URL forwarded to netdata should be `http://netdata.ip:19999/`, not `http://netdata.ip:19999/netdata/`.

**Comment by HostChefs** [comment]
@ktsaou 
I have figured out already about the 404 error and it was a block in the javascripts. I moved the rule below, and it is now working like charm.

I am using nginx, but I wasn't able how to "run" netdata on a single virtual host, rather than on all hosts.

Any help would be appreciated...
