### ISSUE TITLE
Node.js SNMP Plugin, lacking documentaion?

### ISSUE THREAD

**Issue by gonace** [firehol/netdata#2399]
Hi
I'm looking at the node.js plugin for collecting data from an snmp source, I'm running a few Cisco switches and are able to get a few graphs as I want. However it seems to be missing a lot of documentation regarding the json structure, what's possible and not.

I've been looking at:
https://github.com/firehol/netdata/blob/master/conf.d/node.d/snmp.conf.md
https://github.com/firehol/netdata/wiki/External-Plugins

And it seems that there are no clear documentation for what properties can be used or how to build a structure out of this snmp json configuration.

Am I missing something, like where the documentation is?

The main questions I have:
1) Can I change the icon via the json snmp configuration file ? now it's fa-puzzle-piece!
2) How do I set the "name" of the meny item via the json file?
3) Is it documented how to create a certain type of graph via the json file? (ex cpu utilization, I'm not able to create a decent CPU Utilization graph for a SNMP target.)

Regards,
Erik

**Comment by gonace** [comment]
So I've been working on a small dashboard for my self, but I can't find anyway to set min and max values for the pie diagram for the switch load. It seems to be filling depending on what would be the min and max value currently recoded.

Demo:
http://dashboard.obscured.se/

**Comment by ktsaou** [comment]
Hi,

You are right it is a bit misleading. For data collections there are not many options. The SNMP examples provides state all the available options.

But there are many custom dashboard options. The main problem is that custom dashboards have basic documentation.

To control the y-scale of charts you have many options:

1. The default is that charts auto-scale, independently of all other charts

2. You can make a set of charts auto-scale together (same y-range to all of them), by adding `data-common-min="NAME"` and `data-common-max="NAME"`. `NAME` is anything you like. Charts with the same `NAME` scale together.

3. Depending on the chart type you have chosen, there are options to set min and max. When I was adding chart libraries to netdata, I thought I should support in netdata the options the chart libraries support (hopping that people are already familiar with the chart libraries and they will know the options to use). I was wrong of course. The popularity of netdata is now probably better than the individual chart libraries, and the target group is quite different (so, people using netdata are not familiar with the chart libraries). Anyway, these are the options per chart library:

### easypiechart

- `data-easypiechart-min-value=VALUE`
- `data-easypiechart-max-value=VALUE`

other options supported: https://github.com/ktsaou/netdata/blob/f0c4199237528542c257c06d25035b8770f87268/web/dashboard.js#L5758-L5767

### gauge.js

- `data-gauge-min-value=VALUE`
- `data-gauge-max-value=VALUE`

other options supported: https://github.com/ktsaou/netdata/blob/f0c4199237528542c257c06d25035b8770f87268/web/dashboard.js#L5973-L5980

### dygraphs

- `data-dygraph-valuerange="[min, max]"` (any of the 2 can be `null`)

other options supported: https://github.com/ktsaou/netdata/blob/f0c4199237528542c257c06d25035b8770f87268/web/dashboard.js#L4630-L4707

**Comment by gonace** [comment]
Super, after reading your post and links it's much clearer to me :) Thanks!! 👍
