### ISSUE TITLE
why not make a monitor for docker?

### ISSUE THREAD

**Issue by CHfanghongrui** [firehol/netdata#2400]
just an idea

**Comment by ktsaou** [comment]
netdata monitors docker containers via cgroups.
What is missing?

**Comment by ximbal** [comment]
Would you care to point us to the right cgroups documentation please?

**Comment by ktsaou** [comment]
There isn't any, because there is nothing to do. Just install netdata on a host running any kind of containers and enjoy monitoring.

I could help more, If you briefly explain what you need.

To see a netdata dashboard with containers, check this: https://build.my-netdata.io

**Comment by ktsaou** [comment]
Check this too: https://github.com/firehol/netdata/wiki/monitoring-ephemeral-containers

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by BIskand3** [comment]
I need to validate the container's user file information like total file open , close , etc . Those already have in the host , but i want to look inside the container, is this capable ?

**Comment by ktsaou** [comment]
when netdata runs at the host, its sees all the processes, even the ones inside a container. This means the Applications, Users and User Groups sections include the containerized apps.
Have you tried it?

**Comment by BIskand3** [comment]
i tried, the netdata capture all the basic environment based on cgroups for the container, but that's still not giving the details information, for example like: total open files per user inside the container .

**Comment by ktsaou** [comment]
> total open files per user inside the container .

does docker expose these?

The docker users are mapped at the host. So `apps.plugin` should report them, although not with the same username. But, using `apps_groups.conf` you could define the processes you are interested, and this will report these counts at the Applications section. This is probably the best way to get the metrics you need for the apps inside the containers.

Another future solution would be for `apps.plugin` to provide another grouping: per namespace / container. Since it traverses the whole process tree, it could just group the processes with yet another way. hm... this is a nice enhancement...

**Comment by paulfantom** [comment]
> does docker expose these?

no.

**Comment by ktsaou** [comment]
hm... if `apps.plugin` can find the namespace of each process and it already knows the UID of each process, then it could provide all the charts per container-uid pair... hm...

a lot more charts though....

**Comment by JohnMaguire** [comment]
I think it would be nice to have a monitor that indicates the state of each Docker container:

- Started
- Stopped
- Failed

You could then setup alarms if there are failed containers.

**Comment by ilyam8** [comment]
Not sure what is `failed`.

That is what docker_engine [exposes](https://docs.docker.com/config/thirdparty/prometheus/):

```
# HELP engine_daemon_container_states_containers The count of containers in various states
# TYPE engine_daemon_container_states_containers gauge
engine_daemon_container_states_containers{state="paused"} 0
engine_daemon_container_states_containers{state="running"} 0
engine_daemon_container_states_containers{state="stopped"} 0
```

More detailed info can be retrieved via [docker remote api ](https://docs.docker.com/engine/api/v1.39)

In [the documentation](https://docs.docker.com/engine/api/v1.39/#operation/ContainerInspect) i see:
 - "created"
 - "running"
 - "paused" 
 - "restarting"
 - "removing"
 - "exited"
 - "dead"
