### ISSUE TITLE
prometheus metrics missing until restart

### ISSUE THREAD

**Issue by vincus** [firehol/netdata#2402]
It seems netdata stochastically stops providing prometheus format metrics, until restart
Cant reproduce easily, have to wait days to come up again, any idea ?

**Comment by ktsaou** [comment]
hm... prometheus pulls the metrics from netdata. So, netdata is just there waiting for prometheus to ask for metrics. If this happens again, try to fetch the URL you have configured to prometheus to fetch data from netdata. If it does not work, we have a problem in netdata. If it does work, you may have a networking issue or something at the prometheus side.

**Comment by vincus** [comment]
Yes, when it happens it gives you a blank page instead of shiny mereics. It is definitely a netdata issue, not prometheus (however it has its own flaws but not on thisl :) )

**Comment by vincus** [comment]
*metrics (no edit from mobile github)

**Comment by ktsaou** [comment]
Does it still happen. I have tried hard to reproduce it without success.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
