### ISSUE TITLE
about the metric system.ram.used/system.ram.free

### ISSUE THREAD

**Issue by zhangxin0112** [firehol/netdata#2404]
hi . i confuse about the system.ram.used/system.ram.free
in my consideration the netdata should use the data as the linux's role 
so it should be :
system.ram.used  72671
system.ram.free 24023

[root@node3 ~]# free -m
             total       used       free     shared    buffers     cached
Mem:         96695      72671      24023          0       1028      49603
-/+ buffers/cache:      22040      74655
Swap:            0          0          0

but now  . currect :
![netdata_free](https://user-images.githubusercontent.com/8244097/27719451-00e922b4-5d85-11e7-896f-8584fe34fca7.png)

reference:
http://www.linuxatemyram.com/

**Comment by ktsaou** [comment]
Hi,

this chart shows a break-down of the system ram. The sum of all dimensions should be the total ram of the system (if you check the left side of the chart, the whole chart should peak at 96695MB).

If we were presenting the chart with `free = 72671` the chart would peak above the physical ram of the system. We should either eliminate `cached` or have a separate chart for it.

So, `cached` is a form of `free`, but it is not unused. `free` is unused.

**Comment by ktsaou** [comment]
The rightmost chart at the top of the dashboard, shows the percentage of used ram, counting `cached` as `free`. So, you already have the info you need.

The `system.ram` chart is supposed to provide a detailed analysis of how the system ram is used. It is like a pie chart.

**Comment by zhangxin0112** [comment]
ye. 
got it.
