### ISSUE TITLE
Incremental charts interpolations

### ISSUE THREAD

**Issue by ChiraMircea** [firehol/netdata#2409]
Hi, is there a way to remove the interpolation of incremental charts? The [docs](https://github.com/firehol/netdata/wiki/External-Plugins) say for incremental charts: he value increases over time, the difference from the last value is presented in the chart, the server interpolates the value and calculates a per second figure. But I can't find a way to disable this and only have it use the actual value.

Here's an example: I need to display new data every 5 seconds, so if I first pass 100 to my chart and at the next call 105 I want my incremental chart to display 5 but it ends up displaying strange values like 0,64. Now, I'm guessing this is the result of calculating a 'per second' figure' but I'm looking for a way to show the exact difference directly. Is there a way to do this with incremental charts?

**Comment by ktsaou** [comment]
Hi,

sorry there is no option to disable interpolation for incremental dimensions. All the incremental dimensions show values "per second", calculating the exact value at second boundaries with microsecond resolution, no matter what the data collection frequency is.

But if you write your own plugin, you can send the metrics as `absolute` (i.e. do the math yourself: 105 - 100 = 5 and send this 5 to netdata as absolute).

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
