### ISSUE TITLE
Stuck at the end while making all in web

### ISSUE THREAD

**Issue by Saminkatwal** [firehol/netdata#241]
![netdata prob](https://cloud.githubusercontent.com/assets/18487382/14568429/b743a6ae-02ed-11e6-9a13-fd1d2c9da234.JPG)

**Comment by ktsaou** [comment]
this has been fixed earlier today #194 #232 
Please pull it again and retry

**Comment by Saminkatwal** [comment]
it's working now thanx :) i have been trying it get it done myself but i couldn't well thanx finally it's fixed
