### ISSUE TITLE
Prometheus Labels vs Names

### ISSUE THREAD

**Issue by efaden** [firehol/netdata#2410]
So I am starting to use NetData to stream to prometheus for graphing longer term.  The issue I am running into is with the way that NetData chooses the names of the metrics that actually makes it more difficult to query.  

See: https://www.robustperception.io/extracting-labels-from-legacy-metric-names and https://www.robustperception.io/whats-in-a-__name__/ ...

From talking to the prometheus guys the metric names should be more generic and the specifics placed into labels...

For example the metric:

services_cpu_system_slice_ssh_service{instance="bupivicaine"}

May be better saved as:

services_cpu_system_slice{service="ssh", instance="bupivicaine"}

Or: 
cgroup_smokeping_cpu_per_core_cpu0{instance="bupivicaine"}

as:

cgroup_cpu_per_core{service="smokeping", cpu="cpu0", instance="bupivicaine"} 

Thoughts?  This makes it much easier to query and utilize PomQL and other functions.

**Comment by mvanrompuy** [comment]
I was actually about to type down the exact same remark. :)

I was looking specifically looking at getting a query to get an overview of the proportional usage of cpu/mem per user. With the current metrics setup, every user is a separate metric (users_cpu_usera, users_cpu_userb, ...). To me it would also make more sense of having separate labels in the users_cpu metric (users_cpu{username="usera", instance="netdata0"}).

My workaround for now is using a regex on the metric name in my prometheus query: {__name__=~"users_cpu_.*"}.

It seems like one could create this setup on the existing Netdata output by using a custom scrape config using 'metric_relabel_configs', but I have yet to try it out...

**Comment by ktsaou** [comment]
Hi,

netdata does not know what each metric represents. All metrics have the same attributes (`host`, `type`, `id`, `family`, `context`, etc).

When we added prometheus export, there was a discussion about the format. We [identified](https://github.com/firehol/netdata/issues/1497#issuecomment-270485717) that netdata is missing an attribute (`instance`), which is incorporated into `type` and currently can only be extracted with heuristics (the dashboard does this with javascript). So, we have to finish #807 to settle this issue.

**Comment by efaden** [comment]
Gotcha.  Good to know its in the works.  Having a lot of those metrics with
labels would make it much easier to use in grafana.  Right now I have to
run several queries, instead of just being able to run one and using the
labels.

Similarly the instance which is currently this is being written out with
underscores instead of periods....  Is there a reason for this?

Thanks!

-Eric

**Comment by ktsaou** [comment]
Cleaning up.
