### ISSUE TITLE
update dm device name from /dev/mapper

### ISSUE THREAD

**Issue by sn-x** [firehol/netdata#2414]
Hi!

Is it currently possible to update disk (dm device names) from /dev/mapper/*?

Netdata:
![selection_102](https://user-images.githubusercontent.com/15047082/27833833-afc5ea9a-60d4-11e7-9800-d93150fb2336.png)

/dev/mapper:
![selection_103](https://user-images.githubusercontent.com/15047082/27834003-6f927c44-60d5-11e7-8e42-e00e4d917ed1.png)

**Comment by Ferroin** [comment]
I would actually love to have this too, but it is worth pointing out that it is non-trivial because almost any profile other than a simple linear one has multiple underlying devices.  For example, for a 2-way replicated RAID-1 LV, you have the following names in /dev/mapper:
`VG-LV0`
`VG-LV0_rimage0`
`VG-LV0_rimage1`
`VG-LV0_rmeta0`
`VG-LV0_rmeta1`
In a similar manner, you get one device per stripe for parity raid profiles, and one pair of devices per PV for RAID-10, not to mention the complexities of cached or thinly-provisioned devices, both of which have at least two higher-level underlying devices, and may have multiple lower-level underlying devices.

**Comment by ktsaou** [comment]
ok, here it is.
It works only if the disk is one-to-one mapped.

**Comment by ktsaou** [comment]
It works on my machine, but I would appreciate it if you can test it on your systems.

The charts are backwards compatible (they can be accessed by both `dm-X` and the device mapper name (only the device mapper name is shown on the dashboard, but both work).

**Comment by sn-x** [comment]
Wow, great! That was fast.
Give me a couple of minutes to test and I will report back.

**Comment by sn-x** [comment]
I have copied the modified file to my local source, built a deb package and pushed it to one of my servers. I still see "dm-*" devices in the dashboard.

a) I tried to enable logging at lines 86, 94, 97 in src/proc_diskstats.c, but nothing is logged. 
b) I looked at "strings /usr/sbin/netdata" and can see the lines below, which (i think) indicates the correct src/proc_diskstats.c is included (since previous version didn't include string "%s/dev/mapper")
...
proc_diskstats.c
Cannot read link '%s'
/sys/dev/block/%lu:%lu/%s
path to get h/w sector size
%s/dev/mapper
...

Do you have a suggestion on how to continue?

**Comment by ktsaou** [comment]
It works only for disk major 253.
Could you please check your `/proc/diskstats` for the major number (the first column) of your `dm-XX` devices?

**Comment by sn-x** [comment]
You are correct. The major number differs across different kernels. I've been testing on kernel 3.16.

Output of /proc/devices:
a) Debian Jessie (kernel 3.16)
- 254 device-mapper
b) Debian Wheezy (kernel 3.2)
 - 253 device-mapper
 - 254 mdp
c) Ubuntu 17.04 (kernel 4.10)
 - 253 device-mapper
 - 254 mdp
d) CentOS 7 (kernel 3.10)
 - 254 mdp

I am still searching for documentation files..

**Comment by sn-x** [comment]
I did a test on Debian Wheezy and it works. Great patch!

About the major number - I am looking at https://www.kernel.org/doc/html/latest/admin-guide/devices.html?highlight=mapper, and I see: "240-254                 Reserved for local use". 
Does this indicate the major is dynamic - first comes first serves?

**Comment by sn-x** [comment]
Another update.. I also found a Debian Wheezy (krnerl 3.2) server that has device mapper at major 254

**Comment by ktsaou** [comment]
hm... I can add 254 too, or I can add another option for disk patterns to lookup via device mapper (i.e. `lookup device mapper names for disks = dm-*`).

**Comment by Ferroin** [comment]
Pretty much, 253 or 254 (depends on the kernel and if it's MD or DM framework) is the default, but they aren't guaranteed to be used, and more than just those can be used if more than 256 mapped devices exist.

From my perspective, there are two ways this could be handled:
1. Check `/proc/devices` at startup, see what minors are listed there for the device mapper or mdp, and work with those.
2. Just assume that symlinks in /dev/mapper that point to a block device is a mapped device, and just work with those.

The second is a  bit more robust when dealing with _big_ systems.

**Comment by ktsaou** [comment]
> The second is a bit more robust when dealing with big systems.

why?

I see that in my patch there is an issue. I just match the names. I could use your suggestion No 2 and check that the file pointed to by the symlink has the same major and minor, independently of its name.

**Comment by Ferroin** [comment]
I actually didn't see your comment before I posted mine.  I like the idea of just specifying a regex to use for the lookups better, device numbers (major or minor) aren't guaranteed stable these days anyway, and matching those instead of just matching the node names (which are generally more consistent across systems), and it deals with the fact that systems with more than 256 DM devices will overflow into other major numbers.

**Comment by ktsaou** [comment]
Wow! overflowing the major/minor numbers is a big problem. Things will go crazy. Are you sure this is really happening on big systems?

**Comment by sn-x** [comment]
Another thing I noticed - if I look at the dashboard directly on the server, device names are correctly displayed (mapped), but looking through master netdata, I still see dm-* devices.

Are the mapped names forwarded to the master?

**Comment by ktsaou** [comment]
hm... they are supposed to. I'll try to reproduce this later today.

**Comment by ktsaou** [comment]
Did you refresh the master dashboard? The original chart names still work, so if you had the dashboard open you will not notice the change.

**Comment by ktsaou** [comment]
ok, I know what happened. The master needs to be restarted (no need to be updated to the latest version). It does not change the names of the running charts, to avoid breaking its running clients. It needs to reload the charts, so just restart it.

**Comment by sn-x** [comment]
You are correct! Restarting the master fixed the issue.

**Comment by Ferroin** [comment]
I just double checked, I was thinking of old UNIX behavior, not current linux behavior (minor used to be 8 bits), so for any realistic system there should be no overflow.

The whole thing about 253 versus 254 for the major still applies though.

**Comment by ktsaou** [comment]
ok, here it is. Now it works for any major:minor, and compares these numbers to match the right name.

**Comment by sn-x** [comment]
I have tried the latest patch. It works with major 253 and 254 on Debian Wheezy.
On Debian Jessie with device-mapper 254, I still see dm-* device. 

Any suggestion how to pinpoint the problem?

**Comment by ktsaou** [comment]
ok, please check:

```
# netdata expects that this directory contains symlinks pointing to the actual device files (it assumes they are relative symlinks  - which might be wrong)
ls -l /dev/mapper

# check for errors about this functionality
grep "DEVICE-MAPPER" /var/log/netdata/error.log
```

**Comment by sn-x** [comment]
debian8 ~ $ file /dev/mapper/VG-LV_SWAP
/dev/mapper/VG-LV_SWAP: symbolic link to ../dm-1

debian8 ~ $ file /dev/dm-1
/dev/dm-1: block special (253/1)  

debian8 ~ $ grep "DEVICE-MAPPER" /var/log/netdata/error.log | wc -l
0

I have also tried uncommenting additional logging on lines 91, 96, 100.

**Comment by ktsaou** [comment]
ok, please post the `/proc/diskstats` of the machine that fails to do it.

**Comment by ktsaou** [comment]
If you are viewing it on a master, remember to restart it after you update the slave.

I see in the code that there is no condition at all. But the right file has the debug comments at lines 94, 99, 103. Are you sure you are using the latest?

**Comment by sn-x** [comment]
I am using the file commited 15 hours ago (https://github.com/ktsaou/netdata/blob/542967bf7ae71df1e3f07c4a56dbdfd0fc035c88/src/proc_diskstats.c - 542967b). Is this the correct one?

debian8 ~ $ cat /proc/diskstats
   2       0 fd0 4 0 32 144 0 0 0 0 0 144 144
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8      16 sdb 62549 17481 1904133 408268 16018150 71036905 1141384605 599206996 1 76546480 599732692
   8      17 sdb1 69 106 1400 100 1430548 17203 2024068 20631768 0 20513472 20630996
   8      18 sdb2 78 0 156 540 0 0 0 0 0 536 536
   8      21 sdb5 62145 16885 1896601 405908 14587357 71019702 1139359569 578565648 1 56632408 579098768
   8       0 sda 786123 3239865 477262495 8370272 15590268 67916290 673747867 510718852 1 74694632 519168856
   8       1 sda1 2246 14560 1963122 50588 1429179 3913 73505 15462156 0 15399676 15511460
   8       2 sda2 80 0 160 380 0 0 0 0 0 380 380
   8       5 sda5 783642 3224993 475295477 8317924 14160847 67912377 673673410 495242920 1 59828560 503639172
   9       0 md0 486 0 3882 0 5889 0 73416 0 0 0 0
   9       1 md1 441170 0 10541000 0 82395375 0 671675496 0 0 0 0
 253       0 dm-0 13442 0 428650 54948 313890 0 3199240 14291444 0 2562884 14347252
 253       1 dm-1 461 0 3688 1376 2588 0 20704 160272 0 13988 161664
 253       2 dm-2 6903 0 269766 49868 210939 0 2011552 6020292 0 3264028 6071304
 253       3 dm-3 243 0 1938 2648 39837 0 318696 1499184 0 868240 1501848
 253       4 dm-4 298 0 13770 380 24963 0 210328 984168 0 532344 984544
 253       5 dm-5 419615 0 9821420 1895896 80377977 0 665914976 3717223872 1 72064704 3719178212

**Comment by ktsaou** [comment]
I don't see why it should not work.

Do me a favour: above [line 58](https://github.com/ktsaou/netdata/blob/542967bf7ae71df1e3f07c4a56dbdfd0fc035c88/src/proc_diskstats.c#L58), add this:

```
info("DEVICE-MAPPER ('%s', %lu:%lu): checking for its name.", disk, major, minor);
```

After this, do you have it in logs? You should.

**Comment by sn-x** [comment]
Baaaah! I have script that checks out the code, updates some files, and builds a package. I had a bug in my own code, and the modified proc_diskstat.c was never updated, so the package was faulty. 
I can now confirm it works properly on both Debians (7 and 8) and with both major numbers (253, 254).

I am really sorry for wasting your time. And thank you very much for the patch all your help!

**Comment by ktsaou** [comment]
ok. perfect. I am merging it.

**Comment by ktsaou** [comment]
merged it
