### ISSUE TITLE
Access to log content

### ISSUE THREAD

**Issue by Noxalus** [firehol/netdata#2418]
Hello everyone. 😄 

I've just browsed the entire documentation, and I didn't see anything to have access to the content of log files for a specific service. I've read that with **web_log** plugin, we can [tail the log files](https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file#tail-the-log) of web servers like Apache, but it seems to be used only to produce charts.

So I'm wondering whether it's actually possible to get access to log files content from the netdata interface like keymetrics.io does?

**Comment by ktsaou** [comment]
Hi, netdata is purely charts and alarms. It does not store any of the source data. It only process them to produce metrics for the charts.

**Comment by Noxalus** [comment]
That's what I thought, thank you for the confirmation 👍
