### ISSUE TITLE
centos 6 init.d startup usage ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#242]
Just found out you actually do have a redhat/centos 6 init.d start up file https://github.com/firehol/netdata/commits/master/system/netdata-init-d.in but was wondering what's the official method of deployment step wise ?

cheers

George

**Comment by ktsaou** [comment]
The build system (and the installer) will create a file in the same directory, with the same name but without the `.in` extension.

That file should be able to manage your netdata directly from the directory you decided to install it (whatever you gave to `--install` at the installer).

Test it of course before relying on it.
These files are community contributed.
If you find any discrepancy, please make a PR to fix it.

**Comment by centminmod** [comment]
i see so if i installed at `--install /opt` it would be at `/opt/netdata/system/netdata-init-d.in`

**Comment by ktsaou** [comment]
No these are not installed. They will be in the build directory as `system/netdata-init-d`

**Comment by ktsaou** [comment]
is this ok to close?

**Comment by centminmod** [comment]
thanks for clarification :)
