### ISSUE TITLE
Can be a Nagios-alike replacement?

### ISSUE THREAD

**Issue by sebelk** [firehol/netdata#2424]
Hi,

I wonder if netdata can be a nagios-alike replacement. Does store history? Or is only realtime?

Thanks in advance!

**Comment by ktsaou** [comment]
Hi,

it depends on your needs.

Given enough disk space you can have a netdata master that stores months of metrics for all your systems. Or you can archive them to a time-series database and use grafana to view them.

netdata is also missing UIs to manage as a whole everything you have. nagios, zabbix, etc are a lot more worked in this area. I think netdata v1.8.0 (the release after the next one) will be worked significantly in this area (at least my plan is to).

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. Keep in mind central netdata has been rescheduled for v1.9.0
