### ISSUE TITLE
global settings for controlling units for memory size, disk space and network bandwidth

### ISSUE THREAD

**Issue by apiemont** [firehol/netdata#2425]
I have the following:

```
# df -h /mnt/vol4/
Filesystem           Size  Used Avail Use% Mounted on
euchvs01:/srv/diska  233T  1.5T  232T   1% /mnt/vol4

```
but netdata web interface for that host disk space utilization shows the correct number but wrong unit, e.g. GB instead of TB.

**Comment by apiemont** [comment]
took a screenshot: https://transfer.sh/fg8X7/unit.png

**Comment by Ferroin** [comment]
It looks like it unconditionally uses GB as the unit (I've got a couple of systems with sub-GB filesystems which still show values in GB instead of more sensible units).

**Comment by ktsaou** [comment]
You can change the units, but unfortunately it is quite some configuration work (you will have to edit netdata.conf find ` = GB` and set it to ` = MB` and for all dimension on these charts, multiply the existing divisors with 1024.

However, it would be nice to have a few settings to set units for memory, disk and network.

**Comment by ktsaou** [comment]
I have moved all the unit conversion requests to #2745 
So, let's continue this discussion there.

**Comment by cakrit** [comment]
bytes are already supported as valid units, the collector just needs to send `B`. You can see all the conversions in https://github.com/netdata/netdata/blob/master/web/gui/src/dashboard.js/units-conversion.js

**Comment by hexchain** [comment]
So, in order to use *bytes in all `net.<iface>` charts, I need to edit `[net.*].units` for all interfaces in the configuration file, right?

**Comment by mfundul** [comment]
> 
> 
> So, in order to use *bytes in all `net.<iface>` charts, I need to edit `[net.*].units` for all interfaces in the configuration file, right?

That is correct.

**Comment by vlvkobal** [comment]
@hexchain you can change units using one of these methods:
1) change units and divisors in `collectors/proc.plugin/proc_net_dev.c` and recompile netdata
    - change string "kilobits/s" to unit you want
    - change corresponding multipliers and divisors:
```
rrddim_add(d->st_bandwidth, "received", NULL,  8, BITS_IN_A_KILOBIT, RRD_ALGORITHM_INCREMENTAL)
                                              ^^^^^^^^^^^^^^^^^^^^^^
```
2) change `divisor` for every dimension and `units` for every chart as @ktsaou wrote in [this comment](https://github.com/netdata/netdata/issues/2425#issuecomment-314849779)
