### ISSUE TITLE
Feature Request: FireQOS & Prometheus Class Integration

### ISSUE THREAD

**Issue by GitStoph** [firehol/netdata#2426]
Request: class intregration into the prometheus API scrape.
Example:
![image](https://user-images.githubusercontent.com/20820226/27918085-811bde60-6233-11e7-8c3e-d0a62e0edf3c.png)
Netdata in the live dashboard does a fantastic job parsing the name of the class created in FireQOS to give the charts a nice meaningful label.
![image](https://user-images.githubusercontent.com/20820226/27918142-acd840c0-6233-11e7-9b2d-b2ef2033cd72.png)
However, in the API page from /host/<hostname>/api/v1/allmetrics?format=prometheus, it looks more like this.

Since it is not typically practical (in my environment at least?) to have the exact same fireqos rules across all of my servers, it'd be great if the API format that prometheus scraped could also parse the name of the class. Basically, no more tc_ens192_ifb_20_. Instead if it had something meaningful like AdminSubnet, SNMP, etc, then when I was creating my Grafana templates/dashboards, they could be used for all servers as long as the rule was given the same name whenever it was in use across any server?

I hope I'm explaining my request adequately.. Another example may be something like, I have a memcached rule to match port 11211 on server A that parses as rule tc_ens192_ifb_11_. On server B, it happens to be rule tc_ens192_ifb_14_. As is, I could not hope to template this since `irate(tc_ens192_ifb_11_{exported_instance="serverA"}[10s])*8` would not match up with `irate(tc_ens192_ifb_14_{exported_instance="serverB"}[10s])*8`. It'd be nice to be able to use something like `irate(tc_ens192_ifb_memcached_{exported_instance="$host"}[10s])*8`. Then I'd be able to make a template for multiple servers without making a million dashboards.

Would this be helpful to anyone else? It could potentially be used for other DB types/scraping methods? I'm not sure how difficult this would be to code, but I know it'd be extremely helpful for our environment!

Thanks for the great work!

**Comment by ktsaou** [comment]
Nice idea.
Implemented it in PR #2430 
To test it before merge, install `https://github.com/ktsaou/netdata`

**Comment by ktsaou** [comment]
merged it
