### ISSUE TITLE
Alarm thresholds are mixed for the same charts but different alarms

### ISSUE THREAD

**Issue by Jetman80** [firehol/netdata#2429]
Hi!
`My netdata version: 1.6.0-630-gd808708_rolling`

I want to make higher thresholds for some of disks on the server.
Alarm config:
```
health.d/custom/disk_1.conf:
# 60min disk_util alarm for dm-2 with normal thresholds
   alarm: 60min_disk_utilization
      on: disk_util.dm-2
  lookup: average -60m unaligned
   units: %
   every: 1m
   **green: 90
     red: 98**
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: the percentage of time the disk was busy, during the last 60 minutes
      to: sysadmin

# catch standard disk_util alarm template for dm-2 with unreal thresholds
   alarm: 10min_disk_utilization
      on: disk_util.dm-2
  lookup: average -10m unaligned
   units: %
   every: 1m
   **green: 200
     red: 200**
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: the percentage of time the disk was busy, during the last 10 minutes
      to: sysadmin
```

Live alarm config from the server shows thresholds as they should be:
```
:19999/api/v1/alarms?all output:
                "disk_util.dm-2.60min_disk_utilization": {
                        "id": 1496946062,
                        "name": "60min_disk_utilization",
                        "chart": "disk_util.dm-2",
                        "family": "dm-2",
...
                        **"green":90,
                        "red":98,**
                        "value":94.70965
                },
               "disk_util.dm-2.10min_disk_utilization": {
                        "id": 1496945860,
                        "name": "10min_disk_utilization",
                        "chart": "disk_util.dm-2",
                        "family": "dm-2",
...
                        **"green":200,
                        "red":200,**
                        "value":94.31286
                },
```

But the web site shows different thresholds:
<img width="438" alt="browser_2017-07-07_16-42-17" src="https://user-images.githubusercontent.com/28017144/27960577-77814a1e-6334-11e7-8066-29f96ae9cb31.png">

Apparently, it takes thresholds from the first chart if the names of charts are the same for several alarms.I tried to change alarms order - always first thresholds are taken.

**Comment by ktsaou** [comment]
Hi, `red` and `green` thresholds are per chart. I plan to visualize them on the dashboard (add red and green lines on the charts). So, the first alarm that defines them is the winner.

So, I suggest to leave one set as the chart standard (which will eventually get visualized) and on the second alarm instead of using `$red` and `$green`, use the absolute numbers directly.

Let me check if the docs say the above...

**Comment by ktsaou** [comment]
It did not. I added it now: https://github.com/firehol/netdata/wiki/health-configuration-reference#the-format

Thank you for pointing it out.

**Comment by Jetman80** [comment]
Thanks, now it's clear.

**Comment by startryst** [comment]
> Hi, `red` and `green` thresholds are per chart. I plan to visualize them on the dashboard (add red and green lines on the charts). So, the first alarm that defines them is the winner.
> 
> So, I suggest to leave one set as the chart standard (which will eventually get visualized) and on the second alarm instead of using `$red` and `$green`, use the absolute numbers directly.
> 
> Let me check if the docs say the above...

@ktsaou Is the green/red threshold visualized on the dashboard, or not yet? I'm running on v1.19.0-90-nightly, and set the green and red with different values(which equal to the value of warn/critcal), but nothing show-up on the dashboard.

**Comment by ilyam8** [comment]
Hi @startryst 

>  Is the green/red threshold visualized on the dashboard, or not yet?

No, they aren't.
