### ISSUE TITLE
Prometheus export: instance value should not replace dots with underscores

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2432]
Prometheus export currently generates only one label: `{instance="<hostname>"}`

At the moment the hostname is [squashed](https://github.com/ktsaou/netdata/blob/6bd9fe43cf00d9522ca5437f1b13e91e3a718621/src/rrd2json.c#L193) using `prometheus_name_copy`, which in particular replaces dots with underscores. However this should not be done.

Whilst prometheus [permits](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) only a small subset of characters for metric names and label names, this is not true of label values: they can be any unicode characters (of which ASCII is a subset of course).

The only thing necessary is to [escape](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details) backslash, double quote and newline, by prepending them with a backslash.  It would of course be unusual for a hostname to contain those characters, but you may as well be safe.

-----

Aside: currently the metric name is [assembled](https://github.com/ktsaou/netdata/blob/6bd9fe43cf00d9522ca5437f1b13e91e3a718621/src/rrd2json.c#L227) from chart and dimension, so these *do* still need to be squashed.  Should this change to a series of labels, then the label names must be from the safe set but the label values can be any unicode values.

**Comment by ktsaou** [comment]
ok, I am fixing it now.

**Comment by ktsaou** [comment]
ok, here it is. In PR #2430

**Comment by candlerb** [comment]
Thanks; I don't think the logic is quite right but I've left a comment with the details.

At the moment you are using one function (`prometheus_name_copy`) for two different purposes - for copying parts of the metric name (which *cannot* have a dot), and for copying the hostname into a label value (which *can* have a dot).

**Comment by ktsaou** [comment]
merged it
