### ISSUE TITLE
Alarm back to normal notification

### ISSUE THREAD

**Issue by CGreenburg** [firehol/netdata#2434]
This is a feature request. After an alarm is triggered (e.g. CPU 10-min avg is over 75%) and is resolved (CPU 10-min average drops below 75%), a notification could be sent out saying the alarm has been resolved.

**Comment by CGreenburg** [comment]
Alright apparently this is already in place, it took a little bit for the back to normal notification to get sent out. See the screenshot:

<img width="656" alt="screen shot 2017-07-07 at 11 52 34 pm" src="https://user-images.githubusercontent.com/13036301/27982710-8e7861b8-636f-11e7-82f2-9bd1b14c468f.png">

Is there a reason it took nearly 30 minutes to get a back to normal response? It shows the notification time at 11:26 PM but I didn't receive it until 11:49 PM in Discord. Is this an issue with their servers and the message being delayed?

**Comment by ktsaou** [comment]
Hi,

netdata supports hysteresis on alarm notifications. Both `up` and `down`.
If you check the alarm definition on the dashboard, it says:

**hysteresis on recovery 15 minutes, multiplied by 1.5, up to 1 hour**

So, when the alarm recovers netdata will wait 15 minutes to send the recovery notification. If the alarm raises again in that timeframe it does not send again the alarm and increases the delay to 22.5 minutes. It continues up to 1 hour.

Without this, you should have received multiple alarms.

**Comment by CGreenburg** [comment]
Hi thanks for replying! I appreciate all of the work you have put into Netdata, it's truly an awesome tool.

I may have missed that in the documentation. Thanks for explaining that to me.
