### ISSUE TITLE
Fping Plugin Questions

### ISSUE THREAD

**Issue by hmmxp** [firehol/netdata#2437]
Dear All,

Have a few questions which i need some clarification

After adding the fping plugin to the netdata installation, i am seeing 3 graphs which i need some clarification

1. Latency - is this the measurement of RTT?
2. Quality - what does this graph measure?
3. Packets - what does this graph measure?

How can i create a custom graph to measure packet loss percentage? What is the calculation for packet loss?

Thank You All

**Comment by ktsaou** [comment]
1. yes, rtt as min, average and max
2. packet success % (the opposite of packet loss %)
3. number of packets sent and received within each period

**Comment by hmmxp** [comment]
How can i create a custom graph to measure packet loss percentage? What is the calculation for packet loss?

**Comment by ktsaou** [comment]
These are directly exposed by fping 3.6+ with option `-N`. There are alarms that measure and report packet loss: https://github.com/firehol/netdata/blob/34b88ccc826aec4c38ce6994e0c6f715d70faf15/conf.d/health.d/fping.conf#L39-L52

**Comment by hmmxp** [comment]
Meaning To Say, To Measure Packet Loss

# other fping options - these are the defaults
fping_opts="-R -b 56 -i 1 -r 0 -t 5000"

This Portion

# other fping options - these are the defaults
fping_opts="-R -b 56 -i 1 -r 0 -t 5000 -N"

And Netdata will automatically create the graph?

**Comment by ktsaou** [comment]
No. I just described that fping controls the charts that are created.

If you just want to enable fping for your hosts, edit `/etc/netdata/fping.conf`, and set `hosts="host1 host2 host3"`, like the file instructs. Restart netdata and you are done.
 
You should change `fping_opts` only if you know what you are doing.

**Comment by hmmxp** [comment]
End Day, How Can I Add 1 More Custom Chart To Display Packet Loss? I Know There Is Alarm But This Is Not What I Want, I Just Need 1 More Chart To Display Packet Loss

How Do I Do So?

**Comment by ktsaou** [comment]
Sorry, you can't without altering the source code of `fping`.
The exact opposite is available as a chart: link quality (so instead of 1% packet loss, you have 99% quality).

**Comment by hmmxp** [comment]
Hi ktsaou,

Much Appreciated With Your Response, After Thinking Through This Is Actually A Better Way To Do Looking At Quality.

Before I Close This Question, Can I Confirm The Calculation of Quality?

If Sent Packet is 5 and Receive Packet is 5, Quality Will Return 100%

But I Saw Sent Packet is 5 and Receive Packet is 4, Quality Returns 80%

How Does The Calculation Works?

Thank You

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1200

**Comment by hmmxp** [comment]
Still Do Not Understand, Means This Is FPing Bug and I Have To Run /usr/libexec/netdata/plugins.d/fping.plugin install and See Any New Version?

**Comment by hmmxp** [comment]
Also What Is The Recommended Configuration for fping? Should I Leave Deafult?

ping_every = 200

fping_opts = -R -b 56 -i 1 -r 0 -t 5000

Is The Demo Site Using The Same Configuration As Above?

**Comment by ktsaou** [comment]
> Still Do Not Understand, Means This Is FPing Bug and I Have To Run

Well... fping calculates quality. fping also reports packets sent and received. The 2 does not necessarily match under all conditions, since there are timing issues and preferences made by the fping developers. Based on my experience, I would suggest to mostly ignore the packets chart. Focus on quality and latency.

> I Have To Run /usr/libexec/netdata/plugins.d/fping.plugin install and See Any New Version?

No. Installing fping using the netdata plugin is not required. If you have a netdata compatible fping, everything is good.

> Also What Is The Recommended Configuration for fping? Should I Leave Default?

Yes, unless you know what you are doing. The default is good enough to detect failures and latency variations quickly.

**Comment by hmmxp** [comment]
Thank You KT For All Clarification
