### ISSUE TITLE
chart question

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2439]
Hello,

I was wondering what was the type of the ram chart in system overview.
I want to do a similar chart for a custom plugin, I tried every type of chart but I don't get the same result. 
Thanks for your help !

**Comment by ktsaou** [comment]
`stacked`. 3 types are currently supported: `line`, `area` and `stacked`.

**Comment by cgoze** [comment]
I tried stacked but I don't get the colored areas under the value of the metrics as it is in the ram chart. Here's a screenshot of my dashboard

![capture d ecran 2017-07-10 a 14 35 02](https://user-images.githubusercontent.com/29546231/28018381-66c99a96-657d-11e7-954a-7fdb439ffed6.png)

**Comment by ktsaou** [comment]
This is a line chart. Most probably you have misspelled it and netdata fallbacks to line.
When you change that, you have to restart netdata.

**Comment by cgoze** [comment]
I checked the spelling and restart netdata I still have the same thing

**Comment by ktsaou** [comment]
Please post the CHART line of your custom plugin.
It is probably in the wrong position or something.

**Comment by cgoze** [comment]
> CHARTS = {
        'normal.q_long.q': {
                'options': [None, "normal.q & long.q", "coeurs", 'coeurs sur normal.q & long.q', None,     'stacked',3000],
                'lines': [
                        ['coeurs_nl', 'used', 'absolute'],
                        ['coeurs_avl_nl', 'avail', 'absolute'],
                        ['coeurs_res_nl', 'reserved', 'absolute'],
        ]},

	'web.q': {
                'options': [None, "web.q", "coeurs", 'web.q', None, 'stacked', 3000],
                'lines': [
                        ['coeurs_web', 'used', 'absolute'],
                        ['coeurs_avl_web', 'avail', 'absolute'],
                        ['coeurs_res_web', 'reserved', 'absolute'],
        ]},

	'bigmem.q': {
                'options': [None, "bigmem.q", "coeurs", 'bigmem',None, 'stacked', 3000],
                'lines': [
                        ['coeurs_big', 'used', 'absolute'],
                        ['coeurs_avl_big', 'avail', 'absolute'],
                        ['coeurs_res_big', 'reserved', 'absolute'],
                ]}
}

**Comment by ktsaou** [comment]
ok, sorry... I meant to run it by hand and post here the output. Like:

```sh
# /usr/libexec/netdata/plugins.d/python.d.plugin 1 2>/dev/null | grep ^CHART
CHART cpu.cpufreq '' 'CPU Clock' MHz cpufreq '' line 90000 1
CHART netdata.plugin_pythond_cpufreq '' 'Execution time for cpufreq plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
CHART sensors.pch_skylake-virtual-0_temperature '' 'pch_skylake-virtual-0 temperature' Celsius temperature sensors.temperature line 90000 1
CHART sensors.acpitz-virtual-0_temperature '' 'acpitz-virtual-0 temperature' Celsius temperature sensors.temperature line 90001 1
CHART sensors.coretemp-isa-0000_temperature '' 'coretemp-isa-0000 temperature' Celsius temperature sensors.temperature line 90002 1
CHART sensors.dell_smm-virtual-0_temperature '' 'dell_smm-virtual-0 temperature' Celsius temperature sensors.temperature line 90003 1
CHART sensors.dell_smm-virtual-0_fan '' 'dell_smm-virtual-0 fans speed' Rotations/min fans sensors.fan line 90004 1
CHART netdata.plugin_pythond_sensors '' 'Execution time for sensors plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
CHART routes_default.routes_v4 '' 'IPv4 Routes' 'routes found' ipv4 routes.routes_v4 line 60000 5
CHART netdata.plugin_pythond_routes_default '' 'Execution time for routes_default plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 5
CHART postfix_local.qemails '' 'Postfix Queue Emails' emails queue postfix.qemails line 60000 10
CHART postfix_local.qsize '' 'Postfix Queue Emails Size' 'emails size in KB' queue postfix.qsize area 60001 10
CHART netdata.plugin_pythond_postfix_local '' 'Execution time for postfix_local plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 10
CHART cpu.cpu0_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90000 1
CHART cpu.cpu1_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90001 1
CHART cpu.cpu2_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90002 1
CHART cpu.cpu3_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90003 1
CHART cpu.cpu4_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90004 1
CHART cpu.cpu5_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90005 1
CHART cpu.cpu6_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90006 1
CHART cpu.cpu7_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90007 1
CHART netdata.plugin_pythond_cpuidle '' 'Execution time for cpuidle plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
```

of course, only for your plugin.

**Comment by cgoze** [comment]
I have this output :
> 2017-07-10 16:06:07: python.d INFO: CHECKED OK: SGE
CHART SGE.normal.q_long.q '' 'normal.q & long.q' coeurs 'coeurs sur normal.q & long.q' stacked 3000 300000 1
CHART SGE.web.q '' web.q coeurs web.q stacked 3000 300001 1
CHART SGE.bigmem.q '' bigmem.q coeurs bigmem stacked 3000 300002 1
CHART netdata.plugin_pythond_SGE '' 'Execution time for SGE plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1

**Comment by ktsaou** [comment]
ok, the problem is this:

one of my output:
CHART cpu.cpu0_cpuidle '' 'C-state residency' time% cpuidle '' stacked 90000 1

one of your output:
CHART SGE.web.q '' web.q coeurs web.q stacked 3000 300001 1

As you can see `stacked` is in the wrong position. it should be 3rd from the end, but it is fourth.

**Comment by cgoze** [comment]
So how can I do to correct it ?

**Comment by ktsaou** [comment]
I don't know. @l2isbad any ideas?

**Comment by l2isbad** [comment]
'bigmem.q': {
            'options': [None, 'bigmem.q', 'coeurs', 'bigmem','bigmem.bigmem', 'stacked'],
            'lines': [
                    ['coeurs_big', 'used', 'absolute'],
                    ['coeurs_avl_big', 'avail', 'absolute'],
                    ['coeurs_res_big', 'reserved', 'absolute'],
            ]}

**Comment by cgoze** [comment]
Thanks very much it's working now !
I have another question, in the cpu chart in the section system overview, the vertical scale is always from 0 to 100 whatever is the cpu value, how can I reproduce it ?

**Comment by ktsaou** [comment]
Charts information is stored at /usr/share/netdata/web/[dashboard_info.js](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js).

For custom plugins you can create a new such file (there is /usr/share/netdata/web/[dashboard_info_custom.example.js](https://github.com/firehol/netdata/blob/master/web/dashboard_info_custom_example.js) you can use to start with).

You have to copy it under a new name, so that it will not be overwritten with netdata updates.

To configure your file set in netdata.conf:

```
[web]
   custom dashboard_info.js = your_file_name.js
```

To find what you have to add, search for a chart that already does what you need, in `dashboard_info.js` and copy and paste the relevant entries to your file.

**Comment by ktsaou** [comment]
updated the wiki page: https://github.com/firehol/netdata/wiki/Overview#customizing-the-standard-dashboards with the info above.

**Comment by cgoze** [comment]
Ok thanks or your help ! Great work you've done with netdata :)

**Comment by ktsaou** [comment]
> great work you've done with netdata :)

thanks! Its users are the driving force to make it better. so share the word...

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
