### ISSUE TITLE
moving install ?

### ISSUE THREAD

**Issue by centminmod** [firehol/netdata#244]
What's the recommended process for moving an existing netdata install from default installed directory to a new one ? Keeping configuration intact ? i.e. nginx path to status stub ?

so from
`./netdata-installer.sh`
to
`./netdata-installer.sh --install /opt`

**Comment by ktsaou** [comment]
The internal compilation defaults are all editable in `netdata.conf`. So, you can just move it and edit the config file to set the new path in all variables the old is referenced (and of course uncomment them).

The easiest though would be:

1. re-install to the new location
2. copy `/etc/netdata` from the old to the new (even if you edited your config, most probably you haven't uncommented the paths, so the old config will probably be ok in the new location too).
3. if you have installed custom plugin, copy them too (the plugins should not have any hardcodes paths)
4. If you want to keep your data, copy `/var/cache/netdata` too.
5. start netdata from the new location
6. download the config again from the server (just to have the commented variables with the right paths)

**Comment by ktsaou** [comment]
updated my answer

**Comment by ktsaou** [comment]
is this ok to close?

**Comment by centminmod** [comment]
thanks @ktsaou 

yup ok to close
