### ISSUE TITLE
[Question] Which netdata backend is best on armhf?

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2440]
I am running netdata on a Beaglebone black which has 512mb ram. Which is the best backend?

Unless I am mistaken, it seems like opentsdb and graphite backends are heavy. While json dbs on armhf are not well supported generally speaking. 

Happy to hear recommendations if anyone has a tried and tested solution with netdata!

**Comment by ktsaou** [comment]
netdata does not need a backend. You need it only if you plan to query the metrics with another visualizer (e.g. grafana).
For 512MB RAM... hm... it will be tough to find one...

**Comment by elfgoh** [comment]
I plan to store the queries and send back certain metrics, perhaps when certain thresholds are triggered. Perhaps then it is unwise to have the backend locally. I am guessing it is possible to have  remote backend?

**Comment by elfgoh** [comment]
@ktsaou I am wondering if it is possible to use sqlite since it seems like it can be used to store json content https://sqlite.org/json1.html

I suspect this can be supported with 512mb ram.

**Comment by ktsaou** [comment]
What are you trying to do?

The best would probably be to use netdata with `memory mode = map` and give it enough disk space. netdata will be very happy with 512MB RAM.

**Comment by elfgoh** [comment]
The simplified use case is to just let netdata be a collector of metrics have it stored locally. `memory mode = map` seems like a possible solution and I will look at it more deeply later.

Or are there other alternatives?

**Comment by elfgoh** [comment]
```
We suggest not to use this mode on nodes that run other applications. There will always be dirty memory to be synced and this syncing process may influence the way other applications work. 
```

We do have other applications running on the device, therefore `memory mode = map` seems unsuitable

**Comment by Ferroin** [comment]
That may not have as much impact as you might think, providing your other applications aren't constantly accessing the disks themselves.

Also, on the specific note of Graphite, you don't have to run the whole stack, you can just run Carbon (the storage component) on that system and run the graphing front-end elsewhere to save quite a lot of space in memory.

**Comment by elfgoh** [comment]
As an update, I installed [prometheus as a backend](https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus) since it is recently supported in netdata.

It seems to be running fine on the Beaglebone Black

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
