### ISSUE TITLE
Proxy/Relay question?

### ISSUE THREAD

**Issue by LeeNX** [firehol/netdata#2441]
Greetings .. I have a question that I think I know the answer too, but would like confirmation.  
  
I have a netdata install behind a very slow uplink, which I currently access via a secure nGinx reverse proxy, but I believe that this becomes very bandwidth limited if more than one users visit the public facing side.  
  
I have read that netdata's streaming is not really an HTTP standard stream (might be the wrong terms) and that nGinx nor Varnish or other reverse proxies can really cache/proxy the stream.  
  
Can somebody confirm, that netdata and it's on-demand metric streaming the best proxy for netdata. ie public -> netdata -> slow-uplink -> netdata the best solution?  
  
Thanks

**Comment by ktsaou** [comment]
Hi, yes the streaming protocol of netdata is not http proxy friendly. The 2 netdata have to talk directly.
So, if you mirror your netdata to a public place outside your slow uplink, users will be hitting your public netdata. The private netdata will use about 300kbps of your uplink to mirror its metrics to the public netdata (it is 300kbps per netdata mirrored). If you set up a VPN, you can compress that to about 1/3. Of course the bandwidth depends on the number of metrics mirrored. So, you have to test it.

**Comment by LeeNX** [comment]
Thanks @ktsaou for your quick reply!  
  
The slow uplink is only 256kbs and that is for network usage too, so been able to access the isolated netdata instance seems unlikely.  
  
Currently accessed over a VPN, but have not measured the amount of bandwidth saved because of the VPN, don't expect to save too much, seen that the encryption will add overhead.  
  
Was hoping that the public netdata instance would only stream the metrics been viewed and not all the metrics, but that is why I asked this question.  
  
All public netdata visitors will only need access to metrics once? ie 10 users but only netdata to netdata metric streamed once

**Comment by ktsaou** [comment]
> All public netdata visitors will only need access to metrics once? ie 10 users but only netdata to netdata metric streamed once

yes, but all the metrics of the private netdata will be streamed to the public one.
You can disable the metrics you don't need though. Just configure the plugins of the private netdata and enable only those that you need.

**Comment by LeeNX** [comment]
Thanks ...  
  
Mmm, last crazy question today before I try and put any of this to the test.  
  
Is it possible, other than running two netdata instances on the private side, to only stream selected metrics? I am thinking that I would like to keep all the pretty metrics for viewing as many metrics in the private network, but only selected metrics for public abuse ...

**Comment by ktsaou** [comment]
> Is it possible, other than running two netdata instances on the private side, to only stream selected metrics?

unfortunately, not currently.

**Comment by LeeNX** [comment]
Thanks @ktsaou , I believe you have answered my questions.  
  
I had expected as much, but confirmation has saved me some time.  
    
This question can be closed.
