### ISSUE TITLE
dashboard config load problem

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2445]
Hello,

I have this error message every time I refresh my netdata dashboard : 
> Cannot load required JS library: http://195.221.173.202:19999/dashboard_info.js?v20170530-1

What does that mean ?

**Comment by ktsaou** [comment]
Does the file `/usr/share/netdata/web/dashboard_info.js` exist?

Please post `ls -l /usr/share/netdata/web/dashboard_info.js`

**Comment by cgoze** [comment]
> -rw-r--r-- 1 netdata netdata 71773 Jul 11 15:29 dashboard_info.js

**Comment by ktsaou** [comment]
This is probably a corrupted file. The original is:

```sh
# ls -l /usr/share/netdata/web/dashboard_info.js
-rw-rw-r--. 1 netdata netdata 71462 Jul 10 14:49 /usr/share/netdata/web/dashboard_info.js
```

How did you install it?
Could you please re-install netdata?

**Comment by cgoze** [comment]
Same problem

**Comment by cgoze** [comment]
Somehow it solved itself, thanks :)

**Comment by ktsaou** [comment]
ok, nice.
