### ISSUE TITLE
Enable keepalive on UrlService

### ISSUE THREAD

**Issue by Wing924** [firehol/netdata#2446]
UrlService open http connection every seconds.
Because keepalive is off, TCP sockets are not reused.
It cause so many TIME_WAIT sockets.

I think make keepalive on can improve performance.

**Comment by ktsaou** [comment]
@l2isbad have a look please.

**Comment by l2isbad** [comment]
I am not sure this can be implemented using urllib2 w/o additional packages or something.

**Comment by ktsaou** [comment]
hm... this is a big problem though. I hadn't realized we work like that...
I read about urllib3 and other alternatives.
Why do they bother you?

**Comment by l2isbad** [comment]
Well, the main goal was to make it work on all installs out from the box without additional installing i think. urllib3 is not default package on debian <= 7

**Comment by ktsaou** [comment]
hm... yes we have to support older systems.

Can we use urllib3 only when it is available?
Can we ship urllib3 with netdata? (if it is python-only without any dependencies, this could be easy)

**Comment by l2isbad** [comment]
I like the idea to switch to the urllib3

**Comment by ktsaou** [comment]
ok, I mark as enhancement, assigned to you.
Thanks!

**Comment by ktsaou** [comment]
merged it
