### ISSUE TITLE
Doesn't detect Mongo database after stopping and starting Mongo service

### ISSUE THREAD

**Issue by jnogol** [firehol/netdata#2450]
Hi, I'm monitoring a host with a Mongo database on it and, testing if alarming was working properly, I stopped the service (using either `service mongod stop` or `systemctl stop mongod.service`) and, instead of alarming me of it, Netdata just "forget" there is a Mongo database and, when I restart the service, it just ignores it. 

Anyone here faced the same issue?

**Comment by ktsaou** [comment]
I don't have mongodb handy. @l2isbad could you please check?

**Comment by l2isbad** [comment]
works without problems for me (stop/start/restart mongdodb.service)

btw found some bugs looking through the code
like

https://github.com/firehol/netdata/blob/master/python.d/mongodb.chart.py#L361-L362

dimension id's must be: oplog_r, oplog_w

**Comment by ktsaou** [comment]
@l2isbad , would you like to make a PR (remember the elasticsearch one)?

**Comment by ktsaou** [comment]
@l2isbad I am planning to release 1.7 this weekend, so if you have any pending items please try to close them in the next few days...

**Comment by jnogol** [comment]
mmmm, this is weird, it just started to work. 

Watching the error log, looks like the connection to Mongo was refused (either Mongo itself refused it or the port wasn't available) in the first attempt and that's why Netdata couldn't scrape any metrics from it. As you can see in the test (restarting at the same time Mongod and Netdata) I did an hour ago:

```
2017-07-13 09:03:15: python.d ERROR: mongodb_local [Errno 111] Connection refused
2017-07-13 09:03:15: python.d ERROR: mongodb_local check() failed - disabling job
2017-07-13 09:03:15: python.d ERROR: DISABLED: mongodb/local
```

I took a glance over `python.d/mongod.conf` and `netdata.conf` and couldn't find any "retry policy". Has Netdata something like this? In case it hasn't, IMO it could be helpful if, instead of giving up at the very first attempt, it tries a few times (a scenario comes to my mind: I restart the host, and, for some reason, Mongo is slower than Netdata to startup and then there's no scraping Mongo metrics).

**Comment by ktsaou** [comment]
If netdata manages to collect metrics from a source when it starts, it will never retire until it is restarted. Of course, as time passes and the source is not available, it slows down the checks.

So, the key is to collect metrics when it starts.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
