### ISSUE TITLE
Netdata doesn't detect Redis service is down

### ISSUE THREAD

**Issue by jnogol** [firehol/netdata#2451]
Hi,

I have a host with three different Redis services. Netdata detects the three of them and monitors them and take metrics smoothly, but if I stop any of the three services, it still "thinks" they're up. Why can be this happening?

**Comment by ktsaou** [comment]
So, the charts of the stopped redis server are still been updated with data?

**Comment by jnogol** [comment]
Exactly, it shows constant values instead of null ones. But the services are stopped.

I'm using Debian 8, Redis 3.2.9, if it helps.

**Comment by ktsaou** [comment]
@l2isbad could you please check this?

**Comment by l2isbad** [comment]
I believe i did such tests when fixing https://github.com/firehol/netdata/issues/2177 (on debian 8!)

but sure i have to re-check. Will do later 😄

**Comment by l2isbad** [comment]
Ok, i did some tests and all is fine. 
![screenshot_20170713_234204](https://user-images.githubusercontent.com/22274335/28171912-ec4d9506-6824-11e7-9323-7395171e9a02.png)

> Exactly, it shows constant values instead of null ones. But the services are stopped.

The chart is frozen. It has no gaps until the service restarting (look at the time).

![screenshot_20170713_234126](https://user-images.githubusercontent.com/22274335/28172021-42f71d00-6825-11e7-8b97-7ab388dc9639.png)

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.
