### ISSUE TITLE
[Question] smooth and straight lines

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2452]
Just a general question: why are some of the lines straight and some smoothed?

e.g. network Kb/s is straight, network packets/s is smoothed. This is clearer when zoomed in.

![image](https://user-images.githubusercontent.com/44789/28119201-e4d651f6-670b-11e7-8e7f-bea54553376e.png)

**Comment by ktsaou** [comment]
Limitation of dygraphs. It supports smooth lines only for line charts. It cannot do it for area and stacked charts.

**Comment by candlerb** [comment]
Thank you 👍
