### ISSUE TITLE
FreeNAS-11 (There but not working?)

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [firehol/netdata#2460]
So looking for this to work on my new FreeNAS build (which is running FreeNAS-11.0 Stable) I noticed it was built for "Corral" which is essentially a scrapped project...

Anyway, I decided to see if it would still work (thus included) and it is...sort of.

The commands prompted aren't correct. You must edit /etc/rc.conf and add
netdata_enabled="YES"

then when you try and start, you get this output:
Starting netdata.
su: unknown login: netdata
/usr/local/etc/rc.d/netdata: WARNING: failed to start netdata

Issue is, do I REALLY have to create a net login just for netdata? 

Solution: Yes...almost.

Create a user etc, and now I get
Blah # service netdata start
 Starting netdata.

but alas

Blah # service netdata status
 netdata is not running.

**Comment by ktsaou** [comment]
Unfortunately, I don't use freenas.
@jordanhubbard could you please help?

**Comment by xfakt-pj** [comment]
If I am not mistaken @jordanhubbard is not working on the Freenas project anymore. Freenas Corral is indeed scrapped and the 'original' freenas line is continued, so it would be useful to port netdata to that line.

**Comment by xfakt-pj** [comment]
If installing netdata on freenas directly is not a viable option for some reason we can maybe use the graphite exporter that comes with Freenas by default, and send this data to netdata. Maybe a bit out there, just an idea.

**Comment by ktsaou** [comment]
Well... the freenas team has customized netdata for inclusion in freenas, so I guess you should open a ticket on their ticketing system to get this fixed.

Adding a graphite listener in netdata is a nice idea, but it does not exist yet.

**Comment by jordanhubbard** [comment]
@xfakt-pj is unfortunately correct - I am no longer involved in any way with FreeNAS.  That project is dead to me.  💀 😄

**Comment by ktsaou** [comment]
sad news.
@xfakt-pj I suggest to open an issue at freenas ticketing. I don't see how I can help. The folks at freenas know what to do to fix this issue.

**Comment by xfakt-pj** [comment]
Oh it's not something I specifically need, just pitching in with some info ;)

**Comment by BrickerBrickerOneNine** [comment]
So....

**Comment by peterrus** [comment]
So this is something I am afraid you have to pick up the folks @ freenas.

**Comment by BrickerBrickerOneNine** [comment]
Ok thanks

**Comment by ktsaou** [comment]
I am very sorry, but I don't think we can do anything to fix netdata on freenas. It is up to the freenas team to do it. They already know how to do it.

**Comment by ktsaou** [comment]
Cleaning up. If there is anything we can do to help, let me know.
