### ISSUE TITLE
New plugin to display a specific process metrics ?

### ISSUE THREAD

**Issue by rahulpathakgit** [firehol/netdata#247]
I want to monitor a specific process with its CPU, mem usuage. I suppose I can write a new plugin for that.  Need some pointers, Where should I start,

**Comment by ktsaou** [comment]
If your process runs as a specific user or a specific group, this information is already there on your dashboard.

To isolate a process, the easiest way is to edit `/etc/netdata/apps_groups.conf` and add a group specific for your process. `apps.plugin` however may aggregate its children and possibly its direct parents to it. Check [this wiki page](https://github.com/firehol/netdata/wiki/Apps-Plugin). You can experiment with this. It might do your job.

Last, you can also develop your own plugin. Check this for pointers: https://github.com/firehol/netdata/wiki/External-Plugins#skeleton-plugins

**Comment by ktsaou** [comment]
Did you find a way to do it?

**Comment by rahulpathakgit** [comment]
Sorry , saw this message little late. Yes, my initial problem was solved with process groups. 
But I have another problem and I am still working on it. Problem is that in our system, we have a service manager, services/modules are implemented as shared objects. Service manager while bootup forks a process and load specific service shared object in it. This happens for every service.

When I use process group for any particular service in apps_groups.conf then chart displays the metrics of all the services spawned by service manager instead of that particular service. 

I don't understand why its happening, other service processes are not even in the hierarchy of the process which I am trying to profile.

Will it be a good idea to write a script to parse procfs for that specific service myself and hook it as a plugin to netdata?    or is there anything netdata can provide me out of the box to solve this problem?

**Comment by ktsaou** [comment]
I think you can do this with `apps_groups.conf`, but to help you further I would need some more information. If this is not sensitive info, you could post a `ps fax` and some info on how you want the processes grouped.
