### ISSUE TITLE
Copying Netdata charts 

### ISSUE THREAD

**Issue by Seretsi** [firehol/netdata#2472]
Hey team, I wanted to know how I could go about taking snap shots of charts produced in the netdata monitoring streams. This is just so things like reports can be compiled post monitoring.

**Comment by ktsaou** [comment]
Hi,

unfortunately this is not included yet.

If you need long term metrics, I suggest to install a time-series database and configure it as a backend to archive the metrics there.

Keep in mind netdata exposes the metrics in many formats (including csv, tsv, html, json, etc). It is also a google data provider (so you can fetch metrics in google sheets or google charts). Check the API: https://github.com/firehol/netdata/wiki/REST-API-v1

You can always download them with a single URL, but still archiving them at a time-series database is the mainstream method these days.

**Comment by Seretsi** [comment]
OK thanks a million.

**Comment by ktsaou** [comment]
Cleaning up. If there is anything we can do to help, let me know.
btw, this is related to #309
