### ISSUE TITLE
HAProxy Unix Socket

### ISSUE THREAD

**Issue by TimmyTossPot** [firehol/netdata#2475]
Firstly, awesome software, thank you :)

Secondly, I don't use Github so this maybe the wrong way to report the problem.

I was trying to use the unix socket option within the python plugin for HAProxy, unfortunately I receive the following error in the debug log:
a bytes-like object is required, not 'str'

I had to modify the base.py to send a byte object rather than a string by adding the .encode option to the send command of SocketService...

 def _send(self):
        """
        Send request.
        :return: boolean
        """
        # Send request if it is needed
        if self.request != self.__empty_request:
            try:
                self.debug("sending request:", str(self.request))
                self._sock.send(self.request.encode())
            except Exception as e:
                self._socketerror("error sending request:" + str(e))
                self._disconnect()
                return False
        return True

**Comment by l2isbad** [comment]
yes, you are right. It must be [bytes obj for python 3](https://docs.python.org/3/library/socket.html#socket.socket.send)

**Comment by ktsaou** [comment]
I am marking this as bug (right?)

**Comment by TimmyTossPot** [comment]
Correct. Fix provided as above.

**Comment by ktsaou** [comment]
merged the fix
