### ISSUE TITLE
install netdata failed in ubuntu

### ISSUE THREAD

**Issue by zhugw** [firehol/netdata#248]
Hi, 
    Right now I tried to install `netstat` in my compute(`ubuntu system`). 
```
➜  netdata git:(master) sudo ./netdata-installer.sh
checking for sin in -lm... yes
./configure: line 5030: syntax error near unexpected token `newline'
./configure: line 5030: `	PKG_CHECK_MODULES('

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:

1. The package zlib1g-dev has to be installed.

2. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required

3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

```
What's the problem? how to resolve it?

**Comment by 1c7** [comment]
have you run ``` apt-get install zlib1g-dev gcc make git autoconf autogen automake pkg-config ``` ？
according to https://github.com/firehol/netdata/wiki/Installation

**Comment by glensc** [comment]
according to error, pkgconfig macro not expanded from aclocal. incomplete configure generated. run autoreconf -vif after installing the deps should help regenerate configure script.

**Comment by zhugw** [comment]
Thanks! @glensc . I tried below way, I'm not sure if it's your real meaning. 
```
➜  netdata git:(master) sudo autoreconf -vif 
[sudo] password for zhuguowei: 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
autoreconf: running: /usr/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'

➜  netdata git:(master) sudo ./netdata-installer.sh
checking for inline... inline
checking for sin in -lm... yes
./configure: line 5030: syntax error near unexpected token `newline'
./configure: line 5030: `	PKG_CHECK_MODULES('

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
but still have the same error

**Comment by glensc** [comment]
you do not seem to have pkg-config installed and your second paste does not show that you installed it or what is it's version or package contents

**Comment by ktsaou** [comment]
Did you fixed it?

**Comment by paulfantom** [comment]
@zhugw is it fixed?

**Comment by ktsaou** [comment]
I think this is ok. I am testing netdata on ubuntu LTS releases 10.4, 12.4, 14,4, 16,4, so it should work.

**Comment by paulfantom** [comment]
> ubuntu LTS releases 10.4

@ktsaou I think 10.4 isn't supported by Canonical for at least a year.
Great job with cleaning up issues. :+1:

**Comment by ktsaou** [comment]
> Great job with cleaning up issues.

Thanks! I followed your lead...

**Comment by jarodlee** [comment]
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'   
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->



Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues


I am install netdata at ubuntu 20.04,but show this error....hope someone help how to fixit.

**Comment by ktsaou** [comment]
@jarodlee we have binary packages now for ubuntu. You don't need to compile netdata.
Check this: https://learn.netdata.cloud/docs/agent/packaging/installer/
