### ISSUE TITLE
Support for Oracle Linux

### ISSUE THREAD

**Issue by schindlerd** [firehol/netdata#2480]
Hi,

we are using Oracle Linux but installer fails at recognizing OS release:
 --- Install netdata at system init ---
I don't know what init file to install on system 'ol-6.9'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service.

I guess the $key variable from functions.sh should match the ID and VERSION_ID.

This is an example content of /etc/os-release:
NAME="Oracle Linux Server"
VERSION="6.9"
ID="ol"
VERSION_ID="6.9"
PRETTY_NAME="Oracle Linux Server 6.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:6:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6"
ORACLE_BUGZILLA_PRODUCT_VERSION=6.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=6.9

Thanks a lot :)

**Comment by ktsaou** [comment]
merged it.
