### ISSUE TITLE
Add Path on netdata.service unit file on CoreOS

### ISSUE THREAD

**Issue by ximbal** [firehol/netdata#2484]
I will begin this by saying that I have the restriction to use CoreOS.

I am unable to load any Python plugin, because Python was not installed, I managed to installed it in /opt and I need to change the $PATH to see inside /opt so I can actually load the Python Plugin, I noticed that the user (netdata) is a user that basically controls the daemon/service (netdata.service unit), it has no home.  

After doing some reading I am able to "alter" the Environment Variables using an Environment Directive on my Unit File, however, it does not seems to be working. Do you have any idea on how to achieve this so that netdata can find the python executable and then load the plugins that use python.d???

I know this is not  a pure NetData question and probably has more to do with CoreOS but for the sake of documentation I am posting it here on the hopes someone will point me in the right direction.

Thank you.
EN

**Comment by ximbal** [comment]
2017-07-19 19:04:42: netdata INFO : Adjusted my Out-Of-Memory score to '1000'.
      2 2017-07-19 19:04:42: netdata ERROR: Cannot adjust netdata scheduling policy to idle (5), with priority 0. Falling back to nice (errno 38, Function not implemented)
      3 2017-07-19 19:04:42: netdata INFO : netdata started on pid 4264.
      4 2017-07-19 19:04:42: netdata INFO : Host 'ip-172-31-31-223.ca-central-1.compute.internal' (at registry as 'ip-172-31-31-223.ca-central-1.compute.internal') with guid 'd93fa        fde-6b09-11e7-b563-0231412bbd89' initialized, os linux, tags '', update every 1, memory mode save, history entries 3996, streaming disabled (to '' with api key ''), health         enabled, cache_dir '/opt/netdata/var/cache/netdata', varlib_dir '/opt/netdata/var/lib/netdata', health_log '/opt/netdata/var/lib/netdata/health/health-log.db', alarms defau        lt handler '/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
      5 2017-07-19 19:04:42: netdata INFO : netdata initialization completed. Enjoy real-time performance monitoring!
      6 2017-07-19 19:04:42: netdata INFO : HEALTH thread created with task id 4277
      7 2017-07-19 19:04:42: netdata INFO : PLUGINS.D thread created with task id 4278
      8 2017-07-19 19:04:42: netdata INFO : Multi-threaded WEB SERVER thread created with task id 4279
      9 2017-07-19 19:04:42: netdata INFO : Listening on 'tcp:[0.0.0.0]:19999'
     10 2017-07-19 19:04:42: netdata INFO : Listening on 'tcp:[::]:19999'
     11 2017-07-19 19:04:42: netdata INFO : STATSD main thread created with task id 4280
     12 2017-07-19 19:04:42: netdata INFO : BACKEND: thread created with task id 4276
     13 2017-07-19 19:04:42: netdata INFO : BACKEND: thread exiting
     14 2017-07-19 19:04:42: netdata INFO : CGROUP Plugin thread created with task id 4275
     15 2017-07-19 19:04:42: netdata INFO : DISKSPACE thread created with task id 4274
     16 2017-07-19 19:04:42: netdata INFO : PROC Plugin thread created with task id 4273
     17 2017-07-19 19:04:42: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 4288
     18 2017-07-19 19:04:42: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 4289
     19 2017-07-19 19:04:42: netdata INFO : STATSD collector thread No 2 created with task id 4284
     20 2017-07-19 19:04:42: netdata INFO : POLLFD: LISTENER: listening on 'udp:[::1]:8125'
     21 2017-07-19 19:04:42: netdata INFO : POLLFD: LISTENER: listening on 'udp:[127.0.0.1]:8125'
22 2017-07-19 19:04:42: netdata INFO : POLLFD: LISTENER: listening on 'tcp:[::1]:8125'
     23 2017-07-19 19:04:42: netdata INFO : POLLFD: LISTENER: listening on 'tcp:[127.0.0.1]:8125'
     24 2017-07-19 19:04:42: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 4287
     25 2017-07-19 19:04:42: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' running on pid 4290
     26 2017-07-19 19:04:42: netdata INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' running on pid 4291
     27 2017-07-19 19:04:42: netdata INFO : IDLEJITTER thread created with task id 4272
     28 2017-07-19 19:04:42: netdata INFO : TC thread created with task id 4271
     29 2017-07-19 19:04:42: apps.plugin INFO : started on pid 4287
     30 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin: line 2: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found

**Comment by ximbal** [comment]
However Python is Installed, it has to do with the %PATH, which I am unable to set for the UNIT.

**Comment by ktsaou** [comment]
Hi,

edit `/opt/netdata/etc/netdata/netdata.conf` and set:

```
[plugins]
	PATH environment variable = /opt/python:WHATEVER IS ALREADY THERE
```

Then, restart netdata.
Of course uncomment the line and replace `/opt/python` with the right path to find the python binary.

I have tried to statically compile python as part of the netdata binary package. However I couldn't do it.

If anyone can provide a script to statically compile python v2 or v3, please post it here. I will be glad to add it to the binary netdata package.

**Comment by ximbal** [comment]
That worked with a slight tweak, adding to the $PATH Environment Variable the path for Python Binaries, so instead of adding `/opt/python`, I've added `/opt/python/bin`.

It does not compile directly from Python, but I managed to Install it with a script:

```
#!/bin/bash
# make directory
mkdir -p /opt/bin
cd /opt
wget http://downloads.activestate.com/ActivePython/releases/2.7.13.2714/ActivePython-2.7.13.2714-linux-x86_64-glibc-2.12-402178.tar.gz
tar -xzvf ActivePython-2.7.13.2714-linux-x86_64-glibc-2.12-402178.tar.gz

mv ActivePython-2.7.13.2714-linux-x86_64-glibc-2.12-402178 apy && cd apy && ./install.sh -I /opt/python/

ln -s /opt/python/bin/easy_install /opt/bin/easy_install
ln -s /opt/python/bin/pip /opt/bin/pip
ln -s /opt/python/bin/python /opt/bin/python
ln -s /opt/python/bin/virtualenv /opt/bin/virtualenv
```

Then added the Python Binaries path to:

```
[plugins]
	PATH environment variable = /opt/python/bin:WHATEVER IS ALREADY THERE
```

**Comment by ktsaou** [comment]
Cleaning up. If there something we can do, just post here.
