### ISSUE TITLE
Alarms and Alerts on Custom Dashboard

### ISSUE THREAD

**Issue by Jhexd** [firehol/netdata#2488]
Hi and thank you for the awesomeness that is Netdata.  I've built a custom dashboard to monitor a few servers at the office, but I cannot seem to get Slack-based alarm notifications.  Per http://localhost:19999/netdata.conf -- I am modifying the correct file with my slack webhook URL and
the #alarms and #systems channels have been created.

When adding metrics to the dashboard, should I be adding an alarm entry of some kind under data-host=http://localhost:19999 ?

I've combed over everything I can find and I'm pretty sure I'm missing something simple here--  Please advise and thanks!

**Comment by ktsaou** [comment]
Hi,

I just merge PR #2489 that allows alarm-notify.sh to print debugging info for tracing notification issues.
To use it:

1. Use `netdata-updater.sh` to update your netdata
2. To test alarms run:

```sh
export NETDATA_ALARM_NOTIFY_DEBUG=1
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```

The output of this command should now provide enough information to understand why it fails.

**Comment by Jhexd** [comment]
Thanks for the prompt response--  I receive:

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2017-07-24 18:36:46: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'cryptix', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CRITICAL'.
# FAILED

 Within this configuration file, I have modified the following sections:

# enable / disable features
SEND_SLACK="YES"
SEND_DISCORD="NO"
SEND_PUSHOVER="NO"
SEND_TWILIO="NO"
SEND_HIPCHAT="NO"
SEND_MESSAGEBIRD="NO"
SEND_TELEGRAM="NO"
SEND_EMAIL="NO"
SEND_PUSHBULLET="NO"
SEND_KAFKA="NO"
SEND_PD="NO"
SEND_CUSTOM="NO"

# slack configs
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/T456W90QN/B6TKRA0BB/etc etc"
DEFAULT_RECIPIENT_SLACK="alarms"
declare -A role_recipients_slack=()

The if statement beneath the commented line that reads: "# check that we have at least a method enabled" chooses the else condition even though the SEND_SLACK variable is set to "YES"

**Comment by ktsaou** [comment]
This is wrong:

```
declare -A role_recipients_slack=()
```

You should not change the defaults. There were many such lines. Just restore them and it will work.

**Comment by Jhexd** [comment]
Thanks!  We got this figured out now!  

I only had to modify the /etc/netdata/health_alarm_notify.conf file...  NOT the /usr/libexec/netdata/plugins.d/alarm-notify.sh script.

Solved-- many thanks!!
