### ISSUE TITLE
web_log should stop to collect unique ips when all_time is set to false

### ISSUE THREAD

**Issue by Wing924** [firehol/netdata#2490]
When all_time is set to false, even unique IPs graph is not shown, the data is collected in memory.
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L532
If we add a guard to stop this heavy function, we can improve performance.

**Comment by l2isbad** [comment]
> the data is collected in memory

yeah, it's a bug

> heavy function

function itself not heavy

**Comment by Wing924** [comment]
I'm sorry not to express clearly. 
The "heavy function" means use more memory than that of usual plugins. (I have too many unique users)

**Comment by l2isbad** [comment]
Thx for reporting i will fix the bug in 
https://github.com/firehol/netdata/pull/2481

**Comment by ktsaou** [comment]
merged it.
