### ISSUE TITLE
Remove top my-netdata bar

### ISSUE THREAD

**Issue by izghitu** [firehol/netdata#2494]
Hi,

I am trying to include the output of netdata clients into an iframe of a web page. My problem is that I need to hide/remove the top my-netdata bar with all the settings, alarms, update, help, etc buttons.

Is it possible in any way to hide/remove that whole top bar?
Please let me know.

Thanks in advance.

**Comment by hmmxp** [comment]
I think this is possible through use of custom dashboard as per wiki

https://github.com/firehol/netdata/wiki/Custom-Dashboards

**Comment by ktsaou** [comment]
Hi,

adding a netdata dashboard in an iframe will be problematic if you want the charts to be updated only when the page has focus. You see, iframes have a different focus compared to the rest of the page. So, you will be clicking on the page (outside the iframe) and the charts will not be updating.

Of course, you can force to dashboard to always update the charts (independently of the focus), but will put some pressure on your network and the web browser cpu.

The ideal way to include `dashboard.js` to your page, and add a `div` for each chart you want to add. This way, the chart focus and page focus will match.

The wiki page posted by @hmmxp is perfect to get you started with this.

**Comment by izghitu** [comment]
@hmmxp @ktsaou thank you both for your advices. I will check out the info and see what I can do with it
