### ISSUE TITLE
Various Plugins Improvements in v1.7.0

### ISSUE THREAD

**Issue by hmmxp** [firehol/netdata#2497]
Dear All,

I saw in release 1.7.0 there is FPing and other plugins improvements, are there any way for us to know what are enhanced or changed?

Thank You

**Comment by ktsaou** [comment]
Of course, just use the "Pull requests" tab of github, and search for

```
is:pr is:closed fping 
```

example for fping:

https://github.com/firehol/netdata/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20fping

**Comment by hmmxp** [comment]
Thank You So Much, This Will Help Everyone Who Wish To Know What Was Changed and Potentially Spot Any Future Bugs
