### ISSUE TITLE
cannot configure on current ubuntu LTS

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#25]
@alonbl I am trying to run it through several linux distros.

This is what happens on current ubuntu LTS:

```sh
$ ./configure --prefix=/opt/netdata
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
./configure: line 3902: PKG_PROG_PKG_CONFIG: command not found
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for inline... inline
checking for sin in -lm... yes
./configure: line 4992: syntax error near unexpected token `newline'
./configure: line 4992: `       PKG_CHECK_MODULES('
```

**Comment by alonbl** [comment]
this is different issue... you need to have access to pkg.m4 on the machine you run make dist.

so when trying this, always use recent development machine to perform the packaging, then transfer the tarball to the build machine. this way you always generate the up-to-date artifacts requires for the build.

**Comment by ktsaou** [comment]
You lost me...

Let's assume I have this machine only and I am trying to install the development version of netdata (the most common case, until we release it), how can I install it?

I tried also as root. Same result.

Note also this:

> ./configure: line 3902: PKG_PROG_PKG_CONFIG: command not found

Is there something the user can do to configure it?

**Comment by alonbl** [comment]
well... autoconf process separate between development machine and build machine.
developer have autoconf/automake/libtool/perl and other tools at his machine, while build requirements are minimum shell and POSIX tools.
the way it is achieved is by generating code at developer machine and have it available for build machine.
configure script is a good example, it is generated out of many files.
one of them, which is missing in this environment is pkg.m4 which is the code of pkg-config.
so your options are:
1. for development use your machine, for build/test use the older machine. this is the best practice. run autoreconf -ivf && ./configure && make dist at development machine, extract and build tarball on build machine.
2. locate the package that provide /usr/share/aclocal/pkg.m4, usually it will be something like pkgconfig or pkgconfig-devel,  install it, then run autoreconf -ivf.
3. copy pkg.m4 to package's m4 directory from a machine it is available, then run autoreconf -ivf.

**Comment by ktsaou** [comment]
ok. I found pkg-config was missing.

Alter installing it and running `. /etc/profile`, everything works.
