### ISSUE TITLE
Mariadb - Source contains parsing errors: '/etc/mysql/my.cnf'

### ISSUE THREAD

**Issue by nobicycle** [firehol/netdata#2500]
Hi,
I get this debug message:

> 	2017-07-23 09:23:16: python.d ERROR: mysql_mycnf2_netdata Source contains parsing errors: '/etc/mysql/my.cnf'
> 		[line 42]: 'skip-external-locking\n'
> 		[line 145]: 'quick\n'
> 		[line 149]: 'no-auto-rehash\n'mysqld --help --verbose
> 		[line 160]: 'interactive-timeout\n'

However 
`mysqld --help --verbose`
shows no errors in my.cnf

/etc/netdata/python.d/mysql.conf contains :

> mycnf2_netdata:
>   name     : 'local'
>   user     : 'netdata'
>   'my.cnf' : '/etc/mysql/my.cnf'
> 
> socket1_netdata:
>   name     : 'local'
>   user     : 'netdata'
>   # pass     : ''
>   socket   : '/run/mysqld/mysqld.sock'

**Comment by hmmxp** [comment]
Hi There,

As per my understanding that python.d/mysql.conf is in YAML format, can kindly check that there are proper indentation and adhere to YAML format?

**Comment by l2isbad** [comment]
i have same rows in `my.cnf` and there is no error for me. What python-mysql package are you using?
As a workaround i suggest not to use 'my.cnf' and move all the credentials to the module configuration file.

**Comment by l2isbad** [comment]
module configuration file is https://github.com/firehol/netdata/blob/master/conf.d/python.d/mysql.conf

I suggest to remove "my.cnf": "/etc/mysql/my.cnf" thing.

**Comment by ktsaou** [comment]
@l2isbad is `my.cnf` parsing is not working for `pymysql`, can we disable it (with a warning) when we use pymyql?

**Comment by nobicycle** [comment]
Hi l2isbad,

The reason I went for pymysql rather than MySQL-python is that the latter is not available for python 3 (yet)
https://pypi.python.org/pypi/MySQL-python/1.2.5

If I remove "my.cnf": "/etc/mysql/my.cnf" from the config file then debug gives the following:

> 2017-07-26 21:01:49:  INFO: Using python v3
> 2017-07-26 21:01:49:  INFO: YAML output is ordered
> 2017-07-26 21:01:49: python.d INFO: reading configuration file: /usr/lib/netdata/plugins.d/../../../../etc/netdata/python.d.conf
> 2017-07-26 21:01:49: python.d INFO: MODULES_DIR='/usr/lib/netdata/python.d/', CONFIG_DIR='/usr/lib/netdata/plugins.d/../../../../etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
> 2017-07-26 21:01:49: python.d DEBUG: mysql: loading module configuration: '/usr/lib/netdata/plugins.d/../../../../etc/netdata/python.d/mysql.conf'
> 2017-07-26 21:01:49: python.d DEBUG: mysql: reading configuration
> 2017-07-26 21:01:49: python.d DEBUG: mysql/mycnf2_netdata: job added
> 2017-07-26 21:01:49: python.d DEBUG: mysql/socket1_netdata: job added
> 2017-07-26 21:01:49: python.d DEBUG: all job objects [<Service(mycnf2_netdata, initial daemon)>, <Service(socket1_netdata, initial daemon)>]
> 2017-07-26 21:01:49: python.d ERROR: mysql_mycnf2_netdata _get_data() returned no data or type is not <dict>
> 2017-07-26 21:01:49: python.d ERROR: mysql_mycnf2_netdata check() failed - disabling job
> 2017-07-26 21:01:49: python.d ERROR: DISABLED: mysql/mycnf2_netdata
> 2017-07-26 21:01:49: python.d ERROR: mysql_socket1_netdata _get_data() returned no data or type is not <dict>
> 2017-07-26 21:01:49: python.d ERROR: mysql_socket1_netdata check() failed - disabling job
> 2017-07-26 21:01:49: python.d ERROR: DISABLED: mysql/socket1_netdata
> 2017-07-26 21:01:49: python.d DEBUG: overridden job names: []
> 2017-07-26 21:01:49: python.d DEBUG: all remaining job objects: []
> 2017-07-26 21:01:49: python.d FATAL: no more jobs
>

**Comment by l2isbad** [comment]
dpkg -l | grep python | grep mysql
ii  python-mysqldb                       1.2.3-2.1                           i386         Python interface to MySQL
ii  python3-mysqldb                      1.3.7-1~bpo8+1                      i386         Python interface to MySQL

**Comment by ktsaou** [comment]
Cleaning up. If there something we can do, just post here.
