### ISSUE TITLE
python module bug after an update

### ISSUE THREAD

**Issue by cgoze** [firehol/netdata#2506]
Hello,

I ran netdata-updater, and I saw on the dashboard that my python plugins wouldn't appear anymore.
I checked on the debug mode and I have this error (for every python plugin) : 
> 2017-07-24 11:28:44: python.d ERROR: Problem loading quotas 'module' object has no attribute 'disable_warnings'
2017-07-24 11:28:44: python.d FATAL: no modules found.
DISABLE

I don't know where it comes from since my code didn't change. Thanks for your help :)

**Comment by ktsaou** [comment]
Yesterday we added `urllb3` to support keep-alive on the connections generated by URLService.

@l2isbad check this. Can we do anything to be backward compatible?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L46

This one needed to disable warnings (self signed certificate, etc).
Looks like it's old `urllib3` package on your system @cgoze (the one shipped with netdata is less preferred).

What we can do:
1. add try, except for https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L46
2. make the one that is installed with the netdata more preferable

**Comment by cgoze** [comment]
Done ! Thanks :)
