### ISSUE TITLE
How does netdata establish server identity?

### ISSUE THREAD

**Issue by vbonline** [firehol/netdata#2516]
After a successfull testing phase we are beginning to roll out netdata on 80+ Linux servers.

Our Linux admin refuses to execute your install script on every machine, so he did a single install and rsync's everything to the machines, and deploys netdata.conf and stream,.conf via puppet on the other machines.

As long as only one of the rsynced netdata are running everything is fine. Once a second server starts I get this in the error log (Identifying data removed):

2017-07-25 15:33:21: netdata INFO : STREAM xxxxx.xx.xx [receive from [xxx.xxx.xxx.xxx]:43602]: multiple streaming connections for the same host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.

How does netdata establish identity of the sending server?

**Comment by ktsaou** [comment]
Hi,

you should not rsync `/var/lib/netdata` and `/var/cache/netdata`. These directories should be unique to each of your netdata and each netdata is able to general all the files in them. Just create the directories with the proper permissions and rights. Each netdata will do the rest.

For your reference, the unique id of each netdata is at `/var/lib/netdata/registry/netdata.public.unique.id`. This has a random GUID generated the first time netdata runs on a machine. It is never overwritten. This is used to uniquely identify each netdata. If you copy that file to multiple netdata servers, many things will break (the master netdata will have the impression that multiple nodes are streaming metrics for the same host, the `my-netdata` menu will list all your servers with as one, etc). So, let each netdata generate that file on each server.

**Comment by vbonline** [comment]
Thank you! Thats was very helpful. We'll try tomorrow..

**Comment by ddeimeke** [comment]
Please consider this solved. (I am one of the admins Volker wrote about.)

Ansible Playbook adjusted.

Works like a charm. Thank you!

**Comment by ktsaou** [comment]
Nice! Thanks!

**Comment by makutamatey** [comment]
netdata documentation covers /**etc** home directory more than  /**opt** directly so it is making it difficult getting this done. how can i get the log files and the machine id from /**opt** directory . /var/log/netdata/debug.log, tail -f /var/log/netdata/*.log and /var/lib/netdata/registry/netdata.public.unique.id do not work for me on some of my servers because the directory is now /**opt** and these paths do not apply.

**Comment by vlvkobal** [comment]
`sudo cat /opt/netdata/var/lib/netdata/registry/netdata.public.unique.id`

**Comment by vlvkobal** [comment]
You can check your current lib directory at http://localhost:19999/netdata.conf in the `[global]` section:
`# lib directory = /opt/netdata/var/lib/netdata`

**Comment by hamidreza-shoghi** [comment]
Thanks @ktsaou my problem solved.

**Comment by okgolove** [comment]
Can I (and should I?) manage it manually if I want to keep a new machine in parent netdata with the same hostname?

**Comment by MrZammler** [comment]
Hi @okgolove 

You can have a new netdata machine with the same hostname; assuming that their `netdata.public.unique.id`'s are different, they should not cause anything wrong.

If it's a new installation (not a full copy of the other one) Netdata will handle creating a new unique `netdata.public.unique.id`.

**Comment by okgolove** [comment]
If I set the same hostname I got two nodes with the same hostname on parent netdata: one offline (old) with old metrics and one live (new) with new metrics. Is there a possibility to "merge" it?

**Comment by MrZammler** [comment]
Not easily I'm afraid, if not at all. The parent netdata will keep separate metric databases for those two, since their id's are different.

**Comment by ktsaou** [comment]
On Netdata Cloud you can have them both in the same Room(s) and the overview dashboard will merge their data on the charts.

**Comment by okgolove** [comment]
@ktsaou unfortunately I can't use netdata cloud and the only one setup is capable for me is having parent and multiple children.

**Comment by ktsaou** [comment]
> @ktsaou unfortunately I can't use netdata cloud and the only one setup is capable for me is having parent and multiple children

@okgolove Oh! I see. Is this a company wide policy to not use SaaS or something else we probably miss?

Generally, Netdata Cloud stores in its databases just a few metadata about your infrastructure (the nodes you have, the metrics they collect, the retention of the metrics collected, etc). No sensitive business or technical information is collected or stored. Not even the metrics data. All the metrics data are stored exclusively on your Netdata Agents, which is exactly the same when you run the agents standalone. And it is free. So, what prevents you from using Netdata Cloud?

**Comment by okgolove** [comment]
@ktsaou first of all the company doesn't want to be dependent on cloud solutions which is not managed by us at all. As an example I can give your temporary free cloud plan. Currently it has unlimited notification integrations, but who knows what will happen as soon as paid plan arrives. And this is only one example.

I don't mean you cloud solution is bad, I think this is a cool feature (especially in terms of sensitive information) but it just doesn't suite us.
