### ISSUE TITLE
Netdata not showing stats for all LXD containers

### ISSUE THREAD

**Issue by cythoning** [firehol/netdata#2517]
Hi

I have 9 lxd containers on Ubuntu, and Netdata is at any time only showing me stats for 8 of them. If I stop one container and restart Netdata, it will show the container that wasn't shown before, but if I restart the container again Netdata will ignore it until I turn off another one. Is there some setting I need to set to show more than 8 containers?

Cheers

**Comment by ktsaou** [comment]
hm... I guess everything using default in netdata.conf. Right?

There is no limit on the number of containers netdata can use. Check https://build.my-netdata.io for example. It has more than 20.

Can you give me a procedure to reproduce this? It may be a bug.

Until we solve this, I think I can add an option to netdata.conf to disable containers cleanup, so a removed container will never be removed from netdata, but let's try first to fix it.

**Comment by cythoning** [comment]
I didn't change anything in the netdata.conf concerning cgroups. All I changed is longer history, update every 2s and bind to 0.0.0.0. I don't know how well it is reproducible since other Netdata instances seem to be fine with more than 8 containers. But here is what I do:
I run Ubuntu Server 16.04 with 9 lxd containers (all Ubuntu 16.04). When I start the server Netdata only shows 8 of the containers, no matter how long I wait. And its always the same one that is missing.
I can then stop one of the containers, it disappears from Netdata and after about 10s the missing one shows up. When I start the stopped container again, it will not show up on Netdata, only when I stop another one. Whenever I restart Netdata its always the same container missing. I also created additional containers to check if its just that particular one that has problems showing up, but even with 10+ containers running it always only shows 8.

**Comment by ktsaou** [comment]
Could you please post the output of this:

```sh
grep -i cgroup /var/log/netdata/error.log
```

I see there is an internal protection in netdata for 500 cgroups (these include all the cgroups, even if they are not visible containers). netdata logs `Maximum number of cgroups reached (%d). Not adding cgroup '%s'` if this is reached.

**Comment by cythoning** [comment]
Well that seems to be it. There were a lot of lines like
`2017-07-25 20:16:39: netdata INFO : Maximum number of cgroups reached (500). Not adding cgroup '/system.slice/lxd.service'`

I raised the maximum number of cgroups to 1000 and now all containers show up.

**Comment by ktsaou** [comment]
ok, I am increasing that number to 1000 too.

**Comment by cythoning** [comment]
Thanks for the quick reply. And thanks for the great work on Netdata, fantastic tool!
