### ISSUE TITLE
Changing endpoints for nginx and php7-fpm

### ISSUE THREAD

**Issue by dugajean** [firehol/netdata#2522]
By default netdata fetches information for nginx and php7-fpm from the `/status` and `/stub_status` respectively. In my case, my app allows for new URLs to be created from its dashboard, where the `/status` might get used, causing problems.

Where in Netdata's configuration do I exactly change these default endpoints to something more unique (eg. I can prefix the endpoints with `netdata_`). 

Help would be appreciated!

**Comment by ktsaou** [comment]
Hi,

- [nginx](https://github.com/firehol/netdata/blob/2d86d96378ab3320d1c5e47fd1c1b1290795b63c/conf.d/python.d/nginx.conf#L92-L102)
- [apache](https://github.com/firehol/netdata/blob/2d86d96378ab3320d1c5e47fd1c1b1290795b63c/conf.d/python.d/apache.conf#L70-L80)

In general, all are in `/etc/netdata/python.d/*.conf`.

**Comment by ktsaou** [comment]
And:

- [php-fpm](https://github.com/firehol/netdata/blob/2d86d96378ab3320d1c5e47fd1c1b1290795b63c/conf.d/python.d/phpfpm.conf#L72-L82)

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
