### ISSUE TITLE
Netdata proxies using data-host

### ISSUE THREAD

**Issue by samueljon** [firehol/netdata#2523]
Hi,

I've set up a netdata proxy that I'm streaming all the host that I'm currently monitoring. I would like to create a dashboard on the netdata proxy host with graphs from  the servers available through this proxy.

https://my-netdata-host.tld/api/v1/charts displays an array of hosts available

```json
"hosts": [
		{
			"hostname": "host-a.tld"
		},
		{
			"hostname": "host-b.tld"
		},
		{
			"hostname": "host-c.tld"
		}
	]
```

How do I access the hosts in my data-host= property when adding graphs or do I use different syntax ?

**Comment by ktsaou** [comment]
Hi,

You should use the base URL of the master netdata (eg `http://master.netdata.ip:19999/`) and append `/host/HOSTNAME/`.

The same thing is done by the dashboard when you click on a host mirrored at the `my-netdata` menu.
