### ISSUE TITLE
Use socket file instead of IP

### ISSUE THREAD

**Issue by habib-the-sweet** [firehol/netdata#2526]
Hello.

I use nginx as reverse proxy for netdata. I would like to use the same port as netdata default (19999) but I can't because netdata already use it. Of course I can change port on nginx but is it possible to proxy directly to socket file like `fastcgi_pass unix:/var/run/php5-fpm.sock;` ?

**Comment by ktsaou** [comment]
Hi,

you can bind nginx on port `19999` and netdata on `localhost:19998` and instruct nginx to use netdata on localhost 19998.

I think it should also be possible to bind nginx on `ETHERNET_IP:19999` and netdata on `localhost:19999`, but I haven't ever tried it...

**Comment by yoursvivek** [comment]
1. Change `default port` in netdata configuration `/etc/netdata/netdata.conf` under `web` section

```
[web]
	default port = 19998
```
2. Put following configuration in a file at `/etc/nginx/site-enabled/netdata` 

```
upstream netdata {
    server localhost:19998;
}
server {
	listen 19999 default_server;
	listen [::]:19999 default_server;

    location / {
        proxy_pass http://netdata;
    }
}
```

3. Reload nginx.

Viola done!

**Comment by ktsaou** [comment]
ok, but also change to:

```
[web]
   bind to = localhost
```

So, that port 19998 will not be open to anyone else except localhost.

**Comment by ktsaou** [comment]
This has been implemented with https://github.com/firehol/netdata/pull/2657 as requested with https://github.com/firehol/netdata/issues/2656
