### ISSUE TITLE
"host needs attention" E-mail after 1 dropped packet

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2529]
If an interface drops just one packet, netdata sends me a warning E-mail - and then again 10 minutes later when the condition clears.  I have a server which does this a couple of times a day.

The mail helpfully tells me exactly which file to edit (`/opt/netdata/etc/netdata/health.d/net.conf`) and which line (9) to fix this.  Kudos for that.

However, I think this is too sensitive as a default.  A single packet dropped is almost certainly not a cause for concern; at least, it doesn't warrant an E-mail.

In contrast: there is also a packet loss ratio test.  This doesn't issue a warning until 0.5% of packets have been dropped, which is a very high threshold.  Losing 1 in 200 packets is really bad; even 1 in 1000 would be a concern.

So I would like to suggest some more useful defaults:

~~~
# absolute packets_dropped:
# at least 5 packets in 10 minutes (average 1 dropped every 2 minutes)

    warn: $this > 4
~~~

And:

~~~
# packets_dropped_ratio:
# at least 0.1%, subject to a minimum of 2 drops; critical at 2%

    calc: (($inbound_packets_dropped != nan AND $this > 1) ? ($inbound_packets_dropped * 100 / $this) : (0))
    warn: $this > 0.1
    crit: $this > 2
~~~

These are still quite sensitive, but a bit less than now.

**Comment by ktsaou** [comment]
I agree.

I also made the ratio alarms trigger only if there are >50 packets in 10 minutes, and >5 dropped.
The badges should show the real ratio, even if the alarm is not triggered (less that 50 packets total or less than 5 dropped).

**Comment by ktsaou** [comment]
I removed the extra limit. It was totally wrong.
I did it exactly as you suggested.

**Comment by candlerb** [comment]
Cool.

I would also be fine with the absolute packet drop threshold being a bit higher - perhaps 10 packets in 10 minutes, maybe even as high as 50 as you originally suggested - for the benefit of very busy servers.

But even 5 or 10 packets lost in 10 minutes is probably still worth investigating; and if you conclude this is "normal" then you can always raise the threshold by hand.

**Comment by ktsaou** [comment]
merged it.
Let's see...
