### ISSUE TITLE
Pfsense with squid module

### ISSUE THREAD

**Issue by lbsou** [firehol/netdata#2542]
Hi!

First, I want to thank you for building such a great product. REALLY, it is awesome!

I'm experiencing a problem while trying to get the charts of squid working.

The port use is 8080.

When I do a "squidclient -h 127.0.0.1 -p 8080 cache_object://127.0.0.1:8080/counters" I get correct result.

```
=================================================
HTTP/1.1 200 OK
Server: squid
Mime-Version: 1.0
Date: Tue, 01 Aug 2017 12:37:02 GMT
Content-Type: text/plain;charset=utf-8
Expires: Tue, 01 Aug 2017 12:37:02 GMT
Last-Modified: Tue, 01 Aug 2017 12:37:02 GMT
X-Cache: MISS from XXXXXXXXXXXX
X-Cache-Lookup: MISS from XXXXXXXXXXXXX
Connection: close

sample_time = 1501590972.500919 (Tue, 01 Aug 2017 12:36:12 GMT)
client_http.requests = 1009
client_http.hits = 0
client_http.errors = 23
etc etc etc
=================================================
```

If I start `python.d.plugin` in debug mode for squid

```
/usr/local/libexec/netdata/plugins.d/python.d.plugin 2 debug squid

=================================================
2017-08-01 08:38:11:  INFO: Using python v2
2017-08-01 08:38:11:  INFO: YAML output is ordered
2017-08-01 08:38:11: python.d INFO: reading configuration file: /usr/local/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf
2017-08-01 08:38:11: python.d ERROR: /usr/local/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf reading error: [Errno 2] No such file or directory: '/usr/local/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf'
2017-08-01 08:38:11: python.d INFO: MODULES_DIR='/usr/local/libexec/netdata/python.d/', CONFIG_DIR='/usr/local/libexec/netdata/plugins.d/../../../../etc/netdata/', UPDATE_EVERY=2, ONLY_MODULES=['squid']
2017-08-01 08:38:11: python.d ERROR: squid: configuration file '/usr/local/libexec/netdata/plugins.d/../../../../etc/netdata/python.d/squid.conf' not found. Using defaults.
2017-08-01 08:38:11: python.d DEBUG: squid: setting configuration for only one job
2017-08-01 08:38:11: python.d DEBUG: squid: job added
2017-08-01 08:38:11: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-08-01 08:38:11: python.d DEBUG: squid No unix socket specified. Trying TCP/IP socket.
2017-08-01 08:38:11: python.d DEBUG: squid No host specified. Using: 'localhost'
2017-08-01 08:38:11: python.d DEBUG: squid No port specified. Using: '3128'
2017-08-01 08:38:11: python.d DEBUG: squid No request specified. Using: ''
2017-08-01 08:38:11: python.d DEBUG: squid creating socket to '127.0.0.1', port 3128
2017-08-01 08:38:11: python.d DEBUG: squid connecting socket to '127.0.0.1', port 3128
=================================================
```

So it seems that python.d.plugin is unable to find python.d.conf

The path should be  :` /usr/local/libexec/netdata/plugins.d/../../../../usr/local/etc/netdata/python.d.conf`

I modified the CONFIG_DIR in `/usr/local/libexec/netdata/plugins.d/python.d.plugin` to `/usr/local/etc/netdata/` and modify `/usr/local/etc/netdata/python.d/squid.conf` so that one of the jobs use port 8080 like that 

```
tcp3128oldipv4:
  name     : 'local'
  host     : '127.0.0.1'
  port     : 8080
  request  : 'cache_object://127.0.0.1:8080/counters'
```

 I get : 
```
=================================================
BEGIN squid_local.clients_net 0
SET client_http_kbytes_in = 4977
SET client_http_kbytes_out = 17679
SET client_http_hit_kbytes_out = 0
END
BEGIN squid_local.clients_requests 0
SET client_http_requests = 1046
SET client_http_hits = 0
SET client_http_errors = 43
END
BEGIN squid_local.servers_net 0
SET server_all_kbytes_in = 16970
SET server_all_kbytes_out = 4798
END
BEGIN squid_local.servers_requests 0
SET server_all_requests = 611
SET server_all_errors = 0
END

BEGIN netdata.plugin_pythond_squid_local 0
SET run_time = 2
END

2017-08-01 08:41:40: python.d DEBUG: squid_local squid_local updated in 2 ms
2017-08-01 08:41:40: python.d DEBUG: squid_local sleeping for 1.98878502846 secs to reach frequency of 2.0 secs, now: 1501591300.01  next: 1501591302.0  penalty: 0
^C2017-08-01 08:41:40: python.d DEBUG: squid_local sleeping for 1.16311001778 secs to reach frequency of 2.0 secs, now: 1501591300.84  next: 1501591302.0  penalty: 0


=================================================
```

So I seem to get it work but I do not get any charts in the WEBUI.

I tried to start the python.d.plugin with the user netdata with the same result.

```
chsh -s /usr/local/bin/bash netdata
su -s netdata
```

Any idea?!

**Comment by ktsaou** [comment]
It seems that you have installed netdata without the installer, so the default relative paths are wrong.
If you used the installer, it should install netdata in `/opt/netdata`, or `/usr/local/netdata`, or something that should put all the netdata files under the same root directory.

**Comment by lbsou** [comment]
Hi! Thanks for the quick answer!

I have tried to uncomment the "config directory" with good path + restart with no success.

So, I uninstalled netdata package and decided to try to compile it instead with the installer.

As for the previous install, I followed the install procedure of this page (now FreeBSD instead of PFsense section) : https://github.com/firehol/netdata/wiki/Installation

I installed all the dependencies :

autoconf-2.69_1
autoconf-wrapper-20131203
automake-1.15_1
automake-wrapper-20131203
bash-4.4.12_2 
curl-7.54.1
e2fsprogs-libuuid-1.43.4
gcc-5.4.0
pidof-20050501
pkgconf-1.3.0,1
python2-2_3
python27-2.7.13_3
/usr/libdata/pkgconfig/zlib.pc (built-in, is it ok? Not found any package for it)

[/root/netdata]# ./autogen.sh
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
configure.ac:178: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:190: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:302: error: possibly undefined macro: AC_CHECK_HEADER
autoreconf-2.69: /usr/local/bin/autoconf-2.69 failed with exit status: 1
 FAILED

What am I missing?

I tried to debug this part, see the attached file. Thanks!

[debug.txt](https://github.com/firehol/netdata/files/1193850/debug.txt)

**Comment by lbsou** [comment]
More information :

**Comment by lbsou** [comment]
**Here more info**

First, if I do # **sh -n configure**

configure: 6373: Syntax error: newline unexpected (expecting ")")

The line 6373 is : 

PKG_CHECK_MODULES(
    ZLIB,
    zlib,
    have_zlib=yes,
    have_zlib=no
)

It does not seem to be link with zlib but with PKG_CHECK_MODULES.

The package pkgconf-1.3.0,1 is installed. I did reboot since the install.

I tried to run ./configure and got this error in the config.log
usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/stdio.h:53:23: fatal error: sys/cdefs.h: No such file or directory

With that command I found that it was looking for cdefs.h in  "/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/sys/"

# **echo "#include <sys/cdefs.h>" | gcc -E -x c - | grep types**

I have install the src.txz and added a symbolic link from 

/usr/include/machine/
and 
/usr/include/sys
to 
/usr/src/sys/sys

**The error is now different** 

configure:3877: gcc -o conftest    conftest.c  >&5
In file included from /usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/stdio.h:55:0,
                 from conftest.c:11:
/usr/src/sys/sys/_types.h:38:9: error: unknown type name '__uint32_t'
 typedef __uint32_t __blksize_t; /* file block size */

=======MORE AND MORE=======
         ^
/usr/src/sys/sys/_types.h:63:9: error: unknown type name '__uint32_t'
 typedef __uint32_t __uid_t;
         ^
/usr/src/sys/sys/_types.h:93:9: error: unknown type name '__uint_least16_t'
 typedef __uint_least16_t __char16_t;
         ^
/usr/src/sys/sys/_types.h:94:9: error: unknown type name '__uint_least32_t'
 typedef __uint_least32_t __char32_t;

In file included from conftest.c:11:0:
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/stdio.h:60:9: error: unknown type name '__size_t'
 typedef __size_t size_t;
         ^
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/stdio.h:71:9: error: unknown type name '__ssize_t'
 typedef __ssize_t ssize_t;
         ^
/usr/local/lib/gcc5/gcc/x86_64-portbld-freebsd10.3/5.4.0/include-fixed/stdio.h:77:9: error: unknown type name '__va_list'
 typedef __va_list __not_va_list__;
         ^
configure:3881: $? = 1
configure:3888: ./conftest
eval: ./conftest: not found
configure:3892: $? = 127
configure:3899: error: in `/root/netdata':

Hope this is enough information for you to have an idea of what is going on! Thank you!

**Comment by ktsaou** [comment]
hm... I need help too.
@vlvkobal could you please check this?

**Comment by vlvkobal** [comment]
> You can't compile netdata on pfSense. Take a look at https://doc.pfsense.org/index.php/Can_I_compile_software_on_pfSense

Look at #1640 for more information about `netdata` on `pfSense`

**Comment by vlvkobal** [comment]
Notice!
> A virtual machine or separate system can be setup to compile software, and then the compiled binaries/packages/software can be moved over to the firewall.

Thus, if you need a specially configured and compiled package you still have a possibility to do it, with some inconvenience though.

**Comment by lbsou** [comment]
Thank you!

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
