### ISSUE TITLE
Reverse time flow on x-axis?

### ISSUE THREAD

**Issue by laneshields** [firehol/netdata#2543]
I am incorporating some Netdata charts into a webpage to visualize data for a project I am working on.  I'd really like to reverse the direction of the x-axis so the graphs move from left to right instead of right to left because it would make more sense in the context of the page I am creating.  Is this something I can do easily?

**Comment by ktsaou** [comment]
Hi,

For dygraphs add `<div ... data-override-options="ms">`

The [default dygraph options](https://github.com/firehol/netdata/blob/4a0bfcebfed5af394934e9d1be5c1e2393d67481/web/dashboard.js#L6173) are `ms|flip`.

**Comment by ktsaou** [comment]
Well... I didn't said `data-append-options`. I said `data-override-options`. Different things. The `append` one appends your options to the existing ones (which does not remove `flip`). The `override` one replaces the default options with the ones specified.

**Comment by ktsaou** [comment]
btw, I just tested it. It works.

**Comment by laneshields** [comment]
You are right.  I must have misread your initial post.  I didn't know data-ovderride-options was even a valid option.  But it does work, thank you.  I really like netdata and what I can do with it!
