### ISSUE TITLE
How to read temperature without sensors in FreeBSD?

### ISSUE THREAD

**Issue by theAlchemist-dev** [firehol/netdata#2544]
Hello,

I am using your amazing piece of software on my `FreeBSD 10.3` server.
When reading the documentation, the sensor data should be read with `sensors`?

FreeBSD has no `sensors` command IMO, but I do have `kldload coretemp` with readout by `sysctl`:

`# kldload coretemp`
`# sysctl -a |grep temper`
`dev.cpu.3.temperature: 35.0C`
`dev.cpu.2.temperature: 35.0C`
`dev.cpu.1.temperature: 30.0C`
`dev.cpu.0.temperature: 30.0C`

Am I missing some configuration?
The CPU frequencies are being read, so the required `Python cpufreq` module is working, right?

Edit: `netdata version: 1.7`

**Comment by ktsaou** [comment]
hm... I think is this not supported out of the box.

@vlvkobal is that something we can support on FreeBSD?

@theAlchemist-dev you can create a simple bash plugin to execute these commands and turn the output to something netdata can accept. Use this file as a starting point: https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh

**Comment by vlvkobal** [comment]
I'm on the road for a few days more. I'll be able to look at it in a week.

**Comment by vlvkobal** [comment]
@theAlchemist-dev I can't get CPU temperature on VM. Thus, I had to write it blindly on the basis of `man`. Could you try a code from `git clone --depth=1 --branch coretemp https://github.com/vlvkobal/netdata.git`. Is it working?

**Comment by theAlchemist-dev** [comment]
Thanks for the help, I did not had time yet to try it myself.

@vlvkobal I have installed the repo and I got netdata running.
However, I don't see the temperature anywhere in the web UI.

I am checking the error.log now, but I am not sure what to search for.
Any advice on where I should look :)?

**Comment by vlvkobal** [comment]
Does `grep temperature error.log` show something?

**Comment by theAlchemist-dev** [comment]
Nope, sorry, I have done that, but I cannot find anything with `temp` other than `hddtemp`

**Comment by theAlchemist-dev** [comment]
For the record, I have installed `netdata` using the `netdata-installer.sh` script. That should use your edited `make file` right?

**Comment by vlvkobal** [comment]
You can do `make clean` before `netdata-installer.sh` to be shure that all is rebuilt from scratch.

**Comment by theAlchemist-dev** [comment]
@vlvkobal Good one, sadly it makes no difference.

**Comment by vlvkobal** [comment]
Is it possible to get access to your machine?

**Comment by theAlchemist-dev** [comment]
That depends:

1. Can we discuss this in private?
2. What kind of access do you need, I am not very comfortable giving you root access...

**Comment by vlvkobal** [comment]
Please e-mail to `vlad@prokk.net`. I think I don't need root access. I'll have some time for programming tomorrow in the evening.

**Comment by theAlchemist-dev** [comment]
@vlvkobal, thank you very much for helping out.

The temperature can now be monitored on my FreeBSD machine :D
