### ISSUE TITLE
libvirt plugin

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2545]
netdata already monitors libvirt VMs through cgroups.
For each VM it can get CPU, Memory and Disk I/O, as seen by the host.

However, libvirt provides an API that can expose:

- CPU (same with cgroups),
- Memory (it can provide the amount of memory used inside the VM, while cgroups can only see the total allocated)
- Disk (I think it is the same with cgroups),
- Network (this is unique - it cannot be fetched via cgroups)

Additionally, libvirt is able to provide information about all the VMs running, their statuses, etc.

**Comment by ktsaou** [comment]
@l2isbad I see libvirt provides a python bindings. I don't know however if a non-privileged user (like netdata), can query it.

If this can be done, the best would be to write it in python.
If this is not possible, probably a little C `setuid` binary would be the solution.

**Comment by l2isbad** [comment]
http://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Guest_Domains-Monitoring.html

> Statistical metrics are available for monitoring the utilization rates of domains, vCPUs, memory, block devices, and network interfaces.

quick test (as a in `libvirt` group)
```python
import libvirt
from xml.etree import ElementTree

STATE = {1: 'RUNNING', 5: 'SHUTOFF'}
conn = libvirt.open('qemu:///system')

for vm in conn.listAllDomains():
    vm_name, vm_id = vm.name(), vm.ID()
    vm_state, vm_reason = vm.state()
    print('[{}:{}]---> state: {}, reason code {}'.format(vm_name, vm_id, STATE[vm_state], vm_reason))
```

```
[murky:118]---> state: RUNNING, reason code 1
[ns5:67]---> state: RUNNING, reason code 1
[videoserver:119]---> state: RUNNING, reason code 1
[appstore:6]---> state: RUNNING, reason code 1
[win2k3r2-remote-desktop:-1]---> state: SHUTOFF, reason code 2
[Hamster:94]---> state: RUNNING, reason code 1
[olimp:114]---> state: RUNNING, reason code 1
[noc:112]---> state: RUNNING, reason code 1
[iptv-radius3:117]---> state: RUNNING, reason code 1
```




**Example stats from random vm:**
```python
Hamster = conn.lookupByName('Hamster')
Hamster.getCPUStats(False)
```

```
[{'cpu_time': 1119233643425987, 'vcpu_time': 595268058146559},
 {'cpu_time': 1186421804127589, 'vcpu_time': 623894745656658},
 {'cpu_time': 1175294268724113, 'vcpu_time': 616716731941643},
 {'cpu_time': 1178945751579061, 'vcpu_time': 621928030223959},
 {'cpu_time': 1174805923977951, 'vcpu_time': 621201417169122},
 {'cpu_time': 1168677922542931, 'vcpu_time': 617908764320719},
 {'cpu_time': 1140175463533241, 'vcpu_time': 605051507354514},
 {'cpu_time': 1170226073114724, 'vcpu_time': 619282696278895},
 {'cpu_time': 848493695686616, 'vcpu_time': 448743106055339},
 {'cpu_time': 817377540123427, 'vcpu_time': 425562698441931},
 {'cpu_time': 823497184513642, 'vcpu_time': 433654510879188},
 {'cpu_time': 823517923438717, 'vcpu_time': 433432694080374},
 {'cpu_time': 825021127992959, 'vcpu_time': 434075134457836},
 {'cpu_time': 818271373576352, 'vcpu_time': 425384501153565},
 {'cpu_time': 799589748161571, 'vcpu_time': 417120544502234},
 {'cpu_time': 831383804732049, 'vcpu_time': 434092153050708}]
```

```python
Hamster.getCPUStats(True)
```
```
[{'cpu_time': 15900933302123117,
  'system_time': 1256125470000000,
  'user_time': 71137180000000}]
```
```python
Hamster.memoryStats()
```

```
{'actual': 4194304,
 'available': 4044728,
 'major_fault': 89444115,
 'minor_fault': 401226872573,
 'rss': 4405416,
 'swap_in': 2924288,
 'swap_out': 4803400,
 'unused': 1505920}
```

```python
tree = ElementTree.fromstring(Hamster.XMLDesc())
iface = tree.find('devices/interface/target').get('dev')
stats = Hamster.interfaceStats(iface)
print('read bytes:    '+str(stats[0]))
print('read packets:  '+str(stats[1]))
print('read errors:   '+str(stats[2]))
print('read drops:    '+str(stats[3]))
print('write bytes:   '+str(stats[4]))
print('write packets: '+str(stats[5]))
print('write errors:  '+str(stats[6]))
print('write drops:   '+str(stats[7]))
```

```
read bytes:    1290307744269
read packets:  3879926622
read errors:   0
read drops:    0
write bytes:   414728396608
write packets: 3465762146
write errors:  0
write drops:   0
```

```python
bDevice = tree.find('devices/disk/target').get('dev')
stats = Hamster.blockStats(bDevice)
print('Read requests issued:  '+str(stats[0]))
print('Bytes read:            '+str(stats[1]))
print('Write requests issued: '+str(stats[2]))
print('Bytes written:         '+str(stats[3]))
print('Number of errors:      '+str(stats[4]))
```

```
Read requests issued:  101773362
Bytes read:            716035215360
Write requests issued: 1254629416
Bytes written:         12697856345088
Number of errors:      -1
```

**Comment by ktsaou** [comment]
Wow! So it works!
Can you turn it to a netdata plugin?

I guess we will need a `vlibirt_local` section with a few charts about the status of libvirt and then one section `vmname_local` for each VM (cpu, vpu, mem, swap, page_faults, disk i/o, disk ops, net bandwidth, net packets, net drops, net errors).

**Comment by l2isbad** [comment]
> Can you turn it to a netdata plugin?

Sure

**Comment by ktsaou** [comment]
perfect!

**Comment by ktsaou** [comment]
> Any news regarding the libvirt netdata plugin?

netdata already monitors libvirt VMs, through cgroups. Is there something missing?

**Comment by tmiradu** [comment]
Even it can see the VMs, the data is not accurate. For example memory graphs are only straight lines, fewer graphs than the host machine.

**Comment by Ferroin** [comment]
I think you're misunderstanding what the libvirt plugin is tracking.

What the libvirt plugin is actually tracking is the data reported by libvirt about the host's resource utilization resulting from each VM (for example, how much memory on the host each VM is taking up).

What you appear to want is data from the guest systems.  There is no way to do this with netdata only installed on the host, just install netdata in each guest and have them stream metrics to the host.

**Comment by tmiradu** [comment]
OK. Thank you very much!

**Comment by slynn1324** [comment]
This might belong as a new issue, but I'm finding the cpu usage stats to be extremely under-reported for qemu vms when compared to usage in either htop or virt-manager.  

On my current system (Ubuntu 18.04) I'm seeing the following for a qemu vm:

❯ cat cpuacct.stat
user 9525
system 3322112

The system number is only increasing by 1-4 each second, even though other monitoring tools are reporting 40-45%+ cpu usage for the vm.  Netdata reports that cgroup_qemu_qemu_7_myvm.cpu is 3-5 %.   This machine has 4 cores, so for the host I would expect an overall total to be in the ~10%+ range. 

Any ideas what I'm seeing here?

**Comment by prologic** [comment]
You should file a new issue to discuss the specific issues you are seeing there.
