### ISSUE TITLE
bug: prometheus backend close connection when set 'send charts matching' to negative pattern

### ISSUE THREAD

**Issue by Wing924** [firehol/netdata#2547]
`send charts matching` has a bug when set it to negative patterns.

If I set 
```
[backend]
    send charts matching = netdata.*
```
It works and only show metrics with `netdata.*`. 
But if I set `send charts matching = !netdata.*` the http connection will be closed without any output.

access_log:
```
2017-08-02 02:54:28: 3: 10.0.2.2 port 62892 connected on thread task id 13055
2017-08-02 02:54:28: 3: (sent/all = 0/0 bytes -0%, prep/sent/total = 0.14/0.09/0.23 ms) data: 200 '/api/v1/allmetrics?format=prometheus'
2017-08-02 02:54:28: 3: 10.0.2.2 port 62892 disconnected from thread task id 13055
```

HTTP request:
```
curl -vs http://localhost:19999/api/v1/allmetrics\?format\=prometheus
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 19999 (#0)
> GET /api/v1/allmetrics?format=prometheus HTTP/1.1
> Host: localhost:19999
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Connection: close
< Server: NetData Embedded HTTP Server
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Content-Type: text/plain; version=0.0.4
< Date: Wed, 02 Aug 2017 02:45:30 GMT
< Cache-Control: no-cache
< Expires: Wed, 02 Aug 2017 02:45:31 GMT
<
* Closing connection 0
```

**Comment by ktsaou** [comment]
Hi, there is no default for the pattern.

Use:

```
[backend]
    send charts matching = !netdata.* *
```

The last `*` says: send the rest

**Comment by Wing924** [comment]
@ktsaou It works! Thank you!

**Comment by ktsaou** [comment]
nice!

**Comment by vincus** [comment]
Hmm, it does not seem to be filtering

```
# cat /etc/netdata/netdata.conf | grep -A2 backend
[backend]
    send charts matching = !netdata_cpu_softnet.* *
        # enabled = no
#  curl --silent "http://localhost:19999/api/v1/allmetrics?format=prometheus?source=as_collected" | grep netdata_cpu_softnet | head
netdata_cpu_softnet_stat_total{chart="cpu.cpu39_softnet_stat",family="softnet_stat",dimension="processed"} 639735 1504618910114
netdata_cpu_softnet_stat_total{chart="cpu.cpu39_softnet_stat",family="softnet_stat",dimension="dropped"} 0 1504618910114

```

**Comment by ktsaou** [comment]
@vincus when netdata is pushing metrics to backends, it filters only charts, not dimensions. So, it will either send the entire chart (all its dimensions), or it will send nothing about a chart.

**Comment by ktsaou** [comment]
btw, also `send charts matching` checks the chart name, as shown on the dashboard.

**Comment by vincus** [comment]
So in netdata terms from `netdata_cpu_softnet_stat_total{chart="cpu.cpu39_softnet_stat",family="softnet_stat",dimension="processed"}` the dimension is everything from `netdata_cpu.*`  instead of just `"processed"`?

**Comment by ktsaou** [comment]
Well, netdata does not filter on the values printed / formatted for prometheus. It filters them **before** formatting them.

netdata has charts and dimensions/metrics in each chart.  For example, for this chart:

![image](https://user-images.githubusercontent.com/2662304/30081382-a1477244-928f-11e7-923c-c83915aecb2b.png)

The chart name is `system.cpu`. This is what is filtered (e.g .  `send charts matching = system.*`). All the lines / metrics / dimensions in this chart will be sent, or not sent based on this filtering.

**Comment by vincus** [comment]
Hmm
Tried with
```
[backend]
    send charts matching = !netdata.cpu.* *

```
tried with
```
[backend]
    send charts matching = !netdata_cpu.* *
```
tried with
```
[backend]
    send charts matching = !*cpu.* *
```
tried with
```
[backend]
    send charts matching = !.*cpu.* *
```
tried with
```
[backend]
    send charts matching = !.*cpu.* *

```tried with
```
[backend]
    send charts matching = !netdata.groups.* *
```
tried with
```
[backend]
    send charts matching = !netdata_groups.* *
```

Non of them filtered out anything (same amount of rows, metrics still exist)
Maybe I am wrong, but it does not seem to be too simple
