### ISSUE TITLE
How to set EMAIL-FROM

### ISSUE THREAD

**Issue by approximatenumber** [firehol/netdata#2548]
Hi. Cannot find the answer. 
I use netdata-container [titpetric/netdata](https://hub.docker.com/r/titpetric/netdata/). On my mail-server I see these logs:
```
mail                                 | Aug  2 08:37:06 mail amavis[1886]: (01886-11) Passed BAD-HEADER-1 {RelayedOutbound,Quarantined}, LOCAL [172.23.0.10]:33590 <root@e24d0b5cccc1> -> <me@example.com>, quarantine: v/badh-vUpNSgSzfnEZ, Queue-ID: E07B2380804, mail_id: vUpNSgSzfnEZ, Hits: -, size: 9023, queued_as: 10D90383905, 140 m
mail                                 | Aug  2 08:37:12 mail postfix/smtp[9786]: 10D90383905: to=<me@example.com>, relay=example.com[62.117.103.48]:25, delay=6.1, delays=0.01/0.01/0.41/5.7, dsn=5.7.1, status=bounced (host smtp.example.com[62.117.103.48] said: 550 5.7.1 Message rejected as spam by Content Filtering. (in reply to end of DATA command))
```
So, there is bad header with address `root@e24d0b5cccc1` which dropped by relay server as spam.
I cannot find option to set FROM-ADDRESS of netdata to send mail from determined email-address (ex. `netdata@my-server.com`), neither in netdata-docs, nor in container-docs (`SSMTP_HOSTNAME` doesn`t help).

**Comment by ktsaou** [comment]
I have added an option to set it.
Check PR #2552

**Comment by ktsaou** [comment]
merged it.
Just update your netdata and set this variable in `/etc/netdata/health_alarm_notify.conf`

**Comment by approximatenumber** [comment]
@ktsaou thanks!
