### ISSUE TITLE
optimize javascript dates generation

### ISSUE THREAD

**Issue by fredericopissarra** [firehol/netdata#255]
On src/web_buffer.c I notice two routines commented as "the fastest way possible" (buffer_jsdate & buffer_date). Without using assembly language there is a minor enhancement which will quadruple the speed for such routines. Take a look at this small test:

https://ghostbin.com/paste/k5fz6

[]s
Fred

**Comment by ktsaou** [comment]
Nice! You are so right! It is obvious a single pointer is faster than an array with index.
Thanks!

What would also make a big difference in netdata are these 4 functions: https://github.com/firehol/netdata/blob/master/src/storage_number.c

But are already too low-level for my know-how.
Can you help?

I would be honored to have your name on these commits.
Can you make PRs?

**Comment by Ubiquitous** [comment]
That is definitely faster... on line 187
```
 p = (unsigned char *)r - 1;
```
consider changing to:
```
 p = (char *)r - 1;
```
otherwise it converts between pointers to integer types with different sign.

**Comment by ktsaou** [comment]
line 187 of which file?

**Comment by Ubiquitous** [comment]
The sample here:

https://ghostbin.com/paste/k5fz6

**Comment by ktsaou** [comment]
I changed the main(), like this:

```c
void main(void)
{
  char b1[30], b2[30], b3[30];
  unsigned long long c1 = 0, c2 = 0, c3 = 0;
  int i, j, k, x, m = 5000000;

  // Example of date: 2014-Apr-17 12:00:00.

  for(x = 0; x < m ;x++) {
    begin_tsc();
    i = buffer_jsdate(b1, 2014, x % 12, x % 30, x % 24, x % 60, x % 60);
    c1 += end_tsc();

    begin_tsc();
    j = buffer_jsdate2(b2, 2014, x % 12, x % 30, x % 24, x % 60, x % 60);
    c2 += end_tsc();

    begin_tsc();
    k = buffer_jsdate3(b3, 2014, x % 12, x % 30, x % 24 , x % 60, x % 60);
    c3 += end_tsc();
  }
  c1 /= x;
  c2 /= x;
  c3 /= x;

  printf("buffer_jsondate  'prints' \"%s\" (%d bytes long) in %llu cycles.\n"
         "buffer_jsondate2 'prints' \"%s\" (%d bytes long) in %llu cycles.\n"
         "buffer_jsondate3 'prints' \"%s\" (%d bytes long) in %llu cycles.\n",
         b1, i, c1,
         b2, j, c2,
         b3, k, c3);
}
```

compiled with this:

```
gcc -Wall -Wextra -O2 -mtune=native -o test test.c
```

and got these results:

```
buffer_jsondate  'prints' "Date(2014,7,19,7,19,19)" (23 bytes long) in 195 cycles.
buffer_jsondate2 'prints' "Date(2014,7,19,7,19,19)" (23 bytes long) in 127 cycles.
buffer_jsondate3 'prints' "Date(2014,7,19,7,19,19)" (23 bytes long) in 1872 cycles.
```

Every time I run it, I get the same results. So I guess this is the real measurement.
Can you explain why a single run reports so bigger numbers?

**Comment by Ubiquitous** [comment]
What's interesting is if you take the loop and change `buffer_jsdate`, `buffer_jsdate2`, and `buffer_jsdate3` to the same value for all three the results might be more revealing.
```
for(x = 0; x < m ;x++) {
	begin_tsc();
	i = buffer_jsdate(b1, 2014, x % 12, x % 30, x % 24, x % 60, x % 60);
	c1 += end_tsc();

	begin_tsc();
	j = buffer_jsdate(b2, 2014, x % 12, x % 30, x % 24, x % 60, x % 60);
	c2 += end_tsc();

	begin_tsc();
	k = buffer_jsdate(b3, 2014, x % 12, x % 30, x % 24 , x % 60, x % 60);
	c3 += end_tsc();
}
```
The original function frequently beats 'improved' version — they are very close. The improved one does save a few bytes from being stored in the buffer I think.

**Comment by fredericopissarra** [comment]
Well... TSC isn't that precise, you have to look for cache, TLBs and OS threads issues. It varies each time you measure... And have to take good care of compiler optimizations as well...

Notice: begin_tsc() make sure the processor is serialized calling cpuid with eax=0, before using rdtsc to read the timestamp. end_tsc() tries to do the same with rdtscp instruction (but this is not always correct).

I avoided to clear the caches and invalidate the TLBs to get values closest to the reality... And, of course, those values depends on the processor's architecture (Sandy Bridge, Haswell, Broadwell, etc).

Well... Measuring with a lot of interations and calculating the mean value helps, but this means, by your measures, that using sprintf() is faster that using the actual method, and for a single call this is false! sprintf() is 10 times slower.

**Comment by fredericopissarra** [comment]
@ktsaou, it will be a great pleasure to contribute to this beautiful project... I'll take a look at those 4 functions you mention... Is it ok to fork the project and submit pull requests? Or do you prefeer any other method?

**Comment by fredericopissarra** [comment]
And, you are absolutely correct about that casting to "unsigned char *", @Ubiquitous... My mistake! :)

**Comment by fredericopissarra** [comment]
I've tried other things to make this test faster... There are two divisions for month, day, hours, minutes and seconds (one integer division and another one to get the reminder)... But changing those two divisions with a call to div(), from stdlib, makes things worse...

The compiler otimizes those two divisions in just one anyway...

But, in the original code there are superfluous multiplications to get the reminder when calculating the digits of 'year'.... year=(year / 1000) * 1000 is the same as year %= 1000. MAYBE the compiler would optimize this (I have my doubts).

**Comment by fredericopissarra** [comment]
I don't know if this kind of "enhancement" will do any good, but I am taking a look on substituting select() syscalls do epoll API (Linux) and kqueue (FreeBSD)... Or, maybe, using libevent... This was not my ideia, it came from a friend who enjoyed the project as well...

epoll and libevent are really fast for multiple connections... select is old school, it works well, but it is slow...

**Comment by ktsaou** [comment]
> it will be a great pleasure to contribute to this beautiful project... I'll take a look at those 4 functions you mention... Is it ok to fork the project and submit pull requests? Or do you prefeer any other method?

PRs are perfect.

**Comment by ktsaou** [comment]
This is merged with #299

**Comment by ktsaou** [comment]
@fredericopissarra I think we can close this.

**Comment by ktsaou** [comment]
cleaning up.
