### ISSUE TITLE
[question] Restart SytemD and OperRC services

### ISSUE THREAD

**Issue by archenroot** [firehol/netdata#2554]
Hello,

first of all thanks for this comprehensive monitoring beast. I was playing with lot and wasn't happy with any or was forced to jump into payed enterprise tools, but netdata really broke me down (in positive way) so far,and I am still studying it💃 

I have previously build small web GUI for checking status of services on remote Linux machines with capability to retrieve error reason from the relevant log file and show it and also allow the user to manage the service (stop/restart/start). Is this possible to achieve in as is netdata or if not, could someone point me with right direction about where to do changes to bring this support?

**Comment by archenroot** [comment]
I have also plugin for my GUI in Java where I can click on the host or service and it pop-ups terminal windows, so I can directly look at the server issues via SSH, is there something like this possible?

**Comment by Ferroin** [comment]
I think this might be beyond the scope of netdata, there are already quite a few existing tools to do this, one of the most notable examples probably being [monit](https://mmonit.com/monit/) (FWIW, netdata plus monit is probably one of the most complete open source monitoring solutions available).

As far as a remote terminal, that's almost certainly beyond the scope of netdata (not to mention again that tools that already do that exist).

Keep in mind netdata is a _monitoring_ tool, not a system management tool.

**Comment by archenroot** [comment]
@Ferroin I understand, well on this project I have small infrastructure (30 servers) and I am still looking for something comprehensive ALL in ONE solution 👯‍♂️ 

But I understand your point of course, thanks for the feedback. Closing this.
