### ISSUE TITLE
compile for ti-am335x

### ISSUE THREAD

**Issue by soso7885** [firehol/netdata#2556]
Hi  I want to use this tool to my board which use ti-am335x soc, but cannot build it, I host is ubuntu 14.04, here is my step:
1.  ./autogen.sh
2.  ./configure --host=arm-linux-gnueabihf --with-zlib --with-math --with-user=netdata 
3.   make

arm-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I..  -DVARLIB_DIR="\"/usr/local/var/lib/netdata\"" -DCACHE_DIR="\"/usr/local/var/cache/netdata\"" -DCONFIG_DIR="\"/usr/local/etc/netdata\"" -DLOG_DIR="\"/usr/local/var/log/netdata\"" -DPLUGINS_DIR="\"/usr/local/libexec/netdata/plugins.d\"" -DRUN_DIR="\"/usr/local/var/run/netdata\"" -DWEB_DIR="\"/usr/local/share/netdata/web\""          -g -O2 -pthread -MT apps_plugin.o -MD -MP -MF .deps/apps_plugin.Tpo -c -o apps_plugin.o apps_plugin.c
In file included from apps_plugin.c:8:0:
common.h:85:23: fatal error: uuid/uuid.h: No such file or directory
compilation terminated.

see the log, cannot find "uuid/uuid.h", how can I fix it ?

**Comment by ktsaou** [comment]
You need the `uuid-dev` package installed.
Is this cross compilation?

**Comment by soso7885** [comment]
so I need to compiling uuid-dev for am335x?

**Comment by ktsaou** [comment]
Did you solved it?

**Comment by markwone** [comment]
> Did you solved it?

Hi I want to use this tool to my board which use zynq 7020 soc,I cross compile the lib uv,uuid,zlib.and cross build netdata success by xilinx compile tool chain。then make it run on zynq ，but zynq have not  Browser，so I want connect with win 10 pc by usb rndis，I can ping the zynq，but http con't connect  the netdata。 have you try run netdata on same Embedded platform？

**Comment by markwone** [comment]
> > Did you solved it?
> 
> Hi I want to use this tool to my board which use zynq 7020 soc,I cross compile the lib uv,uuid,zlib.and cross build netdata success by xilinx compile tool chain。then make it run on zynq ，but zynq have not Browser，so I want connect with win 10 pc by usb rndis，I can ping the zynq，but http con't connect the netdata。 have you try run netdata on same Embedded platform？

it work，thx
