### ISSUE TITLE
allow charts to specify the symbol for digit grouping

### ISSUE THREAD

**Issue by BrainDoctor** [firehol/netdata#2557]
In countries such as Germany and Switzerland, where Commas are often used as a decimal delimiter instead of a period, it is rather confusing when a chart is displaying the digit grouping symbol as a comma.

It would be helpful if it can be changed.

Example:
![comma as digit grouping](https://user-images.githubusercontent.com/12159026/28939419-8f47707a-7891-11e7-8012-66b33205e401.png)

In this screenshot, it can be read as 7.306 kilobytes/s, when really it is 7306. Using the comma for digit grouping (separation of thousands, millions, etc) is confusing.

![dot as decimal delimiter](https://user-images.githubusercontent.com/12159026/28939434-9992ef5a-7891-11e7-999e-74a5618ddf4c.png)

Now when the charts constantly switch between these two representations, it is not clear which one's what.

I would welcome it if I can set the digit grouping symbol to `'`, (single quote), which is most commonly used in my country.

**Comment by ktsaou** [comment]
Hi,

this is controlled by your web browser. If you set your web browser to the right locale, all numbers will be personalized for you.

To check it, press F12 on your browser, switch to the console tab and type:

```
console.log(new Intl.NumberFormat(undefined).format(1050.2));
```

According to the javascript docs:

> The locales argument must be either a string holding a BCP 47 language tag, or an array of such language tags. If the locales argument is not provided or is undefined, the **runtime's default locale** is used.

So, your runtime default locale is probably wrong..

**Comment by BrainDoctor** [comment]
This was indeed the case. So I changed the language in the android tablet, but that just resulted in the decimal digit being the comma and the grouping digit the period (just replaced eachother, which is even more confusing!). This is very disappointing by Samsung, but clearly not netdata's fault.
