### ISSUE TITLE
netdata reports updates on two servers, running update script reports I'm up to date.

### ISSUE THREAD

**Issue by ZoeyCluff** [firehol/netdata#2558]
I installed netdata using your script on two of my servers. when I load netdata it's saying it's out of date with update instructions.

Fri Aug  4 07:51:51 UTC 2017 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Fri Aug  4 07:51:51 UTC 2017 : INFO:  Updating netdata source from github...
Already up-to-date.
Fri Aug  4 07:51:51 UTC 2017 : INFO:  Nothing to be done! (use -f to force re-install)
➜  cron.daily 

The site reports:

Your netdata version: 1.7.0-101-g6597990c_rolling
Your netdata commit: 6597990 
New version of netdata available!

Latest commit: df95739

**Comment by ktsaou** [comment]
hm...

Please do these:

```
cd /usr/src/netdata.git # or anywhere else you have netdata source

git fetch --all
git reset --hard origin/master
git pull
./netdata-updater.sh -f
```

Is it fixed?

If not, please post your `.git/config`

**Comment by ZoeyCluff** [comment]
It did install something new when I do the updater.

the .git config is 

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/firehol/netdata.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

Looking into ChangeLog it's saying netdata (1.7.0) - 2017-07-16

**Comment by ZoeyCluff** [comment]
Running those commands on both servers appears to have fixed the problem (testing on server 2 now). it also helps to not have netdata installed on server1 also installed via apt.

**Comment by ktsaou** [comment]
ok, on the failing server, there is the file `./src/web/version.txt`

This file should be copied to `/usr/share/netdata/web/version.txt`.

Could you please post both files?

**Comment by ZoeyCluff** [comment]
don't know which directory to look for for the first (no web folder at /usr/src/netdata.git/src)

/usr/share reports: df957395370e656a9961a5b3cfa8d4db80801282

**Comment by ktsaou** [comment]
Yes, my bad: `/usr/src/netdata.git/web/version.txt`

**Comment by ZoeyCluff** [comment]
df957395370e656a9961a5b3cfa8d4db80801282

**Comment by ktsaou** [comment]
Then both files show the same and this is the latest.
What does the dashboard show? It should show that one.

**Comment by ZoeyCluff** [comment]
Your netdata version: 1.7.0-116-g2218107e_rolling
Your netdata commit: 2218107 
New version of netdata available!

Latest commit: df95739

Click here for the changes log since your installed version, and
click here for directions on updating your netdata installation.

We suggest to review the changes log for new features you may be interested, or important bug fixes you may need.
Keeping your netdata updated, is generally a good idea.

**Comment by ktsaou** [comment]
In the meantime the latest is newer.
Mine shows:

```
Your netdata version: 1.7.0-119-gdf957395_rolling
Your netdata commit: df95739 

You already have the latest netdata!
```

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
