### ISSUE TITLE
Crash after few minute

### ISSUE THREAD

**Issue by ivandal77** [firehol/netdata#2559]
Dear,
after a minute of working netdata crash:

`[78942.950145] netdata[21621]: segfault at 0 ip 00007fed52253c31 sp 00007fed4779cf98 error 4 in libc-2.17.so[7fed521cd000+1b8000]
`

netdata version:

`netdata 1.7.0-116-g2218107_rolling
`

system:

`LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseWorkstation
Description:    Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo
`

kernel:
`Linux netmanager.fbk.eu 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

I am getting crazy,
any help?
Thanks a lot,

Ivan

**Comment by ktsaou** [comment]
I'll need you help to trace the issue.

Can you install `valgrind` on this machine? If yes, I can give you a few instructions to trace it. Otherwise, I'll need to find access to a RHEL 7.4 to trace it.


If you can install `valgrind` do these:

```sh
sudo su

cd /usr/src/netdata.git  # or anywhere else you have the netdata source

# compile netdata with debug info
CFLAGS="-O1 -ggdb" ./netdata-installer.sh --dont-start-it

# stop netdata
systemctl stop netdata

# run netdata through valgrind
valgrind ./src/netdata -D
```

It will be slower now. Let it run like that until it crashes.
Post the output here.

**Comment by ktsaou** [comment]
I installed RHEL 7.4 on a VM.

I am running netdata on it without issues.

Is there anything special about you server?

**Comment by ivandal77** [comment]
Dear,
nothing special.
On Monday I try your suggestions and post here the output.
Thanks again,
Ivan

Il 04 Ago 2017 8:19 PM, "Costa Tsaousis" <notifications@github.com> ha
scritto:

**Comment by BrainDoctor** [comment]
hmm my guess is that your libc-dev is broken somehow. I just had a similar error today where I couldn't start ssh server. It turned out that I had to reinstall the mentioned package. I used the command `dpkg --search $(debsums -sc)` to find all broken packages. Debian's debsums is the key though, which compares the MD5 sums of the package files. I then reinstalled it with `apt-get --reinstall install libc6-dev` and others. I hope there is a similar tool in RHEL.

**Comment by ivandal77** [comment]
Thanks to all,
@ktsaou I have done some test recompiling netdata and running with valgrind.
But the only error we obain is related to valgrind itself!! :-(

`--32415:0: aspacem Valgrind: FATAL: VG_N_SEGMENTS is too low.
--32415:0: aspacem   Increase it and rebuild.  Exiting now.
`

The special about the server is that netdata is collecting data from ~140 Linux other servers.
Any other suggestion?
Thanks,

Ivan

**Comment by ktsaou** [comment]
hm... this does not seem netdata related. Let me read a bit about it.

Please also check `sysctl vm.max_map_count`. netdata needs 1 mmap per metric and one per chart. So, if you have 200 charts and 1500 metrics per server, you will need `1700 * 140 = 238.000`. I would suggest to set it to 500000 or 1 mil.

**Comment by ktsaou** [comment]
Is seems that the memory allocations made by netdata overflow the valgrind internal structures and valgrind requires recompiling to increase them.

My guess is that the suggestion I gave you above will fix the problem.

**Comment by ivandal77** [comment]
Dear,
valgrind compiled with new VG_N_SEGMENTS value, `vm.max_map_count` increased to 1 mil.
Netdata is still crashing, [here](https://pastebin.com/MHTJx0Wx) is the valgrind output.
The old 1.6 was working without error.
Thanks,
Ivan

**Comment by ktsaou** [comment]
thanks!

It seems that it gets a NULL title on a chart from a slave. I am making a PR now to catch this case.

**Comment by ktsaou** [comment]
Could you please install `https://github.com/ktsaou/netdata` and retry?
If it still crashes, please post a valgrind dump again.

**Comment by mvivaldi** [comment]
Hi, I'm a colleague of ivandal77, I installed the new version and it seems to work (it didn't crash in the last hour... usually it crash in about 5 minutes). 

Thank you 

P.S. ivandal77 will report back tomorrow if something change

**Comment by ktsaou** [comment]
merged the fix.
If the issue remains, please post here.
