### ISSUE TITLE
mysql_socket4 _get_data() returned no data or type is not <dict>

### ISSUE THREAD

**Issue by beardedeagle** [firehol/netdata#2560]
I am trying to set up mysql monitoring and getting the following errors:
```
2017-08-04 14:49:21: python.d ERROR: DISABLED: mysql/socket3
2017-08-04 14:49:21: python.d ERROR: mysql_socket4 _get_data() returned no data or type is not <dict>
2017-08-04 14:49:21: python.d ERROR: mysql_socket4 check() failed - disabling job
2017-08-04 14:49:21: python.d ERROR: DISABLED: mysql/socket4
2017-08-04 14:49:21: python.d ERROR: mysql_socket5 _get_data() returned no data or type is not <dict>
2017-08-04 14:49:21: python.d ERROR: mysql_socket5 check() failed - disabling job
2017-08-04 14:49:21: python.d ERROR: DISABLED: mysql/socket5
2017-08-04 14:49:21: python.d ERROR: mysql_socket6 _get_data() returned no data or type is not <dict>
2017-08-04 14:49:21: python.d ERROR: mysql_socket6 check() failed - disabling job
2017-08-04 14:49:21: python.d ERROR: DISABLED: mysql/socket6
2017-08-04 14:49:21: python.d ERROR: mysql_socket7 _get_data() returned no data or type is not <dict>
2017-08-04 14:49:21: python.d ERROR: mysql_socket7 check() failed - disabling job
2017-08-04 14:49:21: python.d ERROR: DISABLED: mysql/socket7
```
My config:
```
socket1:
  name: 'local'
  'my.cnf' : '/etc/db1.cnf'
  socket: '/run/mysql/db1.sock'
socket2:
  name: 'local'
  'my.cnf' : '/etc/db2.cnf'
  socket: '/run/mysql/db2.sock'
socket3:
  name: 'local'
  'my.cnf' : '/etc/db3.cnf'
  socket: '/run/mysql/db3.sock'
socket4:
  name: 'local'
  'my.cnf' : '/etc/db4.cnf'
  socket: '/run/mysql/db4.sock'
socket5:
  name: 'local'
  'my.cnf' : '/etc/db5.cnf'
  socket: '/run/mysql/db5.sock'
socket6:
  name: 'local'
  'my.cnf' : '/etc/db6.cnf'
  socket: '/run/mysql/db6.sock'
socket7:
  name: 'local'
  'my.cnf' : '/etc/db7.cnf'
  socket: '/run/mysql/db7.sock'
```
And I gave `CONNECT` grant to the `netdata` user. But all I get is those errors the error.log and the charts don't show in the dashboard. Is there something I am missing here?

**Comment by beardedeagle** [comment]
Additional info:
```
Your netdata version: 1.7.0-119-gdf957395_rolling
Your netdata commit: df95739 

PyMySQL==0.7.11
```

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/2500

Looks like current version of mysql plugin only works with python-mysqldb.

**Comment by beardedeagle** [comment]
I'll take a look at fixing the plugin code then

**Comment by ktsaou** [comment]
> Looks like current version of mysql plugin only works with python-mysqldb.

@l2isbad I thought `pymysql` is not able to parse `my.cnf` properly but it works if the python plugin is configured not to use `my.cnf`. Am I right?

**Comment by l2isbad** [comment]
@ktsaou 
It was a assumption based on this issue and https://github.com/firehol/netdata/issues/2500.

I just checked and everything works with python-pymysql (0.7.6-1~bpo8+1).

**Comment by l2isbad** [comment]
But sure there is something wrong with `mysql plugin` (or `MysqlService`) because of 2 issues with same errors (`pymysql`). But i can't reproduce the error so far.

**Comment by ktsaou** [comment]
ok thanks!

the idea is that if it does not work, we should remove it and update the docs.

In general, pymysql is a python-only implementation and is significantly slower the pymysqldb. But it would be nice to support it, for cases that pymysqldb cannot be installed.

**Comment by beardedeagle** [comment]
That's my specific issue, I cannot use `pymysqldb` due to the `mysql-devel` package req.

don't know if it will help, but `pymysql` has the following:
`pymysql.install_as_MySQLdb()`

**Comment by ktsaou** [comment]
I see this ticket is probably incomplete.
@l2isbad is there anything pending with this? Is pymysql supported?

**Comment by l2isbad** [comment]
> Is pymysql supported?

Yes

> But i can't reproduce the error so far.

> I just checked and everything works with python-pymysql (0.7.6-1~bpo8+1, 0.7.11).

And I see the commit to [disable "my.cnf" parsing when using "pymysql"](https://github.com/firehol/netdata/commit/bc50c1d999f16be4818b8df1bf53b4dd7fb84ba7)

**Comment by ktsaou** [comment]
ok thanks!
So, cleaning up. @beardedeagle if you need more help, or if it does not work for you, please post here to find a solution.
