### ISSUE TITLE
Cannot open file '/proc/diskstats' entries appear every second in error.log

### ISSUE THREAD

**Issue by hazarkarabay** [firehol/netdata#2561]
I'm using netdata in a OpenVZ container. It works, but every second it logs an error to error.log, because there are no `/proc/diskstats` exposed to the container. 

Can I prevent this without disabling the entire error.log?

ps: OpenVZ support was "enabled" at some point, some discussions that I found at: https://github.com/firehol/netdata/issues/1369
Probably this error.log issue introduced by that.

error.log
```
...
2017-08-06 18:50:44: netdata ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-08-06 18:50:45: netdata ERROR: PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2017-08-06 18:50:46: netdata Too many logs (201 logs in 200 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1000 seconds.
```

**Comment by ktsaou** [comment]
Hi,

netdata has a protection for such flood that I see has kicked in.

You have a few options:

1. leave it like that. 200 log lines per hour will be logged
2. disable `/proc/diskstats` in `netdata.conf`

```
[plugin:proc]
	/proc/diskstats = no
```


3. if you own the host and you want to monitor all of it, with netdata running in a container, expose `/proc`, `/sys`, `/dev` from the host to a `/host` directory of the container and set in `netdata.conf`:

```
[global]
	host access prefix = /host
```

4. if you own the host, netdata can monitor everything about it, if you install it at the host. There will be no need to run netdata in containers. I am not familiar with OpenVZ hosts though. I know for sure that the static 64 bit binary netdata can be installed everywhere a Linux kernel runs. So, most probably can work on OpenVZ hosts.

**Comment by hazarkarabay** [comment]
Hi,
The error.log takes ~2Mb daily, not that is taking a huge space or something but still it was logging unnecessary information.

Disabling `/proc/diskstats` in `netdata.conf` solved it. I searched about it before posting and can't find it, Sorry if it was already documented somewhere.

(for 3 and 4: I don't own the host but thanks for the information anyway)

Thanks!
