### ISSUE TITLE
easypieChart: How to use average value instead of sum?

### ISSUE THREAD

**Issue by qdore** [firehol/netdata#2565]
I found that chart librarise is use sum value, could it use average value?

**Comment by ktsaou** [comment]
sum or average of what exactly?

By default easypiecharts return the average of the sum of all dimensions of a chart throughout a timeframe.

So, if we have a chart that refreshes per second and we want an easypiechart that shows the average of the last 10 seconds, it will show the 10 second average of the sum of all dimensions of the chart.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
