### ISSUE TITLE
statsd 64bit values not graphing correctly

### ISSUE THREAD

**Issue by kellabyte** [firehol/netdata#2568]
I'm using statsd to push price graphs to netdata but netdata is not displaying correctly values that are really low.

For example, if I push a gauge with values in the `0.00562490` range the graph displays like this.

![screen shot 2017-08-07 at 12 39 46 pm](https://user-images.githubusercontent.com/676347/29036709-82925a18-7b6e-11e7-8398-023a67442d82.png)

If I multiply the value it displays much better.
![screen shot 2017-08-07 at 12 41 08 pm](https://user-images.githubusercontent.com/676347/29036711-8a84573a-7b6e-11e7-89c3-4c5a93ccd1ae.png)

This is wrong though because it misleads the user and each price of different things are going to be different. Is there a way to adjust the graph to handle larger and smaller values correctly? It seems like the graphing library isn't handling these correctly?

**Comment by ktsaou** [comment]
Hi,

netdata  data collection works with signed 64 bit integer values, which are converted to floating point using multipliers and dividers. This is throughout netdata.

For statsd gauges I have hardcoded them to have 3 fractional digits.

I think there should a config option for that.

I am making a PR now.

**Comment by kellabyte** [comment]
Awesome! Thank you so much. How do I take advantage of this config option?

**Comment by ktsaou** [comment]
edit netdata.conf and set:

```
[statsd]
	decimal detail = 1000
```

The default is `1000` which gives 3 fractional digits.
Set it to the number you want (i.e. 1, 10, 100, 1000, 10000, 100000, 1000000, etc).

**Comment by ktsaou** [comment]
Install `https://github.com/ktsaou/netdata`. This version includes PR #2566

**Comment by kellabyte** [comment]
If I have netdata already installed, what is the best way to update/re-install?

**Comment by ktsaou** [comment]
I merged the update, so just re-install netdata the same way you did before.

Alternatively, if you installed from source, in the netdata source directory there should be a script called `netdata-updater.sh`. Just run it.

**Comment by kellabyte** [comment]
I re-ran `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` and then added this to the `netdata.conf`

```
[statsd]
        # enabled = yes
        # update every (flushInterval) = 1
        # udp messages to process at once = 10
        # create private charts for metrics matching = *
        # max private charts allowed = 200
        # max private charts hard limit = 1000
        # private charts memory mode = save
        # private charts history = 3996
        # histograms and timers percentile (percentThreshold) = 95.00000
        # add dimension for number of events received = yes
        # gaps on gauges (deleteGauges) = no
        # gaps on counters (deleteCounters) = no
        # gaps on meters (deleteMeters) = no
       # gaps on histograms (deleteHistograms) = no
        # gaps on timers (deleteTimers) = no
        # listen backlog = 4096
        # default port = 8125
        # bind to = udp:localhost tcp:localhost
        decimal detail = 10000000
```

but I'm still only seeing values of `0.0000` and values like `0.00060164` are showing up as `0.0006` constant and won't show an update such as `0.00060999` for example.

Did I update wrong?

**Comment by ktsaou** [comment]
I think it is ok, but we hit other problems.

Let me explain.

I tested your 2 values  `0.00060164` and `0.00060999` and this is the chart I got:

![screenshot from 2017-08-08 22-45-17](https://user-images.githubusercontent.com/2662304/29091358-56cb13de-7c8b-11e7-810b-925a5586d7d6.png)

As you can see, the chart shows a difference. I checked the values in the db. They are right (the netdata db has 7 fractional digits precision).

However, they are exported to the dashboard as `0.00060` and `0.00061`: the function that renders numbers to JSON, has 5 fractional digits precision.

Then there is another problem. The dashboard has another (stupid) limitation, showing all legends with up to 4 fractional digits.

So, this is a bug. All netdata functions should support up to 7 fractional digits.

The fix requires some peace of mind to do it properly, and I am on a trip until Aug 21st. So, I will fix this as soon as I come back. Until then, you can safely visualize 5 fractional digits (the legends will show 4, but the chart will render 5).

Sorry for all these. I didn't realize there are such discrepancies on small numbers.

**Comment by ktsaou** [comment]
I opened issue #2573 to remember to fix it.

**Comment by kellabyte** [comment]
Great, thanks so much for all the wonderful feedback and help :) I'll use it as-is and I'll give it a test once you're back and you have time to tackle it. Thanks again so much!

**Comment by ktsaou** [comment]
In https://github.com/ktsaou/netdata I have fixed the internal netdata limitation, so that netdata generates JSON output with up to 7 fractional digits.

You can install it and try it. The chart will still show just 4 digits on the legends, but the the graph will have 7 digits detail.

**Comment by ktsaou** [comment]
PR #2577

**Comment by ktsaou** [comment]
updated the PR to have the chart legends render up to 7 fractional digits.
![screenshot from 2017-08-10 03-00-48](https://user-images.githubusercontent.com/2662304/29148748-239ca994-7d78-11e7-8cab-828b0b822149.png)

**Comment by ktsaou** [comment]
merged the fix
