### ISSUE TITLE
Postgres permission denied for database rdsadmin

### ISSUE THREAD

**Issue by luvpreetsingh** [firehol/netdata#2569]
I am using the latest netdata on ubuntu 14.04.

I am trying to make a connection to postgresql db on my remote server.
Here is the config, 

    tcpipv4:
        name     : 'Postgres2'
        database : 'test_db'
        user     : 'xxxx'
        password : 'xxxxx'
        host     : 'XXXX-db-rds.amazonaws.com'
        port     : XXXX

Firstly, I did not get what is the difference between tcp and tcpipv4 connection?

Now, I am getting this error, 

    alphauser@AlphaServer:/var/log/netdata$ sudo /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 postgres
    .
    .
    2017-08-08 12:24:46: python.d DEBUG: postgres/tcpipv4: job added
    .
    . 
    2017-08-08 12:24:47: python.d INFO: CHECKED OK: postgres_tcpipv4
    2017-08-08 12:24:47: python.d INFO: RENAMED: postgres_Postgres2 , from postgres_tcpipv4
    .
    .
    2017-08-08 12:24:47: python.d ERROR: postgres_Postgres2 permission denied for database rdsadmin

    2017-08-08 12:24:47: python.d ERROR: DISABLED: postgres/Postgres2
    2017-08-08 12:24:47: python.d FATAL: no more jobs
    DISABLE

The current user only has read only access to this database. Do we need write access for this also ?
What is this connection error ?

**Comment by ktsaou** [comment]
Hi,

I think real-only access is needed. But I am not an expert on postgres.

@facetoe @l2isbad any ideas what is wrong with this setup?

**Comment by facetoe** [comment]
You only need read permission so that's fine. Can you confirm that you are able to access the database using with the exact same parameters using `psql`?

**Comment by luvpreetsingh** [comment]
No, I don't have any access to that.

But why is it required ? I am using some different database to connect to.

**Comment by facetoe** [comment]
It would be helpful to confirm whether or not you can connect and run simple queries using another program.

Looking at the error again, it could be that your user does not have read permissions on the `rdsadmin` database. If you modify your config and include only your `test_db` database in the `database_poll` option do you still have the error?

**Comment by luvpreetsingh** [comment]
Yes.

I added `database_poll : test_db`, and it worked.

**Comment by facetoe** [comment]
Excellent, glad it's working.

**Comment by facetoe** [comment]
@ktsaou I think this counts as a bug. The check succeeds but then the plugin fails afterwards due to what seems to be a permissions issue on the `rdsadmin` db. When I get the chance I'll spin up an instance on RDS and do a bit of investigation. If it is indeed a permissions issue then I think the `FIND_DATABASES` query should be modified to only return those database that the plugin can successfully gather data on.

**Comment by luvpreetsingh** [comment]
I think it is an exception for Amazon RDS.

**Comment by ktsaou** [comment]
@facetoe I marked it as bug.
It is yours to fix. Thanks!

**Comment by luvpreetsingh** [comment]
> Firstly, I did not get what is the difference between tcp and tcpipv4 connection?

What about my this question ?

**Comment by facetoe** [comment]
Looks like `tcp` is either ipv4 or ipv6 as 'localhost' could resolve to any one of them while `tcpipv4` is a IPv4 address (127.0.0.1).

I don't think they make any difference as it is just the default job name.

**Comment by luvpreetsingh** [comment]
Look here, https://github.com/firehol/netdata/blob/master/conf.d/python.d/postgres.conf

There are 3 options.

> I don't think they make any difference as it is just the default job name.

 It works fine for sure, but why make a confusion ?

**Comment by facetoe** [comment]
Ahhh, those are used for auto discovery, they are not really options. When netdata is first installed and this plugin is loaded it will:

* try to connect to the unix socket as the postgres user
* resolve localhost and attempt to connect as the postgres user (if localhost is missing from /etc/hosts this can fail)
* attempt to connect on an IPv4 address (127.0.0.1)
* attempt to connect on an IPv6 address (::1) 

If none of the above succeed then the plugin is disabled.

**Comment by ktsaou** [comment]
merged the fix.
Shall we keep this issue open?

**Comment by facetoe** [comment]
I don't think so. The bug is fixed and all questions answered. Should be good to close.
