### ISSUE TITLE
MySQL chart dosen't show

### ISSUE THREAD

**Issue by vahit** [firehol/netdata#2570]
Hi guys.
I installed netdata on docker container, to this work i use as alpine image, run netdata with **root** user. I config it to run as headless and send all informations to another netdata on other container (for that i use as `/etc/netdata/stream.conf` file and api key configuration)  All default charts is OK.
I try enable mysql python plugin, 
**/etc/netdata/python.d/mysql.conf:**
```
update_every  : 10
priority      : 10
retries       : 5

local:
  name  : 'db-2'
  user    : 'netdata'
  host    : 'X.X.X.X'
  port    : '3306'
```
I config  `netdata` user on MySQL to connect without password and it cloud run `SHOW SALVE STATUS;` command.
enable mysql on `/etc/netdata/python.d.config` file:
```
enabled: yes
default_run: yes
mysql: yes
```
and in last step i install `py-mysqldb` package which is the equivalent of `python-mysqldb` in alpine.
When i run debug command:
```
/usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
```
it stream data successfully, log file: https://gist.github.com/vahit/e565afb3539b28db7f1082086aa28bc3
but mysql chart doesn't appear on dashboard!!
What's the problem and How can i resolve it?

**Comment by ktsaou** [comment]
Most probably there is a permission issue on the mysql server.
What does `/var/log/netdata/error.log` say about mysql?

**Comment by vahit** [comment]
https://gist.github.com/vahit/1f2f5087b4333fd668a67a70951fe0b8
Do you have any ideas?

**Comment by l2isbad** [comment]
> 2017-08-08 09:50:53: python.d ERROR: mysql_DATABASssssE MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
> 2017-08-08 09:50:53: python.d ERROR: mysql_DATABASssssE check() failed - disabling job
> 2017-08-08 09:50:53: python.d ERROR: DISABLED: mysql/DATABASssssE

https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L32-L40

https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L1044-L1046

**Comment by vahit** [comment]
I installed `py-mysqldb` whish that is equivalent of `python-mysqldb` base on #2560 
Anyway i have `MySQLdb` module:
```
bash-4.3# python
Python 2.7.13 (default, Apr 20 2017, 12:13:37) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>> dir(MySQLdb);
['BINARY', 'Binary', 'Connect', 'Connection', 'DATE', 'DATETIME', 'DBAPISet', 'DataError', 'DatabaseError', 'Date', 'DateFromTicks', 'Error', 'FIELD_TYPE', 'IntegrityError', 'InterfaceError', 'InternalError', 'MySQLError', 'NULL', 'NUMBER', 'NotSupportedError', 'OperationalError', 'ProgrammingError', 'ROWID', 'STRING', 'TIME', 'TIMESTAMP', 'Time', 'TimeFromTicks', 'Timestamp', 'TimestampFromTicks', 'Warning', '__all__', '__author__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__revision__', '__version__', '_mysql', 'apilevel', 'connect', 'connection', 'constants', 'debug', 'escape', 'escape_dict', 'escape_sequence', 'escape_string', 'get_client_info', 'paramstyle', 'release', 'result', 'server_end', 'server_init', 'string_literal', 'test_DBAPISet_set_equality', 'test_DBAPISet_set_equality_membership', 'test_DBAPISet_set_inequality', 'test_DBAPISet_set_inequality_membership', 'thread_safe', 'threadsafety', 'times', 'version_info']
>>>
```
and when i run debug command it could connnect to mysql and fetch datas. it's that log: https://gist.github.com/vahit/e565afb3539b28db7f1082086aa28bc3

**Comment by l2isbad** [comment]
> and when i run debug command

Did you run it as user netdata ? (`sudo su -s /bin/bash netdata`)

**Comment by vahit** [comment]
Why should i do this?
All of netdata process run as **root** user:
```
bash-4.3# ps ax | grep -i netdata
    1 root      27:36 /usr/sbin/netdata -D -u root -s /host
   24 root       9:58 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
  314 root       4:41 /usr/libexec/netdata/plugins.d/apps.plugin 1
  316 root       0:00 grep -i netdata
bash-4.3# 
```
and with the root user debug command return true output!!

**Comment by l2isbad** [comment]
default is https://github.com/firehol/netdata/wiki/netdata-security#your-systems-are-safe-with-netdata

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.

**Comment by pajarraco** [comment]
Hi, I get this error when I try to install the plugin

'# /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
2018-07-24 09:42:13: python.d INFO: plugin: main: Using python 2
2018-07-24 09:42:13: python.d DEBUG: plugin: main: module load source: 'mysql' => [OK]
2018-07-24 09:42:13: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
2018-07-24 09:42:13: python.d ERROR: plugin: main: load config error : expected '', but found ''
in "/usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d/mysql.conf", line 106, column 1
2018-07-24 09:42:13: python.d DEBUG: plugin: main: job initialization: 'mysql mysql' => ['OK']
2018-07-24 09:42:13: python.d DEBUG: plugin: main: module status: 'mysql' => [OK] (jobs: 1)
2018-07-24 09:42:13: python.d ERROR: mysql: mysql: Connection properties are missing
2018-07-24 09:42:13: python.d INFO: mysql: mysql: check() => [FAILED]
2018-07-24 09:42:13: python.d INFO: plugin: main: FINISHED

**Comment by l2isbad** [comment]
yo @pajarraco 

I see

> 2018-07-24 09:42:13: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
> 2018-07-24 09:42:13: python.d ERROR: plugin: main: load config error : expected '', but found ''
> in "/usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d/mysql.conf", line 106, column 1

That is why 

> 2018-07-24 09:42:13: python.d ERROR: mysql: mysql: Connection properties are missing

Check the config please

**Comment by pajarraco** [comment]
Thanks, I fix it, I miss to put 
"local:" on /etc/netdata/python.d/mysql.conf
