### ISSUE TITLE
Netdata installation: Build and compilation error 

### ISSUE THREAD

**Issue by csebiplob** [firehol/netdata#2572]
**Build and compilation error while installing netdata:**
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name...
configure: error: in `/opt/epic/administration/sources/netdata':
configure: error: C compiler cannot create executables
See `config.log' for more details.
FAILED

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

**Comment by BrainDoctor** [comment]
I had a similar issue in #2502, where I ended up downgrading gcc from 4.9 to 4.8

However, I believe that actually the `libc6-dev` package that was broken. I suggest you run 

`apt-get install debsums`
and then 
`dpkg --search $(debsums -sc)` (this might take a few minutes, but it displays all broken packages) and reinstall the relevant packages.

**Comment by csebiplob** [comment]
Thanks for your response.
I am trying to install on Redhat 6.7 . would you please give me actual
command that will help me to sort out.

Best Regards
Biplob

**Comment by BrainDoctor** [comment]
I'm afraid I don't know the commands for RHEL. My idea is basically to find out which packages are broken and then reinstall them. I expect it's possible for RHEL too to compare the MD5 sums of the installed packages. You may need to google on that.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
