### ISSUE TITLE
The installer continues on CTRL+D

### ISSUE THREAD

**Issue by Licenser** [firehol/netdata#2574]
When the installer asks
```
Press ENTER to build and install netdata to '/opt/netdata' >
```
and a user presses CTRL+D to close the STDIN and cancel the installation.

The installer happily decides to continue.

**Comment by ktsaou** [comment]
Hi.

Thanks! I have submitted patches to fix this.
PR #2577

**Comment by ktsaou** [comment]
merged the fix
