### ISSUE TITLE
can't set a group different form the user

### ISSUE THREAD

**Issue by Licenser** [firehol/netdata#2575]
`netdata -u` enforces to have a group that is the same as the username, if that doesn't exist you are out of luck.

**Comment by ktsaou** [comment]
Hi,

I think that "you are out of luck" means that the default `web files group` option is incorrectly set to the username netdata runs as, ignoring the effective group of the given user.

I have fixed that in PR #2577 
Now `web files owner` and `web files group` default to user and group netdata runs as and they are independent to each other.

**Comment by ktsaou** [comment]
merged the fix
