### ISSUE TITLE
Suspicious File Alert

### ISSUE THREAD

**Issue by Nirjonadda** [firehol/netdata#2580]
I am getting lot of email from CSF - lfd : Suspicious File Alert. Please let me know this fix.

````
Time:  Wed Aug  9 17:50:06 2017 -0600
File:  /tmp/.netdata-charts.d-j9YzuBV3Om
Reason: Suspicious directory
Owner:  netdata:netdata (985:982)
Action: No action taken
````

**Comment by ktsaou** [comment]
Hi,

suspicious of what?

This directory is created by `charts.d.plugin` of netdata while it runs. It is legit, except if I am missing something.

**Comment by Nirjonadda** [comment]
Yes, This directory is created by netdata but ConfigServer Security & Firewall send email Alert from this files because Suspicious File.

**Comment by Ferroin** [comment]
So in other words, your over-zealous IDS software is throwing a false positive because it thinks the files shouldn't be there.  This is something you need to take up with the vendor for that software, just like if you get a false positive from a virus scanner.

**Comment by Nirjonadda** [comment]
Please check from command line ````.```` The filename starts with dot and it will be normally hidden .

Just do fom command line.
````
rm -rf /tmp/.netdata-charts.d-WimwdJhhwF
rm -rf/tmp/.netdata-charts.d-j9YzuBV3Om
````

**Comment by Ferroin** [comment]
Again, CSF is just throwing a false positive.  This type of thing happens all the time with new software (and netdata is pretty new) when dealing with both IDS and AV software.  The standard procedure for dealing with it is to ask the vendor of the IDS or AV software to whitelist the new software.  This means you need to talk to the CSF developers about getting this whitelisted.

**Comment by ktsaou** [comment]
@Nirjonadda I am not sure I can do anything to help you.

@Ferroin is right. The only solution you have is to talk with the CSF folks to fix their detection.

Of course, if  the CSF folks require something that netdata can do to prevent this alarm, I would be glad to do it.

**Comment by natehudson** [comment]
I use CSF/LFD and I've faced this issue too. You can add 
~~~~
/tmp/\.netdata-charts.*
~~~~
to **/etc/csf/csf.fignore** to permanently igore these files, and then restart CSF/LFD
~~~~
service csf restart
service lfd restart
~~~~
which should stop the alerts. I'd agree that is not really a netdata bug.

**Comment by ktsaou** [comment]
@natehudson thank you!

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
