### ISSUE TITLE
Suggestion for Redis monitoring improvement

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#2581]
Here is something that happened to me on a web server last night which was difficult to detect but NetData could have alerted me easily. So I hope we can add some metric to this plugin. Let me explain what has happened.

Redis used around 50% of overall RAM but everything looked just fine, we still had enough RAM left for all other services to still operate nicely. The only issue had been that applications depending on Redis did not work any more, data didn't update properly.

When I tried to flush the redis keys, just to reset everything, I got an error message that this wasn't possible:

```
(error) MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

So looking into the redis logs I found that to be full of these:

```
1175:M 10 Aug 08:38:42.001 * 1 changes in 900 seconds. Saving...
1175:M 10 Aug 08:38:42.001 # Can't save in background: fork: Cannot allocate memory
```

What that means, Redis was not able to modify ANY of the records in its database and hence wasn't operating anymore at all. Just reading existing items was still OK.

Now, how could that be monitored? To be honest I don't know for sure but watching the log would be an option.

**Comment by ktsaou** [comment]
hm... well netdata monitors metrics, we need to find a metric to detect this.

Is there a redis metric showing number of critical errors, memory allocation errors, last db save time, or something that can be used as a number?

**Comment by ktsaou** [comment]
based on this page: https://redis.io/commands/INFO

I see redis exposes these:

```
# Persistence
rdb_changes_since_last_save:6573850
rdb_bgsave_in_progress:0
rdb_last_save_time:1499989883
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
```

So, I think we can create a chart tracking the health of persistence and add an alarm to it.
@l2isbad what do you think?

**Comment by l2isbad** [comment]
Sounds good. But the next two weeks I will be on vacation.

**Comment by ktsaou** [comment]
it is ok. I am already in vacation...
Get rest and enjoy it.

**Comment by jurgenhaas** [comment]
Sorry for my late response and thanks for picking this up. Your approach sounds great, that nails it.

**Comment by l2isbad** [comment]
> rdb_changes_since_last_save:6573850
> rdb_bgsave_in_progress:0
> rdb_last_save_time:1499989883
> rdb_last_bgsave_status:ok
> rdb_last_bgsave_time_sec:-1
> rdb_current_bgsave_time_sec:-1

How this should be grouped into the charts?
I see only `rdb_changes_since_last_save` is only used atm

**Comment by ktsaou** [comment]
I see netdata already provides `redis.persistence`, a chart that tracks `rdb_changes_since_last_save`.

I suggest to provide:

A chart: `redis.bgsave_now` (in family `persistence`) that tracks `rdb_bgsave_in_progress`. This would either give 0/1, or the number of seconds `rdb_bgsave_in_progress` is found contiguously not zero.

A chart `redis.bgsave_health` (in family `persistence`) that tracks `rdb_last_bgsave_status`. Again this would either give 0/1, or the number of seconds `rdb_last_bgsave_status` is found contiguously not `ok`.

Based on the above we could provide 2 alarms:

1. `bgsave_slow`, if `redis.bgsave_now` goes above, eg, 15 minutes
2. `bgsave_broken`, if `redis.bgsave_health` goes above 0.

**Comment by ktsaou** [comment]
merged it
