### ISSUE TITLE
how to configure the memory model = none?

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#2584]
how to configure the memory model = none?

**Comment by ktsaou** [comment]
In netdata.conf, set:

```
[global]
    memory mode = none
```

**Comment by FANGXIANGQUAN** [comment]
Hi ktsaou,I know this configuration, but I don't know how to send data to a central  netdata server. can you tall me ?think you .

**Comment by ktsaou** [comment]
Have you read this: https://github.com/firehol/netdata/wiki/Replication-Overview#streaming-configuration ?

**Comment by FANGXIANGQUAN** [comment]
thinks，this document i didn't see before。
