### ISSUE TITLE
Set FROM header with more specific parameters

### ISSUE THREAD

**Issue by arthurlogilab** [firehol/netdata#2586]
Hi, 

Very happy to see #2548 being implemented so fast with #2552 

In my case (very restrictive outgoing rules on the smtp server) I have to patch plugins.d/alarm-notify.sh further. So far I've got it to work by adding flags to sendmail : 

```
        "${sendmail}" -t -f 'example@host.com' -F "Full Name Example"
```

The SMTP server also checks for "Full Name Example"... 

Do you know if there is a better way to use sendmail in this script ? 

In any case, would it be possible to make this configurable from conf.d/health_alarm_notify.conf ? 

Thanks for a great piece of software!

**Comment by ktsaou** [comment]
Can you try setting `EMAIL_SENDER="Full Name Example <example@host.com>"`?

**Comment by arthurlogilab** [comment]
I did... for some reason, that didn't work (I can investigate further if you know how)

**Comment by ktsaou** [comment]
hm... just tested and it works. Are you sure?
I received the email at gmail with the configured sender name and sender email.

**Comment by ktsaou** [comment]
You can also use:

```
EMAIL_SENDER="\"Full Name Example\" <example@host.com>
```

here is what I received by setting it to `EMAIL_SENDER="\"Me, myself and I\" <test@tsaousis.gr>"`

![screenshot from 2017-08-11 14-16-18](https://user-images.githubusercontent.com/2662304/29211122-d37e4f20-7e9f-11e7-8eb5-78b6814185a6.png)

**Comment by arthurlogilab** [comment]
I have tried a number of combinations which fail (I know, sender verification is a pain)

```
From: "\"Full Name Example\" <example@host.com>"
Aug 11 12:35:47 hostfqdn postfix/smtp[28420]: BB685A12B3: to=<dest@email.com>, [snip] said: 554 Transaction failed: Address contains illegal characters in user name: '<"\"Full Name Example\" <example@host.com>"@hostfqdn>'. (in reply to end of DATA command))


From: \"Full Name Example\" <example@host.com>
Aug 11 12:38:35 hostfqdn postfix/smtp[1591]: 85633A12B3: to=<dest@email.com>, [snip] said: 554 Transaction failed: Missing '"' (in reply to end of DATA command))


From: "Full Name Example" <example@host.com>
Aug 11 12:40:45 hostfqdn postfix/smtp[5765]: 90591A12B1: to=<dest@email.com>, [snip] said: 554 Message rejected: Email address is not verified. The following identities failed the check: netdata@hostfqdn (in reply to end of DATA command))


From: Full Name Example <email@host.com>
Aug 11 12:42:15 hostfqdn postfix/smtp[5765]: 99423A12B3: to=<dest@email.com>, [snip] said: 554 Message rejected: Email address is not verified. The following identities failed the check : netdata@hostfqdn (in reply to end of DATA command))
```

(thanks for taking the time for such a corner case)

**Comment by ktsaou** [comment]
When you say "sender verification fails" what exactly do you mean?
What appear to be the sender, as seen by the tools you use?

**Comment by arthurlogilab** [comment]
The outgoing SMTP server has restrictions on which senders are allowed and it checks both the email used in the FROM field but also the display name in the FROM field.

**Comment by ktsaou** [comment]
> The outgoing SMTP server has restrictions on which senders are allowed and it checks both the email used in the FROM field but also the display name in the FROM field.

Can you check what the SMTP server sees as display name? I mean it should see whatever we set. If it does not see the one we have set, then what does it see as display name?

**Comment by ktsaou** [comment]
I did a few tests with `-f email -F name` and `From: ` line.

For postfix, it seems it keeps an envelope header outside the mail header and adds the `From` line if it is not there, when it dispatches the email. To my understanding to does not parse the `From` line to provide the outer envelop it uses, which somehow breaks the sender verification.

From the postfix `sendmail` manual, I see `-F` and `From` should be identical though:

```
      -F full_name
              Set the sender full name. This overrides the NAME environment variable, and is used only
              with messages that have no From: message header.

       -f sender
              Set the envelope sender address. This is the address where delivery problems are sent to.
              With Postfix versions before 2.1, the Errors-To: message header overrides the error return
              address.
```

What bothers me is the original `sendmail` documentation. [It says](http://www.sendmail.org/~ca/email/man/sendmail.html):

```
     -Ffullname  Set the full name of the sender.

     -fname      Sets the name of the ``from'' person (i.e., the sender of the
                 mail).  -f can only be used by ``trusted'' users (normally
                 root, daemon, and network) or if the person you are trying to
                 become is the same as the person you are.
```

I don't know if `sendmail -f email` will fail, instead of just being ignored.

Also I don't know what other MTAs do with these flags (eg exim).

Let me check if I can optionally add `-f` and `-F` to sendmail...

**Comment by ktsaou** [comment]
ok, I think I did it.
EMAIL_SENDER is now parsed and used for adding `-f` and `-F` options to sendmail.
By default (with empty EMAIL_SENDER) these options are not added, so no harm can be done for existing installations using the default options.

Does it work for you now?

**Comment by ktsaou** [comment]
merged it.

**Comment by salsa-dev** [comment]
I had to edit `send_email()` in `plugins.d/alarm-notify.sh` to make emails beeing accepted by the server:
`sendmail: envelope from address 'ops@example.com' not accepted by the server`

So that email address after `-f ` option goes without single quotes:
`-f ops@example.com`

**Comment by ktsaou** [comment]
@salsa-dev you are suggesting that the single quotes added by netdata are the problem? Because the single quotes should never reach `sendmail`. They are only used by bash to make sure the parameter is passed to sendmail as it should.

Which mail server do you use?

**Comment by ktsaou** [comment]
anyways, I removed the single quotes from the email address. I guess it was not really useful there.

**Comment by ktsaou** [comment]
merged it.
