### ISSUE TITLE
Netdata segfaults on MIPS (ASUS N66U)

### ISSUE THREAD

**Issue by chrisob** [firehol/netdata#2591]
As soon as the service is started, netdata almost immediately segfaults.  

### Platform:

- ASUS N66U, running Asuswrt-Merlin version 380.67
- Architecture: MIPS
- Installed with Entware-ng
```admin@router:~# opkg info netdata
Package: netdata
Version: 1.6.0-1
Depends: libc, libssp, zlib, libuuid
Status: install user installed
Section: admin
Architecture: mipselsf
MD5Sum: b7c5fa72f3742c1bb05b7c3a62e26645
Size: 1337555
Filename: netdata_1.6.0-1_mipselsf.ipk
Conffiles:
 /opt/etc/netdata/netdata.conf 842beeff1b1f4e84af04bab3411a3159637b2f737b52045b2eb066d6f05cdc59
Description: netdata is a highly optimized Linux daemon providing real-time performance
 monitoring for Linux systems, applications and SNMP devices over the web.
Installed-Time: 1502497537
```

```
admin@router:~# uname -a
Linux router 2.6.22.19 #1 Sun Jul 16 12:55:33 EDT 2017 mips ASUSWRT-Merlin
admin@router:~# netdata  -V
netdata 1.6.0
```
### Logs:
Starting netdata after a clean install:
```
admin@router:~# opkg install netdata
Installing netdata (1.6.0-1) to root...
Downloading http://pkg.entware.net/binaries/mipsel/netdata_1.6.0-1_mipselsf.ipk
Configuring netdata.
admin@router:~# /opt/etc/init.d/S60netdata start
 Starting netdata...              done. 
admin@router:~# /opt/etc/init.d/S60netdata check
 Checking netdata...              dead. 
admin@router:~# tail -20 /tmp/syslog.log
Aug 12 02:25:45 syslog: User 'root' is not present. Ignoring option.
Aug 12 02:25:45 netdata[2632]: Cannot adjust my Out-Of-Memory score to 1000.
Aug 12 02:25:45 netdata[2632]: scheduler idle priority 0 is above the maximum -1. Using the maximum.
Aug 12 02:25:45 netdata[2632]: Cannot adjust netdata scheduling policy to idle (5), with priority -1. Falling back to nice
Aug 12 02:25:45 netdata[2632]: netdata started on pid 2632.
Aug 12 02:25:45 netdata[2632]: Host 'router' with guid '5300e986-7ee3-11e7-ad65-e21d04bec638' initialized, os linux, update every 2, memory mode ram, history entries 4036, streaming disabled (to '' with api key ''), health disabled, cache_dir '/opt/var/cache/netdata', varlib_dir '/opt/var/lib/netdata', health_log '/opt/var/lib/netdata/health/health-log.db', alarms default handler '/opt/lib/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
Aug 12 02:25:45 netdata[2632]: IDLEJITTER thread created with task id 2636
Aug 12 02:25:45 netdata[2632]: PROC Plugin thread created with task id 2637
Aug 12 02:25:45 admin: Started netdata from .
Aug 12 02:25:45 netdata[2632]: DISKSPACE thread created with task id 2641
Aug 12 02:25:45 netdata[2632]: BACKEND thread created with task id 2642
Aug 12 02:25:45 netdata[2632]: BACKEND thread exiting
Aug 12 02:25:45 netdata[2632]: HEALTH thread created with task id 2643
Aug 12 02:25:45 netdata[2632]: PLUGINS.D thread created with task id 2644
Aug 12 02:25:45 netdata[2632]: Multi-threaded WEB SERVER thread created with task id 2645
Aug 12 02:25:45 netdata[2632]: Listening on '[::]:19999'
Aug 12 02:25:45 netdata[2632]: Listening on '[0.0.0.0]:19999'
Aug 12 02:25:45 netdata[2632]: netdata initialization completed. Enjoy real-time performance monitoring!
Aug 12 02:25:46 netdata[2632]: PROCFILE: Cannot open file '/proc/self/mountinfo'
Aug 12 02:25:46 netdata[2632]: PROCFILE: Cannot open file '/proc/1/mountinfo'
```

Running netdata in the foreground:
```
admin@router:~# netdata -D
2017-08-12 02:27:42: netdata: ERROR: User 'root' is not present. Ignoring option. (errno 9, Bad file descriptor)
Segmentation fault
admin@router:~#
```
Changing references from the user 'root' to 'admin' in netdata.conf gets rid of the ERROR message, but netdata still segfaults.

**Comment by ktsaou** [comment]
Hi,

can you try netdata v1.7 or the git version? There have been too many fixes since v1.6

Do you have `valgrind` on this machine? If you do, run:

```sh
valgrind /usr/sbin/netdata -D
```

and post here the output.

**Comment by chrisob** [comment]
Thanks for the response, I'll open an issue with Entware to see if they'll update their netdata package to 1.7.

Here's the valgrind output: https://pastebin.com/1sJZ2Szb

One of the Entware guys suggested that my kernel version (2.6.22) is "[too old for netdata to be run correctly](https://github.com/Entware-ng/Entware-ng/issues/737#issuecomment-321959655)", is this accurate?

**Comment by chrisob** [comment]
I'll attempt to install from git, but it's an embedded device, so I'm not sure how smoothly that will go.

**Comment by ktsaou** [comment]
> Here's the valgrind output

hm... this netdata binary does not have symbols in it, so it is not helpful.

> One of the Entware guys suggested that my kernel version (2.6.22) is "too old for netdata to be run correctly", is this accurate?

no, not at all. netdata runs perfectly on kernel 2.6

> I'll attempt to install from git, but it's an embedded device, so I'm not sure how smoothly that will go.

That would be great. If it still crashes, we will have proper valgrind output.

**Comment by chrisob** [comment]
Thanks again for the feedback.  

Unfortunately, [Entware](http://pkg.entware.net/binaries/mipsel/Packages.html) doesn't have any of the dependencies needed  (libuuid-dev, zlib-dev, really any dev library) to build netdata on my device, so I'll have to try and cross compile the binary somewhere else...  I haven't really done anything like this before, so it might take a while!

**Comment by chrisob** [comment]
OK, so after a bit of toiling, I believe I've cross-compiled a netdata binary for my router that contains symbols: https://pastebin.com/5wxkfshF

Is there any other helpful info I can provide?

**Comment by ktsaou** [comment]
found it and fixed it.
If netdata was not finding any usable mount points to create disk space charts for (e.g. all mount points are read only, or cannot read `/proc/self/mountinfo`), it was crashing.

Fixed it in PR #2607 
I will merge it once travis completes (in 10 mins).

Thank you for reporting it!

**Comment by ktsaou** [comment]
btw, if you want to use an older binary, you can disable the faulty diskspace plugin, by editing netdata.conf and setting:

```
[plugins]
	diskspace = no
```

The above should allow a faulty netdata to run without crash.

**Comment by ktsaou** [comment]
merged it.
Could you please confirm it is now fixed?

**Comment by chrisob** [comment]
Wow, you work fast! Testing now...

**Comment by chrisob** [comment]
It looks like the Entware toolchain doesn't play nice with the netware 1.7, so I'm not able to test this change yet (complaining about undefined references to powl and sqrtl, so I guess it can't find this tgmath.h).  I'll see if I can fix this and compile v1.7 soon.

Regarding disabling the diskspace plugin (still stuck with 1.6 for now), netdata doesn't segfault anymore, but the web UI fails to load, and netdata is killed while running under valgrind: https://pastebin.com/nTg4fesU

**Comment by ktsaou** [comment]
> netdata is killed while running under valgrind

hm this seems a valgrind issue under mips.

> the web UI fails to load,

Fails with what error?
It may be a permissions issue. Make sure these settings match the file ownership:

```
[web]
	web files owner = netdata
	web files group = netdata
```

**Comment by chrisob** [comment]
There is no web UI error, either on the command line when using '-D', or in the browser.  It looks like netdata's webserver is able to bind to a port and my browser can open a socket, but netdata never sends a response and the browser times out after sending the request:
```
admin@router:/tmp/home/root# netstat -tuln | grep 19999
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      
tcp        0      0 :::19999                :::*                    LISTEN      
admin@router:/tmp/home/root# netstat -tun | grep 19999
tcp      642      0 192.168.2.1:19999       192.168.2.2:38280       ESTABLISHED 
```


The owner of the web files matches what's set in netdata.conf:
```
admin@router:/tmp/home/root# grep "web files" /opt/etc/netdata/netdata.conf
	# web files directory = /opt/share/netdata/web
	web files owner = admin
	web files group = admin
admin@router:/tmp/home/root# ls -l /opt/share/netdata/web/
drwxr-xr-x    2 admin    root          4096 Aug 19 12:39 css
-rw-r--r--    1 admin    root         16513 May 30 19:25 dashboard.css
-rw-r--r--    1 admin    root         22030 May 30 19:25 dashboard.html
-rw-r--r--    1 admin    root        283369 May 30 19:25 dashboard.js
-rw-r--r--    1 admin    root         16904 May 30 19:25 dashboard.slate.css
-rw-r--r--    1 admin    root         54011 May 30 19:25 dashboard_info.js
-rw-r--r--    1 admin    root          1830 May 30 19:25 dashboard_info_custom_example.js
-rw-r--r--    1 admin    root         56875 May 30 19:25 favicon.ico
drwxr-xr-x    2 admin    root          4096 Aug 19 12:39 fonts
-rw-r--r--    1 admin    root          8128 May 30 19:25 goto-host-from-alarm.html
drwxr-xr-x    2 admin    root          4096 Aug 19 12:39 images
-rw-r--r--    1 admin    root        176826 May 30 19:25 index.html
drwxr-xr-x    2 admin    root          4096 Aug 19 12:39 lib
-rw-r--r--    1 admin    root         31635 May 30 19:25 netdata-swagger.json
-rw-r--r--    1 admin    root         19535 May 30 19:25 netdata-swagger.yaml
-rw-r--r--    1 admin    root          7727 May 30 19:25 registry.html
-rw-r--r--    1 admin    root           119 May 30 19:25 robots.txt
-rw-r--r--    1 admin    root           283 May 30 19:25 sitemap.xml
-rw-r--r--    1 admin    root         11704 May 30 19:25 tv.html
-rw-r--r--    1 admin    root             2 May 30 19:25 version.txt
```


Here's netdata's logs from my syslog:  https://pastebin.com/r85Cprzr

**Comment by chrisob** [comment]
I've enabled all debug flags, here's my error log: http://sprunge.us/daAg 
And my debug log: http://sprunge.us/UNVT

**Comment by ktsaou** [comment]
I think your netdata is not configured properly.

netdata uses the `accept4()` call. This call is not available on all systems, so netdata implements this if it is not there. This is a compile time decision, which apparently is wrong on your case. You system does not have `accept4()` but netdata was compiled assuming it is there.

If your automake takes the wrong decision, I suggest, just after running `./configure ...` to edit `./config.h` (in the source root directory) and comment out or remove this:

```
/* Define to 1 if you have the `accept4' function. */
#define HAVE_ACCEPT4 1
```

Then compile netdata like you did. This netdata will now insert its own implementation if `accept4()`.

**Comment by chrisob** [comment]
That's it, I'm able to get to the web UI now!!  Thank you so much for your patience!  

I'll open a ticket with the package maintainers to take a look at why Entware's make system thinks this accept4 call is available.

Thank you again for such amazing software and fantastic support!!!

**Comment by ktsaou** [comment]
hm... they closed the issue.
Let me check if I can do something about it...

**Comment by chrisob** [comment]
Above and beyond, yet again :)

Let me know if I can give a hand with testing.

**Comment by ktsaou** [comment]
ok, I added configure option `--disable-accept4` to force netdata use its own version of `accept4()`.
I also detected this case at runtime and logged this:

```
netdata has been compiled with the assumption that the system has the accept4() call, but it is not here. Recompile netdata like this: ./configure --disable-accept4 ...
```

**Comment by ktsaou** [comment]
merged it.

**Comment by chrisob** [comment]
Thanks so much yet again!

**Comment by jlgoolsbee** [comment]
I ran into this `accept4()` issue on a Synology DS212 running DSM 6.1.5-15254, installing in a Debian Chroot environment. Thanks for finding and fixing this!
