### ISSUE TITLE
Insert into Wordpress

### ISSUE THREAD

**Issue by ocuil** [firehol/netdata#2595]
Hi there,

I try to insert into wordpress but i get always the same error...

dashboard.js:6389 Uncaught TypeError: $ is not a function
    at Object.isAlreadyLoaded (dashboard.js:6389)
    at Object.NETDATA.loadRequiredJs (dashboard.js:6427)
    at dashboard.js:7069
    at Object.NETDATA._loadjQuery (dashboard.js:3936)
    at dashboard.js:7068
    at dashboard.js:7083

could you please help me?

thanks

**Comment by ktsaou** [comment]
Hi,

netdata dashboard depends on jquery.
It seems that wordpress is shipping its own version of jquery. Check this: https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/ It seems there is a workaround to improve the compatibility of jquery apps under wordpress.

I am not familiar with wordpress. If anyone else can help, please do so.

For sure, I can change all `$` references to `jQuery` in dashboard.js, but I guess we may then hit issues with the jquery chart libraries netdata uses.

**Comment by ktsaou** [comment]
Another newer reference: https://premium.wpmudev.org/blog/adding-jquery-scripts-wordpress/

**Comment by BrainDoctor** [comment]
was just randomly reading this issue.

I managed to get it to work in a personal project like this:
```javascript
// anonymous function
(function (MONITOR, $, undefined) {
// code...

}(window.MONITOR = window.MONITOR || {}, jQuery));
```
this does the following:
* If window.MONITOR is not defined, create a new empty object and pass it to the anonymous function
* assign parameter `$` the currently loaded jQuery instance
* the 3rd parameter is intentionally left undefined, in case other libraries overwrite undefined

maybe you can do something similar in dashboard.js: Load jQuery only if it's not defined yet. Don't know what happens with outdated versions or incompatibilities though. But you can still use `$`

reference: https://appendto.com/2010/10/how-good-c-habits-can-encourage-bad-javascript-habits-part-1/

**Comment by ocuil** [comment]
I will try it thanks !!!!

**Comment by ktsaou** [comment]
> Load jQuery only if it's not defined yet.

Yes, this is what the dashboard already does.

> Don't know what happens with outdated versions or incompatibilities though.

dashboard.js should work with any jquery version above 1.x

Of course, the chart libraries may have their own requirements.

**Comment by ktsaou** [comment]
I attempted to work around the issue by modifying dashboard.js according to @BrainDoctor suggestions.
Can you test it now?
Get dashboard.js from PR #2601

**Comment by ktsaou** [comment]
merged it.
