### ISSUE TITLE
About refresh of

### ISSUE THREAD

**Issue by ocuil** [firehol/netdata#2598]
Hi there,
When I click in other windows and lose the focus on netdata web, the graphs stop, how I can leave it on ?
Thanks in advance,
Kind regards

**Comment by simonnagl** [comment]
In the top page menu click on Settings.

There move to tab Performance and set the option "When to refresh the charts" to always.

<img width="896" alt="bildschirmfoto 2017-08-14 um 20 00 01" src="https://user-images.githubusercontent.com/7253893/29284485-4304a456-812b-11e7-8940-e0b7512f5dbf.png">

**Comment by ktsaou** [comment]
Keep in mind this setting is not saved. You will have to do it every time. But, once you set it to `Always`, you can bookmark the URL to come back with this setting enabled.

This setting is propagated from netdata to netdata via the `my-netdata` menu, so if you need it enabled on all your servers, just bookmark one netdata with this enabled, and then use the `my-netdata` menu to jump from server to server. It will always be enabled.

**Comment by ocuil** [comment]
Thanks a lot about that, But I wouldlike to setup it in the code on my custom dashboard.

**Comment by ktsaou** [comment]
> Thanks a lot about that, But I wouldlike to setup it in the code on my custom dashboard.

of course. After loading `dashboard.js`, set:

```js
NETDATA.options.current.stop_updates_when_focus_is_lost = false;
```

Other available options:
https://github.com/firehol/netdata/blob/f0e29046889438bfb084f560c9cf32577935d640/web/dashboard.js#L351

Example on how to do it:
https://github.com/firehol/netdata/blob/f0e29046889438bfb084f560c9cf32577935d640/web/tv.html#L53-L77

**Comment by ocuil** [comment]
Thanks a lot !!!
