### ISSUE TITLE
some metrics are missing in the backend for a some time. 

### ISSUE THREAD

**Issue by harutiundermenjian** [firehol/netdata#2602]
Hello,
I have setup netdata with the backend graphite and noticed that some metrics(on each server it can be different metric) are missing in the backend for a some hour(e.g. the system.load1 and load15 can appear but load5 absent) . After a few hour the metric may appear.

**Comment by ktsaou** [comment]
Hi,

Could you please post the `[backend]` section of your `netdata.conf`.
I need it to try to reproduce this.

**Comment by harutiundermenjian** [comment]
sure
[backend]
        enabled = yes
        data source = average
        type = graphite
        destination = HERE_IS_THE_GRAPHITE_HOSTNAME:2013
        prefix = netdata
        update every = 20
        buffer on failures = 20
        timeout ms = 40000
        send names instead of ids = yes
        send charts matching = !cpu* *

**Comment by ktsaou** [comment]
I can't reproduce it.

This is what I did:

1. In your `[backend]` config I just changed `HERE_IS_THE_GRAPHITE_HOSTNAME` with `127.0.0.1`.
2. I run `/path/to/netdata.git/contrib/nc-backend.sh start 2013`. This starts a dummy backend that just saves the metrics to a file in /tmp and prints them on console.
3. restarted netdata to activate the change.

Then I checked what netdata sends:

```sh
# grep "system.load" /tmp/netdata-nc-backend-2013
netdata.ktsaou-laptop.system.load.load1 0.0350000 1502877555
netdata.ktsaou-laptop.system.load.load5 0.2050000 1502877555
netdata.ktsaou-laptop.system.load.load15 0.5850000 1502877555
netdata.ktsaou-laptop.system.load.load1 0.0264077 1502877575
netdata.ktsaou-laptop.system.load.load5 0.1964077 1502877575
netdata.ktsaou-laptop.system.load.load15 0.5764077 1502877575
netdata.ktsaou-laptop.system.load.load1 0.1950000 1502877595
netdata.ktsaou-laptop.system.load.load5 0.2225000 1502877595
netdata.ktsaou-laptop.system.load.load15 0.5750000 1502877595
netdata.ktsaou-laptop.system.load.load1 0.4225000 1502877615
netdata.ktsaou-laptop.system.load.load5 0.2775000 1502877615
netdata.ktsaou-laptop.system.load.load15 0.5850000 1502877615
netdata.ktsaou-laptop.system.load.load1 0.3369169 1502877635
netdata.ktsaou-laptop.system.load.load5 0.2650000 1502877635
netdata.ktsaou-laptop.system.load.load15 0.5750000 1502877635
netdata.ktsaou-laptop.system.load.load1 0.2875000 1502877655
netdata.ktsaou-laptop.system.load.load5 0.2600000 1502877655
netdata.ktsaou-laptop.system.load.load15 0.5650000 1502877655
netdata.ktsaou-laptop.system.load.load1 0.2750000 1502877675
netdata.ktsaou-laptop.system.load.load5 0.2600000 1502877675
netdata.ktsaou-laptop.system.load.load15 0.5550000 1502877675
netdata.ktsaou-laptop.system.load.load1 0.2711664 1502877695
netdata.ktsaou-laptop.system.load.load5 0.2603888 1502877695
netdata.ktsaou-laptop.system.load.load15 0.5500000 1502877695
netdata.ktsaou-laptop.system.load.load1 0.2475000 1502877715
netdata.ktsaou-laptop.system.load.load5 0.2550000 1502877715
netdata.ktsaou-laptop.system.load.load15 0.5400000 1502877715
netdata.ktsaou-laptop.system.load.load1 0.3269170 1502877735
netdata.ktsaou-laptop.system.load.load5 0.2723057 1502877735
netdata.ktsaou-laptop.system.load.load15 0.5400000 1502877735
netdata.ktsaou-laptop.system.load.load1 0.3150000 1502877755
netdata.ktsaou-laptop.system.load.load5 0.2700000 1502877755
netdata.ktsaou-laptop.system.load.load15 0.5350000 1502877755
netdata.ktsaou-laptop.system.load.load1 0.2346113 1502877775
netdata.ktsaou-laptop.system.load.load5 0.2575000 1502877775
netdata.ktsaou-laptop.system.load.load15 0.5250000 1502877775
netdata.ktsaou-laptop.system.load.load1 0.4850271 1502877795
netdata.ktsaou-laptop.system.load.load5 0.3055832 1502877795
netdata.ktsaou-laptop.system.load.load15 0.5375000 1502877795
netdata.ktsaou-laptop.system.load.load1 0.5150000 1502877815
netdata.ktsaou-laptop.system.load.load5 0.3300000 1502877815
netdata.ktsaou-laptop.system.load.load15 0.5400000 1502877815
```

As you can see, all the metrics are sent every exactly 20 seconds...

Can you help me reproduce it?

**Comment by ktsaou** [comment]
Are you using the latest git version of netdata?
There have been a few changes recently that might have affected this.

**Comment by ktsaou** [comment]
Have you solved it?

**Comment by harutyundermenjyan** [comment]
The version I'm using is netdata 1.7.1 I've cloned it about 2week ago and the issue is exist yet.
I'll try the new version as well. 
Thanks.

**Comment by harutyundermenjyan** [comment]
Hi Costa Tsaousis,
I've installed the new version in the few of my hosts and haven't yet noticed an issue but to be sure I think it needs to be tested to more hosts
In any case thanks for the great product!

**Comment by ktsaou** [comment]
ok nice.
If the problem comes back, please post here. It is important this feature to be solid rock.
