### ISSUE TITLE
[Question] How to render incremental counter

### ISSUE THREAD

**Issue by alekc** [firehol/netdata#2606]
I am trying to render an incremental counter (only goes up) with go_expvar and I am having hard time to understand how to do it.  Output graph is the same as uptime. 

My current setting is following: 
```
app1:
  name : 'Wafg'
  url  : 'http://127.0.0.1:7777/debug/vars'
  collect_memstats: true
  extra_charts:
    - id: "wafg_connections"
      options:
        name: num_connections
        title: "Waf connections"
        units: connections
        family: conn
        context: expvar.runtime.goroutines
        chart_type: lines
      lines:
        - {expvar_key: 'counters.connections', expvar_type: int, id: runtime_goroutines}
```

Any hints? 
Thanks

**Comment by ktsaou** [comment]
Hi,

I am sorry, I don't know how to do this with expvar.
@kralewitz could you please help?

**Comment by kralewitz** [comment]
Hey @alekc,

I see that your `chart_type` under `options` is set to `lines` - that value does not exist in netdata (it can be either `line`, `area`, or `stacked`).

Try to set it to `line` and let me know, if it fixes the problem, the config looks ok otherwise.

**Comment by alekc** [comment]
@kralewitz  Thx for reply. My issue is not with a chart_type (in theory lines were fine since it was defaulting to line anyway), but with the fact that I can't find a way to use incremental algorithm. 

To explain myself better: right now I have following graph
![image](https://user-images.githubusercontent.com/302807/29513469-624a83e4-865d-11e7-9921-0c6e3a78e612.png)

As you can see it's a counter for connections, and it's constantly growing up (like an uptime graph). 

What I'd like to achieve is something similar to 
![image](https://user-images.githubusercontent.com/302807/29513529-8d3e3bcc-865d-11e7-9d20-5097bb0af4e9.png)

I can achieve that by changing my golang code and use something like Paul Bellamy's rate counter (https://github.com/paulbellamy/ratecounter) but I'd rather use a dimension with incremental algorithm from netdata docs (https://github.com/firehol/netdata/blob/master/plugins.d/README.md#dimension) and have full count of connections for my reference.

> incremental
> 
> the value increases over time, the difference from the last value is presented in the chart, the server interpolates the value and calculates a per second figure

As I said, it's possible that I am missing something pretty obvious, but so far I did not have any luck.

Cheers

**Comment by kralewitz** [comment]
Oh, okay, I thought the plugin wasn't working at all or something, thanks for the extra explanation.

The `go_expvar` code that parses the line config should support all the `DIMENSION` parameters defined in the link you posted,  see this code snippet from the plugin:

```
                chart_dict['lines'].append(
                    [
                        line.get('id', ''),
                        line.get('name', ''),
                        line.get('algorithm', ''),
                        line.get('multiplier', 1),
                        line.get('divisor', 100 if ev_type == 'float' else 1),
                        line.get('hidden', False)
                    ]
                )
```

So, if the plugin sees any of these keys in the line config, it should pass them on to `netdata`.

In your case, that would be:

```
lines:
        - {expvar_key: 'counters.connections', expvar_type: int, id: runtime_goroutines, algorithm: incremental}
```

Let me know if this helped.

**Comment by alekc** [comment]
Perfect, thanks 

![image](https://user-images.githubusercontent.com/302807/29514784-ab47869c-8661-11e7-948b-4c9120ccba30.png)

I think it might be worth to add some extra info about graph rendering to current wiki for expvar, it's quiet hard to understand how to go further than standard lines

Cheers, closing this thread. 

P.s. if anyone else encounter this issue and change the algorithm: you will also need to clear entry from /var/cache/netdata/metricName

**Comment by kralewitz** [comment]
Okay, I'm glad it's working for you.

The extra line/dimension values are mentioned in the "Line definitions" section of the wiki article - there's a link to the `DIMENSION` section in the "External plugins" article, but I agree that it could be a bit clearer.

I will explicitly mention all the available dimension parameters in the `go_expvar` article, hope that will clear things up a bit.

**Comment by kralewitz** [comment]
I have updated the wiki:

https://github.com/firehol/netdata/wiki/Monitoring-Go-Applications#monitoring-custom-vars-with-go_expvar
