### ISSUE TITLE
Empty screen after some time

### ISSUE THREAD

**Issue by habib-the-sweet** [firehol/netdata#261]
![blackscreen](https://cloud.githubusercontent.com/assets/13257902/14597849/edf4bba4-0557-11e6-9ba1-c895d7a397df.png)

Only restart can resolve a problem, but after some time this problem repeats again.

Here is my config:

```
[global]
	# config directory = /opt/netdata/etc/netdata
	# plugins directory = /opt/netdata/usr/libexec/netdata/plugins.d
	# web files directory = /opt/netdata/usr/share/netdata/web
	# cache directory = /opt/netdata/var/cache/netdata
	# log directory = /opt/netdata/var/log/netdata
	# host access prefix = 
	# debug flags = 0x00000000
	# memory deduplication (ksm) = yes
	# debug log = /opt/netdata/var/log/netdata/debug.log
	# error log = /opt/netdata/var/log/netdata/error.log
	# access log = /opt/netdata/var/log/netdata/access.log
	# memory mode = save
	# hostname = mon1.sigma-it.local
	# history = 3600
	# update every = 1
	# pthread stack size = 8388608
	# run as user = netdata
	# web files owner = netdata
	# web files group = netdata
	# http port listen backlog = 100
	# port = 19999
	# ip version = any
	# bind socket to IP = *
	# disconnect idle web clients after seconds = 60
	# enable web responses gzip compression = yes

```

I tried to uncomment "hostname" option but it didn't help. The issue is reproduced on any browser or computer

**Comment by ktsaou** [comment]
If you refresh the page does it work?

If yes, check the settings on the dashboard You may have to set `How to handle hidden charts?` to `Destroy`. If this is the case, it is a browser memory issue.

**Comment by habib-the-sweet** [comment]
No. After refresh I still get a blank page. Here is the screenshot from anoter browser on another PC
![blankmozila](https://cloud.githubusercontent.com/assets/13257902/14599837/692b240c-0562-11e6-8161-52f194083cec.png)

**Comment by ktsaou** [comment]
is the netdata server running?

I just merged a few additional checks. Can you please `git pull` and re-install it?

**Comment by habib-the-sweet** [comment]
Re-install didn't help. Current version: fc838eda9e2917737c054f1fd751d1a5bd5604cd  

Yes. Netdata server is running:

```
[root@mon1 netdata]# ps -ef | grep netdata
netdata  20589     1  0 12:56 ?        00:00:03 /opt/netdata/usr/sbin/netdata -pidfile /opt/netdata/var/run/netdata.pid
netdata  20596 20589  0 12:56 ?        00:00:00 /bin/bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  20599 20589  0 12:56 ?        00:00:04 /bin/bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
root     20605 20589  1 12:56 ?        00:00:12 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  26618 20599  0 13:10 ?        00:00:00 sleep 0.2
netdata  26629 20596  0 13:10 ?        00:00:00 sleep 0.997

```

**Comment by ktsaou** [comment]
To avoid committing just tests, it seems that for some reason the dashboard cannot fetch the list of charts, please make this change:

edit `/usr/share/netdata/dashboard.js` and add the line `console.log(data)`, like this (it is the second line shown below):

```js
                        .done(function(data) {
                                console.log(data);
                                if(data !== null) {
                                        var h = NETDATA.chartRegistry.fixid(host);
                                        //console.log('downloaded all charts from ' + host + ' (' + h + ')');
                                        self.charts[h] = data.charts;
                                }
                                if(typeof callback === 'function')
                                        callback(data);
                        })
```

Yours should log null.
Now fetch the same url from your server: `http://your.server:19999/api/v1/charts`. It should respond with a json array. [This is from the demo server](http://netdata.firehol.org/api/v1/charts).

Can you report your results?

**Comment by habib-the-sweet** [comment]
After ~15 minutes I got blank screen again. Here is may charts-file. 

[charts.txt](https://github.com/firehol/netdata/files/223568/charts.txt)

**Comment by ktsaou** [comment]
I think I found it.

You have user group called `INT\domain`. This backslash is the problem.
I will convert all backslahes and quotes to underscores in apps.plugin, this evening.

Thanks for reporting this!

**Comment by ktsaou** [comment]
I have pushed the fix.
Please `git pull` and re-install it.
If it is fixed, please close this.

**Comment by habib-the-sweet** [comment]
Thank you for your product and for your responsiveness!
