### ISSUE TITLE
Monitoring php-fpm permission denied

### ISSUE THREAD

**Issue by ahmnabil** [firehol/netdata#2610]
Hi,

i'm trying to monitor php-fpm but can't get the charts to show at the dashboard 

this is from the error logs for netdata
grep php-fpm /var/log/netdata/error.log

2017-08-20 09:30:07: apps.plugin ERROR: Cannot process /proc/25816/io (command 'php-fpm') (errno 13, Permission denied)

for many different procs same error

running nginx+php-fpm 7 on centos 7 with vestacp as the control panel

need some help :)

**Comment by ktsaou** [comment]
Hi,

2 problems:

1. apps.plugin seems that is missing its capabilities. How did you install netdata? I suggest to run these to make apps.plugin run as root:

```sh
sudo chown root:root /usr/libexec/netdata/plugins.d/apps.plugin
sudo chmod 4755 /usr/libexec/netdata/plugins.d/apps.plugin
```

2. To collect metrics from php-fpm, a netdata python module is required. To run this module in debug mode, use this:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the python plugin, php-fpm module in debug mode
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 phpfpm
```

and post the output here.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
