### ISSUE TITLE
enabling samba polling results in interrupt storms

### ISSUE THREAD

**Issue by VVelox** [firehol/netdata#2613]
I can't seem to narrow down what it is doing, but if I enable Samba polling the system slows to a crawl and a single core spends a lot of time handling interrupts.

Disabling it fixes it. I can't seem to be able to reproduce this via "smbstatus -P".

**Comment by ktsaou** [comment]
Hi,

@ntlug do you also experience this?

@VVelox could you please check if you get the same result by running the following by hand:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the smb plugin
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 samba
```

Can you post the interrupts chart? (which interrupt does this?)
Also, which distro do you use?

**Comment by ntlug** [comment]
Hmm... my interrupts seem to be ok... I DISABLEd samba anyway and the interrupts looked the same to me.  Not sure what's going on.

**Comment by VVelox** [comment]
Hoi!

Sorry about the slow reply. Post more testing this turned out to be a motherboard board starting to flake.
