### ISSUE TITLE
fping questions

### ISSUE THREAD

**Issue by hmmxp** [firehol/netdata#2615]
Dear All,

Some questions relating to fping

My understanding is  the below configuration is for 5 pings per second

update_every=1
ping_every=200
fping_opts="-R -b 56 -i 1 -r 0 -t 5000"

If configuration calls for 10 pings per minute, is it correct to modify the ping_every to 6,000 as per below assumption?

As my understanding is 1 sec = 1000ms and ping_every 200 equates to 5 pings x 200 = 1000ms and therefore 60 sec = 60,000ms and ping_every 6,000 equates to 10 pings x 6,000 = 60,000ms?

Beside the above configuration changes, do i need to modify the -i option? As default is 1 ms when sending packets to others hosts.  

Lastly,
soft link fping.plugin to fping2.plugin, in /usr/libexec/netdata/plugins.d
is this the correct command to do the softlink in CentOS 7: ln -s fping2.plugin /usr/libexec/netdata/plugins.d/fping.plugin

If i encountered further errors or issue, which log file should i dig in?

Thank You In Advance

**Comment by ktsaou** [comment]
Hi,

You have to align everything to this:

```
update_every=1
```

The above means that fping will have to give statistics every single second. If you want 10 pings per minute, statistics cannot be calculated 60 times per minute (every second).

So, first decide how frequently you want the chart to update and then decide how many pings per iteration you want to have for providing statistics for each iteration.

For example, to update the chart every 10 seconds and use 2 pings every 10 seconds, use this:

```sh
update_every=10   # in seconds, ie 10000 ms
ping_every=$(( (update_every * 1000 ) / 2 ))   # send one ping every 5000 ms
```

You normally do not need to modify anything else.

Regarding the link, do this:

```sh
# become root
sudo su

# step into the plugins directory
cd /usr/libexec/netdata/plugins.d

# link fping.plugin to fping2.plugin
ln -s fping.plugin fping2.plugin
```

**Comment by hmmxp** [comment]
For Sharing Purpose, I Have Updated The Document At
https://github.com/firehol/netdata/wiki/fping-Plugin
