### ISSUE TITLE
Documentation Updates for Prerequisite

### ISSUE THREAD

**Issue by hmmxp** [firehol/netdata#2616]
Dear All,

Not sure whether the documents have reference that certain plugins requires the use of NodeJS? And if NodeJS is not present on the NetData server, certain plugins will not run.

I think it will be good to have this documented to help everyone, if it is not written or maybe i need to see an eye doctor if i miss out

**Comment by simonnagl** [comment]
I think you just missed it. The installation page tells you about it.
Also `netdata-installer.sh` promts it during installation.

Where did you search for this information? Maybe there is a place where a link to https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system would help folks searching this later on.

> netdata plugins and various aspects of netdata can be enabled or benefit when these are installed (they are optional):
> 
> package|description
> :-----:|-----------
> `bash`|for shell plugins and alarm notifications
> `curl`|for shell plugins and alarm notifications
> `iproute`|for monitoring Linux QoS
> `python`|for most of the external plugins
> `python-yaml`|for parsing `python.d.plugin` configuration<br/>(netdata ships one version for python2 and python3)
> `python-mysqldb`|used for monitoring mysql databases
> `python-psycopg2`|used for monitoring postgres databases
> `python-pymongo`|used for monitoring mongodb databases
> `nodejs`|used for `node.js` plugins for monitoring `named` and SNMP devices
> `lm-sensors`|for monitoring hardware sensors
> `libmnl`|for collecting netfilter metrics
> `netcat`|for shell plugins to collect metrics from remote systems
> 
> *netdata will greatly benefit if you have the above packages installed.*
> 

from https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system


> For the plugins, you will at least need:
>   curl, bash v4+, python v2 or v3, node.js

From https://github.com/firehol/netdata/blob/master/netdata-installer.sh

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post.
