### ISSUE TITLE
systemd no auto-restart

### ISSUE THREAD

**Issue by Christophe31** [firehol/netdata#2617]
Hi I had an issue which closed netdata but he was able to turn back up by himself alone by himself.

Here the exception which turned down netdata:

    22:24:50: netdata: INFO : Initializing file /opt/netdata/var/cache/netdata/UUID/net.vethd030791/sent.db.
    22:24:50: netdata: INFO : Initializing file /opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/main.db.
    22:24:50: netdata: ERROR: Cannot allocate PRIVATE ANONYMOUS memory for KSM for file '/opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/received.db'. (errno 12, Cannot allocate memory)
    22:24:50: netdata: ERROR: Cannot allocate PRIVATE ANONYMOUS memory for KSM for file '/opt/netdata/var/cache/netdata/UUID/net_packets.vethd030791/sent.db'. (errno 12, Cannot allocate memory)        
    22:24:50: netdata: FATAL: Cannot strdup() string 'sent' # : Cannot allocate memory

    22:24:50: netdata: INFO : Saving database [3 hosts(s)]...
    22:24:50: netdata: INFO : Saving database of host 'server_2_hostname'...
    22:24:50: netdata: INFO : IDLEJITTER thread exiting
    22:24:50: netdata: ERROR: STREAM server_hostname [receive from [anIP]:33516]: disconnected (completed updates 31608723).
    22:24:50: netdata: INFO : STREAM server_hostname [receive from [anIP]:33516]: receive thread ended (task id 22087)
    22:24:50: netdata: INFO : CGROUP thread exiting
    22:24:50: netdata: INFO : DISKSPACE thread exiting
    22:24:50: netdata: INFO : PROC thread exiting
    22:24:50: netdata: ERROR: PLUGINSD: plugin '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' disconnected.
    22:24:50: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' on pid 6762 stopped after 632216 successful data collections (ENDs).
    22:24:50: netdata: ERROR: child pid 6762 killed by signal 15. (errno 9, Bad file descriptor)
    22:24:50: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' thread exiting
    22:24:50: netdata: INFO : PLUGINS.D thread exiting
    22:24:51: netdata: ERROR: PLUGINSD: plugin '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' disconnected.
    22:24:51: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 24107 stopped after 140782920 successful data collections (ENDs).
    22:24:51: netdata: ERROR: child pid 24107 killed by signal 15. (errno 9, Bad file descriptor)
    22:24:51: netdata: INFO : PLUGINSD: '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' thread exiting
    22:24:51: netdata: ERROR: child pid 22828 killed by signal 13. (errno 9, Bad file descriptor)
    22:24:51: netdata: INFO : TC thread exiting
    22:24:55: netdata: INFO : Saving database of host 'server_hostname'...
    22:24:55: netdata: INFO : HEALTH thread exiting
    22:25:09: netdata: INFO : Saving database of host 'server_2_hostname'...
    22:26:31: netdata: INFO : netdata exiting. Bye bye...

but it didn't restarted. when I restarted it manually, it worked like a charm… shouldn't the service auto restart on unexpected shutdown?

I didn't deleted anything manually, here mydf -h line for the / (containing /opt) part.

    /dev/sda2       916G   11G  859G   2% /

This issue is related to this one: [netdata_ynh/#9](https://github.com/YunoHost-Apps/netdata_ynh/issues/9#issuecomment-323806759)

**Comment by ktsaou** [comment]
Hi,

thanks! Fixed it in PR #2619

**Comment by Christophe31** [comment]
Thx.

**Comment by Christophe31** [comment]
note: it looks like closing nicely, I'm not sure if systemd will get that it was closed by failure, but I hope it would work.

**Comment by ktsaou** [comment]
I checked the code. It exits with code 1 in this case, which is handled by systemd as a failure.

**Comment by ktsaou** [comment]
merged it.
