### ISSUE TITLE
receiving warning emails when config says critical only

### ISSUE THREAD

**Issue by natehudson** [firehol/netdata#2618]
First of all, I'm really digging netdata and how it is replacing multiple monitoring systems in my environment, thanks!

Quick question though, I'm having difficulty getting netdata to only send email alerts on critical alarms. 

I've edited /etc/netdata/health_alarm_notify.conf to set the DEFAULT_RECIPIENT_EMAIL to "root|critical"

All other recipients remain at the defaults:

~~~~
root@myvps1:~# cat /etc/netdata/health_alarm_notify.conf | grep -i send_email
SEND_EMAIL = "YES"

root@myvps1:~# cat /etc/netdata/health_alarm_notify.conf | grep -i DEFAULT_RECIPIENT_EMAIL
DEFAULT_RECIPIENT_EMAIL = "root|critical"
role_recipients_email[sysadmin]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[domainadmin]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[dba]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[webmaster]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[proxyadmin]="${DEFAULT_RECIPIENT_EMAIL}"
~~~~

Even with these settings, I am still receiving email alerts that seem to be warnings, not critical alerts, for example:

~~~~
netdata notification
myvps1 needs attention

net_packets.venet0
CHART

outbound packets dropped ratio = 0.16% 
the ratio of outbound dropped packets vs the total number of sent packets of the network interface, during the last 10 minutes
ALARM

venet0
FAMILY

WARNING
SEVERITY

Thu Aug 17 15:45:08 UTC 2017
TIME
~~~~

I've checked the Alarm page in the GUI and it shows a few alarms in the "orange is warning" state.

The Alarm Log in the GUI doesn't show any Critical alerts for around this time period.

I've turned on debugging for "D_HEALTH" and am attempting to gather more information.

Could there be some stuck alarm state from the time before I added the "|critical" that keeps alerting?

Am I missing some other config?

Thanks.

**Comment by ktsaou** [comment]
Hi,

You are right. There was a bug:

Severity filtering keeps a status for each alarm for each recipient. So, if it ever sent a `CRITICAL` notification for an alarm to a recipient, it remembers it and will send a non-`CRITICAL` notification to the same recipient to let him/her know the alarm is now not `CRITICAL`.

The bug was that it was not cleaning up properly under all cases,  so it was mistakenly insisting on sending non-`CRITICAL` notifications.

I fixed it.

After PR #2619 is merged, it will cleanup by itself once you receive a `CLEAR` notification for each of the alarms. Unfortunately, it will still mistakenly send you `WARNING` notifications until each alarm falls back to its `CLEAR` state (restarting netdata will not fix this).

I suggest to clean this dirty status info by hand:

```sh
sudo rm -rfi /var/cache/netdata/alarm-notify/
```

**Comment by ktsaou** [comment]
merged it.

**Comment by metaphys** [comment]
Hi,
Thanks for this wonderful software!
I'm afraid that this ticket should be reopened. I'm facing the same issue with the following:
from /etc/netdata/health_alarm_notify.conf:
```
DEFAULT_RECIPIENT_EMAIL="email1@example.org|critical email2@example.org|critical"
[...]
DEFAULT_RECIPIENT_TELEGRAM="-XXXXXXXXX|critical"
```
from /var/log/netdata/error.log:
```
INFO: sent email notification for: host1 fping.host2_quality.packet_loss is WARNING to 'email2@example.org, email1@example.org'
INFO: sent telegram notification for: host1 fping.host2_quality.packet_loss is WARNING to '-XXXXXXXXX'
```
If I can do anything to help you debugging this one, please let me know how :)

**Comment by ktsaou** [comment]
@metaphys netdata sends warnings to critical-only recipients, if the last state of the alarm was critical. So, it depends on the transition:

1. CLEAR->WARNING: sending WARNING
2. WARNING->CLEAR: sending CLEAR
3. WARNING->CRITICAL: sending CRITICAL
4. CRITICAL->WARNING: sending WARNING
5. CRITICAL->CLEAR: sending CLEAR

In the above transitions, only the first two should not send the notification to recipients that want critical notifications only. The last three will send them.

Can you check which ones you receive?

**Comment by Ankk98** [comment]
Facing the same issue. We do not want CRITICAL alerts if the new state is WARNING. If this aligns with the team, I would like to contribute to fix this issue.
