### ISSUE TITLE
FreeBSD: Monitoring erase/trim activity for disks and ZFS (enhancement)

### ISSUE THREAD

**Issue by borjam** [firehol/netdata#2625]
FreeBSD's version of ZFS supports TRIM for SSD storage. The performance of some flash storage devices is heavily dependant on TRIM/BIO_DELETE usage, and it has proved to be troublesome now and then. Some device firmware versions have made trouble in the past.

devstat reports statistics for four different classes of operations: read, write, free and others. "Free" are deletion operations (TRIM for SATA SSDs, in general, BIO_DELETE for different kinds of devices) and "other" are, unless I am wrong, operations such as cache flushes. It would be useful to track the four cathegories as a deviation can give hints about potential firmware or even hardware problems.

The relevant parameters to pull from devstat would be:

- DSM_BUSY_PCT
- DSM_MB_PER_SECOND_READ
- DSM_MB_PER_SECOND_WRITE
- DSM_MB_PER_SECOND_FREE 
- DSM_MS_PER_TRANSACTION_READ
- DSM_MS_PER_TRANSACTION_WRITE
- DSM_MS_PER_TRANSACTION_OTHER
- DSM_MS_PER_TRANSACTION_FREE
- DSM_TRANSFERS_PER_SECOND_FREE
- DSM_TRANSFERS_PER_SECOND_READ
- DSM_TRANSFERS_PER_SECOND_WRITE
- DSM_TRANSFERS_PER_SECOND_OTHER 

ZFS makes it quite simple to monitor trim/bio_delete activity. These are the relevant paarmeters:
kstat.zfs.misc.zio_trim.failed: Number of TRIM requests that failed for reasons other 
           than not supported
kstat.zfs.misc.zio_trim.unsupported: Number of TRIM requests that failed because
           TRIM is not supported
kstat.zfs.misc.zio_trim.success: Number of successful TRIM requests
kstat.zfs.misc.zio_trim.bytes: Number of bytes successfully TRIMmed

I include four graphs from a vintage activity monitoring app (Orca). Data is gathered by "devilator" (a FreeBSD equivalent to the original "orcallator"). "da1" is a hard disk, "da4" is a SSD used as both
L2arc and ZIL for ZFS.

![devilator_micro1_counter_zfs_trim_bytes-daily](https://user-images.githubusercontent.com/14802180/29653672-01726988-88ab-11e7-9c85-ba1ed1121440.png)
![devilator_micro1_counter_zfs_trim_succ __zfs_trim_fail __zfs_trim_unsup-daily](https://user-images.githubusercontent.com/14802180/29653673-019126c0-88ab-11e7-8afc-ad276833b80e.png)
![devilator_micro1_gauge_diskbw_ada3_mspertransread __diskbw_ada3_mspertranswrite __diskbw_ada3_mspertransother __diskbw_ada3_mspertransfree-daily](https://user-images.githubusercontent.com/14802180/29653675-01970892-88ab-11e7-9ba3-bb470349c41d.png)
![devilator_micro1_gauge_diskbw_ada4_mspertransread __diskbw_ada4_mspertranswrite __diskbw_ada4_mspertransother __diskbw_ada4_mspertransfree-daily](https://user-images.githubusercontent.com/14802180/29653674-01970c16-88ab-11e7-90aa-72bd16df907c.png)

**Comment by ktsaou** [comment]
Hi,

nice! I didn't know this.
@vlvkobal have a look at this.

**Comment by ktsaou** [comment]
merged it!

**Comment by borjam** [comment]
Great! I've just checked, perfect.

Just one suggestion: the default vertical size for the "milliseconds/s", "milliseconds per operation", "kilobytes per operation" is too small to accomodate more than two magnitudes. I would make them larger because, at least on FreeBSD, you are going to see three magnitudes (read/write/other) with a fourth one (deletes or frees) in case the disk supports TRIM or a similar "delete" command.

Just a cosmetic issue ;)

**Comment by ktsaou** [comment]
Could you please post a screenshot? I need to see the exact chart names.

**Comment by borjam** [comment]
Of course. Sorry I quoted the graphs names poorly!

"Average Completed I/O Operation Time"
"Average Service Time"
"Disk Total I/O Time"

Before this update these graphs were meant to display only two magnitudes (read and write) and now it's four (read, write, other, free)



![screen shot 2017-10-20 at 08 18 36](https://user-images.githubusercontent.com/14802180/31807608-7e4b8d2c-b56f-11e7-97e1-e1a178b855d8.png)
