### ISSUE TITLE
Question: Monitor only services

### ISSUE THREAD

**Issue by k-hristov** [firehol/netdata#2626]
Hey
I am using a lot of LXC containers.

I have installed netdata on the host machine but i want to monitor services like apache, mysql and etc. installed in the containers.

Is there a way to configure netdata to gather data only for certain services without any other data (without cpu, ram, hdd since i am monitoring them with netdata on the host machine) ?

Thanks in advance!

**Comment by ktsaou** [comment]
Hi,

Yes, of course. Edit `netdata.conf` and configure the `[plugins]` section. `proc` is the system metrics. If you need a few of `proc`, there is another section `[plugin:proc]` you can fine tune it.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
