### ISSUE TITLE
Question: Can Netdata be used for uptime monitoring?

### ISSUE THREAD

**Issue by pavinjosdev** [firehol/netdata#2627]
Hey everyone,

I understand Netdata's primary goal is decentralized performance monitoring but can it perform uptime monitoring and alerting on downtime? It would've been perfect for my use then. Any pointers in that direction is much appreciated.

Thanks and Best Regards,
Pavin Joseph.

**Comment by ktsaou** [comment]
Hi,

what "uptime monitoring and alerting" means for you?

**Comment by pavinjosdev** [comment]
Hi,

> what "uptime monitoring and alerting" means for you?

I would like to get alerts (email) if a monitored system is unavailable (due to network issues or otherwise). Since there is no master/central server I don't understand how this can be implemented.

**Comment by ktsaou** [comment]
ok,

This will be implemented in v1.8 in an automated way (central health monitoring). This will have all netdata register with a central server and declare they are alive regularly (eg. every 30 seconds). If a server fails to declare itself as alive, an alarm will be triggered.

Until then, you have a few options:

1. You can ping the servers with the fping plugin. So, assume that one or more of your servers are the central health servers and configure them to ping all the other servers. This already has alarms out of the box. You can see this live at https://london.my-netdata.io (the atlanta server is down).

2. You can mirror all your netdata databases to a central netdata server and configure health monitoring on it to be active even when a server is disconnected. The central server will trigger many alarms if a slave does not push metrics for 10 seconds. Of course, this will need a dedicated server with more memory.

In v1.8, I hope this will be settled in netdata itself (you will define one of your netdata as a health master, or you will use the free online service we are building).

**Comment by pavinjosdev** [comment]
@ktsaou Thank you. That solves it. Its a great software, I can't believe its free!

**Comment by shellshock1953** [comment]
Hello,
Does it works now?

**Comment by ktsaou** [comment]
the work-around yes, the central health monitoring not yet.
