### ISSUE TITLE
Netdata "update every = 0.5"

### ISSUE THREAD

**Issue by spyff** [firehol/netdata#2628]
Hi!

It is possible to set `update every` to less than 1 second? I want more fine grained updates, 0.5 sec is the goal. I tried
```
update every = 0.5
update every = 0,5
```
and none of them seems to be work.

**Comment by ktsaou** [comment]
I am sorry, this is not possible with the current netdata.
I never thought this could be needed. Compared to anything per second was wow!

There was someone trying to make it at #449 , but I don't know what finally happened.

**Comment by ktsaou** [comment]
Cleaning up.
