### ISSUE TITLE
Trigger Alarms (Question)

### ISSUE THREAD

**Issue by tl87** [firehol/netdata#2629]
Hello,

I have a question about the alarms.

I've setup alarm notifications via Slack. I've tested with the script alarm-notify.sh (https://github.com/firehol/netdata/wiki/alarm-notifications), it works and I get notifications through Slack.

I want to trigger an alarm, to se if I will get a notification without testing with the script.

The rule I am trying to trigger is **CPU load**:
system.cpu "average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)"
- warning when | $this > (($status >= $WARNING) ? (75) : (85))
- critical when | $this > (($status == $CRITICAL) ? (85) : (95))
- check every | 1 minute

I have used strees-ng on the server and pushed the CPU-load to 80% for 15 minutes and still no alarm, even though, as I read it, I was suppose to receive a notification when CPU-load is between 75-85% for longer then 1 min.

Is there somewhere in a config, where I need to enable something, rule or alert?

Any advice would be much appreciated :-)

**Comment by tl87** [comment]
Hi @ktsaou 

I've tried to stress the CPU-load to 90% for more then a minute and still no alarms. I had Slack opened up as well as the web-gui.

Netdata does not seem to be able to detect the alarms or something. Is there somewhere in the config, where I need to enable the alarms? To my understanding the alarms should already be enable when Netdata is installed, correct?

**Comment by tl87** [comment]
In /etc/netdata/netdata.conf 
Do I need to remove some of the # under [health] section to enable it ?

**Comment by ktsaou** [comment]
While stressing the system, this screen what does it say?

![image](https://user-images.githubusercontent.com/2662304/29705977-ebe5b23a-8988-11e7-8d06-186615572275.png)

How much was the percentage at the badge?

**Comment by tl87** [comment]
This is strange.

On the **dashboard**, the CPU-load is around **90%**:
![image](https://user-images.githubusercontent.com/5989314/29706487-49035622-8982-11e7-8e03-acf61d7edfb5.png)

... but **alarms** barely shows any stress:
![image](https://user-images.githubusercontent.com/5989314/29706511-5a428e58-8982-11e7-95e8-2b696a434031.png)

I guess, if an alarm shows low CPU usage, it will of course not trigger an alarm, but how is that alarm is showing a CPU-load of around 6% even though dashboard shows around 90% ?

**Comment by ktsaou** [comment]
The badge shows the average of the **10 minutes** and is refreshed every 10 seconds or so...

**Comment by tl87** [comment]
So you will need to stress the CPU-load on 85% or more for more then 10 minutes to trigger an alarm?

**Comment by ktsaou** [comment]
To trigger this alarm, yes.

Do this:

```
while [ 1 ]; do telnet SERVER_IP 12345; done
```

Where `SERVER_IP` is any **existing** server and `12345` is any port that no daemon is listening. Leave it running for a few seconds. On your screen you should get something like this:

```sh
# while [ 1 ]; do telnet 10.11.12.1 12345; done
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
telnet: Unable to connect to remote host: Connection refused
Trying 10.11.12.1...
```

It should be rolling fast.

After 10 seconds your dashboard will pop-up and alarm and slack will show this:

![image](https://user-images.githubusercontent.com/2662304/29707115-d1533808-898c-11e7-8a42-45dcc495dd88.png)

**Comment by ktsaou** [comment]
Keep in mind that alarm has a protection to prevent it from spamming you. So, once you trigger it, it will not send another notification for 1 hour.

**Comment by tl87** [comment]
Thank you @ktsaou all seems to be working, even got the CPU to trigger an alarm.
