### ISSUE TITLE
Change in config settings not reflected in curl output

### ISSUE THREAD

**Issue by mikeweilgart** [firehol/netdata#2634]
I have placed the file `/etc/netdata/netdata.conf` with a setting (just to test it) under `[global]`, namely `update every = 15`.  I then ran `service netdata restart`, which redirected to `systemctl restart netdata.service`.  (This is on RHEL 7.)

I then tried running `curl http://localhost:19999/netdata.conf | less`, and found the `update every` line was commented out and showing the default value of `1`.

How do I get netdata to pick up the changed config?  How do I confirm that it has done so, if not with the curl command shown above?

(I also tried stopping and starting netdata, confirming in between that it was actually no longer running, and I also tried changing the owner and permissions of `/etc/netdata/netdata.conf`.  Initially it was owned by root with permissions 600, which was an obvious mistake; setting it to root and 644 produced no change in the above outcome; chowning it to netdata:netdata likewise produced no change in outcome.)

**Comment by ktsaou** [comment]
Could you please post the `[global]` section of the running netdata? The one you get with curl.

**Comment by mikeweilgart** [comment]
Thanks; it turned out the netdata instance was installed in `/opt`, so the config file I had to change was actually `/opt/netdata/etc/netdata/netdata.conf`.
