### ISSUE TITLE
running Apache with Nginx reverse proxy

### ISSUE THREAD

**Issue by macnux** [firehol/netdata#2635]
Hi
I'm running Apache with Nginx reverse proxy with a valid SSL certificate.
I've installed netdata successfully and I can access netdata without problems. https://SERVERIP:19999
Now I need to access it like this: 
https://mydomain.com/netdata
I've typed the following in /usr/local/apache/conf.d/vhosts-ssl.conf:

```
<VirtualHost SERVERIP:443>
	RewriteEngine On
	ProxyRequests Off

	ProxyPass "/netdata" "http://SERVERIP:19999/" connectiontimeout=5 timeout=30
	ProxyPassReverse "/netdata" "http://SERVERIP:19999/"
	RewriteRule ^/netdata$ https://%{HTTP_HOST}/netdata/ [L,R=301]
</VirtualHost>
```
Then i restart apache and nginx and check https://domain.com/netdata not found !!
what is the problem?

Regards,

**Comment by ktsaou** [comment]
Hi, I just updated the wiki page https://github.com/firehol/netdata/wiki/Running-behind-apache

Could you please check the updated instructions?

**Comment by macnux** [comment]
I've done what you modified and still 404 not found.

**Comment by ktsaou** [comment]
I think this has to do with your setup.

On an existing virtual host, that already works perfectly for other content, add the following before anything else:

```
	RewriteEngine On
	ProxyRequests Off
	ProxyPreserveHost On

	<Proxy *>
		Require all granted
	</Proxy>

	# Local netdata server accessed with '/netdata/', at 127.0.0.1:19999
	ProxyPass "/netdata/" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30 keepalive=on
	ProxyPassReverse "/netdata/" "http://127.0.0.1:19999/"

        # if the user did not give the trailing /, add it
	RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]
```

Then just fetch `/netdata/` on that virtual host. Just tested it and it works.

**Comment by macnux** [comment]
Works like charm!!
But one last thing. how to prevent the old url http://SERVERIP:19999 ?

Regards,

**Comment by ktsaou** [comment]
If the apache is on the same host with netdata, but bind netdata to `localhost`. The way says how.
If the netdata is remote, you have to use a firewall to do it. This says how: https://github.com/firehol/netdata/wiki/netdata-security#use-an-authenticating-web-server-in-proxy-mode

**Comment by macnux** [comment]
Apache is on the same host and I don't know how to block the old path.

**Comment by ktsaou** [comment]
The wiki page you used says how: https://github.com/firehol/netdata/wiki/Running-behind-apache#limit-direct-access-to-netdata

**Comment by ktsaou** [comment]
Use `bind to = 127.0.0.1` since the config you used attempts to access netdata this URL:

```
ProxyPass "/netdata/" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30 keepalive=on
```

**Comment by ktsaou** [comment]
Also in rules I gave you the `RewriteRule` line should be `https` (since you use https), like this:

```
RewriteRule ^/netdata$ https://%{HTTP_HOST}/netdata/ [L,R=301]
```

**Comment by macnux** [comment]
Awesome without a word !!
Have a great day.
