### ISSUE TITLE
Graphs Not Displaying Any Infromation

### ISSUE THREAD

**Issue by clydemadg** [firehol/netdata#264]
The graphs aren't showing information. A snapshot is attached.
![graphsnap](https://cloud.githubusercontent.com/assets/18534397/14609458/e6f798e4-0557-11e6-869c-cfb38dbdce2e.png)

**Comment by ktsaou** [comment]
Can you please press F12 and see if there are any errors logged?
Also, please post the output of this url: `http://your.netdata.server:19999/api/v1/charts`

**Comment by clydemadg** [comment]
No errors logged by pressing F12.
I am using konqueror.
[output.txt](https://github.com/firehol/netdata/files/224092/output.txt)

**Comment by clydemadg** [comment]
I've tried other browsers and they have worked, but recently it has been acting rather strange. If I use firefox it looks like this 
![firefoxsnap](https://cloud.githubusercontent.com/assets/18534397/14610055/4ab297f6-055a-11e6-9f75-9f609b16d840.png)

That makes me think it is the browser configuration.

**Comment by ktsaou** [comment]
Are you accessing netdata directly or though a proxy (nginx for example)?

**Comment by clydemadg** [comment]
Directly.

**Comment by ktsaou** [comment]
Can you `tail -f /var/log/netdata/error.log` and hit F5 or firefox?
It might be a file permissions problem.

**Comment by clydemadg** [comment]
I just fixed it. My browser config was messing it up

**Comment by clydemadg** [comment]
So this can be helpful to others what type of configuration of the browser could cause trouble?

**Comment by ktsaou** [comment]
> So this can be helpful to others what type of configuration of the browser could cause trouble?

yes of course, share your fix...
