### ISSUE TITLE
CPU IO support

### ISSUE THREAD

**Issue by Hexiann** [firehol/netdata#2645]
I can't seem to find a chart which shows CPU IO load which is reported by iostat. Have I missed something?

It would also be amazing if we could see the CPU IO load on a per-application basis, though measuring that may not be possible.

**Comment by ktsaou** [comment]
Hi,

can you give me the exact `iostat` command you run?

**Comment by ktsaou** [comment]
> It would also be amazing if we could see the CPU IO load on a per-application basis

I guess you are looking for this:

![screenshot from 2017-08-30 01-34-03](https://user-images.githubusercontent.com/2662304/29847248-5a29e890-8d23-11e7-890e-512f125bca87.png)

It is at the Applications section. Netdata does the same for systemd services, for users and user groups.

It would be nice to have your `iostat` command though, to see if you are looking for something different.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.

**Comment by QCU266** [comment]
@ktsaou Hi, how do you implement the disk io of application? I read netdata source code , I found it read "/proc/[pid]/io" file. But I didn't understand how netdata read these "/proc/[pid]/io" file , the "/proc/[pid]/io" file only their owner can read.

`# ll /proc/*/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/102/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1049/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1050/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/10/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1114/io
-r--------. 1 root    root    0 Sep 12 06:56 /proc/11960/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/11/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/12/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1356/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1357/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/13/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/14/io
-r--------. 1 root    root    0 Sep 26 22:59 /proc/15126/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/15/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/16/io
-r--------. 1 root    root    0 Sep 26 23:14 /proc/17795/io
-r--------. 1 root    root    0 Sep 26 23:14 /proc/17804/io
-r--------. 1 root    root    0 Sep 26 23:14 /proc/17807/io
-r--------. 1 root    root    0 Sep 26 23:14 /proc/17810/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/17/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1837/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1876/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1877/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1878/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1879/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1880/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/1/io
-r--------. 1 netdata netdata 0 Sep 26 23:26 /proc/20273/io
-r--------. 1 netdata netdata 0 Sep 26 23:26 /proc/20304/io
-r--------. 1 root    root    0 Sep 26 23:26 /proc/20305/io
-r--------. 1 root    root    0 Sep 26 23:26 /proc/20543/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/20/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/21/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/22/io
-r--------. 1 root    root    0 Sep 17 17:01 /proc/23759/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/23/io
-r--------. 1 root    root    0 Sep 21 07:26 /proc/24359/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/24/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2513/io
-r--------. 1 root    root    0 Sep 27 00:57 /proc/2564/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/25/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/266/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/267/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/268/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/269/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/26/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/270/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2738/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/273/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2740/io
-r--------. 1 root    root    0 Sep 20 03:43 /proc/27488/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/274/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/275/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/276/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/277/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/278/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/279/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/27/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/281/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/282/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/283/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2854/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2855/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2856/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2858/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2859/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2860/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2861/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2862/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2863/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2864/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2865/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2866/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2867/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2868/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2869/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/286/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2871/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2872/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2873/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2874/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2875/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2876/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2877/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2878/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2879/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/287/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2880/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2881/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/288/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/289/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/28/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/290/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/291/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/292/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/293/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/294/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/295/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/297/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/298/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/2/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/300/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/301/io
-r--------. 1 root    root    0 Sep  1 05:32 /proc/30259/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/305/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/307/io
-r--------. 1 root    root    0 Sep  1 03:18 /proc/30979/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/311/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/312/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/314/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/315/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/316/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/317/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/318/io
-r--------. 1 root    root    0 Sep 24 03:15 /proc/31973/io
-r--------. 1 root    root    0 Sep 24 03:15 /proc/31975/io
-r--------. 1 root    root    0 Sep 24 03:15 /proc/31976/io
-r--------. 1 root    root    0 Sep 24 03:15 /proc/31977/io
-r--------. 1 root    root    0 Sep 24 03:15 /proc/31978/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/319/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/320/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/321/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/322/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/324/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/325/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/326/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/327/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/328/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/329/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/330/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/331/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/332/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/333/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/334/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/335/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/336/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/337/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/338/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/339/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/33/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/340/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/341/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/342/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/343/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/344/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/345/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/346/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/347/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/348/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/349/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/34/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/350/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/351/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/35/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/36/io
-r--------. 1 root    root    0 Sep 27 01:05 /proc/3787/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/37/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/38/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/3/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/451/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/452/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/468/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/469/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/46/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/470/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/471/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/472/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/473/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/474/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/475/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/476/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/477/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/49/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/50/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/52/io
-r--------. 1 root    root    0 Sep 27 01:15 /proc/5322/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/546/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/567/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/577/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/610/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/611/io
-r--------. 1 root    root    0 Sep 26 22:01 /proc/6124/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/612/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/613/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/614/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/615/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/616/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/617/io
-r--------. 1 root    root    0 Sep 27 01:23 /proc/6551/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/674/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/693/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/697/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/699/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/700/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/704/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/706/io
-r--------. 1 netdata netdata 0 Sep 27 01:26 /proc/7093/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/718/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/719/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/71/io
-r--------. 1 root    root    0 Sep 26 22:10 /proc/7553/io
-r--------. 1 root    root    0 Sep 26 22:10 /proc/7569/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/772/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/7/io
-r--------. 1 mysql   mysql   0 Sep  6 01:37 /proc/8276/io
-r--------. 1 mysql   mysql   0 Sep  6 01:37 /proc/8469/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/8/io
-r--------. 1 root    root    0 Aug 30 02:38 /proc/9/io
-r--------. 1 root    root    0 Sep 27 01:29 /proc/self/i`

**Comment by ktsaou** [comment]
The screenshot above shows the charts that render `/proc/X/io`.

**Comment by QCU266** [comment]
@ktsaou  Sorry, forgive my poor English. I mean， how netdata gets permission to read these `/proc/[pid]/io` files. From the output content of command ` ls -l /proc/*/io`, I found these  `/proc/[pid]/io`  files only their owner can read（ACL: ` -r-------- `).

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/wiki/Apps-Plugin#apps-plugin-is-missing-information

**Comment by QCU266** [comment]
Oh, I see~
@l2isbad , thanks!
