### ISSUE TITLE
Spurious spikes/alerts in disk backlog for LVM devices

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2646]
This is a system running Ubuntu 16.04, kernel 4.4.0-87-generic, netdata 1.6.0

This system has bursty disk I/O, but only for about a minute every 5 minutes (it's running both cacti and librenms).

I was getting a lot of disk backlog alert E-mails, and I still get them even after increasing the thresholds to:

~~~
   green: 10000
     red: 20000
~~~

Here is an example:

~~~
disk_backlog.dm-2 (Chart)
--
10min disk backlog = 10002 ms average of the kernel estimated disk backlog, for the last 10 minutes (Alarm)
dm-2 (Family)
WARNING (Severity)
Tue Aug 29 07:04:29 BST 2017 (Time)

The source of this alarm is line 98@/opt/netdata/etc/netdata/health.d/disks.conf
~~~

The problem appears to be specifically with this device `dm-2`.  The peak backlog reported here is extremely high - up to 400 seconds!

![image](https://user-images.githubusercontent.com/44789/29806844-472435b0-8c89-11e7-9fd8-c1e0da6f7342.png)

Hence I can understand why the 10-minute average can exceed 10 seconds.

However, dm-2 is an LVM logical volume, backed by physical volume `/dev/md1`, which in turn is backed by physical disks `sda` and `sdb`.  The backlog on the physical disks is reasonable: it peaks at about 15 seconds, but only for a few seconds.

![image](https://user-images.githubusercontent.com/44789/29806870-62515868-8c89-11e7-8c45-c361acc4c11c.png)

![image](https://user-images.githubusercontent.com/44789/29806880-705fd132-8c89-11e7-945b-80a4c5662446.png)

So I'm trying to understand how the backlog for `dm-2` is so high.

Looking at the % utilisation graphs for dm-2 / sda / sdb, they are consistent with each other:

![image](https://user-images.githubusercontent.com/44789/29806900-81825f34-8c89-11e7-8d4f-d68d162d90e6.png)

![image](https://user-images.githubusercontent.com/44789/29806917-90df38d0-8c89-11e7-82fc-0f2bf24d249d.png)

![image](https://user-images.githubusercontent.com/44789/29806940-a3d47180-8c89-11e7-833b-b3977cb369ea.png)

Netdata does indeed warn that the backlog figure can be inaccurate - but it seems to be wildly inaccurate in this case.

So I'm wondering on the best option here:

1. Is it possible to fix or disable the backlog stat for `dm-*` ?

    I note that netdata does not provide *any* backlog graph for md1 (it shows only `disk.md1`, `disk_ops.md1`, `disk_avgsz.md1`).  Therefore, perhaps it already filters out this metric for certain sorts of 'virtual' device.  If so, it could also filter out the dm/lvm devices as well.

2. Can I filter the alarms, e.g. by setting

    ~~~
    template: 10min_disk_backlog
          on: disk.backlog
    families: sd*
    ~~~

    I can't find the 'families' setting documented in the [reference](https://github.com/firehol/netdata/wiki/health-configuration-reference), but I'll try this.

3. Maybe if backlog figures are unreliable, they shouldn't have alarms enabled by default.  I notice that there is also a `10min_disk_utilization` alarm, which as I've shown above, has decent data to work with; maybe a separate backlog alarm isn't necessary.

**Comment by ktsaou** [comment]
Hi,

Could you please fetch `http://your.netdata.ip:19999/netdata.conf` and post this section:

```
[plugin:proc:/proc/diskstats]
	# enable new disks detected at runtime = yes
	# performance metrics for physical disks = auto
	# performance metrics for virtual disks = auto
	# performance metrics for partitions = no
	# bandwidth for all disks = auto
	# operations for all disks = auto
	# merged operations for all disks = auto
	# i/o time for all disks = auto
	# queued operations for all disks = auto
	# utilization percentage for all disks = auto
	# backlog for all disks = auto
	# remove charts of removed disks = yes
	# path to get block device infos = /sys/dev/block/%lu:%lu/%s
	# path to get h/w sector size = /sys/block/%s/queue/hw_sector_size
	# path to get h/w sector size for partitions = /sys/dev/block/%lu:%lu/subsystem/%s/../queue/hw_sector_size
	# path to device mapper = /dev/mapper
	# filename to monitor = /proc/diskstats
	# exclude disks = loop* ram*
	# performance metrics for disks with major 259 = yes
	# performance metrics for disks with major 253 = yes
```

**Comment by candlerb** [comment]
~~~
[plugin:proc:/proc/diskstats]
	# enable new disks detected at runtime = yes
	# performance metrics for physical disks = auto
	# performance metrics for virtual disks = auto
	# performance metrics for partitions = no
	# bandwidth for all disks = auto
	# operations for all disks = auto
	# merged operations for all disks = auto
	# i/o time for all disks = auto
	# queued operations for all disks = auto
	# utilization percentage for all disks = auto
	# backlog for all disks = auto
	# filename to monitor = /proc/diskstats
	# path to get block device infos = /sys/dev/block/%lu:%lu/%s
	# path to get h/w sector size = /sys/block/%s/queue/hw_sector_size
	# path to get h/w sector size for partitions = /sys/dev/block/%lu:%lu/subsystem/%s/../queue/hw_sector_size
	# exclude disks = loop* ram*
	# performance metrics for disks with major 8 = yes
	# performance metrics for disks with major 9 = yes
	# performance metrics for disks with major 252 = yes

[plugin:proc:/proc/diskstats:loop0]
	# enable = no

[plugin:proc:/proc/diskstats:loop1]
	# enable = no

[plugin:proc:/proc/diskstats:loop2]
	# enable = no

[plugin:proc:/proc/diskstats:loop3]
	# enable = no

[plugin:proc:/proc/diskstats:loop4]
	# enable = no

[plugin:proc:/proc/diskstats:loop5]
	# enable = no

[plugin:proc:/proc/diskstats:loop6]
	# enable = no

[plugin:proc:/proc/diskstats:loop7]
	# enable = no

[plugin:proc:/proc/diskstats:sda]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

[plugin:proc:/proc/diskstats:sda1]
	# enable = yes
	# enable performance metrics = no
	# bandwidth = no
	# operations = no
	# merged operations = no
	# i/o time = no
	# queued operations = no
	# utilization percentage = no
	# backlog = no

[plugin:proc:/proc/diskstats:sda2]
	# enable = yes
	# enable performance metrics = no
	# bandwidth = no
	# operations = no
	# merged operations = no
	# i/o time = no
	# queued operations = no
	# utilization percentage = no
	# backlog = no

[plugin:proc:/proc/diskstats:sdb]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

[plugin:proc:/proc/diskstats:sdb1]
	# enable = yes
	# enable performance metrics = no
	# bandwidth = no
	# operations = no
	# merged operations = no
	# i/o time = no
	# queued operations = no
	# utilization percentage = no
	# backlog = no

[plugin:proc:/proc/diskstats:sdb2]
	# enable = yes
	# enable performance metrics = no
	# bandwidth = no
	# operations = no
	# merged operations = no
	# i/o time = no
	# queued operations = no
	# utilization percentage = no
	# backlog = no

[plugin:proc:/proc/diskstats:md0]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

[plugin:proc:/proc/diskstats:md1]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

[plugin:proc:/proc/diskstats:dm-0]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

[plugin:proc:/proc/diskstats:dm-1]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto

... there is then a bunch of other stuff before ....

[plugin:proc:/proc/diskstats:dm-2]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto
~~~

**Comment by candlerb** [comment]
Plus I note that majors 8, 9, 252 are sd, md, dm- respectively.

~~~
# ls -l /dev | grep sd[a-z]
brw-rw---- 1 root   disk      8,   0 Aug  9 14:15 sda
brw-rw---- 1 root   disk      8,   1 Aug  9 14:15 sda1
brw-rw---- 1 root   disk      8,   2 Aug  9 14:15 sda2
brw-rw---- 1 root   disk      8,  16 Aug  9 14:15 sdb
brw-rw---- 1 root   disk      8,  17 Aug  9 14:15 sdb1
brw-rw---- 1 root   disk      8,  18 Aug  9 14:15 sdb2

# ls -l /dev | grep md[0-9]
brw-rw---- 1 root   disk      9,   0 Aug  3 16:42 md0
brw-rw---- 1 root   disk      9,   1 Aug  3 16:42 md1

# ls -l /dev | grep dm-
brw-rw---- 1 root   disk    252,   0 Aug  3 16:42 dm-0
brw-rw---- 1 root   disk    252,   1 Aug  3 16:42 dm-1
brw-rw---- 1 root   disk    252,   2 Aug  3 16:42 dm-2
~~~

**Comment by ktsaou** [comment]
The second question can be fixed by editing `netdata.conf` and uncommenting and setting to `no` any of the following you don't need:

```
[plugin:proc:/proc/diskstats:dm-2]
	# enable = yes
	# enable performance metrics = yes
	# bandwidth = auto
	# operations = auto
	# merged operations = auto
	# i/o time = auto
	# queued operations = auto
	# utilization percentage = auto
	# backlog = auto
```

So, the only problem is to merge `dm-2` and `/var/lib/lxd`?

Could please post the output of these?

```sh
sudo su -s /bin/bash netdata
cat /proc/self/mountinfo
```

Is it possible that the `/var/lib/lxd` was mounted after netdata was started? If this is the case, netdata will not rename the charts. If you now restart netdata and refresh the dashboard, does it still show `dm-2` and `/var/lib/lxd` separately?

**Comment by candlerb** [comment]
> Could please post the output of these?

~~~
$ id
uid=999(netdata) gid=999(netdata) groups=999(netdata),4(adm)
$ cat /proc/self/mountinfo
18 23 0:17 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
19 23 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
20 23 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=8180600k,nr_inodes=2045150,mode=755
21 20 0:14 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
22 23 0:18 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=1640156k,mode=755
23 0 252:0 / / rw,relatime shared:1 - ext4 /dev/mapper/wrn--mon2-root rw,errors=remount-ro,data=ordered
24 18 0:12 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
25 20 0:19 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
26 22 0:20 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
27 18 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
28 27 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
29 18 0:23 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
30 27 0:24 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,hugetlb
31 27 0:25 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,blkio
32 27 0:26 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,devices
33 27 0:27 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,memory
34 27 0:28 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,cpu,cpuacct
35 27 0:29 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,net_cls,net_prio
36 27 0:30 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,freezer
37 27 0:31 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,cpuset
38 27 0:32 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,pids
39 27 0:33 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,perf_event
40 18 0:7 / /sys/kernel/debug rw,relatime shared:23 - debugfs debugfs rw
41 20 0:34 / /dev/hugepages rw,relatime shared:24 - hugetlbfs hugetlbfs rw
42 40 0:9 / /sys/kernel/debug/tracing rw,relatime shared:25 - tracefs tracefs rw
43 19 0:35 / /proc/sys/fs/binfmt_misc rw,relatime shared:26 - autofs systemd-1 rw,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
44 20 0:16 / /dev/mqueue rw,relatime shared:27 - mqueue mqueue rw
45 18 0:36 / /sys/fs/fuse/connections rw,relatime shared:28 - fusectl fusectl rw
91 23 9:0 / /boot rw,relatime shared:73 - ext4 /dev/md0 rw,data=ordered
94 23 0:38 / /var/lib/lxd rw,relatime shared:76 - btrfs /dev/mapper/wrn--mon2-lxd rw,space_cache,subvolid=5,subvol=/
95 23 0:41 / /var/lib/lxcfs rw,nosuid,nodev,relatime shared:78 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
98 94 0:43 / /var/lib/lxd/shmounts rw,relatime shared:80 - tmpfs tmpfs rw,size=100k,mode=711
100 94 0:44 / /var/lib/lxd/devlxd rw,relatime shared:82 - tmpfs tmpfs rw,size=100k,mode=755
155 43 0:56 / /proc/sys/fs/binfmt_misc rw,relatime shared:84 - binfmt_misc binfmt_misc rw
183 22 0:119 / /run/user/0 rw,nosuid,nodev,relatime shared:86 - tmpfs tmpfs rw,size=1640156k,mode=700
~~~

> Is it possible that the /var/lib/lxd was mounted after netdata was started?

I've definitely restarted netdata since the system came up.  But just to be sure, I've restarted it again, and done a shift-reload in the browser, and I still get `dm-2` and `/var/lib/lxd` separately.

> The second question can be fixed by editing `netdata.conf`

Before doing that, I'd like to understand why, in the web UI, `md*` devices don't get performance metrics by default, but `dm-*` devices do (surely both are "virtual" devices?)

This is despite the fact that the expanded config shows:

~~~
	# performance metrics for disks with major 8 = yes
	# performance metrics for disks with major 9 = yes
	# performance metrics for disks with major 252 = yes
...
[plugin:proc:/proc/diskstats:md*]
	# enable performance metrics = yes
	# i/o time = auto
...
[plugin:proc:/proc/diskstats:dm-*]
	# enable performance metrics = yes
	# i/o time = auto
...
~~~

which suggests I should see them for everything.  Does "auto" mean different things for `md*` and `dm-*` devices?

Also: I'd rather not to have to tweak the config for individual `dm-*` devices, because if I add a new logical volume I'd have to tweak it again. Is there a way to say "no performance metrics for all `md*`/`dm-*` devices?  All such devices have a physical underlying device of some sort.

**Comment by ktsaou** [comment]
> Does "auto" mean different things for md* and dm-* devices?

`auto` means: enable them if you find any useful info. So, netdata collects these metrics, but finds them just zero (i.e. the kernel does not collect these values). You can turn it to `yes` to see it yourself (you will just get charts with zeros). This info is collected from `/proc/diskstats`.



> Also: I'd rather not to have to tweak the config for individual dm-* devices, because if I add a new logical volume I'd have to tweak it again. Is there a way to say "no performance metrics for all md*/dm-* devices? All such devices have a physical underlying device of some sort.

You can disable all performance metrics for these devices by tweaking:

```
[plugin:proc:/proc/diskstats]
	# exclude disks = loop* ram*
	# performance metrics for disks with major 8 = yes
	# performance metrics for disks with major 9 = yes
	# performance metrics for disks with major 252 = yes
```

The excluded disks checks the third column of `/proc/diskstats`.

Let me check why the merging of `dm-2` and `/var/lib/lxd` fails on your system...

**Comment by ktsaou** [comment]
> Let me check why the merging of dm-2 and /var/lib/lxd fails on your system...

Actually, I need your `/proc/diskstats` to make this check. Could you please post it?

**Comment by candlerb** [comment]
> Actually, I need your /proc/diskstats to make this check. Could you please post it?

Certainly!

~~~
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 15846553 705138 1981360134 154502872 118163401 38962907 8682793952 1476137140 0 385593720 1630591328
   8       1 sda1 29832 2192 4022576 194032 2098743 3674 1080935 68891856 0 68646896 69084216
   8       2 sda2 15815749 702944 1977287150 154306980 116064420 38959233 8681712065 1407244260 0 325553928 1561509976
   8      16 sdb 15117689 707599 1960872863 162236248 118115781 39010353 8682793952 1765909168 0 382822900 1928221552
   8      17 sdb1 28510 2087 3904082 220000 2098743 3674 1080935 69651724 0 69395884 69871240
   8      18 sdb2 15088200 705511 1956917485 162014412 116016800 39006679 8681712065 1696256456 0 320817500 1858310508
   9       0 md0 327 0 20314 0 6350 0 1080688 0 0 0 0
   9       1 md1 1851866 0 35238434 0 150274353 0 8656111632 0 0 0 0
 252       0 dm-0 76886 0 2841618 341756 2074381 0 32358904 99275084 0 21167780 99618672
 252       1 dm-1 966 0 16616 11056 60444 0 483552 3756484 0 133516 3812176
 252       2 dm-2 1771345 0 32379432 55320256 147383886 0 8623269176 197019388 0 379899892 253510836
~~~

**Comment by ktsaou** [comment]
I checked how netdata correlates disks with mount points. It uses major and minor numbers.

So, for your root, I see `/proc/self/mountinfo` gives:

```
23 0 252:0 / / rw,relatime shared:1 - ext4 /dev/mapper/wrn--mon2-root rw,errors=remount-ro,data=ordered
```

and `/proc/diskstats`:

```
252       0 dm-0 76886 0 2841618 341756 2074381 0 32358904 99275084 0 21167780 99618672
```

So, they are correlated.

But for your `/var/lib/lxd` your `/proc/self/mountinfo` says:

```
94 23 0:38 / /var/lib/lxd rw,relatime shared:76 - btrfs /dev/mapper/wrn--mon2-lxd rw,space_cache,subvolid=5,subvol=/
```

That is major = 0 and minor = 38, which is not found in `/proc/diskstats`:

```
252       2 dm-2 1771345 0 32379432 55320256 147383886 0 8623269176 197019388 0 379899892 253510836
```

Is there anything special about it? I am not sure if this is related to `btrfs`.
Searching for any relevant documentation...

**Comment by ktsaou** [comment]
Checked my `btrfs` disks:

```
# cat /proc/self/mountinfo  | grep btrfs
20 0 0:17 / / rw,relatime - btrfs /dev/sdd3 rw,compress=lzo,ssd,discard,space_cache,autodefrag,subvolid=5,subvol=/
49 20 0:17 /var/lib/docker/plugins /var/lib/docker/plugins rw,relatime - btrfs /dev/sdd3 rw,compress=lzo,ssd,discard,space_cache,autodefrag,subvolid=5,subvol=/var/lib/docker/plugins
50 20 0:17 /var/lib/docker/btrfs /var/lib/docker/btrfs rw,relatime - btrfs /dev/sdd3 rw,compress=lzo,ssd,discard,space_cache,autodefrag,subvolid=5,subvol=/var/lib/docker/btrfs
```

So, this is related to `btrfs`. Somehow btrfs dynamically provides major and minor numbers, hiding the real device.

Searching for a solution...

**Comment by ktsaou** [comment]
Well, I can't find a solution and I think it is logical. The mount point is of btrfs subvolume. You could have mounted 2 subvolumes and both would resolve to the same device.

I could try to correlate the device with the mount point, using the device path. This will be perfect if the device has one subvolume, but it totally mess things when the device has multiple subvolumes. It will be completely random which of the multiple mount points will be elected for this. You could restart netdata and get completely different chart names.

I am not sure if we should do this. I think will introduce more problems than the ones it attempts to solve.
For sure, I could add a `name = ` config option, so that you can name the disks manually in `netdata.conf`.

If you have any better suggestion, I am open to alternatives.

**Comment by candlerb** [comment]
> Well, I can't find a solution and I think it is logical. The mount point is of btrfs subvolume. You could have mounted 2 subvolumes and both would resolve to the same device.

Thank you, that makes sense.

One option I can think of is to group the mountpoints under the device:

* Disk dm-2
    * `disk_util.dm-2`
    * `disk_space._mnt_foo`
    * `disk_space._mnt_bar`

But that's not helpful if you're looking for the used disk space of `/mnt/bar` and you don't happen to know which device it's on.  Also, if I disable dm-2 performance collection then it will change.

So I think the current behaviour is reasonable now that I understand it.

* Disk dm-2
    * `disk_util.dm-2`
* /mnt/foo
    * `disk_space._mnt_foo`
* /mnt/bar
    * `disk_space._mnt_bar`

I guess it might be nice to see the underlying device name for each mount point, like this:

* Disk dm-2
    * `disk_util.dm-2`
* /mnt/foo (dm-2)
    * `disk_space._mnt_foo`
* /mnt/bar (dm-2)
    * `disk_space._mnt_bar`

But even then, it won't tell me that `dm-2` is on `md1`, or that `md1` is on `sda+sdb`; so there's minimal benefit.

**Comment by ktsaou** [comment]
ok, then we can close this?

**Comment by candlerb** [comment]
> `auto` means: enable them if you find any useful info. So, netdata collects these metrics, but finds them just zero (i.e. the kernel does not collect these values). You can turn it to `yes` to see it yourself (you will just get charts with zeros). This info is collected from `/proc/diskstats.`

Just for future reference:

~~~
   9       0 md0 327 0 20314 0 6350 0 1080688 0 0 0 0
   9       1 md1 1851866 0 35238434 0 150274353 0 8656111632 0 0 0 0
 252       0 dm-0 76886 0 2841618 341756 2074381 0 32358904 99275084 0 21167780 99618672
 252       1 dm-1 966 0 16616 11056 60444 0 483552 3756484 0 133516 3812176
 252       2 dm-2 1771345 0 32379432 55320256 147383886 0 8623269176 197019388 0 379899892 253510836
~~~

the columns are [documented here](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats). Cols 7, 11, 13, 14 are those relating to I/O times, and they're all zero for md devices.

**Comment by candlerb** [comment]
> ok, then we can close this?

Yes, thanks.  I have set

~~~
[plugin:proc:/proc/diskstats]
	performance metrics for disks with major 252 = no
~~~

and this should silence the spurious alarms.  I'll just have to remember to do it on other deployments.

**Comment by ktsaou** [comment]
It would probably more consistent to use:

```
[plugin:proc:/proc/diskstats]
    exclude disks = loop* ram* dm-*
```

The major numbers may change.

**Comment by candlerb** [comment]
You're right, I'll do that instead.

Ideally I'd just disable "backlog" for dm-*, since the other diskstats are meaningful; but I can't see how to do that without doing individual settings under each `[plugin:proc:/proc/diskstats:dm-X]`

**Comment by ktsaou** [comment]
Yes, you are right, you can't do it like that.

But, ideally you should just exclude the given disks from the alarm. You can use the `families` line of the alarm.

To find the families of the charts, fetch `http://your-netdata-ip:19999/api/v1/charts`, search for the specific chart and you will find something like this:

```
		"disk_backlog.dm-2": 		{
			"id": "disk_backlog.dm-2",
			"name": "disk_backlog.fedora_home",
			"type": "disk_backlog",
			"family": "/home",
			"context": "disk.backlog",
			"title": "Disk Backlog (disk_backlog.fedora_home)",
			"priority": 2003,
			"enabled": true,
			"units": "backlog (ms)",
			"data_url": "/api/v1/data?chart=disk_backlog.fedora_home",
			"chart_type": "area",
			"duration": 3996,
			"first_entry": 1504078019,
			"last_entry": 1504082015,
			"update_every": 1,
			"dimensions": {
				"backlog": { "name": "backlog" }
			},
			"green": 2000,
			"red": 5000
		},
```

So, at the alarm, change the `families` line to look like this:

```
families: !/home *
```

The above says: apply this alarm on all disks with any family, except `/home`. You can prepend any number of negative expressions (use `*` as wildcard too, eg. `!dm-*`).

---

Another way to disable this alarm for all disks (just comment it out).

---

Another solution is to increase the threshold of the alarm for all disks.

---

Another solution is to overwrite the template with an alarm for each disk you want different thresholds (ie copy it, change the first line from `template` to `alarm` and on the `on` line give the exact chart name you want this to be applied.

---

Generally speaking, I would never stop data collection just because an alarm bothers me. I would fix, or remove the alarm.

**Comment by candlerb** [comment]
> So, at the alarm, change the `families` line to look like this:

Thank you for that example; I'll use `families: !dm-* *`

I looked [here](https://github.com/firehol/netdata/wiki/health-configuration-reference) but couldn't find a definition of what syntax that attribute has. In fact, it doesn't appear to mention the `families:` attribute at all.

> Generally speaking, I would never stop data collection just because an alarm bothers me. I would fix, or remove the alarm.

Normally I would agree with you, but here it seems that the data itself is bad. 400 seconds of I/O backlog?? Which vanishes after a couple of seconds?  That's not a true representation of reality.

OTOH, if netdata is accurately reflecting what the kernel is telling it, then I guess it should still be recorded.

I'm just trying to work out what exactly it shows.  AFAICS, the code collects column 14 of diskstats - [described](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats) as "weighted time spent doing I/Os (ms)", more info [here](https://www.kernel.org/doc/Documentation/iostats.txt)

~~~
        backlog_ms      = str2ull(procfile_lineword(ff, l, 13)); // rq_ticks
~~~

Does netdata apply additional processing to this?  Let me check.  Running this code:

~~~
# for i in {1..300}; do grep 'dm-2' /proc/diskstats | awk '{print $14}'; sleep 1; done | perl -ne 'print $_-$t,"\n"; $t=$_;'
~~~

at the same time as netdata collects.  Here I get this graph:

![image](https://user-images.githubusercontent.com/44789/29864799-af0c3398-8d6b-11e7-8f91-6560f4e205b5.png)

And here's the last 30 seconds or so of the perl script output, which I stopped just after the big peak:

~~~
420
324
75280
107400
28876
188
288
83796
102312
93404
99312
145316
88548
97356
98928
348
256
2332
1588
3564
2208
164
42992
220
2133876
1776992
352624
70620
36
0
32
676
84924
26632
^C
~~~

OK, there's a big peak of 2,133,876 there; netdata's peak is 212,022 ms, so I guess there is some sort of normalisation.  (These are 0.1ms ticks perhaps?)

But if that's what the kernel is telling us, then I suppose it should be collected.

**Comment by Ferroin** [comment]
I don't think the device number matching issue is specific to BTRFS, I'm seeing equivalently bogus major:minor combinations for a number of physical filesystems on my systems, so I think there may be some bigger issue there (especially considering that the major:minor combination in `/proc/self/mountinfo` does not correctly match the `st_dev` field for files on the filesystem).

**Comment by ktsaou** [comment]
> I looked here but couldn't find a definition of what syntax that attribute has. In fact, it doesn't appear to mention the families: attribute at all.

I added it: https://github.com/firehol/netdata/wiki/health-configuration-reference#alarm-line-families
Thanks for pointing out.


> Does netdata apply additional processing to this?

Other that interpolation, no. Interpolation is used to properly find the right value at second boundaries.

> These are 0.1ms ticks perhaps?

Yes, the divider is 10: https://github.com/firehol/netdata/blob/d5e6ad1a66e2fd0ccb9d1803c44d6c8ad3258fd9/src/proc_diskstats.c#L617

**Comment by ktsaou** [comment]
> I'm seeing equivalently bogus major:minor combinations for a number of physical filesystems on my systems

@Ferroin can you post one  non-btrfs, non-volume-manager case? It may help us find some docs about it.

**Comment by Ferroin** [comment]
I just checked further, all the cases where the major and minor are bogus on my system are one of:

* BTRFS volumes.
* Automounted volumes handled by autofs.
* Bind mounts.

So it looks like there's something common between the three here.

For BTRFS volumes at least, you can parse the output of `btrfs filesystem show <path>` to get the list of block devices for the volume.  It would also be kind of nice if netdata could merge different mounts of the same BTRFS volume (maybe list all the paths it's mounted at separated by commas?).  OpenSUSE systems in particular are going to have hellishly long disk lists in netdata that just repeat the same chart at least a dozen times (because they explicitly mount each and every subvolume).

**Comment by candlerb** [comment]
Is it really the same chart? I'm afraid I know little about btrfs.

Say I have `/mnt/foo` and `/mnt/bar` which are two subvolumes of the same btrfs filesystem.  Could they each have different used space and free space, or will they always be the same?  Does netdata show the space used in the subvolume, or the whole filesystem?  What if the subvolumes have different [quotas](https://btrfs.wiki.kernel.org/index.php/Quota_support) ?

**Comment by Ferroin** [comment]
WIth limited exceptions when using quota groups, it should be the exact same chart.  I don't think netdata handles quota groups though, so even if they are used, you will probably see the same chart.

**Comment by ktsaou** [comment]
> It would also be kind of nice if netdata could merge different mounts of the same BTRFS volume (maybe list all the paths it's mounted at separated by commas?). OpenSUSE systems in particular are going to have hellishly long disk lists in netdata that just repeat the same chart at least a dozen times (because they explicitly mount each and every subvolume).

well, netdata provides 2 kinds of metrics for disks:

1. performance metrics of the unterlying disks. It does this by processing `/proc/diskstats` and eliminating partitions from the list.

2. disk space metrics of the mounted disks. It does this by processing `/proc/self/mountinfo` and eliminating read-only mounts and other cases that do not provide any real value.

The whole idea of mapping disk peformance statistics with disk space metrics is to name the disk performance charts, with something more meaningful than `/dev/sda` (eg name them `/home`).

To my understanding, no matter what we do, the 2 lists will always be separate and there will always be many ways to correlate them or present them (unix is generally very innovative in this area).

**Comment by Ferroin** [comment]
Indeed.  My point was more that BTRFS subvolumes (and ZFS datasets, but I have near zero experience dealing with ZFS on anything but FreeNAS so I can't give good advice on that) are one of the few cases where there's likely to be significant duplication that shouldn't be too hard to handle in netdata.  If I can find the time, I may look into this specifically, but it's not likely that I'll be able to any time soon.

**Comment by candlerb** [comment]
> To my understanding, no matter what we do, the 2 lists will always be separate and there will always be many ways to correlate them or present them

Indeed, and a very common case is where a single disk sda has partitions sda1 (/) and sda2 (/home).

By default, Netdata only collects performance stats for sda, and not for each individual partition.  But the space utilisation is per filesystem and hence per partition.
