### ISSUE TITLE
percentiles on statsd timer metrics do not seem correct

### ISSUE THREAD

**Issue by codl** [firehol/netdata#2647]
with default netdata settings (statsd enabled, 95th percentile on timers), on a692a3b6

running this script, which constantly feeds values 1 to 100 into a timer metric:

```sh
#!/bin/bash
set -o pipefail

value=1
while true; do
    value=$[($value % 100) + 1]
    echo "example.metric:${value}|ms" | nc -u -w0 127.0.0.1 8125
done
```

I would expect the 95th percentile to be at or around 95, instead it hovers around 50, sometimes below the median (which is supposed to be the 50th percentile, and so, always less than or equal to the 95th)

![2017-08-29t12-00-16-00o0](https://user-images.githubusercontent.com/315139/29815655-ba2b5386-8cb1-11e7-8074-9c8d3ad60e2b.png)

**Comment by ktsaou** [comment]
ok,

95th percentile is calculated in netdata as the average of the lower 95% of the values. So on each iteration, netdata keeps all values received, then it sorts them, it excludes the top 5% of them, and finally calculates the average of the rest.

Is this wrong?

**Comment by codl** [comment]
yes, that is wrong

95th percentile is the value below which 95% of samples can be found, so it should be the maximum of the lower 95% of values

**Comment by ktsaou** [comment]
Thanks!

Could you please check PR #2648 ? (install `git clone https://github.com/ktsaou/netdata` and install it)
It should be fixed now.

**Comment by codl** [comment]
looks good to me! Thank you for a swift fix

**Comment by ktsaou** [comment]
merged it!
Thank you for reporting it!
