### ISSUE TITLE
multiple entry lxc container1 user.slice user-0.slice session-number.scope for LXD/LXC containers

### ISSUE THREAD

**Issue by niksfirefly** [firehol/netdata#2649]
I use netdata on host with Ubuntu 16.04 and LXD
Every LXC container is presented in netdata with one main
entry(mem,cpu,disk) and multiple entries (I assume for processess in container)
Something like this
lxc container1
lxc container1 user.slice user-0.slice session-314717.scope
lxc container1 user.slice user-0.slice session-.....scope
lxc container1 user.slice user-0.slice session-....scope

Obviously something is wrong
Is there any config options to change this behaviour?
or may I install netdata on every container?

**Comment by ktsaou** [comment]
Which distro?

It seems that your container cgroups are exposed to the host.  You have probably set a setting for this to happen.

You can disable nested containers in netdata, by editing `netdata.conf` and prepending `!/lxc/*/*/` at

```
enable by default cgroups matching =  !*/init.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/ns  !/machine  !/qemu  !/system  !/systemd  !/user  *
```

So, the final one should be:

```
enable by default cgroups matching =  !/lxc/*/*/ !*/init.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/ns  !/machine  !/qemu  !/system  !/systemd  !/user  *
```

Can you check it?
If it works, I will added to netdata default settings.

**Comment by niksfirefly** [comment]
Ubuntu 16.04
well nothing changed
I also stopped netdata and clean cache.

I notioced multiple entries in netdata error.log:
2017-08-30 18:15:45: cgroup-name.sh: INFO: cgroup 'lxc_container_user.slice_user-0.slice_session
267680.scope' is called 'lxc_container_user.slice_user-0.slice_session-267680.scope'
2017-08-30 18:15:45: /usr/libexec/netdata/plugins.d/cgroup-network FATAL: Invalid pid 0 # : Success

**Comment by ktsaou** [comment]
ok, could you please post this:

```sh
tree /sys/fs/cgroup
```

**Comment by ktsaou** [comment]
and by fetching http://your.netdata.ip:19999/netdata.conf please post this section:

```
[plugin:cgroups]
	# cgroups plugin resource charts = yes
	# update every = 1
	# check for new cgroups every = 10
	# enable cpuacct stat (total CPU) = auto
	# enable cpuacct usage (per core CPU) = auto
	# enable memory (used mem including cache) = auto
	# enable detailed memory = auto
	# enable memory limits fail count = auto
	# enable swap memory = auto
	# enable blkio bandwidth = auto
	# enable blkio operations = auto
	# enable blkio throttle bandwidth = auto
	# enable blkio throttle operations = auto
	# enable blkio queued operations = auto
	# enable blkio merged operations = auto
	# recheck zero blkio every iterations = 10
	# recheck zero memory failcnt every iterations = 10
	# recheck zero detailed memory every iterations = 10
	# enable systemd services = yes
	# enable systemd services detailed memory = no
	# report used memory without cache = yes
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpu,cpuacct
```

(make sure you post all of it - near its end is what netdata has understood out of your `/sys/fs/cgroup` tree.

**Comment by niksfirefly** [comment]
can i post those to your private email?

**Comment by ktsaou** [comment]
Yes, of course: costa@tsaousis.gr but reference this issue in your email.

**Comment by ktsaou** [comment]
I think this has to be prepended in:

```
search for cgroups in subpaths matching = !/lxc/*/*/ ... whatever is already there ...
```

Could you please try it?

**Comment by niksfirefly** [comment]
well it is not working either

**Comment by ktsaou** [comment]
ok, could you please send again the netdata.conf section to check the decisions of netdata?

**Comment by ktsaou** [comment]
My bad. the right settings are these:

```
enable by default cgroups matching = !/lxc/*/* ... rest of the line ...
search for cgroups in subpaths matching = !/lxc/*/* ... rest of the line ...
```

could you please test it?

**Comment by candlerb** [comment]
I have a similar problem.  Distro is ubuntu 16.04, and there's nothing important on this host so I'm fine to post full details.

Containers:

~~~
root@lxd1:~# lxc list
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
|    NAME    |  STATE  |              IPV4              |                    IPV6                    |    TYPE    | SNAPSHOTS |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| apt-cacher | RUNNING | 10.12.255.31 (eth0)            | XXXX:XXX:XXXX:XXXX::31 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| builder    | RUNNING | 172.17.0.1 (docker0)           | YYYY:YYY:YYYY:21:216:3eff:fe9e:4381 (eth0) | PERSISTENT | 0         |
|            |         | 10.12.21.46 (eth0)             |                                            |            |           |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| ns-auth    | RUNNING | 10.12.255.32 (eth0)            | XXXX:XXX:XXXX:XXXX::32 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| prometheus | RUNNING | 10.12.255.33 (eth0)            | XXXX:XXX:XXXX:XXXX::33 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| smtp       | RUNNING | 10.12.255.34 (eth0)            | XXXX:XXX:XXXX:XXXX::34 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| tick       | RUNNING | 10.12.255.35 (eth0)            | XXXX:XXX:XXXX:XXXX::35 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| unifi      | RUNNING | 10.12.255.30 (eth0)            | XXXX:XXX:XXXX:XXXX::30 (eth0)              | PERSISTENT | 0         |
+------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
~~~

All the containers were created before netdata was installed.  The first time I went to the netdata UI I saw no containers, but after a few minutes they appeared.

In addition to these containers, two spurious extra ones are seen:

* `lxc tick user.slice user-0.slice session-377.scope`
* `lxc tick user.slice user-0.slice session-395.scope`

![](https://user-images.githubusercontent.com/44789/29998671-3d903e24-9029-11e7-85bc-74c49735fb27.png)

More screenshots, including graphs, in https://github.com/firehol/netdata/issues/2668#issuecomment-326769532 . Oddly: `session-377.scope` has a normal set of graphs but they are all zero. `session-395.scope` has graphs for `net eth0`, which none of the other containers have. 

The "tick" container has nothing unusual, just the services of the [TICK stack](https://docs.influxdata.com/chronograf/v1.3/introduction/getting-started/).  There is no nested lxd-in-lxd anywhere on this host. I had previously experimented with docker-in-lxd in the "builder" container, but there are no docker containers running there now.

Information as requested:

* [tree /sys/fs/cgroup](https://gist.githubusercontent.com/candlerb/3bb13d62783a054bb6604c63cdeb4ec4/raw/e77755a99dd0e9bdf5dccb4e5fca53c57ee82901/tree-sys-fs-cgroup.txt) - 48,409 lines, just over 3MB

* [plugin:cgroups section of netdata.conf](https://gist.github.com/b2705e89e2e08c7f4cddcf3522b8bc02)

    I note two important lines here:

    ~~~
            # enable cgroup lxc_tick_user.slice_user-0.slice_session-377.scope = yes
    ...
            # enable cgroup lxc_tick_user.slice_user-0.slice_session-395.scope = yes
    ~~~

**Comment by ktsaou** [comment]
thanks!

Could you please try the 2 settings I posted above? Alternatively, you can `git clone https://github.com/ktsaou/netdata.git` and run `./netdata-installer.sh` for it. It has these settings by default.

**Comment by candlerb** [comment]
netdata.conf now contains:

~~~
# Get config from http://127.0.0.1:19999/netdata.conf
[plugin:cgroups]
        enable by default cgroups matching = !/lxc/*/* !*/init.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/ns  !/machine  !/qemu  !/system  !/systemd  !/user  *
        search for cgroups in subpaths matching = !/lxc/*/* !*/init.scope  !*-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/ns/*  *
~~~

and the spurious containers have now gone from the UI. Thank you!

Container CPU and Memory graphs look good.  Container disk util graphs are all zero, but that's a separate issue (and could be lxd's fault)

**Comment by niksfirefly** [comment]
thank you
it is working exactly as @candlerb said

**Comment by candlerb** [comment]
Aside:

~~~
search for cgroups in subpaths matching = !/lxc/*/* !*/init.scope  !*-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/ns/*  *
~~~

I wonder if the `!/lxc/*/ns/*` is now redundant, given the earlier `!/lxc/*/*` ?

**Comment by ktsaou** [comment]
> I wonder if the !/lxc/*/ns/* is now redundant, given the earlier !/lxc/*/*

yes it is. The new default settings in #2672 has `ns` replaced with the new.

**Comment by ktsaou** [comment]
merged it.
