### ISSUE TITLE
Netdata start issue on Bash on Windows

### ISSUE THREAD

**Issue by JamesMaksen** [firehol/netdata#2653]
Hi folks,

I installed Netdata on unbuntu Bash for Windows 10, it worked fine until today as i have this error when launching it 
---
⋊> / service netdata start                                                                                      09:54:30
 * Starting real-time performance monitoring netdata                                                                    netdata: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
/lib/lsb/init-functions : ligne 30 :   640 Abandon                 (core dumped) /sbin/start-stop-daemon $args --chdir "$PWD" --exec $exec --oknodo --pidfile "$pidfile" -- "$@"

FYI i'm on the last netdata version (runned ./netdata-updater.sh recently).

Someone have any clue on this ?

Thanks in advance,

**Comment by ktsaou** [comment]
No idea but searching for `IN6_IS_ADDR_V4MAPPED`, gives a few clues:

https://github.com/Microsoft/BashOnWindows/issues/2142

**Comment by JamesMaksen** [comment]
Issue resolved Thanks for the tip 👍 

Seem to be related to the network interface added by virtualbox
after deactivating them
and reboot of windows 10
> netdata worked again.
