### ISSUE TITLE
Security question, System Integrity checking detected a modified system file (md5sum comparison test.)

### ISSUE THREAD

**Issue by Sweepr** [firehol/netdata#2655]
LFD on my VPS complains about a changed binary on a daily basis, does this mean the netdata file auto update's and thus the md5sum comparison test fails?

Normally this would only occur upon update so my question is what's happening?

```
Time:     Wed Aug 30 04:00:17 2017 +0200

The following list of files have FAILED the md5sum comparison test. This means that the file has been changed in some way. This could be a result of an OS update or application upgrade. If the change is unexpected it should be investigated:

/usr/sbin/netdata: FAILED
```

```
netdata -V
netdata 1.7.0-186-gd5e6ad1_rolling
```

**Comment by ktsaou** [comment]
Hi,

yes, if you don't want netdata to auto-update, remove `/etc/cron.daily/netdata-updater`.

**Comment by Sweepr** [comment]
Hi,

Just checking to be sure, i'll just add the file to the LFD ignore list.

Thank you for your quick response!,

**Comment by GerasDraugas** [comment]
@Sweepr can you write, where in whm&cpanel to update netdata ignore list?

**Comment by Sweepr** [comment]
When you have CSF installed you should place it in /etc/csf/csf.pignore, in CentOS that is.

**Comment by alexbogias** [comment]
> 
> 
> When you have CSF installed you should place it in /etc/csf/csf.pignore, in CentOS that is.

I added all of these but is still alerts me :(
```
cmd:/usr/sbin/netdata
exe:/usr/sbin/netdata
cmd:/usr/sbin/netdatacli
exe:/usr/sbin/netdatacli
```

**Comment by Sweepr** [comment]
@alexbogias

Did you do restart 'csf -r' ?

**Comment by Sweepr** [comment]
@alexbogias and restarted LFD too i guess?

**Comment by alexbogias** [comment]
@Sweepr hmmm I use webmin and when I save file it says:

> Changes saved. You should restart lfd.

So I sure did. But it says that only LFD is needed...

I'll restart CSF also now and let you know in next update. Thanks

**Comment by OdysLam** [comment]
Hey @alexbogias, welcome to our community.

Ooh boy this is an old thread, I would be very curious to see how you handle the issue. Perhaps we can add a small tip in our docs (cc @joelhans). 

Also folks, we are in the process of migrating the community to our brand new forum! Make sure you join us at https://community.netdata.cloud ! ✌️

**Comment by alexbogias** [comment]
Nice finding you all here @OdysLam 
Καλησπέρα :P

Sorry for resurrecting such an old thread for an off topic "csf" question, but I am trying to mute those alerts for a long time now :(

**Comment by alexbogias** [comment]
@Sweepr Netdata updated and CSF send an alert mail again... Something is wrong :/

**Comment by OdysLam** [comment]
Let's try and get the agent team in here, this is well beyond my expertise 😅

**Comment by alexbogias** [comment]
I will try to add them here:
/etc/csf/csf.dirwatch

**Comment by Sweepr** [comment]
in `/etc/csf/csf.pignore` i have put `exe:/usr/sbin/netdata` and did `service lfd restart` 

I'm not getting any notifications now.

**Comment by alexbogias** [comment]
OK I removed everything else except this one... Thanks @Sweepr
