### ISSUE TITLE
Feature Request: Add the ability to listen on a unix domain socket instead of binding to an IP address.

### ISSUE THREAD

**Issue by Ferroin** [firehol/netdata#2656]
As of right now, netdata only allows serving it's HTTP interface over a regular TCP/IP connection.  This works fine in most cases, but has some limitations, most notably:
1. Access control for local users is complicated.
2. Performance when proxying netdata through another local web server is not as good as it could be.

Adding the ability to listen on a unix domain socket would solve both issues because:
1. You can then use regular POSIX filesystem permissions (and also ACL's) to control local access.
2. You don't incur a round-trip through the TCP and IP stacks when for each request.

Providing this functionality is pretty standard for web applications that expect to be proxied through another web server in regular usage, and connecting to a web application that provides this type of access is well supported in most standard web servers.

Adding this would also provide a much more secure and robust way to handle #2526.

**Comment by ktsaou** [comment]
ok, here it is, but untested. netdata now accepts `unix:/path/to/socket` to all bind to (web, statsd) and connect to settings (backends).

I have just verified the sockets are created. Let's now find how to configure an nginx or apache proxy to unix sockets...

**Comment by ktsaou** [comment]
...and it works... tested it with nginx.
Though netdata complains about certain things on these sockets....
Trying to fix them now...

**Comment by ktsaou** [comment]
Done in PR #2657 
I have tested with nginx and I have resolved all issues.
I would appreciate it if you could test it.

**Comment by Ferroin** [comment]
Double checked, things appear to be working correctly, though I don't have the required stuff to test talking to backends.  Also manually compared output for various requests on UDS versus TCP (netcat is a wonderful tool), and everything matches up correctly there too.
