### ISSUE TITLE
live data

### ISSUE THREAD

**Issue by vendforce** [firehol/netdata#2660]
How can I save settings to keep refresh charts to always instead of focus

**Comment by ktsaou** [comment]
Hi,

it is the first setting on the dashboard settings.

![image](https://user-images.githubusercontent.com/2662304/29938893-d8bf06fc-8e92-11e7-9b30-35d996be084e.png)

If you need it always like that, bookmark a netdata after you set it to `Always` and jump from server to server via the `my-netdata` menu.
