### ISSUE TITLE
Automated installation does not create 'netdata' user and group

### ISSUE THREAD

**Issue by gil-andre** [firehol/netdata#2661]
Deploying netdata in AWS machines, on CentOS 7 (x86-64) servers.

Using pre-compiled binary version `netdata-v1.7.0-186-gd5e6ad1a-x86_64-20170831-062850.gz.run` with installation options: `--quiet --accept --target /opt/netdata/` 

The installation proceeds correctly, but the `netdata` user and group are not created and starting Netdata itself fails with the systemd-related error: `217/USER`, since the `User` configured in `/etc/systemd/system/netdata.service` manifest is set to `User=netdata`.

Obvious correction for this issue is to manually add user & group `netdata`. The service is then able to be started correctly.

However, deploying on a Virtual Box Centos7 VM, user and group are properly corrected using the same version of the pre-compiled binary, and does not encounter the same issue.

Any help, beyond the solution above would be greatly appreciated. Thanks!

**Comment by ktsaou** [comment]
Hi,

Could you please deploy a netdata on such a machine and post the full output of it?
It should provide information about the fault.

**Comment by gil-andre** [comment]
Yes, I'll try to do this on Monday September 4th. I'll post the results here.

**Comment by gil-andre** [comment]
Sorry, running behind. Will post more soon.

**Comment by gil-andre** [comment]
[test_netdata_aws_centos7.txt](https://github.com/firehol/netdata/files/1285393/test_netdata_aws_centos7.txt)

Testing with a brand new AWS machine running CentOS 7.3.1611, the user and group `netdata` are created correctly.

This installation was performed using the netdata installer version: `netdata-v1.7.0-215-gbf207ad3-x86_64-20170907-062852.gz.run`.

I suppose this was a fluke. All my apologies for the noise.

**Comment by ktsaou** [comment]
ok, no problem.
