### ISSUE TITLE
Not seeing lxd containers

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2668]
According to [this page](https://github.com/firehol/netdata/wiki/monitoring-cgroups):

> By default (without any configuration) netdata should pick systemd services, all kinds of containers (lxc, docker, etc) and virtual machines spawn by managers that register them with cgroups (qemu, libvirt, etc).

I've just installed netdata on an ubuntu 16.04 host which has some lxd containers, using the quick form:

~~~
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
~~~

and it has given me `netdata v1.7.0-189-g06de36a9_rolling`

However, none of the containers are being shown (nor the systemd cgroups for that matter).  I see these headings only:

![image](https://user-images.githubusercontent.com/44789/29998367-ff3192ac-9020-11e7-8c81-9bc7ff7f1daf.png)

There *is* a graph under *Netdata Monitoring* for cgroups, showing that the cgroups collection is using a small amount of CPU time.

![image](https://user-images.githubusercontent.com/44789/29998377-3a6c43f8-9021-11e7-88a2-701d27c85405.png)

If I curl <http://127.0.0.1:19999/netdata.conf>  I get:

~~~
...
        # cgroups = yes
...
        # enable by default cgroups matching =  !*/init.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/ns  !/machine  !/qemu  !/system  !/systemd  !/user  *
~~~

which I don't understand as it seems to *disable* docker, lxc etc.

The containers were all present before netdata started.

The cgroups info appears to be fine. For example, one of my containers is called "prometheus" and I have all these:

~~~
# find /sys/fs/cgroup -name 'prometheus'
/sys/fs/cgroup/freezer/lxc/prometheus
/sys/fs/cgroup/blkio/lxc/prometheus
/sys/fs/cgroup/perf_event/lxc/prometheus
/sys/fs/cgroup/devices/lxc/prometheus
/sys/fs/cgroup/hugetlb/lxc/prometheus
/sys/fs/cgroup/pids/lxc/prometheus
/sys/fs/cgroup/net_cls,net_prio/lxc/prometheus
/sys/fs/cgroup/cpu,cpuacct/lxc/prometheus
/sys/fs/cgroup/memory/lxc/prometheus
/sys/fs/cgroup/cpuset/lxc/prometheus
/sys/fs/cgroup/systemd/lxc/prometheus
~~~

Any suggestions as to what I should do next?

**Comment by ktsaou** [comment]
Which distro do you use?

Run this command to make sure the files are there:

```
find /sys/fs/cgroup -name cpuacct.stat -o -name cpuacct.usage_percpu -o -name memory.stat -o -name memory.usage_in_bytes -o -name memory.msw_usage_in_bytes -o -name memory.failcnt -o -name blkio.io_service_bytes -o -name blkio.io_serviced -o -name blkio.throttle.io_service_bytes -o -name blkio.throttle.io_serviced -o -name blkio.io_merged -o -name blkio.io_queued
```

then, post here the `[plugin:cgroups]` section of your `http://your.netdata.ip:19999/netdata.conf`.

**Comment by candlerb** [comment]
Sorry - now I go back to the UI, they are there now.  I guess  I hadn't waited long enough for netdata to pick up the containers; and/or I needed to refresh the web page.

But now I have a different problem. One of my containers is called "tick", but there are two odd-looking extra items:

*  `lxc tick user.slice user-0.slice session-377.scope`
* ` lxc tick user.slice user-0.slice session-395.scope`

![image](https://user-images.githubusercontent.com/44789/29998671-3d903e24-9029-11e7-85bc-74c49735fb27.png)

When I filter your `find` command, I see there are cgroups for 377 but not 395.

~~~
# find /sys/fs/cgroup -name cpuacct.stat -o -name cpuacct.usage_percpu -o -name memory.stat -o -name memory.usage_in_bytes -o -name memory.msw_usage_in_bytes -o -name memory.failcnt -o -name blkio.io_service_bytes -o -name blkio.io_serviced -o -name blkio.throttle.io_service_bytes -o -name blkio.throttle.io_serviced -o -name blkio.io_merged -o -name blkio.io_queued | egrep '\b(377|395)\b'
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.throttle.io_serviced
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.io_serviced
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.throttle.io_service_bytes
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.io_service_bytes
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.io_merged
/sys/fs/cgroup/blkio/lxc/tick/user.slice/user-0.slice/session-377.scope/blkio.io_queued
/sys/fs/cgroup/cpu,cpuacct/lxc/tick/user.slice/user-0.slice/session-377.scope/cpuacct.usage_percpu
/sys/fs/cgroup/cpu,cpuacct/lxc/tick/user.slice/user-0.slice/session-377.scope/cpuacct.stat
/sys/fs/cgroup/memory/lxc/tick/user.slice/user-0.slice/session-377.scope/memory.usage_in_bytes
/sys/fs/cgroup/memory/lxc/tick/user.slice/user-0.slice/session-377.scope/memory.failcnt
/sys/fs/cgroup/memory/lxc/tick/user.slice/user-0.slice/session-377.scope/memory.stat
~~~

* `lxc tick` has `cpu`, `mem`, `disk` graphs. The values look plausible.

![image](https://user-images.githubusercontent.com/44789/29998703-ef9f1144-9029-11e7-90f2-d88c73dfb30c.png)

* `session-377.scope` has `cpu`, `mem`, `disk` graphs too, but they are zeros - even if I look back over the whole hour of history

![image](https://user-images.githubusercontent.com/44789/29998751-13947bec-902b-11e7-8f1b-4b8d76734bbf.png)

* `session-395.scope` has `net eth0` only; and none of the other containers have a `net` entry.

![image](https://user-images.githubusercontent.com/44789/29998714-0a9631e4-902a-11e7-9e6e-0184f625fb10.png)

**Comment by ktsaou** [comment]
I think you face the same problem with #2649
Could you join the discussion there? Try the solutions provided, and if it does not work for you either, please give me the feedback I have requested at that issue, so that I can trace it and find a solution.

**Comment by candlerb** [comment]
OK thanks - closing this one.
