### ISSUE TITLE
"Chart Reset" button doesn't do anything

### ISSUE THREAD

**Issue by pjlegato** [firehol/netdata#267]
After panning a chart, pressing the "Chart Reset" (play button) doesn't do anything.

Double-clicking the chart does perform a reset and restore normal auto-refreshing operation.

Chrome/Mac.

**Comment by pjlegato** [comment]
This is actually a manifestation of the same issue as in #265 -- the reset button does work, but only if no left/right edge whitespace is showing anywhere on the chart. If any whitespace is showing, the reset button doesn't work.

**Comment by ktsaou** [comment]
ok. I close this. we will talk on #265

**Comment by pjlegato** [comment]
Well, the reset button should still work, even if the chart is scrolled into whitespace. That'll be one of the first things the user tries to do to rescue the situation when the chart gets into a weird state.

**Comment by ktsaou** [comment]
You are right.

**Comment by ktsaou** [comment]
But let's discuss all these whitespace issues on #265. Any solution we find will be applied to everywhere.
