### ISSUE TITLE
Netdata running at 100% CPU when the master gets online after some time offline

### ISSUE THREAD

**Issue by theblazehen** [firehol/netdata#2671]
![2017-09-03-084710_938x493_scrot](https://user-images.githubusercontent.com/3276410/30001135-85db258a-9084-11e7-9bea-0fb4c1580643.png)

Will let it keep running if there's anything you want me to look at, otherwise I'll restart it and see if that solves it. It went through a hard shutdown.

[error.log.txt](https://github.com/firehol/netdata/files/1272772/error.log.txt)

**Comment by ktsaou** [comment]
Check these:

2017-09-03 06:48:24: netdata INFO : STREAM jeandreDesktop [receive from [10.128.1.166]:56400]: multiple streaming connections for the same host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.

**Comment by theblazehen** [comment]
Yeah, no idea how that happened, as that host got rebooted as well. It's using the systemd service that the installer installs. Restarted all netdata and it's back to normal now. Thanks.

**Comment by theblazehen** [comment]
@ktsaou Could this possibly be considered as a denial of service vulnerability? Seeing as any host that can relay data to netdata can cause 100% CPU usage, not sure what affect it has on alerting / web interface.

**Comment by ktsaou** [comment]
@theblazehen could you please help me reproduce this?

netdata has only one condition this could happen: the central netdata has a big database for a slave (eg. a few days of metrics), and the slave gets offline for almost that amount of time (without exceeding it). In this case, netdata has to zero all the metrics for the duration the slave was offline. It does this on a per-chart basis on a single thread.

If the duration the slave was offline exceeds the database duration, netdata will just scrap it and start over. So, this is pretty fast.

Of course, if the master was offline, it has to do this for all the slaves. This is the only condition netdata will have use many threads in doing so (one thread per slave).

Is this your case?

**Comment by ktsaou** [comment]
Of course the above is applied to any condition the round robin database has to zeroed. It could happen for example, if data collection stops for a few charts and then it is resumed (eg. you stopped a database server, and then you bring back online). But this normally go unoticed, since it is pretty fast for just a few charts. It is noticeable when netdata has to do this for several thousands of metrics.

**Comment by theblazehen** [comment]
The master and one slave were offline for a couple hours, some other slaves kept running. The master uses iSCSI storage from the slave that went down, so once the slave was brought back up then the master got brought back up a few minutes later. I was using the map memory mode.

Does that help at all?

**Comment by ktsaou** [comment]
thanks! yes, this is what I thought.

Generally speaking, this is a rare condition. I already have a task to optimize this a bit: #2382

**Comment by ktsaou** [comment]
Cleaning up. Let's continue this discussion at #2382
