### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by MartijnBraam** [firehol/netdata#2675]
web_log plugin reports unmatched lines.

This is my log:

```txt
2600:1:b15e:cbf2:2873:6af6:e4a2:51d7 - - [03/Sep/2017:12:20:57 -0400] "-" 408 137 "-" "-"
2600:1:b15e:cbf2:2873:6af6:e4a2:51d7 - - [03/Sep/2017:12:20:57 -0400] "-" 408 137 "-" "-"
2600:1:b15e:cbf2:2873:6af6:e4a2:51d7 - - [03/Sep/2017:12:20:57 -0400] "-" 408 137 "-" "-"
2600:1:b15e:cbf2:2873:6af6:e4a2:51d7 - - [03/Sep/2017:12:20:57 -0400] "-" 408 137 "-" "-"
```

**Comment by ktsaou** [comment]
thanks! @l2isbad another one.

**Comment by l2isbad** [comment]
The problem is not ipv6 lines.
I don't see `$requet" $status`

**Comment by ktsaou** [comment]
oops! you are right.
@MartijnBraam could you please check your web server config? This log is incomplete.

**Comment by MartijnBraam** [comment]
I guess its this:
```
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
```
But wouldn't that mean that _all_ the loglines are unmatched instead only 0.1%?

**Comment by ktsaou** [comment]
@l2isbad I found out why this is happening: http response 408 means "Request Timeout". So the web server did not get the request at all. To my understanding the request URL is this: `"-"`.

I understand this is quite a special case. The web servers does not really have more information to log. Also, these log files may be quite important. A massive 408 ratio may mean that the network that connects the web server to the internet is broken (there is already an alarm for 4xx for such reasons).

I think we should support it somehow.

What do you think?

**Comment by l2isbad** [comment]
Well, sounds reasonable and should be implemented for sure. But i am not sure there is an easy way to do this without breaking compatibility with current implementation of `custom regex feature`.

**Comment by ktsaou** [comment]
> Well, sounds reasonable and should be implemented for sure. But i am not sure there is an easy way to do this without breaking compatibility with current implementation of custom regex feature.

I guess you mean that because web_log auto-detects the pattern to be used, based on the first log entry, if the first entry is a 408 line it may end up with the wrong pattern.

So, actually the problem is to support 408, without breaking pattern auto-detection.

Right?
