### ISSUE TITLE
fail2ban issue (or any other log file)

### ISSUE THREAD

**Issue by G4Zz0L1** [firehol/netdata#2676]
How can I make netdata read the log, if the log are made by root?
I've already tried to add netdata to root group, and launching netdata as root, but it still complain:
`python.d ERROR: fail2ban_fail2ban /var/log/fail2ban.log is not readable or empty`
even if:
`-rw------- 1 root root 927 4 set 01.01 fail2ban.log`

**Comment by l2isbad** [comment]
> python.d ERROR: fail2ban_fail2ban /var/log/fail2ban.log is not readable or empty

https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L74-L76

> add netdata to root group

-rw------- 1 root root 927 4 set 01.01 fail2ban.log

Please add `read` for the `root` group then.

**Comment by G4Zz0L1** [comment]
Ok, it was only that, I've fixed it with a 644 and some changes in the logrotate. Thanks!
