### ISSUE TITLE
prometheus CPU calculation

### ISSUE THREAD

**Issue by vincus** [firehol/netdata#2678]
We are trying to migrate to the new netdata from the old one and convert our old charts.
  It seems there is a bug which prevents to use different dimensions in the same query.
  Example:
`  irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="user"}[2m])`
results: ~200 (as expected)
 ```
 irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="user"}[2m]) + 
  irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="user"}[2m])
```
  results: double of the user cpu (as expected)
```
  irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="user"}[2m]) + 
  irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="system"}[2m])
```
  _**result: no data**_
 ` irate(netdata_system_cpu_total{chart="system.cpu",family="cpu",dimension="system"}[2m])`
  result: ordinary system cpu usage data

  Not sure it is Prometheus or we are trying it wrong

**Comment by ktsaou** [comment]
> Not sure it is Prometheus or we are trying it wrong

Well, you ask prometheus for `user` cpu and you get it, then you ask for `system` cpu and you get this too, but when you add these two, you get no data.

This does not seem netdata related.

@brian-brazil what do you think?

**Comment by brian-brazil** [comment]
This is the way it's meant to work, see https://www.robustperception.io/understanding-machine-cpu-usage/

**Comment by ktsaou** [comment]
ok. Is anything pending? Can we close this?

**Comment by vincus** [comment]
Sure, closing thx

**Comment by SuperQ** [comment]
It would be nice if netdata exposed the cpu dimension in addition to the cpu mode.  This is how we expose it in the `node_exporter`[0].

[0]: https://github.com/prometheus/node_exporter/blob/master/collector/cpu_linux.go#L154-L166

**Comment by ktsaou** [comment]
> It would be nice if netdata exposed the cpu dimension in addition to the cpu mode.

"cpu dimension"? example? what do you mean?

**Comment by SuperQ** [comment]
Here's an example of the metrics `node_exporter` provides:
```
# HELP node_cpu Seconds the cpus spent in each mode.
# TYPE node_cpu counter
node_cpu{cpu="cpu0",mode="guest"} 0
node_cpu{cpu="cpu0",mode="idle"} 1.62540573e+06
node_cpu{cpu="cpu0",mode="iowait"} 2597.56
node_cpu{cpu="cpu0",mode="irq"} 0
node_cpu{cpu="cpu0",mode="nice"} 4149.68
node_cpu{cpu="cpu0",mode="softirq"} 16.28
node_cpu{cpu="cpu0",mode="steal"} 0
node_cpu{cpu="cpu0",mode="system"} 27190.81
node_cpu{cpu="cpu0",mode="user"} 100564.47
node_cpu{cpu="cpu1",mode="guest"} 0
node_cpu{cpu="cpu1",mode="idle"} 1.19748502e+06
node_cpu{cpu="cpu1",mode="iowait"} 2135.45
node_cpu{cpu="cpu1",mode="irq"} 0
node_cpu{cpu="cpu1",mode="nice"} 3522.1
node_cpu{cpu="cpu1",mode="softirq"} 187.95
node_cpu{cpu="cpu1",mode="steal"} 0
node_cpu{cpu="cpu1",mode="system"} 25526.88
node_cpu{cpu="cpu1",mode="user"} 93054.14
```

NOTE: The `node_exporter` metric isn't perfect either, we need to fix the `cpu` label to be more like `cpu="0"`.  And the metric name should be something like `node_cpu_seconds_total`.  We already have an open issue to fix these. :smile:

**Comment by ktsaou** [comment]
I see....

unfortunately netdata sends them as different metrics per core. I understand we should probably provide some kind of mapping to have them mapped in the format you suggest...

**Comment by ktsaou** [comment]
I think I found a way to do this in netdata. Check #2689
