### ISSUE TITLE
decrease python plugins history

### ISSUE THREAD

**Issue by vahit** [firehol/netdata#2680]
Hi guys
We config netdata to keep data only one hour on memory, but out data on python plugins (like mysql) exist for 12 hours and this creates a lot of problems for us.
How can i config python plugins history?

**Comment by ktsaou** [comment]
Hi,

netdata does not have different history options for plugins. The amount of time is controlled by 2 settings: `update every` (seconds) and `history` (entries).

Each plugin can only control its `update every`, but not its `history`. So, if you run netdata with `update every = 1` and `history = 3600`, you will get 1 hour of data (1 * 3600 = 3600 seconds). But if you set python.d.plugin mysql `update every = 10`, then you will get (10 * 3600 = 36000 seconds or 10 hours).

However, you can control history per chart, via `netdata.conf`. You can overwrite the default for any of the charts you like.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
