### ISSUE TITLE
Adding a chart dynamically after netdata already started (question)

### ISSUE THREAD

**Issue by nadeem2001** [firehol/netdata#2681]
Hi,

I was just wondering if it is possible to add a new chart or change the data-host value of a current one so we can switch between hosts/nodes on our server set up.

Currently just trying this out so I have a simple **system.cpu** chart (using **gauge** as the chart type),

I have a number of servers to monitor which are selected by a drop down list. If I select "host 2" for example I want to switch that chart (either by destorying and re-creating or perferably switching the data-host value),

I've tried doing both by using NETDATA pause/unpause and by delaying the NETDATA.start after I dynamically update the data-host (which also didn't load the second hosts data).

Is there a proper way of doing this?

The only other way I can think of is using an iFrame and loading it a fresh which would be the last option.

Regards

**Comment by nadeem2001** [comment]
Okay I think I have this working now.  

Thanks for the awesome bit of kit btw!

**Comment by ktsaou** [comment]
Hi, thanks.

The easiest way is to use bootstrap tabs. `dashboard.js` fully supports them.
