### ISSUE TITLE
use /etc/hostid on freebsd to uniquely identify a netdata server

### ISSUE THREAD

**Issue by muahdib69** [firehol/netdata#2682]
Hello, 

I have a central netdata monitor and 4 headless slaves. One of those slaves some behaves erratic. Al servers are FreeBSD 11.0, version of netdata is 1.6.0.

The host with erratic data shows:
![image](https://user-images.githubusercontent.com/10959054/30062339-208e7c4a-924b-11e7-8947-16bd51364b75.png)

While a server with comparative load shows:
![image](https://user-images.githubusercontent.com/10959054/30062375-38105712-924b-11e7-9279-b613a43af111.png)

I deleted the data from the host in question on the proxy server from /var/cache/netdata, I deleted also the data on the slave itself (not sure if there gets stored anything, I am running in headless mode). 

I restarted the services etc. Monitoring on the slave with systat (reviewing IP and DISK IO) does show normal values.

Any ideas?

Thanks

**Comment by muahdib69** [comment]
OK, I found out the WHY, but not how to really fix it. 

This is a digital ocean server, we cloned the machine (created a snapshot) and sent the snapshot to another datacenter and created a new (test) server.

Now the public id in /var/db/netdata stayed the same and the data got screwed up. 

We set a new id in /var/db/netdata and restarted netdata. Now everything seems OK again. 

Maybe it would be worth (at least on FreeBSD) to use the host id (UUID in /etc/hostid) which normally is generated at installation time. 

....

any ideas?

Thank you

**Comment by ktsaou** [comment]
Hi,

netdata generates a UUID on first start and saves it at `/var/lib/netdata/registry/netdata.public.unique.id`. This UUID uniquely identifies a netdata forever. Of course, if you delete it, it creates a new one.

I didn't know about `/etc/hostid`. It seems a nice idea to use this. Is it guarranteed this to be there? Shall we provide a fallback on freebsd in case this cannot be read?

Today, if netdata cannot create `/var/lib/netdata/registry/netdata.public.unique.id` it refuses to start, as this will break a lot of things. If we don't provide a fallback on freebsd and `/etc/hostid` cannot be parsed (it is not there, it is not a valid GUID, etc), netdata will refuse to start.

**Comment by muahdib69** [comment]
I will do a bit of research on /etc/hostid and I'l comment when I know it's ins and outs.
Thank you for your positive feedback, 

best

**Comment by muahdib69** [comment]
Hello, 

i dug into the /etc/hostid and found the following:

On boot if the file /etc/hostid does not exist, a new hostid is generated (from SMBios.system.uuid, if that fails, a random uuid is generated). This uuid is then set as a sysctl value (kern.hostuuid). There is also an ID generated (32 bit, based on md5 on the kern.hostuuid), which gets stored as kern.hostid. The kern.hostid is generally deprecated as a 32 bit value is to small for a unique id.

Later in the boot process the hostid is written to the /etc/hostid file, if for some reason it differs (e.g. system hardware has changed and smbios.system.uuid has a new value). This can be deactivated with an rc.conf entry, meaning one can set manually a host-uuid and it will never change, or leave it and on occasion it may change. E.g. DigitalOcean does change the smbios.system.uuid bios value every time a virtual machine gets stopped and started (not on a simple reboot tough). Also, DigitalOcean does it's on thing generating the hostid with their own startup scripts, therefore not accepting a administrator setting of not changing the hostid. 

What we opted to do is to make the /etc/hostid file immutable on FreeBSD, so it has an unique value and will never overwritten (as we use digital ocean as well).

All that being said, I would not recommend setting by default the UUID to /etc/hostid on FreeBSD, but I would definitly appreciate the possibilito to configure the path of the UUID file. So on my FreeBSD servers I set netdata uuid file = /etc/hostid and get what I want without having to think about cloning and moving servers around, because changing the /etc/hostid we allready do in such occasions. 

Hope this helps to make an informed decision,

Best

**Comment by ktsaou** [comment]
> I would definitly appreciate the possibilito to configure the path of the UUID file. So on my FreeBSD servers I set netdata uuid file = /etc/hostid and get what I want without having to think about cloning and moving servers around, because changing the /etc/hostid we allready do in such occasions.

This already exists: https://github.com/ktsaou/netdata/blob/793dcded1f97a5493375bb241c8903587426ce39/src/registry_init.c#L24

like this:

```
[registry]
	netdata unique id file = /var/lib/netdata/registry/netdata.public.unique.id
```

**Comment by ktsaou** [comment]
But keep in mind netdata will overwrite this file if it is not a valid GUID.

**Comment by muahdib69** [comment]
Hi, 

thank you very much for your responses. I guess a formal reading of the config files is in order. 

best,
