### ISSUE TITLE
[Question] Gauge chart for disk space used for /

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2687]
I am trying to create a gauge showing the used disk space. But unfortunately it seems that I cant figure out what I should use for the `data-common-max` attribute. 

What is the best way to do this? Is there a way to sum `used` and `avail` dimensions?

```
                 <div data-netdata="disk_space._"
                        data-title="Available disk space for /"
                        data-common-max="disk-space"
                        data-dimensions="avail"
                        data-decimal-digits="0"
                        data-chart-library="gauge"
                        data-width="19%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
  
```

**Comment by ktsaou** [comment]
`data-common-max` and `data-common-min` are used to synchronize the y-range of 2 or more charts. Just give the same keyword to all of them, and the charts will auto-adjust their scale to be the same (and `min` of the smallest become the `min` of all, the `max` of the largest becomes the `max` of all).

The netdata home page https://my-netdata.io uses this to sync all the gauges. The default netdata dashboard uses this on cpu core charts (cpu utilization, interrupts, softnet, etc).

**Comment by ktsaou** [comment]
To sum dimensions on gauge charts, just pipe separate all of them, like `data-dimensions="avail|used"`. If you want to sum all the dimensions, just omit `data-dimensions`.

**Comment by elfgoh** [comment]
This is the partition that i am interested in:

```
/dev/mmcblk0p1   15G  1.3G   13G  10% /
```

It still isnt entirely clear to me how I should display a gauge chart showing just the number of GB used. This is the code snippet that I use but it gives me the wrong results

```
                <div data-netdata="disk_space._"
                        data-dimensions="used"
                        data-decimal-digits="0"
                        data-title="Used disk space for /"
                        data-chart-library="gauge"
                        data-width="19%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
```
<img width="171" alt="screen shot 2017-09-07 at 6 58 39 pm" src="https://user-images.githubusercontent.com/491688/30160365-8fe20b7a-93fe-11e7-979c-4b2f001d4cd3.png">

I expect the gauge to show as 1, with a max of 15. Please enlighten me

**Comment by elfgoh** [comment]
Reading some of the source, I find that modifying `data-gauge-max-value=` does the trick. But how should I used this without a hardcoded value?

**Comment by ktsaou** [comment]
Unfortunately you can't. Netdata dashboards dynamically calculate the max from the last `data-points` entries.

The only way, is to use the same `data-common-max` with another visible chart (any type: gauge, dygraph), that has the right max value. So, if you put another chart with the total and use the same `data-common-max` in both, you will get what you need.

**Comment by elfgoh** [comment]
> The only way, is to use the same data-common-max with another visible chart (any type: gauge, dygraph), that has the right max value. So, if you put another chart with the total and use the same data-common-max in both, you will get what you need.

I can try this. But which chart has the right max value for total diskspace? I cant seemed to find any at the moment

**Comment by ktsaou** [comment]
> I cant seemed to find any at the moment

the one you have used. `data-common-max` will use the visible y-scale:

![image](https://user-images.githubusercontent.com/2662304/30198437-5e814e38-9476-11e7-8768-9cf3e14dbd68.png)

(i.e. the y-axis on the left)

**Comment by ktsaou** [comment]
You can also add a gauge, without setting `data-dimensions`. You will get the sum of all dimensions.

**Comment by ktsaou** [comment]
And I just recalled this:

```
<div data-netdata="system.ram"
    data-dimensions="used|buffers|active|wired"
    data-append-options="percentage"
    data-chart-library="easypiechart"
    data-title="Used RAM"
    data-units="%"
    data-easypiechart-max-value="100"
    data-width="9%"
    data-after="-480"
    data-points="480"
    data-colors="#66AA00">
```

This is used RAM chart on the dashboard.

![image](https://user-images.githubusercontent.com/2662304/30198631-57d20b1c-9477-11e7-998c-a7a7fec27bc0.png)

So, you request from netdata the percentage of any dimension of a chart, vs the chart total.

**Comment by elfgoh** [comment]
Thanks your suggestion looks promising!

Say for `system.ram`, I wished to display the percentage of `buffers`, how do I explicitly achieve that in your example?

In my use case, it displays `avail` disk space, but I wish to display `used` diskspace

```
                <div data-netdata="disk_space._"
                        data-title="Available disk space for /"
                        data-append-options="percentage"
                        data-decimal-digits="0"
                        data-dimensions="used|avail"
                        data-chart-library="gauge"
                        data-width="19%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        data-gauge-max-value="100"
                        data-units="%"
                        ></div>
```

**Comment by ktsaou** [comment]
Set on `data-dimensions` a pipe delimited list of the dimensions, for which you need the percentage, over the total (the sum of all dimensions).

So to get `buffers * 100 / total`, set `data-dimensions="buffers"` and `data-append-options="percentage"`. Similarly for `used`.

**Comment by elfgoh** [comment]
For disk space, it seems like there is a few percentage points of discrepancy, 13.9 vs 15. Is the displayed value correct?

<img width="125" alt="screen shot 2017-09-11 at 6 28 55 pm" src="https://user-images.githubusercontent.com/491688/30270435-23d317ca-971f-11e7-9a41-8c858fec044b.png">
:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            98M   11M   88M  11% /run
/dev/mmcblk0p1   15G  2.0G   12G  15% /
tmpfs           245M   52K  244M   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           245M     0  245M   0% /sys/fs/cgroup
```

**Comment by ktsaou** [comment]
Could you please post the netdata chart instead of `df`?

We need to verify:

1. netdata has the real info in the relative chart of the standard dashboard
2. netdata calculates the percentage properly

**Comment by ktsaou** [comment]
And `df` seems to round things in a strange way:

```
[costa@ktsaou-laptop ~]$ df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/fedora-root   50G   34G   14G  72% /

[costa@ktsaou-laptop ~]$ df
Filesystem              1K-blocks      Used Available Use% Mounted on
/dev/mapper/fedora-root  51474912  35008832  13828256  72% /
```

I mean `13828256 KB` cannot be `14 GB`. It is `13.18 GB`/.

**Comment by elfgoh** [comment]
<img width="1018" alt="screen shot 2017-09-11 at 7 04 15 pm" src="https://user-images.githubusercontent.com/491688/30271772-12559b80-9724-11e7-8340-1b197b263787.png">


I am assuming you require the above chart?

**Comment by elfgoh** [comment]
My df output

```
$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
udev               10240       0     10240   0% /dev
tmpfs              99956   10480     89476  11% /run
/dev/mmcblk0p1  14896384 2072640  12187736  15% /
tmpfs             249888      52    249836   1% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
tmpfs             249888       0    249888   0% /sys/fs/cgroup

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             10M     0   10M   0% /dev
tmpfs            98M   11M   88M  11% /run
/dev/mmcblk0p1   15G  2.0G   12G  15% /
tmpfs           245M   52K  244M   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           245M     0  245M   0% /sys/fs/cgroup
```

**Comment by ktsaou** [comment]
Lets see:

total: `14896384 KB = 14.21 GB`
free: `12187736 KB = 11.62 GB`
used: `2072640 KB = 1.97 GB`, which is `2072640 * 100 / 14896384 = 13.91 %`

So, netdata is right.

**Comment by elfgoh** [comment]
I see. Makes sense from your computation . Guess we cant trust the calculation by `df`. Then what about the figures in this chart? There seems to be about 0.02 Gb discrecpancy
<img width="1018" alt="screen shot 2017-09-11 at 7 04 15 pm" src="https://user-images.githubusercontent.com/491688/30272535-82949f60-9727-11e7-87ab-8cf36d0fa2a9.png">

**Comment by ktsaou** [comment]
It is at the presentation. netdata has decided to show the chart with 1 fractional digit. So, it rounded everything to 1 fractional digit.

The calculations made by the server have up to 7 fractional digits.


So:

total `14.21 GB rounded to 14.2 GB`
free `14.62 GB rounded to 14.6 GB`
used `1.97 GB rounded to 2.0 GB`

**Comment by ktsaou** [comment]
> Guess we cant trust the calculation by df

probably `df` is assuming that `reserved for root` is `used` too. With this added to `used` and rounding to zero fractional digits, `df` is also right.

**Comment by elfgoh** [comment]
Thanks! This issue is considered resolved

**Comment by johnczer** [comment]
So is there a way to add a gauge for disk space in the System Overview section.  I would like to be able to see at a glance how much disk space there is without scrolling to that section.  Thanks
