### ISSUE TITLE
samba plugin always reporting 0 for all metrics

### ISSUE THREAD

**Issue by hopoffbaby** [firehol/netdata#2695]
Hi All,

I have just installed netdata 1.7.0-215-gbf207ad_rolling onto a centos7.3 samba server with samba 4.4.4 installed.

In order to get the samba pluging to show up in the GUI i needed to add netdata to sudoers however the charts are always reporting 0's. 

Does anyone have any suggestions how I can get this working?

Thanks

**Comment by ktsaou** [comment]
Could you please provide the output of the command `smbstatus -P`?

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
