### ISSUE TITLE
can we monitor webrtc?

### ISSUE THREAD

**Issue by johnfelipe** [firehol/netdata#2696]
How can do it?

**Comment by ktsaou** [comment]
I think webrtc is browser-to-browser communication. The webrtc API provides statistics but these are only exposed on the web browsers participating each communication.

So, what netdata can monitor?
Is there any other tool that can monitor webrtc? I see there is https://github.com/indradhanush/WebRTC-Monitor, but check what it does: it opens a chrome in headless mode.

**Comment by ktsaou** [comment]
Cleaning up, but if I have understood this wrong, post here.
