### ISSUE TITLE
timezone setting on the dashboard

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2698]
@glatapoui suggested at #1544 to add an option to switch timezone at the browser, as a feature for easily correlating netdata views with others sources (e.g. log files).

This is a nice one.

**Comment by glatapoui** [comment]
Thank you @ktsaou for entering this request. Basically a simple switch "Remote/Local timezone" would be perfect. 

If you want, here is a little background for our use case: we have netdata alerts going into our slack, where a rapid-response team is watching every incident. Problem is: we have servers in different timezones, and that team is also spread out on mulitple (other) time zones. Each time an alert happens, a member of the team checks the netdata of the corresponding server and the available logs to determine what was happening at that time. And if what is diplayed in the log file and on the webpage of netdata is not in the same time zone, it is harder to find the cause of an incident.

**Comment by ktsaou** [comment]
I have implemented this and a bit more. Actually I tried to detect the current timezone of the system at the server. This was a bit tricky and it works on most of the systems, but not all. The problem is that the javascript needs the time-zone in IANA location format (e.g. `Europe/London`), while posix reports the timezone in iso format (e.g. `GMT+1` or `EST`).

A did a few tricks to get it, but anyway I added a dashboard setting that allows the user selecting, if auto-detection fails. Also, you can set it in `netdata.conf`.

Anyway, it works. I would appreciate it if you could test it.

Check PR #2847

**Comment by glatapoui** [comment]
Hello @ktsaou !

Thank you for your reactivity and for that sweet feature !
It does work for me, and with auto-detect too (in UTC).

Have a great day !

**Comment by ktsaou** [comment]
nice! thank you for your feedback!

**Comment by ktsaou** [comment]
merged it !
