### ISSUE TITLE
Alarms from multiple hosts on a custom dashboard 

### ISSUE THREAD

**Issue by povesteam** [firehol/netdata#2700]
Hi @ktsaou!

I activated alarms in a custom dashboard with charts from different `data-host`s, the alarms are fetched only from the origin host.

```js
netdataShowAlarms = true;
NETDATA.alarms.callback = data => {
    // this display an object with alarms from the first host
    // it should come as an array with all hosts in page, each with its alarms
    console.log('NETDATA.alarms.callback', data);
}
```

This happens because `dashboard.js` `NETDATA.alarms.get` makes an ajax call only once, to `NETDATA.alarms.server`.

I would like to receive alarms from all hosts in this callback, or even in multiple callbacks.

Is there a configuration for this use case?
Or a code snippet to extend this functionality?

The reason for this request is that I want to have a `div` on top of the page that shows all open alarms from all monitored hosts, as a bunch of badges with links to their respective netdata charts.

![image](https://user-images.githubusercontent.com/506532/30211379-7e94bbdc-94a9-11e7-8ada-b118244819ec.png)

Thank you!
Congrats for building such great software!

**Comment by ktsaou** [comment]
Hi,

thanks!

I think #2737 will handle this,
So, let's continue this discussion there.
