### ISSUE TITLE
apcupsd missing dimensions are graphed as zero

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2701]
netdata automatically collects stats from apcupsd.  Woot!

However I noticed something strange and investigated.  The metric `netdata_apcupsd_input_voltage_Volts_average` is reported with three dimensions, "voltage", "min" and "max".  Whilst "voltage" is correct, "min" and "max" are always zero.

~~~
root@nuc2:~# curl -s localhost:19999/api/v1/allmetrics?format=prometheus | grep netdata_apcupsd_input_voltage
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="voltage"} 238.0000000 1504900880000
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="min"} 0.0000000 1504900880000
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="max"} 0.0000000 1504900880000
~~~

It wasn't clear to me if it was netdata responsible for creating the min/max values, or the UPS.

It took me a while, but I think I've found out why.  Looking in `charts.d/apcupsd.chart.sh`, it seems to be parsing some values which my particular apcupsd doesn't return:

~~~
/^MINLINEV.*/           { input_voltage_min = \$3 * 100 };
/^MAXLINEV.*/           { input_voltage_max = \$3 * 100 };
~~~

Whereas apcaccess shows:

~~~
root@nuc2:~# apcaccess
APC      : 001,037,0937
DATE     : 2017-09-08 21:05:59 +0100
HOSTNAME : nuc2.example.net
VERSION  : 3.14.12 (29 March 2014) debian
UPSNAME  : bx700
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2017-09-06 17:36:30 +0100
MODEL    : Back-UPS XS 700U
STATUS   : ONLINE
LINEV    : 238.0 Volts
LOADPCT  : 11.0 Percent
BCHARGE  : 94.0 Percent
TIMELEFT : 37.6 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 3 Minutes
MAXTIME  : 0 Seconds
SENSE    : Medium
LOTRANS  : 140.0 Volts
HITRANS  : 300.0 Volts
ALARMDEL : 30 Seconds
BATTV    : 13.2 Volts
LASTXFER : Low line voltage
NUMXFERS : 3
XONBATT  : 2017-09-08 20:48:03 +0100
TONBATT  : 0 Seconds
CUMONBATT: 300 Seconds
XOFFBATT : 2017-09-08 20:50:28 +0100
SELFTEST : NO
STATFLAG : 0x05000008
SERIALNO : 3B1523X08653
BATTDATE : 2015-06-03
NOMINV   : 230 Volts
NOMBATTV : 12.0 Volts
NOMPOWER : 390 Watts
FIRMWARE : 924.Z3 .I USB FW:Z3
END APC  : 2017-09-08 21:06:01 +0100
~~~

Earlier in the script it sets these values to defaults of zero, and so a timeseries with zero values is generated.

Since my UPS doesn't support MINLINEV and MAXLINEV, I don't know what it's supposed to represent - are they the highest/lowest values seen, or are these thresholds?  In the latter case, maybe LOTRANS and HITRANS respectively can take their place.

~~~
--- usr/libexec/netdata/charts.d/apcupsd.chart.sh.orig	2017-07-21 07:28:40.000000000 +0100
+++ usr/libexec/netdata/charts.d/apcupsd.chart.sh	2017-09-08 21:24:23.866243247 +0100
@@ -107,7 +107,9 @@
 /^BATTV.*/		{ battery_voltage = \$3 * 100 };
 /^NOMBATTV.*/		{ battery_voltage_nominal = \$3 * 100 };
 /^LINEV.*/		{ input_voltage = \$3 * 100 };
+/^LOTRANS.*/		{ input_voltage_min = \$3 * 100 };
 /^MINLINEV.*/		{ input_voltage_min = \$3 * 100 };
+/^HITRANS.*/		{ input_voltage_max = \$3 * 100 };
 /^MAXLINEV.*/		{ input_voltage_max = \$3 * 100 };
 /^LINEFREQ.*/		{ input_frequency = \$3 * 100 };
 /^OUTPUTV.*/		{ output_voltage = \$3 * 100 };
~~~

That works:

~~~
# curl -s localhost:19999/api/v1/allmetrics?format=prometheus | grep netdata_apcupsd_input_voltage
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="voltage"} 236.0000000 1504902330000
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="min"} 140.0000000 1504902330000
netdata_apcupsd_input_voltage_Volts_average{chart="apcupsd.input_voltage",family="input",dimension="max"} 300.0000000 1504902330000
~~~

However there is a more general issue: if a particular data source is not present, would it be possible suppress the output and the chart, rather than generating a metric with a value of zero?  Perhaps the script could return a sentinel value like NULL so that no time series is generated at all, or it is treated as missing data?

There are other apcupsd metrics where I see a zero graph because there is no data: `LINEFREQ`, `OUTV`, `NOMOUTV`, `ITEMP`.  I think those would all be better as no graph.

**Comment by candlerb** [comment]
Sorry, I missed out the one crucial bit of information: I am looking at graphs through prometheus, not netdata's internal interface.  I have a recollection that netdata by default suppresses its own charts with all-zero values.  But prometheus sees these metrics as real values.

**Comment by ktsaou** [comment]
Hi,

according `apcaccess` man page: https://linux.die.net/man/8/apcaccess

```
MAXLINEV: Maximum input line voltage since apcupsd startup
MINLINEV: Minimum input line voltage since apcupsd startup
LOTRANS : Input line voltage below which UPS will switch to battery
HITRANS : Input line voltage above which UPS will switch to battery
```

I think your UPS does not report them, so netdata just uses zeros.

**Comment by candlerb** [comment]
Ah thank you, they are all documented there :-)

> I think your UPS does not report them, so netdata just uses zeros.

Yes, and the problem (for me) is that a time series with zero values is not the same as no time series.  I was confused because there are time series in prometheus which correspond to values which apcupsd is *not* reporting, specifically:

* `netdata_apcupsd_input_voltage_Volts_average{dimension="min"}`
* `netdata_apcupsd_input_voltage_Volts_average{dimension="max"}`
* `netdata_apcupsd_input_frequency_Hz_average`
* `netdata_apcupsd_output_voltage_Volts_average{dimension="voltage"}`
* `netdata_apcupsd_output_voltage_Volts_average(dimension="nominal"}`
* `netdata_apcupsd_temperature_Celsius_average`

**Comment by ktsaou** [comment]
ok.

Ideally, dimensions with just zeros should not be added at all to netdata, but doing so in bash will make the plugin slower. So, I preferred to leave them there with zeros.
