### ISSUE TITLE
Fail2ban module doesn't get all jails

### ISSUE THREAD

**Issue by G4Zz0L1** [firehol/netdata#2702]
I think it may be some misconfiguration, but i don't know what else to try:

Status
|- Number of jail:	19
`- Jail list:	apache-auth, apache-badbots, apache-botsearch, apache-fakegooglebot, apache-modsecurity, apache-nohome, apache-noscript, apache-overflows, apache-shellshock, pam-generic, php-url-fopen, postfix, postfix-rbl, postfix-sasl, recidive, sendmail-auth, sendmail-reject, sshd, webmin-auth

python.d INFO: fail2ban Jails: ['apache-fakegooglebot', 'pam-generic', 'apache-botsearch', 'apache-auth', 'apache-nohome', 'php-url-fopen', 'sendmail-auth', 'apache-overflows', 'recidive', 'apache-badbots', 'apache-noscript', 'apache-modsecurity', 'webmin-auth', 'apache-shellshock']

**Comment by l2isbad** [comment]
Well, where is your jails? 
I see you can define a `file` or a `dir` in the [module configuration file](https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L33-L34).

Plugin searches all the jails in the `file` and in all files in the `dir` and returns them in such order
https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L143-L147

Add them to the active jails if jail status is `true` and removes if `false`.
https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L96-L100

And the last step is to remove some jails if they are defined in [exclude](https://github.com/firehol/netdata/blob/master/python.d/fail2ban.chart.py#L102-L104)

**Comment by G4Zz0L1** [comment]
All my jails are in the jail.local file and the jail dir is empty. The module works perfectly, but not all jails are fetched from that file. The file of the module configuration is the default one, so the exclude parameter is empty.

**Comment by l2isbad** [comment]
Can you post `jail.local` to https://pastebin.com ?

**Comment by G4Zz0L1** [comment]
Sure!
https://pastebin.com/c4JKnjaE

**Comment by l2isbad** [comment]
ok, its a bug, thx for reporting @G4Zz0L1
