### ISSUE TITLE
headless collector on Debian wheezy mips

### ISSUE THREAD

**Issue by debiansid** [firehol/netdata#2707]
Hi there 
I have an ubnt usg-3p, which is running edgeos(aka Debian wheezy for mips). I want to monitor it from netdata, is there a way to cross build headless collector for it, then I can monitor it from master.

Thanks

**Comment by ktsaou** [comment]
hm... sorry I am not familiar with cross compiling, but netdata should be able to compile perfectly on this mips machine.

**Comment by debiansid** [comment]
Ok then I want to know what part of netdata is must have for headless collector?

**Comment by ktsaou** [comment]
> Ok then I want to know what part of netdata is must have for headless collector?

You will need at least the netdata daemon. As far as compilation is concerned, if you can compile the daemon, then you can also compile the few external plugins that need compilation. The rest are in python, node.js or bash.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
