### ISSUE TITLE
[Feature] Show averaging period?

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2708]
Would it be possible to show the averaging period somewhere on the scale when zoomed out? e.g.

~~~
operations/s (15 second average)
~~~

This is because the size of a spike varies depending on the zoom level, and knowing the averaging period is important to interpret this.  For example, zoomed out:

![image](https://user-images.githubusercontent.com/44789/30246773-5336a682-95fb-11e7-8e3c-0c2d1de40ce0.png)

But zoomed in:

![image](https://user-images.githubusercontent.com/44789/30246783-ac20c57a-95fb-11e7-80ff-1d57d6d99b55.png)

ATM what I do is move the cursor a pixel left and right and see how the time value changes, unless I'm missing something...

**Comment by ktsaou** [comment]
nice request!


> ATM what I do is move the cursor a pixel left and right and see how the time value changes, unless I'm missing something...

you are doing right.

**Comment by ktsaou** [comment]
fixed in PR #2833
