### ISSUE TITLE
Install all the required packages

### ISSUE THREAD

**Issue by Nirjonadda** [firehol/netdata#2710]
I am getting error from Install all the required packages for monitoring everything netdata can monitor. Please let me know this fix.

````
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
````

Error Log:

````
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: http-parser >= 2.7.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues
````

**Comment by ktsaou** [comment]
Hi,

this is a problem of your package manager. I don't know how to fix it.
netdata will be installed, even without node.js, so I think you can proceed and then try to find out why your package manager cannot install node.js.

**Comment by Nirjonadda** [comment]
nodejs cannot update/install on centos 7 due to missing http_parser. The reason behind the issue, is in that RHEL 7.4 now includes this package in the default repo, and for that reason its now removed from epel repository. The result is that there is no fight for RHEL users what version is best, but the disadvantage is that Centos users who are stuck for now on Centos 7.3, are missing a dependency for node.js until Centos 7.4 is out that is.
