### ISSUE TITLE
Netdata Installation Introduction for CentOS 7

### ISSUE THREAD

**Issue by Nirjonadda** [firehol/netdata#2711]
How to Netdata Installation for CentOS 7 with cPanel server? I am doing following step by step installation of Netdata for CentOS 7. Please let me know that does this correct steps? Does I am missing any thing?

Install the packages for having a basic netdata installation (system monitoring and many applications, without mysql / mariadb, postgres, named, hardware sensors and SNMP):

Steps 1

````
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata
````
Install all the required packages for monitoring everything netdata can monitor,

Steps 2

````
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
````
CentOS / Red Hat Enterprise Linux

Steps 3

````
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm-sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel
````
Install netdata

Steps 4
````
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
````
Start netdata

Steps 5
````
./netdata-installer.sh
````

**Comment by ktsaou** [comment]
Hi,

yes, this is it pretty much. Steps 1, 2 and 3 are overlapping. Pick any of the 3 - it is not bad to run them all, but all 3 do the same thing.

**Comment by Nirjonadda** [comment]
@ktsaou Then does Steps 1, 2 and 3 are same command and only required packages for monitor?

**Comment by ktsaou** [comment]
yes
