### ISSUE TITLE
Customize email notification subject/body?

### ISSUE THREAD

**Issue by aeros88** [firehol/netdata#2717]
I'm using fping with netdata to alert me via email if one of my IP Cameras goes offline. Would it be possible in cases where fping is throwing the alarm to alter the notification to show the remote host's name rather than the host (server running netdata)?

If my IPC_Entry camera goes offline, an email is sent with subject "server1 is critical - host reachable - fping.ipc_entry.latency". The body of the email also shows the big red banner "server1 is critical".

Looking through alarm-notify.sh, I understand why it says what it says but it does seem misleading at first glance when the email comes in.

**Comment by ktsaou** [comment]
Can you post one such notification?
I think it states the unreachable host.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.

**Comment by Ankk98** [comment]
Did anyone find any solution for this? I also need this functionality. I can contribute if this aligns with the maintainers.
