### ISSUE TITLE
API returns wrong date (1 month in the past)

### ISSUE THREAD

**Issue by andryyy** [firehol/netdata#272]
Hi,
Thanks for this great app!
I'm quering the API like this: /api/v1/data?chart=system.cpu&format=csv

Expected result: `2016-04-19 08:39:00`
Actual Result: `2016-03-19 08:39:00` 

Format doesn't matter, date is always wrong.

Maybe I am missing something? :-)

André

**Comment by ktsaou** [comment]
Thanks for reporting this.
Javascript uses months with January = 0, so the mess with CSV.
Fixed it.

**Comment by ktsaou** [comment]
I close this. It is fixed.
If you need something more, open it again.
