### ISSUE TITLE
how to disable cgroup monitoring

### ISSUE THREAD

**Issue by starplanet** [firehol/netdata#2721]
my machine has hundreds of docker containers. netdata will monitor all these containers default and occupy a lot of memory. I want to disable monitoring docker and add the following lines to netdata.conf:

```
[plugin:cgroups]
enabled = no
search for cgroups under /sys/fs/cgroup/devices = no
enable cgroup docker = no
```

but it doesn't work. Can someone tell me how to configure netdata.conf to disable cgroup monitoring?

**Comment by ktsaou** [comment]
Hi,

Use this section:

```
[plugins]
	# PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
	# PYTHONPATH environment variable = 
	# tc = yes
	# idlejitter = yes
	# proc = yes
	# diskspace = yes
	# cgroups = yes
	# checks = no
	# enable running new plugins = yes
	# check for new plugins every = 60
	# charts.d = yes
	# freeipmi = yes
	# apps = yes
	# node.d = yes
	# fping = yes
	# python.d = yes
```

To learn how to work with `netdata.conf` check this: https://github.com/firehol/netdata/wiki/Configuration#a-note-about-netdataconf

**Comment by starplanet** [comment]
Thanks. I get it.

**Comment by ktsaou** [comment]
Cleaning up. If you need more help, just post here.
