### ISSUE TITLE
[Question] Display uptime in gauge using other time units

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2723]
Is it possible to display the uptime using hours, days, minutes etc, instead of seconds?
``` 
               <div data-netdata="system.uptime"
                        data-title="System uptime"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
```
<img width="157" alt="screen shot 2017-09-12 at 1 38 28 pm" src="https://user-images.githubusercontent.com/491688/30309799-cad3184a-97bf-11e7-93d0-aae20bbd0212.png">

**Comment by elfgoh** [comment]
@ktsaou is what I request possible? If not, it is ok and we can close this issue

**Comment by l2isbad** [comment]
Uptime badge looks nice
https://github.com/firehol/netdata/issues/1842#issuecomment-282554304
(just saying 😄 )

**Comment by ktsaou** [comment]
I have moved all the unit conversion requests to #2745 
Units conversion will also allow us to overwrite the presentation of any value, even for uptime.
So, let's continue this discussion there.
