### ISSUE TITLE
How to remove a registered host?

### ISSUE THREAD

**Issue by fotock** [firehol/netdata#2725]
Hi, one of my netdata host server expired. 
But on the dashboard the menu still shows it every time.

How can I remove/unregister it?

Thanks.

**Comment by ktsaou** [comment]
Use the trashcan icon:

![image](https://user-images.githubusercontent.com/2662304/30341105-87e6e898-97fd-11e7-9d80-72405dfd503f.png)

This removes the last URL you have accessed the server with. If the server had multiple URLs you have to do it many times (yes, I know it is stupid - I will fix it at the next version that will refactor the registry menu).

**Comment by fotock** [comment]
Thanks.
