### ISSUE TITLE
Question: why is it not advised running the install command as a super user instead of waiting for prompt?

### ISSUE THREAD

**Issue by jeanpchr** [firehol/netdata#2726]
The installation section of the wiki says the recommended method of installing netdata is running the `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` command. However, it also says that this command should not be run with `sudo`. I would like to know why running this command as super user is not advised and if there would be any issues in doing so.
The reason for my question is that I'm automating the install of netdata along a mailing server and running the scripts as super user with the `--dont-wait` flag seems the way to go in this case.

**Comment by zek0faws** [comment]
I think if you run the script as sudo it'll be installed all as sudo, and so the files may be not accessibled by www-data. Waiting to have the sudo command to be prompted, it'll execute special commands like create the user and add it to the group. The files created are not sudo.

**Comment by Ferroin** [comment]
There's a lot of stuff that the installer does that does not need to be run with elevated privileges (checking the system to make sure everything that's needed is present for example).  The fewer things that are run with elevated privileges, the fewer places something can potentially go wrong and brick the system.

For an automated deployment situation, assuming you're already running with elevated privileges, it should work fine as you described.

@zek0faws 'sudo' isn't a user or an execution state, it's a privilege elevation command similar in nature to the UAC prompts you get on Windows when you try to install something.  Commands run with sudo have privileges equivalent to the root user (unless you use the -u option to select a different user, then you have privileges matching that user), which means among other things that they can manipulate file ownership however they want, which is in turn the big reason that this matters at all (you can't set file ownership to anyone other than yourself as a normal user).

**Comment by jeanpchr** [comment]
Thank you for the input @Ferroin and @zek0faws.

**Comment by ktsaou** [comment]
btw, it could be done with:

```sh
curl -Ss https://my-netdata.io/kickstart.sh | sudo bash
```

but in this case, the script run will not be able to accept input from the terminal. So, this run would actually be headless.

**Comment by jeanpchr** [comment]
Thank you @ktsaou!
