### ISSUE TITLE
Multi-hosts page empty

### ISSUE THREAD

**Issue by tgalloy** [firehol/netdata#2735]
Hello,

I was trying to make a master netdata server, but when I was going on http://myserver/host/server1, the page wasn't loading charts. I was thinking I was doing something wrong, so I remade everything, but the same thing happened.

In the Web console, I have an error about dashboard.js could not load (Error 404). Netdata is searching him in the /host directory, and I think this is the problem.

PS : Sorry for any language issues, English isn't my first language.

**Comment by GitStoph** [comment]
What happens if you go to http://your.server.fqdn:19999, and then check the registry in the upper left? If your stream config is set properly, the database for that server will be linked for you there?

**Comment by tgalloy** [comment]
I can see the database, and the link is working. Buuuut, I see the problem, and It was a user issue. I forgot a / at the end of the URL... I feel so dumb.
