### ISSUE TITLE
how to authorization for the netdata

### ISSUE THREAD

**Issue by 143230** [firehol/netdata#2739]
i was using the netdata on my personal cloud system, but the netdata can be accessed to every one has the address, so how i can do to prevent the unauthorized access?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/70
https://github.com/firehol/netdata/issues/2732
[Running behind nginx](https://github.com/firehol/netdata/wiki/Running-behind-nginx)
[Running behind apache](https://github.com/firehol/netdata/wiki/Running-behind-apache)

**Comment by 143230** [comment]
Perfect, Thank you very much!!!

**Comment by toxikas** [comment]
thank You very much!
