### ISSUE TITLE
statsd corrupt: ERROR 405 - Cannot download charts index from server

### ISSUE THREAD

**Issue by supergicko** [firehol/netdata#2740]
Hi.

First of all, thank you for the great work on netdata.

Today, I am running the latest netdata (installed via precompiled package via kickstart.sh). Runs fine on many nodes, except one. 

This one gets the error:

"ERROR 405 - Cannot download charts index from server"

-> Downloaded the raw json and saw 2 corrupt fields in the **statsd_meter__1_.meter** key.

```
"statsd_meter__1_.meter": {
			"id": "statsd_meter__1_.meter",
			"name": "statsd_meter__1_.meter",
			"type": "statsd_meter__1_",
			"family": "meters",
			"context": "�1",
			"title": "�1 (statsd_meter__1_.meter)",
```

Since it runs fine on many nodes except one, which system package do I need to upgrade on this particular node to make the **statsd_meter__1_.meter** values working again? 💃 

Thanks in advance,
Cheers

**Comment by ktsaou** [comment]
Hi I think you are sending UTF encoded metrics on this node.
Let me check the code for the composition of context and title....

**Comment by ktsaou** [comment]
Yeap, this is it. The code uses the string you sent to statsd as context and title.
I will convert all invalid characters to `_` for them too.

**Comment by supergicko** [comment]
thanks for quick response @ktsaou 
it was an clean installation without modification btw.

**Comment by ktsaou** [comment]
ready. will be merged in a while (waiting for travis to finish|)

**Comment by ktsaou** [comment]
merged it

**Comment by supergicko** [comment]
@ktsaou thanks will check when binary is available 👍

**Comment by ktsaou** [comment]
Just created an updated binary package.
Re-install it, like you already have.

**Comment by ktsaou** [comment]
It should be: netdata-v1.7.0-264-gca19f8e6-x86_64-20170915-132929.gz.run

**Comment by supergicko** [comment]
@ktsaou so far, everything seems ok. Works. Thanks again
