### ISSUE TITLE
system.swap not seen on netdata

### ISSUE THREAD

**Issue by SarangBalbix** [firehol/netdata#2744]
Hello,

My currently updated install of netdata doesn't seem to have the system.swap setting, as seen on https://ns3003126.postblue.info/#menu_system_submenu_disk;theme=slate;help=true. I have checked and I'm on latest netdata (commit 9671757). Am I missing something?

Thanks!

**Comment by ktsaou** [comment]
2 charts below the one you posted. Here: https://ns3003126.postblue.info/#menu_system_submenu_swap;theme=slate;help=true

**Comment by SarangBalbix** [comment]
Apologies for being unclear - my netdata install doesn't have the system.swap UI - they are in order:
[cpu] [load] [disk] [ram] [swap - this is is missing in my case] [network] ... .

Am I missing some setting?

Thanks!

**Comment by ktsaou** [comment]
oh... sorry!

It is simple to check:

```sh
# cat /proc/meminfo  | grep -i swap
SwapCached:            0 kB
SwapTotal:      16400380 kB
SwapFree:       16400380 kB
```

What is yours?

**Comment by SarangBalbix** [comment]
Ahh that was it - OS bug.
```# cat /proc/meminfo  | grep -i swap
SwapCached:            0 kB
SwapTotal:             0 kB
SwapFree:              0 kB```
