### ISSUE TITLE
allow user settings to control the units of the charts at the dashboard

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2745]
netdata has hard-coded units. So:

- disk I/O is in `kilobytes/s`
- disk size is in `GB`
- memory size is in `MB`
- network bandwidth in is `kilobits/s`
- temperatures in Celcius

The ultimate goal is to allow users to change these on the dashboard.

A simple solution would be to provide a `data-value-formatter="function(){ ... }"` at the charts, to allow the caller overwrite the presentation of the numbers.

To achieve a higher abstraction, another setting should be supported: `data-convert-units-to="wanted units"`. This should automatically change the formatter function and the units of the chart. It could also apply some error checking to ensure the wanted units can be applied to this chart.

Then, on the dashboard, a new settings tab should be added to allow the user set the desired units for each type of metrics.

The above should fix: #2425, #376, #1433, #616

Using the same mechanism arbitrary changes to the presentation of values could be supported. This should fix: #1842 point 6 (uptime) and #2723

**Comment by Ferroin** [comment]
Long term, it would also be nice to have adaptive scaling for units that take metric prefixes (disk space for example).  Doing this would of course require netdata to track what each unit type is (although, just tracking if it uses a metric prefix or not might be enough, as that's really the only practical scaling for anything netdata natively collects).

**Comment by ktsaou** [comment]
@Ferroin an example?

**Comment by Rockstar04** [comment]
I believe that @Ferroin means to allow for units to automatically update based on what would make the most sense. E.g.1000000 bytes displays as 1MB, if that same metric grows to 1000000000 bytes over time, the display would at some point switch to 1GB automatically. Network traffic could also benefit, we go from KB/s at night, to multiple GB/s during our peaks during the day on our database server.

**Comment by ktsaou** [comment]
h,,, this is nice too! I like it. So, an `auto` setting to scale it automatically.

**Comment by simonnagl** [comment]
plus one for the auto setting to scale automatically!

**Comment by ktsaou** [comment]
ok, here it is.... testers needed...
PR #2847 

Just 2 files changes: `index.html` and `dashboard.js` in the web dir. So, you can download them, copy them over the existing ones and press control-F5 on the dashboard to refresh them.

**Comment by ktsaou** [comment]
This is nice:

The dashboard does dynamic units conversion, on the fly, like the following. Note that the chart units change, based on the value of the selected dimension:

![peek 2017-10-06 22-58](https://user-images.githubusercontent.com/2662304/31296227-309a4c06-aaea-11e7-8c7b-3bca6a954372.gif)

**Comment by ktsaou** [comment]
This is almost done. Just a few more tests pending.

**Comment by l2isbad** [comment]
Looks amazing! (uptime looks great now) 😄

**Comment by ktsaou** [comment]
merged it !

**Comment by jvanhees** [comment]
Can we also use this in the Gauge, Piechart and other visualisations?
