### ISSUE TITLE
[question] How to change the title/direction text of network interfaces

### ISSUE THREAD

**Issue by jsveiga** [firehol/netdata#275]
On the Quality of Service and Network Interfaces categories, it is possible to edit the title for the line graphs on netdata.conf "title=" entries, but I couldn't find how to edit the "ethX (in/out)" titles (attached images), or at least how to make netdata correctly recognize which interfaces are actually (in) or (out), as in my case it is wrong (eth0 and eth2 are external interfaces, eth1 is the internal).

Thanks!
![untitled0](https://cloud.githubusercontent.com/assets/7563634/14636919/a65379ae-0604-11e6-81ce-ba019b9a6b5a.png)
![untitled1](https://cloud.githubusercontent.com/assets/7563634/14636925/ad9c8624-0604-11e6-8bd9-437628f95484.png)

**Comment by ktsaou** [comment]
Welcome.

This seems to be a bug. The names should be autodetected.
Could you please tar `/var/run/fireqos` and make it available to me (send me an email if you don't want to post it - no sensitive info is there - just some fireqos metadata).

I'll have a look this evening.

**Comment by jsveiga** [comment]
No problem, here's the tar. Don't mind the huge number of eth1 classes; I'm experimenting with an automatic generation script which pulls proxy login and static dhcp data just to show individual bandwidth usage in the qos graphics. The actual tc is made only on eth0 and eth2, and even without eth1 on fireqos I had "eth0 (in)", "eth2 (out)".

I have also attached the conf files for netdata and fireqos 

(github didn't let me upload tbz2 nor .conf; so I had to zip them)

Thanks again!

[files.zip](https://github.com/firehol/netdata/files/225977/files.zip)

**Comment by jsveiga** [comment]
Ok, I understood what happened.

After looking at the netdata live demo I realized the eth0 (XXX) comes from the id of the interface in the fireqos configuration - but it grabs the text until the "_" or the "-". My interfaces were named "in-vivo", "out-vivo", "in-horz", "out-horz", "in-yk", "out-yk", and it was just grabbing the "in"/"out".

I was here confused thinking netdata was trying to figure out which interfaces where internal/external, and that the "in"/"out" came from this process..

Sorry for the confusion!

**Comment by ktsaou** [comment]
ok. I think I have understood the issue too.
There is a mode in fireqos that creates bi-directional interfaces (in and out with one config). In this mode fireqos appends `-in` and `out`. Netdata strips that and what remains is taken as the name of the interface.

So, if you just rename your interfaces to `X-in` and `X-out` instead of `in-X` and `out-X`, everything should work.

I think I can also add this logic in the `tc-helper` in netdata to avoid this confusion in the future.

**Comment by jsveiga** [comment]
Thank you; it's perfect now (and even more, with the new debian packaging for my Jessie).

Best regards!

**Comment by ktsaou** [comment]
for me to remember:

This is very good: http://stackoverflow.com/a/9406981/4525767

Finds the longest common substring in 2 strings. I'll adapt `tc-helper` to do this, so it will not mater how you write them, it will just get their common part.

**Comment by ktsaou** [comment]
ok. It was a lot more complex to have this comparison (each chart is processed independently) so I just ended up matching `in`, `out` as a prefix and a suffix.
I close this. If any issue remains, please open it again.
