### ISSUE TITLE
is there an option to show zero values?

### ISSUE THREAD

**Issue by woosley** [firehol/netdata#2755]
hi, 
it seems that the webui is sending options "options=ms|flip|jsonwrap|nonzero" to the backend, this will filter out the fields whose values are all zero

is there an option to enable disable this feature. I want to see the metrics on the web even if there are just zero, for example: mysql slow query.

**Comment by ktsaou** [comment]
It is there:

![image](https://user-images.githubusercontent.com/2662304/30530773-42241908-9c52-11e7-8c28-e86818445747.png)

**Comment by woosley** [comment]
thanks!
