### ISSUE TITLE
plugins should support a force option to enable jobs bypassing auto-detection

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2757]
I have the following problem on an active-passive cluster: when the cluster switches and the resources (application servers) are moved from one node to another, we have to restart netdata on the receiving node to activate monitoring for them.

It would be perfect if the users could set at the job level `always_on: true` or `force_on: true` to bypass auto-detection and force specific jobs to be always available.

@l2isbad I understand that in certain cases the `check()` function may provide some initialization. So this functionality should implemented by retrying the `check()` every X seconds (eg 1 minute).

What do you think?

**Comment by ktsaou** [comment]
Or we implement `autodetection_retry: 60` (by default `0` to disable this feature), so that the same setting enables/disables the feature and also sets the retry frequency.

**Comment by l2isbad** [comment]
I agree, this should be implemented.

> autodetection_retry: 60

👍

**Comment by l2isbad** [comment]
> So this functionality should implemented by retrying the check() every X seconds (eg 1 minute)

Ok, i did it. Should the interval be in seconds or minutes?

**Comment by ktsaou** [comment]
> Should the interval be in seconds or minutes?

seconds is nice.

I think of adding a function in netdata to parse durations, like the health module does (suffix `s`, `m`, `h`, `d` any number - the default is `s`). I'll open a new issue for this. So, just support seconds and eventually the users will be able to configure it the way they like it.

**Comment by ktsaou** [comment]
I'll open a new issue for it, to develop this on all plugins and netdata and identify the settings that should support it.
