### ISSUE TITLE
sending messagebird SMS problem

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#2758]
@ktsaou 
Hello, "MESSAGEBIRD_NUMBER" is what？

**Comment by ktsaou** [comment]
https://github.com/firehol/netdata/wiki/messagebird-notifications

**Comment by FANGXIANGQUAN** [comment]
Can I use the test credits to send an alert message?

**Comment by FANGXIANGQUAN** [comment]
think you @ktsaou ,My problem is solved！
