### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by rpyne** [firehol/netdata#2761]
I apologize for not knowing the ins and outs of netdata plugins, but with all of the great plugins listed, I cannot find anywhere that tells how to install a plugin.

**Comment by ktsaou** [comment]
All are installed and most support autodetection.
I most of the cases, you need to configure the application you want to monitor to allow netdata access it.

Each plugin has a config file with its defaults at `/etc/netdata/python.d`, `/etc/netdata/charts.d` and `/etc/netdata/node.d`.

This wiki page has more details: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins
