### ISSUE TITLE
Learning about metrics database.

### ISSUE THREAD

**Issue by talkyy** [firehol/netdata#2762]
Hi all,
I have to know about metrics database of netdata so i have some questions below:
1. Is metrics database a time-seri database?
2. How does netdata  store metrics?
3. Do all metrics have any structure?
4. Can we get these metrics to predict system's trend?
Sorry for my bad English and thanks for your support!

**Comment by ktsaou** [comment]
Hi,

1. by default netdata stores them in its own database, but it can push them to graphite, opentsdb, prometheus and all compatible ones.

2. there are many memory modes supported https://github.com/firehol/netdata/wiki/Memory-Requirements

3. netdata, internally organizes metrics into hosts, charts, and dimensions, the same way they are viewed in the dashboard.

4. of course, that is the idea. You can query directly netdata using its API https://github.com/firehol/netdata/wiki/REST-API-v1, or you can configure netdata to push metrics to a time-series db and query that.
