### ISSUE TITLE
Not working in digitalocean droplet with lnmp enviroment

### ISSUE THREAD

**Issue by johnfelipe** [firehol/netdata#2767]
I have droplet with ubuntu 14 in digitalocean with this lnmp env https://github.com/lj2007331/lnmp

I do this:

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

This is log:
https://gist.github.com/johnfelipe/00894b9e5513e5215b6541f646e38eca

But i cant acces:

> ERR_CONNECTION_TIMED_OUT

How solve this?

**Comment by ktsaou** [comment]
You probably have a firewall active, that prevents your browser from accessing netdata.
If it was "CONNECTION REFUSED" then netdata could possibly not running. But "CONNECTION TIMEOUT" means your browser cannot talk to it.

**Comment by johnfelipe** [comment]
Distributor ID: Ubuntu
	Description:    Ubuntu 14.04.5 LTS
	Release:        14.04
	Codename:       trusty

How can review that, pls share me instruction for review and active only netdata, i need all working same:

http://200.122.209.132/

Stay alert

**Comment by ktsaou** [comment]
1. verify netdata runs:

```sh
# sudo netstat -nat | grep 19999
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN 
```

If it does not show anything, start netdata:

```sh
systemctl start netdata
```

and check again if it runs.

2. Once it runs, then allow it at the firewall:

```sh
iptables -I INPUT -p tcp --dport 19999 -j ACCEPT
```

3. open your browser and go to `http://your.server.ip:19999/`

But, I suggest to read the docs of your system to understand how to configure things in it. The `iptables` command I gave you above is not a good solution.
