### ISSUE TITLE
Can't send data to influxdb

### ISSUE THREAD

**Issue by critaL** [firehol/netdata#2769]
Hey

I tried making it so netdata sends it's data to a influxdb backend but i'm having no luck.

My influxdb is a container running on ip 192.168.1.118:8083 and netdata is running on another machine.
Here is the netdata.conf:

        [backend]
         host tags =
         enabled = yes
         data source = average
         type = graphite
         destination = tcp:192.168.1.118:8086
         prefix = netdata
         hostname = nms1
         update every = 10
         buffer on failures = 10
         timeout ms = 20000
         send names instead of ids = yes
         send charts matching = *

If i ssh into the container and use the influx command, i can see that no data is being written to the influxdb database. Also, where do i specify which database netdata sends it's data to?

**Comment by critaL** [comment]
This was fixed by me enabling opentsdb in influxdb.conf

**Comment by ktsaou** [comment]
Yes, and `type = opentsdb` at netdata.conf (you have `graphite` above).
