### ISSUE TITLE
display only top x out of y processes

### ISSUE THREAD

**Issue by cocoon** [firehol/netdata#2770]
Hi,

I just started some weeks ago with netdata and it's working mostly great.

One thing I did not figure out is if it is somehow possible to let a graph only show for example the top 5 processes with the highest cpu usage out of a processlist of 10.

I have appgroups with many processes and want only to display the heavy ones dynamically.

Is something like this implemented?

One usecase would be you have a fixed display that only can show a limited number of graphs on the dislpay and instead of creating 20 graphs and need to scroll manually it would be possible to display it live in one graph.

**Comment by ktsaou** [comment]
Hi,

Unfortunately netdata does not work like that. The top 5 processes may change over time. So the top processes now, may not be the same to the top processes 10 seconds before. So, at the end we will have to monitor every single process in the system.

This is what apps.plugin does with apps groups.

Keep in mind that if you don't have systemd services enabled, [you can configure your systemd](https://github.com/firehol/netdata/wiki/monitoring-systemd-services) to expose metrics per service and netdata will show them all.
