### ISSUE TITLE
Sending metrics to another netdata server causes 100% CPU usage on pfsense router

### ISSUE THREAD

**Issue by critaL** [firehol/netdata#2771]
Hey

I've succesfully installed netdata on my pfsense router and everything is working great. However, i want to send the metrics to another centralized netdata server. For this i am configuring the pfsense router as a slave with the stream.conf file, this is what it looks like:

    [stream]
    # Enable this on slaves, to have them send metrics.
    enabled = yes
    
    # Where is the receiving netdata?
    # A space separated list of:
    #
    #      [PROTOCOL:]HOST[%INTERFACE][:PORT]
    #
    # If many are given, the first available will get the metrics.
    #
    # PROTOCOL  = tcp or udp (only tcp is supported by masters)
    # HOST      = an IPv4, IPv6 IP, or a hostname.
    #             IPv6 IPs should be given with brackets [ip:address]
    # INTERFACE = the network interface to use
    # PORT      = the port number or service name (/etc/services)
    #
    # This communication is not HTTP (cannot be proxied by web proxies).
    destination = tcp:192.168.1.56:19999

    # The API_KEY to use (as the sender)
    api key = redacted

I have noticed that if i have set the stream to "yes" the CPU usage maxes out at 100 %. If i leave it "off", there is no issues. I am using the latest freebsd [version](https://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/netdata-1.7.0.txz) of netdata.

**Comment by simonnagl** [comment]
Hi,

this was a bug which was fixed with release 1.8.0. Check [Installation](https://github.com/firehol/netdata/wiki/Installation) on how to get the latest netdata.

Alternatively you can wait until @mmokhi updates the package.

**Comment by mmokhi** [comment]
It's committed minutes ago :sweat_smile: [sorry for delay, was under review :wink:]

**Comment by ktsaou** [comment]
thanks! I am closing this, but you can still post.

**Comment by critaL** [comment]
Thank you @mmokhi ! However, i cannot seem to find it? When i browse https://pkg.freebsd.org/FreeBSD:10:amd64/latest/All/ for netdata 1.8 i only find the 1.7 release. Am i doing something wrong?
