### ISSUE TITLE
Rearranging charts

### ISSUE THREAD

**Issue by Komic** [firehol/netdata#2774]
This might be pretty dumb but I haven't found anything about this in the wiki: let's say I'd like to move my only `dns_query_time` chart from its own group to the _Network Interfaces_ one, would I have to edit the plugin or is there an easier way to edit that kind of stuff?

Cheers!

**Comment by ktsaou** [comment]
Unfortunately there is no configuration for that.

The main menu item each chart belongs, is decided at `index.html`, [here](https://github.com/firehol/netdata/blob/20980d7907d6a81dd05eea417e2fdadea87ef03c/web/index.html#L1204-L1299). Currently this decision is based on the first element of the chart id (which means you cannot change it at the plugin).

**Comment by Komic** [comment]
Oh alright, I might try to throw a dirty hack at this on my fork then. Thanks!
