### ISSUE TITLE
When build rpm for ia64 error "zlib required but not found"

### ISSUE THREAD

**Issue by android116** [firehol/netdata#2778]
When I try to build a rpm for SLES-11 ia64, I get an error:

`checking for ZLIB... no

configure: error: zlib required but not found. Try installing 'zlib1g-dev' or 'zlib-devel'.

error: Bad exit status from /var/tmp/rpm-tmp.60979 (%build)`

 when compiling. But the packages of zlib are installed:

`rpm -qa | grep zlib

zlib-devel-1.2.3-106.34

zlib-1.2.3-106.34`

**Comment by ktsaou** [comment]
A few systems have broken `pkg-config`.

To bypass that check, append `--libs-are-really-here` to the command line you . If the libs are really installed, netdata will be compiled successfully.

**Comment by android116** [comment]
Sorry, I do not quite understand where I need to specify the `--libs-are-really-here`.
I collect the package with a command:
`rpmbuild -ba /usr/src/packages/SPECS/netdata.spec`

**Comment by ktsaou** [comment]
oops! sorry.

Execute these before building the rpm:

```sh
    export ZLIB_CFLAGS=" "
    export ZLIB_LIBS="-lz"
    export UUID_CFLAGS=" "
    export UUID_LIBS="-luuid"
```

**Comment by android116** [comment]
Thanks, it helped, but now the package assembly stops with such an error:

```
make[2]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/web'
make[1]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/web'
Making install in contrib
make[1]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0/contrib'
make[2]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0/contrib'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/contrib'
make[1]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/contrib'
Making install in tests
make[1]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0/tests'
make[2]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0/tests'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/tests'
make[1]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0/tests'
make[1]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0'
make[2]: Entering directory `/usr/src/packages/BUILD/netdata-1.8.0'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0'
make[1]: Leaving directory `/usr/src/packages/BUILD/netdata-1.8.0'
+ find '' -name .keep -delete
find: `': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.23783 (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.23783 (%install)
```

**Comment by ktsaou** [comment]
The command executed is this: `find "${RPM_BUILD_ROOT}" -name .keep -delete`
So, I guess your `RPM_BUILD_ROOT` is unset?

**Comment by android116** [comment]
Oops. Sorry, this I tried to do under the root it is not right. Correctly from under the average user. But here is another mistake. For some reason the catalog in /etc
`make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/etc/netdata/charts.d'
 /bin/mkdir -p '/etc/netdata'
/bin/mkdir: cannot create directory `/etc/netdata': Permission denied
/bin/mkdir: cannot create directory `/etc/netdata': Permission denied
 /bin/mkdir -p '/etc/netdata/node.d'
 /bin/mkdir -p '/etc/netdata/health.d'
/bin/mkdir: cannot create directory `/etc/netdata'make[2]: *** [install-dist_chartsconfigDATA] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [install-dist_configDATA] Error 1
: Permission denied
make[2]: *** [install-dist_nodeconfigDATA] Error 1
/bin/mkdir: cannot create directory `/etc/netdata': Permission denied
make[2]: *** [install-dist_healthconfigDATA] Error 1
make[2]: Leaving directory `/home/iv/rpmbuild/BUILD/netdata-1.8.0/conf.d'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/iv/rpmbuild/BUILD/netdata-1.8.0/conf.d'
make: *** [install-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.67261 (%install)`

is being created, but of course it can not, because there is no root right. Am I doing something wrong?

**Comment by ktsaou** [comment]
Hm... I don't know.
Could you please post the commands you use to build the rpm?

**Comment by android116** [comment]
So, first and in order:

```
mkdir ~/rpmbuild
mkdir ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
echo '%_topdir %(echo $HOME)/rpmbuild' >~/.rpmmacros
```

```
export ZLIB_CFLAGS=" "
export ZLIB_LIBS="-lz"
export UUID_CFLAGS=" "
export UUID_LIBS="-luuid"
```

in `~/rpmbuild/SOURCES/`
`netdata-1.8.0.tar.gz  netdata-1.8.0.tar.xz`

in `~/rpmbuild/SOURCES/` - `netdata.spec` from `netdata-1.8.0.tar.gz`

When I tried to build a package, I got an error:
```
rpmbuild -ba ~/rpmbuild/SPECS/netdata.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.99631
+ umask 022
+ cd /home/iv/rpmbuild/BUILD
+ cd /home/iv/rpmbuild/BUILD
+ rm -rf netdata-1.8.0
+ tar -xf /home/iv/rpmbuild/SOURCES/netdata-1.8.0.tar.xz
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Error exit delayed from previous errors
error: Bad exit status from /var/tmp/rpm-tmp.99631 (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.99631 (%prep)
```

Then I fixed in the `netdata.spec` line
`Source0:       https://github.com/firehol/%{name}/releases/download/v1.8.0/%{name}-1.8.0.tar.xz`
on
`Source0:        https://github.com/firehol/%{name}/releases/download/v1.8.0/%{name}-1.8.0.tar.gz`

After that the assembly went, but stopped on the error of creating directories.
If you create directories in the `/etc/netdata`, then there will be an error creating directories in `/usr/share/netdata`, `/var/log/netdata`, `/var/log/cache/netdata`.

I do not understand why in the assembly of RPM there are attempts to create directories, which in theory should be created only when installing rpm

**Comment by ktsaou** [comment]
I am downloading SLES to try to find the issue.
If anyone knows how to help, please do so.

**Comment by android116** [comment]
Thank you. But I admit that everything can be a little different. I have:

```
cat /etc/SuSE-release 
SUSE Linux Enterprise Server 11 (ia64)
VERSION = 11
PATCHLEVEL = 0
```

```
uname -a
Linux test 2.6.27.19-5-default #1 SMP 2009-02-28 04:40:21 +0100 ia64 ia64 ia64 GNU/Linux
```

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
