### ISSUE TITLE
How to display data from other servers when they are slaves?

### ISSUE THREAD

**Issue by critaL** [firehol/netdata#2779]
Hi,

I am trying to develop a custom dashboard and i'm having issues displaying data from other servers. I am using the master/slave configuration where the other netdata servers are sending their data to a master.

Here is the index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>NetData TV Dashboard</title>
    <meta name="application-name" content="netdata">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <meta property="og:locale" content="en_US" />
    <meta property="og:image" content="https://cloud.githubusercontent.com/assets/2662304/22945737/e98cd0c6-f2fd-11e6-96f1-5501934b0955.png"/>
    <meta property="og:url" content="http://my-netdata.io/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="netdata"/>
    <meta property="og:title" content="netdata - real-time performance monitoring, done right!"/>
    <meta property="og:description" content="Stunning real-time dashboards, blazingly fast and extremely interactive. Zero configuration, zero dependencies, zero maintenance." />
    
</head>
<script>
var netdataTheme = 'slate'; // this is dark
// Set the default netdata server.
// on charts without a 'data-host', this one will be used.
// the default is the server that dashboard.js is downloaded from.
// var netdataServer = 'http://my.server:19999/';
</script>
	 <script type="text/javascript" src="http://nms1:19999/dashboard.js"></script>

<body>

<div style="width: 100%; text-align: center;">
	<div data-netdata="net.ens192"
         data-chart-library="gauge"
         data-width="250px"
         data-after="-60"
         data-points="60"
	 data-title="nms1 network"
	 data-units="megabits/second"
    	></div>
	<div data-netdata="net.ens192"
	 data-host="http://nms1:19999/host/ansible/"
         data-chart-library="gauge"
         data-width="250px"
         data-after="-60"
         data-points="60"
	 data-title="ansible network"
	 data-units="megabits/second"
    ></div>
</div>
</body>
</html>
```

The issue is with the "data-host" on the second gauge. I cannot get any data extracted from it. I cannot seem to find any info on this, it's probably real easy though.

Also, is my "data-units" correct? Will they display in mbit/s instead of kbps?

**Comment by ktsaou** [comment]
It works for me (I just changed `nms1` and `ansible` to my hosts):

![image](https://user-images.githubusercontent.com/2662304/30763352-76758fbc-9fee-11e7-9818-1bda28212578.png)

To trace the issue, when you view the dashboard, press F12 and open the network tab. Are the queries successful? (status 200 = ok).

Regarding the units, you are just changing the label. Unfortunately you cannot change the values yet. This requires #2745 to be implemented.

**Comment by critaL** [comment]
Yes the status is 200, however i get the following error: 
![netdataissue](https://user-images.githubusercontent.com/788321/30771068-76305a5e-a03f-11e7-81bd-17a7d08bbaf4.PNG)

**Comment by ktsaou** [comment]
Then, I guess `net.ens192` is not a valid network interface of your ansible host. I that right?

**Comment by critaL** [comment]
Unfortunately no, it is the correct interface. Maybe i did something wrong when setting up master/slave? Mainly in the netdata.conf? 

In every slave's netdata.conf i set the following:

memory mode = none
web mode = none

And it's sending it's metrics to a influxdb backend.

**Comment by ktsaou** [comment]
If you go to `http://nms1:19999/host/ansible/` do you get a working dashboard?
If not, that is the problem. You probably have memory mode = none at the master.
If you get the dashboard, then check if the network interface is there.

**Comment by critaL** [comment]
![image](https://user-images.githubusercontent.com/788321/30776481-7f22d606-a0a7-11e7-913c-bc6a036be725.png)

I got the dashboard and found the network interface.

**Comment by ktsaou** [comment]
Your running html file is not the one you posted above.

At the browser screenshot with debugging I see `http://ansible:19999/...`, but it should be `http://nm1:19999/host/ansible/...`.

Could you please post a browser console error while requesting the chart from netdata master?

**Comment by critaL** [comment]
I don't quite follow sorry. When i'm using the default dashboard that comes with netdata, everything works perfectly. But when i try to make my own custom dashboard and add individual charts from different machines, that's when i get the problem. I can request everything from the master (nms1) but when i request charts from other hosts e.g. ansible, i get an error. 

If i understood you correctly you want the debug from loading the custom dashboard:

![image](https://user-images.githubusercontent.com/788321/30776585-6f0a7452-a0a9-11e7-973b-4d3a80610304.png)

Again, sorry if i misunderstood you.

**Comment by ktsaou** [comment]
ok,

on your html you have:

```
</script>
	 <script type="text/javascript" src="http://nms1:19999/dashboard.js"></script>

<body>

<div style="width: 100%; text-align: center;">
	<div data-netdata="net.ens192"
         data-chart-library="gauge"
         data-width="250px"
         data-after="-60"
         data-points="60"
	 data-title="nms1 network"
	 data-units="megabits/second"
    	></div>
	<div data-netdata="net.ens192"
	 data-host="http://nms1:19999/host/ansible/"
         data-chart-library="gauge"
         data-width="250px"
         data-after="-60"
         data-points="60"
	 data-title="ansible network"
	 data-units="megabits/second"
    ></div>
</div>
```

So, you load `dashboard.js` from `http://nms1:19999/`, the first host is does not have a `data-host` so it comes for the host `dashboard.js` is loaded, and the second chart says it should come from `http://nms1:19999/host/ansible/`.

You have verified that `http://nms1:19999/host/ansible/` shows a dashboard and there is chart `net.ens192` there.

But, your screenshot says:

![image](https://user-images.githubusercontent.com/2662304/30776644-d7e1780a-a0b2-11e7-8c59-e8373cf4e95a.png)

So, the html you posted above and one you use are not the same. The second chart on your version of the html says `data-host="http://ansible:19999/"`, which as you said above is a slave, configured to work headless (no API, no DB), so your custom dashboard gets a connection refused.

To fix it, at the second chart, put the right URL and it will work.

**Comment by critaL** [comment]
Yes! Thank you, it worked now. 

However i noticed that immediately after changing the URL it still would not work so i had to open an incognito window and then it worked. I feel so stupid...

Thanks again, you can close this now :)

**Comment by ktsaou** [comment]
> However i noticed that immediately after changing the URL it still would not work so i had to open an incognito window and then it worked

Probably you should have to press control-F5 to force reloading the html. Incognito did the same (did not use the cached version of the html).
