### ISSUE TITLE
question -- cluster support for netdata

### ISSUE THREAD

**Issue by techie879** [firehol/netdata#2782]
Hi, 

I am a newbie in netdata world.  We have several hundred systems in an HPC cluster.  Can netdata be used to collect metrics from all these machines and provide central reporting?

thanks.

**Comment by critaL** [comment]
Maybe [this](https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes) is what you're looking for?

**Comment by techie879** [comment]
Thanks, critaL, I will give this a try.

**Comment by ktsaou** [comment]
If the systems are ephemeral, @critaL suggestion is the way to go. If the systems are not ephemeral, then just install netdata on all of them. You can centralize the metrics if you want, but it is not required.

**Comment by ttben** [comment]
Hi,

Sorry to discuss on a closed issue ; but "You can centralize the metrics if you want, but it is not required." Do you have any pointer on *how* doing this? I am thinking of monitoring a cluster of raspberry pi, maybe using netdata docker-image.

Thanks!

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/wiki/Replication-Overview
and this: https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes
