### ISSUE TITLE
Running into issues with nginx reverse proxy

### ISSUE THREAD

**Issue by critaL** [firehol/netdata#2787]
Hi, 

I want to put my custom dashboard behind a nginx reverse proxy and i'm getting a blank page after doing so. This is the error i get when loading the page:

```Mixed Content: The page at 'https://dash.domain.com/' was loaded over HTTPS, but requested an insecure script 'http://nms1:19999/dashboard.js'. This request has been blocked; the content must be served over HTTPS. ```

Here is the nginx configuration for the site:
```
upstream backend {
    # the netdata server
    server nms1:19999;
    keepalive 64;
}

server {
    # nginx listens to this
    listen 80;

    # the virtual host name of this
    server_name dash.domain.com;
    root /usr/share/nginx/html;
        location ~ /.well-known {
                allow all;
        }

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl http2;
        server_name dash.domain.com;
        resolver 8.8.4.4 8.8.8.8 valid=300s;
        resolver_timeout 10s;
        root /usr/share/nginx/html;
        location ~ /.well-known {
                allow all;
        }

        ssl_certificate /etc/letsencrypt/live/redacted/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/redacted/privkey.pem;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';

        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/letsencrypt/live/redacted/chain.pem;

ssl_dhparam /etc/ssl/certs/dhparam.pem;
        ssl_ecdh_curve secp384r1;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend/dash.html;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}
```

So basically i want to proxy my custom dashboard which is at http://nms1:19999/dash.html to dash.domain.com and i'm getting issues when requesting dashboard.js over https.

**Comment by ktsaou** [comment]
At your custom dashboard, change `http://nms1:19999/` to `//nms1:19999/`. This way the browser uses the protocol the dashboard is accessed with.

Generally, everything supplied by the stock netdata, uses relative URLs. There is nothing hardcoded to `http` or `https`. All these are decided by your browser at runtime.

**Comment by ktsaou** [comment]
There is one exception: the registry URL. But this is configured by you at `netdata.conf`.

**Comment by critaL** [comment]
Hmm, in my dashboard i changed it from:
 `<script type="text/javascript" src="http://nms1:19999/dashboard.js"></script>` 
to:
 `<script type="text/javascript" src="//nms1:19999/dashboard.js"></script>`

If i understood you correctly, that's what im supposed to do right? Then i get the same blank page but with a new error: `GET https://nms1:19999/dashboard.js net::ERR_SSL_PROTOCOL_ERROR`

**Comment by ktsaou** [comment]
I meant: `//dash.domain.com/dashboard.js`.
The whole idea is to pass it through the proxy.

**Comment by critaL** [comment]
I'm sorry i don't follow,

In which file should i change it to `dash.domain.com/dashboard.js`? In my custom dashboard .html file i have the following: 
`<script type="text/javascript" src="//nms1:19999/dashboard.js"></script>`
And my nginx conf remains the same as above.

Because if i change the line: `<script type="text/javascript" src="//nms1:19999/dashboard.js"></script>`
to: `<script type="text/javascript" src="//dash.domain.com/dashboard.js"></script>` it does not find the file.

Or is this in the netdata.conf file?

**Comment by ktsaou** [comment]
ok:

You have your netdata server running as `http://nms1:19999`

You are proxying it via an nginx at `https://dash.domain.com`.

Since you want it proxied, you should now **forget that you can access `http://nms1:19999` directly**. If you use the git version of netdata you can also apply an access list in `netdata.conf`, so that netdata at `nms1:19999` will only accept requests from the nginx server and your netdata slaves.

Then, you have a custom dashboard. Which URL you should use? We said that `http://nms1:19999/` does not exist any more. Never use `http://nms1:19999/` anywhere except `nginx.conf` (nginx should be the only one knowing where your netdata really is). So, the URL to use for your dashboard is `https://dash.domain.com`.

If you want your dashboard to work with both HTTP and HTTPS, you can omit the protocol and use it like `//dash.domain.com/`. But you need to configure your nginx accordingly.

**Comment by critaL** [comment]
Then i think i have everything correctly but since it's still not working i have created a gist for you to check all of the relevant config files, [here](https://gist.github.com/critaL/4c1614b4d3e2fde60a76d304ccb1774d).

I really appreciate all the help i am getting.

**Comment by ktsaou** [comment]
In `dash.html` search and replace all occurrences of `http://nms1:19999/` or `https://nms1:19999/`, with:

`https://dash.domain.com/`

(or whatever is the nginx hostname you use).

So, your slave would be:

`https://dash.domain.com/host/ansible/`

**Comment by critaL** [comment]
https://gist.github.com/critaL/4c1614b4d3e2fde60a76d304ccb1774d

Okay i did that but it still would not work, I'm still getting this error:

![gist](https://user-images.githubusercontent.com/788321/30782308-ce9094de-a12f-11e7-878a-3fb1bdc25752.PNG)

**Comment by ktsaou** [comment]
@critaL you did not do what I told you to do.
The URL I see on the screenshot should have been replaced.
If you change the file on disk, but it does not change on your browser, press CONTROL-F5 on your browser.

**Comment by critaL** [comment]
Sorry about that, i thought you only meant the data-host portions. Here is an updated screenshot:

![gist](https://user-images.githubusercontent.com/788321/30782391-f392f072-a131-11e7-8ffb-b2889f0909a0.PNG)

**Comment by ktsaou** [comment]
ok. Does it work now? I don't see any errors.

**Comment by critaL** [comment]
No it does not I'm afraid, it times out. I'm starting to wonder if it's just easier to host a webpage directly on the webserver instead of trying the reverse proxy way. I'll try that tomorrow morning and let you know how it goes.

**Comment by ktsaou** [comment]
@critaL I don't see any errors on the screenshot. Could you please switch to the network tab and find the request that has Status not equal to 200.

**Comment by critaL** [comment]
![gist](https://user-images.githubusercontent.com/788321/30794818-b0e9a376-a1ca-11e7-86ee-0828086bd644.PNG)

The problem almost certainly is that i'm hosting the custom dashboard on the netdata master itself and not on the nginx machine. In my dash.html file i now have the following: `<script type="text/javascript" src="https://dash.viclab.se/dashboard.js"></script>`

Essentially this means that the dashboard.js file is on the nginx machine, which it is not, therefore the 404. Maybe i should drop this and just host the custom dashboard along with a dashboard.js file on the nginx machine?

**Comment by ktsaou** [comment]
Cleaning up.
If an issue remains, just post here.
