### ISSUE TITLE
Changes since v1.8 (i.e. change log of netdata v1.9)

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2788]
The following are the changes since netdata release v1.8:

---

# Overview of netdata v1.9

1. **snapshots**
   We can now save and load dashboard snapshots for any timeframe in any resolution!

2. **highlighted time-frame**
   We can now highlight a selected time-frame on all dashboard charts!

3. **export to PDF**
   We can now export netdata dashboards to PDF, for any timeframe with any detail!

4. **access lists** (IP filtering)
   We can now setup IP filtering at `netdata.conf` for all functions of netdata (dashboard access, streaming, registry, badges, etc - no more iptables rules for protecting netdata).

5. **TCP overflows and connection drops**
   netdata can now detect TCP listening sockets overflows and connection drops, for any server running on the host (even the ones netdata is not aware of).

6. **libvirt VMs**
   netdata now detects **libvirt** network interfaces and moves them to VM section of the dashboard (it also supports `.libvirt-qemu` naming of cgroups).

7. **Units auto-scaling**
   netdata dashboards can now **scale units** (`KB` -> `MB` -> `GB` -> `TB`, etc), on the fly.

8. **Units conversions**
   netdata dashboards can now **convert units** (eg. Celsius to Fahrenheit, seconds to HH:MM:DD, etc), on the fly.

9. **Multiple Timezones**
   netdata dashboards can now **change timezone** on the fly (yes, we can now compare charts with server logs).

10. **python.d.plugin** rewritten
   @l2isbad rewrote the whole of it, to add flexibility and support the latest netdata features! The new plugin supports the old python modules.

11. **better / faster dashboard scrolling**
   netdata now uses passive event listeners to detect page scrolling. This improved significantly the responsiveness of the dashboard (check your dashboard settings: `sync` scrolling is the fastest, `async` is closer to the older behavior).

12. netdata now monitors **couchdb**, **powerdns**, **beanstalkd** and **dnsdist** !

13. netdata now detects **redis** background save failures

14. netdata can now send **flock.com** and **kavenegar.com** alarm notifications

and as always... dozens more improvements, enhancements, new features and bug fixes!

---

## netdata dashboard snapshots !

Netdata can now export and import dashboard **snapshots**.

Snapshots are JSON files containing everything the dashboard needs to be rendered: charts and chart data.

They are exported as JSON files, to your computer. The saved snapshots can be loaded back on any netdata dashboard (even of different host). When importing, not network traffic is generated. The web browser loads the local file and renders an interactive dashboard to examine it.

The current visible timeframe of the dashboard is respected, so first align the dashboard to the timeframe required and the click "Export". The pop-up allows selecting the resolution of the export (its detail).

![peek 2017-11-13 13-13](https://user-images.githubusercontent.com/2662304/32723039-a89d6d62-c874-11e7-9735-3f576b2b215c.gif)

---

## highlighted time-frame !

Press the ALT or CONTROL key and select a time-frame at a chart. An overlay will appear with the selected time-frame and all the charts will highlight the same region.

The highlighted time-frame:

1. Is added to the URL hash, so that reloading the page keeps it
2. Is propagated to other netdata servers, via the `my-netdata` menu
3. Is save in dashboard snapshots (and of course restored when they are loaded back)

![peek 2017-11-19 19-39](https://user-images.githubusercontent.com/2662304/32993483-78f8f148-cd61-11e7-9dbb-dab082ec231a.gif)

Also, netdata charts can now be zoomed vertically (use the SHIFT key, like in zoom, but select the chart vertically):

![peek 2017-11-19 20-10](https://user-images.githubusercontent.com/2662304/32993790-bf47b8d8-cd65-11e7-8f4a-c92d48e8a454.gif)

---

## netdata dashboards to PDF !

netdata dashboards can now be printed to PDF. Just click the :printer: icon on the dashboard.

The current visible timeframe of the dashboard is respected, so first align the dashboard to the timeframe required and the click "Print".

![peek 2017-11-11 19-55](https://user-images.githubusercontent.com/2662304/32692083-8db522de-c71a-11e7-8c17-7d731cdf0945.gif)

---

## netdata now supports API access lists (IP filtering)

netdata can now check the client IPs connecting to it and deny/allow access based on your settings. No more iptables rules to control access to netdata.

All these settings are [netdata simple patterns](https://github.com/firehol/netdata/wiki/Configuration#netdata-simple-patterns) that are checked against the client IP (string matching - not subnet matching). localhost clients (IPv4, IPv6 and unix domain sockets) can be matched with `localhost`:

#### Global access control

- `[web].allow connections from` to match the clients' IPs allowed to connect to netdata. This has the same effect with iptables (but implemented at the application level - so clients will get connected, and disconnected immediately if they are not allowed access, without any response from netdata).

#### Dashboard access control

- `netdata.conf`: `[web].allow dashboard from` to match the clients' IPs that are allowed to access the dashboard (ie fetch static files and query netdata API).
- `netdata.conf`: `[web].allow badges from` to match the clients' IPs that are allowed to access badges (the dashboard clients are allowed to access badges too, so this setting allows badges to clients that do not have access to the dashboard).

#### Streaming access control

- `netdata.conf`: `[web].allow streaming from` to match the the clients' IPs that are allowed to stream to stream metrics.
- `stream.conf`: `[API_KEY].allow from` to match the clients' IPs allowed to push metrics for the given API KEY.
- `stream.conf`: `[MACHINE_GUID].allow from` to match the clients' IPs allowed to push metrics for the specific machine.

netdata will also check the API keys supplied by slaves and proxies connected.

#### Other access lists

- `netdata.conf`: `[web].allow netdata.conf from` to limit the clients that can get `netdata.conf` - by default netdata allows only private IPs.
- `netdata.conf`: `[registry].allow from` to limit the clients allowed to access the registry (only when this netdata acts as a registry).

---

## netdata detects TCP listening sockets overflowing or dropping connections

Added a new chart: `ipv4.tcplistenissues` with dimensions `ListenOverflows` and `ListenDrops`.

> This chart detects if any listening TCP socket on the host, is overflown, or it drops connections. This is system-wide: any listening TCP socket, of any application.

The chart will not be shown if these kernel counters are zero. It will be enabled automatically if it is found non-zero at any point (it is collected via `/proc/net/netstat` every second). If you need to enable it even if it is zero, edit netdata.conf and set:

```
[plugin:proc:/proc/net/netstat]
	TCP listen issues = yes
```

Two alarms have been added, one for `ListenOverflows` and one for `ListenDrops` that detect if there is any overflow or drop in the last minute (they run every 10 seconds).

slack alarm for overflows:

![image](https://user-images.githubusercontent.com/2662304/31415368-b547d524-ae2b-11e7-895a-8b2f87b8ec81.png)

slack alarm for drops:

![image](https://user-images.githubusercontent.com/2662304/31415446-3980c13e-ae2c-11e7-9635-f1edfff7cc50.png)

and the alarms configuration:

![screenshot from 2017-10-09 23-04-05](https://user-images.githubusercontent.com/2662304/31356299-3e42ef12-ad46-11e7-9bf5-007ba57b3755.png)

The alarms will automatically be attached when the chart is active.

The overflows dimension and alarm is supported on FreeBSD too.

## `/proc/net/sockstat` and `/proc/net/sockstat6`

These files provide sockets statistics for all protocols.

![screenshot from 2017-11-07 02-39-37](https://user-images.githubusercontent.com/2662304/32471232-ebdb905a-c364-11e7-9d2f-a472de516315.png)

netdata also adds 3 new alarms:

1. too many tcp orphan sockets
2. tcp memory that detects that the tcp stack is under memory pressure or close to giving memory errors
3. too many tcp connections (for kernels that do not support dynamic allocation of connections)

---

## Streaming

- netdata proxies with more than 100 slaves, had a timing issue that caused them to crash randomly on slave reconnects. Parts of the code have been rewritten to get rid of the timing issue.

- netdata slaves and proxies, now have a protection that ensures they will never use 100% CPU, even if the master is misbehaving.

- expired orphaned hosts are now removed from the `my-netdata` menu of the dashboard.

- streaming functions can now be monitored via `access.log`

- streaming now support **IP filtering**. So the entire streaming functionality, API keys and MACHINE GUIDs can be associated with one or more IPs or IP patterns.

- streaming now transfers alarm variables too

---

## python.d.plugin rewritten

@l2isbad did a marvelous job rewriting `python.d.plugin`. The new plugin:

1. supports option `autodetection_retry: SECONDS`. When set to non-zero, the plugin will re-check the module every that many seconds. This solves the problem that netdata did not persist on collecting metrics from applications, if the application is not found running when netdata starts. By default is zero for all modules, so you need to enable it for all the applications you need it.

2. got a rewrite of several functions, like logging, module configuration, chart and dimensions management.

3. the new URL service disables by default certificates checks, to allow self-signed certificates to work without configuration.

The new plugin is compatible with custom python modules developed for the previous version.

---

## web_log plugin

- custom regex now supports parsing hostnames and IPs @l2isbad 

- web_log now parses lines with error 408 (request timeout - these are a special case, since the request has not received by the web server, so the log line is incomplete) @l2isbad 

- now properly parses `resp_length` with value `-` @racciari

---

## couchdb monitoring

CouchDB maintainer @wohali, submitted a couchdb plugin for netdata. The plugin monitors:

- database activity
- http response codes
- server operations
- per DB statistics

![mwsnap 2017-09-29 22_54_33](https://user-images.githubusercontent.com/112292/31041874-7463c37a-a56a-11e7-9d10-3ce969b983ea.png)
![mwsnap 2017-09-29 22_54_44](https://user-images.githubusercontent.com/112292/31041875-74651f40-a56a-11e7-9181-5771d1de9fef.png)

---

## redis monitoring

2 charts have been added to monitor background save health status, bundled with 2 alarms that detect if background save has failed, or background save is slow (warn > 10 mins, crit > 20min). @l2isbad 

![screenshot_20170925_092235](https://user-images.githubusercontent.com/22274335/30788234-ba213432-a1d3-11e7-8f94-a9452ed94e3d.png)

---

## Other new and enhanced plugins

- netdata now monitors [PowerDNS](https://www.powerdns.com/), @l2isbad 

- netdata now monitors [beanstalkd](http://kr.github.io/beanstalkd/), @l2isbad 

- netdata now monitors [dnsdist](https://dnsdist.org/), @nobody-nobody

- disks under Linux are renamed using `/dev/disk/by-label`. An option has been added at netdata.conf to also allow renaming based on `/dev/disk/by-id`.

- `chrony` is now disabled by default, because there have been reports that `chronyc` enters an infinite loop in CentOS and RHEL.

- `tomcat` improvements to support flavors of the tomcat server @Wing924

- `zfs` on FreeBSD now monitors ZFS TRIM statistics

- disks monitoring charts on FreeBSD got a lot more FreeBSD related dimensions.

- added CPU frequency charts on FreeBSD (Linux already had them).

- chart `system.io` (the total system Disk I/O) is now calculated by aggregating the reads and writes of all physical disks. The previous `system.io` chart (that is based on `pgpgin` and `pgpgout` from `/proc/vmstat`) is now named `system.pgpgio`. The key difference is that the new `system.io` now sees ZFS I/O, and it also correctly and accurately sums the real disk bandwidth of RAID arrays.

- chart `system.net` (the total system network bandwidth) is now calculated by aggregating the bandwidth of all physical network interfaces and is common for both IPv4 and IPv6.

- `tc` (QoS) charts now sort the dimensions on the legends, the same way `tc` reports them.

- `postgres` versions <= 10 the WAL directory was named `pg_xlog'` and from 10 upwards has been renamed to `pg_wal` @facetoe

- `mysql` (and mariadb) got new charts for galera replication @spinitron

- `openvpn_log` improvements @l2isbad

- `smartd` improvements @l2isbad

- `varnish` module has been rewritten @l2isbad

- `mdstat` regex fix @l2isbad

- `smartd_log` improvements @l2isbad

- `dns_query_time` improvements @wungad

- `isc_dhcpd` improvements @wungad

- `freeipmi.plugin` got a command line option (can be given at netdata.conf) to ignore certain sensor IDs that are faulty.

- `freeradius` improvements @wungad

- `node.d.plugin` bugfixes

## Plugins protocol enhancements

- netdata now supports multiple plugin directories. The setting is the same in `netdata.conf`, `plugins directory = "DIRECTORY1" "DIRECTORY2" ...`, up to 20 directories. By default netdata sets:

```
[global]
      plugins directory = "/usr/libexec/netdata/plugins.d" "/etc/netdata/custom-plugins.d"
```

- netdata now supports **alarms variables**.

   Each plugin can now define **host global** and **chart local** variables with static values, that can be used in alarms' expressions. So, hosts and charts can now have any number of static values associated with them (eg. an application server may expose its max connections limit), and these static values can be used to trigger alarms (eg. the current connections, is compared to the max connections variable). The whole setup allows alarm templates to use this feature (eg each netdata can maintain different such variables for each server it monitors).

   Alarm variables are propagated to upstream netdata servers.

---

## O/S - distro support

- added init file for SLC 6.9 and CloudLinux Server release 6.9

- packages installer was incorrectly detecting all python versions as version 2.

- a `makeself` bug that prevented the static netdata binaries from being installed on `busybox` systems, has been fixed.

- openrc startup script (gentoo, alpine) had hardcoded the path to netdata. This affected all static-64bit builds when installed on these distros. Fixed.

- the static 64bit installer now downloads netdata.conf, much like the git installer does.

- openrc / gentoo init improvements @candrews

- enabled support for macOS versions 10.5+ (10.11 was working already) @vlvkobal 

- enabled support for FreeBSD 12 @vlvkobal 

- fixed a crash on macOS hosts with empty disk names.

- added `Dockerfile.armv7hf` for running netdata under docker on ARM v7 machines @justin8

---

## Dashboard improvements

- hover selection of charts is now faster on all browsers. Perfect on Chrome, Firefox and Opera. Quite usable on Edge.

- the dashboard is now fixed when a modal is open, preventing scrolling the page.

- the dashboard now uses fontawesome 5.0.1 for icons.

- the chart names can now be searched with browser control-F (find in page). netdata lazy loads all charts for it was impossible to search of a chart. Now the charts are searchable. This is important on dashboards with several hundreds of statsd charts, because all these charts appear under the same section.

- netdata now detects **libvirt** VM network interfaces and moves them to the VM section of the dashboard. The same functionality already exists for containers.

   ![screenshot from 2017-10-31 01-32-43](https://user-images.githubusercontent.com/2662304/32200665-7c2b2d1c-bddb-11e7-98a8-c027578b2b0a.png)

- Show the context of each chart. The `context` is used in alarm templates. (hover on the date of the chart)

   ![image](https://user-images.githubusercontent.com/2662304/31103168-529d9a1a-a7de-11e7-8257-5f08d93083ba.png)

- Show the resolution of the chart. (hover on the time of the chart)

   ![image](https://user-images.githubusercontent.com/2662304/31103223-7deaeaec-a7de-11e7-8470-f62191ec9303.png)

- The dashboard now adds a tooltip at the date of the charts, to show the plugin and its module that collects each chart.

- The dashboard should now put a lot less CPU pressure on the browser when the page does not have focus.

#### automatic units scaling

The dashboard does dynamic units scaling, **on the fly** ! It converts:

- network bandwidth (`kilobits/s` to `megabits/s` or `gigabits/s`)
- input/output bandwidth (`kilobytes/s` to `megabytes/s` or `gigabytes/s`, similarly for `KB/s`)
- memory sizes (`MB` to `KB`, `GB` or `TB`)
- disk sizes (`GB` to `MB` or `TB`)

Chart units dynamically adapt based on the value of the selected dimension too:

![peek 2017-10-06 22-58](https://user-images.githubusercontent.com/2662304/31296227-309a4c06-aaea-11e7-8c7b-3bca6a954372.gif)

Custom dashboards can give `data-desired-units="UNITS"` and netdata will automatically convert the presented values to the desired units. `UNITS` can be any of the supported one, or `auto` for auto-scaling based on the values, or `original` to show the original units maintained by the netdata server.

#### units conversions

The dashboard now supports units conversions. Currently it converts:

temperatures from `Celsius` to `Fahrenheit`

![image](https://user-images.githubusercontent.com/2662304/31411328-ef7558a0-ae19-11e7-9905-dbb95b261d12.png)

`seconds` to human readable duration `DDd:HH:MM:SS`

![image](https://user-images.githubusercontent.com/2662304/31411264-c1e68454-ae19-11e7-9870-2bd633443545.png)

#### timezone conversions

netdata can now convert all dates presented to any timezone. Traditionally netdata presented all charts at the timezone of the viewer. This allowed homogeneous central administration of systems that are installed all over the world. However, this was inefficient when we needed to compare the information presented on the dashboard, with the log files of the servers.

So, now netdata can present the charts on any timezone. The netdata server auto-detects the timezone of the server and new dashboard settings have been added to allow this conversion.

If autodetection of the servers timezone fails, the configuration option `[global].timezone` has been added in `netdata.conf` to set it. Also, the dashboard itself allows the viewers to configure the timezone (it is saved at browser local storage, so this has to be set just once per viewer).

#### new dashboard options

To support all the above, the dashboard settings got a new tab, with all the required options:

![screenshot from 2017-10-10 23-54-01](https://user-images.githubusercontent.com/2662304/31409982-587d96f4-ae16-11e7-8cab-7b66d6b0eb6e.png)

---

## statsd improvements

- statsd metrics can now be added to statsd synthetic charts using patterns. No need to add a `dimension` line for each statsd metric to be added. netdata will also extract the wildcarded part of the metric name and use that one for the dimension name.

- dimensions added to statsd synthetic charts, can automatically be renamed using a dictionary. Each synthetic charts application has its own dictionary of name - value pairs, which is used to automatically rename statsd metrics when they are added to synthetic charts.

- statsd timers and histograms now report zeros when nothing is collected

---

## Badges improvements

- fixed a bug in netdata badges that was incorrectly matching zero values with the `null` color condition.

- added API option `display_absolute` to allow badges use the signed value for color evaluation, but present the absolute value.

---

## Other Alarm and Alarm Notifications Improvements

- warning emails sent by netdata, are now a little bit more orange (they were a bit green'sh).

- added flock.com notifications @tvarsis

- added kavenegar.com support for SMS notifications @vahit

- fixed a bug in email notifications that was triggering a corrupted MIME match by anti-spam solutions.

- pushbullet notifications now track the devices, so that per device filtering at pushbullet is possible. Also improved the formatting a bit. @user501254

- pushover notifications fixes (the priority of warnings was set incorrectly)

- alarms can now use variables like this `${variable with spaces or +, -, *, / in it}`. So, alarms can now use dimension names with any character in them.

---

## Other Improvements

- `access.log` has been refactored to support monitoring all netdata operations

- inodes monitoring is now by default disabled for mount points based on filesystems that do not have a maximum inode threshold (such as `cephfs`).

- `rabbitmq` has been added to `apps_groups.conf` so that `apps.plugin` now monitors (cpu, memory, disk I/O, sockets, etc) for rabbitmq instances.

- several email and log management apps have been added to `email` and `logs` targets of `apps_groups.conf`, @Flums

- `ceph` target added to `apps_groups.conf` to allow netdata monitor  [Ceph](//ceph.com/) - the unified, distributed storage system, @k0ste

- refactored several internal data collection plugins to eliminate a few hundreds of index lookups per second.

- `netdata.conf` settings that are loaded from disk, but were the same with the default ones, were generated commented when the server was asked to give its config. Now all loaded settings are generated uncommented.

- netdata simple patterns can now extract the the wildcarded part of the string they match (used in statsd synthetic charts)

- netdata simple patterns can allow escaping spaces by prefixing them with a backslash.

**Comment by LeeNX** [comment]
Might not be a right place to ask, but should we not be thinking of a v1.8.1 with the new python plugin, just to keep the versions a little cleaner?

**Comment by ktsaou** [comment]
updated infographic.

![netdata-overview](https://user-images.githubusercontent.com/2662304/32356021-19baa4a2-c03b-11e7-981a-b3b6ec30d5b7.png)

**Comment by akki8400** [comment]
hi,
Actually i want to know that does netdata creates the logs for each graphical analysis.

**Comment by akki8400** [comment]
hi,
can i increase the history  statistics time in graphs.

**Comment by ktsaou** [comment]
> can i increase the history statistics time in graphs.

Yes, edit `netdata.conf` and set `history` as you need. Read also the memory requirement wiki page.

Please open a new issue if you have more questions.

**Comment by ktsaou** [comment]
@l2isbad I think we should release netdata v1.9.0 this weekend.
What do you think?
For sure, this is a huge release. Way too many changes, improvements, enhancements and features!

**Comment by l2isbad** [comment]
@ktsaou 
agree 👍

**Comment by ktsaou** [comment]
v1.9.0 released!
