### ISSUE TITLE
netdata compile install

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#2793]
Hi,   
    I compile and install netdata, the use of --sysconfdir=/opt /config/netdata, the installation process is not being given, but after loading in the /opt/config/netdata directory can not find netdata.conf .

**Comment by ktsaou** [comment]
Could you please post the error you see?

**Comment by FANGXIANGQUAN** [comment]
thanks, I have solved this problem, because I did not have to download the configuration file!
