### ISSUE TITLE
netdata should be installed in /usr/sbin?

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#28]
@alonbl I think netdata should be installed `/usr/sbin`, not `/usr/bin`.
I am not sure though. netdata is a system daemon. Its place should be in `sbin` somehow.
Right?

**Comment by alonbl** [comment]
I only followed what was in previous mode, BIN_DIR... you can modify bin_ to sbin_ in Makefile.am, quite simple to customize now... :)

**Comment by ktsaou** [comment]
ok, please do so. Thanks!

**Comment by alonbl** [comment]
will do, however, you do not need me for these minor changes.

**Comment by ktsaou** [comment]
you are so right! I don't have clue how to do it though. I'll talk with @philwhineray from now on.

Again, thank you very much for your help so far.

**Comment by alonbl** [comment]
it is very simple, read some about automake and see that it is much simpler than what you already know.
I will be glad to assist.

**Comment by ktsaou** [comment]
ok. I'll do. Thanks!
