### ISSUE TITLE
Permission denied accessing /proc and /sys (Debian 7 and 8)

### ISSUE THREAD

**Issue by sherl0k** [firehol/netdata#280]
I had an earlier build of netdata installed on both a debian 7 and debian 8 install and decided to upgrade today. I've since lost some graphs, namely around networking and disk. The error log is showing the following:

```
16-04-19 15:38:56: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' called DISABLE. Disabling it.
16-04-19 15:38:56: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' on pid 3119 stopped.
16-04-19 15:38:56: ERROR: netdata: pid 3119 exited with code 143.
16-04-19 15:38:56: ERROR: netdata: PROCFILE: Cannot open file '/sys/kernel/mm/ksm/pages_shared' (errno 13, Permission denied)
16-04-19 15:38:56: ERROR: netdata: PROCFILE: Cannot open file '/sys/kernel/mm/ksm/pages_sharing' (errno 13, Permission denied)
16-04-19 15:38:56: ERROR: netdata: PROCFILE: Cannot open file '/sys/kernel/mm/ksm/pages_unshared' (errno 13, Permission denied)
16-04-19 15:38:56: ERROR: netdata: PROCFILE: Cannot open file '/sys/kernel/mm/ksm/pages_volatile' (errno 13, Permission denied)
16-04-19 15:38:56: ERROR: netdata: PROCFILE: Cannot open file '/sys/kernel/mm/ksm/pages_to_scan' (errno 13, Permission denied)
16-04-19 15:38:56: ERROR: apps.plugin: pid 3108 netdata states parent 1, but the later does not exist.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.cpu/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.mem/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.threads/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.processes/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.cpu_user/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.cpu_system/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.major_faults/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.minor_faults/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.lreads/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.lwrites/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.preads/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.pwrites/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.files/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.sockets/root.db.
16-04-19 15:38:57: INFO: netdata: Initializing file /var/cache/netdata/users.pipes/root.db.
16-04-19 15:38:57: ERROR: netdata: Cannot read sector size for device sda from /sys/block/sda/queue/hw_sector_size. Assuming 512. (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: Cannot read sector size for device sdb from /sys/block/sdb/queue/hw_sector_size. Assuming 512. (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/snmp' (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/snmp6' (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/netstat' (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/stat/nf_conntrack' (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 13, Permission denied)
16-04-19 15:38:57: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/rpc/nfsd' (errno 13, Permission denied)
```

I'm wary to run netdata as root, is there a workaround for this? I can provide more information as needed.

**Comment by ktsaou** [comment]
Can you `ls -l` these files?

**Comment by sherl0k** [comment]
They all appear to be owned by root, 444 perms. couple examples:

```
# ls -l /sys/block/sda/queue/hw_sector_size
-r--r--r-- 1 root root 4096 Apr 19 15:48 /sys/block/sda/queue/hw_sector_size

t# ls -l /proc/net/netstat 
-r--r--r-- 1 root root 0 Apr 19 15:50 /proc/net/netstat
```

**Comment by ktsaou** [comment]
Well, there is no reason to fail reading them.

Questions that might help find out a solution:

1. Do you use apparmor, selinux or something similar?
2. Have you re-installed (re-compiled) netdata after updating your system? You should...
3. What user netdata runs as? The default is `netdata`. Did you change it?

**Comment by sherl0k** [comment]
1. selinux is disabled (`/selinux/enforce` is set to zero)
2. The OS hasn't been touched. I simply upgraded netdata from a previous build - ran `git pull` inside the netdata, followed by `./netdata-install.sh`
3. netdata is running as the `netdata` user, that has not changed.

**Comment by ktsaou** [comment]
ok.

Please do this:

```sh
sudo su -c 'cat /proc/net/snmp' netdata
```

Does it work?

**Comment by sherl0k** [comment]
the `netdata` user doesn't have a valid shell per `/etc/passwd` (set to `/sbin/nologin` which does not exist on debian systems, it's actually `/usr/sbin/nologin`) but setting it to `/bin/bash` and running, i get permission denied.

```
# sudo su -c 'cat /proc/net/snmp' netdata
cat: /proc/net/snmp: Permission denied
```

FWIW, I tested a clean install on a Fedora 23 VM and it worked without issue. I also upgraded a CentOS6 netdata instance and did not see this, either. I don't have a clean Debian install handy to test with, only these two I've already upgraded. I tried to uninstall and reinstall also, that did not work on the Debian instances.

**Comment by ktsaou** [comment]
By the way, I just installed a debian 8.3 and I don't have this issue either.
Do you have any complains in the system log (`/var/log/messages`, `/var/log/kern.log`, etc)?

**Comment by ktsaou** [comment]
Are you starting netdata with systemd? Can you try to start it as root by hand?

**Comment by sherl0k** [comment]
I think you're onto something here, @ktsaou . I was indeed using the systemd script. If I run it by hand, I don't have the issue.

**Comment by ktsaou** [comment]
Then it must be something with systemd configuration. I just started mine on debian with systemd and it works...

**Comment by ktsaou** [comment]
Using the default systemd file found in `netdata.git/system/netdata.service`

**Comment by sherl0k** [comment]
Yeah, I'm unsure what's happening. screams of something specific on my end. I'll keep digging. thanks for the help!

**Comment by glensc** [comment]
btw, generally just `ls -l /proc/net/snmp` to diagnose permission problem is not enough. should do `ls -ld` for **each** parent dir component as well, and run the command as **target** user, and in special filesystems like `/proc` or `/sys`, do not trust permissions, try opening the files.

so:
https://github.com/firehol/netdata/issues/280#issuecomment-212097619

should had asked instead:
```
sudo -H -u netdata ls -ld /proc/net/snmp
sudo -H -u netdata ls -ld /proc/net
sudo -H -u netdata ls -ld /proc
sudo -H -u netdata file /proc/net/snmp
```

**Comment by deveth0** [comment]
Hi,
i'm running netdata on a debian through systemd (also tested manually) and get the same issue with another path:
````
root@proxmox:/etc/netdata# sudo -H -u netdata ls -ld /proc/net/snmp /run/lxcfs/controllers/blkio/lxc/112/blkio.io_serviced
ls: cannot access /run/lxcfs/controllers/blkio/lxc/112/blkio.io_serviced: Permission denied
-r--r--r-- 1 root root 0 May 14 17:57 /proc/net/snmp
````

neither kern.log nor messages show anything interesting here :(
