### ISSUE TITLE
FreeBSD cpu frequency

### ISSUE THREAD

**Issue by hoopty** [firehol/netdata#2816]
Hello, I'd like to ask to have the current cpu speed (frequency) added to the metrics that are monitored & reported in the FreeBSD sysctl driver.  

Here's how you get the frequency on supported systems, and keep in mind that all cores operate at the same frequency.

```
#sudo sysctl -n dev.cpu.0.freq
3601
```

Thanks!

**Comment by ktsaou** [comment]
nice!

@vlvkobal check this.

**Comment by vlvkobal** [comment]
@hoopty Please update `netdata`. CPU frequency chart was implemented in #2856
