### ISSUE TITLE
1.8.0 missing ipv4 but shows ipv6

### ISSUE THREAD

**Issue by xuefer** [firehol/netdata#2819]
git rev: 89ed309252981ddd50f697fde4fe93019cb3e652
```
# uname -a
Linux Router-2408 4.9.50 #0 SMP Thu Sep 21 02:51:15 2017 x86_64 GNU/Linux
```

```
# cat /proc/net/snmp
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails FragOKs FragFails FragCreates
Ip: 1 64 160286144 177 0 39292144 0 0 115873932 157033887 13 4113 4948 9146077 4566242 4951 191 0 382
Icmp: InMsgs InErrors InCsumErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 5674754 3403 0 281663 6424 71 0 7 181205 5205384 0 0 0 0 5682192 0 157208 2472 0 0 0 5341307 181205 0 0 0 0
IcmpMsg: InType0 InType3 InType5 InType8 InType11 InType12 OutType0 OutType3 OutType8 OutType11
IcmpMsg: 5205384 281663 7 181205 6424 71 181205 157208 5341307 2472
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 253932 36631 33783 13640 47 37095478 61626110 5429050 1933 23161 36
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 73060789 9773 64 72493244 0 0 64 69229
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
UdpLite: 0 0 0 0 0 0 0 0
```
netdata shows ipv6 but can't show ipv4

**Comment by Xoib** [comment]
Interesting, for me it's exactly the opposite since, showing ipv4 stuff but not the ipv6.

```
# uname -a
Linux ns373245.ip-178-33-232.eu 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /proc/net/snmp
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails FragOKs FragFails FragCreates
Ip: 2 64 39493852 0 0 0 0 0 39310778 38306439 123 40 25 427 201 25 0 0 0
Icmp: InMsgs InErrors InCsumErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 1995571 300 0 4266 45 0 0 1 1991214 41 4 0 0 0 2050586 0 59357 4 0 0 0 7 1991214 0 4 0 0
IcmpMsg: InType0 InType3 InType5 InType8 InType11 InType13 OutType0 OutType3 OutType8 OutType11 OutType14
IcmpMsg: 41 4266 1 1991214 45 4 1991214 59357 7 4 4
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 544449 308519 3928 36860 6 36069017 196889447 356286 560 1341724 28
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors
Udp: 1477797 3866 0 2202670 0 0 0
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors
UdpLite: 0 0 0 0 0 0 0
```

**Comment by ktsaou** [comment]
@xuefer if want to enable the chart, although it is useless, edit `netdata.conf` and set:

```
[plugin:proc:/proc/net/netstat]
	bandwidth = yes
```

The default value is `auto`, which means: yes, if it is not zero.

---

@Xoib for `system.ipv6` do the same, on this section:

```
[plugin:proc:/proc/net/snmp6]
	bandwidth = yes
```

**Comment by xuefer** [comment]
now you mention it this is bogus. i just fixed my configuration. didn't know where to look

**Comment by ktsaou** [comment]
What did you fix? Post it here for others having similar issues to fix them too.

**Comment by xuefer** [comment]
sure. it was long time ago i forgot. as i see the netdata.conf file searching for snmp, i remember that i had it disabled in by setting it to "no", along with other few settings
why i disabled it: i ran netdata on router, maybe because the older kernel was slow on accessing these paths and i didn't want to waste cpu cycles having netdata to read it. it seems the new kernel isn't slow. (or should i double re-check it)

as far as i can remember, some old monitor app wanted to (or has to) read the whole tcp connection list which is extremely slow for a host with thousands of connections.

if netdata know which stats path is slow, it should disable that by default and let user to decide. for users like me don't have to worry about this.

**Comment by ktsaou** [comment]
> if netdata know which stats path is slow

The files netdata reads are aggregated (by the kernel counters). It does not read all the connections of the system (although there are a few request for that).

So, the number of connections the kernel has, have no impact on the cpu utilization of netdata.

If want to save cycles, disable external plugins. `apps.plugin` for example is twice as "heavy" compared to netdata.

**Comment by Xoib** [comment]
I understand why it doesn't work : 

```
root@box:/var/log/netdata# grep -i netstat error.log
2017-10-08 11:17:35: netdata ERROR: PROCFILE: Cannot open file '/proc/net/netstat' (errno 13, Permission denied)
root@box:/var/log/netdata# grep -i snmp6 error.log
2017-10-08 11:17:35: netdata ERROR: PROCFILE: Cannot open file '/proc/net/snmp6' (errno 13, Permission denied)
root@box:/var/log/netdata# systemctl status netdata -l
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: active (running) since dim. 2017-10-08 11:17:35 CEST; 4min 8s ago
 Main PID: 11730 (netdata)
   CGroup: /system.slice/netdata.service
           ├─11730 /usr/sbin/netdata -P /run/netdata/netdata.pid -D
           ├─11740 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─11747 /usr/libexec/netdata/plugins.d/apps.plugin 1
           └─11751 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1

oct. 08 11:17:35 ns373245.ip-178-33-232.eu systemd[1]: Started Real time performance monitoring.
```

netdata don't have the right on a lot of path, search for "errno 13" on error.log and you will see.

**Comment by ktsaou** [comment]
Are you running grsec?

These files are world readable:

```sh
# ls -l /proc/net/netstat 
-r--r--r-- 1 root root 0 Οκτ   8 13:00 /proc/net/netstat

# ls -l /proc/net/snmp6
-r--r--r-- 1 root root 0 Οκτ   8 13:00 /proc/net/snmp6
```

**Comment by Xoib** [comment]
I do, but I have the same output : 

```
ls -l /proc/net/netstat
-r--r--r-- 1 root root 0 oct.   9 20:18 /proc/net/netstat

ls -l /proc/net/snmp6
-r--r--r-- 1 root root 0 oct.   9 20:18 /proc/net/snmp6
```

**Comment by ktsaou** [comment]
I think grsec does several things differently regarding /proc, independently of filesystem permission. However, I don't know much about it. If you search the issues, there have been quite a few issues with it so far. You have 2 alternatives:

1. run netdata as `root`
2. configure grsec to allow group `netdata` access the files (I think grsec allows one and only one group to access `/proc` files - either set this group in grsec to `netdata`, or run netdata with group that has access).

**Comment by mamema** [comment]
even though this is an old issue, i'm currently struggeling with it.
I'm running netdata in docker and the host has ipv6 disabled, but netda shows ipv6 traffic and NO ipv4 traffic
the running netdata.conf shows:
# section 'system.ipv4' is not used.

/ # cat /proc/net/netstat
TcpExt: SyncookiesSent SyncookiesRecv SyncookiesFailed EmbryonicRsts PruneCalled RcvPruned OfoPruned OutOf
WindowIcmps LockDroppedIcmps ArpFilter TW TWRecycled TWKilled PAWSPassive PAWSActive PAWSEstab DelayedACKs
 DelayedACKLocked DelayedACKLost ListenOverflows ListenDrops TCPPrequeued TCPDirectCopyFromBacklog TCPDire
ctCopyFromPrequeue TCPPrequeueDropped TCPHPHits TCPHPHitsToUser TCPPureAcks TCPHPAcks TCPRenoRecovery TCPS
ackRecovery TCPSACKReneging TCPFACKReorder TCPSACKReorder TCPRenoReorder TCPTSReorder TCPFullUndo TCPParti
alUndo TCPDSACKUndo TCPLossUndo TCPLostRetransmit TCPRenoFailures TCPSackFailures TCPLossFailures TCPFastR
etrans TCPForwardRetrans TCPSlowStartRetrans TCPTimeouts TCPLossProbes TCPLossProbeRecovery TCPRenoRecover
yFail TCPSackRecoveryFail TCPSchedulerFailed TCPRcvCollapsed TCPDSACKOldSent TCPDSACKOfoSent TCPDSACKRecv
TCPDSACKOfoRecv TCPAbortOnData TCPAbortOnClose TCPAbortOnMemory TCPAbortOnTimeout TCPAbortOnLinger TCPAbor
tFailed TCPMemoryPressures TCPSACKDiscard TCPDSACKIgnoredOld TCPDSACKIgnoredNoUndo TCPSpuriousRTOs TCPMD5N
otFound TCPMD5Unexpected TCPSackShifted TCPSackMerged TCPSackShiftFallback TCPBacklogDrop TCPMinTTLDrop TC
PDeferAcceptDrop IPReversePathFilter TCPTimeWaitOverflow TCPReqQFullDoCookies TCPReqQFullDrop TCPRetransFa
il TCPRcvCoalesce TCPOFOQueue TCPOFODrop TCPOFOMerge TCPChallengeACK TCPSYNChallenge TCPFastOpenActive TCP
FastOpenActiveFail TCPFastOpenPassive TCPFastOpenPassiveFail TCPFastOpenListenOverflow TCPFastOpenCookieRe
qd TCPSpuriousRtxHostQueues BusyPollRxPackets TCPAutoCorking TCPFromZeroWindowAdv TCPToZeroWindowAdv TCPWa
ntZeroWindowAdv TCPSynRetrans TCPOrigDataSent TCPHystartTrainDetect TCPHystartTrainCwnd TCPHystartDelayDet
ect TCPHystartDelayCwnd TCPACKSkippedSynRecv TCPACKSkippedPAWS TCPACKSkippedSeq TCPACKSkippedFinWait2 TCPA
CKSkippedTimeWait TCPACKSkippedChallenge TCPWinProbe TCPKeepAlive TCPMTUPFail TCPMTUPSuccess
TcpExt: 0 0 0 1220 0 0 0 16 0 0 1313721 0 0 0 0 0 298790 138 476 66144 66146 914688 78776 133495724 0 2088
6365 717650 6626467 5113909 0 112 0 3 5 0 3 30 23 34 256 1 0 0 0 440 30 394 32071 2103 6 0 0 18 0 483 1 16
37 0 34655 172 0 256 0 0 0 18 1 219 0 0 0 6935 1089 3467 1 0 0 0 0 0 0 1 222869 1047 0 1 198 73 0 0 0 0 0
0 4562 0 408091 43 43 37 30787 17705661 716 15724 6 626 34 0 18 0 0 0 2178 17254 0 0
IpExt: InNoRoutes InTruncatedPkts InMcastPkts OutMcastPkts InBcastPkts OutBcastPkts InOctets OutOctets InM
castOctets OutMcastOctets InBcastOctets OutBcastOctets InCsumErrors InNoECTPkts InECT1Pkts InECT0Pkts InCE
Pkts
IpExt: 0 0 345709 361452 244683 168275 379746008700 623304966014 99712738 92675284 14503878 8998596 0 3159
41817 0 15958 0

i cannot understand why ipv4 traffic isn't shown and ipv6 is.....
