### ISSUE TITLE
Shell arithmetic expansion

### ISSUE THREAD

**Issue by fredericopissarra** [firehol/netdata#282]
Both bash and sh documentation (Linux) says that $[expression] is an old syntax. They prefeer $((expression)). bash manpage says:

"The old format $[expression] is deprecated and will be removed in upcoming versions of bash."

sh manpage shows only $((expression)) syntax, not $[expression].

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
I guess then I have a lot of work:

- here: https://github.com/firehol/firehol/blob/master/sbin/firehol.in
- here: https://github.com/firehol/firehol/blob/master/sbin/fireqos.in
- here: https://github.com/firehol/firehol/blob/master/sbin/link-balancer.in
- and here: https://github.com/firehol/firehol/blob/master/sbin/update-ipsets.in

:)

**Comment by glensc** [comment]
`$[]` is not only old, but not present in posix, and thus not all shells support it:

```
$ mksh -c 'echo $[1+1]; echo $((1+1));'
$[1+1]
2
```
