### ISSUE TITLE
Beanstalk monitoring

### ISSUE THREAD

**Issue by edwade3** [firehol/netdata#2820]
I was looking for a beanstalk monitor to use with netdata but couldn't find one and spoke to you guys on twitter and you weren't aware of one so I've put one together. It's rough and is all configured from within the chart.py file at the moment but it works. It creates a dimension with tubename_stat and then assigns the value to that.

Happy for someone to tear it apart or adapt it!
[beanstalk.chart.txt](https://github.com/firehol/netdata/files/1346426/beanstalk.chart.txt)

**Comment by ktsaou** [comment]
Thanks!
@l2isbad have a look at this. If it is not too hard, please turn this into a netdata plugin.

**Comment by edwade3** [comment]
No problem! Hopefully it's a good enough start for someone to build on to!

**Comment by edwade3** [comment]
I created a pull request where the config file is present and used within the code so hopefully it's OK! https://github.com/firehol/netdata/pull/2831
