### ISSUE TITLE
Warning E-mail banner is green-ish

### ISSUE THREAD

**Issue by candlerb** [firehol/netdata#2823]
The banner colour for `severity: warning` E-mails is a sort of greenish-yellow.  It's not immediately obvious (to me) whether it's a warning or a return to normal state.

The colour is `#caca4b`

![image](https://user-images.githubusercontent.com/44789/31055028-204adc7e-a673-11e7-89b6-10d8b57f8762.png)

I suggest that something like `#ffc107`, which is more obviously amber, would be better.

![image](https://user-images.githubusercontent.com/44789/31055023-0cbb6dd6-a673-11e7-9125-9d9153fa831e.png)

**Comment by ktsaou** [comment]
thanks! did that.
