### ISSUE TITLE
multiple streaming connections for the same host detected.

### ISSUE THREAD

**Issue by RiceBowlJr** [firehol/netdata#2827]
Hi there,

I work on AWS, so I have multiple instances behind a load balancer. Those pop automatically depending on traffic on the application served by those instances.
The process of poping an instance is the following:
- I created an image (AMI) with all I want on it (my application and NetData, with stream conf (slave) for NetData)
- I use this same image for all my instances, so each time an instance need to be set, I use this image, and only set the hostname dynamically via AWS API so my instances each have a unique name (like for example `myapp-front-<aws-ec2-id>`, `aws-ec2-id` is unique ID set by AWS to identify instances)

But, for a reason I'm not sure about, the master thinks that the data coming from those instances come from the same instance, I can see the message in the logs:

```
2017-10-02 08:52:06: netdata INFO : STREAM ****host_anonymised***** [receive from [*****IP_anonymised******]:33986]: multiple streaming connections for the same host detected. If multiple netdata │ * Documentation:  https://help.ubuntu.com/
are pushing metrics for the same charts, at the same time, the result is unexpected.
```

But when I try to install and configure Netdata at the moment I start the instances (so not installed and configured in my AMI image), I got it working like a charm. So I think that NetData is putting some ID in the configuration at isntallation, that compromises the way I handle this.

May it be possible to make it work the way I want (with NetData pre-installed on an image that I boot on)? It will be very helpful for my instances to boot (and bootstrap) properly, with no possible fail at bootstrap (doing it my way, I just set the hostname at bootstrap, everything else is done in the image).

Here is my stream conf:

Master:
```
[<my-api-key-anonymised>]
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
```
Slave:
```
[stream]
    enabled = yes
    destination = master-hostname:19999
    api key = <my-api-key-anonymised>
    timeout seconds = 60
    default port = 19999
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
```

Thanks.

**Comment by ktsaou** [comment]
Hi,

On your image you should delete `/var/lib/netdata/registry/netdata.unique.id`.
This file has a GUID that uniquely identifies each netdata. If the file is not there, a new GUID is generated. So, just delete that file on your image, so that all new VMs based on this image (netdata slaves), will generate their own.

**Comment by RiceBowlJr** [comment]
Thanks a lot! It works like a charm with that.

**Comment by ktsaou** [comment]
Added this note at the wiki: https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes#netdata-unique-id
