### ISSUE TITLE
Get postgres max_connections settings in health.d alarm template

### ISSUE THREAD

**Issue by dennislaumen** [firehol/netdata#2829]
Hi all!

First off, compliments on the awesome project! 👏

I have some questions regarding writing custom alarms. I created the following, really simple alarm for checking the number of Postgres connections. Naturally, I'd like to check for a percentage in relation to the max_connections configured in Postgres (200 in this example). I hardcoded it here, and this works, but it'd be way nicer if I could get this from Postgres itself of course. Is this possible?

```
template: postgres_max_connections
      on: postgres.db_stat_connections
    calc: ($connections / 200) * 100
   every: 1m
    warn: $this > 80
    crit: $this > 95
```

Furthermore, I was wondering whether I can find a list somewhere for the values I can use in "on". I guessed this based one some other values I saw used in health.d but I'm guessing (hoping 😉) I can find these values somewhere else (or maybe there's a "formula" to use with which I can deduct them).

Thanks in advance and keep up the good work!

**Comment by ktsaou** [comment]
I have rendered the context with PR #2833 .

Although this is not intuitive, you can find all the variables available using:

```
http://your.netdata.ip:19999/api/v1/alarm_variables?chart=system.cpu
```

Of course replace `system.cpu` with the chart you are interested. This shows also the `context`.

There are 3 sets of variables:

- chart variables (i.e. variables local the chart)
- family variables (i.e. variables local to all the charts that have the same family with the one in question)
- host variables (i.e. every single variable netdata has for this host)

The number of variables is just too big... so just search for what you are looking.

**Comment by ktsaou** [comment]
Regarding the max connections from postgres:

unfortunately plugins cannot define variables yet. We have to extend the protocol a bit to allow this to happen. There is issue #2688 exactly for that.

The only way today for plugins to push variables to netdata, is to define a metric (a chart dimension) with the value they want. This wastes some memory, but it is the only way today.

**Comment by dennislaumen** [comment]
Thanks @ktsaou! Everything's clear now. I'll leave the max_connections hardcoded for now.
