### ISSUE TITLE
Disk missing from netdata

### ISSUE THREAD

**Issue by cobrafast** [firehol/netdata#2830]
I performed a firmware update on `/dev/sdg` (and as a result the drive was disconnected until reboot) and now the drive is missing from netdata even after reboot.  
The drive is completely fine otherwise; it shows up in `/proc/diskstats`:

       8      96 sdg 147 0 12945 11100 331871 256333 302059872 47834206 0 810120 47845223

Netdata v1.8.0.

What's going wrong?

**Comment by ktsaou** [comment]
Are you sure it is not on your dashboard?
fetch `http://your.netdata.ip:19999/api/v1/charts` and search on this page for `sdg`. Did you find it? Can you post here your findings?

**Comment by cobrafast** [comment]
Yes, it shows up in there:

		...
		"disk_qops.sdg": 		{
			"id": "disk_qops.sdg",
			"name": "disk_qops.sdg",
			"type": "disk_qops",
			"family": "/mnt/8tr",
			"context": "disk.qops",
			"title": "Disk Current I/O Operations (disk_qops.sdg)",
			"priority": 2002,
			"enabled": true,
			"units": "operations",
			"data_url": "/api/v1/data?chart=disk_qops.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506961506,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"operations": { "name": "operations" }
			},
			"green": null,
			"red": null
		},
		...
		"disk_svctm.sdg": 		{
			"id": "disk_svctm.sdg",
			"name": "disk_svctm.sdg",
			"type": "disk_svctm",
			"family": "/mnt/8tr",
			"context": "disk.svctm",
			"title": "Average Service Time (disk_svctm.sdg)",
			"priority": 2007,
			"enabled": true,
			"units": "ms per operation",
			"data_url": "/api/v1/data?chart=disk_svctm.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"svctm": { "name": "svctm" }
			},
			"green": null,
			"red": null
		},
		"disk_avgsz.sdg": 		{
			"id": "disk_avgsz.sdg",
			"name": "disk_avgsz.sdg",
			"type": "disk_avgsz",
			"family": "/mnt/8tr",
			"context": "disk.avgsz",
			"title": "Average Completed I/O Operation Bandwidth (disk_avgsz.sdg)",
			"priority": 2006,
			"enabled": true,
			"units": "kilobytes per operation",
			"data_url": "/api/v1/data?chart=disk_avgsz.sdg",
			"chart_type": "area",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		"disk_await.sdg": 		{
			"id": "disk_await.sdg",
			"name": "disk_await.sdg",
			"type": "disk_await",
			"family": "/mnt/8tr",
			"context": "disk.await",
			"title": "Average Completed I/O Operation Time (disk_await.sdg)",
			"priority": 2005,
			"enabled": true,
			"units": "ms per operation",
			"data_url": "/api/v1/data?chart=disk_await.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		...
		"disk_iotime.sdg": 		{
			"id": "disk_iotime.sdg",
			"name": "disk_iotime.sdg",
			"type": "disk_iotime",
			"family": "/mnt/8tr",
			"context": "disk.iotime",
			"title": "Disk Total I/O Time (disk_iotime.sdg)",
			"priority": 2022,
			"enabled": true,
			"units": "milliseconds/s",
			"data_url": "/api/v1/data?chart=disk_iotime.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		"disk_mops.sdg": 		{
			"id": "disk_mops.sdg",
			"name": "disk_mops.sdg",
			"type": "disk_mops",
			"family": "/mnt/8tr",
			"context": "disk.mops",
			"title": "Disk Merged Operations (disk_mops.sdg)",
			"priority": 2021,
			"enabled": true,
			"units": "merged operations/s",
			"data_url": "/api/v1/data?chart=disk_mops.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		"disk_util.sdg": 		{
			"id": "disk_util.sdg",
			"name": "disk_util.sdg",
			"type": "disk_util",
			"family": "/mnt/8tr",
			"context": "disk.util",
			"title": "Disk Utilization Time (disk_util.sdg)",
			"priority": 2004,
			"enabled": true,
			"units": "% of time working",
			"data_url": "/api/v1/data?chart=disk_util.sdg",
			"chart_type": "area",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"utilization": { "name": "utilization" }
			},
			"green": 90,
			"red": 98
		},
		"disk_backlog.sdg": 		{
			"id": "disk_backlog.sdg",
			"name": "disk_backlog.sdg",
			"type": "disk_backlog",
			"family": "/mnt/8tr",
			"context": "disk.backlog",
			"title": "Disk Backlog (disk_backlog.sdg)",
			"priority": 2003,
			"enabled": true,
			"units": "backlog (ms)",
			"data_url": "/api/v1/data?chart=disk_backlog.sdg",
			"chart_type": "area",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"backlog": { "name": "backlog" }
			},
			"green": 2000,
			"red": 5000
		},
		"disk_ops.sdg": 		{
			"id": "disk_ops.sdg",
			"name": "disk_ops.sdg",
			"type": "disk_ops",
			"family": "/mnt/8tr",
			"context": "disk.ops",
			"title": "Disk Completed I/O Operations (disk_ops.sdg)",
			"priority": 2001,
			"enabled": true,
			"units": "operations/s",
			"data_url": "/api/v1/data?chart=disk_ops.sdg",
			"chart_type": "line",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		"disk.sdg": 		{
			"id": "disk.sdg",
			"name": "disk.sdg",
			"type": "disk",
			"family": "/mnt/8tr",
			"context": "disk.io",
			"title": "Disk I/O Bandwidth (disk.sdg)",
			"priority": 2000,
			"enabled": true,
			"units": "kilobytes/s",
			"data_url": "/api/v1/data?chart=disk.sdg",
			"chart_type": "area",
			"duration": 3996,
			"first_entry": 1506960364,
			"last_entry": 1506964360,
			"update_every": 1,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null
		},
		...

**Comment by ktsaou** [comment]
It is on your dashboard too as `/mnt/8tr`. Check it. The menu says `/mnt/8tr`, and the charts are referring to `sdg`.

netdata renames the family of the disk, if it finds it mounted.

**Comment by cobrafast** [comment]
That's odd, other drives are mounted too and are not on the dashboard by their mountpoint name...

**Comment by ktsaou** [comment]
The mount point is used only when the entire disk is mounted. If you have mounted a partition of it, netdata will not show the mount point, since there may be many of them.

**Comment by ktsaou** [comment]
hm... is it possible that netdata was started with these disks connected but not mounted?

In this case, netdata does not alter its initial detection. So, if it found the disk `sde`, but at that time it was not mounted, it would leave it without altering the name.

A simple check is to restart netdata. After the restart, does it properly show all the disks mounted?

**Comment by cobrafast** [comment]
Nope, restarting netdata changes nothing.

**Comment by ktsaou** [comment]
Could you please post your `/proc/self/mountinfo` ?

**Comment by cobrafast** [comment]
Sure

```
18 22 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:5 - proc proc rw
19 22 0:18 / /sys rw,nosuid,nodev,noexec,relatime shared:6 - sysfs sys rw
20 22 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs dev rw,size=16421788k,nr_inodes=4105447,mode=755
21 22 0:19 / /run rw,nosuid,nodev,relatime shared:12 - tmpfs run rw,mode=755
22 0 0:20 / / rw,relatime shared:1 - btrfs /dev/sdh3 rw,ssd,discard,space_cache,subvolid=5,subvol=/
23 19 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:7 - securityfs securityfs rw
24 20 0:23 / /dev/shm rw,nosuid,nodev shared:3 - tmpfs tmpfs rw
25 20 0:24 / /dev/pts rw,nosuid,noexec,relatime shared:4 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
26 19 0:25 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:8 - tmpfs tmpfs ro,mode=755
27 26 0:26 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:9 - cgroup2 cgroup rw
28 26 0:27 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,name=systemd
29 19 0:28 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
30 26 0:29 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,freezer
31 26 0:30 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,devices
32 26 0:31 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,net_cls,net_prio
33 26 0:32 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,memory
34 26 0:33 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,cpu,cpuacct
35 26 0:34 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,pids
36 26 0:35 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,cpuset
37 26 0:36 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,blkio
38 26 0:37 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,perf_event
39 18 0:38 / /proc/sys/fs/binfmt_misc rw,relatime shared:22 - autofs systemd-1 rw,fd=37,pgrp=1,timeout=0,minproto=5,maxproto=5,direct
40 19 0:8 / /sys/kernel/debug rw,relatime shared:23 - debugfs debugfs rw
41 20 0:17 / /dev/mqueue rw,relatime shared:24 - mqueue mqueue rw
42 20 0:39 / /dev/hugepages rw,relatime shared:25 - hugetlbfs hugetlbfs rw,pagesize=2M
43 19 0:40 / /sys/kernel/config rw,relatime shared:26 - configfs configfs rw
73 22 0:42 / /tmp rw,nosuid,nodev shared:27 - tmpfs tmpfs rw
75 22 8:114 / /boot rw,relatime shared:28 - ext4 /dev/sdh2 rw,data=ordered
71 22 8:96 / /mnt/8tr rw,noexec,noatime shared:29 - xfs /dev/sdg rw,attr2,inode64,noquota
80 22 0:44 / /mnt/8t0 rw,noexec,relatime shared:30 - btrfs /dev/sde rw,compress=lzo,space_cache,subvolid=5,subvol=/
78 22 0:43 / /mnt/8t1 rw,noexec,relatime shared:31 - btrfs /dev/sdf rw,compress=lzo,space_cache,subvolid=5,subvol=/
79 21 0:50 / /run/user/1000 rw,nosuid,nodev,relatime shared:32 - tmpfs tmpfs rw,size=3285320k,mode=700,uid=1000,gid=1000
197 19 0:53 / /sys/fs/fuse/connections rw,relatime shared:141 - fusectl fusectl rw
202 22 8:129 / /mnt/tmp rw,relatime shared:145 - ext4 /dev/sdi1 rw,data=ordered
86 73 0:55 / /tmp/.veracrypt_aux_mnt1 rw,nosuid,nodev,relatime shared:133 - fuse.veracrypt veracrypt rw,user_id=0,group_id=0,allow_other
208 22 0:58 / /mnt/r50 rw,relatime shared:149 - btrfs /dev/mapper/veracrypt1 rw,space_cache,subvolid=5,subvol=/
192 22 0:52 / /mnt/data rw,nosuid,nodev,relatime shared:137 - fuse.maidfs maidfs rw,user_id=0,group_id=0,allow_other
```

**Comment by ktsaou** [comment]
yes, you are right. `btrfs` has subvolumes.

netdata matches disks with mount points using the `major` and `minor` numbers. Your `sdg` disk has `8:96` on both `/proc/diskstats` and `/proc/self/mountinfo`.

For `btrfs`, `lvm` and all the volume managers though, the `/proc/self/mountinfo` has different numbers, because even the kernel cannot match them one-on-one.

This is as expected.
