### ISSUE TITLE
orphaned ephemeral nodes are visible even after expiration

### ISSUE THREAD

**Issue by mechakiwi** [firehol/netdata#2832]
I'm attempting to set up support for ephemeral nodes; we have various AWS instances that will appear & disappear without warning. I've tried to follow the instructions found at https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes

I've set up a static master instance that has a registry and has persistence.

All slaves are set up with the following:

> memory mode = none
> registry to announce = (my static master instance)

I have several static slave instances that send data to the master and I have no issues there.

Ephemeral instances are created with no issue and they show up in the my-netdata dropdown list with no problem; all use the same API key to send data to the master.

The problem I'm having is that the ephemeral instances never disappear from the my-netdata dropdown list. I've set the following on the master as a test:

> cleanup obsolete charts after seconds = 120
> cleanup orphan hosts after seconds = 120

However, after an ephemeral instance is terminated it never goes away from the my-netdata dropdown list; this is true even after clearing the browser cache and reloading from the masters URL. The only thing that seems to make them go away is to restart the master netdata process.

My expectation was that the terminated host/instance would go away after 120 seconds. Is this not correct?

Thanks,

~a

**Comment by ktsaou** [comment]
> My expectation was that the terminated host/instance would go away after 120 seconds. Is this not correct?

Well... yes and no:

- netdata cleans up orphaned hosts, when **a new host gets connected**. So, if no new host gets connected, the old ones will be there forever.

- netdata cleans up obsolete charts (this has nothing to do with mirrored hosts, it is a feature that the slave says that they are obsolete now - like removed disk drives, ethernet interfaces, etc), when new charts are being added.

So, netdata does not cleanup, unless something new would probably use the resources occupied.

I think however, that orphaned hosts should be removed from the menu. Let me check the code.

**Comment by ktsaou** [comment]
Yeap. I found it. It shows the hosts on the menu, although they are orphaned.
I am making a PR now.

**Comment by ktsaou** [comment]
It is in #2833

**Comment by ktsaou** [comment]
merged it
