### ISSUE TITLE
Mysql graphs enchance

### ISSUE THREAD

**Issue by vnikitov** [firehol/netdata#284]
It would be good to monitor also MySql graphs like (if it is possible of course):
MySQL Qcache Prunes
MySQL bufferpool hitrate
MySQL bufferpool log waits
MySQL bufferpool wait free
MySQL connection time
MySQL index usage
MySQL keycache hitrate
MySQL long running procs
MySQL open files
MySQL qcache hitrate
MySQL slow queries
MySQL threadcache hitrate
MySQL threads cached
MySQL threads connected
MySQL threads running
MySQL tmp disk tables

Also I think some of them are included.

**Comment by ktsaou** [comment]
If you can write simple shell scripts, the plugin that does the job is here: https://github.com/firehol/netdata/blob/master/charts.d/mysql.chart.sh

You can fork the repo, modify this script, test it on you installation and create a pull request to be merged into netdata.

Otherwise, I'll need some time to look to it...

**Comment by ktsaou** [comment]
> MySQL Qcache Prunes
> MySQL qcache hitrate

I am adding all QCache variables in 4 charts

> MySQL bufferpool hitrate
> MySQL bufferpool log waits
> MySQL bufferpool wait free

I am adding all buffer pool variables in 5 charts

> MySQL connection time

I don't see any variable reporting connection time.

> MySQL index usage

I don't see any variable reporting index usage

> MySQL keycache hitrate

I am adding key MyISAM key cache in 3 charts

> MySQL long running procs

I don't see any variable reporting long running procs

> MySQL open files

I am adding the open files in 2 charts

> MySQL slow queries

Slow queries is already there

> MySQL threadcache hitrate

I don't any variable about thread cache hitrate

> MySQL threads cached
> MySQL threads connected
> MySQL threads running

Threads are already there

> MySQL tmp disk tables

Tmp disk tables are already there

**Comment by paulfantom** [comment]
> MySQL threadcache hitrate

I think something like this is implemented as `Thread_cache_misses`.
And I don't believe those can be grabbed just by simple query `SHOW GLOBAL STATUS`:
> MySQL connection time
> MySQL index usage
> MySQL long running procs

Close?

**Comment by ktsaou** [comment]
mysql connection time could be measured if we close and re-open the connection. To avoid doing this per second, we could do it once every (e.g.) 10 seconds with a special chart having `update_every = 10`.

Also, a friend showed these to me:

http://pmmdemo.percona.com/graph/dashboard/file/MySQL_Overview.json
http://pmmdemo.percona.com/graph/dashboard/file/MySQL_Table_Statistics.json

I need to go chart by chart to see what is missing (if any) from netdata.

For sure there is a need for a different kind of visualization that can have hundreds of dimensions (i.e. mysql tables), and only show the top 10 or 20 at a chart. There have been a few more github issues with related requests (i.e. dynamically add / remove dimensions). The problem with a huge number of dimensions per chart is that the netdata core will need to calculate all of them on each chart refresh. I can think of a solution to this to sort-list the top dimensions and only work on those, but it needs some more work.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.

**Comment by fzyzcjy** [comment]
Hi! I wonder whether we can have a `hit ratio` figure? We already have two separate graphs showing the `Innodb_buffer_pool_read_requests` & `Innodb_buffer_pool_reads`, and the `hit ratio` is just the quotient of the two. Since hit ratio is a useful indication, could we have that? Thanks very much! 

By the way, thanks for the wonderful Netdata! Now I really get addicted to it!
