### ISSUE TITLE
[proxy:error] Connection refused

### ISSUE THREAD

**Issue by Knot3n** [firehol/netdata#2841]
Hi, 

my Vhost: 

<VirtualHost *:80>
        ServerName netdata.x.com
    Redirect 301 "/" "https://netdata.x.com/"

</VirtualHost>

<VirtualHost *:443>
        Servername netdata.x.com

	RewriteEngine On
	ProxyRequests Off
	ProxyPreserveHost On

        <Proxy *>
                Require all granted
        </Proxy>

        ProxyPass "/" "http://localhost:19999/" connectiontimeout=5 timeout=30 keepalive=on
        ProxyPassReverse "/" "http://localhost:19999/"
        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/netdata.x.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/netdata.x.com/privkey.pem
        Header always set Strict-Transport-Security "max-age=31536000; includeSubDomain"

        ErrorLog ${APACHE_LOG_DIR}/netdata-error.log
        CustomLog ${APACHE_LOG_DIR}/netdata-access.log combined
</VirtualHost>

Netdata.conf (WEB)

[web]
        # mode = multi-threaded
        # listen backlog = 4096
        default port = 19999
        bind to = localhost
        # web files owner = netdata
        # web files group = netdata
        # disconnect idle clients after seconds = 60
        # respect do not track policy = no
        # x-frame-options response header =
        # allow connections from = localhost *
        # allow dashboard from = localhost *
        # allow badges from = *
        # allow streaming from = *
        # allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
        enable gzip compression = yes
        # gzip compression strategy = default
        # gzip compression level = 3

Errorlog from apache2

[Wed Oct 04 11:05:29.196919 2017] [proxy_http:error] [pid 13014] [client 162.158.x] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://netdata.x.com/
[Wed Oct 04 11:05:39.319985 2017] [proxy:error] [pid 13015] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:19999 (localhost) failed
[Wed Oct 04 11:05:39.320018 2017] [proxy:error] [pid 13015] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Wed Oct 04 11:05:39.320024 2017] [proxy_http:error] [pid 13015] [client 162.158.90.79:18811] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://netdata.x.com/
[Wed Oct 04 11:05:41.056512 2017] [proxy:error] [pid 13016] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:19999 (localhost) failed

I have no clue what is wrong.. because if i delete the apache2 netdata.conf and add the conf again (fresh) it is working for a few minutes .. then stopped.

If you want to see the "Full" FQDN you can write me and i'll give it to you for testing.

Maybe someone can help me .. thx!

*PS. if i activate the "IP:PORT" (without Localhost @web @conf) so default value .. it is working but with my domain its not.

*edit*

127.0.0.1:19999 is reachable with "curl" !

**Comment by Knot3n** [comment]
*Update

I disabled the Proxy Modules from apache2 and deleted the vhost netdata.conf
and reinstalled all the things again + created a new vhost for netdata now its working ... dont know for how long.

**Comment by ktsaou** [comment]
I hope it will stay there forever.
I am closing this, but if you need help, just post.
