### ISSUE TITLE
[Question] Is it safe to install on a prod CentOS Plesk machine?

### ISSUE THREAD

**Issue by UltimateByte** [firehol/netdata#2843]
Hey there,

Just a (hopefully) quick question : Is it safe to install Netdata on a CentOS 7.4 VM on production that is powered by Plesk?

Thank you.

**Comment by Rockstar04** [comment]
I cant speak to the environment specifics here, but I would suggest spinning up a new CentOS 7.4 VM and install netdata first to get familiar with the install process and how to configure it. I've installed netdata on several ubuntu servers in production with no issues.

**Comment by ktsaou** [comment]
netdata should be safe to be installed on any Linux system.

But, because you never know, it is safer (as @Rockstar04 suggests) to install it on a similar test environment first and then to install it on production.

**Comment by UltimateByte** [comment]
Thanks for your replies.

Well, I'm used to Netdata, I've installed it quite often on Debian machines that were brand new, so I know it works, but never after prod..

I won't be able to re-create the exact same environment at home and cannot obtain a second identical VM, so... Since you seem to think that cats won't be killed during the operation, I'll just try it out right now and get you posted with the results.

**Comment by UltimateByte** [comment]
Well, it seems to work perfectly fine. I just had to open the port within the firewall and rock on!
I'll let you know if I find anything weird but I'm confident it'll be just fine now.

Thank you all, rock on! <3
