### ISSUE TITLE
After restart netdata, plugin mdstat (Systemd Service) is disabled

### ISSUE THREAD

**Issue by andrewsergeev** [firehol/netdata#2846]
**Systemd Service is disappear**

I don't know why, but when i restart my netdata:
`service netdata restart` or `systemctl restart netdata`

When i open netdata page after restart, i not see **Systemd Service**, why it's happens?

P.S. When i update `netdata-updater.sh -f` it's help and **Systemd Service** again shown, before the first restart.

**Comment by ktsaou** [comment]
It usually needs 10 seconds for CGROUPS to kick in. Have you tried waiting a bit?

**Comment by andrewsergeev** [comment]
Oh, I really needed to wait before updating the page, I apologize for the time spent)
