### ISSUE TITLE
[Question] What is the status of support for python 3?

### ISSUE THREAD

**Issue by elfgoh** [firehol/netdata#2848]
I see that there is [logic](https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh#L1527) to handle python 3 but it seems like the [support isn't complete](https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh#L730) eg 

```
declare -A pkg_python_mysqldb=(
	 ['alpine']="py-mysqldb"
	   ['arch']="mysql-python"
	 ['centos']="MySQL-python"
	 ['debian']="python-mysqldb"
	 ['gentoo']="dev-python/mysqlclient"
	['sabayon']="dev-python/mysqlclient"
	   ['rhel']="MySQL-python"
	   ['suse']="python-MySQL-python"
	['default']="python-mysql"

	# exceptions
  ['fedora-24']="python2-mysql"
	)

declare -A pkg_python3_mysqldb=(
	 ['alpine']="WARNING|"
	   ['arch']="WARNING|"
	 ['centos']="WARNING|"
	 ['debian']="WARNING|"
	 ['gentoo']="dev-python/mysqlclient"
	['sabayon']="dev-python/mysqlclient"
	   ['rhel']="WARNING|"
	   ['suse']="WARNING|"
	['default']="WARNING|"

	# exceptions
	['ubuntu-16.04']="python3-mysqldb"
```

May I know the status roadmap for python 3 support?

**Comment by ktsaou** [comment]
We fully support python3. We did since the very beginning.

The distributions do not support python3 yet.

**Comment by elfgoh** [comment]
In the above example, python3-mysqldb is present. Why does the [line for debian](https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh#L755) indicate `['debian']="WARNING|"`

> The distributions do not support python3 yet.

In my case, I am using Debian stretch which is built up from a minimal image. It definitely supports python 3, though I need to install manually. Is this the type of support that you are referring to?

**Comment by ktsaou** [comment]
ok, I thought you mean "support in netdata". In netdata it was always supported.

I added `python3-mysqldb` for debian. Actually I added it for all future releases of debian/ubuntu, blacklisting it for the older ones.
