### ISSUE TITLE
memory utillization ( Used RAM ) calculation

### ISSUE THREAD

**Issue by shkart** [firehol/netdata#2849]
Hi, 
    I am trying to calculate the Used RAM ( memory utilization ) in standalone application. I understand the netdata tool is updating the Used RAM field using the formula 

Used RAM = $used * 100 / ($used + $cached + $free)

when I use the exact formula I am getting different result. Can anyone please tell me how exactly it is getting calculated.

Thanks in advance.

**Comment by ktsaou** [comment]
Could you please post screenshots of what you see in netdata (chart and alarm)?

**Comment by shkart** [comment]
Hi kstsaou,
                 Please see below screenshot file.

![screen_shot](https://user-images.githubusercontent.com/28146585/31288753-dcb55cb2-aae3-11e7-9caf-603ce46a1614.png)

Thanks in advance.

**Comment by ktsaou** [comment]
I would need the `system.ram` chart too.

**Comment by shkart** [comment]
Here it is,

![screen_shot_system_ram](https://user-images.githubusercontent.com/28146585/31289506-95cac6f4-aae6-11e7-9e16-0c19e2bbb20b.png)

**Comment by ktsaou** [comment]
The pie chart shows: `(used + buffers) * 100 / total`.

In your case:

```
total = 80 + 777 + 121 + 10 = 988
used = 777 + 10 = 787
% = 787 * 100 / 988 = 79,66
```

I guess the little difference is because of timing: the 2 screenshots are not from the same second.
Your previous screenshot showed 78.4 %.

If you really want to verify this, I suggest to fetch `http://your.netdata.ip:19999/api/v1/data?chart=system.ram&after=-1`. This will give you something like this:

```js
{
 "labels": ["time", "free", "used", "cached", "buffers"],
    "data":
 [
      [ 1507321478, 153.50391, 6323.859, 1361.8516, 147.46094]
  ]
}
```

and do the calculation yourself.

**Comment by shkart** [comment]
Thanks for the reply, 

If we calculate from below values I am getting exact values as in the chart.

{
 "labels": ["time", "free", "used", "cached", "buffers"],
    "data":
 [
      [ 1507321478, 153.50391, 6323.859, 1361.8516, 147.46094]
  ]
}

Can you please tell me how these values are getting populated after reading from /proc/meminfo file. 

As I understand, 

"free" is mapped to MemFree in /proc/meminfo file,
"cached" is mapped to Cached in /proc/meminfo file
"buffers" is mapped to Buffers in /proc/meminfo file
"used" = MemTotal - MemFree - Buffers - Cached

and I used these values from the file directly to formula,

%Used Ram = ( "used" + "buffers" ) / ("free" + "cached" + "buffers" + "used")

And I am getting the different result.

Can you please tell how the values are getting converted to 

   "data":
 [
      [ 1507321478, 153.50391, 6323.859, 1361.8516, 147.46094]
  ]

**Comment by ktsaou** [comment]
netdata read these values from `/proc/meminfo`. This is the code: https://github.com/ktsaou/netdata/blob/71d403647d024b7e9db96c8c38ec11109e4a694e/src/proc_meminfo.c#L165-L168

It then applies interpolation to find the exact value at second-boundaries. For example, 500MB at 00:00:00.500 and 1000MB at 00:00:01.500, gives 750MB at 00:00:01.000.

**Comment by shkart** [comment]
I am not sure how netdata is applying the interpolation, can you please share the algorithm on how the values are getting converted.

**Comment by ktsaou** [comment]
Of course: https://github.com/ktsaou/netdata/blob/57a38770fe2ddb93587fe9c2023163ff6117c869/src/rrdset.c#L820-L1016

netdata has unit tests to ensure this works as expected. You can run them with:

`netdata -W unittest`

There will be a lot of output. Check for blocks like this:

```
Running test 'test1':
test absolute values stored at exactly second boundaries
    > test1: feeding position 1
       >> dim1 with value 10
2017-10-15 18:57:34: netdata INFO : INTERNAL CHECK: host 'unittest', chart 'netdata.unittest_test1' is collected in the same interpolation point: short by 500000 microseconds
    > test1: fixing first collection time to be 0 microseconds to second boundary
    > test1: feeding position 2, after 1.000 seconds (1.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 20
    > test1: feeding position 3, after 1.000 seconds (2.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 30
    > test1: feeding position 4, after 1.000 seconds (3.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 40
    > test1: feeding position 5, after 1.000 seconds (4.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 50
    > test1: feeding position 6, after 1.000 seconds (5.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 60
    > test1: feeding position 7, after 1.000 seconds (6.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 70
    > test1: feeding position 8, after 1.000 seconds (7.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 80
    > test1: feeding position 9, after 1.000 seconds (8.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 90
    > test1: feeding position 10, after 1.000 seconds (9.000 seconds from start), delta 10.0000000, rate 10.0000000
       >> dim1 with value 100
    test1/dim1: checking position 1 (at 0 secs), expecting value 20.0000000, found 20.0000000, OK
    test1/dim1: checking position 2 (at 1 secs), expecting value 30.0000000, found 30.0000000, OK
    test1/dim1: checking position 3 (at 2 secs), expecting value 40.0000000, found 40.0000000, OK
    test1/dim1: checking position 4 (at 3 secs), expecting value 50.0000000, found 50.0000000, OK
    test1/dim1: checking position 5 (at 4 secs), expecting value 60.0000000, found 60.0000000, OK
    test1/dim1: checking position 6 (at 5 secs), expecting value 70.0000000, found 70.0000000, OK
    test1/dim1: checking position 7 (at 6 secs), expecting value 80.0000000, found 80.0000000, OK
    test1/dim1: checking position 8 (at 7 secs), expecting value 90.0000000, found 90.0000000, OK
    test1/dim1: checking position 9 (at 8 secs), expecting value 100.0000000, found 100.0000000, OK

```

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
