### ISSUE TITLE
Linking Prometheus to Netdata when it's been bound to localhost

### ISSUE THREAD

**Issue by jonathannz** [firehol/netdata#2853]
I've followed your instructions for binding Netdata to localhost (127.0.0.1), so that it can only be accessed within the local server (which I am doing via an SSH session that binds my localhost:19998 to the server localhost:19999.

Now I am setting up Prometheus. I have followed the instructions you provide in the wiki. I changed the following:

`static_configs:
      - targets: ['{your.netdata.ip}:19999']`

to

`static_configs:
      - targets: ['{127.0.0.1}:19999']`

I've also tried:

``static_configs:
      - targets: ['{PUBLIC-IP}:19999']`

I get a connection time out when accessing PUBLIC:9090. 

I have the firewall on Azure set to allow inbound requests on 9090.

Am I going about this the right way?

**Comment by ktsaou** [comment]
Is your prometheus running on the same server netdata runs?

**Comment by jonathannz** [comment]
Yes, all on the one VM.

**Comment by ktsaou** [comment]
Run this:

```sh
curl 'http://127.0.0.1:19999/api/v1/allmetrics?format=prometheus'
```

Does it work?

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
