### ISSUE TITLE
detect overflow of TCP LISTEN queue

### ISSUE THREAD

**Issue by ChrisEt** [firehol/netdata#2855]
Hi,
I'd like to propose adding the _TcpExtListenOverflows_ counter to the chart "TCP Handshake Issues".
### Reason behind this:
I'm currently investigating a problem on one of our machines where the server (Java-based) can't keep up with the amount of incoming connections. New connections fill up the LISTEN queue until it finally overflows. The result is that connections get dropped. I'd like to monitor this condition in a chart and add an alarm to this.
For those interested in the background, this post nicely descibes what is behind this counter: https://perfchron.com/2015/12/26/investigating-linux-network-issues-with-netstat-and-nstat/
And here: http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
### More ideas:
I also thought if it makes sense to monitor the length of the LISTEN queue directly (Recv-Q in `netstat -n -a` for LISTEN connections). But a) this would require parsing through all open connections which, as you correctly state in #2169 is not a good idea performance-wise, and b) the length of this queue can be configured by applications so we would not know when it is full.
But I guess a temporary increase of queued connections is not a problem, only when connections start to be dropped massively. That is a condition I'd like to be notified of.

What do you think? Is this an addition that would make sense? And by the way, keep up the good work, I love this tool!

**Comment by ktsaou** [comment]
Hi,

excellent idea! Thank you for requesting this!

Actually, there are a ton of metrics in the kernel. I have added many, but there are a lot more that I couldn't find any information, so they are not enabled.

Implemented in PR #2857

**Comment by ktsaou** [comment]
merged it.

**Comment by ChrisEt** [comment]
And just a few minutes ago I got an alarm from my server, reporing listen overflows. And this even though the netdata service was temporarily set to "disabled"! You're a wizard, how did you do this man? :-)
