### ISSUE TITLE
Disable group of plugins at once

### ISSUE THREAD

**Issue by Redsandro** [firehol/netdata#2858]
Is there a way to disable a group of plugins without hunting down every graph in the configuration?

I.e. intuitively something like so:

```
[users.*]
    enabled = no
[groups.*]
    enabled = no
[netdata.*]
    enabled = no
```

**Comment by Redsandro** [comment]
@ktsaou First things first. Here's some kind of reward for commenting on this issue so quickly! :1st_place_medal: 

I did actually glance over that in the docs and in the config, but I failed to extrapolate or understand which ones to disable. For example, how do I know what is the `users` or `groups` plugin? Is there some naming convention that, once known, makes sense?

**Comment by ktsaou** [comment]
You are right. This is problematic.

Unfortunately, the original idea about enabling/disabling things, was to control the CPU consumption of netdata and its plugins. So, they have been organized with plugins in mind.

There is issue #2692 to extend the plugins protocol a bit, to allow netdata know the plugin and its module that collects each chart. netdata could expose this information on the dashboard or allow us to enable/disable them centrally.

**Comment by Redsandro** [comment]
Thank you for the reference @ktsaou. I'm not sure if there's an issue for this, but it would also help to have a little 'X' next to each graph, and on click the graph would remove itself (and the corresponding entry in the configuration would get an `enabled = no` in case the server or service reboots).

### Workaround

One not-so-high-tech workaround is to use a regular expression on a default configuration file like so:

* Find: 
  * `^\[(users\..+)\]([\n\t#\w \=]+)# enabled = yes`
* Replace: 
  * `[\1]\2enabled = no`
* Find: 
  * `^\[(groups\..+)\]([\n\t#\w \=]+)# enabled = yes`
* Replace: 
  * `[\1]\2enabled = no`
* Find: 
  * ...etc

This works in your favorite multi-line regex find/replace supporting text editor. Like Geany:
![image](https://user-images.githubusercontent.com/1702193/31359274-93ded2d0-ad49-11e7-8dca-60278f4db936.png)

This is not ideal for quickly 'setting up' a new server, but it's slightly better than finding each entry manually.
