### ISSUE TITLE
Net Data Mailing Issue

### ISSUE THREAD

**Issue by ankushsatija1** [firehol/netdata#2859]
Dear Sir

I have installed netdata for my organization for monitor the bandwidth and other process and  it installed successfully i also configured mail function and getting mail on server up performance or any other related issue but one thing i got one issue,i got all mail in spam folder instead of inbox folder so can you please let me know where i can authenticate my mail id and password so that i got mail on inbox folder.

Url :- http://34.201.63.210:19999/

Please support me asap thanks.

**Comment by ktsaou** [comment]
Well, I am not sure how to help you.

netdata calls `sendmail -t` to send the emails, as local user `netdata`. It is then up to your email server to do the rest.

So, I suggest to look for help at your mail server documentation or forums.

**Comment by ktsaou** [comment]
If you need to tweak the sender of the emails, check this: https://github.com/firehol/netdata/blob/7a1b3d8b1a789ca621278fb04d2b3b03ce15badd/conf.d/health_alarm_notify.conf#L104

With this option you can configure the sender of the emails. So they will not be sent as `netdata@host` but as whatever you write there, by running `sendmail -f ${EMAIL_SENDER} -t`.

Still, how the email is routed and trusted, is handled entirely by your MTA.

**Comment by talkyy** [comment]
Hi,
I think you should explain how you install and config alarm via email. I tried config alarm via email and it works very well.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
