### ISSUE TITLE
disabling bootstrap causes js exception

### ISSUE THREAD

**Issue by swiftugandan** [firehol/netdata#286]
I am creating a custom dashboard that does not need bootstrap. I disabled it using:

**var netdataNoBootstrap = true; ** and the graphs  fail to show with the exception

"**TypeError: $(...).popover is not a function**" in the console

Please advise

**Comment by swiftugandan** [comment]
my head

`    <head>
        <title>Title</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        
        <script language="javascript" type="text/javascript">
            var netdataNoSparklines = true;              // do not use sparkline
            var netdataNoPeitys = true;                  // do not use peity
            var netdataNoGoogleCharts = true;    // do not use google
            var netdataNoMorris = true;                  // do not use morris
            var netdataNoEasyPieChart = true;    // do not use easy pie chart
            var netdataNoGauge = true;                   // do not use gauge.js
            var netdataNoD3 = true;                              // do not use D3
            var netdataNoC3 = true;                              // do not use C3
            // var netdataNoBootstrap = true;               // do not load bootstrap
        </script>
        <script type="text/javascript" src="/netdata/dashboard.js"></script>
    </head>`

**Comment by ktsaou** [comment]
ok. I added the popovers last week.

Until I fix it permanently, please open the default dashboard using your browser, disable help (from the settings modal) and retry your dashboard.

I will have the dashboard disable help automatically, if bootstrap is not loaded.

**Comment by ktsaou** [comment]
Ok. Fixed it.

**Comment by swiftugandan** [comment]
Thank you
