### ISSUE TITLE
Docker unit-scaling features

### ISSUE THREAD

**Issue by that1guy** [firehol/netdata#2860]
Hello,

I've just pulled down the most recent docker image (`docker pull firehol/netdata`) but I don't see the new unit-scaling features.  Any ideas whats going on?  Thanks.

![image](https://user-images.githubusercontent.com/1218940/31427423-0ecbae6e-ae1c-11e7-8e37-49ca1ecdf306.png)

![image](https://user-images.githubusercontent.com/1218940/31427392-ee1af396-ae1b-11e7-8af2-489f1491056e.png)

**Comment by ktsaou** [comment]
Just installed too.
It has the new functionality.

![screenshot from 2017-10-11 13-44-37](https://user-images.githubusercontent.com/2662304/31436065-5ebfd09e-ae8a-11e7-9bb3-551c17361b21.png)

version:

![screenshot from 2017-10-11 13-45-12](https://user-images.githubusercontent.com/2662304/31436090-7167d516-ae8a-11e7-95e6-b2ff44e592b2.png)

Could you please press control-F5 on your browser? It may have cached the files from a previous run, on the same IP.

**Comment by that1guy** [comment]
Apologies guys.  This was a cloudflare caching issue.  Thanks for knocking some sense into me.
