### ISSUE TITLE
netdata-updater.sh failing

### ISSUE THREAD

**Issue by scottjl** [firehol/netdata#2867]
Centos 7 system, server is up-to-date. netdata-updater.sh fails with the following:

```
Wed Oct 11 07:11:25 CDT 2017 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Wed Oct 11 07:11:25 CDT 2017 : INFO:  Updating netdata source from github...
error:  while accessing https://github.com/firehol/netdata.git/info/refs

fatal: HTTP request failed
Wed Oct 11 07:11:25 CDT 2017 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)
```

Is auto-updating gone?

**Comment by ktsaou** [comment]
It works for me.
Could you please retry? It might be a networking issue, or some maintenance by github.

**Comment by scottjl** [comment]
Nope. It's been doing this the past 2 days. I have netdata installed on about 100 servers and I'm getting spammed with failed update notices :-(

**Comment by scottjl** [comment]
Apparently github implemented some change. I get the following error when I follow the URL:

Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
