### ISSUE TITLE
unable to working with debian 8 working with ubuntu 16.04

### ISSUE THREAD

**Issue by rajuginne** [firehol/netdata#2870]
root@lamp-1-vm:~/netdata# netstat -nat  | grep 19999
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN
root@lamp-1-vm:~/netdata# ps fax | grep netdata
 2811 pts/1    S+     0:00  |                       \_ grep netdata
 2330 ?        Sl     0:00 /usr/sbin/netdata
 2348 ?        S      0:00  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
 2351 ?        Sl     0:00  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 2352 ?        S      0:00  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
 2578 ?        Sl     0:00 /usr/sbin/netdata
 2596 ?        S      0:00  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
 2599 ?        Sl     0:00  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 2600 ?        S      0:00  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

sudo nano /etc/netdata/netdata.conf

[web]
        # mode = multi-threaded
        # listen backlog = 4096
         default port = 19999
         bind to = 0.0.0.0:19999
         web files owner = netdata
         web files group = netdata

firewall ufw 

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
21                         DENY        Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
WWW Full                   ALLOW       Anywhere
25                         DENY        Anywhere
9000                       ALLOW       Anywhere
Nginx HTTP                 ALLOW       Anywhere
19999/tcp                  ALLOW       Anywhere
2000/tcp                   ALLOW       Anywhere
22                         ALLOW       Anywhere (v6)
21                         DENY        Anywhere (v6)
80                         ALLOW       Anywhere (v6)
443                        ALLOW       Anywhere (v6)
WWW Full (v6)              ALLOW       Anywhere (v6)
25                         DENY        Anywhere (v6)
9000                       ALLOW       Anywhere (v6)
Nginx HTTP (v6)            ALLOW       Anywhere (v6)
19999/tcp                  ALLOW       Anywhere (v6)
2000/tcp                   ALLOW       Anywhere (v6)

iptables -s

root@lamp-1-vm:~/netdata# sudo iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
fail2ban-NoLoginFailures  tcp  --  anywhere             anywhere             mul                                                                                                                     tiport dports http,https
fail2ban-NoProxy  tcp  --  anywhere             anywhere             multiport d                                                                                                                     ports http,https
fail2ban-BadBots  tcp  --  anywhere             anywhere             multiport d                                                                                                                     ports http,https
fail2ban-nginx-http-auth  tcp  --  anywhere             anywhere             mul                                                                                                                     tiport dports http,https
fail2ban-ssh-ddos  tcp  --  anywhere             anywhere             multiport                                                                                                                      dports ssh
fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dport                                                                                                                     s ssh
ufw-before-logging-input  all  --  anywhere             anywhere
ufw-before-input  all  --  anywhere             anywhere
ufw-after-input  all  --  anywhere             anywhere
ufw-after-logging-input  all  --  anywhere             anywhere
ufw-reject-input  all  --  anywhere             anywhere
ufw-track-input  all  --  anywhere             anywhere

Chain FORWARD (policy DROP)
target     prot opt source               destination
ufw-before-logging-forward  all  --  anywhere             anywhere
ufw-before-forward  all  --  anywhere             anywhere
ufw-after-forward  all  --  anywhere             anywhere
ufw-after-logging-forward  all  --  anywhere             anywhere
ufw-reject-forward  all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ufw-before-logging-output  all  --  anywhere             anywhere
ufw-before-output  all  --  anywhere             anywhere
ufw-after-output  all  --  anywhere             anywhere
ufw-after-logging-output  all  --  anywhere             anywhere
ufw-reject-output  all  --  anywhere             anywhere
ufw-track-output  all  --  anywhere             anywhere

Chain **fail2ban-BadBots** (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-NoLoginFailures (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-NoProxy (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-nginx-http-auth (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-ssh (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-ssh-ddos (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain ufw-after-forward (1 references)
target     prot opt source               destination

Chain ufw-after-input (1 references)
target     prot opt source               destination
ufw-skip-to-policy-input  udp  --  anywhere             anywhere             udp                                                                                                                      dpt:netbios-ns
ufw-skip-to-policy-input  udp  --  anywhere             anywhere             udp                                                                                                                      dpt:netbios-dgm
ufw-skip-to-policy-input  tcp  --  anywhere             anywhere             tcp                                                                                                                      dpt:netbios-ssn
ufw-skip-to-policy-input  tcp  --  anywhere             anywhere             tcp                                                                                                                      dpt:microsoft-ds
ufw-skip-to-policy-input  udp  --  anywhere             anywhere             udp                                                                                                                      dpt:bootps
ufw-skip-to-policy-input  udp  --  anywhere             anywhere             udp                                                                                                                      dpt:bootpc
ufw-skip-to-policy-input  all  --  anywhere             anywhere             ADD                                                                                                                     RTYPE match dst-type BROADCAST

Chain ufw-after-logging-forward (1 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 3/min b                                                                                                                     urst 10 LOG level warning prefix "[UFW BLOCK] "

Chain ufw-after-logging-input (1 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 3/min b                                                                                                                     urst 10 LOG level warning prefix "[UFW BLOCK] "

Chain ufw-after-logging-output (1 references)
target     prot opt source               destination

Chain ufw-after-output (1 references)
target     prot opt source               destination

Chain ufw-before-forward (1 references)
target     prot opt source               destination
ufw-user-forward  all  --  anywhere             anywhere

Chain ufw-before-input (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTA                                                                                                                     BLISHED
ufw-logging-deny  all  --  anywhere             anywhere             state INVAL                                                                                                                     ID
DROP       all  --  anywhere             anywhere             state INVALID
ACCEPT     icmp --  anywhere             anywhere             icmp destination-u                                                                                                                     nreachable
ACCEPT     icmp --  anywhere             anywhere             icmp source-quench
ACCEPT     icmp --  anywhere             anywhere             icmp time-exceeded
ACCEPT     icmp --  anywhere             anywhere             icmp parameter-pro                                                                                                                     blem
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
ACCEPT     udp  --  anywhere             anywhere             udp spt:bootps dpt                                                                                                                     :bootpc
ufw-not-local  all  --  anywhere             anywhere
ACCEPT     udp  --  anywhere             224.0.0.251          udp dpt:mdns
ACCEPT     udp  --  anywhere             239.255.255.250      udp dpt:1900
ufw-user-input  all  --  anywhere             anywhere

Chain ufw-before-logging-forward (1 references)
target     prot opt source               destination

Chain ufw-before-logging-input (1 references)
target     prot opt source               destination

Chain ufw-before-logging-output (1 references)
target     prot opt source               destination

Chain ufw-before-output (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTA                                                                                                                     BLISHED
ufw-user-output  all  --  anywhere             anywhere

Chain ufw-logging-allow (0 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 3/min b                                                                                                                     urst 10 LOG level warning prefix "[UFW ALLOW] "

Chain ufw-logging-deny (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             state INVALID limi                                                                                                                     t: avg 3/min burst 10
LOG        all  --  anywhere             anywhere             limit: avg 3/min b                                                                                                                     urst 10 LOG level warning prefix "[UFW BLOCK] "

Chain ufw-not-local (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             ADDRTYPE match dst                                                                                                                     -type LOCAL
RETURN     all  --  anywhere             anywhere             ADDRTYPE match dst                                                                                                                     -type MULTICAST
RETURN     all  --  anywhere             anywhere             ADDRTYPE match dst                                                                                                                     -type BROADCAST
ufw-logging-deny  all  --  anywhere             anywhere             limit: avg                                                                                                                      3/min burst 10
DROP       all  --  anywhere             anywhere

Chain ufw-reject-forward (1 references)
target     prot opt source               destination

Chain ufw-reject-input (1 references)
target     prot opt source               destination

Chain ufw-reject-output (1 references)
target     prot opt source               destination

Chain ufw-skip-to-policy-forward (0 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere

Chain ufw-skip-to-policy-input (7 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere

Chain ufw-skip-to-policy-output (0 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere

Chain ufw-track-input (1 references)
target     prot opt source               destination

Chain ufw-track-output (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             state NEW
ACCEPT     udp  --  anywhere             anywhere             state NEW

Chain ufw-user-forward (1 references)
target     prot opt source               destination

Chain ufw-user-input (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ssh
DROP       tcp  --  anywhere             anywhere             tcp dpt:ftp
DROP       udp  --  anywhere             anywhere             udp dpt:fsp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     udp  --  anywhere             anywhere             udp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     udp  --  anywhere             anywhere             udp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             multiport dports h                                                                                                                     ttp,https /* 'dapp_WWW%20Full' */
DROP       tcp  --  anywhere             anywhere             tcp dpt:smtp
DROP       udp  --  anywhere             anywhere             udp dpt:25
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9000
ACCEPT     udp  --  anywhere             anywhere             udp dpt:9000
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http /* 'd                                                                                                                     app_Nginx%20HTTP' */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:19999
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:cisco-sccp

Chain ufw-user-limit (0 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 3/min b                                                                                                                     urst 5 LOG level warning prefix "[UFW LIMIT BLOCK] "
REJECT     all  --  anywhere             anywhere             reject-with icmp-p                                                                                                                     ort-unreachable

Chain ufw-user-limit-accept (0 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere

Chain ufw-user-logging-forward (0 references)
target     prot opt source               destination

Chain ufw-user-logging-input (0 references)
target     prot opt source               destination

Chain ufw-user-logging-output (0 references)
target     prot opt source               destination

Chain ufw-user-output (1 references)
target     prot opt source               destination
root@lamp-1-vm:~/netdata#

**Comment by rajuginne** [comment]
server @ google cloud

**Comment by ktsaou** [comment]
Hi,

Did you solve it? When you say it does not work, what exactly do you mean?

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
