### ISSUE TITLE
./makeself/build-x86_64-static.sh failure

### ISSUE THREAD

**Issue by woosley** [firehol/netdata#2873]
Hi, 

I am trying to build the static file using _./makeself/build-x86_64-static.sh_, but the build failed,

looking at the log, it seems the build failed at bash installation. 
here is the build full log: 
https://gist.github.com/woosley/f1d122bd951a485d64f09131dd1e1127

here is the bash make output:
https://gist.github.com/woosley/29d6e4fcb4df3f18a372168c25c6ed51

Can you kindly take a look what is wrong?

**Comment by ktsaou** [comment]
Hi,

I think there some issue with your setup. I see errors like these:

```
/usr/include/ctype.h:12:7 error: expected identifier ...
```

This is a system include file...

**Comment by woosley** [comment]
closing, I tried another VM and  worked.
