### ISSUE TITLE
zfs writes are not monitored

### ISSUE THREAD

**Issue by diched** [firehol/netdata#2877]
Hi,

Just created a simple stripe zfs pool with
zpool create -f zfspool sdb sdc sdd

on a Centos7 machine. 

And ran bonnie++ on it. The netdata showed read activity instead of write (but lower throughput than in reality).

Anyone else seen a similar problem?

Thanks

**Comment by ktsaou** [comment]
ok, I installed zfs on my system to test this.

The statistics provided by zfs are about its performance and caches, as a filesystem. ZFS does not provide statistics about reads/writes to the underlying devices. The kernel does.

So, at the `ZFS Filesystem` section of netdata, you can find statics about the operation of ZFS, independently on the number of mount points, pools, etc. This has stats about cache hits, L2 ARC, etc.

To find the I/O bandwidth, you can check the `Disks` section at netdata. There you will find what each physical disk does, its I/O bandwidth, operations/s, utilization %, etc.

**Comment by diched** [comment]
Hi Costa,

Thanks for looking into this.
Basically, what I've reported is exactly the problem in the Disks section -
instead of write activity I've observed read, while intensive write
operation was ongoing (bonnie benchmark), and iostat was showing proper
numbers in the process.

Thanks
Ed

**Comment by ktsaou** [comment]
> Basically, what I've reported is exactly the problem in the Disks section

Cannot be. How much ram do you have? Are you writing with bonnie, more than your ram?

bonnie can measure what is writing. netdata monitors what the kernel really wrote. At the `Applications` charts you should see both logical and physical writes. The logical writes should be close to what bonnie reports.

If you want to monitor bonnie, add it to `/etc/netdata/apps_groups.conf`. Then netdata will be able to report both logical and physical reads and write for bonnie.

**Comment by ktsaou** [comment]
Of course, disk I/O is completely different. Your `sdb`, `sdc` and `sdd` charts should report their physical writes.

**Comment by diched** [comment]
I write double the RAM amount, and also provide the direct write option,
just in case.
Bonnie returned correct results, so did iostat. I didn't care to check the
Applications section, that wasn't interesting for now. But the sdc sdb and
overall activity was totally off. Like it was in fact writing 1.5GB/s, and
netdata showed 700MB/s being *read* not written.

I will redo the test as soon as I recreate my pools, testing hardware raid
for the moment (works perfectly, just to mention it).

**Comment by diched** [comment]
I redid the tests with the newest version of netdata, and can confirm my observations. I run fio tests on the zpool, and it does reads and writes with different block sizes in a sequence. The console shows the actual read and write throughputs and iops:

Jobs: 1 (f=1): [_(25),W(1),P(22)] [96.2% done] [0KB/1605MB/0KB /s] [0/3210/0 iops] [eta 00m:30s]        

Netdata displays a picture as can be seen in the attachment 
<img width="1373" alt="screen shot 2017-10-25 at 19 46 58" src="https://user-images.githubusercontent.com/32767337/32014203-b625c832-b9bd-11e7-8637-0af73323fd2d.png">

Here, the green "in" spikes (shown the "donuts" as read activity) actually correspond to the moments where fio is doing WRITE traffic. During real READ actions there is zero activity shown on the overall 'disks' menu. The file size is smallish though - I have 40G, while the RAM is 256. I might have to redo it with larger file size for once. But would appreciate your inpur/comments.
Thanks!

**Comment by ktsaou** [comment]
Also, please post the same chart for each of your disks. In general netdata does not do anything special with zfs. These are the stats the kernel exposes. On the tests I made above, I checked the per-disk stats and they were accounting zfs reads and writes.

**Comment by diched** [comment]
The individual disks show both read and write operations. This is however meaningless - I'm interested in total throughput, like that normally presented by the disks section, or the top-level system overview donut, which provide false information in this case.

**Comment by ktsaou** [comment]
ok, I think I found the problem.

The total disk I/O reported by netdata comes for `/proc/vmstat`, counters `pgpgin` and `pgpgout`:

- `pgpgin` is the amount of memory (in KB) that the kernel paged in from disk.
- `pgpgout` is the amount of memory (in KB) that the kernel paged out to disk.

So, my understanding is that zfs works in a way that the kernel gets confused.

I see that `vmstat -d` uses `/proc/diskstats`, which is probably what we should do too.

Let me check how to fix that.

**Comment by diched** [comment]
Thanks ! 
If I can be of any help please let me know!
Also, just FYI, "zpool iostat" reports the correct integrated IO per pool. If there is a way to somehow plug that info under individual pool stats, that would be awesome!

**Comment by ktsaou** [comment]
Implemented at PR #2927

**Comment by ktsaou** [comment]
I have to admin though, that on my system both the old and the new charts report the same:

![image](https://user-images.githubusercontent.com/2662304/32021940-8cbf05ec-b9dd-11e7-9905-44ad773f5e85.png)

The new chart (above) comes from the sum of all disks, and the old chart (below) comes from `/proc/vmstat`. It might be kernel dependent though (I run 4.13.5).

**Comment by diched** [comment]
I use the stock 3.10.0. 
How can I test this patch?

**Comment by ktsaou** [comment]
> How can I test this patch?

```
git clone https://github.com/ktsaou/netdata
```

then, run `netdata-installer.sh` from it.

**Comment by ktsaou** [comment]
merged it.
