### ISSUE TITLE
service removed from display when it dies or dies and is restarted

### ISSUE THREAD

**Issue by sbingram** [firehol/netdata#2878]
I have an instance with MySQL running that periodically dies from an out of memory issue. When the service dies, rather than issue an alarm, Netdata simply removes the service from the display. If systemd is set to auto-restart the service, the service does not reappear in Netdata until Netdata itself is restarted. Since we are trying to be notified when MySQL dies, this doesn't work so well. Is this an expected behavior or a bug?

**Comment by ktsaou** [comment]
I think this is what happens:

1. mysql runs out of memory
2. netdata is killed by the kernel (it is marked to be killed first)
3. mysql is killed just after
4. netdata is restarted

So, it ends up without monitoring mysql.

I suggest to change the OOM score of netdata. If you run it under `systemd` (most current systems), you will need to edit `/etc/systemd/system/netdata.service` and set:

```
[Service]
  # set the minimum OOMScore netdata can have
  OOMScoreAdjust=-1000
```

And then you will be able to set it in `netdata.conf`, with this:

```
[global]
  # set the netdata OOMScore
  OOM score = -500
```

Note, that if you want to set it from `netdata.service`, you can set in `netdata.conf` this:

```
[global]
  # make netdata keep the OOMScore set by systemd
  OOM score = keep
```

**Comment by ktsaou** [comment]
I added a wiki page for this: https://github.com/firehol/netdata/wiki/netdata-OOMScore

**Comment by sbingram** [comment]
That makes sense, and in the latest example I can confirm via logs that both netdata and mysql were both killed by the kernel due to an OOM situation. From the timestamp it appears as though netdata was restarted first (I also have mysql set to restart via systemd) so it didn't see mysql upon startup, thus it didn't display it. Obviously without netdata running, there is no way for it to alert. I'm making the changes you suggested to see that netdata hopefully remains running and see if this doesn't resolve the issue. Is there no way to have netdata see new processes that start on the system without having to restart netdata itself?

**Comment by l2isbad** [comment]
> Is there no way to have netdata see new processes that start on the system without having to restart netdata itself?

implemented for python modules in https://github.com/firehol/netdata/pull/2872

**Comment by sbingram** [comment]
Ok, just reporting back on this one. I made the changes suggested by Costa and it worked perfectly. MySQL exceeded the available RAM and was shutdown by the kernel. This time Netdata remained running and was able to alert about the outage and again when the MySQL service returned after being restarted by systemd. I'd say this one is resolved.

An additional comment, I'm not sure why you would want the default setting to kill Netdata first. While I agree that on a production server you want to protect the primary services at all cost. However, with as few resources as Netdata uses, is it really helping much by killing it? I'd personally rather see Netdata keep running and let me know I have a problem without fail, but I certainly do like that you have an easy choice via the config.

**Comment by ktsaou** [comment]
nice!

Check this for the reasons behind my decision: https://github.com/firehol/netdata/issues/2549#issuecomment-319666691
