### ISSUE TITLE
changes to haproxy.chart.py gets overwritten

### ISSUE THREAD

**Issue by nullart** [firehol/netdata#2880]
Hi,

I updated /usr/libexec/netdata/python.d/haproxy.chart.py, but on the next day, it reverted back.

Is there a way for my changes to persist? 

thanks,

**Comment by l2isbad** [comment]
1. rename it to `haproxy_custom.chart.py`
2. disable old haproxy module in [python.d.conf](https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf)

```yaml
haproxy: no
```
3. restart netdata.service

**Comment by nullart** [comment]
I may have missed something, as theres no haproxy in the monitoring after. Heres what I did:

1. Rename  /usr/libexec/netdata/python.d/haproxy.chart.py to  /usr/libexec/netdata/python.d/haproxy_custom.chart.py
2. updated /usr/libexec/netdata/python.d/haproxy_custom.chart.py to my settings. Basically I used "svname" for the backend.
3. disabled haproxy in /etc/netdata/python.d.conf by "haproxy: no"
4. restarted netdata: "service netdata restart"

I'm using Debian 8

**Comment by l2isbad** [comment]
@nullart 
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins (debug section)

```
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug haproxy_custom
```

I'm using Debian 8
👍  😄

**Comment by nullart** [comment]
Thanks @l2isbad ! It worked! 

Heres what was needed after running the plugin debug:
copied: /etc/netdata/python.d/haproxy.conf to /etc/netdata/python.d/haproxy_custom.conf
chown netdata:netdata /etc/netdata/python.d/haproxy_custom.conf

cheers!
