### ISSUE TITLE
Monitoring smartd attributes on multiple disks

### ISSUE THREAD

**Issue by skibbipl** [firehol/netdata#2889]
I have several disks on the server. I've enabed smartd logging and configured netdata to parse the cvs files. Unfortunately after restart all I can see is something like this:
![obraz](https://user-images.githubusercontent.com/4746858/31671427-3fb18d30-b35a-11e7-86fb-f39a77dd4823.png)
From what I understand each attrlog line describes each disk. Is it possible to rename `attrlog` labels to real disk names or models? Also can I exclude some disks from charts?

**Comment by l2isbad** [comment]
![screenshot_20171017_235443](https://user-images.githubusercontent.com/22274335/31672108-9af15d1a-b396-11e7-82ab-348ab9a47b30.png)

can you install and check https://github.com/firehol/netdata/pull/2872 ?

**Comment by l2isbad** [comment]
> Also can I exclude some disks from charts?

No, but it's easy to implement. 

How about space separated patterns in smartd_log.conf

```yaml
exclude: 'PATTERN1 PATTERN2'
```

Check will be simple 'if PATTERN in DISK_NAME' do not collect stats for the disk

**Comment by skibbipl** [comment]
Can I just replace python files or I have to install bleeding edge netdata from git? I use prepackaged 1.8 version from debian? Also will it be possible to display some smartd graphs in raw and some normalized? From what I can see it's not possible to mix those types currently. My netdata.conf:
```
[smartd_log.attrid5]
	units = raw
```
But graph still displays normalized data:
![obraz](https://user-images.githubusercontent.com/4746858/31672955-3654244c-b35e-11e7-911c-a9159c4ff4d6.png)

**Comment by l2isbad** [comment]
> Also will it be possible to display some smartd graphs in raw and some normalized? 

It will. After we implement it but not now 😄 

all module configuration should be in module conf file (`/opt/netdata/etc/netdata/python.d/smartd_log.conf)`

And please `ls` your smartd log dir

```
lgz@lgz-homepc[/var/log/smartd]ls
KINGSTON_SHFS37A120G-50026B7266003D93.ata.csv  ST500DM002_1BD142-Z3TW9E8F.ata.csv
```

The name is all the letters before the dot occurs. It may be bad logic in your case.

**Comment by skibbipl** [comment]
Unfortunately I failed to install newest python plugins on my current netdata by simply replacing them. It seems I need to compile netdata from source, which is not possible at the moment.
Regarding excluding disks - I guess space separated disk names are OK.
In debian smartd logs files are following this pattern:
```
# ls /var/lib/smartmontools/
attrlog.ST3500630AS-SERIAL12345.ata.csv         smartd.ST31000524AS-SERIAL12345.ata.state
```

**Comment by l2isbad** [comment]
@skibbipl 

> In debian smartd logs files are following this pattern:

it's not debian only

see `-A` option description (man smartd)

```
-A PREFIX, --attributelog=PREFIX
              Writes  smartd  attribute  information  (normalized  and raw attribute values) to files ´PREFIX´´MODEL-SERIAL.ata.csv´ or ´PREFIX´´VENDOR-MODEL-SERIAL.scsi.csv´.  At each
              check cycle attributes are logged as a line of semicolon separated triplets of the form "attribute-ID;attribute-norm-value;attribute-raw-value;".  For SCSI devices  error
              counters and temperature recorded in the form "counter-name;counter-value;" Each line is led by a date string of the form "yyyy-mm-dd HH:MM:SS" (in UTC).

              If this option is not specified, attribute information is written to files ´/var/lib/smartmontools/attrlog.MODEL-SERIAL.ata.csv´.  To disable attribute log files, specify
              this option with an empty string argument: ´-A ""´.  MODEL and SERIAL are build from drive identify information, invalid characters are replaced by underline.
```
I suggest to add -A option.

```
grep opts /etc/default/smartmontools 
#smartd_opts="--interval=1800"
smartd_opts="--interval=600 -A /var/log/smartd/"
```

Anyway it's a bug (@ktsaou ). `attrlog.MODEL-SERIAL.ata.csv` not parsed correctly

**Comment by l2isbad** [comment]
fixed in https://github.com/firehol/netdata/pull/2872 (exculde disks from data collection feature added too)

**Comment by ktsaou** [comment]
merged the fix

**Comment by skibbipl** [comment]
@l2isbad The new smartd works perfectly, however I have a suggestion - can you monitor only smartd.log files that are recently updated? I had a lot of different disks in my server and there are lot of old files in the directory. Perhaps those files can be parsed based on last modified date, let's say not older than <number_of> days? I guess it's possible to filter out old files i nthe config, but making it dynamic will allow for example to monitor external drives when they're connected to server.
