### ISSUE TITLE
Chart not found

### ISSUE THREAD

**Issue by Lallassu** [firehol/netdata#289]
Running netdata on ARM (raspberry pi 3)

Trying to get temperature data from sensors plugin. Got this error when setting the data-netdata to "sensors.temp_thermal_zone0_thermal_thermal_zone0":

sensors.temp_thermal_zone0_thermal_thermal_zone0: chart not found on url "/api/v1/chart?chart=sensors.temp_thermal_zone0_thermal_thermal_zone0"

It does exists on the system: 
$ ls /var/cache/netdata/sensors.temp_thermal_zone0_thermal_thermal_zone0/
main.db                                            sys_devices_virtual_thermal_thermal_zone0_temp.db

And going to the url shows that it does exist:
http://192.168.1.150:19999/api/v1/chart?chart=sensors.temp_thermal_zone0_thermal_thermal_zone0

    {
    "id": "sensors.temp_thermal_zone0_thermal_thermal_zone0",
    "name": "sensors.temp_thermal_zone0_thermal_thermal_zone0",
    "type": "sensors",
    "family": "temperature",
    "context": "sensors.temp",
    "title": "thermal_zone0 Temperature (sensors.temp_thermal_zone0_thermal_thermal_zone0)",
    "priority": 90001,
    "enabled": true,
    "units": "Celsius",
    "data_url": "/api/v1/data?chart=sensors.temp_thermal_zone0_thermal_thermal_zone0",
    "chart_type": "line",
    "duration": 3600,
    "first_entry": 1461177473,
    "last_entry": 1461181073,
    "update_every": 1,
    "dimensions": {
        "sys_devices_virtual_thermal_thermal_zone0_temp": {
            "name": "temp"
        }
     }
    }

Is this some bug or am I doing something wrong here?

**Comment by ktsaou** [comment]
If you press F12 on your browser, you can see the URL your dashboard attempts to fetch.
Can you post it here?

**Comment by Lallassu** [comment]
Oh I just checked my code and you are right. I forgot to change the data source from my other server where I tried it on first, which also have netdata so the data steam was still flowing making me believe that it actually failed on my rpi. Haven't had the chance to switch it yet but I'm certain that this is the problem.

Sorry for this and keep up the good work!
