### ISSUE TITLE
Netdata Version g396337e5 breaks streaming to master on OSX

### ISSUE THREAD

**Issue by GitStoph** [firehol/netdata#2890]
Two broken caching servers attempting to stream netdata metrics:
OSX:
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: MacHD
      Boot Mode: Normal
      Computer Name: Server4
      User Name: adminuser (adminuser)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1:07
```
Netdata:
```
$ ~/opt/netdata/usr/sbin/netdata -version
netdata 1.8.0-180-g396337e5_rolling
```
OSX (working client):
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: MacHD
      Boot Mode: Normal
      Computer Name: Server2
      User Name: adminuser (adminuser)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 15 days 2 minutes
```
Netdata (working client):
```
$ ~/opt/netdata/usr/sbin/netdata -version
netdata 1.8.0-84-g57efe2e5_rolling
```

Noticed the issue originally on one server. Completely reinstalled netdata. Netdata would work IF it was set to run standalone. The second I set it up to stream, one of the CPU's would peg at max and no metrics would ever be sent correctly. Validated on a second server where no configs were changed, the only thing that was done was a netdata update. Been looking through the error logs and nothing is standing out as a potential cause. 
Working on a pastebin of the error log.
*Edit* - https://pastebin.com/X3JK0xPT pastebin of the full error log. How else can I help?

**Comment by ktsaou** [comment]
Please update the master too.
There have been new developments ( #2688 )  on the streaming protocol, so newer slaves require newer masters too.

**Comment by GitStoph** [comment]
The master was running the latest version of netdata at the time. 
```
$ netdata -version
netdata 1.8.0-141-g396337e_rolling
``` 
(On the master)

**Comment by ktsaou** [comment]
To understand the issue, I need the log of the master. It should log something like "ERROR: PLUGINSD ...description of the error... Disabling it."

Can you post a few such lines from the master?

**Comment by ktsaou** [comment]
The master should be later or equal to `netdata 1.8.0-180-g396337e5_rolling`.
So your master is old.

**Comment by GitStoph** [comment]
That's interesting, because I ran the updater a couple times while troubleshooting and it insisted that there were no new versions to update to.. Is that a bug with the updater potentially? I just updated again today and the issue still persists.
Master:
```
$ netdata -v
netdata 1.8.0-190-g1e11e62_rolling
```
Non-working OSX slave:
```
$ ~/opt/netdata/usr/sbin/netdata -v
netdata 1.8.0-190-g1e11e622_rolling
```

Both were updated within seconds of each other. I updated the master first. I see again that the numbers do not match exactly. I ran the updater again with the -f flag, and again they both resulted in the above versioning.

https://pastebin.com/K9Y2yEsH - a pastebin from the master as requested

**Comment by ktsaou** [comment]
> I ran the updater a couple times while troubleshooting and it insisted that there were no new versions to update to.. Is that a bug with the updater potentially?

Did you update with the updater? It only runs a `git pull`, so this might be something related to github...

---

In the logs you posted I see:

```
2017-10-18 14:21:56: netdata ERROR: PLUGINSD: <server.4.ip.address>:51673 : read failed.
2017-10-18 14:21:56: netdata ERROR: STREAM <Server4> [receive from [<server.4.ip.address>]:51673]: disconnected (completed 0 updates).
2017-10-18 14:21:56: netdata ERROR: PLUGINSD: <server.4.ip.address>:51769 : read failed.
2017-10-18 14:21:56: netdata ERROR: STREAM <Server4> [receive from [<server.4.ip.address>]:51769]: disconnected (completed 0 updates).
```

But I can't find its connection. Ideally I would need a complete session (connection to disconnection) to find out what happens. Keep in mind though, that just from the messages above I see that master believes the slave was disconnected by itself. On your previous logs (from the slave), I see:

```
2017-10-17 11:00:46: netdata ERROR: STREAM <Server4> [send]: not ready - discarding collected metrics. (errno 60, Operation timed out)
```

So, it seems you have some kind of networking issue between these two (yes, I know these are not logs from the same session - so I might be wrong).

In general it would help if you could run the following on both servers and provide the logs of just a few complete sessions (from connection to disconnection):

```
tail -f /var/log/netdata/error.log | grep -E "(PLUGINSD|STREAM)"
```

**Comment by GitStoph** [comment]
From the master:
```
$ tail -f /var/log/netdata/error.log | grep -E "(PLUGINSD|STREAM)"


2017-10-20 12:05:23: netdata ERROR: PLUGINSD: 10.2.1.13:55200 : read failed.
2017-10-20 12:05:23: netdata ERROR: STREAM AppleCache4 [receive from [10.2.1.13]:55200]: disconnected (completed 0 updates).
2017-10-20 12:05:23: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55200]: receive thread ended (task id 3691)
2017-10-20 12:05:33: netdata INFO : STREAM [receive from [10.2.1.13]:55397]: new client connection.
2017-10-20 12:05:33: netdata INFO : STREAM AppleCache4 [10.2.1.13]:55397: receive thread created (task id 4526)
2017-10-20 12:05:33: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55397]: initializing communication...
2017-10-20 12:05:33: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55397]: receiving metrics...
```
Entire error log of the slave after a complete reinstall of netdata, fixing the stream conf, and restarting netdata to begin streaming.
[error.log](https://github.com/firehol/netdata/files/1402743/error.log)

I also completely reinstalled netdata on the master just before the slave. Now `netdata -version` yields `netdata 1.8.1_rolling`. From the browser i can see that it is `7ce25e3`. `netdata -version` on the slave yields `netdata 1.8.0-200-g7ce25e35_rolling`. How can this be? I've verified that I'm running the latest version of git on the server & the slave? 

Interestingly, I killed and restarted netdata again on the slave while still tailing on the master. I saw this:
```
2017-10-20 12:19:44: netdata ERROR: PLUGINSD: 10.2.1.13:55397 : read failed.
2017-10-20 12:19:44: netdata ERROR: STREAM AppleCache4 [receive from [10.2.1.13]:55397]: disconnected (completed 0 updates).
2017-10-20 12:19:44: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55397]: receive thread ended (task id 4526)
2017-10-20 12:20:13: netdata INFO : STREAM [receive from [10.2.1.13]:55520]: new client connection.
2017-10-20 12:20:13: netdata INFO : STREAM AppleCache4 [10.2.1.13]:55520: receive thread created (task id 14416)
2017-10-20 12:20:13: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55520]: initializing communication...
2017-10-20 12:20:13: netdata INFO : STREAM AppleCache4 [receive from [10.2.1.13]:55520]: receiving metrics...
```
It appears that one start of netdata actually attempted to send two different streams? Or is the second one a retry?

**Comment by GitStoph** [comment]
I apparently may have stumbled on a fix.. maybe you can explain to my why this works? 
In netdata.conf
```
         web files owner = <myadminuser>
         web files group = <myadmingroup>
```
By default, these values were set to `root` and `wheel`, which likely would have conflicted with the UID of the ubuntu netdata master's idea of who root and wheel are?

**Comment by ktsaou** [comment]
So, you say that with `memory mode = none` the macOS slave enters an infinite loop, but with `memory mode = ram` it works?

**Comment by GitStoph** [comment]
@ktsaou Correct. Technically i used `memory mode = save`, but it seemed like for some reason that w/o a local database existing, it'd refuse to stream anything forward. Seems like the issue began the day I made the issue here with that version update. There shouldn't have been anything run to change the brew installed utilities or OSX updates, so I'd believe it to be something that changed in netdata's code? Not sure what that may be. I do know that this currently works as a fix however, and they're currently still running without any issues.

**Comment by ktsaou** [comment]
oops! this was a bug.
Fixed it in #2914

**Comment by ktsaou** [comment]
merged it.
You can now return to `memory mode = none`.

**Comment by ktsaou** [comment]
thank you for reporting this!

**Comment by GitStoph** [comment]
Confirmed this is now working again. Thanks for fixing!
