### ISSUE TITLE
Alerts threshold change

### ISSUE THREAD

**Issue by steveharder** [firehol/netdata#2891]
Hi I would like to change CPU warning and critical threshold from 75 to 30 .
Once I do  in /etc/netdata/health.d/cpu.conf and restart netdata service, I still see in the web GUI the old settings, nor I get no notifications when testing the new settings.
I have Netdata version 1.6.1 installed.

Thanks,

**Comment by ktsaou** [comment]
Please update your netdata. The version you have is ancient !
Please also post this screenshot from your netdata:

![screenshot from 2017-10-19 23-54-12](https://user-images.githubusercontent.com/2662304/31793777-e034f790-b528-11e7-8bd1-36605acc16c9.png)

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
