### ISSUE TITLE
RAM Graph hangs w/ FreeBSD

### ISSUE THREAD

**Issue by vaadm** [firehol/netdata#2896]
The graph of RAM hangs and locks on my FreeBSD servers as the size of the buffers increase. In some cases it takes about a minute for buffers to grow to 2041 and then the realtime graphing hangs and halts.

**Comment by ktsaou** [comment]
Hi,

I am not sure I understand. What do you mean "locks", "hangs" and "halts"? Will a screenshot help?

cc @vlvkobal

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
