### ISSUE TITLE
Not receiving alarms from all netdata instances

### ISSUE THREAD

**Issue by steveharder** [firehol/netdata#2899]
Hi,

I have about 10 Linux VMs installed with Netdata, at some point some of the VMs stopped sending alerts out and I'm not receiving email notifications from them.
When I run the test alarm "/usr/libexec/netdata/plugins.d/alarm-notify.sh test"
it fails to send from the specific VM, but if I change the account from "root"  in "/etc/netdata/health_alarm_notify.conf" and sends the test to my 
office365 email ( just like how it is in the master netdata sends emails from, with this email account via sendmail)
it seems to send the test mail but not any other new generated alerts (from the problematic VM)

Thanks,

**Comment by ktsaou** [comment]
Hi,

I think this is related to the configuration of your email server. I suggest to examine the mail server logs to find out what is happening and why these emails are rejected.

Keep in mind you can set the sender of the emails [here](https://github.com/firehol/netdata/blob/970b605121f5301a0c6d38352a175d32efde9c3b/conf.d/health_alarm_notify.conf#L105).

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
