### ISSUE TITLE
Gradient color problem

### ISSUE THREAD

**Issue by fabiocpv** [firehol/netdata#2902]
Hello, i'm trying to put gradient color on gauges but i'm not able to do:

			div data-netdata="system.cpu"
                        data-host="http://xxx/netdata/server5/"
                        data-common-max="system.cpu"
                        data-decimal-digits="0.0"
                        data-title="System CPU"
			data-chart-library="gauge"
                        data-gauge-max-value="100"
			data-gauge-generate-gradient="[0, 70, 100]"
			data-gauge-gradient-percent-color-0="#4fce00"
			data-gauge-gradient-percent-color-70="#ffb200"
			data-gauge-gradient-percent-color-100="#ff0000"
                        data-units="%"
                        data-width="9%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        /div

With or without the options, the chart stay with the same default color, its only changes if i put data-colors="#228B22" but its static and not dynamic like i wanted...

**Comment by gaohailang** [comment]
I think this is bug in `NETDATA.gaugeChartCreate` function. 
`if (generateGradient.constructor === Array) `,  However `generateGraident` is boolean value,  So the code should be ` if (NETDATA.dataAttribute(state.element, 'gauge-generate-gradient', false).constructor === Array) {`
      
As the code shown below:
```js
        var generateGradient = NETDATA.dataAttributeBoolean(state.element, 'gauge-generate-gradient', false);

        .....
        .....

        if (generateGradient.constructor === Array) {
            // example options:
            // data-gauge-generate-gradient="[0, 50, 100]"
            // data-gauge-gradient-percent-color-0="#FFFFFF"
            // data-gauge-gradient-percent-color-50="#999900"
            // data-gauge-gradient-percent-color-100="#000000"

            options.percentColors = [];
            var len = generateGradient.length;
            while(len--) {
```

![image](https://user-images.githubusercontent.com/697853/32315212-3d15406a-bfe6-11e7-8566-b4179c059d14.png)
![image](https://user-images.githubusercontent.com/697853/32315224-497d4816-bfe6-11e7-8f88-0a58a8cd1e8e.png)

**Comment by ktsaou** [comment]
Thanks! you are right!

**Comment by fabiocpv** [comment]
thanks.
