### ISSUE TITLE
web_log plugin should be able to read json logs

### ISSUE THREAD

**Issue by michael-niemand** [firehol/netdata#2903]
We have configured our nginx to put out all access logs in json format. 
I tried to configure the web_log plugin to read json logs, but without success. One could probably create a regex to parse the json into fields as a custom format, but I expect this to create a lot of load. 
So it'd be great to just be able to set a "type: nginx_json" and be done with it ...

**Comment by l2isbad** [comment]
Well,  you can configure the logging in two different files using a different format.

```
 access_log  /log/access.log  json;
 access_log  /log/access_netdata.log  netdata;
```

**Comment by michael-niemand** [comment]
That's the way I have done it now.
