### ISSUE TITLE
a guide for how to debug plugin's operation

### ISSUE THREAD

**Issue by donghwicha** [firehol/netdata#2905]
Hello. I'm trying to use certain plugins on netdata,
but I couldn't find any document how I can find if it is working or not using its log.

I know that there is log file "/var/log/netdata/error.log",
but it says as below and I can't see whole log file. 

> "python.d.plugin: throttling further log messages for 1035 seconds"

Furthermore,  the log lines are somewhat misleading cause it says Error for checking the existence of monitoring target and it is not the error runtime of plugin or agent. 

> 2017-10-21 01:42:45: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfsd' (errno 2, No such file or directory)
> 2017-10-21 01:42:45: netdata ERROR: PROCFILE: Cannot open file '/proc/net/rpc/nfs' (errno 2, No such file or directory)

I'm sorry if this is duplicate 
but please point me any document how I can debug plugins on netdata daemon.

**Comment by donghwicha** [comment]
I found out that the message below is related with a constant value on python

> "python.d.plugin: throttling further log messages for 1035 seconds"

> https://github.com/firehol/netdata/blob/master/python.d/python_modules/msg.py#L43

Would there be any work around for this? I want to see all the logs.

**Comment by l2isbad** [comment]
> Would there be any work around for this? I want to see all the logs.

fixed in https://github.com/firehol/netdata/pull/2872

> but please point me any document how I can debug plugins on netdata daemon.

for all [python.d](https://github.com/firehol/netdata/tree/master/python.d) modules
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by donghwicha** [comment]
Thanks @l2isbad and could you also point me where I can find how to disable all of the monitoring metrics?

As my original message was about log of plugin, not about how to use plugin,
it would be greatly helpful for me to proceed.

**Comment by l2isbad** [comment]
> where I can find how to disable all of the monitoring metrics?
`netdata.conf`
`python.d.conf`

what exactly do you want?

**Comment by donghwicha** [comment]
@l2isbad  oops. I think I overlooked the line below on the link you shared.
Thanks and I will go on. I'm closing this thread. 

>/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
