### ISSUE TITLE
Illegal instruction - Debian Stretch i586

### ISSUE THREAD

**Issue by AWoodley** [firehol/netdata#2909]
Having trouble getting netdata started on my Soekris Net5501 running Debian Stretch. I've the Debian packages, the single-line-install script, and building manually from a recent git pull.

```
root@Clacks:~/netdata# /opt/netdata/usr/sbin/netdata -D
Illegal instruction
```

```
root@Clacks:~/netdata# dmesg |grep netdata
[ 1612.507011] traps: netdata[9691] trap invalid opcode ip:44caef sp:bfb24e20 error:0
[ 1612.507060]  in netdata[438000+c9000]
```

```
root@Clacks:~/netdata# strace /opt/netdata/usr/sbin/netdata -D
...
open("/opt/netdata/var/lib/netdata/health/health-log.db", O_WRONLY|O_CREAT|O_APPEND, 0666) = 6
_llseek(6, 0, [0], SEEK_END)            = 0
close(6)                                = 0
open("/opt/netdata/var/lib/netdata/health/health-log.db", O_WRONLY|O_CREAT|O_APPEND, 0666) = 6
_llseek(6, 0, [0], SEEK_END)            = 0
open("/opt/netdata/etc/netdata/health.d", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 7
fstat64(7, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
getdents(7, /* 40 entries */, 32768)    = 968
open("/opt/netdata/etc/netdata/health.d/lighttpd.conf", O_RDONLY) = 8
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x4ceaef} ---
+++ killed by SIGILL +++
Illegal instruction
```

```
root@Clacks:~/netdata# uname -a
Linux Clacks 4.9.0-4-686 #1 SMP Debian 4.9.51-1 (2017-09-28) i586 GNU/Linux
```

**Comment by AWoodley** [comment]
A little more info; I spun up an install in Virtualbox, using the same preseed as was used to install the Net5501. I then installed netdata from stretch-backports and it worked without issue.

This leads me to believe that the issue is with the CPU in the Net5501; its an AMD Geode version 5.10.2.

**Comment by AWoodley** [comment]
root@Clacks:~# cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 5
model		: 10
model name	: Geode(TM) Integrated Processor by AMD PCS
stepping	: 2
cpu MHz		: 499.911
cache size	: 128 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 1
wp		: yes
flags		: fpu de pse tsc msr cx8 sep pge cmov clflush mmx mmxext 3dnowext 3dnow eagerfpu 3dnowprefetch vmmcall
bugs		: sysret_ss_attrs
bogomips	: 999.82
clflush size	: 32
cache_alignment	: 32
address sizes	: 32 bits physical, 32 bits virtual
power management:

**Comment by AWoodley** [comment]
The invalid instructions are in the SSE instruction set, which AMD Geodes don't have.

A work-around is to configure with --disable-x86-sse. Could this be incorporated into some form of automatic detection in the configure script?

**Comment by ktsaou** [comment]
Hi,

it seems there is something: http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_x86_features.m4

I'll try it tomorrow and post here.

**Comment by AWoodley** [comment]
Include --disable-x86-sse when you call _configure_.

If you're rebuiliding the Debian package, add it to _override_dh_auto_configure_ in debian/rules:

```
--- netdata-1.6.0/debian/rules	2017-07-16 03:15:59.000000000 +0800
+++ netdata-1.6.0+dfsg-disable-x86-sse/debian/rules	2017-10-25 20:38:17.614408229 +0800
@@ -25,7 +25,7 @@
 	#dh $@ --with autoreconf
 
 override_dh_auto_configure:
-	dh_auto_configure -- --with-math
+	dh_auto_configure -- --with-math --disable-x86-sse
 
 override_dh_auto_build:
 	dh_auto_build --parallel
```

**Comment by ChuckWhitson** [comment]
Thanks @AWoodley

**Comment by ChuckWhitson** [comment]
After rebuilding with --disable-x86-sse, the service doesn't even start now.

**Here is what is in my debian/rules:**
override_dh_auto_configure:
        # dh_auto_configure -- --with-math --with-webdir=/var/lib/netdata/www
        dh_auto_configure -- --with-math --with-webdir=/var/lib/netdata/www --disable-x86-sse

**I notice that when ./configure is called here is its parameters:**
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=ne                                                                                                                      tdata CFLAGS=-O2

● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Thu 2018-05-03 23:08:51 UTC; 14s ago
  Process: 19344 ExecStart=/usr/sbin/netdata -P /run/netdata/netdata.pid -D (code=killed, signal=ILL)
  Process: 19341 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 19337 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 19344 (code=killed, signal=ILL)

May 03 23:08:51 SOEKRIS_5501_01 systemd[1]: netdata.service: Main process exited, code=killed, status=4/ILL
May 03 23:08:51 SOEKRIS_5501_01 systemd[1]: netdata.service: Unit entered failed state.
May 03 23:08:51 SOEKRIS_5501_01 systemd[1]: netdata.service: Failed with result 'signal'.

**Comment by ktsaou** [comment]
@alonbl when netdata is compiled on an AMD Geocode CPU it crashes with SIGILL. The configure option `--disable-x86-sse` does not help (netdata does not even start).

Any ideas what configure options are needed to compile on older CPUs?

**Comment by ktsaou** [comment]
btw, I tried compiling netdata on a VM with cpu set to `pentium2` (i586) and netdata compiled and run with the default settings, but I guess this is not a valid test, since the host CPU was core i7 and probably was able to run all the cpu instructions offered to it.

**Comment by ktsaou** [comment]
I managed to reproduce this on a VM running knoppix 8.1 on an i486 cpu.
However, when added `--disable-x86-sse` netdata run perfectly.

With PR #3692 I added the option `--disable-x86-sse` to `netdata-installer.sh` (which also works with `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-x86-sse`.

btw, to install netdata on knoppix 8.1, you need to copy uuid.h from another machine. Run these:

```sh
# create the missing directory
sudo mkdir /usr/include/uuid

# copy the missing header file from another linux
sudo scp user@another.linux.machine:/usr/include/uuid/uuid.h /usr/include/uuid/

# copy the missing library from the knoppix CD to its location
sudo cp /KNOPPIX/lib/i386-linux-gnu/libuuid.so.1 /usr/lib/libuuid.so

# install netdata
# packages update will fail, but press ENTER to proceed building and installing netdata
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --libs-are-really-here --disable-x86-sse
```

**Comment by ChuckWhitson** [comment]
I can confirm that rebuilding with < PR [#3692](https://github.com/firehol/netdata/pull/3692) and running ./netdata-installer.sh with --disable-x86-sse seems to work around the issue.

I noticed at least when ./configure was was called it was listed:
[/tmp/netdata]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata **--disable-x86-sse** CFLAGS=-O2

For some reason, modifying my debian/rules didn't take and I tried multiple times to confirm I wasn't doing something wrong.

**Comment by ktsaou** [comment]
@AWoodley does it work for you?

**Comment by AWoodley** [comment]
@ktsaou I just re-tested my patch and it works ok. After apply the patch I ran dpkg-buildpackage -b, and confirmed in the log that disable-x86-sse is include in the arguments passed to configure.

```
root@Hex:/usr/src/temp/netdata-1.6.0+dfsg# grep disable-x86-sse config.log
  $ ./configure --build=i686-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/i386-linux-gnu --libexecdir=${prefix}/lib/i386-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-math --disable-x86-sse
```

Check the resulting Makefile to confirm that sse2 has been disabled.

With SSE2:
```CFLAGS = -g -O2 -fdebug-prefix-map=/usr/src/temp/netdata-1.6.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -O3 -pthread -msse2 -mfpmath=sse -flto```

Without SSE2:
```CFLAGS = -g -O2 -fdebug-prefix-map=/usr/src/temp/netdata-1.6.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -O3 -pthread -flto```

Note the missing ```-msse2 -mfpmath=sse```.

**Comment by alonbl** [comment]
Hi,
I guess everything turned out ok, or anything I can help?
Alon

**Comment by ktsaou** [comment]
Thank you @alonbl 
Everything seems to be working ok.

One question: Ideally, I would like this to be automated somehow, ie configure.ac to detect it should not enable sse.

I found this: http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_check_x86_features.m4

But I am afraid to use it. This adds a lot more flag, depending on the CPU of the system. This may break a lot of things (like packages that are distributed in binary and are expected to work on a broad range of processors). So, I preferred not to use it.

One solution could be to add a `--enable-cpu-features` flag or something similar, that could enable this.

What do you think?

**Comment by alonbl** [comment]
the problem when automatic enable of cpu features during build is that the software may require to run on different host. This is why we tend not to auto-detect optimization setting but have them explicitly enabled.

It can be automated, see below:
```
cpp -dM /dev/null -march=native | grep SSE
cpp -dM /dev/null | grep SSE
```
I do not like this, it makes downstream task harder than explicit. You can add --enablexxx=auto to apply the logic but still accept explicit yes/no (disable/enable) to override.

The other option is to build always with sse support and check at runtime using __builtin_cpu_supports and have conditional.

**Comment by ktsaou** [comment]
ok, thanks. I'll leave it like it is now.

**Comment by csamsel** [comment]
Although this has been closed, i'd like to add something. Has someone actually tried if e.g. SSE / `--march=native` gives a meaningful improvement for netdata? If not, you could just always use `--march=i586`

**Comment by FedericoCeratto** [comment]
Related bug in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879765
