### ISSUE TITLE
any retention rule for metric data stored on influxdb?

### ISSUE THREAD

**Issue by donghwicha** [firehol/netdata#2911]
Hello.
I need to keep the database as small as possible so that there is no burden on management of influxdb,
but at the same time I need to keep the monitoring data at least 1 week. 

The first solution I come up with is downsampling stored data. But the database of netdata has so many tables,
so is there any document for netdata database where I can find how to create some queries for this? 
https://docs.influxdata.com/influxdb/v1.3/guides/downsampling_and_retention/

Or, to make it very simple, is there anyway I can remove whole data of netdata database every 1 week?

**Comment by ktsaou** [comment]
Hi,

I am sorry, I don't know. The document you posted does not provide any means for managing retention across a large number of metrics.

A simple solution would be to push only the metrics you really need, by filtering them at netdata. This is done with `send charts matching = *` option in netdata.conf. You can give there a space separated list of the charts you need.

If anyone else knows how to properly manage retention on infludb, please help...

**Comment by vbonline** [comment]
CREATE RETENTION POLICY "one_week_only" ON "your_databas_name" DURATION 7d REPLICATION 1 DEFAULT
