### ISSUE TITLE
Dashboard for 20 servers

### ISSUE THREAD

**Issue by harshainukollu** [firehol/netdata#2912]
HI,

I have 20 centos servers.I want to monitor all the 20 servers CPU,Swap etc in a single dashboard(netdata).

Is it possible?

Regards,
Harsha

**Comment by fabiocpv** [comment]
yes, use web/tv.html

**Comment by harshainukollu** [comment]
I have this configuration file in tv.html.
<!DOCTYPE html>
<html lang="en">
<head>
    <title>NetData TV Dashboard</title>
    <meta name="application-name" content="netdata">

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <meta property="og:locale" content="en_US" />
    <meta property="og:image" content="https://cloud.githubusercontent.com/assets/2662304/22945737/e98cd0c6-f2fd-11e6-96f1-5501934b0955.png"/>
    <meta property="og:url" content="http://my-netdata.io/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="netdata"/>
    <meta property="og:title" content="netdata - real-time performance monitoring, done right!"/>
    <meta property="og:description" content="Stunning real-time dashboards, blazingly fast and extremely interactive. Zero configuration, zero dependencies, zero maintenance." />

</head>
<script>
// this section has to appear before loading dashboard.js

// Select a theme.
// uncomment on of the two themes:

// var netdataTheme = 'default'; // this is white
var netdataTheme = 'slate'; // this is dark


// Set the default netdata server.
// on charts without a 'data-host', this one will be used.
// the default is the server that dashboard.js is downloaded from.

// var netdataServer = 'http://my.server:19999/';
</script>



<script type="text/javascript" src="dashboard.js?v20170724-7"></script>

<script>
// Set options for TV operation
// This has to be done, after dashboard.js is loaded

// destroy charts not shown (lowers memory on the browser)
NETDATA.options.current.destroy_on_hide = true;

// set this to false, to always show all dimensions
NETDATA.options.current.eliminate_zero_dimensions = true;

// lower the pressure on this browser
NETDATA.options.current.concurrent_refreshes = false;

// if the tv browser is too slow (a pi?)
// set this to false
NETDATA.options.current.parallel_refresher = true;

// always update the charts, even if focus is lost
// NETDATA.options.current.stop_updates_when_focus_is_lost = false;

// Since you may render charts from many servers and any of them may
// become offline for some time, the charts will break.
// This will reload the page every RELOAD_EVERY minutes

var RELOAD_EVERY = 5;
setTimeout(function(){
    location.reload();
}, RELOAD_EVERY * 60 * 1000);

</script>
<body>

<div style="width: 100%; text-align: center; display: inline-block;">

    <div style="width: 100%; height: 24vh; text-align: center; display: inline-block;">
        <div style="width: 100%; height: 15px; text-align: center; display: inline-block;">
            <b>CPU On both servers</b>
        </div>
        <div style="width: 100%; height: calc(100% - 15px); text-align: center; display: inline-block;">
            <br/>
            <div data-netdata="system.cpu"
                    data-host="http://registry.my-netdata.io"
                    data-title="CPU usage of registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    data-dygraph-valuerange="[0, 100]"
                    ></div>
            <div data-netdata="system.cpu"
                    data-title="CPU usage of your netdata server"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    data-dygraph-valuerange="[0, 100]"
                    ></div>
        </div>
    </div>


    <div style="width: 100%; height: 24vh; text-align: center; display: inline-block;">
        <div style="width: 100%; height: 15px; text-align: center; display: inline-block;">
            <b>Disk I/O on both servers</b>
        </div>
        <div style="width: 100%; height: calc(100% - 15px); text-align: center; display: inline-block;">
            <div data-netdata="system.io"
                    data-host="http://registry.my-netdata.io"
                    data-common-max="io"
                    data-common-min="io"
                    data-title="I/O on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>
            <div data-netdata="system.io"
                    data-title="I/O on your netdata server"
                    data-common-max="io"
                    data-common-min="io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>
        </div>
    </div>


    <div style="width: 100%; height: 24vh; text-align: center; display: inline-block;">
        <div style="width: 100%; height: 15px; text-align: center; display: inline-block;">
            <b>IPv4 traffic on both servers</b>
        </div>
        <div style="width: 100%; height: calc(100% - 15px); text-align: center; display: inline-block;">
            <div data-netdata="system.ipv4"
                    data-host="http://registry.my-netdata.io"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-title="IPv4 traffic on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>
            <div data-netdata="system.ipv4"
                    data-title="IPv4 traffic on your netdata server"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>
        </div>
    </div>

    <div style="width: 100%; height: 23vh; text-align: center; display: inline-block;">
        <div style="width: 100%; height: 15px; text-align: center; display: inline-block;">
            <b>Netdata statistics on both servers</b>
        </div>
        <div style="width: 100%; max-height: calc(100% - 15px); text-align: center; display: inline-block;">
            <div style="width: 49%; height:100%; align: center; display: inline-block;">
                registry.my-netdata.io
                <br/>
                <div data-netdata="netdata.requests"
                        data-host="http://registry.my-netdata.io"
                        data-common-max="netdata-requests"
                        data-decimal-digits="0"
                        data-title="Chart Refreshes/s"
                        data-chart-library="gauge"
                        data-width="20%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
                <div data-netdata="netdata.clients"
                        data-host="http://registry.my-netdata.io"
                        data-common-max="netdata-clients"
                        data-decimal-digits="0"
                        data-title="Sockets"
                        data-chart-library="gauge"
                        data-width="20%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        data-colors="#AA5500"
                        ></div>
                <div data-netdata="netdata.net"
                        data-dimensions="in"
                        data-common-max="netdata-net-in"
                        data-decimal-digits="0"
                        data-host="http://registry.my-netdata.io"
                        data-title="Requests Traffic"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
                <div data-netdata="netdata.net"
                        data-dimensions="out"
                        data-common-max="netdata-net-out"
                        data-decimal-digits="0"
                        data-host="http://registry.my-netdata.io"
                        data-title="Chart Data Traffic"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
            </div>
            <div style="width: 49%; height:100%; align: center; display: inline-block;">
                your netdata server
                <br/>
                <div data-netdata="netdata.requests"
                        data-title="Chart Refreshes/s"
                        data-common-max="netdata-requests"
                        data-decimal-digits="0"
                        data-chart-library="gauge"
                        data-width="20%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
                <div data-netdata="netdata.clients"
                        data-common-max="netdata-clients"
                        data-decimal-digits="0"
                        data-title="Sockets"
                        data-chart-library="gauge"
                        data-width="20%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        data-colors="#AA5500"
                        ></div>
                <div data-netdata="netdata.net"
                        data-dimensions="in"
                        data-common-max="netdata-net-in"
                        data-decimal-digits="0"
                        data-title="Requests Traffic"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
                <div data-netdata="netdata.net"
                        data-dimensions="out"
                        data-common-max="netdata-net-out"
                        data-decimal-digits="0"
                        data-title="Chart Data Traffic"
                        data-chart-library="easypiechart"
                        data-width="15%"
                        data-height="100%"
                        data-after="-300"
                        data-points="300"
                        ></div>
            </div>
        </div>
    </div>
</div>
</body>
</html>



How to add remaining 19 servers ip or hostname in this configuration file?

Regards,
Harsha

**Comment by fabiocpv** [comment]
use the: data-host="http://registry.my-netdata.io" for each server you want

**Comment by harshainukollu** [comment]
I can't get you. Can you please explain clearly how to setup.

TIA.

**Comment by ktsaou** [comment]
A chart is this:

```html
            <div data-netdata="system.ipv4"
                    data-host="http://registry.my-netdata.io"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-title="IPv4 traffic on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>
```

The `data-host` attribute, defines the server the chart will come from.

The idea is to design page with simple boxes (`div`s) in any arrangement you like, using standard HTML. Then, once you have a page with `div`s positioned the way you like it, adding these attributes to them, netdata will turn them to charts.

**Comment by harshainukollu** [comment]
Where should in add the second server?
I have these servers:192.168.1.2,192.168.1.3------192.168.1.20

Regards,
Harsha

**Comment by fabiocpv** [comment]
<div data-netdata="system.ipv4"
                    data-host="http://192.168.1.2:9999"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-title="IPv4 traffic on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>

            <div data-netdata="system.ipv4"
                    data-host="http://192.168.1.3:9999"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-title="IPv4 traffic on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>

            <div data-netdata="system.ipv4"
                    data-host="http://192.168.1.3:9999"
                    data-common-max="traffic"
                    data-common-min="traffic"
                    data-title="IPv4 traffic on registry.my-netdata.io"
                    data-chart-library="dygraph"
                    data-width="49%"
                    data-height="100%"
                    data-after="-300"
                    ></div>

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.

**Comment by rasmusdencker** [comment]
@ktsaou Let me know if it's more appropriate to open a new issue instead of reopening this. This is also related to #218.

**Main question:** How would you go about doing this for an ephemeral node setup where the hosts vary by the hour? 

The topo is very simple; 1 master and _n_ auto-scaling headless slaves streaming to the master. 

My initial thought was to create a graph template, then dynamically generate the DOM altering the `data-host` attribute from an array of hostnames (`data-host="http://mynetstat:19999/host/[DYNAMIC]"`); this would be done on each reload. 

However, this approach proposes the need for retrieving a list of hosts currently known by the master, potentially filtering the 'dead' ones out (the ones that have not reported data for the last half hour for example), and after trawling through the docs and issues, it seems that it's not really possible to get such a list.

The 'hack' would be to create a JSON API which returns a list of currently alive hostnames from the mechanism controlling the auto-scaling, which would give a much more precise list.

How would you suggest going about this? Is it possible to achieve with the current codebase?

## Extra goodies: Dream scenario

Just scribbling down my thoughts. Imagine that each slave supported sending metadata describing themselves while establishing the stream connection with arbitrary key-value pairs prefixed with the `meta` keyword:

*stream.conf*
```
[stream]
    enabled = yes
    destination = the-master:19999
    api key = ...
    meta role = web
    meta displayname = webserver30
```

The dashboard would then support the following syntax with the new `data-master`, `data-host-meta-*` and `data-host-alivethreshold` attributes (the latter controlling the maximum amount of time to have passed since the last 'ping' from the host for it to be considered). Also, in this scenario (not necessarily a part of a mvp), it's possible to use placeholders in the `data-title` attribute.

```
<div data-netdata="disk_space._"
                data-master="http://192.168.1.3:9999"
                data-host-meta-role="web"
                data-host-alivethreshold="-30m"
                data-title="Root disk space on {host.meta.displayname}"
                 ....
                ></div>
```

The above would then generate one chart per matching host.
