### ISSUE TITLE
Automatic disk space monitoring configuration

### ISSUE THREAD

**Issue by HackToHell** [firehol/netdata#2916]
Hey!

We use docker with lvm, the disks are attached by kubernetes, so it's dynamic in nature, the problem is how do I enforce a config for all the new disks, say I want to enable space and inode monitoring for them. In the config file it's hundreds of lines of 
```
[plugin:proc:diskspace:/var/lib/origin/openshift.local.volumes/pods/963b10b3-728e-11e7-b7db-42010a920006/volumes/kubernetes.io~secret/server-certificate]
	# space usage = no
	# inodes usage = no
```

Is there a way to blanket force space usage etc ?

**Comment by ktsaou** [comment]
Hi,

yes this:

```
[plugin:proc:diskspace]
	# remove charts of unmounted disks = yes
	# update every = 1
	# check for new mount points every = 15
	# exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
	# exclude space metrics on filesystems = 
	# space usage for all disks = auto
	# inodes usage for all disks = auto
```

netdata will automatically switch the settings to `no` for any mount point it fails to `stat()` (i.e. does not have permission to check, or the path does not lead to a directory).

I think in your case, it does not have permission to `stat()` them, so you may need to add user `netdata` to a group that has access to these directories.

**Comment by ktsaou** [comment]
You should have logs about it, like this:

```
DISKSPACE: Cannot stat() mount point '%s' (disk '%s', filesystem '%s', root '%s')."
```

**Comment by HackToHell** [comment]
Ah thank you I did indeed find it and I was able to fix it :+1:
