### ISSUE TITLE
Quality of Service - lower values and higher at the charts

### ISSUE THREAD

**Issue by ipiasecki** [firehol/netdata#2919]
Hi.
I use netdata 1.8.0-361-g0a49e32_rolling commit 0a49e32. 
At the charts of Quality of Service i can see, that lower values are behind that higher. And lower values have got higher values than higher in the reality. I attached screen shot.

![screen](https://user-images.githubusercontent.com/11630236/31944862-c5c58930-b8cd-11e7-9237-5958d12301d0.png)

Is this bug ? At the another charts all seems to be ok. Lower values are before this higher.

**Comment by ktsaou** [comment]
Hi, the order of dimensions at the chart legends is controlled by the plugins that generate them (they also get colors based on position).

For the `tc` plugin the order depends on the way `tc` itself outputs them. I see mine is:

```json
			"dimensions": {
				"20:": { "name": "default" },
				"19:": { "name": "dsl/background" },
				"18:": { "name": "dsl/default" },
				"17:": { "name": "dsl/surfing" },
				"16:": { "name": "dsl/synacks" },
				"15:": { "name": "dsl/servers" },
				"14:": { "name": "dsl/vpns" },
				"13:": { "name": "dsl/interactive" },
				"12:": { "name": "dsl/voip" }
			},
```

and I get this:

![image](https://user-images.githubusercontent.com/2662304/31965083-d60e0fb0-b90e-11e7-8590-fbd6dce6f56a.png)

So, I think they appear in the reverse order they are configured.
This is wrong. It should be the same order. Let' me check how I can fix this.

**Comment by ktsaou** [comment]
It seems I did it:

![image](https://user-images.githubusercontent.com/2662304/31965881-658fd572-b911-11e7-8ecf-ea4c27783855.png)

**Comment by ktsaou** [comment]
merged it.

**Comment by ipiasecki** [comment]
Thank You for this all great job !

**Comment by ipiasecki** [comment]
Hi i checked this on my updated system. The sytuation is still the same. Screen attached. ssh class with value 1.9 has higher chart plot than class default with value 6.8. Green chart plot should be before orange chart. 
![screenshot](https://user-images.githubusercontent.com/11630236/31982064-f78c1716-b956-11e7-9cc0-af873a4f2e68.png)

Besides chart pikes have errors when compared to scale (left side of the scale).
![screenshot2](https://user-images.githubusercontent.com/11630236/31982156-8046ac74-b957-11e7-85b2-549dbd6db7aa.png)

Is this fixable ?
