### ISSUE TITLE
alarm events not sent

### ISSUE THREAD

**Issue by woosley** [firehol/netdata#2923]
Hi  I am trying to use the alarm system in my setup, but it seems to me that there are some alarm events not sent. 

Based on the document, I assume that every event will be sent by `/usr/libexec/netdata/plugins.d/alarm-notify.sh.` because `The external script will be called for all status changes.`, this includes alarm clear events.

but comparing notifications I  got from email and alarm events on the web page(screenshot below), it seems that the clear events are not sent at all. 

![image](https://user-images.githubusercontent.com/61531/31975429-cb1d83f6-b963-11e7-8302-e8a32cbb0137.png)
![image](https://user-images.githubusercontent.com/61531/31975452-df7b9522-b963-11e7-9a74-16bae6a8f11c.png)

my netdata version is 1.7.0-257-g732dca16_rolling and Centos6.5

**Comment by ktsaou** [comment]
Check the hysteresis info:

![image](https://user-images.githubusercontent.com/2662304/31983233-19f6c5c2-b965-11e7-8b27-0237fbb0811e.png)

So, to avoid sending flip-flop notifications, netdata waits some time.

The log includes this info (you can enable extra columns to check yourself the delays applied):

![screenshot from 2017-10-25 09-18-08](https://user-images.githubusercontent.com/2662304/31983318-75d81454-b965-11e7-98f2-0bf6481a6c31.png)

**Comment by woosley** [comment]
thanks! this indeed makes sense
