### ISSUE TITLE
Error when i want graph on 7 days or misunderstanding

### ISSUE THREAD

**Issue by Aornn** [firehol/netdata#2924]
Hi !
i want to have a graph on 7 days (i have the ressources needed) so i edit my netdata.conf but nothing has changed on my graph, do i need to change something else ?
And my second request is when my mouse is over an graph a point appear on every graph, how can I do to display the point only on the graph who is my mouse ?
Thank you !

```
	<div id="iscsi">
	<h1 style="margin-left:50px;">STORAGE ISCSI</h1>
	<h3 style="margin-left: 70px;">CPU</h3>
	<div data-title="Cpu"  data-width="100%" data-dygraph-valuerange="[0, 100]" data-netdata="system.cpu" data-height="150px" data-before="0"  data-after="-480" data-host="http://test-iscsi:19999"></div>
	<h3 style="margin-left: 70px;">DISK UTIL</h3>
	<div data-title="Disk current I/O operations" data-width="100%" data-colors role="application" data-before="0" data-after="-480" data-netdata="disk.sdb"  data-height="150px" data-host="http://test-iscsi:19999"></div>
	<h3 style="margin-left: 70px;">NETWORK</h3>
	<div data-title="Bandwith"  data-width="100%" data-netdata="net.eth0" data-before="0" data-after="-480" data-height="150px" data-host="http://test-iscsi:19999"></div>
	</div>
```

PS : All my graph is on specific html page

**Comment by ktsaou** [comment]
Hi,

How did you change the history to get 7 days of data in netdata.conf? Could you please post the global section of your netdata.conf?

The sync of charts selection can be disabled from the dashboard settings.
If you want to do it programaticaly (in javascript), add the following to your dashboard, after you load `dashboard.js`:

```html
<script>
NETDATA.options.current.sync_selection = false;
</script>
```

There are many options you can tweak:

https://github.com/ktsaou/netdata/blob/da87208e2d40a639d3717231c57f9358ccc20aef/web/dashboard.js#L300-L384

**Comment by Aornn** [comment]
Because i have many servers so i need to edit each netdata.conf on every servers ?

This is one of my netdata.conf juste for test with the only line i change :

```
# netdata configuration
#
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

# global netdata configuration

[global]
	# glibc malloc arena max for plugins = 1
	# glibc malloc arena max for netdata = 1
	# hostname = test-iscsi
	history = 604800
	# update every = 1
```

**Comment by ktsaou** [comment]
ok, then the database will grow up 7 days (604800 secs). It will **grow**, so you need to wait 7 days for it to reach its full size.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
