### ISSUE TITLE
User Based Apache Monitoring

### ISSUE THREAD

**Issue by ashutoshpw** [firehol/netdata#2926]
Is there a way by which we can configure apache monitoring on user base, like which user is consuming more resources and which not.

**Comment by ktsaou** [comment]
Do you mean to extract the username from the apache access log and report e.g. a chart with requests per authenticated user?

There is no plugin for that.

I think this would be of very little use. Most applications today do not use HTTP authentication. They authenticate users at the application level, so apache will not log the username.

Then, even if we had this information, the users will most probably not request at the frequency netdata report metrics. I mean, I can't think of any user making constant per second requests for a web server. So, the chart will have many dimensions, and just sparse data on each dimension.

I think you should probably use a web log analyzer, like piwik, for this kind of information.

**Comment by ashutoshpw** [comment]
Well, I meant the same.
As I have a VPS with over 40 users and sometimes some of them consume more resources, I just wanted to monitor them and also, if it was available I may even set alerts to take control of that.

I didn't know about the piwik. Thanks for Recommending, I will give it a try.
You can now close the issue.
