### ISSUE TITLE
App grouping question

### ISSUE THREAD

**Issue by adrianmihalko** [firehol/netdata#2928]
I just found this project, it is very impressive.

I have one question after installing:  netdata can work only by grouping apps? Or it is possible to not group apps?

**Comment by ktsaou** [comment]
netdata monitors many things, through plugins.

Grouping of apps is done by `apps.plugin`. This plugin provides grouping by custom configuration (you define the grouping), by system user and user group.

netdata can also monitor systemd services (depending on the distro, you many need to configure systemd to allow this - check the wiki).

Then, there are system specific plugins (not related to apps) and per application plugins (i.e. plugins that collect application specific metrics, like mysql, nginx, apache, etc).

All plugins can be enabled and disabled. So, you decide what to monitor.
