### ISSUE TITLE
Master don't accept it's well known slave server

### ISSUE THREAD

**Issue by Christophe31** [firehol/netdata#2934]
I have some error on streaming betwin two instances (diferents timezones) it worked until 15 octobre, I have no clues on how to fix. it seems like it broke  without human intervention (daily upgrade?)

Here slave and master logs.

I changed ips and server names for lisibility and privacy.

[error.log](https://github.com/firehol/netdata/files/1422071/error.log)
[m_error.log](https://github.com/firehol/netdata/files/1422072/m_error.log)

**Comment by ktsaou** [comment]
Hi,

It seems that your slave is set to auto-update netdata, but your master is not. So, the slave is using a streaming protocol newer than that of the master.

The protocol is backwards compatible, but the master needs to support the newer one.

So, just update your master.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
