### ISSUE TITLE
Change install instructions in wiki

### ISSUE THREAD

**Issue by svenstaro** [firehol/netdata#294]
This section: https://github.com/firehol/netdata/wiki/Installation#archlinux should be renamed to "Arch Linux" (correct style) and the instructions should just be ```pacman -S netdata```. I put the package into [community] and will delete it from AUR soon.

**Comment by ktsaou** [comment]
Updated. Is it ok now?

**Comment by svenstaro** [comment]
```or run the following (and ignore the next section):

wget https://aur.archlinux.org/cgit/aur.git/snapshot/netdata.tar.gz
tar xf netdata.tar.gz && cd netdata/
makepkg -sri```

must be deleted as well.

**Comment by ktsaou** [comment]
ok. Now?

**Comment by svenstaro** [comment]
Looking good!

**Comment by ecki** [comment]
I guess you can close this as the wiki is moved (however the forwarding link is broken again, should be 
https://docs.netdata.cloud/packaging/installer/ - or maybe Point to more stable start page)

**Comment by cakrit** [comment]
Thanks @ecki, the link has been corrected. I doubt we'll move it again any time soon.
