### ISSUE TITLE
Alerting: cannot touch '/var/cache/netdata/alarm-notify/*: Permission denied

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#2943]
When using channel separation (to warn and critical) got some errors:

In the tail of file **health_alarm_notify.conf**:
```
role_recipients_pd[admin]="a..b 1..f|critical"
role_recipients_telegram[admin]="3..2 -2..9|critical"
role_recipients_telegram[devel]="3..2"
```

Inside **error.log**:
```
mkdir: cannot create directory '/var/cache/netdata/alarm-notify/pd': Permission denied
touch: cannot touch '/var/cache/netdata/alarm-notify/pd/1...f/1..3': Permission denied
touch: cannot touch '/var/cache/netdata/alarm-notify/telegram/-2...9/1..3': Permission denied
```

Issue affected only to critical channels.
After creating of /var/cache/netdata/alarm-notify/pd /var/cache/netdata/alarm-notify/telegram with chmod 777, everything works file.

**Comment by ktsaou** [comment]
Did you install netdata from source, or via a package?

**Comment by shellshock1953** [comment]
From package. v1.7.0-184-ga692a3b6_rolling

**Comment by ktsaou** [comment]
Most probably the permissions are wrong. You can:

```sh
chown -R netdata:netdata /var/cache/netdata/
```

Where did you find that package? Most distros are packaging released versions, not the `rolling` ones.

**Comment by shellshock1953** [comment]
Making custom rpm from sources. Can you check if such behaviour exists in build from sources?
"chown -R netdata:netdata /var/cache/netdata/" worked, thank you!

**Comment by ktsaou** [comment]
hm... I see it is in the rpm spec:

https://github.com/ktsaou/netdata/blob/89ed309252981ddd50f697fde4fe93019cb3e652/netdata.spec.in#L190

Can you check your `netdata.spec` has this line?
Which distro?

**Comment by shellshock1953** [comment]
I`m closing this. Seems it was my fault. Sorry for the inconvenience.
