### ISSUE TITLE
l2arc accounting for misses as hits

### ISSUE THREAD

**Issue by setharnold** [firehol/netdata#2945]
Hello, I just quickly skimmed through the sources and thought this looked out of place:

```
// l2 reads
unsigned long long l2hit = arcstats.l2_hits + arcstats.l2_misses;
```

I wouldn't expect l2hit to be the sum of hits and misses; is the name slightly misleading or is one of these variables supposed to aim at something else?

Thanks

https://github.com/firehol/netdata/blob/502c33810fcec4fd5e5171b1d7ab6b23365bfcbf/src/zfs_common.c#L27

**Comment by ktsaou** [comment]
You are so right!

Thank you for reporting this. I can't even understand how we got to write that there. It seems an incomplete copy-paste...
