### ISSUE TITLE
display file system name instead of dm-n

### ISSUE THREAD

**Issue by abdulirfan3** [firehol/netdata#295]
Hello,

We are running RHEL 6 and we use LVM to create a file system layout for our host.  As you can see from the attached screenshot we have 3 disk assigned to this VM(xvda, xvdb, xvdc) and out of that we have carved up 26 different filesystem (dm-0 to dm-25).  So I was wondering if its possible to display the file system name instead of dm-n, Now everything we have an issue with specific file system we have to go to the host and run something like "lsblk" to find out what dm-n refers to what filesystem.

![image](https://cloud.githubusercontent.com/assets/11415069/14709125/9a46186a-0794-11e6-87fd-0c9fea53a454.png)

**Comment by ktsaou** [comment]
You are very unlucky. I spent 3 hours writing the code for dynamically updating the charts with the mount points of the disks, I was almost there to commit it... and I lost it. I was trying to delete a file and my IDE deleted the whole `src` directory! !@!$#%#@#%@#@$...

Here is what you can do until I re-write it:

1. download the latest netdata.conf from your server, using this:

 ```sh
curl "http://localhost:19999/netdata.conf" >/etc/netdata/netdata.conf.new
```

2. You can change all occurrences of `family = dm-0` to `family = whatever` to have dm-0 appear as `whatever` in the menu.

3. once you are happy: `mv /etc/netdata/netdata.conf.new /etc/netdata/netdata.conf`

4. restart netdata

**Comment by abdulirfan3** [comment]
awe bummer .... Thank you for the suggestion, I will do what is recommended above until the new update is out that dynamically gets that info.

**Comment by abdulirfan3** [comment]
Not that I am trying to be pushy but I wanted to find out when you would have this implemented by?  Reason being, we are putting netdata as part of our template and would like to have the latest one that has this fix as that pretty important to us.  Otherwise we will have to go back to all the servers we deployed from this template that does not have this fix...

**Comment by ktsaou** [comment]
Give me a few days. This is also needed in various other places, so it will be the next thing I'll add.

**Comment by ktsaou** [comment]
Keep in mind the automatic thing will only work if you have mounted the whole disk. If you mount partitions of the disks, what I am going to do will not help.

**Comment by abdulirfan3** [comment]
Okay thanks.  Will it work if we use LVM ?

**Comment by ktsaou** [comment]
I don't know.

This is how it works:

1. It reads `/proc/diskstats`. The first 2 columns is MAJOR and MINOR ids.
2. It checks if `/sys/dev/block/MAJOR:MINOR/partition` exists and states a partition id, in which case this block device is by default not collected by netdata (you can enable it yourself).
3. This is what I am going to do now: read `/proc/self/mountinfo`. The third column is MAJOR:MINOR and the fifth is the mount point. For all collected devices, set the `family` of the charts to the mount point.

**Comment by ktsaou** [comment]
Oops! sorry. I closed it accidentally.

**Comment by ktsaou** [comment]
(actually I didn't close it - it was linked to the PR and github closed it somehow)

The fix has been merged. Please check it.

**Comment by abdulirfan3** [comment]
works like a charm...we have about 100 LVM created out of 15 disk and all of them are displayed ... not only we get it a entire disk (sda or xvda) but also all LVM as well...

THANK YOU...Great work....

**Comment by ktsaou** [comment]
ok great!

Make a git pull before you install this on more servers (I had a little bug, and on some machines the mountinfo processing was crashing netdata).
