### ISSUE TITLE
All charts empty with sync pan and zoom enabled

### ISSUE THREAD

**Issue by miltieIV2** [firehol/netdata#2950]
Your netdata version: 1.8.1_rolling
Your netdata commit: 4f0ca78 

netdata on ip-10-10-96-180, collects every second 46,915 metrics, presented as 592 charts and monitored by 80 alarms, using 736 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.

Even with the fix in 50f91e2931297782ab5fc563825c30c94588822c, when I turn on:
"Settings -> Synchronization -> Sync pan and zoom on all charts?", all charts show empty.

**Comment by ktsaou** [comment]
Hi,

nice machine! I guess 100+ processors/cores?

Could you please open the console of your browser and check for errors?

Did it work in the past? I mean, can you tell if the recent PRs broke it?

**Comment by miltieIV2** [comment]
The machine is an AWS EC2 i3.16xlarge hosting MySQL because they don't offer an AWS RDS MySQL bigger than a db.r3.8xlarge grrrr.

Of course, I switch the setting a reloaded and now it's working....

The situation before was that, with no changes and a wakeup / reload it was empty.

When it flakes again, I'll poke around in Chrome developer tools and poke around.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
