### ISSUE TITLE
alarm-notify.sh not always executed

### ISSUE THREAD

**Issue by VinceCOT** [firehol/netdata#2952]
Hi !

I've recently install netdata on my server and I wanted to have email notifications so I've follow the instructions on https://github.com/firehol/netdata/wiki/email-notifications.
I've configured the file health_alarm_notify.conf then I've tested by running the command /usr/libexec/netdata/plugins.d/alarm-notify.sh test [ROLE] and this worked perfectly with any role (sysadmin, webmaster...).

But after some days, I've realized that I don't receive all the mail notifications (critical or warning alerts) in my mail box.
I've simulate multiple times some 404 error on nginx and I only saw the web notifications and the logs alarm but I don't get anything by mail notifications.
I set a logger command in the script alarm-notify.sh and after running some tests this script is not always execute when I got critical or warning alerts. (I only got web notifications and the logs alarm)
The most of time I don't get the emails (the script alarm-notify.sh is not calling) but sometimes it work and when I receive the mail I saw that this time the script was well executed so the problem is not this script but why sometimes it's not calling by alert ?

Default execute path for all my alerts : /usr/libexec/netdata/plugins.d/alarm-notify.sh

Alert tested :
template: 1m_bad_requests
      on: web_log.response_statuses
families: *
   hosts: *
  lookup: sum -1m unaligned of bad_requests
    calc: $this * 100 / $1m_requests
   units: %
   every: 10s
    warn: ($1m_requests > 20) ? ($this > (($status >= $WARNING)  ? ( 10 ) : ( 30 )) ) : ( 0 )
    crit: ($1m_requests > 20) ? ($this > (($status == $CRITICAL) ? ( 30 ) : ( 50 )) ) : ( 0 )
   delay: up 2m down 15m multiplier 1.5 max 1h
    info: the ratio of HTTP bad requests (4xx) over the last minute
      to: webmaster

Thank you in advance for your help

**Comment by ktsaou** [comment]
Hi,

`alarm-notify.sh` is called by netdata after these delays are applied:

```
delay: up 2m down 15m multiplier 1.5 max 1h
```

But the dashboard shows all notifications in real-time. This leads sometimes to confusion, since you see the dashboard notification, but you have to wait that time to receive any other notification.

There are many ways to verify netdata sends the notifications as it should. 

You can enable extra columns at the alarm log:

![screenshot from 2017-11-02 01-28-56](https://user-images.githubusercontent.com/2662304/32302804-486cf62a-bf6d-11e7-8ffb-1b5696244a5c.png)

The information shown at the alarm log can also be fetched with this URL: `http://your.netdata.ip:19999/api/v1/alarm_log`. It will give you many sections, like this:

```json
	{
		"hostname": "box",
		"unique_id": 1488157878,
		"alarm_id": 1487987281,
		"alarm_event_id": 140,
		"name": "outbound_packets_dropped_ratio",
		"chart": "net_packets.eth0",
		"family": "eth0",
		"processed": true,
		"updated": true,
		"exec_run": 0,
		"exec_failed": false,
		"exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
		"recipient": "sysadmin",
		"exec_code": 0,
		"source": "52@/etc/netdata/health.d/net.conf",
		"units": "%",
		"info": "the ratio of outbound dropped packets vs the total number of sent packets of the network interface, during the last 10 minutes",
		"when": 1509325786,
		"duration": 9,
		"non_clear_duration": 0,
		"status": "CLEAR",
		"old_status": "UNINITIALIZED",
		"delay": 0,
		"delay_up_to_timestamp": 1509325786,
		"updated_by_id": 1488158052,
		"updates_id": 1488157730,
		"value_string": "0%",
		"old_value_string": "0%",
		"value":0,
		"old_value":0
	}
```

So, if you believe you have an alarm that netdata failed to send, I'll need this info to trace it.

**Comment by VinceCOT** [comment]
Thank you very much for your answer you I've completely missed the parameter delay...
And after some investigations it was exactly the subject of my misunderstanding so everything is fine.

By the way, do you know the location of the mail template and if it's possible to edit it ?

**Comment by ktsaou** [comment]
It is in `alarm-notify.sh`

You can copy that file under another name (so that it will not be overwritten by netdata updates), edit it to suits your needs, and set the new name at `netdata.conf`, like this:

```
[health]
	script to execute on alarm = /usr/libexec/netdata/plugins.d/my-super-alarm-notify.sh
```

**Comment by ktsaou** [comment]
Keep in mind though, that this could lead to your alarms not being sent if we change the interface of `alarm-notify.sh`. So, you should check for changes when you update netdata.

**Comment by VinceCOT** [comment]
Thank you for all this informations it's perfect I will take a closer look at that.
