### ISSUE TITLE
netdata random exits

### ISSUE THREAD

**Issue by AnoopAlias** [firehol/netdata#2953]
The netdata service is exiting randomly 

##########################
]# journalctl -u netdata
-- Logs begin at Sun 2017-10-29 08:02:01 CET, end at Thu 2017-11-02 05:50:19 CET. --
Oct 29 06:03:32 web1.example.com systemd[1]: Started Real time performance monitoring.
Oct 29 06:03:32 web1.example.com systemd[1]: Starting Real time performance monitoring...
Oct 31 17:21:08 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Oct 31 17:21:10 web1.example.com systemd[1]: Started Real time performance monitoring.
Oct 31 17:21:10 web1.example.com systemd[1]: Starting Real time performance monitoring...
Oct 31 21:44:13 web1.example.com systemd[1]: netdata.service: main process exited, code=killed, status=11/SEGV
Oct 31 21:44:13 web1.example.com systemd[1]: Unit netdata.service entered failed state.
Oct 31 21:44:13 web1.example.com systemd[1]: netdata.service failed.
Oct 31 23:10:37 web1.example.com systemd[1]: Started Real time performance monitoring.
Oct 31 23:10:37 web1.example.com systemd[1]: Starting Real time performance monitoring...
Oct 31 23:33:44 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Oct 31 23:33:46 web1.example.com systemd[1]: Stopped Real time performance monitoring.
Oct 31 23:33:46 web1.example.com systemd[1]: Started Real time performance monitoring.
Oct 31 23:33:46 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 03:51:21 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Nov 01 03:51:22 web1.example.com systemd[1]: Stopped Real time performance monitoring.
Nov 01 03:54:16 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 03:54:16 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 03:54:40 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Nov 01 03:54:43 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 03:54:43 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 11:09:54 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Nov 01 11:09:59 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 11:09:59 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 11:29:48 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Nov 01 11:29:51 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 11:29:51 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 18:21:18 web1.example.com systemd[1]: Stopping Real time performance monitoring...
Nov 01 18:21:22 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 18:21:22 web1.example.com systemd[1]: Starting Real time performance monitoring...
Nov 01 22:42:52 web1.example.com systemd[1]: netdata.service: main process exited, code=killed, status=11/SEGV
Nov 01 22:42:52 web1.example.com systemd[1]: Unit netdata.service entered failed state.
Nov 01 22:42:52 web1.example.com systemd[1]: netdata.service failed.
Nov 01 22:47:14 web1.example.com systemd[1]: Started Real time performance monitoring.
Nov 01 22:47:14 web1.example.com systemd[1]: Starting Real time performance monitoring...
#####################################################

What does it mean when it say

netdata.service: main process exited, code=killed, status=11/SEGV

**Comment by ktsaou** [comment]
oops! Are you running the latest netdata?

**Comment by AnoopAlias** [comment]
Just updated to latest
###########################
Your netdata version: 1.8.0-345-g4f0ca78b_rolling
Your netdata commit: 4f0ca78
############################

will let you know if the issue happens again

Thanks,

**Comment by ktsaou** [comment]
ok. I am closing this.If the issue persists I will re-open it.
