### ISSUE TITLE
Add GPU Support

### ISSUE THREAD

**Issue by FranciscoGomez90** [firehol/netdata#2954]
Hi there!

I'm currently managing several GPU servers and I think GPU monitoring would be an interesting feature, don't you think?

**Comment by Ferroin** [comment]
#2759 is a preliminary implementation for NVIDIA GPU's.  I'm not aware of any current plans for AMD or Intel GPU's (I would think Intel's wouldn't be too hard, not sure about AMD).

**Comment by l2isbad** [comment]
Please read all comments before use it. To be honest i don't like current implementation and i don't recommend to use it (not an expert)

**Comment by l2isbad** [comment]
another option is https://github.com/coraxx/netdata_nv_plugin (https://github.com/firehol/netdata/issues/2249)

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
