### ISSUE TITLE
Option to set max bandwidth value

### ISSUE THREAD

**Issue by fransozen** [firehol/netdata#2958]
On the system overview, the max values of the "net inbound/outbound" are dynamic, which make the red/green circle values irrelevant since they don't show how much of the available bandwidth is used.
It might be relevant for the network interface graphs as well.

**Comment by ktsaou** [comment]
Well, if we set the max to the interface speed, these circles will mostly be empty, unless you have a very busy server.

The way it is now, the circles show how relative is the current traffic, compared to the peak traffic of the  visible dashboard time.

**Comment by fransozen** [comment]
Your comment could apply to the CPU and the RAM, why have a 0-100% scale on them if not to show which of these resources are busy.
Some server are network centered: file server, tor relays, routers and so on, it would make sense to have the ability to quickly see if the network is bottlenecked somehow. 
It might be a personal point of view but I feel the dynamic mode is misleading, showing a more or less full circle even if the ressource is not so busy.

**Comment by ktsaou** [comment]
For CPU and RAM, the resources are finite. We can always know what is 100%.

For network and disk, what is 100% if the server has 2 network interfaces and 2 disks?

If we assume that 100% is the sum of the max capacity of all physical network interfaces, we will render something that is totally wrong. We will show 50% when your internet interface is 100% and your management interface is 0%.

There are also many setups that the physical network interface has a link speed of 1Gbit, but the actual feed on the link cannot exceed a certain threshold (e.g 100Mbit). This is the case of most dedicated circuits. How will we know what is 100% in these cases?

Then, there are exotic network interfaces: bonds, bridges, VPNs, etc. If you check the cloud world, it becomes even more complicated. Physical interfaces are shared among many blades and each blade overbooks the network to virtual machines. So a server has 40Gbit physical capacity, but is offers it as 400Gbit to its virtual machines. Which is the right 100%? 40, 400, or 440?

You see, there is no way to calculate 100% for network and disk. It depends on the setup.

**Comment by ktsaou** [comment]
> For CPU and RAM, the resources are finite. We can always know what is 100%.

Just for completeness:

1. CPU % is affected by the CPU clock. 100% at which clock speed? Hopefully the linux kernel adapts the clock speed as demand grows. But still 5% CPU utilization at the lowest clock speed, is actually 1% at the highest speed. This is why many applications are shown in netdata as utilizing a lot less resources when the system is under stress.

2. Memory is also dynamic in many setups. Even VMs have balloon drivers that can automatically adapt the memory size according to the demand. The percentage in this case, is again based on the currently addressable memory. If memory grows or shrinks the percentage changes accordingly.

However, on both of these cases we can know what is the currently max. So a percentage, although not strictly accurate, is a good representation of what is happening.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
