### ISSUE TITLE
Netdata consuming all available SWAP space

### ISSUE THREAD

**Issue by tsrofj** [firehol/netdata#2960]
Thanks for a GREAT tool!

Summary: On a Centos7 w/ PostgreSQL9.6, Netdata is using all available swap space.
We are saving Netdata data on the local host, 36 hours. Netdata version: 1.7.0-127-g2d6660fc_rolling, Netdata commit: 2d6660f. CentOS Linux release 7.3.1611 (Core) .

Netdata reports swap usage for the system:
![image](https://user-images.githubusercontent.com/28957756/32334906-a969f0da-bfb9-11e7-8ff6-ed8273cfd657.png)
![image](https://user-images.githubusercontent.com/28957756/32334940-bf81f930-bfb9-11e7-8b31-d94f26187afb.png)

command 'top -c' reports that the swap space is mostly used by netdata:
![screenshot from 2017-11-02 10-39-munged](https://user-images.githubusercontent.com/28957756/32336181-9f9c50e0-bfbc-11e7-8bc7-c7dd733f4c4a.png)

Yesterday, Netdata had over 4GB of swap consumed (and had had for about a week before I could devote any time to troubleshooting). Executed 'systemctl restart netdata.service' and the swap consumed by Netdata went to near zero.

This chart shows the drop at ~1130 local time yesterday when Netdata was restarted:
![image](https://user-images.githubusercontent.com/28957756/32335651-5801ac04-bfbb-11e7-8c1c-eac082abcfc5.png)
And, notice the precipitous climb around 00:00 -- our system-level backups kick off around that time. Database backups, however, occur earlier and seem to have not affected the swap space.

Here's some of the Netdata-specific charts:
![image](https://user-images.githubusercontent.com/28957756/32335769-a2977046-bfbb-11e7-8f13-4c7a170034cb.png)

![image](https://user-images.githubusercontent.com/28957756/32335808-b8367406-bfbb-11e7-9b39-c48de8cfeb03.png)

I see that there is a netdata update, however this is a production Postgres host during our very busy time -- it will be difficult to update packages on this host unless I can point to a fix for the swap space consumption in the update. I looked at the changes log for the update and didn't find anything in the changes re: netdata or swap that seemed to address this issue.

Additional trouble-shooting/logs/etc. recommendations?

Thanks,
Jason

**Comment by ktsaou** [comment]
Could you please check this chart:

![image](https://user-images.githubusercontent.com/2662304/32351474-27d5d7e2-c026-11e7-8add-f15cf14d1f89.png)

Zoom it out completely. For the last 36 hours, does the memory of netdata constantly increase?
If yes, there is a memory leak.

I see you have constant chart refreshes, so I guess you have a dashboard on TV. Could you please stop it for 1-2 hours. Does the memory increase while the dashboard on tv is off? If it does not increase, the memory leak is at the internal web server.

It would be great if you could update to the latest netdata. I see you are using the static 64 bit binary package. So updating is almost instant. My suggestion is to update it. We have applied many fixes.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
