### ISSUE TITLE
Getting ACPI IPMI errors in syslog every 3 seconds on Dell R720xd, CentOS 6, 2.6.32-642.3.1.el6.x86_64

### ISSUE THREAD

**Issue by kuzmeech** [firehol/netdata#2961]
Getting errors like below every 3 seconds, it was happening on netdata 1.7, I've just pulled the latest netdata 1.8 and rebuilt it 20171102 17:33EST (netdata 1.8.0-345-g4f0ca78_rolling), however the error persists, so it wasn't introduced very recently.. 
```
Nov  2 17:30:25 host kernel: ACPI: No handler for Region [POWR] (ffff8820538672b8) [IPMI]
Nov  2 17:30:28 host kernel: ACPI: No handler for Region [POWR] (ffff8820538672b8) [IPMI]
Nov  2 17:30:31 host kernel: ACPI: No handler for Region [POWR] (ffff8820538672b8) [IPMI]
Nov  2 17:30:34 host kernel: ACPI: No handler for Region [POWR] (ffff8820538672b8) [IPMI]
```

Erros go away after netdata process is killed, and reappear after I start netdata. Took me awhile to realize these lines in /var/log/messages are being caused by a running netdata process.

Firmware version for iDRAC (Enterprise) and BIOS for just in case:
```
[root@host netdata]# omreport chassis firmware
Firmware Information

Version Information
iDRAC7                 : 2.32.31.30 (Build 3)
Lifecycle Controller 2 : 2.32.31.30

[root@host netdata]# omreport chassis bios
BIOS Information

Manufacturer : Dell Inc.
Version      : 2.5.4
Release Date : 01/22/2016
```

**Comment by ktsaou** [comment]
According to https://access.redhat.com/solutions/49225

> These error messages can be avoided by blacklisting the "acpi_power_meter" module causing the IPMI region to be used.  The acpi_power_meter module is one module which is known to cause this error on some systems.
> The messages are a sign that some power management features may not be usable.  It's not a sign of a dangerous condition and the messages should be considered informational and not a dangerous error which must be corrected.

According to https://www.novell.com/support/kb/doc.php?id=7010449

> This is caused by a missing kernel module

Also https://www.suse.com/support/kb/doc/?id=7010449

> This is caused by a missing kernel module

---

So, I guess that something netdata monitors triggers this. Probably `sensors`. You can either `modprobe` the missing kernel module, or disable monitoring sensors in netdata (edit `/etc/netdata/python.d.conf`).

**Comment by kuzmeech** [comment]
Thank you, I've also googled and found these links, and tried
```
[root@host ~]# modprobe ipmi_si
[root@host ~]# modprobe acpi_ipmi

```
and it had no effect, quite surprising it causes this hard-to-find-cause error in syslogd out of the box.. 
Settings sensors:no stopped the output..

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.

**Comment by kiler129** [comment]
While this discussion is very old it's a first google result for the problem (and it happens on many Dell & HP servers).
The solution is to execute:

```shell
rmmod acpi_power_meter
echo acpi_power_meter >> /etc/modprobe.d/blacklist-power-meter.conf
```

**Comment by alitoufighi** [comment]
Since this is a top Google result I would also like to mention that loading `acpi_ipmi` kernel module fixed those error messages on a HPE DL380 Gen10 running Ubuntu 20.04.1:
```
modprobe acpi_ipmi
```

**Comment by opensourcerulez** [comment]
modprobe ipmi_si
modprobe acpi_ipmi

helped on ubuntu 20.04 and HPE gen10 plus
