### ISSUE TITLE
Install issues on cPanel Cloudlinux VPS server

### ISSUE THREAD

**Issue by haleeben** [firehol/netdata#2963]
Hi 

I received this message when installing on my cPanel Cloudlinux VPS server

--- Install netdata at system init --- 
I don't know what init file to install on system 'CloudLinux Server release 6.9 (Igor Volk)'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service. 

 --- Start netdata --- 
[/root/netdata]# /sbin/service netdata stop 
netdata: unrecognized service
 FAILED   

Stopping netdata on pid 838221 ....
netdata on pid 838221 stopped.
[/root/netdata]# /sbin/service netdata restart 
netdata: unrecognized service
 FAILED   

[/root/netdata]# /sbin/service netdata start 
netdata: unrecognized service
 FAILED   

[/root/netdata]# stop_all_netdata 
 OK   

[/root/netdata]# /usr/sbin/netdata 
 OK   

OK. NetData Started!

**Comment by ktsaou** [comment]
Hi,

thanks! Do you know the distro cPanel Cloudlinux VPS is based on?

I understand it is not a systemd system. So, does it use `open-rc` (gentoo, alpine), `LSB` (debian, ubuntu), or `init.d` (fedora, rhel, centos, oracle, etc)?

**Comment by haleeben** [comment]
Hi

Its centos 6.5

**Comment by ktsaou** [comment]
merged the fix.
Please re-install netdata. It should now install the init.d service too.
