### ISSUE TITLE
Netdata monitoring Exim & Dovecot

### ISSUE THREAD

**Issue by arjove** [firehol/netdata#2966]
Hi,

We have exim and dovecot installed on the server, and netdata does not bring up a chart with things like the email que. 

I installed netdata manually, making sure to include the all that netdata can monitor things. 

What should i do to make the exim and dovecot charts show up?

**Comment by l2isbad** [comment]
Hi
I suggest to run modules in [debug mode](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
