### ISSUE TITLE
registry hostname on an headless collector

### ISSUE THREAD

**Issue by damianetienne** [firehol/netdata#2968]
I have some doubts on how to implement "registry hostname" feature on a netdata headless collector.

The Configuration on my central netdata:

[registry]
	enabled = yes
	registry to announce = http://mycentralnetdata.com:19999
	registry hostname = Monitor - mycentralnetdata. com

And on my slaves netdatas:

[registry]
	enabled = no
	registry to announce = http://mycentralnetdata.com:19999
	registry hostname = DNS - slave.****. com

The hostname of the central netdata is displayed correctly in the my-netdata menu, but not the other slave servers. 

It is worth mentioning that all slave servers have the web service disabled

[web]
	mode = none

So I access them through the "my-netdata" menu or via: http://mycentralnetdata.com:19999/host/slave.com*

My question is whether it is absolutely necessary to enable web service on slave servers for the "registry hostname" feature to work properly?

**Comment by ktsaou** [comment]
Hi,

The registry is not used on headless slaves. Only the master advertises their dashboards, so you don't have to set it at your headless slaves.

**Comment by damianetienne** [comment]
Thanks.

It would be great if you could sort the headless collectors in some way, since it is difficult to find them if there are many servers configured on the same installation.
