### ISSUE TITLE
Question: I like the dashboard, can I use dashboard to render prometheus data?

### ISSUE THREAD

**Issue by gaohailang** [firehol/netdata#2971]
where should I convert the data from Prometheus to the format which is netdata dashboard needed? Thanks a lot

**Comment by ktsaou** [comment]
Unfortunately no. The netdata dashboard relies to the netdata API.

We could have a prometheus data collection plugin though. So, a netdata plugin could use prometheus as a source of metrics, which will then be exposed on the netdata dashboards.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
