### ISSUE TITLE
Cgroup config difficulty

### ISSUE THREAD

**Issue by spinitron** [firehol/netdata#2973]
I use lxc containers. In the screenshot below, the chart groups for the two containers are useful. The hundreds of system.slice groups that follow are not.

I have not been able to configure netdata to show the graphs for the two lxc containers and get rid of the rest. I was not able to understand these [instructions](https://github.com/firehol/netdata/wiki/monitoring-cgroups). 

![screenshot](https://monosnap.com/file/kdqW9TD7PDfJ0lPWxPLMzemOW8GYuD.png)

**Comment by ktsaou** [comment]
Hi,

The fix is simple, but I would like your help to understand how to do this right.

Please answer these questions:

1. `uname -a`
2. `cat /etc/os-release`
3. `tree /sys/fs/cgroup` (it will be long, probably use pastebin or something else)
4. `curl -Ss http://localhost:19999/netdata.conf | sed -n -e "/^\[plugin\:cgroups\]$/,/^$/p"`

Using the above, I'll adapt the netdata defaults to handle your case too.

**Comment by spinitron** [comment]
1. Linux bhs3.spinitron.com 4.9.58-xxxx-std-ipv6-64 #1 SMP Mon Oct 23 11:35:59 CEST 2017 x86_64 GNU/Linux

2.
        PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
        NAME="Debian GNU/Linux"
        VERSION_ID="9"
        VERSION="9 (stretch)"
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

3. https://gist.github.com/spinitron/f8337bcd5327a9e4bc851aee83fbbeea

4.
        enable cpuacct usage (per core CPU) = no
        run script to rename cgroups matching = *lxc*  *
        cgroups to match as systemd services = !/system.slice/*/*.service  !/system.slice/*.service
        # cgroups plugin resource charts = yes
        # update every = 5
        # check for new cgroups every = 50
        # enable cpuacct stat (total CPU) = auto
        # enable memory (used mem including cache) = auto
        # enable detailed memory = auto
        # enable memory limits fail count = auto
        # enable swap memory = auto
        # enable blkio bandwidth = auto
        # enable blkio operations = auto
        # enable blkio throttle bandwidth = auto
        # enable blkio throttle operations = auto
        # enable blkio queued operations = auto
        # enable blkio merged operations = auto
        # recheck zero blkio every iterations = 10
        # recheck zero memory failcnt every iterations = 10
        # recheck zero detailed memory every iterations = 10
        # enable systemd services = yes
        # enable systemd services detailed memory = no
        # report used memory without cache = yes
        # path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpu,cpuacct
        # path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
        # path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
        # path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
        # max cgroups to allow = 1000
        # max cgroups depth to monitor = 0
        # enable new cgroups detected at run time = yes
        # enable by default cgroups matching =  !*/init.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  *
        # search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/*  *
        # script to get cgroup names = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
        # script to get cgroup network interfaces = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network
        # enable cgroup _ = no
        # search for cgroups under / = yes
        # enable cgroup user.slice = no
        # enable cgroup init.scope = no
        # enable cgroup lxc = no
        # search for cgroups under /lxc = yes
        # enable cgroup lxc_epf2 = yes
        # enable cgroup lxc_epf1 = yes
        # enable cgroup system.slice = no
        # search for cgroups under /system.slice = yes
        # enable cgroup system.slice_irqbalance.service = no
        # enable cgroup system.slice_lvm2-lvmetad.service = no
        # enable cgroup system.slice_run-r15909153467b49a698f6d3eb91ca0a2c.scope = yes
        # enable cgroup system.slice_run-reed05b1fe3784193823cdc458f6b838c.scope = yes
        # enable cgroup system.slice_home.mount = no
        # enable cgroup system.slice_php7.1-fpm.service = no
        # enable cgroup system.slice_v2_automation.service = no
        # enable cgroup system.slice_run-rf5a6a70318564ceeb50afb079cb4453d.scope = yes
        # enable cgroup system.slice_run-r1f6e85ef7bd840349e4daa06a438b720.scope = yes
        # enable cgroup system.slice_run-ra657bb07ddd04635a43e8a0f6c32f309.scope = yes
        # enable cgroup system.slice_salt-minion.service = no
        # enable cgroup system.slice_run-rf000099b7d704cb79ce4240003272f03.scope = yes
        # enable cgroup system.slice_run-rdd21e678ac8841b3aa43a99f0cdf16e2.scope = yes
        # enable cgroup system.slice_run-rfce32a108a064fe58685838aa41b5e03.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2did-nvme/x2dnvme.8086/x2d435650463732333330304a5134353052474e/x2d494e5445 = no
        # enable cgroup system.slice_run-rba285f2163734069b8feb748046435a0.scope = yes
        # enable cgroup system.slice_var-lib-lxc.mount = no
        # enable cgroup system.slice_run-re2a1f8acba4445d3aaccdf02df6f3a36.scope = yes
        # enable cgroup system.slice_run-rc30bbac8f9084dc283a48cabdd92c09d.scope = yes
        # enable cgroup system.slice_run-rd9b77eeb24024574a7f35206dfd00e10.scope = yes
        # enable cgroup system.slice_run-r695ee4ecebab43df917bfa958321a743.scope = yes
        # enable cgroup system.slice_systemd-random-seed.service = no
        # enable cgroup system.slice_run-r1dcad96308a445559f4e8ef444d97528.scope = yes
        # enable cgroup system.slice_run-rc93d46deee4d42029698b78f7fc233c7.scope = yes
        # enable cgroup system.slice_run-r16450f39efe94e389f585d53b5c39e8a.scope = yes
        # enable cgroup system.slice_systemd-journal-flush.service = no
        # enable cgroup system.slice_run-r647d9c34b5ab4219a918d1cf5ab4c8b2.scope = yes
        # enable cgroup system.slice_run-r9dfe6cc1c5694966972b45692639476d.scope = yes
        # enable cgroup system.slice_systemd-timesyncd.service = no
        # enable cgroup system.slice_run-r060cf9a4470043fab70c17ae97cf7928.scope = yes
        # enable cgroup system.slice_systemd-user-sessions.service = no
        # enable cgroup system.slice_run-rc714cd5bfc6443d8b3c98b3f101d8bc2.scope = yes
        # enable cgroup system.slice_sys-kernel-config.mount = no
        # enable cgroup system.slice_run-r23468145af3a4e56a53309a5b7c9eac1.scope = yes
        # enable cgroup system.slice_v2_push.service = no
        # enable cgroup system.slice_run-r52ec711b1a87408a9046122c44ebdfe2.scope = yes
        # enable cgroup system.slice_glusterfs-server.service = no
        # enable cgroup system.slice_sphinxsearch.service = no
        # enable cgroup system.slice_lvm2-monitor.service = no
        # enable cgroup system.slice_lxcfs.service = no
        # enable cgroup system.slice_run-r87c2b04e55db41b0a2972efe32da3085.scope = yes
        # enable cgroup system.slice_lxc-net.service = no
        # enable cgroup system.slice_run-r5746ed0e01be46fbb9886a848ee07872.scope = yes
        # enable cgroup system.slice_hddtemp.service = no
        # enable cgroup system.slice_run-r667429a32f6e46a1a5248ec2f1eafc58.scope = yes
        # enable cgroup system.slice_run-rc32733ecebd84cccb4753261111cdc18.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2dlabel-swap/x2dnvme0n1p3.swap = no
        # enable cgroup system.slice_run-r6439f61c82884eb4a5fe1f68cbeec82a.scope = yes
        # enable cgroup system.slice_run-r8e06fe11de05422c8853c39a9e0dce50.scope = yes
        # enable cgroup system.slice_run-r769caf8dcd5248c5aa16f7680d5e57d4.scope = yes
        # enable cgroup system.slice_run-rd87b95ade1af48daac29fc41dbf349a2.scope = yes
        # enable cgroup system.slice_nginx.service = no
        # enable cgroup system.slice_sys-fs-fuse-connections.mount = no
        # enable cgroup system.slice_systemd-udev-settle.service = no
        # enable cgroup system.slice_run-r7e66f7fe8c60430bb9ab53de1f95284f.scope = yes
        # enable cgroup system.slice_dbus.service = no
        # enable cgroup system.slice_run-r16ccabce07e24425ac697a9ed0d7df2a.scope = yes
        # enable cgroup system.slice_run-rfdf3471c1a4949818788f253548066e5.scope = yes
        # enable cgroup system.slice_var-lib-lxcfs.mount = no
        # enable cgroup system.slice_postfix.service = no
        # enable cgroup system.slice_run-r8e75f41bf3df4c7ab94d7cabec7ce4c8.scope = yes
        # enable cgroup system.slice_systemd-modules-load.service = no
        # enable cgroup system.slice_var-lib-mysql.mount = no
        # enable cgroup system.slice_run-ra9d4e795b8ac42fc894715df3a7231b6.scope = yes
        # enable cgroup system.slice_dev-mqueue.mount = no
        # enable cgroup system.slice_run-r738b36054de64e3c8d6006b947e7b3b5.scope = yes
        # enable cgroup system.slice_run-re1c592e77cbf4398bd0b4dcc0aeb7d95.scope = yes
        # enable cgroup system.slice_run-r492b0c599a514f619af43807ef495b86.scope = yes
        # enable cgroup system.slice_run-ra40c13bb459a42caa7b9bea0f7834147.scope = yes
        # enable cgroup system.slice_ssh.service = no
        # enable cgroup system.slice_run-rdb474c628da245fc83c05a668eb10d58.scope = yes
        # enable cgroup system.slice_systemd-tmpfiles-setup.service = no
        # enable cgroup system.slice_run-r94a9903a72d34824afe7feb94622da56.scope = yes
        # enable cgroup system.slice_run-reae237bd47dd407cb23c2a792372b382.scope = yes
        # enable cgroup system.slice_run-r4398969a9b0649cca439d1c1b473010e.scope = yes
        # enable cgroup system.slice_systemd-remount-fs.service = no
        # enable cgroup system.slice_system-getty.slice = no
        # enable cgroup system.slice_run-rd0fa81544cd3463ab1cc244fc222bc93.scope = yes
        # enable cgroup system.slice_systemd-networkd-wait-online.service = no
        # enable cgroup system.slice_run-raff055893fe9427fb153c0ad0fc0ad19.scope = yes
        # enable cgroup system.slice_run-rbce2bc14703b48e483e20f34da48c181.scope = yes
        # enable cgroup system.slice_run-rec61a6a11bf44ad38cbdffe2ab193cbc.scope = yes
        # enable cgroup system.slice_run-ra458f6cfd8a44721951aa9c91406869c.scope = yes
        # enable cgroup system.slice_systemd-update-utmp.service = no
        # enable cgroup system.slice_system-systemd/x2dfsck.slice = no
        # enable cgroup system.slice_run-r3cdb475d461648f18538395f66e9a2fa.scope = yes
        # enable cgroup system.slice_run-r9f80b603fd4348cc9f57de9fa58c26a3.scope = yes
        # enable cgroup system.slice_run-r7f31156036134218b338f4289877297f.scope = yes
        # enable cgroup system.slice_run-rf7b600e2781048c0939178b103dd2274.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2duuid-5a9098df/x2dbf7e/x2d44e2/x2d92c7/x2d85cb2c2af698.swap = no
        # enable cgroup system.slice_keyboard-setup.service = no
        # enable cgroup system.slice_run-rddbc0571eb32445c8465d01dfe6a1a26.scope = yes
        # enable cgroup system.slice_run-r69a08a4a212e473587bb073fa8247ae0.scope = yes
        # enable cgroup system.slice_run-r841297636f6b4f4fb44e37a53750297f.scope = yes
        # enable cgroup system.slice_run-r5052a2dcb0084ea4979e13731add5858.scope = yes
        # enable cgroup system.slice_run-r5c7aefe8f1aa45c59ae1701c8d3d9a80.scope = yes
        # enable cgroup system.slice_run-re6a43c7b2bdb4d768a20554736a2012e.scope = yes
        # enable cgroup system.slice_run-r24dc32b3ddb244918cddd41a97d0791f.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2dpath-pci/x2d0000_02_00.0/x2dnvme/x2d1/x2dpart3.swap = no
        # enable cgroup system.slice_home-data.mount = no
        # enable cgroup system.slice_run-rc25a54b8b07f4a858c67bd2e75967d3e.scope = yes
        # enable cgroup system.slice_sysstat.service = no
        # enable cgroup system.slice_run-r1cbdce925dd0443d87305c2e32133f0f.scope = yes
        # enable cgroup system.slice_systemd-logind.service = no
        # enable cgroup system.slice_v2_harvest.service = no
        # enable cgroup system.slice_run-ra1d6a88309a649e4a11230e71328bf5e.scope = yes
        # enable cgroup system.slice_run-r6dc956281a4f45aaaa12364740c7bcda.scope = yes
        # enable cgroup system.slice_run-r9f92a587281b4d709780ca2c564ebb4d.scope = yes
        # enable cgroup system.slice_run-rcfe7312c41d1409b8f1b891c7c11cb3a.scope = yes
        # enable cgroup system.slice_run-rb8ccd7f2786c47ac937c1c81d7d1360a.scope = yes
        # enable cgroup system.slice_run-rf08656ed3c114f4d80c3ff31e00af956.scope = yes
        # enable cgroup system.slice_run-r0db964fef38d43209cef50559005b3cd.scope = yes
        # enable cgroup system.slice_run-r1deb1b73097c40359b9e8e05493937df.scope = yes
        # enable cgroup system.slice_run-r183f3446e4414e9192abd01d7ab248b1.scope = yes
        # enable cgroup system.slice_run-r703f5688a5ca472b9f58f758dcb6d157.scope = yes
        # enable cgroup system.slice_run-r84cf5d7719624eabb1aebb975186a9c8.scope = yes
        # enable cgroup system.slice_run-rf2f31507352e40b483ca21a7afe6a76a.scope = yes
        # enable cgroup system.slice_cron.service = no
        # enable cgroup system.slice_systemd-udevd.service = no
        # enable cgroup system.slice_run-r84ce7c32ead2490ab772c5cf847ec833.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2did-nvme/x2dintel_ssdpe2mx450g7_cvpf723300jq450rgn/x2dpart3.swap = no
        # enable cgroup system.slice_dev-nvme0n1p3.swap = no
        # enable cgroup system.slice_var-lib-sphinxsearch.mount = no
        # enable cgroup system.slice_rsyslog.service = no
        # enable cgroup system.slice_netdata.service = no
        # enable cgroup system.slice_run-r07e4f94cc4e1441e9d5dbbeccabe1e43.scope = yes
        # enable cgroup system.slice_run-rf53ad475975d4a069f86106eb101667b.scope = yes
        # enable cgroup system.slice_networking.service = no
        # enable cgroup system.slice_run-rf3385a3965de4468950ada0cafd9b63e.scope = yes
        # enable cgroup system.slice_systemd-tmpfiles-setup-dev.service = no
        # enable cgroup system.slice_run-r717627e8c8214c0fbb6524a1c21bbcb5.scope = yes
        # enable cgroup system.slice_memcached.service = no
        # enable cgroup system.slice_run-rf27fce4750b64f8ba239d21e3a70b881.scope = yes
        # enable cgroup system.slice_run-r2504e43361d143a0a972139e43428ecb.scope = yes
        # enable cgroup system.slice_run-rade17ad9ebe3445ebe5b80b4cad14ed9.scope = yes
        # enable cgroup system.slice_systemd-journald.service = no
        # enable cgroup system.slice_run-r52c9b70accf34689840ca10d194f9119.scope = yes
        # enable cgroup system.slice_run-r07405b7e14fe4c82bd52404b0469455c.scope = yes
        # enable cgroup system.slice_console-setup.service = no
        # enable cgroup system.slice_mariadb.service = no
        # enable cgroup system.slice_bind9.service = no
        # enable cgroup system.slice_run-r999f621a2e8841dbb0110a0c9a02267f.scope = yes
        # enable cgroup system.slice_run-r64c4aae371db4f0fa166ca439ecbe2a7.scope = yes
        # enable cgroup system.slice_run-rea3e8bece1b6457eb915408c574dac71.scope = yes
        # enable cgroup system.slice_v2_chat.service = no
        # enable cgroup system.slice_run-r2d5c560ffe1142cda4c1423c94dab57f.scope = yes
        # enable cgroup system.slice_run-rc19ef009223f42f6a9fe0b7ff81f9746.scope = yes
        # enable cgroup system.slice_run-r70c8e029907d4ccdbc00ef098b1ee501.scope = yes
        # enable cgroup system.slice_run-rd414caf66f8b4373adf6e311712eff84.scope = yes
        # enable cgroup system.slice_run-rdb4742c107ba484093f7a4f5d7562f05.scope = yes
        # enable cgroup system.slice_boot-efi.mount = no
        # enable cgroup system.slice_systemd-sysctl.service = no
        # enable cgroup system.slice_systemd-networkd.service = no
        # enable cgroup system.slice_salt-master.service = no
        # enable cgroup system.slice_run-r30020eac76eb409b8b63646e323d9120.scope = yes
        # enable cgroup system.slice_dev-disk-by/x2dpartuuid-9245c9a4/x2d0f38/x2d461a/x2da61c/x2dcfa874ed9aa8.swap = no
        # enable cgroup system.slice_run-rd2c9a75fc3904b9b892eb30b395b4487.scope = yes
        # enable cgroup system.slice_run-r1d660b26fc794450a8ae9e4a7e78dcb8.scope = yes
        # enable cgroup system.slice_run-r6a080062025a4358894b6d9306a6ef3a.scope = yes
        # enable cgroup system.slice_-.mount = no
        # enable cgroup system.slice_run-r1ba132a9ff1a4db48477b16e46c89049.scope = yes
        # enable cgroup system.slice_lxc.service = no
        # enable cgroup system.slice_run-r3eafc1e75350409c8c0f1c2df72d0ed2.scope = yes
        # enable cgroup system.slice_srv-brick.mount = no
        # enable cgroup system.slice_systemd-udev-trigger.service = no
        # search for cgroups under /lxc/epf2 = yes
        # enable cgroup lxc_epf2_user.slice = no
        # enable cgroup lxc_epf2_init.scope = no
        # enable cgroup lxc_epf2_system.slice = no
        # search for cgroups under /lxc/epf2/system.slice = no
        # search for cgroups under /lxc/epf1 = yes
        # enable cgroup lxc_epf1_user.slice = no
        # enable cgroup lxc_epf1_init.scope = no
        # enable cgroup lxc_epf1_system.slice = no
        # search for cgroups under /lxc/epf1/system.slice = no

**Comment by ktsaou** [comment]
Thanks!

Could you please edit netdata.conf and set:

```
[plugin:cgroups]
   enable by default cgroups matching = !/system.slice/run-*.scope <whatever is already there>
```

So, just add `!/system.slice/run-*.scope` as the first parameter, followed by a space and whatever that line already has.

Then restart netdata. Did it fix it?

PS: Do you know which program created all the scopes?

**Comment by tom--** [comment]
That fixed it. Thanks.

I have no idea what created all those scopes. I don't even know what a system.slice scope is :(

**Comment by tom--** [comment]
thanks for alerting me to the scopes. i'm researching it.
