### ISSUE TITLE
netdata - swap memory usage chart not showing

### ISSUE THREAD

**Issue by nadlabs** [firehol/netdata#2978]
HI,

I have a virtual server running and it does not appear to have the swap charts enabled.

If I go to the charts area mydomain.com/19999/api/v1/charts/ and look for system.swap - it does not appear the list.

I have another (hardware) server running and that is okay. 

I read this https://github.com/firehol/netdata/issues/947#issuecomment-246719397 and thought it maybe because the swap for the virtual server is set to 0. Is this the issue?

If so is it possible to enable it anyway (couldn't see anywhere in the netdata.conf file where this should be set to auto - there are a lot of swap settings) or is there a way to detect if the swap chart is enabled before showing the user (to prevent any errors displaying to the user)

Thanks in advance.

**Comment by ktsaou** [comment]
Most probably your VPS does not have any swap configured.

You can enable it in netdata.conf:

```
[plugin:proc:/proc/meminfo]
	system swap = auto
```

Turn `auto` to `yes`. Uncomment the line too.

- `auto` means: show it only if it is not zero
- `yes` means: show it always

**Comment by nadlabs** [comment]
You were right. The server did not have any swap configured. Fixed now. Feel free to close this.

Thanks for you help!
