### ISSUE TITLE
Process up/down

### ISSUE THREAD

**Issue by alexillsley** [firehol/netdata#2979]
Hi,
I would like to create simple badge to include on a dashboard that is green or red depending on if a certain process I named is running. How best to go about this?

Understand that netdata is mainly for performance monitoring. If I cant do an up/down status, how would I do process uptime length? I suppose if process uptime is 0 then it can be red.

Thanks,
Alex

**Comment by magao** [comment]
If you have a `process.uptime` chart, then a badge like:

`<embed type="image/svg+xml" src="http://localhost:19999:/api/v1/badge.svg?refresh=60&chart=process.uptime&dimension=process_name&label=Up&value_color=red:null|red<=0|green"></embed>`

should work.

By using an `<embed>` you could also include custom javascript to find the value in the SVG and modify it to what you want (but you'd need to trigger it each time the badge refreshed).

**Comment by alexillsley** [comment]
How do I create a proccess.uptime chart?

**Comment by ktsaou** [comment]
Hi,

here is the flow:

1. Edit `apps_groups.conf` and add a group for your application. For example, to monitor application `myapp`, add this:

```
myapp: *myapp*
```

Then restart netdata. Just with the above, the `Applications` charts will now have dimension called `myapp`.

2. Once you have the above set and running, create a badge like this:

```
https://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=myapp&value_color=green%3E0%7Cred
```

The color expression unescaped is this: `value_color=green>0|red`.

Here is an example for the process `netdata` at `https://registry.my-netdata.io`:

![image](https://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=netdata&value_color=green%3E0%7Cred)

and here is the same chart for `myapp` (which of course is not running there):

![image](https://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=myapp&value_color=green%3E0%7Cred)

netdata will be able give you a lot more badges about your app!
Examples below for process `netdata`:

1. CPU usage: ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.cpu&dimensions=netdata&value_color=green%3E0%7Cred)
2. Disk Physical Reads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.preads&dimensions=netdata&value_color=green%3E0%7Cred) (this will be red if the application is not reading from disk - you can swap the colors if you like)
3. Disk Physical Writes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.pwrites&dimensions=netdata&value_color=green%3E0%7Cred)
4. Disk Logical Reads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.lreads&dimensions=netdata&value_color=green%3E0%7Cred)
5. Disk Logical Writes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.lwrites&dimensions=netdata&value_color=green%3E0%7Cred)
6. Open Files ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.files&dimensions=netdata&value_color=green%3E0%7Cred)
7. Real Memory ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.mem&dimensions=netdata&value_color=green%3E0%7Cred)
8. Virtual Memory ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.vmem&dimensions=netdata&value_color=green%3E0%7Cred)
9. Minor Page Faults ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.minor_faults&dimensions=netdata&value_color=green%3E0%7Cred)
10. Processes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=netdata&value_color=green%3E0%7Cred)
11. Threads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.threads&dimensions=netdata&value_color=green%3E0%7Cred)
12. Major Faults (swap activity) ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.major_faults&dimensions=netdata&value_color=green%3E0%7Cred)
13. Open Pipes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.pipes&dimensions=netdata&value_color=green%3E0%7Cred)
14. Open Sockets ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.sockets&dimensions=netdata&value_color=green%3E0%7Cred)

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
