### ISSUE TITLE
Strange connection

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#2983]
HI, I have netdata and prometheus setup on different hosts.
When I look open connections, i see such an output.

    `Active Internet connections (w/o servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State
    tcp        0      0 elilocardi.com:19999  my_prometheus_ip.st:29660 TIME_WAIT`

My question is  - what is elolocard.com and what has it to do with my netdata?

**Comment by ktsaou** [comment]
This is not netdata related.

Run `netstat -n` and check your DNS server. Your local IP is resolved to `elilocardi.com`.

btw, the connection in question is a connection from your prometheus to your netdata. Nothing fancy. Just a DNS issue you have.

**Comment by vaheminasyan** [comment]
Thanks. Sorry for inconvenience.
