### ISSUE TITLE
OpenVPN plugin returns data but not displayed in graph

### ISSUE THREAD

**Issue by ratchetnclank** [firehol/netdata#2988]
The python.d daemon seems to get the data from the openvpn status log but the chart is always empty on the netdata dashboard.

Contents of `/etc/netdata/python.d/ovpn_status_log.conf`
```
default:
 log_path: '/etc/openvpn/openvpn-status.log'
 update_every: 10
```

Results from  `/usr/libexec/netdata/plugins.d/python.d.plugin 1 trace openvpn`

```
CHART ovpn_status_log_default.traffic '' 'OpenVPN Traffic' 'KB/s' 'traffic' 'openvpn_status.traffic' area 60001 10 '' 'python.d.plugin' 'ovpn_status_log'
DIMENSION 'bytes_in' 'in' incremental 1 1024 ''
DIMENSION 'bytes_out' 'out' incremental 1 -1024 ''

BEGIN ovpn_status_log_default.traffic 0
SET 'bytes_in' = 1597174
SET 'bytes_out' = 5251316
END

CHART ovpn_status_log_default.users '' 'OpenVPN Active Users' 'active users' 'users' 'openvpn_status.users' line 60000 10 '' 'python.d.plugin' 'ovpn_status_log'
DIMENSION 'users' 'users' absolute 1 1 ''

BEGIN ovpn_status_log_default.users 0
SET 'users' = 2
END

BEGIN netdata.runtime_ovpn_status_log_default 0
SET run_time = 0
END
```

Netdata Version is `netdata 1.8.0-439-g3e7952d_rolling`

**Comment by ktsaou** [comment]
Could you please run the plugin as user `netdata`?

```sh
# become user netdata
sudo su -s /bin/bash netdata

# run the plugin
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug openvpn
```

**Comment by ktsaou** [comment]
cc: @l2isbad

**Comment by l2isbad** [comment]
It's `ovpn_status_log`, not `openvpn`.
Do a `/usr/libexec/netdata/plugins.d/python.d.plugin 10 debug ovpn_status_log` (`trace` option needed it there is any exceptions) as user `netdata`.


> always empty on the netdata dashboard

please post a screenshot

**Comment by ratchetnclank** [comment]
Turns out it was permissions. Sorry

**Comment by jneivil** [comment]
Permisoions

in what file?

**Comment by ratchetnclank** [comment]
The open VPN status log file.

/etc/openvpn/openvpn-status.log

Running as the netdata user didn't have access.
