### ISSUE TITLE
Installation deleted /etc/network folder

### ISSUE THREAD

**Issue by apintocr** [firehol/netdata#2991]
Greetings,

I installed netdata and my /etc/network folder was erased, causing my server not to boot.

I'm using a Ubuntu 16.04 OpenVZ VPS.

Restoring the /etc/network/ folder from a backup solved the problem but it can be a major headache if the user doesn't know much about networking.

I used the one-liner install as recommended in the docs.

**Comment by ktsaou** [comment]
Hi,

netdata does not touch `/etc/network`.

I believe you will not be able to reproduce this by installing netdata.
Could you please try it?

I checked the source tree for any references to `/etc/network`. I couldn't find any.

```sh
# cd /path/to/netdata.git
# grep -R '/etc/network' *
<nothing printed>
```

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
