### ISSUE TITLE
Connector tomcat not collect full stats (only 4 over 8)

### ISSUE THREAD

**Issue by jneivil** [firehol/netdata#2996]
I install netdata ok
I use tomcat plugin ok but I only see 4 graphics of memory and not 4 graphs (access/bandwidth/processing_time/threads)

In my tomcat log all ok, except these graphs show me: was removed due to non updating.

In my netdata config:

localhost:
name: ...
url: ...
user: ...
pass: ...
connector: 'http-nio-8080'

localipv4:
name: ...
url: ...
user: ...
pass: ...
connector: 'http-nio-8080'

localipv6:
name: ...
url: ...
user: ...
pass: ...
connector: 'http-nio-8080'

My http://localhost:8080/managet/status?XML=true show me a full xml stats with all metrics and I don't understand why python plugin not is successed.

I debugged tomcat.chart.py and I detected that line 104 (https://github.com/firehol/netdata/blob/master/python.d/tomcat.chart.py) 

...
...
 if conn.get('name') == self.connector_name:
...
..

conn.get('name') has value "http-nio-8080" but self.connector_name has value http-nio-8080

There is a double quote before and after connector name.

I change:
      if conn.get('name').replace('"','') == self.connector_name:
by
       if conn.get('name') == self.connector_name:

and all ok.

**Comment by l2isbad** [comment]
thx @jneivil 
@Wing924 have a look

**Comment by Wing924** [comment]
@jneivil 
It looks wired.
Can you paste output of http://localhost:8080/managet/status?XML=true ?

**Comment by jneivil** [comment]
Información de Servidor
Apache Tomcat/8.0.24	
1.8.0_72-b15	
Oracle Corporation	
Linux	2.6.32-573.12.1.el6.x86_64	
amd64



Tomcat Status
JVM:	free:686599328	total:1055916032	max:1908932608
Memory Pools
Name:PS Eden Space	Type:Heap memory	Initial:268435456	Committed:321912832	Maximum:680001536	Used:259828560
Name:PS Old Gen	Type:Heap memory	Initial:716177408	Committed:716177408	Maximum:1431830528	Used:97735424
Name:PS Survivor Space	Type:Heap memory	Initial:44564480	Committed:17825792	Maximum:17825792	Used:11752720
Name:Code Cache	Type:Non-heap memory	Initial:2555904	Committed:50659328	Maximum:251658240	Used:50140992
Name:Compressed Class Space	Type:Non-heap memory	Initial:0	Committed:7340032	Maximum:1073741824	Used:6892280
Name:Metaspace	Type:Non-heap memory	Initial:0	Committed:64184320	Maximum:-1	Used:62032176
Connector -- "http-nio-8443"
threadInfo	maxThreads:150	currentThreadCount:10	currentThreadsBusy:0
requestInfo	maxTime:0	processingTime:0	requestCount:0	errorCount:0	bytesReceived:0	bytesSent:0
Stage	Time	B Sent	B Recv	Client	VHost	Request
Connector -- "ajp-nio-8009"
threadInfo	maxThreads:200	currentThreadCount:0	currentThreadsBusy:0
requestInfo	maxTime:0	processingTime:0	requestCount:0	errorCount:0	bytesReceived:0	bytesSent:0
Stage	Time	B Sent	B Recv	Client	VHost	Request
Connector -- "http-nio-8080"
threadInfo	maxThreads:200	currentThreadCount:24	currentThreadsBusy:1
requestInfo	maxTime:66572	processingTime:7873867	requestCount:28222	errorCount:333	bytesReceived:157461416	bytesSent:246764318

**Comment by jneivil** [comment]
![foto1 png](https://user-images.githubusercontent.com/10145194/32668696-97900468-c63e-11e7-88b9-e84bf9540136.png)
![foto2 png](https://user-images.githubusercontent.com/10145194/32668699-97ee1418-c63e-11e7-9845-d13cbecf2483.png)
![foto3 png](https://user-images.githubusercontent.com/10145194/32668700-981d8360-c63e-11e7-997b-3786f692dd98.png)

**Comment by Wing924** [comment]
@jneivil 
Can you show me the raw XML? (click view source)

**Comment by jneivil** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status>
   <jvm>
      <memory free="928197512" total="1059586048" max="1908932608" />
      <memorypool name="PS Eden Space" type="Heap memory" usageInit="268435456" usageCommitted="329252864" usageMax="687865856" usageUsed="21031200" />
      <memorypool name="PS Old Gen" type="Heap memory" usageInit="716177408" usageCommitted="716177408" usageMax="1431830528" usageUsed="103934928" />
      <memorypool name="PS Survivor Space" type="Heap memory" usageInit="44564480" usageCommitted="14155776" usageMax="14155776" usageUsed="6422408" />
      <memorypool name="Code Cache" type="Non-heap memory" usageInit="2555904" usageCommitted="50855936" usageMax="251658240" usageUsed="49875968" />
      <memorypool name="Compressed Class Space" type="Non-heap memory" usageInit="0" usageCommitted="7340032" usageMax="1073741824" usageUsed="6893288" />
      <memorypool name="Metaspace" type="Non-heap memory" usageInit="0" usageCommitted="64184320" usageMax="-1" usageUsed="62122688" />
   </jvm>
   <connector name="&quot;http-nio-8443&quot;">
      <threadInfo maxThreads="150" currentThreadCount="10" currentThreadsBusy="0" />
      <requestInfo maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" />
      <workers />
   </connector>
   <connector name="&quot;ajp-nio-8009&quot;">
      <threadInfo maxThreads="200" currentThreadCount="0" currentThreadsBusy="0" />
      <requestInfo maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" />
      <workers />
   </connector>
   <connector name="&quot;http-nio-8080&quot;">
      <threadInfo maxThreads="200" currentThreadCount="24" currentThreadsBusy="1" />
      <requestInfo maxTime="66572" processingTime="9246325" requestCount="36295" errorCount="457" bytesReceived="205025647" bytesSent="316022038" />
   </connector>
</status>

**Comment by jneivil** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status>
   <jvm>
      <memory free="928197512" total="1059586048" max="1908932608" />
      <memorypool name="PS Eden Space" type="Heap memory" usageInit="268435456" usageCommitted="329252864" usageMax="687865856" usageUsed="21031200" />
      <memorypool name="PS Old Gen" type="Heap memory" usageInit="716177408" usageCommitted="716177408" usageMax="1431830528" usageUsed="103934928" />
      <memorypool name="PS Survivor Space" type="Heap memory" usageInit="44564480" usageCommitted="14155776" usageMax="14155776" usageUsed="6422408" />
      <memorypool name="Code Cache" type="Non-heap memory" usageInit="2555904" usageCommitted="50855936" usageMax="251658240" usageUsed="49875968" />
      <memorypool name="Compressed Class Space" type="Non-heap memory" usageInit="0" usageCommitted="7340032" usageMax="1073741824" usageUsed="6893288" />
      <memorypool name="Metaspace" type="Non-heap memory" usageInit="0" usageCommitted="64184320" usageMax="-1" usageUsed="62122688" />
   </jvm>
   <connector name="&quot;http-nio-8443&quot;">
      <threadInfo maxThreads="150" currentThreadCount="10" currentThreadsBusy="0" />
      <requestInfo maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" />
      <workers />
   </connector>
   <connector name="&quot;ajp-nio-8009&quot;">
      <threadInfo maxThreads="200" currentThreadCount="0" currentThreadsBusy="0" />
      <requestInfo maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" />
      <workers />
   </connector>
   <connector name="&quot;http-nio-8080&quot;">
      <threadInfo maxThreads="200" currentThreadCount="24" currentThreadsBusy="1" />
      <requestInfo maxTime="66572" processingTime="9246325" requestCount="36295" errorCount="457" bytesReceived="205025647" bytesSent="316022038" />
   </connector>
</status>

**Comment by jneivil** [comment]
You can see

` <connector name="&quot;http-nio-8080&quot;">`

**Comment by Wing924** [comment]
@jneivil 
Thank you for your reporting.
I checked many tomcat status XML:
tomcat 8.5: `<connector name='"http-nio-8080"'>`
tomcat 7.0: `<connector name='"http-apr-8080"'>`

You're aright, the connector names contain quote in XML.
I'll send PR to make it easier to configure (add partial match)

But you can configure it in current version:
```
localhost:
name: ...
url: ...
user: ...
pass: ...
connector: '"http-nio-8080"'
```

**Comment by ktsaou** [comment]
merged it!
