### ISSUE TITLE
autoconf help

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#30]
@alonbl a little help:

1. I want files in conf.d not overwrite files already existing in `/etc/netdata`. I can't figure out how to do it. Now, every time I `make install` the files `/etc/netdata/apps_groups.conf` and `/etc/netdata/charts.d.conf` are overwritten.

2. Is there an official way to add the user `netdata` and chown the web files during `make install`?

    Initially I added this to `web/Makefile.am`, but I didn't know if this is good, so I removed it:

    ```sh
install-data-hook:
        if [ `id -u` == 0 ]; then \
                getent group netdata > /dev/null || groupadd -r netdata; \
                getent passwd netdata > /dev/null || useradd -r -g netdata -c netdata -s /sbin/nologin -d / netdata; \
                chown -R netdata $(DESTDIR)$(cachedir) $(DESTDIR)$(webdir); \
        fi

```

**Comment by alonbl** [comment]
You should understand the split between build and packaging.

The build should minimize touch of system, please do not add create users and such, these belong to packaging, see the spec file for details.

Same for files that are being overridden, it is best to not reach to this state so product provide its defaults in /usr/share/netdata/conf.d while read /etc/netdata/conf.d for override. Or use downstream mechanism to avoid overwrite, I will push a patch for this. The problem with the downstream mechanism is that if your application requires a new variable it will fail to start until user actually fix his system.

**Comment by alonbl** [comment]
just another note... nobody should do make install these days as root... as it is violate the integrity of the system and package manager by adding  untracked files to /usr.

what distro are you using? if not rpm based I will try to add your variant of packaging.

**Comment by ktsaou** [comment]
The problem I have is that most users that install netdata these days, are doing it directly from github. I have provided a `netdata-installer.sh` script in the repo that will automate configuration and build for new users. This will do `make install` so, it will eventually touch the system (add the user, fix permissions, etc).

Regarding missing configurations, `netdata` provides internal defaults for all settings, so it will start even if the configuration is absent or different. My problem are the overwrites. If you download and build a new version of it directly from github, you will loose your previous configuration. This is wrong. It should not happen.

I am using many distros. I develop on Gentoo, but I use on production almost everything.

**Comment by ktsaou** [comment]
The patch is still overwritting files in /etc/netdata:

```sh
make install

Making install in charts.d
make[1]: Entering directory '/data/src/netdata.git/charts.d'
make[2]: Entering directory '/data/src/netdata.git/charts.d'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/libexec/netdata/charts.d'
 /usr/bin/install -c README.md airsearches.chart.sh cpu_apps.chart.sh cpufreq.chart.sh crsproxy.chart.sh example.chart.sh load_average.chart.sh mem_apps.chart.sh mysql.chart.sh nut.chart.sh opensips.chart.sh postfix.chart.sh sensors.chart.sh squid.chart.sh '/usr/libexec/netdata/charts.d'
make[2]: Leaving directory '/data/src/netdata.git/charts.d'
make[1]: Leaving directory '/data/src/netdata.git/charts.d'
Making install in conf.d
make[1]: Entering directory '/data/src/netdata.git/conf.d'
make[2]: Entering directory '/data/src/netdata.git/conf.d'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/etc/netdata'
 /usr/bin/install -c -m 644 charts.d.conf apps_groups.conf '/etc/netdata'
make[2]: Leaving directory '/data/src/netdata.git/conf.d'
make[1]: Leaving directory '/data/src/netdata.git/conf.d'
Making install in plugins.d
make[1]: Entering directory '/data/src/netdata.git/plugins.d'
make[2]: Entering directory '/data/src/netdata.git/plugins.d'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/libexec/netdata/plugins.d'
 /usr/bin/install -c -m 644 README.md '/usr/libexec/netdata/plugins.d'
 /bin/mkdir -p '/usr/libexec/netdata/plugins.d'
 /usr/bin/install -c charts.d.dryrun-helper.sh charts.d.plugin tc-qos-helper.sh loopsleepms.sh.inc '/usr/libexec/netdata/plugins.d'
make[2]: Leaving directory '/data/src/netdata.git/plugins.d'
make[1]: Leaving directory '/data/src/netdata.git/plugins.d'
Making install in src
make[1]: Entering directory '/data/src/netdata.git/src'
make[2]: Entering directory '/data/src/netdata.git/src'
 /bin/mkdir -p '/usr/sbin'
  /usr/bin/install -c netdata '/usr/sbin'
 /bin/mkdir -p '/var/cache/netdata'
 /usr/bin/install -c -m 644 .keep '/var/cache/netdata'
 /bin/mkdir -p '/var/log/netdata'
 /usr/bin/install -c -m 644 .keep '/var/log/netdata'
 /bin/mkdir -p '/usr/libexec/netdata/plugins.d'
  /usr/bin/install -c apps.plugin '/usr/libexec/netdata/plugins.d'
make  install-data-hook
make[3]: Entering directory '/data/src/netdata.git/src'
if [ `id -u` == 0 ]; then \
        chown root '/usr/libexec/netdata/plugins.d/apps.plugin' && \
                chmod 4755 '/usr/libexec/netdata/plugins.d/apps.plugin'; \
else \
        echo; \
        echo "ATTENTION"; \
        echo; \
        echo "setuid bit of /usr/libexec/netdata/plugins.d/apps.plugin must be set, please execute as root:"; \
        echo "chown root '/usr/libexec/netdata/plugins.d/apps.plugin' && chmod 4755 '/usr/libexec/netdata/plugins.d/apps.plugin'"; \
        echo; \
fi
make[3]: Leaving directory '/data/src/netdata.git/src'
make[2]: Leaving directory '/data/src/netdata.git/src'
make[1]: Leaving directory '/data/src/netdata.git/src'
Making install in web
make[1]: Entering directory '/data/src/netdata.git/web'
make[2]: Entering directory '/data/src/netdata.git/web'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/share/netdata/web'
 /usr/bin/install -c -m 644 datasource.html index.html index.js netdata.js robots.txt theme.css '/usr/share/netdata/web'
make[2]: Leaving directory '/data/src/netdata.git/web'
make[1]: Leaving directory '/data/src/netdata.git/web'
make[1]: Entering directory '/data/src/netdata.git'
make[2]: Entering directory '/data/src/netdata.git'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/data/src/netdata.git'
make[1]: Leaving directory '/data/src/netdata.git'
```

**Comment by alonbl** [comment]
I find it hard to believe anyone installs as root without packaging, this is violation of all distro rules, as you progress with build system you should also understand this.

To build and install rpm you run:
```
autoreconf -ivf && ./configure && make dist && rpmbuild -tb <tarball> && rpm -i <rpm>
```
I also use gentoo I will send you an ebuild.

**Comment by alonbl** [comment]
> The patch is still overwritting files in /etc/netdata:

the patch is for rpm distro.
portage will also protect config files.
if you want to have non standard complex build system without downstream doing its work, I am not the right contact.

**Comment by alonbl** [comment]
I sent you an ebuild.
As you progress in build system, you should also consider adjusting to package managers.
In any case, if you insist the Makefile.am is plain Makefile, you can add there whatever you want, I strongly recommend of not doing that.

**Comment by alonbl** [comment]
> Regarding missing configurations, netdata provides internal defaults for all settings, so it will start even if the configuration is absent or different.

so why do you place anything at /etc? maybe you should just create empty directory and put examples at /usr/share?

**Comment by ktsaou** [comment]
Thanks for the ebuild. You are the best!

> so why do you place anything at /etc? maybe you should just create empty directory and put examples at /usr/share?

It is a bit more complex. The netdata daemon has good internal defaults for everything, its configuration can be downloaded from the daemon itself (http://127.0.0.1:19999/netdata.conf). So the user can download it and customize it.

Then there are plugins. netdata will attempt to run all installed plugins by default. It is up to them to find out if they can work on the given system.

Plugins may need some configuration.

For example, `apps.plugin` which collects information about the running processes, groups tasks together and reports data to netdata for the groups. It needs some configuration for this grouping. I have supplied sensible defaults (`app_groups.conf`), but the user may need to customize it.

Another plugin called `charts.d.plugin` allows writing plugins in BASH that are loaded into memory once (they are functions) and it runs them in a loop to collect data. each of these sub-plugins can either autodetect if it is capable of running on the current system (zero configuration), or needs some additional configuration.

I need somehow to supply a `charts.d.conf` file that will have by default enabled all sub-plugins that can autodetect if they can run, and disabled all those that need manual configuration.

So, this is the whole thing with configuration files.

I think that the best possible way is to supply files in /etc/netdata with the suffix `.conf.dist` meaning that these files are the distribution defaults. If the same file with `.conf` extension does not exist, it would be safe to copy `.conf.dist` to `.conf` to get a default configuration.

**Comment by alonbl** [comment]
again... either have defaults within application and examples, or have /usr/share/netdata/conf.d with app default and allow /etc/netdata/conf.d to override. in either case there should be no conflict when installing/upgrading package.

generating configuration "from the daemon" should not be done at all, it should be generated statically when built as a base for user to override specific vars, this is what conf.d is for.

conf.d definition is replacement of config file with multiple files. in shell it essentially:
```
DEFAULTS="/usr/share/xxx/defaults.conf"
CONFIG=/etc/xxx.conf
. "${DEFAULTS}"
[ -e "${CONFIG}" ]; . "${CONFIG}"
for config in "${CONFIG}".d/*.conf; do
    . "${config}"
done
```

In this example, once defaults are:
```
var1=aaaa
var2=bbbb
var3=cccc
```
If user wishes to modify var2 it should put /etc/xxx.conf.d/50-my-config.conf with only:
````
var2=llll
```
This way if product default changes it is accepted without conflict, also different packages can put different config files at conf.d to override each by alphabetic order.
