### ISSUE TITLE
PowerDNS does not show up

### ISSUE THREAD

**Issue by nobody-nobody** [firehol/netdata#3002]
Hi there,

using the latest netdata release (updated some minutes ago).
I cant get the powerdns chart to show up.
python.d/powerdns.conf:
```
localhost:
 name : 'local'
 url : 'http://127.0.0.1:8083/api/v1/servers/localhost/statistics'
 header:
  X-API-Key: 'api-key-i-set'
```
I can see the stats when I use wget:
`wget -O- --header="X-API-Key: api-key-i-set"  http://127.0.0.1:8083/api/v1/servers/localhost/statistics`

Searching the internet I found that I can run a query manually with python.d.plugin so I tried:
`sudo -u netdata /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 powerdns`
That seem to work since I can see some data...

I am new to netdata so I dont know how to debug this problem...

Thanks!

**Comment by l2isbad** [comment]
> That seem to work since I can see some data...

please post the output here

and i suggest to 

`cd to netdata log dir`
`grep powerdns error.log`

**Comment by nobody-nobody** [comment]
Hi,

error.log and output of python.d.plugin is attached.
I could not find powerdns in the errorlog so might it be possible that it is just not loading at all?
I attached netdata.conf too.

[error.log](https://github.com/firehol/netdata/files/1464607/error.log)
[netdata-powerdns.txt](https://github.com/firehol/netdata/files/1464608/netdata-powerdns.txt)
[netdata.conf.txt](https://github.com/firehol/netdata/files/1464613/netdata.conf.txt)

Thanks

**Comment by l2isbad** [comment]
> I could not find powerdns in the errorlog so might it be possible that it is just not loading at all?

show your [python.d.conf](https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf)

**Comment by nobody-nobody** [comment]
Yup... thats it :)
Somehow I overlooked this config file. Powerdns was not included.

Thank you very much for your help!
