### ISSUE TITLE
Alarm for big system load

### ISSUE THREAD

**Issue by dpanic** [firehol/netdata#3003]
Perhaps it will be good to have alarm for big system load, calculated by number of CPUs on machine.

**Comment by ktsaou** [comment]
based on `system.load` or something else?
Can you describe the alarm?

**Comment by thomasleveil** [comment]
I wish we had an alarm for:
_load average over 10 minute_ > number of CPUs

**Comment by ktsaou** [comment]
hm... I think I can add the number of processors to a health variable....

**Comment by ktsaou** [comment]
Can you check how many processors `/proc/stat` lists when you shut a few of them? The way I implemented this, is that it gets updated every seconds to match the number of cores listed in `/proc/stat`.
