### ISSUE TITLE
System overview forum integration

### ISSUE THREAD

**Issue by MrYoshii** [firehol/netdata#3006]
Hi, guys i have a question.

i have a Forum https://darkside-gaming.at is it possible to get only the system overview shown on the mainpage of the forum?

**Comment by ktsaou** [comment]
It is generally simple. Include `dashboard.js` and add a `div` for each chart.

1. These are the DIVs for the overview: https://github.com/ktsaou/netdata/blob/eeddf788996eac7f91723742bc7fd13ebbe5e5fd/web/index.html#L1462-L1619 . You can also find them by inspecting them with your browser.

2. `dashboard.js` uses several variables you can define before sourcing it: https://github.com/ktsaou/netdata/blob/35e2322e06c857bf19ef408ddd09e357bbe8d6a3/web/dashboard.js#L4-L47 . Adapt them to your needs (for example, you many need to tell it to not load bootstrap).

3. You can find documentation for custom dashboards here: https://github.com/firehol/netdata/wiki/Custom-Dashboards

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
