### ISSUE TITLE
Can netdata be used to watch data from other devices that don't have netdata installed?

### ISSUE THREAD

**Issue by jtlindsey** [firehol/netdata#3012]
Can netdata be used to watch data from other devices that don't have netdata installed? For example: I have a network switch that i can point to a syslog server. So i setup Ubuntu Server as the target, configured `/etc/rsyslog.conf` and then installed netdata on it. Can this work or is this outside the intended use of netdata?

**Comment by ktsaou** [comment]
Most of the netdata plugins are able to collect data from multiple servers, local and remote.
So, I am not sure what exactly you need to monitor remotely, but if you find a way for a netdata to have access to it, yes it can monitor it.

**Comment by jtlindsey** [comment]
> Most of the netdata plugins are able to collect data from multiple servers, local and remote.
> So, I am not sure what exactly you need to monitor remotely, but if you find a way for a netdata to have access to it, yes it can monitor it.

I was trying to monitor all info, notice, warnings, etc from my switch. When i google "netdata module syslog" all the information I'm finding is offering information with the expectation the user wants to monitor local data or data from another machine that is running netdata.

I've installed netdata. Setup was super easy following the docs. Can you point me to the documentation that discusses how to use netdata to collect information from systems that just send data to and IP and port but don't have netdata installed? I'm trying to send data from a network switch logs and then I would like to setup my Dell server IDRAC to send data to it as well.

**Comment by nobody-nobody** [comment]
How about writing a plugin for that?
Just collect (e.g. ssh, listen on port for incoming) and parse the data and create shapes which presents it.

**Comment by l2isbad** [comment]
>  Can you point me to the documentation that discusses how to use netdata to collect information from systems that just send data to it via IP and port but don't have netdata installed themselves?

What information do you need to collect from remote device?

> I'm trying to send data from a network switch logs

Netdata is not syslog server.

**Comment by jtlindsey** [comment]
@l2isbad from @ktsaou 's reply from my original post:

> Most of the netdata plugins are able to collect data from multiple servers, local and remote

Was leading me to believe the answer to my original question must be that what I'd like to do is NOT outside of scope for what netdata was intended for.

> What information do you need to collect from remote device?

I've answered that in my second post:

> I was trying to monitor all info, notice, warnings, etc from my switch

And similar data from multiple devices like [IDRAC](http://www.dell.com/support/manuals/tc/en/tcdhs1/idrac8-with-lc-v2.05.05.05/idrac8_2.05.05.05_ug-v1/configuring-remote-system-logging-using-web-interface?guid=guid-4550d811-135e-45bc-ab0c-49d8ddc7cc99&lang=en-us) or similar devices that I cannot install netdata on. From what i can see right now, it looks like netdata is only useful for monitoring systems that have netdata installed. I realize netdata is not a syslog server. From the first post scenario, if I setup Linux to collect information from other devices (_because it can be setup as a syslog server_), can i use netdata to monitor that data? Or is that beyond what netdata was intended to be used for?

@nobody-nobody for Linux as syslog I'm already listening on port 514 which works for at least getting data from other devices. Are you saying all I have to do at this point is write a plugin similar to [here](https://github.com/firehol/netdata/tree/master/node.d)? That would work for devices that broadcast information like the Fronius Symo and accept connections via IP and PORT. But what about devices that just send information to another IP and PORT like a log server from a network switch or Dell iDRAC? Are there existing modules or documentation for creating modules that just parse information from local logs of data from external devices?

**Comment by fossxplorer** [comment]
+1 @jtlindsey I have some sort of same need, particularly iDRAC/iLO/Supermicro's IPMI (BMCs in general). Docker is being mentioned with netdata, but how? Do we need to build netdata into the Docker image that we wish to monitor? Or can it pull data while being installed on a Docker host for all running Docker instances? 

The ones i know about, e.g being Zabbix and Ganglia all need a local daemon running that collects and stores the data locally on each devices. Then a master node will pull the data from each nodes.

**Comment by Ferroin** [comment]
For Docker and other container systems, you run netdata on the host, and it auto-detects the containers and monitors them without needing anything internal to the container.

Regarding the way it works on a network:  Each host system runs netdata.  You can choose whether you want to push stats to a central system or not (you can only get aggregate data if you do), but even if you do, you can still talk to individual systems directly to get stats for them.

Regarding IPMI:  I'm pretty sure there isn't an IPMI data collection module (though there is an SNMP one), but it should in theory not be hard to write one.

**Comment by ktsaou** [comment]
There is an IPMI module for netdata. It is enabled automatically if the system has freeipmi development packages installed. You can also enable it by passing `--enable-plugin-freeipmi` to `netdata-installer.sh`.

In general netdata can monitor anything it can have access to. We usually build plugins to collect specific metrics from specific sources. Writing netdata plugin is relatively easy.

So, if you want to monitor something we don't have a plugin already, you have the following options:

1. Write a shell script to do it. There are many examples available. The script will collect the info and push it to netdata. This is the simplest if you are not a developer, but the least efficient too.

   I usually start with this, for quickly getting something monitored. Even if you have a feed of something, you can easily turn a `tail -f xxx.log | awk -f script.awk` to a netdata plugin. If you search the issues you will find 1-2 versions of such cases.

2. Write it in python. This is widely used and quite easy ( thanks to @l2isbad ).

3. Write it in node.js. If you know javascipt, this is the way to go.

4. etc

Any language can be used. Python is the preferred, but any will do.

So, first find the source, then turn it to metrics, then feed the metrics somehow to netdata.

Keep in mind netdata is also a statsd server. Many enterprise apps support statsd, so have a look there too.

**Comment by magao** [comment]
Presumably your syslog server is generating output somewhere (e.g. writing to a file). You could write a plugin that tailed that file parsing out the data from devices sending to it.

As a similar example, I have a DSL router that I have ssh access to, but can't install netdata on. I wrote a plugin running on my QNAP's NetData instance to ssh into the router and retrieve data such as DSL stats (e.g. line rate), pinging the first hop and `/proc/net/dev` and `/proc/net/ip_conntrack` (to do an approximate breakdown of internet traffic by client). I then parse the output on the QNAP and turn them into metrics (as an implementation detail, I do the retrieval and parsing on a separate thread so that it doesn't interfere with other plugins - the main plugin thread simply returns the most recent stats to NetData).

**Comment by jtlindsey** [comment]
@ktsaou thanks for the confirmation. I found one of the threads your mentioned here that is using tail in a plugin:
https://github.com/firehol/netdata/issues/1495  and the `web_log` plugin here:
https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file#tail-the-log

So i will get to work playing with options 1-3. @magao that is good to know. Also I didn't realize i could put netdata on Synology or QNAP until i read your comment.

**Comment by ktsaou** [comment]
This is a good example of `tail | awk` plugin: https://github.com/firehol/netdata/pull/628#issuecomment-229776351

web_log is perfect for web server log files. There are also simpler python versions you can adapt.
