### ISSUE TITLE
Inacurrate network data.

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#3013]
Hi, I,m trying to visualize redis network usage with netdata-prometheus-grafana stack.
While host network traffic shows correctly, redis network usage is higher than host network usage.
I think that's not possible. Here is the chart screenshot link and queries.
`abs(netdata_redis_net_kilobits_persec_average{instance='$host',dimension='out'})`
`abs(netdata_system_net_kilobits_persec_average{instance='$host',dimension='sent'})`

https://screencast.com/t/6NCoNBCIX1lr

**Comment by ktsaou** [comment]
Could you please provide the same info from the netdata charts?

**Comment by vaheminasyan** [comment]
Could you please guide me how to do that?

**Comment by vaheminasyan** [comment]
Maybe this is what we need.

I made 2 queries at the same time:
First for redis_local.net chart:
curl 'http://localhost:19999/api/v1/data?chart=redis_local.net&after=-1&format=datasource&options=nonzero'


`google.visualization.Query.setResponse({version:'0.6',reqId:'0',status:'ok',sig:'1510687461',table:{
 "cols":
 [
        {"id":"","label":"time","pattern":"","type":"datetime"},
        {"id":"","label":"","pattern":"","type":"string","p":{"role":"annotation"}},
        {"id":"","label":"","pattern":"","type":"string","p":{"role":"annotationText"}},
     {"id":"","label":"in","pattern":"","type":"number"},
     {"id":"","label":"out","pattern":"","type":"number"}
  ],
    "rows":
 [
        {"c":[{"v":"Date(2017,10,14,19,24,21)"},{"v":null},{"v":null},{"v":27919.13},{"v":-1658393.4}]}
  ]
}});`

And second for system.ipv4 chart
curl 'http://localhost:19999/api/v1/data?chart=system.ipv4&after=-1&format=datasource&options=nonzero


`google.visualization.Query.setResponse({version:'0.6',reqId:'0',status:'ok',sig:'1510687460',table:{
 "cols":
 [
        {"id":"","label":"time","pattern":"","type":"datetime"},
        {"id":"","label":"","pattern":"","type":"string","p":{"role":"annotation"}},
        {"id":"","label":"","pattern":"","type":"string","p":{"role":"annotationText"}},
     {"id":"","label":"received","pattern":"","type":"number"},
     {"id":"","label":"sent","pattern":"","type":"number"}
  ],
    "rows":
 [
        {"c":[{"v":"Date(2017,10,14,19,24,20)"},{"v":null},{"v":null},{"v":25014.37},{"v":-1052561.8}]}
  ]
}});`

**Comment by vaheminasyan** [comment]
Another query result.
Redis: `{"c":[{"v":"Date(2017,10,14,19,31,10)"},{"v":null},{"v":null},{"v":23334.83},{"v":-1318197}]}`
Host:  `{"c":[{"v":"Date(2017,10,14,19,31,10)"},{"v":null},{"v":null},{"v":24789.17},{"v":-914292.4}]}`

**Comment by ktsaou** [comment]
ok.

1. `system.ipv4` is what the system reports as the total IPv4 traffic of the host.
2. `redis.net` is what redis reports as its bandwidth.
3. there is also `system.ipv6` that reports IPv6 traffic (in many cases this includes localhost traffic).
4. in recent versions of netdata, I have also added `system.net`. This is the sum of the bandwidth of all **physical** network interfaces. It does not include `lo`, VPNs, host to container traffic, host to VM traffic and it does not care about IPv4 and IPv6 (it uses the network interfaces' counters).

In your case, the fact is that your redis believes it has that traffic. But at the same time, traffic is accounted in many ways. So, I think you somehow missing redis traffic that is not accounted at `system.ipv4`.

**Comment by vaheminasyan** [comment]
Thanks.
Let me update my netdata installation to the latest version and check again.

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but if you need help just post.
