### ISSUE TITLE
Using a HTTP proxy in the updater cron job

### ISSUE THREAD

**Issue by willyb321** [firehol/netdata#3016]
Hi, I run netdata at a place that requires proxy for all non-local traffic, and was wondering if there was any way to export a proxy in the netdata updater script. At the moment, it just fails to update because it doesn't pick up the proxy.

Thanks.

**Comment by ktsaou** [comment]
hm... you can delete the update script from your /etc/cron.daily and add something like this:

```sh
#!/bin/sh
export http_proxy="http://10.1.1.1:3128/"
export https_proxy="http://10.1.1.1:3128/"
/usr/src/netdata.git/netdata-updater.sh
```

Don't name your script `/etc/cron.daily/netdata-updater`, because it will be deleted by the installer and replaced by the default. Name it something else.

**Comment by willyb321** [comment]
Ahh awesome will give it a try and report back. Thanks

**Comment by willyb321** [comment]
It works! Thanks very much! Will close this now.
