### ISSUE TITLE
Monitoring smartd attributes improvements

### ISSUE THREAD

**Issue by skibbipl** [firehol/netdata#3017]
Old discussion in #2889
1. Make the smartd plugin "smarter". Parse smartd_log files only if they're updated in the last X (configurable) days. This will filter old smartd data for disks that are not used on the machine any more.
2. Allow plugin to detect external drives when they're connected to the machine. This is totally optional.

**Comment by ktsaou** [comment]
@l2isbad could you please help?

**Comment by l2isbad** [comment]
will do

**Comment by l2isbad** [comment]
@ktsaou 
somehow i need to remove dimensions from chart in runtime.
The only way i can do it is to make them hidden, right?

**Comment by ktsaou** [comment]
> The only way i can do it is to make them hidden, right?

I think so. Why you need to remove them? If this is generally needed, we should probably extend the plugins protocol a bit.

**Comment by l2isbad** [comment]
> I think so. Why you need to remove them?

I need to remove them because `smartd_log` chart dimensions are disks (chart per attribute not per disk).

To add support for 

> Allow plugin to detect external drives when they're connected to the machine

without restart of netdata.

adding/removing (new disks, old (not updated in X minutes) disk in runtime.

> If this is generally needed, we should probably extend the plugins protocol a bit.

Not sure about that. Set/unset 'hidden' works nice.

**Comment by ktsaou** [comment]
merged it
