### ISSUE TITLE
dns_query_time doesn't seem to process IPv6 servers

### ISSUE THREAD

**Issue by Komic** [firehol/netdata#3019]
Just tried adding my provider's IPv6 DNS servers (`dns_servers: '2001:bc8:401::3 2001:bc8:1::16 62.210.16.6 62.210.16.7'`), netdata doesn't seem to process them. IPv4 still works fine.

**Comment by l2isbad** [comment]
@Komic 
i believe the problem is 
https://github.com/firehol/netdata/blob/master/python.d/dns_query_time.chart.py#L110-L114

To make the plugin work just replace it with (quick fix)

```python
def check_ns(ns):
    return True
``` 

i will fix it soon

**Comment by wungad** [comment]
Fixed in a20b74c, included in #3051

**Comment by Komic** [comment]
thanks, closing!~
