### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by alexillsley** [firehol/netdata#3028]
Hi, 

is it possible to get the hostname from netdata to include in an html dashboard?

Thanks

**Comment by ktsaou** [comment]
Will this do?

```
http://registry.my-netdata.io/api/v1/registry?action=hello
```

It gives:

```
{
	"action": "hello",
	"status": "ok",
	"hostname": "london.my-netdata.io",
	"machine_guid": "79dd9dbc-189e-11e6-904a-0401d1165f01",
	"registry": "https://registry.my-netdata.io"
}
```

**Comment by alexillsley** [comment]
Thanks worked perfectly, was able to embed host name now using

<h3 id="hostnames"></h3>
<script> 
var request = new XMLHttpRequest();
request.open('GET', '/api/v1/registry?action=hello', true);

request.onload = function() {
  if (request.status >= 200 && request.status < 400) {
    // Success!
    var data = JSON.parse(request.responseText);
        document.getElementById("hostnames").innerHTML=data["hostname"];
  } else {
    // We reached our target server, but it returned an error
    
  } 
};

request.onerror = function() {
  // There was a connection error of some sort
};

request.send();

</script>
