### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by Nirjonadda** [firehol/netdata#3031]
Please let me know that How we can disable email notifications?

**Comment by ktsaou** [comment]
You can disable email notifications by editing `/etc/netdata/health_alarm_notify.conf` and setting `SEND_EMAIL="NO"`, here: https://github.com/firehol/netdata/blob/f314f1d841d328744bc83a1dfb2b427ab806f126/conf.d/health_alarm_notify.conf#L111

You can disable all the alarms in netdata, by editing `/etc/netdata/netdata.conf` and setting

```
[health]
  enabled = no
```

**Comment by Nirjonadda** [comment]
@ktsaou Today i have installed in new server but does not find out `/etc/netdata/health_alarm_notify.conf`

**Comment by Nirjonadda** [comment]
![screenshot00375](https://user-images.githubusercontent.com/6899856/46167926-64b16e00-c297-11e8-857b-2ddbe1f56f1b.png)

**Comment by paulfantom** [comment]
@Nirjonadda we just changed placing of configuration files and whole config management. You can read more in https://github.com/netdata/netdata/issues/4182

**Comment by Nirjonadda** [comment]
@paulfantom So file location changed? I have found this files both location. So what location we can use for disable email notifications?

`/root/netdata/conf.d/health_alarm_notify.conf`

`/usr/lib/netdata/conf.d/health_alarm_notify.conf`

**Comment by Nirjonadda** [comment]
`/root/netdata/conf.d/health_alarm_notify.conf`

![screenshot00376](https://user-images.githubusercontent.com/6899856/46168398-a8f13e00-c298-11e8-87a3-af9ad21bce9c.png)

`/usr/lib/netdata/conf.d/health_alarm_notify.conf`

![screenshot00377](https://user-images.githubusercontent.com/6899856/46168404-ad1d5b80-c298-11e8-822f-a51b5ca970ca.png)

**Comment by Ferroin** [comment]
If the file exists in `/etc/netdata`, it will override anything located in `/usr/lib/netdata/conf.d`.  Using this, you can copy the file to `/etc/netdata` and edit it there just like you would have before the change to disable email notifications.

**Comment by Nirjonadda** [comment]
@Ferroin How to copy from `/usr/lib/netdata/conf.d` to `/etc/netdata`?

**Comment by Nirjonadda** [comment]
@paulfantom One more ask, So need copy from `/usr/lib/netdata/conf.d` to `/etc/netdata` because netdata update or upgrade will be overwriting this files?

**Comment by ktsaou** [comment]
Yes, the files in `/usr/lib/netdata/conf.d` get overwritten with updates. The files in `/etc/netdata` do not.

So, just copy the file you need and then edit it.

**Comment by Nirjonadda** [comment]
@paulfantom Not working to copy. I think does not have `conf.d` folder in `/etc/netdata`?

````
[root@ra ~]# cp /usr/lib/netdata/conf.d/health_alarm_notify.conf /etc/netdata/conf.d/
cp: cannot create regular file ‘/etc/netdata/conf.d/’: Not a directory
[root@ra ~]#
````

**Comment by paulfantom** [comment]
@Nirjonadda 

```bash
mkdir -p /etc/netdata/conf.d/
cp /usr/lib/netdata/conf.d/health_alarm_notify.conf /etc/netdata/conf.d/
```
