### ISSUE TITLE
[question] Alarm on Java method execution timeout supported?

### ISSUE THREAD

**Issue by archenroot** [firehol/netdata#3032]
Hello,

can I monitor and alarm on timeout java method execution?

**Comment by ktsaou** [comment]
hm... probably with JMX plugin?
@simonnagl can you help?

**Comment by simonnagl** [comment]
Mhm... Then there needs to be an JMX MBean that detects and exposes the timeout. There is no metric I know coming with the JVM. @archenroot, how do you detect the timeout for now? Is it in code you maintain? If there is a way to detect it it would be possible to put it into an netdata plugin and write an alarm for it.

**Comment by archenroot** [comment]
@simonnagl so far I use AspectJ for automated logging of entry/exit, and I do post log analysis...but Thought it could be available as kind of metric.... let me think...

**Comment by simonnagl** [comment]
Having an aspect which can detect the timeout you could easily write an MBean to expose it. Here is a tutorial for Standard MBeans.
https://docs.oracle.com/javase/tutorial/jmx/mbeans/standard.html

When exactly do you want to trigger an alarm? If any method takes longer then a specific threshold? If you can tell me more about what you want to to, maybe I can help.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
