### ISSUE TITLE
Add ability to restart disabled plugin without restarting service

### ISSUE THREAD

**Issue by magao** [firehol/netdata#3037]
I have some external data sources where the data may not be available for a period of time, but then come back. Currently this results in the plugin being disabled and needing to restart the NetData service.

It would be useful if we could flag a plugin to be periodically re-checked if disabled, and if it passes restart the plugin (in fact, just restarting would be enough I guess). Something like:

```
[plugin]
recheck disabled = 5m
```
to recheck every 5 minutes after it had been disabled. Default would be not to re-check.

**Comment by ktsaou** [comment]
Which one?

1. internal netdata plugins usually persist (there are exceptions though)
2. python.d.plugin already has the option `autodetection_retry: SECONDS` to persist checking. It supports this per module and per module job.
3. node.d.plugin does not have such option - we should support `autodetection_retry`, but it is not there yet.
4. charts.d.plugin does not have such option - we should support `autodetection_retry`, but it is not there yet.

Keep in mind that if you kill any netdata plugin, netdata will restart it after a few seconds (configurable via netdata.conf), forcing it to re-check all its modules.

So, which one?

**Comment by magao** [comment]
Ideally all of them, but primarily python.d.plugin (for my own plugins) and charts.d.plugin (I'm having trouble with a UPS attached to one of my QNAPs ... stops being detected sometimes).

I was totally unaware of `autodetection_retry:` for python.d.plugin. Looks like it's post-1.8.0 - I might have to grab the latest source and upgrade python.d.plugin.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
