### ISSUE TITLE
3 servers, 1 dashboard

### ISSUE THREAD

**Issue by domacikolaci** [firehol/netdata#3039]
Hi,

Ive been doing some googling, and everywhere I go I see I have to make a custom dashboard just to view 3 different dashboards in 1. Here is what I want to be able to do

- Myself and my team go to a webpage external to the network
- A server dashboard loads
- We then are able to switch between dashboards to see other servers

Is this possible? Im bassed in another company, but manage $client's systems and want to view all their stats, and also present this to the client to view. Got the alerts going to slack, just need this now!

**Comment by domacikolaci** [comment]
Noone? I was thinking an nginx conf that might forward all of this but not to sure, haven't messed with nginx much. Has anyone done a similar setup?

**Comment by ktsaou** [comment]
Hi, you can setup an nginx to proxy all your netdata and you can add authentication to it.
Check the wiki: https://github.com/firehol/netdata/wiki/Running-behind-nginx

So the idea is:

1. configure all your netdata to accept connection only from nginx
2. configure your nginx to proxy all your netdata
3. configure your nginx to support authentication
4. share the nginx URL with your colleagues or customers

**Comment by ktsaou** [comment]
You need a custom dashboard, only if you want to view selected charts from all servers on one web page.

**Comment by domacikolaci** [comment]
Thanks for that @ktsaou ! I'll give it all a shot over the next couple days (Few things going on with the clients servers atm ;) ) Appreciate the help though!

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
