### ISSUE TITLE
Fake Api consumer

### ISSUE THREAD

**Issue by zohaib85** [firehol/netdata#3040]
Can some guide me how to get / setup fake api consumers?
I want to validate all existing rest / soap APIs with some sort of test and display data on netdata dashboard.

Thanks in advance.

**Comment by zohaib85** [comment]
Reference to quora.
![image](https://user-images.githubusercontent.com/13233663/33018949-423fc962-cdf0-11e7-9435-e075523e79cb.png)

**Comment by ktsaou** [comment]
Hi,

netdata is able to execute any command to test any API. So, if you have a `curl` command, or any other command, that can test your API, you can easily turn this to a netdata plugin. You can do it with:

- [plain shell scripting](https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh)
- [python](https://github.com/firehol/netdata/tree/master/python.d)
- [node.jd](https://github.com/firehol/netdata/tree/master/node.d)

or any other language you are familiar with. The netdata [plugin protocol is pretty simple](https://github.com/firehol/netdata/wiki/External-Plugins).

This however is sampling. So you will make a test per second, or every few seconds to find out if your API works.

The best way is to give netdata access to your web server logs. This way you will have a holistic view of your API. You will get alarms when your API malfunctions, even if the specific sampling test succeeds. With minor web server configuration tweaking, you can also get statistics about the response timings of your API, like this (the first chart is bandwidth, the second is timings):

![screenshot from 2017-11-23 23-24-35](https://user-images.githubusercontent.com/2662304/33188804-83fe9466-d0a5-11e7-8e88-286c01e488b3.png)

or even get a break-down for the API methods called:

![screenshot from 2017-11-23 23-25-33](https://user-images.githubusercontent.com/2662304/33188816-aae6686a-d0a5-11e7-845c-fb76a585653e.png)

If netdata runs on the same host with the web server, netdata could also monitor the web server itself or your applications server (via its process id). So, you could configure it to trigger alarms if the process stops, or the number of sockets it has falls below a threshold, etc.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
