### ISSUE TITLE
Smartd temperature attribute reporting issues

### ISSUE THREAD

**Issue by skibbipl** [firehol/netdata#3041]
Hello,
Some of my disks are reporting differently S.M.A.R.T attribute 194 (temperature). This causes some strange results in netdata - temperature is displayed as billions of degrees:
![obraz](https://user-images.githubusercontent.com/4746858/33020251-d91f6740-cdfd-11e7-8acf-bb24e901785f.png)
I checked the smartmontools csv files and it seems some disks report data in a different manner:
```
normal data (WD drives) - netdata displays correct temperature:
194;110;37;

strange data (Seagate and Samsung drives) - netdata displays billions of degrees:
194;43;73014444075; - seagate
194;64;193274642466; - samsung
```
According to `smartctl -A /dev/sdX` both affected disk have this temperatures:
```
194 Temperature_Celsius     0x0002   064   055   000    Old_age   Always       -       34 (Min/Max 17/45) - samsung
194 Temperature_Celsius     0x0022   043   066   000    Old_age   Always       -       43 (0 17 0 0 0) - seagate
```
I guess it would be nice to sanitize the data in python plugin, or create some rules that can support different reporting style. On the other hand disk temperatures are provided by `hddtemp` so it's not a critical issue.

All attributes are set to be reported RAW in netdata. I use latest build.

**Comment by ktsaou** [comment]
Hi,

@l2isbad any ideas?

**Comment by l2isbad** [comment]
To be honest no.
We can add something like
https://github.com/firehol/netdata/blob/master/python.d/sensors.chart.py#L52-L57
and skip raw values if they are not in limits.

**Comment by ktsaou** [comment]
sounds nice.
Please do...

**Comment by l2isbad** [comment]
> To be honest no.
> We can add something like
> https://github.com/firehol/netdata/blob/master/python.d/sensors.chart.py#L52-L57
> and skip raw values if they are not in limits.

@skibbipl  ^^ will be implemented. If you has any other ideas you are welome 😄

**Comment by skibbipl** [comment]
This will definitely solve the issue regarding big values. However all disks made by Seagate will probably report bad values and netdata will not be able to monitor that specific S.M.A.R.T. attribute.

I was thinking about adding logic behind collecting this attribute from csv. Something like this:
`if disk_name like "Seagate*" get 2nd value from the csv column.`
194;**_43_**;73014444075;
`if disk_name like "WD*" get 3rd value from the csv column.`
194;110;**_37_**;

But honestly I'm not sure if it's worth the hassle...

**Comment by l2isbad** [comment]
Well, according `man smartctl` there is always  one raw and one normalized (1-254) value per attribute.

43;73014444075; **43** raw or normalilized? `73014444075` is 100% raw, then 43 is normalized. But it looks like it's actual temperature, so it's raw too..

Since we have charts not per disk (the main reason is super long disk names) but per attribute we can't mix `raw` and `normalized` values in one chart (values ​​should be the same units).

> if disk_name like "Seagate*" get 2nd value from the csv column.

And i am not an HDD expert (lol), i am not sure this is true for all Seagate disks.

For now to skip such weired values looks the best idea.

**Comment by ilyam8** [comment]
@terba 

it won't work (120)


https://github.com/netdata/netdata/issues/3041#issuecomment-347566128
i see
> 194;110;37;


how about this ?

```python
return min(int(self.normalized_value), int(self.raw_value))
```

**Comment by terba** [comment]
It would work, as raw is compared to 120 not the normalized value. Anyway your `min` solution looks better.

**Comment by ilyam8** [comment]
@Ferroin what do you think?

**Comment by Ferroin** [comment]
I think the `min` approach will probably work reliably in a vast majority of cases, though it should probably be possible to force things to use raw or normalized.
