### ISSUE TITLE
Monitoring without charts (hidden charts)

### ISSUE THREAD

**Issue by dolphin82** [firehol/netdata#3043]
Hello!
I need to monitor some parameters without charts , becouse there are only status "ok" or "fail"(0 or 1). So if the status is "fail", i need to send the alert.   In the wiki it is written that there is an ability to hide the dimension by set the "hidden" flag in the DIMENSION. 
Tried set it. but unfortunately i can't do this and dimension is not hidden.
Tested this in the example plugin example.chart.py :
"CHARTS = {
    'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            **['random1','rand1','absolute','1','1','hidden']**
        ]
    }
}

"
But it doesn't work :

 ./python.d.plugin example
2017-11-20 15:17:16: python.d INFO: plugin: main: Using python 2
2017-11-20 15:17:16: python.d INFO: example: example: check() => [OK]
CHART netdata.runtime_example '' 'Execution time for example' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

CHART example.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'example'
**DIMENSION 'random1' 'rand1' absolute 1 1 ''**

Then i tried to set 'hidden' flag in the def get_data(in the example.chart.py)  :
self.dimension('random1','random1','absolute',1,1,'hidden')
This doesn't work too.

Is this bug, or i do somthing wrong?
Is there any way to monitoring something without charts or hide the chart?

Thank you very much in advance for your reply!

**Comment by l2isbad** [comment]
@dolphin82 Hi

> Is this bug, or i do somthing wrong?

Bug.

https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/charts.py#L8

Add `'hidden'` after `'divisor'`

> I need to monitor some parameters without charts

With hidden you can hide dimensions not charts.

**Comment by dolphin82** [comment]
@l2isbad Hi!

Thank you very much!

Now it works fine

**Comment by l2isbad** [comment]
@ktsaou 
mark it as a bug and reopen pls

**Comment by dolphin82** [comment]
@l2isbad Hi again!
One more question. If i add flag 'hidden' when the chart is initialaising all works fine.
But if i try to add new dimension with flag 'hidden' it's does not work.

**self.charts['random'].add_dimension(['temp','temp','1','1','hidden'])**
./python.d.plugin test

CHART test.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'test'
DIMENSION 'rand1' 'rand1' incremental 1 1 ''
DIMENSION 'temp' 'temp' absolute 1 1 ''

And can i monitor some parameters without charts, only for alerts, or maybe hide the chart?

Thank you.

**Comment by dolphin82** [comment]
@l2isbad 
Sorry, it's my mistake : **self.charts['random'].add_dimension(['temp','temp','absolute','1','1','hidden'])**
All works fine!

**Comment by ktsaou** [comment]
merged it
