### ISSUE TITLE
what I will do that I want to add more charts(for example apache)

### ISSUE THREAD

**Issue by ChenMiaohong** [firehol/netdata#3045]
hello:

> This is your example for mysql in debug mode.

> You can verify netdata plugins are able to collect metrics, following this procedure:

```sh
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql
```

I want to know the method what add plugin into netdata  permanent。I look forword to getting help.

**Comment by ktsaou** [comment]
Hi,

To add apache charts to netdata, you need to configure your apache to accept queries from netdata.

As you see at the apache plugin configuration for netdata, it queries a specific apache URL: https://github.com/firehol/netdata/blob/7a7324a81855fed0fdc43ca60bde6376179ce15b/conf.d/python.d/apache.conf#L79

Please check the apache manual to allow this. You need to enable `mod_status` at apache.

**Comment by ChenMiaohong** [comment]
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql
the above is the debug mode.
I want to know the method what add plugin into netdata permanent.
for example.https://github.com/coraxx/netdata_nv_plugin
1.I want to what I need to modify the conf file ?
2.the modify file is or not  locate at /etc/netdata/python.d/mysql.conf?

**Comment by ktsaou** [comment]
> I want to know the method what add plugin into netdata permanent.

It is permanent. If the plugin works in debug mode, restart netdata. It work.

You need to edit the config file `/etc/netdata/python.d/mysql.conf` only if you need to set a password or change the mysql port.

Generally, to collect mysql metrics, you need to configure your mysql server to allow netdata to connect.
The config file has instructions:

https://github.com/firehol/netdata/blob/fb05a25120ed5489a1f95ed4fa361d6990234f45/conf.d/python.d/mysql.conf#L78-L93

**Comment by ChenMiaohong** [comment]
I thank for your respone.but I finish the operation that create user 'netdata'@'localhost';I restart the mysql
and netdata,but thought the website http://localhost:19999 ,I can't find the chart about mysql.
the below is my configure about mysql /etc/netdata/python.d/mysql.conf.can you help me find out the mistake?thabks!
`# Additionally to the above, mysql also supports the following:
#
        socket: '/var/run/mysqld/mysql.sock'
#
#  or
        host: 'localhost' # the host to connect to
        port: 3306             # the port to connect to
#
#  in all cases, the following can also be set:
#
        user: 'netdata'       # the mysql username to use
        pass: ''       # the mysql password to use
#
`
my Email is cmhiot@126.com.can I have your Email?

**Comment by ktsaou** [comment]
So, when you run this:

```
```sh
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql
```

What output you have? Does it work?

my email is everywhere, including the footer of all netdata dashboards. But, please do not use it unless absolutely necessary. Your problem can be a problem others have too. Solving it in public will help many more and prevent new issues.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
