### ISSUE TITLE
Not sure if socket without a proper protocol is a good idea.

### ISSUE THREAD

**Issue by fredericopissarra** [firehol/netdata#305]
I believe some *nix platforms have a problem with unspecified protocols when calling socket(). On web_server.c there are calls such as:

`sock = socket(AF_INET, SOCK_STREAM,0);`

and

`sock = socket(AF_INET6, SOCK_STREAM,0);`

Maybe it is prudent to specify IPPROTO_TCP, instead of 0.

**Comment by ktsaou** [comment]
this has been fixed.
