### ISSUE TITLE
varnish.memory_usage chart makes no sense

### ISSUE THREAD

**Issue by codl** [firehol/netdata#3054]
![sscrot](https://user-images.githubusercontent.com/315139/33142041-64dcef1a-cfb5-11e7-9f88-8f3e9a06d0e6.png)

i do not understand how I should read this. are they stacked but one of them is negative?

**Comment by l2isbad** [comment]
yes, this should be fixed

**Comment by ktsaou** [comment]
merged it

**Comment by codl** [comment]
this still looks wrong to me in a brand new way

i have a 1 GiB storage backend. it seems 'free' is dropping twice as fast as it should

![out](https://user-images.githubusercontent.com/315139/33695949-3c3e2a78-db00-11e7-9264-7da0555b5c6b.gif)

**Comment by l2isbad** [comment]
Yes, looks wrong.

That is how it works

https://github.com/firehol/netdata/blob/master/python.d/varnish.chart.py#L216-L217

free is 
`s0.g_space` - `s0.g_bytes`

seems this is a wrong calculation

**Comment by l2isbad** [comment]
@codl any ideas how we should calc memory usage? 😄 (i am not a varnish user)

**Comment by codl** [comment]
i'm not familiar with varnish's stat stuff but looking at `varnishstat`'s output with, again, 1 GiB of storage:

```
$ varnishstat -1 | grep -E 's0.g_(bytes|space)'
SMF.s0.g_bytes                        703115264          .   Bytes outstanding
SMF.s0.g_space                        370626560          .   Bytes available
```

it seems that `g_space` is the amount of free storage, not the total storage. so this should be correct:

```patch
@@ -216,217 +216,217 @@
         data['memory_allocated'] = int(data['s0.g_bytes'])
-        data['memory_free'] = int(data['s0.g_space']) - data['memory_allocated']
+        data['memory_free'] = int(data['s0.g_space'])
```
