### ISSUE TITLE
Nginx two backends and a defualt on root location

### ISSUE THREAD

**Issue by mrunc** [firehol/netdata#3065]
Can some one please help me with this I have two servers / backends I want to have a default one to work at the root location on sub-domain while having both work as https://name.com/server1 & https://name.com/server2 and select between both from netdata menu at the left
it works OK with a server name as /server1 but I can't get the root sub-domain to redirect to my default backend/server I getting this error: 
"ERROR 405: Cannot download charts index from server: https://netdata.name.com/api/v1/charts"

Here is my configuration:

    
    upstream netdata-server1 {
        server 127.0.0.1:19999;
        keepalive 64;
    }
       upstream netdata-server2 {
        server 10.10.10.10:19999;
        keepalive 64;
    }
    server {
    
      listen 80;
      server_name netdata.name.com;
      return 301 https://$server_name$request_uri;
    }
    
    server {
  
     listen          443 ssl http2;
     server_name     netdata.name.com;
  
     ssl_certificate /etc/letsencrypt/live/netdata.name.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/netdata.name.com/privkey.pem;
     ssl_trusted_certificate /etc/letsencrypt/live/netdata.name.com/fullchain.pem;
     
     ssl_client_certificate /opt/name/certs/rootCA.crt;
     ssl_crl /opt/name/crl/ca.crl;
     ssl_verify_client on;
     
     include snippets/ssl-params.conf;
  
    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://server1;
        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
  
    location ~ /(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata-$behost/$ndpath$is_args$args;
        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
  
  
    location ~ /(?<behost>.*) {
        return 301 /$behost/;
    }
  
    }

**Comment by ktsaou** [comment]
I think the best way to configure both servers to run as `https://nginx.hostname/SERVERX/` and then redirects users accessing `https://nginx.hostname/` without a server, to `https://nginx.hostname/SERVER1/`.

**Comment by mrunc** [comment]
Thanks, that was easier than I thought

    
    upstream netdata-server1 {
        server 127.0.0.1:19999;
        keepalive 64;
    }
       upstream netdata-server2 {
        server 10.10.10.10:19999;
        keepalive 64;
    }
    server {
    
      listen 80;
      server_name netdata.name.com;
      return 301 https://$server_name$request_uri;
    }
    
    server {
  
     listen          443 ssl http2;
     server_name     netdata.name.com;
  
     ssl_certificate /etc/letsencrypt/live/netdata.name.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/netdata.name.com/privkey.pem;
     ssl_trusted_certificate /etc/letsencrypt/live/netdata.name.com/fullchain.pem;
     
     ssl_client_certificate /opt/name/certs/rootCA.crt;
     ssl_crl /opt/name/crl/ca.crl;
     ssl_verify_client on;
     
     include snippets/ssl-params.conf;
  
    location ~ /(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata-$behost/$ndpath$is_args$args;
        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
  
  
    location / {
        return 301 /SERVER1/;
    }
  
    }

**Comment by mrunc** [comment]
Sorry another question; what about the registry now? for SERVER1 to be the registry
Is this a correct configuration for registry

SERVER1 config:

        [registry]
        enabled = yes
        registry to announce = https://netdata.name.com/SERVER1
        #registry hostname = SERVER1
        # allow from = * 

SERVER2 config

        [registry]
        enabled = no
        registry to announce = https://netdata.name.com/SERVER1
        #registry hostname = SERVER2
        # allow from = *

Is there any other values I need to uncomment ? should I use Internal addresses ?
and the fact that I'm using client certificates verification will it affect how registry works? 

perhaps I should use private internal addresses to bypass certificates verification and then use "registry domain =" value for public links in alerts ?? am I getting this right?

**Comment by ktsaou** [comment]
It seems right.
The web browsers talk to the registry, so you should not bypass your security.

**Comment by mrunc** [comment]
Thanks, every thing works like a charm now
