### ISSUE TITLE
what we will do when I add more chart

### ISSUE THREAD

**Issue by ChenMiaohong** [firehol/netdata#3068]
Netdatat provide many available external plugins for user.but the method of every plugins configure is different.when face to a new plugins ,what we will do is very important.
so I look forword to getting  the process to configure external plugins.
for mysql.for sensor.for ngix.I look forword to get your respone.

**Comment by ktsaou** [comment]
I am not sure I understand the question.

Each plugin has its own configuration file. The default configuration file shipped with netdata should be generally good for most major distros. If  the defaults supplied by netdata are not good for your distro, please report an issue and we will fix it.

netdata supports auto-detection when possible, so you normally don't have to change anything at netdata. Instead you need to configure your applications to allow netdata connect to them. For example, you need to:

1. configure `mysql` to allow the local user `netdata` to connect. netdata does not any special privileges. If you allow this without password, you will not have to edit the plugin config.

2. to collect sensor info, you need to install and configure lm-sensors.

3. to collect information from nginx, you need to enable the `status` module of nginx. Once you enable this, restart netdata and it will find out.

So, generally you should edit netdata configs in rare cases.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
