### ISSUE TITLE
Combined graphs

### ISSUE THREAD

**Issue by pricklydevil** [firehol/netdata#3070]
Heya,

So have been playing around with Netdata and I absolutely love it! One thing I wanted to do though was do an overall single dashboard, with graphs that combine input from multiple systems .. so for example, CPU of all systems being monitored onto a single chart and then have other charts such as disk space, NIC throughput, RAM usage, process count etc without having to have multiple different dashboards.

Looking at the documentation, there doesn't seem to be an example of such a thing .. I know it can be done in Grafana as I've worked in companies that have used it for monitoring but struggling to figure it out with Netdata.

I'm looking to create it for a whole environment using the tv.html as an output that will be keyboard/mouseless.

Any chance somebody can guide me in the right direction?

**Comment by ktsaou** [comment]
Check custom dashboards. On your netdata go to `http://your.netdata.ip/tv.html` for an example of a 2-server dashboard.

Generally, you place a few `div` blocks in an html page, and netdata turns all the `div` into charts. It is relatively simple. No javascript necessary.

This is, for example, what I have at home:

![screenshot from 2017-11-28 01-52-05](https://user-images.githubusercontent.com/2662304/33295568-ce1a0062-d3de-11e7-9df6-3214d78acc7a.png)

With some basic bootstrap knowledge, you can add tabs and other fancy elements.

**Comment by pricklydevil** [comment]
Heya, thanks for coming back to me :)

That's an example of multiple systems but individual graphs, whereas I'm looking to create a single graph that displays multiple systems.

Something like this but taking data from multiple systems:

![stacked_graph](https://user-images.githubusercontent.com/13431730/33343093-0f95dc12-d47c-11e7-8fd7-5efc01af8cb9.png)

It may not be possible inside Netdata so may have to go down as a feature request, but it's definitely something that makes monitoring dashboards look better IMHO :)

Cheers

**Comment by ktsaou** [comment]
I am sorry, netdata does not support this currently.

There are enhancement requests #2650,  #2359 and #359 that are close/same to what you need.
So, I am marking this as duplicate.

**Comment by pricklydevil** [comment]
No problems, I really do appreciate you coming back to me :) I'll still be using Netdata and hopefully those enhancements make it into mainstream.

Keep up the amazing work though :)
