### ISSUE TITLE
Gaps in data collection - lots of alerts triggered

### ISSUE THREAD

**Issue by skibbipl** [firehol/netdata#3075]
Hello,
I use nedtada to monitor a debian server with very limited resources (2 CPU Cores / 4GB RAM) but with a few services running. Netdata is having problems collecting data constantly and I'm observing gaps on the charts:
![obraz](https://user-images.githubusercontent.com/4746858/33340016-24c0de30-d47b-11e7-8e29-16fa8d04c8ad.png)
Of course I don't mind having small gaps in data collection, however this leads to massive alerting regarding missing data:
```
postgres last collected secs = 00:00:06 ago
number of seconds since the last successful data collection
```
Is it possible to fine tune netdata alert rules somehow so they will not spam with useless mails that postgresql data was not collected for only 10 seconds? Is it possible to make a rule that will trigger the alert if database is not reporting data for 30 seconds or even more? I tried to read wiki on alerts, but honestly I still don't understand how they work. Some pictures with timeline when alerts are triggered would definitely help.
On the other hand are there any ways to make netdata more reliable with data collection? I tried setting different netdata process priorities but I still was spammed with missing data alerts.

**Comment by ktsaou** [comment]
Could you please export a snapshot of the dashboard, showing 3-4 gaps with per-second resolution?
I think we should fix the root cause.

**Comment by skibbipl** [comment]
I'm using unfortunately debian packaged stable nedtata 1.8 which doesn't have snapshots feature. Anu other ways to help you debug the issue? Or I should upgrade netdata first?

**Comment by ktsaou** [comment]
There is a work-around:

Go to `http://london.my-netdata.io/#;server=http://your.netdata.ip:19999/`

You will get a new netdata dashboard, on your netdata.
Then take a snapshot.

**Comment by ktsaou** [comment]
btw, this is a web browser feature. Your netdata will not be exposed.

**Comment by skibbipl** [comment]
I've send you e-mail with link to the snaphot as I cannot paste it here.

**Comment by ktsaou** [comment]
I received it.

At the snapshot, I see that netdata plugins loose 1 sec every minute. 

However, there are a few plugins that sometimes report their time to run, and this exceed 1000 ms.

So, I understand that something intensive runs on this server once every minute and since netdata runs with the idle scheduling priority, it stops to allow the other process run.

I suggest to follow one of the 2 examples shown on this wiki page: https://github.com/firehol/netdata/wiki/netdata-process-priority (just added them), to increase the scheduling priority of netdata a bit.

I hope that the issue will now be gone, and you will be able to see which process is taking that much CPU once every minute.

**Comment by ktsaou** [comment]
I think you are running a cron job of some sort every minute.

This chart:

![image](https://user-images.githubusercontent.com/2662304/33345375-da7c00b0-d494-11e7-8e4f-9c24c92e1b51.png)

shows that your little server is executing 30.000 page faults (30.000 x 4k = about 120MB) in a second and this continues for 2-3 seconds.

Your spawning a few processes at the same time:

![image](https://user-images.githubusercontent.com/2662304/33345535-5b274a6c-d495-11e7-9c07-5b5c56905409.png)

Which increases context switches quite high:

![image](https://user-images.githubusercontent.com/2662304/33345557-78f341ae-d495-11e7-93c1-554a05275662.png)

At the same time, this single CPU VM is getting network spikes:

![image](https://user-images.githubusercontent.com/2662304/33345667-cca5ff12-d495-11e7-93ab-484e9388c301.png)

and disk spikes:

![image](https://user-images.githubusercontent.com/2662304/33345694-e336be74-d495-11e7-946b-a45095be3e9f.png)

So, I guess it is just too much work for a single core server. Keep in mind that if this is a production system, you are offering a bad service for 1-2 seconds every minute.

**Comment by skibbipl** [comment]
Yeah, this is an overloaded server, but for now I can't upgrade it with more resources or split into multiple servers. But the `nice` setting in systemd resolved the data collecting gaps (by using more precious server resources of course).
