### ISSUE TITLE
Custom python.d plugin: How to set the type value?

### ISSUE THREAD

**Issue by mmikitka** [firehol/netdata#3076]
I created a custom plugin in /usr/libexec/netdata/python.d and I want to know how to modify the following /api/v1/charts values associated with my plugin (see everything marked with "CHANGE"):

```
    "CHANGE.heartbeatdb":    {
      "id": "CHANGE.heartbeatdb",
      "name": "CHANGE.heartbeatdb",
      "type": "CHANGE",
....
    },
```

**Comment by ktsaou** [comment]
Hi,

I think this `CHANGE` is the module name.
@l2isbad can this be changed, or the only way is to rename the module?

**Comment by l2isbad** [comment]
Yes, it can be changed.

@mmikitka 
To replace module name with the custom one please change
```python
self.module_name
```
in ```__init__``` or ```check```

**Comment by mmikitka** [comment]
Thank you for the quick response.

The check() method in python.d/example.chart.py is static so it does not have access to the object instance: 'self'. I made the change in the __init__ method, but I only see a partial change. After tracing  through more Python code, I see undesirable values coming through the configuration parameter passed to my Service object:

My module's constructor, Service::__init__ receives the following configuration values, as seen before calling the parent constructor, SimpleService::__init__:
```
configuration = OrderedDict([('user', 'root'), ('pass', 'password'), ('retries', 60), ('autodetection_retry', 0), ('update_every', 1), ('priority', 90000), ('chart_cleanup', 10), ('job_name', 'heartbeat_db'), ('override_name', 'heartbeat_DB')])
```
I do not know where the 'job_name' and 'override_name' values are coming from - these values were used in a previous iteration of the code which I since removed, so I'm inclined to believe that these are cached values. I run 'rm -rf /var/cache/netdata/*' between restarts - is there another cache?

Here are the contents of my module, which is located in /usr/libexec/netdata/python.d/foo.chart.py:

```
from bases.FrameworkServices.SimpleService import SimpleService

# default module values
#update_every = 4
priority = 90000
retries = 60

ORDER = ['heartbeatdb', 'another']
CHARTS = {
    'heartbeatdb': {
        'options': [None, 'Services', 'services', 'Services', 'foo.heartbeatdb', 'line'],
        'lines': [
            ['total services', 'total', 'incremental'],
            ['active services', 'active', 'incremental']
        ]
    },  
    'another': {
        'options': [None, 'Another', 'another', 'Another', 'foo.another', 'line'],
        'lines': [
            ['A', 'A', 'incremental'],
            ['B', 'B', 'incremental']
        ]
    }
}

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.module_name = 'foo'  

    @staticmethod
    def check():
        return True

    def get_data(self):
        data = dict()

        data['total services'] = 100
        data['active services'] = 50

        data['A'] = 1
        data['B'] = 2

        return data
```

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L75-L82

`CHANGE` is `actual_name`.

Every job has:
1. `module_name` - **module_name**.chart.py
2. `job_name` - if module is not multijob then ` job_name` = `module_name`

Multijob config file example:

```yaml
heartbeat_db:
    name: 'heartbeat_DB'
    user: 'user'
    pass: 'password'
```

`heartbeat_db` is `job_name`

3. `override_name` is `name` from configuration file (or '' if not exist).

`heartbeat_DB` is `override_name`


```python
    @property
    def name(self):
        if self.job_name:
            return '_'.join([self.module_name, self.override_name or self.job_name])
        return self.module_name
```

Examples:

**Multijob with override_name**

```yaml
heartbeat_db:
    name: 'heartbeat_DB'
    user: 'user'
    pass: 'password'
```

`CHANGE` = module_name_heartbeat_DB

**Multijob without override_name**

```yaml
heartbeat_db:
    user: 'user'
    pass: 'password'
```

`CHANGE` = module_name_heartbeat_db

**1 job**

```yaml
    user: 'user'
    pass: 'password'
```

`CHANGE `= module_name

Actually `CHANGE ` is:

```python
    def actual_name(self):
        return self.fake_name or self.name
```

To replace `module_name + override_name/job_name` you can use:

[self.fake_name](https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L62)

```yaml
heartbeat_db:
    name: 'heartbeat_DB'
    user: 'user'
    pass: 'password'
```

```python
class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.fake_name = 'foo'
```

`CHANGE `= `foo`

But keep in mind `fake_name` only works with multijob configuration but the number of jobs should not be more than one.

**Comment by mmikitka** [comment]
Well done - you filled in my knowledge gap! Closing this issue.
