### ISSUE TITLE
Disk addressing by WWN/other id?

### ISSUE THREAD

**Issue by amichelic** [firehol/netdata#3081]
We have some disks in a machine where we want to disable backlog alerting (or monitoring). Those disks are idle most of the time, but every now and then they get hit with a huge amount of data. So then the disk will have a high backlog and netdata will send an alert.

Disabling backlog monitoring is no problem for the logical volumes on those disks - there is a section `[plugin:proc:/proc/diskstats:vgnn-mmmmm]` in **netdata.conf**, and I can set `backlog = no`.

The actual block device however is a problem. There's a section e.g. `[plugin:proc:/proc/diskstats:sdj]` where I can set `backlog = no` - but on the next restart it's very likely that we find this disk on a different block device id (and then the wrong disk has backlog monitoring disabled).

Is there any possibility to address the disks via WWN or model/serial number? `/dev/disk/by-id/wwn-0x500xxxxxxxxxxxxx` (being a symlink e.g. to `/dev/sdj`) would uniquely identify the disk in question.

**Comment by ktsaou** [comment]
Hi,

I suggest not to set `backlog = no` in netdata.conf. This disables the chart too, so you will not be able to see disk backlog either.

The right way to disable a disk alarm but keep the chart, is to edit [/etc/netdata/health.d/disks.conf](https://github.com/firehol/netdata/blob/a1cf62fee9a591d9649ebb19716c8811768d47fb/conf.d/health.d/disks.conf#L116) and set:

```
template: 10min_disk_backlog
...
families: disk1 disk2 disk3
...
```

`families` are the submenus of the netdata main menu:

![image](https://user-images.githubusercontent.com/2662304/33449246-e393714c-d610-11e7-8f97-47e9231a06d4.png)

---

naming the disks is nice, and I think actually it is pretty simple to do.
Let me give it a try...

**Comment by ktsaou** [comment]
done. Check #3084 .

Note that I have chosen not to name disks by-id by default. You have to enable it in netdata.conf.

The reason is that this also changes the submenu of the dashboard menu and the chart name. I think that `sda1` is better than `nvme-eui.0025385171502b1c`.

So, only in cases like yours, you can enable this, and configure the alarms using the disk ids.

**Comment by ktsaou** [comment]
merged it.
Just update your netdata...

**Comment by amichelic** [comment]
Thank you, this is great! I've now excluded all the irrelevant disks via `families: !wwn-1 !wwn-2 *` and now the alerts are much more useful.
