### ISSUE TITLE
Python pluging: "* was suppressed due to non updating"

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3085]
If some charts, created from custom python plugins, fails to update (for example some database replication dropped, but we are gather data about this replication), they will be stopped and than dispensary from Netdata`s dashboard.
Is there an easy way to recreate those charts, what they will some data (restore of db replication)?

**Comment by l2isbad** [comment]
You can disable suppressing

https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L213-L216

[any module configuration file](https://github.com/firehol/netdata/blob/master/conf.d/python.d/beanstalk.conf#L42-L50)

**Comment by shellshock1953** [comment]
That`s way easy, thank you!
