### ISSUE TITLE
Apps plugin: Possibility of gathering per-PID stats?

### ISSUE THREAD

**Issue by mmikitka** [firehol/netdata#3088]
Can you please provide direction on gathering per-PID stats? I have a use-case that requires analysis of system resources used by individual processes (by PID), not the aggregate.

**Comment by ktsaou** [comment]
a few specific PIDs or all PIDs?

If you need this for a few specific PIDs, then edit `/etc/netdata/apps_groups.conf` and at the top (the order is important), add groups for each of the processes you need.

Unfortunately, netdata cannot monitor all PIDs individually (i.e. like `top` does).

**Comment by mmikitka** [comment]
Thank you for the response. I am familiar with apps_groups.conf, which
provide aggregate stats across processes of the same type, but I want to
track stats of individual PIDs. As far as I know, entering the PID integer
values into apps_groups.conf will not provide what I'm looking for, unless
I'm wrong.

I'd like to modify the process stats code to optionally collect stats at a
per-PID level - can you provide some high-level guidance on how to make
this happen from a code architecture perspective?

**Comment by ktsaou** [comment]
Why you want to configure pids?
I mean, you can configure process names / patterns to assign a single pid.

Anyway, it is relatively easy to modify apps.plugin:

1. [This function](https://github.com/ktsaou/netdata/blob/527c1afc2bd8f558492572d5d3f63696390e02e1/src/apps_plugin.c#L493) is called to create a linked list of aggregation targets.
2. [This function](https://github.com/ktsaou/netdata/blob/527c1afc2bd8f558492572d5d3f63696390e02e1/src/apps_plugin.c#L752) is called to assign pids to targets.

The line:

```
name: process1 process2 process3
```

creates 3 targets, each of them having its own pids. The later 2 targets are aggregated to the first, which is submitted to netdata.

So, to support pids, you could modify the first function to support:

```
name: @pid1 @pid2 @pid3
```

and at the second function assign the pid to its target.

But, this will useless/wrong after a reboot or if you restart the processes.

Are you sure you want it like that?

**Comment by mmikitka** [comment]
Thank you @ktsaou. I am monitoring a server with multiple applications of the same type which start at random, and I want to understand the use of system resources over the lifetime of a process, not the lifetime of netdata. By aggregating data from all processes of a given type, I will not be able to obtain the per-PID lifetime observations that I'm seeking.

**Comment by Ferroin** [comment]
Is there any way to have the applications specify some unique string in their command-line or process name (kind of like the `-name` option for QEMU, which sets the thread name for all spawned threads, and updates `/proc/$PID/comm` to contain the same name)?

If so, you could set up whatever starts the instances to generate a unique ID of some sort (possibly even just a UUID), and then have netdata match on those.

Alternatively, find a way to get each instance in it's own cgroup, and then just look at the cgroups for per-process stats, while using the apps plugin for the aggregates.

**Comment by ktsaou** [comment]
btw, netdata also supports monitoring systemd. So, if each process is started with systemd, netdata will provide a dimension per systemd service.

Cleaning up. I am closing this, but if you need help, just post.
