### ISSUE TITLE
Does the dashboard support table？

### ISSUE THREAD

**Issue by kramerli** [firehol/netdata#3091]
I just installed the netdata and go through the default  dashboard page. It seems that most charts are lines with time series data.

I want to add some table on the dashboard. Is it possible? How to do it?

**Comment by talkyy** [comment]
You can make your custom dashboard. Let have a look at: https://github.com/firehol/netdata/wiki/Custom-Dashboards
I also think it is necessary to have some table on dashboard, but it depends on what is your need.

**Comment by ktsaou** [comment]
table? you mean you want to see the values formatted in a table?

**Comment by talkyy** [comment]
I think table is suitable for the monitoring statuses of devices. Like this:
![image](https://user-images.githubusercontent.com/26269505/33525561-a06e11a0-d864-11e7-8fb7-d8a390802f21.png)
Of course charts the best way for monitor in real-time, but sometime tables are better.

**Comment by ktsaou** [comment]
Unfortunately no. netdata is about performance monitoring, so it monitors only metrics.
You probably need an NMS.

**Comment by kramerli** [comment]
@ktsaou Yes， I was expecting value formatted in tables like @talkyy demonstrated.  Tables seems more clear in some situation.

**Comment by magao** [comment]
You can of course use the [API](https://github.com/firehol/netdata/wiki/REST-API-v1) to retrieve the data from NetData, and construct the table using javascript.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
