### ISSUE TITLE
Health check with pattern for all dimensions on the chart

### ISSUE THREAD

**Issue by dolphin82** [firehol/netdata#3097]
Hello!
I have the hidden chart with many dimensions(about 70). It works fine as a trigger : if everything is fine the value of dimensions is 0, and if there is a problem the value is 1.
But i need health monitoring for all this dimensions(dim1,dim2,dim3...dim70). Can i do thomething like this ? : 

`template: testtemplate`
      `on: testchart`
    `calc: $dim*`   - the pattern of all dimensions
   `every: 10s`
    `crit: $this > 0`
   `delay: down 1m multiplier 1 max 1m`
    `info: There is a problem with dim-n(name of the dimension)`
      `to: sysadmin`

Or maybe there is a better way for monitor many parameters , for example add the chart if this possible or dimension only when the plugin returns some value, for example 1?
Thank you.

**Comment by ktsaou** [comment]
You can add a `lookup` line, like this:

```
lookup: average -1s
crit: $this > 0
```

This will set to variable `$this` the average of the last 1 second (i.e. the value of the last 1 second), of the sum of all dimensions.

So, if any dimension is non-zero, the alarm will be triggered.

You can also select dimensions like this:

```
lookup: average -1s of dim1,dim2,dim3
crit: $this > 0
```

The above, will set `$this = dim1 + dim2 + dim3`

or just this:

```
calc: $dim1 + $dim2 + $dim3
crit: $this > 0
```

---

I have at my todo list to provide also templates per dimension. So for each dimension of a chart, add an alarm to do something. But this is future...

**Comment by dolphin82** [comment]
Ok, thank you

**Comment by Richie81** [comment]
I know it's a necro(kind of), but do we have an ETA on this feature?

Thanks,
Richie

**Comment by ktsaou** [comment]
hm... this issue is closed. Please open a new one for the feature you miss.
