### ISSUE TITLE
Registry of netdata installations

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#310]
When you have multiple netdata servers, there should be something like a "registry": i.e. how many servers do I have?, which are their URLs?, etc.

This would also be used for monitoring all of them from a single dashboard, so instead of saving them to browser local storage, a central place could have a list of them.

The dashboard on each netdata server (i.e. your web browser) could then contact the registry to get the list of netdata installations you have, and allow you to mix and match charts on the same dashboard from multiple netdata servers.

**Comment by simonnagl** [comment]
Just an idea how registration might work quite simple.

In each server configuration we can specify a number of other servers.

1. If a server get's started it adds itself and all configurated servers to the list of known servers.
2. If a server get's added to the list of servers it sends it's whole list of known servers to each server in the list.
3. If a server recieves a list of servers it compares the list with it's own list and and adds new servers to his list.

With this algorithm every server should know every other server in a graph after a view calls. I know this algorithm can be improved at some points and we should discuss about how to handle servers wich are not running.

Every server can now embed the graphs of other servers in it's status page. A dropdown servers in the title-bar to switch to other servers directly and with drag and drop to compare like at the example page.

**Comment by ktsaou** [comment]
Well, the problem is that the netdata servers are not aware of their URL.

I am thinking something a lot simpler:

## How the registry works

1. Each netdata generates a random GUID which acts its unique MACHINEID. It does this once and it saves it on disk. We need this to figure if the same server is accessed with different URLs.

2. Every time **you** (your web browser) fetches a netdata dashboard, your browser consults the registry, for 2 reasons:

  1. to let it know you are accessing a specific MACHINEID with a specific URL.
  2. to fetch the list of all the other netdata dashboards you have accessed in the past.

So, to let the registry know all your servers, you will have to just view each netdata once!

### How my browser is identified?

Your browser gets a random GUID the first time it contacts the registry. This acts as a PERSONID. This is **you**. Every time the browser talks to the registry it gives this id back to the registry.

- Where is this PERSONID saved?

  a cookie (cookies are synced among your PCs, so cookies are good).

- What happens if I lose this PERSONID?

  nothing, just access all your netdata dashboards once again.
  If you need a backup, the netdata dashboards could have a special menu item to give you the list.

- Can I share this PERSONID?

  no, share the URLs of your netdata dashboards and the others will get their own PERSONID.

## What data are stored in the registry?

1. Person ID (a random GUID the registry generated the first time you contacted the registry)
2. Machine ID (a random GUID your netdata generated the first time it run)
3. URL (the browser URL when you viewed each netdata)

### Where is the registry?

This is the nice thing. Any netdata server may be able to act as a registry. Pick one.

The netdata demo servers could also act as a global registry for everyone, even the ones that do not own a netdata server.

### Where is the registry configured?

At `netdata.conf`. So just point all your netdata servers to the same registry. This means that you could have many separate lists of netdata servers. Just use a different netdata server as the registry for each different group of servers.

### What happens if the data of a registry are lost (corrupted disk, etc)?

Well, we could at some point have a simple replication between 2 or more netdata registries, but I think this might be overkill.

---

How does that sound?

**Comment by FallingSnow** [comment]
I like @simonnagl's idea. It was the same thing I came up with while reading the issue. It's kind of like an [ARP table](https://en.m.wikipedia.org/wiki/Address_Resolution_Protocol#Example).

To solve the server not knowing it's own URL you could just have the dashboard send its window.location. Then each server would store itself (identifier+location) and all the other servers it knows about.

In order to find out about other servers you could either implement some kind of discovery protocol or have clients additionally work as ARP links, without the storing itself part.

This has the advantage of being distributed, zero user interaction, and redundant.

**Comment by ktsaou** [comment]
ok, a few questions:

1. Server A

 - for you is "http://db1:19999/",
 - for me is "http://FallingSnowNetdata/public/netdata/myserver/"
 - for @simonnagl is http://my.fallingsnowvpn/private/netdata/database/"

2. I have installed 10 servers, but the firewall allows the marketing department to view only 2 (1, 2), the devops of application A to view 5 (1,2,3,4,5), the devops of application B to view 4 (4,5,6,7) and you to view all 10 (1-10).

3. I have installed 100 servers, but each customer views its own, while your team views all.

4. I have installed 10 servers but they are in different DMZs that cannot talk to each other. You can access them all, but they cannot talk to each other.

I could think a few more cases.
How do you solve these?

To my understanding, the registry is there to help the browser, so there is only meaning to talk with the browser.

**Comment by FallingSnow** [comment]
1. I don't know if you're familiar with Plex but they have a system where servers have multiple addresses. They use a kind of lazy load. For example, if there are 3 different addresses and I can only access the server from last one, then the dashboard would first try "http://db1:19999/" (local networks) which would result in "connection refused". It would then proceed till it reaches the 3rd (most remote) and gets a success.

2. As long as we are only talking about firewalls and not group authentication then I think the system would manage itself. Every time the marketing department views the dashboard it would try all 10 servers list of addresses. Only 2 of which would succeed. If you decided to open the firewall to allow the MD to view server 3, all the MD would need to do is reload the page.

3. This is where an ARP table might not work so well... If every server has a list 100 servers then they would all try to access 100 servers when the dashboard loads, all would fail except when your team accesses it. (This is starting to leave the realm of firewalls and entering authentication in my opinion) But I can think of at least 3 solutions, others would require a type of authentication.

    - A list of all possible servers is shown, connection attempts are only made when a server is actually selected.
    - Dashboards distributed by your customers' servers are set to not attempt to contact other servers.
    - Rules defining which address ranges can/shouldn't be stored in netdata "ARP tables".

4. That's OK. They don't need to ever talk to each other. They can solely communicate through you if clients are setup to be ARP links. *I mean to set it up so they did you would need to create a discovery protocol anyway*

### Advantages

- To see accessible servers users would not need to first access them.
- No setup.
- No need for PERSONIDs.

### Disadvantages

- Server addresses may become unmanageable over time.
    - **Solution:** Setting expire times for ARP entries can solve this like it does in a real ARP table.
- ~~Deleting a server from an ARP table would be next to impossible. **This is a significant draw back**~~ Instead just have the server attempt to contact a server before adding it to the ARP table, if it succeeds, add it. Therefore each server only contains healthy links.
- No deleting servers from lists.
    - **Solution:** *This works on the presumption that users are ARP links too.* The dashboard may have a module to delete servers from the user's local storage ARP table, and adding it to an exclusion list in the user's local storage. That prevents the user from picking it up again.

IDK if this got out of hand, but I enjoyed myself lol.

**Comment by ktsaou** [comment]
I think you have not understood why we need the registry. So let me explain.

I have 2 functions in mind:

## my netdata

This would be a drop down list of all the netdata servers you know. You can use it to jump from server to server easily.

Why do we need it?

I take as an example myself. I have about 100 servers. All running netdata. A few are accessed directly, others are in a DMZ and there is a central nginx in proxy mode, etc. I have a bookmarks folder called netdata, but sometimes I forget to bookmark a server, in other cases we changed something in the paths for accessing them, my team sends the new URLs, but I forget to change the bookmarks, etc. At the end, less than half are in my bookmarks folder and several bookmarks do not work anymore. Chaos.

If you have 100 servers, depending on who you are, the servers you work are different. If you are a DBA you care mainly about the DBs, if you are network guy you care about SNMP data or possibly a the linux firewalls / routers, etc.

What I am trying to do here is help all the users. So instead of bookmarking the netdata servers at their browsers, or presenting a very long list with all servers to all viewers, the registry could assist them by **transparently** tracking the netdata URLs and the frequency each netdata is used by each user, so a nice **personalized** drop down list can be presented with the netdata servers each viewer cares about.

## dynamic dashboards

Today the dashboard is fixed. It gets a list of charts and dimensions from a netdata server, it renders a page and this is it.

I think it would be nice to have a search box, where you can search for hosts, charts, dimensions and units.

So, in our 100 servers example, if you need to find the queries/s of a mysql, you could write `mysql` or `queries/s` or `db1` to get again **personalized** results. If out of the 100 servers, 10 are mysql servers, but you use only a specific one, I don't see why you should get results from the others. It will only confuse you.

So, the registry should solve a user problem. A **personalized** user problem.


Is it clearer now?

**Comment by simonnagl** [comment]
I like the idea of having the registry. I did not think about more complex setup with, let's say your 100 servers, and some people not interrested or unable to query all of them.

**There are some things I do not understand. Maby I need to learn...**

> cookies are synced among your PCs, so cookies are good

How does this work? I do not think I have the same cookie on every PC.

> This means that you could have many separate lists of netdata servers

How does that work exactly? Let's give me a try why I think this might not work.

1. I query `S1`. `S1` configured `S2` as registry. It is empty for my UID `UID1`. This will create a new registry at `S2`.
1. I query `S3`. `S3` configured `S4` as registry. It is empty for my UID `UID1`. This will create a new registry at `S4`.

That would break the user centerd design. If I query a new server which I do not manage I cannot know which of my realy known servers can be queried from that site.

Why don't we store the registy server as a cookie to. This would limit the number of lists we can have but I think this is fine.

**There are some improvements I would like to suggest.**

> If you need a backup, the netdata dashboards could have a special menu item to give you the list

It would be nice to have also an option to restore a list. It just needs to query each URL line by line.

@FallingSnow, could you please think about Advantages and Disadvantages of @ktsaou's approach too. Why can't you live with it? Where do you see problems for your use?

**Comment by ktsaou** [comment]
> cookies are synced among your PCs, so cookies are good
> How does this work? I do not think I have the same cookie on every PC.

All the browsers have some kind of login. Just login on them and all your bookmarks, cookies and possibly saved passwords are synced everywhere you login (even your mobile phone). There are also browser plugins that offer the same functionality, even cross browser (i.e. sync chrome and firefox).

> This means that you could have many separate lists of netdata servers
> How does that work exactly? Let's give me a try why I think this might not work.
> 
> I query S1. S1 configured S2 as registry. It is empty for my UID UID1. This will create a new registry at S2.
> I query S3. S3 configured S4 as registry. It is empty for my UID UID1. This will create a new registry at S4.

I consider this a feature, not an issue. Let's see why:

- At your work you have registry S1. When you view a netdata server of your work, you will have all your company's netdata servers at the drop down list.
- At your home you have registry S2. When you view a netdata server of your home, you will have all your home's netdata servers at the drop down list.

If at your work you have 2 registries, then either you have misconfigured it, or you really need that isolation.

The default registry could be `https://netdata-registry.firehol.org`, so most people that will not re-configure the registry of their servers, will never face this issue. If however, you want your netdata servers to never appear at a foreign registry, just set your own registry at them.

> That would break the user centerd design. If I query a new server which I do not manage I cannot know which of my realy known servers can be queried from that site.

The registries provide a <b>context</b> which is controlled by the owners of the netdata servers. Let's think of it at scale: every linux on the world has netdata installed, netdata dashboards are all over the internet and real-time charts of netdata appear at the home page of sites, at blogs, etc. A user is surfing on the net, and suddenly his company drop down list gets filled with hundreds of netdata servers he does not care about. So, the registry (the <b>context</b>) is a form of grouping and isolating them.

> Why don't we store the registy server as a cookie to. This would limit the number of lists we can have but I think this is fine.

The cookie is domain specific (the domain you visit, ie the netdata server). So, you will have to set the registry by hand on all netdata servers you visit.

> It would be nice to have also an option to restore a list. It just needs to query each URL line by line.

At some point in future, registries could allow you to login too to restore your list. But yes, you could also paste a bunch of URLs to be added to the registry (it will verify them of course).

**Comment by FallingSnow** [comment]
I'm still confused on what a registry is. From what I've been able to gather and what @ktsaou has clarified, it seems like a list of bookmarks that have been auto bookmarked. Every time you visit a server it is added to the bookmark list. Then, when you pull up the list you have all your servers. Am I understanding this correctly?

**Comment by ktsaou** [comment]
yes, exactly.

It also has a counter of your visits to each netdata, it can detect changing urls of netdata servers, and will be used when searching things. Multiple registries can help you isolate servers that should not be related in any way.

We can also think of additional features:

1. Each user could name the servers (the names could be personal or public)
2. Each user could add tags to the servers (the tags could be personal or public)
etc.

**Comment by FallingSnow** [comment]
I suppose the only difference between @ktsaou and my thinking is the implementation of a central server. If an auto bookmark list is all that is required, it could easily be accomplished via [synced storage](https://developer.chrome.com/extensions/storage). This would require no central server, no initial user configuration, and could easily implement features 1 & 2 @ktsaou lists above.

I feel adding a central server will introduce an external call (by default settings) that isn't necessary and reduce reliability of the service as a whole: what if this central server goes down?

I don't know how my method would impact searching though. I'd need to know a little more about how the search happens.

**Comment by ktsaou** [comment]
unfortunately synced storage is chrome only. The traditional localStorage is never synced, by design.

> I feel adding a central server will introduce an external call (by default settings) that isn't necessary and reduce reliability of the service as a whole: what if this central server goes down?

The call to the registry will happen from the browser in a non-blocking fashion. If the registry is down you will not get the list, but it will not affect anything else. The dashboard will work without delay, no visible errors will be there. To cover the scenario the registry is down, the dashboard could also save the last list taken from the registry to browser localStorage. So, even if the registry is down, you will get the last known backup of it.

> I don't know how my method would impact searching though. I'd need to know a little more about how the search happens.

Searching is about:

1. netdata servers, which will be done by the browser on the list from the registry
2. charts, dimensions, units, etc, which is between the browser and each netdata server

**Comment by FallingSnow** [comment]
Well isn't the PERSONID only stored as a cookie anyway? Moving to another computer wouldn't save your list. There is no way *(that I can think of)*, aside from chrome's storage.sync, to save a person's list when moving to a new computer without authentication.

For search, does the registry maintain a cache of all searchable terms, such as which servers have a MySQL component or does it query every server when the search is made?

**Comment by ktsaou** [comment]
> Well isn't the PERSONID only stored as a cookie anyway? Moving to another computer wouldn't save your list.

The PERSONID is stored in a cookie when your browser communicates with the registry. Is registry specific. Different registries, different PERSONIDs.

> There is no way (that I can think of), aside from chrome's storage.sync, to save a person's list when moving to a new computer without authentication.

If you login at your browser and you sync bookmarks, cookies, etc the PERSONID will be transferred too.

> For search, does the registry maintain a cache of all searchable terms, such as which servers have a MySQL component or does it query every server when the search is made?

I will try to avoid this. I think it will be very fast to do it directly on each netdata server with an async loop. Generally for this kind of search, each netdata will respond in less than a millisecond, but connection setup may be a problem. I will test it before deciding.

**Comment by FallingSnow** [comment]
> If you login at your browser and you sync bookmarks, cookies, etc the PERSONID will be transferred too.

Are you sure cookies are synced too? I have found some resources stating they are not but the resources are out of date. My concern is why store data on a server if it can't be accessed anywhere other than the originating computer, better off storing it in a local form.

Even if cookies are synced, why not store the list in a cookie rather than an external server?

> I will try to avoid this. I think it will be very fast to do it directly on each netdata server with an async loop.

I agree. This will always provide the most up to date information too.

I feel like we have been going back and forth for a while. I understand that you want to store someone's list on an external server so it can be accessed from another computer. But in order to access that information from another computer identifying information must be sent irrespective of the registry, IE. PERSIONID. And if data is already sent without involving the registry, just send the list that way.

**Comment by FallingSnow** [comment]
@simonnagl what are your thoughts?

**Comment by ktsaou** [comment]
ok, I will do some tests to verify persistent cookies are copied and report back.

**Comment by ktsaou** [comment]
I haven't managed to test it yet, but from what I read cookies are not synced, at least by chrome.
I will run test, however if persistent cookies are not synced, the only way to have the list synced, is authentication at the registry.

I'll report back.

**Comment by ktsaou** [comment]
I am experimenting / finalizing the `dictionary.c` code in netdata (which is currently unused) and could be used for the registry.

A few performance statistics:

```
Inserting 1000000 entries in the dictionary
Added 1000000 entries in 987086 nanoseconds: 1013082 inserts per second
 > Dictionary: 1000000 inserts, 0 deletes, 1000000 searches

Retrieving 1000000 entries from the dictionary
Read 1000000 entries in 590006 nanoseconds: 1694898 searches per second
 > Dictionary: 0 inserts, 0 deletes, 1000000 searches

Resetting 1000000 entries in the dictionary
Reset 1000000 entries in 639127 nanoseconds: 1564634 inserts per second
 > Dictionary: 0 inserts, 0 deletes, 1000000 searches

Searching  1000000 non-existing entries in the dictionary
Searched 1000000 non-existing entries in 528582 nanoseconds: 1891854 searches per second
 > Dictionary: 0 inserts, 0 deletes, 1000000 searches

Deleting 1000000 entries from the dictionary
Deleted 1000000 entries in 1297450 nanoseconds: 770742 deletes per second
 > Dictionary: 0 inserts, 1000000 deletes, 1000000 searches
```

This is on a Q6600 (quad core 3Ghz). Wow! This is really fast!

**Comment by ktsaou** [comment]
Well, I work all day with it: https://github.com/ktsaou/netdata/blob/registry/src/registry.c

It is now in a working state, but no load/save and network yet.

And it is fast:

```
Generating 100000 machine guids

Generating 1000000 users accessing 50000 machines
1000000 accesses served in 21.30 seconds (46957 per second)

All 1000000 users accessing again the same 50000 servers
1000000 accesses served in 9.59 seconds (104329 per second)

All 1000000 users accessing a new server, out of the 50000 servers
1000000 accesses served in 9.81 seconds (101972 per second)

1000000 random users accessing a random server, out of the 50000 servers
1000000 accesses served in 10.75 seconds (92993 per second)

1000000 random users accessing a random server, out of 100000 servers
1000000 accesses served in 11.99 seconds (83372 per second)

2000000 random user accesses to a random server, out of 100000 servers, using 1 out of 3 a random url
2000000 accesses served in 27.73 seconds (72113 per second)
```

For 1.000.000 unique users (web browsers) and 100.000 servers (unique netdata installations), it needs about 1GB RAM and it pretty much serves 50.000 - 100.000 queries per second, on a single core of my Q6600 test machine !

**Comment by ktsaou** [comment]
another full day.

registry with load/save is ready.

It allows 3 types of queries:

1. new user accessing a specific machine using a specific url
2. existing user accessing a specific machine using a specific url
3. get all urls a specific machine can be accessed (the interface still missing, but the database is there)
4. delete a specific url from specific user (the interface still missing, but the database is there)

To prevent registry entries loss from server crashes, it works like this:

- all database is indexed in memory
- all queries are logged to `registry-log.db`, a machine readable text file
- on exit, if it manages to save the data to `registry.db` it deletes `registry-log.db`
- on start, it loads both `registry.db` and `registry-log.db`

So, even if the netdata crashes, the whole database is on disk. On restart it will load it back.

These are pending:

- [ ] locking to allow concurrency
- [ ] provide the interface for getting all the urls of specific machine
- [ ] provide the interface for deleting a url for a specific user
- [ ] generate JSON output for all queries
- [ ] extent the API to support registry queries

The current code is pretty stable, it passes all the tests I could do, including several hours of operating at 100.000 random queries/s, valgrind, etc.

**Comment by ktsaou** [comment]
Almost done. The server is almost ready. Still missing the javascript code...

I think this weekend we will have a registry...

**Comment by ktsaou** [comment]
By the way, with all the locking and the on-disk registry log, we are still at around 50.000 queries/s on my test machine....

**Comment by FallingSnow** [comment]
Wow @ktsaou, you've really made some amazing progress over the last few days. I'm looking forward to seeing the registry done.

**Comment by ktsaou** [comment]
Thanks!

The registry is working now, even on the dashboard, but no UI yet. I have to render the menu somehow. I had to re-write a somewhat messy part of netdata, the parsing the web requests to extract the http headers. This was required to to allow it respond to CORS with the proper Origin. Now cookies do travel even in CORS. I have to test it though.


What is now left:

- [ ] build a UI for the registry
- [ ] test everything extensively!

**Comment by ktsaou** [comment]
Netdata with registry (no UI yet): http://netdata-test.firehol.org:19999/#netdata_registry
These are the statistics of its operation.

**Comment by ktsaou** [comment]
Today is a UI day. I'll build a simple drop down list at the header.

BTW, we could also store at the registry these:

1. `users`, just an email and a [HMAC](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code). So, if you know the email and the HMAC generated by your web browser (using a password we will never store) matches, you will get the same cookie.

  Of course, we will need a way to restore it in case someone forgets the password (send an email with a new signature, etc).

2. dashboard settings could be saved at the registry too. So, your dashboard settings will follow you!

**Comment by ktsaou** [comment]
Operational with UI: http://netdata-test.firehol.org:19999/#netdata_registry

Missing the delete function...

**Comment by simonnagl** [comment]
I do not see the UI. Where can it be found?

**Comment by FallingSnow** [comment]
Upper left I believe...

**Comment by simonnagl** [comment]
Could you make a screenshot for me? Am I blind? :see_no_evil:

**Comment by FallingSnow** [comment]
![registry-screenshot](https://cloud.githubusercontent.com/assets/2512197/15207377/9dc4d2be-17da-11e6-8d5e-86c90c4df7c4.jpg)

**Comment by simonnagl** [comment]
Ok. I had to access another public netdata server to see this. 
@FallingSnow: Tank you for the help!

**Comment by ktsaou** [comment]
Later today I will install the 3 demo sites with this version to see it in action learning netdata servers.

Pick a domain for the global registry:

1. netdata-registry.firehol.org
2. registry.netdata.online (I have netdata.online)
3. registry.netdata.rocks (I have netdata.rocks)
4. registry.my-netdata.io (my-netdata.io is free)
5. registry.mynetdata.io (mynetdata.io is free)

**Comment by ktsaou** [comment]
I took all the domains (including the 2 .io). I will make the registry listen on all of them

**Comment by ktsaou** [comment]
guys I am very happy: registry is done !

At the demo sites - play with it... I also added "impersonate" to allow you copy the cookie between browsers (although I think there might be security issues with it). More tomorrow....

**Comment by ktsaou** [comment]
Guys I have opened #416 for discussion about the future of the registry. I think the registry opens a world of new features to netdata. Let's discuss them there.
