### ISSUE TITLE
Change the mail alarm format

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#3100]
We now use email to inform the police, I know the default email alarm format is as follows:

haproxy_via_url.health_bdown
CHART

haproxy last collected (was warning for 50 seconds)
 number of seconds since the last successful data collectionALARM

health
FAMILY

Recovered from WARNING
SEVERITY

Wed Sep 20 17:25:26 CST 2017 
(was warning for 50 seconds)TIME

Can we define the alarm content ourselves?

**Comment by Ferroin** [comment]
The template used is found in the `alarm_notify.sh` script, starting at around line [1611](https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh#L1611).  On my system (may be different for yours), it's located in `/usr/libexec/netdata/plugins.d/alarm-notify.sh`.

You can copy that script elsewhere, modify it as you see fit, and then add (or update) this fragment to your `netdata.conf` file:

```
[health]
        script to execute on alarm = <path>
````

Replace `<path>` with the path to the copy of the script you created.

**Comment by ktsaou** [comment]
@Ferroin is perfectly right.

Another solution is to edit `/etc/netdata/health_alarm_notify.conf` and:

1. set `SEND_EMAIL="NO"` to disable the built in emails.
2. set `DEFAULT_RECIPIENT_CUSTOM="me@example.com"` (or any other recipient)
3. add the code you like at the function `custom_sender()` (at the same conf file) to do whatever you like (`$1` will be the email address you set above).

This way you can keep the netdata maintained `alarm-notify.sh` and add your custom notification sender along everything else netdata does.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.

**Comment by niiihaaad** [comment]
solution provided by @Ferroin does not seem to work
