### ISSUE TITLE
Problems with named and XML

### ISSUE THREAD

**Issue by rstewart-rsi** [firehol/netdata#3105]
I have netdata configured to connect to a local named server.  My issue is the output is XML, the script cant detect the output.  The suggested paths of http://10.0.0.1:8888/xml/v3/server fail with a 404, but if I use http://localhost:8888/ I get output, but its all XML.  Any suggestions, I have been all over the config ( named.conf ) with a fine tooth comb to no avail.  I have installed named on CentOS 7 via the package manager.  Thanks in advance,

./disco

**Comment by ktsaou** [comment]
netdata needs v3 xml. For this you need named v9.10.

The [wiki has information about changing the URL](https://github.com/firehol/netdata/blob/master/conf.d/node.d/named.conf.md#xml-instead-of-json-from-bind) at netdata, but I don't think the v2 xml statistics of named will be parsed by netdata. You can give it a try though.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
