### ISSUE TITLE
how to run single python scrypt

### ISSUE THREAD

**Issue by RossWilliamson** [firehol/netdata#3108]
Maybe this is obvious but I'm trying to run a single python script in python.d.  I have no idea what I need to do in /etc/netdata/python.d.  

- Do I need to create a conf file?  
- Do I need to delete all the conf files in there for the python scripts I don't want to run
- Do I need to delete all the python files in /var/libexec/python.d
- Is there a setting in /etc/netdata/netdata.conf that states that I only want to run a single python script
- Is there a way to debug the plugin outside of netdata?

Apologies for all the questions but I'm struggling to find simple examples that don't including running everything in a default state.

**Comment by l2isbad** [comment]
[how-to](https://github.com/firehol/netdata/wiki/How-to-write-new-module)

[examples](https://github.com/firehol/netdata/tree/master/python.d) (name must be [NAME.chart.py](url))

[debug](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by l2isbad** [comment]
> Do I need to create a conf file?
not necessary

> Do I need to delete all the conf files in there for the python scripts I don't want to run

no

> Do I need to delete all the python files in /var/libexec/python.d

no

> Is there a setting in /etc/netdata/netdata.conf that states that I only want to run a single python script

it is [python.d.conf](https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf)

**Comment by RossWilliamson** [comment]
Thank you - that is really helpful!

**Comment by RossWilliamson** [comment]
So I checked the the python script using the debug outline above and I have the debug showing that it's setting my dimensions:

BEGIN loadcheck.loadcheck 0
SET 'rate' = 412
SET 'accepted' = 284
SET 'accepted_total' = 284
END

But when I enable it in python.d.conf with:  cpuminer: yes

All I get is a /var/cache/netdata/netdata.runtime_loadcheck directory with main.db and run_time.db in it.  I don't get any directory that with "rate" or "accepted" in like I do with example.random (which I've enabled and shows that I have main.db random[1-3].db

Very very confused.....

**Comment by l2isbad** [comment]
post here the whole output from debug

**Comment by RossWilliamson** [comment]
Code: 

`from random import SystemRandom

from bases.FrameworkServices.LogService import LogService

# default module values
update_every = 4
priority = 90000
retries = 60

ORDER = ['cpuminer']
CHARTS = {
    'cpuminer': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['hash_rate'],
            ['accepted'],
            ['accepted_total']
        ]
    }
}


class Service(LogService):
    def __init__(self, configuration=None, name=None):
        LogService.__init__(self, configuration=configuration, name=name)
        self.log_path = '/var/log/syslog'
        self.order = ORDER
        self.definitions = CHARTS

    @staticmethod
    def check():
        return True

    def get_data(self):
        raw = self._get_raw_data()
        if not raw:
                return None

        data = {}

        for row in raw:
                if row.find("cpuminer"):
                        print("CRAAAAP", row)
                        if row.find("Total:") != -1:
                                t_data = row.split("Total:")
                                print("POOOOOOOOP", t_data)
                                data['hash_rate'] = round(float(t_data[1][:-4]))

                        if row.find("accepted:") != -1:
                                a_data = row.split("accepted:")
                                a_data = a_data[1].split("(diff")
                                a_data = a_data[0].split("/")
                                print("PLAAAAAP", a_data[0], a_data[1])
                                data['accepted'] = int(a_data[0])
                                data['accepted_total'] = int(a_data[1])

        return data
                                                         `

**Comment by l2isbad** [comment]
```python
    def get_data(self):
        raw = self._get_raw_data()
        if not raw:
                return None

        data = dict(hash_rate=0, accepted=0, accepted_total=0)
```

**Comment by l2isbad** [comment]
and remove all `print` from the plugin ofc

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
