### ISSUE TITLE
Using a collected variable for max value on easypiechart

### ISSUE THREAD

**Issue by RossWilliamson** [firehol/netdata#3116]
Is there a way to set the maxvalue on an easypiechart (or gauge) by using a collected parameter.  For example:

```
<div data-netdata="test.quick"
   data-dimensions="accepted"
   data-host="http://192.168.1.2:19999/host/host1"  // There may be ~100 of these at some point
   data-chart-library="easypiechart"
   data-????-max-value = "test.quick.total" - i.e. another variable in test.quick
><\div>
```

Note that I don't want to share a max-value for all charts - I just want the max to be set for that partically instance of test.quick on that one client (host1)

I'm also having a lot of difficulty locating a list of options for things like gauge, dygraph and easypiechart (hence the ???? because I don't know what that is)

**Comment by talkyy** [comment]
You can use JavaScript to change min or max value of a chart.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
