### ISSUE TITLE
Chart not loaded

### ISSUE THREAD

**Issue by kramerli** [firehol/netdata#3120]
I write some python chart and put it at python.d. Also the corresponding conf  file in 

    etc/netdata/python.d

Then I run command below  to check if the plugin can work

	python usr/libexec/netdata/plugins.d/python.d.plugin my_chart 

	2017-12-11 17:04:08: python.d INFO: plugin: main: Using python 2
	2017-12-11 17:04:09: python.d INFO: my_chart: mgr: check() => [OK]
	CHART netdata.runtime_my_chart_my_chart.ceph_admin '' 'Execution time for my_chart_my_chart.ceph_admin' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
	DIMENSION run_time 'run time' absolute 1 1

	CHART my_chart_my_chart.ceph_admin.query 'io' 'io_per_second' 'count' 'ceph' 'ceph_ctx' line 70000 1 '' 'python.d.plugin' 'my_chart'
	DIMENSION 'disk_io' 'disk_io' absolute 1 1 ''
	DIMENSION 'mem_io' 'mem_io' absolute 1 1 ''

	BEGIN my_chart_my_chart.ceph_admin.query 0
	SET 'disk_io' = 51
	SET 'mem_io' = 6
	END

	CHART my_chart_my_chart.ceph_admin.io 'qps' 'query_per_second' 'count' 'ceph' 'ceph_ctx' line 70001 1 '' 'python.d.plugin' 'my_chart'
	DIMENSION 'qps' 'qps' absolute 1 1 ''

	BEGIN my_chart_my_chart.ceph_admin.io 0
	SET 'qps' = 20
	END

Looks fine to me.  

But, I can not find the chart on dashboard. Can not find the corresponding api by /api/v1/charts either. So can you give some advice please?

**Comment by l2isbad** [comment]
run it as netdata user
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
