### ISSUE TITLE
send data to influxdb backend failed

### ISSUE THREAD

**Issue by kramerli** [firehol/netdata#3122]
I try to  config the influxdb as backend of netdata. Below are my configuration. The influxdb is 1.4.2

	[backend]
			host tags = ip=my_ip hostname=ceph_node1
			enabled = yes
			data source = as collected
			type = opentsdb
			destination = tcp:influxdb_ip:8086
			prefix = netdata.ceph_admin
			hostname = ceph_node1
			update every = 10
			buffer on failures = 10
			timeout ms = 20000
			send names instead of ids = yes
			send charts matching = netdata.net

But there errors in netdata log as below

    2017-12-11 17:22:59: netdata ERROR: BACKEND: 'tcp:172.25.44.238:8086' closed the socket
    2017-12-11 17:22:59: netdata INFO : BACKEND: received 103 bytes from opentsdb backend. Ignoring them. Sample: 'HTTP/1.1 400 Bad Request  Content-Type: text/plain; charset=utf-8  Connection: close    400 Bad Request'

So is there anything wrong?

**Comment by talkyy** [comment]
Try change port `destination = tcp:influxdb_ip:8086` to `destination = tcp:influxdb_ip:4242` and enable opentsdb in `/etc/influxdb/influxdb.conf`. It will auto generate a database with name opentsdb in influxdb.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
