### ISSUE TITLE
Cannot display absolute value in badge coloured by original value

### ISSUE THREAD

**Issue by magao** [firehol/netdata#3123]
I have a badge that I want to display as an absolute value, but want to colour it depending on what the original value was e.g. green if it was positive, red if it was negative. We don't have any colour-blind people viewing my dashboard ...

Currently the `value_color` option applies against the displayed value, so a URL of the form:

`/api/v1/badge.svg?&chart=mychart&dimension=mydim&options=abs&value_color=grey:null|%235cb85c>0|%23cb3935`

will only ever be grey or green, never red. It would be good to have an option like `options=display_absolute` so only the display value is affected.

**Comment by ktsaou** [comment]
in PR #3125
