### ISSUE TITLE
Zero values are considered null in badge colour conditions

### ISSUE THREAD

**Issue by magao** [firehol/netdata#3124]
If you have a badge `value_color` like:

`value_color=grey:null|%235cb85c>=0|%23cb3935`

then a zero value will be treated as null instead of obeying the second condition. `null` should IMO only refer to when data isn't available for the dimension.

I'm guessing the null check is simply doing a truth test and both empty data and zero evaluate to false.

**Comment by ktsaou** [comment]
thanks! this was a bug.
fixed it - will be merged in a while...
