### ISSUE TITLE
dynamic chart content don't scroll if not click?

### ISSUE THREAD

**Issue by hhgzxn** [firehol/netdata#3126]
Everytime I first load the dashboard, the chart content do not scroll from right to left as time goes by if I do not click the page content.

**Comment by ktsaou** [comment]
Which browser?
netdata does not refresh the charts if the page does not have your focus. For some reason your browser does not give focus to netdata when it starts it.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
