### ISSUE TITLE
Socket push to remote server?

### ISSUE THREAD

**Issue by leemalmac** [firehol/netdata#313]
Hi.

I've searched for similar issues and found similar, but wasn't able to find the answer.

Is it possible to add support for socket push to remote server to collect data instead of making HTTP requests to all servers in a list? I think it would be more simple to manage installations in such a way.

I'm asking because I really fell in love with netdata, and want to use it in production, but I do not want to mess with a list of servers.

I'm not a C ninja-coder, but I think I can implement this with some help from the community.

**Comment by ktsaou** [comment]
Hi,

Pushing data is easy. But the remote server can make things complicated, it we have to adapt / transform / map the data to whatever the other system expects.

So, what would be the remote server?

**Comment by leemalmac** [comment]
The remote server is the server that collects data, like Zabbix which has a central server and agents. That server should expect the same data format as netdata front-end to make things simple. So we still can use Netdata UI without modifications, we just send request to a DB through HTTP api, not to the server directly.

But one possible problem I see, if we monitor 20-50 parameters, the server (that collects data) will receive 20-50 RPS from one agent. It should scale really well for big installations.

**Comment by ktsaou** [comment]
Well, a lot of users ask for something like this. This is why I wrote #178 

I have to admit, since I wrote #178 I spend quite some time thinking of it. I just posted a new comment there with my view. I would like to have your comments...

**Comment by ktsaou** [comment]
netdata now supports streaming metrics to one or more central netdata. Actually, a lot more are supported, like headless data collectors, headless proxies, store and forward proxies, metrics routing, etc.

Check: https://github.com/firehol/netdata/wiki/Replication-Overview
