### ISSUE TITLE
netdata-installer.sh --dont-wait no longer working

### ISSUE THREAD

**Issue by tisc0** [firehol/netdata#3135]
Hi guys,
Got a weird behavior, I might miss something.
Folloging the process : 
```
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/root/kickstart_netdata.sh && bash /root/kickstart_netdata.sh -i netdata-all --non-interactive
cd /root
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata  && ./netdata-installer.sh --dont-wait
```
=> Nothing happen

I tried to debug a bit : 
```
echo DEBUG1

while [ ! -z "${1}" ]
do
        echo "DEBUG2*****"
    if [ "$1" = "--install" ]
        then
        NETDATA_PREFIX="${2}/netdata"
        shift 2
(...)
    elif [ "$1" = "--dont-wait" ]
        then
        DONOTWAIT=1
        echo "DONOTWAIT = ${DONOTWAIT}"
        shift 1

```
- I see DEBUG1 if I call the script without option
- I don't see neither "DEBUG2*****"" nor "DONOTWAIT = ${DONOTWAIT}" with --dont-wait or any other option.
- basic --help doesn't produce any output either

Sorry if it's already noticed in another issue, I search a bit but didn't found any.
I've been deploying it successfully multiple times, and since the quality of  that project is really high, I'm really wondering what did I wrong.

Thanks for help !

**Comment by ktsaou** [comment]
well this is weird. It works for me on all systems.
could you please change DEBUG1 to:

```sh
echo " DEBUG1: '$1', '${1}' "
```

I think it will show the first parameter twice.

Then change this:

```sh
while [ ! -z "${1}" ]
```

to this:

```sh
while [ "z" != "z${1}" ]
```

I think in this case it will enter the loop, but this "fix" has to be applied on all conditions, i.e. I think your bash uses the script options as options to `[` (i.e. `test` command), instead of evaluating them.

This used to be an ancient way of examining strings that start with ` - `, so I wonder: which bash version do your run? which distro is this?

**Comment by tisc0** [comment]
Hi katsaou !
Was working until recently for me too yes :/
CentOS Linux release 7.4.1708 (Core) 
Bash version : bash-4.2.46-29.el7_4.x86_64

For the debug code you suggested : 
```
echo " DEBUG1: '$1', '${1}' "
#while [ ! -z "${1}" ]
while [ "z" != "z${1}" ]
do
        echo DEBUG2
```
The result is no output at all with an option, and that with no option (which make sense) : 

```
root@dse-vm03 01:55:36:  ~/netdata # ./netdata-installer.sh 
 DEBUG1: '', ''
(...)
banner
etc...
```
Nothing special in .bashrc that could change the behavior of it, no fancy stuff either. A mistake somewhere is not to be excluded but I really lack of idea right now, my day's been very long, bed's calling !  :)

Thanks for answering so quickly. I saw you already added the "normalized"  installation of netdata in /etc (#3136 related to #3063) => thanks !
I'll git it a try tomorrow !
++

**Comment by tisc0** [comment]
Found it... I misused /etc/profile.d to put some script started everytime I open a session... and also when scripts like yours are really working in the system.
The exit 1 came from a script of mine in between, thanks bash -x (We do better when we've slept a bit).
The weird is not anymore, victory of the Light again \o/
But you might have changed something, since I've created hundreds of VMs with that very same code in there without a problem, no ?!
