### ISSUE TITLE
dashboard.js - Multiplier? (celsius in thousands)

### ISSUE THREAD

**Issue by dgmarques** [firehol/netdata#3137]
Hello,

I'm using the `dashboard.js` and i need to apply a divider to my values.
I'm getting values like `65000` when it should be `65.00`; the unit is supposedly in celsius but I doubt my cpu temperature is in the thousands. Is there anyway this can be achieved using `dashboard.js`?

Here is a screenshot of what is currently shown:
![screenshot_20171214_172730](https://user-images.githubusercontent.com/34550273/34005867-3d43a3ea-e0f4-11e7-88cc-c8bc1d641f29.png)

Thanks for your time!!

**Comment by talkyy** [comment]
Hi,
What kind of plugin you use to collect CPU temperature? I think you can divide this value in source code of plugin (or not multiple the value).

**Comment by dgmarques** [comment]
Hello @talkyy! 

I'm using this code for generate my temperature graph.

`   <div class="netdata-container"  data-netdata="platform.temperatures" data-title="Temperature" data-dygraph-strokewidth="2" data-dygraph-smooth="false" data-dygraph-highlightcirclesize="4" data-after="-60" data-height="180px"> </div>`

`platform.temperatures` is the only graph that i can do because in my`api/v1/charts` is the only chart that appears as available to measure the temperature.

Thanks for your time!

**Comment by dgmarques** [comment]
Turns out my plugin for the temperature was reading values like `65000` and was giving them to netdata just like that. I modified the plugin to return to netdata the value retrived divided by `1000`.

Thank you for your time and sorry for any inconvenience!
