### ISSUE TITLE
Option to send notifications to Alerta.io?

### ISSUE THREAD

**Issue by kattunga** [firehol/netdata#3147]
Hi,

Is it any way to send alert notifications to Alerta.io ?
Alerta can receive alerts with a simple http call to Webhooks.

Regards

**Comment by ktsaou** [comment]
Hi,

netdata uses a shell script for that: https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh

Can you add alerta.io to it and make a PR?

To add alerta.io you can search for `slack` and copy-paste-rename-adapt for alerta.io.

**Comment by kattunga** [comment]
Hi Costa,

Yes I'll do it and make a PR asap.

Regards

2017-12-19 8:47 GMT-03:00 Costa Tsaousis <notifications@github.com>:

**Comment by kattunga** [comment]
PR done.

![screenshot at 2017-12-20 15 09 44](https://user-images.githubusercontent.com/2139720/34222974-49699506-e59c-11e7-819a-cd7e091d86c6.png)
