### ISSUE TITLE
Option to see all host alarms in one place (ephemeral nodes)

### ISSUE THREAD

**Issue by kattunga** [firehol/netdata#3148]
Hi, 

I set up a master host with 20 nodes streaming data to it.
Is there any way to see all node's fired alarms at the same time.
Right now I need to enter host by host to see each alarm list.
I planing to control about 200 nodes and it is practically imposible without a central page to see all fired alarms.

With this option we can completely replace any Nagios / Zabbix instalation.

Another option is to set up an Alerta.io server, but I don't know how to integrate Netdata with Alerta.

Regards

**Comment by ktsaou** [comment]
Yes, I know. It was scheduled to be implemented with netdata 1.8 but we a bit behind.

For the moment, the only way is to push all alarm notifications to slack of email and monitor them there.

I hope the next netdata version will have this feature.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
