### ISSUE TITLE
Varnish and HAProxy charts appear and disappear...

### ISSUE THREAD

**Issue by tisc0** [firehol/netdata#3152]
... with regular holes in their charts when they appear.
Was 1.8.0-599-gc6252a0_rolling, upgraded to v1.9.0-8-ge928d0d_rolling.
Just checked home on my linux Google chrome navigator and FF, and impossible to reproduce what happened under Windows 10, Vivaldi, Chrome or Firefox...
I'll recheck tomorrow... but don't tell me I have [again] a ghost in the skull...

AH! Just happened again under nux ! Holes, andd then a refresh and those 2 charts disappeared !
Sreenshot attached
![screenshot from 2017-12-19 00-10-59](https://user-images.githubusercontent.com/18009937/34132672-3e99bca6-e451-11e7-88cf-0d5373f568bd.png)
![screenshot from 2017-12-19 00-10-43](https://user-images.githubusercontent.com/18009937/34132673-3eba1c4e-e451-11e7-9d28-be221815bddb.png)

Actually, no data missing in grafana... which is a good news.

**Comment by l2isbad** [comment]
Can you show a cpu usage graph?

If there is no sensitive information i suggest to share the snapshot 😄

**Comment by tisc0** [comment]
Hi l2isbad ,
The CPU usage is seriously sleepy :) I'ts a proxy machine with low activity during this period.
Sorry, can't share the snapshot, it's a client machine (might be cool to anonym-ize the ssnpass ?! ;]). 
But I'll push one as soon as I can reproduce the problem on a test machine !

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
