### ISSUE TITLE
get max conntrack

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#3154]
Hi. It would be great if netdata were able to also report the `net.nf_conntrack_max` value.
```
sysctl -a | grep net.nf_conntrack_max
net.nf_conntrack_max = 1000000
```

**Comment by ktsaou** [comment]
It is already there:

![screenshot from 2017-12-19 16-17-14](https://user-images.githubusercontent.com/2662304/34161092-1e995fa6-e4d8-11e7-93e6-9cbc68cf5666.png)

The max does not change over time. So, netdata does not chart it, but it uses it to calculate % full of conntrack.

**Comment by vaheminasyan** [comment]
Thanks a Lot.
