### ISSUE TITLE
Out Of Memory monitoring

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#3155]
Hi，ktsaou
    We now want to use netdata to monitor oom, do you have time to help write a plug-in?Thank you very much!!!

**Comment by ktsaou** [comment]
it is already there:

![screenshot from 2017-12-19 16-15-08](https://user-images.githubusercontent.com/2662304/34161018-d6afe8fe-e4d7-11e7-8c99-094c8a5f88cd.png)

what else you need?

**Comment by FANGXIANGQUAN** [comment]
@ktsaou Think you !
