### ISSUE TITLE
python.d/mysql.conf: MySQL user & GRANT OPTION

### ISSUE THREAD

**Issue by gdelafond** [firehol/netdata#3158]
Hello,

In the default file python.d/mysql.conf file there is the SQL request to create a SQL user needed by netdata.
```
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost' with grant option;
# > flush privileges;
```
Is the "grant option" really needed ? If yes, could you explain why ?

Here is the official doc (from https://mariadb.com/kb/en/library/grant/#the-grant-option-privilege) for the the GRANT OPTION Privilege : 

> Use the WITH GRANT OPTION clause to give users the ability to grant privileges to other users at the given privilege level. Users with the GRANT OPTION privilege can only grant privileges they have. They cannot grant privileges at a higher privilege level than they have the GRANT OPTION privilege.
> 
> The GRANT OPTION privilege cannot be set for individual columns. If you use WITH GRANT OPTION when specifying column privileges, the GRANT OPTION privilege will be granted for the entire table.
> 
> Using the WITH GRANT OPTION clause is equivalent to listing GRANT OPTION as a privilege.

Thank you.

**Comment by ktsaou** [comment]
oops! No, it should not be needed.
Could you please check that it works without it?

**Comment by gdelafond** [comment]
It works without it (we are already using it without the GRANT OPTION), we need the REPLICATION CLIENT rights to get slave status on MySQL slaves servers.

**Comment by ktsaou** [comment]
So how is the right one?

```
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost';
# > grant replication client on *.* to 'netdata'@'localhost';
# > flush privileges;
```

?

**Comment by gdelafond** [comment]
REPLICATION CLIENT implies USAGE, so we can put only : 

```
# > create user 'netdata'@'localhost';
# > grant replication client on *.* to 'netdata'@'localhost';
# > flush privileges;
```

**Comment by ktsaou** [comment]
merged the fix. thanks!
