### ISSUE TITLE
api call to get data in shell friendly format

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#316]
It would be nice to support something like this:

``` sh
eval "$(curl http://localhost:19999/api/v1/chart=system.cpu&format=shell&after=-600&options=unaligned)"
```

This should create the variables `SYSTEM_CPU_SYSTEM`, `SYSTEM_CPU_USER`, `SYSTEM_CPU_WAITIO`, etc (one for each dimension of the chart), having the average utilization of the last 600 seconds.

**Comment by simonnagl** [comment]
I think we can close this.

**Comment by ktsaou** [comment]
you are right!

for anyone looking at this: #1504
