### ISSUE TITLE
install error on FreeNAS (FreeBSD)

### ISSUE THREAD

**Issue by nojohnny101** [firehol/netdata#3161]
Great tool! Have it running great on my raspberry pi 3 but want to get it up and running on my FreeNAS box.

I followed the install instructions under the FreeBSD section but I can ran into this error:

```
Making all in src
cc             -O2 -I/usr/local/include -D_THREAD_SAFE -pthread   -o netdata adaptive_resortable_list.o  appconfig.o avl.o backend_prometheus.o  backends.o clocks.o common.o  daemon.o dictionary.o eval.o  global_statistics.o health.o  health_config.o health_json.o  health_log.o log.o main.o  plugin_checks.o plugin_idlejitter.o  plugins_d.o popen.o procfile.o  registry.o registry_db.o  registry_init.o registry_internals.o  registry_log.o registry_machine.o  registry_person.o registry_url.o rrd.o  rrd2json.o rrd2json_api_old.o  rrdcalc.o rrdcalctemplate.o rrddim.o  rrddimvar.o rrdfamily.o rrdhost.o  rrdpush.o rrdset.o rrdsetvar.o  rrdvar.o signals.o simple_pattern.o  socket.o statistical.o statsd.o  storage_number.o unit_test.o url.o  web_api_old.o web_api_v1.o  web_buffer.o web_buffer_svg.o  web_client.o web_server.o plugin_freebsd.o  freebsd_sysctl.o  freebsd_getmntinfo.o  freebsd_getifaddrs.o  freebsd_devstat.o zfs_common.o  freebsd_kstat_zfs.o  freebsd_ipfw.o    -lm    -lz  -L/usr/local/lib -luuid   
appconfig.o: In function `appconfig_get_float':
appconfig.c:(.text+0xbc2): warning: powl has lower than advertised precision
main.o: In function `kill_childs':
main.c:(.text+0x5b4): undefined reference to `tc_child_pid'
main.c:(.text+0x5be): undefined reference to `tc_child_pid'
main.c:(.text+0x5df): undefined reference to `tc_child_pid'
main.c:(.text+0x5f5): undefined reference to `tc_child_pid'
main.c:(.text+0x60b): undefined reference to `tc_child_pid'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** [netdata] Error code 1

make[2]: stopped in /netdata/src
1 error

make[2]: stopped in /netdata/src
*** [all-recursive] Error code 1

make[1]: stopped in /netdata
1 error

make[1]: stopped in /netdata
*** [all] Error code 2

make: stopped in /netdata
1 error

make: stopped in /netdata
 FAILED
```

Any ideas?

**Comment by tisc0** [comment]
+1 : same problem under FreeBSD 10.3p26
pkg install bash e2fsprogs-libuuid git curl autoconf automake pkgconf pidof => OK
Then same compilation problem than nojohnny101, despite a previous successful install under the same OS, same repository, same packages versions.
I guess some libs/packages are missing ? 

Thanks for  help.

**Comment by ktsaou** [comment]
Could you please retry?
I think it has been fixed by a PR merged yesterday.

**Comment by nojohnny101** [comment]
Thanks for the update. The install goes off without a hitch now, no errors this time.

However upon completion of installation, the UI is not reachable through http://ip.address:19999

Running "service netdata start" from within the jail that I installed netdata in gives:

`root@netdata:/netdata # service netdata start
netdata does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
root@netdata:/netdata # `

**Comment by ktsaou** [comment]
hm... I don't know how to create a startup script for freenas - although the current version of netdata includes a startup script fro freebsd.

So, I am closing this. If there is something missing, let me know.
