### ISSUE TITLE
Add type sum to statsd counters' dimensions

### ISSUE THREAD

**Issue by bsphere** [firehol/netdata#3163]
I'm sending performance metrics from an embedded app to netdata with statsd. 
some infrequent events are being sent as counters but its much more useful to chart the sum and not occasional ticks..

**Comment by ktsaou** [comment]
You are right. This will be useful.

I was thinking of adding support for dimensions like this:

```
dimension = calc EXPRESSION TO EVALUATE
```

where `EXPRESSION TO EVALUATE` could use any statsd metric like this: `(${statsd.metric.1} + ${statsd.metric.2}) * ${statsd.metric.3}`.

But, I think you probably need something completely different, like: `sum(metric.*)`, that is sum all the dimensions matching a pattern.

**Comment by bsphere** [comment]
actually what I'm looking for is like sending gauges with +/-, but staying true to the standard statsd protocol which doesn't support that... I want to increase counters, but I don't care about rate of changes because of the low update frequency.

calculated metrics sounds awesome, especially if you have some functions like time() so you can do stuff with timestamps...

**Comment by ktsaou** [comment]
You need to send gauges. netdata gauges support +/- and stay there (they are not rates). So instead of `metric:+1|c`, send `metric:+1|g`.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
