### ISSUE TITLE
Modify the switch port flow unit

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#3165]
At present, SNMP monitors the port flow of the switch, the unit is kilobits/s, and the configuration is written to die in SNMP. Conf, can you please adjust the unit according to the volume of the traffic?For example, when small, it was kilobits/s, big time for megabit/s

**Comment by ktsaou** [comment]
It should do it by itself. 

Here is mine, that does it:

![screenshot from 2018-01-03 13-29-26](https://user-images.githubusercontent.com/2662304/34518874-279c9f24-f08a-11e7-9661-a133e6d09a36.png)

Could you please post your snmp config? Most probably the units are misspelled.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
