### ISSUE TITLE
apcupsd and multiple devices

### ISSUE THREAD

**Issue by sega-yarkin** [firehol/netdata#3167]
Hi guys!
Is it possible to extend apcupsd module to working with multiple UPS devices?
We can start several apcupsd daemons on different ports and it will be great if script supports taking a list of ports instead a single port. In parameters name we can append destination port or look for UPSNAME field from UPS status (that is better).
Thanks!

**Comment by ktsaou** [comment]
Hi. Done in PR #3211 
Will be merged in a while.

**Comment by ktsaou** [comment]
merged it

**Comment by sega-yarkin** [comment]
@ktsaou Thanks, everything works great!
