### ISSUE TITLE
Not able to build rpm

### ISSUE THREAD

**Issue by vadirajks** [firehol/netdata#3169]
Not able to build rpm :
extracting debug info from /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/libexec/netdata/plugins.d/apps.plugin
extracting debug info from /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/sbin/netdata
4055 blocks
+ /usr/lib/rpm/check-rpaths /usr/lib/rpm/check-buildroot
Processing files: netdata-1.9.1-1.el6.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/libexec/netdata/plugins.d/cgroup-network
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.Nkk2b2
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd netdata-1.9.0-31-g93fa1cc_rolling
+ DOCDIR=/root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/share/doc/netdata-1.9.1
+ export DOCDIR
+ rm -rf /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/share/doc/netdata-1.9.1
+ /bin/mkdir -p /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/share/doc/netdata-1.9.1
+ cp -pr README.md /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/share/doc/netdata-1.9.1
+ exit 0

RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/netdata-1.9.1-1.el6.x86_64/usr/libexec/netdata/plugins.d/cgroup-network

Thanks,

**Comment by Wing924** [comment]
I think cgroup-network is not exist on el6.

**Comment by ktsaou** [comment]
Hi.

I think I fixed it in PR #3213

**Comment by ktsaou** [comment]
merged it.

**Comment by ktsaou** [comment]
I also added a script to build the rpm: https://github.com/firehol/netdata/blob/master/contrib/rhel/build-netdata-rpm.sh - I plan to add this to travis to make sure we always are able to build RPMs.
