### ISSUE TITLE
Support HTML5 notifications

### ISSUE THREAD

**Issue by gdraynz** [firehol/netdata#317]
It would be awesome to have a way to set up thresholds in data graphs that would throw [html5 notifications](https://developer.mozilla.org/fr/docs/Web/API/notification) upon reaching a configurable % value.
I didn't see anything about this kind of feature.
Any thoughts ?

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
PR #775 adds alarms to netdata.
No UI yet - until we stabilize the server code.
I am looking for beta testers. If you are interested join the discussion there.

**Comment by ktsaou** [comment]
merged it.
