### ISSUE TITLE
Web server does not support symlinks for files (Linux)

### ISSUE THREAD

**Issue by magao** [firehol/netdata#3171]
I have my custom dashboard being developed in a Mercurial repository, and wanted to symlink the files into the NetData web server directory. Doing so resulted in access denied errors for the symlinked files.

My solution was to move everything into a directory and symlink the directory, which worked. Another alternative (if the files are on the same filesystem) is to hardlink.

Is this a bug, or are symlinked files being actively excluded?

**Comment by ktsaou** [comment]
This is for security reasons. The netdata web server:

1. does not allow `..` in the URL paths
2. does not serve symlinked files
3. checks all files it serves for user and group ownership (defined in `netdata.conf`)

The whole idea is to avoid a possible abuse using the netdata web server. So, it is quite strict.

Keep in mind you can host your custom dashboard on any web server. There is no need to put it on netdata.

**Comment by magao** [comment]
In that case I think it should probably be stricter - it should probably check for symlinks in any path under the NetData web/ directory. Although personally that would be a pain for me since it would mess with my development setup.

**Comment by ktsaou** [comment]
I think it is not needed. Actually I could allow symlinked files, as long as the 3rd point remains. So, netdata could server symlinked files if the files they point to have the right ownership.

The whole idea is to prevent netdata from serving `/etc/passwd` or other system files, and the only real constrain is point 3.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
