### ISSUE TITLE
Netdata Phone Home?

### ISSUE THREAD

**Issue by rohn-niaid** [firehol/netdata#3172]
We installed and then immediately uninstalled netdata due to the first batch of warning emails that were recevied which indicated included a URL indicating that we could view the Warning message on "https://registry.my-netdata.io/goto-host-from-alarm?host=OUR HOST&Details of the warning"  which in part meant that details of our environment as revealed in the warning had been transferred to the registry-my-netdata.io  server.  

I could not find a warning of this broadcasting of internal data to an external host.  What did I miss?

**Comment by ktsaou** [comment]
Setup your own registry (click `my-netdata` then `what is this?` for more info).

So, this is the flow:

1. Your netdata sent you an email.
2. The email needs to know the URL for accessing your netdata. But which is it?

To solve this problem, netdata follows this procedure:

3. Your browser has accessed the netdata dashboard in the past (if it hasn't the email click will not work).

4. When you viewed the dashboard, your web browser got a unique random GUID from the registry and has registered this netdata to the netdata registry (you can have your own registry - the default is a free service I maintain). So, it told the registry that netdata No X (random GUID generated by your netdata), with name `AA` can be accessed at URL `http://whatever:19999/`)

5. You click the email, and your browser opens a page at the registry saying "Hey I want to access a server I have accessed in the past. It is called `AA`".

6. The registry looks up this in its database and diverts your browser to your netdata. If you have accessed your netdata via multiple URLs, the registry will give them all to your browser, and a script will check which one works now.

That's all...

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you need help, just post.
