### ISSUE TITLE
health monitoring / alarms / notifications

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#318]
Let's see what basic alarms / notifications could mean:

Each netdata should be able to perform simple health monitoring checks.

A simple health monitoring is something like any of these:
1. check that dimension/metric `M` is `above X` or `below X` on the average for the last `S` seconds and set alarm `A1` to on if it is and off if it is not.
2. check that dimension/metric `M` has never gone `above X` or `below X` in the last `S` seconds and set alarm `A1` to on if it has and off if it has not.
3. check that dimension/metric `M` has been updated in the last `S` iterations (1 iteration = the dimensions `update_every` seconds) and set alarm `A2` to on if it has not and to off if it has.
4. check that dimension/metric `M` exists (has been collected at least once) and set alarm `A3` to on if it is not and off if it is.
5. check that alarm `A1` is on `and` / `or` alarm `A2` is on and set alarm `A4` when both are on, or off when either is off.

For stacked charts, `M` could be:
- an absolute value for a dimension
- an absolute value for the total of the chart
- a percentage of a dimension vs the chart total

Alarm actions should take place when alarms switch states (on-to-off, off-to-on) and the action should be:
1. execute a script to handle the alarm
2. show the alarm on the dashboard

Alarms could be propagated to a central alarm daemon that could trigger cross server alarms and notifications.
## What is an alarm?

For the user, an alarm is:
1. a unique id / name
2. a machine readable description of what to check
3. a state (`on` or `off`)

Internally, in netdata, in addition to the above, an alarm:
1. has one or more dependencies (charts, dimensions or other alarms)
2. has one or more dependants (other alarms that should be checked when this alarm switches state)
## Healthd

The communication between netdata and healthd should be signed. It is not crucial to be encrypted, but it has be signed so that the health server will know it is talking to the right netdata.

This is how it can work:
1. Each netdata will have a public and a private health GUID. These are like the `machine_guid` of the registry. The public GUID will be given to the registry with each message, while the private one will be used for signing all messages it sends to the health server.
2. At each netdata configuration there will be a `[health]` section. In this section the URL of the health server will be set.
3. Each netdata will have a new thread to take care of its communication to the netdata server.
4. Every time an alarm switches state, netdata will give a unique incremental ID to the event, sign (HMAC) the whole message with its private key and send it to healthd.
5. healthd will accept events only for the netdata for which it has their private health GUID.

**SPECS IN PROGRESS**

**Comment by ktsaou** [comment]
Related issues: #317 #88 #178

**Comment by simonnagl** [comment]
I think we should add another point:

1a. check that dimension/metric M is above or below for the last S seconds and set alarm A1 to on if it is and off if it is not.

**Comment by ktsaou** [comment]
> 1a. check that dimension/metric M is above or below for the last S seconds and set alarm A1 to on if it is and off if it is not.

where is the difference? The "average"?

**Comment by simonnagl** [comment]
Yes. Checking for averange allows peaks. Checking if a value never goes above ore below a secified value does not.

**Comment by ktsaou** [comment]
Oh! I see, you mean this:

- check that dimension/metric ` M ` has never gone `above` or `below` in the last ` S ` seconds and set alarm ` A1 ` to on if it is and off if it is not.

right?

**Comment by simonnagl** [comment]
Yes. This is correct. Sorry if my english was not correct or exact. I am no native speaker and still learning.

**Comment by ktsaou** [comment]
> I am no native speaker

I am not either. No problem.

**Comment by ktsaou** [comment]
added it to the specs.

**Comment by jurgenhaas** [comment]
Love this approach. I'd like to add to **What is an alert?** that you probably want to add a configurable snapshot to it, configurable such that you want to define the timestamp for which snapshot relative to the alert you want to attach.

**Comment by ktsaou** [comment]
After the poll in #436 this is the issue that got most attention. Since this is what most people need, I already spend some time thinking what to do.

So, the following is what I have concluded so far. If you have any thoughts, share them, before it is too late.

I'll describe how the configuration will be made. I hope this will explain the flexibility we will get.

---

## Health configuration

A configuration file (probably `health.conf`) will exist. This configuration will accept the following format (I like the yaml configuration @paulfantom implemented in `python.d.plugin`, so, I am thinking of converting everything to yaml, including this).

```yaml
name:
  on: chart name, context name, including dimensions
  eval: description of how to calculate the value to check
  warning: a Boolean expression that should result in TRUE or FALSE
  critical: a Boolean expression that should result in TRUE or FALSE
```

Let's see an example:

```yaml
total_cpu_60s:
  on: system.cpu;
  eval: average(-60s);
  critical: > 95;
  warning: > 80;
```

This will calculate **on every update of `system.cpu`** the average of the last 60 seconds, check if it is above 80.

To understand all the options, let's see how this will be internally interpreted:

```yaml
total_cpu_60s:
  on: system.cpu/all;
  eval: average(-60s at 0 every 1s);
  critical: $total_cpu_60s > 95;
  warning: $total_cpu_60s > 80;
```

Let's see each line in detail:

- `total_cpu_60s` is the name of this monitor.

- `on: system.cpu/all` defines the chart and the dimensions to be evaluated. Dimensions will be accepted after the `/`, comma separated.

  To define templates, I think we should also support `@context/dimensions`. So this monitor will be automatically attached to all charts with this `context`.

- `eval: average(-60s at 0 every 1s)` calculates the average the last 60 seconds, starting from point 0 (the latest), every second.

  To understand how flexible this is: `eval: average(-3600s at -3600 every 10s)` will calculate the average of an hour, starting one hour in the past, every 10 seconds.

  Other functions will be `max()`, `min()`, `sum()`, `incremental()` (incremental sum).

  I am also researching an infix expressions parser for use here. So that we could say `average(-60s) * 100 / average(-120s)`. 

  Here is where it gets interesting: we should be able to refer to other chart, system and monitoring variables by name. I am thinking of defining a few global variables and a few local ones. Examples:

  - `$now` is the current timestamp (global)
  - `$last_collected_t` is the timestamp the chart was last collected
  - `$first_collected_t` is the timestamp of the oldest data for the chart
  - `$name` will resolve to the `eval` line of any other defined monitor (!) so that on another monitor we could write `eval: $total_cpu_60s + ... / ...`

- `critical` and `warning` are expressions that are evaluated to TRUE or FALSE. Variables will be available here too, with these additions:

  - `^name` will resolve to the `warning` status of any other monitor (0 or 1).
  - `!name` will resolve to the `critical` status of any other monitor (0 or 1)

  I think though these are very cryptic, so probably functions will be better: `warning(name)` and `critical(name)`. We could also support `value(name)` instead of `$name`.

I believe the values of the monitors should be charted in netdata too: each monitor definition will also have its chart, probably in a special area in the dashboard. So we will be able to see them in action.

Still researching... Any ideas are welcome.

**Comment by paulfantom** [comment]
Maybe don't do checking based on seconds, but on cycles, same way as [monit](https://mmonit.com/monit/documentation/monit.html) does it (will be the same if `update_every` is 1).

I don't think we should chart monitors data because essentially alerts are booleans. Maybe implement #531 first and then use it to show alerts. This way maybe we could also attach it to monitored chart.

**Comment by ktsaou** [comment]
Charts about the `eval` section of the monitors. Not about the status. I think there should a menu on the dashboard, to show all the monitors (a chart and a status for each).

**Comment by swiftugandan** [comment]
As part of alerting, how are we going to guard against floods of notifications when a given alert persists? Will there be some sort of backoff?

**Comment by ktsaou** [comment]
> As part of alerting, how are we going to guard against floods of notifications when a given alert persists? Will there be some sort of backoff?

nice point!

**Comment by ktsaou** [comment]
for those interested to monitor my progress on health monitoring, I am commiting changes to this repo: https://github.com/ktsaou/netdata/tree/health

So, far:

1. netdata internal structures can now handle multi-host data. This opens the door for central mirroring of the data (I will not proceed in this direction further until several other improvements are made).

2. there are 3 indexes of variables that can be used in health monitoring expressions: **chart local variables**, **context variables** and **host variables**.

3. netdata populates all charts and dimensions as variables automatically. This has been done without adding any overhead to netdata runtime; netdata continues to run as efficient as before,

4. netdata now has an infix expression parser that supports normal calculations but also boolean expressions. I finished the parser today. I had to write this by myself. I experimented with a few solutions found online, but the complexity was too high to make it do what we need it to do.

What remains to have operational health monitoring in netdata:

1. finish the expression evaluator (especially the part that will use the variables in the indexes)

2. parse the health configuration file and convert it to internal structures (I will make a few changes to the proposed design above).

3. have a separate thread in netdata to handle alarms (this will just call an external script for the moment)

4. show something in UI about the currently raised alarms and the alarms log.

5. test everything.

I'll keep posting my progress...

**Comment by davidak** [comment]
let me know when i can do 5. :)

had i said that grafana is also integrating alerting? maybe you can get inspired by some of their ideas and thoughts or get in contact with them. https://github.com/grafana/grafana/issues/2209

**Comment by ktsaou** [comment]
thanks for the lead. This is a very interesting topic.

Check this comment: https://github.com/grafana/grafana/issues/2209#issuecomment-152254218. The way I am designing netdata, I believe it will solve all of them.

**Comment by ktsaou** [comment]
@davidak can you help testing the expressions parser? If yes, check out my repo (the `health` branch), build netdata and compile the `test-eval.c` in the `profile` directory (at its top it has the command line to compile it).

It works like this:

```sh
$ ./test-eval '10+20*(2+3)/2+-4/2'

OK
Expression: '10+20*(2+3)/2+-4/2'
Parsed as : '((10 + ((20 * (2 + 3)) / 2)) + (-4 / 2))'
Error code: 0 (success)

Evaluates to: 58.000000
```

it supports the following operators: `+`, `-`, `*`, `/`, `>`, `<`. `>=`, `<=`, `!`, `==`, `!=`, `<>`, `NOT`, `&&`, `AND`, `||`, `OR`. Boolean operators return either `1` or `0`. It should also support precedence on the operators. Decimal numbers are also supported.

This is the building block for all calculations that will check if a metric reached the warning or critical level.

**Comment by ktsaou** [comment]
We have health monitoring now!

If you are interested to join the beta testers, join the discussion on PR #775

**Comment by ktsaou** [comment]
merged health monitoring

**Comment by opcode02** [comment]
Is there a way to disable HTML notification style alarms, like you can for other types of alarm notifications? I can't seem to find anything referencing that in any of the health.d documents.

**Comment by ktsaou** [comment]
Do you want to disable alarms entirely or just HTML notifications?
To disable them entirely, you can set `[health].enabled = no` in `netdata.conf`.

**Comment by opcode02** [comment]
Actually it comes down to 1 alarm, we have a large Linux system that has mariadb running on it. You recently added support for monitoring the mysql slow query log, this is a dev system where we have non indexed queries in the same slow query log so devs can look and decide if that non indexed query needs and index. 

My problem is I watch netdata and I want to see HTML notifications for alarms but that slow query log is over the top since we have quite a few things in that log all the time. I would like the disable that one alarm for HTML, I found a way around it by ending the slow query alarm parameters in the health.d directory and setting the trip numbers much higher. 

I guess what I'm proposing is a way to turn off single alarms that doesn't involve changing a bunch of numbers so they can be turned on/off easily.

**Comment by ktsaou** [comment]
I think it is time to close this.

**Comment by rm4** [comment]
where  path  health,conf ? i cannot find file health.conf

**Comment by ktsaou** [comment]
There is no `health.conf`.

There is:

1. section `[health]` in `netdata.conf`
2. file `health_alarm_notify.conf` you can edit with:

```sh
/etc/netdata/edit-config health_alarm_notify.conf
```
