### ISSUE TITLE
freeradius: freeradius: "secret" not set

### ISSUE THREAD

**Issue by idsecurity** [firehol/netdata#3188]
Hello,

I'm trying to set up netdata 1.9.0-68-g35cb6fbf_rolling to monitor freeradius on SLES 12 SP3.

I've edited freeradius.conf and uncommented host, port and secret.
But when I restart netdata I get a complaint in the error.log:

`python.d ERROR: freeradius: freeradius: "secret" not set`

Any ideas how I can troubleshoot it further?

Thanks!

**Comment by l2isbad** [comment]
it works

![screenshot_20171229_112213](https://user-images.githubusercontent.com/22274335/34427915-9eb3c046-ec8a-11e7-9101-536f4dec895e.png)

**Comment by idsecurity** [comment]
Hi,
After reverting to the original file and adding `secret` to the **end** of the file it works. 
Thanks!
