### ISSUE TITLE
Common issue

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3191]
I have posted a number of recent questions and I thank you for the assistance I have been given. I am noticing some "common" issues, especially those that start with http://127.0.0.1... in that some tend to get "Connection Refused" status. 
Since all these tend to be local queries, would this say ports need to be open or services are not running to process these ports?

**Comment by ktsaou** [comment]
A "connection refused" is handled by the kernel, and is triggered when no application server is listening on the port in question.

Could you please provide a few instructions to reproduce the issue you face?
