### ISSUE TITLE
Can't make "View Netdata" link in health notification work

### ISSUE THREAD

**Issue by tom--** [firehol/netdata#3196]
The registry appears to work and I have shared it across two browsers.

![menu](https://monosnap.com/file/Pf7gsmDyv7HHSSUfOg02WJC67Wtl9X.png)

But the "Vew Netdata" link in any health notification email results in this:

![notice](https://monosnap.com/file/yA2eN6vmTxoQYizz00K7c2DyyotSfv.png)

The https URL here is correct. A moment later the message updates to 

**Added all the known URLs for this machine.**

I can't discover how to resolve this.

**Comment by ktsaou** [comment]
if you click one of the "failed" URLs, does the right netdata dashboard open?

**Comment by tom--** [comment]
@ktsaou Yes, the failed URLs work when I click on them.

In case it is relevant, I use nginx as reverse proxy to the netdata web server as upstream. The nginx location has HTTP basic auth for password protection.

**Comment by ktsaou** [comment]
Did you solve it?

Now that I think of it, you may have filtered the `OPTIONS` http requests, which are automatically made by web browsers when a page makes a ajax call to a different host.

I suggest to check your nginx and netdata access logs. Most probably they are filtered somehow.

**Comment by angel333** [comment]
I've had the same problem and for me the culprit was indeed Apache's HTTP basic auth (the error is visible in browser's developer tools). Unfortunately, if your netdata have to be in DMZ (like mine), I don't have a proper solution. I solved it by authorizing by IP (in addition to basic auth) - that obviously works but it's just a workaround.

Another option could probably be just leaving `OPTIONS` unsecured. Although I personally wouldn't go that route, it should be safe to do.

Proper solution would probably be just not having netdata in DMZ. Client certificate auth might work too.

**Comment by tom--** [comment]
@angel333 I use nginx but I agree the HTTP basic auth is most likely what breaks it.

In my config, each host with netdata runs the netdata server on port 19999 on its private VLAN interface. One server provides rproxy for them. Idk if this is equivalent to a DMZ. Its nginx public-facing server block has

        # reverse proxy for netdata monitor server
        location ^~ /net/data {
            auth_basic "Authentication Required";
            auth_basic_user_file netdata-access;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_pass_request_headers on;
            proxy_set_header Connection "keep-alive";
            proxy_store off;
            gzip on;
            gzip_proxied any;
            gzip_types *;

            # For each netdata host, e.g. foo, a location block like this
            location ~ /net/data/foo/(?<ndpath>.*) {
                proxy_pass http://foo_netdata_backend/$ndpath$is_args$args;
            }
        }

And for each netdata host an upstream is defined like this

    upstream foo_netdata_backend {
        server foo_address:19999;
        keepalive 64;
    }
