### ISSUE TITLE
[ HipChat ] HTML <small> tag not supported 

### ISSUE THREAD

**Issue by cig0** [firehol/netdata#3200]
Hi,

While testing HipChat integration I noticed the `<small>` HTML tag was being printed alongside the alert messages, as shown below:

![screen shot 2017-12-31 at 00 18 57-compressed](https://user-images.githubusercontent.com/394089/34462847-4d2845f6-ee2b-11e7-881f-cd9d11aabb41.png)

It turns out that HipChat doesn't render this tag, as stated here: https://developer.atlassian.com/server/hipchat/messages/ (although Confluence does, as explained here: https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html).

So, after editing the `# prepare HTML versions of elements` section from `alarm-notify.sh` and removing them, alert messages are now correctly displayed:

![screen shot 2017-12-31 at 12 42 51-compressed](https://user-images.githubusercontent.com/394089/34462894-f29273d6-ee2b-11e7-932e-f2ab4b046ba8.png)

There are some ways to workaround this issue, maybe the easiest (and simplest?) one being adding a conditional statement to detect if `info_html` and `raised_for_html` are meant to be displayed on HipChat.

I would be happy to do this myself, but maybe you guys have an approach that better suites your style or needs.

Thanks!

**Comment by ktsaou** [comment]
Hi,

thank you trying it. I was looking for someone to confirm this works! (someone requested, we built it, but we never got feedback about it).

Can you try something? Please edit `alarm-notify.sh` and change this:

```sh
send_hipchat() {
    local authtoken="${1}" recipients="${2}" message="${3}" httpcode sent=0 room color sender msg_format notify

```

to this:

```sh
send_hipchat() {
    local authtoken="${1}" recipients="${2}" message="${3}" httpcode sent=0 room color sender msg_format notify

    # remove <small></small> from the message
    message="${message/<small>/}"
    message="${message/<\/small>/}"

```

Since, the only problem is `<small></small>` I thought the easiest fix is just to remove them from the message hipchat will send.

If this works, I will make a PR.

**Comment by cig0** [comment]
Hi @ktsaou, thanks for the quick reply.

As per your request, I added:
``` bash
# remove <small></small> from the message
message="${message/<small>/}"
message="${message/<\/small>/}"
```

right after:
```bash
send_hipchat() {
    local authtoken="${1}" recipients="${2}" message="${3}" httpcode sent=0 room color sender msg_format notify
```

so now it looks like:
```bash
# -----------------------------------------------------------------------------                                                                                                                                                               
# hipchat sender                                                                                                                                                                                                                              

send_hipchat() {
    local authtoken="${1}" recipients="${2}" message="${3}" httpcode sent=0 room color sender msg_format notify

    # remove <small></small> from the message                                                                                                                                                                                                 
    message="${message/<small>/}"
    message="${message/<\/small>/}"

    if [ "${SEND_HIPCHAT}" = "YES" -a ! -z "${HIPCHAT_SERVER}" -a ! -z "${authtoken}" -a ! -z "${recipients}" -a ! -z "${message}" ]
    then
...
...
```

Now, as you can see from the following screenshot, the `<small>` tag is removed only from the first notification:

![screen shot 2018-01-02 at 22 02 54-compressed](https://user-images.githubusercontent.com/394089/34506188-61683a00-f009-11e7-8663-bf1bdfc84738.png)

Also, can you explain me how the substitution in `message="${message/<small>/}"` works?

**Comment by ktsaou** [comment]
hm.... yes, it should be:

```sh
    # remove <small></small> from the message                                                                                                                                                                                                 
    message="${message//<small>/}"
    message="${message//<\/small>/}"
```

The substitution is:

1. replace the first occurrence of  `OLD` with `NEW`: `${string/OLD/NEW}`
2. replace all the occurrences of  `OLD` with `NEW`: `${string//OLD/NEW}`

Example:

```sh
# x="hello"; echo ${x/l/L}
heLlo
# x="hello"; echo ${x//l/L}
heLLo
```

**Comment by cig0** [comment]
I see, just like a sed 👍 

I confirm that after adding the missing slash all is well now @ktsaou, feel free to go ahead an merge the change.
Do you have an estimate of when the next pre-built binary for GNU+Linux will be released?

Thanks!

**Comment by ktsaou** [comment]
> Do you have an estimate of when the next pre-built binary for GNU+Linux will be released?

tonight! - every night!

**Comment by ktsaou** [comment]
merged it.


> just like a sed :)

btw, yes like `sed`, but without the fork - i.e. a lot faster!
