### ISSUE TITLE
Python plugin to be waiting for custom service

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3214]
Hello,
I have Redis, that I am running not from systemD, but from Circus.
When server is booting, Netdata runs much faster, than Redis - and  Netdata`s redis-plugin fails to start.

For now I created Netdata`s drop-in (ExecStartPre) than wait 60 sec to Redis-port has been binded, and than starts Netdata - but it is not the best solution.

Is there any options in plugin conf file to wait some additional time till Redis starts.

**Comment by ktsaou** [comment]
yes, use this option to tell netdata to never give up checking: https://github.com/firehol/netdata/blob/c6caec3eb9c43120efc19f1137031c1ae299b2d7/conf.d/python.d/redis.conf#L40
