### ISSUE TITLE
any way to specify static version with kickstart-static64.sh

### ISSUE THREAD

**Issue by fabMrc** [firehol/netdata#3220]
Currently i use netdata 1.8.0 and when I try to install a new netdata agent with my ansible role it run failed because --accept option is now deprecated

curl -Ss https://my-netdata.io/kickstart-static64.sh -o /tmp/kickstart-static64.sh && chmod +x /tmp/kickstart-static64.sh  && sh /tmp/kickstart-static64.sh  --dont-wait --non-interactive --accept

So is a way to fix version of kickstart-static64.sh and specify netdata static version to avoid upgrade incompatibility ?

**Comment by ktsaou** [comment]
Hi,

`--accept` was never a valid option. The new kickstart-static64.sh now checks for invalid parameters and refuses to run if it finds any.

`--accept` is an option of the underlying `.run` makeself executable, that is enabled when `--dont-wait` or `--non-interactive` is given to kickstart-static64.sh.

Also `--dont-wait` and `--non-interactive` [is the same option](https://github.com/firehol/netdata/blob/36c58af5c4c85f676c78e273bbf07a560084ff85/kickstart-static64.sh#L219) with different names.

Anyway, I am adding `--accept` as a valid option, another name for `--dont-wait` and `--non-interactive`.

**Comment by ktsaou** [comment]
merged it.
Please retry - it should work now.

**Comment by promethe42** [comment]
AFAIK it doesn't answer the original question, which is:

> So is a way to **fix version** of kickstart-static64.sh and **specify netdata static version** to avoid upgrade incompatibility ?
