### ISSUE TITLE
Netdata tries to execute /usr/sbin/ipsec via sudo

### ISSUE THREAD

**Issue by svengo** [firehol/netdata#3221]
I'm using netdata 1.9.0-113-g2cff2b7_rolling (with daily updates). I received security warnings today and yesterday:

````
Jan  4 06:25:39 arnor sudo:  netdata : user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/sbin/ipsec whack --status
Jan  4 06:25:39 arnor sudo:  netdata : user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/sbin/ipsec whack --trafficstatus
````

netdata is not in sudoers as this is not documented. Btw, ``ipsec whack`` do not work:

````
sven@arnor:~$ sudo /usr/sbin/ipsec whack --status
/usr/sbin/ipsec: unknown IPsec command `whack' (`ipsec --help' for list)
sven@arnor:~$ sudo /usr/sbin/ipsec whack --trafficstatus
/usr/sbin/ipsec: unknown IPsec command `whack' (`ipsec --help' for list)
sven@arnor:~$ ipsec --version
Linux strongSwan U5.3.5/K4.4.0-104-generic
````

The issue is similar to #2158.

**Comment by ktsaou** [comment]
Hi,

this is done by the new libreswan plugin. I didn't know strongSwan installs the same command (`ipsec`). I'll add a check for it.

**Comment by ktsaou** [comment]
in PR #3223

**Comment by ktsaou** [comment]
btw, how do you get interface statistics with strongswan?

**Comment by ktsaou** [comment]
merged it. Could you please update and retry? Now it checks if `ipsec` is libreswan and attempts to run it only when it is.

**Comment by l2isbad** [comment]
@ktsaou 
i believe netdata still run `ipsec --version` with `sudo` 
so

> I received security warnings today and yesterday

is not fixed

**Comment by ktsaou** [comment]
> i believe netdata still run ipsec --version with sudo

no. The PR just merged does not use sudo for getting the version.

> i have no active connections but looks like it is
> ipsec status|statusall [<connectionname>]

I would need a few examples of running tunnels to make a plugin for it.

**Comment by Thermi** [comment]
Use [VICI](https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/vici/README.md) ([strongSwan plugin](https://wiki.strongswan.org/projects/strongswan/wiki/Vici)). It's much more elegant (and infinitely better than screen scraping).

**Comment by ktsaou** [comment]
vici seems nice indeed!
I guess this is strongswan only. So, I suggest to open a new issue about it and discuss with @l2isbad how this could be implemented (I see there is a python library for it).

**Comment by Thermi** [comment]
I'm not actually interested in this software. This issue just came up when I searched for libreswan stuff on twitter.

**Comment by lets00** [comment]
Strongswan also uses ipsec. I asked on twitter (@netdata) if libreswan plugin could also be used to monitoring strongswan statistcs and someone say no. Further, I will test this solution with strongswan because is plausible that this script works in it too.

**Comment by Thermi** [comment]
No, it's not plausible, because the two projects share exactly 0% of their code base.
