### ISSUE TITLE
Can I add alarm panel to custom dashboard?

### ISSUE THREAD

**Issue by talkyy** [firehol/netdata#3225]
Hi,
I want to add netdata's all alarm in default dashboard (the image below) to my custom dashboard. The default dashboard so nice, but sometime I want to use my custom dashboard and I also want to view all alarm in my custom dashboard. Can I do it?

![image](https://user-images.githubusercontent.com/26269505/34567659-b9bcd2d2-f195-11e7-9639-388fc1664f18.png)

**Comment by talkyy** [comment]
Hi, I can see that all alarms and alarm log are in `localhost:19999/api/v1/alarms?all` and `localhost:19999/api/v1/alarm_log`. I need to make a alarm panel like default dashboard for my custom dashboard. Could you show me the way to add this to my custom dashboard?
Thank you for your time!

**Comment by ktsaou** [comment]
hi,

before loading `dashboard.js`, set:

```js
var netdataShowAlarms = true
```

The above will enable web notifications on your custom dashboard.

You can also set the following to show web notifications just for a few alarm roles:

```sh
var netdataAlarmsRecipients = [ 'role1', 'role2', ... ];
```

Unfortunately, to re-create the modal, you will have to do it yourself. The netdata code that does this is the following: https://github.com/firehol/netdata/blob/fa78a22f6fd86adf2caf0b018736c588bc33786e/web/index.html#L2122-L2767

**Comment by ktsaou** [comment]
I am closing this, but if there is something pending, post here and I'll reopen it.
