### ISSUE TITLE
[Bug] Netdata StatsD settings

### ISSUE THREAD

**Issue by jeremyjpj0916** [firehol/netdata#3229]
Following comments here: https://github.com/firehol/netdata/wiki/statsd

I should be able to do this:

![bugnetdata](https://user-images.githubusercontent.com/31913027/34588121-62626d60-f179-11e7-81d8-824a4de38a4b.png)

Where I can have kong.*.request.status.total metrics not exposed as a private chart via the !(not) symbol. 

But when I load up my netdata I see it, I have tried moving it around and such in the list to the front and before/after the kong.*.request.status.200 tag but nothing seems to work. I always end up seeing:

![netdataviewbug](https://user-images.githubusercontent.com/31913027/34588218-cf4e8a58-f179-11e7-85cc-49922e1e4518.png)

Do the exclusion commands not currently work?

-Jeremy

**Comment by ktsaou** [comment]
ok. I am closing this, but you can still post.

**Comment by jeremyjpj0916** [comment]
I think my problem was I had declared these metrics as an app called kong, and I needed to create my regex in that config portion rather than the main [statsd] global config section. I also have noticed that if I disable private charts, then the /api/v1/allmetrics?format=prometheus_all_hosts now lacks the specific statsD metrics that I was charting in the dashboard(I still expected the rest API to have the data though), I assume I still have to enable private charts, set soft limit to 0 if I want no specific charting on Netdata but still want to expose them to the Netdata REST API for Prometheus. then set the hard limit to something crazy like 100000000 so all the StatsD data will be exposed to Prometheus.

**Comment by ktsaou** [comment]
hm... netdata exposes to prometheus only charts. So, either set their memory history too low (5 or 10 seconds is enough). If you use `as-collected` in prometheus you can also set the statsd chart memory to `none`.

**Comment by jeremyjpj0916** [comment]
@ktsaou I had the metrics separated into my own [app] config, I should have defined my regex there. One thing that I am still struggling with is how to expose statsD metrics on the /api/v1/allmetrics?format=prometheus_all_hosts endpoint but also not expose those same statsD charts in my Netdata dashboard(I only want to ship those off to prometheus/grafana). It seems if I disable private charts I also lose exposing statsD graph info on the REST endpoint?

**Comment by jeremyjpj0916** [comment]
I even had another idea to try to hide displaying the graphs on the UI so I could just expose the data to Prometheus by using !* on the slave but then that hides it all in UI and in the REST API, I just want to not display it in UI but keep the data flowing with the REST API for external use:

![anotherattempt](https://user-images.githubusercontent.com/31913027/35781997-7ad1ff6a-09bf-11e8-818e-354ee38b34ba.png)

**Comment by ktsaou** [comment]
hm... you are right, this cannot be done currently.
What I can do, is add an option to hide these charts from the dashboard, but expose them to backends.

However, this means these charts will be accessible by the API if someone knows their names.

Would this help?

**Comment by jeremyjpj0916** [comment]
@ktsaou 

Right, that is exactly what I need 👍  ! If they are not exposed then the main dashboard will not have browser lag that comes with all these chats being made out which is my goal.

It would definitely help my use case! Let me know if/when you get the chance to implement a field like that with some code magic.

Thanks,
Jeremy

**Comment by jeremyjpj0916** [comment]
@ktsaou had any chance to look into this? Would it be simpler to point me what file and line in source I can just comment out to prevent the display of Charts in the UI(hence making the potential for web browser page load freezes due to too many display charts a non-issue?)

Thanks,
-Jeremy

**Comment by ktsaou** [comment]
In PR #3467

**Comment by ktsaou** [comment]
merged it

**Comment by jeremyjpj0916** [comment]
Thank you sir! Very much appreciated, now I won't have to worry about scale of my private charts. I suppose eventually the REST API could expose too many values in a given time potentially to make scraping a hard task with a huge payload but not sure. I was thinking about if say no statsD values are coming by so the rest api exposure of the statsD value on a given chart goes to 0, if you have the setting to delete charts inactive after __ amount of time then the REST API won't be exposing that value of 0 for long right? That way the data exposed on Netdata endpoint only stays relevant while traffic is passing through to the chart. Won't have a bunch of dead exposed statsD values of 0's since the auto delete will catch them after a certain amount of time.

**Comment by ktsaou** [comment]
hm...

I had a similar problem with you: one application I have generates about 700.000 unique statsd metrics per week. I tried to understand what to do with them and how to treat such a case.

I concluded that the best way is to use statsd synthetic charts (actually this app was the reason I built synthetic charts in netdata).  I disabled private charts completely. In private charts I cherry pick the metrics I am interested, even with patterns (in synthetic charts you can say: add in this chart, as dimensions, all statsd metrics matching this pattern - synthetic charts can also dynamically name the dimensions the way you like it, using dictionaries).

So, although it requires another step, instead of a bunch of metrics, I now have totally meaningful netdata dashboards. I grouped the statsd metrics into functions (applications in synthetic charts terminology), with properly formatted charts and reasonably named dimensions.

This specific netdata is configured with memory mode `map` and 30 days of data (several GB - you need SSD disks for this), so I have very detailed data (per second) and quite long history.

Have you considered something like that?

The way you use netdata now, you don't actually have any benefits over e.g. [brubeck](https://github.com/github/brubeck) - I would say the opposite: you will hit many limitations by using netdata just as a pass-through for archiving raw statsd metrics to a time-series db. netdata can do it, but brubeck will be a lot more efficient and simpler in this.

**Comment by jeremyjpj0916** [comment]
I will look into the synthetic chart option as well for room for potential chart minimization. As it stands now I get about 7 private charts generated for every API Proxy created. So if I have say realistically 4,000-5,000 API proxies then that is 35,000 charts so not as extreme as your 700,000 metrics/charts produced in a week :) .

But I am still confused on how this flag will work in a master/slave relationship from my prior question, does the flag getting set on the slave(netdata.conf) impact what the master dashboard will display when I select the slave from the drop down menu for viewing since its a mirror of the node? Or do I have to set it at the master netdata.conf(I don't think I do but I wanted to verify with the master (you 💯) ).

**Comment by ktsaou** [comment]
The flag is propagated with the charts. So, for the master these are standard netdata charts that have the `hidden` flag set.

I think however that you also expect netdata to self cleanup old statsd charts. It won't. netdata self cleanups only when a chart is marked as `obsolete` and statsd charts are currently never marked `obsolete`. So, I think you also need another statsd option: `cleanup old private chart = SECONDS`.

Right?

**Comment by jeremyjpj0916** [comment]
> So, I think you also need another statsd option: cleanup old private chart = SECONDS.

Does this exist now or are you saying this would be something you could add to make your statsD implementation more robust?

Also back on the original question, I think the first part answers my question. So flag is propagated with the charts, so when a slave has that flag set for statsD section, and it streams data to the master which a stream consists of the data needed and chart properties (hidden flag being one of those newer properties you just added). I use the master UI drop down and select a given slave netdata for viewing, that slave with the new feature statsD hidden private charts will = yes so now when viewing it from master it will not display it. 

I think we are close to on the same train of thought now :) , I am just slow on the pickup haha.

**Comment by ktsaou** [comment]
> . If it does not exist I think this feature would certainly have huge value because then you would not be exposing "dead" metrics on the REST API endpoint for statsD metrics that are not actively getting any intake into netdata.

hm... statsd does not work like that. Once a statsd metric is collected and assigned to one or more charts, it is always updated, even if nothing is collected. If it did not, you would have gaps on the charts when statsd did not receive a metric within the update frequency of a chart.

Also, when netdata marks a chart as obsolete, it will eventually delete the data. So, you will loose data. Generally, deleting metrics is not a nice idea. We do it, but I am always trying to avoid it...

> slave with the new feature statsD hidden private charts will = yes, so now when viewing the slave from master it will not display any of the hidden charts.

yes, both slave and master have to be updated with this feature.

**Comment by jeremyjpj0916** [comment]
Confirmed with the flag set on my slaves, viewing their data from the master does not display their statsD private charts, yet when I go to the master's rest API and hit the /api/v1/allmetrics?format=prometheus_all_hosts endpoint I do see my statsD metrics still being exposed for backend to scrape. This feature will enable statsD users of netdata to house many charts without worrying about UI browser display problems. ktsaou delivering quality work :+1:  . This topic can be closed now as the feature is there
