### ISSUE TITLE
Scaling/Logarithmic Graphs, but in sync with other charts/graphs?

### ISSUE THREAD

**Issue by nzurku** [firehol/netdata#3237]
We're looking for the ability to have 4-8 graphs (BGP internet links) that are scaling based on incoming interface speed, but have all 4-8 of the graphs scale at the same speed.

We have issues in our NOC with scaling graphs that from a distance you can't tell the difference between 10mbps and 1gbps. The solution is to have an upper bound of 4gbps so the graphs are identical across the NOC TVs. This means that during low traffic, the graphs are too low to read.

That said, during peak hours or DDoS attacks, the graphs often max out so we'd like them to all scale at the same time so our NOC techs can easily see what graphs are way out of wack.

Anyone have a method to scale all the graphs in sync? Having them always be 4000mbps, and then jump to 10gbps if one of them goes that high would be awesome.

**Comment by ktsaou** [comment]
Hi,

On custom dashboards you have the following options:

1. you can set on the charts `data-common-max="NAME"`. Use the same `NAME` on the charts you want to share y-range. With that setting, all charts will get the same range, but still if one goes to 4gbps, all of them will do and you will miss the detail.

2. I added it in PR #3283 a new dygraph theme called `logscale`. Use this in combination to be above, to have logarithmic charts that share their y-range.

**Comment by ktsaou** [comment]
merged it.
