### ISSUE TITLE
Netdatas behind Proxy: Should we worry about DDOS? Need help configuring multi-netdata streaming setup

### ISSUE THREAD

**Issue by Kramerican** [firehol/netdata#3240]
## DDOS theoretically possible

Right now I have 7 hosts running netdata, in default configuration IP restricted to a single machine running Nginx in proxy mode.

The Nginx proxy is not password protected, as I'd like to serve certain stats to my clients using badges - some auth mechanism might be possible, but I haven't figured out how that should work yet.

I am worried about the obvious attack which would be that you could enumerate the hosts and then start DOS'ing them through the central node, as all traffic just gets proxied onwards, and in this fashion effectively and quite simply impact my entire infrastructure.

**This is obviously bad.**

The server running the Nginx proxy is a dedicated server just for my toolchain, so it would be perfect to switch to the setup where my hosts just stream to the central server in realtime - thereby saving memory on hosts - and also isolating them from any potential DOS attacks.

## Mitigation by using a central Netdata

I have spent the day scouring the docs and looking at the config files, but it is all rather unclear to me. What I'd like to accomplish is:

1. Just stream data to a central Netdata. IP restricted so no other IP's can request this data.

2. Have the central Netdata keep 24h worth of stats, and optimize for memory use. Potential resulting high disk I/O is not an issue on this server

**I am missing some clearer docs - information about this is spread across many wiki pages**

## My plan - so far

Before proceeding, I would like to confirm with you guys, if possible, that this is the right approach:

1. Create an uuid for my hosts (my API key) using `uuidgen` 
2. Edit `/opt/netdata/etc/netdata/stream.conf` on all my hosts (slaves) where

```
 [stream]
 enabled = yes
 destination = tcp:111.111.111.1 (my Master node IP)
```

3. Restart netdata on my hosts? `killall netdata` and then run netdata again?

- Is that it, for these steps? Will the slaves now stop collecting data locally and just stream?

4. Edit `/opt/netdata/etc/netdata/stream.conf` now on my central node (Master) were

```
[uuid]
 enabled = yes
 default history = 86400 (I want 24h of data accessible for all my slaves)
```
 
5. I guess I also need a restart here on my master

- Port 19999 (default) is already open on slaves and master. Slaves will only accept incoming connections from Master IP.

6. Reconfigure my Nginx proxy so it just proxies to the local Netdata, and not the remotes anymore. I would attempt to use unix socket here for speed

7. Do memory optimization, either using KSM or allow it to use disk. Suggestions? :)

**Is it this simple?**

Thank you for any input you might have

**Comment by ktsaou** [comment]
Hi,

## DDoS

Any server exposed on the internet is subject to DDoS.

By default netdata runs with the idle scheduling policy. This means it gets CPU, only when the system has idle to spare. Also netdata gives itself an OOM score 1000. This means netdata will be the first process to be killed if the server starves for memory.

netdata also supports a single threaded web server (check the `[web]` section in netdata.conf). If you use this, no matter what the netdata web server does, just one core will be used.

Keep in mind, the netdata dashboard and API are read-only. Check [netdata security](https://github.com/firehol/netdata/wiki/netdata-security) for more info.

Obviously, I don't suggest poeple to run netdata open on the internet. If you need to expose your production netdata to the internet, isolating it to a central netdata is a good strategy. So, any DDoS will hit the master netdata, not your production systems.

If you only need to expose badges, you can create a simple cron job to dump them to static files once every a few seconds and serve the static files via another web server.

Another good strategy for DDoS protection is to use traffic QoS. Applying a bandiwdth limit will save your servers (this is not about netdata - [you should use QoS on all internet facing servers](https://github.com/firehol/netdata/wiki/You-should-install-QoS-on-all-your-servers)).

## Central netdata

The configuration is quite simple.

Assuming you will use API KEY `11111111-2222-3333-4444-555555555555`:

#### stream.conf on central netdata

```
[11111111-2222-3333-4444-555555555555]
    enabled = yes
    allow from = 10.* 192.168.* 172.16.*
```

`allow from` is used to limit the IPs the master netdata will accept streaming from.

#### stream.conf on slave netdata

```
[stream]
    enabled = yes
    destination = tcp:[111.111.111.1]:19999
    api key = 11111111-2222-3333-4444-555555555555
```

Using the above, your netdata slaves will be autonomous systems with replication. They will serve a dashboard themselves, if you need it.

- If you want to make them headless collectors, then set `[web].mode = none` in netdata.conf. So, the slaves will not be listening on any web port.

- if you don't need to run alarms on them, then set `[global].memory mode = none` in netdata.conf - this will also disable the database on them (they will run with just 5MB of RAM).

> Slaves will only accept incoming connections from Master IP.

netdata masters do not connect to netdata slaves. The slaves connect to their master, pushing their metrics.

> Do memory optimization, either using KSM or allow it to use disk. Suggestions? :)

`[global].memory mode = map` and KSM are mutually exclusive. Pick either.

> Is it this simple?

yeap.

**Comment by Kramerican** [comment]
Hello :)

**DDOS**

Wonderful idea using cronjobs! I already run [frequent-cron](https://github.com/homer6/frequent-cron) on my server so I can leverage that to generate badges. It will take a bit of engineering, but a great way to isolate Netdata!

**Configuration**

Thank you _**very**_ much for your clarification and insights! :+1:

**Comment by Ferroin** [comment]
Slightly OT, but strictly speaking, this:

> By default netdata runs with the idle scheduling policy. This means it gets CPU, only when the system has idle to spare. 

Is not entirely accurate.  The SCHED_IDLE CPU class and IOPRIO_CLASS_IDLE I/O class are not actually true idle schedulers on Linux, they give the process in question insanely low priority (kind of like setting the OOM score to 1000 gives netdata very high OOM killer priority), but they can and will still preempt other tasks if the CPU or disk is overcommitted (just like how setting the OOM score high does not guarantee that netdata will be killed, it just makes it statistically certain in most cases).  While not usually significant in most cases, this distinction gets very important when talking about things like DoS attacks (something running under a true idle scheduler can't reliably be used for a DoS attack, but something running under SCHED_IDLE can).

**Comment by Kramerican** [comment]
I have now started the config, and a sticky point has come up: How to allow slaves to stream data to my master, but at the same time have my master web interface protected?

My initial thought was that doing this in my master config

```
[web]
 bind to = unix:/tmp/netdata.sock
```
Would just affect the web interface, but that Netdata would still listen on port 19999 for data from slaves. It seems it does not - `netstat -tapn` confirms that Netdata is indeed no longer listening on port 19999

Ok, fair enough. My next thought was then, OK I need Netdata to listen on port 19999 I'll just hav to IP restrict it to my slaves and my Nginx server ... Changing it back to something like:

```
[web]
 allow connections from = MY_SERVER_IP
```

or 

```
[web]
 allow connections from = 127.0.0.1
```

Does not work however, I get in the NginX error log:

> 2018/01/08 18:23:46 [error] 19852#19852: *557 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 90.185.74.180, server: XXX.XXX.io, request: "GET /netdata/ HTTP/1.1", upstream: "http://127.0.0.1:19999/", host: "XXX.XXX.io"

This does not look like the SELinux error seen in your docs [Running-behind-nginx](https://github.com/firehol/netdata/wiki/Running-behind-nginx)

What is the correct way to:

1. Allow slaves to stream to master
2. Expose the web interface of master, in a protected way (I was/am using basicauth + SSL)

**Comment by ktsaou** [comment]
Use 

```
[web]
 allow connections from = localhost SLAVE1 SLAVE2 SLAVE3
```

`localhost` matches `127.0.0.1`, `::1` and unix domain sockets.

So, the port 19999 will be there and anyone will be able to connect, but netdata will immediately disconnect all except localhost and the slaves defined.

**Comment by ktsaou** [comment]
I am closing this, but if there is something pending, post here and I'll reopen it.
