### ISSUE TITLE
Question: (MemTotal - Memory Used) vs. Memory Available.

### ISSUE THREAD

**Issue by johnnyb2good** [firehol/netdata#3241]
Referring to the previous Q&A in issue #1034 ("Help required to match data to of system.ram to free -m"):

Netdata provides system RAM metrics of Free, Used, Cached and Buffers.
Per closed issue #1034, Used is calculated as:

unsigned long long Used = MemTotal - MemFree - Cached - Buffers;

I have been using this "Used" metric as a percentage of MemTotal (calc'd through Netdata provided metrics as the sum of free, used, cached and buffers) to track how close the system is to being out of memory (OOM) when it approaches and hits 100% Used.

However, while (MemTotal - Used) does seem to be close to the OS provided metric of MemAvailable most of the time based on observation, they do report different results.

From the kernel commit comment at [https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773), MemAvailable does a calculation that's a little more involved that what (MemTotal - Used) amounts to, and that calculation may change in the future.

For those of us who would like to track available system memory closely and accurately, wouldn't it be good to provide the OS calculated MemAvailable metric as well since that seems to differ by a least a small extent to the estimate of (MemTotal - Used)?

Or is there a better way to look at this than I am doing?  Or maybe I'm missing something?

Thanks!

John

**Comment by ktsaou** [comment]
Nice finding. Somehow I missed that metric.

Check PR #3242 

I have chosen to exclude ZFS RAM from the alarm (ie. consider ZFS ARC memory as available). I am not sure though.

**Comment by johnnyb2good** [comment]
That's great, thanks for the update!  I'm good with excluding ZFS RAM from the alarm -- doesn't affect me either way.   Feel free to change as you see fit.  Thanks for a great product!

I don't really understand the alarm math, but haven't looked at it much either.  If you are trying to take a measure of available ram left as a percent--not counting ZFS where memory allocated to ZFS is accounted for in $used_ram_to_ignore--I would think it would look more like:

($avail + $used_ram_to_ignore) * 100 / ($system.ram.used + $system.ram.free + $system.ram.cached + $system.ram.buffers)

The denominator here should work out to MemTotal from the OS and then you're calculating MemAvailable (+ZFS RAM if any) as a percent of MemTotal.

In any case, I haven't done reading on the alarm variables in detail and could be missing a simple definition, so feel free to close the ticket.  I can adjust the alarm as needed for myself.

Thanks again!

John

**Comment by ktsaou** [comment]
yes, you are right. I forgot to fix the denominator during copy-paste. fixing it now.

**Comment by ktsaou** [comment]
fixed it

**Comment by ktsaou** [comment]
merged it.
