### ISSUE TITLE
Raspbian Jesse python-ipaddress

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3243]
When trying to configure monitoring for isc dhcp and check the logs, I keep getting the error:
2018-01-07 13:28:27: python.d ERROR: isc_dhcpd: job_name: 'python-ipaddress' module is needed

When trying to do apt-get install python-ipaddress I am getting "Unable to locate package python-ipaddress.

**Comment by l2isbad** [comment]
https://launchpad.net/ubuntu/bionic/+package/python-ipaddress

**Comment by ktsaou** [comment]
cleaning up. I am closing this, but you can still post.
