### ISSUE TITLE
no chart for external mariadb 

### ISSUE THREAD

**Issue by kepeta** [firehol/netdata#325]
netdata installed on /root/bin/netdata
mysql.conf 
> mysql_cmds[DB1]="/usr/bin/mysql"
mysql_opts[DB1]="-h 10.10.10.10 -unetdata -ppassword"

i got this error, please help me to solve this out
> 16-04-27 12:16:30: ERROR: netdata: PLUGINSD: '/root/bin/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' is requesting a BEGIN on chart 'mysql_DB1.tmp', which does not exist. Disabling it.

here's the screenshot
![mariadb](https://cloud.githubusercontent.com/assets/18693403/14842659/b69d6020-0c73-11e6-8f14-27d38feb5395.JPG)
 
here's the output for /root/bin/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin debug 10 mysql
> charts.d: started from '/root/bin/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 10 mysql
charts.d: configuration file '/etc/netdata/charts.d.conf' not found. Using defaults.
charts.d: 'airsearches' is enabled.
charts.d: 'apache' is enabled.
charts.d: 'ap' is enabled.
charts.d: 'cpu_apps' is enabled.
charts.d: 'cpufreq' is enabled.
charts.d: 'crsproxy' is enabled.
charts.d: 'example' is enabled.
charts.d: 'load_average' is enabled.
charts.d: 'mem_apps' is enabled.
charts.d: 'mysql' is enabled.
charts.d: 'nginx' is enabled.
charts.d: 'nut' is enabled.
charts.d: 'opensips' is enabled.
charts.d: 'phpfpm' is enabled.
charts.d: 'postfix' is enabled.
charts.d: 'sensors' is enabled.
charts.d: 'squid' is enabled.
charts.d: 'tomcat' is enabled.
charts.d: enabled charts:  airsearches apache ap cpu_apps cpufreq crsproxy example load_average mem_apps mysql nginx nut opensips phpfpm postfix sensors squid tomcat
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/airsearches.chart.sh'
charts.d: airsearches: configuration file '/etc/netdata/airsearches.conf' not found. Using defaults.
charts.d: airsearches: not configured. Please set airsearches_url='url' in /etc/netdata/airsearches.conf
charts.d: chart 'airsearches' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/apache.chart.sh'
charts.d: apache: configuration file '/etc/netdata/apache.conf' not found. Using defaults.
apache: Invalid response or missing keys from apache server: <!DOCTYPE html> <html lang="en"> <head> <title>404 Page Not Found</title> <style type="text/css">  selection{ background-color  #E13300; color  white; }  moz-selection{ background-color  #E13300; color  white; }  webkit-selection{ background-color  #E13300; color  white; } body {   background-color  #fff;         margin  40px;   font  13px/20px normal Helvetica, Arial, sans-serif;    color  #4F5155; } a {   color  #003399;         background-color  transparent;  font-weight  normal; } h1 {     color  #444;    background-color  transparent;  border-bottom  1px solid #D0D0D0;       font-size  19px;       font-weight  normal;     margin  0 0 14px 0;     padding  14px 15px 10px 15px; } code {  font-family  Consolas, Monaco, Courier New, Courier, monospace;         font-size  12px;        background-color  #f9f9f9;      border  1px solid #D0D0D0;      color  #002166;         display  block;         margin  14px 0 14px 0;  padding  12px 10px 12px 10px; } #container {    margin  10px;   border  1px solid #D0D0D0;      -webkit-box-shadow  0 0 8px #D0D0D0; } p {      margin  12px 15px 12px 15px; } </style> </head> <body>  <div id="container">            <h1>404 Page Not Found</h1>             <p>The page you requested was not found.</p>    </div> </body> </html>
apache: cannot find stub_status on URL 'http://127.0.0.1:80/server-status?auto'. Please set apache_url='http://apache.server:80/server-status?auto' in /etc/netdata/apache.conf
charts.d: chart 'apache' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh'
charts.d: ap: configuration file '/etc/netdata/ap.conf' not found. Using defaults.
/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh: line 36: iw: command not found
charts.d: chart 'ap' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/cpu_apps.chart.sh'
charts.d: cpu_apps: configuration file '/etc/netdata/cpu_apps.conf' not found. Using defaults.
charts.d: cpu_apps: Please set cpu_apps_apps='command1 command2 ...' in /etc/netdata/cpu_apps_apps.conf
charts.d: chart 'cpu_apps' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/cpufreq.chart.sh'
charts.d: cpufreq: configuration file '/etc/netdata/cpufreq.conf' not found. Using defaults.
charts.d: chart 'cpufreq' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/crsproxy.chart.sh'
charts.d: crsproxy: configuration file '/etc/netdata/crsproxy.conf' not found. Using defaults.
charts.d: crsproxy: not configured. Please set crsproxy_url='url' in /etc/netdata/crsproxy.conf
charts.d: chart 'crsproxy' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/example.chart.sh'
charts.d: example: configuration file '/etc/netdata/example.conf' not found. Using defaults.
charts.d: 'example' activated
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/load_average.chart.sh'
charts.d: load_average: configuration file '/etc/netdata/load_average.conf' not found. Using defaults.
charts.d: chart 'load_average' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/mem_apps.chart.sh'
charts.d: mem_apps: configuration file '/etc/netdata/mem_apps.conf' not found. Using defaults.
charts.d: mem_apps: not configured. Please set mem_apps_apps='command1 command2 ...' in /etc/netdata/mem_apps_apps.conf
charts.d: chart 'mem_apps' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/mysql.chart.sh'
charts.d: loading chart options: '/etc/netdata/mysql.conf'
charts.d: 'mysql' activated
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/nginx.chart.sh'
charts.d: nginx: configuration file '/etc/netdata/nginx.conf' not found. Using defaults.
nginx: Invalid response from nginx server: <!DOCTYPE html> <html lang="en"> <head> <title>404 Page Not Found</title> <style type="text/css"> ::selection{ background-color: #E13300; color: white; } ::moz-selection{ background-color: #E13300; color: white; } ::webkit-selection{ background-color: #E13300; color: white; } body { background-color: #fff; margin: 40px; font: 13px/20px normal Helvetica, Arial, sans-serif; color: #4F5155; } a { color: #003399; background-color: transparent; font-weight: normal; } h1 { color: #444; background-color: transparent; border-bottom: 1px solid #D0D0D0; font-size: 19px; font-weight: normal; margin: 0 0 14px 0; padding: 14px 15px 10px 15px; } code { font-family: Consolas, Monaco, Courier New, Courier, monospace; font-size: 12px; background-color: #f9f9f9; border: 1px solid #D0D0D0; color: #002166; display: block; margin: 14px 0 14px 0; padding: 12px 10px 12px 10px; } #container { margin: 10px; border: 1px solid #D0D0D0; -webkit-box-shadow: 0 0 8px #D0D0D0; } p { margin: 12px 15px 12px 15px; } </style> </head> <body> <div id="container"> <h1>404 Page Not Found</h1> <p>The page you requested was not found.</p> </div> </body> </html>
nginx: cannot find stub_status on URL 'http://127.0.0.1:80/stub_status'. Please set nginx_url='http://nginx.server/stub_status' in /etc/netdata/nginx.conf
charts.d: chart 'nginx' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/nut.chart.sh'
charts.d: nut: configuration file '/etc/netdata/nut.conf' not found. Using defaults.
which: no upsc in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin:/usr/sbin:/usr/local/sbin)
charts.d: ERROR: Command 'upsc' is not found in the system path.
charts.d: chart 'nut' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/opensips.chart.sh'
charts.d: opensips: configuration file '/etc/netdata/opensips.conf' not found. Using defaults.
which: no opensipsctl in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin:/usr/sbin:/usr/local/sbin)
charts.d: ERROR: Command 'opensipsctl' is not found in the system path.
charts.d: chart 'opensips' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/phpfpm.chart.sh'
charts.d: phpfpm: configuration file '/etc/netdata/phpfpm.conf' not found. Using defaults.
charts.d: 'phpfpm' activated
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/postfix.chart.sh'
charts.d: postfix: configuration file '/etc/netdata/postfix.conf' not found. Using defaults.
charts.d: 'postfix' activated
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/sensors.chart.sh'
charts.d: sensors: configuration file '/etc/netdata/sensors.conf' not found. Using defaults.
charts.d: sensors: no sensors found in '/sys/devices'.
charts.d: chart 'sensors' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/squid.chart.sh'
charts.d: squid: configuration file '/etc/netdata/squid.conf' not found. Using defaults.
which: no squidclient in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin:/usr/sbin:/usr/local/sbin)
charts.d: ERROR: Command 'squidclient' is not found in the system path.
charts.d: chart 'squid' check() function reports failure.
charts.d: loading chart: '/root/bin/netdata/usr/libexec/netdata/plugins.d/../charts.d/tomcat.chart.sh'
charts.d: tomcat: configuration file '/etc/netdata/tomcat.conf' not found. Using defaults.
which: no xmlstarlet in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin:/usr/sbin:/usr/local/sbin)
charts.d: ERROR: Command 'xmlstarlet' is not found in the system path.
charts.d: chart 'tomcat' check() function reports failure.
charts.d: activated charts:  example mysql phpfpm postfix
charts.d: requested to run only for: 'mysql'
charts.d: activated charts: mysql
charts.d: Calling 'mysql_create()'...
CHART mysql_db1.net '' "mysql Bandwidth" "kilobits/s" bandwidth mysql.net area 60001 10
DIMENSION Bytes_received in incremental 8 1024
DIMENSION Bytes_sent out incremental -8 1024

CHART mysql_db1.queries '' "mysql Queries" "queries/s" queries mysql.queries line 60002 10
DIMENSION Queries queries incremental 1 1
DIMENSION Questions questions incremental 1 1
DIMENSION Slow_queries slow_queries incremental -1 1

CHART mysql_db1.handlers '' "mysql Handlers" "handlers/s" handlers mysql.handlers line 60003 10
DIMENSION Handler_commit commit incremental 1 1
DIMENSION Handler_delete delete incremental 1 1
DIMENSION Handler_prepare prepare incremental 1 1
DIMENSION Handler_read_first read_first incremental 1 1
DIMENSION Handler_read_key read_key incremental 1 1
DIMENSION Handler_read_next read_next incremental 1 1
DIMENSION Handler_read_prev read_prev incremental 1 1
DIMENSION Handler_read_rnd read_rnd incremental 1 1
DIMENSION Handler_read_rnd_next read_rnd_next incremental 1 1
DIMENSION Handler_rollback rollback incremental 1 1
DIMENSION Handler_savepoint savepoint incremental 1 1
DIMENSION Handler_savepoint_rollback savepoint_rollback incremental 1 1
DIMENSION Handler_update update incremental 1 1
DIMENSION Handler_write write incremental 1 1

CHART mysql_db1.table_locks '' "mysql Tables Locks" "locks/s" locks mysql.table_locks line 60004 10
DIMENSION Table_locks_immediate immediate incremental 1 1
DIMENSION Table_locks_waited waited incremental -1 1

CHART mysql_db1.join_issues '' "mysql Select Join Issues" "joins/s" issues mysql.join_issues line 60005 10
DIMENSION Select_full_join full_join incremental 1 1
DIMENSION Select_full_range_join full_range_join incremental 1 1
DIMENSION Select_range range incremental 1 1
DIMENSION Select_range_check range_check incremental 1 1
DIMENSION Select_scan scan incremental 1 1

CHART mysql_db1.sort_issues '' "mysql Sort Issues" "issues/s" issues mysql.sort.issues line 60006 10
DIMENSION Sort_merge_passes merge_passes incremental 1 1
DIMENSION Sort_range range incremental 1 1
DIMENSION Sort_scan scan incremental 1 1

CHART mysql_db1.tmp '' "mysql Tmp Operations" "counter" temporaries mysql.tmp line 60007 10
DIMENSION Created_tmp_disk_tables disk_tables incremental 1 1
DIMENSION Created_tmp_files files incremental 1 1
DIMENSION Created_tmp_tables tables incremental 1 1

CHART mysql_db1.connections '' "mysql Connections" "connections/s" connections mysql.connections line 60008 10
DIMENSION Connections all incremental 1 1
DIMENSION Aborted_connects aborded incremental 1 1

CHART mysql_db1.binlog_cache '' "mysql Binlog Cache" "transactions/s" binlog mysql.binlog_cache line 60009 10
DIMENSION Binlog_cache_disk_use disk incremental 1 1
DIMENSION Binlog_cache_use all incremental 1 1

CHART mysql_db1.threads '' "mysql Threads" "threads" threads mysql.threads line 60010 10
DIMENSION Threads_connected connected absolute 1 1
DIMENSION Threads_created created incremental 1 1
DIMENSION Threads_cached cached absolute -1 1
DIMENSION Threads_running running absolute 1 1

CHART mysql_db1.thread_cache_misses '' "mysql Threads Cache Misses" "misses" threads mysql.thread_cache_misses area 60011 10
DIMENSION misses misses absolute 1 100

CHART mysql_db1.innodb_io '' "mysql InnoDB I/O Bandwidth" "kilobytes/s" innodb mysql.innodb_io area 60012 10
DIMENSION Innodb_data_read read incremental 1 1024
DIMENSION Innodb_data_written write incremental -1 1024

CHART mysql_db1.innodb_io_ops '' "mysql InnoDB I/O Operations" "operations/s" innodb mysql.innodb_io_ops line 60013 10
DIMENSION Innodb_data_reads reads incremental 1 1
DIMENSION Innodb_data_writes writes incremental -1 1
DIMENSION Innodb_data_fsyncs fsyncs incremental 1 1

CHART mysql_db1.innodb_io_pending_ops '' "mysql InnoDB Pending I/O Operations" "operations" innodb mysql.innodb_io_pending_ops line 60014 10
DIMENSION Innodb_data_pending_reads reads absolute 1 1
DIMENSION Innodb_data_pending_writes writes absolute -1 1
DIMENSION Innodb_data_pending_fsyncs fsyncs absolute 1 1

CHART mysql_db1.innodb_log '' "mysql InnoDB Log Operations" "operations/s" innodb mysql.innodb_log line 60015 10
DIMENSION Innodb_log_waits waits incremental 1 1
DIMENSION Innodb_log_write_requests write_requests incremental -1 1
DIMENSION Innodb_log_writes writes incremental -1 1

CHART mysql_db1.innodb_os_log '' "mysql InnoDB OS Log Operations" "operations" innodb mysql.innodb_os_log line 60016 10
DIMENSION Innodb_os_log_fsyncs fsyncs incremental 1 1
DIMENSION Innodb_os_log_pending_fsyncs pending_fsyncs absolute 1 1
DIMENSION Innodb_os_log_pending_writes pending_writes absolute -1 1

CHART mysql_db1.innodb_os_log_io '' "mysql InnoDB OS Log Bandwidth" "kilobytes/s" innodb mysql.innodb_os_log_io area 60017 10
DIMENSION Innodb_os_log_written write incremental -1 1024

CHART mysql_db1.innodb_cur_row_lock '' "mysql InnoDB Current Row Locks" "operations" innodb mysql.innodb_cur_row_lock area 60018 10
DIMENSION Innodb_row_lock_current_waits current_waits absolute 1 1

CHART mysql_db1.innodb_rows '' "mysql InnoDB Row Operations" "operations/s" innodb mysql.innodb_rows area 60019 10
DIMENSION Innodb_rows_read read incremental 1 1
DIMENSION Innodb_rows_deleted deleted incremental -1 1
DIMENSION Innodb_rows_inserted inserted incremental 1 1
DIMENSION Innodb_rows_updated updated incremental -1 1

CHART mysql_db1.binlog_stmt_cache '' "mysql Binlog Statement Cache" "statements/s" binlog mysql.binlog_stmt_cache line 60020 10
DIMENSION Binlog_stmt_cache_disk_use disk incremental 1 1
DIMENSION Binlog_stmt_cache_use all incremental 1 1
CHART mysql_db1.connection_errors '' "mysql Connection Errors" "connections/s" connections mysql.connection_errors line 60021 10
DIMENSION Connection_errors_accept accept incremental 1 1
DIMENSION Connection_errors_internal internal incremental 1 1
DIMENSION Connection_errors_max_connections max incremental 1 1
DIMENSION Connection_errors_peer_addr peer_addr incremental 1 1
DIMENSION Connection_errors_select select incremental 1 1
DIMENSION Connection_errors_tcpwrap tcpwrap incremental 1 1
charts.d: 'mysql' has initialized.
charts.d: run_charts=' mysql'
CHART netdata.plugin_chartsd_mysql '' 'Execution time for mysql plugin' 'milliseconds / run' charts.d netdata.plugin_charts area 145000 10
DIMENSION run_time 'run time' absolute 1 1
BEGIN mysql_db1.net
SET Bytes_received = 1145947028720
SET Bytes_sent = 39152122069588
END
BEGIN mysql_db1.queries
SET Queries = 4976576090
SET Questions = 4976576090
SET Slow_queries = 264792
END
BEGIN mysql_db1.handlers
SET Handler_commit = 43111627
SET Handler_delete = 16420046
SET Handler_prepare = 0
SET Handler_read_first = 3375082
SET Handler_read_key = 321379166184
SET Handler_read_next = 1396364537949
SET Handler_read_prev = 5510178266
SET Handler_read_rnd = 5682095254
SET Handler_read_rnd_next = 2973612492043
SET Handler_rollback = 48
SET Handler_savepoint = 0
SET Handler_savepoint_rollback = 0
SET Handler_update = 115663309
SET Handler_write = 149362965
END
BEGIN mysql_db1.table_locks
SET Table_locks_immediate = 1945493546
SET Table_locks_waited = 1566818
END
BEGIN mysql_db1.join_issues
SET Select_full_join = 928183
SET Select_full_range_join = 70
SET Select_range = 88617989
SET Select_range_check = 0
SET Select_scan = 129690962
END
BEGIN mysql_db1.sort_issues
SET Sort_merge_passes = 21908
SET Sort_range = 72995921
SET Sort_scan = 56019721
END
BEGIN mysql_DB1.tmp
SET Created_tmp_disk_tables = 25571012
SET Created_tmp_files = 44418
SET Created_tmp_tables = 43299402
END
BEGIN mysql_DB1.connections
SET Connections = 65640831
SET Aborted_connects = 22
END
BEGIN mysql_DB1.binlog_cache
SET Binlog_cache_disk_use = 0
SET Binlog_cache_use = 0
END
BEGIN mysql_DB1.threads
SET Threads_connected = 14
SET Threads_created = 223978
SET Threads_cached = 6
SET Threads_running = 1
END
BEGIN mysql_DB1.thread_cache_misses
SET misses = 34
END
BEGIN mysql_DB1.innodb_io
SET Innodb_data_read = 950052540416
SET Innodb_data_written = 219723904512
END
BEGIN mysql_DB1.innodb_io_ops
SET Innodb_data_reads = 57986740
SET Innodb_data_writes = 8941078
SET Innodb_data_fsyncs = 3461274
END
BEGIN mysql_DB1.innodb_io_pending_ops
SET Innodb_data_pending_reads = 0
SET Innodb_data_pending_writes = 0
SET Innodb_data_pending_fsyncs = 0
END
BEGIN mysql_DB1.innodb_log
SET Innodb_log_waits = 0
SET Innodb_log_write_requests = 11976154
SET Innodb_log_writes = 1545903
END
BEGIN mysql_DB1.innodb_os_log
SET Innodb_os_log_fsyncs = 1980096
SET Innodb_os_log_pending_fsyncs = 0
SET Innodb_os_log_pending_writes = 0
END
BEGIN mysql_DB1.innodb_os_log_io
SET Innodb_os_log_written = 6336454656
END
BEGIN mysql_DB1.innodb_cur_row_lock
SET Innodb_row_lock_current_waits = 0
END
BEGIN mysql_DB1.innodb_rows
SET Innodb_rows_inserted = 9574374
SET Innodb_rows_read = 476343307731
SET Innodb_rows_updated = 678710
SET Innodb_rows_deleted = 95493
END
BEGIN mysql_DB1.binlog_stmt_cache
SET Binlog_stmt_cache_disk_use = 0
SET Binlog_stmt_cache_use = 0
END
BEGIN mysql_DB1.connection_errors
SET Connection_errors_accept = 0
SET Connection_errors_internal = 0
SET Connection_errors_max_connections = 0
SET Connection_errors_peer_addr =
SET Connection_errors_select = 0
SET Connection_errors_tcpwrap = 0
END
BEGIN netdata.plugin_chartsd_mysql
SET run_time = 23
END

**Comment by ktsaou** [comment]
thanks for reporting this!

The problem was the name `DB1`. When converted to chart id it becomes `db1`. But then, I had a few types in certain charts and used `DB1` to reference them.

It is now fixed.
Just pull the latest version and it should work.

**Comment by kepeta** [comment]
wow amazing, it works perfectly thank you very much 
![mariadb1](https://cloud.githubusercontent.com/assets/18693403/14845317/96044c8e-0c87-11e6-97cf-4e670bd9716f.JPG)
