### ISSUE TITLE
netdata loses everything after system reboot

### ISSUE THREAD

**Issue by icyblade** [firehol/netdata#3250]
This problem was found while I was trying to diagnose the problem of my server after a sudden hang&automatic reboot.

As #86 has mentioned, netdata will loads the data from `/var/cache/netdata` and continues, showing a small gap. However, my netdata shows nothing before the reboot time, but everything after the reboot time works fine.
After checking the `error.log`, I find something interesting:

> 2018-01-09 19:43:20: netdata ERROR: File /opt/netdata/var/cache/netdata/system.idlejitter/main.db does not have the desired size. Clearing it.

It seems that all the cache has been cleared after the reboot, so everything is lost. However, I can't find any related information about this "does not have the desired size".

Full `error.log` is available here: https://pastebin.com/uFvaHgBL

**Comment by ktsaou** [comment]
Hi,

by default netdata does not save its database while it runs. It saves them when it cleanly exits and loads it back when it restarts, So, if the server crashes, the metrics are lost.

You have a few options to overcome this:

1. set `memory mode = map`. This save continuously the database to disk. netdata will use memory mapped files (like swap), so every a few seconds everything will be saved. It has a constant disk I/O though.

2. setup a netdata master, and configure all your netdata to stream metrics to it. This way you could have a master with `memory mode = map` and all the slaves with any other memory mode (even `memory mode = none`).

3. use a time-series database to archive all the metrics. netdata supports prometheus, graphite, opentsdb and all compatible ones (kairodb, influxdb, etc). It also supports `JSON` backends.

**Comment by icyblade** [comment]
Thanks for your help! I'll have a try.
