### ISSUE TITLE
Problem with statsd after upgrade

### ISSUE THREAD

**Issue by cis2131** [firehol/netdata#3265]
After automatic upgrade today 11/1-18, statsd has stopped working.

It gives the following error at start:
netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: internal error: discarding 20 bytes received on socket 8

Current version is now: 1.9.0-173-g256b929_rolling

**Comment by ktsaou** [comment]
Yes, you are right. Just fixed it with PR #3266 
Sorry for this.

So, just update your netdata.
