### ISSUE TITLE
How to monitor apache vhosts with netdata

### ISSUE THREAD

**Issue by RichardNeveri** [firehol/netdata#3274]
Hi,

first, a huge thanks for Netdata. It's awesome. I already have the mysql and apache plugin configured and am wondering : Is there a way to monitor the vhosts to see which gets the most requests and or uses the most resources (cpu etc..)?

This would be a huge help when trying to pinpoint which site needs to be optimized the first to sort of get the most server performance out of the least amount of work.

Thanks for any tips!

**Comment by l2isbad** [comment]
Hi @RichardNeveri 
https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file
https://london.my-netdata.io/default.html#menu_web_log_nginx_netdata_submenu_responses;theme=slate

**Comment by RichardNeveri** [comment]
Hi l2isbad, thansk for the reply. I'll check it out.
