### ISSUE TITLE
Memory Limit Failures on cgroup

### ISSUE THREAD

**Issue by donghwicha** [firehol/netdata#3281]
Hello. I'm using netdata for monitoring cgroup
and I found out that there is a metric called "Memory Limit Failures"
but I can not find  any documentation about it. 

Can someone please point me where I can find information about "Memory Limit Failures"?
Any hint would be appreciated.

**Comment by ktsaou** [comment]
Hi,

You want to setup memory limits for your containers or you want to monitor the limits you have already set on your containers?

**Comment by donghwicha** [comment]
>  I found out that there is a metric called "Memory Limit Failures"

it is already there on netdata web UI and I want to know what's supposed to mean. I couldn't find any explanation about it and I had to dig into its source code. 

https://github.com/firehol/netdata/blob/3365691a1b8b4d445aa2cb0fc8afaeafb347dc85/src/sys_fs_cgroup.c#L1663-L1676

**Comment by ktsaou** [comment]
oh, I see. This is a metric exposed by the kernel, when you have configured a limited amount of memory for a container. So, the kernel counts the number of times it limited the container to use more memory.

The kernel counter is called `memory.failcnt`. More information here: https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

**Comment by donghwicha** [comment]
Thanks for the explanation!
