### ISSUE TITLE
Prometheus get different time metrics

### ISSUE THREAD

**Issue by andreioss** [firehol/netdata#3287]
Hi!
I have set up netdata+prometheus+grafana.
netdata 1.9
Prom 2.0
Collection method - average.
Scrape interval - 5 seconds.

And I observe a strange thing - every request to build a graph, give me different set of time for metric points, therefore I've got different variants of graphic (every Execute in Prom web ui or Update in grafana web ui), because metrics values are little vary.

For example, we have:
netdata_system_cpu_percentage_average{chart="system.cpu",dimension=~".*",family="cpu",instance="$host",job="netdata-scrape"}

and first execute give me some set of metrics, one or them - 7:15:39GMT and have value of system.cpu guest = 0.40122... second time I've Execute, and getting total different set of times and point for 7:15:39GMT already disappear and I have 7:15:44GMT, or 7:15:27GMT with another values.

Here are three screenshots of three executes in a row, why are they so different?

![screenshot-2018-1-15 prometheus time series collection and processing server 2](https://user-images.githubusercontent.com/4836307/34931437-dbecaee8-f9df-11e7-91ae-e30498401734.png)
![screenshot-2018-1-15 prometheus time series collection and processing server 1](https://user-images.githubusercontent.com/4836307/34931445-e3d67166-f9df-11e7-91f1-7125ba52c646.png)
![screenshot-2018-1-15 prometheus time series collection and processing server](https://user-images.githubusercontent.com/4836307/34931447-e649158e-f9df-11e7-8626-caa7ba4d2daf.png)

**Comment by andreioss** [comment]
In Prom logs I see such errors:

`
level=warn ts=2018-01-14T19:06:02.805141096Z caller=scrape.go:905 component="target manager" scrape_pool=netdata-scrape target="http://HOSTNAME:19999/api/v1/allmetrics?format=prometheus&source=average" msg="Error on ingesting samples with different value but same timestamp" num_dropped=3`

**Comment by ktsaou** [comment]
hm... I think this is a question about prometheus. netdata sends only one value to prometheus every time and prometheus keeps tracks of them as a series.

This seems like prometheus is receiving metrics from multiple netdata, but it thinks it is the same.

Though, I am not really the guy to answer this.

**Comment by andreioss** [comment]
Hmmm, I see, thanks.
Going to Prom community with question :)

**Comment by ktsaou** [comment]
ok, if you conclude there is a fault in netdata, please let us know...

**Comment by andreioss** [comment]
I apologize, don't you mind if I add some piece of info here, about this problem? Maybe someone have a fresh idea...
I asked everywhere in Prometheus community, but there is dead activity unfortunately :( .

> I've noticed, that on every execute I've got new timestamp for the same metric and labels.

> Scrape time - every 5 sec in Prometheus.
> For example I executed:
> 
> netdata_system_load_load_average{chart="system.load",dimension="load15",family="load",instance="$host",job="netdata-scrape"}
> And get following metrics:
> 
> 23:52:01GMT value
> 23:52:06GMT value
> 23:52:11GMT value
> 
> On the next query execute I'm getting following:
> 
> 23:52:04GMT value
> 23:52:09GMT value
> 23:52:14GMT value
> 
> And the next:
> 
> 23:52:02GMT value
> 23:52:07GMT value
> 23:52:12GMT value
> 
> in the end, after some numbers of execute, I get "23:52:01GMT value" again.
> It seems, like on query, Prometheus didn't give all points but some of them, some set of them, and on every update, it give me new and new set of timestamps of metrics.

And I'm sure it's the same instance, I've checked all my nodes that scraping from netdata - there is no even similar metric value in specified time period... Just different timestamps.

**Comment by n0guest** [comment]
> I apologize, don't you mind if I add some piece of info here, about this problem? Maybe someone have a fresh idea...

Not sure if i'm able to help, but i have one question related to your initial post in prometheus-users mail list:

> and first execute give me some set of metrics, one or them - 7:15:39GMT and have value of system.cpu guest = 0.40122... second time I've Execute, and getting total different set of times and point for 7:15:39GMT already disappear and I have 7:15:44GMT, or 7:15:27GMT with another values.

Are you sure about "disappearing"? It could be a very dumb assumption, but did you check same metric including interval? I.e. what you see when you ran such query:

```
netdata_system_load_load_average[1m]
```

Based on your description (first query at  7:15:39GMT, second at 7:15:44GMT) it looks like Prometheus just shows last "scraped" value and it's normal behaviour.

PS: We're using Netdata 1.8.x with Prometheus 2.x/Grafana 4.6 and i didn't see such problems. At least for now.

**Comment by andreioss** [comment]
Wow, thanks for reply! :)

After some research and diagnosis I've discovered, that Prometheus store all metrics as scraped and in its storage everything is fine (I've checked it via curl queries to Prom).

I think there is some logic in grafana building graph and aggregation points it get from Prometheus with specified query. 
What do I mean - grafana *did not* show every metric time point on graph as it get from Prom.

For example, I have 30sec scrape interval and resolution on grafana - 1/2.
And such query:
`netdata_system_cpu_percentage_average{chart="system.cpu",dimension=~".*",family="cpu",instance="$host",job="netdata-scrape"}`
Opening graph for the first time, give me such metric points:

12:52:04GMT
12:53:04GMT
12:54:04GMT
and so on, and it seems alright!

But on the next update graph, I've completely another time points:
12:52:25GMT
12:53:25GMT
12:54:25GMT

And of course there are NO such timestamps at the Prometheus!
For this host I have following metric points:

12:52:00GMT
12:52:30GMT
12:53:00GMT
and so on.

I just want to understand such behavior of grafana, is it alright and how can I force it to draw exact points from Prom database without aggregation...

**Comment by n0guest** [comment]
> I just want to understand such behavior of grafana, is it alright and how can I force it to draw exact points from Prom database without aggregation...

I guess it's offtopic for this place and not related to Netdata ;)

PS: But, i'd recommend you to read Grafana docs. Especially related to Metrics tab (min step and resolution). It could help you understand how Grafana draws it and why.
