### ISSUE TITLE
High memory consumption by netdata process

### ISSUE THREAD

**Issue by hktyper** [firehol/netdata#3293]
Machine specs
CPU(s):                      20
On-line CPU(s) list:   0-19
Thread(s) per core:   2
Core(s) per socket:   10
Socket(s):                  1
Model name:            Intel(R) Xeon(R) CPU E5-2450L v2 @ 1.70GHz
RAM:                        64GB

Changes and declarations made in netdata.conf

```
[global]
        # glibc malloc arena max for plugins = 1
        # glibc malloc arena max for netdata = 1
        # hostname = xpnyph0014.lab
        history = 86400
        update every = 30

```

```
[users.cpu]
        # history = 3996
        enabled = no
        # cache directory = /var/cache/netdata/users.cpu
        # chart type = stacked
```

```
[plugin:cgroups]
        cgroups plugin resource charts = no
        # update every = 1
        # check for new cgroups every = 10

```

Cannot seem to reduce the MEM utilisation below 29GB no matter what plugin i disable, although disabling the plugins doesn't seem to reduce the MEM usage either, also reading through the documentation the dimensions corresponds with the MEM usage also, however is reducing the dimensions carried out in /opt/netdata-1.9.0/web/dashboard.html?

![netdata](https://user-images.githubusercontent.com/10854706/34983976-32e4b99e-faa7-11e7-85ed-abac8ceed9ce.png)

**Comment by l2isbad** [comment]
I see `30 days, 4 hours and 30 mins of real-time history` (1 month per seconds history).

**Comment by hktyper** [comment]
Apologies forgot to add, this machine also acts as a master with 12 other slaves streaming it's metrics to it also, however documentation would indicate this should have no bearing on the MEM usage.

`        # memory mode = save`

And also virtual memory set to;

`vm.max_map_count = 65530`

**Comment by ktsaou** [comment]
`memory mode = map` is for such setups. But you need SSD disks.
Read more here: https://github.com/firehol/netdata/wiki/Memory-Requirements#running-a-dedicated-central-netdata-server

**Comment by csamsel** [comment]
my 2 cents: For cases like this, (optionally) using an external database server like postgres/mysql/etc or mongodb/redis seems more appealing to me then engineering all the memory management inside netdata.

**Comment by ktsaou** [comment]
> my 2 cents: For cases like this, (optionally) using an external database server like postgres/mysql/etc or mongodb/redis seems more appealing to me then engineering all the memory management inside netdata.

hm... the most appropriate would be a time-series db. But the whole idea with netdata is to eliminate the need for such dbs. I think the new db format we prepare will solve most memory management problems.
