### ISSUE TITLE
Issues installing netdata

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3298]
I was wondering if there was a known problem with installing netdata. Getting:
pi@TestPi:/opt $ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
curl: (7) Failed to connect to my-netdata.io port 443: Connection timed out

Traceroute gets to:
14  ae-2.r02.londen01.uk.bb.gin.ntt.net (129.250.3.1)  132.771 ms  132.259 ms  130.512 ms
15  ae-1.r03.londen01.uk.bb.gin.ntt.net (129.250.3.37)  133.202 ms  130.624 ms  125.933 ms
16  62.73.179.138 (62.73.179.138)  127.964 ms ae-1.digital-ocean.londen01.uk.bb.gin.ntt.net (83.231.181.122)  127.288 ms 62.73.179.138 (62.73.179.138)  121.584 ms
17  * * *
18  * * *

**Comment by ktsaou** [comment]
my fault. wrong click at cloudflare.com
It should be working shortly.

**Comment by ktsaou** [comment]
it should be ok now.
