### ISSUE TITLE
Current Netdata shows blank screen, no graphs on my system

### ISSUE THREAD

**Issue by dlakelan** [firehol/netdata#3299]
I had netdata working before, but at the moment when I connect to http://myhost.lan:19999 I get the background screen and a busy loading sign and if I scroll down a bunch of fairly raw un-formatted sections of a web page, as if there's something seriously wrong with the CSS and it's not rendering into any kind of visual display. Is this just me? I uninstalled and re-installed using current pre-compiled script... no help, same thing.

This is running on a recently updated (few days ago) Debian Testing system.

**Comment by ktsaou** [comment]
I think this is related to this https://github.com/firehol/netdata/pull/3310

Could you please re-install?

**Comment by dlakelan** [comment]
Yes, reinstall today fixed this issue.
