### ISSUE TITLE
monitor postgres on CentOS6

### ISSUE THREAD

**Issue by BillTian** [firehol/netdata#3300]
**environment:**

1.     OS: CentOS 6.9
2.     Python: 2.6.6 with python-psycopg2-2.0.14-2.el6.x86_64 installed
3.     Netdata: 1.9.0

**error in netdata log:**
postgres: tcpipv4: check() unhandled exception: 'psycopg2._psycopg.connection' object has no attribute 'set_session'

I think this is because the wrong psycopg2 version, i installed python2.7.14 in /usr/local with `make altinstall` , can netdata run plugins whith python2.7.14 in `/usr/local` ?

Thank a lot !

**Comment by l2isbad** [comment]
Hi @BillTian 
https://github.com/firehol/netdata/issues/2151#issuecomment-299042629

**Comment by BillTian** [comment]
@l2isbad , Thank you !
It's working now !
