### ISSUE TITLE
Installing Netdata

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3305]
Wanted to check to see if there was an issue with netdata installation:
pi@HornDNS:~ $ sudo bash <(curl -Ss https://my-data.io/kickstart.sh)
bash: /dev/fd/63: No such file or directory
pi@HornDNS:~ $ curl: (7) Failed to connect to my-data.io port 443: Connection refused

**Comment by ktsaou** [comment]
Hi,

1. do not `sudo` this command, it will do it by itself when needed - when you sudo, the downloaded script is given to `sudo`, but we want it to be given to `bash`.

2. the URL is `my-netdata.io`, not `my-data.io`

**Comment by hornjt75862** [comment]
I am sorry for these questions. You have been so supportive and I thank you again for all the assistance you have provided.
