### ISSUE TITLE
Python Cherrypy + Logfile Monitoring

### ISSUE THREAD

**Issue by r-chris** [firehol/netdata#3307]
I am trying to add netdata to our servers and probably haven't fully understood how the plugins work or if what I'm trying to do is easily possible.

Essentially, I was hoping I could setup a health-status monitor for our [cherrypy](http://cherrypy.org) webapp as well as use netdata to monitor its log files. I would ideally like to write some filters for those log-files that allow me to display status info for things like:
- how many requests / sec are coming in
- how many people are currently logged in
- ...

I had a look through the different plugins (charts, python, ...) but didn't fully understand if I should write a new plugin for this or just add a new "module"?

**Comment by r-chris** [comment]
Maybe there is already some comparable example to what I am trying to achieve, if anyone could kindly point me in the right direction? Thanks!

**Comment by ktsaou** [comment]
Hi,

I suggest to set a specific goal. The way you asked is too generic.

Generally though, you should prefer to write a plugin module for the language of your choice. I guess you prefer python, so just write a python plugin. [There are dozens already](https://github.com/firehol/netdata/tree/master/python.d), so just pick one and adapt it.

The simplest is this: https://github.com/firehol/netdata/blob/master/python.d/example.chart.py

For your log files, if they look like web logs, the `web_log` module is quite powerful - you may get it to parse your log files with just configuration. Check this: https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file and its config file: https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf

**Comment by r-chris** [comment]
Great - I will certainly try both options.

If I understood the plugins correctly, I can just drop in a new py file right next to the others (+ a config file?) and netdata should load that file automatically?

**Comment by l2isbad** [comment]
> If I understood the plugins correctly, I can just drop in a new py file right next to the others (+ a config file?) and netdata should load that file automatically?

yes
