### ISSUE TITLE
dashboard for the home page of netdata (your comments needed)

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#331]
Check this: http://netdata.firehol.org/demosites.html?v2

I plan to put this as the home page of netdata demo sites.

Any comments are welcomed.

**Comment by simonnagl** [comment]
Netdata.clients could be interesting too.

**Comment by ktsaou** [comment]
thanks!

> Netdata.clients could be interesting too.

Well, the demo sites go out through nginx, which go out through cloudflare.com, so you cannot tell the actual unique clients, but yes it should be there...

**Comment by FallingSnow** [comment]
502 error :(

**Comment by ktsaou** [comment]
thanks! updating to the latest version.
now it is ok.

**Comment by ktsaou** [comment]
done. this is now the home of http://netdata.firehol.org/
