### ISSUE TITLE
How to ignore dropped ICMP packets ?

### ISSUE THREAD

**Issue by jpic** [firehol/netdata#3314]
Hello !

We drop ICMP packets, sometimes this causes inbound packets dropped ratio alert, is it possible to keep the alert but ignore ICMP packets ?

Thanks !

**Comment by ktsaou** [comment]
Unfortunately no. This is entirely handled by the kernel. netdata just reads the number of dropped packets without any control on it.

**Comment by jpic** [comment]
Awesome, thanks for answering.​
