### ISSUE TITLE
Sensors temperature alarm

### ISSUE THREAD

**Issue by tern222** [firehol/netdata#3315]
Hello. Try to do alarm for temperature sensor. In my system i see two. If i use sensors.acpitz-virtual-0_temperature all ok

```
   alarm: cpu_temp
      on: sensors.acpitz-virtual-0_temperature
   units: Celsius
   every: 10s
    warn: $temp1 > 25 OR $temp2 > 25
    crit: $temp1 > 28 OR $temp2 > 28
    info: cpu core temperature
      to: sysadmin
```

if i use sensors.coretemp-isa-0000_temperature nothing works

 ```
alarm: cpu_temp
      on: sensors.coretemp-isa-0000_temperature
   units: Celsius
   every: 10s
    warn: $Core 0 > 25 OR $Core 1> 25
    crit: $Core 0 > 28 OR $Core 1 > 28
    info: cpu core temperature
      to: sysadmin
```
Tell me please how to bring the second option to the working class?
Tell please how to calculate the average temperature for a parameter "calc:"?

**Comment by dzaczek** [comment]
i have this same problem

**Comment by tern222** [comment]
I've been neglectful in the study documentation. In my case, Core 0 and Core 1 should be replaced by Core_0 and Core_1

**Comment by ktsaou** [comment]
> I've been neglectful in the study documentation. In my case, Core 0 and Core 1 should be replaced by Core_0 and Core_1

You can see the dimensions of a chart with this:

```
http://your.netdata.ip/api/v1/chart?chart=system.cpu
```

Replace `system.cpu` with the chart you want to examine.

If the dimension contains spaces, you can use `${Core 0}`.
