### ISSUE TITLE
backends: select which hosts to send

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3316]
If I understand correctly, Netdata Master Node will send all Clients (slaves) metrics to backend. 
But what if Clients (slaves) sends their metrics to backend by them-self (fault tolerance).
Is there an option to Netdata Master send its metric but not Clients (slaves) one?
Thank you.

**Comment by ktsaou** [comment]
Unfortunately no, but we could add such an option.

**Comment by ktsaou** [comment]
in PR #3322

**Comment by ktsaou** [comment]
merged it.
