### ISSUE TITLE
Synology: netdata updater causes netdata to remain stopped after a successful update

### ISSUE THREAD

**Issue by agross** [firehol/netdata#3321]
Hi,

I'm using netdata on a Synology with Debian Chroot. All netdata-related features work except for the update mechanism that is enabled by default.

From reading the installer logs, it seems that the installer is unable to restart netdata after the update because `systemctl start netdata` is ignored by the system (with exit code 0) and other methods of starting netdata are not tried.

Relevant log lines:
<details>

```
 --- Restore user edited netdata configuration files ---
...
 --- Fix generated files permissions ---
...
 --- Add user netdata to required user groups ---
...
 --- Read installation options from netdata.conf ---
...

 --- Install netdata at system init ---
I don't know what init file to install on system 'debian-8'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service.

 --- Start netdata ---
[/usr/src/netdata.git]# /bin/systemctl stop netdata
Running in chroot, ignoring request.
 OK

Stopping netdata on pid 9932 ..........
netdata on pid 9932 stopped.
[/usr/src/netdata.git]# /bin/systemctl restart netdata
Running in chroot, ignoring request.
 OK

OK. NetData Started!

 --- Check KSM (kernel memory deduper) ---
...
 --- Check version.txt ---
 --- Check apps.plugin ---
 --- Generate netdata-uninstaller.sh ---
 --- Basic netdata instructions ---
...

Uninstall script generated: ./netdata-uninstaller.sh
Update script generated   : ./netdata-updater.sh

netdata-updater.sh can work from cron. It will trigger an email from cron
only if it fails (it does not print anything when it can update netdata).
 --- Refreshing netdata-updater at cron ---
[/usr/src/netdata.git]# rm /etc/cron.daily/netdata-updater
 OK

[/usr/src/netdata.git]# ln -s /usr/src/netdata.git/netdata-updater.sh /etc/cron.daily/netdata-updater
 OK


 --- We are done! ---
```

</details>

On the Synology UI for Debian Chroot I have set up to launch netdata and cron as services, so I do not need to start anything manually after rebooting the device:

<img width="902" alt="2018-01-20_13-14-29" src="https://user-images.githubusercontent.com/16245/35183298-e17d95d6-fde3-11e7-8030-472a423aac6b.png">

**Comment by ktsaou** [comment]
hm...

so this is the problem:

```
[/usr/src/netdata.git]# /bin/systemctl stop netdata
Running in chroot, ignoring request.
 OK

Stopping netdata on pid 9932 ..........
netdata on pid 9932 stopped.
[/usr/src/netdata.git]# /bin/systemctl restart netdata
Running in chroot, ignoring request.
 OK
```

1. the installer found that netdata was still running after `systemctl stop netdata`, and stopped it.
2. the installer did not check that netdata was started after `systemctl restart netdata` and just used the exit code of `systemctl`.

So, I think the only solution would be to also check that netdata is started and if it is not to start it without calling `systemctl`.

**Comment by agross** [comment]
Yes, I had the same idea. But I wasn't sure if I was correct. What would be the fallback mechanism?

Given that Debian Chroot on Synology shows whether a service is running or not (see screenshot), I would be in favor of a solution that makes the lsb script report that netdata is running after an automatic update.

**Comment by agross** [comment]
Yes, I had the same idea. But I wasn't sure if I was correct. What would be the fallback mechanism?

Given that Debian Chroot on Synology shows whether a service is running or not (see screenshot), I would be in favor of a solution that makes the lsb script report that netdata is running after an automatic update.

**Comment by agross** [comment]
Yes, I had the same idea. But I wasn't sure if I was correct. What would be the fallback mechanism?

Given that Debian Chroot on Synology shows whether a service is running or not (see screenshot), I would be in favor of a solution that makes the lsb script report that netdata is running after an automatic update.

**Comment by agross** [comment]
Yes, I had the same idea. But I wasn't sure if I was correct. What would be the fallback mechanism?

Given that Debian Chroot on Synology shows whether a service is running or not (see screenshot), I would be in favor of a solution that makes the lsb script report that netdata is running after an automatic update.

**Comment by agross** [comment]
Yes, I had the same idea. But I wasn't sure if I was correct. What would be the fallback mechanism?

Given that Debian Chroot on Synology shows whether a service is running or not (see screenshot), I would be in favor of a solution that makes the lsb script report that netdata is running after an automatic update.

**Comment by ktsaou** [comment]
Can you check it? PR #3323.

**Comment by agross** [comment]
Seems to be working! As always, thank you for the immediate fix!

```
 --- Install netdata at system init ---
I don't know what init file to install on system 'debian-8'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service.

 --- Start netdata ---
[/usr/src/netdata.git]# /bin/systemctl stop netdata
Running in chroot, ignoring request.
 OK

Stopping netdata on pid 7855 ..............
netdata on pid 7855 stopped.
[/usr/src/netdata.git]# /bin/systemctl restart netdata
Running in chroot, ignoring request.
 OK

Ooops! it seems netdata is not started.
[/usr/src/netdata.git]# /bin/systemctl start netdata
Running in chroot, ignoring request.
 OK

Hm... it seems netdata is still not started.
[/usr/src/netdata.git]# stop_all_netdata
 OK

[/usr/src/netdata.git]# /usr/sbin/netdata
 OK

OK. NetData Started!
```
