### ISSUE TITLE
REQUEST: a graph detailing the amount of data written to/deleted from a file system

### ISSUE THREAD

**Issue by nizedk** [firehol/netdata#3324]
The graph should not show the amount of data written (as is already graphed otherwise) but the effective reduction or increase in free space; so you can see if ie. a process is logging less than it did before, that more data is being written or deleted.

The reason for the request is that if you have, say 500 kbyte/sec logfiles added to a file system (say, because of an error), and you fix the error, it's not evident in the disk usage graph on o large volume. You need more than hours of overview to see that on the angle of the graph.

A database could also be writing the same place over and over, which would be data written, but not less free space.

For me it would help to find out if the trend for disk usage is changed; much like the 'time to disk full' alarm is doing, just visualized in 'data added or removed'.

I hope you get my drift. :-)

Also, thank you for a great product that is useful and of high quality.

Br,
Martin

**Comment by nizedk** [comment]
If not clear, i was thinking of a amount pr time unit graph

**Comment by Ferroin** [comment]
OK, so just to clarify, you want  a graph of the change in free space over time?

I actually agree that such a chart could be very useful.  At the very least, it would probably simplify the calculations for the time to disk full alarm (the alarm itself actually calculates the rate of change and extrapolates time remaining from that, so this would end up pushing that rate calculation logic into the main netdata process itself).

**Comment by nizedk** [comment]
Yes, exactly, so you can see when data was added or freed etc. and at what rate pr time unit

**Comment by ktsaou** [comment]
Guys, I am not sure I understand. I don't the difference with the existing free space chart.

Could you please provide an example case?

**Comment by nizedk** [comment]
Sorry about the long delay in my answer.

If you have a free space graph over time, on a 2 TB volume, and you add 1 Mbyte/sec, and you fix a process so you only add 500Kbyte/sec, it's almost impossible to discern on the free space graph - it would effectively be flat You can't tell the difference on the IO rate graphs, as they do not necessarily result in free space change.

So, a graph showing the 1 MByte/sec reduction in freespace and afterwards a change to 500 KByte/sec reduction, would be exactly what I need; much like a network interface graph deals in rate/timeinterval and not volume; that wouldn't help you much.

**Comment by Ferroin** [comment]
As @nizedk commented, scale is really the issue here.

Put a slightly different way, imagine you've got a 10TB filesystem that has 5TB of data on it.  Now imagine you delete a 1TB file.  You'll definitely notice that on the free space graph.  You'll probably notice a 100GB file being deleted too, and you might notice a 10GB file being deleted (though it may not show up in the numbers off to the side because netdata only shows two digits beyond the decimal point).  Now imagine how hard it's going to be to see that a 100MB file got deleted from the same filesystem.  Similarly, imagine how hard it would be to notice a slow 1MB/s increase in space usage on that 10TB filesystem.

This issue of scaling is why network usage graphs are always measuring instantaneous rate, not cumulative usage, and why you almost always want not just a total count of processes on the system but also a graph of how fast new processes are being created.

**Comment by ktsaou** [comment]
hm... I think this is my fault. It should be like this:

![peek 2018-01-27 13-35](https://user-images.githubusercontent.com/2662304/35471600-fcd1b154-0366-11e8-807c-ed3219b5a944.gif)

making a PR now...

**Comment by ktsaou** [comment]
merged it

**Comment by nizedk** [comment]
Awesome! Thanks a bundle!

I'd still like the rate indication, but this works much better than before.

Great work, much appreciated!

**Comment by ktsaou** [comment]
> I'd still like the rate indication

I gave it a thought. This feature is needed for a lot more things, like the apps charts, memory, etc. Adding all these extra charts would waste resources, gives that the information is already "hidden" in the charts that already exist.

Probably, some day we may support "derivative charts", that is charts that do not have any real resources inside netdata, but are derived from the existing ones. We need this in a ton of cases...

**Comment by nizedk** [comment]
Offloading memory usage to relative simple cpu calculations, or entirely offloading to client-side calculations could probably provide som benefits, as long as they do not prevent the usage of backends and their visualization mechanics.

Again, thank you, it has already made my sysadmin life somewhat more efficient. :-)
