### ISSUE TITLE
Notifications to Microsoft Teams

### ISSUE THREAD

**Issue by wccropper** [firehol/netdata#3330]
Our company is adding Microsoft Teams. I would like to send alerts to a channel just like Slack, etc. I have the ability to create API urls just like Slack. What would be needed to implement this?

**Comment by donghwicha** [comment]
you can use Prometheus after integration with netdata.  Prometheus has notification feature.

**Comment by Ferroin** [comment]
The code that's actually responsible for sending the alerts is in [alarm-notify.sh](https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh).

If you can get API urls similar to those used by Slack, it shouldn't be too hard to integrate.  The various `send_` functions in alarm-notify.sh are what actually issues alert (most of them are just wrappers around a call to cURL that submits the required data to the required URL), I'd suggest starting by looking through those in particular.

**Comment by ktsaou** [comment]
@wccropper it should be very simple to do it. As @Ferroin says, it is just copy-paste-adapt.
You can give it a try and make a PR - I'll review this to make sure you did it right.

**Comment by domacikolaci** [comment]
Hi, 

I'm looking at integrating Netdata to Microsoft Teams now, how do we proceed with this? Dont see anything in the Wiki.

Thanks :)

**Comment by domacikolaci** [comment]
Bump <3

**Comment by ktsaou** [comment]
It has been merged in early august.
@Ferroin has a pending task to create the wiki.

However, you can find relevant info at the config file: https://github.com/firehol/netdata/blob/be9507fe8d3bbf6fe9ec91bce653e00675352db6/conf.d/health_alarm_notify.conf#L342-L374

**Comment by ktsaou** [comment]
This has been fixed with #3903
