### ISSUE TITLE
Split mdstat operation status?

### ISSUE THREAD

**Issue by agross** [firehol/netdata#3331]
Hi,

I currently have a RAID array rebuild on one of my netdata hosts. The mdstat operation status by default shows the "finish min[utes]" and transfer rate as "MB/s" (negated value).

For large arrays the rebuild can take a very long time, hence "finish min" is very large (I started at ~7000), but "MB/s" is low compared to that (I get around 30). As such the combined graph showing both values could be improved from a "MB/s" perspective because you can only barely see the differences:

<img width="570" alt="2018-01-23_16-45-36" src="https://user-images.githubusercontent.com/16245/35285343-6bdbb96c-005d-11e8-8a43-00c5c0b88874.png">

"MB/s" changes though as you can see when you disable "finish min":
<img width="579" alt="2018-01-23_16-45-50" src="https://user-images.githubusercontent.com/16245/35285368-7c142ddc-005d-11e8-95f6-d14443aa536c.png">

Ideas:
* Split into two graphs, make all values positive
* Scale the negative axis differently (not sure if this is possible)

**Comment by l2isbad** [comment]
You are right.
