### ISSUE TITLE
Mysql Monitor Fails On Cluster Primary Node

### ISSUE THREAD

**Issue by name256** [firehol/netdata#3334]
Good day,

I have been having a hard time configuring mysql monitoring on the primary node of a Percona XtraDB cluster. I have been getting the below errors when I run **/usr/libexec/netdata/plugins.d/python.d.plugin degug 1 | grep mysql**

2018-01-24 11:03:38: python.d ERROR: mysql: socket3_root: **chart 'mysql_local.slave_behind' was suppressed due to non updating**
2018-01-24 11:03:38: python.d ERROR: mysql: socket3_root: **chart 'mysql_local.slave_status' was suppressed due to non updating**

The two other databases in the cluster are working fine with netdata monitoring and are providing data as required.

Kindly assist in resolving the issue.

Abel

**Comment by l2isbad** [comment]
Hi @name256 
Please do 
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by name256** [comment]
Hi @l2isbad,
Thanks for the response. Please find attached the loge output of the **/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql** command.

[mysql_local.log](https://github.com/firehol/netdata/files/1659247/mysql_local.log)

**Comment by l2isbad** [comment]
I see it works (`socket3` job)

**Comment by name256** [comment]
@l2isbad seems my configs are running from /opt instead of /etc like my other installations. Finally got it working. I am not very sure but I think this may be a side effect of me doing the basic installation first and then doing the full installation later that downloaded all the plugins i.e **bash <(curl -Ss https://my-netdata.io/kickstart** and then **bash <(curl -Ss https://my-netdata.io/kickstart.sh) all**

However thank you very much for taking the time to assist.

Kind regards
