### ISSUE TITLE
Health logs in journald not shown, when using "error log = stderr" or "error log = syslog"

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3338]
Hello,
I`m trying to configure ELK to work with Netdata.
But I cant see no health messages in journald.
I saw NETDATA_LOG_DIR var, but it seems has no effect, when set to to "stderr" of "syslog".

**Comment by ktsaou** [comment]
Which message exactly? Can you post one? I think you are looking for the messages of `alarm-notify.sh`, which should be present in journald when `error log = stderr`.
