### ISSUE TITLE
Monitoring questions

### ISSUE THREAD

**Issue by holzfelix** [firehol/netdata#3339]
hi is it possible to do the following:

I have in a docker container a application running. this application is listening on a specific port. 
Can I test if I get HTTP Status 200 from the applications port, and if not I want a notification? 
and also if the response time is tooo long I want a notification is that possible?

Thanks

**Comment by r-chris** [comment]
I'm not an expert at `netdata`, but this sounds more like a job for an uptime monitoring tool. I actually would like to do something as you describe with `netdata` as well, but as far as I understand this tool it can monitor log files from **within** the server, not from the outside.

I have packaged `netdata` inside my docker containers and you might want to look at how it monitors log files.

**Comment by holzfelix** [comment]
Do you maybe have another solution for me?

**Comment by Ferroin** [comment]
Are you just trying to verify that the application itself is running inside the container, or do you need to know if the container isn't running too?

In the first case, check out some of the more advanced process supervision tools like [monit](https://mmonit.com/monit/) (in fact, monit can do exactly what you want, and if you are running it inside the container it can even restart the application for you if the check fails and things time out).

In the second case, a tool like monit would work too, you just run it outside the container (or on a dedicated monitoring host).

As a general rule, Netdata isn't really all that great for this type of thing, as such a situation typically means you have to write up a custom plugin to do what you want.  On that note, I've been considering for a while now writing a plugin to handle this type of thing (send a predefined message to a given port at a given IP address over TCP or UDP, validate the response, and record the latency), but I have not really had the time to work on it, and don't have any seriously pressing need for it myself.

**Comment by r-chris** [comment]
Generally agree with @Ferroin here - __monit__ is worth a look, but if you need to monitor a larger network of instances, their "master" node to collect everything is not free software. (Their licensing can be described as decent, though and no I am not affiliated with them).

**Comment by Ferroin** [comment]
If it's a large network, then I'd actually suggest something like Nagios over monit, as it's better designed for stuff like that.

**Comment by r-chris** [comment]
Yeah thanks - it’s not a large network and Zabbix / nagios is just too much trouble to setup - I was looking for something simpler

**Comment by ktsaou** [comment]
Generally, writing such a plugin for netdata is pretty simple. You can even write it in bash.

However, the proper solution would be to make netdata monitor a web server log file. If your web app does not support log files, I suggest to install `nginx` in front of it (on the same host). `nginx` will not introduce any noticable latency on localhost and netdata can use its log file to provide all kinds of alarms.

Docs: https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file
Demo: https://london.my-netdata.io/#menu_web_log_nginx_netdata

You will be amazed with the insights netdata provides with simple access to a web log file... It is also comes with a lot standard alarms...

**Comment by holzfelix** [comment]
Thanks for your Ideas. I finally set up a nagios ... Its userinterace is not such nice than netdata but it does what I need. 

Thanks

**Comment by ilyam8** [comment]
@arenddeboer 

sounds like [httpcheck](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/httpcheck) module

**Comment by arenddeboer** [comment]
@ilyam8 ahh, thanks!
