### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by CallMeR** [firehol/netdata#3358]
The following packages have unmet dependencies:
 uuid-dev : Depends: libuuid1 (= 2.27.1-6ubuntu3.3) but 2.27.1-6ubuntu3.4 is to be installed
E: Unable to correct problems, you have held broken packages.
-------------------------------------------------------------------------------------------------------------------
lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
------------------------------------------------------------------------------------------------------------------
Is there sth wrong with my ecs ？
8D

**Comment by ktsaou** [comment]
hm... did you try `apt-get update` or `apt-get distro-sync` ? It seems there is some inconsistency on the versions of your packages.

But I am not the expert on this.
If anyone can help, please do...

**Comment by Aitkots** [comment]
I think it's the problem about the  specific distro “Ubuntu Core”，I've tried another distro “ubuntu server”,everything works fine~8D

**Comment by ktsaou** [comment]
Too late reply, but you can always install the static built of netdata. That package requires just a linux kernel.
