### ISSUE TITLE
Expose Netdata Slave Metrics on Master REST API Endpoint Override Option

### ISSUE THREAD

**Issue by jeremyjpj0916** [firehol/netdata#3359]
Hey @ktsaou , we spoke on gitter chat and you said to make a git issue and you would try to help me out so I will post a short synopsis of my problem and what options there are and what option is my personal favorite.

So Master/slave behavior for exposing data in Netdata is like so currently:
```
https://netdatamaster.com/api/v1/allmetrics?format=prometheus
https://netdatamaster.com/host/{netdata-slave-hostname}/api/v1/allmetrics?format=prometheus
```

This is a problem for any cloud based deployment because it makes it impossible to have Prometheus scrape 1 restful API to get all the data about master and slave nodes at the same time. And the real deal breaker for me is {netdata-slave-hostname} is random and not predictable, OpenShift is our cloud manager and it generates a random hostname like myapp-dx9f83d so the last portion is always random and I am constantly doing bounces and redeployment so it is always changing. Therefor I cannot scrape any slave data from an off the cloud Prometheus server.

I can think of two options that would help out people in my situation:

Option 1. Create an override on the netdata.conf file in global or web(wherever you think is more appropriate) that lets me override the default behavior and expose slave data on just the master endpoint(https://netdatamaster.com/api/v1/allmetrics?format=prometheus) 
Where slave data will expose on the masters rest API page like so as an example:
```
netdata_{netdata-slave-hostname}_ipv4_tcpofo_packets_persec_average
```
This option ^ would be the easiest for me to work with.

Option 2. Create an API call that responds with all hosts that are present and active streaming data to Netdata currently(I say active because I have noticed even after a slave that sent data briefly gets taken offline is in the registry permanently even if I took it offline, I think getting ones that have sent data in the last few minutes is a better implementation for the API so I don't try to scrape paths that don't have active data), then I can write my own program to call that endpoint, get the hosts and update my Prometheus TARGET endpoints to include the ones netdata master reports exists. This is my least favorite option because it means more complex logic on my side. I actually still see value in option 2 as well though so I think doing both features could really extend netdata's abilities. 

Let me know your thoughts here!
Thanks,
-Jeremy

**Comment by ktsaou** [comment]
Ok, let me try to add option 1 into netdata.

btw, option 2 is already there. Call `/api/v1/charts` and at the end you will find:

```
"hosts": [
		{
			"hostname": "box"
		},
		{
			"hostname": "server1"
		},
		{
			"hostname": "server2"
		}
	]
```

The above is a list of the hosts currently streaming metrics to this master netdata. The first is always self.

**Comment by ktsaou** [comment]
ok, this is embarrassing. Option 1 is already in netdata:

```
http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus_all_hosts
```

**Comment by ktsaou** [comment]
And it is documented: https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus#streaming-data-from-upstream-hosts

So, this is done. Both your options are already in netdata.

**Comment by jeremyjpj0916** [comment]
Not embarrassing my friend, this is great news! And it is my fault, I should have seen it because I have looked over that page but at the time when I first implemented Netdata I was not using your awesome master/slave logic so I wrongly assumed when I looked at the base http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus and saw only my master metrics that that was all I could get on one rest endpoint. But to be specific on the REST endpoint:
``` 
/api/v1/charts
```
I am noticing some buggy behavior. Take a look, this is about 10 minutes after I have killed kong-29 box and brought up a kong-30 box. The host count reports 3 hosts, the old one that has been dead for 10 mins is still on the hosts list even though its not active streaming currently but also the REST endpoint is not reporting the newest and latest host(kong-30):

![possiblehostsbug](https://user-images.githubusercontent.com/31913027/35486984-22b5ea74-0444-11e8-8680-1423784f40b3.png)

![allhostsincludingold](https://user-images.githubusercontent.com/31913027/35486989-2832c828-0444-11e8-85c0-e5ae8f92d7f7.png)

Other than the above problem ^, the netdata prometheus_all_hosts tag seems to be the answer I was looking for. @ktsaou  let me know your thoughts on the above problem, maybe a bug in the refresh logic of the API and active hosts? Should be reproducible:

1. Create a master
2. Create a slave streaming data to master
3. Kill the slave and startup a new slave with different hostname
4. Watch as the GUI has the new host, the integer value on the api reports 3 nodes now, but the actual list of hosts only has the master and the old killed slave, not the new active running slave which is what we want(at discard the old slave no longer streaming data since its inactive).

Thanks,
Jeremy

**Comment by ktsaou** [comment]
hm... something else is happening.
The UI uses this exact array to build the menu... Probably your browser has cached the result. Can you check?

**Comment by jeremyjpj0916** [comment]
I took a look, you are right, my browser client must be doing some caching. But the host array still contains hosts that are not active streaming:
```
   "hosts":    [
      {"hostname": "netdata-27-g55mh"},
      {"hostname": "kong-32-tuymi"},
      {"hostname": "kong-31-m3pes"}
   ]
```
How long does it take before a slave that has not streamed any data in a certain amount of time gets purged from the master? I would only want kong-32 at this stage, kong-31 is gone and never coming back hah. Seems netdata will hold that old host indefinitely since it sent metrics at some point in the past. Maybe an override in the netdata.conf could be made that allows a purge of old hosts after a few mins of inactivity has occurred? Active streaming slaves are what I want an array of. All my slaves will be kong-number-*some hash* so I can parse those out, but the inactive one being left there is kinda a problem because on a web dashboard i am building I want to only have current active slaves in my drop down.

**Comment by ktsaou** [comment]
> How long does it take before a slave that has not streamed any data in a certain amount of time gets purged from the master?

```
[global]
	# cleanup obsolete charts after seconds = 3600
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes
```

`cleanup obsolete charts after seconds` for charts that are marked obsolete (removed mount points, removed network interfaces, disks, etc)

`cleanup orphan hosts after seconds` for disconnected hosts

**Comment by jeremyjpj0916** [comment]
Ah so 1 hour defaults, that might be the issue then, I think I will set that to 5 minutes or so and retest. Will post back with my findings then we can close this issue :) ! Still working through that statsD issue I raised and will comment back on progress there too. 

Thanks!
-Jeremy

**Comment by jeremyjpj0916** [comment]
Update: The changes worked! Once set to 5 mins I was able to watch the old stagnant slave drop off. Wow thats super cool. We can close this topic. Thanks again!
