### ISSUE TITLE
SNMP interfeis name from id  ?

### ISSUE THREAD

**Issue by dzaczek** [firehol/netdata#3362]
Hi  
I m using snmp on my router Asus rt66nu  with standard example config.
But there name interfaces are very ugly . Any one know how to setup 
interfaces title value from oid .
1.3.6.1.2.1.2.2.1.2.1 <- name for interface is the second to last number=2 , last number number interface 

example now Title for plot is 
"Router-Honkong Bandwidth for port 2" 
i would like :
"Router-Honkong Bandwidth for port eth1" 
example names from oid:
➜  ~ cat testsnmp.txt | egrep  '1\.3\.6\.1\.2\.1\.2\.2\.1\.2\.[1-9]'                             
.1.3.6.1.2.1.2.2.1.2.1 = STRING: lo             
.1.3.6.1.2.1.2.2.1.2.2 = STRING: eth0           
.1.3.6.1.2.1.2.2.1.2.3 = STRING: eth1           
.1.3.6.1.2.1.2.2.1.2.4 = STRING: eth2           
.1.3.6.1.2.1.2.2.1.2.5 = STRING: vlan1          
.1.3.6.1.2.1.2.2.1.2.6 = STRING: vlan2          
.1.3.6.1.2.1.2.2.1.2.7 = STRING: br0            
.1.3.6.1.2.1.2.2.1.2.8 = STRING: imq0           
.1.3.6.1.2.1.2.2.1.2.9 = STRING: imq1 

My config 

> {
>     "enable_autodetect": false,
>     "update_every": 10,
>     "servers": [
>         {
>             "hostname": "xxx.xxx.xxx.xxx",
>             "community": "public",
>             "update_every": 10,
>             "options": { "timeout": 20000 },
>             "charts": {
>                 "snmp_switch.bandwidth_port": {
>                     "title": "Router-Honkong Bandwidth for port ",
>                     "units": "kilobits/s",
>                     "type": "area",
>                     "priority": 1,
>                     "family": "ports",
>                     "multiply_range": [ 1, 9 ],
>                     "dimensions": {
>                         "in": {
>                             "oid": "1.3.6.1.2.1.2.2.1.10.",
>                             "algorithm": "incremental",
>                             "multiplier": 8,
>                             "divisor": 1024,
>                             "offset": 0
>                         },
>                         "out": {
>                             "oid": "1.3.6.1.2.1.2.2.1.16.",
>                             "algorithm": "incremental",
>                             "multiplier": -8,
>                             "divisor": 1024,
>                             "offset": 0
>                         }
>                     }
>                 }
>             }
>         }
>     ]
> }

**Comment by ktsaou** [comment]
Well, you should add `titleoid`, just below `title`. You will get this:

![image](https://user-images.githubusercontent.com/2662304/35830142-ec276c18-0acd-11e8-84cb-795c6e7f32c8.png)

It is documented here: https://github.com/firehol/netdata/blob/master/conf.d/node.d/snmp.conf.md#retreiving-names-from-snmp
