### ISSUE TITLE
Add custom label for prometheus export

### ISSUE THREAD

**Issue by andreioss** [firehol/netdata#3364]
Hello,
It would be usefull, to have an opportunity to add custom label=value pairs to every metric that exporting to prometheus via api/v1/allmetrics?format=prometheus.
Use case - I have large number of hosts, that belonged to different types (groups), and if I can add such identification to every metric on every host, then it would be very convenience to group them in grafana dashboards for example.
Now for me there are only two ways:
1. Doing some cumbersome relabeling in the prometheus job
2. Group hosts by placing them in different sd-fd-config files and then - different job names reflecting its groups.

**Comment by londonowl1973** [comment]
# Debian / Ubuntu
apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl

# Fedora
dnf install zlib-devel libuuid-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils

# CentOS / Red Hat Enterprise Linux
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm-sensors make MySQL-

**Comment by andreioss** [comment]
Sorry, what is it?

**Comment by ktsaou** [comment]
@andreioss I think @londonowl1973 is by mistake.

What you need is already in netdata. Edit `/etc/netdata/netdata.conf` and set 👍 

```
[backend]
	host tags = XXX
```

Keep in mind that `XXX` should be written in the format expected by prometheus. netdata will add to the response, exactly the way it has been given to it: https://github.com/firehol/netdata/blob/fdd6bb81af362b2bcf563f61e62124f8dfc8e843/src/backend_prometheus.c#L114

So, for prometheus use something like `key1="value"1,key2="value2"`.

**Comment by andreioss** [comment]
Thanks @ktsaou, but therefore needed some clarification on this info - https://github.com/firehol/netdata/wiki/netdata-backends:

> Host tags = TAG1=VALUE1 TAG2=VALUE2 ... defines tags that should be appended on all metrics for  the given host. These are currently only sent to opentsdb. Host tags are mirrored with database replication (streaming of metrics between netdata servers).

Only opentsbd? Is it implied Prom support or not?

And this option add new metric for host with specified values, but I meant - add custom labels to every metric, that exported by netdata, though it seems current behavior suitable to me too, so thanks for the help!

**Comment by ktsaou** [comment]
> Only opentsbd? Is it implied Prom support or not?

I updated it:

- `host tags = list of TAG=VALUE` defines tags that should be appended on all metrics for the given host. These are currently only sent to opentsdb and prometheus. Please use the appropriate format for each time-series db. For example opentsdb likes them like `TAG1=VALUE1 TAG2=VALUE2`, but prometheus like `tag1="value1",tag2="value2"`. Host tags are mirrored with database replication (streaming of metrics between netdata servers).

---

> And this option add new metric for host with specified values, but I meant - add custom labels to every metric, that exported by netdata,

This was a choice of the prometheus maintainers. I wanted to send them on every metric, but they suggested it is faster / more efficient to do it with host tags.

**Comment by KarthikRangaraju** [comment]
> I wanted to send them on every metric, but they suggested it is faster / more efficient to do it with host tags

This is based on the assumption that there will be a Prometheus server PER group. For example: If I had two environments DEV & PROD & had a prometheus server for each.  

A prometheus server in DEV would scrape VMs running netdata agents in DEV and we could leverage the "external_labels" at the prometheus server level to attach "environment: DEV" for all netdata metrics in DEV. 

But the moment we have a single prometheus server scraping netdata agents across multiple different groups, it's not possible anymore to differentiate :( This is why it'd be useful to send the custom labels per metric instead.

This will give us more freedom to slice and dice metrics by diifferent groups, visualize them, alert them, scrape them independently. What not.
