### ISSUE TITLE
systemd-nspawn containers

### ISSUE THREAD

**Issue by cyayon** [firehol/netdata#3367]
Hi,

I am trying to monitor my systemd-nspawn container. Of course, i have enabled accounting in systemd and systemd-cgtop  shown me correct tree. 
/etc/systemd/system.conf :
DefaultCPUAccounting=yes
DefaultIOAccounting=yes
DefaultBlockIOAccounting=yes
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes

I have tried to configure netdata.conf:
[plugin:cgroups]
check for new cgroups every = 10
path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices

Netdata show me only cpu, mem and disk in web interface. I would like to show each machine.slice/<container>.service, Is it possible ?

Thanlks

**Comment by ktsaou** [comment]
So, you want netdata to walkthrough the services running inside the container... nice request...

No, it is not there, but I really like this.

I have never used systemd-nspawn. Can you suggest a nice guide to help me get familiar with it? I need a test environment to make this happen...

**Comment by cyayon** [comment]
Hi,

Thanks for your answer.

Firstly, i would like to see usage (CPU/Mem/io) of each container, not processes inside. 
Of course, if i could obtain stats of inside containers, it will be better...
If think after reading netdata docs it’s already possible, I am certainly doing something wrong...

I have no specific guide of nspawn, but it use cgroups namespace as lxc/lxd. 

Thanks

--
Christophe Yayon

**Comment by cyayon** [comment]
For example, i have 2 nspawn containers : baley and edgar. Here is the tree of /sys/fs/cgroup.

How could i configure netdata to identify the cpuacct of these 2 machine.slice ?

thanks

# systemd-cgtop  | grep -E "edgar|baley"
/machine.slice/baley.service                                           18      -   180.2M        -        -
/machine.slice/edgar.service                                           81      -   430.0M        -        -

# find  /sys/fs/cgroup/cpuacct/ |grep -E "baley|edgar"
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpu.stat
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.stat
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cgroup.clone_children
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_percpu_sys
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_user
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_percpu_user
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_percpu
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpu.cfs_period_us
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpu.cfs_quota_us
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/tasks
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/notify_on_release
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpu.shares
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cgroup.procs
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_sys
/sys/fs/cgroup/cpuacct/machine.slice/edgar.service/cpuacct.usage_all
/sys/fs/cgroup/cpuacct/machine.slice/baley.service
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpu.stat
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.stat
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cgroup.clone_children
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_percpu_sys
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_user
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_percpu_user
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_percpu
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpu.cfs_period_us
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpu.cfs_quota_us
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/tasks
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/notify_on_release
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpu.shares
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cgroup.procs
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_sys
/sys/fs/cgroup/cpuacct/machine.slice/baley.service/cpuacct.usage_all

**Comment by ktsaou** [comment]
hm... this is just configuration in netdata.conf:

```
[plugin:cgroups]
    enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  * 
```

The above disables `*.service`, so add at the beginning `machine.slice/*.service`, remove the comment and restart netdata.

If it works, please post a screenshot of the menu. We may also need to remove `.service` from their names.

**Comment by cyayon** [comment]
Hi,

Perfect ! 
But how could i remove .service from their names ? Is it a netdata params ?
Could i have processes from container too ? like apps on host ?

Thanks

![netdata](https://user-images.githubusercontent.com/16900507/35688341-41d9c97c-0771-11e8-95c1-90fabb0c2766.png)

**Comment by ktsaou** [comment]
let me make a PR to fix both issues:

1. allow `machine.slice/*.service`
2. fix the name

**Comment by ktsaou** [comment]
And I see another issue: netdata could not find the network interface of the containers. Does systemd-nspawn add a network interface per container? Can you post a screenshot of the "Network Interfaces" menu?

**Comment by ktsaou** [comment]
PR #3382 - should enable the systemd-nspawn containers by default and should also rename them.

**Comment by ktsaou** [comment]
merged it.

Please post the screenshot of your network interfaces so that we can check what is missing there.

**Comment by cyayon** [comment]
There is an interface for each container. Named « vb-<container name> ». I can see them on interfaces menu list, no problem. I can’t post screenshot for now...

--
Christophe Yayon

**Comment by ktsaou** [comment]
ok thanks.

On your network interfaces there will be a list of course. But the interface of each container should appear with the container, like this:

![screenshot from 2018-02-02 23-16-14](https://user-images.githubusercontent.com/2662304/35755266-38b0e048-086f-11e8-828a-f8f705dde52d.png)

netdata should be able to find the container each interface belongs to, on kernel v4+. Unfortunately on older kernels this is problematic.

**Comment by cyayon** [comment]
Ok, there no interface inside the container. Only on host.

Inside the container, the interface is name « host[0-9]+ » like eth*.


--
Christophe Yayon

**Comment by cyayon** [comment]
Hi, 

be carefull, i had to include /machine.slice/*.service (with a begininh '/') in netdata config file. Without '/' i had no container check.

enable by default cgroups matching =  /machine.slice/*.service !*/init.scope  !/system.slice/run-*.scope !/system.slice/*.socket *.scope  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker
 !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  *

**Comment by ktsaou** [comment]
> be carefull, i had to include /machine.slice/*.service (with a begining '/') in netdata config file. Without '/' i had no container check.

I missed that comment somehow.
Making a PR now.

**Comment by ktsaou** [comment]
In PR #3425

**Comment by cyayon** [comment]
Thanks

--
Christophe Yayon
