### ISSUE TITLE
get host list using api

### ISSUE THREAD

**Issue by dsaydon90** [firehol/netdata#3368]
Hi,

I'm trying to implement a dynamic dashboard so it will add all the hosts that I added "ephemeral monitoring" using loop

I couldn't find a way to get all of the hosts list that the netdata master is keeping. there is a way to get the hosts list using api?

For example:
![image](https://user-images.githubusercontent.com/22152786/35564121-bde1c58a-05c1-11e8-9ef3-3bb38de13d03.png)

**Comment by ktsaou** [comment]
At the end of the `/api/v1/charts` you will find the list of hosts you need.

**Comment by dsaydon90** [comment]
Thanks a lot!
this give me what I need:
`curl http://netdata_url:19999/api/v1/charts | jq .hosts`
