### ISSUE TITLE
Monitor SSH failed authentication

### ISSUE THREAD

**Issue by Yaser-Amiri** [firehol/netdata#3370]
Hi, I wrote a module to monitor failed ssh login attempts. Do you have desire to add it to Netdata?
It's so simple but very useful. It has an unusual thing! It needs to adding netdata user to adm group (to get read access for /var/log/auth.log)
Would you prefer this in the core or as a stand-alone?

**Comment by l2isbad** [comment]
> adding netdata user to adm group (to get read access for /var/log/auth.log)

[already there](https://github.com/firehol/netdata/blob/master/installer/functions.sh#L810)

**Comment by Yaser-Amiri** [comment]
So it can't work on CentOS at least! I don't like that my Monitoring system takes admin perms.
Is there any packaging regulation for Netdata modules? I think it's better to create a stand-alone package.

**Comment by l2isbad** [comment]
create module
@
modify [wiki page](https://github.com/firehol/netdata/wiki/Third-Party-Plugins)

**Comment by Yaser-Amiri** [comment]
I added it to Wiki. Thanks.
