### ISSUE TITLE
No more exemple for Java processes ? 

### ISSUE THREAD

**Issue by CorentinDy** [firehol/netdata#3374]
Hi, 
i'm wondering if those exemple for jmx java processes are still available somewhere else ? 

https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#java-processes

thx

**Comment by ktsaou** [comment]
@simonnagl please check this.

**Comment by simonnagl** [comment]
Hello, I am currently working on a java plugin with JMX module at #2663. If you install this branch all your java processes should show up on the dashboard.

What do you mean with examples? If you need any help just ask.

**Comment by CorentinDy** [comment]
Sorry, the project don't use anymore netdata, but thank's for the anwsers !
