### ISSUE TITLE
Seeking advice: Multiple customers, multiple servers per customer, multiple jump boxes, single dashboard

### ISSUE THREAD

**Issue by mmikitka** [firehol/netdata#3375]
Firstly: you are doing excellent work with Netdata. I'm very impressed.

Can you please advise on "best practices" to solve the following problem with Netdata?

* A single dashboard within the corporate network which gathers health information from all servers on all customers
* Multiple customers
* There are 50-200 servers/customer
* It takes 3-5 SSH hops to reach any given server (VPN access required)
* The individual servers do *not* have outbound Internet access and cannot push data
* The corporate aggregation dashboard would pull alarms and measurement data from all the customers
* The corporate aggregation instance would push alarms
* From the corporate aggregation instance, I can directly access Netdata on an individual server

I found the following articles, but I'm not sure where the limitations lie at a system level:

* Use Nginix for proxying through the networks (the 3-5 hops problem): https://github.com/firehol/netdata/wiki/Running-behind-nginx
* Create a registry in the corporate network: https://github.com/firehol/netdata/wiki/mynetdata-menu-item
* Customize the dashboard: https://github.com/firehol/netdata/wiki/Custom-Dashboards#

I am unsure about the following:
* Limitations of the Nginix solution for proxying through networks
* Whether alarm aggregation (pulling) is possible
* Whether pushing alarms from the aggregation instance is possible
* Whether the Netdata registry can auto-populate entries to avoid accessing the servers individually

Thank you for your time and effort.

**Comment by ktsaou** [comment]
Well, you have many options. For example:

1. Run a standalone netdata per server and access them directly via an nginx or a hierarchy of nginx (eg. one nginx accesses all netdata directly, or one master nginx accesses one slave nginx per customer which accesses all the netdata directly). This is the simplest, does not stream any metrics and each server is standalone (both dashboard and alarms). You can aggregate alarms by email, slack, alerta, pagerduty, etc.

2. Run a standalone netdata per server, and provide an nginx per customer that will provide authentication and SSL for all netdata of the customer. This means you can share access with your customer to his nginx.

3. Run a headless slave netdata per server (without alarms) and have a master netdata per customer. So all servers of a customer will be streaming metrics to the customer master netdata (within the customer setup). This again will need an nginx per customer (SSL and authentication), but you can now centralize all the alarms configuration at this server.

4. Like 3, but the master netdata per customer, will actually be a slave of your super-master netdata at HQ that aggregates metrics from all servers of all customers. This setup allows you to have different alarms and data retention policies centrally.

As you can see, netdata is generally quite flexible in this area.

I would base this decision based on the following:

1. netdata masters may require dedicated resources (depending on the size of the db you need - mainly RAM - the CPU will be ignorable even if you stream 200 slaves to a master).

2. Do you need to archive the metrics to time-series dbs?

3. Do you need to share access to netdata with your customers?

4. Are there any bandwidth restrictions / limitations?

5. Do you run a corporate portal or wiki? I have found that embedding monitoring there is ideal for all employees - and netdata can do it if you don't require authentication for accessing the dashboards (or if you share authentication with the wiki / portal).

Keep in mind a hierarchy of slave -> proxy -> master netdata will allow you to have:

   i. different alarms at different levels - so, the slaves may have no alarms at all, but the customer master may run a set of alarms for all the netdata of the customer and your super-master netdata may run another set of alarms for the entire infrastructure. Generally, alarms can be configured at any level - they are propagated - each netdata runs its own alarms for all the hosts it monitors.

  ii. different registries - this is useful if your customers will also be accessing their netdata servers.

  iii. different time-series databases for you and your customers. For example, a customer of yours may require time-series metrics to a graphite and another to opentsdb, while you use prometheus - a hierarchy of netdata allows you to do this.

Of course, streaming netdata metrics requires 100 - 150 kbps per server (lot's of metrics).

**Comment by mmikitka** [comment]
Much appreciated @ktsaou 

For those looking for more implementation details, in addition to the links that I posted in the first comment, see https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes
