### ISSUE TITLE
grafana dashboard for netdata via graphite

### ISSUE THREAD

**Issue by chaoyongzhou** [firehol/netdata#3376]
I want to setup a historic data monitor based on stack netdata + graphite + grafana. Seems no suitable grafana dashboard for netdata. 

Grafana dashboard 1295# is based on stack netdata + influxdb + grafana.

**Comment by chaoyongzhou** [comment]
ok, I made it. 

I published a grafana dashboard 4562# which is indeed coming from 1295#.

**Comment by chaoyongzhou** [comment]
Moreover, I upload the dashboard to repository: 
https://github.com/chaoyongzhou/grafana-dashboards

Any modification is welcome and free.

Enjoy!

**Comment by ktsaou** [comment]
nice. thank you for sharing.
