### ISSUE TITLE
Spikes in system.swap metric in LXC container

### ISSUE THREAD

**Issue by davidmehren** [firehol/netdata#3380]
I have an LXC container running on a Proxmox 5.1 host and noticed these spikes in swap usage:
![image](https://user-images.githubusercontent.com/5023650/35737025-6e18105c-082a-11e8-84d5-9a349cc1eaac.png)
Other tools like htop or the swap usage meter in Proxmox don't show these spikes, so I suspect that there's something wrong with netdata collecting the data?

**Comment by davidmehren** [comment]
I just resized the browser window a bit and the graph changed:
![image](https://user-images.githubusercontent.com/5023650/35737407-a57c5fd4-082b-11e8-8490-df127d998bcc.png)
So this might just be some kind of visual glitch?
I sometimes get warning emails for system.swap though...

**Comment by ktsaou** [comment]
> So this might just be some kind of visual glitch?

no. The value on the chart changes depending on the number of seconds aggregated per point on your screen. On your second chart, netdata shows the average of 2 seconds per point, so the spikes are half the size. You can see the aggregation period by hovering on the time above the legend of the chart.

netdata calculates swap used from `/proc/meminfo` using a very simple calculation: https://github.com/firehol/netdata/blob/75426841ffd5077dfb4c811880442818e6c2fed9/src/proc_meminfo.c#L211

`SwapTotal` and `SwapFree` are reported by the kernel:

```sh
# cat /proc/meminfo  | grep ^Swap
SwapCached:            0 kB
SwapTotal:      16400380 kB
SwapFree:       16400380 kB
```

I see in the code that netdata assumes the units are always `kB`, so this can be an issue if we find that the kernel swaps units under conditions.

I see on your screenshots, this is quite frequent. Could you please run this:

```sh
watch -n 1 'cat /proc/meminfo  | grep ^Swap'
```

and at the same check what netdata reports. Keep in mind that if the kernel changes the value for a fraction of second you may not be able to spot it like that. Try changing `-n 1` to `-n 0.5` or lower to get more frequent updates.

**Comment by ktsaou** [comment]
I found one of my server doing the same. Here is the funny kernel swap reporting:

![funny-swap](https://user-images.githubusercontent.com/2662304/35754244-75aad124-086b-11e8-8d1e-ab8f007cdd38.gif)

I'll make the alarm send notifications after the alarm is triggered for 30 seconds.

**Comment by ktsaou** [comment]
merged it
