### ISSUE TITLE
Add support for ARM64 Docker container

### ISSUE THREAD

**Issue by JasonSwindle** [firehol/netdata#3384]
Howdy,

It would be great to support an ARM64 container. Currently there is a container that support armhf, but more and more SBC are ARM64.

Thanks,
Jason

**Comment by ktsaou** [comment]
hm... the change seems simple.
can you make a PR?

@justin8 can you help?

**Comment by justin8** [comment]
Yeah, should be easy enough. I don't have an arm64 device to test on however.

@JasonSwindle do you know of a docker image with cross-compilation support for arm64? I wouldn't want to build it myself without at least that part being tested on a real device

**Comment by justin8** [comment]
Reading up a little more, it seems aarch64 would probably suffice for most SBCs? `arm64` as an architecture seems to be mostly Apple devices.

Making one for aarch64 would be trivial. I'll push a CR in a bit

**Comment by ktsaou** [comment]
done - docker hub is updated!
Thank you @justin8 !

**Comment by justin8** [comment]
@ktsaou No problem!
