### ISSUE TITLE
Disable all plugins, but whitelist custom plugins

### ISSUE THREAD

**Issue by ccremer** [firehol/netdata#3385]
Hi, it's me again ;)

Is there an easy way to disable all the systems plugin and only enable very specific ones?
I'm thinking about Dockerizing a minimal netdata installation that enables only the ones I need. In my case I need the fronius and stiebeleltron plugins with an influxDB backend for archiving. All the others (CPU, etc) can be left disabled.
Thoughts?
Thanks.

**Comment by ktsaou** [comment]
ok, it is not a single line, but here is how to do it:

1. `/etc/netdata/netdata.conf` at the `[plugins]` section disable all, except `python.d`.
2. `/etc/netdata/python.d.conf` disable the ones you don't need.
