### ISSUE TITLE
When using exec, email alerts are not sent

### ISSUE THREAD

**Issue by pestevao** [firehol/netdata#3392]
Hello,

I have configured a health check to execute a script but sent a email alert too like:

      (...)
      to: xpto
    exec: /path/to/my/script

But this only execute the script and does not sent any email.
Is this the expected behaviour?

Thank you, Pedro

**Comment by ktsaou** [comment]
yes. You can however call the default `alarm-notify.sh` script to dispatch the standard notifications.

So, from your `exec` script, run:

```sh
#!/usr/bin/env bash

# call the standard dispatch
${NETDATA_PLUGINS_DIR}/alarm-notify.sh "${@}"

# do whatever else you like
...

```

**Comment by ktsaou** [comment]
I am closing this, but you can still post.
