### ISSUE TITLE
system.uptime in LXC container

### ISSUE THREAD

**Issue by skyxx** [firehol/netdata#3393]
Hi All. First I want to thanks for your great work on this project.

Im running netdata inside LXC container (using LXD 2.21 on Ubuntu 16.04.3) and the **system.uptime** value returning uptime for host server where container running and not for container itself.
Maybe i missing something in settings or its a bug ?

Thanks.

**Comment by ktsaou** [comment]
Hi, thanks.

This is interesting. The kernel reports inside the containers the host uptime, not the container uptime. I guess the same is reported by the `uptime` command. Can you check?

**Comment by skyxx** [comment]
Hi ktsaou. uptime and also /proc/uptime shows correct value inside container. 
In which way netdata getting uptime value ? It can be LXC bug.

**Comment by ktsaou** [comment]
netdata reads `/proc/uptime`: https://github.com/firehol/netdata/blob/364c4fa2de20eb6ccb60256ce94c34835b79cb0f/src/proc_uptime.c#L15

**Comment by ktsaou** [comment]
Could you please check the contents of `/proc/uptime` inside the container and at the host ?
netdata uses the first of the 2 numbers in that file.

**Comment by skyxx** [comment]
Contents look okay .. :

[root@test]# uptime
 10:04:02 up 5 min,  0 users,  load average: 0.21, 0.14, 0.10
[root@test]# cat /proc/uptime
359.00 351.00

but graph shows uptime 6d:19:56:22

I will open issue on LXD git to get more info and check.

**Comment by ktsaou** [comment]
If `/proc/uptime` shows the correct uptime, it is not a problem of lxd.

Could you please post this from the container:

```sh
curl -s http://localhost:19999/netdata.conf | grep 'host access prefix'
```

**Comment by skyxx** [comment]
Result is below. I try also prometheus_node_exporter and it also report wrong uptime.

[root@test]#  curl -s http://localhost:19999/netdata.conf | grep 'host access prefix'
        # host access prefix =

**Comment by ktsaou** [comment]
So, you say that when you do `cat /proc/uptime` you see the correct uptime, but when netdata or prometheus_node_exporter read it, they read the uptime of the host?

**Comment by skyxx** [comment]
exactly.
and i dont understand how it is possible.

**Comment by skyxx** [comment]
sorry i forgot post value from both .. here are they:

HOST:
[root@lxd298p]# cat /proc/uptime
592268.99 1177987.48

CONTAINER:
[root@test]# cat /proc/uptime
2640.00 2600.00

**Comment by ktsaou** [comment]
hm... I don't know how to help you with this. netdata reads `/proc/uptime` and it does not process it at all, so a netdata running inside the container should present whatever `/proc/uptime` says.

If anyone has any idea what is happening, please post.

**Comment by skyxx** [comment]
I wrote to lxcsfs guys and they do analysis and say that time in /proc/uptime in container is ok. So Netdata dont read it.

When we look at code in netdata/src/proc_uptime.c at line 8
```
#ifdef CLOCK_BOOTTIME_IS_AVAILABLE
     uptime = now_boottime_usec() / 1000;
#else
```
Looks like /proc/uptime is not read because CLOCK_BOOTTIME_IS_AVAILABLE is set to 1 so 
uptime = now_boottime_usec() / 1000;

**Comment by ktsaou** [comment]
I should have looked better - and I should buy them a beer for doing my work...

In PR #3437 
Now it uses `now_boottime_usec() / 1000` only when the time difference with /proc/uptime is less than a second. So, the first time it is collected it checks if they match. If they do it uses `now_boottime_usec() / 1000`, otherwise it uses `/proc/uptime`.

Thank you!

**Comment by ktsaou** [comment]
merged it!
Again, many thanks for tracking this down...

**Comment by jtp10181** [comment]
I think this CLOCK_BOOTTIME_IS_AVAILABLE thing is possibly affecting my setup as well. I have checked my /proc/uptime and it looks fine, but my uptime is always shown as 0. Is there any way for me to check how netdata is getting the uptime? I think in order to test your fix I would need to compile netdata myself? It is currently installed from a package (running on an embedded system, a router).

```
cat /proc/uptime
30904.19 45094.16
```

**Comment by ktsaou** [comment]
> I think in order to test your fix I would need to compile netdata myself

I am afraid so... I hope I will release v1.10 in a few days, so the maintainers of that package may update it...

**Comment by ktsaou** [comment]
However, if `CLOCK_BOOTTIME` is broken and reports zero all the time, many many more things would break. netdata uses it for a ton of things.

Can you upload a snapshot? (not a screenshot, but a netdata snapshot - from the navigation bar). Put it in a `.zip` and attach it to a comment here.

**Comment by jtp10181** [comment]
Here you go.
[netdata-RT-AC56R-3B98-20180308-191558-720.zip](https://github.com/firehol/netdata/files/1795346/netdata-RT-AC56R-3B98-20180308-191558-720.zip)

**Comment by ktsaou** [comment]
strange indeed. Everything else seems normal...
