### ISSUE TITLE
Many mails 

### ISSUE THREAD

**Issue by gamersalpha** [firehol/netdata#3399]
i rreceived so many mail like that : 

```
`

net_packets.eth0                                             Chart
--
inbound packets dropped ratio (was warning for 10 minutes) the  ratio of inbound dropped packets vs the total number of received  packets of the network interface, during the last 10 minutes                                             Alarm
eth0                                             Family
Recovered from WARNING                                             Severity
Wed Feb  7 18:28:01 CET 2018                                             (was warning for 10 minutes)

`
```

```
net_packets.eth0                                             Chart
--
inbound packets dropped ratio = 0.2% the  ratio of inbound dropped packets vs the total number of received  packets of the network interface, during the last 10 minutes                                             Alarm
eth0                                             Family
WARNING                                             Severity
Wed Feb  7 14:38:01 CET 2018                                              Time


```

i receiveid so many alamr like this, can u explain me please ?

**Comment by jefft** [comment]
netdata is exceptionally noisy. Here is my inbox after a night when my desktop happened to be left running: 
![image](https://user-images.githubusercontent.com/205995/35947440-01ba109a-0cbc-11e8-9a48-3dfda8a4949a.png)

Netdata on production servers behaves fine (in my experience) but it is all but unusable on desktops. I wish netdata had some feedback mechanism for learning what "normal" is on a particular instance. Perhaps a "reduce alarm sensitivity by 20%" link in alerts?

**Comment by ktsaou** [comment]
@jefft you are right, netdata alarms are tuned for servers, not desktops.

A simple solution is to disable emails (edit `/etc/netdata/health_alarm_notify.conf` and set `SEND_EMAILS="NO"`).
