### ISSUE TITLE
development progress

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#34]
1. I have developed a new API for netdata. The new one supports multiple output formats:

 - JSON
 - JSONP
 - Complete Google Visualization API support (https://developers.google.com/chart/interactive/docs/dev/implementing_data_source) (without the query language of course - just the data format exports)
 - CSV
 - TSV (tab separated)
 - SSV (space separated values - not CSV like, more like "just a bunch of values": JBOV)
 - HTML

 I'll build a swagger document to describe it.

2. I have developed javascript code to allow building dashboards using multiple chart engines:

 - google charts
 - dygraph.com
 - sparkline.js
 - peity.js
 - morris.js

3. Dashboards can now have charts from multiple netdata servers. This means that if you have installed netdata on many machines in a datacenter, you can build dashboards with charts from multiple servers (e.g. compare the disk I/O of one, with cpu utilization of another, with requests/s of a third).

 You can see an example dashboard here: http://195.97.5.206:19999/dashboard.html

 As you will see there, `dygraph` is by far the fastest (the page is benchmarking javascript performance of all chart libraries used).

 I have not updated the old UI to use the new dashboard logic yet. This needs some more work. I will also use `dygraph` by default.

@alonbl I have added a few files in the web/ directory. I have modified `Makefile.am` but I am not sure I did it right (I added a few directories - shall we add Makefile.am to each?).

@philwhineray, delay a bit the release of netdata. I need a few more days to update its UI to use the new chart libraries.

**Comment by alonbl** [comment]
please sort items within targets of Makefile.am, this way it is easier to patch these in predictable order.

you probably want:
```
weblibdir=$(webdir)/lib
dist_weblibdir_DATA = \
        lib/dygraph-combined.js \
        lib/dygraph-synchronizer.js \
        lib/jquery-1.11.3.min.js \
        lib/jquery.peity.min.js \
        lib/jquery.sparkline.min.js \
        lib/morris.min.js \
        lib/raphael-min.js \
        $(NULL)
````

or we can add Makefile.am within the lib, no much difference.

what I am more worried about is the licensing, you embed 3rd party sources within your package, which effects the license of your package as well.

**Comment by ktsaou** [comment]
Do you mean to add it to the existing Makefile.am, like this:

```
#
# Copyright (C) 2015 Alon Bar-Lev <alon.barlev@gmail.com>
#
MAINTAINERCLEANFILES= $(srcdir)/Makefile.in

dist_web_DATA = \
        datasource.html \
        index.html \
        index.js \
        netdata.js \
        robots.txt \
        theme.css \
        css/morris.css \
        dashboard.html \
        dashboard.js \
        $(NULL)


weblibdir=$(webdir)/lib
dist_weblibdir_DATA = \
        lib/dygraph-combined.js \
        lib/dygraph-synchronizer.js \
        lib/jquery-1.11.3.min.js \
        lib/jquery.peity.min.js \
        lib/jquery.sparkline.min.js \
        lib/morris.min.js \
        lib/raphael-min.js \
        $(NULL)
```

Regarding the license, you are right.

dygraphs, which is the most interesting, is MIT licensed (https://github.com/danvk/dygraphs/blob/master/LICENSE.txt).

sparklines has a BSD license (http://opensource.org/licenses/BSD-3-Clause)

jquery is also MIT licensed.

I can remove morris.js and raphael.js. They are not needed (yet).

Generally, we can use all of them via a content distribution network, but we have to find a way to install them if the user needs them locally (the whole point of including them is that netdata will be used in situations where the network is down, so CDN is not a good choice). Can we have them downloaded as part of the installation?

**Comment by alonbl** [comment]
I had a mistake: dist_weblibdir_DATA -> dist_weblib_DATA

you can download these during make dist, so they are available within tarball. however, the license impact will be similar as you redistribute them.

**Comment by ktsaou** [comment]
I have seen in gentoo various packages that download additional files during installation. Can we have something like this for netdata?

**Comment by alonbl** [comment]
> I have seen in gentoo various packages that download additional files during installation. Can we have something like this for netdata?

yes, but it makes it harder to use in rpm based environment for example.
better to find a proper dependency if available, I am unsure that in this case there is, so best solution would be to redistribute.

**Comment by ktsaou** [comment]
I have replaced the dashboard of netdata with the new one:

http://netdata.firehol.org/

Regarding the licenses of re-distributed tools, I have mentioned everything in [LICENSE](https://github.com/firehol/netdata/blob/master/LICENSE.md). @alonbl on your experience is this the right way to do it, or we need something more/different?

**Comment by alonbl** [comment]
Looks good!
