### ISSUE TITLE
Container list looks out of place

### ISSUE THREAD

**Issue by ET-Bent** [firehol/netdata#340]
After updating to the latest release (30.04.2016 / 01:37 CEST | Netdata version: 77612636a4c605549f911e4a505c77bb707aaf39) I got this issue:

![auswahl_032](https://cloud.githubusercontent.com/assets/5788982/14932277/31aa1928-0e74-11e6-9af9-a2027c60925f.png)

Is the part in the red box a bug or a feature as this looks a bit out of place? Also clicking on the links in the red box has no effect as they seem to link to nothing,

**Comment by ktsaou** [comment]
I think you have the same problem with #329 .
The fix is ready, but needs some testing. Check this for instructions: https://github.com/firehol/netdata/issues/329#issuecomment-215896279

If you can test it too, please do.

**Comment by ET-Bent** [comment]
@ktsaou Thanks for looking into this. I pulled the latest source from the repo you mentioned in your comment and cleared my log before. This is the error.log I get after running the latest version: http://paste.ee/p/fb3no#bS3oLXNmQ6xFNqL0Tmd3b8Vpo2ir46ye (Netdata: `091a878175eb89ef7923a6c516cb138e2832954e`). The issue stays the same as shown above.

**Comment by ktsaou** [comment]
ok. If I understand correctly your `user.slice` is named `user` and you have containers under `machine`.

Please go to `http://your.netdata:19999/netdata.conf` and paste your `[plugin:cgroups]` here. Mine is this:

```
[plugin:cgroups]
	# cgroups plugin resources = yes
	# check for new cgroups every = 10
	# enable cpuacct stat = on demand
	# enable cpuacct usage = on demand
	# enable memory = on demand
	# enable blkio = on demand
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# max cgroups to allow = 50
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh
	# enable cgroup / = no
```

Please paste yours.

**Comment by ktsaou** [comment]
Which distro, version and kernel version are you using?
I guess every distro has done a few variations on the naming of several cgroup paths and we need to find out the possible ones to provide reasonable defaults for everyone.

**Comment by ktsaou** [comment]
What bothers me though, is that you way the container menus are still non-functional...
ok, one step at a time. Please give me the info requested above, and we will solve this issue later.

**Comment by ET-Bent** [comment]
Here you go:

`
[plugin:cgroups]
	# cgroups plugin resources = yes
	# check for new cgroups every = 10
	# enable cpuacct stat = on demand
	# enable cpuacct usage = on demand
	# enable memory = on demand
	# enable blkio = on demand
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# max cgroups to allow = 50
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# script to get cgroup names = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
	# enable cgroup / = no
	# search for cgroups under / = yes
	# enable cgroup user = yes
	# search for cgroups under /user = yes
	# enable cgroup user/0.user = yes
	# search for cgroups under /user/0.user = yes
	# enable cgroup user/0.user/1.sessio = yes
	# enable cgroup user/0.user/3.sessio = yes
	# enable cgroup user/0.user/2.sessio = yes
	# enable cgroup user/0.user/4.sessio = yes
	# enable cgroup user/0.user/5.sessio = yes
`

`uname -a
Linux 4.5.0-999-generic #201603182201 SMP Sat Mar 19 02:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

`
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
`

Thanks for looking into this! Let me know if you need anything else. If you need to access the panel, we can get this set up too.

**Comment by ktsaou** [comment]
Thanks, in the config you posted there is no `machine` or `windows_10_20` but on your screenshot there are. Are you sure the above is all of it?

I think all these are libvirt related: https://libvirt.org/cgroups.html#currentLayoutGeneric

To hide the user charts set these:

```
enable cgroup user = no
search for cgroups under /user = no
```

I will try to provide reasonable defaults with a PR tomorrow.

Regarding the non-working menu, please do these:

1. Verify the cgroups charts of the non working menu are displayed. Since the menu does not work, just scroll the screen to verify them.
2. If they are there, can you check if you have a javascript error? Press F12 on your browser, and check the console for error message.

**Comment by ktsaou** [comment]
I have merged #344 that attempts disable `user`, `user.slice`, etc
I have noted #345 in or TODO list, since systemd is capable for a lot more.

**Comment by ktsaou** [comment]
In the last 2 days I have submitted a series of patches related to cgroups. Could you please check the latest version and report if it works for you?

**Comment by ktsaou** [comment]
Thanks to @DavidSichau for tracing it at #361 , this has been fixed!

**Comment by ktsaou** [comment]
I am closing this. If the issue remains, please post.
