### ISSUE TITLE
Option to display container name instead of id

### ISSUE THREAD

**Issue by realies** [firehol/netdata#3401]
Would be great to see an option to display docker container names instead of their id.

**Comment by ktsaou** [comment]
This should already work.

Please post the output of:

```
grep cgroup-name.sh /var/log/netdata/error.log
```

**Comment by realies** [comment]
Using Netdata with [this](https://hub.docker.com/r/titpetric/netdata/) container. Noticed it's redirecting the log error log to `error.log -> /dev/stderr`. After close inspection noticed `/var/run/docker.sock` is not mounted. Mounting it resolved the issue. Is there any point to have read/write access to the socket or read only is sufficient?

**Comment by ktsaou** [comment]
> Is there any point to have read/write access to the socket or read only is sufficient?

I am not sure, but normally a request has to be written to the socket, and then the reply is read. So, I think write access is required. Can you try it and report back success or failure?

**Comment by realies** [comment]
@ktsaou, running with read-only permissions since adding the socket mapping. It seems to be resolving container names just fine. Would be interested in knowing why is `r/w` the suggested mapping.
