### ISSUE TITLE
Regular expression log

### ISSUE THREAD

**Issue by fcasco** [firehol/netdata#3403]
I would like to have a module that can be configured to scan a log and send metrics based on some regular expressions. Something like the web_log but more generic, almost like using only the url chart that uses regular expressions to match to urls.

I can write it in Python or Bash but I don't really know where to start, is there any documentation to get me started?

**Comment by l2isbad** [comment]
Hil @fcasco 
https://github.com/firehol/netdata/wiki/How-to-write-new-module
