### ISSUE TITLE
webroot detection error when "printing" behind a proxy ?

### ISSUE THREAD

**Issue by poofyteddy** [firehol/netdata#3410]
Hello, so i'm really learning right now and there is a huge change that the issue is on my part and not on yours, but because it seam weird to me i post it anyway.
I can access netdata interface under /monitoring/, but the print system don't take it in account

## Expected Behavior
When i click on the print button, a new windows should pop leading to `192.168.XXX.XXX/monitoring/##menu_system;theme=slate;help=true;mode=print`

## Current Behavior
When i click on the print button, a new windows pop leading to `192.168.XXX.XXX/##menu_system;theme=slate;help=true;mode=print`

## Context 
i run netdata behind a Apache proxy, here is my config for it :
```
<VirtualHost *:80>
        Redirect "/monitoring" "/monitoring/"
        ProxyPreserveHost ON
                ProxyRequests ON
                ProxyPass /monitoring/ http://127.0.0.1:19999/
                ProxyPassReverse /monitoring/ http://127.0.0.1:19999/

        ErrorLog ${APACHE_LOG_DIR}/monitoring/error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/monitoring/access.log vhost_combined
</VirtualHost>

```
if i chose to export a badge for example, the link i get does contain the /monitoring/

I really don't know if it's a miss configuration of Apache, or something else, and lack the vocabulary to find relevant issue on google.

**Comment by ktsaou** [comment]
yes, this is a bug. thank you for reporting it.

**Comment by ktsaou** [comment]
fix in PR #3412

**Comment by ktsaou** [comment]
merged it!

**Comment by poofyteddy** [comment]
Thank's for the fast fix ^^ i'm glad it wasn't my fault for once
