### ISSUE TITLE
netdata not finding pymongo module [question]

### ISSUE THREAD

**Issue by reagank** [firehol/netdata#3416]
I'm trying to set up mongodb monitoring, and I'm currently receiving the message "Pymongo module is needed to use mongodb.chart.py"

I've installed pymongo globally, and when I open a python repl then I can run "import pymongo" successfully.

When I try to run "/usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb" then I get the error message "Pymongo module is needed to use mongodb.chart.py". Everything looks to be pointing to the same python - the standard installation at /usr/bin/python. Pymongo is definitely installed for that python, and I've checked to make sure that the permissions were set to allow the netdata user to access it. I've also tried installing the pymongo module in /etc/netdata/python.d/python_modules, but that doesn't seem to be recognized.

Is that path the correct place to put the python modules? How can I make netdata find/recognized the installed pymongo? Any help would be appreciated

**Comment by ktsaou** [comment]
hm... I don't know.

@l2isbad any ideas?

**Comment by l2isbad** [comment]
@reagank 
Edit `/etc/netdata/netdata.conf` and set `PYTHONPATH environment variable =`

**Comment by reagank** [comment]
@I2isbad @ktsaou thanks very much for the help. The issue ended up being file permissions for the newly installed modules, although I have no clue why it would work in the python shell and not here. 🤷‍♂️

I also learned in the process that I had the python_modules location wrong - it’s under /usr/libexec/netdata/python.d/ 

The PYTHONPATH variable would also have worked the fix my issue. I was looking for a way to specify a particular python installation for netdata to use and that would be a great way to use a virtual environment for netdata. Thanks again for the help, I think netdata is fantastic!
