### ISSUE TITLE
My

### ISSUE THREAD

**Issue by jonathannz** [firehol/netdata#3427]
I gather my issue is the same as that posted here: https://github.com/firehol/netdata/issues/1588

I was also getting the error, `MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin`.

I installed `python-pip` package, and then did a `pip install PyMySQL` command, as per the instruction on that issue discussion. But I still get the same error.

I am not all that familiar with Python. Is there some command I must run to reload it after adding the `PyMySQL` module to it? I've searched online for information on such, but turned up nothing related to reloading Python.

Please advise.
Thanks.

**Comment by l2isbad** [comment]
duplicate https://github.com/firehol/netdata/issues/3428
