### ISSUE TITLE
Gaps in the netdata charts frequently

### ISSUE THREAD

**Issue by Ankit-Kulkarni** [firehol/netdata#3438]
@ktsaou Netdata is just awesome !. However I am having this same trouble  #3075  or #1712 (Getting lot of alerts due to gaps in charts ) . I tried changing the process priority from the following suggested source https://github.com/firehol/netdata/wiki/netdata-process-priority and tried almost all combinations for both kinds of systems(systemd + upstart ) still facing the same issue. 

I have netdata installed on all of the servers in different geographic regions. Each region also has a proxy netdata server which forwards all data to a central netdata master. Thus the single central netdata master is responsible to get  data from netdata proxies from each region. I use this central netdata master server to send all notifications and check for alarms. 

My current configs looks like- 
* Netdata slave (upstart system- ubuntu 14.04) 
```
[global]
        access log = none
        update every = 2
        process scheduling policy = fifo
        process scheduling priority = 80


[web]
        bind to = 127.0.0.1 ::1

[registry]
    enabled = no
    registry to announce = http://<mynetdataregistryaddress>

```
* Sample Netdata proxy netdata.conf 
```
[global]
        access log = none
        update every = 2
        process scheduling policy = other
        process nice level = -1

[registry]
    enabled = no
    registry to announce = http://<mynetdataregistryaddress>

```
Also what I noticed is the gap I see locally on server happened at 12:17 PM IST 

![db netdata dashboard 12-17ist](https://user-images.githubusercontent.com/2667270/36366109-a8668978-1572-11e8-80b8-f0e4e0d30b8c.png)
however on central netdata master server it appears 12:19PM IST . Kind of confused here. 
![db netdata dashboard 12-19ist](https://user-images.githubusercontent.com/2667270/36366110-acda63bc-1572-11e8-92e5-501855ad0835.png)

**Comment by ktsaou** [comment]
Hi, thanks!

The gap on the slave seems to be related to CPU usage. Have you tried giving `rr` priority to netdata or just `other` with nice = -1?

If netdata runs under systemd, it is likely that netdata won't be able to change its priority. Have you verified it did (netdata logs this to error.log).

The fact that the gaps between master and slave do not match, is strange. Generally, slaves push to masters the collected data, not the processed data. So, each netdata involved does its own calculations.  Of course the code is the same so the gaps should have been replicated.

Do you have reconnects between the slave and the proxy or the master?
Which memory modes do you use? Memory modes could affect timing and could introduce artificial gaps on proxies and masters.

**Comment by Ankit-Kulkarni** [comment]
Hi , Yes I tried changing the priority `rr` and also tried with `other` with `nice = -1` on both type of systems (upstart and systemd ) 

I checked netdata error log on the master no logs found related to priority however I can find logs like below .
```
netdata INFO  : PLUGINSD[apps] : File /var/cache/netdata/apps.lwrites/build.db is too old (last collected 86548 seconds ago, but the database is 7992 seconds). Clearing it.

netdata INFO  :STREAM_RECEIVER[myhostname,[MY_IP]:59300] : RRD database for chart 'cpu.cpu0_softirqs' on host 'myhostname' is 26.00591 secs in the past. Adjusting it to current time.
```
I checked the clocks on all system . They are all in sync . 

I also found logs related to disconnect and connect  often in access.log also found some disconnect logs in error.log . Here's a kind of sample from error.log : 
* on a proxy server 
```
netdata ERROR : PLUGINSD[charts.d] : '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 5723) disconnected after 0 successful data collections (ENDs).
```
* on master server 
```
netdata ERROR : STREAM_RECEIVER[myhostname,[myip]:49968] : STREAM myhostname [receive from [myip]:49968]: disconnected (completed 8280333 updates)
```
The memory modes I am using are as follows :
On slaves - ram
On proxy - save
on master - save

I think its important to mention here one more thing that all the proxies connect to master using tcp but over public ip(since they are in different geographic zones) .

**Comment by ktsaou** [comment]
ok, one step at a time.

First let's check the scheduling policy and the priority of the slave. Run on the slave this:

```
awk '/policy/ {print $NF}' /proc/`pidof netdata`/sched
```

It will give you a number. These are valid values (from `/usr/include/linux/sched.h`):

```c
#define SCHED_NORMAL            0
#define SCHED_FIFO              1
#define SCHED_RR                2
#define SCHED_BATCH             3
/* SCHED_ISO: reserved but not implemented yet */
#define SCHED_IDLE              5
#define SCHED_DEADLINE          6
```

Similarly the priority can be viewed with this:

```sh
awk '/prio/ {print $NF}' /proc/`pidof netdata`/sched
```

With this we will verify that the slave is actually running with a priority that should prevent it from loosing the cpu.

Once we verify this, we can move on to the next check.

**Comment by Ankit-Kulkarni** [comment]
Hi Thanks, 
I have checked as per your suggestion . 

`awk '/policy/ {print $NF}' /proc/`pidof netdata`/sched` 
output - `5` 

awk '/prio/ {print $NF}' /proc/`pidof netdata`/sched
output - `139`

My netdata config defined  on a slave( which has upstart) includes this . 
```
        process scheduling policy = fifo
        process scheduling priority = 80
``` 
From what the output looks it suggests that the priority and policy both are not changed. Netdata on this instance is running as `netdata` user.

**Comment by ktsaou** [comment]
hm... I am a bit confused. So, does netdata respect the setting you give it or not?

I am especially interested for the system you posted the gap above (the one you defined as the slave: upstart system- ubuntu 14.04). If this system runs with `idle` (5), then the gap on the slave is logical.

**Comment by Ankit-Kulkarni** [comment]
Yes for the affected system I have right settings applied in conf as mentioned above but its running with `idle` (5) . It seems to me that netdata didn't respect the setting mentioned.

**Comment by ktsaou** [comment]
> Yes for the affected system I have right settings applied in conf as mentioned above but its running with idle (5) . It seems to me that netdata didn't respect the setting mentioned. I have tried netdata restart and netdata stop/start a couple of times but no luck.

ok, this is the reason for the gap at the slave. We need to fix this. Is this an upstart system or a systemd? Please run this on that system and paste here the result:

```sh
curl -s 'http://localhost:19999/netdata.conf' |  sed -n -e '/\[global\]/,/^$/p'
```

**Comment by Ankit-Kulkarni** [comment]
Here's the output of the command for the upstart system . 

```
[global]
	access log = none
	update every = 2
	process scheduling policy = fifo
	process scheduling priority = 80
	# glibc malloc arena max for plugins = 1
	# glibc malloc arena max for netdata = 1
	# hostname = cc-test-db
	# history = 3996
	# config directory = /etc/netdata
	# log directory = /var/log/netdata
	# web files directory = /usr/share/netdata/web
	# cache directory = /var/cache/netdata
	# lib directory = /var/lib/netdata
	# home directory = /var/cache/netdata
	# plugins directory = "/usr/libexec/netdata/plugins.d" "/etc/netdata/custom-plugins.d"
	# memory mode = save
	# host access prefix =
	# memory deduplication (ksm) = yes
	# TZ environment variable = :/etc/localtime
	# timezone = Etc/UTC
	# debug flags = 0x0000000000000000
	# debug log = /var/log/netdata/debug.log
	# error log = /var/log/netdata/error.log
	# errors flood protection period = 1200
	# errors to trigger flood protection = 200
	# run as user = netdata
	# OOM score = 1000
	# pthread stack size = 8388608
	# cleanup obsolete charts after seconds = 3600
	# gap when lost iterations above = 1
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes
```
 
From a systemd machine here's the output . 

[global]
	access log = none
	update every = 2
	process scheduling policy = keep
	# glibc malloc arena max for plugins = 1
	# glibc malloc arena max for netdata = 1
	# hostname = rss-server
	# history = 3996
	# config directory = /etc/netdata
	# log directory = /var/log/netdata
	# web files directory = /usr/share/netdata/web
	# cache directory = /var/cache/netdata
	# lib directory = /var/lib/netdata
	# home directory = /var/cache/netdata
	# plugins directory = "/usr/libexec/netdata/plugins.d" "/etc/netdata/custom-plugins.d"
	# memory mode = save
	# host access prefix =
	# memory deduplication (ksm) = yes
	# TZ environment variable = :/etc/localtime
	# timezone = Etc/UTC
	# debug flags = 0x0000000000000000
	# debug log = /var/log/netdata/debug.log
	# error log = /var/log/netdata/error.log
	# errors flood protection period = 1200
	# errors to trigger flood protection = 200
	# run as user = netdata
	# OOM score = 1000
	# pthread stack size = 8388608
	# cleanup obsolete charts after seconds = 3600
	# gap when lost iterations above = 1
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes

I checked all of my systems I think the same is the problem almost with every VM. No VM respected the netdata settings. Not really sure why.  I had installed netdata on each vm using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` . Also ran `apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`.

**Comment by ktsaou** [comment]
sorry for the delay... too many requests...

I installed ubuntu 14.04 on a VM to test it. I found netdata logs this:

```
2018-03-09 00:32:25: netdata ERROR : MAIN : scheduler fifo priority 80 is above the maximum 0. Using the maximum.
```

I traced it down and found a line was missing from netdata, so it was not actually changing the scheduling policy.

It is not also logging it:

```
2018-03-09 00:52:47: netdata INFO  : MAIN : Adjusted netdata scheduling policy to fifo (1), with priority 80.
```

Thank you for reporting this!
I'll merge it in a while.

**Comment by ktsaou** [comment]
merged it.
Please update your netdata and check `/var/log/netdata/error.log`. It should report success or failure to apply the given policy.

**Comment by Ankit-Kulkarni** [comment]
I updated netdata to latest and tried changing priorities. I think it worked now. 

Will monitor the charts for 2-3 days and see if any gaps comes. 

Thanks a lot
