### ISSUE TITLE
ISC-DHCP and Python.d Update Init Issue

### ISSUE THREAD

**Issue by HammaBamma** [firehol/netdata#3442]
Hello,

Great product by the way! 

I just started using this, and I'm trying to have it dump prometheus stats out for my DHCP servers. I've got the config file for isc-dhcpd.conf exactly as it's described in the document. Yet when I start and run netdata I get this in the error.log file.

```

2018-02-19 16:16:48: python.d INFO: isc_dhcpd: dhcpdv4: check() => [OK]
2018-02-19 16:16:48: netdata ERROR : PLUGINSD[python.d] : File /var/cache/netdata/netdata.runtime_isc_dhcpd_nanogNetworks/main.db is too old. Clearing it.
2018-02-19 16:16:48: netdata INFO  : PLUGINSD[python.d] : File /var/cache/netdata/netdata.runtime_isc_dhcpd_nanogNetworks/run_time.db is too old (last collected 1519075008 seconds ago, but the database is 3996 seconds). Clearing it.
2018-02-19 16:16:49: python.d ERROR: isc_dhcpd: dhcpdv4: update() unhandled exception: __init__() takes exactly 4 arguments (3 given)
```

I've been digging all over the place and can't figure out what is causing this issue. Regardless it's not processing the requests.. After awhile of just leaving the netdata running i'll get a message like

```
2018-02-19 13:51:36: python.d ERROR: isc_dhcpd: job_name: stopped after 60 data collection failures in a row

```
Version: v1.9.0-449-gaf5f974_rolling
isc_dhcpd.conf Config:
```
dhcpdv4:
  name: nanogNetworks
  update_every: 1
  pools:
    manage: '192.252.241.0/24'
```

Brand new Ubuntu box with py-ipaddress installed.. 

Don't mind the different job names. I've been trying to change all the params.. 

Thanks for your help!

-Con

**Comment by l2isbad** [comment]
@HammaBamma 
can you share your leases file ?

**Comment by HammaBamma** [comment]
Here you are good sir... @l2isbad  This is from a secondary failover peer, I haven't installed NetData on my primary box as I'd like to test on secondary before.

[dhcpd.leases.txt](https://github.com/firehol/netdata/files/1738476/dhcpd.leases.txt)

**Comment by l2isbad** [comment]
@HammaBamma 
i found

all backup leases has no `ends` thing

```
lease 199.187.219.63 {
  starts 6 2018/02/17 01:13:21;
  tsfp 6 2018/02/17 01:13:21;
  atsfp 6 2018/02/17 01:13:21;
  binding state backup;
}
```

How we should interpret such leases?

**Comment by HammaBamma** [comment]
@l2isbad 

Based on this article: https://www.isc.org/wp-content/uploads/2017/08/dhcp41leases.html

It says that it's an available address if it's binding state is backup, like it's not in use anymore. 

Sorry that I'm using a confusing failover scheme, it's just our redundancy requirements here.

I appreciate your quick replies though..

**Comment by HammaBamma** [comment]
Just updated the chart file with your fix, and the plugin ingests the lease file and starts properly.. However it's not outputting any leases. I'm going to install this on the other server and see if the result is the same.. See here to see my dashboard.. http://services2.meetings.nanog.org:19999/#menu_isc_dhcpd_nanogNetworks_submenu_utilization;theme=slate;help=true

**Comment by l2isbad** [comment]
Well, lease considered active and valid if:
1. binding state is `active`
2. `ends` time - current time > 0

All such leases are active leases in `All Active Leases` chart.

if active and valid lease belongs to configured pool you can see it in `Active Leases Per Pool `.

It works for me with your `dhcpd.leases.txt`.

I made some changes to it.

```diff
--- Downloads/dhcpd.leases.txt	2018-02-21 09:38:53.236902129 +0900
+++ /opt/dhcpd.leases.txt	2018-02-21 09:38:30.760833253 +0900
@@ -18000,10 +18000,10 @@
 }
 lease 192.252.241.137 {
   starts 0 2018/02/18 22:58:32;
-  ends 0 2018/02/18 22:58:33;
+  ends 0 2018/02/25 22:58:33;
   tstp 0 2018/02/18 22:58:33;
   cltt 0 2018/02/18 22:58:32;
-  binding state free;
+  binding state active;
   hardware ethernet 70:ef:00:66:b7:16;
   uid "\001p\357\000f\267\026";
 }
@@ -20787,7 +20787,7 @@
 }
 lease 199.187.217.148 {
   starts 0 2018/02/18 23:23:36;
-  ends 0 2018/02/18 23:53:36;
+  ends 0 2018/02/25 23:53:36;
   tstp 1 2018/02/19 00:08:36;
   tsfp 1 2018/02/19 00:08:36;
   atsfp 1 2018/02/19 00:08:36;
```

config
```yaml
dhcpdv4:
  leases_path: '/opt/dhcpd.leases.txt'
  name: nanogNetworks
  update_every: 1
  pools:
    manage: '192.252.241.0/24'
```

![screenshot_20180221_094040](https://user-images.githubusercontent.com/22274335/36457049-5e7db5e6-16eb-11e8-995c-226f20353e74.png)

**Comment by ktsaou** [comment]
hm... this issue was closed with the merge of the PR. If you need more help, just post.
