### ISSUE TITLE
Help: Push over Pushover does not work

### ISSUE THREAD

**Issue by LevelOne2k** [firehol/netdata#3451]
Hello, I have set Push over in the file "/etc/netdata/health_alarm_notify.conf":

```
#pushover (pushover.net) global notification options

#multiple recipients can be given like this:
                  "HERE_IS_MY_USER_KEY"

#enable/disable sending pushover notifications
SEND_PUSHOVER="YES"

#Login to pushover.net to get your pushover app token.
#You need only one for all your netdata servers (or you can have one for
#each of your netdata - your call).
#Without an app token, netdata cannot send pushover notifications.
PUSHOVER_APP_TOKEN="HERE_IS_MY_TOKEN"

#if a role's recipients are not configured, a notification will be send to
#this pushover user token (empty = do not send a notification for unconfigured
#roles):
DEFAULT_RECIPIENT_PUSHOVER=""
```

It does not work:

> #SENDING TEST WARNING ALARM TO ROLE: sysadmin
> /usr/libexec/netdata/plugins.d/../../../../etc/netdata/health_alarm_notify.conf: line 132: HERE_IS_MY_TOKEN: command not found
> 2018-02-21 18:21:58: alarm-notify.sh: INFO: sent email notification for: xxxxx.de test.chart.test_alarm is WARNING to 'root'
> #OK
> 
> #SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
> /usr/libexec/netdata/plugins.d/../../../../etc/netdata/health_alarm_notify.conf: line 132: HERE_IS_MY_TOKEN: command not found
> 2018-02-21 18:21:59: alarm-notify.sh: INFO: sent email notification for: xxxxx.de test.chart.test_alarm is CRITICAL to 'root'
> #OK
> 
> #SENDING TEST CLEAR ALARM TO ROLE: sysadmin
> /usr/libexec/netdata/plugins.d/../../../../etc/netdata/health_alarm_notify.conf: line 132: HERE_IS_MY_TOKEN: command not found
> 2018-02-21 18:21:59: alarm-notify.sh: INFO: sent email notification for: xxxxx.de test.chart.test_alarm is CLEAR to 'root'
> #OK

**Comment by ktsaou** [comment]
Use this:

```
SEND_PUSHOVER="YES"
PUSHOVER_APP_TOKEN="HERE_IS_MY_TOKEN"
DEFAULT_RECIPIENT_PUSHOVER="HERE_IS_MY_USER_KEY"
```

**Comment by wdiechmann** [comment]
it works - when you open the Pushover app ;)
