### ISSUE TITLE
syntax error near unexpected token when installing

### ISSUE THREAD

**Issue by trebonius0** [firehol/netdata#3452]
Hi

I just cloned the netdata repo and I get an error when running `sudo sh netdata-installer.sh`

> netdata-installer.sh: line 13: syntax error near unexpected token `<'

> netdata-installer.sh: line 13: `    done < <( echo "${PATH}" | tr ":" "\n" )'

**Comment by ktsaou** [comment]
Please use `bash`, not `sh`.
