### ISSUE TITLE
Visebletotal dimension in the prometheus

### ISSUE THREAD

**Issue by cornerot** [firehol/netdata#3455]
Hello!

netdata version: 1.9.0

Why is there no "visebletotal" dimension in the prometheus metrics?

`curl -s localhost:19999/api/v1/allmetrics | grep NETDATA_SYSTEM_RAM`

```bash
NETDATA_SYSTEM_RAM_FREE="991"      # MB
NETDATA_SYSTEM_RAM_USED="6201"      # MB
NETDATA_SYSTEM_RAM_CACHED="39032"      # MB
NETDATA_SYSTEM_RAM_BUFFERS="18158"      # MB
NETDATA_SYSTEM_RAM_VISIBLETOTAL="64382"      # MB
```

`curl -s 'localhost:19999/api/v1/allmetrics?format=prometheus' | grep netdata_system_ram`

```bash
netdata_system_ram_MB_average{chart="system.ram",family="ram",dimension="free"} 988.7647231 1519289775000
netdata_system_ram_MB_average{chart="system.ram",family="ram",dimension="used"} 6202.7583077 1519289775000
netdata_system_ram_MB_average{chart="system.ram",family="ram",dimension="cached"} 39033.0707692 1519289775000
netdata_system_ram_MB_average{chart="system.ram",family="ram",dimension="buffers"} 18158.2038462 1519289775000
```

Visebletotal metric is useful for percentage calculation.

**Comment by ktsaou** [comment]
I think prometheus can calculate this. If we add the visible total to prometheus, then if you ask prometheus for a sum, it will return twice the value.

**Comment by cornerot** [comment]
Ok, a sound decision. Thanks.
