### ISSUE TITLE
Support Infos about HugePages

### ISSUE THREAD

**Issue by h0lzi** [firehol/netdata#3461]
Hi,
I monitor some Oracle Database Systems which use Hugepages:

cat /proc/meminfo |grep -i Hugep
AnonHugePages:    368640 kB
**HugePages_Total:   53342
HugePages_Free:    11904**
HugePages_Rsvd:        0
HugePages_Surp:        0
**Hugepagesize:       2048 kB**

Those are reserved at front and show up as used RAM:

![image](https://user-images.githubusercontent.com/615675/36591428-4a06bef2-1892-11e8-85c7-c908c3bcf05c.png)

Would be awsome if used could be separated to show HugePages_Total and Free.
So I could see who much is used by other stuff and If I have lot's of Free HugePages that are "wasted" because can't be used by other stuff.

**Comment by ktsaou** [comment]
In PR #3462
