### ISSUE TITLE
Error 405: Cannot download charts index from server ..... /api/v1/charts

### ISSUE THREAD

**Issue by Night1** [firehol/netdata#347]
Hey awesome work with this, looks amazing, 

I'm experinces an issue, which I'm unable to figure out. I keep getting this error:  Error 405: Cannot download charts index from server ..... /api/v1/charts

This is both on the server it self, from local and external devices. I had the same issue when I first set this up however after a reboot it worked just fine.  Then after a while the error returns. 

has anyone seen this issue ? Firewall is set to allow traffic from my devices.

**Comment by MadddinTribleD** [comment]
Hey there,

Same problem here. Worked fine just before updating to Version a143f8ab8c44451fef816f29e99b74588c39d127

**Comment by ktsaou** [comment]
is there anything logged in `/var/log/netdata/error.log` and `/var/log/netdata/access.log` when you do this?

Just `tail -f /var/log/netdata/*.log` and hit refresh on your browser. What do they say?

**Comment by ktsaou** [comment]
I think this is related to something collected from your system which breaks the JSON generated.

Try this:

1. Go to http://your.server:19999/api/v1/charts
2. Hit Control-A then Control-C
3. Go to http://jsonlint.com/
4. Hit Control-V
5. Press Validate JSON

Can you give me the error message?

**Comment by ktsaou** [comment]
I think I fixed it. Could you please install the latest version and retry?

**Comment by Night1** [comment]
Installing new now, this was error fra json


Error: Parse error on line 952:
...vctm",			"family": "/media/night/WD\040
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by MadddinTribleD** [comment]
Fixed for me.

Thanks a lot.

**Comment by Night1** [comment]
Yup it is up and running, great work! Thank you

**Comment by ktsaou** [comment]
Can you help me understand what is happening with cgrousp? It seems that every machine is different.

I need your `[plugin:cgroups]` section from http://your.server:19999/netdata.conf.
Can you post it here?

**Comment by Night1** [comment]
[plugin:cgroups]
	# cgroups plugin resources = yes
	# check for new cgroups every = 10
	# enable cpuacct stat = on demand
	# enable cpuacct usage = on demand
	# enable memory = on demand
	# enable blkio = on demand
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# max cgroups to allow = 50
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh
	# enable cgroup / = no

**Comment by ktsaou** [comment]
ok thanks!
If this is fixed, please close it.

**Comment by Night1** [comment]
# # @

**Comment by Mirabis** [comment]
Got the same on the docker image ;p 
```
"title": "Queued I/O Operations (all disks) for cgroup system.slice/dev-dm\ (cgroup_system.slice_dev_dm_.queued_ops)", 
```

```
Error: Parse error on line 375:
...d_ops",			"title": "Queued I/O Operatio
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

Version ```a143f8ab8c44451fef816f29e99b74588c39d127 ```

Prob have to wait for an update on docker image and/or update manually

**Comment by ktsaou** [comment]
Could you please pull it again?
It has been fixed 2 days ago.

**Comment by Mirabis** [comment]
I re-created the container, and following the dockerfile - it should have pulled a new one on start ;/ 

Will re-try in a min

**Comment by ktsaou** [comment]
It is still the old one

**Comment by Mirabis** [comment]
Running : https://github.com/titpetric/netdata 

but mapping volumes to the folder doesn't seem to work.....

- Keep the issue closed ; ) will wait till it's resolved on container side...;)

**Comment by ktsaou** [comment]
@titpetric FYI

**Comment by titpetric** [comment]
Bumped version, should be up in a minute.

**Comment by Mirabis** [comment]
Re-pulled image, restarted and tested = confirmed working.

Thanks for support guys!

@titpetric Any chance u can have :latest do a git pull (update) on container start?
and then do specific versions as tag (if neccesary)?

**Comment by titpetric** [comment]
Well, no. Currently the container image overhead is just a few megabytes (base image + 9mb?), git pull + build would require several 100MB worths of downloads (gcc, libs, etc) every time you'd start a new container. Working on true automatic updates.

**Comment by titpetric** [comment]
@Mirabis thanks to @ktsaou the container build has been fully automated. It should keep in line with whatever changes are pushed to this repo. Best, T

**Comment by axper** [comment]
Ok since this is the second result when searching for this error I'm gonna post the solution here.

For some wierd reasonn pressing Ctrl+F5 to reload the page results in this error. Pressing F5 however, the page loads properly.
