### ISSUE TITLE
FreeBSD make fail

### ISSUE THREAD

**Issue by denningsrogue** [firehol/netdata#3477]
When I attempt to install netdata on FreeBSD 11.1 p6, make fails with the following error:

--- apps.plugin ---
/tmp//ccptRm1K.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0x2835): undefined reference to `arl_free'
collect2: error: ld returned 1 exit status
*** [apps.plugin] Error code 1

make[2]: stopped in /usr/home/denningsrogue/netdata/src

Any help would be appreciated. (I also tried to install from ports and pkgs.  The installs seems to finish without issue, but netdata is inaccessible even though the service is running.)

**Comment by ktsaou** [comment]
You are right!
fixing it now.

**Comment by ktsaou** [comment]
merged it.
please try again.

**Comment by ktsaou** [comment]
and thank for reporting this. Somehow I missed it.

**Comment by denningsrogue** [comment]
Resolved!  Thank you very much.  Outstanding work!


Richard Peters
richardpeters@icloud.com
