### ISSUE TITLE
Add tags to json backend similar to the opentsdb and prometheus backends

### ISSUE THREAD

**Issue by sarlalian** [firehol/netdata#3479]
The OpenTSDB and Prometheus backends allows for tags to be added to each message, in the form of 

```
key=value,key=value
```

It would be really nice to have tags in the json payload as well for the json backend, ideally in a hash called "tags" or some such.  Preferably this would piggy back of the existing "host tags" config option in the backend config section.

```json
{
  "tags: {
    "key": "value",
    "key": "value"
 }
```

A potential example follows
```json
{
  "prefix": "n",
  "tags": {
    "country": "US",
    "location": "CA",
    "class": "web"
  },
  "hostname": "web-server",
  "chart_id": "disk_space._",
  "chart_name": "disk_space._",
  "chart_family": "/",
  "chart_context": "disk.space",
  "chart_type": "disk_space",
  "units": "GB",
  "id": "used",
  "name": "used",
  "value": 71.69738,
  "timestamp": 1519693529
}
```
Same use case as the typical OpenTSDB / Prometheus use case, to limit queries across fleet wide data to a subset of hosts by location / purpose / other extensible metadata.

**Comment by ktsaou** [comment]
hm, you are right.
Adding them like this in netdata.conf is pretty simple:

```
[backend]
   tags = { "country": "US", "location": "CA", "class": "web" }
```

So, if `tags` is set, netdata will just copy it to the json, without parsing it.

Will this do?

**Comment by ktsaou** [comment]
actually, although I have resisted to parse the tags, I think netdata will eventually have to.
I can think a few cases that the same tags have to be passed to different backends, so passing them through without properly formatting them for each backend will eventually break something...

**Comment by sarlalian** [comment]
The above would work certainly.  I think if you parse the tags, then they could more easily be formatted on a per backend basis, which may in the end make it easier to support tags for different backends.

But passing them through blindly would work for my purposes.

**Comment by ktsaou** [comment]
in PR #3556

**Comment by ktsaou** [comment]
merged it.
