### ISSUE TITLE
Question: Disable sensors section?

### ISSUE THREAD

**Issue by jeremyjpj0916** [firehol/netdata#3480]
I have been looking all over in my .conf file to figure out how to disable/remove the entire sensors charts/data:

![image](https://user-images.githubusercontent.com/31913027/36710815-41f4c3f8-1b4e-11e8-8d51-5f6e0997fd88.png)

So here is a snippit of my netdata.conf file too regarding sensors:
![image](https://user-images.githubusercontent.com/31913027/36710869-8435e60c-1b4e-11e8-87a4-d1dbd14d2cde.png)

As a user of this application for about 2 months I have gotten pretty good at disabling charts I don't want, but when uuid's and others things get thrown into the mix I no longer know where/how to do:

[whatgoeshere]
    enabled = no

For getting rid of this section.

Thanks!
-Jeremy

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf#L70

**Comment by jeremyjpj0916** [comment]
@l2isbad you sir are a saint. Mystery solved.
