### ISSUE TITLE
Support for bcache

### ISSUE THREAD

**Issue by billy482** [firehol/netdata#3482]
[Bcache](https://en.wikipedia.org/wiki/Bcache) is a nice cache block layer for Linux.

Munin plugin for example:
[bcache.txt](https://github.com/firehol/netdata/files/1762122/bcache.txt)
Don't be fooled by extension, It's a bash script.

**Comment by ktsaou** [comment]
nice idea. never used one. probably it is time...

I see it exposes a lot of info: https://www.kernel.org/doc/Documentation/bcache.txt

**Comment by ktsaou** [comment]
in PR #3504 
Can you test it?

**Comment by ktsaou** [comment]
updated the description at the PR

**Comment by ktsaou** [comment]
merged it.
