### ISSUE TITLE
support for icecast stats (json api)

### ISSUE THREAD

**Issue by tommybuck** [firehol/netdata#3486]
Would it be possible to add support for Icecast stats please?

I know Icecast exposes a json api using http://youricecastserver.com:8000/status-json.xsl

I would like to chart the amount of listeners.

Cheers,

**Comment by ktsaou** [comment]
Can you post one such json file?

**Comment by tommybuck** [comment]
If you browse to [Here](http://192.99.34.205:8443/status-json.xsl) it will give you json data.

It looks like this:
`{
  "icestats": {
    "admin": "icemaster@localhost",
    "host": "miledmusic.com",
    "location": "Earth",
    "server_id": "Icecast 2.4.2",
    "server_start": "Fri, 05 Jan 2018 06:59:09 -0500",
    "server_start_iso8601": "2018-01-05T06:59:09-0500",
    "source": [
      {
        "audio_info": "bitrate=256",
        "bitrate": 256,
        "genre": "Unspecified",
        "listener_peak": 22,
        "listeners": 1,
        "listenurl": "http://miledmusic.com:8443/autodj",
        "server_description": "Default description",
        "server_name": "Stream Name",
        "server_type": "audio/mpeg",
        "server_url": "http://localhost/",
        "stream_start": "Fri, 05 Jan 2018 07:10:24 -0500",
        "stream_start_iso8601": "2018-01-05T07:10:24-0500",
        "title": "Perez Prado and his Orchestra - Rosina",
        "dummy": null
      },
      {
        "listeners": 0,
        "listenurl": "http://miledmusic.com:8443/live",
        "dummy": null
      },
      {
        "listeners": 0,
        "listenurl": "http://miledmusic.com:8443/stream",
        "dummy": null
      }
    ]
  }
}`

**Comment by l2isbad** [comment]
@tommybuck 
what charts do you want

![screenshot_20180302_113457](https://user-images.githubusercontent.com/22274335/36880773-c821fe70-1e0d-11e8-83f6-dabc644ecc3e.png)

**Comment by tommybuck** [comment]
Source 0 Listeners please.

**Comment by l2isbad** [comment]
@tommybuck 
Ok.
So it can be N sources. Source is **active** when it has `server_*`, etc. Module should chart number of listeners for all active sources. Right?

**Comment by tommybuck** [comment]
yes please

**Comment by ktsaou** [comment]
merged it.
