### ISSUE TITLE
Telegram Alarms works only by hand execution.

### ISSUE THREAD

**Issue by isca0** [firehol/netdata#3489]
I have deployed netdata on several servers, but i can see the alarms are only sended to telegram when i force to execute it by hand calling the script manually like:

```
/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh sysadmin hostname 1519681630 1519679963 7 1519845175 host_reachable fping.hostname_latency hostname CRITICAL CLEAR 0 1 14@/opt/netdata/etc/netdata/health.d/fping.conf 328 0 up/down states if the remote host is reachable down up
```
The alarm-notify.sh test 'CRITICAL' works fine on every server.
All alarms are showed fine trought web browser also. 
I dont know if is something i missing here, but i see no erros on logs. 
health_alarm_notify.conf is configured as defaults, just added my telegram bot token and mychat id. 

>What i expected: All alarms automatically sent trought telegram.

My netdata version is netdata 1.9.0-505-gca904596_rolling, installed from kickstart-static64.sh.

**Comment by ktsaou** [comment]
hm... interesting.

netdata sends the alarms while running as user `netdata`. Also, the static build is using a binary `curl` shipped with netdata.

Please try this:

```sh
# become user netdata
sudo su -s /bin/sh netdata

# use the static binaries shipped with netdata
export PATH="/opt/netdata/bin:${PATH}"

# enable debugging
export NETDATA_ALARM_NOTIFY_DEBUG=1

# test the alarms
/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```

Could you please post the output?

**Comment by isca0** [comment]
God bless you for this DEBUG=1 command... ;) Now i can see the netdata curl is failing...

```
/opt/netdata/bin/curl --data-urlencode disable_notification=true --data-urlencode parse_mode=HTML --data-urlencode disable_web_page_preview=true --data-urlencode $'text=\342\234\205 hostname recovered - <b>test alarm</b>\ntest.chart (test.family)\n<a href="https://registry.my-netdata.io/goto-host-from-alarm.html?host=hostname&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3">test alarm (alarm was raised for 3 seconds)</a>\n<i>this is a test alarm to verify notifications work</i>' https://api.telegram.org/bot12456:XXAAHHSHHXBBA/sendMessage\?chat_id=chatidnum
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```
I have made a workaround appendind `-k` and works ;-). 
Any sugestion with `CApath none` error on this curl!?

**Comment by ktsaou** [comment]
which distro is this?

**Comment by isca0** [comment]
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

**Comment by ktsaou** [comment]
ok, found the issue.

centos installs the certificate as `/etc/ssl/certs/ca-bundle.crt`, but the static curl build searches for it as `etc/ssl/certs/ca-certificates.crt`.

You have a few options:

1. `rm /opt/netdata/bin/curl`, so that netdata will use the `curl` command from your system
2. link the file you have with the file it searches
3. I see here https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url you can also:

  - set `export CURL_CA_BUNDLE="/etc/ssl/certs/ca-bundle.crt"` at `/opt/netdata/etc/netdata/health_alarm_notify.conf`
  - edit `~netdata/.curlrc` and set `cacert=/etc/ssl/certs/ca-bundle.crt`

I think we should detect this at the installer and automatically fix it for you.

**Comment by ktsaou** [comment]
I think I will implement the last option at the installer:

edit `~netdata/.curlrc` and set `cacert=/etc/ssl/certs/ca-bundle.crt`

Can you check if this works?

**Comment by isca0** [comment]
This installation are setting $HOME of netdata on "/"
I changed netdata `$HOME` to `/opt/netdata` and added .curlrc, it worked! ;) 
Now curl `RESPONSE CODE: 200`

But still works only when i run mannually, automatically trought netdata daemon, i still not receiving alarms...

**Comment by ktsaou** [comment]
> This installation are setting $HOME of netdata on "/"

oops! that is another bug.

> I changed netdata $HOME to /opt/netdata and added .curlrc, it worked! ;)
> But still works only when i run mannually, automatically trought netdata daemon, i still not receiving alarms...

ok, let me test it a bit...

**Comment by ktsaou** [comment]
ok, fixed the user netdata home on new installation and printed instructions to fix it on existing installations.

I attempted to fix the issue with the SSL CA certifications, at least for CentOS (it is unbelievable that Linux folks tend to disagree on every possible detail), but at the same time I added `--insecure` (`-k`) to `curl`. I thought that it is better to dispatch the notifications even if the certifications cannot be validated. The notification itself is not that sensitive afterall.

In PR #3490

**Comment by isca0** [comment]
Thank you, installation is fixed and working ;-) 
But i still not receiving telegram notifications. I receive only when i run alarm by hand on command line. 
Is the active critical alarms to be triggered to alarm-notify.sh? I understand if i restart netdata service and if exist some active alarm it must be trigger alarm-notify.sh and send telegram messages automatically, but isnt working like that.
On web browser the alarm is active and showing the popup, netdata curl is working by hand allways as netdata user. What is missing out here!?

**Comment by ktsaou** [comment]
When `alarm-notify.sh` is run by netdata, it logs it to `/opt/netdata/var/log/netdata/error.log`.

```sh
# grep alarm-notify /var/log/netdata/error.log
2018-03-01 11:32:22: alarm-notify.sh: INFO: not sending notification for CLEAR of 'ktsaou-laptop.system.softnet_stat.10min_netdev_budget_ran_outs' (last status was UNINITIALIZED)
2018-03-01 17:43:42: alarm-notify.sh: INFO: sent email notification for: ktsaou-laptop httpcheck_smynetdata.error.httpcheck_last_collected_secs is WARNING to 'root'
2018-03-01 17:43:42: alarm-notify.sh: INFO: sent email notification for: ktsaou-laptop httpcheck_mynetdata.error.httpcheck_last_collected_secs is WARNING to 'root'
2018-03-01 17:48:52: alarm-notify.sh: INFO: sent email notification for: ktsaou-laptop httpcheck_smynetdata.error.httpcheck_last_collected_secs is CLEAR to 'root'
2018-03-01 17:48:52: alarm-notify.sh: INFO: sent email notification for: ktsaou-laptop httpcheck_mynetdata.error.httpcheck_last_collected_secs is CLEAR to 'root'
```

Do you have such logs?

btw, PR #3496 will remove the `--insecure` flag by default. PR #3490 should have already fixed the issue for CentOS (add `cacert=` to `~netdata/.curlrc`), but you will need to run this to change the home of the user netdata to the installation path of the static-netdata:

```
usermod -d /opt/netdata netdata
```

**Comment by isca0** [comment]
Let me try explain bether, i have fixed by hand this permissions and curl by hand as you said, and the telegram messages are working. I think my problem isn't any more related with curl -k or cacert...
If i `grep alarm` on this `error.log` file i have a few telegram messages. So telegram messages are working. 
But what i think is happening is some role on alarms set alarms as 'alerady exist'  so i think they not will be sent trought telegram. Am I Right!?
For example:
```
netdata INFO  : MAIN : Health alarm 'system.swap.used_swap' already exists in host 'hostname'.
```

So in fact, i think this is related to some histeresys set on swap.conf healtd.d so if i got it right, if i remove delay on this kind of alarm and reload with `killall -USR2 netdata` this alarm must be now sented trought telegram. Is this right?

What happen is, this same alarm popup on my browser again after reload, but wasent sent trought telegram.
![](https://image.ibb.co/maqRyS/popupswap.jpg)

 If i look the `swap.conf` settings trought the netdata pannel, it dosent have my changes on this alarm.
![](https://preview.ibb.co/eDXBXn/swapalarm.jpg)

Here is how my `swap.conf' alarm is:
```
alarm: used_swap
      on: system.swap
      os: linux freebsd
   hosts: *
    calc: $used * 100 / ( $used + $free )
   units: %
   every: 5s
    warn: $this > (($status >= $WARNING)  ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
    info: the percentage of swap memory used
      to: sysadmin
```

What i missing here!?

**Comment by ktsaou** [comment]
The log `already exists in host` means that you have the alarm defined more than once.
Check your `health.d` directory. You may have copied `swap.conf` to another file.

Run:

```sh
# sudo grep used_swap /opt/netdata/etc/netdata/health.d/*
```

How many of them?

**Comment by isca0** [comment]
Yes, in fact they are duplicated, now everything works just fine... Thanks a lot for the help. Congrats for the work... ;-)
