### ISSUE TITLE
Set up retries count in charts.d plugins

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#3493]
Hello, 
I`m trying to write very simple bash plugin.
There are _check() and _update() functions, and everything seems working as expected, except one thing.
If _update() fails to get data, it will make around 10 tries...:

`module's 'vault' update() function reports failure. Will keep trying for a while.`

...than plugins stops:

`vault: nothing left to do, exiting...`

Python plugins have `retries` var, so I tried to set up `vault_retries` (among `vault_priority` or `vault_update_every`), but it did not work.

Thank you!

**Comment by ktsaou** [comment]
You are right. This is missing.
Adding it now.

**Comment by ktsaou** [comment]
In PR #3524

**Comment by ktsaou** [comment]
merged it. Please update your netdata.

`vault_retries=123` will work now...
