### ISSUE TITLE
I can only open netdata on my home ip

### ISSUE THREAD

**Issue by thegreatzeus** [firehol/netdata#3499]
Hi; 
I installed netdata around 3 weeks ago; I haven't been able to access it on any other IP than the IP that I have in my apartment. 
I have tried almost all the solutions on google, iptables and everything but still I can't access it on other IPs.

**Comment by pedro-nonfree** [comment]
change in `/etc/netdata/netdata.conf`

```diff
-bind socket to IP = 127.0.0.1
+bind socket to IP = 0.0.0.0
```

it's preferrable to use an internal network that only you can access

take care:
```
# Netdata is not designed to be exposed to potentially hostile
# networks.See https://github.com/firehol/netdata/issues/164
```

**Comment by thegreatzeus** [comment]
Thanks for your reply, which part of the file should I put this? 
I placed it at the end of the [web] section and gracefully restarted but still no change.

**Comment by pedro-nonfree** [comment]
Replace the current line in red with the line in green (without the signs, this is a diff)

if you place at the end, as you have the other line I don't know what's happening

alternatively, paste here the configuration file

**Comment by thegreatzeus** [comment]
I couldn't find it anywhere in the configuration file, so here is the attached file.

[netdata.zip](https://github.com/firehol/netdata/files/1776575/netdata.zip)

**Comment by pedro-nonfree** [comment]
strange netdata.config

in section global

[global]

put:

bind socket to IP = 0.0.0.0

in one case, I have netdata in localhost (by default)

```
# ss -tupanl | grep 19999
tcp    LISTEN     0      128    127.0.0.1:19999                 *:* 
```

in another case, it is publicly available

```
# ss -tupanl | grep 19999
tcp    LISTEN     0      100       *:19999                 *:*                   users:(("netdata",pid=15997,fd=3))
```

**Comment by thegreatzeus** [comment]
I made changes, restarted the whole server still no changes, 
can you please do me a favor and modify the configuration file for me? I would truly appreciate it.

**Comment by l2isbad** [comment]
@thegreatzeus 

>  I haven't been able to access it on any other IP than the IP that I have in my apartment.

Can you describe it a bit? What do you want to achieve? What is "apartment IP"?
Did you install it on your home PC and want to access from the outside?

**Comment by pedro-nonfree** [comment]
@thegreatzeus 

pasting the initial part of your configuration until the line we are talking about appears:

```
# netdata configuration
#
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

# global netdata configuration

[global]
bind socket to IP = 0.0.0.0
```

**Comment by ktsaou** [comment]
Hi,

I am adding the following just for completeness:

if you want to access netdata from outside your local LAN, you should do one of the following:

1. setup a VPN, so that you can safely enter your LAN and then access netdata. **This is the best solution.**

2. setup a web server in front of netdata and proxy netdata through it. The wiki has examples for almost all web servers (nginx, apache, etc). This method will allow you to password protect your netdata and possibly add SSL to it. This is good case, if you want to allow third parties access your netdata.

3. if you want to access netdata from a static IP (e.g. you want to access a netdata at work from your home or vice-versa), netdata supports IP filtering. Check the `[web]` section of your `/etc/netdata/netdata.conf`.

---

@pedro-nonfree your netdata.conf is too old. The current netdata.conf about web config is like this:

```
[web]
	# mode = static-threaded
	# listen backlog = 4096
	# default port = 19999
	# bind to = *
	# web files owner = netdata
	# web files group = netdata
	# disconnect idle clients after seconds = 60
	# timeout for first request = 60
	# respect do not track policy = no
	# x-frame-options response header = 
	# allow connections from = localhost *
	# allow dashboard from = localhost *
	# allow badges from = *
	# allow streaming from = *
	# allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
	# enable gzip compression = yes
	# gzip compression strategy = default
	# gzip compression level = 3
	# web server threads = 4
```

Though, the current netdata supports also old config files, so your config works, but is not suggested.
You can download the latest config version from your netdata. You posted the instructions above.

**Comment by davidcrx** [comment]
You can just allow your ip in the following way.
Edit /etc/netdata/netdata.conf

[web]
        # mode = static-threaded
        # listen backlog = 4096
         default port = 1999x
        # bind to = *
        # web files owner = netdata
        # web files group = netdata
        # disconnect idle clients after seconds = 60
        # timeout for first request = 60
        # respect do not track policy = no
        # x-frame-options response header =
        # allow connections from = localhost, 172.26.30.237
        allow dashboard from = 81.44.x.x
        # allow badges from = *
        # allow streaming from = *
        # allow netdata.conf from = 172.26.30.*
        # enable gzip compression = yes
        # gzip compression strategy = default
        # gzip compression level = 3
        # web server threads = 2

Restart netdata: killall netdata; sleep 3; netdata

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but you can still post.
