### ISSUE TITLE
Netdata custom apps monitoring

### ISSUE THREAD

**Issue by elifatalay** [firehol/netdata#3516]
I want to make separate demonstrations of our specific applications running on the device on Netdata. So how much of our custom application does the CPU use? as. Is this possible?

**Comment by ktsaou** [comment]
Of course.

Edit `/etc/netdata/apps_groups.conf` and add a group for your application.

For example, to monitor application `myapp`, add this:

```
myapp: *myapp*
```

The first part is the process group name, and after `:` is a space separated list of patterns (asterisks are recognized only at the beginning or the end of each pattern).

Then restart netdata. With just the above, the `Applications` charts will now have dimension called `myapp`.

For more information check this: https://github.com/firehol/netdata/wiki/Apps-Plugin and the information at the header of [apps_groups.conf](https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf).

---

Once you have the above, your app will appear at this chart (example at the registry): https://registry.my-netdata.io/#menu_apps

![image](https://user-images.githubusercontent.com/2662304/37111230-d607d1fc-2247-11e8-94c4-677df4e6185d.png)

---

You can also create badges that you can embed anywhere you like. For example:

```
https://your.netdata.ip:19999/api/v1/badge.svg?chart=apps.processes&dimensions=myapp&value_color=green%3E0%7Cred
```

The color expression unescaped is this: `value_color=green>0|red`.

Here is an example for the process group `sql` at `https://registry.my-netdata.io`:

![image](https://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=sql&value_color=green%3E0%7Cred)

and here is the same badge for `myapp` (which of course is not running there so just a `-` is shown):

![image](https://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=myapp&value_color=green%3E0%7Cred)

netdata is able give you a lot more badges for your app.
Examples below for process group `sql`:

1. CPU usage: ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.cpu&dimensions=sql&value_color=green%3E0%7Cred)
2. Disk Physical Reads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.preads&dimensions=sql&value_color=green%3E0%7Cred) (this will be red if the application is not reading from disk - you can swap the colors if you like)
3. Disk Physical Writes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.pwrites&dimensions=sql&value_color=green%3E0%7Cred)
4. Disk Logical Reads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.lreads&dimensions=sql&value_color=green%3E0%7Cred)
5. Disk Logical Writes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.lwrites&dimensions=sql&value_color=green%3E0%7Cred)
6. Open Files ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.files&dimensions=sql&value_color=green%3E0%7Cred)
7. Real Memory ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.mem&dimensions=sql&value_color=green%3E0%7Cred)
8. Virtual Memory ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.vmem&dimensions=sql&value_color=green%3E0%7Cred)
9. Minor Page Faults ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.minor_faults&dimensions=sql&value_color=green%3E0%7Cred)
10. Processes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.processes&dimensions=sql&value_color=green%3E0%7Cred)
11. Threads ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.threads&dimensions=sql&value_color=green%3E0%7Cred)
12. Major Faults (swap activity) ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.major_faults&dimensions=sql&value_color=green%3E0%7Cred)
13. Open Pipes ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.pipes&dimensions=sql&value_color=green%3E0%7Cred)
14. Open Sockets ![image](http://registry.my-netdata.io/api/v1/badge.svg?chart=apps.sockets&dimensions=sql&value_color=green%3E0%7Cred)

**Comment by elifatalay** [comment]
Thank you!!!

**Comment by garronej** [comment]
Hi,
This is cool but is there a way to configure the fact that only 7 characters are displayed?
Even when putting the cursor on the process label only 20 characters are shown in the tooltip.

In my case, for example, I want to track processes named:
* semasim root process
* semasim daemon
* semasim crypto worker
* semasim asterisk

And I end up with: 
![Screenshot 2020-03-27 at 18 00 03](https://user-images.githubusercontent.com/6702424/77780817-dddc7d80-7054-11ea-82b3-6b0d24b6eaaf.png)

It really damages the readability...

**Comment by ilyam8** [comment]
I think currently there is no way to configure/change it and yes, readability is far from good. Current dashboard has a lot of problems, there is a lot of plans to improve it. Not sure about roadmap/dates, but this is planned.

**Comment by aasutossh** [comment]
Hi, So if I want to monitor more than one apps, I need to put all of them entries in `/etc/netdata/apps_groups.conf`?

**Comment by vlvkobal** [comment]
It looks like the sum of `VmRSS` is less than the sum of `RssFile + RssShmem` in `/proc/<pid>/status` for every process listed. There is the following condition in apps.plugin
[`(w->status_vmrss > w->status_vmshared)?(w->status_vmrss - w->status_vmshared):0ULL`](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_plugin.c#L3539)
where
[`p->status_vmshared = p->status_rssfile + p->status_rssshmem;`](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_plugin.c#L1328)

@Ferroin do you have an idea how to calculate the real memory usage correctly?
