### ISSUE TITLE
[Feature Request] Exporting metric with current netdata version

### ISSUE THREAD

**Issue by Ziars** [firehol/netdata#3519]
Greetings!

I've recently discovered that among the netdata metrics being exported is missing one that contains the current netdata version. Such metric would be useful for external dashboards (no need in additional requests to find out the version of source-netdata). Could you please add such metric? I mean something like this:

`netdata_version="1.9.0"`

Here are such metrics, being stored in Prometheus, containing versions of Grafana:

`grafana_info{version="4.6.2"}`

Prometheus:

`prometheus_build_info{version="2.0.0"}`

Alertmanager:

`alertmanager_build_info{version="0.11.0"}`

For example, I'm using Netdata+Prometneus+Grafana stack, and this mechanism depends heavily on the version of netdata used as the exporter. Having an exported metric with the version of netdata, I could have created a small graph-panel on my dashboards, allowing me to check the used version of netdata at a glance, without having to do this manually.

**Comment by n0guest** [comment]
+1 for this feature. 

It could be very useful when you have many Netdata installations. And looks like it "common practice" for Prometheus exporters.

**Comment by ktsaou** [comment]
So, I should just add:

```
netdata_info{version="1.9.0"}
```

to the generated metrics?

**Comment by ktsaou** [comment]
hm... how should I do it when a netdata master is sending metrics for multiple netdata slaves? Each slave may be a different version.

**Comment by ktsaou** [comment]
I see we send per host this:

```
netdata_host_tags{instance="HOSTNAME",TAGS} 1 MS
```

Can we add the version there? Like:

```
netdata_host_tags{instance="HOSTNAME",version="VERSION",TAGS} 1 MS
```

**Comment by n0guest** [comment]
> hm... how should I do it when a netdata master is sending metrics for multiple netdata slaves? Each slave may be a different version.

I guess, you could add "instance" label to distinguish "netdata_info" metrics from different installations of netdata's. 

> netdata_host_tags{instance="HOSTNAME",TAGS} 1 MS

I vote for "netdata_info" as a name for the metric with "version/build/etc".

> I see we send per host this:

You mean it's already included in in exported metrics? If yes, then in which version? I checked "recent" 1.9.0 and didn't find "netdata_host_tags".

PS: BTW, what about "process_start_time_seconds" and other metrics about process info? (see previous comments).

**Comment by ktsaou** [comment]
In PR #3538 I added the netdata version with this:

single host metrics:

```
netdata_info{application="netdata",version="1.9.0-647-g5f251467_rolling"}
```

multi-host metrics:

```
netdata_info{instance="box",application="netdata",version="1.9.0-647-g5f251467_rolling"}
```

All the other metrics (netdata uptime, netdata memory, netdata sockets, etc), should be added as netdata charts (at the netdata section, at the end of the dashboard).

Please open a new issue for the ones you need but are missing.

**Comment by n0guest** [comment]
> netdata_info{application="netdata",version="1.9.0-647-g5f251467_rolling"}

Could you, please, explain why you've decided not to add instance label in "single host metrics"? 

It looks little inconsistient for me. If you're exporting instance label in "multi-host metics", then why not to export the same set of labels for "single host metrics"? Absence of "instance" label would be a headache when one is writing PromQL query. 

Would you mind add it in all scenarios?

**Comment by ktsaou** [comment]
hm... I don't know. I thought it was requested that way.

@brian-brazil I need you help on this:

When netdata sends data for a single host to prometheus it does not add `instance="HOSTNAME"`. This is only sent, when the netdata response includes multiple hosts.

This label is added to:

1. `netdata_info` - netdata application name and version
2. `netdata_host_tags` - custom tags configured per host
3. all the metrics

@n0guest suggests the `instance` should be added in single host responses too.
Should I add it?

**Comment by brian-brazil** [comment]
> It looks little inconsistient for me. If you're exporting instance label in "multi-host metics", then why not to export the same set of labels for "single host metrics"? Absence of "instance" label would be a headache when one is writing PromQL query.

Multi-host is not recommended from a Prometheus standpoint, it should be scraping targets directly and exposing an `instance` label in that case is bad form.

I'd say do whatever you usually do with single/multi host metrics.

> netdata_host_tags - custom tags configured per host

This should be `netdata_host_tags_info`.

**Comment by ktsaou** [comment]
> I'd say do whatever you usually do with single/multi host metrics.

hm... there is no "usual" in this case. I'll do whatever you like.

From your response I understand you want the single host response to be optimal, without `instance=`.

Then, for those that want to avoid multi-host configuration at prometheus and prefer to fetch multi-host data with one scrape from a netdata master, the `instance=` label is required to distinguish the metrics.

> This should be netdata_host_tags_info.

oops! will this change break existing queries? Are you sure this is required?

**Comment by brian-brazil** [comment]
> oops! will this change break existing queries? Are you sure this is required?

It would break existing queries. It's not required required, but this is the appropriate suffix for this sort of annotation-like metric.

**Comment by ktsaou** [comment]
Do you want me to add it another time with the right name, and deprecate the old?

**Comment by brian-brazil** [comment]
That'd be a good approach. You might want to wait a bit until the Info metric is more official.

**Comment by n0guest** [comment]
> Multi-host is not recommended from a Prometheus standpoint, it should be scraping targets directly and exposing an instance label in that case is bad form.

Yes, i know about "standart" recommendation. But it's our usage case for now. In fact, we're using Netdata master as "relay" for metrics of Netdata's slaves. Even considering all current downfalls and all possible future problems :)

>>I'd say do whatever you usually do with single/multi host metrics.
> hm... there is no "usual" in this case. I'll do whatever you like.

But i guess, it's already working exactly like this? For example, netdata_netdata_apps_cpu_milliseconds_persec_average from internal Netdata stats. In case with master plus few slaves this metrics comes from all Netdata's. I.e. from master and all slaves. And all received metics contain instance label (unique for master and all of slaves).
And yes, i know, that using Netdata's master as source of also slaves metrics - it's not "right" from Prometheus point of view. But then why was added "format=prometheus_all_hosts"? We're already here and we're already not doing all "exactly" as needed by Prometheus unspoken rules.

> Then, for those that want to avoid multi-host configuration at prometheus and prefer to fetch multi-host data with one scrape from a netdata master, the instance= label is required to distinguish the metrics.

It's exactly what i'm talking about. If one doesn't want to face possible problems (eg. master is down, all slaves metrics are unavailable), then don't use it. Use "standart" way with "single-host metrics" and direct access for pulling metrics.

PS: BTW, none of other Prometheus exporters have slave mode. So, each rule has an exception?)

**Comment by ktsaou** [comment]
> That'd be a good approach. You might want to wait a bit until the Info metric is more official.

done

@n0guest I think @brian-brazil expresses what should generally be good or practice for prometheus.

I understand the netdata master deviates a bit from it. It provides a feature that prometheus considers bad practice. I added this feature to netdata, mainly because users wanted it, independently of what prometheus suggests.

It is very simple to get a multi-host format from a standalone netdata. Just use `/api/v1/allmetrics?format=prometheus_all_hosts`. netdata will return the multi-host format, even if there is just a single host database.

So you have the choice. Either use `format=prometheus` or `format=prometheus_all_hosts`, everywhere!

**Comment by n0guest** [comment]
> It is very simple to get a multi-host format from a standalone netdata. Just use /api/v1/allmetrics?format=prometheus_all_hosts. netdata will return the multi-host format, even if there is just a single host database.

I know about this option and we're using it some time already. My main questions is simple. Will be "instance" label included in netdata_host_tags_info metrics from Netdata's slaves? I.e. if we're using format=prometheus_all_hosts, then we'll get "instance" tags of all Netdata, including slaves? 

PS: Imho, there is no point in having master's version and don't have slave's versions.

**Comment by ktsaou** [comment]
> Will be "instance" label included in netdata_host_tags_info metrics from Netdata's slaves? I.e. if we're using format=prometheus_all_hosts, then we'll get "instance" tags of all Netdata, including slaves?

host tags are propagated with the streaming protocol. So, netdata proxies and masters will report the host tags configured at each slave.

With PR #3538 , the netdata version is also propagated. So, the master will report (to backends, on the dashboard, on upstream netdata servers), the version of the slave collecting the metrics.

**Comment by n0guest** [comment]
> With PR #3538 , the netdata version is also propagated. So, the master will report (to backends, on the dashboard, on upstream netdata servers), the version of the slave collecting the metrics.

Thank you! As i understand, this feature will be included in next release? Do you have any estimate dates for it (i.e. for the next release)?

**Comment by ktsaou** [comment]
merged it.

I am waiting a couple of issues that fix bugs.
I would say v1.10 will be released in the next 15 days.

**Comment by l2isbad** [comment]
> next 15 days

1st april :thinking:

**Comment by ktsaou** [comment]
ok, let's try to make it in March then...

**Comment by raqqun** [comment]
@ktsaou 

Unfortunately, i think this merge caused a parsing error with prometheus. From today my  prometheus server can't scrape netdata metrics and netdata target is always DOWN.

```bash
curl -s http://0.0.0.0:19999/api/v1/allmetrics?format=prometheus | ./promtool check metrics
error while linting: text format parsing error in line 1: expected float as value, got ""
```

**Comment by ktsaou** [comment]
merged the fix. Sorry for that! My bad!
