### ISSUE TITLE
How do I debug a python plugin that is not a "Service"?

### ISSUE THREAD

**Issue by nirmalthacker** [firehol/netdata#3522]
Hi

I have a custom plugin written in Python that is not using any of the Framework Services classes such as URLService, LogService etc. In fact I merely adopted this script and turned it to generate and spit out data that was relevant for my use case: See script in this issue https://github.com/firehol/netdata/issues/206 by user: ktsaou

It runs great and I can see the charts in netdata but I really like the ability to debug a Service based script. When I try to debug this script I hit an exception:

'module' object has no attribute 'Service'

I already understand what is going on, i think : the python plugin daemon probably runs all charts that are based on the Service architecture, which leads me to the questions:

1. How do I debug a plugin that is a simply Python script and doesn't use the Service classes
2. What runs these scripts, if its not the python plugin daemon?
3. Maybe I should simply implement a custom class that inherits the base Service class to get around this? Is there any advantage to this?
4. Is there a way I can see the loading, output of netdata's internal and external plugins on the command line? This is useful for me in scenarios where I don't want to load up a browser in a remote machine via an SSH tunnel.

Thanks!

**Comment by l2isbad** [comment]
Well, the easiest way is to [create](https://github.com/firehol/netdata/wiki/How-to-write-new-module) a `Service` class which inherits from [SimpleService] (`SimpleService` inherits from Threading)(https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/SimpleService.py#L42).

In general `python.d.plugin` [initialize all the Service classes](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L174). And [start() them](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L337-L342).

**Comment by nirmalthacker** [comment]
Gotcha, thanks!
