### ISSUE TITLE
Badge Update vs. Chart Update

### ISSUE THREAD

**Issue by sereeds** [firehol/netdata#3525]
I have followed the guide regarding "Custom Dashboards" to create a page with some charts and a few badges.  I am using the java script method that is shown to update the badges.  However, I notice that when the page in not in focus, the charts do not update as intended, but the badges continue to update.

One great feature that I like about netdata is how it does not update the charts to the client, unless the page is in focus.  Is there some way I can have the badges update in the same way, only when the page is active?

**Comment by ktsaou** [comment]
I have created a simple javascript file you can include in your page:

https://github.com/firehol/netdata/blob/master/web/refresh-badges.js

The header of the file, says how to use it.

**Comment by ktsaou** [comment]
I updated the wiki to point to that file too: https://github.com/firehol/netdata/wiki/Generating-Badges

**Comment by sereeds** [comment]
It works great, thank you.

Looking at the script, it appears to work on badges without the class applied, as you're parsing the src url for a match.
So l assume that I don't need to use class="netdata-badge" on the img tags now?
Or maybe you want to change the script to require the class?

Either way, charts and badges update perfectly using your script.
Thanks.

**Comment by ktsaou** [comment]
> Looking at the script, it appears to work on badges without the class applied, as you're parsing the src url for a match.

yes, I tried to avoid the classes, so that you can copy-paste the URLs without worrying about anything else.

**Comment by ktsaou** [comment]
perfect!
