### ISSUE TITLE
"pushed metrics must not have timestamps" when pushing metrics to pushgateway

### ISSUE THREAD

**Issue by tompluess** [firehol/netdata#3526]
When pushing metrics from 
`/api/v1/allmetrics?format=prometheus`
to a [Prometheus Pushgateway](https://github.com/prometheus/pushgateway) I get a `400 Bad Request, pushed metrics must not have timestamps`.

Setup
* Image titpetric/netdata:latest
* Prometheus 2.2
* Prometheus Pushgateway 0.4.0

Is there an option to omit timestamps (e.g. `&timestamps=no`)?
Or any other hint how to integrate netdata with a Pushgateway?

**Comment by Vad1mo** [comment]
Reading on the [timestamp][1] concept, I think you should also raise the same question on [prometheus/pushgateway][2]. 


[1]: https://github.com/prometheus/pushgateway#about-timestamps
[2]: https://github.com/prometheus/pushgateway

**Comment by ktsaou** [comment]
In PR #3533

**Comment by ktsaou** [comment]
Updated the wiki too: https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus#timestamps

**Comment by tompluess** [comment]
@ktsaou thank you for the immediate PR!
`&timestamps=no` works for me as expected!
