### ISSUE TITLE
netdata on cloned ec2 instance

### ISSUE THREAD

**Issue by dankott** [firehol/netdata#3545]
server was cloned with netdata already installed and, when it is added to the registry, the server that it was cloned from disappears from the registry.

**Comment by ktsaou** [comment]
Each netdata has a unique id stored at `/var/lib/netdata/registry//netdata.public.unique.id`.
Please do not clone this file, as it uniquely identifies each netdata.
If you delete this file, netdata will create a new one the next time it starts.

**Comment by dankott** [comment]
thank you!
