### ISSUE TITLE
Swappiness?

### ISSUE THREAD

**Issue by FallingSnow** [firehol/netdata#355]
Show the current swappiness next to the swap graph using `/proc/sys/vm/swappiness`.

**Comment by simonnagl** [comment]
Does swappiness vary on your system?
Is history of swappiness needed?

**Comment by FallingSnow** [comment]
Not a graph. Just a number, next to the title showing the current number. So I can relate how much swap is used related to my current swappiness.

**Comment by ktsaou** [comment]
> Not a graph. Just a number, next to the title showing the current number.

This is what I understood too. To collect it and show it in the title of a chart or something.

Probably a new feature in netdata is needed to maintain just a few name-value pairs that will be exposed to the dashboard to be presented somewhere. If we do it that way, we could even show the processors of your computer, the version of mysql, the version of the kernel, etc.

**Comment by ktsaou** [comment]
I will collect all such requests to #531.
I am closing this. If you need to add something please follow #531.
