### ISSUE TITLE
Unable to get the web_log timings and requests size charts

### ISSUE THREAD

**Issue by h0gar** [firehol/netdata#3553]
I installed netdata out of the box. Everything is working fine except one thing.

I noticed under "web log apache" I had only:

- responses
- bandwith
- http methods
- http versions
- ip protocols
- clients

So I then followed the instructions here: https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L89

So in both /etc/apache2/sites-available/000-default.conf and /etc/apache2/sites-available/000-default-le-ssl.conf I added the 3 lines.

I restarted apache and I have the logs. For example: 

`xx.xx.xx.xx - - [18/Mar/2018:12:06:53 +0100] "GET /cee2ed8ef60051df2c4a12c5ab84acd2.png HTTP/1.1" 200 51190 1359 761 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"`

Then I restarted netdata with: 

`systemctl restart netdata`

Now I refreshed the dashboard a couple of times, but the web_log timings and requests size charts are not appearing.

I tried running the plugin manually with:

`sudo su -s /bin/bash netdata`
`/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 apache`

but it seems to be working fine. I have a bunch of:

```
BEGIN apache_local.bytesperreq 1000084
SET 'size_req' = 1657
END

BEGIN apache_local.connections 1000084
SET 'connections' = 2
END

BEGIN apache_local.bytespersec 1000084
SET 'size_sec' = 1762
END

BEGIN apache_local.reqpersec 1000084
SET 'requests_sec' = 1
END

BEGIN apache_local.requests 1000084
SET 'requests' = 454
END

BEGIN apache_local.net 1000084
SET 'sent' = 735
END
```

I checked /var/log/netdata/error.log but there is nothing interesting.

What else should I do?

**Comment by cloudz** [comment]
Did you run the command as user "netdata" or as your regular root/privileged user?

**Comment by h0gar** [comment]
Oh yes, sorry I forgot to mention that. I did"

`sudo su -s /bin/bash netdata
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 apache`

**Comment by h0gar** [comment]
Acutally now I have the same problem with postgresql. The postgresql plugin is running I don't see the charts on the dashboard. It seems I need to do something to enable new charts no?

**Comment by h0gar** [comment]
Hum, suddenly after another netdata restart I got all the charts. Sorry for wasting your time.
