### ISSUE TITLE
remote alarms

### ISSUE THREAD

**Issue by flipchan** [firehol/netdata#3555]
im trying to get netdata to give me alarms if two external servers stop sending me data

My case:
```
Server A runs netdata 
Server B and C runs important services
if one of those servers/processes dies i want an alarm throw the webui 
```

as far as i can c you can only alarm based on local services and the api doesnt support this

So i basicly need netdata to give me alarms if a process on server B or C dies
and i what i think would be a solution is the make a script and send like a heartbeat/"everything is okey" package and if netdata doesnt get that package within a certain time frame it gives me an critical alarm.

Im not sure how to solve this doe..

is this a feature?

i cant be able to find any similar usecase that is implemented

**Comment by ktsaou** [comment]
Hi - thanks for using github!

netdata can collect process information, only when it runs on the machine the processes run. Generally, netdata is quite light and safe to run everywhere, even on production servers.

If however you can't run it on servers B and C (I would love to know why), you can use 2 plugins we added a few days ago:

1. `httpcheck` that can query a remote web server (or API)
2. `portcheck` that can check if any remote tcp port is listening for connections

Both can be configured via `/etc/netdata/python.d/` (check a `.conf` file with the name of the plugin).

Once you configure it, you can check it with this:

```sh
# become user netdata
sudo su -s /bin/sh netdata

# run the httpcheck plugin by hand in debug mode
/usr/libexec/netdata/plugins.d/python.d.plugin debug trace 1 httpcheck
```

**Comment by flipchan** [comment]
thanks for the quick reply,

Would it be possible to write a python script as a plugin that listens/binds 0.0.0.0 and if i dont recieve a buffer within X amount of time it alerts, or if it doesnt write to a logfile within X amount of time it alarms ?

**Comment by ktsaou** [comment]
yes, you can do this.

Write your python code to do whatever you like. Then write a simple netdata plugin to get the status from your daemon.

It seems complicated though. Why don't you just run netdata on the remote hosts? If you do, netdata will monitor quite some information about your processes. Check this: #3516

**Comment by flipchan** [comment]
if i run multiple netdata instances can i get all netdata alarms in the same webui/browser window?

**Comment by ktsaou** [comment]
late reply:

> if i run multiple netdata instances can i get all netdata alarms in the same webui/browser window?

unfortunately no. You have to have one tab open for every netdata you have. It is probably better to configure a notification method to receive notifications.
