### ISSUE TITLE
Any time monitoring

### ISSUE THREAD

**Issue by elifatalay** [firehol/netdata#3562]
Hi, 

Our devices have been working for days. We want our data to be registered without constantly monitoring our devices. We should know what happened on any day and time. As far as Netdata is concerned, we can only scroll backwards. This is not a useful solution from the point of view. How can I do that?

Thanks...

**Comment by ktsaou** [comment]
So, you want longer history? What do you mean with "we want our data to be registered"?

**Comment by elifatalay** [comment]
Yes, quite a long history. For example, I want to see a moment three days ago. Or a week ago.

**Comment by ktsaou** [comment]
late reply: you can send netdata metrics to a time-series db: graphite, prometheus, opentsdb and all compatible ones.

Closing this, but you need help, just post.
