### ISSUE TITLE
Netdata copy files

### ISSUE THREAD

**Issue by elifatalay** [firehol/netdata#3570]
Hi,

Two copy files are created under the netdata folder (.orig and .old). What's the reason for this? And how can we prevent it? Example is below.
![image](https://user-images.githubusercontent.com/3518836/37829798-86c9bb52-2eb1-11e8-9324-91cc3b63a72c.png)

Thank you!

**Comment by ktsaou** [comment]
The `.orig` file is the version shipped with netdata. So if at any time you need to reset a config to the defaults, copy the `.conf.orig` to `.conf`.

The `.old` file is the version you had installed before updating netdata. So if an netdata update broke one of your configs, you have a backup.

**Comment by elifatalay** [comment]
Thank you!
