### ISSUE TITLE
Timestamp on custom dashboard?

### ISSUE THREAD

**Issue by ChrisEt** [firehol/netdata#3571]
We have built a nice dashboard with a lot of gauges, easypiecharts and dygrahps to visualize what our cluster is currently doing. Now we realized that the current timestamp is shown nowhere on our dashboard! (Note that when mousing over a dygraph it is possible to inspect specific timestamps.)

What would be the most elegant way to incorporate this timestamp on a custom dashboard?

**Comment by ktsaou** [comment]
Could you please post a screenshot?
dygraphs should provide enough timestamps...

**Comment by ChrisEt** [comment]
![hermes cluster dashboard](https://user-images.githubusercontent.com/5184690/37893251-bc48f2f4-30da-11e8-86da-9c5420b1e76b.png)

Have a look at this screenshot. When the user mouses over one of the dygraphs, all charts show the values of that respective point in time. We'd like to show that timestamp somewhere in the header, is there a way to do this?

**Comment by ktsaou** [comment]
hm... nice request...
let me check how it can be done.

**Comment by ktsaou** [comment]
in PR #3575

**Comment by ChrisEt** [comment]
That's a great feature, many thanks for implementing this so quickly! 

We added one small workaround though, beaucse we realized "selection" keeps its value even though the user has moused away:
```javascript
    this.updateChartWithData = function (data) {
        // ...
        if (this.foreign_element_selection !== null)
            this.foreign_element_selection.innerText = "";
```
The idea being that "selection" only shows a timestamp when the user has selected a specific value in the diagram. But I'm still not 100% happy with that solution 😄

**Comment by ktsaou** [comment]
ok nice.
In PR #3580 the final touch of clearing the selection date when mouse hover ends.
