### ISSUE TITLE
How to install a specific version

### ISSUE THREAD

**Issue by promethe42** [firehol/netdata#3585]
Hi,

I need to be able to download and install a specific version.
I've read this doc:

https://github.com/firehol/netdata/wiki/Installation#x86_64-pre-built-binary-for-any-linux

I did not found any documentation about that.
I also did not find [any relevant issue](https://github.com/firehol/netdata/issues?utf8=%E2%9C%93&q=is%3Aissue+version+install).

I've downloaded `kickstart-static64.sh` and I don't see any option to specify the version to download/install.

Please advise.

**Comment by ktsaou** [comment]
Hi, download the file you like from https://github.com/firehol/binary-packages
Then, just run it on a terminal with `sudo`.
