### ISSUE TITLE
How to change netdata dashboard from / to /netdata

### ISSUE THREAD

**Issue by Macley-Kun** [firehol/netdata#3588]
Hi!

I've bin using your work for a little while and decided to customize some little stuff here and there. I managed to change port but wanna change the following:

http://mysite.com:19999/ <-shows netdata 👍 
to this
http://mysite.com:19999/netdata

I'm not able to find this config in the netdata.conf

Any hints or tips how i can change this easly? (and maybe update proof?(So the config stays where it at after updating))

**Comment by Macley-Kun** [comment]
Um, i haven't bin able to get this to work sadly...

I run apache and lighttpd. But i think netdata uses it's default configuration to host the dashboard. Any clue where this file is located? Because i've searched high and low haha

**Comment by ktsaou** [comment]
netdata does not use anything from apache. netdata is self sustained. you only need to configure a virtual path of apache to act as a proxy, forwarding the requests to another web server (netdata).

The config examples posted at the wiki work. I am using them all the time.

https://github.com/firehol/netdata/wiki/Running-behind-apache

**Comment by Macley-Kun** [comment]
Ah thats how iT works! Ill try iT out again in the next days. I’ll close the issue immediately after I’ve got it working.

**Comment by Macley-Kun** [comment]
Good news, i finnaly figured out how to do it haha.

# Solution to run 2 sites on Apache2 on the same port
For Debian stretch only!
```
sudo apt-get install apache2 -y
sudo a2enmod proxy
sudo a2enmod proxy_http
sudo a2enmod rewrite
systemctl restart apache2
```
What i always did wrong was making two: 
```
<VirtualHost *:80>
~my website stuff~
<VirtualHost>

<VirtualHost *:80>
~netdata proxy stuff~
<VirtualHost>
```

Simpley put everything in *one <VirtualHost *:80><VirtualHost>!*

After a reboot (to be sure) everything works amazingly!

Thank you for making this awsome application. If your curious about what i made you can visit http://deltabot.tk/netdata

Have a great weekend!
