### ISSUE TITLE
httpcheck plugin doesn't send clear event to alerta

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#3590]
I'm very excited about the new httpcheck plugin in 1.10 and also the alerta.io integration. Immediately started to try both together and most of it works really great. Clearing alerts for other events seems to be working OK but those for httpcheck don't. I have done some analysis and found this:

When going to the netdata dashboard and look at the alarm log I see these 4 events:

```
{
  "header": [
    ["Event Date", "Unique ID", "Alarm ID", "Alarm Event ID", "Chart", "Alarm", "Friendly Value", "Old Value", "Value", "Status", "Updated Status", "Updated By ID", "Updates ID"]
  ],
  "data": [{
    "Event Date": "15:06:51",
    "Unique ID": "1477471154",
    "Alarm ID": "1477140618",
    "Alarm Event ID": "38",
    "Chart": "httpcheck_WB_FIMF_CN.response_time",
    "Alarm": "web service slow",
    "Friendly Value": "695.7 ms",
    "Old Value": "713.33",
    "Value": "695.71",
    "Status": "CLEAR",
    "Updated Status": "CURRENT",
    "Updated By ID": "-",
    "Updates ID": "1477471153"
  }, {
    "Event Date": "15:05:41",
    "Unique ID": "1477471153",
    "Alarm ID": "1477140618",
    "Alarm Event ID": "37",
    "Chart": "httpcheck_WB_FIMF_CN.response_time",
    "Alarm": "web service slow",
    "Friendly Value": "997.8 ms",
    "Old Value": "1063.45",
    "Value": "997.76",
    "Status": "WARNING",
    "Updated Status": "UPDATED",
    "Updated By ID": "1477471154",
    "Updates ID": "1477471152"
  }, {
    "Event Date": "15:04:51",
    "Unique ID": "1477471152",
    "Alarm ID": "1477140618",
    "Alarm Event ID": "36",
    "Chart": "httpcheck_WB_FIMF_CN.response_time",
    "Alarm": "web service slow",
    "Friendly Value": "1081 ms",
    "Old Value": "1015.37",
    "Value": "1081.07",
    "Status": "CRITICAL",
    "Updated Status": "UPDATED",
    "Updated By ID": "1477471153",
    "Updates ID": "1477471150"
  }, {
    "Event Date": "15:03:21",
    "Unique ID": "1477471150",
    "Alarm ID": "1477140618",
    "Alarm Event ID": "35",
    "Chart": "httpcheck_WB_FIMF_CN.response_time",
    "Alarm": "web service slow",
    "Friendly Value": "687.9 ms",
    "Old Value": "544.6",
    "Value": "687.86",
    "Status": "WARNING",
    "Updated Status": "UPDATED",
    "Updated By ID": "1477471152",
    "Updates ID": "1477471133"
  }]
}
```

The first 2 are getting through to are shown in /var/log/netdata/error.log but the other 2 don't and that's why the alerts stays on CRITICAL in alerts.io:

```
2018-03-31 14:28:21: charts.d: ERROR: opensips: module's 'opensips' check() function reports failure.
2018-03-31 15:03:21: alarm-notify.sh: INFO: sent alerta notification for: pmon1 httpcheck_WB_FIMF_CN.response_time.web_service_slow is WARNING to 'Paragon'
2018-03-31 15:03:27: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'httpcheck_WB_FIMF_CN.response_length' on host 'pmon1' is 0.31909 secs in the future (counter #54348, update #53465). Adjusting it to current time.
2018-03-31 15:03:27: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'httpcheck_WB_FIMF_CN.response_time' on host 'pmon1' is 0.31903 secs in the future (counter #54348, update #53465). Adjusting it to current time.
2018-03-31 15:04:21: alarm-notify.sh: INFO: sent alerta notification for: pmon1 httpcheck_WB_FIMF_CN.status.web_service_unreachable is WARNING to 'Paragon'
2018-03-31 15:04:51: alarm-notify.sh: INFO: sent alerta notification for: pmon1 httpcheck_WB_FIMF_CN.response_time.web_service_slow is CRITICAL to 'Paragon'
2018-03-31 15:57:58: netdata INFO  : WEB_SERVER[static2] : POLLFD: LISTENER: client slot 4 (fd 42) from '134.3.125.181:53082' is idle for more than 60 seconds - closing it. 
```

Any idea what could go wrong here?

**Comment by jurgenhaas** [comment]
Ah, just found `options: no-clear-notification` in the health config for httpcheck and I could imagine that (a) this is the reason why the clear event is not sent and (b) if I removed that option that probably clear events would be sent all the time? If that's true, is there any way around this?

**Comment by ktsaou** [comment]
The option `no-clear-notification` does indeed prevent the clear notification to be sent.

We enable this option when the clear notification will be misleading. In this particular case, we compare the last 3 minutes latency to the last 1 hour latency. So, lets assume the last 1h latency is 10ms and the last 3m latency is 100ms. As time passes (the collected latency remains at 100ms), the last 1h average moves towards 100ms. When it reaches 50ms netdata will send a clear notification, although the latency is still 100ms.

This kind of alarm is dynamic. It does not have a fixed latency in it. It would require the alarm to have another capability (define own variables), which is not available currently in netdata...

**Comment by jurgenhaas** [comment]
Thanks @ktsaou I do understand now what's going on. What confuses me though is that the dashboard is receiving a clear event and that left me with an inconsistent experience.

With regard to self-defined variables, wouldn't it be possible to define the thresholds for latency with each of the charts in /etc/netdata/python.d/httpcheck.conf?

**Comment by ne0c0de** [comment]
I just try to test the httpcheck plugin and uncomment to see the example of the warning.

I edited the file located on /etc/netdata/python.d/httpcheck.conf and uncomment these lines:

```
# jira:
#   url: 'https://jira.localdomain/'
```

and then restarted the netdata service. on error log of netdata i saw these lines:

```
2018-04-05 11:30:58: python.d ERROR: plugin: main: module load config: 'httpcheck' => [FAILED]
  in "/etc/netdata/python.d/httpcheck.conf", line 38, column 1
  in "/etc/netdata/python.d/httpcheck.conf", line 100, column 2
2018-04-05 11:30:59: python.d ERROR: httpcheck: httpcheck: URL is not defined or type is not <str>
2018-04-05 11:30:59: python.d INFO: httpcheck: httpcheck: check() => [FAILED]
```

line 38:
```
chart_cleanup: 0
```

line 100:
```
 jira:
```

what am i doing wrong? @jurgenhaas can you please share your config for httpscheck for an example?

**Comment by jurgenhaas** [comment]
I left the original file and appended blocks for each check at the end of the file. One example is this:

```
f4e9a10f-510a-53fe-9cc0-7812b0ddf6d3:
    name: 'LakeDrops'
    url: 'https://www.lakedrops.com'
    regex: LakeDrops
```

**Comment by ktsaou** [comment]
Late reply (sorry, I missed this somehow).

> Thanks @ktsaou I do understand now what's going on. What confuses me though is that the dashboard is receiving a clear event and that left me with an inconsistent experience.

hm.... yes the dashboard ignores this option. Generally the dashboard does not respect any of the alarm options (it ignores notification delays for example). This is on purpose. I wanted the dashboard to be more interactive.

The truth is that the alarm is really cleared. So the dashboard is telling the truth.
 
> With regard to self-defined variables, wouldn't it be possible to define the thresholds for latency with each of the charts in /etc/netdata/python.d/httpcheck.conf?

You can copy-paste the entire alarm, change the `template` keyword to `alarm` and at the `on` line give the chart id/name you are interested. You can mix templates and alarms (same alarm name). netdata will prefer an alarm when if finds one for the chart in question, and if it does not exist, it will use the template.

**Comment by ktsaou** [comment]
I am closing this. But feel free to post.
