### ISSUE TITLE
Clearly wrong CPU usage info on FreeNAS

### ISSUE THREAD

**Issue by skwerlman** [firehol/netdata#3591]
OS: FreeNAS 11.1-U4
Version: netdata v1.8.0

netdata occasionally reports CPU usage info that is very obviously wrong, such as cron using more than 1,400,000,000% of the CPU. These points do occur at about the same time as real cron jobs, but they are way, _way_, _**way**_ too high to be correct for a 6-core machine.

![2018-04-01-102940_1553x442_scrot](https://user-images.githubusercontent.com/6954107/38174494-f81a1860-359b-11e8-99fa-ab2fc6c1c5a3.png)

The spikes only appear in the following graphs:
- apps.cpu
- groups.cpu
- users.cpu

The actual cpu usage (according to netdata!) is under 20% during these spikes

**Comment by ktsaou** [comment]
Could you please install netdata 1.10? I believe this is fixed.

**Comment by skwerlman** [comment]
unfortunately, 1.8.0 is the version bundled with FreeNAS at the moment. if it's already been fixed, I'll pester them to update it. thanks
