### ISSUE TITLE
Supervisord monitoring

### ISSUE THREAD

**Issue by ne0c0de** [firehol/netdata#3598]
Hi,

I'm using supervisord (http://supervisord.org/) to run background services.

I want to monitor these processes over netdata and get alerts if some the of defined processes are down. Is it possible with any plugin?

**Comment by Ferroin** [comment]
As far as I know, there's not currently any plugin that does this for arbitrary processes (though many of the plugins for collecting statistics from server software will check that said software is running and send an alert if it isn't).

However, if you just want alerts when processes are down, you probably don't need Netdata to handle them at all.  Take a look at [supervisor-alert](https://github.com/rahiel/supervisor-alert), or more generically [the supervisord events API](http://supervisord.org/events.html).

**Comment by ne0c0de** [comment]
Thank you so much Ferroin,

Actually supervisor-alert is the exact thing that i'm looking for. However i wrote a code snippet while waiting and would like to share here (as it's doing same thing via nodejs)

https://gist.github.com/ne0c0de/43e27fc6f6f9d51b327376e5c3d73992
