### ISSUE TITLE
Support for mentions via slack alerts

### ISSUE THREAD

**Issue by jmordica** [firehol/netdata#3604]
Is there a way currently to allow for mentions to be added to alerts when using slack notifications? The issue is even when turning notifications ON for all messages in a particular channel, the push and/or desktop notification doesn't fire on receiving webhooks. The workaround here would be (I assume) to add a mention payload to the webhook. Thoughts?

Thanks!

**Comment by ktsaou** [comment]
This is an option on the slack client:

![image](https://user-images.githubusercontent.com/2662304/41265810-bb28158a-6dfc-11e8-855d-442b45b6c2c0.png)

Switch it to "All new messages" and you are done.

I am closing this, but you can still post.
