### ISSUE TITLE
Netdata taking more than 30% CPU on an average

### ISSUE THREAD

**Issue by samof76** [firehol/netdata#3605]
![screenshot from 2018-04-04 18 08 14](https://user-images.githubusercontent.com/98111/38308088-99d9a80c-3833-11e8-9e08-9956cfce1831.png)
Now if you need more info, I would be pleased to provide. Just guide me on what info you would require.

**Comment by ktsaou** [comment]
Do you have other netdata mirrored to this host?
Could you please grep the pid that takes so much CPU to `/var/log/netdata/error.log`?

**Comment by samof76** [comment]
I will close this as, I have encountered this again now.
