### ISSUE TITLE
Linking in ui of docker containers does not work

### ISSUE THREAD

**Issue by DavidSichau** [firehol/netdata#361]
It seems that there is a small typo in the linking of docker containers:

In the menu the `href` is e.g.: `cgroup_cleanup-57089_1638cbbb`

And the headings have the `id`: `cgroup_cleanup-57089.1638cbbb`

The only difference is the `_` vs `.`

**Comment by ktsaou** [comment]
Thanks for tracing it!
Merged the fix.

**Comment by DavidSichau** [comment]
@ktsaou Thanks for the fast fix :+1:
