### ISSUE TITLE
How to enable mongoDB monitoring?

### ISSUE THREAD

**Issue by ranabasheer** [firehol/netdata#3610]
Hello all,
I have installed the software and am impressed by it. Now I want the software to monitor MongoDB instance running on localhost. How do I go about doing this? I read the docs and looked for similar issues in the Wiki. 

I see that I need to create a configuration which is listed here: https://github.com/firehol/netdata/tree/master/python.d#mongodb

Where do I create the configuration to enable the monitoring?

Any pointers would be great help.

**Comment by jubel02** [comment]
It has to monitor all known services by default, if you installed mongodb after installing netdata, you should restart netdata service and it should be there. If you already had installed mongodb before installing netdata, i have no idea, it should be already listed. Mine is working by default.

**Comment by l2isbad** [comment]
@ranabasheer 

https://github.com/firehol/netdata/tree/master/python.d#mongodb

Do you have `python-pymongo` installed?

What about [credentials](https://github.com/firehol/netdata/blob/master/conf.d/python.d/mongodb.conf#L69-L72)?

plugin debug mode
```
sudo su -s /bin/bash netdata
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mongodb
```

**Comment by vrst37** [comment]
I have tried all sequences, the graph just does not show up on the webpage. I can see the communication between the script (in debug mode) with the mongoDB.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/3614#issuecomment-380104949

(if https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf#L14 `no` module must be explicitly enabled)

**Comment by vrst37** [comment]
Ok I did what you said, and I am confused now. I am getting pymongo not installed error.

    edyza@ubuntu:/var/log/netdata$ grep mongo /opt/netdata/var/log/netdata/error.log
    2018-04-11 01:25:16: python.d ERROR: mongodb: local: Pymongo module is needed to use mongodb.chart.py
    2018-04-11 01:25:16: python.d INFO: mongodb: local: check() => [FAILED]

But this is so strange, I have installed pymongo for both pythons on my machine. 

    edyza@ubuntu:/var/log/netdata$ python
    Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pymongo
    >>> 

    edyza@ubuntu:/var/log/netdata$ python3
    Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pymongo
    >>> 

    edyza@ubuntu:/var/log/netdata$ which python
    /usr/bin/python
    edyza@ubuntu:/var/log/netdata$ which python3
    /usr/bin/python3

Can you shed some light on which python is being used? Really appreciate your quick responses.

**Comment by l2isbad** [comment]
looks like it's `pythonpath` issue
As you see the module did not manage to import the library.

> Edit /etc/netdata/netdata.conf and set PYTHONPATH environment variable =

also see https://github.com/firehol/netdata/issues/3416

**Comment by vrst37** [comment]
Still no luck, I tried to install the pymongo package (directly unzipped the pymongo) into the python_modules folder. I still got the error.

Then I tried to set the PYTHONPATH to /usr/bin/python and no luck, then I tried the path /usr/bin/python3 and no luck.

Any other tips?

**Comment by vrst37** [comment]
So here are a few other things I tried:

I found that that the packages are being run from /opt/netdata/usr/libexec/netdata/python.d

So I went and edited the source code and outputted the following line:

Line 1 is the sys.path, Line 2 is python version (it is using 2.7), Line 3 is current working directory and Line 4 is standard error message

    2018-04-11 02:27:54: python.d ERROR: mongodb: local: ['/opt/netdata/usr/libexec/netdata/plugins.d', '/usr/local/lib/python2.7/dist-packages/memory_profiler-0.52.0-py2.7.egg', '/opt/netdata/etc/netdata', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/opt/netdata/usr/libexec/netdata/python.d/python_modules']
    2018-04-11 02:27:54: python.d ERROR: mongodb: local: sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
    2018-04-11 02:27:54: python.d ERROR: mongodb: local: /opt/netdata/etc/netdata
    2018-04-11 02:27:54: python.d ERROR: mongodb: local: Pymongo module is needed to use mongodb.chart.py
    2018-04-11 02:27:54: python.d INFO: mongodb: local: check() => [FAILED]

**Comment by l2isbad** [comment]
https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH
it's not path to `python`

`pymongo` dir?

**Comment by vrst37** [comment]
To this I say amen. 

The trick is to install pymongo in the folder named "python_module".

So here is the first step: run the command:
    pip2 install --target=/opt/netdata/usr/libexec/netdata/python.d/python_modules pymongo

and if it gives you a permission error, then run the command:
    sudo -H pip2 install --target=/opt/netdata/usr/libexec/netdata/python.d/python_modules pymongo

I think there is lot of good information in this thread, I will write a small post on it, do you think I should write it in the wiki page?

**Comment by l2isbad** [comment]
Well, no. 

> The trick is to install pymongo in the folder named "python_module".

this is dirty workaround :smile: 

I suggest to remove it and install again. Preferably from repo (`apt-get install python-pymongo `if you are on deb/ununtu)

**Comment by vrst37** [comment]
Why can we not make this a default? Why must the pymongo be installed
manually?

**Comment by vrst37** [comment]
If the apt-get can install the package, the install script should be able install the pymongo when it requests sudo privileges from the user, unless I am missing something.

**Comment by l2isbad** [comment]
> Why must the pymongo be installed
> manually?

https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system

**Comment by l2isbad** [comment]
**Basic** install doesn't install all the stuff needed by all python modules.

**Comment by ktsaou** [comment]
I am closing this, but if you need help, just post.

**Comment by shinebayar-g** [comment]
I encountered same issue while installing Netdata prepackaged version. It was obvious that I was missing required packages.

https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system

Thanks to both of you resolving this issue.

**Comment by ThomasOrlita** [comment]
> apt-get install python-pymongo

Installing pymongo using this command made it work on Debian 10. I was trying to do `pip3` install pymongo`, but that didn't work. I'd be really helpful if this command was mentioned in the wiki.

**Comment by ilyam8** [comment]
> pip3 install pymongo

It is very likey because of default python verion on your system is python2.

`pip3 install pymongo` + make pythond.plugin to use py3 would do too

**Comment by mailinglists35** [comment]
sorry to bump into your old dead thread, does anyone know how to DISABLE mongodb in netdata, which seem to be ENABLED by default?
the reason is it does periodic tcp connects to localhost:27017, and I have strict firewall rules and I don't want to create exceptions for it and it annoys in my firewall logs every 10 seconds.

````
$ journalctl -k -S 16:50 --no-hostname |grep 27017
Mar 07 16:50:00 kernel: RFC3964_IPv4_REJECT: IN= OUT=lo SRC=0000:0000:0000:0000:0000:0000:0000:0001 DST=0000:0000:0000:0000:0000:0000:0000:0001 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=553348 PROTO=TCP SPT=52466 DPT=27017 WINDOW=65476 RES=0x00 SYN URGP=0
Mar 07 16:50:09 kernel: RFC3964_IPv4_REJECT: IN= OUT=lo SRC=0000:0000:0000:0000:0000:0000:0000:0001 DST=0000:0000:0000:0000:0000:0000:0000:0001 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=191248 PROTO=TCP SPT=40174 DPT=27017 WINDOW=65476 RES=0x00 SYN URGP=0
Mar 07 16:50:10 kernel: RFC3964_IPv4_REJECT: IN= OUT=lo SRC=0000:0000:0000:0000:0000:0000:0000:0001 DST=0000:0000:0000:0000:0000:0000:0000:0001 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=343282 PROTO=TCP SPT=40174 DPT=27017 WINDOW=65476 RES=0x00 SYN URGP=0
Mar 07 16:50:19 kernel: RFC3964_IPv4_REJECT: IN= OUT=lo SRC=0000:0000:0000:0000:0000:0000:0000:0001 DST=0000:0000:0000:0000:0000:0000:0000:0001 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=433810 PROTO=TCP SPT=44740 DPT=27017 WINDOW=65476 RES=0x00 SYN URGP=0
Mar 07 16:50:20 kernel: RFC3964_IPv4_REJECT: IN= OUT=lo SRC=0000:0000:0000:0000:0000:0000:0000:0001 DST=0000:0000:0000:0000:0000:0000:0000:0001 LEN=80 TC=0 HOPLIMIT=64 FLOWLBL=587553 PROTO=TCP SPT=44740 DPT=27017 WINDOW=65476 RES=0x00 SYN URGP=0
````
