### ISSUE TITLE
Badges with binary data, ON OFF, true false

### ISSUE THREAD

**Issue by sereeds** [firehol/netdata#3613]
I am collecting some binary data with netdata, it's always either 1 or 0.  I have created some badges to show the data, and set the colors to red on 0 and green on 1.
However the badges will also show the values.
Is there a better way to show binary data with badges, resulting in true/false, red/green, or on/off type badges?

Thank you.

**Comment by ktsaou** [comment]
Late reply. Sorry.

Yes there is. Set the `units` to any of the following and netdata will show the relative text: https://github.com/firehol/netdata/blob/f70a47874235e996961b9f0beac8cd6fed48309f/src/web_buffer_svg.c#L553-L586

I am closing this, but you can still post.

**Comment by ktsaou** [comment]
oh, and I forgot: most probably you need to change `/` to `\`, because the URL parser splits keywords at `/`. So, try `&units=on%5Coff`.

**Comment by sereeds** [comment]
Thank you.  That would be the solution I'm looking for, except I can't get it to work.

I have the latest from GIT: netdata 1.10.0-323-gf47b067_rolling

It always shows "up/down" as the units, regardless of the value.
I tried all ways to use the slash in the url, and tried all the escape codes too.

Maybe using the pipe character is easier?
`&units=up|down`

**Comment by sereeds** [comment]
I made some progress on this issue.  

I downloaded source, went into the file: web_buffer_svg.c
I replaced the 2 pieces of code, "up/down" to "updown".
So I removed the 

Ran the netdata-installer.sh to rebuild and install, now the badges with binary data work.  As I suspected, the slash was the problem.

Now when I test this URL, it works as should, and only shows "down" for units, as the value is zero:
http://x.x.x.x:19999/api/v1/badge.svg?chart=system.ipc_semaphores&label=test&dimensions=semaphores&units=updown

So without the slash in the units name, it parses the units correctly, using EITHER "up" or "down".

I also found another issue with the slashes (%5C) in the URL.  If you are using Apache as a reverse proxy to a Netdata server, Apache will not allow encoded URL's be default.  You need to add the Apache directive "AllowEncodedSlashes NoDecode" to your Apache config.

So perhaps it is best practice to avoid using the slashes in the URL this way.  In my example above, removing them from your code solved all problems and is working as designed.

Thank you for adding that in that feature.

**Comment by ktsaou** [comment]
Yes, the problem with slashes is nasty.
I added support for `-` too (so `up-down`) with PR #3954.

**Comment by ktsaou** [comment]
merged the PR.
