### ISSUE TITLE
dovecot not graphing but check passes

### ISSUE THREAD

**Issue by VVelox** [firehol/netdata#3617]
I see this in error.log and am not seeing anything else about it failing. Unfortunately it never shows up 

    2018-04-09 22:29:45: python.d INFO: dovecot: localsocket: check() => [OK]

Running the command below shows socket is usable by the user netdata.

    su -m netdata -c 'doveadm stats top'

The config for it is as below.

    localsocket:
        name     : 'local'
        socket   : '/var/run/dovecot/stats'

The version in question is 1.10.0 on FreeBSD.

**Comment by VVelox** [comment]
Hmm... seeing the same thing with fail2ban as well. The check is passing, but the graphs for it never show up.

**Comment by l2isbad** [comment]
hello @VVelox 
`python.d.plugin` [has debug mode](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by VVelox** [comment]
@l2isbad 

Found the problem...

    PLUGIN_CONFIG_DIR = os.getenv('NETDATA_CONFIG_DIR', os.path.dirname(__file__) + '/../../../../etc/netdata') + '/'

should be...

    PLUGIN_CONFIG_DIR = os.getenv('NETDATA_CONFIG_DIR', os.path.dirname(__file__) + '/../../../etc/netdata') + '/'

In '/usr/local/libexec/netdata/plugins.d/python.d.plugin' was resulting in an error about it not finding the dovecot config file.

**Comment by ktsaou** [comment]
This should only happen if you install netdata in non-standard directories and you run the plugin by hand. netdata tells its plugins where the configs are, so this should not be a problem for netdata.

I am closing this, but you can still post.
