### ISSUE TITLE
mdadm mismatch_cnt statistic/alarm

### ISSUE THREAD

**Issue by zafai** [firehol/netdata#3622]
Hello together,

I really like the wait netdata is showing the mdadm status.
What is missing in my opinion is a alarm on the mdX devices when the check finds a mismatch for that we could parse /sys/block/mdX/md/mismatch_cnt and display it as a chart and also alarm the admin when the value is going up.

**Comment by l2isbad** [comment]
yo @zafai 
I google a bit and found
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=405919

```
I have noticed that /sys/block/md1/md/mismatch_cnt reports a count of 
128 unsynchronized blocks. checkarray does not report or fix this issue.
Doing the same manually (echo check >/sys/block/md1/md/sync_action) does
not fix the issue either - mismatch_cnt is reset to 0 at the start of 
the resync, and goes up to 128 somewhere between 40% and 50% of the 
resync.
```

So `mismatch_cnt` is a unsynchronized blocks or what?

Is this a thing? :smile: If yes, i think we should add it. 

> and also alarm the admin when the value is going up.

Should we warn the user if value > 0 ?

**Comment by csamsel** [comment]
> So mismatch_cnt is a unsynchronized blocks or what?

Somewhat. If you run a scrub on the array to verify its consistency - mismatch_cnt goes up for every error. A number > 0 is definitely worth a warning. 

Just a few things to keep in mind - it is only updated during a check or resync action which is usually triggered manually or by cron. Most distributions will have measures in place to warn the user after the cronjob, e.g. mail. So it's likely the warning is redundant.

**Comment by zafai** [comment]
I think a warn bigger 0 is a good idea.

On my systems there was only a cronjob for the check, but not for notification, so a reminder for the admin is a nice way that he can check and solve it.

**Comment by l2isbad** [comment]
So, do we need chart and alarm or only alarm value > 0 ?

**Comment by zafai** [comment]
In my opinion, an alarm > 0 is enough.

**Comment by ktsaou** [comment]
Is this issue done? Do we need to add/change an alarm, a chart or what?

**Comment by l2isbad** [comment]
I think we need to add variable to existing chart and alarrm on it

**Comment by ktsaou** [comment]
merged it
