### ISSUE TITLE
Add Elasticsearch collector

### ISSUE THREAD

**Issue by panda87** [firehol/netdata#363]
This will be very useful to look at realtime elasticsearch data through netdata

**Comment by ktsaou** [comment]
Can you describe this a little more?

- you want to monitor the performance of elasticsearch with netdata, or
- you want to use elasticsearch as a backend for netdata

**Comment by ktsaou** [comment]
I guess you mean something like this: https://github.com/signalfx/collectd-elasticsearch/blob/master/elasticsearch_collectd.py

**Comment by renapu** [comment]
Hi, i think he is searching for something like this tool here: https://www.oreilly.com/ideas/10-elasticsearch-metrics-to-watch

I also would like to use netdata to get more insight to my ES-Cluster

**Comment by ktsaou** [comment]
Thanks!

Yes, I understood it. Too many feature requests through... If you can help writing a data collector for it, in any language, I would be glad to assist...

**Comment by paulfantom** [comment]
I started writing this. Currently I have done data collection and parsing as well as presenting shards information. I am stuck with a way to present nodes information (there is a lot of data).
I need to know which road to take:

1. add information from all nodes and present as 'cluster'
2. present separate charts for each node

Also if the second way is better, should I:
- group same type charts (ex. JVM info) together. It would look like this:
```
shards chart
node-1.jvm
node-2.jvm
node-3.jvm
node-1.os
node-2.os
node-3.os
```
- group nodes together
```
shards chart
node-1.jvm
node-1.os
node-2.jvm
node-2.os
node-3.jvm
node-3.os
```

**Comment by gruselglatz** [comment]
@paulfantom Wow, thank you for your efforts, i am looking forward to help you testing this out.

I think the group same type of charts would look better, or is better understandable.

**Comment by FarhadF** [comment]
@paulfantom Looking great, any news on this?

**Comment by ktsaou** [comment]
cc: @l2isbad please check this one too.

@paulfantom is probably busy (I hope he is fine).

**Comment by l2isbad** [comment]
Well, i need help then @FarhadF @gruselglatz 
What do we need to collect?
According [datadog](https://www.datadoghq.com/blog/collect-elasticsearch-metrics/)
> There are five main HTTP APIs that you can use to monitor Elasticsearch

First API is node stats:

- os: Information about the operating system’s resource usage, including CPU utilization and memory usage.

- process: Like the os section, this section offers metrics about resource usage, but limited to what the Elasticsearch JVM process is using. This section also provides the number of open file descriptors being used by Elasticsearch.

- jvm: This is where you will find all of the JVM metrics, including JVM heap currently in use, amount of JVM heap committed, and the total count and time spent on young- and old-generation garbage collections. Note that garbage collection count is cumulative, so the longer a node has been running, the higher this number will be.

- thread_pool: Provides the number of active, queued, and rejected threads for each thread pool; the main ones to focus on are index, bulk, merge, and search.

- fs: File system information (available disk space and disk I/O stats).

- transport: Stats about cluster communication (bytes sent and received).
- http: Number of HTTP connections currently open and total number of HTTP connections opened over time.

- breakers (only applicable for version 1.4 or later): Information about the circuit breakers. The most important section here is “fielddata”, which tells you the maximum size a query can be before tripping this circuit breaker. It also tells you how many times the circuit breaker has been tripped. The higher this number is, the more you may want to look into optimizing your queries or upgrading your memory.

**What charts do we need?**

**Comment by l2isbad** [comment]
@FarhadF @gruselglatz 
Actually you can see all the information node stats API proved yourself

```
# python3  (just run python interpreter from shell)
>>> from requests import get
>>> import json
>>> reply = json.loads(get('http://localhost:9200/_nodes/stats').text)
>>> reply
```
number of nodes
```
>>> len(reply['nodes'])
1
```
all stuff for the first node ([0], second will be [1])
```
>>> reply['nodes'][[n for n in reply['nodes'].keys()][0]].keys()
dict_keys(['fs', 'transport', 'os', 'indices', 'name', 'host', 'process', 'jvm', 'breakers', 'timestamp', 'thread_pool', 'http', 'transport_address', 'ip', 'script'])
```

jvm memory
`>>> reply['nodes'][[n for n in reply['nodes'].keys()][0]]['jvm']['mem']`

jvm gc
`>>> reply['nodes'][[n for n in reply['nodes'].keys()][0]]['jvm']['gc']`

and so on

I mean this is **the most difficult and important part** - what to collect, how to group it etc.

**Comment by FarhadF** [comment]
I'm trying to list endpoints, and the information that I consider valuable in charts. I did a research of monitoring services like new relic to see what they collect too.

**Nodes API:**

curl "http://NodeIP:9200/_cat/nodes?v"
Output:
```
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
node1 ip           23          97   0    0.00    0.04     0.07 mdi       -      node 1
node 2 ip          21          97   0    0.00    0.01     0.05 mdi       -      node 2
node n ip           27          97   0    0.00    0.05     0.08 mdi       *      node n
```
first of all I think we need local node's information only, Because we will usually install netdata on all the nodes. we can find our node from node ip in  nodes api case.
Metrics to collect: 

- heap percent
- ram percent
- cpu load 1min
- is master -> 0 or 1 -> master is identified by *

**Cluster API:**
Metrics specified in this api endpoint are cluster wide, and usually aggregate of all nodes.
curl http://nodeip:9200/_cluster/stats?pretty

- indices count
- shards total
- docs count
- docs deleted
- store size in bytes
- throttle time in millis
- all query cache metrics
-----------------------------------
- nodes count total 
- nodes count data
- nodes count coordinating only
- nodes count master
- nodes count ingest
I think this part should be in a single chart.
--------------------------------------
- openfiles descriptors min/max/average

curl http://nodeip:9200/_cluster/health?pretty

- relocating_shards
- initializing_shards
- unassigned_shards
- delayed_unassigned_shards
- number_of_pending_tasks
- number_of_in_flight_fetch
- task_max_waiting_in_queue_millis
- active_shards_percent_as_number


**_stats API:**
This part is a bit harder, Some stats should be compared to the last value to get the exact time for example.
curl "http://172.30.4.149:9200/_stats" 

```
"indexing": {
        "index_time_in_millis": 30321, -> should be compared to last value
        "index_current": 0,
        "index_failed": 0,
        "delete_time_in_millis": 4236, -> should be compared to last value
        "noop_update_total": 0,
        "throttle_time_in_millis": 0 -> should be compared to last value
}

"search": {
        "query_total": 220354, 
        "query_time_in_millis": 15713, -> should be compared to last value
        "query_current": 0,
        "fetch_total": 2081,
        "fetch_time_in_millis": 374, -> should be compared to last value
        "fetch_current": 0,
        "scroll_total": 0,
        "scroll_time_in_millis": 0, -> should be compared to last value
        "scroll_current": 0,
        "suggest_total": 0,
        "suggest_time_in_millis": 0, -> should be compared to last value
        "suggest_current": 0
}

"merges": {
        "current": 0,
        "current_docs": 0,
        "current_size_in_bytes": 0,
        "total": 1558,
        "total_time_in_millis": 159846,  -> should be compared to last value
        "total_docs": 6169462,
        "total_size_in_bytes": 2505169867,
        "total_stopped_time_in_millis": 0,  -> should be compared to last value
        "total_throttled_time_in_millis": 0,  -> should be compared to last value
      },
      "refresh": {
        "total": 14611, 
        "total_time_in_millis": 115168  -> should be compared to last value
      },
      "flush": {
        "total": 31,
        "total_time_in_millis": 1205  -> should be compared to last value
      },
      "warmer": {
        "current": 0,
        "total": 14675,
        "total_time_in_millis": 3792  -> should be compared to last value
      }
```

**Comment by l2isbad** [comment]
Looks like we need more then one elasticsearch plugin

1. **elasticsearch_node** (local node only)
url: http://localhost:9200/_nodes/_local/stats
 * jvm 
 * breaker
 * thread_pool 
 * ?
 

2. **elasticsearch_cluster**
url: http://localhost:9200/_cluster/stats
url: http://localhost:9200/_cluster/health

- Literally all. Why not (the default set of charts could be indices/shards/docs/querycache/nodes whatever). All others could be enabled in config file.

3....

What about **_stats API:**? 

It is Index Stats API. A lot of stats for every index. How is this supposed to work?

**Comment by l2isbad** [comment]
Are you ok with that @FarhadF

**Comment by FarhadF** [comment]
@l2isbad Great job man! 

> What about _stats API:?
> url: http://localhost:9200/<INDEX_NAME>/_stats/indexing,search,merges,refresh,flush,warmer (??)
> 
> It is Index Stats API. A lot of stats for every index. How is this supposed to work?
> List of indices to monitor in conf?

This is per index stats, and some deployments have hug number of indices, I suggest we do not enable this by default in case you want to add it to features.

**Comment by l2isbad** [comment]
Yeah. That is why i suggest to implement real-time index performance feature as a standalone plugin

**Comment by l2isbad** [comment]
Ok, i created initial version
https://github.com/firehol/netdata/pull/1581
Lets start from it and make it better

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
I think we can close this now. I something is missing please post.

**Comment by sLuvpreet33** [comment]
how do we add user auth parameters USERNAME and PASSWORD in python.d/elasticsearch.conf file ?

    local:
      name: 'elastic'  # also, is this what appear as name in the sidebar OR the above mentioned 'local' ?
      host:'127.0.0.1'
      port:'9200'
      username:'elastic'
      password:'changeme'
      cluster_health: True
      cluster_stats: True

This does not seem to work for me.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L504-L508

```yaml
user: 'user'
pass: 'password'
```

**Comment by sLuvpreet33** [comment]
I recommend to mention this is in the file in the commented section.

Thanks.

**Comment by ktsaou** [comment]
@l2isbad I also see that the conf file says it uses python requests.
Is this still valid?

**Comment by l2isbad** [comment]
@sLuvpreet33 
You are right

@ktsaou 
[No](https://github.com/firehol/netdata/pull/1940)

i have to update the conf file, got it 😄

**Comment by ktsaou** [comment]
and I think I also have to update the packages installer https://github.com/firehol/netdata-demo-site/blob/2b7d1a61e15ffa2354139d88f054d7b5ca0b6d8d/install-required-packages.sh#L1046

**Comment by sLuvpreet33** [comment]
Hey, elasticsearch is not getting configured in netdata. 

I have 2 systems, both using 16.04 ubuntu, one is my local machine and other is the server.

On my local machine, I have not used any basic auth on elasticsearch. It was pretty simple,

    local:
      server: '127.0.0.1'
      port: '9200'

It worked on my local machine. But on my server I have used basic auth, and this is what I have done, 

    local:
      server: '127.0.0.1'
      port: '9200'
      user: 'netdata'
      pass: 'netdata'

I have not made any change in /etc/netdata/python.d.conf and in netdata.conf. I am using the latest commit version. What can be the possible reasons for this ?

**Comment by l2isbad** [comment]
[debug](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by sLuvpreet33** [comment]
2017-06-16 13:42:05:  INFO: Using python v2
    2017-06-16 13:42:05:  INFO: YAML output is ordered
    2017-06-16 13:42:05: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
    2017-06-16 13:42:05: python.d ERROR: /etc/netdata/python.d.conf reading error: [Errno 13] Permission denied: '/etc/netdata/python.d.conf'
    2017-06-16 13:42:05: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['elasticsearch']
    2017-06-16 13:42:05: python.d ERROR: elasticsearch: configuration file '/etc/netdata/python.d/elasticsearch.conf' not found. Using defaults.
    2017-06-16 13:42:05: python.d DEBUG: elasticsearch: setting configuration for only one job
    2017-06-16 13:42:05: python.d DEBUG: elasticsearch: job added
    2017-06-16 13:42:05: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
    2017-06-16 13:42:05: python.d ERROR: elasticsearch Host is not defined in the module configuration file
    2017-06-16 13:42:05: python.d ERROR: elasticsearch check() failed - disabling job 
    2017-06-16 13:42:05: python.d ERROR: DISABLED: elasticsearch/None
    2017-06-16 13:42:05: python.d DEBUG: overridden job names: []
    2017-06-16 13:42:05: python.d DEBUG: all remaining job objects: []
    2017-06-16 13:42:05: python.d FATAL: no more jobs
    DISABLE

I changed permissions but still got the same errors.
The tricky thing is that it is showing this same output on both my machines. While on my local machine it is working just fine.

**Comment by l2isbad** [comment]
Did you run the debug as `netdata` user?

> I changed permissions but still got the same errors

all files in /etc/netdata must be `netdata:netdata`

**Comment by sLuvpreet33** [comment]
The files are ok `netdata:netdata`

> Did you run the debug as netdata user?

I just simply run it, as I have done a lot of times earlier, 

    monitoring-server@monitoring-server:~$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug elasticsearch

**Comment by l2isbad** [comment]
```bash
# become user netdata
sudo su -s /bin/bash netdata  # <- !this!

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mysql
```
