### ISSUE TITLE
Issue with statsd sample rate

### ISSUE THREAD

**Issue by julsemaan** [firehol/netdata#3630]
Hi,

I'm a pretty new user to netdata, we're integrating this in our solution and we do use a lot of statsd metrics that we initially put in place with the original nodejs version of statsd.

Now, we've noticed that there is an issue with the sample rate and timing metrics when using netdata.

Lets say I send the following metric:
```
localhost_localdomain.pf__api__radius_rest_authorize.timing:57|ms|@0.1
```

Then the charts show a value of 0.55 seconds (10 times as much)

If I send the following metric:
```
localhost_localdomain.pf__locationlog__locationlog_synchronize.timing:3|ms|@0.2
```

Then the charts show a value of 15 milliseconds (5 times as much)

So it seems like the timings are impacted by the sample rate which shouldn't happen since even though I'm sampling one of 5 executions, it doesn't mean they take 5 times as much time to execute.

Thanks!

**Comment by julsemaan** [comment]
Any feedback on this issue ?

**Comment by ktsaou** [comment]
Hi,

yes, this seems a bug. Let me fix it.

**Comment by ktsaou** [comment]
hm... how should the sampling rate be interpreted for timers/histograms?

I mean, what if we have, within the same interpolation:

```
10|ms|@0.5
20|ms|@0.1
```

Is it:

- 15 (i.e. (`10 + 20 / 2` sampling rate ignored) )
- 18.33 (i.e. `(10 / 0.5 + 20 / 0.1) / (1 / 0.5 + 1 / 0.1)` )
- 13.57 (i.e. `(10 / (1 - 0.5) + 20 / (1 - 0.1)) / (1 / (1 - 0.5) + 1 / (1 - 0.1))`)

Do you know what your previous statsd did?

**Comment by ktsaou** [comment]
I understand it is the third option.

In this example:

```
10|ms|@0.5
20|ms|@1.0
```

The right result should be 13.33, meaning that 10 has 2 samples and 20 has only one.

**Comment by julsemaan** [comment]
I don't know exactly how the "real" statsd deals with that, my gut feeling would tell me to record 10ms twice in the DB (so like if we received 2 events of 10ms) and record 20ms 10 times.

Then we'd get 18.33

**Comment by ktsaou** [comment]
hm... you are right.
Let's go with the second option.

**Comment by julsemaan** [comment]
My logic would be:
```
((10×2)+(20×10))÷(2+10)
```

**Comment by ktsaou** [comment]
yes, I agree - second option does exactly that.

**Comment by ktsaou** [comment]
merged it!
Thank you for reporting it - and sorry for the delay...

**Comment by julsemaan** [comment]
Thanks a lot for the quick fix today @ktsaou
