### ISSUE TITLE
Netdata doesn't show http2 number of requests.

### ISSUE THREAD

**Issue by catalindevops** [firehol/netdata#3637]
After apache upgrade and enable http2 on site number of requests showed by netdata  was reduced drastically from 250 rps to 30-40 rps. After checking those were in fact http 1.0 and 1.1 requests.
Can netdata count http2 requests ? I saw that netdata interrogates mod_status from apache, but in their documentation is specified that http2 has his owns workers which are not monitored by mod_status.

Any help ?

**Comment by catalindevops** [comment]
@ktsaou can you help me with an answer ? Thank you :).

**Comment by l2isbad** [comment]
>  but in their documentation is specified that http2 has his owns workers which are not monitored by mod_status

link ?

**Comment by catalindevops** [comment]
From documentation "The first noticeable thing after enabling HTTP/2 is that your server processes will start additional threads. The reason for this is that HTTP/2 gives all requests that it receives to its own Worker threads for processing, collects the results and streams them out to the client.

In the current implementation, these workers use a separate thread pool from the MPM workers that you might be familiar with. This is just how things are right now and not intended to be like this forever. (It might be forever for the 2.4.x release line, though.) So, HTTP/2 workers, or shorter H2Workers, will not show up in mod_status. They are also not counted against directives such as ThreadsPerChild."

Link: https://httpd.apache.org/docs/2.4/mod/mod_http2.html @l2isbad  I hope it helps

**Comment by ktsaou** [comment]
hm... interesting... so apache does not expose any metrics about http/2.

I guess you can use the web_log module to get statistics of all the traffic. Have you tried it?

**Comment by catalindevops** [comment]
Thanks, i tried with web_log module and i can see number of requests.

**Comment by ktsaou** [comment]
Cleaning up....
