### ISSUE TITLE
httpcheck python.d plugin fails

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#3641]
Trying to use the httpcheck plugin with the following content (`python.d/httpcheck.conf`):

```
google:
    url: 'https://www.google.com'
```

I get the following error:

```
2018-04-20 15:08:10: python.d ERROR: httpcheck: google: _get_data() failed. Url: https://www.google.com. Error: 'module' object has no attribute 'NewConnectionError'
2018-04-20 15:08:10: python.d INFO: httpcheck: google: check() => [FAILED]
```

Are there any way to solve this?

**Comment by ktsaou** [comment]
hm... it works for me.
Are you using python2 or python3?

@ccremer could you please check this?

I used this config:

```yaml
mynetdata:
    url: 'http://london3.my-netdata.io/'
    timeout: 10
    redirect: no
    status_accepted:
        - 200
        - 301
    regex: '.*netdata.*'

smynetdata:
    url: 'https://london3.my-netdata.io/'
    timeout: 10
    redirect: no
    status_accepted:
        - 200
        - 301
    regex: '.*netdata.*'

google:
    url: 'https://www.google.com'
```

under python2:

```sh
# python2 /usr/libexec/netdata/plugins.d/python.d.plugin 1 httpcheck 
2018-04-20 16:24:21: python.d INFO: plugin: main: Using python 2
2018-04-20 16:24:22: python.d INFO: httpcheck: mynetdata: check() => [OK]
2018-04-20 16:24:22: python.d INFO: httpcheck: smynetdata: check() => [OK]
2018-04-20 16:24:23: python.d INFO: httpcheck: google: check() => [OK]
```

under python3:

```sh
# python3 /usr/libexec/netdata/plugins.d/python.d.plugin 1 httpcheck 
2018-04-20 16:24:49: python.d INFO: plugin: main: Using python 3
2018-04-20 16:24:49: python.d ERROR: httpcheck: mynetdata: Url: http://london3.my-netdata.io/. Error: cannot use a string pattern on a bytes-like object
2018-04-20 16:24:49: python.d ERROR: httpcheck: mynetdata: _get_data() returned no data or type is not <dict>
2018-04-20 16:24:49: python.d INFO: httpcheck: mynetdata: check() => [FAILED]
2018-04-20 16:24:50: python.d ERROR: httpcheck: smynetdata: Url: https://london3.my-netdata.io/. Error: cannot use a string pattern on a bytes-like object
2018-04-20 16:24:50: python.d ERROR: httpcheck: smynetdata: _get_data() returned no data or type is not <dict>
2018-04-20 16:24:50: python.d INFO: httpcheck: smynetdata: check() => [FAILED]
2018-04-20 16:24:50: python.d INFO: httpcheck: google: check() => [OK]
```

So, google worked on both cases. However, it seems that somehow there is an issue with python3.

@l2isbad

**Comment by l2isbad** [comment]
@dseira  please show output from

```python
[~]python
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> for i, v in enumerate(dir(urllib3.exceptions)):
...     print(i, v)
... 

```

**Comment by l2isbad** [comment]
> However, it seems that somehow there is an issue with python3.

yes, it's a bug

**Comment by dseira** [comment]
But there is still something wrong with `http` because I get the following error for the `marca` check:
```
2018-04-20 17:43:56: python.d ERROR: httpcheck: marca: update() unhandled exception: 'module' object has no attribute 'NewConnectionError'
2018-04-20 17:43:59: python.d ERROR: httpcheck: marca: update() unhandled exception: 'module' object has no attribute 'NewConnectionError'
```
And the graph shows the cut:
![seleccion_067](https://user-images.githubusercontent.com/378158/39060887-e06682a4-44c2-11e8-85e2-f9a4aace9945.jpg)

**Comment by dseira** [comment]
Sorry guys, after upgrade to the latest netdata `v1.10.0-43-gefbc533f_rolling` all the 4 httpcheck work as expected.

**Comment by l2isbad** [comment]
@ktsaou found a bug

> 2018-04-20 16:24:50: python.d ERROR: httpcheck: smynetdata: Url: https://london3.my-netdata.io/. Error: cannot use a string pattern on a bytes-like object

@dseira please reopen

**Comment by Avik1993** [comment]
I am facing similar issue. My config looks like this:
`cool_website:
   url: 'http://localhost:2324/service/tick'
   status_accepted:
     - 200
     - 204
   timeout: 2
`

I get error 

> 2019-05-27 17:41:39: python.d ERROR: httpcheck[cool_website] : _get_data() failed. Url: http://localhost:2324/service/tick. Error: 'module' object has no attribute 'NewConnectionError'

**Comment by ilyam8** [comment]
@Avik1993 netdata version?

**Comment by Avik1993** [comment]
Hi @ilyam8 
netdata v1.14.0-29-g9f151a8

**Comment by ilyam8** [comment]
You need to update `urllib3` package, `NewConnectionError` was added in [1.12 (2015-09-03)](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#112-2015-09-03)

**Comment by Avik1993** [comment]
I am at version 1.7.1 for urllib3 in python 3. which version do i need to update it to?

**Comment by ilyam8** [comment]
I suggest to the latest you can get in case nothing depends on `1.7.1`

**Comment by Avik1993** [comment]
the package was installed as a dist-package. So I wont be able to remove it just using 

> pip install --upgrade

Any other way to perform this?

**Comment by Avik1993** [comment]
ok i seem to have made progress here. 
I did upgrade `urllib3` to latest version. And the check also passed but I am not able to see any charts in Netdata UI.
Logs from Error.log file
`2019-05-27 19:23:35: python.d INFO: plugin[main] : httpcheck[cool_website] : init successful
2019-05-27 19:23:35: python.d INFO: plugin[main] : httpcheck[cool_website] : check successful
2019-05-27 19:23:35: netdata INFO  : PLUGINSD[python.d] : Initializing file /opt/netdata/var/cache/netdata/netdata.runtime_httpcheck_cool_website/main.db.
2019-05-27 19:23:35: netdata INFO  : PLUGINSD[python.d] : Initializing file /opt/netdata/var/cache/netdata/netdata.runtime_httpcheck_cool_website/run_time.db.
2019-05-27 19:23:35: python.d INFO: plugin[main] : httpcheck[cool_website] : started in thread
ubuntu@ip-172-31-32-126:/opt/netdata/var/log/netdata$ 
`

**Comment by Avik1993** [comment]
Hi
One more question @ilyam8 .
What if I want to run a different custom script for different endpoints monitored through httpcheck.
Say  I have one endpoint `http://a/b`, for which I want script `Alarm1.sh` to execute and for endpoint `http://c/d` i want `Alarm2.sh` to be triggered.
I know each alarm has a parameter exec, which can be used to run a custom script. But what I want to run a different custom script for different endpoints?

**Comment by ilyam8** [comment]
You need to write all those alarm yourself then :smile: 	

Or

Write a wrapper wich executes certain script based on input params

default exec is [`alarm-notify.sh`](https://github.com/netdata/netdata/blob/master/health/notifications/alarm-notify.sh.in), i see input params are

https://github.com/netdata/netdata/blob/e11a4e4a5dc5231ffb2f58ff05f32156c052766a/health/notifications/alarm-notify.sh.in#L203-L228

[](url)

**Comment by Avik1993** [comment]
so you mean i can write a wrapper script with which will accept the same number of arguments as alarm-notify.sh does. Filter based on input parameters `name`, `chart`, `family`.
Thats a nice idea!

**Comment by cakrit** [comment]
> so you mean i can write a wrapper script with which will accept the same number of arguments as alarm-notify.sh does. Filter based on input parameters `name`, `chart`, `family`.
> Thats a nice idea!

It will be much easier for you, if you just put your code in a [custom notification sender](https://docs.netdata.cloud/health/notifications/custom/).

**Comment by Avik1993** [comment]
Sure. Thanks @cakrit  Will try it out!

**Comment by Avik1993** [comment]
@cakrit apart from adding logic to `custom_sender()` function, does anything needs to be configured?
I did add my logic (Filtering based on `$chart`, `$family`) and did log some messages using `info` as well but didnt see any of those messages in any log file for netdata.
Where exactly does those logs are written?

**Comment by ilyam8** [comment]
@Avik1993 i think it will be easier to help you if you share the code

**Comment by Avik1993** [comment]
@ilyam8 Thanks for responding.
Here is sample code:

```
custom_sender() {

	info "Parameters coming from netdata are: CHART = $chart, FAMILY = $family, SEVERITY = $severity and ALARM = $alarm"

	if [[ $chart -eq "httpcheck_<CHECK1>.status" && $family -eq "status" ]]; then
		sudo service <SERVICE_1> start
	elif [[ $chart -eq "httpcheck_<CHECK2>.status" && $family -eq "status" ]]; then
		sudo service <SERVIVE_2> start
	elif [[ $chart -eq "httpcheck_<CHECK3>.status" && $family -eq "status" ]]; then
		sudo service <SERVICE_3> start
	fi
}

```

**Comment by ilyam8** [comment]
just a quick comment about `sudo` there. Have you added netdata to the `sudo` group?
And you need `-n` flag for sudo.

>      -n, --non-interactive
>        Avoid prompting the user for input of any kind.  If a pass‐
>        word is required for the command to run, sudo will display an
>        error message and exit.

**Comment by Avik1993** [comment]
Yes, @ilyam8 I have netdata as a sudoer user.
Also, I didn't note about `-n` flag. That would surely be helpful.

And I figured out the issue. Actually the custom_sender() function in file `/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf` needs to be modified but in documentation its mentioned to modify code in `/opt/netdata//usr/libexec/netdata/plugins.d/alarm-notify.sh`.
Could this be updated in the documentation for future users?

**Comment by ilyam8** [comment]
So you are saying you get it working?

**Comment by Avik1993** [comment]
Yes. After making the changes to `/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf`, i got it working. Haven't tested the sudo functionality yet. But custom functionality is kicking in!

**Comment by ilyam8** [comment]
> /opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf

this one will be rewritten after next upgrage

You need to copy stock config to the /etc/netdata and modify it there
https://github.com/netdata/netdata/tree/master/health/notifications#configuration

> needs to be modified but in documentation its mentioned to modify code in /opt/netdata//usr/libexec/netdata/plugins.d/alarm-notify.sh.

Where?

https://github.com/netdata/netdata/tree/master/health/notifications/custom

> You can look at the other senders in /usr/libexec/netdata/plugins.d/alarm-notify.sh for examples.

it is suggested to look in, not modify, anyway the path is wrong, you are right.
