### ISSUE TITLE
FYI: Homebrew formula (package) of netdata for macOS 

### ISSUE THREAD

**Issue by rickard-von-essen** [firehol/netdata#3642]
I have created a [homebrew](https://brew.sh/) formula (package) of _netdata_ for macOS.

I'll try to track updates and update the formula, but if you are a homebrew user it's very easy to create a PR for a update user, just:

```sh
brew bump-formula-pr netdata
``` 

See [How To Open a Homebrew Pull Request (and get it merged)](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request).

I also updated the [install instructions](https://github.com/firehol/netdata/wiki/Installation#macos) to reflect this.

**Comment by rickard-von-essen** [comment]
Feel free to close this if there is no more instructions to update etc.

**Comment by simonnagl** [comment]
I think this should be added at #651

**Comment by l2isbad** [comment]
> I also updated the install instructions to reflect this.

https://github.com/firehol/netdata/wiki/Installation/_compare/b145fd0%5E...b145fd0

**Comment by rickard-von-essen** [comment]
@l2isbad Any particular reason for the revert of the Wiki?

**Comment by l2isbad** [comment]
@rickard-von-essen well, let's ask @Popsoywhip 

I don't know, wiki is open for edit to everyone

**Comment by rickard-von-essen** [comment]
That seems to be his/her only change to netdata and the user is only 13 days old on GitHub. Maybe it was just a misstake.

**Comment by rickard-von-essen** [comment]
I just reverted his revert... and added a comment to #651.
