### ISSUE TITLE
Problems with importing "correct" version of urllib3

### ISSUE THREAD

**Issue by aigr** [firehol/netdata#3647]
While writing a python plugin for NetData I noticed that **sys.path** includes the **python.d** directory early, but includes **python_modules** late.

This means that if you try to **import urllib3** you'll get the systems-wide installed version of urllib3 before you get the one shipped with NetData.

When the two different versions of urllib3 are sufficiently different from each other, it gets unnecessarily hard to write a plugin that works across installations.

Would it be possible to get the **python_modules** version included earlier in **sys.path**?

**Comment by l2isbad** [comment]
Hi @aigr 

`netdata.conf `has `PYTHONPATH`

```
[plugins]
        # PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
        PYTHONPATH environment variable = /opt/netdata/usr/libexec/netdata/python.d/python_modules/
```

**Comment by aigr** [comment]
Thanks! I'll try that out.
