### ISSUE TITLE
Netdata long term data with graphite tutorial

### ISSUE THREAD

**Issue by JsBergbau** [firehol/netdata#3655]
Here https://github.com/firehol/netdata/wiki/netdata-backends is written how to configure netdata to send its data to graphite and you can monitor it with grafana. However there is no tutorial / explanation how to get graphite and grafana working. Where do I find a tutorial for netdata with graphite and grafana?

Thanks for helping.

**Comment by Ferroin** [comment]
General setup of Graphite and Grafana should be no different than what they explain upstream.

**Comment by JsBergbau** [comment]
What do you mean by explain upstream?

**Comment by l2isbad** [comment]
`graphite/grafana` official documentation

**Comment by l2isbad** [comment]
Never used grafana. I may be wrong but
http://docs.grafana.org/guides/getting_started/
http://docs.grafana.org/features/
is a good place to start

I see https://github.com/firehol/netdata/issues/3376

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
