### ISSUE TITLE
python.d ERROR: xmit_packet: local: Command "['/usr/sbin/perfquery', '-x']" returned no data

### ISSUE THREAD

**Issue by noamargalitu** [firehol/netdata#3660]
![screen shot 2018-04-26 at 3 56 37 pm](https://user-images.githubusercontent.com/38051199/39334067-6fa5b934-496a-11e8-9a2e-765913a4a4b4.png)

Hi,
I am trying to debug this executable service plug in and keep receiving the above error. I have made netdata an owner of all my files (.py, .conf) as well as an owner of /usr/sbin/perfquery. if i run /usr/sbin/perfquery -x in sudo su -s /bin/bash netdata i do see an output. 
Let me know if you find a solution

**Comment by ZAM-** [comment]
After looking at the [line](https://www.google.com/url?q=https://github.com/firehol/netdata/blob/05168b8c6d01a70a9a7f811a012c3cfe127dd075/python.d/python_modules/bases/FrameworkServices/ExecutableService.py%23L87&sa=D&source=hangouts&ust=1524868443786000&usg=AFQjCNGtiHfjfToE3aVTZkCdQ4uK-LTZBA) in the ExecutableService class,  it seems like the "returned no data" line would be executed regardless if there is data or not.

**Comment by l2isbad** [comment]
It will executed only if data is not `not emtpy dict`

https://github.com/firehol/netdata/blob/05168b8c6d01a70a9a7f811a012c3cfe127dd075/python.d/python_modules/bases/FrameworkServices/ExecutableService.py#L85-L86
