### ISSUE TITLE
Can't exclude /media/ from disk space alerts

### ISSUE THREAD

**Issue by brianguy** [firehol/netdata#3662]
USB drives that get mounted get mounted to /media/ and show up as usbhd-sdx, e.g. /media/usbhd-sdd, however, I can't seem to get netdata to properly exclude the path.

I've tried to add it to netdata.conf:
```
[plugin:proc:diskpace]
exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/* /media/*
```

But I still get notified with
```
out of disk space time = 1h 
estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour
disk_space._media_usbhd-sdd (family /media/usbhd-sdd)
```

Is this expected to work as described? How would I go about disabling this? Thanks.

**Comment by ktsaou** [comment]
hm... just tested this and it works.

Please fetch `http://your.netdata.ip:19999/netdata.conf` and search for `/media/usbhd-sdd`.

You can get the info I look for with this:

```
curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[plugin:proc:diskspace\]/,/^$/p'
```

and this:

```
curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[plugin:proc:diskspace:\/media\/usbhd-sdd\]/,/^$/p'
```

**Comment by ktsaou** [comment]
btw, the way you disable it, netdata will also stop providing charts for these disks.
You can disable only alarms (but keep the charts), by editing `/etc/netdata/health.d/disks.conf` and setting (I changed only the `families` line):

```
template: out_of_disk_space_time
      on: disk.space
      os: linux freebsd
   hosts: *
families: !/media/usbhd-sdd *
    calc: ($disk_fill_rate > 0) ? ($avail / $disk_fill_rate) : (inf)
   units: hours
   every: 10s
    warn: $this > 0 and $this < (($status >= $WARNING)  ? (48) : (8))
    crit: $this > 0 and $this < (($status == $CRITICAL) ? (24) : (2))
   delay: down 15m multiplier 1.2 max 1h
    info: estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour
      to: sysadmin
```

This will keep all the alarms, but disable only out of disk time prediction.

**Comment by brianguy** [comment]
I see, that makes sense since it's just streaming up data. Didn't think about that. To confirm then, adding /media/* to 'exclude space metrics on paths' on all clients would do the trick?

Disabling the alarm at master should be sufficient for my immediate needs, so I'm giving that a shot. Thanks.
