### ISSUE TITLE
Option to re read a config file without restarting the netdata service

### ISSUE THREAD

**Issue by kumarankit1234** [firehol/netdata#3681]
I have written a node plugin to monitor redis keys which are dynamic.
The keys have a common prefix. So i want to do something like this.
i. Get all keys using the keys * redis command.
ii. For each of the above keys create a chart.

Repeat the above two process every 30 second. 

For the first point. ,i did the following
i. Wrote a simple node script that read the redis keys using the keys * command and created a new conf file.
ii. Compared the new conf file with the old file.
iii. If there was any change then replace the old file with the new one and then restart netdata.

The restart netdata every 30 seconds is a very expensive task. So is there a way for the netdata process to re read a particular conf file without having to restart netdata.

**Comment by ktsaou** [comment]
Hi,

I think you should do this in your node plugin. There is no need to restart netdata. Just make the plugin push the new charts to netdata.
