### ISSUE TITLE
Removing the popin while displaying in dedicated screens

### ISSUE THREAD

**Issue by pupeno** [firehol/netdata#3686]
Hello,

I'm the creator of [Dashman](https://dashman.tech), an application to manage dashboards and one of my clients is using it display a NetData dashboard. The problem they are having is the popin that appears saying ["Welcome to the world of netdata"](https://london.my-netdata.io/default.html#menu_system;theme=slate;help=true). How do you permanently dismiss it so when NetData is show on every screen on the office automatically, it shows the dashsboard and not the popin blocking the data

**Comment by ktsaou** [comment]
Hi,

this popup is shown only on the netdata demo sites. It does not appear on any other installation.

Even on the netdata demo sites you can disable it by appending `;nowelcome=1`, like this:

https://london.my-netdata.io/default.html#menu_system;theme=slate;help=true;nowelcome=1
