### ISSUE TITLE
In the Apache log many requests like "GET /server-status?auto HTTP/1.1"

### ISSUE THREAD

**Issue by vladns** [firehol/netdata#3687]
Hello! After installation netdata, in the Apache log many requests like "GET / server-status? Auto HTTP / 1.1" go every second. It is possible to make somehow so that the apache did not write them and a log-file? This makes it difficult to view useful logs.

**Comment by l2isbad** [comment]
You can disable `apache` pugin and use `web_log` instead.

**Comment by mpinkerman** [comment]
sudo a2dismod status -- Its the mod_status doing what its supposed to. If you go to /etc/mods-enabled and locate the status.conf file you can edit the line where it says "Require Host" and change the host to the name based virtual host file you'd like to monitor. Then visit http://server-name/server-status. You can even set the refresh rate of the page with certain browsers by crafting the request like this "http://server-name/server-status?refresh=[insert numerical value representing desired seconds here]

**Comment by ShagoY** [comment]
Hi,
How to disable the apache plugin properly?
I tried "apache: no" in go.d.conf and python.d.conf without success...

Thanks.

**Comment by ilyam8** [comment]
Hi @ShagoY 

`apache: no` in `python.d.conf` will do 100%, restart `netdata.service` then

> I tried "apache: no" in go.d.conf and python.d.conf without success...

Maybe you changed in stock `python.d.conf`, you need the one in `/etc/netdata`

**Comment by mpinkerman** [comment]
Depending on your slave setup it can get noisy. If you have the script enabled as a slave and a master it can cause this kind of traffic. Double check your config files to ensure you have the device set as one or the other
