### ISSUE TITLE
snmp 64bit interfaces on junos

### ISSUE THREAD

**Issue by afletch** [firehol/netdata#369]
When polling 64bit interface counters on JunOS using snmp.node.js, the values returned are always NaN. Debugging enabled shows the following:
```
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: making 4 entries request, max is: 50
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: got valid snmp response: [ { oid: '1.3.6.1.2.1.31.1.1.1.7.598',
    type: 70,
    value: <Buffer 00 a7 ab 81 d1 16> },
  { oid: '1.3.6.1.2.1.31.1.1.1.11.598',
    type: 70,
    value: <Buffer 00 d9 46 af 31 87> },
  { oid: '1.3.6.1.2.1.31.1.1.1.7.906',
    type: 70,
    value: <Buffer 00 81 a1 ac 44 f0> },
  { oid: '1.3.6.1.2.1.31.1.1.1.11.906',
    type: 70,
    value: <Buffer 00 da 30 dd 1b 18> } ]
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.7.598 = ����
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.11.598 = �F�1�
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.7.906 = ���D�
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: found snmp value of OIDs 1.3.6.1.2.1.31.1.1.1.11.906 = �0�
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: finished snmp with 4 successful and 0 failed values
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: snmp: n.n.n.n: processing snmp response (received in 13 ms)
Wed May 04 2016 16:09:00 GMT+0100 (BST): node.d.plugin: DEBUG: setting current chart to snmp_switch.bandwidth_port1
BEGIN snmp_switch.bandwidth_port1 486000
SET in = NaN
SET out = NaN
END
```

**Comment by ktsaou** [comment]
Are you using the latest version?
The first version of netdata did not handle 64 bit counters properly.

**Comment by afletch** [comment]
@ktsaou Yes, verified the changes in #75 are in the copy cloned from github today.
FWIW the value returned into `value64` at `node.d/node_modules/netdata.js:345` is `NaN`.

**Comment by ktsaou** [comment]
ok. Can you help me fix this?

Please add add this line:

```js
					this.error('64BIT VALUE: ' + value.toOctetString());
					var value64 = new Int64(value);
					this.queue('SET ' + dimension + ' = ' + value64.toString(10));
```

and give me the printout?

You can run the plugin by hand like this:

```sh
/usr/libexec/netdata/plugins/node.d.plugin 1 snmp
```

**Comment by ktsaou** [comment]
Edit the file in `/usr/libexec/netdata/node.d/node_modules/netdata.js`

**Comment by ktsaou** [comment]
My bad. You need to add this:

```
this.error('64BIT VALUE: ' + value.toString('hex'));
```

**Comment by afletch** [comment]
@ktsaou Sure, output from this line is:
`ERROR: snmp: 85.92.76.99: 64BIT VALUE: 00a7bcdcef51`

**Comment by ktsaou** [comment]
ok. node-int64 is not good:

```js
var Int64 = require('node-int64');
var bigInt = require('big-integer');

var value = new Buffer([0x00, 0xa7, 0xbc, 0xdc, 0xef, 0x51]);

var v1 = new Int64(value);
console.log('int64: ' + v1.toString(10));

var v2 = bigInt('0x' + value.toString('hex'));
console.log('big-integer: ' + v2.toString(10));
```

The output is:

```
int64: NaN
biginteger: 720428134225
```

I am replacing node-int64 with big-integer. I will submit a PR in a while.

**Comment by ktsaou** [comment]
Found a better way: netdata accepts values from plugins in hex too.

Could you please clone https://github.com/ktsaou/netdata and install it? If this works (it should), I will merge it so you can use the main repo again.

Thanks!

**Comment by afletch** [comment]
Yep, that seems to work much better. Thanks.

**Comment by ktsaou** [comment]
Thanks! Merged it to official repo.

**Comment by antonsb** [comment]
Still happening:
`
snmpwalk -t 20 -v 1 -O fn -c public 192.168.88.1 1.3.6.1.2.1.31.1.1.1.11.2
.1.3.6.1.2.1.31.1.1.1.11.2 = Counter64: 1606684
`


`/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
CHART "snmp_switch.bandwidth_port1" "snmp_switch.bandwidth_port1" "Switch Bandwidth for port 1" "kilobits/s" "ports" "" "area" 50001 10
DIMENSION "in" "in" "incremental" 1 1 
DIMENSION "out" "out" "incremental" -1 1 
BEGIN snmp_switch.bandwidth_port1 
SET in = ����0
SET out = J��0
END
`

**Comment by ktsaou** [comment]
@antonsb I think your issue is exactly the same with #2362 (check the debug log posted near the end of the discussion - the same kind of corruption exists there too).

Let's continue this discussion there.
