### ISSUE TITLE
No LVM disk space usage on Synology

### ISSUE THREAD

**Issue by Shini31** [firehol/netdata#3696]
Hello,

After installing netdata on my DS415+ synology following the wiki, the lvm disk space usage isn't monitoring.

![synology_disks](https://user-images.githubusercontent.com/333820/39765466-31d4fd1e-52e2-11e8-9b81-4519eaabd751.png)

Disk space usage is only present for partitions _"/dev"_ and _"synoboot"_ while the most relevant partition is the _"/dev/vg1/volume_1"_

```
df -h
Filesystem         Size  Used Avail Use% Mounted on
/dev/md0           2.3G  883M  1.3G  40% /
none               990M  4.0K  990M   1% /dev
/tmp               994M  1.2M  993M   1% /tmp
/run               994M  3.2M  991M   1% /run
/dev/shm           994M  4.0K  994M   1% /dev/shm
none               4.0K     0  4.0K   0% /sys/fs/cgroup
cgmfs              100K     0  100K   0% /run/cgmanager/fs
/dev/vg1/volume_1  8.2T  7.2T 1007G  88% /volume1
```

If you need more information, don't hesitate to tell me.

Regards.

**Comment by ktsaou** [comment]
It is probably a permissions issue. User `netdata` needs to have read access to it, otherwise it cannot read it.
Please post `ls -ld /volume1`.

**Comment by Shini31** [comment]
```
ls -ld /volume1
drwxr-xr-x 18 root root 4096 May  5 15:35 /volume1
```

The netdata user is in a chroot, so it cannot access /volume1. 
I just turned up /volume1 in the chroot and now I have well the disk space usage for this partition.

Thanks !
