### ISSUE TITLE
httpcheck user-agent

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#3704]
As a improvement, it would really useful to be able to setup an specific user-agent in the httpcheck plugin. This can be nice for several purposes.

**Comment by Ferroin** [comment]
Agreed, though it would be even better to allow specifying (almost) arbitrary headers.  That would also allow sending cookies, bypassing caching of intermediary proxies (and thus checking backend servers directly), specifying a referrer, specifying auth credentials, and probably a bunch of other things I can't think of.

**Comment by ktsaou** [comment]
@ccremer check this...

**Comment by l2isbad** [comment]
> specifying (almost) arbitrary headers

https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/UrlService.py#L25

https://github.com/firehol/netdata/blob/master/conf.d/python.d/powerdns.conf#L77-L78

**Comment by l2isbad** [comment]
```yaml
job_name:
  url: "URL"
  header:
    user-agent: "USER_AGENT"
```

**Comment by ktsaou** [comment]
Wow! It is already there...

**Comment by dseira** [comment]
cool! it works!

Thanks!

I'm going to create a PR to put this into a comment in htttpcheck plugin because it is a really useful feature.

**Comment by orgoj** [comment]
> ```yaml
> job_name:
>   url: "URL"
>   header:
>     user-agent: "USER_AGENT"
> ```

headers:
