### ISSUE TITLE
IPv4 UDPLite stats are always visible, even if UDPLite is not used on a system

### ISSUE THREAD

**Issue by Ferroin** [firehol/netdata#3706]
Just noticed this while testing #3705.  The IPv4 networking section shows UDPLite charts, but the IPv6 section does not, despite there being separate files for IPv4 and IPv6 stats for UDPLite in `/proc/net`.

**Comment by ktsaou** [comment]
hm... the ipv4 versions do not check if the values are non-zero. let me fix that. There is no point to have charts with just zeros...

**Comment by ktsaou** [comment]
In PR  #3705
