### ISSUE TITLE
question: writing a plugin from list of dicts

### ISSUE THREAD

**Issue by binooetomo** [firehol/netdata#3713]
I've list of dicts like :

```
[
    {"LVE": "UID_577",
		"NETI": 0,
		"lNETI": 0,
		"NETO": 0,
		"lNETO": 0,
		"EP": 0,
		"lEP": 20,
		"fEP": 0,
		"MEM": 0,
		"lMEM": 262144,
		"fMEM": 0,
		"CPU": 0,
		"lCPU": 10000,
		"IO": 0,
		"lIO": 1024,
		"NPROC": 0,
		"lNPROC": 100,
		"fNPROC": 0,
		"IOPS": 0,
		"lIOPS": 1024,
		"MEMPHY": 0,
		"lMEMPHY": 262144,
		"fMEMPHY": 0,
		"nCPU": 1,
		"lCPUW": 100},
    {"LVE": "willesta",
		"NETI": 0,
		"lNETI": 0,
		"NETO": 0,
		"lNETO": 0,
		"EP": 0,
		"lEP": 20,
		"fEP": 0,
		"MEM": 0,
		"lMEM": 262144,
		"fMEM": 0,
		"CPU": 0,
		"lCPU": 10000,
		"IO": 0,
		"lIO": 1024,
		"NPROC": 0,
		"lNPROC": 100,
		"fNPROC": 0,
		"IOPS": 0,
		"lIOPS": 1024,
		"MEMPHY": 0,
		"lMEMPHY": 262144,
		"fMEMPHY": 0,
		"nCPU": 1,
		"lCPUW": 100},
    {"LVE": "mailman",
		"NETI": 0,
		"lNETI": 0,
		"NETO": 30600,
		"lNETO": 0,
		"EP": 0,
		"lEP": 20,
		"fEP": 0,
		"MEM": 0,
		"lMEM": 262144,
		"fMEM": 0,
		"CPU": 5529209233,
		"lCPU": 10000,
		"IO": 3056,
		"lIO": 1024,
		"NPROC": 0,
		"lNPROC": 100,
		"fNPROC": 0,
		"IOPS": 298,
		"lIOPS": 1024,
		"MEMPHY": 116,
		"lMEMPHY": 262144,
		"fMEMPHY": 0,
		"nCPU": 1,
		"lCPUW": 100},
]

```
That list is dynamicaly created by reading /proc/lve/list and /etc/passwd of CloudLinux, means the length of list is different for each call:
Actually, the example list is just part of real data I got.

Kindly please tell me how to write plugin if ... For every 'LVE' I want charts of:
1. Network : NETI vs NTO
2. Memory : MEM vs lMEM
3. Disk IO : IO vs lIO

I read https://github.com/firehol/netdata/blob/master/python.d/beanstalk.chart.py , but still don't know how to adopt it.

Sincerely
-bino-

**Comment by l2isbad** [comment]
> means the length of list is different for each call

To be honest i don't get it :cry:  Are LVEs different at each call? How often do they change? Should we remove LVE from charts if it is not in call result or return zeros?

**Comment by l2isbad** [comment]
And yes, seem `beanstalk` module is ok example for your needs.

**Comment by binooetomo** [comment]
@l2isbad  yes ....
What I mean with LVE is LVE user id.
So each time an admin adding or deleting a user, the length of the list will change.

actualy, the original value of key LVE is a user's UID , but I replace it with user's name ... taken from /etc/passwd

here is how I got the datas :

```
uids = {}
with open('/etc/passwd','r') as pwdfile :
    for p in pwdfile.readlines() :
        u = p.strip().split(':')
        if u[-1] != '/usr/local/cpanel/bin/noshell' :
            continue
        uids[u[2]]=u[0]

xxx=[]
with open('/proc/lve/list', 'r') as procfile :
    lines = procfile.readlines()
    headers = lines[0].strip()
    if ':' in headers :
        headers = headers.split(':')[1]
    headers = headers.split('\t')
    for l in lines[1:] :
        thisdict={}
        datas = l.strip().split('\t')
        for i in range(len(datas)) :
            thisdict[headers[i]] = int(datas[i])
        if str(thisdict['LVE']) in uids :
            thisdict['LVE'] = uids[str(thisdict['LVE'])]
        else :
            thisdict['LVE'] = 'UID_'+str(thisdict['LVE'])
        xxx.append(thisdict)

```

**Comment by binooetomo** [comment]
Great ...
I really appreciate
I'll report as soon as possible.

**Comment by binooetomo** [comment]
Dear @l2isbad 
here is my modification in _get_raw_data

```
    def _get_raw_data(self):
        retdict = [
                    {"LVE": "UID_577",
		                "NETI": 0,
		                "lNETI": 0,
		                "NETO": 0,
		                "lNETO": 0,
		                "EP": 0,
		                "lEP": 20,
		                "fEP": 0,
		                "MEM": 0,
		                "lMEM": 262144,
		                "fMEM": 0,
		                "CPU": 0,
		                "lCPU": 10000,
		                "IO": 0,
		                "lIO": 1024,
		                "NPROC": 0,
		                "lNPROC": 100,
		                "fNPROC": 0,
		                "IOPS": 0,
		                "lIOPS": 1024,
		                "MEMPHY": 0,
		                "lMEMPHY": 262144,
		                "fMEMPHY": 0,
		                "nCPU": 1,
		                "lCPUW": 100},
                    {"LVE": "willesta",
		                "NETI": 0,
		                "lNETI": 0,
		                "NETO": 0,
		                "lNETO": 0,
		                "EP": 0,
		                "lEP": 20,
		                "fEP": 0,
		                "MEM": 0,
		                "lMEM": 262144,
		                "fMEM": 0,
		                "CPU": 0,
		                "lCPU": 10000,
		                "IO": 0,
		                "lIO": 1024,
		                "NPROC": 0,
		                "lNPROC": 100,
		                "fNPROC": 0,
		                "IOPS": 0,
		                "lIOPS": 1024,
		                "MEMPHY": 0,
		                "lMEMPHY": 262144,
		                "fMEMPHY": 0,
		                "nCPU": 1,
		                "lCPUW": 100},
                    {"LVE": "mailman",
		                "NETI": 0,
		                "lNETI": 0,
		                "NETO": 30600,
		                "lNETO": 0,
		                "EP": 0,
		                "lEP": 20,
		                "fEP": 0,
		                "MEM": 0,
		                "lMEM": 262144,
		                "fMEM": 0,
		                "CPU": 5529209233,
		                "lCPU": 10000,
		                "IO": 3056,
		                "lIO": 1024,
		                "NPROC": 0,
		                "lNPROC": 100,
		                "fNPROC": 0,
		                "IOPS": 298,
		                "lIOPS": 1024,
		                "MEMPHY": 116,
		                "lMEMPHY": 262144,
		                "fMEMPHY": 0,
		                "nCPU": 1,
		                "lCPUW": 100},
                ]
        return retdict

```
Here is the result : 
![screenshot_2018-05-11_18-48-41](https://user-images.githubusercontent.com/28727621/39923124-8a1def6e-554c-11e8-96ad-a1bcf1415f42.png)

The first chart (Network) looks fine ... there is 'neti' and 'neto'.
But ...
the 2nd (Memory) only show 'lmem', while there have to be 'mem' also.
the 3rd (Disk) only show 'lio', while there have tobe 'io' also.

here is the debug : 

> 
> netdata@core:/etc/netdata/python.d$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace lve
> 2018-05-11 11:47:57: python.d INFO: plugin: main: Using python 2
> 2018-05-11 11:47:57: python.d DEBUG: plugin: main: module load source: 'lve' => [OK]
> 2018-05-11 11:47:57: python.d DEBUG: plugin: main: module load config: 'lve' => [OK]
> 2018-05-11 11:47:57: python.d DEBUG: plugin: main: job initialization: 'lve lve_job' => ['OK']
> 2018-05-11 11:47:57: python.d DEBUG: plugin: main: module status: 'lve' => [OK] (jobs: 1)
> 2018-05-11 11:47:57: python.d INFO: lve: lve_job: check() => [OK]
> CHART netdata.runtime_lve_CL_LVE '' 'Execution time for lve_CL_LVE' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
> DIMENSION run_time 'run time' absolute 1 1
> 
> 2018-05-11 11:47:57: python.d DEBUG: lve: lve_job: create() => [OK] (charts: 9)
> 2018-05-11 11:47:57: python.d DEBUG: lve: lve_job: started, update frequency: 1, retries: 60
> 2018-05-11 11:47:57: python.d DEBUG: lve: lve_job: sleeping for 0.841547966003 to reach frequency of 1 sec
> CHART lve_CL_LVE.mailman_disk '' 'Disk' 'units' 'lve mailman' 'lve.disk' line 60008 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'mailman_IO' 'io' absolute 1 1 ''
> DIMENSION 'mailman_lIO' 'lio' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.mailman_disk 0
> SET 'mailman_IO' = 3056
> SET 'mailman_lIO' = 1024
> END
> 
> CHART lve_CL_LVE.UID_577_memory '' 'Memory' 'units' 'lve UID_577' 'lve.memory' line 60001 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'UID_577_MEM' 'mem' absolute 1 1 ''
> DIMENSION 'UID_577_lMEM' 'lmem' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.UID_577_memory 0
> SET 'UID_577_MEM' = 0
> SET 'UID_577_lMEM' = 262144
> END
> 
> CHART lve_CL_LVE.UID_577_disk '' 'Disk' 'units' 'lve UID_577' 'lve.disk' line 60002 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'UID_577_IO' 'io' absolute 1 1 ''
> DIMENSION 'UID_577_lIO' 'lio' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.UID_577_disk 0
> SET 'UID_577_IO' = 0
> SET 'UID_577_lIO' = 1024
> END
> 
> CHART lve_CL_LVE.willesta_disk '' 'Disk' 'units' 'lve willesta' 'lve.disk' line 60005 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'willesta_IO' 'io' absolute 1 1 ''
> DIMENSION 'willesta_lIO' 'lio' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.willesta_disk 0
> SET 'willesta_IO' = 0
> SET 'willesta_lIO' = 1024
> END
> 
> CHART lve_CL_LVE.mailman_network '' 'Network' 'units' 'lve mailman' 'lve.network' line 60006 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'mailman_NETI' 'neti' absolute 1 1 ''
> DIMENSION 'mailman_NETO' 'neto' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.mailman_network 0
> SET 'mailman_NETI' = 0
> SET 'mailman_NETO' = 30600
> END
> 
> CHART lve_CL_LVE.mailman_memory '' 'Memory' 'units' 'lve mailman' 'lve.memory' line 60007 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'mailman_MEM' 'mem' absolute 1 1 ''
> DIMENSION 'mailman_lMEM' 'lmem' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.mailman_memory 0
> SET 'mailman_MEM' = 0
> SET 'mailman_lMEM' = 262144
> END
> 
> CHART lve_CL_LVE.willesta_network '' 'Network' 'units' 'lve willesta' 'lve.network' line 60003 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'willesta_NETI' 'neti' absolute 1 1 ''
> DIMENSION 'willesta_NETO' 'neto' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.willesta_network 0
> SET 'willesta_NETI' = 0
> SET 'willesta_NETO' = 0
> END
> 
> CHART lve_CL_LVE.UID_577_network '' 'Network' 'units' 'lve UID_577' 'lve.network' line 60000 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'UID_577_NETI' 'neti' absolute 1 1 ''
> DIMENSION 'UID_577_NETO' 'neto' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.UID_577_network 0
> SET 'UID_577_NETI' = 0
> SET 'UID_577_NETO' = 0
> END
> 
> CHART lve_CL_LVE.willesta_memory '' 'Memory' 'units' 'lve willesta' 'lve.memory' line 60004 1 '' 'python.d.plugin' 'lve'
> DIMENSION 'willesta_MEM' 'mem' absolute 1 1 ''
> DIMENSION 'willesta_lMEM' 'lmem' absolute 1 1 ''
> 
> BEGIN lve_CL_LVE.willesta_memory 0
> SET 'willesta_MEM' = 0
> SET 'willesta_lMEM' = 262144
> END
> 
> BEGIN netdata.runtime_lve_CL_LVE 0
> SET run_time = 0
> END
> 
> 2018-05-11 11:47:58: python.d DEBUG: lve: lve_job: update => [OK] (elapsed time: 0, retries left: 60)
> 2018-05-11 11:47:58: python.d DEBUG: lve: lve_job: sleeping for 0.996820926666 to reach frequency of 1 sec
> 
 

I really appreciate your help

Sincerely
-bino-

**Comment by l2isbad** [comment]
![screenshot_20180511_210610](https://user-images.githubusercontent.com/22274335/39923562-2af00dde-555f-11e8-8283-0a0d41c0809a.png)

**Comment by binooetomo** [comment]
Got It .....

But for the sake of fancy, kindly please tell where to set it to 'All' 

Sincerely
-bino-

**Comment by l2isbad** [comment]
`Dashboard` -> `Settings`

**Comment by binooetomo** [comment]
Done.

I wil post complete code soon as I can deploy in production machine.

Sincerely
-bino-
