### ISSUE TITLE
/etc/netdada files keep changing

### ISSUE THREAD

**Issue by jorgemfm** [firehol/netdata#3714]
Hi!

We are currently implementing an intrusion detection system on our infrastructure. This system is configured to detect file changes and we started to notice that files inside /etc/netdata keeps changing sometimes daily, including files like:

/etc/netdata/charts.d/apache.conf.old
/etc/netdata/charts.d/nut.conf.orig
/etc/netdata/charts.d/example.conf
/etc/netdata/python.d/unbound.conf
/etc/netdata/python.d/spigotmc.conf
/etc/netdata/node.d/snmp.conf.md
/etc/netdata/node.d/README.md

etc...

Is this normal?

Thank You

**Comment by ktsaou** [comment]
Hi,

You most probably have the automatic update feature (a daily cron job that updates netdata - you can delete it if you don't want it).

Every time netdata is updated, all the config files that have not been changed by a user, but have been changed upstream, are replaced and a backup is kept. This is done by comparing the MD5 sums of them with the ones found in the repo.

So, as long as you don't touch the config files and they are updated by us, every update installs their latest versions.

3 versions of the files are kept in /etc/netdata:

1. `XXX.conf` the currently active config file - this is overwritten on updates, if not touched by you
2. `XXX.conf.orig` the original config file for the version of netdata installed
3. `XXX.conf.old` the previous version of the config you had installed, before updating netdata (a backup of your previous version)

**Comment by ktsaou** [comment]
Just to be clear: netdata itself (the daemon and its plugin) do not write anything in `/etc/netdata`. They only read these files. Only the update process (the netdata installer) writes files in `/etc/netdata`.

**Comment by ktsaou** [comment]
I use it on production servers (so, I try to be very careful with the merges).
But, this is not a commitment that bugs will not be introduced. I just try to the best of my knowledge and testing so far, to merge stable code and features.
