### ISSUE TITLE
Permit percentColors of Gauge chart to be set

### ISSUE THREAD

**Issue by afletch** [firehol/netdata#372]
as per: http://jsfiddle.net/berni/Yb4d7/

The percentColours values are currently set in dashboard.js (gaugueChartCreate) by adjusting the luminance of the startColor, but this really doesn't achieve much at all.

The intention of this option is to provide percent-based colors to reflect the value displayed (see jsfiddle above)

Suggest allowing these to be set via the custom dash using attr such as `data-gauge-percent-color-0, data-gauge-percent-color-50, data-gauge-percent-color-100`

eg.
```
<div data-netdata="unique.id"
     data-chart-library="gauge"
     data-gauge-percent-color-0="#009900" // green
     data-gauge-percent-color-50="#ff9933" // amber
     data-gauge-percent-color-100="#ff3300" //red
     ></div>
```

**Comment by ktsaou** [comment]
I have added it, but you have to do this:

```
<div data-netdata="unique.id"
    data-chart-library="gauge"
    data-gauge-generate-gradient="[0, 10, 100]"
    data-gauge-gradient-percent-color-0="#FFFFFF"
    data-gauge-gradient-percent-color-10="#999900"
    data-gauge-gradient-percent-color-100="#000000"
    ></div>
```

The `data-gauge-generate-gradient` can be `true`, `false` or an array of the percentages you want to give custom colors. You can add as many percentages as you like.

This is not merged yet.

**Comment by ktsaou** [comment]
It is in PR #375

**Comment by ktsaou** [comment]
merged it
