### ISSUE TITLE
restart required on backend dns change?

### ISSUE THREAD

**Issue by colomb001** [firehol/netdata#3721]
I'm sending netdata metrics to influxdb using the opentsb backend type. I moved the influxdb to a new server and expected netdata to start sending metrics to the new server once the DNS updated had propagated. Unfortunately, that wasn't the case. Even though dns resolved correctly on the netdata host sending the data, netdata continued to send data to old server until I restarted service.

**Comment by ktsaou** [comment]
I think this is related to DNS caching. netdata resolves the hostname on every connection attempt. But the system may be caching the result.

**Comment by ktsaou** [comment]
Just verified what I posted above.
The code really resolves all hostnames on every connection attempt. It is up to the system to respond with the valid IP address.
