### ISSUE TITLE
debian package generates version 1.0.0 instead of 1.1.0

### ISSUE THREAD

**Issue by jsveiga** [firehol/netdata#373]
Hi, I'm generating the debian Jessie package with:
`git pull`
`ln -s contrib/debian`
`dpkg-buildpackage -us -uc -rfakeroot`
but although the current release is 1.1.0, the generated package is
`netdata_1.0.0_amd64.deb`
and it installs as 1.0.0 (version returned by dpkg-query).

Thanks!

EDIT: Note: the actual program is updated, it's just the version identification which is not.

**Comment by ktsaou** [comment]
I think this is the cause: https://github.com/firehol/netdata/pull/132#issuecomment-214719345

I have updated the debian changelog file with #375.

@mcnewton, @lhw is this correct? Should I merge it?

**Comment by ktsaou** [comment]
I will merge it (too many outstanding merges with it). If something is wrong, let me know.

**Comment by mcnewton** [comment]
@ktsaou yes, that's perfect.

It is up to you really whether you want to be that detailed in the debian/changelog file. Personally I would just add a new entry at the top with the new version that just says something like "Update to new version" in the comments. Or even, being very naughty, replace the whole file with a copy that has just a single entry with the new version number in it.

For the Debian project, that file makes sense. For a debian/ directory in the upstream codebase all you really care about is the version number in it. The rest is interesting for the end user, but they will be the one that built the package so it's not critical as they'll have a copy of your ChangeLog file anyway.

The best thing might be to update whatever scripts you use to build a new release to just update the version in debian/changelog automatically. Not as accurate, but one less thing to worry about having to do each release.

Cheers,
Matthew

**Comment by ktsaou** [comment]
thanks!

> The best thing might be to update whatever scripts you use to build a new release to just update the version in debian/changelog automatically. Not as accurate, but one less thing to worry about having to do each release.

@philwhineray can you take care of this at the release system?

**Comment by philwhineray** [comment]
Yes; I will look at this as soon as I get a chance. I guess manual action is OK until then.
