### ISSUE TITLE
Feed stops when using bootstrap accordion

### ISSUE THREAD

**Issue by solitaryr** [firehol/netdata#374]
I'm trying to create a dashboard using bootstrap [collapsible accordion sections](http://getbootstrap.com/javascript/#collapse-example-accordion) but if I collapse the section, the graphs disappear when uncollapsed.  I'm sure i'm missing something simple but web development is not my strong suit.  Any advice would be appreciated.

thanks

=G=

**Comment by ktsaou** [comment]
Try adding this at your page, after loading `dashboard.js`:

```html
<script>
$('.collapse').on('shown.bs.collapse', NETDATA.onscroll);
</script>
```

If it works, I'll add it to `dashboard.js` so that it will be there by default.

**Comment by ktsaou** [comment]
In general the `NETDATA.onscroll()` function notifies the dashboard that something changed on the page regarding the visibility of charts. `dashboard.js` caches heavily almost everything to achieve its speed, so when the visibility of charts is changed, it must be notified to re-evaluate the visible charts.

**Comment by ktsaou** [comment]
You are going to need both `hidden` and `shown`. I updated my response above.

**Comment by solitaryr** [comment]
Awesome.  Worked for me.  Thanks.

**Comment by ktsaou** [comment]
nice!

**Comment by ktsaou** [comment]
merged the change too into the repo.
