### ISSUE TITLE
Do you have in plan to implement Megacli (hardware RAID) support metrics ?

### ISSUE THREAD

**Issue by petarkozic** [firehol/netdata#3757]
Hi,
this is question only.
Do you have in plan to implement MegaCLI output for hardware RAID support and battery on hardware raid.
This is very useful for many. 
Thank's !

**Comment by ktsaou** [comment]
I think this is just the output of a command line. Right?

If yes, could you please post here the output of the command you are interested?

**Comment by petarkozic** [comment]
Than, command:
`megacli -AdpBbuCmd  -a0`

show full info about battery on RAID controller.

Usefull info was bolded.


BBU status for Adapter: 0

BatteryType: BBU
**Voltage: 3902 mV**
Current: 0 mA
Temperature: 31 C
**Battery State: Optimal**
BBU Firmware Status:

  **Charging Status              : None**
  Voltage                                 : OK
  Temperature                             : OK
  Learn Cycle Requested	                  : No
  Learn Cycle Active                      : No
  Learn Cycle Status                      : OK
  Learn Cycle Timeout                     : No
  I2c Errors Detected                     : No
  Battery Pack Missing                    : No
  Battery Replacement required            : No
  Remaining Capacity Low                  : No
  Periodic Learn Required                 : No
  Transparent Learn                       : No
  No space to cache offload               : No
  Pack is about to fail & should be replaced : No
  Cache Offload premium feature required  : No
  Module microcode update required        : No

BBU GasGauge Status: 0x0128
Relative State of Charge: 91 %
Charger Status: Complete
Remaining Capacity: 526 mAh
Full Charge Capacity: 583 mAh
isSOHGood: Yes
  Battery backup charge time : 0 hours

BBU Capacity Info for Adapter: 0

  Relative State of Charge: 91 %
  Absolute State of charge: 0 %
  Remaining Capacity: 526 mAh
  Full Charge Capacity: 583 mAh
  Run time to empty: Battery is not being charged.
  Average time to empty: 42 Min.
  Estimated Time to full recharge: Battery is not being charged.
  Cycle Count: 5
Max Error = 0 %
Remaining Capacity Alarm = 0 mAh
Remining Time Alarm = 0 Min

BBU Design Info for Adapter: 0

  Date of Manufacture: 00/00, 0000
  Design Capacity: 460 mAh
  Design Voltage: 0 mV
  Specification Info: 0
  Serial Number: 0
  Pack Stat Configuration: 0x0000
  Manufacture Name: 0x113
  Firmware Version   : 0.4
  Device Name:
  Device Chemistry:
  Battery FRU: N/A
Module Version = 0.4
  Transparent Learn = 1
  App Data = 1

BBU Properties for Adapter: 0

  Auto Learn Period: 90 Days
  Next Learn time: Sat Jul 14 02:06:53 2018
  Learn Delay Interval:0 Hours
  Auto-Learn Mode: Transparent

Exit Code: 0x00

**Comment by Ferroin** [comment]
For the first command, the error counts strike me as potentially being useful as well.

For the second command, exposing the charge percentage seems to make sense (and the temperature probably does too, if that isn't already covered by the `sensors` module).

**Comment by petarkozic** [comment]
Sure, especially Media Error is very useful. Sometimes Media Error can suggest us that we can expect some problem with that disk :)

**Comment by l2isbad** [comment]
@petarkozic 
please do
- `time megacli -LDPDInfo -aAll > /dev/null`
- `time megacli -AdpBbuCmd -a0 > /dev/null`

What about `megacli` permissions?

**Comment by Ferroin** [comment]
Not 100% certain about this, but I think permissions require that either:

1. You're running as `root`, or have CAP_SYS_ADMIN.
or:
2. The command is SUID 0 or has CAP_SYS_ADMIN in it's filesystem capabilities.
or:
3. You configure the system such that your user has read and write access to the device nodes associated with the MegaRAID devices.

**Comment by l2isbad** [comment]
@petarkozic 

So the only important info is **State** and we want to know if state is **Degraded** or not, am i right?

What charts do we need?

**Comment by petarkozic** [comment]
@l2isbad 
Ok, here is some advice for important info.

**Media error** is very useful info because can tell us that drive have some fail, in that situation RAID maybe works correctly but we need to check that drive before fail totally.

**State: Degraded** is mandatory, that tell us the RAID was degraded, on or more disk fail completely and RAID don't have consistency.

**Predictive Failure Count** also warn us that this disk have some problem. Here is different experience, but in general this is very useful info.
This is info from SMART for Predictive Failure Count:
Predictive failures

> S.M.A.R.T. signals predictive failures when the drive is performing unacceptably for a period of time. The firmware keeps a running count of the number of times the error rate for each attribute is unacceptable. To accomplish this, a counter is incremented each time the error rate is unacceptable and decremented (not to exceed zero) whenever the error rate is acceptable. If the counter continually increments such that it reaches the predictive threshold, a predictive failure is signaled. This counter is referred to as the Failure
> 
> History Counter. There is a separate Failure History Counter for each attribute.

Charts, hm..
Here is very useful battery capacity chart-s. Alongside where we can see currently capacity we can see when capacity of our battery fall down, that is useful info for us that we need to change battery.

Also maybe, media error charts. Why ? If someone use netdata as collector also, (I'm using) to proceed data to prometheus, can check in long period when this error happened.

I think all this info was useful, if I can help something I'm here ;)

**Comment by l2isbad** [comment]
@petarkozic 
please post here full output of `megacli -LDPDInfo -aAll`

**Comment by petarkozic** [comment]
@l2isbad 

Length depend of how much disk you have, for each disk info is repeated:

```
Adapter #0

Number of Virtual Disks: 1
Virtual Drive: 0 (Target Id: 0)
Name                :Virtual Disk 0
RAID Level          : Primary-1, Secondary-0, RAID Level Qualifier-0
Size                : 3.491 TB
Sector Size         : 512
Is VD emulated      : No
Mirror Data         : 3.491 TB
State               : Optimal
Strip Size          : 64 KB
Number Of Drives    : 8
Span Depth          : 1
Default Cache Policy: WriteBack, ReadAhead, Direct, No Write Cache if Bad BBU
Current Cache Policy: WriteBack, ReadAhead, Direct, No Write Cache if Bad BBU
Default Access Policy: Read/Write
Current Access Policy: Read/Write
Disk Cache Policy   : Disk's Default
Encryption Type     : None
Default Power Savings Policy: Controller Defined
Current Power Savings Policy: None
Can spin up in 1 minute: No
LD has drives that support T10 power conditions: No
LD's IO profile supports MAX power savings with cached writes: No
Bad Blocks Exist: No
PI type: No PI

Is VD Cached: No
Number of Spans: 1
Span: 0 - Number of PDs: 8

PD: 0 Information
Enclosure Device ID: 32
Slot Number: 0
Drive's position: DiskGroup: 0, Span: 0, Arm: 0
Enclosure position: 1
Device Id: 0
WWN: 5002538c4002e713
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221104000000
Connected Port Number: 4(path0)
Inquiry Data: S1YHNXAG804005      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :33C (91.40 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 1 Information
Enclosure Device ID: 32
Slot Number: 2
Drive's position: DiskGroup: 0, Span: 0, Arm: 1
Enclosure position: 1
Device Id: 2
WWN: 5002538c00019b96
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221106000000
Connected Port Number: 6(path0)
Inquiry Data: S1YHNYAG600061      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :33C (91.40 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 2 Information
Enclosure Device ID: 32
Slot Number: 1
Drive's position: DiskGroup: 0, Span: 0, Arm: 2
Enclosure position: 1
Device Id: 1
WWN: 5002538c4002e707
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221100000000
Connected Port Number: 0(path0)
Inquiry Data: S1YHNXAG803993      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :34C (93.20 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 3 Information
Enclosure Device ID: 32
Slot Number: 3
Drive's position: DiskGroup: 0, Span: 0, Arm: 3
Enclosure position: 1
Device Id: 3
WWN: 5002538c4002e70f
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221102000000
Connected Port Number: 2(path0)
Inquiry Data: S1YHNXAG804001      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :34C (93.20 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 4 Information
Enclosure Device ID: 32
Slot Number: 5
Drive's position: DiskGroup: 0, Span: 0, Arm: 4
Enclosure position: 1
Device Id: 5
WWN: 5002538c4002e712
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221101000000
Connected Port Number: 1(path0)
Inquiry Data: S1YHNXAG804004      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :34C (93.20 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 5 Information
Enclosure Device ID: 32
Slot Number: 4
Drive's position: DiskGroup: 0, Span: 0, Arm: 5
Enclosure position: 1
Device Id: 4
WWN: 5002538c4002e6e9
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221105000000
Connected Port Number: 5(path0)
Inquiry Data: S1YHNXAG803963      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :33C (91.40 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 6 Information
Enclosure Device ID: 32
Slot Number: 6
Drive's position: DiskGroup: 0, Span: 0, Arm: 6
Enclosure position: 1
Device Id: 6
WWN: 5002538c4002da83
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221107000000
Connected Port Number: 7(path0)
Inquiry Data: S1YHNXAG801029      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :33C (91.40 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




PD: 7 Information
Enclosure Device ID: 32
Slot Number: 7
Drive's position: DiskGroup: 0, Span: 0, Arm: 7
Enclosure position: 1
Device Id: 7
WWN: 5002538c4002dade
Sequence Number: 2
Media Error Count: 0
Other Error Count: 0
Predictive Failure Count: 0
Last Predictive Failure Event Seq Number: 0
PD Type: SATA

Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
Coerced Size: 893.75 GB [0x6fb80000 Sectors]
Sector Size:  512
Logical Sector Size:  512
Physical Sector Size:  512
Firmware state: Online, Spun Up
Device Firmware Level: 003Q
Shield Counter: 0
Successful diagnostics completion on :  N/A
SAS Address(0): 0x4433221103000000
Connected Port Number: 3(path0)
Inquiry Data: S1YHNXAG801120      SAMSUNG MZ7LM960HCHP-00003              GXT3003Q
FDE Capable: Not Capable
FDE Enable: Disable
Secured: Unsecured
Locked: Unlocked
Needs EKM Attention: No
Foreign State: None
Device Speed: 6.0Gb/s
Link Speed: 6.0Gb/s
Media Type: Solid State Device
Drive:  Not Certified
Drive Temperature :34C (93.20 F)
PI Eligibility:  No
Drive is formatted for PI information:  No
PI: No PI
Drive's NCQ setting : N/A
Port-0 :
Port status: Active
Port's Linkspeed: 6.0Gb/s
Drive has flagged a S.M.A.R.T alert : No




Exit Code: 0x00
```

**Comment by l2isbad** [comment]
How to determine which PD is out of order (`State: Degraded`)?

**Comment by petarkozic** [comment]
State **Degraded** is on Adapter level not on PD. 
State degraded only can show to us that RAID don't have consistently and we need to find faulty drives.

In the moment when RAID is degraded, some of PD info may exclude because drive was totally fails, becuase is to hard to find which PD (drive) was fault.

You can see similar http://www.mostlychris.com/blog/2009/07/29/check-raid-status-with-megacli/

**Comment by l2isbad** [comment]
@petarkozic so...

- adapter has n SPANs
- SPAN has n PDs

am i right?

Slot number is always unique?

**Comment by petarkozic** [comment]
@l2isbad 

Yes, adapter has n SPANS and SPANS has n PDs(Phisical Drives)

Yes, slot number is always unique. If some drive fails in some n SLOT, and we change that drive, after changing that drive will have it  same n SLOT number.

**Comment by petarkozic** [comment]
@l2isbad @ktsaou 
Can we implement RAID status for Adaptec raid controler because Adaptec have own cli ?
I can help you again with output and test.

Thank you.

**Comment by l2isbad** [comment]
@petarkozic Sure. Open a new issue.
