### ISSUE TITLE
Support for squid custom_log_format in web_log plugin

### ISSUE THREAD

**Issue by salsa-dev** [firehol/netdata#3759]
As far as I understand the squid type of the we_log plugin doesn't support custom_log_format with regex.

https://github.com/firehol/netdata/blob/34a49fbd039c59241a41e6490893f4cc1e1a5b46/python.d/web_log.chart.py#L789

Could you, please, support custom log format?

**Comment by l2isbad** [comment]
Yes, you are right.

https://github.com/firehol/netdata/issues/3730

**Comment by salsa-dev** [comment]
Oh, someone has already opened an issue for this. It took me two weeks to submit it. Sorry, closing this.
