### ISSUE TITLE
Access to file '/usr/share/netdata/web/index.html' is not permitted, and then Failed to contact the registry

### ISSUE THREAD

**Issue by SaintFenix** [firehol/netdata#3764]
#1199
I was having the issue as labeled here but was able to fix it by uncommenting a few lines in my /etc/netdata/netdata.conf [web] header.

I believe the problem is similar due to me installing on Gentoo.

```
[web]
	# mode = static-threaded
	# listen backlog = 4096
	default port = 19999
	bind to = *
	web files owner = netdata
	web files group = netdata
	# disconnect idle clients after seconds = 60
	# timeout for first request = 60
	# respect do not track policy = no
	# x-frame-options response header = 
	# allow connections from = localhost *
	# allow dashboard from = localhost *
	# allow badges from = *
	# allow streaming from = *
	# allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
	# enable gzip compression = yes
	# gzip compression strategy = default
	# gzip compression level = 3
	# web server threads = 6
	# web server max sockets = 512
```

The problem is, is that now, I cannot seem to get netdata to connect to my registry on another machine. it throws this error:

In order to clarify my steps:

1. I attempted to Emerge it first from the gentoo repositories, the version is older, and I couldn't get it to come up, or work at all.

2. I instead used the 1 liner Curl install, that seemed to work fine, netdata wouldn't come up without a restart however, 

3. after the restart it came up properly, but then it gave me a very small and strange netdata.conf I then modified it by adding the [registry] tag and a few parameters since I thought that would be all I need, that didn't work though:

```
# netdata configuration
#
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

[global]
    run as user = netdata

    # the default database size - 1 hour
    history = 3600

    # by default do not expose the netdata port
    bind to = localhost

[web]
    web files owner = root
    web files group = netdata

[registry]
    enabled = no
    registry to announce = 192.168.1.150:19999
```

4. I then copied a working one from an Ubuntu system I had just in case I was missing something, which made it work!, All lines in this copied version are commented, with the exception of the four marked above in [web] and the two uncommented in [registry] so that I could host my own. here is that section:

```
[registry]
	enabled = no
	# registry db directory = /var/lib/netdata/registry
	# netdata unique id file = /var/lib/netdata/registry/netdata.public.unique.id
	# registry db file = /var/lib/netdata/registry/registry.db
	# registry log file = /var/lib/netdata/registry/registry-log.db
	# registry save db every new entries = 1000000
	# registry expire idle persons days = 365
	# registry domain = 
	registry to announce = 192.168.1.150:19999
	# registry hostname = WestGermany
	# verify browser cookies support = yes
	# max URL length = 1024
	# max URL name length = 50
	# allow from = *
```

I've already got a constellation of Netdata servers running and am trying to have them all connect to the same registry, all of them save this one seem to do so fine.

5. I tried this command to get it to connect to my registry

`sudo chown -R root /usr/share/netdata`

which borked it and the page would load saying only: Access to file '/usr/share/netdata/web/index.html' is not permitted,

6. then I did a:

`sudo chown -R netdata /usr/share/netdata`

which brought it back and now it's working. It's currently running, but doesn't connect to my self-hosted registry still.

Any help you can give would be muchly appreciated. :)

**Comment by ktsaou** [comment]
> I attempted to Emerge it first from the gentoo repositories, the version is older, and I couldn't get it to come up, or work at all.

@candrews please check this. The default package for gentoo does not work?

@SaintFenix I think the other problems you faced are because you didn't uninstall the official package before installing from source. Could you please completely remove netdata (both package and `netdata-uninstaller.sh` and re-install from source?

Make sure you don't have `/etc/netdata` before re-installing.

**Comment by csamsel** [comment]
I'm using Gentoo aswell, and reinstalling netdata (or updating it) indeed breaks ownershop of `/usr/share/netdata/web/*`  (files are owned by root) requiring running something like `chown -R netdata:netdata /usr/share/netdata/web`

**Comment by Ferroin** [comment]
Hmm, that's odd, the live ebuild (`net-analyzer/netdata-9999`) seems to work fine here without causing this issue.

As far as the old version in the portage tree, he may have only set keywords for that older version.  Portage has versions from 1.8 up to 1.10, plus the live ebuild which builds direct from the git tree's master branch.

**Comment by csamsel** [comment]
i just had a look at the ebuild

```
101c101
<       fowners -Rc root:${NETDATA_GROUP} /usr/share/${PN}
---
>       fowners -Rc ${NETDATA_USER}:${NETDATA_GROUP} /usr/share/${PN}
```

would do it. Although i'm not sure if adding

```fowners -Rc ${NETDATA_USER}:${NETDATA_GROUP} /usr/share/${PN}/web```

would be better, to keep root as owner of `/usr/share/netdata` (all other dirs in /usr/share are owned by root.

**Comment by Ferroin** [comment]
OK, NVM, my `/etc/netdata/netdata.conf` has:

```
[web]
    web files owner = root
    web files group = netdata
```

Which is why it's working for me.  I'm not quite sure whether or not I added that manually, but it got added at some point, as the ebuild I mentioned above as woking has the same `fowners -Rc root:${NETDATA_GROUP} /usr/share/${PN}` line in it.

**Comment by csamsel** [comment]
Hm, the default configuration in https://github.com/firehol/netdata/blob/master/system/netdata.conf

has these aswell. I might have a relative old installation were these defaults did not exist yet. It was changed in 2016 in 1abb8faa8c

**Comment by SaintFenix** [comment]
I did a complete nuke, and reinstall from source from here, and it is working fine. 

I think @ktsaou and @candrews  are both right, I kinda got in my own way here.

since @csamsel seems to be working on getting an issue fixed here, I won't close my own ticket, but for all intent and purposes here I'm done and good.

Thank you guys for the wonderful software, and the excellent help.

**Comment by ktsaou** [comment]
@csamsel could you please check this:

1. on a clean gentoo
2. install netdata package with emerge
3. install from source, on top of it

This should work. If not, could you please help me adapt the installer  to apply the right permissions? The installer is supposed to check netdata.conf and use web permissions specified there.

**Comment by csamsel** [comment]
Hi, 
i'm sure a clean install will work.

@SaintFenix and my problem was, that we had old configurations with 
```	web files owner = netdata
	web files group = netdata```

instead of the new default `web files owner = root`

**Comment by ktsaou** [comment]
hm... this can only happen if the config was edited by hand.

The packaged version uses `web files owner = root`, while the github version leaves this setting commented. So, if netdata.conf was not edited by hand, how did this setting appear?

**Comment by ktsaou** [comment]
ok, I am closing this, since, as you say, it is not an issue currently.
If I am wrong please correct me.
