### ISSUE TITLE
Theme overrides bootstrap

### ISSUE THREAD

**Issue by solitaryr** [firehol/netdata#377]
I think I'm missing something.  The netdata slate theme appears to be overriding my bootstrap theme.  Is there a way to let the local bootstrap instance manage the theme?  I don't see anything in the wiki.  Gonna keep poking but thought I'd ask.

**Comment by ktsaou** [comment]
Add the following before loading `dashboard.js`:

```html
<script>
var netdataNoBootstrap = true;
</script>
```

You will have to load bootstrap yourself too.

**Comment by solitaryr** [comment]
Seems like I recall reading that setting somewhere.  Looks to have fixed my issue...this one.
