### ISSUE TITLE
netdata ERROR : MAIN : EXIT: cannot unlink pidfile '/run/netdata/netdata.pid'. (errno 2, No such file or directory)

### ISSUE THREAD

**Issue by JianYu97** [firehol/netdata#3771]
system centos 7  ， My last night install netdata direct use github of shell  A key to install ，last night be fine ，but this morning web page cannot be displayed 502 ， journalctl -xe show the title ， Can you help me ， sorry Forgive my English

**Comment by JianYu97** [comment]
In a real environment, you can't use it for a while after installation, what's the reason for that? Well, look through the firefox browser and you can't call the graph, what's the reason for that?

**Comment by ktsaou** [comment]
Hi,

I just installed centos7 on a VM and installed netdata on it.
I can't see any issues. netdata is available for use immediately after installation.

Could you please provide the steps to reproduce the problem?

**Comment by JianYu97** [comment]
Thanks a million your reply，new old stock that‘s it during use log in web show 502，pop up a  Can’t call tabulation ，I don‘t you Touch not encountered 。

**Comment by JianYu97** [comment]
I just put it there netdata systemctl stop and systemctl start ，again login web show
“ ERROR 405: Cannot download charts index from server”    your now error ？

**Comment by JianYu97** [comment]
Now my chart shows that I don't know what caused the mistake. Thank you very much。
About configuration file some questions to ask, I want to change the configuration file under the backend configuration, the # in front of me, or not to is deleted, l still keep no matter the # directly, go directly to modify the back of the parameters，Finally, thank you for opening up the software, and I'm glad we're on the same planet

**Comment by ktsaou** [comment]
Thank you, but I can't understand the question. All the settings that have `#` in front of them, are the defaults. You need to remove the `#` if you want to change the default. To keep the default, with or without `#` does not matter.

**Comment by JianYu97** [comment]
ok，Thank you for you answer
