### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by simonnagl** [firehol/netdata#378]
In the near feature I want to help improving the documentation of netdata.

First I want to make a suggestion how netdata may be documented. I think we should design documentation with this concept:
- Document everything once. That means, if one thing of netdata changes, we have to adapt the documentation at one point.
- Make documentation accessible. This means, someone who installs netdata should be able to read the parts of the documentation he needs to run and configure netdata even without beeing connected to the internet.
- Document workflows.
1. The README at the root directory should
   - [x] Describe as catchy as possible what netdata is.
   - [ ] List the features of netdata (the last release).
   - [ ] Give a short installation guide.
   - [ ] Contain a short reference where to gain further informations.
2. Every subdirectory should contain a README that
   - [ ] Describes what's in the directory.
   - [ ] Referes to further documentation.
3. Documentation in dashboards. (web folder of netdata) should
   - [ ] One page per plugin which.
     - [ ] Describe how to read the values.
     - [ ] Contain links for further reading.
     - [ ] Be a fantastic user expirience. (Try to configure automatic. If not able, let the user configure the dashboard in the site to see some output.)
   - [ ] Describe the pulblic API. (Things we do not whant to change)
     - [ ] REST API.
     - [ ] Configuration options.
4. The online doc (wiki, readthedocs, github pages or mkdocs) should have this areas:
   1. How to install.
   2. How to configure.
      - [ ] Give a extended configuration guide.
   3. How to contribute.
      - [ ] Describe releas cycles.
      - [ ] Coding rules
      - [ ] Describe how to write documentation
      - [ ] Describe how to write plugins
      - [ ] An intruduction to the code. Where to find what.
      - [ ] Hold a roadmap with plans and their status, maby priority.
   
   All areas should be:
   - [ ] editable by everyone. We should let everybody contribute in a save way.
5. The manpages should
   - [ ] Describe the minimum it needs to.
   - [ ] Refer to offline and online documentation.
6. Doxygen should
   - [ ] Document internal headers. Functions and structs

Please tell me what you think about it. There are some things we should discuss.
- Should we add manpages in plain (groff_man) format ore use something more readable like markdown and a converter?
- Wiki vs. Readthedocks. Discussion at #365

**Comment by ktsaou** [comment]
1. yes, I think already does
2. nice idea, yes of course
3. I categorize documentation in the following areas:

  1. **How to use netdata**

    These should be articles, that explain how someone can use an installed netdata to understand the charts. Some of this information should be included in the dashboard itself ( #279 ).

    What would be awesome, is to have live pages - custom dashboards - specializing in monitoring specific things. These pages could in the `web` directory of netdata. For example we may build a custom dashboard that analyzes mysql performance. This dashboard could query netdata to find if you have any mysql servers configured, if not it would give you instructions on how to configure the plugin, if found more than one it would allow you to select one of them and for the selected it would present all the mysql charts, together with a lot more information, links, references, etc. If we do this right, these dashboards should be campaignable (i.e. people should tweet about them, should link to them from forums, blogs, etc).

    We could follow such a pattern for all applications plugins: each plugin should have such a web page.

    I understand this is might be consider a tool, but if you think a bit of it, this is what most people would expect to get. Not only visualize the metrics, but also have references on what each metric means, how they can decide what is good and what is bad, what to do to fix their performance issue, etc. This kind of documentation will make netdata really unique.

  2. **How to configure netdata**

     For this I would follow a simple rule: answer each question once. Instead of answering by commenting at the issue, write the answer at the wiki and link it to the issue.

  3. **How to write plugins**

    This requires a reference manual and examples.

  4. **How to use the API**

    This requires a reference manual and examples.

  5. **How to contribute to netdata**

    This should describe release cycles, coding style, etc.

  Keep in mind **netdata is a web server**. End-user documentation could be distributed with netdata in the `web` directory and the dashboard could link to it.

4. I don't think we need manpages. Just one manpage would be enough that should describe the absolute minimum you might need to read while offline (how to start it, how to stop it, where is the configuration file, what format it has, how to edit it, where you can get more help, etc).

5. I have never used doxygen, so I don't know.

**Comment by simonnagl** [comment]
I answer to the numbering of @ktsaou 

1. Yes. I like to make some enhancements. I will open a pull request for it.
2. Thank you. Pull request will come to.
3. Having categories looks good. Some comments.
    1. I do not know if we need such a section. Live pages sond awesome for informing the user. And could maby be enogh.
    2. Nice idea. Of course.
    3. I think this should be a section/site in how to contribute. If not writing documentation, ect. have to be an area too.
    4. Yes. What's the API for you? Only REST?
    5. Of course.

> nd-user documentation could be distributed with netdata in the web directory and the dashboard could link to it.

I did not think of this option. This sounds great. Maby we should document everything that could be usefull offline there. This is a great method on doing something once and being able to publish it local and online without much effort.

4. With the possibility to link to an offline documentation: You are right! Having a minimal manpage I thing using groff_man is fine.
5. I will release a pull request with one header file documented for an example in the next days.

PS: I edited the first entry.

**Comment by ktsaou** [comment]
1. I can add a repo with the wiki

   This has the problem that for each PR, two repos will need to be synced.

2. I can add the wiki (or sections of it) to a `wiki/` directory in the netdata repo.

  This has the problem that editing the wiki (or the sections copied into `wiki/`) directly on github should be prevented

Any other options?

**Comment by simonnagl** [comment]
What about using github pages for the wiki?

**Advantages**
1. Having the wiki in the repository.
2. Everybody can make pull requests.
3. Changes are displayed without any additional effort.
4. Everybody can purpose a file change directly on github.

**Disadvantages**
1. The wiki moves from https://github.com/firehol/netdata/wiki to https://firehol.github.io/netdata

**Comment by ktsaou** [comment]
It will again require 2 PRs per change. For maintenance viewpoint, gh-pages will be the same with a different repo. No?

**Comment by simonnagl** [comment]
Shure. But we would have pull request only at one repository, not two.
Another option proposed I like was using mkdocs.

We would have a directory wiki. This can be used with mkdocs to compile documentation used local or at the web (firehol admin server)

**Comment by ktsaou** [comment]
I have used gh-pages in the past for http://iplists.firehol.org.

I am not 100% happy with any solution. gh-pages is a new site from scratch. A site for netdata would require a lot of work and I am not ready to deal with it now.

Also, I still believe everything should be served by netdata itself. But this would again require building a site around documentation.

For the time being I suggest to do something very simple.

**Comment by simonnagl** [comment]
> For the time being I suggest to do something very simple.

Of course. Today I tried to port the wiki to mkdocs. I opened a pull request at #420. If you like it I would do the rest of work.

**Comment by ktsaou** [comment]
> Of course. Today I tried to port the wiki to mkdocs. I opened a pull request at #420. If you like it I would do the rest of work.

nice! I'll have a look. Can we use these files to update the github wiki too?

**Comment by simonnagl** [comment]
I am not sure if that can be done easy. There is a tool to update gh-pages but this is not wat you want: http://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages.
I am not sure if there is a simple way to use it for the wiki because I think the github wiki is always a separate git repo.

**Comment by ktsaou** [comment]
yes, but what if I just make a script to copy the files to the wiki?

**Comment by simonnagl** [comment]
This will work. Anyways we have to check if we can use folders in the github wiki repository.
If yes, all is fine.
If not, all is fine anyways. We just have to configure the structure at `mkdoc.yaml`

**Comment by simonnagl** [comment]
> we have to check if we can use folders in the github wiki repository

Checked. It works. The wiki does not care where the files are. The only thing we need to rename is `index.md` (mkdocs) to `Home.md` (wiki).

**Comment by ktsaou** [comment]
Well... I have not yet decided what to do with this.

I know we have discussed this, but I still believe we should move all documentation to the netdata web server.

I have been researching a solution.

So far I have concluded that we should use:

1. https://github.com/markdown-it/markdown-it (it seems the more complete and actively developed markdown implementation for javascript)
2. https://highlightjs.org/ (for syntax highlighting)

And move everything to `web/docs`.

I have also researching for a better navbar menu for the dashboard, something that would allow for more options (like the documentation), which will not be disturbing on mobile devices. I like a lot the menu on this site: http://www.dwmkerr.com/learn-docker-by-building-a-microservice/ However it is for angularjs.

I think we are not ready to work on this yet (at least I am not). I still spend some time researching alternatives.

**Comment by simonnagl** [comment]
> I still believe we should move all documentation to the netdata web server

I also belief this is the best solution.

1. Everybody can help making the documentation better using pull requests.
2. Offline and online documentation.
3. Everything at one place.

I currently have no time to do more research on finding "the best" solution for doing this. You are right, we are not able to work on this at the moment.

> I have also researching for a better navbar menu for the dashboard

Some of my thoughts to this:
We want to have a responsive dashboard. At the same time we get more and more charts. Today we only have the main menu on small screens, not the "chart section menu". I really like your idea using a menu that can be swiped in and out. Maybe we should even use two. One at the left side. There are items which are currently at the header bar (and more). The other one goes on the right side. There is the "chart section menu" which gives a chart overview and faster scrolling. On wide screens both menus can be shown all the time, on small screens they can be accessed with touch gestures and small fixed buttons. The buttons should always contain symbols and text, not just a symbol, because of usability. (Maybe the discussion about navigation should go to another issue)

Can you please tell me what are the disadvantages of using mkdocs (#420)?

**Comment by glensc** [comment]
btw, i read (https://github.com/ariya/phantomjs/pull/14489) that: 
> Also note that Github extremely recently (2016-08-17) added functionality for Github Pages (JekyllRB) to be published from the master branch, if the documentation is placed in a sub-folder titled "doc". This means the site can still be published using Github Pages.

**Comment by simonnagl** [comment]
Closing. Discussion continues at #1518
