### ISSUE TITLE
How netdata get metrics 

### ISSUE THREAD

**Issue by highgozhangyc** [firehol/netdata#3784]
Hi，
How did netdata get the metrics of load(for example,also may be cpu and others)?Did it get that by parsed the /proc/loadavg file,or some other way?
Thanks

**Comment by ktsaou** [comment]
Place the mouse pointer over the date of a chart, and it will tell you.

![image](https://user-images.githubusercontent.com/2662304/41206312-a943c9a6-6d0a-11e8-99cb-6ab01e4bd8be.png)
