### ISSUE TITLE
system.net.sent is off by a factor of 10

### ISSUE THREAD

**Issue by Marcool04** [firehol/netdata#3790]
Hi there,
First things first: thanks to all contributors for this exceptional and highly useful collection of software.
I have run into something rather strange today on an Archlinux ARM Raspberry Pi 3B1. Some general info:

````
$ uname -a
Linux [HOST] 4.14.44-1-ARCH #1 SMP Fri Jun 1 13:13:07 UTC 2018 armv7l GNU/Linux
-------
$ pacman -Si netdata
Repository      : community
Name            : netdata
Version         : 1.10.0-1
Description     : Real-time performance monitoring, in the greatest possible detail, over the web
Architecture    : armv7h
URL             : https://github.com/firehol/netdata/wiki
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libmnl  libnetfilter_acct  zlib
Optional Deps   : [CLIP]
Conflicts With  : None
Replaces        : None
Download Size   : 1800.30 KiB
Installed Size  : 7703.00 KiB
Packager        : Arch Linux ARM Build System <builder+xu5@archlinuxarm.org>
Build Date      : Wed 28 Mar 2018 02:39:33 PM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
````

A backup is uploading to remote a machine from the Raspberry Pi I have netdata on, and the upload speed is shown as 1Mb/s on the netdata chart:
[netdata system.net chart screenshot](https://framapic.org/N0LZalqD5JYC/vRuqMo0OLKb2.jpg)
This made me jump as the machine is on a very poor adsl connection, that has never uploaded anything faster than about 300kb/s tops.
I ran nethogs and got the following:
````
NetHogs version 0.8.5

    PID USER     PROGRAM     DEV        SENT      RECEIVED
   1466 [user1]     [program1]     eth0      101.429       4.414 KB/sec
    660 [user2]     [program2]     eth0        0.546       0.730 KB/sec
  28309 [user3]     [program3]     eth0        0.070       0.095 KB/sec

  TOTAL                                102.046       5.239 KB/sec
````

So it seems like the netdata chart is reporting 10 times the transfer rate that nethogs is. I will have to trust this one, as it is in line with the "true" upload rate that I am used to observing on this server; what's more, the backup that is uploading is around 1Gb, and if the upload speed was really 1Mb/s it would be over now, and it is still running.
The chart I am refering to in netdata is called "Physical Network Interfaces Aggregated Bandwidth (system.net)" and in this case it is the "sent" graph that is playing up.
I have searched the issue tracker for anything similar but if there is a report of this I must have missed it… Let me know if you need any further information or if I can help debugging this.
Regards,
Mark.

**Comment by ktsaou** [comment]
Hi,

thank you for reporting this.

`system.net` is reporting the total bandwidth of all non-virtual network interfaces. I understand it may be counting something it shouldn't.

Could you please check the network interfaces section of the dashboard?

You can also take a snapshot of the dashboard (press the  ![image](https://user-images.githubusercontent.com/2662304/41111913-12bc8ff8-6a86-11e8-94f9-89d65282654f.png) icon - it will save a file, make a zip with it and attach it this issue).

**Comment by Marcool04** [comment]
Hi and thanks for the fast response.
The network interfaces shows only the eth0 interface (gigabyte ethernet) which is indeed in use. It seems that the "Bandwidth" chart there is also reporting an erroneous value; on the other hand the packet count is correct by the looks of it. The large upload is now finished to the snapshot doesn't show megabyte transfer rates as I was observing earlier.
Here it is:
[netdata-20180607-181440-660.snapshot.zip](https://github.com/firehol/netdata/files/2081266/netdata-20180607-181440-660.snapshot.zip)

**Comment by ktsaou** [comment]
Checking the original post again:

NetHogs says 102.046 KB/s. This means `102.046 KB/s * 8 bits per byte = 816.368 kbit/s`. If NetHogs does not account the whole of it, it can easily be 1Mbit/s.

Are you sure this is wrong?

**Comment by ktsaou** [comment]
btw. I don't see any issues in the snapshot...

**Comment by Marcool04** [comment]
> NetHogs says 102.046 KB/s. This means 102.046 KB/s * 8 bits per byte = 816.368 kbit/s.
Of course that's it! I didn't even think for a second that the units could be different. You're absolutely right, it looked like a factor ten to me but it's a factor of 8 that I'm seeing. Sorry for the time spent chasing a ghost :)
