### ISSUE TITLE
[REQUEST] Add Fleep/webhook notifications

### ISSUE THREAD

**Issue by issak** [firehol/netdata#3792]
Fleep offers integration with webhooks, it takes a simple CURL to the webhook address with "from" and "message" arguments, if would be great if it could be added to Netdata

Fleep webhook api documentation: https://fleep.io/blog/integrations/webhooks/

**Comment by Ferroin** [comment]
@issak  I've just created a PR to support Fleep notifications.  If you could test it and make sure it works, that would help to get it merged (I don't use Fleep myself, so I can't really test it).
