### ISSUE TITLE
How to increase historical data storage to at least a few hours?

### ISSUE THREAD

**Issue by COLABORATI** [firehol/netdata#3795]
Maybe something is wrong with my version of net-data, but I can not see *any* historical data, not even for the last 24 hours - reading your wiki that seems to be a feature? - however, I do not understand how you would not have the idea to at least implement a small scale historical puffer for at least 24 hours - that would help a lot in many situations - I do not know anybody staring at live views of sensor data whole day, that concept makes absolutely no sense at all. Of course you want to have at least a small historical view. 

So hopefully I have overlooked some config value - how would I configure net-data to have at least 24 hours of data available for review? Thanks!

**Comment by Ferroin** [comment]
It's configured via the `history` key in the `[global]` section of the configuration file.  The value is specified in seconds, so for 24 hours you need `history = 86400`.  Note that this will increase memory usage significantly.

**Comment by ktsaou** [comment]
Hi @xinmans . This is an old setting when the memory mode was `save`. Netdata now has `dbengine` that is configured differently and can grow retention way more. Please check this: https://learn.netdata.cloud/docs/agent/database/engine/
