### ISSUE TITLE
which protocol to communicate into master and slaves ?

### ISSUE THREAD

**Issue by mouchref** [firehol/netdata#3802]
question

**Comment by ktsaou** [comment]
it the same used between netdata plugins and the netdata daemon, as described here: https://github.com/firehol/netdata/wiki/External-Plugins#the-output-of-the-plugin

The initial request (slave->master) looks like HTTP, but the method is not `GET` or `POST`, but `STREAM`. After the request is made, the master responds with a predefined response to let the slave know it is netdata, and immediately the slave starts streaming metrics in the plugin format. Once streaming has started, the communication is unidirectional (slave to master, the master never responds).

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but you can still post.
