### ISSUE TITLE
about the tomcat.chart.sh

### ISSUE THREAD

**Issue by gengchong** [firehol/netdata#381]
![issue](https://cloud.githubusercontent.com/assets/3761390/15068854/914c94c2-13ac-11e6-9b53-766af69aeb8d.png)

the tomcat_get function  【curl   -Ss "$tomcat_url"】 modified 【curl -u tomcatUser:tomcatPassword  -Ss "$tomcat_url"】 what do you think?

**Comment by ktsaou** [comment]
Sure.
@jgeromero would you like to do it, or you want me to do it?

**Comment by jgeromero** [comment]
Ok enhancement added in pull request #384 

Thanks.

**Comment by ktsaou** [comment]
this is merged now.
