### ISSUE TITLE
If using unix socket the server do not listen to global socket

### ISSUE THREAD

**Issue by vikrantrathore** [firehol/netdata#3811]
I have following configuration on master node.

```
[global]
        access log = none
        run as user = netdata
        memory mode = save
        web files owner = root
        web files group = root
        # Netdata is not designed to be exposed to potentially hostile
        # networks.See https://github.com/firehol/netdata/issues/164
        bind socket to IP = 127.0.0.1

[web]
        mode = multi-threaded
        bind to = unix:/run/netdata/netdata.sock
```
In this configuration the server will only create unix socket and thebind to ip with socket 19999 does not work. I wanted this to gather stats from slave nodes.

**Comment by ktsaou** [comment]
These two settings are the same. When the second is present the first is ignored (the first was the only setting a few released before).

I suggest to use this:

```
[web]
        bind to = unix:/run/netdata/netdata.sock tcp:127.0.0.1:19999
```

You can add up to 50 different ports.

Also, the `static-threaded` web server is a lot better (actually it prevents memory fragmentation by eliminating ephemeral per-thread memory pools). The `multi-threaded` was the default a few releases back too.

**Comment by ktsaou** [comment]
btw, if you fetch `http://your.netdata.ip:19999/netdata.conf` it will tell you which settings are not actually used.

**Comment by vikrantrathore** [comment]
Thanks for quick help I indeed corrected it. I am closing the ticket.
