### ISSUE TITLE
Can't install netdata on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by shinebayar-g** [firehol/netdata#3827]
I'm trying to install netdata on one of my old servers.

Here is the installation process:

![image](https://user-images.githubusercontent.com/3091558/41427244-e355c9ec-7038-11e8-89f3-707d61a4d7b1.png)

![image](https://user-images.githubusercontent.com/3091558/41427334-260626f6-7039-11e8-8e9a-80df245a9cb8.png)

I even tried to install packages manually as instructed [here](https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system)

`apt-get install zlib1g-dev` result

![image](https://user-images.githubusercontent.com/3091558/41427509-bf223b18-7039-11e8-8d5e-4f4a679a665f.png)

How can i install netdata on this server?

**Comment by shinebayar-g** [comment]
Update: Oh silly silly me. Binary package installation worked for me.

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

**Comment by ktsaou** [comment]
binary packages have their own `bash`, `curl` and `fping`. So, you are set.
