### ISSUE TITLE
ERROR 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by qurname** [firehol/netdata#3834]
Hi! 
I know that similar questions have already been asked, I read them, but I still could not find a solution..
I have this config nginx 

```
upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
    }

server {
   listen 80;
   server_name mysite.com;
   location = /netdata {
        return 301 /netdata/;
   }
   location ~ /netdata/web/(?<ndpath>.*) {
   #location ~ /netdata/web {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        #proxy_pass http://127.0.0.1:19999/$ndpath$is_args$args;
        proxy_pass //netdata/$ndpath$is_args$args;
        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
}
```
I use ssl on site. If i try http://mysite.com:19999 - it's excellent work.
curl and http://mysite.com:19999/api/v1/charts work too.
What am I doing wrong?

**Comment by Ferroin** [comment]
You've got an error in your config:

            proxy_pass //netdata/$ndpath$is_args$args;

should instead be:

            proxy_pass http://netdata/$ndpath$is_args$args;

Since you don't have a protocol specified in the `upstream` block, you need to specify it where you actually reference the upstream server.

**Comment by qurname** [comment]
Thanks, but your comment did not solve the problem.
The answer was in the question =)
I use ssl, but listen on 80 port.
