### ISSUE TITLE
Netdata makes problems when enabled with ffmpeg and Decklink

### ISSUE THREAD

**Issue by mustafalani** [firehol/netdata#3836]
I have netdata installed on Ubuntu servers that run ffmpeg to encode video using Blackmagic Decklink input cards. We have noticed that if Netdata is running, it makes some drop frames in the encoded video stream, the drop frames are replaced with frames of "colour bar" which indicates that the Decklink card isn't encoding at the time when it happens. I can confirm that the servers are capable enough to run multi process and threads of ffmpeg without making any issues, and it only happens when Netdata is running. :(
We like Netdata and would very much like to keep it running.

**Comment by ktsaou** [comment]
Hi,

This is probably something related to what netdata monitors.

Is this a physical server? If yes, I would first disable sensors monitoring. There has been a report in the past that on certain hardware, reading sensors freeze the entire machine for the time the sensors need to be exposed by the hardware. This has nothing to do with netdata - it is more like a hardware/driver/kernel problem.

If you disable sensors and it is not fixed, I would try to disable plugins, until I find the plugin that causes it.

To disable plugins, edit netdata.conf find the `[plugins]` section and disable everything except `proc`. Does it still happen? If it still happens, try to disable individual modules of the `proc` plugin (find the section `[plugin:proc]` in netdata.conf.

So, my suggestion is to try to find the problem. In general, the netdata application is extremely system friendly: it runs unprivileged, entirely in userspace, runs with the `IDLE` process scheduling priority, etc. So, something that netdata uses triggers this in your case.

**Comment by ktsaou** [comment]
btw, if you solve it, please share your experiences - others may need this in the future.

**Comment by mustafalani** [comment]
Hi and thank for the quick answer.
Disabling sensors monitoring didn't help much, so I had to go ahead and disable all plugins except `proc` plugin which have fixed the problem. then I started enabling the plugins one by one to figure out which one is causing the problem.
Apparently, I have more than one plugin causing this issue.
Finally my `[plugins]` section looks like this:
```
[plugins]
        # PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/$
        # PYTHONPATH environment variable =
        # proc = yes
        # diskspace = yes
        cgroups = no
        tc = no
        idlejitter = no
        # enable running new plugins = yes
        # check for new plugins every = 60
        # charts.d = yes
        fping = no
        python.d = no
        apps = no
        node.d = no
```
Thank you again for this great tool.

**Comment by Ferroin** [comment]
If you want to narrow things down a bit further, the python.d plugin lets you enable or disable individual modules in `/etc/netdata/python.d.conf`.  Good candidates there to try disabling (based on personal experience) include the ntpd, postfix, and unbound plugins, all of which tend to show somewhat regular spikes in latency.

**Comment by ktsaou** [comment]
@mustafalani it would be very helpful if you count narrow it a bit further. My intention is to disable by default all plugins that cause problems, so your help will be appreciated.

**Comment by mustafalani** [comment]
Sorry for the very late response, I ended up disabling `python.d = no` plugin only.

**Comment by ktsaou** [comment]
Most probably this is related to sensors monitoring.
Since, you solve it, I am closing this.
