### ISSUE TITLE
kickstart-static64.sh fails with sh as root

### ISSUE THREAD

**Issue by c99ipnerd** [firehol/netdata#3840]
When the ./kickstart-static64.sh is started with sh as root (debian 9), the ${UID} is not set and the check for sudo fails.

It works when the check as in the kickstart.sh script is added on the beginning.
`[ -z "${UID}" ] && UID="$(id -u)"`

**Comment by ktsaou** [comment]
Thank you for reporting this.
Fixed with PR #3863

**Comment by ktsaou** [comment]
Installed the updated at `my-netdata.io` too.
So, please check it now and report success or failure.
Thank you!
