### ISSUE TITLE
Mongodb with ssl/keyfile does not work

### ISSUE THREAD

**Issue by 0xicl33n** [firehol/netdata#3846]
Connecting to a server with keyfile encryption causes it to close immediately
```
netdata@spyke2:/etc/netdata/python.d$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mongodb
2018-06-19 19:15:57: python.d INFO: plugin: main: Using python 2
2018-06-19 19:15:58: python.d DEBUG: plugin: main: module load source: 'mongodb' => [OK]
2018-06-19 19:15:58: python.d DEBUG: plugin: main: module load config: 'mongodb' => [OK]
2018-06-19 19:15:58: python.d DEBUG: plugin: main: job initialization: 'mongodb scalegrid' => ['OK']
2018-06-19 19:15:58: python.d DEBUG: plugin: main: module status: 'mongodb' => [OK] (jobs: 1)
2018-06-19 19:15:58: python.d ERROR: mongodb: scalegrid: connection closed
2018-06-19 19:15:58: python.d INFO: mongodb: scalegrid: check() => [FAILED]
2018-06-19 19:15:59: python.d INFO: plugin: main: FINISHED
```

`pymongo` [supports SSL and keyfile encrytion](http://api.mongodb.com/python/current/examples/tls.html), but netdata does not. It can be completely transparent of the actual netdata application since it is just a plugin. I will look into adding support for it. The conf file could look like this:

**mongodb.conf:**
```
example:
    name : 'example'
    host : 127.0.0.1
    port : 45801
    user : 'user'
    password : 'password' 
    ssl : 'yes'
    keyfile : '/home/netdata/db.pem'

```

The other option is to  allow us to connect with [mongodb connect strings](https://docs.mongodb.com/manual/reference/connection-string/). [Motor ](http://motor.readthedocs.io/en/stable/)would actually be a much better alternative to pymongo as well since they both have the same syntax

**Comment by Ferroin** [comment]
The relevant plugin code can be found [here](https://github.com/firehol/netdata/blob/master/python.d/mongodb.chart.py).

**Comment by Ferroin** [comment]
Also, if you make any changes to the config format, don't forget to update the config file [here](https://github.com/firehol/netdata/blob/master/conf.d/python.d/mongodb.conf) and the readme info [here](https://github.com/firehol/netdata/blob/master/python.d/README.md) to reflect the changes.

**Comment by 0xicl33n** [comment]
```
diff --git a/python.d/mongodb.chart.py b/python.d/mongodb.chart.py
index e81bed84..ef6471d0 100644
--- a/python.d/mongodb.chart.py
+++ b/python.d/mongodb.chart.py
@@ -376,6 +376,7 @@ class Service(SimpleService):
         self.password = self.configuration.get('pass')
         self.host = self.configuration.get('host', '127.0.0.1')
         self.port = self.configuration.get('port', 27017)
+        self.uri = self.configuration.get('uri')
         self.timeout = self.configuration.get('timeout', 100)
         self.metrics_to_collect = deepcopy(DEFAULT_METRICS)
         self.connection = None
@@ -649,7 +650,13 @@ class Service(SimpleService):
 
     def _create_connection(self):
         conn_vars = {'host': self.host, 'port': self.port}
-        if hasattr(MongoClient, 'server_selection_timeout'):
+        if self.uri:
+            try:
+                connection = MongoClient(self.uri)
+                server_status = connection.admin.command('serverStatus')
+            except PyMongoError as error:
+                return None, None, str(error)

```
it actually should be that easy @Ferroin

**Comment by Ferroin** [comment]
Feel free to submit a PR.  Given how simple it is, I doubt it will be much issue to get it merged (especially since it leaves the old interface intact, so it won't break existing installs).

**Comment by fmercier-almerys** [comment]
Hi and if you need to connect to mongo with double authent (client cert validation and ssl server communication) is your patch working ?
To trust replicaSet cert I am use to trust the ROOT CA into OS , mongodb client works well in this way .
