### ISSUE TITLE
How to monitor dovecot in container ?

### ISSUE THREAD

**Issue by petarkozic** [firehol/netdata#3850]
Hi,

I'm using mailcow-dockerized mail server. All services on that server was in container. 
On host machine I have installed netdata.

How can I monitor services in container, more precisely I need stat for dovecot.
In that container I see process and socket but how to monitor that.
Is that possible or I need to do something more, like link some socket or process to host machine.

Thanks !

**Comment by ktsaou** [comment]
Have you tried to configure netdata to talk to it by adapting this file: https://github.com/firehol/netdata/blob/master/conf.d/python.d/dovecot.conf (you have it as `/etc/netdata/python.d/dovecot.conf`).

**Comment by petarkozic** [comment]
I can't becuase all dovecot works into containaer I don't know how to connect netdata dovecot.conf with dovecot socket into container.
If netdata don't have that ability, I can only try to expose dovecot stat port onto host.

**Comment by ktsaou** [comment]
Well, you have to expose the dovecot socket to the host somehow. Generally docker has this capability, but I don't have the command line options handy.

Otherwise, you will have to expose the port of dovecot to the host, like you said.

**Comment by petarkozic** [comment]
Sure, thank you. I'm resolved this. Here is need to enable dovecot stats to listen on example default port and than that port must to be exposed to host. After that netdata scrape statistics like a charm.
