### ISSUE TITLE
Check if slave is down

### ISSUE THREAD

**Issue by xikaos** [firehol/netdata#3856]
Hello guys!

I'm having a good time with netdata since it is very well documented.

Although I do not found some sort of "standard" alarm to notify me when a slave is down.

Any ideas on how to do that?

I thought about triggering it when CPU average is at 0, but that may be very prone to errors.

Thanks in advance.

**Comment by xikaos** [comment]
Hi Costa!

Sorry for the late response.

I tried to configure the alert putting it under the health.d directory in my slaves, without success.

The alarm doesn't show in the dashboard and also doesn't trigger notifications.

Do I need to do something else to activate it?

Let me know if you need more info about my environment!

Thank you very much!

**Comment by ccremer** [comment]
Try putting the config on the master. Obviously the slave won't be able to alert it it's down ;)

**Comment by xikaos** [comment]
@ccremer You nailed it, lol. I've put on the master health.d directory and it worked after a restart.

I've created a public gist so people can find it searching on Google. 

https://gist.github.com/xikaos/40062e4dced73f9b8fb7e724383c7cf2

Thanks for the answer!
