### ISSUE TITLE
Finding the Source of Metrics from Dashboard

### ISSUE THREAD

**Issue by nitanka** [firehol/netdata#3867]
I have setup Master Slave deployment of `Netdata`, where the Netdata agents installed on the servers will send the data to the Master node.
On the Dashboard of Master Node, I am checking the metrics of all the nodes. 

But for some reason, one of the agent was not reporting the metrics as expected, so I have uninstalled it, but the dashboard is still showing the Metrics. 

To debug the whole scenario, I want to know from which server (IP) the metrics are coming from.

**Comment by ktsaou** [comment]
Hi, check `/var/log/netdata/error.log`. grep the server name.

**Comment by ktsaou** [comment]
You can also find all clients streaming with access.log:

```sh
grep STREAM /var/log/netdata/access.log
```

**Comment by nitanka** [comment]
Thank you!
