### ISSUE TITLE
%d & %lu format strings given incorrect data types

### ISSUE THREAD

**Issue by davidsilveiro** [firehol/netdata#387]
Love the tool!

**Variable i  - requires signed
src/sys-fs_cgroup.c:1012
src/sys-fs_cgroup.c:1019**

**Variable oincrement - requires unsigned
src/unit_test.c:763**

**Comment by ktsaou** [comment]
Thanks!
I can't believe how many such cases there were. Check this: https://github.com/firehol/netdata/pull/565/files

Fixed all of them.
