### ISSUE TITLE
Application not showing up in dashboards

### ISSUE THREAD

**Issue by willkara** [firehol/netdata#388]
So I'm trying to add Plex Media Server.

Took a look [here ](https://github.com/firehol/netdata/issues/234)and it didn't work.

Here's the output of ps -ef | grep plex:

http://pastie.org/private/2udutelyjdw8aye467nz7a

And here's what I've tired already in the .conf file

PlexServer: "Plex Media Serv"
PlexTranscode: "*Plex New Transcoder*"

My guess is that defining the process name incorrectly?

**Comment by ktsaou** [comment]
Can you give me this:

```sh
ps -e | grep -i plex
```

**Comment by willkara** [comment]
Looks like it's working now! I guess it just needed a full system restart :)

Thanks for making a seriously amazing product. We're currently using it to make a dashboard for our servers at work.

**Comment by ktsaou** [comment]
Thanks!
Can you give me the exact entries you used? I'll add them by default so that everyone will benefit...

**Comment by willkara** [comment]
Sorry, just saw this message. Will comment with my entries so that everyone else can use them.

**Comment by ktsaou** [comment]
Cleaning up. appl.plugin has a better config now that allows it even to search for substrings in the command line run in all processes.
