### ISSUE TITLE
Json format

### ISSUE THREAD

**Issue by DrGkill** [firehol/netdata#389]
The result returned as json is malformed. It works for retreiving with javascript but it's an invalid json format.

curl 'http://127.0.0.1:19999/api/v1/data?chart=apps.cpu&format=json&points=2'
```
{
        "labels": ["time", "other", "lxc", "ksmd", "system", "netdata", "kernel", "cron", "inetd", "log", "ssh", "apache"],
        "data":
        [
                [ new Date(2016,4,8,15,29,24), 0.77299, 0, 0, 1.54549, 4.09126, 1.54464, 2.31824, 0, 0, 3.09192, 0.77335]
        ]
}
```
`new Date` is not a valid json string, and shoud be something like `"new Date(2016,4,8,15,29,24)"`

**Comment by simonnagl** [comment]
You are right. This is already marked as a bug in #83.

Thank you for reporting anyways. If you want to contribute just open a pull request.

**Comment by DrGkill** [comment]
Ok thanks, i'll use `&options=seconds` for now.

**Comment by ktsaou** [comment]
I close this, we have #83 to discuss the issue.
