### ISSUE TITLE
Running netdata without root permissions

### ISSUE THREAD

**Issue by samayres1992** [firehol/netdata#390]
Currently for netdata to work I have to run ```sudo /usr/sbin/netdata```

```
16-05-08 11:15:01: ERROR: netdata: Failed to convert IP '127.0.0.1' to a valid IPv6 address. Disabling IPv6.
16-05-08 11:15:01: INFO: netdata: Listening on IP '127.0.0.1' (IPv4).
16-05-08 11:15:01: INFO: netdata: Managed to open an IPv4 socket on port 19999.
```

The error seems to be expected according to #164, which is fine.

But when I run netdata without root ```/usr/sbin/netdata```

```

sam@snowflake:/opt/letsencrypt$ /usr/sbin/netdata
16-05-08 11:10:37: ERROR: netdata: Failed to convert IP '127.0.0.1' to a valid IPv6 address. Disabling IPv6.
16-05-08 11:10:37: INFO: netdata: Listening on IP '127.0.0.1' (IPv4).
16-05-08 11:10:37: INFO: netdata: Managed to open an IPv4 socket on port 19999.
16-05-08 11:10:37: ERROR: netdata: Cannot open error log file '/var/log/netdata/error.log'. (errno 13, Permission denied)
16-05-08 11:10:37: FATAL: netdata: Cannot demonize myself. # : Success

```

I can't start netdata, is there anyway I can fix this?  It's clearly a permission issue but unsure what I need to change.  I've given netdata the ownership of the folder, so it should be able to access what it needs to run. 

Thanks for any help you give!

**Comment by ktsaou** [comment]
What are the permissions of `/var/log/netdata`.

**Comment by samayres1992** [comment]
@ktsaou I've given it 775, it works with 777 but as far as I'm aware that's not really the best way to resolve an issue. 

Is this solely due to netdata being unable to access a log file?

**Comment by ktsaou** [comment]
yes. Check the directory `/var/log/netdata` permissions too.

**Comment by ktsaou** [comment]
The installer will also install it as as a normal user, with the parameter `--install /tmp`.

**Comment by con-f-use** [comment]
In lieu of a better place to ask. How would I go about to build a user-space **static** version of netdata? Is there something like `./netdata-1.9.0-31_x86_64.gz.run --target /tmp/ --static`?

**Comment by ktsaou** [comment]
@con-f-use unfortunately this is not supported. You can do it, but you will need to configure all directories by hand.

It is probably simpler to install from source. That installer supports building netdata without any root access.

**Comment by con-f-use** [comment]
I have done that and it was easier than expected. Thank you for taking the time to answer.
