### ISSUE TITLE
require option to monitor multiple nginx remote server logs using web_log

### ISSUE THREAD

**Issue by gsmtamil** [firehol/netdata#3919]
i have more than 6 nginx server i need to monitor all the server logs using netdata web_log which is installed in some other instance.

**Comment by ktsaou** [comment]
3 options:

1. install netdata on all your servers
2. use syslog to move the log files to central server and install netdata there
3. share the path of the logs using NFS to a central server and install netdata there

The easiest is to install netdata everywhere. This is how it has been designed to work...

**Comment by gsmtamil** [comment]
Thanks for your support, I have installed netdata to all the servers and I have been using stream option to collect all data into one server.
