### ISSUE TITLE
Nut command upsc failed

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#3920]
I have two UPSs set up to monitor with NUT. Several times a day I am getting health alerts for one of them. Sometimes it is 30 minutes between alerts, sometimes it is half a day. Looking a the log files, I see: 
```
charts.d: : nut: command 'upsc NAME@FQDN ' failed:
```
This is only for one of the two UPSs, and I haven't seen anything in my NUT server's log files. It seems the command is only failing once, as the charts show the stats going back to nominal almost immediately after dropping to zero. Is there any way to get more detailed logging for why this command keeps failing?

**Comment by ktsaou** [comment]
Just below that line you should have a block like this:

```
 --- BEGIN TRACE ---

<< log of the failed command here >>

 --- END TRACE ---
```

So, use `less` to view the log.

**Comment by kmlucy** [comment]
Ah, thanks. I was just searching through the logs. Unfortunately, the trace is empty:
```
--- BEGIN TRACE ---
--- END TRACE ---
```

**Comment by ktsaou** [comment]
So, it failed without logging anything... I added logging of the return code.

I see that the plugin runs `nut` with a timeout: https://github.com/firehol/netdata/blob/ec0d897da8e8a25457156fe8a855f20d142bddfc/charts.d/nut.chart.sh#L30

The default timeout is 2 seconds: https://github.com/firehol/netdata/blob/ec0d897da8e8a25457156fe8a855f20d142bddfc/charts.d/nut.chart.sh#L17

You can set that variable in `nut.conf` to increase it: https://github.com/firehol/netdata/blob/ec0d897da8e8a25457156fe8a855f20d142bddfc/conf.d/charts.d/nut.conf#L18

On my tests, `timeout` returns with code 124 when a timeout occurs:

```sh
# timeout 2 sleep 10; echo $?
124
```

Run the above yourself (there are many versions of the `timeout` command, so the code may be different). If you see that code logged (after you update your netdata, to have this logged), the `nut` command times out...

**Comment by kmlucy** [comment]
Of course, now that I needed it to error, it took two days to happen. It is a timeout issue, so I've increased the timeout and will go from there.

**Comment by kmlucy** [comment]
I have increased the timeout to 9 seconds, and haven't had any problems for a week or so. I bumped it up 1-2 seconds at a time until I got to 9.
