### ISSUE TITLE
Master Netdata as Subfolder on Nginx

### ISSUE THREAD

**Issue by scolby33** [firehol/netdata#3933]
Is it possible to stream from a slave to a master netdata behind an Nginx config like shown in the wiki?

```
upstream netdata {
    server unix:/tmp/netdata.sock;
    keepalive 64;
}

server {
   listen 80;

   # the virtual host name of this subfolder should be exposed
   #server_name netdata.example.com;

   location = /netdata {
        return 301 /netdata/;
   }

   location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
}
```

**Comment by ktsaou** [comment]
Hi,

the streaming protocol is not HTTP, so nginx will not understand it.
A simple solution is to also allow port 19999 (or any other - netdata supports many) public and use netdata access lists to allow only your slaves to connect.

So, you could use something like (in netdata.conf):

```
[web]
  bind to = 0.0.0.0:19999
  allow connections from = localhost 10.* 192.168.* 172.16.*
```

So, it will allow connections from `localhost` (your nginx) and the private IPs of the slaves you allow.
All other connections to port 19999 will be disconnected immediately (without receiving the request).

**Comment by scolby33** [comment]
Makes sense, I knew it was a bit of a long shot. My nodes are at multiple sites, but I ended up putting them all on a VPN and allowing the streaming data into the master that way.
