### ISSUE TITLE
completely turn off public and own registry

### ISSUE THREAD

**Issue by toastbrotch** [firehol/netdata#3937]
how do i turn off the usage of registry.my-netdata.io without having my own registry?
seems not documented here: https://github.com/firehol/netdata/wiki/mynetdata-menu-item

even with 
```
[registry]
enabled = no
registry to announce = 
```
i see http requests going there and the links in the mails point there too.

is there a way to run netdata
- without own registry
- without communicating via registry.my-netdata.io
- with mails that link to the real url of netdata, not registry.my-netdata.io

thanx for your help. 
everything else is super cool (so far), but i just don't like phone-home stuff at all.
(besides that, the public registry might be also illegal in the EU under GDPR, as users are identifiable and share personal attributes (ip) with the public registry without knowing or explicit opt-in or accepting any privacy declaration, ... i would not enable this by default)

**Comment by toastbrotch** [comment]
i've seen discussion here https://github.com/firehol/netdata/issues/2760 

the workaround setting the registry to announce to the "public" url works only so far that the web-ui does not phone home anymore. in emails i get the correct link but redirecting does not work: 
"Sorry... your account is not linked to a netdata server named: bla.internal"

ah right, of course we have it behind a reverseproxy...

**Comment by ktsaou** [comment]
Did you manage to setup your own registry?

The public registry is not a "phone home". It is a free service we offer. I have responded in detail in https://github.com/firehol/netdata/issues/2760#issuecomment-403178620 - for GDPR too.

So, I am closing this as duplicate, but you can still post if you have problems setting up your own registry.

**Comment by ktsaou** [comment]
I am sorry, I won't.
netdata requires a registry.

For how long do you use netdata? Have you tried to troubleshoot a distributed performance issue with netdata?

Please, try these a few times. If you can work without a registry, I'll open it. But please share a video of what you did and how you worked, without using the my-netdata menu.

**Comment by Ferroin** [comment]
@ktsaou Not everyone _needs_ the my-netdata menu.  It's helpful for some use cases, but not much for others (case-in-point, the my-netdata entries for my personal systems don't technically work for any of them but the internet routable ones, so there's no point in me even trying to use it).  The links in notifications fall into the same category (I never use them myself, but then I also know which system it is (and half the time, usually what's wrong) just by the email titles).

Beyond that, there's nothing in Netdata that actually depends on the registry as far as I can tell, except for the stuff that calls out to it.  Being able to disable those callouts if you know you don't need any of the features which depend on the registry would be really useful for some people, so they don't have to block them in the local firewall to avoid wasting network bandwidth.

**Comment by ktsaou** [comment]
Let's continue this discussion at #3990
