### ISSUE TITLE
Unable to proxy Netdata :19999 to /netdata nginx

### ISSUE THREAD

**Issue by Macley-Kun** [firehol/netdata#3945]
I'm trying to run Netdata on /netdata instead of :19999 using nginx. But for some reason it's not working.

### Location of configuration
`/etc/nginx/conf.d/default.conf`

### Configuration
https://hastebin.com/uqamoweput.nginx

### Netdata working on port 19999
http://64.190.91.66:19999

### nginx working on port 80
http://64.190.91.66

### Netdata not working on /netdata
http://64.190.91.66/netdata

I hope someone sees what i'm missing here, i would love to host netdata proper on my site!

**Comment by Macley-Kun** [comment]
@l2isbad where did you put this configuration?

**Comment by l2isbad** [comment]
In my case it in `/etc/nginx/sites-enabled/default`

**Comment by l2isbad** [comment]
You need to remove `/netdata` part from request. This is what rewrite rule does.

**Comment by Macley-Kun** [comment]
Thank you so much! It's working!

When i added it in the requrest file, i placed it inside the `server {` and then added your exact config!

Thank you so much for helping!!
