### ISSUE TITLE
netdata uses 100% CPU when trying to access netdata dashboard

### ISSUE THREAD

**Issue by nathan-liyiming** [firehol/netdata#3957]
I have one master machine to store data (5GB) from 50+ slaves. When I try to curl localhost:19999 or access the dashboard in the master box, it is super slow and suddenly CPU goes to 100%. After I run `systemctl restart netdata`, the CPU goes back to normal. But, once I access dashboard, the CPU always goes to 100% and can't open dashboard.

In the master, memory mode is `map`. In the slave, I set `update every = 30`. Do I miss any config setting? BTW, when I had only about 10 slaves, it worked well.

**Comment by ktsaou** [comment]
Which version of netdata? Is it the current git version? (there was a bug with an infinite loop at the streaming code in an older version).

If it is the current version, could you please edit `stream.conf` and set `multiple connections = deny`? This will deny multiple connections from the same host. If 2 or more netdata share the same unique id, things can go crazy. This setting makes sure that each netdata unique id, is allowed just once to stream metrics.

**Comment by nathan-liyiming** [comment]
Thanks for this quick response. I use the current version from git. I try your solution, it doesn't work well: when I set `multiple connections = deny`, I can't read any metrics from dashboard. (more context: I use `[API_KEY] section` to set up master and slave).

Finally, the issue is that there is the limitation for file descriptors and the number of memory map. After changing them to the big values, it solves the problem and CPU goes down to normal. What I did is as follows:

1. `echo 1000000 > /proc/sys/fs/file-max` (`lsop -p NETDATA_PID | wc -l` shows `276460` for 100+ slaves)
2. `echo 2000000 /proc/sys/vm/max_map_count` (`pmap NETDATA_PID | wc -l` shows `276501` for 100+ slaves)

This is one hacky way. Do you have any suggestions to improve it? Thanks for your help!

**Comment by ktsaou** [comment]
You are right. File descriptors! Of course!

I think the right way to change this is via systemd. Edit /etc/netdata/systemd/netdata.service and set:

```
LimitNOFILE=10000
```

To set max map count use `/etc/sysctl.conf`. This is system wide.
