### ISSUE TITLE
Use newer packaging systems like flatpak, appimage or snap

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#3964]
Due to the complexity of a project and the fact that it couldn't be successfully integrated into distribution repositories, maybe it is time to consider using newer system of packaging application like [flatpak](https://flatpak.org), [appimage](https://appimage.org) or [snap](https://snapcraft.io). They are by nature cross compatible with most linux distros (including IoT ones) as conceptually they are closer to docker containers than to "standard" packaging.

This could potentially change our default installation method from a script to an actual package.

However since those packaging systems are similar to docker containers, they are also run in a sandboxed mode which could potentially cause problems.

**Comment by paulfantom** [comment]
This should also simplify support for "it does not work on my machine" issues as the default installation method would produce identical package across all systems.

After introducing flatpak/snap we should keep an installation with script, but as a fallback method.

@ktsaou wdyt?

**Comment by ktsaou** [comment]
Snap devs did a PR but it is now leftover: #1991

flatpack seems like a desktop solution. I don't have any experience with it.

appimage seems like a smarter `makeself`. Instead of installing it, it mounts the image and runs the application.

> This should also simplify support for "it does not work on my machine" issues as the default installation method would produce identical package across all systems.

I think this is solved with the static netdata package (`makeself` based). This is how we now install netdata on CoreOS and systems without or with a broken package management.

**Comment by paulfantom** [comment]
I think those 3 packaging systems were degined primarily for desktop usage. Basically the main trend is to use containers on servers and maybe one of those (flatpak/snap/appimage) on desktop machine. However that doesn't mean that they cannot be used on servers or low-power IoT devices (snap is a good example of this).

Personally I think there is a need for a simplified installation method with a simple update schema. It would be good to have pre-built binaries, so provisioning netdata to 10s or 100s of hosts would be simpler and quicker. Also lack of compilation tools on target system should increase system security by reducing attack surface (less software - less entrypoints).


> This is how we now install netdata on CoreOS

We shouldn't advice users to use `makeself` installation method on system which was built specially for containerized applications. Especially since there is a netdata docker container.

**Comment by paulfantom** [comment]
This was a bad idea. I am focusing my time on deb/rpm packages located at packagecloud.io.
