### ISSUE TITLE
How could I disable some metrics that are special for machines?

### ISSUE THREAD

**Issue by nathan-liyiming** [firehol/netdata#3965]
I have deployed netdata to more than 100 machines. There is one machine as master to store them. However, I find some metrics aren't useful for me and I want to disable them in order to save disk space (`enabled = no` is only for the metric with the fixed name). For examples, there are `cpu.cpu0`, `disk_await.xvdb`, `disk_space._run` etc. These metrics are generated depending on the num of cpus or the info of disk volumes. Do we have any way to disable them? I hope to have one configuration file (`netdata.conf`) for all the slaves to only collect the data that I need. Thanks!

**Comment by nathan-liyiming** [comment]
nvm, I find it, maybe it is easy to let users enable the metrics what they need.

**Comment by guanghui1987** [comment]
> I have deployed netdata to more than 100 machines. There is one machine as master to store them. However, I find some metrics aren't useful for me and I want to disable them in order to save disk space (`enabled = no` is only for the metric with the fixed name). For examples, there are `cpu.cpu0`, `disk_await.xvdb`, `disk_space._run` etc. These metrics are generated depending on the num of cpus or the info of disk volumes. Do we have any way to disable them? I hope to have one configuration file (`netdata.conf`) for all the slaves to only collect the data that I need. Thanks!



> nvm, I find it, maybe it is easy to let users enable the metrics what they need.

Hello, guys! Can you share your solution for more details.
Thank you!

**Comment by ilyam8** [comment]
There is an option in `stream.conf` to filter metrics to be streamed

```
    # filter the charts to be streamed
    # netdata SIMPLE PATTERN:
    # - space separated list of patterns (use \ to include spaces in patterns)
    # - use * as wildcard, any number of times within each pattern
    # - prefix a pattern with ! for a negative match (ie not stream the charts it matches)
    # - the order of patterns is important (left to right)
    # To send all except a few, use: !this !that *   (ie append a wildcard pattern)
    send charts matching = *
```
