### ISSUE TITLE
netdata doesn't load graphs from disk

### ISSUE THREAD

**Issue by roedie** [firehol/netdata#3984]
Hi,

I'm running netdata 1.10.0 with a central server. But when I restart the central server I lose all history.

I use 'memory mode = save' in netdata.conf and I can see it updates all the salve node databases on disk.

When netdata is started again I can scroll back in the graph history of the central netdata server itself but not of the nodes which write their data to this central server. How can I make sure slave data survives a restart of the master server?

Sander

**Comment by l2isbad** [comment]
Hi @roedie 
https://github.com/firehol/netdata/blob/master/conf.d/stream.conf#L93-L101

**Comment by roedie** [comment]
Even when I use memory = map the graphs do not load at restart.

**Comment by roedie** [comment]
Right, after staring at the problem for multiple days, I've found it. Sorry about this one.
