### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by simonnagl** [firehol/netdata#399]
I do not like how command line options are defined.

1. They do not stick to any standard I know.
    - [IEEE Std 1003.1, 2013 Edition](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)
    - [GNU Coding Standard](http://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces)
2. `-df` and `-nd` and `-ch` are irritating. They are no long options with describing naming, nor short options. The standards I know would treat such strings as two options.
3. usage string does not contain every option listed below.

- I would like to change configuration options matching to one of the standards above. I would prefer IEEE, GNU is fine to if you prefer it.

- I would like to add -h (help) and -v (version).

- I would like to implement better to maintain configuration options. That means having
    - an array of struct which contain option, (evtl. longopt), optarg, description, ...)
    - a switch to add the handling of options
    - auto-generated help message

What do you think?

**Comment by ktsaou** [comment]
I agree.
Try to emulate the existing options though, or a lot of people will have to change their startup scripts...

**Comment by simonnagl** [comment]
Of course. I will provide a patch in the next days.
