### ISSUE TITLE
nms: new process and high cpu consumption peaks every 5 minutes

### ISSUE THREAD

**Issue by alexara** [firehol/netdata#4005]
Hello,

I recently installed `netdata v1.10.0` on `Debian 9` and observerd that an application group, which netdata calls `nms`, spawns every 5 minutes, as seen in the screenshots:

![nms](https://user-images.githubusercontent.com/13819719/43154737-b8be54cc-8f75-11e8-9eff-2a0d3c7a1c30.png)
![nms2](https://user-images.githubusercontent.com/13819719/43154738-b8e5e9f6-8f75-11e8-92e4-ac3263c788bd.png)

Since `nms` belongs to netdata: https://github.com/firehol/netdata/blob/80eb352145de2074489d0f173297528c5f5be3ad/conf.d/apps_groups.conf#L142
is that behavior expected and normal or is something running faulty on my system?

**Comment by Ferroin** [comment]
First off, `apps_groups.conf` is just a mapping of application names to the groups that netdata reports them under.  Netdata itself doesn't start any of these (well, technically doesn't, the first set of application groups defined near the top of the file is stuff that netdata starts, but this file does not configure that).

Now, as for the main part of your question.  `nms` is short for something along the lines of `network monitors'.  Everything in that group is a network monitoring tool.  The names listed there _should_ correspond to the debian packages providing each program.  Most likely, one of them is configured to check something (or lots of things) at a 5 minute interval on your system, and that is what's causing the spikes.

**Comment by alexara** [comment]
> Most likely, one of them is configured to check something (or lots of things) at a 5 minute interval on your system, and that is what's causing the spikes.

That appears sensible to me. I am going to investigate it. 
So from that point of view `netdata` already gave me some new insight into my system. :)

Thanks.

**Comment by alexara** [comment]
I could solve it: The spikes belong to the `munin-update` process.

See http://munin-monitoring.org/wiki/faq 
> Munin runs at an interval of every five minutes (*/5) on debian systems by default.

**Comment by Ferroin** [comment]
Glad you were able to find it, and also that netdata was able to help you learn more about your system!
