### ISSUE TITLE
Errors caused by listening on both IPv4 and IPv6

### ISSUE THREAD

**Issue by Lusbert** [firehol/netdata#402]
I ran netdata on my debian Jessie with the default options and saw this messages:
 
```
16-05-12 11:41:32: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
16-05-12 11:41:32: ERROR: netdata: IPv6 bind() failed. Disabling IPv6. (errno 98, Address already in use)
16-05-12 11:41:32: INFO: netdata: Listening on any IPs (IPv4).
16-05-12 11:41:32: ERROR: netdata: IPv4 bind() failed. (errno 98, Address already in use)
16-05-12 11:41:32: FATAL: netdata: Cannot listen socket. # : Success
```
Then, I set listen only on IPv4 in the config file, restarted  netdata and fixed them.

**Comment by ktsaou** [comment]
Hi, it is already started (the installer starts it too), or something else is listening on port 19999.
Can you verify it is not already running?

**Comment by Lusbert** [comment]
Hi, there is nothing listening on that port previously. I set both IPv4 and IPv6 again and its working now with IPv4, but it appears that is only listening on IPv6. 

```
root@debian:/data/nfs# ss -ltn4 |grep 19999
root@debian:/data/nfs# ss -ltn6 |grep 19999
LISTEN     0      100                      :::19999                   :::*     

```
So, do you mean netdata starts after the install?

Thanks!

**Comment by ktsaou** [comment]
> So, do you mean netdata starts after the install?

Yes, the installer starts it by default.
