### ISSUE TITLE
Badges - seconds units

### ISSUE THREAD

**Issue by sereeds** [firehol/netdata#4029]
I really appreciate the way the the badges scale up the seconds units to hours, days, etc.  That is some very excellent work on the badges.

However, when the value is zero, it displays "never".  Some people seem to go into a panic frenzy when they see that word "never".  Can we please have a configurable option to change that to just "0 s" or something appropriate.

Thank you.

**Comment by ktsaou** [comment]
I see in the code: https://github.com/firehol/netdata/blob/002023173ec1aab38d79257c07ec94e008b61dc5/src/web_buffer_svg.c#L507-L514

it shows `now` when it is zero and `never` when it is undefined.

I guess we should change `never` to `undefined`. Right?

**Comment by sereeds** [comment]
OR maybe `null `?

**Comment by ktsaou** [comment]
it is now merged

**Comment by sereeds** [comment]
Didn't want to go with `zilch` or `nada` ?

Just joking around, `undefined` is good.
Thanks for making the change, you're the best.
