### ISSUE TITLE
problem enabled mysql

### ISSUE THREAD

**Issue by d1mf** [firehol/netdata#4032]
Hello. I have centOS7 and MariaDB 10.

How enable MySQL? This log

 connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 00:07:31: charts.d: ERROR: mysql: no mysql servers found. Please set mysql_opts[name]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 00:07:31: charts.d: ERROR: mysql: module's 'mysql' check() function reports failure.
2018-08-06 00:07:31: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
  in "/opt/netdata/etc/netdata/python.d/mysql.conf", line 130, column 1
2018-08-06 00:07:31: python.d ERROR: mysql: mysql: Connection properties are missing
2018-08-06 00:07:31: python.d INFO: mysql: mysql: check() => [FAILED]
2018-08-06 00:08:36: charts.d: : mysql: command '/usr/bin/mysql -h localhost -N -e SHOW\ GLOBAL\ STATUS\; ' failed with code 1:
2018-08-06 00:08:36: charts.d: ERROR: mysql: cannot get global status for 'local'. Please set mysql_opts[local]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 00:08:36: charts.d: ERROR: mysql: no mysql servers found. Please set mysql_opts[name]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 00:08:36: charts.d: ERROR: mysql: module's 'mysql' check() function reports failure.
2018-08-06 00:08:36: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
  in "/opt/netdata/etc/netdata/python.d/mysql.conf", line 130, column 1
2018-08-06 00:08:36: python.d ERROR: mysql: mysql: Connection properties are missing
2018-08-06 00:08:36: python.d INFO: mysql: mysql: check() => [FAILED]

**Comment by d1mf** [comment]
This default config. I comment  few lines.


# netdata python.d.plugin configuration for mysql
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - global variables
#  - one or more JOBS
#
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# JOB parameters have to be indented (using spaces only, example below).

# ----------------------------------------------------------------------
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.

# update_every sets the default data collection frequency.
# If unset, the python.d.plugin default is used.
# update_every: 1

# priority controls the order of charts at the netdata dashboard.
# Lower numbers move the charts towards the top of the page.
# If unset, the default for python.d.plugin is used.
# priority: 60000

# retries sets the number of retries to be made in case of failures.
# If unset, the default for python.d.plugin is used.
# Attempts to restore the service are made once every update_every
# and only if the module has collected values in the past.
# retries: 60

# autodetection_retry sets the job re-check interval in seconds.
# The job is not deleted if check fails.
# Attempts to start the job are made once every autodetection_retry.
# This feature is disabled by default.
 autodetection_retry: 5

# ----------------------------------------------------------------------
# JOBS (data collection sources)
#
# The default JOBS share the same *name*. JOBS with the same name
# are mutually exclusive. Only one of them will be allowed running at
# any time. This allows autodetection to try several alternatives and
# pick the one that works.
#
# Any number of jobs is supported.
#
# All python.d.plugin JOBS (for all its modules) support a set of
# predefined parameters. These are:
#
# job_name:
#     name: myname            # the JOB's name as it will appear at the
#                             # dashboard (by default is the job_name)
#                             # JOBs sharing a name are mutually exclusive
#     update_every: 1         # the JOB's data collection frequency
#     priority: 60000         # the JOB's order on the dashboard
#     retries: 60             # the JOB's number of restoration attempts
#     autodetection_retry: 0  # the JOB's re-check interval in seconds
#
# Additionally to the above, mysql also supports the following:
#
#     socket: 'path/to/mysql.sock'
#
#  or
     #host: localhost # the host to connect to
#     port: PORT             # the port to connect to
#
#  in all cases, the following can also be set:
#
    # user: root       # the mysql username to use
#     pass: 'password'       # the mysql password to use
#

# ----------------------------------------------------------------------
# mySQL CONFIGURATION
#
# netdata does not need any privilege - only the ability to connect
# to the mysql server (netdata will not be able to see any data).
#
# Execute these commands to give the local user 'netdata' the ability
# to connect to the mysql server on localhost, without a password:
#
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost';
# > flush privileges;
#
# with the above statements, netdata will be able to gather mysql
# statistics, without the ability to see or alter any data or affect
# mysql operation in any way. No change is required below.
#
# If you need to monitor mysql replication too, use this instead:
#
# > create user 'netdata'@'localhost';
# > grant replication client on *.* to 'netdata'@'localhost';
# > flush privileges;
#

# ----------------------------------------------------------------------
# AUTO-DETECTION JOBS
# only one of them will run (they have the same name)

#mycnf:
 # name     : 'mysql local'
 # 'my.cnf' : '/etc/my.cnf'

#mycnf2:
 # name     : 'local'
 # 'my.cnf' : '/etc/mysql/my.cnf'

#debiancnf:
#  name     : 'local'
#  'my.cnf' : '/etc/mysql/debian.cnf'

#socket1:
#  name     : 'local'
  # user     : ''
  # pass     : ''
#  socket   : '/var/run/mysqld/mysqld.sock'

#socket2:
 # name     : 'local'
 #  user     : 'root'
  # pass     : ''
#  socket   : '/var/run/mysqld/mysql.sock'

socket3:
  name     : 'local'
   user     : 'root'
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'

socket4:
  name     : 'local'
  # user     : ''
  # pass     : ''
  socket   : '/tmp/mysql.sock'

tcp:
  name     : 'local'
  # user     : ''
  # pass     : ''
  host     : 'localhost'
  port     : '3306'
  # keep in mind port might be ignored by mysql, if host = 'localhost'
  # http://serverfault.com/questions/337818/how-to-force-mysql-to-connect-by-tcp-instead-of-a-unix-socket/337844#337844

tcpipv4:
  name     : 'local'
  # user     : ''
  # pass     : ''
  host     : '127.0.0.1'
  port     : '3306'

tcpipv6:
  name     : 'local'
  # user     : ''
  # pass     : ''
  host     : '::1'
  port     : '3306'


# Now we try the same as above with user: root
# A few systems configure mysql to accept passwordless
# root access.

mycnf1_root:
  name     : 'local'
  user     : 'root'
  'my.cnf' : '/etc/my.cnf'

mycnf2_root:
  name     : 'local'
  user     : 'root'
  'my.cnf' : '/etc/mysql/my.cnf'

socket1_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  socket   : '/var/run/mysqld/mysqld.sock'

socket2_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  socket   : '/var/run/mysqld/mysql.sock'

socket3_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'

socket4_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  socket   : '/tmp/mysql.sock'

tcp_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  host     : 'localhost'
  port     : '3306'
  # keep in mind port might be ignored by mysql, if host = 'localhost'
  # http://serverfault.com/questions/337818/how-to-force-mysql-to-connect-by-tcp-instead-of-a-unix-socket/337844#337844

tcpipv4_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  host     : '127.0.0.1'
  port     : '3306'

tcpipv6_root:
  name     : 'local'
  user     : 'root'
  # pass     : ''
  host     : '::1'
  port     : '3306'


# Now we try the same as above with user: netdata

mycnf1_netdata:
  name     : 'local'
  user     : 'netdata'
  'my.cnf' : '/etc/my.cnf'

mycnf2_netdata:
  name     : 'local'
  user     : 'netdata'
  'my.cnf' : '/etc/mysql/my.cnf'

socket1_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  socket   : '/var/run/mysqld/mysqld.sock'

socket2_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  socket   : '/var/run/mysqld/mysql.sock'

socket3_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'

socket4_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  socket   : '/tmp/mysql.sock'

tcp_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  host     : 'localhost'
  port     : '3306'
  # keep in mind port might be ignored by mysql, if host = 'localhost'
  # http://serverfault.com/questions/337818/how-to-force-mysql-to-connect-by-tcp-instead-of-a-unix-socket/337844#337844

tcpipv4_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  host     : '127.0.0.1'
  port     : '3306'

tcpipv6_netdata:
  name     : 'local'
  user     : 'netdata'
  # pass     : ''
  host     : '::1'
  port

**Comment by paulfantom** [comment]
@d1mf please wrap pasted information in code block. It increases readability of your messages a lot.

More information: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by d1mf** [comment]
Sorry. Done. I add a config. This just default config, I comment few lines.

**Comment by paulfantom** [comment]
@d1mf 

> "/opt/netdata/etc/netdata/python.d/mysql.conf", line 130, column 1

This couldn't be written simpler. You have a problem somewhere in line 130. This corresponds to this section:
```yaml
socket3:
  name     : 'local'
   user     : 'root'
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'
```

YAML is sensitive to whitespaces, so number of spaces is important. Now compare section above to this one and I hope you will instantly see what is wrong:
```yaml
mycnf1_root:
  name     : 'local'
  user     : 'root'
  'my.cnf' : '/etc/my.cnf'
```

**Comment by d1mf** [comment]
You have an example this config? I want  paste

**Comment by d1mf** [comment]
Done


2018-08-06 21:31:17: charts.d: : mysql: command '/usr/bin/mysql -h 127.0.0.1 -uroot -N -e SHOW\ GLOBAL\ STATUS\; ' failed with code 1:
2018-08-06 21:31:17: charts.d: ERROR: mysql: cannot get global status for 'local'. Please set mysql_opts[local]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 21:31:17: charts.d: ERROR: mysql: no mysql servers found. Please set mysql_opts[name]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 21:31:17: charts.d: ERROR: mysql: module's 'mysql' check() function reports failure.
2018-08-06 21:31:18: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
  in "/opt/netdata/etc/netdata/python.d/mysql.conf", line 131, column 1
2018-08-06 21:31:18: python.d ERROR: mysql: mysql: Connection properties are missing
2018-08-06 21:31:18: python.d INFO: mysql: mysql: check() => [FAILED]
[root@server ~]# mcedit  /opt/netdata/etc/netdata/python.d/mysql.conf

Not work

**Comment by d1mf** [comment]
![screenshot_167](https://user-images.githubusercontent.com/10393074/43719417-54b9960a-9996-11e8-89d2-d5179e396957.jpg)

**Comment by l2isbad** [comment]
@d1mf 

Still syntax error

> 2018-08-06 21:31:18: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
in "/opt/netdata/etc/netdata/python.d/mysql.conf", line 131, column 1

Look at line 131

[Online yaml validator](http://yaml-online-parser.appspot.com/) - сopy the entire configuration there to see if it has any errors.

**Comment by d1mf** [comment]
socket3: - this 131 line.  
  name     : 'local'
  user     : 'root'
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'

I think this config not valid?

**Comment by l2isbad** [comment]
Well, i suggest to remove (delete) all jobs from config you don't need. After you have only one it will be easier to debug the problem.

**Comment by d1mf** [comment]
Error lines fixed.

2018-08-06 23:17:57: charts.d: : mysql: command '/usr/bin/mysql -h 127.0.0.1 -uroot -N -e SHOW\ GLOBAL\ STATUS\; ' failed with code 1:
2018-08-06 23:17:57: charts.d: ERROR: mysql: cannot get global status for 'local'. Please set mysql_opts[local]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 23:17:57: charts.d: ERROR: mysql: no mysql servers found. Please set mysql_opts[name]='options' to whatever needed to get connected to the mysql server, in /opt/netdata/etc/netdata/mysql.conf
2018-08-06 23:17:57: charts.d: ERROR: mysql: module's 'mysql' check() function reports failure.
2018-08-06 23:17:58: python.d ERROR: mysql: mysql: Can't establish connection to MySQL: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
2018-08-06 23:17:58: python.d INFO: mysql: mysql: check() => [FAILED]

**Comment by d1mf** [comment]
bash: /usr/libexec/netdata/plugins.d/python.d.plugin: No such file or directory

**Comment by d1mf** [comment]
Thanks for your help. I fix this problem.
1) I create other user mysql
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost' with grant option;
# > flush privileges;
2) I comment lines in config mcedit /opt/netdata/etc/netdata/python.d/mysql.conf
![screenshot_172](https://user-images.githubusercontent.com/10393074/43778849-6c24d65a-9a5f-11e8-9596-deaaf7da3050.jpg)

3) I edit config mcedit /opt/netdata/etc/netdata/charts.d/mysql.conf  ( remove other lines save only one socket) to
![screenshot_171](https://user-images.githubusercontent.com/10393074/43778898-8a52e9a0-9a5f-11e8-84a6-d54a6a595813.jpg)

Result 
![screenshot_173](https://user-images.githubusercontent.com/10393074/43778930-a5eb491e-9a5f-11e8-97f3-0413c8f8228e.jpg)

 Very nice.

**Comment by l2isbad** [comment]
@d1mf nice you had succeeded :+1:

**Comment by d1mf** [comment]
Yes.
P.S. if using user root command
mysql -u root ( login working)
user netdata "mysql -u root" not working
User netdata(linux) not have access login root mysql
This just a problem. I want using same user root(need 100% create new user MySQL)
