### ISSUE TITLE
Changing python version

### ISSUE THREAD

**Issue by andybr0** [firehol/netdata#4038]
Hey,

Need some help to set default python version to 2.7

I've got stuck after upgrading pip for python/python2.6 (it keeps crashing), so I had to install 2.7 to install pymysql.

Job done and all I did after was :

1. Added the following in netdata.conf : 

`PATH environment variable = /usr/local/bin`
`PYTHONPATH environment variable = ${PYTHONPATH_NETDATA}`

root@s062 [/etc/netdata]# printenv | grep -i pythonpath
PYTHONPATH_NETDATA=/usr/local/bin/python2.7
root@s062 [/etc/netdata]# which python2.7
/usr/local/bin/python2.7

2. Tried to set an alias for the user netdata for python to '/usr/local/bin/python2.7'

None worked.

Thanks!

**Comment by l2isbad** [comment]
yo @andybr0 

https://github.com/firehol/netdata/issues/1731#issuecomment-277767601

**Comment by andybr0** [comment]
Thanks, @l2isbad 

Guess what, it didn't work, but, unbeliveably, this one worked : 

(Modified /usr/libexec/netdata/plugins.d/python.d.plugin - even if it doesn't make sense for me cuz that isn't stored in a variable that will be called later on, haha)

'''':; exec "$(command -v **python2.7** || command -v python3 || command -v python2 ||
echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''

Fyi, I'm using CloudLinux 6.

This can be closed, thanks.

**Comment by paulfantom** [comment]
> This can be closed, thanks.

You can do it! :stuck_out_tongue:

**Comment by andybr0** [comment]
First time using github. xD

**Comment by l2isbad** [comment]
@andybr0 
Keep in mind that `python.d.plugin` will be overwritten after next update.

**Comment by mailinglists35** [comment]
this is still broken 

both environment variable and global option "PYTHONPATH environment variable" appears to be loaded into netdata, however the cx_Oracle plugin ignores it and goes with /usr/bin/python. I see netdata process environment in /proc/pid/ is loading PYTHONPATH=/usr/bin/python3 as I asked by editing the systemd service with Environ=... or changing the netdata.conf, however the cx_Oracle loads with python2 which is the os default in centos 7 (and fails to work, as it requires python 3)

also I see `/usr/libexec/netdata/plugins.d/python.d.plugin` appears to look at it's argument `-p` and use that path for python executable, but apparently the parent process netdata didn't pass that argument to it (i dont' see it in ps, I only see `/etc/netdata/python /usr/libexec/netdata/plugins.d/python.d.plugin 1`). perhaps it should do that?

**Comment by mailinglists35** [comment]
only the workaround in comment 2 works

**Comment by ilyam8** [comment]
Hi @mailinglists35, it works

```cmd
ilyam@x:~$ ps aux | grep "[p]ython.d.plugin"
netdata   7753  0.1  5.2 109140 53288 ?        Sl   Apr20   8:42 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

ilyam@x:~$ grep "plugin:python.d" -A 2 /opt/netdata/etc/netdata/netdata.conf
[plugin:python.d]
	# update every = 1
	command options = -ppython3

ilyam@x:~$ sudo systemctl restart netdata
ilyam@x:~$ ps aux | grep "[p]ython.d.plugin"
netdata  25882 74.0  2.3  75888 23748 ?        D    06:39   0:00 python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
```

**Comment by mailinglists35** [comment]
ah lovely, thank you! I was trying `-p /usr/sbin/python3` 😂

**Comment by ilyam8** [comment]
> -p /usr/sbin/python3

The problem is a space, should be `-p/usr/sbin/python3`
