### ISSUE TITLE
Stops updating when window is not active.

### ISSUE THREAD

**Issue by deathtrip** [firehol/netdata#4039]
I have a multi monitor setup, and when i open netdata in one monitor and switch to another one, the stats stop updating until i reactivate the window. I suspect it's done to not waste resources, but it's not ideal when using multiple monitors. An option to always update would solve this. Using 1.10 version on Arch Linux with chromium browser.

**Comment by paulfantom** [comment]
Go to settings (cog wheel in the upper right corner) and change parameter "When to refresh the charts?" from "On Focus" to "Always".

**Comment by deathtrip** [comment]
Somehow i omitted this, while skimming the options quickly. Closing. Thanks for the answer.
