### ISSUE TITLE
stream and allmetrics api are not feasible in large scale setup 

### ISSUE THREAD

**Issue by Ehekatl** [firehol/netdata#4043]
netdata is awesome and it works well in distributed manner on individual server.
I wanna bring it to our production, with the power for central selected metrics only to netdata master or prom.

Here is a few of my use case:

 - on slave node, netdata collect fine grained data for short period, as well as streaming to proxy
 - proxy node will overcome network difficulty and upstream to master node, it also serve for prometheus scrape with allmetrics api
 - master store the data for longer period for problem tracing

I tried dozens of slave streaming to master, and the data transfer is already overwhelming, but I need collect data from thousands of netdata slave in production. 

An easy fix would be support different update interval on each node, say slave update per second, proxy per 15 seconds for prom support, and master node update per minute with important metrics only. With an instance of 256GB mem, we could easily feed with thousands of slave data in days.

Also allmetrics api need should support `send charts matching` like in backend, it's very unnecessary to pull all data together.

**Comment by ktsaou** [comment]
Hi,

I understand you have 2 problems:

1. the bandwidth required for streaming all the metrics
2. the memory required for maintaining all the metrics centrally

Right?

**Comment by paulfantom** [comment]
@Ehekatl Out of curiosity, what is the scale of netdata deployment you want to do? I mean how many nodes?

**Comment by paulfantom** [comment]
> Also allmetrics api need should support send charts matching like in backend, it's very unnecessary to pull all data together.

It is called `allmetrics` so it should expose all metrics. This api is meant to be used by prometheus and in such model discarding metrics should be done by prometheus itself.

**Comment by ktsaou** [comment]
I missed that.

The `send charts matching` setting is respected by the prometheus backend. So, for `allmetrics?format=prometheus` and `allmetrics?format=prometheus_all_hosts` it works.

`allmetrics` has non-prometheus formats, which are not backend related, so they ignore this option.

Make sure you uncomment it in `netdata.conf` though.

**Comment by Ehekatl** [comment]
@ktsaou thanks! I missed that point 👍 , it's better to document this nice feature
`send charts matching` works well with allmetrics api

closed

**Comment by paulfantom** [comment]
> new database format that will be able to provide a better memory footprint

If you figure out how to create efficient database for metrics from 1000s of nodes, then pitch it to google or uber, they will be very interested :smile:

Uber is already working on such thing based on gorilla database paper (as almost all new time-series dbs) - [uber m3db](https://github.com/m3db).

**Comment by ktsaou** [comment]
Well, Gorilla managed to have 1.3 bytes per point.
I think we can do 1 byte per point easily. The reason is that we have to shrink down from 4 bytes per points. They are shrinking down from 16 bytes (or 12 I don't recall exactly).

**Comment by paulfantom** [comment]
> I think we can do 1 byte per point easily

I think you are too optimistic in that.

**Comment by ktsaou** [comment]
> I think you are too optimistic in that.

We have done some tests with @Ferroin. We can gain 50% due to deduplication and 50% due to compression. This is 25%. We start from 4 bytes, so 1 byte finally.
This is without doing the XOR and variable record length magic Gorilla does.
