### ISSUE TITLE
metrics and alarms for streaming?

### ISSUE THREAD

**Issue by Ehekatl** [firehol/netdata#4044]
idk if it's possible to get the metrics and alarm when slave failed to stream?
this is a very important feature when slaves are dynamic, slaves may connected to different proxy

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/issues/3931

**Comment by Ehekatl** [comment]
@ktsaou I saw that issue, but what would be better is let slave send alarm directly instead of let proxy to check.

I'm running a HA proxy cluster, and thanks to the good design of socket client, I'm able to provider a list of ip with dns, node will try different ones if previous connect failed.

In such case, proxy stream health check doesn't work.
