### ISSUE TITLE
duplicate name in statsd chart

### ISSUE THREAD

**Issue by Ehekatl** [firehol/netdata#4045]
I'm on the latest netdata version with default statsd config, I added a simple statsd gauge and this is what i got:

`statsd_gauge_billing_metrics_collector_new_billing_files.statsd_gauge_billing_metrics_collector_new_billing_files.statsd_gauge_billing_metrics_collector_new_billing_files.gauge`

![](https://i.ooxx.ooo/2018/08/07/6432108ec11abee98cf82f3b9f4423cd.png)

**Comment by Ehekatl** [comment]
I found out this duplication was caused by stream, each time it append statsd label on it again.
in my setup I have slave -> proxy -> master

**Comment by ktsaou** [comment]
I thought this had been fixed. Are all your netdata up to date?

**Comment by ktsaou** [comment]
It was fixed with this: https://github.com/firehol/netdata/pull/2294
Which is pretty old. Let me setup a test environment to test this.

**Comment by Ehekatl** [comment]
let me upgrade to the latest version and see
thanks!
