### ISSUE TITLE
/proc/interrupts plugin memory leak

### ISSUE THREAD

**Issue by abalabahaha** [firehol/netdata#4051]
Recently noticed this odd behavior on one of my ARM64 servers running netdata `v1.10.0-537-g6832ce4_rolling`.

If `plugin:proc:/proc/interrupts` is enabled, netdata memory usage appears to increase until the system OOM killer kills the netdata process. If I refresh the dashboard, the `###` in `"netdata collects every second ### metrics"` appears to be increasing by 5 every data collection interval, +1 per interrupt graph (`system.interrupts`, `cpu.cpu#_interrupts` for CPUs 0-3). After a restart yesterday, it went from ~350 metrics to over 50,000 metrics in a couple hours, eating up over 600MB RAM.

I've been unable to reproduce the behavior on a second server, but the issue persists across complete netdata re-installs on this server alone. Disabling the `/proc/interrupts` metric appears to work as a temporary fix, but any pointers on figuring out what's going wrong would be appreciated. Thanks.

**Comment by Ferroin** [comment]
Could you provide a sample of `/proc/interrupts` from one of the systems?  I'm betting it's a parsing problem, and there's a new dimension getting created each collection cycle, but determining that for sure is going to require a sample of `/proc/interrupts` from a system demonstrating the issue.

**Comment by abalabahaha** [comment]
System with issue:
```
$ cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3       
  3:  453878208  395543651  370433962  375091079     GICv3  27 Level     arch_timer
 38:          0          0          0          0     GICv3  33 Level     uart-pl011
 42:          0          0          0          0   ITS-MSI 32768 Edge      virtio1-config
 43:   22710415          0          0          0   ITS-MSI 32769 Edge      virtio1-req.0
 44:          0          0          0          0   ITS-MSI 16384 Edge      virtio0-config
 45: 1691568750          0          0          0   ITS-MSI 16385 Edge      virtio0-input.0
 46:      27873          0          0          0   ITS-MSI 16386 Edge      virtio0-output.0
 47:          0          0          0          0     pl061   3 Edge      GPIO Key Poweroff
IPI0:1145401553 1472373355 1450864145 1424997779       Rescheduling interrupts
IPI1:        44        144        156        166       Function call interrupts
IPI2:         0          0          0          0       CPU stop interrupts
IPI3:         0          0          0          0       CPU stop (for crash dump) interrupts
IPI4:         0          0          0          0       Timer broadcast interrupts
IPI5:         1          0          0          0       IRQ work interrupts
IPI6:         0          0          0          0       CPU wake-up interrupts
Err:          0
```

Similar system without issue:
```
$ cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3       
  3:  371437939  299493661  277196595  267549707     GICv3  27 Level     arch_timer
 38:          0          0          0          0     GICv3  33 Level     uart-pl011
 42:          0          0          0          0   ITS-MSI 32768 Edge      virtio1-config
 43:   40387242          0          0          0   ITS-MSI 32769 Edge      virtio1-req.0
 44:          0          0          0          0   ITS-MSI 16384 Edge      virtio0-config
 45:  162588387          0          0          0   ITS-MSI 16385 Edge      virtio0-input.0
 46:       1704          0          0          0   ITS-MSI 16386 Edge      virtio0-output.0
 47:          0          0          0          0     pl061   3 Edge      GPIO Key Poweroff
IPI0: 236572354  206877055  214651873  215353967       Rescheduling interrupts
IPI1:      4188       4908       4761       4322       Function call interrupts
IPI2:         0          0          0          0       CPU stop interrupts
IPI3:         0          0          0          0       CPU stop (for crash dump) interrupts
IPI4:         0          0          0          0       Timer broadcast interrupts
IPI5:    252430          0          0          0       IRQ work interrupts
IPI6:         0          0          0          0       CPU wake-up interrupts
Err:          0
```

**Comment by abalabahaha** [comment]
Upon further testing, I think it's the parser trying to grab `IPI0:1145401553` as a single word. If I change the monitor file and have a script manually add a space after that colon, the metrics count stops increasing.

**Comment by Ferroin** [comment]
Thanks for reporting this in the first place, it probably would have gone unnoticed for quite some time since machines which have seen billions of interrupts are not exactly a common test case for Netdata.
