### ISSUE TITLE
httpcheck: ability to disable response_time alarm for specific services

### ISSUE THREAD

**Issue by tferreira** [firehol/netdata#4056]
Hi,

I'm using the httpcheck functionnality and it's helping me a lot to keep netdata as my unique monitoring system. Good job developing it!

However, I'm monitoring websites that are often under heavy load and could have rollercoaster-like response times. I'd love to be able to keep the alarm on status code, but still be able to deactivate the "response_time" one for specific web services.

Is that something easily doable ?

Thank you!

cc @ccremer ;-)

**Comment by ccremer** [comment]
alarms are configured in the configuration file:
https://github.com/firehol/netdata/blob/master/conf.d/health.d/httpcheck.conf
Also check out the reference for health:
https://github.com/firehol/netdata/wiki/health-configuration-reference

If you want to completely disable response times for all websites, comment out the respective section.

If you want to modify the alarm for a single site, add a section (in the same or a new file) like this:
```
   alarm: web_service_slow
families: *
      on: httpcheck_yourwebsite.response_time
  lookup: average -10m unaligned of time
   units: ms
   every: 10s
    warn: ($this > ($1h_web_service_response_time * 3) )
    crit: ($this > ($1h_web_service_response_time * 5) )
    info: average response time over the last 3 minutes, compared to the average over the last hour
   delay: down 5m multiplier 1.5 max 1h
 options: no-clear-notification
      to: webmaster
```
which is basically the same, except "template" is now "alarm" and a few modified numbers. you'll have to figure out which ones you like.

If you set "to: silent", then you will still see the alarm in the alarm list (all - tab) greyed out and it won't send a notification. Some alarms are configured like this only to provide intermediary values used by other alarms. The example above just shows this: it uses `$1h_web_service_response_time`

I haven't tested this, but it should provide a starting point at the least.

**Comment by tferreira** [comment]
Thank you very much for your answer, I'll do it that way!
