### ISSUE TITLE
[ Prometheus ] RAM Metric sum 

### ISSUE THREAD

**Issue by inattendu** [firehol/netdata#4065]
First, congratulation for all the work made on the prometheus integration,
---

I'm trying to create (grafana) alert on RAM usage, so I need to sum the cached & free amount of RAM.

I'm actualy stuck because I can get this two metrics separately, but can't do the addition on the prometheus query.. 

The folowing query return "No datapoints found." :

`netdata_system_ram_MB_average{chart="system.ram",dimension="cached",family="ram",instance="192.168.66.102:19999",job="netdata-io"} +  netdata_system_ram_MB_average{chart="system.ram",dimension="free",family="ram",instance="192.168.66.102:19999",job="netdata-io"}`

strange fact : that second query effectively double the original value of cached RAM..  
`(netdata_system_ram_MB_average{chart="system.ram",dimension="cached",family="ram",instance="192.168.66.102:19999",job="netdata-io"} +  netdata_system_ram_MB_average{chart="system.ram",dimension="cached",family="ram",instance="192.168.66.102:19999",job="netdata-io"} )`

but as soon as I use two different dimensions, the query failed to get metrics.

**Comment by n0guest** [comment]
How about this?

```
sum(netdata_system_ram_MB_average{dimension=~"(cached|free)",family="ram",instance="192.168.66.102:19999",job="netdata-io"}) by (instance,job)
```
PS: BTW, it's kinda offtopic for Netdata's issue and you better to ask such questions in [Prometheus Users at Google Groups](https://groups.google.com/d/forum/prometheus-users).
