### ISSUE TITLE
freeipmi.plugin : Not working on Raspberry Pi

### ISSUE THREAD

**Issue by IWishIhadAnOriginalUsername** [firehol/netdata#4066]
Hi,
Should the freeimpi plugin work on a Raspberry Pi 3B?

I do not see any chart or alarm options after installation.

When I test:
pi@raspberrypi:/etc/netdata $ sudo su -s /bin/sh netdata

**$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug**
_2018-08-19 19:40:10: freeipmi.plugin ERROR : MAIN : update frequency 5 seconds is too small for IPMI. Using 5.
freeipmi.plugin: calling _init_ipmi_config()
freeipmi.plugin: calling ipmi_monitoring_init()
freeipmi.plugin: detecting IPMI minimum update frequency...
freeipmi.plugin: checking data collection speed iteration 1 of 10
2018-08-19 19:40:10: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): internal system error (errno 9, Bad file descriptor)
2018-08-19 19:40:10: freeipmi.plugin FATAL : MAIN :freeipmi.plugin: data collection failed. # : Success_

(Some of the debug output should probably be reconsidered :) )

Steps to recreate:
Install all pre-requisites (I tried `curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
` and `apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`  + relevant ipmi tools (libipmimonitoring)
Then installed.
- As per https://github.com/firehol/netdata/wiki/Installation 
and https://github.com/firehol/netdata/wiki/monitoring-IPMI)

All tools seem to be present and the plugin generated.
ipmi-sensors - 1.4.11
netdata freeipmi.plugin 1.10.1_rolling

In **/etc/netdata/netdata.conf**
```
[plugins]
 freeipmi = yes

[plugin:freeipmi]
         update every = 1

        # command options =

```

Note: In your documentation, there is slightly conflicting information:
https://github.com/firehol/netdata/wiki/monitoring-IPMI :  

> 
> 
>     install libipmimonitoring-dev or libipmimonitoring-devel (freeipmi-devel on RHEL based OS) using the package manager of your system.
> 
>     re-install netdata from source. The installer will detect that the required libraries are now available and will also build freeipmi.plugin.

but on https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata : 

>  compile/install netdata with --enable-plugin-freeipmi

(I have tried both.)

**Comment by Ferroin** [comment]
Given your configuration, it looks like you're trying to collect data from the local system.  This will never work for a Raspberry Pi, because they have no IPMI hardware.

**Comment by IWishIhadAnOriginalUsername** [comment]
Thank you.
