### ISSUE TITLE
Silent Installation script

### ISSUE THREAD

**Issue by enVolt** [firehol/netdata#4069]
Hi,

The auto-installation script is really simple to use. Does the magic automatically. I was recently installing netdata on multiple instances. It happened often that installation was waiting for prompt to press "Y" and such things. Can we have a silent installation script, in case everything is going smooth?

**Comment by paulfantom** [comment]
We already have parameters which can be used in case someone wants non-interactive installation, like `--dont-wait`. As for silencing (no log output) it can be achieved by simply adding `&>/dev/null` to the command.

**Comment by solution-al** [comment]
This is how we try to install netdata in an unattended way:

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait
```

It still asks us for the initial installation permission and while updating/installing with apt. We would like to have a way of not getting any prompts.
