### ISSUE TITLE
how to stop netdata on MacOS

### ISSUE THREAD

**Issue by hayata-yamamoto** [firehol/netdata#4082]
According to your stdout on installer.sh, killall command is to stop netdata service on MacOS, but I cannot stop.

```
> killall netdata 
No matching processes belonging to you were found
```

Would you tell how to stop your service ( and start )?

**Comment by mike-savory** [comment]
Try with “ sudo killall netdata “

**Comment by hayata-yamamoto** [comment]
Thanks!

**Comment by aSk134** [comment]
"sudo pkill netdata" should also work
