### ISSUE TITLE
Busy Elasticsearch instances go missing

### ISSUE THREAD

**Issue by NetwarSystem** [firehol/netdata#4087]
I have recently begun running netdata with the primary motivation of keeping an eye on Elasticsearch. My dev environment is three two core VMs running on an old laptop, one of my production systems is a standalone 24 core 48 gig Xeon. Elastic is 5.6.10 or 5.6.11, most systems are Ubuntu 16.04.05 LTS.

No matter what class of machine, when the system gets busy during bulk ingestion of content, netdata will often drop the 'elasticsearch local' option. Restart of netdata will bring it back, but this sometimes requires two or three "systemctl restart netdata" to restore.

I examined the elasticsearch.conf file:

>    alarm: elasticsearch_last_collected
>       on: elasticsearch_local.cluster_health_status
>     calc: $now - $last_collected_t
>    units: seconds ago
>    every: 10s
>     warn: $this > (($status >= $WARNING)  ? ($update_every) : ( 5 * $update_every))
>     crit: $this > (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))
>     info: number of seconds since the last successful data collection
>       to: sysadmin

Does this mean that Elasticsearch would be treated as down after 60 * 10 seconds of being unavailable? Some of the data I handle will make a system busy for ten hours. I'd prefer spotty coverage to the hassle of having to constantly restart.

**Comment by ktsaou** [comment]
> Does this mean that Elasticsearch would be treated as down after 60 * 10 seconds of being unavailable?

No. warning on 5 seconds, critical on 60 seconds. This is irrelevant to the issue of netdata losing connection to elasticsearch.

Generally, data collection never gives up. So, if elasticsearch is unresponsive, the netdata plugin will retry forever (of course the alarm will trigger).

There is another issue though. Netdata runs by default with the idle scheduling policy, so it gets CPU only when there is some available. If your system, is 100% busy for that long, I suggest to increase the netdata priority. This will also increase the priority of the plugins.

To increase netdata priority under systemd, you need to edit netdata.service to set:

```
CPUSchedulingPolicy=rr
CPUSchedulingPriority=99
```

The above allows netdata to be run with real-time priority 50 (1 lowest, 99 highest).
Then you need to edit netdata.conf to set the same:

```
[global]
  process scheduling policy = rr
  process scheduling priority = 99
```

Keep in mind that netdata.conf can only lower the priority set by systemd. So, to increase it, you have to edit both.

The above will allow netdata to get the CPU it needs, even when the system is 100% busy.

**Comment by paulfantom** [comment]
```
[global]
  process scheduling policy = keep
```

Why don't we make this a default setting? Shouldn't managing scheduling and priority be a job of an init system?

**Comment by ktsaou** [comment]
> Shouldn't managing scheduling and priority be a job of an init system?

Frequently it is not.

What we can do, is modify `netdata.service` to run netdata with these options:

```
netdata -W set global 'process scheduling policy' 'keep'
```

So, when run under systemd, it will not touch these settings. Making a PR...

**Comment by paulfantom** [comment]
> Frequently it is not.

Seems like we are fixing someone else bug here by creating a workaround. Why not fix this in those init systems then?

**Comment by ktsaou** [comment]
Well, it is not only init systems.
When you run it in docker, you will have the same effect. If you run it by hand you will have to do this too.
It is better to ignore the defaults only when running under systemd, to allow systemd have full control.

**Comment by ktsaou** [comment]
PR #4143 does it.
Of course, netdata installer never overwrites netdata.service, so existing installations will have to copy it by themselves.

**Comment by paulfantom** [comment]
> netdata installer never overwrites netdata.service

That is something which should be fixed as it is a design bug.

**Comment by ktsaou** [comment]
merged the fix.
@paulfantom if we update netdata.service with the installer, people will loose their settings. These files are supposed to be editable. Except if we install it in `/usr/lib/systemd/system` and link it to `/etc/systemd/system/`.

hm...

**Comment by paulfantom** [comment]
That's why installed systemd service should be in /lib not in /etc. You don't need to link it to /etc, that is systemd design and it is installation bug on our side.

**Comment by paulfantom** [comment]
More info about systemd service files:
https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files section "Where are Systemd Unit Files Found?"

**Comment by ktsaou** [comment]
ok, in PR #4151

**Comment by Komic** [comment]
@ktsaou will running `netdata-updater.sh` apply this change?

**Comment by ktsaou** [comment]
The new installer will install netdata.service to /lib/systemd/system. But we cannot delete /etc/systemd/system/netdata.service automatically (it may have been modified).

So, if you delete this, before running the updater, the new installer will install the new.

Of course, after we merge #4151

**Comment by Komic** [comment]
sounds good, thanks. (:
