### ISSUE TITLE
alarm-notify.sh test - Email - Receive only one

### ISSUE THREAD

**Issue by Ricolo53** [firehol/netdata#4094]
Hello,

When I launch `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` without ROLE to test email notification (with postfix), I can see on syslog that 3 emails was send but only one has good recipent. Here log

> Aug 30 20:06:35 appli postfix/local[29095]: 2CF46E0125: to=<no-reply@myapp.fr>, relay=local, delay=0, delays=0/0/0/0, dsn=5.1.1, status=bounced (unknown user: "no-reply")
> Aug 30 20:06:35 appli postfix/qmgr[15901]: 2CF46E0125: removed
> Aug 30 20:06:35 appli postfix/local[29095]: 2D229DFAD8: to=<no-reply@myapp.fr>, relay=local, delay=0, delays=0/0/0/0, dsn=5.1.1, status=bounced (unknown user: "no-reply")
> Aug 30 20:06:35 appli postfix/qmgr[15901]: 2D229DFAD8: removed
> Aug 30 20:06:35 appli postfix/smtp[29009]: CC6F1DFB6D: to=<myappfr@gmail.com>, relay=gmail-smtp-in.l.google.com[66.102.1.26]:25, delay=0.54, delays=0/0/0.41/0.13, dsn=2.0.0, status=sent (250 2.0.0 OK 1535652395 y9-v6si6091902wrl.91 - gsmtp)

As you can see, 2 mails was send to **EMAIL_SENDER** config (no-reply) and only one to **DEFAULT_RECIPIENT_EMAIL**

Below debug when I launch command

> # SENDING TEST WARNING ALARM TO ROLE: sysadmin
> 2018-08-30 20:06:34: alarm-notify.sh: INFO: sent email notification for: myappfr test.chart.test_alarm is WARNING to 'myappfr@gmail.com'
> # OK
> 
> # SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
> 2018-08-30 20:06:34: alarm-notify.sh: INFO: sent email notification for: myappfr test.chart.test_alarm is CRITICAL to 'myappfr@gmail.com'
> # OK
> 
> # SENDING TEST CLEAR ALARM TO ROLE: sysadmin
> 2018-08-30 20:06:34: alarm-notify.sh: INFO: sent email notification for: myappfr test.chart.test_alarm is CLEAR to 'myappfr@gmail.com'
> # OK

Does I'm doing something wrong ?

**Comment by ktsaou** [comment]
hm... I think something else is wrong. Emails bounce. Have you used anywhere in alarm-notify configuration the email "no-reply@myapp.fr"?

You can get more output from `alarm-notify.sh` by running this:

```sh
export NETDATA_ALARM_NOTIFY_DEBUG=1
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```

**Comment by Ricolo53** [comment]
Thanks for reply.

It was very strange. I relaunch test (with & without export) and now it's ok, I receive all 3 testing emails.

We apply little change on postfix configuration to avoid gmail ban (remove IPV6 sending per exemple), perhaps it resolve error..

In all case thanks for helping & information about DEBUG, it's not on [wiki page](https://github.com/firehol/netdata/wiki/alarm-notifications)

**Comment by ktsaou** [comment]
> In all case thanks for helping & information about DEBUG, it's not on wiki page

Thank you! Just added it.
