### ISSUE TITLE
SNMP section not visible after September 1st

### ISSUE THREAD

**Issue by simonszu** [firehol/netdata#4099]
I have had a working SNMP configuration in the past. However, somewhen around September 1st it stopped working. I have netdata running as a docker container and autoupdate via https://github.com/v2tec/watchtower. The last metrics netdata collected and pushed to my InfluxDB was from August 30th. 
Now, SNMP isn't working for some reasons, maybe because of an update of netdata? 

However, `/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp` returns values, but it just isn't showing up in the web frontend. I cannot find any lines regarding `node` or `snmp` in the log files either, it just seems that netdata is ignoring snmp (or node, i cannot tell, since snmp is the only node.js plugin i use) at all. 

Maybe this is related to https://github.com/firehol/netdata/issues/4021

**Comment by ktsaou** [comment]
hm... interesting... nothing changed in that respect in netdata.

Can you try running the snmp plugin as user netdata?

**Comment by ktsaou** [comment]
SNMP plugin depends on node.js. I guess user netdata cannot run node.js for some reason.

**Comment by simonszu** [comment]
I am running netdata dockerized. In the container, netdata isn't `su`-able, and sudo isn't available. However, i am closing it now, since i have SNMP reappearing again. Maybe it was an issue of the underlying base image.
