### ISSUE TITLE
netdata-installer.sh

### ISSUE THREAD

**Issue by titpetric** [firehol/netdata#41]
Hi,

I would ask if you could split the installer at least into two logical parts. I would like just to build netdata, and have the other steps (running netdata) as optional. It can be done with arguments, like make:

```
./netdata-installer.sh build install
```

Which would first run build, and then the install part (some loop over arguments in bash). I am building a docker image which requires building an artefact, but it doesn't require generating the configs/running netdata (this should be done when the container runs).

**Comment by ktsaou** [comment]
Hi,

Once netdata is released I will remove the installer. So, don't depend on it.

The standard procedure for compiling from source can be used to build netdata:

```sh
# set this to the directory to install netdata
# if empty, it will be installed in /
NETDATA_PREFIX=

/autogen.sh

./configure \
	--prefix="${NETDATA_PREFIX}/usr" \
	--sysconfdir="${NETDATA_PREFIX}/etc" \
	--localstatedir="${NETDATA_PREFIX}/var" \
	--with-zlib --with-math --with-user=netdata \
	CFLAGS="-O3"

make && make install
```

If you use the `netdata` user (option `--with-user=netdata` above), you may need to add this user to the system. The following commands add it, if it is not already there:

```
getent group netdata > /dev/null || groupadd -r netdata
getent passwd netdata > /dev/null || useradd -r -g netdata -c netdata -s /sbin/nologin -d / netdata
```

To prevent netdata from complaining about missing directories, create these directories (if they are not already there) and chown them (and their contents) to user `netdata`:

```sh
${NETDATA_PREFIX}/usr/share/netdata/web
${NETDATA_PREFIX}/etc/netdata
${NETDATA_PREFIX}/var/cache/netdata
${NETDATA_PREFIX}/var/log/netdata
```

`make install` will setuid to root `${NETDATA_PREFIX}/usr/libexec/netdata/plugins.d/apps.plugin`
Make sure it does in your system. It should be owned by `root` with permissions 4755, like this:

```text
-rwsr-xr-x 1 root root 81592 Dec 18 03:25 apps.plugin
```

Also, if you don't care about configuration, touch this file to prevent netdata from complaining:

```
${NETDATA_PREFIX}/etc/netdata/netdata.conf
```

**Comment by ktsaou** [comment]
Also, I suggest to set `NETDATA_PREFIX` to `/opt` or `/usr/local`.
You should not "poison" your system with unpackaged installations.

Keep in mind that I develop netdata these days. Currently the source is pretty stable, but keep an eye on it and report any issues you find.

Thanks!

**Comment by titpetric** [comment]
Hello,

Current problem is that when/if I would copy the above build procedure into the Dockerfile, that we would have split responsibility when it comes to building netdata. When the build procedure will change, the Docker build would break. I'd like to avoid this split brain build if possible.

I'm more than capable and willing to fork/fix/pull the netdata repo and make changes to netdata-installer.sh to isolate the build logic away from the run logic. All I need is your blessing :)

Well, and opinion how to do it:

1. I can just add arguments: ./netdata-install.sh [build|run] (options)
2. I can split the script into: ./netdata-install, and ./netdata-run

It just depends on what you would like better.

Best,
Tit

**Comment by titpetric** [comment]
Or, since I'm doing this the ass-backwards way, maybe it's better to start with packaging netdata into a .deb, which would handle some things here (files, folders, permissions, users, ...). At least the install/run part is then standardized in some measure.

**Comment by titpetric** [comment]
FYI, working Dockerfile is up:

GitHub: https://github.com/titpetric/netdata
Docker Hub: https://hub.docker.com/r/titpetric/netdata/

I'm gonna close this issue, and continue in the Docker thread. Thank you.
