### ISSUE TITLE
Systemd documentation

### ISSUE THREAD

**Issue by deveth0** [firehol/netdata#410]
Hi,

I just wanted to add some hints on how to use the serviced scripts available in 
https://github.com/firehol/netdata/tree/master/system
````
killall netdata
cp netdata.service /etc/systemd/system/
service netdata start
systemctl enable netdata.service
````

Might be useful for others ;)

**Comment by ktsaou** [comment]
Thanks! I added this information at the installation page.

**Comment by ktsaou** [comment]
I close this. If you need more help, open it again...
