### ISSUE TITLE
how to use ceph.plugin?thx

### ISSUE THREAD

**Issue by taozi-xie** [firehol/netdata#4101]
I don't know how to add the ceph plugin to netdata and display it?Would you like to help me?thx

**Comment by lets00** [comment]
Hi @taozi-xie ,

Please, read this documentation to enable ceph plugin in your environment:
https://github.com/firehol/netdata/tree/master/python.d#ceph

**Comment by lets00** [comment]
@ktsaou I think that you can close this issue or add some tags to identify this like a **Question** (not a Issue).
