### ISSUE TITLE
some question about ceph.plugin

### ISSUE THREAD

**Issue by taozi-xie** [firehol/netdata#4102]
I want to use ceph.plugin to monitor the status of ceph cluster.I did something as the guide, such as change configuration
`

- local:
-   config_file: '/etc/ceph/ceph.conf'
-   keyring_file: '/etc/ceph/ceph.client.admin.keyring'

`

it works when I use the command "/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph",
return the ceph cluster status:
`

- 2018-09-04 17:31:24: python.d DEBUG: ceph: ceph: create() => [OK] (charts: 14)
- 2018-09-04 17:31:24: python.d DEBUG: ceph: ceph: started, update frequency: 10, retries: 60
- 2018-09-04 17:31:24: python.d DEBUG: ceph: ceph: sleeping for 7.4548007967 to reach frequency of 10 sec
- CHART ceph.osd_usage '' 'Ceph OSDs' 'KB' 'osd' 'ceph.osd_usage' line 60011 10 '' 'python.d.plugin' 'ceph'
- DIMENSION 'osd.0' 'osd.0' absolute 1 1 ''
- DIMENSION 'osd.1' 'osd.1' absolute 1 1 ''
- DIMENSION 'osd.2' 'osd.2' absolute 1 1 ''
- DIMENSION 'osd.3' 'osd.3' absolute 1 1 ''
- DIMENSION 'osd.4' 'osd.4' absolute 1 1 ''
- DIMENSION 'osd.5' 'osd.5' absolute 1 1 ''
- DIMENSION 'osd.6' 'osd.6' absolute 1 1 ''
- DIMENSION 'osd.7' 'osd.7' absolute 1 1 ''........

.`

But，when I  start the netdata server,the log shows :
`

- 2018-09-04 17:29:53: python.d ERROR: ceph: ceph: error connecting to the cluster
- 2018-09-04 17:29:53: python.d INFO: ceph: ceph: check() => [FAILED]

`

I don't know why? Would you like to help me solve the question? Much obliged for your assistance!
Thx!

**Comment by lets00** [comment]
Hi @taozi-xie,

Do you use sudo user to run ```python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph```?

In debug mode, the plugin is ok.

I think this error is related to permission about netdata user to access rados and ceph files. Please, confirm if you executed this step:

```
chmod 640 /etc/ceph/ceph.client.admin.keyring
```
You can see more information about ceph module in:
https://github.com/firehol/netdata/tree/master/python.d#ceph

**Comment by taozi-xie** [comment]
Thanks,it works.  The error is related to permission of the file /etc/ceph/ceph.client.admin.keyring, I use the command:

- chmod +r /etc/ceph/ceph.client.admin.keyring

Thx!
