### ISSUE TITLE
Raise an alarm when a docker container is unhealthy

### ISSUE THREAD

**Issue by tuxity** [firehol/netdata#4111]
Hello,

Would it be possible to add an alarm when a docker container is going (un)healthy (with docker health check)? 

I'm trying to understand how the system work to do it but it's not very clear for me. I should add the metric first ?

Thanks

**Comment by Ferroin** [comment]
You would need to be tracking this with a metric somehow to create an alarm for it.  I could actually see some practicality to having a graph that tracks the total number of 'unhealthy' Docker containers on a system as part of Netdata itself, at which point it would be trivial to add an alarm that fires if that value ever goes above 0.

**Comment by tuxity** [comment]
Okay, I understand a bit more. I’m going check that to add that metric and alarm then. 

Thank you, gonna update the ticket later

**Comment by tuxity** [comment]
I've started something very basic [here](https://github.com/MilleniumStudio/netdata/tree/docker)
I'm learning how the project works at the same time, so might be a bit ugly.

**Comment by Ferroin** [comment]
For the start of a plugin, it actually doesn't look too bad.  The only issue I see is that you've got a bunch of unrelated formatting changes in `python.d/README.md`.  The only other things I would change so far are stylistic and not functional problems, but those can wait until you have a working plugin.  Once you do get it working, feel free to submit a PR, I'll be happy to help review it.

**Comment by tuxity** [comment]
I'm kinda stuck, I don't understand why I can't use `DockerClient` class imported with `docker` module.
I guess it's maybe a conflict or modules paths not setted correctly 🤔

Last version: https://github.com/MilleniumStudio/netdata/blob/docker/python.d/docker.chart.py

**Comment by ktsaou** [comment]
@l2isbad @paulfantom please check this.

**Comment by paulfantom** [comment]
@tuxity some error logs would be nice

**Comment by tuxity** [comment]
@paulfantom 
```
2018-09-12 22:27:59: python.d ERROR: docker: local: ['/usr/libexec/netdata/plugins.d', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages', '/usr/libexec/netdata/python.d/python_modules']
2018-09-12 22:27:59: python.d ERROR: docker: local: check() unhandled exception: module 'docker' has no attribute 'DockerClient'
2018-09-12 22:27:59: python.d INFO: docker: local: check() => [FAILED]
```

**Comment by l2isbad** [comment]
yo @tuxity 

Nice error right here! :smile: 

You have to rename you module to import `docker`. You literally import your own module

https://github.com/MilleniumStudio/netdata/blob/b46ad211507f4de3d063c909bd0898ddd4fbd943/python.d/docker.chart.py#L5-L9

**Comment by tuxity** [comment]
DUH, that's what I thought...
The `docker` module is from https://github.com/docker/docker-py, so I should rename the files in netdata ? to which name ? `dockerd` `docker-daemon` maybe ?

**Comment by Ferroin** [comment]
`docker-daemon` wouldn't work because the file has to be importable in Python as a module, and identifiers in Python (and thus module names) can't have a `-` in them.

**Comment by l2isbad** [comment]
whatever you prefer (`docker.chart.py` -> `new_name.chart.py`)

**Comment by tuxity** [comment]
Okay, thank you guys.
I'm gonna update that, and keep you updated for a review.

**Comment by l2isbad** [comment]
> I'm gonna update that

it is not the only problem you have, to make it work do

1. remove `create_charts` method
2. add dimensions to the `CHARTS`, like

```python
    'running_containers': {
        'options': [None, 'Number of running containers', 'running_containers', 'running_containers', 'docker.running_containers', 'line'],
        'lines': [
            ['running_containers', 'running']
        ]
    },
```

3. return data `dict` from `get_data` (should be a simple `dict`, defaultdict not needed, as well as there is not reason to use instance attr for data ('self.data'))

**Comment by tuxity** [comment]
@l2isbad is everything is fix as you said, and it's working. I'm cleaning everything now.

You have ideas of some metrics I can at the same time ?

**Comment by tuxity** [comment]
Added in #4191
