### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by celliott113** [firehol/netdata#4119]
The experimental packages installer failed.

This is what it says:

celliott@hclus1-dev1-satx-us28:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Fetched 172 kB in 1s (130 kB/s)
Reading package lists... Done
celliott@hclus1-dev1-satx-us28:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
celliott@hclus1-dev1-satx-us28:~$ curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 18.04.1 LTS (Bionic Beaver)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 18.04

We detected these:
Distribution    : ubuntu
Version         : 18.04
Codename        : 18.04.1 LTS (Bionic Beaver)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2

The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:  sudo apt-get update

sudo apt-get install autoconf autoconf-archive autogen automake curl gcc git libmnl-dev lm-sensors make netcat nodejs pkg-config python python-mysqldb python-psycopg2 python-pymongo python-yaml uuid-dev zlib1g-dev

Press ENTER to run it >
sudo apt-get install autoconf autoconf-archive autogen automake curl gcc git libmnl-dev lm-sensors make netcat nodejs pkg-config python python-mysqldb python-psycopg2 python-pymongo python-yaml uuid-dev zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'netcat-openbsd' instead of 'netcat'
Package autoconf-archive is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package lm-sensors is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'autoconf-archive' has no installation candidate
E: Unable to locate package autogen
E: Package 'lm-sensors' has no installation candidate
E: Unable to locate package nodejs

We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues

celliott@hclus1-dev1-satx-us28:~$

please paste your screen here

```

**Comment by ktsaou** [comment]
Thank you for letting us know.
It is now fixed.
