### ISSUE TITLE
cgroup-names.conf

### ISSUE THREAD

**Issue by deveth0** [firehol/netdata#412]
Hi all,

I'm quite happy with my netdata installation, thanks for this awesome software!

Currently I try to figure out how to give my Container (lxc) more comprehensible names. As far as I understand, this should be done through using cgroup-names.conf which is called from cgroup-name.sh.
e.g. I have a Container called lxc_117 and added this to my conf:
````
lxc_117 foobar
````
running the script also returns the correct name:
````
root@proxmox:/etc/netdata# /usr/libexec/netdata/plugins.d/cgroup-name.sh lxc_117
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc_117' is called 'foobar'
````

but the WebUI does not use this name (still displays Container: lxc_101). Is there anything I miss or missunderstand here?

Thank you in advance!

**Comment by ktsaou** [comment]
Nice you like netdata! Thanks!

Check your `/var/log/netdata/error.log`. The names taken from cgroups normally have a prefix, like `lcx/container` or something similar. That one is the first column of `cgroups-names.conf`. netdata logs all runs of `cgroup-name.sh` so, the key you are looking should be in your logs.

**Comment by deveth0** [comment]
Ah thanks! The correct syntax was:
````
lxc/101 munin
````

**Comment by ktsaou** [comment]
ok, I am closing this. If you need more help open it again...

**Comment by ovizii** [comment]
doesn't work for me. Inside /etc/netdata/cgroup-names.conf I tried both of the following 

`lxc/100 = alfred
lxc/102 = bailey
lxc/104 = drake
lxc/105 = edgar
lxc/108 = mike
qemu.slice/103.scope = charles
qemu.slice/111.scope = jacob
`
as well as 
`lxc/100 alfred
lxc/102 bailey
lxc/104 drake
lxc/105 edgar
lxc/108 mike
qemu.slice/103.scope charles
qemu.slice/111.scope jacob
`

but I still do not see netdata picking up the names :-(

**Comment by ktsaou** [comment]
We are discussing this in #791
