### ISSUE TITLE
External Plugin collet path disk usage issue

### ISSUE THREAD

**Issue by phantazia** [firehol/netdata#4120]
Hi,

I'm trying to add python plugin to get disk usage consumption for a specific path 
I'm able to get the result (on the console) when I'm running the plugin with **netdata/plugins.d/python.d.plugin 1 debug trace app_space**  but it doesn't work with netdata service, I found this error on the error.log file 
`2018-09-06 08:04:13: netdata ERROR : PLUGINSD[python.d] : (0464@plugins_d.:pluginsd_proces): sent command '['171704\t/disk/myapp/data\n']' which is not known by netdata, for host 'mymachine'. Disabling it.`
Find below the plugin

```
import re
import sys
from bases.FrameworkServices.ExecutableService import ExecutableService

priority = 60000
retries = 60

ORDER = ['usage']

CHARTS = {
    'usage': {
        'options': [None, "Current App space usage", "node", "usage", "disk.usage", "line"],
        'lines': [
            ['usage', None, 'absolute']
        ]}
}

class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.command = '/usr/bin/du /disk/myapp/data -s'
        self.order = ORDER
        self.definitions = CHARTS

    def _get_data(self):
        """
        returns dict {unique_dimention_name -> value} or None
        """
        raw_data = self._get_raw_data()
        print(raw_data)
        if not raw_data:
            return None

        print("before ending")
        for line in raw_data:
            print("test")
        return {'usage': line.split("\t")[0] }
```
Thanks in advance

**Comment by ktsaou** [comment]
btw, keep in mind it is quite resource expensive what you are trying to do. Your system may be significantly influenced by this, depending on size of this directory. So, do not run this every second. I suggest to run it every 30 seconds or even more.

If this is a production server, I suggest to consider giving this path a different disk, or partition, so that the used/available disk space will be easily extracted.

**Comment by phantazia** [comment]
Thanks a lot for your quick response. it's just a draft, for production the frequency will be longer.
For allowing a specific disk/partition, I agree, we already planned this, but for that, we need to get the path consumption (queuing system), the disk usage is very versatile for this app, it's why we need this plugin

**Comment by phantazia** [comment]
Hi Ferroin,

Thanks a lot for your help, no more error now. I'm wondering why the result is not exposed through REST API (/api/v1/allmetrics)? It's not automatic, should I add something?

**Comment by ktsaou** [comment]
> Thanks a lot for your help, no more error now. I'm wondering why the result is not exposed through REST API (/api/v1/allmetrics)? It's not automatic, should I add something?

It should be. Is it collected? Do you have charts being refreshed with it? I guess you are not filtering metrics in the `[backend]` section of `netdata.conf`. Right?

**Comment by phantazia** [comment]
I think I missed a step, No chart also. I didn't update netdata.conf, it contains the default config. Should I add something?

**Comment by ktsaou** [comment]
Have you tried to check it works, outside netdata?
Here is how: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by phantazia** [comment]
yes, since the first version (with ExecutableService) it was working  with "/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace path_usage"

**Comment by ktsaou** [comment]
Could you please post the output of that trace, including the commands you run?
Did you run it in debug mode as user `netdata`?

**Comment by phantazia** [comment]
Sorry for the late replay
Please find below the output and the command
`-bash-4.2$ /opt/netdata/netdata-plugins/plugins.d/python.d.plugin debug trace 1 pathusage
2018-09-12 13:53:40: python.d INFO: plugin: main: Using python 3
2018-09-12 13:53:40: python.d DEBUG: plugin: main: module load source: 'pathusage' => [OK]
2018-09-12 13:53:40: python.d DEBUG: plugin: main: module load config: 'pathusage' => [OK]
2018-09-12 13:53:40: python.d DEBUG: plugin: main: job initialization: 'pathusage pathusage' => ['OK']
2018-09-12 13:53:40: python.d DEBUG: plugin: main: module status: 'pathusage' => [OK] (jobs: 1)
2018-09-12 13:53:40: python.d INFO: pathusage: pathusage: check() => [OK]
CHART netdata.runtime_pathusage '' 'Execution time for pathusage' 'ms' 'python.d' netdata.pythond_runtime line 145000 10
DIMENSION run_time 'run time' absolute 1 1

2018-09-12 13:53:40: python.d DEBUG: pathusage: pathusage: create() => [OK] (charts: 1)
2018-09-12 13:53:40: python.d DEBUG: pathusage: pathusage: started, update frequency: 10, retries: 60
2018-09-12 13:53:40: python.d DEBUG: pathusage: pathusage: sleeping for 1.3693228419870138 to reach frequency of 10 sec
MyApp Usage is :1075421185
MyApp Usage is :992712286
CHART pathusage.pathusage '' 'A random number' 'random number' 'random' 'random' line 90000 10 '' 'python.d.plugin' 'pathusage'
DIMENSION 'path1' 'path1' absolute 1 1 ''
DIMENSION 'path2' 'path2' absolute 1 1 ''

BEGIN pathusage.pathusage 0
SET 'path1' = 1075421185
SET 'path2' = 992712286
END

BEGIN netdata.runtime_pathusage 0
SET run_time = 13
END

2018-09-12 13:53:42: python.d DEBUG: pathusage: pathusage: update => [OK] (elapsed time: 13, retries left: 60)
2018-09-12 13:53:42: python.d DEBUG: pathusage: pathusage: sleeping for 9.978889172896743 to reach frequency of 10 sec
MyApp Usage is :1075432345
MyApp Usage is :992712286
BEGIN pathusage.pathusage 10007207
SET 'path1' = 1075432345
SET 'path2' = 992712286
END

BEGIN netdata.runtime_pathusage 10007207
SET run_time = 5
END`

**Comment by l2isbad** [comment]
Remove your prints.

> MyApp Usage is :1075421185
> MyApp Usage is :992712286

**Comment by phantazia** [comment]
It s working. Thank you all for your help

**Comment by ktsaou** [comment]
btw, if you want to print debug output, you should print to stderr, since stdout is processed by netdata.

**Comment by phantazia** [comment]
Yes, I missed this point. Thank you
