### ISSUE TITLE
Swap analysis - enhancement request

### ISSUE THREAD

**Issue by 74cmonty** [firehol/netdata#4123]
Hi,
I have sometimes issues with swapping.
My understanding is that most critical with regards to swapping is which process is reading in/out of swap.
The total allocated swap size is of less importance.

In order to see which process is allocating memory in swap I use this query (as root) on a server that shows 100% swap allocation:
```
root@ld4257:~# free -h
              total        used        free      shared  buff/cache   available
Mem:            62G         10G        400M        145M         51G         51G
Swap:          8,0G        8,0G          0B

root@ld4257:~# (echo "COMM PID SWAP"; for file in /proc/*/status ; do awk '/^Pid|VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | grep kB | grep -wv "0 kB" | sort -k 3 -n -r) | column -t | head -20
COMM             PID           SWAP
kvm              2764201       1451548  kB
kvm              3825563       529548   kB
kvm              3436825       443928   kB
pvedaemon        2040775       93332    kB
pvedaemon        worke588021   78192    kB
pvedaemon        worke601705   77936    kB
pvedaemon        worke594032   76580    kB
pve-ha-crm       2986637       67708    kB
pve-ha-lrm       2986565       56468    kB
ceph-osd         1900720       41084    kB
ceph-osd         1900723       40508    kB
pvestatd         3118          38248    kB
pve-firewall     3119          36948    kB
ceph-mgr         1902937       22496    kB
ceph-mon         1900649       6580     kB
pmxcfs           2040721       3000     kB
influxd          3166611       1008     kB
fail2ban-server  2695          992      kB
sssd_ssh         1878          836      kB

```

Can you consider to enhance the monitoring functionality with something similar?

THX

**Comment by ktsaou** [comment]
Hi, it is already there:

![image](https://user-images.githubusercontent.com/2662304/45188201-14b52d80-b23c-11e8-8d0f-b711c33200a4.png)

In the "Applications", "Users" and "User Groups" sections of the dashboard.
If you need to include specific apps in the dimensions of the charts, you can edit this file: https://github.com/firehol/netdata/blob/master/conf.d/apps_groups.conf (as `/etc/netdata/apps_groups.conf`).

**Comment by 74cmonty** [comment]
great!
