### ISSUE TITLE
Disk usage missing for some disks

### ISSUE THREAD

**Issue by metasikander** [firehol/netdata#4124]
I have a digital ocean droplet with an extra block storage disk mounted in /mnt/ (from /dev/disk/by-id/) that is not showing up with usage statistics in netdata.
here's a dump from the api (the mountpoint is named sunnyvolume): https://gist.github.com/metasikander/6a8ef982f8e2412824335e1bcbe8c61a
is there something i can do to make sure it shows up in netdata?

**Comment by ktsaou** [comment]
Hi, 

could you please post the output of this:

```sh
curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[.*diskspace.*]/,/^$/p'
```

and the output of this:

```sh
cat /proc/self/mountinfo 
```

**Comment by metasikander** [comment]
Here you go

> curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[.*diskspace.*]/,/^$/p'

https://gist.github.com/metasikander/e670ba71a92aebe175bb17676a136c14

> cat /proc/self/mountinfo

https://gist.github.com/metasikander/a3d70ecd4464146cb334337e47032785

**Comment by ktsaou** [comment]
I should be showing. I think you are running an old version of netdata. Which version do your run?

**Comment by metasikander** [comment]
Yes that's it!
I installed it from the ubuntu repo, which is v 1.9.0.
So I uninstalled that now, and ran the installation-script instead, and now with the newest version it works.
Thank you!

**Comment by paulfantom** [comment]
Another issue which would be non-existent if we were packaging netdata ourselves. I am starting to collect those :smile:

**Comment by ktsaou** [comment]
Ooops! how it was masked?

Let me search for it: https://askubuntu.com/questions/710420/why-are-some-systemd-services-in-the-masked-state

> mask is a stronger version of disable. Using disable all symlinks of the specified unit file are removed. If using mask the units will be linked to /dev/null. This will be displayed if you check e.g. by systemctl status halt.service. The advantage of mask is to prevent any kind of activation, even manual.

hm...

**Comment by ktsaou** [comment]
I tried on ubuntu to install netdata from package and then remove it. Once it was removed, netdata was left as masked in systemd. So, this is done by the package manager when it removes packages.

I don't think we should touch this. If netdata is masked, only the user should unmask it by hand. Otherwise we risk our updater to unmask netdata, even when the user wants it masked.

**Comment by paulfantom** [comment]
> If netdata is masked, only the user should unmask it by hand

That is exactly how masking/unmasking should be handled. I just wonder why ubuntu masks service when it removes package.

**Comment by paulfantom** [comment]
Masked doesn't stop service it is a measure to disallow enabling service.
