### ISSUE TITLE
docker mount folder with "-v /home/netdata:/etc/netdata" but there is nothing.

### ISSUE THREAD

**Issue by zaywalker** [firehol/netdata#4125]
hello. first of all, thanks for the awesome system monitor.

and sorry about this noob question.

I'm using netdata with docker and it works fine. but I need to tune some charts so I did,

`sudo docker exec -it netdata /bin/bash`

and I modify some /etc/netdata.

and I guess, it would be easier to run docker mount with config folder "/etc/netdata"

so, I ran docker like this. (actually, I use docker portainer webui. I just assume command like below)

```
sudo docker run -d \
--restart unless-stopped \
--name netdata \
-v /sys:/host/sys \
-v /proc:/host/proc \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /home/netdata:/etc/netdata \
firehol/netdata
```

unfortunatly, in /home/netdata, there is empty.

please any help and advice?!

**Comment by paulfantom** [comment]
> unfortunatly, in /home/netdata, there is empty.

You mounted empty directory from host over one inside container. In this case you need to provide your own config in `/home/netdata`. More info: https://docs.docker.com/storage/volumes/

**Comment by zaywalker** [comment]
Oh. I see. I hope netdata generates some config files if these are missing :) Thanks for the answer!

**Comment by ktsaou** [comment]
So, netdata does not start if `netdata.conf` is missing?

**Comment by paulfantom** [comment]
> I'm using netdata with docker and it works fine. but I need to **tune some charts** so I did, 

:smile:

**Comment by nemchik** [comment]
Sorry to necro this, it may deserve it's own issue, but it seems like there's a number of `.conf` files that might normally be editable on an install directly to a system but cannot be changed when running netdata in docker. It would be VERY beneficial if the `.conf` files could be put in a `/config` volume or something similar and automatically created if missing.

**Comment by paulfantom** [comment]
@nemchik we are working towards different mechanism of loading config files (similar to how systemd loads its service files). This should also solve your issue. Right now you can use docker to mount your own files over netdata ones, same way as you mount volumes.

**Comment by nemchik** [comment]
So for now it's advised to make a volume for each `.conf` file in `/etc/netdata`? If I'm doing this and the container is being created for the first time and the volumes (`.conf` files) don't exist would they be created?

**Comment by ktsaou** [comment]
> So for now it's advised to make a volume for each `.conf` file in `/etc/netdata`? If I'm doing this and the container is being created for the first time and the volumes (`.conf` files) don't exist would they be created?

I think you need to map `/etc/netdata` to a directory of yours; `-v /home/netdata:/etc/netdata` does that I think.

**Comment by paulfantom** [comment]
You can either map everything like @ktsaou says, or if you want to change just some files, then map only those files.

Volume mounting in docker is quite flexible, and yes it will "create" files. For example using such syntax:
```
-v /home/me/some_config.conf:/etc/netdata/some_config.conf
```
Will mount file `/home/me/some_config.conf` as a `/etc/netdata/some_config.conf` and it doesn't matter is a file existed previously inside a container. It doesn't even matter if a dir exists, it will create whole path.

**Comment by nemchik** [comment]
The reason I asked is it seemed like if i were to use `-v /home/netdata:/etc/netdata` and `/home/netdata/netdata.conf` does not exist on the host the first time the container is run it sounds like it won't start up. I suppose I can give this a shot right now.

**Comment by paulfantom** [comment]
Yes, because you over-mounted whole directory.

**Comment by paulfantom** [comment]
Try this exercise (no docker required):
1. Create a directories: `/mnt/A` and `/mnt/B`
2. Create some files in `/mnt/A`, like for example `/mnt/A/some_file`
3. Bind mount `/mnt/B` over `/mnt/A`, like `mount --bind /mnt/B /mnt/A`
4. Go to `/mnt/A`, do you see `some_file` there?

That's a simplification of how volumes work in docker.

**Comment by paulfantom** [comment]
As for recreating configuration files on first run, it is just wrong. That's what default values embedded inside an app or even better in `/lib` are for.

**Comment by nemchik** [comment]
I'm going to assume in step 4 above you would NOT see `some_file` although I haven't double checked right this moment. I have done similar things in the past when first messing around with how mount works.

That being said I have created a volume `- ${DOCKERCONFDIR}/netdata:/etc/netdata` in my compose file and netdata seems to start fine, but that folder remains empty. I assume the `.conf` files in that folder are only used if found?
