### ISSUE TITLE
error: cannot take the address of an rvalue of type 'FILE *' when building on OpenBSD

### ISSUE THREAD

**Issue by williamleuschner** [firehol/netdata#4145]
On [line 137 of log.c](https://github.com/firehol/netdata/blob/master/src/log.c#L137) (and a few lines after that), netdata tries to get the address of `stdout` and co., which is a compilation error on OpenBSD (see issue title), and is [not technically within C specifications](http://openwall.com/lists/musl/2018/02/02/2).

I have some experience developing in C and could probably put a patch together which uses freopen(3), as suggested by the musl developer in the mailing list link above. Should I investigate patching it myself, or is this a trivial enough change that you'd rather just do it yourself?

**Comment by ktsaou** [comment]
Hi, could you please test PR #4149  ?

**Comment by ktsaou** [comment]
btw, it works on Linux, and it does not get the address of `FILE *` anymore.

**Comment by ktsaou** [comment]
Well, it turns out it does not work on a few versions of gcc/Linux:

```
log.c: In function 'reopen_all_log_files':
log.c:142:16: error: assignment of read-only variable 'stdout'
         stdout = open_log_file(STDOUT_FILENO, stdout, stdout_filename, &output_log_syslog, 0, NULL);
                ^
log.c:145:16: error: assignment of read-only variable 'stderr'
         stderr = open_log_file(STDERR_FILENO, stderr, stderr_filename, &error_log_syslog, 0, NULL);
                ^
log.c: In function 'open_all_log_files':
log.c:153:11: error: assignment of read-only variable 'stdin'
     stdin = open_log_file(STDIN_FILENO, stdin, "/dev/null", NULL, 0, NULL);
           ^
log.c:155:12: error: assignment of read-only variable 'stdout'
     stdout = open_log_file(STDOUT_FILENO, stdout, stdout_filename, &output_log_syslog, 0, NULL);
            ^
log.c:156:12: error: assignment of read-only variable 'stderr'
     stderr = open_log_file(STDERR_FILENO, stderr, stderr_filename, &error_log_syslog, 0, NULL);
            ^
```

So, even the `freopen()` method is not valid.

**Comment by ktsaou** [comment]
If you check the code, it attempts to change the level-1 file (fd) and use `dup2()` to copy the new file descriptor to the location required by `stdXXX` (so 1 for stdin, 2 for stdout, 3 for stderr). This way it manages to reopen the file without changing `stdXXX`.

The whole point for passing the address of `FILE *` was only for `stdaccess` (the access.log of netdata).
So I updated the code to prevent it from attempting to set `stdXXX`, except `stdaccess`.

**Comment by williamleuschner** [comment]
Thanks! The patch from PR #4149 makes `log.c` build successfully. Next up, `threads.c`…
