### ISSUE TITLE
python clocks don't work under FreeBSD

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#4152]
From https://github.com/firehol/netdata/pull/3776#issuecomment-416839935

Commit 20bbce31336b860af48a918046b7defd31be5ee8 seems to break Python plugins on FreeBSD; at least on this system:
```
$ uname -mrs 
FreeBSD 10.4-RELEASE-p10 amd64
$ python --version
Python 2.7.15
```

After updating to the latest git version, python plugins no longer returned data (neither when running from netdata, nor when running directly in debug mode) (this isn't 100% true - once in a while (several minutes) a record is returned). I narrowed the problem down to the mentioned commit, reverting it makes the plugins run fine again.

Researching a bit more revealed that FreeBSD is using different constants for CLOCK_MONOTONIC (from /usr/include/time.h): 
```
#define CLOCK_VIRTUAL   1
//...
#define CLOCK_MONOTONIC 4
```

So the Python code is now using CLOCK_VIRTUAL, which is defined as "for time that increments only when the CPU is running in user mode on behalf of the calling process". The old value 4 was actually good on FreeBSD, because it referenced CLOCK_MONOTONIC.

**Comment by l2isbad** [comment]
I think we can use https://github.com/atdt/monotonic/blob/master/monotonic.py
