### ISSUE TITLE
Print Min Max avg and current leyend on dygraph chart

### ISSUE THREAD

**Issue by fnonino** [firehol/netdata#4195]
Hi! 
i just create a simple netdata page, with banwith and packet data of some interfaces of my server
i want to show max min and avg and current chart data, not only current.
is it possible? how?
here is my litle code

<div style="width: 80%; height: 600px; text-align: center; display: inline-block;">

            <div data-netdata="net.eth0"
                    data-title="Trafico"
                    data-append-options="absolute" 
                    data-chart-library="dygraph" 
                    data-width="100%"
                    data-height="100%"
                    ></div>
        </div>
        <div style="width: 80%; height: 600px; text-align: center; display: inline-block;">
            <div data-netdata="net_packets.eth0"
                    data-title="Paquetes"
                    data-append-options="absolute" 
                    data-dimensions="received|sent"
                    data-chart-library="dygraph"
                    data-width="100%"
                    data-height="100%"
                    ></div>
        </div>

thanks a lot

**Comment by ktsaou** [comment]
If you want to do it without javascript, add a badge. https://github.com/firehol/netdata/wiki/Generating-Badges

**Comment by ktsaou** [comment]
btw, we plan to enhance the charts, to show a lot more info. Even the "volume" of dimensions.

**Comment by fnonino** [comment]
Excelent!
Badges solved the case
you can close this 
Thanks a lot!
