### ISSUE TITLE
UTC Timezone

### ISSUE THREAD

**Issue by nathanila** [firehol/netdata#4202]
Please allow for picking a server timezone of UTC

**Comment by paulfantom** [comment]
Please provide more information.

**Comment by ktsaou** [comment]
@nathanila I guess you mean on this list:

![image](https://user-images.githubusercontent.com/2662304/45592065-1ed9d900-b96c-11e8-9565-9883cbc5fac6.png)

Right?

**Comment by ktsaou** [comment]
Generally, UTC is Europe/London, but yes, there should be a separate entry for UTC.

**Comment by paulfantom** [comment]
> UTC is Europe/London

For only half of the year.

**Comment by nathanila** [comment]
@ktsaou Yes, that is the right image.

**Comment by ktsaou** [comment]
ok, added it.

**Comment by ktsaou** [comment]
merged it.
Just update and you will have it.
