### ISSUE TITLE
redis.chart.py stops with error "check() unhandled exception: 'rdb_bgsave_in_progress'"

### ISSUE THREAD

**Issue by ossjet** [firehol/netdata#4204]
Hey there!

I have a liitle problem with `redis.chart.py` plugin. Here it is:

```
# NETDATA_CONFIG_DIR=/etc/netdata `which python` -d /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin redis debug 1 2>&1 | tail -4

2018-09-16 01:29:06: python.d ERROR: redis: localipv4: check() unhandled exception: 'rdb_bgsave_in_progress'
2018-09-16 01:29:06: python.d ERROR: redis: localipv4: check() => [FAILED]
2018-09-16 01:29:06: python.d INFO: plugin: main: FINISHED
```
I noticed that `rdb_bgsave_in_progress` is not presented in the `INFO` command output:
```
~# redis-cli -v
redis-cli 2.4.14

# echo INFO | redis-cli 
redis_version:2.4.14
redis_git_sha1:00000000
redis_git_dirty:0
arch_bits:64
multiplexing_api:epoll
gcc_version:4.6.2
process_id:982
uptime_in_seconds:5586425
uptime_in_days:64
lru_clock:611508
used_cpu_sys:775.17
used_cpu_user:1654.56
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
connected_clients:1
connected_slaves:0
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
used_memory:727704
used_memory_human:710.65K
used_memory_rss:1007616
used_memory_peak:761864
used_memory_peak_human:744.01K
mem_fragmentation_ratio:1.38
mem_allocator:jemalloc-2.2.5
loading:0
aof_enabled:0
changes_since_last_save:0
bgsave_in_progress:0
last_save_time:1531449618
bgrewriteaof_in_progress:0
total_connections_received:44029
total_commands_processed:5416672
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
vm_enabled:0
role:master
```

I guess that is the reason.

Sadly, I do not have any skills in Python. That means I cannot fix this problem in the right way by myself. By the way, plugin started to work normally when I commented out these lines in `redis.chart.py` file:

```
#        if data['rdb_bgsave_in_progress'] != '0\r':
#            self.bgsave_time += self.update_every
#        else:
#            self.bgsave_time = 0
#
#        data['rdb_last_bgsave_status'] = 0 if data['rdb_last_bgsave_status'] == 'ok\r' else 1
#        data['rdb_bgsave_in_progress'] = self.bgsave_time
```

Because of that, it is working in forever cycle as we need.

---
Problem found in Netdata 1.9, but as I can see, `redis.chart.py` is identical to that of current Netdata release 1.10.

P.S. Before posting this issue I have double searched for that problem in current ones and did not found any mention about it.

**Comment by paulfantom** [comment]
I would advise you to update your infrastructure as redis 2.4.14 is archaic (it is so old that it isn't even shown in http://download.redis.io/releases/).

But back to the subject, temporary solution would be to wrap this line: https://github.com/firehol/netdata/blob/c1be3331aa7acc209d5c3232ddb13c10900d50c0/python.d/redis.chart.py#L194-L195

in try...except block. Like this:
```py
if data.get('redis_version'):
    try:
        self.get_data_redis_specific(data)
    except:
        pass
```

For more @l2isbad could probably help :smile:

**Comment by l2isbad** [comment]
thx for reporting @ossjet

**Comment by ktsaou** [comment]
merged the fix.
