### ISSUE TITLE
ERROR 101

### ISSUE THREAD

**Issue by nikosp7** [firehol/netdata#4212]
After the update of 17-Sep-2019 I get the following error on a site with an embedded netdata chart :

ERROR 101: Cannot load jQuery: http://myserver:19999/dashboard.js/lib/jquery-2.2.4.min.js

**Comment by ndom91** [comment]
Same here - all external charts no longer working

**Comment by egrinant** [comment]
Had the same error. Just append ?v20170724-1 to the url to your netdata.js and it will be working again.

`<script type="text/javascript" src="dashboard.js?v20170724-1"></script>`

**Comment by ndom91** [comment]
@egrinant thanks - worked on one of my pages with custom dashboards. Can't get it to work on my second page however

**Comment by nikosp7** [comment]
thank, it worked

**Comment by ktsaou** [comment]
Sorry... my fault.
Just fixed it.
