### ISSUE TITLE
Use netdata secure

### ISSUE THREAD

**Issue by Tallerik** [firehol/netdata#4225]
Is there a way to restrict access on netdata which is running on default server(port=19999)?

Thanks

**Comment by ktsaou** [comment]
Keep in mind that if you can run netdata behind another web server, you can set all the above settings to `localhost` and configure an nginx, an apache, or another web server for access control.

The wiki has pages with configuration instructions for the most popular web servers.

**Comment by Tallerik** [comment]
Thanks that help.
