### ISSUE TITLE
Can I use tomcat plugins to monitor multi tomcat instances with different ports, e.g. 8080, 8090, 9100?

### ISSUE THREAD

**Issue by lonelyhsu** [firehol/netdata#426]
as title

**Comment by ktsaou** [comment]
@jgeromero could you please help?

**Comment by jgeromero** [comment]
Pull request #429 allows monitoring of a single tomcat instance on any port other than the default 8080. Monitoring of multiple instances (on different ports) within the same plugin is something I will have to look into later on. For now, what @lonelyhsu can do is make a copy of plugin for each of the instances he/she would like to monitor. i.e. tomcat.chart.8090.sh tomcat.chart.8080.sh etc..

**Comment by lonelyhsu** [comment]
@jgeromero thanks for your prompt reply.
I've tried what you suggested, it did work with 1 plugins, but when I tried to use multiple plugins, I'm not able to see all the data at the same time, i.e. in Netdata dashboard I can't see data from tomcat.chart.8090 and tomcat.chart.8080 at the same time.
Is there anything that needs to be configured if I'd like to use this way?

**Comment by simonnagl** [comment]
I think renaming this way will not work. As described on https://github.com/firehol/netdata/wiki/General-Info---charts.d files need to be named `<filename>.chart.sh and and functions and variables in the plugin need to start with `<filename>_`. Renaming all this should work. I have not tested it.

**Comment by jgeromero** [comment]
I've corrected my example above, thanks @simonnagl. Yes, all of that should be renamed to monitor multiple instances.

**Comment by ktsaou** [comment]
You have to rename:

1. filename `*.chart.sh`
2. functions and global variables (if you don't do this, the second plugin will overwrite the code of the second, so only one set will be collected, twice).
3. The first argument to `CHART` and `BEGIN` lines (if you don't do this, both plugins will update the same charts).

**Comment by lonelyhsu** [comment]
It works.
Thanks for your great support.

![image](https://cloud.githubusercontent.com/assets/16219830/15492190/28c29516-21ab-11e6-9e59-9bf54fbc19c0.png)
![image](https://cloud.githubusercontent.com/assets/16219830/15492205/56ef6dc4-21ab-11e6-92c7-c0f1dc034862.png)

**Comment by paulfantom** [comment]
Basically problem is resolved with `python.d.plugin`.

Close?

**Comment by ktsaou** [comment]
Yes, I marked it as fixed. I am closing this. Please test, if you have any problems just post.
