### ISSUE TITLE
1.2.0 fails to build the debian package

### ISSUE THREAD

**Issue by jsveiga** [firehol/netdata#427]
The changelog file is missing from contrib/debian; the build fails with:

tail: cannot open ‘debian/changelog’ for reading: No such file or directory
dpkg-buildpackage: error: tail of debian/changelog gave error exit status 1

I've added a symlink (...netdata/contrib/debian# ln -s ../../ChangeLog changelog), but it the fails because the ChangeLog is not in a debian-changelog parseable format.

I've fixed the format, but then it fails with:

dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-math --with-webdir=/var/lib/netdata/www returned exit code 1
debian/rules:20: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 255
make[1]: Leaving directory '/home/jsveiga/firehol/netdata'
debian/rules:9: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

EDIT: ok, the build failure was apparently due to a missing uuid-dev package. So the problem is just the changelog.

**Comment by philwhineray** [comment]
Can you try to run the failing configure step from the .deb build manually,
so we can see the output? I don't think it's related to the changelog
problem.

The changelog is now supposed to be autogenerated but it looks like I
didn't handle the scenario of using a clean git repo: sorry.

For now you can choose to use your version, download a pre-packaged tarfile
which will have the changelog included, or generate one in the git repo
before doing the build of the .deb. This should do the latter:

./autogen.sh
./configure
make -C contrib debian/changelog

Then whatever you normally do e.g.:

ln -s contrib/debian
dpkg-buildpackage -us -uc -rfakeroot

**Comment by philwhineray** [comment]
Or to avoid the autogen and configure steps, this should work to
generate the changelog instead:

make -C contrib -f Makefile.am debian/changelog PACKAGE_VERSION=`awk
-F'[][]' '/defi.*VERSION_.*\])/ {printf "." $4}' configure.ac | sed -e
's/^\.//' -e 's/\._/_/'`

**Comment by jsveiga** [comment]
Hi, thanks! The build failure (after I changed the changelog) was just because of the missing uuid-dev; it was indeed unrelated to the changelog issue.

**Comment by paulfantom** [comment]
Is this solved?

**Comment by jsveiga** [comment]
Yes! I've been updating my debian install since then by generating the
.deb. Thanks!
