### ISSUE TITLE
POLL: which is the feature we should implement next?

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#436]
Just like the comments below

(I added one like to make the buttons available - please don't comment in this issue)

**Comment by ktsaou** [comment]
## longer data history

find ways to compress, dedup, reduce or whatever necessary to have at least a week of data in netdata.

**Comment by ktsaou** [comment]
## dashboard snapshots

allow taking snapshots of timeframes, that can be loaded back for further examination
#309

**Comment by ktsaou** [comment]
## multi-server dashboards

using the registry features #416 allow dynamic cross-server dashboards to be created and work towards making netdata a master piece for multi-server performance monitoring

**Comment by ktsaou** [comment]
## health monitoring / alarms / alerts / notifications

add health monitoring features to netdata and create the central health monitoring system
#318

**Comment by ktsaou** [comment]
## dashboard editor

allow creating custom dashboards directly from the web front end

**Comment by Yenthe666** [comment]
Hi @ktsaou just my five cents here as a new person that just discovered Netdata (also congratz on this amazing software!):
 - It would be great to have the installation automatically creating an automatic `daemon`
 - The ability to create dashboards from the website is a major plus, this means no longer having to edit and create files from the command line.
 - Alarms and notifications would be awesome, especially if they could be sent to a push notification client for example.

**Comment by ktsaou** [comment]
> It would be great to have the installation automatically creating an automatic daemon

I would love to understand what this means for you. Can you open a new issue to describe it?

**Comment by Yenthe666** [comment]
@ktsaou explained the raw details here https://github.com/firehol/netdata/issues/438.
Also: It would be great if data was stored in database such as `postgreSQL`.

**Comment by rvanrootselaar** [comment]
- historic data

**Comment by ktsaou** [comment]
> historic data

This is what I thought too and this is why I wrote it first. However, as you can see most users need health monitoring before that. Let's see how it ends. I'll leave running for a few more days...

**Comment by rvanrootselaar** [comment]
Looking at it a little closer with a programmer colleague of mine we think that a pause button would even be better than historic data and probably be easier to realize. So just being able to keep the 1 hour view as it is without losing data past 1 hour ago (and not getting any new data). This means when a performance issue takes place and lasted, say a couple of minutes, you have more than one hour to analyse and look at the event before you lose all the data on it. Congrats on a really nice product by the way.

**Comment by ktsaou** [comment]
> Looking at it a little closer with a programmer colleague of mine we think that a pause button would even be better than historic data and probably be easier to realize. So just being able to keep the 1 hour view as it is without losing data past 1 hour ago (and not getting any new data). This means when a performance issue takes place and lasted, say a couple of minutes, you have more than one hour to analyse and look at the event before you lose all the data on it.

Snapshots #309 is probably a better alternative to this. Using snapshots you don't pause data collection, but you save the timeframe you are interested. The saved snapshot could be loaded back to be analyzed and will be kept until you delete it.

Snapshots can also have a "killer feature": compare the current data against the snapshot data and present the differences, sorted by max difference. This way you could quickly find out that your disk is getting twice as many IOPs, you database is having twice as many slow queries, etc.

**Comment by HuangShaoyan** [comment]
Allow using apt-get to install netdata on Debian and Ubuntu.

**Comment by fnzv** [comment]
Storing data for retention on a backend like Elasticsearch, so it's also possible to send alerts & full text search

**Comment by jasonsoul** [comment]
Hi @ktsaou ,
I have to say it's a great project it work perfectly with my Synology NAS.
Just wondering to know if there's any plan to monitor disk temperature?
Thanks

**Comment by ktsaou** [comment]
> Just wondering to know if there's any plan to monitor disk temperature?

Well, it can be easily done. I resisted to the idea since a few disks lead to corruption if you access SMART while they are writing. You can write a plugin in BASH for that. Check the `charts.d` directory. Pick an example chart and modify it to call `hddtemp`. If you need help, open a new issue and I'll help.

**Comment by nixfu** [comment]
Move away from using the build scripts as installer.  Build binaries and install packages, then use the install packages for the installation not the build scripts.

**Comment by paulfantom** [comment]
@jasonsoul monitoring disk temperatures is already implemented (#511).
@nixfu @HuangShaoyan I am working on using [OBS](https://build.opensuse.org/) as a build and distribution platform.

**Comment by tx7** [comment]
Can you add CPU temp to the system overview?

**Comment by paulfantom** [comment]
@tx7 aren't CPU temperatures monitored by `sensors.chart.sh` plugin?

**Comment by tx7** [comment]
I'm not sure.

**Comment by paulfantom** [comment]
@tx7 [Documentation](https://github.com/firehol/netdata/tree/master/charts.d#sensors) say it can.

**Comment by tx7** [comment]
So, I need to modify the codes in ` /etc/netdata/sensors.conf  ` ?

# the directory the kernel keeps sensor data
sensors_sys_dir="${NETDATA_HOST_PREFIX}/sys/devices"

# how deep in the tree to check for sensor data
sensors_sys_depth=10

# if set to 1, the script will overwrite internal
# script functions with code generated ones
# leave to 1, is faster
sensors_source_update=1

# how frequently to collect sensor data
# the default is to collect it at every iteration of charts.d
sensors_update_every=

# array of sensors which are excluded
# the default is to include all
sensors_excluded=()`

**Comment by paulfantom** [comment]
@tx7 It should work out-of-the-box. If it is not working add `sensors=yes` to `/etc/netdata/charts.d.conf`.
When it still doesn't work, maybe you have some strange sensors, check if `sensors` command gives you some output. 
And if it still doesn't work, open an issue and we will try to resolve it.

**Comment by ktsaou** [comment]
netdata finds sensors with this:

```sh
find /sys/devices -maxdepth 10 -name \*_input -o -name temp
```

on my laptop it gives this:

```sh
# find /sys/devices -maxdepth 10 -name \*_input -o -name temp
/sys/devices/virtual/hwmon/hwmon0/temp1_input
/sys/devices/virtual/thermal/thermal_zone0/temp
/sys/devices/virtual/thermal/thermal_zone1/temp
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp3_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input
/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp2_input
```

**Comment by tx7** [comment]
I checked, the sensors are working.
I'm thinking to put a CPU temp in the system overview as quick glance.

**Comment by ktsaou** [comment]
As requested, I have developed health monitoring!

It is in testing phase.

If you are interested to join the beta testers, join the discussion on PR #775

**Comment by shadycuz** [comment]
@ktsaou Where are we at on this? I'm currently looking through things with the your help needed label trying to stay busy. Should you close and reopen this topic for another round of feature voting? I think health alarms are out of "Beta" testing but I know they are currently being expanded and improved.

**Comment by ktsaou** [comment]
Alarms are still missing a few key features:

1. central notifications, which will also provide alarms/notifications in a case a server crashes and provide a few new notification methods, like centralised web browser notifications for servers that their dashboard is not open. It will also provide the basics for having a chat bot interacting with all our netdata installs.
2. a better UI at the dashboard.
3. ability to setup and dismiss alarms from the dashboard, which however depends on authentication.

I think however it is time to work on the dashboard a bit more. I would like to move all documentation at the netdata dashboard and at the same time implement a few features related to the second winner of the poll: multi-server dashboards.

Another solution could be to implement authentication now (make netdata an OAUTH2 provider, so that all our netdata installs will use that one for authentication).

I don't know yet. My schedule is very tight, so I think I will just provide small improvements for this month.
