### ISSUE TITLE
Automatic daemon creation on installation

### ISSUE THREAD

**Issue by Yenthe666** [firehol/netdata#438]
Hi @ktsaou,

As you've asked in the other topic I'll write out what I'd love to see in netdata.
At this point when you install Netdata through the Wiki everything will be fine and working, untill you reboot the server. After the reboot you will have to manually restart your Netdata with `sudo /usr/sbin/netdata` for example.
However, wouldn't it be nice if the daemon could be created by the system on installation or through a script?
I did something along these lines for another software that didn't have this too (named Odoo). You can find an example here: https://github.com/Yenthe666/InstallScript/blob/All/odoo_install.sh#L156-L236

The idea is to create a init / daemon file through a `.sh` file, which is eventually added to the `rc.d` system with `sudo update-rc.d $OE_CONFIG defaults`.

I know my script / idea isn't perfect but I'm sure you can figure out an even nicer way to have this added on the system by default. This would save quite some time.

**Comment by Yenthe666** [comment]
@ktsaou,

To further expand on this: at this point I had to move `/system/netdata-init-d.in` to `/etc/.init.d` (and I named it `netdata.conf`) and then had to run `sudo update-rc.d netdata.conf defaults`, just to get a Daemon up and running. I'm sure we could automate this?

On a sidenote: after I've done this and check out the Daemon I get the following issue:
![image](https://cloud.githubusercontent.com/assets/6352350/15454504/6d32d638-203a-11e6-93aa-7da8282c335a.png)

Not sure if this is my fault or not though.

**Comment by ktsaou** [comment]
This need some work in order to be automated. Some systems use systemd, others user init.d, a few more use openrc.

netdata provides init scripts for all of them. They are in the `system/` directory. Don't use the `.in` files. When you build netdata, you will also have the same files without `.in`. These are the ones you need.

The installation page describes the steps to get them installed: https://github.com/firehol/netdata/wiki/Installation#starting-netdata-at-boot

**Comment by ktsaou** [comment]
Regarding your suggestion to save netdata metrics to a relational db such as postgres, I am afraid this cannot be done. Netdata collects from 1.000 to 5.000 metrics per second per server. Do the math. The postgres installation you are going to need is huge for just a week of data. Not to mention that it will have constantly 1.000-5.000 queries per second.

There are dedicated databases for this kind of data, like opentsdb, influxdb, etc. Even on these dbs though, the amount of data netdata generates will stress them significantly and they will need dedicated hardware, proper configuration, etc.

The idea with netdata is to collect as many metrics as possible. To be free to collect anything you like, even if it is does not seem required initially. And this has to be done in a way that the resources required should be ignorable.

**Comment by simonnagl** [comment]
Also regarding to the suggestion to save netdata metrics to a relational db:

I think this can be done. Of course the facts @ktsaou mentioned are true. Putting the data with one query per chart and dimension to the database might not work.

Anyways we could have a plugin to export data of snapshots (#309) to a relational db.

Although we could provide configuration options to output CSV files with the data of a time interval in conjunction with import scripts for relational databases.
For example `netdata` would output the new data every half our and triggers the database to input this data.

On the other hand, like @ktsaou said, there are dedicated databases for this kind of data.

**Comment by Yenthe666** [comment]
Hi @ktsaou and @simonnagl,

Regarding the automatic Daemon: Yes it requires quite some work, such as figuring out on which system the user is at first and so on. But, the very big plus side is that this makes the monitoring software a **lot** easier. I see this monitoring tool as a tool for the less tech people that still want to know a lot about the system. I for one had to figure out how to configure this automatic boot of Netdata, which was my only downside so far.
I know it requires some work but eventually it will help a lot of people and your software will become much easier to use.

Regarding the database: I do agree that storing 1.000 to 5.000 records per second requires quite a big and strong database and will eventually probably still give issues. But, why not make it configurable to save the data you wish in the database? In my example I would like to have a long term history of the CPU cycles, memory limit and network but _not_ about all of those 5.000 metrics. Why don't we create a possibility to store parts of the data, configurable by the end user? This would probably come down to saving a few dozen records a second, which is easily manageable by postgreSQL for example.

**Comment by ktsaou** [comment]
netdata already outputs CSV output via its API. I could easily make it output SQL `INSERT` statements too, so that you could write something like this:

```sh
curl "http://localhost:19999/api/v1/data?chart=mychart&points=60&after=-3600&format=sql" | mysql -D mydb
```

The above would create 60 rows for the last 3600 seconds, one row per minute and insert them into mysql db `mydb`. Of course you could use your favorite relational database instead.

So you can add such a script to a cron job.

Will this do it?

**Comment by simonnagl** [comment]
I do not think we should do this.
I do not know postgres, but most databases can load CSV files much faster than doing insert statements one another.
In my opinion the preferred way should be to provide scripts that are able to do this job for different databases.

@Yenthe666: Do you know if this is available for postregss?

**Comment by Yenthe666** [comment]
@simonnagl yes you can import CSV's in PostgreSQL (http://stackoverflow.com/questions/19400173/how-should-i-import-data-from-csv-into-a-postgres-table-using-pgadmin-3).
Nevertheless, this should have some connector / configurator in place of having to do this manually. I would like long-term statistics of part of the data and I bet more people will need this.

**Comment by simonnagl** [comment]
The best way to export data is using the [REST API](http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/firehol/netdata/master/web/netdata-swagger.yaml).

You can write a plugin that does not send data to `netdata` but export it. If we want a general plugin for relational databases we should think about the database scheme.

The simplest method would be to put all data in one table (timestamp,chart,dimension,value). From there a database owner can reuse the data for the specified purpose.

**Comment by rainliu67** [comment]
Would you consider adding anomaly detection?

**Comment by ktsaou** [comment]
Interesting. I think however that anomaly detection is just trying to figure out **where** in a time series is the anomaly. Netdata on the other hand have many time-series and we are adding more all the time (currently it collects 1.000 to 5.000 metrics per server and I would love to add a lot more application, reaching even 10.000 metrics per server).

With some many time-series, the interesting question is not **where** the anomaly is, but **why** the anomaly exists and **what** the anomaly influenced.

I am not a data scientist to solve this problem with theoretical models. Utilizing only common sense, I would say that by comparing a "known good" period, with any other period, we could come with a list of metrics that might be responsible for the anomaly or that have been influenced significantly by the anomaly (i.e. database requests per seconds increased, disk wait I/O increased, so we reached a congestion point).

Of course, I welcome any PRs in this area.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this. If you need help, just post.
