### ISSUE TITLE
Netdata behing Apache proxy

### ISSUE THREAD

**Issue by matejvelikonja** [firehol/netdata#44]
Has anyone successfully created an apache proxy for netdata?

I would like to access netdata dashboard on a subdirectory. Something like example.com/netdata.

Is it even possible?

**Comment by ktsaou** [comment]
Hi,

I can give it a try. The html/javascript will most probably need a few tweaks...

mod_proxy or something else?

**Comment by matejvelikonja** [comment]
mod_proxy would be great :)

**Comment by ktsaou** [comment]
ok, here it is.

I tested it with these settings:

```
<VirtualHost *:80>
        ProxyRequests Off
        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
        ProxyPass "/netdata/box" "http://127.0.0.1:19999/" connectiontimeout=5 timeout=30
        ProxyPassReverse "/netdata/box" "http://127.0.0.1:19999/"

        ProxyPass "/netdata/pi1" "http://10.11.12.81:19999/" connectiontimeout=5 timeout=30
        ProxyPassReverse "/netdata/pi1" "http://10.11.12.81:19999/"

        # rest of virtual host config
```

My apache is 2.2.31.
Using the above configuration, keep-alive between apache and netdata is active. Pay some attention to keep-alive, or netdata will be slow:

Check `/var/log/netdata/access.log` (you will have to scroll on the page to see the recent log entries - netdata writes this file with buffering, to prevent frequent disk activity).

If for every netdata request you have logs like the following, keep-alive is not enabled on apache:

```
16-01-22 21:14:55: 211: 127.0.0.1 port 59785 connected on thread task id 3281
16-01-22 21:14:55: 211: (sent/all = 2583/4981 bytes -48%, prep/sent/total = 0.34/0.48/0.82 ms) data: 200 '//api/v1/data?chart=example.random2&format=array&points=600&group=average&options=absolute|jsonwrap|nonzero&after=-600&dimensions=random&_=1453490033461'
16-01-22 21:15:55: 211: 127.0.0.1 port 59785 disconnected from thread task id 3281
```

So, if for every request you have 3 lines (connected, a random URL, disconnected - very close it each other), the connection between apache and netdata lacks keep-alive. You should enable it somehow. Check your apache docs. Mine had it enabled by default.

**Comment by ktsaou** [comment]
I forgot:

You have to add the trailing ` / ` on your browser. I cannot fix this. This is how browsers work.

When you omit the trailing `/` and the URL is `http://host/netdata`, index.html is trying to retrieve the relative URL `dashboard.js`. The browser is requesting `http://host/dashboard.js`. It replaces `/netdata` with `/dashboard.js`.

When you append the `/`, like this: `http://host/netdata/`, the browser requests `http://host/netdata/dashboard.js`, which works.

**Comment by ktsaou** [comment]
I edited the response above, so please read it on github, not from email.

**Comment by matejvelikonja** [comment]
i've tried it and it works like a charm

but i've also added a simple redirect 

```
RewriteEngine On
RewriteRule ^/netdata/box$ http://%{HTTP_HOST}/netdata/box/ [L,R=301]
```

just to redirect from non trailing slash to the one with tralining, because netdata does not work without traling slash.

I suggest you add this apache config to readme. I guess more people will need it and they will find it easier.

**Comment by ktsaou** [comment]
There is one more thing I would like to test:

I don't know if apache is going to uncompress and recompress netdata's response. If this happens, it would be best to disable compression at netdata.

To disable response compression in netdata edit `netdata.conf` and set:

```
enable web responses gzip compression = no
```

(the option should already be there)

Can you test if after disabling this you still receive compressed responses at your browser?

**Comment by ktsaou** [comment]
Check also this page:

https://github.com/firehol/netdata/wiki/Running-behind-apache

Do you believe we should state something more?

**Comment by matejvelikonja** [comment]
I've changed netata to `compression=no` and I still receive compress data in browser `Content-Encoding:gzip`

**Comment by ktsaou** [comment]
Thanks!
