### ISSUE TITLE
custom curl options to charts.d plugins

### ISSUE THREAD

**Issue by lokiiiii** [firehol/netdata#442]
Hi there,

After searching for hours how to do it, I finally managed to get my nginx stub status & php-fpm status working fine, but now I have an issue:
In my nginx vhost configuration, my server bloc listening on port 443 is actually configured with a htaccess authentification for all locations, and netdata scripts don't seem to like htaccess as I found some "401 Authorization denied" in my netdata logs.
I could try passing username & password via url (like http://user:pass@mydomain.com) but it doesn't seem to work under SSL (but it IS working through http)
So is there a way to define htaccess credentials somewhere so that netdata's scripts can use them to run its scripts ?

My english is not that good so I hope you'll understand my issue correctly, please ask I some infos are needed,
Thanks a lot :)

**Comment by ktsaou** [comment]
I have prepared a PR that allows you to set curl options on tomcat, apache, nginx and phpfpm. However github is having issues right now and does not allow me to see my commits. I'll update this as soon as they get through.

**Comment by ktsaou** [comment]
Added the PR #445
Testing it now...

**Comment by ktsaou** [comment]
merged it.

You can use `X_curl_opts` where `X` is `nginx`, `tomcat` to set custom curl options for each plugin.

**Comment by lokiiiii** [comment]
Wow, thanks a lot for your reactivity ! :)
Just a stupid question: where should I put these options ? In /etc/netdata/netdata.conf ?

**Comment by ktsaou** [comment]
Each of these plugins has its own file: `/etc/netdata/tomcat.conf` and `/etc/netdata/nginx.conf`

On each file you can add the URL and the options. Read the top few lines of the scripts themselves. You will find out the options you have to set.

**Comment by ktsaou** [comment]
nice!
