### ISSUE TITLE
Data Collection in Python Custom Plug-ins 

### ISSUE THREAD

**Issue by sanaumer** [firehol/netdata#447]
Hello, 

I am using Python template in issue #206 for writing custom plugin , but I am faced with a issue. For data collection, I read data from a csv file and process it a little and then send it to netdata. But I think when a csv file is opened in the netdata plugin, netdata cannot find the chart and displays this message: 
"mychart.mr: chart not found on url "/api/v1/chart?chart=mychart.mr"

So, kindly suggest me how to go about data collection ?

Currently, I am opening the csv file in the netdata plugin and passing the values to the netdata. But the above error appears...

Thanks in anticipation. :)

**Comment by ktsaou** [comment]
Check `/var/log/netdata/error.log`. Does it say anything about your plugin?

**Comment by sanaumer** [comment]
It says: " INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/hvbench.plugin' on pid 16221 stopped"
" ERROR: netdata: pid 16221 exited with code 2.
" ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/hvbench.plugin' (pid 16221) does not generate useful output. Waiting a bit before restarting it again."
"INFO: netdata: PLUGINSD: '/usr/libexec/netddata/plugins.d/hvbench.plugin' running on pid 16346"
"INFO: netdata: executing command: 'exec /usr/libexec/netddata/plugins.d/hvbench.plugin 1 ' on pid 16346"
Unknown option: -
usage: /usr/bin/python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
"INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/hvbench.plugin' on pid 16346 stopped"
"ERROR: netdata: pid 16346 exited with code 2."

and it keeps on trying..

**Comment by ktsaou** [comment]
Your plugin does not run well.
Python complains about:

```
Unknown option: -
usage: /usr/bin/python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

Can you post the plugin?

**Comment by ktsaou** [comment]
I received it. I'll try to test it later today.

**Comment by ktsaou** [comment]
I found 2 problems:

1. Your plugin is windows encoded. It has `\r\n` at its end. This is the main problem. The file you sent does not work on linux at all. It is not a netdata problem.

2. Your csv file is accessed using a relative filename. netdata switches directories, so please use absolute filenames.

After these fixes, it works:

![image](https://cloud.githubusercontent.com/assets/2662304/15584815/ea7eb8e4-2384-11e6-8523-decf5523ff3c.png)

**Comment by sanaumer** [comment]
Yeah, that works!

Thanks for making such an awesome tool!

PS: These were rookie mistakes. :-P
