### ISSUE TITLE
logrotate file creation error

### ISSUE THREAD

**Issue by i300220** [firehol/netdata#453]
Hi,

Got this error on all my systems for 5 days.  Updated, waited, re-updated, nothing helped.

Not good because logrotate is run in a cron job and if it returns an error, the daily cron job stop executing right there and maintenance is not getting done.

Systems are debian Jessie 8

/etc/cron.daily/logrotate:
error: error setting owner of /var/log/netdata/access.log.1.gz to uid 998 and gid 998: Operation not permitted
run-parts: /etc/cron.daily/logrotate exited with return code 1

root@NC-PH-0657-10:/usr/local/src/netdata# ll /var/log/netdata/
total 28268
drwxr-xr-x  2 netdata netdata     4096 May 25 07:19 .
drwxr-xr-x 36 root    root       12288 May 25 07:19 ..
-rw-r--r--  1 netdata netdata 16417484 May 24 17:45 access.log
-rw-------  1 netdata netdata        0 May 24 07:14 access.log.1
-rw-------  1 netdata root           0 May 25 07:19 access.log.1.gz
-rw-r--r--  1 netdata netdata        0 Mar 31 12:37 debug.log
-rw-r--r--  1 netdata netdata 12499477 May 25 08:20 error.log
-rw-r--r--  1 netdata netdata        0 May 24 15:58 .keep

**Comment by ktsaou** [comment]
@philwhineray @simonnagl any ideas?

**Comment by philwhineray** [comment]
This sounds about right?

https://lists.debian.org/debian-user/2015/08/msg01309.html

**Comment by ktsaou** [comment]
now it has:

```
su netdata
```

Shall we do it:

```
su netdata netdata
```

?

**Comment by patschbo** [comment]
This works for me!

**Comment by ktsaou** [comment]
Oh, I see access.log is group owned by root.
I am making a PR to have netdata chown its log files.

**Comment by ktsaou** [comment]
I will merge this later today. I need to make a few more tests.

**Comment by ktsaou** [comment]
merged the fix. Please update your netdata.

**Comment by i300220** [comment]
The recent fix does not work on one system at least.  Other systems are waiting for the daily cron job to run.

Replacing 'su netdata' with 'create 0640 netdata netdata' is the proper fix.  On Debian 8 Jessie.

root@NC-PH-0657-10:/usr/local/src/netdata# !gi
git pull
Already up-to-date.

root@NC-PH-0657-10:/usr/local/src/netdata# cat /etc/logrotate.d/netdata
/var/log/netdata/*.log {
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
        sharedscripts
        #
        # if you add netdata to your init.d/system.d
        # comment su & copytruncate and uncomment postrotate
        # to have netdata restart when logs are rotated
        su netdata
        copytruncate
        #
        #postrotate
        #       if service netdata status > /dev/null ; then \
        #               service netdata restart > /dev/null; \
        #       fi;
        #endscript
}

**Comment by ktsaou** [comment]
ok, updated it.
