### ISSUE TITLE
Netdata can't active on centos 7

### ISSUE THREAD

**Issue by tuanmmt** [firehol/netdata#454]
Hello all,

I installed netdata on centos 7 and after that I can't active netdata.service with command "systemctl start netdata"

My error is:

â— netdata.service - Linux real time system monitoring, over the web
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-05-25 21:52:39 ICT; 10h ago
  Process: 10399 ExecStart=/usr/sbin/netdata -pidfile /var/run/netdata.pid (code=exited, status=1/FAILURE)

May 25 21:52:39 localhost.localdomain systemd[1]: Starting Linux real time system monitor.....
May 25 21:52:39 localhost.localdomain netdata[10399]: 16-05-25 21:52:39: INFO: netdata: Li...)
May 25 21:52:39 localhost.localdomain netdata[10399]: 16-05-25 21:52:39: ERROR: netdata: I...)
May 25 21:52:39 localhost.localdomain netdata[10399]: 16-05-25 21:52:39: INFO: netdata: Li....
May 25 21:52:39 localhost.localdomain netdata[10399]: 16-05-25 21:52:39: ERROR: netdata: I...)
May 25 21:52:39 localhost.localdomain netdata[10399]: 16-05-25 21:52:39: FATAL: netdata: C...s
May 25 21:52:39 localhost.localdomain systemd[1]: netdata.service: control process exited...=1
May 25 21:52:39 localhost.localdomain systemd[1]: Failed to start Linux real time system ...b.
May 25 21:52:39 localhost.localdomain systemd[1]: Unit netdata.service entered failed state.
May 25 21:52:39 localhost.localdomain systemd[1]: netdata.service failed.
Hint: Some lines were ellipsized, use -l to show in full

Please help me solve this problem. Thanks all!

**Comment by ktsaou** [comment]
The log is cut. Could you please post the full lines to let us know the error message?

**Comment by tuanmmt** [comment]
Hello ktsaou,

When I use command "systemctl start netdata"  on centos 7 , It appear this error:

[root@localhost ~]# systemctl start netdata.service
Job for netdata.service failed because the control process exited with error code. See "systemctl status netdata.service" and "journalctl -xe" for details.

And after that, I use "systemctl status netdata.service" , the error log is above .

**Comment by ktsaou** [comment]
Yes, I understood that. However the log lines are ellipsized.  It says:

Hint: Some lines were ellipsized, use -l to show in full

Could you please run it with `-l` to show the full lines?

**Comment by tuanmmt** [comment]
Sorry for this prob. I will give you after show: 

[root@localhost ~]# systemctl status netdata.service -l
â— netdata.service - Linux real time system monitoring, over the web
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-05-26 13:53:26 ICT; 1h 5min ago
  Process: 6419 ExecStart=/usr/sbin/netdata -pidfile /var/run/netdata.pid (code=exited, status=1/FAILURE)

May 26 13:53:26 localhost.localdomain systemd[1]: Starting Linux real time system monitoring, over the web...
May 26 13:53:26 localhost.localdomain netdata[6419]: 16-05-26 13:53:26: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
May 26 13:53:26 localhost.localdomain netdata[6419]: 16-05-26 13:53:26: ERROR: netdata: IPv6 bind() failed. Disabling IPv6. (errno 98, Address already in use)
May 26 13:53:26 localhost.localdomain netdata[6419]: 16-05-26 13:53:26: INFO: netdata: Listening on any IPs (IPv4).
May 26 13:53:26 localhost.localdomain netdata[6419]: 16-05-26 13:53:26: ERROR: netdata: IPv4 bind() failed. (errno 98, Address already in use)
May 26 13:53:26 localhost.localdomain netdata[6419]: 16-05-26 13:53:26: FATAL: netdata: Cannot listen socket. # : Success
May 26 13:53:26 localhost.localdomain systemd[1]: netdata.service: control process exited, code=exited status=1
May 26 13:53:26 localhost.localdomain systemd[1]: Failed to start Linux real time system monitoring, over the web.
May 26 13:53:26 localhost.localdomain systemd[1]: Unit netdata.service entered failed state.
May 26 13:53:26 localhost.localdomain systemd[1]: netdata.service failed.

**Comment by ktsaou** [comment]
Netdata is already running.
kill the running one and start it via systemd.

**Comment by simonnagl** [comment]
Have you installed `netdata` with `netdata-installer.sh`?
It starts `netdata` at the end. Maybe this instance is running on your machine.

**Comment by tuanmmt** [comment]
Hello simonnagl,

I install netdata with netdata-installer.sh. However, I want to active netdata.service with command "systemctl start netdata.service" but it' just failed.

**Comment by simonnagl** [comment]
try:
```
sudo killall netdata
sudo sytemctl start netdata.service
```

If it fails please give us the output of `journalctl -r -u netdata` until the last start of `netdata`.

**Comment by tuanmmt** [comment]
Ok. I fixed prob. Thank you so much
