### ISSUE TITLE
Netdata to monitor shared library in C++ executable 

### ISSUE THREAD

**Issue by sam0302** [firehol/netdata#455]
Hello,

I am new to netdata. I have a shared library and I would like to know the usage of this shared library using netdata. I checked the documentation about plugin.d in netdata, which states Any program that can print a few values to its standard output can become a netdata plugin. Does that mean, if I have an executable that uses this shared library and it outputs using stdout with CHART, DIMENSION etc will be shown in Netdata? How will netdata know this program is a plugin?
Please suggest what would be the ideal approach for this?

**Comment by ktsaou** [comment]
yes, any program that can output CHART, DIMENSION, etc lines can be a netdata plugin. Netdata will start it by placing it in `/usr/libexec/netdata/plugins` with the extension `.plugin`.

If your program cannot run under netdata, you have many options: Your program could just expose its counters via IPC, or a unix socket, or write them to a file in tmpfs and the plugin could just use any of these methods to get the counters and send them to netdata.

**Comment by ktsaou** [comment]
Of course, whatever you do, make sure it is resource efficient, especially CPU efficient.
