### ISSUE TITLE
netdata starts logging before opening the log files and writes to stderr

### ISSUE THREAD

**Issue by MelkorLord** [firehol/netdata#459]
Netdata starts logging information before opening the log files and thus, end up writing text to stderr which is not desirable when invoking netdata as a service.

Also, the text written to stderr is "lost" as it does not appear on the log files (error.log for instance)

Example
```
 * Starting real-time system monitoring netdata
16-05-27 04:31:07: INFO: netdata: Listening on all IPs (IPv6 and IPv4)
   ...done.
```
and editing /etc/netdata/netdata.conf 
```
[global]
  bind socket to IP = 127.0.0.1
```
makes netdata even more chatty
```
 * Starting real-time system monitoring netdata
16-05-27 04:31:25: ERROR: netdata: Failed to convert IP '127.0.0.1' to a valid IPv6 address. Disabling IPv6.
16-05-27 04:31:25: INFO: netdata: Listening on IP '127.0.0.1' (IPv4).
16-05-27 04:31:25: INFO: netdata: Managed to open an IPv4 socket on port 19999.
   ...done.
```
This also affects log rotation and you end up receiving a mail from cron every day with this very same text.

**Comment by ktsaou** [comment]
I have commented these logs in #464

**Comment by ktsaou** [comment]
I have not removed this line:

```
16-05-27 04:31:25: ERROR: netdata: Failed to convert IP '127.0.0.1' to a valid IPv6 address. Disabling IPv6.
```

You can get rid of this message by setting:

```
[global]
    ip version = ipv4
```

**Comment by MelkorLord** [comment]
Sorry to dig out this old thread but the issue is back :-( upon (re)start, the following text is output on the console : 
```
16-10-17 19:55:21: INFO: netdata: System has 8 processors.
16-10-17 19:55:21: INFO: netdata: System supports 32768 pids.
```
There really should be an option to set the log level. Even the "error.log" is flooded each time "netdata" is restarted with lots of "INFO" lines that make the real errors hard to spot without filtering.

**Comment by ktsaou** [comment]
ok, I cleaned up a lot of INFO messages. netdata already has a multi-level logging. Debug messages can be enabled and disabled for all operations independently. I consider INFO and ERROR the once that already be present. So, just just moved a lot of INFO messages to DEBUG sections. It should be a lot better now.

In PR #1123
