### ISSUE TITLE
URL relative call for easy proxy

### ISSUE THREAD

**Issue by cyayon** [firehol/netdata#46]
Hi,

When trying to use a reverse proxy in front of netdata, you need to use a full virtual hostname because of absolute /api/* calls in (js and html code).

Could it be possible to add a configure param to define and relative URL ?

for example http://<hostname>/netdata/api/... instead of http://<hostname>/api/...

Thanks in advance.

**Comment by ktsaou** [comment]
Hi,

it should already work. Have you checked it out recently (fixed this weekend).

Check these:

https://github.com/firehol/netdata/wiki/Running-behind-apache

and

#44

**Comment by ktsaou** [comment]
If you plan to use it on custom dashboards, this might be helpful too:

https://github.com/firehol/netdata/wiki/Custom-Dashboards#the-default-netdata-server

**Comment by cyayon** [comment]
Hi,

Thanks for your answer !

I use a version of last week, i will check...
I am using lighttpd, but it should be possible... 

I Will keep you informed and give you my config if you want publish...

Best regards,

--
Christophe Yayon

**Comment by cyayon** [comment]
Hi,

yes, everything is fine and working with lighttpd too.

Here is my config if you want to publish (for lighttpd 1.4.x) :

# netdata with lighttpd 1.4.x
$HTTP["url"] =~ "^/netdata/" {   proxy.server  = ( "" => ("" => ( "host" =>
"127.0.0.1", "port" => 19998 ))) }
$SERVER["socket"] == ":19998" { url.rewrite-once = ( "^/netdata(.*)$" =>
"/$1" )   proxy.server = ( "" => ( "" => ( "host" => "127.0.0.1", "port" =>
19999 ))) }


PS : you have to use this workaround because version 1.4.x cannot rewrite
and proxyfing in the same statement... With next major release 1.5, it will
be possible... (
http://stackoverflow.com/questions/14536554/lighttpd-configuration-to-proxy-rewrite-from-one-domain-to-another
)

thanks again and your netdata tool is very cool ! :-)


On Tue, Jan 26, 2016 at 7:53 PM, Christophe Yayon <cyayon@nbux.org> wrote:

> Hi,
>
> Thanks for your answer !
>
> I use a version of last week, i will check...
> I am using lighttpd, but it should be possible...
>
> I Will keep you informed and give you my config if you want publish...
>
> Best regards,
>
> --
> Christophe Yayon
>
> Le 26 janv. 2016 à 19:48, Costa Tsaousis <notifications@github.com> a
> écrit :
>
> Hi,
>
> it should already work. Have you checked it out recently (fixed this
> weekend).
>
> Check these:
>
> https://github.com/firehol/netdata/wiki/Running-behind-apache
>
> and
>
> #44 <https://github.com/firehol/netdata/issues/44>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firehol/netdata/issues/46#issuecomment-175173593>.
>
>


-- 
Christophe Yayon
cyayon@nbux.org

**Comment by ktsaou** [comment]
Thanks!
I will add it.

Can you give me some info about the config (i.e. what is port 1998)?

**Comment by cyayon** [comment]
Port 19998 is another port (which you want) to double proxy. Without this workaround, with the current stable version of lighttpd, you can not rewrite and proxy in the statement.

--
Christophe Yayon

**Comment by ktsaou** [comment]
ok. thanks.
Here it is: https://github.com/firehol/netdata/wiki/Running-behind-lighttpd

If you want me to state something different, more, please let me know.
