### ISSUE TITLE
mysql.chart.sh on ubunutu 14.04 not working

### ISSUE THREAD

**Issue by rdnkrkmz** [firehol/netdata#462]
First of all, thanks for this great project.

I am examining the **mysql.chart.sh** to write a plugin for postgresql (firstly to test, if it is successful I want to improve and share it). But actually I could not run mysql.chart for mysql server.
Now, before I expect it to work I try it on a separate window to see how the  mysql.chart.sh works. But when I try, it gets the "**line 198: fixid: command not found**" (from eclipse). I looked in the system, not executable as "fixid" and no query results on the web.

I am right to test this individually?
If I am right, also a question: What  should be the order of function calls?
functions as below:
**mysql_exec()
mysql_get()
mysql_check()
mysql_create()
mysql_update()**

Thanks lot.

**Comment by ktsaou** [comment]
How do you run it?

These scripts are sourced from `charts.d.plugin`. So to test any of them you should run this:

```sh
/usr/libexec/netdata/plugins/charts.d.plugin 1 mysql
```

The above will run `mysql.chart.sh`.

`fixid()` and a few more calls, are functions in `charts.d.plugin`.

**Comment by ktsaou** [comment]
the path I posted was wrong. I updated it.

**Comment by ktsaou** [comment]
Regarding the sequence, `charts.d.plugin` calls them as follows:

1. `X_check()` - if it returns 1, it stops - this function should just test it can run on this machine.
2. `X_create()` - again if it returns 1, it stops - this function should create the charts (CHART, DIMENSION lines)
3. `X_update()` - again if it returns 1, it stops - this function is the data collection
4. `X_update()`
5. `X_update()`
6. `X_update()`

etc, forever.

The other functions, are helpers within the plugin. `charts.d.plugin` will never call them directly.

**Comment by rdnkrkmz** [comment]
Thank you for useful information and quick reply. 
Now it works. Actually log says that netdata plugin tries to to connect mysql as "netdata@localhost" but no such user in mysql. 
I created this user to use for monitoring db. Everything is fine now.

But now, for postgresql;
Is it feasible for netdata to to run some of queries with psql for every 5 sec. to collect postgresql system infos?

Queryies like :

SELECT * FROM pg_stat_activity;
SELECT * FROM pg_stat_database;
SELECT * FROM pg_stat_user_tables;
SELECT * FROM pg_stat_user_indexes;
SELECT * FROM pg_locks;

or if you know a better way, appreciated.

**Comment by ktsaou** [comment]
Yes of course. If you need help doing this, I suggest to run these queries on your db and post the results here. I'll guide you how to do it.

**Comment by ktsaou** [comment]
Cleaning up.
If you need help, please post here.
