### ISSUE TITLE
How to transfer history stats from RAM to external memory - pendrive

### ISSUE THREAD

**Issue by Andrew543** [firehol/netdata#463]
Hi, here is information: https://github.com/firehol/netdata/wiki/Memory-Requirements - "if you need a long history, you will need a lot of RAM." 
Is there any way to save the history on pendrive or other external memory? It will be very helpfull, if we dont have enough RAM and want check history from last 7 days.

Path for data history can be set for example in [global] config.
hostory directory = /mnt/sdaX etc.

Is it possible to add this feature?

**Comment by ktsaou** [comment]
Currently netdata supports 3 memory modes:

1. `ram` where the chart data are purely in memory. Data are never saved on disk.
2. `save` (the default) where the data are only in RAM while netdata runs and are saved to / loaded from disk on netdata restart.
3. `map` where the data are in memory mapped files.

`map` is the one you need. It works like the swap. Keep in mind though, this will have a constant write on your disk. When netdata writes data on its memory, the Linux kernel marks the related memory pages as dirty and automatically starts updating them on disk. Unfortunately we cannot control how frequently this works. The Linux kernel uses exactly the same algorithm it has for its swap memory.

To try it, edit netdata.conf and set:

```
[global]
    memory mode = map
    cache directory = /var/cache/netdata
```

**Comment by ktsaou** [comment]
I updated the wiki page for this info.

**Comment by Andrew543** [comment]
Thx for replay.

When i set:
[global]
    memory mode = map
    cache directory = /mnt/sdb2/netdata

"When netdata writes data on its memory, the Linux kernel marks the related memory pages as dirty and automatically starts updating them on disk." 

First system use RAM and then netdata use external disk.

**Comment by Andrew543** [comment]
Thx for replay.

I try:
[global]
memory mode = map
cache directory = /mnt/sdb2/netdata

"When netdata writes data on its memory, the Linux kernel marks the related memory pages as dirty and automatically starts updating them on disk."

As you said, first system use RAM and then netdata use external disk.
If we could set only external memory (pendrive) it will be the best. 
Now in "map" mode, RAM is still used (at beggining) - so this setting for small devices is usless.
Ive tested it on OpenWRT CC.

**Comment by ktsaou** [comment]
> Now in "map" mode, RAM is still used (at beggining) - so this setting for small devices is usless.

This is done by the linux kernel. RAM is used "on demand" in `map` mode. Even initially it won't be used if the kernel believes there is no point to (or there is no memory available).

In other words, in `map` mode, netdata does not allocate memory. It says it wants the files memory mapped and the linux kernel decides how much RAM it will use.

**Comment by Andrew543** [comment]
In log i get something like this:
 daemon.err netdata[2146]: Cannot advise the kernel about the memory usage of file 'PATH to *.db' etc.

Should i set something else, or this kind of log is normal, when i used MAP mode?

**Comment by ktsaou** [comment]
No, this is ok. It is not an error, but a warning. netdata is using `madvice()` to let the kernel know it intends to use its memory sequentially (this could allow the kernel cache the proper parts of the files). This call fails on your system. No harm.

**Comment by Andrew543** [comment]
Thanks for help!
