### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by mjnaderi** [firehol/netdata#466]
After I updated netdata from c09a625 to fdb2a27, netdata consumes memory a lot:

![screenshot from 2016-05-31 08-02-43](https://cloud.githubusercontent.com/assets/2115303/15662527/c4b29452-2706-11e6-9dba-590c4b5051d5.png)

Its memory usage increases, and it doesn't stop utill I have to kill it.

**Comment by ktsaou** [comment]
What is your history size? Have you changed the default database of 3600 seconds of history?

Why I am asking: The chart you are posting is tracking the memory applications use, independently of how much they have allocated. So if you have a day of data, netdata will be shown in this chart as getting more and more memory until its whole database has been written once.

**Comment by ktsaou** [comment]
I found it. I am making a PR now.

**Comment by ktsaou** [comment]
merged the fix.

Thanks for reporting this!
