### ISSUE TITLE
Wrong Time in Charts

### ISSUE THREAD

**Issue by mjnaderi** [firehol/netdata#467]
As you see in this picture, I have moved the mouse on 08:19 AM but the upper time displays 07:19 AM.

This happens for all charts.

![screenshot from 2016-05-31 08-19-48](https://cloud.githubusercontent.com/assets/2115303/15662723/c5b3ae34-2708-11e6-9f8f-2b6dee5ffb46.png)

**Comment by ktsaou** [comment]
Interesting.
Which is the right one?

The date at the legend is rendered by me, the x-axis is handled by dygraphs. So, please give me a hint where to look.

**Comment by mjnaderi** [comment]
The right one is 08:19 AM (which is in chart's legend).

**Comment by mjnaderi** [comment]
Sorry, I mean the one which is in x-axis (08:19 AM).

**Comment by ktsaou** [comment]
I'll check it later today.
What is your timezone?

**Comment by mjnaderi** [comment]
My Timezone is [Asia/Tehran](https://en.wikipedia.org/wiki/Asia/Tehran) (UTC+03:30).
But part of year, it becomes UTC+04:30 due to Daylight Saving Time. Now it is UTC+04:30.
Maybe the problem is related to DST.

**Comment by simonnagl** [comment]
For me there is no such issue. My timezone is affected by DST also.

Could you please provide the output of `timedatectl status` or a corresponding call if you do not use systemd. Mine is
```
      Local time: Di 2016-05-31 13:18:54 CEST
  Universal time: Di 2016-05-31 11:18:54 UTC
        RTC time: Di 2016-05-31 11:18:54
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

**Comment by ktsaou** [comment]
This is a javascript issue. Dates are transferred from the netdata server in timestamps (which are always GMT-0).

I guess this it is a browser issue. Could you please check it with another browser?

If it is a browser issue, then probably dygraphs are using a different locale-time function than I do on the legend, hence the difference.

**Comment by mjnaderi** [comment]
I checked it with the latest versions of Chromium (Chromium 51.0.2704.63) and Firefox (Mozilla Firefox 46.0.1). The issue exists in both browsers.

**Comment by ktsaou** [comment]
This is becoming even more interesting.

I format both values.

The x-axis is formatted with the javascript functions `Date.getHours()`, `Date.getMinutes()` and `Date.getSeconds()`:

https://github.com/firehol/netdata/blob/630a74a5bf201d0ca6ef3cef3cef4df251e766a5/web/dashboard.js#L3862

Description here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getHours

The legend is formatted with `Date.toLocaleDateString()` and `Date.toLocaleTimeString()`:

https://github.com/firehol/netdata/blob/630a74a5bf201d0ca6ef3cef3cef4df251e766a5/web/dashboard.js#L1963-L1967

Description here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

Now, the question is: **why these 2 javascript functions return different results?**

Searching...

**Comment by ktsaou** [comment]
Can you confirm the problem can be reproduced with this:

1. Press F12 on your browser (any browser page will do - even here on github)
2. Switch to `Console`
3. Type: `(new Date).toLocaleTimeString()`. Mine returns the correct local time. If yours right?

**Comment by ktsaou** [comment]
http://jj09.net/javascript-date-a-bad-part/

Says: Both `toLocaleDateString()` and `toLocaleTimeString()` return different results, depended on user’s machine settings and geographical location.

Typing this on your browser console, will give you the timezone in minutes, your browser believes you are now: `(new Date).getTimezoneOffset()`. Is it right?

**Comment by mjnaderi** [comment]
![screenshot from 2016-06-01 21-24-18](https://cloud.githubusercontent.com/assets/2115303/15718148/3f91cfa6-283f-11e6-82e9-9b6e0f24c152.png)

When I typed these, my actual local time was 9:24 PM.

**Comment by ktsaou** [comment]
This seems a problem of your browser. I don't think I should do anything to fix it.

**Comment by ktsaou** [comment]
Have you fixed it?
If you believe there should be anything netdata could do to fix this, please post here.

**Comment by mjnaderi** [comment]
A few weeks ago, I re-installed my OS (Arch Linux), and after visiting NetData dashboard, I was surprised. The problem was gone. Now it displays correct time. I didn't update NetData. So I think the problem was related to Browser or some package which was updated.
Thanks for investigating this issue.
