### ISSUE TITLE
Error 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by redrock88** [firehol/netdata#475]
Hi There, 

First off, thank you for creating such a great and beautiful tool! I'm wondering if you may be able to help me with the issue however? I periodically get "Error 405: Cannot download charts index from server" when trying to access netdata.  A reboot of the server brings it back for a while, but then the error returns. Error is same across multiple browsers and computers.

I'm running netdata on Ubuntu server 14.04. No proxy and firewall doesn't appear to be the issue (have insured proper rule added, as well as turned off/on).

Below are the results of tail -f /var/log/netdata/*.log:

> ==> /var/log/netdata/access.log <==
16-06-01 23:38:50: 20: (sent/all = 1568/3471 bytes -55%, prep/sent/total = 1.61/0.58/2.19 ms) data: 200 '/api/v1/data?chart=system.cpu&format=array&points=360&group=average&options=absolute|jsonwrap|nonzero&after=-360&_=1464835128999'
16-06-01 23:38:50: 21: (sent/all = 1286/2713 bytes -53%, prep/sent/total = 0.43/0.51/0.94 ms) data: 200 '/api/v1/data?chart=system.io&format=array&points=360&group=average&options=absolute|jsonwrap|nonzero&after=-360&dimensions=out&_=1464835129000'
16-06-01 23:38:50: 19: (sent/all = 269/1151 bytes -77%, prep/sent/total = 0.40/0.24/0.64 ms) data: 200 '/api/v1/data?chart=system.io&format=array&points=360&group=average&options=absolute|jsonwrap|nonzero&after=-360&dimensions=in&_=1464835129001'
16-06-01 23:38:50: 17: (sent/all = 269/3672 bytes -93%, prep/sent/total = 0.64/0.26/0.90 ms) data: 200 '/api/v1/data?chart=system.swap&format=array&points=360&group=average&options=absolute|jsonwrap|nonzero|percentage&after=-360&dimensions=free&_=1464835129002'
16-06-01 23:39:50: 19: 10.0.1.20 port 58922 disconnected from thread task id 23371
16-06-01 23:39:50: 18: 10.0.1.20 port 58920 disconnected from thread task id 23370
16-06-01 23:39:50: 17: 10.0.1.20 port 58888 disconnected from thread task id 23301
16-06-01 23:39:50: 16: 10.0.1.20 port 58886 disconnected from thread task id 23300
16-06-01 23:39:50: 20: 10.0.1.20 port 58924 disconnected from thread task id 23372
16-06-01 23:39:50: 21: 10.0.1.20 port 58928 disconnected from thread task id 23420

> ==> /var/log/netdata/debug.log <==

> ==> /var/log/netdata/error.log <==
16-06-01 23:58:46: apps.plugin: Too many logs (101 logs in 694 seconds, threshold is set to 100 logs in 3600 seconds). Preventing more logs from process 'apps.plugin' for 2906 seconds.
16-06-02 00:08:04: INFO: netdata: Exit main loop of netdata.
16-06-02 00:08:04: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 16265 stopped.
16-06-02 00:08:04: ERROR: netdata: pid 16265 killed by signal 15.
/usr/libexec/netdata/plugins.d/charts.d.plugin: line 456:   445 Terminated              sleep 0.2  (wd: /tmp/.netdata-charts.d-A7LJnZGa4Q)
16-06-02 00:08:04: ERROR: netdata: pid 3337 killed by signal 15.
16-06-02 00:08:04: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/charts.d.plugin' on pid 16268 stopped.
16-06-02 00:08:04: ERROR: netdata: pid 16268 killed by signal 15.
16-06-02 00:08:05: ERROR: netdata: Cannot unlink pidfile '/var/run/netdata.pid'. (errno 13, Permission denied)
16-06-02 00:08:05: INFO: netdata: NetData exiting. Bye bye...

Thanks in advance!

**Comment by redrock88** [comment]
Correction::::: it appears that rebooting the server no longer resolves the issue, even temporarily.

**Comment by ktsaou** [comment]
Is it the standard dashboard or your own?
Have you tried a different browser? There are many browser plugins that may interfere.

When this happens, open a new tab at the browser and fetch this url:

```
http://your.netdata.server:19999/api/v1/charts
```

Does it work? Please post the result here.

Try it also on the demo sites:

[http://london.netdata.rocks/api/v1/charts](http://london.netdata.rocks/api/v1/charts)

[http://atlanta.netdata.rocks/api/v1/charts](http://atlanta.netdata.rocks/api/v1/charts)

[http://athens.netdata.rocks/api/v1/charts](http://athens.netdata.rocks/api/v1/charts)

Do these work?

**Comment by ktsaou** [comment]
I think I know what is happening.

You might have a chart name with an invalid javascript name. I can fix this, but I need the problematic output of `http://your.netdata.server:19999/api/v1/charts`.

**Comment by redrock88** [comment]
Hi Costa,

Thank you for your quick reply, my apologies for the delay on my end!

So.... strangely, here's what I have (not sure if this makes sense to
you)....

First - just to be clear - I have made no changes to the default netdata
setup. I just installed as per instructions and left as is. I do not use
proxy and my firewall has been disabled just in to be sure it is not
interfering.

I have tried accessing netdata from both Mac OSX and Ubuntu, have used
Safari, Firefox and Chrome (all extensions disabled) and all show the same
error: Could not connect to server, connection refused.

When I tried the demo links you posted, (e.g.
http://london.netdata.rocks/api/v1/charts) they page does not load properly
for me (again, multiple os's & browsers). Instead of rendering the page,
I'm shown just the code (see screenshot).

However, if I go to just http://london.netdata.rocks, then the page
displays fine (this happens with Atlanta and Athens servers as well).

Any thoughts?

Thanks again for your assistance!

**Comment by ktsaou** [comment]
Github has removed the screenshot. Can you paste it to github or send it to costa@tsaousis.gr ?

**Comment by ktsaou** [comment]
@redrock88 when you fetch http://london.netdata.rocks/api/v1/charts you should get the code. This is the whole idea.

On your server you should get the code do. I need this code, from your server. It is automatically generated using information from each system. There must be an error when netdata runs on your system.

So just fetch http://your.netdata:19999/api/v1/charts and give me the code. Not a screenshot. I need the whole of it.

**Comment by redrock88** [comment]
Apologies - I was under the impression that going to
http://london.netdata.rocks/api/v1/charts  would show you the demo page.

When I went to  http://*myserver*:19999/api/v1/charts it did not display
any code, just that it could not connect. It appears that the netdata
service was not starting at all (it had previously, but then ceased to do
so for some reason).

It appears that the fix was to add the following config file as per these
instructions:
http://samiux.blogspot.ca/2016/04/howto-netdata-on-ubuntu-14044-lts.html

Since adding the config file, it has been working (at least for the last
hour or so and persists through reboots).

My apologies for your trouble.

**Comment by ktsaou** [comment]
ok. I am closing this.

**Comment by dwalst** [comment]
Hello I am receiving the following errors on Redhat Enterprise 7 and would like to know where I would put the suggested netdata.conf file on RHEL 7 as Rhel 7 does not have an "/etc/init" FS or Dir.

-Error 405: Cannot download charts index from server:  http://xx.xxx.xx.xxx:19999/api/v1/charts
-Cannot load required JS library: http://xx.xxx.xx.xxx.19999/lib/bootstrap.min.js

**Comment by axper** [comment]
Ok since this is the first result when searching for this error I'm gonna post the solution here.

For some wierd reasonn pressing Ctrl+F5 to reload the page results in this error. Pressing F5 however, the page loads properly.

**Comment by phpmydev** [comment]
Howdy!
now I am getting this (I deleted a new post on the subject) and what I am now getting from api/v1/charts is:
This host does not maintain a database
This is an install of netdata while installing iRedMail - any clue?
Thank you in advance!

**Comment by juanjocastillo** [comment]
just install netdata... get the same Error 405... have to restar (# netdata restart) manually every reboot not even a cron job do nothing...
