### ISSUE TITLE
Packaging help on Archlinux

### ISSUE THREAD

**Issue by SanskritFritz** [firehol/netdata#48]
I'm trying to create an Archlinux package for netdata based on the netdata-9999.ebuild file. However I don't know how to do make install with a prefix directory. Like this:
```	./autogen.sh
	./configure \
		--prefix="/usr" \
		--sbindir="/usr/bin" \
		--sysconfdir="/etc" \
		--libexecdir="/usr/lib" \
		--localstatedir="/var" \
		--with-zlib --with-math --with-user=netdata \
		CFLAGS="-O3"

	make \
		prefix="$pkgdir/usr" \
		sbindir="$pkgdir/usr/bin" \
		sysconfdir="$pkgdir/etc" \
		libexecdir="$pkgdir/usr/lib" \
		localstatedir="$pkgdir/var" \
		install
```
When I install and start netdata and look at the default config, it seeks its directories still in the $pkgdir directory, despite my configure step. 
Please help me.

**Comment by ktsaou** [comment]
Sorry, I don't know either.
@alonbl could you please help?

**Comment by alonbl** [comment]
Hi,

@SanskritFritz: you do not need to override any parameter in make, as all registered during configure.

@ktsaou: this package is not fully migrated to autotools/packaging, only core transition was done, we discussed this in the past, form example we need to generate a template with all directory location and source it in netdata-installer.sh and any file that reference a file location, similar to what you have done in firehol. Provide init script to start/stop. Actually, the netdata-installer.sh should not be required at all, most should be done by either the make install and the init-script or systemd unit.

**Comment by SanskritFritz** [comment]
@alonbl How do I install the program into $pkgdir then? Do I have to copy all files manually or is there another automated method?

**Comment by alonbl** [comment]
@SanskritFritz: I do not see any issue with installation, only when the scripts/programs that should be aware of the new file locations.

```
$ git clone https://github.com/firehol/netdata
$ cd netdata/
$ autoreconf -ivf
$ ./configure --prefix=/test1
$ make install DESTDIR=/tmp/tmproot
$ find /tmp/tmproot/ | head -n 10
/tmp/tmproot/
/tmp/tmproot/test1
/tmp/tmproot/test1/var
/tmp/tmproot/test1/var/log
/tmp/tmproot/test1/var/log/netdata
/tmp/tmproot/test1/var/log/netdata/.keep
/tmp/tmproot/test1/var/cache
/tmp/tmproot/test1/var/cache/netdata
/tmp/tmproot/test1/var/cache/netdata/.keep
/tmp/tmproot/test1/libexec
```

**Comment by cyayon** [comment]
Hi,

here is my PKGBUILD, it is perfectible, but should be sufficient ...
 
---------------
pkgname=netdata
_gitname=netdata
pkgver=20160119
pkgrel=0
groups=('nbux')
pkgdesc="netdata"
arch=('i686' 'x86_64')
url="https://github.com/ktsaou/netdata"
license=('GPL')
categories=('network')
backup=('etc/netdata/netdata.conf')
install=netdata.install

depends=('make')
makedepends=('cmake' 'git')
options=(!emptydirs)

_destination="/opt/netdata"
_user="netdata"

source=("${_gitname}::git+https://github.com/ktsaou/${_gitname}.git#branch=master" 'netdata.service')

md5sums=("SKIP" "SKIP")

build() {
        cd "${srcdir}/${_gitname}"
        ./autogen.sh
        ./configure --prefix="${_destination}" --with-zlib --with-math --with-user=${_user} CFLAGS="-O3"
        make
}

package() {
        cd "${srcdir}/${_gitname}"
        make DESTDIR="${pkgdir}" install
        install -D -m644 ${srcdir}/netdata.service ${pkgdir}/usr/lib/systemd/system/netdata.service
        touch "${pkgdir}${_destination}/etc/netdata/netdata.conf"
        chown root:root "${pkgdir}${_destination}/etc/netdata/netdata.conf"
}
-------------------


netdata.install 
----------------------------------
_destination="/opt/netdata"
_user="netdata"

post_install() {
echo "Fixing directory permissions for user ${USER}..."
for x in var/cache/netdata share/netdata/web var/log/netdata etc/netdata ; do
        if [ ! -d "${x}" ] ; then
                mkdir -p "${x}" || exit 1
        fi
        chown -R "${_user}:${_user}" "${_destination}/${x}"
        chmod 0775 "${_destination}/${x}"
done

# fix apps.plugin to be setuid to root
chown root:root "${_destination}/libexec/netdata/plugins.d/apps.plugin"
chmod 4755 "${_destination}/libexec/netdata/plugins.d/apps.plugin"

if [ ! -f "${_destination}/etc/netdata/netdata.conf" ] ; then
        touch "${_destination}/etc/netdata/netdata.conf"
        chown "${_user}:${_user}" "${_destination}/etc/netdata/netdata.conf"
fi
}

post_upgrade() {
    post_install "$1"
}
-----------------------



netdata.service (systemd service unit)
------------------------
[Unit]
Description=Netdata monitoring server
After=network.target

[Service]
User=root
ExecStart=/opt/netdata/sbin/netdata -u netdata
ExecStop=/usr/bin/pkill netdata
Type=forking
KillMode=process

[Install]
WantedBy=multi-user.target
---------------------

**Comment by ktsaou** [comment]
> @ktsaou: this package is not fully migrated to autotools/packaging, only core transition was done, we discussed this in the past, form example we need to generate a template with all directory location and source it in netdata-installer.sh and any file that reference a file location, similar to what you have done in firehol. Provide init script to start/stop. Actually, the netdata-installer.sh should not be required at all, most should be done by either the make install and the init-script or systemd unit.

Well, I really need help. All these seem Greek to me (I am Greek, so this is not actually valid, but anyway you got the idea :-)

How should I do it? @philwhineray since you have done all this excellent work for firehol, can you help please?

**Comment by ktsaou** [comment]
I have added openrc/systemd scripts: #50, #51 

> we need to generate a template with all directory location and source it in netdata-installer.sh

I don't get this. `make install` installs everything already. Why do we need this template?
Actually `make install`:

1. copies all files
2. adds the `netdata` user and group
3. creates the needed directories (/var/cache/netdata, /etc/netdata)

So, what else do we need?

**Comment by SanskritFritz** [comment]
@alonbl Thanks, I forgot about the DESTDIR directive.

**Comment by SanskritFritz** [comment]
@cyayon Why is your package not on AUR?

**Comment by cyayon** [comment]
I will... :-) perhaps tomorrow.

--
Christophe Yayon

**Comment by SanskritFritz** [comment]
I have published my netdata-git package just now.
