### ISSUE TITLE
badges auto-refresh

### ISSUE THREAD

**Issue by glensc** [firehol/netdata#492]
https://github.com/firehol/netdata/wiki/Generating-Badges#can-badges-auto-refresh
> > Can badges auto-refresh?
> _No_

have you thred "Refresh: 60" http header?
https://en.wikipedia.org/wiki/URL_redirection#Refresh_Meta_tag_and_HTTP_refresh_header

**Comment by ktsaou** [comment]
Nice! I didn't know this feature.
It will not work on github though. Github has its own proxy to serve all images. So they fetch the image, they strip stuff they don't like, and they generate different URLs for all images. This is why the badges come with slight delay too.

I'll give it a try...

**Comment by ktsaou** [comment]
done...

**Comment by ktsaou** [comment]
updated the registry too.
Yeap, auto-refreshing of images in github does not work.

**Comment by ktsaou** [comment]
and guess what... it does not work on chrome and firefox. It works only if you fetch the image directly. If you add it to a page, they don't auto-refresh...

**Comment by ktsaou** [comment]
I added a simple javascript solution at the wiki.
