### ISSUE TITLE
Deprecated -pidfile option is used in netdata.service

### ISSUE THREAD

**Issue by SanskritFritz** [firehol/netdata#497]
```ExecStart=/usr/bin/netdata -pidfile```
should be 
```ExecStart=/usr/bin/netdata -P```
in
/usr/lib/systemd/system/netdata.service
because the log states:
```netdata[2649]: /usr/bin/netdata: deprecate option -- -pidfile -- please use -P instead.```
(BTW the error message also contains a typo: 'deprecate' should be 'deprecated')

**Comment by isonet** [comment]
I created a pull request for this issue: #500 
I hope this is ok.

**Comment by ktsaou** [comment]
This is merged, so I close it.
