### ISSUE TITLE
openrc script

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#50]
I have added an openrc script:

https://github.com/firehol/netdata/blob/master/system/netdata-openrc

@alonbl could you please check it?

If tried to implement a dynamic dependency check, so that netdata will `use` other services only if these services are enabled.

I also tried to switch ownership of files if the netdata user is changed.

Any comments are welcome.

**Comment by alonbl** [comment]
when pushing something for review, please issue a pull request on your behalf, easier to review.

**Comment by alonbl** [comment]
mostly same as systemd:

1. it should be a template to replace autoconf/automake file locations and other fields.
2. shell usage: escape all variables.
3. use after keyword for all these that are optional instead of the hack.
4. I think I sent you an example of an service, you should not call start-stop-daemon directly and should not fork your program, use:
```
pidfile="/var/run/xxx.pid"
command="xxxx"
command_args="start or any other parameters for foreground"
command_background="yes"
start_stop_daemon_args="--user user:group"

depend() {
	use logger
	need net
        after apache2
}

start_pre() {
	mkdir -p /var/cache/xxx
	chown user:group /var/cache/xxx
}
```
5. all the logic of storing configuration file from the running daemon is highly non standard and should be avoided. in any case, if you like this it is common to both systemd and openrc, so you should move it to own script that perform the start/stop and wraps the daemon which in both case will be non forking.
6. at least in gentoo, such package should be implemented as webapp, using apache cgi/fcgi and not run its own daemon, and integrated with vhost[1]

[1] https://wiki.gentoo.org/wiki/Webapp-config

**Comment by ktsaou** [comment]
ok, this response is big because I think you have missed something.

## webapp (point 6)
- netdata is a data collector daemon, much like `collectd`.
- netdata is a timeseries database, much like (but of course more limited than) opentsdb, influxdb or even mysql. It provides a REST API to query this database.
- netdata is a web server, much like (but more limited than) apache.

netdata is a not a webapp. It does not have any server-side scripting. Its web content is static files that are transferred to web browser as-is. netdata serves this content using its internal web server mainly to avoid CORS (cross site scripting) overheads. It will work if this content is served by another web server, but under certain cases it will slower (CORS adds an OPTIONS request before every GET).

So, it cannot be implemented as cgi/fcgi and it should not be implemented to run entirely under a different web server (it is like saying that because `named` has a web interface, it should be running under apache as cgi - no it should not).

## using the `after` keyword (point 3)
According to the documentation, the `after` dependency will stop netdata if any of the processes it is `after` is stopped. I needed a way to say:

1. start netdata at the end of everything else (the other have to be started first, or the performance collectors for them will fail)

2. do not stop netdata if any other process stops

Why? Let's say you monitor your system metrics, apache2 and mysql with netdata. You normally don't want to stop monitoring your system because you want to stop apache for a while. The netdata collector that talks to apache will fail and stop, but the rest of them will work.

So, I ended up checking `/etc/runlevels` if other processes, for which netdata has performance collectors, are enabled. For those that are enabled I used the `use` keyword, which according to the docs (and my tests) netdata will not be stopped if any of the processes in its `use` list, are stopped.

Of course I am open to other ideas. I couldn't find an official solution to this.

## Configuration (point 5)
Netdata does not need a configuration file (an empty one will do just fine).

The configuration file is a `name = value` dictionary. You cannot predict it (except the global section at the top). netdata autodetects everything at run time. This is an advantage: you get perfect performance monitoring for everything on your system, without configuring anything (actually this zero-configuration and auto-detection of everything was your idea a month ago - which I found fascinating!).

So, to find what configuration options are available, we have to start netdata, which will start all its data collectors, wait a few seconds for everything to be to initialized, and then check the dictionary for settings found on your system. Based on what it found, you can start tweaking settings.

If we don't do it this way, the admin will have to go through a series of configuration steps which are totally unnecessary. Check this [configuration file](http://netdata.firehol.org/netdata.conf). There is no way for someone to write all these by hand.

I don't think this way of auto-configuration is wrong. We just need to find a way to save this file the first time netdata starts on a system.

## escaping variables (point 2)
The variables at the top of the openrc file should reflect the contents of the file `/etc/conf.d/netdata`. The script works. What to escape?

## start-stop-daemon (point 3)
I tried it and it didn't work. So, I saw what mysql and apache2 were doing and did the same thing.
I'll give it a try again.

## templating (point 1)
If you do the systemd one, I'll try to learn what you did and adapt this one.

Thanks!
