### ISSUE TITLE
Netdata not showing Network Interfaces / ipv4 on Ubuntu Xenial

### ISSUE THREAD

**Issue by rc55** [firehol/netdata#502]
Hi,

I've installed netdata and successfully configured Nginx to handle the incoming traffic with authentication. Regardless of it running under Nginx or not, I cannot get netdata to show per interface traffic, it is not listed on the right hand jump menu.

Any help greatly appreciated.

Kind regards,

Ruairi

**Comment by ktsaou** [comment]
Hi,

is it running in a container?

Netdata reads `/proc/net/dev`. This is mine:

```sh
 # cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 234391449915 1432405347    0  412    0     0          0   2400573 2494162731217 2267669143    0   47    0     0       0          0
dsl0-ifb: 79797965002 191817552    0    0    0     0          0         0 79797965002 191817552    0    0    0     0       0          0
docker0:  244643    4262    0    0    0     0          0         0 10235494    6959    0    0    0     0       0          0
  dsl0: 80150484347 192068655    0    0    0     0          0         0 77377242876 161736893    0    0    0     0       0          0
  eth2: 84385052013 192202477    0    0    0     0          0     71435 81051873450 162438029    0    0    0     0       0          0
vethab85279:     648       8    0    0    0     0          0         0    29001      37    0    0    0     0       0          0
gstag0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
    lo: 13429745227 40536729    0    0    0     0          0         0 13429745227 40536729    0    0    0     0       0          0
realize: 45148093   67354    0    0    0     0          0         0  8098535   60298    0    0    0     0       0          0
exohiko0: 168065030  765423    0    0    0     0          0         0 78620059  765301    0    0    0     0       0          0
```

What is yours?

Check also its permissions. This is mine:

```sh
# ls -l  /proc/net/dev
-r--r--r-- 1 root root 0 Jun  6 20:44 /proc/net/dev
```

**Comment by rc55** [comment]
Thank you for the reply. It's not in a container.

```
# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
 teql0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0: 142533716232 1097890367    0    9    0     0          0    953944 3491947956886 2361189995    0    0    0     0       0          0
dummy0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 bond0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  ifb0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
ip6tnl0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  ifb1:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  sit0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
    lo: 13086314   45197    0    0    0     0          0         0 13086314   45197    0    0    0     0       0          0
 tunl0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0

```

```
# ls -l  /proc/net/dev
-r--r--r-- 1 root root 0 Jun  7 13:06 /proc/net/dev
```

**Comment by ktsaou** [comment]
ok, eth0 should be there.

Is there in your error.log about eth0?

```sh
grep eth0 /var/log/netdata/error.log
```

Is it enabled in your netdata.conf?

```sh
curl http://localhost:19999/netdata.conf | less
```

search for eth0 (press `/eth0` while in less). Does it say anything about it?

**Comment by rc55** [comment]
The error.log does not mention eth0, however there are a lot of other errors:
[(https://gist.github.com/rc55/0abceefcba74cdef6fc4af80590018eb)]

The netdata.conf is pretty much default, I tried to mirror the examples set up on the demo servers.

**Comment by rc55** [comment]
It's possibly related to this:
`https://github.com/firehol/netdata/issues/280`

I have configured it to run with systemd, however the linked issue doesn't have a clear resolution, unless I'm missing something.

**Comment by ktsaou** [comment]
Do you have selinux or apparmor installed?

**Comment by ktsaou** [comment]
@philwhineray any ideas?

**Comment by rc55** [comment]
# apparmor_status
apparmor module is not loaded.

sestatus
The program 'sestatus' is currently not installed. You can install it by typing:
apt install policycoreutils

**Comment by ktsaou** [comment]
hm... may be grsecurity?

```sh
sysctl -a | grep grsecurity
```

does it print anything?

**Comment by ktsaou** [comment]
we have seen grsecurity in #434

**Comment by rc55** [comment]
#sysctl -a | grep grsecurity
kernel.grsecurity.audit_ptrace = 1
kernel.grsecurity.consistent_setxid = 1
kernel.grsecurity.deny_new_usb = 0
kernel.grsecurity.dmesg = 1
kernel.grsecurity.forkfail_logging = 1
kernel.grsecurity.grsec_lock = 0
kernel.grsecurity.harden_ptrace = 1
kernel.grsecurity.ptrace_readexec = 1
kernel.grsecurity.signal_logging = 1
kernel.grsecurity.timechange_logging = 1

**Comment by rc55** [comment]
Hi, I've just tried the amendment in #434, after which the issue appears to be resolved.

edit /etc/netdata/netdata.conf and set:

> [global]
> run as user = root
> web files owner = netdata
> web files group = netdata

Then the following:
service netdata restart

**Comment by ktsaou** [comment]
ok, just keep in mind you now run netdata as root.
Ideally, you should not want this permanently. Why don't you configure grsecurity properly? (I don't know how - I think there is `gradmin` to do this)

**Comment by paulfantom** [comment]
And now every script runs as root.

**Comment by ktsaou** [comment]
And if you find a way, please post it here, so that others can benefit from your time.

**Comment by paulfantom** [comment]
It would probably better to set something like `GRKERNSEC_PROC_GID` to your `netdata` group.

**Comment by rc55** [comment]
> ok, just keep in mind you now run netdata as root.
Ideally, you should not want this permanently. Why don't you configure grsecurity properly? (I don't know how - I think there is gradmin to do this)

Apologies for any frustration, this is how the server was pre-configured by my provider.

**Comment by rc55** [comment]
> Probably it would be better to set something like GRKERNSEC_PROC_GID to your netdata group.

I have tried to figure out how to do this, I haven't had much luck. Any ideas?

**Comment by paulfantom** [comment]
You can assign netdata GID to `grsec_proc_gid=` in grub kernel command line.

**Comment by ktsaou** [comment]
@rc55 more info: https://en.wikibooks.org/wiki/Grsecurity/Appendix/Grsecurity_and_PaX_Configuration_Options#Default_Special_Groups

**Comment by paulfantom** [comment]
@rc55 did you manage to solve this?

**Comment by ktsaou** [comment]
Let's close this. @rc55 if you need help, just post.
