### ISSUE TITLE
C++ plugin throwing Error(13)

### ISSUE THREAD

**Issue by sam0302** [firehol/netdata#506]
Hello,

I have written a C++ plugin and placed at location /usr/libexec/netdata/plugin.d/ folder. When running the plugin from bash, I can see the output printed properly, however, when i run the netdata, I see below error in the error.log

ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/connPlugin.plugin' is sending command 'Error(13)' which is not known by netdata. Disabling it.

what could be the reason? Please suggest.

**Comment by ktsaou** [comment]
Your plugin is printing `Error(13)` on its standard output when run by netdata (and as user netdata). Your plugin prints this. So, I don't know what error 13 is.

**Comment by sam0302** [comment]
Ok, The issue was my plugin was trying to read a directory which did not had sufficient permission.
anyway thanks for the help.

**Comment by ktsaou** [comment]
nice you solved it.
