### ISSUE TITLE
data resolution for disk_space datasource

### ISSUE THREAD

**Issue by DrGkill** [firehol/netdata#508]
When `disk_space` datasource is called with second resolution, a minute resolution is given :

```
curl 'http://localhost:19999/api/v1/data?chart=disk_space.sda1&points=60&options=seconds'
{
        "labels": ["time", "avail", "reserved for root", "used"],
        "data":
        [
                [ 1465224120, 9.67699, 0.72065, 4.14516],
                [ 1465224060, 10.47882, 0.72065, 3.34141],
                [ 1465224000, 10.47882, 0.72065, 2.55448],
```

It may not be an issue but only a large scheduled tick to avoid performance issues ?

**Comment by ktsaou** [comment]
`points=60` means: give me 60 points for the whole database. So, if you have a database of 3600 seconds / 60 points requested = 60 seconds per point.

**Comment by ktsaou** [comment]
If you want the last minute of data per second, use `after=-60`.

**Comment by DrGkill** [comment]
Ok cool ! Thanks !
