### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#51]
Added systemd service

https://github.com/firehol/netdata/blob/master/system/netdata-systemd

@alonbl any comments?

Do I need a Makefile.am in the system directory?

**Comment by alonbl** [comment]
I am not a master in systemd, however:

1. this should be a template a .in.in for autoconf to subst and automake to subst, for example: the user, group, the localstatedir etc...
2. when using systemd you should not go into background, as systemd monitors the process.
3. you should use pre-start command to create the /var/run directory as root.
4. you should run your daemon as unprivileged user.
5. you should log into stdout/stderr instead of syslog if possible.
6. usually we call this unit :)

If you fix all above except of (1), I will embed it and fix (1).

**Comment by ktsaou** [comment]
Thanks!

## running as a different user (point 4)
netdata starts as root and switches to the user given in its config. The admin can control the user to switch to from `netdata.conf` or the command line. So, there is no need to start it as another user. 

In general I prefer to start netdata as root and then switch to another user. If I am correct, netdata could spawn data collector childs as root (the ones that require it), and then switch the main process (and the internal web server) to another user. This will allow processes in its process tree to have different capabilities, even if they are shell scripts.

## backgrounding (point 2)
I read that the `forking` type in systemd works well, as far as the daemon is writing a pid file which is stated in the unit file. I tested this config and it works. systemd does monitor it properly.

To start netdata without forking passing the parameter `-nd` is enough. But I think it is not needed.

## create /var/run as root (point 3)
The netdata daemon already does this (as root, before switching to another user).

## syslog (point 5)
The netdata daemon already does this (syslog is off by default and is controlled by its config file).

## Unit (point 6)
ok. Shall I rename the file?

## templating (point 1)
Thanks! Please do so!

**Comment by alonbl** [comment]
Hi,
I do not think you understand.
The forking and switch user behavior belongs to the "old world", openrc and systemd are both taking care of what used to be taken care by daemon and in more secure manner.
Your daemon should not fork, this also removes complexity and errors from daemon.
Your daemon should not not run as root at all as far as I understand, you can set capabilities to the unprivileged process as well using systemd/openrc.
If you must have root, probably you need two daemons, one for the application and the other to perform privileged operations, it may modify your design, but this is how we write privilege escalation these days.
Using internal web server is also something that should be avoided if possible, as the amount of bugs we see in custom http handling is huge.
Regards,

**Comment by philwhineray** [comment]
I appreciate you were asked for comments and have done just that.

In practice I think larger design questions belong in their own bugs where they can be addressed according to resources, peoples interest etc. and proposed solutions evaluated on merit.

The question here is does the proposed packaging do an adequate job for the program as written?

**Comment by SanskritFritz** [comment]
```ExecStart=/usr/sbin/netdata``` should not be hardcoded, I install netdata into /usr/bin.

**Comment by ktsaou** [comment]
Yes, this is templating @alonbl talked about.
Hopefully, either @alonbl or @philwhineray I hope will help...

**Comment by SanskritFritz** [comment]
Ah again I missed something and talked too early. Sorry for the noise.

**Comment by alonbl** [comment]
I will try to do this next week-end.

**Comment by SanskritFritz** [comment]
The new template works great. Just one minor cosmetic grip: /bin/kill is still hardcoded. Archlinux has all binaries in /usr/bin, and /bin is a symlink to that. So everything works without problem, I just thought it would be nice to have /usr/bin/kill nevertheless in my package. I know the standard is /bin/kill, so if you don't change it, it is perfectly OK with me.

**Comment by alonbl** [comment]
@SanskritFritz: we are working on improving this see #163

**Comment by ktsaou** [comment]
Cleaning up. If something remains open it up again.
