### ISSUE TITLE
How to retrieve the statistics of the app read/write on disk

### ISSUE THREAD

**Issue by phamhp** [firehol/netdata#512]
Hi there,
I have an application, and I would like to get the statistic of read/write, network sent/receive and memory. So, I follow the trick on issue #217. 
With issue #217 , I can access get application CPU statistics in HTML page by using the command , 
http://127.0.0.1:19999/api/v1/data chart=apps.cpu&before=0&after=-600&options=seconds&format=html ( and it works)
Howerver, If i replace the word (apps.cpu with apps.disk , apps.swap, apps.net), I can not retrieve the HTML page, 
I got the error : Chart 'apps.disk' is not found.

Please take a look, 
Thank you

**Comment by ktsaou** [comment]
Hi, there is no chart `apps.disk`. There are many disk charts for apps, with different names. Goto to the dashboard, and at the title of chart you are interested, you will find its id in parentheses.

![image](https://cloud.githubusercontent.com/assets/2662304/15884147/f4a9c51c-2d56-11e6-814a-2833cc21a66d.png)

**Comment by phamhp** [comment]
Hi @ktsaou 
Thank you for the help.

**Comment by ktsaou** [comment]
No windows yet. But it runs on bash on Windows, the upcoming windows release.
