### ISSUE TITLE
sensors.chart.sh grabbing too much data

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#514]
I have about 30 sensors in my system, but I don't want every data from every sensor. So I set a couple of sensors to `enabled = no` in netdata.conf. However when setting this option, `sensors_create()` still creates `sensors_update()` for all my sensors. Is there any option I can set to disable or enable some sensors?

**Comment by ktsaou** [comment]
Unfortunately the only way currently is to copy `sensors.chart.sh` and adapt it to your needs. You will have to change all `sensors*` functions, variables and chart names to something else.

I am sure we have to find a better way.

**Comment by paulfantom** [comment]
There is a function `sensors_check_files()` which I think can be adapted to exclude not needed sensors.

For example there can be added an array `sensors_excluded` with excluded sensor points and modified `sensors_check_files()` to this version:

```
declare -A sensors_excluded=()
sensors_excluded[0]="coretemp.0/hwmon/hwmon0/temp2_input" #just an example

sensors_check_files() {
        # we only need sensors that report a non-zero value
        # also remove not needed sensors

        local f= v=
        local excluded=
        for f in $*
        do
                [ ! -f "$f" ] && continue
                for ex in ${sensors_excluded[@]}; do
                        [[ $f =~ .*$ex$ ]] && excluded='1' && break
                done

                [ "$excluded" != "1" ] && v="$( cat $f )" || v=0
                v=$(( v + 1 - 1 ))
                [ $v -ne 0 ] && echo "$f" && continue

                echo >&2 "$PROGRAM_NAME: sensors: $f gives zero values"
        done
}
```
And `sensors_excluded` can be set in `/etc/netdata/sensors.conf`. But I don't know what is the proper way to load this config file into the script.

**Comment by ktsaou** [comment]
the file `/etc/netdata/sensors.conf` is loaded by `charts.d.conf`, so this is good approach.
Can you make a PR?

**Comment by paulfantom** [comment]
I forgot to reset `excluded` variable. But now it is ok. I have tested PR #515 and it is working.

**Comment by paulfantom** [comment]
I have another question. Auto-generated file `$TMP_DIR/sensors.sh` uses `printf` and `cat` for updating variable in `sensors_update()`. Would netdata benefit from changing it from:
```
printf "SET sys_devices_platform_w83627ehf_656_temp1_input = "; cat /sys/devices/platform/w83627ehf.656/temp1_input
``` 
to 
```
echo "SET sys_devices_platform_w83627ehf_656_temp1_input = "$(< /sys/devices/platform/w83627ehf.656/temp1_input )
```

Basically using bash to read file instead of invoking `cat` multiple times.

**Comment by ktsaou** [comment]
nice! thanks!
Please submit a PR.
I have merged #515

**Comment by paulfantom** [comment]
Already done in #516

**Comment by ktsaou** [comment]
merged it
