### ISSUE TITLE
Error: "Access to file '' is not permitted."

### ISSUE THREAD

**Issue by SanskritFritz** [firehol/netdata#52]
I have started netdata, copied the default config to /etc/netdata, but I get this error in the browser:
```Access to file '' is not permitted.```
Here is the log:
https://gist.github.com/153990a3fae7b3010c62
Please help me fixing this.

**Comment by ktsaou** [comment]
I don't see it.
At which line number?

**Comment by ktsaou** [comment]
I think it was given to you on your browser.

Can you give me the URL that caused netdata response with this?

**Comment by ktsaou** [comment]
I see in the code that message can be given if the web files are not owned by the user netdata runs.

If you installed netdata on your system, the web files should be at `/usr/share/netdata/web`.

Check the directory and its contents.
If netdata runs as user `netdata`, this directory and its contents should be owned by this user too.

**Comment by ktsaou** [comment]
I added a log line to error log for this. The line states the path to the problematic filename its current owner and the wanted one.

**Comment by SanskritFritz** [comment]
Thanks, I see. I missed setting the permissions in my package. However, I find it strange that those files are not readable by netdata. Does the program try to change any file under /usr? Because all files are visible by any user in the system, even if they are root owned.

**Comment by ktsaou** [comment]
> However, I find it strange that those files are not readable by netdata.

The internal web browser of netdata refuses to serve files not owned by its user. Security rules.

**Comment by SanskritFritz** [comment]
I see, thanks for the info. Now it works beautifully here too.

**Comment by Porco-Rosso** [comment]
Hi I'm having troubles with the same issue, what exactly did you run?
Nether 
`chown root -R /root/netdata/netdata/usr`
Nor
`chown netdata:netdata -R /root/netdata/netdata/usr`
Help

(I ran the install to the folder `~/netdata`)

**Comment by ktsaou** [comment]
netdata drops its privileges when started.
It becomes user `netdata`.
So, install it outside `/root` (prefer `/tmp` if you plan to delete it later).
If you really want to start it as root, add `-u root` to the command line, but I strongly suggest against this practice.

**Comment by Porco-Rosso** [comment]
Just got it up and running, thanks! I'm still learning the ropes.

**Comment by quixand** [comment]
"netdata drops its privileges when started. It becomes user netdata."
This is a very important bit of info.

**Comment by Fleetside58** [comment]
I installed Netdata as a sudoer, everything in `/usr/share/netdata/web` is owned by user `netdata`, but I am still getting 'access to file not permitted'. Do I have to run `/usr/sbin/netdata` AS user `netdata`?

**Comment by SanskritFritz** [comment]
On Wed, Nov 16, 2016 at 5:29 AM, Fleetside58 <notifications@github.com>
wrote:

> I installed Netdata as a sudoer, everything in /usr/share/netdata/web is
> owned by user netdata, but I am still getting 'access to file not
> permitted'. Do I have to run /usr/sbin/netdata AS user netdata?
>
No, by default netdata drops to the netdata user when you run it as root,
unless you configured it differently. I run netdata from systemd with no
special settings:

root@HomeC ~# ps -ef | grep netdata
netdata  23194     1  0 10:36 ?        00:00:01 /usr/bin/netdata -D
netdata  23200 23194  0 10:36 ?        00:00:00 bash
/usr/lib/netdata/plugins.d/tc-qos-helper.sh 1
netdata  23209 23194  0 10:36 ?        00:00:01
/usr/lib/netdata/plugins.d/apps.plugin 1
netdata  23215 23194  0 10:36 ?        00:00:01 /usr/sbin/python
/usr/lib/netdata/plugins.d/python.d.plugin 1
netdata  24335 23200  0 10:41 ?        00:00:00 sleep 0.994
root     24343 23156  0 10:41 pts/4    00:00:00 grep --color=auto netdata

**Comment by ktsaou** [comment]
Get `http://your.netdata.ip:19999/netdata.conf and seek for these 2 options:

```
[global]
	# run as user = 
	# web files owner = 
```

If they are empty, like the ones above, user `netdata` is assumed. If they are not empty, these are the permissions the web files should have.

Check also `/var/log/netdata/error.log`, it should give you some info.
