### ISSUE TITLE
Haproxy Plugin

### ISSUE THREAD

**Issue by leepfrog-ger** [firehol/netdata#522]
I'd love to see a plugin for HAproxy (stuff like traffic, connections/requests per second, http status code counts, etc)
Haproxy can expose statistics through a unix socket

**Comment by ktsaou** [comment]
Hi, I don't use HAProxy.

If you can provide the commands to collect statistics and sample output of these commands, we could write a BASH data collector for it.

**Comment by Flums** [comment]
HaProxy produces a site called haproxy-status where data is posseble to collect. A demo for the site can be found here: http://demo.haproxy.org/

Haproxy can have multiple frontends and backends. I would also love to see a Haproxy plugin.

**Comment by paulfantom** [comment]
It would probably be easier to use CSV format presented by haproxy-stats combined with `norefresh` option. ex.:
http://demo.haproxy.org/;csv;norefresh

**Comment by ktsaou** [comment]
> http://demo.haproxy.org/;csv;norefresh

this seems easy. If you know which info you need, a plugin will be just an `awk` statement.

**Comment by Flums** [comment]
You want all the "Curr" field (compare CSV to webpage), and bytes at least.

**Comment by Flums** [comment]
You would also want to read configuration from /etc/haproxy/haproxy.cfg (or *.cfg). These sites is normally password protected. It looks like this:

stats uri     /haproxy-status # try IP/{url from "stats uri"}
stats auth    balancer:fjalacer # user:password for accesing csv

**Comment by ktsaou** [comment]
So,

a section (submenu on the dashboard) for each `pxname`, with 4 charts ( `qcur`, `scur`, `bin`, `bout` ), with dimensions all the values of `svname`?

in the demo example:

- haproxy
  - http-in
    - chart for `qcur` with dimensions: `FRONTEND`, `IPv4-direct`, `IPv6-cached`, `IPv6-direct`, `local`, `local-https`
    - another for `scur` (same dimensions)
    - another for `bin` (same dimensions)
    - another for `bout` (same dimensions)
  - www
  - git
  - demo

This is it?

**Comment by paulfantom** [comment]
You can do it without `awk` just use `IFS=','` and load it to bash arrays.

**Comment by ktsaou** [comment]
> You can do it without awk just use IFS=',' and load it to bash arrays.

Yeap, but I think will be slower.

**Comment by leepfrog-ger** [comment]
From my understanding reading data from the stats page is less than optimal. Using sockets should be muss easier and less error prone: https://www.datadoghq.com/blog/how-to-collect-haproxy-metrics/

**Comment by paulfantom** [comment]
It could support both methods. Using `echo "show stat" | nc -U /var/run/haproxy.sock` presents the same data as from `http://<host>/;csv;norefresh`

**Comment by paulfantom** [comment]
It's been a month but I have created initial version of haproxy module (available in #784). However it is not ready to be merged because I don't have any haproxy instance. @Flums @leepfrog-ger can you test it?
This will need some testing with access via url and unix socket (sample configuration provided in `/etc/netdata/python.d/haproxy.conf` file.

**Comment by leepfrog-ger** [comment]
Thanks for taking the time to write an initial configuration @paulfantom 
I hope I find time to test your version within the upcoming week. I'll let you know the results

**Comment by l2isbad** [comment]
This one can be closed now @ktsaou
