### ISSUE TITLE
Package manager for javascript dependencies

### ISSUE THREAD

**Issue by isonet** [firehol/netdata#524]
I think it might be a good idea to use either bower or npm to manage all the javascript libraries in /web/lib .
If you think this would be a good idea I could start working on it.

**Comment by ktsaou** [comment]
Hi, this is a nice idea. I can think of 2 issues:

1. Updates to the package may break netdata

2. The installation procedure will have to change - users will be required to have `bower` or `npm` installed. This is the main issue currently, since netdata is being downloaded more than 800 times per day from github. Currently netdata runs even on old system (kernel 2.6) or even embedded devices (routers, NAS, etc).

Can you think of any solutions to these?
One solution could be to provide the files (as we do now) and allow the user to update them using `bower` or `npm`?
Any other ideas?

**Comment by paulfantom** [comment]
Please don't request users to install `bower` or `npm` on their machines. I have couple of machines on which I use `netdata` and I really don't want to have those programs just to update `netdata`.

**Comment by ktsaou** [comment]
> Please don't request users to install bower or npm on their machines. I have couple of machines on which I use netdata and I really don't want to have those programs just to update netdata.

This is why I said optionally use them. You will not have to, but you could.

**Comment by isonet** [comment]
I completely agree that this should be optional.

As I see it there are 3 options:

1. Download the javascript files during installation / make with curl from either github or a CDN.
2. Use npm or bower 
3. Use a CDN

I think using npm or bower for a project that is supposed to have few dependencies is the wrong approach.
The best option in my opinion would be to use a CDN, netdata would be a lot smaller and it wouldn't have to serve all these files. This might actually help a lot for embedded devices which don't have a lot of space.
The problem with this is offline usage and enterprise networks.

We could circumvent this problem by combining solution 1 and 2 and offering the user the choice during the installation.

These are just some ideas I had, I'm open for any feedback.

**Comment by ktsaou** [comment]
Keep in mind that we need netdata to be operational with no internet connection available. This actually removes option 3 (use a CDN at runtime).

I still think the solution we have chosen so far (i.e. package the files with netdata) is the simplest and most reliable solution. We have increased a bit the size of the package, but after evaluating the pros and cons of each solution, I still think pre-packaging them is the simplest and more reliable.

**Comment by paulfantom** [comment]
My two cents:
I agree about bower/npm. Also packaging would be easier without them.

I don't think that introducing CDN just to slim netdata of a few kilobytes (whole `web` folder is about 3.3M and `lib` subfolder is about 804K ) is a way to go. Especially if it creates a lot of new problems.


...and @ktsaou was faster in saying the same:)

**Comment by chagara** [comment]
yes, this will cause a whole mess for uss that use it offline.
