### ISSUE TITLE
Error 405: Cannot download charts index from server:  http://172.18.200.21:19999/api/v1/charts

### ISSUE THREAD

**Issue by dwalst** [firehol/netdata#529]
#475 
Hello, I am receiving the following errors on RHEL 7 when I try to connect to the web dashboard and would like to know where I would put the suggested netdata.conf file on RHEL 7 as RHEL 7 does not have an "/etc/init" FS/Dir.  

-Error 405: Cannot download charts index from server: http://xx.xxx.xx.xxx:19999/api/v1/charts
-Cannot load required JS library: http://xx.xxx.xx.xxx.19999/lib/bootstrap.min.js

**Comment by ktsaou** [comment]
netdata.conf should be `/etc/netdata/netdata.conf`.

Regarding the error 405, your should check your `/var/log/netdata/error.log`. Access the dashboard and check what this file says. It should complain.

Also please fetch this  `http://xx.xxx.xx.xxx:19999/api/v1/charts` and post the result here.

**Comment by dwalst** [comment]
The  /etc/netdata/netdata.conf is there.
The last few lines of my error.log is as follows:
16-06-10 11:16:08: ERROR: netdata: File /var/cache/netdata/netdata.response_time/response_time.db is too old. Clearing it.
16-06-10 11:16:08: ERROR: netdata: File /var/cache/netdata/netdata.compression_ratio/savings.db is too old. Clearing it.
16-06-10 11:16:12: ERROR: apps.plugin: Cannot process /proc/28332/stat (errno 2, No such file or directory)
16-06-10 11:16:18: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 28446
16-06-10 11:16:18: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/node.d.plugin 1 ' on pid 28446.
/usr/libexec/netdata/plugins.d/node.d.plugin:18: ReferenceError: process is not defined
16-06-10 11:16:18: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' on pid 28446 stopped.
16-06-10 11:16:18: ERROR: netdata: pid 28446 exited with code 3.
16-06-10 11:16:18: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 28446) does not generate useful output. Waiting a bit before
 starting it again.
16-06-10 11:16:19: ERROR: apps.plugin: Cannot process /proc/28455/stat (errno 2, No such file or directory)
16-06-10 11:16:26: ERROR: apps.plugin: Cannot process /proc/28566/stat (errno 2, No such file or directory)
16-06-10 11:16:29: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 28627
16-06-10 11:16:29: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/node.d.plugin 1 ' on pid 28627.
/usr/libexec/netdata/plugins.d/node.d.plugin:18: ReferenceError: process is not defined
16-06-10 11:16:29: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' on pid 28627 stopped.
16-06-10 11:16:29: ERROR: netdata: pid 28627 exited with code 3.
16-06-10 11:16:29: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 28627) does not generate useful output. Waiting a bit before
 starting it again.
16-06-10 11:16:33: ERROR: apps.plugin: Cannot process /proc/28691/stat (errno 2, No such file or directory)
16-06-10 11:16:40: INFO: netdata: Exit main loop of netdata.
16-06-10 11:16:40: ERROR: netdata: pid 27765 killed by signal 13.
16-06-10 11:16:40: INFO: netdata: NetData exiting. Bye bye...

And connecting to  http://xx.xxx.xx.xxx:19999/api/v1/charts responds with "This page cannot be displayed"

**Comment by ktsaou** [comment]
It seems that netdata exits.
I have added some tracing to find out why.
Could you please update your netdata and post again the last view lines of error.log?

**Comment by dwalst** [comment]
Here it is:
# tail /var/log/netdata/error.log
16-06-10 16:37:30: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/ip_vs_stats' (errno 2, No such file or directory)
16-06-10 16:37:30: ERROR: netdata: PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
16-06-10 16:37:30: INFO: netdata: Disabling /proc/net/rpc/nfsd threads histogram. It seems unused on this machine. It will be enabled automatically when found with data in it.
16-06-10 16:37:30: INFO: netdata: Disabling /proc/net/rpc/nfsd read ahead histogram. It seems unused on this machine. It will be enabled automatically when found with data in it.
16-06-10 16:37:30: INFO: netdata: Disabling /proc/net/rpc/nfsd v4 operations chart. It seems unused on this machine. It will be enabled automatically when found with data in it.
16-06-10 16:37:36: ERROR: apps.plugin: Cannot process /proc/26106/stat (errno 2, No such file or directory)
16-06-10 16:37:51: ERROR: apps.plugin: Cannot process /proc/26316/stat (errno 2, No such file or directory)
16-06-10 16:38:06: ERROR: apps.plugin: Cannot process /proc/26538/stat (errno 2, No such file or directory)
16-06-10 16:38:29: ERROR: apps.plugin: Cannot process /proc/26866/stat (errno 2, No such file or directory)
16-06-10 16:38:36: ERROR: apps.plugin: Cannot process /proc/26971/stat (errno 2, No such file or directory)

**Comment by ktsaou** [comment]
Did you access the dashboard? It seems running now.

**Comment by ktsaou** [comment]
Reproduce the error and then give me the log.

**Comment by dwalst** [comment]
[root@REDHATTEST2 netdata]# docker run -d --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p 19999:19999 training/webapp
a8c7df2834f1f334b9be81ea3c40a73bb065085cb98f7b473ccb2e23e4ff0940
[root@REDHATTEST2 netdata]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS                                NAMES
a8c7df2834f1        training/webapp     "python app.py"     About a minute ago   Up About a minute   5000/tcp, 0.0.0.0:19999->19999/tcp   netdata

But I get this when I try to bring up the dashboard 
"-Error 405: Cannot download charts index from server: http://xx.xxx.xx.xxx:19999/api/v1/charts"

**Comment by dwalst** [comment]
Then I get "This page can't be displayed", when I fetch http://172.18.200.21:19999/api/v1/charts

**Comment by ktsaou** [comment]
You run netdata in a docker... hm... I don't know what is wrong.

@titpetric could you please help?

**Comment by titpetric** [comment]
@dwalst - it seems you didn't provide the SYS_PTRACE capability, but there might be other issues just within your docker file and the base image you're working with. Consider using titpetric/netdata as base and then replace/add the entrypoint with a propper control deamon (supervisord)?

**Comment by dwalst** [comment]
Hello Titpetric, thank you for your input above, but I am going to uninstall Netdata and Docker and start from scratch, is there an install guide/walk thru for using Netdata to monitor performance on Docker containers that you can suggest?

Also, are either of these the correct syntax for this command?
docker run -d --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p --cap-add SYS_PTRACE -h 19999:19999 training/webapp

docker run -d --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro --cap-add SYS_PTRACE -h $(Plehbe1) -p 19999

**Comment by dwalst** [comment]
I ran the following and am still receiving the **"-Error 405: Cannot download charts index from server: http://xx.xxx.xx.xxx:19999/api/v1/charts"** error when trying to fetch the Netdocker dashboard:  **docker run -d --name netdata --cap-add SYS_PTRACE -v /proc:/host/proc:ro -v /sys:/host/sys:ro -p 19999:19999 training/webapp****

Also I am unclear what is meant by:
_**Consider using titpetric/netdata as base and then replace/add the entrypoint with a propper control deamon (supervisord)?**_

**Comment by dwalst** [comment]
Ok I got it, I needed the following:
docker run -d --name netdata -v /proc:/host/proc:ro -v /sys:/host/sys:ro --cap-add SYS_PTRACE -h $(hostname) -p 19999:19999 titpetric/netdata

Now I need it to provide monitoring for multiple containers on multiple hosts :)

**Comment by ktsaou** [comment]
To monitor applications within the containers from one netdata you will probably need this: https://github.com/firehol/netdata/issues/474#issuecomment-223142222 when it will be implemented though. The only way to collect application metrics today is via the network (system metrics for applications in containers are already collected)

I am closing this. If you need further help, please post here.
