### ISSUE TITLE
Badges displaying incorrectly

### ISSUE THREAD

**Issue by biff24** [firehol/netdata#535]
I tried to get badges from my my netdata setup and used one the provided examples from the wiki http://192.168.0.111:19999/api/v1/badge.svg?chart=system.cpu&

it turned out like this:
![image](https://cloud.githubusercontent.com/assets/8680108/15982997/2f4ef07a-2f5f-11e6-8143-ceea000def8a.png)

The CPU usage was correct but the formatting of the badge was not correct. After inspecting the badge I saw the width and values were very large.

![image](https://cloud.githubusercontent.com/assets/8680108/15982977/5d0f2b66-2f5e-11e6-93a9-ff017d8ac806.png)

Is this a configuration issue on my part or something else?
This is setup on centos 7.2 and running the newest version of netdata(as of Jun 10th)

Thanks.

**Comment by ktsaou** [comment]
Hi,

Can you try http://shields.io/
The badges displayed from them are ok?

SVG images are vectors and rely on the availability of specific fonts on your machine. netdata calculates the widths based on verdana font. shield.io does the same: https://github.com/badges/shields/blob/master/measure-text.js

In linux you can get the required fonts by installing `corefonts`.

**Comment by biff24** [comment]
https://registry.my-netdata.io/api/v1/badge.svg?chart=system.cpu& and  http://shields.io/ badges are displayed correctly.

I could not find a `corefonts` rpm but i saw `"<g fill=\"#fff\" text-anchor=\"middle\" font-family=\"DejaVu Sans,Verdana,Geneva,sans-serif\" font-size=\"11\">"` in web_buffer_svg.c so i installed `dejavu-fonts-common.noarch 0:2.33-6.el7       dejavu-sans-fonts.noarch 0:2.33-6.el7       dejavu-sans-mono-fonts.noarch 0:2.33-6.el7`

That fixed several of the values
![image](https://cloud.githubusercontent.com/assets/8680108/15985841/c3efbe02-2fbf-11e6-8f33-534d7601fed6.png)

but there is still one value that is not being properly calculated.

**Comment by ktsaou** [comment]
I have merged a fix. Could you please check it?

**Comment by biff24** [comment]
Works great now after the fix! Netdata is one awesome tool I look forward to watching it grow.

**Comment by ktsaou** [comment]
Thanks!
