### ISSUE TITLE
Mips64 version

### ISSUE THREAD

**Issue by gruselglatz** [firehol/netdata#54]
Hi,

is there someone with cross-compiling skills who can make a mips64 package for debian squeeze to run this on a router? (like Ubiquiti Edge Router)

Thanks for the help

**Comment by ktsaou** [comment]
Did you manage to do it?
I see netdata has been released in various NAS and router boxes, so it definitely works.
If you need help, it is probably better to open a new issue now as netdata now has a much bigger user-base.

I am closing this.
