### ISSUE TITLE
Configuration files in different folders.

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#545]
Maybe there should be a slightly different structure of storing configuration files. Currently we have every config file stored in one directory. I propose one main directory with `netdata.conf` and in this directory subdirectories like `charts.d`, `node.d`, `python.d` etc. This way we won't have problems with different plugins accessing the same configuration file.

**Comment by ktsaou** [comment]
I agree.

**Comment by ktsaou** [comment]
Let's start with python.d and we will fix the rest later.
Can you do it?

**Comment by ktsaou** [comment]
Also I suggest the example plugin to be disabled by default. There is no point to load python just for that.

**Comment by ktsaou** [comment]
Regarding the configuration,

in charts.d.plugin there is a configuration file just for specifying which modules you want loaded: `charts.d.conf`.

I think we should have a similar one for python: `python.d.conf` and this should not be inside the python.d directory. Probably the `python.d` configuration directory should be specified inside `python.d.conf`.

The default should be to enable all plugins except `example`.

Can you do this too?

**Comment by paulfantom** [comment]
Yes, but not today. 
My team is playing today in EURO2016 :)

**Comment by ktsaou** [comment]
no problem. Anytime you like.

**Comment by paulfantom** [comment]
Currently `python.d.plugins` searches for configuration file `python.d.conf` with variables named:
- enable
- plugins_config_dir
- plugins_dir
- interval # this one probably should be deleted
- debug # this one I will delete

To prevent loading all modules (current state) I propose to add variable `disable` with comma separated list of disabled modules and default state of: `disable = example`

About multiple configurations per module in python. 
I am testing `mysql.chart.py` with multiple servers in mind and my configuration file have something like:
```
config = [
    {
        'name'     : 'local',
        'user'     : 'root',
        'password' : 'blablablabla',
        'socket'   : '/var/run/mysqld/mysqld.sock'
    },
    {
        'name'     : 'remote',
        'user'     : 'netdata',
        'password' : 'blablablabla',
        'host'     : 'some.remote.ip',
        'port'     : '3306'
     }]
```
How it works:
- `python.d.plugin` loads `config` variable as if it is in INI file and passes it as a string to `mysql.chart.py`
- `mysql.chart.py` converts it from string to list of dictionaries using json parser.

I will later investigate switching namespaces in python.

**Comment by paulfantom** [comment]
Regarding storing configuration files I think we should apply your idea of storing plugins `.conf` files (like `python.d.conf`) outside of modules directories to every plugin. This way we would have something like this tree:
```
main
\_charts.d
  \_mysql.conf
  \_sensors.conf
  \_etc.
\_node.d
\_python.d
  \_mysql.conf
\_charts.d.conf
\_netdata.conf
\_node.d.conf
\_python.d.conf

**Comment by ktsaou** [comment]
yes, that is what I had in mind

**Comment by paulfantom** [comment]
Back to this issue. I believe it should be finished before releasing version 1.3.
I will try to fix this for `charts.d`, but `node.d` is yours.

**Comment by ktsaou** [comment]
I think it is fixed already. What is missing?

**Comment by ktsaou** [comment]
The installer moves the files to the proper location and `charts.d.plugin` searches in both locations. `node.d.plugin` does not, but I think there is no need to. I have not seen any node.js plugins apart the ones I wrote.

**Comment by ktsaou** [comment]
I think we can close this. @paulfantom check it and report back.

**Comment by paulfantom** [comment]
ok, perfect. We should write somewhere about storing configuration files in specific folders.
