### ISSUE TITLE
Squid prevent logging of netdata requests

### ISSUE THREAD

**Issue by josealgardataborges** [firehol/netdata#548]
We now have squid3 charts in netdata working, but everytime netdata requests info, we have a new line added to the squid3 log, like so:

`cache_object://127.0.0.1/counters`

How can we prevent this line from being added to the logs (in our case MySQL logs)?

Anyone knows?

**Comment by paulfantom** [comment]
I am no squid expert but as far as I can see `squid.chart.sh` is executing `squidclient -h 127.0.0.1 -p $port cache_object://127.0.0.1:$port/counters` where `$port` is either 3128 or 8080 (depends on your squid configuration). Probably you should add some rule to disable logging of this url, maybe by adding this to another acl and disabling logging for it. Like:
```
acl exclude dst 127.0.0.1
access_log none exclude
```
or even better change `dst 127.0.0.1` to something like [url_regex](http://wiki.squid-cache.org/SquidFaq/SquidAcl#ACL_elements)

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, please post here.
