### ISSUE TITLE
Swap graph

### ISSUE THREAD

**Issue by tycho** [firehol/netdata#549]
I notice a bit of inconsistency with the overview graphs at the top. Each of them measures units of that resource being utilized, _except_ for the swap graph. It represents the percentage of that resource that is "free". I find this misleading. Could this graph be changed to be consistent with the rest of the graphs, and instead represent the percentage of swap _in use_?

**Comment by ktsaou** [comment]
I have intentionally present free swap and free memory as percentages.

Let's see why: **You have 1GB swap free**. Is it good or bad? You cannot tell. But if I tell you that you have 50% swap free you immediately know this is bad. Similarly for 99% swap free, you know this is good.

Of course I am open to other alternatives, but keep in mind that at the top we need something that can ring a bell immediately. A few charts below you can find out the exact swap memory you have.

Ideally, we could have presented as percentages disk and network too. However, these do not have an upper limit. I cannot calculate somehow the maximum disk or network speed, not to mention that the performance of disk and network cards is often affected by other factors too.

**Comment by tycho** [comment]
Why do they indicate *free* instead of *used* memory/swap though? Every time I see one of those high-level overview graphs with a nearly full value, I wonder "oh crap, is something wrong" and then realize "oh, it's *free* memory, nevermind".

**Comment by tycho** [comment]
I have zero problem with them being represented as percentages, that wasn't the problem I had with them. It's that they're currently representing how much of a resource is *free* rather than *used*.

**Comment by simonnagl** [comment]
Two things. 

First if we change the direction, which is what @tycho whats we need to change it for swap and RAM.

Second why not display the value in MB. We can set `data-easypiechart-max-value` to the maximum value so the circle will represent percentage and the label a value.

**Comment by jurgenhaas** [comment]
I would also +1 for showing the percentage used rather than percentage free. That is more in line with the other charts that also show utilization instead of availability.

**Comment by ktsaou** [comment]
ok, did that.

**Comment by ktsaou** [comment]
now showing the used instead free memory and swap memory
