### ISSUE TITLE
Working examples

### ISSUE THREAD

**Issue by ishmaelen** [firehol/netdata#55]
Hello,

Do you have working examples for a netdata install with dashboards from other machines?
I am considering using netdata to show dasboards on TV for multiple machines..

**Comment by ktsaou** [comment]
A very simple demo of a custom dashboard:

https://netdata.firehol.org/demo.html

You can specify per chart the server using `data-host="http://server:19999/"`.

The options you can give per chart are (mostly) documented at https://github.com/firehol/netdata/wiki/Custom-Dashboards

You can also check the source of https://netdata.firehol.org/index.html for the most complete working example. It is a bit complicated, though.

If you put it on a TV, the biggest issue you may face is that if a chart fails (it is down), the chart will stay failed until you refresh the page. Also, if one server is slow (network latency maybe) it will slow down the refreshes of all charts. If you need fixes for these, open issues and I'll try to fix it `dashboard.js` to work around them.

**Comment by ishmaelen** [comment]
Hello,

Thanks for your swift reply and for a promising product!

I'll try it out (data-host="remove-server:19999") and see what sort of issues I stumble into.

I guess I can auto-refresh with a browser plugin every N minutes or so as well to avoid failed charts but the issue of refreshing all charts even though one server is slow sounds like a generally good idea to fix. After all the point of having netdata is to see such problems :)

**Comment by ishmaelen** [comment]
Server1: Running netdata Web .. 
Server2: data-host="http://server1:19999/"
Server3: data-host="http://server1:19999/"

How would I then show a dashboard with e.g. system.ipv4 for each 3 servers so that I can see the names etc. in dashbaord?

**Comment by ktsaou** [comment]
> How would I then show a dashboard with e.g. system.ipv4 for each 3 servers so that I can see the names etc. in dashbaord?

It is HTML. You can write in it anything you like (above, below or at the sides of each chart). You can also overwrite the titles of the charts.

For example:

```html

<!DOCTYPE html>
<html lang="en">
<head>
	<title>NetData Dashboard</title>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
	<meta name="author" content="costa@tsaousis.gr">

	<script type="text/javascript" src="dashboard.js"></script>
</head>
<body>

<div style="width: 100%; text-align: center;">
	My first chart. It comes from netdata server 1
	<br/>
	<div data-netdata="system.ipv4"
			data-chart-library="dygraph"
			data-width="100%"
			data-height="120px"
			data-after="-600"
			data-points="600"
			data-title="system.ipv4 from netdata server 1"
			></div>
	<br/>
	My second chart. It comes from netdata server 2
	<br/>
	<div data-netdata="system.ipv4"
			data-chart-library="dygraph"
			data-width="100%"
			data-height="120px"
			data-after="-600"
			data-points="600"
			data-title="system.ipv4 from netdata server 2"
			data-host="http://server2:19999/"
			></div>
	<br/>
	My third chart. It comes from netdata server 3
	<br/>
	<div data-netdata="system.ipv4"
			data-chart-library="dygraph"
			data-width="100%"
			data-height="120px"
			data-after="-600"
			data-points="600"
			data-title="system.ipv4 from netdata server 3"
			data-host="http://server3:19999/"
			></div>
	<br/>
</div>
</body>
</html>
```

**Comment by ishmaelen** [comment]
Thanks for your kind help!
