### ISSUE TITLE
Ugly side slider in dashboard UI

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#550]
It is not something important but I found that on small screens we can have two different sliders. One is displayed when chart is too small to contain whole legend and the different one is displayed when side panel cannot show everything on screen.
I propose to change the second one to be similar to the first one or disable it completely.
You can see it on this screenshot (first one is near `handlers/s` and second is on the right):
![screenshot_20160613_231735](https://cloud.githubusercontent.com/assets/3531758/16023604/cd65ff5a-31bd-11e6-857f-c535e2b5bc08.png)

**Comment by ktsaou** [comment]
Yeap. You are right.
Also this one:

![image](https://cloud.githubusercontent.com/assets/2662304/16027465/be6059da-31de-11e6-95f8-2dff2492ac16.png)

**Comment by ktsaou** [comment]
I need to find some time to do it.

**Comment by paulfantom** [comment]
While looking at those screens I see some other inconsistency. Do you see how `MySQL: local` and `phpfpm_local` are displayed? One has colon `:`, the other has underscore `_` and both those separators are for the same reason. I was trying to find it in plugins code but I failed, is it set somewhere on the client side?

**Comment by ktsaou** [comment]
Yes, this is done in `index.html`. Ideally we should do it for all modules supporting multiple data collection sources.

**Comment by ktsaou** [comment]
this has been fixed, long time ago....
