### ISSUE TITLE
How to add the host

### ISSUE THREAD

**Issue by xxlaila** [firehol/netdata#553]
Now installed on a server installed netdata, how other server added, or a web interface for each server, and have integrated?

**Comment by ktsaou** [comment]
Hi, you need one netdata per server.
The `my-netdata` menu on the dashboard links them all.

**Comment by xxlaila** [comment]
I see, there is a link, but didn't see where to add

**Comment by xxlaila** [comment]
I saw on the web interface of the my - netdata menu, but don't know where is the other servers, is inside the shell using the command line to add??

**Comment by xxlaila** [comment]
Thank you so much!!I have added the server, but now I have a question?Install the all servers must be connected?And I saw a browser is open registration ID.How to ensure that safe?

**Comment by ktsaou** [comment]
Sorry for the late reply. I was in a trip.

Please have a look at https://github.com/firehol/netdata/wiki/mynetdata-menu-item to understand how it works. The registry works with random GUIDs generated by each netdata server and the registry.

The only personal information shared to the registry is the URLs of your netdata servers. If these URLs are publicly accessible (they should not), then just enable one of your netdata servers to act as the registry too. This way, all your information will be stored at your netdata servers. Nothing will be shared outside your network.
