### ISSUE TITLE
Dynamically change the DIMENSION values

### ISSUE THREAD

**Issue by sam0302** [firehol/netdata#554]
Hello,

I have a scenario where I am reading data from shared memory and need to dynamically populate the DIMENSION field. For example, different clients have different requests which I am capturing based on different shared memory. And the DIMENSION field should change as per the requests as below

vector<std::string> files;
for(unsigned i = 0; i < size; ++i)
		cout << "DIMENSION" <<  " " << files[i] << " " <<  files[i]  << " " << "absolute 1 1" << endl;

When the contents of the files changes, I do not see that being reflected on the netdata graph. 
And the above statement is inside While(1) loop which should referesh each time data changes.

**Comment by ktsaou** [comment]
Hi.

Currently you can only add dimensions to a chart. You cannot remove existing ones.

You can add dimensions any time you like, but you have to re-send the CHART command and then the DIMENSION you want to add. There is no need to send all the DIMENSIONS again (although it will harm if you do).

What I normally do, is to have in my plugins a list of dimensions and for each dimension I have a boolean that states if it has been sent to netdata or not. Then before sending the collected data, I check if there is any dimension that is not sent, in which case I re-print the CHART and the DIMENSION lines, and then I send the data.

Keep in mind that if you add hundreds of dimensions to a single chart, this chart will become slow. This happens for 2 reasons:

1. Internally, netdata generates JSON data for the chart refreshes in one pass for all dimensions. So as you add dimensions you actually multiply the amount of work netdata has to do for updating the chart on the dashboard. This is minor though. I will just increase latency by a few milliseconds.

2. The dashboard (the javascript code) will have to render hundreds of lines for each chart refresh. This is the biggest problem. Javascript code is not made this kind of work. There is a point above which the javascript code will simple not be able to cope with it.

**Comment by ktsaou** [comment]
I forgot.
I think you can resend a DIMENSION with the same ID but a different NAME. In this case, the dimension will change name on the dashboard, but the old chart data will not be erased. The new values will appear after the old.

**Comment by ktsaou** [comment]
And finally, If you explain a bit more your specific need (i.e. why you need this?) and in case your need seems generic enough to be supported by netdata, I may extend the plugin API to support it.

**Comment by sam0302** [comment]
Thanks for the reply.
Well, I have developed a netdata plugin that will monitor number of clients connected to a server and each client making some random requests to server which i need to monitor in netdata chart. So, I would like DIMENSION to list the clients connected and dynamically this should change to show what all clients connected at what time and got disconnected at what time, also how many request they make to the server.

So, currently as you said, netdata will not erase the old data chart, so I end up seeing list of clients that gets connected with older list also :-(

**Comment by ktsaou** [comment]
So, what would be useful for you is to be able to obsolete dimensions?

**Comment by ktsaou** [comment]
Cleaning up. If you need help, just post.
