### ISSUE TITLE
Unsupported v1 API command: badge.svg

### ISSUE THREAD

**Issue by kianxineki** [firehol/netdata#556]
Hi, I'm trying to use to paint badge.svg information but arch linux me not working properly.

[root@archdroid ~]# pacman -Ss netdata
community/netdata 1.2.0-1 [installed]

Linux archdroid 3.14.65-8-ARCH #1 SMP PREEMPT Tue Jun 7 19:18:18 MDT 2016 aarch64 GNU/Linux

url: http://status.rookie.ninja/api/v1/badge.svg?chart=netdata.requests

**Comment by ktsaou** [comment]
This feature is not released yet. I will come out with v1.3.0.
So, to use it now, you will have to install netdata from source.

**Comment by ktsaou** [comment]
I am closing this. We will be releasing 1.3.0 in a few days, so you will get it with that if you haven't already installed netdata from source.
