### ISSUE TITLE
Problem with phpfpm.chart.sh and php 5.3.x

### ISSUE THREAD

**Issue by n0guest** [firehol/netdata#558]
Hi. I've added phpfpm_url to phpfpm.conf, but received such message in error.log:

> cannot find status on URL

After short digging i've found this check in phpfpm_get function:

        if [[ "${phpfpm_response[0]}" != "pool:" \
                || "${phpfpm_response[2]}" != "process" \
                || "${phpfpm_response[5]}" != "start" \
                || "${phpfpm_response[12]}" != "accepted" \
                || "${phpfpm_response[15]}" != "listen" \
                || "${phpfpm_response[16]}" != "queue:" \
                || "${phpfpm_response[26]}" != "idle" \
                || "${phpfpm_response[29]}" != "active" \
                || "${phpfpm_response[32]}" != "total" \
                || "${phpfpm_response[43]}" != "slow" \
        ]]
                then
                echo >&2 "phpfpm: invalid response from phpfpm status server: ${phpfpm_response[*]}" 
                return 1
        fi

Later i've found, that fpm-status from php 5.3 doesn't have a field with "slow requests":

		pool:                 www
		process manager:      dynamic
		start time:           14/Jun/2016:23:35:42 +0300
		start since:          3
		accepted conn:        4
		listen queue:         0
		max listen queue:     0
		listen queue len:     0
		idle processes:       1
		active processes:     1
		total processes:      2
		max active processes: 1
		max children reached: 0

 it's a bug or you've intentionally give up of support of "legacy" php versions?

**Comment by ktsaou** [comment]
I don't know.
This plugin has been developed by @safeie 
@safeie could you please help?

**Comment by paulfantom** [comment]
@n0guest could you check if version of `phpfpm.chart.sh` from my netdata fork is working?
I have modified it to remove "slow queries" if not present.

Also, soon I will write it in python:)

**Comment by n0guest** [comment]
I've used this revision:

https://raw.githubusercontent.com/paulfantom/netdata/24382e47cac83df14373a31bd1342187e7d55469/charts.d/phpfpm.chart.sh

And looks like it works fine. At least it didn't write any errors in log as it was before. And graphs are showing some data. I hope those changes will be merged to upstream?

**Comment by ktsaou** [comment]
make a PR please and I'll merge it.

**Comment by paulfantom** [comment]
Thanks for testing it.

I have made PR #567.

Close?

**Comment by ktsaou** [comment]
merged it.
