### ISSUE TITLE
mysql: unknown column 'value'

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#559]
1. netdata error.log
**ERROR 1054 (42S22) at line 1: Unknown column 'value' in 'where clause'**
charts.d: mysql: cannot get global status for 'RED'. Please set mysql_opts[RED]='options' to whatever needed to get connected to the mysql server, in /etc/netdata/mysql.conf
charts.d: mysql: no mysql servers found. Please set mysql_opts[name]='options' to whatever needed to get connected to the mysql server, in /etc/netdata/mysql.conf
charts.d: chart 'mysql' check() function reports failure.

2. mysql.conf
mysql_cmds[RED]="/opt/mysql-5.7.10/bin/mysql"
mysql_opts[RED]="-h localhost -uroot -pPASSWORD"

**Comment by ktsaou** [comment]
could you please run `mysql -e 'show global status;'` and post the first few lines?

**Comment by sohwaje** [comment]
[root@localhost.localdomain:/usr/libexec/netdata/charts.d]mysql -uroot -pPASSWORD -e 'show global status;'
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------------------------------------------+--------------------------------------------------+
| Variable_name                                 | Value                                            |
+-----------------------------------------------+--------------------------------------------------+
| Aborted_clients                               | 14198                                            |
| Aborted_connects                              | 235875                                           |
| Binlog_cache_disk_use                         | 0                                                |
| Binlog_cache_use                              | 0                                                |
| Binlog_stmt_cache_disk_use                    | 0                                                |
| Binlog_stmt_cache_use                         | 0                                                |
| Bytes_received                                | 2927855095                                       |
| Bytes_sent                                    | 16990044658                                      |
| Com_admin_commands                            | 455585                                           |

**Comment by sohwaje** [comment]
[root@localhost.localdomain:/usr/libexec/netdata/charts.d]mysql -uroot -pPASSWORD -e "show global status where 'Value' REGEXP '^[0-9]';"
mysql: [Warning] Using a password on the command line interface can be insecure.

**Comment by paulfantom** [comment]
So it doesn't show anything? Not even the error?

**Comment by paulfantom** [comment]
And: `mysql -e "show global status where Value REGEXP '^[0-9]';"` ?

**Comment by sohwaje** [comment]
Yes, That's the lot.

**Comment by paulfantom** [comment]
I made a mistake in the previous one. This one doesn't have `'` around Value.

**Comment by sohwaje** [comment]
[root@localhost.localdomain:/usr/libexec/netdata/charts.d]mysql -uroot -pPASSWORD -e "show global status where Value REGEXP '^[0-9]';"  
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 1: Unknown column 'Value' in 'where clause'

**Comment by paulfantom** [comment]
Found it. All tests were performed on MariaDB which has columns `Variable_name` and `Value`. MySQL on the other hand presents those columns with the same names when displaying, but in INFORMATION_SCHEMA it stores them as `Variable_name` and `Variable_value`.

For now if you change line 20 in `charts.d/mysql.chart.sh` it will work.
You need to change:
```sh
arr=($("${@}" -e "SHOW GLOBAL STATUS WHERE value REGEXP '^[0-9]';" | egrep "^(Bytes|Slow_|Que|Handl|Table|Selec|Sort_|Creat|Conne|Abort|Binlo|Threa|Innod|Qcach|Key_|Open)" ))
```
to:
```sh
arr=($("${@}" -e "SHOW GLOBAL STATUS WHERE variable_value REGEXP '^[0-9]';" | egrep "^(Bytes|Slow_|Que|Handl|Table|Selec|Sort_|Creat|Conne|Abort|Binlo|Threa|Innod|Qcach|Key_|Open)" ))
```
Just `value` to `variable_value`

**Comment by sohwaje** [comment]
I just succeeded.Thank you very much.

**Comment by ktsaou** [comment]
@paulfantom I guess we should remove the regex to allow it work everywhere. Can you make a PR or you want me to do it?

**Comment by sohwaje** [comment]
<img width="1068" alt="2016-06-16 12 09 34" src="https://cloud.githubusercontent.com/assets/19942049/16085440/0934e6c8-3357-11e6-9715-f0eee066deb1.png">

**Comment by sohwaje** [comment]
<img width="1455" alt="2016-06-16 12 08 43" src="https://cloud.githubusercontent.com/assets/19942049/16085456/1524275a-3357-11e6-82b1-d723b1a7db47.png">

**Comment by paulfantom** [comment]
I am working on a workaround. @ktsaou if you have some fast and easy way to make it work, go on. But remember that `arr` needs to have only rows with numeric values.
