### ISSUE TITLE
Please consider changing hashbang in mysql.chart.py to "#!/usr/bin/env python3"

### ISSUE THREAD

**Issue by andrzejc** [firehol/netdata#562]
Currently the MySQL python plugin has hardcoded path to python3 executable to /usr/bin/python3. There's lots of systems where python3 is installed in alternative location (e.g. /usr/local/bin/python3, /opt/bin/python3 etc.) and the plugin won't work out of the box (with a misleading info in netdata error log that file mysql.chart.py is not found). Changing the hashbang to use env to locate python3 fixes the issue and makes the plugin runnable out-of-the-box for much larger user base.

**Comment by paulfantom** [comment]
Currently python3 has also `-u` switch which cannot be used with `env`.
If you know how to force python to use unbuffered output with `env` I would be very happy to change it.

**Comment by andrzejc** [comment]
First thing that comes to my mind is to have the master process set env var PYTHONUNBUFFERED=1 before spawning plugin scripts

**Comment by paulfantom** [comment]
Ok, thank you. I will change it later:)

**Comment by glensc** [comment]
some SO links doing it programmatically:
- http://stackoverflow.com/questions/881696/unbuffered-stdout-in-python-as-in-python-u-from-within-the-program
- http://stackoverflow.com/questions/107705/disable-output-buffering/1736047#1736047

**Comment by paulfantom** [comment]
Do you know if I set `os.environ['PYTHONUNBUFFERED'] = '1'` in `python.d.plugin`, plugins loaded by this program will have unbuffered I/O or do I need to reopen `stdout` and `stderr` like in links from stackoverflow? Because I think this would be the easiest one.

**Comment by paulfantom** [comment]
That was probably a stupid question. I will use this solution:

**Comment by andrzejc** [comment]
I’d have to check the code how the plugins are started - I presume that if you’re using hashbangs in their code, they are executed as separate subprocesses with new python started from scratch as opposed to forking the  existing one, so I guess this would work then, but I can’t know for sure without checking this, which I will be able to later in the evening.

-Andrzej Ciarkowski

**Comment by paulfantom** [comment]
shebang in `mysql.chart.py` is unnecessary and will be removed. They are imported as python modules.

**Comment by paulfantom** [comment]
I have made changes in my [forked version under branch 'hashbang'](https://github.com/paulfantom/netdata/tree/hashbang). 

If someone is willing to test it I would be very grateful as I don't have time today and tomorrow.

**Comment by ktsaou** [comment]
> PYTHONUNBUFFERED=1

I can set this in the netdata core if that will help.

**Comment by glensc** [comment]
well. imho using env variable is unreliable, someone might do debugging and does not know that need to set such variable, that's why i'd do the unbuffering in the code.

**Comment by ktsaou** [comment]
You are right. But python disables buffering on the console. So, I guess it won't harm to add it to netdata. It will eliminate issues for people not aware (and even experienced python devs are not aware that python prints unbuffered on console and buffered on pipe #447 #206).

**Comment by ktsaou** [comment]
merged the fix.
