### ISSUE TITLE
Netdata SNMP Configuration

### ISSUE THREAD

**Issue by LevanM** [firehol/netdata#566]
Hello

I have searched everywhere but I can't find snmp configuration tutorial or example config file.
I also was looking for it on github wiki but without success.
Can someone help?
I want to add new Devices (Server, Cisco Routers, etc) and monitor them using SNMP

**Comment by ktsaou** [comment]
Check this:
https://github.com/firehol/netdata/wiki/snmp.node.js

**Comment by LevanM** [comment]
**ktsaou**

Thank you. 
Sorry, I didn't notice

**Comment by ktsaou** [comment]
no problem.

**Comment by LevanM** [comment]
I have one more question :)
I want to monitor Windows Server using SNMP
Is there any example how can I do it?

In this example, there is aonly written about monitoring switch ports.
https://github.com/firehol/netdata/wiki/snmp.node.js

**Comment by ktsaou** [comment]
I have never done this for monitoring windows, but I guess the procedure is the same:

1. enable SNMP in windows
2. verify it works from your linux box using `snmpwalk`
3. find the OIDs you need to monitor
4. configure the netdata plugin to collect these OIDs and group them to charts
5. restart netdata and see it collecting the data you configured

**Comment by ktsaou** [comment]
If you manage to do it, I would appreciate a step-by-step guide and an example netdata config that can be added to the wiki, so that others can benefit too.

**Comment by LevanM** [comment]
Okey,

I am trying to do it right now.
I soon as I success, I will let you know.
