### ISSUE TITLE
tomcat or xmlstarlet?

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#569]
1. error.log
charts.d: tomcat: configuration file '/etc/netdata/tomcat.conf' not found. Using defaults.
which: no xmlstarlet in (/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/bin:/root/bin)
charts.d: ERROR: Command 'xmlstarlet' is not found in the system path.
charts.d: chart 'tomcat' check() function reports failure.

2. tomcat.chart.sh

> #!/bin/bash
> 
> # Description: Tomcat netdata charts.d plugin
> # Author: Jorge Romero
> 
> # the URL to download tomcat status info
> # usually http://localhost:8080/manager/status?XML=true
> tomcat_url="http://127.0.0.1:8080/manager/status?XML=true"
> tomcat_curl_opts=""
> 
> # set tomcat username/password here
> tomcatUser="admin"
> tomcatPassword="1234!"
> 
> # _update_every is a special variable - it holds the number of seconds
> # between the calls of the _update() function
> tomcat_update_every=
> 
> tomcat_priority=60000
> 
> # convert tomcat floating point values
> # to integer using this multiplier
> # this only affects precision - the values
> # will be in the proper units
> tomcat_decimal_detail=1000000
> 
> # used by volume chart to convert bytes to KB
> tomcat_decimal_KB_detail=1000
> 
> tomcat_check() {
> 
>         require_cmd xmlstarlet || return 1
> 
> 
>         # check if url, username, passwords are set
>         if [ -z "${tomcat_url}" ]; then
>                 echo >&2 "tomcat url is unset or set to the empty string"
>                 return 1
>         fi
>         if [ -z "${tomcatUser}" ]; then
>                 echo >&2 "tomcat user is unset or set to the empty string"
>                 return 1
>         fi
>         if [ -z "${tomcatPassword}" ]; then
>                 echo >&2 "tomcat password is unset or set to the empty string"
>                 return 1
>         fi
> 
>         # check if we can get to tomcat's status page
>         tomcat_get
>         if [ $? -ne 0 ]
>                 then
>                 echo >&2 "tomcat: couldn't get to status page on URL '${tomcat_url}'."\
>                 "Please make sure tomcat url, username and password are correct."
>                 return 1
>         fi
> 
>         # this should return:
>         #  - 0 to enable the chart
>         #  - 1 to disable the chart
> 
>         return 0
> }
> 
> tomcat_get() {
>         # collect tomcat values
>         tomcat_port="$(IFS=/ read -ra a <<< "$tomcat_url"; hostport=${a[2]}; echo "${hostport#*:}")"
>         mapfile -t lines < <(curl -u "$tomcatUser":"$tomcatPassword" -Ss ${tomcat_curl_opts} "$tomcat_url" |\
>                 xmlstarlet sel \
>                         -t -m "/status/jvm/memory" -v @free \
>                         -n -m "/status/connector[@name='\"http-bio-$tomcat_port\"']/threadInfo" -v @currentThreadCount \
>                         -n -v @currentThreadsBusy \
>                         -n -m "/status/connector[@name='\"http-bio-$tomcat_port\"']/requestInfo" -v @requestCount \
>                         -n -v @bytesSent -n -)
> 
>         tomcat_jvm_freememory="${lines[0]}"
>         tomcat_threads="${lines[1]}"
>         tomcat_threads_busy="${lines[2]}"
>         tomcat_accesses="${lines[3]}"
>         tomcat_volume="${lines[4]}"
> 
>         return 0
> }
> 
> # _create is called once, to create the charts
> tomcat_create() {
>         cat <<EOF
> CHART tomcat.accesses '' "tomcat requests" "requests/s" statistics tomcat.accesses area $((tomcat_priority + 8)) $tomcat_update_every
> DIMENSION accesses '' incremental
> CHART tomcat.volume '' "tomcat volume" "KB/s" volume tomcat.volume area $((tomcat_priority + 5)) $tomcat_update_every
> DIMENSION volume '' incremental divisor ${tomcat_decimal_KB_detail}
> CHART tomcat.threads '' "tomcat threads" "current threads" statistics tomcat.threads line $((tomcat_priority + 6)) $tomcat_update_every
> DIMENSION current '' absolute 1
> DIMENSION busy '' absolute 1
> CHART tomcat.jvm '' "JVM Free Memory" "MB" statistics tomcat.jvm area $((tomcat_priority + 8)) $tomcat_update_every
> DIMENSION jvm '' absolute 1 ${tomcat_decimal_detail}
> EOF
>         return 0
> }
> 
> # _update is called continiously, to collect the values
> tomcat_update() {
>         local reqs net
>         # the first argument to this function is the microseconds since last update
>         # pass this parameter to the BEGIN statement (see bellow).
> 
>         # do all the work to collect / calculate the values
>         # for each dimension
>         # remember: KEEP IT SIMPLE AND SHORT
> 
>         tomcat_get || return 1
> 
>         # write the result of the work.
>         cat <<VALUESEOF
> BEGIN tomcat.accesses $1
> SET accesses = $((tomcat_accesses))
> END
> BEGIN tomcat.volume $1
> SET volume = $((tomcat_volume))
> END
> BEGIN tomcat.threads $1
> SET current = $((tomcat_threads))
> SET busy = $((tomcat_threads_busy))
> END
> BEGIN tomcat.jvm $1
> SET jvm = $((tomcat_jvm_freememory))
> END
> VALUESEOF
> 
>         return 0
> }

**Comment by sohwaje** [comment]
I solved it.
https://github.com/firehol/netdata/pull/277

![default](https://cloud.githubusercontent.com/assets/19942049/16145554/45507876-34b4-11e6-9461-17680d5ec38e.JPG)

**Comment by sohwaje** [comment]
But I couldn't show data. :(

![ss](https://cloud.githubusercontent.com/assets/19942049/16145817/a9d16c64-34b5-11e6-8588-9b65b763fcc3.JPG)

**Comment by ktsaou** [comment]
@jgeromero can you help?

**Comment by sohwaje** [comment]
Yes.

**Comment by sohwaje** [comment]
/var/log/netdata/error.log
/usr/libexec/netdata/plugins.d/../charts.d/tomcat.chart.sh: line 67: xmlstarlet: command not found
/usr/libexec/netdata/plugins.d/../charts.d/tomcat.chart.sh: line 67: xmlstarlet: command not found
/usr/libexec/netdata/plugins.d/../charts.d/tomcat.chart.sh: line 67: xmlstarlet: command not found
/usr/libexec/netdata/plugins.d/../charts.d/tomcat.chart.sh: line 67: xmlstarlet: command not found
.....

**Comment by ktsaou** [comment]
have you installed `xmlstarlet`?

**Comment by sohwaje** [comment]
yes.
[root@gaudium:/var/log/netdata]rpm -qa | grep xmlstarlet
xmlstarlet-1.3.1-1.3.x86_64

**Comment by sohwaje** [comment]
tomcat.chart.sh, I configured it like this.
tomcat_url="http://10.0.2.192:8080/manager/status?XML=true"
tomcatUser="test"
tomcatPassword="1234!"
tomcat_check() {

        require_cmd xmlstarlet || return 1
#require_cmd xmllint || return 1
        # check if url, username, passwords are set
        if [ -z "${tomcat_url}" ]; then
                echo >&2 "tomcat url is unset or set to the empty string"
                return 1
        fi
        if [ -z "${tomcatUser}" ]; then
                echo >&2 "tomcat user is unset or set to the empty string"
                return 1
        fi
        if [ -z "${tomcatPassword}" ]; then
                echo >&2 "tomcat password is unset or set to the empty string"
                return 1
        fi

**Comment by ktsaou** [comment]
You should not touch this script. Your configuration should be placed in `/etc/netdata/tomcat.conf`.

Anyway, do you still get `xmlstarlet: command not found` in error.log?

**Comment by sohwaje** [comment]
1. Not touch? OK. I restored that file. 
tomcat_url=""`
tomcat_curl_opts=""

# set tomcat username/password here
tomcatUser=""
tomcatPassword=""

2. But I do not find tomcat.conf. Should I be made? How?

3. I installed it. xmlstarlet
[root@gaudium:/usr/libexec/netdata/charts.d]xmlstarlet
XMLStarlet Toolkit: Command line utilities for XML
Usage: xmlstarlet [<options>] <command> [<cmd-options>]
where <command> is one of:
  ed    (or edit)      - Edit/Update XML document(s)
  sel   (or select)    - Select data or query XML document(s) (XPATH, etc)
  tr    (or transform) - Transform XML document(s) using XSLT
  val   (or validate)  - Validate XML document(s) (well-formed/DTD/XSD/RelaxNG)
  fo    (or format)    - Format XML document(s)
  el    (or elements)  - Display element structure of XML document
  c14n  (or canonic)   - XML canonicalization
  ls    (or list)      - List directory as XML
  esc   (or escape)    - Escape special XML characters
  unesc (or unescape)  - Unescape special XML characters
  pyx   (or xmln)      - Convert XML into PYX format (based on ESIS - ISO 8879)
  p2x   (or depyx)     - Convert PYX into XML
<options> are:
  --version            - show version
  --help               - show help
Wherever file name mentioned in command help it is assumed
that URL can be used instead as well.

Type: xmlstarlet <command> --help <ENTER> for command help

XMLStarlet is a command line toolkit to query/edit/check/transform
XML documents (for more information see http://xmlstar.sourceforge.net/)
[root@gaudium:/usr/libexec/netdata/charts.d]

**Comment by paulfantom** [comment]
You should create `tomcat.conf` in the same folder where `netdata.conf` is located.
It should have following content:
```sh
tomcat_url="http://10.0.2.192:8080/manager/status?XML=true"
tomcatUser="test"
tomcatPassword="1234!"
```

**Comment by paulfantom** [comment]
@ktsaou why `tomcat.chart.sh` has non-standard `tomcatPassword` and `tomcatUser`? Shouldn't it be following the convention and be named: `tomcat_password` and `tomcat_user`?
If you agree I can make PR.

**Comment by sohwaje** [comment]
Thank you. I succeed. 
<img width="1239" alt="2016-06-17 11 38 51" src="https://cloud.githubusercontent.com/assets/19942049/16154190/b8c5d528-34e4-11e6-928d-5e725e8a05e6.png">

**Comment by ktsaou** [comment]
> @ktsaou why tomcat.chart.sh has non-standard tomcatPassword and tomcatUser? Shouldn't it be following the convention and be named: tomcat_password and tomcat_user?
> If you agree I can make PR.

please do... but also support the existing format to prevent loosing charts....

**Comment by paulfantom** [comment]
Already done in #576. Close?

**Comment by ktsaou** [comment]
thanks!
