### ISSUE TITLE
Listen to range of IPs, ``Failed to convert IP '{{IP}}' to a valid IPv4 address``

### ISSUE THREAD

**Issue by 85pando** [firehol/netdata#570]
If I want to let netdata listen to a range of IPs, how would the syntax for this be. I tried the following:

```
bind socket to IP = 123.456.789.0/24
bind socket to IP = 123.456.789.*
```

For both there is the error ```ERROR: netdata: Failed to convert IP '{{IP}}' to a valid IPv4 address.```

Now the question is, am I doing something wrong here or is this not possible yet?

**Comment by ktsaou** [comment]
You need to allow just a range of IPs to access it or you need to actually bind itself on multiple IPs/network interfaces of the host?

**Comment by 85pando** [comment]
Yeah sure, did not have any coffee, yet.

What I want to do:

* netdata running on server
* access it from any point in our university/corporate network (lets just say we have a small network like shown above)
* No access from outside of that network.

**Comment by ktsaou** [comment]
You have 2 options:

1. bind netdata to 0.0.0.0:19999 and use iptables to restrict access to port 19999, or
2. bind netdata to 127.0.0.1:19999 and proxy it with nginx, apache, lighttpd. Apply all access control (including username/password if you need it) to the web server. You can find guides on how to do this at the wiki.

**Comment by 85pando** [comment]
Ok, I just thought it would be possible without seperate Webserver.
