### ISSUE TITLE
apache: missing 'Total Accesses', cannot find stub_status on URL 'http://127.0.0.1:80/server-status?auto'.

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#577]
1.Error log
apache: missing 'Total Accesses' from apache server: BusyWorkers  3 IdleWorkers  30 Scoreboard  ..___C______._.____._..____.__K..W_._._____.__..................................................................................................................
................................................................................................
apache: cannot find stub_status on URL 'http://127.0.0.1:80/server-status?auto'. Please set apache_url='http://apache.server:80/server-status?auto' in /etc/netdata/apache.conf
charts.d: chart 'apache' check() function reports failure.
charts.d: No charts to collect data from.

2./etc/netdata/apache.conf
apache_url="http://127.0.0.1:80/server-status?auto"
apache_curl_opts=
apache_update_every=

**Comment by ktsaou** [comment]
Run this and post the result:

```sh
curl "http://127.0.0.1:80/server-status?auto"
```

**Comment by sohwaje** [comment]
BusyWorkers: 1
IdleWorkers: 9
Scoreboard: ._......_W_._._.__....._......_.................................................................................................................................................................................................................................

**Comment by sohwaje** [comment]
I solved it. 
My Web Server is Apache 2.2.x. 

1.
# vi httpd-info.conf
ExtendedStatus On   <------unmakred

2. ./apachectl restart

**Comment by ktsaou** [comment]
ok
