### ISSUE TITLE
missing apps and custom dashboard options

### ISSUE THREAD

**Issue by max12m3** [firehol/netdata#58]
Hello,
thanks for creating this nice monitor tool, i really like it :D
but i have an issue on my aarch64 debian 8 maschine
the hole /#apps tree is missing ??
i only see:

    System Overview
    Memory
    CPUs
    Disks
    IPv4 Networking
    Network Interfaces
    Sensors
    Netdata Monitoring
    Example Charts

maybe i overlooked something?
i also have a question about the defaults for the dashboard options
where can i set 'When to refresh the charts?' to always
and 'Which dimensions to show?' to all
Thank You !
Max from Germany

**Comment by ktsaou** [comment]
## apps

apps are monitored with `apps.plugin`. My guess is that yours is not running.

By default `apps.plugin` should be in `/usr/libexec/netdata/plugins.d` and should be setuid to root.
Try running it by hand. This is mine for example:

```sh
 # /usr/libexec/netdata/plugins.d/apps.plugin
16-03-26 19:10:26: INFO: apps.plugin: NETDATA_HOST_PREFIX is not passed from netdata
16-03-26 19:10:26: INFO: apps.plugin: starting...
CHART apps.cpu '' 'Apps CPU Time (400% = 4 cores)' 'cpu time %' cpu apps.cpu stacked 20001 1
DIMENSION other '' incremental 100 100 noreset
DIMENSION ksmd '' incremental 100 100 noreset
DIMENSION system '' incremental 100 100 noreset
DIMENSION netdata '' incremental 100 100 noreset
DIMENSION kernel '' incremental 100 100 noreset
DIMENSION cron '' incremental 100 100 noreset
DIMENSION openvpn '' incremental 100 100 noreset
DIMENSION inetd '' incremental 100 100 noreset
DIMENSION ppp '' incremental 100 100 noreset
DIMENSION nms '' incremental 100 100 noreset
DIMENSION log '' incremental 100 100 noreset
DIMENSION vbox '' incremental 100 100 noreset
DIMENSION deluge '' incremental 100 100 noreset
DIMENSION ntp '' incremental 100 100 noreset
DIMENSION cups '' incremental 100 100 noreset
DIMENSION clam '' incremental 100 100 noreset
```

And these are its permissions:

```sh
# ls -l /usr/libexec/netdata/plugins.d/apps.plugin
-rwsr-xr-x 1 root root 181312 Mar 13 14:25 /usr/libexec/netdata/plugins.d/apps.plugin
```

You can configure the applications it monitors using `/etc/netdata/apps.conf`.

## chart options

When you build a custom dashboard you have to create a custom options menu yourself. You can control the various options of the dashboard using members of `NETDATA.options.current`.

You can find the options currently supported using this url: https://github.com/firehol/netdata/blob/master/web/dashboard.js#L196:L261

The options your are looking for are:

`NETDATA.options.current.eliminate_zero_dimensions = true;` Set this to false to always show all dimensions.

`NETDATA.options.current.stop_updates_when_focus_is_lost = true;` Set this to false to always refresh the charts, even if the window has lost focus.

`NETDATA.options.current.eliminate_zero_dimensions = true;` Set this to false to always show all dimensions.

You can set any of these options on your custom dashboard, by adding a `script` section, after you load `dashboard.js`, like this:

```html
<!-- you should already have this line in your custom dashboard -->
<script type="text/javascript" src="dashboard.js"></script>

<!-- this is what you need to add -->
<script type="text/javascript">
   NETDATA.options.current.stop_updates_when_focus_is_lost = false;
   NETDATA.options.current.eliminate_zero_dimensions = false;
</script>
```

**Comment by max12m3** [comment]
Thanks for the fast answer!

`cat /var/log/netdata/error.log  | grep apps.plugin`
INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 23003
INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/apps.plugin 1 ' on pid 23003.
 INFO: apps.plugin: Found NETDATA_HOST_PREFIX=''
INFO: apps.plugin: starting...
ERROR: apps.plugin: Cannot process /proc/1/io (errno 2, No such file or directory)
ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' is requesting a BEGIN on chart 'apps.cpu', which does not exist. Disabling it.
INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 23003 stopped.

-rwsr-xr-x 1 root root 75K Mär 26 18:46 /usr/libexec/netdata/plugins.d/apps.plugin
im runninng a 3.14.29 kernel
but still cant get the apps working any idea?
Thanks

**Comment by ktsaou** [comment]
strange.

Can you post the output of this:

```sh
# /usr/libexec/netdata/plugins.d/apps.plugin | grep apps.cpu
16-03-26 20:39:43: INFO: apps.plugin: NETDATA_HOST_PREFIX is not passed from netdata
16-03-26 20:39:43: INFO: apps.plugin: starting...
CHART apps.cpu '' 'Apps CPU Time (400% = 4 cores)' 'cpu time %' cpu apps.cpu stacked 20001 1
CHART apps.cpu_user '' 'Apps CPU User Time (400% = 4 cores)' 'cpu time %' cpu apps.cpu_user stacked 20020 1
CHART apps.cpu_system '' 'Apps CPU System Time (400% = 4 cores)' 'cpu time %' cpu apps.cpu_system stacked 20021 1
CHART netdata.apps_cpu '' 'Apps Plugin CPU' 'milliseconds/s' apps.plugin netdata.apps_cpu stacked 140000 1
BEGIN apps.cpu 0
BEGIN apps.cpu_user 0
BEGIN apps.cpu_system 0
BEGIN netdata.apps_cpu 0
BEGIN apps.cpu 968676
BEGIN apps.cpu_user 968676
BEGIN apps.cpu_system 968676
BEGIN netdata.apps_cpu 968676
^C
```

**Comment by ktsaou** [comment]
Also, I do have `/proc/1/io`:

```sh
# ls -l /proc/1/io
-r-------- 1 root root 0 Mar 26 20:40 /proc/1/io
```

Are you running it in container or docker?

**Comment by max12m3** [comment]
its located on my rootfs i dont have docker installed
`➜  /usr/libexec/netdata/plugins.d/apps.plugin | grep apps.cpu
16-03-26 19:55:12: INFO: apps.plugin: NETDATA_HOST_PREFIX is not passed from netdata
16-03-26 19:55:12: INFO: apps.plugin: starting...
16-03-26 19:55:12: ERROR: apps.plugin: Cannot process /proc/1/io (errno 2, No such file or directory)
BEGIN apps.cpu 0
BEGIN apps.cpu_user 0
BEGIN apps.cpu_system 0
BEGIN netdata.apps_cpu 0
BEGIN apps.cpu 999570
BEGIN apps.cpu_user 999570
BEGIN apps.cpu_system 999570
BEGIN netdata.apps_cpu 999570
BEGIN apps.cpu 999920
BEGIN apps.cpu_user 999920
BEGIN apps.cpu_system 999920
BEGIN netdata.apps_cpu 999920
`

**Comment by ktsaou** [comment]
ok, I traced it.

The reason is that it cannot read any of `/proc/X/io`. This results in no processes to monitor at all.

In my system all processes have this file, with contents like this:

```sh
# cat /proc/1/io
rchar: 423755727216
wchar: 66792076076
syscr: 2275576409
syscw: 218687919
read_bytes: 54433370112
write_bytes: 50069458944
cancelled_write_bytes: 110620672
```

Do you have such files?

**Comment by max12m3** [comment]
`ls -al /proc/*/io
zsh: no matches found: /proc/*/io`
no all are missing, do you know how to enable these files ?

**Comment by ktsaou** [comment]
Sorry! I don't know. I guess it has something to do with your kernel. A kernel build option possibly.

Anyway, I just pushed a change to apps.plugin to allow it work without these files. Keep in mind I/O information will be missing from apps charts if you don't have these files.

**Comment by max12m3** [comment]
Thanks for the great support :D 
now it works, except the IO charts

**Comment by hussain6001** [comment]
For /proc/*/io information we have to enable below kernel configurations,

CONFIG_TASKSTATS=y
CONFIG_TASK_DELAY_ACCT=y
CONFIG_TASK_XACCT=y
CONFIG_TASK_IO_ACCOUNTING=y

**Comment by ktsaou** [comment]
thanks! Good to know!
