### ISSUE TITLE
Apache2 reverse proxy doesn't work

### ISSUE THREAD

**Issue by maedox** [firehol/netdata#580]
Because the app assumes everything is served at /. So I have to create a separate hostname and virtual host just for Netdata. It would be easier if I could serve it on another path on the same hostname as everything else.

What I'd like to do:
```
ProxyPass        /nd http://localhost:19999/ retry=1
ProxyPassReverse /nd http://localhost:19999/
```

However I immediately get a 404 for /dashboard.js.

**Comment by ktsaou** [comment]
Hi,

netdata does not assume it runs on `/`. I have many installations that serve different netdata as folders to the same URL.

Check this wiki page: https://github.com/firehol/netdata/wiki/Running-behind-apache#netdata-via-apaches-mod_proxy

**Comment by maedox** [comment]
Nice. Turns out the problem was the missing / on the URL. Should have thought of that, but normally apps take care of that themselves.

Thanks for the pointer.

**Comment by ktsaou** [comment]
> but normally apps take care of that themselves

Unfortunately, this is a logical problem that cannot be handled by the app. The only app that can solve it is the proxy. This is why you need the `RewriteRule` at apache. Check the wiki.

**Comment by maedox** [comment]
Could be. I have seen it when I make apps with the Flask framework. If I request `https://somehost/app` it redirects to `https://somehost/app/`. There might be some mod_wsgi magic involved for all I know.
Using a RewriteRule is fine, though, so no worries.
