### ISSUE TITLE
synced y-range in charts

### ISSUE THREAD

**Issue by Carles-Figuerola** [firehol/netdata#593]
Some data makes sense in two visualization styles. If I have 12 cores, I do like to see which ones are spiking but also I would love to normalize all the Y axes so I can see which ones are being utilized the most in comparison to its equals. Same thing for comparable pieces of information.

**Comment by ktsaou** [comment]
So you would like to have a CPU chart with dimensions the total CPU utilization of each core/CPU 

Is that right?

**Comment by Carles-Figuerola** [comment]
I'll expand on what I'm trying to say. Imagine the case where the computer has 2 cpus, so netdata will create one graph for each cpu. Those two graphs would look that this:

![cpu0-current](https://cloud.githubusercontent.com/assets/13749641/16246375/951c116c-37ca-11e6-952f-6abbd3d18417.png)
![cpu1-current](https://cloud.githubusercontent.com/assets/13749641/16246377/96df42bc-37ca-11e6-8365-bb3ab1fcb24c.png)
We get maximum information on a per core basis because we can see all the details, but it is easy to miss that one is being used at peaks of 5% while the other peaks at 30%.

Normalizing to the maximum range of the metric doesn't help either because it can make some graphs disappear:
![cpu1-100](https://cloud.githubusercontent.com/assets/13749641/16246458/ec52eb86-37ca-11e6-8568-ef979c78f052.png)
![cpu0-100](https://cloud.githubusercontent.com/assets/13749641/16246455/ea9169c6-37ca-11e6-90ee-bc4813766f66.png)

The ideal solution would be to get the highest value of a set of metrics (in this case ~38) and make all graphs in a group have that value as their max level:
![cpu0-normalized](https://cloud.githubusercontent.com/assets/13749641/16246564/6002da14-37cb-11e6-832c-8959decce49e.png)
![cpu1-normalized](https://cloud.githubusercontent.com/assets/13749641/16246568/63405bca-37cb-11e6-870f-7f2ab68c6d72.png)
Which makes it very easy to see if there is an imbalance in similar metrics.

Obviously, neither the first or the third method would be useful by themselves but a way to change between them would be very nice.

**Comment by ktsaou** [comment]
I see. So you are mainly interested in normalizing the y-range of the charts.

Today, netdata tries to adapt the y-range of all charts so that you get the max visual detail of them. For example, if all values of such a chart range from 30 to 40, netdata will show a chart with y-range 30-40, thus magnifying the visual detail within this range.

I understand however your need. We need to find a way of identifying the charts that should have synced y-range.

**Comment by simonnagl** [comment]
If we think of making the y-range more appropriate we should also think about which charts should not get "the max visual detail" but a specified range or a specified lowest or highest value.

An example is disk space usage. There the scale always should be [0;<disk_size>] to have a better experience.

**Comment by thinrope** [comment]
Being able to select charts in the WebUI may be one way: select all charts that you want, then right-click on one (or use fixed menu) and choose action: Unify y-range.
Similar will be, "use log scale"

Other useful actions to dynamically create new chart such that:
* merge:  it shows all selected data
* add: add the data (per interval) and display single aggregate
* subtract: hmm, only useful for two (greyed out if you select >2)

**Comment by ktsaou** [comment]
Now charts can have synchronized y-axis, using:

```html
    <div ...
    data-common-max="name"
    data-common-min="name"
    ...></div>
```

`name` is anything you like. The charts with the name `name` will have common y-range (min, max, or both).
