### ISSUE TITLE
Custom registry appears broken. 

### ISSUE THREAD

**Issue by davenull** [firehol/netdata#594]
I have the main system I want to be the registry configured as per the instructions, and all the other machines point to it as well, but none of them communicate with the registry, nor am I ever given a UID. What could I have done wrong?

**Comment by davenull** [comment]
It appears to only be affecting the arch machines, and I used pacman to install it on all of them.

**Comment by ktsaou** [comment]
Go to http://your.netdata.server:19999/api/v1/registry?action=hello

Try this on the problematic servers. What do they respond?

**Comment by davenull** [comment]
{
	"action": "hello",
	"status": "ok",
	"hostname": "(null)",
	"machine_guid": "",
	"registry": "(null)"
}

**Comment by davenull** [comment]
The config entries follow for the registry, the other machines have enabled = no
[registry]
         enabled = yes
         registry db directory = /var/lib/netdata/registry
         registry to announce = http://192.168.1.110:19999

**Comment by davenull** [comment]
As far as I can tell, in the Arch package, the Machine guid is never generated.

**Comment by davenull** [comment]
For comparison, this is the results from my Scientific Linux machine. 
(Some details altered to keep guid and hostname secret)
{
	"action": "hello",
	"status": "ok",
	"hostname": "victory",
	"machine_guid": "d7e1a562-3edf5-11e6-bd211-000c2987fe77",
	"registry": "https://registry.my-netdata.io"
}

**Comment by ktsaou** [comment]
Strange. Can you check /var/lib/netdata/registry?
What files are there on the server that returns null machine guid?

**Comment by ktsaou** [comment]
Check also the permissions of the directory

**Comment by davenull** [comment]
Actually, that directory was never created by the arch package. Seems that would be causing the issues.

**Comment by davenull** [comment]
Is there a way to force the creation of the required directories and the guid?

**Comment by ktsaou** [comment]
Do these:

```sh
mkdir /var/lib/netdata
chown netdata:netdata /var/lib/netdata
```

then restart netdata, it will create the rest.

In version 1.2.0 (the arch version) `make install` did not create `/var/lib/netdata`. Now it does.

**Comment by ktsaou** [comment]
I am closing this. If you need further help, please post here.
