### ISSUE TITLE
NGINX sample backend server code missing ;

### ISSUE THREAD

**Issue by n7ipb** [firehol/netdata#599]
Original code:
    location ~ /netdata/(?<behost>.*) {
        return 301 /netdata/$behost/
    }

Should be:
    location ~ /netdata/(?<behost>.*) {
        return 301 /netdata/$behost/;
    }
 
Else nginx startup gives an error: nginx: [emerg] unexpected "}"

**Comment by ktsaou** [comment]
thanks!
