### ISSUE TITLE
IPv4 + IPv6

### ISSUE THREAD

**Issue by cobrafast** [firehol/netdata#60]
I'd like to have combined stats of IPv4 (the way it's now) and IPv6 (I'm aware there don't seem to be any IPv6 stats at the moment).

**Comment by ktsaou** [comment]
Well, there are no IPv6 stats at the moment, because I don't know where to find them.
Do you have any idea where in /proc or /sys they are?

**Comment by cobrafast** [comment]
Spontaneously, on a 4.3.3-7 x86_64 kernel, I can find the following files:

- /proc
  - /dev_snmp6/*
  - /icmp6
  - /igmp6
  - /ip6_*
  - /ipv6_route
  - /mcfilter6
  - /raw6
  - /rt6_stats
  - /snmp6
  - /sockstat6
  - /tcp6
  - /udp6
  - /udplite6

**Comment by ktsaou** [comment]
well, most of these are not statistics.

Possibly these are:

- `/proc/net/sockstat6`
- `/proc/net/rt6_stats`
- `/proc/net/snmp6`

Ok. My poor research.
Let me find some documentation to figure out which charts we need.

**Comment by ktsaou** [comment]
I am writing the ipv6 data collector, using `/proc/net/snmp6`.

I cannot find what these are:

```
Ip6InNoECTPkts                          1161295
Ip6InECT1Pkts                           0
Ip6InECT0Pkts                           6
Ip6InCEPkts                             0
```

Does anyone know?

**Comment by ArtriciaDM** [comment]
Wow

Artricia Harris

On Apr 2, 2016 10:47 AM, Costa Tsaousis <notifications@github.com> wrote:
I am writing the ipv6 data collector, using `/proc/net/snmp6`.

I cannot find what these are:

```
Ip6InNoECTPkts                          1161295
Ip6InECT1Pkts                           0
Ip6InECT0Pkts                           6
Ip6InCEPkts                             0
```

Does anyone know?


---

**Comment by ktsaou** [comment]
Also, any idea how to group in charts these:

```
Icmp6InMsgs                             68
Icmp6InErrors                           0
Icmp6OutMsgs                            17
Icmp6OutErrors                          0
Icmp6InCsumErrors                       0
Icmp6InDestUnreachs                     1
Icmp6InPktTooBigs                       0
Icmp6InTimeExcds                        0
Icmp6InParmProblems                     0
Icmp6InEchos                            2
Icmp6InEchoReplies                      2
Icmp6InGroupMembQueries                 0
Icmp6InGroupMembResponses               0
Icmp6InGroupMembReductions              0
Icmp6InRouterSolicits                   0
Icmp6InRouterAdvertisements             0
Icmp6InNeighborSolicits                 0
Icmp6InNeighborAdvertisements           63
Icmp6InRedirects                        0
Icmp6InMLDv2Reports                     0
Icmp6OutDestUnreachs                    1
Icmp6OutPktTooBigs                      0
Icmp6OutTimeExcds                       0
Icmp6OutParmProblems                    0
Icmp6OutEchos                           2
Icmp6OutEchoReplies                     2
Icmp6OutGroupMembQueries                0
Icmp6OutGroupMembResponses              0
Icmp6OutGroupMembReductions             0
Icmp6OutRouterSolicits                  3
Icmp6OutRouterAdvertisements            0
Icmp6OutNeighborSolicits                1
Icmp6OutNeighborAdvertisements          0
Icmp6OutRedirects                       0
Icmp6OutMLDv2Reports                    8
Icmp6InType1                            1
Icmp6InType128                          2
Icmp6InType129                          2
Icmp6InType136                          63
Icmp6OutType1                           1
Icmp6OutType128                         2
Icmp6OutType129                         2
Icmp6OutType133                         3
Icmp6OutType135                         1
Icmp6OutType143                         8
```

I guess we are going to have these charts:

1. icmp_messages
   - Icmp6InMsgs
   - Icmp6OutMsgs

2. icmp_by_type
 - Icmp6InType1
 - Icmp6InType128
 - Icmp6InType129
 - Icmp6InType136
 - Icmp6OutType1
 - Icmp6OutType128
 - Icmp6OutType129
 - Icmp6OutType133
 - Icmp6OutType135
 - Icmp6OutType143

3. icmp_errors
 - Icmp6InErrors
 - Icmp6OutErrors
 - Icmp6InCsumErrors
 - Icmp6InDestUnreachs
 - Icmp6InPktTooBigs
 - Icmp6InTimeExcds
 - Icmp6InParmProblems
 - Icmp6OutDestUnreachs
 - Icmp6OutPktTooBigs
 - Icmp6OutTimeExcds
 - Icmp6OutParmProblems

4. icmp_echos
 - Icmp6InEchos
 - Icmp6OutEchos
 - Icmp6InEchoReplies
 - Icmp6OutEchoReplies

5. icmp_groupmemb
 - Icmp6InGroupMembQueries
 - Icmp6InGroupMembResponses
 - Icmp6InGroupMembReductions
 - Icmp6OutGroupMembQueries
 - Icmp6OutGroupMembResponses
 - Icmp6OutGroupMembReductions

6. icmp_router
 - Icmp6InRouterSolicits
 - Icmp6InRouterAdvertisements
 - Icmp6OutRouterSolicits
 - Icmp6OutRouterAdvertisements

7. icmp_neightbor
 - Icmp6InNeighborSolicits
 - Icmp6InNeighborAdvertisements
 - Icmp6OutNeighborSolicits
 - Icmp6OutNeighborAdvertisements

8. icmp_redirects
 - Icmp6InRedirects
 - Icmp6OutRedirects

9. icmp_mldv2
 - Icmp6InMLDv2Reports
 - Icmp6OutMLDv2Reports

Are these ok?

**Comment by ktsaou** [comment]
Your are so responsive...

Anyway, IPv6 performance monitoring just added!
