### ISSUE TITLE
application plugins: mutual exclusion

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#603]
cc @paulfantom 

With the addition of python.d.plugin and the migration of plugins from shell scripting to python, we need to find a way to mutually exclude plugins that do the exact same job.

One solution could be for netdata to create the directory `/var/run/netdata`, when plugins lock predefined files. For example, both mysql plugins could attempt to lock `mysql_local.lock`, so that only one will get the lock and proceed. In this cases we need to find a locking mechanism that can be common across the different plugin technologies (bash, python, node.js, etc)

**Comment by paulfantom** [comment]
I have also thought about using `*.lock` files, especially since we have `NETDATA_CACHE_DIR` which could be used. However there are some problems:
- which plugin should run first?
- need to have persistent naming convention across every plugin (in python job name is created dynamically from configuration file and module name, but in bash it is static)

**Comment by ktsaou** [comment]
I was thinking to using the chart id (i.e. `mysql_local`), which should be the same across all plugins.
Regarding the priorities we could also use hardcoded priorities in the plugins (not the modules of the plugins) and similar locks using the names of the modules (i.e. `mysql`).

We could also use netdata itself somehow. I try to avoid 2-way communication between netdata and its plugins.

I'll think a bit more about it...

**Comment by paulfantom** [comment]
That might work.

Could we agree on naming convention just to clarify our communication?
I propose based on naming of directories:
- plugin: ex. `charts.d.plugin` or `python.d.plugin`
- module: ex. `mysql.chart.sh`

**Comment by ktsaou** [comment]
> Could we agree on naming convention just to clarify our communication?

I agree. That was I had in mind too.

**Comment by paulfantom** [comment]
About 2-way communication, it will complicate everything.

**Comment by ktsaou** [comment]
Yes I agree.

**Comment by ktsaou** [comment]
I have given a solution in #686
