### ISSUE TITLE
python plugins: threads

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#604]
Today, python modules are executed one after another. This has the problem that delays in data collection of one module increase the latency of another. If for example we have to collect data from 30 servers, per second, and each server responds in 50ms, we will not be able to collect all data within 1 second.

To solve this in `node.d.plugin` I have done the following:

1. I utilized javascript async features to collect data concurrently. So all the tasks to collect data are executed in parallel (node.js is single threaded, but has async I/O allowing to behave like there are threads in place).

  So, the main loop keeps track of which jobs has started and which have finished, to avoid collecting data for the same job more than once concurrently.

2. To avoid multiplexing the output sent to netdata from multiple data collections, all modules generate data for netdata in a buffer and only when they finish one iteration, the whole data stream is send to netdata in a single print operation.

@paulfantom any ideas?

**Comment by paulfantom** [comment]
You are reading in my mind.
Today I was searching for some ideas, and currently my main idea is to spawn every job in separate thread utilizing `threading` library. 
Normally I would use `asyncio` python module, but it was introduced in python 3.4 and I want to support python 2.7 and >3.1

**Comment by ktsaou** [comment]
nice!
