### ISSUE TITLE
Disk space utilization for mount is incorrect

### ISSUE THREAD

**Issue by syss** [firehol/netdata#605]
I have mounted hard disk which has one partition over the whole drive (sda).
This partition is ext4 formatted

When I look at netdata it gives this:
![image](https://cloud.githubusercontent.com/assets/1512894/16286046/2d50f140-38da-11e6-817f-70bb10f946e6.png)

but `df -h` gives the following: 
/dev/sda1       275G   43G  219G  17% /mnt/fts300gb

edit: inodes from netdata match the output of `df -i`
edit2: available space of /mnt/fts300gb seems to match used space of `/` (maybe coincidence?)

my id if needed: 950c6083-0fc1-4da3-87c4-dde194ee526f
how can I give you proper debug information?

**Comment by ktsaou** [comment]
netdata uses `statvfs()` system call to find this information.

@simonnagl any ideas?

**Comment by simonnagl** [comment]
@syss: Could you please provide the output of `proc/diskstats` `proc/mounts` and `proc/self/mountinfo`. Also the output of `uname -rsm` might be relevant.

Maby `statvfs` is called with the wrong path. `df` also uses `statfs` but I am pretty sure this is not the reason!

**Comment by syss** [comment]
`/proc/diskstats`

```
179       0 mmcblk0 362814 284384 16632652 2556100 1658189 2269313 35067489 222199210 0 15818210 224778100
 179       1 mmcblk0p1 939 727 29402 4490 1 0 1 20 0 3610 4460
 179       2 mmcblk0p2 361538 283657 16597474 2550870 1658188 2269313 35067488 222199190 0 15816290 224772910
   8       0 sda 4127101 143471 467693074 60933160 2665780 519644 483726496 964344820 0 34182610 1025059400
   8       1 sda1 4126997 143471 467691810 60932450 2665780 519644 483726496 964344820 0 34181820 1025051010
```

`/proc/mounts`
```
/dev/mmcblk0p1 /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro 0 0
/dev/sda1 /mnt/fts300gb ext4 rw,relatime,data=ordered 0 0
```

`/proc/self/mountinfo`
```
15 0 179:2 / / rw,relatime shared:1 - ext4 /dev/root rw,data=ordered
37 15 8:1 / /mnt/fts300gb rw,relatime shared:23 - ext4 /dev/sda1 rw,data=ordered
```

`uname -rsm`
`Linux 4.1.12+ armv6l`

It's a RPi
I stripped the information which I found has nothing to do with root or the mount.
If you need them just tell me

**Comment by ktsaou** [comment]
I think I have fixed it.
Please install the latest git version and let me know if the problem remains.
