### ISSUE TITLE
Registry trouble

### ISSUE THREAD

**Issue by dropped** [firehol/netdata#607]
I'm testing registry between two ec2 instances, both using Ubuntu 14.04.3 LTS

'instanceA - 172.31.9.120' (registry) 
[registry]
  enabled = yes
  registry to announce = http://172.31.9.120:19999

```
{
	"action": "hello",
	"status": "ok",
	"hostname": "ip-172-31-9-120",
	"machine_guid": "1f6ef878-392b-11e6-9c09-0ad3adcb5c45",
	"registry": "http://172.31.9.120:19999"
}
```

'instance B - 172.31.9.121'
[registry]
  enabled = no
  registry to announce = http://172.31.9.120:19999

```
{
	"action": "hello",
	"status": "ok",
	"hostname": "ip-172-31-9-121",
	"machine_guid": "139ccac6-392f-11e6-a4b5-0ab9e76232b9",
	"registry": "http://172.31.9.120:19999"
}
```

Communication between the instances, it's ok:

```
ip-172-31-9-121:/opt/src/netdata# curl -X GET -i http://172.31.9.120:19999/api/v1/registry?action=hello                                           
HTTP/1.1 200 OK
Connection: close
Server: NetData Embedded HTTP Server
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Date: Thu, 23 Jun 2016 11:38:25 GMT
Expires: Thu, 07 Jul 2016 11:38:25 GMT
Cache-Control: public
Content-Length: 171

{
        "action": "hello",
        "status": "ok",
        "hostname": "ip-172-31-9-120",
        "machine_guid": "1a4c8e06-392f-11e6-8ac1-0ad3adcb5c45",
        "registry": "http://172.31.9.120:19999"
}
```

Reading the logs in the registry, I got this:
```
ERROR: netdata: Registry: cannot open registry file: '/var/lib/netdata/registry/registry.db' (errno 2, No such file or directory)
```

Checked the permissions:

```
# ls /var/lib/netdata/registry -la
total 12
drwxr-xr-x 2 netdata netdata 4096 Jun 23 12:20 .
drwxr-xr-x 3 netdata netdata 4096 Jun 23 10:41 ..
-rw-r--r-- 1 netdata netdata    0 Jun 23 10:41 .keep
-rw-rwxr-- 1 netdata netdata   36 Jun 23 10:41 netdata.public.unique.id
-rw-rw-rw- 1 netdata netdata    0 Jun 23 10:44 registry-log.db
``` 

Clicking in my-netdata, just showing: Loading... 

Any ideas?

Thanks in advance.

**Comment by ktsaou** [comment]
I guess the error has been logged just once. This is normal. I see it has created the file.

I suspect there is something wrong while connecting to the registry. Could you please press F12 on your browser and check for errors on the console tab?

---
Sent from my iphone.

23 Ιουν 2016, 15:31, ο/η dropped <notifications@github.com> έγραψε:

**Comment by dropped** [comment]
Hi @ktsaou 
I see only the registry-log.db (empty) not the registry.db file how the error log informed.

Using Devel Tools, I've got this:
```
ERROR 410: Netdata registry ACCESS failed: http://172.31.9.120:19999
```
My nginx conf:

```
upstream instanceB {
    server 172.31.9.121:19999;
    keepalive 64;
}

upstream instanceA {
    server 172.31.9.120:19999;
    keepalive 64;
}


server {
    listen 80;
    server_name 172.31.9.120;

    auth_basic "Protected";
    auth_basic_user_file passwords;

    location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://$behost/$ndpath$is_args$args;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }

    # make sure there is a trailing slash at the browser
    # or the URLs will be wrong
    location ~ /netdata/(?<behost>.*) {
        return 301 /netdata/$behost/;
    }

}
```

Thanks

**Comment by ktsaou** [comment]
Since you proxy it, the registry url should the path to access the netdata dashboard through your nginx. So the registry url you configured is wrong.

The registry.db is not created if not needed. This is ok.

---
Sent from my iphone.

23 Ιουν 2016, 21:39, ο/η dropped <notifications@github.com> έγραψε:

**Comment by ktsaou** [comment]
Have you solved it?

**Comment by ktsaou** [comment]
Cleaning up. If the problem remains, please post.

**Comment by evasil** [comment]
Hello,

I confirm I get:

`ERROR 410: Netdata registry ACCESS failed: http://xx.yy.zz.aa:ppp`

when accessing non-registry host, but which configured to speak to registry announced as xx.yy.zz.aa:ppp

My registry host is behind the Nginx with Auth. Nginx listens xx.yy.zz.aa:ppp and then proxies to localhost:19999

How the non-registry host will be able to speak to registry, when registry  host is behind passworded Nginx?

**Comment by evasil** [comment]
Sorry, I was testing wrong way, sitting inside of LAN trying to access registry on WAN.

Correct error is as below:

"ERROR 409: Cannot ACCESS netdata registry: http://net.xxx.yyy:zzzz responded with: {"status":"redirect","registry":"http://net.xxx.yyy:zzzz"}"

**Comment by ktsaou** [comment]
Hi, you have cookies disabled at your browser. The registry needs to set "Third party cookies" to your browser, and it seems that you have disabled them. Can you check?

**Comment by evasil** [comment]
Hello Costa,

hm. When I checked last time I used Dev panel in Firefox by F12, to see 
the console.
I was sure cookies are enabled in that mode.

But today I've found that browser cache is set disabled when I used dev 
panel. When I enabled browser cache in dev panel and tested again, it 
worked ok, just asked me to auth the second time (to registry host).

Sorry for false buzz, that was definitely my local issue.

While we are speaking here... I have a question regarding HDD Temp 
graph. When it set to detect drives automatically, it takes only one 
drive - sda, while my system has sdb, sdc, and sdd. However if I set 
them manually in python.d/hddtemp.conf as:

devices:
   - sdb
   - sdc
   - sdd

Then the graph not visible and error log says that:

python.d ERROR: hddtemp: cannot parse configuration file 
'/etc/netdata/python.d/hddtemp.conf': list indices must be integers, not str

is there any way to fix it?

Thank you,

Ilya Vasilenko

**Comment by l2isbad** [comment]
Yo @evasil 

If you have any jobs configured in conf file you need to add `devices` only to job configuration
```yaml
laocalhost:
  name: 'local'
  host: 'localhost'
  devices:
      - sda
      - sdc
      - sdd
  port: 7634
```

**Comment by evasil** [comment]
to @l2isbad 

thank you, I have modified the config, but the issue still exists. I've created a new one here: https://github.com/firehol/netdata/issues/1836 as it is offtopic for the current discussion. Will highly appreciate if you guys may have a look at that.
