### ISSUE TITLE
Authentication prompt twice.

### ISSUE THREAD

**Issue by tx7** [firehol/netdata#610]
Hi all,

I don't know whether it's a Netdata's bug or a SSLissue.
I saved my credentials in my browser when it prompted, then when I relaunch and log into Netdata, it prompts for credentials, I hit OK.
Then it accepted, but a few seconds later, it prompts again with a blank credentials box.
If I click cancel, it still working, but It will prompts again.
However, if I re-enter my credentials, then it's fine.

I've tried it on Firefox and Google Chrome.

**Comment by ktsaou** [comment]
netdata does not authenticate its users. I guess you proxy the requests with another web server. Right?

**Comment by tx7** [comment]
I'm using my own domain: https://abc.xyz.com:7443.
I'm followed the Nginx guide that provided from you guys.

**Comment by ktsaou** [comment]
Hm... I think you get the double authentication because of the registry. One authentication to access the netdata dashboard, and if the netdata you are accessing is not the registry, you get another one to access the registry too.

Is that right?

**Comment by tx7** [comment]
I think so, but I only want to use my domain as main registry.
Is is the registry announce = ?

**Comment by ktsaou** [comment]
I think that if you use the same nginx for all your netdata servers and the registry, on the same path, you will not get authenticated twice. But I have not tried it.

This is the configuration for accessing multiple netdata via one nginx: https://github.com/firehol/netdata/wiki/Running-behind-nginx#access-multiple-netdata-servers-via-one-nginx

If you apply authentication to this config and announce the registry to use the same path too, I guess you will be authenticated once.

Yes, `registry to announce` should be in the same path too.

**Comment by tx7** [comment]
I think I just fixed it.
I turned disabled registry in the netdata.conf.

Thanks for helping.

**Comment by ktsaou** [comment]
ok. Why don't you leave there the default registry?
We will build upon the registry many more features (like dynamic cross server dashboards). You should have it enabled.

**Comment by tx7** [comment]
I have only one server, and now put it back to the default settings, and it using the  [registry.my-netdata.io](url). No more authentication prompt twice.
