### ISSUE TITLE
ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM: not found

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#613]
[root@gaudium:/usr/libexec/netdata/plugins.d]**/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp**

/usr/libexec/netdata/plugins.d/node.d.plugin: line 2: exec: ERROR node.js IS NOT AVAILABLE IN THIS SYSTEM: not found

**Comment by ktsaou** [comment]
install the package `nodejs`

**Comment by sohwaje** [comment]
1.But I cannot show graph.
2.snmp.conf
[root@gaudium:/etc/netdata]vi snmp.conf 
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "211.115.94.198",
            "community": "sigong",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "snmp_switch.bandwidth_port1": {
                    "title": "IDC Firewall",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.2.27",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.2.26",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024
                        }
                    }
                }
           }
        }
    ]
}
![default](https://cloud.githubusercontent.com/assets/19942049/16399486/bfc60eac-3d0d-11e6-96d9-edfb74308ace.JPG)

**Comment by sohwaje** [comment]
- Mib value
.1.3.6.1.2.1.2.2.1.2.26 = STRING: eth2
.1.3.6.1.2.1.2.2.1.2.27 = STRING: eth3
I want to see them.

**Comment by ktsaou** [comment]
Your OIDs are wrong. You need the OIDs that measure the bytes in/out (your are going to need 2 OIDs per ethernet interface). The ones you used are the names of the ethernet interfaces, which of course cannot be charted...

**Comment by sohwaje** [comment]
So..it is as in the following.

# snmpwalk -t 20 -v 1 -O fn -c sigong 10.10.10.1

But I cannot find OIDs that measure the bytes in/out.

**Comment by sohwaje** [comment]
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "10.10.10.1",
            "community": "sigong",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "snmp_switch.bandwidth_port1": {
                    "title": "eth2",
                    "units": "gigabits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.26",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.26",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024
                        }
                    }
                }
                , "snmp_switch.bandwidth_port2": {
                    "title": "eth3",
                    "units": "gigabits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.27",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.27",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024
           }
        }
        }
      }
     }
    ]
}

**Comment by ktsaou** [comment]
which model is the SNMP device your are trying to monitor?

**Comment by sohwaje** [comment]
I want to replace "kilobits" by "gigabits". How?

**Comment by sohwaje** [comment]
SNMP device is TrusGuard.

**Comment by ktsaou** [comment]
> I want to replace "kilobits" by "gigabits"

increase the `divisor`. Your device should have a bytes counter for input and another for output. The `multiplier` and `divisor` do the unit conversion. `algorithm = incremental` means that the source is always increased, so the incremental difference is used, multiplied by the `multiplier` and divided by the `divisor`.

**Comment by ktsaou** [comment]
I am closing this. If you need help, please post here.
