### ISSUE TITLE
SNMP IP Traffic

### ISSUE THREAD

**Issue by Silente** [firehol/netdata#617]
You can set that netdata remark which generate the most IP traffic when connected via SNMP to a firewall for example?

**Comment by ktsaou** [comment]
I am not sure I understand the question. Can you elaborate a bit?

**Comment by Silente** [comment]
Tracking device which generates traffic from the LAN, and coming out to the Internet

**Comment by ktsaou** [comment]
I see. netdata is not a traffic sniffer. If you have an SNMP device that provides this information or another program that can find this information, you could write a netdata plugin to have netdata render this information though.

**Comment by ktsaou** [comment]
I am closing this. If you need any help, post here.
