### ISSUE TITLE
How to change the update link?

### ISSUE THREAD

**Issue by chagara** [firehol/netdata#619]
Helo,

We use certain systems without internet. Is it possible to change the url for the update button to get them updated? also does it have to be in github or can it be hosted on a web server?

**Comment by ktsaou** [comment]
Update check works by fetching the file `version.txt` from netdata, which compares the the latest commit id from github.

In `index.html` there are 2 functions:

1. `getNetdataVersion()` to fetch `version.txt` from netdata
2. `getGithubLatestCommit()` to fetch the latest commit id from github

The check is made in `notifyForUpdate()`.

You can overwrite these functions to do whatever you like.

Keep in mind, we actively work on netdata. So, you will have to redo your changes on every update. You can probably keep a diff and re-apply them to a newer version.

**Comment by chagara** [comment]
thank you. We will have to do this as none of the systems have internet access so we will have to do the steps you mentioned.

**Comment by ktsaou** [comment]
Keep in mind you can disable the update check by deleting the `version.txt` file from `/usr/share/netdata/web`.

**Comment by ktsaou** [comment]
I am closing this. If you need help, post here.
