### ISSUE TITLE
nginx auth doesn't work

### ISSUE THREAD

**Issue by Owned67** [firehol/netdata#622]
nginx/1.10.1

/etc/nginx/passwd/monitoring_htpasswd (chmod 640, chown www-data:www-data monitoring_htpasswd)

file monitoring_htpasswd exit

netdata.conf: https://paste.mondedie.fr/?ce2dffe56dcd8050#uXyb2jhTFPQjR+RmDCrGAUjwC3ry5vNAVIEG5hH8d/w=

No error in log nginx.

I have two vhost (rutorrent and netdata), auth for rutorrent work fine but not for netdata....

**Comment by ktsaou** [comment]
What does it do?
Does nginx respond to requests?
Has the password file any contents?

I don't think this is netdata related. Can you serve some static content with the same nginx config?

**Comment by tx7** [comment]
These codes should locate before 'server'....
`auth_basic "Monitoring";
    auth_basic_user_file "/etc/nginx/passwd/monitoring_htpasswd";`

**Comment by Owned67** [comment]
no auth, i get access without auth...

Sorry, I do not understand your questions my english is bad...

monitoring_htpasswd file is correct (user:passwd)

Nginx work fine, just auth doesn't work for netdata...

In doc nginx, syntax is correclty, so why add before server?

**Comment by tx7** [comment]
If you add the authentication before server, it protects entire site, instead just the portion of the location of the web.

**Comment by Owned67** [comment]
I have try, no change (clear cache, cookie etc... and restart nginx)

**Comment by tx7** [comment]
Remove the quotations: /etc/nginx/passwd/monitoring_htpasswd

I believe the htpasswd shoudl be '**.htpasswd**'

**Comment by Owned67** [comment]
no change xD

sudo htpasswd -c /etc/nginx/.htpasswd myuser

mypassword
repeatmypassword

added to netdata.conf:
auth_basic "Restricted";                                #For Basic Auth
auth_basic_user_file /etc/nginx/.htpasswd;  #For Basic Auth

resart nginx

clear all data in chrome or firefox
go to http://MYIP:19999

no auth....

**Comment by ktsaou** [comment]
Can you serve some static content with the same nginx config?

**Comment by Owned67** [comment]
what?

Sorry, I do not understand your questions my english is bad

**Comment by Owned67** [comment]
I have rutorrent and auth work fine

**Comment by ktsaou** [comment]
Yes I know. But can you test rutorrent with the netdata config?
ngnix communicates with netdata **after** authentication. So, netdata cannot influence nginx authentication.

**Comment by Owned67** [comment]
I have try, no change.

**Comment by paulfantom** [comment]
@Owned67 maybe my nginx configuration will help you.
I have it served under: https://my.domain.tld/netdata
```conf
upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
}

server {

[ other configuration lines ]

    location /netdata {
        return 301 /netdata/;
    }

    location ~ /netdata/(?<ndpath>.*) {
        auth_basic "Protected";
        auth_basic_user_file /etc/nginx/passwords-netdata;
        proxy_redirect off;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
}
```

This is an extract from larger configuration file.

**Comment by Owned67** [comment]
Hello,

it's strange, with my vhost, i have acces by mydomain.com (auth and https) but if access to mydomain:1999, nothing....

Thanks for paste, I'l try

**Comment by tx7** [comment]
I don't put my port number in the server_name.
If you access from your https://abc.xyz.com:8443, then it put proxy it to your localhost.

**Comment by ktsaou** [comment]
Did you solve it?

**Comment by ktsaou** [comment]
Cleaning up. If you need help, just post.
