### ISSUE TITLE
Can netdata be created in RPM or DEB form?

### ISSUE THREAD

**Issue by chagara** [firehol/netdata#623]
Just looking a way to auto deploy netdata inside our repos.

**Comment by X3MBoy** [comment]
Fro creating the RPM, you have the spec files, and the source is available too, so you shouldn't had any problem. For DEB, i have no idea.

**Comment by chagara** [comment]
Do you have any guides on how to do it? I tried to google and couldn find anything I could follow.

**Comment by ktsaou** [comment]
Sorry. I don't know either.
