### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#627]
How to change this font size?
![font](https://cloud.githubusercontent.com/assets/19942049/16477176/72b90088-3eca-11e6-90b9-ea16a6a54e28.JPG)

**Comment by ktsaou** [comment]
I have increased the font sizes a bit recently.
Please update your netdata and give it a try.

I also plan to provide a completely different legend on the charts to allow a lot bigger fonts.

I am closing this now, but you need to discuss something with us, just post.
