### ISSUE TITLE
registry.db not being created

### ISSUE THREAD

**Issue by Telmo** [firehol/netdata#629]
While troubleshooting what hosts were not showing in the my-netdata menu I came across this in the log files:

```
access.log:16-06-30 13:57:44: 95: (sent/all = 202/202 bytes -0%, prep/sent/total = 0.02/0.07/0.09 ms) data: 200 '/api/v1/registry?action=hello'
error.log:16-06-30 13:07:50: ERROR: netdata: Registry: cannot open registry file: '/app/netdata/var/lib/netdata/registry/registry.db' (errno 2, No such file or directory)
error.log:16-06-30 13:17:14: ERROR: netdata: Registry: cannot open registry file: '/app/netdata/var/lib/netdata/registry/registry.db' (errno 2, No such file or directory)
```

The directory exists but the db file is not there:

```
[root@docker-ch2-1p netdata]# ls -la /app/netdata/var/lib/netdata/registry/
total 16
drwxr-xr-x 2 netdata netdata  118 Jun 30 13:07 .
drwxr-xr-x 3 netdata netdata   64 Jun 30 12:49 ..
-rw-r--r-- 1 netdata netdata    0 Jun 30 12:49 .keep
-rw-r--r-- 1 netdata netdata  157 Jun 30 12:49 ._.keep
-rw-rwxr-- 1 netdata netdata  157 Jun 30 12:02 ._netdata.public.unique.id
-rw-rwxr-- 1 netdata netdata   36 Jun 30 12:02 netdata.public.unique.id
-rw-rw-rw- 1 netdata netdata 1991 Jun 30 13:55 registry-log.db
[root@docker-ch2-1p netdata]# ls -la /app/netdata/var/lib/netdata/registry/registry.db
ls: cannot access /app/netdata/var/lib/netdata/registry/registry.db: No such file or directory
[root@docker-ch2-1p netdata]#
```

The system is configured to be a registry:

```
[registry]
	enabled = yes
	# registry db directory = /app/netdata/var/lib/netdata/registry
	# netdata unique id file = /app/netdata/var/lib/netdata/registry/netdata.public.unique.id
	# registry db file = /app/netdata/var/lib/netdata/registry/registry.db
	# registry log file = /app/netdata/var/lib/netdata/registry/registry-log.db
	# registry save db every new entries = 1000000
	# registry expire idle persons days = 365
	# registry domain =
	registry to announce = http://docker-ch2-1p.test.net:19999
	registry hostname = docker-ch2-1p.sys.comcast.net
	# verify browser cookies support = yes
	# max URL length = 1024
	# max URL name length = 50
```

is there anything that I am missing? Is this causing the other hosts not to show on the my-netdata menu?

Thanks

**Comment by ktsaou** [comment]
This is ok. The error says "cannot open", stating the there is no old database file already to load.
This file is created after `registry save db every new entries = 1000000` entries are written to `registry-log.db`. If it fails to create it, it will log "cannot create" and it will continue operating without optimizing the `registry-log.db` file.

**Comment by Telmo** [comment]
the thing is I am still unable to see the other hosts in the my-netdata menu.

**Comment by ktsaou** [comment]
If you go with your browser to the URL you set as `registry to announce`, does a netdata dashboard come up? It should.

If it doesn't come up, the registry URL is wrong.

**Comment by Telmo** [comment]
with this setting:

```
registry to announce = http://docker-ch2-1p.test.net:19999
```

by going to the URL I do see the dashboard, however the my-netdata menu only contains that host, the other hosts have this on their configuration:

```
[registry]
        # enabled = no
        # registry db directory = /app/netdata/var/lib/netdata/registry
        # netdata unique id file = /app/netdata/var/lib/netdata/registry/netdata.public.unique.id
        # registry db file = /app/netdata/var/lib/netdata/registry/registry.db
        # registry log file = /app/netdata/var/lib/netdata/registry/registry-log.db
        # registry save db every new entries = 1000000
        # registry expire idle persons days = 365
        # registry domain =
        registry to announce = http://docker-ch2-1p.test.net:19999
        registry hostname = docker-wc-1p
        # verify browser cookies support = yes
        # max URL length = 1024
        # max URL name length = 50
```

it may be very well that I am configuring something wrong, I just can't figure out what.

from one I can reach the other so I know connectivity is not an issue:

```
[root@docker-wc-1p netdata]# curl -X GET -i http://docker-ch2-1p.sys.comcast.net:19999/api/v1/registry?action=hello
HTTP/1.1 200 OK
Connection: close
Server: NetData Embedded HTTP Server
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Date: Thu, 30 Jun 2016 19:34:36 GMT
Expires: Thu, 14 Jul 2016 19:34:36 GMT
Cache-Control: public
Content-Length: 202

{
	"action": "hello",
	"status": "ok",
	"hostname": "docker-ch2-1p..test.nett",
	"machine_guid": "7efe8ae4-3eba-11e6-bb6d-0242ac110002",
	"registry": "http://docker-ch2-1p..test.net:19999"
}
```

by the way, thank you very much for this project, I have been looking for exactly this for a very long time.

**Comment by ktsaou** [comment]
thanks!

Could you please press F12 on your browser and navigate to another host (not the registry)?
Does it talk to the registry? Is it logging an error on the console of your browser?

**Comment by Telmo** [comment]
Safari and Firefox do not show any errors in the console, Chrome displays this error:
```
Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.
Uncaught TypeError: Cannot read property 'removeAttribute' of null
(anonymous function)	@	VM450:5
(anonymous function)	@	VM450:20
```
but I am not entirely sure that error is not related to something like AdBlock. I am not sure what you mean with "Does it talk to the registry?" I can't see any type of XHR from the non registry to the registry, each on of the hosts only shows itself in the my-netdata menu.

**Comment by ktsaou** [comment]
You mean there is no line like this?

![image](https://cloud.githubusercontent.com/assets/2662304/16530302/2f12ee6e-3fd0-11e6-89b7-e628aaede666.png)

**Comment by Telmo** [comment]
sorry about the delay on the response I was out on vacation and didn't have access to the systems. this is what I am seeing in the logs:

if I login to the secondary host *not* the registry

```
ERROR 409: Cannot ACCESS netdata registry: http://docker-ch2-1p.test.net:19999 responded with: {"action":"access","status":"disabled","hostname":"docker-ch2-1p","machine_guid":"7efe8ae4-3eba-11e6-bb6d-0242ac110002","registry":"https://registry.my-netdata.io"}
```

this one I suspect is because it can't reach the internet:

```
ERROR 409: Cannot ACCESS netdata registry: https://registry.my-netdata.io responded with: {"status":"redirect","registry":"https://registry.my-netdata.io"}
```

**Comment by ktsaou** [comment]
I am a bit confused. Are you using your registry or the default one?

The secondary host (not the registry) advertises the default registry. You have to set your own. The line:

```
registry to announce = http://docker-ch2-1p.test.net:19999
```

has to be set on **all** your netdata hosts.

The second error you posted has to do with browser cookies, including **third party cookies**.
Do you have them enabled?

**Comment by Telmo** [comment]
This is what I see:

GET http://docker-ch2-1p.test.net:19999/api/v1/registry?action=access&machine=7efe8ae4-3eba-11e6-bb6d-0242ac110002&name=docker-wc-1p&url=http%3A%2F%2Fdocker-wc-1p.test.net%3A19999%2F&_=1469473505677

```
{
	"action": "access",
	"status": "ok",
	"hostname": "docker-ch2-1p.test.net",
	"machine_guid": "7efe8ae4-3eba-11e6-bb6d-0242ac110002",
	"person_guid": "5f2ddae0-c939-4432-82aa-44ae07637bc9",
	"urls": [
		[ "7efe8ae4-3eba-11e6-bb6d-0242ac110002", "http://docker-wc-1p.test.net:19999/", 1469473508000
, 2, "docker-wc-1p" ]
	]

}
```

**Comment by Telmo** [comment]
if I click on "my-netdata" and then on docker-ch2-1p.test.net I get a modal windows with this:

```
docker-ch2-1p.test.net
Checking known URLs for this server...
http://docker-ch2-1p.test.net:19999/	OK
http://docker-wc-1p.test.net:19999/	OK

Checks may fail if you are viewing an HTTPS page and the server to be checked is HTTP only.
```

and if I click on the url for http://docker-wc-1p.test.net:19999/ it takes me to the correct URL, but it does not display it in the list of hosts.

**Comment by ktsaou** [comment]
Have you copied the same `/var/lib/netdata/registry` on the 2 servers?
The file `/var/lib/netdata/registry/netdata.public.unique.id` is the unique machine ID of each netdata. I think you have copied that file to both your servers, so the registry think both servers are the same one.

Just delete it from one of the two and restart netdata. It will create a new one.

**Comment by Telmo** [comment]
@ktsaou that fixed the issue! thanks a lot for the help
