### ISSUE TITLE
Forward data to logstash

### ISSUE THREAD

**Issue by jeevanjoseph** [firehol/netdata#636]
Is there a guide or instructions on how to forward the collected data to logstash or a similar logging backend ?
#10 issues seems to reference a logstash forwarder, but no further details

Is there a way for us to control log format using the debug/tracing options and include a selective set of metrics captured to be persisted to the the debug.log file ?

**Comment by jinxfei** [comment]
+1
I also think a forwarding mechanism is wonderful. If the forwarder can be provided by the user as a plugin or extension will be better, because I want to forward(pub) the collected data to a redis server.

**Comment by ktsaou** [comment]
Can you elaborate a bit on how this would work?

netdata collects about 1.000 to 5.000 metrics per server per second and I expect this to reach 10.000 within the next year. This is a lot of information. Even simple logging of this information to a file is well... not practical.

To make good use of the data in netdata, I have currently the following in our todo plan:

1. provide health monitoring directly in netdata #318 (this is my next todo, according to the poll #436), including a central monitoring solution, much like the registry works (i.e. every netdata would be able to health monitor any number of other netdata servers).

2. support longer data history in netdata. I am experimenting with various alternatives. For example http://atlanta.netdata.rocks is setup with `[global].memory mode = map`, which puts all the data in swap like files. Check the constant spikes in `waitio` it has. I think I can extend netdata to support a 2-stage memory model for working on the data: one RAM mode for the last few hours of data and one swap-like mode for archiving the data. This will lower the I/O pressure on the server and will allow netdata to have, for example, 1-2 weeks of data directly on the dashboard, of course with a few GB of disk footprint.

3. to support exporting data I plan to support snapshots #309 . Snapshots will allow us to export data from netdata in any detail we like at predefined periods. For example, once per hour export all the data as average per-minute resolution. These data could then be transferred to another system.

Of course I am open to other ideas...

**Comment by chagara** [comment]
This might work if netdata can export the data in a specific format that logstash can ingest easier. Something kind of like syslog RFC3164 format or any other format logstash accepts. I would say syslog format would probably be easier to do. Here is a list of all the logstash formats it accepts. https://www.elastic.co/guide/en/logstash/current/input-plugins.html

**Comment by paulfantom** [comment]
@chagara First of all [RFC3164](https://tools.ietf.org/html/rfc3164) is obsoleted by [RFC5424](https://tools.ietf.org/html/rfc5424). Secondly syslog protocol isn't very optimal to send 10000 log messages per second, something like ZeroMQ would be more suited for this task.

**Comment by jeevanjoseph** [comment]
I was not looking to capture everything that NetData captures - it really does a large superset of what I really need. For me, knowing my CPU utilization over time (maybe every ${10s} - My jobs are usually long running CPU and memory intensive things ), and other metrics like load average, memory and interrupts would be a good start for me. I also use the MySQL charts.d plugin, so these metrics ${ bad queries, connections etc.}  is also important for me. Its more like Option 3 #309  that I was looking for. 

The goal would be for me to push this to ELK stack and setup Elast-Alert (in Elastic Search) to send notifications when bad things happen (like CPU getting pegged at 100% for  ${long} time).

After discussing this with a couple of other folks who know logstash better than me, using the charts API to GET the stats at a much wider interval would also suffice the need I'm after. I'm going to explore that option more for now .

**Comment by ktsaou** [comment]
implemented netdata backends: **graphite** and **opentsdb** in PR #1264 .
testers needed, so if you use any, please join comment on the PR.

**Comment by ktsaou** [comment]
merged it. so just update netdata and configure it.
wiki page: https://github.com/firehol/netdata/wiki/netdata-backends

**Comment by ktsaou** [comment]
Cleaning up: I am closing this.
If something remains, please post and I'll re-open it.

**Comment by candlerb** [comment]
> Even simple logging of this information to a file is well... not practical.

Aside: [bro](http://blog.bro.org/2012/05/upcoming-binary-output-with-dataseries.html) can write out to a file format called [DataSeries](https://github.com/dataseries/DataSeries) which seems to be [designed](http://www.hpl.hp.com/techreports/2009/HPL-2009-323.pdf) for this sort of application.

**Comment by EnzoAkira** [comment]
Hello all!
Has anyone configured this setting? netdata -> logstash -> Elastic <- Kibana

I came across with a tutorial with netdata to syslog-ng then to elasticsearch and works perfectly, but after a meeting with my superiors they don't want syslog-ng, so I have to try logstash.

The backend configs it's very different that with syslog? And from logstash how I config inputs? I have been studying logstash for a few of days and it hasn't been easy.

**Comment by kumareshan11** [comment]
> nd from logstash how I config in

@EnzoAkira  did you got any good luck with your requirement, am also trying to build similar flow 
netdata -> logstash -> Elastic  > kibana

let me know if you have any suggestions !?
