### ISSUE TITLE
python.d log parser for nginx

### ISSUE THREAD

**Issue by epema** [firehol/netdata#637]
I have multiple vhosts on nginx.
/etc/nginx/conf.d/
site1.conf
site2.conf
site3.conf

Is there a way to have different graph for each vhost?

**Comment by paulfantom** [comment]
I don't think that nginx has something like `stub_status` for every vhost and currently netdata doesn't parse log files (soon it will, look at: #632). When log parser is implemented, monitoring of different vhosts will be possible. For now I don't think there is a way to do it.

**Comment by paulfantom** [comment]
@epema log parser is now implemented in python, but I need to know which values (available in log) you want to present on graph.

**Comment by epema** [comment]
Great! hm.. requests and connections?

**Comment by paulfantom** [comment]
Since this cannot be implemented by using existing `nginx.chart.py` and I will need to create new plugin like `nginx_vhost.chart.py` or something with similar name, @ktsaou can you label it as `new plugin request`?

**Comment by ktsaou** [comment]
Yes ok.
I suggest though this to be named `nginx_log` since we may use it for a lot more than just vhosts. For example to count 404 or specific URL hit, etc.

**Comment by paulfantom** [comment]
Back to this.
> For example to count 404

I wrote a simple parser to show all "20X", "30X", "40X", and "50X" (code below). Is there a need for this?
```py
# -*- coding: utf-8 -*-
# Description: nginx log netdata python.d module
# Author: Pawel Krupa (paulfantom)

from base import LogService
import re

priority = 60000
retries = 60
# update_every = 3

ORDER = ['codes']
CHARTS = {
    'codes': {
        'options': [None, 'nginx status codes', 'requests/s', 'requests', 'nginx_log.codes', 'stacked'],
        'lines': [
            ["20X", None, "incremental"],
            ["30X", None, "incremental"],
            ["40X", None, "incremental"],
            ["50X", None, "incremental"]
        ]}
}


class Service(LogService):
    def __init__(self, configuration=None, name=None):
        LogService.__init__(self, configuration=configuration, name=name)
        if len(self.log_path) == 0:
            self.log_path = "/var/log/nginx/access.log"
        self.order = ORDER
        self.definitions = CHARTS
        pattern = r'" ([0-9]{3}) ?'
        #pattern = r'(?:" )([0-9][0-9][0-9]) ?'
        self.regex = re.compile(pattern)

    def _get_data(self):
        """
        Parse new log lines
        :return: dict
        """
        data = {'20X': 0,
                '30X': 0,
                '40X': 0,
                '50X': 0}
        try:
            raw = self._get_raw_data()
            if raw is None:
                return None
            elif not raw:
                return data
        except (ValueError, AttributeError):
            return None

        regex = self.regex
        for line in raw:
            code = regex.search(line)
            beginning = code.group(1)[0]

            if beginning == '2':
                data["20X"] += 1
            elif beginning == '3':
                data["30X"] += 1
            elif beginning == '4':
                data["40X"] += 1
            elif beginning == '5':
                data["50X"] += 1

        return data

```

**Comment by ktsaou** [comment]
nice! add it to the repo. We will find out...

**Comment by paulfantom** [comment]
Ok, added in #774

**Comment by shadycuz** [comment]
@epema You can make a log file for each vhost. Just put it in the server block. [See this](https://www.digitalocean.com/community/questions/nginx-define-logs-in-nginx-conf-vs-server-blocks). Then in the plugin reference each log file. I'm not sure what the menu would look like if you pull multiple logs. I will let you know when I set mine up.

@paulfantom I like the plugin but it crashes. I think it is because it's trying to access the log while it's being written to by nginx? Maybe? See #1007 for what I see in my log. I will look through my Nginx Log and try to see what details get logged that we might want to parse.

**Comment by ktsaou** [comment]
There is now a new `web_log` plugin capable of monitoring any number of web log files. Check the wiki here: https://github.com/firehol/netdata/wiki/The-spectacles-of-a-web-server-log-file
