### ISSUE TITLE
Mismatched time format

### ISSUE THREAD

**Issue by lokkenjawnz** [firehol/netdata#64]
Time shows in 24H under charts, but in 12H above legends

**Comment by ktsaou** [comment]
ok, I traced it.
The time at the charts it is formatted by be to always show 24H.

The date and time at the legends is controlled by the browser.
In chrome, you have to go to [chrome://settings/languages](chrome://settings/languages) select the local you want, restart chrome and it will be adapted.

On one used is the one marked as "Google Chrome is displayed in this language". I changed mine from "English" to "English (United Kingdom)" (I also placed it first in the list), restarted chrome and now I get date and time properly.

![image](https://cloud.githubusercontent.com/assets/2662304/14225695/ceb75bc8-f8d4-11e5-992f-8cab3cc5a920.png)

**Comment by ktsaou** [comment]
Generally, this date and time should be displayed to user's locale. So, I don't want to set it manually. It would require configuration settings for the user to set the locale, etc, while the browser already has them, which once set properly should work on all web apps.

**Comment by cwoodwar6** [comment]
@ktsaou The U.S. English locale in Chrome does not appear to be formatting the time in the legend to a 12-hr clock as I would assume is standard in U.S. English.

Also, is it possible to use the browser locale to format the chart time? I'd prefer the chart and legend were both in 12hr time.

**Comment by ktsaou** [comment]
Please open a new issue. I think I can add an option for the legend time to be 12-hour based.
But the x-axis of the chart would need 3 more characters, which is a no-go due to space limitations.
