### ISSUE TITLE
terribly slow scrolling up and down in browser

### ISSUE THREAD

**Issue by mailinglists35** [firehol/netdata#652]
latest chrome on windows 8.1; major web sites scroll up and down without delay or interruptions
core2duo @1,8GHz
intel 945 video
3Gb ram
no video hardware acceleration available
video in action https://www.youtube.com/watch?v=cc91ecW6w5o
i scroll down, then nothing happens for many hundreds miliseconds, then it scrolls. very annoying.

**Comment by ktsaou** [comment]
Hi,

I am not sure how to fix this. I guess the problem is this:

> no video hardware acceleration available

Have you tried to switch dashboard settings to lower the pressure of the browser?

**Comment by mailinglists35** [comment]
> Have you tried to switch dashboard settings to lower the pressure of the browser?

yes, makes no difference :(

the same with firefox

**Comment by ktsaou** [comment]
Well... compared to simple web pages that scroll properly, netdata has to calculate the charts when the page is scrolled. Simple web pages just draw text and images. netdata has to fetch data and do math on them to render the charts.

I am afraid you will need to enable hardware acceleration somehow. If you do, your computer will do just fine (I have a few such computers - actually I intentionally developed the javascript code on such a computer - it will still be somewhat slow, but it will be pretty usable).

I am very sorry, but I cannot see any way to speed up this operation without hardware acceleration.

**Comment by mailinglists35** [comment]
drawing the graphs consumes only 13 to 28 % cpu for browser process and happens instantly.
it's the scrolling up and down that pushes the cpu to the limit.

**Comment by ktsaou** [comment]
ok. I profiled it again (you can do it too on chrome, press F12, select profiles, click "Select Javascript CPU Profiles" and `Start` and then click on the page and start scrolling it - to finish it, click `Stop`) :

![image](https://cloud.githubusercontent.com/assets/2662304/16601327/8b736822-4314-11e6-8009-9f04c3ab4dc0.png)

As you can see:

- 60% was used by the browser (I think this is your problem)

- `getBoundingClientRect()` accounts for 5%. This is called to find which charts are visible (via `isVisible()` which is below with 1.74%). It is cached, but the caches are destroyed on scroll.

- `maxMessageFontSize()` accounts for 2.5%. This is called to calculate the font size for hidden charts (the "netdata" watermark).

Let's do an experiment:

Open `/usr/share/netdata/web/dashboard.js` with an editor, find lines 477 - 479 with this content:

```js
		var targets = NETDATA.options.targets;
		var len = targets.length;
		while(len--) targets[len].isVisible();
```

and comment them out (add `//` at the beginning of each line), like that:

```js
		// var targets = NETDATA.options.targets;
		// var len = targets.length;
		// while(len--) targets[len].isVisible();
```

Save it and press control-F5 to reload the dashboard. Is it faster? If yes, I can add this to a setting on the dashboard.

**Comment by mailinglists35** [comment]
yes, it is faster.
this + making the window height small enough to fit one chart (instead of four charts on regular maximized window) makes scrollling near instant on chrome canary

scrolling is effectively instant on firefox nightly regardless of enabling/disabling the dashboard.js code, but also really faster on smaller window height.

here are some profiling on chrome canary
modified dashboard.js, run 3 times, with settings for older pc turned on
http://i.imgur.com/722687T.png
http://i.imgur.com/joLYdK4.png
http://i.imgur.com/YmlsN1v.png

original
http://i.imgur.com/ajqItX9.png
http://i.imgur.com/wgEj6WY.png
http://i.imgur.com/JKzs7Hk.png


with default settings
original dashboard.js
http://i.imgur.com/RMVfK9W.png

modified
http://i.imgur.com/M5tJ96p.png

modified + small height
http://i.imgur.com/RpIFiZR.png

**Comment by mailinglists35** [comment]
should i file an issue to chrome instead?

**Comment by ktsaou** [comment]
Did you solved it?

**Comment by mailinglists35** [comment]
no
but I'll just wait for chrome 53 to become stable (it works ok with it)
