### ISSUE TITLE
Allow empty values when using import function

### ISSUE THREAD

**Issue by topranks** [firehol/netdata#653]
Hi,

Really amazing work on NetBox so far.... it really is a great system and has potential to be by far the best combined DCIM/IPAM system out there!

I found that when importing data the 'optional' fields have to have a non-null value in them to be entered.  I've tried just using two commas back to back, or using the term 'null' in the field, but in both cases this failed (null worked when it was just looking for a string, but on related fields the lookup failed).

Can it be adjusted to that optional fields can be left out when importing via CSV?  So that an empty field represented with two commas (,,) can be used?

thanks,

Cathal.

**Comment by ktsaou** [comment]
I guess you have posted on the wrong project. Most probably you need to post on this: https://github.com/digitalocean/netbox

**Comment by topranks** [comment]
Doh!  I am so sorry ktsaou.... my apologies!

I user netdata all the time on all my systems, and I'm pushing other people towards it all the time.  I had both github's open in different tabs and must have clicked the wrong one :(

All the best,

Cathal.

**Comment by ktsaou** [comment]
no problem :)
