### ISSUE TITLE
Add IP Address to Interface

### ISSUE THREAD

**Issue by topranks** [firehol/netdata#654]
In the GUI it doesn't seem to give an option to select the device/interface when putting in an IP?

Once it's added the device/interface fields are shown when you select the IP, but they just say 'none'.  The only way I've found to populate these fields is using the 'Import IPs' option, and including the device in the CSV.

thanks,

Cathal.

**Comment by ktsaou** [comment]
Again... wrong project?

**Comment by topranks** [comment]
Sorry!
