### ISSUE TITLE
What should I do with it ?

### ISSUE THREAD

**Issue by jiansl** [firehol/netdata#658]
1. The package uuid-dev (or libuuid-devel) has to be installed.
   
   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here
2. The package zlib1g-dev (or zlib-devel) has to be installed.
   
   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here
3. You need basic build tools installed, like:
   
   gcc make autoconf automake pkg-config
   
   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

**Comment by ktsaou** [comment]
before that message there is an error. Could you please post it?
Also, state which distribution/version you have.

**Comment by jiansl** [comment]
version   is 1.2

**Comment by ktsaou** [comment]
@jiansl I need the error shown on your console, the Linux distribution you use and its version.

**Comment by jiansl** [comment]
[root@harzone192168145 netdata-1.2.0]# cd  netdata-1.2.0/
[root@harzone192168145 netdata-1.2.0]# ls
aclocal.m4      config.guess  COPYING      netdata-9999.ebuild    src
autogen.sh      config.h.in   depcomp      netdata-installer.log  system
autom4te.cache  config.h.in~  install-sh   netdata-installer.sh   tests
build           config.log    LICENSE.md   netdata.spec           web
ChangeLog       config.sub    m4           netdata.spec.in
charts.d        configure     Makefile.am  node.d
compile         configure.ac  Makefile.in  plugins.d
conf.d          contrib       missing      README.md
[root@harzone192168145 netdata-1.2.0]# ./netdata-installer.sh

Welcome to netdata!
Nice to see you are giving it a try!

You are about to build and install netdata to your system.

It will be installed at these locations:

  - the daemon    at /usr/sbin/netdata
  - config files  at /etc/netdata
  - web files     at /usr/share/netdata
  - plugins       at /usr/libexec/netdata
  - cache files   at /var/cache/netdata
  - db files      at /var/lib/netdata
  - log files     at /var/log/netdata
  - pid file      at /var/run

This installer allows you to change the installation path.
Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

:-----------------------------------------------------------------------------
Running command:

./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'

:-----------------------------------------------------------------------------
Running command:

./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... 
configure: error: in `/home/netdata-1.2.0/netdata-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues


[root@harzone192168145 netdata-1.2.0]#

**Comment by paulfantom** [comment]
> configure: error: in /home/netdata-1.2.0/netdata-1.2.0': configure: error: C compiler cannot create executables See config.log' for more details.

So what does your `config.log` say?

**Comment by ktsaou** [comment]
> configure: error: C compiler cannot create executables See config.log

This is your problem.

Can you post the last 100 lines of config.log?

**Comment by jiansl** [comment]
ACLOCAL='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run aclocal-1.11'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run tar'
AUTOCONF='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run autoconf'
AUTOHEADER='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run autoheader'
AUTOMAKE='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run automake-1.11'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-O3'
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS=''
LIBMNL_CFLAGS=''
LIBMNL_LIBS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run makeinfo'
MATH_CFLAGS=''
MATH_LIBS=''
MKDIR_P='/bin/mkdir -p'
NFACCT_CFLAGS=''
NFACCT_LIBS=''
OBJEXT=''
OPTIONAL_MATH_CLFAGS=''
OPTIONAL_MATH_LIBS=''
OPTIONAL_NFACCT_CLFAGS=''
OPTIONAL_NFACCT_LIBS=''
OPTIONAL_UUID_CLFAGS=''
OPTIONAL_UUID_LIBS=''
OPTIONAL_ZLIB_CLFAGS=''
OPTIONAL_ZLIB_LIBS=''
PACKAGE='netdata'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='netdata'
PACKAGE_RPM_RELEASE=''
PACKAGE_RPM_VERSION='1.2.0'
PACKAGE_STRING='netdata 1.2.0'
PACKAGE_TARNAME='netdata'
PACKAGE_VERSION='1.2.0'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
UUID_CFLAGS=''
UUID_LIBS=''
VERSION='1.2.0'
ZLIB_CFLAGS=''
ZLIB_LIBS=''
ac_ct_CC='gcc'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
cachedir=''
chartsdir=''
configdir=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='/var'
logdir=''
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
nodedir=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
pluginsdir=''
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='/etc'
target_alias=''
varlibdir=''
webdir=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME "netdata"
#define PACKAGE_TARNAME "netdata"
#define PACKAGE_VERSION "1.2.0"
#define PACKAGE_STRING "netdata 1.2.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE "netdata"
#define VERSION "1.2.0"

configure: exit 77

**Comment by jiansl** [comment]
configure:2988: error: in `/home/netdata-1.2.0/netdata-1.2.0':
configure:2991: error: C compiler cannot create executables
See `config.log' for more details.

**Comment by ktsaou** [comment]
hm... I don't see an error. Anyone having any ideas what is wrong?

**Comment by jiansl** [comment]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by netdata configure 1.2.0, which was
generated by GNU Autoconf 2.63.  Invocation command line was

  $ ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-zlib --with-math --with-user=netdata CFLAGS=-O3

## --------- ##
## Platform. ##
## --------- ##

hostname = harzone192168145
uname -m = x86_64
uname -r = 2.6.32-431.el6.x86_64
uname -s = Linux
uname -v = #1 SMP Sun Nov 10 22:19:54 EST 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /root/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1914: checking whether to enable maintainer-specific portions of Makefiles
configure:1923: result: no
configure:1997: checking for a BSD-compatible install
configure:2065: result: /usr/bin/install -c
configure:2076: checking whether build environment is sane
configure:2136: result: yes
configure:2277: checking for a thread-safe mkdir -p
configure:2316: result: /bin/mkdir -p
configure:2329: checking for gawk
configure:2345: found /bin/gawk
configure:2356: result: gawk
configure:2367: checking whether make sets $(MAKE)
configure:2389: result: yes
configure:2477: checking build system type
configure:2495: result: x86_64-unknown-linux-gnu
configure:2517: checking host system type
configure:2532: result: x86_64-unknown-linux-gnu
configure:2602: checking for gcc
configure:2618: found /usr/bin/gcc
configure:2629: result: gcc
configure:2861: checking for C compiler version
configure:2869: gcc --version >&5
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2873: $? = 0
configure:2880: gcc -v >&5
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
configure:2884: $? = 0
configure:2891: gcc -V >&5
gcc: '-V' option must have argument
configure:2895: $? = 1
configure:2918: checking for C compiler default output file name
configure:2940: gcc -O3   conftest.c  >&5
gcc: error trying to exec 'cc1': execvp: No such file or directory
configure:2944: $? = 1
configure:2982: result: 
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "netdata"
| #define PACKAGE_TARNAME "netdata"
| #define PACKAGE_VERSION "1.2.0"
| #define PACKAGE_STRING "netdata 1.2.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE "netdata"
| #define VERSION "1.2.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2988: error: in `/home/netdata-1.2.0/netdata-1.2.0':
configure:2991: error: C compiler cannot create executables
See `config.log' for more details.

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=-O3
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBMNL_CFLAGS_set=
ac_cv_env_LIBMNL_CFLAGS_value=
ac_cv_env_LIBMNL_LIBS_set=
ac_cv_env_LIBMNL_LIBS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MATH_CFLAGS_set=
ac_cv_env_MATH_CFLAGS_value=
ac_cv_env_MATH_LIBS_set=
ac_cv_env_MATH_LIBS_value=
ac_cv_env_NFACCT_CFLAGS_set=
ac_cv_env_NFACCT_CFLAGS_value=
ac_cv_env_NFACCT_LIBS_set=
ac_cv_env_NFACCT_LIBS_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_UUID_CFLAGS_set=
ac_cv_env_UUID_CFLAGS_value=
ac_cv_env_UUID_LIBS_set=
ac_cv_env_UUID_LIBS_value=
ac_cv_env_ZLIB_CFLAGS_set=
ac_cv_env_ZLIB_CFLAGS_value=
ac_cv_env_ZLIB_LIBS_set=
ac_cv_env_ZLIB_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run aclocal-1.11'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run tar'
AUTOCONF='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run autoconf'
AUTOHEADER='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run autoheader'
AUTOMAKE='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run automake-1.11'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-O3'
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS=''
LIBMNL_CFLAGS=''
LIBMNL_LIBS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/missing --run makeinfo'
MATH_CFLAGS=''
MATH_LIBS=''
MKDIR_P='/bin/mkdir -p'
NFACCT_CFLAGS=''
NFACCT_LIBS=''
OBJEXT=''
OPTIONAL_MATH_CLFAGS=''
OPTIONAL_MATH_LIBS=''
OPTIONAL_NFACCT_CLFAGS=''
OPTIONAL_NFACCT_LIBS=''
OPTIONAL_UUID_CLFAGS=''
OPTIONAL_UUID_LIBS=''
OPTIONAL_ZLIB_CLFAGS=''
OPTIONAL_ZLIB_LIBS=''
PACKAGE='netdata'
PACKAGE_BUGREPORT=''
PACKAGE_NAME='netdata'
PACKAGE_RPM_RELEASE=''
PACKAGE_RPM_VERSION='1.2.0'
PACKAGE_STRING='netdata 1.2.0'
PACKAGE_TARNAME='netdata'
PACKAGE_VERSION='1.2.0'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
UUID_CFLAGS=''
UUID_LIBS=''
VERSION='1.2.0'
ZLIB_CFLAGS=''
ZLIB_LIBS=''
ac_ct_CC='gcc'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
ax_pthread_config=''
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
cachedir=''
chartsdir=''
configdir=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/netdata-1.2.0/netdata-1.2.0/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='/var'
logdir=''
mandir='${datarootdir}/man'
mkdir_p='/bin/mkdir -p'
nodedir=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
pluginsdir=''
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='/etc'
target_alias=''
varlibdir=''
webdir=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME "netdata"
#define PACKAGE_TARNAME "netdata"
#define PACKAGE_VERSION "1.2.0"
#define PACKAGE_STRING "netdata 1.2.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE "netdata"
#define VERSION "1.2.0"

configure: exit 77

**Comment by paulfantom** [comment]
Maybe it is this line that causes problems:
> gcc: error trying to exec 'cc1': execvp: No such file or directory

Which may be resolved by reinstalling `cpp`.
But I am not sure.

**Comment by ktsaou** [comment]
did you solve it?
