### ISSUE TITLE
example html code

### ISSUE THREAD

**Issue by leonteale** [firehol/netdata#664]
What is example html code to add one of the graphs to another page on my site.

i have installed and running the netdata on port 19999 as expected. 

i want to embed a graph on my http://website:80

specifically the graph in the screenshot. do you have example code i could simple add. thanks! 

![2016-07-07 00_20_25-ip-172-31-26-27 netdata dashboard](https://cloud.githubusercontent.com/assets/3170212/16637707/e205e60a-43d8-11e6-8f38-cfa5326d5b60.png)

**Comment by Xela-TheCreation** [comment]
https://github.com/firehol/netdata/wiki/Custom-Dashboards
https://github.com/firehol/netdata/blob/master/web/dashboard.html

you can view the index source, the element you are looking for can be found line 1871-1987. https://github.com/firehol/netdata/blob/master/web/index.html#L1871-L1987

**Comment by ktsaou** [comment]
I hope you solved the issue. If not post here.
