### ISSUE TITLE
Makefile.am:4: option `dist-xz' not recognized

### ISSUE THREAD

**Issue by marcin93** [firehol/netdata#67]
I try to install netdata on suse 11.4 but after installing all dependencies and run ./netdata-installer.sh (as root) I got:
```
Running command:
./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
Makefile.am:4: option `dist-xz' not recognized
autoreconf: automake failed with exit status: 1
```

Installation pass after I removed mentioned option from Makefile.am.

**Comment by ktsaou** [comment]
@alonbl @philwhineray 
Can you help?

**Comment by alonbl** [comment]
too old automake?

please remember that autoreconf && make dist should be done on dev machine, older distros can be used to build.

regardless of above, I am unsure why dist-xz is used for such small project, we can remove this and produce gz, which should be more than sufficient.

**Comment by justincm** [comment]
remove the installed packages using either yum or apt for which ever distro you are using and get the lates and install them from source

get http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz
