### ISSUE TITLE
Accessing NETDATA monitoring from a router outside the local network

### ISSUE THREAD

**Issue by jairusan** [firehol/netdata#675]
I was wondering if this is a limitation or an issue.  I have opened the ports 19999 in my local network and when I access the "external IP : 9999" I can see that I have access to NETDATA but there is so much latency that I am not even able to see the graphics completely.

Is this tool aiming to be use in a local computer only? or through the same subnet or LAN but not externally?

Thank you in advance!

**Comment by ktsaou** [comment]
No there is no such limitation. Something else is the problem.
In `/var/log/netdata/access.log` you can see the time netdata took to respond to each request. It is probably less than 1 ms (netdata logs time from the first byte received to the last byte sent).

**Comment by jairusan** [comment]
ktsaou: Thank you very much for your response.  I wonder if it was because of the company's firewall. I was trying to access NETDATA from a desktop at my company when I was getting the page very slowly and not painting the animation at all.  I will try again and check the logs.  In addition I will also try from a CAFE and see if I get a different result.

Again, Thank you so much! ^^

**Comment by ktsaou** [comment]
ok. I am closing this. If you need more help, just post.

**Comment by jairusan** [comment]
ktsaou: You were right.  My company's firewall is definitely blocking ports/protocol affecting the functionality of NETDATA.  Here is a screenshot of accessing NETDATA from my LTE network, this is so cool!  Thank you again for the hard work.
![netdata-android](https://cloud.githubusercontent.com/assets/5609312/16791772/028d0420-48fd-11e6-96d6-231d3270f903.png)
