### ISSUE TITLE
CoreOS Support

### ISSUE THREAD

**Issue by qrpike** [firehol/netdata#68]
Can you verify if this works on a large CoreOS cluster?

Thanks,

**Comment by ktsaou** [comment]
Sorry. I don't have access to CoreOS.
I don't see why it shouldn't however.
Can you try it?

**Comment by ktsaou** [comment]
have you tried it?

**Comment by qrpike** [comment]
I have not yet. I have a cluster of 32 CoreOS blades, so it would be a good test. Is it possible to run this from inside of a docker container? That seems like a cross-platform solution to at least running it.

**Comment by ktsaou** [comment]
Cleaning up: I am closing this.
netdata runs in containers perfectly, but you will get the most by running it at the host.
I have read a lot about CoreOS, but I haven't had the chance to access one. It would be interesting if you could share your experience with netdata running on it.

**Comment by a86c6f7964** [comment]
just as an fyi. ran
```bash
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
```

and got
```
Loading /etc/os-release ...
Unknown distribution ID: coreos
Cannot find valid distribution in: coreos
Loading /etc/lsb-release ...
/tmp/kickstart.sh: line 215: Linux: command not found
Cannot find valid distribution with lsb-release

I NEED YOUR HELP
It seems I cannot detect your system automatically.
And it seems I cannot find a known package manager in this system.
Please open a github issue to help us support your system too.
```

**Comment by ximbal** [comment]
Same issue here

**Comment by ktsaou** [comment]
CoreOS does not have a package management, so the installer cannot install the required packages for compiling netdata.

On CoreOS I use the static 64bit versions of netdata. They run perfectly on CoreOS.

**Comment by mildred** [comment]
With netdata static version on CoreOS I have an error though, /lib is not writable:

```
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service 
cp: cannot create regular file '/lib/systemd/system/netdata.service': Read-only file system
 FAILED   

 FAILED  Cannot install netdata init service. 
```

It would be great if the static package did support writing the systemd unit to /etc/systemd/system instead
