### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by LotusGuy** [firehol/netdata#680]
The experimental packages installer failed.

This is what it says:

Cannot find /etc/os-release
Cannot find valid distribution with lsb-release
Loading /etc/centos-release ...
/tmp/kickstart.sh: eval: line 127: syntax error near unexpected token `('
/tmp/kickstart.sh: eval: line 127: `CentOS release 6.8 (Final)'
Cannot parse this lsb-release: CentOS release 6.8 (Final)
Loading /etc/redhat-release ...
/tmp/kickstart.sh: eval: line 127: syntax error near unexpected token `('
/tmp/kickstart.sh: eval: line 127: `CentOS release 6.8 (Final)'
Cannot parse this lsb-release: CentOS release 6.8 (Final)

please paste your screen here

```

**Comment by ktsaou** [comment]
Thanks for reporting this.
Could you please re-try the same command?

**Comment by ktsaou** [comment]
did it run ok?

**Comment by LotusGuy** [comment]
Yes, now it runs clean.

Cheers.
