### ISSUE TITLE
python.d.plugin mysql wrong chart

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#681]
![image](https://cloud.githubusercontent.com/assets/2662304/16808514/78d789b6-4925-11e6-884b-ca97a6b914b6.png)

I guess it should be `incremental`.

@paulfantom

**Comment by ktsaou** [comment]
many charts have the same issue.

**Comment by ktsaou** [comment]
actually almost all mysql charts have the same issue.

Also, check this:

![image](https://cloud.githubusercontent.com/assets/2662304/16808678/1c26a00c-4926-11e6-9c30-3a7e049cc171.png)

**Comment by ktsaou** [comment]
Also a squid one:

![image](https://cloud.githubusercontent.com/assets/2662304/16809074/95defae2-4927-11e6-8eab-53af8b7ead77.png)

**Comment by paulfantom** [comment]
Fixed all those issues.
