### ISSUE TITLE
python.d modules configuration documentation

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#685]
I suggest to add this header in all python.d/*.conf files:

```yaml
# netdata python.d.plugin configuration for ${MODULE}
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - global variables
#  - one or more JOBS
#
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# JOB parameters have to be indented (example below).
#
# ----------------------------------------------------------------------
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.
#
# update_every sets the default data collection frequency.
# If unset, the python.d.plugin default is used.
# update_every: 1
#
# priority controls the order of charts at the netdata dashboard.
# Lower numbers move the charts towards the top of the page.
# If unset, the default for python.d.plugin is used.
# priority: 60000
#
# retries sets the number of retries to be made in case of failures.
# If unset, the default for python.d.plugin is used.
# Attempts to restore the service are made once every update_every
# and only if the module has collected values in the past.
# retries: 10
#
# ----------------------------------------------------------------------
# JOBS (data collection sources)
#
# The default JOBS share the same *name*. JOBS with the same name
# are mutually exclusive. Only one of them will be allowed running at
# any time. This allows autodetection to try several alternatives and
# pick the one that works.
#
# Any number of jobs is supported.
#
# All python.d.plugin JOBS (for all its modules) support a set of
# predefined parameters. These are:
#
# job_name:
#     name: myname     # the JOB's name as it will appear at the
#                      # dashboard (by default is the job_name)
#                      # JOBs sharing a name are mutually exclusive
#     update_every: 1  # the JOB's data collection frequency
#     priority: 60000  # the JOB's order on the dashboard
#     retries: 10      # the JOB's number of restoration attempts
#
# Additionally to the above, ${MODULE} also supports the following.
#
```

where `${MODULE}` is the name of each module.

**Comment by ktsaou** [comment]
@paulfantom check this

**Comment by ktsaou** [comment]
updated it.

**Comment by ktsaou** [comment]
I can add it to the files. @paulfantom I want you to check that what I wrote is valid, that python.d.plugin works this way.

**Comment by ktsaou** [comment]
updated it again.

**Comment by paulfantom** [comment]
Everything you wrote is true. However config parser can do a little bit more. I will show on examples:
Those 3 configurations will give you the same nginx job:
1.
```yaml
update_every: 3
url: "http://localhost/stub_status"
```
2.
```yaml
update_every: some_number_which_is_not_important
local:
  url: "http://localhost/stub_status"
  update_every: 3
```
3.
```yaml
update_every: 3
some_name_which_is_overriden:
  url: "http://localhost/stub_status"
  name: local
```

First one can be used when job is only for one instance (ex. `sensors.chart.py`), second one is used when there are many jobs (ex. some database server), and the third one is for jobs which need auto-detection (like default `mysql.conf` for `mysql.chart.py`).
However only `update_every`, `retries` and `priority` can be overriden per job, so this will work, but global `url` is ignored (and `update_every` is equal to 3 for `local` job):
```yaml
update_every: 2
url: "http://example.com/stub_status"
local:
  url: "http://localhost/stub_status"
  update_every: 3
```

What's more, config parser supports more of YAML syntax, which is used in `sensors.chart.py` to exclude sensor types or sensor chips (notice `-` in front of some lines)

**Comment by ktsaou** [comment]
ok.

I did the following changes:

```
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.
```

I removed the second line of this:

```
# Additionally to the above, ${MODULE} also supports the following.
# You can set them globally (default for all JOBs) and/or per JOB.
```

The 1st example you gave is not the same with the other 2. The first one will not have `_local` appended to it. I thought a bit of this while writing the info, but I concluded that this will only confuse people. So, I suggest to document this special behaviour with the additional yaml options (the ` - `) in `sensors.conf` only.

**Comment by paulfantom** [comment]
> The 1st example you gave is not the same with the other 2.

In every module which inherits after `UrlService` default name is `local` (look at line 444 of `base.py`). So they will be the same.

**Comment by paulfantom** [comment]
Of course it is one specific example.

**Comment by ktsaou** [comment]
ok. I still think this special case to be documented on where it is needed.
Do you agree?

If yes, I will make a PR with all the config files.

**Comment by paulfantom** [comment]
Yes, I agree.

**Comment by ktsaou** [comment]
In `python.d.conf` can the global default options be set (update_every, priority, retries)?

**Comment by paulfantom** [comment]
`python.d.conf` will take only `update_every`, `debug`, `enabled` and module names.

**Comment by ktsaou** [comment]
If a module does not set a priority, which one is used?
retries?

**Comment by paulfantom** [comment]
In case of `update_every`, `priority` and `retires`, priority is:
1. configuration file (job section)
2. configuration file (global section)
3. module global value
4. value defined in `BASE_CONFIG` dictionary in `python.d.plugin`

**Comment by ktsaou** [comment]
So, all three variables follow this rule: `update_every`, `priority` and `retries`?

**Comment by paulfantom** [comment]
Yes.

**Comment by ktsaou** [comment]
But `update_every` can also be set in `python.d.conf` ?

**Comment by paulfantom** [comment]
If `update_every` is set in `python.d.conf` it is treated the same way as passing it from command line.

**Comment by ktsaou** [comment]
if both the command line and the python.d.conf update_every are set? I ask because netdata always appends the update frequency to its plugins.

**Comment by paulfantom** [comment]
command line has priority.

Now that I see it. It doesn't make sense to set `update_every` in `python.d.conf`

I propose to skip it.

**Comment by ktsaou** [comment]
sorry for asking so much... I am trying to write the info at the config files.

**Comment by ktsaou** [comment]
i.e. is this valid for `apache_cache.conf`:

```yaml
apache:
  name: "local"
  path: "/var/log/apache/cache.log"

apache2:
  name: "local"
  path: "/var/log/apache2/cache.log"

httpd:
  name: "local"
  path: "/var/log/httpd/cache.log"
```

**Comment by paulfantom** [comment]
Every module can have multiple jobs. Even when it doesn't make sense. This is because `python.d.plugin` is responsible for spawning jobs and modules are just prototypes of those jobs. You cannot write a module which won't be able to support many jobs.

Yes it is valid.

I don't have problems with answering those questions. Ask how many questions you want.

**Comment by ktsaou** [comment]
Is this valid for mysqldb or only for pymysql:

```yaml
mycnf:
  name     : 'local'
  'my.cnf' : '/etc/mysql/my.cnf'
```

**Comment by ktsaou** [comment]
I guess yaml supports both single quotes and double quotes. Yes?

**Comment by paulfantom** [comment]
PyMYSQL is meant to be used as direct replacement of mysqldb, so it should be valid for both.

Better, YAML also supports no quotes (and this is the standard way).

I think that this configuration file could also look like this (but I am not sure):
```yaml
mycnf:
  name   : local
  my.cnf : /etc/mysql/my.cnf
```

**Comment by ktsaou** [comment]
I am also confused a bit about YaML. I have seen a few implementations that require `;` at the end of each line, or they consider the following lines to text on the same one. I don't know if this has to do anything with quotes (i.e. no quotes = semicolon at the end)

**Comment by ktsaou** [comment]
https://learn.getgrav.org/advanced/yaml

- double quotes allow escaping
- single quotes do not allow escaping
- without quotes may interfere with yaml syntax

**Comment by ktsaou** [comment]
So, I guess single quotes is the best to get the string as-is.

**Comment by paulfantom** [comment]
YAML looks very simple, but it is quite complicated configuration file. 
I am using just basics, but `python.d.plugin` uses `yaml.load(stream)` to load configuration file. And PyYAML should be fully compatible with every YAML file.

**Comment by paulfantom** [comment]
Please say somewhere that YAML uses spaces not tabs as indent.

**Comment by ktsaou** [comment]
ok added.

I recall you told me that the all the modules that access URLs support authentication.
Which options enable it?

**Comment by paulfantom** [comment]
Both `password:` and `user:` must be set to use authentication.

**Comment by ktsaou** [comment]
`password` or `pass`, because the mysql one is `pass`.

**Comment by ktsaou** [comment]
I suggest to decide which of the two you will use, and use it everywhere.

**Comment by paulfantom** [comment]
Which do you want?

**Comment by ktsaou** [comment]
`password` pairs with `username`
`pass` pairs with `user`

?

**Comment by ktsaou** [comment]
or support all them...

**Comment by paulfantom** [comment]
So `pass` it is. I will implement it in already open PR #684

**Comment by ktsaou** [comment]
ok
`pass` and `user`.

**Comment by ktsaou** [comment]
does redis has auth support?

**Comment by paulfantom** [comment]
Unfortunately no.

**Comment by ktsaou** [comment]
ok. I see mysql has `password`, not `pass`. Would you change that too?

**Comment by ktsaou** [comment]
my bad. We can leave it `password` everywhere.
You decide.

**Comment by paulfantom** [comment]
I already changed it.

**Comment by ktsaou** [comment]
ok. in mysql too?

**Comment by ktsaou** [comment]
I saw it. yes in mysql too.

**Comment by ktsaou** [comment]
In redis.conf I see the `port` is string. I will make it a number in yaml. Yes?

**Comment by paulfantom** [comment]
Yes, change it.

**Comment by ktsaou** [comment]
Is authentication also supported for squid?

**Comment by ktsaou** [comment]
I also think `request` in squid should be named `url`.

**Comment by ktsaou** [comment]
> I also think request in squid should be named url.

or it does not matter, leave it as is.

**Comment by ktsaou** [comment]
> Is authentication also supported for squid?

please answer just this.

**Comment by paulfantom** [comment]
No it isn't.

**Comment by paulfantom** [comment]
Authentication is only supported for:
- `mysql`
- all services based on `UrlService` (`apache`, `nginx`, and `tomcat`)

**Comment by ktsaou** [comment]
and `phpfm` I guess

**Comment by paulfantom** [comment]
Oh, I forgot about it, but yes.

**Comment by paulfantom** [comment]
I wanted to implement `squid` based on `UrlService`, but they use some strange non-standard uri `cache-object://` which cannot be used with python `urllib`.

**Comment by ktsaou** [comment]
ok, about the sensors, I see this:

```
#types:
#  - temperature
#  - fan
#  - voltage
#  - current
#  - power
#  - energy
#  - humidity
#chips:
#  - i8k
```

Which are valid combinations?
Are there keywords (i.e. chip names) that can be found somehow?

**Comment by ktsaou** [comment]
In postfix and exim is there anything the user can configure? Like the command to be run for example?

**Comment by ktsaou** [comment]
In several email configuration it is useful the configure multiple queues. So it has meaning to have jobs for these modules, each one running a different command to get the queue size of a different queue.

Can this be done?

**Comment by paulfantom** [comment]
Those are all valid `types`, they can be combined as someone wishes.

`chips` are more problematic. Basically when running command `sensors` in command line you get something like this:
```
acpitz-virtual-0                                                                                                                                                                                                                             
Adapter: Virtual device                                                                                                                                                                                                                      
temp1:        +25.0°C  (crit = +107.0°C)                                                                                                                                                                                                     
                                                                                                                                                                                                                                             
i8k-virtual-0                                                                                                                                                                                                                                
Adapter: Virtual device                                                                                                                                                                                                                      
Processor Fan: 3501 RPM                                                                                                                                                                                                                      
CPU:            +45.0°C                                                                                                                                                                                                                      
Ambient:        +38.0°C                                                                                                                                                                                                                      
SODIMM:         +44.0°C                                                                                                                                                                                                                      
Other:          +41.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +46.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:         +44.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:         +45.0°C  (high = +100.0°C, crit = +100.0°C)
```
chips are:
```
acpitz-virtual-0
i8k-virtual-0
coretemp-isa-0000
```
But I am just checking `chips` from configuration file against those above with `startswith()` method, so in config file they can be named as:
1.
```yaml
chips:
  - acpitz
  - i8k
  - coretemp
```
as well as:
2.
```yaml
chips:
  - acpitz-virtual-0
  - i8k-virtual-0
  - coretemp-isa-0000
```

Usually chip name is used like in 1. example.

**Comment by paulfantom** [comment]
Since `exim` and `postfix` are based on `ExecutableService` they don't have anything that can be configured.

I can uncomment code which will enable setting `path` to executable. But it is not tested.

**Comment by ktsaou** [comment]
path to executable or the whole command line?

**Comment by paulfantom** [comment]
Which ever you like.

**Comment by ktsaou** [comment]
> Which ever you like.

ok, please do so, full command lines, so that jobs can be created.

> valid types, they can be combined

combined? How this is done? I mean, by default everything is commented. If I uncomment something then all others are automatically disabled?

**Comment by paulfantom** [comment]
>  full command lines

Just be aware that it is basically `path_to_executable + executable_options` (like `/usr/bin/exim -bpc`). You cannot use shell expressions in it.

**Comment by paulfantom** [comment]
in every module file there is list named `ORDER`. In case of `sensors.chart.py`, `types` just override this list.

deafult `ORDER = ['temperature', 'fan', 'voltage', 'current', 'power', 'energy', 'humidity']`, but when config file is like:
```yaml
types:
  - temperature
  - fan
```
you have only `ORDER = ['temperature', 'fan']` which will effect in getting data only from temperature sensors and fans.

**Comment by paulfantom** [comment]
Also if you change config to:
```yaml
types:
  - fan
  - temperature
```
You should have fans before temperatures in netdata dashboard.

**Comment by ktsaou** [comment]
> Just be aware that it is basically path_to_executable + executable_options (like /usr/bin/exim -bpc). You cannot use shell expressions in it.

Is the path really needed? Can the command be given without its path?

**Comment by ktsaou** [comment]
> you have only ORDER = ['temperature', 'fan'] which will effect in getting data only from temperature sensors and fans.

nice! So this feature can be used on all modules?

**Comment by paulfantom** [comment]
Right now it cannot be used on all modules. Maybe later.

Path isn't needed. For example `exim.chart.py` is using command `exim -bpc`.
Configurable parameter for `ExecutableService` modules is `command:`

**Comment by ktsaou** [comment]
perfect!

**Comment by paulfantom** [comment]
I think this is enough for me today. Good night.
