### ISSUE TITLE
migrating to python.d.plugin

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#686]
One of key issues to migrate to `python.d.plugin` is the default configuration files that are installed at users computers, which have `charts.d.plugin` enabled.

One solution to update the users to the new configuration would be to detect old configuration files that have been used as-is.

I came up with this little script that once run in `conf.d` it will generate the `md5sum` hashes of old versions of all configuration files:

```sh
#!/bin/bash

for x in $(find . -name \*.conf)
do
        x="${x/.\//}"
        echo "${x}"
        for c in $(git log --follow "${x}" | grep ^commit | cut -d ' ' -f 2)
        do
                git checkout ${c} "${x}" || continue
                s="$(cat "${x}" | md5sum | cut -d ' ' -f 1)"
                echo >>configs.signatures "${x}:${s}"
                echo "    ${s}"
        done
        git checkout HEAD "${x}" || break
done

cat configs.signatures | sort -u >configs.signatures.tmp
mv configs.signatures.tmp configs.signatures
```

This is a sample output:

```
apps_groups.conf:0056936ce99788ed9ae1c611c87aa6d8
apps_groups.conf:18ee1c6197a4381b1c1631ef6129824f
apps_groups.conf:2f4a85fedecce1bf425fa1039f6b021e
apps_groups.conf:3af522d65b50a5e447607ffb28c81ff5
apps_groups.conf:4a448831776de8acf2e0bdc4cc994cb4
apps_groups.conf:5bf51bb24fb41db9b1e448bd060d3f8c
apps_groups.conf:636d032928ea0f4741eab264fb49c099
apps_groups.conf:647361e99b5f4e0d73470c569bb9461c
apps_groups.conf:6a47af861ad3dd112124c37fbf09672b
apps_groups.conf:79a37756869d9b4629285922572d6b9b
apps_groups.conf:99c1617448abbdc493976ab9bda5ce02
apps_groups.conf:9c0185ceff15415bc59b2ce2c1f04367
apps_groups.conf:a0ee8f351f213c0e8af9eb7a4a09cb95
apps_groups.conf:a7cceeafb1e6ef1ead503ab65f687902
apps_groups.conf:a837986be634fd7648bcdf939019424a
apps_groups.conf:a9cd91675467c5426f5b51c47602c889
apps_groups.conf:acaa6731a272f6d251afb357e99b518f
apps_groups.conf:bb51112d01ff20053196a57632df8962
apps_groups.conf:d9258e671d0d0b6498af1ce16ef030d2
apps_groups.conf:ebd0612ccc5807524ebb2b647e3e56c9
apps_groups.conf:f2f1b8656f5011e965ac45b818cf668d
apps_groups.conf:fdea185e0e52b459b48852aa37f20e0f
charts.d.conf:4ccb06fff1ce06dc5bc80e0a9f568f6e
charts.d.conf:4e995acb0d6fd77403a2a9dca984b55b
charts.d.conf:535e5113b07b0fc6f3abd59546c276f6
charts.d.conf:a02d14124b19c635c1426cee2e98bac5
charts.d.conf:ca026d7c779f0a7cb7787713c5be5c47
python.d/apache_cache.conf:e0e96cc47ed61d6492416be5236cd4d3
python.d/apache.conf:5278ebbae19c60db600f0a119cb3664e
python.d/apache.conf:5829812db29598db5857c9f433e96fef
python.d.conf:38d1bf04fe9901481dd6febcc0404a86
python.d.conf:4b775fb31342f1478b3773d041a72911
python.d.conf:99a3de85d1e7826ed64a5f8576712e5d
python.d.conf:a2944a309f8ce1a3195451856478d6ae
python.d.conf:af44cc53aa2bc5cc8935667119567522
python.d.conf:b27f10a38a95edbbec20f44a4728b7c4
python.d.conf:b32164929eda7449a9677044e11151bf
python.d.conf:b8969be5b3ceb4a99477937119bd4323
python.d.conf:d55be5bb5e108da1e7645da007c53cd4
python.d.conf:f82924563e41d99cdae5431f0af69155
python.d/cpufreq.conf:7830066c46a7e5f9682b8d3f4566b4e5
python.d/cpufreq.conf:b5b5a8d6d991fb1cef8d80afa23ba114
python.d/example.conf:a8bb4e1d0525f59692778ad8f675a77a
python.d/example.conf:e5f32f54d6d6728f21f9ac26f37d6573
python.d/exim.conf:73125ae64d5c6e9361944cd9bd14844e
python.d/exim.conf:a94af1c808aafdf00537d85ff2197ec8
python.d/hddtemp.conf:731a1fcfe9b2da1b9d685056a59541b8
python.d/hddtemp.conf:d74dc63fbe631dab9a2ff1b0f5d71719
python.d/mysql.conf:1ea8e8ef1fa8a3a0fcdfba236f4cb195
python.d/mysql.conf:5379cdc26d7725e2b0d688d785816cef
python.d/mysql.conf:88f77865f75c9fb61c97d700bd4561ee
python.d/mysql.conf:b0f0a0ac415e4b1a82187b80d211e83b
python.d/mysql.conf:df381f3a7ca9fb2b4b43ae7cb7a4c492
python.d/nginx.conf:21924a6ab8008d16ffac340f226ebad9
python.d/nginx.conf:c61948101e0e6846679682794ee48c5b
python.d/phpfpm.conf:8c1d41e2c88aeca78bc319ed74c8748c
python.d/phpfpm.conf:b8b87574fd496a66ede884c5336493bd
python.d/phpfpm.conf:c88fb430f35b7d8f08775d84debffbd2
python.d/phpfpm.conf:d7e0bd12d4a60a761dcab3531a841711
python.d/postfix.conf:ca249db7a0637d55abb938d969f9b486
python.d/redis.conf:b915126262d08aa9da81de539a58a3fb
python.d/sensors.conf:cfecf298bdafaa7e0a3a263548e82132
python.d/squid.conf:64070d856ab1b47a18ec871e49bbc13b
python.d/squid.conf:78bb08809dffcb62e9bc493840f9c039
python.d/squid.conf:7d8bd884ec26cb35d16c4fc05f969799
python.d/squid.conf:91cf3b3d42cac969b8b3fd4f531ecfb3
python.d/squid.conf:ade389c1b6efe0cff47c33e662731f0a
python.d/squid.conf:e3e5bc57335c489f01b8559f5c70e112
python.d/tomcat.conf:0388b873d0d7e47c19005b7241db77d8
```

We could possibly use this information to check if the user has edited a file or not. If he has not edited the file, then it should be safe to update it to the latest version.

We could implement this in `netdata-installer.sh`.

cc: @paulfantom

**Comment by paulfantom** [comment]
I don't remember if I have been talking about it. Ignore it if I have.

It is not exactly about migration, but about python dependencies. Could we make python3 default interpreter, and use python2 as a fallback? This would need to be implemented in dependency installer script (and shebang in `python.d.plugin` also should be changed a little).

Python3 has many improvements over python2 (ex. not locking every thread when `encode()` is used in one of them), and current modules codebase is compatible with both versions.

**Comment by ktsaou** [comment]
We can switch the shebang and make the installer enable python3 dependencies if python3 is installed (now it just checks the default python version).

However, installing the dependencies will be a mess. Check this: https://github.com/firehol/netdata-demo-site/blob/fbcafead8c5c7bd021e06c5ceb8ed651b0d669eb/install-required-packages.sh#L650-L661

Check also a few lines above about pip3. It is a mess. python3 is not yet mainstream.

Thankfully, at least pyyaml is available on all distributions.

I think the best is to use what the user has set as the default python interpreter. So first try `python`, then `python2` and then `python3`. I prefer `python2` second to allow the users use the mysql plugin.

I think the problem will magnify as we add modules. Think postgress, elasticsearch, etc.

Though, I guess at the end we will be forced to use pip. I don't know.

For the moment setting the shebang to use whatever the user has select for `python` seems right.

**Comment by ktsaou** [comment]
I did it. By default `python`, then `python3`, then `python2`.
So let the users choose.

Also I put `python3` second, although this will never be used.

**Comment by paulfantom** [comment]
> Also I put python3 second, although this will never be used.

It should be used on fedora 24, since it doesn't ship python2 as default (unless you install it).

**Comment by paulfantom** [comment]
> I think the problem will magnify as we add modules.

That depends on number of imported python modules (like MySQLdb), which I am trying not to use.

**Comment by ktsaou** [comment]
I have a few statistics on the number of users that follow the packages installer. The last 2 days about 300 servers were added, but only 50 used the packages installer. This means people have disabled `charts.d.plugin` and are not using `python.d.plugin` mainly because the PyYaml is not there.

I think we should follow the practice I have followed for node.d.plugin and the web dashboard: **package key dependencies with netdata**.

So, since pyyaml is pure python, I suggest to package it with netdata.
Can you do this?

**Comment by paulfantom** [comment]
I can do it. But it will need to bundle two libraries since pyyaml has some minor differences for version 2 and 3. This will add 34 new files in two directories, shall I proceed with it?

Also @glensc won't be happy about it.

**Comment by paulfantom** [comment]
> So, since pyyaml is pure python, I suggest to package it with netdata.

Look at [my fork](https://github.com/paulfantom/netdata), I bundled pyyaml and it is working. Do you want PR with it?

**Comment by ktsaou** [comment]
> Also @glensc won't be happy about it.

I am not either. Distribution simply ignore their users. I am not.

> Do you want PR with it?

yes please. Please add an entry in LICENSE.md and make sure the Makefiles work.

Does the proper version of pyyaml is selected automatically based on python version running the plugin?

**Comment by paulfantom** [comment]
Already done all those things. And yes it is selected automatically based on python version being used.
