### ISSUE TITLE
sensors no longer showing up

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#699]
The temperature charts are no longer showing up after one of the last few updates (I am not sure exactly which one. Looking at the logs, I see:

```
charts.d: 'sensors' is NOT enabled. Add a line with sensors=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
```

**Comment by paulfantom** [comment]
Netdata is using `python.d.plugin` now as default. Could you execute:
```sh
cat /var/log/netdata/error.log | grep sensors
```
and post output?

**Comment by kmlucy** [comment]
It is only the one line posted above:
```
charts.d: 'sensors' is NOT enabled. Add a line with sensors=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
```

**Comment by paulfantom** [comment]
It looks like you don't have `python-pyyaml` installed. Could you run:
```sh
cat /var/log/netdata/error.log | grep python
```
and post output?

**Comment by kmlucy** [comment]
```
16-07-15 21:20:22: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 17
16-07-15 21:20:22: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/python.d.plugin 1 ' on pid 17.
/usr/libexec/netdata/plugins.d/python.d.plugin: line 2: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found
16-07-15 21:20:22: INFO: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 17 stopped after 0 successful data collections (ENDs).
16-07-15 21:20:22: ERROR: netdata: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' exited with error code 127. Disabling it.
```

I should probably mention that I am running it in a Docker container via titpetric/netdata. It seems like the issue is with the container and not with netdata, correct?

**Comment by paulfantom** [comment]
This is the issue:
`line 2: exec: ERROR python IS NOT AVAILABLE IN THIS SYSTEM: not found`
You don't have python in this container. Since you don't have python, netdata cannot execute `python.d.plugin`.

**Comment by paulfantom** [comment]
Look at:
https://github.com/firehol/netdata/wiki/Installation#1-prepare-your-system

**Comment by ktsaou** [comment]
@paulfantom even if python is installed, this will require to user NETDATA_HOST_PREFIX from python.d.plugin.

I mark this as duplicate to #692 and bug.

**Comment by ktsaou** [comment]
and now that I think of it, even setting NETDATA_HOST_PREFIX only cpufreq will work. Sensors will not work since the python version is based on lm-sensors and most probably lm-sensors cannot be aware of NETDATA_HOST_PREFIX.

@kmlucy I think you will have to set `sensors=force` to `/etc/netdata/charts.d.conf` to use the old BASH plugin. I don't see how this can work with the new python.d.plugin.

**Comment by ktsaou** [comment]
@titpetric my bad: I didn't let you know of the new feature set.

@paulfantom has done a wonderful job porting almost all BASH plugins to python, making a lot of plugins (apache, nginx, mysql, etc) a lot more efficient.

The new plugin is now used by default and the old equivalent require from the user to set `plugin=force` in `/etc/netdata/charts.d.conf` to enable them. This has been made to avoid duplicate data collection of the same values.

To ease the installation of dependencies, a new script has been built, that depending on the system it runs it tries to figure the package names that have to be installed. This script is here: https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh Check also the installation page that shows how to use it.

**Comment by titpetric** [comment]
@ktsaou Is it possible to include a test (in netdata-installer.sh) so it fails with a non-zero exit code if something like python is missing? With automake you'd have some ./configure script which does the same.

Also, I can't use install-required-packages in the build, as it's a non-interactive shell. Currently, I'm going to add the required packages into the apt-get lines in build.sh directly, but I would suggest to add some kind of option check for install-required-packages.sh. (--force, -y,...). If it helps, I am also setting ENV DEBIAN_FRONTEND=noninteractive, which you could check in the script.

Best,
Tit

**Comment by titpetric** [comment]
netdata docker fixed with additional dependencies. suggesting to close

**Comment by kmlucy** [comment]
Sensors is showing up again, but there is a related issue. I have two physical CPUs in my server, and each has cores 0-3. Only the cores in the second CPU are getting values. See below. Before the switch to python.d.plugin, there were separate charts for each physical CPU.
![image](https://cloud.githubusercontent.com/assets/13952475/17022944/d47fc086-4f1e-11e6-95d9-b93268ce22d5.png)

**Comment by paulfantom** [comment]
@kmlucy could you give me output of `sensors` command?

**Comment by kmlucy** [comment]
```
kyle@manta:~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +47.0°C  (high = +87.0°C, crit = +103.0°C)
Core 1:       +45.0°C  (high = +87.0°C, crit = +103.0°C)
Core 2:       +48.0°C  (high = +87.0°C, crit = +103.0°C)
Core 3:       +46.0°C  (high = +87.0°C, crit = +103.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +44.0°C  (high = +87.0°C, crit = +103.0°C)
Core 1:       +44.0°C  (high = +87.0°C, crit = +103.0°C)
Core 2:       +46.0°C  (high = +87.0°C, crit = +103.0°C)
Core 3:       +41.0°C  (high = +87.0°C, crit = +103.0°C)
```

**Comment by paulfantom** [comment]
@kmlucy  Could you verify if version from [my fork](https://github.com/paulfantom/netdata) works as expected?

**Comment by kmlucy** [comment]
Using your fork, the sensor data looked good:

![image](https://cloud.githubusercontent.com/assets/13952475/17041461/23c61abe-4f74-11e6-9030-742844ae8778.png)

**Comment by kmlucy** [comment]
With the latest push, it looks like it is working well. Thanks.
