### ISSUE TITLE
A lot of information.

### ISSUE THREAD

**Issue by simpleacc** [firehol/netdata#702]
Hello,

I am using netdata since 1 week ago and I can not find a solution.
On website show us a lot of information that I do not want to use... Can I hide/disable some graphics? For example... I only want to see CPU, RAM, IPv4, Firewall and temperature graphics. Is it possible?

Thanks in advance.

**Comment by ktsaou** [comment]
You can create a custom dashboard. It is very simple. Check `http://your.netdata:19999/tv.html`. View its source. It is plain HTML (no javascript). Just copy it and adapt it.

**Comment by simpleacc** [comment]
Great! Thank you so much.
