### ISSUE TITLE
mass update for netdata?

### ISSUE THREAD

**Issue by maciu10** [firehol/netdata#706]
Is there any options for mass updating multiple netdata servers? As i install more and more servers with netdata its getting harder to keep up with the updates.

**Comment by paulfantom** [comment]
Do you use ansible? If yes then you could write simple ansible playbook for this.

**Comment by maciu10** [comment]
Thanks for the answer and yes i could possibly do it myself (using numerous tools not only ansible). So back to original question - is there such a thing in netdata? Perhaps plans?

**Comment by paulfantom** [comment]
I don't think there are any plans considering mass deployment/upgrade of netdata. @ktsaou are there?

However I had similar problem yesterday, and I started to write ansible playbook, maybe sometime later it will be included.

**Comment by ktsaou** [comment]
I haven't any. But I am open to ideas...

**Comment by maciu10** [comment]
Thanks for the responses guys!
