### ISSUE TITLE
openelec openpht rasplex

### ISSUE THREAD

**Issue by duecedriver** [firehol/netdata#708]
in this system we have no installer or repo

any way to run this in this 'closed' environment of openelec?

**Comment by ktsaou** [comment]
I don't know. If anyone knows please help.

**Comment by paulfantom** [comment]
First what comes into my mind is packaging netdata as a kodi addon (personally I have never done this). 
Second could be compiling openelec from source with included netdata in it.

However there are also problems with netdata modules (nodejs, python).

In the end I don't think you will be able to run netdata on openelec.

**Comment by paulfantom** [comment]
But if someone finds any way to run it on openelec (especially on Raspberry Pi), I would be very grateful for instructions.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
