### ISSUE TITLE
Free Swap chart suggestion

### ISSUE THREAD

**Issue by groxar** [firehol/netdata#71]
The easypiechart of the swap displays the free swap space in contrary to the other charts in the row that display the utilization of their resource.
My suggestion would be to display the swap usage instead. Atleast from my point of view i'm perfectly happy not to use any of my swap space. Actually I would be concerned if the swap usage would go beyond 70% and don't see it as a under utilized resource if the usage is low.

**Comment by ktsaou** [comment]
Well, initially I wanted to display percentages at the top, to give a better overview of the machine.

However, network and disk do not have a max value, so a percentage cannot be calculated (internally a percentage is calculated to render the charts, but this based on the max of the visible area - showing that percentage by number was misleading).

On the other hand, turning the memory charts to absolute values introduces more problems.

For example, to have any meaning, "swap" should be "swap used" and RAM should be "available RAM". They are opposite.

Then, "available RAM" as an absolute number is also wrong. I have "1GB" RAM available. Is it good or bad? You can't tell. But if we show "10% available RAM", you know this is bad. So, I have concluded to show them the way they are now.

**Comment by groxar** [comment]
Using percentages for the overview are flawless and the values for Network and disk are reasonable. It gives an overview over the system usage without needlessly overwhelm the user.
I just instinctively interpreted a full circle as bad and an empty/low one as good (at least on my workstation). 
But i understand your thought and there you are coming from, so i accept your decision and thank you for this excellent monitoring tool. I enjoy having this overview and the visualization that makes real-time system monitoring easy and enjoyable.

**Comment by ktsaou** [comment]
ok. Thanks!
I close it. You can re-open it any time.
