### ISSUE TITLE
failed to contact the registry...

### ISSUE THREAD

**Issue by davidak** [firehol/netdata#711]
I get this error when i have **third-party cookies disabled**.

Reproducible with Chromium 45 and Firefox 47.

I don't get it directly on the registry:

https://registry.my-netdata.io/

In the JS Console i see:
```
ERROR 409: Cannot ACCESS netdata registry: https://registry.my-netdata.io responded with: {"status":"redirect","registry":"https://registry.my-netdata.io"}
```

**Comment by ktsaou** [comment]
Cookes are required. It cannot be done any other way.
Just enable cookies for the registry URL.

**Comment by ktsaou** [comment]
I have implemented this in netdata: https://github.com/firehol/netdata/pull/483
so that netdata can respect DoNotTrack

It is there, but not tested very well, so the feature is disabled by default.
You can test it if you set your own registry.

**Comment by davidak** [comment]
Can you create a troubleshooting section [on the wiki page](https://github.com/firehol/netdata/wiki/mynetdata-menu-item) and link the error message to it?

I think that would be a solution for this ticket.

**Comment by ktsaou** [comment]
ok, added it:

https://github.com/firehol/netdata/wiki/mynetdata-menu-item#troubleshooting-the-registry

Thanks!

**Comment by davidak** [comment]
>To use the registry, your web browser needs to support cookies.

Can you clarify a bit more that the browser has to support **third-party cookies** or allow the URL of the registry. That might not be clear for not so technical people.

**Comment by ktsaou** [comment]
Made the change.
I was not aware of this term, so I learned something today... nice!
thanks!

**Comment by vinodborole** [comment]
@ktsaou Even though my third party cookie support is enabled i am unable to use the registry feature; i get a different error though

`
ERROR 409: Cannot ACCESS netdata registry: http://10.43.11.197:19999/ responded with: {"action":"access","status":"disabled","hostname":"host-1","machine_guid":"a8c8924a-1b71-11e7-ab5e-fa163e34bdb2","registry":"http://10.43.11.197:19999/"}
`

I have two netdata server and one of them is a registry; i followed the [wiki](https://github.com/firehol/netdata/wiki/mynetdata-menu-item) but could not make it work.

I am using google chrome  - Version 57.0.2987.133 (64-bit) 

attached is the cookie settings
![thirdpartycookie](https://cloud.githubusercontent.com/assets/3897901/24797019/1d45f834-1bad-11e7-8d03-fa0d2ff4360c.jpeg)

**Comment by ktsaou** [comment]
Is `http://10.43.11.197:19999/` configured as a registry?
It needs to have `[registry].enabled = yes` in netdata.conf

**Comment by vinodborole** [comment]
@ktsaou My bad; the enabled was "no". Its working now thanks for your prompt response appreciate it 👍

**Comment by elmicha** [comment]
I had the same problem, and in my case I forgot to disable "Privacy Badger".

**Comment by IKENMouad** [comment]
> Is `http://10.43.11.197:19999/` configured as a registry? It needs to have `[registry].enabled = yes` in netdata.conf

i have this configuration. and still get the same error . 

i create an issue for more details #15744
