### ISSUE TITLE
Using netdata with Flask

### ISSUE THREAD

**Issue by MajorTom6** [firehol/netdata#717]
I am using netdata with pythons well used flask.

I have been using flask's inbuilt development server to test various functions along development and while this has worked fine locally, when accessing the development server on the local network (via phone / other laptops) only the flask elements load while the netdata graphs and .css does not.

I have tried taking the dashboard.js file and jquery.js file that netdata serves and put it into flask's static directory, but then I have the same problem even locally !

Please shed some light as to why this is happening and how it may be resolved.

Here are some snippets:

    from flask import Flask, render_template
    app = Flask(__name__)
    @app.route('/')
    def index():
    status = False
    return render_template('index.html', status = status)
    if __name__ == '__main__':
        app.run()

And for the html:

    <script>var netdataTheme = 'slate';</script>
    <script type="text/javascript" src="http://localhost:19999/dashboard.js"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}"/>

And with the local *.js

    <script type=text/javascript src="{{ url_for('static', filename='jquery.js') }}"></script>
    <script>var netdataTheme = 'slate';</script>
    <script type="text/javascript" src="{{ url_for('static', filename='dashboard.js') }}"></script>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}"/>

Sorry I'm not a big web guy so it may be something simple, thanks for any input you can give.
If you need to see the full project it can be found here: https://github.com/majortom6/aqua

**Comment by paulfantom** [comment]
I don't think it is Flask error.

Basically by setting this:
```html
<script type="text/javascript" src="http://localhost:19999/dashboard.js"></script>
```
browser will try to load script from `http://localhost:19999/dashboard.js`. So when you access webpage from the same machine on which it is running, everything will be ok. However if you access it from different machine it won't since `localhost` is now client machine.
Remember that HTML is parsed on client side not on server side.

Quick fix would be to change this:
```html
<script type="text/javascript" src="http://localhost:19999/dashboard.js"></script>
```
to:
```html
<script type="text/javascript" src="http://web_server_ip:19999/dashboard.js"></script>
```
and setting static IP for the web server.

**Comment by MajorTom6** [comment]
Ah yes, that corrected it.
Thanks very much.
I would also like to add I very much appreciate the work you guys have been doing, the python plugin system looks great ! :D

**Comment by paulfantom** [comment]
Thank you very much. 
Seems resolved. Closing.
