### ISSUE TITLE
Can I use Tomcat Multi Instance?

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#719]
I have made session clustering by Tomcat7. Here is 4 instances. I have to monitor them. But I do not understand #426 

plz Help

**Comment by paulfantom** [comment]
#426 was about bash module, currently netdata moved to using python modules as default. Since then you can use `tomcat.chart.py` which has easy to use configuration file for many instances. Just look at default `/etc/netdata/python.d/tomcat.conf`, which also has some instructions how to configure it.

**Comment by sohwaje** [comment]
Thank you for your answer.

How can I start a "python.d/tomcat.conf"? and also 
How can I edit that file?

[root@gaudium:/etc/netdata/python.d]cat tomcat.conf
# netdata python.d.plugin configuration for tomcat
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - global variables
#  - one or more JOBS
#
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# JOB parameters have to be indented (using spaces only, example below).

# ----------------------------------------------------------------------
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.

# update_every sets the default data collection frequency.
# If unset, the python.d.plugin default is used.
# update_every: 1

# priority controls the order of charts at the netdata dashboard.
# Lower numbers move the charts towards the top of the page.
# If unset, the default for python.d.plugin is used.
# priority: 60000

# retries sets the number of retries to be made in case of failures.
# If unset, the default for python.d.plugin is used.
# Attempts to restore the service are made once every update_every
# and only if the module has collected values in the past.
# retries: 5

# ----------------------------------------------------------------------
# JOBS (data collection sources)
#
# The default JOBS share the same *name*. JOBS with the same name
# are mutually exclusive. Only one of them will be allowed running at
# any time. This allows autodetection to try several alternatives and
# pick the one that works.
#
# Any number of jobs is supported.
#
# All python.d.plugin JOBS (for all its modules) support a set of
# predefined parameters. These are:
#
 job_name:
     name: myname     # the JOB's name as it will appear at the
#                      # dashboard (by default is the job_name)
#                      # JOBs sharing a name are mutually exclusive
     update_every: 1  # the JOB's data collection frequency
     priority: 60000  # the JOB's order on the dashboard
     retries: 5       # the JOB's number of restoration attempts
#
# Additionally to the above, tomcat also supports the following:
#
#     url: 'URL'       # the URL to fetch nginx's status stats
#
# if the URL is password protected, the following are supported:
#
     user: 'tomcat'
     pass: 'shee0828'
#

# ----------------------------------------------------------------------
# AUTO-DETECTION JOBS
# only one of them will run (they have the same name)

localhost:
  name : 'tomcat1'
  url  : 'http://localhost:8080/manager/status?XML=true'

localhost:
  name : 'tomcat1'
  url  : 'http://localhost:18080/manager/status?XML=true'

#localipv4:
#  name : 'local'
#  url  : 'http://127.0.0.1:8080/manager/status?XML=true'

#localipv6:
#  name : 'local'
#  url  : 'http://[::1]:8080/manager/status?XML=true'

**Comment by sohwaje** [comment]
python.d ERROR: tomcat: cannot parse configuration file '/etc/netdata/python.d/tomcat.conf': sequence item 2: expected string, ParserError found

**Comment by ktsaou** [comment]
can you post the file?

**Comment by sohwaje** [comment]
What kind of file do you want?
error.log file? or tomcat.conf?

**Comment by ktsaou** [comment]
tomcat.conf

**Comment by sohwaje** [comment]
# netdata python.d.plugin configuration for tomcat
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - global variables
#  - one or more JOBS
#
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# JOB parameters have to be indented (using spaces only, example below).

# ----------------------------------------------------------------------
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.

# update_every sets the default data collection frequency.
# If unset, the python.d.plugin default is used.
update_every: 1

# priority controls the order of charts at the netdata dashboard.
# Lower numbers move the charts towards the top of the page.
# If unset, the default for python.d.plugin is used.
priority: 60000

# retries sets the number of retries to be made in case of failures.
# If unset, the default for python.d.plugin is used.
# Attempts to restore the service are made once every update_every
# and only if the module has collected values in the past.
retries: 5

# ----------------------------------------------------------------------
# JOBS (data collection sources)
#
# The default JOBS share the same *name*. JOBS with the same name
# are mutually exclusive. Only one of them will be allowed running at
# any time. This allows autodetection to try several alternatives and
# pick the one that works.
#
# Any number of jobs is supported.
#
# All python.d.plugin JOBS (for all its modules) support a set of
# predefined parameters. These are:
#
# job_name:
#     name: myname     # the JOB's name as it will appear at the
#                      # dashboard (by default is the job_name)
#                      # JOBs sharing a name are mutually exclusive
#     update_every: 1  # the JOB's data collection frequency
#     priority: 60000  # the JOB's order on the dashboard
#     retries: 5       # the JOB's number of restoration attempts
#
# Additionally to the above, tomcat also supports the following:
#
#     url: 'URL'       # the URL to fetch nginx's status stats
#
# if the URL is password protected, the following are supported:
#
     user: 'tomcat'
     pass: 'shee0828'
#

# ----------------------------------------------------------------------
# AUTO-DETECTION JOBS
# only one of them will run (they have the same name)

localhost:
  name : 'local'
  url  : 'http://localhost:8080/manager/status?XML=true'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8080/manager/status?XML=true'

localipv6:
  name : 'local'
  url  : 'http://[::1]:8080/manager/status?XML=true'
You have new mail in /var/spool/mail/root

**Comment by paulfantom** [comment]
So basically you haven't configured tomcat module.

Your `tomcat.conf` should be like this (excluding comments):

```yaml
tomcat1:
  url: '10.0.1.212:8080'
  user: 'tomcat'
  pass: '12345'
tomcat2:
  url: '10.0.1.212:18080'
  user: 'tomcat'
  pass: '12345'
tomcat3:
  url: '10.0.1.212:28080'
  user: 'tomcat'
  pass: '12345'
tomcat4:
  url: '10.0.1.212:38080'
  user: 'tomcat'
  pass: '12345'
```

Have you read what is in `tomcat.conf`?

Also you have mail for `root`. :smile:

**Comment by sohwaje** [comment]
Thank you for reply.
1.
tomcat1:
  url  : 'http://10.0.1.212:8080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'

tomcat2:
  url  : 'http://10.0.1.212:18080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'

tomcat3:
  url  : 'http://10.0.1.212:28080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'
2.
python.d ERROR: tomcat_tomcat3 expected path separator ([)
python.d INFO: Disabled tomcat/tomcat3
python.d ERROR: tomcat_tomcat2 HTTP Error 401: basic auth failed
python.d ERROR: tomcat_tomcat2 Parse() argument 1 must be string or read-only buffer, not None
python.d INFO: Disabled tomcat/tomcat2


I read it. I did not read it, but I did not understand. So I am Asian beginner. :(

Root told me "Don't be discouraged!!!"

學而時習之 不亦說乎

**Comment by sohwaje** [comment]
Update error.log

python.d ERROR: tomcat_tomcat3 expected path separator ([)
python.d INFO: Disabled tomcat/tomcat3
python.d ERROR: tomcat_tomcat2 expected path separator ([)
python.d INFO: Disabled tomcat/tomcat2
python.d ERROR: tomcat_tomcat1 expected path separator ([)
python.d INFO: Disabled tomcat/tomcat1

**Comment by paulfantom** [comment]
Seems like there is some kind of bug in `tomcat.chart.py` code. Possibly module cannot parse XML provided by tomcat. Sadly I cannot fix it right now.

**Comment by paulfantom** [comment]
Could you send me output of:
```
curl -u tomcat:12345 http://10.0.1.212:8080/manager/status?XML=true
```

so I can find out what is wrong?

**Comment by paulfantom** [comment]
Also your configuration file should follow YAML syntax (indentation with spaces is important!). Sections cannot be written like this:
```yaml
tomcat1:
url : 'http://10.0.1.212:8080/manager/status?XML=true'
user : 'tomcat'
pass : '12345'
```
they should be like this:
```yaml
tomcat1:
  url : 'http://10.0.1.212:8080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'
```

Also what python version it is run with? To check run:
```
python --version
```

Because tomcat module needs at least python 2.7 to run.

**Comment by sohwaje** [comment]
1. curl -u tomcat:12345 http://10.0.1.212:8080/manager/status?XML=true
[tomcat_curl.txt](https://github.com/firehol/netdata/files/380058/tomcat_curl.txt)

**Comment by sohwaje** [comment]
2. YAML syntax 
 I have done.

3.python --version
2.6.6

**Comment by sohwaje** [comment]
1. I installed a python 2.7 and run python -V. 
[root@gaudium:/etc/netdata/python.d]python -V
Python 2.7.9

2. I succeeded in monitoring a tomcat1. but cannot succeeded others. 
python.d ERROR: tomcat_tomcat3 check function failed.
python.d INFO: Disabled tomcat/tomcat3
python.d ERROR: tomcat_tomcat2 check function failed.
python.d INFO: Disabled tomcat/tomcat2

**Comment by paulfantom** [comment]
This message:
```
tomcat_tomcat2 check function failed
```
usually means that `netdata` connected to tomcat instance, but couldn't get any data.

Could you navigate to the folder containing `python.d.plugin` (usually `/usr/libexec/netdata/plugins.d`) and run:
```
./python.d.plugin tomcat debug
```
And post command output?

**Comment by sohwaje** [comment]
[root@gaudium:/usr/libexec/netdata/plugins.d]python -V
Python 2.7.9
[root@gaudium:/usr/libexec/netdata/plugins.d]./python.d.plugin tomcat debug
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
python.d DEBUG: tomcat: loading module configuration: '/etc/netdata/python.d/tomcat.conf'
python.d DEBUG: tomcat: reading configuration
python.d DEBUG: tomcat/tomcat3: job added
python.d DEBUG: tomcat/tomcat2: job added
python.d DEBUG: tomcat/tomcat1: job added
python.d DEBUG: all job objects [<Service(tomcat3, initial daemon)>, <Service(tomcat2, initial daemon)>, <Service(tomcat1, initial daemon)>]
python.d ERROR: tomcat_tomcat3 check function failed.
python.d INFO: Disabled tomcat/tomcat3
python.d ERROR: tomcat_tomcat2 check function failed.
python.d INFO: Disabled tomcat/tomcat2
python.d DEBUG: tomcat_tomcat1 check succeeded
python.d DEBUG: overridden job names: []
python.d DEBUG: all remaining job objects: [<Service(tomcat1, initial daemon)>]
CHART tomcat_tomcat1.accesses '' 'tomcat requests' requests/s statistics tomcat.accesses area 60000 1
DIMENSION accesses accesses absolute 1 1
CHART tomcat_tomcat1.volume '' 'tomcat volume' KB/s volume tomcat.volume area 60001 1
DIMENSION volume volume incremental 1 1
CHART tomcat_tomcat1.threads '' 'tomcat threads' 'current threads' statistics tomcat.threads line 60002 1
DIMENSION current current absolute 1 1
DIMENSION busy busy absolute 1 1
CHART tomcat_tomcat1.jvm '' 'JVM Free Memory' MB statistics tomcat.jvm area 60003 1
DIMENSION jvm jvm absolute 1 1

CHART netdata.plugin_pythond_tomcat_tomcat1 '' 'Execution time for tomcat_tomcat1 plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

python.d DEBUG: created charts for tomcat_tomcat1
python.d DEBUG: tomcat_tomcat1 will be run in 894 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 895 ms (update_every: 1000 ms, latency: 0 ms
BEGIN tomcat_tomcat1.accesses 895073
SET accesses = 63381
END 
BEGIN tomcat_tomcat1.volume 895073
SET volume = 149590219
END 
BEGIN tomcat_tomcat1.threads 895073
SET current = 128
SET busy = 1
END 
BEGIN tomcat_tomcat1.jvm 895073
SET jvm = 31197960
END 

BEGIN netdata.plugin_pythond_tomcat_tomcat1 895073
SET run_time = 12
END
python.d DEBUG: tomcat_tomcat1 updated in 12 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 1000 ms (update_every: 1000 ms, latency: 1 ms
BEGIN tomcat_tomcat1.accesses 1000727
SET accesses = 63385
END 
BEGIN tomcat_tomcat1.volume 1000727
SET volume = 149599667
END 
BEGIN tomcat_tomcat1.threads 1000727
SET current = 128
SET busy = 2
END 
BEGIN tomcat_tomcat1.jvm 1000727
SET jvm = 30861080
END 

BEGIN netdata.plugin_pythond_tomcat_tomcat1 1000727
SET run_time = 12
END
python.d DEBUG: tomcat_tomcat1 updated in 12 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 999 ms (update_every: 1000 ms, latency: 0 ms
BEGIN tomcat_tomcat1.accesses 999278
SET accesses = 63389
END 
BEGIN tomcat_tomcat1.volume 999278
SET volume = 149609162
END 
BEGIN tomcat_tomcat1.threads 999278
SET current = 128
SET busy = 2
END 
BEGIN tomcat_tomcat1.jvm 999278
SET jvm = 30412296
END 

BEGIN netdata.plugin_pythond_tomcat_tomcat1 999278
SET run_time = 11
END
python.d DEBUG: tomcat_tomcat1 updated in 11 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 1000 ms (update_every: 1000 ms, latency: 1 ms
BEGIN tomcat_tomcat1.accesses 1000736
SET accesses = 63393
END 
BEGIN tomcat_tomcat1.volume 1000736
SET volume = 149618635
END 
BEGIN tomcat_tomcat1.threads 1000736
SET current = 128
SET busy = 1
END 
BEGIN tomcat_tomcat1.jvm 1000736
SET jvm = 30066392
END 

BEGIN netdata.plugin_pythond_tomcat_tomcat1 1000736
SET run_time = 13
END
python.d DEBUG: tomcat_tomcat1 updated in 13 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 999 ms (update_every: 1000 ms, latency: 0 ms
BEGIN tomcat_tomcat1.accesses 999166
SET accesses = 63396
END 
BEGIN tomcat_tomcat1.volume 999166
SET volume = 149628083
END 
BEGIN tomcat_tomcat1.threads 999166
SET current = 128
SET busy = 2
END 
BEGIN tomcat_tomcat1.jvm 999166
SET jvm = 29674856
END 
......

Only display tomcat1.

**Comment by paulfantom** [comment]
Could you post output of:
```
curl -u tomcat:12345 http://10.0.1.212:18080/manager/status?XML=true
```

**Comment by sohwaje** [comment]
I tried to follow. "curl -u tomcat:12345 http://10.0.1.212:18080/manager/status?XML=true > curl.txt"

[curl.txt](https://github.com/firehol/netdata/files/381129/curl.txt)

**Comment by paulfantom** [comment]
I found 2 bugs regarding `tomcat.chart.py`
1. module cannot open anything that is on port other than 8080
2. data provided by you is malformed and crashes this module. It throws XML_ERROR_JUNK_AFTER_DOC_ELEMENT error.

I will take care of it, but probably not in this week since I am on trip.

**Comment by sohwaje** [comment]
You're the best.

I hope you enjoy the trip.

**Comment by paulfantom** [comment]
I'm back. Can you check if tomcat is working for you now?

**Comment by sohwaje** [comment]
Yes I can. I'm ready.

**Comment by paulfantom** [comment]
@sohwaje could you try to test netdata from [my repository](https://github.com/paulfantom/netdata)?

**Comment by sohwaje** [comment]
I have to reinstall a netdata?

**Comment by paulfantom** [comment]
You can reinstall or just swap `tomcat.chart.py` with version from my repository and restart `netdata`.

`tomcat.chart.py` should be located in `/usr/libexec/netdata/python.d/tomcat.chart.py`.

**Comment by sohwaje** [comment]
root@gaudium:/usr/libexec/netdata/plugins.d]./python.d.plugin tomcat debug
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
python.d DEBUG: tomcat: loading module configuration: '/etc/netdata/python.d/tomcat.conf'
python.d DEBUG: tomcat: reading configuration
python.d DEBUG: tomcat/tomcat2: job added
python.d DEBUG: tomcat/tomcat1: job added
python.d DEBUG: all job objects [<Service(tomcat2, initial daemon)>, <Service(tomcat1, initial daemon)>]
python.d DEBUG: tomcat_tomcat2 'NoneType' object has no attribute 'attrib'
python.d DEBUG: tomcat_tomcat2 check succeeded
python.d DEBUG: tomcat_tomcat1 check succeeded
python.d DEBUG: overridden job names: []
python.d DEBUG: all remaining job objects: [<Service(tomcat2, initial daemon)>, <Service(tomcat1, initial daemon)>]
python.d ERROR: tomcat_tomcat2 HTTP Error 401: Unauthorized
python.d DEBUG: tomcat_tomcat2 must be string or read-only buffer, not None
python.d ERROR: tomcat_tomcat2 create function failed.
python.d INFO: Disabled tomcat/tomcat2
CHART tomcat_tomcat1.accesses '' 'tomcat requests' requests/s statistics tomcat.accesses area 60000 1
DIMENSION accesses accesses absolute 1 1
CHART tomcat_tomcat1.volume '' 'tomcat volume' KB/s volume tomcat.volume area 60001 1
DIMENSION volume volume incremental 1 1
CHART tomcat_tomcat1.threads '' 'tomcat threads' 'current threads' statistics tomcat.threads line 60002 1
DIMENSION current current absolute 1 1
DIMENSION busy busy absolute 1 1
CHART tomcat_tomcat1.jvm '' 'JVM Free Memory' MB statistics tomcat.jvm area 60003 1
DIMENSION jvm jvm absolute 1 1

CHART netdata.plugin_pythond_tomcat_tomcat1 '' 'Execution time for tomcat_tomcat1 plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

python.d DEBUG: created charts for tomcat_tomcat1
python.d DEBUG: tomcat_tomcat1 will be run in 232 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 233 ms (update_every: 1000 ms, latency: 0 ms
BEGIN tomcat_tomcat1.accesses 233202
SET accesses = 2648
END 
BEGIN tomcat_tomcat1.volume 233202
SET volume = 6248448
END 
BEGIN tomcat_tomcat1.threads 233202
SET current = 128
SET busy = 1
END 
BEGIN tomcat_tomcat1.jvm 233202
SET jvm = 225357184
END 

BEGIN netdata.plugin_pythond_tomcat_tomcat1 233202
SET run_time = 6
END
python.d DEBUG: tomcat_tomcat1 updated in 6 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 999 ms (update_every: 1000 ms, latency: 0 ms
BEGIN tomcat_tomcat1.accesses 999996
SET accesses = 2653
END 
BEGIN tomcat_tomcat1.volume 999996
SET volume = 6260371
END 
BEGIN tomcat_tomcat1.threads 999996
SET current = 128
SET busy = 1
END 
BEGIN tomcat_tomcat1.jvm 999996
SET jvm = 224802304
END

**Comment by sohwaje** [comment]
/etc/netdata/python.d/tomcat.conf
tomcat1:
  url : 'http://127.0.0.1:8080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'

tomcat2:
  url : 'http://127.0.0.1:18080/manager/status?XML=true'
  user : 'tomcat'
  pass : '12345'

**Comment by sohwaje** [comment]
root@gaudium:/etc/netdata/python.d]curl -u tomcat:12345 http://127.0.0.1:18080/manager/status?XML=true
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status><jvm><memory free='128626152' total='275251200' max='872415232'/><memorypool name='PS Eden Space' type='Heap memory' usageInit='15728640' usageCommitted='207093760' usageMax='282591232' usageUsed='101998424'/><memorypool name='PS Old Gen' type='Heap memory' usageInit='41943040' usageCommitted='49283072' usageMax='654311424' usageUsed='25769336'/><memorypool name='PS Survivor Space' type='Heap memory' usageInit='2621440' usageCommitted='18874368' usageMax='18874368' usageUsed='18857288'/><memorypool name='Code Cache' type='Non-heap memory' usageInit='2555904' usageCommitted='12976128' usageMax='251658240' usageUsed='11362560'/><memorypool name='Compressed Class Space' type='Non-heap memory' usageInit='0' usageCommitted='4063232' usageMax='1073741824' usageUsed='3818288'/><memorypool name='Metaspace' type='Non-heap memory' usageInit='0' usageCommitted='33947648' usageMax='-1' usageUsed='32945088'/></jvm><connector name='"ajp-bio-18009"'><threadInfo  maxThreads="200" currentThreadCount="0" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers></workers></connector><connector name='"http-bio-18080"'><threadInfo  maxThreads="200" currentThreadCount="8" currentThreadsBusy="1" /><requestInfo  maxTime="177" processingTime="239" requestCount="7" errorCount="4" bytesReceived="0" bytesSent="16626" /><workers><worker  stage="S" requestProcessingTime="5" requestBytesSent="0" requestBytesReceived="0" remoteAddr="127.0.0.1" virtualHost="127.0.0.1" method="GET" currentUri="/manager/status" currentQueryString="XML=true" protocol="HTTP/1.1" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /></workers></connector><connector name='"http-bio-18443"'><threadInfo  maxThreads="256" currentThreadCount="0" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers></workers></connector></status




[root@gaudium:/etc/netdata/python.d]curl -u tomcat:12345 http://127.0.0.1:8080/manager/status?XML=true
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status><jvm><memory free='75158800' total='274726912' max='872415232'/><memorypool name='PS Eden Space' type='Heap memory' usageInit='15728640' usageCommitted='204472320' usageMax='280494080' usageUsed='154517184'/><memorypool name='PS Old Gen' type='Heap memory' usageInit='41943040' usageCommitted='50855936' usageMax='654311424' usageUsed='25802704'/><memorypool name='PS Survivor Space' type='Heap memory' usageInit='2621440' usageCommitted='19398656' usageMax='19398656' usageUsed='19248224'/><memorypool name='Code Cache' type='Non-heap memory' usageInit='2555904' usageCommitted='11927552' usageMax='251658240' usageUsed='11770944'/><memorypool name='Compressed Class Space' type='Non-heap memory' usageInit='0' usageCommitted='4194304' usageMax='1073741824' usageUsed='3855984'/><memorypool name='Metaspace' type='Non-heap memory' usageInit='0' usageCommitted='34603008' usageMax='-1' usageUsed='33516664'/></jvm><connector name='"http-bio-8443"'><threadInfo  maxThreads="256" currentThreadCount="0" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers></workers></connector><connector name='"ajp-bio-8009"'><threadInfo  maxThreads="200" currentThreadCount="0" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers></workers></connector><connector name='"http-bio-8080"'><threadInfo  maxThreads="256" currentThreadCount="116" currentThreadsBusy="1" /><requestInfo  maxTime="150" processingTime="549" requestCount="114" errorCount="56" bytesReceived="0" bytesSent="266517" /><workers><worker  stage="S" requestProcessingTime="4" requestBytesSent="0" requestBytesReceived="0" remoteAddr="127.0.0.1" virtualHost="127.0.0.1" method="GET" currentUri="/manager/status" currentQueryString="XML=true" protocol="HTTP/1.1" /><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /></workers></connector></statu

**Comment by paulfantom** [comment]
Ok, pushed some changes to my repository. Can you test it?

**Comment by sohwaje** [comment]
I tried again but failed.

**./python.d.plugin tomcat debug**
INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
python.d DEBUG: tomcat: loading module configuration: '/etc/netdata/python.d/tomcat.conf'
python.d DEBUG: tomcat: reading configuration
python.d DEBUG: tomcat/tomcat2: job added
python.d DEBUG: tomcat/tomcat1: job added
python.d DEBUG: all job objects [<Service(tomcat2, initial daemon)>, <Service(tomcat1, initial daemon)>]
python.d DEBUG: tomcat_tomcat2 'NoneType' object has no attribute 'attrib'
python.d DEBUG: tomcat_tomcat2 check succeeded
python.d DEBUG: tomcat_tomcat1 check succeeded
python.d DEBUG: overridden job names: []
python.d DEBUG: all remaining job objects: [<Service(tomcat2, initial daemon)>, <Service(tomcat1, initial daemon)>]
python.d ERROR: tomcat_tomcat2 HTTP Error 401: Unauthorized
python.d DEBUG: tomcat_tomcat2 must be string or read-only buffer, not None
python.d ERROR: tomcat_tomcat2 create function failed.
python.d INFO: Disabled tomcat/tomcat2
CHART tomcat_tomcat1.accesses '' 'tomcat requests' requests/s statistics tomcat.accesses area 60000 1
DIMENSION accesses accesses absolute 1 1
CHART tomcat_tomcat1.volume '' 'tomcat volume' KB/s volume tomcat.volume area 60001 1
DIMENSION volume volume incremental 1 1
CHART tomcat_tomcat1.threads '' 'tomcat threads' 'current threads' statistics tomcat.threads line 60002 1
DIMENSION current current absolute 1 1
DIMENSION busy busy absolute 1 1
CHART tomcat_tomcat1.jvm '' 'JVM Free Memory' MB statistics tomcat.jvm area 60003 1
DIMENSION jvm jvm absolute 1 1

CHART netdata.plugin_pythond_tomcat_tomcat1 '' 'Execution time for tomcat_tomcat1 plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

python.d DEBUG: created charts for tomcat_tomcat1
python.d DEBUG: tomcat_tomcat1 will be run in 550 ms
python.d DEBUG: tomcat_tomcat1 ready to run, after 552 ms (update_every: 1000 ms, latency: 1 ms

**Comment by paulfantom** [comment]
My last commit changed two files from `python.d` directory:
- `tomcat.chart.py`
- `python_modules/base.py`

Based on this message:
> tomcat_tomcat2 'NoneType' object has no attribute 'attrib'

I think you have old `base.py`. Please update it to newer version and retest.

**Comment by sohwaje** [comment]
Thank you so much. been achieved!
<img width="1556" alt="2016-08-07 10 59 52" src="https://cloud.githubusercontent.com/assets/19942049/17460033/caf8d124-5c8e-11e6-8f9b-8b2110289b13.png">
<img width="1591" alt="2016-08-07 11 00 00" src="https://cloud.githubusercontent.com/assets/19942049/17460032/caf477a0-5c8e-11e6-8bf8-20b871e170d1.png">

**Comment by paulfantom** [comment]
One more thing. I believe tomcat charts aren't displayed correctly. To fix this swap `tomcat.chart.py` to newer version from my repository.

**Comment by sohwaje** [comment]
<img width="1717" alt="2016-08-08 9 56 20" src="https://cloud.githubusercontent.com/assets/19942049/17480468/004d178e-5db3-11e6-97b2-0a07786da527.png">
I did.

**Comment by paulfantom** [comment]
Thanks for testing. I believe it is complete.
