### ISSUE TITLE
python.d logservice parses the whole file when starting

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#721]
@paulfantom the LogService should not parse the whole file on the first iteration. The way it is now, if the log file monitored is huge, it takes a considerable amount of time to start.

Of course, special care has to be taken so that this happens only on the first iteration. If the file is closed and re-opened it should attempt to continue from the point it was the last time, or fallback to parse the whole file only if the length of the file is smaller that then last known length.

**Comment by paulfantom** [comment]
Can you explain what should it parse in the first iteration?  Last line only?

**Comment by ktsaou** [comment]
I think this should be the flow:

1. the file is opened and position is set at the end of it and all counters are zeroed
2. python.d calculates the time of the next run and waits until it is time to run
3. if any rows have been read, the plugin processes them and updates its counters
4. the plugin sends the collected values to netdata

When `BEGIN` line does not have microseconds to it, netdata keeps the values but does not render them. So that `incremental` dimensions will work properly at the next iteration.

I have found the following problems:

1. `BEGIN` statements incorrectly report microseconds on the first iteration #720 

2. The plugin reads the whole file while initialising. This has 2 issues:

  - it reports unrealistics values, since the whole file is reported as if it happened within one iteration point
  - it is really slow if the file is very big

3. And a new one, I just found: If no rows are read from the file, no data are send to netdata. This makes the charts show gaps. If the dimensions are `absolute` or `percentage-of-absolute-row` it should send zeros, if the dimensions are `incremental` or `percentage-of-incremental-row` it should send again the values of the last iteration.

  So, the plugin will not report values for a chart to netdata, only if the data collection failed. For the LogService, a log file that does not have any new lines, is not a failure. It should only fail (and show gaps at the charts) if reading the file actually failed.

Keep in mind that `incremental` dimensions are a lot better than `absolute` ones, since netdata properly interpolates `incremental` dimensions to find the exact **rate** per second, using nanosecond calculations. `absolute` ones are not a rate, but rather a snapshot of something at a point in time. `incremental` dimensions can be used by netdata to also report the **volume** of something within a timeframe (e.g. badges), while `absolute` ones will not report accurate values.

**Comment by paulfantom** [comment]
Thanks for explanation, later I'll see how this can be implemented.

**Comment by paulfantom** [comment]
I have implemented fix for 1. in `SimpleService` and for 2. in `LogService`. However 3. cannot be resolved globally since `_get_data` is implemented in module. I will add a comment in `apache_cache.chart.py` about:
> If the dimensions are absolute or percentage-of-absolute-row it should send zeros, if the dimensions are incremental or percentage-of-incremental-row it should send again the values of the last iteration.

Also is this information anywhere in documentation (because it should)?

I will make PR after some testing.

**Comment by paulfantom** [comment]
[This commit](https://github.com/paulfantom/netdata/commit/091bc73943961d24a27ea6eadf5014ccd651376b) should fix all those issues. It also include some minor speed improvements, deactivated prototype of proxy handling in `UrlService` and some code cleanup.

**Comment by ktsaou** [comment]
Regarding 3, I don't know if we should keep the collected values in the job object. I mean, instead of returning the values from `_get_data()`, to have `_get_last_value()`, `_set_new_value()` method in the job, that the modules can call to get and set each dimension value. This way, the modules will not need to do/know anything about the algorithms of the dimensions.

I tried today to write a custom module for the log service, for a custom web app. I ended up placing all the job counters in the job object so that they will remain across `_get_data()` calls. I did this because I needed to have `incremental` dimensions.

I don't know, your call...

**Comment by paulfantom** [comment]
Current flow of every module is like this:
1. run `update()` implemented in `SimpleService`
2. this will run `_get_data` implemented in module
3. which can can execute  `_get_raw_data` implemented in framework class (like `LogService`).

Method from points 1 and 2 can be overridden in custom module. However it is not recommended.

As you can see method `_get_data` must be there. If I want to remove it, I will need to either rewrite parts of all modules to use something new or rewrite it in `LogService`.
I think it will be easier to just change how `_get_raw_data` works and keep last values in job object, but only if it needs to (`incremental` and `percentage-of-incremental-row`). It would be just one dict created in `create` containing dimension names and values.

**Comment by paulfantom** [comment]
I want to create framework with which someone could quickly create a new module. And I think in current state it is fairly easy to write a new module. It just needs couple of things:

1. import framework service class
2. write chart definitions and their order 
3. write `Service` class as a child of framework class
4. add a constructor to class, which will run `FrameworkClass.__init__(self, configuration=configuration, name=name)`
5. add data parsing method `_get_data`, which will execute `_get_raw_data` to get something to work on.

After some code cleanup it won't even need `check()`, like in `nginx.chart.py`.

I believe adding new steps to it, complicates the process. I even want to reduce some steps, like no. 4.

**Comment by ktsaou** [comment]
ok. Probably I didn't explained it right. I didn't suggest to get rid of `_get_data()`. Actually I like it.

Today, apache_cache has this:

```python
        hit = 0
        miss = 0
        other = 0
        for line in raw:
            if "cache hit" in line:
                hit += 1
            elif "cache miss" in line:
                miss += 1
            else:
                other += 1

        return {'hit': hit,
                'miss': miss,
                'other': other}
```

To have incremental values, we need `hit`, `miss` and `other` to be in the job object. What I did, was to search/replace `hit` with `self.hit`, `miss` with `self.miss` and `other` with `self.other`. Of course I initialed them to zero at `__init__()`.

I find this reduntant though. The job object already has a dictionary with all dimensions. So, I thought it would be better to use like this:

```python
        hit = 0
        miss = 0
        other = 0

        # work with local variables, for speed
        for line in raw:
            if "cache hit" in line:
                hit += 1
            elif "cache miss" in line:
                miss += 1
            else:
                other += 1

        # update the values in the job object
        self._add_value('hit', hit)
        self._add_value('miss', miss)
        self._add_value('other', other)

        return True
```

So, what I propose is to define `_set_value('dimension', number)` that will set the value of a dimension and `_add_value('dimension', number)` that will add/increment the value of a dimension inside the job object.

This way, each dimension is independent of the others and the job object could know how to handle them depending on whether it has updated or not.

**Comment by ktsaou** [comment]
If it was not parsing a log file, that would need local variables, for speed, it would look like that:

```
        for line in raw:
            if "cache hit" in line:
                self._add_value('hit', 1)
            elif "cache miss" in line:
                self._add_value('miss', 1)
            else:
                self._add_value('other', 1)

        return True
```

For all other modules, except log parsing, it would be actually simpler and shorter...

**Comment by ktsaou** [comment]
I just checked what mysql and redis do. I think what I propose is not right either.

Probably, an option to treat the `_get_data()` returning dictionary as **additional values** would be better and simpler.

I don't know. Your call. What we need for sure, is incremental dimensions at the log service.

**Comment by paulfantom** [comment]
1. `_get_raw_data()` should be considered what a name says, just a grabber of raw values.
2. `_get_data()` should parse those raw values and there should be logic about what to do with those values (set to 0, or to last value)
3. python has some strange [overhead with every function call](https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Data_Aggregation) so they should be avoided if we want fast data collection. So I consider this wrong:
```py
self._add_value('hit', hit)
self._add_value('miss', miss)
self._add_value('other', other)
```
I was considering this approach couple of weeks ago, but not anymore.
4. I have modified `_get_raw_data` to return empty list (which is considered `False` in python). This can be used in `_get_data` to set values as expected when nothing changes. Basically I would recommend keeping an internal dictionary of default values and updating them in every `_get_data` cycle. This should be faster than executing some additional methods for every dimension.

**Comment by ktsaou** [comment]
> Basically I would recommend keeping an internal dictionary of default values and updating them in every _get_data cycle.

This would be nice. Keep in mind though that gaps should be present for values not collected. You have to somehow detect which values have been collected and which did not. For this reason I think the following is not right if you just going the send the old data to netdata:

> I have modified _get_raw_data to return empty list (which is considered False in python).

So, there is a difference between a value that has been collected, but is zero or "same to the previous on" and a value that has not been collected at all. Keep that in mind. The latest should show a gap (and we will need this for health monitoring).

I have not understood how the plugin will know that a module is supposed to add something to a metric (i.e. log service `incremental`), or replace the previous value with the new (all other services so far, with `incremental` dimensions). Do you have a solution for this?

**Comment by paulfantom** [comment]
Current approach assumes that parsing and validating data will be implemented in `_get_data` method. That way that all those problems would be resolved in module not in framework classes and neither in plugin.

First of all plugin (`python.d.plugin`) doesn't do anything with data, even `print` statement (I think there is only one, in `_commit()`) is in `SimpleService` class, so it cannot know what module is supposed to do with data. Plugin just supervises execution of modules.
Secondly `_get_raw_data` returns RAW data. In case of `LogService` it returns list of last lines from log file, so it also cannot know what to do with it. It also returns empty list if no new lines have been added and `None` if something wrong happened.

However I could modify `update` (and possibly `create`) in `SimpleService` to add dimension data validator. Since there is already a `for` loop iterating other dimensions:
```py
                for dim in self.definitions[chart]['lines']:
                    try:
                        self.set(dim[0], data[dim[0]])
                    except KeyError:
                        pass
```
But it will probably slow every module and add something relevant to just one (I think it is not needed in `UrlService` or others, apart from `LogService`).
Of course I could reimplement `create` and `update` in `LogService` to add validator only for `LogService`. But I don't know if this is the correct approach.

Last thing:
> Keep in mind though that gaps should be present for values not collected

I don't think this is relevant for `LogService` since it will have plenty of not collected values, so it should have plenty of gaps, but we don't want this.

**Comment by paulfantom** [comment]
If I recall correctly gap in dimension will be shown if `_get_data` doesn't return this dimension in its return dictionary.
On `apache_cache` example: if `_get_data` returns:
```py
{'miss': 2,
 'other': 5}
```
there will be a gap in `hit` dimension. So I don't need to implement anything, it is already implemented (I think).

**Comment by paulfantom** [comment]
Example of module with `incremental` and `absolute` dimension types:

```py
class Service(LogService):
    def __init__(self, configuration=None, name=None):
        LogService.__init__(self, configuration=configuration, name=name)
        if len(self.log_path) == 0:
            self.log_path = "/var/log/some_log_file.log"
        self.order = ORDER
        self.definitions = CHARTS
        self._default = {'ab' : 0, 'inc': None}

    def _get_data(self):
        try:
            raw = self._get_raw_data()
            if raw is None:
                return None
            elif len(raw) == 0:  # or: elif not raw:
                return self.default
        except (ValueError, AttributeError):
            return None

        ab = 0
        inc = 0
        for line in raw:
            if "some_absolute_val" in line:
                ab += 1
            elif ""some_incremental_val" in line:
                inc += 1

        self.default['inc'] = inc

        return {'ab': ab,
                'inc': inc}
```

It should work as expected.

**Comment by ktsaou** [comment]
ok. nice, This is more-or-less what I have done too.

Regarding gaps and your example where `hit` is missing, I think it would be proper to also support this:

```python
{'hit': None,
 'miss': 2,
 'other': 5}
```

So, setting the variables to `None` before collecting the data, and returning this `None` will prevent the plugin from sending a value to netdata, thus resulting in a gap.

Probably this works already.

**Comment by paulfantom** [comment]
If dimension value is set to type which cannot be converted to int, it will print error using this line:
`self.error("cannot set non-numeric value:", value)`.
So if you set it to `None`, or some non-numeric string it won't be updated, thus there will be a gap.

It is already implemented.
