### ISSUE TITLE
Can't have multiple server.

### ISSUE THREAD

**Issue by tchoblond59** [firehol/netdata#726]
Hello !

I try to run the example tv.html on my own server but i got some problems.
I have server A running as the registry and server B as the client. Both of them works great nut when i ty to access Tv.html i have an error in the console saying : "A wildcard  '*' cannot be used in the 'Access-control-allow-origin header.

What can i do ??

Thanks for all your work ;)

**Comment by ktsaou** [comment]
which web browser and version?
are you using the latest netdata?

**Comment by tchoblond59** [comment]
I'am running Chrome 52.0.2743.82 m  latest i think...
I have the same issue on firefox latest.
Maybe i did something wrong but i dont know what...
My servers are running Debian 8 for the registry one and Debian 7 for the client...
I follow the wiki for config file...

**Comment by ktsaou** [comment]
hm... strange... I use the same browser in fedora 24 without issues.
I guess there must be a browser extension that does this.
Can you disable all browser extensions and test again?

**Comment by tchoblond59** [comment]
I try on internet explorer and i have no extension on it...
Same error i guess. The error is follow by 
    ERROR 404: Chart not found: /api/v1/chart?chart=system.cpu
But if i try to access directly to server B 192.168.105.20:19999/api/v1/chart?chart=system.cpu I have something in JSON...

**Comment by ktsaou** [comment]
Please do these:

1. go to `/tv.html`
2. press F12 to open the console on your browser.
3. In the "Network" tab you will see the requests it does.
4. Find a request that goes to netdata.firehol.org (you can add the "Domain" column to find that)
5. Click on its URL, to see detail about it.
6. Give me a copy of the Request and the Response Headers

Netdata will not respond with `*` if it get the `Origin: ` HTTP header.
For some reason, it seems that your browsers do not send this header, or a proxy you use strips it before sending it to netdata.

Do you use a proxy?

**Comment by tchoblond59** [comment]
The `tv.html` works fine without any modification. But when i change the host of the left column graph i had the error... I just run a new VM with latest debian and netdata and it works in tv.html... 
I did exactly the same as other host... Maybe config problem. 
You can solve the issue, sorry.

**Comment by matejvelikonja** [comment]
If someone else encounters similar issue:
I forgot to add `http://` in front of domain. After adding it, the problem was gone.
