### ISSUE TITLE
nfs file system name not being displayed properly

### ISSUE THREAD

**Issue by abdulirfan3** [firehol/netdata#727]
Hello,

I have a unusual file system(AWS EFS) that i am mounting on one of my server where netdata is installted...here is the output of df

ip-10-0-6-76:/var/netdata# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/xvda1             40G  5.3G   34G  14% /
none                  7.5G     0  7.5G   0% /dev/shm
/dev/mapper/vg00-lvol1
                      4.8G   21M  4.6G   1% /tmp
/dev/mapper/vg00-lvol2
                      4.8G   11M  4.6G   1% /home
/dev/mapper/vg00-lvol3
                      4.8G  652M  4.0G  15% /var
us-east-1d.fs-9108ccd8.efs.us-east-1.amazonaws.com:/
                      8.0E     0  8.0E   0% /efs
ip-10-0-6-76:/var/netdata#

but in netdata "/efs" is not showing up...i have tried to stop and start netdata but still nothing being showed....i have other NFS servers where a user managed NFS is mounted on the client and they all show up....

![image](https://cloud.githubusercontent.com/assets/11415069/17116612/3efaa2a2-527e-11e6-9e32-300860622829.png)

**Comment by ktsaou** [comment]
You are right. The current version of netdata shows only information about disks which have a block devices on this linux.

@simonnagl was planning to split that logic and present information about all mounted disks.

@simonnagl do you want me to finish it? We also have PR #430 hanging around.

**Comment by simonnagl** [comment]
Hello @ktsaou, sorry for my long time off. Please finish all my open things if you like. At the moment I have some private projects which need more time a day has.
I may be come back and help you out with some other issues when things changes. Thank you for that amazing project!

**Comment by ktsaou** [comment]
@simonnagl ok, I'll take care. Thank you very much for you contributions so far and I hope to have you back soon.

**Comment by abdulirfan3** [comment]
@ktsaou 

just checking to see if there is any update on this ?

**Comment by ktsaou** [comment]
The code is almost there. But it needs some more work.
I am trying to finalize alarms these days. If everything goes well, I'll try to work on this before the end of the month.

**Comment by ktsaou** [comment]
I believe this has been fixed with #1146 
Can you check?

**Comment by ktsaou** [comment]
I am closing this. It should be fixed. If it does not work for you, please post.
