### ISSUE TITLE
ERROR 410: Netdata registry ACCESS failed: (null)

### ISSUE THREAD

**Issue by morlix** [firehol/netdata#731]
Hello,

i have installed netdata 1.2.0 on two of my gentoo machines and on both of them the registry isn't working with the following error in the browser console:

![image](https://cloud.githubusercontent.com/assets/283996/17173082/ef7e423e-53f8-11e6-87e0-96122f6d514f.png)

**Comment by ktsaou** [comment]
Can you try the git version. This is already supported in gentoo.

**Comment by morlix** [comment]
This is fixed in the git version.

**Comment by paulfantom** [comment]
@ktsaou do you think we should release 1.3 some time soon?

**Comment by ktsaou** [comment]
I hope in the next 1-2 weeks I will release it.
