### ISSUE TITLE
User and password authentications

### ISSUE THREAD

**Issue by ferztyle** [firehol/netdata#732]
Hi!, is there an opcion for setting a user and password for the statistics page? thanks for advance!

**Comment by paulfantom** [comment]
Currently netdata doesn't support user authentication (look at #70). For authentication I suggest  using nginx in front of netdata with basic HTTP auth ([here is netdata wiki page for it](https://github.com/firehol/netdata/wiki/Running-behind-nginx#enable-authentication)).

**Comment by ferztyle** [comment]
Ok but what happens if i want to install in hundreds of servers? i have to install a web server for every server too?

**Comment by paulfantom** [comment]
I am sorry but currently, if you want authentication for every one of those hundreds of servers I don't think there is any other option (without knowing anything about your infrastructure).

Netdata will add authentication some time in the future, but it is a little bit more complicated, and there are different priorities right now (look at #436).

**Comment by ferztyle** [comment]
Ok, thanks fot you help and congrats for this amazing project..

**Comment by ktsaou** [comment]
@ferztyle if your servers are on one site and you have a DMZ, you can install one nginx to pass through all your netdata servers.
