### ISSUE TITLE
netdata fail to install 

### ISSUE THREAD

**Issue by Djacke** [firehol/netdata#736]
Sorry, you do not seem to have autotools 2.60 or later, which is
required to build from the git sources of netdata.

You can either install a suitable version of autotools and automake
or download a netdata package which does not have these dependencies.

Source packages where autotools have already been run are available
here:
   https://firehol.org/download/netdata/

The unsigned/master folder tracks the head of the git tree and released
packages are also available.

**Comment by ktsaou** [comment]
Which distribution you use?

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
