### ISSUE TITLE
Support for Dovecot?

### ISSUE THREAD

**Issue by ragnar76** [firehol/netdata#737]
Is there any chance to get support for dovecot? it has doveadm which displays who is connected to the server so it would be very easy to count how many users are connected. It looks like this:

```
root@mail:~# doveadm who
username          	# 	proto 	(pids)                          (ips)
xxx@testdomain.lcl 1 	imap  	(9130)                          (xxx.xxx.xxx.xxx)
asd@testdomain.lcl 2 	imap  	(18022 6938)                    (xxx.xxx.xxx.xxx)
qwe@testdomain.lcl 1 	imap  	(15627)                         (xxx.xxx.xxx.xxx)
xyz@testdomain.lcl 5 	imap  	(28624 28297 17563 32263 18488) (xxx.xxx.xxx.xxx)
```
cheers

**Comment by paulfantom** [comment]
@ragnar76 you want to have only one chart with number of users connected to dovecot? Or maybe you know what else can (and should) be monitored in this program?

**Comment by ragnar76** [comment]
Dovecot also has

> doveadm status top

But it was not working in my machines so i didnt mention it. Cannot say nothing more about it :(

**Comment by paulfantom** [comment]
Can `doveadm who` be executed by user netdata?

**Comment by paulfantom** [comment]
Basically you want to  count lines or sum numbers in second column? 

I have never used dovecot thus I am asking.

**Comment by paulfantom** [comment]
Ok, here is an example of `dovecot.chart.py`:
```py
from base import ExecutableService

priority = 60000
retries = 60

ORDER = ['users']
CHARTS = {
    'users': {
        'options': [None, "Dovecot connected users", "users", 'queue', 'dovecot.users', 'line'],
        'lines': [
            ['users', None, 'absolute']
        ]}
}

class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.command = "dovecot who"
        self.order = ORDER
        self.definitions = CHARTS

    def _get_data(self):
        try:
            raw = self._get_raw_data()[1:]
        except (ValueError, AttributeError):
            return None
        # sum second column
        count = 0
        for line in raw:
            count += int(line.split(' ')[1])
        # count lines:
        # count = len(raw)

        return {'users': count}
```

In this version it sums second column and shows it on chart. If you want to count lines just comment out:
```py
        # sum second column
        count = 0
        for line in raw:
            count += int(line.split(' ')[1])
```
and uncomment:
```py
# count = len(raw)
```

**Comment by ragnar76** [comment]
Will try it tonight

**Comment by paulfantom** [comment]
I read more about `dovecot who` and added new line `sessions`. Now script looks like this:
```py
from base import ExecutableService

priority = 60000
retries = 60

ORDER = ['users']
CHARTS = {
    'users': {
        'options': [None, "Dovecot connected users", "no.", 'users', 'dovecot.users', 'line'],
        'lines': [
            ['users', None, 'absolute'],
            ['sessions', None, 'absolute']
        ]}
}

class Service(ExecutableService):
    def __init__(self, configuration=None, name=None):
        ExecutableService.__init__(self, configuration=configuration, name=name)
        self.command = "dovecot who"
        self.order = ORDER
        self.definitions = CHARTS

    def _get_data(self):
        try:
            raw = self._get_raw_data()[1:]
        except (ValueError, AttributeError):
            return None
        # count lines:
        users = len(raw)
        # sum second column
        sessions = 0
        for line in raw:
            sessions += int(line.split(' ')[1])


        return {'users': users,
                'sessions': sessions}
```

**Comment by paulfantom** [comment]
@ragnar76 did you test it?

**Comment by ragnar76** [comment]
Not yet. My newborn needs a bit attetion. Will tty it AG work tomorrow

**Comment by paulfantom** [comment]
Ok, no rush, newborn is definitely more important :smile:

**Comment by ragnar76** [comment]
hm, using a tablet computer with german autocorrection is not good in english :D however. i've put the second script into /usr/libexec/netdata/python.d but nothing happens. when i run doveadm as an regular user i get an error message with:

doveadm(ragnar): Fatal: net_connect_unix(/var/run/dovecot/anvil) failed: Permission denied

will try to make it run as another user

**Comment by ragnar76** [comment]
okay, using the 1st script and change the file persmissions from 0600 to 0606 made it. it runs but i cannot say anything about security flaws now

**Comment by ktsaou** [comment]
running `strace doveadm who` reveals:

```
connect(8, {sa_family=AF_LOCAL, sun_path="/var/run/dovecot/anvil"}, 110) = 0
fcntl(8, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(8, F_SETFL, O_RDWR)               = 0
write(8, "VERSION\tanvil\t1\t0\nCONNECT-DUMP\n", 31) = 31
fstat(8, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
read(8, "\n", 8192)                     = 1
close(8)                                = 0
```

It is very simple text I/O.

However, the permissions are very strict. I think it can only be done with a setuid to root program.

**Comment by paulfantom** [comment]
I think that this approach is wrong.
Dovecot has [statistics interface](http://wiki2.dovecot.org/Statistics) which is by default on port 24242. I will rewrite this module to grab data from this interface.

**Comment by paulfantom** [comment]
I have rewritten dovecot module. Currently it is located in [my repository](https://github.com/paulfantom/netdata). 
Also remember that user netdata needs `rw` permissions to dovecot stats socket.

**Comment by paulfantom** [comment]
Some clarification:
- statistics interface it isn't by default on port 24242, default is a unix socket named `stats` located in `/var/run/dovecot` (at least on debian)
- stats unix socket doesn't have write permission for anyone else than root. To gain access by netdata, `sudo chmod a+w /var/run/dovecot/stats` should be run (or some other way to give write access to user netdata, for example ACLs).
- I have run some basic tests and created simple module in #762

**Comment by ragnar76** [comment]
I'm on vacation. will test it when i'm back
