### ISSUE TITLE
Error log spam due to memory cgroup not being mounted by default

### ISSUE THREAD

**Issue by lhw** [firehol/netdata#749]
By default the memory cgroup is not mounted on debian. But the netdata daemon assumes a location and tries accessing the memory.stat on every check. This results in a massive error log spam when the netdata daemon runs. About 15k lines or 3MB a day.

I think a short check if the cgroup mounts exists before accessing the files lower in the tree should be the easiest solution right now.

**Comment by ktsaou** [comment]
Can you give me a few of the log lines? I see it should not attempt to read memory files if they do not exist. So, I have missed this condition somewhere.

**Comment by lhw** [comment]
```
16-08-01 15:18:02: ERROR: netdata: PROCFILE: Cannot open file '/sys/fs/cgroup/memory/docker/a9f269f2bd304651d21459f0439ab719c58265c9b16a777c5d7cdbe79d108b58/memory.stat' (errno 2, No such file or directory)
16-08-01 15:18:02: ERROR: netdata: PROCFILE: Cannot open file '/sys/fs/cgroup/memory/docker/bc78a94726290b1c8dec3670e4302811c596318a9c32ad2ab1bd72f8b617c252/memory.stat' (errno 2, No such file or directory)
16-08-01 15:18:04: netdata: Too many logs (201 logs in 101 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1099 seconds.
```
The check logs every missing container memory.stat every 2 secs until the logger stops for the 1200 seconds.

**Comment by ktsaou** [comment]
I have made a patch in my fork (`https://github/ktsaou/netdata`) where this is solved.
Could you please test it before merging it?

**Comment by lhw** [comment]
Thank you for the quick patch. I'll test it in a bit and report back on the log handling. It was just a bit excessive even with logrotate compressing the old ones it was hard to find actual log entries.

**Comment by lhw** [comment]
Patched it up a little to work with the stable release. Looks good to me so far. I'll let it run for now and see what happens over time.

**Comment by ktsaou** [comment]
ok merged it. If you find something let me know.
