### ISSUE TITLE
Unsupported type Counter64 in node.js SNMP plugin

### ISSUE THREAD

**Issue by Dragonn** [firehol/netdata#75]
Javascript NET-SNMP library doesn't support Counter64 data type directly and returns byte array.

I don't use javascript, but I tried to fix it manually. Please revise and test attached patch file [0001-Fixed-SNMP-type-Counter64.patch.txt](https://github.com/firehol/netdata/files/195876/0001-Fixed-SNMP-type-Counter64.patch.txt) and consider merging into master :o)

**Comment by ktsaou** [comment]
Interesting!
Probably, a better way could be to use https://github.com/broofa/node-int64 to pass the 64 bit values to the netdata server.
I'll have a look during the weekend.

**Comment by ktsaou** [comment]
ok, I added int64 support at `node.d.plugin`, so nothing is needed in the snmp plugin.
Can you test it please?

**Comment by k0ldbl00d** [comment]
Is there any way to get Counter64 value represented as string?
