### ISSUE TITLE
Memcached support

### ISSUE THREAD

**Issue by LucaDev** [firehol/netdata#751]
I'd love to see an memcached support showing stats like hit/miss rate, current connections, cache size and so on. I found this python module which could be modified and used: https://github.com/dlrust/python-memcached-stats

**Comment by paulfantom** [comment]
@LucaDev could you test [memcached module](https://github.com/paulfantom/netdata/blob/master/python.d/memcached.chart.py) for netdata from [my repository](https://github.com/paulfantom/netdata)?

**Comment by LucaDev** [comment]
Yeah, it runs perfectly! Thank you very much!

**Comment by LucaDev** [comment]
I think memcached_local.net should be removed because written bytes gets very high. It raised to 6,4 billions in like 4 hours or so

**Comment by paulfantom** [comment]
`memcached_local.net` will be changed to `incremental` instead of `absolute`. So it won't show such data. Future changes are in [my repo](https://github.com/paulfantom/netdata)

**Comment by LucaDev** [comment]
Thanks :) :+1:
