### ISSUE TITLE
Virtual Machines reported as containers

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#753]
I found that while using KVM with qemu, netdata treats VMs as containers.

Example lines from log:
```
/usr/lib/netdata/plugins.d/cgroup-name.sh: cgroup 'machine.slice/machine-qemu\x2dcentos7.0.scope/vcpu1' is called 'machine.slice/machine-qemu\x2dcentos7.0.scope/vcpu'
INFO: netdata: executing command: 'exec /usr/lib/netdata/plugins.d/cgroup-name.sh 'machine.slice/machine-qemu\x2dcentos7.0.scope/emulator'' on pid 16237.

```
System:
openSUSE Leap 42.1

**Comment by ktsaou** [comment]
Does it show it on the dashboard?

Unfortunately netdata has to call `cgroup-name.sh` for every cgroup found in a system. The reason is docker: docker gives random IDs to cgroups. So, to have consistent configuration in netdata (to enable/disable cgroups), netdata uses the name of cgroups which is obtained by calling `cgroup-name.sh`, **before** checking if it is enabled or not. Thus, this script is called for every cgroup.

So, does it appear in the dashboard?

**Comment by paulfantom** [comment]
Yes it does.
![vm](https://cloud.githubusercontent.com/assets/3531758/17344257/c016ea38-5901-11e6-8e25-f445df156489.jpeg)

**Comment by ktsaou** [comment]
I am still trying to figure out if this is good or bad...

What do you think? Is this something we would like to have or prevent by default?

**Comment by paulfantom** [comment]
I think it is good that they are displayed, but they should be displayed as VMs, not containers.

**Comment by ktsaou** [comment]
I think we can differentiate based only on string matching. i.e. `machine.slice` or `machine-qemu`. I don't like it though.

**Comment by paulfantom** [comment]
I don't think there is any other way. Also netdata cannot search for `machine-qemu` but only for `qemu` since on non-systemd OSes, this cgroup has different naming schema.

**Comment by ovizii** [comment]
I am also seeing KVMs as containers but in the dashboard KVMs only show CPU stats while containers also show memory and disk stats.

**Comment by ktsaou** [comment]
> KVMs only show CPU stats while containers also show memory and disk stats.

This depends on the information exposed by the kernel in cgroups. netdata does not filter this information.

**Comment by leleobhz** [comment]
+1 affected. Same issue reported here and by @ovizii 

There is no way to create a special case for QEMU/KVM?

**Comment by ktsaou** [comment]
ok, I added in PR #775 a fix for that. It will be reported as VM. But please check it and report back success or failure (a screenshot is best).

To test it, clone my repo and checkout the `health` branch.

**Comment by ktsaou** [comment]
merged the fix
