### ISSUE TITLE
cannot get hddtemp data

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#754]
First off, I am running inside a docker container via titpetric/netdata. I am trying to figure out what I need to pass through to the container to get this information. When I grep hddtemp in the logs, I get:
```
charts.d: 'hddtemp' is NOT enabled. Add a line with hddtemp=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
python.d INFO: hddtemp_localipv4 No excluded disks
python.d ERROR: hddtemp_localipv4 no data received
python.d ERROR: hddtemp_localipv4 check function failed.
python.d INFO: Disabled hddtemp/localipv4
python.d INFO: hddtemp_localipv6 No excluded disks
python.d ERROR: hddtemp_localipv6 no data received
python.d ERROR: hddtemp_localipv6 check function failed.
python.d INFO: Disabled hddtemp/localipv6
python.d INFO: hddtemp_localhost No excluded disks
python.d ERROR: hddtemp_localhost no data received
python.d ERROR: hddtemp_localhost check function failed.
python.d INFO: Disabled hddtemp/localhost
```

**Comment by paulfantom** [comment]
do you have `hddtemp` daemon running and cab netdata access it on `localhost:7634`?

**Comment by kmlucy** [comment]
When I have hddtemp daemon running, and the container using host networking, I get:
```
charts.d: 'hddtemp' is NOT enabled. Add a line with hddtemp=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
python.d INFO: hddtemp_localipv4 No excluded disks
python.d ERROR: hddtemp_localipv4 integer division or modulo by zero
python.d INFO: Disabled hddtemp/localipv4
python.d INFO: hddtemp_localipv6 No excluded disks
python.d ERROR: hddtemp_localipv6 integer division or modulo by zero
python.d INFO: Disabled hddtemp/localipv6
python.d INFO: hddtemp_localhost No excluded disks
python.d ERROR: hddtemp_localhost integer division or modulo by zero
python.d INFO: Disabled hddtemp/localhost
```

**Comment by paulfantom** [comment]
```
ERROR: hddtemp_localhost integer division or modulo by zero
```
It looks like `hddtemp.chart.py` cannot find any drives. This is probably because module searches `/dev` directory for files starting with `sd` (line 46 of `hddtemp.chart.py`).
It should be changed to something more flexible, but I didn't have any ideas at that time.

Temporary fix would be to change line 68:
```py
self.disk_count = self._get_disk_count()
```
to  something like this:
```py
self.disk_count = 2 
```
Where `2` is you disk count.

**Comment by kmlucy** [comment]
Can I set that from the hddtemp.conf file? Or would I have to modify the hddtemp.chart.py file?

**Comment by paulfantom** [comment]
I have enabled a possibility to override autodetection of number of disks by setting `disk_count` variable in `hddtemp.conf`. Here is [my repo](https://github.com/paulfantom/netdata), if you are willing to test it.

**Comment by l2isbad** [comment]
`python.d.plugin` has [debug mode](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by adrfantini** [comment]
@l2isbad  Thanks, I'll open a new issue with the data collected.
