### ISSUE TITLE
How do i add my own plugin?

### ISSUE THREAD

**Issue by davidak** [firehol/netdata#755]
I already create this with the help of [the documentation](https://github.com/firehol/netdata/wiki/External-Plugins):

https://davidak.basecom.de/paste/?5586fed69607c654#GHIXDSXx4H2vxTBeoylAO4qpU2zo1Nk7uXgU6CbNxqs=

put it in `/etc/netdata/charts.d/` or `/usr/libexec/netdata/charts.d/` as **ipfs.charts.sh**

and put `ipfs=yes` in `/etc/netdata/charts.d.conf`

but it don't appear in the webui :(

**Comment by ktsaou** [comment]
@davidak install it in `/usr/libexec/netdata/charts.d` as you propose and then run:

```sh
# /usr/libexec/netdata/plugins/charts.d.plugin debug 1 ipfs
```

It should tell you what is wrong with it.

**Comment by davidak** [comment]
```
# ll /usr/libexec/netdata/charts.d/ipfs.charts.sh
-rwxr-xr-x 1 root root 468 Aug  2 14:00 /usr/libexec/netdata/charts.d/ipfs.charts.sh*
# /usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 ipfs
charts.d: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 1 ipfs
Cannot understand parameter ipfs. Aborting.
DISABLE
```

**Comment by paulfantom** [comment]
> /usr/libexec/netdata/charts.d/ipfs.charts.sh

It is not a valid filename. Should be:
`ipfs.chart.sh`

**Comment by davidak** [comment]
thanks, that was one problem.

```
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 ipfs
[...]
charts.d: activated charts:  ipfs
charts.d: requested to run only for: 'ipfs'
charts.d: activated charts: ipfs
charts.d: Calling 'ipfs_create()'...
CHART ipfs.peers '' "IPFS Peers" "peers"
DIMENSION peers '' absolute 1 1
charts.d: 'ipfs' has initialized.
charts.d: run_charts=' ipfs'
CHART netdata.plugin_chartsd_ipfs '' 'Execution time for ipfs plugin' 'milliseconds / run' charts.d netdata.plugin_charts area 145000 1
DIMENSION run_time 'run time' absolute 1 1
charts.d: sleeping for 0.409 seconds.
BEGIN ipfs.peers
SET peers = 223
END
BEGIN netdata.plugin_chartsd_ipfs
SET run_time = 293
END
charts.d: sleeping for 0.699 seconds.
BEGIN ipfs.peers
SET peers = 223
END
BEGIN netdata.plugin_chartsd_ipfs 1001000
SET run_time = 68
END
charts.d: sleeping for 0.923 seconds.
```

after i restarted netdata i see the chart, but it don't get the data. the issue is that it has to be executed as root. i'm not sure if sudo would help. do you have a solution?

**Comment by ktsaou** [comment]
You have 3 options:

1. Configure `sudo`  via `/etc/sudoers` to allow user `netdata` run `ipfs` as `root`.
2. Put the ipfs command in a cron job to save its output once per minute to a file in a tmpfs filesystem and make your plugin use that file as source (of course, you will get 1/min chart).
3. Run netdata as root.

I would go for 1, like this:

Create the file `/etc/sudoers.d/netdata` with this content:

```
netdata ALL = NOPASSWD: /path/to/ipfs
```

Then netdata will be able to `sudo ipfs` without password.

To test it create a netdata shell with this: `su netdata --shell /bin/bash` and run `sudo -n ipfs` as netdata. It should not ask for password.

Modify your plugin to call `sudo -n ipfs`. Make sure you add `-n`. It states that if sudo requires the user to enter a password, it will just fail.

**Comment by davidak** [comment]
I tried 1. like you see in my last codeblock of my last comment. ipfs don't find it's config in `/root/.ipfs` and i'm not allowed to `sudo cd /root`.

But there is an environment variable `IPFS_PATH` to set the ipfs repository location. (i just found out :))

so i need in sudoers:

```
netdata ALL=NOPASSWD:SETENV: /usr/local/bin/ipfs
```

And execute the command in the plugin with

```
sudo IPFS_PATH=/root/.ipfs $ipfs swarm peers 2>/dev/null | wc -l
```

![bildschirmfoto 2016-08-04 um 13 21 16](https://cloud.githubusercontent.com/assets/91113/17400118/6e005ea0-5a46-11e6-9a8a-36ff8f81d9d4.png)

should i recreate that in python and create a PR? (would it really make a difference here?)

**Comment by paulfantom** [comment]
There is a 4th way: use [ipfs API](https://ipfs.io/docs/api/). This:
```
curl http://127.0.0.1:5001/api/v0/swarm/peers
```
should give you same (or similar) data as `ipfs swarm peers`.

**Comment by davidak** [comment]
@paulfantom thanks!

I'm not sure what needs less resources, open a tcp connection or execute a binary. maybe the first? @ktsaou

**Comment by paulfantom** [comment]
@davidak if you want speed, here is python version of your script using ipfs API:
```py
# -*- coding: utf-8 -*-
# Description: IPFS netdata python.d module
# Author: Pawel Krupa (paulfantom)

from base import UrlService
import json

# default module values (can be overridden per job in `config`)
# update_every = 2
priority = 60000
retries = 60

# default job configuration (overridden by python.d.plugin)
# config = {'local': {
#     'update_every': update_every,
#     'retries': retries,
#     'priority': priority,
#     'url': 'http://localhost:5001/api/v0/swarm/peers'
# }}

# charts order (can be overridden if you want less charts, or different order)
ORDER = ['peers']

CHARTS = {
    'peers': {
        'options': [None, 'IPFS Peers', 'peers', 'Peers', 'ipfs.peers', 'line'],
        'lines': [
            ["peers", None, 'absolute']
        ]}
}


class Service(UrlService):
    def __init__(self, configuration=None, name=None):
        UrlService.__init__(self, configuration=configuration, name=name)
        if len(self.url) == 0:
            self.url = "http://localhost:5001/api/v0/swarm/peers"
        self.order = ORDER
        self.definitions = CHARTS

    def _get_data(self):
        """
        Format data received from http request
        :return: dict
        """
        try:
            raw = self._get_raw_data()
        except AttributeError:
            return None

        try:
            parsed = json.loads(raw)
            peers = len(parsed['Strings'])
        except:
            return None

        return {'peers': peers}
```

**Comment by ktsaou** [comment]
@paulfantom you are the best!
