### ISSUE TITLE
IP/Port config regression

### ISSUE THREAD

**Issue by dgw** [firehol/netdata#756]
After not updating netdata for a month or so, I came back and updated all my instances with a script. Suddenly, all four servers started showing a Bad Gateway error (I reverse-proxy through nginx).

Digging through, I discovered that netdata was once again binding to the default port.

Testing various revisions with `git bisect` got me to d052989, which apparently changed the configuration setting names. I see there is code in there as well to rename the settings to the new names, but it doesn't appear to work.

I'm labeling this as a regression in the IP/Port configuration, but it is probably a bug in the `config_rename()` function.

**Comment by ktsaou** [comment]
Thanks for reporting this! Rename was working but the index had a wrong hash. Fixed it.
Sorry for the incovinience.

**Comment by dgw** [comment]
No problem! Glad to have been able to pin it down to a specific commit for you. Thanks for the absurdly fast turnaround.
