### ISSUE TITLE
add option to disable the internal webserver

### ISSUE THREAD

**Issue by LucaDev** [firehol/netdata#758]
I'd love to see an option to disable the internal webserver for users who want so serve their static netdata files with an nginx or similar webserver

**Comment by ktsaou** [comment]
You can make netdata listen on `localhost` and proxy it via an nginx, apache, lighttpd, etc, and you can add user authentication in this case.

The internal web server is used primarily for the API that serves the chart data. Without it, netdata will have to be a CGI of some kind.

The internal web server serves netdata's static content (with many restrictions - files owned by specific user, files owned by specific group, files in a specific directory, etc) just to ease the setup for most users.

Why do you need this?

**Comment by LucaDev** [comment]
It just seems a bit redundant to me to have two Webservers in row. Btw I'm currently using nginx as an reverse proxy.

**Comment by ktsaou** [comment]
Let's say that we do this and disable the netdata internal webserver. How do you expect it to work? I mean, how do you believe the chart data should be served to your web browser?

**Comment by LucaDev** [comment]
Something like an standalone socket would be needed. How is it done at the moment?

**Comment by ktsaou** [comment]
So you would like your web browser to talk to a standalone socket that is not HTTP? Why?

The difference between a "standalone socket" and a "web server" is the HTTP protocol, i.e. the standard that allows us to describe requests and replies exchanged via sockets.

Sorry, but I cannot understand what you propose. I don't see any benefits in replacing HTTP with a custom protocol (and sockets need a protocol, we cannot avoid it).

**Comment by LucaDev** [comment]
Forget about it. It was an stupid idea. It could save some resources but the impact would be so minimal and the effort to implement this would be huge - so it's really not worth it
