### ISSUE TITLE
Installer fails with unrecognized command line option '-qversion'

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#759]
I'm on Ubuntu 14.04 and all libraries are installed and all components are updated to the latest releases. I always update netdata via git using the latest code (master) and then run netdata-installer.sh

This morning this is failing and the error in config.log reads like this:

```
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
configure:3334: $? = 0
configure:3323: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3334: $? = 4
configure:3323: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3334: $? = 4
configure:3354: checking whether the C compiler works
configure:3376: gcc -O3   conftest.c  >&5
Traceback (most recent call last):
  File "/usr/local/bin/as", line 19, in <module>
    general.run(parser, general.find_script(True))
  File "/opt/ansible/lib/general.py", line 33, in find_script
    return importlib.import_module('.' + scriptname, package='scripts')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Import by filename is not supported.
configure:3380: $? = 1
configure:3418: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "netdata"
| #define PACKAGE_TARNAME "netdata"
| #define PACKAGE_VERSION "1.2.1_master"
| #define PACKAGE_STRING "netdata 1.2.1_master"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "netdata"
| #define VERSION "1.2.1_master"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3423: error: in `/opt/netdata':
configure:3425: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by ktsaou** [comment]
I just installed it on ubuntu 14.04 LTS without any issues.
I think the whole point is this error: `configure:3425: error: C compiler cannot create executables`. For some reason your gcc is faulty or corrupted.

**Comment by jurgenhaas** [comment]
Well it worked exactly the same way since the advent of netdata and the hosts are locked down. Only thing being installed or updated regularely are system or component updates from official sources.

**Comment by ktsaou** [comment]
What is `/usr/local/bin/as` ?
`as` is the assembler, part of gcc. It seems your `/usr/local/bin/as` is a python script.

Can you post your `$PATH` variable?

One solution could be to run it as follows:

```sh
PATH="/bin:/sbin:/usr/bin:/usr/sbin" ./netdata-installer.sh
```

This makes sure the system paths are first.

**Comment by jurgenhaas** [comment]
Oh dear, that was a symbolic link to an Ansible script. Sorry for the confusion, that was obviously a local mistake.
