### ISSUE TITLE
packages installer failed on Cloudlinux

### ISSUE THREAD

**Issue by columbusgeek** [firehol/netdata#760]
The experimental packages installer failed.

This is what it says:

http://prntscr.com/c22vd8

I get this error on my CloudLinux machines.  So far no issues on my small machines.  this is an amazing system.  I'm happy I found it.  :)

**Comment by ktsaou** [comment]
Hi, can you help me support your distribution?

I will need the first few lines printed by the packages installer, to understand what it detected on your system.

The key problem is that it cannot install `git` and `autogen`. Can you find the packages that should be installed to get these two?

**Comment by columbusgeek** [comment]
Yep.  For some reason CloudLinux doesnt have a few things ready to go on it.  "autoconf-archive" and "in one case MySQL-python".
I was able to get "autogen" installed by using 

yum --enablerepo=epel-testing install autogen

I already have autoconf-archive installed as far as I can tell
package autoconf-2.63-5.1.el6.noarch is already installed

At this point I am a bit out of my depth I fear.

**Comment by ktsaou** [comment]
If you manage to install `git` you will be able to install netdata.
Alternativerly, you can download a zip from github (check the project's home), unzip it and run `./netdata-installer.sh`.

**Comment by ktsaou** [comment]
Did you solve it?

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
