### ISSUE TITLE
I have a question about the custom dashboard.

### ISSUE THREAD

**Issue by sohwaje** [firehol/netdata#766]
I have created a new my custom dashboard.
But This dashboard did not display the number of graph. 
See below two graph. One graph is Apache Web Server. Others graph is Tomcat Server. 
The latter is cannot view the number of graph.
![graph](https://cloud.githubusercontent.com/assets/19942049/17513279/072092c0-5e67-11e6-833f-c94b70b9d1cc.JPG)

**Comment by sohwaje** [comment]
[custom_dashboard.txt](https://github.com/firehol/netdata/files/408718/custom_dashboard.txt)

**Comment by ktsaou** [comment]
The second chart is referring the id of the first `tomcat_tomcat1.accesses.netdata`. Make sure everything in the second chart is using `tomcat2`.

**Comment by ktsaou** [comment]
You have the problem in apache too.

**Comment by ktsaou** [comment]
Keep in mind the chart you are using is a synthetic chart defined in this dashboard (it is not a standard one managed by netdata itself). So, pay some attention to the ids linked to each chart.

**Comment by sohwaje** [comment]
1.The second chart is referring the id of the first tomcat_tomcat1.accesses.netdata. Make sure everything in the second chart is using tomcat2.
-> I fixed it chart of tomcat2. 
<div role="tabpanel" class="tab-pane" id="tomcat2_requests">
                                        <div class="mysparkline">
                                                <div class="mysparkline-overchart-label">
                                                        <b>melete.kr</b>  tomcat2 accesses
                                                </div>
                                                <div class="mysparkline-overchart-value" id="tomcat_tomcat2.accesses.netdata" >
                                                </div>
                                                <div data-netdata="tomcat_tomcat2.accesses"
                                                                data-dimensions="accesses"
                                                                data-host=""
                                                                data-chart-library="dygraph"
                                                                data-dygraph-theme="sparkline"
                                                                data-dygraph-type="area"
                                                                data-width="100%"
                                                                data-height="100%"
                                                                data-after="-300"
                                                                data-colors="#5555AA"
                                                                data-show-value-of-requests-at="tomcat_tomcat2.accesses.netdata"
                                                                >
                                                </div>
                                        </div>

**Comment by ktsaou** [comment]
nice.

To properly show the number in the tomcat charts you have to change `data-show-value-of-requests-at` to `data-show-value-of-accesses-at`.

**Comment by ktsaou** [comment]
`accesses` is the name of the dimension to render its value as number on top of the chart.
