### ISSUE TITLE
python plugin takes long time to start collecting data and throws errors

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#772]
@paulfantom check this:

```
python.d ERROR: postfix_local Something wrong:  [Errno 32] Broken pipe
python.d FATAL: no more jobs
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 521, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 409, in update
    msg.fatal("no more jobs")
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 50, in fatal
    sys.stdout.write('DISABLE\n')
BrokenPipeError: [Errno 32] Broken pipe
```

Also, it takes a long time to start collecting data...

**Comment by ktsaou** [comment]
Using python 3.4

**Comment by ktsaou** [comment]
I notice this long delay to start in gentoo and arch. Both are using python 3.

**Comment by LucaDev** [comment]
Same on Ubuntu 16.04:
`python.d ERROR: postfix_local Something wrong:  [Errno 32] Broken pipe
python.d FATAL: no more jobs
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 521, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 409, in update
    msg.fatal("no more jobs")
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 50, in fatal
    sys.stdout.write('DISABLE\n')
IOError: [Errno 32] Broken pipe
`

**Comment by paulfantom** [comment]
Created fix in #774. Tested it on openSUSE and it appears to work. @LucaDev can you test it?

**Comment by LucaDev** [comment]
I'll try it later and tell you about the results

**Comment by LucaDev** [comment]
Jep, works perfectly

**Comment by LucaDev** [comment]
Oh, wait, it just happend again:

> python.d FATAL: no more jobs
> Traceback (most recent call last):
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 521, in <module>
>     run()
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in run
>     charts.update()
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 409, in update
>     msg.fatal("no more jobs")
>   File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 50, in fatal
>     sys.stdout.write('DISABLE\n')
> IOError: [Errno 32] Broken pipe

**Comment by paulfantom** [comment]
Ok, this is a different type of problem. Somehow stdout is closed before python writes to it. In [my repo](https://github.com/paulfantom/netdata), I [changed `sys.stdout.write` to `print`](https://github.com/paulfantom/netdata/commit/ecd55438cdf2cef9881b36137ba73a7a54383eb9) maybe it will help.

I tried to reproduce this with no success.

**Comment by paulfantom** [comment]
I think this should be fixed now in #774. I tried to reproduce this on openSUSE Leap 42.1, Fedora 24, and Ubuntu 16.04 but I didn't encounter this issue.

**Comment by ktsaou** [comment]
@paulfantom there is a 15 second timeout when checking squid:

```
16-08-20 22:45:42: python.d ERROR: squid_tcp8080oldipv6 Socket timed out.
16-08-20 22:45:42: python.d ERROR: squid_tcp8080oldipv6 no data received
16-08-20 22:45:42: python.d ERROR: squid_tcp8080oldipv6 check function failed.
16-08-20 22:45:42: python.d INFO: Disabled squid/tcp8080oldipv6

16-08-20 22:45:57: python.d ERROR: squid_tcp8080newipv4 Socket timed out.
16-08-20 22:45:57: python.d ERROR: squid_tcp8080newipv4 no data received
16-08-20 22:45:57: python.d ERROR: squid_tcp8080newipv4 check function failed.
16-08-20 22:45:57: python.d INFO: Disabled squid/tcp8080newipv4
16-08-20 22:45:57: python.d ERROR: local already exists. Stopping 'tcp3128newipv6'
16-08-20 22:45:57: python.d INFO: Disabled squid/tcp3128newipv6

16-08-20 22:46:12: python.d ERROR: squid_tcp8080new Socket timed out.
16-08-20 22:46:12: python.d ERROR: squid_tcp8080new no data received
16-08-20 22:46:12: python.d ERROR: squid_tcp8080new check function failed.
16-08-20 22:46:12: python.d INFO: Disabled squid/tcp8080new

16-08-20 22:46:27: python.d ERROR: squid_tcp8080oldipv4 Socket timed out.
16-08-20 22:46:27: python.d ERROR: squid_tcp8080oldipv4 no data received
16-08-20 22:46:27: python.d ERROR: squid_tcp8080oldipv4 check function failed.
16-08-20 22:46:27: python.d INFO: Disabled squid/tcp8080oldipv4

16-08-20 22:46:42: python.d ERROR: squid_tcp8080old Socket timed out.
16-08-20 22:46:42: python.d ERROR: squid_tcp8080old no data received
16-08-20 22:46:42: python.d ERROR: squid_tcp8080old check function failed.
16-08-20 22:46:42: python.d INFO: Disabled squid/tcp8080old
16-08-20 22:46:42: python.d ERROR: local already exists. Stopping 'tcp3128newipv4'
16-08-20 22:46:42: python.d INFO: Disabled squid/tcp3128newipv4

16-08-20 22:46:57: python.d ERROR: squid_tcp8080newipv6 Socket timed out.
16-08-20 22:46:57: python.d ERROR: squid_tcp8080newipv6 no data received
16-08-20 22:46:57: python.d ERROR: squid_tcp8080newipv6 check function failed.
16-08-20 22:46:57: python.d INFO: Disabled squid/tcp8080newipv6
```

So, the total time for checking squid is more than a minute.
I think that either we have to do these in parallel, or lower the timeout to 5 seconds.

**Comment by paulfantom** [comment]
For now I lowered timeout to 5s. Also I will try to find more permanent solution to this problem, but I doubt that it will happen soon (lack of time).
