### ISSUE TITLE
better systemd netdata.service

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#773]
@candrews @paulfantom please check this.
Do you see any compatibility issues (related to older systemd)?

```
[Unit]
Description=Real time system monitoring
After=network.target httpd.service squid.service nfs-server.service mysqld.service named.service postfix.service

[Service]
Type=simple
User=netdata
Group=netdata

# is this realy needed?
RuntimeDirectory=netdata

# netdata internally already handles this
WorkingDirectory=/tmp

# no need for pid file, we start netdata without forking
# PIDFile=/var/run/netdata.pid
ExecStart=/usr/sbin/netdata -D

# -----------------------------------------------------------------------------
# Stopping netdata

KillMode=mixed
KillSignal=SIGTERM

# saving a big db on slow disks may need some time
TimeoutStopSec=60

# and disable SIGKILL - if sent during save, we will loose the db
SendSIGKILL=no

# -----------------------------------------------------------------------------
# Hardening

AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only
# NoNewPrivileges=true is implicitly set by the MemoryDenyWriteExecute=true

# This makes node.js plugins to crash
# MemoryDenyWriteExecute=true

# -----------------------------------------------------------------------------
# Be very system friendly

# be the first to be killed when there is no memory
# netdata handles this internally
# OOMScoreAdjust=1000

# run with the lowest process priority
# netdata internally already handles this
# Nice=19

# run only when the system can spare CPU
# netdata handles this internally
# CPUSchedulingPolicy=idle

# run with lowest I/O scheduling priority
IOSchedulingPriority=7

[Install]
WantedBy=multi-user.target
```

**Comment by ktsaou** [comment]
umask is not needed. netdata handles it: https://github.com/firehol/netdata/blob/6f5478693acedeb5268db047af109b5c7f8d6a72/src/daemon.c#L238

**Comment by ktsaou** [comment]
nice is not needed. netdata handles it: https://github.com/firehol/netdata/blob/6f5478693acedeb5268db047af109b5c7f8d6a72/src/main.c#L659

**Comment by ktsaou** [comment]
related to #769 #608

**Comment by ktsaou** [comment]
netdata handles internally:

1. umask (was 0, now is 0022)
2. CPU scheduling priority to IDLE, or if that fails, nice 19.

https://github.com/ktsaou/netdata/blob/30ce32f31ea23ef2166cd24e4a9a00aac34a9946/src/daemon.c#L315-L325

**Comment by paulfantom** [comment]
I don't see issues. Maybe @candrews will see some. 
However I would prefer to create PIDfile on daemon startup. For example I am using it with monit to check if netdata runs or not (and restart it if needed).

**Comment by ktsaou** [comment]
> However I would prefer to create PIDfile on daemon startup.

Me too. We have 3 options:

1. Allow netdata start as `root` and use `/var/run/netdata.pid` so that it will never fail
2. Start netdata as user `netdata` and use `/var/run/netdata/netdata.pid` **but have a solution that will never fail**.
3. Start netdata as user `netdata` with `-D` and forget the pid file, or put it in `/var/log/netdata/netdata.pid` which will never fail.

I understand 2 cannot be done.
So, it is going to be either 1 or 3.

**Comment by ktsaou** [comment]
I came up with this:

```

[Service]
Type=simple
WorkingDirectory=/tmp
User=netdata
Group=netdata
RuntimeDirectory=netdata
ExecStartPre=mkdir -p /var/run/netdata
ExecStartPre=chown -R netdata:netdata /var/run/netdata
ExecStartPre=chmod 0775 /var/run/netdata
ExecStart=/usr/sbin/netdata -D -P /var/run/netdata/netdata.pid

# -----------------------------------------------------------------------------
# Stopping netdata

KillMode=mixed
KillSignal=SIGTERM

# saving a big db on slow disks may need some time
TimeoutStopSec=60

# and disable SIGKILL - if sent during save, we will loose the db
SendSIGKILL=no

# -----------------------------------------------------------------------------
# Hardening netdata

AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only

# is implicitly set by the MemoryDenyWriteExecute=true
# NoNewPrivileges=true

# Do not enable - it makes node.js plugins to crash
# MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
```

**Comment by ktsaou** [comment]
Check this: https://github.com/ktsaou/netdata/commit/7be4d1e56904c079e40a45b4e1ac85e5e940653a

1. SIGHUP to re-open the log files
2. updated netdata.logrotate
3. updated netdata.service to have the above (-D and -P)

**Comment by paulfantom** [comment]
Looks good. :+1: 
But I cannot test it today. I will do this tomorrow.

**Comment by ktsaou** [comment]
I found another problem. The following give these capabilities to the entire netdata process tree. With them, apps.plugin works without running `setcap` on it.

> AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE
> CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE

**Comment by ktsaou** [comment]
> The following give these capabilities to the entire netdata process tree. With them, apps.plugin works without running setcap on it.

Actually this change is actually "Loosening", not "Hardening"....

**Comment by paulfantom** [comment]
So basically we are back to the previous `netdata.service` file + adding this:
```
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only
```
I think that actions executed as `ExecStartPre` should be handled by setting appropriate [`tmpfiles`](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) when installing netdata. It would solve problems like those mentioned in #769 and maybe #780.
Also this way we can get back to using `Type=forking` with option `PIDFile`.

**Comment by ktsaou** [comment]
@alonbl was suggesting that netdata should start as user `netdata` without daemonizing itself. I think this `netdata.service` is the best so far: https://github.com/ktsaou/netdata/blob/health/system/netdata.service.in

It starts as user netdata, it does not fork, it creates a PID file and I hope it will not fail, thanks to the `ExecStartPre` lines.

**Comment by paulfantom** [comment]
It looks strange.
I don't like those `ExecStartPre` lines. This is usually done with one file located in `/etc/tmpfiles.d/` directory which should have one line:
```
d /var/run/netdata 0755 netdata netdata - -
```

**Comment by alonbl** [comment]
You should not create pid file either, systemd will manage the stop signal
for you when service type is simple.

**Comment by paulfantom** [comment]
I educated myself some more on systemd services and @alonbl is right, netdata shouldn't create PID file, and it should use Type=simple without daemonizing itself.

Also probably in this situation it can be socket activated, which can be useful if someone wants to use netdata as htop replacement and get just current data.

**Comment by ktsaou** [comment]
updated it to be `Type=simple` without a pid file. It will be merged with #775

**Comment by alonbl** [comment]
Not needed:
KillMode=mixed
KillSignal=SIGTERM

Not needed as if timed out you need to kill anyway.
SendSIGKILL=no

Not sure why this is:
RuntimeDirectory=netdata

Having /tmp as working directory is not healthy, let it be the working
directory of the $HOME of user or /.
WorkingDirectory=/tmp

The entire "Hardening netdata" is not required as it should inherit from
defaults.

**Comment by ktsaou** [comment]
Did all these: https://github.com/ktsaou/netdata/blob/health/system/netdata.service.in

Also:

- netdata now verifies it has access to its directories before starting: https://github.com/ktsaou/netdata/blob/f78f32cd77f28a251d3a9a5f7423b2745ceaefa1/src/main.c#L417-L422

- netdata `chdir`s to its configuration directory, to allow its plugins work with relative filenames for their config files: https://github.com/ktsaou/netdata/blob/f78f32cd77f28a251d3a9a5f7423b2745ceaefa1/src/main.c#L437

- verifies it can create its /var/lib/netdata/registry directory for saving registry related files: https://github.com/ktsaou/netdata/blob/health/src/registry.c#L1616-L1618

- verifies it can write its unique registry id too: https://github.com/ktsaou/netdata/blob/health/src/registry.c#L1261-L1266

If any of these verifications fail, it quits with an error.

**Comment by ktsaou** [comment]
merged  the fix.
