### ISSUE TITLE
netdata nginx revese proxy

### ISSUE THREAD

**Issue by ezar** [firehol/netdata#778]
First, thank you for this wonderful app! I liked it.

I want to use nginx reverse https proxy. I follow wiki page but it doesn't works:

Error:

> File '/usr/share/netdata/web/netdata' does not exist, or is not accessible.

```
upstream netdata_server {
    # the netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

        location /netdata {
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://netdata_server;
                proxy_http_version 1.1;
                proxy_pass_request_headers on;
                proxy_set_header Connection "keep-alive";
                proxy_store off;
        }
```

Can you help me?

**Comment by paulfantom** [comment]
Maybe this `location` block will work:
```
    location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata_server/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
```

**Comment by ezar** [comment]
Doen't work!

**Comment by paulfantom** [comment]
Working site file for nginx:
```
upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
   listen 80;
   server_name localhost 127.0.0.1;

   location /netdata {
        return 301 /netdata/;
   }

   location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
```

If this doesn't work, please attach nginx logs so we can find what is causing this problem.

**Comment by paulfantom** [comment]
Also what are permissions to `'/usr/share/netdata/web/netdata`?

**Comment by ezar** [comment]
Works now! thanks @paulfantom 

I see that /usr/share/netdata/web/netdata doesn't exists... 

Regards,

**Comment by paulfantom** [comment]
> I see that /usr/share/netdata/web/netdata doesn't exists...

All web related files should be stored in `/usr/share/netdata/web`

I am closing this since it is resolved.

**Comment by ktsaou** [comment]
@rileytg I edited the wiki page https://github.com/firehol/netdata/wiki/Running-behind-nginx, mainly to change the header. The config above is about running a netdata as a subfolder, not a subdomain.

Thanks!

**Comment by Avik1993** [comment]
I am having similar issue.
I get error message `File does not exist, or is not accessible: /usr/share/netdata/web/netdata/`

**Comment by Avik1993** [comment]
> > I see that /usr/share/netdata/web/netdata doesn't exists...
> 
> All web related files should be stored in `/usr/share/netdata/web`
> 
> I am closing this since it is resolved.

Thats exactly what i have @paulfantom 
But why does it goes onto to refer to `/usr/share/netdata/web/netdata` instead of just `/usr/share/netdata/web`

**Comment by cakrit** [comment]
Please continue in #6393. I'll add this latest comment as well.
