### ISSUE TITLE
Release new version (v1.3 or even v2.0)

### ISSUE THREAD

**Issue by paulfantom** [firehol/netdata#782]
@ktsaou I think we should be releasing new version of netdata soon. However we should fix some bugs before. I am presenting list of no-go issues which should be fixed before (most of which should be fixed by me):
- [x] #781 SegmentationFault caused by `sensors.chart.py`
- [x] #772 BrokenPipeError
- [x] #785 #773 #780 #769 systemd service and PIDFile location

If you have more, please add to the list above.

**Comment by ktsaou** [comment]
I agree. I think it would be better to proceed to version 2.0 by including PR #775.
I am just a few days before I have operational health monitoring.
Also, in the same PR I have made several improvements and cleanups.

I have also added in the same PR a systemd file I am testing, with all our findings settled.

**Comment by ktsaou** [comment]
@paulfantom I think we should release this asap, probably as 1.3. The current release 1.2 is too old and I don't want to keep the new features back for too long.

So, I suggest to focus on bug fixing this week and release it next weekend as 1.3.
If I haven't managed to render alarms on the dashboard, we will release it without it.

**Comment by paulfantom** [comment]
Oh, I just wrote about version number in #807. I agree, we should focus on bug fixing and release it as soon as possible. 
As of python part, I think it is ready. And I won't merge any new modules until v1.3.

**Comment by LucaDev** [comment]
You could use [Semantic Versioning](http://semver.org/) for more clearness about what changed if you plan more regular releases

**Comment by ktsaou** [comment]
@paulfantom I am planning for a release today. I'll merge PR #845 before doing so.
Do you have any pending items?

**Comment by paulfantom** [comment]
No I don't have any. On my side it's a go.

**Comment by ktsaou** [comment]
released 1.3.0 !

I have added a tag on it (as I always do).

**Comment by ktsaou** [comment]
all demo sites updated 1.3.0.
@paulfantom they all run python.d.plugin now...

**Comment by paulfantom** [comment]
Great! I'm so happy that I participate in this project! :tada:

I think we still have much work to do. First, let's create this "support" branch of git repo, so we can start working on improvements for v2.0. Secondly I have a list of modules I want to write or improve (based on other monitoring tools, like [telegraf](https://github.com/influxdata/telegraf), [datadog](https://github.com/DataDog/dd-agent) or NewRelic). Right now my priority is to support:
- JMX and Cassandra with it. (I think this will be some parent class, like `UrlService`)
- Mongodb
- ElasticSearch
- Couchbase

One more thing I really want to do before v2.0 is to start releasing netdata as binary package (first rpm, then deb, later others). I am still learning how to do it properly.
Sadly I won't have much time to spend on netdata in the next 2-3 months (work stuff and home project which needs attention). So my participation won't be as great as it was a month ago. But still I will try to do whatever is in my power to move netdata forward. Basically I won't write new modules, but I will support others writing them, and create bugfixes.

Also I am closing this since new version is released.

**Comment by ktsaou** [comment]
nice!

I have created `1.3.0-support` branch.

Regarding packaging, keep in mind that based on the `netdata-packages-installer.sh`, our users use these distributions:

```
      2 distribution=linuxmint
      3 distribution=redhatenterpriseserver
      4 distribution=gentoo
      4 distribution=suse
      7 distribution=oracleserver
     10 distribution=arch
     26 distribution=fedora
     38 distribution=rhel
    259 distribution=centos
    358 distribution=debian
    650 distribution=ubuntu
```

Each entry is unique per IP. So, each one is counted once.

As you can see `deb` is by far the most popular.

**Comment by ktsaou** [comment]
and a break-down by version:

```
     1 distribution=centos version=6.3
      1 distribution=centos version=6.6
      1 distribution=centos version=7.2
      1 distribution=debian version=2016.07-1
      1 distribution=debian version=3+
      1 distribution=debian version=3.1
      1 distribution=debian version=7.0
      1 distribution=manjarolinux version=16.06.1
      1 distribution=oracleserver version=6.1
      1 distribution=oracleserver version=7.2
      1 distribution=redhatenterpriseworkstation version=6.8
      1 distribution=rhel version=7.1
      1 distribution=suse version=20160716
      1 distribution=ubuntu version=0.2.1
      1 distribution=ubuntu version=11.10
      1 distribution=ubuntu version=14.10
      1 distribution=ubuntu version=2.0
      1 distribution=ubuntu version=gmac
      2 distribution=centos version=6.7
      2 distribution=debian version=2016.06-2
      2 distribution=fedora version=22
      2 distribution=linuxmint version=1
      2 distribution=rhel version=6.8
      2 distribution=ubuntu version=0.4
      2 distribution=ubuntu version=13.04
      3 distribution=debian version=2.0
      3 distribution=redhatenterpriseserver version=6.8
      3 distribution=rhel version=7
      3 distribution=suse version=42.1
      3 distribution=ubuntu version=0.3.2
      4 distribution=gentoo version=
      5 distribution=oracleserver version=6.8
      6 distribution=debian version=2016.1
      7 distribution=ubuntu version=15.04
      9 distribution=fedora version=23
     10 distribution=arch version=
     15 distribution=fedora version=24
     15 distribution=rhel version=2016.03
     16 distribution=debian version=
     17 distribution=rhel version=7.2
     17 distribution=ubuntu version=15.10
     22 distribution=ubuntu version=12.04
     69 distribution=debian version=7
     89 distribution=centos version=6.8
    163 distribution=centos version=7
    261 distribution=debian version=8
    299 distribution=ubuntu version=14.04
    313 distribution=ubuntu version=16.04
```

**Comment by paulfantom** [comment]
I chose RPM to be first just because it is easier for me to work with. My plan is to learn how to automatize package build based on RPM, then simply add DEB. But I want both of them before v2.0.
