### ISSUE TITLE
Category name in python plugin ignored

### ISSUE THREAD

**Issue by Splo0sh** [firehol/netdata#786]
Hi,

I need your help. I tried my hands at writing a plugin. I want to see the currently connected users on my TeamSpeak 3 server so I wrote this python script [here](https://github.com/Splo0sh/netdata_ts3_plugin/blob/master/ts3.chart.py?ts=4).
Everything seems to work fine, well except of an broken pipe, but I'll work this out as well at some point ^^

There is only the problem that even though I'm setting the category name as 'TeamSpeak Server', the type from "type.id" is used as the category name. Probably some stupid mistake on my side, but I would appreciate your help a lot.

Cheers,
J

Img: 
![ts3_issue](https://cloud.githubusercontent.com/assets/19515548/17671281/875418f0-6316-11e6-8e4c-6fae9251c2e7.png)

Chart Code:
```
def create(self):
    self.chart(
            'ts3.users_connected', '', 'User on TeamSpeak Server', 'users',
            'users', 'TeamSpeak Server', 'line', priority, update_every)
    self.dimension('online')
    self.commit()
    return True
```

**Comment by paulfantom** [comment]
`python.d.plugin` uses simplified chart naming, without `type.id`, `priority`, and `update_every`.
`self.chart` takes only:
- name
- title
- units
- family
- category
- charttype

**Comment by paulfantom** [comment]
Also it seems that your module could benefit from using `SocketService` instead of `SimpleService`. Look at modules like:
- dovecot
- hddtemp
- memcached
- redis
to find out how it can be implemented.

Sorry for lack of documentation on topic of python modules. It is something I should do ASAP.

**Comment by paulfantom** [comment]
I was wrong about code that I wrote. `self.chart()` of course takes all arguments you are providing. However I don't know why netdata doesn't set provided category name. Can you run `python.d.plugin debug ts3 | grep CHART` and post couple of lines?

Also I see couple of issues with your code:
- there should be no `print` statements. Instead there should be `self.debug`, `self.info`, and `self.error`. 
- all checking if server is available or not should be in `check` method not in constructor.

**Comment by paulfantom** [comment]
Can you also check if swapping chart line to this helps:
```py
self.chart('ts3.users_connected', '', 'User on TeamSpeak Server', 'users', 'TeamSpeak Server', 'ts3.users', 'line', priority, update_every)
```

**Comment by Splo0sh** [comment]
Thanks for the help and the pointers, I appreciate it! I will take them to heart and implement them asap. This screams for a version 0.2 ;) I had this script that I used for Munin and "ported" it kind of. I will look into the `SocketService`.

To the Problem at hand. `python.d.plugin debug ts3 | grep CHART` spits this out:
```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug ts3 | grep CHART
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['ts3']
python.d DEBUG: ts3: loading module configuration: '/etc/netdata/python.d/ts3.conf'
python.d DEBUG: ts3: reading configuration
ts3.chart.py [Info] TeamSpeak server process found. Connecting...
ts3.chart.py [Info] Connected to TeamSpeak server: sid=1 @ localhost:10011
python.d DEBUG: ts3: job added
python.d DEBUG: all job objects [<Service(None, initial daemon)>]
python.d DEBUG: ts3 check succeeded
python.d DEBUG: overridden job names: []
python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
python.d DEBUG: created charts for ts3
python.d DEBUG: ts3 ts3 will be run in 8984 ms
python.d DEBUG: ts3 ts3 ready to run, after 8985 ms (update_every: 10000 ms, latency: 1 ms
python.d DEBUG: ts3 ts3 updated in 4 ms
python.d DEBUG: ts3 ts3 ready to run, after 10008 ms (update_every: 10000 ms, latency: 9 ms
python.d DEBUG: ts3 ts3 updated in 3 ms
```
The config file `/etc/netdata/python.d/ts3.conf`, btw, has only comments in it:
```
# netdata python.d.plugin configuration for ts3
#
# update_every: 10
# priority: 60000
# retries: 10
```

Swapping the chart, results in this:

![ts3_issue2](https://cloud.githubusercontent.com/assets/19515548/17680644/854ed7ae-6341-11e6-8d2f-32eededc7c25.png)

**Comment by paulfantom** [comment]
Hmmm. Could you run `python.d.plugin debug ts3` and post about 40 first lines?

**Comment by Splo0sh** [comment]
sure, gladly:

```
# /usr/libexec/netdata/plugins.d/python.d.plugin debug ts3
 INFO: Using python v2
python.d INFO: reading configuration file: /etc/netdata/python.d.conf
python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['ts3']
python.d DEBUG: ts3: loading module configuration: '/etc/netdata/python.d/ts3.conf'
python.d DEBUG: ts3: reading configuration
ts3.chart.py [Info] TeamSpeak server process found. Connecting...
ts3.chart.py [Info] Connected to TeamSpeak server: sid=1 @ localhost:10011
python.d DEBUG: ts3: job added
python.d DEBUG: all job objects [<Service(None, initial daemon)>]
python.d DEBUG: ts3 check succeeded
python.d DEBUG: overridden job names: []
python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
CHART ts3.users_connected '' 'User on TeamSpeak Server' users users 'TeamSpeak Server' line 60000 10
DIMENSION online online absolute 1 1

CHART netdata.plugin_pythond_ts3 '' 'Execution time for ts3 plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 10
DIMENSION run_time 'run time' absolute 1 1

python.d DEBUG: created charts for ts3
python.d DEBUG: ts3 ts3 will be run in 7969 ms
python.d DEBUG: ts3 ts3 ready to run, after 7977 ms (update_every: 10000 ms, latency: 7 ms
BEGIN ts3.users_connected 0
SET online = 0
END

BEGIN netdata.plugin_pythond_ts3 0
SET run_time = 4
END

python.d DEBUG: ts3 ts3 updated in 4 ms
python.d DEBUG: ts3 ts3 ready to run, after 10002 ms (update_every: 10000 ms, latency: 9 ms
BEGIN ts3.users_connected 10002386
SET online = 0
END

BEGIN netdata.plugin_pythond_ts3 10002386
SET run_time = 3
END

python.d DEBUG: ts3 ts3 updated in 3 ms
python.d DEBUG: ts3 ts3 ready to run, after 9999 ms (update_every: 10000 ms, latency: 9 ms
BEGIN ts3.users_connected 9999871
SET online = 0
END

BEGIN netdata.plugin_pythond_ts3 9999871
SET run_time = 4
END

python.d DEBUG: ts3 ts3 updated in 4 ms
python.d DEBUG: ts3 ts3 ready to run, after 9996 ms (update_every: 10000 ms, latency: 6 ms
BEGIN ts3.users_connected 9996682
SET online = 0
END

python.d DEBUG: ts3 ts3 updated in 9 ms
^CTraceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 521, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 410, in update
    time.sleep(1)
KeyboardInterrupt
```

Is this enough?

**Comment by paulfantom** [comment]
Ok, I think everything is as it should be. What do you want to accomplish?

**Comment by Splo0sh** [comment]
The category name at the moment is "ts3" but I want it to be something else, like "Team SpeakServer" for example. I want to add maybe more charts beside users etc and I want them to be grouped like the others, like "Netdata Monitoring", "System", "Apache local" etc. under the banner "Teamspeak Server".

**Comment by ktsaou** [comment]
The menu name at the charts is controlled in `index.html`. By default it is the `type` in `type.id`. So the closest you can get without changing `index.html` is to the chart id to `team_speakserver.users_connected`.

Please don't set the `context` to `Team SpeakServer`. The context shou;d have the format `type.id` too, and is used when this plugin monitors multiple servers.

**Comment by ktsaou** [comment]
I found the wiki documentation was wrong. It was from a previous version of the plugins API. I updated it to reflect how it works.

https://github.com/firehol/netdata/wiki/External-Plugins

**Comment by Splo0sh** [comment]
Copy that. Thank you for clearing this up : )

**Comment by Splo0sh** [comment]
I rewrote my [Teamspeak plugin](https://github.com/Splo0sh/netdata_ts3_plugin/blob/master/ts3.chart.py?ts=4) to use the `SocketService`. I think it works nicely. I'll probably let it read out some more stats at some point.
Thanks again for the help.

**Comment by paulfantom** [comment]
@Splo0sh your rewritten Teamspeak looks nice. Although I would cahnge lines 74, and 75 from:
```py
self.user = ""  # <=== ADD LOGIN CREDENTIALS
self.passwd = ""  # <=== ADD LOGIN CREDENTIALS
```
to:
```py
try:
    self.user = configuration['user']
except KeyError:
    self.user = ""
try:
    self.passwd = configuration['pass']
except KeyError:
    self.passwd = ""
```
This way you can read `user` and `pass` from configuration file.

And please don't use `sys.exit`. This will close all `python.d.plugin` not only `ts3.chart.py` module.
Modules are closed by `python.d.plugin` when `check()` method fails.

**Comment by Splo0sh** [comment]
ah, did not think about that, of course. I will change that. Thanks for the feedback.
I already had the config file in mind for things like login credentials and maybe the amount of virtual servers to check etc. I will change that as well.

> Modules are closed by python.d.plugin when check() method fails.

So should I best not even check for a running Teamspeak process during initialization and just let it fail? Or what would you consider best practice? I just wanted to spare the plugin the retries and just disable it immediately when there is no Teamspeak server process.

**Comment by paulfantom** [comment]
Netdata took this approach:
- execute `check` method at startup to find which modules can be run. Here should be done some basic checking if monitored service is running, if there is access to it, etc.
- execute `create` method to create chart definitions
- run `update` in forever loop. If update fails retry for previously set number of times (`retries` variable)

However to simplify this, `python.d.plugin` does all those for you. You just need to choose which type of service you will be using (like `SocketService`) and provide:
- chart definition in `CHART` global variable
- charts order in `ORDER` global variable
- `Service` class with constructor executing constructor of parent class
- `_get_data` method which is how you parse data provided by `_get_raw_data` method. Output should be a dictionary, where keys are unique chart dimensions.

Simplest example of this is probably [`nginx.chart.py`](https://github.com/firehol/netdata/blob/master/python.d/nginx.chart.py).

> should I best not even check for a running Teamspeak process during initialization and just let it fail?
 
Yes, let it fail. But not with `sys.exit`, just `return None` in `_get_data` when no data could be found.

**Comment by Splo0sh** [comment]
I was just about to edit my post to "never mind, I was missing the wood for the trees". I thought the check was done before every update. Thank you for the explanation.

**Comment by paulfantom** [comment]
One more thing. If you can find a way to always know where data ends `SocketService` provides a way to keep socket open. 
Just add to class constructor:
```py
self._keep_alive = True
```
and you need to write one more method called ` _check_raw_data`.
This method takes RAW data and returns `False` if data is incomplete or `True` if it is complete.

**Comment by Splo0sh** [comment]
Those two I already got  : D thanks
