### ISSUE TITLE
LXC support

### ISSUE THREAD

**Issue by Kubuxu** [firehol/netdata#79]
Support for Linux Containers would be awesome.

Possible things to support:
* pre container usages of cpu, io and so on.
* per container network adapter usages 

Data about LXC containers can be accessed via liblxc.

**Comment by ktsaou** [comment]
I agree!
Patience...

**Comment by ticklemynausea** [comment]
Hi. I'm loving everything about netstat so far, this is amazing work!

However I ran into a little issue which I think is LXC-related. In the "Applications" section it shows per-process cpu, disk, mem and process count. The applications we have that are more resource hungry run within Linux Containers. These processes will show up under "Applications", obviously, but their names are switched with applications that run directly on the host (for example, a "java" application that takes most of our resources shows up as "fail2ban").

Maybe @Kubuxu could confirm if he sees the same is I do?

I think a fix for this would have priority over the enhancements proposed in this thread.

**Comment by ktsaou** [comment]
I don't an lxc installation handy.

The grouping of the process tree is handled with /etc/netdata/apps.conf.
Can you experiment a bit to find a solution? (restart netdata to apply it - you call also do `killall apps.plugin` without restart the whole of it, but the old chart dimensions will not go away)

**Comment by ticklemynausea** [comment]
Do you mean `/etc/netdata/apps_groups.conf` ?

I get what this file is for, but I don't think the issue I'm describing has anything to do with this.

**Comment by ktsaou** [comment]
Sorry. Yes, this is the filename.

ok. I may have misunderstood your point:

The applications section is controlled by this file. This is how "applications" are defined.

What apps.plugin does is that is builds a process tree in memory and for each process it gives it a tag (as defined in apps_groups.conf - the first word is the tag, the latter are the process names to take the tag). Processes without a tag inherit the tag of their parent process.

Then it sums up all the resource usage per tag and reports everything to netdata.

So, when you say that applications are mixed up at the charts, I understand the tagging / grouping made above is wrong.

Right?

**Comment by ktsaou** [comment]
> I came across netdata just today.

It is ok. Most did the same! Yesterday we were just very few... :)

Could you please post a screenshot with a point selected on the chart ? If it really is `fail2ban`, I do have a bug. I think though it is `other`.

You can also click on `fail2ban` to see just this one.

**Comment by ticklemynausea** [comment]
Yes of course. It is indeed fail2ban:

http://i.imgur.com/MKLZktA.png 
http://i.imgur.com/ez1MVfp.png

**Comment by ktsaou** [comment]
ok. it is a bug!

Please help me a bit more. 
Can you post the results of `ps -e` and `ps fax` ?

**Comment by ktsaou** [comment]
Make sure there is no sensitive info there. `ps -e` should not have. `ps fax` might. So check it first. This is a public site.

**Comment by ticklemynausea** [comment]
I don't really feel comfortable sharing my entire process tree with the whole internet. Would it be okay if I mail those results to you?

**Comment by ktsaou** [comment]
yes, please do so. I need to figure out what is wrong!
Thanks!

**Comment by ticklemynausea** [comment]
I've emailed you the details you asked for!

**Comment by ktsaou** [comment]
ok found it. And it might not be a bug exactly!

This is what happens:

As I said, `apps.plugin` takes the whole process tree and it gives a tag to each process. At the end of this process, a few processes are tagged and others are not.

Now, `apps.plugin` tries to figure out which tag to give to the processes that do not have one.

As I said, it gives the tag of the parent.
But what happens when none of its parents is tagged?

Well, `apps.plugin` gives to the parents the tag of top-most child that is tagged.

If no child is tagged either, it sends the whole process tree to `other`.

I am not sure I have to change it. Probably, I will need to add `lxc-start` to `apps_groups.conf`. This will make all the untagged processes under `lxc-start` to be marked as `lxc`.

What do you think?

**Comment by Kubuxu** [comment]
It would  be a solution for a problem @ticklemynausea is having.

I would be really grateful for ability to inspect usages on per container basis but it would have to come with some UI changes.

**Comment by ktsaou** [comment]
I think I should add an entry called `containers` matching all possible user space managers.

lxc is matched by `lxc-start`.

Does anyone know how to match `docker` or any other?

**Comment by ktsaou** [comment]
> I would be really grateful for ability to inspect usages on per container basis but it would have to come with some UI changes.

There are several issues about containers. I'll try to aggregate all the needs, do some research on the data available and come back with a solution. I'll invite you when I am ready.

**Comment by ticklemynausea** [comment]
@ktsaou, following your description of the issue and suggested fix, I went ahead and added `lxc: lxc-start` to apps_groups.conf and restarted netdata. It still shows up as 'fail2ban'.

**Comment by ktsaou** [comment]
ok, my bad.
Please pull it again. I believe it is fixed now.

**Comment by ticklemynausea** [comment]
It worked!

I also was able to add `java: java` to `apps_groups.conf` to closely monitor the resource heavy application which runs inside lxc.

Thanks very much!

**Comment by ktsaou** [comment]
nice!

ok, back to the original request. Support LXC monitoring.
I think this is the same with #91 
Since this has actually become an `apps.plugin` issue, I suggest to proceed discussing containers monitoring there.
I know this one was opened first, but please let me cleanup the issues a bit.
So, I close this, see you at #91.
Thanks!

**Comment by ktsaou** [comment]
have a look at #115 
I would like to have your view.
