### ISSUE TITLE
Weird behavior regarding LXCs

### ISSUE THREAD

**Issue by ovizii** [firehol/netdata#790]
I followed your installation instructions: https://github.com/firehol/netdata/wiki/Installation => starting netdata at boot => systemd 

If I do: service netdata start and visit the netdata dashboard I don't see any cgroups. 

if I then service netdata stop and simply start it by typing "netdata" on the command line while being logged in as root, I see the cgroups in my dashboard.

Any ideas?

**Comment by ktsaou** [comment]
This must be related to #608 #773 and possibly others.

I have concluded that the right systemd netdata.service is this: https://github.com/ktsaou/netdata/blob/health/system/netdata.service.in

Can you test it?
(install it in `/etc/systemd/system/netdata.service`, but fix the path for the netdata executable).

Please report back success or failure.

**Comment by ovizii** [comment]
Worked. Thanks!
