### ISSUE TITLE
cgroup-names.conf format

### ISSUE THREAD

**Issue by ovizii** [firehol/netdata#791]
I tried both of the following

lxc/100 = alfred 
lxc/102 = bailey
lxc/104 = drake 
lxc/105 = edgar 
lxc/108 = mike 
qemu.slice/103.scope = charles 
qemu.slice/111.scope = jacob 

as well as 
lxc/100 alfred 
lxc/102 bailey 
lxc/104 drake 
lxc/105 edgar 
lxc/108 mike 
qemu.slice/103.scope charles 
qemu.slice/111.scope jacob 

but I still do not see netdata picking up the names :-(

/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc/100
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc/100' is called 'lxc/100'

**Comment by ktsaou** [comment]
Can you run it by hand?

I see it does this:

```sh
cat "${CONFIG}" | grep "^${CGROUP} " | sed "s/[[:space:]]\+/ /g" | cut -d ' ' -f 2
```

So, just set `CONFIG=/etc/netdata/cgroups-names.conf` and `CGROUP="lxc/100"` and run the command above. Does it work?

**Comment by ktsaou** [comment]
Keep in mind the file `/etc/netdata/cgroups-names.conf` has to be read-accessible by user `netdata`.

**Comment by ktsaou** [comment]
And, it does not need the `=` sign.

**Comment by ovizii** [comment]
hi, thanks for the feedback. 

Can I run what by hand? This was me running it by hand, sorry, should have made that clearer:
```/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc/100
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc/100' is called 'lxc/100'`
```

I have edited /usr/libexec/netdata/plugins.d/cgroup-name.sh and replaced 
`CONFIG="${NETDATA_CONFIG_DIR}/cgroups-names.conf"
`
with
`CONFIG="/etc/netdata/cgroups-names.conf"
`

I had previously checked and all files inside /etc/netdata were owned by netdata:netdata 
`ls -al /etc/netdata/
total 344
drwxr-xr-x   5 netdata netdata   4096 Aug 16 11:31 .
drwxr-xr-x 113 root    root      4096 Aug 15 21:55 ..
-rw-r--r--   1 netdata netdata   7102 Aug 15 21:55 apps_groups.conf
-rw-r--r--   1 netdata netdata    127 Aug 16 11:36 cgroup-names.conf
drwxr-xr-x   2 netdata netdata   4096 Aug 15 21:55 charts.d
-rw-r--r--   1 netdata netdata   1829 Aug 15 21:55 charts.d.conf
-rw-rw-r--   1 netdata root    304920 Aug 16 11:56 netdata.conf
drwxr-xr-x   2 netdata netdata   4096 Aug 15 21:55 node.d
drwxr-xr-x   2 netdata netdata   4096 Aug 15 21:55 python.d
-rw-r--r--   1 netdata netdata    865 Aug 15 21:55 python.d.conf
`

and when manually run it still fails:
`#/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc/100
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc/100' is called 'lxc/100'
lxc/100
`

current content of /etc/netdata/cgroup-names.conf: 
`lxc/100 alfred
lxc/102 bailey
lxc/104 drake
lxc/105 edgar
lxc/108 mike
qemu.slice/103.scope charles
qemu.slice/111.scope jacob
`

I'm not sure why I should set: `CGROUP="lxc/100"` it currently is set to `CGROUP="${1}"` but I did try and it didn't make any difference.

**Comment by ktsaou** [comment]
Check this:

```
# cat /etc/netdata/cgroups-names.conf
lxc/100 alfred
lxc/102 bailey
lxc/104 drake
lxc/105 edgar
lxc/108 mike
qemu.slice/103.scope charles
qemu.slice/111.scope jacob

# export NETDATA_CONFIG_DIR=/etc/netdata/

# /usr/libexec/netdata/plugins.d/cgroup-name.sh lxc/100
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc/100' is called 'alfred'
alfred

```

So, it works for me.
Can you re-check?

**Comment by ktsaou** [comment]
check again with the stock version of the script. This is what I did.

**Comment by ovizii** [comment]
oh god. I had a typo: `cgroup-names.conf` - missing the S after cgroup :-( 
so sorry about this.

**Comment by ovizii** [comment]
Sorry to re-open this issue but I just updated to the latest netdata version and my containers are again called lxc 100 instead of the names I gave them. 

`#cat /etc/netdata/cgroups-names.conf
lxc/100 alfred
lxc/102 bailey
lxc/104 drake
lxc/105 edgar
lxc/108 mike
lxc/112 lawrence
qemu.slice/103.scope charles
qemu.slice/111.scope jacob`

and yet inside netdata they are named: 
`lxc 100
lxc 102
.
.
.
qemu.slice 111.scope`

is my format somehow off?

**Comment by ktsaou** [comment]
For code blocks use 3x <code> ` </code> at the beginning and the end (I edited your comment to fix this).

Hm... I think there are a need to convert certain characters that interfere with javascript to `_`.
So, could you please check your `/var/log/netdata/error.log`?

Probably you need this:

```
lxc_100 alfred
lxc_102 bailey
```

Sorry for the inconvenience! I really missed this side-effect when I made this change.

**Comment by ovizii** [comment]
Thanks, will remember the tripple `for the future!

/var/log/netdata/error.log indeed contained entries like:
```/usr/libexec/netdata/plugins.d/cgroup-name.sh: cannot find cgroup 'lxc_112' in '/etc/netda
ta/cgroups-names.conf'.
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cannot find cgroup 'qemu.slice' in '/etc/ne
tdata/cgroups-names.conf'.```

and changing to this worked indeed: 
```
lxc_100 alfred
lxc_102 bailey
lxc_104 drake
lxc_105 edgar
lxc_108 mike
lxc_112 lawrence
qemu.slice_103.scope charles
qemu.slice_111.scope jacob
```

**Comment by neogta** [comment]
Hello,
sorry to come back on this issue.

I have NO problem with LXC containers
BUT cannot get to work my QEMU containers matching name : 
My cgroups-names.conf
`qemu.slice_101.scope SGX-Freenas
qemu.slice_991.scope SGX-Windows10
lxc_102 SGX-Owncloud
lxc_100 SGX-Landing
lxc_103 SGX-Openvpn
lxc_104 SGX-Redmine
lxc_105 SGX-Pydio
lxc_107 SGX-Nextcloud
lxc_110 SGX-Ampache
lxc_112 SGX-Piwigo
lxc_151 WEB-msage
lxc_152 WEB-reserve
lxc_153 WEB-adecom
lxc_154 WEB-gabriel
lxc_200 SGX-rto
lxc_301 SGX-backuppc
lxc_333 SGX-Plex
lxc_401 SGX-GauchoOC
lxc_901 SGX-zoneminder
lxc_995 SGX-dash
`

output of :  /usr/libexec/netdata/plugins.d/cgroup-name.sh qemu.slice_991.scope
```
2017-03-15 12:14:58: cgroup-name.sh: INFO: cgroup 'qemu.slice_991.scope' is called 'SGX-Windows10'
SGX-Windows10
```

my netdata.conf  cgroups part: 
`[plugin:cgroups]
	enable cgroup lxc_110-1 = no
	enable cgroup lxc_110-2 = no
	enable cgroup lxc_333-1 = no
	enable cgroup lxc_200-1 = no
	enable cgroup lxc_200-2 = no
	enable cgroup lxc_200-3 = no
	enable cgroup lxc_200-4 = no
	enable cgroup lxc_200-5 = no
	enable cgroup lxc_200-6 = no
	enable cgroup lxc_200-7 = no
	enable cgroup lxc_200-8 = no
	enable cgroup lxc_200-9 = no
	enable cgroup lxc_200-10 = no
	enable cgroup lxc_200-11 = no
	enable cgroup lxc_200-12 = no
	enable cgroup lxc_200-13 = no
	enable cgroup lxc_200-14 = no
	enable cgroup lxc_200-15 = no
	enable cgroup lxc_200-16 = no
	enable cgroup qemu.slice = yes
	enable cgroup qemu.slice/991.scope = yes
	enable cgroup qemu.slice/101.scope = yes
	enable by default cgroups matching = /system.slice/docker-*.scope  !*.mount  !*.partition  !*.scope  !*.service  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/ns  !/machine   !/system  !/systemd  !/user  *
	# cgroups plugin resource charts = yes
	# update every = 1
	# check for new cgroups every = 10
	# enable cpuacct stat (total CPU) = auto
	# enable cpuacct usage (per core CPU) = auto
	# enable memory (used mem including cache) = auto
	# enable detailed memory = auto
	# enable memory limits fail count = auto
	# enable swap memory = auto
	# enable blkio bandwidth = auto
	# enable blkio operations = auto
	# enable blkio throttle bandwidth = auto
	# enable blkio throttle operations = auto
	# enable blkio queued operations = auto
	# enable blkio merged operations = auto
	# recheck zero blkio every iterations = 10
	# recheck zero memory failcnt every iterations = 10
	# recheck zero detailed memory every iterations = 10
	# enable systemd services = yes
	# enable systemd services detailed memory = no
	# report used memory without cache = yes
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpu,cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
	# max cgroups to allow = 500
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# search for cgroups in subpaths matching =  !*-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  * 
	# script to get cgroup names = /mnt/SSD/ADMIN/NETDATA/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
	# run script to rename cgroups matching =  *docker*  *lxc*  !/  !*.mount  !*.partition  !*.scope  !*.service  !*.slice  !*.swap  !*.user  * 
	# cgroups to match as systemd services =  !/system.slice/*/*.service  /system.slice/*.service 
	# enable cgroup / = no
	# search for cgroups under / = yes
	# enable cgroup lxc = no
	# search for cgroups under /lxc = yes
	# enable cgroup sgx-owncloud = yes
	# search for cgroups under /lxc/102 = yes
	# enable cgroup lxc_102_ns = no
	# enable cgroup sgx-redmine = yes
	# search for cgroups under /lxc/104 = yes
	# enable cgroup lxc_104_ns = no
	# enable cgroup sgx-pydio = yes
	# search for cgroups under /lxc/105 = yes
	# enable cgroup lxc_105_ns = no
	# enable cgroup sgx-nextcloud = yes
	# search for cgroups under /lxc/107 = yes
	# enable cgroup lxc_107_ns = no
	# enable cgroup sgx-ampache = yes
	# search for cgroups under /lxc/110 = yes
	# enable cgroup lxc_110_ns = no
	# enable cgroup web-msage = yes
	# search for cgroups under /lxc/151 = yes
	# enable cgroup lxc_151_ns = no
	# enable cgroup web-reserve = yes
	# search for cgroups under /lxc/152 = yes
	# enable cgroup lxc_152_ns = no
	# enable cgroup web-adecom = yes
	# search for cgroups under /lxc/153 = yes
	# enable cgroup lxc_153_ns = no
	# enable cgroup web-gabriel = yes
	# search for cgroups under /lxc/154 = yes
	# enable cgroup lxc_154_ns = no
	# enable cgroup sgx-rto = yes
	# search for cgroups under /lxc/200 = yes
	# enable cgroup lxc_200_ns = no
	# enable cgroup sgx-backuppc = yes
	# search for cgroups under /lxc/301 = yes
	# enable cgroup lxc_301_ns = no
	# enable cgroup sgx-plex = yes
	# search for cgroups under /lxc/333 = yes
	# enable cgroup lxc_333_ns = no
	# search for cgroups under /lxc/333/ns = yes
	# enable cgroup lxc_333_ns_init.scope = no
	# enable cgroup lxc_333_ns_system.slice = no
	# enable cgroup sgx-gauchooc = yes
	# search for cgroups under /lxc/401 = yes
	# enable cgroup lxc_401_ns = no
	# enable cgroup sgx-zoneminder = yes
	# search for cgroups under /lxc/901 = yes
	# enable cgroup lxc_901_ns = no
	# search for cgroups under /lxc/901/ns = yes
	# enable cgroup lxc_901_ns_init.scope = no
	# enable cgroup lxc_901_ns_system.slice = no
	# enable cgroup lxc_901_ns_user.slice = no
	# search for cgroups under /lxc/901/ns/user.slice = yes
	# enable cgroup lxc_901_ns_user.slice_user-0.slice = no
	# search for cgroups under /lxc/901/ns/user.slice/user-0.slice = yes
	# enable cgroup lxc_901_ns_user.slice_user-0.slice_session-52168.scope = no
	# enable cgroup lxc_901_ns_user.slice_user-0.slice_user_0.service = no
	# enable cgroup lxc_901_ns_user.slice_user-0.slice_session-52134.scope = no
	# enable cgroup sgx-dash = yes
	# search for cgroups under /lxc/995 = yes
	# enable cgroup lxc_995_ns = no
	# search for cgroups under /lxc/110-1 = yes
	# enable cgroup lxc_110-1_ns = no
	# search for cgroups under /lxc/110-2 = yes
	# enable cgroup lxc_110-2_ns = no
	# search for cgroups under /lxc/200-1 = yes
	# enable cgroup lxc_200-1_ns = no
	# search for cgroups under /lxc/200-2 = yes
	# enable cgroup lxc_200-2_ns = no
	# search for cgroups under /lxc/200-3 = yes
	# enable cgroup lxc_200-3_ns = no
	# search for cgroups under /lxc/200-4 = yes
	# enable cgroup lxc_200-4_ns = no
	# search for cgroups under /lxc/200-5 = yes
	# enable cgroup lxc_200-5_ns = no
	# search for cgroups under /lxc/200-6 = yes
	# enable cgroup lxc_200-6_ns = no
	# search for cgroups under /lxc/200-7 = yes
	# enable cgroup lxc_200-7_ns = no
	# search for cgroups under /lxc/200-8 = yes
	# enable cgroup lxc_200-8_ns = no
	# search for cgroups under /lxc/200-9 = yes
	# enable cgroup lxc_200-9_ns = no
	# search for cgroups under /lxc/333-1 = yes
	# enable cgroup lxc_333-1_ns = no
	# search for cgroups under /lxc/333-1/ns = yes
	# enable cgroup lxc_333-1_ns_init.scope = no
	# enable cgroup lxc_333-1_ns_system.slice = no
	# enable cgroup lxc_333-1_ns_user.slice = no
	# search for cgroups under /lxc/200-10 = yes
	# enable cgroup lxc_200-10_ns = no
	# search for cgroups under /lxc/200-11 = yes
	# enable cgroup lxc_200-11_ns = no
	# search for cgroups under /lxc/200-12 = yes
	# enable cgroup lxc_200-12_ns = no
	# search for cgroups under /lxc/200-13 = yes
	# enable cgroup lxc_200-13_ns = no
	# search for cgroups under /lxc/200-14 = yes
	# enable cgroup lxc_200-14_ns = no
	# search for cgroups under /lxc/200-15 = yes
	# enable cgroup lxc_200-15_ns = no
	# search for cgroups under /lxc/200-16 = yes
	# enable cgroup lxc_200-16_ns = no
	# search for cgroups under /qemu.slice = yes
	# enable cgroup system.slice = no
	# enable cgroup user.slice = no
	# search for cgroups under /lxc/107/ns = yes
	# enable cgroup lxc_107_ns_init.scope = no
	# enable cgroup lxc_107_ns_system.slice = no
	# search for cgroups under /lxc/107/ns/system.slice = yes
	# enable cgroup lxc_107_ns_system.slice_dbus.service = no
	# enable cgroup lxc_107_ns_system.slice_proc-sys-net.mount = no
	# enable cgroup lxc_107_ns_system.slice_proc-stat.mount = no
	# enable cgroup lxc_107_ns_system.slice_cron.service = no
	# enable cgroup lxc_107_ns_system.slice_dev-lxc-console.mount = no
	# enable cgroup lxc_107_ns_system.slice_rc-local.service = no
	# enable cgroup lxc_107_ns_system.slice_mnt-ivan.mount = no
	# enable cgroup lxc_107_ns_system.slice_apache2.service = no
	# enable cgroup lxc_107_ns_system.slice_postfix.service = no
	# enable cgroup lxc_107_ns_system.slice_mnt-younes.mount = no
	# enable cgroup lxc_107_ns_system.slice_mnt-manudl.mount = no
	# enable cgroup lxc_107_ns_system.slice_-.mount = no
	# enable cgroup lxc_107_ns_system.slice_proc-uptime.mount = no
	# enable cgroup lxc_107_ns_system.slice_networking.service = no
	# enable cgroup lxc_107_ns_system.slice_ufw.service = no
	# enable cgroup lxc_107_ns_system.slice_accounts-daemon.service = no
	# enable cgroup lxc_107_ns_system.slice_resolvconf.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-user-sessions.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-journald.service = no
	# enable cgroup lxc_107_ns_system.slice_sys-devices-virtual-net.mount = no
	# enable cgroup lxc_107_ns_system.slice_sys-fs-fuse-connections.mount = no
	# enable cgroup lxc_107_ns_system.slice_systemd-tmpfiles-setup.service = no
	# enable cgroup lxc_107_ns_system.slice_proc-diskstats.mount = no
	# enable cgroup lxc_107_ns_system.slice_ondemand.service = no
	# enable cgroup lxc_107_ns_system.slice_dev-mqueue.mount = no
	# enable cgroup lxc_107_ns_system.slice_proc-swaps.mount = no
	# enable cgroup lxc_107_ns_system.slice_ssh.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-logind.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-journal-flush.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-random-seed.service = no
	# enable cgroup lxc_107_ns_system.slice_system-getty.slice = no
	# enable cgroup lxc_107_ns_system.slice_system-container/x2dgetty.slice = no
	# enable cgroup lxc_107_ns_system.slice_mysql.service = no
	# enable cgroup lxc_107_ns_system.slice_proc-cpuinfo.mount = no
	# enable cgroup lxc_107_ns_system.slice_proc-sysrq/x2dtrigger.mount = no
	# enable cgroup lxc_107_ns_system.slice_proc-meminfo.mount = no
	# enable cgroup lxc_107_ns_system.slice_irqbalance.service = no
	# enable cgroup lxc_107_ns_system.slice_dev-lxc-tty1.mount = no
	# enable cgroup lxc_107_ns_system.slice_console-getty.service = no
	# enable cgroup lxc_107_ns_system.slice_php7.0-fpm.service = no
	# enable cgroup lxc_107_ns_system.slice_apparmor.service = no
	# enable cgroup lxc_107_ns_system.slice_rsyslog.service = no
	# enable cgroup lxc_107_ns_system.slice_systemd-remount-fs.service = no
	# enable cgroup lxc_107_ns_system.slice_sys-kernel-debug.mount = no
	# enable cgroup lxc_107_ns_system.slice_dev-hugepages.mount = no
	# enable cgroup lxc_107_ns_system.slice_systemd-update-utmp.service = no
	# enable cgroup lxc_107_ns_system.slice_mnt-manu.mount = no
	# enable cgroup lxc_107_ns_system.slice_dev-lxc-tty2.mount = no
	# enable cgroup lxc_107_ns_user.slice = no
	# search for cgroups under /lxc/333/ns/system.slice = yes
	# enable cgroup lxc_333_ns_system.slice_dbus.service = no
	# enable cgroup lxc_333_ns_system.slice_proc-sys-net.mount = no
	# enable cgroup lxc_333_ns_system.slice_dev-lxc-console.mount = no
	# enable cgroup lxc_333_ns_system.slice_nslcd.service = no
	# enable cgroup lxc_333_ns_system.slice_-.mount = no
	# enable cgroup lxc_333_ns_system.slice_ufw.service = no
	# enable cgroup lxc_333_ns_system.slice_resolvconf.service = no
	# enable cgroup lxc_333_ns_system.slice_systemd-journald.service = no
	# enable cgroup lxc_333_ns_system.slice_sys-devices-virtual-net.mount = no
	# enable cgroup lxc_333_ns_system.slice_sys-fs-fuse-connections.mount = no
	# enable cgroup lxc_333_ns_system.slice_dev-mqueue.mount = no
	# enable cgroup lxc_333_ns_system.slice_systemd-journal-flush.service = no
	# enable cgroup lxc_333_ns_system.slice_systemd-reboot.service = no
	# enable cgroup lxc_333_ns_system.slice_apparmor.service = no
	# enable cgroup lxc_333_ns_system.slice_sys-kernel-debug.mount = no
	# enable cgroup lxc_333_ns_system.slice_dev-hugepages.mount = no
	# enable cgroup lxc_333_ns_system.slice_systemd-update-utmp.service = no
	# search for cgroups under /lxc/901/ns/system.slice = yes
	# enable cgroup lxc_901_ns_system.slice_dbus.service = no
	# enable cgroup lxc_901_ns_system.slice_proc-sys-net.mount = no
	# enable cgroup lxc_901_ns_system.slice_proc-stat.mount = no
	# enable cgroup lxc_901_ns_system.slice_cron.service = no
	# enable cgroup lxc_901_ns_system.slice_dev-lxc-console.mount = no
	# enable cgroup lxc_901_ns_system.slice_rc-local.service = no
	# enable cgroup lxc_901_ns_system.slice_apache2.service = no
	# enable cgroup lxc_901_ns_system.slice_postfix.service = no
	# enable cgroup lxc_901_ns_system.slice_-.mount = no
	# enable cgroup lxc_901_ns_system.slice_proc-uptime.mount = no
	# enable cgroup lxc_901_ns_system.slice_networking.service = no
	# enable cgroup lxc_901_ns_system.slice_ufw.service = no
	# enable cgroup lxc_901_ns_system.slice_accounts-daemon.service = no
	# enable cgroup lxc_901_ns_system.slice_resolvconf.service = no
	# enable cgroup lxc_901_ns_system.slice_systemd-user-sessions.service = no
	# enable cgroup lxc_901_ns_system.slice_systemd-journald.service = no
	# enable cgroup lxc_901_ns_system.slice_sys-devices-virtual-net.mount = no
	# enable cgroup lxc_901_ns_system.slice_sys-fs-fuse-connections.mount = no
	# enable cgroup lxc_901_ns_system.slice_systemd-tmpfiles-setup.service = no
	# enable cgroup lxc_901_ns_system.slice_zoneminder.service = no
	# enable cgroup lxc_901_ns_system.slice_proc-diskstats.mount = no
	# enable cgroup lxc_901_ns_system.slice_var-cache-zoneminder.mount = no
	# enable cgroup lxc_901_ns_system.slice_systemd-resolved.service = no
	# enable cgroup lxc_901_ns_system.slice_dev-mqueue.mount = no
	# enable cgroup lxc_901_ns_system.slice_proc-swaps.mount = no
	# enable cgroup lxc_901_ns_system.slice_ssh.service = no
	# enable cgroup lxc_901_ns_system.slice_systemd-logind.service = no
	# enable cgroup lxc_901_ns_system.slice_systemd-journal-flush.service = no
	# enable cgroup lxc_901_ns_system.slice_systemd-random-seed.service = no
	# enable cgroup lxc_901_ns_system.slice_system-postfix.slice = no
	# enable cgroup lxc_901_ns_system.slice_system-getty.slice = no
	# enable cgroup lxc_901_ns_system.slice_system-container/x2dgetty.slice = no
	# enable cgroup lxc_901_ns_system.slice_keyboard-setup.service = no
	# enable cgroup lxc_901_ns_system.slice_polkitd.service = no
	# enable cgroup lxc_901_ns_system.slice_mysql.service = no
	# enable cgroup lxc_901_ns_system.slice_proc-cpuinfo.mount = no
	# enable cgroup lxc_901_ns_system.slice_proc-sysrq/x2dtrigger.mount = no
	# enable cgroup lxc_901_ns_system.slice_proc-meminfo.mount = no
	# enable cgroup lxc_901_ns_system.slice_irqbalance.service = no
	# enable cgroup lxc_901_ns_system.slice_dev-lxc-tty1.mount = no
	# enable cgroup lxc_901_ns_system.slice_console-getty.service = no
	# enable cgroup lxc_901_ns_system.slice_apparmor.service = no
	# enable cgroup lxc_901_ns_system.slice_console-setup.service = no
	# enable cgroup lxc_901_ns_system.slice_rsyslog.service = no`

and output :) 

![image](https://cloud.githubusercontent.com/assets/11615302/23946083/4ceb42c4-0979-11e7-95c5-9a16c646e0f2.png)

thanks !
