### ISSUE TITLE
No longer getting sensor data

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#792]
As of recently, (I'm not sure exactly when, but within the last few days), I am no longer getting sensor data in Netdata.

In the error logs, I get:
```
python.d ERROR: Problem loading sensors No Module named new_sensors
```

**Comment by ktsaou** [comment]
@paulfantom check this. I checked on my machines, I am not getting them either.

**Comment by paulfantom** [comment]
This should be fixed now. There was a bug in `sensors.chart.py`, but I already fixed it.
@kmlucy can you confirm?

**Comment by kmlucy** [comment]
The sensors data is back, but the core naming is off. The cores should be numbered 0 through 3, but they are showing as 0, 1, 9, and 10. See the screenshot:

![screenshot 2016-08-16 at 1 19 36 pm](https://cloud.githubusercontent.com/assets/13952475/17708703/1f6ff2ec-63b4-11e6-9e1b-3cb3a214fce1.png)

**Comment by paulfantom** [comment]
Can you append output of `sensors` command?

**Comment by paulfantom** [comment]
Ok, no need for this, I found your old output of `sensors` command.
Recently I have moved to [different sensors library](https://github.com/paroj/sensors.py) and I believe it might be a bug in this library.

**Comment by kmlucy** [comment]
Actually, it looks like that's my bad. I just swapped the CPUs in the server, and I didn't realize the core names had changed. 

```
kyle@manta:~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +41.0°C  (high = +61.0°C, crit = +71.0°C)
Core 1:       +39.0°C  (high = +61.0°C, crit = +71.0°C)
Core 9:       +38.0°C  (high = +61.0°C, crit = +71.0°C)
Core 10:      +38.0°C  (high = +61.0°C, crit = +71.0°C)
coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +42.0°C  (high = +61.0°C, crit = +71.0°C)
Core 1:       +38.0°C  (high = +61.0°C, crit = +71.0°C)
Core 9:       +41.0°C  (high = +61.0°C, crit = +71.0°C)
Core 10:      +41.0°C  (high = +61.0°C, crit = +71.0°C)
```

**Comment by paulfantom** [comment]
Oh. Good to see that this isn't a bug :smile:

I am closing this since I believe it is resolved.

**Comment by kmlucy** [comment]
Confirmed, this is resolved. Thanks for the help.
