### ISSUE TITLE
Error package autoconf 2.59

### ISSUE THREAD

**Issue by ragansis** [firehol/netdata#795]
I have the next error
autotools 2.60 or later is required

Found autotools 2.59

---

autotools 2.60 or later is required

Sorry, you do not seem to have autotools 2.60 or later, which is
required to build from the git sources of netdata.

Netdata is support for RedHat 5.5?

Thanks

regards

**Comment by ktsaou** [comment]
Netdata will run if you manage to compile it.

@philwhineray @alonbl any ideas on how to compile netdata with autotools 2.59? Which is the feature of 2.60 we need?

**Comment by alonbl** [comment]
there is no reason to support autoconf < 2.60, we discussed that multiple
times in the past, you release tarball generated with recent autotools,
this tarball contain anything that is required to be built without
autotools dependencies..

**Comment by ktsaou** [comment]
@alonbl thanks!
@ragansis this means you can install the released version of netdata. In a few days we will release 2.0. So, please install 1.2.0 for the moment and update to 2.0 when it will be released.

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
