### ISSUE TITLE
RPM build fails on RHEL 6.8

### ISSUE THREAD

**Issue by cscicchillo** [firehol/netdata#796]
Trying to package netdata for RHEL 6.8 using the included spec file from the github repo. Build fails with the following errors:

```
+ /usr/lib/rpm/check-buildroot
Processing files: netdata-1.2.0-1.el6.x86_64
error: File not found by glob: /home/X/rpmbuild/BUILDROOT/netdata-1.2.0-1.el6.x86_64/etc/netdata/python.d/*.conf
error: File not found: /home/X/rpmbuild/BUILDROOT/netdata-1.2.0-1.el6.x86_64/var/lib/netdata


RPM build errors:
    File not found by glob: /home/X/rpmbuild/BUILDROOT/netdata-1.2.0-1.el6.x86_64/etc/netdata/python.d/*.conf
    File not found: /home/X/rpmbuild/BUILDROOT/netdata-1.2.0-1.el6.x86_64/var/lib/netdata

```

Full build output attached
[out.txt](https://github.com/firehol/netdata/files/423171/out.txt)

**Comment by cscicchillo** [comment]
I used the source from http://firehol.org/download/netdata/releases/v1.2.0/ and it appears it does not contain all the files referenced in the spec file such as the python.d directory. I've also tried the netdata-master.zip downloaded from github without any luck although it is a different problem.

**Comment by paulfantom** [comment]
You cannot mix software version and expect it to work. Current spec file is for current (master branch of git repository) version of netdata, not v1.2.0. Reason you are seeing problems with `python.d` folder is simple: there was no python plugin in v1.2.0. If you want to use v1.2.0 look at this spec file: https://github.com/firehol/netdata/blob/bb4aa949f5ac825253d8adc6070661299abc1c3b/netdata.spec.in

What is the problem with current spec file and `netdata-master.zip`?

**Comment by cscicchillo** [comment]
I think it's a version issue then. I will double check everything and give it a shot.

**Comment by ktsaou** [comment]
There has been quite some work on rpm packaging since this issue was opened.

Please update your netdata and give it a try again.
If you find an issue, please post here.
