### ISSUE TITLE
duplicate notifications for partition and block device (disk)

### ISSUE THREAD

**Issue by davidak** [firehol/netdata#800]
Since the VM runs on a XenServer, the first block device is named `xvda`.

On that we have 3 partitions mounted to `/` (ext4), `/boot` (ext4) and swap.

![bildschirmfoto 2016-08-18 um 15 12 12](https://cloud.githubusercontent.com/assets/91113/17774910/30c60f06-6556-11e6-9af1-3a31ce7b481c.png)

Netdata recognizes the 2 mountpoints and the blockdevice.

Since the mountpoints are **on** the blockdevice we get very similar values. That might be useful when we have more partitions so we have combined values in the block device graphs.

`/` or `dm_1` like the graph is called, has no equivalent to `disk_mops.xvda`, the rest of the graphs are identical. `/` has `disk_space` and `disk_inodes` additionally. `/boot` has only `disk_space` and `disk_inodes`.

But we get duplicated notification with the new alerting feature when the main partition has a high backlog value.

steps to reproduce:
1. create big file that uses not more than 80% of space (20 GB free, so my file will be 12 GB)

`dd if=/dev/zero of=testdatei bs=1M count=12000`
1. while the file get's created with 93 MB/s i get 4 notifications with similar informations for `/` (here `dm-1`) and `xvda`

```
disk_backlog.xvda
CHART
5min_disk_backlog = 2734
ALARM
Escalated to CRITICAL
SEVERITY
Thu Aug 18 15:43:20 CEST 2016 
(was in warning for 1 minute)
TIME
```

```
disk_backlog.dm-1
CHART
5min_disk_backlog = 2677
ALARM
Escalated to CRITICAL
SEVERITY
Thu Aug 18 15:43:22 CEST 2016 
(was in warning for 1 minute)
TIME
```

That is duplicate information and not helpful.

**Comment by ktsaou** [comment]
@davidak we have to find if it is possible for netdata to detect that `dm-1` and `xvda` are the same disk.

netdata detects disk and partitions using `/proc/self/mountinfo`. It assumes that block devices with the same major number on `/proc/self/mountinfo` are the same disk and different minor numbers define partitions.

Can you post your `/proc/self/mountinfo`? (only the entries related to `xvda` and `dm-1` are related to this)

**Comment by davidak** [comment]
```
$ cat /proc/self/mountinfo
17 22 0:15 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
18 22 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
19 22 0:5 / /dev rw,relatime - devtmpfs udev rw,size=496624k,nr_inodes=124156,mode=755
20 19 0:12 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
21 22 0:16 / /run rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=101372k,mode=755
22 1 252:1 / / rw,noatime,nodiratime - ext4 /dev/dm-1 rw,nobarrier,quota,usrquota,grpquota,errors=remount-ro,data=ordered
23 17 0:17 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
24 17 0:18 / /sys/fs/fuse/connections rw,relatime - fusectl none rw
25 17 0:6 / /sys/kernel/debug rw,relatime - debugfs none rw
26 17 0:10 / /sys/kernel/security rw,relatime - securityfs none rw
27 21 0:19 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=5120k
28 21 0:20 / /run/shm rw,nosuid,nodev,relatime - tmpfs none rw
29 21 0:21 / /run/user rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=102400k,mode=755
30 17 0:22 / /sys/fs/pstore rw,relatime - pstore none rw
31 22 202:1 / /boot rw,relatime - ext4 /dev/xvda1 rw,data=ordered
32 18 0:23 / /proc/xen rw,relatime - xenfs none rw
```

I use LVM for the `/` and swap Partition.

```
$ mount
/dev/mapper/vg01-lvroot on / type ext4 (rw,noatime,nodiratime,errors=remount-ro,barrier=0,usrquota,grpquota)
...
/dev/xvda1 on /boot type ext4 (rw)
```

**Comment by ktsaou** [comment]
hm... we need to find something that will say that `dm-1` and `xdva` are the same. But I don't see a solution.

**Comment by davidak** [comment]
maybe we can find a hint somewhere in `/sys`

```
cat /sys/devices/virtual/block/dm-1/dm/name
vg01-lvroot
```

Is it only a problem with LVM?

**Comment by ktsaou** [comment]
well, I think all the volume managers will be problematic in this area. Volume managers use the underlying physical disks in many different ways, so unless we start detecting exactly what each volume manager does, there will be no solution to this problem...

**Comment by ktsaou** [comment]
Cleaning up.
