### ISSUE TITLE
Tomcat plugin only works with BIO connector

### ISSUE THREAD

**Issue by Reya** [firehol/netdata#801]
Hello,

I had a problem to use netdata with Tomcat.

In "tomcat.char.py" line 96 and 97:
 `threads = data.find("./connector[@name='\"http-bio-" + str(self.port) + "\"']/threadInfo")`
`requests = data.find("./connector[@name='\"http-bio-" + str(self.port) + "\"']/requestInfo")`

I replaced "http-bio" by "http-nio" and it works. I think it will be interesting to add all the connectors used by Tomcat ([Tomcat connectors documentation](https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Connector_Comparison))

**Comment by Dominiquini** [comment]
I have this problem too...

**Comment by ktsaou** [comment]
@paulfantom can we support both `bio` and `nio` ?

**Comment by paulfantom** [comment]
I think it is doable. Will work on it.

**Comment by ktsaou** [comment]
@paulfantom when you find some time remember this too...

**Comment by paulfantom** [comment]
@ktsaou I'll try to resolve some issues this weekend (sorry, don't have much time on other days).

**Comment by ktsaou** [comment]
ok, I'll try to delay 1.4 release for a week to have as much as you can in it.

**Comment by paulfantom** [comment]
@Reya could you test if version from (tomcat-connectors branch in my repository)[https://github.com/paulfantom/netdata/tree/tomcat-connectors] is working for `nio` connector?

**Comment by Reya** [comment]
@paulfantom It does not work.
It never goes in the except block because no exception is thrown here:
```
except:
            self.connector = "http-nio"
            test = self._get_data()

```
Maybe that could be a solution (just thinking) :
```
test = self._get_data()
if test is None or len(test) == 0:
         self.connector = "http-nio"
         test = self._get_data()
if test is None or len(test) == 0:
          return False
else:
          return True
```

**Comment by Reya** [comment]
up

**Comment by l2isbad** [comment]
@Reya are you still interested in it? 
I found that `http://localhost:8080/manager/status?XML=true` is very easy to parse with regex
```
>>> dict(re.findall(r'([\w]+)=\\?[\'\"](\d+)\\?[\'\"]', reply.text))
{u'bytesReceived': u'0', u'usageInit': u'2555904', u'usageUsed': u'2117120', u'currentThreadsBusy': u'1', u'max': u'129761280', u'currentThreadCount': u'10', u'usageCommitted': u'2555904', u'requestBytesSent': u'0', u'free': u'11107312', u'errorCount': u'1120', u'processingTime': u'4876', u'maxThreads': u'200', u'requestCount': u'2267', u'requestBytesReceived': u'0', u'bytesSent': u'4428599', u'requestProcessingTime': u'0', u'maxTime': u'1182', u'total': u'29093888', u'usageMax': u'50331648'}
Time', u'4876'), (u'requestCount', u'2267'), (u'errorCount', u'1120'), (u'bytesReceived', u'0'), (u'bytesSent', u'4428599'), (u'requestProcessingTime', u'1'), (u'requestBytesSent', u'0'), (u'requestBytesReceived', u'0'), (u'requestProcessingTime', u'0'), (u'requestBytesSent', u'0'), (u'requestBytesReceived', u'0')]

```
That is all.
