### ISSUE TITLE
Can I use some of the gauges in my page?

### ISSUE THREAD

**Issue by ssaguiar** [firehol/netdata#803]
Until now I haven't found how to embed some gauges in my page to monitor memory, disk, net traffic and cpu.
Is this possible, from the local server instance?
Where can I find examples of this? 

Thank you very much

Sergio

**Comment by ktsaou** [comment]
Hi, just open http://your.netdata:19999/tv.html and view its source. It is very simple.

**Comment by ssaguiar** [comment]
ok, thanks.
I have another question, if possible:
We use a video board's gpu's to capture video. Is it inyour plans to have suport to show data for the gpu's?
Thanks again.

**Comment by LucaDev** [comment]
look at #770

**Comment by ssaguiar** [comment]
Thanks very much, my friend.

**Comment by ktsaou** [comment]
ok, I am closing this.
