### ISSUE TITLE
Docker container names

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#812]
Docker just updated to 1.12.1 (https://github.com/docker/docker/blob/master/CHANGELOG.md), and with the update, Netdata is no longer getting the names of my Docker containers. The only relevant thing I noticed in the logs at first glance was:
```
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'docker_24d6d7864596ca723361404546e35b7f39277721109eee704fa3e88927912631' is called 'docker_24d6d7864596ca723361404546e35b7f39277721109'
```
There is one similar line for each running container.

**Comment by ktsaou** [comment]
It is a script that does this job: https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh

I can see a problem but I don't know if this will fix it: change the line 50 to add the underscore, like this:

```
DOCKERID="$( echo "${CGROUP}" | sed "s|^.*docker[_-/]\([a-fA-F0-9]\+\)[_-\.]\?.*$|\1|" )"
```

There were 2 occurences of `[-/]` which I changed to `[_-/]`.

Can you check it works like that? If it works, it has nothing to do with the docker API. I think another merge made today replaced all `-` in cgroups with `_`.

Report back for me to merge the fix.

**Comment by ktsaou** [comment]
I updated my response.

**Comment by kmlucy** [comment]
I updated `cgroup-name.sh` with the underscores, but it made no difference.

**Comment by ktsaou** [comment]
Ahh.. it needs 2 more underscores.

Can check with this version: https://github.com/ktsaou/netdata/blob/7b7793a37d3812e4ab6c216c3d48cba27870cac3/plugins.d/cgroup-name.sh

You can run the command by hand, as shown in the log - no need to install it and restart netdata.

**Comment by kmlucy** [comment]
I tried using your repo, but get the same result.

**Comment by ktsaou** [comment]
Thanks.
This time I tested it and for me it works: https://github.com/ktsaou/netdata/blob/master/plugins.d/cgroup-name.sh

Does it work for you?

**Comment by kmlucy** [comment]
Yeah, it is working for me as well now.

**Comment by ktsaou** [comment]
ok. Thanks for reporting it.
