### ISSUE TITLE
Netdata and Raspbian not showing dashboard no working buttons

### ISSUE THREAD

**Issue by sevaho** [firehol/netdata#817]
I've installed everything correctly but when I go to 127.0.0.1:19999 (actually I reverse proxy it so it's myserver.com/netdata) I'm getting a white page with text and buttons but none of the buttons is working. I've put HTTPS off but still the buttons don't work. I can also go to netdata.conf if it's needed for more information.

My server specs:

Raspberry PI 3B
Raspbian GNU/Linux 8.0 (jessie) 4.4.18-v7+

[![Screenshot from 2016-08-22 09-02-01.png](https://s14.postimg.org/qd8v01k8x/Screenshot_from_2016_08_22_09_02_01.png)](https://postimg.org/image/cjkiazrnh/)

**Comment by ktsaou** [comment]
Please press F12 on your brower to open its console. What does it log?

**Comment by sevaho** [comment]
Good troubleshoot, didn't think of that first, there is indeed some problem, output:

ReferenceError: NETDATA is not defined
<anonymous>
netdata:1678
netdata:1678:9

**Comment by ktsaou** [comment]
Press F5 with the console open. There must be an error that it cannot load a file.
Also, `tail -f /var/log/netdata/error.log` while doing this. There may be a permission problem somewhere.

**Comment by ktsaou** [comment]
Is the raspbian using a sdcard for storage? I had a similar incident in the past and it turned out the sdcard was bad.

**Comment by sevaho** [comment]
this is the output from **tail -f var/log/netdata/error.log**

`I cannot send emails - there is no sendmail command available.
/usr/libexec/netdata/plugins.d/alarm-email.sh: line 12: : command not found
/usr/libexec/netdata/plugins.d/alarm-email.sh: FAILED to send notification email for WARNING on 'disk_backlog.mmcblk0.10min_disk_backlog'
16-08-22 09:40:04: ERROR: netdata: child pid 14105 exited with code 1.
16-08-22 09:41:04: INFO: netdata: Health alarm 'disk_backlog.mmcblk0.10min_disk_backlog' = 614.05 - changed status from WARNING to CLEAR
16-08-22 09:41:04: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/alarm-email.sh '10min_disk_backlog' 'disk_backlog.mmcblk0' 'CLEAR' 'WARNING' '614' '1146' '68@/etc/netdata/health.d/disks.conf' '60' '120'' on pid 14255.
I cannot send emails - there is no sendmail command available.
/usr/libexec/netdata/plugins.d/alarm-email.sh: line 12: : command not found
/usr/libexec/netdata/plugins.d/alarm-email.sh: FAILED to send notification email for CLEAR on 'disk_backlog.mmcblk0.10min_disk_backlog'
16-08-22 09:41:04: ERROR: netdata: child pid 14255 exited with code 1.
`

**Comment by ktsaou** [comment]
this is about alarms. Nothing to do with the dashboard.

Could you please download `dashboard.js` like this: `http://your.netdata:19999/dashboard.js`. Does it work?

**Comment by sevaho** [comment]
Yes that works, it is a a long file.


[dashboard.js.zip](https://github.com/firehol/netdata/files/429607/dashboard.js.zip)

**Comment by sevaho** [comment]
Well suddenly it worked, magic. Netdata needed to grab some data first before actually showing the dashboard?

**Comment by ktsaou** [comment]
no, I don't think so. Something else is happenning. Can you press Control-F5 on your browser to force a full reload of the page?

**Comment by sevaho** [comment]
It works and kept working, no more errors whatsoever, I did a reinstall and everything worked extraordinary. Nothing in the console or in the error logs.

Thank you for your help :)

**Comment by LucaDev** [comment]
If you open myserver.com/netdata it will not show correctly(because it can not load the js and css files), but if you open myserver.com/netdata/ it will.

**Comment by radvc** [comment]
Hi, I have the same problem, looking on the browser console dashboard.js not found.

**Comment by ktsaou** [comment]
> Hi, I have the same problem, looking on the browser console dashboard.js not found.

with a reverse proxy?

**Comment by radvc** [comment]
@ktsaou It's working now, I place the location /netdata before all locations
