### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by Vaiune** [firehol/netdata#82]
This is such an awesome project.
I would like to know if there would be support for postgresql charts like mysql has.
Are you planning to implement this in near future?

**Comment by ktsaou** [comment]
Yes, but getting likes on this will help me prioritize it. Another way is to help me.

You can help by deciding the charts needed to monitor this DB and the values/dimensions each chart will have (mapping them to the values already exposed by postgres). This is time consuming. I spent a day to build it for mysql (a lot of charts).

Also, if you can write shell scripts or javascript, I can help you write the whole plugin too.

**Comment by vnikitov** [comment]
Great! I think this enhancement will be a great advantage.
Also it would be cool to monitor also MySql graphs like:
MySQL Qcache Prunes
MySQL bufferpool hitrate
MySQL bufferpool log waits
MySQL bufferpool wait free
MySQL connection time
MySQL index usage
MySQL keycache hitrate
MySQL long running procs
MySQL open files
MySQL qcache hitrate
MySQL slow queries
MySQL threadcache hitrate
MySQL threads cached
MySQL threads connected
MySQL threads running
MySQL tmp disk tables

**Comment by ktsaou** [comment]
Please open a new issue for mysql (I'll be lost). I also plan to re-write the mysql collector in node.js to lower its resource usage when set to per second collection.

**Comment by ktsaou** [comment]
@paulfantom this one may require another python dependency. Do you know which one?

**Comment by paulfantom** [comment]
Currently I don't have enough knowledge about PostgreSQL monitoring to write a module, but I will get there.
But I think you are right, this will need another python dependency and I cannot tell right now which one.

**Comment by gnedev** [comment]
Guys I like your project and as I am going to write some enhancement, maybe this PostgreSQL monitoring could be my first activity.
If you agree, has some advices or recommendations we will be in touch.

**Comment by ktsaou** [comment]
@gnedev perfect!
In which language you plan to do this?

**Comment by gnedev** [comment]
I can do it in any language.
Depends on your point of view for better project consistency and common use of technologies.
So far shell scripting, python and perl should be enough. However if C or C++ is needed it will be included. First target is to implement plugin and to see it is working. After that to look if there is some bottleneck on performance and to tune it. It is monitoring service should be very lightweight as process.
That's why I asked if you have some advices, based on your experience, in order to decrease iterations to get it accomplished.

**Comment by ktsaou** [comment]
I would start with python. Python is pretty descent. Node.js is faster. Bash is simpler, but not resource efficient.

If you can do it in python, you can check the mysql plugin: https://github.com/firehol/netdata/blob/master/python.d/mysql.chart.py

@paulfantom has done a great job to optimize the python base classes and it is now very well suited for most modules. However the CPU resources used for collecting data from a db, per second, depends heavily on the python library you are going to use. In mysql, for example, `python-mysqldb` is 10 times faster than `pymysql` (the later is a pure python implementation, while the former is a C library with python bindings - thus the difference). Check our discussion of mysql here: https://github.com/firehol/netdata/pull/555

Of course, C is the best solution, but I wouldn't advice you to start with it.

**Comment by DrGkill** [comment]
A good start point would be to use pgcenter. It gives lots of information real time and is coded in C. Very fast and low CPU/RAM footprint : 

```
    %cpu:  0.1 us,  0.0 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st                              activity:  6 total,  5 idle,  0 idle_in_xact,  1 active,  0 waiting,  0 others
 MiB mem:  64516 total,  52749 free,    216 used,    11551 buff/cached                                      autovacuum:  0/3 workers/max,  0 manual,  0 wraparound, 00:00:00 vac_maxtime
MiB swap:    974 total,    974 free,      0 used,      0/0 dirty/writeback                                  statements:   0 stmt/s,  0.000 stmt_avgtime, 00:00:00 xact_maxtime

datname        commit  rollback  reads  hits  returned  fetched  inserts  updates  deletes  conflicts  deadlocks  tmp_files  tmp_bytes  read_t  write_t
winergia       0       0         0      0     0         0        0        0        0        0          0          0          0          0       0
```

**Comment by DrGkill** [comment]
Another good source for netdata would be the munin plugins here : 
https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/

**Comment by ktsaou** [comment]
Cleaning up day. This is implemented, thanks to @facetoe, so we can close it.

Thank you @facetoe !
