### ISSUE TITLE
MySQL error when importing SimpleService

### ISSUE THREAD

**Issue by Kharag** [firehol/netdata#821]
Hey,

I tried configuring the MySQL Module but it won't run.
I'm using the GIT version.

Calling it via debug gives the following error:

    # /usr/libexec/netdata/plugins.d/python.d.plugin mysql debug

    16-08-22 17:17:13:  INFO: Using python v3
    16-08-22 17:17:13: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
    16-08-22 17:17:13: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/',       CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
    16-08-22 17:17:13: python.d ERROR: Problem loading mysql cannot import name 'SimpleService'
    16-08-22 17:17:13: python.d FATAL: no modules found.
    DISABLE

The nginx or postfix modules run without problems..

Tell me if I can provide more info!

**Comment by ktsaou** [comment]
strange!
@paulfantom any ideas?

**Comment by paulfantom** [comment]
@Kharag what is your python version (`python3 --version`) and operating system (`cat /etc/os-release`)?

Also if you could edit file `/usr/libexec/netdata/plugins.d/python.d.plugin` and change line line 130:
```py
            msg.error("Problem loading", name, str(e))
```
to:
```py
            import traceback
            msg.error("Problem loading", name, str(e))
            print(traceback.format_exc())
```
then rerun `/usr/libexec/netdata/plugins.d/python.d.plugin mysql debug` and post output.

**Comment by Kharag** [comment]
Hello,

of course:

    # python3 --version
    Python 3.4.5

    # cat /etc/redhat-release 
    CentOS release 6.8 (Final)

And here is the trace:

    # /usr/libexec/netdata/plugins.d/python.d.plugin mysql debug
    16-08-22 21:14:51:  INFO: Using python v3
    16-08-22 21:14:51: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
    16-08-22 21:14:51: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/',  CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mysql']
    Traceback (most recent call last):
    File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 125, in _import_module
    return importlib.machinery.SourceFileLoader(name, path).load_module()
    File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
    File "<frozen importlib._bootstrap>", line 1614, in load_module
    File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 1220, in load
    File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1129, in _exec
    File "<frozen importlib._bootstrap>", line 1471, in exec_module
    File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
    File "/usr/libexec/netdata/python.d/mysql.chart.py", line 5, in <module>
    from base import SimpleService
    ImportError: cannot import name 'SimpleService'

    16-08-22 21:14:51: python.d ERROR: Problem loading mysql cannot import name 'SimpleService'
    16-08-22 21:14:51: python.d FATAL: no modules found.

**Comment by paulfantom** [comment]
Could you also show output of `/usr/libexec/netdata/plugins.d/python.d.plugin nginx debug` (first ~30 lines)?

**Comment by Kharag** [comment]
hmm I see now that I'm apparently not using the nginx module?
But I definitely edited the python-nginx config file and it loaded..
And I get live data ?

    # /usr/libexec/netdata/plugins.d/python.d.plugin nginx debug
    16-08-22 22:06:08:  INFO: Using python v3
    16-08-22 22:06:08: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
    16-08-22 22:06:08: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/',       CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['nginx']
    Traceback (most recent call last):
    File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 125, in _import_module
    return importlib.machinery.SourceFileLoader(name, path).load_module()
    File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
    File "<frozen importlib._bootstrap>", line 1614, in load_module
    File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 1220, in load
    File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1129, in _exec
    File "<frozen importlib._bootstrap>", line 1471, in exec_module
    File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
    File "/usr/libexec/netdata/python.d/nginx.chart.py", line 5, in <module>
    from base import UrlService
    ImportError: cannot import name 'UrlService'

    16-08-22 22:06:08: python.d ERROR: Problem loading nginx cannot import name 'UrlService'
    16-08-22 22:06:08: python.d FATAL: no modules found.

**Comment by paulfantom** [comment]
It looks like you have other python module named `base.py` which is taking precedence over `/usr/libexec/netdata/python_modules/base.py`. 
I'm curious if changing line 27 in `python.d.plugin` from:
```py
sys.path.append(MODULES_DIR + "python_modules")
```
to
```py
sys.path.insert(1, MODULES_DIR + "python_modules")
```
will fix this issue.

You can have data from bash modules. Check `/var/log/netdata/error.log`.

**Comment by paulfantom** [comment]
Could you also give output of:
```sh
grep "Using python" /var/log/netdata/error.log
```

**Comment by Kharag** [comment]
Ah now this is interesting:
16-08-22 22:24:48:  INFO: Using python v2

While the script itself uses python3..

But i can confirm your fix:
If I edit the lines, both plugins run without error.

**Comment by paulfantom** [comment]
One more thing. Could you revert to `sys.path.append(MODULES_DIR + "python_modules")`, remove all files ending with **`*.pyc`** in `/usr/libexec/netdata/` and its subfolders. Then run `/usr/libexec/netdata/plugins.d/python.d.plugin mysql debug`?

**Comment by paulfantom** [comment]
Also we are using this hacky shebang to detect proper python version:
```
#!/usr/bin/env bash
'''':; exec "$(command -v python || command -v python3 || command -v python2 || echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
```
Maybe you have aliased `python` to `python3` somewhere? This way by running `python.d.plugin` in interactive shell you are using `python3`, but when netdata runs it, there is no alias, and it is using `python` symlinked to `python2`.

**Comment by Kharag** [comment]
I checked, and there is an alias in /usr/local/bin, to which the bash cmd also points.
Without the alias, everything checks out and runs fine.

I wonder what i broke by removing the alias :)

**Comment by paulfantom** [comment]
I am closing this. If you will have more problems, go on and ask, we'll be happy to help.
