### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by davistan** [firehol/netdata#826]
Hi, just a suggestion to improve notifications.

It will be nice to be able to send health alerts or any important notifications via telegram. I found a CLI that can be used - https://github.com/vysheng/tg

Thanks and keep up this great project!

**Comment by ktsaou** [comment]
what a nice idea!

I want to propagate alarms to a central netdata before adding such integrations. A central place will allow us to configure all these just once, on one server, instead of every server (the cli command you sent requires your key).

Also, I hope I could build a public, global health monitoring server (like the registry) where users that are not willing to setup their own, will be able to use one by just installing netdata on one server. This public global health monitoring server could be a telegram bot, so keys will be required from you.

**Comment by ktsaou** [comment]
too early in the morning... my response had typos, so I edited it.

**Comment by davistan** [comment]
Yes, that sounds like a good plan. The key can be stored in a config file as this is similar to email settings in a way.

**Comment by LucaDev** [comment]
Wow, thats a great idea! Telegram would make things a lot easier!

**Comment by ktsaou** [comment]
I just found this one: https://www.pushbullet.com/
Seems nice too.

**Comment by ktsaou** [comment]
This is also interesting: https://github.com/dschep/ntfy

**Comment by davistan** [comment]
Thanks @ktsaou for the ntfy suggestion. This looks much better as it can support various backends. If this can be added, then this means that netdata can support notifications to whole lot more of options apart from email only.

**Comment by ktsaou** [comment]
> Thanks @ktsaou for the ntfy suggestion. This looks much better as it can support various backends. If this can be added, then this means that netdata can support notifications to whole lot more of options apart from email only.

It is very simple to run anything you like. netdata executes `alarm-email.sh` found in the plugins directory. You can change it to anything you like via `netdata.conf` option `script to execute on alarm`. So, create a script that accepts the same parameters as `alarm-email.sh` to do whatever you like. A  wrapper for `ntfy` is pretty simple and straightforward.

**Comment by Splo0sh** [comment]
> It is very simple to run anything you like. netdata executes `alarm-email.sh` found in the plugins directory. You can change it to anything you like via `netdata.conf` option `script to execute on alarm`. 

@ktsaou how would I set the default alarm in the `netdata.conf` exactly?
At the moment I'm adding `exec: /path/to/alarm.sh` to every alarm I want to use.

**Comment by ktsaou** [comment]
Here it is:

```
[health]
	# enabled = yes
	# health configuration directory = /etc/netdata/health.d
	# script to execute on alarm = /usr/libexec/netdata/plugins.d/alarm-email.sh
	# in memory max health log entries = 1000
	# run at least every seconds = 10
```

Uncomment and set `script to execute on alarm`.

Check also #915 . It seems good too...

**Comment by Splo0sh** [comment]
I was/am not able to find that section in my `netdata.conf`, that's why I had to ask. I just updated to the latest build again to be sure.
`cat /etc/netdata/netdata.conf| grep health` shows nothing. But I will add it manually. Thank you very much.

**Comment by ktsaou** [comment]
You can get the running `netdata.conf` with `http://your.netdata:19999/netdata.conf`.

**Comment by ktsaou** [comment]
FYI: I have added pushover.net and slack.com notifications already in `emails-notify.sh`.

![image](https://cloud.githubusercontent.com/assets/2662304/18409570/b37f2c44-7752-11e6-92d1-3d6d79900ac6.png)

**Comment by Splo0sh** [comment]
@ktsaou, works like a charm 👍
