### ISSUE TITLE
Frequent ACPI errors in dmesg ring buffer

### ISSUE THREAD

**Issue by ewwhite** [firehol/netdata#827]
On my RHEL/CentOS physical systems (HP ProLiant), the latest commit generates a stream of the following message in the `dmesg` output. 

    ACPI Error (psparse-0537): Method parse/execution failed [\_SB_.PMI0._PMM] (Node ffff88061b24d650), AE_AML_BUFFER_LIMIT
    ACPI Exception: AE_AML_BUFFER_LIMIT, Evaluating _PMM (20090903/power_meter-342)

This is new, and I'm not certain what the origin of the probe/message is. I've tried disabling the sensors charts with no success.

**Comment by ktsaou** [comment]
Can you disable all external plugins? edit `/etc/netdata/netdata.conf` find the `[plugins]` section and set all plugins to `no` except the `proc` one (uncomment the lines too). Does it still happen?

**Comment by ewwhite** [comment]
I've uncommented the lines and set all plugins to no, except for `proc`.   
I don't see the issue at the moment.

**Comment by ktsaou** [comment]
ok. this is good (it would be very strange if that was not the case).

I search around and found:

https://bugs.launchpad.net/ubuntu/+source/acpi/+bug/606999
https://www.novell.com/support/kb/doc.php?id=7010449
http://www.serveradminblog.com/2015/05/kernel-acpi-error-smbusipmigenericserialbus/

As I see it this is related to sensors.

@paulfantom is it possible that the sensors library is loaded even when the sensors plugin is disabled?

**Comment by ewwhite** [comment]
On HP servers, it's not necessary to use sensors since the HP has purpose-built tools for hardware monitoring. I never disabled sensors for netdata in the past, but it does seem like something is querying very frequently.

**Comment by ktsaou** [comment]
ok. i thought you disabled sensors.

1. comment out again the lines you uncommented in netdata.conf
2. edit `/etc/netdata/python.d.conf` and disable sensors (set `sensors: no` and uncomment it).

Does it happen now?

**Comment by ewwhite** [comment]
This is done. I reverted the changes and manually disabled sensors. 

I'm not seeing the issue now.

**Comment by ktsaou** [comment]
nice!

**Comment by literal** [comment]
I had the same problem on an HP server and there is a smarter solution found here: https://www.novell.com/support/kb/doc.php?id=7010449

Instead of disabling sensors in netdata altogether, you can just disable the acpi_power_meter kernel module, which doesn't work anyway on affected HP servers due to a BIOS bug. This way netdata can still get the temperature readings.

This is how you can disable the module immediately:
`sudo modprobe -r acpi_power_meter`

And this is how you make it permanent:
`sudo echo "blacklist acpi_power_meter" >> /etc/modprobe.d/hwmon.conf`

Solved the problem for me on an HP ProLiant DL180 running Debian 8.7.

**Comment by ktsaou** [comment]
@literal nice info! thanks!

**Comment by ktsaou** [comment]
I have added a note to documentation about this, diverting users to this issue for more help.

**Comment by Motophan** [comment]
Hi, really sorry to necro this, but is there a way to do this via docker? I dont have /etc/netdata/python.d.conf in the container when I add host:/docker/netdata container /etc/netdata/

**Comment by eXcalibre** [comment]
I run on HP hardware running 
Centos 8 
netdata v1.18.1 
and had this issue.
I change the sensor to "no" in 
/etc/netdata/conf.d/python.d.conf
Stopped all the horrid alerts.

thanks for this thread. and Netdata. :)
