### ISSUE TITLE
Disabled "Chart Legend" popup on hover

### ISSUE THREAD

**Issue by pavs** [firehol/netdata#829]
On default dashboard I can block this from setting, how do I block this on a custom dashboard?

Second question. Currently, I am using CSS `display: none` to achieve this look:

![screen shot 2016-08-24 at 12 09 45 am](https://cloud.githubusercontent.com/assets/3807064/17904000/5bb88120-698f-11e6-9260-46cd3007a4e0.png)

Is it possible to make a custom dashboard just with legend and no graph, if so how?

**Comment by ktsaou** [comment]
To disable help, before loading `dashboard.js` set this:

```js
var netdataShowHelp = false;
```

Check the top of `dashboard.js`. There are a few options there.

For your second question, I don't have an answer. I have not designed this to supported. Sorry.
