### ISSUE TITLE
Dygraph Value Range

### ISSUE THREAD

**Issue by willzfarmer** [firehol/netdata#832]
Is there any way to set the value range on dygraph plots? I'd love to set these cpu plots to have ymax=800 and the mem plots to have ymax=16*1024. I looked through the custom dashboard wiki but I couldn't find any documentation.

![image](https://cloud.githubusercontent.com/assets/546524/17912752/67fc4c86-694a-11e6-8136-f84d3b4c2173.png)

**Comment by ktsaou** [comment]
Yes you can. Set `data-dygraph-valueRange=[MIN, MAX]`, when `MIN` and `MAX` are the values you want for the y-axis.

Check it here: https://github.com/firehol/netdata/blob/e91f00d99f4965e985981b93fa46ef33f94dd726/web/dashboard.js#L3820

You can find more options just above and below that.

**Comment by ktsaou** [comment]
I edited my response. Use only small case letters.

**Comment by willzfarmer** [comment]
Awesome, thanks!

**Comment by willzfarmer** [comment]
Actually, can we add this to the documentation somewhere so other people can look at it as well?

**Comment by ktsaou** [comment]
I will do when I write the page about dygraphs in the wiki. This page is not there yet. I just enabled editing the wiki for anyone, so if you want to contribute this page, please do so...

**Comment by willzfarmer** [comment]
Yep, I made the page as a UNDER CONSTRUCTION page, and I'll add more to it as time goes on, but at least it's there now.

**Comment by willzfarmer** [comment]
https://github.com/firehol/netdata/wiki/Dygraph

**Comment by ktsaou** [comment]
nice, thanks!
