### ISSUE TITLE
Containers are missing with d9c264a7

### ISSUE THREAD

**Issue by agross** [firehol/netdata#833]
After updating yesterday night I found that containers no longer show up on the UI. Unfortunately, I cannot find entries related to cgroups in the error.log.

**Comment by ktsaou** [comment]
This is what I changed yesrday to prevent repeating errors when certain cgroup features are missing from the kernel: https://github.com/firehol/netdata/pull/830/files

Could you please run:

```
grep -i cgroup /var/log/netdata/error.log
```

and post the results?

**Comment by agross** [comment]
This is all that is logged upon starting netdata:

```
$ sudo tail -f /var/log/netdata/error.log | grep cgroup
   8   :16-08-24 12:58:04: INFO: netdata: Starting thread cgroups.
  13   :16-08-24 12:58:04: INFO: netdata: CGROUP Plugin thread created with task id 11685
  59   :16-08-24 12:58:05: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/cgroup-name.sh '_'' on pid 11815.
  60   :/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup '_' is called '_'
```

I notice the log contains: `Too many logs (201 logs in 25 seconds, threshold is set to 200 logs in 1200 seconds)` How to disable that?

**Comment by agross** [comment]
Found the setting. Logs don't change, though.

**Comment by ktsaou** [comment]
ok. I found the bug. Submitting a fix now.

**Comment by ktsaou** [comment]
and merged it.
Could you please pull it and check?

**Comment by agross** [comment]
Containers are back! :+1:

Many thanks!
