### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by jlec** [firehol/netdata#839]
Since the 1.2.0 release there have been so many good enhancements and bug fixes. Please cut a release.

**Comment by ktsaou** [comment]
It is planned for this weekend.

**Comment by ktsaou** [comment]
#782

**Comment by jlec** [comment]
Thanks @ktsaou. And obviously ALL CAPS THANKS for developing this thing. We are just deploying it in an HPC environment which just works perfect.

**Comment by ktsaou** [comment]
ok. 1.3.0 released, with health monitoring!
