### ISSUE TITLE
Mdadm(Software Raid) & SMART monitoring

### ISSUE THREAD

**Issue by LucaDev** [firehol/netdata#840]
I dont exactly know how mdadm and smart values could be displayed but charts are not suitable I guess

**Comment by ktsaou** [comment]
SMART is very chart friendly.
There is smartd, but I don't know if it provides an API.

For mdadm, I don't know.

**Comment by paulfantom** [comment]
If we can do some good SMART parsing, we could get rid of `hddtemp` since it basically reads SMART data.

**Comment by LucaDev** [comment]
I heard of [pySMART](https://pypi.python.org/pypi/pySMART) but its only a python wrapper for smartctl

**Comment by LucaDev** [comment]
I got it, you could parse /proc/mdstat for Mdadm stats

**Comment by ktsaou** [comment]
parse what?

```
$ cat /proc/mdstat
Personalities : [raid6] [raid5] [raid4] [raid0] [raid1] [raid10] [linear] [multipath] 
md125 : active raid1 sdc1[0] sdb1[5] sda1[4]
      52427704 blocks super 1.2 [3/3] [UUU]
      
md126 : active raid5 sdc2[0] sdb2[4] sda2[3]
      25162752 blocks super 1.2 level 5, 512k chunk, algorithm 2 [3/3] [UUU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md127 : active raid5 sdc3[0] sdb3[4] sda3[3]
      3777000448 blocks super 1.2 level 5, 512k chunk, algorithm 2 [3/3] [UUU]
      bitmap: 9/15 pages [36KB], 65536KB chunk

unused devices: <none>
```

There is nothing to chart...

**Comment by LucaDev** [comment]
You could chart the rebuilding process but that would need some sort of dynamic chart which is only visible if needed. It can also show if a device isn't synced and/or degraded, we dont really need charts for this but an alarm would be useful to have all my alarms in one place

**Comment by l2isbad** [comment]
Well i read the https://raid.wiki.kernel.org/index.php/Mdstat article and imho all we need for every raid is (I will consult with the sysadmins tomorrow)

**1. status - active or not**

Personalities : [linear] [raid0] [raid1] [raid5] [raid4] [raid6]
md0 : **active** raid6 sdf1[0] sde1[1] sdd1[2] sdc1[3] sdb1[4] sda1[5] hdb1[6]
      1225557760 blocks level 6, 256k chunk, algorithm 2 [7/7] [UUUUUUU]

**2. % of active devices in raid**

Personalities : [linear] [raid0] [raid1] [raid5] [raid4] [raid6]
md0 : active raid6 sdf1[0] sde1[1] sdd1[2] sdc1[3] sdb1[4] sda1[5] hdb1[6]
      1225557760 blocks level 6, 256k chunk, algorithm 2 **[7/7]** [UUUUUUU]

I dont understand why we need something other than just to parse /proc/net. 

```
In [5]: re.findall(r'(md[0-9]+) : ([a-z]+).*?((?<= \[)[0-9]+)/([0-9]+(?=\] ))', ' '.join(proc_stat.split()))
Out[5]: 
[('md125', 'active', '3', '3'),
 ('md126', 'active', '3', '3'),
 ('md127', 'active', '3', '3')]
```

Am i missing something?

**Comment by ktsaou** [comment]
@l2isbad I like your thinking...

**Comment by l2isbad** [comment]
ok. as i say i will consult a sysadmin guy tomorrow and will do a pr.
The plugin seem very simple and at the same time is a very important

**Comment by ktsaou** [comment]
> The plugin seem very simple and at the same time is a very important one

sure. We will need an alarm for it too...

**Comment by mkubenka** [comment]
@l2isbad Checkout Munin RAID plugin:

https://github.com/munin-monitoring/contrib/blob/master/plugins/disk/raid

**Comment by l2isbad** [comment]
@mkubenka 
https://github.com/firehol/netdata/pull/1489
![screenshot_20170104_173154](https://cloud.githubusercontent.com/assets/22274335/21635980/07ea502c-d2a4-11e6-9686-de91433cd726.png)

but I did not know about reshape..but it easily can be added
**reshape**|check|resync|recovery

**Comment by l2isbad** [comment]
Well yes, I definitely need to add 'reshape'. Thx.

**Comment by ktsaou** [comment]
I think we can close this now. If something is missing, just post.
