### ISSUE TITLE
nfacct plugin

### ISSUE THREAD

**Issue by umarmeo** [firehol/netdata#847]
Hello, I am trying to enable nfacct via ./configure --enable-plugin-nfacct but getting following error at the end.
checking for uint32_t... yes
checking for inline... inline
checking for sin in -lm... yes
checking for UUID... configure: error: Package requirements (uuid) were not met:

No package 'uuid' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables UUID_CFLAGS
and UUID_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Please guide what should I do? I have installed netdata on another server with same method and firewall option is enabled on that server by default. But on 2nd server It is not available so I tried to do this manually but getting the above error. 
Why it is not enabled on this server by default?

**Comment by ktsaou** [comment]
nfacct information can only be accessed by `root`. This is the reason it is not enabled. We have to re-write it as an external plugin.

If you enable it now, the whole netdata process tree, including the web server, will have to run as `root`.
When we rewrite it as an external plugin, only this component will run as `root` (or with more capabilities), much like the `apps.plugin` does.

In general the netdata daemon should not run as `root`. It is a web server, so it receives requests from the outside and serves them. Of course, there is no known security issue in netdata, even when it runs as `root`, but you should avoid it.

**Comment by umarmeo** [comment]
Thank you for your reply.
I am not an experienced user. Please guide me how to run netdata as root?

**Comment by ktsaou** [comment]
have you followed the installation guide to install it?

Here it is: https://github.com/firehol/netdata/wiki/Installation

Once installed, edit /etc/netdata/netdata.conf and set `run as user = root`. Uncomment the line too. Then restart netdata. It will run as root.

I strongly advise you not to do this though.

**Comment by umarmeo** [comment]
I have started it as you advice But i am getting following error on myserver:19999
Access to file '/usr/share/netdata/web/' is not permitted.

**Comment by umarmeo** [comment]
Its done.
Thank you
