### ISSUE TITLE
QoS graph doesn't show up 

### ISSUE THREAD

**Issue by drahti** [firehol/netdata#849]
I am not sure if this is actually a bug in the software, but as I followed the documentation on the wiki step by step there's probably at least an error over there.

So what I did. I first installed netdata, everything default.
Then I wrote a fireqos.conf that configures QoS for the device eth1 and applied it using fireqos start.
I verified it using fireqos status and restarted netdata expecting to see a QoS graph after a restart.

But the graph was missing.

Trying to identify the cause of the issue I checked the following:
tc-qos-helper.sh is running in the background
running tc-qos-helper.sh manually results in lots of output.

What can I do to get the graph to show up or what additional information do you need to narrow down the issue?

**Comment by ktsaou** [comment]
Do you have any errors in `/var/log/netdata/error.log`?
Which distro you run?

Please verify user `netdata` can get tc output. Do this:

```sh
# become root
sudo su

# become netdata
su netdata -s /bin/bash

# run tc-qos-helper.sh as netdata
/usr/libexec/netdata/plugins.d/tc-qos-helper.sh
```

Post a few lines of the last command.

**Comment by drahti** [comment]
Thanks a lot for the quick answer.
error.log has quite a few errors, but most of them relate to python.d and I believe none relate to tc. I've attached a log of the first couple of minutes after startup.

running the tc-qos-helper from the netdata user produces valid output (from what I can say) and I've attached it as well.

Right now it's running on a raspbian which is based on debian 8. That will be my target distribution as well, right now I'm just playing around from home.


[error.txt](https://github.com/firehol/netdata/files/441175/error.txt)
[tchelper.txt](https://github.com/firehol/netdata/files/441177/tchelper.txt)

**Comment by ktsaou** [comment]
I'll have to setup such an evnironmnet myself to see what is happening. QoS monitoring in netdata works in debian (all demo sites are debian based).

**Comment by drahti** [comment]
sure. thanks for all the effort.

If I can do anything to help you with this, please let me know!

**Comment by cytrinox** [comment]
I've the same problem (and log outputs) with current git master and debian stretch on ARM.
tc-qos-helper.sh is running in background but no charts visible.

**Comment by ktsaou** [comment]
I found the bug. I am making a PR now.

**Comment by ktsaou** [comment]
merged it.
It should be ok now.
