### ISSUE TITLE
"Guest" support

### ISSUE THREAD

**Issue by jonathanselea** [firehol/netdata#850]
Alright, first of all. Excuse me if this is already a feature. But I would like to see some sort of "control panel" where I can change what kind of graph should be shown to visitors accessing the site.

For example:
If I login via the webGUI as an admin I would have access to ALL information (if the netdata.conf file says so). But if "guest" visit the site she/he can only see thoose graph that I have specified to be accessible for "guests".

I know I can configure netdata to require a login very easy, but not as I suggested above.

**Comment by paulfantom** [comment]
First of all you cannot log in to netdata since it doesn't have authentication. What you could do is use some kind of reverse proxy (like nginx) and create [custom netdata dashboard](https://github.com/firehol/netdata/wiki/Custom-Dashboards) visible to "Guest" users.

**Comment by jonathanselea** [comment]
@paulfantom 
I currently used apache as a reverse proxy and it works flawless. 
Did'nt really think far enough (or not at all) if your simple solution, thanks for the idea!
