### ISSUE TITLE
NIC dropped packets

### ISSUE THREAD

**Issue by tx7** [firehol/netdata#853]
Hi,

Netdata reporting that my bond0 is dropped 31 packets within the 30 mins.
I wonder if that has to do with my current network settings: sudo ethtool -K bond0 tso off gso off gro off lro off

I'm using the above settings so that my system can hibernate properly.

Thanks.

**Comment by ktsaou** [comment]
I am sorry I can't help you with that. I wouldn't care too much if this is not a server.

**Comment by ktsaou** [comment]
I found this: https://access.redhat.com/sites/default/files/attachments/20150325_network_performance_tuning.pdf

It has all the background information regarding packets dropped and how-to to fix them. Each case is different, so you have to try it.

**Comment by ktsaou** [comment]
Also, the current version of netdata has alarms that for issues that cause packet drops (so that you can fix them).

**Comment by Tronic69** [comment]
I just wonder how netdata gets the values for that 1hour_packet_drops_* instances.
I got alarms for 1hour_packet_drops_inbound aprox every hour for <60 dropped packets and I checked the ratio which is 0.05 percent dropped of all packets. So, I don't think there is any problem.

**Comment by ktsaou** [comment]
> I just wonder how netdata gets the values for that 1hour_packet_drops_* instances.

netdata reads `/proc/net/dev` on Linux. This file has packet drops inbound and outbound per network interface.
