### ISSUE TITLE
Temperature graph does not show up

### ISSUE THREAD

**Issue by emansih** [firehol/netdata#858]
hey, i tried to monitor my temperature using this tool, however, i can't seem to find the temperature chart even though temperature plugin is supported. i am running this on a raspberry pi.I noticed you used lm-sensors, however it does not work with raspberry pi. 

_cat /sys/class/thermal/thermal_zone0/temp_
 
does work though.

**Comment by paulfantom** [comment]
Can you test if `sensors` command give you temperature reading from your sensor?

**Comment by emansih** [comment]
`$ sensors`
`No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.`

`$ sudo sensors-detect`
# sensors-detect revision 6209 (2014-01-14 22:51:58 +0100)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): yes
modprobe: FATAL: Module cpuid not found.
Failed to load module cpuid.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Lastly, we can probe the I2C/SMBus adapters for connected hardware
monitoring devices. This is the most risky part, and while it works
reasonably well on most systems, it has been reported to cause trouble
on some systems.
Do you want to probe the I2C/SMBus adapters now? (YES/no): yes
Sorry, no supported PCI bus adapters found.

Next adapter: bcm2708_i2c.1 (i2c-1)
Do you want to scan it? (YES/no/selectively): yes
Client found at address 0x1b
Handled by driver `snd_soc_tas5713' (already loaded), chip type `tas5713'
    (note: this is probably NOT a sensor chip!)

Sorry, no sensors were detected.
Either your system has no sensors, or they are not supported, or
they are connected to an I2C or SMBus adapter that is not
supported. If you find out what chips are on your board, check
http://www.lm-sensors.org/wiki/Devices for driver status.

**Comment by paulfantom** [comment]
You have your answer. Since netdata uses `lm-sensors` and they cannot find your sensor it is impossible for netdata to plot temperature graph.

**Comment by emansih** [comment]
yea, like i said in my first post, "I noticed you used lm-sensors, however it does not work with raspberry pi. cat /sys/class/thermal/thermal_zone0/temp

does work though."

**Comment by paulfantom** [comment]
Ok, I don't know what do you expect us to do.

If sensor is not detected by lm-sensors package, then netdata cannot use it. Basically you have two options:
1. Find how to force lm-sensors to detect your device
2. Write your own netdata module to periodically read data from `/sys/class/thermal/thermal_zone0/temp`.

**Comment by ktsaou** [comment]
The old BASH module can be used for this.

To enable the old BASH module do these:

1. Disable sensors for python.d.plugin by editing `/etc/netdata/python.d.conf` and setting `sensors: no`.
2. Enable sensors for charts.d.plugin by editing `/etc/netdata/charts.d.conf` and setting `sensors=force`.

**Comment by ktsaou** [comment]
@paulfantom I discussed this issue with @emansih on reddit. I asked him to open a github issue.

**Comment by ktsaou** [comment]
@emansih did you manage to do it?

**Comment by emansih** [comment]
oh hey, sorry I wasn't online yesterday. Yea, i tried what you told me but temperature is still not showing up

**Comment by paulfantom** [comment]
@emansih Can you execute this command and post output:
```sh
find /sys -maxdepth 11 -name \*_input -o -name temp
```

**Comment by emansih** [comment]
$ find /sys -maxdepth 11 -name \*_input -o -name temp
/sys/devices/virtual/thermal/thermal_zone0/temp
find: `/sys/kernel/debug': Permission denied

$ sudo find /sys -maxdepth 11 -name \*_input -o -name temp
[sudo] password for daniel:
/sys/devices/virtual/thermal/thermal_zone0/temp

**Comment by ktsaou** [comment]
Strange.

on my raspbian 7:

```sh
# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

# su netdata -s /bin/bash
netdata@pi1:/root$ cd
netdata@pi1:/$ find /sys -maxdepth 11 -name *_input -o -name temp -exec ls -l {} \;
-r--r--r-- 1 root root 4096 Sep  2 11:23 /sys/devices/virtual/thermal/thermal_zone0/temp

```

I don't have a raspbian 8 to test.

**Comment by emansih** [comment]
yikes, i followed @paulfantom command without a ;

```
$ find /sys -maxdepth 11 -name *_input -o -name temp -exec ls -l {} \;
-r--r--r-- 1 root root 4096 Sep  1 19:43 /sys/devices/virtual/thermal/thermal_zone0/temp
find: `/sys/kernel/debug': Permission denied
$ sudo !!
sudo find /sys -maxdepth 11 -name *_input -o -name temp -exec ls -l {} \;
[sudo] password for daniel:
-r--r--r-- 1 root root 4096 Sep  2 14:21 /sys/devices/virtual/thermal/thermal_zone0/temp

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**Comment by ktsaou** [comment]
Did you solve it?

With a fresh installation of netdata on a pi I edited `/etc/netdata/charts.d.conf` and uncommented `sensors = force`.

Restarted netdata and I got this:

![image](https://cloud.githubusercontent.com/assets/2662304/18688762/6d753ccc-7f8e-11e6-9c46-7844129db0ac.png)

**Comment by emansih** [comment]
sorry for the super late reply, it works for me now. thanks!
