### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by pjlegato** [firehol/netdata#86]
As far as I can tell, all metrics are reset to zero when netdata is restarted.

It'd be nice to have optional disk persistence, so you could do things like look at historic data from several days ago to debug something.

**Comment by cbricart** [comment]
...which additionally emphasizes my question what `$NETDATA_PREFIX/var/cache/` is for after all..
it's not mentioned about anywhere in the "docs" - even contrary to the docs stating »there's any disk I/O apart from the buffered logging«

**Comment by ktsaou** [comment]
When netdata exits, it saves all data to `/var/cache/netdata`. When you restart it, it loads these data and continues, showing a small gap at the charts for the time it was not running.

If yours is not doing this, it could be because it cannot write to it. This directory should be owned by user `netdata`.

You can also check `/var/log/netdata/error.log` for errors during exit.

Persistent storage is needed though. I agree.

**Comment by cbricart** [comment]
is it really *needed* or rather _nice to have it, if supported_ ..? (<- runtime-wise)
personally, I would even prefer to put it on some `tmpfs` or make it even disable-able per config if the user wants it

**Comment by ktsaou** [comment]
well, this is what I am thinking would be nice:

For an hour data of 1.000 dimensions, we need about 15MB. If we compress this, it can become around 7-8 MB.

We can save them hourly in chunks of 100 dimensions every minute. This is less than 1MB per minute.

Reading it would only be necessary when you zoom out on this area of the charts, and this would only read the specific dimensions you need - not everything.

How does that sound?

**Comment by pjlegato** [comment]
Ah, I see. The docs do give the impression that it has no persistence at all (e.g. "no disk I/O other than logging".)

@cbricart A seperate "long term persistence" module that collects and saves the stream to disk would be a fine solution. Then it could be on a seperate host so as to not affect disk I/O on the target host, or also run on localhost if disk I/O is not an issue.

**Comment by ktsaou** [comment]
> make it even disable-able per config

of course!

**Comment by ktsaou** [comment]
> A seperate "long term persistence" module that collects and saves the stream to disk would be a fine solution.

I think of a thread specific for this purpose.

**Comment by ktsaou** [comment]
> no disk I/O other than logging

during runtime yes, this is the case. Where did you find it, to update it a bit?

**Comment by cbricart** [comment]
https://github.com/firehol/netdata/wiki
»3. Once started, it does not use any disk I/O, apart its logging (check Log Files).«

**Comment by ktsaou** [comment]
thanks! updated both.

**Comment by pjlegato** [comment]
It wouldn't be able to run on a different machine if it's just a thread.

My use case, for example, is for database servers. On high traffic database servers, they need all the disk I/O bandwidth they can get.

This could be partially mitigated by using something like ionice. And I suppose it would not be difficult to break the thread out into a seperate process later...

BTW, thanks for your work -- the graphs are beautiful!

**Comment by ktsaou** [comment]
@pjlegato netdata now supports backends: graphite and opentsdb. So, I think we can consider this fixed.
