### ISSUE TITLE
Atomic operations detections fails on OpenWRT/LEDE

### ISSUE THREAD

**Issue by diizzyy** [firehol/netdata#860]
https://github.com/firehol/netdata/commit/db787ff47f80740ae266e0e347a6b49b3a395c35

After this commit netdata fails to compile using the LEDE-project toolchain.

`global_statistics.o: In function `finished_web_request_statistics':
global_statistics.c:(.text+0x90): undefined reference to `__atomic_compare_exchange_8'
global_statistics.c:(.text+0xc8): undefined reference to `__atomic_fetch_add_8'
global_statistics.c:(.text+0xe0): undefined reference to `__atomic_fetch_add_8'
global_statistics.c:(.text+0xf8): undefined reference to `__atomic_fetch_add_8'
global_statistics.c:(.text+0x110): undefined reference to `__atomic_fetch_add_8'
global_statistics.c:(.text+0x128): undefined reference to `__atomic_fetch_add_8'
global_statistics.o:global_statistics.c:(.text+0x140): more undefined references to `__atomic_fetch_add_8' follow
global_statistics.o: In function `global_statistics_copy':
global_statistics.c:(.text+0x3a4): undefined reference to `__atomic_compare_exchange_8'
collect2: error: ld returned 1 exit status
Makefile:575: recipe for target 'netdata' failed
make[6]: *** [netdata] Error 1
`

**Comment by ktsaou** [comment]
interesting...

to overcome the error, run the installer like this:

```sh
CFLAGS="-DNETDATA_NO_ATOMIC_INSTRUCTIONS=1" ./netdata-installer.sh
```

It should do it by itself (https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/src/common.h#L63-L65). If you know a better way of detecting this, please let me know.

The above will disable the atomic instructions and use pthreads locks instead. You can also avoid the overheads of the locks if you use the single threaded web server in netdata (suggested for IoT). To enable the single threaded web server, set `multi threaded web server = no` in `netdata.conf` (also uncomment the line).

**Comment by diizzyy** [comment]
Thanks for the quick reply, I'll poke around a bit and see how it can be fixed.

**Comment by diizzyy** [comment]
It's a band-aid fix but it works for now. No idea how to detect this any better right now.
https://github.com/openwrt/packages/pull/3109/files

**Comment by ktsaou** [comment]
ok. I am closing this.

**Comment by ktsaou** [comment]
@alonbl I am trying to find a better way to detect if the compiler supports `__atomic_fetch_add`, `__atomic_fetch_sub` and `__atomic_compare_exchange`.

I use them as an optimization to avoid pthreads locks in certain places, like this: https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/src/global_statistics.c#L23-L57

I have seen examples that such atomic operations can be detected by autoconf: https://chromium.googlesource.com/chromiumos/third_party/gcc/+/foo-test/libatomic/acinclude.m4#89 but I am confused.

I already do is this: https://github.com/firehol/netdata/blob/020a100fd41a1859a2d0b9e26c8f4edb2fe2e872/src/common.h#L63-L65, but it seems it fails on certain cases (I guess cross-compiling).

Have you ever seen a way to have autoconf detect these properly?

Thanks!

**Comment by alonbl** [comment]
Hello,

All macro conditionals should be removed from common.h and moved to
autoconf.

To test if a function exists you should use:

          AC_LINK_IFELSE([AC_LANG_CALL([], [function])],
            [action-if-found], [action-if-not-found])

Or use AC_LANG_PROGRAM if these are builtin.

To define size_t use:

          AC_TYPE_SIZE_T


To determine the size of size_t use an check for ac_cv_sizeof_size_t:

          AC_CHECK_SIZEOF([size_t])

Alternative you can check the size of void*
Not sure what RUSAGE_THREAD is used for, but principal is the same.
Not sure if you actually use GCC_VERSION, must not be used for anything but
debug display string.

Regards,
Alon

**Comment by ktsaou** [comment]
@diizzyy in PR #1028 I have implemented a new way of detecting `__atomic_X` operations. Is it possible to test it if it works now without defining the `NETDATA_NO_ATOMIC_INSTRUCTIONS`?

I've retained `DNETDATA_NO_ATOMIC_INSTRUCTIONS` in it, so please remove this variable from your `./configure` line before testing it.

**Comment by diizzyy** [comment]
I'll have a look at this tomorrow, thanks!

**Comment by ktsaou** [comment]
Thanks! I have merged it. So just get the repo as usual.

**Comment by diizzyy** [comment]
Unfortunately it still gives you the same error as before.
Master branch  901343a

**Comment by ktsaou** [comment]
Have you run `./autogen.sh` and `./configure ...` again?

**Comment by diizzyy** [comment]
As far as I can tell yes

http://projects.pyret.net/dump/netdata-build.txt

**Comment by ktsaou** [comment]
ok, my bad.
I just pushed a commit to fix it.
Could you please retry?

**Comment by diizzyy** [comment]
Fixed, thanks!
