### ISSUE TITLE
python mysql exception

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#861]
```
Exception in thread reporting:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/base.py", line 166, in run
    time.sleep(self.timetable['next'] - time.time())
IOError: [Errno 22] Invalid argument

```

```
# python --version
Python 2.6.5
```

This is an old ubuntu machine. It monitors 2 databases. Once works, the other reports this error.

cc: @paulfantom

**Comment by ktsaou** [comment]
I restarted netdata and suddenly, it works.
Any ideas what is this?

**Comment by paulfantom** [comment]
I really don't know. Those lines should be well tested by now. So maybe it is related to python version.

> Python 2.6.5

I'm curious, is it ubuntu 10.04?

**Comment by ktsaou** [comment]
yes it is, but I cannot update it soon.
