### ISSUE TITLE
installation failure on centos 5

### ISSUE THREAD

**Issue by jewes** [firehol/netdata#864]
error:

web_server.c: In function 'accept4':
web_server.c:42: error: 'O_CLOEXEC' undeclared (first use in this function)
web_server.c:42: error: (Each undeclared identifier is reported only once
web_server.c:42: error: for each function it appears in.)

**Comment by ktsaou** [comment]
thanks for reporting this.
The fix will be merged with PR #865

**Comment by ktsaou** [comment]
merged
