### ISSUE TITLE
logrotate is having issues

### ISSUE THREAD

**Issue by jurgenhaas** [firehol/netdata#866]
The error messages that I'm receiving from Ubuntu 14.04 hosts are these:

```
/etc/cron.daily/logrotate:
error: error setting owner of /var/log/netdata/access.log.1 to uid 999 and gid 999: Operation not permitted
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

The file listing looks like this:

```
ll /var/log/netdata/
total 13M
-rw-r--r-- 1 netdata netdata 1.1M Aug 31 08:19 access.log
-rw------- 1 netdata netdata    0 Aug 31 07:35 access.log.1
-rw------- 1 netdata netdata   20 May 22 09:35 access.log.10.gz
-rw------- 1 netdata netdata   20 May 21 09:35 access.log.11.gz
-rw------- 1 netdata netdata   20 May 20 09:35 access.log.12.gz
-rw------- 1 netdata netdata   20 May 19 09:35 access.log.13.gz
-rw------- 1 netdata netdata   20 May 18 09:35 access.log.14.gz
-rw------- 1 netdata netdata   20 May 29 09:35 access.log.3.gz
-rw------- 1 netdata netdata   20 May 28 09:35 access.log.4.gz
-rw------- 1 netdata netdata   20 May 27 09:35 access.log.5.gz
-rw------- 1 netdata netdata   20 May 26 09:35 access.log.6.gz
-rw------- 1 netdata netdata   20 May 25 09:35 access.log.7.gz
-rw------- 1 netdata netdata   20 May 24 09:35 access.log.8.gz
-rw------- 1 netdata netdata   20 May 23 09:35 access.log.9.gz
-rw-r--r-- 1 netdata netdata    0 May 12 17:29 debug.log
-rw-r--r-- 1 netdata netdata  12M Aug 31 08:22 error.log
```

Note, I had the error previously as well and had deleted access.log.1 and access.log.1.gz manually just to see if that made any difference then. It didn't.

So it appears that the access.log.1 is being created but doesn't contain access.log - instead it has zero length.

Looking at the timestamps, this might have worked until May 31st but fails ever since. I didn't notice before because I only forwarded system mails when testing alarms - my bad.

**Comment by jurgenhaas** [comment]
I have just checked, the uid and gid of netdata is indeed 999, so that shouldn't be an issue.

THe directory is owned by netdata as well and the mode is 755.

**Comment by ktsaou** [comment]
I am not an expert on this. On my servers this seems to be working fine.

@paulfantom any ideas?

**Comment by paulfantom** [comment]
On mine log rotation also work.

@jurgenhaas which netdata version is used on this server? 

I have also checked if netdata logrotate file was changed since May, but it hasn't. Only thing we changed was signal handling ( probably @ktsaou knows more about it).

However I think there is one workaround. Add this line to `/etc/logrotate.d/netdata` (somewhere between parenthesis):
```
su netdata netdata
```

**Comment by jurgenhaas** [comment]
@paulfantom I'm running on master branch of netdata and I looked around on my various hosts that all run Ubuntu 14.04 but got installed at different times. They come with different versions of `/etc/logrotate.d/netdata` and it looks like the installed is only creating that file once when initially installed and doesn't ever update. That's fair enough, as I deploy with Ansible I can also create my own logrotate script once I found out how that should look like to properly work.

That's maybe something that should be documented, that admins should check their logrotate scripts. This is because they don't seem to be tailored towards OS specifics, e.g.

- they call `/sbin/service netdata try-restart` which has 2 problems in my case: (1) `/sbin/service` doesn't exist (it's `/usr/sbin/service`) and (2) the option `try-restart` doesn't exist either.
- according to the comment in that file, the line `su netdata` should be commented out if netdata is included in init.d which is true in my case
- in one of the versions I found `if service netdata status > /dev/null ; then service netdata restart > /dev/null; fi;` where the `if` statement never seems to be treu because of the pipe to /dev/null

Maybe the installer could generate OS specific logrote script?

**Comment by ktsaou** [comment]
The problem is to find what each OS and version needs.
If we can find this info and conclude that different OSes need different logrotate configuration, sure this is the way to go.

Did you manage to make it work? What did you do?

The latest version of the logrotate config uses this:

```sh
/bin/kill -HUP `pidof netdata 2>/dev/null` 2>/dev/null || true
```

which I think is pretty generic. SIGHUP instructs netdata to re-open the config files.

**Comment by jurgenhaas** [comment]
I went for this:

```
/var/log/netdata/*.log {
  daily
  missingok
  rotate 14
  compress
  delaycompress
  notifempty
  sharedscripts
  create 640 netdata netdata
  postrotate
    /usr/sbin/service netdata restart >/dev/null
  endscript
}
```

and haven't seen any issues so far, but let's see what happens within the next 24 hours.

Do you reckon I should replace the service restart with the kill -HUP version?

**Comment by jurgenhaas** [comment]
It's looking good, logrotate seems to be working on all the hosts now without further warnings.

**Comment by ktsaou** [comment]
nice. I see that your version compared to the one shipped with netdata (https://github.com/firehol/netdata/blob/master/system/netdata.logrotate.in) has the following differences:

1. yours has `create 640 netdata netdata`, while the stock version has `create 0664 netdata netdata`.

2. yours has `/usr/sbin/service netdata restart >/dev/null` while the stock version has:

  ```
/bin/kill -HUP `pidof netdata 2>/dev/null` 2>/dev/null || true
```


If we keep the `postrotate` of the stock version, I think we can ommit the `create` line completely. netdata will create the log files after receiving the HUP signal.

So, could you please check that the `postrotate` script of the stock version works for you, with the `create` line removed?

**Comment by jurgenhaas** [comment]
OK, I'll give that a try and report back.

**Comment by jurgenhaas** [comment]
Right, this is now working correctly on all my hosts. So the above logrotate configuration with your suggested changes seems to be the right way to go and this isuue could then be closed.

**Comment by ktsaou** [comment]
So, we just need to remove the create line. Right?

**Comment by jurgenhaas** [comment]
That's correct.

**Comment by ktsaou** [comment]
in PR #890
