### ISSUE TITLE
Will this support windows system?

### ISSUE THREAD

**Issue by crazy-canux** [firehol/netdata#871]
Can I use any protocal or  agent to monitor windows server?

**Comment by ExoticChicken** [comment]
Nope This is For Linux Only.
Maybe in the future but i doubt it

**Comment by crazy-canux** [comment]
ok

**Comment by rajgomase24** [comment]
will this work for other unix platform like AIX, HP-UX solaris etc.

**Comment by ktsaou** [comment]
It should compile and run on any Unix system, but data collection from the system is currently implemented for Linux, FreeBSD and MacOS. Data collection from applications should work anywhere there is python, bash v4+, node.js.

**Comment by rajgomase24** [comment]
Thanks for detail.
