### ISSUE TITLE
python.d postfix error

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#878]
On gentoo I get this:

```
16-09-03 03:24:30: python.d ERROR: postfix_local Something wrong:  [Errno 32] Broken pipe
16-09-03 03:24:30: python.d FATAL: no more jobs
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 533, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 528, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 409, in update
    msg.fatal("no more jobs")
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 72, in fatal
    print('DISABLE')
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ktsaou** [comment]
@paulfantom please check this

**Comment by ktsaou** [comment]
and to note that python.d.plugin, although it logs this, it runs.

**Comment by paulfantom** [comment]
We have two errors here, and both are caused by the same. They are caused by closing stdout pipe, before printing something. Problem lies in python inability to execute `print()`.

Also since python.d.plugin displays Traceback there is no way it is still running.

**Comment by ktsaou** [comment]
> Also since python.d.plugin displays Traceback there is no way it is still running.

That was strange, yes.
I can't reproduce it now (not even the error).
My gentoo has python3.4 by default.

Anyway, if I manage to reproduce it, I will re-open this.

**Comment by paulfantom** [comment]
I was reading more about BrokenPipeError and it seems that this error is caused by receiving SIGPIPE signal.
