### ISSUE TITLE
docker mount points are way too long and overlap

### ISSUE THREAD

**Issue by agross** [firehol/netdata#880]
Reference: https://twitter.com/linuxnetdata/status/771755064000147456

I'm not really sure what you mean. Disks | /var/lib/docker/devicemapper/...? Or alarms in the disk category?

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/18224635/6d64ce66-71e5-11e6-811d-1ebe135f63f5.png)

I think I have fixed it in PR #879

**Comment by ktsaou** [comment]
I am also trying to find a way to map network interfaces to containers. I want to move these `veth*`:

![image](https://cloud.githubusercontent.com/assets/2662304/18224647/c2676c7a-71e5-11e6-9f33-1cca66a28a79.png)

to their proper place, under the containers:

![image](https://cloud.githubusercontent.com/assets/2662304/18224652/db0d4966-71e5-11e6-9b68-2eecb698614d.png)

No luck so far. I can't figure a way that given the interface name, the docker container id can be found.
Of course, I want to do this without talking to docker. I have to do it the linux way (i.e. information in `/proc` or `/sys`).

**Comment by ktsaou** [comment]
And the same is true for mount points.

**Comment by ktsaou** [comment]
btw, I think the menu in PR #879 will be a lot better for your case. I replaced keywords with icons, so that it is shorter.

**Comment by agross** [comment]
OK, I now get  what you mean :)

It seems `docker network inspect` does not show what netdata needs.

One suggestion I found was to do the matching based on IP addresses:
```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' $CONTAINER
172.17.0.4
```

And after that (in a loop until a match is found): 
```
$ NETWORK_NAME=bridge
$ docker network inspect --format='{{range .IPAM.Config}}{{.Subnet}} {{end}}' $NETWORK_NAME
172.17.0.0/16
```

Here's another solution: https://bugzilla.redhat.com/show_bug.cgi?id=1251538#c15

```
$ docker inspect --format='{{.NetworkSettings.SandboxKey}}' youtrack
/var/run/docker/netns/09379f98d3bd
$ nsenter --net=/var/run/docker/netns/09379f98d3bd ethtool -S eth0
NIC statistics:
     peer_ifindex: 25
$ ip link | grep 25:
25: veth942ebf9@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default
```

This appears to be related.
https://github.com/docker/docker/issues/17064

---

Note that my two `br-*` interfaces relate to the `*-default` networks above that are created by `docker-compose`.

So for standalone containers there is a relation container 1 <-> 1 network: `teamcity`, `youtrack`, `hub`, `nginx`.

For containers run via `docker-compose` there is an additional `br-*` interface for communication between the composed containers. Each bridge relates to a line in  `docker network ls`.

```
[root@router netdata]#  brctl show
bridge name      bridge id               STP enabled     interfaces
br-157cb8ae9ab8  8000.0242be4f54b8       no              veth01b25e9
                                                         vethbb23c90
br-227b9402be1b  8000.024254010c29       no              veth3d44651
docker0          8000.0242292b8b62       no              veth4bd64ac
                                                         veth61aa9d6
                                                         veth942ebf9
```

**Comment by agross** [comment]
> I have to do it the linux way (i.e. information in /proc or /sys)

Whoops. I missed that important line!

**Comment by ktsaou** [comment]
This one is interesting:

```
nsenter --net=/var/run/docker/netns/09379f98d3bd ethtool -S eth0
NIC statistics:
     peer_ifindex: 25
$ ip link | grep 25:
25: veth942ebf9@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default
```

but then... `eth0`? 
I need to find a more generic way...

**Comment by ktsaou** [comment]
I have merged PR #879.
Can you update your netdata to check how it looks?

**Comment by ktsaou** [comment]
oh! it is updated. Thanks! Checking it now...

**Comment by agross** [comment]
> Can you update your netdata to check how it looks?

Did that already :-)

https://github.com/firehol/netdata/pull/879#issuecomment-244546519

**Comment by agross** [comment]
> but then... eth0?

Yeah, I don't know what this is supposed to mean, esp. given that my server doesn't even have `eth0`.

**Comment by agross** [comment]
> but then... eth0?

Interesting: the interface automatically becomes eth0 as soon as you run `nsenter`:

```
$ nsenter --net=/var/run/docker/netns/99b23df27bee ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
```

Related? https://github.com/firehol/netdata/issues/474

**Comment by ktsaou** [comment]
We will continue this discussion in #474 .
I am closing this. The new UI I hope solves also horizontal scrollbar issue you were having.

**Comment by agross** [comment]
Looking great! :+1:
