### ISSUE TITLE
import graphs into something like wordpress

### ISSUE THREAD

**Issue by paxanon** [firehol/netdata#891]
Hi,

Im in the middle of making a monitoring system for quite a few locations with a local site for displaying the graphs.

Im looking for a way to import into a wordpress (or other easy to manage / design framework) how should / would i go about doing this ?

**Comment by ktsaou** [comment]
Can you elaborate a bit "import into a wordpress"? What do you mean?

**Comment by paxanon** [comment]
i was thinking i could make a simple webpage via wordpress (webdesign was never my strong suite) and have that do layout of pages while i put in the graphs i wanted to show on each page.

Hope that clarifies it

**Comment by ktsaou** [comment]
ok. If you can put raw html in the wordpress page (sorry, I don't know), just open `http://your.netdata:19999/tv.html`, view its source and copy and paste a few `<div>` blocks. Each `<div>` is a chart.

You will have to include `dashboard.js` from a netdata server for this to work.
Check what `tv.html` does.

**Comment by ktsaou** [comment]
Also, check the top of `dashboard.js` (https://github.com/firehol/netdata/blob/master/web/dashboard.js) for the variables you can define before loading it. Using these you can disable, for example, bootstrap or prevent netdata from loading its own copy of jquery.

**Comment by paxanon** [comment]
Perhaps i worded it wrong.
I have a few (3 atm more if i get it to work as i want) netdata servers all on different networks.
I have one cloud webserver that i would like to collect and show data in a mixed website build on wordpress (could try something else, but wordpress is kinda working for the other things i use it for).

as a sidenode, the netdata badges doesnt update automatically, i have to reload the page for it to update.
Did i miss something or is this by design ?

**Comment by ktsaou** [comment]
Badges autorefresh if you use `<embed src="BADGE_URL" type="image/svg+xml" height="20" />` and the BADGE_URL has the `refresh=` parameter.

Regarding your wordpress request, I think I still don't get it. You want to embed netdata charts in a wordpress site, but your netdata servers will not be accessible by the users of this site?

**Comment by paxanon** [comment]
must have missed the refresh parameter, thanks

yes that is correct, the users of the wordpress site wont be able to access the netdata servers.

**Comment by ktsaou** [comment]
You can have your web server (apache, nginx, etc), proxy the chart requests to your netdata servers. This way your users need access to your web server and your web server needs access to netdata. Using the features of your web server you can also limit the URLs your web server will allow to be proxies.

Will this solve it?

**Comment by paxanon** [comment]
perhaps.
for now im working in a test setting, atm my biggest 'challange' is to actually get the charts to show in a wordpress page.
Security will be next step

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you need help just post and we will follow up.
