### ISSUE TITLE
Where can this be installed

### ISSUE THREAD

**Issue by spot88** [firehol/netdata#894]
Hello! Sorry if this is a stupid question. 

Can i install this on a VMware(Linux) and get information on a dedicated server that's not located on the local network? - Even is it possible to "watch" multiple servers over the internett using ssh or something? 

Thanks for the reply, and keep up this great project. 
-spot

**Comment by spot88** [comment]
Anyone can elaborate please? Want to install this on a second computer to monitor my main server.

**Comment by ktsaou** [comment]
Hi,

Install netdata on your main server and use a web browser on your second computer, to view the dashboard of the main server.
