### ISSUE TITLE
How can i configure Netdata in a multiple server enviorment to only send the data to the default server and not to the client?

### ISSUE THREAD

**Issue by hcosoft** [firehol/netdata#902]
I have multiple servers setup with netdata. 
2 Server i want to monitor and another server i just want to use as Dashboard for a tv. 
Dashboard has only access to the 2 other servers on port 19999 and is in a different subnet. 
All servers have netdata installed.

For security reasons the dashboard is not allowed to communicate with the 2 Servers to monitor.

To access the 2 servers i want to monitor i have to use a VPN tunnel. 
When i try to access the dashboard server without, the only data remaining is from the Dashboard server. 

I figured out that my client has to have a connection to all of the three servers to get data. 

Is there a way i can collect all data on the dashboard server, without the requirement to have a connection to all the three servers from my PC?

**Comment by ktsaou** [comment]
You can install one nginx or apache on one of your servers and proxy netdata through it. You can also configure user authentication on this web server so that all your netdata will be password protected.

Check the wiki.

**Comment by MrSiNiSt3R** [comment]
Grafana
