### ISSUE TITLE
system.proc

### ISSUE THREAD

**Issue by unixdav** [firehol/netdata#907]
Hi,

Can you explain me what kind of sytem process does this "id-netdata" mesuring ?
                       data-netdata="system.processes"
                       data-title="System Process"
                 
the graphic is moving between 2, 3 and 4 process, but i have more than that running.
thank you for your help.

**Comment by ktsaou** [comment]
running = run (in the CPU) now
blocked = willing to run now, but cannot

2 charts below is system.active_processes which lists all the processes opened in the system.

**Comment by unixdav** [comment]
thanks ! very helpful.
great product btw ;)
