### ISSUE TITLE
cgroups support

### ISSUE THREAD

**Issue by Kubuxu** [firehol/netdata#91]
Sorry for flooding you with feature requests.

cgroups' filesystem provides statistics about CPU time, IO times, memory usage and so which is really useful and really is a base for LXC and in case of systemd will provide accurate per-user, -subsystem, -slice and in some cases -service statists.

(only quirk of cgroups IIRC is that memory usage includes disk cache in RAM which makes RAM usage seem higher than it should be).

**Comment by ktsaou** [comment]
Can you give me the output of:

```sh
find /sys/fs/cgroup
```

on a system with lxc containers?

I am also trying to find the same from a system with docker containers. Can anyone help?

**Comment by magik6k** [comment]
While reading directly from cgroup fs works for LXC it's not advised, as it's cgroup locations may differ on various distros and LXC versions. Instead you really should consider using LibLXC with it's get_cgroup_item function. For reference: https://github.com/lxc/lxc/blob/master/src/lxc/lxccontainer.h

**Comment by ktsaou** [comment]
> Instead you really should consider using LibLXC with it's get_cgroup_item function.

I see, but then we are going to need one plugin for every cgroup manager. Writing LXC will not provide anything to Docker funs...

I don't have an issue with it. It just doubles (or even triples) the work to be done...

**Comment by magik6k** [comment]
I'm aware of that, just wanted to point at 'the LXC way', using normal cgroups will still be just fine.

**Comment by Kubuxu** [comment]
[Here](https://gist.github.com/Kubuxu/a443014329fbdb3bbd6202e4f90304b2) is our cgourps tree, as you can see it can be quite chaotic (in some cases one lxc container will be included in two places in cgroups tree, see for example `pid` tree).

Also their location can be dynamic as it depends on how it was started and what is the parent process.

Possible solution is to see which process started the tree (`lxc-start`) and then use: `/proc/$PID/cgroup` which will produce something like:

```
cat /proc/460/cgroup
9:net_cls:/
8:freezer:/
7:pids:/system.slice/system-lxc.slice/lxc@nexus.service
6:blkio:/system.slice/system-lxc.slice/lxc@nexus.service
5:devices:/system.slice/system-lxc.slice/lxc@nexus.service
4:memory:/system.slice/system-lxc.slice/lxc@nexus.service
3:cpu,cpuacct:/system.slice/system-lxc.slice/lxc@nexus.service
2:cpuset:/
1:name=systemd:/system.slice/system-lxc.slice/lxc@nexus.service
```

**Comment by ktsaou** [comment]
ok, let's discuss what information are we planning to show.

I thought something like this:

for each container, a chart for:

1. CPU
2. Block I/O
3. RAM

If I get it right, the above can be taken from `/sys/fs`. We only need to somehow find the container names to have something with meaning.

What else can we show?

**Comment by Kubuxu** [comment]
Process and task counts would also be available with limits.

There are many different stats about those 3 key points you mentioned.

I think it would be possible to use generic cgroups interface for reading the data but  arriving with correct cgroup to read would have to be done on per usage case (LXC, docker, other things).

I wouldn't recommend using `lxc-start` as a sign of LXC container as it can be started without it with use of libLXC but libLXC provides 

![](https://assets.magik6k.net/screenshoots/1459458389.png)
(the `/sbin/init` runs inside the container created from Java/Scala bindings to libLXC).

**Comment by ktsaou** [comment]
ok. To get process count per cgroup we could modify `apps.plugin` to collect this info. This plugin already walks through the entire process tree every second. It could also collect the cgroup each process runs under.

Can someone post `find /sys/fs/cgroup` to see what info is there?

**Comment by Kubuxu** [comment]
I posted it earlier, you might not have noticed it so posting full link: https://gist.github.com/Kubuxu/a443014329fbdb3bbd6202e4f90304b2

**Comment by ktsaou** [comment]
Oh! Sorry! I missed it.

What I understand is that there is a directory called `lxc` and within it, there is a directory with the container name.

Info about the `/sys/fs` stats is here: https://www.kernel.org/doc/Documentation/cgroup-v1/

**Comment by Kubuxu** [comment]
It might be true, it doesn't have to. Best way to do it would be to find out that some process is LXC, docker or other cgroups enabled manager and use `/proc/$PID/cgroups` to get location of cgroups for this process.

For example for process id 513 which is `init` process of one of my containers I get following `/proc/512/cgroups`:
```
 9:net_cls:/lxc/kubuxu
8:freezer:/lxc/kubuxu
7:pids:/init.scope/lxc/kubuxu
6:blkio:/init.scope/lxc/kubuxu
5:devices:/init.scope/lxc/kubuxu
4:memory:/init.scope/lxc/kubuxu
3:cpu,cpuacct:/init.scope/lxc/kubuxu
2:cpuset:/lxc/kubuxu
1:name=systemd:/system.slice/system-lxc.slice/lxc@kubuxu.service/init.scope
```

This also means that even if LXC or docker change their cgroups layout (names are just names they have no real meaning as what is important is processes that run under them) or kernel 4.6 is deployed (that makes some changes to nested cgroups from the inside) the code using `/proc/$PID/cgroups` will still work if it is able to identify root process of given task.

**Comment by ktsaou** [comment]
have a look at #115 
I would like to have your view.

**Comment by Kubuxu** [comment]
Note: You can also list processes under given cgroup with `cgroup.procs` entry in any cgroup.

**Comment by ktsaou** [comment]
This is not exactly related to the issue we discuss here, but it might helpful.

WIth the https://github.com/firehol/netdata/commit/da9e1df4cbde9208d30b99937046b667e82e88a1 commit, the following have been added:

1. Per user charts (all of the previously known as Apps Charts: cpu, memory, disk, files, sockets, pipes, swap, etc)

  these were tricky, because:
  -  I had to find a way to detect the username of all running pids without reading all the thousands of the `/proc/X/status` files. It turns out that just examining each pid /proc directory `/proc/X` (without reading any files), I could get the effective uid and gid of the process - this is very fast, just this addition did not have any impact on the profiler, and
  - tasks switch users all the time (especially samba - every few seconds), so the incremental resources consumed were transferred among users and resulted in unrealistic spikes in the charts (I solved it of course, but it required some treatment).

2. Per user group charts (all of them again)

 similar to the above - same things

3. Almost total re-write of `apps.plugin`.

  The new one is optimized too. It is 10% faster, **after the new features**, compared to the old.

4. Solved a few corner cases that were unhandled in the previous version.

Enjoy!

**Comment by ktsaou** [comment]
Check PR #308
First support for monitoring cgroups. Tomorrow I will try to work around the 2 issues mentioned there, before merging it.

**Comment by ktsaou** [comment]
PR #308 has been merged!

**Comment by ktsaou** [comment]
cgroups support is now complete.

Only for docker, there is a pending item in #115 to use a proxy to get the docker names instead of adding the user `netdata` to the `docker` group.

**Comment by ktsaou** [comment]
I think this can be closed now.
