### ISSUE TITLE
python.d: UrlService.check() always fails

### ISSUE THREAD

**Issue by sehraf** [firehol/netdata#910]
Hi
i'm currently trying to add a new python module and had problems with the check() function from UrlService.
It seems to me that UrlService.check() will always return False since check() calls _get_data() [1] wich is implemented by SimpleService and returns {} [2]. The value returned by _get_data() is then checked with `if test is None or len(test) == 0:` wich will always be true since `len({}) = 0` and UrlService.check() will return False.

I assume that UrlService.check() should use _get_raw_data() instead to check whether it gets something from the URL or not. Or did i overlook / misunderstood something here?

[1] https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L493
[2] https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py#L335

**Comment by ktsaou** [comment]
@paulfantom please check this...

**Comment by sehraf** [comment]
i know what i oversaw:
_get_data() should be implemented by the class that derives from UrlService and so check should be find as long as the class i'm implementing is fine.

sorry for the noise
now my new python plugin is running - expect a pull request soon 😄
