### ISSUE TITLE
Compiling on RHEL5.x

### ISSUE THREAD

**Issue by fumok** [firehol/netdata#911]
Hi,

I've found a little problem compiling on RHEL5.9. I've deleted line from 41 to 46 in web_server.c, and now is running fine.

Thanks for this awesome tool.

**Comment by ktsaou** [comment]
These: https://github.com/firehol/netdata/blob/master/src/web_server.c#L41-L46 ?

I have added the `#ifdef` there for this exact reason. Are you running an older clone of the repo?

**Comment by ktsaou** [comment]
I don't have access to RHEL 5. Can you post the error you got before removing them?

**Comment by jasonwbarnett** [comment]
@ktsaou I'll check this for you once more details are posted

**Comment by fumok** [comment]
This is the error (after ./configure && make):

web_server.c: In function ‘accept4’:
web_server.c:43: error: ‘O_CLOEXEC’ undeclared (first use in this function)
web_server.c:43: error: (Each undeclared identifier is reported only once
web_server.c:43: error: for each function it appears in.)

I confirm those lines:
https://github.com/firehol/netdata/blob/ae273fdf4bcd99bab8953d0fd233c5381bd5374c/src/web_server.c#L41-L46

RHEL5.x have autoconf 2.59 so I've downloaded this source:
https://firehol.org/download/netdata/unsigned/master/netdata-1.3.1_master.tar.gz

For your information:
gcc --version
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)

Just ask if you need more details.

Thanks a lot.

**Comment by ktsaou** [comment]
thanks!

The fix will be merged with PR #905
