### ISSUE TITLE
python.d multiple dimensions on different charts with same name

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#913]
@paulfantom I want to adapt apache_cache.py for one of my applications to parse the log file and create a lot of charts with exactly the same dimensions.

For example:

- chart API1 would have dimensions 1xx, 2xx, 3xx, 4xx, 5xx
- chart API2 would have the same dimensions
- etc.

I see that the return value of the data collection module returns an object where each dimension is uniquely named.

Am I missing something?

**Comment by paulfantom** [comment]
You are right, each dimension is in fact uniquely named. That was one of shortcuts I took to simplify modules development.

**Comment by ktsaou** [comment]
Is there a work-around? For example to give different dimensions ids but the same dimension names. Will this work?

**Comment by paulfantom** [comment]
Sorry, I was not clear enough. Dimension id's are unique, but their names doesn't have to be. However further in program you need to assign values to dimension id's not names (which are only taken into account when creating charts).

**Comment by ktsaou** [comment]
ok thanks!
