### ISSUE TITLE
disable alarms...

### ISSUE THREAD

**Issue by abdulirfan3** [firehol/netdata#917]
Hello,

Is there a way to disable the whole alarm feature completely for specific hosts?? We use netdata for more of on-demand monitoring and do not need that feature enabled on all of our system...so how would one disable the alarm? I have not seen anything related to this in the wiki page...

**Comment by Splo0sh** [comment]
Have you tried the `netdata.conf` and set
```
[health]
    enabled = no
```

**Comment by i300220** [comment]
edited netdata.conf as instructed followed by 'killall -USR2 netdata'

doesn't work

it's a real annoyance as i get cron jobs on all computers expected to trigger several of the pre-programmed alarms

i don't want to mess with the health;d directory or risk to have it overwritten with fresh alarm files with each and every upgrade.  

please provide instructions to disable permanently as i don't have time to configure each and every one of them at once.

don't get me wrong, i think it's an excellent feature however i'm not ready to enable it now or in a near future.

best regards!

**Comment by Splo0sh** [comment]
You have to restart netdata (service netdata restart).
I tried it yesterday. Worked like a charme :)

**Comment by i300220** [comment]
ah! thanks!  excellent news!

**Comment by ktsaou** [comment]
`killall -USR2 netdata` reloads only the alarms configured in `/etc/netdata/health.d`. Changing `netdata.conf` requires restarting netdata.

Sorry for the inconvenience...

**Comment by abdulirfan3** [comment]
this works, thanks....

**Comment by wellington1993** [comment]
Thanks! @ktsaou and @coraxx
