### ISSUE TITLE
Systemd script failed to make netdata bind on port <1024

### ISSUE THREAD

**Issue by SandPox** [firehol/netdata#921]
Since netdata.service use account "netdata" to start so it's not possible to bind on these port (required root).
[Service]
User=netdata
Group=netdata

my current workaround are changing those value to "root" but it will create a security risk so it's not recommend.

**Comment by ktsaou** [comment]
nice finding thanks for sharing!

**Comment by LucaDev** [comment]
You could try using setcap 'cap_net_bind_service=+ep' /path/to/netdata

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion/issue, please post and I'll re-open it.
