### ISSUE TITLE
cgroups names collapse

### ISSUE THREAD

**Issue by fumok** [firehol/netdata#922]
With systemd cgroups names are sometime very long, it happens they collapse in unexpected way.

Example:

/usr/libexec/netdata/plugins.d/cgroup-name.sh:
 cgroup 'machine.slice_machine-qemu/x2drt1host01/x2dgo/**x2drt1vlin**/x2da.scope' is called '**machine.slice_machine-qemu/x2drt1host01/x2dgo/x2dr**'
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'machine.slice_machine-qemu/x2drt1host01/x2dgo/**x2drt1vwin**/x2da.scope' is called '**machine.slice_machine-qemu/x2drt1host01/x2dgo/x2dr**'

As yuo see I've two kvm guest (which names contains rt1vlin and rt1vwin, ok they are quite similar), but they are graphed as one. I've not understand if strings are truncated after 50 chars, or after fourth /

It's suffice to edit 
/etc/netdata/cgroups-names.conf

machine.slice_machine-qemu/x2drt1host01/x2dgo/x2drt1vlin/x2da.scope firtvm
machine.slice_machine-qemu/x2drt1host01/x2dgo/x2drt1vwin/x2da.scope secondvm

and now I can see two distinct charts. It would be very handy to use regex, or something similar, for not having to edit cgroups-names.conf every time a contanier is added.

Thanks a lot.

P.S.
I've read #412 #791

**Comment by ktsaou** [comment]
You are right. Stripping the text there is not good.
I'll check alternatives this weekend.

Thanks for reporting this!

**Comment by fumok** [comment]
Investigating further ... new versions of libvirt (2.2.0) add a sequential and changing number (to cgroup path) at every guest restart.
I must study better this behaviour.

**Comment by ktsaou** [comment]
hm... similar to what docker does.

Do they provide a way of quering something to get the name.

We could just alter this script: https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh to do whatever necessary (similar to what we have done for docker).

**Comment by fumok** [comment]
Trunced by 50 chars.

https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L74

**Comment by ktsaou** [comment]
> truncated by 50 chars.

yes I know.

> Maybe this is a starting point:

I am not sure it is. We need to somehow find the name given the cgroup path.
For example, given: `machine.slice_machine-qemu/x2drt1host01/x2dgo/x2drt1vlin/x2da.scope` which is the name?

**Comment by fumok** [comment]
IMHO in `machine.slice_machine-qemu/x2drt1host01/x2dgo/x2drt1vlin/x2da.scope` there are only two useful files:

    cgroup.procs
    tasks

all of which return some PID. Then you can parse /proc/$PID/cmdline (euristic needed)

**Comment by ktsaou** [comment]
Does `virsh list` support an extended view or something to show more information?

**Comment by fumok** [comment]
Not that I know, sorry.

    virsh help list
    
    
      NAME
        list - list domains
    
      SYNOPSIS
        list [--inactive] [--all] [--transient] [--persistent] [--with-snapshot] [--without-snapshot] [--state-running] [--state-paused] [--state-shutoff] [--state-other] [--autostart] [--no-autostart] [--with-managed-save] [--without-managed-save] [--uuid] [--name] [--table] [--managed-save] [--title]
    
      DESCRIPTION
        Returns list of domains.
    
      OPTIONS
        --inactive       list inactive domains
        --all            list inactive & active domains
        --transient      list transient domains
        --persistent     list persistent domains
        --with-snapshot  list domains with existing snapshot
        --without-snapshot  list domains without a snapshot
        --state-running  list domains in running state
        --state-paused   list domains in paused state
        --state-shutoff  list domains in shutoff state
        --state-other    list domains in other states
        --autostart      list domains with autostart enabled
        --no-autostart   list domains with autostart disabled
        --with-managed-save  list domains with managed save state
        --without-managed-save  list domains without managed save
        --uuid           list uuid's only
        --name           list domain names only
        --table          list table (default)
        --managed-save   mark inactive domains with managed save state
        --title          show domain title

**Comment by ktsaou** [comment]
Well, for the moment I will remove the 50 characters limit.

Check these:

- https://libvirt.org/cgroups.html
- https://www.centos.org/docs/5/html/5.2/Virtualization/sect-Virtualization-Commands_for_Red_Hat_Virtualization-virsh_the_command_line_interface_tool_for_virtualization.html

I understand there is some logic on how the cgroups hierarchy is created by libvirt (i.e. there are UUIDs, DOMs, etc), so we may just need some understanding on how to parse the cgroup path and which command could be helpful.

Unfortunately, I don't use this technology, so my learning curve will be high. Is there anyone expert on this to help us?

**Comment by ktsaou** [comment]
I increased the length to 100. I'll make a PR in a while.

**Comment by ktsaou** [comment]
merged it.
