### ISSUE TITLE
Centos 5.5 - Sorry! NetData failed to build... The package zlib1g-dev has to be installed.

### ISSUE THREAD

**Issue by justincm** [firehol/netdata#93]
I installed the packjages required for centos as per the instructions 
yum install zlib-devel gcc make git autoconf autogen automake pkgconfig

 Installing:
 automake                                noarch                        1.9.6-3.el5                            base                        476 k
Updating:
 gcc                                     i386                          4.1.2-55.el5                           base                        5.2 M
 git                                     i386                          1.8.2.1-2.el5                          epel                        7.4 M
 zlib-devel                              i386                          1.2.3-7.el5                            base                        102 k
Installing for dependencies:
 perl-TermReadKey                        i386                          2.30-4.el5                             epel                         32 k
Updating for dependencies:
 cpp                                     i386                          4.1.2-55.el5                           base                        2.7 M
 gcc-c++                                 i386                          4.1.2-55.el5                           base                        3.4 M
 libgcc                                  i386                          4.1.2-55.el5                           base                         97 k
 libstdc++                               i386                          4.1.2-55.el5                           base                        364 k
 libstdc++-devel                         i386                          4.1.2-55.el5                           base                        2.8 M
 perl-Git                                i386                          1.8.2.1-2.el5                          epel                         49 k
 zlib                                    i386                          1.2.3-7.el5                            base                         51 k

Transaction Summary

Install       2 Package(s)
Upgrade      10 Package(s)

Total download size: 23 M
Is this ok [y/N]: y
Downloading Packages:
(1/12): perl-TermReadKey-2.30-4.el5.i386.rpm                                                                             |  32 kB     00:00
(2/12): perl-Git-1.8.2.1-2.el5.i386.rpm                                                                                  |  49 kB     00:00
(3/12): zlib-1.2.3-7.el5.i386.rpm                                                                                        |  51 kB     00:00
(4/12): libgcc-4.1.2-55.el5.i386.rpm                                                                                     |  97 kB     00:00
(5/12): zlib-devel-1.2.3-7.el5.i386.rpm                                                                                  | 102 kB     00:00
(6/12): libstdc++-4.1.2-55.el5.i386.rpm                                                                                  | 364 kB     00:00
(7/12): automake-1.9.6-3.el5.noarch.rpm                                                                                  | 476 kB     00:00
(8/12): cpp-4.1.2-55.el5.i386.rpm                                                                                        | 2.7 MB     00:00
(9/12): libstdc++-devel-4.1.2-55.el5.i386.rpm                                                                            | 2.8 MB     00:00
(10/12): gcc-c++-4.1.2-55.el5.i386.rpm                                                                                   | 3.4 MB     00:00
(11/12): gcc-4.1.2-55.el5.i386.rpm                                                                                       | 5.2 MB     00:00
(12/12): git-1.8.2.1-2.el5.i386.rpm                                                                                      | 7.4 MB     00:00

Total                                                                                                           7.2 MB/s |  23 MB     00:03
Running rpm_check_debug
Running Transaction Test
Finished Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing     : automake                                                                                                                1/22
  Updating       : zlib                                                                                                                    2/22
  Updating       : libgcc                                                                                                                  3/22
  Updating       : libstdc++                                                                                                               4/22
  Updating       : cpp                                                                                                                     5/22
  Updating       : gcc                                                                                                                     6/22
  Installing     : perl-TermReadKey                                                                                                        7/22
  Updating       : libstdc++-devel                                                                                                         8/22
  Updating       : zlib-devel                                                                                                              9/22
  Updating       : gcc-c++                                                                                                                10/22
  Updating       : perl-Git                                                                                                               11/22
  Updating       : git                                                                                                                    12/22
  Cleanup        : perl-Git                                                                                                               13/22
  Cleanup        : libstdc++-devel                                                                                                        14/22
  Cleanup        : gcc-c++                                                                                                                15/22
  Cleanup        : gcc                                                                                                                    16/22
  Cleanup        : cpp                                                                                                                    17/22
  Cleanup        : libstdc++                                                                                                              18/22
  Cleanup        : zlib-devel                                                                                                             19/22
  Cleanup        : zlib                                                                                                                   20/22
  Cleanup        : git                                                                                                                    21/22
  Cleanup        : libgcc                                                                                                                 22/22

Installed:
  automake.noarch 0:1.9.6-3.el5

Dependency Installed:
  perl-TermReadKey.i386 0:2.30-4.el5

Updated:
  gcc.i386 0:4.1.2-55.el5                      git.i386 0:1.8.2.1-2.el5                      zlib-devel.i386 0:1.2.3-7.el5

Dependency Updated:
  cpp.i386 0:4.1.2-55.el5                  gcc-c++.i386 0:4.1.2-55.el5        libgcc.i386 0:4.1.2-55.el5      libstdc++.i386 0:4.1.2-55.el5
  libstdc++-devel.i386 0:4.1.2-55.el5      perl-Git.i386 0:1.8.2.1-2.el5      zlib.i386 0:1.2.3-7.el5

Complete!

##############################################

./netdata-installer.sh  --zlib-is-really-here

Welcome to netdata!
Nice to see you are giving it a try!

You are about to build and install netdata to your system.

It will be installed at these locations:

  - the daemon    at /usr/sbin/netdata
  - config files  at /etc/netdata
  - web files     at /usr/share/web/netdata
  - plugins       at /usr/libexec/netdata
  - cache files   at /var/cache/netdata
  - log files     at /var/log/netdata

This installer allows you to change the installation path.
Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system >
ok, assuming zlib is really installed.
Running ./autogen.sh ...
:-----------------------------------------------------------------------------
Running command:

./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:4: error: Autoconf version 2.60 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You many need to check these:

1. The package zlib1g-dev has to be installed.

2. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

#######

even running with the --zlib-is-really-here option it still fails the same

**Comment by xitude** [comment]
Run it again with the flag
> --zlib-is-really-here

**Comment by justincm** [comment]
Got to the bottom of it.

I had to remove using yum automake and autoconf and reconfigure them from source to their latest versions.
after that it bailed at line 5030 and line 5047 on the configure so I just removed the following lines from the configure.ac file

#if test "${enable_plugin_nfacct}" = "yes"; then
#       PKG_CHECK_MODULES(
#               NFACCT,
#               libnetfilter_acct,
#       )
#       PKG_CHECK_MODULES(
#               LIBMNL,
#               libmnl,
#       )
#       test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
#       test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5
#
#$as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
#
#       OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
#       OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"
#fi
#if test "${with_zlib}" = "yes"; then
#       PKG_CHECK_MODULES(
#               ZLIB,
#               zlib,
#       )
#       test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5
#
#$as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
#
#       OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
#       OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
#fi

then it installed and is running

**Comment by MuhammadFayazkhan** [comment]
same error kindly tell me the solution about that.

i am looking forward your good response .

**Comment by MuhammadFayazkhan** [comment]
You many need to check these:

The package zlib1g-dev has to be installed.

You need basic build tools installed, like:

gcc make autoconf automake pkg-config

If your system cannot find ZLIB, although it is installed
run me with the option: --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

https://github.com/firehol/netdata/issues

#######

even running with the --zlib-is-really-here option it still fails the same


try it ...but same error :-1:  :(

**Comment by justincm** [comment]
remove the yuim installed packages of automake and autoconf

then download and install from source the latest of them

 wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
 wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz

I then commented out in the configure.rc file the following lines

> if test "${enable_plugin_nfacct}" = "yes"; then
>  PKG_CHECK_MODULES(
>  NFACCT,
>  libnetfilter_acct,
>  )
>  PKG_CHECK_MODULES(
>  LIBMNL,
>  libmnl,
>  )
>  test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
>  test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5
> 
> $as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
>    OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
>    OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"
> 
> 
> fi
>  if test "${with_zlib}" = "yes"; then
>  PKG_CHECK_MODULES(
>  ZLIB,
>  zlib,
>  )
>  test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5
> 
> $as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
>    OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
>    OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
> fi

then reran the ./netdata-installer.sh --zlib-is-really-here

now running

**Comment by MuhammadFayazkhan** [comment]
i did it same but same issue .

**Comment by MuhammadFayazkhan** [comment]
./netdata-installer.sh --zlib-is-really-here

Welcome to netdata!
Nice to see you are giving it a try!

You are about to build and install netdata to your system.

It will be installed at these locations:

  - the daemon    at /usr/sbin/netdata
  - config files  at /etc/netdata
  - web files     at /usr/share/netdata
  - plugins       at /usr/libexec/netdata
  - cache files   at /var/cache/netdata
  - log files     at /var/log/netdata

This installer allows you to change the installation path.
Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system >
ok, assuming zlib is really installed.
Running ./autogen.sh ...
:-----------------------------------------------------------------------------
Running command:

./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:4: error: Autoconf version 2.60 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:

1. The package zlib1g-dev has to be installed.

2. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues

**Comment by justincm** [comment]
I also had to remove autoconf from yum and reinstall from source
wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz

**Comment by MuhammadFayazkhan** [comment]
i have remove both  packages of automake and autoconf from yum ....

downloaded both pakage as you give me .
still same issuse .

**Comment by MuhammadFayazkhan** [comment]
install this ..
 yum install zlib-devel gcc make git  autogen  pkgconfig 
and then i have download this 
wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz 

then  i have download 
git clone https://github.com/firehol/netdata.git --depth=1  
then go to 
cd netdata 
commented also  these line form Netsatedata folder file name configure.ac 

if test "${enable_plugin_nfacct}" = "yes"; then
PKG_CHECK_MODULES(
NFACCT,
libnetfilter_acct,
)
PKG_CHECK_MODULES(
LIBMNL,
libmnl,
)
test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5

$as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"

fi
if test "${with_zlib}" = "yes"; then
PKG_CHECK_MODULES(
ZLIB,
zlib,
)
test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5

$as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
fi

and run this command ./netdata-installer.sh --zlib-is-really-here 
still same issue

**Comment by MuhammadFayazkhan** [comment]
kindly give me instruction i am worry about that ..

**Comment by justincm** [comment]
Try export AUTOM4TE=autom4te2.6x before running ./netdata-installer

**Comment by MuhammadFayazkhan** [comment]
from where 

Try export AUTOM4TE=autom4te2.6x  ???? where is it .?

**Comment by justincm** [comment]
from the command line before you run the ./netdata-installer command

**Comment by MuhammadFayazkhan** [comment]
same issue i run it AUTOM4TE=autom4te2.6x  
then run ./netdata-installer as well as ./netdata-installer.sh --zlib-is-really-here  

same issue

**Comment by MuhammadFayazkhan** [comment]
Welcome to netdata!
Nice to see you are giving it a try!

You are about to build and install netdata to your system.

It will be installed at these locations:

  - the daemon    at /usr/sbin/netdata
  - config files  at /etc/netdata
  - web files     at /usr/share/netdata
  - plugins       at /usr/libexec/netdata
  - cache files   at /var/cache/netdata
  - log files     at /var/log/netdata

This installer allows you to change the installation path.
Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system >
ok, assuming zlib is really installed.
Running ./autogen.sh ...
:-----------------------------------------------------------------------------
Running command:

./autogen.sh

./autogen.sh: line 2: autoreconf: command not found

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! NetData failed to build...

You many need to check these:

1. The package zlib1g-dev has to be installed.

2. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

3. If your system cannot find ZLIB, although it is installed
   run me with the option:  --zlib-is-really-here

If you still cannot get it to build, ask for help at github:

   https://github.com/firehol/netdata/issues
??????????????????????????????????????????? what should i do .. NOW >> >

**Comment by MuhammadFayazkhan** [comment]
would like to tell me exactly thing for Centos 5.8 64 bit

**Comment by justincm** [comment]
Did you 
make install
on autoconf?

**Comment by MuhammadFayazkhan** [comment]
i have install autoconf via yum ...but as you given tar that was not running properly ..

**Comment by MuhammadFayazkhan** [comment]
guide me step by step

**Comment by MuhammadFayazkhan** [comment]
error 

Running command:

./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:4: error: Autoconf version 2.60 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

**Comment by justincm** [comment]
the yum version of autoconf is too old
You need to wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz 
tar -zxvf autoconf-latest.tar.gz 
cd autoconf-latest
./configure
make
make install

**Comment by MuhammadFayazkhan** [comment]
done now what should i do ?

**Comment by MuhammadFayazkhan** [comment]
./autogen.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
autoreconf: running: /usr/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
Makefile.am:4: option `dist-xz' not recognized
autoreconf: automake failed with exit status: 1


NOW NEW error ...

**Comment by MuhammadFayazkhan** [comment]
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
autoreconf: running: /usr/local/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
Makefile.am:4: option `dist-xz' not recognized
autoreconf: automake failed with exit status: 1

**Comment by MuhammadFayazkhan** [comment]
![image](https://cloud.githubusercontent.com/assets/18190518/14282407/9f4eac26-fb57-11e5-86f8-199e0cde1ac5.png)

**Comment by justincm** [comment]
Which version of automake do you have installed?

**Comment by MuhammadFayazkhan** [comment]
1.9.6-3.el5

**Comment by MuhammadFayazkhan** [comment]
now i have run wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz 
then 
./configure 
 Now >??? i have remove 1.9.6-3.el5 this one .

**Comment by justincm** [comment]
you need to run

make

then 

make install

then run automake --version it should be 

> # automake --version
> #automake (GNU automake) 1.15
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Tom Tromey <tromey@redhat.com>
>        and Alexandre Duret-Lutz <adl@gnu.org>.

**Comment by MuhammadFayazkhan** [comment]
Thanx alot i have done it.. Successfully run netdata

**Comment by ktsaou** [comment]
If you contribute a wiki page to help others too, it would be perfect!

Thanks!

**Comment by MuhammadFayazkhan** [comment]
sure dear why not

On Wed, Apr 6, 2016 at 10:52 AM, Costa Tsaousis <notifications@github.com>
wrote:

> If you contribute a wiki page to help others too, it would be perfect!
>
> Thanks!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/firehol/netdata/issues/93#issuecomment-206129482>
>



-- 

*Thanks & Regards,*


*Muhammad Fayaz Khan*

*System Engineer *

[image: cid:image001.png@01D055D3.20D64C80]

*Address: *86, Block 7 & 8, J.C.H.S., Shaheed-e-Millat Road, Karachi –
Pakistan.

*UAN:* +92 21 111 000 NET (638) *| Fax:* +92 21 34390794 *| *

*Email:* fayyaz.khan@connect.net.pk <danish.khan@connect.net.pk> *| URL:*
www.connect.net.pk

**Comment by hmmmph** [comment]
In Addition to commenting out the following in the `configure.ac` file:
```
if test "${enable_plugin_nfacct}" = "yes"; then
PKG_CHECK_MODULES(
NFACCT,
libnetfilter_acct,
)
PKG_CHECK_MODULES(
LIBMNL,
libmnl,
)
test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5

$as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"

fi
if test "${with_zlib}" = "yes"; then
PKG_CHECK_MODULES(
ZLIB,
zlib,
)
test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5

$as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
fi
```

I also needed to comment out the following in `netdata-installer.sh` — otherwise the changes to `configure.ac` would simply get overwritten:

```
echo >&2 "Running ./autogen.sh ..."
run ./autogen.sh || exit 1
```

**Comment by philwhineray** [comment]
Think this can be closed. The installer will point you to the right place to download a pre-autoconfed package if you don't have autotools or too low a version now.

**Comment by paulfantom** [comment]
@ktsaou Close?
