### ISSUE TITLE
apcupsd monitoring 

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#936]
apcupsd has an information server which can provide a lot of useful information about the ups. In particular, the status, load percent, and battery charge would be useful to graph. 

This link details how to get information from the information server: 
http://www.apcupsd.org/manual/manual.html#nis-network-server-protocol 

Would this be something doable for a plugin?

**Comment by ktsaou** [comment]
There is already support for `nut` in netdata.
I see it supports APC UPSes: http://networkupstools.org/ddl/APC/

I think APC has an `apcaccess` command. So, you can adapt [nut.chart.sh](https://github.com/firehol/netdata/blob/master/charts.d/nut.chart.sh) to parse its output.

Unfortunately, I don't have access to an APC UPS.
Can you do it?

**Comment by kmlucy** [comment]
I created a working apcupsd plugin by modifying the nut plugin:

https://github.com/kmlucy/netdata/commit/c0bbc42b0260f6f8103b52227fa302ca46396373

One thing I'm not sure how to do is set the IP address and port from a .conf file, as opposed to just in the script.

**Comment by ktsaou** [comment]
nice!

> One thing I'm not sure how to do is set the IP address and port from a .conf file, as opposed to just in the script.

It is already done. Just edit `/etc/netdata/charts.d/apcupsd.conf` and set any of your global variables. They will overwrite the ones in the code.

Why don't you make a PR?

**Comment by kmlucy** [comment]
Alright, just created: https://github.com/firehol/netdata/pull/939

**Comment by ktsaou** [comment]
merged it

**Comment by ktsaou** [comment]
I am closing this. Thanks!

**Comment by kmlucy** [comment]
Glad to help!
