### ISSUE TITLE
[question] Is there a way to select which partitions are/are not monitored for specific alarms?

### ISSUE THREAD

**Issue by jsveiga** [firehol/netdata#937]
I checked the health.d/disks.conf, but couldn't find a way to make specific alarms ignore or apply only to specific disks.

My issue is that I have systems that use a partition used for an incremental backup. This partition is always used to its max (the backup script automatically removes the oldest backups to free space on demand). This makes the disk space alarm trigger all the time, so it'd be nice to be able to tell netdata to ignore these partitions (I actually disabled the alarm completely).

I also have some iSCSI partitions used for backups, and during the backup it seems like they they are triggering the backlog alarm. Being able to specify alarms with different thresholds for specific partitions would avoid that.

Thanks!
Joao

**Comment by ktsaou** [comment]
Hi,

copy the `template` block that already exist, paste it back and change on the first line the keyword `template` to keyword `alarm` and change the line `on: CONTEXT` to `on: CHART`.

For example, to override this template:

```
template: disk_space_usage
      on: disk.space
    calc: $used * 100 / ($avail + $used)
   every: 1m
    warn: $this > 80
    crit: $this > 95
   units: %
    info: current disk space usage
      to: sysadmin
```

copy it and paste it somewhere like this:

```
   alarm: disk_space_usage
      on: disk_space.sdd1
    calc: $used * 100 / ($avail + $used)
   every: 1m
    warn: $this > 80
    crit: $this > 95
   units: %
    info: current disk space usage
      to: sysadmin
```

This way you can override templates for specific charts.

I suggest to put your alarms on a separate file to allow netdata update its own file on future releases (if you don't change anything on file, the `netdata-installer.sh` will update it to the most recent version).

**Comment by jsveiga** [comment]
sounds great, thanks! I'll try it today!

**Comment by jsveiga** [comment]
It worked,

just a comment: it seems it still generated alarms both for the "template: disk_space_usage" (for all disks) and for the "alarm: disk_space_usage", so I had to either comment the "template:" definition or edit the thresholds for it, so it stopped sending the emails.

Thanks again!

**Comment by ktsaou** [comment]
> just a comment: it seems it still generated alarms both for the "template: disk_space_usage" (for all disks) and for the "alarm: disk_space_usage", so I had to either comment the "template:" definition or edit the thresholds for it, so it stopped sending the emails.

For the same disk? It should not happen. Can you uncomment it and give me the output of `http://your.netdata:19999/api/v1/alarms?all`?

**Comment by jsveiga** [comment]
Sure,

I have attached my disks.conf, local_disks.conf, and the alarm.txt output.

on local_disks.conf you can see I've created an "alarm:disk_space_usage" with warn/crit 98/99 to try to override the 80/95 on the "template:disk_space_usage" of disks.conf.

yet, on alarm.txt line 1559 there's a "disk_space.sdc3.disk_space_usage" with warning, with the 80/95 thresholds. (on line 239 there's an specific "disk_space.sdc3.disk_space_usage_bkp" I created for sdc3 on local_disks.conf for this backup partition, with the 98/99 thresholds correctly identified).

to stop the sdc3 alarm to keep triggering, I have to either comment the "template:disk_space_usage" section of disks.conf, or set its thresholds to 98/99 too.

Thanks again!
Joao

[files.zip](https://github.com/firehol/netdata/files/474825/files.zip)

**Comment by ktsaou** [comment]
I see.
For overriding to work, your alarm has to be named exactly like the template.
This means all your custom `disk_space_usage` alarms would need to be named `disk_space_usage`, not `disk_space_usage_bkp`, `disk_space_usage_root`, etc.

So ok, since you commented the template and you have given alarms for all your disks, it is ok.

**Comment by jsveiga** [comment]
But I did have a "alarm:disk_space_usage" with warn/crit 98/99 on local_disks.conf, same name, different thresholds. The thresholds on the template still generated the alarm.

Joao

**Comment by ktsaou** [comment]
In alarms.txt I see:

```json
		"disk_space.sdc3.disk_space_usage": {
			"name": "disk_space_usage",
			"chart": "disk_space.sdc3",
			"family": "/mnt/backup/hd",
			"active": true,
			"exec": "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/alarm-notify.sh",
			"recipient": "sysadmin",
			"source": "34@/etc/netdata/health.d/disks.conf",
			"units": "%",
			"info": "current disk space usage",
			"status": "WARNING",
			"last_status_change": 1473947019,
			"last_updated": 1473947019,
			"next_update": 1473947079,
			"update_every": 60,
			"calc":"$used * 100 / ($avail + $used)",
			"calc_parsed":"(($used * 100) / ($avail + $used))",
			"warn":"$this > 80",
			"warn_parsed":"($this > 80)",
			"crit":"$this > 95",
			"crit_parsed":"($this > 95)",
			"green":null,
			"red":null,
			"value":86.1689
		},
```

The above comes from `34@/etc/netdata/health.d/disks.conf` which is the template.

And:

```json
		"disk_space.sdc3.disk_space_usage_bkp": {
			"name": "disk_space_usage_bkp",
			"chart": "disk_space.sdc3",
			"family": "/mnt/backup/hd",
			"active": true,
			"exec": "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/alarm-notify.sh",
			"recipient": "root",
			"source": "71@/etc/netdata/health.d/local_disks.conf",
			"units": "%",
			"info": "current disk space usage",
			"status": "CLEAR",
			"last_status_change": 1473947019,
			"last_updated": 1473947019,
			"next_update": 1473983019,
			"update_every": 36000,
			"calc":"$used * 100 / ($avail + $used)",
			"calc_parsed":"(($used * 100) / ($avail + $used))",
			"warn":"$this > 98",
			"warn_parsed":"($this > 98)",
			"crit":"$this > 99",
			"crit_parsed":"($this > 99)",
			"green":null,
			"red":null,
			"value":86.1689
		},
```

which comes from `71@/etc/netdata/health.d/local_disks.conf`.

The problem is that the later that comes from your file is named `disk_space_usage_bkp`. If it was named `disk_space_usage` it would override the first.

**Comment by jsveiga** [comment]
Thanks, got it. I thought the "alarm:disk_space_usage" would override all
disk_space_usage.*
