### ISSUE TITLE
Build packages for various distributions

### ISSUE THREAD

**Issue by hauleth** [firehol/netdata#94]
It should not be hard using [fpm](https://github.com/jordansissel/fpm).

**Comment by fabfurnari** [comment]
If needed I can help with debian packaging (source/binary package)

**Comment by daveloyall** [comment]
@fabfurnari see #42

**Comment by ktsaou** [comment]
> If needed I can help with debian packaging (source/binary package)

I need help! So, please do!

**Comment by tsumaru720** [comment]
producing packages would be nice, this would make for easier deployment using orchestration (puppet, for example!)

**Comment by hauleth** [comment]
There is also hosted solution which has special offer for [FLOSS](https://packagecloud.io/pricing).

**Comment by mcnewton** [comment]
For Debian see #132 as a start.

**Comment by philwhineray** [comment]
I am going to close this as a duplicate of #87 please continue discussion there,

**Comment by ktsaou** [comment]
Closing it as @philwhineray suggested.
