### ISSUE TITLE
alarm icons should always come from the public registry

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#941]
Private URLs are not routed to slack, pushover, etc.
alarm notification URLs should get their images from the global publicly available registry.

**Comment by ktsaou** [comment]
fix in PR #950.

**Comment by ktsaou** [comment]
merged it

**Comment by stefanvangastel** [comment]
Is there a way I could achieve the opposite? So get the alarm icons from a private URL? I run netdata in an offline on-premise environment..

**Comment by ktsaou** [comment]
> Is there a way I could achieve the opposite? So get the alarm icons from a private URL? I run netdata in an offline on-premise environment..

yes: https://github.com/firehol/netdata/blob/70417d058f73384caee1224c9c729c394834170b/conf.d/health_alarm_notify.conf#L40

**Comment by stefanvangastel** [comment]
Cool, I'm going to give it a try.

**Comment by stefanvangastel** [comment]
Works like a charm. Thanks!
