### ISSUE TITLE
alarm tester script

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#943]
We need an alarm tester script, that will:

1. switch to user netdata
2. call `alarm-notify.sh` with a test alarm

to verify alarms are working on the given host.

**Comment by tperalta82** [comment]
Hey there, there is no need to add a script to do that IMO.
You can probably just add something like this to the wiki in the health-monitoring section:

### Alarm Notifications Testing 
"You can test your alarms by running..... be sure to replace /usr/libexec to your install dir if you have a custom one"
 
```
/usr/libexec/netdata/plugins.d/alarm-notify.sh 'sysadmin' 'debclean' '1475604061' '1475604028' '3' '1475604369' '10min_cpu_usage' 'system.cpu' 'cpu' 'WARNING' 'CLEAR' '83' '80' '2@/etc/netdata/health.d/cpu.conf' '360' '0' '%' 'average cpu utilization for the last 10 minutes'
```
And you do not need to be in the user netdata either, ran it with a regular user and it's working

**Comment by x85446** [comment]
I found this useful...  Please do add it to the wiki...

**Comment by ktsaou** [comment]
This is obsolete information. You can run:

```
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```

**Comment by ktsaou** [comment]
Added it to the wiki: https://github.com/firehol/netdata/wiki/health-monitoring#testing-alarms
