### ISSUE TITLE
Consistent green coloring for "free" (SWAP & RAM)?

### ISSUE THREAD

**Issue by bluepuma77** [firehol/netdata#944]
Free SWAP is green - that makes sense to me.

Free RAM is orange, almost red, that is counter-intuitive to me.

Screenshot: RAM left, SWAP right
![ram-swap](https://cloud.githubusercontent.com/assets/5221187/18472687/337ebae6-79b9-11e6-9a1b-8f3a8cf6b6e1.png)

Can I change that via configuration or does it need to be changed in the code?

**Comment by ktsaou** [comment]
you are right. I'll do it later today.

**Comment by ktsaou** [comment]
fixed it. It is not merged yet. I am fixing a few more issues and I'll merge it.
Thanks for reporting it!

**Comment by ktsaou** [comment]
In PR #950. Will be merged tomorrow.

**Comment by ktsaou** [comment]
merged the fix

**Comment by bluepuma77** [comment]
Perfect, thanks.
