### ISSUE TITLE
frequent alarms switches spam with notifications

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#945]
The biggest problem with alarms today is for cases where the alarm switch states all the time.
For example, we have an alarm where:

```
every: 10s
warn: $this > 70
crit: $this > 90
```

Let's assume the alarm changes values from 69.9 to 70.1 every 10s. We are going to get a lot of alarms.
The same will happen if the value changes from 89.9 to 90.1.

I am trying to find a way to avoid them.

Any ideas are welcome...

cc: @davidak

**Comment by ktsaou** [comment]
one way is to delay notifications for X amount of time, only when the alarm is demoted (i.e. CRITICAL->WARNING, CRITICAL->CLEAR, WARNING->CLEAR).

This could be a configuration option, for example:

```
delay: 1h
```

would delay the dispatch of the demoted alarm notification for 1h.

**Comment by ktsaou** [comment]
@paulfantom, @philwhineray  if you have any ideas, please join...

**Comment by ktsaou** [comment]
I see there are 3 strategies:

1. filter notifications based on level (e.g. mute warnings)

  it would be nice if we could filter the alarms in `alarm-notify.sh`, so that each role or destination address could have each own setting.

2. delay notifications of escalated alarms

  this is used in hope the alarm will go off soon.

3. delay notification of demoted alarms

  this is used to avoid alarms that are switching state all the time.


2 and 3 could be implemented in netdata with a configuration like this:

```
flap: up 1m down 10m multiplier 1.5 max 1h
```

The above defines that escalation changes would be delayed by 1 minute and demotions by 10 minutes. If a state switch occurs within the delayed period, the delays should be multiplied 1.5, up to 1 hour.

**Comment by paulfantom** [comment]
Another approach would be implementing some sort of hysteresis.

**Comment by ktsaou** [comment]
> Another approach would be implementing some sort of hysteresis.

example? I thought these delays are hysteresis...

**Comment by ktsaou** [comment]
I made some changes to support this:

```
delay: up 1m down 10m multiplier 1.5 max 1h
```

and added such definitions to all alarms. Let's see if it is going to be any better.

**Comment by paulfantom** [comment]
> example? I thought these delays are hysteresis...

I wouldn't call them hysteresis, since they are just delays. I thought about implementation based not on time series but on value. Like triggering alarm on `$this > 70` and then waiting for it to drop down to let's say `$this < 65` before allowing for next alarm to be sent. The best part is that it can be combined with time-based solution.

**Comment by ktsaou** [comment]
ok. Probably I am biased with the hysteresis word (I am Greek and hysteresis or "υστέρηση" in Greek means "delay").

I tried hard to find an easy way to adapt the thresholds. However, since warning and critical conditions are expressions, you cannot just check the value.

To support something like this, it would require for netdata to have expressions for:

- `clear-from-uninitialised`
- `clear-from-warning-or-critical`
- `warning-from-critical`
- `warning-from-clear`
- `critical-from-warning-or-clear`

There is also an `undefined` state internally that is used when the database lookup gave no value, or when the `calc` expression gave `NaN` or `INF`.

Too complex... (to understand and describe).

Another solution was to use the `?` operator of expressions and make netdata offer a way to examine the current status of the alarm. Like:

```
warn: (CRITICAL OR WARNING) ? ($this > 75) : ($this > 80)
crit: (CRITICAL) ? ($this > 85) : ($this > 90)
```

So that the `warn` condition for example, if the alarm is CLEAR, it will use `$this > 80`, but if it is WARNING or CRITICAL it will use `$this > 75`. 

Sure, we can add something like that...

**Comment by ktsaou** [comment]
PR #950 added for notification delays

**Comment by ktsaou** [comment]
merged it

**Comment by paulfantom** [comment]
I agree it would be over complicated. However this looks nice:
> ```
warn: (CRITICAL OR WARNING) ? ($this > 75) : ($this > 80)
crit: (CRITICAL) ? ($this > 85) : ($this > 90)
```

 :+1:

**Comment by ktsaou** [comment]
ok I did it in PR #952 , like this:

```
warn: ($status >= $WARNING) ? ($this > 75) : ($this > 80)
```
