### ISSUE TITLE
netdata - network interface - no graphs unless something using it ?

### ISSUE THREAD

**Issue by w1bble** [firehol/netdata#947]
I'm monitoring some SPAN ports in unused interfaces and can't understand why netdata was reporting no data when no application was using it (doesn't netdata see data on up interfaces not doing anything?)

I started tcpdump to test and netdata started graphing, stop tcpdump and the graph flatlines showing nothing.

Bug or other issue?

I can replicate if needs be and provide any background info (base 64bit unbuntu 16.04 system with broadcom cards)

**Comment by ktsaou** [comment]
netdata is trying to save some memory on your server. So, it just skips interfaces that their usage counters are zero. Check this config (comes from `/etc/netdata/netdata.conf`:

```
[plugin:proc:/proc/net/dev]
	# filename to monitor = /proc/net/dev
	# enable new interfaces detected at runtime = auto
	# enable ifb interfaces = no
	# bandwidth for all interfaces = auto
	# packets for all interfaces = auto
	# errors for all interfaces = auto
	# drops for all interfaces = auto
	# fifo for all interfaces = auto
	# compressed packets for all interfaces = auto
	# frames, collisions, carrier counters for all interfaces = auto
```

`auto` = **enable the relative charts, only if the collected metrics are non-zero**.

So, netdata by default shows interfaces and charts for the interfaces (it also does this for many more metrics, like disks, firewall data, qos, etc), only if they are used. Of course, once enabled, netdata will continue to present the collected information, even if the interface is not used any more.

**Comment by ktsaou** [comment]
and note that you can set these values per interface too.

**Comment by ktsaou** [comment]
Keep in mind that:

1. for new charts to appear on the dashboard you have reload the page on your browser (i.e. hit F5). No need to restart netdata itself.

2. alarms will be automatically attached to new charts. For example, there is an alarm that is triggered when an interface is dropping packets. Until that chart is enabled there is no alarm for it. But once the chart is enabled, the alarm is also automatically activated and triggered.

**Comment by w1bble** [comment]
nope, the netdata graph showed nothing unless an app / process was/is using the interface.
if I stop the service using it netdata graphs dropped back to zero.

**Comment by ktsaou** [comment]
May be I didn't understand the problem.

What netdata does, is that it does not show the charts at all, if all their metrics are zero. Once at least a packet reaches the interface, a reload of the dashboard will show the charts for this network interface.

You say that the charts are shown and while there is an application using the interface you see values at the dashboard, but if you stop the application using the network interface, the charts although are still there, they show zero values. Then, what is the problem? If no one is using a network interface, the charts should show zero values.

Am I missing something?

**Comment by w1bble** [comment]
![screen shot 2016-09-14 at 10 00 23](https://cloud.githubusercontent.com/assets/9034546/18506146/66de7bf2-7a62-11e6-8889-d7451ebf3779.png)
![screen shot 2016-09-14 at 10 01 35](https://cloud.githubusercontent.com/assets/9034546/18506147/66df0e28-7a62-11e6-84d6-c76efcef1a81.png)

I stopped the application using eno3 & eno4 and the network speed indicates nothing passing (it's a span port so constant traffic).

Is this really expected behaviour?

**Comment by w1bble** [comment]
(in the second graph I restarted my application hence it shows traffic passing again)

**Comment by ktsaou** [comment]
Sorry... I forgot to follow up this.

Well, this has nothing to do with netdata. These are the values exposed by the linux kernel. So, I don't know if this is expected or not.

I am not an expert on port spanning, but I would find it strange if the switch is mirroring traffic when no one is receiving it. I don't know though. This is just a guess...

**Comment by ktsaou** [comment]
Cleaning up: I am closing this, but if you believe there is a fault in netdata (or anything netdata can do to help), post here and I'll open it again.
