### ISSUE TITLE
named stats doesnt work on bind 9.9 (debian jessie)

### ISSUE THREAD

**Issue by Scrasa** [firehol/netdata#948]
(doesn't know if it's a bug or feature request ...)
Debian jessie give bind9 9.9.5
Apparently on 9.9, the statistics-channel on json doesn't exist. More the stats on xml exist only on v2, not v3. You must compil bind9 with directive "--enable-newstats" to support v3 (as explained : https://ftp.isc.org/isc/bind9/cur/9.9/doc/arm/Bv9ARM.ch06.html#statschannels ). Unfortunatly debian jessie (stable) seems not using --enable-newstats ...

More, the "/server" parameter on url doesn't work on bind 9.9.
So configuring netdata with named.conf only work with :

            "url": "http://localhost:8888/xml/v2",

And the netdata give the following error :

/usr/lib/x86_64-linux-gnu/netdata/node.d/named.node.js:137
        var len = d.server.counters.length;
                          ^
TypeError: Cannot read property 'counters' of undefined
    at Object.named.xml2js (/usr/lib/x86_64-linux-gnu/netdata/node.d/named.node.js:137:27)
    at named.processResponse (/usr/lib/x86_64-linux-gnu/netdata/node.d/named.node.js:185:27)
    at /usr/lib/x86_64-linux-gnu/netdata/node.d/node_modules/netdata.js:232:5
    at IncomingMessage.<anonymous> (/usr/lib/x86_64-linux-gnu/netdata/node.d/node_modules/netdata.js:105:8)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by ktsaou** [comment]
unfortunately netdata does not support xml/v2. Only xml/v3. I think the main problem with xml/v2 is that it always produces a huge XML output. This makes both named and node.js parser in netdata use a lot of CPU. So, I decided when I was writing this, that there is no point to support it.

If you update your named, everything will work...

**Comment by Scrasa** [comment]
Thanks for your reply
Continue what you do, netdata is a great tool.

Le 2016-09-13 19:01, Costa Tsaousis a écrit :
> unfortunately netdata does not support xml/v2. Only xml/v3. I think
> the main problem with xml/v2 is that it always produces a huge XML
> output. This makes both named and node.js parser in netdata use a lot
> of CPU. So, I decided when I was writing this, that there is no point
> to support it.
> 
> If you update your named, everything will work...
