### ISSUE TITLE
Not listing all drives for disk_space.xxxx

### ISSUE THREAD

**Issue by mspk7305** [firehol/netdata#949]
Dell T430 server, has a 1tb at /dev/sda and a pair of 250gig ssd drives at /dev/sdb and /dev/sdc
mounted in fstab at boot with 
/dev/sdb1    /media/ssd1    ext4    defaults    0    1
/dev/sdc1    /media/ssd2    ext4    defaults    0    1

I am able to get read and write data for the drives, and am able to get disk_space.sda1 but disk_space.sdb1 and disk_space.sdc1 do not seem to generate.

**Comment by ktsaou** [comment]
interesting!

Can you post your `/proc/diskstats` and `/proc/self/mountinfo` ?

**Comment by mspk7305** [comment]
[mountinfo.txt](https://github.com/firehol/netdata/files/470889/mountinfo.txt)
[diskstats.txt](https://github.com/firehol/netdata/files/470890/diskstats.txt)

**Comment by ktsaou** [comment]
even more interesting. The values are there.

Could you please also post your `netdata.conf`? I need you to take it from netdata, like this: `http://your.netdata:19999/netdata.conf`. This one will show us which disks netdata found.

**Comment by mspk7305** [comment]
[netdata.conf.txt](https://github.com/firehol/netdata/files/470945/netdata.conf.txt)

**Comment by mspk7305** [comment]
Not sure if this helps but here is the output of /api/v1/charts as well
[api.v1.charts.txt](https://github.com/firehol/netdata/files/470950/api.v1.charts.txt)

**Comment by mspk7305** [comment]
so the mount point was owned by a user rather than root, chowned to root & restarted netdata, can get info on disk space now. 
 
thanks!

**Comment by ktsaou** [comment]
I am confused. Is the issue solved? Shall we close this?

**Comment by mspk7305** [comment]
Here is what I observed:
 
The disks sdb1 and sdc1 were mounted in two different locations, you can see that in the info attached above. netdata was looking to the mount owned by ethosadmin, getting a permission denied message, and giving up. once I unmounted that location and restarted netdata, it was able to read the intended mount location which the netdata account has access to.  
 
It is working now. Thanks!!
