### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by ben29** [firehol/netdata#95]
checking for sin in -lm... yes
./configure: line 4929: syntax error near unexpected token `newline'
./configure: line 4929: `	PKG_CHECK_MODULES('

**Comment by justincm** [comment]
I commented out in the configure.rc file the following line


> if test "${enable_plugin_nfacct}" = "yes"; then
>  PKG_CHECK_MODULES(
>  NFACCT,
>  libnetfilter_acct,
>  )
>  PKG_CHECK_MODULES(
>  LIBMNL,
>  libmnl,
>  )
>  test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
>  test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5
> 
> $as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
>  OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
>  OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"
> 
> fi
>  if test "${with_zlib}" = "yes"; then
>  PKG_CHECK_MODULES(
>  ZLIB,
>  zlib,
>  )
>  test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5
> 
> $as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
>  OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
>  OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
>  fi

then reran the ./netdata-installer.sh --zlib-is-really-here

now running

**Comment by ben29** [comment]
yea i did it.
but next commit or next change
i need to it over and over again

**Comment by justincm** [comment]
You are editing the configure.ac file right?

I made the change there and it remain persistent. 

If you change the configure file it will change each time you run the installer because it uses the .ac file to build the configure file

**Comment by Ismael** [comment]
Try installing pkg-config

**Comment by justincm** [comment]
it is installed on my system

I do get this in the install 

./configure: line 3940: PKG_PROG_PKG_CONFIG: command not found

**Comment by paulfantom** [comment]
Is this still an issue?

**Comment by ktsaou** [comment]
I think not. I am closing it. If it still is, please post.

**Comment by kachkaev** [comment]
I just faced the same strange issue on one of the machines with Ubuntu. After a short investigation, it turned out that `pkg-config` was not installed. Don't ask why, I did not set up that server :–) Got things fixed this way:

```bash
sudo apt-get install pkg-config
```

Could `pkg-config` be checked by the pre-install script if this can't have any unwanted side-effects?

**Comment by ktsaou** [comment]
The pre-installation script already checks all packages:

```sh
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
```

Check the installation wiki page: https://github.com/firehol/netdata/wiki/Installation

Did you use this?

**Comment by kachkaev** [comment]
That's what I ran first like on any other machines. The script did install a bunch of things, but not `pkg-config` for some reason. Sorry for not explaining this clearly @ktsaou.

Strange that `pkg-config` was not installed for me despite that it is mentioned in that shell script. If the same thing happens again on another machine, I'll investigate and share the logs. If anyone else ends up on this page with the same error, please copy the results of your pre-install (prepare) script and the details of your OS.

**Comment by ktsaou** [comment]
Could you please append ` -i` to the command line?

This will make the script ignore packages found to be installed and suggest to install all the packages it detects as needed.

So, if you run it with ` -i` does it attempt to install `pkg-config`?

**Comment by kachkaev** [comment]
I'm not able to check this any more unfortunately. Now everything is installed and netdata is working well (just like on any other machines, where I did not face this problem).

I'll add to this thread if I see the same error message. Thanks so much @ktsaou for your diligence and care in investigating user's issues! This is a very pleasant, but a not very commong thing to see on github!

**Comment by ktsaou** [comment]
ok, thanks!
