### ISSUE TITLE
process cmdline from API

### ISSUE THREAD

**Issue by vincus** [firehol/netdata#953]
Is it possible to query the running processes cmdline via API call ?

**Comment by ktsaou** [comment]
I am not sure I understand the question.

In general netdata exposes only statistics / metrics. Which information are you looking for?

**Comment by vincus** [comment]
I aware that netdata only exposes metrics, however netdata already collects
process information and some information is chopped. What I am trying to
achive - as netdata is being installed on all of our servers - is we would
collect a typical "ps axu" output from all of our machines in every 10
seconds. As netdata already has this info just chopping it out I wonder is
it possible to get the process cmdline (like: java -xxx.jar -XmX4000m blah
blah). This way we would eliminate the need to install additional data
collection modules on our servers

**Comment by ktsaou** [comment]
I see. Unfortunately no, this cannot be done with netdata. The process tree is crawled by `apps.plugin` which sends to netdata only aggregated metrics. I would also consider this information a security issue if exposed by netdata.

I am thinking of adding a process watchdog in netdata. Something that you could say "I want to watch over this process" and netdata will automatically add a series of alarms for it (is it running? does it have open sockets? Is its memory usage stable (does it have a memory leak)? is it swapping? does it use a log of I/O?, etc).

There are two ways to do it: extend apps.plugin or use systemd cgroups. I am still researching about the optimal way this would work though (so, don't expect to see it soon).
