### ISSUE TITLE
Monitor bandwidth for multiple hosts

### ISSUE THREAD

**Issue by mulletman87** [firehol/netdata#954]
This looks fantastic! 

I want to run it on a Linux gateway and monitor the bandwidth usage of multiple hosts on a per IP basis. 

Keeping in mind that the network is made up of smart phones, tablets, laptops, etc, is this possible?

I would be monitoring an interface destined for the WAN. Overall bandwidth is useful but definitely bandwidth per host.

Thanks

**Comment by ktsaou** [comment]
Unfortunatelly this information is not exposed by the kernel.
There are a few solutions that install special kernel modules to sniff the traffic and break down the traffic per IP.

I normally use QoS for that. That is classify the traffic into the traffic you want, and then monitor QoS classes with netdata.

You can use FireQoS for that.

**Comment by mulletman87** [comment]
Thanks @ktsaou for the response.

I was looking at it for awhile, especially the post on doing it per application but I didn't think it would help me because I was more interested in simply monitoring per IP bandwidth.

So to clarify, if I ran FireQOS on my linux gateway, that would expose the source IPs that are going through it (automatically). I could then just apply the same priority to all traffic, but in doing so, I would have a classification per IP address. 

Then within netdata (also installed on the linux gateway), I would monitor that classification (if there were 20 hosts, there will be 20 classifications if I understand correctly) and it could appear on the right (e.g. 192.168.0.50, etc.), kinda like it's shown in the image below.

![image](https://cloud.githubusercontent.com/assets/22201235/18550204/e806defe-7b52-11e6-865a-8fb27f874269.png)

Ideally, if I add another three tablets into the network, it would be epic if they were classified and added to the dashboard automatically.

Am I making sense here?

Thanks :)

**Comment by ktsaou** [comment]
Something like that.
To avoid having hundreds of dimensions on the charts, you could configure your dhcp server to provide IPs from a subnet to all devices of each user or team. So you could have classes like `user1`, `user2`, etc or even `accounting`, `development`, `marketing`, `legal`, etc.

**Comment by mulletman87** [comment]
That makes sense! 

Is it possible for netdata to read from a netflow source or maybe iptables logs?

If it is done via FireQoS, is there a way to autoclassify them based on the hostname that is sending the traffic through the linux gateway? For example, if three IP addresses come through eth0, it will do a reverse netbios lookup for each one to get the device name, which will be the class name used and created in FireQoS.

Then, if netdata monitors the FireQoS classes, will it display like the image above (on the right), with something like "laptop-mulletman", "pc-mulletman" and "phone-mulletman", with a pretty much hands off approach.

I will probably have to hire someone to do this for me but I want to know what is possible first hehe.

At the end, I just want to be able to add random hosts to the network, have them push their data through a linux gateway and have a way to monitor how much bandwidth each one is using in a graphical way. And my word, netdata graphs look AMAZING so I am hoping that this can be done.

Thanks for your time, I really appreciate it.

**Comment by ktsaou** [comment]
> Is it possible for netdata to read from a netflow source or maybe iptables logs?

currently no, but there is a plugin API available where everyone can write data collection modules.

> If it is done via FireQoS, is there a way to autoclassify them based on the hostname that is sending the traffic through the linux gateway? For example, if three IP addresses come through eth0, it will do a reverse netbios lookup for each one to get the device name, which will be the class name used and created in FireQoS.

FireQoS is a wrapper for `tc`. `tc` is layer-3. So, unfortunately no. However, the `tc-qos-helper.sh` has an API to netdata to rename dimensions. So, they can be collected as IPs and named to whatever. This is how it already works for FireQoS (`tc-qos-helper.sh` collects `tc` statistics, even if not configured by FireQoS, but if it is FireQoS, it also collects class names from a run-time directory in `/var/run` maintained by FireQoS).

It is doable, but I think a chart with 256 dimensions will be slow for your browser, so the magic of netdata might be lost. I would prefer to have something like `joe`, `mary`, `servers`, `guests`, or even `desktops`, `laptops`, `tablets`, `phones`, `guests`. This can be done by subneting the dhcp responses, with FireQoS and netdata. No code.

**Comment by ktsaou** [comment]
And by the way for my home I prefer something like `voip`, `interactive` (games, ssh, dns, etc), `vpns`, `servers`, `surfing`, `background`. I can't see which client is doing it, but I do have a clue of what is happening. I can prioritise this traffic too.

**Comment by mulletman87** [comment]
Thanks for the responses and explanation.

Regarding your last message, I absolutely love that. I seem to recall seeing a dashboard like that (think it was on the FireQoS pages) but I ruled it out because I figured it could only be done when data is being collected FROM each host (meaning that something would need to be installed on them, which is an issue for phones, etc).

Are you suggesting that I could collect this kind of info (classify AND combine totals) for all video traffic (as an example) going through my Linux gateway?

And then shape all video traffic (optionally of course), regardless of the computer/tablet/iPhone that it's coming from?

That.. would.. be.. beyond.. awesome!!

**Comment by ktsaou** [comment]
this is what I do.

**Comment by mulletman87** [comment]
Wow that is legit! 

Could I be a bother and use the same config, dashboard, classifications, etc that you currently have running at your home, provided it doesn't contain anything sensitive?

I know it's being a little lazy but at least it will get things up and running quickly, then I could always tweak it as I pour over the wiki.

Maybe something like Dropbox zip or something? I would appreciate it so much, I don't mind paying you for your trouble. 

Been looking for a solution for almost a full year and this is even better than I originally planned.

Thanks so much!

**Comment by ktsaou** [comment]
My home config is the FireQoS tutorial: https://github.com/firehol/firehol/wiki/FireQOS-Tutorial
I have made little adaptations since then...

**Comment by ktsaou** [comment]
For servers, I use adaptations of this: https://github.com/firehol/netdata/wiki/You-should-install-QoS-on-all-your-servers#setup-qos-the-right-way

**Comment by mulletman87** [comment]
Test

Thank you, I will look over it with a fresh set of eyes tomorrow morning. 

I just have one more question.

I am routing traffic (destined for the WAN) from my DSL router to a Linux box. Once the traffic arrives and is processed, it routes it back to the DSL router and it proceeds out to the WAN (there are iptable rules to prevent loops).

The only catch it that it's all done on a single interface, so I have created two sub interfaces, one on the DSL router subnet range and the other on the client facing subnet range. 

To your knowledge, would this cause issues with FireQoS? I am thinking that it could count data twice or something to that effect? I have used tools like darkstat, etc and they didn't have that problem but obviously fireQoS is doing things much differently.

Thanks

**Comment by ktsaou** [comment]
What you are interested is only the traffic from/to the router. So, you can have QoS at 100Mbps or 1Gbps at the interface and a subclass at 20Mbps for the router traffic only matching traffic from/to the router. It will be tricky since the src/dst of packets cannot be used. You have to MARK the packets in iptables.

There are a few alternatives, like: VLANs if you have switch that can do it, switching the router to bridge mode so that you run PPPoE on your linux (this is how I do it, so that I have eth0 for my lan and ppp0 for the internet), or even buying a USB ethernet card to connect the router to your linux.

Read the tutorial, the manuals and experiment a bit.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this for now.

**Comment by mulletman87** [comment]
Thank you @ktsaou. I apologize for the delayed response (and for opening the thread again) but I just wanted to show my appreciation for your guidance. I have chatted to my dev buddy and he has agreed to write a plugin to pull data from a package called "iptraf" and graph the results using the API. Although this means that I cannot use the QoS method immediately (which I am still keen for, still weighing up my options), it will serve its purpose, especially on a small >10 device network.

Just for anyone else who needs it, iptraf can output data like this:

Wed Apr 25 23:08:42 2012; UDP; eth0; 65 bytes; from 192.168.1.20:45061 to 192.168.1.254:53
Wed Apr 25 23:08:42 2012; UDP; eth0; 133 bytes; from 192.168.1.254:53 to 192.168.1.20:45061
Wed Apr 25 23:08:43 2012; UDP; eth0; 96 bytes; from 192.168.1.21:137 to 192.168.1.20:137
Wed Apr 25 23:08:44 2012; UDP; eth0; 472 bytes; from 192.168.1.21:1900 to 239.255.255.250:1900

I am not 100% sure if building the plugin will be easy but I suppose that depends on the skill of the developer. I will make sure it is available for others when it is done.

Thanks!

**Comment by sagar-chandarana** [comment]
@mulletman87 Wondering if this plugin you guys planned to build is ready?

**Comment by sagar-chandarana** [comment]
@ktsaou would you please provide some guidance over how to modify `tc-qos-helper.sh` to extract bandwidth info per source IP? Another graph of destination IP would be required as well. So two graphs.

Our use case is that we have VPN servers with 100+ users on each. Each user is bound to particular 'Exit IP' on the server, for them to have a static IP when they access internet. We want to see how each IP (and thus user) is using the bandwidth.

**Comment by ktsaou** [comment]
@sagar-chandarana use fireqos.

You can set something like this in `/etc/firehol/fireqos.conf`:

```sh
# generate the fireqos bidirectional interface
interface eth0 world bidirectional balanced rate 1gbit minrate 100kbit

# loop 255 times (I assumed 1 class C for all users)
for x in {1..255}
do
   # add a class per user
   class user${x}

   # match the traffic for this user
   # this matches the source IP of packets, at the input
   # and the opposite at the output (i.e. the destination IP of packets)
   # I assumed the IP of all users is 10.1.1.${x}
   match input src 10.1.1.${x}
done
```

Of course adapt it to your needs. You can also name the classes by the user names or use any IP (no need for a common class-C).

Start it with `fireqos start`.

Then restart netdata and it will now monitor all the classes.

Note that the above will also balance the traffic of all the users. No one will be able to monopolize the bandwidth, no matter how many sockets he opens.

---

another solution is to compile netdata with `--enable-plugin-nfacct` and run it as root (edit `/etc/systemd/system/netdata.service`). You will have the nfacct plugin.

Then, you can use your iptables firewall to configure accounting (NFACCT) for each of your users.

You will get something like this:
![screenshot from 2017-12-08 21-21-02](https://user-images.githubusercontent.com/2662304/33781551-bbc5e070-dc5d-11e7-838e-d4e696c54264.png)

**Comment by sagar-chandarana** [comment]
@ktsaou perfect. So fireqos.conf is basically a bash script? What I am wanting to ask is, how much programmable can it be? It would be great if we are able to fetch a list of IPs from a remote source with curl
thank you for such a detailed and helpful response

**Comment by ktsaou** [comment]
It can do whatever bash can do. It is a plain simple common bash script (I am talking about `fireqos.conf` - fireqos itself is also a bash script, but its config is too).

**Comment by jult** [comment]
So, did anyone yet accomplish per LAN IP traffic usage monitoring for netdata yet? We're at nftables now, and 7 years along, and still this is not a feature I see anywhere, a simple listing of top traffic usage to/from the internet for, let's say, a basic debian 12 router doing NAT, charting the top users per selected timeslot. Amazed by how hard to find this is. I have tried literally several dozens of tools for this, but none do what once was done by bandwidthd, but excludes LAN to LAN traffic and pushes out a simple graphic visualization of it. So we can pin down which LAN IP uses up all traffic with our ISP.

**Comment by ilyam8** [comment]
Hey, @jult. There are ways to do it. For instance, you can:

- create [nfacct objects](https://manpages.ubuntu.com/manpages/trusty/man8/nfacct.8.html).
- use iptables to match whatever and use iptable's `nfacct` extension to specify the existing object name that will be used for accounting the traffic that this rule-set is matching.
- Netdata's [nfacct](https://github.com/netdata/netdata/tree/master/src/collectors/nfacct.plugin) plugin will collect bytes/packets for every `nfacct` object.
