### ISSUE TITLE
[question] Is planned a version for Open WRT or DD-WRT so we can monitor our routers?

### ISSUE THREAD

**Issue by chronossc** [firehol/netdata#955]

**Comment by ktsaou** [comment]
Have you checked https://github.com/firehol/netdata/issues/651 ?

**Comment by chronossc** [comment]
Oh nop, I did not saw it. Sorry.
Maybe is nice to refer the link in the README or update it's description of supported systems :)?

**Comment by ktsaou** [comment]
I added a reference to issue #651 at the installation wiki page.
Thanks!
