### ISSUE TITLE
Literal IPV6 addresses confuse the registry

### ISSUE THREAD

**Issue by codl** [firehol/netdata#956]
If I connect to netdata with a literal IPv6 address in the URL, like [http://[::1]:19999/](http://[::1]:19999/), the registry cuts it off at the opening bracket and only saves `http://`

After that, the my-netdata menu item for that machine sends me to about:blank until i manually open it with another address

```
GET https://registry.my-netdata.io/api/v1/registry?action=access&machine=XXXXXXXX-2272-11e6-8618-bc5ff49a7415&name=ugu.tao.codl.fr&url=http%3A%2F%2F%5B%3A%3A1%5D%3A19999%2F

{
	"action": "access",
	"status": "ok",
	"hostname": "london.my-netdata.io",
	"machine_guid": "79dd9dbc-189e-11e6-904a-0401d1165f01",
	"person_guid": "YYYYYYYY-3d85-492e-97a9-1c55031f0b7e",
	"urls": [
		[ "XXXXXXXX-2272-11e6-8618-bc5ff49a7415", "http://", 1473878768000, 1, "ugu.tao.codl.fr" ]
	]

}
```

**Comment by ktsaou** [comment]
hm... this seems a javascript problem. Let me check...

**Comment by ktsaou** [comment]
No it is not... this is must be a very old bug. When I was testing swagger I noticed it passes arrays with `[...]`, so I had used them in query string separators.

I am fixing it now.

**Comment by ktsaou** [comment]
I made PR #952 that fixes it, but this requires updating netdata on the registry. I need to do some more testing, so please give me 1-2 days until the registry is updated.

**Comment by ktsaou** [comment]
merged it and updated the registry too.

**Comment by codl** [comment]
Fantastic, thank you for such a fast fix!
