### ISSUE TITLE
Spec file references 1.3.1 but doesn't exist, breaks RPM BUILD

### ISSUE THREAD

**Issue by bgulla** [firehol/netdata#957]
The netdata.spec.in currently refers to http://firehol.org/download/netdata/releases/v1.3.1_master/ but that does not currently exist. This breaks the ability to build an RPM without modifying the spec file.

**Comment by ktsaou** [comment]
You are right. This is what the git version currently says.
What should  it say? The git version is `1.3.1_master`, where `_master` means 'not released yet'.
The released files have their own version.

**Comment by ktsaou** [comment]
Cleaning up. I am closing this, but if you have a suggestion, please post and I'll re-open it.
