### ISSUE TITLE
EasyPieCharts color changing regarding value

### ISSUE THREAD

**Issue by DrGkill** [firehol/netdata#958]
Is it possible to change the color regarding the value with easy pie charts ?

Like they do hear but directly with the netdata options ?

http://stackoverflow.com/questions/21862290/how-can-i-change-bar-color-of-jquery-easypiechart

Thanks !

**Comment by ktsaou** [comment]
I remember I have done this for gauge charts... let me check...

yes, I did: https://github.com/firehol/netdata/blob/3294c3db55012477a51e5fc2baf4f2c50c3b47e7/web/dashboard.js#L5121-L5122

And based on the stackoverflow example, I think you can do it with netdata too:
https://github.com/firehol/netdata/blob/3294c3db55012477a51e5fc2baf4f2c50c3b47e7/web/dashboard.js#L4914

something like this:

```
<div ... data-easypiechart-barcolor="function (percent) { return (percent < 50 ? '#5cb85c' : percent < 85 ? '#f0ad4e' : '#cb3935');}" ...></div>
```

Can you try it?

**Comment by ktsaou** [comment]
If it does not work, I'll try to do something for this...

**Comment by DrGkill** [comment]
Hi ktsaou ! 
Thanks for the reply. Unfortunately it does not work. It shows no bar at all.

**Comment by ktsaou** [comment]
ok, I'll give it a try...

**Comment by ktsaou** [comment]
ok, fixed that. You have to define the function like this:

```html
<div ... data-easypiechart-barcolor="(function (percent) { return (percent < 50 ? '#5cb85c' : percent < 85 ? '#f0ad4e' : '#cb3935');})" ...></div>
```

i.e. the whole function needs to be enclosed in parentheses.
