### ISSUE TITLE
How to monitor (automaounted) nfs-io? /nfsiostat

### ISSUE THREAD

**Issue by snoopotic** [firehol/netdata#959]
Hi,
I use automounter to mount NFS drives in my network unter /net/ ...
How can I monitor these io stats of NFS drives (esp. readdir & getattr)?

**Comment by ktsaou** [comment]
the linux kernel exposes NFS statistics via `/proc/net/rpc/nfsd` on the NFS server. Netdata already provides this information.

You want them on the client. Let me check...

I see there is `/proc/net/rpc/nfs`. They seem similar. I can make a PR to collect them too.

**Comment by snoopotic** [comment]
This would be nice.
Thank you.

**Comment by ktsaou** [comment]
I added PR #968 that provides NFS Client statistics.

If you use NFS v4, I need your help. I haven't verified that NFS v4 is collected properly (the values are collected, but I am not sure their labels are right).

**Comment by ktsaou** [comment]
merged it.
