### ISSUE TITLE
Custom dashboard compatibility with jQuery 3.0

### ISSUE THREAD

**Issue by jbelien** [firehol/netdata#962]
Hi guys,

I tried to add a "custom dashboard" in my page which uses jQuery 3.0 ; the error is the following : 

> TypeError: $.ajax(...).success is not a function

[line 5555 of _dashboard.js_]

Indeed, the methods `success`, `error` and `complete` were renamed to `done`, `fail` and `always`. See JQuery Core 3.0 Upgrade Guide : https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax

Thanks for the good work, **netdata** is awesome !

**Comment by ktsaou** [comment]
I thought I fixed it. The fix in PR #964.
Thanks for reporting it!

**Comment by ktsaou** [comment]
merged it.
