### ISSUE TITLE
Tips for auto-update ?

### ISSUE THREAD

**Issue by UltimateByte** [firehol/netdata#965]
Hi,

I'm glad to see frequent updates, but a bit sad to see that i'm outdated every day !
Do anybody have some tips about how to run netdata auto-updates ?

I can easily think of a script to run as a cronjob, that would git pull netdata, then it would have to detect if there was an update to decide whether or not to run the installer.
Maybe git is returning a value if some files are updated, if so, the according piece of code would amazing.

I'd be more than happy to add interesting tips (if any) to the wiki.

Cheers :beers: 

PS : Best monitoring tool ever, thanks for it.

**Comment by ktsaou** [comment]
In PR #966, `netdata-installer.sh` now generates `netdata-updater.sh` which you can run either interactively or from cron-job.

When running headless (i.e. crontab) the updater will not output anything, unless something failed, so that you will receive an email from crond if it fails.

The updater is re-generated after each successful netdata installation. It maintains all flags and options given to the installer, including the working directory.

I needed something like that to quickly update a lot of servers. So, here it it.

**Comment by ET-Bent** [comment]
in `/usr/local/bin/netdata-update`
```
#!/bin/bash

rm -rf /tmp/netdata/ && cd /tmp/ && git clone https://github.com/firehol/netdata.git --depth=1 && cd netdata && echo -ne '\n' | ./netdata-installer.sh --install /opt
```

in your crontab add:

```
# update netdata
0 6 * * * /usr/local/bin/netdata-update
```

That's what we have been using for half a year now, nice to know that there is a script shipped with netdata now.

Big thanks to @ktsaou for everything ! :smirk:

**Comment by UltimateByte** [comment]
Awesome guys !

So this needs to be argemented with the new update system & cronjob info:
https://github.com/firehol/netdata/wiki/Installation#updating-netdata-after-its-installation

```
You can update netdata to the latest version by getting into netdata.git you downloaded before and running:

# go to the git downloaded directory
cd /path/to/git/downloaded/netdata

# download the latest version
git pull

# rebuild it, install it, run it
./netdata-installer.sh
The installer will also restart netdata with the new version.
```

**Comment by ktsaou** [comment]
Thanks, I updated the wiki.

**Comment by UltimateByte** [comment]
You've been faster than me (was editing it in a turtle way after testing) :p 
I will be able to shorten this explanation without losing any information and add a cronjob example. Hold on for it. 

The only little problem with this netdata-update.sh, is that it will run the installer again even if there was no update. For example, say you want to run it every 6 hours, then four netdata interruptions will occur each day while there was maybe fewer updates than that

**Comment by ktsaou** [comment]
every 6 hours? ok....

It could do a `git log | grep ^commit | head -n 1 | cut -d ' ' -f 2` to get the latest commit before and after the `git pull`. If it is the same, no update has been made.

**Comment by ktsaou** [comment]
wait a moment. I will fix it.

**Comment by UltimateByte** [comment]
I said every 6 hours because it's me, but i'm pretty sure some people will want every hour or so. :o))

Awesome if you fix it :)

I'm figuring out a way to make it simple on the wiki.

**Comment by ktsaou** [comment]
Ok. I am testing it.

Keep in mind we should encourage people to update software like that using a crontab. Things can always goes wrong and a suggestion to automatically update it via cron puts a lot of stress on me to be very careful what I commit on this repo. A bad commit and things can go crazy...

**Comment by ktsaou** [comment]
should **NOT** of course I meant...

**Comment by ktsaou** [comment]
ok. it is in PR #969
waiting for travis-ci to finish to merge it.

**Comment by UltimateByte** [comment]
OK, i'll add a comment about the risks.

**Comment by ktsaou** [comment]
merged

**Comment by UltimateByte** [comment]
Tested out, works perfectly !

I think i'm happy with the wiki now, hopefully you are too !
https://github.com/firehol/netdata/wiki/Installation#updating-netdata-after-its-installation

**Comment by ktsaou** [comment]
Looks nice! Thank you!

**Comment by UltimateByte** [comment]
My pleasure !
Thanks a lot for that awesome netdata-updater.sh addition !
Adopted instantly !

At LGSM we like cronjobs ! https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs
The least day to day maintenance i do, the happier i am !

Cheers 
:beers:
