### ISSUE TITLE
errno 98 and FATAL: netdata: Cannot listen socket

### ISSUE THREAD

**Issue by shivdhwaj** [firehol/netdata#97]
Got into these errors:

> /usr/sbin/netdata
> 16-03-31 16:56:53: ERROR: netdata: IPv6 bind() failed. (errno 98, Address already in use)
> 16-03-31 16:56:53: ERROR: netdata: IPv4 bind() failed. (errno 98, Address already in use)
> 16-03-31 16:56:53: FATAL: netdata: Cannot listen socket. # : Success

OS - Ubuntu 14.04 LTS

**Comment by ktsaou** [comment]
It is already running, or something else is running on port 19999 (you can set it on the config file). But check it is not already running. The installer starts it automatically.

**Comment by shivdhwaj** [comment]
Its running on the Browser 
Nothing is running on the specified port.

**Comment by ktsaou** [comment]
ok, run this to find if it is running:

```sh
ps fax | grep netdata
```

and this to see if something is having port 19999:

```sh
netstat -nat  | grep 19999
```

You can start netdata on another port by running:

```sh
netdata -p 9999
```

**Comment by shivdhwaj** [comment]
Its running fine and I am able to see the results.

Does errors may cause the real data?

**Comment by ktsaou** [comment]
> Does errors may cause the real data?

Sorry. I don't understand this.

**Comment by arush-sal** [comment]
@shivdhwaj What is the port number you are using on your browser ? If it is 19999, then can you share the result of `ps fax | grep netdata` and `netstat -atnp  | grep netdata`.

As, I was facing the same issue but as @ktsaou pointed it out, that was just because another instance was running.

**Comment by shivdhwaj** [comment]
@arush-sal  Please find the attached screen-shot of the command's result:
![issue dump](https://cloud.githubusercontent.com/assets/4490787/14197436/04caff06-f7ec-11e5-9ad2-dbf694be6be9.png)
@ktsaou  
> Does errors may cause the real data?

I want to ask if this error which is coming on the  terminal will cause any issue or incorrect data that is being generated.
Will the error lead to wrong data that is being show on the application?

**Comment by ktsaou** [comment]
> Will the error lead to wrong data that is being show on the application?

no. If it is running, your data are ok.

**Comment by DavePS** [comment]
When the installation is completed, netdata will be automatically be executed...

**Comment by ktsaou** [comment]
shall we close this? I understand your issue is solved. Yes?

**Comment by shivdhwaj** [comment]
:) :+1:
