### ISSUE TITLE
python.d.plugin does not get NETDATA_CONFIG_DIR

### ISSUE THREAD

**Issue by bbbenjie** [firehol/netdata#971]
Hi guys, I'm having an issue with python.d.plugin.
Since it cannot get the environmental variable NETDATA_CONFIG_DIR (= None), CONFIG_DIR is pointing to /etc/netdata/.
This path is wrong as soon as you install netdata in a different directory using ./netdata-installer.sh --install /different/path

`CONFIG_DIR = os.getenv('NETDATA_CONFIG_DIR', "/etc/netdata/")`

https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L23

**Comment by ktsaou** [comment]
> Since it cannot get the environmental variable NETDATA_CONFIG_DIR

Are you sure? netdata passes this environment variable to its plugins. How did you verified it?
If you run the plugin by hand, you have to set it yourself.

**Comment by paulfantom** [comment]
Line `CONFIG_DIR = os.getenv('NETDATA_CONFIG_DIR', "/etc/netdata/")` in `python.d.plugin` works as it should, it grabs `NETDATA_CONFIG_DIR` environment variable and sets python global variable `CONFIG_DIR`. When `NETDATA_CONFIG_DIR` isn't set, `CONFIG_DIR` is set to default value of "/etc/netdata/".

**Comment by bbbenjie** [comment]
Sorry, this was a false alarm while debugging my mysql issue.
I forgot to set NETDATA_CONFIG_DIR to the corresponding dir when running `/path/to/netdata/usr/libexec/netdata/plugins.d/python.d.plugin debug mysql`

Thanks for your fast responses :-)
