### ISSUE TITLE
Cannot read /proc/net/snmp IcmpMsg line. Expected 12 params, read 3.

### ISSUE THREAD

**Issue by ufergus** [firehol/netdata#976]
Cannot read /proc/net/snmp IcmpMsg line. Expected 12 params, read 3.

I am now getting this error after updating today.  Looks to be coming from this commit.

d05bc3cb8eb4d5d2e5e3328a19447d4b8177421e

My /proc/net/snmp shows this for line IcmpMsg

IcmpMsg: InType3 OutType3
IcmpMsg: 2293 2746

**Comment by ktsaou** [comment]
which kernel version you use?

**Comment by ktsaou** [comment]
I am fixing it. It seems the columns included are not fixed.

**Comment by ktsaou** [comment]
ok. I rewrote the whole module. Now it parses the header lines it finds in the file.
Preparing a PR...

**Comment by ktsaou** [comment]
merged the fix.
Thanks for reporting it!
