### ISSUE TITLE
clearos 6.7 and centos 6 - packages installer failed

### ISSUE THREAD

**Issue by JasonBee** [firehol/netdata#979]
The experimental packages installer failed.

This is what it says:

``` txt

Press ENTER to run it > ENTER
yum install autoconf-archive autogen libmnl-devel libuuid-devel lm_sensors MySQL-python nodejs python-yaml zlib-devel 
Loaded plugins: clearcenter-marketplace, fastestmirror
Setting up Install Process
ClearCenter Marketplace: fetching repositories...
Loading mirror speeds from cached hostfile
 * atomic: www5.atomicorp.com
 * clearos: mirror1-frankfurt.clearos.com
 * clearos-addons: mirror1-frankfurt.clearos.com
 * clearos-centos: download3.clearsdn.com
 * clearos-centos-updates: download3.clearsdn.com
 * clearos-extras: mirror1-frankfurt.clearos.com
 * clearos-fast-updates: download3.clearsdn.com
 * clearos-updates: mirror1-frankfurt.clearos.com
 * contribs: download3.clearsdn.com
 * epel: mirror.steadfast.net
 * private-clearcenter-dyndns: download1.clearsdn.com:80
No package autoconf-archive available.
No package autogen available.
Package libmnl-devel-1.0.3-4.el6.art.x86_64 already installed and latest version
Package libuuid-devel-2.17.2-12.18.el6.x86_64 already installed and latest version
Package PyYAML-3.10-7.el6.art.x86_64 already installed and latest version
Package zlib-devel-1.2.3-29.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package MySQL-python.x86_64 0:1.2.3-0.3.c1.1.el6 will be installed
---> Package lm_sensors.x86_64 0:3.1.1-17.el6 will be installed
--> Processing Dependency: lm_sensors-libs(x86-64) = 3.1.1-17.el6 for package: lm_sensors-3.1.1-17.el6.x86_64
--> Processing Dependency: lm_sensors-libs(x86-64) = 3.1.1-17.el6 for package: lm_sensors-3.1.1-17.el6.x86_64
--> Processing Dependency: libsensors.so.4()(64bit) for package: lm_sensors-3.1.1-17.el6.x86_64
--> Processing Dependency: libsensors.so.4()(64bit) for package: lm_sensors-3.1.1-17.el6.x86_64
---> Package nodejs.x86_64 0:0.10.46-1.el6 will be installed
--> Processing Dependency: libuv.so.0.10()(64bit) for package: nodejs-0.10.46-1.el6.x86_64
--> Running transaction check
---> Package libuv.x86_64 1:0.10.34-1.el6 will be installed
---> Package lm_sensors-libs.x86_64 0:3.1.1-17.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
```

I've got the following repos active
- atomic: www5.atomicorp.com
- clearos: mirror1-frankfurt.clearos.com
- clearos-addons: mirror1-frankfurt.clearos.com
- clearos-centos: download1.clearsdn.com
- clearos-centos-updates: download1.clearsdn.com
- clearos-extras: mirror1-frankfurt.clearos.com
- clearos-fast-updates: download1.clearsdn.com
- clearos-updates: mirror1-frankfurt.clearos.com
- contribs: download1.clearsdn.com
- epel: mirror.steadfast.net
- private-clearcenter-dyndns: download3.clearsdn.com:80

**Comment by ktsaou** [comment]
Could you please post the whole output. I really need the header to understand the situation.

**Comment by JasonBee** [comment]
It was simple - should have pointed out the relevant portion:

> No package autoconf-archive available.
> No package autogen available.

There seems to be some chatter about these two packages having been pulled from distribution on fedora/centos. I had to compile autoconf-archive from source. Never found a viable source for autogen. So far I have it working without it.

JB

**Comment by bluepuma77** [comment]
Maybe run it with(in) Docker:
```
docker pull titpetric/netdata
docker rm -f -v netdata # remove old version
docker run \
  --name netdata \
  --restart always \
  --cap-add SYS_PTRACE \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -p 19999:19999 \
  -d titpetric/netdata
```

**Comment by ktsaou** [comment]
@JasonBee I really need the header of the packages installer. I'll have to adapt it so that people using the same distribution as yours will get the right packages to be installed.

Could you please post it?

**Comment by rgarrigue** [comment]
That look like the problem I just got. With CentOS 6 the installer does not work

- netcat is installed with package nc instead of nmap-ncat. You may use '*bin/nc' for compatibility with both I think.
- autogen is available with epel-testing, aka `yum install autogen --enablerepo=epel-testing`
- autoconf-archive rpm isn't available easily, see https://pkgs.org/download/autoconf-archive

Tried removing autoconf_archive stuff from kickstart.sh, it worked.

**Comment by JasonBee** [comment]
Can you elaborate on what else I can provide? What I posted was the *entirety of the setup output from the terminal.

I can try to run it again on a clean build…I also posted the resolution which was to install the two missing packages manually.

The build I am using is a rhel variant named “clearos” 

http://gamblisfx.com/how-to-install-netdata-system-monitoring-on-clearos-7-1/ <http://gamblisfx.com/how-to-install-netdata-system-monitoring-on-clearos-7-1/>

JB

**Comment by JasonBee** [comment]
Reinstalling - grabbed the full terminal output.

[root@gateway ~]# curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
Cannot find /etc/os-release
Cannot find valid distribution with lsb-release
Loading /etc/redhat-release ...
/tmp/kickstart.sh: line 136: Community: command not found
Cannot parse this lsb-release: ClearOS Community release 6.7.0 (Final)

I NEED YOUR HELP
It seems I cannot detect your system automatically.
I found though that the following installers are available:

 - Redhat/Fedora/Centos based (installer is: yum)

To proceed please write one of these: yum: yum 
yum in centos, rhel or fedora? > centos
Checking package manager: yum
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

We detected these:
Distribution    : centos
Version         : 6.7.0
Codename        : Final
Package Manager : install_yum
Packages Tree   : centos
Detection Method: user-input
Default Python v: 2 

The following command will be run:


 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  

yum install autoconf-archive autogen libmnl-devel libuuid-devel MySQL-python python-yaml zlib-devel 


Press ENTER to run it > ENTER
yum install autoconf-archive autogen libmnl-devel libuuid-devel MySQL-python python-yaml zlib-devel 
Loaded plugins: clearcenter-marketplace, fastestmirror
Setting up Install Process
ClearCenter Marketplace: fetching repositories...
Loading mirror speeds from cached hostfile
 * atomic: www5.atomicorp.com
 * clearos: clearos.bhs.mirrors.ovh.net
 * clearos-addons: clearos.bhs.mirrors.ovh.net
 * clearos-centos: download1.clearsdn.com
 * clearos-centos-updates: download1.clearsdn.com
 * clearos-extras: clearos.bhs.mirrors.ovh.net
 * clearos-fast-updates: download1.clearsdn.com
 * clearos-updates: clearos.bhs.mirrors.ovh.net
 * contribs: download1.clearsdn.com
 * private-clearcenter-dyndns: download3.clearsdn.com:80
Webmin                                                                                                                   | 1.0 kB     00:00     
ajenti                                                                                                                   | 2.5 kB     00:00     
atomic                                                                                                                   | 3.4 kB     00:00     
beats                                                                                                                    | 2.9 kB     00:00     
clearos                                                                                                                  | 3.8 kB     00:00     
clearos-addons                                                                                                           | 2.9 kB     00:00     
clearos-centos                                                                                                           | 3.7 kB     00:00     
clearos-centos-updates                                                                                                   | 2.9 kB     00:00     
clearos-extras                                                                                                           | 2.9 kB     00:00     
clearos-fast-updates                                                                                                     | 2.9 kB     00:00     
clearos-updates                                                                                                          | 2.9 kB     00:00     
newrelic                                                                                                                 |  951 B     00:00     
No package autogen available.
Package libmnl-devel-1.0.3-4.el6.art.x86_64 already installed and latest version
Package libuuid-devel-2.17.2-12.18.el6.x86_64 already installed and latest version
Package MySQL-python-1.2.3-0.3.c1.1.el6.x86_64 already installed and latest version
Package PyYAML-3.10-7.el6.art.x86_64 already installed and latest version
Package zlib-devel-1.2.3-29.el6.x86_64 already installed and latest version
Nothing to do

All Done! - Now proceed to the next step.

**Comment by ktsaou** [comment]
ok, I have done all the fixes:

1. assigned clearos to centos
2. netcat installed with package `nc` on centos-6
3. autoconf-archive is not installed

Could you please test it?

**Comment by JasonBee** [comment]
Sorry for the lag - have been monitoring the thread intensively but wasn't logged in to see this update. I will test this now.

FYI I'm spreading news of this to local municipalities (City of Toronto being one where I work, and adding others. These are analytics tools (droids) we were looking for ;)

**Comment by ktsaou** [comment]
nice, thanks!

**Comment by JasonBee** [comment]
1) Wiped net data from my system, and reinstalled.
2) seems to install well, and is left in the running state after install.
3) Still have to install the service by hand, but I understand this is expected [behaviour according the setup docs] (https://github.com/firehol/netdata/wiki/Installation#starting-netdata-at-boot)

Final wrap-up: install from scratch on ClearOS  shows no errors.

BRILLIANT work on this. I'm very very impressed by the final product. 

Sorry I should say stalkerishly impressed.

If you need anything from me log or output-wise let me know. Given how awesome this product is I'm willing to fire up a VM and try a from-scratch install on ClearOS 7 just to confirm.

**Comment by joseluisq** [comment]
@bluepuma77 really amazing !
Works fine with Docker in CentOS 6
https://github.com/titpetric/netdata

**Comment by ktsaou** [comment]
Cleaning up day. I am closing this, but if you have a suggestion or issue, please post and I'll re-open it.
