### ISSUE TITLE
./configure: line 4860: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by roottox** [firehol/netdata#98]
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64 GNU/Linux

./configure: line 4860: syntax error near unexpected token `newline'
./configure: line 4860: `       PKG_CHECK_MODULES('

**Comment by justincm** [comment]
I commented out in the configure.rc file the following line

> if test "${enable_plugin_nfacct}" = "yes"; then
>  PKG_CHECK_MODULES(
>  NFACCT,
>  libnetfilter_acct,
>  )
>  PKG_CHECK_MODULES(
>  LIBMNL,
>  libmnl,
>  )
>  test -z "${NFACCT_LIBS}" && as_fn_error $? "netfilter_acct required but not found" "$LINENO" 5
>  test -z "${LIBMNL_LIBS}" && as_fn_error $? "libmnl required but not found" "$LINENO" 5
> 
> $as_echo "#define INTERNAL_PLUGIN_NFACCT 1" >>confdefs.h
>  OPTIONAL_NFACCT_CLFAGS="${NFACCT_CFLAGS} ${LIBMNL_CFLAGS}"
>  OPTIONAL_NFACCT_LIBS="${NFACCT_LIBS} ${LIBMNL_LIBS}"
> 
> fi
>  if test "${with_zlib}" = "yes"; then
>  PKG_CHECK_MODULES(
>  ZLIB,
>  zlib,
>  )
>  test -z "${ZLIB_LIBS}" && as_fn_error $? "zlib required but not found" "$LINENO" 5
> 
> $as_echo "#define NETDATA_WITH_ZLIB 1" >>confdefs.h
>  OPTIONAL_ZLIB_CLFAGS="${ZLIB_CFLAGS}"
>  OPTIONAL_ZLIB_LIBS="${ZLIB_LIBS}"
>  fi
> 

then reran the ./netdata-installer.sh --zlib-is-really-here

now running

**Comment by roottox** [comment]
thx for fast feedback. gonna test your workaround laters @home.
but isnt it a bug if im already used the option "--zlib-is-really-here" its still checking?

**Comment by insom** [comment]
Hi @roottox / @justincm,

I had this but it was because I was missing pkg-config - can you check if you have all the deps installed?

    gcc make autoconf automake pkg-config zlib1g-dev node curl

**Comment by justincm** [comment]
centos 5 no pkg-config available.

**Comment by insom** [comment]
Hi @justincm - I gave the Ubuntu package names, but `pkgconfig` (with no hyphen) *is* available on CentOS 5. zilb will be `zlib-devel`. You may need to find Node from somewhere else though, it looks like it didn't make it into CentOS properly until CentOS 6, sorry.

**Comment by justincm** [comment]
pkgconfig and zlib0devel both were installed

for node I used this
curl --silent --location https://rpm.nodesource.com/setup | bash -

**Comment by ktsaou** [comment]
node.js is only needed for SNMP and named. If you don't need these plugins, you can skip node.js

**Comment by roottox** [comment]
thanks for feedback, got it running :)

the localized repro from serverprovider didnt know "pkg-config" - shame them...
after changing to offical sources, all went fine. 

Summary:
To start it, just run it:
/opt/netdata/usr/sbin/netdata
Enjoy!

___
uname -a && dpkg-query -l | egrep "gcc|make|autoconf|automake|pkgconfig|zlib1g-dev|node|curl|pkg-config" | awk  {'print $1" "$2'}

Linux blafoo 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64 GNU/Linux

ii autoconf
ii automake
ii automake1.9
ii curl
ii devscripts
ii gcc
ii gcc-4.7
ii gcc-4.7-base:amd64
ii libcurl3:amd64
ii libcurl3-gnutls:amd64
ii libgcc1:amd64
ii make
ii php5-curl
ii pkg-config
ii zlib1g-dev:amd64

**Thx for help. Though my eyes gone to sleepy to catch this in "realtime". **

Thx & best rgds 
rt

/closed
