### ISSUE TITLE
Question about using webserver with netdata on other server

### ISSUE THREAD

**Issue by Codgedodger** [firehol/netdata#983]
Hello,

I'm trying to setup a website where I have a summary of current stats. My webserver is hosted on a wordpress layout. My server is hosted in a different location with obviously a different IP. I can go to IP:19999 on my server with no issues. I'd just like to the users to be able to see the server stats without having to go to the server IP. 

Tried some of the examples of the html codes but nothing is working. I just want this to be shown on the website. 
![capture](https://cloud.githubusercontent.com/assets/14158068/18617854/162b24d2-7da8-11e6-955c-a2c1b03690f9.PNG)

Any examples or walk through someone can help me with? I'd be forever grateful.

**Comment by ktsaou** [comment]
You can proxy netdata through another web server. This means your users will see only your web server, for both netdata and your site. Netdata can run at `http://your.web.server/netdata/` or any other patch you like.

Have you checked the wiki?

**Comment by Codgedodger** [comment]
Yes, but I'm rather new to configuring my nginx. Would I replace the /etc/nginx/sites-enabled/default with 
`upstream backend {
    # the netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
    # nginx listens to this
    listen 10.1.1.1:80;

    # the virtual host name of this
    server_name netdata.example.com;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}`?

**Comment by ktsaou** [comment]
I usually create a new file in `/sites-available/netdata.conf` which I link to `/sites-enabled/netdata.conf`. I don't like touching the default files.

But I don't know either. My nginx configuration know-how is pretty basic.

**Comment by Codgedodger** [comment]
Sorry for simple questions but is this in reference to my proxied webserver? or the local IP of the actual server?

`server_name netdata.example.com`

**Comment by paulfantom** [comment]
You can have multiple server names and `listen` doesn't have to have ip address. So it can be like this:
```
    # nginx listens to this
    listen 80;

    # the virtual host name of this
    server_name netdata.example.com SERVER_IP_ADDRESS;
```
Rest of your config should be ok.

**Comment by Codgedodger** [comment]
Must just be something with my nginx install or something. I have this setup. 

`upstream backend {
    # the netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
    # nginx listens to this
    listen 80;

    # the virtual host name of this
    server_name [Static Public IP], [Internal IP];

    location /netdata {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:19999;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}
`

Then linked with nginx restarted. All I get is a 404 error.

**Comment by paulfantom** [comment]
I adapted my nginx config:
```
upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
    listen 80;
    server_name 169.54.80.94, 10.140.36.50;

    location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;        
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;
    }
```

It should serve netdata on those adresses:
- http://169.54.80.94/netdata 
- http://10.140.36.50/netdata

**Comment by Codgedodger** [comment]
It still doesn't work. Must just be a nginx issue. I'm planning on setting up a next server anyways and will re-apply this to it. Thank you everyone!

**Comment by ktsaou** [comment]
ok. I am closing this. If we can help just comment.
