### ISSUE TITLE
divisor no longer work on system.ipv4

### ISSUE THREAD

**Issue by patschbo** [firehol/netdata#985]
i use the conversion from kb/s to MB/s but since the last update, it doesn`t work any more!
But on with system.io it works still....

i use the following entry on /etc/netdata/netdata.conf

[system.ipv4]
    # history = 3600
    # enabled = yes
    # cache directory = /opt/netdata/var/cache/netdata/system.ipv4
    # chart type = area
    # type = system
    # family = network
    # context = system.ipv4
    # units = kilobits/s
    units = MB/s
    # priority = 500
    # gap when lost iterations above = 1
    # name = system.ipv4
    # title = IPv4 Bandwidth (system.ipv4)
    # dim received name = received
    # dim received algorithm = incremental
    # dim received multiplier = 8
    # dim received divisor = 1024
    dim received divisor = 8388608
    # dim sent name = sent
    # dim sent algorithm = incremental
    # dim sent multiplier = -8
    # dim sent divisor = 1024
    dim sent divisor = 8388608

**Comment by ktsaou** [comment]
I had a few dimensions renamed.

Internally netdata supports 2 names for each dimension: `id` and `name`.

I had re-worked the `/proc/net/snmp` and `/proc/net/netstat` collectors to support new features.
The old `id`s are now `name`s.

So, just download the latest `netdata.conf` from netdata and apply the new divisor to the new dimensions.

Sorry of the inconvenience... and yes I know I should find a better way to change the units of charts...

**Comment by patschbo** [comment]
Yes, it works again!
Thanks!
