### ISSUE TITLE
High CPU usage of python.d.plugin, even with all python plugins disabled

### ISSUE THREAD

**Issue by hashworks** [firehol/netdata#987]
[As you can see here](https://fb.hash.works/ZAPxaf/) `/usr/lib/netdata/plugins.d/python.d.plugin` has quite a high CPU usage.

This is the case even when I disable all python plugins:
```
$ cat /etc/netdata/python.d.conf
enabled: no
logs_per_interval: 200
log_interval: 3600
apache: no
apache_cache: no
cpufreq: no
dovecot: no
example: no
exim: no
hddtemp: no
ipfs: no
memcached: no
mysql: no
nginx: no
nginx_log: no
phpfpm: no
postfix: no
redis: no
sensors: no
squid: no
tomcat: no
```

BTW, I only have this on one of my servers. Any idea how I could debug this a bit?

**Comment by ktsaou** [comment]
hm... I guess only the python version could affect this.
@paulfantom could you please check this?

**Comment by hashworks** [comment]
I just tried this with python 2.7 and python 3.5, same result.

**Comment by hashworks** [comment]
Closing this for now. It seems like my testing was flawed and somehow it ignored my settings. I tested again and I tracked it down to the phpfpm plugin now. I think the problem are multiple TLS encrypted status pages. I'll check.

**Comment by paulfantom** [comment]
@hashworks looks like your CPU doesn't support something like AES-NI.

**Comment by hashworks** [comment]
@paulfantom Yeah it's an old server I rented. I'll upgrade it sooner or later.
