### ISSUE TITLE
How to enable Nginx python plugin?

### ISSUE THREAD

**Issue by shadycuz** [firehol/netdata#993]
Hey guys, 

I have nginx stub_status working and can browse to it. I have enabled python.d in the netdata.conf, I have enabled nginx in the python.d.conf and I have properly configured nginx.conf. After restarting netdata I still don't see it in the gui. Am I missing something? Do you have to configure a chart manually? 

Thanks,

Edit: just to make sure I ran the update script. Now I have an Example Charts in my menu... even though in python.d.conf example : no 

I'm getting this
A random number (example.python_random)

but still no nginx =/

**Comment by shadycuz** [comment]
16-09-20 11:03:33: python.d INFO: Disabled nginx_log
charts.d: 'nginx' is NOT enabled. Add a line with nginx=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
16-09-20 11:07:50: INFO: netdata: executing command: 'exec /usr/libexec/netdata/plugins.d/cgroup-name.sh 'lxc_nginx'' on pid 26708.
/usr/libexec/netdata/plugins.d/cgroup-name.sh: cgroup 'lxc_nginx' is called 'lxc_nginx'
16-09-20 11:07:50: python.d ERROR: nginx_localipv4 <urlopen error [Errno 111] Connection refused>


when I go to the charts config it says
# OLD MODULES THAT ARE NOW SERVED BY python.d.plugin

do they need enabled? I'm currently working on the connection refused error

**Comment by shadycuz** [comment]
Okay final update, I can wget the page so I do have access to it from the netdata box (its a container same machine).

The error in the log now is.

16-09-20 11:25:14: python.d ERROR: nginx_RemoteNginx HTTP Error 404: Not Found
16-09-20 11:25:14: python.d ERROR: nginx_RemoteNginx check function failed.

config is 


update_every : 10
priority     : 90100

RemoteNginx:
  name : 'Nginx Proxy'
  url     : 'http://XXXXXXX.co/nginx_status'
  retries : 10

I still have the random example charts with example = no

**Comment by paulfantom** [comment]
Did you change anything in `charts.d.conf`? If yes, please revert those changes to default state from netdata repository.
Python configuration files should follow YAML syntax (indentations with space), does your files follow it? It should look like this:
```yaml
update_every : 10
priority : 90100

RemoteNginx:
  name : 'Nginx Proxy'
  url : 'http://XXXXXXX.co/nginx_status'
  retries : 10
```
Also you should have line `nginx: yes` in `python.d.conf` file.

About example chart, it can be enabled in `charts.d.conf` or in `python.d.conf`, make sure it is disabled in both files by setting appropriate key to `no`.

**Comment by ktsaou** [comment]
The default configuration files shipped with netdata should do it for `localhost`.

If you need to add more nginx servers, possibly at remote hosts, append to the nginx configuration something like this:

```
remotehost1:
  url  : 'http://remotehost1/stub_status'

remotehost2:
  url  : 'http://remotehost2/stub_status'
```

You can add as many as you like. The `name` parameter is used to name them differently, if you don't like `remoteserverX`, or you want to have mutually exclusive configurations (like the default).

For `name`, please use something without spaces.

**Comment by shadycuz** [comment]
@paulfantom I think I had a space in front of the example: no, I copied the python.d.conf from the git repo to my install directory and that solved it. 

@paulfantom  @ktsaou 

Still haveing issues with the nginx python plugin. I have fixed the syntax. I had url (lots of spaces)      : "myurl" but even after fixing I have errors in the netdata log file.

```
16-09-20 22:12:11: python.d ERROR: nginx_RemoteNginx HTTP Error 404: Not Found
16-09-20 22:12:11: python.d ERROR: nginx_RemoteNginx check function failed.
```

Does it have to be example.com/stub_status, I have 'mydomain.co/nginx_status' 

I have this after all the local ones

```
RemoteNginx:
  name : 'Nginx_Proxy'
  url : 'http://my-domain.co/nginx_status'
  retries : 10

```

**Comment by shadycuz** [comment]
Got it to work, it's hard coded somewhere in the Nginx python plugin to be "/stub_status" it can't be anything else. I was using "/nginx_status". How can I contribute to the wiki? I'm rather new to github but I would like to clear some things up in the documentation for beginners like me.

**Comment by ktsaou** [comment]
> it's hard coded somewhere in the Nginx python plugin to be "/stub_status" it can't be anything else. I was using "/nginx_status".

I don't see it hardcoded: https://github.com/firehol/netdata/blob/master/python.d/nginx.chart.py

Is it possible this to be hardcoded in nginx? Did you test it with `curl`?

**Comment by shadycuz** [comment]
@ktsaou 

I did not net with curl but I could wget it when it was /nginx_status but the plugin would not work. Once I changed it to /stub_status it worked fine after restarting netdata.

**Comment by paulfantom** [comment]
@shadycuz it "stub_status" isn't hardcoded anywhere in netdata, are you sure your nginx configuration is ok?

**Comment by shadycuz** [comment]
It's working great, I'll change it back to nginx_status tonight to see if
it works.

**Comment by shadycuz** [comment]
Current working config
```
RemoteNginx:
  name : 'Reverse_Proxy'
  url  : 'http://64.137.226.113/stub_status'
  retries : 10
```

trying 
```
RemoteNginx:
  name : 'Reverse_Proxy'
  url  : 'http://64.137.226.113/nginx_status'
  retries : 10
```
```
current working nginx config 
    location /stub_status {
        # Turn on nginx stats
        stub_status on;
        # I do not need logs for stats
        access_log   on;
        # Security: Only allow access from 192.168.1.100 IP #
        allow 64.137.167.7;
        # Send rest of the world to /dev/null #
        deny all;
   }

```
trying
```
    location /nginx_status {
        # Turn on nginx stats
        stub_status on;
        # I do not need logs for stats
        access_log   on;
        # Security: Only allow access from 192.168.1.100 IP #
        #allow 64.137.167.7;
        # Send rest of the world to /dev/null #
        #deny all;
   }


And it works. I'm not sure why it didn't the first time when I could wget it but the plugin wouldn't work. I'm using a different server then before. I was using ubuntu 14.04 now 16.04. It could also be that before I was using a URL now I'm using IP address. 




```

**Comment by sLuvpreet33** [comment]
I am facing trouble in activating python.d plugin . Here are my files https://bpaste.net/show/8fc380ea8a2a

What am I doing wrong ?

**Comment by ktsaou** [comment]
Retries handles the number of retries in case nginx is not responding.

Test your nginx:

```
wget 'URL'
```

It should work, otherwise your nginx configuration is wrong.

**Comment by naritasaxena** [comment]
im trying to enable nginx on netdata but its not working for me. Saw many examples followed all and below is what i added in ngnix.conf and its accessible through curl/wget as well:
`RemoteNginx:
  name : 'Nginx'
  url  : 'http://host:8082/stub_status'
  retries : 10`

the only thing which is different is port none of the examples show. Is it possible to fetch from different port on the remote host?

**Comment by ktsaou** [comment]
@naritasaxena  when using curl you should get something like this:

```sh
# curl 'http://127.0.0.1/stub_status'
Active connections: 32
server accepts handled requests
 266198 266198 402306
Reading: 0 Writing: 1 Waiting: 31
```

These few numbers are everything netdata needs from nginx.
You should also enable the `web_log` plugin. Make sure it has access to your `access.log` file.

**Comment by naritasaxena** [comment]
@ktsaou yes with curl i do get to see
 <Active connections: 1 
server accepts handled requests
 10474653 10474653 20757415 
Reading: 0 Writing: 1 Waiting: 0 >

enabled web_log plugin as well but no luck.
still cant see Nginx on netdata. :(

**Comment by l2isbad** [comment]
@naritasaxena  check "verify netdata plugin" part
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by naritasaxena** [comment]
@l2isbad looks like its fetching from nginx correctly but i dnt see on UI.
`bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug nginx
2017-05-08 04:09:00:  INFO: Using python v2
2017-05-08 04:09:00:  INFO: YAML output is ordered
2017-05-08 04:09:00: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-05-08 04:09:00: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['nginx']
2017-05-08 04:09:00: python.d DEBUG: nginx: loading module configuration: '/etc/netdata/python.d/nginx.conf'
2017-05-08 04:09:00: python.d DEBUG: nginx: reading configuration
2017-05-08 04:09:00: python.d DEBUG: nginx/RemoteNginx: job added
2017-05-08 04:09:00: python.d DEBUG: nginx/localipv4: job added
2017-05-08 04:09:00: python.d DEBUG: nginx/localipv6: job added
2017-05-08 04:09:00: python.d DEBUG: all job objects [<Service(RemoteNginx, initial daemon)>, <Service(localipv4, initial daemon)>, <Service(localipv6, initial daemon)>]
2017-05-08 04:09:00: python.d INFO: CHECKED OK: nginx_RemoteNginx
2017-05-08 04:09:00: python.d INFO: RENAMED: nginx_Nginx , from nginx_RemoteNginx
2017-05-08 04:09:00: python.d ERROR: nginx_localipv4 HTTP Error 404: Not Found
2017-05-08 04:09:00: python.d ERROR: nginx_localipv4 check() failed - disabling job
2017-05-08 04:09:00: python.d ERROR: DISABLED: nginx/localipv4
2017-05-08 04:09:00: python.d ERROR: nginx_localipv6 <urlopen error [Errno -2] Name or service not known>
2017-05-08 04:09:00: python.d ERROR: nginx_localipv6 check() failed - disabling job
2017-05-08 04:09:00: python.d ERROR: DISABLED: nginx/localipv6
2017-05-08 04:09:00: python.d DEBUG: overridden job names: ['nginx_Nginx']
2017-05-08 04:09:00: python.d DEBUG: all remaining job objects: [<Service(Nginx, initial daemon)>]
CHART nginx_Nginx.connections '' 'nginx Active Connections' connections 'active connections' nginx.connections line 60000 1
DIMENSION active active absolute 1 1
CHART nginx_Nginx.requests '' 'nginx Requests' requests/s requests nginx.requests line 60001 1
DIMENSION requests requests incremental 1 1
CHART nginx_Nginx.connection_status '' 'nginx Active Connections by Status' connections status nginx.connection_status line 60002 1
DIMENSION reading reading absolute 1 1
DIMENSION writing writing absolute 1 1
DIMENSION waiting idle absolute 1 1
CHART nginx_Nginx.connect_rate '' 'nginx Connections Rate' connections/s 'connections rate' nginx.connect_rate line 60003 1
DIMENSION accepts accepted incremental 1 1
DIMENSION handled handled incremental 1 1

CHART netdata.plugin_pythond_nginx_Nginx '' 'Execution time for nginx_Nginx plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

2017-05-08 04:09:00: python.d DEBUG: created charts for nginx_Nginx
2017-05-08 04:09:00: python.d DEBUG: nginx_Nginx starting data collection - update frequency: 1.0  retries allowed: 10
2017-05-08 04:09:00: python.d DEBUG: nginx_Nginx sleeping for 0.510937929153 secs to reach frequency of 1.0 secs, now: 1494230940.49  next: 1494230941.0  penalty: 0
BEGIN nginx_Nginx.connections 0
SET active = 1
END 
BEGIN nginx_Nginx.requests 0
SET requests = 20757418
END 
BEGIN nginx_Nginx.connection_status 0
SET reading = 0
SET writing = 1
SET waiting = 0
END 
BEGIN nginx_Nginx.connect_rate 0
SET accepts = 10474656
SET handled = 10474656
END 

BEGIN netdata.plugin_pythond_nginx_Nginx 0
SET run_time = 2
END

2017-05-08 04:09:01: python.d DEBUG: nginx_Nginx nginx_Nginx updated in 2 ms
2017-05-08 04:09:01: python.d DEBUG: nginx_Nginx sleeping for 0.996836900711 secs to reach frequency of 1.0 secs, now: 1494230941.0  next: 1494230942.0  penalty: 0
BEGIN nginx_Nginx.connections 1000500
SET active = 1
END 
BEGIN nginx_Nginx.requests 1000500
SET requests = 20757419
END 
BEGIN nginx_Nginx.connection_status 1000500
SET reading = 0
SET writing = 1
SET waiting = 0
END 
BEGIN nginx_Nginx.connect_rate 1000500
SET accepts = 10474657
SET handled = 10474657
END 

BEGIN netdata.plugin_pythond_nginx_Nginx 1000500
SET run_time = 2
END

2017-05-08 04:09:02: python.d DEBUG: nginx_Nginx nginx_Nginx updated in 2 ms
2017-05-08 04:09:02: python.d DEBUG: nginx_Nginx sleeping for 0.996426105499 secs to reach frequency of 1.0 secs, now: 1494230942.0  next: 1494230943.0  penalty: 0
BEGIN nginx_Nginx.connections 999997
SET active = 1
END 
BEGIN nginx_Nginx.requests 999997
SET requests = 20757420
END 
BEGIN nginx_Nginx.connection_status 999997
SET reading = 0
SET writing = 1
SET waiting = 0
END 
BEGIN nginx_Nginx.connect_rate 999997
SET accepts = 10474658
SET handled = 10474658
END 

BEGIN netdata.plugin_pythond_nginx_Nginx 999997
SET run_time = 2
END

2017-05-08 04:09:03: python.d DEBUG: nginx_Nginx nginx_Nginx updated in 2 ms
2017-05-08 04:09:03: python.d DEBUG: nginx_Nginx sleeping for 0.996504068375 secs to reach frequency of 1.0 secs, now: 1494230943.0  next: 1494230944.0  penalty: 0`

**Comment by naritasaxena** [comment]
Thanks Guys it worked. I had to enabled python.d, and chart.d in netdata.conf. Somehow they were disabled in my configurations.

**Comment by Avik1993** [comment]
I am facing a similar issue with Nginx.
Even though nginx stub_status seem to work but 'web_log' plugin seems to be disabled.
Error.log says that the plugin is disabled..
Can it be the issue of log format mismatch?

**Comment by ilyam8** [comment]
Hi @Avik1993 

> Error.log says that the plugin is disabled..

please show error.log
