### ISSUE TITLE
Example Chart appears even though python.d.conf example= no

### ISSUE THREAD

**Issue by shadycuz** [firehol/netdata#994]
Happened after updating to a1b1ad434ba481ac736a68950ad31bb9fd22cf4c

I brought this up in my post about nginx python plugin but decided to bring this up here for clarity.

**Comment by ktsaou** [comment]
Just installed the latest version of netdata at http://bangalore.netdata.rocks/
I don't see this problem.

In your `/etc/netdata` directory there must be files:

1. ending with `*.conf`, these are the currently used files
2. ending with `*.old`, these should be the same with `*.conf` and are a backup made during the last time you installed netdata
3. ending with `*.orig`, these are the original files, as shipped with netdata.

Check them. You must have misconfigured something.

**Comment by shadycuz** [comment]
I copied the original back, I think I had several spaces in front of example: no that caused it.

**Comment by ktsaou** [comment]
Is this solved? Can we close it?

**Comment by shadycuz** [comment]
Yes, I think it was white space issue. Do you need help cleaning up old issues?

**Comment by ktsaou** [comment]
> Do you need help cleaning up old issues?

Thanks! I need help for everything actually. I think I just cleaned them up though. The others have to stay. 90% of them are enhancements...

**Comment by shadycuz** [comment]
Well let me know what you need done. I would rather have you developing
then worrying about maintenance
